### ISSUE TITLE
MRTK 2.7 - Quest 2 - Cannot Move Camera

### ISSUE THREAD

**Issue by mkemka** [microsoft/MixedRealityToolkit-Unity#10004]
## Describe the bug

The camera is spawned in a seemingly random position and cannot be moved. It can be moved when the scene is played but not before.

## To reproduce

1. Using Unity 2020.3, Quest 2, MRTK 2.7
2. Import the toolkit into a scene and set up the camera.
3. Change the position of the camera
3. Run the scene.

## Expected behavior

Expect the camera to spawn in the location that the Main Camera is set to.
Can see that a MRTK_Quest_OVRCameraRig(Clone) is created as the camera but I can't seem to work out how to find where this is created.

**Comment by RogPodge** [comment]
When deploying to XR devices, the device drivers will assume control over camera location based on the user moving about their world / boundary. This is because it is super weird to have the scene's initial position be offset from reality, so it will always try to initialize the playspace to the origin and properly align the camera with respect to that.

This is why we try to reinitialize the camera and playspace to the proper position when running in editor, to best match the experience of deploying on device.

**Comment by mkemka** [comment]
Thanks for the reply - this makes sense and I am sorry for the basic question.

Currently I am using the Quest in stationary boundary so the experience is sitting down. For some reason the spawn point is [0,-20, 0] (under the floor) and it does't change regardless of if I set the main camera to be [0, 0, 0] or update the transform upon creation. This seems like a very basic question so I apologise if I am missing something in the documentation. 

How can I set the camera to spawn at a certain position in the playspace?

**Comment by RogPodge** [comment]
Is your playspace configured to be centered at the origin? Any displacement between the camera and the playspace may cause issues when the scene is started.

In addition, can you check your Mixed Reality Scene Content object to make sure things aren't getting positioned in unexpected places

![image](https://user-images.githubusercontent.com/39840334/122839007-0bda5d00-d2ac-11eb-85b7-c600e12ab5e2.png)

As well as the experience settings

![image](https://user-images.githubusercontent.com/39840334/122839098-3f1cec00-d2ac-11eb-99d1-c49c86d2389f.png)

This configuration spawned the camera at 0,0,0 for me

**Comment by RogPodge** [comment]
Small ping on if you have enough info to proceed and we can close this issue @mkemka

**Comment by mkemka** [comment]
Sorry - thank you so much for the follow-up. I am still having the same issue and found if I enter inverse co-ordinares (-20 instead of 20 on the x axis for example) it does position the camera as long as I select both the camera and the playspace. I will start a new project and test the above.

**Comment by RogPodge** [comment]
Looping back around on this issue and pinging to see if it's still a problem @mkemka
