### ISSUE TITLE
SpatialMapping has offset

### ISSUE THREAD

**Issue by Zod-** [Microsoft/MixedRealityToolkit-Unity#1001]
I've been using spatial mapping in a recent project and I'm having an issue with the position of the mesh. It is not aligned with the real world for me.
![20170921_182746_hololens 1](https://user-images.githubusercontent.com/5775094/30707619-55b204a6-9efc-11e7-8bac-c8bda828208c.jpg)

Are there any reasons this can happen? Where can I begin to debug this. Note that I'm using the v1.5.8.0 as I'm required to use Unity 5.6.X for this project.

**Comment by StephenHodgson** [comment]
@Zod- the current master branch should support U5.6, if you wanna use the latest features. This might be something that could have been fixed since 1.5.8

**Comment by Zod-** [comment]
Ok thanks then I'll give that a try. I'm only using the SpatialMapping part and some utilities anyway since I'm dependant on the MRDesignLab events with their graphical assets.

**Comment by Subere23** [comment]
Make sure your camera is starting at 0,0,0.  Spatial mapping will be offset if for some reason the camera has moved.

**Comment by Zod-** [comment]
@Subere23 My camera actually had an offset and I removed it last week when I was trying to solve this but it didn't work. I'll try deleting all the cached things and do a clean build.

**Comment by Zod-** [comment]
The offset on the camera was the issue, thanks guys.
