### ISSUE TITLE
The dependencies of MRTK 2.7.1 are wrong

### ISSUE THREAD

**Issue by ikorin24** [microsoft/MixedRealityToolkit-Unity#10019]
## Describe the bug

The dependencies of MRTK 2.7.1 are wrong.

The package which MRTK 2.7.1 depends on is `com.microsoft.mixedreality.toolkit.standardassets %version%` in the following link,
but `%version%` is not valid. So, Unity cannot resolve the dependencies and the installation will fail.

https://dev.azure.com/aipmr/MixedReality-Unity-Packages/_packaging?_a=package&feed=Unity-packages&package=com.microsoft.mixedreality.toolkit.foundation&version=2.7.1&protocolType=Npm

For example, an error occurs when installing MRTK 2.7.1 from OpenUPM.

## To reproduce

1. Create a new Unity project. (I used Unity 2019.4.25f1)
2. Execute the following command at the root directory of the project in the terminal. Install the MRTK 2.7.1 via OpenUPM.

```sh
openupm install -r https://pkgs.dev.azure.com/aipmr/MixedReality-Unity-Packages/_packaging/Unity-packages/npm/registry/ com.microsoft.mixedreality.toolkit.foundation@2.7.1
```

3. The installation will fail. OpenUPM sais the error;

```
WARN 404 package com.microsoft.mixedreality.toolkit.standardassets@%version% is not a valid choice of 2.7.1, 2.7.0, 2.7.0-preview.5, 2.7.0-preview.4, 2.7.0-preview.3, 2.7.0-preview.2, 2.6.2, 2.6.1, 2.6.0, 2.6.0-preview.20210220.4, 2.5.4, 2.5.3, 2.5.2, 2.5.1, 2.5.0, 2.5.0-preview.20200928.5, 2.5.0-preview.20200922.2, 2.5.0-preview.20200911.1
notice suggest to install com.microsoft.mixedreality.toolkit.standardassets@%version% or a replaceable version manually
ERR! missing dependencies please resolve thie issue or run with option -f to ignore the warning
```

## Expected behavior

Successful installation.

## Screenshots

![wrong_version_image](https://user-images.githubusercontent.com/19363522/123074121-fef76e00-d451-11eb-88da-4581120d1794.png)

## Your setup

- Unity Version : Unity 2019.4.25f1
- MRTK Version : v2.7.1

## Target platform

Unity editor

**Comment by keveleigh** [comment]
Thanks for the report! We just shipped a 2.7.2 release which fixes this configuration issue and have delisted the broken 2.7.1 release. Please refresh your feed at try out 2.7.2.

Fixed via #10018
