### ISSUE TITLE
Voice chat not working

### ISSUE THREAD

**Issue by meah** [Microsoft/MixedRealityToolkit-Unity#1002]
i added the both script to the main camera and when joined to session and i was able to hear only my voice not the voice of other user that running the app in unity

**Comment by edwinckc** [comment]
Not sure this is the same problem you're having, but hope it helps.

I originally tried placing both MicrophoneTransmitter and MicrophoneReceiver on the camera directly, but I got a warning while running on the HoloLens, about attaching two audio sources? It only attached to one (maybe the Trransmitter script?) and I kept hearing my own echo in voice chat. Creating two empty game objects under the camera, and then adding the trasmitter and receiver scripts to each one respectively, fixed the problem for me. It's not a live stream though, so on a local network I get 0.5s lag and over Azure it's up to 10s lag.

**Comment by mr-mystery** [comment]
MicrophoneTransmitter and MicrophoneReceiver have been removed from the MixedRealityToolkit v.2017.2.0. 
It is mentioned as "Group Voice Chat" feature is given as built in option in Mixedreality Toolkit, but how to implement in a unity project?
What are the new scripts or components need to be added for incorporating Voice Chat?
Tools Used:
Unity Version : Unity 2017.1.2 f1
Toolkit Version : MixedReality Toolkit v.2017.2.0

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
