### ISSUE TITLE
Make it possible to track simple foot gestures

### ISSUE THREAD

**Issue by mangolas** [microsoft/MixedRealityToolkit-Unity#10020]
## Describe the problem

We are building a HoloLens app for drone pilots and most of the time their both hands are tied to controller and they can't use any hand gestures. So the ability to give some very basic commands, like selecting between two options by stepping on them, would be very useful.

## Describe the solution you'd like

A way to track foot in a way that one could look down and be able to step on "button" on ground. So the tracking could be really "low-fi", even the very rudimentary level of tracking would be useful.

## Describe alternatives you've considered

None as we don't know how to add a new tracking feature.

Drone pilots operate on noisy environment and have radios with them, so voice commands are not an option.

## Additional context

None.

**Comment by CDiaz-MS** [comment]
An alternative to step driven input could be eye tracking input.  The eye tracking input entry point does not require hands or voice.  MRTK has eye tracking examples located here (requires a HoloLens2): [Eye Tracking Examples](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/example-scenes/eye-tracking-examples-overview?view=mrtkunity-2021-05)

**Comment by mangolas** [comment]
Yes, that is a good point, and it is in our roadmap to investigate could we utilise eye tracking for giving commands for our use case.

But the use cases for foot behaviour tracking would still in our opinion be an interesting and potentially useful even in wider sense, like for example virtual pedals for guitarists and so on.

**Comment by Zee2** [comment]
Hand tracking is implemented at the hardware/system level on HoloLens 2, and implementing a similar computer vision solution for tracking feet would not be feasible (in my opinion) in Unity without serious performance impact.

As @CDiaz-MS suggested, using eye tracking would be the suggested solution. Specifically, I'd recommend using this pattern: https://docs.microsoft.com/en-us/windows/mixed-reality/design/gaze-and-dwell

Gaze-and-dwell means that UI elements can be selected and confirmed simply by looking at them, and holding the gaze cursor on the element for a certain duration of time.

Given that you are using HoloLens 2 (presumably), you can use https://docs.microsoft.com/en-us/windows/mixed-reality/design/gaze-and-dwell-eyes, which relies on the eye tracking to perform precise eye-gaze-based dwell interactions. If you are on HoloLens 1, eye gaze is not supported, only head gaze, which is detailed here: https://docs.microsoft.com/en-us/windows/mixed-reality/design/gaze-and-dwell-head

**Comment by mangolas** [comment]
Ok, thanks for input and recommendations. Perhaps in HoloLens 3 then :)
