### ISSUE TITLE
(Urgent) Unity 2020.3 + OpenXR: Visual Studio deploys to HoloLens 2 like a desktop application

### ISSUE THREAD

**Issue by FlyingFlambe** [microsoft/MixedRealityToolkit-Unity#10035]
## Describe the bug

Once the project is built and deployed via Visual Studio, HoloLens 2 recognizes the app as if it's a windowed application (e.g. web browser, video player, image viewer, etc). In Unity Holographic Remoting Play Mode, this bug does not occur and plays normally.

## To reproduce

Follow the in the tutorial provided by MRTK:
(1) https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/xr-project-setup?tabs=openxr
(2) https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=openxr

Once the build solution is created and the proper settings in Visual Studio are set (Release, ARM64, etc), the application runs in HoloLens 2 like so.

![error2_HL2build](https://user-images.githubusercontent.com/22328598/123663770-5738c200-d7fc-11eb-9115-00b97de39d9b.gif)

## Expected behavior

When using holographic remoting in play mode, the application works as expected. Note: I need to enable Initialize XR on Startup for desktop in Project Settings for it to work. I assume that I need to enable Initialize XR on Startup for UWP/HoloLens for build, but OpenXR Project Validation throws an error that prevents me from building the VS solution, so I'm forced to fix them (i.e. disable Initialize XR on Startup for both desktop and UWP.

![expected_HL2build](https://user-images.githubusercontent.com/22328598/123669142-666e3e80-d801-11eb-8dce-bae00b994978.gif)

## Your setup

- Unity 2020.3.12f1, URP template
- MRTK v2.7.2
- OpenXR v1.0.0
- Visual Studio 2019 v16.10.2
- Mixed Reality Feature Tool v1.0.2104.4 beta

![image](https://user-images.githubusercontent.com/22328598/123662591-3d4aaf80-d7fb-11eb-976d-593da77b9bf8.png)

## Target platform

- HoloLens 2

## Additional information

Related to: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10037

Also, the error in the gif says:
"A scripted object (probably Microsoft.MixedReality.Toolkit.XRSDK.Oculus.Input.OculusXRSDKDeviceManagerProfile?) has a different serialization layout when loading. (Read 72 bytes but expected 116 bytes.)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?"

There is no custom Oculus setup in the project.

**Comment by FlyingFlambe** [comment]
See issue+comment for fix: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10037#issuecomment-869856207

**Comment by kemykung** [comment]
I have the same problem....How to solve it? Please help me ><
