### ISSUE TITLE
SingleInstance.OnDestroy should be virtual.

### ISSUE THREAD

**Issue by timGerken** [Microsoft/MixedRealityToolkit-Unity#1004]
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/57a18910669daec4f5328480719a66bea04fa2c2/Assets/HoloToolkit/Utilities/Scripts/SingleInstance.cs#L35

OnDestroy should be marked as virtual, otherwise it hijacks my script's ability to handle OnDestroy to do its own cleanup.

**Comment by StephenHodgson** [comment]
Agreed, although I thought it was already virtual.

**Comment by StephenHodgson** [comment]
Hey @timGerken, in the future please be sure to open a Pull Request please, so we can track this better.

Thanks.

**Comment by timGerken** [comment]
sigh, @StephenHodgson , though I was pushing to my fork instead of directly here. Not sure how to undo that action... @keveleigh ?

**Comment by StephenHodgson** [comment]
It's no worries, I've done the same before.
