### ISSUE TITLE
Near Interaction for controllers

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#10057]
## Describe the problem

Currently, near interactions are not enabled by default for controllers due to the near pointers (the poke and grab pointers), only be available for articulated hands

## Describe the solution you'd like

Enable these pointers on motion controllers across the board and ensure that they are usable.

**Comment by MaxWang-MS** [comment]
Is this the same as #9505?

**Comment by RogPodge** [comment]
Yeah it's the same issue, this time with a PR attached :)

**Comment by MaxWang-MS** [comment]
OK, please remember to close the other issue as well when the PR is merged.
