### ISSUE TITLE
MixedRealityKeyboard does not have a method Show()

### ISSUE THREAD

**Issue by janick187** [microsoft/MixedRealityToolkit-Unity#10056]
## Describe the issue
In the documenation it is mentioned that after attaching MixedRealityKeyboard component, the keyboard can be displayed by the `Show()` method. 
However, this component does implement a method called `Show()`:

![missing show metod](https://user-images.githubusercontent.com/43849960/124584068-1b34db00-de54-11eb-8f86-ec0f35278df9.PNG)

## Feature area
No method available to display the keyboard.

## Existing doc link
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/experimental/mixed-reality-keyboard?view=mrtkunity-2021-05

## Additional context
I want the user to enter a passcode.

**Comment by MaxWang-MS** [comment]
Thanks for reporting the issue. The `Show` and `Hide` function in the documentation should actually be `ShowKeyboard(string text = "", bool multiLine = false)` and `HideKeyboard()`. We are in the process of making the doc update. Please note you will not see `ShowKeyboard(string text = "", bool multiLine = false)` in the event dropdown as shown in the screenshot as it has two (optional) parameters. You can write a script with a parameterless function to call `ShowKeyboard()` and then link that function to the event.

**Comment by MaxWang-MS** [comment]
The documentation has been updated.
