### ISSUE TITLE
Preventing Interaction of 3d Objects Behind a 2d Unity Canvas

### ISSUE THREAD

**Issue by seancheno** [microsoft/MixedRealityToolkit-Unity#10054]
## Describe the bug

On our mobile app utilizing MRTK, we have a 2d unity canvas that overlays half the screen. When dragging or clicking on the 2d panel, 3d objects behind it are affected. Have tried many potential fixes including changing the `Pointer Raycast Layer Masks` options in the Input -> Pointers section of the MRTK configurable options, but having no luck. 

## To reproduce

1. Load the `HandInteractionExamples` MRTK demo scene.
2. Create a 2d Unity canvas game object.
3. Add an image child inside the Unity canvas.
4. Drag around and click on the image and notice how interactable 3d objects behind the canvas are moved/affected.

## Expected behavior

Interactions on the 2d Unity canvas should prevent pointers from interacting with interactable objects behind the canvas.

## Screenshots

https://user-images.githubusercontent.com/46169876/124505963-e22f3480-dd87-11eb-9fd9-a55d495443da.mov

## Your setup (please complete the following information)

- Unity version 2019.4.8
- MRTK Version 2.4

## Target platform (please complete the following information)

- Mobile - IOS/Android

**Comment by elbuhofantasma** [comment]
Hello @seancheno, thank you for your Mobile Platform bug submission. I will investigate this issue and then assign it to the appropriate person. I will update this issue when I finish investigating.

**Comment by RogPodge** [comment]
@elbuhofantasma any update on this?

**Comment by seancheno** [comment]
Quick update @elbuhofantasma I posted a thread on the unity [forum](https://forum.unity.com/threads/mrtk-how-to-ensure-clicks-on-2d-unity-canvas-dont-affect-the-3d-objects-behind-it.1136413/). Someone replied saying `Is your canvas in screen space or world space? XR doesn't support screen space UIs, only world space.`

We are using screen space for our canvas and cannot change it, thus are hoping there is a way to have this particular issue solved while still using a screen space unity canvas.

**Comment by seancheno** [comment]
Just wanted to bump this thread and see if a potential fix of workaround to this issue has been found. Thank you.

**Comment by elbuhofantasma** [comment]
Hello @seancheno I apologize for not giving any updates for this long. Some other duties took precedence until now. 

I have not found a workaround just yet, as my investigation paused on this issue paused for a little bit. However starting tomorrow I am putting all of my focus on this repo's issues. This issue is first on my list tomorrow morning.

One suggestion I have to try until I conclude the investigation is to use try the LegacyXR pipeline. This would be a temporary fix as we are recommending Unity 2020 and OpenXR, and LegacyXR is in the process of being deprecated in the MRTK.

**Comment by seancheno** [comment]
Thank you very much for the reply and information. I am eager to see what you uncover after digging into this issue. Your time is greatly appreciated. I will look into the workaround, but am suspecting that with our current setup, switching back to legacy might cause some issues. Thus, really hoping for the best as you dig into this issue.  Will stay tuned.

**Comment by RogPodge** [comment]
Heads up that this issue should be fixed going into MRTK v3

**Comment by RogPodge** [comment]
Closing for now, since raycasts blocking selection is only really feasible when the UI is also in world space. Other confusion points regarding this and the Pointing Raycast Layermasks should be fixed with #10508
