### ISSUE TITLE
SurfaceMagnetism exhibits gimbal locking behavior when an object is placed on a horizontal surface and Orientation Mode is set to Surface Normal

### ISSUE THREAD

**Issue by holomatt** [microsoft/MixedRealityToolkit-Unity#10064]
## Describe the bug

SurfaceMagnetism exhibits gimbal locking behavior when an object is placed on a horizontal surface and Orientation Mode is set to Surface Normal.

## To reproduce

1. Add SurfaceMagnetism and SolverHandler to an object.
2. Enable Spatial Awareness at runtime (holographic remoting works fine)
3. Configure SurfaceMagnetism Orientation Mode to "Surface Normal"
4. Set target on SolverHandler to any horizontal surface (floor, ceiling, table)
5. Trigger the SurfaceMagnetism behavior by proximity to the surface

## Expected behavior

Object orientation does not exhibit gimble locking (snaps back and forth between polar rotations in response to minute changes in the SA mesh's normal.

## Setup

Unity 2020.3, MRTK 2.7.2, WindowsXR SpatialAwareness Observer

**Comment by Zee2** [comment]
Thanks for reporting this! I'll take a look as soon as I can.
