### ISSUE TITLE
Render from PV Camera with the same near plane distance as the main camera

### ISSUE THREAD

**Issue by rolandsmeenk** [microsoft/MixedRealityToolkit-Unity#10062]
## Describe the problem

When recording with Render from PV Camera enabled I often run into near plane clipping in the recorded video. Typically does will be the case when using direct hand manipulation of holograms. This clipping is not visible in HoloLens, but only seen after the recording is done so this must be a difference in near plane settings for the PV camera and the camera used for rendering the stereo view.

## Describe the solution you'd like

The PV Camera near plane distance should match the near plane settings from the stereo camera. 

## Describe alternatives you've considered

Manual configuration of the PV Camera near plane, but this may still result in a difference between the view in HoloLens and the recording. For instance if a near plane fading is enabled in the used shaders you probably want to see the same visual effects in the recorded video.

## Additional context

![20210712_131621_HoloLens](https://user-images.githubusercontent.com/480316/125279096-cee61100-e313-11eb-800b-c7410f15d1b4.jpg)

**Comment by keveleigh** [comment]
Which version of Unity are you using? If you're using Windows XR Plugin, which version of that are you using? I think this should be fixed on the latest versions across the board, but I can try to narrow down where the proposed fixes landed.

**Comment by rolandsmeenk** [comment]
Unity 2019.4.21f1, Legacy XR, MRTK 2.7.2.0
But I will check with a newer Unity

**Comment by keveleigh** [comment]
> Unity 2019.4.21f1, Legacy XR

Looks like it landed in 2019.4.26f1 for legacy

**Comment by rolandsmeenk** [comment]
Checked with 2019.4.28f1, Legacy XR and Unity 2020.3.11f1, OpenXR and near plane clipping is no longer an issue.

**Comment by keveleigh** [comment]
Thank you for confirming!!
