### ISSUE TITLE
SliderSounds plays sounds when the slider position is updated by the system

### ISSUE THREAD

**Issue by holomatt** [microsoft/MixedRealityToolkit-Unity#10065]
SliderSounds plays sfx when the system updates the slider thumb position. This results in anomalous sounds from the user's perspective as they are not interacting with the slider.

Examples: 

Slider position is set to a value on initialization. Slider position is set to a value ambiently by the system during the experience.

Expected Behavior:

SliderSounds only triggers as a result of user interaction or provides a bool to govern this behavior.

**Comment by Zee2** [comment]
@RogPodge Do you want to take a look at this, because I think you were working with the touch slider recently? If not, there is another bug with touch slider (#10066) that I was going to tackle (same root cause as a previous bug I fixed), and I could do this at the same time.

**Comment by RogPodge** [comment]
@holomatt do you have a quick video reproducing the issue? I'm wondering if rogue events are firing somewhere and want to make sure we're looking at the right scenario
