### ISSUE TITLE
TMP InputField submit event by cancelling Hololens Keyboard

### ISSUE THREAD

**Issue by hermann-noll** [microsoft/MixedRealityToolkit-Unity#10063]
## Describe the bug

When using a TextMeshPro inputfield in a MRTK canvas and the system hololens keyboard a submit event is fired even though the user pressed the X-button to cancel the input.

## To reproduce

1. Create a scene containing a MRTK canvas and a TMP input field
2. Add a handler to the submit event
3. Build and run on Hololens
4. Observe the submit event being fired when the X-Button is pressed

## Expected behavior

A submit event should only be fired when the user presses the enter or equivalent button.

## Your setup (please complete the following information)

- Unity Version 2020.3.13f1
- MRTK Version 2.7.2

## Target platform (please complete the following information)

- HoloLens 2

**Comment by MaxWang-MS** [comment]
Thanks for reporting this issue! The TMP input field is owned by Unity so you might want to file a Unity bug and/or bring this up in their forum.
