### ISSUE TITLE
Allow the user to choose the button state depending on follow behavior

### ISSUE THREAD

**Issue by arsdever** [microsoft/MixedRealityToolkit-Unity#10070]
The script looks a bit limiting with the current implementation. This somehow forces the user to have a `FollowMe` button, but the user may want to have a `Pin` button instead, which is impossible to assign as an interactable for the `FollowMeToggle` component the reverse behavior of `IsToggled` state.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/265a0ea3621c84b88e4b02e7fcd1b5682afef56a/Assets/MRTK/SDK/Features/UX/Scripts/Slate/FollowMeToggle.cs#L196

**Comment by RogPodge** [comment]
Just so I'm understanding this correctly, is this issue requesting a behavior that explicitly has the opposite behavior of the FollowMeToggle? From what I can tell, the FollowMeToggle will either pins its gameobject in place or set it to follow the user, so the desired "pin" behavior would work without any additional changes.

**Comment by arsdever** [comment]
The speech is not about the behavior of the `gameObject` it is assigned to, but rather the toggled state of the interactable, which is optional to be assigned. So, if the user has a `Pin` button (which is toggled when the `gameObject` is not following) the script doesn't fit, whereas for `FollowMe` buttons (which is toggled when the `gameObject` is following) it works perfectly.

**Comment by RogPodge** [comment]
Ah I see where the request is coming from. Basically, you're looking for the option to set the interactable's toggle state to false when the FollowMeToggle's follow property is true and vice versa right?

**Comment by arsdever** [comment]
Exactly. I would say it's even better to have an `enum` for choosing how should the `Interactable` behave depending. Maybe the user doesn't want the `Interactable` to change the state at all (although it's possible by not attaching the `Interactable` at all).

I was trying to prepare a PR. Maybe today I'll propose it. Let's see what comes.

**Comment by keveleigh** [comment]
@arsdever Thanks for adding this new behavior!
