### ISSUE TITLE
PinchSlider: How to update slider in script?

### ISSUE THREAD

**Issue by janick187** [microsoft/MixedRealityToolkit-Unity#10073]
## Describe the issue
I query a value from an external server inside my c# script. I get a float value from this server in the range of [0,1].
Now from inside the code I want to update the PinchSlider with this value. 

Unfortunately the following calls do not work. The PinchSlider is not updated: 
```
// update value
brightnessSlider.GetComponent<PinchSlider>().SliderValue = newBrightness;    
// update line
brightnessSlider.transform.Find("TrackVisuals").Find("Line_active").gameObject.transform.localScale = new Vector3(transform.localScale.x, newBrightness, transform.localScale.z);
 // update label
brightnessSlider.transform.Find("SliderValue").GetComponent<TextMeshPro>().text = $"{newBrightness:F2}";
```

## Feature area
Documentation is very basic and does not include any information regarding updating slider inside script.

## Existing doc link
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/sliders?view=mrtkunity-2021-05

**Comment by RogPodge** [comment]
Tested changing the slider values via code and it seemed to work in the example scenes. Which MRTK version are you looking at?

**Comment by janick187** [comment]
Sorry, how can I check my version of MRTK?
Also, youd cou kindly share your code lines for chaning slider value? Did it also adjust the slider visually (i.e. the line and toggle)?

**Comment by RogPodge** [comment]
This is the test update code I added to the PinchSlider.cs script and it let me increase a slider's value by pressing the up arrow key


        public void Update()
        {
            if(UnityEngine.Input.GetKeyDown(KeyCode.UpArrow))
            {
                SliderValue += 0.01f;
            }
        }

It ends up moving the slider thumb and increasing the value of the text display, though I don't see any gameobject on the default prefab labled as "Line_active".

Later builds of MRTK has the following menu option, though if you don't have that it's hard to say which version you are on unfortunately :(

![image](https://user-images.githubusercontent.com/39840334/125667851-4f7554f8-1333-4c07-80be-0af39f4ea7ce.png)

**Comment by RogPodge** [comment]
@janick187 is this still an issue for you?

**Comment by RogPodge** [comment]
Closing as resolved. If you're still seeing this issue please feel free to repoen.
