### ISSUE TITLE
Shader renderings are only visible in one eye

### ISSUE THREAD

**Issue by Jason-Chn95** [microsoft/MixedRealityToolkit-Unity#10079]
## Describe the bug

Shader renderings are only visible in one eye，everything appears in the Unity editor. After packaging, I noticed that the shader effect is only displayed in the left eye, and the right eye does not see the shader effect.

## To reproduce

1.Write your own shader
2.Attach to the material ball and then add the shader to Unity's Graph includingshaders list
3.XR Setting
![image](https://user-images.githubusercontent.com/57438511/125597697-f5d7ff2b-98ba-4d57-a8f1-d1c21f14c641.png)
4.Pack it and view it at HoloLens

## Expected behavior

Shader effects can be normally seen in both eyes

## Your setup (please complete the following information)

- Unity Version [2019.4.5f1]
- MRTK Version [v2.5.0]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
> 1.Write your own shader

I would recommend reading https://docs.unity3d.com/2020.2/Documentation/Manual/SinglePassInstancing.html, particularly the section under "Custom shaders". There may be some lines you'll need to add to your shader to properly support single pass instanced rendering.

**Comment by Jason-Chn95** [comment]
> > 1.编写自己的着色器
> 
> 我建议阅读https://docs.unity3d.com/2020.2/Documentation/Manual/SinglePassInstancing.html，特别是“自定义着色器”下的部分。您可能需要向着色器添加一些行以正确支持单通道实例化渲染。

I have modified these according to the instructions, but they are still not displayed after packaging. May I ask if there is something wrong with my operation?
![image](https://user-images.githubusercontent.com/57438511/125719919-e6077351-fa88-4546-bad3-c645c289917f.png)


![image](https://user-images.githubusercontent.com/57438511/125720011-0f79868d-5124-4c65-b2e0-73bae9c64d67.png)



`Shader "Move/JT" {
    Properties {
        _Texture_Color ("Texture_Color", Color) = (0.5,0.5,0.5,1)
        _Texture ("Texture", 2D) = "black" {}
        [MaterialToggle] _Toggle ("Toggle", Float ) = 1
        _U_Speed ("U_Speed", Float ) = 0
        _V_Speed ("V_Speed", Float ) = -0.3
        [HideInInspector]_Cutoff ("Alpha cutoff", Range(0,1)) = 0.5
    }
    SubShader {
        Tags {
            "IgnoreProjector"="True"
            "Queue"="Transparent"
            "RenderType"="Transparent"
        }
        Pass {
            Name "FORWARD"
            Tags {
                "LightMode"="ForwardBase"
            }
            Blend SrcAlpha OneMinusSrcAlpha
			ZWrite Off
			ZTest Off							// We will need our 2D geometry to render on top of everything else, so we will disable Z tests
			Cull Off							// We will not concern ourselves with culling when rendering 2D geometry, so we will turn it off
			Fog{ Mode Off }
			Blend SrcAlpha OneMinusSrcAlpha		// Enable alpha blending for meshes with transparent vertices
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #define UNITY_PASS_FORWARDBASE
            #include "UnityCG.cginc"
            #pragma multi_compile_fwdbase
            #pragma multi_compile_fog
            #pragma only_renderers d3d9 d3d11 glcore gles 
            #pragma target 3.0
            uniform sampler2D _Texture; uniform float4 _Texture_ST;
            uniform fixed _Toggle;
            uniform float _U_Speed;
            uniform float _V_Speed;
            uniform float4 _Texture_Color;
            struct appdata
            {
                float4 vertex : POSITION;
                float2 uv : TEXCOORD0;

                UNITY_VERTEX_INPUT_INSTANCE_ID //Insert
            };
            struct v2f
            {
                float2 uv : TEXCOORD0;
                float4 vertex : SV_POSITION;

                UNITY_VERTEX_OUTPUT_STEREO //Insert
            };
            struct VertexInput {
                float4 vertex : POSITION;
                float3 normal : NORMAL;
                float2 texcoord0 : TEXCOORD0;
            };
            struct VertexOutput {
                float4 pos : SV_POSITION;
                float2 uv0 : TEXCOORD0;
                float4 posWorld : TEXCOORD1;
                float3 normalDir : TEXCOORD2;
                UNITY_FOG_COORDS(3)
            };
            v2f vert(appdata v)
            {
                v2f o;

                UNITY_SETUP_INSTANCE_ID(v); //Insert
                UNITY_INITIALIZE_OUTPUT(v2f, o); //Insert
                UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o); //Insert

                o.vertex = UnityObjectToClipPos(v.vertex);

                o.uv = v.uv;

                return o;
            }
            VertexOutput vert (VertexInput v) {
                VertexOutput o = (VertexOutput)0;
                o.uv0 = v.texcoord0;
                o.normalDir = UnityObjectToWorldNormal(v.normal);
                o.posWorld = mul(unity_ObjectToWorld, v.vertex);
                o.pos = UnityObjectToClipPos( v.vertex );
                UNITY_TRANSFER_FOG(o,o.pos);
                return o;
            }
            float4 frag(VertexOutput i) : COLOR {
                float4 node_5399 = _Time;
                float2 node_2628 = (i.uv0+(float2(_U_Speed,_V_Speed)*node_5399.g));
                float4 _Texture_var = tex2D(_Texture,TRANSFORM_TEX(node_2628, _Texture)) * _Texture_Color;
				return _Texture_var;
            }
            ENDCG
        }
    }
    FallBack "Diffuse"
    CustomEditor "ShaderForgeMaterialInspector"
}
`

**Comment by Waffle1434** [comment]
Your vertex shader modifications for single pass instanced look right to me, maybe its the fragment shader? Does rewriting the frag as:
```
fixed4 frag(VertexOutput i) : COLOR {
   return fixed4(0,1,0,1);
}
```
display a green mesh in both eyes?

**Comment by Waffle1434** [comment]
It looks like you have... two vertex shaders? (`v2f vert(appdata v)` and `VertexOutput vert (VertexInput v)`) There can only be one.

Maybe try:
```C
CGPROGRAM
#pragma vertex vert
#pragma fragment frag
#define UNITY_PASS_FORWARDBASE
#include "UnityCG.cginc"
#pragma multi_compile_fwdbase
#pragma multi_compile_fog
#pragma only_renderers d3d9 d3d11 glcore gles
#pragma target 3.0
uniform sampler2D _Texture; uniform float4 _Texture_ST;
uniform fixed _Toggle;
uniform float _U_Speed;
uniform float _V_Speed;
uniform float4 _Texture_Color;

struct VertexInput {
    float4 vertex : POSITION;
    float3 normal : NORMAL;
    float2 texcoord0 : TEXCOORD0;
    UNITY_VERTEX_INPUT_INSTANCE_ID //Insert
};
struct VertexOutput {
    float4 pos : SV_POSITION;
    float2 uv0 : TEXCOORD0;
    float4 posWorld : TEXCOORD1;
    float3 normalDir : TEXCOORD2;
    UNITY_FOG_COORDS(3)
    UNITY_VERTEX_OUTPUT_STEREO //Insert
};

VertexOutput vert (VertexInput v) {
    VertexOutput o = (VertexOutput)0;
    
    UNITY_SETUP_INSTANCE_ID(v); //Insert
    UNITY_INITIALIZE_OUTPUT(v2f, o); //Insert
    UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o); //Insert
    
    o.uv0 = v.texcoord0;
    o.normalDir = UnityObjectToWorldNormal(v.normal);
    o.posWorld = mul(unity_ObjectToWorld, v.vertex);
    o.pos = UnityObjectToClipPos( v.vertex );
    UNITY_TRANSFER_FOG(o,o.pos);
    return o;
}
float4 frag(VertexOutput i) : COLOR {
    float4 node_5399 = _Time;
    float2 node_2628 = (i.uv0+(float2(_U_Speed,_V_Speed)*node_5399.g));
    float4 _Texture_var = tex2D(_Texture,TRANSFORM_TEX(node_2628, _Texture)) * _Texture_Color;
return _Texture_var;
}
ENDCG
```

**Comment by Jason-Chn95** [comment]
> This is not a MRTK issue, this is your shader not supported single pass instanced stereo.
> 
> It looks like you have... two vertex shaders? (`v2f vert(appdata v)` and `VertexOutput vert (VertexInput v)`) There can only be one.
> 
> Maybe try:
> 
> ```c
> CGPROGRAM
> #pragma vertex vert
> #pragma fragment frag
> #define UNITY_PASS_FORWARDBASE
> #include "UnityCG.cginc"
> #pragma multi_compile_fwdbase
> #pragma multi_compile_fog
> #pragma only_renderers d3d9 d3d11 glcore gles
> #pragma target 3.0
> uniform sampler2D _Texture; uniform float4 _Texture_ST;
> uniform fixed _Toggle;
> uniform float _U_Speed;
> uniform float _V_Speed;
> uniform float4 _Texture_Color;
> 
> struct VertexInput {
>     float4 vertex : POSITION;
>     float3 normal : NORMAL;
>     float2 texcoord0 : TEXCOORD0;
>     UNITY_VERTEX_INPUT_INSTANCE_ID //Insert
> };
> struct VertexOutput {
>     float4 pos : SV_POSITION;
>     float2 uv0 : TEXCOORD0;
>     float4 posWorld : TEXCOORD1;
>     float3 normalDir : TEXCOORD2;
>     UNITY_FOG_COORDS(3)
>     UNITY_VERTEX_OUTPUT_STEREO //Insert
> };
> 
> VertexOutput vert (VertexInput v) {
>     VertexOutput o;
>     
>     UNITY_SETUP_INSTANCE_ID(v); //Insert
>     UNITY_INITIALIZE_OUTPUT(VertexOutput, o); //Insert
>     UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o); //Insert
>     
>     o.uv0 = v.texcoord0;
>     o.normalDir = UnityObjectToWorldNormal(v.normal);
>     o.posWorld = mul(unity_ObjectToWorld, v.vertex);
>     o.pos = UnityObjectToClipPos( v.vertex );
>     UNITY_TRANSFER_FOG(o,o.pos);
>     return o;
> }
> fixed4 frag(VertexOutput i) : COLOR {
>     float4 node_5399 = _Time;
>     float2 node_2628 = (i.uv0+(float2(_U_Speed,_V_Speed)*node_5399.g));
>     float4 _Texture_var = tex2D(_Texture,TRANSFORM_TEX(node_2628, _Texture)) * _Texture_Color;
>     return _Texture_var;
> }
> ENDCG
> ```

Thank you so much!!! It worked:)
