### ISSUE TITLE
How to make a Hologram appear directly in fornt of the user's face?

### ISSUE THREAD

**Issue by janick187** [microsoft/MixedRealityToolkit-Unity#10087]
## Describe the issue
From the documentation and solver overview it is not clear to me how I can make a Hologram to face always the user's face?
E.g. no matter if the user is looking up to the ceiling or looking down to the floor, changing a Hologram's state suddenly to activate should make it appear always in front of the user so that the user does not have to search for the hologram. Which solver do I need to use and what settings?

## Feature area
Documentation does not contain examples.

## Existing doc link
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/solvers/solver?view=mrtkunity-2021-05

**Comment by Zee2** [comment]
Hi there @janick187, the Follow solver is exactly what you need. The Follow solver, when attached to your GameObject, will cause the object to always be within the user's field of view, with a configurable maximum degree angle/displacement that the solver will allow the object to be within.

![image](https://user-images.githubusercontent.com/5544935/126201444-5c07fc42-21b9-4a83-a183-00c24760a43e.png)
![followexamplescene](https://user-images.githubusercontent.com/5544935/126201465-f2cbbb1c-de13-470a-b829-71c096e8d881.gif)
