### ISSUE TITLE
Can you add the Spatial awareness support to Android and iOS

### ISSUE THREAD

**Issue by ajinkya446** [microsoft/MixedRealityToolkit-Unity#10084]
## Actual Problem

Spatial Awareness not supported in Android and iOS devices for detecting the spatial mesh in real world through device camera.

## Solution need to add

Can you add the support in Android and iOS device for scanning spatial mesh.

## Platform
Unity Editor: 2019.4.22f
Android OS: Android 11
iOS OS: iPhone 6s(13)

**Comment by Zee2** [comment]
Unfortunately, ARKit/ARCore do not support meshing/scene reconstruction at this time.

![image](https://user-images.githubusercontent.com/5544935/126201835-b30c29c0-3c8d-48c5-bc99-4cb4ddd22451.png)

When ARKit/ARCore provide meshing support through ARFoundation, we will support it. @keveleigh we don't currently have any plans to support meshing on Android separate from ARFoundation, do we?

**Comment by keveleigh** [comment]
Correct, we don't. We could add support for planes in the meantime though, as both ARKit and ARCore, as well as HL2 on OpenXR, support that.

**Comment by Zee2** [comment]
Sounds good. Closing this, but we can track the addition of new scene reconstruction and scene understanding features on mobile platforms in a different work item.
