### ISSUE TITLE
Project selection fails if folder names are lower case

### ISSUE THREAD

**Issue by Vectrobe** [microsoft/MixedRealityToolkit-Unity#10080]
## Describe the bug

Project selection stage of the tool installer will fail, if the target project has lower case or mixed case folders, it will think its not a unity project and complain that the folders are missing

## To reproduce

Make a dummy project with any of the three "Assets", "Packages", "ProjectSettings", with the case of any character in any folder changed from the example.

Selecting the dummy project will fail, with the "needs folders..." type error message.

## Expected behavior

The folders are there, its a valid project, this warning should not occur.

## Your setup (please complete the following information)

- Unity Version N/A
- MRTK Version MixedRealityFeatureTool-1.0.2104.4-Beta

## Target platform (please complete the following information)

- N/A

## Additional context

You need to sanity check the comparison when running on windows, since windows does not allow folders to be created using same characters of different casing.
Run a lower-case-pass on all folder strings before comparing, or use a compare function that does so.
For targeting linux; find a suitable folder for the given name and set that as the name to use, or use this method in general.

**Comment by elbuhofantasma** [comment]
Hello @Vectrobe thank you for submitting this issue on the Mixed Reality Feature Tool! I have assigned @davidkline-ms to investigate this, and @keveleigh added it to the appropriate Project for the Mixed Reality Feature Tool

**Comment by keveleigh** [comment]
I've just opened a PR on the MR Feature Tool repo to fix this. Thanks for the report!
