### ISSUE TITLE
No version of GetRawBBCorners that works with BoundsControl is public

### ISSUE THREAD

**Issue by SebastianMeinberger** [microsoft/MixedRealityToolkit-Unity#10083]
## Describe the bug

GetRawBBCorners from the [BoundingBoxHelper](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/265a0ea3621c84b88e4b02e7fcd1b5682afef56a/Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBoxHelper.cs) is obsolete, since it uses the deprecated BoundingBoxes. The hint says "Use GetRawBBCorners and pass in TargetBounds", but GetRawBBCorners has no overloading that accepts a BoxCollider. However, there exists GetRawBoundsCorners, which accepts a BoxCollider, but it can't be used outside of the MRTK assembly since it is internal.

## To reproduce

1. Create a script outside of the MRTK assembly
2. Create a BoundingBoxHelper object
3. Create a BoundsControl object
4. Call GetRawBBCorners on the BoundingBoxHelper object with boundsControlObject.TargetBounds as said in the hint of the obsolete message (This won't work, since GetRawBBCorners has no overloading that accepts a TargetBounds/BoxCollider)
5. Call GetRawBoundsCorners on the BoundingBoxHelper object with boundsControlObject.TargetBounds (This won't work, since GetRawBoundsCorners is internal and we are not in the same assembly as the BoundingBoxHelper)

## Expected behavior

Some version of GetRawBBCorners should be usable with the new BoundsControl outside of the MRTK assembly.

## Your setup

- Unity Version 2019.4.5f1
- MRTK Version v2.7.2

## Target platform

- HoloLens 2
- OpenVR

**Comment by elbuhofantasma** [comment]
Hello @SebastianMeinberger thank you for submitting this BoundsControl bug! We will investigate this and get back to you with our findings. Could you please add some additional details to your repro steps to help us investigate this bug faster? Thanks!
