### ISSUE TITLE
Does Follow.cs replace FollowMeToggle.cs?

### ISSUE THREAD

**Issue by FlyingFlambe** [microsoft/MixedRealityToolkit-Unity#10095]
## Describe the issue
Seeking clarification when using the follow/follow me toggle component in combination with a solver.

## Feature area
The MRTK documentation says very little about the **Follow Me Toggle** class solver which has me wonder if there is an intention to deprecate it. The **Follow Me Toggle** solver also auto-assigns the Radial View solver so that it works properly.

In comparison, the doc recommends using the **Follow** solver which is described as acting similarly to the Radial View solver. This seems to be the simpler and newer approach.

## Existing doc link
Current solvers doc page: https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/solvers/solver?view=mrtkunity-2021-05

Follow me toggle class: https://docs.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.toolkit.ui.followmetoggle?view=mixed-reality-toolkit-unity-2020-dotnet-2.7.0

**Comment by elbuhofantasma** [comment]
Hello @FlyingFlambe thank you for submitting this documentation issue! I have assigned @MaxWang-MS since he is our documentation expert, to help clarify this issue for you and the community.

**Comment by polar-kev** [comment]
@cre8ivepark can you share your response to this issue here?

**Comment by RogPodge** [comment]
Closing as this has gone stale and we're looking to revamp our solver implementation/documentation for MRTK3.
