### ISSUE TITLE
Microsoft.Windows.UI.Xaml.CSharp.targets was not found - VS17 - Last MRT Build

### ISSUE THREAD

**Issue by Andre-Rb** [Microsoft/MixedRealityToolkit-Unity#1009]
Hi, I come to you guys for help because I've been trying for some time to get the build portal to work at 100% without much success, I don't know if it's a bug or something wrong on my side.

I get the following error while MSBuild runs the command 
`"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe" "C:\Users\PROJECTPATH\UWP\PROJECTNAME.sln" /t:Build /p:Configuration=MASTER /p:Platform=x86`

During the generation of an APPX from the solution build with the toolkit.
I'm suspecting a path issue/something not installed that I missed, but I can't find it sadly.

EDIT : I should mention that the files actually does not exist, nor it's parent folder and that my sln file mentions Visual Studio 2015, that surprises me.

Cheers 

Here's the error :
```C:\Users\Technoshop_User\Documents\Dev Projects\Unity\GTS_Demo\UWP\GTS_Demo\GTS_Demo.csproj(254,11): error MSB4226: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\WindowsXaml\v15.0\Microsoft.Wind
ows.UI.Xaml.CSharp.targets" was not found. Also, tried to find "Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths a
re defined in "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.
C:\Users\Technoshop_User\Documents\Dev Projects\Unity\GTS_Demo\UWP\GeneratedProjects\UWP\Assembly-CSharp\Assembly-CSharp.csproj(178,11): error MSB4226: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Micros
oft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Also, tried to find "Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (
x86)\MSBuild" . These search paths are defined in "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in o
ne of the search paths.
C:\Users\Technoshop_User\Documents\Dev Projects\Unity\GTS_Demo\UWP\GeneratedProjects\UWP\Assembly-CSharp-firstpass\Assembly-CSharp-firstpass.csproj(183,11): error MSB4226: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Build
Tools\MSBuild\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Also, tried to find "Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) -
 "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file
 exists on disk in one of the search paths.```

**Comment by HattMarris1** [comment]
I had an issue that I think is similar to this, try updating your nuget packages, or maybe refer to #934

**Comment by StephenHodgson** [comment]
What version of visual studio do you have installed?

Do you have all the sdks installed as well?

**Comment by Andre-Rb** [comment]
@StephenHodgson ```
Microsoft Visual Studio Community 2017 
Version 15.3.5
VisualStudio.15.Release/15.3.5+26730.16
Microsoft .NET Framework
Version 4.7.02555

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA648
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA648
Microsoft Visual C# 2017

Application Insights Tools for Visual Studio Package   8.8.00712.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30726.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Template Engine 2017   15.0.30726.0
ASP.NET Template Engine 2017

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2017.2    Build 109.0.20170824.131346
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.3.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

TypeScript   2.3.4.0
TypeScript tools for Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Unity   3.3.0.2
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.26730.08
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.
```

I try to always have the latest version. And concerning SDKs I installed all the W10 and W8 SDKs the VS Installer Tool offered me (plus all .net Framework)

I followed all requirement in tutorials, so I guess something is missing but I can't find it.

@HattMarris1 I was unable to right click update nuget packages ( tried in VS17 & VS15 but they can't find anything to update)

**Comment by StephenHodgson** [comment]
Thanks, I'll look into this more for you.

In the meantime, if you find a fix or manage to get it working, let me know.

What happens when you do a traditional build through vs?

**Comment by Andre-Rb** [comment]
Well, that's what I was doing last week when getting to know the Hololens and MRTK.
I was generating a sln with MRTK and buidling and deploying with VS17 , building wouldn't work with Unity alone and APPX would throw another error, kinda fixed it by "building from the sources" MRTK.

**Comment by Andre-Rb** [comment]
I'll be damned, I uninstalled a VS Build Tool version that I installed next to my VS17 installations this morning, and MRTK used VS17 MSBuild ( I just added it too, dunno if related ) and the appx build went, AFAIK smoothly.
At this point I don't know if I had very poor look with my environment or if tuts we not explicit enough.. But it looks like it's gonna work.
I'll try to deploy this, I'll keep you posted.

**Comment by StephenHodgson** [comment]
Yay!

**Comment by Andre-Rb** [comment]
Yup, deploying without an issue ( expect me forgetting the password, duh)
Glad it works, but I can't shake the feeling that I'll stumbled across something later... Being a dev makes you paranoid, not judging the awesome work done here obviously :)

**Comment by StephenHodgson** [comment]
>  Being a dev makes you paranoid

😆 tell me about it!  The biggest example being that I wrap things in null checks even when I _know_ they could never be null

**Comment by omen7288** [comment]
> I'll be damned, I uninstalled a VS Build Tool version that I installed next to my VS17 installations this morning, and MRTK used VS17 MSBuild ( I just added it too, dunno if related ) and the appx build went AFAIK smoothly.

I was hitting the same issue and had to do the same (remove the MSBuild tools for VS2017, and then rerun the VS2017cleanup/installer and reboot to fix this). Thanks.

**Comment by c-trinh** [comment]
> I'll be damned, I uninstalled a VS Build Tool version that I installed next to my VS17 installations this morning, and MRTK used VS17 MSBuild ( I just added it too, dunno if related ) and the appx build went AFAIK smoothly.
> At this point I don't know if I had very poor look with my environment or if tuts we not explicit enough.. But it looks like it's gonna work.
> I'll try to deploy this, I'll keep you posted.

Thank you so much, this actually works. I have been banging my head on this issue for about a week, only to learn you just have to reinstall the build tool.
