### ISSUE TITLE
v3: Core systems should be reimplemented XR Subsystems

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#10098]
As part of MRTK v3 embracing more of the built-in and XR Interaction Toolkit components, the plan is to evaluate each core system and determine

1. Is there an equivalent built-in solution
2. Is there value in aggregating / wrapping built-in solution(s)
3. The shape of the new subsystem + additional components to achieve parity with MRTK v2.x

This combines and replaces #9186 and #9511 

Some tracked issues for subsystems work:

#10124 
#10122

**Comment by Zee2** [comment]
Resolved as we have followed this architectural direction in MRTK3.
