### ISSUE TITLE
Scene understanding crashes Unity 2020.3.2f1

### ISSUE THREAD

**Issue by sBailey5449** [microsoft/MixedRealityToolkit-Unity#10099]
## Describe the bug

Unity immediately crashes when trying to open the Scene Understanding example scene in Unity 2020.3.2f1. Produces the error message shown in screenshots. This also happens if you try to add the WindowsSceneUnderstandingObserver in the MixedRealityToolkit object where all various MRTK settings reside. 

## To reproduce

Create a new project in Unity 2020.3.2f1 and import essential MRTK components. Import the Scene Understanding sample scene via package manager. Navigate to the example scene and try to open it. Application immediately crashes. 

Or

Have an existing MRTK project and try to add the WindowsSceneUnderstandingObserver in the MixedRealityToolkit object under Spatial Awareness/

## Expected behavior

Expect there to be no errors

## Your setup (please complete the following information)

- Unity Version 2020.3.2f1
- MRTK Version 2.7.2

## Target platform (please complete the following information)

- HoloLens 2 / UWP

<img width="344" alt="error" src="https://user-images.githubusercontent.com/37403659/126400515-8ec7329f-48b7-4c0e-9d17-a761353b4ecc.PNG">

**Comment by MaxWang-MS** [comment]
Thanks for reporting the issue. I was not able to reproduce with Unity 2020.3.2, MRTK 2.7.2, Mixed Reality OpenXR plugin 1.0.1 and Scene Understanding 0.6.0 (I was able to open the sample scene and run it successfully). Could you share with us which XR pipeline you used (Windows XR Plugin or OpenXR) and maybe attach the Unity editor log located at `%LOCALAPPDATA%\Unity\Editor\Editor.log` if you feel comfortable? Otherwise please reply with the lines in the editor log that seems relevant so that we can better troubleshoot the issue.

**Comment by sBailey5449** [comment]
I have tried both the Windows XR Plugin and OpenXR with the exact same result. Just tried this again with a totally new project and used the mixed reality feature tool to add MRTK, examples, extensions, foundation, and standard assets. Also adding platform support for Mixed Reality OpenXR plugin and Mixed Reality Scene Understanding. Latest versions selected for all items. After opening the project I import the scene understanding example via package manager and try to open the example scene that results in the error above.

There is nothing in the Editor Log to indicate the error even happened. The last lines in the file are attached.
<img width="899" alt="noerror" src="https://user-images.githubusercontent.com/37403659/126504149-d2170514-0a89-4be3-82ed-ce5ba5656319.PNG">

**Comment by MaxWang-MS** [comment]
Now that seems very weird now... So the runtime library popped up, you clicked OK, Unity crashed and there is nothing in their log? Could you send us a copy of the fresh project that on your side exhibited the behavior? We'll try to do a repro with it. At this point I am almost wondering if it's a runtime library not properly installed issue.

**Comment by sBailey5449** [comment]
Turns out this problem was resolved once I upgraded to a more recent version of windows
