### ISSUE TITLE
Set 'OpenXR' Hand Ray Disable Bug

### ISSUE THREAD

**Issue by dn-soft** [microsoft/MixedRealityToolkit-Unity#10104]
## Describe the bug

The problem is that if you don't change your profile every time you build, 'Hand Ray' will be disabled with a very high probability.

## To reproduce

We are currently building HoloLens2 by adding QRCode in the Open XR environment.

The problem is that if you don't change your profile every time you build, 'Hand Ray' will be disabled with a very high probability.

Currently, I have created several similar profiles, and I am praying for 'Hand Ray' to turn on by changing the profile every time.

It is too difficult to develop.

Why is 'Hand Ray' disabled with a certain probability every time I build?

## Your setup (please complete the following information)

-Build OS: Windows 10
-Unity: 2020.3.12f1
*Please refer to the image below for MRTK2 and OpenXR versions.
![00_All Plug-in version](https://user-images.githubusercontent.com/65150702/126744500-67780c90-bae0-432b-a8d0-151c090ea8c3.png)

![01_XR Plug-in](https://user-images.githubusercontent.com/65150702/126744874-db69b9c7-41fc-499a-8fc2-33ffbe8d78ac.png)

![02_OpenXR](https://user-images.githubusercontent.com/65150702/126744886-a80b99fc-a804-46bb-b6bd-e35b7880bef1.png)

## Target platform (please complete the following information)

-Platform: UWP
-Device: HoloLens2

## Additional context

Features 1. Once disabled with the same profile, it will be disabled even if you continue to build. (So I always build with changing profiles)
Feature 2. If you change your profile, it will be reactivated with a high probability.

**Comment by keveleigh** [comment]
This sounds like a bug we're tracking on the OpenXR plugin side. I'll report this as another data point and see if we can get to the bottom of it.

**Comment by dn-soft** [comment]
> This sounds like a bug we're tracking on the OpenXR plugin side. I'll report this as another data point and see if we can get to the bottom of it.
> 
> As a workaround, I'd try launching the app and immediately moving your hands **out of view** so they aren't tracked when the app launches.

Does the workaround you mentioned only apply to the first run of the build?
Or is it applied every time you run it?

When I tested, if 'Hand Ray' was not visible during the first build, 'Hand Ray' is not visible no matter how you close the app and run it again.

If you see 'Hand Ray' when building for the first time, it will continue to look good even if you continuously relaunch the app.

**Comment by keveleigh** [comment]
It's likely per app session, so if you aren't fully closing (clicking the X on the slate) and re-opening, the app may continue to have problems.

**Comment by keveleigh** [comment]
This should be fixed (and has been for a while)! Please re-open if you're still hitting it.
