### ISSUE TITLE
Toggle switch to stop gaze input from deactivating

### ISSUE THREAD

**Issue by boersig** [microsoft/MixedRealityToolkit-Unity#10103]
## Describe the problem

I need the gaze input (without eye tracking) to be active at all times. At the moment it deactivates when my hands enter the Hololenses FOV.

## Describe the solution you'd like

A simple toggle switch in the inspector saying something like "keep gaze input active at all times"

## Describe alternatives you've considered

- implementing my own raycast-based gaze provider, but I would prefer to keep the input methods uniformly
- I also tried [this](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/input/eye-tracking/eye-tracking-target-selection?view=mrtkunity-2021-05#example-4-use-hand-rays-and-eye-gaze-input-together), but couldn´t get it to work. This is most probably due to my own stupidity, but I guess that I am not the only person who needs this feature and who would welcome a more user friendly option.

Thank you very much advance!

**Comment by boersig** [comment]
Hello,

Could you tell me if you plan on implementing something like this in the near future, so that I know wether I should wait for it or build my own ad-hoc solution?

Thank you in advance!

**Comment by keveleigh** [comment]
You're likely going to want to look into the `PointerBehavior` concept in MRTK. We have some helpers at https://github.com/microsoft/MixedRealityToolkit-Unity/blob/265a0ea3621c84b88e4b02e7fcd1b5682afef56a/Assets/MRTK/SDK/Features/UX/Scripts/Utilities/PointerBehaviorControls.cs that might be usable in this case (things like `SetHoloLens1()` turn off hand rays but keep the gaze pointer on). You can also just explicitly set the gaze pointer to be `AlwaysOn` using the same patterns, if you aren't looking to change other pointers at the same time:

```c#
PointerUtils.SetGazePointerBehavior(PointerBehavior.AlwaysOn);
```

**Comment by boersig** [comment]
Perfect, this was exactly what I needed!

Thank you very much✌
