### ISSUE TITLE
EyeTrackingTarget not triggering OnLookAway when passing from collider with EyeTrackingTarget to collider without

### ISSUE THREAD

**Issue by Walkramis** [microsoft/MixedRealityToolkit-Unity#10106]
## Describe the bug

When having two objects with colliders right next two each other, one with EyeTrackingTarget and one without. If eye gaze is passing between these two directly (meaning eye gaze raycast is hitting a collider each frame) OnLookAway will not trigger. It will only trigger when looking at another object with EyeTrackingTarget or when the eye gaze raycast is not hitting anything.

## To reproduce

1. Setup a basic scene with MRTK and eye tracking.
2. Create two cubes with colliders.
3. Add an EyeTrackingTarget to one of them and some identifiable behaviours to OnLookAtStart and OnLookAway.
4. Position them close so the eye gaze can go between them without "missing".
5. Observe that OnLookAway will not trigger when going from the first to the second cube.

From Looking at the code it seems LookedAtTarget is not updated if a collider is hit but LookedAtEyetarget is null (from line 263):
```
LookedAtEyeTarget = hitInfo.collider.transform.GetComponent<EyeTrackingTarget>();

if (LookedAtEyeTarget != null)
{
    LookedAtTarget = LookedAtEyeTarget.gameObject;
}
```

## Expected behavior

Expected behavior would be that OnLookAway would trigger even when gaze passes directly from object with EyeTrackingTarget to one without.
Code suggestion change that fixed the issue for me.

Changed:
```
if (LookedAtEyeTarget != null)
{
    LookedAtTarget = LookedAtEyeTarget.gameObject;
}
```
To:
```
LookedAtTarget = hitInfo.collider.transform.gameObject;
```

## Screenshots
Current behaviour:
![current](https://user-images.githubusercontent.com/16719812/126783284-2f0bade8-a105-4efb-be43-81ceb78c0446.gif)

Expected:
![expected](https://user-images.githubusercontent.com/16719812/126783325-676fab62-49bf-46a5-8a23-041164ebc55e.gif)

## Your setup (please complete the following information)

- Unity Version 2020.03.13
- MRTK Version v2.7.2

## Target platform (please complete the following information)

- HoloLens 2
- OpenXR

**Comment by polar-kev** [comment]
Hey @Walkramis, can you submit a PR with your code changes so we can run some tests on it and see if anything breaks?

**Comment by Walkramis** [comment]
Sure thing!
I have now added a pull request at https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10127
Let me know if you need anything else :)
