### ISSUE TITLE
Canvas contents not visible in Mixed Reality Capture

### ISSUE THREAD

**Issue by cwule** [microsoft/MixedRealityToolkit-Unity#10111]
## Describe the bug

I have a canvas with an image and text on it, eg. the SceneDescriptionPanelRev from the MRTK example EyeTrackingDemo-03-Navigation. When deploying the app to the Hololens and recording it via Mixed Reality Capture, the canvas appears empty (screenshots below).

## To reproduce

Open an example from the MRTK examples that contains a canvas with an image and text, eg. EyeTrackingDemo-03-Navigation. Deploy to Hololens 2. The canvas will be visible (as expected). Open Mixed Reality Capture via device portal or take a video. The canvas will appear empty (unexpected).

## Expected behavior

The same content should appear on the Hololens 2 and via Mixed Reality Capture.

## Screenshots

https://imgur.com/a/B0vykut

## Your setup (please complete the following information)

- Unity Version 2020.3.4f1
- MRTK Version 2.7.2

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

Found this when working on another canvas, so this problem is not specific to the scene mentioned above.

**Comment by elbuhofantasma** [comment]
Hello @cwule, thanks for submitting this issue with the Canvas and Mixed Reality Capture! We will start looking into this and update this issue with our findings.

**Comment by keveleigh** [comment]
This sounds like a fixed bug on the Unity side.

> Unity Version 2020.3.4f1

Looks like it was fixed in 2020.3.8f1, so you'll need to update your Unity version to get the fix.
FYI @elbuhofantasma

**Comment by cwule** [comment]
Thanks, that solved it. Tested and works with Unity 2020.3.14f1
