### ISSUE TITLE
Problems with your tests && ShellHandRayPointer

### ISSUE THREAD

**Issue by Proton-V** [microsoft/MixedRealityToolkit-Unity#10126]
Hello! 
I see that your test for cursor sometimes doesn't work correctly.
`BaseCursorTests.CursorContextMove`
Bug with 
`            yield return rightHand.SetGesture(ArticulatedHandPose.GestureId.Pinch);
`

I thought about what it was connected with and found a connection.
Your raycast is not working correctly in some place.

Demonstration of inappropriate behavior:
![Optional Text](https://i.ibb.co/h1rDLbP/photo-2021-07-30-06-50-29.jpg)
![Optional Text](https://i.ibb.co/wrLQwtw/photo-2021-07-30-06-50-35.jpg)

Can you give me a more precise direction of where to look to fix this?

And will we merge my old request for the master? https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10033
It has been lying for almost a month)

@davidkline-ms 
@keveleigh

**Comment by RogPodge** [comment]
Should be fixed with the above and also #10508
