### ISSUE TITLE
Build Error on Unity 2021.1.15f1 / MRTK 2.7.2.0

### ISSUE THREAD

**Issue by ARecentDeveloper** [microsoft/MixedRealityToolkit-Unity#10130]
The following errors are thrown while trying to build an app using MRTK for Hololens 2.

 `ArgumentException: The Assembly UnityEditor.CoreModule is referenced by UploaderTool_Editor ('Packages/com.microsoft.altspacevr_uploader/Plugins/UploaderTool_Editor.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <5be0ebaa82df43c7b5c1b1db9bde1e97>:0)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at <5be0ebaa82df43c7b5c1b1db9bde1e97>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)`

`Build completed with a result of 'Failed' in 6 seconds (5782 ms)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
`

`UnityEditor.BuildPlayerWindow+BuildMethodException: 3 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002ca] in <5be0ebaa82df43c7b5c1b1db9bde1e97>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <5be0ebaa82df43c7b5c1b1db9bde1e97>:0 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
`

I followed the exact same steps from this [tutorial](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=openxr).

Unity 2021.1.15f1
Mixed Reality Toolkit 2.7.2.0

**Comment by keveleigh** [comment]
> Packages/com.microsoft.altspacevr_uploader

Are you using the AltspaceVR Uploader package? You might be able to uninstall it to work around this issue if not. As far as I can tell from the linked tutorial, the only packages it asks to be installed are `Mixed Reality Toolkit Foundation` and `Mixed Reality OpenXR Plugin`:

> Check the Mixed Reality Toolkit Foundation and click on the dropdown next to it to select MRTK 2.7.2, also check the Mixed Reality OpenXR Plugin 1.0.0 and click on the dropdown next to it to select most recent version available, then click on Get features button to download the selected packages.

**Comment by ARecentDeveloper** [comment]
Thank you, the error seems to come from AltspaceVR as you mentioned. I removed the package and everything works as it should for now. Thanks again.
As for the build platform, (if I understood you correctly) I was using 10.0.10240.0.
Thanks again.

**Comment by keveleigh** [comment]
Thanks for following up! Going to close this for now, as it's up to the Altspace team to update their package. I've made them aware of this issue.
