### ISSUE TITLE
Didn't find information about area restrictions of spatial mapping

### ISSUE THREAD

**Issue by nickxr** [microsoft/MixedRealityToolkit-Unity#10137]
## Describe the issue
I need to scan large spaces and save the entire mesh to an .obj format model.  

## Feature area
Everything works fine, but I didn't find any information on area restrictions.

## Existing doc link
https://docs.microsoft.com/en-us/windows/mixed-reality/design/spatial-mapping

## Additional context
I increased the Observation extents, but all I got was to keep the scan no more than 400 square meters.

Your documentation says the following: "Also note that, the spatial mapping system won't provide information about surfaces far away from the user's current location. So the application must 'remember' surfaces itself if it's to build a map of a large area"

I would like to know how far away?

**Comment by davidkline-ms** [comment]
Thank you @nickxr. I will forward this issue to our documentation repository.

**Comment by davidkline-ms** [comment]
Closing in favor of the linked documentation issue
