### ISSUE TITLE
get teleport target position??

### ISSUE THREAD

**Issue by davoodkharmanzar** [microsoft/MixedRealityToolkit-Unity#10141]
hi,
how can i get teleport target position?

`public void OnTeleportCompleted(TeleportEventData eventData) => position = eventData.Hotspot.Position;`  ??

**Comment by keveleigh** [comment]
You may be able to go off the pointer object itself, something like `public void OnTeleportCompleted(TeleportEventData eventData) => position = eventData.Pointer.Result.Details.Point;`

**Comment by davoodkharmanzar** [comment]
> You may be able to go off the pointer object itself, something like `public void OnTeleportCompleted(TeleportEventData eventData) => position = eventData.Pointer.Result.Details.Point;`

thanks for your reply :]
but is this local position or world position?

**Comment by keveleigh** [comment]
Should be in world position, as that's what we use to position the teleport cursor, but if you're seeing otherwise let me know!

**Comment by RogPodge** [comment]
@davoodkharmanzar did this answer your question? If so, may we close this issue?

**Comment by RogPodge** [comment]
Thanks!
