### ISSUE TITLE
Separate user-specific holographic remoting settings to avoid polluting VCS'

### ISSUE THREAD

**Issue by NoTuxNoBux** [microsoft/MixedRealityToolkit-Unity#10143]
## Describe the bug

On OpenXR and Unity 2020, holographic remoting settings seem to be stored in `Assets/XR/Settings/Open XR Package Settings.asset`. This includes the IP address under `m_remoteHostName`, and whether it is enabled or not. By nature, these settings are user-specific, meaning that in a team with multiple developers with different local networks, local changes will keep showing up in Git, but also overwrite settings unless special care is taken.

Because this file seems to contain other important settings as well, it doesn't seem possible to ignore it entirely.

## To reproduce

1. Use the MRTK with Unity 2020, OpenXR, and Git.
2. Modify the OpenXR remoting settings in Unity.
3. Observe them being changed in `Assets/XR/Settings/Open XR Package Settings.asset`.
4. Observe Git changes being logged.

## Expected behavior

These specific settings are either in a separate file that can be fully ignored, or, preferably, somewhere in the new `UserSettings` top-level Unity folder, which can be ignored as a whole and contains settings specific to the user.

## Your setup (please complete the following information)

- Unity Version: 2020.3.11f1
- MRTK Version 2.7.0

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
This is a great callout! I'll bring this back to our Mixed Reality OpenXR Plugin workstream and figure it out.

**Comment by keveleigh** [comment]
This has been updated in the Mixed Reality OpenXR Plugin but hasn't yet been released. I'll update this thread when the next release comes out.

**Comment by keveleigh** [comment]
@NoTuxNoBux Sorry for not updating sooner: this shipped September 7th in the 1.0.3 release. Thanks for the suggestion!
