### ISSUE TITLE
Teleportation System - Select target points in 3D environment

### ISSUE THREAD

**Issue by MiPa12** [microsoft/MixedRealityToolkit-Unity#10152]
## Problem

I have the problem that I need to be able to teleport in the whole 3d environment and not just on a 2d surface.

To clarify it a bit, assume I want to teleport from the black plane to the center of the cube

<img src="https://user-images.githubusercontent.com/61323363/129224048-5da0f2ca-2504-4da1-a733-fce31434ced7.png" width="400" height="400">

With the current version I'm just able teleport to this position when I place an object with a Box Collider to my prefered target position, like so

<img src="https://user-images.githubusercontent.com/61323363/129225084-6bec0116-1956-45b6-b7da-f1d7f0065d1a.png" width="300" height="300">

<img src="https://user-images.githubusercontent.com/61323363/129217767-78a8ca4b-e64a-4830-8a72-eca9f3ee3544.png" width="300" height="300">

Also I realized that I'm restricted to a specific angle of the mesh with the Box Collider, which means when I have a plane with a Box Collider and I turn it to 90° I'm not able to teleport anymore:

<img src="https://user-images.githubusercontent.com/61323363/129217775-85162e49-20c8-4f0e-8dd6-5974b8f717c6.png" width="300" height="300">

## Describe the solution you'd like

How can I change the current teleport pointer to a simple line? I'm looking for a solution which is depicted below

<img src="https://user-images.githubusercontent.com/61323363/129227946-d241b96e-a668-4bf7-8b68-c0a062535c8c.png" width="500" height="400">

I also need a way to change the angle of the target teleport area as it is currently parallel to the ground

<img src="https://user-images.githubusercontent.com/61323363/129229594-68554566-1fc9-4937-b762-164d1a6e036c.png" width="400" height="400">

I would be happy about any advice on this. Thanks

## Target platform 
- WMR immersive
- OpenVR
- HP Reverb G2
- HoloLens 2

**Comment by elbuhofantasma** [comment]
Hello @MiPa12 thank you for submitting this teleportation feature request! I am assigning @RogPodge to investigate.

**Comment by RogPodge** [comment]
For teleporting to angled or sloped surfaces, what should be the user's pose should be after teleporting to that surface? We currently we maintain the user's orientation after a teleport because it reduces discomfort, so I'm not sure that tilting the user's pose would be the correct solution.


As far as making the teleport pointer a line, you can alter the ParabolaPhysicalLineDataProvider component on the teleport pointer prefab so that it's custom gravity is 0. This will make the teleport ray straighten out, though there is still the question of how the user's rotation should behave when targetting an angled surface/wall.

![image](https://user-images.githubusercontent.com/39840334/129751491-1d081c1e-4dea-4f7e-aa8c-54c79df89a8d.png)

**Comment by MiPa12** [comment]
Hi, thanks for the answer. I think my drawing was a bit confusing. The orientation from the user after teleportation should stay the same. I just want to change the position. 
![teleportation](https://user-images.githubusercontent.com/61323363/131398707-d5368e1f-2891-4adc-91cb-6f3df9a9f8eb.png)
Currently, I don't have access to the hardware .I'll test it when I get back to the office. I think turning off the gravity should do the trick

**Comment by RogPodge** [comment]
I think currently we don't change the user's orientation when teleporting to a surface, except for when using the teleport hotspot, which can optionally orient the direction the user is facing with respsect to the y-axis.

Have you been able to get back to the office? If you have do you have a video showing the issues you're encountering?

**Comment by RogPodge** [comment]
ping on this @MiPa12

**Comment by MiPa12** [comment]
I made a little custom version and now it worked. Thanks again
