### ISSUE TITLE
ShellHandRayPointer(Clone)_Cursor disable script/action

### ISSUE THREAD

**Issue by MiPa12** [microsoft/MixedRealityToolkit-Unity#10157]
Hi,
how can I disable the default controller pointer (Right_ShellHandRayPointer(Clone)_Cursor) and afterwards enable it again if necessary during runtime?
Thanks

![Screenshot (71)](https://user-images.githubusercontent.com/61323363/129414306-7b44e6a1-ec88-4dba-bacd-143f068442b9.png)

**Comment by elbuhofantasma** [comment]
Hello @MiPa12 Thank you for submitting this Documentation issue. You can enable/disable the default cursor using [PointerUtils.cs](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Assets/MRTK/SDK/Features/Utilities/PointerUtils.cs). 

You can use the "SetHandRayPointerBehavior" and "SetMotionControllerRayPointerBehavior" classes from lines 178-196 in PointerUtils.cs to enable or disable the pointers at runtime, depending on if you are using Hand Tracking or you are using Motion Controllers. With the "Set[input type]RayPointerBehavior" classes, you can use the [PointerBehavior Enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.toolkit.input.pointerbehavior?view=mixed-reality-toolkit-unity-2020-dotnet-2.7.0) to enable or disable the pointers at runtime by passing the proper PointerBehavior Enum value for disabling or enabling the default cursor.

I am going to close this issue, but please feel free to re-open it if you need more information.
