### ISSUE TITLE
Gesture not being recognized in Hololens 1 using XR SDK 

### ISSUE THREAD

**Issue by akash14darshan** [microsoft/MixedRealityToolkit-Unity#10153]
## Description

Input gesture which was working with the legacy XR no more works with the new XR SDK. In the sample scene in :
``Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionGestureEventsExample.unity`` 
with default settings with no modification what so ever.

However it seems to work on the editor with the same setup.

## Steps to reproduce the behavior:

1. Assets/MRTK/Examples/Demos/HandTracking/Scenes
2. Open the scene HandInteractionGestureEventsExample.unity. Add to build scenes.
3. Build and deploy to device

## Expected behavior

Its expected to see the Hold gesture working on the device with the sphere lighting up, but unfortunately it doesn't work

## Screenshots

![image](https://user-images.githubusercontent.com/13174425/129231933-50a89115-fc2e-4603-abeb-bc1263adaab4.png)

## My Setup

- Unity 2020.3.11f1
- MRTK 2.7.2.0

## Target platform

- HoloLens 1

**Comment by polar-kev** [comment]
@keveleigh, should this have been fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9843?

**Comment by keveleigh** [comment]
Unfortunately, not fully. That only added support for OpenXR, but Windows XR Plugin support is still lacking.

**Comment by keveleigh** [comment]
I'm going to have to close this out as won't fix :( this is not likely to be added to Windows XR Plugin at this point, as Unity has moved most of their efforts onto OpenXR.
