### ISSUE TITLE
Hololens Video recording & images not showing UI elements

### ISSUE THREAD

**Issue by Spoon2311** [microsoft/MixedRealityToolkit-Unity#10155]
## Describe the bug

We're working with the Hololens 2 and sadly when recording a video, taking an image or going into the live-view, Unity UI-components are not shown in the image/video.

We are using: We're using Unity 2020.3.6f1, MRTK 2.7.2 with OpenXR backend.

## To reproduce

Open a Unity project with MRTK 2.7.2 and OpenXR backend.

Create a Window and put one TextMeshPro-Component and a TextMeshProUGUI-Component on it.

When building the application and running it on Hololens 2, both are visible within the device.

Start a recording of what you see through the Hololens 2 or take an image. (You can use voice command or using the main-menu and the corresponding media capture function)

Once the video/photo is saved open the device portal and download the made video/photo.

Opening the photo/video only the TextMeshPro-Component is visible while the TextMeshProUGUI is not.

(You can also use the live-preview, instead of recording a video and the same behaviour should show as if you'd record the scene)

## Expected behavior

I would expect the video/photo to render also Unity UI-Components

## Screenshots

![hqkv6](https://user-images.githubusercontent.com/59868550/129237658-e93645bb-2c5d-4cab-b5f3-f91cb0035128.jpg)
An image of the scene when capturing it with an image.
The title above is a TextMeshPro-Component, below the red line there is text visible for me in the Hololens 2.

## Your setup (please complete the following information)

- Unity Version [ 2020.3.6f1]
- MRTK Version [2.7.2]
- OpenXR backen

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
This was a bug in the Unity engine. It should be fixed on 2020.3.8, 2021.2.0a16, and 2021.1.6f1. Looks like you're on 2020.3.6, so you'll need to update if possible.

**Comment by Spoon2311** [comment]
> This was a bug in the Unity engine. It should be fixed on 2020.3.8f1, 2021.2.0a17, and 2021.1.7f1. Looks like you're on 2020.3.6, so you'll need to update if possible.

Thanks a lot for the answer it was a simple issue of updating! 👍
Problem solved now.

**Comment by wh569860630** [comment]
hello @Spoon2311 I would like to ask how to implement hololens2 video recording function in unity， Thank U...
