### ISSUE TITLE
Project path???

### ISSUE THREAD

**Issue by tiripon** [microsoft/MixedRealityToolkit-Unity#10151]
## Describe the bug

I click Start
It asks for the project path
I click the ... 3 dots
And browse to the project folder which contains the Assets, Packages and ProjectSettings folders
And I'm stuck there because it's expecting me to choose a file not a folder.

Is it a file or a folder that it wants???

You see since it's expecting a file when you click open it opens the Assets folder because it's the first folder at the top.

## To reproduce
I click Start
It asks for the project path
I click the ... 3 dots
And browse to the project folder which contains the Assets, Packages and ProjectSettings folders

## Expected behavior
I expect it to accept the folder and go on with the rest of the process

## Screenshots
![image](https://user-images.githubusercontent.com/1155996/129108866-0fc4b372-6cd2-4157-b1f5-b4291d968884.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.29f1
- MRTK Version I don't know where to find that info but I just downloaded it from MS's site

## Target platform (please complete the following information)

???

**Comment by davidkline-ms** [comment]
@tiripon, thank you for your issue report.

It wants a file. The tool pre-sets the value '_', which does not exist (but that's ok). This is a limitation to the WPF UI framework's implementation of the Windows Common Dialogs. If you navigate to your project folder and select nothing, you should be able to select the project.

I am investigating a better solution and will update as soon as possible.

**Comment by tiripon** [comment]
@davidkline-ms
Thanks for the reply.
Actually, if I select nothing (By clicking into the blank area) and click "Open" it goes in the Assets folder.
Either I keep or I remove the "_" character and click "Open" it still goes into the Assets folder.

There is absolutely nothing I can do that will enable me to proceed to the next step.

**Comment by tiripon** [comment]
UPDATE: I was able to progress by deleting the "_" and type it back in. Then clicking "Open" works.

**Comment by keveleigh** [comment]
Going to close this out as "no repro"
