### ISSUE TITLE
How can I disable the debugger?

### ISSUE THREAD

**Issue by alienshek337** [microsoft/MixedRealityToolkit-Unity#10179]
## Describe the bug

Can't disable the debugger after build the package from visual studio 2019

Here's the screenshot of the debugger
![Screenshot 2021-08-23 181248](https://user-images.githubusercontent.com/68799623/130433954-b39f0053-91ee-4c1c-b1fa-aaab6971065c.png)

## Expected behavior

Building without any debugger

## Your setup (please complete the following information)

- Unity Version 2020.3.13f1
- MRTK Version 2.7.2

## Target platform (please complete the following information)

- HoloLens 2

**Comment by MaxWang-MS** [comment]
Please see discussion thread #10116 for the solution.
