### ISSUE TITLE
TestGazeProviderTargetUnityUi fails sporadically

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#10170]
## Describe the bug

The play mode test `TestGazeProviderTargetUnityUi` fails sporadically when testing in-editor. 

## To reproduce

1. Run the `FocusProviderTests` in editor.
2. May need to run them several times to repro the sporadic failure

## Expected behavior

Tests should either pass every time or fail every time... nondeterministic tests are scary!

## Screenshots

![image](https://user-images.githubusercontent.com/5544935/129947981-6bcc8356-a82a-4e45-a208-8a031ebbea68.png)

## Your setup (please complete the following information)

- Unity 2019.4.28f1
- MRTK `main` at time of posting
- x86/Standalone current build target
- No VR HMD connected

**Comment by polar-kev** [comment]
Closing since reported as fixed during issue triage meeting.
