### ISSUE TITLE
Input simulation error on 2.7.2 + 2020.3.11

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#10171]
## Describe the bug
When I run input simulation (click the play button) I see these messages and input simulation is not working. (Game mode screen is on)

InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.
UnityEngine.Input.GetKeyDown (UnityEngine.KeyCode key) (at <6af207ecd21044628913f7cc589986ae>:0)
Microsoft.MixedReality.Toolkit.Windows.Input.WindowsSpeechInputProvider.Update () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@e0afa285b30b-1624597398823/Providers/Windows/WindowsSpeechInputProvider.cs:202)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem.Update () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@e0afa285b30b-1624597398823/Core/Services/BaseDataProviderAccessCoreSystem.cs:51)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit+<>c.<UpdateAllServices>b__72_0 (Microsoft.MixedReality.Toolkit.IMixedRealityService service) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@e0afa285b30b-1624597398823/Core/Services/MixedRealityToolkit.cs:1054)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit.ExecuteOnAllServicesInOrder (System.Action`1[T] execute) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@e0afa285b30b-1624597398823/Core/Services/MixedRealityToolkit.cs:1145)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit.UpdateAllServices () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@e0afa285b30b-1624597398823/Core/Services/MixedRealityToolkit.cs:1054)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit.Update () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@e0afa285b30b-1624597398823/Core/Services/MixedRealityToolkit.cs:727)

## To reproduce
Import MRTK 2.7.2 Foundation and Standard Assets through MR Feature Tool
Create a new scene
Use the MRTK menu Add to scene and Configure
Run the scene.

## Screenshots
<img width="753" alt="2021-08-18 13_25_30-unity - TestPage - Universal Windows Platform - Unity 2020 3 11f1_ _DX11_" src="https://user-images.githubusercontent.com/13754172/129968997-b9fff673-2cc3-4f49-ab2f-b4387f14b3ea.png">

## Your setup (please complete the following information)

- Unity Version 2020.3.11f1
- MRTK Version 2.7.2 (Through MR Feature Tool)

**Comment by keveleigh** [comment]
This is currently a known issue, tracked by https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9703.
The configurator _should_ prompt you to update to "Both", but you can also do it manually in the Player Settings under Other Settings at 
![image](https://user-images.githubusercontent.com/3580640/129972020-4c739206-0e54-48ae-b835-7188bd6d4fea.png)

**Comment by cre8ivepark** [comment]
Active Input Handling under Player Settings > Other Settings > Configuration 
With update to 'Both', Input simulation works well.

**Comment by keveleigh** [comment]
Going to close this and leave #9703 for tracking
