### ISSUE TITLE
MRTK console errors when imported in latest versions of Unity 2021.2

### ISSUE THREAD

**Issue by IslamAbdlhalim** [microsoft/MixedRealityToolkit-Unity#10182]
## Describe the bug

Mixed Reality Toolkit packages don't work on the latest versions of 2021.2 on Unity which is 2021.2.0b9. When installing Mixed Reality Toolkit Foundation and Mixed Reality Toolkit Standard Assets on to a project, it will cause Console errors.
 
## To reproduce

1. Create a Unity project
2. Open Mixed Reality Tool Kit
3. Import Mixed Reality Tool Kit Foundation and Mixed Reality Tool Kit Standart Assets package
4. Open project on Unity Editor
5. Observe errors in the Console window 

## Screenshots

2021.2.0b9: Doesn't work, will display a lot of errors
![image](https://user-images.githubusercontent.com/81768496/130602009-bdd57a40-d4a7-4361-a9e6-c46a6363fa52.png)
2021.2.0b5: Doesn't work. but will display fewer amount of errors
![image](https://user-images.githubusercontent.com/81768496/130602151-bcc0d8d5-4cd7-4f28-9c04-6698425ff70d.png)
2021.2.0a17: Works and won't display any errors
![image](https://user-images.githubusercontent.com/81768496/130602222-24b81a18-17e6-40ca-ab07-a4cf18747662.png)

## Your setup (please complete the following information)

- Unity Version 2021.2.0b9
- MRTK Version 2.7.2

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

## Additional context
I'm not sure at which Unity version does it stop working. But it works completely fine in Unity 2021.2.0a17

**Comment by IslamAbdlhalim** [comment]
Hey, this issue is also apparent in 2022.1.

**Comment by keveleigh** [comment]
The System.Numerics issue looks tracked on Unity's side, with a fix in review for 2022.1 and planned for 2021.2: https://issuetracker.unity3d.com/issues/compiler-error-cs0433-when-using-types-from-the-system-dot-numerics-namespace-under-net-standard-2-dot-1

The "unassigned guid" issue is fixed in the latest MRTK dev branch via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9938. It'll be in our next release!

**Comment by polar-kev** [comment]
@keveleigh, is there anything outstanding for this issue?

**Comment by keveleigh** [comment]
> @keveleigh, is there anything outstanding for this issue? 

Not that I'm aware of! Every change is in the dev branch. Just needs to be in a release.
