### ISSUE TITLE
GLTF object appears black when it is loaded with Unity's Standard shader

### ISSUE THREAD

**Issue by wonkee-kim** [microsoft/MixedRealityToolkit-Unity#10195]
## Describe the bug

When loading gltf, and if there's no MixedRealityStandard shader, ConstructGLTF creates materials using Unity's Standard shader.
And if the main color data is null, CreateStandardShaderMaterial() assigns the null data to the main color of the material so the gltf object appears black.
This can be avoided by checking the color data is null as like the same as CreateMRTKShaderMaterial() does.

## To reproduce

1. Have gltf object that doesn't have color data.
2. Load the gltf object using MRTK's gltf utility.
3. The object appears black.

## Expected behavior

The main color shouldn't be assigned and keep the default white color.

## Screenshots

![black](https://user-images.githubusercontent.com/830808/131764698-86b02bc9-d74b-4716-b4c5-49e353ef378b.JPG)

## Your setup (please complete the following information)

- Unity Version [2020.1.17f1]
- MRTK Version [v2.0]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- Quest
- OpenVR

## Fix

This can be fixed by adding lines on **_Assets/MRTK/Core/Utilities/Gltf/Serialization/ConstructGLTF.cs_** between line 363 as below.
~~material.color = gltfMaterial.pbrMetallicRoughness.baseColorFactor.GetColorValue();~~
```
if (gltfMaterial.pbrMetallicRoughness?.baseColorFactor != null)
{
    material.color = gltfMaterial.pbrMetallicRoughness.baseColorFactor.GetColorValue();
}
```

**Comment by davidkline-ms** [comment]
@wonkee-kim, Thanks for the report and the suggested fix! Would you be willing to submit a PR with the proposed change?

thanks!

**Comment by wonkee-kim** [comment]
Yeah I would like to. If you can give me an access to push a branch, I will make one.
Cheers!

**Comment by keveleigh** [comment]
@wonkee-kim We've tended to recommend making a fork of the repo in order to create PR branches. More info can be found at https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/contributing/contributing?view=mrtkunity-2021-05#contribution-process! Thanks!

**Comment by wonkee-kim** [comment]
> @wonkee-kim We've tended to recommend making a fork of the repo in order to create PR branches. More info can be found at https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/contributing/contributing?view=mrtkunity-2021-05#contribution-process! Thanks!

Thank you for the instruction! I just made a PR here.
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10209
