### ISSUE TITLE
Scene system errors occur in projects using MixedRealityFeatureTools.

### ISSUE THREAD

**Issue by HoloMoto** [microsoft/MixedRealityToolkit-Unity#10199]
## Describe the bug

When I try to use the scene system in a Unity project with MRTK imported by MixedReality FeatureTools, I get a lot of dialogs saying "It is not allowed to open a scene in a read-only package. 

## To reproduce

1. Use the MixedRealityFeatureTool to deploy the MRTK Foundation, Tools, Examples, and Extentions packages.
2. Configure MRTK in the scene and enable the scene system in the MixedRealityToolkit configuration.
3. Set the scene system to [MixedRealitySceneSystem].
4. Sets the default MixedRealitySceneSystem.
5. A dialog box will appear.　"It is not allowed to open a scene in a read-only package."

## Expected behavior

The dialog is looping, appearing even after at least a thousand of them have been erased.

This may be due to the fact that MRTK is imported into the Package by using MixedRealityFeatureTools instead of directly under Assets.

## Screenshots

![スクリーンショット 2021-09-03 154925](https://user-images.githubusercontent.com/36409613/132113247-3850ce05-ad07-4ae8-8632-08b94904d66f.png)

## Your setup (please complete the following information)

・Unity 2021.1.19f1
・MixedRealityFeatureTool-1.0.2104.4-Beta
・MRTK v2.7

## Target platform (please complete the following information)

- HoloLens 2

**Comment by HoloMoto** [comment]
I found an issue with a similar problem. This may be helpful.
However, when I place the DefaultMixedRealitySceneSystemProfile from Colne in Assets, the same dialog occurs whether I close or close it.
https://github.com/microsoft/MixedReality-WebRTC/issues/526

**Comment by davidkline-ms** [comment]
Investigate which default scenes are in the immutable folder and possibly create a migration code path

**Comment by RogPodge** [comment]
Marking as closed since we're no longer using the scene system.
