### ISSUE TITLE
Visual Studio 2017 is required to build projects using the MRTK

### ISSUE THREAD

**Issue by serup** [microsoft/MixedRealityToolkit-Unity#10196]
Visual Studio 2017 is required to build projects using the MRTK

_Originally posted by @StephenHodgson in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/1830#issuecomment-372893353_

It saw a similar issue with Visual Studio 2019 installed

**Comment by StephenHodgson** [comment]
Unity should be installing this dependency if it is required. the full 2017 installation isn't required, but the build tools installer is.

I believe this also depends on the Unity editor version and UWP sdk versions you're targeting.

**Comment by StephenHodgson** [comment]
An example of errors you might expect to see if missing workloads:
```
  il2cpp.exe didn't catch exception: System.InvalidOperationException: C++ code builder is unable to build C++ code. In order to build C++ code for Universal Windows Platform, you must have one of these installed:
          Visual Studio 2015 with C++ compilers and Windows 10 SDK (it cannot build C++ code because it is not installed or missing C++ workload component)
          Visual Studio 2015 installation is found by looking at "SOFTWARE\Microsoft\VisualStudio\14.0_Config\InstallDir" in the registry
          Windows 10 SDK is found by looking at "SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0\InstallationFolder" in the registry
          Visual Studio 2017 (or newer) with C++ compilers and Windows 10 SDK (it cannot build C++ code because architecture ARM64 is not supported by this Visual Studio version)
          Visual Studio 2017 (or newer) installation is found using Microsoft.VisualStudio.Setup.Configuration COM APIs
```

**Comment by StephenHodgson** [comment]
If this happens simply open Visual Studio 2019+ and it should prompt you to install the missing requirements

**Comment by keveleigh** [comment]
> It saw a similar issue with Visual Studio 2019 installed

Can you expand a bit on the Visual Studio and Unity versions you're using please?
And also paste a selection of the errors you're seeing, if possible. Thanks!

**Comment by keveleigh** [comment]
Going to close this one out, since it's been a few months without activity. Please reopen if you're still having trouble and we'll figure it out!
