### ISSUE TITLE
Update BuildAndDeployPortal

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1020]
- [x] Add quick options to switching between IHMDs and HoloLens
- [x] Manually add IP of remote devices
- [x] Install via WiFi
- [x] Better enumeration of Appx Package folders. #1136
- [x] Fixed Build window incrementing the reserved number for Windows Store Apps #1402
- [x] Add support for installing on local machine (for IMHD apps)
- [x] HTTPS support #98

**Comment by BenWoodford** [comment]
> It would be nice if I could cancel the search and manually enter the IP of my HoloLens.

**Comment by StephenHodgson** [comment]
Just a taste of how the new build window will look.

Added some tabs and organized everything.

![image](https://user-images.githubusercontent.com/13334553/33299296-cd49348a-d39f-11e7-9e76-74abd4c49c5b.png)
![image](https://user-images.githubusercontent.com/13334553/33299304-d8464ab2-d39f-11e7-87d8-e346ba9721f6.png)
![image](https://user-images.githubusercontent.com/13334553/33299346-01a4c67c-d3a0-11e7-9039-8cdb457abdd1.png)
![image](https://user-images.githubusercontent.com/13334553/33299364-110a4402-d3a0-11e7-891d-fc7def0a26e8.png)

**Comment by hanzz0502** [comment]
I want to manually enter the IP of my HoloLens,but I can't find the options like "Deploy Options",which is different from your's,why?    This is the screenshot of the "Build Window"

![buildwindow](https://user-images.githubusercontent.com/26197589/33710919-0ba45068-db7d-11e7-9c7a-1425a5ef6a85.png)

**Comment by StephenHodgson** [comment]
Because the screen shots are what the build window will look like when the changes are merged.

**Comment by hanzz0502** [comment]
Then what can I do in this "Build Window" which is different from your's,if I want to manually enter the IP of my HoloLens

**Comment by StephenHodgson** [comment]
You can't

**Comment by hanzz0502** [comment]
Is there any configuration file I can used to change the IPAddress instend of "127.0.0.1"?
The Build Window can't find the IPAddress of Hololens itself even though Hololens is running,what can I do?Linking Hololens to PC by usb?

**Comment by StephenHodgson** [comment]
It's currently unimplemented and my PR addresses that. Yes, the only way is currently via USB.

**Comment by shllybkwrm** [comment]
Can't you build the Visual Studio package and deploy it to your IP of choice from there?

**Comment by hanzz0502** [comment]
I can use Visual Studio to deploy it to the Hololens. But I think ,using the build window to deploy it to Hololens can be faster.
