### ISSUE TITLE
Depth Buffer Format settings

### ISSUE THREAD

**Issue by maradanovic** [microsoft/MixedRealityToolkit-Unity#10214]
## Describe the bug

Depth Buffer Format is set to 16 bit in Setting-> XR Plugin Management -> Windows Mixed Reality. 
Despite this, I get "Depth Buffer Sharing has 24-bit depth format selected. Consider using 16-bit for performance." notification on play.

## Expected behavior

No notification on run.

## Your setup (please complete the following information)

- Unity Version [2019.4.16f1]
- MRTK Version [v2.4]

## Target platform (please complete the following information)

- HoloLens

**Comment by polar-kev** [comment]
Hey @radacadabra are you sure this was in MRTK 2.4? If so, could you please update to a later version of MRTK? I don't believe this was supported in MRTK 2.4.

**Comment by maradanovic** [comment]
Solved by updating MRTK.
