### ISSUE TITLE
IconSet inspector is broken

### ISSUE THREAD

**Issue by FejZa** [microsoft/MixedRealityToolkit-Unity#10229]
## Describe the bug

The inspector for custom icon sets is broken it seems and does not allow adding any icons.

![image](https://user-images.githubusercontent.com/9565734/134341195-d1bbddcf-be3e-47a3-ab84-dc60e204ff6a.png)

## To reproduce

1. Create icon set using `Assets->Create->Mixed Reality->Toolkit->IconSet`
2. Select the created file
3. See error

## Expected behavior

I am able to add icons.

## Screenshots

![image](https://user-images.githubusercontent.com/9565734/134341354-3cf88e15-3683-4cb5-97c7-93af8cd372cf.png)

**Comment by polar-kev** [comment]
Hey @FejZa, can you let us know which Unity version and MRTK version you saw this in?

**Comment by polar-kev** [comment]
@RogPodge, I saw this message from the HoloDeveloper Slack on this issue,

> I had a quick look at the code and the problem looks to be that the new array UI in unity 2020 includes it's own foldout using the same BeginFoldoutHeaderGroup call, so when MRTK wraps it, it's created a nested foldout which isn't supported.

**Comment by FejZa** [comment]
@polar-kev sure. This is

- Unity 2020.3.18.f1
- MRTK 2.7.2

**Comment by RogPodge** [comment]
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9999 

We've pushed in a fix for this, it looks like it just missed out 2.7.2 window. It'll be fixed in the next release!
