### ISSUE TITLE
ShellHandRayPointer Cursor appears at origin for one frame when hand is detected

### ISSUE THREAD

**Issue by WikkidEdd** [microsoft/MixedRealityToolkit-Unity#10236]
## Describe the bug

When a hand is detected, the ShellHandRayPointer Cursor spawns at the origin of the scene and is visible for one frame before it is updated into the correct position. This happens both in editor and on the HoloLens. It is particularly noticeable on the HL when your hands are on the border of being detected and it flickers on and off rapidly.  

The gifs shows the scene view pointing at the origin and the game view when the hand comes on you can see a one frame flicker of the cursor at the origin

![CursorFlicker](https://user-images.githubusercontent.com/1579290/134703549-4d1d7e0b-2691-4a5b-a4f9-4d59eb20778a.gif)

This is a freeze-frame when it appears
![SingleFrame](https://user-images.githubusercontent.com/1579290/134705270-d6654744-95f6-4bcb-8f76-3564ff2b4eba.jpg)

## To reproduce

In Editor
1. Install the latest version of MRTK including examples.
2. Open the HandInteractionExamples scene
3. Press Play
4. Toggle simulated hand on and off
5. Observe the origin in the scene view

On Hololens 2
1. Install the latest version of MRTK including examples.
2. Build and run HandInteractionExamples scene
3. Take note of where your HL2 was when it started the app
4. Move so you can see where your HL2 was when it started (aka the scene origin)
5. Move your hands in and out of view while watching the scene origin

## Expected behavior

Cursor should only appear in the correct position at the end of the pointer,

## Your setup (please complete the following information)

- Unity Version 2020.3.6
- MRTK Version 2.7.2

## Target platform (please complete the following information)

- HoloLens 2
- Unity Editor

**Comment by zxubian** [comment]
Also experiencing this bug.
