### ISSUE TITLE
MRTK Tools Build Window stuck in Importing Assets loop after accessing Visual Studio project.

### ISSUE THREAD

**Issue by b-huynh** [microsoft/MixedRealityToolkit-Unity#10248]
## Describe the bug

Building an MRTK project using the Build Window provided in MRTK Tools, and then subsequently accessing the Visual Studio project to build an app package, causes the Unity Editor to get stuck in a loop of constantly "Importing Assets" indefinitely. This renders Unity unusable until it is restarted.

## To reproduce

1. Create an MRTK app for HoloLens 2 in Unity, following the [HoloLens 2 development fundamentals exercise](https://docs.microsoft.com/en-us/learn/modules/learn-mrtk-tutorials/1-3-exercise-configure-unity-for-windows-mixed-reality)
2. In the Unity Editor, go to 'Build Window'
3. Click on 'Build Unity Project'
4. Once build is complete, click on 'Open in Visual Studio'
5. After visual studio has opened, go back to the Unity Editor.
6. Unity attempts to "Import Assets" and continues indefinitely (I've waited at least 30 minutes).

## Expected behavior

The "Importing Assets" window should not appear after the build is complete. It should not reappear continuously every time I switch to the Unity Editor window.

## Screenshots

![Stuck importing assets 2](https://user-images.githubusercontent.com/1728231/136274515-71972227-1bdb-4dfb-a5a6-e71aa4c0bfb9.png)
![Stuck importing console](https://user-images.githubusercontent.com/1728231/136274531-89e90225-7179-4760-af76-49371abc17bb.png)

## Your setup (please complete the following information)

- Unity 2020.3.19f1 (LTS)
- MRTK Foundation 2.7.2
- MRTK Tools 2.7.2
- MRTK OpenXR Plugin 1.0.3
- Visual Studio 2019 16.11.4

## Target platform (please complete the following information)

- HoloLens 2 (ARM64)

## Additional context

Problem does not occur when building using Unity Build Settings (Ctrl + Shift + B) and opening the Visual Studio Project manually through file explorer. Screenshot of stuck prompt and the console output generated after build included above.

**Comment by Zee2** [comment]
Closing as duplicate, see above.
