### ISSUE TITLE
If the Unity splash screen is disabled for an OpenXR hololens 2 app where spatial awareness is enabled, the spatial mesh is not built.

### ISSUE THREAD

**Issue by larryNexus** [microsoft/MixedRealityToolkit-Unity#10245]
## Describe the bug

If the Unity splash screen is disabled for an OpenXR hololens 2 app where spatial awareness is enabled, the spatial mesh is not built. In the same project, if the splash screen is enabled, the spatial mesh is built and functions properly.

## To reproduce

1. Create an MRTK app in Unity for hololens 2 with spatial awareness enabled by following the MRTK project setup instructions  [here](https://docs.microsoft.com/en-us/learn/modules/learn-mrtk-tutorials/1-3-exercise-configure-unity-for-windows-mixed-reality).
2. Switch to UWP build platform, then build and run the app on hololens 2.
3. See that spatial awareness and the spatial mesh are running properly
4. Disable the unity splash screen in the project settings
5. Build and run the app again
6. See that the spatial awareness is not functioning properly and the spatial mesh is not created

To make it easy to reproduce this error, I have created a nearly-empty MRTK project repository on github.

The only modifications to this project as compared to the MRTK tutorial instructions are:
* Cloned the default hololens 2 MRTK configuration to enable spatial mesh and set mesh visibility to occlusion
* Added an ErrorManager that receives any exceptions thrown and displays them on a camera-anchored canvas

The repository for that project is [here](https://github.com/larryNexus/mrtk-testing).

## Expected behavior

Disabling the Unity splash screen should not affect the proper functioning of the MRTK spatial awareness mesh.

## Your setup

- Unity Version: 2020.3.17 and 2020.3.8
- MRTK Version: 2.7.2
- MRTK OpenXR: 1.0.1, 1.0.3
- com.unity.xr.openxr 1.2.8

## Target platform (please complete the following information)

- HoloLens 2, ARM or ARM64

**Comment by keveleigh** [comment]
For some reason, I wasn't able to repro this 🤔 based on looking at the code though, i think there's a good chance this will be fixed via #10366

**Comment by keveleigh** [comment]
Going to close this out, as I'm unable to repo with the meshing fix in 2.7.3
