### ISSUE TITLE
Oculus hands&controllers not visible when using OpenXR on Oculus Runtime

### ISSUE THREAD

**Issue by eusebiu** [microsoft/MixedRealityToolkit-Unity#10242]
## Describe the bug

Oculus hands&controllers not visible when using OpenXR on Oculus Runtime.

## To reproduce

1. Install MRTK 2.7.2, Oculus runtime (latest)
2. Create a OpenXR profile based on the default one
3. Do the configuration in XR Management to use OpenXR and Oculus Touch controllers
4. Run app on Oculus Runtime.

## Expected behavior

Controllers and hands should be visible. Controllers became visible if SteamVR is used as the default XR runtime but they disappear if menu controller button is pressed.

## Your setup (please complete the following information)

- Unity 2021.1.21
- MRTK 2.7.2

## Target platform (please complete the following information)

- Oculus Quest 1 (both Oculus and SteamVR runtimes)

**Comment by eusebiu** [comment]
Hey @polar-kev - I don't think this has to do with Unity 2021. Does the scenario work on Unity 2020?

**Comment by berndolauerto** [comment]
This is the same behavior as my submitted bug. This has to do with the OpenXR implementation of the Oculus Integration Tools. 

![image](https://user-images.githubusercontent.com/24796274/136518425-ca866137-0c21-4ea4-bca2-3ffd14f307fa.png)

**Comment by eusebiu** [comment]
OpenXR might not support all XR SDK features but at least the controllers should be visible, no? :)

**Comment by RogPodge** [comment]
Should be addressed with

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10574
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10568
