### ISSUE TITLE
Azure Spatial Anchor doesn't work

### ISSUE THREAD

**Issue by mins-verse** [microsoft/MixedRealityToolkit-Unity#10260]
## Overview

Hi, I have a problem about Azure Spatial Anchor in the tutorial from Microsoft Document.

Here is the link:
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-05

I followed all instruction and the log showed me that it worked but the anchor wasn't updated.
In other words, the position and rotation of the object from each user was different although I finished all process for sharing the anchor, such as start session,  create anchor, share anchor, and get anchor.

Can you let me know how I can fix it?

## Expected behavior

After the process, the users can share the same position and rotation of the shared object which is with anchor.

## Actual behavior

There was no difference between before the process and after the process.

## Steps to reproduce

Here are the images which I captured from two Hololens, A and B:

HoloLens A
![20211014_172043_HoloLens (2)](https://user-images.githubusercontent.com/87890982/137398790-bf7f2979-4ba5-4ddb-aaee-c961f33f8dc7.jpg)

Hololens B
![20211014_142019_HoloLens (2)](https://user-images.githubusercontent.com/87890982/137399044-9504aa48-39b4-4502-b018-559771dd7ef6.jpg)

## Unity editor version
Unity 2020.3.18

## Mixed Reality Toolkit release version
MRTK 2.7.2

**Comment by fxjoanny** [comment]
Hi,
I have exactly the same issue.
To answer you :
1. Yes, I use OpenXR
2. When my Azure anchor os located successfully, I have a position with (2.7, 0.0, -1.1) and a rotation with (0.0, 0.5, 0.0, -0.9)

I hope it might help.
Thank you for your help.

**Comment by fxjoanny** [comment]
After further researches, I found a solution [here](https://github.com/Azure/azure-spatial-anchors-samples/issues/307#issue-1020197758).
The AnchorModuleScript is missing the alignement stuff. It quite solve the problem for me.
Now the object correctly rotated but the object is at the place of the avatar for me.

**Comment by polar-kev** [comment]
> After further researches, I found a solution [here](https://github.com/Azure/azure-spatial-anchors-samples/issues/307#issue-1020197758). The AnchorModuleScript is missing the alignement stuff. It solved the problem for me.

@mins-verse did this solution work for you as well?

**Comment by polar-kev** [comment]
Hi @mins-verse, I'm going to close this issue since @fxjoanny proposed a solution. If that solution does not work for you, you can reopen the issue.
