### ISSUE TITLE
Input System should easily handle update from 2017.1 to 2017.2

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1027]
We should think of a way for our Input System to be forward compatible to keep older projects on the cutting edge.

**Comment by paseb** [comment]
The only way you can support that is a light weight abstraction layer.

**Comment by StephenHodgson** [comment]
I think you're right. I was thinking about getting started on back porting some of the input changes and marking the ole references obsolete. Luckily a lot of the system is self contained, so there shouldn't be too much to update on the dev side.

The biggest change will be the event data and API changes, but hopefully those will get updated for free with the unity updater.
