### ISSUE TITLE
Requesting for downloading the app "designing holograms" on HoloLens 2

### ISSUE THREAD

**Issue by 962557346** [microsoft/MixedRealityToolkit-Unity#10281]
## Describe the problem

Hi. I want to download the app "designing holograms" on HoloLens 2. Because I can't open the Microsoft store due to the Web Proxy, so I download the app from microsoft website, but it tolds me that "It looks like you don’t have any applicable device(s) linked to your Microsoft account. To install, sign in on a device with your Microsoft account." However, I always sign in on my HoloLens 2 with my account. 

![image](https://user-images.githubusercontent.com/24918185/139064692-c4c58ab3-e0f4-48c3-88cb-1b81a40ec2aa.png)

## Describe the solution you'd like

Use the app "designing holograms" on HoloLens 2 or my computer.

## Describe alternatives you've considered

No.

**Comment by polar-kev** [comment]
Hey @962557346, this is outside the scope of the MRTK team.  I recommend filing this bug on Feedback Hub.
You can find Feedback bug by selecting the Start  button, and then typing or selecting Feedback Hub.

Full instructions here: https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332
