### ISSUE TITLE
MRTK BoundsControl destroys Box Collider or NearInteractionGrabbable

### ISSUE THREAD

**Issue by iweinbau** [microsoft/MixedRealityToolkit-Unity#10290]
## Describe the bug

When the` OnDisable()` function is called on `BoundsControl` The `NearInteractionGrabbalble` is removed when the `BoundsControl` has an `Bounds Override` assigne to it. Otherwise it removes the `Box Collider` attached to the same gameobject.

## To reproduce
1. Create a game object with a `BoundsControl`, `Box Collider` and `NearInteractionGrabbable`
2. Disable `BoundsControl` or disable gameobject
3. The `NearInteractionGrabbable` or the `Box Collider` gets removed from the game object. 

## Expected behavior

The `BoundsControl` is deactivated while the other compents are still on the gameobject.

## Your setup (please complete the following information)

- Unity Version 2020.3.17f1
- MRTK Version v2.7.2

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

I'm trying to disable game objects from script. However, I do not want to add new components everytime I disable gameobjects with a `BoundsControl` attached to it.

**Comment by polar-kev** [comment]
Hey @iweinbau, when you re-enable bounds control does the NearInteractionGrabbable get re-added?

**Comment by iweinbau** [comment]
No, once the nearinteractiongrabbable component is removed it remains removed even after activating the boundscontrol
