### ISSUE TITLE
Can not genrate build

### ISSUE THREAD

**Issue by sw-ms-ankitsangani** [Microsoft/MixedRealityToolkit-Unity#1029]
after download unity2017.2 Dev branch can not generate builds for HoloLens. I faced 7 error in ControllerVisualizer.cs script which mention below

1 => Assets\HoloToolkit\Input\Scripts\ControllerVisualizer.cs(145,24): error CS1061: 'SpatialInteractionSource' does not contain a definition for 'Handedness' and no extension method 'Handedness' accepting a first argument of type 'SpatialInteractionSource' could be found (are you missing a using directive or an assembly reference?)

2 => Assets\HoloToolkit\Input\Scripts\ControllerVisualizer.cs(145,38): error CS0103: The name 'SpatialInteractionSourceHandedness' does not exist in the current context

3 => Assets\HoloToolkit\Input\Scripts\ControllerVisualizer.cs(149,29): error CS1061: 'SpatialInteractionSource' does not contain a definition for 'Handedness' and no extension method 'Handedness' accepting a first argument of type 'SpatialInteractionSource' could be found (are you missing a using directive or an assembly reference?)

4 => Assets\HoloToolkit\Input\Scripts\ControllerVisualizer.cs(149,43): error CS0103: The name 'SpatialInteractionSourceHandedness' does not exist in the current context

5 => Assets\HoloToolkit\Input\Scripts\ControllerVisualizer.cs(162,92): error CS1061: 'SpatialInteractionController' does not contain a definition for 'TryGetRenderableModelAsync' and no extension method 'TryGetRenderableModelAsync' accepting a first argument of type 'SpatialInteractionController' could be found (are you missing a using directive or an assembly reference?)

6 => Assets\HoloToolkit\Input\Scripts\ControllerVisualizer.cs(212,69): error CS1061: 'SpatialInteractionSource' does not contain a definition for 'Handedness' and no extension method 'Handedness' accepting a first argument of type 'SpatialInteractionSource' could be found (are you missing a using directive or an assembly reference?)

Thanks,
Ankit Sangani

**Comment by Andre-Rb** [comment]
I noticed this too yesterday.
Felt back to the master branch, cannot help you further sorry.

**Comment by sw-ms-ankitsangani** [comment]
I faced same error in master branch also after that move back to holotoolkit 2017.1.f1

**Comment by StephenHodgson** [comment]
Use the pre-release of the dev branch for now, as we're moving to stabilize it with the master branch.

You're going to get the same errors in the master branch because none of the new APIs are in 2017.1.

**Comment by StephenHodgson** [comment]
I'm also interested to know what version of unity you were using and your build settings.

**Comment by sw-ms-ankitsangani** [comment]
I'm using unity 2017.2.0f1

**Comment by StephenHodgson** [comment]
And your build settings?

**Comment by sw-ms-ankitsangani** [comment]
10.0.15063.0 this is latest installed in pc

**Comment by StephenHodgson** [comment]
Well, there's your problem. You'll need the 10.0.16 SDK and the pre-release RS3 windows insider preview build of Windows 10.

**Comment by StephenHodgson** [comment]
![screenshot_20170927-043744](https://user-images.githubusercontent.com/13334553/30911498-b46e6d64-a33d-11e7-9cec-d6021ad40efb.jpg)

**Comment by sw-ms-ankitsangani** [comment]
Thanks @StephenHodgson for help.

**Comment by StephenHodgson** [comment]
No worries, glad to help 😁

**Comment by DaveAccenture** [comment]
If a new SDK is required, then the  bug is that it is not provided, either by Unity or MS when installing Unity or the MRTK. Please provide for this!

**Comment by keveleigh** [comment]
@DaveAccenture A compatible SDK is provided in the Visual Studio 2017 installer, if you run it and modify your installation.

![image](https://user-images.githubusercontent.com/3580640/36502288-584b22ea-16fe-11e8-8c5f-b6c07a5bfbd8.png)

**Comment by StephenHodgson** [comment]
@DaveAccenture

Visual studio is also a requirement and the download is provided there upon installation.

**Comment by DaveAccenture** [comment]
Thanks. Shouldn't that have happened automatically when I installed 2017.3.1p1? Or does it see that VS is installed and not bother checking for updates?
