### ISSUE TITLE
Scene Understanding: objects are rotated around the origin in editor playmode with remoting

### ISSUE THREAD

**Issue by mihaits** [microsoft/MixedRealityToolkit-Unity#10307]
## Describe the bug

When using Scene Understanding through holoremoting, the returned spatial data objects are rotated around the scene origin (0, 0, 0) relative to where they should be with a seemingly arbitrary offset.

## To reproduce

Enable Spatial Awareness System.
Add a Windows Scene Understanding Observer.
Observe as the returned meshes/planes are offset from real world surfaces.

## Screenshots

![scene understanding bug](https://user-images.githubusercontent.com/27222926/141122191-64e0cd20-a632-4369-818b-b09327e7a9a7.png)

## Your setup

- Unity  2021.1.28f1
- MRTK 2.7.3
- Mixed Reality OpenXR plugin 1.1.2
- Scene Understanding 0.6.0 package

## Target platform 

- Unity Editor with remoting

**Comment by MaxWang-MS** [comment]
Hi @mihaits, thanks for reporting this issue. We have yet to officially support Scene Understanding via Remoting due to a recently resolved limitation in one of our dependencies. We will add SU via remoting support in the coming release. cc: @keveleigh
