### ISSUE TITLE
Green platform when building to Quest 2 from Unity?

### ISSUE THREAD

**Issue by reeseras** [microsoft/MixedRealityToolkit-Unity#10300]
## Describe the bug

I don't know why this suddenly started happening, but all of my unity projects now create this green platform when I build them to the headset.

## To reproduce

I have no idea how to reproduce this. 

## Expected behavior

No Green platform. Especially on older projects.

## Screenshots
![Incorrect Scene](https://user-images.githubusercontent.com/26148056/140582859-87187ae7-cc01-4aff-8b74-1ffc3f5a32b8.jpg)

![com dsu MRTK272-20211105-154231](https://user-images.githubusercontent.com/26148056/140582836-04ce39a2-7bf6-42b5-8dbf-af3262eb1ea0.jpg)

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.3.19f1
- MRTK Version v2.7.2

## Target platform (please complete the following information)

Quest 2

## Additional context

I've also submitted this to Unity general forums:
https://forum.unity.com/threads/green-platform-when-building-to-android-for-oculus-quest-2.1193545/

**Comment by reeseras** [comment]
As an update, it seems platform only appears if I have a roomscale guardian set up. If I use a stationary guardian it's not there.

**Comment by polar-kev** [comment]
Hey @reeseras, if you go to the Boundary Visualization Settings section of the profile system, you can turn off "Show" under Floor Settings or change it to another color.
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/boundary/boundary-system-getting-started?view=mrtkunity-2021-05#configure-boundary-visualization

**Comment by reeseras** [comment]
Thanks so much! Not sure how I turned this on or didn't notice it before.
