### ISSUE TITLE
MixedRealityPlayspace keeps being created, camera bug.

### ISSUE THREAD

**Issue by jarrettd96** [microsoft/MixedRealityToolkit-Unity#10301]
## Describe the bug
Hello, i recently converted my unity project to a MRTK and getting ready to export it to my hololens 2 for testing. I keep getting an error where i have a playspace already thats set as main camera but once i exit out of unity and reopen it, unity will duplicate the playspace and put the one i want as a child to the new one that was just made. This gives me an error were there are too many cameras etc. below i uploaded a video to streamable thats a minute long and shows exactly what im talking about and what happens. Any suggestions or idea, been messing with this for a few hours and cant figure it out. 

## Screenshots

https://streamable.com/oxy5iq

## Target platform (please complete the following information)

- HoloLens 2
- OpenVR

First time posting sorry if format is wrong

**Comment by polar-kev** [comment]
Hi @jarrettd96 it looks like your project has ended up in a weird state with the MixedRealityPlayspace gameobject not being named correctly. I recommend starting a new project and using the "Add to Scene and Configure" button to automatically configure your scene for MRTK.
