### ISSUE TITLE
MRTK GridObjectCollection Vertical scroll limit

### ISSUE THREAD

**Issue by melixor** [microsoft/MixedRealityToolkit-Unity#10333]
## Describe the bug

i'm building a ScrollingObjectCollection by code. I'm having a problem consisting in a limit of vertical scroll dimension. In few words i'm not able to scroll to the end of items. Have anyone meet this problems and solved it? Thank in advance

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.4.24f1]
- MRTK Version [e.g. v2.7.2]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by MaxWang-MS** [comment]
Hi @melixor, could you share a video or a repro project with us so that we can take a look?

**Comment by xandrew94x** [comment]
Hi,
I have a similar error.
Same Unity and MRTK version.

I noticed that when I put the objects in the container before playing scene the scroll object works well. 

If instead I insert the objects in runtime, the container shows only the first objects and by activating the scroll they are not scrolled even though the objects are present. I mean, the scroll is activated, but trying to scroll, the animation always returns me to the first objects.

The setup are:

![scrollobject](https://user-images.githubusercontent.com/28739225/143415494-1e3370a7-f790-4b72-adc4-1879be8a3f56.PNG)

![gridobjectcollection](https://user-images.githubusercontent.com/28739225/143415775-87b05cb8-22df-4fbd-a653-b46a239089d1.PNG)

**Comment by MaxWang-MS** [comment]
The issue posted by @xandrew94x is addressed in a separate issue #10350. Closing this issue as we have not been hearing back from @melixor. Please reopen the issue and provide us with more information if this continues to be an issue, thanks.
