### ISSUE TITLE
BoundsControl missing documentation of some properties

### ISSUE THREAD

**Issue by julesra** [microsoft/MixedRealityToolkit-Unity#10346]
## Describe the issue
The page for BoundsControl doesn't describe some of the properties (ex: BoundsCorners, Active). Please explain what these are.

## Feature area
Missing documentation

## Existing doc link
https://docs.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.toolkit.ui.boundscontrol.boundscontrol?view=mixed-reality-toolkit-unity-2020-dotnet-2.7.0

## Additional context
PS: I used to be able to submit these documentation issues right in the doc page, but now I can't seem to find any buttons to submit feedback. Where are these / do these only appear for some pages ?

**Comment by MaxWang-MS** [comment]
Hi @julesra, thanks for letting us know about the issue. The API reference doc you linked was automatically generated from the source code by tools so there is no feedback button there. Here (this repo) is the best place for you to report issues regarding the API reference docs.
@Zee2 Could you take a look and add the missing comments when available?

**Comment by Zee2** [comment]
Hi @julesra, thanks for reporting this. This is resolved as part of our 2.7.3 release. Thank you!

**Comment by Zee2** [comment]
Fixed with #10361.
