### ISSUE TITLE
Not able to debug in VS - Microsoft.MixedReality.QR.pdb could not be found in the selected paths

### ISSUE THREAD

**Issue by whatever881** [microsoft/MixedRealityToolkit-Unity#10344]
## Describe the bug

Symbol loading for Microsoft.MixedReality.QR.dll was skipped because it is not specified in the included modules list

## To reproduce

1. Install  Microsoft.MixedReality.QR (NuGet) & MRTK
2. Try to debug

## Expected behavior

We should be able to debug app with Microsoft.MixedReality.QR.dll 

## Screenshots

![Capture](https://user-images.githubusercontent.com/95287242/144044768-f8f61abf-e361-4d07-8de9-bf4f21118eaf.PNG)

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.3.3f1]
- MRTK Version [e.g. v2.7]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by polar-kev** [comment]
Hey @whatever881, MRTK does not ship the QR library. It looks like the owner of the library either,

1. did not include the pdb file in the nuget package, or
2. did not publish it to the symbol server

I'll forward this to the QR library owner.

**Comment by polar-kev** [comment]
Hey @whatever881, this request has been routed. I'll update this issue when share how they intend to proceed.

**Comment by majaeger** [comment]
Hi @whatever881 , I am working on adding symbols to the next release. In the meantime, you should still be able to debug your app by excluding the dll in the Visual Studio options

![image](https://user-images.githubusercontent.com/24962807/146072931-1a261096-3c2a-4c53-b151-302312b9ff7c.png)

https://devblogs.microsoft.com/devops/understanding-symbol-files-and-visual-studios-symbol-settings/#configuring-visual-studios-settings
