### ISSUE TITLE
World Locking causing inaccurate Spatial Observations extents

### ISSUE THREAD

**Issue by peterneil-bimholoview** [microsoft/MixedRealityToolkit-Unity#10343]
With a brand new installation of our App the spatial observer will display correctly with the extents as expected (Point A). However, I shut down the application and move a few meters (Point B) and start up the application again no spatial observer is visible. I walk toward Point A and look back toward Point B and the Spatial Observer is visible at Point B.  I walk toward Point B and the spatial observer progressively disappears.

Disabling the World Locking causing the spatial observer to work as expected. 

In Open XR I get the same issue if the Observer Shape is Axis Aligned Cube but User Aligned Cube works as expected.  However, in WMR Plugin 4.6.1 both User Aligned Cube and Axis Aligned Cube experience this issue.  

Unity: 2020.3.13f
MTRK: 2.7.2
WMR Plugin: 4.6.1
WLT: 1.4.2

PointA:
![PointA](https://user-images.githubusercontent.com/58964321/143804329-e6a49b64-cb2f-4236-a84a-b84e6f5fb312.jpg)

Point B:
![PointB](https://user-images.githubusercontent.com/58964321/143804340-c91f2112-181f-4299-bd3e-d924f3ba2bba.jpg)

Looking back at Point B:
![Looking Back at Point B](https://user-images.githubusercontent.com/58964321/143804344-7e54ba4e-0578-45b1-a37a-1c8ace89330b.jpg)

**Comment by peterneil-bimholoview** [comment]
Also, turning off WLT Auto-Load also stops this issue

**Comment by fast-slow-still** [comment]
In the past, this issue has come from MRTK failing to transform the spatial mesh data from the coordinate space in which they are reported (e.g. by WinMR Plugin) into Unity's global coordinate space. 

In general, low level systems like the WinMR Plugin or OpenXR Plugin are unaware of any transform that might be applied to the camera, for example the teleport transform in the MRTK Playspace. So that transform needs to be applied at the SpatialMeshObserver level (or thereabouts) to place them properly in Unity's global space.

WLT corrects the camera's position by applying a transform to the MRTK Playspace, so a breakage in applying the Playspace transform will become apparent when using WLT.

**Comment by fast-slow-still** [comment]
@peterneil-bimholoview , are you using MRTK v2.7.2 from a release package (either .unitypackage or from MRFeatureTool), or is it the latest from the MRTK github main branch? Thanks!

**Comment by peterneil-bimholoview** [comment]
Hi @fast-slow-still we got the MRTK and WLT from the MRFeatureTool.  

Some more background, all with the same MRTK, WLT and Unity versions 

WMR Plugin: 4.5.0
Axis Aligned Cube = Observer Extents Correct
User Aligned Cube = Observer Extents Incorrect

OpenXR Plugin:
Axis Aligned Cube = Observer Extents Incorrect
User Aligned Cube = Observer Extents Correct

WMR Plugin: 4.6.1
Axis Aligned Cube = Observer Extents Incorrect
User Aligned Cube = Observer Extents Incorrect

**Comment by fast-slow-still** [comment]
@peterneil-bimholoview Hi Peter, I'm going to try to have a look at this this weekend. I was hoping you could clarify something for me. Which of the following statements would you say best describes the issue you are seeing?

1. The spatial mesh appears offset from the physical geometry that it is supposed to represent.
2. The spatial mesh is aligned with the physical geometry, but the area being meshed is offset from where it should be.

Thanks!

**Comment by peterneil-bimholoview** [comment]
Hi @fast-slow-still No.2 is the problem we are seeing.  If you have trouble reproducing the issue I have side-loadable version of our App which shows the issue.

**Comment by fast-slow-still** [comment]
If you look in the old XR2018/WindowsMixedRealitySpatialMeshObserver.cs, in function ConfigureObserverVolume(), you'll see the correct implementation for the volume:

```csharp
                // The observer's origin is in world space, we need it in the camera's parent's space
                // to set the volume. The MixedRealityPlayspace provides that space that the camera/head moves around in.
                Vector3 observerOriginPlayspace = MixedRealityPlayspace.InverseTransformPoint(ObserverOrigin);
                Quaternion observerRotationPlayspace = Quaternion.Inverse(MixedRealityPlayspace.Rotation) * ObserverRotation;
```
The adjusted observerOriginPlayspace and observerRotationPlayspace are then passed to the observer to set the current bounds.

However, this logic is missing in later implementations. For example, in XRSDK/WindowsMixedRealitySpatialMeshObserver.cs, the inspector values of ObserverOrigin and ObserverRotation, which are in Unity's global space, are passed directly to the observer, which expects them to be relative to the camera parent (the MRTK Playspace).

ObserverOrigin seems to be set in GenericXRSDKSpatialMeshObserver.cs in UpdateObserver:

```csharp
                        if (!IsStationaryObserver)
                        {
                            ObserverOrigin = CameraCache.Main.transform.position;
                        }
```
Note that that is grabbing the camera's global position. But then it is passed directly to the meshsubsystem in GenericXRSDKSpatialMeshObserver.ConfigureObserverVolume() and the XRSDK/MixedRealitySpatialMeshObserver.ConfigureObserverVolume() override.
```csharp
                switch (ObserverVolumeType)
                {
                    case VolumeType.AxisAlignedCube:
                        meshSubsystem.SetBoundingVolume(ObserverOrigin, ObservationExtents);
                        break;
```
So those two ConfigureObserverVolume functions need to be updated to follow the pattern in XRSDK2018/MixedRealitySpatialMeshObserver.cs above.

@MaxWang-MS @keveleigh @davidkline-ms @paco-ms

**Comment by davidkline-ms** [comment]
@fast-slow-still, @peterneil-bimholoview

sorry this wound up falling under the radar and missing 2.7.3. I will look into this and work with the team to get it packaged as soon as possible
