### ISSUE TITLE
MRTK-Quest prefab instance problems with Unity 2020.3.24

### ISSUE THREAD

**Issue by Holo-Krzysztof** [microsoft/MixedRealityToolkit-Unity#10351]
## Describe the bug
After importing MRTK 2.7.2 into Unity 2020.3.24 and trying to open one of the MRTK-Quest prefabs I get these error messages:
```
Prefab instance problem: MRTK-Quest_OVRCameraRig (Missing Prefab with guid: 126d619cf4daa52469682f85c1378b4a)
Prefab instance problem: MRTK-Quest_HandsPrefab (Missing Prefab with guid: 835e735ca71bf78459fb2cababd74112)
Prefab instance problem: MRTK-Quest_LocalAvatar (Missing Prefab with guid: 84c8b8609f9bb434eaf5248f17ff1293)
```

## To reproduce

1. Import MRTK 2.7.2 into a Unity 2020.3.24 project
2. Open one of the MRTK-Quest prefabs
3. Observe errors about missing components

## Expected behavior

I'd expect all the prefab components to exist.

## Your setup (please complete the following information)

- Unity Version 2020.3.24
- MRTK Version 2.7.2

## Target platform (please complete the following information)

- Unity Editor

**Comment by keveleigh** [comment]
I believe this is expected if Oculus' Unity integration package isn't installed, but @RogPodge would know best!

**Comment by RogPodge** [comment]
Yeah, those MRTK prefabs utilize prefabs that are located in the Oculus Integration package. Be sure to follow [these steps](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/supported-devices/oculus-quest-mrtk?view=mrtkunity-2021-05) to configure MRTK to deploy to the oculus quest

**Comment by RogPodge** [comment]
Let us know if those steps are out of date or if you are still encountering issues afterwards!

**Comment by Holo-Krzysztof** [comment]
Oh, alright. We don't deploy to Quest right now so I guess that's why I never noticed this before.

Wouldn't it be better if those prefabs lived in the Oculus integration package then? It'd prevent some confusion for sure, because once I got these error messages right after importing MRTK into a blank project. Doesn't happen always though.

**Comment by RogPodge** [comment]
We're not directly plugged into the decision making on Oculus Quest's side of things, and because those prefabs take a dependency on MRTK packages I don't think it's quite feasible.
