### ISSUE TITLE
hand not rotating when using XR plug-in management

### ISSUE THREAD

**Issue by frere97** [microsoft/MixedRealityToolkit-Unity#10352]
the virtual object used to represent the hand will follow your hand but will not rotate until you lose the focus of the window.

https://user-images.githubusercontent.com/35118366/144668157-6924d363-4e4f-4eaf-984b-244c458c3ff5.mp4

obs: for a temporary solution i'm minimizing and maximizing the game by code.
obs 2: i'm using the XR plug-in management, this is the open XR configuration Tab

![image](https://user-images.githubusercontent.com/35118366/144668394-a4c5c40e-dae5-4501-be08-4d1a04d6ef68.png)
![image](https://user-images.githubusercontent.com/35118366/144668407-6fc2949a-564f-4fc4-9cb2-477f58c61441.png)

**Comment by keveleigh** [comment]
Which script are you using to have the cube follow the hand? Is it the action-based TrackedPoseDriver?

**Comment by frere97** [comment]
it's the action based xr controller

![image](https://user-images.githubusercontent.com/35118366/145030952-82c3870d-a793-4969-9ead-2c9a2e53ad1a.png)

**Comment by keveleigh** [comment]
> it's the action based xr controller

Ah, okay! This is a known bug when using MR OpenXR's Hand Tracking feature. Unity's input system gets a little confused and tries to access the rotation from an input device that isn't providing rotation, so it just uses an identity quaternion.

If you aren't actively using articulated hand joints, you can turn this feature off. If you _are_ using articulated hand joints, unfortunately I'm not aware of a workaround at this time.

![image](https://user-images.githubusercontent.com/3580640/145090586-d42c7ad1-08f4-432c-bd5f-92096bb9dea2.png)

**Comment by frere97** [comment]
probably i will use, because the app will work with vr headsets too, so probably is better i've still minimize and maximize the window when i start the holoremote

**Comment by keveleigh** [comment]
@frere97 I believe we've identified a way to fix this via an MR OpenXR Plugin package change. I have a PR open for it now internally, and I'll work to get it in our next release!

**Comment by frere97** [comment]
thanks man, if there is anything i can make to help let me know

**Comment by keveleigh** [comment]
This has been released in the 1.3.0 release of the Mixed Reality OpenXR Plugin package!
