### ISSUE TITLE
uGUI related does not work well with Unity 2017.2

### ISSUE THREAD

**Issue by kameware** [Microsoft/MixedRealityToolkit-Unity#1037]
"KeyboardTest.unity" This does not work on Unity 2017.2, will it work?
uGUI related does not work well with Unity 2017.2

**Comment by StephenHodgson** [comment]
It was broken before 2017.2.

**Comment by kameware** [comment]
Are you planning to fix the relationship between uGUI and IInputHandler(IInputClickHandler)?

**Comment by StephenHodgson** [comment]
Yes.

**Comment by StephenHodgson** [comment]
For the dev branch you need to register the canvases for ugui support.

**Comment by kameware** [comment]
So, how can i use InputField? or do you have any other plan or way to use?

**Comment by StephenHodgson** [comment]
I couldn't tell ya atm. I haven't had a chance to test that yet.

**Comment by kameware** [comment]
Now we will use "RegisterPointableCanvas.cs" to watch the trend. Thank you.
