### ISSUE TITLE
left hand attached to my little finger

### ISSUE THREAD

**Issue by frere97** [microsoft/MixedRealityToolkit-Unity#10380]
So, my right hand is following normally my hand, but the left hand is following my little finger as we can see in the video, this make it really hard to interact with thigs such as UI, i am using the  XR plug-in management with the mrtk, and using the version 2020.3.20f1 of unity. 

https://user-images.githubusercontent.com/35118366/146414245-39505485-74d9-4251-bfc2-7ea03d16c09a.mp4

and this is my input system window
![image](https://user-images.githubusercontent.com/35118366/146414795-872f4ad3-94ad-4925-a663-b4ac17a0372f.png)

**Comment by frere97** [comment]
forget it, i've just fixed it, change the rotation/handbonedata to pointer/rotation

**Comment by keveleigh** [comment]
Glad to hear you were able to resolve it!
