### ISSUE TITLE
Teleport raycast hits "Ignore Raycast" layer.

### ISSUE THREAD

**Issue by reeseras** [microsoft/MixedRealityToolkit-Unity#10387]
When using the teleport gesture, the teleport raycast interacts with all colliders including those on the "Ignore Raycast" layer. The pointer for grabbing works fine, just not the teleport. 

I checked "MixedRealityToolkit" settings but there's nothing under teleport:
![image](https://user-images.githubusercontent.com/26148056/146617652-285aa4a3-60c6-4de5-aec4-147f04e6a2e6.png)

Anywhere else I should check to fix this?

## Unity editor version
2020.3.19f1

## Mixed Reality Toolkit release version
2.7.2

**Comment by RogPodge** [comment]
The teleport layer settings should be on the teleport pointer itself. 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.toolkit.teleport.teleportpointer.validlayers?view=mixed-reality-toolkit-unity-2020-dotnet-2.7.0

**Comment by reeseras** [comment]
Perfect! Found it in the inspector for MixedRealityToolkit under "input". I had to copy the prefab to make it editable then replace it in the input settings mentioned above. Thanks so much!

**Comment by reeseras** [comment]
Maybe I'm misunderstanding, but "ignore raycast" is in invalid layers as well as another layer I added. The only layer in "valid layers" is "default". I triple checked and the object I'm trying to pass through is on the "ignore raycast" layer, and the teleporter still doesn't cast through it. Do I need to change something in the prefab besides valid and invalid layers?

**Comment by RogPodge** [comment]
I think I also misunderstood. To get the actual ray to pass through other objects is a separate topic and I _think_ you'd have to change the raycast provider itself in order to get it to pass through objects. I don't think we expose that ability through code unforuntately....

Tagging @keveleigh for if he knows where this might be exposed, I didn't see anything when looking through our codebase.

**Comment by reeseras** [comment]
I know I've done this before via the pointer raycast layer masks inside the pointers settings. But this doesn't seem to work anymore: 
![image](https://user-images.githubusercontent.com/26148056/148302379-734386b1-7dba-40a1-8410-563152604929.png)

**Comment by RogPodge** [comment]
Apologies for the late response on this. Will timebox looking into a fix for this during this week, though for v3 it'll definitely be addressed due to our input system changes.
