### ISSUE TITLE
oculus quest hand tracking fails with link cable in editor

### ISSUE THREAD

**Issue by graemeaj** [microsoft/MixedRealityToolkit-Unity#10397]
## Describe the bug

When using a link cable to connect to a quest 1 HMD for use in the editor, no pose info is sent to the hand prefab and an error appears. the hand location and rotation is accurate, but pinching and button pressing is impossible. **Note** that in an android build with the same settings, the hand poses work fine. This only affects the editor with the link cable it seems

## To reproduce

1.  open HandInteractionexamples scene
2. plug in oculus quest 1 to PC with no controllers
3. MRTK will spin up the MRTK-Quest_OVRCameraRig
4. hands will be backwards, the hand location is tracked but the hand poses don't change, input to buttons is hard and pinching is gone

## Expected behavior

The hand poses should work in android and link cable/editor mode identically (track the hand and match the poses)

## Screenshots

![2021-12-23 11_28_57-Window](https://user-images.githubusercontent.com/9042770/147279479-331f1747-f785-4bdc-ac96-e141b460109a.png)

this screenshot is of my hand pointing up, notice no pose

error dump:

KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Microsoft.MixedReality.Toolkit.XRSDK.Oculus.Input.OculusHand.UpdateController (OVRHand hand, OVRSkeleton ovrSkeleton, UnityEngine.Transform trackingOrigin) (at Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Scripts/Input/Controllers/OculusHand.cs:136)
Microsoft.MixedReality.Toolkit.XRSDK.Oculus.Input.OculusXRSDKDeviceManager.UpdateHand (OVRHand ovrHand, OVRSkeleton ovrSkeleton, Microsoft.MixedReality.Toolkit.Utilities.Handedness handedness) (at Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs:310)
Microsoft.MixedReality.Toolkit.XRSDK.Oculus.Input.OculusXRSDKDeviceManager.UpdateHands () (at Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs:301)
Microsoft.MixedReality.Toolkit.XRSDK.Oculus.Input.OculusXRSDKDeviceManager.Update () (at Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs:210)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem.Update () (at Assets/MRTK/Core/Services/BaseDataProviderAccessCoreSystem.cs:51)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit+<>c.<UpdateAllServices>b__72_0 (Microsoft.MixedReality.Toolkit.IMixedRealityService service) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:1054)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit.ExecuteOnAllServicesInOrder (System.Action`1[T] execute) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:1145)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit.UpdateAllServices () (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:1054)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit.Update () (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:727)

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.4.23f1]
- MRTK Version [e.g. v2.7.2]
- Oculus XR plugin version 1.8.1 (also tried an older version from late last year with same issue)

## Target platform (please complete the following information)

- Oculus XR - Oculus quest 1 & Link cable in Unity editor

## additional info

I have tried different cables, updating all my packages and the unity XR manager plugin, changing the "palm prefab" in the MRTK articulated hand settings to null

**Comment by RogPodge** [comment]
We don't have any official support for Oculus Link in MRTK as of now. We'd really appreciate any community contributions to greenlight this development path! Ideally with OpenXR as the industry moves towards unifying behind that backend.

**Comment by Zee2** [comment]
MRTK3 has full Quest Link support, with hand tracking :)
