### ISSUE TITLE
How do I use German, French, Spanish Text to Speech, the voice is always the English voice

### ISSUE THREAD

**Issue by whatever881** [microsoft/MixedRealityToolkit-Unity#10395]
## Describe the issue
How do I use German, French, Spanish Text to Speech, the voice is always the English voice

## Feature area
How do I use German, French, Spanish Text to Speech, the voice is always the English voice

## Existing doc link
How do I use German, French, Spanish Text to Speech, the voice is always the English voice

## Additional context
How do I use German, French, Spanish Text to Speech, the voice is always the English voice

**Comment by keveleigh** [comment]
By default, the TTS script uses whatever your system default voice is set to. You'll want to follow the steps at https://support.microsoft.com/en-us/topic/how-to-download-text-to-speech-languages-for-windows-10-d5a6b612-b3ae-423f-afa5-4f6caf1ec5d3 to download additional voices.
Double checking my device though, I don't seem to see the page to update the default, and we currently only have the English voices in our TTS enum to choose from. This will likely need a fix in MRTK to expand the enum or allow from custom voices via a string entry or something.

**Comment by whatever881** [comment]
Thanks for the info.
I can't execute step 4 - "Under Language options > Speech, select Download." on my Hololens 2. I think changing the speech on Hololens is not yet supported by the OS, am I right?

**Comment by Rive4** [comment]
Hello, I am followed the steps to change the language and I also removed the English package (just in case) and I still listen the voice in English so that solution did not work for me.
Is there any known update related to the language change?
