### ISSUE TITLE
ConstantViewSize solver changes the scale of the object to a ratio of (1:1:1) on three axes

### ISSUE THREAD

**Issue by KritiaSthovania** [microsoft/MixedRealityToolkit-Unity#10396]
## Describe the bug

The _ConstantViewSize_ solver automatically changes the scale of the object to a ratio of (1:1:1) on three axes, as it directly computes the _GoalScale_ using _Vector3.one*scale_. However, there can be problems if the original scale of the object/prefab is not (1,1,1).

## To reproduce

1. Choose an object in the scene.
2. Change its scale to (1,2,1) in the inspector.
3. Add the _ConstantViewSize_ solver and _SolverHandler._
4. Start the scene. 
5. Seeing that the scale is modified to a ratio of (1:1:1).

## Expected behavior

The _ConstantViewSize_ solver can modify the scale of an object keeping its original ratio on three axes unchanged.

## Your setup

- Unity Version 2020.3.24f1
- MRTK Version 2.7.3

## Target platform

- HoloLens
- HoloLens 2

**Comment by RogPodge** [comment]
I think this was an unfortunate side effect of how this solver was designed (the assumption that the prefab had a starting scale of 1,1,1).

We're a bit busy at the moment with our v3 work but we'll see if we can make the starting scale configurable for the v3 version of the solver.
