### ISSUE TITLE
gltf node id and gameObject pairs

### ISSUE THREAD

**Issue by idea-lei** [microsoft/MixedRealityToolkit-Unity#10399]
## Describe the problem

till now we only have the whole `GameObjectReference` in `GltfObject`, and it's tidious to write own mapping logic to get corresponding GameObject of specific node, because we only have node name under `GltfNode` (without NodeId of course), meanwhile, some names could be the same. Comparing tranform could be a solution but definitly not elegant...

## Describe the solution you'd like

add Node-GameObject-Pairs Dictionary in `GltfObject` and add the pair during constructing a node (in Method `ConstructNodeAsync`).

## Describe alternatives you've considered

create a method after construction to pair node id and corresponding GameObject. But as mentioned above, this would be relatively complex.

**Comment by keveleigh** [comment]
@idea-lei Do you think there's any benefit to having the dictionary indices be the string names instead of the int ids? I guess all nodes are guaranteed an id while only some may have a name, but the names are a little more human-parseable.
