### ISSUE TITLE
baselib link error when building from MRTK build 

### ISSUE THREAD

**Issue by XPav** [microsoft/MixedRealityToolkit-Unity#10403]
## Describe the bug

When building via MRTK, the build fails due to:

`(Filename: Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@53ebe713ab19-1641334424296/Core/Extensions/ProcessExtensions.cs Line: 104)

         EXEC : error : Unity.IL2CPP.Building.BuilderFailedException: The Baselib library 'C:\Program Files\Unity\Hub\Editor\2021.2.7f1\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\il2cpp\Release\baselib.dll' does not exist and is required for this build. [C:\dev\blah\foo\app\Builds\WSAPlayer\Il2CppOutputProject\Il2CppOutputProject.vcxproj]
`
This is failing because the line to baselib is missing the architecture.

## To reproduce

Make a blank project, follow tools to configure for MRTK.  Go to Build Window, hit Build, wait, watch failure.

## Expected behavior

A successful build

## Your setup (please complete the following information)

- Unity Versions 2021.2.7f1 and 2020.3.23f1 both exhibit the problem
- MRTK Version 2.7.3.0

## Target platform (please complete the following information)

Targeting HL2, don't get that far.

## Additional context

The offending vcxproj contains the following baselib directory define --`"$(UnityWSAPlayerDir)Players\UAP\il2cpp\$(PlatformTarget)\$(UnityPlayerConfiguration)`, which, when building from MRTK, does not have PlatformTarget defined.  Building the solution in VS is fine.

**Comment by MaxWang-MS** [comment]
Thanks for posting the issue! It seems that this is the same issue as [one on Unity Forum](https://forum.unity.com/threads/unity-il2cpp-building-builderfailedexception-baselib-dll-does-not-exist.1182046/). We will investigate.

**Comment by MaxWang-MS** [comment]
Hi @XPav and @des1gnerw1tch, I was not able to reproduce the issue with MRTK 2.8.2 and Unity 2020.3.36/2021.3.5. Please let me know if you are still having this issue with the latest Unity and MRTK versions.
