### ISSUE TITLE
Stuck between master and RC Beta branch

### ISSUE THREAD

**Issue by Andre-Rb** [Microsoft/MixedRealityToolkit-Unity#1040]
Hi, 

I'm completely clueless on how to find a way to get to work with the MRTK and Hololens.
I finally got to work my dev env ( meaning VS17 or Unity + MRTK managin both to deploy and build the app).  
BUT ! When I use the master branch with Unity 2017.1.1.f1 I'm stuck with
 ```Error! RenderTexture.GenerateMips failed: render texture does not have mip maps (set useMipMap to true).```
 that's freaking annoying because it floods my console a lot and could even lower performances.

On the other hand, with Unity 2017.2.0f1 (RC) and beta branch, I'm being told my target device ( Hololens isn't up to date) ` DEP3321: To deploy this application, your deployment target should be running Windows Universal Runtime version 10.0.16288.0 or higher. You currently are running version 10.0.14393.1715. Please update your OS, or change your deployment target to a device with the appropriate version.	GTS_Demo`
I'm already running Insider on it and it's up to date :(
(Latest SDK and insider update installed on the dev computer)

And finally, master branch MRTK with a beta Unity doesn't work, as I understand API changed a lot.

I know this is not bug related but I'm starting to loose hope on finding a stable dev environment...  Plus Unity forums and  Microsoft Hololens forums never have shown very helpful

Thanks a lot in advance !

**Comment by jessemcculloch** [comment]
Hey Andre,

The generate mipmaps error is benign, you can ignore it, although like you mentioned, it fills the logs and is annoying.

The issue you are running into with 2017.2 is a pretty easy fix.  On the unity build settings window, you probably have the build target set to "latest installed" where as HoloLens is at version 15063. If you set that to match, it should solve that problem.

**Comment by Andre-Rb** [comment]
Holy cow, it's finally working ! thanks a lot @jessemcculloch ! 
I'm a bit confused, isn't the latest SDK (16 something) needed to run the beta MRTK ?

**Comment by jessemcculloch** [comment]
Yes and no. It needs to be installed for some of the API's for the Immersive Headsets and Motion Controllers to compile. But the OS on the HoloLens itself is only at 15063.

**Comment by Andre-Rb** [comment]
Noted !
But as I expected something else doesn't work.
I'm attempting to build&run the SpatialUnderstanding scene. But it crashed my Unity or throws an exception in VS or crashes on Hololens. Is it an known issue ? I can't get to work any spatial visualization since this morning ^^"

**Comment by jessemcculloch** [comment]
Did you grab the pre-release of Dev_Unity_2017.2 from the releases page, or did you just download the raw code from the branch this morning?

**Comment by Andre-Rb** [comment]
My bad, forgot to answer.
Yup I did :)
And there is more I never managed to get to work SpatialMapping from MRTK, even in the 'old' version.
I check `drawVisualMeshes` but never show a thing ( So I used the Unity vanilla component )
