### ISSUE TITLE
Near Interaction Press is working in Unity Game view, but not physical Hololens when deployed.

### ISSUE THREAD

**Issue by pratyush-p** [microsoft/MixedRealityToolkit-Unity#10401]
## Describe the bug

I am not able to use any buttons via near interaction on my Hololens 2. I have to use far-interaction hand rays instead. In my Unity Game view, however, everything is working exactly as it should. Also, for some reason, near interaction grabbables work on my hololens too, just not pressables like buttons.

## To reproduce

1. Create Unity Project w/ MTRK with DefaultHololens2ConfigurationProfile
2. Create a Hololens2 Button from Prefab
3. Create a basic cube with Box Collider, Object Manipulator, and Near Interaction Grabbable
4. Go into Unity game mode, and press button (Listening for default sound effects) and grab cube.
5. Deploy to Hololens, and do same actions as Step 4.

## Expected behavior

I expect to hear sound effects for near interaction pressing when on my hololens.

## Your setup (please complete the following information)

- Unity Version [2020.3.25f1 Personal]
- MRTK Version [v2.7.3]

## Target platform (please complete the following information)

- Hololens 2

## Additional context

I came across this problem when I was going through the Hololens 2 Fundamentals Tutorial, and I tried deploying the Mars Rover project to my Hololens 2. I am new to Hololens and Holograms in general, so all feedback is welcome.

**Comment by RogPodge** [comment]
We haven't been able to reproduce this issue on v2, nor on the new v3 architecture. Closing for now unless we see more occurrences of this happening/have some video/logs to look at.
