### ISSUE TITLE
Oculus Quest 2: Cannot toggle profiler (dictation not working?)

### ISSUE THREAD

**Issue by trzy** [microsoft/MixedRealityToolkit-Unity#10411]
## Describe the bug

I am unable to toggle the profiler that is enabled by default on Oculus Quest 2 both in Link mode and when running an APK deployed to the device. I am using more or less the default settings profiles (I modified the camera profile to not render a skybox so that I could enable passthrough mode in my app). 

Is dictation supposed to "just work" or is there some additional configuration needed?

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.3.25f1]
- MRTK Version [e.g. v2.7.3.1]

## Target platform (please complete the following information)

- Oculus Quest 2

**Comment by polar-kev** [comment]
Hi @trzy, thanks for filing. There currently isn't a plan to support keyword recognition on Quest in MRTK v2 which is required to toggle the profiler via speech. We are, however, planning to support this in MRTK v3.
