### ISSUE TITLE
How to implement a custom Progress Indicator after the splash screen before loading a scene 

### ISSUE THREAD

**Issue by SWARAVL** [microsoft/MixedRealityToolkit-Unity#10413]
## Overview
How to implement a custom Progress Indicator after the splash screen before loading a scene 

## Expected behavior
We want to customize the default progress indicator (basically, we don't want to see the rotating orbs and would like to replace it)
when the scene launches after the splash screen

## Actual behavior
Before the scene launches, for about 3 seconds, we see the default progress indicator(4 rotating orbs)

## Steps to reproduce
Create a Unity Project and set up MRTK
Add an object onto your scene
Build and deploy on Hololens 2
Once the app launch with splash screen, you should see the default progress indicator coming up before the actual scene loads.

## Unity editor version
2019.4.13f1

## Mixed Reality Toolkit release version
2.5.3
![Capture](https://user-images.githubusercontent.com/93895727/149106052-f8d99d4c-f25d-47b2-9828-51a0954d788c.PNG)

**Comment by polar-kev** [comment]
Hey @SWARAVL, the rotating orbs are controlled by the HoloLens platform, not by MRTK. Although MRTK ships a progress indicator, it cannot be used during the initial app loading sequence.

Are you using the scene transition service at all here?

**Comment by SWARAVL** [comment]
Hey @polar-kev, he rotating orbs are controlled by the HoloLens platform, not by MRTK. Although MRTK ships a progress indicator, it cannot be used during the initial app loading sequence - I see, thanks for the info. We shall check on the Hololens page for a solution if it exists.

Are you using the scene transition service at all here? - Yup, we tried this concept. Unfortunately, it did not work out for us.
