### ISSUE TITLE
Creating and Modifying Icon Sets Different Menu Location

### ISSUE THREAD

**Issue by A-Ivan** [microsoft/MixedRealityToolkit-Unity#10412]
## Describe the issue
In the [Buttons documentation page](Buttons), more specifically the section on [Creating and Modifying Icon Sets](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/button?view=mrtkunity-2021-05#creating-and-modifying-icon-sets), it is stated that "You can create a new button icon set with the asset menu: Create > Mixed Reality Toolkit > Icon Set".

I believe this menu option has changed to Create > **Mixed Reality** > Icon Set. I would also add a note that this should be done in the Project window in Unity, just to be clear.

This is what the **Mixed Reality Toolkit** menu options are (no Icon Set option):

![image](https://user-images.githubusercontent.com/17125077/149037502-7d0750ce-e805-4a04-9385-0a567c828706.png)

This is what the **Mixed Reality** menu options are (has Icon Set option):

![image](https://user-images.githubusercontent.com/17125077/149037602-e3f45ce4-cb28-4281-bd51-35bd66783ab7.png)

Unity version 2020.3.24f1
MRTK version 2.7.3

**Comment by polar-kev** [comment]
Hey @A-Ivan, thanks for raising this. I will forward it to our doc writing team so they can fix it.

**Comment by A-Ivan** [comment]
You're welcome @polar-kev

**Comment by polar-kev** [comment]
The fix has been merged and should be live shortly.
