### ISSUE TITLE
Teleport or move the cam w/o  the parabolic teleport pointer

### ISSUE THREAD

**Issue by istvanContXtual** [microsoft/MixedRealityToolkit-Unity#10427]
Hi,

Is there a way to teleport or move the camera without the parabolic teleport pointer?

I am trying to create a map or toolbelt based system, where i can just press a button in a ui panel and move the camera top a pre defined location in the world.

Tried CoreServices.TeleportSystem.RaiseTeleportRequest(pointer, teleportHotspot); but does not seem to be working.

Any help/suggestion is much appreciated!

Using MRTK 2.7.x and  Unity 2020.3.LTS

**Comment by RogPodge** [comment]
This code block might be what you're looking for.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/cb7b4c9349c58b731af015df94ac3e383771effa/Assets/MRTK/SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs#L278-L293

Essentially move the playspace and that should allow for the camera to move without having to raise teleports or other such things
