### ISSUE TITLE
MRTKFeatureTool doesn't start

### ISSUE THREAD

**Issue by jonas-weimar** [microsoft/MixedRealityToolkit-Unity#10420]
## Describe the bug

We want to develop an app for the hololens 2 platform with unity and face the problem, that the downloaded MRTKFeatureTool doesn't start up, not showing even the slightest sign of action besides a shortly appearing loading indicator. No errors thrown anywhere.

## To reproduce

1. Start a new Unity project
2. switch platform to universal
3. set hololens as build target (essentially just following the official instructions for a new hololens project)
4. Download MRTKFeatureTool to install Hololens Feature Group
5. Open Tool -> nothing happens

## Expected behavior

We'd expect the program to open. Or at least to get a precise description of why it doesn't.

## Screenshots

After clicking the app icon nothing happens...
<img width="1260" alt="Bildschirmfoto 2022-01-17 um 14 22 07" src="https://user-images.githubusercontent.com/38507420/149776651-b0698e47-6dce-4db2-8a2d-3c908a7bdce7.png">

The feature group is not clickable before using the MRTKFeatureTool i guess...
<img width="894" alt="Bildschirmfoto 2022-01-17 um 14 21 33" src="https://user-images.githubusercontent.com/38507420/149776683-664226a7-6c12-41a3-be7b-0727bcc36b7d.png">

## Your setup (please complete the following information)

- Unity Version 2020.3.22f1 Personal
- using Microsoft.MixedReality.Toolkit.Unity.Foundation.2.7.3.unitypackage
- NOTE: We're using Windows 11 (ARM) via Paralells on a M1 MacBook Pro

## Target platform (please complete the following information)

- HoloLens 2

# Thanks in advance

**Comment by keveleigh** [comment]
Any ideas, @davidkline-ms?

**Comment by jonas-weimar** [comment]
@keveleigh I sadly don't find this entry. But what I have found out today when scraping the eventlog is, the following:

####
Description: A .NET application failed.
Application: MixedRealityFeatureTool.exe
Path: C:\Users\jonasweimar\Desktop\MRTKFeatureTool\MixedRealityFeatureTool.exe
Message: Failed to load the dll from [C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.13\hostpolicy.dll], HRESULT: 0x800700C1
An error occurred while loading required library hostpolicy.dll from [C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.13]
###

I then had a look into the quoted folder - but the file was there.

**Comment by jonas-weimar** [comment]
# Update

After installing .NET (x64) and reconfiguring VS it all works now.

**Comment by steven-cerebralfix** [comment]
Yeah I have this issue too. I've totally uninstalled all things .NET and Visual Studio. Still doesn't load after fresh installs of both. It was working fine (for about 4 months) up until about a month ago and I've not got it to load since then.

I don't get any error logs. The process just stops without displaying any windows or error messages.

MixedRealityFeatureTool.log reads:
```
Mixed Reality Feature Tool 1.0.2203.0
[25/05/2022 2:11:35 pm] Refreshing the Primary catalog.
[25/05/2022 2:11:35 pm] Reading Primary feed
```

I've tested:
MixedRealityFeatureTool-1.0.2111.0-Preview
MixedRealityFeatureTool-1.0.2111.1-Preview
MixedRealityFeatureTool-1.0.2203.0-Preview
All of which have previously worked fine.

**Comment by steven-cerebralfix** [comment]
Continues to not load in MixedRealityFeatureTool-1.0.2206.0-Preview

**Comment by farhadpiri** [comment]
> # Update
> After installing .NET (x64) and reconfiguring VS it all works now.

reconfiguring VS? what do you mean by that?

**Comment by worixon** [comment]
Hi, I'm with the same problem here . Is there still anyone who fixed it ?

**Comment by SimonTkacc** [comment]
Hello, in my Case it would not start as well, so I tried installing all the .net Versions (5.0, 6.0 and the newest 8.0) and it did not work. I was in a VM in VMWare and from stock these VMs get not much CPU. By Increasing the VM CPU from 2 Cores to 8 Cores it worked. I gave it first just more RAM, but it looks like CPU is there more Important. I hope it helps someone :)

**Comment by david-c-kline** [comment]
I no longer have access to the Mixed Reality Feature Tool source code, sorry.
