### ISSUE TITLE
[Oculus] Allow only avatar hands to be visible (no controllers)

### ISSUE THREAD

**Issue by eusebiu** [microsoft/MixedRealityToolkit-Unity#10429]
## Describe the problem

In versions prior to MRTK 2.7.3 the avatar hands were visible without the controllers.

## Describe the solution you'd like

The Oculus Device Manager should allow what type controller to be visible: controllers only, avatar hands only, both.

## Describe alternatives you've considered

Unchecking Render Avatar hands with controllers in Oculus Device Manager hide the avatar hands.

MRTK v2.7.3

**Comment by RogPodge** [comment]
Thanks for raising this issue, we'll try to accomdate for it ASAP

**Comment by RogPodge** [comment]
Closing as Oculus itself has deprecated its old hand avatar system: https://developer.oculus.com/downloads/package/unity-integration/39.0#deprecation

We advise users to use OpenXR for Quest compatibility for Unity 2020 and beyond
