### ISSUE TITLE
Is there any documentation on how to view a UI/canvas in Hololens 2?

### ISSUE THREAD

**Issue by A-Ivan** [microsoft/MixedRealityToolkit-Unity#10423]
I want to use a UI/canvas that is constantly shown and fixed to the user's view, like a head-up display. I know this might not be the best way visualize information while wearing the Hololens and there are many drawbacks to using fixed displays, but for prototyping this is what I need for now.

Unity version 2020.3.24f1
MRTK version 2.7.3
Hololens 2 (build 20348.1442)

I tried the following things:

1. Create a canvas object with a text object as a child of it
2. Set the canvas as a child of the Main Camera, which is a child of the MixedRealityPlayspace object.
3. Convert the canvas to an MRTK Canvas (Canvas -> Inspector -> Canvas, there will be a button to convert)

Now comes the part I'm having difficulty with, which is choosing the render mode to use for the canvas.

**Canvas Render Mode World Space**

World Space render mode is the mode that the Hololens [buttons](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/button?view=mrtkunity-2021-05) use. This works (canvas text can be seen in the Hololens) only in the Unity Editor (i.e., using Holographic Remote). Building this to the Hololens will cause the canvas to not appear there, not sure why this does not appear when running natively on the Hololens but appears when using Holographic Remote with the Unity Editor.

**Canvas Render Mode Screen Space - Camera**

Using Screen Space - Camera render mode, this works (canvas text can be seen in the Hololens) in both the Unity Editor (i.e., using Holographic Remote) and when running natively on the Hololens. An extra step that is required is to set the Render Camera (Unity Editor -> Canvas -> Inspector -> Canvas -> Render Mode -> Render Camera) to be the Main Camera (MixedRealityPlayspace -> Main Camera). 

Though this works, the following error will appear:

World Space Canvas should have no camera set to work properly with Mixed Reality Toolkit. At runtime, they'll get their camera set automatically.
UnityEngine.Debug:LogError (object)
Microsoft.MixedReality.Toolkit.Input.Utilities.CanvasUtility:VerifyCanvasConfiguration () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@396ac65d719d-1639692003058/Services/InputSystem/Utilities/CanvasUtility.cs:61)
Microsoft.MixedReality.Toolkit.Input.Utilities.CanvasUtility:Start () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@396ac65d719d-1639692003058/Services/InputSystem/Utilities/CanvasUtility.cs:38)

The problem is that if you follow these instructions, not setting a render camera via the inspector window (leaving it as empty), the error goes away but the canvas cannot be seen anymore. This occurs because the render camera that is automatically chosen is the UIRaycastCamera (this a separate game object generated in the Hierarchy during runtime).

Is there any clear documentation on this?

What option should be used to be able to create a UI/canvas that is constantly visible to the user? Should I use Screen Space and manually set the render camera and just ignore the errors?

Thank you.

**Comment by RogPodge** [comment]
I think following [these steps ](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/button?view=mrtkunity-2021-05 )to make "Unity" canvas buttons, and then using [various solvers](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/solvers/solver?view=mrtkunity-2021-05) might be the way to go here. Having the user have to interact with various buttons with a display that tightly moves with the head may not be the easiest to use.

If you just want to render text, I believe you can do that without having to convert to an MRTK canvas. A normal canvas UI should work well enough if you just want some text to float in a particular part of the view.

**Comment by A-Ivan** [comment]
Thank you @RogPodge for the information. In my case I only need to display text, no button interactions. I'll look into using a normal canvas UI.

It would be great if there was some information on the documentation to better explain the difference (pros/cons and example use cases) between a "Unity" and a "MRTK" canvas. This would make it clear when developing which one to use and why,

**Comment by RogPodge** [comment]
We'll keep that in mind and take another pass at clarifying out existing docs

**Comment by A-Ivan** [comment]
Happy to hear that, thank you.

**Comment by fmatulic** [comment]
Let me re-use this issue to ask a related question about support for regular Unity UI canvas in screen space (camera and overlay). Currently it doesn't seem to be the case, which is unfortunate. Displaying text and UI elements in a fixed screen position like a HUD is a use case that is common enough that MRTK should be able to handle it directly and seamlessly. Using a world space canvas that has to be continuously reoriented and with a shader that renders UI elements on top of everything isn't ideal.

**Comment by Zee2** [comment]
We don't have any plans to support screenspace UI in XR devices, as this isn't supported by Unity themselves and has serious rendering/graphical implications.
