### ISSUE TITLE
Bug when trying to connect HoloLens together

### ISSUE THREAD

**Issue by dtb49** [Microsoft/MixedRealityToolkit-Unity#1042]
I'm not sure if that happens to anyone else but, when I start my application and I am trying to anchor or import an anchor, the process will get hung up and never finish. The problem does not go away with a simple restart of the application. It forces me to basically restart my  HoloLens almost every time I go to test it out.

For example, I've noticed it happens more often than not when during one iteration HoloLens1 is the host and HoloLens2 is the client. However, if I make changes and re-deploy except I make HoloLens2 host about 90% of the time I am forced to restart HoloLens2 and sometimes even HoloLens1.

**Comment by StephenHodgson** [comment]
On the sharing stage, cold you enable detailed logging, run it again, and share the output with us?
