### ISSUE TITLE
Hand Mesh Visualization not visible in Holographic Remoting for Editor Play Mode

### ISSUE THREAD

**Issue by mihaits** [microsoft/MixedRealityToolkit-Unity#10439]
## Describe the bug

When using the editor play mode, the hand mesh visualization is not visible if holographic remoting is used.

## To reproduce

Under MRTK profile go to:
Input > Articulated Hand Tracking >Hand Mesh Visualization Modes
Make sure Editor is checked

Connect a HL2 device using Holographic Remoting for Play Mode

## Workaround

Under MRTK profile go to:
Input > Controllers > Microsoft Articulated Hand Both Hands
check "Use platform models"

This makes the rig based mesh visible during remoting.

Having the true hand mesh reported by the device would be ideal since it's more accurate. Is this is a current limitation of remoting and/or MRTK architecture?

## Setup

- Unity 2021.1-2021.2
- MRTK 2.7.3
- Mixed Reality OpenXR Plugin 1.2.1
- OpenXR Plugin 1.3.1

## Target platform

- HoloLens 2

**Comment by keveleigh** [comment]
> Is this is a current limitation of remoting and/or MRTK architecture?

It's a limitation of remoting. You can view the unsupported/limited APIs at https://docs.microsoft.com/windows/mixed-reality/develop/native/holographic-remoting-troubleshooting#limitations, including the hand mesh APIs: 
![image](https://user-images.githubusercontent.com/3580640/151851445-36c7157c-41e8-431e-a921-cafda90473f1.png)
