### ISSUE TITLE
Integrate HoloLens hand tracking to my own DLL

### ISSUE THREAD

**Issue by chinmaychinara91** [microsoft/MixedRealityToolkit-Unity#10438]
Hi,

I wanted to integrate the holoLens2 hand tracking feature into my own DLL. My work involves doing the integration in C++. Is there a c++ version of the MRTK that I can use to create my own DLL?

Chinmay

**Comment by polar-kev** [comment]
Hey @chinmaychinara91, please see this overview on native development for HoloLens 2 https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/directx-development-overview?tabs=openxr
