### ISSUE TITLE
Conflict with MRTK and Azure Storage For Unity Package

### ISSUE THREAD

**Issue by ARGs-code** [microsoft/MixedRealityToolkit-Unity#10437]
## Describe the bug

Importing the AzureStorageForUnity.package into a Unity Project with Mixed Reality Toolkit creates Compiler errors. If you remove the dll that comes with the AzureStorageForUnity.package you get errors because it references strong named Newtonsoft.Json assembly references for 10.0.0.0 and Mixed Reality Toolkit Package forces 12.0.0.0.

## To reproduce

Make a Unity Project in Unity 2020.3.x
Import Mixed Reality Toolkit from Microsoft Using the MRTK Feature Discovery Tool
Notice you have no errors after completing setup

Import AzureStorageForUnity.package

Notice Compiler Errors from Newtonsoft.Json.dll conflicts.

"Assets\MRTK.Tutorials.AzureCloudServices\Scripts\Dtos\ImageElement.cs(7,10): error CS0433: The type 'JsonPropertyAttribute' exists in both 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' and 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'"

Can't remove the .dll that is included with the MRTK Package Manager because it's managed by unity's package system. If remove or modify the .dll that comes with the AzureStorageForUnity.package then you get the following compiler error.

"Assembly 'Assets/Azure Storage/Plugins/Microsoft.WindowsAzure.Storage.dll' will not be loaded due to errors:
Microsoft.WindowsAzure.Storage references strong named Newtonsoft.Json Assembly references: 10.0.0.0 Found in project: 12.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

Issue arose from following the tutorial at this location:
https://docs.microsoft.com/en-us/learn/modules/azure-cloud-services-tutorials/3-exercise-azure-cloud-services-for-hololens-2

## Expected behavior

Azure Storage for Unity Package works with same Newtonsoft Package as MRTK.
## Your setup (please complete the following information)

- See reproduction steps 

## Target platform (please complete the following information)
- HoloLens 2

## Additional context

If anyone from MRTK could find for me the MSFT product owner for Azure Storage for Unity Package I will log a bug there, but I could not find it so I am logging it here in the hopes that it can begin to be resolved.

**Comment by keveleigh** [comment]
> Mixed Reality Toolkit Package forces 12.0.0.0

Do you know where this dependency is coming from? Where's the DLL in the package structure? I'm not aware of MRTK 2.x having a Newtonsoft.Json dependency.

**Comment by ARGs-code** [comment]
Good point Keveleigh. You are correct, it appears that Newtonsoft Json is a default package included in Unity even in empty projects that I can not remove. My default unity template includes MRTK and nothing else, so I mistakenly thought this was part of MRTK. But it's not. It's part of any new unity project. It doesn't show up in the package manager so I can't remove it from there and it is a package so deleting it just means unity remakes it once I load the project back up, doesn't even show up in the package manifest.

So not an MRTK issue at all. But entirely an AzureStorageForUnity package bug. Sorry about that. Still if anyone could point me to where I can log a bug with the right team I would appreciate it. We would like to explore what the tutorial seems to offer, but can't due to this issue.
