### ISSUE TITLE
Controller Input mappings inconsistancy in Prefabs

### ISSUE THREAD

**Issue by DDReaper** [Microsoft/MixedRealityToolkit-Unity#1044]
While working on another project, I noticed an inconsistency in the Input names that are used in different components of the project.

MixedRealityCameraParent uses:

- CONTROLLER_LEFT_STICK_HORIZONTAL
- CONTROLLER_LEFT_STICK_VERTICAL
- CONTROLLER_RIGHT_STICK_HORIZONTAL
- CONTROLLER_RIGHT_STICK_VERTICAL

However the Input system prefab included with the Manager Prefab uses:

- ControllerLeftStickX
- ControllerLeftStickY

I did note some of the Examples / tests have been updated to use the Fist set but these have not been replicated to the Prefab

**Comment by StephenHodgson** [comment]
Thanks for reporting.  I've got plans to look this over as soon as we get the initial input updates completed.

**Comment by StephenHodgson** [comment]
@DDReaper can you post a screen shot of this?  

I can't seem to find the component you're talking about.

**Comment by DDReaper** [comment]
Ok, sorry.  So if you start a new scene and drag the MixedCameraRealityParent and Managers prefabs to the scene.  You'll see one set of mappings in the MCRP and one in the Gestures control.

Although to be honest, we need to go thorough all the prefabs and check.

One big issue with having so many different Input settings, is that you can't include them in an asset package. So the user either has to set them up manually or import the project Input assets file manually.

It might also be worth looking at integration with input assets like InControl (later)

**Comment by StephenHodgson** [comment]
I anyway have the opportunity to directly download from GitHub. Check out the project setup wizard.

**Comment by StephenHodgson** [comment]
Ahh found it.  Thanks!
