### ISSUE TITLE
DefaultCursor does not work with Motion Controller Teleportation

### ISSUE THREAD

**Issue by jessemcculloch** [Microsoft/MixedRealityToolkit-Unity#1045]
Teleportation does not work if you are using the default cursor prefab in your scene, works fine when using Cursor prefab

**Comment by StephenHodgson** [comment]
Hmm, I wonder what the difference is.

**Comment by DDReaper** [comment]
Hmm, that's odd. Granted I've only used cursor so far and haven't tried the others. Will investigate
