### ISSUE TITLE
MaterialInstance allocates memory each frame

### ISSUE THREAD

**Issue by matthewsanderssaab** [microsoft/MixedRealityToolkit-Unity#10453]
## Describe the bug

In the update loop MaterialInstance calls cachedRenderer.sharedMaterials which allocates memory to return the materials array.
When used in complex scene graphs under a component like a scrolling object collection, this can lead to large allocations on each frame (~5KB per 100 materials).

## To reproduce

Create a scene with 10 MRTK buttons inside a scrolling object collection.

Start the scene.

In the profiler observe that the MaterialInstance allocates every frame.

## Expected behavior

No or low allocations per frame

## Your setup (please complete the following information)

- Unity Version 2019.4.35f1
- MRTK Version v2.5 - Current

## Target platform (please complete the following information)

- HoloLens 2

## Additional context
Consider change to use GetSharedMaterials and a pre-allocated list.

**Comment by MaxWang-MS** [comment]
Hi @matthewsanderssaab, this issue is addressed by #9193. Noite you will need to manually enable the `CacheSharedMaterialsFromRenderer` flag on ClippingPrimitives/MaterialInstance.
