### ISSUE TITLE
Update Wiki documentation

### ISSUE THREAD

**Issue by HattMarris1** [Microsoft/MixedRealityToolkit-Unity#1046]
I was going to add some solutions to common build issues to the main readme, (mentioned here: #934), but I'm not sure if it would be better to have them in the wiki?

 I noticed it hasn't been updated since April, is this because you can't make pull requests to the wiki?

**Comment by StephenHodgson** [comment]
Yeah that needs to get updated. I think there's a plan to generate the documentation straight from the code base via the xml.

**Comment by StephenHodgson** [comment]
Updated Wiki
