### ISSUE TITLE
MRTK

### ISSUE THREAD

**Issue by GusLee** [microsoft/MixedRealityToolkit-Unity#10472]
## Your setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Kent1LG** [comment]
I am facing this same issue as well !

Here's my own feedbacks :
[Put feedbacks here]

**Comment by MaxWang-MS** [comment]
Hi @GusLee, please fill out the template so that we can help you with the issue you are facing.
