### ISSUE TITLE
Update Dev branch to 2017.2.0f2-MRTP

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1047]
A special release of the Unity Editor for Mixed Reality projects [has been announced](https://forum.unity.com/threads/custom-build-2017-2-rc-mrtp-windows-mixed-reality-technical-preview.498253/). 

[Download Link](http://beta.unity3d.com/download/b9a6355603bd/download.html)

Release Notes:
Improved CPU/GPU synchronization which can result in significant performance improvements for 

- CPU/GPU bound titles.

Bug Fixes:

- Fixed an issue which prevented Holographic Simulation or Remoting from working on Windows Fall Creators Update builds (case 952039)
- Fixed Asserts triggering when playing a Windows Mixed Reality application in the Editor if the Mixed Reality Portal was not running (case 950519)
- Fixed an issue that prevented Unity from updating its culling frustum if the Windows API failed to return culling data (case 927404)
- Guarded against a potential crash if Windows Mixed Reality APIs don't return a valid camera back buffer (case 948814)
- renderViewportScale fixes
- Changing renderViewportScale with anti-aliasing causes the app to freeze (case 916194)
- Viewport scaling changes scale around the bottom-left corner instead of the center when the setting is lower than 1 (case 916192)
- Tracking-space and tracking-loss fixes
- Can't set tracking-space type to Stationary (case 946305)
- Tracking-loss screen renders badly and it shouldn't at all on opaque headsets (case 942154)
- Tracking loss type is not falling back to stationary when setup has not been configured (case 945163)
- Windows MR reports incorrect grip-pose rotation (case 949198)
- You can now correct for controller jitter by updating their poses' information in OnPreRender (case 948954)
- Fix for crash when toggling XRSettings.enabled off and then on again (case 952997)
- Fix for incorrect velocity of controllers being reported relative to starting orientation instead of world origin (case 953023)

General lifetime and start-up fixes:

- Fixed an issue which prevented Holographic Simulation or Remoting from working on Windows Fall Creators Update builds (case 952039)
- Fixed Asserts triggering when playing a Windows Mixed Reality application in the Editor if the Mixed Reality Portal was not running (case 950519)
- Fixed an issue that prevented Unity from updating its culling frustum if the Windows API failed to return culling data (case 927404)
- Guarded against a potential crash if Windows Mixed Reality APIs don't return a valid camera back buffer (case 948814)
- Controllers now picked up and work in play-in-editor. Note: you may still encounter issues . Restarting the controller should fix this. (case 934611)

**Comment by keveleigh** [comment]
Closed via #1050
