### ISSUE TITLE
Oculus Quest 2: Touch Input not recognized

### ISSUE THREAD

**Issue by loibnerg** [microsoft/MixedRealityToolkit-Unity#10486]
## Describe the bug

I've placed a cube and want it to move by touching it with the index finger. This works fine inside the Unity Play Mode. So when I move my virtual index finger to the the cube the cube can be pushed away.

When deploying on Oculuse Quest 2 the touch input gets not recognized and the hand just wents through.

**Update:** The same issue can be tested with the HoloLens2 Button. In Play-Mode the button can be pressed with the index finger on the Oculus Quest 2 it doesn't work.

## To reproduce

1. Do the setup properly: https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/supported-devices/oculus-quest-mrtk?view=mrtkunity-2021-05
2. Place a cube and add NearInteractionTouchable
3. Add the following script to the cube:

```
public class CubeTouchHandler : MonoBehaviour, IMixedRealityTouchHandler
{
    public void OnTouchCompleted(HandTrackingInputEventData eventData)
    {
        
    }

    public void OnTouchStarted(HandTrackingInputEventData eventData)
    {       
        
    }

    public void OnTouchUpdated(HandTrackingInputEventData eventData)
    {
        Debug.Log(eventData.InputData);
        
        this.transform.position = 
            new Vector3(this.transform.position.x, 
                        this.transform.position.y, 
                        eventData.InputData.z + this.transform.localScale.z / 2.0F);
                
    }
}
```

5. In Play mode the hand can move the cube.
6. Deploying on Oculus Quest 2 does not move the cube

## Expected behavior

I've expected the cube to move on touch input also when deployed to the Oculus Quest 2.

## Your setup (please complete the following information)

- Unity Version [2019.4.34f1]
- MRTK Version [2.7.3]
- Oculus XR Plugin [1.11.2]
- 

## Target platform (please complete the following information)

- Oculus Quest 2

**Comment by loibnerg** [comment]
I did some research to understand what is missing. Here are my findings:

When I activate the hand tracking for the Oculus Quest 2 and I use the tracked hands all works fine and the Touch Event is recognized.

When I use the controllers - where I activated the display of controllers and hands - I see the hands but the Touch Event is not recognized.

So the correct question should be: How can I activate the Poke Pointer for the Oculus Quest 2 Controllers?

**Comment by loibnerg** [comment]
I now tried with the Oculus Rift S and it didn't work either. It seems to me, that the Poke Pointer is not correctly implemented on the Oculus Touch Controller. Can you confirm this? Is there a plan to implement the Oculus Touch Controller - Poke Pointer? 

In several apps on can use the Touch Controllers to Poke objects and buttons by pressing the Grip Button and NOT touching the Trigger button.

Thanks for your answers!

**Comment by RogPodge** [comment]
It will make it into the next 2.8 drop, for now it can be pulled from the main branch.

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10059
