### ISSUE TITLE
Cannot see HoloLens2 system keyboard display pad

### ISSUE THREAD

**Issue by rueilmanzambi** [microsoft/MixedRealityToolkit-Unity#10490]
Hello, I am building an app with MRTK in Unity and I am deploying it to the HoloLens 2. I am calling the system keyboard TouchScreenKeyboard, but it is not showing the display pad part of the keyboard, i.e., when I am entering the characters with the system keyboard inside the app, I cannot see what I am typing. I am using the default keyboard.

**Comment by MaxWang-MS** [comment]
Hi @rueilmanzambi, the lack of the preview (aka the "display pad") is a known limitation of Unity and not a bug of MRTK. If you do need one, we have an implementation in MRTK (the `MixedRealityKeyboardPreview` prefab). Please see the left-hand side of the `HandInteractionExamples` scene as an example.
