### ISSUE TITLE
Teleport with air tap

### ISSUE THREAD

**Issue by sonostrano** [microsoft/MixedRealityToolkit-Unity#10499]
I'm using the teleport system with Hololens2.
I'd like to teleport using air tap. 

How can I show the the teleport pointer  when the hand is in the poke gesture for example?

thanks

**Comment by Zee2** [comment]
Hi @sonostrano, we don't have a great story for Hololens and teleport right now. Generally, using teleportation (or locomotion) at all in AR is mostly discouraged, as it doesn't make for a very good user experience. There is no "floor" object/height in Hololens, which makes teleportation-based locomotion tricky, and breaking the connection between the in-experience reference frame and the user's real-world reference frame can reduce the immersiveness of the experience.

However, if you do need to move holograms *towards* the user (i.e., what locomotion in this context would probably be used for), you can create a root parent object and have your scene content as children of this root pivot. By moving the pivot around, you can allow the user to bring content towards them.

If this doesn't solve your needs, please reopen this and we will get back to you!
