### ISSUE TITLE
URP Camera settings are not copied over the platform one (Oculus)

### ISSUE THREAD

**Issue by eusebiu** [microsoft/MixedRealityToolkit-Unity#10505]
## Describe the bug

Main Camera settings are not copied on the platform one - e.g. Oculus.

## To reproduce

1. Create a new project
2. Add MRTK to scene
3. Add Oculus in Input 
4. Enable Post Processing in MixedRealityPlayspace/Main Camera
5. Run.

## Expected behavior

Post processing should be enabled in OVRRig cameras (Post processing not working anymore).

## Your setup

- Unity 2021.1/2
- MRTK Version 2.7.3

## Target platform

- Oculus (guess it happens also on other)

**Comment by eusebiu** [comment]
workaround:
```
#if OCULUSINTEGRATION_PRESENT
        private OVRCameraRig cameraRig;

        private void Start()
        {
            StartCoroutine(ProcessStart());
        }

        IEnumerator ProcessStart()
        {
            yield return new WaitUntil(() => CoreServices.InputSystem != null);
            yield return new WaitUntil(() => CameraCache.Main != null);

            cameraRig = GameObject.FindObjectOfType<OVRCameraRig>();

            if (cameraRig != null)
            {
                var cameras = cameraRig.GetComponentsInChildren<Camera>();
                foreach (var cam in cameras)
                {
                    var UAC = cam.GetUniversalAdditionalCameraData();
                    UAC.renderPostProcessing = true;
                    UAC.antialiasing = AntialiasingMode.SubpixelMorphologicalAntiAliasing;

                    cam.nearClipPlane = 0.1f;
                }
            }
        }
```

**Comment by Zee2** [comment]
@eusebiu thanks for reporting. @RogPodge will investigate.

**Comment by RogPodge** [comment]
This workaround should be sufficient if anyone else is hitting this issue. I couldn't get this to repro, though it might be due to a timing difference in when the camera settings are applied.
