### ISSUE TITLE
Default GazeInput permission requires manual eye calibration on HL2

### ISSUE THREAD

**Issue by srinjoym** [microsoft/MixedRealityToolkit-Unity#10509]
## Describe the bug

The MRTK initial setup process asks users to enable the "GazeInput" capability for HL2. This permission prevents Auto Eye Position (AEP) from running and requires every new user to perform manual eye calibration. We should only enable this permission if the user checks "Is Eye Tracking Enabled" in the pointer profile.

## Your setup (please complete the following information)

- Unity 2020.3.x
- MRTK 2.7.3

## Target platform (please complete the following information)
- HoloLens 2

**Comment by elbuhofantasma** [comment]
Thanks for bringing this issue to our attention @srinjoym! I am assigning @keveleigh to look into this.
