### ISSUE TITLE
QR Code Detection limit 100

### ISSUE THREAD

**Issue by vicgasor** [microsoft/MixedRealityToolkit-Unity#10518]
## Description
We were developing an app that requires working with 300+ QR codes. 
The method already used is the one described with [MixedReality-QRCode-Sample](https://github.com/microsoft/MixedReality-QRCode-Sample)
The problem came when we noticed that there is a limit of 100 callbacks from different QR codes. After exactly 100 codes the app does not receive any callback.

We already discarded that the problem came from our QR generated, but the process stops every time after 100 different detections no matter which range of our 300+ QR we use.

This came as a surprise because already tested some other client requirements, and everything works as expected, we did not expect to find some kind of limited access like this.

## To Reproduce
Just use a quick test of [MixedReality-QRCode-Sample](https://github.com/microsoft/MixedReality-QRCode-Sample) and check that you won't get any callbacks after 100 detections.

## Setup
- Unity Version 2019.4.21
- MRTK Version v2.7.0

## Target platform
- HoloLens 2

## Additional context
Our developers tried to clear all the related variables but seem that is an API limit not documented. The only related information we found is this [Link](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/3146), which is closed but seems that is not resolved.

**Comment by elbuhofantasma** [comment]
Hello @vicgasor thank you for your bug submission! @WikkidEdd is correct, this is an OS level bug. You can also use [the Submit Feedback](https://docs.microsoft.com/en-us/hololens/hololens-feedback) feature on HoloLens 2 to file the issue as well. 

I am going to close this issue since it is external to MRTK.
