### ISSUE TITLE
Project does not build for IL2CPP

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1051]
Unity 2017.2.0f1
IL2CPP scripting back end.
VS 2017 15.3.5

**Comment by jessemcculloch** [comment]
Test

**Comment by keveleigh** [comment]
Strange, this worked a few builds ago, and none of the errors are from new things. Perhaps an IL2CPP bug?

![image](https://user-images.githubusercontent.com/3580640/31105234-6913cdce-a797-11e7-9061-0eb0d19be7f3.png)

**Comment by StephenHodgson** [comment]
Did we ever test to make sure the IL2CPP built for the master branch merge?

**Comment by keveleigh** [comment]
@StephenHodgson I don't believe I tested it post-merge, but many of these errors are on scripts that were unchanged from the merge, like HapticsExtensions and ControllerVisualizer, which I know have built with IL2CPP in the past.

**Comment by StephenHodgson** [comment]
I'll check again

**Comment by StephenHodgson** [comment]
Master branch has the same issue.  I think it has something to do with the .NET 4.0+ compatibility.

**Comment by keveleigh** [comment]
Yep, changing the API Compatibility Level to .NET 4.6 allows the project to build. It looks like this was previously set in the dev branch, but was overwritten by my merge from master. I'll put out a PR to change it back.

**Comment by StephenHodgson** [comment]
@keveleigh, could you open the PR on master branch, since if affects both?
