### ISSUE TITLE
Vive Controllers Not Recognized or Supporting Pointers

### ISSUE THREAD

**Issue by methot-ilya-3ds** [microsoft/MixedRealityToolkit-Unity#10528]
## Describe the bug

Unless similar steps are followed to issue #8835 the vive controllers arent tracked. 

Even after following the steps from above the controller still does not register / attach the pointer.

## To reproduce

1. ![image](https://user-images.githubusercontent.com/64415447/161850483-23657cc9-8484-4c92-b6b2-f030afc18d71.png)
2. ![image](https://user-images.githubusercontent.com/64415447/161850607-fc9da5e2-f8d4-4ffa-ab87-184d33cc34af.png)
3. ![image](https://user-images.githubusercontent.com/64415447/161850649-51649a73-4f17-43f5-834a-242887c8bb8d.png)

## Expected behavior

Controllers to spawn and contain pointers which are trigger on controller press.

## Your setup (please complete the following information)

- Unity 2020.2.2f1
- MRTK 2.7.3

## Target platform (please complete the following information)

- OpenVR
- HTC Vive

**Comment by methot-ilya-3ds** [comment]
After numerous tries I was able to get this working by using the documentation from #8835 

The home page of MRTK claims to support HTC Vive but documentation on how to do so is nowhere to be found.

I'd recommend using the documentation that Eusebiu provided to create a page describing how to actually setup Vive controllers with MRTK.

**Comment by RogPodge** [comment]
Tracking this as a "need to update documentation" issue.

**Comment by zxzkf1992** [comment]
@methot-ilya-3ds Hi, I would like to ask, have you tried to modify the position of the fingers of the hand model through the vive controller button. For example, pressing the trigger on the controller makes the hand model a fist. I haven't been able to find an API about the relationship between vive controller input and HandJoint or HandMesh.

**Comment by methot-ilya-3ds** [comment]
To further update this ticket, MRTK 3 is working with the Vive and latest OpenXR with all of the default settings. 

@[zxzkf1992](https://github.com/zxzkf1992) I've not experimented with opening or closing of the hand yet so I can't speak to that.

**Comment by zxzkf1992** [comment]
@methot-ilya-3ds thank you for your reply, i will try on it.
