### ISSUE TITLE
HoloLens 2 Apps starting in deadlock on Unity 2020.3.32f1 and Unity 2021.2.17f1

### ISSUE THREAD

**Issue by anthony-simetri** [microsoft/MixedRealityToolkit-Unity#10520]
## Describe the bug

The application starts and shows loading animation forever. Downgrading to Unity 2020.3.31f1 allows the same application to load.

## To reproduce

Create an MRTK project with OpenXR

## Expected behavior

The application should load a scene.

## Your setup (please complete the following information)

- Unity 2020.3.32f1
- MRTK v2.7.3

## Target platform (please complete the following information)

- HoloLens 2
- OpenXR

## Additional context

I have not tested with any other settings, but I am providing a log file for the running project. The ending line states that a deadlock may occur.
[UnityPlayer.log](https://github.com/microsoft/MixedRealityToolkit-Unity/files/8382136/UnityPlayer.log)

**Comment by franzabist** [comment]
Same problem confirmed for Unity 2021.2.17f1 as opposed to 2021.2.16f1 which runs without problems.

**Comment by serhan-gul** [comment]
Same problem here. Downgrading to 2020.3.28f1 worked for the same application.

**Comment by Holo-Krzysztof** [comment]
Oof. Just ran into this as well, previously Unity 2020.3.17 and MRTK 2.7.2 worked fine.

Interestingly, when setting up an empty project with Unity 2020.3.32 and MRTK 2.7.3 I could not reproduce the bug. It only happens in our application which was upgraded from a previous Unity release. Super weird.

**Comment by anthony-simetri** [comment]
> Oof. Just ran into this as well, previously Unity 2020.3.17 and MRTK 2.7.2 worked fine.
> 
> Interestingly, when setting up an empty project with Unity 2020.3.32 and MRTK 2.7.3 I could not reproduce the bug. It only happens in our application which was upgraded from a previous Unity release. Super weird.
> 
> Might just be luck/timing though. The log is full of this:
> 
> ```
> GfxDeviceD3D11Base::WaitForLastPresentationAndGetTimestamp() was called multiple times in a row without calling GfxDeviceD3D11Base::PresentFrame(). This may result in a deadlock.
> ```

I have to admit my original project had a little more than nothing in it. Very small test project. Could be specific to one of the services running or lucky timing as you suggested.

**Comment by keveleigh** [comment]
Yep, this is an issue on the Unity side. 

As a **workaround**, if you have a pro license, disable the splash screen in your UWP settings.
Unity has found a fix for the issue and is working on getting it released.

**Comment by ABNV09** [comment]
Same problem, while Unity is fixing it, I was able to deploy successfully using 2020.3.27f1

**Comment by Holo-Krzysztof** [comment]
> Yep, this is an issue on the Unity side.
> 
> As a **workaround**, if you have a pro license, disable the splash screen in your UWP settings. Unity has found a fix for the issue and is working on getting it released.

Is there an item on Unity's issue tracker for this?

**Comment by keveleigh** [comment]
> Also, apparently it's fixed with .33, did anyone verify this?

Yep, I verified it! There's now a non-blocking follow-up bug that the Unity splash screen doesn't show up at all, but the app still launches.

**Comment by ChaoNero** [comment]
The app does launch in .33 but it becomes really laggy and fills the unitylog with errors would not recommend

.28 is the way to go

**Comment by keveleigh** [comment]
> The app does launch in .33 but it becomes really laggy and fills the unitylog with errors would not recommend
> 
> .28 is the way to go

Can you post a snippet of the errors in the log please? I hadn't been able to repro.

**Comment by ChaoNero** [comment]
> > The app does launch in .33 but it becomes really laggy and fills the unitylog with errors would not recommend
> > .28 is the way to go
> 
> Can you post a snippet of the errors in the log please? I hadn't been able to repro.

Sure ! 

It goes on normally then I get this error each call : 

GfxDeviceD3D11Base::WaitForLastPresentationAndGetTimestamp() was called multiple times in a row without calling GfxDeviceD3D11Base::PresentFrame(). This may result in a deadlock.

This started to happen when I updated the project from .13 to .33 and when I went back to .28 it stopped
