### ISSUE TITLE
SharingWorldAnchorManager AnchorStore always null

### ISSUE THREAD

**Issue by Tam66662** [Microsoft/MixedRealityToolkit-Unity#1055]
It took me all day to figure out why I was not getting an AnchorStore (always null) when using the SharingWorldAnchorManager.  I put some debug logs in its Start method, as well as its base class (WorldAnchorManager) Start method.  I found that the base class Start method never gets called.

The reason why the base class Start method never gets called is because it is 'private'.  I believe it needs to be 'protected virtual' and that the SharingWorldAnchorManager's Start method needs to explicitly call base.Start() in order for the AnchorStore to ever be ready.

I think this problem exists in just the Dev branch, not the master.  In the master, I do not see a base Start method.

Thanks for reading,
Tam

**Comment by StephenHodgson** [comment]
This class is the same on both branches.

**Comment by StephenHodgson** [comment]
Also, real quick, are you starting in the Editor?  Because if you are, you'll never get an AnchorStore anyway.

**Comment by StephenHodgson** [comment]
>The reason why the base class Start method never gets called is because it is 'private'. I believe it needs to be 'protected virtual' and that the SharingWorldAnchorManager's Start method needs to explicitly call base.Start() in order for the AnchorStore to ever be ready.

I think you're right, this might be the issue here.

**Comment by Tam66662** [comment]
@StephenHodgson This problem occurs in the HoloLens, not the Unity Editor.  I think your last reply indicates that you and I are on the same page here.  The SharingWorldAnchorManager is the same in both branches, but the base WorldAnchorManager is not the same in both branches.

Thanks for the reply,
Tam

**Comment by StephenHodgson** [comment]
> he SharingWorldAnchorManager is the same in both branches, but the base WorldAnchorManager is not the same in both branches.

That's unsettling. They should be.   Might open a new issue just for this.

**Comment by keveleigh** [comment]
Here's the diff:
![image](https://user-images.githubusercontent.com/3580640/31104189-627863e6-a790-11e7-8d04-23123b91114a.png)

Looks like a change was made in case WorldAnchorStore isn't ready in Awake. I don't know when/if this scenario might happen, but I can investigate.

**Comment by StephenHodgson** [comment]
@keveleigh, the PR fixes the discrepancy between the branches. Thanks for pulling up that diff!

**Comment by keveleigh** [comment]
@StephenHodgson Awesome! Happy to help 😄
