### ISSUE TITLE
 C1083 Cannot open include file: 'HolographicAppRemoting/StreamerHybridPlayer.h': No such file or directory

### ISSUE THREAD

**Issue by rueilmanzambi** [microsoft/MixedRealityToolkit-Unity#10559]
Hello, i am building an app with Unity and Visual Studio 2019 for the HoloLens. The most recent feature that i added is the ability to connect the application to an Azure database. When I run it on Unity, everything works as expected, but when I try to compile the project in Visual Studio in order to upload it to the HoloLens, this is one of two errors that I am getting. The other one is "MSB4181 The "CompileXaml" task returned false but did not log an error."
Does anyone know how to solve it? Everything was working well until I added that database feature.

**Comment by keveleigh** [comment]
Huh! Could you include the full build log please, if possible?

> Everything was working well until I added that database feature.

Did you have to add any UPM packages to support this? Or otherwise importing DLLs into your Assets?

**Comment by Zee2** [comment]
Stale, needs more info!
