### ISSUE TITLE
MRTK Foundation Package and other content  (Photon, Unity UI) incompatibility in Visual Studio 2019.

### ISSUE THREAD

**Issue by dantonks** [microsoft/MixedRealityToolkit-Unity#10558]
## Describe the bug

When the MRTK Foundation Package is deployed to the Unity Package, Photon and UnityUI no longer load in Visual Studio, prompting the missing assembly reference error.

## To reproduce

1: Install Unity 2021.2.15f1 (also reproduced in 2020.3.23f1)
2: Switch target platform to Android.
3: Using the Mixed Reality Feature Tool, deploy MRTK Foundation Package.
4: Install Photon Networking Package.
5: Create a script with a reference to both Unity UI and Photon networking.

## Expected behavior

Photon and Unity UI namespaces to still be accessible within visual studio when opening project scripts.

## Screenshots

[Error](https://i.imgur.com/XaKwtsv.png)
[Package Manager](https://i.imgur.com/WJASJ3f.png)

## Your setup

- Unity Version 2021.2.15f1
- MRTK Version 2.7.3

## Target platform

- Android, OpenXR

## Additional context

Photon no longer shows as in project within the package manager window (shows correctly prior to deployment of MRTK)

Photon is currently the free package during development, this will be upgraded to the paid package in May 2022 as we enter the next phase of development.

Builds do not fail and the Unity console does not display any errors. The issue only occurs within Visual Studio (installed version, 2019 version 16.11.13).

**Comment by dantonks** [comment]
MRTK namespaces are also not visible in visual studio.

**Comment by dantonks** [comment]
I have done this a few times, including a full library clear in the Unity project. Even repulled the repo and deployed the plugins fresh. No dice unfortunately.

**Comment by dantonks** [comment]
If it helps, I have tried:

Ditching the branch entirely, nuking my repo, pulling again, branching off and installing the plugins via the Mixed Reality Feature Tool again.

Deleting Libraries.

Regenerating project files.

Updating Visual Studio.

Downgrading Unity back to 2020.3.

I do still need to install the paid Photon plugin when we purchase that next week. Will feed back if this resolves it.

Hope this helps?

Dan

**Comment by MaxWang-MS** [comment]
Closing as this issue seems to be resolved.
