### ISSUE TITLE
Eye tracking pupil size (HoloLens 2)

### ISSUE THREAD

**Issue by hunter12580** [microsoft/MixedRealityToolkit-Unity#10578]
## Describe the problem

 I found it could be helpful to have pupil size data available when evaluating user's performance, measuring level of stress and calibrating UI brightness... Some alternative solutions like Pupil Labs doesn't support HoloLens 2 yet. 

## Describe the solution you'd like

It could be super continent if the EyeGazeProvider includes the pupil size function. Thanks!

**Comment by MaxWang-MS** [comment]
Hi @hunter12580, unfortunately HoloLens 2 does not support providing pupil size data to developers, and thus the MRTK team is not able to provide it.
