### ISSUE TITLE
NullReferenceException Crashes the build

### ISSUE THREAD

**Issue by izkara** [Microsoft/MixedRealityToolkit-Unity#1058]
Sorry about the weird opening/closing/editing this post.

When I build to Hololens or to PC on the Universal Windows Platform Building setting, both will build fine but then crash when they run. I tried hitting Play on the Unity editor and I get this error:

```
NullReferenceException: Object reference not set to an instance of an object
HoloToolkit.Sharing.Utilities.AutoJoinSessionAndRoom.SessionTrackerDisconnected () (at Assets/HoloToolkit/Sharing/Scripts/Utilities/AutoJoinSessionAndRoom.cs:91)
HoloToolkit.Sharing.Utilities.AutoJoinSessionAndRoom.Start () (at Assets/HoloToolkit/Sharing/Scripts/Utilities/AutoJoinSessionAndRoom.cs:57)
```

Any advice is appreciated.

**Comment by izkara** [comment]
Sorry about the weird opening/closing/editing this post.


When I build to Hololens or to PC on the Universal Windows Platform Building setting, both will build fine but then crash when they run. I tried hitting Play on the Unity editor and I get this error:

```
NullReferenceException: Object reference not set to an instance of an object
HoloToolkit.Sharing.Utilities.AutoJoinSessionAndRoom.SessionTrackerDisconnected () (at Assets/HoloToolkit/Sharing/Scripts/Utilities/AutoJoinSessionAndRoom.cs:91)
HoloToolkit.Sharing.Utilities.AutoJoinSessionAndRoom.Start () (at Assets/HoloToolkit/Sharing/Scripts/Utilities/AutoJoinSessionAndRoom.cs:57)
```

Any advice is appreciated.

**Comment by StephenHodgson** [comment]
Are you using the release version or the latest version from master?

**Comment by izkara** [comment]
I am using the one found here, I believe the latest release, on the latest Unity install:
https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/v1.2017.1.1

**Comment by izkara** [comment]
I get an error like this when I run to PC:

![image](https://user-images.githubusercontent.com/6410498/31105289-d9b5c776-a797-11e7-82d6-6f9a54a3b780.png)

**Comment by izkara** [comment]
Something I do notice is that when I run the sharing service, I do not get multiple IP addresses listed out like I see in most examples where there are usually 4. Could this be part of the problem by any chance?

![image](https://user-images.githubusercontent.com/6410498/31105347-52ee4758-a798-11e7-8b98-8d7b09f96ad8.png)

**Comment by StephenHodgson** [comment]
Try using the latest version from the master branch.

**Comment by StephenHodgson** [comment]
Try using the latest version from the master branch.  There were some fixes sense then.

**Comment by StephenHodgson** [comment]
But it looks like the Sharing Stage instance might be null.  Be sure you have the Sharing Stage in your scene.

**Comment by izkara** [comment]
Sorry, when you say sharing stage, do you mean the prefab?

**Comment by StephenHodgson** [comment]
Either the `Sharing.prefab` or your own version with the `SharingStage` component attached to a `GameObject`.

**Comment by StephenHodgson** [comment]
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/v1.2017.1.1/Assets/HoloToolkit/Sharing/Scripts/Utilities/AutoJoinSessionAndRoom.cs#L91

Can add a breakpoint on line 91 and tell me if the `SharingStage` instance, `SessionsTracker`, or the `ServerDisconnected` is null on this line?

**Comment by izkara** [comment]
Okay, well I definitely have the second option you listed going on, with SharingStage attached to an empty game object with some cubes floating around in it. I am seeing now that when I run the app locally on the PC, it now connects, but when I build it to the Hololens it still will not connect.

I am not sure how to debug on the Hololens, I've tried having the Visual Studio settings set to Debug, x86, Device, and I just hit the green play button next to Device to run, but then it just deploys, runs on the Hololens, and immediately crashes.

**Comment by StephenHodgson** [comment]
Sounds like you're missing something in your scene.

**Comment by izkara** [comment]
Hmmm. I'm attaching an image now- can you help me figure out what it is? I've been trying to figure this out for a few days now with no luck and this is the closest I'm getting. I'm using this tutorial because even the HololensAcademy 240 was not getting me anywhere, what with the lack of instructions on how to set up the HoloToolKit and everything...
https://mtaulty.com/2017/03/14/hitchhiking-the-holotoolkit-unity-leg-11-more-steps-with-sharing-holographic-experiences/


![image](https://user-images.githubusercontent.com/6410498/31106461-a8978c84-a7a0-11e7-8880-bd8316fb2fc8.png)

![image](https://user-images.githubusercontent.com/6410498/31106470-b5b11f2a-a7a0-11e7-8f9b-c83bb3f7d5e5.png)

**Comment by izkara** [comment]
I just changed the client role to secondary to try my luck- I was using primary before, though. 

![image](https://user-images.githubusercontent.com/6410498/31106537-29f59b7c-a7a1-11e7-831f-a928d5ef6a81.png)

**Comment by StephenHodgson** [comment]
Well the first thing you need to do is [this](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/GettingStarted.md#4-preparing-a-scene-for-holographic-content).

Then add the sharing prefab to your scene and you should be good to go.

Don't change the client role. That's broken.

**Comment by StephenHodgson** [comment]
Take a look at the[ SharingTest scene](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Tests/Sharing/Scenes/SharingTest.unity)

**Comment by izkara** [comment]
Hi, thanks for that feedback. I went through the steps and although it does run now, it still does not connect to the sharing server. I also have some additional errors now in the unity console.

![image](https://user-images.githubusercontent.com/6410498/31106881-76ffec04-a7a3-11e7-8475-1083c89a0860.png)

![image](https://user-images.githubusercontent.com/6410498/31106896-9977afe2-a7a3-11e7-8a02-11713a855118.png)

**Comment by StephenHodgson** [comment]
Now your build settings are wrong. Screen shot your build settings window.

**Comment by izkara** [comment]
![image](https://user-images.githubusercontent.com/6410498/31107011-5b631b8c-a7a4-11e7-9b63-5b7dd52c25fc.png)

**Comment by StephenHodgson** [comment]
I'm sorry, I mean the HoloToolkit build window.

**Comment by izkara** [comment]
Oh, that's actually in the previous screenshot but here it is cropped for you. I also made sure in player settings that everything necessary has been checked off.

![image](https://user-images.githubusercontent.com/6410498/31107140-2d603c32-a7a5-11e7-9a1b-132f94066607.png)

**Comment by StephenHodgson** [comment]
What happened to the screen shot of your build errors?

**Comment by izkara** [comment]
Oh, I got rid of those because I realized they were left over from a previous issue. Trying to keep the thread clean of frivolous things..

**Comment by StephenHodgson** [comment]
Yeah it's not related to the original. Now it seems you can't build.

What version of Visual Studio do you have installed?

**Comment by izkara** [comment]
I actually just reinstalled Visual Studio 2017 today specifically to see if they would help with these issues. I updated everything and made sure that all the items that I could find on the "individual components" list were selected.

**Comment by izkara** [comment]
I can build, and it does run on the Hololens, but it does not connect. It does show me the spatial mapping mesh edges and the cubes and the cursor, though.

**Comment by izkara** [comment]
After making the suggested changes to the Scene, I tried running the application on my PC and it no longer connects to the sharing service either.

**Comment by StephenHodgson** [comment]
> I tried running the application on my PC and it no longer connects to the sharing service

Did you put in the IP address you're trying to connect to from the Sharing Service exe window?

**Comment by izkara** [comment]
Yes. If you look at the image I posted showing the screen sharing service launcher in the command prompt, you will see the value is set as 192.168.2.40, and it is set to the same value in the server address. I did ensure the service works with the sharing manager, I was able to join and exit a room through that.

**Comment by izkara** [comment]
It would be so great if that were all it took! -.-'

**Comment by StephenHodgson** [comment]
I'd build and run the sharing test scene to make sure it's not an issue with your setup.

**Comment by izkara** [comment]
It certainly does run on the PC as I mentioned 5 comments ago, but it no longer connects at all. To be honest I actually did go through those steps before and ended up where I am now, which was why I started trying out the other tutorial I provided a link to which got me a little further, with at least the PC app connecting.

So at this time, the app will run on both the Hololens and on the PC, but neither will connect to the sharing service.

![image](https://user-images.githubusercontent.com/6410498/31107560-12ee0e9e-a7a8-11e7-9e2e-8d4b545f422d.png)

**Comment by StephenHodgson** [comment]
> It would be so great if that were all in the toolkit!

Not sure I understand. What's missing?

**Comment by izkara** [comment]
I think you misread that! I said "It would be so great if that were all it took" as in, it would be so great if it were just a matter of me getting the IP address wrong :p

**Comment by StephenHodgson** [comment]
😂 this is true!

Sorry just trying to cover all the bases.

If you're a member of the toolkit slack channel, pm me there if you want to get in depth help.

**Comment by StephenHodgson** [comment]
https://holodevelopersslack.azurewebsites.net/

**Comment by izkara** [comment]
I am not a member, but I do have slack. Joining now!
I really appreciate you taking the time to help walk me through this, seriously I've been banging my head on my desk for days now..! Thank you so much.

**Comment by izkara** [comment]
Issue was resolved by changing to a different network, there were likely security features on the one I was using before. Thanks!
