### ISSUE TITLE
The material of the hand mesh is not the material of the object specified in HandMeshPrefab in MRTKProfile.

### ISSUE THREAD

**Issue by HoloMoto** [microsoft/MixedRealityToolkit-Unity#10605]
## Describe the bug

　This issue is not confirmed on HoloLens 2 and from what I have seen it occurs on the editor and on PC builds using LeapMotion (UltraLeap).

　In MRTK, the material specified in the renderer of the prefab specified in the HandMeshPrefab of the InputProfiler's Articulated Hand Tracking should be referenced when drawing the hand.

　In HoloLens 2 this is good working.
However, in the editor and from what I've check, these are not applied to PC builds like LeapMotion(UltraLeap), and there was trouble with materials not being changed.

 From what I have seen it looks like the cause is in RiggedHandVisualizer.cs.
 By default, the controller profile specifies RiggedHandLeft.prefab (RiggedHandRight.prefab) for Global Right(Left) Hand Visualizer.
 RiggedHandVisualizer.cs.

 
![OfficeWall_Albedo](https://user-images.githubusercontent.com/36409613/169637785-a4db6701-e789-4798-a630-326319b4eace.png)

　RiggedHandVisualizer.cs is owned by this prefab, and the HandMesh material is overridden by the HandMaterial here.

　By default, the HandMeshOutline of MRTK\Providers\Oculus\XRSDK\MRTK-Quest\Art\Materials is specified, but by changing this HandMaterial, the HandMesh material can be changed in the editor and on UltraLeap's PC. I can able to change the HandMesh in the editor and in the PC build of UltraLeap by changing this HandMaterial.

I have spent so much time on this issue that I feel it should be documented or the HandMaterial in RiggedHandVisualizer.cs should reference the material defined in the MRTK profile.

## Environment

・Windows10

・Unity 2021.3.2f1(LTS)

・MRTK v2.7.3 

## To reproduce

1. Open to Unity MRTK Project.
2. Clone the default MRTK profile inputs, Articulated Hand Tracking.
3. Change HandMeshPrefab to a prefab with any material specified.
4. Check with the editor or PC Build + LeapMotion.
In this case, the material of the prefab specified in HandMeshPrefab should not be reflected and HandMeshOutline.mat should be attached to the hand mesh.
5.Change HandMaterial to any material from RiggedHandLeft.prefab (RiggedHandRight.prefab) specified in the Global Right(Left) Hand Visualizer in the Input profile.

　Check again, the material of the hand mesh has been changed.

## Expected behavior

The material specified in the HandMeshPrefab should be set as the material for the HandMesh in non-HoloLens 2 environments also.

## Target platform (please complete the following information)

・in Unity Editor 

・Windows PC Build(PC and Mac)

・UWP(PC Build)

## Additional context

I am prepared to contribute to MRTK by working on documentation or functionality changes to resolve this issue as soon as a direction is set.

Finaly, I am very sorry if this is not a bug but normal behavior and I have missed some documentation or other somewhere.

**Comment by HoloMoto** [comment]
I have also looked into others.
The default OpenXR profile, OpenXRControllerMappingProfile, has a HandSkeleton prefab, but in this case, the HandMesh is not displayed in the scene even if the HandMesh display is enabled. 

<img width="1735" alt="スクリーンショット 2022-04-11 085127" src="https://user-images.githubusercontent.com/36409613/169647687-5bddcba4-43a7-4e22-8d4a-7a62e598c710.png">


I still feel this is confusing.

**Comment by HoloMoto** [comment]
I always thought that in order to change the HandMesh material, the material specified in the HandMeshPrefab of Articulated HandTracking is used for rendering.
In fact, this is how it behaves in HoloLens 2.

However, does HandTracking other than HoloLens 2 use the prefab defined in the Controller?
　If so, I may have misunderstood.
　Articulated HandTracking allows you to switch the display of meshes, joints, etc. as part of the management of HandTracking, so if I'm right, the HandMeshPrefab is the same as the Controller's prefab, and the Controller's prefab is the same as the HandMeshPrefab. I find it confusing that there are two separate places to change the material for HandMesh.
　I feel that it would be better to have one place for the developer to look if possible.

Translated with www.DeepL.com/Translator (free version)

**Comment by RogPodge** [comment]
Hey there!

There's unfortunately a pretty confusing situation here, the `HandMeshPrefab` in the Articulated HandTracking Profile is specifically used to generate the hand mesh when the system provides valid data, the primary provider of which is the HoleLen2. In editor and on devices like VR headsets, we don't get any hand data. In these cases, the `RiggedHandLeft/Right .prefab`s render their own SkinnedMeshRenderer, which is a separate entity entirely.

We're refactoring it in the linked PR to only refer to materials. "System" Hand Mesh refers to system generated meshes, whereas "Rigged" Hand Mesh refers to hand meshes on pre-rigged models

![image](https://user-images.githubusercontent.com/39840334/169912176-4992f411-b15a-42c3-a06e-2303f5969f88.png)
