### ISSUE TITLE
Functionality of eye tracking fails depending on the language.

### ISSUE THREAD

**Issue by adrian-ArXr** [microsoft/MixedRealityToolkit-Unity#10604]
## Describe the bug

The funcionality of eye tracking is failing when we execute the program in English but when we do that in German is working properly. I use the script "Gazeprovider" from Microsoft and I don't know if is a bug from MRTK or if someone has the same problem
This problem is detected in HL2.

## Expected behavior

Eye gaze should have the same behaviour in English as in German.

## Your setup (please complete the following information)

Unity Version [2020.3.34f1]
MRTK Version [v2.7.2]
![image](https://user-images.githubusercontent.com/105932042/169554360-73512764-1074-4281-9df7-1e4c77633605.png)

## Target platform (please complete the following information)

-HoloLens 2
-OpenXR

**Comment by adrian-ArXr** [comment]
@keveleigh  I don't know if you have some other persons with the same problem.

**Comment by keveleigh** [comment]
> @keveleigh Kurtis Eveleigh FTE I don't know if you have some other persons with the same problem.

I think this is the first report I've seen! To clarify the repro steps:

1. Which locale/language is your HoloLens set to? Is that what you're switching between English and German?
1. Which locale/language is your PC / Unity set to? Is that also changing?
1. Do you have an appx or player log you might be able to share?
    1. The most helpful thing could be to do a recording of the failure case in the Feedback Hub and reporting the case number here so I can flag it internally.

Thanks!

**Comment by Spoon2311** [comment]
I'm experiencing the same issue 👍

**Comment by adrian-ArXr** [comment]
In german you can use this functionality and it is working properly  👍

**Comment by MaxWang-MS** [comment]
This does seem to be the same issue as #10154 and @keveleigh and I are working on a fix right now.

**Comment by MaxWang-MS** [comment]
The fix for this issue has been released in MRTK 2.8.1. Please let me know if you are still running into the issue!
