### ISSUE TITLE
Leap Motion tracked hand mesh switches to opposite hand while attempting to use teleport

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#10615]
## Describe the bug

When the user has one or both hands in the view of the Leap Motion device

## To reproduce

1. Set up a fresh 2.8 clone for Leap Motion (Standalone and UWP both have this issue)
2.  Open the Leap Motion Hand Tracking Example scene
3. Press the play button to start the example scene
4. Attempt to use one hand to teleport to another location
5.  See hand mesh switch to the opposite hand

## Expected behavior

The hand mesh does not switch to the opposite hand while trying to use a gesture.

## Screenshots

https://user-images.githubusercontent.com/65038391/170331377-04a8e5c4-6b75-4992-9374-5e61970fab9a.mp4

## Your setup (please complete the following information)

- Unity Version 2021.3.3, 2020.3.34, 2019.4.39
- MRTK Version prerelease/2.8

## Target platform (please complete the following information)

- Leap Motion

## Additional context

This issue does not occur if both hands are trying to use the teleport gesture but will occur if both hands are being tracked and only one hand attempts the teleport gesture. This issue also occurs when building the project and running it on a PC as seen in the attached video.

**Comment by Zee2** [comment]
Assuming this is an Ultraleap hand tracking quality problem (their tracking algos getting confused about which hand is which...)
