### ISSUE TITLE
Very low performance after publishing with MRTK3 default configuration

### ISSUE THREAD

**Issue by qiaofuwenlu** [microsoft/MixedRealityToolkit-Unity#10635]
## Describe the bug

Very low performance after publishing with MRTK3 default configuration.

## To reproduce

1. Configured following the steps demonstrated in Mixed Reality Dev Days 2022.
2. Published the scnece "HandInteractionExamples" on Hololens2.
3. The frame rate is only 10 or lower.

## Expected behavior

Just a simple scene, the frame rate should be 50 or higher.

## Your setup (please complete the following information)

- Unity Version 2021.3.4f1c1
- URP pipeline
- MRTK Version 3.0
- VS 2019
- OpenXR

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

All my configurations are based on demonstrated in Mixed Reality Dev Days 2022.
Theoretically, a simple scene should have a high frame rate，But a frame rate of 10 is unacceptable.
Is this a performance problem of mrtk3 or a problem in the default configuration？

**Comment by keveleigh** [comment]
Hmm, what are your build settings in Visual Studio? Debug/Release/Master and ARM/ARM64?
I've also heard that we're tracking some URP issues on UWP in Unity 2021 (more info at https://docs.microsoft.com/windows/mixed-reality/develop/unity/known-issues#active-blocking-issues), but I didn't think they were quite as severe as this!

**Comment by qiaofuwenlu** [comment]
Hi&nbsp;


I just tested Build-In pipeline,and it's fine, frame rate is 50 when published on Hololens2.


Other settings are the same，so the reason is the problem of rendering pipeline.


This is really exaggerated，frame rate is&nbsp;than 10 in URP.


Li




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/MixedRealityToolkit-Unity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月11日(星期六) 凌晨1:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/MixedRealityToolkit-Unity] Very low performance after publishing with MRTK3 default configuration (Issue #10635)





 
Hmm, what are your build settings in Visual Studio? Debug/Release/Master and ARM/ARM64?
 I've also heard that we're tracking some URP issues on UWP in Unity 2021 (more info at https://docs.microsoft.com/windows/mixed-reality/develop/unity/known-issues#active-blocking-issues), but I didn't think they were quite as severe as this!

**Comment by davidkline-ms** [comment]
I will be sure to follow up with Unity.

**Comment by Zee2** [comment]
@qiaofuwenlu , can you confirm you are on URP? I've not been able to reproduce perf issues *this* bad on URP.

**Comment by Zee2** [comment]
Hi, we're closing this as can't-repro for now. If you have more detailed repro information (such as a zip of the project + project settings + etc) please reopen!

**Comment by qiaofuwenlu** [comment]
Hi


My settings in VS is Release and ARM64.


Do you think it may be caused by URP? I will try Build-in today.


This problem is in Mrtk v2.x&nbsp; has a similar problem.But there is a clear contrast.
When I use MRTK v2.x, the settings in MixedRealityTookit in Hierarchy.
if select "OpenXRConfigurationProfile "the frame rate is low than 10 after publish on Hololens2.
But if select "DefaultHololens2ConfigurationProfile "the frame rate is hgih than 50 after publish on Hololens2.


There is only one Default ConfigurationProfile in Mrtk3,Without comparison, I don't know whether it is caused by the configuration file or some errors.


We look forward to your reply.


Thanks~


Li




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/MixedRealityToolkit-Unity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月11日(星期六) 凌晨1:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/MixedRealityToolkit-Unity] Very low performance after publishing with MRTK3 default configuration (Issue #10635)





 
Hmm, what are your build settings in Visual Studio? Debug/Release/Master and ARM/ARM64?
 I've also heard that we're tracking some URP issues on UWP in Unity 2021 (more info at https://docs.microsoft.com/windows/mixed-reality/develop/unity/known-issues#active-blocking-issues), but I didn't think they were quite as severe as this!
