### ISSUE TITLE
Identifier uniqueness warning in MRTK3 preview

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#10637]
Reported via holodevelopers on slack:

![image](https://user-images.githubusercontent.com/13281406/173160714-fc9c43b8-a36a-4cf5-a3a5-a14ada6f6fb1.png)

This is with the pre.6 release

**REPRO STEPS**
* Import Mixed Reality Graphics Tools
* Import MRTK Standard Assets

**Comment by keveleigh** [comment]
This is also present in MRTK2, which might help narrow down the offending object 
![image](https://user-images.githubusercontent.com/3580640/174143415-973a83ea-31e8-40c5-b89d-68cb4dd4aff4.png)

**Comment by Zee2** [comment]
@davidkline-ms , can you revisit this and ensure this is fixed?

**Comment by davidkline-ms** [comment]
warning is coming from the standard assets folder.... investigating

**Comment by davidkline-ms** [comment]
Root caused this warning to the Cheese.fbx file. It contains multiple items labeled node_id4...

**Comment by davidkline-ms** [comment]
@cre8ivepark, I do not appear to be good enough at modeling tools to resolve the multiple node_id4 entries in the model (Unity shows 3 of them, post import). Can you use your design skills to resolve the import warning?

Thanks!

**Comment by cre8ivepark** [comment]
Opened PR for the fix.
