### ISSUE TITLE
Is there a Way to Stop Hand Interactions Triggering Joystick Button Events?

### ISSUE THREAD

**Issue by jackmca** [microsoft/MixedRealityToolkit-Unity#10631]
## Describe the bug

Hand interactions are triggering joystick button events, namely the right hand pinch is triggering Joystick Button 5

## To reproduce

Use the following code in a script
`if (Input.GetKeyDown(KeyCode.Joystick1Button5))`
`Debug.Log("Pressed")`

Observe how pinching with the right hand will trigger this event.

I recognize that this is deliberate behavior,  but I was wondering if this could be disabled or amended in some way as I require a Gamepad Controller to trigger Joystick 1 Button 5 and the hand pinch is interfering with this 

## Expected behavior

There should be a way to use a Gamepad Controller input without being affected by hand interactions

## Your setup (please complete the following information)

- Unity Version 2020.3.34f1
- MRTK Version 2.7.3.0

## Target platform (please complete the following information)

- HoloLens 2

Thanks in Advance!

**Comment by keveleigh** [comment]
Unfortunately, I'm not aware of a way to do this. The main way around it I can think of would be to query the joystick names and figure out which index is the gamepad vs the hand: https://docs.unity3d.com/ScriptReference/Input.GetJoystickNames.html

**Comment by jackmca** [comment]
Thanks for the reply, i'll give that a shot
