### ISSUE TITLE
MRTK 2.8 can not find vive wand controller definitions

### ISSUE THREAD

**Issue by zxzkf1992** [microsoft/MixedRealityToolkit-Unity#10644]
## Describe the issue
I saw on the official documentation of MRTK 2.8 that MRTK already supports HTC VIVE controller natively, and I saw VIVE Wand in the controller definitions. But after I imported MRTK into Unity, I didn't find the definition of vive wand controller under Input -> controller -> controller definitions. Although running in Editor,  the HTC VIVE's helmet and controller are tracked, but I can't modify the input mapping settings in controller definitions.

Please how can I show the vive wand controller in the controller definitions?

**Here is a screenshot from the official documentation**
<img width="546" alt="Pciture1" src="https://user-images.githubusercontent.com/45712264/173473252-377546d6-f0c2-4e3f-81d5-68de69c84d02.png">

**Here is a screenshot of controller definitions in Unity**
<img width="330" alt="Picture2" src="https://user-images.githubusercontent.com/45712264/173473258-815cc493-6cdf-48db-bf6d-0d1b25b1bbf6.png">
<img width="330" alt="Picture3" src="https://user-images.githubusercontent.com/45712264/173473259-6f980b3b-466b-4272-bd8b-72595a77224b.png">

## Your Setup
- Unity 2021.3.4f1c1
- MRTK 2.8
- OpenXR

## Target Platform
HTC VIVE pro

**Comment by davidkline-ms** [comment]
@keveleigh. Can you look into concrete classes for OpenXR?
