### ISSUE TITLE
MeshOutline applied full object instead of outlining

### ISSUE THREAD

**Issue by abhilashca** [microsoft/MixedRealityToolkit-Unity#10657]
## Describe the bug

Creating new material for outline is applying material color to the entire object.

## To reproduce

1. Open `OutlineExamples` from below path

![image](https://user-images.githubusercontent.com/12084395/174430016-73a169db-3ce3-42c9-a5db-61cc6bcea5ca.png)

2. Duplicate the `Cube` on the left-side.

![image](https://user-images.githubusercontent.com/12084395/174430076-3eebf380-d0f0-43ca-9ab8-65a2b068d024.png)

3. Create new material with a color (Yellow here) with below options

![image](https://user-images.githubusercontent.com/12084395/174430182-ad91d27e-563d-4619-95a2-44cf3762a875.png)

4. Apply the material

![image](https://user-images.githubusercontent.com/12084395/174430350-5131d433-7ced-4c04-9d55-442ac46dbabd.png)

5. Run the application

6. Notice the color of the copied cube. Entire cube has Yellow color instead of outline.

![image](https://user-images.githubusercontent.com/12084395/174430301-0175ec5d-d5fb-466e-a4f0-ddcda3093955.png)

Note: If I switch the material to OutlineOrange and other colors available within MRTK, then outline is properly rendered. It appears something silly happening with the newly created material.

## Expected behavior

The applied material color should come as outline instead of applying the entire object.

## Screenshots

Already provided above.

## Your setup (please complete the following information)

- Unity Version 2019.4.14f1
- MRTK Version v2.5.3

## Target platform (please complete the following information)

- PC, Mac & Linux Standalone
- Android

## Additional context

NA

**Comment by Proton-V** [comment]
@abhilashca
