### ISSUE TITLE
Hand simulation in mrtk3 does not a work according to documentation

### ISSUE THREAD

**Issue by relaxer80** [microsoft/MixedRealityToolkit-Unity#10655]
## Describe the bug
It's not possible to rotate the left hand so that the palm is facing you in the editor. According to documentation left shift bring sup the left hand, holding lctrl + mouse move should rotate hand.  left ctrl brings up right hand. 

## To reproduce

1. setup a project with mrtk 3
2. enter play mode
3. press left shift to bring up the left hand
4. press left alt and move mouse to rotate hand. 
=>> left hand moves

## Expected behavior
left hand should rotate. 

## Your setup (please complete the following information)

- Unity Version [2020.3.27f1]
- MRTK Version [v3.0]

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

Pressing T and left alt rotates the hand as expected. Rotate command should have priority over move as in mrtk2

**Comment by Zee2** [comment]
Thanks for reporting this @relaxer80 , assigning to @davidkline-ms as he's the sim expert. I know we've had issues in the past with the input actions for the sim having issues overriding each other; this might be a known problem.

**Comment by davidkline-ms** [comment]
Hi @relaxer80,

As @Zee2 mentions, I work a lot with the simulator. There are actually multiple control schemes available in the simulator. Can you confirm that you have "MRTK v3" configured as the Control Set in the inspector?

![image](https://user-images.githubusercontent.com/13281406/176012239-f26bbefd-27d9-41c8-af9b-96e53f1c572b.png)

Thanks!

**Comment by Zee2** [comment]
Closing as stale, @relaxer80 if the above suggestion doesn't resolve your issue, please reopen! Thanks 👐
