### ISSUE TITLE
MRTK3 Far Ray Cursor not recognizing spatial map

### ISSUE THREAD

**Issue by astaikos316** [microsoft/MixedRealityToolkit-Unity#10667]
## Describe the bug

Building for MRTK3 on Hololens 2.  When trying to interact with the spatial mapping mesh to place a hologram, the far ray cursor does not show up and the far ray does not recognize it is hitting the spatial mapping mesh.

## Expected behavior

Far ray cursor should appear when far ray hits spatial mapping mesh.

## Your setup (please complete the following information)

- Unity Version 2021.3.4f1
- MRTK Version 3

## Target platform (please complete the following information)

- HoloLens 2

**Comment by Zee2** [comment]
Thanks for reporting this @astaikos316! Have you checked what layer your spatial mesh is on, vs the layermask on the ray interactor?

**Comment by Zee2** [comment]
@astaikos316 , closing as resolved assuming the layermask change fixed your issue. If you're still running into issues, please reopen! We'll make sure the layermask is configured by default if it isn't already.

**Comment by astaikos316** [comment]
I also had to add a Base Interactable Component to the Spatial Map prefab in order for it to work.  Sorry for not reporting sooner.

**Comment by ragavendranbala** [comment]
Hi @astaikos316 thanks for your reply. I have added the Base Interactable on Spatial Mesh and it is working as expected. Now I need to know how to get the ray hit position on the spatial map to instantiate an object on the far ray hit point. Can you help me on that?

**Comment by Zee2** [comment]
See other issue response @ragavendranbala !
