### ISSUE TITLE
V3 Object Manipulator editor hands cause pivot rotation of object.

### ISSUE THREAD

**Issue by JPalmerDev** [microsoft/MixedRealityToolkit-Unity#10674]
## Overview
When using the hands in the editor view and grabbing an object, it has a tendency to drift around it's Y axis so the forward facing direction is to your right

## Expected behavior
An object that is grabbed should maintain it's general orientation unless you're rotating it.

## Actual behavior
When objects are grabbed, they rotate awkwardly and don't face you.
This behavior appears to be editor only, and does not appear on HL2 devices.

## Steps to reproduce
I encountered this in the Canvas Example scene. Just grab the main window.
![image](https://user-images.githubusercontent.com/53239030/176109370-2c5ea5d2-f74a-4181-b1a7-851603517d5e.png)

## Unity editor version
2020.3.30f1

## Mixed Reality Toolkit release version
com.microsoft.mixedreality.openxr: 1.4.0
com.microsoft.mixedreality.visualprofiler: 1.0.0
com.microsoft.mrtk.accessibility: 1.0.0-development
com.microsoft.mrtk.core: 3.0.0-development
com.microsoft.mrtk.data: 1.0.0-development
com.microsoft.mrtk.diagnostics: 3.0.0-development
com.microsoft.mrtk.environment: 3.0.0-development
com.microsoft.mrtk.extendedassets: 3.0.0-development
com.microsoft.mrtk.graphicstools.unity: 0.3.15
com.microsoft.mrtk.input: 3.0.0-development
com.microsoft.mrtk.spatialmanipulation: 3.0.0-development
com.microsoft.mrtk.standardassets: 3.0.0-development
com.microsoft.mrtk.uxcomponents: 3.0.0-development
com.microsoft.mrtk.uxcore: 3.0.0-development
com.microsoft.mrtk.windowsspeech: 3.0.0-development

**Comment by Zee2** [comment]
Thanks for reporting. Can you send a screenshot of the input simulator settings you're using? Specifically, the pivot/anchor point of the hand?

**Comment by Zee2** [comment]
Can repro; this is partly due to somewhat bad recorded simulated poses.
