### ISSUE TITLE
Tilegenerator doesn't actually resize

### ISSUE THREAD

**Issue by XPav** [Microsoft/MixedRealityToolkit-Unity#1067]
Unity 2017.1, MRTK at 2017.1 release.

The Tilegenerator makes all the tiles, but all are the initial size.

**Comment by StephenHodgson** [comment]
The interesting thing is no logic surrounding the resizing was changed.

**Comment by StephenHodgson** [comment]
Really strange thing is Unity _seems_ to think it's been resized but the OS knows better.
![image](https://user-images.githubusercontent.com/13334553/31153614-09121e10-a857-11e7-8680-551945210e79.png)

**Comment by XPav** [comment]
Ok, so the tiles are now all the proper size according to the filename, but I'm still getting errors on AppX build.

Running msbuild /p:Configuration=Release;Platform=x86 from the right folder....

`  Package.appxmanifest(18,56): error APPX1619: App manifest references the square 150x150 logo image 'Assets\Square150x150Logo.scale-125.png' which does not have valid dimensions. It must be 188x188 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(18,56): error APPX1619: App manifest references the square 150x150 logo image 'Assets\Square150x150Logo.scale-150.png' which does not have valid dimensions. It must be 225x225 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(18,56): error APPX1619: App manifest references the square 150x150 logo image 'Assets\Square150x150Logo.scale-200.png' which does not have valid dimensions. It must be 300x300 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(18,56): error APPX1619: App manifest references the square 150x150 logo image 'Assets\Square150x150Logo.scale-400.png' which does not have valid dimensions. It must be 600x600 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(19,26): error APPX1619: App manifest references the wide 310x150 logo image 'Assets\Wide310x150Logo.scale-125.png' which does not have valid dimensions. It must be 388x188 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(19,26): error APPX1619: App manifest references the wide 310x150 logo image 'Assets\Wide310x150Logo.scale-150.png' which does not have valid dimensions. It must be 465x225 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(19,26): error APPX1619: App manifest references the wide 310x150 logo image 'Assets\Wide310x150Logo.scale-200.png' which does not have valid dimensions. It must be 620x300 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(19,26): error APPX1619: App manifest references the wide 310x150 logo image 'Assets\Wide310x150Logo.scale-400.png' which does not have valid dimensions. It must be 1240x600 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(18,105): error APPX1619: App manifest references the small logo image 'Assets\Square44x44Logo.scale-125.png' which does not have valid dimensions. It must be 55x55 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(18,105): error APPX1619: App manifest references the small logo image 'Assets\Square44x44Logo.scale-150.png' which does not have valid dimensions. It must be 66x66 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(18,105): error APPX1619: App manifest references the small logo image 'Assets\Square44x44Logo.scale-200.png' which does not have valid dimensions. It must be 88x88 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(18,105): error APPX1619: App manifest references the small logo image 'Assets\Square44x44Logo.scale-400.png' which does not have valid dimensions. It must be 176x176 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(8,6): error APPX1619: App manifest references the store logo image 'Assets\StoreLogo.scale-125.png' which does not have valid dimensions. It must be 63x63 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(8,6): error APPX1619: App manifest references the store logo image 'Assets\StoreLogo.scale-150.png' which does not have valid dimensions. It must be 75x75 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(8,6): error APPX1619: App manifest references the store logo image 'Assets\StoreLogo.scale-200.png' which does not have valid dimensions. It must be 100x100 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(8,6): error APPX1619: App manifest references the store logo image 'Assets\StoreLogo.scale-400.png' which does not have valid dimensions. It must be 200x200 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(20,27): error APPX1619: App manifest references the splash screen image 'Assets\SplashScreen.scale-125.png' which does not have valid dimensions. It must be 775x375 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(20,27): error APPX1619: App manifest references the splash screen image 'Assets\SplashScreen.scale-150.png' which does not have valid dimensions. It must be 930x450 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(20,27): error APPX1619: App manifest references the splash screen image 'Assets\SplashScreen.scale-200.png' which does not have valid dimensions. It must be 1240x600 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
  Package.appxmanifest(20,27): error APPX1619: App manifest references the splash screen image 'Assets\SplashScreen.scale-400.png' which does not have valid dimensions. It must be 2480x1200 pixels. [C:\dev\HoloAirTraffic\UWP\HoloAirTraffic\HoloAirTraffic.csproj]
`

**Comment by StephenHodgson** [comment]
Did you get warnings about the files being too big when generating the icons?

**Comment by XPav** [comment]
Nope.

Looking at the output UWP folder, the scaled files are all the same resolution.

![image](https://user-images.githubusercontent.com/10382630/31158206-0a455fd6-a875-11e7-8d58-bb38ce60c1f9.png)

**Comment by StephenHodgson** [comment]
I tested the PR on two different machines. This issue is fixed by #1072

**Comment by StephenHodgson** [comment]
Hmm interesting it works when building from VS but not through the build window.

**Comment by StephenHodgson** [comment]
The images are def getting cropped properly.   The issue I'm personally running into is getting it to build in Editor.

**Comment by XPav** [comment]
If you open the generated Package.appxmanifest in VS, it does in fact Red-X all the tiles with the incorrect sizes.  Then, as you say, it Builds with no warnings.   ?

Is it Unity or MRTK that's supposed making the .scale-xxx images?

**Comment by StephenHodgson** [comment]
Unity.  Yeah I see the red X's but it still builds fine in VS. Hmm. I wonder if there's something I'm missing.

**Comment by StephenHodgson** [comment]
I see it now.
They're getting cropped properly now, but they're not resized for each properly.

![image](https://user-images.githubusercontent.com/13334553/31185338-8d546faa-a8e0-11e7-9b4c-80d43036d349.png)

**Comment by StephenHodgson** [comment]
@XPav, try out my latest push.  Should be good to go now :)

**Comment by XPav** [comment]
All working, built and deployed, once I got my source image simple enough.

My splash screen looks a little cheap though, but I suspect that's due to the poor skills of the artist (me), not any code problems.

**Comment by StephenHodgson** [comment]
Can you review that PR for me?  Thanks
