### ISSUE TITLE
Spatial Mouse Support

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#10688]
Support for HoloLens-shell-style spatial/3D mouse in MRTK3. 

## Pull Request

- https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10690

**Comment by AMollis** [comment]
@shaynie can you take a look at this?  Related to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10690?

**Comment by AMollis** [comment]
Spatial mouse support has been added

- https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11643
