### ISSUE TITLE
Stateviz doesn't nullcheck tintables and continuously screams about it (2302)

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#10685]
## Describe the bug

If a tintable is null, StateViz doesn't nullcheck and will continuously NRE and not process any other effects.

- MRTK3

## Target platform
- All

**Comment by Zee2** [comment]
Closed by #10689 . @keveleigh why isn't this happening automatically? :(

**Comment by keveleigh** [comment]
> Closed by #10689 . @keveleigh why isn't this happening automatically? :(

It only auto-closes for the default branch 😓
