### ISSUE TITLE
Engine build for playables fix (2336)

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#10687]
Tracking ongoing work to resolve Playables bug with Unity support services.

**Comment by Zee2** [comment]
Update; Unity has approved a fix in 2023. Is still working on backports to 2020/2021....

**Comment by AMollis** [comment]
This appears to the bug

> When disabling an object that has Playables (AnimationClipPlayable) attached to an Animator, the current state of the animation is destructively written into the object and all current information about the animator/animation is lost.
> 
> When the object is re-enabled, the animator thinks that the current state is the "neutral/idle", and all weights and additive animations apply on top of that current state.
> 
> It easily reproduces in several ways, but two repros are included in the sample scene.
> 
> The property "keepAnimatorControllerStateOnDisable" is EXACTLY the fix we would need, but we need it to apply to Playables. That property only works for AnimatorControllers.

The issue should be addressed now by setting `keepAnimatorStateOnDisable` to true.  This is from Unity

> The releases that contain the backport fixes for the following issue are finally available ([Unity 2021.3.16f1](https://unity.com/releases/editor/whats-new/2021.3.16) and [Unity 2020.3.43f1](https://unity.com/releases/editor/whats-new/2020.3.43)):
> 
> Animation: Fixed issue where, for some playable graphs, the animated displacement of the animated game object would keep accumulating when the game object was disabled and enabled. The original behaviour can be restored with the keepAnimatorStateOnDisable variable. ([UUM-3486](https://issuetracker.unity3d.com/issues/playables-lose-the-animator-state-when-disabling-a-gameobject-with-playables-attached-to-an-animator))

**Comment by AMollis** [comment]
We're not sure what is impacted by this bug, or what is the actual issue.

Closing this for now.   Zee2, if you have more information, please add here
