### ISSUE TITLE
Quick Question: Does MRTK3 break existing MRTK2 projects?

### ISSUE THREAD

**Issue by cafigz** [microsoft/MixedRealityToolkit-Unity#10680]
Hi!

I have my project all setup and working with MRTK2 and I like the new prefabs. Does adding the new MRTK3 break the existing project?

Best regards!

**Comment by Zee2** [comment]
For now, we don't support intermingling MRTK3 features with MRTK2 projects, with the exception of data binding. Stay tuned for additional info + guidance regarding migrating existing MRTK2 projects to MRTK3.

**Comment by cafigz** [comment]
Thanks, for now all I want to do is to import new buttons and hand menu prefabs 👍🍡
Best regards!
