### ISSUE TITLE
FastConfigurable Lighting

### ISSUE THREAD

**Issue by LanceMcCarthy** [Microsoft/MixedRealityToolkit-Unity#1070]
I'm seeing a weird behavior with materials using the FastConfigurable shader.

See [this screenshot](https://www.screencast.com/t/OPiJFF1s) of what I'm reporting. I put an extra bright point light in that corner to have better contrast.

@dbastienMS Did I misconfigure the shader? All I did was add it to the material and set the albedo texture

**Comment by LanceMcCarthy** [comment]
Forgot to add my environment facts:
- Windows Insider: Fast (16299.15)
- Unity 2017.2 RC (aka f2 MRTP, [this latest](https://forum.unity.com/threads/custom-build-2017-2-rc-mrtp-windows-mixed-reality-technical-preview.498253/) version, which fixes MR issues)
- Visual Studio 2017 (latest release to 15.3)

**Comment by derdimi** [comment]
I updated to Unity 2017.1.1p4 yesterday. Now HoloToolkit's InteractiveMeshCursor is red instead of white. It also uses the FastConfigurable shader. I will also try 2017.2.0f2 RC2 later.

**Comment by davidkline-ms** [comment]
FastConfigurable has been deprecated in favor of the new Mixed Reality Toolkit / Standard shader. You are likely to get better results with the new shader.
