### ISSUE TITLE
crash when start spatial mesh MRTK3

### ISSUE THREAD

**Issue by qiaofuwenlu** [microsoft/MixedRealityToolkit-Unity#10701]
## Describe the bug

Always crash when open spatial mesh.
If Hololens2 connected on my LAN server, when open spatial mesh  it inevitable crash.

## To reproduce

1. Stop mesh spatial at start.
2. Start spatial mesh when necessary.
3. There is a 30% chance of crash.
4. If Hololens2 connected on my LAN server, when open spatial mesh  it inevitable crash.

## Expected behavior

Start spatial mesh normally.

## Your setup (please complete the following information)

- Unity Version 2021.3.4.f1c1
- MRTK3
- Build-In RenderPipe

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

I think it may not be the performance reason, because the frame rate is always kept at 30-60,And as long as it is opened successfully, it will not get stuck.

When I use MRTK2.X There is no such error,and it's different spatial systems.Now in MRTK3 use XRMeshSubsystem.Start()

**Comment by astaikos316** [comment]
Have you tried just adding a ARSpatialManager GameObject to your XR Rig and add the ARMeshManager script to it?

**Comment by qiaofuwenlu** [comment]
Of course, now it is just what you said,the ARSpatialMeshManager GameObject With ARMeshManager is under MRTK XR Rig.
If I don't change it dynamically, there is no problem.
But if I use code to Start or Stop, there always be problems,especially Start.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/MixedRealityToolkit-Unity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月4日(星期一) 凌晨1:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/MixedRealityToolkit-Unity] crash when start spatial mesh MRTK3 (Issue #10701)





 
Have you tried just adding a ARSpatialManager GameObject to your XR Rig and add the ARMeshManager script to it?

**Comment by GiovanniTurri** [comment]
I would try to replicate your situation @qiaofuwenlu , but I need a hand on the build side: using 2021.3.5f1, I tried to switch platform to build (both UWP and, in an other copy of the project, Android) but I have `Assets\BuildAssets\BuildApp.cs(7,19): error CS0234: The type or namespace name 'Build' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)`
Did you faced it too?
Thank you

**Comment by RogPodge** [comment]
Hey there, thanks for filing an issue!

Can you provide some more details as to the nature of the crash? Were there any error messages logged? My first instinct is that this might not be a solely MRTK3 issue.

**Comment by GiovanniTurri** [comment]
Thank you @RogPodge 
I think I didn't add something from MixedRealityFeatureTool.exe
Downloading the GitHub MRTK zip and loading there my scene, it now builds :D

**Comment by RogPodge** [comment]
I don't think we can do much to help tackle this issue without logs. The code provided here also isn't super helpful.
