### ISSUE TITLE
I can't use hand move model with oculus quest2

### ISSUE THREAD

**Issue by KorxGame** [microsoft/MixedRealityToolkit-Unity#10707]
## Describe the bug

I can't use handController move model with oculus quest2

## To reproduce

[新建文本文档.txt](https://github.com/microsoft/MixedRealityToolkit-Unity/files/9055825/default.txt)

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.3.5f1]
- MRTK Version [e.g. v3.0]

## Target platform (please complete the following information)

- Oculus quest2

**Comment by Zee2** [comment]
Unfortunately, we need more info to resolve this issue. Please reopen when you've got more context, we look forward to figuring it out with you. Thank you!
