### ISSUE TITLE
Build Window improvements

### ISSUE THREAD

**Issue by DDReaper** [Microsoft/MixedRealityToolkit-Unity#1071]
Noted a few minor niggles with the Build Window:

- [x] Will let the user build with no scenes in the project (noob fail)
- [x] Make sure the selected option is reflected in the built project (test)- Unity still defaults to ARM which is not helpful
- [X] Needs to be able to support IL2CPP scripting target.  (Some Unity features such as PostProcessing only work on IL2CPP)
- [x] Update "View Log File" for local build if we're not targeting the HoloLens.
- [ ] ~~Disable / skip "Unity C# Projects" when using "Build AppX" or "Build sln / Build AppX" as this fauses the build to fail.~~

**Comment by StephenHodgson** [comment]
The IL2CPP can be easily changed in the Configure/Apply Mixed Reality Settings and in the Player Settings, but I could replace the MS Build Version Label with this instead. (We don't really need to know what Build Version we're using anyway seeing as the SDK pretty much spells it out for us)

**Comment by StephenHodgson** [comment]
We should update the default platform to x86 for HoloLens and x64 for HMDs

**Comment by DDReaper** [comment]
Another issue to "fix" is to "UnCheck" / Disable the "Unity C# Projects" option automatically when using "BuildAppX" or "Build sln /AppX" as this causes the build to fail.
Edited header post.

**Comment by DDReaper** [comment]
Hmm, also noticed they have changed the "Windows Universal" build options. So these should probably be taken in to account in the Build Window
![image](https://user-images.githubusercontent.com/1793042/31169993-65accf30-a8f2-11e7-8cd7-7a51b5e30885.png)

**Comment by StephenHodgson** [comment]
I've already taken this into consideration.

**Comment by StephenHodgson** [comment]
The unity C# projects really ought to work and is a unity bug.  I'm not sure if there's a benefit to changing this.

**Comment by DDReaper** [comment]
SO do you want to remove the "C# Projects" request?
That just leaves the "Build Log" button request.  Had a few builds fail and even though there was a log, the button was disabled?

**Comment by StephenHodgson** [comment]
> SO do you want to remove the "C# Projects" request?

I'd rather remove. It _should_ get fixed by unity at some point.

**Comment by DDReaper** [comment]
Removed the C# project task, added to the "fix later" bucket
