### ISSUE TITLE
Official Support for "Enter Play Mode Settings" without domain reload 

### ISSUE THREAD

**Issue by TheOnlyMunk** [microsoft/MixedRealityToolkit-Unity#10724]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/296

___

## Describe the problem

I'm always frustrated when [...]

I enter play mode and it takes 10+ seconds to start.

## Describe the solution you'd like

Would love for MRTK to officially support the option under Project Settings -> Editor- > Enter Play Mode Options (true) -> Reload Domain (false) + Reload Scene (false). 

![image](https://user-images.githubusercontent.com/23356406/178274670-28130ddd-3cac-4568-a88c-8e0ace35fa39.png)

When toggling off "Reload Domain" I get a bunch of errors.

## Describe alternatives you've considered

Not having fast iteration times or try to dig deep into the MRTK architecture to solve manual reloads myself. 
Wanted to hear whether it's something that is already being looked into or not.

**Comment by Zee2** [comment]
I believe this is something that's actually blocked by the underlying input system, and other deeper things out of our control... Most of the time when I've tried to do a no-reload change, it's been non-MRTK things complaining (input system, XR plugins, etc...)

**Comment by AMollis** [comment]
@shaynie anything we can do anything here?
