### ISSUE TITLE
Changing profile at runtime with MixedRealityToolkit.Instance.ActiveProfile = profileToUse; throws NullReferenceException

### ISSUE THREAD

**Issue by nutmeg15** [microsoft/MixedRealityToolkit-Unity#10720]
## Describe the bug

When attempting to set a profile at runtime by following [these](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/configuration/mixed-reality-configuration-guide?view=mrtkunity-2022-05#active-profile-switch) instructions, a null reference error is thrown.

## To reproduce

1. Configure and save an MRTK profile
2. Give the script a public MixedRealityToolkitConfigurationProfile named profileToUse
3. Include MixedRealityToolkit.Instance.ActiveProfile = profileToUse
4. Set profileToUse to the previously saved MRTK profile in Unity Inspector
5. Run in play mode to get the error
## Expected behavior

The MRTK profile should switch easily.

## Screenshots
![image](https://user-images.githubusercontent.com/32004180/178048908-cba79029-25a1-4a63-ada1-98fe8dc6f10c.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.36f1
- MRTK Version v2.7.3.0

## Target platform (please complete the following information)

- Oculus Quest 2

**Comment by Proton-V** [comment]
@nutmeg15 
Hello. You can use `MixedRealityToolkit.SetProfileBeforeInitialization` if you want switch profile before initialization
```
using Microsoft.MixedReality.Toolkit;
using UnityEngine;

public class PreInitProfileSwapper : MonoBehaviour
{
    [SerializeField]
    private MixedRealityToolkitConfigurationProfile newProfile;

    void Awake()
    {
        MixedRealityToolkit.SetProfileBeforeInitialization(newProfile);
    }
}

```

Please use `MixedRealityToolkit.Instance.ActiveProfile = profileToUse` at runtime if you have active profile.

Also you have `[DefaultExecutionOrder]` attribute to set Awake/Start call before/after other scripts. Like this:
```
[DefaultExecutionOrder(-1)]
public class PreInitProfileSwapper : MonoBehaviour
{
```

Have a nice day 😊

**Comment by Proton-V** [comment]
Also I checked it again and got error stack when I have active MixedRealityToolkit Inspector. I sent micro changes for this issue
