### ISSUE TITLE
Fallback Controller Models for MRTK3

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#10731]
In cases where the platform does not provide controller models to use, we want to have generic controller models that users can use to visualize their controllers

**Comment by SimonDarksideJ** [comment]
Having just done some testing with Quest, this is something I would highly support. It also appears that MRTK3 has introduced a regression issue in this area.

In MRTK 2 it is possible to assign different controller models per platform (including the above aforementioned fallbacks).  However, in MRTK3 it is only possible to assign a single controller model directly to the Articulated Hand controller (which is also odd if you want controller models and not hands).

There are also several options for assigning models to the Articulated Hand Controller which are not yet documented as to their effect.

Might be worth moving the controller models configuration to an area that support per-platform configuration, with the fallback support.

There is also a question for how custom hand models could be used with Animation, as the Articulated hand controller appears to support this use case, but is still waiting on the documentation train.  The current documentation link taks you to the Unity Input Actions Controller page which does not explain the inspector screen.

**Comment by Zee2** [comment]
#10787 I believe is tracking this now!

**Comment by RogPodge** [comment]
Completed as of #10787
