### ISSUE TITLE
Update audio demos and spatializer settings

### ISSUE THREAD

**Issue by david-c-kline** [microsoft/MixedRealityToolkit-Unity#10744]
The currently imported (into the MRTKDevTemplate) generates a repeating series of warnings, unless the sound output device is configured for Windows Sonic.

At the very least, documentation needs to be authored to explain the warning and how to eliminate it. NOTE: The warning does not occur on HoloLens 2 devices.

Ideally, the spatializer should be updated to the latest and the audio demos configured for the new requirements (ex: use of an AudioMixer component, etc.) AND demo documentation should be written to describe the requirements and what they enable.

**Comment by AMollis** [comment]
@marlenaklein-msft  there are 5 issues related to spatial audio,  Can you help provide more context on these issues, and resolve any deduplicates?

The spatial audio issues area:

1. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6897
3. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10744
4. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10979
5. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11176
6. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11177

**Comment by marlenaklein-msft** [comment]
Closing this and consolidating spatial audio bugs into three issues:
[Add Warning for Missing Audio Mixer (Spatial Audio)](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11431)
[Updating Sample Scenes with Mixer for Spatial Audio](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11432)
[Documentation for Spatial Audio](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11433)
