### ISSUE TITLE
Bug in WorldAnchorManager.AttachAnchor method

### ISSUE THREAD

**Issue by eluchsinger** [Microsoft/MixedRealityToolkit-Unity#1074]
According to the documentation of the `AttachAnchor(GameObject gameObjectToAnchor, string anchorName = null)` method, you can provide an anchor name or leave it empty. In case you leave it empty, the method uses the name of the GameObject. The documentation of the parameter `anchorName` says, the name is a generated GUID.

```
<summary>
Attaches an anchor to the GameObject.  
If the anchor store has an anchor with the specified name it will load the anchor, 
otherwise a new anchor will be saved under the specified name.  
If no anchor name is provided, the name of the anchor will be the same as the GameObject.
</summary>
<param name="gameObjectToAnchor">The GameObject to attach the anchor to.</param>
<param name="anchorName">Name of the anchor.  If none provided a GUID is generated for you.</param>
<returns>The name of the newly attached anchor.</returns>
```
Right now, the framework overwrites my custom name and sets the gameObject name instead. The reason for this is the conditional being wrong. Instead of this:
`anchorName = string.IsNullOrEmpty(anchorName) ? anchorName : gameObjectToAnchor.name;`

it should be like this:
`anchorName = string.IsNullOrEmpty(anchorName) ? gameObjectToAnchor.name : anchorName;`

I will try to fix this myself or call for help if I can't get it running. This means that I will go with the GameObject name, instead of the GUID and update the XML Documentation.

**Comment by StephenHodgson** [comment]
Thanks for the report. I'll be sure to update the documentation as well.  The reason I changed to to be the game object name, instead of a guid, was to make it easier to spawn and anchor GameObjects without needing to know the guid ahead of time. All anchored GameObjects should have a unique name.

**Comment by eluchsinger** [comment]
I am trying to create one, but I don't find a lot of [information](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit-UnitTests )  about creating UnitTests. Do I have to import NUnit myself using NuGet? Can I add the tests in a new Test class under `HoloToolkit-UnitTests/Utilities/WorldAnchorManagerTest.cs`?

**Comment by StephenHodgson** [comment]
@Zod- knows a bit more about this.

**Comment by eluchsinger** [comment]
@Zod- I would still be interested in knowing if I can add Unit Tests for this case, if possible.

**Comment by Zod-** [comment]
@eluchsinger There is no need to import anything. NUnit is already included with Unity. Just create a new class and add tags to test methods and then you can run it from the `Test Runner` window in the Unity Editor.
In the Editor, you can also create a template file using `Create > Testing > EditMode Test C# Script`.

For this particular method, you'll have to extract that logic into a separate method since it won't run in the editor e.g.:
```CSharp
public static string GenerateAnchorName(GameObject gameObjectToAnchor, string anchorName = null)
{
    return string.IsNullOrEmpty(anchorName) ? gameObjectToAnchor.name : anchorName;
}
```

And then test it.
```csharp
public class WorldAnchorManagerTests
{
    [Test]
    public void TestGenerateAnchorNameFromGameObject()
    {
        const string expected = "AnchorName";
        var gameObject = new GameObject(expected);
        var result = WorldAnchorManager.GenerateAnchorName(gameObject);
        Assert.That(result, Is.EqualTo(expected));
    }

    [Test]
    public void TestGenerateAnchorNameFromParameter()
    {
        const string expected = "AnchorName";
        var gameObject = new GameObject();
        var anchorName = WorldAnchorManager.GenerateAnchorName(gameObject, expected);
        Assert.That(anchorName, Is.EqualTo(expected));
    }
}
```

![image](https://user-images.githubusercontent.com/5775094/31202150-ccb759e2-a961-11e7-863e-b9340141d92e.png)
