### ISSUE TITLE
[MRTK3] Bounds control - Flickering handles

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#10753]
## Describe the bug
Bounds control's handles are flickering on the device. 

## To reproduce
Build and deploy HandInteractionExamples scene to HL2.

https://user-images.githubusercontent.com/13754172/179493963-f07efebb-e684-4d32-8e8d-5650796ab231.mp4

**Comment by Zee2** [comment]
This is due to the Windows SDK version being used during the compile process. Yes, seriously 😅 Just use a more up-to-date SDK version during the compile process and you should be good to go.
