### ISSUE TITLE
Refactor Solver System to be more extendible and user friendly

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#10759]
Based on comments left from #10748 

Basically, Solvers needlessly inherit from Monobehaviors so that they can exist as components on a gameobject, even though they do not perform any independent actions during update. This results in several design quirks, like relying on inspector ordering and having to register and unregister from a SolverHandler.

This issue tracks re-architecting the system to improve on the current design.

**Comment by keveleigh** [comment]
Previously discussed in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/2798 and https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4675 as well.

**Comment by SimonDarksideJ** [comment]
Ahh, this brings back such memories @keveleigh  and for beating me to referencing that age old request :D

**Comment by AMollis** [comment]
Related PR #11323
