### ISSUE TITLE
Mixed reality portal crashes

### ISSUE THREAD

**Issue by glvidrine8** [Microsoft/MixedRealityToolkit-Unity#1076]
When I open the mixed reality portal and turn on the headset button ON SCREEN it Reyes to load then the screen flickers on and off a couple times then it says driver failed to start and only one of my monitors work.i have to restart my pic to get them both on.

**Comment by StephenHodgson** [comment]
Might want to check the forums for help on this.
Issues should be directly related to the toolkit.
