### ISSUE TITLE
Linear Color Space Support

### ISSUE THREAD

**Issue by jloehr** [microsoft/MixedRealityToolkit-Unity#10774]
## Describe the bug

From the ["Updates on OpenXR for Mixed Reality"](https://www.youtube.com/watch?v=RkWeRmtWyVo&t=1438s) talk during the MR DevDays, it was mentioned that with OpenXR HoloLens supports Linear Color Space. However it seems the MRTK shaders are lacking proper Linear Color Space support.

Switching to Linear results in various colors being off or other rendering artifacts like light bleeding on the UI backplates.

## To reproduce

1. Open your MRTK project and switch to Linear Color Space in the UWP Player settings.
2. Build a scene with the hand mesh visualizer enabled and other UI building blocks.
3. Observe hand mesh coloring being much more darker, as well as light bleeding on UI backplates.

## Expected behavior

Overall visuals is the same or just minor color blending variations.

## Screenshots

Linear Color Space
![OpenXR_Linear](https://user-images.githubusercontent.com/4631548/180201517-22c8312d-6917-4ee7-b94b-0e3613bd1298.jpg)

Gamma Color Space
![WMR_Gamma](https://user-images.githubusercontent.com/4631548/180201527-216cd8b1-e6e3-40d0-b079-31d1e4d1c85d.jpg)

## Your setup

- Unity 2020.3.20f1
- MRTK 2.8.2

## Target platform 

- HoloLens 2

**Comment by Zee2** [comment]
@Cameron-Micka, confirming that MRGT + other internal projects are fully linear? We will be moving MRTK3 to Linear imminently, but we probably would like some guidance + handholding (especially for the huge number of legacy materials/components/etc in MRTK2)

**Comment by Zee2** [comment]
@jloehr , thanks for filing this. We're definitely in the process of moving everything to Linear as soon as we can; it's just a large process with a lot of moving parts. We'll use this issue to reference other linear space problems.

**Comment by Cameron-Micka** [comment]
> @Cameron-Micka, confirming that MRGT + other internal projects are fully linear?

Yes, general guidance these days is to develop in linear color space. Gamma was the old recommendation because not all hardware had native linear color support (if your platform returns true when calling [this API](https://docs.unity3d.com/ScriptReference/Display-requiresSrgbBlitToBackbuffer.html) then using a linear color space may hurt performance. But most platforms these days will return false.)

Also, all shaders assume calculations are done in linear color space. This means Unity will automatically do sRGB to linear color conversion on textures and colors when necessary. There are some edge cases here we have tried to account for in our shaders. But if you find any others, please raise them as a bug!

> We will be moving MRTK3 to Linear imminently, but we probably would like some guidance + handholding (especially for the huge number of legacy materials/components/etc in MRTK2)

Certainly! I wish one set of content could exist for both color spaces, but this is almost never the case so a lot of hand tuning will have to be done to re-author colors and textures. I'd nominate @cre8ivepark to help out as well since he has a great eye for this. 😊

**Comment by jloehr** [comment]
> We will be moving MRTK3 to Linear imminently, but we probably would like some guidance + handholding (especially for the huge number of legacy materials/components/etc in MRTK2)

> We're definitely in the process of moving everything to Linear as soon as we can;

That's great to hear, looking forward to MRTK3 GA 👍 

Also, I wasn't sure whether Linear space support was on the feature list in the first place, so feel free the change this issue from **Bug** to **Feature Request**.

Regarding the articulated hand mesh, it seems it's not just a color issue, but also an alpha blending issue with content in the background:
![image](https://user-images.githubusercontent.com/4631548/180777997-839eedba-c973-4e0c-897d-7e6a1091ec7f.png)

>  I wish one set of content could exist for both color spaces, but this is almost never the case so a lot of hand tuning will have to be done to re-author colors and textures.

In case it's of any value, there is the[ `UNITY_COLORSPACE_GAMMA` builtin shader define](https://docs.unity3d.com/ScriptReference/Rendering.BuiltinShaderDefine.UNITY_COLORSPACE_GAMMA.html), as well as the builtin `GammaToLinearSpace` shader helper function for shader properties that are not automatically converted.

**Comment by cre8ivepark** [comment]
Thanks @jloehr! Looking into this with technical designers and trying to see how we can achieve a similar color & contrast for MRTK3 materials. It seems not too much tweak for UI (backplate/innerplate, etc) but for other default MRTK color material series, trying to figure out how to fix the overall dull color and increase contrast & highlights. 

For your hand menu UI, the one you are using has 'Inner Glow' turned on which gives you 'bleeding light'. It is coming from the HandMenuLayoutExample scene and they have slightly different backplates than the original HoloLens 2 UI backplate which does not use Inner Glow property.

![2022-07-28 21_13_40](https://user-images.githubusercontent.com/13754172/181502712-5be7a612-c4e8-4b27-8bf3-cadc2796836b.png)
![2022-07-28 21_13_23](https://user-images.githubusercontent.com/13754172/181502721-0ddef6f5-1bdd-4ed0-ad76-22ddd192e18d.png)


To fix this, you can just adjust or uncheck Inner Glow property in the HandMenu_Backplate.mat
 
![2022-07-28 21_09_53](https://user-images.githubusercontent.com/13754172/181502768-d51597e1-cf21-4451-a130-5071d2677d42.png)

**Comment by MaxWang-MS** [comment]
This issue should have been fixed via #10871 and will ship in pre.11. Please feel free to reopen if you are still experiencing this issue.
