### ISSUE TITLE
Interaction Mode Manager Prioritized Interaction Modes bug

### ISSUE THREAD

**Issue by LocalJoost** [microsoft/MixedRealityToolkit-Unity#10770]
## Describe the bug

If you expand the first item ("Far") it appears over the seconds and the result is quite unreadable

![image](https://user-images.githubusercontent.com/4129183/179961305-1d9b245f-7116-49bc-9bcb-23f487968382.png)

## To reproduce

See image above

## Expected behavior

Panel should not appear over the items below but should expand properly. Like items 2-5 in the list

## Your setup (please complete the following information)

- Unity Version 2020.3.35f1
- MRTK Version 3.0.0-pre7

**Comment by Zee2** [comment]
Tagging + assigning @RogPodge as he is King of Mode Management ;)

**Comment by LocalJoost** [comment]
Maybe I should have explicitly added this is about MRTK3 but I hope that is clear from context 😊

**Comment by RogPodge** [comment]
I think this was a unity inspector bug 😅. Let me try to find the source issue but it's definitely something we need to address. I'll be sure to follow up!

**Comment by RogPodge** [comment]
Fixed with Unity 2020.3.37 and above!

https://issuetracker.unity3d.com/issues/first-array-element-expansion-is-broken-for-arrays-that-use-custom-property-drawers
