### ISSUE TITLE
It is possiable through the vive controller button control the HandJoint???

### ISSUE THREAD

**Issue by zxzkf1992** [microsoft/MixedRealityToolkit-Unity#10773]
## Describe the problem

I would like to ask if there is an API to modify the pose data of the hand model through the vive controller button? For example, 
by default, pressing the trigger button of the vive controller will move all fingers except the thumb to the palm. I want to modify this relationship, but I can't find the API between vive controller input and HandJoint. If anyone has done related content, or knows the API, please let me know, thanks !

## Additional context

MRTK 2.8.0
HTC VIVE pro controller 
steamVR
Unity 2021.3.4f1

**Comment by Zee2** [comment]
@keveleigh, are these OpenXR joints or SteamVR-proprietary joints or what?

**Comment by keveleigh** [comment]
Hmm...assuming this is from the OpenXR APIs, the only way I'm aware of the influence the joints is via the hand joint motion range API https://registry.khronos.org/OpenXR/specs/1.0/man/html/XrHandJointsMotionRangeEXT.html.

I actually just merged a PR in the Mixed Reality OpenXR Plugin to add support for this extension, and the API should ship in the 1.5.0 release of that package.

**Comment by Zee2** [comment]
Closing as 1.5.0 is imminent!
