### ISSUE TITLE
Thermal Power Notification SDK is not recognizing events based on peripherals selected

### ISSUE THREAD

**Issue by hemasree99s** [microsoft/MixedRealityToolkit-Unity#10777]
## Describe the bug

Thermal Power Notification SDK is not recognizing  events based on peripherals monitored in Hololens 2

## To reproduce

Tried with example suggested in  https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/managing-power-and-thermals

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.3.20f1]
- MRTK Version [e.g. v2.7.3]
- OpenXR

## Target platform (please complete the following information)

- HoloLens 2

**Comment by hemasree99s** [comment]
@chorkin

**Comment by chorkin** [comment]
@hemasree99s , what OS version are you using?  The SDK is supported starting with 22H1 [20348.1501] (https://docs.microsoft.com/en-us/hololens/hololens-release-notes) and the insider release that just preceded it.

**Comment by chorkin** [comment]
And what is the result?  Does not recognizing peripherals mean that no notifications are received or is something else happening?  Please provide as many details as possible

**Comment by hemasree99s** [comment]
Thanks for the quick update. Currently, we use 20348.1511.arm64fre.fe_release_svc_sydney_rel_prod.220705-1520. I tried to monitor battery peripheral. Though I had less than 50% of charges, it says as no user impact

**Comment by hemasree99s** [comment]
What is the minimum MRTK version it supports?

**Comment by chorkin** [comment]
PowerThermalNotification does not require MRTK.  To be clear the events this SDK uses are based on **thermal** notifications.  Battery percentage would not be an event you could monitor.  There are system APIs for that kind of notification.  This SDK would allow you to receive a notification if the batter was becoming warm/hot.  If you wanted to test the event without actually having a hot battery, there's a link to the following page in the article: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/using-the-windows-device-portal#powerthermalsdk-test

**Comment by hemasree99s** [comment]
I tried using power thermal sdk test and it worked. Was trying to test the same in Hololens 2. Also, How does the mitigation level being mapped to cpu and battery peripherals? 
Does the cpu utilization percentage mapped directly differenrlt mitigation levels?

**Comment by chorkin** [comment]
To reiterate: This is **thermal notifications**.  The only notifications the SDK provides are based on temperature information in the system.  The peripheral you are listening to is fed information by sensors in local proximity.  So for CPU this would be temperature information near/around the CPU.

**Comment by hemasree99s** [comment]
Thanks for the timely help!
