### ISSUE TITLE
[MRTK3] Input Simulator controls are broken

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#10789]
## Describe the bug

You can't hold down spacebar + control to move the hand, select, and rotate anymore. You used to be able to. (Previously in MRTK3)

In addition, if you try and use control _only_, the simulator gets into a state where the left mouse button doesn't even initiate a grab anymore. This makes it basically impossible to do any kind of rotations with the input sim. The only way to do it is to use the T/Y toggle system, but even then it's impossible to do a grab in-place. It requires you to move the hand during your rotation, which is extremely kludgy.

@keveleigh, I wouldn't be terribly surprised if that has something to do with the input system changes we did a while ago?

## To reproduce

Use input sim, try and rotate an object.

## Expected behavior

You should be able to hold down spacebar to make the right hand appear, and then also hold control to enable/disable rotation, all the while the LMB should still function.

## Your setup (please complete the following information)

- MRTK3 `mrtk3` branch

**Comment by Zee2** [comment]
We may be replacing our current input simulator with XRI's new one in 2.3. See #11282.

**Comment by AMollis** [comment]
@srinjoym can you verify in editor?   @shaynie can you investigate pulling in the new simulator from 2.3

**Comment by Zee2** [comment]
@AMollis I've literally been laid off, please try to avoid assigning me these issues as it sends me notification spam (and I'm also legally restricted from contributing to this project)

**Comment by shaynie** [comment]
I tried the new XRI toolkit 2.3 simulator, and I don't recommend switching to it for GA.  Pulling in XRI 2.3 did not seem to break any input in editor on Hololens, so we should still consider it for GA.
