### ISSUE TITLE
Gaze Provider Settings not serialized in Pointer Profile

### ISSUE THREAD

**Issue by JakobAnarkyLabs** [microsoft/MixedRealityToolkit-Unity#10786]
## Describe the bug

From MRTK 2.8.0 and onwards, it has been possible to set the 'Gaze Provider Settings' on the MixedRealityPointerProfile, which is great. However, these settings are not serialized in the profile ScriptableObject (MixedRealityPointerProfile) as is generally the case with the settings in the profile system. Rather, the custom inspector for the MixedRealityPointerProfile just binds to the serialized settings on the IMixedRealityGazeProvider on the currently active main camera (CameraCache.Main) - it will be serialized in the scene files.  This means that the MixedRealityPointerProfile does not actually hold the 'Gaze Provider Settings' as you would expect. You can have different settings in different scenes, and if you switch scenes, you will see the settings on the (same) MixedRealityPointerProfile actually change.

You could argue whether this is a bug or not, but I think that the behaviour goes against the general use and understanding of the profile system - that the profiles hold (and show) settings that can be re-used across the whole application.

## To reproduce

1. Create two different scenes (Scene1 and Scene2) with MRTK configured to use the same MixedRealityToolkitConfigurationProfile.
2. With Scene1 open, change some Gaze Provider Setting in the commonly shared MixedRealityPointerProfile (Input->Pointers, Clone the asset if currently using the default read-only one).
3. Notice that the Scene1 scene file has changed and save the scene file.
4. Open Scene2 and then inspect the MixedRealityPointerProfile. Notice that the settings have switched back to the previous state.
5. Open Scene1 again and inspect the MixedRealityPointerProfile again. Notice that the settings now again shows the changed settings that we set in step 2.

## Expected behavior

That the MixedRealityPointerProfile holds the 'Gaze Provider Settings' and applies them in all the scenes where the profile is used. Not the other way around, which is currently the case.

## Your setup

- Unity Version 2021.3.4f1
- MRTK Version 2.8.2

## Target platform

- HoloLens 2

## Additional context

A solution might be that the 'Gaze Provider Settings' are simply serialized on the MixedRealityPointerProfile objects and then not serialized (nor visible) on the GazeProvider component (on the camera) - to avoid double serialization of the same settings as well as confusion about where the setting is actually stored.

I know that MRTK 3 is coming out soon(ish) so maybe this is not the most important issue in the world :-)

**Comment by RogPodge** [comment]
Hey there, sorry for the late response.

Yeah, you're correct that this kind of goes against the rest of the profile architecture. This is a symptom of the gaze pointer/provider having a bit of a legacy "special" status from the old HoloToolkit days, and unfortunately isn't something we'll have time to rearchitect. For now, the best solution is to ensure that your camera (and by extension, your gaze provider) is synced between each scene you intend to use it. The changes introduced in 2.8 to show those settings on the profile were intended as more of a helpful QoL improvement, as a fully un-mucking the special status the gaze provider has had since the early days would introduce too many breaking changes.

**Comment by JakobAnarkyLabs** [comment]
That is totally understandable. We will manage with the current setup and then embrace MRTK 3 when it is ready.
