### ISSUE TITLE
An error occurred while resolving packages With MRFT

### ISSUE THREAD

**Issue by studyzx** [microsoft/MixedRealityToolkit-Unity#10791]
## Describe the bug

I created a new, empty, 3D Unity project and imported OpenXR and MRTK by the Mixed Reality Feature Tool. ( just like https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/new-openxr-project-with-mrtk)

But always fail to import. The error is:

An error occurred while resolving packages:
  Project has invalid dependencies:
    com.microsoft.mixedreality.openxr: zlib: unexpected end of file
    com.microsoft.mixedreality.toolkit.foundation: zlib: unexpected end of file
    com.microsoft.mixedreality.toolkit.standardassets: zlib: unexpected end of file

A re-import of the project may be required to fix the issue or a manual modification of E:/unityproject/Demo/Packages/manifest.json file.

## To reproduce

1. creat a new unity 3d project (2020.3.37f1c1)
2. switch UWP platform
3. open the MRFT(MixedRealityFeatureTool-1.0.2206.1-Preview) 
4. import MRTK 2.8.2 and openxr plugin, check the valid, and it works fine.
5. when I return to Unity, it does show the import package. (in Project\Packages\MixedReality, the .tgz is here alright)
6. then unity report the error, and project setting / XR plug-in still grayed out 

## Screenshots

![1658885635](https://user-images.githubusercontent.com/20589408/181141218-0fdc6b49-cf88-47b6-a044-f86fed7a35a2.jpg)

![image](https://user-images.githubusercontent.com/20589408/181141255-45acf0a9-ede0-4282-98bd-1908672e8282.png)

![image](https://user-images.githubusercontent.com/20589408/181141291-b8eb48bf-4bff-4567-b58a-feb3eaa35860.png)

## Your setup (please complete the following information)

- Unity Version [2020.3.37f1c1]
- MixedRealityFeatureTool-1.0.2206.1-Preview)

## Target platform (please complete the following information)

- HoloLens 2

Any help would be greatly appreciated!

**Comment by MaxWang-MS** [comment]
It seems that this is due to a networking issue. Could you share the log with us in case it has some useful information? The easiest way to access the log is to go to Settings > Diagnostics.
![image](https://user-images.githubusercontent.com/68253937/181645056-0e77b791-a667-4d69-b533-329b91d53c70.png)

You could also try enabling "Overwrite existing package files" under Settings > Download and then try again with a new project.

**Comment by studyzx** [comment]
@MaxWang-MS Thank you for your reply!

I have checked the Settings > Diagnostics， but there doesn't seem to be any error logs in the log file.
![image](https://user-images.githubusercontent.com/20589408/181913841-9a33c49c-b03b-4bfd-baf6-82369f17ca17.png)

**Comment by studyzx** [comment]
@MaxWang-MS  
Hi, Max, the method you mentioned "enabling "Overwrite existing package files" under Settings > Download and then try again with a new project."  worked~ no error and build success!
Thank you very much for your help!
