### ISSUE TITLE
Can pinch slider have customized range (minValue to maxValue)?

### ISSUE THREAD

**Issue by Yuchong-Geng** [microsoft/MixedRealityToolkit-Unity#10803]
Hi,

I have just started developing with MRTK and I am having trouble using the pitch slider. I want to have a slider that can take a range other than the default 0 to 1. But this seems to be hard to achieve. 

I have tried to change the `minValue` and `maxValue` fields in the script but it does not seem to be working. The slider still only has a range from 0 to 1. 

So I wonder if the pitch slider can take customized `minValue` and  `maxValue`, similar to the slider provided by Unity.

**Comment by Zee2** [comment]
@RogPodge , we've heard this from other folks. We may want to try and mirror the UGUI equivalents in overall API surface so that they are more like drop-in equivalents.

**Comment by RogPodge** [comment]
Should be done!
