### ISSUE TITLE
[MRTK3] Enable theming by default

### ISSUE THREAD

**Issue by LocalJoost** [microsoft/MixedRealityToolkit-Unity#10804]
## Describe the problem

Theming is disabled by default. I have to set MRTK_UX_DATABINDING_THEMING_ENABLED to _enable_ it. _Why_ would you ship a kit with a major feature in a disabled state? Possibly for performance reasons?  Even then, it would make more sense then to have in to enabled by default and have an option to _disable_ it. Like I can now opt for not loading some MRTK3 packages to speed up performance and/or compile time. It feels illogical.

**Comment by Zee2** [comment]
Hi @LocalJoost, it's to ensure the performance hit from the (extremely-early-preview) theming system is not by default. We've tried to follow "performance-by-default, features-by-request" in MRTK3. 

The theming system may see significant alterations/changes before GA, by the way. 

Also, we may not have done the best job PR-ing this; but the public preview is definitely not to be considered "shipped", at least not to the quality bar we try to uphold. So, take it all with a grain of salt, and we apologize for any inconveniences.

**Comment by Zee2** [comment]
Closing this as a "will be figured out before GA" thing :) Our goal is to have zero perf overhead for features that aren't desired; how we get to that endpoint is not 100% determined yet. Not to worry @LocalJoost , your concern is heard!
