### ISSUE TITLE
[MRTK3] VR system slows down after debugger attached

### ISSUE THREAD

**Issue by eusebiu** [microsoft/MixedRealityToolkit-Unity#10818]
## Describe the bug

After attaching the VS debugger on a MRTK3 project, the VR system slows down considerably. The only way to get back is to reboot the computer.

## To reproduce

1. Attach VS debugger on MRTK3 project
2. Stop at a breakpoint
3. Continue
4. Stop debugger
5. VR is stuttering

## Expected behavior

VR is not stuttering.

## Your setup

- Unity Version 2021.3.7f1 (LTS)
- MRTK3

## Target platform

- OpenXR + Oculus (Quest 1) Link (with both SteamVR or Oculus alone)

**Comment by Zee2** [comment]
Thanks for reporting this! Do you have any other VR device to repro with?

**Comment by eusebiu** [comment]
I noticed this happens on MRTK2 also if I leave it running for some time with the debugger attached and then I try to reattach. When this happens, it breaks down.
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎25-‎May-‎22
OS build	19042.1826
Experience	Windows Feature Experience Pack 120.2212.4180.0
NVIDIA Quadro RTX 5000 with Max-Q Design 16GB.

I have a feeling this started to happen after this Windows Update (as I did not do any VR lately).

**Comment by eusebiu** [comment]
I noticed that when this started to happen, I get this message in the Console:
Physics.ClosestPoint can only be used with a BoxCollider, SphereCollider, CapsuleCollider and a convex MeshCollider.
UnityEngine.Collider:ClosestPoint (UnityEngine.Vector3)
Microsoft.MixedReality.Toolkit.Input.ReticleMagnetism:Update () (at Library/PackageCache/com.microsoft.mrtk.input@cae224c3445a/Interactors/InteractorVisuals/ReticleMagnetism.cs:152)

I am not using ReticleMagnetism at all... or I am not aware of using it...

**Comment by eusebiu** [comment]
> Thanks for reporting this! Do you have any other VR device to repro with?

Only Oculus.

**Comment by eusebiu** [comment]
I think it is related to Oculus runtime... Their log is full of Frame dropped due to encoder backup...
