### ISSUE TITLE
Toggling Non-Canvas toggle switch off does not remove the color

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10815]
## Describe the bug

Toggling a non-canvas toggle switch from on to off does not fully toggle the switch, the color remains

## To reproduce

1. Launch UITearSheet Example (non-canvas)
2. Toggle non-canvas switches on, then off
3. See switch not change color, acting like its on if the user isn't looking carefully

## Expected behavior

When toggled off, the switch will not be empty with no color

## Video

https://user-images.githubusercontent.com/110259320/182422454-afece86a-8474-4f3a-8cc3-464764983afe.mp4

## Your setup

- Device HoloLens2
- Unity Version [2020.3.37f1]
- Commit Version acdecca31b97720a6fcda057cc35b3815ad56a02

## Target platform

- HoloLens 2
- Quest

**Comment by Zee2** [comment]
This is fixed by #10751!

**Comment by Zee2** [comment]
Fixed.
