### ISSUE TITLE
[MRTK3 pre.8 build call] Should be able to re-adjust where an example scene is located as a whole

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10813]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/283

___

## Describe the problem

Example scenes are places inside of PC monitors and other nearby objects, making them more difficult to interact. 

## Describe the solution you'd like

A single point of reference to re-adjust the position of example scenes, encompassing everything allowing movement around the user's environment

## Describe alternatives you've considered

Toggle to 'Reset' a scene based on the direction the user is facing

**Comment by Zee2** [comment]
This is already possible. You can grab the description panel and move the whole scene around!

**Comment by Clandguth** [comment]
I am not seeing this on the majority of the example scenes.
I am on Quest 2, commit 6a6b51b19ab81a90d9e9c4cb80452dfebf47d567

The following do NOT have the capability as you described @Zee2 

- Bounds Control
- Canvas Example
- Dialog Example
- Eye Gaze Example
- Interactable Button Example
- Object Bar Example
- Spatial Mapping Example
- Tab View Example
- Toggle Collection Example
- UI Backplate Example
- Virtualized Scroll Rect List

**Comment by Clandguth** [comment]
Continuing to see this on commit 609214a6a387fbbed16adadf6cf87c4c80e44159

**Comment by Zee2** [comment]
Some scenes intentionally don't do this (like the BoundsControl scene, where the description panel itself is a bounds example :D ) but yes some others should have it.
