### ISSUE TITLE
HandConstraintPalmUp has issues + glitches

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10811]
## Describe the bug

The SampleSceneHandMenu does not close completely when moving hands back to default position. Instead, the menu will rapidly rotate around the hand, and face away from the user. Once the user rotates the hand completely away, the menu will disappear

## To reproduce

1. Bring up SampleSceneHandMenu (Face palm towards the device in front of the screen)
2. **See issue** when you slowly rotate hand from palm facing the screen, back to default position

## Expected behavior

The menu will close completely once it recognizes that the user is attempting to close the menu

## Screenshots

Video Attached

## Your setup

- Device HoloLens2
- Unity Version [2020.3.37f1]
- Commit Version acdecca31b97720a6fcda057cc35b3815ad56a02

## Target platform

- HoloLens 2
- Quest

## Additional context

- Text says "Hello from Redmond" on the back of the menu

https://user-images.githubusercontent.com/110259320/182405837-27d5ffe4-300e-41af-be4b-97eaf2fe22d1.mp4

**Comment by Zee2** [comment]
As intended, this is a feature of HandConstraintPalmUp.

**Comment by Zee2** [comment]
Ah, wait, I just saw the weird backwards flipping behavior. Thought you were just talking about the fact that the hand menu follows the hand for a bit after putting the hand back down.
