### ISSUE TITLE
Dialog near/far broken; needs to be refactored to properly scalable Canvas dialogs

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10812]
## Describe the bug

In Dialogue Example Scene, it "demonstrates the use of the Dialog control...You can specify the title, description text, and the placement location - Near or far"

When the user selects the different interactions, all near, and far dialogue boxes were the same distance away from the user

## To reproduce

1. Launch Dialogue Example scene
2. Select any of the 3 'Near Interaction' choices - Remember how far away the box is
3. Select any of the 3 'Far Interaction' choices
4. Compare the distance.

## Expected behavior

'Near' and 'Far' dialogue box options change distance very clearly, I would expect the 'Far' to be interacted with Hand-rays instead of the hand-cursor.

## Screenshots

Video attached

## Your setup (please complete the following information)

- Device: HoloLens 2
- Commit Version acdecca31b97720a6fcda057cc35b3815ad56a02
- Unity Version [2020.3.37f1]

## Target platform (please complete the following information)

- HoloLens 2
- Quest

## Additional context

https://user-images.githubusercontent.com/110259320/182411115-d3a53657-78a0-43f2-89d1-78aee5e23f9a.mp4

**Comment by Zee2** [comment]
Known issue, as part of the Dialog "deprecation" of non-canvas. This will be resolved as the Dialog prefabs are fixed + refactored.

**Comment by Zee2** [comment]
Completed by #11113.
