### ISSUE TITLE
Quest requires special manifest entry to enable system keyboard, not documented

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10817]
## Describe the bug

Not able to enter either textbox in the example scene - Could be related to not having the motion controllers for Quest

## To reproduce

1. Launch Input Field Example scene
2. Observe not being able to interact with textboxes using hand-cursor

## Expected behavior

Can select and interact with textboxes with hand-cursors

## Your setup

- Device Quest
- Unity Version [2020.3.37f1]
- Commit Version acdecca31b97720a6fcda057cc35b3815ad56a02

## Target platform

- OpenVR

**Comment by Zee2** [comment]
Known issue! Special steps have to be taken to update the Android manifest file to enable the system keyboard.

@MaxWang-MS , we should get this documented and/or get a custom build processor step to apply this manifest change on build.

**Comment by MaxWang-MS** [comment]
After a discussion with @keveleigh we decided to not create a custom build processor for this and instead we are documenting this issue in MRTK3 docs.
