### ISSUE TITLE
Add scene title to SampleSceneHandMenu

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10810]
## Describe the problem

Unsure which app is which during testing, if an issue is found. The user must already know the scene, or be willing to dive back into Unity to figure app the issue was hit on in order to properly report it.

## Describe the solution you'd like

Print the Scene title on the hand menu of each scene

EX: Underneath the text "Navigate Sample Scenes"

## Describe alternatives you've considered

Create a new window solely for the purpose of displaying the scene name and basic info

**Comment by Clandguth** [comment]
Going farther into a test pass, its obvious this is handled mostly throughout the Scenes.

This issue affects the CanvasExample scene. Will add additional comments if the issue is encountered on other scenes

**Comment by Zee2** [comment]
I've been thinking about doing this! Will add it soon.
