### ISSUE TITLE
Unable to deselect feature packages in MR Feature Tools

### ISSUE THREAD

**Issue by abhilashca** [microsoft/MixedRealityToolkit-Unity#10827]
## Describe the bug

The current version of MR Feature Tools allows you to add feature packages in Unity Project. However, there is no option to uncheck a feature package to remove any feature packages that are already installed.

## To reproduce

1. Launch MR Feature Tool
2. Add few features packages through MR Feature Tools to a sample Unity3d project
3. Close MR Feature Tool
4. Launch MR Feature Tool again and browse to previously selected Unity3d project
5. You can see previously installed feature packages
6. There is no mechanism to uninstall previously installed feature

## Expected behavior

There should be an option to deselect feature packages and apply the changes, so that unselected feature packages are removed.

## Your setup

- Unity Version [2019.4.14f1]
- MRTK Version [v2.6.0]

## Target platform (please complete the following information)

- Oculus Quest

**Comment by abhilashca** [comment]
Here is what I have done now
- removed unwanted packages from `manifest.json`
- deleted `Library` folder since I was getting error from `Artifacts` folder

**Comment by MaxWang-MS** [comment]
You can remove packages using [Unity's package manager](https://docs.unity3d.com/Manual/upm-ui.html).

**Comment by MaxWang-MS** [comment]
Do you have some thoughts on this @davidkline-ms?

**Comment by abhilashca** [comment]
@MaxWang-MS Yeh, I didn't thought I could remove that from Unity Package Manager. I was thinking since MR Feature Tool helped install the packages, I could do removal from MR Feature Tool itself.

Thanks for the help.

**Comment by Zee2** [comment]
Closing for now.
