### ISSUE TITLE
MixedRealityBuildProcessor assumes project name during editor builds

### ISSUE THREAD

**Issue by ShocksPegsLucky** [microsoft/MixedRealityToolkit-Unity#10820]
## Overview

A post process exception is thrown after programmatically compiling a project with a custom output path.

CheckRemotingJson function inside MixedRealityBuildProcessor.cs assumes that a project being build through the editor will have its data folder prepended with the product name declared in the Unity editor settings. However, when a special output path is passed as an argument to the UnityEditor.BuildPlayer API, the data folder is prefixed with the name of the executable instead. This alone would not be an issue, but the code in CheckRemotingJson does not check for file existence before attempting to delete it.

## Expected behavior

Build post processors are run without incident.

## Actual behavior

The following exception is thrown after the player is built:

`DirectoryNotFoundException: Could not find a part of the path 'E:\BuildAgent\work\ff228974cb5c14fa\Output\Crane Simulation_Data\Plugins\x86_64\RemotingXR.json'.
at System.IO.FileSystem.DeleteFile (System.String fullPath) [0x0001a] in <00c558282d074245ab3496e2d108079b>:0`

## Steps to reproduce

Programmatically compile a project while specifying an output path where the executable name is not the same as the value of PlayerSettings.ProductName.

## Unity editor version

Unity 2021.2.4f1

## Mixed Reality Toolkit release version

2.7.3.0

**Comment by keveleigh** [comment]
Interesting! I'll look into this. We specifically use https://docs.unity3d.com/ScriptReference/Build.Reporting.BuildSummary-outputPath.html as the base path, which should match whatever you pass into the BuildPlayer API, so we may be able to parse out what this folder _should_ be based on that value.

Thanks for the report!

**Comment by ShocksPegsLucky** [comment]
I have been able to work around this issue by making sure I clear the output folder before building. My guess is that there is an earlier check somewhere that will prevent the CheckRemotingJson function from running if the output folder is not present?
