### ISSUE TITLE
Is it possible to define gestures for the MRTKSimulatedController with controller input

### ISSUE THREAD

**Issue by mmaurer42612** [microsoft/MixedRealityToolkit-Unity#10826]
I tried to change the gestures for controller input using the OpenXR Hands API, because i wanted the thumb to not be streched out in the resting pose.  I guess this happens somewhere in the SimulatedController.cs, but i find it hard to define different positions for the simulated hand. 

Is there a simple way to define positions of joints or full gestures according to Controller Input?

**Comment by Zee2** [comment]
@keveleigh , when we re-record our simulated poses, we should probably include an API for folks to upload their own.

**Comment by Zee2** [comment]
Also, @mmaurer42612 it is up to the platform to provide conformant hand joints when controllers are being used. @keveleigh is working on some improvements to the OpenXR plugin to allow folks to request conformant joints from the platform.

**Comment by Zee2** [comment]
Closing, expecting this to be resolved both by #10836 as well as the upcoming OpenXR release with conformal controller hand joints.
