### ISSUE TITLE
No cursor shows up when hovering over unity's default canvas elements

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#10839]
## Describe the bug

No cursor shows up over selectable unity UI canvas elements

## To reproduce

1. Open the MRTK HandInteractionExampleScene
2. Follow these steps to create selectable canvas UI: https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@2.0/manual/ui-setup.html
3. Notice that no cursor shows up over these UI elements

## Expected behavior

Unity UI elements should behave the same as MRTK UI elements.

**Comment by Zee2** [comment]
Resolved.
