### ISSUE TITLE
Mouse can interact with MRTK UI elements while hands are present in the scene.

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#10837]
## Describe the bug
When using input simulation, the mouse can accidentally interact with UI elements while the simulated hands are on the screen. 

## To reproduce

1. Open the MRTK HandInteractionExamples scene
2. Start the scene
3. Bring up the simulated hand
4. Try interacting with the scene using the mouse pointer.

## Expected behavior

The mouse pointer should be disabled from interacting with elements in the scene when hands are present.

## Your setup (please complete the following information)

- Unity Version 2020.3.36f1
- MRTK Version: 3.0.0-latest

**Comment by keveleigh** [comment]
Fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10838
