### ISSUE TITLE
Start placement of MixedRealityCameraParent is floating??

### ISSUE THREAD

**Issue by DDReaper** [Microsoft/MixedRealityToolkit-Unity#1084]
Seen this on / off in the project through the various merges / updates.  However, it's currently stuck in the project.

Replication Steps:
* Create afresh clone of the Repo to a new folder (just to ensure nothing is mixed up)
* Start Unity on new folder (testing with 2017.2.0f2 & 2017.2.0f2-MRTK dev
* Open a Scene (InputManagerTests is a good one)
* START MR Portal (we wouldn't want Unity to Crash now would we :D)
* Enable Simulator (just for convenience, a headset produces the same result)
* Hit Play

Expected: (captured from Unity as an approximate)
![image](https://user-images.githubusercontent.com/1793042/31236574-5f20dbc0-a9ec-11e7-812f-1a0fbbfc8f86.png)

Actual: (captured from MR Portal)
![image](https://user-images.githubusercontent.com/1793042/31236523-35dbc54a-a9ec-11e7-9dce-cdf2cf7cce19.png)

As you can see, the start position is elevated A LOT

Result is the same either it is run from Unity or from a Built project in Debug, Master or Release.

**Comment by StephenHodgson** [comment]
I don't think many of the test scenes have been updated to work properly with the new camera prefab.

**Comment by keveleigh** [comment]
This is to do with the way Unity's coordinate system works in MR now.

There are currently two types of space types in Unity: Stationary and RoomScale. Stationary places (0,0,0) at the starting point of your head, like we're used to with HoloLens. RoomScale places (0,0,0) on the floor, directly below where you "centered" your space during set-up of the mixed reality portal (when you held the HMD up and pressed the "center" button during OOBE).

All of our samples have their starting location placed as though (0,0,0) will be the starting point of the user's head, but that isn't always true anymore.

**Comment by DDReaper** [comment]
So the answer is to position the camera "up" so it's head height (about 0.8f in my previous experiments).
I'll test but unsure.

Although, does this present a problem based on the "Mode" the Kit is in, since it's possible to switch between them? DO we need additional code to determine the starting position and position accordingly  @keveleigh ?

**Comment by StephenHodgson** [comment]
I think Unity is getting the "floor" offset info from the windows spatial APIs, correct?

**Comment by DDReaper** [comment]
Also tested with / without the boundary, in seated or "Full Experience" mode.  Has no effect.  SO the setting must be per device maybe? If these scenes work fine with HL

**Comment by DDReaper** [comment]
OK, so as an additional test, I also cleared the "Environment" data (e.g. boundary and floor detection) and this cause the following result:
![image](https://user-images.githubusercontent.com/1793042/31279076-8a55a8d0-aa9f-11e7-95e4-3e5705090386.png)

So we can't just take what Unity gives us at face value.  To me, it looks like it has repositioned the world at the floor, which causes half the scene to be clipped? Very odd.
