### ISSUE TITLE
Quest 2 hand-ray does not move when drawing in the SlateDrawingExample

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10846]
## Describe the bug

When the user starts to draw with the hand ray, the cursor is locked where they initially select, while drawing continues as expected

## To reproduce

1. In the Slate Drawing Example
2. Start drawing with the hand-ray
3. See issue, where cursor is locked in place, while drawing continues as expected

## Expected behavior

User may use hand-rays to start drawing, And the cursor will move along with the user, or maybe disappear entirely

## Video

https://user-images.githubusercontent.com/110259320/183743172-10d58d89-0262-4089-9947-d5268c6b912a.mp4

## Your setup

- Unity Version 2020.1.37f1
- MRTK Version 3.0
- Commit Version 6a6b51b19ab81a90d9e9c4cb80452dfebf47d567

## Target platform (please complete the following information)

- Quest 2

## Additional context

Hand-Rays cannot select the pen/pencil, must grab with the hand cursor

**Comment by Zee2** [comment]
Known issue, being addressed in #10751
