### ISSUE TITLE
MRTK3: Vive Focus 3 Support. 

### ISSUE THREAD

**Issue by DeakWebster** [microsoft/MixedRealityToolkit-Unity#10849]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/280

___

Problem: Vive Focus 3 MRTK3 Support
Vive Focus 3 is currently a higher requested VR headset for enterprise customers than Quest 2. Especially in the government, mil sim, and NASA. It is Open XR compatible and also works with hand tracking and controllers that are actually extremely similar to Quest 2. It also works now with Unity's XR Interaction Toolkit. The current sdk that is used is the Vive Wave sdk, and it's extremely barren when it comes to features, and also is extremely unpolished. I think MRTK3 would provide a much better headstart. Even with Unity's XR Interaction toolkit the feature set is still relatively barren with Focus 3 compared to MRTK.

Solution:
Focus 3 supports Open XR, works with XR Interaction Toolkit in Unity, and also works with both hand tracking and controllers. I would like to see a lot of MRTK3 work with this headset. Quest 2 is awesome, but most our government customers don't want it. Less and less customers in NASA, DoD, and Law Enforcement are going towards Quest 2 due to METAs reputation debt, and the association of facebook accounts with users (I understand that is going away but government customers won't care). Focus 3, is pretty much the enterprise, and government alternative to a Quest 2 currently for now.

- Make MRTK3 work with Focus 3 by taking advantage of the Focus 3's compatibility with Open XR, and Unity's XR Interaction Toolkit. 
- Ideally both controllers and hand tracking should work with it since the Focus 3 is capable of both. 
- If both aren't possible having it compatible with just the controllers will still suffice. 

**Additional context**
- There is support for wrist trackers in the works that will further improve the accuracy of hand tracking, but it will be optional. 
- It's possible that Open XR may still be in public beta, however the repos are still available. It's had some time to iron things out. Regardless of this I think it's in a state where an attempt to make MRTK3 compatible is possible. 
- Link to the documentation for set up: https://forum.htc.com/topic/12959-tutorial-focus3-openxr-open-beta-getting-started-in-unity/
 Link to a Github repo: 
- 2020 Unity https://github.com/hardcoded2/HelloVR/suites/6113995207/artifacts/212516274 
- 2021 Unity https://github.com/hardcoded2/HelloVR/suites/6113995207/artifacts/212516275

**Comment by Zee2** [comment]
Hi @DeakWebster! We'd love to see MRTK3 on the Vive Focus 3.

Taking a brief look at the documentation, I'm not immediately seeing a reason why MRTK3 _**wouldn't**_ work out of the box on the Vive Focus 3. We've seen MRTK3 to work surprisingly well on random un-tested devices that we've never personally used; Snapdragon Spaces is a great example.

The team here doesn't have any VF3s on hand, but we'd love to see a community member try it out and report back to us what the situation looks like. From what we can see, it "should" just work! But we'd be very happy and interested in making sure MRTK3 works well on the VF3.

**Comment by DeakWebster** [comment]
Are there any documented cases of it working successfully on previous Vive Headsets like the Vive PRO 2? We can certainly let the MRTK dev team know if it works in the coming months, and if it doesn't submit, we can a bug report/feature request once we have more information to give your MRTK team?

**Comment by Zee2** [comment]
Sounds like you're in the right place, because MRTK3's goal is to provide that cross-platform UI on any OpenXR device!

With OpenXR, it's highly likely that any OpenXR-compliant device will work with MRTK3. That's kind of the point 😋 The team here in Redmond is extremely small, and we don't have all of these devices to test with, unfortunately. We rely on the community to give it a try on new devices and let us know if there are compatibility issues!

I personally have an original 2016-era Vive. @maluoi might have a Vive Pro or something? I don't recall. MRTK3 should definitely work on PCVR headsets like the Vive if they're running on an OpenXR-compatible runtime like SteamVR!

**Comment by Zee2** [comment]
@DeakWebster, happy to announce that Vive Focus 3 works suprisingly well, all things considered.

The only thing that isn't working right now is hand pinching and rays. Controllers work great, and hand tracking works too, it's just without the pinch + ray actions.

I followed https://developer.vive.com/resources/openxr/openxr-mobile/tutorials/unity/getting-started-openxr-mobile/, and seemed to work well (other than the above issues). We're working on sorting those out!

**Comment by mr0ng** [comment]
Following :)

**Comment by jasonodomtaqtile** [comment]
> Following :)

ditto
