### ISSUE TITLE
Quest 2 HandConstraintPalmUp has issues throughout all example scenes

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10848]
## Describe the bug

HandConstraintPalmUp is not opening consistently

## To reproduce

1. Attempt to open the HandConstraintPalmUp, by facing your palm towards the Quest 2 headset
2. Observe the menu can open up, but the user may have to perform the action multiple times before the device recognizes the action.

## Expected behavior

HandConstraintPalmUp appears smoothly when facing the users palm to the screen

## Video

https://user-images.githubusercontent.com/110259320/183748907-c619a907-b721-410f-ae45-f1b818b72546.mp4

## Your setup (please complete the following information)

- Unity Version 2020.3.37f1
- MRTK Version 3.0
- Commit Version 6a6b51b19ab81a90d9e9c4cb80452dfebf47d567

## Target platform (please complete the following information)

- Quest 2

## Additional context

Appears in all examples

**Comment by Zee2** [comment]
Same issue as #10811 .

**Comment by Zee2** [comment]
This is because of the overly aggressive "must-look-at-menu" part of the constraint. Will be fixed in a hand menu overhaul I'm working on.
