### ISSUE TITLE
CanvasExample, Bounds description panel missing Min/Max scale constraints

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10865]
## Describe the bug

Canvas example main window is missing Min/Max scale constraints

## To reproduce

1. Select main window in the center of the scene
2. Select the side to enable Bounds controls
3. See Issue, missing Min/Max scale constraints

## Expected behavior

A window has a minimum and maximum value

## Video

https://user-images.githubusercontent.com/110259320/184193824-42d92eb6-17fc-4262-824c-cf51715a632e.mp4

## Your setup

- Unity Version 2020.3.37f1
- MRTK Version 3.0
- Commit Version 9a14d8ad28e9861d4b4077ae02168177fc9d90b1

## Target platform

- HoloLens 2

**Comment by keveleigh** [comment]
Closed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10868
