### ISSUE TITLE
Near menu pinning is uncomfortably low

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10866]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/278

___

## Describe the bug

- When a window is pinned to follow you, it will fall below vision, and lowering the headset to look down at the window makes them move even further down in vision.

## To reproduce

1. Launch NearMenuExample scene
2. Pin multiple windows to follow the user
3. Observe, the windows fall below vision level

## Expected behavior

- The user can move the window pinned to the user in vision, and it will follow the user at a comfortable angle and distance

## Video in MRTK3

https://user-images.githubusercontent.com/110259320/184195193-a1b2396f-b793-403c-a089-644932b171d7.mp4

## Video in Default HL2 OS -- closer to what I would expect

https://user-images.githubusercontent.com/110259320/184195686-1c0579e1-2ecf-4667-b177-38dbab0e509d.mp4

## Your setup

- Unity Version 2020.3.37f1
- MRTK Version 3.0
- Commit Version 9a14d8ad28e9861d4b4077ae02168177fc9d90b1

## Target platform

- HoloLens 2

**Comment by Zee2** [comment]
Multiple pinned menus fighting is a won't-fix-for-now, this is a significant feature investment (docking/placement API).
