### ISSUE TITLE
Hand Interaction Example: Gravity issues with new Manipulation Interaction objects

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10883]
## Describe the bug

2 separate issues with gravity on the manipulation objects.

1. Coffee Mug has no applied gravity, will float forever in a direction
2. Tri-pod object is moved when touched by the open space around an object (See 2nd video)

## To reproduce

1. In Hand Interaction Example scene
2. Grab and move the Coffee mug, slowly push it into the tri-pod and observe the tri-pod moves without being touched by the object
3. Release the coffee mug, and observe no gravity

## Expected behavior

The Manipulation Interaction objects all have gravity, and will not move unless acted upon by an outside force

## Video 1

https://user-images.githubusercontent.com/110259320/185195349-22eeec5c-d5d6-4b40-90f4-3e3f2aaf4787.mp4

## Video 2

https://user-images.githubusercontent.com/110259320/185195337-7af162b9-6b97-492d-94d2-5a6cfc0f21be.mp4

## Your setup (please complete the following information)

- Unity Version 2020.1.37f1
- Commit Version 064f7cf9dd7eaa6addf29b3ed2706ed683fe7fe2

## Target platform (please complete the following information)

- HoloLens 2

**Comment by Zee2** [comment]
Yup, known issue... been around since forever ago. Thanks for logging it.
