### ISSUE TITLE
HL2 AirTap allows the user to select an interactable when not hovered

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10885]
## Describe the bug

User can select an interactable on all sides of the object, outside of the expected bounds

## To reproduce

1. Open any interactable example scene
2. Select around interactable objects
3. Observe the objects are selected and the state of what they interact with is changed

## Expected behavior

User can only select an object when hovering over it directly

## Videos

https://user-images.githubusercontent.com/110259320/185197855-7f425a6b-438f-4278-98b2-b540710e38e7.mp4

https://user-images.githubusercontent.com/110259320/185197887-b4f78154-c33c-4a3a-80f3-d449bd04d24b.mp4

## Your setup (please complete the following information)

- Unity Version 2020.3.37f1
- Commit Version 064f7cf9dd7eaa6addf29b3ed2706ed683fe7fe2

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
Looks like this _could_ be the gaze+pinch interactor, keying off your eye gaze. I wonder if we need more feedback when this happens, like the hand rays disappearing or something while a gaze+pinch interaction is in progress.

**Comment by Zee2** [comment]
That's the gaze pinch manipulation, yep. Hand rays and gazepinch being on simultaneously isn't recommended for developers (at some point we'll enforce this)
