### ISSUE TITLE
[pre.10 block] Interaction Mode Manager doesn't switch modes correctly

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10882]
## Describe the bug

When a user moves closer to an object with their hands, the HL2 does not auto detect the distance to the object and does not switch 
 the selector to the hand-cursor, meaning the user cannot interact up close

## To reproduce

1. Interact with hand-rays at a distance
2. Attempt to get closer, and see issue, unable to use hand-cursor to interact or select holograms

## Expected behavior

When a user moves their hand closer to a hologram, the system should automatically switch to the hand-cursor

## Video

https://user-images.githubusercontent.com/110259320/185193851-a586e407-20ec-4bac-b8dd-6e0e253d1f34.mp4

## Your setup 

- Unity Version 2020.3.37f1
- Commit Version 064f7cf9dd7eaa6addf29b3ed2706ed683fe7fe2

## Target platform (please complete the following information)

- HoloLens 2

## Additional Info and video

When interacting with bounds control on a coffee mug, the hand-ray is still visible

https://user-images.githubusercontent.com/110259320/185193466-93a26dae-fbc2-4fc0-9838-200934c56af1.mp4

**Comment by Zee2** [comment]
@RogPodge , looks like something on the IMM broke.

**Comment by keveleigh** [comment]
Not sure if this is related, but I'm seeing a lot of null ref spam on an HL2: 
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/3580640/185217371-bba08bfb-eff5-407c-94c2-4a5f74273725.png">

**Comment by Clandguth** [comment]
Roger thinks he has a solution after looking in person with me. We set up a basic logger and found there was another element not supposed to be in there. Had a test branch in the works for me to test out soon

![image](https://user-images.githubusercontent.com/110259320/185242779-f2e854de-2691-4e69-b938-d1ef9439b7a7.png)

**Comment by RogPodge** [comment]
Closed by #10890
