### ISSUE TITLE
If no XR Plugin Provider is checked, Input System spams errors and nothing works

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#10880]
## Describe the bug

If no XR Plugin provider is checked in the XR settings, the input system starts spamming IndexOutOfRange errors. Not even input simulation works.

## To reproduce

1. Make a new MRTK3 project
2. Don't check any of the plugin providers

<img width="263" alt="image" src="https://user-images.githubusercontent.com/5544935/185026122-742cd5b8-ce3c-41c6-a645-6a41405559fd.png">

3. Make sure you have the input simulator in your scene
4. Observe errors

<img width="479" alt="image" src="https://user-images.githubusercontent.com/5544935/185026162-bf4c8d3f-82ac-40ad-92dd-f49f5c64293c.png">

## Expected behavior

Input simulation should work without XR providers enabled; after all, it makes its own synthetic devices, so....

## Your setup (please complete the following information)

- MRTK3 pre.9

**Comment by Zee2** [comment]
@keveleigh, I'm assigning you on this one because I feel like you'd know what is up with this...

**Comment by keveleigh** [comment]
Yeah, I've seen this one a few times too...it also repros when you uncheck `Initialize XR on Startup`. It seems to be related to the eye tracking `PoseControl` fun workaround stuff we had to do, possibly, but I haven't dug any deeper than that yet.

**Comment by keveleigh** [comment]
Fixed via #10946
