### ISSUE TITLE
Select speech command is not getting Recognized in MRTK 2.8.2

### ISSUE THREAD

**Issue by hemasree99s** [microsoft/MixedRealityToolkit-Unity#10881]
## Describe the bug

Select speech command is not getting recognized in MRTK 2.8.2

## Expected behavior

Select speech command should get recognized 

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.3.20f1]
- MRTK Version [e.g. v2.8.2]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by hemasree99s** [comment]
@keveleigh Any Update on this?

**Comment by keveleigh** [comment]
@hemasree99s Are you using Windows XR Plugin or OpenXR?

**Comment by hemasree99s** [comment]
@keveleigh , currently using OpenXR
