### ISSUE TITLE
Using the Dialog control with the Canvas Dialog prefab from the UX components throws an exception

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#10888]
## Describe the bug

Using the Standard 3D dialog is fine and works as expected.  However, when trying to use the CanvasDialog prefab in the UX controls,  opening the dialog causes a "Index Error" exception, likely to the scripts not being able to detect the buttons on the prefab.

* The Dialog examples do not include an example for using the CanvasDialog prefab - and
* The Canvas examples do not include an example using the CanvasDialog prefab

So consumers are a bit of a loss trying to use the Dialog control in Canvas mode.

## To reproduce

1. Create a script to instantiate the Dialog control
2. Assign the CanvasDialog prefab to the "Dialog.InstantiateFromPrefab" call
3. Open the dialog

## Expected behavior

A working dialog control using the Canvas (regular dialog control does not work if you are not using the MRTK rig, e.g. desktop mode)

## Your setup (please complete the following information)

- Unity Version - 2020.3.37
- MRTK Version V3

## Target platform (please complete the following information)

- UWP desktop

**Comment by SimonDarksideJ** [comment]
Always the way, found the issue 30 seconds after raising the bug and the FIX is very simple.

The issue is because the container in the prefab that holds the buttons is NOT called "ButtonParent" and the script has this GO name HARDCODED in to the function to get the buttons for the dialog.

There is an ancillary issue that the instantiated canvas is NOT attached to a Canvas, and is just placed in the scene.  Which "works" but is unreadable as it's too small

**Comment by Zee2** [comment]
Yup, the dialogs are quite borked right now. #10812 is tracking some other things involving Dialogs being borked. (The fact they throw warnings is also a good sign they're still not done :D )

**Comment by Zee2** [comment]
> the script has this GO name HARDCODED in to the function to get the buttons for the dialog.

Yeah, this is one of the things I'll be nuking from Dialog.

**Comment by SimonDarksideJ** [comment]
Happy to help out to make it a better system :D 

It does feel a "little" overengineered and may benefit from a fresh implementation, leaving the old one in the dust.

**Comment by Zee2** [comment]
That's what I'm feeling too. I'll make sure to tag you on the PR.

**Comment by Zee2** [comment]
@SimonDarksideJ , take a peek at #11113 !

**Comment by Zee2** [comment]
Completed by #11113.
