### ISSUE TITLE
UI Tear Sheet Dialog examples have an additional PressableButton spanning the width as the expected two buttons

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10893]
## Describe the bug

UI Tear Sheet Dialog examples have additional 'none' text between buttons

## To reproduce

1. Launch UI Tear Sheet, see issue on Dialog examples

## Expected behavior

2 buttons in dialog box

## Screenshots
![Capture](https://user-images.githubusercontent.com/110259320/185502493-9464ef6c-7307-4644-84e6-933513791740.PNG)

![20220818_143135_HoloLens](https://user-images.githubusercontent.com/110259320/185499575-b947e248-2d31-4ccd-bcf5-6d357c0db65c.jpg)

## Your setup (please complete the following information)

- Unity Version 2020.3.37f1
- Commit Version 7244dc4455

## Target platform (please complete the following information)

- HoloLens 2

**Comment by Clandguth** [comment]
Under further investigation, the issue is an additional button, not text between the two intended buttons

**Comment by Zee2** [comment]
Known issue, wontfix, it's part of how Dialogs configure their buttons at runtime and will probably be nuked as part of an upcoming Dialog refactor.
