### ISSUE TITLE
Colored cubes in Hand Interaction Example cannot move other objects, but can be moved by other objects

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10894]
## Describe the bug

All the objects on the table should be able to interact with each other with simulated gravity

- Cubes fall if dropped, and can interact with each other
- Cubes move if pushed by the mug or TriPod
- Mug and TriPod do not move if pushed by the colored blocks

## To reproduce

1. Open Hand Interaction Example Scene
2. Grab a cube, they fall if dropped, and can interact with other colored blocks
3. Grab a Mug or the TriPod Object, Cubes move if pushed by either
4. Mug and TriPod do not move if pushed by the colored blocks

## Expected behavior

All objects interact with each other in the same way.

## Video

https://user-images.githubusercontent.com/110259320/185500709-07e833ee-2a66-483f-8530-90b6de82c30f.mp4

## Your setup

- Unity Version 2020.3.37f1
- Commit Version7244dc4455

## Target platform

- HoloLens 2

**Comment by Clandguth** [comment]
Seems like this could be intended, based on the mass of the different objects.

**Comment by keveleigh** [comment]
@cre8ivepark was this behavior intentional?

**Comment by cre8ivepark** [comment]
> @cre8ivepark was this behavior intentional?

I believe this will be fixed by Finn's #10908
