### ISSUE TITLE
Request: Speech example scene - working

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#10927]
## Describe the issue
In reviewing the documentation for speech commands, I found inconsistencies and questions about how to implement Speech commands.  And in testing I was unable to "get it working". (using [this document](https://docs.microsoft.com/en-gb/windows/mixed-reality/mrtk-unity/mrtk3-core/packages/core/subsystems/phraserecognitionsubsystem#setup))

None of the current Example scenes as part of the MRTK3 have speech commands configured as far as I can tell.
As well as Zappys Playground, speech does not seem implemented.

If there is a scene configured that I just cannot find, great.  But this area needs more documentation / support

## Feature area
What's incorrect? What's missing?
No proper Speech docs or examples

## Existing doc link

- https://docs.microsoft.com/en-gb/windows/mixed-reality/mrtk-unity/mrtk3-core/packages/core/subsystems/phraserecognitionsubsystem#setup

**Comment by Zee2** [comment]
Assigning @MaxWang-MS here. We've heard conflicting reports about the Speech docs... some other folks got it working just fine, so we'd love to dig in on where our speech documentation isn't working well!

**Comment by MaxWang-MS** [comment]
Hi @SimonDarksideJ, we just fixed an issue preventing the "select" keyword from being recognized on HoloLens 2 recently. The necessary changes on the MRTK3 side were made in pre.9, but the fix also relies on changes introduced into Mixed Reality OpenXR plugin 1.5, which is going live soon. The sample scenes (e.g. the HandInteractionExamples scene) contain buttons with "select" configured as the default keyword, and that's likely the reason why you were not able to get speech working. Please try again with Mixed Reality OpenXR plugin 1.5 and the latest MRTK3 release once the former is live.

**Comment by SimonDarksideJ** [comment]
Thanks for the update @MaxWang-MS , can you also confirm that the update also takes into account when a different word/command is configured for the PressableButton control?  As not all buttons have the word "Select" on then :D

**Comment by MaxWang-MS** [comment]
No, the update should not change the behavior of the recognition of "non-select" keywords. In those cases, things should be working already. The Mixed Reality OpenXR plugin is 1.5 publicly available right now, so please update your project to that version/clone the current MRTK3 branch, follow the instructions you linked above and things should work fine in the HandInteractionExamples scene (assuming you enabled the eye gaze permission, if you look at the buttons in the middle of the scene and say select, the buttons should be triggered).

**Comment by MaxWang-MS** [comment]
As mentioned above the issue should have been fixed. Please reopen the issue if you are still running into problems with the latest version of MRTK3 and MR OpenXR plugin.
