### ISSUE TITLE
MRFT prompts to install .NET in order to run; button does nothing

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#10921]
## Describe the bug

When doing a clean download + install of MRFT, it prompts to download .NET. Clicking "yes" does nothing.

## To reproduce

1.Fresh download of MRFT
2. See prompt for .NET download
3. Click yes
4. Nothing happens

## Expected behavior

Redirect to .NET download site, probably?

## Screenshots

![image](https://user-images.githubusercontent.com/5544935/186062139-f37423f2-ba96-49a5-8025-cfe7d7ae12e8.png)

**Comment by davidkline-ms** [comment]
We are in the process of updating the Mixed Reality Feature Tool to .NET 6. At the same time, we are planning on releasing a single-binary version which will contain the .NET runtime as well as the assorted DLLs that comprise the tool. We are doing some testing on this new configuration and will advise once it is available.

**Comment by MaxWang-MS** [comment]
This issue will be resolved by the new version of MRFT we are shipping very soon.
