### ISSUE TITLE
Example scenes migration from v2

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#10926]

**Comment by cre8ivepark** [comment]
Opened PR #10966

**Comment by AMollis** [comment]
@marlenaklein-msft  Can you catalog the MRTK2 scenes that need to migrated to MRTK3

**Comment by AMollis** [comment]
Possible related PR #10966

**Comment by AMollis** [comment]
Tracking with smaller issues

## Learning Paths (P1)
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11440

## Add MRTK2 Example Scenes to MRTK3 (P2)
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11484
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11486
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11488
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11491

## Add MRTK2 Example Scenes to MRTK3 (P3)
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11485
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11487
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11490
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11492
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11499
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11502
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11510
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11511
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11512
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11513
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11515

## Add MRTK2 Example Scenes to MRTK3 (P4)
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11493
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11500
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11501
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11503
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11504
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11505
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11505

**Comment by ragavendranbalaCES** [comment]
Cloned the MRTK DevTemplate unity project. LineExamples Scene is not available.
