### ISSUE TITLE
Regression; OpenXR plugin update causes errorspam when no XR device connected

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#10938]
## Describe the bug

Errorspam when no XR device is connected.

<img width="673" alt="image" src="https://user-images.githubusercontent.com/5544935/186517988-fafd860d-5ca5-425e-ace4-0efaa3692832.png">

Regression, most probably caused by OpenXR Plugin 1.5.1 update.

**Comment by MaxWang-MS** [comment]
This is confirmed to be a regression in Unity's OpenXR plugin 1.5.x.

**Comment by Zee2** [comment]
Should be fixed by 1.6.0 Unity OpenXR plugin release.
