### ISSUE TITLE
Cannot Teleport inside a 'Trigger'

### ISSUE THREAD

**Issue by amrittb** [Microsoft/MixedRealityToolkit-Unity#1094]
When using 'MixedRealityCameraParent' and using teleport, I cannot teleport inside a Trigger.

**Comment by CrazyTegger** [comment]
Is there any documentation on what teleporting is? I haven't heard that term used before.

**Comment by StephenHodgson** [comment]
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Unity_2017.2.0/README.md

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
