### ISSUE TITLE
Port Build Window to MRTK3 (or generally split out)

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#10947]
https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/mrtk2/features/tools/build-window?view=mrtkunity-2022-05

**Comment by Zee2** [comment]
Could you explain the need/requests for this? I've never personally used it and I've always been sort of confused by why it exists. Is it basically just a GUI wrapper for calling VS build actions to generate an appx vs needing to open VS yourself?

**Comment by keveleigh** [comment]
It's basically meant to be a one-stop-shop for building a Unity project, building the appx (if UWP), and deploying it on-device all in one go (or in steps, if you prefer, but all without leaving the context of the Unity editor).
It also has additional convenience features, like the ability to manage multiple versions of the same app on your machine and selectively deploy specific versions.

I've gone through phases of using it or not, but from conversations with community members over the years, I'm always surprised by how many people have used it. It might be the most used dev feature in MRTK2 😅

**Comment by pajama** [comment]
to be able to build unity, then an appx x, then distribute with one click of a button is so important when iterating on builds while multitasking. It saves you from babysitting the sometimes awfully long build times in unity before rushing over to vs.

**Comment by AMollis** [comment]
We won't be doing this work.  Unity's build window provides much of the functionality needed to build and deploy to the HoloLens.
