### ISSUE TITLE
Automated performance validation test on device

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#10959]
To monitor the performance changes within MRTK3, it would be super useful to have a scene with associated scripts to perform some common operations on devices and give us performance numbers when the operations are done (e.g. 95 percentile fps, etc.) This way we can better understand how we are doing on perf and also catch performance regressions.

**Comment by AMollis** [comment]
We have a different work stream looking at ways to monitor performance, separate from MRTK work.  However the goal is that we would monitor performance across Unity versions, OS versions, MRTK versions, OpenXR Runtime versions, and OpenXR MR Plugin versions
