### ISSUE TITLE
Swaped profile isn't included in build

### ISSUE THREAD

**Issue by bacnar** [microsoft/MixedRealityToolkit-Unity#10951]
## Describe the bug

The scene is saved with none of the profiles selected. After changing anything and Unity is reloaded we check what platform we are using and then set the correct profile for it. Now the problem is that setting MixedRealityToolkit.ActiveProfile to correct one, doesn't work. It does work in the editor but doesn't on Android or Hololens(UWP).

## To reproduce

1. Open included a project
2. Build for Android or UWP
3. Start the app on a device
4. App doesn't set text because the profile is null (should also be visible with the attached debugger)

## Expected behavior

A proper profile should be selected as in the editor.

## Your setup (please complete the following information)

- Unity Version: 2021.3.4f1
- MRTK Version: 2.8.2

## Target platform (please complete the following information)

- Android
- HoloLens 2

## Additional context

Sample project included that indicates the problem.
[mrtk-sample.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/9444490/mrtk-sample.zip)

**Comment by MaxWang-MS** [comment]
Hi @bacnar, I took a look at the project and found some issues: you are relying on editor-only APIs (`AssetDatabase.LoadAssetAtPath` etc.) to load the profile. And the script is put under an Editor assembly (`Main.asmdef`). Thus, the script does not execute in a built player. We have two suggested paths:
1. Make `ProfileSwapper` a `MonoBehaviour` and expose serialized fields for the profiles. If you assign the profiles there, they will be included in the build. Make sure you add the `MonoBehaviour` to your scene.
2. Use [`Resources.Load`](https://docs.unity3d.com/ScriptReference/Resources.Load.html), but look out for the pitfalls mentioned in [Unity's documentation](https://docs.unity3d.com/ScriptReference/Resources.html).
