### ISSUE TITLE
Curved Pointers

### ISSUE THREAD

**Issue by derekfreed** [microsoft/MixedRealityToolkit-Unity#10958]
## Describe the problem

I wish I had a default implementation for Curved pointers. Essentially the same kind of thing as shell hand ray but mixed with the parabolic form of teleport pointer. I know there is a curve pointer class but there is no default implementation. This would be particularly useful for placing objects using tap to place script. I imagine having a curved controller ray option for solver handler would do the trick

**Comment by davidkline-ms** [comment]
Thanks for the feature request!

**Comment by Zee2** [comment]
XRI offers parabolic rays by default: https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@2.1/manual/xr-ray-interactor.html

![image](https://user-images.githubusercontent.com/5544935/187794823-ea6a39b5-5768-4514-aa2e-b0fc14a62f92.png)

**Comment by Zee2** [comment]
Closing as not planned for MRTK2, as it is offered by default in MRTK3.
