### ISSUE TITLE
[QUICK] Disable Spatial Awareness Triangles

### ISSUE THREAD

**Issue by cafigz** [microsoft/MixedRealityToolkit-Unity#10968]
Hi guys! How can I disable these white triangles from the 1st person view?
It's updating and showing in real-time and it's gets really laggy.
I don't use spatial awareness at all in my app, is there a way to disable it in this project only? 

![image](https://user-images.githubusercontent.com/103571527/188493762-e21fa5ad-4ebd-401a-8dfd-f56339500b11.png)

**Comment by HarrisonBT** [comment]
not a bug

Just disable spatial awareness observer in the MRTK configuration profile..

**Comment by cafigz** [comment]
Thanks, that was exactly it 🗡️ I didn't want to label it as a bug, I just wanted to ask it, but for some reason I couldn't add the Question label. Thanks once again
