### ISSUE TITLE
Unable to Get Far Ray hit point when select gesture used

### ISSUE THREAD

**Issue by ragavendranbala** [microsoft/MixedRealityToolkit-Unity#10967]
## To reproduce

Create a script with the reference of MRTK Ray Interactor
Subscribe to Select Enter Event with a method
The Select enter event will trigger the subscribed method with SelectEnterEventArgs argument
The argument doen't having the hit point to perfom some basic actions like instantiating the object on the hit point.

On MRTK2. It can be done using IMixedRealityPointerHandler's OnPointerClicked method and this event will be triggered on both hands. I couldn't find any documentation for subscribing to these kind of events in MRTK3.

**Comment by Zee2** [comment]
Hi @ragavendranbala!

`SelectEnterEventArgs` has the `interactorObject` property, which is the interactor that initiated the selection. Then you can query `.GetAttachTransform(interactable)` from that interactor object, which will represent the point of interaction on the specified interactable (regardless of whether it is a ray, a touch, a grab, or any other form of interaction.)
