### ISSUE TITLE
[MRTK3] PressableButton missing SetToggled() function

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#10975]
## Describe the problem
MRTK3's PressableButton does not provide SetToggled() or equivalent function/property that allows developers to set toggle state through code or inspector. .MRTK2 provided SetToggled() so that application logic can control the toggle state.

## Example
In Near Menu, when the user grabs the manipulation bar, moves it then releases it, we disable tag-along behavior and set Pin button state's toggle state on. Without SetToggled() function, there is no way to change the toggle state of the Pin button.

<img width="920" alt="2022-09-07 11_57_13-MRTKDevTemplate - NearMenuExamples - Universal Windows Platform - Unity 2020 3 3" src="https://user-images.githubusercontent.com/13754172/188957039-e4b16ac2-85b4-4c45-aa80-2b26de24ea56.png">

<img width="391" alt="2022-09-07 11_57_49-MRTKDevTemplate - NearMenuExamples - Universal Windows Platform - Unity 2020 3 3" src="https://user-images.githubusercontent.com/13754172/188957057-0a1c00e5-b06f-4a67-8ada-aa9f82237906.png">

**Comment by MaxWang-MS** [comment]
@Zee2 Is there a new way to do this or this is a gap?

**Comment by Zee2** [comment]
This is already possible. `ForceSetToggled(value, fireEvents)`. https://docs.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.toolkit.statefulinteractable.forcesettoggled?view=mrtkcore-3.0#microsoft-mixedreality-toolkit-statefulinteractable-forcesettoggled(system-boolean-system-boolean).

**Comment by Zee2** [comment]
This may need a single-variable override to be able to be invoked from a UnityEvent, though.

**Comment by brdystudios** [comment]
@Zee2 Right, it would be helpful to have one that can be used in the Inspector as well. Shall I reopen this issue with an updated title?

**Comment by Zee2** [comment]
> @Zee2 Right, it would be helpful to have one that can be used in the Inspector as well. Shall I reopen this issue with an updated title?

I'll open a new one (specific to adding an overload).

Thanks!
