### ISSUE TITLE
[MRTK3] Non-Canvas Buttons: Audio spatializer warning messages + decreasing volume on multiple press

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#10979]
## Describe the bug
On Non-canvas Buttons 

- Warning message + audio effect volume decreases on multiple press.
- Message: Audio source failed to initialize audio spatializer. Please check that the project audio settings and make sure that the selected spatializer is compatible with the target.

## To reproduce

1. Open a scene that contains PressableButton prefabs (non-canvas)
2. Run the scene
3. Check console messages

![2022-09-07 15_54_51](https://user-images.githubusercontent.com/13754172/188997640-b74d4d9a-685c-4a17-b6ef-33fae5855941.png)

**Comment by davidkline-ms** [comment]
The repeated warnings appear to be an issue in the Unity Engine. Whenever a sound is played, the engine appears to confirm the spatializer works on the current platform (and settings). If not, it displays this warning.

The volume decrease is likely due to the platform (ex: Windows) and/or the project not being properly configured. If you are using the Microsoft Spatializer, the configuration settings in the project will be different.

**Comment by davidkline-ms** [comment]
[This page](https://docs.microsoft.com/en-us/gaming/acoustics/unity-integration#set-up-audio-dsp) describes the steps that are needed to be performed if using Microsoft Spatializer 2.x (please note that while the documentation shows 'Project Acoustics', the steps are the same).

**Comment by Zee2** [comment]
@davidkline-ms , is there still no plan to fix this, other than wait for Unity to change this behavior?

**Comment by Zee2** [comment]
This is associated with #11177. Any updates here @davidkline-ms ?

**Comment by AMollis** [comment]
Related to #11177 ?

**Comment by AMollis** [comment]
@marlenaklein-msft  there are 5 issues related to spatial audio,  Can you help provide more context on these issues, and resolve any deduplicates?

The spatial audio issues area:

1. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6897
3. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10744
4. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10979
5. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11176
6. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11177
