### ISSUE TITLE
[pre.11] Hand-Rays have lots of unexpected movement

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10974]
## Describe the bug

Hand-Ray pointers move jaggedly around where the user is pointing, without additional movement

## To reproduce

Use Hand-Rays in the latest commit 3746f110c22c028902a9ca8665e3227661f979b3 or later

## Expected behavior

Hand-Rays are consistent and stay in one location when the user stops moving.

## Video

https://user-images.githubusercontent.com/110259320/188956062-fa9c74b2-f7dd-434b-8eac-3d5c6cbb3c08.mp4

## Your setup (please complete the following information)

- Unity Version 2020.3.37.f1

## Target platform (please complete the following information)

- HoloLens2
- Quest 2

**Comment by Clandguth** [comment]
@MaxWang-MS I encountered another behavior relating to this issue. It is sort of hard to tell whats going on because of the movement, but when the user moves their head, the hand-ray will move along with the headset from side to side. Here is a video showing this. 

https://user-images.githubusercontent.com/110259320/189408039-55273ffc-ab6c-45ff-aaf5-47e667938649.mp4

**Comment by keveleigh** [comment]
Hand ray moving with the head is currently expected on some platforms due to the current hand ray fallback implementation.

The originally reported instability is being investigated.

**Comment by Clandguth** [comment]
@keveleigh I am seeing the hand-ray moving with the head on HL2, and Quest2, while more clear on Quest 2, I feel like this has regressed to a state worth taking a look at. I could create a separate issue if need be.

**Comment by keveleigh** [comment]
Yeah, sounds good! I think it'd be good to track these separately.

**Comment by keveleigh** [comment]
Fixed in #10999
