### ISSUE TITLE
Separate cursor and ray visual editor controls for Far Rays

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#10982]
## Describe the problem

Cursors and the ray visuals are currently tightly tied together for Far Ray Interactors. This combined with some ambiguity about what parts of the line renderer are controlled by the Ray Visuals script makes it difficult to easily customize the visuals for far ray interactions.

## Describe the solution you'd like

clean up the MRTK Ray Visuals to better showcase the separation of responsibilities between the ray visuals, cursor visuals, and components that those respective scripts utilize.

**Comment by holomatt** [comment]
In order to save perf, it would be awesome to also be able to disable the hand ray line line calculation entirely in addition to being able to customize the cursor visuals separately.
