### ISSUE TITLE
Compare perf across MRTK2 and 3

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#11005]
Compare MRTK2 and 3 perf in some comparable scene(s) to get a concrete understanding of where we stand in performance right now.

**Comment by AMollis** [comment]
@srinjoym we should verify performance of MRTK3 before GA release

**Comment by AMollis** [comment]
Performance is comparable to MRTK2, expect for the MRTK3's primary button and dialog types (canvas versions)

We've opened a sperate task to investigate improvements to these components:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11471
