### ISSUE TITLE
Cursor Prefab Object: logic for button-normal-specific reticle orientations

### ISSUE THREAD

**Issue by holomatt** [microsoft/MixedRealityToolkit-Unity#11018]
-The Cursor visualization currently snaps to the sides of button colliders in a layout, causing awkward visuals and confusing interactions when the cursor flickers between orienting along the front normal of the button and the sides of it.

-It's confusing when I try to target a button and the cursor renders orientated along the side of the button as opposed to the front. It can also be challenging to interact when the cursor flickers between a pose aligned to the normal of the button vs the side.

-PressableButton \ Enforce Front Push property could be made to ensure the cursor only renders oriented with the button collider's normal. Alternatively, a helper on the Cursor prefab could include a property to enable this behavior.

-Layouts with no gutter/padding between buttons in a collection, but this does not help with single button layouts or the the exposed edges of the button collection.

-This issue could be considered an interaction blocker as "flickering" between aligning with the front/side of the button combined with the "Enforce Front Push" property can result in failed interaction attempts.

**Comment by Zee2** [comment]
Gracias @holomatt :) We'll make this GA blocking for sure.

**Comment by Zee2** [comment]
@AMollis please unassign me. I am unfortunately no longer legally allowed to contribute to this project (aside from no longer being employed by Microsoft 😅)

**Comment by shaynie** [comment]
Talked to Matt, and he'd like to see the cursor only face the interactable normal.  If we take a fix, we'll need to check the behavior on interactables with sphere or capsule colliders.
