### ISSUE TITLE
Hand Tracking not working on Oculus Quest 2

### ISSUE THREAD

**Issue by Jerry-04** [microsoft/MixedRealityToolkit-Unity#11026]
## Describe the bug

I'm testing the hand tracking and hand interaction on Oculus Quest 2 using MRTK 2.8(Unity version 2022.1.12f). However, in the HandInteractionExamples scene my hands are unable to work(or be seen). 

I've enabled the hand tracking in my Quest device and I've also set the **Hand Tracking Support** to **Hands Only** in the Oculus Project Config file.

For the MixedRealityToolKit, I was cloning from ObsoleteXRSDKConfigureProfile.

Hands tracking is not working either in Unity editor or after deploying to Quest.

## Screenshots

![MRTK](https://user-images.githubusercontent.com/26646837/190721601-e997b245-b1ad-4959-81dd-cc8557de3e53.png)
![Oculus Settings](https://user-images.githubusercontent.com/26646837/190722505-d95dde99-c397-4317-8a0d-11f7a7d2d4bc.png)
![XR plugin management](https://user-images.githubusercontent.com/26646837/190722532-a83e8b54-56f4-4a01-8fa6-0bd8a9454b17.png)
![open xr](https://user-images.githubusercontent.com/26646837/190722578-f9c59e7a-be87-46ab-b824-ffe9e4caa90b.png)

## Your setup (please complete the following information)

- Unity Version [2022.1.12f1]
- MRTK Version [v2.8]

## Target platform (please complete the following information)

- Oculus Quest

**Comment by Zee2** [comment]
Assigning @RogPodge as he's our Quest extraordinaire for MRTK2

**Comment by Jerry-04** [comment]
False alarm, turned out to be that I forgot to **integrate Oculus integration Unity modules**. Thank your for the responding!

**Comment by Zee2** [comment]
Great! Thanks for the update @Jerry-04.
