### ISSUE TITLE
Play mode tests don't properly publish their results in CI

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#11027]
Play mode tests don't properly publish their results in CI, meaning we cannot actually report whether they succeed or fail.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk3/Pipelines/Templates/tests.yaml

**Comment by Zee2** [comment]
This was attempted to be solved in #10843 , but @keveleigh and I couldn't figure out where the .xmls were going.

**Comment by Zee2** [comment]
Solved by Testmaster @Clandguth !
