### ISSUE TITLE
Missing Script in Mediacal sample for Voice commands

### ISSUE THREAD

**Issue by cyrillef** [Microsoft/MixedRealityToolkit-Unity#1102]
Voice commands not working because of a missing script
Go on the Managers GameObject and notice after open the scene that there is a script missing.
Tested on unity 2017.1.2f1 Windows

**Comment by HattMarris1** [comment]
Seems to be due to SpeechInputSource.cs replacing KeywordManager.cs in in this merge: #1085

**Comment by StephenHodgson** [comment]
Well, the `KeywordManager` has been obsolete for a while.

Unfortunately, Examples that are not maintained regularly do get deprecated.

I'm sure it's not too difficult to hook back up.
Using a previous release you could open the projects side by side, and update the scene.
