### ISSUE TITLE
Cursors/Reticles vanish when cast against non-interactive colliders or disabled PressableButtons

### ISSUE THREAD

**Issue by holomatt** [microsoft/MixedRealityToolkit-Unity#11023]
## Describe the problem

It's challenging/confusing to interact with Slate based UI when the cursor visibility flickers on/off when pointing at the slate backplate or against PressableButtons that are not currently interactive.

## Describe the solution you'd like

An option to allow the Cursors/Reticles to always visualize against colliders in the layer mask setup.

## Describe alternatives you've considered

Not seeing a possible route to fix this without changes to MRTK Rig Prefab/Classes

## Additional context

Cursor visual stability is key to consistent feedback loop for understanding cursor and hand tracking state against collision surfaces. Only supporting visualization against PressableButtons that are currently interactable creates"holes" in the castable surface of a a slate interface and introduces flicker/instability in the cursor visualization, resulting in reduced user confidence when pointing at the panel with Far Ray Interactors or PokePointer.

**Comment by RogPodge** [comment]
Added a new setting to address this in #11022 

![306519506_3183805988550364_180012656966366707_n](https://user-images.githubusercontent.com/39840334/190715582-3314c6af-4fac-4e5c-8c71-389f2aa0b906.png)

**Comment by keveleigh** [comment]
Looks like this is fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11022
