### ISSUE TITLE
Error CS0246 after import holotoolkit at unity

### ISSUE THREAD

**Issue by l1mts** [Microsoft/MixedRealityToolkit-Unity#1103]
I am using Unity 5.6.3p1 and when I import the HoloToolKit I have the following error: 
Assets/HoloToolkit/Utilities/Scripts/Editor/AutoConfigureMenu.cs(14,38): error CS0246: The type or namespace name `IActiveBuildTargetChanged' could not be found. Are you missing an assembly reference?

I tried to use Unity 5.3.1f1 but I have the same problem. 
What can I do? 
Thank you,

**Comment by HattMarris1** [comment]
Try updating to Unity 5.6.3p4: https://unity3d.com/unity/qa/patch-releases/5.6.3p4

5.6.3p4 is the minimum requirement for the toolkit at the moment: https://github.com/Microsoft/MixedRealityToolkit-Unity/wiki

**Comment by StephenHodgson** [comment]
Be sure to stay download and use the latest release v1.2017.1.2
