### ISSUE TITLE
Context-aware reticles not yet implemented in MRTK3

### ISSUE THREAD

**Issue by ragavendranbala** [microsoft/MixedRealityToolkit-Unity#11037]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/259

___

## To reproduce

1. Open mrtk3 DevTemplate  Project
2. Open BoundsControl Example Scene
3. Click any one of object and try to move the cursor towards the edges of the handles.

## Expected behavior

The cursor should change based on the interaction going to do. In this case Scale or Rotate.

## Actual behavior
The cursor is not changing based on the manipulator

- Unity Version [e.g. 2020.3.38f1]
- MRTK Version [e.g. v3]

## Target platform

- HoloLens
- HoloLens 2
- WMR immersive

**Comment by RogPodge** [comment]
This is currently being worked on! We're just finishing up a PR that will help get animated cursors working in MRTK3

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11022

**Comment by Zee2** [comment]
Clarification: the cursor does _**animate**_, but it does not switch icons to represent different types of manipulations.

**Comment by AMollis** [comment]
@shaynie is this a regression from MRTK2?
