### ISSUE TITLE
QRTracker how to not store QR Codes in memory?

### ISSUE THREAD

**Issue by KillTheProcess23** [microsoft/MixedRealityToolkit-Unity#11044]
Hi everyone, im using the [MixedReality-QRCode-Sample](https://github.com/microsoft/MixedReality-QRCode-Sample) and it works just fine except that QR Codes persists between session of the app (i know this is intended, but not useful in my case). I need to restart the Hololens to clear those.
Is there any way to not store the QR Codes generated?

Also let's say i've read the QR Code and instantiated the prefab, how do i remove the QRCode id from memory  once i destroy the gameobject?

**Comment by keveleigh** [comment]
Hey @KillTheProcess23!

I reached out to the feature team responsible for QR code tracking, and it sounds like restarting the device is the only mechanism for removing QR codes from memory. The recommendation is to ignore QR codes older than a specific timestamp if you're trying to remove stale codes.

For more info: https://learn.microsoft.com/windows/mixed-reality/develop/advanced-concepts/qr-code-tracking-overview#managing-qr-code-data

**Comment by KillTheProcess23** [comment]
Yes that's the workaround i've been using to solve this. And it works like a charm! I just hope QR codes are not "heavy" in memory but since with a simple restart they are gone it should not be a problem.

For anyone struggling with this just add this line of code before any action is performed

```
//declare a DateTimeOffset variable and when the watcher start put this e.g. in SetupQRTracking()
public void SetupQRTracking() {
     //setup stuff...
     watcherStart = DateTimeOffset.Now;
}
if (action.qrCode.LastDetectedTime > watcherStart) {
     switch (action.qrAction) {
        //manage your cases here
     }
}
```

Thanks! :)

**Comment by keveleigh** [comment]
Thanks for providing a code reference!
