### ISSUE TITLE
Pointer reticle doesn't disappear when using hand-rays 

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#11045]
## Describe the bug

The pointer reticle is placed on the finger of the user, It is expected when the user swaps to using hand rays instead of their pointer, the reticle will disappear and create a new one on the end of the hand-ray. In this case, it is not removing the initial pointer reticle.

## To reproduce

Launch any MRTK3 sample scene, swap between using pointer, and hand-rays

## Expected behavior

It is expected when the user swaps to using hand rays instead of their pointer, the reticle will disappear and create a new one on the end of the hand-ray, until the user swaps back to pointer

## Screenshots

![image](https://user-images.githubusercontent.com/110259320/192335358-9f0956a6-db0e-4c1b-9de7-3c737f8223de.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.39f1
- Commit Version 87db81236428d6868c9c3f47c4b6cffbc35d5079, most likely originated from the reticle changes on commit a51a28f9b7a7ca1fd2efe7fef1ec4eed2e38a284

## Target platform (please complete the following information)

- Quest 2
- HoloLens 2

**Comment by RogPodge** [comment]
Fixed by this: #11038 It's a followup PR that didn't get checked in right before the weekend.
