### ISSUE TITLE
[MRTKv3] BoundsControl manipulation started and ended lacking some arguments

### ISSUE THREAD

**Issue by akash14darshan** [microsoft/MixedRealityToolkit-Unity#11049]
## Describe the problem

BoundsControl handles can be used to scale, translate and rotate the object. In MRTK 2.8 there were different UnityEvents for scaling started ended, and similar for rotation and translate. However in MRTKv3 there seems no such way to differentiate between such operations based on the selected handles.

## Describe the solution you'd like

A simpler solution for this is to either expose some fields like HandleType and ManipulationAxis (for translation and rotation) and update these fields before Invoking the manipulation event, or provide these extra information in the manipulation event argument.

## Describe alternatives you've considered

At the present, I am forced to go with reflection. But this is not a stable solution due to performance, and also due to potential unwanted Unity issues due to IL2CPP.

**Comment by Zee2** [comment]
Sounds good! Thanks for highlighting this.

**Comment by Zee2** [comment]
@akash14darshan , I looked into this; you can indeed check which manipulation occurred as follows:

```
// boundsControl.ManipulationStarted.AddListener(MyEventListener)
// SelectEnterEventArgs is the arg type passed by XRI when an interaction begins.
void MyEventListener(SelectEnterEventArgs args)
{
    if (args.interactableObject is BoundsHandleInteractable handle)
    {
        HandleType typeOfManipulatedHandle = handle.HandleType;
        // Do whatever you'd like with this information!
    }
}
```

**Comment by akash14darshan** [comment]
@Zee2 oh I see. thanks for helping with it.
Is there a similar way to get the rotation axis/translation axis aswell?
