### ISSUE TITLE
Follow me Toggle is not Available for Slate UI

### ISSUE THREAD

**Issue by ragavendranbala** [microsoft/MixedRealityToolkit-Unity#11041]
## To reproduce

1. Clone the MRTKDevTemplate file from mrtk3 Branch

2. Open UITearSheet Scene
3. Click the Pin Icon on the Slate UI

## Expected behavior

The Pin should toggle the follow me behaviour

## Actual behavior
The Pin is disabling the slate UI and unable to find the follow me toggle option in followme script

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.3.38f1]
- MRTK Version [e.g. v3]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive

**Comment by MaxWang-MS** [comment]
Fixed via #11255
