### ISSUE TITLE
MRTK3 VR interactions without using XRTK

### ISSUE THREAD

**Issue by ytehreem** [microsoft/MixedRealityToolkit-Unity#11050]
## Describe the problem

Currently, there is nothing on MRTK3 teleportation system. How can we add teleportation using MRTK3 without using XRTK.
Same problem with socket interactor (to join or drop objects in specific location). 
## Describe the solution you'd like
Can we achieve basic physical interactions like teleporting, joining, grabbing etc. without using XRTK? 

## Additional context
If the features are there in MRTK3, where we can find its documentation?

Thanks.

**Comment by keveleigh** [comment]
To clarify here, by "XRTK" are you referring to Unity's XR Interaction Toolkit?

If so, we've been using XR Interaction Toolkit (we tend to refer to it as XRI) for the things it supports, like teleportation and any existing interactors. I'd refer to Unity's docs for those features, like https://learn.unity.com/tutorial/locomotion-and-teleportation-in-the-xr-interaction-toolkit.

Are you finding gaps in their support? We've been working to make MRTK3 as interoperable and compatible as possible with the rest of Unity's XR Interaction Toolkit without reinventing the things they already do, so please flag anything we've missed!

**Comment by ytehreem** [comment]
Ah okay thanks for the answer. I got it.
