### ISSUE TITLE
SerializeReference YAML format incompatibility between 2020 and 2021

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#11077]
## Describe the bug

2021 serializes `SerializeReference`s differently than 2020. Usually, this causes little no interruptions, but when making _prefab variants_ in 2021 of 2020-serialized prefabs with `SerializeReference` data, it can silently corrupt prefabs :(

## To reproduce

1. Make prefab variant of button in 2021
2. Specify an override to a StateVisualizer effect (note; _adding new effects_ does not surface this bug)
3. Save, commit changes
4. Clear library
5. Prefabs corrupted

## Expected behavior

SerializeReference overrides should not cause prefab corruption.

## Additional info

- The 2021 serialization, when adding a new entry to a list and then immediately defining it (this example resizes from 1 -> 2, and defines the new object), does this:
    - Overrides size of list:
        `propertyPath: ListOfReferences.Array.size`
        `value: 2`
    - Defines new RefID inline:
        `propertyPath: ListOfReferences.Array.data[1]`
        `value: LONGNUMBER`
    - Immediately, for subsequent entries in the yaml, begins referring to this entry by the LONGNUMBER.
    - Specifies the type and assembly:
        `propertyPath: managedReferences[LONGNUMBER]`
        `value: MyAssembly MyNamespace.MyType`
    - Specifies the new value of this item:
        `propertyPath: managedReferences[LONGNUMBER].SomeValue`
        `value: 42069`

- The 2020 serialization, which is observed in MRTK's override of Action Button on Empty Button, appears as follows
    - Overrides size of list:
        `propertyPath: ListOfReferences.Array.size`
        `value: 2`
    - Does not define a new refid.
    - Specifies assembly and type of the item:
        `propertyPath: ListOfReferences.Array.data[1]`
        `value: MyAssembly MyNamespace.MyType`
        - Notice: the property path is NOT a RefID, it's a path!
    - Specifies new value of the item:
        `propertyPath: ListOfReferences.Array.data[1].SomeValue`
        `value: 42069`
        - Like above, the property path is NOT a RefID, it's a path!
        
 When the 2020 packages are consumed in 2021 project, Unity 2021 tries to make a 2021-formatted override on a 2020-formatted asset, which causes the problem. It tries to refer to the serialized item by `managedReferences[LONGNUMBER]` even though `LONGNUMBER` does not actually exist in the base asset.

**Comment by Zee2** [comment]
@JonathanPalmerGD

**Comment by Zee2** [comment]
Katie H and I determined this is a Unity YAML serialization bug related to immutable packages wherein prefab variants that are variants of prefabs in immutable packages will have the incorrect YAML format serialized to disk.

**Comment by Zee2** [comment]
Further investigations:

- The 2021 serialization, when adding a new entry to a list and then immediately defining it (this example resizes from 1 -> 2, and defines the new object), does this:
    - Overrides size of list:
        `propertyPath: ListOfReferences.Array.size`
        `value: 2`
    - Defines new RefID inline:
        `propertyPath: ListOfReferences.Array.data[1]`
        `value: LONGNUMBER`
    - Immediately, for subsequent entries in the yaml, begins referring to this entry by the LONGNUMBER.
    - Specifies the type and assembly:
        `propertyPath: managedReferences[LONGNUMBER]`
        `value: MyAssembly MyNamespace.MyType`
    - Specifies the new value of this item:
        `propertyPath: managedReferences[LONGNUMBER].SomeValue`
        `value: 42069`

- The 2020 serialization, which is observed in MRTK's override of Action Button on Empty Button, appears as follows
    - Overrides size of list:
        `propertyPath: ListOfReferences.Array.size`
        `value: 2`
    - Does not define a new refid.
    - Specifies assembly and type of the item:
        `propertyPath: ListOfReferences.Array.data[1]`
        `value: MyAssembly MyNamespace.MyType`
        - Notice: the property path is NOT a RefID, it's a path!
    - Specifies new value of the item:
        `propertyPath: ListOfReferences.Array.data[1].SomeValue`
        `value: 42069`
        - Like above, the property path is NOT a RefID, it's a path!
        
 When the 2020 packages are consumed in 2021 project, Unity 2021 tries to make a 2021-formatted override on a 2020-formatted asset, which causes the problem.

**Comment by AMollis** [comment]
@shaynie We'll might be removing support for 2020 with PR [11345](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11345).  Can you investigate the impact here.
