### ISSUE TITLE
MRTK3 HandConstraintPalmUp doesn't default to head gaze for uncalibrated users

### ISSUE THREAD

**Issue by camnewnham** [microsoft/MixedRealityToolkit-Unity#11092]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/250

___

## Describe the bug

When the app has gaze permission enabled but the user is uncalibrated (declines prompt to calibrate) the Gaze controller remains at the origin, but appears to still be considered active.

As a result, the HandConstraintPalmUp only triggers if the user happens to be looking in the same direction as the default.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk3/com.microsoft.mrtk.spatialmanipulation/Solvers/HandConstraintPalmUp.cs#L268-L290

Or have I miswired something?

MRTK `3.0.0-pre.11` 

MixedRealityOpenXRPlugin `1.5.1`

**Comment by camnewnham** [comment]
It seems that `InputTrackingState` is not `None` if eyes are untracked (visor flipped up) as well (this does not affect the hand menu, but has other considerations)

**Comment by Zee2** [comment]
HandConstraintPalmUp is being totally re-jiggered in this PR: #10852 . Will be totally redone and optimized for head gaze!

**Comment by camnewnham** [comment]
> HandConstraintPalmUp is being totally re-jiggered in this PR: #10852 . Will be totally redone and optimized for head gaze!

Oh, nice! That looks great. 

Perhaps the separate (or more appropriate) issue here is that `GazeController` is reporting a non-`None` trackingstate when the user isn't calibrated or the eye tracking isn't current (visor flipped up, headset off, etc).
