### ISSUE TITLE
[Pre.12 Blocker] Crash on UITearSheet Example scene after moving to another example scene

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#11094]
## Describe the bug

App crash back to the OS Shell. Was experienced when attempting to move to another example Scene from UITearSheet

## To reproduce

1. Build a MRTK3 Sample app with at least 3 scenes, with UITearSheet in between the other scenes
2. Launch the UITearSheet example
3. Open the hand menu and navigate forward or backward to one of the other examples
4. Experience crash after a short period of time

## Expected behavior

App does not crash when moving scenes

## Video and Logs

https://user-images.githubusercontent.com/110259320/194924246-b63bc401-3772-4cba-9379-13256216215c.mp4

[UnityPlayer.log](https://github.com/microsoft/MixedRealityToolkit-Unity/files/9747960/UnityPlayer.log)

## Your setup (please complete the following information)

- Unity Version 2021.3.9f1
- Commit Version 1ae9296ff50078df42c4df9b8beca4497df24370

## Target platform

- HoloLens 2

**Comment by Clandguth** [comment]
Has something to do with changing scenes. Have not encountered on any other example

Unloading 9 Unused Serialized files (Serialized files now loaded: 0)

According to @Zee2, its unloading everything when changing to another scene.

**Comment by Zee2** [comment]
Closing, no repro
