### ISSUE TITLE
HandInteraction example objects are moving quickly back and forth when colliding, one cube is falling through the platform

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#11095]
## Describe the bug

Objects when colliding are moving back and forth very quickly, one object was falling through the Interactable platform

## To reproduce

1. Launch HandInteraction Example
2. Move near interaction examples on the right of the scene, cubes will start moving quickly back and forth as soon as the scene begins, one is falling through the platform

## Expected behavior

Cubes are still unless being directly manipulated by the user, or an object the user is moving

## Video

https://user-images.githubusercontent.com/110259320/194926670-499a21e9-4736-46fc-b83e-eb61a99e80f9.mp4

## Your setup (please complete the following information)

- Unity Version 2021.3.9f1

## Target platform (please complete the following information)

- HoloLens 2

**Comment by Zee2** [comment]
Probably something weird to do with moving the content root around... not a big problem for us.

**Comment by Clandguth** [comment]
@Zee2 Only reason the content root was moved was to get the behavior recorded on video. The behavior was occurring before moving the content root.

**Comment by Zee2** [comment]
Can't repro this either.

**Comment by Zee2** [comment]
Closing for lack of repro.
