### ISSUE TITLE
[MRTK3] Using OculusXR feature in the OpenXR Feature Group causes quest controller visuals to be glitched

### ISSUE THREAD

**Issue by akash14darshan** [microsoft/MixedRealityToolkit-Unity#11101]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/248

___

## Describe the bug

When I enable the "OculusXR Feature" in OpenXR Feature Groups (to enable Quest specific things like Passthrough, OVRInput, etc) the controller gets visual gets bugged, and the Far interaction ray looks bent.
The controller model seems to be stuck in the air (as seen in screenshot)
The controller does seem to respond ingame though to rotations. But movement seems to not work.

Hand tracking seems to work fine without any issues.

## To reproduce

1. Configure the project as mentioned in the [Microsoft's guide](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/deployment/quest-deployment)
2. Goto `ProjectSettings/XR Plugin Management/Open XR`, and select android operating system.
3. Enable "OculusXR Feature" in OpenXR Feature Groups.
4. Build and deploy to device

## Expected behavior

Normally I would expect this feature not to interfere with the controllers.

## Screenshots

![image](https://user-images.githubusercontent.com/13174425/195373195-21afe0c8-3430-4f28-a763-a1c0840e10b4.png)
![com AfterNow AnPrez-20221012-201201](https://user-images.githubusercontent.com/13174425/195379482-7695d50e-b5b3-4198-b862-53f173109ad7.jpg)

## Your setup (please complete the following information)

Unity 2021.3.8f1
MRTK3 Repo (as of commit https://github.com/microsoft/MixedRealityToolkit-Unity/commit/87ae775470952d28f0d459e9abeb6b95102505ff)

## Target platform (please complete the following information)

- Quest 2

## Additional context

I'm not sure if its helpful or not, but `OVRPlugin.GetSystemHeadsetType()` returns `OVRPlugin.SystemHeadset.Oculus_Quest` instead of `OVRPlugin.SystemHeadset.Oculus_Quest_2` on Quest 2

**Comment by Zee2** [comment]
@keveleigh , are we supporting this path at all?

**Comment by keveleigh** [comment]
Oh hmm...I haven't done much with Oculus' feature here since it's a _little_ heavy 😅 but it seems weird to me that it'd affect our own input! I can see about testing this today

**Comment by akash14darshan** [comment]
I dont know if this info could be useful or not, 
but from as what I can think of, it seems like the Ray is always coded to originate from the controller model prefab.

When I added OVRManager prefab in the script with "Disable Eye Anchor Cameras" I noticed that hand tracking was still fine and unaffected, but with controller, I could see the Quest controller model (of Quest1 instead of Quest2) on screen which was moving and following my movement.

**Comment by merulaxr** [comment]
I haven't been able to get Oculus's OpenXR feature to work properly at all, it seems very early still. Is this really an MRTK bug?

**Comment by akash14darshan** [comment]
> I haven't been able to get Oculus's OpenXR feature to work properly at all, it seems very early still. Is this really an MRTK bug?

It seems so because MRTK Inputs should not be affected by enabling `Oculus XR` OpenXR feature.

**Comment by Zee2** [comment]
This is sort of tricky because we're not explicitly supporting using OVR APIs or OVRManager with MRTK3. However, as it stands, things probably shouldn't be interfering.

**Comment by akash14darshan** [comment]
I did some research on it and i think the root cause is the `rotationAction` and the `positionAction` in the action based controller.
They do work normally but for reason with Oculus XR enabled, it doesn't work.

I did find a workaround for it.
There are two requirements for it are:
- Detect if hand tracking or controller
I'm doing this using Unity Input System's Oculus Touch Left/Right controllet presence.
- Create new Input Asset which will use Oculus Touch Controller Left and Right device position and rotation respectively.

Now create a new script, attach it to Mrtk XR rig prefab.
i) when the controller mode is detected, get reference to left and right action based controller. save references to old position and rotation action. Then apply the new position and rotation action which we created from Oculus Touch Controller.
ii) when hand tracking is back, restore back the old position and rotation action.

I don't know if I my steps were clear or not, but using this workaround I am now able to use controllers in quest normally.


PS:
I will gladly respond to anything if required, but i still hope this workaround becomes a part of core mrtk itself since now I'm able to use all the Oculus XR specific features with MRTK3 which is a huge plus for me. It would be a bonus for many other quest developers who would like to use quest specific features like Passthrough, etc

**Comment by Zee2** [comment]
@akash14darshan thanks for the extra info here. There should be a way we can get around this without doing funky runtime input action swapping... Pinging @keveleigh  here :)

**Comment by keveleigh** [comment]
Confirmed repro over Link 😡 will dig in to see why this feature is causing issues!

**Comment by keveleigh** [comment]
Hey @akash14darshan! I was previously able to repro, I believe with the 46.0 version of Meta's Oculus Integration package. After updating to 47.0, I can no longer repro. Are you able to update and give this another shot without your workaround?
