### ISSUE TITLE
Assembly with name 'Microsoft.MixedReality.Toolkit.Tools' already exists (Packages/com.microsoft.mixedreality.toolkit.tools/MRTK.Tools.asmdef)

### ISSUE THREAD

**Issue by cherrychocolate** [microsoft/MixedRealityToolkit-Unity#11125]
## Describe the bug

The following errors show up after the import of the latest MRTK3 package
`Assembly with name 'Microsoft.MixedReality.Toolkit.Tools' already exists (Packages/com.microsoft.mixedreality.toolkit.tools/MRTK.Tools.asmdef)`
`Assembly with name 'Microsoft.MixedReality.Toolkit.Tools' already exists (Packages/com.microsoft.mrtk.tools/MRTK.Tools.asmdef)`
```
An error occurred while resolving packages:
  Project has invalid dependencies:
    com.microsoft.mixedreality.sceneunderstanding: zlib: unexpected end of file
    com.microsoft.mixedreality.toolkit.extensions: zlib: unexpected end of file
    com.microsoft.mixedreality.toolkit.gpustats: zlib: unexpected end of file
A re-import of the project may be required to fix the issue or a manual modification of D:/SDK/SDK_Project/MRTK_3/Packages/manifest.json file.

```
I've tried to re-import the package several times.

## To reproduce

Import the latest MRTK3 package

## Screenshots

<img width="748" alt="d049e47d22ca9eac362378426a199185" src="https://user-images.githubusercontent.com/6879561/197105203-18a526d3-a839-4f38-87dc-10d0d0539257.png">
<img width="600" alt="1666323523459_8AACC4FF-AAAD-4885-9045-F358FFD693B1" src="https://user-images.githubusercontent.com/6879561/197106135-04d54c2a-af5c-4699-a3ce-949f3fb09b17.png">

## Your setup (please complete the following information)

- Unity Version [2020.3.36f1c1]
- MRTK foundation toolkit[v 2.8.2]
- MRTK3

## Target platform (please complete the following information)

- OpenXR(Oculus)

**Comment by Zee2** [comment]
Clarifying; it doesn't look like this is MRTK3, correct? Your Feature tool is showing MRTK3 0/16, and you have v2.8 installed for most of the other packages. In addition, the Foundation is MRTK v2 only and is not to be combined with any MRTK3 packages.

**Comment by keveleigh** [comment]
Ahh @davidkline-ms, looks like the MRTK3 Tools package assembly created in #10829 conflicts with the MRTK2 assembly. We should either try to make it a true 2.x -> 3.x version of the "same" package or potentially rename the MRTK3 assembly to not conflict. Side-by-side installation _should_ be possible imo.

**Comment by keveleigh** [comment]
The `zlib: unexpected end of file` logs often come from incomplete downloads from the Mixed Reality Feature Tool (also ping @davidkline-ms and @MaxWang-MS). Any chance you could grab the logs for us please? https://learn.microsoft.com/windows/mixed-reality/develop/unity/configuring-feature-tool#diagnostic-settings

**Comment by Shanksmate** [comment]
> Clarifying; it doesn't look like this is MRTK3, correct? Your Feature Tool is showing MRTK3 0/16, and you have v2.8 installed for most of the other packages. In addition, the Foundation is MRTK v2 only and is not to be combined with any MRTK3 packages.

Hi, sorry to sorta throw this in here.
Please, does this mean the MRTK Figma Bridge should not be combined with MRTK3? The Feature tool lists the Foundation package as a dependency and it leads to a host of conflicts. I was really looking forward to using the Figma Bridge with the MRTK3 Figma Toolkit. 

![MRTK3 errors](https://user-images.githubusercontent.com/100446713/199833106-9bd8b784-05cd-476e-a448-f4459bda3835.PNG)

**Comment by Zee2** [comment]
Hi there,

No, the Figma Bridge is currently MRTK2 only. We don't currently support mixing any packages between MRTK2 and 3.
