### ISSUE TITLE
Build failure, invalid SDK version reported in Appxmanifest

### ISSUE THREAD

**Issue by ccpp** [microsoft/MixedRealityToolkit-Unity#11124]
## Describe the bug

In a command-line build on GitHub we experience build failure due to an invalid AppxManifest.xml.
MRTK constructs an invalid Package.appxmanifest with SDK versions like **"wdf"** (GitHub windows-latest, or **"winv6.3"** (windows-2019):
```xml
  <Dependencies>
    <TargetDeviceFamily Name="Windows.Holographic" MinVersion="10.0.10240.0" MaxVersionTested="wdf" />
    <PackageDependency Name="Microsoft.VCLibs.140.00" MinVersion="14.0.30704.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
  </Dependencies>
```
The version name is wrongly constructed from **Windows Kits folder name** in `UpdateDependenciesElement`.

## To reproduce

Use the following PowerShell lines:
```powershell
Install-Module UnitySetup -Force
Import-Module UnitySetup
Install-UnitySetupInstance -Installers ( `
  Find-UnitySetupInstaller -Version "2019.4.32f1" -Components 'Windows','Windows_IL2CPP','UWP_IL2CPP')

Start-UnityEditor -Project .\ `
  -ExecuteMethod Microsoft.MixedReality.Toolkit.Build.Editor.UnityPlayerBuildTools.StartCommandLineBuild `
  -BuildTarget WSAPlayer `
  -BatchMode `
  -LogFile .\Logs\Build.log `
  -Wait `
  -AdditionalArguments "-verbose -nographics -logDirectory Logs -buildAppx -arm64 -release" `
  -Verbose
```

## Expected behavior

The .appx is built with a valid AppxManifest.xml.

## Your setup (please complete the following information)

- Unity Version 2019.4.32f1
- MRTK Version 0.7.2, 0.8.2
- OS: GitHub-hosted windows runners

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
Ooh this is weird...looks like our version parsing logic is falling over on those VM images, but I'm not 100% sure why the folders wouldn't be named as expected!

**Comment by ccpp** [comment]
WDF is Windows Drivers (framework?)
Others stumbled over this in completely different settings:
* https://github.com/microsoft/Windows-driver-samples/issues/488
* https://www.cnblogs.com/zhangdongsheng/p/13370239.html
Is enumerating the folders really the correct way to extract valid version numbers?

**Comment by keveleigh** [comment]
> Is enumerating the folders really the correct way to extract valid version numbers?

It has so far worked out (well...until now!), but I think you're right and it might be a more fragile assumption than expected. At least, especially the assumption that we can just take the last entry and run with it.
