### ISSUE TITLE
Camera Positioned to Origin instead of floor in Seated and Standing scale

### ISSUE THREAD

**Issue by amrittb** [Microsoft/MixedRealityToolkit-Unity#1115]
If I select seated-and-standing scale during setup, sometimes the camera is positioned at origin. Also, when setting up with room scale if the boundary is lost during playing from editor, the position is reset to origin.

**Comment by StephenHodgson** [comment]
What version of the editor are you using?

**Comment by StephenHodgson** [comment]
Probably related to #1084

**Comment by amrittb** [comment]
Having issues from Unity2017.2.0b* till Unity2017.2.0f2 release. Yes, That's the issue.

**Comment by StephenHodgson** [comment]
Closing because duplicate status.
