### ISSUE TITLE
Controller model materials are broken under URP

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#11165]
### Discussed in https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/11162

<div type='discussions-op-text'>

<sup>Originally posted by **imjusthere** November  2, 2022</sup>
I used the MRTK3 demo project and updated MRTK3 to the newest versions to fix some teleportation bugs. Then when I imported the Universal Render Pipeline it broke some of the materials. The controllers are pink. I can't edit the prefab controllers it is using because it tells me the folder is read only. I changed the input folders to not be read only but it doesn't seem to make a difference to Unity. I was able to create my own controller prefabs and fix the textures but I don't see where to replace the original controller prefabs with my own. Any help would be greatly appreciated.</div>

**Comment by Zee2** [comment]
@RogPodge updates on this?

**Comment by Zee2** [comment]
Is this a gltf importer oopsie or something we're going to have to fix on our end?

**Comment by imjusthere** [comment]
> Is this a gltf importer oopsie or something we're going to have to fix on our end?

I'd also like to know if there has been progress on this. And if it does have to do with the gltf importer I'd like to know that as well. I recently ran into the error below when also including the unity package for "Ready Player Me". I'm using their avatars and their package also has a gltf importer. Which of the MRTK3 packages uses the importer? And if they all need it, is there a way to deal with this?

Multiple scripted importers are targeting the extension 'glb' and have all been rejected: GLTFast.Editor.GltfImporter (assembly: C:\Users\Chris\Documents\Unity Projects\Subway\UnityProjects\Subway\Library\ScriptAssemblies\glTFastEditor.dll), Siccity.GLTFUtility.GLBImporter (assembly: C:\Users\Chris\Documents\Unity Projects\Subway\UnityProjects\Subway\Library\ScriptAssemblies\Siccity.GLTFUtility.Editor.dll)
UnityEditor.AssetImporters.ScriptedImporter:RegisterScriptedImporters ()

**Comment by keveleigh** [comment]
@imjusthere Are you referring to these prefab controllers? 
<img width="329" alt="image" src="https://user-images.githubusercontent.com/3580640/206007814-25a4da31-80fd-4060-af73-2aaedd0f26a7.png">

I'm not able to repro in my quick test :/ can you please confirm:

1. Which glTF importer are you using and which version?
2. Which MRTK version are you using?
3. Which Unity version are you using?
4. Which URP version are you using?

I was using:
1. https://github.com/atteneder/glTFast/tree/v4.9.1
2. 3.0.0-pre.12
3. Unity 2021.3.8f1
4. URP 12.1.7

Thanks!

**Comment by keveleigh** [comment]
Aha! I went through the set up steps again and was able to repro this time. Digging in now...

<img width="317" alt="image" src="https://user-images.githubusercontent.com/3580640/206542906-1c2436fc-9041-4722-9d77-07d388fdeb8b.png">

**Comment by keveleigh** [comment]
Okay, after clicking "Reimport All"

<img width="296" alt="image" src="https://user-images.githubusercontent.com/3580640/206554248-44914ecc-3ccd-4445-b884-48cf9eda1140.png">

the controller (as well as all the MRTK sample scene content) has been reloaded using URP:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/3580640/206554499-72be9e8a-ebd7-4f33-8c39-12fb37230bb9.png">

Does "Reimport All" work for you @imjusthere?

**Comment by imjusthere** [comment]
I'm afraid I can't test it. The project isn't the same anymore. I had to
redo it because of multiple GLF importers.

**Comment by keveleigh** [comment]
> I'm afraid I can't test it. The project isn't the same anymore. I had to redo it because of multiple GLF importers.

No worries! I'm going to go ahead and close this issue for now though, since I believe I was able to fix it with an asset reimport.
