### ISSUE TITLE
Build failure with Unity 2023.1 related to custom awaiters

### ISSUE THREAD

**Issue by simonferquel** [microsoft/MixedRealityToolkit-Unity#11171]
## Overview

Unity 2023.1 introduce await support for pretty much every async constructs in Unity. As an example we added a GetAwaiter extension method to AsyncOperation.
This introduce ambiguous calls at compile time when trying to compile the MRTK package because of this file here: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/0d2cdf9defe019ad8cdf1093bb8580c646e9695e/Assets/MRTK/Core/Utilities/Async/AwaiterExtensions.cs

Note: I'll try to submit a PR next week to fix this

## Expected behavior

With 2023.1+, those extension methods should not be compiled, and the code relying on them should use Unity-builtin awaiters

## Actual behavior

Compilation of the package fails

## Steps to reproduce

- Create a project with Unity 2023.1
- Add the package to it
- Compilation fails

## Unity editor version
2023.1

## Mixed Reality Toolkit release version
2.8.2

**Comment by keveleigh** [comment]
Very exciting to see that Unity's adding built-in support for this! It's been a long time coming!

**Comment by sailro** [comment]
cc @jbevain
