### ISSUE TITLE
Spatialized audio on UX buttons eventually is inaudible after several presses

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#11177]
## Describe the bug

Similar to #11176, in the MRTKDevTemplate example scenes, the buttons' spatialized audio stops being audible after a few button presses.

## To reproduce

1. Open sample scene
2. Press buttons many times
3. After 4 or 5 presses, the sound stops playing.

## Expected behavior

Sound should continue playing.

## Your setup (please complete the following information)

- MRTK latest, 2020.3.38f1

## Additional context

This is probably the same, or similar, issue as #11176

**Comment by Zee2** [comment]
@davidkline-ms updates on this?

**Comment by AMollis** [comment]
@marlenaklein-msft  can you verify that this issue is still reproducible after configuring the MSFT Spatializer

**Comment by AMollis** [comment]
Related to #10979 ?

**Comment by AMollis** [comment]
@marlenaklein-msft  there are 5 issues related to spatial audio,  Can you help provide more context on these issues, and resolve any deduplicates?

The spatial audio issues area:

1. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6897
3. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10744
4. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10979
5. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11176
6. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11177

**Comment by marlenaklein-msft** [comment]
Closing this and consolidating spatial audio bugs into three issues:
[Add Warning for Missing Audio Mixer (Spatial Audio)](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11431)
[Updating Sample Scenes with Mixer for Spatial Audio](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11432)
[Documentation for Spatial Audio](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11433)
