### ISSUE TITLE
Spatialized audio is inaudible

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#11176]
## Describe the bug

In my own (non-Template project) I'm encountering a bug when I try to set up my audio using the Microsoft Spatializer. When an audio source is set up for spatialization, it simply does not play any audio.

## To reproduce

1. Install Microsoft Spatializer
3. Select Microsoft Spatializer as the desired spatializer in the project settings
4. Add an audio source to a GameObject
5. Configure audio source to spatialize. Set Spatial 3D blend to 100%
6. Play an audio clip with `PlayOneShot`

Observe that no audio is audible, on HoloLens 2 or on Windows with spatial audio enabled.

## Expected behavior

You should hear something, at least

## Your setup (please complete the following information)

- MRTK pre.12
- Unity 2021.3.1

## Target platform (please complete the following information)

- HoloLens 2
- Windows

## Additional context

The setup instructions were followed from here: https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/spatial-sound-in-unity

**Comment by srinjoym** [comment]
Issue: Audio mixer is not set to the Master Audio Mixer on PressableButton's from MRTK when using the Spatializer plugin. We should find the first audio mixer in the project and set it automatically, or show a warning

**Comment by marlenaklein-msft** [comment]
Closing this and consolidating spatial audio bugs into three issues:
[Add Warning for Missing Audio Mixer (Spatial Audio)](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11431)
[Updating Sample Scenes with Mixer for Spatial Audio](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11432)
[Documentation for Spatial Audio](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11433)
