### ISSUE TITLE
[MRTK3] Changing SimulatedHMD to public from internal

### ISSUE THREAD

**Issue by akash14darshan** [microsoft/MixedRealityToolkit-Unity#11184]
## Describe the problem

It's just a keyword change, but this change will allow me to create a custom input simulator which I can utilize for Android and iOS mobile. With thischange, I have paired up an mobile phone's rotation and position based on unity canvas buttons. I could also pair them up with the device sensors for easier control.

## Describe the solution you'd like

Simply changing SimulatedHMD to `public` instead of `internal`

## Describe alternatives you've considered

For now I'm using the cloned repository. But it'll be nice for this to be changed in the source itself.

## Additional context

It will also be nice to switch SimulatedController to `public` instead of `internal`
I have future plans to make use of a simulated controller using raspberry pi and this is the way for it i think.

**Comment by Zee2** [comment]
@akash14darshan feel free to open a PR!

**Comment by Zee2** [comment]
@akash14darshan, if this is still an issue, please feel free to open a PR (and reopen this issue). Otherwise closing as stale.

Your input sim idea sounds awesome! The XRI folks have actually designed a new input sim themselves with the new 2.3 update that might be worth taking a look at.
