### ISSUE TITLE
How do I get files under the path of Application.persistentDataPath?

### ISSUE THREAD

**Issue by AsIfPu** [microsoft/MixedRealityToolkit-Unity#11193]
I built a UWP project, stored the player information and wrote it to the path. But I can't find the file in this path and import it to my computer.

In the editor, I can find the file I saved fromC:\Users\admin\AppData\LocalLow\DefaultCompany\Hololens

Perhaps there are other ways to get the file I saved?

**Comment by MaxWang-MS** [comment]
Are you using a HoloLens? If so you can access the files via the device portal.

**Comment by AsIfPu** [comment]
> 你在使用 HoloLens 吗？如果是这样，您可以通过设备门户访问文件。

 Thanks for your reply. I found the file successfully
