### ISSUE TITLE
Create wall, ceiling and floor finding example

### ISSUE THREAD

**Issue by brean** [Microsoft/MixedRealityToolkit-Unity#1119]
Hi,

I'd like to have a wall, floor & ceiling finding example in the examples-folder. There is a Plane-Fining example but it lacks propper documentation and it does not work on the Hololens Out-of-the-box (if you just publish it it just shows the loaded fake-mesh). I'd like to create a new example that is close to the [Holograms 230-Documentation](https://developer.microsoft.com/en-us/windows/mixed-reality/holograms_230) that also shows walls and its dimensions. 

According to the [contribution guidelines](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/CONTRIBUTING.md) I created this ticket - if it is OK with you guys I would go on and provide a pull request.

**Comment by StephenHodgson** [comment]
Plane finding also breaks wack, so we could move the plugins to the examples folder while we're at it.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
