### ISSUE TITLE
Two hand object manipulation of type scaling not scaling the right way in MRTK3

### ISSUE THREAD

**Issue by akash14darshan** [microsoft/MixedRealityToolkit-Unity#11208]
## Describe the bug

A combination of Object Manipulator and MinMaxScale constraint leads to unexpected behaviour where the scale of object enlarges even with both hands are brought closer

## To reproduce

1. Add min max scale constraint to object manipulator
2. Make sure that the minimum scale is within a reasonable range to test this
3. Scale down the object, and try to bend the rays
4. When the rays start to bend, you notice the object enlarging even when it shouldnt

## Expected behavior

I would expect the object to stay at the minimum scale as long as the both hands are brought closer.

## Footage

https://user-images.githubusercontent.com/13174425/202428977-bf66a66b-3066-46ee-9e6f-63cd258a2463.mp4

## Your setup (please complete the following information)

- Unity 2021.3.8f1
- MRTK 3

## Target platform (please complete the following information)

- Quest 2

**Comment by Zee2** [comment]
Thanks for reporting this @akash14darshan .

**Comment by Zee2** [comment]
This should be tracked as part of #10759. @RogPodge , more math headaches

**Comment by shaynie** [comment]
Fixed here: https://github.com/microsoft/MixedRealityToolkit-Unity/commit/8bb2ef979fdb24119fa29493553050bf8a66d189
