### ISSUE TITLE
Custom interaction mode

### ISSUE THREAD

**Issue by MehdiViper** [microsoft/MixedRealityToolkit-Unity#11207]
## Overview
I want to define new interaction mode, for teleporting. If I use current modes it will interfere with other MRTK interactors. 
How can I do this? 

## Unity editor version
2021.3.13 LTS

## Mixed Reality Toolkit release version
MRTK3 pre. 12

**Comment by Zee2** [comment]
Assigning Roger here. You should be able to add your custom interaction mode on the InteractionModeManager component itself in the inspector.

**Comment by RogPodge** [comment]
+1 on Finn's statement. You should be able to easily add a new Mode to the Interaction Mode Manager

**Comment by Zee2** [comment]
@MehdiViper closing, please reopen if the IMM does not behave as expected!
