### ISSUE TITLE
Mouse/keyboard control when running as normal UWP-Windows application

### ISSUE THREAD

**Issue by brean** [Microsoft/MixedRealityToolkit-Unity#1120]
I have some UWP-specific C# code (For networking, bluetooth and wifi-detection) that does not work in Unity-3D. So I build the C#-project, open it in Visual Studio and then work on that. To test it I like to run it directly on my PC without deploying it to any device.

Proposal: Allow Keyboard/Mouse control the same way it works in the Unity-Editor for the build version if a connected mouse/keyboard is detected.

**Comment by StephenHodgson** [comment]
I'd actually like to see this customizable.

Ideally moose and keyboard should work as is, without having to hold shift to click. Or even the traditional wasd and mouse options would be great as well.

**Comment by brean** [comment]
> Ideally mouse and keyboard should work as is, without having to hold shift to click.
You can configure the ButtonType in InputManager -> EditorHandsInput -> HandControls -> LeftHand/RightHand -> FingerUpButton/FingerDownButton from "Shift and Left"/"Control and Left" to just "Left" so you don't need to hold it for the air-tap.

I could imagine that there are scenarios where you'd like to control the camera position with WASD-keys if an external keyboard is connected but you also like to have it as input for a text field - both in the same application you like to debug, so you need to be able to switch this somehow at runtime (If you could determine if you run as an MR-Headset-application you could also disable the WASD-control automatically and have some key reserved for the switch when debugging as standalone c#-app).

**Comment by brean** [comment]
I don't know if it worked before because I still had some of my old code in there or if sth. changes, but the mouse/keyboard interaction does NOT work on the current master branch. I just run the InteractiveObjectExample demo on my notebook (as well as some of my own projects) and tried to control the cam with my mouse/keyboard as in the Game Mode of the Unity Editor which did not work.

**Comment by genereddick** [comment]
Mouse input not working for me either in any environment (within immersive display or in Unity editor with Enable VR unchecked).
