### ISSUE TITLE
Correct World Space Canvas Settings (scale, pos-z, width, height)

### ISSUE THREAD

**Issue by Maesla** [microsoft/MixedRealityToolkit-Unity#11203]
## Overview
Hello,

I am trying to figure out the correct settings for a World Space Canvas.
I know that I can not use Screen Space-Overlay and Screen Space-Camera and the only available Render mode is World Space. 

So, I have been checking all the MRTK examples and I have seen all kind of scales, pos-z, width and heights.

I am trying to find a world space canvas that fits perfectly at the HoloLens 2 field of view, but I can not find the correct values.

So I found that Hololens 2 has a resolution of 1440x960 and an aspect ratio of 3:2.

I set up those numbers but the result wasn't the expected, I couldn't see anything on the Hololens, so probably I am misunderstanding something

So my question is:

What would be a pos z, width, height and scale of a world space canvas that fits 100% the Hololens2 field of view?

Note: I understand that pos-z is from camera and scale and pos-z are correlated

Thank you

## Expected behavior
The canvas fills 100% the hololens2 field of view
## Actual behavior
The canvas is much more higher that I expected

![image](https://user-images.githubusercontent.com/25863696/201707518-eb400199-49c7-49e8-a60a-618e3c4ac18a.png)

## Unity editor version
2020.3.41
## Mixed Reality Toolkit release version
2.8.2.0

**Comment by Zee2** [comment]
Hi @maesla. You should not be using a canvas that perfectly fits the user's field of view. Headlocked content is strongly discouraged in immersive applicactions, and if the canvas is not headlocked, a piece of content large enough to fill the entire FOV will be nearly unusable the user moves around and shifts their perspective.

You should take a look at our example scenes under `UnityProjects/MRTKDevTemplate` for examples of how to author quality worldspace UI for XR. Our particular design system uses the following measurements:

- 0.001 scale on root canvas only: maps 1mm to 1 design unit (u)
- 32u x 32u basic unit for buttons/labels
- 8u text and up

These measurements are optimized for near touch with articulated hands.

**Comment by bonfry** [comment]
> Hi @Maesla. You should not be using a canvas that perfectly fits the user's field of view. Headlocked content is strongly discouraged in immersive applicactions, and if the canvas is not headlocked, a piece of content large enough to fill the entire FOV will be nearly unusable the user moves around and shifts their perspective.
> 
> You should take a look at our example scenes under `UnityProjects/MRTKDevTemplate` for examples of how to author quality worldspace UI for XR. Our particular design system uses the following measurements:
> 
> * 0.001 scale on root canvas only: maps 1mm to 1 design unit (u)
> * 32u x 32u basic unit for buttons/labels
> * 8u text and up
> 
> These measurements are optimized for near touch with articulated hands.

Is there a reference for MRTK2? Thanks

**Comment by Maesla** [comment]
> Hi @Maesla. You should not be using a canvas that perfectly fits the user's field of view. Headlocked content is strongly discouraged in immersive applicactions, and if the canvas is not headlocked, a piece of content large enough to fill the entire FOV will be nearly unusable the user moves around and shifts their perspective.
> 
> You should take a look at our example scenes under `UnityProjects/MRTKDevTemplate` for examples of how to author quality worldspace UI for XR. Our particular design system uses the following measurements:
> 
> * 0.001 scale on root canvas only: maps 1mm to 1 design unit (u)
> * 32u x 32u basic unit for buttons/labels
> * 8u text and up
> 
> These measurements are optimized for near touch with articulated hands.

Hi @Zee2 , thank you for your answer.

I agree that a full headlocked canvas is not the best approach, BUT.
It's another tool in the toolbox. For instance, I wanted it because I want to show a watermark at bottom-left with the number version so the QA can have information about the version for their reports, and I want to make it as little intrusive as possible.
I know that MRTK Visual Profiler uses Text Mesh for these things.

Others applications could be showing full HUDs, or color filters.
![image](https://user-images.githubusercontent.com/25863696/202698132-62f16f43-72b2-4863-a895-6e43db397d4c.png)
![image](https://user-images.githubusercontent.com/25863696/202698326-7a461216-e418-429e-b907-00cc7a12b559.png)

So I think you are right as a common guideline, but I think enabling full canvas in UI space could be a very handy tool to have.

Thanks
