### ISSUE TITLE
UX Migration Documentation for MRTK2 to MRTK3

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#11216]
UX Migration Documentation for MRTK2 to MRTK3

**Comment by marlenaklein-msft** [comment]
Here is [MRTK2 UX Documentation](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/ux-building-blocks/app-bar?view=mrtkunity-2022-05). Currently no UX migration documentation.

**Comment by marlenaklein-msft** [comment]
[Migration Documentation](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/architecture/mrtk-v2-to-v3)
