### ISSUE TITLE
Snapdragon Spaces Hand Tracking in MRTK3

### ISSUE THREAD

**Issue by astaikos316** [microsoft/MixedRealityToolkit-Unity#11210]
Has anyone else tried taking a look at how to get Spaces Hand Tracking fully working with MRTK3?  I have gotten grabbing objects working but I have not been able to get near and far UX interactions to work at all.  Anyone have some ideas or would like to work through some of the challenges with me?

**Comment by Zee2** [comment]
Hi @astaikos316! There are a few bugs in the Spaces runtime that are preventing our interactions from fully lighting up properly. The issues we're currently working on with the Qualcomm team are

- The Qualcomm runtime reports that it supports the `XR_MSFT_hand_tracking_mesh` extension when it does not actually do so. Our MR OpenXR plugin will attempt to initialize this extension and then crash.
- The Qualcomm phone controller reports that it implements the Microsoft Mixed Reality Motion Controller Profile, which is inaccurate as it does not represent a particular handedness of a controller. This will cause the phone controller device to interfere with the interactions associated with a particular tracked hand. The workaround for this is to remove support for any motion controller profiles in your XR settings.

We're actively collaborating with the engineers over on the Spaces team to improve this situation.
