### ISSUE TITLE
Rigged Hand Shapes and Animation

### ISSUE THREAD

**Issue by MehdiViper** [microsoft/MixedRealityToolkit-Unity#11211]
## Overview
I'm using MRTK3 with HTC Vive, when I press trigger button corresponding hand will have fist shape, or some other shapes while pressing grip button. I want to know how they are working under the hood, I want to add custom shapes when interacting with different intractable. 
How can I do this? 

Which subsystem or class has hand shaping duty? 

Thank you in advance 🙏🏻
## Unity editor version
2021.3.13 LTS 

## Mixed Reality Toolkit release version
MRTK3 pre.12

**Comment by Zee2** [comment]
Hi there, these hand shapes are driven directly from the underlying platform. MRTK3 does not currently support custom hand shapes for interactions on controllers. If you'd like to look into implementing your own, check out the `HandsSubsystem` definition where you can create your own hand data "provider".

**Comment by Zee2** [comment]
For more context; the synthetic hands subsystem is what drives the hand shapes in-editor during hand simulation, and you would probably be able to pattern your own subsystem after that.

**Comment by MehdiViper** [comment]
> 

Is there any chance that hand shape will be added to MRTK3?

**Comment by Zee2** [comment]
Hand shapes are supported in simulation, but we don't currently have interactable-specific hand shapes on the roadmap. This is mostly due to our focus on AR and MR platforms where your physical hand is visible. We welcome community packages for this functionality though!
