### ISSUE TITLE
Create a MRFT ready way to ingest the latest MRTK3 improvements

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#11224]
Tracking an MRTK3 distribution improvement to get the latest improvements as they are accepted into the main repository.

**Comment by Zee2** [comment]
I.e., nightlies in MRFT

**Comment by AMollis** [comment]
Unclear what the work was here.   

Also, we are investigating better ways to deliver MR unity packages, without the need for a standalone feature tool

**Comment by keveleigh** [comment]
> Unclear what the work was here.

We were thinking about how to easily distribute regular preview builds, like nightlies, in a reasonable and discoverable way, to get the latest changes from the repo out to the world quickly.
