### ISSUE TITLE
Environment Package shows up in Mixed Reality Feature Tool

### ISSUE THREAD

**Issue by Victor-x1** [microsoft/MixedRealityToolkit-Unity#11227]
![mrtk3](https://user-images.githubusercontent.com/44679314/202867694-a9557fd6-9708-46ba-aca6-7de85a2478b2.jpg)

The MRTK3 environment package was removed in pre12, but still shows up in the Mixed Reality Feature Tool under MRTK3.  Maybe there should be a Warning in Project Validation to show that its depreciated, and should be removed from Project. 

[MRTK3 Pre12 Changelog](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/changelogs/mrtk3-pre-12-changelog)
`We've removed the environment package. We recommend using Unity's built-in support for playspace boundary queries instead, as well as ARFoundation's ARMeshManager for scene reconstruction.`

**Comment by davidkline-ms** [comment]
i can deprecate the package on the feed. that will hide it from the MRFT UI by default (customers who need it can unhide deprecated packages in settings)

**Comment by Victor-x1** [comment]
That's perfect! Thank you so much.

**Comment by davidkline-ms** [comment]
Done :smile:

<img width="314" alt="image" src="https://user-images.githubusercontent.com/13281406/204940591-da6e94ee-09fe-49c2-b82b-0e2b107dfaac.png">
