### ISSUE TITLE
Have the cursor icon change for spatial manipulation controls [MRTK3]

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#11221]
The MRTK3 cursors do not change to different icons when using spatial manipulation controls. This issue tracks adding custom cursor icons during these key scenarios.

Example include:

Showing a resize or rotate control when a cursor is over a bounding box affordance
Showing a translation icon when cursor is hovering over a moveable object.

**Comment by RogPodge** [comment]
Currently blocked by the XRI implementation. Currently, interactables aren't allowed to modify the custom cursor before it is attached to the interactable hovering over it, without reimplementing the XRBaseInteractable's caching system. This interferes with our ability to change and orient the icon of a bounds control handle relative to the center of the bounds control itself.

We really need to bring this up to the XRI team ASAP to be unblocked on our implementation.

**Comment by keveleigh** [comment]
Reopening and marking as blocked

**Comment by marlenaklein-msft** [comment]
Closing with #11603.
