### ISSUE TITLE
Oculus integration breaks holographic Remoting for playmode 

### ISSUE THREAD

**Issue by ttkrpink** [microsoft/MixedRealityToolkit-Unity#11226]
Mixed Reality OpenXR Plugin, 1.6.0
MRTK, 2.8.2
Oculus Integration, 46.0.0
Unity 2020.3.50f1c1

Before Oculus Integration is installed, holographic remoting works as expected. I can see hololens2 in playmode. Once Oculus Integration is installed, Hololens shows "Receiving..." and the game view is stuck.

Be sure to commit before oculus, once it's installed, it can not be uninstalled.

Thanks for your help.

**Comment by satyapoojasama** [comment]
Hi @ttkrpink, thank you for reporting this bug. Couple of things to confirm here:
- May I get a screenshot of your "PlayerSettings-> XR Plug-in Management" on Unity after installing Oculus integration?
- Also, wondering if Holographic Playmode Remoting is enabled after oculus integration?

I did try and repro this bug on my end but couldn't repro it. So, if you can provide Unity Editor log and [ETL traces](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/wiki/Troubleshooting-for-developers#capture-a-diagnostics-trace-from-the-command-line) when this happens, it will help me diagnose this a bit better.

**Comment by ttkrpink** [comment]
> Hi @ttkrpink, thank you for reporting this bug. Couple of things to confirm here:

Thanks for your response. The following figures are: settings before and after Oculus, Screen capture before and after oculus, and video capture after oculus. The scene is not changed. From the figure and video, you can see the "Receiving..." is showing in the middle of the screen. 

The ETL file is from the Hololens2, I changed the extension from ETL to TXT so I can upload the file.

Thanks for your help.


![Before Oculus](https://user-images.githubusercontent.com/2522889/203720040-d928ed10-7b75-4453-887a-a510bc7bad20.PNG)
![After Oculus](https://user-images.githubusercontent.com/2522889/203720058-971cff2c-2b6f-4355-9ec2-ab968ce0af22.PNG)

![20221124_150056_HoloLens](https://user-images.githubusercontent.com/2522889/203719227-70c63e33-2b28-4b2d-a7b8-5e9ef0a552b6.jpg)

![20221124_151724_HoloLens](https://user-images.githubusercontent.com/2522889/203719260-5fc0e5cc-f0df-428e-b4be-50d7a91bb370.jpg)

https://user-images.githubusercontent.com/2522889/203719568-fe5dca90-db32-4050-9ca5-6049ddb369e4.mp4

[EtwTrace-2022-11-24-15-22-52.txt](https://github.com/microsoft/MixedRealityToolkit-Unity/files/10081674/EtwTrace-2022-11-24-15-22-52.txt)

**Comment by satyapoojasama** [comment]
Thank you for the details @ttkrpink. This looks good to me. Although, I will need ETL trace on the PC (not on HoloLens2) as the app is actually running on the PC. Those traces would really help. Thanks again.

**Comment by satyapoojasama** [comment]
Hi @ttkrpink, can you please provide ETL traces from your PC and not from your HL2??

**Comment by ttkrpink** [comment]
> Hi @ttkrpink, can you please provide ETL traces from your PC and not from your HL2??

sorry， I am away from my office since lastweek. I will get the etl files late next week. thanks for your help

**Comment by ttkrpink** [comment]
ETL files before and after oculus are uploaded. Please rename them from txt to etl.
[MPR_After_Oculus.txt](https://github.com/microsoft/MixedRealityToolkit-Unity/files/10152413/MPR_After_Oculus.txt)
[MPR_Before_Oculus.txt](https://github.com/microsoft/MixedRealityToolkit-Unity/files/10152414/MPR_Before_Oculus.txt)

**Comment by devdeeprc** [comment]
Hi @ttkrpink it seems that the Oculus package is setting the environment blend mode to something that is not supported by HoloLens 2 and hence the remoting breaks. At this point, the only workaround available is to uncheck the Oculus integration feature while using remoting.

**Comment by ttkrpink** [comment]
> Hi @ttkrpink it seems that the Oculus package is setting the environment blend mode to something that is not supported by HoloLens 2 and hence the remoting breaks. At this point, the only workaround available is to uncheck the Oculus integration feature while using remoting.

Thanks for working on this issue. Your workaround solution works fine.
