### ISSUE TITLE
Unit tests for MRTK3 Solvers

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#11220]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/224

___

Tracks creating new unit tests for MRTK3 solvers

**Comment by srinjoym** [comment]
Started some of this work with an initial set of tests for the `SolverHandler` script in this PR #11441

**Comment by AMollis** [comment]
The MRTK3 Solver system will be replaced with a new Transformation system.    Given this, unit tests for the older Solver system are less of a priority. We will continue to create new unit tests for Slovers if their are bug fixes in the area.
