### ISSUE TITLE
Create a pipeline to easily create and deploy consistent stable MRTK3 drops with Semantic Versioning

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#11225]
Tracks a high level task to improve and create a predictable, easy way of creating stable MRTK3 drops which following Semantic Versioning.

[https://semver.org/spec/v2.0.0.html](https://semver.org/spec/v2.0.0.html
)

- [ ] Per package versioning  Major.Minor.Patch[.AdoBuildNumber]

**Comment by AMollis** [comment]
The solution here should work with the CI pipleine


This might be covered withhttps://github.com/microsoft/MixedRealityToolkit-Unity/issues/11078 and https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11225. Needs more investigation to understand what the requirements were here.

https://semver.org/spec/v2.0.0.html

**Comment by AMollis** [comment]
Work has been completed
