### ISSUE TITLE
Load appropriate interaction profile on device detection

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#11222]
Tracking work that is being done on the platform level to ensure that the correct interaction profile is loaded when a device is detected (i.e., is the device that appeared a motion controller, a hand, a motion controller with hand tracking, etc.)

**Comment by AMollis** [comment]
@RogPodge we aren't clear what the issue is here.   Closing the issue for now. If you have more information that can help, please post here and we'll re-open the issue.
