### ISSUE TITLE
SolverExamples Example Scene from Documentation missing in MRTK3 Repo

### ISSUE THREAD

**Issue by Victor-x1** [microsoft/MixedRealityToolkit-Unity#11232]
## Describe the issue
The MRTK3 Documentation mentions a SolverExamples.scene file but no file exists in the MRTK3 repo. 

## Feature area
There is no SolverExamples.* file in the MRTK3 Dev Template or MRTK3 Repo. 

## Existing doc link
[Solvers — MRTK3](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-spatialmanipulation/packages/spatialmanipulation/solvers/solver)

## Additional context
Documentation Text:
`Examples of how to use the Solvers system can be found in the SolverExamples.scene file.`

File below is also missing from MRTK3 repo:

`Directional Indicator Example Scene (Assets/MRTK/Examples/Demos/Solvers/Scenes/DirectionalIndicatorSolverExample.unity`

**Comment by Zee2** [comment]
Hi, thanks for calling this out. We're currently overhauling the solvers/constraints system so there might be some inconsistencies. I'll keep this ticket open to track docs improvements once that overhaul comes out.

**Comment by Zee2** [comment]
Blocking this issue on the completion of revised Solvers/Constraints architecture.

**Comment by marlenaklein-msft** [comment]
SolverExamples scene added in #11522.
