### ISSUE TITLE
[MRTK 2.8.3 Build Call] Quest 2 device specific graphical issue

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#11237]
## Describe the bug

A semi-transparent white outline is seen on most windows at various spots, currently unsure what the trigger is. 

Sometimes the outline is constant, other times it seems to change based on the users position or controller position

## To reproduce

Enter any of the MRTK2 examples with the Example Hub, and interact with examples as you normally would

## Expected behavior

There is no graphical outline

## Screenshots

![com Microsoft MixedReality Toolkit-20221122-125722](https://user-images.githubusercontent.com/110259320/203414533-0946b9e6-4d81-4dfe-b154-43305979a0e7.jpg)

## Your setup (please complete the following information)

- Unity Version 2020.3.39f1
- MRTK Version 2.8.3 Build Call

## Target platform (please complete the following information)

- Quest 2

## Additional context

Not seen on Hololens 2 testing

**Comment by Clandguth** [comment]
Issue was resolved with gamma color space, and selecting auto graphics API.
![image](https://user-images.githubusercontent.com/110259320/203621758-70fa4103-4354-4f54-96d6-0e83d8b647fa.png)

**Comment by keveleigh** [comment]
@RogPodge @Clandguth Should we add something to our docs about Gamma being the only supported (or recommended?) color space for Quest 2?

**Comment by RogPodge** [comment]
> @RogPodge @Clandguth Should we add something to our docs about Gamma being the only supported (or recommended?) color space for Quest 2?

I think so yeah, made an issue for MRTK3: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11258

**Comment by MaxWang-MS** [comment]
We should call this out for MRTK2 as well.
