### ISSUE TITLE
Why have SingleInstance?

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1123]
Only difference between `SingleInstance` and `Singleton` is that it doesn't depend on the instance being set in `Awake`. 

What's the benefit?

I propose removing `SingleInstance` and replacing its usage with `Singleton`.

**Comment by keveleigh** [comment]
The benefit is that a dev can reference a SingleInstance anywhere in code, without the Awake restriction. This is the way Singleton used to be, and there are devs who prefer that pattern. See #1039, for example.

**Comment by StephenHodgson** [comment]
How is `Awake` a restriction?

**Comment by keveleigh** [comment]
It's a restriction because I can't reference a Singleton in any Awake function with the guarantee that it exists yet.

**Comment by StephenHodgson** [comment]
Hmm, so then we should replace `Singleton` with `SingleInstance`?

**Comment by keveleigh** [comment]
I personally think we should, but others disagree, as seen in the other issue referenced above and the fact that it was changed in the first place.

There's also some discussion from @darax about the two at the bottom of #486 (along with the rest of the thread discussing `Singleton`, some of which seems to have been fixed already).

**Comment by StephenHodgson** [comment]
I agree. My only goal here is to reduce the amount of complexity and redundancy.

**Comment by darax** [comment]
I was disappointed last year when I discovered that the HoloToolkit singleton was changed.  There were a cascade of issues that were created by making that change, discovered slowly over time.  While creating MR250, I uncovered more scripts that didn't fully comply with the new behavior.  I also frequently find myself wanting to access a singleton during an Awake() function.

I had a choice: 
1. Revert singleton to its old behavior. 
2. Create a new singleton like class with the old behavior. 
3. Fix the scripts that weren't 'complying' and fully comply myself

In order to avoid breaking a bunch of scripts that might rely on the new behavior, I chose option 2. I agree it is sub optimal to have two 'singleton' classes, and maybe I should have picked option 3.  I simply couldn't bring myself to do it.

**Comment by StephenHodgson** [comment]
I could look into this and see if I can get the classes to work with the current Singleton.

In the meantime, this issue does indeed come up often.

https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1031#issuecomment-333630887

>I think the biggest part of the problem is that we're attaching instances to GameObjects in the first place.
>
>Ideally these instances should live on their own and not be tied to such things, but alas this is Unity, and in order to have a script run it needs to be a Component that you've got to attach to a GameObject that has to be enabled in your scene.
>
>It's a spit in the traditional paradigm of how software engineers usually treat programming, and is usually one of the biggest gripes traditional software engineers have with using Unity.

**Comment by darax** [comment]
Both approaches fall apart if the game object is disabled. I would much rather use the approach in SingleInstance because it is simpler and sets fewer traps.

**Comment by StephenHodgson** [comment]
Awake does not get called for disabled GameObjects.

**Comment by timGerken** [comment]
In the event the SingleInstance is on a disabled game object (to start with), Awake should allow for finding zero instances (without spamming the console window).

**Comment by StephenHodgson** [comment]
Well this is annoying as well.  Apparently `OnEnable` or even `Start` could be called before other `GameObjects` `Awake` call.

http://answers.unity3d.com/questions/1081660/onenable-called-before-awake.html

**Comment by StephenHodgson** [comment]
@timGerken btw if you don't wanna spam the console but still check if the Instance is valid you can always call `AssertIsInitialized` or `IsInitialized` before calling the actual `Instance`

**Comment by timGerken** [comment]
`OnEnable` may not be safe, but I'm pretty sure `Start` is.

[MonoBehaviour.Start](https://docs.unity3d.com/ScriptReference/MonoBehaviour.Start.html)

> The Awake function is called on all objects in the scene before any object's Start function is called. This fact is useful in cases where object A's initialisation code needs to rely on object B's already being initialised; B's initialisation should be done in Awake while A's should be done in Start.

**Comment by StephenHodgson** [comment]
Nope. `Start` is also not safe.  Remember this is called on a _per GameObject basis_.

**Comment by keveleigh** [comment]
Why is `Start` also not safe?

https://docs.unity3d.com/Manual/ExecutionOrder.html

> Note that for objects added to the scene, the Awake and OnEnable functions for all scripts will be called before Start

**Comment by StephenHodgson** [comment]
> Why is Start also not safe?

Because each of the Unity APIs are called on a per object basis, and even though one object's `Start` function has been called, another object may still get their `Awake` called much later.

That specific link does call out `Awake` but it's easy to search for other examples.

**Comment by timGerken** [comment]
The documentation for Start clearly says that Awake is called *for all objects in the scene* _before_ any object's Start method is called.

**Comment by keveleigh** [comment]
> even though one object's Start function has been called, another object may still get their Awake called much later.

That statement is only true for objects instantiated during runtime.

**Comment by StephenHodgson** [comment]
I think we should write a test to make a definitive statement.

**Comment by StephenHodgson** [comment]
> The documentation for Start clearly says that Awake is called for all objects in the scene before any object's Start method is called.

Yeah this _should_ be the case, but it doesn't actually seem to be if we're getting scripts `OnEnable` and `Start` functions called anyway.

**Comment by StephenHodgson** [comment]
Oh I see, `Awake` and `OnEnable` always get called before `Start`.

So potentially one scripts `Awake` and another's `OnEnable` could be but not their `Start` functions.

**Comment by StephenHodgson** [comment]
Okay so how come we don't assign an Instance if we don't find one like in @timGerken's lastest change to `SingleInstance`?

Was there a reason for this?

```
        private static T _Instance;
        public static T Instance
        {
            get
            {
                if (_Instance == null)
                {
                    T[] objects = FindObjectsOfType<T>();
                    if (objects.Length == 1)
                    {
                        _Instance = objects[0];
                    }
                    else if (objects.Length > 1)
                    {
                        Debug.LogErrorFormat("Expected exactly 1 {0} but found {1}", typeof(T).ToString(), objects.Length);
                    }
                }
                return _Instance;
            }
        }
```

**Comment by timGerken** [comment]
Yes, because the SingleInstance object may be on a gameobject that is disabled at scene load time. If that's the case, you'd expect instance to be null and want to do a null check without spamming the console.

**Comment by StephenHodgson** [comment]
I understand why you changed it, I just want to know why we don't apply to changes to `Singletion`

**Comment by timGerken** [comment]
We probably should.

**Comment by StephenHodgson** [comment]
I'm just trying to remove a largely duplicated class, that essentially does the same thing.

**Comment by StephenHodgson** [comment]
We can keep the `Awake` assignment, but still do the more expensive `FindObjectsOfType<T>();` if our instance is `null`.

**Comment by StephenHodgson** [comment]
What if we move away from using the Singleton pattern?

**Comment by darax** [comment]
We will (or at least I will) still want to have a convenient way to create globally accessible app state. That will probably carry with it the same lifetime problems under a different name.

The concern about FindObjectsOfType<T> being expensive is valid when someone calls .Instance frequently when the object is either not in the scene or disabled. I wonder if we could, instead, document the performance drawback of frequently polling for an instance to become available. Or we could rename SingleInstance to Singleton and Singleton to PollableSingleton.

**Comment by StephenHodgson** [comment]
It's only expensive if `FindObjectsOfType` doesn't return anything each time, correct?

**Comment by StephenHodgson** [comment]
Could we also only have it call `FindObjectsOfType` once, and every subsequent time only return null unless `Awake` sets it?

**Comment by darax** [comment]
that would be okay.  So long as it is done in a way where if I forget to base.Awake() the only thing I lose is setting the instance.   base.Awake() will need to tolerate the instance being set from FindObjectByType<> .

**Comment by StephenHodgson** [comment]
Check out that PR and let me know your thoughts.

**Comment by darax** [comment]
that looks good.
