### ISSUE TITLE
What is the point of sharing anchors?

### ISSUE THREAD

**Issue by motionsmith** [Microsoft/MixedRealityToolkit-Unity#1124]
Hey guys,

There is so much great stuff here. We're doing some experiments with your Sharing namespace. I have a few architectural and/or philosophical questions to make sure that I'm not missing something.

We deployed SharingTest.unity which effectively syncs users' camera transforms. The head transforms are relative to a sphere hologram, which either IS or IS CONTAINED BY an "anchor".

I'm trying to understand what the point of "sharing" anchors (AKA uploading/downloading anchors) is. I understand what anchors are in HL's device coordinate system. However, in SharingTest, there is no shared coordinate system data, so each device's spheres are in different places. Likewise, when I move my sphere, that sphere doesn't move on the other clients' devices.

If two people are in the same room, a fiducial marker would effectively align the devices' coordinate systems by allowing the clients to adjust their holograms relative to the markers. I thought anchors would have something to do with that, but I don't see anything like that occuring in this demo.

Thanks, I'm sure I'm missing something.

Eric

**Comment by NeerajW** [comment]
The point of sharing an anchor is to that HoloLens1 shared their reference point coordinate with HoloLens2 can then localize to the same coordinate system. They have to be the same visual tracking points and physical space. You will have to write extra code to broadcast the location of the shared holograms when it's moving. You cannot move an object which has an anchor attached to it. You can move a hologram which is a child of an anchor.

Please reopen if your question was not answered.
