### ISSUE TITLE
[MRTK3]MinMax scale constraint for ObjectManipulator

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#11249]
There needs to be a MinMax scale constraint that easily integrates with the Object Manipulator in order to prevent microscopic or extremely large scale objects.

**Comment by srinjoym** [comment]
This is already supported in MRTK 3. Validated on device and there are docs here: https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-spatialmanipulation/packages/spatialmanipulation/constraint-manager#transform-constraints
