### ISSUE TITLE
[MRTK 3] Button inside Bound controlled object is not clickable on Oculus Rift S

### ISSUE THREAD

**Issue by genaray** [microsoft/MixedRealityToolkit-Unity#11240]
## Describe the bug

A MRTK Button as a child of a object manipulated and bound controlled gameobject is not interactable.
It looks like the rays are blocked. Not sure if this intended or not, however its extremely hard to combine objects while that issue persist.

In my case i want to have a moveable table with a button on it to execute an action.
Not possible since the button can not be interacted with. 

## To reproduce

1. Create Gameobject with ObjectManipulator, BoundsControl
2. Create a cube child Gameobject 
3. Create a PressableButton next to it
4. Run and see that the PressableButton can not be interacted with, the Bounds blocks any interactions with it

## Expected behavior

A Button should be interactable within a manipulated object. 

## Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/20269164/203583108-cd8dc7ea-b567-4660-b38b-44d4bf99a5b6.png)
"AirHockeyTable" is the root with ObjectManipulator and BoundsControl.
The child "Lock & Start" is a MRTK Button Prefab.
That one is not interactable. 

## Your setup (please complete the following information)

- Unity Version 2021.3.14f
- MRTK Version 3

## Target platform (please complete the following information)

- HoloLens 2
- Oculus Rift S

**Comment by Zee2** [comment]
This is easily fixed! Go into the base interactable settings on your objectmanipulator and button and make sure the collider is set manually. XRI tries to auto-detect the correct collider to associate with the interactable, but in cases with nested interactables, it can sometimes fail.
