### ISSUE TITLE
What are "rooms"?

### ISSUE THREAD

**Issue by motionsmith** [Microsoft/MixedRealityToolkit-Unity#1125]
Hey guys, another terminology question. :)

What is a "room"? I understand the concept of a "session" as essentially a collection of users who are communicating over a shared network. However, it looks like there is sometimes this thing called a "room" which is in a session. What is the purpose of a "room" that a "session" cannot accomplish? I don't see much documentation about "rooms" here on Github.

At this point, my best guess is that a session is terminologically equivalent to a "lobby" where everyone is on the same network, then a room would be a filter where you only get messages from people in the same room as you even though, technically, you may be connected to everyone in the session?

Thanks again,

Eric

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
