### ISSUE TITLE
MRTK3 iOS build, no camera support?

### ISSUE THREAD

**Issue by ttkrpink** [microsoft/MixedRealityToolkit-Unity#11293]
## Describe the problem

MRTK2, after switching to iOS, I almost don't have to change the scene camera setting. Once built on iOS devices, the scene shows with the camera on.
MRTK3, I did the same. But this time, the iOS does not even ask for camera permission. The scene contents show correctly but with a black background. And I can not rotate the iOS device to see the whole MR content.

## Describe the solution you'd like

As in MRTK2, the camera shows the environment as the AR contents' background.

If you get the camera working, could you please share the settings?

Thanks.

**Comment by Zee2** [comment]
Hey @ttkrpink, thanks for reporting. We'll take a look. We've done some evaluation for ARCore but not as much testing on ARKit. @keveleigh will have more to say.

**Comment by dudziakl** [comment]
@ttkrpink I think you are missing ARSession object and ARCameraBackground script attached to the camera. Check this instruction on how to setup the scene for the AR Foundation https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/manual/index.html#scene-setup

**Comment by Zee2** [comment]
@ttkrpink please let us know if you're still experiencing issues after following the scene setup details that @dudziakl shared. If there's still problems, please reopen the issue!
