### ISSUE TITLE
GLTF Throws warning at build time

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1129]
```
Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
warning CS4014: Assets\HoloToolkit\Utilities\Scripts\GLTF\Scripts\AsyncAction.cs(21,13)
```

**Comment by brean** [comment]
Right now my build fails because GLTF is not known. Do I need to download/install something?

**Comment by StephenHodgson** [comment]
What's your stats? Editor, windows version, visual studio version, sdkb version, etc?

**Comment by HattMarris1** [comment]
^I also have that problem

**Comment by brean** [comment]
> What's your stats?
- Unity 2017.1.1f1
-  .NET Scripting Backend
- Stable .NET 3.5 Scripting Runtime
- Windows 10.0.15063 Build 15063
- Visual Studio 2017 Version 15.4.0
- SDK 10.0.16299.0

**Comment by StephenHodgson** [comment]
Well, lots of reasons.

You're using the wrong editor version. You need 2017.2.0f2 MRTP
You're using the wrong version of Windows. You need the fall creators update build 1709

**Comment by HattMarris1** [comment]
Mine does this in the master branch, It's coming from MotionControllerVisualiser.cs

**Comment by StephenHodgson** [comment]
Please do. I'll take a look this morning.

**Comment by brean** [comment]
I am running the 1703, it is Version 1703 OS Build 15063.674. I will update my Unity. Btw. There is 2017.2.0f3 out as stable version. Can I update to that or does it have to be 2017.2.0f2 MRTP?

**Comment by StephenHodgson** [comment]
Idk, still need to check.

Btw, what branch are you using?

**Comment by brean** [comment]
master. Same as @HattMarris1 . When I comment out the "using GLTF" everything looks to work fine.

**Comment by brean** [comment]
I will install Unity 2017.2.0f3 because it is the default stable release and I can not find a download link to 0f2

**Comment by StephenHodgson** [comment]
Don't update your editor. You should be good.

Just don't use the 10.0.16299.0 SDK for 2017.1

**Comment by keveleigh** [comment]
I don't see this warning anymore when building. Please reopen if you're still able to repro.
