### ISSUE TITLE
Mixed Reality Feature Toolkit refreshing catalogue - not responding 

### ISSUE THREAD

**Issue by badguy-studios** [microsoft/MixedRealityToolkit-Unity#11305]
Running MRTK3 on an M1 Mac running Parallels VM with Windows 11. Trying to download the Figma-Unity bridge, but the Mixed Reality Feature Toolkit gets stuck on the "Refreshing catalogs" process and never moves on to the next step. 

<img width="802" alt="image" src="https://user-images.githubusercontent.com/83097003/208175558-b790a88e-b49d-4ecb-a5e2-2207166fea8f.png">

Is there another way to download the bridge?

**Comment by davidkline-ms** [comment]
@badguy-studios, thank you for the report. We have a few reports of issues running on an M1 Mac and are investigating.

**Comment by badguy-studios** [comment]
> 

thanks for the quick reply! Is there another way I can access the Figma-Unity bridge?

**Comment by davidkline-ms** [comment]
you can download the bridge manually (you will also need to import into your project via the Unity Package Manager manually as well) from https://dev.azure.com/aipmr/MixedReality-Unity-Packages/_artifacts/feed/Unity-packages

**Comment by badguy-studios** [comment]
Fantastic - thank you!!

**Comment by taskins1** [comment]
Today I have the same problem, was this fixed in any way? or did anybody find a better solution instead of adding them manually?
