### ISSUE TITLE
The mrtk_release broken

### ISSUE THREAD

**Issue by sergiosolorzano** [microsoft/MixedRealityToolkit-Unity#11304]
The [mrtk_release](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/mrtk_release) is broken

## Feature area
What's incorrect? What's missing?

## Existing doc link
If this is about something in an existing document, please provide link

**Comment by keveleigh** [comment]
Hello! Is there a link or something in the documentation that still refers to the mrtk_release branch? We removed it a while back in favor of individual version branches
![image](https://user-images.githubusercontent.com/3580640/208159908-0d86fee2-4eef-46b8-b24d-b4878c3a08fe.png)

**Comment by sergiosolorzano** [comment]
Ah I see, thank you!
