### ISSUE TITLE
MR OpenXR Plugin build processor does not run with new OpenXR Plugin "Meta Quest" feature

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#11302]
## Describe the bug

Now that the feature name for Quest support on the Unity OpenXR Plugin is "Meta Quest Support", the MR OpenXR plugin fails to run its build processor (as it is looking for the old name), and as a result the Android manifest does not include declarations of hand tracking support and breaks hands on Quest.

## To reproduce

Build app for Quest on latest MR OpenXR Plugin (1.6.0) and latest OpenXR Plugin (1.6.0). Observe Quest OS detects it as a non-hand-tracking app and does not allow any hand data through.

## Expected behavior

Hand tracking should work as expected.

## Your setup 

- MRTK3 latest
- MR OpenXR 1.6.0
- Unity OpenXR 1.6.0
- Quest

## Context

Should be fixed in upcoming MR OpenXR 1.7.0. Shouldn't block pre.13... probably...

**Comment by yl-msft** [comment]
@Zee2  let us know if 1.7 MR plugin solved this problem for you, and please close this issue once you validated.  Thanks!

**Comment by keveleigh** [comment]
Can confirm that this is fixed in my repro after #11303
