### ISSUE TITLE
Option for WebRTC (Microsoft Mesh?)

### ISSUE THREAD

**Issue by alexapropt** [microsoft/MixedRealityToolkit-Unity#11319]
After the deprecation of WebRTC, we don't have an efficient option to create stream-oriented communication. Any chance of sharing within MRTK3 a package that would help us?

**Comment by Zee2** [comment]
Hi @alexapropt, unfortunately we don't have anything to share at this time. If you're looking for some examples of basic multiplayer functionality, I have a toy repo set up here (https://github.com/Zee2/MRTK3-Netcode) that demonstrates using the new Netcode for GameObjects API. It's not a generic stream-oriented communication protocol, but they've done a good job making it relatively easy to setup and understand.

Of course, the other standard Unity options like Photon, Steamworks.NET are all good too.

Sorry we don't have anything more to offer right now.

**Comment by Zee2** [comment]
If and when we do have anything to share, we'll reopen this with more details.
