### ISSUE TITLE
UI Toolkit compatibility and Volumetric UI

### ISSUE THREAD

**Issue by TheXRMonk** [microsoft/MixedRealityToolkit-Unity#11310]
Volumetric UI is one of the greatest improvements from MRTK 2 to MRTK 3, but UGUI is starting to be left behind.

Unity's "UI Toolkit" is the future. 

I know this may be premature, especially as world space rendering isn't even (officially) supported yet.
But... are there any plans for supporting UI Toolkit?

We are especially interested, as our UI would be used across different devices (also non-XR), and our customer's industry has strict accessibility requirements to flat-screen experiences, and it seems like unity's strategy is to only support screen readers on UI Toolkit - something that is not supported by UGUI.

**Comment by Zee2** [comment]
Hey @TheXRMonk, we really wanted to pursue UI Toolkit, but even Unity themselves said they had no intention of officially supporting worldspace UI anytime soon, and they also have no intention of supporting actual volumetric/3D UI with UI Toolkit at any point in the future. They also don't currently recommend using it for in-game UI yet.

If and when Unity ever supports 3D UI with UI Toolkit, we'll take a look, but until then it is not usable for our use cases.

**Comment by keveleigh** [comment]
> and it seems like unity's strategy is to only support screen readers on UI Toolkit - something that is not supported by UGUI.

This is a very interesting piece of information. FYI @davidkline-ms for accessibility investigations.

**Comment by TheXRMonk** [comment]
> > and it seems like unity's strategy is to only support screen readers on UI Toolkit - something that is not supported by UGUI.
> 
> This is a very interesting piece of information. FYI @davidkline-ms for accessibility investigations.
I got this information from the Unity roadmap. It's under planned; 
![image](https://user-images.githubusercontent.com/54309738/208858015-90aaea99-cd50-4acc-aef1-a452e0dbf6e7.png)

While this is in progress;
![image](https://user-images.githubusercontent.com/54309738/208858210-0fc659ee-9e7e-4cad-844e-1678fa4abad2.png)

source; https://unity.com/roadmap/unity-platform/ui

**Comment by keveleigh** [comment]
Thanks for the link! Much appreciated

**Comment by davidkline-ms** [comment]
> > and it seems like unity's strategy is to only support screen readers on UI Toolkit - something that is not supported by UGUI.
> 
> This is a very interesting piece of information. FYI @davidkline-ms for accessibility investigations.

I have periodic meetings with Unity re: their accessibility plans. In addition, I am investigating adding a self-voiced screen reader to MRTK that can be used 1) in places where Unity's solution does not support the scenario, 2) to add additional features (ex: spatialized screen reading), 3) for consistency across platforms, etc.

**Comment by TheXRMonk** [comment]
> > > and it seems like unity's strategy is to only support screen readers on UI Toolkit - something that is not supported by UGUI.
> > 
> > 
> > This is a very interesting piece of information. FYI @davidkline-ms for accessibility investigations.
> 
> I have periodic meetings with Unity re: their accessibility plans. In addition, I am investigating adding a self-voiced screen reader to MRTK that can be used 1) in places where Unity's solution does not support the scenario, 2) to add additional features (ex: spatialized screen reading), 3) for consistency across platforms, etc.

So with "self-voiced" I'm guessing you mean something like; https://github.com/mikrima/UnityAccessibilityPlugin ? 
Apple has released a package for unity that hooks into VoiceOver, which has similar approach to UAP (decorating UI game objects for building the semantic tree).
