### ISSUE TITLE
Right-clicking on the test names in Unity's Test Runner and clicking "Open source code" doesn't work

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#11327]
## Describe the bug

![image](https://user-images.githubusercontent.com/3580640/209714561-8db78b83-3762-4932-a476-c8505f9b977e.png)

![image](https://user-images.githubusercontent.com/3580640/209714551-bd1df2d4-e504-4c8f-bae2-03a516ffeb95.png)

**Comment by keveleigh** [comment]
Looks like Unity's Input System tests suffer from this too, so it's not just us 😅

**Comment by keveleigh** [comment]
On further investigation, it looks like this feature might just be bugged for `[UnityTest]`s. It seems to work for `[Test]`s

**Comment by Zee2** [comment]
This has literally always been the case for me since I can remember. Has never worked properly for me (I believe also in MRTK v2)

**Comment by keveleigh** [comment]
Ah dang, okay! I'll go ahead and close this out as External
