### ISSUE TITLE
Enabling Motion Controller Model in MRTK3 with Quest freezes app

### ISSUE THREAD

**Issue by mmoerman** [microsoft/MixedRealityToolkit-Unity#11337]
## Describe the bug

Whenever I enable "Motion Controller Model" in trhe OpenXR Features group the MR app freezes when I start it  on a Quest 2.

## To reproduce

- Setup MRTK3 project (can be any project, you can use the MRTKDevTemplate examples for this), with OpenXR
-  Import Oculus Interaction Toolkit and enable its OpenXR component. (Note that if I disable the OpenXR component behaviour is still the same)
- In OpenXR feature groups enable following
    - Hand Tracking
    - Oculus Quest Support
- Us the default MRTK3 profile with the following sub-systems enabled
    - Accessibility
    - Hands Aggregator
    - OpenXR Hands API
    - Hand Synthesis

Import KTX (2.2.3) and glTFast (5.0.0) as per the validation requirements (I understand this is required to be able to import the controller models from Oculus Interaction Toolkit). 

When I Build and run the APK on a Quest 2 this way everything works fine.
When I enable the Motion Controller Model under the OpenXR Feature Group, and build and run the APK on a Quest 2 the App freezes right after startup, it shows 2 beams that should shoot out of the controllers and freezes.

## Expected behavior

The 3D Model fo the Quest 2 controllers should load and bne shown in the app and the app should not freeze.

## Screenshots

App is frozen so screenshot is fairly useless.

## Your setup (please complete the following information)

- Unity Version - 2021.3.16f1
- MRTK Version 3 pre12
- Windows 10

## Target platform (please complete the following information)

- Oculus Quest 2 
- OpenXR

**Comment by RogPodge** [comment]
Are there any specific logs are you able to pull from the crash itself? In your configuration, you noted that in the OpenXR feature groups, you enabled
- Oculus Quest Support

This feature is not one that's included in our one that comes from the Mixed Reality Open XR plugin, and I suspect it's coming from the Oculus Interaction Toolkit. What might be happening is that these 2 features (Oculus Quest Support, Motion Controller Model) are coming into conflict, but I would need more information and access to the code that each is using to get a better idea.

@keveleigh  since these are OpenXR features.

**Comment by keveleigh** [comment]
@mmoerman

> Import KTX (2.2.3) and glTFast (5.0.0)

Can you give an older version of glTFast a try please? We've been testing on 4.7.0. I wonder if there are any breaking changes in the 5.0.0 release that cause us problems.

**Comment by seosukhyun** [comment]
> 

I had a same problem with controller visualization.
After downgrade glTFast & KTX, it fixed. 
It seems have problems with recent version.
Thanks

**Comment by mmoerman** [comment]
> @mmoerman
> 
> > Import KTX (2.2.3) and glTFast (5.0.0)
> 
> Can you give an older version of glTFast a try please? We've been testing on 4.7.0 (and KTX 2.1.2). I wonder if there are any breaking changes in the 5.0.0 release that cause us problems.

Downgrading to these versions of KTX and glTFast worked, thank you for your help.
