### ISSUE TITLE
Pinky joints when using rigged hand mesh on Leap Motion needs investigation

### ISSUE THREAD

**Issue by graceCode100** [microsoft/MixedRealityToolkit-Unity#11341]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/201

___

## Describe the bug

User feedback: Pinky joints in the rigged hand mesh behave weirdly when using Leap Motion. Needs further investigation to determine if resolved.

**Comment by Zee2** [comment]
This is due to some joint alignment weirdness in the hand model we're using. The pinky joint is a little bit crooked for some reason. I can take another look at our mesh and try and un-kink the pinky joint.
