### ISSUE TITLE
Will TAP support(4.6 subset) be a standard in 2017.2 branch ?

### ISSUE THREAD

**Issue by waynebaby** [Microsoft/MixedRealityToolkit-Unity#1134]
TAP is good.  I am ready to push some code  for MRTK, to enable developer call UWP API much easier.

The code will like what i have witten in  
https://blogs.msdn.microsoft.com/appconsult/2017/09/01/unity-coroutine-tap-en-us/

But I cannot submit any code until  this project is ready for 4.6 subset.

Is there any plan about updating everything to 4.6?  

Thanks

Wayne

**Comment by StephenHodgson** [comment]
Both the master and dev branches are both already targeting .NET 4.6

**Comment by waynebaby** [comment]
@StephenHodgson  

So i cannot add my code in current version. 

Is there a conditinal compile symble for 4.6 “scripting runtime version”?   
I cannot find it in https://docs.unity3d.com/Manual/PlatformDependentCompilation.html

Thanks


Wayne

**Comment by StephenHodgson** [comment]
Player Settings/Scripting Runtime Version

![image](https://user-images.githubusercontent.com/13334553/31557577-3cacdb4e-affe-11e7-8b69-273a0b2c503f.png)

**Comment by waynebaby** [comment]
@StephenHodgson  by “ conditinal compile symble”  I mean if i can use “#if UNITY_EDITOR”  liked lines in cs file.

I will take it as there is no such symbol yet.  


Thanks

**Comment by StephenHodgson** [comment]
I'm not sure why a conditional compile symbol is needed.

**Comment by waynebaby** [comment]
@StephenHodgson 

If i am uploading some code with async await, 3.5 subset would crash in the editor.  

if i add a conditional compile symbol, the ones who use 4.6 subset could be benefited by those async await code.

**Comment by StephenHodgson** [comment]
Unsure if we need to add compile symbols for this. 

I'm fairly certain you can check which scripting level you're running and handle it accordingly. 

```
PlayerSettings.GetApiCompatibilityLevel(BuildTargetGroup.WSA);
```

**Comment by waynebaby** [comment]
but async n await keywords are compiler level,   a logic if will not bypass a compile level error...

**Comment by StephenHodgson** [comment]
Good point.  We could show a dialog that prompts users to update their api level.

**Comment by davidkline-ms** [comment]
The vNext branch is going to move to .NET 4.6 support
