### ISSUE TITLE
Splash image is not set when tracking is lost in hololens

### ISSUE THREAD

**Issue by hemasree99s** [microsoft/MixedRealityToolkit-Unity#11340]
## Describe the bug

Splash image is not set when tracking is lost in Hololens
## To reproduce

Followed this link - https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/extensions/lost-tracking-service?view=mrtkunity-2022-05

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.3.20f1]
- MRTK Version [e.g. v2.7.3]

## Target platform (please complete the following information)

- HoloLens 2
- OpenXR

**Comment by hemasree99s** [comment]
@CDiaz-MS @vtieto @qianw211

**Comment by keveleigh** [comment]
Ah hmm. Are you using the Mixed Reality OpenXR Plugin? Also, do you have an AR Session in the scene?

**Comment by hemasree99s** [comment]
![image](https://user-images.githubusercontent.com/47776870/210764765-ae8915da-b523-4368-993a-0b31a6b07345.png)
We are using OpenXR plugin. AR session is present as specified in above image.

Also tried the same in unity 2021.3.16f1 and MRTK 2.8.3.

Hope, we should disable  On Tracking loss and pause and show image in setting ?

**Comment by keveleigh** [comment]
Ahh hmm. In your screenshot I see an AR Session Origin, but AR Session is a different component:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/3580640/211908529-7c4741ef-5cc8-4f8c-9db4-0d4afd5b1739.png">

Can you try adding that to your scene and seeing what happens?

**Comment by hemasree99s** [comment]
Issue exists with the above approach too

**Comment by siamonas** [comment]
@hemasree99s @keveleigh I had the same problem. After some debugging, I found that the `sessionSubsystem.trackingState` in the Update() function of LostTrackingService.cs was only returning Tracking and Limited.

So I changed the following if statement from:
`if (sessionSubsystem.trackingState == UnityEngine.XR.ARSubsystems.TrackingState.None && sessionSubsystem.notTrackingReason == NotTrackingReason.Relocalizing)`

to the following:
`if (sessionSubsystem.trackingState != UnityEngine.XR.ARSubsystems.TrackingState.Tracking && sessionSubsystem.notTrackingReason == NotTrackingReason.Relocalizing)`

I'm not sure if this is may affect other parts of the code, but from my experience, while using HoloLens 2, I couldn't get the trackingState equal to TrackingState.None.

I could create a pull request for you guys to check if this helps.

Have a nice one,
Stavros

**Comment by keveleigh** [comment]
@siamonas Thanks for looking into this! I double checked the implementation between the two and it looks like the OpenXR implementation _is_ less likely to drop all the way to `TrackingState.None` compared to Windows XR Plugin. I think your proposed change would be good and reasonable!

**Comment by AMollis** [comment]
@srinjoym, can you look into pulling #11407 into MRTK3. 

We should also look into the possibility of completing the PR #11407
