### ISSUE TITLE
Multiple Selection for InteractiveRadialSet

### ISSUE THREAD

**Issue by brean** [Microsoft/MixedRealityToolkit-Unity#1135]
Hi,

I needed some UI that allows Multiple button/checkbox selection, so it works like the HTML "multiple"-attribute on a ```<select>```-tag. 

I extended the InteractiveRadialSet and renamed it to InteractiveSet.

Take a look at my commit
https://github.com/brean/MixedRealityToolkit-Unity/commit/f62517766a410bd466b7fce1cb0bfd2217cb3e04#diff-140091b8c4f1cd712a8dac02c037d100 .

If this is OK I will create a pull request.

**Comment by StephenHodgson** [comment]
Looks good!

Please do.
