### ISSUE TITLE
When using simulated hands, and the `CanvasProxyInteractor` is disabled by the mode manager, `UGUIInputAdapterDraggable` nullrefs

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#11354]
## Describe the bug

When the mode manager disables `CanvasProxyInteractor` during input simulation (from #10838), `UGUIInputAdapterDraggable` starts NREing when dragged on by a mouse, because it doesn't check for the validity of the proxy interactor during the drag.

## To reproduce

Bring up hand, move mouse cursor onto object with `UGUIInputAdapterDraggable`, drag mouse, observe NREs

## Expected behavior

Should be nullchecked/no NREs

**Comment by shaynie** [comment]
Verified fixed with input simulation in HandInteractionExamples scene
