### ISSUE TITLE
Research Mode with Unity 2021.3.4f1 and OpenXR 1.7.0

### ISSUE THREAD

**Issue by camroo29** [microsoft/MixedRealityToolkit-Unity#11358]
## Describe the problem

I am trying to use Research Mode in Unity 2021.3.4f1 with OpenXR to stream Point Cloud Data. I am following this project: (https://github.com/petergu684/HoloLens2-ResearchMode-Unity/tree/master/UnitySample)

The author has used the Windows Mixed Reality Plugin which is not supported in newer versions of Unity.

I am stuck retrieving the Origin Coordinates. The author used 

> <b>IntPtr WorldOriginPtr = UnityEngine.XR.WindowsMR.WindowsMREnvironment.OriginSpatialCoordinateSystem;</b>
> <b>unityWorldOrigin = Marshal.GetObjectForIUnknown(WorldOriginPtr) as Windows.Perception.Spatial.SpatialCoordinateSystem;</b>

As a Windows Mixed Reality alternative, I have tried (https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10082). But I keep getting missing assembly reference errors.

Would you please suggest to me what I should do to use Research Mode with Unity 2021.3.4f1 and OpenXR 1.7.0

Thank You!

**Comment by camroo29** [comment]
So I added OpenXR like this
><b>#if ENABLE_WINMD_SUPPORT</b>
><b>using HL2UnityPlugin;</b> 
><b>using Microsoft.MixedReality.OpenXR;</b>
><b>#endif</b>

Building fails with,
> The type or namespace name 'SpatialCoordinateSystem' could not be found (are you missing a using directive or an assembly reference?)

**Comment by keveleigh** [comment]
Ahhh whoops yeah, you'll need another namespace for that. You'll need to include `Windows.Perception.Spatial` as well. Visual Studio has helpers to figure out which namespaces might be missing, like the little "Quick actions" light bulb:

![image](https://user-images.githubusercontent.com/3580640/211369176-c8b2ee5b-dab8-4f5f-a269-f49833140a78.png)
