### ISSUE TITLE
Error retrieving configuration when starting WindowsPhraseRecognitionSubsystem (MRTK3)

### ISSUE THREAD

**Issue by datglove** [microsoft/MixedRealityToolkit-Unity#11366]
## Describe the bug

Encounter an error-- "Configuration could not be retrieved for Microsoft.MixedReality.Toolkit.Speech.Windows.WindowsPhraseRecognitionSubsystem+WindowsPhraseRecognitionProvider." --when MRTKLifecycleManager attempts to start the MRTK Windows PhraseRecognition Subsystem.

## To reproduce

1. (In Editor) enable "MRTK Windows PhraseRecognition Subsystem" in Project Settings > MRTK3
2. Open Unity scene containing the default MRTK XR Rig prefab
3. Play
4. See above error in Console immediately after "[MRTKLifecycleManager] Starting Microsoft.MixedReality.Toolkit.Speech.Windows.WindowsPhraseRecognitionSubsystem"

## Expected behavior

PhraseRecognition Subsystem starts with no errors.

## Your setup

- Unity 2021.3.8
- com.microsoft.mrtk.windowsspeech 3.0.0-pre.13 (+ dependencies)

## Target platform

- Windows Editor
- HoloLens 2

## Additional context

Error does not occur after downgrading to com.microsoft.mrtk.windowsspeech 3.0.0-pre.12 .

I believe the problem is in WindowsPhraseRecognitionSubsystem.cs:
In [WindowsPhraseRecognitionProvider.Start](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/37c36a681239d7430a12bb1d3d034b68db90d412/com.microsoft.mrtk.windowsspeech/Subsystems/WindowsPhraseRecognitionSubsystem.cs#L94) , changing the second type argument in:
`config = XRSubsystemHelpers.GetConfiguration<WindowsPhraseRecognitionSubsystemConfig, WindowsPhraseRecognitionProvider>();`
to:
`config = XRSubsystemHelpers.GetConfiguration<WindowsPhraseRecognitionSubsystemConfig, WindowsPhraseRecognitionSubsystem>();` 
appears to fix the error and is consistent with other XRSubsystemHelpers.GetConfiguration calls e.g. in WindowsSpeechRecognitionProvider and the MRTK Hand Aggregator Subsystem.

**Comment by MaxWang-MS** [comment]
Thanks for filing the issue @datglove! I just noticed this as well and it will be fixed in #11348

**Comment by MaxWang-MS** [comment]
Fixed via #11348.
