### ISSUE TITLE
VS19 + VS22 causes error - Visual Studio 2017 support for ARM64 is not installed

### ISSUE THREAD

**Issue by arsi0001** [microsoft/MixedRealityToolkit-Unity#11362]
I have a local building agent for a Unity|HoloLens-Project. The whole time I had VS2019 on the agend installed and everything worked well. Today I had to install VS2022 on my agent because of a different .net 6 project (so it has nothing todo with my unity stuff!).

However, after installing VS2022, my Unity project can no longer be built with VS2019. I get the following output:

    EXEC(0,0): Error : System.NotSupportedException: Visual Studio 2017 support for ARM64 is not installed.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(46,5): Error MSB3073: Der Befehl ""C:\agent\_work\1\b\UWP_Build\Il2CppOutputProject\\IL2CPP\build\deploy\netcoreapp3.1\il2cpp.exe" --libil2cpp-static --compile-cpp -architecture=ARM64 -configuration=Release -platform=winrt -outputpath="C:\agent\_work\1\b\UWP_Build\\build\bin\ARM64\Release\GameAssembly.dll" --data-folder="C:\agent\_work\1\b\UWP_Build\\build\bin\ARM64\Release\\" -cachedirectory="C:\agent\_work\1\b\UWP_Build\\build\obj\il2cppOutputProject\ARM64\Release\\" -generatedcppdir="C:\agent\_work\1\b\UWP_Build\Il2CppOutputProject\\Source"  --incremental-g-c-time-slice=3 --baselib-directory="C:\agent\_work\1\b\UWP_Build\Players\UAP\il2cpp\ARM64\Release" --avoid-dynamic-library-copy --profiler-report --additional-defines=WINDOWS_UWP --additional-defines=UNITY_UWP --additional-defines=UNITY_WSA_10_0 --additional-defines=UNITY_WSA --additional-defines=UNITY_WINRT --additional-defines=PLATFORM_WINRT -dotnetprofile=unityaot -verbose --relative-data-path=Data/il2cpp_data --map-file-parser="C:\agent\_work\1\b\UWP_Build\Il2CppOutputProject\\IL2CPP\MapFileParser\MapFileParser.exe"" wurde mit dem Code -1 beendet.
    Process 'msbuild.exe' exited with code '1'.

The whole thing makes no sense to me. If I have only VS19 installed everything runs. When I install VS22, I get this error message. I went back to the building agent myself and manually opened the project in VS19 and tried to creat/publish an APPX. There I got the already known errors displayed and one more:

    System.NotSupportedException: Visual Studio 2017 support for ARM64 is not installed.
    MSB3073	The command ""C:\agent\_work\1\b\UWP_Build\Il2CppOutputProject\\IL2CPP\build\deploy\netcoreapp3.1\il2cpp.exe" --libil2cpp-static --compile-cpp -architecture=ARM64 -configuration=Release -platform=winrt -outputpath="C:\agent\_work\1\b\UWP_Build\\build\bin\ARM64\Release\GameAssembly.dll" --data-folder="C:\agent\_work\1\b\UWP_Build\\build\bin\ARM64\Release\\" -cachedirectory="C:\agent\_work\1\b\UWP_Build\\build\obj\il2cppOutputProject\ARM64\Release\\" -generatedcppdir="C:\agent\_work\1\b\UWP_Build\Il2CppOutputProject\\Source"  --incremental-g-c-time-slice=3 --baselib-directory="C:\agent\_work\1\b\UWP_Build\Players\UAP\il2cpp\ARM64\Release" --avoid-dynamic-library-copy --profiler-report --additional-defines=WINDOWS_UWP --additional-defines=UNITY_UWP --additional-defines=UNITY_WSA_10_0 --additional-defines=UNITY_WSA --additional-defines=UNITY_WINRT --additional-defines=PLATFORM_WINRT -dotnetprofile=unityaot -verbose --relative-data-path=Data/il2cpp_data --map-file-parser="C:\agent\_work\1\b\UWP_Build\Il2CppOutputProject\\IL2CPP\MapFileParser\MapFileParser.exe"" was terminated with the code -1.
    MSB8020	The build tools for v143 (platform toolset = "v143") were not found. To build using the v143 build tools, install the v143 build tools. Alternatively, upgrade to the latest Visual Studio tools by selecting the Project menu or right-clicking the solution and selecting Reassign Solution.

Workload in my VSInstaller for VS19:
[![enter image description here][1]][1]

It doesn't make sense that VS17 with ARM64 is suddenly demanded.<br> And it makes no sense that suddenly the build tools for version 143 are required.<br> The project is opened with VS19(=v142) and not with VS22(=v143).

  [1]: https://i.stack.imgur.com/6c2Nf.png
  [2]: https://i.stack.imgur.com/tnuOQ.png

**Comment by keveleigh** [comment]
>I have a local building agent for a Unity|HoloLens-Project.

If this is a static agent, I wonder if any reuse of solutions that were generated before the tools update is causing a problem here. Like @RogPodge mentioned, it could be good to try deleting any existing sln or csproj files and letting Unity regenerate them with the new installations (and maybe the Library folder if that doesn't work?).

**Comment by arsi0001** [comment]
@RogPodge I thought to post it here, as this is where I hoped to find the highest number of developers who are knowledgeable in the context of AR, UWP, HoloLens. 

@keveleigh I removed VS completely two time to reproduce this behaviour. After removing VS I installed at first VS19 (tried to build → succeeded) and then additionally VS22 (tried to build → failed). My Agent clears the build folder before every new build.

I also remember having this issue in the past on my working computer. I just fixed it by using only VS22.

**Comment by delzrm** [comment]
grrr, I just wasted 2 hours with this exact problem

**Comment by SandyLovegood** [comment]
meet the same problem.
I use vs2019 all the time. Today I download a sample project and somehow the new Unity Editor requires VS2022. The installation of VS2022 on Unity Hub failed but I thought it's not a big problem, cause I wasn't really expecting too much on that sample.
Then I try to pack my old projects and they all failed.
