### ISSUE TITLE
Multiple glb and gltf importers error in Unity when importing ready player me package. How can I fix this?

### ISSUE THREAD

**Issue by tsai-you-shin** [microsoft/MixedRealityToolkit-Unity#11376]
We use MRTK package in our project and we also need Ready Player Me model. 
However, we face some issue after we start import the ready player me package into our project. 
We get some error messages as below:

    Multiple scripted importers are targeting the extension 'gltf' and have all been rejected: ...
    Multiple scripted importers are targeting the extension 'glb' and have all been rejected: ...

Which is also similar to this question online: 
https://forum.unity.com/threads/multiple-glb-importers-how-do-i-fix-this.1364523/

Is there any clear instruction for us to walk around this problem?

## Setup 

- Unity Version v2020.3.21
- MRTK Version v2.8.2
- Ready player me Version v1.13.1

## Target platform 

- HoloLens 2

**Comment by keveleigh** [comment]
Ah yep! If you specifically want to use Ready Player Me's importer, you can disable the MRTK importer with the following menu item: 

![image](https://user-images.githubusercontent.com/3580640/212976422-d4ae6d9d-ef6c-4565-93a5-9ad53bad3532.png)

See #9658 for more info.
