### ISSUE TITLE
Clearing VirtualizedScrollRectList doesn't always work.

### ISSUE THREAD

**Issue by Magiel1975** [microsoft/MixedRealityToolkit-Unity#11377]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/194

___

## Overview
I wasn't able to completely clear the list every time. Perhaps I need more info on how to properly use the OnInvisible Action.
My workaround was to add 
`        public void ResetList()`
`        {`
`            SetItemCount(0);`
`            OnValidate();`
`        }`
to a copy of the VirtualizedScrollRectList class

## Expected behavior
When clearing the list with SetItemCount(0), all items should be removed every time SetItemCount(0) is used.

## Actual behavior
First time the items are removed, but the second time the items remain visible in the list and ItemCount remains > 0.
The new items will appear on the same position as the items still in the list, showing items through each other.

## Steps to reproduce

1. Add Items to the List. 
2. SetItemCount(0)
3. Add new Items to the List. 
4. SetItemCount(0)

## Unity editor version
2021.3.16f1

## Mixed Reality Toolkit release version
MRTK3

**Comment by Zee2** [comment]
@maluoi ? 😉
