### ISSUE TITLE
Piano Keys Location Bug

### ISSUE THREAD

**Issue by Jerryaa98** [microsoft/MixedRealityToolkit-Unity#11389]
Hi,
I am doing a project for university using mrtk2 with unity, basically I'm doing a virtual piano that you can learn songs on like the other apps with midi cubes falling on it and stuff, but sometimes when I press the piano keys they don't get back up so their z position stays  goes to 0.2~0.4 permenantly.

## To reproduce the bug:
after I light up the keys that i want to play I just keep playing the piano, eventually I will encounter it

## Screenshots

![pianoIssue](https://user-images.githubusercontent.com/82344133/213861174-b0b1851b-554f-4b26-b700-2a7e64f990a3.jpg)

here is a screenshot showing what I mean by keeping their position.
note that the C key before the yellow key has already been pressed and the D key after the yellow key hasn't been pressed.
so I don't think it is because of the color changes.

## My setup

- Unity Version  2021.3.13f1
- MRTK2

##Target platform :

- testing it on metaquest 2

**Comment by AMollis** [comment]
@marlenaklein-msft can you try reproducing in the MRTK3 sample scenes?

**Comment by Jerryaa98** [comment]
its okay, turned out to be a bug in the script.
