### ISSUE TITLE
Keyboard and/or example scene broken by null reference

### ISSUE THREAD

**Issue by adrianimajion** [Microsoft/MixedRealityToolkit-Unity#1138]
I am struggling to get the Keyboard prefab working in a project - it does not seem to behave as expected when placed in a scene with a KeyboardInputField, even with the KeyboardInputField explicitly assigned to the keyboard. The text does not replace the placeholder after submission and when built to the device the keyboard does not appear when triggered and the framerate drops. I think this might be related to the axis slider since I'm not clear on exactly where that goes. I've placed it on the InputField but it results in odd behavior with the field sliding off screen gradually.

 I assume I implemented the prefab wrong so I opened the KeyboardTest scene, but that scene throws NullReferenceException for both the InputField and AxisSlider component of the Keyboard prefab - it will not play in the editor or build to the device.

Can someone please tell me what I am doing wrong utilizing the keyboard for text input, and update the scene accordingly? I can fix the scene and make a pull request once I know what's wrong.

**Comment by StephenHodgson** [comment]
Pretty sure this is a duplicate.

Also, there's an open PR #1133 that addresses some of these issues.

**Comment by adrianimajion** [comment]
Yes, I just found the issue from September 8th - apologies for the duplicate. I will try that open PR, thank you!
