### ISSUE TITLE
Setting up new Project generates GUID conflicts followed by "MRTK Profile could not be retrieved"

### ISSUE THREAD

**Issue by primepeter** [microsoft/MixedRealityToolkit-Unity#11380]
## Description
After setting up a new Project, multiple GUID conflicts are thrown, e.g.:

`GUID [4c63e230f530e6c4e8be8b25846c0989] for asset 'Packages/com.microsoft.mixedreality.toolkit.foundation/SDK/Features/UX/Prefabs/RiggedHandVisualizer/RiggedHand.mat.meta' conflicts with:
  'Packages/com.microsoft.mrtk.input/Visualizers/RiggedHandVisualizer/RiggedHand-PrepassZ.mat.meta'
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.
`

![Unity_MRTK_GUID_Erros](https://user-images.githubusercontent.com/22826723/212928930-ad973da9-68f5-4c34-be86-cf7f12bc294b.png)

After a restart, the GUID Errors disappear and the Errors shows up:
 
 `MRTK Profile could not be retrieved.
UnityEngine.Debug:LogError (object)
Microsoft.MixedReality.Toolkit.XRSubsystemHelpers:GetConfiguration<Microsoft.MixedReality.Toolkit.Input.SyntheticHandsConfig, Microsoft.MixedReality.Toolkit.Input.SyntheticHandsSubsystem> () (at Library/PackageCache/com.microsoft.mrtk.core@20f12f4209d5/Utilities/XRSubsystemHelpers.cs:226)
Microsoft.MixedReality.Toolkit.Input.SyntheticHandsSubsystem:Register () (at Library/PackageCache/com.microsoft.mrtk.input@c0af6e6e9a0e/Subsystems/SyntheticHands/SyntheticHandsSubsystem.cs:43)`

Followed by warning
`Interaction Layer31 is not set to teleport`
which can be easily resolved by setting in to teleport.

## To reproduce

1. Create new Unity 3D Project
2. Open Feature Toolkit and navigate to project Folder
3. Install Following Features, as can be seen under header "Setup" > "package.json"
4. go back to unity, confirm restart, get GUID Errors
6. Follow the "project validation" to apply autofix and set up OpenXR Interaction Profiles 
8. Go to  MixedReality>Toolkit>Add to scene and configure
9. First time hitting play unity crashes
10. every other start of the Project get the Error ´MRTK Profile could not be retrieved.´

## Expected behavior

Start the scene when hitting play, even if nothing except the profiler bar would be visible.

## setup

- Unity Version [2021.3.4f1]
- MRTK Version [2.8.3, details in package.json]

### package.json:

"dependencies": {
    "com.microsoft.azure.remote-rendering": "file:MixedReality/com.microsoft.azure.remote-rendering-1.1.30.tgz",
    "com.microsoft.mixedreality.openxr": "file:MixedReality/com.microsoft.mixedreality.openxr-1.7.0.tgz",
    "com.microsoft.mixedreality.toolkit.examples": "file:MixedReality/com.microsoft.mixedreality.toolkit.examples-2.8.3.tgz",
    "com.microsoft.mixedreality.toolkit.extensions": "file:MixedReality/com.microsoft.mixedreality.toolkit.extensions-2.8.3.tgz",
    "com.microsoft.mixedreality.toolkit.foundation": "file:MixedReality/com.microsoft.mixedreality.toolkit.foundation-2.8.3.tgz",
    "com.microsoft.mixedreality.toolkit.standardassets": "file:MixedReality/com.microsoft.mixedreality.toolkit.standardassets-2.8.3.tgz",
    "com.microsoft.mixedreality.toolkit.testutilities": "file:MixedReality/com.microsoft.mixedreality.toolkit.testutilities-2.8.3.tgz",
    "com.microsoft.mixedreality.toolkit.tools": "file:MixedReality/com.microsoft.mixedreality.toolkit.tools-2.8.3.tgz",
    "com.microsoft.mrtk.core": "file:MixedReality/com.microsoft.mrtk.core-3.0.0-pre.13.tgz",
    "com.microsoft.mrtk.graphicstools.unity": "file:MixedReality/com.microsoft.mrtk.graphicstools.unity-0.4.0.tgz",
    "com.microsoft.mrtk.input": "file:MixedReality/com.microsoft.mrtk.input-3.0.0-pre.13.tgz",
    "com.microsoft.mrtk.spatialmanipulation": "file:MixedReality/com.microsoft.mrtk.spatialmanipulation-3.0.0-pre.13.tgz",
    "com.microsoft.mrtk.standardassets": "file:MixedReality/com.microsoft.mrtk.standardassets-3.0.0-pre.13.tgz",
    "com.microsoft.mrtk.uxcomponents": "file:MixedReality/com.microsoft.mrtk.uxcomponents-3.0.0-pre.13.tgz",
    "com.microsoft.mrtk.uxcore": "file:MixedReality/com.microsoft.mrtk.uxcore-3.0.0-pre.13.tgz",
    "com.unity.collab-proxy": "1.15.17",
    "com.unity.feature.development": "1.0.1",
    "com.unity.ide.rider": "3.0.14",
    "com.unity.ide.visualstudio": "2.0.15",
    "com.unity.ide.vscode": "1.2.5",
    "com.unity.test-framework": "1.1.31",
    "com.unity.textmeshpro": "3.0.6",
    "com.unity.timeline": "1.6.4",
    "com.unity.ugui": "1.0.0",
    "com.unity.visualscripting": "1.7.8",
    "com.unity.xr.openxr": "1.6.0",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }

## Target platform (please complete the following information)
- OpenXR
- Simulation input (mouse, keyboard)

**Comment by Zee2** [comment]
Hey there, it looks like you might be mixing MRTK3 and MRTK 2.x packages, is that correct? The two sets of packages aren't currently intended to coexist in the same package, and as such there might be GUID conflicts. @keveleigh can elaborate some more.

We might want to change the GUIDs for the controller/hand meta files if they're causing these (otherwise intentional) conflicts.

**Comment by primepeter** [comment]
Hi, That could be the problem, there are warnings in the Project Validation about MRTK3. 

![Screenshot 2023-01-18 134120](https://user-images.githubusercontent.com/22826723/213174564-cb610d7e-42b2-4c74-b796-46fb4b0f422d.png)

But I didn't mix it on purpose. I simply marked the Features via Feature toolkit and went on, on a fully new created Unity Project.

Which packages should I downgrade to which Version to be fully compatible with MRTK 2.8.3?

**Comment by AMollis** [comment]
@primepeter Please remove all the MRTK 2.x packages from the package.  MRTK v2 and MRTK v3 packages are not compatible together.

**Comment by keveleigh** [comment]
> @primepeter Please remove all the MRTK 2.x packages from the package.  MRTK v2 and MRTK v3 packages are not compatible together. 

I'd propose the opposite. These conflicting GUIDs should be regenerated in MRTK3 with a migration path. We'd been intentionally trying to make it possible for MRTK2 and MRTK3 to coexist for scenarios like side-by-side migration.

**Comment by chillbert** [comment]
does team still exist?

**Comment by shaynie** [comment]
@chillbert Yes!  You can find the latest version in the new repository here:  https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity
