### ISSUE TITLE
[pre.14][solvers] SolverHandler IsHandTracked not working when handedness is set to `Everything`

### ISSUE THREAD

**Issue by holomatt** [microsoft/MixedRealityToolkit-Unity#11398]
## Describe the bug

--When `SolverHandler` is set to Tracked Handedness Left+Right, `HandConstraintPalm` Up First Hand Detected and Last Hand lost Unity Event fields do not function.
--When there are two `SolverHandler` with Tracked Handedness set to Left and Right respectively, `HandConstraintPalmUp`  Last Hand Detected field does not consider the opposing hand.

## To reproduce

--Add `SolverHandler`, `HandConstraintPalmUp`, `HandBounds` to a GameObject

1. Set a single instance of `SolverHandler` to Tracked Handedness to `Everything`  (`Both` does not reproduce the issue)
2. Hook feedback to `HandConstraintPalmUp` First Handed Detected and Last Hand Detected Fields

OR

1. Add two instances the above component setup and set `TrackedHandedness` for one to Left and the other to Right
2. Hook feedback to `HandConstraintPalm` Up First Hand Detected and Last Hand Detected Fields for each solver

## Expected behavior

--A single `SolverHandler` set to Left+Right or Everything should fire events correctly
--Last Hand Detected field on `HandConstraintPalmUp` should consider the opposing hand

## Your setup (please complete the following information)

- Unity Version 2021.3
- MRTK Version 3.pre-14
- MR OpenXR Plugin 1.7.0 (also tried 1.4.4, etc)
- 
## Target platform (please complete the following information)

- Editor UWP w/Sim Hand
- HL2

## Additional context

In pre.12 this scenario also generated an Assertion Failed:

``Microsoft.MixedReality.Toolkit.HandednessExtensions:ToXRNode (Microsoft.MixedReality.Toolkit.Handedness) (at Library/PackageCache/com.microsoft.mrtk.core@3.0.0-pre.12.18/Utilities/Extensions/HandednessExtensions.cs:93)``

**Comment by holomatt** [comment]
cc @Zee2  @RogPodge

**Comment by holomatt** [comment]
<img width="858" alt="image" src="https://user-images.githubusercontent.com/12565843/215573624-c00176cd-a0eb-447f-8a6f-ea6ebe8498f7.png">
^^Looks like this is where the issue stems from when set to Both

**Comment by AMollis** [comment]
@srinjoym is this something needed for GA?

**Comment by AMollis** [comment]
@srinjoym I chatted with @holomatt  about this.    There is an assumption that this issue stems from a limitation in XRI 2.2, and can be addressed by upgrading to XR1 2.3.    Can you help determine if there is a solution that doesn't require upgrading to XR1 2.2.  The issue for upgrading to XR1 2.3 is #11282

**Comment by shaynie** [comment]
No repro after upgrading XRI to 2.3.  Please re-open if you encounter it again with XRI 2.3 installed.

**Comment by holomatt** [comment]
Just tested on 3.0.0-pre.15 - this still reproduces. Setting SolverHandler to Both or Everything does not function. Still need to use two instances of the SolverHandler set to Left and Right respectively in order to implement hand menus for both hands.

**Comment by holomatt** [comment]
After more testing with @AMollis  - we found that this issue is an inspector bug specific to selecting the "Everything" value. The "Both" value works great, but once the user changes the Enum away from the default (Both) it latches to "Everything" when selecting more than one hand, resulting in non-operation.

**Comment by AMollis** [comment]
Hopefully this is fixed now :)
