### ISSUE TITLE
What is the possible future of this project?

### ISSUE THREAD

**Issue by KuraiAndras** [microsoft/MixedRealityToolkit-Unity#11391]
## Describe the problem

With the recent layoff of the MRTK team what will happen to the project?

## Describe the solution you'd like

The continuation of the project. I understand that this whole project is a massive undertaking and in the future the developers working on it might have difficult feelings working on it

## Describe alternatives you've considered

1. Continue this under the .NET Foundation and receive funding
2. Set up some way to directly fund the project (i.e.: Patreon)
3. Make this purchasable on the Asset Store
4. Let the community take control over the repository/project and establish a new community ownership
5. A mix of the above points

## Additional context

I have been developing software with this toolkit since 2019, for HoloLens 1 and 2, HTC Vive and recently Varjo VR-3. Our company sees a huge potential in Mixed Reality, and when starting a new project using the Mixed Reality Toolkit always was the default choice of handling user interactions: it provides the best of the best UX in XR, easy to work with, and solves whole classes of problems when starting a new XR project. Letting this toolkit go would be a great loss for the whole XR community, and I really hope that there will be a continuation of this.

Thank you everyone who has worked on this project - you really made a lot of programmer's lives easier with this and made us hopeful for the future of XR.

**Comment by Victor-x1** [comment]
On Twitter Zeez2 said possible Open Source MIT License
https://twitter.com/FNS_Developer/status/1616950687010807809

**Comment by Zee2** [comment]
Hi @Victor-x1. The project is already entirely MIT licensed.

The team will give an update as soon as we can. As you can probably expect, there's a lot on our plate right now 😅 Thank you for all the positive messages of support and concern.

**Comment by Zee2** [comment]
Hi @Victor-x1, @KuraiAndras , please see the [`pre.14` announcement](https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/11395), and stay tuned for further updates. `pre.14` will be the final release from the MRTK team, barring any other hotfixes that we deem mission critical.

**Comment by AMollis** [comment]
@KuraiAndras, we appreciate your patience and support for MRTK3. A new team has taken over the project, and we are making good progress. We will update you on the new release date for GA as soon as possible. We also value your questions and feedback for the team. Please don’t hesitate to reach out to us anytime.

**Comment by BertrandDeSaintBezier** [comment]
Any chance you could comment on the macro-level vision for this project ? Is Microsoft/1st-party development coming to an end after the GA, or are there plans for longer-term support and further releases ?
