### ISSUE TITLE
MRTK3 Spatial Awareness

### ISSUE THREAD

**Issue by WVandergrift** [microsoft/MixedRealityToolkit-Unity#11400]
Is there documentation available for enabling spatial awareness on MRTK3?

## Existing doc link
[MRTK2 Spatial Awareness Documentation](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/spatial-awareness/spatial-awareness-getting-started?view=mrtkunity-2021-05)

**Comment by Zee2** [comment]
Hey there @WVandergrift . "Spatial Awareness" functionality is now 100% covered by the built-in Unity ARFoundation APIs.

For scene reconstruction (i.e., meshing), [see the ARMeshManager API.](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/api/UnityEngine.XR.ARFoundation.ARMeshManager.html)

For scene understanding, i.e., planefinding, [see the plane detection API](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/manual/features/plane-detection.html)

That same page should have information on spatial anchors and other features that used to be offered through MRTK "Spatial Awareness".

Cheers :)

**Comment by WVandergrift** [comment]
Thanks for the detailed info @Zee2! Closing the issue.
