### ISSUE TITLE
The MRTK3 example scenario reported an error when publishing to Hololens2 using ARM Release

### ISSUE THREAD

**Issue by 91i1** [microsoft/MixedRealityToolkit-Unity#11419]
Hello, my personal project requirements were released to Hololens2 using ARM Release, and I was testing with the MRTK3 sample project, and VS had the following BUG,May I ask how to solve this problem:

The unity version I'm using is 2021.3.14f1c1；
UWP  Platform；
Visual Studio 2019;

![1](https://user-images.githubusercontent.com/125975752/225613751-459f60d6-fb88-41bf-a5fd-756fb59f42c3.png)
![2](https://user-images.githubusercontent.com/125975752/225613761-3213af44-9321-4134-9008-9b9e27de354a.png)
![3](https://user-images.githubusercontent.com/125975752/225614783-db62de75-546f-4f39-9c00-f39bcb848018.png)

已启动生成…
1>------ 已启动生成: 项目: Il2CppOutputProject, 配置: Release ARM ------
1>Building GameAssembly.dll with MsvcWinRtToolChain
1>	Msvc Install Version: 16.0
1>	Msvc Install SDK Directory: C:\Program Files (x86)\Windows Kits\10
1>	Msvc Linker Path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\ARM\link.exe
1>	Msvc Compiler Path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\ARM\cl.exe
1>
1>	Output directory: D:\A\A\BulidTest\App\build\bin\ARM\Release
1>	Cache directory: D:\A\A\BulidTest\App\build\obj\il2cppOutputProject\ARM\Release
1>ObjectFiles: 887 of which compiled: 0
1>Total compilation time: 858 milliseconds.
1>EXEC : error : Unity.IL2CPP.Building.BuilderFailedException: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\ARM\link.exe /out:"D:\A\A\BulidTest\App\build\obj\il2cppOutputProject\ARM\Release\linkresult_B7611E108EDABE5AF5B5C83E330EFD90\GameAssembly.dll" /ignore:4206 /DEBUG /INCREMENTAL:NO /LARGEADDRESSAWARE /NXCOMPAT /DYNAMICBASE /NOLOGO /TLBID:1 /OPT:REF /OPT:ICF /OPT:LBR /DLL /IGNORE:4104 /NODEFAULTLIB:uuid.lib "Shcore.lib" "WindowsApp.lib" "Crypt32.lib" "Iphlpapi.lib" "D:\Program Files\Unity\2021.3.14f1c1\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\il2cpp\ARM\Release\baselib.dll.lib" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\ARM\store" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\arm" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\ucrt\arm" /APPCONTAINER /SUBSYSTEM:WINDOWS /NODEFAULTLIB:ole32.lib /NODEFAULTLIB:kernel32.lib @"C:\Users\holortc\AppData\Local\Temp\tmpEE63.tmp"
1>
1>���ڴ����� D:\A\A\BulidTest\App\build\obj\il2cppOutputProject\ARM\Release\linkresult_B7611E108EDABE5AF5B5C83E330EFD90\GameAssembly.lib �Ͷ��� D:\A\A\BulidTest\App\build\obj\il2cppOutputProject\ARM\Release\linkresult_B7611E108EDABE5AF5B5C83E330EFD90\GameAssembly.exp
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_Delegate_sendToAllPeers������ MCSession_SendToAllPeers_m05D206ED560D05F8D35C42F57ABAC0BDDCCC2669 �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_Delegate_initWithName������ MCSession_InitWithName_mB47809B8068161BF69CF80ACB4C61E7380C10586 �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_Delegate_receivedDataQueueSize������ MCSession_GetReceivedDataQueueSize_m270753069757F4DDE1315FD34BD6195AF6124099 �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_Delegate_dequeueReceivedData������ MCSession_DequeueReceivedData_mB68CCB7C0CC97AB9E5C1415A7612D84C2DFD98A8 �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_Delegate_connectedPeerCount������ MCSession_GetConnectedPeerCount_m889159CC4C0302AE0C6DC8A5D16BFE594BB6934B �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_Delegate_setEnabled������ MCSession_SetEnabled_mDA05621506EC33993DE6CE32213C31A35B0AFF2D �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_Delegate_getEnabled������ MCSession_GetEnabled_m0F8E2DB79BA38E67F73C37AC896CC71BF41B513D �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_CFRelease������ "public: __cdecl il2cpp::utils::FinallyHelper<class <lambda_0f0c9a355a302c09b098f7df71f76d05>,0>::~FinallyHelper<class <lambda_0f0c9a355a302c09b098f7df71f76d05>,0>(void)" (??1?$FinallyHelper@V<lambda_0f0c9a355a302c09b098f7df71f76d05>@@$0A@@utils@il2cpp@@QAA@XZ) �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_NSData_getLength������ NSData_GetLength_m18870E8FA9B7121546844048DB0B2844349CC8FB �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_NSData_getBytes������ NSData_GetBytes_m675068905E6D0AEB2634D33998FF660D1EE78910 �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_NSData_createWithBytes������ NSData_CreateWithBytes_m9ACDA1908385AE95805AE95663A33063AD4B5EC6 �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_NSData_createWithBytesNoCopy������ NSData_CreateWithBytesNoCopy_mB7116AA642F24E05CC717E682CDB1C618301CCA7 �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_NSError_code������ NSError_GetCode_m08024CB17028A1274EA7AC9399DCCD0B0448946B �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_NSError_localizedDescription������ NSError_GetLocalizedDescription_m2F66521E246FC066B9DAF54D0D468199C60C435A �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_NSString_createWithString������ MCSession__ctor_m48D4CF11A5FF84874EBBB812B176F36DAFA5942D �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_NSString_lengthOfBytesUsingEncoding������ NSString_GetLengthOfBytes_m56E659D320AC220C7F92B2A26CD59A9E9D89A199 �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_NSString_getLength������ NSString_GetLength_m12CFED74B3771A60877D978EAAA025612EE93B28 �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_NSString_getBytes������ NSString_GetBytes_m4D966C0430053F000B1EA0FE1D1F14260E6201F4 �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_NSString_serialize������ NSString_Serialize_m11682E0AE3634B4B1048F8D05B3F9FCECB3F2D8E �������˸÷���
1>616623E5388FF4A9F35D3BAA8446015F.obj : error LNK2019: �޷��������ⲿ���� UnityMC_NSString_deserialize������ NSString_Deserialize_m633254993101859F460428DF408E66CA9C6DDCBA �������˸÷���
1>D:\A\A\BulidTest\App\build\obj\il2cppOutputProject\ARM\Release\linkresult_B7611E108EDABE5AF5B5C83E330EFD90\GameAssembly.dll : fatal error LNK1120: 20 ���޷��������ⲿ����
1>
1>   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
1>   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
1>   at il2cpp.Compilation.CompilationDriver.Run(RuntimePlatform platform, Il2CppCommandLineArguments il2CppCommandLineArguments, BuildingOptions buildingOptions, ReadOnlyCollection`1 matchedAssemblyMethodSourceFiles)
1>   at il2cpp.Program.DoRun(String[] args, RuntimePlatform platform, Il2CppCommandLineArguments il2CppCommandLineArguments, BuildingOptions buildingOptions, Boolean throwExceptions)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(46,5): error MSB3073: 命令“"D:\A\A\BulidTest\App\Il2CppOutputProject\\IL2CPP\build\deploy\il2cpp.exe" --libil2cpp-static --compile-cpp -architecture=ARMv7 -configuration=Release -platform=winrt -outputpath="D:\A\A\BulidTest\App\\build\bin\ARM\Release\GameAssembly.dll" --data-folder="D:\A\A\BulidTest\App\\build\bin\ARM\Release\\" -cachedirectory="D:\A\A\BulidTest\App\\build\obj\il2cppOutputProject\ARM\Release\\" -generatedcppdir="D:\A\A\BulidTest\App\Il2CppOutputProject\\Source"  --incremental-g-c-time-slice=3 --baselib-directory="D:\Program Files\Unity\2021.3.14f1c1\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\il2cpp\ARM\Release" --avoid-dynamic-library-copy --dont-deploy-baselib --profiler-report --additional-defines=WINDOWS_UWP --additional-defines=UNITY_UWP --additional-defines=UNITY_WSA_10_0 --additional-defines=UNITY_WSA --additional-defines=UNITY_WINRT --additional-defines=PLATFORM_WINRT -dotnetprofile=unityaot-win32 -verbose --relative-data-path=Data/il2cpp_data”已退出，代码为 4。
1>已完成生成项目“Il2CppOutputProject.vcxproj”的操作 - 失败。
2>------ 已启动生成: 项目: Anchors, 配置: Release ARM ------
2>LINK : fatal error LNK1181: 无法打开输入文件“D:\A\A\BulidTest\App\build\bin\ARM\Release\GameAssembly.lib”
2>已完成生成项目“Anchors.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 2 个，最新 0 个，跳过 0 个 ==========
========== 部署: 成功 0 个，失败 0 个，跳过 0 个 ==========

**Comment by AMollis** [comment]
@91i1 can you please provide the version of Visual Studio 2019 you are using.  Have you tried the latest version of Visual Studio 2022 v17.5.2?

**Comment by stgrosshh** [comment]
You have to use ARM 64-bit Architecture for HL2.

**Comment by keveleigh** [comment]
> You have to use ARM 64-bit Architecture for HL2.

32-bit ARM should work as well! Are you running into issues with it?

**Comment by stgrosshh** [comment]
> > You have to use ARM 64-bit Architecture for HL2.
> 
> 32-bit ARM should work as well (though I believe 64-bit has been the recommendation unless you have 32-bit dependencies)! Are you running into issues with it?

Didn't try, but always used ARM64 for my HL2 builds... so just thought.

**Comment by 91i1** [comment]
> @91i1您能否提供您正在使用的Visual Studio 2019版本。您是否尝试过最新版本的 Visual Studio 2022 v17.5.2？

Hello, I am currently using VS version 2019.16.11.24.
I haven't tried an ARM build with VS2022 yet

**Comment by 91i1** [comment]
> > 您必须对 HL64 使用 ARM 2 位体系结构。
> 
> 32 位 ARM 也应该可以工作（尽管我相信 64 位是推荐的，除非您有 32 位依赖项）！您是否遇到问题？

Yes, my original project had a 32-bit dependency. My original project can normally use ARM to build under VS2019 and MRTK2.8.3, but it can't after upgrading to MRTK3. What is the reason?
