### ISSUE TITLE
HandConstraintPalmUp comments outdated

### ISSUE THREAD

**Issue by marlenaklein-msft** [microsoft/MixedRealityToolkit-Unity#11417]
## Describe the issue
In HandConstraintPalmUp, comments reference IMixedRealityHand, which does not exist in MRTK3.

**Comment by AMollis** [comment]
@marlenaklein-msft  can you please provide a link to learn.microsoft.com document?

**Comment by marlenaklein-msft** [comment]
Fixed with PR #11497
