### ISSUE TITLE
Improvements to Spatial Understanding Documentation

### ISSUE THREAD

**Issue by BenWoodford** [Microsoft/MixedRealityToolkit-Unity#1142]
It's been... a learning experience working on a wrap up of the spatial understanding stuff with HoloLens. And I think there's a few improvements that could be made.

I'm awful at writing documentation, so I'd rather get the discussion going with a few things off the top of my head:

- `ActivateShapeAnalysis` _must_ be called before shapes will work
- `AddShapes` only seems to work if spatial understanding is complete. Otherwise it appears to not register any of the shapes properly. This is shown in the examples but not in the docs.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
