### ISSUE TITLE
StateViz AnimationEffect - DrawIf property exception spam

### ISSUE THREAD

**Issue by holomatt** [microsoft/MixedRealityToolkit-Unity#11436]
## Describe the bug

PR: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11438

Console spams exceptions while interacting with StateViz while an Animation type effect is attached.

DrawIf operates on the object being serialized. In this case, we have a StateVisualizer that is being serialized, which contains a simple serializable class: AnimationEffect. AnimationEffect makes use of 'drawif' referencing one of its members, but AnimationEffect is not a monobehavior and will only ever be serialized in the context of another object. In this case, StateVisualizer. When the DrawIf attribute code is invoked, it looks for the specified property name (weightMode) on the object being serialized (a StateVisualizer) and throws an error because that doesn't exist.

## To reproduce

1. Add PressableButton to a GameObject
2. Add StateViz to the same GameObject
3. Add Animation effect type to any StateViz outlet

## Observed behavior

Console spams exception: 

DrawIfAttribute couldn't find the SerializedProperty to compare against! (property name: weightMode)

## Expected behavior

No exception spam.

## Your setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. 3.0.0-preview.14

**Comment by AMollis** [comment]
Fixed with this pull request

* https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11438
