### ISSUE TITLE
App on HoloLens2 crashes when I start playing video

### ISSUE THREAD

**Issue by Rutherfordum** [microsoft/MixedRealityToolkit-Unity#11448]
## Describe the bug

App on HoloLens2 crashes when I start playing video

## To reproduce

1. Install MRTK 2.8.3
2. Configure the project for HoloLens 2
3. Add to new scene and configure
4. Add world canvas RawImage
5. Add standart VideoPlayer Unity 
6. Change RenderMode on the VideoPlayer to RenderTexture and use AudioOutputMode to Direct
7. Add video clip to VideoPlayer
8. Create a new RenderTexture and add this to VideoPlayer and RawImage
9. Build adn Run app on Hololens at Runtime.

## Expected behavior

Video plays and app doesn't crash on HoloLens 2

## Videos

[Video problem.](https://youtu.be/Au8jMkaMl4w)

## Your setup

- Unity Version [e.g. 2021.3.16f1]
- MRTK Version [e.g. v2.8.2]

## Target platform

- HoloLens 2

## Additional context

[UnityPlayer.log](https://github.com/microsoft/MixedRealityToolkit-Unity/files/11146090/UnityPlayer.3.log)

**Comment by AMollis** [comment]
@Rutherfordum thank you for your issue.  Unfortunately this issue appears unrelated to MRTK.   Can you please visit https://support.unity.com and open an issue with Unity.
