### ISSUE TITLE
Active Hover Persists When Hand Rays Far Away

### ISSUE THREAD

**Issue by marlenaklein-msft** [microsoft/MixedRealityToolkit-Unity#11447]
## Describe the bug
Once active hover is activated for a button, the hand can move far away or close to other buttons and active hover still persists. 

## Screenshots
![image](https://user-images.githubusercontent.com/125413876/229606256-3db35a51-4455-4f0b-855b-518ee1da5a3e.png)
![image](https://user-images.githubusercontent.com/125413876/229606691-6cdb749a-4480-419d-9016-93b7a2dccfd2.png)

## Setup
- Unity Version 2020.3.42
- MRTK3

**Comment by AMollis** [comment]
@marlenaklein-msft  is still for both Canvas and Non-Canvas buttons?

**Comment by marlenaklein-msft** [comment]
Yes, on both

**Comment by keveleigh** [comment]
These buttons both look reasonably close to the center of the screenshots. Are you sure they aren't being hovered by the gaze+pinch interactor? 

You can use the XR Interaction Debugger to check this.

![image](https://user-images.githubusercontent.com/3580640/230138949-05bd3d25-5610-4208-9188-fea408758a95.png)

![image](https://user-images.githubusercontent.com/3580640/230140222-def16938-d533-4845-a056-d029a85ba776.png)

**Comment by marlenaklein-msft** [comment]
Ah yes! They are being hovered by GazePinch. I think this behavior is reasonable then.
