### ISSUE TITLE
MRTK 2.7.3 -> 2.8.3 migration: Articulated Hand Tracking: no more Articulated Mesh Prefab ?

### ISSUE THREAD

**Issue by Xispeo** [microsoft/MixedRealityToolkit-Unity#11442]
## Overview
In the MRTK configuration panel, Input section, Articulated Hand Tracking subsection, there is no more Hand Mesh Prefab but System Hand Mesh Material and Rigged Hand Mesh Material.. ??

## Expected behavior
Being able to configure a Hand Mesh Prefab, not Materials only which sound to me as a (strange) regression

## Actual behavior
Regression allowing us to only configure Materials but no more Prefabs

## Steps to reproduce
Just compare MRTK configuration of Input/Articulated Hand Tracking between 2.7.3 and 2.8.3

## Unity editor version
2020.3.43

## Mixed Reality Toolkit release version
2.7.3/2.8.3

**Comment by AMollis** [comment]
@Xispeo thank you for your feedback.  What scenario are you currently blocked on?

In MRTK 2.8.3 you are still able to modify the rigged hand model for the control definition settings:

![image](https://user-images.githubusercontent.com/36461279/228959091-6207ca82-4d27-4b91-89f1-f01f6200b05b.png)

Does this not meet your requirements?

**Comment by Xispeo** [comment]
Yes, perfect, thank you for your fast answer
