### ISSUE TITLE
Pico Neo controller support?

### ISSUE THREAD

**Issue by Toby-mxr** [microsoft/MixedRealityToolkit-Unity#11443]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/175

___

## Describe the problem

Are you able to get controller profiles for the Pico neo (3, 4) controllers as when I make a build and test on my Pico neo 3 link nothing shows up for my controllers. I debugged it and it gets a GenericJoysticController profile but no functionality happens. Am I doing something wrong or does mrtk not support the Pico controllers?

Any extra information can be given.

**Comment by Phantomxm2021** [comment]
In here: https://github.com/Phantomxm2021/PicoMRTK3
