### ISSUE TITLE
MSBuild.exe is missing or invalid (path=). Note that the default version is 14.0

### ISSUE THREAD

**Issue by reillydonovan** [Microsoft/MixedRealityToolkit-Unity#1146]
When trying to build an appx I am returned the following:
Unable to find a valid path to Visual Studio Instance!
UnityEngine.Debug:LogError(Object)

MSBuild.exe is missing or invalid (path=). Note that the default version is 14.0
UnityEngine.Debug:LogError(Object)

I've tried updating everything.  Unity. (2017.1.2.f1) The Windows SDK.  Visual Studio with all of the additional components listed.  No luck.

Any suggestions on how to correct this issue?

**Comment by StephenHodgson** [comment]
What SDK are you targeting?

**Comment by reillydonovan** [comment]
10.0.15063
10.0.16299
are the ones I tried

**Comment by StephenHodgson** [comment]
Use 15063 for 2017.1

**Comment by StephenHodgson** [comment]
It seems like you may not have something installed right for Visual Studio

Go back and make sure you have the right components installed.
Be sure MsBuild is included.

**Comment by reillydonovan** [comment]
Ok, that wasn't installed.  Now I have MSBuild included and I am returned the following:

MSBuild error (code = 1)
UnityEngine.Debug:LogError(Object)
HoloToolkit.Unity.BuildDeployTools:BuildAppxFromSLN(String, String, Boolean, String, String, String, Boolean, Boolean) (at Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployTools.cs:278)
HoloToolkit.Unity.BuildDeployWindow:BuildAll(Boolean) (at Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs:716)
HoloToolkit.Unity.<OnGUI>c__AnonStorey1:<>m__1() (at Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs:474)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()

**Comment by StephenHodgson** [comment]
Okay, build it the normal way and open it in Visual Studio and build there.

**Comment by reillydonovan** [comment]
Ok, I'll try building the appx from the visual studio solution.
I can build successfully if I build using Unity's traditional build window instead of the mixed reality build window.  I'll report back soon, thanks.

**Comment by jessemcculloch** [comment]
I have always had to do a regular build (Unity Build, then Visual Studio Build and deploy) first before I could use the MRTK build window.

**Comment by brean** [comment]
> I have always had to do a regular build (Unity Build, then Visual Studio Build and deploy) first before I could use the MRTK build window.
Same here. At least the build of the VisualStudio-Solution from Unity, otherwise the buttons in the Build Window were disabled.

**Comment by StephenHodgson** [comment]
I think I figured it out guys.  Got a PR open to fix this.
