### ISSUE TITLE
There is a error in MRTK3 github page and some advices

### ISSUE THREAD

**Issue by nongzhang** [microsoft/MixedRealityToolkit-Unity#11463]
## Describe the issue
https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk3
this is the page of MRTK3,but the link is 404.
![image](https://user-images.githubusercontent.com/24870308/231637330-a738fadc-f27d-4cfa-b6a6-598803aa86c1.png)
The correct link is https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-new-project

When i download MRTK3 temple project, and follow the documentation for setting up MRTK3 packages as dependencies,there is many error in unity console.  About Data and Diagnostic. After a long period of research，two feature packages havent to import.
MRTK Diagnostic(MRTK3) and MRTK3 Data Binding and Theming(Experimental) .

I suggest that the official add this note.

**Comment by marlenaklein-msft** [comment]
Thanks for filing this issue, the broken link has been fixed!

I haven't been able to reproduce the Data and Diagnostic errors. Recent changes may have fixed this. If you encounter this again, could you please reopen this issue and provide your steps to reproduce this error?
