### ISSUE TITLE
Create How-To Documentation For Dwell in MRTK3

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11479]
## Overview

MRTK2 provided a how-to document for adding dwell to an application, https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/ux-building-blocks/dwell?view=mrtkunity-2022-05.  We are missing a similar document for MRTK3.

## Additional Context

There is already a reference API document for MRTK3's `InteractorDwellManager` 

https://learn.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.toolkit.input.interactordwellmanager?view=mrtkinput-3.0

**Comment by marlenaklein-msft** [comment]
Dwell info found [here](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-input/packages/input/eye-tracking).
