### ISSUE TITLE
Dictation is not working in MixedRealityKeyboardExample in HoloLens2

### ISSUE THREAD

**Issue by swatvel** [microsoft/MixedRealityToolkit-Unity#11474]
On clicking TMP_InputField MixedRealityKeyboard gets invoked. I am trying to enter text via dictation, by selecting the microphone icon.  The icon color changes to blue, but it does not update the dictated text in the inputfield. 

1. Launch MixedRealityKeyboardExample scene
2. Select TMP_InputField and start dictating by selecting the microphone in keyboard

## Expected behavior

Dictated text should be present in the input field

## Screenshots

![image (3)](https://user-images.githubusercontent.com/36452156/233329525-92144b33-8a48-4a83-ac66-1092b425e674.png)

- Unity Version [2021.3.16f1]
- MRTK Version [2.8.3]

## Target platform (please complete the following information)
- HoloLens 2

**Comment by AMollis** [comment]
Thank you for the issue @swatvel .   There was a recent service outage causing speech scenarios to fail on HoloLens 2.   These issues have since been resolved.  Can you please try again?

**Comment by swatvel** [comment]
Thanks @AMollis this got resolved.
