### ISSUE TITLE
Investigate performance improvements to canvas UI

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11471]
## Describe the problem

MRTK3's canvas buttons and canvas dialogs are noticeably less performant than MRTK2/3's non-canvas versions. We need to understand why, and how to improve these elements. 

## Describe the solution you'd like

Come up with a plan for improving canvas buttons and canvas dialogs

## Additional context

This issue seems related to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6180

Part of the issue might be because of the multiple z-layers on the MRTK3 buttons, which cause less of draw call batching within canvas UI (more batching occurs in non-Canvas UI)

## Goals

- [x] Create a performance scene we can use to measure canvas UI improvements
- [ ] Define a set of work to improve performance of canvas UI

**Comment by srinjoym** [comment]
Started this investigation. On first glance, it seems like we are creating more draw calls in canvas UI vs. comparable non canvas UI leading to the performance bottleneck. Will continue profiling this with more comparable scenes and then investigate areas to reduce draw calls. 

The biggest source of draw calls so far is the button front plate as the individual icon and text takes two draw calls minimum. The default canvas UI tearsheet scene has 469 draw calls. With no front plate, we drop 149 draw calls

**Comment by AMollis** [comment]
Investigation was done, but no actionable items were found.
