### ISSUE TITLE
Create Overvew Documentation For VirtualizedScrollRectList

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11476]
## Overview 

The MRTK3 API reference has `VirtualizedScrollRectList` documentation at https://learn.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.toolkit.ux.virtualizedscrollrectlist?view=mrtkuxcore-3.0.  However, there is no overview documentation.

## Work

Add an overview document for `VirtualizedScrollRectList` under the [UX Core](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-uxcore/packages/uxcore/overview) documentation

**Comment by marlenaklein-msft** [comment]
Doc found [here.](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-uxcore/packages/uxcore/virtualized-list)
