### ISSUE TITLE
Sample Scene: Complete PR to add TapToPlace, Clipping, Outline, Solver Example (Follow / RadialView / InBetween), and Directional Indicator Sample to MRTK3

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11489]
## Overview

Add some example scenes for the high-priority features frequently used by customers from v2:

- TapToPlace Example: Known issue - only magnetic behavior works when 'auto start' is checked. Select (pickup/place)behavior is not working. Need engineering investigation on input/interactor.

- Clipping Example

- Outline Example

- Solver Example (Follow / RadialView / InBetween)

- Directional Indicator Example

## Pull Request

- https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10966

**Comment by marlenaklein-msft** [comment]
Sample scene added in #11522.
