### ISSUE TITLE
Inside Unity Editor, when InputField has focus, camera moves when pressing the A,W,S, and D key

### ISSUE THREAD

**Issue by Victor-x1** [microsoft/MixedRealityToolkit-Unity#11496]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/146

___

## Describe the bug
MRTK3
In Scenes/InputFieldExamples pressing A,W,S,D moves the inputfield left,up,right,down inside Unity Editor.

## To reproduce

1. In Unity Editor, Load InputFieldExamples Scene
2. Press Play
3. In the InputField press the keyboard key A, W, S , and D.

## Expected behavior

Inside Unity Editor, When in Play mode, when you type the key A, W, S, D the input field should not move. 

## Screenshots
Video attached
[Youtube](https://www.youtube.com/watch?v=gs1ugslYOJg)

## Your setup (please complete the following information)

- Unity Version 2021.3.21f
- MRTK 3 - updated to April 20, 2023 "Shayine 2021 Upgrade"

## Target platform (please complete the following information)

- HoloLens 2

## Additional context
Issue appears to be related to Input Simulator prefab -> Camera Settings -> Simulation enabled. See video.

**Comment by AMollis** [comment]
This does appear to be relate to MRTK3's camera/head simulation.  Thank you for the issue
