### ISSUE TITLE
Sample Scene: Add ClippingInstancedExamples to MRTK3

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11510]
## MRTK2 Scene Name

ClippingInstancedExamples

## Overview

This scene shows how the MRTK/Standard shader in conjunction with clipping primitives (ClippingPlane, ClippingSphere, & ClippingBox) can be used to dynamically clip pixels on meshes instanced on the GPU. This method allows for significantly more clipped meshes by enabling automatic batching across all renderers that share the same material even if they interact with different clipping primitives.

## Additional Context

MRTK/Standard shader replaced by GraphicsTools shader

**Comment by Weimmer** [comment]
Hi, is it possible to use custom "ClippingMesh" somehow? Like currently it only support plane, sphere and box, it would be great if it support custom mesh shape clipping.

**Comment by AMollis** [comment]
Done
