### ISSUE TITLE
Dev branch announcement

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1151]
Now that the master and dev branches are synced up we should open PRs on the master branch and test against both to ensure forwards compatibility.

Those changes will then get merged in a master -> dev branch sync that'll happen daily, or as needed.

Remember to wrap 2017.2 specific code in `#if UNITY_2017_2_OR_NEWER` as needed.

Don't worry about the Unity APIs as much, cause it's a simple find/replace to change the VR to XR and Unity also automatically updates the APIs for you as needed.

I'm trying to get the repo to a point where it doesn't matter what version of the editor you open it with.

**Comment by brean** [comment]
> Those changes will then get merged in a master -> dev branch sync that'll happen daily, or as needed

So will changes on master merged into dev (according to the arrow direction) and dev will become the new master in one big merge or do you intend to merge parts of dev into master?
And should new stuff that might get pushed into the MRTK developed using dev or master branch?

**Comment by StephenHodgson** [comment]
> dev will become the new master in one big merge or do you intend to merge parts of dev into master and have multiple smaller pull requests?

We've already been doing some syncing of the branches, but yes, at some point Dev will be merged back into master.
