### ISSUE TITLE
Remove MRKT3 Android's dependency on MR OpenXR Plugin.

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11524]
# Overview

The [Mixed Reality OpenXR Plugin v1.8.0](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/releases/tag/v1.8.0) removed support for Android.  Andriod is no longer being supported by Microsoft's plug-in.  Unfortunately, MRTK3 still relies on the MR OpenXR Plugin for Android Hand Joints.

# Fix

Instead of relying on the MR OpenXR Plugin for Android Hand Joints, MRTK3 should use other methods for obtaining hand joints.

**Comment by mschult2** [comment]
I think I have a similar problem. But I'm not even building Android w/ OpenXR, I'm building Android w/ ARCore. No MRTK needed for my Android mobile target.

Even so, the mere presence of the MRTK package is causing the build to fail.

Any workarounds?

```
Library\PackageCache\com.microsoft.mrtk.input@473ce5ad9479\Subsystems\Hands\OpenXRHandsSubsystem.cs(8,30): error CS0234: The type or namespace name 'OpenXR' does not exist in the namespace 'Microsoft.MixedReality' (are you missing an assembly reference?)
```

**Comment by AMollis** [comment]
@mschult2, before we resolve this issue, you have to downgrade to an earlier version MR Open XR Plugin.  Trying switching to v1.7.2

https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/releases/tag/v1.7.2

**Comment by AMollis** [comment]
Open XR v1.8.1  added Android support back.  So this is no longer needed

- https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/releases/tag/v1.8.1

**Comment by mschult2** [comment]
Great! I’ll upgrade OpenXR 1.8.0 to 1.8.1, then rebuild my MRTK app for Android.
