### ISSUE TITLE
Using Microsoft.MixedReality.OpenXR not found in MRTK3 preview 14

### ISSUE THREAD

**Issue by jasonodomtaqtile** [microsoft/MixedRealityToolkit-Unity#11520]
## Describe the bug

"using Microsoft.MixedReality.OpenXR;" Not Found during the compilation of Android-based project. There was a missing reference in the assembly definition.

## Your setup (please complete the following information)

- Unity Version [Unity 2021.3.21f1]
- MRTK Version [v3 preview 14]

## Target platform (please complete the following information)

- Qualcomm Spades

## Additional context

Opening the Microsoft.MixedReality.OpenXR.asmdef in a text editor and adding  "Android" as an option in the "include Platforms" section fixed this issue for me.

**Comment by AMollis** [comment]
@jasonodomtaqtile  what version of "Mixed Reality OpenXR Plugin" are you using?  In version 1.8.0 we have removed support for Android

https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/releases/tag/v1.8.0

If you still require Android support please downgrade to v1.7.2

https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/releases/tag/v1.7.2


I've opened a separate issue to remove MRTK3's dependency on the MR OpenXR Plugin for Android

- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11524

**Comment by AMollis** [comment]
Resolving as Won't Fix, since Android support was removed from the "Mixed Reality OpenXR Plugin"
