### ISSUE TITLE
Text clipping region in the `VirtualizedScrollRectList` sample scene is not great

### ISSUE THREAD

**Issue by marlenaklein-msft** [microsoft/MixedRealityToolkit-Unity#11537]
## Describe the bug

In the sample scene, the backplate or the clipping region is not sized properl.  The list items are visible outside of the bounds of the backplate.  We should resize the backplate or clipping region of this sample scene.  

Also, verify that `VirtualizedScrollRectList` don't have this clipping issue, and fix as needed.

## To reproduce

Play VirtualizedScrollRectList sample scene.

## Screenshots

![image](https://user-images.githubusercontent.com/125413876/236066931-ad4f3364-0dd1-425b-b1ec-58d384df972a.png)

## Additional Context

Upon starting the sample scene, the list starts scrolling and does not stop until you click the up or down button.  This is by design.

**Comment by AMollis** [comment]
@marlenaklein-msft  the auto scrolling is by design (see our manual tests doc 😉).  

I'm updating the title to fix clipping

**Comment by AMollis** [comment]
This has been fixed
