### ISSUE TITLE
Validate MRTK3 in Unity 2022

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11548]
## Describe the problem

MRTK3 needs to be verified that it works in Unity 2022 before MRTK3 GA

## Describe the solution you'd like

- [ ] Update MRTK3 sample project to Unity 2022 (don't commit)
- [ ] Run a manual test pass in Editor and on HL2 device

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by shaynie** [comment]
Upgraded to Unity 2022.2.19  
Passed all automated and manual tests.
Good to go.
