### ISSUE TITLE
Mixed Reality Toolkit menu resets old settings.

### ISSUE THREAD

**Issue by amrittb** [Microsoft/MixedRealityToolkit-Unity#1154]
Not an important issue, but when Applying Mixed Reality Project Settings (**Mixed Reality Toolkit > Configure > Apply Mixed Reality Project Setting**s) in already configured project, it restores the build platform to Standalone. This happened to me when trying to **only** import XBOX mapping into the project. Also, I was asked to give permission to download input manager from Github e**ven after unchecking** the 'import xbox mapping' option.

**Comment by StephenHodgson** [comment]
The toggles all act as switches to the settings, either enabling or disabling the settings.

Sorry, this was unintuitive.
Generally you want to leave the UWP, XR, and Direct 3D options on, _unless_ you don't want them.

It _is_ strange that the propmpt to download even after unchecking the `Import Xbox Settings` though.

**Comment by amrittb** [comment]
Thanks for clearing that up.
