### ISSUE TITLE
[MRTK3] When the MetaXR feature is enabled in the OpenXR Feature Group, the Ray is no longer displayed in Quest hand tracking.

### ISSUE THREAD

**Issue by spg666** [microsoft/MixedRealityToolkit-Unity#11553]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/113

___

## Describe the bug

When the MetaXR feature is enabled in the OpenXR Feature Group, the Ray is no longer displayed in Quest hand tracking.

## To reproduce

1. Use the VR template of Unity 2021.3.25f1.
2. Install Mixed Reality OpenXR 1.7.2, MRTK Input 3.0.0-pre15, MRTK UX Components 3.0.0-pre15 using MixedRealityFeatureTool.exe.
3. Install Oculus Integration SDK 53.1.
4. Enable MetaXR feature in the OpenXR Feature Group.
5. Build and run on Quest 2.
6. Notice that the Ray is not displayed during hand tracking.

## Expected behavior

Even when the MetaXR feature is enabled, the Ray should still be visible during hand tracking on Quest.

## Your setup (please complete the following information)

- Unity Version: 2021.3.25f1
- MRTK Version: 3.0.0-pre15
- Mixed Reality OpenXR: 1.7.2
- Oculus Integration SDK: 53.1

## Target platform (please complete the following information)

- Quest2

## Additional context

When the MetaXR feature is deactivated within the OpenXR Feature Group, the Ray properly appears during hand tracking on the Quest. 
Furthermore, while the hand tracking system allows for successful button interaction, it fails to respond to the ObjectManipulator.
The Ray is visible when using Oculus Link to run the application within the Unity Editor.

**Comment by MickGerrit** [comment]
I was having the same issue... I walked into this issue because I tried to make passthrough working by importing Oculus Integration. With MetaXR enabled, not only does the ray not folllow hands anymore, I could also not do any pinch interactions. But... I was able to press buttons with the tip of my index finger

**Comment by Phantomxm2021** [comment]
I was having the same issue. And I have debug the `MRTKRayInteractor` -> `Update` [the `aimPose` and `devicePose` value are always **0** ]

**Comment by Ali-Can-Keskin** [comment]
I face the exact same thing when trying to make passthrough work. I now see this is not planned but is enabling passthrough on Quest (2/3/Pro) is planned or is it already available?
