### ISSUE TITLE
AssetBundle Is Visible Only in Left Eye

### ISSUE THREAD

**Issue by purpleharp** [microsoft/MixedRealityToolkit-Unity#11561]
## Describe the bug
I Create an Empty Scene and Load a cube by AssetBundle, The Cube Is UnVisible in RightEye, How to handle it. My Platform is Hololens

## Your setup (please complete the following information)

- Unity Version [ 2020.3.46f1]
- MRTK Version [2.8.3]

## Target platform (please complete the following information)

- HoloLens1

**Comment by shaynie** [comment]
@purpleharp, this sounds like your Render Mode is set to Single Pass Instanced, but the cube has a material that uses a shader that doesn't support single pass.  The MRTK standard shader supports single pass, so let us know if you are already using it.  If it is a custom shader, take a look here for how to modify it to support single pass:  https://docs.unity3d.com/Manual/SinglePassInstancing.html

**Comment by AMollis** [comment]
@purpleharp can you kindly follow-up with @shaynie's question?

We suspect that the shader you are using doesn't support single pass instancing.   The simplest test is to set the mesh's material to one of the built-in MRTK materials.  The MRTK shader correctly supports single pass instancing.

**Comment by AMollis** [comment]
@purpleharp closing this issue as external issue.

If you find that there is a problem with the MRTK2 shaders, please open a new issue
