### ISSUE TITLE
Unable to import SharingClient.dll to VS2017

### ISSUE THREAD

**Issue by eluchsinger** [Microsoft/MixedRealityToolkit-Unity#1156]
Can't import the `SharingClient.dll` in VisualStudio. There is an issue that already explains the [issue](https://github.com/Microsoft/MixedRealityToolkit/issues/107) in the MRT repo.

Furthermore, I can't run the `BuildAll.bat` script. I get errors, because it is looking for dependencies from VS2015. I have installed almost every possible component of VS2017, but it still fails. I installed VS2015 community edition with default components and it seems to work (at least, it's doing something right now.)

**Comment by StephenHodgson** [comment]
This issue is unrelated to this repo.

**Comment by eluchsinger** [comment]
Well I read the documentation in this repo, so I opted to open the issue here. If you want you can close the issue then.
