### ISSUE TITLE
Singleton instance not initializing properly.

### ISSUE THREAD

**Issue by HattMarris1** [Microsoft/MixedRealityToolkit-Unity#1157]
I'm using the most recent master branch, using Unity editor 2017.1.2f1

`The WorldAnchorManager singleton instance is being accessed while it's null. Make sure it's included in the scene, and your initialization/deinitialization sequence is compatible with singletons.
UnityEngine.Debug:LogErrorFormat(String, Object[])
HoloToolkit.Unity.Singleton \'1:get_Instance() (at Assets/HoloToolkit/Utilities/Scripts/Singleton.cs:21)
HoloToolkit.Sharing.Utilities.<AutoConnect>c__Iterator0:MoveNext() (at Assets/HoloToolkit/Sharing/Scripts/Utilities/AutoJoinSessionAndRoom.cs:248)`

**Comment by StephenHodgson** [comment]
It's not directly related to the Sharing service.  

As a quick fix, change the script execution order until the errors go away.  We've not to look into improve the `Singleton Instantiation` better.

To change the script execution order: `Edit/Project Settings/Script Execution Order` and add the offending scripts and make them run first.

**Comment by StephenHodgson** [comment]
See #1123
