### ISSUE TITLE
DictationSample scene - cannot move the scene description panel

### ISSUE THREAD

**Issue by shaynie** [microsoft/MixedRealityToolkit-Unity#11581]
## Describe the bug

Other example scenes let you drag the entire scene contents by grabbing the description panel and moving it.  In the DictationExample scene the description panel is locked in place.

## To reproduce

1. Load the DictationExample scene in the Unity editor
2. Run the scene
3. Using input simulation, note that you cannot select the description panel.

## Expected behavior

The description panel should be interactable and move the scene content.

**Comment by AMollis** [comment]
Tracking with 

- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11580
