### ISSUE TITLE
Error when opening MRTK

### ISSUE THREAD

**Issue by kylegag** [Microsoft/MixedRealityToolkit-Unity#1159]
Upon opening the MRTK(just downloaded) in Unity 2017.1.2f1 I get the following error: 
Assets/HoloToolkit/BuildAndDeploy/Editor/XdeGuestLocator.cs(57,17): error CS0815: An implicitly typed local variable declaration cannot be initialized with `null'

**Comment by StephenHodgson** [comment]
Fixed in PR #1158
