### ISSUE TITLE
MRTK3: NonNativeKeyboard Prefab - Missing Textures

### ISSUE THREAD

**Issue by oculavis-cvar** [microsoft/MixedRealityToolkit-Unity#11606]
## Describe the bug

Textures e.g. for arrows seem to be missing for the non native keyboard.

## To reproduce

Open the NonNativeKeyboard prefab after setting up a project (in this case with Android as a build target) and adding MRTK3.pre16 to it (all packages except Accesibility, Text To Speech and Speech are installed).

## Expected behavior

The keyboard sprites are not missing.

## Screenshots

![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/124585152/6b99349b-260e-420e-a303-2283a33b12b3)
![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/124585152/102e57c6-603a-452b-968b-e2c13d83e669)

## Your setup (please complete the following information)

- Unity Version 2022.2.21
- MRTK Version MRTK3.pre16

## Target platform (please complete the following information)

- MagicLeap 2 / any Android target

**Comment by marlenaklein-msft** [comment]
Thanks for reporting the bug! Will update the sprite references.

**Comment by marlenaklein-msft** [comment]
Issue should be fixed with this PR #11608.
