### ISSUE TITLE
Can't build for Android with Unity 2022.2.11

### ISSUE THREAD

**Issue by ShayneRC** [microsoft/MixedRealityToolkit-Unity#11612]
## Describe the bug

Every build fails with this exception: Cannot include plugin 'Packages/com.microsoft.azure.remote-rendering/Plugins/WSA/ARM64/Microsoft.Holographic.HybridRemoting.lib' (Key: microsoft.holographic.hybridremoting.lib;None) since plugin with the same name and architecture was already added ('Packages/com.microsoft.azure.remote-rendering/Plugins/x86_64/Microsoft.Holographic.HybridRemoting.lib (Architecture: None)').

We were previously on Unity 2020.3.36 and MRTK 2.7.2. We upgraded to Unity 2022.2.11 to hopefully fix a separate issue but first ran into an issue with some scripts (noted below) so we upgraded to the latest MRTK 2.8.3 which fixed those script issues. This let me start a new build for Android (targeting the Meta Quest Pro) which promptly fails with the error above. I'm guessing this means that Unity 2022 is not supported yet? I couldn't find any documentation stating which Unity versions MRTK 2.8.3 supports.

Scripts that had issues with MRTL 2.7.2 and Unity 2022.2.11:
- Tools/MSBuild/Scripts/Utilities.cs
- Foundation/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs

## To reproduce

1. Have everything set up with plugins, MRTK etc stated below (not sure if the plugins are relevant here or not).
2. Build Settings > Android > Device selected > Build And Run.
3. Build will fail with error above.

## Expected behavior

I expected those files to have different build architectures set so an Android build will not fail. Because they are part of the package I cannot modify them - unless I'm missing something.

## Screenshots

Full stack trace:
```
Exception: Cannot include plugin 'Packages/com.microsoft.azure.remote-rendering/Plugins/WSA/ARM64/Microsoft.Holographic.HybridRemoting.lib' (Key: microsoft.holographic.hybridremoting.lib;None) since plugin with the same name and architecture was already added ('Packages/com.microsoft.azure.remote-rendering/Plugins/x86_64/Microsoft.Holographic.HybridRemoting.lib (Architecture: None)').
UnityEditor.Android.AndroidBuildPostprocessor.CollectPlugin (System.String path, Unity.Android.Types.AndroidArchitecture architecture, System.Collections.Generic.Dictionary`2[TKey,TValue] pluginContainer) (at <9abad5b5f4714a9c834c3a12a1e7cdc6>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PluginsDataFor (UnityEditor.Modules.BuildPostProcessArgs args) (at <9abad5b5f4714a9c834c3a12a1e7cdc6>:0)
UnityEditor.Modules.BeeBuildPostprocessor+<GetDataForBuildProgramFor>d__44.MoveNext () (at <9dccbc75b8a249d78358fb192f335670>:0)
UnityEditor.Android.AndroidBuildPostprocessor+<GetDataForBuildProgramFor>d__25.MoveNext () (at <9abad5b5f4714a9c834c3a12a1e7cdc6>:0)
System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () (at <40b481cb584843bbbf4c840095ac6811>:0)
Bee.BeeDriver.BeeDriver.WriteDataForBuildProgram (Bee.BeeDriver.InternalState state, System.Threading.Tasks.TaskCompletionSource`1[TResult] dagGenerationCompletionSource) (at <121dc6afd18c416ebb3890a6cc2efeb0>:0)
Bee.BeeDriver.BeeDriver+<>c__DisplayClass0_0.<BuildAsync>g__WriteData|0 () (at <121dc6afd18c416ebb3890a6cc2efeb0>:0)
Bee.BeeDriver.BeeDriver.BuildAsync (Bee.BeeDriver.BuildRequest buildRequest, System.Threading.CancellationToken cancellationToken) (at <121dc6afd18c416ebb3890a6cc2efeb0>:0)
UnityEditor.Modules.BeeBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at <9dccbc75b8a249d78358fb192f335670>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```

## Your setup

- Unity Version 2022.2.11
- MRTK 2.8.3
- OpenXR 1.5.3
- Oculus Integration 53.1

## Target platform

- Meta Quest Pro

## Additional context

I could build perfectly fine prior to upgrading Unity and MRTK. Upgrade processes ran smoothly apart from those script errors above.

**Comment by AMollis** [comment]
@ShayneRC , your issue appears to be related to Azure Remote Rendering. 

I encourage you to open an issue here.  https://github.com/Azure/azure-remote-rendering/issues
