### ISSUE TITLE
MRTK support for Apple VisionOs and Vision Pro

### ISSUE THREAD

**Issue by njannink** [microsoft/MixedRealityToolkit-Unity#11611]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/88

___

With the upcomming release of Apple VisionOs what will be the vision of MRTK for supporting this and the Apple Vision Pro.

Would love some insights to be able to form our architecture roadmap.

**Comment by camnewnham** [comment]
Based on the [packages used](https://youtu.be/UajMl7ckrqQ?t=727) some thoughts/discussion points:
- I expect MRTK3 UI to work out of the box
- I suggest MRTK3 Input package should migrate/support Unity's XR Hands package. Hopefully not a huge task, see: https://localjoost.github.io/Getting-Unity-XR-hands-to-work-on-HoloLens-and-Quest-in-a-bare-bones-project/
- There is no mention of OpenXR and instead seems to be ARFoundation (ARKit) - so some app changes required but given that minimal work is required to get an MRTK3 app running on ios/android with ARFoundation I expect this to also be mostly out of the box.

For early testing, you can apply to Unity's beta program: https://create.unity.com/spatial

Disclaimer: Not a core MRTK contributor

**Comment by AMollis** [comment]
Thank you @njannink ,  at this time we have no plans to support Apple Vision Pro.  However, community contributions are welcome, and we encourage the community to add this support.

**Comment by yosun** [comment]
Needs to be reconsidered https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/88
