### ISSUE TITLE
Fixed MRTK3 StateVisualizer tests fail sporadically during PR validation: TestWaitForLongRunningEffect and TestSleepWakeBehavior

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11616]
# Overview

StateVisualizer tests fail sporadically during PR validation: TestWaitForLongRunningEffect and TestSleepWakeBehavior

**Comment by marlenaklein-msft** [comment]
Additionally, the GazeDwellTest fails sporadically in the TestRunner (not observed during PR Validation).

**Comment by AMollis** [comment]
We believe this is fixed now
