### ISSUE TITLE
Spatial Awareness not functioning in Play Mode in any project

### ISSUE THREAD

**Issue by tlarregle-sig** [microsoft/MixedRealityToolkit-Unity#11613]
## Describe the bug

I am developing an app for the HoloLens 2, and I was testing it through the Holographic Remoting in play mode with Unity.

Through my development, I noticed that I can't use the spatial awareness anymore, even if I checked the "Enable Spatial Awareness System" and I set the display settings of the mesh observer to "Visible". I also tried the default profiles that enable the spatial awareness.
When I tried to open other projects where it was initially working, I am running the same issue, regardless of the Unity version. Going to an earlier version of my project didn't work.

I followed the basic tutorial to setup an app for the HoloLens on a blank project, it didn't work either.

However, when I build the project to deploy on the HoloLens, the spatial awareness works fine and the meshes of the spatial awareness are correctly displayed.

I've been trying to solve it and I don't see anyone having this issue, did anyone experience anything like this?

## Expected behavior

The spatial awareness is initialised, and the mesh of the environment appear in the scene. 

## Your setup (please complete the following information)

- Unity Version 2021.3.16f1
- MRTK Version 2.8.0
- OpenXR plug-in version 1.8

## Target platform (please complete the following information)

- HoloLens 2

**Comment by tlarregle-sig** [comment]
After further investigations and tests, the build version crashes randomly. When I look at the dump file, it gives me the error 0xc0000005 with "Openxr_runtime_debugger.pdb not loaded".

I tried to switch the profile to "DefaultHololens2ConfigurationProfile" and it stopped crashing like it used to. When I enabled the spatial awareness in this profile  -because it isn't activated by default- it starts crashing again.

This crash occurs only when I enable the spatial awareness in my Toolkit.

**Comment by tlarregle-sig** [comment]
Some updates, the build version has been rectified, it came from a bad configuration of the HoloToolkit, I made a new profile from scratch and made some tests and now it works without any crash. 

Still can't have the spatial awareness in play mode though.

**Comment by zenorbi** [comment]
For me the uninstall of Vive Streaming Hub and Vive Business Streaming solved the issue. What tipped me off was that I saw this in the Player.log and Editor.log files when starting the remoting session: `System Properties: Name="Vive OpenXR: Vive SRanipal", VendorId=2996`

**Comment by tlarregle-sig** [comment]
Hey, sorry for the very late answer, I didn't have the opportunity to try it out earlier. 
Indeed, I had these two Vive applications and uninstalling them made the spatial awareness work again. 

Thank you very much for your answer, i'll close the issue.
