### ISSUE TITLE
Steam VR compatibility with MRTK

### ISSUE THREAD

**Issue by UttamB11** [microsoft/MixedRealityToolkit-Unity#11621]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/83

___

## Overview
We are trying to currently implement streaming with Steam VR and MRTK. When testing we found that the scene runs, however we are not able to interact with MRTK's Object such as buttons.

## Expected behavior
Steam VR inputs should work with MRTK inputs to interact with MRTK Components.

## Actual behavior
When using MRTK with Steam VR, the inputs of steam VR do not get mapped with MRTK and cannot interact with the other components.

## Steps to reproduce
Install Steam VR and MRTK.
Open any sample scene of Steam VR and add a MRTK Component to the scene.
Build and run.

You will notice that you cannot interact with the component

## Unity editor version
2021 (LTS)

## Mixed Reality Toolkit release version
MRTK 3 pre 16

**Comment by AMollis** [comment]
@UttamB11 unfortunately at this time we don't support Steam VR.  However, we will accept Pull Requests from the community that enable this support in MRTK3.

Without any investigation on my part, I suspect that the default actions defined in "[MRTK Default Input Actions](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk3/com.microsoft.mrtk.input/Assets/Input%20Actions/MRTK%20Default%20Input%20Actions.inputactions)" asset need to be updated to also support Steam VR.  

![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/36461279/c1266c96-10c6-40be-8dcb-01a11cfd3d38)

**Comment by UttamB11** [comment]
Thanks for letting me know. Currently, since I need to do this, I will try to rebind the MRTK Inputs with Steam VR Inputs to see if that works.
The idea is that when an input is detected on Steam VR's end, it will automatically map that input action to the same one in MRTK to add the interaction.
