### ISSUE TITLE
Move MRTK3's `MRTKRayReticleVisual::LocateTargetHitPoint` to common location so it can be shared

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11649]
# Overview

Consider Moving MRTK3's `MRTKRayReticleVisual::LocateTargetHitPoint` to `BaseReticleVisual`.  Both `MRTKRayReticleVisual` and the new spatial mouse reticle share very similar logic.  We should consider moving `LocateTargetHitPoint` to some common location.

**Comment by marlenaklein-msft** [comment]
Closed with #11699.
