### ISSUE TITLE
Support for April tags Detection in Hololens 2

### ISSUE THREAD

**Issue by hemasree99s** [microsoft/MixedRealityToolkit-Unity#11640]
Support for April tags Detection in Hololens 2

**Comment by AMollis** [comment]
@hemasree99s , thank you for your feature request.   Unfortunately this request is not directly related to MRTK.  Instead, can you please provide feedback via one of our other Mixed Reality feedback portals.  You can find more ways to provide feedback here: https://learn.microsoft.com/en-us/hololens/hololens-feedback

Thank you!
