### ISSUE TITLE
Cannot open MRTK C# projects in Visual Studio 2017

### ISSUE THREAD

**Issue by kylegag** [Microsoft/MixedRealityToolkit-Unity#1164]
After following steps 1-4 as described in MixedRealityToolkit-Unity/GettingStarted.md, I set Build Settings to the following : 
![build_settings](https://user-images.githubusercontent.com/30510888/31587772-1b718e7e-b1ad-11e7-877d-98ce11c1e5fa.JPG)
 I then build and attempt to open the file using Mixed Reality Toolkit -> Build Window -> Open Project Solution. 
VS 2017 then gives me this error message: 
![vs_error](https://user-images.githubusercontent.com/30510888/31587776-2258e8a4-b1ad-11e7-8ebe-7416b7a71052.JPG)

Here are the Individual Components I have installed for VS 2017:
[Individual_Components.pdf](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/1385650/Individual_Components.pdf)

**Comment by StephenHodgson** [comment]
What version of the editor do you have?

**Comment by kylegag** [comment]
Unity 2017.1.2f1 and I'm using the latest release of the HoloToolkit for Unity 2017.1.2f1 released 9 days ago

**Comment by StephenHodgson** [comment]
You can't build to the 16299 SDK if you don't have the fall creators update and unity 2017.2.

**Comment by kylegag** [comment]
Ah okay thank you
