### ISSUE TITLE
Update subsystem documentation to reflect migration to input package

### ISSUE THREAD

**Issue by marlenaklein-msft** [microsoft/MixedRealityToolkit-Unity#11644]
Relevant docs, for [dictation](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-core/packages/core/subsystems/dictationsubsystem) and [keyword recognition](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-core/packages/core/subsystems/keywordrecognitionsubsystem) subsystems, should be updated.

**Comment by AMollis** [comment]
This is not needed anymore given the move was undone

- https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11651
