### ISSUE TITLE
Update MRTK3's min input package version to v1.6.1 

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11648]
# Overview

Before 1.6 mouse input did not always work on HL2.  We should update to the latest version of the input package before GA.  Use version 1.6.1

# Tasks

- [x] Update package.json files to reference 1.6.1
- [x] Update sample app's package manifest to use 1.6.1

**Comment by marlenaklein-msft** [comment]
Closed with #11661
