### ISSUE TITLE
Bugs in MRTK3 BoundsControl

### ISSUE THREAD

**Issue by Vincent-zhai-github** [microsoft/MixedRealityToolkit-Unity#11655]
## Describe the bug

After using bounds control function, deactivating the mounted gameobject and reactivating it after a while will result in two types of bugs:

1. The bounding box and handles appear directly and cannot be operated. After clicking on the gameobject several times, it returns to normal. 
2. The bounding boxes and handles cannot be activated again. 

## To reproduce

1. Go to a game object with BoundsControl
2. Click on this game object until the bounding box is hidden
4. Disable this game object
5. Enable this game object
6. The bounding box will be displayed and cannot be used

## Your setup

- Unity 2021.3+
- MRTK3 pre.14+

## Target platform

- HoloLens 2
- Unity Editor

## Screenshots

https://github.com/microsoft/MixedRealityToolkit-Unity/assets/51319222/3ed502ac-03df-4f9e-9b38-2c036b708d8d

**Comment by marlenaklein-msft** [comment]
@Vincent-zhai-github, thanks for reporting this! The issue should be closed with changes in #11698. The fix will be included in the next release.
