### ISSUE TITLE
MRTK3's `See-It-Say-It` label doesn't appear with gaze input

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#11667]
# Overview 

MRTK3's `See-It-Say-It` label doesn't appear with gaze input

# Reproduction

1. Open the see-it-say-it example scene
2. Hover a button using eye gaze.
3. Expected to see the `see-it-say-it` label....but it doesn't appear (bug)
4. Say "select", and button is invoked

**Comment by marlenaklein-msft** [comment]
Closed with https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11677
