### ISSUE TITLE
XR SDK Pipleline cannot detect OpenXR

### ISSUE THREAD

**Issue by mirages** [microsoft/MixedRealityToolkit-Unity#11669]
## Describe the bug

The MRTK Project Configurator show `XR Pipline Setting - XR SDK width builtin plugin (non-OpenXR) in use.`

## To reproduce

1. I create a demo project as [Introduction to the Mixed Reality Toolkit-Set Up Your Project and Use Hand Interaction](https://learn.microsoft.com/en-us/training/modules/learn-mrtk-tutorials/1-5-exercise-configure-resources?tabs=openxr)
2. When I finished the `Show XR Plug-In Management Settings` step (select the openXR and fixed issues), the `MRTK Project Configurator` still show `Show XR Plug-In Management Settings`, not the `Apply Settings`. Although I reopened the project， this problem still exists.
3. Then I close the `MRTK Project Configurator` window, and add `Add to Scene and Configure...`, then I open the `MRTK Project Configurator` window, it show like this:
<img width="1181" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12791299/fac399e2-102b-4852-8de3-e341621abf51">

## Expected behavior

The tutorial shows that it should like this：
<img width="810" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12791299/eb731def-69b4-422f-8dea-31e8e4d7a814">

## Screenshots

My project setting：
<img width="950" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12791299/a68d1f00-b7e0-447d-b8dc-f129949a90c9">
<img width="951" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12791299/b75ea9c7-0835-47b5-8cc5-336b5763cebc">
<img width="643" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12791299/b3432a70-dc91-4719-98f9-5ee7ba51eb99">

## Your setup (please complete the following information)

- Unity Version
<img width="723" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12791299/ce81ee3f-59da-4a4c-a1dc-cb7c809852d7">

- MRTK Version or Commit 
<img width="793" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12791299/694ea70f-fcfe-46fc-9ae5-eb6aede732ab">

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

none

**Comment by AMollis** [comment]
@mirages , this looks like a documentation bug, can you please open an issue in the documentation repository? 

Note, we are in the process of updating these tutorials to use MRTK3.   So the MRTK2 images will likely not be updated to match the actual behavior
