### ISSUE TITLE
"Look rotation viewing vector is zero" gets printed continuosly in MRTK 3 

### ISSUE THREAD

**Issue by hemasree99s** [microsoft/MixedRealityToolkit-Unity#11670]
I was trying to update raystep by collecting the origin from MRTKRayInteractor->rayOriginTransform and endRayposition using MRTKRayReticleVisual->Reticle, "Look rotation viewing vector is zero" is getting printed continuosly in MRTK 3

Below is the sample code, 
![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/47776870/c50248db-b73b-422a-b826-ea41897464cf)

**Comment by AMollis** [comment]
@hemasree99s why do need to access the ray origin transform and reticle transform?  If this is for obtaining the interactor's intersection points, I would recommend not doing this.

Instead see my response your discussion post here:

https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/11636#discussioncomment-6364662
