### ISSUE TITLE
Bug: Keyboard not deleting final character

### ISSUE THREAD

**Issue by bkfichter** [Microsoft/MixedRealityToolkit-Unity#1169]
Using the Keyboard prefab to type into an inputfield-
When using backspace to remove characters, the final character is not deleting from the input field.
If you highlight the character and type any other character, it still does not delete or replace.

**Comment by StephenHodgson** [comment]
Duplicate of #917

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
