### ISSUE TITLE
MRTK Profile Goes Null - Probably a Unity Package Manager thing

### ISSUE THREAD

**Issue by JShull** [microsoft/MixedRealityToolkit-Unity#11691]
## Describe the bug

MRTKProfileEditor.cs throws a null reference on Line 264 if the serializedMixerGroup is null. This then causes a sort of cascading effect in which the Unity Editor while you try to use the editor window to select the various profiles - doesn't draw and just says 'null'. I wouldn't go far to say this is a bug, as I quickly fixed it by reimporting the Microsoft Spatializer package via the MRTK feature tool. I just wanted to document this because I'm sure someone else out there might run into a similar issue. Maybe some sort of way to remind users to check and/or reinstall the Spatial Audio Package? The Project Validation didn't catch it - so I' really think this is a unique one off with the Package Manager and/or something getting out of order. I did have it installed, and when I first open Unity said I had it installed. I came back into Unity, had some other stuff and noticed that the profile said null. I then looked and saw that everything was where it should be, ran the Project Validation = no issues. However, the MRTK Feature Tools did not see it, so to me that was a nice catch and it reinstalled them and that error went away so you can probably ignore this and/or immediately close this as it more than likely is something with Unity Package Manager fritzing out and less you all - but just wanted to report it!

## To reproduce

No clue - I opened up Unity and it was just null. It worked the first time I opened it up but somewhere in there Unity and/or my MRTK Profile lost that reference information. 

## Screenshots

What I did as a quick fix - just so I could see the Profile in the editor - was modify the DrawSelectedMixer() function to do a quick null reference check on the serializedMixerGroup parameter. This then at least showed me the scriptable object profile in the editor but I don't think actually solves the core problem.

![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12342337/72c8a3dc-1748-4958-b5bb-8c34adae90d4)

Without this quick hack of a fix you see this in the editor -->
![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12342337/b515af54-bab9-4bf7-87f2-1b580156ec7b)

With my quick hack of a fix you see this in the editor -->
![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12342337/609e9e13-2e11-4893-8179-65b82fb32ac9)

## Your setup (please complete the following information)

- Unity Version [e.g. 2021.3.28f1]
- MRTK Version or Commit [mrtk3](https://github.com/microsoft/MixedRealityToolkit-Unity/commit/7bff152e5bcec49ad306949443f9ddaced091b0c)

## Target platform (please complete the following information)

- UWP for HoloLens 2

## Additional context

Again - just wanted to report it because I feel like that area within the code could also remind users to check their Spatial Audio

**Comment by AMollis** [comment]
Fixed with

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11694
