### ISSUE TITLE
Capability to set custom cursor in MRTK 3 for far ray

### ISSUE THREAD

**Issue by amea32179** [microsoft/MixedRealityToolkit-Unity#11702]
We could not set a custom cursor at runtime since Base Reticle and Reticle Root of MRTKBaseReticalVisual of MRTK Right Hand Controller of far ray is not accessible.

**Comment by AMollis** [comment]
If you are just wanting to change the reticle when hovering over an interactable, have you tried using the "custom reticle" property on the interactable itself.  This will change the cursor when you hover over the interactable.

![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/36461279/723a13a0-6313-4e41-8a66-2d2abb7ef28e)

If you want to change the cursor, regardless of what interactable is being hovered, I recommend finding the `BaseReticleVisual` on the interactor, and call the `BaseReticleVisual.AttachCustomReticle`.  This will hide the default reticle, and show your custom one.  Note, as soon as you hover over an interactable with a custom reticle set, this will be cleared.

If you want to change the cursor regardless of what interactable is being hovered and without calling `BaseReticleVisual.AttachCustomReticle`, you'll need create a variant of the `MRTK LeftHand Controller` and change the Far Ray's reticle to your own game object.  Your game object could then manage its own visual as it sees fit.

![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/36461279/37f4d244-891c-4691-bc50-9bf90d5df370)

At this time, we don't believe it necessary to expose the underlying reticle game objects. If you have concerns or comments, please follow-up with this thread:

https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/11688
