### ISSUE TITLE
Content masking using unity ui scroll view not working with 16 bit depth submission mode

### ISSUE THREAD

**Issue by h421qqq** [microsoft/MixedRealityToolkit-Unity#11709]
## Describe the bug

I have text in a scroll view that is masked so the user can scroll to read. In unity play mode, it works as expected. when deployed on my hololens 2 with Depth Submission Mode set to 16 bit, the text does not appear masked and can be seen overflowing. when deployed with depth of 24 bit it works as expected. (correct me if this is the proper way to deploy but i get the "depth should be set to 16 bit" in the project validation thing)

1. Make a scene with the Unity UI scroll view.
2. Add text to the scroll viewthat overflows the view port.
3. Deploy to Hololens 2 with 16 bit depth submission mode and see overflowing text.

## Expected behavior

Proper content masking with 16 bit depth submission mode.

## Screenshots

When trying to screenshot, the scroll view looks fine. However in person, on the hololens2, the text is overflowing

## Your setup

- Unity Version 2022.3.1f1
- MRTK3 commit e807733

## Target platform
- HoloLens 2

**Comment by AMollis** [comment]
@h421qqq , if you are using UGUI, you'll have to use 24 bit depth for the clipping to work. The UGUI relies on the stencil buffer to clip the scrolling button list. The stencil buffer is only available when the depth submission mode is set to 24-bit. To properly render UGUI using the Unity Scroller, please make sure to configure Depth Submission Mode to be 24-bit, under Project Settings > XR Plug-In Management > OpenXR.  


I recommend taking a look at our `VirtualizedScrollRectList` scene, for a sample of how-to setup a scroller with MRTK UI elements.
