### ISSUE TITLE
Notified when a specific SyncPrimitive changes

### ISSUE THREAD

**Issue by kyleWillson** [Microsoft/MixedRealityToolkit-Unity#1170]
I am trying to understand how to setup sharing, while setting up an exploratory test I was wondering something.  From what I can tell, if a SyncPrimitive child changes in a SyncObejct, the ObjectChanged flag will be fired.  But does that ObjectChanged flag tell you which particular SyncPrimitive Child changed? Or does it just say, "hey, there was a change in the children"?  Which is the way I think it works.  Is that correct?

So based on above, if I want to be notified of which particular SyncPrimitive Changed, I wrap SyncBool in a SyncObject wrapper.  Like this: 
```
[SyncDataClass]
public class SyncNotifyingBool : SyncObject
{
    [SyncData] public SyncBool IsActive;
}
```
Now I can be notified when individual SyncPrimitives Change in my SyncObejct class like:
```
[SyncDataClass]
public class SyncSpawnedTestContainer : SyncSpawnedObject
{
    [SyncData] public SyncNotifyingBool IsAActive;

    [SyncData] public SyncNotifyingBool IsBActive;
```

Is that generally the right idea overall?

**Comment by Ristophonics** [comment]
Hi Kyle,
I'm working on the same issue, trying to use the TransformSynchronizer.cs as a template for a BoolSynchronizer. Have you had any success so far with SyncBool?

**Comment by Ristophonics** [comment]
@Firifire here is the most stripped down version. Please post any improvement. Regards

`namespace HoloToolkit.Sharing
{

    public class BoolSynchronizer : MonoBehaviour
    {

        [SerializeField] public bool _thisToggle00;
        [SerializeField] public GameObject _GameobjectToToggle00;

        public SyncBool boolDataModel00;

        private void Start()
        {
            _thisToggle00 = false;
        }

        public void ToggleOffSwitch00()
        {
            if (_thisToggle00 == true)
            {
                Debug.Log("Toggling OFF");
                _thisToggle00 = false;
                boolDataModel00.Value = _thisToggle00;
                Debug.Log("Syncbool Value is NOW" + boolDataModel00.Value.ToString());
            }
        }

        public void ToggleOnSwitch00()
        {
            if (_thisToggle00 == false)
            {
                Debug.Log("Toggling ON");
                _thisToggle00 = true;
                boolDataModel00.Value = _thisToggle00;
                Debug.Log("Syncbool Value is NOW" + boolDataModel00.Value.ToString());
            }
        }

        private void CheckBoolStatus()
        {
            if (_thisToggle00 != boolDataModel00.Value)
            {
                _thisToggle00 = boolDataModel00.Value;
            }
        }

        private void FixedUpdate()
        {
            if (_thisToggle00)
            {
                _GameobjectToToggle00.SetActive(true);
            }
            if (!_thisToggle00)
            {
                _GameobjectToToggle00.SetActive(false);
            }
            CheckBoolStatus();
        }
    }
}`

**Comment by Firifire** [comment]
@Ristophonics Thanks. Seems like ObjectChanged was not working for me. 

Well, with your help. I am currently progressing like this.

I have altered SyncSpawnedObject to include two additional function

```
 ...      
        public virtual void SecondaryInitilize() //To initialize variables
        {

        }

        public virtual void AttachSync(GameObject instance) //To attach Synchronizer
        {

        }
```

Then in PrefabSpawnManager I add two lines 

```
...
            dataModel.Initialize(instanceName, parent.transform.GetFullPath("/"));
            dataModel.Transform.Position.Value = localPosition;
            dataModel.Transform.Rotation.Value = localRotation;
            dataModel.SecondaryInitilize(); //Initialize Variables

...
            // Setup the transform synchronization
            TransformSynchronizer transformSynchronizer = instance.EnsureComponent<TransformSynchronizer>();
            transformSynchronizer.TransformDataModel = dataModel.Transform;
            dataModel.AttachSync(instance); //Attach Sync

```

instead of adding variables to SyncSpawnedObject. I create another SyncDataClass inheriting SyncSpawnedObject, and overriding the functions

```
/// <summary>
/// A SpawnedObject contains all the information needed for another device to spawn an object in the same location
/// as where it was originally created on this device.
/// </summary>
[SyncDataClass]
public class SyncToggle: SyncSpawnedObject 
{
    [SyncData] public SyncTransform Transform;

    [SyncData] public SyncString Name;

    [SyncData] public SyncString ParentPath;

    [SyncData] public SyncString ObjectPath;

    [SyncData] public SyncBool NetworkBoolean00; // new SyncBool`

    public override void AttachSync(GameObject instance)
    {
        NetworkBoolean00 = false;
    }
    public override void AttachSync(GameObject instance)
    {
        BoolSynchronizer boolSynchronizer = instance.EnsureComponent<BoolSynchronizer >();
        boolSynchronizer.boolDataModel = NetworkBoolean00;
    }

```

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
