### ISSUE TITLE
CanvasSlider handle runs out of bounds

### ISSUE THREAD

**Issue by johannes-weidenfeller** [microsoft/MixedRealityToolkit-Unity#11718]
## Describe the bug

When using the CanvasSlider component and adapting the Min and Max values, the start and end point of the slider still correspond to values of 0 and 1. This causes the slider handle to 
i) not be positioned at the left edge when taking on the minimum value and
ii) run out of bounds if the maximum value is higher than 1 (see image below).

## To reproduce

Add a canvas slider component on a world space canvas and change the minimum and maximum values to values other than 0 and 1.

## Expected behavior

The slider start and end values should correspond to the minimum and maximum values set.

## Screenshots
![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/54772951/9f69ac62-2b81-499a-98ed-de04556fa6f4)

## Your setup (please complete the following information)

- Unity Version 2021.3.19.f1
- MRTK Version 3.0.0-pre.17

## Target platform (please complete the following information)
- HoloLens 2

**Comment by marlenaklein-msft** [comment]
@johannes-weidenfeller, thanks for reporting the bug! It should be fixed with this change #11742. Please reopen this thread if you continue to see any issues.
