### ISSUE TITLE
MRTK3 deploy on Hololens 2 crash on startup 

### ISSUE THREAD

**Issue by ChiaraLoca** [microsoft/MixedRealityToolkit-Unity#11716]
## Describe the bug

After deploy on Hololens 2 the applicatin load for few sends than crash.

This is the error shown:

Eccezione generata in corrispondenza di 0x00007FF882A7EA70 (GameAssembly.dll) in Marhvl_MRTK3.exe: 0xC0000005: violazione di accesso durante la scrittura del percorso 0x0000007D2B400D20.

## To reproduce

I followed the "Starting from a new project" guide and added a cube with Object manipulator
https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-new-project

## Expected behavior

The application starts and visulaizes the cube

## Your setup (please complete the following information)

- Unity Version 2021.3.15f1
- MRTK Version MRTK3 preview 17

## Target platform (please complete the following information)

- HoloLens 2

##Relevant Packages
"com.microsoft.mixedreality.openxr" : "file:MixedReality/com.microsoft.mixedreality.openxr-1.8.1.tgz",
    "com.microsoft.mrtk.core" : "file:MixedReality/com.microsoft.mrtk.core-3.0.0-pre.17.tgz",
    "com.microsoft.mrtk.graphicstools.unity" : "file:MixedReality/com.microsoft.mrtk.graphicstools.unity-0.5.12.tgz",
    "com.microsoft.mrtk.input" : "file:MixedReality/com.microsoft.mrtk.input-3.0.0-pre.17.tgz",
    "com.microsoft.mrtk.spatialmanipulation" : "file:MixedReality/com.microsoft.mrtk.spatialmanipulation-3.0.0-pre.17.tgz",
    "com.microsoft.mrtk.standardassets" : "file:MixedReality/com.microsoft.mrtk.standardassets-3.0.0-pre.17.tgz",
    "com.microsoft.mrtk.uxcomponents" : "file:MixedReality/com.microsoft.mrtk.uxcomponents-3.0.0-pre.17.tgz",
    "com.microsoft.mrtk.uxcore" : "file:MixedReality/com.microsoft.mrtk.uxcore-3.0.0-pre.17.tgz",
    "com.microsoft.spatialaudio.spatializer.unity" : "file:MixedReality/com.microsoft.spatialaudio.spatializer.unity-2.0.37.tgz",

**Comment by Victor-x1** [comment]
I believe the minimum Unity version to run Pre.17 is 2021.3.21f1. Try running your project with that version.

**Comment by AMollis** [comment]
@ChiaraLoca , can you share your entire package manifest?   It might be helpful to compare with our sample manifest (https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk3/UnityProjects/MRTKDevTemplate/Packages/manifest.json)

Also, it would be helpful if you'd shared a Unity project with an isolated reproduction of the problem.  As we are unable to reproduce the issue.

**Comment by AMollis** [comment]
@ChiaraLoca , we are unable to reproduce this issue. 

Also, it would be helpful if you'd shared a Unity project with an isolated reproduction of the problem. As we are unable to reproduce the issue.  Once you have this sample project, please create a new issue, or contact us and we'll reactive this issue
