### ISSUE TITLE
SharingSpawnTest scene throws null reference exception on device

### ISSUE THREAD

**Issue by HattMarris1** [Microsoft/MixedRealityToolkit-Unity#1171]
I'm using latest version of the master branch, unity 2017.1.2f1.

I've made sure the Internet client server and private network server are checked.

![image](https://user-images.githubusercontent.com/17457941/31624616-3260b8b4-b29b-11e7-9d3d-178790cdff0a.png)

I get this error in the roomandanchortest scene as well.

Thanks,

**Comment by StephenHodgson** [comment]
What's null?  The `SharingWorldAnchorManager.Instance` or the `gameObject` you're passing in?

**Comment by kyleWillson** [comment]
If I remember correctly I dont think those example scenes dont have SharingWorldAnchorManager on either the Stage gameobject or SharingManager.  If you add them it should fix it

**Comment by HattMarris1** [comment]
@kyleWillson that fixed it, thanks!

Shall I open a PR for this?

**Comment by StephenHodgson** [comment]
Sure
