### ISSUE TITLE
 'SpatialInteractionController' does not contain a definition for 'TryGetRenderableModelAsync'

### ISSUE THREAD

**Issue by linojon** [Microsoft/MixedRealityToolkit-Unity#1172]
Hi, trying to build example scene (MotionControllerTest). It runs in editor. Get this error when try to build:

Assets\HoloToolkit\Input\Scripts\Utilities\Extensions\InteractionSourceExtensions.cs(97,39): error CS1929: 'SpatialInteractionController' does not contain a definition for 'TryGetRenderableModelAsync' and the best extension method overload 'InteractionSourceExtensions.TryGetRenderableModelAsync(InteractionSource)' requires a receiver of type 'InteractionSource'

Using Unity 2017.2.0f3-MRTP
Windows 10 Pro build 16299.19
MRTK Dev_Unity_2017.2.0 branch

**Comment by StephenHodgson** [comment]
Do you have the latest SDK installed? 10.0.16267.0?

**Comment by linojon** [comment]
Thanks, that was it. Got it to build. (Yay) and run via VS. But the controller models dont show up (the data is updated like when Play in editor). I'm running the example scene with no modifications.

**Comment by linojon** [comment]
Is there a forum or slack to ask questions? i'd really like to figure out the controller models question. Thanks.

**Comment by HattMarris1** [comment]
There is -> https://holodevelopersslack.azurewebsites.net/

**Comment by linojon** [comment]
oh, MixedRealityCameraParent/MotionControllers was disabled in the scene by default. <happy dance>
Thank you guys for being so responsive.

**Comment by keveleigh** [comment]
The models not showing is likely timing with the driver. The first time you use the controllers in an app, the driver attempts to download the actual models. If they download during app usage, the models should pop in. Making sure you have the latest drivers wouldn't hurt either.

**Comment by StephenHodgson** [comment]
Huh strange. I'm pretty sure we enabled those on the prefab again. Did you get the latest release?

**Comment by keveleigh** [comment]
Never mind! Looks like you figured it out :) I believe we updated the prefab recently to make controllers on the default again.

**Comment by monsdar** [comment]
Had the same issue too, turned out I had the new (10.0.16299.0) and the old SDK installed (10.0.15063.0). I needed to switch the SDK to the new version in the Unity Build settings.

Not sure if this needs to be done manually or if my project is just a bit messed up. Wanted to let you know in case someone has the same issue.

**Comment by andijakl** [comment]
This issue also affects the main branch, so it also appears when building for HoloLens and using the default 15063 SDK for that. Not sure if switching to the 16299 SDK is the best solution for HoloLens?
