### ISSUE TITLE
HttpRequest Failed with Windows SDK Version 10.0.22000.0

### ISSUE THREAD

**Issue by mixedHans** [microsoft/MixedRealityToolkit-Unity#11737]
## Describe the bug

When using Windows 11-SDK 10.0.22261.0 instead of Windows 10 SDK 10.0.19041 to build a mixed reality application for the hololens 2 I am experiencing problems with System.Net.Http HttpClient SendAsync(myHttpRequest), which results in failing the operation with an AggregateException.

## To reproduce

1. Setup a new unity project following the recommended setup for hololens 2 mixed reality development without MRTK using OpenXR.
2. Build the project to the hololens using Target SDK Version 10.0.22000.0 in the build settings.
3. Try to send and receive a http request via using var myHttpResponse = await _myHttpClient.SendAsync(myRequest);
4. In the editor this works fine, but after building it to the hololens, the operation throws an AggregateException. 

## Expected behavior

I expected to send and receive an http message via System.Net.Http HttpClient with the SendAsync(request) method. Trying to do so results in an AggregateException.
"exception":"One or more errors occurred. (An error occurred while sending the request)"
"exception":"An error occurred while sending the request"
"exception":"System.AggregateException"

## Your setup (please complete the following information)

- Unity Version [2022.3.0]
- OpenXR with Mixed Reality OpenXR 1.8.1 and Unity OpenXR Plugin 1.7.0
- Visual Studio 2022

## Target platform (please complete the following information)

- HoloLens 2

## FIX

Going back to 10.0.19041.0 fixed the issue.

**Comment by AMollis** [comment]
Closing this issue, as it appears unrelated to the MRTK.  Please visit https://learn.microsoft.com/en-us/hololens/hololens2-support for your other support opinions.
