### ISSUE TITLE
DllNotFoundException: AzureSpatialAnchors assembly

### ISSUE THREAD

**Issue by mirages** [microsoft/MixedRealityToolkit-Unity#11738]
## Describe the bug

DllNotFoundException: AzureSpatialAnchors assembly:<unknown assembly> type:<unknown type> member:(null)
Microsoft.Azure.SpatialAnchors.AnchorLocateCriteria..ctor () (at ./Library/PackageCache/com.microsoft.azure.spatial-anchors-sdk.windows@c59f29caea85/Runtime/AzureSpatialAnchorsBridge_Windows.cs:2199)

## To reproduce

Follow the tutorial, and run project with play mode in unity. [https://learn.microsoft.com/zh-cn/training/paths/beginner-hololens-2-tutorials/](https://learn.microsoft.com/zh-cn/training/paths/beginner-hololens-2-tutorials/)

## Expected behavior

No error reported

## Screenshots

<img width="436" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12791299/68c25889-6dad-47b2-860a-810e071dc6d8">

## Your setup (please complete the following information)

- Unity Version 2022.3.4f1
- MRTK Version or Commit <img width="178" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12791299/7346332e-f59a-4e70-9f29-42817c5d5a1e">
- 
<img width="339" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12791299/50dd88fc-d9ec-4845-97b2-92738a54e286">

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

<img width="494" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/12791299/8d543086-2bf3-475a-94f5-5843453f3330">

**Comment by AMollis** [comment]
Thank you for this bug.  We are working on new learning paths for MRTK3.  Once MRTK3 is released to GA, the new learning paths will also be shipped
