### ISSUE TITLE
Cannot switch from XRHands to Controllers

### ISSUE THREAD

**Issue by neuro-sam** [microsoft/MixedRealityToolkit-Unity#11741]
There seems to be a bug in the `XRInputModalityManager` class which is meant to toggle between active controller types.

Steps to reproduce:
1. Create an empty 3D Unity-template project
2. Import XR Interaction Toolkit 2.4.3 + Starter Assets
3. Import XR Hands 1.2.1 + HandVisualizer
4. Import XR Plugin Management
5. Project Settings: XR Plug-in Management = OpenXR ... enable Meta Quest Support, Meta Hand Tracking Aim, Hand Tracking Subsystem
6. Open HandsDemoScene from XRInteractionTooklit/2.4.3/HandsInteractionDemo/Runtime
7. Build and run on Quest 2
-- end of setup --
8. Move controllers, See them move in VR
9. Place controllers idly on the table, See hands appear in VR
10. Pick up controllers

Expected state:
- Controllers appear in VR as in step 8.

Actual state:
- Controllers' raycast stay locked in virtual space, No controller mesh visible, Only locomotion via joystick works

Particularly the `onDeviceChange` function seems to incorrectly handle the assignment of device type back to controllers:

![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/23667589/c9b332ba-4bc4-43f5-9c88-6d108afe5b09)

_Issue related to a post by @imjusthere in https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/11525_

**Comment by AMollis** [comment]
This bug is not related to MRTK.  Please follow-up with Unity
