### ISSUE TITLE
MotionControllerVisualizer doesn't support default models

### ISSUE THREAD

**Issue by MsDerekMa** [Microsoft/MixedRealityToolkit-Unity#1174]
MotionControllerVisualizer allows you to specify an override model for the left and right controller, but it doesn't allow you to specify a default model if the controller model can't be loaded, for example in a non-networked scenario.

One possible solution would be to add a Boolean to specify if the alternate controllers are overrides or defaults. If defaults, it would try to use the OS's model first and if that fails it would fall back to the default.

**Comment by jessemcculloch** [comment]
Is the default model currently dependent on the network?  I was under the impression it was pulling the controller model from the driver installed on the machine.

**Comment by MsDerekMa** [comment]
The controller model is pulled down while the computer is on the network with the controllers turned on. If for some reason you don't have network when you turn the controllers on, they will still work, but you won't have the models.
