### ISSUE TITLE
app can't open

### ISSUE THREAD

**Issue by zzcoppt** [microsoft/MixedRealityToolkit-Unity#11743]
Hololens2 ,2020.3.24f1c2/2022.2.2f1c1/mrtk2.8.3
can't open my app

error log:
![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/35337694/2a0bdab0-8312-4ee6-bcdd-25ab0c8aeed3)

my configs:
![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/35337694/2bfa902d-148d-44f7-831a-c44e246a1370)
![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/35337694/3717f9f0-f87d-4777-9d70-8e897f07ca72)
![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/35337694/8aacca7e-b71e-4fad-9281-c1dc663485fe)

**Comment by shaynie** [comment]
@zzcoppt Can you share the contents of your packages\manifest.json file please?  There is an input system bug that could cause this, I want to see what version you have imported.
Thanks!

**Comment by shaynie** [comment]
Please re-open if you still need help with this issue.
