### ISSUE TITLE
Hololens FileOpenPicker Scaling

### ISSUE THREAD

**Issue by jaredcoh** [microsoft/MixedRealityToolkit-Unity#11757]
## Describe the bug

When I am running the FileOpenPicker on my Hololens application (self-created in Unity) and try to expand the window vertically, the file names and thumbnails get stretched as well.
## To reproduce

1. Create a unity project (OpenXR on start up using MRTK)
2. Use this code to create a file open pickerhttps://stackoverflow.com/questions/66281959/system-exception-getting-called-when-assessing-openfilepicker-on-hololens/66282480#66282480
3. Deploy the program on VS
4. Open the FilePIcker on your hololens 
5. Use any of the one-axis scale bars to visualize the error

## Expected behavior

When i move one of the scale bars, I expect the relative scaling of everything to stay constant, just more files to be visible. 

## Screenshots
![unnamed](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/76497624/ac55cd40-997d-48fa-bd94-b0b2ac012619)
^^ FOP when opened (works as normal)
![unnamed](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/76497624/653e86a1-6b64-422f-a522-c74f3c1663c7)
^^ FOP when being dragged (works as normal)

![unnamed](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/76497624/5e680856-f1e1-4fc6-b33c-6315e2e70022)
^^ FOP after release (uniaxial scaling results in distortion of graphics)

## Your setup (please complete the following information)

- Unity Version 2022.3.5.f1
- MRTK 2.8.3.0

## Target platform (please complete the following information)

- HoloLens 2

**Comment by AMollis** [comment]
@jaredcoh thank you for your feedback.  Unfortunately, this issue is not related to MRTK.   Please open an issue via the Feedback Hub app on the HoloLens 2.   For more information, please see https://learn.microsoft.com/en-us/hololens/hololens-feedback
