### ISSUE TITLE
MRTK-Quest_LocalAvatar missing or broken

### ISSUE THREAD

**Issue by ErnestKid** [microsoft/MixedRealityToolkit-Unity#11771]
## Describe the bug

MRTK-Quest_LocalAvatar is missing or broken while using the latest version of Oculus Integration.

## To reproduce

1. Start off with a new project
2. Import the Oculus Integration v55 package
3. Import the MRTK2 Foundations 2.8.3 package
4. Install required plugins
5. See error as below in console

> Problem detected while importing the Prefab file: 'Packages/com.microsoft.mixedreality.toolkit.foundation/Providers/Oculus/XRSDK/MRTK-Quest/Prefabs/MRTK-Quest_LocalAvatar.prefab'.
> The file might be corrupt or have a missing Variant parent or nested Prefabs. See details below.
> Errors:
>	Prefab Variant problem. Missing Prefab Variant parent: 'MRTK-Quest_LocalAvatar (Missing Prefab with guid: 84c8b8609f9bb434eaf5248f17ff1293)'

## Expected behavior

No errors are supposed to pop up when imported. The local avatar will show when ran on the Oculus Quest 2. Hand tracking should work.

## Screenshots

![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/104735282/65c6e324-964b-4df0-8dff-0b20d8ba599b)

## My setup

- Unity Version 2022.3.2f1
- MRTK Version v2.8.3
- Oculus Integration v55 

## Target platform

- Oculus (Meta) Quest 2

## Additional context

Reasons for the LocalAvatar from what I believe are because of Meta making the avatars a seperate package. Even installing the Avatar SDK, they had changed how it works, and the prefabs are no longer located where MRTK expects.

**Comment by shaynie** [comment]
@ErnestKid Can you please verify that you are still seeing this?  I ran this using Unity 2022.3.4f1, oculus v55, and MRTK 2.8.3 and didn't see the same errors.
<img width="1067" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/9615036/4e6e53e5-1f2f-4683-a076-be6d46f0e9df">
<img width="321" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/9615036/6c78c380-a584-492c-ab59-7bcf665c26f6">
