### ISSUE TITLE
Eyetracking pupil diameter

### ISSUE THREAD

**Issue by hunter12580** [microsoft/MixedRealityToolkit-Unity#11782]
## Describe the problem
Will MRTK3 provide pupil diameter in the eyetracking package? 

## Describe the solution you'd like
A series of amazing functions would be enabled if we could access the pupil diameter and center coordinate of eyeballs.  

## Describe alternatives you've considered
We've been trying alternatives but your HoloLens2 is pretty tight with its visor space, add-on eye trackers wouldn't work smoothly. And the built-in eye tracker is taking the perfect spot. We really wish there is an alternative.

**Comment by marlenaklein-msft** [comment]
Hi @hunter12580, for MRTK3 issues please file an issue in the [new repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity). Thanks!
