### ISSUE TITLE
When click an  ActionButton sometimes have "An Interactable received a Select Exit event for an Interactor that was not selecting it."

### ISSUE THREAD

**Issue by ChiaraLoca** [microsoft/MixedRealityToolkit-Unity#11781]
## Describe the bug

I have a ActionButton, i use the MRTK3 ActionButton prefab.
When i click it in the editor sometimes i have 2 error: 

This one is from CanvasProxyInteractor of MRTK XR Rig MRK3 3 prefab: 
UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable:OnSelectExiting (UnityEngine.XR.Interaction.Toolkit.SelectExitEventArgs)
Microsoft.MixedReality.Toolkit.MRTKBaseInteractable:OnSelectExiting (UnityEngine.XR.Interaction.Toolkit.SelectExitEventArgs) (at Library/PackageCache/com.microsoft.mrtk.core@66c690c1a686/Interactables/MRTKBaseInteractable.cs:291)
UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor:EndManualInteraction ()
Microsoft.MixedReality.Toolkit.UX.CanvasProxyInteractor:StartSelect (UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable,UnityEngine.Vector3) (at Library/PackageCache/com.microsoft.mrtk.uxcore@13263b650b38/Interop/CanvasProxyInteractor.cs:74)
Microsoft.MixedReality.Toolkit.UX.UGUIInputAdapter:OnPointerDown (UnityEngine.EventSystems.PointerEventData) (at Library/PackageCache/com.microsoft.mrtk.uxcore@13263b650b38/Interop/UGUIInputAdapter.cs:241)
UnityEngine.XR.Interaction.Toolkit.UI.UIInputModule:Update () (at Library/PackageCache/com.unity.xr.interaction.toolkit@2.3.0/Runtime/UI/UIInputModule.cs:132)

This one is from The component UIGUI input adapter of ActionButton : 
An Interactor received a Select Exit event for an Interactable that it was not selecting.
UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor:EndManualInteraction ()
Microsoft.MixedReality.Toolkit.UX.CanvasProxyInteractor:StartSelect (UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable,UnityEngine.Vector3) (at Library/PackageCache/com.microsoft.mrtk.uxcore@13263b650b38/Interop/CanvasProxyInteractor.cs:74)
Microsoft.MixedReality.Toolkit.UX.UGUIInputAdapter:OnPointerDown (UnityEngine.EventSystems.PointerEventData) (at Library/PackageCache/com.microsoft.mrtk.uxcore@13263b650b38/Interop/UGUIInputAdapter.cs:241)
UnityEngine.XR.Interaction.Toolkit.UI.UIInputModule:Update () (at Library/PackageCache/com.unity.xr.interaction.toolkit@2.3.0/Runtime/UI/UIInputModule.cs:132)

i think the problem is the button but im not sure.

the button then execute the onclicked action

## Your setup

- Unity Version 2021.3.21
- MRTK Version3 pre17

## Target platform

- HoloLens 2

**Comment by marlenaklein-msft** [comment]
Hi @ChiaraLoca, for MRTK3 issues please file an issue in the [new repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity). Thanks!
