### ISSUE TITLE
Orientations of motion controllers do not match MR headset Heading

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1179]
When running any scene while the MR headset is oriented in the direction it was setup, the motion controllers look like they're setup correctly.
When rotated any degree from the setup position, starting the app results in the motion controllers being off. Rotated 180 degree and it's as if someone infront of you were holding the controllers, mimiking your movements. The controllers common reference position and rotation seems to be bound to the setup ones.

**Comment by keveleigh** [comment]
Are you running a regular 2017.2 build or an MRTP build of Unity? This sounds like a bug that has been fixed in the MRTP builds: http://beta.unity3d.com/download/edcd66fb22ae/download.html

**Comment by Alexees** [comment]
Thanks,
that was it, we were using Unity 2017.20f2, using MRTP worked.

**Comment by StephenHodgson** [comment]
@keveleigh I was able to replicate this in that build you referenced.

**Comment by StephenHodgson** [comment]
Actually this was fixed.  Seems to be a different issue better described in #1244
