### ISSUE TITLE
Apply settings MRTK gives error about menu in mixed reality/project/apply

### ISSUE THREAD

**Issue by GLARKI** [microsoft/MixedRealityToolkit-Unity#11792]
## Describe the bug
When using the MRTK Project Configurator and I press Apply settings to target HL2, I get this error:

"ExecuteMenuItem failed because there is no menu named 'Mixed Reality/Project/Apply recommended project settings for HoloLens 2'
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Microsoft.MixedReality.Toolkit.Utilities.Editor.MixedRealityProjectConfiguratorWindow:RenderMicrosoftOpenXRPipelineDetected () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@f2323a9b7aec/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs:305)
Microsoft.MixedReality.Toolkit.Utilities.Editor.MixedRealityProjectConfiguratorWindow:RenderXRPipelineSelection () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@f2323a9b7aec/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs:181)
Microsoft.MixedReality.Toolkit.Utilities.Editor.MixedRealityProjectConfiguratorWindow:OnGUI () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@f2323a9b7aec/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs:136)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)"

<img width="1920" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/115214302/909323ab-2cdd-44e2-99af-7690dd0ae283">

Not sure how bad this is.

## To reproduce

1. New unity project 2021.3.14f1
2. Import extension, foundation, examples, assets MRTK2 2.8.3. and OpenXR 1.9.
3. Perform settings
4. Press apply
5. See behaviour

## Target platform (please complete the following information)
- HoloLens 2

**Comment by AMollis** [comment]
@shaynie can you please investigate.

**Comment by AMollis** [comment]
@GLARKI ....


‼️ Important.   For all new applications, we highly recommend using MRTK3 instead of MRTK2.  MRTK3 is better supported.  You can find MRTK3 documentation at  https://mixedrealitytoolkit.org

**Comment by GLARKI** [comment]
Good advice! Thanks for your time
- FYI after reimporting OpenXR, ad scene, and configuring, It was solved. Probably I did something wrong that I cannot recall atm.

I chose MRTK2 due to the extended eye-tracking example git I found and wanted to test.
If  EETDataProviderTest.cs and code like "ExtendedEyeGazeDataProvider.GazeType.Left" is still viable, I'd happily switch for this project. Haven't tried it out yet.

**Comment by AMollis** [comment]
@GLARKI , a lot of the eye tracking samples were ported to MRTK3.  You can find them at https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/tree/main/UnityProjects/MRTKDevTemplate/Assets/Scenes/EyeTracking

I'm closing this bug as not repo.  Please reach out if you have any other questions or issues.

**Comment by shaynie** [comment]
@GLARKI, the ExtendedEyeGazeDataProvider from here: https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/extended-eye-tracking-unity doesn't a specific MRTK version.  So yes, please try MRTK3 in new projects :)
