### ISSUE TITLE
Controllers, Hands and Passthrough not working on MKRT2 when using OpenXR on Quest

### ISSUE THREAD

**Issue by djhuds2k** [microsoft/MixedRealityToolkit-Unity#11799]
I am trying to get the Azure Remote Rendering Tutorial Sample working on Quest with Passthrough. It requires OpenXR otherwise remote rendering won't work.

If I just run Oculus XR then everything is working with MRKT (Hands and controllers) but I then can't use Remote Rendering because it needs OpenXR.

I have now managed to get things working if I use Quest Link and play mode in Unity Editor but if I build an APK it doesn't work. It's as if it's not loading Oculus as the Input Provider as the MRTK-Quest_OVRCameraRig is not being instantiated. I've tried removing all the other input providers but get the same issue. Is there any way we can force MRTK to use the Oculus Input Data Provider even if OpenXR is also added as an XR plugin?

I've tried Unity 2020 up to 2022 and I've tried MRTK 2.7.0 up to 2.8.3 and Mixed Reality OpenXR 1.8.0 up to 1.9.1 but all have the same issue. I've also managed to get it working with MRTK 3 but then a lot of other things are broken...

**Comment by AMollis** [comment]
MRTK2 is now under limit support.  We will only be addressing high priority bugs, and breaking changes caused by Unity updates.

This bug unfortunately does not meet our bar to investigate.  

I encourage you to continue to try using MRTK3, however Quest support of MRTK3 is limited.

**Comment by AMollis** [comment]
If this is a ARR sample bug, I encourage you to open a bug for the ARR team.   They might be able to assist you.

https://github.com/Azure/azure-remote-rendering/issues
