### ISSUE TITLE
Extended Delay in Launching Hololens Application

### ISSUE THREAD

**Issue by nixan2001** [microsoft/MixedRealityToolkit-Unity#11802]
I have encountered a significant delay in launching my applications that already tested on my Hololens device. Typically, the application would start promptly after displaying the "Made by Unity" screen, but recently, I've been experiencing a delay of approximately 10 minutes before the application is visible.

**Comment by AMollis** [comment]
This is unlikely an MRTK issue.  If you need support for general HoloLens 2 development, please reach out to our support team at https://aka.ms/hldevsupport
