### ISSUE TITLE
Adding LayerMask to control where teleport can be done.

### ISSUE THREAD

**Issue by amrittb** [Microsoft/MixedRealityToolkit-Unity#1180]
Some form of implementation to control where the user is able to teleport.
 
In **MixedRealityTeleport.cs"**, add the following lines

`public LayerMask ignoreTeleportInLayers = 0;`

In the same file in 'PositionMarker' function, update the comparison to:

` if (focusDetails.Object != null && ! focusDetails.Object.IsInLayerMask(ignoreTeleportInLayers) && (Vector3.Dot(focusDetails.Normal, Vector3.up) > 0.90f))
`

Is there any other optimized way this can be done?

**Comment by jessemcculloch** [comment]
Oh, I like this idea

**Comment by StephenHodgson** [comment]
Seconded

**Comment by StephenHodgson** [comment]
This would probably fix #1094 as well.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
