### ISSUE TITLE
The self-built app deployment was successful, but it failed to run on the HoloLens 2.

### ISSUE THREAD

**Issue by keblicuey** [microsoft/MixedRealityToolkit-Unity#11816]
Environment:
- Unity 2022.3.15f1c1
- MRTK3 or import packages，both tried+openXR
- HoloLens 2
-vs2019
Problem:
After deploying the project to HL2 via VS, the self-created app appears in the HL2 application. However, upon opening, only a white box appears without displaying any models. I wonder how to solve it so that my scene can correctly present on the HL2. Thanks a lot.
![6182cbf351173edb1acdcc7d48cabc6](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/81084513/877601b1-aad3-4586-aa1f-b81993049019)

**Comment by AMollis** [comment]
If this an MRTK3 bug, please open in our MRTK3 repository @ https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity

If you need general HoloLens developer support please open a ticket at https://aka.ms/hldevsupport

This repository is only for MRTK2 issues.
