### ISSUE TITLE
mrtk3 bug

### ISSUE THREAD

**Issue by liuxunfu** [microsoft/MixedRealityToolkit-Unity#11817]
## Describe the bug

The mrtk3 example does not match the latest mrtk3 package in the mixed reality feature tool, resulting in many namespaces not being found.

**Comment by JS-X-Visual** [comment]
Wrong repository. See Readme 

> MRTK v3+

>New versions of the Mixed Reality Toolkit will be released by the [Mixed Reality Toolkit](https://github.com/MixedRealityToolkit/) >organization using a repository at https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity. Visit this [repository]>>(https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity) for the latest version of the MRTK project, and when creating >new issues or discussion topics for MRTK version 3 or later.

**Comment by AMollis** [comment]
Hi @liuxunfu ,  please visit https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity for MRTK3
