### ISSUE TITLE
MRTK3 input package misses dependency on glTFast

### ISSUE THREAD

**Issue by nonemec-havok** [microsoft/MixedRealityToolkit-Unity#11823]
Reopening #11294 - the issue back then was dropped because there was no simple&clear solution. By now the solution is trivial:

glTFast is now provided directly by Unity: https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.4/manual/index.html

Simply add a dependency on "com.unity.cloud.gltfast": "6.4.0" to the mrtk.input package.json

**Comment by AMollis** [comment]
MRTK3 by default doesn't include a dependency on glTFast.  This was intentionally done, so apps are free to select the GLT solution of their choosing.  MRTK3 does not want to dictate what FLT package wo consume.

Also, this project is only for legacy MRTK2 issue.

Please open future MRTK3 issues at the MRTK3 project @ https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity.
