### ISSUE TITLE
Hand interaction is normal, but the display position is above the head（mrtk3 unity2022）

### ISSUE THREAD

**Issue by S9ARK1E** [microsoft/MixedRealityToolkit-Unity#11825]
![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/73104918/18d9dcda-7c0f-4267-9ae2-60a0558fcbd8)
What could be the problem?

**Comment by AMollis** [comment]
Please open MRTK3 issues here

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity
