### ISSUE TITLE
MRTK3 and Mixed reality Toolkit do not work together in same project

### ISSUE THREAD

**Issue by tithisingh22** [microsoft/MixedRealityToolkit-Unity#11828]
## Describe the bug

MRTK3 (15/15) and Mixed reality toolkit(10/10) when imported together or one after another in a single project show right controller prefab missing error  or corrupt hence both cannot be imported together in one project when imported individually it works fine

## To reproduce
![mrtk3](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/108583724/623c1541-e742-47c2-8d9e-2bc1b67d45eb)

there is no  clear option to check out the unrequired assests while importing if there is such option we can cross out the dulpicate assets to avoid issue while installing

## Expected behavior

to use some object collection tools of toolkit and rig or other elements tried  to import them together for smooth functioning

## Screenshots

added a screenshot
## Your setup (please complete the following information)

- Unity Version tried it on 2021.3,2022.3.24,2022.2 also
- MRTK Version or Commit [e.g. v2.0] [e.g. [b026319](https://github.com/microsoft/MixedRealityToolkit-Unity/commit/b0263190f4cf7636ec4aacb08d4224bcc5ec5719)]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

## Additional context

if its a configuration issue from myside please help me becuase i couldnt find any solution over documentation

**Comment by tithisingh22** [comment]
bug with featuretool installation of mrtk3 and  toolkit together

**Comment by nmanis** [comment]
For this one, MRTK 3 should be only one selected if doing new work.   

So, would re-run the Microsoft Mixed Reality Feature tool & not select the "Mixed reality toolkit(10/10)" since well, that is the older toolkit.  Otherwise, either stick with MRTK 2.8.3 or go to MRTK 3  (not both at same time though).

**Comment by AMollis** [comment]
Hi @nmanis ... unfortunately having MRTK2 and MRTK3 in the same project is not supported.  You'll have to remove all references to MRTK2 first, before updating to MRTK3.
