### ISSUE TITLE
MRTK3 toolkit foundation Text-To-Speech not working on Meta Quest 3.

### ISSUE THREAD

**Issue by Sanket2255** [microsoft/MixedRealityToolkit-Unity#11829]
## Overview
I have converted my Unity project of hololens2 to Meta Quest 3 which is integrated using OpenXR, so everything , handinteractions, handmenu , other functionalities of project works fine but only Text-To-Speech do not work on Meta Quest 3 as it has condition Windows_UWP works only for UWP, not for android , so is there any way to convert TTS to work on Meta Quest 3.
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity editor version
2022.3
## Mixed Reality Toolkit release version
MRTK3

**Comment by nmanis** [comment]
This issues list is for the legacy MRTK 2.8.3 release

This should be posted over on MRTK 3 issues list: 
https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues

**Comment by jadhavsanket2255** [comment]
> This issues list is for the legacy MRTK 2.8.3 release
> 
> This should be posted over on MRTK 3 issues list: https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues

Thankyou for informing, I will post it on MRTK3 issues
