### ISSUE TITLE
MRDesignLabs Bounding Box Problems

### ISSUE THREAD

**Issue by tspaddock** [Microsoft/MixedRealityToolkit-Unity#1183]
I need help please and I ask you to be patient with me.
This is very concerning to me because I do not know what is going wrong and this is something I need to implement into my projects ASAP.
I have been trying for almost a month to try to get the bounding box to function and I am not successful.
I have followed everything that I can reference online to get this bounding box to function and nothing seems to be helping. I have set it up before but only with a simple 3D box element,
The way I have set things up is by putting the Appbar and Bounding box into the main hierarchy. Then I have added the Box Collider, Bounding Box Target and Compound Button to the parent layer of an imported FBX asset. This FBX prefab within my hierarchy has multiple layers of child objects.
The Hololens prefab is also within my hierarchy.
Please let me know what else I should be adding or give me some ideas as to what I could look for. Maybe I should ask if the Bounding Box is meant for prefab with multiple layers. 
Thank you!
@Railboy #has helped me before regarding this issue.

**Comment by StephenHodgson** [comment]
This issue probably belongs in the MR Design Lab repo, or as a comment in the MR Design Lab Merge PR

**Comment by tspaddock** [comment]
Thank you I will post there.
