### ISSUE TITLE
Unable to get Coordinate System with new Open XR and MRTK3

### ISSUE THREAD

**Issue by tranquanglam123** [microsoft/MixedRealityToolkit-Unity#11833]
I am doing the same project, and I use this reference solution https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10082#issuecomment-905865993 to get the coordinate system:

#if ENABLE_WINMD_SUPPORT
    Windows.Perception.Spatial.SpatialCoordinateSystem unityWorldOrigin;
#endif

    private void Awake()
    {
#if ENABLE_WINMD_SUPPORT
    SpatialCoordinateSystem unityWorldOrigin = PerceptionInterop.GetSceneCoordinateSystem(UnityEngine.Pose.identity) as SpatialCoordinateSystem;
#endif

But it always return null. 

Expected behaviour:
The function returns the coordinate system

Unity editor version
Unity 2022.3.21f1

Mixed Reality Toolkit
MRTK 3

**Comment by marlenaklein-msft** [comment]
hi @tranquanglam123, please log MRTK3 bugs here https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity
