### ISSUE TITLE
Mixed Reality Feature Tool not responding

### ISSUE THREAD

**Issue by ebners** [microsoft/MixedRealityToolkit-Unity#11839]
## Describe the bug

Everytime that I start the Mixed Reality Feature Tool it gets stuck and the process stops responding after a few seconds.
I suspect that the ARM-based processor could be part of the reason that it breaks.

## To reproduce

1. Open the Feature Tool

## Expected behavior

The program should not stop responding

## Screenshots
[image](https://github.com/user-attachments/assets/ec28a321-6e9b-46b2-9747-37bcfa7066d9)
## Your setup (please complete the following information)

- Mixed Reality Feature Tool Version: 1.0.2209.0
- Microsoft Surface Pro 11th Edition
- Windows 11
- ARM-based processor Snapdragon(R) X 10-core X1P64100
- Unity Version [e.g. 2022.3.48f1]

## Target platform (please complete the following information)

- Quest 3

## Additional context

Is the feature tool kit compatible with arm based systems?

**Comment by AMollis** [comment]
Hi @ebners please reach out to our support team at https://aka.ms/hldevsupport.  They will help you with this issue.
