### ISSUE TITLE
Migrating from MRTK 2.4 to 2.8.3

### ISSUE THREAD

**Issue by EngrMariam** [microsoft/MixedRealityToolkit-Unity#11838]
I have been using Unity version 2019.4.4 with MRTK 2.4, and I’m currently trying to migrate to MRTK 2.8.3. However, I am encountering numerous compiler errors during the process.
Has anyone successfully completed this migration? If so, could you please share any tips or tricks you found helpful? I haven't found documentation specifically addressing the migration from 2.4 to 2.8.3; most resources I’ve seen only cover the transition from 2.0 to 2.4.

**Comment by AMollis** [comment]
Hi @EngrMariam, please reach out to our support team at https://aka.ms/hldevsupport and they will assist you with these issues.

**Comment by EngrMariam** [comment]
Hi Adam,
Thank you for getting back to me. I’ve reached out to customer support, but unfortunately, they were unable to provide a solution. The solutions I found online seem to be specific to upgrading from MRTK 2.0 to MRTK 2.4, which doesn’t resolve my issue.
If you happen to have a solution, I would greatly appreciate it if you could share it with me. For now, I’ve had to set the Unity project aside as I’m still stuck.
Thank you,Mariam
Sent from Yahoo Mail on Android 
 
  On Wed, Nov 20, 2024 at 1:00 PM, Adam ***@***.***> wrote:   


Hi @EngrMariam, please reach out to our support team at https://aka.ms/hldevsupport and they will assist you with these issues.
