### ISSUE TITLE
local scaling with multiple input based on far interaction 

### ISSUE THREAD

**Issue by nilshof01** [microsoft/MixedRealityToolkit-Unity#11834]
## Describe the bug

I have one game object in my scene which has an object manipulator attached. When i want to scale or move it with the controllers (Meta quest 3) everything works fine. Then when I switch to my hands, I can move the object by pinching but as soon as I want to rescale it with both hands the scene crashes and the following error appears: 
'''
transform.localScale assign attempt for '1AFB_bounding_sphere' is not valid. Input localScale is { NaN, NaN, NaN }.
UnityEngine.Transform:set_localScale (UnityEngine.Vector3)
MixedReality.Toolkit.SpatialManipulation.ObjectManipulator:ApplyTargetTransform () (at ./Library/PackageCache/org.mixedrealitytoolkit.spatialmanipulation@5fe191610f47/ObjectManipulator/ObjectManipulator.cs:882)
MixedReality.Toolkit.SpatialManipulation.ObjectManipulator:ProcessInteractable (UnityEngine.XR.Interaction.Toolkit.XRInteractionUpdateOrder/UpdatePhase) (at ./Library/PackageCache/org.mixedrealitytoolkit.spatialmanipulation@5fe191610f47/ObjectManipulator/ObjectManipulator.cs:848)
UnityEngine.XR.Interaction.Toolkit.XRInteractionManager:Update ()
'''
Here, "1AFB_bounding_sphere" is the name of my object which has the object manipulator attached. 

## To reproduce

Hardware:
- Meta quest 3 
- controllers
- your hands

Software:
- XR Hands 1.3.0
- XR Interaction Toolkit 3.0.3
- Unity OpenXR Meta 1.0.1
- Universal RP 14.0.10
- MRTK Input 4.0.0-pre.1
- MRTK Spatial Manipulation 4.0.0-pre.1 
- MRTK Standard Assets 3.2.0
- MRTK Tools 3.0.4
- MRTK Core Definitions 4.0.0-pre.1
- MK UX Components  4.0.0-pre.1
- MRTK UX Components (Non-Canvas) 4.0.0-pre.1
- MRTK Extended Assets 3.0.3 
- MRTK Diagnostics 3.0.2
- AR Foundation 5.1.5

My XR rig is basically copied from the HandsdemoScene under: Assets/Samples/XR Interaction Toolkit/3.0.3/Hands Interaction Demo/HandsDemoScene.unity. My object has the following components:
- MeshRenderer
- MeshCollider
- ObjectManipulator (with multiple selection mode and rotate about object center for near and far)

Run the scene and use both of your hands with pinching on the same object with the object manipulator to scale it.

## Expected behavior

I would have expected no error. 

## Your setup (please complete the following information)

- Unity Version 2022.3

## Target platform (please complete the following information)

- Meta quest 3 (Android)

**Comment by marlenaklein-msft** [comment]
hi @nilshof01, please log MRTK3 issues here https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity
