### ISSUE TITLE
ScrollingObjectCollection.ManageVisibility takes too long when numerous objects in container

### ISSUE THREAD

**Issue by julienlang** [microsoft/MixedRealityToolkit-Unity#11832]
## Describe the bug

Using the [MRTK2 ScrollingObjectCollection](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/ux-building-blocks/scrolling-object-collection?view=mrtkunity-2022-05), when the list of objects in the container is more than just a few (like in the example scenes) the ManageVisibility method, which is called every frame, takes too long and significantly impacts performance: from 60fps to 20fps!

## To reproduce

Following instructions in page linked above, create a ScrollingObjectCollection. Add many buttons to its GridObjectCollection. Update the collection. 
Using the Unity profiler, you can notice that the Camera pre-render or the LateUpdate (depending on the UseOnPreRender option) takes a lot of time.

## Expected behavior

ManageVisibility is not called when the collection hasn't been scrolled.
This is the workaround I have implemented.

**Comment by AMollis** [comment]
Hi @julienlang , unfortunately this issue does not meet the minimum requirements for addressing.  You may still reach out to our support team at https://aka.ms/hldevsupport and they will assist you with this issue.
