### ISSUE TITLE
How to build and import a local repo of MRTK into my Unity project

### ISSUE THREAD

**Issue by ShayneRC** [microsoft/MixedRealityToolkit-Unity#11842]
## Describe the issue
I'd like to make my own personal change to the MRTK staying on the version I am currently on (not upgrading to MRTKv3). I've forked the repo and made my change but I'm unsure on how to go about building it so I can use it as a package in Unity.

## Feature area
It would be great if there were steps available on how to get a local version of the MRTK into my Unity project without just dragging the assets in. Preferably how it's currently done with making each part into a .tgz file.

## Existing doc link
N/A

## Additional context
This would help for future custom development anyone else may want.

**Comment by AMollis** [comment]
Thank you for reporting this issue.  Unfortunately, we are only fixing high priority issues for MRTK2.  There is currently no active development on MRTK2.

Moving this issue to the forums.

If you need further assistance, please reach out to our support team at https://aka.ms/hldevsupport
