### ISSUE TITLE
Error at InteractionSourceExtensions when building

### ISSUE THREAD

**Issue by ForrestDumb** [Microsoft/MixedRealityToolkit-Unity#1186]
Unity 2017.2.0f3
MRTK v1.2017.2.0
Target Release 10.0.15063.0
Scripting Backend .NET ( IL2CPP build - which was selected as the Default - was incompatible with my Visual Studio 2017 Fall Creator Update Version)

EDIT: I'm building for HoloLens, with the regular MRTK, not the MRTP like in #1172

When trying to build the Visual Studio Unity Project (via Build Window - didn't test normal build before making changes to my copy) with only the TapToPlace Example Scene, I got an error in InteractionSourceExtensions.cs at

101                         returnValue = sourceState.Source.Controller.TryGetRenderableModelAsync();

that SpatialInteractionController did not have a method TryGetRenderableModelAsync() and that the closest overload required a receiver of type InteractionSource

I "fixed" the problem for myself by getting rid of the Extension class and removing all references to the StartHaptics() and StopHaptics() Methods, but you might want to look into this.

Sorry if this is a non-issue and stems from my own inability.

Cheers

**Comment by StephenHodgson** [comment]
I'll double check this.  It might be best if you use the 2017.1 unity and the 10.0.15063.0 SDK

**Comment by StephenHodgson** [comment]
See #1184
