### ISSUE TITLE
Toggle/Button behavior unreliable in ScrollViewer

### ISSUE THREAD

**Issue by CrazyTegger** [Microsoft/MixedRealityToolkit-Unity#1188]
When Toggles or Buttons are placed in a ScrollView, the Toggle/Button air tap is unreliable.

My thought is that the ScrollView drag is interfering with the tap. The ScrollView hold and drag works very well.

To reproduce, create a ScrollView and add a number of Toggles. Add ScrollView and Toggles to gaze layer mask. Using gaze, place the cursor over a Toggle and air tap. Sometimes the Toggle will work, most of the time, it wont.

This only happens on HoloLens - it does not happen in editor.

**Comment by StephenHodgson** [comment]
I take it you're using uGUI?

I think it's a combination of the timing of the user's tap and the tap timer.

I used to be that you could adjust the time that taps were recognized, but that seems to have been removed with the input updates.

**Comment by CrazyTegger** [comment]
Yes, uGUI.

Agreed - I think it also has to do with the delta movement threshold being very small to switch to a drag gesture.

If I hold my head against my office chair to prevent as much movement as possible to the cursor, I can more reliably trigger the event. If I'm standing, there's a ver. very slim chance it'll work.

In the meantime, I've wired up my own down and up events that check what the delta position of the cursor is. If it's within a threshold, call the eventhandler for the toggle/button.

**Comment by keveleigh** [comment]
This should be improved / supported via #3749. Please re-open if you upgrade to MRTK v2 and still see this issue.
