### ISSUE TITLE
Remote Mapping

### ISSUE THREAD

**Issue by StudentMaster** [Microsoft/MixedRealityToolkit-Unity#1192]
Hello guys, I am kind of new here. I am trying to upload the spatial mapping meshes to a server. Not all at once (as in Remote Mapping) but progressively, only sending the new, updated or the removed mesh data. I think I will have to rewrite the SpatialMappingObserver for this. Maybe you have a better idea how to approach the problem.
Anyway, looking into the code I looked at the SendMeshes() method in RemoteMappingManager.cs:
Is there a reason why the List meshesToSend is inside the foor loop sending only the first element per iteration or am I missing something? I just put the lines 104, 119 & 120 out of the loop, so that all the data is sent over one single tcp connection (only one serialize and one senddata call).

**Comment by keveleigh** [comment]
@darax or @angelaHillier may be able to provide some information here.

**Comment by darax** [comment]
I might have planned to change that loop into a coroutine if the performance didn't look right. 

To your first question, I tossed this together a few weeks ago for a project I'm working on, it doesn't handle deletes, but you could subscribe to the SurfaceChanged event to handle that:

[BuildingMapSurfaceObserver.zip](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/1399216/BuildingMapSurfaceObserver.zip)

**Comment by StudentMaster** [comment]
Wow, thank you very much darax, I will definitely take a good look at it!
