### ISSUE TITLE
XboxControllerInputSource throwing IndexOutOfRangeException/ NullReferenceException

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1199]
The XboxControllerInputSource throws IndexOutOfRangeException because the default for the mapping array seems to be 0 items. Interestingly enough, the array is initialized to 20 entrys in the XBoxControllerExample scene, so it works. But it fails with a NullReferenceException after calling reset on the script in the inspector. When checking the "Use Custom mapping" button to show the entries, they're all there, based on the number of elements of the serialized mapping array. The serialized info seems to be not propagated to the actual array.

**Comment by StephenHodgson** [comment]
Workaround is to just enable and disable custom mapping in `XboxControllerInputSource` inspector.

**Comment by keveleigh** [comment]
Looks like this was fixed in #1415. Please re-open if not.
