### ISSUE TITLE
Some question about the MotionControllerVisualizer

### ISSUE THREAD

**Issue by biezhihua** [Microsoft/MixedRealityToolkit-Unity#1200]
Hi，SDK开发者：

关于MotionControllerVisualizer我有一些疑问。 我知道MotionControllerVisualizer类是用于加载手柄模型的。

但是出现了一些奇怪的问题，当我在Editor模式下运行MotionControllerTest Scene来测试手柄功能时，我仅开启了一个手柄（右手），但是我发现MotionControlles下却出现了两个RightController。

![image](https://user-images.githubusercontent.com/6761107/31761047-3bd23ff8-b4e9-11e7-9791-22d2d8f167ad.png)

我跟踪了代码，我发现右手的手柄的source.id出现了两个（200004 200008），我不知道为什么会这样，我明明只开启了一个右侧手柄。

此外，手柄的位置追踪也有问题，如下：

![image](https://user-images.githubusercontent.com/6761107/31761181-b2074b32-b4e9-11e7-833b-fdb62c48e0b7.png)

我不知道为什么会出现这些情况，是由于我在Editor模式下运行程序造成的么？

Unity 2017.2.0f3 MRTP

希望得到帮助！

**Comment by biezhihua** [comment]
Hi, developer:

I have some issue about the MotionControllerVisualizer Class.  I know the MotionControllerVisualizer Class  is used to load the GamePad model.

But, there were some strange problems.  I start the  MotionControllerTest Scene  to test the right motion in the Editor Mode , but I found two RightController at the MotionControllers.

![image](https://user-images.githubusercontent.com/6761107/31761047-3bd23ff8-b4e9-11e7-9791-22d2d8f167ad.png)

In addition, GamePad position&rotation trace have some problems. You can see below pictures:

![image](https://user-images.githubusercontent.com/6761107/31761181-b2074b32-b4e9-11e7-833b-fdb62c48e0b7.png)

I don't know why these problem arise. 

Thanks~  I hope to get your reply.

**Comment by StephenHodgson** [comment]
I've seen this as well.

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/31818521-1977fb54-b5cb-11e7-84f2-b35e068f5bbd.png)

When I run my project by Visual Studio with Debug mode, the MotionControllerVisualizer class throw a exception.

@StephenHodgson

**Comment by keveleigh** [comment]
@biezhihua The duplicate key exception should be fixed in the latest scripts. Please update and let me know if you still see it.

The controller NaNs seem to be coming in from the platform. It's either an OS or a Unity bug, but I'm not sure yet which.

**Comment by StephenHodgson** [comment]
Related to #1290

**Comment by biezhihua** [comment]
@keveleigh Hi, duplicate key bug not see again. Thanks!
