### ISSUE TITLE
Motion Controller receives cursor after second trigger pull

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1202]
Starting the MotionControllerTest scene, it takes two trigger pulls to switch between gaze and motion controller. The first time, one "Left Controller Lost" and one "Left Controller Detected" show up on the debug wall. Only the second trigger switches the cursor over to the controller. (have tested this only with the touchpad too, with which the problem does not occur)

**Comment by timGerken** [comment]
This is actually an OS/Shell bug and has nothing to do with MRTK. Can't comment on when the fix will be available, but until then, apps will need to deal with this behavior.
