### ISSUE TITLE
HandDraggable example broken in 2017.2

### ISSUE THREAD

**Issue by aaronvark** [Microsoft/MixedRealityToolkit-Unity#1203]
The "GetSupportedInputInfo" function incorrectly appears to return false when checking support for Positional information after receiving OnInputDown events in the HandDraggable.cs script, effectively breaking the ability to move objects on HoloLens using finger input.

I've confirmed position does exist, by checking the Position data contains a valid non-zero location: 

> FocusDetails? det = FocusManager.Instance.TryGetFocusDetails(eventData);
> if (det != null) {
> 	Debug.Log(det.Value.Position);
> }

**Comment by StephenHodgson** [comment]
I know I tested and fixed this for the latest release.

Which version of unity and the SDK are you using?

**Comment by aaronvark** [comment]
I was using the 2017.2 tag, and am using Unity 2017.2.0f3. Can I simply update to the latest dev to fix this?

**Comment by StephenHodgson** [comment]
Use unity 2017.1.2 with the latest release

**Comment by StephenHodgson** [comment]
See #1184

**Comment by hannesne** [comment]
For using 2017.2 editor and tookit on my hololens, I had to comment out the check for position data in handdraggable, and change the references from TryGetPointerPosition (which uses the gaze pointer) to TryGetGripPosition (which gives you your hand position). Works for me now.

**Comment by ThoWelt** [comment]
Hi Hannesne,
could you please post your draggable changes?
I don't get it, how to "comment out the check for position data in handdraggable". There are to many position checks in this class.
Very thanks for your time and your idea!!

**Comment by asanint** [comment]
Hi ThoWelt,

I was having the exact same problem with HandDraggable, your solution works, I think this should be added to the main branch.
Now it works for me using Unity 2017.2.0f3, W-SDK 10.0.16299.0, newest MRTK 4

@StephenHodgson are you having this issue on your end as well?

**Comment by StephenHodgson** [comment]
No, I can confirm I fixed this PR #1177

**Comment by StephenHodgson** [comment]
Seems like 1177 fixed it only for 2017.1 but not for 2017.2

**Comment by asanint** [comment]
Thanks for looking in to it @stephenHodgson.

**Comment by fabioshepherd** [comment]
Thanks @ThoWelt ! I could not realize why the handdraggable script did not work and I was going crazy
