### ISSUE TITLE
Hololens with Unity 2017.2.0f3 not working?

### ISSUE THREAD

**Issue by markus-at-fake** [Microsoft/MixedRealityToolkit-Unity#1210]
Hello!

There is a mention in the front page of this repository that:

"Currently we are waiting on a fix for HoloLens development from Unity, for how you should use the following versions of Unity and the "Release" version of the MRTK Asset: ..."

Also, issue #1184 says that one should stick with 2017.1.x. So, I presume one should not use 2017.2.0 with Hololens but wait for fixes? 

If I try to use the Holographic Emulation in Unity, it freezes the whole editor. I am able to deploy and run examples from the example package, but I do get these:

> Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.

... also, trying to run my own application that uses the VRTK - Unity package, I fall short when the SDK Manager from that package informs me this:

> Ignoring SDK Setup 'HoloLens' because the following VR device names are missing from the PlayerSettings:
> HoloLens

I guess these are issue that hopefully Unity fixes in near future?

bests,
Markus

**Comment by samharper94** [comment]
For me, it works in 2017.2.0f3 MRTP (no Vuforia) but there are a lot of issues. I also get the freeze if I use holographic emulation, but I also get a freeze if I just use the play mode at all. Seemingly this is an issue with the Fall Creator's Update and Unity though.

Main issue I seem to be getting in 2017.2.0f3 MRTP is the hand draggable script doesn't move any objects (tap to place does) and the tracking is very poor when the frame rate dips.

**Comment by kloskow** [comment]
I am having very hard times making ar markers work on new Vuforia and Unity integrated release. Documentations also seems to be out dated on Vuforia's page. Any ideas how to link HoloLens Camera with AR camera?

**Comment by jasonhbartlett** [comment]
Any update on this?  I wanted to try and build a Hololens app with MRTK and Vuforia and I'm not sure which versions of each I should be using.  As Vuforia is now integrated into Unity 2017.2, but 2017.2 is a no-go for Hololens dev's, what is the best path?

**Comment by StephenHodgson** [comment]
See #1335

**Comment by kloskow** [comment]
so far I was told by Vuforia support that there is no link between HololensCamera and ARCamera from Vuforia package. Basically, the ARCamera prefab from Vuforia does the entire job. So far, I have not managed to get the holograms working with suggested by their supports settings. Holograms appear once every so often and seem to have very incorrect tracking. ARToolkit has also comes with an image recognition function so I believe I might give it a go as of now.

**Comment by NeerajW** [comment]
Please reopen if your question was not answered.
