### ISSUE TITLE
Make Singleton accept Callbacks to run when ready

### ISSUE THREAD

**Issue by eluchsinger** [Microsoft/MixedRealityToolkit-Unity#1213]
### Disclaimer
I am a beginner in Unity and HoloLens development. I do not have special knowledge about performance tuning a Unity application (or anything a that's a bit more than basic).

## Current State
Right now, there is no way to efficiently use check, if the Singleton instance is initialized. I have seen applications check for `IsInitialized() == true` in the `Update()` method, but I don't believe this is a good approach for various reasons, like Performance and Code Style (maintainability).

In traditional projects, when you are using the Singleton pattern (_urgh..._), you can either do an eager initialization or a lazy initialization. In HTK's case, the Singleton initializes the Singleton in the `Awake()` method. This means, often the Singleton will be already initialized when you use it, but for example if you require it inside an other `Awake()` method, you can't be sure about that.

## Proposal
Why does the Singleton class not provide a method like `WhenInitialized(Action action)`. This method runs the `action` as soon as the singleton is initialized, or it runs the `action` immediately, if the Singleton is already initialized.

In this way, we provide the users of the Singleton class a way avoid having to poll until the Singleton is available and make their code smarter. Singletons that are never available (`WorldAnchorManager` in Editor?) will never use the callbacks and the code will never get executed.

**Comment by eluchsinger** [comment]
I have opened a PR with an implementation of the proposal, but I am sure it needs more refining. #1215

**Comment by keveleigh** [comment]
> In HTK's case, the Singleton initializes the Singleton in the `Awake()` method.

As of #1160, it now is also set if `Instance` is referred to before Singleton's `Awake()` is called.

**Comment by eluchsinger** [comment]
With the new Singleton implementation of #1160, I have the feeling that a `WhenInitialized(Action action)` method would degrade to pure syntactic sugar.
