### ISSUE TITLE
Any chanches to build solution in new version of unity?

### ISSUE THREAD

**Issue by Hitomilras** [Microsoft/MixedRealityToolkit-Unity#1217]
Hi. Unity 2017.2.f03 now released and, as i see, there is a branch for Unity 2017.2 (Dev_Unity_2017.2.0).
I trying tu build something, but i can't. I can't even build your example scenes.

Error:
```
Assets\Scripts\HoloToolkit\Input\Scripts\Utilities\Extensions\InteractionSourceExtensions.cs(101,39): error CS1929: 'SpatialInteractionController' does not contain a definition for 'TryGetRenderableModelAsync' and the best extension method overload 'InteractionSourceExtensions.TryGetRenderableModelAsync(InteractionSource)' requires a receiver of type 'InteractionSource'
```

And then:
Error building Player because scripts had compiler errors

This errors occurs only during the build process (Build project in your Build Window). 
Really will be gratefull if you help me with this errors or maybe say, what version of Unity, version \ branch of SDK i need to use, to get stable work) It will save me a lot of time, thanks)

**Comment by StephenHodgson** [comment]
See #1184
