### ISSUE TITLE
GameControllerManipulatorTest scene missing script

### ISSUE THREAD

**Issue by linojon** [Microsoft/MixedRealityToolkit-Unity#1220]
Open the HoloToolkit-Examples/GameControllerManipulator/GameControllerManipulatorTest scene and the Managers object is missing a mono script

![image](https://user-images.githubusercontent.com/68624/31863480-ecae3eb0-b71b-11e7-9803-b0ecdeb69a88.png)

**Comment by StephenHodgson** [comment]
Use the XboxControllerTest scene instead

**Comment by StephenHodgson** [comment]
Actually that scene isn't in the toolkit any longer.

Did you delete all your toolkit files before importing the update?
