### ISSUE TITLE
Unity doesn't send image to HMD

### ISSUE THREAD

**Issue by Stealth2615** [Microsoft/MixedRealityToolkit-Unity#1224]
I installed the mixed reality toolkit und it worked quite long. The problem now is that apparently Unity does not send any picture of debug mode from my application to the HMD. Even with everyting set up in Unity and with focus on Unity itself. The MR portal is running in the backround. The Headset stays in the cliff house. Also Unity does recognize the headset. It's even recognize any motion from the HMD. Does anybode know what's the problem here?

**Comment by keveleigh** [comment]
Are you still seeing this with recent versions of Unity and Windows?

**Comment by Stealth2615** [comment]
Hello,

no not anymore.

Thank dpi and best regards

Am 20.02.2018 22:11 schrieb "Kurtis" <notifications@github.com>:
