### ISSUE TITLE
How do I use the UX controls with a RigidBody?

### ISSUE THREAD

**Issue by HattMarris1** [Microsoft/MixedRealityToolkit-Unity#1227]
Hi!

In order to use the Bounding Box component that's part of the MRDL, the root gameobject needs a rigidbody component attached to it.

However, it seems that the slider component (and the other UX components) don't work when there is a rigidbody on any of their parent gameobjects.

Does anyone know of a way around this?

Thanks in advance!

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Comment by AWSi-DR-TS** [comment]
I also run into this problem. Is there a fix by now?

Thanks :)
