### ISSUE TITLE
XBox Controller "A" not responding with latest MRTK

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/MixedRealityToolkit-Unity#1229]
Create a new Unity project, import MRTK, configure for immersive head sets, add default scene settings. Enable Xbox Controller Support. Start project in Unity, observe how nothing happens when you press "A". The cursor should at least react in some way

**Comment by StephenHodgson** [comment]
I don't think the default input system is setup with the XboxControllerInputSource yet.

**Comment by LocalJoost** [comment]
I added a XboxControllerInputSource as in your video. No effect. I wish to stress that this used to work until pretty recently. If you can tell me what changed... maybe I can help.

**Comment by LocalJoost** [comment]
Oh and by the way... all _other_ functions of the Xbox Controller (teleport, move, rotate) work fine. It's just that darn button

**Comment by LocalJoost** [comment]
Interestingly - if you add a XboxControllerInputSource it gets disabled at startup....

**Comment by StephenHodgson** [comment]
I think this was actually because of a change to the prefab itself.

Try adding the GamePadInput script back to the MotionControllers prefab.

It's deprecated and it was meant to be replaced by the the XboxControllerInputSource.

**Comment by LocalJoost** [comment]
It does not seem to have much effect. Do I need to change settings on GamePadInput?

**Comment by LocalJoost** [comment]
Ah. Input Button Fire1 not setup. How should I do this?

**Comment by StephenHodgson** [comment]
Edit/Project Settings/ Input

**Comment by StephenHodgson** [comment]
Although if it's Fire1 that's being referenced in your code, you may want to replace it with whatever the current mapping for your A button is

**Comment by LocalJoost** [comment]
Yeah, found it. That seems to be working, I think this needs to be fixed ;)

**Comment by LocalJoost** [comment]
It's actually easier to set the Gamepad button to XBOX_A.

**Comment by StephenHodgson** [comment]
That's exactly what I was going to suggest

**Comment by LocalJoost** [comment]
But are we agreed this is actually a bug?

**Comment by StephenHodgson** [comment]
Yes.  I need to update the usages of the Xbox Controller on the MixedRealityCameraPrefab.

**Comment by StephenHodgson** [comment]
@LocalJoost is there a specific test scene I should use to test this?

**Comment by LocalJoost** [comment]
I am not aware of one.

Joost van Schaik

Windows Development MVP
Sent from mail for Windows 10

"The world as I envision it in my head is such a more interesting place"

**Comment by keveleigh** [comment]
So what was the bug in this? It sounds like the issue is GamepadInput.cs having stale axis names, correct?

@StephenHodgson I don't see any controller references on the MixedRealityCamera prefabs. Which updates are you referring to? Also, you say that GamepadInput.cs is deprecated. What else implements its functionality of routing taps/holds/navigation through the InputManager from an Xbox controller?

**Comment by StephenHodgson** [comment]
That's a good point kev

**Comment by LocalJoost** [comment]
So I gather this is fixed now? No need to workaround anymore with pulling back in that deprecated class you advised me?

Joost van Schaik

Windows Development MVP
Sent from mail for Windows 10 on my Surface Pro 4

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by StephenHodgson** [comment]
Should be. All I said was update the string references on GamePadInput
