### ISSUE TITLE
Vuforia and MRTK?

### ISSUE THREAD

**Issue by Caltato** [Microsoft/MixedRealityToolkit-Unity#1230]
Hi I'm having a bit of a dilemma. I'm currently working on a game that will require both MRTK and Vuforia. But the problem is that Vuforia asks for the Unity version to be 2017.2 while MRTK only has releases till 2017.1.2. So I'm a bit stuck. Any suggestions? 

Unless I'm missing something. In which case, I apologise.

**Comment by Caltato** [comment]
Unless I'm missing something. In which case, I apologise.

**Comment by samharper94** [comment]
I'm in the same situation. unfortunately nothing to be done until Unity sorts some things out apparently. See #1184 for more info.

**Comment by Caltato** [comment]
Darn... So just gotta wait I guess.

**Comment by afauch** [comment]
Anyone figured out a hack for getting Vuforia to play nice with 2017.2.0p1-MRTP4? I have Vuforia building fine to HoloLens in 2017.2.0f3, but my MRTK interactivity is now broken in 2017.2.0f3. Can't seem to get Vuforia support in 2017.2.0p1-MRTP4. I'm bottlenecked like you guys.

**Comment by jasonhbartlett** [comment]
Same here.  The XR Settings Vuforia link currently takes us to [http://download.unity3d.com/download_unity/b1565bfe4a0c/TargetSupportInstaller/UnitySetup-Vuforia-AR-Support-for-Editor-2017.2.0p1-MRTP4.exe](url) which is a page cannot be displayed.  We'll have to wait for an update I guess.

**Comment by Caltato** [comment]
The new 2017.2.1f1 release of MRTK seems to have fixed it! It all works when built. Vuforia and all. 

But for some reason the GesturesInput and MotionControllers will make Unity crash whenever it is not connnected to the HoloLens.

Apart from that it all works fine.

**Comment by NeerajW** [comment]
Please reopen if your question was not answered.
