### ISSUE TITLE
3D Icon launcher implementation on Unity

### ISSUE THREAD

**Issue by decoc** [microsoft/MixedRealityToolkit-Unity#1231]
The way to implement 3D application icon was opened for IHMD (https://developer.microsoft.com/en-us/windows/mixed-reality/implementing_3d_app_launchers). That's make developed app more attractive, however, there are troublesome steps in order to set an icon.  Importing model to blender and  modify its position, rotation, scale in range of defined area.  Then export it as .glb, drop it Assets directory , and rewrite some settings.   
I'd like to ask you have any plan to implement function to set 3D icon directory on Unity.

**Comment by StephenHodgson** [comment]
I think that's something Unity is going to have to implement in the editor.

But I don't see why we couldn't add it to the build options and append the appxmanifest.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Comment by Yoyozilla** [comment]
@keveleigh 
is that just the asset or will it also do "implement function to set 3D icon directory on Unity."

**Comment by keveleigh** [comment]
@yoyozilla That PR is just the asset, but I can investigate setting the icon as well.
