### ISSUE TITLE
Tapping doesn't work in SpatialUnderstandingExample scene

### ISSUE THREAD

**Issue by pwy1608** [Microsoft/MixedRealityToolkit-Unity#1232]
Just a practice, I used SpatialUnderstadingExample scene in HoloToolkit-Example.
There's no error during building the project in Unity and VS both, but after executing the application in HoloLens or Emulator, tapping the button and panel button in scene is not working.

However, I don't know why, the tapping gesture to stop the spatial scanning works well.

How I click the panel / button in the scene only with hands (without mouse)?

**Comment by StephenHodgson** [comment]
What version of Unity and Window SDK are you using?

**Comment by pwy1608** [comment]
I'm using Unity 2017.2.0f3 and the latest version of Windows SDK, HoloLens Emulator.
Mouse clicking works in Unity scene, but tapping gesture does not work.

**Comment by StephenHodgson** [comment]
See #1184
