### ISSUE TITLE
multi-line in keyboard input field

### ISSUE THREAD

**Issue by meah** [Microsoft/MixedRealityToolkit-Unity#1233]
when use a multi-line and add a big paragraph in the input field i can't see the right position and text where the next text will be added
![keyboard](https://user-images.githubusercontent.com/3739337/32006920-f9fd5354-b99f-11e7-8542-acd005f3b95f.png)

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
