### ISSUE TITLE
Often (but not always) 'double vision' of close by objects

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/MixedRealityToolkit-Unity#1236]
I have not been able to put a definite repo for this, but using Unity 2017.2.0.f3 MRTP I often get 'double vision' of objects that are close by. It feels like anything closer than about 1.5 meters. Cursor seems displayed twice close to each other, I also see two instances of the same controllers through each other when I use only one. It looks like the stereoscopic view does not work properly. When I download my app from the store, everything is fine.

Sometimes restarting the Mixed Reality portal helps, sometimes not even a reboot helps. I thought it had something to do with tracking, but apparently not

**Comment by StephenHodgson** [comment]
I've seen this as well. Didn't know a reboot or relaunch of the portal helps. Thanks!

**Comment by LocalJoost** [comment]
It SOMETIMES helps. Pretty sure it is a race condition. /ref Slack


Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by LocalJoost** [comment]
This seems to fix the double vision. Changed MotionControllerVisualizer

private IEnumerator Start()

        {

            yield return new WaitForSeconds(5);

Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by keveleigh** [comment]
This seems like a Unity bug to me. Have you filed anything?

**Comment by LocalJoost** [comment]
No... Because it makes the chance of this happening less, but not zero. A bit worried about the Unity QA TBH

Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by keveleigh** [comment]
> Because it makes the chance of this happening less

What is "this"?

**Comment by LocalJoost** [comment]
Sorry. Delaying MotionControllerVisualizer init

Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by LocalJoost** [comment]
That makes the chance of double vision less. At least I think so

Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by ChimeraScorn** [comment]
FYI for folks, we are investigating this with Unity.

**Comment by ChimeraScorn** [comment]
Also, I'd recommend against doing unnatural things to work around this, as those workarounds can creep into final apps. :) We will share info as soon as we have it.

**Comment by LocalJoost** [comment]
I know but things sometimes just gotta work, right? 😀

Joost van Schaik

Windows Development MVP
Sent from mail for Windows 10

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by Alexees** [comment]
I'd like to add that the amount also seems to change. Sometimes it's negletable and feels correct, though a little fishy, sometimes it hurts the brain. And there's also in between situations.
This never happened to our project until using MRTP3, but what do you know, maybe we were just lucky.

**Comment by LocalJoost** [comment]
I had it with MRTP, haven't tried MRTP3


Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by Alexees** [comment]
> When I download my app from the store, everything is fine
You were lucky then. In my case, the double vision krept into the store built

**Comment by StephenHodgson** [comment]
Actually, I'm starting to suspect this is also a bug in the MRTK.  The reason I think this is because the controller models don't have a collider and we're not moving the focus plane to them when our gaze hits it.

**Comment by timGerken** [comment]
This is decidedly *not* a MRTK bug. I've verified it fixed in an upcoming 2017 MRTK build that should be released more broadly once it gets through Unity's testing process.

**Comment by StephenHodgson** [comment]
@timGerken  The patch release is out #1301

**Comment by timGerken** [comment]
@StephenHodgson Yes, but the bug fix is in a separate (currently private) MRTP4 build off of that patch release.

**Comment by LocalJoost** [comment]
Yikes. I have posted a version with MRTP3. Can I please have that private beta? Or else and ETA? 😀


Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by timGerken** [comment]
@LocalJoost 
If you had access to MRTP3, you should also gain access to MRTP4 when available.
At this point, I can't provide an ETA.

**Comment by timGerken** [comment]
[MRTP4 is now available](https://forum.unity.com/threads/custom-build-2017-2-rc-mrtp-windows-mixed-reality-technical-preview.498253/)

**Comment by StephenHodgson** [comment]
Already have a PR #1312 for it!  Thanks @timGerken

**Comment by LocalJoost** [comment]
Awesome


Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by Alexees** [comment]
Oh yeah, can't wait too see again.
