### ISSUE TITLE
360° video player prefabs

### ISSUE THREAD

**Issue by HattMarris1** [Microsoft/MixedRealityToolkit-Unity#1238]
I noticed this on the main Readme, and was wondering if there'd been any progress on this? 

Is the aim to have something like what's mentioned in the [HoloTour case study](https://developer.microsoft.com/en-us/windows/mixed-reality/case_study_-_capturing_and_creating_content_for_holotour#video_playback), where only the bits of the video that are currently in the user's view is decoded?

I've experimented a bit with 360° video with the HoloLens, and I've found the HoloLens is only able to handle 720p panoramic video.

Thanks,

**Comment by NeerajW** [comment]
This is feature work we have not investigated as yet. Thank you for filing it.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
