### ISSUE TITLE
Unity 2017.2.0f3 and Unity 2017.2.0f3-MRTP Build Fail

### ISSUE THREAD

**Issue by DenninDalke** [Microsoft/MixedRealityToolkit-Unity#1239]
I've tried to build the commit 72d33d9c854c05fea32c825878e6dff68f6b0818 on Unity 2017.2.0f3 and Unity 2017.2.0f3-MRTP but both are failing.

On Unity 2017.2.0f3 no errors are provided.
On Unity 2017.2.0f3-MRTP it gives me 2 compiler errors:

`Assets\HoloToolkit\Input\Scripts\Utilities\Extensions\InteractionSourceExtensions.cs(101,39): error CS1929: 'SpatialInteractionController' does not contain a definition for 'TryGetRenderableModelAsync' and the best extension method overload 'InteractionSourceExtensions.TryGetRenderableModelAsync(InteractionSource)' requires a receiver of type 'InteractionSource'
`

`Assets\HoloToolkit-Examples\MotionControllers-GrabMechanics\Scripts\BaseGrabber.cs(189,21): error CS0103: The name 'UnityEditor' does not exist in the current context
`

I'm building using SDK 10.0.15063.0.
Any thoughts on that would be appreciated.

**Comment by StephenHodgson** [comment]
You need to use the latest SDK target.

See #1184
