### ISSUE TITLE
Replacement for Unlit/NoDepth and how to make 3D text always visible (not blocked by anything)

### ISSUE THREAD

**Issue by qfliu** [Microsoft/MixedRealityToolkit-Unity#1241]
Hi there, 

I was developing using the HoloLensToolKit before. To make target indicator not blocked by anything, the shader is set to Unlit/NoDepth. After I switched to MixedRealityToolKit, I see that the NoDepth shader is considered as obsolete now. Is there a replacement for the Unlet/NoDepth shader now? I cannot find it in the shader options. 

Also, before, a 3D text would always be visible even if there is an object in front of it. Now, this is not the case. With the default shader from MixedRealityToolKit, a 3D text would not be visible if there is an object between the camera and the text. What do I need to do to change this?

Thanks in advance.

**Comment by StephenHodgson** [comment]
I believe you can just use Unity's default text shader

**Comment by qfliu** [comment]
@StephenHodgson 

I tried to create a 3D text with default values. This works in version 5.6.1f1, but not version 2017.2.0b9. By "works", I mean that the text would not be blocked by an object I generate.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
