### ISSUE TITLE
Save Spatial Mapping/Understanding Scenes have broken script reference

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1252]
Both the `SaveSpatialMapping` and `SaveSpatialUnderstanding` scenes have missing script references on the Scene root object.

Probably related to #817

**Comment by juyingnan** [comment]
I believe it is because Microsoft changed "keyword manager" to "Speech Input Handler", which made the user not able to say "capture mesh" for the save room model function.

**Comment by StephenHodgson** [comment]
It wasn't MSFT, that was me haha.
It was obsolete for a while. Surprised it didn't show up in the compiler warnings

**Comment by juyingnan** [comment]
Ah. So how can I know which function it called when the player says "capture mesh" in the old version?

**Comment by StephenHodgson** [comment]
I just need to pull an older version and copy the keywords and commands

Idk what they are tho
