### ISSUE TITLE
Tagalong Script not working as intended

### ISSUE THREAD

**Issue by eluchsinger** [Microsoft/MixedRealityToolkit-Unity#1253]
Device: HoloLens

I have added the Tagalong script to a GameObject. It follows me, but it always stays behind me, when I walk away. How can I make it stay inside my Field of View?

**Comment by StephenHodgson** [comment]
Try the `SphereBasedTagalong` and reduce it's radius to something line 0.1 and move it out about 2 meters in front of you.

**Comment by eluchsinger** [comment]
Works. Thanks!
