### ISSUE TITLE
[master] cursor ray, etc

### ISSUE THREAD

**Issue by erichfrazer** [Microsoft/MixedRealityToolkit-Unity#1257]
Q1: In MotionControllerTest, when using the CK controller, how do I get it to show a ray, any ray, like in the cliff house? I want my cursor to have a ray pointing out!!

I am trying to figure out the toolkit, for want of better (or any?) docs, and am trying to figure out the function of everything below "Manager" and "DefaultCursor". 

Q2: In Managers/InputManager, why does Managers have a sub-object called "EventSystem" and InputManager, a sub-object of Manager, also have a sub-object "EventSystem"?

Q3: Why does InputManager have a GazeStabilizer script, and it's sub-object ControllerPointerStabilizer also has a GazeStabilizer script? Why not forward from one input set of events to a single GazeStabilizer?

Q4: What does InputManager's MouseInputControl do? What the business with "Simulate Hands in Editor"? Why would you want to simulate a Hand, and is a Hand an input method? Does it mimic a gesture for HoloLens?

Q5: The chain goes DefaultCursor -> AnchorCursor -> CursorVisual... AnchorCursor is basically blank. Why isn't the chain DefaultCursor -> CursorVisual?

Q6: Why does FadePlane's MeshRenderer cast and receive shadows?

Q7: What does InputManager's GazeManager's DebugDrawRay do?  apparently, nothing, as far as I can tell. Debug.DrawRay, can I see that in the editor?

Q8: What is DefaultCursor's AnimatedCursor (script)'s "EnableStateData" and "AnimatedCursorStateData" for? What do these do?!

Q9: StabilizationPlaneModifier script's TrackVelocity and DrawGizmos don't seem to do anything either. What do these do? I don't see them on the Game screen, or in the headset! I don't have that stuff turned off, specficially.

these answers will be greatly appreciated!

**Comment by samharper94** [comment]
Q4. You've got it, it's for hand gestures in HoloLens. Mouse Input Control allows you to use the right click and control the camera in the editor, then shift-click allows mimicking the tap and pinch hand gestures in HoloLens.

**Comment by keveleigh** [comment]
Q1: We don't have any support for ray visualization at the moment. I believe @Railboy is beginning work to add them though!

Q2: Good question! Looks like somebody added an EventSystem to the InputManager prefab at some point (@StephenHodgson?), but scenes haven't been updated to remove the one previously added.

Q3: GazeStabilizer as written keeps a historical track of data. I believe two different instances were used to not mix data, but it could probably be rewritten to clear the data when a source changes or something. This (among other things) will likely need to be addressed if a dev wants to use multiple pointers at once in an app.

Q4: See @samharper94 above.

Q5: I don't know enough about the cursor models,

Q6: It likely doesn't need to.

Q7: Yes, that only renders in the Editor.

Q8: Some of these options have Tooltips if you hover in the inspector. `Enable State Data` specifies the default state to go into when the cursor is enabled. `Animated Cursor State Data` allows you to specify additional states for the cursor, like the dot vs the ring in this cursor example.

Q9: I believe Gizmos are an Editor-only thing.
