### ISSUE TITLE
Mixed Reality Camera Manager settings not stored/retained

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/MixedRealityToolkit-Unity#1258]
![image](https://user-images.githubusercontent.com/4129183/32147193-be6eff6c-bce3-11e7-8a3d-b314d0ed0c78.png)
I tried to set near clip to 0.3 and quality to simple. Save scene, close Unity, Start Unity, settings are reverted again. At least in Unity 2017.1.2.f1, which is the recommended Unity version for a HoloLens app

**Comment by keveleigh** [comment]
This is a bug with [MixedRealityCameraMangerEditor](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/Editor/MixedRealityCameraMangerEditor.cs). Removing that fixes the issue.

**Comment by StephenHodgson** [comment]
Yeah it's not properly getting the serialized object.

**Comment by LocalJoost** [comment]
Yeah I noticed. Unfortunately I don't know much about Editors. Giving the file a proper name is advisable too (there's an "a" missing

**Comment by StephenHodgson** [comment]
Halfway though a fix.  I'll post it shortly.

**Comment by LocalJoost** [comment]
Well @keveleigh's fix works ;)
