### ISSUE TITLE
Request: Add a version readme to the root folder

### ISSUE THREAD

**Issue by rolandsmeenk** [Microsoft/MixedRealityToolkit-Unity#1260]
I would like to be able to quickly identify the version of the MRTK used in projects that I downloaded from GitHub (for instance the Holographic Academy).

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Comment by keveleigh** [comment]
Also, we do now support version numbers for each MRTK package and version. Example (where we updated the version): https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3852
