### ISSUE TITLE
Scene: GrabMechanics doesn't seem to work

### ISSUE THREAD

**Issue by erichfrazer** [Microsoft/MixedRealityToolkit-Unity#1261]
Machine: Windows 10 Fall Creators update, Unity: 2017.2. I tried this scene (GrabMechanics) in the editor, and compiled to debug, and in neither one can I pick up and control anything. Should this scene still work? And if not, I wonder if anybody has a quick answer why not? There isn't much in the scene to begin with!

**Comment by keveleigh** [comment]
Yep, I ran this the other day to help somebody else figure it out. The problem he was running into: are you pointing at the objects to interact or actually reaching out, intersecting the blocks with your block hands, and then interacting? They were trying to point and click, but actually "grabbing" the objects is the way this sample works.

Another thing to check is to make sure you're pressing the right button. If I remember correctly, this scene works with the grasp button, not the trigger.

Let me know if it still doesn't work for you!

**Comment by erichfrazer** [comment]
Oop, Grab does work, you DO have to reach out and grab it w/ the chunky block. Well, this is a relief. And yeah, I'm not used to using the Grasp button. You may close this.

One thing I can't figure out is where MotionController.cs went. I see the visualizer script file, but the MotionController base script is gone. Has this been replaced with a different set of mechanics for input control? and recently?

**Comment by keveleigh** [comment]
There's MotionControllerVisualizer and MotionControllerInfo, which contains the data about the model and animation parameters. I don't believe there's ever been a MotionController script like you describe. The controller controls are routed through InputManager events. Are you perhaps thinking of a script in the MRDL/HUX?

**Comment by StephenHodgson** [comment]
Ah, I tagged this as a bug cause I didn't get it to work either.  Good to hear.

**Comment by hridpath** [comment]
I am using the Motion Controllers from Dell. I can click and change the active controll to the controller but when I focus on an object and click the Grasp button nothing happens. Do I physically need to move the controller to the object?

**Comment by StephenHodgson** [comment]
I believe so

**Comment by hridpath** [comment]
Sorry to say that even moving the controller to touch/pass through did  not work. I am getting the GLTF material for my controller. I move the controller into position and click/grasp the grab button on the side of the controller. nada

**Comment by hridpath** [comment]
I just tried to force the use of the alternate models and still no interactions.

**Comment by keveleigh** [comment]
Looks like there was a bug introduced with the prefab changes in the recent visualizer update. PR incoming with a fix.
