### ISSUE TITLE
App build crashes on Windows 10 without HMD/ Certification Kit fails

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1262]
We are developing for the Acer Mixed Reality Development Edition HMD. On a PC with the HMD connected our app will pass the Windows App Certification Kit tests. Without the HMD it fails:

```
FAILED
Crashes and hangs
Error Found: The crashes and hangs test detected the following errors:
Executable C:\Program Files\windowsapps\app_0.7.25.0_x64__qmf6y42tvhpew\app.exe was detected by Windows Error Reporting and experienced a crash or hang.
Application app_0.7.25.0_x64__qmf6y42tvhpew was detected by Windows Error Reporting and experienced a crash or hang.
Crash dump file C:\Users\x\AppData\Local\Microsoft\AppCertKit\app.exe.10124.dmp was created by Windows Error Reporting and provides additional information.
Crash dump file C:\Users\x\AppData\Local\Microsoft\AppCertKit\app.exe.17184.dmp was created by Windows Error Reporting and provides additional information.
Crash dump file C:\Users\x\AppData\Local\Microsoft\AppCertKit\app.exe.7876.dmp was created by Windows Error Reporting and provides additional information.
```

As I understand it, Apps for Mixed Reality HMDs are not differentiated from ordinary windows 10 apps in the store. This means, users can start the app without any HMD and just crash the app

Mainly, we receive the following two crashes:

```
APPLICATION_FAULT_1007_UnityPlayer.dll!SpatialInputImpl::SetEventHandlerAndAttach
APPLICATION_FAULT_AVRF_1007_UnityPlayer.dll!SpatialInputImpl::SetEventHandlerAndAttach
```

Is this known? Will this be addressed (hopefully soon)?

**Comment by keveleigh** [comment]
Hmm, I'm not aware if this issue has already been reported, but it seems like it should be filed as a bug with Unity.

**Comment by Alexees** [comment]
Where would that be reported if it's the Unity MRTK3 build?

**Comment by keveleigh** [comment]
Same way as normal: Help -> Troubleshoot Issue -> Report a new issue. Let me know the issue number and I can raise it on our end.

**Comment by ChimeraScorn** [comment]
Do you see this if you reboot the machine after unplugging the device, but before running the test?

**Comment by StephenHodgson** [comment]
It's the same error that gets thrown when the editor crashes when you don't have the headset plugged in. Definitely a unity bug.

**Comment by StephenHodgson** [comment]
Workaround found: make sure HMD is plugged in when running cert test

**Comment by linojon** [comment]
Not sure if the same thing but when i run the unity generate project from VS and hmd is not plugged in it crashes with this error
![hist-debug-x64-crash](https://user-images.githubusercontent.com/68624/32241928-dc9bef12-be47-11e7-9565-6cf72268f937.PNG)

**Comment by Alexees** [comment]
Opened bug report case 964561 on the Unity side.
