### ISSUE TITLE
Input Manager Tests no longer pass

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1263]
Input is working, but recent changes and updates have broken the test runner.

![image](https://user-images.githubusercontent.com/13334553/32176190-3133ac5e-bd44-11e7-9724-d48815a7ec7b.png)

**Comment by keveleigh** [comment]
![image](https://user-images.githubusercontent.com/3580640/32188404-f1aad78a-bd64-11e7-9a78-fd7b8f911ac1.png)

Looks like the issue is the new DontDestroyOnLoad calls.
