### ISSUE TITLE
InterpolatedValue might be able to use a method "Await" ?

### ISSUE THREAD

**Issue by erichfrazer** [Microsoft/MixedRealityToolkit-Unity#1266]
I inherited some code that uses a modified version of InterpolatedValue.cs, that has a method Await( ). Every time I import the toolkit, I have to re-add this method, and I'm not sure how to get rid of calling that method in the code I inherited. Could be by any chance add this method to InterpolatedValue.cs on the grounds it might be useful?

here is the code:

        /// <summary>
        /// Waits for the interpolator to complete, unless cancelled.
        /// The token won't cancel the execution of the interpoloatr
        /// </summary>
        /// <param name="token"></param>
        /// <returns></returns>
        public CoroutineEx Await(CancellationToken token)
        {
            return CoroutineEx.Run(Awaiter(), token);
        }

        private IEnumerator<Yield> Awaiter()
        {
            while (IsRunning)
            {
                yield return Yield.WaitForNextFrame;
            }
        }

**Comment by StephenHodgson** [comment]
I think `CoroutineEx` is not anything available in the current MRTK.

Last time I saw it I was working on an internal project there at MSFT.

**Comment by erichfrazer** [comment]
True. I wonder if we could add the Co-routine stuff to the MR Toolkit? If it's not being considered already!

**Comment by StephenHodgson** [comment]
I guess that depends on the guys who wrote it.

I found it useful, and a bit more flexible for working with coroutines in editor scripts.
