### ISSUE TITLE
Ungh - feel stupid - can't understand InputHandler stuff

### ISSUE THREAD

**Issue by erichfrazer** [Microsoft/MixedRealityToolkit-Unity#1270]
I don't see it in the docs. Help point me somewhere useful?

Suppose I have a Unity App and pull in the MRCameraParent, and "Managers", and "Cursor", and in my object's script, I want to detect some input stuff, let's keep the request simple as possible: 
1. If the CK controller is gained or lost
2. the position and rotation of the CK controller
3. the stabilized gaze ray

I don't get it. Lost at sea. First off, I can't fathom why GazeControls, with all it's sub-component axii (sp?) is a sub-object of CameraRig. What does GazeControls DO, anyhow? Wish objects in Unity had a ReadMe text string!  Next, I can't figure out what CameraRig's ManualGazeControl script is really meant to do. I read the blurb that says, "manually controls the camera when not running on HoloLens", but shouldn't ManualGazeControl be a script on InputManager, and it just finds the main camera and sets the position from there? Why is it attached to the camera? And, where does it get its input events from? From the GazeControl's sub-objects, right? Why don't GazeControl's sub-objects get their input from the InputManager? They get it directly from Input.XXX.

Next, InputManager. it's so hard to understand! How do I, a script in Unity, utilize InputManager to get callbacks about controllers coming and going, and how do I use it to get the position & rotation of a CK controller? Can I register for an event?

How does one use IInputHandler? Suppose my class implements IInputHandler, who do I register the callback with? What object? The JPEG shows InputManager implements a  method, RegisterInputSource, which sounds close, but no cigar, but that method doesn't exist. 

What does GazeManager do? I see it's managing the gaze ray, but how do I use it to find the gaze ray from my script? Simply call it? Register an event from it? Okay... but does it stabilize the headset gaze, or if I'm using a controller, will it stabilize and return where the controller is pointing? Hopefully just the main camera is "gaze"

which brings me to the last point - SimpleSinglePointerSelector.. it wants a cursor (I guess?). If my app doesn't have a cursor, but I want an object in my app to track wherever the single pointer is at, can I use the SimpleSinglePointerSelector to send me events about where IT thinks the current single pointer is at, so I can put my fake cursor at that spot?

A test app demonstrating all the above stuff would be pretty cool. All I want is a test app that allows me to look with my head, and point at things with my controller, and know when the controller comes into use and leaves, and if it's not in use, use something else as a controller for the pointer (cursor). My app needs to be able to call "something" and get the current single pointer's position and rotation. I can't figure that out (yet). Still diggin'.

**Comment by erichfrazer** [comment]
I'm making a little test scene. Seems if I put an object in the Scene, and call InputManager.Instance.AddGlobalListener, and implement (for example) IInputHandler, I get callbacks. The default cursor I put into the scene is initially controlled by my gaze, and when I fire up the CK controller, it's now being controlled by the controller. Wow.

Now, I need to figure out how to get notifications the CK died or went out of view, and when it comes back into use. Plus, if I'm getting a ray from the pointer, I want to get a stabilized ray. Wonder how to get that? Call GazeManager.Instance.GetStableRay or something like that? I assume InputManager runs each of it's pointer positions through GazeManager, right?

**Comment by StephenHodgson** [comment]
I'll write you up a detailed reply soon.

**Comment by StephenHodgson** [comment]
Nah, don't beat yourself up.  A lot of people say the same things about the input system, but it's mostly because of the lack of documentation and the vastness and complexity of the system itself.  I know I've done a terrible job at keeping the docs up to date recently, but things are moving so fast.

- `GazeControls`  is only for 2d screens (like standard apps for the editor) to mimic the hands/controllers.  Don't worry about that.

- If you need to get started quickly all this is setup for you via MRTK menu/ Configure / Apply Scene Settings.  Make sure all the checkboxes are there and it'll automagically add the `InputManger`, `DefaultCursor`, and `MixedRealityCameraParent` to your scene.

- Next if you've already got all your scene content on a single object named stage, or similar add the `SceneContentAdjuster` to it.

- From there you're ready to start wiring up inputs.  All input it funneled though the `InputManager` and out through each of the event interfaces.

    - IFocusable for focus enter and exit. The focus can be triggered by the user's gaze or any other gaze source.
    - IHoldHandle for the Windows hold gesture.
    - IInputHandler for source up and down. The source can be a hand that tapped, a clicker that was pressed, etc.
    - IInputClickHandler for source clicked. The source can be a hand that tapped, a clicker that was pressed, etc.
    - IManipulationHandler for the Windows manipulation gesture.
    - INavigationHandler for the Windows navigation gesture.
    - ISourceStateHandler for the source detected and source lost events.
    - ISpeechHandler for voice commands.
    - IDictationHandler for speech to text dictation.
    - IGamePadHandler for generic gamepad events.
    - IXboxControllerHandler for Xbox One Controller events.

- These interfaces are what you'll be referencing in your classes where you'll be implementing the inputs.  Once you reference the interface you're looking for you can start building from there.

**Comment by StephenHodgson** [comment]
>  If my app doesn't have a cursor, but I want an object in my app to track wherever the single pointer is at, can I use the SimpleSinglePointerSelector to send me events about where IT thinks the current single pointer is at, so I can put my fake cursor at that spot?

Yeah we should probably handle the case where users don't want to add a cursor to their app.

**Comment by StephenHodgson** [comment]
The `GazeManager` only handles the gaze stabilization, and nothing else.  The controllers are done differently I believe.

**Comment by erichfrazer** [comment]
This helps, but I’m still a bit shy of the target. Suppose I’m “adjusting” RoboRaid… I want to point the controller at enemies to shoot them, but I want the user’s HMD to be able to look anywhere. Unrelated to the controller. I need to use my own cursor, not the MR Toolkit’s. I want the camera’s position to be “smoothed” and I want the ray from the controller to be smoothed as well, but since they’re pointing different directions, they need to be smoothed separately.

 

Assuming I’ve added the appropriate MRTK’s stuff…

 

For my function GetHeadPosition, I am guessing I return GazeManager.Instance.GazeTransform.position

For the function GetPointerRay, I want to return the camera’s adjusted position IF there is no controller present, and if there is a controller present, I want to return the controller’s ray. What is the method off of InputManager that gets this ray for me? I’ve been staring at it for an hour and can’t figure it out. Granted, I had a tetanus shot yesterday and feel woozy, but it’s not clear to me yet…

 

thanks

**Comment by erichfrazer** [comment]
Oh, I see InputSource now has TryGetPointingRay. This is not obvious from the InputSystemDiagram.png, but obviously, I need to read up all the interfaces. Sorry 'bout that.

**Comment by StephenHodgson** [comment]
Yeah, and I also need to refresh the docs 😅

**Comment by erichfrazer** [comment]
Stephen, I want to email you question, but don’t know your email address. I bet a lot of my colleagues do. Can you write back to me and I’ll ask the question? It’s about a different project. One of my emails is public on my github page.

 

😊

**Comment by StephenHodgson** [comment]
Are you on the slack channel for the Holodevelopers? 
https://holodevelopers.slack.com

Might be better if we wanna have a more fluid conversation.

**Comment by erichfrazer** [comment]
It’s a private question. Not for a public channel. I’m not a member of the slack channel, how do I get an invite, through Microsoft administrators?

**Comment by StephenHodgson** [comment]
Click the link, and signup.  You can Private Message me there.

**Comment by erichfrazer** [comment]
I’m signed up on slack under the microsoft team. I don’t appear to be able to get into holodevelopers, or PM you. What gives. I don’t like slack so far… Plus, I’d rather what I ask you NOT be captured and logged and/or saved by Slack’s servers.

**Comment by StephenHodgson** [comment]
My apologies, I just thought it might be easier to convey the information faster that way.

**Comment by StephenHodgson** [comment]
Check your inbox

**Comment by erichfrazer** [comment]
Which inbox? Github? Slack? This is getting ridiculous. 😊

**Comment by StephenHodgson** [comment]
I sent it to github@dogstar.us

**Comment by erichfrazer** [comment]
I wonder if this will get back to you so far after the original email?

I haven’t used the MRTK in ages… I’m just now getting back into it, and I have to say, the docs seem worse than before, maybe I haven’t looked enough. Can you give me a pointer? I import the MRTK and then drag the MixedRealityCamera and the InputManager prefabs into my project. My goal is to use InteractionManager.InteractionSourceDetected event and to use “whatever” to figure out what the headset position was at various times in the recent past (last 1 second). I need to get the headset’s pose at any time within the last second. Is that possible?

**Comment by erichfrazer** [comment]
I want to get the head pose at an *exact* system time, 240 times per second. I need to get the pose, and a time stamp at which that exact pose actually happened.

**Comment by Ecnassianer** [comment]
240 times per second is extremely fast. Most tracking gear doesn't update faster than 90 fps, only a few at 120 hz. I don't know what the Hololens's position tracking hardware updates at, but I've never heard of anything updating at 240 hz. Even if you could get Unity running at 240 fps on a Hololens, most of those locations are going to be duplicates.

Can you elaborate more on what you mean by "*exact* system time" and why you need 240 hz poses? The general guidance for VR is consistent 90 fps/hz, though you can get by with 60fps/hz. For AR 60 fps/hz is sufficient. If you're doing some kind of specialized position measurement scenario for research or industry and you really do need data accurate to the 1/240th of a second, you're going to need custom tracking hardware that's specialized in that. However, the vast majority of applications are fine with 60/90hz.

Unity has a library called Time, and I generally use Time.time to keep track of time, however if you need real world time you can use .NET's System.DateTime.Now.

**Comment by erichfrazer** [comment]
240HZ for a gyro sensor isn’t normally that fast. 240HZ for a display would be ridiculous. Normally if you want to stabilize your head/view/etc, having a gyro sensor data at a higher frame rate than your display fps is advisable.

**Comment by Ecnassianer** [comment]
This is getting a fair bit out of my area of expertise, but from what I understand, Hololens only uses the gyroscope and other IMU sensors to get information on location in order to approximate the position of the depth cameras, which themselves provide sufficiently precise position data for head tracking. You're thus constrained by the update rate of the depth cameras, not the IMU. Furthermore, if you're using MRTK, you're more or less constrained (sans authoring your own Unity DLL) to Unity's Update functions, which you're not going to get running at 240 fps on Hololens.

In the larger context of Unity MRTK, 240 hz position data is extremely fast. If you'd like to tell us more about what your goal is, we might be able to help you find a way to achieve your goal with a slower position sampling rate.

**Comment by StephenHodgson** [comment]
You could probably poll data faster if you just start off a new thread. Not really something that Unity is confining a dev into using the update loop.

**Comment by aashish-ak** [comment]
@StephenHodgson  I'm also unable to sign in to the slack channel, when open the link holodevelopers.slak.com it asks for signin and no signup option is there, can you help me get in.

**Comment by davidkline-ms** [comment]
@aashish-ak, You can generate an invite for slack at http://holodevelopersslack.azurewebsites.net

Thanks!
