### ISSUE TITLE
Clicker Doesn't Work

### ISSUE THREAD

**Issue by Caltato** [Microsoft/MixedRealityToolkit-Unity#1271]
Hi, I'm having a little trouble getting the clicker input. From what I've gathered, all I should need to do is have my script extend IInputClickHandler and the clicker should call OnInputClicked. And if I want it to react without it needing to focus I just set a global listener as well right? Or am I doing this wrong?

I've done the above mentioned and it works for when I air tap. However the clicker still does nothing. (Though the clicker is connected to the Hololens)

**Comment by StephenHodgson** [comment]
I'll need to dig up a clicker to test this with to confirm.

**Comment by Caltato** [comment]
Yeap I have tried both adding it to global listeners as well as just gazing and clicking. Sadly, neither worked.

**Comment by Caltato** [comment]
Update: I tried using the clicker in the example scenes for input. Doesn't work. ;/ Any ideas for possible reasons as to why it isn't working? @StephenHodgson

**Comment by StephenHodgson** [comment]
Haven't had time to verify this bug. Sorry.

**Comment by Caltato** [comment]
No worries! @StephenHodgson

**Comment by StephenHodgson** [comment]
@Caltato see if PR #1256 fixed your issue. 

I updated all the inputs that don't come from the controller to automatically use the select key press type

**Comment by Caltato** [comment]
@StephenHodgson Hey thanks! I'll try it out and update you when I get back to the office on Monday. Cheers

**Comment by Caltato** [comment]
Hi @StephenHodgson, it still doesn't seem to work, unfortunately. Does it work for you? If so, maybe I'm doing something wrong.

**Comment by StephenHodgson** [comment]
I don't have a clicker to test with, so I can't confirm.

**Comment by Caltato** [comment]
Oh I see. Hmm...

**Comment by StephenHodgson** [comment]
I was able to dig one up today. Here's what I found:

```
OnInputDown
Source: GesturesInput (HoloToolkit.Unity.InputModule.InteractionInputSource)  SourceId: 2000000004  InteractionPressKind: None

OnInputUp
Source: GesturesInput (HoloToolkit.Unity.InputModule.InteractionInputSource)  SourceId: 2000000004  InteractionPressKind: None

OnInputClicked
Source: GesturesInput (HoloToolkit.Unity.InputModule.InteractionInputSource)  SourceId: 0  InteractionPressKind: Select  TapCount: 1
```

Seems like the clicker source is raising `OnInputClicked` correctly (although from the wrong `SourceId`, but not raising `OnInputUp/Down` correctly with the right pretty type.

**Comment by StephenHodgson** [comment]
Ha, so the apparently the Clicker counts as a `InteractionSourceKind.Controller` but when it's clicked does not correctly raise the `InteractionSourcePressType.Select` properly.  It's the same issue we were having with the hands in the HoloLens.

**Comment by Caltato** [comment]
Oh! I see. But if it raises `OnInputClicked` correctly why doesn't it call the code in the function?

**Comment by StephenHodgson** [comment]
Not sure, I can get the `OnInputClicked` just fine for me, in the InputManagerTest scene.

Just the other stuff isn't working properly.

**Comment by Caltato** [comment]
HAHA Oh man. The test scene doesn't work for me though

**Comment by StephenHodgson** [comment]
What version of the Editor are you running?

**Comment by Caltato** [comment]
I tried both 2017.1.2f1 and 2017.2.0f3

**Comment by StephenHodgson** [comment]
I could see why 2017.2.0f3 wouldn't work.

**Comment by StephenHodgson** [comment]
But 2017.1.x I'm surprised doesn't

**Comment by Caltato** [comment]
Yeah. I dont know. I'm quite stuck

**Comment by Caltato** [comment]
I don't need to connect the clicker to unity in any special way or anything right?

**Comment by StephenHodgson** [comment]
Nope, Working on a fix/workaround.

**Comment by Caltato** [comment]
Alright then. Thanks man

**Comment by Caltato** [comment]
Oh! @StephenHodgson Okay so, I have been using Holographic Emulation to test all this time and it wasn't working but I just built it on the hololens and the clicker works fine.

So I guess it's just the holographic emulation. But any reason for that?

**Comment by StephenHodgson** [comment]
Yeah, bc the clicker isn't paired with the PC you're remoting from.

**Comment by Caltato** [comment]
Ahhh. Can it though?

**Comment by StephenHodgson** [comment]
Lol no, I don't think so. But I've never tried.

Essentially when you're remoting to the device you're rerouting all the inputs from the PC to the HoloLens

**Comment by Caltato** [comment]
Yeah can't. There's no suitable driver for it even though it is discoverable. Oh well. Thanks for all the help anyway. Sorry for the bother!

**Comment by StephenHodgson** [comment]
Well, it actually is still a problem for 2017.2

**Comment by Caltato** [comment]
Is it? I was just about to try it actually
