### ISSUE TITLE
Windows Holographic SDK not added when applying Mixed Reality Project Settings

### ISSUE THREAD

**Issue by rolandsmeenk** [Microsoft/MixedRealityToolkit-Unity#1272]
HoloLens Development with Unity2017.1.2.f1 and HoloToolkit-Unity-v1.2017.2.0, Windows 10 version 1709

1. Create empty project -> Mixed Reality Toolkit -> Configure -> Apply mixed reality project settings
2. Edit -> Project Settings -> Player -> Virtual Reality SDKs -> Windows MR (missing from build)
3. Need to manually add Windows Holographic to be able to use "Simulate in Editor" or "Remote to Device"

**Comment by StephenHodgson** [comment]
Hmm, I thought I had fixed this. I'll double check.

**Comment by StephenHodgson** [comment]
I did. But it didn't make it into the last release. See #1251

**Comment by StephenHodgson** [comment]
For now the best workaround is to manually add windows holographic or update your project settings window class with my changes

**Comment by rolandsmeenk** [comment]
OK, thanks for the update.
