### ISSUE TITLE
Help converting from Hololens AR to Headset MR

### ISSUE THREAD

**Issue by Skquark** [Microsoft/MixedRealityToolkit-Unity#1273]
So I had my project working pretty well in the Hololens Emulator, where I begin with walking around to scan mesh then tapping to build the surfaces to populate the environment.  Now I got my Mixed Reality Headset with 2 motion controllers and trying to adapt my project to work in the VR and having confusions/problems.  I disabled the Hololens camera manager and added the MixedRealityCameraParent, no problem there.  I built a room in Sketchup and imported in, colored with the FastConfigurables, added the Mesh Collider, etc.. All is good there, I can build and I'm no longer floating on just the boundary Floor Quad and can see my motion controller and teleport, happy about that.. 
I went to my SpatialMapping component and in the ObjectSurfaceObserver I made my Room Mesh my fbx room model instead of the sample office mesh, and I hope there's a way to make that work to create the SurfacePlane list dynamically from that.  My alternative is to manually place the SurfacePlanes on my walls and floor the same way spatial mapping generates it for my Hololens code to work.  Any advice?

I'm trying to adapt all my Update() code using GazeManager, gazeHitPoint, gazeObject and tap into the Motion Controller inputs so the left & right hand + trigger replaces the gaze.  I looked through the MotionConrollerVisualizer script and the best hint I could find is to extract the controller info from InteractionManager.GetCurrentReading() but it seems like there should be an easier abstracted way to get the controllers' states.
Does a trigger click from the 3D controller do the same as a gaze tap in the Input handlers?  I didn't get much out of the MotionControllerTest example unfortunately..

Another head scratcher I ran into was figuring out what if statement or #if def used to tell the difference between a Hololens transparent device and a Mixed Reality occluded device run?  That should be a simple one but couldn't find reference anywhere...
Thanks, I have more questions on the MR porting process, but I'll save it for after.  I'm just anxious to see my baby working on my goggles..

**Comment by StephenHodgson** [comment]
What version of unity and the toolkit was your old project you're porting?

**Comment by Skquark** [comment]
I'm on Unity 2017.2.0f3 and on the latest MRTK release build.. I was on the Dev branch for a while so I can get a jump on the mixed reality bits, but then switched back to master when those changes got merged.
My opening code is based on the SpatialUnderstandingExample with the room scanning from AppState.cs, so when it starts we're walking around room to scan environment and waiting for a tap from OnInputClicked to RequestFinishScan and I can't get that to work to generate the SurfacePlanes to move on to the next parts...
Thanks.

**Comment by Skquark** [comment]
Just an update/clarification, I tried forcing the RequestFinishScan and ScanComplete of SpatialUnderstanding with the MixedRealityCamera instead of HololensCamera, and I can't get it to generate the list of SurfacePlanes it was able to extract from the given room mesh model like it was able to do when we were in Hololens mode..
So right now, the core of my question is how to mimic the effect of finishing a room scan and making the recognized surfaces with an occluded device?  To duplicate the circumstance, open SpatialUnderstandingExample and run it in the Mixed Reality Portal then try to finalize the spatial mapping of a fake room mesh.  Is there a way to hack it to have the same results as Hololens, or do I have to fake it the hard way?

**Comment by Skquark** [comment]
I'm trying to answer my own question here, but still need help.  I'm figuring out the new Motion Controller Input Interface by taking apart the example script DebugPanelControllerInfo.cs and generating custom events from InteractionManager_InteractionSourceUpdated, so I should be able to get that working right soon.
Also figured out my question on the if statement for the difference between Mixed Reality and Hololens by using if (HolographicSettings.IsDisplayOpaque) ....

I'm still stuck on the SurfacePlane generator, and I imagine anybody else using the SpatialMapping from Hololens in their Mixed Reality hybrid project would be having this same issue.. It used to work fine in the editor to finalize the surfaces before the mesh scanning, but no longer since the MixedRealityCameraParent and the preview opening in the Mixed Reality Portal.  So the short of the question is how could we fix the SpatialUnderstandingExample to immediately finalize the mesh provided in ObjectSurfaceObserver to make the SurfacePlane list?  Thanks.

**Comment by StephenHodgson** [comment]
All you need to do is implement the input interfaces in your scripts.  You don't have to subscribe to the `InteractionManger` if you don't need to.

**Comment by Skquark** [comment]
Yeah, I just didn't like that method of attaching the input interface script to every game object that I want to make interactable, didn't flow well with what I'm making.  I already had it working by using the current gaze object when tapping or using the other gesture or motion controls, I worked out some tricky hacks to hold it together.

However, my question wasn't really about that, I'm trying to get my SurfacePlanes back because nothing in my project works without those placed in the world first.  If there's no way to generate the surfaces from the Mixed Reality headsets at this time, let me know so I can manually place the SurfacePlane objects on my walls and floors just so I can move on, but I'd prefer doing it the right way of automatically placing them from the room mesh.  Thanks.

**Comment by davidkline-ms** [comment]
The Mixed Reality immersive headsets do not support Spatial Mapping, rather they support setting a boundary which will be displayed to your users as they near it.
