### ISSUE TITLE
Error CS8059: Feature 'out variable declaration' is not available in C# 6. Please use 7.

### ISSUE THREAD

**Issue by erichfrazer** [Microsoft/MixedRealityToolkit-Unity#1276]
I'm getting this as a VS 2017 compile error. I'm using Unity 2017.2.0f3-MRTP3, and just started getting this error. I created an empty project, switched it to UWP, set target to "any device", SDK = latest installed, nothing else checked. Set player flags to VR. added a cube, added a script to the cube, went into VS 2017 and compiled. It has "TestProject" and "TestProject.Player" as two separate projects in my VS tree. Compiles great.

Now, I import the MR Toolkit, as a package. VS 2017 wants to reload the SLN, so I say yes, and now it has 3 projects, it added "TestProject.Editor", and now when I compile, it says 

```
2>D:\RanGal\TestDll\Assets\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(52,62,52,64): error CS8059: Feature 'out variable declaration' is not available in C# 6. Please use language version 7 or greater.

2>D:\RanGal\TestDll\Assets\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(88,22,88,50): error CS8059: Feature 'local functions' is not available in C# 6. Please use language version 7 or greater.
```

How do I set unity to use a different compiler version in VS?!

**Comment by StephenHodgson** [comment]
Go to your player settings and see if your settings match these ones:
![image](https://user-images.githubusercontent.com/13334553/32234568-6b133d82-be1a-11e7-9193-65d65c0fe46f.png)

**Comment by erichfrazer** [comment]
It was set to Scripting Backend = IL2CPP. When I switch the Build Settings to UWP, why does this value stay IL2CPP? Anyhow, that fixed it. Thank you again!

**Comment by StephenHodgson** [comment]
IL2CPP is Unity's default scripting backend.
