### ISSUE TITLE
[master] How to draw a ray for the CK controller

### ISSUE THREAD

**Issue by erichfrazer** [Microsoft/MixedRealityToolkit-Unity#1277]
This is silly question, I'm a bit new to Unity...

I want to draw a ray from the CK controller out into the scene where it's pointing. I reckon I can get the ray start/stop points, but how to draw the actual ray? I'm thinking of using a mostly-transparent cylinder that tapers to a point, and using scaling to modify its length. Is there a better way to do this? Anybody working on some proto-code for a ray drawer that they can share? or, is it already in the toolkit, and I haven't seen it?

**Comment by StephenHodgson** [comment]
If you're in the editor you can use the debug draw pointing ray on the `FocusManager`.
![image](https://user-images.githubusercontent.com/13334553/32239171-05478f8c-be27-11e7-9078-c98ab2e301a0.png)


Otherwise you might have to implement yourself. I'm not sure we have anything in the toolkit for that yet.

**Comment by keveleigh** [comment]
@darax added an initial implementation of pointer rays and arc teleporting rays (like the shell) to Mixed Reality 250.
They haven't yet been ported to the Toolkit though.

https://github.com/Microsoft/MixedReality250/blob/master/Assets/HoloToolkit/Input/Scripts/ControllerInfo.cs#L332
https://github.com/Microsoft/MixedReality250/blob/master/Assets/HoloToolkit/Input/Scripts/ControllerVisualizer.cs#L306
https://github.com/Microsoft/MixedReality250/blob/master/Assets/HoloToolkit/Input/Scripts/Gaze/MixedRealityTeleport.cs#L321

**Comment by erichfrazer** [comment]
Oh, nice. I'll look there. thanks.

**Comment by erichfrazer** [comment]
1.	Not useful to see the ray in the editor, I have the headset on my head!
2.	Want to see it in the app. Would be a useful addition to the toolkit. I’ll put it in myself, if I figure it out and I’m allowed to.

**Comment by StephenHodgson** [comment]
There's been some talk of it.  Also, I think the MRDL merge will include these types of things.

**Comment by Alexees** [comment]
@keveleigh What's the difference between Microsoft/MixedRealityToolkit-Unity and Microsoft/MixedReality250 where your code examples come from. Cause it seems to also fix the problem with update inconsistencies between controller data and controller visual positions by removing the need for onBeforeRender.

**Comment by keveleigh** [comment]
It doesn't remove the need for onBeforeRender, it has an older drop of the Toolkit. The older drop does it wrong according to the guidance I've been given by our platform team, which prompted the script update. Polling in onBeforeRender is the correct way to get the controller info for rendering, while polling in Update or using the InteractionManager events is the correct way to get the controller info for game logic. I'm planning on updating the cursor and pointing ray rendering to fit these new guidelines when I get the time.

**Comment by erichfrazer** [comment]
I was under the impression that depending on your logic, onBeforeRender or Update were used, but most often, almost never use both. If onBeforeRender is useful directly prior to rendering, how is Update( ) *more* useful for game logic? If we’re getting the update in the game logic, and we’re about to render, how is that any more proper than getting the values in onBeforeRender? Also, isn’t onBeforeRender more costly (in terms of time) than Update?
