### ISSUE TITLE
"Help Wanted" Accessing SyncRoot

### ISSUE THREAD

**Issue by hansbickhofe** [Microsoft/MixedRealityToolkit-Unity#1278]
Hi all,
how can I get Information of some Elements in the SyncRoot from  a script?

Regards, Hans

**Comment by StephenHodgson** [comment]
Take a look at the `SpawnManager` and how it get's the `SyncArray<T> SyncSource` from the `SharingStage.Root.InstantiatedPrefabs`

**Comment by NeerajW** [comment]
Please reopen if you have other specific issues.
