### ISSUE TITLE
Motion controller : near plane and cloning problem in Unity 2017.2.0f3

### ISSUE THREAD

**Issue by JJJJHao** [Microsoft/MixedRealityToolkit-Unity#1279]
1.
I met some problem when using the HMD in Unity project.
In the hierarchy of my project, for some reason the parent of my "MixedRealityCameraParent" should be scaled to 0.12 . just like the picture below
<img src="https://us.v-cdn.net/6026774/uploads/editor/4v/506cxzoxg3y4.jpg">
But actually I've met some problem when using the HMD because the near plane is not as near as I think. In the Scene window, the plane doesn't clip my controller at all, but in the Game window (or watching in the HMD), my controller is actually clipped.
The main reason is that I change the scale of the parent of "MixedRealityCameraParent".
Is there any way to edit the camera rendering formula or adjust something to fix this problem?
2.
I find that the motion controller should be cloned by the script.
Is there any way that we can put the gameObject directly in the hierarchy of Unity like HTC Vive?
Because I have to change some HTC Vive project into Windows Mixed Reality project.

Thanks a lot!

**Comment by StephenHodgson** [comment]
Why is your camera parented on another game object?

**Comment by JJJJHao** [comment]
Because in my project, I have to scale the player into a smaller size, to meet the need of the environment's resolution.

**Comment by StephenHodgson** [comment]
I think that's a bad idea.

Instead you should be adjusting the scale of your objects.

**Comment by JJJJHao** [comment]
Thanks a lot for answering my question!
But as I mentioned above, I cannot adjust the scale of the object around me because of the resolution. Is there any way to edit the formula calculating in the camera?
Because the project is changed from the HTC Vive project. In the HTC Vive project, I didn't met this problem.

**Comment by keveleigh** [comment]
It makes sense that it isn't clipped in the scene view, because that isn't showing you things from the perspective of your camera, like the game window/HMD does.

Scaling the camera likely does unexpected things.

What are your camera clipping planes set to in the Vive project?

**Comment by StephenHodgson** [comment]
The resolution of your texutres, or the mesh itself?

The mesh resolution wouldn't make a difference, but the texture scaling can also be done too to make it look the same without scaling your camera.
