### ISSUE TITLE
Where does the MR camera's transform get its readings from?

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1280]
I've looked through the API but couldn't find how the camera's transform is driven. Where does it receive it's orientation data?

**Comment by StephenHodgson** [comment]
Most likely ` UnityEngine.XR.XRNode.Head`

**Comment by Alexees** [comment]
The only script I could find using either UnityEngine.XR.XRNode namespace or just XRNode is some FogVolumeCamera. Does this mean the camera is driven from outside the manage side or from within a dll?

**Comment by StephenHodgson** [comment]
The API above should give you the information you're looking for.

**Comment by NeerajW** [comment]
Please reopen if you still have specific issues. Perhaps asking on Unity forums might help with this one as well.
