### ISSUE TITLE
Sharing: Server

### ISSUE THREAD

**Issue by Taghazog** [Microsoft/MixedRealityToolkit-Unity#1281]
This is not really an issue but a request as i don't really understand something about the server right now.
Why can't we run that server on a Hololens?
It makes every possible sharing experience with Hololens only not possible as soon as you don't have an external server running on Desktop. Will it be possible to share experience with only hololens?

**Comment by StephenHodgson** [comment]
Direct pairing used to be possible, but I think got broken somewhere along the way.

The main [MixedRealityToolkit](https://github.com/Microsoft/MixedRealityToolkit) is where this code resides, and you might have better luck asking questions and making pull requests there if you want to update it.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
