### ISSUE TITLE
F key mapped to fade script

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1283]
We shouldn't have [special mapped keys](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/2acbb55496aa689541be74f5e4b4f9bfe49b249a/Assets/HoloToolkit/Utilities/Scripts/FadeScript.cs#L68) like this in production scripts. Maybe adding a debug switch to enable/disable when testing is appropriate.

**Comment by Alexees** [comment]
Wanted to add that the a key is mapped to xbox controller A-Button AND WASD movement when not using HMD. For me that led to confusion when flying around in the scene and toggling objects with the gaze all the time.

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
