### ISSUE TITLE
When will MRDL basic controls be merged into MRTK?

### ISSUE THREAD

**Issue by DreaminginCodeZH** [Microsoft/MixedRealityToolkit-Unity#1284]
My team was trying to use the Holographic-Shell-like MRDL App Bar and BoundingBox controls in our MRTK app, and found that MRDL baseline functionality has been successfully merged hours ago. So I wonder when will the MRDL basic controls be merged, and will it land in v1.2017.2.0 or v1.2017.3.0?

**Comment by StephenHodgson** [comment]
We're still working on it. There's currently an active PR #1197 open for some basic stuff already.

**Comment by cre8ivepark** [comment]
@DreaminginCodeZH PR #1197 includes basic Holographic Button in the InteractableObjectExamples scene. App Bar and BoundingBox control is on phase 2 list - we are updating it to support motion controller's pointer input too.

**Comment by DreaminginCodeZH** [comment]
Thanks for the quick response! I wonder when will the phase 2 controls be merged, and will it land in v1.2017.2.0 or v1.2017.3.0?

**Comment by StephenHodgson** [comment]
ASAP

**Comment by DreaminginCodeZH** [comment]
Just one more question, is it possible for the AppBar and BoundingBox to be merged within two weeks? If not, our team will have to roll our own solution due to time constraint.

**Comment by cre8ivepark** [comment]
@Railboy could you please share rough timeline for your App Bar + Bounding Box updates?
