### ISSUE TITLE
HandDraggable not working

### ISSUE THREAD

**Issue by sathiyasankar** [Microsoft/MixedRealityToolkit-Unity#1286]
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/445c8163590d7b09224dae6a22eb2dc2e0cea230/Assets/HoloToolkit/Input/Scripts/InputSources/InteractionInputSource.cs#L706

This line is always giving value of false which makes HandDraggable not to work. 
If we remove the second parameter InteractionSourceNode.Pointer, then it is working fine. 
Can some one please check whether it is a real issue? If so, please fix this.
I am not sure on other impacted areas though.

**Comment by samharper94** [comment]
What version of Unity/MRTK are you using? Are you using a HoloLens? HandDraggable works fine for me with a HoloLens on 2017.1.2f1 with the current MRTK.

**Comment by sathiyasankar** [comment]
hi @samharper94 , I am using HoloLens device with Unity 2017.3.0b4 and MRTK 2017.1.2.
I downloaded the source code of HoloToolKit from master branch and using that.

**Comment by samharper94** [comment]
Ah, there's the issue! For HoloLens development, you need to stay with Unity 2017.1.x and 10.0.15063.0 SDK. See #1184 for more :)

**Comment by sathiyasankar** [comment]
Oh....I didn't noticed that. Thanks for pointing it out :)
