### ISSUE TITLE
When in editor MixedRealityCameraManager always initializes opaque display when using remoting to HoloLens

### ISSUE THREAD

**Issue by rolandsmeenk** [Microsoft/MixedRealityToolkit-Unity#1287]
The detection and switching between opaque or transparent display is only working when not in editor. When remoting to HoloLens this results in usage of the Opaque Display settings.

**Comment by StephenHodgson** [comment]
Is there a way to know if you're remoting into a device?

**Comment by rolandsmeenk** [comment]
Hmmm, I don't now either. Could not find a direct API and could not find any differences in SystemInfo, Loaded Assemblies, Displays, Application, EditorApplication. 
Maybe just add an editor flag that indicates the user's preference?

**Comment by StephenHodgson** [comment]
I'd rather it be automatic instead of a flag

**Comment by keveleigh** [comment]
Fixed (a while ago) via #1362.
