### ISSUE TITLE
If you use the Fast Configurable 2 Sided shader texture works only with initial texture

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/MixedRealityToolkit-Unity#1288]
If you use the Fast Configurable 2 Sided shader, don't set an initial Texture and try to set it runtime it will not display the texture
Workaround - set a dummy texture at startup . Any texture. Just make sure there is a startup texture.

**Comment by Cameron-Micka** [comment]
I would recommend using the new MRTK/Standard shader with the "Cull Mode" set to "Off" for two sided materials.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
