### ISSUE TITLE
High OS Version validation detected the following errors

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1292]
The WACK validation fails with one error when building an App with this toolkit from Unity. this started happening after the rollout of the fall creators update.
The following link pretty much shows it all. Since I don't know if this is caused by the toolkit or Unity itself, I wanted to start here

https://stackoverflow.com/questions/35543903/the-high-os-version-validation-detected-error-during-windows-app-certification

**Comment by StephenHodgson** [comment]
Make sure you've got the latest versions from visual studio.

I can get the toolkit to pass wack locally in my machine.

**Comment by Alexees** [comment]
I'm running Visual Studio 15.4.2.
Windows is on the ProInsider Preview Build 17025 from 20.10.17
Unity is the MRTP3 version.
The MixedRealityToolkit's last pull is from Friday last week.
Is this issue at least known and was fixed by some known update?

**Comment by StephenHodgson** [comment]
I'd double check your appx manifest to make sure it's targeting 16299

**Comment by Alexees** [comment]
OK, the problem was that building from Unity without copying references left most settings in tact. However the store build settings reverted back to release. I accidentally built for release instead of master and that's why the API wasn't stripped off I guess.
