### ISSUE TITLE
Minor issue with FastConfigurable shader

### ISSUE THREAD

**Issue by MohGhareeb** [Microsoft/MixedRealityToolkit-Unity#1295]
So when you convert a transparent standard shader material to FastConfigurable, it set the blending equation parameters correctly, but it doesn't set the render queue to 3000 (transparent), which causes error in culling calculations.

I dont know if this is working as intended, but I spent a good while scratching my head why my transparent materials were not acting properly.

**Comment by StephenHodgson** [comment]
@dbastienMS Any Ideas?

**Comment by MohGhareeb** [comment]
So I did some investigating, and I found out that the magic happens in the function AssignNewShaderToMaterial in FastConfigurableGUI.cs editor script, the problem happens in base.AssignNewShaderToMaterial call, the material enters that call with the correct render queue and exits it with always opaque (i.e 2000) render queue, which in turns invalidates the flag later in the code.
I think it should pre-fetched before calling the base function like the _Emission property.

**Comment by StephenHodgson** [comment]
Fast configurable shader was depreciated. Please use the MRTK Standard Shaders.
