### ISSUE TITLE
Why is information stripped from touch pad press events?

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/MixedRealityToolkit-Unity#1296]
I seem to be only getting events that tell me _that_ the touch pad is pressed, not _where_. Looking at 
InteractionInputSource, find this method

private void InteractionManager_InteractionSourcePressed(InteractionSourcePressedEventArgs args)
{
    InputManager.Instance.RaiseSourceDown(this, args.state.source.id, (InteractionSourcePressInfo)args.pressType);
}

where args indeed contains touchpadPosition (and a wealth of other info). But to the inputmanager, only the source id and the fact that the touchpad is pressed is passed on.

Why is this? Why is information that can be useful stripped? Am I missing something? Should I look elsewhere for this information

**Comment by keveleigh** [comment]
Yep, as currently coded, you can call [`source.TryGetTouchpad`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/InputSources/InteractionInputSource.cs#L583) to get the position.

You can also monitor the [OnInputPositionChanged event](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/InputHandlers/IControllerInputHandler.cs).

You could also use the [TouchpadTouched/Released events](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/InputHandlers/IControllerTouchpadHandler.cs), though the position could be added to the event data to provide more info.

You have a couple options here.

**Comment by LocalJoost** [comment]
Ah. I see. Thanks
