### ISSUE TITLE
Do I have to do anything in order for the Dictation Recognizer to work with the keyboard?

### ISSUE THREAD

**Issue by dtb49** [Microsoft/MixedRealityToolkit-Unity#1299]
I am trying to implement the keyboard prefab to my project. I can get it to show up and everything and typing works. However, when I press the "speech" button, nothing happens. I have the microphone capability enabled as well as internet client. Is there anything else I need to do in order for the dictation recognizer to work with the keyboard?

**Comment by StephenHodgson** [comment]
Yeah, it needs to be completely refactored to use the `DictationManager` See #834 and #976

**Comment by dtb49** [comment]
That would be it haha I hadn't even looked at the source code beforehand. But, implemented dictation recognizer from Holograms 212 into it and it works nicely now.

**Comment by keveleigh** [comment]
Fixed via #1496
