### ISSUE TITLE
MRTKEditor system is overriding behaviour of [Header] attribute.

### ISSUE THREAD

**Issue by DaveSullivanAtWork** [Microsoft/MixedRealityToolkit-Unity#1300]
The class CustomHeaderDrawer.cs overrides the behaviour of the HeaderAttribtue (unity inspector decorator).
This means that if you are not using the MRTKEditor system for your inspector drawing, the header will not be displayed.  This is controlled by the MRTKEditor.ShowCustomEditors static boolean value.

I don't think that changing core functionality of the unity editor system like this is a good idea and will be confusing for people when all their custom headers suddenly disappear.

I cannot see the [Header] attribute being used anywhere within the MTRK that also uses the MRTKEditor, so I suggest we change this to be a custom attribute and drawer instead of a modification of the standard unity [Header] drawing.

i.e. create a MRTKHeaderAttribute class.

Thoughts?

**Comment by StephenHodgson** [comment]
@Railboy please be sure to address this bug with your latest MRDL PR.

**Comment by Railboy** [comment]
I'll include a fix in #1318.

>I don't think that changing core functionality of the unity editor system like this is a good idea

Agreed. MRTKEditor is supposed to be a lightweight skin that offers additional information. Default editors shouldn't be disrupted.

**Comment by Railboy** [comment]
Fixed in #1318.
