### ISSUE TITLE
PressType on Hololens in Unity 2017.2 is None

### ISSUE THREAD

**Issue by markgrossnickle** [Microsoft/MixedRealityToolkit-Unity#1302]
This seems like it may be more of a Unity issue than a Toolkit issue.

`UnityEngine.XR.WSA.Input.InteractionManager`
InteractionSourceReleased and InteractionSourcePressed both have an args.pressType of None when using the Hololens.  

When the InputManager.Instance.RaiseSourceUp and RaiseSourceDown are called with None it means the UI events are ignored.  A good test case is using the toolkit's Keyboard.prefab.  The roll overs will work fine by no press or release will ever be triggered.

The following quick hack works for my use case but I am uncertain is none is ever a valid PressType which I am now stomping:

``` 
private void InteractionManager_InteractionSourceReleased(InteractionSourceReleasedEventArgs args)
        {  
            var pressType = (InteractionSourcePressInfo)args.pressType;
            if (pressType == InteractionSourcePressInfo.None) pressType = InteractionSourcePressInfo.Select;
            InputManager.Instance.RaiseSourceUp(this, args.state.source.id, pressType);
        }

        private void InteractionManager_InteractionSourcePressed(InteractionSourcePressedEventArgs args)
        {  
            var pressType = (InteractionSourcePressInfo)args.pressType;
            if (pressType == InteractionSourcePressInfo.None) pressType = InteractionSourcePressInfo.Select;
            InputManager.Instance.RaiseSourceDown(this, args.state.source.id, pressType); 
        } 
```

This occurs in both 2017.2.0f3 and 2017.2.0p1.

**Comment by StephenHodgson** [comment]
I'll be sure to address this in #1256
