### ISSUE TITLE
SharingTest stalling after connection

### ISSUE THREAD

**Issue by dave-trainor** [Microsoft/MixedRealityToolkit-Unity#1303]
Building the SharingTest scene and deploying on Hololens results in a connection to the running Sharing Service server and then the Hololens app stalls, with no unity splash screen or game objects created. No previous room and anchor information has been persisted as this is the first time sharing has been enabled. Could this impasse be caused by some aspect of SharingWorldAnchorManager that was/is handled differently by the ImportExportAnchorManager or RoomTest scripts?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
