### ISSUE TITLE
Redundant Script OptimizeSceneForDeviceType does not compile for Unity 2017.1

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1304]
When opening the current master branch in the Unity Editor 2017.1 this class does not properly wrap the Unity.XR class.

This class also is largely redundant to `SceneContentAdjuster` and the `MixedRealityCameraParent` classes.

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
