### ISSUE TITLE
The Capability Settings Window applies changes before Apply is pressed

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#1306]
The calls to `ApplySetting` in `OnGuiChanged` mean that the capabilities are changed whenever a box is checked/unchecked instead of when Apply is clicked.

https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/Editor/CapabilitySettingsWindow.cs#L94

Repro steps:
1. Open the Player Settings via Edit -> Project Settings -> Player
2. Select UWP, then Publishing Settings, and scroll down to Capabilities.
3. Open Mixed Reality Toolkit -> Configure -> Apply UWP Capability Settings
4. Check and uncheck capabilities in this window while watching the Capabilities from step 2.

Expected: Nothing changes until I press Apply.
Actual: The capabilities are changed by the actions in step 4.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
