### ISSUE TITLE
Voice chat not working in MixedRealityToolkit v.2017.2.0!

### ISSUE THREAD

**Issue by mr-mystery** [Microsoft/MixedRealityToolkit-Unity#1310]
@StephenHodgson MicrophoneTransmitter and MicrophoneReceiver have been removed from the MixedRealityToolkit v.2017.2.0.
It is mentioned as "Group Voice Chat" feature is given as built in option in Mixedreality Toolkit, but how to implement in a unity project?
What are the new scripts or components need to be added for incorporating Voice Chat?
Tools Used:
Unity Version : Unity 2017.1.2 f1
Toolkit Version : MixedReality Toolkit v.2017.2.0

**Comment by StephenHodgson** [comment]
@mr-mystery It wasn't removed, but moved to the examples folder. It wasn't being well maintained and the dlls do not pass WACK.

**Comment by mr-mystery** [comment]
So, does it mean we need to import the examples unity package as well to our "whatever" project?

**Comment by StephenHodgson** [comment]
Windows application certification kit. It tests your app before it can be published in the app store.

You could present just copy/paste when you need.

**Comment by mr-mystery** [comment]
Thank you very much bro.

**Comment by mr-mystery** [comment]
@StephenHodgson If the VOIP didn't pass the wack. And if I implement it from the examples folder to my project, will I be able to upload to the windows store?

**Comment by StephenHodgson** [comment]
No, you will not.

**Comment by mr-mystery** [comment]
Thanks for your help.
