### ISSUE TITLE
Current MixedRealityToolkit HoloLens compatibility status with Unity 2017.3 Beta?

### ISSUE THREAD

**Issue by atouchet** [Microsoft/MixedRealityToolkit-Unity#1313]
Hello,

I am using an older version of the MixedRealityToolkit with HoloLens but was interested in updating my project to the Unity 2017.3 beta. Looking at the releases page it says HoloLens users should stay on 2017.1.2. Has anything changed since that release and is it at all possible currently to get the MixedRealityToolkit for HoloLens working with the Unity 2017.3 beta?

**Comment by StephenHodgson** [comment]
The project only targets release versions of Unity (unless there's a big change to Windows Mixed Reality).  If you need to support the beta, you're more than welcome to post your findings here.

**Comment by atouchet** [comment]
Alright, I will probably end up waiting for the official release as opposed to using the beta.
