### ISSUE TITLE
Mixing 2D with 3D

### ISSUE THREAD

**Issue by EduardsBrown** [Microsoft/MixedRealityToolkit-Unity#1317]
I built an app that has some 2D XAML elements and I can switch from that to a full 3D view. I've researched and all the sources seem to say it is not possible to mix 2D windows and 3D objects. I guess what I am trying to ask is, if there is a way that I could achieve this, or is there a plan to implement something like this in the future?

I am going of the Holograms app on HoloLens which does this, so my instinct tells me that there must be a way.

**Comment by eluchsinger** [comment]
Is it possible that the [ApplicationViewManager](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/ApplicationViewManager.cs) class is what you're looking for? The XML Documentation is not so good, but I can imagine it has something to do with that.

**Comment by NeerajW** [comment]
Please reopen in case your question did not get resolved.
