### ISSUE TITLE
UAudioMiniManager doesn't compile with 11-08 pull

### ISSUE THREAD

**Issue by erichfrazer** [Microsoft/MixedRealityToolkit-Unity#1320]
UAudioMiniManager.cs(11,46,11,79): error CS0305: Using the generic type 'UAudioManagerBase<TEvent, TBank>' requires 2 type arguments

today's pull-down.

**Comment by erichfrazer** [comment]
never mind. it's because these files were removed from the latest toolkit, but WERE in the old one, and the whole idea of re-importing a HoloToolkit isn't very well thought out right now. There is no (easy) way of knowing when a file should be removed when you import the latest toolkit.

**Comment by keveleigh** [comment]
The [latest release](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/v1.2017.2.0) specifies:
> When upgrading to this release, delete all toolkit folders before importing the package.

I agree that some sort of upgrade path would be better though.

**Comment by StephenHodgson** [comment]
If you're using git, the files will clean themselves up automatically, but unity doesn't handle this type of thing properly in their asset packages

**Comment by StephenHodgson** [comment]
@erichfazer can we close that.

**Comment by erichfrazer** [comment]
Yep. Sorry.

**Comment by erichfrazer** [comment]
I am using Git to GET the MRTK, but I don’t know the secret sauce to get the MRTK inside of my unity project and have Git deal with two projects in the same tree. I know submodules exist, but I’m not quite sure how that works. I’m thinking of adding a soft-link on the hard drive to point to the holo toolkit…

**Comment by erichfrazer** [comment]
I don’t understand “deleting folders before importing” because Unity’s meta-files bother/worry me. Suppose I’m using the MixedRealityCameraParent in my scene. My unity project is referencing the camera via it’s meta-file, right? Now, I go and delete the HoloToolkit folder. (I admit I haven’t tried this yet). Won’t my camera disappear in my project? Or be broken? If I immediately go and re-import the toolkit, will Unity find and fix my broken links, or will they all be busted? I should go try this and see what happens instead of guessing at it.

**Comment by StephenHodgson** [comment]
The camera itself will exist but the components will have missing references.

The meta files are the key to keeping these references and is what's important when keeping source controlled projects well maintained.
