### ISSUE TITLE
How to quickly add all the input settings to Edit/Project Settings/Input?

### ISSUE THREAD

**Issue by erichfrazer** [Microsoft/MixedRealityToolkit-Unity#1321]
MRTK requires these settings for proper running, but is there a quick-n-dirty way to get these settings into the Axes? Does Menu/Mixed Reality Toolkit/Configure/(something) automagically enter these, or do I need to type them all myself?

**Comment by eirikholhjem** [comment]
The "[GettingStarted.md](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/GettingStarted.md)" explains this great.

Look especially at point 4 and 5.

**Comment by keveleigh** [comment]
This was fixed by #1126, under Mixed Reality Toolkit/Configure/Apply Mixed Reality Project Settings
