### ISSUE TITLE
The cursor does not move with the motion controller

### ISSUE THREAD

**Issue by kameware** [Microsoft/MixedRealityToolkit-Unity#1322]
If you move the sample, the motion controller buttons move but the tracking may not move.
Is this a bug?

**Comment by kameware** [comment]
I feel that it happens often when using only one hand and using it.

**Comment by StephenHodgson** [comment]
It works just like the Shell, where you need to get the cursor focus before the cursor will follow the controller.  You can do this by pulling the trigger two times (Just like in the cliff house)

**Comment by kameware** [comment]
Can I pull the trigger two times after launching the application?
In that state
"Can I pull the trigger twice after launching the application?" Nor "nputTracking.GetLocalRotation (XRNode.RightHand)" can not be acquired either.

**Comment by kameware** [comment]
When that phenomenon happens, whichever button you press will react, but you can not get only position and rotation.
Restart the PC to fix it.

**Comment by StephenHodgson** [comment]
Try turning the controllers on and off again.

**Comment by NeerajW** [comment]
Please reopen with any other specific issues you might have. Original issue seems to be by design.
