### ISSUE TITLE
Merge Buttons

### ISSUE THREAD

**Issue by brean** [Microsoft/MixedRealityToolkit-Unity#1323]
In the Examples-folder we have buttons in UX/Prefabs and Prototyping/Prefabs, I think that the protoyping can use the same prefabs from UX. There are also buttons based on the MRDesignLab-Code in Holotoolkit/UX/Prefab/Buttons (also I am looking for some tutorial/examples how to use those button-prefabs).

**Comment by cre8ivepark** [comment]
@brean Have you tried the test scene InteractableObjectExamples.unity under https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit-Examples/UX/Scenes ?

Readme for InteractableObjectExample scene:
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX/Readme/README_InteractableObjectExample.md

UX Examples Index Page:
https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit-Examples/UX

**Comment by brean** [comment]
@cre8ivepark yes, I have checked the InteractableObjectExamples scene. The prefabs for the buttons there are in the folder
https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit-Examples/UX/Prefabs and there is documentation for it (you linked to it).

But there are also buttons in https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit-Examples/Prototyping/Prefabs 

And there are buttons in the main toolkit folder: https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit/UX/Prefabs/Buttons where I do not see any documentation.

I think it is redundant to have 3 different places for buttons, so I suggest to merge those all together and have one standard way to do basic buttons for hololens.

**Comment by brean** [comment]
Maybe @paseb  can tell us a bit about those buttons: Where are they used? How can I use them? Does it make sense to merge?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
