### ISSUE TITLE
SceneContentAdjuster doesn't work on device

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#1324]
`SceneContentAdjuster` only seems to work in Play mode. When I build and deploy to an immersive HMD, the object stays at the preset height.

`SceneContentAdjuster` also overwrites the X and Z values (to 0) instead of just the height, which doesn't seem ideal.

**Comment by StephenHodgson** [comment]
The x and z values should be zero.  The Scene Contents Adjuster `GameObject` was designed to be placed at the scene origin (0, 0, 0).  The adjuster only should adjust the height of the scene without moving the objects position on x and z.  

Maybe the latest MRTP 4 update changes the way we're getting the height.  Which is strange though, because the MixedRealityCameraParent is using very similar logic.

**Comment by keveleigh** [comment]
> The x and z values should be zero. 

> The adjuster only should adjust the height of the scene without moving the objects position on x and z.

These two sentences seem contradictory. Am I misreading? The second statement seems to say that the adjuster shouldn't touch my preset X and Z values, which is what I'd expect. If I've already placed something at Z = -2 in order to put it in front of the user, I only want the Y value changed depending on which device I'm on. In this case, that gets reset to 0.

**Comment by StephenHodgson** [comment]
In Unity Y is up, not Z.

If you want your objects to be at -2 then you should make it a child of the Game object that the scene content adjuster is attached to.

**Comment by keveleigh** [comment]
I'm aware of the coordinate system :)

I said "in front of", which is Z.

If that's how this script should be used, check your use in the InputManagerTest scene. It is incorrectly used there and overwrites preset values.

I don't think there should be a requirement for me to wrap my content in a parent object. Y should be the only value touched, because we only care about height here. Don't overwrite X or Z.

**Comment by StephenHodgson** [comment]
Okay, I'll update it to only adjust the Y values.

**Comment by keveleigh** [comment]
The more I look at `SceneContentAdjuster`, to more I'm not sure I understand how it works. It looks like it "worked" in the Editor because that was [special cased in `Awake`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/c31425e23595832cb90261f7c1588e8863d06195/Assets/HoloToolkit/Boundary/Scripts/SceneContentAdjuster.cs#L18) to be 1 meter high.

On device, the `Update` loop was putting it at (0, 0, 0), due to [a bug in `TryGetDimensions`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/c31425e23595832cb90261f7c1588e8863d06195/Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs#L141).

What we should be getting is the offset between the floor and the head at app launch, right?

Off-topic, but I don't think we're using `TryGetDimensions` right there even without the Unity bug. It looks like it gives us the bounds dimensions, which means the Y value would be the height of the bounds itself, not the Y value of the floor.

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
