### ISSUE TITLE
Confusing text around Current supported versions

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#1325]
Maybe this is just a formatting issue, but it feels like there is unnecessary confusion in the text on this page. I am assuming that "Mixed Reality" is the blanket term, and includes both "Windows Mixed Reality" headsets and HoloLens.

    Note: The latest release should work for both HoloLens and Windows Mixed Reality development.
    Latest Master Branch Release v1.2017.2.0
    Current Unity Editor Version 2017.2.0p1 MRTP4

    Check out the updates from the Fall Creators update for Windows Mixed Reality

        HoloLens Developers
        Currently we are waiting on a fix for HoloLens development from Unity, for now you should use the 2017.1.2 version of Unity and the "Release" version of the MRTK Asset:
         Unity Editor HoloLens Version 2017.1.2f1

If the Unity editor version is still different for WMR Headsets, then I think you need another section to call this out (and if it is not then I'm even more confused!):

    All MR Developers (both Windows Mixed Reality and HoloLens)     
    Note: The latest release should work for both HoloLens and Windows Mixed Reality development.
    Latest MR Toolkit Master Branch Release v1.2017.2.0

    Windows Mixed Reality Developers
    Current Unity Editor Version 2017.2.0p1 MRTP4

    HoloLens Developers
    Unity Editor HoloLens Version 2017.1.2f1

Then the text on this page: https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/v1.2017.2.0  still links to the Unity MRTP3 version, rather than the MRTP4 version linked on the previous page.

**Comment by StephenHodgson** [comment]
After the next release any version of unity can be used.

**Comment by genereddick** [comment]
Is there a target date for that?

**Comment by StephenHodgson** [comment]
As soon as the API checker pr gets committed.

I also want to hold off on a release until we've updated the multiple pointer PR as well.

**Comment by StephenHodgson** [comment]
I'll be sure to update the editor version links in the release.
