### ISSUE TITLE
Flickering jagged edges for objects in opaque device

### ISSUE THREAD

**Issue by raedbenz** [Microsoft/MixedRealityToolkit-Unity#1327]
Hello,

I am using Unity 2017.2.0f3 MRTP to build my app that runs on Lenovo Explorer HMD. The issue is that on every object we get the effect of flicker and jagged edges. I am running with opaque display settings Ultra.
I then tried the toolkit examples scenes e.g. GrabMechanics, and applied the Mixed Reality Toolkit project & scene settings to it, and still getting the same issue. Also noticed the further u get the more obvious the jagged edges become.
I did a bit of googling and in unity forums they suggest filckering jagged edges is due to small value of near clipping. recommended is about 0.3.
However, the near clipping value that can be set from inspector on the MixedRealityCameraManager script, it keeps showing 0.1 although in script code is 0.3 for opaque devices. Moreover it seems at run time the value also is 0.1 (i am printing the value of CameraCache.Main.nearClipPlane).
Also tried different values for anti aliasing with no luck.
The villa in the portal runs fine.

Can anyone one point me to a sample code that you know it works fine, so I can test it, maybe is something with my dev environment.

Any suggestions please?
Thanks

**Comment by raedbenz** [comment]
Tried it with MRTP4 and 842c4a1 commit. still same issue..please advice urgently.

**Comment by StephenHodgson** [comment]
Please provide a screenshot of the behavior.

You can update the clipping plane on the MixedRealityCameraParent.

Also please provide definitive steps to reproduce.  This could either be an issue with your graphics card or environment setup.

**Comment by raedbenz** [comment]
Hi, as i said in my first post, i am trying to change clipping plane other than 0.1 but at run time is still 0.1.
the villa house of the MR portal looks fine.
What is the best way to take a screenshot while app running ?

**Comment by StephenHodgson** [comment]
Also, there was an issue with the editor not serializing the correct info when choosing the clipping plane for occluded devices but was fixed in #1259

**Comment by raedbenz** [comment]
It seems to me the issue #1259 is still reproducible. 
Thanks

**Comment by StephenHodgson** [comment]
I can assure you #1259 is most definitely fixed.
Serialization is updated when applying changes to the prefab.

![image](https://user-images.githubusercontent.com/13334553/32681567-0d5b237c-c625-11e7-88cc-7afb3539f08d.png)

**Comment by StephenHodgson** [comment]
I suggest posting this question in the [Windows Mixed Reality Forum](https://forum.unity.com/forums/windows-mixed-reality.102/) to see if the Unity engineers have any advice.  I'm thinking this could be an issue with the latest MRTP release but I'm unsure. I don't have the same issues here on my end.  A screenshot of your issue would def help to know what I'm looking for.

**Comment by raedbenz** [comment]
Ok I 'll post it there as well.
The near clipping value is a very strange issue. 
As I mentioned in my first post. When I go to MixedRealityCamera the value shown is 0.1, although if I open the script it says 0.3. Then when I run the app and print CameraCache.Main.nearClipPlane the value is 0.1. The issue I am facing is when running on device not play mode, that's why I asked how to get screenshot at runtime. 
Thanks

**Comment by StephenHodgson** [comment]
Yeah that's definitely a separate issue.  Can you open one specifically for that please?

**Comment by StephenHodgson** [comment]
As for a screenshot you should be able to mirror the mixed reality portal and get something with the shipping tool.

**Comment by raedbenz** [comment]
Here is a bunch of screenshots. Here you can see jagged edges, in video you can see also the flicker of jagged edges. [To download video and sample app click here](https://1drv.ms/u/s!AqyK7GAlUddCiaRDlzU8keYbb3gVJA).
![villa2-portal](https://user-images.githubusercontent.com/15609404/32688342-f870c942-c6c6-11e7-9429-8a2bf478a4f9.png)
![nc0 1-portal-aa4x](https://user-images.githubusercontent.com/15609404/32688343-f8891056-c6c6-11e7-8672-bec55eb6e84c.png)
![nc0 3-portal-aa8x](https://user-images.githubusercontent.com/15609404/32688344-f8a02ac0-c6c6-11e7-89b6-0785c819c87e.png)
![nc0 3-unity-noaa](https://user-images.githubusercontent.com/15609404/32688345-f8b99672-c6c6-11e7-85be-f4436ce1e4dc.png)
![nearclippin0 3-portal-noantialiasing](https://user-images.githubusercontent.com/15609404/32688346-f8d8dc94-c6c6-11e7-9b41-56f272dc23a7.png)

**Comment by raedbenz** [comment]
Posted in unity forum
https://forum.unity.com/threads/flickering-jagged-edges-for-objects-in-immersive-mixed-reality.504067/

**Comment by markgrossnickle** [comment]
@raedbenz Your solution at the bottom of this thread worked perfectly for me: https://forum.unity.com/threads/flickering-jagged-edges-for-objects-in-immersive-mixed-reality.504067/

I didn't realize there was a MSAA property on Unity Cameras and could not figure out why anti-aliasing was not working for me. Also the XRDevice eyeTextureResolutionScale was helpful as well in regards to textures and sprites.  

I think we should add both MSAA and eyeTextureResolutionScale to MixedRealityCameraManager.  Enabling MSAA by default for Opaque as well as eyeTextureResolutionScale to 2.0.  My only hesitation is that instead of people coming here and trying to figure out why they are getting jagged edges we may get people coming and trying to figure out why they have low FPS.

**Comment by jackrohit001** [comment]
Hi all
@raedbenz  I am also facing same problem, But when i checked MSAA it resolved my problem but main problem is in .appx file, When i am playing same Game in mixed reality portal it is showing Jagginess :(
Please help

**Comment by raedbenz** [comment]
When you say it resolved the problem, where did you check that, is it inside unity game window?
it is also worth check your graphic card settings, for instance in NVidia control panel you can allow each app to take control of antialiasing behavior.
Have you tried creating a test app and print out the msaa & eyeTextureResolutionScale  values?
