### ISSUE TITLE
Clarify community contribution guidelines, licensing

### ISSUE THREAD

**Issue by riverar** [Microsoft/MixedRealityToolkit-Unity#133]
Spun off from a discussion in #130, we need to solidify some rules around community contributions as the project becomes more popular. (Probably need to route through Microsoft LCA.)

The [Microsoft CLA](https://cla.microsoft.com/cladoc/microsoft-contribution-license-agreement.pdf) specifically calls out that contributors maintain submission rights.

Some questions:
- What do externals put in the code file header? e.g. Copyright (c) <author>
- What do internals put in the code file header?
- What do moonlighting internals put in the code file header?
- Do we also need to maintain a CONTRIBUTORS.md?
- [Your question here]

**Comment by jwittner** [comment]
Given that we have a Contributing and there are more explicit questions on this general one I'm closing this.
