### ISSUE TITLE
Can't import HoloToolKit into the latest version of Unity 2017.2.0f3? How to import properly? 

### ISSUE THREAD

**Issue by tezelia** [Microsoft/MixedRealityToolkit-Unity#1330]
Hey guys,

Just recently began developing mixed reality applications with Unity for the HoloLens. 

Initially, I began developing the application in Unity 5.4.0f1 HTP version which successfuly built a Visual Studio file, but then realized for more fuctionalities and interaction such as voice recognition, I would need the HoolToolKit for Unity. 

Tutorials on how to successfuly import the holotoolkit aren't that common but still I have honestly followed every tutorial but still get errors. 

Regarding the latest version of Unity, or at least 2017.2.1, how do I successfuly import the holotoolkit? For now I keep getting errors 
```
#Unsupported DDS file.
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEditor.DockArea:OnGUI()

#Removing Assets/HoloToolkit/UX/Resources/Models/Cursor/Cursor_move/CursorRing.fbm/templates because the asset does not exist
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEditor.DockArea:OnGUI()
```
Note: These errors can be removed after clearing the console. Should I ignore these?

Once I download the mixedrealitytoolkit-unity folder from github. Which folders and files do I drag and drop into the assets folder? Do I drag and drop the entire folder? Do I then rebuild, repackage, etc what shall I do, please help :( 

Kind Regards,

**Comment by tezelia** [comment]
Or I would get these switch type errors

#Switching to Windows Store Apps:MetroSupport is disabled

Please help :(

**Comment by samharper94** [comment]
Have you got the Metro support installed for Unity?

**Comment by tezelia** [comment]
Hey, please ignore the comment above (I'll delete it now). Just realized on one version of Unity it wasn't installed but now I'm on the version or the latest version which has it installed, but still no luck :(

**Comment by samharper94** [comment]
Once you get the git repository, only copy the folders over you actually want. I only take Assets\HoloToolKit, HoloToolKit.Meta and the mcs files.

**Comment by eirikhollis** [comment]
I take a different approach, but still commonly used (I think?). Download the masterbranch/latest release and unzip it to a new folder. Start a new unity project and import everything inside the "Assets" folder of the unzipped folder to your project. Then click on one of the folders and choose "Export Package...".

You are now creating a .unitypackage file. Save it somewhere and import it into your existing project using "Assets -> Import Package -> Custom Package". Should work after that.

**Comment by tezelia** [comment]
I tried both but still not wroking

when I go into build window I get this error :(

Failed to locate internal switch adapter
UnityEngine.Debug:LogError(Object)
HoloToolkit.Unity.XdeGuestLocator:<FindGuestAddressAsync>m__0(Object) (at Assets/HoloToolkit/BuildAndDeploy/Editor/XdeGuestLocator.cs:64)

when I try to build from build settings I get these errors as well.... :(

#Assets\HoloToolkit\Input\Scripts\Utilities\Extensions\InteractionSourceExtensions.cs(12,23): error CS0234: The type or namespace name 'Haptics' does not exist in the namespace 'Windows.Devices' (are you missing an assembly reference?)

#Failed to locate internal switch adapter
UnityEngine.Debug:LogError(Object)
HoloToolkit.Unity.XdeGuestLocator:<FindGuestAddressAsync>m__0(Object) (at Assets/HoloToolkit/BuildAndDeploy/Editor/XdeGuestLocator.cs:64)

**Comment by eirikhollis** [comment]
Try closing Unity and Visual Studio and deleting (create a backup first) the two "Visual C# Project file" in the root directory of your project. 

Also, look into "[GettingStarted](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/GettingStarted.md)" to see if you missed something.

**Comment by samharper94** [comment]
Ah the Haptics error, are you using a HoloLens?

**Comment by tezelia** [comment]
My windows 10 version is 1703 (OS Build 15063.674)

I am guessing this is why I am getting the errors? 

Am I supposed to update to version 1709 (OS Build 16299)

But my laptop is not informing me that I need any updates, etc which link do I need for this update, jsut searching on Google now

**Comment by samharper94** [comment]
If you're using a HoloLens you need to use Unity 2017.1.2, #1143 explains why.

**Comment by StephenHodgson** [comment]
Also be sure to look at the [Upgrade Guide] (https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/UpgradeGuide.md)

**Comment by xaviercrespin** [comment]
I have the exact same problem, i can't use the build window, and the same errors : 
#Failed to locate internal switch adapter

Is it because at some point i have installed unity 2017.2? Even after uninstalling 2017.2 and installing 2017.1.2f1 , i can't get MRTK to import successfully without errors, even on a new, empty project

**Comment by StephenHodgson** [comment]
> Failed to locate internal switch adapter

This error message has no impact on your ability to build

**Comment by xaviercrespin** [comment]
I'm completely lost here, i uninstalled everything from unity to VS, reinstalled even the simplest app with just a simple 3D object won't even work on the device now, can you please clarify one thing : 
Are we supposed to use the MRTK 2017.2.0 with unity 2017.1.2f1 ?
Or the MRTK 2017.1.2 with unity 2017.1.2f1 ?

**Comment by StephenHodgson** [comment]
The latest release can be used with with either Unity Editor.
Depending on your platform target:

![image](https://user-images.githubusercontent.com/13334553/32705068-9be000f4-c7c4-11e7-91e0-a5a1ebeff8d9.png)

**Comment by xaviercrespin** [comment]
For the import problem and errors in the console, i found a fix by NOT creating the package from source, but downloading directly the .unitypackage available [on the release page](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/v1.2017.2.0) , and importing the custom package directly in my project. Works like a charm.

**Comment by asanint** [comment]
@StephenHodgson, do you know where the "Failed to locate internal switch adapter" error means? it seems to be triggered by the build window.

**Comment by StephenHodgson** [comment]
It's the build window trying to access the wifi adapter and failing. It's just not implemented.

**Comment by tezelia** [comment]
It works now guys, thanks, I downloaded the 1.2 version as instructed then copy pasted these files directly into the assets of my project

- HoloToolKit
- HoloToolKit.meta
- mcs.rsp
- mcs.rsp.meta

Works fine now :)

**Comment by NeerajW** [comment]
Please reopen if you still have issues.
