### ISSUE TITLE
You can now use one version of Unity for all Windows Mixed Reality Devices

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1335]
HoloLens and IMHD devs can now use any version of Unity for production (So long as it supports Windows Mixed Reality) on the latest master branch checkout 842c4a10869ef5b4bb2ace5c7139210fc82f60d1

Couple of notes:
- you _**must**_ use Unity Editor 2017.2.0p1 MRTP 4
    - Keep in mind that the [editor will crash if you play in editor without a IMHD](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1008).
- You _**must**_ have the latest Windows SDK (10.16299.0) installed, and the MRTK build window will now always default to using it.
    - We now use Windows SDK API Contracts to check to make sure the device the app is installed on can call/use the API we're attempting to use, and will now compile correctly.
- The latest releases still require specific unity versions and SDK targets. **Follow all instructions there.**

**Comment by raedbenz** [comment]
Hi. No link for instructions

**Comment by raedbenz** [comment]
Does this mean i can use Unity Editor 2017.2.0p1 MRTP 4 with MixedRealityToolkit-Unity for Unity 2017.2.0? or do i have to create my own packages from latest code in master branch ?

**Comment by StephenHodgson** [comment]
You'll need to create your own package from the latest sha I posted above.  I specifically said:

>The latest releases still require specific unity versions and sdk targets. Follow all instructions there.

**Comment by LocalJoost** [comment]
For now I would very much recommend  MRTP4 for immersive apps as apps generated with previous versions tend to have 'double vision' sometimes for objects close by. Particularly controllers ;)

**Comment by genereddick** [comment]
Does it matter which version of Unity you use, 2017.2.n or 2017.2.n-MRTP4, if you are targeting HoloLens? Is MRTP4 meant only / primarily for Windows headsets?

**Comment by StephenHodgson** [comment]
Well, considering the HoloLens is a Windows headset, it should be okay ;)

Yeah the build I made the other day works for both IHMDs and HoloLens with the 2017.2.0p1-MTRP4 unity editor.

**Comment by raedbenz** [comment]
Where can I keep track of latest unity MRTP releases?
Thanx

**Comment by StephenHodgson** [comment]
Unfortunately Unity has decided to hide them away in some forum post.

The [latest Unity MRTP builds](https://forum.unity.com/threads/custom-build-2017-2-rc-mrtp-windows-mixed-reality-technical-preview.498253/) appear here in descending order.

**Comment by raedbenz** [comment]
Any luck with creating new release package? I tried creating it myself but when deleting old one from my project and importing new one, build process freezes 100% CPU. I get 8 instances of UnityShaderCompiler.exe hogging cpu.

**Comment by StephenHodgson** [comment]
No, the master branch is too unstable at the moment to make a release.

**Comment by LocalJoost** [comment]
Well that is interesting. What AM I supposed to use then when I make new version? I usually just pull the master branch ;)

**Comment by StephenHodgson** [comment]
Lol yeah, I do too.

That's why I usually try to get fixes in asap.
I'm using the toolkit as a submodule in my projects.

The nice thing about submodules is that you get to choose the checkout Sha you wanna use. Plus it's easier to roll back if something bad happen.

**Comment by jasonhbartlett** [comment]
Quick question: If the HL is running 10.14393 but I can only target to build to 10.16299 when using the above specified versions of Unity and MRTK, am I going to still be able to deploy to HL?  Will this throw all kinds of errors due to namespace problems between VR and XR, etc?

**Comment by StephenHodgson** [comment]
@jasonhbartlett  Yes, you're locked into using either the 15063 or 16299 SDK (Based on the Unity Editor version you're using).  We have a Windows API checker that makes sure the API compatibility works.

**Comment by shllybkwrm** [comment]
"Keep in mind that the editor will crash if you play in editor without a IMHD."
What does this mean if you're only developing for HL?  I rely on the editor to test small changes very frequently...

**Comment by StephenHodgson** [comment]
It means you should keep to the main Unity Releases and to not use the MRTP builds.
