### ISSUE TITLE
Should InputManager prefab or Managers prefab be loaded from Configure

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#1341]
## Overview
In the Editor | Mixed Reality Toolkit | Configure | Scene Settings menus, you can automatically install the InputManager prefab. However, in the documentation here https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/GettingStarted.md, it tells you to load the Managers prefab which includes the InputManager and Event System.

    Add the Managers.prefab (found under HoloToolkit/Input/Prefabs/Cursor), which will add a new Managers folder containing the InputManager Prefab and the all-important UI EventSystem object.

Is there a reason these are not aligned? Should the Configure menu now load the Managers prefab instead?

**Comment by keveleigh** [comment]
Interestingly, I think somebody added an EventSystem to the InputManager prefab itself, now making the Managers prefab obsolete. This should definitely be reconciled.

**Comment by StephenHodgson** [comment]
I'll be sure to update the documentation as part of #1336

**Comment by StephenHodgson** [comment]
Unsure how this manager prefab made it into the project.

We should avoid nested prefabs or assets that have duplicate functionality.
