### ISSUE TITLE
Update Mouse Support to reflect the Shell (Cliffhouse) inputs

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#1342]
## Overview
Using latest Unity & MRTP editions, even when I do not have "Target Occluded Devices" set in the Configure menu, attempting to Run from the Unity Editor opens the app in a connected Windows Headset or simulator, adds a floor plane, doesn't work with the mouse and other issues.

Maybe I'm missing a configuration setting or the expected behavior has changed?

## Expected Behavior
Unless targeting occluded devices, run should not create a floor plane, should preserve the correct placement of the camera (at head level, not floor level), should use the correct camera background, should continue to work with the mouse.

## Actual Behavior
Opens in connected Headset. Sets camera initial position incorrectly (positioned for Windows, not HoloLens). Inserts floor plane into scene. Can't use mouse.

## Unity Editor Version
Unity 2017.2.0p1-MRTP4, but happens in others

## Mixed Reality Toolkit Release Version
HoloTookit-Unity-v1.2017.2.0
also current Master

**Comment by StephenHodgson** [comment]
I don't believe we have proper mouse support that's like in the cliff house yet, but I believe a lot of the preliminary stuff is getting imported with the MRDL merges.

**Comment by genereddick** [comment]
When you click run from within the Unity Editor, how does it determine whether to run in Transparent vs Opaque mode? I had expected, perhaps incorrectly, that setting the checkbox in the Configure Menu for "Target Occluded Devices" would control this -- but it is not clear which settings this effects?

Specifically, on my system I have an HMD. The "Target Occluded Devices" is unchecked and my intention is the deploy to HoloLens, but I want to test within the editor on my PC without deploying. However, when I run within the Unity editor, sometimes it launches the MR Portal, sometimes not, but in every case I get the opaque configuration with the camera and floor misplaced, etc.

**Comment by StephenHodgson** [comment]
I agree, having better support overall for this of switching would be ideal.

Although in my opinion, I think being able to test specific features out with the HMD would effectively be easier to do instead of pushing to the HoloLens each time.  I have a feeling that a lot of apps will be cross platform compatible in this way.

As far as when the mixed reality portal launches, the only deciding factor there is if you have XR enabled or not.

**Comment by StephenHodgson** [comment]
The option for targeting occluded devices is somewhat depricated. 

It used to handle updating the VR/XR SDK target and device target, but that's been deprecated in Unity and it all uses "Windows Mixed Reality" as a single target for all headsets.

The second thing it does is enable/disable the HID capability for HoloLens when using the Xbox controller.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
