### ISSUE TITLE
Clicking buttons on both controllers Crashes Unity

### ISSUE THREAD

**Issue by DDReaper** [Microsoft/MixedRealityToolkit-Unity#1344]
## Overview
When using the MRTK (confirmed it's no an issue if done manually) using the button on one or the other controller is fine.
However, if you click any button on either controller at the same time (doesn't have to be the same button), Unity crashes.

## Expected Behavior
Unity shouldn't crash :D and you should be able to use both controllers buttons simultaneously 

## Actual Behavior
Unity crashes when buttons on both controllers are used at the same time.

## Steps to reproduce
Using either the MRTK or the example scenes
1: Open scen
2: Add scene defaults
3: Run Scene
4: Click buttons at the same time on both controllers

## Unity Editor Version
MRTP4

## Mixed Reality Toolkit Release Version
Master

**Comment by StephenHodgson** [comment]
I wonder if this is a crash caused by the `InteractionManager`?

@DDReaper can you PM me the crash report?

**Comment by DDReaper** [comment]
I doubt it's the interaction manager, as I'm using that in other projects without issue, but happy to be proved wrong.
I'll try and get it tomorrow, however, you should be able to easily recreate the crash yourself

**Comment by StephenHodgson** [comment]
Yeah, I'll def try to get the crash report when I get in tomorrow.

**Comment by keveleigh** [comment]
I looked into this _very_ briefly yesterday and saw a message about a nullable object not having a value. I have a feeling this is somewhere in the Toolkit's `InputManager`.

**Comment by StephenHodgson** [comment]
Here's the error from the editor just before the crash:

```

Assertion failed
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Assert(Boolean)
HoloToolkit.Unity.InputModule.FocusManager:GetPointer(IPointingSource) (at Assets\HoloToolkit\Input\Scripts\Focus\FocusManager.cs:789)
HoloToolkit.Unity.InputModule.FocusManager:GetSpecificPointerEventData(IPointingSource) (at Assets\HoloToolkit\Input\Scripts\Focus\FocusManager.cs:441)
HoloToolkit.Unity.InputModule.InputManager:RaiseSourceUp(IInputSource, UInt32, InteractionSourcePressInfo, Object[]) (at Assets\HoloToolkit\Input\Scripts\Utilities\Managers\InputManager.cs:430)
HoloToolkit.Unity.InputModule.InteractionInputSource:InteractionManager_InteractionSourceReleased(InteractionSourceReleasedEventArgs) (at Assets\HoloToolkit\Input\Scripts\InputSources\InteractionInputSource.cs:919)
UnityEngine.XR.WSA.Input.InteractionManager:OnSourceEvent(EventType, InteractionSourceState, InteractionSourcePressType) (at C:\buildslave\unity\build\Runtime\VR\HoloLens\ScriptBindings\GestureSource.cs:481)
 
(Filename: Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs Line: 789)
```

**Comment by StephenHodgson** [comment]
I noticed that these errors also get raised after pressing any button by itself as well.

**Comment by DDReaper** [comment]
Glad you managed to find the source :D

**Comment by StephenHodgson** [comment]
I think it's definitely because we're switching pointers and the pointer index is briefly empty.

**Comment by DDReaper** [comment]
I was curious about that behaviour. Is there any reason the pointers cannot be handled independently, why does it need a "Master", why not both (or all, including Gaze)?

**Comment by StephenHodgson** [comment]
Yeah, I'm trying to figure out why we're even unregistering the pointer when we switch.
Cause that's really what the problem is.

**Comment by StephenHodgson** [comment]
I got a fix

**Comment by RICKASHEYE** [comment]
this is pretty much what happened

**Comment by RICKASHEYE** [comment]
that is the problem I tried it and it crashed

**Comment by Abstiens** [comment]
I am not sure if my problem is related to this one.

For me, the crash happens, after i release the Trigger on the backside of the controller (no message, Unity just disappears). Nothing happens, while i click and hold the trigger. 
If i pause Unity while i hold the trigger and then release it, it crashes immediatly after i resume.

I am using MRTP4 and the latest master branch. I also tried Pull Request #1350 (applied as patch), but same result.

**Comment by StephenHodgson** [comment]
Probably related in some way, but I'd still like you to open a separate issue for this detailing your repro steps please.

**Comment by Abstiens** [comment]
Wow, you are really fast. Thank you in advance!
#1363
