### ISSUE TITLE
Null refernence errors when running a scene

### ISSUE THREAD

**Issue by DDReaper** [Microsoft/MixedRealityToolkit-Unity#1346]
## Overview
When starting a scene, the following error spams the console window:
```
NullReferenceException: Object reference not set to an instance of an object
HoloToolkit.Unity.InputModule.FocusManager.RaycastUnityUI (HoloToolkit.Unity.InputModule.PointerData pointer, UnityEngine.LayerMask[] prioritizedLayerMasks) (at Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs:616)
HoloToolkit.Unity.InputModule.FocusManager.UpdatePointer (HoloToolkit.Unity.InputModule.PointerData pointer) (at Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs:523)
HoloToolkit.Unity.InputModule.FocusManager.UpdatePointers () (at Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs:466)
HoloToolkit.Unity.InputModule.FocusManager.Update () (at Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs:74)
```

## Expected Behavior
No error messages when starting a scene.

## Actual Behavior
Console Window is filled with above error.

## Steps to reproduce
1: start new project
2: Apply MR project settings
3: Apply MR scene settings
4: Run scene

## Unity Editor Version
MRTP 4

## Mixed Reality Toolkit Release Version
MASTER

**Comment by StephenHodgson** [comment]
When the scene starts, does everything still run correctly with uGUI input?

This may be a race condition where we have not yet set the `RaycastCamera` before starting to process our pointers.

**Comment by edsilv** [comment]
I'm seeing the same issue. Sorry, not sure what you mean regarding uGUI input. 
I tried setting breakpoints in the `Awake` and `Start` methods of `FocusManager`, but they aren't getting hit before the error in `Update` is thrown. Could `Update` somehow be getting called before things have had a chance to initialise?

**Comment by StephenHodgson** [comment]
@DDReaper , @edsilv  can you confirm which prefabs you're using in your scene?

Are you suing the `Managers.prefab` or the `InputManager.prefab`?

**Comment by edsilv** [comment]
I'm using the InputManager (Mixed Reality Toolkit > Configure > Apply Mixed Reality Scene Settings)

![scene](https://user-images.githubusercontent.com/1334393/32701323-433068e8-c7cb-11e7-95e0-99782f3d1169.png)

**Comment by StephenHodgson** [comment]
After looking into this a bit more, I'm actually surprised we don't see [this assertion](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs#L597) fail before we get [the null reference](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs#L616).

**Comment by StephenHodgson** [comment]
Oh I see, our `uiRaycastResult` is not returning the correct data.
