### ISSUE TITLE
During serialization or importing the UX assets, new unsupported assets created.

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1347]
## Overview
When importing/ serializing the project assets are usually re-imported by Unity.  During this process unsupported files are generated during import. 

## Expected Behavior
No, new assets generated during import/serialization

## Actual Behavior
Created new assets:
![image](https://user-images.githubusercontent.com/13334553/32700893-79ddc8cc-c780-11e7-9698-1597e8f5e861.png)

## Steps to reproduce
1. If you already have a copy of the master branch on your machine, delete the temp/library folders in the project root.
2. Open MRTK Project
3. Open any git client and view unstaged changes.  New files should appear here.

## Suggested Steps to Fix
Open `hololens_low.fbx` in a 3d modelling program (probably Maya or 3D Studio Max) and remove the referenced PlasticMaterial, normal, and white assets that are embedded in the file itself.

## Unity Editor Version
Any/All

## Mixed Reality Toolkit Release Version
Latest master branch 29ff159d6dee3a6ca6343c7fc305b26a51030488

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
