### ISSUE TITLE
3D objects not rendered, apparently here, but "black"

### ISSUE THREAD

**Issue by xaviercrespin** [Microsoft/MixedRealityToolkit-Unity#1352]
## Overview
Cannot see the objects although they seem to be here, 
it was working with the same setup a few days ago
## Expected Behavior
Show the 3D objects as holograms
## Actual Behavior
3D objects are not rendered in either the Hololens, or the Hololens emulator.
The cursor disappears when it meets an object that is supposedly here, like a 3D cube, but the object is not appearing, the display is fully black apart from the white cursor.
## Steps to reproduce
Open Unity 2017.2.0f3
Create new, empty project
Import HoloToolkit-Unity-v1.2017.2.0.unitypackage as a custom package
Apply Scene and project settings
Add cube, check in editor game tab, all ok, cube is here, but console errors show up, probably related
![capture](https://user-images.githubusercontent.com/7936285/32702740-8ba2c682-c7eb-11e7-8dcb-8e7d46b3c874.PNG)
![capture3](https://user-images.githubusercontent.com/7936285/32702774-03865c9a-c7ec-11e7-9f94-f3526792b7e6.PNG)
![capture4](https://user-images.githubusercontent.com/7936285/32702775-050cca4a-c7ec-11e7-96c6-5ec3d6a02af7.PNG)
![capture2](https://user-images.githubusercontent.com/7936285/32702777-0642545c-c7ec-11e7-996b-b727a28ae995.PNG)

Open Build settings window, build solution in new and empty UWP folder
Open solution with visual studio 2017
Execute on device without debugging
## Unity Editor Version
Unity 2017.2.0f3
## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-v1.2017.2.0

**Comment by StephenHodgson** [comment]
You're using the incorrect version of the Unity Editor.  You need Unity 2017.2.0p1 MRTP 4

**Comment by StephenHodgson** [comment]
Oh I see, you're also trying to do HoloLens development. Then you need to use the 2017.1.x releases with the HoloToolkit-Unity-v1.2017.2.0 release

**Comment by xaviercrespin** [comment]
if it can help anyone : https://forums.hololens.com/discussion/9199/holograms-not-rendering-in-hololens/
The camera clipping was the culprit
