### ISSUE TITLE
Sharing Object Transform Updates, Rotation, Scale, Bools, etc.

### ISSUE THREAD

**Issue by reillydonovan** [Microsoft/MixedRealityToolkit-Unity#1355]
## Overview
I've been playing with the SharingTest and SharingSpawnTest examples and am having difficulty wrapping my mind around how to properly share/sync and update a game object between devices.

In the SharingSpawnTest I noticed I could resize, rotate, and scale and object over the network but when I try to do this in the SharingTest example nothing updates.  The only thing that is shared is the initial world anchor with the sphere and the only object that updates is the remote head manager.

How would I go about syncing and updating game objects across devices with the SharingTest example?  Is there a generic script I can put on an object similar to the remote head manager script?

Thanks!

**Comment by NeerajW** [comment]
There is not. But you should be able to adapt the RemoteHeadManager which broadcasts the head transform and transform the localPosition of your gameobject.
Remember, you cannot move an object that has an anchor attached to it. The anchor transform will override the gameobject transform.
You can move an object which is a child of an object that has an anchor attached to it.

Please reopen if you have more difficulties.

**Comment by keveleigh** [comment]
I also believe the `SharingSpawnTest` scene utilizes the sync system, which can be used to keep object in sync, like you described, across devices. The scripts are locating in the `Spawn` and `SyncModel` folders in the `Sharing` folder.

https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Sharing/Scripts/SyncModel/SyncObject.cs
