### ISSUE TITLE
Unity crashes after releasing the Trigger Button (Motion Controller).

### ISSUE THREAD

**Issue by Abstiens** [Microsoft/MixedRealityToolkit-Unity#1363]
## Overview
Unity crashes after releasing the Trigger Button (Motion Controller).
The crash happens, after I release the Trigger on the backside of the controller (no message, Unity just disappears). Nothing happens, while I click and hold the trigger.
If I pause Unity while I hold the trigger and then release it, it crashes immediately after I resume.

## Expected Behavior
Unity shouldn't crash. You should be able to use all buttons of the controller without Unity crashing

## Actual Behavior
Unity crashes

## Steps to reproduce
- Cloned the MixedRealityToolkit (Master Branch checked out)
- opened it in Unity (Unity 2017.2.0p1-MRTP4)
- Opened and started the "GrabMechanics" Scene
- Teleporting with Thumbstick works, switching between Controllers with Grip Button works
- Pressing and holding the Trigger works, but ...
- ... releasing the Trigger closes Unity without any further Messages.

Last Editor Log Entries (Multiple Times):

```
InvalidOperationException: Nullable object must have a value.
  at System.Nullable`1[System.Int32].get_Value () [0x0000b] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Nullable.cs:108 
  at HoloToolkit.Unity.InputModule.FocusManager.GetPointer (IPointingSource pointingSource) [0x0001d] in C:\Users\Vuframe\Documents\MixedRealityToolkit-Unity\Assets\HoloToolkit\Input\Scripts\Focus\FocusManager.cs:784 
  at HoloToolkit.Unity.InputModule.FocusManager.GetFocusDetails (IPointingSource pointingSource) [0x00003] in C:\Users\Vuframe\Documents\MixedRealityToolkit-Unity\Assets\HoloToolkit\Input\Scripts\Focus\FocusManager.cs:383 
  at HoloToolkit.Unity.InputModule.Cursor.UpdateCursorTransform () [0x0000c] in C:\Users\Vuframe\Documents\MixedRealityToolkit-Unity\Assets\HoloToolkit\Input\Scripts\Cursor\Cursor.cs:289 
  at HoloToolkit.Unity.InputModule.Cursor.Update () [0x00008] in C:\Users\Vuframe\Documents\MixedRealityToolkit-Unity\Assets\HoloToolkit\Input\Scripts\Cursor\Cursor.cs:143 
 
(Filename: /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Nullable.cs Line: 108)

Assertion failed
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Assert(Boolean)
HoloToolkit.Unity.InputModule.FocusManager:GetPointer(IPointingSource) (at Assets\HoloToolkit\Input\Scripts\Focus\FocusManager.cs:783)
HoloToolkit.Unity.InputModule.FocusManager:GetSpecificPointerEventData(IPointingSource) (at Assets\HoloToolkit\Input\Scripts\Focus\FocusManager.cs:429)
HoloToolkit.Unity.InputModule.InputManager:RaiseSourceUp(IInputSource, UInt32, InteractionSourcePressInfo, Object[]) (at Assets\HoloToolkit\Input\Scripts\Utilities\Managers\InputManager.cs:430)
HoloToolkit.Unity.InputModule.InteractionInputSource:InteractionManager_InteractionSourceReleased(InteractionSourceReleasedEventArgs) (at Assets\HoloToolkit\Input\Scripts\InputSources\InteractionInputSource.cs:919)
UnityEngine.XR.WSA.Input.InteractionManager:OnSourceEvent(EventType, InteractionSourceState, InteractionSourcePressType) (at C:\buildslave\unity\build\Runtime\VR\HoloLens\ScriptBindings\GestureSource.cs:481)
 
(Filename: Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs Line: 783)
```

## Unity Editor Version
Unity 2017.2.0p1-MRTP4

## Mixed Reality Toolkit Release Version
Commit cb59a1c7 (also tried 4daacf92 (Pull Request #1350))

**Comment by StephenHodgson** [comment]
@Abstiens can you confirm #1350 fixes this for you?

**Comment by StephenHodgson** [comment]
@Abstiens try the [latest push](https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1350/commits/1d1dc67b96662374d4d62a76f958ed9b93e47091) to #1350 and let me know if it fixed your issue.

**Comment by Abstiens** [comment]
@StephenHodgson Will check it tomorrow morning
Thank you :)

**Comment by Abstiens** [comment]
@StephenHodgson 
Yes, it is fixed. Thank your very much :)

**Comment by StephenHodgson** [comment]
Please leave issues open until PRs are merged. Thanks
