### ISSUE TITLE
Unity Throws assertions for main camera

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1369]
## Overview
In 2017.2.0f3 and 2017.2.0p1 unity throws assertions for the main camera when checking is the display is opaque.

```
Assertion failed: Main camera does not exist!
UnityEngine.XR.WSA.HolographicSettings:get_IsDisplayOpaque
```

## Steps for work around
Use the MRTP editor builds

## Unity Editor Version
2017.2.0f3 and 2017.2.0p1

## Mixed Reality Toolkit Release Version
db59a1c7fa0c0c463466028c5f3e70088bbfda52

**Comment by brean** [comment]
Has this bug been reported to Unity? (I can not find it in the Unity Bug tracker)

**Comment by genereddick** [comment]
If we are updating the current Unity version to 2017.2.1f1 from the MRTP versions, then this Assertion error is still there.

**Comment by StephenHodgson** [comment]
I don't get the assertion with that editor build

**Comment by markgrossnickle** [comment]
I get this assertion in the editor in 2017.2.1f1 vanilla version... I thought we didn't need MRTP versions at 2017.2.1?

I also just grabbed the latest Toolkit from Master yesterday.

**Comment by markgrossnickle** [comment]
For anyone else hitting this... wrapping a Application.isEditor check around each call to prevent the code from getting hit in the editor is a messy but working solution.

**Comment by StephenHodgson** [comment]
@markgrossnickle, this should be resolved with later versions of Unity

**Comment by StarWardo** [comment]
I am having the same error in the SharingTest.scene  using:

Latest master branch release: 2017.4.1.0
Unity version Patch 2017.2.1p2

I applied project settings, scene settings and UWP capability settings

**Comment by keveleigh** [comment]
@StarWardo Unfortunately, this is a Unity bug with seemingly many versions of 2017.2. The Toolkit and [Microsoft](https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools#installation-checklist-for-hololens) now recommend Unity's LTS branch, 2017.4, for WMR development.
