### ISSUE TITLE
What is the purpose of the SceneContentAdjuster?

### ISSUE THREAD

**Issue by MrMatthias** [Microsoft/MixedRealityToolkit-Unity#1371]
What is the purpose of the SceneContentAdjuster? It puts objects at eye level? 
How does it relate to the experience scale described at: https://developer.microsoft.com/en-us/windows/mixed-reality/coordinate_systems

**Comment by StephenHodgson** [comment]
Determines if you're using the HoloLens or IMHD.

HoloLens head starts at origin, where as the IMHD starts above it.

The `SceneContentAdjuster` is supposed to intelligently move the contents of the scene to the correct position.

**Comment by MrMatthias** [comment]
So positioning the floor at y=0 will work for IMHD without SceneContentAdjuster?
Shouldn't it move the stage down by some eye height value in Orientation-only and seated-scale mode, which have their origin at the initial head position?
