### ISSUE TITLE
Anchors

### ISSUE THREAD

**Issue by tspaddock** [Microsoft/MixedRealityToolkit-Unity#1375]
Hello,
I am having terrible difficulties with Anchor Managers! The hologram that I have sways and jumps all over the place it also jitters and jutters even though the fps is above 60...
What scene example or documentation is the best for me to reference to get the best understanding of how to us implement anchors? I have searched everywhere and nothing is of value!
Thanks!

## Unity Editor Version
5.6.3.p2

**Comment by eluchsinger** [comment]
Do you have good environment conditions? Enough light in the room and no moving stuff?
I don't know what could cause jumping, jittering and jutters of Holograms.

**Comment by PJBowron** [comment]
Your first port of call, if you haven't already visited:
[https://developer.microsoft.com/en-us/windows/mixed-reality/spatial_anchors](url)

**Comment by tspaddock** [comment]
Light conditions are good. Everything I am doing is not helping. I cannot get the hologram to remain steady. Anyone want to make a quick buck or two with this experience let me know!

**Comment by NeerajW** [comment]
Please reopen if your question was not answered.
