### ISSUE TITLE
Pure orientation-only experience places motion controllers off

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1376]
## Overview
The current MixedRealitytoolkit does not provide the possibility to completely restrict the player to head rotation (At least I found nothing). According to the following page `InputTracking.disablePositionalTracking = true;` has to be set:

> https://developer.microsoft.com/en-us/windows/mixed-reality/coordinate_systems_in_unity

In doing so, the head is restricted to rotation, however the Motion Controllers are not properly mapped into space, they're somewhere besides the player.

## Expected Behavior

The BoundaryManager should incorporate this feature. Toggling the boolean shouldn't ruin the relative controller position.

## Actual Behavior
Motion Controllers are somewhere in the space, Can't really tell relative to what they are positioned.

## Steps to reproduce
Create a script and set `InputTracking.disablePositionalTracking = true;`

## Unity Editor Version
MRTP4

**Comment by keveleigh** [comment]
This sounds like a Unity bug. The controller positions provided by Unity aren't respecting that boolean and are instead in relation to where the camera would be if that boolean wasn't set.

**Comment by Alexees** [comment]
File a bug report Case 970761
