### ISSUE TITLE
TapToPlace using SpatialMappingManager

### ISSUE THREAD

**Issue by brean** [Microsoft/MixedRealityToolkit-Unity#1378]
Hi!

The TapToPlace script in the example does not use the Spatial Mapping manager for the placement of objects. I created a small script based on Placeable.cs from https://developer.microsoft.com/en-us/windows/mixed-reality/holograms_230 and TapToPlace and called it MoveToPlace.
See https://gist.github.com/brean/cfa16cf873937db53ac88c8e0974a3dd

If it is OK with you I'd create a small example of show to use it and create a pull request. Alternatively I could extend the existing TabToPlace-Example.

**Comment by StephenHodgson** [comment]
What happens if a dev doesn't include `HoloToolkit.Unity.SpatialMapping;` in their importing of the toolkit?

**Comment by brean** [comment]
It requires the SpatialMappingManager attached otherwise you just get an error in the Log output, it needs the Spatial Mapping active and attached to work. That's one reason why I think I should create an own Example for it.

**Comment by StephenHodgson** [comment]
That's what I'm saying, a hard dependency to the spatial mapping manager should be avoided for modular approach

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
