### ISSUE TITLE
Error InteractionSourceHandedness in 2017.1.2f1

### ISSUE THREAD

**Issue by eluchsinger** [Microsoft/MixedRealityToolkit-Unity#1380]
## Overview
Errors thrown when using latest master in 2017.1.2f1 Unity version.
In the following files:
- [AttachToController](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs)
- [MotionControllerInfo](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerInfo.cs)

## Expected Behavior
No errors thrown when using the HTK.

## Actual Behavior
```
Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs(25,19): error CS0246: The type or namespace name 'InteractionSourceHandedness' could not be found. Are you missing an assembly reference?
```

## Steps to reproduce
Import the HTK in Unity 2017.1.2f1

## Unity Editor Version
Unity 2017.1.2f1

## Mixed Reality Toolkit Release Version
Last master https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/272d5fd10c0b836a2a7bcb021a655dcf2288d7e9

**Comment by krishnan-unni** [comment]
@eluchsinger If your project is not on IHMD and only Hololens, also if you don't want to change your current versions of Unity and toolkit then there is a temporary fix. Just go to the Assets\HoloToolkit\Input\Scripts\Utilities folder in your project and delete these files: AttachToController, MotionControllerInfo and MotionControllerVisualizer.cs. Now restart Unity, it'll compile fine and you'll get the toolkit menu and all. I have not encountered any error in my hololens project yet after this. Waiting for the permanent fix though :)

**Comment by eluchsinger** [comment]
@krishnan-unni I know it works, I am just opening an issue for a bug.

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
