### ISSUE TITLE
Mixed Reality Camera Parent Fade Plane impacts perf on HoloLens

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1389]
## Overview
MRCP Fade Plane is transparent instead of black, and adds a full frame render that impacts performance on HoloLens

## Unity Editor Version
Any

## Mixed Reality Toolkit Release Version
272d5fd10c0b836a2a7bcb021a655dcf2288d7e9

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
