### ISSUE TITLE
Missing controller reference on MRCP prefab

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1390]
## Overview
Missing Game Object references on Mixed Reality Camera Parent prefab.
![image](https://user-images.githubusercontent.com/13334553/32963872-3704a3ea-cb86-11e7-93e4-094c7910608b.png)

## Unity Editor Version
Any

## Mixed Reality Toolkit Release Version
272d5fd10c0b836a2a7bcb021a655dcf2288d7e9

**Comment by StephenHodgson** [comment]
I'm going to suggest we remove the references altogether now that we're loading from the driver.

**Comment by keveleigh** [comment]
We still want an alternate model, in case the driver model isn't available for whatever reason. Preferably, it'd be nicer than the rectangle I put in though haha.

**Comment by StephenHodgson** [comment]
Oh the reference were good. I just didn't include those prefabs in my build.

**Comment by StephenHodgson** [comment]
Want to make a new issue for updating alt controller models?

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
