### ISSUE TITLE
Standalone Build configuration does not compile.

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/MixedRealityToolkit-Unity#1391]
## Overview
Opened a freshly synced project in MRTP4 0p1

## Expected Behavior
No compile errors

## Actual Behavior
```
Error:
Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs(59,53): error CS1061: Type `HoloToolkit.Unity.InputModule.MotionControllerVisualizer' does not contain a definition for `TryGetControllerModel' and no extension method `TryGetControllerModel' of type `HoloToolkit.Unity.InputModule.MotionControllerVisualizer' could be found. Are you missing an assembly reference?
```

## Steps to reproduce
Open project and switch to Mac, PC, & Linux Standalone build.

## Unity Editor Version
2017.2.0p1 MRTP4

## Mixed Reality Toolkit Release Version
Current master

**Comment by NeerajW** [comment]
Likely due to some missing or bad IF DEFs

**Comment by StephenHodgson** [comment]
I take it you're build setting are targeting Windows Standalone?

**Comment by NeerajW** [comment]
True that. However, this is the first I've ever seen something like this happen when you just import the toolkit to your project.

**Comment by Railboy** [comment]
This one's on me #1379 - we merged this to unblock progress on pointers but didn't think to test build targets other than UWP. We'll make sure to test Mac/PC/Linux standalone before future merges.
