### ISSUE TITLE
ButtonIconProfileTexture not saving

### ISSUE THREAD

**Issue by eluchsinger** [Microsoft/MixedRealityToolkit-Unity#1393]
## Overview
I am trying to edit the [DefaultButtonIconProfileTexture](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/UX/Resources/Profiles/DefaultButtonIconProfileTexture.asset) to add my own Icons. I don't know if I am doing this right, but if I press on "Add custom icon" and then I select my icon, the file is not automatically saved. I tried saving the scene and everything, but it also didn't help. This means I can't check-in my changes into the SCM.

Is this intended behavior or is this a bug?

## Expected Behavior
Persist the changes after changing the profiles.

## Actual Behavior
The changes are not persisted. The file is not changing if I add or remove icons from the profile.

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2017.2.0f3

## Mixed Reality Toolkit Release Version
Master branch 272d5fd10c0b836a2a7bcb021a655dcf2288d7e9

**Comment by eluchsinger** [comment]
@Railboy I am sure you know the answer

**Comment by Railboy** [comment]
Changes to the array were not being saved. I've submitted a pull request to fix.

**Comment by keveleigh** [comment]
Don't close things until they're in master.

**Comment by StephenHodgson** [comment]
What about the helper's that auto close issues?  Should we not use those to automatically close issues anymore?

**Comment by keveleigh** [comment]
They auto close when it makes it into master. We should tag things fixed in the dev branch and let the helpers auto close when the fixes go into master.

**Comment by StephenHodgson** [comment]
Ahh, I thought it wasn't using a helper to close it, so when I saw it was merged, I figured it wasn't added.

Good to know!

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
