### ISSUE TITLE
Garbage Upgrade to Unity 2017

### ISSUE THREAD

**Issue by tspaddock** [Microsoft/MixedRealityToolkit-Unity#1396]
## Overview
I have upgraded my Unity software and it has totally screwed up everything that I have been working on for months. Past projects that I have created are now obsolete, new projects can not even be built.
## Expected Behavior
I just want to be able to build a project.
## Actual Behavior
After Installing a bunch of different versions of the software I now finally do not have any compiling errors within Unity, however I cannot get VS to build the Hololens project. When I build or debug the software only a blank/black window shows up. Unity software does not even load upon build.
## Steps to reproduce
Build from Unity then debug in VS2017

## Unity Editor Version
Unity 2017.1.2f1

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-v1.2017.2.0

VS Version 15.4.4

**Comment by OctagonHex** [comment]
For Unity 2017.1.2f1 you need to use HoloToolkit-Unity-Examples-v1.2017.1.2
https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/v1.2017.1.2

I could not get the HoloToolkit-Unity-v1.2017.2.0 release to work for HoloLens on any Unity version I tried.

**Comment by eluchsinger** [comment]
Have you double-checked the capabilities of your Unity project? You need to add the Windows Mixed Reality under XR Settings ->Virtual Reality in Player Settings.

To access player settings:  Edit -> Project Settings -> Player.

**Comment by tspaddock** [comment]
Finally got everything to start working together again with the following configuration:
Unity 2017.2.0f3
HoloToolkit-Unity-v1.2017.2.0
Microsoft VS Community 2017 Ver. 15.4.4
It still does give the following error however I am still able to compile script.
"Assertion failed: Main camera does not exist!
UnityEngine.XR.WSA.HolographicSettings:get_IsDisplayOpaque()
HoloToolkit.Unity.Boundary.BoundaryManager:RenderFloorQuad() (at Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs:101)
HoloToolkit.Unity.Boundary.BoundaryManager:Awake() (at Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs:90)"

**Comment by StephenHodgson** [comment]
@tspaddock see #1369
