### ISSUE TITLE
How to change cursor at runtime 

### ISSUE THREAD

**Issue by raedbenz** [Microsoft/MixedRealityToolkit-Unity#1397]
How can I change cursor style/prefab when hover over certain object then set it back to its defsult design once not in focus anymore?
Thanks

**Comment by Railboy** [comment]
You can do this by using an [**AnimatedCursor** ](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/Cursor/AnimatedCursor.cs) along with the [**CursorModifier** ](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/29ff159d6dee3a6ca6343c7fc305b26a51030488/Assets/HoloToolkit/Input/Scripts/Cursor/CursorModifier.cs)component. The cursor can receive animation triggers via the **CursorModifier's** `CursorParameters` array.

There is an example of the **CursorModifier** in the [InputManagerTest](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit-Examples/Input/Scenes) scene.

**Comment by NeerajW** [comment]
Please reopen if your question was not answered.
