### ISSUE TITLE
What is the maximum size of SharingService

### ISSUE THREAD

**Issue by snowymo** [Microsoft/MixedRealityToolkit-Unity#1399]
## Overview
I wanted to send mesh through hololens sharing service

## Expected Behavior
The mesh could be sent immediately

## Actual Behavior
I need to wait seconds or minutes if the mesh is large.
I wonder how sharing service behave if the content is too large. Therefore I can improve it in my side.

## Steps to reproduce
[how to pack a mesh into sharing service](https://github.com/snowymo/ScanAR/blob/master/Vuforia/Assets/zhenyi/Scripts/CustomMsgMgr.cs)

## Unity Editor Version
2017.1

## Mixed Reality Toolkit Release Version
vs2017

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
