### ISSUE TITLE
Issues with nullreferenceexception error with voice commands in Unity. Is it a HoloToolKit problem?

### ISSUE THREAD

**Issue by tezelia** [Microsoft/MixedRealityToolkit-Unity#1401]
Hey guys,

So I followed the tutorial below regarding voice commands and the 'keyword manager' which is now obsolete.  Instead I used 'speech input source' and 'speech input handler' and followed the tutorial 

https://hololens.reality.news/how-to/holotoolkit-add-voice-commands-your-hololens-app-0175284/

Problem now is, why do I keep receiving this error after following the same tutorial step by step? 

```
NullReferenceException: Object reference not set to an instance of an object
HoloToolkit.Unity.InputModule.SpeechInputSource.OnPhraseRecognized (ConfidenceLevel confidence, TimeSpan phraseDuration, DateTime phraseStartTime, UnityEngine.Windows.Speech.SemanticMeaning[] semanticMeanings, System.String text) (at Assets/HoloToolkit/Input/Scripts/InputSources/SpeechInputSource.cs:166)
HoloToolkit.Unity.InputModule.SpeechInputSource.ProcessKeyBindings () (at Assets/HoloToolkit/Input/Scripts/InputSources/SpeechInputSource.cs:147)
HoloToolkit.Unity.InputModule.SpeechInputSource.Update () (at Assets/HoloToolkit/Input/Scripts/InputSources/SpeechInputSource.cs:88)
```

This is the only reason why my voice commands don't work after building but I am not sure how I can reoslve this in Unity.

Firstly is it actually my coding or workflow in unity or is the problem from the holotoolkit.

I only ask because when I double click the null reference error on Unity, it highlights this line of code within the SpeechInputSource.cs file. 

```
InputManager.Instance.RaiseSpeechKeywordPhraseRecognized(this, 0, confidence, phraseDuration, phraseStartTime, semanticMeanings, text);
```

Am I missing something? This actually happened with another script I created to change colors of a shape. I just keep getting the nullreferencexception errors

Here is the code I attached on the 3d text 

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ColorChange : MonoBehaviour {

	TextMesh textMesh;

	// Use this for initialization
	void Start () {

		textMesh = GetComponent<TextMesh> ();
		
	}
	
	public void ColorBlue ()
	{
		textMesh.color = Color.blue;
	}


	public void ColorRed ()
	{
		textMesh.color = Color.red;
	}
		

	public void ColorGreen ()
	{
		textMesh.color = Color.green;
	}
}
```

**Comment by StephenHodgson** [comment]
In the future, please fill out the Issue template

**Comment by NeerajW** [comment]
Do you have the Microphone capability set in your project?
Edit > Project Settings > Player > Windows Store > Publishing Settings > Capabilities

**Comment by keveleigh** [comment]
Do you have an [`InputManager`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/Utilities/Managers/InputManager.cs) in your scene?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
