### ISSUE TITLE
Update ignore file to exclude UnityPackageManager

### ISSUE THREAD

**Issue by Railboy** [Microsoft/MixedRealityToolkit-Unity#1404]
## Overview
The file manifest.json file is a nuisance that sneaks into commits constantly.

Since we have no immediate plans for using the Package Manager, should we add UnityPackageManager to our .gitignore?

## Unity Editor Version
2017.2.0p1 MRTP4

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
