### ISSUE TITLE
EditorPrefsUtility's filename does not match the class name

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1405]
## Overview
EditorPrefsUtility should match it's file name

## Mixed Reality Toolkit Release Version
2c59d07b574cbde904b7ad6bd2e249438597440d

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
