### ISSUE TITLE
How would someone go about saving Audio Clips?

### ISSUE THREAD

**Issue by dtb49** [Microsoft/MixedRealityToolkit-Unity#1408]
## Overview
I've seen in several Microsoft promotional videos of users being able to record their voice and have it saved so that they can come back to it later (i.e Ford spotlight). I am able to record and play back my recording but how would I go about saving them for later use? 

I didn't see any scripts in the tool kit relating to this so, possible future request also.

**Comment by brean** [comment]
You can Record sounds using the normal Unity-API. Add a AudioSource to a GameObject and you can record sound using something like this:
```
private bool recording = false;

private AudioClip clip;
private float recordingStart;

void StartRecording() {
    clip = Microphone.Start(Microphone.devices[0], true, 30, 44100);
    recordingStart = Time.unscaledTime;
    recording = true;
}

public void StopRecording() {
    if (recording)
	{
		recording = false;

		float timeSinceRecordStarted = Time.unscaledTime - recordingStart;
		if (timeSinceRecordStarted < 30f)
		{
			AudioClip ac = clip;
			float lengthL = ac.length;
			float samplesL = ac.samples;
			float samplesPerSec = (float)samplesL / lengthL;
			if (samplesPerSec * timeSinceRecordStarted <= 0)
			{
				return;
			}
			
			// crop audio to actual recorded sound length
			float[] samples = new float[(int)(samplesPerSec * timeSinceRecordStarted)];
			ac.GetData(samples, 0);

			if ((timeSinceRecordStarted * samplesPerSec) > 0)
			{
				clip = AudioClip.Create("RecordedSound", (int)(timeSinceRecordStarted * samplesPerSec), 1, 44100, false);
				clip.SetData(samples, 0);
			}
		}
    }
```

and to play it 
```
public void PlayRecording(string data)
{
	AudioSource source = gameObject.GetComponent<AudioSource>();
	source.Stop(); // stop recording if needed

	source.clip = clip;
	source.Play();
}
```

Take a look at the Unity 3D scripting reference: https://docs.unity3d.com/ScriptReference/Microphone.Start.html

**Comment by Skquark** [comment]
I had to do this myself and found two ways of implementing.  At first I use this custom SavWav class to convert an AudioClip to a .wav, which you can find here: https://gist.github.com/darktable/2317063
Got that working pretty easily, but then I got the Unity Asset File Manager, which had a method built in to do that too.  Converting to an .mp3 file is a more involved process, but doable with the platform specific codex.

**Comment by dtb49** [comment]
Fortunately I don't need to convert them to an MP3, .wav works fine for me. I basically used that to save them and then I took the file path string and saved it to a [PlayerPrefX](http://wiki.unity3d.com/index.php/ArrayPrefs2) String Array and I also saved the user's cursor position and stored that into a PlayerPrefX Vector3 array. Then I instantiate a cube with an AudioSource at that position and use www to load the AudioClip onto the AudioSource and then when I airtap on the cube it plays the AudioClip back to me. 

Whenever I start back up the app I retrieve my arrays and instantiate all the cubes back to their positions, but I probably wouldn't need to save the positions thinking about it now. I could add a TapToPlace script on it so that it stays in the correct position every load up. 

That is what I have so far anyway. Still working out the kinks of it, but I think its pretty good so far.

**Comment by StephenHodgson** [comment]
@DaveSullivanAtWork would the new audio bank system help with this?

**Comment by DaveSullivanAtWork** [comment]
@StephenHodgson No, this functionality used to be in the MicStream code (HoloToolkit.Unity.InputModule.MicStream) that seems to have been removed (WACK Failure on the supporting dll sited).

**Comment by davidkline-ms** [comment]
MicStreamSelector dll is back in the toolkit!
