### ISSUE TITLE
Build Window make IP Address editable

### ISSUE THREAD

**Issue by eluchsinger** [Microsoft/MixedRealityToolkit-Unity#1409]
## Overview
The build window doesn't let me choose an IP Address. I only see the 127.0.0.1 IP Address. If there is a network discovery happening, it is restricted by the corporate network, so it won't find the HoloLens. I have to enter the IP Address manually.

## Expected Behavior
Can we make the textbox editable so that I can enter the IP Address manually?

**Comment by StephenHodgson** [comment]
See #1020
