### ISSUE TITLE
SpatialMappingTap.shader is not working with single-pass stereo rendering

### ISSUE THREAD

**Issue by if1live** [Microsoft/MixedRealityToolkit-Unity#1411]
## Overview

[SpatialMappingTap.shader](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/SpatialMapping/Shaders/SpatialMappingTap.shader)  not working in single-pass stereo rendering

## Expected Behavior

SpatialMappingTap.shader is working in single-pass stereo rendering.

## Actual Behavior
only rendered in one eye. 

## Steps to reproduce

use spatial mapping tap shader in single-pass sterero rendering.

I already write patch. 

https://github.com/if1live/MixedRealityToolkit-Unity/commit/97bd22b7db42870c1456f89799df2a048b28d054

I read this document, then apply it.
https://docs.unity3d.com/Manual/SinglePassStereoRenderingHoloLens.html

I don't know how to contribute, so I write issue.

## Unity Editor Version

2017.2.0p2

**Comment by StephenHodgson** [comment]
Looks good, open a PR :)

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
