### ISSUE TITLE
Is there an issue with Unity2017.2.p2

### ISSUE THREAD

**Issue by MarjanPl** [Microsoft/MixedRealityToolkit-Unity#1413]
## Overview
Experiencing severe color seperation when walking around an anchored object. Even with explicitly set stabilization plane. 

## Expected Behavior
Anchored Hologramm should be in focus and is absolutly not expected to show color seperation as described here: https://developer.microsoft.com/en-us/windows/mixed-reality/hologram_stability

## Actual Behavior
After anchoring an Object view is fine. Walking around it (after 90 degrees) shows extreme Color Separation, although movement is slow.  Downgrading to Unity3D 2017.2.f1 shows normal behaviour.

## Steps to reproduce
Use Unity3D patch release 2017.2.p2. Use MRT demoscene tab to place. Place object in spatial room. Walk around.

## Unity Editor Version
2017.2.p2

## Mixed Reality Toolkit Release Version
latest i guess.

**Comment by StephenHodgson** [comment]
> latest i guess.

latest from the master branch or the latest release?

**Comment by MarjanPl** [comment]
Now i am embarressed. i pulled with github Desktop and copied necessary files to my Project. base is: https://github.com/Microsoft/MixedRealityToolkit-Unity.git and pull was from 2 weeks ago.
is there some file inside holotoolkits Folders to check a Version number?

I am very sorry, i know These Kind of questions are cumbersome!

**Comment by StephenHodgson** [comment]
No worries! It just really helps when we're trying to pinpoint the issue.
You're right, we really ought to add a version number to the license or readme someplace.

In either case, I'm not sure anything has really changed with the anchoring recently.  That stuff has been pretty stable up until now.

I have not tested MRTK compatibility with the new patch release yet, as we were waiting for a special MRTP build, so I cannot attest to knowing the changes Unity has rolled out.

Sounds like this could potentially be an Editor bug.  Try creating some repro steps that don't include the MRTK just to rule it out.

**Comment by RainslayerX** [comment]
Currently i'm having this issue, MRTP5 build. When walking 90 degrees around the placed object heavy color seperation occurs and when standing behind the object it wont stay stable on the ground, it heavilly drifts. 

When recording with the mixed reality capture its visible that the object moves towards the camera when standing at the point of heavy color seperation. Almost like the Hololens loses track of depth.

I can't remember but i think it does not happen when the stabilization plane is not set. But than the holograms are not stable then in my case. 

Its almost like the stabilization plane doesn't rotate towards the camera in the build, Not able to test this as remote crashes the editor.

**Comment by rolandsmeenk** [comment]
This seems to be similar to https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1481
