### ISSUE TITLE
Removing GamepadInput.cs from InputManager.prefab breaks Xbox gamepad support

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/MixedRealityToolkit-Unity#1414]
## Overview
I understand new events were added for Xbox gamepad but GamepadInput.cs maps A to InputManager air tap. This is now all broken unless I write special code.

## Expected Behavior
Gamepad just works with HTK input manager.

## Actual Behavior
Its broken.

## Steps to reproduce
Use GamepadTest.unity and it does not work.

FIX:
Re-add GamepadInput.cs to GesturesInput under InputManager prefab.

**Comment by StephenHodgson** [comment]
duplicate of #1078

**Comment by StephenHodgson** [comment]
We shouldn't re add the `GamePadInput.cs` because it's now deprecated.
I've got some changes in the pipe to handle the old logic but in a more dynamic/customizable way.

**Comment by keveleigh** [comment]
If there's nothing that currently has this functionality other than `GamepadInput`, then that script is not and should not have been deprecated.

**Comment by StephenHodgson** [comment]
`GamepadInput` was a little too specialized to be on a default prefab.

I found myself removing it every time.

**Comment by StephenHodgson** [comment]
I'll have the PR by the EOD

**Comment by NeerajW** [comment]
It's not duplicate. What you are doing is different. I have customers who want it. We are reading until broken stuff is fixed.
