### ISSUE TITLE
Holograms do not to scale correctly

### ISSUE THREAD

**Issue by monsdar** [Microsoft/MixedRealityToolkit-Unity#1417]
## Overview
In a past project I had to work with bigger holograms (>10m) and found that the holograms aren't scaled correctly. 10 Unity units should be 10 meters, but the scale differs by a small margin (1.55% to 1.8%).

I tested this with multiple HoloLenses in different environments (warehouse, office) at different lighting conditions to make sure it's not an issue with the sensors.

Not even sure if this is a HoloLens/MRTK issue or if this is simply Unity, not sure how to test that.

## Expected Behavior
If I add a cube in Unity and make its size to be 10 units the hologram will be 10 meters in reality too.

## Actual Behavior
The size seems to be off by 1.55% to 1.8%.

## Steps to reproduce
I created a small example project [HERE](https://github.com/monsdar/HoloLens-ScaleTest). I stripped out some parts like the Mixed Reality Toolkit in order to have a small repo. After importing it you should be able to deploy it onto a HoloLens.

The app shows a cube with a lenght of 10m that you could position anywhere around you (usability is not the best, but it is good enough for the purpose). Measure a distance in your area to be 10m long and put the hologram besides it. You'll see that it is shorter than 10m.

## Unity Editor Version
Unity 2017.2.0.f3

## Mixed Reality Toolkit Release Version
MixedRealityToolkit-Unity-1.2017.2.0

**Comment by monsdar** [comment]
Searched a bit through the issue tracker and the web in general, but did not find any usable results. Not sure if I used the wrong words for the search... Has somebody noticed this effect?

**Comment by PJBowron** [comment]
You may be experiencing world-drift. Try using a WorldAnchor to keep your cube in place and see if you get more accurate results.

**Comment by monsdar** [comment]
Thought about world-drift too at first. I made the following observations that speak against it:

* It's reproducible: Holograms are always too short (world-drift would make them randomly look longer, shorter, at a different position). I think the difference between 1.5% and 1.8% is related to world-drift, but the overall effect seems to be something else
* When placing a hologram around you it is too short in each direction. World-drift would put the hologram in a different position, therefore it should be shorter in one direction and longer in another
* When changing the scale to make the hologram appear a bit bigger it fits correctly every time I test. The scale and position of the hologram does not change randomly
* This effect appears in different environments in the same way. In my understanding world-drift depends on the environment you're in.

Nonetheless I'll see for putting in a spatial anchor.

**Comment by PJBowron** [comment]
Yes, given all of the above it does sound like a different issue. World-drift would generally result in effectively larger holograms, as their points of origin subtly follow you as you move. To your last point, drift depends on the HL's ability to accurately track it's own movement in your environment, so yes it may vary from space to space (or even within the same space over time!)

**Comment by monsdar** [comment]
It's also that the holograms are smaller instead of bigger

**Comment by monsdar** [comment]
I also posted this into the Unity forums in order to find someone from Unity to help with this: https://forum.unity.com/threads/unity-scale-does-not-seem-to-fit-real-world-scale.506345/#post-3307004

**Comment by darkgap** [comment]
This happens for me too, the hologram is placed correctly,using world anchor, and the hologram scale is not changed in any of the script in the program (I've also used a floating text with the object scale to be shure about that).
The real world object is about 7 cm smaller than the 3d model in the hololens I use, in another hololens is 7 cm longer though, it seems like a sensor issue, also because from the rs4 the sensor tuning utility is not anymore available in favor of automatic sensor tuning, in fact it happened that one time the hologram fitted the real object perfectly, and after about 20 mins, without changing anything, the hologram was of different size

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Comment by lmaxsmith** [comment]
This is definitely still an issue. Quite consistent according to my measurements. I'm applying universal scaling to models, calculations, etc. to make up for it but that is a bad hacky fix that will cause serious performance problems in the future.

**Comment by yjlintw** [comment]
I'm also seeing the same issue. Unity 2020.3, MRTK version 2.7.2

**Comment by PJBowron** [comment]
Something I just noticed when re-reading the OP is that the originator stripped MRTK from the demo repo. In other words, while this is apparently still a valid issue, that issue doesn't necessarily belong _here_ (in MixedRealityToolkit-Unity).
