### ISSUE TITLE
ReflectionExtensions take BindingFlags parameter but ignore it

### ISSUE THREAD

**Issue by alankemp** [Microsoft/MixedRealityToolkit-Unity#1418]
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/405bb16be62b5d1eb18f8e5f39d9d1fe9a962013/Assets/HoloToolkit/Utilities/Scripts/CrossPlatform/Reflection/ReflectionExtensions.cs#L106-L109

In ReflectionExtensions.cs there is an extension method to get the fields of a type.  This takes BindingFlags as an argument, but doesn't use them.

We were trying to get the public and private member variables like this:

    t.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);

Which works on platforms other than WSA with the native API, but with the extension method the flags are ignored and we got all fields including properties, constants, etc.

This also applies to some of the other methods in that file, at least GetMethods() and GetProperties().

I'd be happy to contribute a patch to implement the filtering.

**Comment by ForrestTrepte** [comment]
Sounds like a good idea to me.

**Comment by StephenHodgson** [comment]
Please do.

**Comment by alankemp** [comment]
I spent some time this afternoon setting up a test project so I could work on this, but it all works!

It works because there is a new System.Reflection.TypeExtensions DLL coming in via the platform SDK.  It is also available standalone as a nuget package from here:  https://www.nuget.org/packages/System.Reflection.TypeExtensions/

Given this is an official release and someone else will maintain/fix the code, I would suggest we now remove ReflectionExtensions.cs from MRTK.

**Comment by StephenHodgson** [comment]
We don't have a way to consume nuget packages in the MRTK, also we need to be able to support IL2CPP or NET scripting backends differently for the reflection extensions, so removing this isn't trivial.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
