### ISSUE TITLE
Adding support for devices that use touchscreens

### ISSUE THREAD

**Issue by PJBowron** [Microsoft/MixedRealityToolkit-Unity#1421]
I've recently been looking into getting apps developed with the toolkit working on mobile devices, especially now following the addition of the WSA buildswitches. One of the sticking points has of course been handling input.

To that end, I've locally added a simple `TouchscreenInputSource` class, following the paradigm of the existing input sources, and propose adding it to the toolkit.

Thoughts at this point? Thanks.

**Comment by StephenHodgson** [comment]
I thin that would be a wonderful idea

**Comment by PJBowron** [comment]
Great - busy day today but I'll try to get a PR together early next week.

**Comment by PJBowron** [comment]
Finally got around to tidying and WACK-testing this submission and creating the PR (#1456).
Apologies for the delay and for any procedural snafus - this is my first GitHub submission...

**Comment by StephenHodgson** [comment]
No worries!  Thanks for the contribution!
