### ISSUE TITLE
Unable to build for HoloLens

### ISSUE THREAD

**Issue by Vusa360** [Microsoft/MixedRealityToolkit-Unity#1422]
## Overview
I am working with Unity to make an application, however, each time I try to build the application in Visual Studio there is an error.
## Expected Behaviour
Builds to HoloLens without any errors
## Actual Behaviour
When build is clicked in Visual Studio an error occurs saying 

> System.IO.FileNotFoundException: ...\UnityEngin.dll

This is due to the letter e being randomly removed from "UnityEngine.dll". It is not limited to files, each time I build it removes a seemingly random letter / number / non-alphanumeric character from a link for a dll file.

A full example of the output can be found [here](https://pastebin.com/NBzBJ94C)
## Steps to reproduce
Create a new unity project in one of the versions mentioned below, set it up for deploying onto the HoloLens, see image <br>
![screenshot 2](https://user-images.githubusercontent.com/20107442/33176660-bb6ea10a-d057-11e7-94fa-4b6de62ef2a6.png)

Import the HoloLens version mentioned below and set up your scene however you like.

Attempt to build in the visual studio version mentioned below.

## Unity Editor Version
2017.2.0p1, 2017.2.0p1-MRTP4, 2017.2.0p2
## Visual Studio Version
15.4.4
## Windows SDK
10.0.16299.0
## Mixed Reality Toolkit Release Version
[Latest Release](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/v1.2017.2.0)
___
I apologise if I just made a mistake in the setup which is causing this

**Comment by StephenHodgson** [comment]
I was not able to reproduce this with 2017.2.0p2 and the steps you have given.

**Comment by Vusa360** [comment]
I have just completed a full reinstall of both unity and vs and it appears to be working again. It appears to have been a fault with one of my installs. Apologies for that
