### ISSUE TITLE
Interactive Mesh Cursor gets bigger after each teleport

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/MixedRealityToolkit-Unity#1423]
Just what it says. It's nice that it scales in the distance, but it's not very handy do to so after a teleport ;). Fix is very simple:
Line 124 is
```
float distance = Vector3.Distance(GazeManager.Instance.GazeOrigin, transform.position);
```
Should be
```
float distance = Vector3.Distance(Camera.main.transform.position, transform.position);
```

**Comment by StephenHodgson** [comment]
Should be `CameraCache.Main`

**Comment by LocalJoost** [comment]
Yeah I fixed it locally by getting camera.main in a class variable

Joost van Schaik

Windows Development MVP
Sent from mail for Windows 10

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by keveleigh** [comment]
Is there an underlying bug in GazeManager here, then?

I'd expect the GazeOrigin to always be the camera's position, but it looks like it isn't being updated properly.

**Comment by keveleigh** [comment]
Hmm, after running and testing the InteractiveMeshCursor scene, I'm unable to repro this issue.

**Comment by LocalJoost** [comment]
Neither can I anymore, in the newest code. So I think this can be closed
