### ISSUE TITLE
APPX does not build on current Unity Version (Assembly-CSharp-firstpass does not exist)

### ISSUE THREAD

**Issue by brean** [Microsoft/MixedRealityToolkit-Unity#1424]
## Overview
When building the APPX I get the error "Failed to restore nuget packages" because the folder Assembly-CSharp-firstpass does not get created during the build process. When I remove the RestoreNugetPackages-check in line 240 ( https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployTools.cs#L240 ) it builds a fine APPX that I can deploy to Hololens without problems. I do not know enough about the build process to say if it is really needed and if my workaround is a valid fix for the current version.

## Expected Behavior
The APPX should just build without any error/the test for Assembly-CSharp-firstpass should (maybe?) be removed.

## Actual Behavior
"Failed to restore nuget packages" is shown (which is also a misleading error message).

## Steps to reproduce
Build an APPX from any project using current Master branch and the stable unity and VS-Versions

## Unity Editor Version
2017.2.03f

## Mixed Reality Toolkit Release Version
master-branch

**Comment by StephenHodgson** [comment]
Interesting that unity isn't creating a first pass dll for you.

I wonder that triggers that.

**Comment by brean** [comment]
So should I report this to Unity?

**Comment by StephenHodgson** [comment]
Unsure, but I am curious why the `firstpass.dll` wasn't generated for you.

**Comment by StephenHodgson** [comment]
Did a bit of research, seems like the `csharp-firstpass.dll` generation _is_ optional.  It's only generated by assets in the first pass during compilation.

[Unity Answers Post](
https://answers.unity.com/questions/614570/how-do-i-get-rid-of-assembly-csharp-firstpass-and.html)
> The Assembly-CSharp-firstpass.dll contains all your compiled scripts which are compiled during the first-pass.

See [Unity Docs for more info](https://docs.unity3d.com/Manual/ScriptCompileOrderFolders.html).
> Phase 1: Runtime scripts in folders called Standard Assets, Pro Standard Assets and Plugins.

**Comment by brean** [comment]
Well, I am using Holotoolkit-Unity, so if nothing from that uses any plugins/assets then yes, I am not using any of those.

**Comment by StephenHodgson** [comment]
No, if you're using the tookit, it should be creating that first pass. Terry deleting all your project sln files and reimport everything in unity.

**Comment by brean** [comment]
I created a brand new empty unity project, added the Mixed-Reality Toolkit Unity Assets, applied all the settings from the Mixed Reality Toolkit-Menu saved the scene and tried to build this (without changeing anything) and it does not build the firstpass.dll. So I assume this specific to my unity and/or Visual Studio version. I think the only possible next step is to file a bugreport for Unity?

**Comment by genereddick** [comment]
Likewise for me. No firstpass is created with just the MRTK installed though it is created with Standard Assets included.

**Comment by Dmidcap** [comment]
Just offering my two cents, I'm having this exact same problem. Try to build Appx, get 'Failed to restore nuget packages', so I go to line 240, comment out the part that checks for Firstpass, click build and voila! I haven't tested the APPX on a hololens yet, will comment again when I do.

**Comment by stonstad** [comment]
I can confirm similar behavior described by @Dmidcap   Commenting out error logic and removing return false (for error status) enables successful build and deployment to HoloLens hardware.
