### ISSUE TITLE
My old project don't build anymore

### ISSUE THREAD

**Issue by thomasH7** [Microsoft/MixedRealityToolkit-Unity#1425]
## Overview
How can I build an old unity 5.5 Hololens app with new windows 10 updates installed .
I think it is because Unity try to build with new UWP SDK but the app is intended to be build with old ones. I didn't manage to change UWP version in 5.5 like I can with 2017.x

## Expected Behavior
Build and deploy my app like 6 months ago

## Actual Behavior

I get errors like this when I try to Build : 
```
Assets\HoloToolkit-Examples\SharingWithUNET\Scripts\GenericNetworkTransmitter.cs(114,57): error CS0246: The type or namespace name 'StreamSocketListener' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit\SpatialMapping\Scripts\RemoteMapping\RemoteMeshSource.cs(140,69): error CS0246: The type or namespace name 'AsyncStatus' could not be found (are you missing a using directive or an assembly reference?)
```

## Unity Editor Version
5.5.1f1

**Comment by StephenHodgson** [comment]
What version of the toolkit are you using?
(That's a required field when creating a new issue)

**Comment by thomasH7** [comment]
Thanks for the fast reply,
I really don't know how to find my holotoolkit version, is there a way to know it ? I made my project early 2017, it was the latest version by then.

**Comment by StephenHodgson** [comment]
Depends on how you imported it into your project. If you did it via get a SHA for the checkout is fine, but if you downloaded a release then I need the release version.

**Comment by thomasH7** [comment]
Just found the unitypackage, it was 1.5.5.0

**Comment by StephenHodgson** [comment]
Try updating to a newer release, or figure out what changed in your project.

**Comment by StephenHodgson** [comment]
Well, _something_ had to have changed since you can't build anymore, correct?

**Comment by thomasH7** [comment]
Nothing changed in my project, this is why I try to find another reason. And because I installed visual studio 2017 and the latest Windows 10 update recently, I guess maybe the problem comes from here. Unity is using UWP to build right ?

**Comment by StephenHodgson** [comment]
Yeah, I think older versions of Unity are not compatible with 2017.

You may need to keep with VS 2015

**Comment by thomasH7** [comment]
ok but I can't target VS 2015 even if I uninstall 2017.
I'll try to uninstall both and reinstall 2015.
Thank for your time.

**Comment by StephenHodgson** [comment]
See #860

**Comment by keveleigh** [comment]
> I use Spectator View and it only works with 5.5

The repo sample has been updated to at least 5.6, though updates to anything newer are likely only namespace/event name updates, rather than functionality updates. Adding @fieldsJacksonG for additional comments.

https://github.com/Microsoft/MixedRealityCompanionKit/blob/master/SpectatorView/Samples/SharedHolograms/ProjectSettings/ProjectVersion.txt

**Comment by thomasH7** [comment]
Thanks, I tried with 5.6 and newer but I didn't manage to compile the dll (multiples errors on both Visual studio 2015 and 2017). Maybe I'll try again later but I'm in the hurry and prefered to keep my 5.5 stable version.
@StephenHodgson I finally manage to compile my project with a Unity 5.5.5 upgrade (Didn't know Unity 5 was still updated). Thanks

**Comment by StephenHodgson** [comment]
I think there was an exception for 5.5 because of the security patch and MSFT updating the build process in VS 2017.

Glad to hear that fixed it.
