### ISSUE TITLE
Update Unity Editor to 2017.2.0p2 MRTP5

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1432]
## Overview
New release of [Unity Editor 2017.2.0p2 MRTP5](http://beta.unity3d.com/download/a07ad30bae31/download.html)

Release Notes:
---
- This build incorporates all changes from Unity’s 2017.2.0p2 patch; see release notes here for details.
- Fixed issue with applications not recovering correctly from tracking loss. (case 969994)
- Fixed a random threading crash.

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
