### ISSUE TITLE
Change the MRTK's default branch to Dev_Working_Branch

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1434]
## Overview
Changing the MRTK's default branch to Dev_Working_Branch
See [Github documentation](https://help.github.com/articles/setting-the-default-branch/) for details

**Comment by keveleigh** [comment]
I don't know if we should do this. We still want people who come to the repo to default to the (theoretically stable) master. There doesn't seem to be a way to both do that and default PRs to the dev branch though.

**Comment by StephenHodgson** [comment]
When you pull or clone from the git client, the master branch will still be automatically checkedout.

The only real difference we will see here is the default branch PRs are opened on.

**Comment by StephenHodgson** [comment]
I think we could have picked a better name as well, haha.  I mean, we already know it's a branch.
