### ISSUE TITLE
Single air tap registers as double air tap with OnInputClicked

### ISSUE THREAD

**Issue by mr-mystery** [Microsoft/MixedRealityToolkit-Unity#1437]
## Overview
I've been creating a functionality for my project. And the functionality is that when the object (Box) collides (using OnTriggerEnter()) with another object (Cylinder) with rigidbody and certain component in the Box object should get disabled. This functionality is working fine. But a script in the Box object which has the OnInputClicked () method registers every tap as a double tap which makes a bool as true and false at the same time which messes up my work. Does anyone have this issue?

P.S. The OnInputClicked () function worked normally before the collision.

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
Unity Version: 2017.1.2f1.

## Mixed Reality Toolkit Release Version
HoloToolkit Version: v1.2017.2.0.

**Comment by mr-mystery** [comment]
Hi @StephenHodgson,

I've been creating a functionality for my project. And the functionality is that when the object (Box) collides (using OnTriggerEnter()) with another object (Cylinder) with rigidbody and certain component in the Box object should get disabled. This functionality is working fine. But a script in the Box object which has the OnInputClicked () method registers every tap as a double tap which makes a bool as true and false at the same time which messes up my work. Does anyone have this issue?

P.S. The OnInputClicked () function worked normally before the collision.
Unity Version: 2017.1.2f1.
HoloToolkit Version: v1.2017.2.0.

**Comment by StephenHodgson** [comment]
Are you consuming the event with `eventData.Use()`?

**Comment by mr-mystery** [comment]
No. I'm not using the eventData.

**Comment by StephenHodgson** [comment]
Yeah, you need to call `eventData.Use()` to prevent the event from falling through to the next handler.

**Comment by StephenHodgson** [comment]
Could you put together a sample project, or some repro steps so we can dive deep into the issue here?

**Comment by mr-mystery** [comment]
Alright.

**Comment by uzumi18** [comment]
EventSystem in InputManager has a 'Input Actions Per Second'.. make sure this is set to something like 10

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
