### ISSUE TITLE
Add WindowsDevicePortalWrapper library to project

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1439]
## Overview
Replace custom Portal API calls with [DevicePortalWrapper](https://github.com/Microsoft/WindowsDevicePortalWrapper)

Currently the only drawback is .Net 3.5 support for backwards compatibility with older versions of Unity
- [library only supports .NET 4.6](https://github.com/Microsoft/WindowsDevicePortalWrapper/issues/260)

**Comment by davidkline-ms** [comment]
I would LOVE to see this done, even if it only works with newer versions of Unity. Rewriting the wrapper to support .net 3.5 would be a significant amount of work.

**Comment by StephenHodgson** [comment]
Let's revisit this after we get vNEXT and package management sorted out.
