### ISSUE TITLE
[master] Haptics doesn't work when running in-editor

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#1440]
## Overview
The UWP haptics APIs are currently exposed in a way that makes them incompatible with running in the Unity editor.

My recommended fix would be by adding to the DLL (we can rename it to make it more accurate) I wrote to expose the motion controller model API, [found in the MixedRealityTookit here](https://github.com/Microsoft/MixedRealityToolkit/blob/master/UnityEditorMotionControllerModelDLL/MotionControllerModel/MotionControllerModel.cpp).

Additional methods could be written, with identical code to lines 18-39, but then calling the haptics APIs like in the [existing Toolkit extensions](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/Extensions/InteractionSourceExtensions.cs#L53).

I initially experimented with this addition when writing the initial DLL, but remember being blocked around creating a `TimeSpan` object, without time at the time to fully investigate.

## Expected Behavior
The haptics APIs work when running in the editor.

## Actual Behavior
The haptics APIs only work in a deployed app.

## Steps to reproduce
Run the MotionControllerTest scene and press grasp or menu to try to trigger haptics.

## Unity Editor Version
All

## Mixed Reality Toolkit Release Version
All

**Comment by StephenHodgson** [comment]
Any way we can extend this to also tie in haptics from non spatial controllers as well?

**Comment by keveleigh** [comment]
Yeah, maybe we can use the [UWP GamePad Vibration APIs](https://docs.microsoft.com/en-us/windows/uwp/gaming/gamepad-and-vibration#vibration-and-impulse-triggers-overview) or the [SimpleHapticsControllers from the UWP RawGameController APIs](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.rawgamecontroller) to expose haptics there as well.
