### ISSUE TITLE
Missing scripts (VoIP)

### ISSUE THREAD

**Issue by eluchsinger** [Microsoft/MixedRealityToolkit-Unity#1447]
## Overview
The [documentation](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Sharing/README.md#microphonetransmittercs) says that I need the `MicrophoneReceiver.cs` and `MicrophoneTransmitter.cs` files in order to send and receive audio.
Those scripts are not in the repository.
## Expected Behavior
Behaviors can be added.
## Actual Behavior
Behaviors are missing
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2017.2.0f3
## Mixed Reality Toolkit Release Version
https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/405bb16be62b5d1eb18f8e5f39d9d1fe9a962013

**Comment by StephenHodgson** [comment]
These were removed temporarily because the dll they relied on doesn't pass wack.  The scripts are in `HoloToolkit-Examples/Input/Scripts`.

**Comment by eluchsinger** [comment]
Should we update the docs then? 
Can we use those from the examples or why are those there? I tried to make that work but failed so far...

**Comment by StephenHodgson** [comment]
See #1336, #987, #746,

**Comment by eluchsinger** [comment]
The files are in the Sharing docs not the Input docs.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
