### ISSUE TITLE
UNET Spectator View Sample

### ISSUE THREAD

**Issue by LexieMeng** [Microsoft/MixedRealityToolkit-Unity#1448]
## Overview
When moving the camera which are attached to the hololens rig, the screen which are live streaming the sharing session inside the spectator view compositor are sticking to the compositor screen. It does not move like a 3D hologram in a 3D space but instead it is just like a picture sticking to the compositor screen.

## Expected Behavior
The 3D holograms should not move but stay in the 3D space just like a normal hologram.
## Actual Behavior
The 3D holograms move when i try to move the camera rig and rotate to take picture in a different angle
## Unity Editor Version
5.6.2f1
## Mixed Reality Toolkit Release Version
5.6.2f1

**Comment by StephenHodgson** [comment]
This issue probably belongs in the [MixedRealityCampanionKit](https://github.com/Microsoft/MixedRealityCompanionKit)

**Comment by Holo1Tero** [comment]
hello Will this problem be solved, I also met a similar situation

**Comment by Holo1Tero** [comment]
hello Will this problem be solved, I also met a similar situation
