### ISSUE TITLE
Unable to interact with UI elements in the Hololens

### ISSUE THREAD

**Issue by dlionz** [Microsoft/MixedRealityToolkit-Unity#1451]
## Overview
In my project, I have a list of UI Buttons that when click will execute a function that teleports the camera position. In the Unity editor, this functionality works as expected however when deployed to the Lense clicking my buttons only seems to refresh the button list.

I thought this was an issue with the RaycastCamera naming but I changed the camera name to UIRaycastCamera and this didn't solve my problem. 

Is this an issue on my end or is it a problem with the Toolkit?

Thank you

## Expected Behavior
Building to the Lense and air tapping UI buttons should perform onClick function associated 

## Actual Behavior
Building to the Lense and air tapping UI buttons causes button list refresh and no event 

## Steps to reproduce
_(Links to sample github project preferred)_
Build scene with Mixed reality menu item config setup, create UI canvas buttons with onClick functions, deploy to Hololense  

## Unity Editor Version
2017.2.0F3

## Mixed Reality Toolkit Release Version
Current

(Please let me know if this is the correct place for this)

**Comment by StephenHodgson** [comment]
This is fixed in the dev branch and will be addressed with the next release.

**Comment by LaneMax** [comment]
Is there an easy fix for this problem without using the Dev Branch?

**Comment by StephenHodgson** [comment]
You could always take a look at the PR and make those changes in your code

**Comment by dlionz** [comment]
Hey, @LaneMax I found that using the latest release https://github.com/Microsoft/MixedRealityToolkit-Unity/releases gave me pretty good results as well as adding Mesh Colliders to my UI elements.

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
