### ISSUE TITLE
Position is off when user click on a slider or keyboard inputfield by using motion controller.

### ISSUE THREAD

**Issue by song1shuai** [Microsoft/MixedRealityToolkit-Unity#1454]
## Overview
Once i click on the UGUI slider or inputfield on keyboard by using motion controller, slider handle or caret move to a weird position(have not test the behavior by using xbox controller).
## Expected Behavior
The silder handle  or caret should move to the position where you clicked.
## Actual Behavior
The slider or caret move to a weird position.
## Steps to reproduce
Under KeyboardTest scene , add a ugui slider under sceneContent/KeyboardTestCanvas. 
pos(0,0,2) width(1600) ,height(200) , then move the cursor to the slider, click on the 
trigger button on the motion controller.
## Unity Editor Version
2017.2.0.p1-MRTP4
## Mixed Reality Toolkit Release Version
Current

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
