### ISSUE TITLE
GesturesInput.cs missing?

### ISSUE THREAD

**Issue by BaconKnight** [Microsoft/MixedRealityToolkit-Unity#1459]
## Overview
Tried to use the InputManager prefab, but none of the gestures worked. When i checked the scripts attached to the prefab I noticed that the GesturesInput.cs script is missing. Didnt find it anywhere in the toolkit

## Unity Editor Version
2017.1.0f3
## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-v1.2017.2.0

**Comment by StephenHodgson** [comment]
You should be using `InteractionInputSource`

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
