### ISSUE TITLE
Restore MicStreamSelector.dll to Input/Plugins

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#1460]
## Overview
MicStreamSelector.dll was moved from Input/Plugins into the Examples tree.

## Expected Behavior
MicStreamSelector.dll to be part of the Input tree.

## Actual Behavior
MicStreamSelector is not part of the core toolkit.

## Mixed Reality Toolkit Release Version
2017.2.x

**Comment by StephenHodgson** [comment]
Agreed, but we should make this change when the signed dlls are updated and addressed

**Comment by davidkline-ms** [comment]
What specific updates are you looking for before adding it back?

**Comment by StephenHodgson** [comment]
@keveleigh should know more about this.

**Comment by keveleigh** [comment]
Fixed via #1670

**Comment by davidkline-ms** [comment]
Thank you, Kurtis!
