### ISSUE TITLE
Motion Controller Tutorial Question

### ISSUE THREAD

**Issue by GT3000** [Microsoft/MixedRealityToolkit-Unity#1465]
This is more of a question but when are we gonna see tutorials for use of the Motion Controllers? The documentation (bless your heart for updating as much as you have) is really not helping me understand how to utilize them in my project. 

Thanks.

**Comment by Railboy** [comment]
Our Mixed Reality 213 tutorial is about to be published. The tutorial will go live [here](https://developer.microsoft.com/en-us/windows/mixed-reality/academy) shortly. In the meantime you can dig into the project [here](https://github.com/Microsoft/MixedReality213).

**Comment by keveleigh** [comment]
MR213 is live at https://developer.microsoft.com/en-us/windows/mixed-reality/mixed_reality_213
