### ISSUE TITLE
Teleportation not working in GrabMechanics scene

### ISSUE THREAD

**Issue by jcurrio** [Microsoft/MixedRealityToolkit-Unity#1466]
## Overview
All the expected functionality is there (grabbing, rotating etc boxes,) however the teleportation target does not appear.

## Unity Editor Version
2017.2.0f3

## Mixed Reality Toolkit Release Version
v1.2017.2.0

**Comment by keveleigh** [comment]
I'm not able to repro this. Are you getting any errors?

![image](https://user-images.githubusercontent.com/3580640/33498698-2e038610-d687-11e7-9e99-160db66ff3f7.png)

**Comment by jcurrio** [comment]
Thanks for looking into it @keveleigh.  I just started a new project and re-imported the asset packages and it's working.  I was previously trying to modify the existing scene, so maybe I made a mistake somewhere along the line.  Thanks again

**Comment by jcurrio** [comment]
Scratch the most recent post.  I added an .obj model I had created and then the teleportation no longer worked.  So I thought it was because of the model (not sure why?).  And then I just created another new project, imported the asset packages and the teleportation didn't work.. So I'm not sure what's going on, there weren't any errors

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
