### ISSUE TITLE
XRSettings.eyeTextureResolutionScale has no impact

### ISSUE THREAD

**Issue by raedbenz** [Microsoft/MixedRealityToolkit-Unity#1467]
I am trying to set XRSettings.eyeTextureResolutionScale in a Lenovo IHMD sample app built with latest dev MRTK and MRTP5 but it seems has no effect.
I need it to tweak SSAA.

When i try it on Unity 2017.2 on HTC Vive device using the[ RenderScale scene](https://github.com/OSVR/Unity-VR-Samples/tree/master/Assets/VRSampleScenes/Scenes/Examples) it works and aliasing quality is improved.
Please advise. Thanks

**Comment by StephenHodgson** [comment]
You should probably open report with Unity.

**Comment by raedbenz** [comment]
I am not sure whether is allowed in windows mixed reality.
https://developer.microsoft.com/en-us/windows/mixed-reality/performance_recommendations_for_immersive_headset_apps#default_render_target_size
