### ISSUE TITLE
Where are MRT Live Stream Series 003-005 on youtube?

### ISSUE THREAD

**Issue by reillydonovan** [Microsoft/MixedRealityToolkit-Unity#1470]
Hi, I was wondering where the mixed reality toolkit live stream videos for 003-005 are on youtube, I see 1,2 and 6.  I would love to dive into 004 where you cover the sharing service and anything to do with custom messages.  Please let me know, cheers!

**Comment by StephenHodgson** [comment]
Well, my live steam videos don't aren't really connected directly to this repository 😆 

I haven't' had time to edit them down cause of the Holidays and such.

**Comment by reillydonovan** [comment]
Oh sorry!  I know you are busy but Would you be able to publish the videos before the holidays at all? Even unedited? The topics covered in them would be very helpful for me for a project I’m working on as I’ve spent a week trying to reverse engineer the sync system and custom messages with limited success. Pretty please? :) thank you so much stephen and happy holidays!

**Comment by StephenHodgson** [comment]
I'll do my best.  You can find them, but I think they're currently unlisted.

**Comment by reillydonovan** [comment]
Great thanks so much Stephen I really appreciate it! Would you be able to share the unlisted address or should I just google search until I get the right keyword for the unlisted video?
