### ISSUE TITLE
SharingWorldAnchorManager NRE

### ISSUE THREAD

**Issue by eluchsinger** [Microsoft/MixedRealityToolkit-Unity#1473]
I've got a `NullReferenceException` in the following line of the `SharingWorldAnchorManager` class.
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/405bb16be62b5d1eb18f8e5f39d9d1fe9a962013/Assets/HoloToolkit/Sharing/Scripts/Utilities/SharingWorldAnchorManager.cs#L668

The parameter `data` is empty. The Call Stack tells me it is being called from an external assembly from the method `HoloToolkit.Sharing.SharingWorldAnchorManager.ExportComplete`. I can't quite follow where the method is called there.

>	Assembly-CSharp.dll!HoloToolkit.Sharing.SharingWorldAnchorManager.ExportComplete(UnityEngine.XR.WSA.Sharing.SerializationCompletionReason status) Line 667	Unknown	Symbols loaded.

What could be the reason for this NRE? Is this method called from an external library or from line 133:
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/405bb16be62b5d1eb18f8e5f39d9d1fe9a962013/Assets/HoloToolkit/Sharing/Scripts/Utilities/SharingWorldAnchorManager.cs#L133

Do we have to implement an error handling for this? The whole sharing story isn't working very reliable.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
