### ISSUE TITLE
Runtime Error with SpectatorView 1.5.7.0 UNET and Holotoolkit 1.5.7.0 sharing.

### ISSUE THREAD

**Issue by eirikhollis** [Microsoft/MixedRealityToolkit-Unity#1474]
## Overview
Immediate crash when pressing play on Unity 5.6.2f1 with SpectatorView_1_5_7_0_UNET and HoloToolkit-Unity-v1.5.7.0:

```
Microsoft Visual ++ Runtime Library
Program:

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

[Image](https://imgur.com/uBluRSv)

Everything was working perfectly. I built and deployed to the Hololenses and everything ran perfectly. However, I had miss-typed the server IP and quickly corrected it before building and deploying in the same manner. But now the application crashes on the hololenses, as well as in the editor with the error above. No logs are outputted.
I rebuilt the project from scratch and experienced the same error. I tried running the project on a different computer, same error.

I've tried researching the problem, but it seems oddly specific. I know that it probably doesn't fit the current issue list on here, but the issue section on the CompanionKit is immensely dead and low-populated. Was hoping any of you had experienced, and hopefully solved, this issue before.

## Expected Behavior
Plays with no error, or at least some error I can debug,

## Actual Behavior
Crashes immediately with no detailed error or logs, as shown in this [picture](https://imgur.com/uBluRSv).

## Steps to reproduce
[Spectator View 1.5.7.2 UNET](https://github.com/Microsoft/MixedRealityCompanionKit/releases/tag/1.5.7.2_UNET)
[HoloToolkit-Unity-v1.5.7.0](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/v1.5.7.0)

New project -> Import HoloToolkit -> Set up prefabs/project/scene/target UWP/capabilities to hololens -> Import SpectatorView_1_5_7_0_UNET -> Add SpectatorViewManager and sharing prefab -> copyDLLs from building compositor.sln to the asset folder -> copy calbrationData.txt to asset folder -> input correct IPs -> Press play.

## Unity Editor Version
5.6.2.f1

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-v1.5.7.0

**Comment by keveleigh** [comment]
Are you still seeing this issue? Especially when using more recent Unity/Toolkit versions.

Additionally, Spectator View is being [updated to remove the Toolkit dependency](https://github.com/Microsoft/MixedRealityCompanionKit/pull/271), allowing app developers to use whichever Toolkit version they like without needing to match.

**Comment by Yoyozilla** [comment]
Bulk closing older HTK bug. Please reopen if you can repro this issue in MRTK v2. 
Thanks!
Yoyo
