### ISSUE TITLE
Check if UNITY_WSA in AttachToController

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#1475]
## Overview
Loaded current dev branch and receive two errors on attempting to build.

First error (see below) is presumably a missing reference in AttachToController. Can be fixed by adding a using statement:

    using UnityEngine.XR.WSA.Input;
## Expected Behavior
No errors.

## Actual Behavior
Errors.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'InteractionSourceHandedness' could not be found (are you missing a using directive or an assembly reference?)	MixedRealityToolkit-Unity	MixedRealityToolkit-Unity\Assets\HoloToolkit\Input\Scripts\Utilities\AttachToController.cs	17	Active
```
## Steps to reproduce
Build current dev branch.

## Unity Editor Version
2017.2.0p2-MRTP5

## Mixed Reality Toolkit Release Version
Dev working branch

**Comment by genereddick** [comment]
Broke these into two bug reports

**Comment by StephenHodgson** [comment]
I wasn't able to duplicate this with the current dev branch checkout 6d49ddacd434bf686e4e188e02a1f5b2e871d570

**Comment by keveleigh** [comment]
I believe this happens when the project is targeted to anything besides UWP.

**Comment by StephenHodgson** [comment]
The Fix
```
    public class AttachToController : MonoBehaviour
    {
#if  UNITY_WSA && UNITY_2017_2_OR_NEWER
        public InteractionSourceHandedness Handedness { get { return handedness; } }

        [Header("AttachToController Elements")]
        [SerializeField]
        protected InteractionSourceHandedness handedness = InteractionSourceHandedness.Left;

#endif
```

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
