### ISSUE TITLE
Reference from HoloToolkit to HoloTookit-Examples breaks build

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#1476]
**Overview**
Loaded current dev branch and receive two errors on attempting to build.

The second error (see #1475  for the first) is in MicrophoneHelperSample. In this case, the MicrophoneHelper Sample class exists in the main project, HoloToolkit, but has a reference to MicrophoneHelper which is in HoloToolkit-Examples. If you don't have HoloTookit_Examples in your project you receive the error.

**Expected Behavior**
Either MicrophoneHelperSample is moved to HoloTookit-Examples or MicrophoneHelper is moved to HoloTookit.

**Actual Behavior**
Errors.

Error CS0103 The name 'MicrophoneHelper' does not exist in the current context Assets\HoloToolkit\Input\Scripts\Utilities\MicrophoneHelperSample.cs 28 Active

**Steps to reproduce**
(Links to sample github project preferred)
Build current dev branch.

**Unity Editor Version**
2017.2.0p2-MRTP5

**Mixed Reality Toolkit Release Version**
Dev working branch

**Comment by keveleigh** [comment]
Ahh hmm, it looks like the sample script was put into the main toolkit, while the actual script was put into the examples folder. I can put out a PR swapping them.

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
