### ISSUE TITLE
Ship MRTK release packages to the Unity asset store

### ISSUE THREAD

**Issue by MarjanPl** [Microsoft/MixedRealityToolkit-Unity#1484]
Readme / Landingpage on Github states:

Unity packages for each release will be published to the Unity asset store.

What? Where? When? Just searched the asset store for Mixed, reality, toolkit, mixedreality, microsoft etc. Did not find anything. Wrong information?

**Comment by NeerajW** [comment]
This is part of the roadmap and we are very close to doing this. We need to sign binaries in order for us to ship these packages. Will use this issue to track that work.

**Comment by StephenHodgson** [comment]
Pretty sure this is a duplicate?

**Comment by davidkline-ms** [comment]
Definitely on my radar for the May release (2017.4.0.0)

**Comment by FlorianJa** [comment]
are there any news?

**Comment by StephenHodgson** [comment]
Good question.

**Comment by davidkline-ms** [comment]
Still on the radar... I will try to make it happen for the 2017.4.1.0 release

**Comment by StephenHodgson** [comment]
@davidkline-ms remember to name it HTK not MRTK in the asset store for the 2017.4.1.0 release

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
