### ISSUE TITLE
Unity Version for Hololens AND MR?

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1487]
Which version of Unity incorporates both, Hololens and MR to use with the Toolkit? Or when will a version be released capable of that?

**Comment by eirikhollis** [comment]
From Readme:

_Note: The latest release should work for both HoloLens and Windows Mixed Reality development._

[github-rel]:                    https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/latest
[mrtk-version-badge]:            https://img.shields.io/github/tag/microsoft/MixedRealityToolkit-unity.svg?label=Latest%20Master%20Branch%20Release&colorB=9acd32
[![Github Release][mrtk-version-badge]][github-rel]

[unity-download]:                 http://beta.unity3d.com/download/b1565bfe4a0c/download.html
[unity-version-badge]:            https://img.shields.io/badge/Current%20Unity%20Editor%20Version-2017.2.0p1%20MRTP4-green.svg
[![Github Release][unity-version-badge]][unity-download]

**Comment by Alexees** [comment]
@eirikhollis yes, I stumbled upon this entry too. But looking into the next page behind the master branch it says:

Window Mixed Reality developers use Unity Editor 2017.2.0p1 MRTP 4
When building for Windows Mixed Reality target 10.0.16299 SDK.
HoloLens developers use Unity Editor 2017.1.2
When building for HoloLens be sure to target the 10.0.15063 SDK.

I think the Note states that the Holotoolkit will work with both, but not that there's a single version of Unity with which both can be addressed. I'm looking for that Unity version.

**Comment by Mudbelly** [comment]
I also found that confusing.

**Comment by jimm98y** [comment]
How about the SharingWorldAnchorManager? It seems to be compile-switched out for the latest version of Unity. Does it mean that after we finally made sharing working in our app, we will lose the functionality after upgrading to the latest version of the toolkit? What options do we have to keep the sharing working AND supporting the mixed reality headsets at the same time?

**Comment by StephenHodgson** [comment]
With the latest master branch release, you can use 2017.2+ to do both HoloLens and Immersive Headset Work.  The next release will also be the same way.

**Comment by Alexees** [comment]
@StephenHodgson thanks. I tried using 2017.2 MRTP5 and it seemed to work. Case closed

**Comment by StephenHodgson** [comment]
I suggest using the latest Dev_Branch for some fixes to the HoloLens input for uGUI tho, if you need it.

**Comment by Alexees** [comment]
@StephenHodgson thanks for that suggestion. Unfortunately the UI is handled when using Holographic Emulation but as soon as it's built to the device those same uGUI elements do not work.

**Comment by NeerajW** [comment]
I believe this issue has been solved since. Same unity builds for both. Please reopen with any other issues in case this did not get solved.
