### ISSUE TITLE
Do not clear all anchors

### ISSUE THREAD

**Issue by mabuchner** [Microsoft/MixedRealityToolkit-Unity#1488]
## Overview

I'm writing a Unity plugin, which uses `WorldAnchor`s to communicate with our native code. By itself this works fine, but in combination with the `WorldAnchorManager`, `SharingWorldAnchorManager` or `ImportExportAnchorManager` of the MixedRealityToolkit, the saved anchors do not arrive in the native code.

## Expected Behavior

A `WorldAnchor` saved via `WorldAnchorStore.Save` inside the callback from `WorldAnchorStore.GetAsync` should be available, if it was saved successfully.

## Actual Behavior

The `WorldAnchorManager`, `SharingWorldAnchorManager` and `ImportExportAnchorManager` clear all anchors inside the callback from `WorldAnchorStore.GetAsync`:
* https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/405bb16be62b5d1eb18f8e5f39d9d1fe9a962013/Assets/HoloToolkit/Utilities/Scripts/WorldAnchorManager.cs#L130
* https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/405bb16be62b5d1eb18f8e5f39d9d1fe9a962013/Assets/HoloToolkit/Sharing/Scripts/Utilities/SharingWorldAnchorManager.cs#L163
* https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/2acbb55496aa689541be74f5e4b4f9bfe49b249a/Assets/HoloToolkit-Examples/Sharing/SharingService/Scripts/ImportExportAnchorManager.cs#L694

Depending on the execution order of the callbacks and our native code, the previously successfully saved `WorldAnchor` might not be available. Whether the `WorldAnchor` can be retrieved or not, seems to be quite random.

## Steps to reproduce

Create a GameObject and attach a new script to it, which
1. retrieves the `WorldAnchorStore` using `WorldAnchorStore.GetAsync` function during the `Start` function.
2. adds a `WorldAnchor` component to the current GameObject and saves it using `WorldAnchorStore.Save` inside the callback from `WorldAnchorStore.GetAsync`.
3. waits until the `WorldAnchorStore` was retrieved and then tries to access the saved anchor during the `Update` call. For example it could try to call `WorldAnchorStore.Delete` with the name of the anchor.

Add the `WorldAnchorManager` script to any GameObject.

After deploying the application to the HoloLens, the `WorldAnchorStore.Delete` call will then fail, if the `WorldAnchorStore.GetAsync` callbacks of the MixedRealityToolkit were processed after the callback of the new script.

## Notes

We don't want to have the MixedRealityToolkit as a dependency of our plugin. Therefore we can't use the `WorldAnchorManager` instead of the `WorldAnchorStore`. However, users of our plugin are free to use the MixedRealityToolkit. The MixedRealityToolkit therefore shouldn't globally delete all anchors.

## Unity Editor Version

Unity 2017.2.0f1

## Mixed Reality Toolkit Release Version

v1.2017.2.0

**Comment by PJBowron** [comment]
Apologies if I'm misunderstanding your problem, but can't clients who are using the MRTk components just set the `PersistentAnchors` Boolean? This will prevent the `Clear()` occurring.

**Comment by mabuchner** [comment]
Yes, but this does not work for users, which do not want persistent anchors.

**Comment by mabuchner** [comment]
Maybe some further explanation to clarify this issue:
* I‘m using the WorldAnchor**Store** to save my anchors. The WorldAnchor**Store** is part of Unity.
* Our clients are using the WorldAnchor**Manager** in any configuration (persistent or non-persistent) they want. The WorldAnchor**Manager** is part of the MixedRealityToolkit.

By blindly erasing all anchors the current implementation of the WorldAnchor**Manager** interferes with other code using the WorldAnchor**Store**.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
