### ISSUE TITLE
What's with the name of the stabilization branch?

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1489]
v2017.2.0.1-Stabilization?

I thought we were dropping the v prefix on the releases?

Also, shouldn't it be 2017.2.1.0 as it'll most likely reflect the new release Unity will have by the time we approve it?

**Comment by keveleigh** [comment]
I copied the tag from your release draft. Certainly that can change between now and then.

If a new Unity release happens, we can address that. The branch name doesn't lock us into a tag.

I mistakenly kept the `v` this time, but, again, the branch name doesn't lock us into a release tag.

**Comment by StephenHodgson** [comment]
No worries, just asking.

**Comment by keveleigh** [comment]
All good! I wanted to try to answer as thoroughly as possible.
