### ISSUE TITLE
Trouble with xbox one Controller

### ISSUE THREAD

**Issue by humpalum** [Microsoft/MixedRealityToolkit-Unity#1490]
## Overview
In our project we use the Xbox controller input. However, some of the buttons don't function correctly. For example, the right trigger always returns -1 instead of the correct value.
It actually works in the Unity Editor, but after deploying it on the Hololens, stuff gets weird.

## Expected Behavior
Right Trigger should return Value between 0 and 1

## Actual Behavior
Returns -1. 

Additionally, the actual action we want to perform, is somehow mapped on the left-Dpad Button.

 
## Steps to reproduce

Our xbox gameobject with all the handlers:

![grafik](https://user-images.githubusercontent.com/11175099/33757747-c4cce8ec-dbfb-11e7-846e-1468077d0ca7.png)

Part of the custom Handler Script.
```
    public override void OnXboxAxisUpdate(XboxControllerEventData eventData)
    {
        GazeInput GI = GazeInput.Instance;

        // Grab with A Button
        if (eventData.XboxA_Down)
        {
            GI.toggleGrab();
        }

        // Move Object further away or closer
        if (eventData.XboxRightTriggerAxis != 0.0)
        {
            GI.pushbackObj(eventData.XboxRightTriggerAxis);
        }
        if (eventData.XboxLeftTriggerAxis != 0.0)
        {

            GI.pullbackObj(eventData.XboxLeftTriggerAxis);
        }


        //ROTATE STUFF
        if (eventData.XboxLeftStickVerticalAxis != 0)
        {
            GI.rotateX(eventData.XboxLeftStickVerticalAxis);
        }
        else
        {
            GI.rotateX(0f);
        }
        if (eventData.XboxLeftStickHorizontalAxis != 0)
        {
            GI.rotateY(eventData.XboxLeftStickHorizontalAxis * -1);
        }
        else
        {
            GI.rotateY(0f);
        }

        if (eventData.XboxLeftBumper_Pressed)
        {
            GI.rotateZ(1f);
        }

        if (eventData.XboxRightBumper_Pressed)
        {
            GI.rotateZ(-1f);
        }
        if (eventData.XboxLeftBumper_Pressed == false && eventData.XboxRightBumper_Pressed == false)
        {
            GI.rotateZ(0f);
        }

        // Grab with A Button
        if (eventData.XboxX_Down)
        {
            GI.repositionCanvas(uiCanvas);
        }

        if (eventData.XboxView_Down)
        {
            Debug.Log("Sel");
            GI.repositionDebugWindow(debugWindow);
        }

    }
```

## Unity Editor Version
unity 2017.2.0f3

## Mixed Reality Toolkit Release Version
Unity 2017.2.0p1 MRTP4

**Comment by StephenHodgson** [comment]
Be sure to check this out and see if this solves some of the issues you're having:
https://developer.microsoft.com/en-us/windows/mixed-reality/hololens_known_issues#xbox_wireless_controller

**Comment by humpalum** [comment]
Still having this problem. Updated to MRTK Version 2017.2.1.4 and reapplied all settings. Checked for updates for the Xbox Controller. Further, we updated the HoloLens
The behavior is still the same: 
DPAD Mapped to Right Trigger,
Right Stick doesn't do anything,
Trigger only control the shared triggers.

Again, you can check the behavior in this short videoclip:
https://youtu.be/jLdp97GnPYk



Here are some screenshots that show our settings:
Status of Controller Fiemware
![1](https://user-images.githubusercontent.com/11175099/39521036-21b10600-4e0d-11e8-97ec-68bf26011735.jpeg)
![2](https://user-images.githubusercontent.com/11175099/39521041-23ae95bc-4e0d-11e8-81b2-76c68f33a4df.jpeg)

HID capability set:
![3](https://user-images.githubusercontent.com/11175099/39521050-2f89da18-4e0d-11e8-8707-3ec570cbd6ca.jpeg)

Which settings we applied:
![4](https://user-images.githubusercontent.com/11175099/39521064-3e6d7742-4e0d-11e8-92a6-b2501a5cc36b.jpeg)



Any further advices you can give us to make this work?

**Comment by StephenHodgson** [comment]
Can't do anything until unity backports the fixes to the controller.

https://fogbugz.unity3d.com/default.asp?1008255_u69q2vd4agsn6i21

**Comment by humpalum** [comment]
Thanks for the Update!
 Seems like we need to wait for Unity to patch Unity.2018 out of beta.
