### ISSUE TITLE
SceneContentAdjuster does not compile in Unity 5.6

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1492]
# Overview
When opening the project in Unity Editor 5.6, the Scene `ContentAdjuster` class raises errors about `XRDevice` and unreachable code.

# Unity Editor
5.6
2017.1

# MRTK version
dd2eb2e36a34cc7fa3a16f59f570ca51ab977694

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
