### ISSUE TITLE
WorldAnchor Sharing not working between hololens devices in 2017.2.0 toolkit!!.

### ISSUE THREAD

**Issue by ARUNVSHIV** [Microsoft/MixedRealityToolkit-Unity#1498]
## Overview
WorldAnchor Sharing not working!!.

## Expected Behavior
share World anchor for holograms!!.
## Actual Behavior
Sharing seems to work, but not Anchor sharing!!.
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2017.1.2f1

## Mixed Reality Toolkit Release Version
2017.2.0

**Comment by StephenHodgson** [comment]
Hi!  Please provide a more detailed explanation of the issue you're having, and also a list of steps to use to reproduce the issue.

Thanks.

**Comment by ARUNVSHIV** [comment]
I was checking the SharingTest scene in the Holotoolkit tests project. The debug text shows the importing and exporting of the anchor but the sphere position is not shared across the devices. Sharing schema version is 17 btw.

**Comment by Alexees** [comment]
We successfully ran the SharingWithUNET scene on two lenses today. This issue is there's one should be fixed alright, but for the time being that scene might help you get going

**Comment by ARUNVSHIV** [comment]
Okai, Thanks for Helping Alexees!!.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
