### ISSUE TITLE
NetworkDiscoveryWithAnchors doesn't start being a server on its own

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1499]
## Overview
The only method (MaybeInitAsServer ) within NetworkDiscoveryWithAnchors that's supposed to switch from client to being the server after a certain time not receiving a broadcast is private and nowhere called. Furthermore, there's no time wait anywhere where the call could be put. One more: InitAsServer, that's called as a coroutine from MaybeInitAsServer does a few yields related to the hololens needing them, while the one other method StartHosting, doesn't.

## Expected Behavior
One should be able to use the script with a configurable interval, after which the client starts being a server.

## Actual Behavior
Script starts as client, that's it.

## Unity Editor Version
MRTP5

## Mixed Reality Toolkit Release Version
Latest dev branch

**Comment by StephenHodgson** [comment]
I'm not familiar with this class, is it in the Sharing With Unet Examples?

**Comment by FlorianJa** [comment]
In the HoloToolkit-Unity-v1.2017.1.2 release the start method looked like this

```
private void Start()
        {
            // Initializes NetworkDiscovery.
            Initialize();

            if (!CheckComponents())
            {
                Debug.Log("Invalid configuration detected. Network Discovery disabled.");
                Destroy(this);
                return;
            }

            broadcastInterval = BroadcastInterval;

            // Start listening for broadcasts.
            StartAsClient();

            // But if we don't get a broadcast after some time we'll start broadcasting.
            // We randomize how long we wait so that we reduce the chances that everyone joins at
            // once and decides that they are the server.  
            // An alternative would be to create UI for managing who hosts.
            float invokeWaitTime = 3 * BroadcastInterval + Random.value * 3 * BroadcastInterval;
            Invoke("MaybeInitAsServer", invokeWaitTime * 0.001f);
        }
```

The last two lines are missing in the method right now.

**Comment by Alexees** [comment]
@FlorianJa thanks for that. I guess the class wasn't properly rewritten than. Thanks

**Comment by StephenHodgson** [comment]
I'd probably replace `Invoke("MaybeInitAsServer", invokeWaitTime * 0.001f);` with a co-routine so that the method name is a symbol instead of a string reference.

**Comment by rafek** [comment]
I would put this:

```csharp
StartCoroutine(MaybeInitAsServer());
```

right after `StartAsClient();`

and would change `MaybeInitAsServer()` to the following:

```csharp
private IEnumerator MaybeInitAsServer()
{
    yield return new WaitForSeconds(5.0f);

    if (TryBroadcasting)
    {
         yield return InitAsServer();
     }
}
```

where `TryBroadcasting` would be `true` by default and changed to `false` whenever a broadcast is received by the client.

**Comment by rolandsmeenk** [comment]
Looks like some changes happened when examples were moved out of the Holotoolkit. Although the commit says "File renamed without changes. " the way the new NetworkDiscoveryWithAnchors works is different from the original. The original version was more an automatic host/client setup and with a join of the first session. The new version is building a list of sessions to be displayed in a UI and then let the user select which session to join. Maybe we should create two different NetworkDiscovery classes for this.

**Comment by keveleigh** [comment]
Luckily, not a result of the movement of the scripts into Examples ("File renamed without changes" is accurate).

This file has existed in its current form in the dev branch starting on May 31, 2017: https://github.com/Microsoft/MixedRealityToolkit-Unity/commits/8066264cad070f25094bdc79110ef827d08c292b/Assets/HoloToolkit/SharingWithUNET/Scripts/NetworkDiscoveryWithAnchors.cs

It didn't get merged into master until last October or so. The GitHub history is slightly misleading, since it doesn't contain merge commits (or the commit that deleted the file in Examples originally, for some reason).

The current version matches what's used in MR250. I'll take a look at the differences and potentially re-implementing the original behavior.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
