### ISSUE TITLE
Failed to get pointer data. Error code: '0x80004005'.

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1500]
## Overview
Developing for MR Headset (Acer), when you run the scene from the editor, have the HMD tilted up and the motion controller on the table, after a few seconds the console gets spammed with these warnings.

## Expected Behavior
no warnings, the controller is just out of sight.

## Actual Behavior
spam

## Unity Editor Version
MRTP5

## Mixed Reality Toolkit Release Version
latest Dev Branch

**Comment by StephenHodgson** [comment]
Can you please provide the output for us to see?

**Comment by Alexees** [comment]
What do you mean by output other than "Failed to get pointer data. Error code: '0x80004005'"

**Comment by StephenHodgson** [comment]
So then there's no stack trace?

**Comment by StephenHodgson** [comment]
No reproduction steps?

**Comment by Alexees** [comment]
I'm afraid not. Here:

![screenshot 15](https://user-images.githubusercontent.com/32508825/33930371-f85bb428-dfec-11e7-9c51-069b76115877.png)

**Comment by Alexees** [comment]
While these errors occur,, the InteractionManager just goes haywire, sending every event every frame (PointerUp, PointerDown...)

**Comment by Alexees** [comment]
Filed a bug report: Case 978556

**Comment by davidslight** [comment]
I have this error just running the MotionControllerTest scene - error is followed by 

transform.localRotation assign attempt for 'LeftController' is not valid. Input rotation is { 0.000000, 0.000000, NaN, 0.000000 }.
UnityEngine.Transform:set_localRotation(Quaternion)
HoloToolkit.Unity.InputModule.MotionControllerVisualizer:UpdateControllerState() (at Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs:168)
HoloToolkit.Unity.InputModule.MotionControllerVisualizer:Update() (at Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs:105)

**Comment by Alexees** [comment]
This has been fixed by Unity as far as the mails go that I received. But, as usual, there's no version I could tell this has been fixed with
