### ISSUE TITLE
Unity 2017.2.0p1-MRTP4 , Unity 2017.2.0b11 crashes in Play mode for Windows Mixed reality(tried with Samsung)!!.

### ISSUE THREAD

**Issue by ARUNVSHIV** [Microsoft/MixedRealityToolkit-Unity#1501]
## Overview
Crashes on Play mode in Unity 2017.2.0p1-MRTP4  , was working fine previously , but crashes from Dec 7th , when playmode is enabled, with Windows Mixed reality device is connected and Mixed reality Portal is awake !!. 
My project was a UWP app, works without crash in Unity 2017.1.2f1 for Hololens support!!.

## Expected Behavior
should able to play without crashing!!.

## Actual Behavior
Crashes on Play, Windows Mixed reality is connected !!.

## Unity Editor Version
2017.2.0p1-MRTP4   , 2017.2.0b11
## Mixed Reality Toolkit Release Version
Master 2017.2.0 

attached crash log file!!.
[error.log](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/1547522/error.log)

**Comment by cre8ivepark** [comment]
One thing you can check - make sure 'Window > Holographic Emulation' is turned off. This caused crashes for the immersive headset.

**Comment by ALARUNVIGNESH** [comment]
Thank Yu, cre8ivepark , I'll give a try!!.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
