### ISSUE TITLE
Error: Input Button CONTROLLER_LEFT_Menu is not setup 

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#1503]
## Overview
I'm getting this error in an existing project when I update to the latest dev branch. It wasn't there prior to the update.

## Expected Behavior
No error.

## Actual Behavior
Error:

ArgumentException: Input Button CONTROLLER_LEFT_MENU is not setup.
 To change the input settings use: Edit -> Project Settings -> Input
HoloToolkit.Unity.InputModule.XboxControllerInputSource.Update () (at Assets/HoloToolkit/Input/Scripts/InputSources/XboxControllerInputSource.cs:91)

## Steps to reproduce
_(Links to sample github project preferred)_
Update project to latest dev branch.

## Unity Editor Version
2017.2.0p2.MRTP5

## Mixed Reality Toolkit Release Version
v1.2017.2.0-dev

**Comment by StephenHodgson** [comment]
Be sure to make sure your editor input mapping is up to date.

**Comment by NeerajW** [comment]
This should be solved. Please reopen if that's not the case.
