### ISSUE TITLE
BoundaryManager should be disabled on HoloLens

### ISSUE THREAD

**Issue by timGerken** [Microsoft/MixedRealityToolkit-Unity#1504]
This code will fail when called on HoloLens. End result is the floor quad gets instantiated at (0,0,0) which is sub-optimal on a non-opaque device.

https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/f2596ee39d740f2eab1209c869ea1e55d0478a49/Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs#L87

**Comment by StephenHodgson** [comment]
@timGerken please use the issue format provided.

Which version are you using?

**Comment by timGerken** [comment]
sigh. apparently creating a new issue from a line of code doesn't use the "new issue" template path. sigh again.

**Comment by timGerken** [comment]
replaced by #1505
