### ISSUE TITLE
BoundaryManager should be disabled on HoloLens

### ISSUE THREAD

**Issue by timGerken** [Microsoft/MixedRealityToolkit-Unity#1505]
## Overview
This code will fail when called on HoloLens. End result is the floor quad gets instantiated at (0,0,0) which is sub-optimal on a non-opaque device.
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/f2596ee39d740f2eab1209c869ea1e55d0478a49/Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs#L87

## Expected Behavior
When on HoloLens, boundary manager is disabled

## Actual Behavior
When on HoloLens, boundary manager draws a floor quad at (0,0,0)

## Steps to reproduce
add MixedRealityCameraParent to a new unity project and run on HoloLens.

## Unity Editor Version
2017.2.0p2-MRTP5

## Mixed Reality Toolkit Release Version
branch v2017.2.0.1-Stabilization
SHA f2596ee39d740f2eab1209c869ea1e55d0478a49

**Comment by timGerken** [comment]
Updated issue as this occurs on both RS1 and RS4 based HoloLens

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
