### ISSUE TITLE
2017.2.1 released today

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1512]
[Latest release of the Unity Engine 2017.2.1.1f1](https://unity3d.com/unity/whats-new/unity-2017.2.1)

Haven't heard back from Unity in a while about the MRTP builds, so I'm unsure if that's a good thing or not.

**Comment by Strepto** [comment]
This seems to fix #1008 for me. This issue has been there in all MRTP builds as I have tested.

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
