### ISSUE TITLE
Keyword Manager Component

### ISSUE THREAD

**Issue by Mudbelly** [Microsoft/MixedRealityToolkit-Unity#1513]
## Overview
Looking to add component keyword manager in hololens but when I search add component it does not show up.

## Unity Editor Version
Unity Editor 2017.1.2f1
## Mixed Reality Toolkit Release Version
Latest Toolkit : MixedRealityToolkit-Unity-1.2017.2.0

**Comment by StephenHodgson** [comment]
There is no such thing as a "Keyword Manager", but you can use `SpeechInputHandler` and `SpeechInputSource` for getting voice data.

**Comment by Mudbelly** [comment]
Did it ever exist? Because I've seen it in a few tutorials, even on Microsofts academy tutorial it was there

**Comment by firativerson** [comment]
@Mudbelly  Yes I was using it in my old project. It was a cool compact script .

**Comment by StephenHodgson** [comment]
It was deprecated and removed.  The `SpeechInputHandler` and `SpeechInputSources` replaced that script.

**Comment by NeerajW** [comment]
We are investigating bringing in a Standalone style folder which can host simple, clean scripts just like the KeywordManager used to be. Don't have a specific update just yet but will keep this open.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
