### ISSUE TITLE
Stabilization branch: Gaze highlight is broken with new shader applied to it

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/MixedRealityToolkit-Unity#1515]
## Overview
GamepadTest.unity test scene.

## Expected Behavior
We should see a highlight when we gaze over a test object.

## Actual Behavior
No highlight since the property being set in code which is _Highlight does not actually exist on the shader. This used to work with the correct shader in the past but I don't see it anywhere now.

## Steps to reproduce
Try running the above test scene.

## Unity Editor Version
2017.2.0p2 MRTP5

## Mixed Reality Toolkit Release Version
Stabilization branch for release.

**Comment by keveleigh** [comment]
The Academy has a [Specular Highlight shader](https://github.com/Microsoft/HolographicAcademy/blob/Holograms-210-Gaze/Completed/ModelExplorer/Assets/Resources/Shaders/SpecularHighlight.shader). Is this the one that was being used?

**Comment by NeerajW** [comment]
I have a fix with current shader.

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
