### ISSUE TITLE
Stabilization branch: Xbox controller does not work in GamepadTest.unity scene

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/MixedRealityToolkit-Unity#1517]
## Overview
Connected Xbox controller.
Unity remoting the test scene into immersive HMD.

## Expected Behavior
A press makes cube bigger.

## Actual Behavior
Nothing happens.

## Steps to reproduce
_(Links to sample github project preferred)_

**Comment by keveleigh** [comment]
Looks like GitHub didn't automatically close these issues when merged into master. I'll close these manually and look into why.
