### ISSUE TITLE
HoloToolKit.Unity.XdeGuestLocator - Failed to locate internal switch adapter 

### ISSUE THREAD

**Issue by Dmidcap** [Microsoft/MixedRealityToolkit-Unity#1519]
## Overview
I'm working on a Hololens project with two other developers. We're all on the same Unity version, and the toolkit files are in source control, so we are all using the same version of that as well. In the past, on an old version of HoloToolKit (before it was Mixed Reality Toolkit), I've been able to use "Build SLN, Build APPX, then Install" option on the Build Window to deploy to our Hololens. 

Recently I reinstalled windows on a new SSD, so I had a brand new installation of Visual Studio (VS2017 4.4.X or around there), Unity, and then made a fresh pull from our repository. When I try to build the Hololens app, I get the "Failed to locate internal switch adapter" error. This has happened on two completely different computers, but does not happen for my coworkers.

## What I've Tried
So far, I've tried a number of different options. I've updated Windows, Reinstalled Unity, checked my Visual Studio packages, tried at least two different versions of Visual Studio 2017, tried repairing Visual Studio, installing the Hololens Emulator, deleting CSPROJ/SLN files and regenerating them, and so on.

I've looked at this [old issue](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1330), but nothing from there seemed to help. I haven't tried upgrading/downgrading Unity yet because my coworkers aren't having any problems with the same version.

At this point, I'm wondering if there's just some small or more obvious thing that I can't think of that might explain the problem.

## Unity Editor Version
Unity 2017.2.0f3

## Mixed Reality Toolkit Release Version
2017.2.0

Thanks!

**Comment by StephenHodgson** [comment]
#1471 fixes this error from showing up in the editor.
