### ISSUE TITLE
Development input is not available outside the Editor

### ISSUE THREAD

**Issue by jwittner** [Microsoft/MixedRealityToolkit-Unity#1520]
We use the standalone windows builds for testing more clients in a shared experience without requiring more devices. I'd love to find a way so that this development input is kept in these builds, and if possible, enable it in my UWP application when launched on a desktop.

We don't want to ship these SKUs, just use them for testing network scenarios.

I'm thinking of adding a define, e.g. MRTK_DEVELOPMENT_INPUT, that if set in your player settings script defines would keep the development input enabled even outside the editor.

Thoughts?

**Comment by StephenHodgson** [comment]
I don't understand what you mean by "Development Input"

**Comment by jwittner** [comment]
Sorry, I'm referring to the mouse and keyboard controls that exist in the editor, but are removed from all the builds.

**Comment by StephenHodgson** [comment]
I was actually looking into making these inputs optional as well, but I think it'll be easier with a simple toggle, and not having to define something in the code anywhere.

It would just be another input source.

**Comment by StephenHodgson** [comment]
No, I was going to add input sources for each that people can add when they need them.

**Comment by jwittner** [comment]
I've had to modify CustomInputSource, AxisController, ButtonController, CustomInputControl, CustomInputSelector, and ManualGazeControl in order to get the input working on Standalone builds. You'd make new ones of each of these for each platform? I think I'm confused.

**Comment by StephenHodgson** [comment]
No, not a new one for each platform.

**Comment by jwittner** [comment]
I guess I'm trying to wrap my head around how making a new input source will solve the problems in the other classes.

**Comment by jwittner** [comment]
So we wouldn't be using any of the other classes in the new solution and we'd replace them with an implementation based on these new input sources? Am I following you right?

I was hoping to just make what we have work in Standalone builds. Ha.

**Comment by StephenHodgson** [comment]
Cause they won't derive from the old classes that use the UnityEditor namespace to get info.

These input sources should be first class citizens.

**Comment by jwittner** [comment]
I agree that we want keyboard and mouse input sources available as well, but I specifically want the behavior of what currently happens in the editor - just out of the editor. I'd like to avoid re-implementing that behavior with new input sources if possible. In your solution that is something I'd have to do right?

**Comment by StephenHodgson** [comment]
I'm also envisioning the inputs that mirror, simulate the Cliff house as well

**Comment by StephenHodgson** [comment]
> I'd like to avoid re-implementing that behavior with new input sources if possible. In your solution that is something I'd have to do right?

Well that's why we're brainstorming now, right? :p 
I'd like to have this without the need for devs to re-implement.  The way I'd like to do it is just have it on the InputManager prefab by default.

**Comment by jwittner** [comment]
So I got input working via the define in my project using a slightly older version of the MRTK and moved to the MRTK proper to apply the changes there. However, now I'm seeing in the MRTK (with no changes) that I can't air-tap when I'm on the PC platform. On UWP it opens the MR portal and let me drive input that way. Is the old floating hands input stuff all stripped out now?

**Comment by StephenHodgson** [comment]
> Is the old floating hands input stuff all stripped out now?

I'm unsure. This could have been a side effect of the Editor thinking you're using an occluded device, instead of a transparent one.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
