### ISSUE TITLE
Unity Editor starts massively lagging randomly

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1523]
## Overview
Once in a while the Unity Editor suffers from a severe performance drop due to FrameEvents.XRBeginFrame -> XR.WaitForGPU constantly consuming 95% of CPU time

## Expected Behavior
no performance drop

## Actual Behavior
severe drop

## Unity Editor Version
MRTP5

## Mixed Reality Toolkit Release Version
latest dev branch

![screenshot 17](https://user-images.githubusercontent.com/32508825/33988528-e4597cac-e0c4-11e7-9631-c9a85e06c0d6.png)

**Comment by StephenHodgson** [comment]
Did you open a bug report with Unity?
