### ISSUE TITLE
Fast Configurable Shader does not work for Per-Pixel Spotlights

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1524]
## Overview
Running a scene with a Pointlight facing straight down at a floor with a Fast Configurable Shader on it has problems with that light. Depending on the view direction and angle, is either on or off on that object.

## Expected Behavior
Light always works

## Actual Behavior
light turns on and off

## Unity Editor Version
MRTP5

## Mixed Reality Toolkit Release Version
latest dev branch

![screenshot 18](https://user-images.githubusercontent.com/32508825/33989480-00ee1730-e0c8-11e7-96ef-d8d4f2554aea.png)
![screenshot 19](https://user-images.githubusercontent.com/32508825/33989482-024839da-e0c8-11e7-9f0a-cef8adf911de.png)

**Comment by StephenHodgson** [comment]
@dbastienMS any input here?

**Comment by Alexees** [comment]
Another weird behaviour. whenever I point with the Motion Controller onto my UI Menu, the floor also looses its lighting.

**Comment by davidkline-ms** [comment]
Fast Configurable has been marked as obsolete and has been replaced with the Mixed Reality Toolkit / Standard shader
