### ISSUE TITLE
Namespace refactor work

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/MixedRealityToolkit-Unity#1527]
## Overview
Need to align folder name and namespace names to new branding.
Also fix/add things that are missing.

Suggestions:
1. Rename HoloToolkit folders -> MixedRealityToolkit verbiage.
2. Rename namespaces like HoloToolkit.Unity to:
MixedRealityToolkit.Input.<SubAreaAsNeeded>
MixedRealityToolkit.Common
MixedRealityToolkit.SpatialMapping etc.

**Comment by jessemcculloch** [comment]
@DDReaper - Hey Simon, here is the issue I talked to you about.  If you have any questions, feel free to tag myself or @NeerajW for guidance.

Thanks!

**Comment by DDReaper** [comment]
Great stuff, will refresh the latest dev branch and start digging in to this.

**Comment by DDReaper** [comment]
[ ] Rename Core HT -> MRTK folder
[ ] Rename Examples HT -> Examples MRTK folder
[ ] Rename Unit Tests HT -> Unit Tests MRTK folder
[ ] Initial global NS rename
[ ] Review Input namespace
[ ] Review Spacial Mapping namespace
[ ] Review boundary namespace
[ ] Review Sharing namespace
[ ] Review Spacial mapping namespace
[ ] Review Spacial Sound namespace
[ ] Review Spacial Understanding namespace
[ ] Review Utilities / UX code
[ ] Review Build code

**Comment by DDReaper** [comment]
Assuming we are keeping the .Unity suffix..

**Comment by StephenHodgson** [comment]
I think we agreed to remove the .Unity suffixes in the last Shiproom Meeting

**Comment by StephenHodgson** [comment]
@NeerajW who's doing the namespace updates for the core toolkit libraries, like Sharing Service, plane finding, and spatial understanding libraries?

**Comment by DDReaper** [comment]
Love to hear what was agreed.  Considering there is another framework behind this one, it's important to distinguish the two.
Although I can see the advantages of dropping .Unity.
Just so I know when doing the updates.

**Comment by jessemcculloch** [comment]
I also agree with @StephenHodgson that we agreed to drop the .Unity.  I think we agreed that it's not common practice in other libraries, the user should already know they are in the unity version of the project, etc.

**Comment by DDReaper** [comment]
What's the view on the Sharing & SharingWithUnet fandango?
Should the SharingWithUnet really be Sharing.UNET ?  And move the files / scripts under Sharing

**Comment by DDReaper** [comment]
SpatialUnderstanding needs a review, as by adding the nameSpace it's created horrible cod for accessing the Singleton.

Utilities currently doesn't use a NameSpace.  With all the scripts in there, is it worth updating them?

**Comment by DDReaper** [comment]
UX is a mess and needs discussion

**Comment by DDReaper** [comment]
OK, everything except UX is done.
Although thinking of renaming SpacialUnderstanding to SpacialUnderstandingManager (to align with other managers)

Thoughts @StephenHodgson / @jessemcculloch / @NeerajW ?

Will tackle UX next, but it really is a complete mess.

**Comment by StephenHodgson** [comment]
Do you have a PR I can review to see what you have so far?

**Comment by DDReaper** [comment]
I see you found it @StephenHodgson 🗡 
https://github.com/DDReaper/MixedRealityToolkit-Unity/tree/MRTK_Rename

**Comment by NeerajW** [comment]
@NeerajW who's doing the namespace updates for the core toolkit libraries, like Sharing Service, plane finding, and spatial understanding libraries?

@DDReaper could you please update those namespaces as well with MixedRealityToolkit? @keveleigh and I can help with binary recompile.

**Comment by NeerajW** [comment]
>>Utilities currently doesn't use a NameSpace. With all the scripts in there, is it worth updating them?
Should they be under MixedRealityToolkit.Utilities? My vote is yes. Else it will muddy intellisence.

**Comment by NeerajW** [comment]
>>Should the SharingWithUnet really be Sharing.UNET ? And move the files / scripts under Sharing

Let's keep the folders separate for ease in deleting code that users don't need.

**Comment by NeerajW** [comment]
@DDReaper thank you for taking this on :)

**Comment by DDReaper** [comment]
> @NeerajW who's doing the namespace updates for the core toolkit libraries, like Sharing Service, plane finding, and spatial understanding libraries?
> @DDReaper could you please update those namespaces as well with MixedRealityToolkit? @keveleigh and I can help with binary recompile.

So you also want me to dig in to the underlying MRTK lib and update their namespaces too, correct @NeerajW? Not just this project.

**Comment by DDReaper** [comment]
Moved Build windows (project setup, scene setup, capabilities setup) to the Build folder/namespace.
As these are Build related and NOT utilities.

**Comment by DDReaper** [comment]
UX done with a little fandankering (technical term), also moved some files around to make more sense.

**Comment by DDReaper** [comment]
Initial review and update done.

Only pending query are the scripts in "Examples\Input\Scripts\VoiceChat" which look more like core classes.
@StephenHodgson believes there were moved here due to WACK issues, which should "hopefully" be resolved by updating the core DLL.s (which I believe will be included with this rename)

**Comment by DDReaper** [comment]
So status update. A new Feature Branch now exists and is up to date with the rename with a few outstanding tasks:

1: Update the Base MRTK dll's and regenerate the SDK classes in MRTK
2: Update naming in shaders (pain in the backside)
3: Review removing old obsolete classes and update docs for removal

**Comment by keveleigh** [comment]
I'm going to go ahead and close this. It was completed in the dev branch, and a decision has been made to not include it in any master branch releases. The vNext namespaces and folder structure and such will better thought out.
