### ISSUE TITLE
Fade Culling

### ISSUE THREAD

**Issue by reillydonovan** [Microsoft/MixedRealityToolkit-Unity#1531]
Is there an example scene or script demonstrating faded culling without a harsh edge?  So that when you move through an object it has a gradient transparency along the culling edge?

**Comment by NeerajW** [comment]
We don't currently but I bet @Cameron-Micka might be able to add this to his list if it does not exist.

**Comment by Cameron-Micka** [comment]
This is a simple as a material checkbox with an upcoming shader change coming to the MRTK (which will also include an example scene!). You can read more about the proposed changes [here.](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1715)

**Comment by keveleigh** [comment]
Fixed via #1743, which added the Assets/MixedRealityToolkit-Examples/StandardShader/Scenes/MaterialGallery.unity scene with examples of how to implement this feature.
