### ISSUE TITLE
Deploying problem to Hololens

### ISSUE THREAD

**Issue by Hobl1990** [Microsoft/MixedRealityToolkit-Unity#1533]
Hi guys, 

I got the following error when I try to deploy the app from the Visual Studio to Hololens: 

`Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler		Der Befehl ""C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\Unity\Tools\AssemblyConverter.exe" -platform=uap -lock="C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\project.lock.json" -bits=32 -configuration=Debug -removeDebuggableAttribute=False -uwpsdk=10.0.16299.0 -path="." -path="C:\Program Files\Unity\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\dotnet\x86\Debug" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\Assembly-CSharp.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.TilemapModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.TextRenderingModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.UIModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.UIElementsModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.SpriteMaskModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.ScreenCaptureModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.PhysicsModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.TerrainPhysicsModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.TerrainModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.StyleSheetsModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.UNETModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.VRModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.VideoModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.VehiclesModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.WindModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.WebModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.UnityWebRequestAudioModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.UnityConnectModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.UnityAnalyticsModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.UnityWebRequestWWWModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.UnityWebRequestTextureModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.UnityWebRequestModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.ClothModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.AudioModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.ARModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.DirectorModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.CrashReportingModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.CoreModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.AnimationModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.AIModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.AccessibilityModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.ParticlesLegacyModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.JSONSerializeModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.Physics2DModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.PerformanceReportingModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.ParticleSystemModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.GridModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.GameCenterModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.InputModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.IMGUIModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.ImageConversionModule.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\Newtonsoft.Json.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.Timeline.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\nunit.framework.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.UI.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.HoloLens.dll" "C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\UnityEngine.Networking.dll"" wurde mit dem Code 1 beendet.	MixedRealityToolkit-Unity	C:\Users\user\Downloads\MixedRealityToolkit-Unity-master\MixedRealityToolkit-Unity-master\Gaze_HolotoolKit\MixedRealityToolkit-Unity\MixedRealityToolkit-Unity.csproj	436	
`
I use the following versions of the tools: 

- Unity (Version 2017.2.0f3)
- Visual Studio Community (Version 15.5.2)
- Latest version of the MixedRealityToolkit-Unity

Does anybody how to fix that issue?

**Comment by Alexees** [comment]
That's easy to fix. Build into an empty folder or delete everything from the one you build into. I think this happens when you build with copy references (which is not necessary). Either the second time you do that this happens, OR, what I think is, when you then disable that flag, the project has duplicates of everything in the build directory and the Unity directory it now references.
I am not sure, but deleting the build stuff fixes it.

**Comment by keveleigh** [comment]
Hey @Hobl1990, did Alexees' fix work for you?

**Comment by NeerajW** [comment]
Please reopen if you still have specific issues.

**Comment by brunasilvalopes** [comment]
I had this same problem and Alexees' fix didn't work for me. The way I fixed it was to rename the folder containing the Unity project to something shorter than MixedRealityToolkit-Unity-Dev_Working_Branch. 
I guess the problem was that the path was too long, and at some point some paths or file names were being trimmed. In my case, when trying to build and deploy the Bounding box scene to my Hololens, on Visual Studio Output window I saw a message saying that "the file **UnityEnine**.UI.dll wasn't found" (notice the missing G on the word Engine - it got trimmed at some point).

**Comment by debyeleong** [comment]
Thanks @brunasilvalopes - I had a similar issue where the compiler complained it couldn't find "UnityEgine.Networking.dll" (note "Egine" instead of "Engine"). Your comment prompted me to shorten a long folder name and the app was able to be deployed at least.

**Comment by Strepto** [comment]
See this comment for the cause of the error: https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1472#issuecomment-386876127
