### ISSUE TITLE
RaycastCamera cannot manually be assigned to canvas camera field

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1534]
## Overview
Dragging the RaycastCamera into the Camera field in WorldSpace mode of a canvas does not work, it doesn't get assigned. This scenario is only possible when adding a prefabbed canvas with WorldSpace configured already, or when adding MixedReality stuff after a canvas has already been setup that way. All other scenarios prompt for the RaycastCamera to be assigned.
Workaround: Select WorldSpace Render Mode again

## Expected Behavior
Assigning a camera should be possible at any time.Or Canvases should be checked for the the right camera being assigned on adding the MR content to a scene or when adding a new prefab to the scene that contains one.

## Actual Behavior
Assignment doesn't work

## Steps to reproduce
Create a canvas and configure it for WorldSpace rendering. Add MR stuff. Try to assign the RaycastCamera to the currently empty camera field.

## Unity Editor Version
MRTP5

## Mixed Reality Toolkit Release Version
current

**Comment by StephenHodgson** [comment]
This was kinda by design.  It was decided that opting out by default was better than overriding values in people's projects.

**Comment by StephenHodgson** [comment]
Although I do have a issue open to make this process easier to do when you add the Input Manager prefab into the scene.
