### ISSUE TITLE
Crash calling Dismiss() on PopupMenu if rootAnimator is null

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#1535]
## Overview
Calling Dismiss on PopupMenu with no Animator
## Expected Behavior
No crash
## Actual Behavior
Crash
## Steps to reproduce
Call Dismiss on PopupMenu with no Animator
The problem is inside Dismiss():

            if (rootAnimator.isInitialized)
            {
                rootAnimator.SetTrigger("Dehydrate");
            }
            else
            {
                gameObject.SetActive(false);
            }

## Unity Editor Version
2017.2.1.f1
## Mixed Reality Toolkit Release Version
Master, Dev, Stabilization

**Comment by ivan2007** [comment]
This issue is present with MRTK 2017.4.0.0

**Comment by keveleigh** [comment]
PopupMenu was written specifically to be used in the InputManagerTest.unity example scene, so it may take some additional reworking to make it properly generic.

That being said, I've included a fix for this in #2358.
