### ISSUE TITLE
Children of game object with attach to controller remain inactive when the game object is deactivate and then reactivate

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#1536]
## Overview
Children of game object with AttachToController remain inactive when the game object is deactivated and then reactivated (with SetChildrenInactiveWhenDetached=true)
## Expected Behavior
The children must be activated when the parent is reactivated
## Actual Behavior
The children remain inactive
## Steps to reproduce
Place AttachToController on a game object with children (SetChildrenInactiveWhenDetached is true)
Deactivate the game object
Reactivate the game object

## Unity Editor Version
2017.2.1f1
## Mixed Reality Toolkit Release Version
Master, Dev, Stabilization

**Comment by ivan2007** [comment]
I think that inside OnEnable it should be:
        protected virtual void OnEnable()
        {
            if (!IsAttached) SetChildrenActive(false);

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
