### ISSUE TITLE
Running in hololens Emulator

### ISSUE THREAD

**Issue by Mudbelly** [Microsoft/MixedRealityToolkit-Unity#1541]
## Overview
Unable to run any scene in emulator, get errors like below:

d3d11: failed to create staging 2D texture w=32 h=32 d3dfmt=65 [887a0005]

I point my sdk to 15063,

## Unity Editor Version
2017.1.2f1
## Mixed Reality Toolkit Release Version
1.2017.1.2

**Comment by Caltato** [comment]
Same. Mine just crashes Unity  :/

**Comment by keveleigh** [comment]
Are you still seeing this issue? I was unable to repro. Please re-open if so.
