### ISSUE TITLE
Null ref exception when attempting to set Input Axes

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1543]
## Overview
When trying to update input manager axes, the editor attempts to load the InputManager.asset located in the ProjectSettings folder, but fails to do so.

## Expected Behavior
Input axes are updated

## Actual Behavior
Null reference exception on serialized Input Manager asset.

## Steps to reproduce
Mixed Reality Toolkit menu -> Apply Project Settings -> Toggle Use InputManager axes -> Apply

## Unity Editor Version
5.6.4p4

## Mixed Reality Toolkit Release Version
2017.2.1.0

**Comment by keveleigh** [comment]
Does this repro in any non-5.6 Unity?

**Comment by StephenHodgson** [comment]
I haven't tested yet.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
