### ISSUE TITLE
Unity 2017.2.1f1 Not able to refind room | Hololens

### ISSUE THREAD

**Issue by RainslayerX** [Microsoft/MixedRealityToolkit-Unity#1545]
## Overview
Regression as this was fixed in a previous MRTP and Unity build. In the scene are the standard prefabs HololensCamera, InputManager, SpatialMapping and DefaultCursor
## Expected Behavior
After losing the room, refind it and continue program
## Actual Behavior
Unity stays on the screen for looking for the room
## Steps to reproduce
Build with Unity 2017.2.1f1 and block the sensors for a second. The screen will popup but the program wont continue execution when not blocking the sensors anymore
## Unity Editor Version
Unity 2017.2.1f1
## Mixed Reality Toolkit Release Version
HoloToolkit Unity 2017.2.1.0

**Comment by StephenHodgson** [comment]
Are you talking about tracking loss?
Is this an issue with the Unity Editor or with a specific component in the toolkit?

**Comment by StephenHodgson** [comment]
Closing in favor of 1547. Better description.
