### ISSUE TITLE
Unity 2017.2.1f1 Dumps on right click + move in Hololens emulator

### ISSUE THREAD

**Issue by Bojoe** [Microsoft/MixedRealityToolkit-Unity#1546]
## Overview
I seem to have an issue if I create a new project, with just a cube and launch in the hololens emulator, I can see the cube but as soon as I right click the mouse and try move it or spacebar the emulator crashes with the following error:

"Exception thrown: 'System.NullReferenceException' in UnityEngine.UI.dll
An unhandled exception of type 'System.NullReferenceException' occurred in UnityEngine.UI.dll
Object reference not set to an instance of an object."

## Unity Editor Version
Unity 2017.2.1f1
## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-2017.2.1.0

**Comment by StephenHodgson** [comment]
Can you provide the full stack trace please?

**Comment by StephenHodgson** [comment]
Do you have anything else in the scene besides a Cube?

I'll need a more detailed description of your scene setup, which prefabs you're using, and a list of repro steps.

**Comment by dlionz** [comment]
Hello @StephenHodgson , I have run into this same issue. I will try and outline how my project is set up.

2017.2.0f3 Unity Version

Current release of Toolkit


The scene has a cube with an onclick and a building that has nothing attached.

I have built my project scene with just the menu item "Mixed Reality Toolkit >Configure Apply Mixed Reality Scene settings" components that this adds. 

I am building my project on a Dell Visor. When I run the built project and use the triggers or click any of the buttons on the controller the program stops and I get the error below.

'HZ-Dell-Visor.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\damie\Documents\HZ-Dell-Visor\TEST\HZ-Dell-Visor\bin\x64\Debug\AppX\System.IO.FileSystem.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
An unhandled exception of type 'System.NullReferenceException' occurred in UnityEngine.UI.dll
Object reference not set to an instance of an object.

Please let me know what else I may need to provide.

**Comment by StephenHodgson** [comment]
Do you have a full stack trace?

**Comment by bkfichter** [comment]
I have a similar issue using Unity 2017.3.0f3
I'm getting a null reference when using the IInputClickHandler. Lands here:
ExecuteEvents.ExecuteHierarchy(inputEventData.selectedObject, pointerInputEventData, ExecuteEvents.pointerDownHandler);

selectedObject is null

So I tried the InputTapTest that is in the Examples under Input and I get the same error inside of Unity when using the emulator tools.

**Comment by BigMacPT** [comment]
Hi, I got the same exact error when using the Tap Gesture on a real Hololens device (not on emulator though).

Anyone has any clues?

Maybe a more recent version of Unity / Toolkit has fixed it?

**Comment by BigMacPT** [comment]
I have succesfully used a Tap Gesture on a real device without it crashing! I had to upgrade to Unity 2017.3.1f1. The Mixed Reality's Toolkit package was 2017.2.1.1 and I'm using Visual Studio 2017 community version 15.5.6.

**Comment by pnolen** [comment]
Running into this today on 2017.1.3p4, and I'm curious. Is there a particular reason why InitializeEventDatas() is called from Awake on the InputManager and not Start? EventSystem.current is set internally on the EventSystem's OnEnable method so if we set this on Start it would guarantee that it was initialized without having to muck around with Script Execution Order.

**Comment by StephenHodgson** [comment]
Yup, just the script execution order. In the next version we're not event tying the event system to a game object so we won't ever run into this issue again.

**Comment by BigMacPT** [comment]
In which version will it be fixed? 2017.2.1.4?
Thank you

**Comment by StephenHodgson** [comment]
>In which version will it be fixed?

vNEXT

**Comment by davidkline-ms** [comment]
#1954 may have fixed this. The fix is in the 2017.2.1.4 HoloToolkit release.
