### ISSUE TITLE
Tracking lost not recovering in HoloLens

### ISSUE THREAD

**Issue by GKersten** [Microsoft/MixedRealityToolkit-Unity#1547]
## Overview
When running a simple app on HoloLens and tracking is lost. The tracking is not being recovered. I thought this was [fixed with MRTP5](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1432). But with the new stable release it looks like it's still not working.

## Expected Behavior
After tracking lost, tracking should resume after a few seconds.

## Actual Behavior
Tracking stays lost, Image of "Mapping your surroundings" is still showing.

## Steps to reproduce

Download:
[TestTracking.zip](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/1571845/TestTracking.zip)

Or:

1. Create new project with latest stable release with Unity 2017.2.1f1 and import HoloToolkit-Unity-2017.2.1.0
2. Configure default Project, Scene and Capability settings through Mixed Reality Toolkit menu.

Than:

3. Build and run the app on HoloLens
4. Put your hand in front of scanners until tracking lost
5. Remove your hand
6. Notice, that tracking does not get restored.

## Unity Editor Version
2017.2.1f1

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-2017.2.1.0

**Comment by GKersten** [comment]
After posting this, i found [#1545](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1545) propbably talking about the same issue.

**Comment by rolandsmeenk** [comment]
Apparently a fix is in the works. https://forum.unity.com/threads/recovering-from-lost-tracking-on-hololens.509376

**Comment by GKersten** [comment]
Thanks for the update @rolandsmeenk . At the moment this really blocks me from using the latest release in production. I thought this was fixed with the latest Unity MRTP release, but apparently not. According to that link it is also not fixed yet in the current 2017.3 release, so lets hope they will release a new 2017.3 MRTP version soon :)

Jumping back to 2017.1 for now.

**Comment by GKersten** [comment]
So, I submitted an issue to Unity with Unity version 2017.2.1f1. I got an email back that they marked it as duplicate and that the bug [is fixed with 2017.2 RC MRTP5](https://forum.unity.com/threads/custom-build-2017-2-rc-mrtp-windows-mixed-reality-technical-preview.498253/). Now I am not sure anymore if this should be integrated with 2017.2.1f1 or not, or either will be fixed in 2017.3.
