### ISSUE TITLE
Tile Generator does not generate proper image dimensions for wide tiles

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1553]
## Overview
Wide tile icon dimensions are not properly updated and set in the PlayerSettings.asset

## Steps to reproduce
Generate Tiles for you app using the Tile Generator.
![image](https://user-images.githubusercontent.com/13334553/34178472-2da7d002-e4bc-11e7-81c7-18091efa7c02.png)

## Unity Editor Version
2017.2.1f1

## Mixed Reality Toolkit Release Version
2017.2.1.0

**Comment by StephenHodgson** [comment]
Weird. I ran this again, and can't seem to find good repro steps.

Worked for me after subsequent attempts.

**Comment by tipiro85** [comment]
I got a similar issue with Unity 2017.3.0f3 and Holotoolkit 2017.2.1.3. When I start generate icons, it stop at step 25/238 and I get the following error : 

> Exception of type 'System.ArgumentOutOfRangeException' was thrown.
> Parameter name: type
> Actual value was StoreTileLogo.
> UnityEngine.Debug:LogError(Object)
> HoloToolkit.Unity.SetIconsWindow:ResizeImages() (at Assets/HoloToolkit/Utilities/Scripts/Editor/SetIconsWindow.cs:230)
> UnityEditor.EditorApplication:Internal_CallDelayFunctions()

I used images which work well on my old version of Unity 5.6.2 and the appropriate Holotoolkit version.

**Comment by cefoot** [comment]
I'm experiencing same issue as @tipiro85 (ArgumentException param:type ActualValue: StoreTileLogo)

I'm using 
MRTK: 2017.2.1.4
Unity: 2017.2.1p2

**Comment by jganser** [comment]
I just tried it out with 
---
Unity 2018.1.0f2
MRTK 2017.4.0.0  commit 05d004f3 
---
and i did get the problem, that all generated wide tiles had the same size as the original : 2480x1200

> Base was a Sprite with following settings
> Sprite Mode = Single
> Pixels Per Unit =  100
> Mesh Type = Full Rect
> Extrude Edges = 1
> Generate Physics = true
> Wrap Mode = Clamp
> Filter Mode = Point (no filter)
> Max Size = 4096
> Resize Algorithm = Michell
> Compression = Normal Quality

**Comment by jganser** [comment]
Changing some values of the sprite, solved the problem. For me.

**Comment by albinhw** [comment]
> Changing some values of the sprite, solved the problem. For me.
c@jganser I am facing the same issue. Can you please share what settings you used for the sprite to resolve the issue?

**Comment by albinhw** [comment]
@jganser I am facing the same issue. Can you please share what sprite settings you used to resolve the issue?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
