### ISSUE TITLE
Frame rate drops to 30 fps when rendering Unity UI

### ISSUE THREAD

**Issue by derdimi** [Microsoft/MixedRealityToolkit-Unity#1561]
Has anybody else experienced frame rate drops down to 30 fps using the Unity UI? Especially when using a Scroll View.

**Comment by StephenHodgson** [comment]
Closing this because it's not a toolkit specific question.

Please use the [Microsoft Developers Forum](https://developer.microsoft.com/en-us/windows/mixed-reality/community) or [Unity's forums](https://forum.unity.com/forums/windows-mixed-reality.102/).

**Comment by derdimi** [comment]
I use all of the forums but I truly think this is the most frequently used forum by experienced HoloLens developers right now. Having said that, I understand where you're coming from. It was worth a try, though. Sorry =)

**Comment by StephenHodgson** [comment]
No worries,  Try the [Slack Channel](https://holodevelopers.slack.com/) too
