### ISSUE TITLE
Network discovery broken by hololens os update

### ISSUE THREAD

**Issue by Kron0** [Microsoft/MixedRealityToolkit-Unity#1564]
## Overview
The latest update to the hololens os has killed the previously working shared with unet code.

## Expected Behavior
The hololens should be able to broadcast and listen for messages

## Actual Behavior
The hololens can start a room, but no one can hear the broadcasts

## Steps to reproduce
Open Unetsharing sample
build sample scene
run on 2 hololens or 1 device and 1 pc; observe the room cannot be seen after being created

## Unity Editor Version
2017.2.1f
## Mixed Reality Toolkit Release Version
v2017.2.1

**Comment by Kron0** [comment]
That's OS build 10.0.14393.1944 btw. Having a look on wireshark I can't see the broadcasts from the server.

**Comment by Kron0** [comment]
Ooops... looks like I had a crahed app in the background blocking the port the server was trying to use.

It does seem that I can't see the rooms from the editor since the 2017.2.1 update though

**Comment by Alexees** [comment]
You're sure you disabled the firewall? If the computer has internet, disable the public one
