### ISSUE TITLE
HoloToolkit-Unity-Tests-v1.5.8.0.unitypackage

### ISSUE THREAD

**Issue by junqiangchen** [Microsoft/MixedRealityToolkit-Unity#1566]
Hello,i want to make sharing example.My Unity is 5.6.3f1,HoloToolkit is 5.8.0. So i download the test code is Sharing Test, When i upload to hololens, the app is broken,i am confused,can you help me or give me some advice,thank you.

**Comment by eirikhollis** [comment]
Try using Unity 5.6.2f1 with [Holotoolkit 1.5.7.0](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/v1.5.7.0). Target the 14393 SDK.

**Comment by NeerajW** [comment]
Any reason you are not on latest Unity and MRTK releases? We will be able to better help with those.
