### ISSUE TITLE
OnInputClicked with avatar

### ISSUE THREAD

**Issue by jarmohh** [Microsoft/MixedRealityToolkit-Unity#1568]
## Overview
I have Avatar and I want to give commands with this code. I don't know it there is better ways to do it.
```
public class WalkTap : MonoBehaviour, IInputClickHandler
{
    private Animator _animator;

    void Start()
    {
        GameObject avatar = GameObject.Find("Walk");
        _animator = avatar.GetComponent<Animator>();
    }

    public void OnInputClicked(InputClickedEventData eventData)
    {
        _animator.Play("Walk");
        eventData.Use(); 
    }
}
```
## Expected Behavior
Avatar walks when click avatar. Code works if I use it with cube and click cube, then avatar start to walk.
## Actual Behavior
Not working with avatar
## Steps to reproduce
Use that script with avatar animation.
## Unity Editor Version
2017.2.1f1
## Mixed Reality Toolkit Release Version
2017.2.1.0

**Comment by Alexees** [comment]
This is not a mixed reality toolkit problem since the only tool related code, the interface, works. Post this in unity answers.

**Comment by StephenHodgson** [comment]
A agree.  This isn't really a toolkit issue.
