### ISSUE TITLE
The gaze will be hidden behind the dropdown menu entries

### ISSUE THREAD

**Issue by Hobl1990** [Microsoft/MixedRealityToolkit-Unity#1569]
Hi guys,
I have troubles with the gazing at the dropdown menu items. When I gaze at one of the entries the gaze will dissapear behind the entries. 
I used the gaze cursor "CursorWithFeedback" from the HoloToolKit and the Dropdown menu from unity.

![issue](https://user-images.githubusercontent.com/32168859/34377874-6f87ff82-eaf3-11e7-81bb-430e5214fcb0.JPG)

Did you know how to solve this issue?

**Comment by StephenHodgson** [comment]
Try messing with the uGUI sorting layers

**Comment by Hobl1990** [comment]
@StephenHodgson thank you for your hint ;) I just added the sorting group component to the canvas and configured the sorting layers. The most important task was to assign the value 30.000 to the order in layer. Now everything works fine ;)
