### ISSUE TITLE
[Hololens] click cannot be differentiated from up

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1570]
## Overview
When the finger is raised off of an intractable element, up and click are always raised no matter where down happened.  
From the Unity UI it's known that a click only happens when the down event happened on the same element.

## Expected Behavior
Click only happens when down happened on that object.

## Actual Behavior
Click always happens

**Comment by StephenHodgson** [comment]
I'm pretty sure this is by design.

**Comment by Alexees** [comment]
In my particular case I have game logic, like dragging, while holding an object. It is possible to end the drag with the cursor over a current UI element. This "design" does not prevent a click from happening on that UI element.  
Why is the design current from what we know about the unity UI behavior?

**Comment by StephenHodgson** [comment]
I agree that ideally it should be the same.

Idk you'll have to ask the MSFT guys that created it.

**Comment by keveleigh** [comment]
I believe @mrbobbybobberson wrote that logic originally.

It's possible that scenario wasn't considered, though I don't know for sure.

**Comment by StephenHodgson** [comment]
@Alexees why not use Hold or Manipulation for your dragging?

**Comment by Alexees** [comment]
It's actually Hold in form of an Update call from the GestureRecognizer. But the initial down on the UI element activates this behavior in the first place while a release finishes it. There are 3 UI buttons related to rotate, move and scale below lets say a cube. Holding on to one of these buttons enables their corresponding functionality. While the whole thing moves along with the cursor when the move handle is used, for the others it's just the offset that's relevant. And when you finish, ergo release, its possible to do that on lets say the 4th button, the exit tool button that disables the whole menu, or a "change object color" button. Right now the only way I see this working is disabling all other UI elements because every element can receive a click when up happens on them no matter where down happened. That was a convenient distinction when using Unitys UI, not so here.

**Comment by StephenHodgson** [comment]
Did you try a modal input handler?

**Comment by Alexees** [comment]
What do you mean by that?

**Comment by StephenHodgson** [comment]
Take a look at `InputManager.Instance.PushModalInputHandler` and `PopModalInputHandler`.

The modal input handlers push a game object into the modal input stack. Any input handlers on the game object are given priority to input events before any focused objects.

**Comment by Alexees** [comment]
This can be closed I guess. I changed all my calls to the same logic without using click for up
