### ISSUE TITLE
UI components not working with multiple scenes

### ISSUE THREAD

**Issue by christian4423** [Microsoft/MixedRealityToolkit-Unity#1573]
## Overview
I had all of my components nested under game objects. This was getting messy for me and I decided to switch to scenes and use UnityManager.SceneManager

Everything is working as expected, except my Input UI Elements are now are not recognized by my gaze cursor. Following the setup for the keyboard input in the Holokit examples, I was able to get it set up before. 

But now I have this issue. 

Here are some screenshots below

![pt1](https://user-images.githubusercontent.com/6324867/34428171-01413900-ec18-11e7-9a80-5f8daa6d98d9.PNG)

If you look at the canvas in the inspector you will see the Camera I need to reference is not allowed. 

![pt2](https://user-images.githubusercontent.com/6324867/34428175-09cb836e-ec18-11e7-8d34-888cf0867849.PNG)

If you look at Inspector when Input Manager is selected, It says UI Raycast Camera is the camera under EventSystem

Let me know if any more information is needed for this or if there is a better way to handle scene management in unity that will allow use of the camera. 

## Unity Editor Version
2017.2
## Mixed Reality Toolkit Release Version
v2017.2.1.0

**Comment by genereddick** [comment]
There are many issues related to multi-scene projects, but see #1420 on this topic. 

You can either create a script and run the code below on loading the new scene. This will update an existing Canvas to the correct camera:
    
    FocusManager.Instance.UpdateCanvasEventSystems();

Or, try creating a new Canvas (and then modifying it to be the same as the old version). For me, I wasn't able to update an existing Canvas with the correct camera, but a new Canvas was OK.

**Comment by StephenHodgson** [comment]
I really don't think using `FocusManager.Instance.UpdateCanvasEventSystems();` is the best solution and was never really intended to be used at run-time.

You should probably set the UIRaycasetCamera directly on your canvas.

```
// Set the Canvas reference in the inspector
private void Awake()
{
    if(myCanvas.isRootCanvas && sceneCanvases[i].renderMode == RenderMode.WorldSpace)
    {
        myCanvas..worldCamera = FocusManager.UIRaycastCamera;
    }
}
```

**Comment by christian4423** [comment]
Sorry, I will review these comments ASAP and respond with any success. I did not get alerted that people responded to this!
