### ISSUE TITLE
Sharing Example does not meet Quality Guidelines

### ISSUE THREAD

**Issue by drakep** [Microsoft/MixedRealityToolkit-Unity#1574]
## Overview
Sharing Example does not have a readme or documentation explaining the scenes and code as required at https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit-Examples
## Expected Behavior
readme visible at https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit-Examples/Sharing
## Actual Behavior
No read me
## Unity Editor Version
Any supported version
## Mixed Reality Toolkit Release Version
Latest released

**Comment by Yoyozilla** [comment]
Bulk closing older HTK bug. Please reopen if you can repro this issue in MRTK v2. 

We will make sure the new sharing in MRTK v2 has doc and readme when it becomes available 
Thanks!

Yoyo
