### ISSUE TITLE
InteractiveElementInstantiate-Example throwing nullpointer

### ISSUE THREAD

**Issue by brean** [Microsoft/MixedRealityToolkit-Unity#1577]
I just started the new year with a clean checkout of the MRTK.

I don't know how that happened (I guess I just forgot to save or something got tangled up during the merge) but the InteractiveGroupSet-Script attached to the "NoteButtonSet"-GameObject in my example ([InteractiveElementInstance on Dev_Working_Branch](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/HoloToolkit-Examples/UX/Scenes/InteractiveElementInstantiate.unity)) does not have the GameObject for the Grid set in the Inspector anymore so the Script throws a NullPointer if you just press play.

Should I just attach it again and create a pull request for the .unity-file or should I write something that searches the scene and attach it programmatically?

In general what is best practice for that? Should scripts search for components in the scene if they are not set in the inspector?

**Comment by StephenHodgson** [comment]
Best practice is to set the reference in the inspector, and fallback if the field/property is null on Start/Awake
