### ISSUE TITLE
KeyboardInputField does not fire Input Events

### ISSUE THREAD

**Issue by testedmargaritta** [Microsoft/MixedRealityToolkit-Unity#1579]
## Overview
[KeyboardInputField](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/UX/Scripts/KeyboardInputField.cs) in MRTK doesn't fire unity event onEndEdit

## Expected Behavior
Toolkit KeyboardInputField should fire onEndEdit unityevents

## Actual Behavior
Toolkit KeyboardInputField does not fire unityevents.

## Unity Editor Version
5.6.4.P1
## Mixed Reality Toolkit Release Version
Latest

**Comment by Alexees** [comment]
Nice to know. Just today I implemented a keyboard input field. Will see if this works with 2017.3

**Comment by 0k1** [comment]
Use onValueChanged as of now. 

onEndEdit needs to be called manually somewhere in KeyboardClosed of KeyboardInputField as Unity [InputField](https://bitbucket.org/Unity-Technologies/ui/src/378bd9240df3ac323ac3de9274dd381ec99f9ebe/UnityEngine.UI/UI/Core/InputField.s) fires its submit method on deselect and Deselect fires as soon as the keyboard pops up and not after end edit actually. 

Hope that makes sense.

**Comment by Alexees** [comment]
as far as I can tell, registering to OnEndEdit in OnPointerClick shows that OnEndEdit gets called immediately. I think, since the KeyboardInputField derives from InputField and the input is basically happening from outside the input field, for the InputField it ends right where it started.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
