### ISSUE TITLE
Supported Unity versions for next release?

### ISSUE THREAD

**Issue by eirikhollis** [Microsoft/MixedRealityToolkit-Unity#1580]
Hi, I am in the process of starting a new long-term project, and was wondering (since I read it somewhere), if future releases of MRTK will cut support for older Unity versions than 2017.3? 
Am I understanding it correctly that starting a new project with 2017.2.1 Unity and MRTK will require an update to 2017.3 for new releases of MRTK following the next (and all future) release?

**Comment by StephenHodgson** [comment]
That is correct.

**Comment by NeerajW** [comment]
Please give us a scenario where you think the older Unity builds must be supported? We believe it's causing more maintenance issues than not.

**Comment by eirikhollis** [comment]
The question was regarding to if a new project I was starting should be started in 2017.3 or 2017.2.0. I chose 2017.3 from the answer. 
Personally, as long as new Unity versions don't introduce new breaking bugs, I believe only the latest should receive the newest toolkit updates. As you say, supporting older versions is definitely more time-consuming.

**Comment by StephenHodgson** [comment]
They have introduced breaking changes from 2017.3 and beyond.

**Comment by davidkline-ms** [comment]
Version 2017.2.1.4 supports Unity 5.6 - 2017.4.
Version 2017.4.0.0 (coming in May 2018) will officially support Unity 2017.1 - 2018.1 (Unity 5.6 will likely still continue to work, if it does not we will investigate bug reports)
