### ISSUE TITLE
GestureRecognizer is slow to recognize Manipulation when using Motion Controllers

### ISSUE THREAD

**Issue by markgrossnickle** [Microsoft/MixedRealityToolkit-Unity#1581]
## Overview
When using Motion controllers the GestureRecognizer seems too slow to recognize manipulations.  If you add IManipulationHandler to a button you will not be able to trigger OnManipulationStarted because by the time the manipulation is registered the focus object will no longer be the button. 

I am adding MR support to HoloMaps.  In HoloMaps we use the GestureRecognizer to track Manipulation for Panning, Drawing the Pen, and Resizing the map.

This works great on the Hololens while using your hand. It also works fine in the editor using the mouse or gamepad.  However, with motion controllers there is a delay and it breaks down to the point where we either need to write custom manipulation code just for Motion controllers or we need to swap our paradigm to use OnInputDown and OnInputUp to keep our code consistent.

## Expected Behavior
While using the motion controller you should be able to grab a button and move your controller to trigger OnManipulationStarted before your cursor leaves the button.

## Actual Behavior
OnManipulationStarted is delayed and does not trigger until your cursor has left the button and another focusObject is found.  This results in OnManipulationStarted from never being sent to the initial button.

## Steps to reproduce
Add two buttons to your scene which implement IManipulationHandler.  Ensure to add a log in OnManipulationStarted.  Make one button very large and one a normal sized.   Note that manipulating the buttons with the motion controller will trigger on the large one but will not on the normal sized one. 

## Unity Editor Version
2017.2.1p1

## Mixed Reality Toolkit Release Version
Latest Master

**Comment by timGerken** [comment]
Interesting. I'm also seeing this lag on HoloLens running an RS4 build and using the clicker. Hand works just fine.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
