### ISSUE TITLE
Hololens neither sharing Anchors nor syncing position when MR device hosts

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1583]
## Overview
Trying to bring Mixed Reality to its fullest, the result of starting a game from a Mixed Reality HMD results in none of the Hololenses starting to share their anchor. AnchorEstablished never gets true in the PlayerController and therefore returns before updating the anchor relative positions of the lenses.

## Expected Behavior
Should not matter who starts a session, the lenses should still create a shared anchor

## Actual Behavior
Hololens devices are not sharing when MR is the host

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2017.3.0f3

## Mixed Reality Toolkit Release Version
not sure. Quite up to date.

**Comment by Alexees** [comment]
Want to put this on hold, there seems to be an issue, but not quite sure anymore

**Comment by cstensonpv** [comment]
Hi! any update ? Got it working? I myself are looking into sharing from Windows VR and an Hololens. Do you have any sample project  that you can share ?

**Comment by StephenHodgson** [comment]
VR devices don't have anchors.

**Comment by cstensonpv** [comment]
I understand that however Sharing is marked as compatible on both "devices"? Is it possible to get it working similair to the demo at the Windows VR hmds release video? 
https://www.youtube.com/watch?v=xTT_3DhTMI8&t=591s
would be really nice for demo purposes

**Comment by StephenHodgson** [comment]
I'm guessing this is using the Sharing with UNET features?

That code hasn't ever really been fleshed out and proven like the sharing service has.

**Comment by cstensonpv** [comment]
Okay. Would be really cool to be able to do something similar.
If anyone has ideas on how to do it I'm intrested

**Comment by daxuewuqing** [comment]
@StephenHodgson Will the anchors be added to the VR devices to achieve accurate positioning?

**Comment by Alexees** [comment]
@StephenHodgson 

> That code hasn't ever really been fleshed out and proven like the sharing service has

What's the difference between Sharing with UNET code and the sharing service you're talking about? Is the "sharing service" something "better"?

**Comment by StephenHodgson** [comment]
I wouldn't say it's _better_ per se, but it doesn't have any example code in it like the UNET stuff did.

**Comment by Alexees** [comment]
> I wouldn't say it's better per se, but it doesn't have any example code in it like the UNET stuff did.

Where do I find it?

**Comment by StephenHodgson** [comment]
It got moved into examples now.
