### ISSUE TITLE
Controller Pointers Base Branch

### ISSUE THREAD

**Issue by Railboy** [Microsoft/MixedRealityToolkit-Unity#1602]
## Overview

This branch adds a basic line pointer example to the MRTK:
https://github.com/Railboy/MixedRealityToolkit-Unity/tree/Controller_Pointers_Base

## Issues

This is a subset of the pointer examples we're working on in #1486. Some changes were necessary to make these classes function in the current dev branch. Those changes have been marked with a comment: 
`// This will be enabled when multi-pointer support is incorporated`
If we open a PR we'll want to strip these out - they're just to facilitate discussion.

Minor issues that are addressed in #1486:
 - Cursor lags behind pointer's target point
 - Single cursor is swapped between multiple pointers
 - IPointerInput.OwnsInput can result in false positives

## Files

- Adds ControllerPointerBase.cs, FocusPointerInput.cs, InteractibleHighlight.cs and LinePointer.cs classes to HoloToolkit/UX/Scripts/Pointers
- Adds ControllerPointerExamples scene to HoloToolkit-Examples/UX/Scenes.
- Adds LinePointerBasic prefab to HoloToolkit-Examples/UX/Prefabs
- Minor changes to several Line classes.

## Questions

Do we feel this is worth merging? How could it be improved?

**Comment by StephenHodgson** [comment]
@Railboy I started working on another branch to show my perspective and a different take on the purposed changes.  I think we should have a comprehensive meeting about and compare notes.

**Comment by Railboy** [comment]
@StephenHodgson Taking a look now. At first blush I don't think your proposed changes conflict with this example in a significant way.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
