### ISSUE TITLE
Sharing Service Remote IP

### ISSUE THREAD

**Issue by 86simonepenna** [Microsoft/MixedRealityToolkit-Unity#1606]
Hello,

The sharing service only works locally but it's not reached from external network. Example:

- deploy sharedService.exe on server with ip "52.232.97.xxx"
- from another pc in another network the connection failed.
- the ports required are open.

Do you have any advice?

Thank you

**Comment by GAnatoliy** [comment]
Hi,

Sharing service definitely works remotely (guys here host it in a cloud https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/953)

I would start from checking network's interaction/accessibility.

**Comment by NeerajW** [comment]
Perhaps some firewall rules are blocking it? I have also tried in the past hosting on an azure VM etc.

**Comment by 86simonepenna** [comment]
I have Dinamic Ip....

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
