### ISSUE TITLE
Switching to MotionController while gazing at UI Element uses pressed color for highlighted color

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1610]
## Overview
When gazing at a default Unity UI Button and then switching over to a Motion Controller switches between Normal Color and Pressed Color until another press happens on the button. Then, Pressed Color is replaced by Highlighted Color again.

## Expected Behavior
When pointing at any UI Element, Highlighted Color should be used, not Pressed Color

## Actual Behavior
When pointing at theUI Element the gaze was at when switching to the Controller, Pressed Color is used for highlights instead of Highlighted Color

## Unity Editor Version
2017.3.0f3

## Mixed Reality Toolkit Release Version
Dev_Working_Branch

**Comment by StephenHodgson** [comment]
I'm going to guess this is because a pointer event was raised to the Standalone Input Module.

I'll be addressing this issue in the [Input System refactor](#1603).

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
