### ISSUE TITLE
App created with HoloToolkit-Unity-2017.2.1.0 crashes in emulator as well as in hololens.

### ISSUE THREAD

**Issue by mr-mystery** [Microsoft/MixedRealityToolkit-Unity#1612]
## Overview

A simple project with only cube and hand draggable script attached crashes with hololens. 

## Expected Behavior

The cube in the project should move when user grabs it and moves it.

## Actual Behavior

The app crashes right a way as soon as manipulation begins.

## Steps to reproduce

1. Create an empty project.
2. Add Hololens Camera, InputManager, Any Cursor and the project settings from the mixedreality tool from the top.
3. Add a cube and attach HandDraggable script to it.
4. Build the UWP app with target SDK as 16299 (15063 won't build, Don't know why). And deploy it to the lens or an emulator.
5. As soon as the cube is visible don't start manipulating. Wait for a few seconds.
6. Now, Start the manipulation. **Ka-Chow**

## Unity Editor Version

Unity 2017.2.1f1 (64-bit)

## Mixed Reality Toolkit Release Version

HoloToolkit-Unity-2017.2.1.0

**Comment by StephenHodgson** [comment]
Do you have any crash logs you'd like to add?
(only lines specific to the crash itself, not the whole thing, if possible.)

**Comment by mr-mystery** [comment]
![debugerror](https://user-images.githubusercontent.com/30065223/34808979-fbf72964-f6b7-11e7-9335-88290f2c5e57.PNG)
![hierarchy](https://user-images.githubusercontent.com/30065223/34808980-fc296b18-f6b7-11e7-8d80-3e195e3153ac.PNG)

**Comment by mr-mystery** [comment]
Is this enough?

**Comment by StephenHodgson** [comment]
Looked like the null ref was coming from a unity dll.

Is there a fill stack trace?

**Comment by mr-mystery** [comment]
No, there wasn't any stack traces. Inside Unity the app is running fine.

**Comment by StephenHodgson** [comment]
See if you can get a fill stack trace

**Comment by mr-mystery** [comment]
Bro. How to do this tracing things?

**Comment by mr-mystery** [comment]
Bro. Found the error! In Hololens camera prefab we have a deprecated GUI layer component. As soon as I removed it my app isn't crashing anymore.  Thanks for your time bro.

**Comment by dayanjan** [comment]
I've been having the same issue and was wondering if it is the same cause as yours. I am new to unity and was wondering how you identify a deprecated GUI layer component within the Hololesn camera prefab. Would you happen to have a screenshot?
