### ISSUE TITLE
GameObject with procedural Mesh selection/focus

### ISSUE THREAD

**Issue by atanasovg** [Microsoft/MixedRealityToolkit-Unity#1615]
## Overview
I have a custom GameObject hierarchy that consists of root object and several children, each one of which has its own procedural mesh, generated upon script Awake. For some reason neither of these custom objects is recognized as valid select/focus target.

I guess I am missing something simple so any insight(s) would be highly appreciated.

## Expected Behavior
Upon gazing at the object, I'd expect the root GameObject to be properly hit-tested and when Air Tap gesture is performed - to become the selected one.

## Actual Behavior
My GameObject is not properly recognized by the Ray-casting routine.

## Steps to reproduce
I can't share my company code but can try to do a simple repro if needed.

## Unity Editor Version
Tried both with Unity 2017.3 and 2017.2.

## Mixed Reality Toolkit Release Version
Latest release available.

**Comment by Weasy666** [comment]
I'm not sure if that is exactly what you are looking for, but you could put a script like this on your root GameObject.
``` csharp
public class rootGameObjectScript: MonoBehaviour, IInputClickHandler
{
    public virtual void OnInputClicked(InputClickedEventData eventData)
    {
       // do stuff you want to do after targeting and tapping your GO here
    }
}
```

I hope this helps.

**Comment by atanasovg** [comment]
@Weasy666 Thanks for the comment, unfortunately being not ray-tested, the GameObject doesn't receive this event.

I found the solution after some more digging - my object was missing a collider and the RayCast Unity routine tests for colliders. Adding a simple BoxCollider solved the issue, so closing it.
