### ISSUE TITLE
Null ref when only using the Mixed Reality Camera prefab and targeting HoloLens

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1617]
## Overview
[Users get a null ref from the Fade Manager when using the Mixed Reality Camera prefab and targeting HoloLens devices](https://holodevelopers.slack.com/archives/C2H4HT858/p1515615259000700).  We should mark this prefab as depreciated and possibly remove it in future releases.

## Mixed Reality Toolkit Release Version
Current

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
