### ISSUE TITLE
UX Interactives only in examples

### ISSUE THREAD

**Issue by FlorianJa** [Microsoft/MixedRealityToolkit-Unity#1619]
## Overview
You only can use the (ux) interactable objects and object collection if you import the example package to your project.  The keyboard scripts and prefab for example is in the core tool kit. Importing the example package only for using the ux elements is in my opinion too much.

I'd like to request all prefabs and script of the interactable objects and object collection in the core toolkit.

**Comment by StephenHodgson** [comment]
We will see.  I'd like to keep the core footprint of the toolkit as small as possible.
