### ISSUE TITLE
Mouse Input doesn't work if XR is disabled

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1621]
## Overview
Mouse Input doesn't work for Simulated Hand Input if XR is disabled.

## Steps to reproduce
Change Build settings and disable XR if enabled and attempt to play any scene with interactivity.

## Mixed Reality Toolkit Release Version
Current

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
