### ISSUE TITLE
OnInputClicked triggered on Multiple Objects

### ISSUE THREAD

**Issue by charlesMP** [Microsoft/MixedRealityToolkit-Unity#1622]
## Overview
HoloLens

In my scene I have a UI Button that is Selected to Instantiate a new Object(Hologram). 
When the Object is Instantiated it is supposed to "tagalong' until the User Taps again to place it. 

## Expected Behavior

User Selects to create the Object. Object follows Gaze until user "Taps" to place it. 

## Actual Behavior

When the User selects the create Button the Object spawns in. Then with out tapping again the Object automatically revives the OnInputClicked event and places right away.

This Also gives me issues with InputFields and the new Keyboard. Where if the KeyBoard's "Enter" or "Close" button is over the InputField it will trigger closing the Keyboard then immediatley reopen the Keyboard because the InputField also received the OnInputClicked event.

2017.2.0p1

Latest Version of InputManagers (Focus, Gaze, etc.)

**Comment by StephenHodgson** [comment]
Make sure you consume the first tap event with `eventData.Use();`

**Comment by charlesMP** [comment]
Can't really add that to Unity Buttons. The functionality is tied to their OnClick which has no real relation to the OnInputClicked() event that gives the eventData object.

**Comment by StephenHodgson** [comment]
That's not true.  The gGUI also uses the same types of event data's and uses the same Event System framework that's built into unity.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
