### ISSUE TITLE
UNET Sharing, Network transform doesn't share for Movement

### ISSUE THREAD

**Issue by ALARUNVIGNESH** [Microsoft/MixedRealityToolkit-Unity#1624]
## Overview
Network transform only seems to work Rotating, movement not working , is there any script like Network transform to scale and send other operations in UNET sharing , checked with Sharing With UNET example scene.unity!!. 
## Expected Behavior
expected move shared too , between hololens and immersive devices(Samsung Odyssey)!!.
## Actual Behavior

Rotation is Shared but not Movement!!.

## Steps to reproduce
I have added a Capsule inside Hologram collection and attached Network Transform to it!!.

## Unity Editor Version
2017.2.0p1
## Mixed Reality Toolkit Release Version
2017.2.0

**Comment by SteveKratos** [comment]
varathu epdi varum...

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
