### ISSUE TITLE
Floor not shown if XR is disabled

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#1626]
## Overview
Floor not shown if XR is disabled
## Expected Behavior
Floor shown
## Actual Behavior
Floor not shown
Inside BoundaryManager the condition is this:
```
private void RenderFloorQuad()
        {
            if (FloorQuad != null && XRDevice.GetTrackingSpaceType() == TrackingSpaceType.RoomScale)
            {
.....
```
## Steps to reproduce
Change Build settings and disable XR if enabled and attempt to play any scene.

## Unity Editor Version
2017.3.0f3
## Mixed Reality Toolkit Release Version
Current

**Comment by StephenHodgson** [comment]
@keveleigh, this was by design, correct?

**Comment by keveleigh** [comment]
Yep! The floor concept in this case doesn't really mean anything in non-XR. If we want to expand this script out more, we should discuss that, but the original intention of this script is to render the user's physical floor when it's defined via room set-up, not to render the ground/terrain/etc of an app on any platform.

**Comment by ivan2007** [comment]
Thank you for your quick response
Normally I disable XR only for debug.
In my case the app is a map so the floor is the core part.
I have modified the condition like this:

if (FloorQuad != null && (XRDevice.GetTrackingSpaceType() == TrackingSpaceType.RoomScale || (HolographicSettings.IsDisplayOpaque && !XRDevice.isPresent)))

It seems to work fine for me.
If you can extend the script I think that it could be useful.
Thank you
Ivan
