### ISSUE TITLE
Unity dropdown doesn't show droplist

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#1630]
## Overview
Unity dropdown doesn't show droplist
## Expected Behavior
Droplist shown
## Actual Behavior
When I gaze the dropdown I can't see the droplist. I can see it in the editor window but not in the game window and in the HMD.
In the hierarchy panel I can see the generated  dropdown list and the associated canvas. If I uncheck 'override sorting' in the canvas I can see the list.
Probably I am missing something
## Steps to reproduce
New unity project
Import MRTK
Apply settings for occluded device
Add dropdown
Set world space for canvas render mode
## Unity Editor Version
2017.3.0f3
## Mixed Reality Toolkit Release Version
Current

**Comment by keveleigh** [comment]
This may be fixed in MRTK v2 via #3749. The example scene contains a Unity UI dropdown that works with the MRTK.
