### ISSUE TITLE
Sharing UNet Missing assembly reference

### ISSUE THREAD

**Issue by reillydonovan** [Microsoft/MixedRealityToolkit-Unity#1631]
## Overview
Building works on my main machine but when setting up to build on another machine I am returned 23 errors all concerning SharingWithUNET Holotoolkit-Examples, starting with this one:
```
Assets\HoloToolkit-Examples\SharingWithUNET\Scripts\NetworkDiscoveryWithAnchors.cs(18,48): error CS0246: The type or namespace name 'NetworkDiscovery' could not be found (are you missing a using directive or an assembly reference?)
```
Using VS 15.4.4 on main machine, 15.5.3 on new machine

## Expected Behavior
to properly build

## Actual Behavior
returned errors 

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2017.1.1.f1

## Mixed Reality Toolkit Release Version
The last one supported on 2017.1.1.f1

**Comment by StephenHodgson** [comment]
What do your build settings look like?

**Comment by keveleigh** [comment]
Unable to repro in recent releases. Please re-open if you're still seeing this.
