### ISSUE TITLE
Headset Adjustment Scene is missing assets

### ISSUE THREAD

**Issue by ARGs-code** [Microsoft/MixedRealityToolkit-Unity#1635]
## Overview
The Headset Adjustment Scene Readme lists a variety of features for this scene which simply are not present.
## Expected Behavior
From the ReadMe- "This scene shows a border at the edge of the user's field of view and instructs him/her to adjust the headset until all four edges are visible. The user (or the demonstrator) can then air-tap or say "I'm ready" to proceed to the actual experience.

This scene is designed to be the first scene the user sees, once the experience is ready to begin. Once the user is ready, it loads either the next scene in the sequence or a scene specified by the NextSceneName property of the HeadsetAdjustment script."

## Actual Behavior
Scene only contains a script to load new scenes, and nothing else. No other assets outside of standard MR Toolkit Prefabs are present either in the scene or in the scene folder.

## Steps to reproduce
Set Headset Adjustment Scene to your active scene, add to your build. Build and deploy. You will see that nothing happens either in the editor or in the hololens.

## Unity Editor Version
2017.2.1f1 & 2017.3.0f3

## Mixed Reality Toolkit Release Version
Current Release available as of 1/15/2018

**Comment by FlorianJa** [comment]
It seems like the content of the scene (edges, text etc) were removed in 
https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/b85895f746c458027de73142a020ed78e67e46e1#diff-0b0aaf2f2c0da5a2409ea65797f94fcf

**Comment by FlorianJa** [comment]
should by fixed by #2054 #2055 and #2058

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
