### ISSUE TITLE
Keyboard prefab and Hololens gaze/airtap

### ISSUE THREAD

**Issue by Taghazog** [Microsoft/MixedRealityToolkit-Unity#1641]
## Overview
Hello Microsoft,

Probably a stupid question here but I couldn't find the answer as there is no clear documentation on that:
While the keyboard works pretty well in Unity with the mouse... how is it supposed to work in Hololens? How do we gaze at the keys, and how do we trigger the unity Button.onclick with the airtap...?

It seems nobody had the problem here, so I may have missed something pretty simple, and Holotoolkit samples could probably work if there was ones with keyboard, but i don't know how to trigger the unity button.onclick on Hololens on a custom project using this prefab, as the gaze doesn't collide with the buttons and then cannot trigger them with the airtap gesture.

Thank you!

## Unity Editor Version
2017.1.2f1

**Comment by Weasy666** [comment]
Did you set the Event Camera of the Keyboard Canvas to the HoloLensCamera?
![image](https://user-images.githubusercontent.com/11967542/35065295-2a869232-fbcd-11e7-8968-b67e7134362a.png)

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
