### ISSUE TITLE
Motion controller model not always loaded when playing in Editor

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#1645]
## Overview
Motion controller model not always loaded when playing in Editor
## Expected Behavior
Motion controller model loaded when playing in Editor
## Actual Behavior
Sometimes the motion controller model is not loaded when playing in Editor
## Steps to reproduce
Play in editor
Immediately activate the window of another program

I made a little debug taking a look at the source code of MotionControllerModel.dll.
The dll make a request of SpatialInteractionManager for the active window, so if you change the window when the toolkit is trying to get the model, the model is not loaded.
I modified the code of the dll to trace some messages.

When the model is not loaded because the active window is not Unity I get:
![image](https://user-images.githubusercontent.com/17752475/35069941-f4aae1d6-fbdb-11e7-86d6-7eebb1b1cbdd.png)

When the model is loaded the active window is with class name 'UnityHoloInEditorWndClass' and I get:

![image](https://user-images.githubusercontent.com/17752475/35070025-4f145904-fbdc-11e7-8119-05b86b784087.png)

Sometimes also if the focus is on Unity, the model is not loaded. In this case the active window is with class name 'UnityContainerWndClass' (the main window of Unity):
![image](https://user-images.githubusercontent.com/17752475/35070222-e03e7a54-fbdc-11e7-9660-a4bd1a5af755.png)

When the model is not loaded it seems that Unity doesn't have a top level window with class name 'UnityHoloInEditorWndClass':
![image](https://user-images.githubusercontent.com/17752475/35070419-86940d6a-fbdd-11e7-8369-72fbd94272eb.png)

When the model is loaded it seems that Unity always has a window with class name 'UnityHoloInEditorWndClass' but it is not a top level window:
![image](https://user-images.githubusercontent.com/17752475/35070482-bd615f64-fbdd-11e7-904e-6ab814866145.png)

When the model is not loaded this two workarounds can be usefull:
1) Stop the app, close the portal and restart the app letting Unity to start the portal.
or
2) Stop the app and switch off the controllers. Start the app and then switch on the controllers.

## Unity Editor Version
2017.3.0f3
## Mixed Reality Toolkit Release Version
Current release

**Comment by DDReaper** [comment]
The gLTF loader is being updated with the latest version from the provider, so this test case will need re-testing then. 
Nut it sounds like a Unity importer issue with them disposing but not properly regenerating internal code when the Unity editor goes out of focus.

**Comment by ivan2007** [comment]
Ok, let me know when I can test it again
Thanks
Ivan

**Comment by keveleigh** [comment]
@DDReaper this is coming from the [Editor loading DLL](https://github.com/Microsoft/MixedRealityToolkit/tree/master/UnityEditorMotionControllerModelDLL) I wrote in the native Toolkit and is in the layer before the model gets to the glTF loader.

I've seen this as well, but haven't yet been able to properly debug, so this info is incredibly helpful!

@ivan2007 Do you think this is a bug in the DLL, where perhaps we're running into a race condition where we ask for the sources before that window is created? Or do you think there's a Unity bug, where they're inconsistently creating that window?

**Comment by keveleigh** [comment]
Also, @ivan2007, does changing the call to `GetActiveWindow()` in line 23 to `FindWindow(L"UnityHoloInEditorWndClass", NULL)` improve consistency?

**Comment by ivan2007** [comment]
@keveleigh, that was the first solution that I tried but it is not sufficient. It seems that a windows with class name 'UnityHoloInEditorWndClass' is necessary but not sufficient to load the models.
I think that we are not running into a race condition because the models are loaded only when the sources are detected from Unity.
The best solution could be if unity tell us what is the window that detected the sources. 
I think that ask for the current active window is not robust but I think also that there is a Unity bug.
Ivan

**Comment by ivan2007** [comment]
@keveleigh, in this case the class name of the active window is 'UnityHoloInEditorWndClass' but there aren't sources for that window:
![image](https://user-images.githubusercontent.com/17752475/35099049-daccc6aa-fc56-11e7-8801-cd31f6b14a30.png)
I can't understand this.
I think we need more details from Unity on how they register that class and then they create the holographic window.
Ivan

**Comment by ivan2007** [comment]
@keveleigh,
I have attached the code of MotionControllerModel that I am using for the test.
The strategy to find UnityHoloInEditorWndClass is this:
1) Search for top level windows
2) Search for all windows of Unity process
3) Active window
Now the correct window seems always found.
I have still seen cases (rare) where no sources are found for the correct window.
I think that another critical point could be the call GetDetectedSourcesAtTimestamp.
We don't know what was the exact time when the source has been detected.
SpatialInteractionSourceState has a property with the time stamp but the Unity class InteractionSourceState no.


[MotionControllerModel.zip](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/1649341/MotionControllerModel.zip)

**Comment by ivan2007** [comment]
@keveleigh,
Looking better at the toolkit code I see that StartTrackingController is not only called when the source is detected but even before (Awake). I think that this could be a problem because in my tests I saw that if I call GetCurrentReading immediately before TryGetMotionControllerModel sometimes there aren't source available. In this moment I can't test that but I think that could explain what I have seen.

**Comment by StephenHodgson** [comment]
@keveleigh 

![image](https://user-images.githubusercontent.com/13334553/35316505-d30235fc-0086-11e8-9cd5-50273363376e.png)

Keep getting these exceptions from the controller model dll as well.  Not sure if it's related.

**Comment by designnomad** [comment]
Hello, 

I am using 2017.2.0p2-MRTP5 build, and having the same issue. 

![errormessage](https://user-images.githubusercontent.com/1609471/35601668-20d7831a-05e9-11e8-80eb-4255d6f8efe1.PNG)

**Comment by keveleigh** [comment]
This should be fixed in the 2017.4.3 release. Please reopen if not.
