### ISSUE TITLE
Objects split into base colors

### ISSUE THREAD

**Issue by marjackarpinski** [Microsoft/MixedRealityToolkit-Unity#1647]
## Overview
When updated to newest version of Mixed Reality Toolkit, there appears to be an issue with displaying objects on HoloLens. Objects base colors separate when moving around.
Made a scene with a single cube using Mixed Reality Toolkit Toolbar button to set up the scene and project settings. The same issue appears on example scenes from Mixed Reality Toolkit.

## Expected Behavior
Objects are stable and colors of an object do not separate

## Actual Behavior
  All objects within the scene split into base colors the same as described in "color separation" section in the documentation https://developer.microsoft.com/en-us/windows/mixed-reality/hologram_stability

Note: Already installed all essential software mentioned in "2017.2 Upgrade Guide for Window Mixed Reality" 

## Steps to reproduce
https://github.com/marjackarpinski/HL_Test

## Unity Editor Version
2017.2.1f1

## Mixed Reality Toolkit Release Version
2017.2.1.1

**Comment by NeerajW** [comment]
This is due to a Unity bug: https://issuetracker.unity3d.com/issues/hololens-jittering-3d-model-causing-color-separation-possibly-due-to-incorrect-stabilization-plane

@StephenHodgson, did the StabilizationPlane script removal from InputManager prefab get checked in to latest release?

**Comment by StephenHodgson** [comment]
No, it did not.

**Comment by NeerajW** [comment]
Got it. Added that as plan for 2017.3 release in the road map PR #1651

**Comment by StephenHodgson** [comment]
Yup.  I plan to address that in #1549 as well.

**Comment by marjackarpinski** [comment]
Thank you guys for the help!

**Comment by yeahbunny** [comment]
@StephenHodgson, @NeerajW guys, do we know when it will be fixed? We need rapidly deploy the new app and we would like to be up to date with new MRTK. Thanks for the answer.

**Comment by jghospital** [comment]
Acording to Unity fix report https://issuetracker.unity3d.com/issues/hololens-jittering-3d-model-causing-color-separation-possibly-due-to-incorrect-stabilization-plane it will be fixed in nest update of Unity version, hoping it will also get fixed with previous versions of MRTK.

**Comment by HoloLensDev** [comment]
Is not fixed in Unity 2017.3.1f1, right?
