### ISSUE TITLE
Grip Position/Rotation is not in SupportedInputInfo 

### ISSUE THREAD

**Issue by romsahel** [Microsoft/MixedRealityToolkit-Unity#1653]
The enum `SupportedInputInfo` contains `Position `and `Rotation` which correspond to the Pointer's position and rotation (see `InteractionInputSource.GetSupportedInputInfo`). 
Thus, `eventData.InputSource.SupportsInputInfo(sourceId, SupportedInputInfo.Position)` always return `false` on the Hololens' InputSource. 
It seems the `SupportedInputInfo` enum needs two new members: `GripPosition` and `GripRotation`; and `InteractionInputSource.GetSupportedInputInfo` needs to be changed accordingly.

**Comment by StephenHodgson** [comment]
A lot of that stuff is going to change in the Input System refactor. I'll be sure to address this there.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
