### ISSUE TITLE
Add Coding Guidelines that follow MSDN standard.

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1660]
## Overview
We should probably add the MSDN as a reference for our coding standards and fix/update anywhere where these guidelines are not being followed in the code for constancy.

**Comment by NeerajW** [comment]
There are tools to enforce this if we truly want to embrace this the right way.

**https://github.com/StyleCop/StyleCop

Project Description**
StyleCop analyzes C# source code to enforce a set of style and consistency rules. It can be run from inside of Visual Studio or integrated into an MSBuild project. 

**Core Principles**

- StyleCop provides value by enforcing a common set of style rules for C# code. StyleCop will continue to ship with a single, consistent set of rules, with minimal rule configuration allowed. Developers can implement their own rules if they so choose. 
- StyleCop ships with the ability to seamlessly integrate with Visual Studio, MSBuild, TFS, etc. Developers are free to implement custom code to integrate StyleCop into other development and tooling environments, as described in the documentation.

**Comment by DDReaper** [comment]
VS2017 already dose a great job of enforcing coding warnings.  Agree, we should check all the scripts and standardise them.
I have fixed a few (by accident) in the Namespace refactor, but it needs to be more global.
