### ISSUE TITLE
Missing Script References in SolverExamples

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1661]
## Overview
Missing Script references in the SolverExamples scene.

## Mixed Reality Toolkit Release Version
48a9ac506c430325340e248c8421604e54de1804

**Comment by keveleigh** [comment]
![image](https://user-images.githubusercontent.com/3580640/35303065-8cb8334e-0045-11e8-959f-b7597222d129.png)

@radicalad Any idea what these might have been?

**Comment by keveleigh** [comment]
![image](https://user-images.githubusercontent.com/3580640/35304649-1ef89992-004b-11e8-94cd-3ff5a172fbe8.png)

Looks like it was a Solver Controller Finder script, which no longer exists in favor of Solver Handler inheriting `ControllerFinder`.

**Comment by StephenHodgson** [comment]
So just removing the script references is a valid fix?

**Comment by radicalad** [comment]
Yep. I tested it when we switched to ControllerFinder -> SolverHandler. I just didn't notice the missing script references because everything ran fine. Sorry guys - my bad.
