### ISSUE TITLE
Input for the hololens not being processed properly by some Input interfaces

### ISSUE THREAD

**Issue by Wilsoner** [Microsoft/MixedRealityToolkit-Unity#1662]
## Overview
IInputHandler will receive input just fine in the editor with editor hands input, but when built to the hololens it will not correctly detect the input type and it will think the type has no positional data
## Expected Behavior
build to hololens, tap down, get a position of the input. 
## Actual Behavior
get an output with BaseObject:cannot be shown in debug mode or something similar for sourceType, and there is no positional data
## Steps to reproduce
https://spheregen-my.sharepoint.com/:u:/p/eric_wilson/EcPLubnvhUVAvsSRyhRVjpwBR6vrIdCaTH4gZVXXuFqlng?e=i6Vvvd

open the zipped project
test tapping on the cube in the editor with the editor hands and read the output, see that there is positional data
build and deploy to the hololens. tap the cube but see that there is no positional data

## Unity Editor Version
2017.2.1
## Mixed Reality Toolkit Release Version
2017.2.1

**Comment by StephenHodgson** [comment]
@Wilsoner Do you have a copy of the project on github?

**Comment by StephenHodgson** [comment]
I'll be sure to address this in #1603

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
