### ISSUE TITLE
Class FileSystemHelper: FileStream and BinaryWriter not disposed in case of Exception

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#1663]
## Overview
Class FileSystemHelper: FileStream and BinaryWriter not disposed in case of Exception
## Expected Behavior
FileStream and BinaryWriter disposed also in case of Exception (using construct)
## Actual Behavior
FileStream and BinaryWriter not disposed in case of Exception
## Steps to reproduce
See the source code.

## Unity Editor Version
2017.3.0f3
## Mixed Reality Toolkit Release Version
Current master

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
