### ISSUE TITLE
Add SpritePackerMode to applied project settings

### ISSUE THREAD

**Issue by Zod-** [Microsoft/MixedRealityToolkit-Unity#1664]
## Overview
The sprite atlas or sprite packer is required for better keyboard performance. It has to be turned on in the project settings which is currently missing in the setup setps.
## Expected Behavior
Turn on sprite packer mode when applying MR project settings. The setting can be found at  `EditorSettings.spritePackerMode = SpritePackerMode.AlwaysOn`.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
