### ISSUE TITLE
Update KeyboardAtlas references

### ISSUE THREAD

**Issue by Zod-** [Microsoft/MixedRealityToolkit-Unity#1665]
## Overview
Files and Folders got moved around but the references in the KeyboardAtlas did not get updated. This causes the Keyboard to run slightly worse than before as it can't make the best use of drawing batches.

## Solution
I can fix the atlas so that it's up to date again, however this seems like a short term solution as it's quite easy to break the atlas. Moving sprites, folders and adding new sprites to the keyboard all require a manual update of the atlas. 
A better solution would probably be a `IPreprocessBuild` script that grabs all the sprite locations from the keyboard prefab and adds them to the atlas to automate this process.

**Comment by keveleigh** [comment]
Fixed via #1764
