### ISSUE TITLE
Agree and standardise all #IF definitions for the MRTK

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#1667]
## Overview
Currently several different #IF statements are used across the MRTK solution.  These need to be standardised across the code.

## Expected Behavior

Agree expected / standardised definitions

 - UNITY_EDITOR - Obvious, editor only code
 - MRTK_WSA - UWP targeted platforms and MR (will define UNITY_WSA)
 - MRTK_OPENVR - SteamVR target platform (future reserved, will define UNITY_STANDALONE)
 - MRTK_OPENXR - Future reservation for OpenXR

We should also avoid UNITY_VERSION_XX if possible, or have a generic definition for managed versions (define once and reuse internal definition, so it's easier to change / maintain)

**Comment by StephenHodgson** [comment]
> MRTK_OPENVR 

Is this defined by Unity?

**Comment by StephenHodgson** [comment]
> UNITY_VERSION_XX

After 2017.3 there's no way to support backwards capabilities in the editor, so that PR removed most of those.

**Comment by StephenHodgson** [comment]
> MRTK_WSA - UWP targeted platforms and MR (will define UNITY_WSA)

This seems rather confusing. Not sure I like this idea.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
