### ISSUE TITLE
UI works fine in the editor but, is corrupted when deployed to the HoloLens

### ISSUE THREAD

**Issue by dtb49** [Microsoft/MixedRealityToolkit-Unity#1668]
## Overview
I am in the process of creating a UI system for my application and the UI looks great in the editor but, whenever I deploy to the HoloLens the UI always renders pink. I am really trying to instantiate the UI at runtime and thinking that it might be some type of error on my part so I placed it directly in the hierarchy instead and it still renders pink on the HoloLens. 

I ported this UI from an older version of Unity(2017.1) and removed all the scripts associated with it and only kept the image scripts for it. Does anyone know why this would happen? 

I also added a new Panel and changed the canvas to world space and it rendered pink for it as well when deployed to the HoloLens.

## Expected Behavior
UI to render normally

## Actual Behavior
UI renders pink/corrupted

## Unity Editor Version
Unity 2017.3

## Mixed Reality Toolkit Release Version
latest

**Comment by Firifire** [comment]
I believe you should try with Unity 2017.2.0f3.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
