### ISSUE TITLE
Problem creating another 3D Text Font Material

### ISSUE THREAD

**Issue by dtb49** [Microsoft/MixedRealityToolkit-Unity#1671]
![fontcompare](https://user-images.githubusercontent.com/10440063/35460057-25fea6fa-02a8-11e8-97ff-54d1f3e290c6.png)

Basically I have a font file, Franklin Gothic, I have imported it to Unity and followed all of the steps mentioned in the 3DText ReadMe file. I'm not sure if this is a Unity bug or not but, I have tried importing two or three other fonts and it hasn't worked for them either. 

I believe the problem lies with either the font file or how Unity handles font file importing. As you can see in the picture that looking at the selawk (example font) the Font Material shows up which I believe is the reason that it works correctly. However, after importing two or three fonts and none of them showed up like this one I feel as this is either a bug or maybe I just am getting something wrong or maybe even missing a step. 

I have created the material and attached to a text prefab. I was able to successfully replicate the selawk in 3D but, none of the others. If anyone could give me a hand with this it would be very grateful.

Thank you!

**Comment by cre8ivepark** [comment]
@dtb49 Could you please let us know which Unity version you are using?

**Comment by dtb49** [comment]
I used 2017.1.0  and later 2017.3 and I haven't been able to get it to work in either of these versions.

**Comment by cre8ivepark** [comment]
@dtb49 I tried with Franklin Gothic font but I was not able to repo the issue. (screen shot below shows proper font & occlusion)
1. Imported TTF font file
2. Duplicated 3DTextSelawik material, renamed it to 3DTextFranklinGothic
3. Duplicated 3DTextPrefab, renamded it to 3DTextPrefabFranklinGothic
4. Assigned TTF font file's texture to 3DTextFranklinGothic material
5. Assigned 3DTextFranklinGothic material to 3DTextPrefabFraklinGothic

![2018-02-02 10_02_31-unity 2017 3 0f3 64bit - untitled - mixedrealitytoolkit-unity - pc mac linu](https://user-images.githubusercontent.com/13754172/35747756-523af2d4-0800-11e8-8c66-9ba54e08e7f8.png)

**Comment by dtb49** [comment]
That is quite odd, after you did it I went back and duplicated the material and then changed out the texture over it, works fine now. I must have missed a step or something when creating the material before.

**Comment by cre8ivepark** [comment]
@dtb49 Thank you for your confirmation!
