### ISSUE TITLE
Billboard PivotAxis.Free only rotates around X and Y

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#1672]
## Overview
Related to #208 (XY can be defined to replace the current Free behavior) and #383.

This happened with the removal of the `Quaternion.LookRotation` up vector at line 76 in https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/37247d9489910735b833f5bb20b3be840a07a5b0#diff-40903bdeebaf71c08a776607e5cb91e0

## Expected Behavior
Billboards with a "free" pivot axis should rotate around all three axes.

## Actual Behavior
Billboards with a "free" pivot axis only rotate around X and Y.

## Steps to reproduce
1. Place Billboard.cs on an object in a scene.
2. Set the Pivot Axis to Free.

## Unity Editor Version
Any

## Mixed Reality Toolkit Release Version
Any

**Comment by keveleigh** [comment]
I'm also open to discussion on if Billboard should even support the Z axis. I'm not sure how useful it really is...

**Comment by davidkline-ms** [comment]
I have no problem with granting devs the power to have billboard rotate around any axis they wish. a VERY early version of this script did just that :)
