### ISSUE TITLE
Create standard Examples docs template for MRTK Examples

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#1674]
## Overview
Following a review of the updated examples in #1669
We need a standardised template for the Example Readme's 

These should detail
- Title
- High level overview
- screenshots
- Example usage
- Further reading

(Preliminary title suggestions)

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
