### ISSUE TITLE
Update each example scene to have standardized components

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#1675]
## Overview
Following a review of the updated examples in #1669

Each scene should apply a standard look and feel for all MRTK examples, comprising of:

 - A Standard Skybox (recommending a plain light grey box, as used in the MotionControllersTest scene)
 - A Standard set of colours (like in the MotionControllersTest Scene)

Effectively, each example should look and feel the same, so the user knows what to expect.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
