### ISSUE TITLE
MRDK AppBar Billboarding

### ISSUE THREAD

**Issue by tspaddock** [Microsoft/MixedRealityToolkit-Unity#1677]
## Overview
I have implemented the Appbar within my project and it is not billboarding as expected. All other functionality works correctly.

## Actual Behavior
Appbar focus remains only on original location of default hololens camera position.

## Steps to reproduce
Click on gameobject as required. Appbar appears...

## Unity Editor Version
2017.1.1f1
## Mixed Reality Toolkit Release Version
Most recent release.

**Comment by Railboy** [comment]
Hi @tspaddock - if you do a pull request we can take a look at your implementation.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
