### ISSUE TITLE
AutoJoinSessionAndRoom's vague connection/disconnection logic

### ISSUE THREAD

**Issue by rafek** [Microsoft/MixedRealityToolkit-Unity#1680]
This is not real issue I guess, I'm just trying to understand how [AutoJoinSessionAndRoom script](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Sharing/Scripts/Utilities/AutoJoinSessionAndRoom.cs) works and I can't get why `Start()` method and `SessionTrackerDisconnected()` are implemented the way they are.

Namely:

1. Why in `Start()` there is autoconnect being fired *only* when not connected to `SharingStage`? What if by any chance `SharingStage` connects before this scripts starts?
2. ~Why `SessionTrackerDisconnected()` calls autoconnect logic? This is the method being called on server disconnected event also, so what's the point of calling autoconnect?~

If it's all on purpose, then I think I don't understand something here :)

EDIT: Disregard the 2nd point. I seems that autoconnect feature is not only for when application starts but also when the user would be disconnected from the session somehow.

**Comment by StephenHodgson** [comment]
>Why in Start() there is autoconnect being fired only when not connected to SharingStage?

So we can subscribe to our connection events.

>What if by any chance SharingStage connects before this scripts starts?

Then we ask it to disconnect and attempt to reconnect again so we get into a good state.

**Comment by rafek** [comment]
If `SharingStage` is connected before this script runs, the only piece of code that runs is:

```csharp
private void SharingManagerConnected(object sender = null, EventArgs e = null)
{
    SharingStage.Instance.SharingManagerConnected -= SharingManagerConnected;
    SharingStage.Instance.SessionsTracker.ServerDisconnected += SessionTrackerDisconnected;
}
```

There's no action for disconnect anywhere, is there?

**Comment by StephenHodgson** [comment]
>There's no action for disconnect anywhere, is there?

Disconnection events only get raised by the sharing stage. This class listens for it and attempts to automatically reconnect.

If you're trying to make a matchmaking type system, you won't want to use this script.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
