### ISSUE TITLE
Can't update device's status in the application.

### ISSUE THREAD

**Issue by RoCk3TL** [Microsoft/MixedRealityToolkit-Unity#1691]
## Overview
The motion controllers' input and the headset tracking can only be detected and set BEFORE i open my 
master build UWP application. It's highly likely that i set something wrong in the Unity, but i still need to know how to fix it.（They work perfectly in play mode）
 
## Expected Behavior
I can power on the motion controller or set the headset tracking AFTER i open my application, and still get the correct tracking.

## Actual Behavior
I have to power on the motion controller and make sure the headset already got the tracking signal BEFORE i start my application, otherwise they won't work correctly.

## Unity Editor Version
Unity 2017.2 MRTP5

## Mixed Reality Toolkit Release Version
2017.2.1.1

**Comment by keveleigh** [comment]
This sounds like a controller detection bug that I believe was present in MRTP5. Please re-open if you're still seeing this issue, but this should have been resolved in later versions of Unity. The [current recommendation](https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools#installation-checklist-for-hololens) is Unity 2017.4.
