### ISSUE TITLE
What is the future of Grab Mechanics?

### ISSUE THREAD

**Issue by jbienzms** [Microsoft/MixedRealityToolkit-Unity#1692]
## Background
Our team is working on a sample library that makes it easy to capture online and offline analytics in Mixed Reality applications. You can read about the project and download it from here:

[Mixed Reality Analytics Sample](http://www.roadtomr.com/2018/02/02/2430/mr-analytics-sample/)

We currently track events like GazeEnter, PointerEnter, GazeExit, PointerExit. We would also like to track events like Grab and Release.

The [VRTK](http://vrtk.io) has supports grab interactions through [VRTK_InteractableObject](https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/Scripts/Interactions/VRTK_InteractableObject.cs) and [VRTK_InteractGrab](https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs). [NewtonVR](http://www.newtonvr.com) has a similar concept through [NVRInteractable](https://github.com/TomorrowTodayLabs/NewtonVR/blob/master/Assets/NewtonVR/NVRInteractable.cs). 

Unfortunately the MRTK doesn't seem to have a core concept of Grab and Release. There is a sample called [Grab Mechanics](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit-Examples/MotionControllers-GrabMechanics) that appears to be a "semi-official" way of doing it, but it currently only exists as a sample. It is not part of the core toolkit.

## Question
We are hoping to build analytics in a way that it does not _depend_ on any particular library, but where possible we would like to integrate it in the most sensible way that makes it easiest to use.

What will become of the Grab Mechanics sample? Will it remain only just a sample in the **HoloToolkit-Examples** folder, or will the many interfaces and scripts that are part of this sample be merged into the core toolkit?

**Comment by DDReaper** [comment]
Hi @jbienzms 
This has been a subject of much discussion of late, with the general consensus that the "Toolkit" should provide a much more unified and standard way for implementing interactions in to any project, similar in the way VRTK does.

The thinking being that their should be "prefabs" or some other standard mechanism that will be part of the MRTK to simply add to a "thing" to enable those features.  This will also make such interactions a lot easier to implement for consumers.

**Comment by jbienzms** [comment]
I like the thinking there. And I do like what VRTK has done in this area. So what is the current thinking as far as who would take on this work and when it might get scheduled? I'd like to make sure the analytics project has _at least_ as good support for MRTK as it does for VRTK.

**Comment by Railboy** [comment]
> Unfortunately the MRTK doesn't seem to have a core concept of Grab and Release. 

This is something we are working on incorporating into the input system via **Focusers**.

Once Focusers are part of the core input system, Touch / Untouch and Grab / Release will be refactored as 'flavors' of Focus / Unfocus.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
