### ISSUE TITLE
Feature Request: HandDraggable with variables to be able to lock certain axis upon drag/move

### ISSUE THREAD

**Issue by dtb49** [Microsoft/MixedRealityToolkit-Unity#1696]
I'm in the process of modifying HandDraggable where the user has the ability to drag an object on a certain axis. For example locking an object's x and z axis and only modifying the y. I feel that this would be a great feature to add to the MRTK. Possibly do something like they did with the Rotation Mode and make an enum for Positioning mode. Something like free axis, move X, move Y, move Z. I wrote the logic up kind of quick:

this would go under the UpdateDragging method just beneath the draggingPosition assignment. The only modding necessary would be to change under the Lerp function to just draggingPosition and adding the enum as a variable

`            draggingPosition = pivotPosition + (targetDirection * targetDistance);

            //if we set it to something other than default set the lock variables to our original position and move variable to stay the same
            if (PositionMode == PositionModeEnum.MoveX)
            {
                draggingPosition = new Vector3(draggingPosition.x, HostTransform.position.y, HostTransform.position.z);
            }
            else if (PositionMode == PositionModeEnum.MoveY)
            {
                draggingPosition = new Vector3(HostTransform.position.x, draggingPosition.y, HostTransform.position.z);
            }
            else if (PositionMode == PositionModeEnum.MoveZ)
            {
                draggingPosition = new Vector3(HostTransform.position.x, HostTransform.position.y, draggingPosition.z);
            }
            //else if default grab the direction value
            else{
                draggingPosition += cameraTransform.TransformDirection(objRefGrabPoint);
            }`

A better way to do this is probably to grab the user's direction and incorporate it into the calculation. But my main need for this is the Y axis and it would be really hard to mess that up haha.

**Comment by StephenHodgson** [comment]
Why not just use the INavigationHandler?

**Comment by dtb49** [comment]
I honestly haven't ever used it before and don't really know what it can do. I have watched a couple of your videos though and they've definitely helped me out with learning the different features of the MRTK. Keep it up!

I just thought of this solution so I can easily switch between one axis movement and free axis movement if I wanted to. I'm sure there are better ways to do this. This is just the first one I thought about in like five or ten minutes and a lot of the objects in my apps have a HandDraggable script on them so I was pretty familiar with that script.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
