### ISSUE TITLE
Keyboard and KeyboardInputField not receiving tap events

### ISSUE THREAD

**Issue by Bazilikum** [Microsoft/MixedRealityToolkit-Unity#1700]
## Overview
The KeyboardInputField and the Keyboard dont seem to receive tap events, only mouse click events.
**edit using toolkit 2017.2.1.1: KeyboardInputField receives events, but the Keybord is not a collider for the gaze**

## Expected Behavior
Tap events would be converted to mouse click events and pass through to the keyboard and input field
**edit using toolkit 2017.2.1.1: KeyboardInputField receives events, but the Keybord is not a collider for the gaze so cant tap on keys**

## Actual Behavior
Tap events are not passed, only mouse click events.
**edit using toolkit 2017.2.1.1: Keyboard is a collider for the gaze**

## Steps to reproduce
Create a KeyboardInputField and a Keyboard instance in a scene, play and try to edit the input field.
Will work in editor (mouse click)
Will work in emulator (when using mouse input)
Wont work in emulator and device (when using tap)
**edit using toolkit 2017.2.1.1: Input field works, keyboard inaccessible to tap**

## Unity Editor and Toolkit versions
Latest working we could find:
Unity 2017.1.2f1
MRTK 2017.1.2
SDK 10.0.16299.0
Doesnt seem to work on any later combination.
**see edits**

## Our current workaround:
Added the IInputClickHandler interface and converted Tap events to Mouse click events for the following classess:
KeyboardInputField, KeyboardValueKeys, KeyboardKeyFunc

**Comment by Bazilikum** [comment]
**edit using toolkit 2017.2.1.1: KeyboardInputField works, Keyboard is not a collider**

**Comment by keveleigh** [comment]
I'm not able to repro this. The MRTK keyboard is working for me in the KeyboardTest example scene. Are you still seeing this issue?
