### ISSUE TITLE
Simple Tagalong does not move back/forth

### ISSUE THREAD

**Issue by Firifire** [Microsoft/MixedRealityToolkit-Unity#1701]
## Overview
So I noticed that when I turn around until I the object is out of the view frustum, and the object comes back in the view like it should, but if you move back or forward immediately when after it is back in view, for few moments the object wont move and then suddenly it warps to the tagalong distance.
## Expected Behavior
Moves along the user at all times while staying in the frustum.
## Actual Behavior
Does not move along when interpolator is running
## Steps to reproduce
Add A cube to the scene, add a simple tagalong script to the cube.
Script Settings > Default
## Unity Editor Version
2017.2.0f3
## Mixed Reality Toolkit Release Version
2017.2.1.0

**Comment by StephenHodgson** [comment]
I think the sphere based tagalong performs a lot better.

Try using that one instead.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
