### ISSUE TITLE
run SpacialProcessing in a loop at the scanning interval

### ISSUE THREAD

**Issue by brean** [Microsoft/MixedRealityToolkit-Unity#1702]
## Overview
I like to rerun the plane finding whenever the ObjectSurfaceObserver did its update.

## Expected Behavior
I think adding an UnityEvent that can be Invoked in the Update-function of ObjectSurfaceObserver could do the trick.

## Actual Behavior
The Update-functions in ObjectSurfaceObserver and SpatialMappingObserver are private, so to me it looks like there is no trigger for the plane-finding after a surface-scan update.

I am also wondering if there is a better way to find walls/run plane finding

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
