### ISSUE TITLE
SharingTest not working, Anchor data invalid

### ISSUE THREAD

**Issue by fraspadafora** [Microsoft/MixedRealityToolkit-Unity#1713]
## Overview
I'm trying to run the SharingTest demo, but anchors are not valid and not uploaded to the sharing service. 
I tried with 4 different Hololens, removing the Spaces, creating the anchors after 10 seconds, creating a custom scene but there is no solution.
![20180212_213018_hololens](https://user-images.githubusercontent.com/10370697/36118376-224f03ae-103d-11e8-878c-eea7900aae20.jpg)

## Expected Behavior
SharingTest demo on two Hololens connected to the Sharing Service and sharing the WorldStage anchor of the first hololens connected. 

## Actual Behavior
When running the first Hololens and running the SharingTest, the Anchor is not uploaded.
The anchor data is 0 bytes. I checked the size in the method "ExportComplete" of SharingWorldAnchorManager class, line 588
`if (rawAnchorUploadData.Count < MinTrustworthySerializedAnchorDataSize)`

The demo worked fine 2-3 times, uploading the anchors, after that it never worked again, I tried with 4 Hololens and it is not working.

## Steps to reproduce
Just compile the SharingTest project and run it on the Hololens.

## Unity Editor Version
2017.3.1f 64Bit
I tried also with 2017.2.1f and it is not working.

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-2017.2.1.1

**Comment by StephenHodgson** [comment]
How much data was the anchors generating?

**Comment by fraspadafora** [comment]
Hi @StephenHodgson 
The anchor data is 0 bytes.
I checked the size in the method "ExportComplete" of SharingWorldAnchorManager class, line 588

` if (rawAnchorUploadData.Count < MinTrustworthySerializedAnchorDataSize)`

The weird thing is that it worked 2-3 times, and then suddendly it never worked again in anyone of the devices.

Do you have any idea of why the anchor is creating is empty?

**Comment by StephenHodgson** [comment]
From your video the lighting seemed to be really low. I'd suggest making sure that your ambiabt lighting is brighter.

**Comment by fraspadafora** [comment]
I tried also in my office with lot of light, but the problem persists.
My tries at the moment are:
- Different places (Home, Office)
- Different WiFi
- Unity 2017.3.1f and Unity 2017.2.1f
- HoloToolkit-Unity-2017.2.1.1
- 4 Hololens

Any further suggestion?

**Comment by mschnabel** [comment]
Unity: 2017.2.0f3 (also tested with 2017.3.1p1)
MRTK: 2017.2.1.0

I have a similar problem with the Sharing Service and the anchors. When I launch our Unity app on a Hololens and connect to the sharing server, everything looks fine and the anchors get updated (the debug text says so). When I launch the app on a second Hololens and connect to the same room via sharing service, the debug texts says that the anchor data is invalid.

I can also see that the shared holograms which are seen by both devices (this is actually working fine) are not in the same space in the real world. I would assume that the invalid anchor data is referring to my SharedWorldAnchor - therefore the anchors are at different positions on both devices because the update won't work correctly. 

Maybe my problem is related to this one from @fraspadafora .

**Comment by fraspadafora** [comment]
I'm doing other test. I think the problem is in the order of execution of the Netowrk scripts.
- Sharing Stage
- SharingWorldAnchorManager
- AutoJoinSessionAndRoom

I'm checking this.

**Comment by FCuttino** [comment]
Hello @fraspadafora!

I may have had this exact same issue.

You might need to enable the SpatialPerception capability for your Unity project. 
It is located under Edit -> Project Settings -> Player -> Publishing Settings

**Comment by daxuewuqing** [comment]
I had the same problem.Have you solved the problem?

**Comment by daxuewuqing** [comment]
Hi @StephenHodgson

**Comment by maguileracanon** [comment]
Same thing here. I am sure I have the SpatialPerception capabilities enabled
Unity: 2017.2.0f3 I updated the MRTK but it keeps happening . Also happens with the Holograms 240 tutorial files, the  Complete version keeps getting the Log
**denied access to WorldAnchor serialization**
Any ideas?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
