### ISSUE TITLE
Application stuck after the "Trying to map your surroundings" window pops-up

### ISSUE THREAD

**Issue by Cycov** [Microsoft/MixedRealityToolkit-Unity#1714]
## Overview
When Hololens can no longer recognize the environment the application is stuck, with the "Trying to map your surroundings" stuck in front of the user, without any animation.
## Expected Behavior
Hololens to map the surroundings once it can, and remove the "Trying to map your surroundings" window afterwards, allowing the user to continue using the application.
## Actual Behavior
The message remains stuck and follows the users view, blocking spatial mapping.
Holograms no longer fixed in the world
I uploaded a video with a simple demonstration here: https://vimeo.com/255452197
Shut down the lights, then I obstructed the cameras and released them.
## Steps to reproduce
Create a very simple unity project, obstruct the spatial mapping cameras, stand close to a wall or turn off the light if it's dark.
## Unity Editor Version
2017.2.1f1
## Mixed Reality Toolkit Release Version
2017.2.1.0
## Note
Worked on all previous Holotoolkit, works as intended outside of application

**Comment by StephenHodgson** [comment]
Have you tested this without the toolkit?

**Comment by Cycov** [comment]
My mistake,indeed the same problem occurs without toolkit. Is my hololens device broken?

**Comment by StephenHodgson** [comment]
I'm not sure

**Comment by panaali** [comment]
It's a unity problem, Look at #1778
