### ISSUE TITLE
Replace the FastConfigurable Shader System

### ISSUE THREAD

**Issue by Cameron-Micka** [Microsoft/MixedRealityToolkit-Unity#1715]
# Overview
Hi All, we've discussed this in the weekly ship room but here is the official proposal. I would like to replace the current FastConfigurable shader with "Fluent," a shader system our team has built and maintains. This replacement will not only contain the shading system but also example scenes we have created. I plan to rename Fluent to "MixedRealityToolkit/Standard" for integration into the MRTK. But, will refer to it for Fluent in this proposal.

## What is Fluent?
Fluent is a collection of shading techniques for mimicking [**Microsoft's Fluent Design System**](https://fluent.microsoft.com/) within Unity 3D.

Fluent is useful for anyone who would like to build mixed reality experiences in Unity while adhering to Fluent Design System principles. **The goal of Fluent is to have a single, flexible shader that can achieve visuals similar to Unity's Standard Shader, implement Fluent Design System principles, and remain performant on mixed reality devices.**

## Why use Fluent?
- Dynamic Lighting - Lighting is designed to mimic the standard shader a close as possible while staying within performance guidelines. Lighting is achieved via dynamic lighting (single directional light Blinn-Phong) with specular reflections, reflection, refraction, emissive lighting, rim lighting (fresnal), image based lighting, environment lighting, and hover lighting (cursor light).

<img width="1024" alt="mrsmaterialgallery" src="https://user-images.githubusercontent.com/13305729/36127937-9f04713c-1014-11e8-9842-3cd2e03e6bd1.png">

- Performant - Fluent is architected to run at 60fps to ensure motion is smooth.

- Procedural UX - Procedurally generated borders will react to hover lighting, and border colors can be overwritten for desired effects. Transparent objects with rounded corners will be also be anti-aliased without the need for multisampling. Inner glow can also be emitted from borders. Procedurally generated fluent borders will preserve width even when applied to non-uniformly scaled objects. Rounded corners are calculated at runtime to support animation and infinite resolution.

![itemcontent](https://user-images.githubusercontent.com/13305729/36128123-84c562da-1015-11e8-8c8f-b60e0c2e18b0.png)

- Animatable - All of Fluent's shader properties can be animated using Unity's animation system to achieve motion or via script with material property blocks.

- Configurable - Easily create any material surface you desire via check boxes in a custom material inspector.

<img width="512" alt="mrsmaterialgallery" src="https://user-images.githubusercontent.com/13305729/36128496-87f3b66c-1017-11e8-8a9b-9043c5ad6c47.png">

## Limitations
- Only one light source is supported, the directional light.
- Performance when using normal mapping can be slow when a material that uses normal mapping takes up most of your view.
- Fluent does not support dynamic shadows.

## Questions
- I'm planning to move FastConfigurable into the Obsolete folder. Is that the proper approach or should it be removed all together?
- Should I try to port all existing materials over to Fluent or wait to have that happen gradually over time?

**Comment by DDReaper** [comment]
Is fluent really a replacement for the FastConfigurable shader, which itself has only recently replaced the old Obsolete shaders (most but not all)
Should we not use both for a time until it's fully adopted in the MRTK? Especially with it's single light type limitation.

**Comment by StephenHodgson** [comment]
I think providing a method to convert them would we nice.

**Comment by Cameron-Micka** [comment]
@DDReaper that is an excellent question! I've heard that there is a desire to replace to FastConfigurable shader because it has been difficult for content creators (especially ones new to MR) to match Unity's Standard shader. Deprecating (and not removing) the FastConfigurable shader would make sure people still have access to it if need be. As for the light limitation, this is more of a design choice to help aide content creators down an ideal performance path (ie lean on static lighting over dynamic lighting). But, if there is a want from the community for supporting 'X' number of point lights, I would be more than happy to add that as a feature which can be enabled.

@StephenHodgson I love that idea. I'll work on making sure ShaderGUI::AssignNewShaderToMaterial supports conversion from FastConfigurable materials.

**Comment by genereddick** [comment]
I'm in favor of replacing Fast Configurable but it should be deprecated, not removed. At least not for a couple release cycles.

**Comment by NeerajW** [comment]
Also agree with @genereddick on marking it obsolete. Also please convert the existing materials to use the MRTK\Standard instead.

I have not seen any requests on supporting multiple light sources so far. So we could consider that to be a future enhancement.

**Comment by jwittner** [comment]
Mixed Reality is about to take a step up in performance and visual quality.

**Comment by Cameron-Micka** [comment]
@genereddick I agree, that makes sense to me.

@NeerajW Perfect, I will do that! And, thank you for the insight into the community lighting requests.

@jwittner Thank you! :)

**Comment by derekfreed** [comment]
The shader to rule all shaders, really hope this gets in!

**Comment by mcowling** [comment]
This will really take Mixed Reality to another level, visually. Awesome way to simplify things and give so much freedom with easily customizing UI and still remain performant!

**Comment by kianng** [comment]
Amazing shader that run 60fps! I have been using this shader and really loving it! Can't wait to see how the community is going to use it and see their outcome.

**Comment by chadbramwell** [comment]
I've been using this internally. I LOVE IT.

It's simple to use. The example scene runs at 60 FPS and shows the great variety possible.

The "light" (passing the cursor position as a shader param) is performant, usable and looks great.

The edged-borders make it really fast an easy for me to mockup good looking UI with the Unity Cube primitive!

And selfish promotion here, I expanded the cursor in the example scene - it uses a Unity Quad (just 2 triangles!) and the rounded corners feature to have pixel perfect edging. Putting your hand into the ready-gesture (finger up) will automatically animate the dot to a ring - no change in geometry, simply driving values through the shader! It's versatile!

We finally have something that emulates the shell so we can create beautiful consistent experiences!

Did I say that I LOVE this?

**Comment by Cameron-Micka** [comment]
@derekfreed @mariahcowling @kianng @chadbramwell Thank you all for the kind words! :)

**Comment by Cameron-Micka** [comment]
Another great point @DDReaper, after our call last week I downloaded 2018.1.0b5. Fluent and it's examples worked out of the box for Unity's built in render pipeline, but did not work when I tested the "Lightweight VR - Preview" pipeline. This isn't surprising since Unity's build in Standard shader also doesn't work on any of the custom scriptable pipelines.

When the MRTK community decides to make the jump to 2018 we have a big choice to consider (and maybe this has already been made?) if we want to write a custom pipeline, use the Lightweight VR pipeline, or the built in pipeline. If we pick a custom one (not the built in one) we will have to change ALL of our shaders to pull from the correct include paths, update all of the pass tags, and change all of our light constants (and maybe a few other constants) to pull from custom light structs. You can see an example of the changes that would need to be made [here.](https://gist.github.com/phi-lira/225cd7c5e8545be602dca4eb5ed111ba)

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
