### ISSUE TITLE
MTRK Dev BuildAndDeploy Errors in Unity 2018 Beta

### ISSUE THREAD

**Issue by randystiles** [Microsoft/MixedRealityToolkit-Unity#1716]
## Overview
Has anyone tried Unity 2018.1.0b6 64bit with MRTK Dev_Working_Branch #1518 committed four hours ago?  Basically this is the latest MRTK as far as I can tell, matched with the latest beta Unity version 2018.  It barfs in BuildAndDeploy folder with 22 errors for types and PlayerSettings.   It barfs on editor scripts.   Yes I know the suggested Unity version is something like Unity 2017.2. 1f1 but I have to get Unity and/or Microsoft to fix an interaction that fails for FileSavePicker in UWP for MR and HoloLens, and Unity will only take bugs serious when you show they appear in their latest beta version.  It will likely prove to be a bug in MS UWP area but because it involves an interface between two systems I have to show it crops up when using  both together.

## Expected Behavior
Build basic MRTK (dev, stable or master) with Unity 2018.1.0b6 64bit with no build errors
## Actual Behavior
Can't Build basic MRTK dev version in Unity  2018.1.0b6 64bit with MRTK Dev_Working_Branch #1518 
(Also problem in stable and master)
This is a small sef the errors for editor build in latest beta: Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildSLNUtilities.cs(145,44): error CS0029: Cannot implicitly convert type `UnityEditor.Build.Reporting.BuildReport' to `string'
Assets/MixedRealityToolkit/Utilities/Scripts/Editor/SetIconsWindow.cs(311,50): error CS0117: `UnityEditor.PlayerSettings.WSAImageType' does not contain a definition for `StoreTileLogo'
## Steps to reproduce
_(Links to sample github project preferred)_
Use the actual MRTK Dev github with Unity 2018 beta 6
## Unity Editor Version
Unity 2018.1.0b6 64bit 
## Mixed Reality Toolkit Release Version
MRTK Dev_Working_Branch #1518 committed four hours ago (20180213 2pm)

**Comment by StephenHodgson** [comment]
We only support official releases, and up to the recommended editor version on the readme.

That being said, thanks for reporting so we know what to look out for.

**Comment by DDReaper** [comment]
I've fixed some of the future issues (Build tools and tagalong) and submitted a PR to stabilisation.

The Enum flag fix however, isn't present in the 2017.2.1 build, so we will have to reevaluate for 2017.3.

As to the Image issues, Unity have simply forcibly cleaned up their WSA enums to remove the original  image types and the Phone platform in 2018.   Not sure how these are (or if they are) in 2017, so this will need further review.

**Comment by DDReaper** [comment]
Submitted #1717 to resolve some of the issues in stabilization.
Will roll forward those to dev working once merged.

Need to discuss on the supported images parts, as it seems prudent to also remove those enum checks now, provided they don't cause issue with supported builds.

**Comment by randystiles** [comment]
@DDReaper Thank you for addressing some of the 2018 BuildAndDeploy issues so quickly.  I will try them out in the beta 6 version again.  @StephenHodgson do you know who I might talk to at Microsoft that handles code for the Unity interface to the UWP api contract for FileSavePicker on HoloLens and Immersive (occluded) headsets? We use it in our HoloLens product in the Windows Store and need to fix it.
