### ISSUE TITLE
Incorrect lighting in HMD when using linear color space in Unity 2017.3.1f1

### ISSUE THREAD

**Issue by 265lutab** [Microsoft/MixedRealityToolkit-Unity#1719]
## Overview
When using the linear color space in unity 2017.3.1f1 the image that is displayed in the headset is far darker than what is displayed in the unity editor. If I switch to the gamma color space I don't see this error and when using Unity 2017.2.0p2-MRTP5 linear color space is displayed correctly.
## Expected Behavior
Same image to be displayed in the headset as in the editor
## Actual Behavior
Image displayed in headset is much darker
## Steps to reproduce
_(Links to sample github project preferred)_
Set color space to linear in unity 2017.3.1f1
## Unity Editor Version
unity 2017.3.1f1
## Mixed Reality Toolkit Release Version
MixedRealityToolkit for Unity 2017.2.1f1

**Comment by StephenHodgson** [comment]
Unsure if this is related to the MRTK.
