### ISSUE TITLE
HTK sharing is not working b/w hololens and Immersive headsets!!.

### ISSUE THREAD

**Issue by ALARUNVIGNESH** [Microsoft/MixedRealityToolkit-Unity#1720]
## Overview
trying to sharing bw hololens and immersive headset!!.
## Expected Behavior
it supposed to be work like 2 hololenses.
## Actual Behavior
Not connected.
## Steps to reproduce
tried with HTK sharing scene , not connecting / sharing  bw hololens and immersive headsets.

## Unity Editor Version
2017.2.1p1
## Mixed Reality Toolkit Release Version
2017.2.1.0

**Comment by keveleigh** [comment]
Are either devices able to connect? The HoloLens or the immersive headset?

**Comment by ALARUNVIGNESH** [comment]
Immersive headset even didnt connect to HTK sharing services!!.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
