### ISSUE TITLE
Broken materials after obsolete shader removal

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#1721]
## Overview
Some materials (mostly in the UX folders) have broken after the removal of most of the obsolete shaders. Some (the ones listed with InternalErrorShader below) were broken already anyway.

Material Name | Shader
-- | --
Balloon | StandardFast
BoundingBoxSpherical | StandardFast   (Fade)
BoundingBoxTransparent | StandardFast   (Fade)
ButtonBackground | Lambertian   Configurable Transparent
ButtonForeground | Lambertian   Configurable
ButtonHighlightCircle | Unlit Configurable   Transparent
ButtonHighlightRectangle | Unlit Configurable   Transparent
ButtonIconMaterial | Unlit Configurable   Transparent
ButtonMat | StandardFast
CeilingPlane | InternalErrorShader
FloorPlane | InternalErrorShader
Highlight | Unlit Configurable
PushButtonYellow | StandardFast
SampleBlue | StandardFast
SampleGreen | StandardFast
SampleOrange | StandardFast
SamplePink | StandardFast
SampleRed | StandardFast
TablePlane | InternalErrorShader
TeleportMarker | StandardFast
ToolTipBalloon | StandardFast
WallPlane | InternalErrorShader
White | StandardFast

## Mixed Reality Toolkit Release Version
https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/ff2249935d3e0ca214d26643cc10e277ea70fcfa

**Comment by Cameron-Micka** [comment]
@keveleigh I'm about to convert many of these materials over to the new shader outline [here](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1715). I can fix up these materials as I make my changes.
