### ISSUE TITLE
client Authority(Immersive headset) to share hologram to the host(Hololens) not shared, while the Host to client was getting shared in UNET!!.

### ISSUE THREAD

**Issue by ALARUNVIGNESH** [Microsoft/MixedRealityToolkit-Unity#1722]
## Overview
Two way sharing not working in UNET bw immersive and hololens!!.
## Expected Behavior
two way sharing between hololens to immersive and immersive to hololens!!.
## Actual Behavior
sharing from immersive to hololens is not getting shared, while the host to client was getting shared!!.
## Steps to reproduce
tried with UNET Sharing scene in 2017.2.1 toolkit , added a extra cube  added network identity and transform and player was enabled to local player authority!!.
## Unity Editor Version
2017.2.1p1
## Mixed Reality Toolkit Release Version
2017.2.1

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
