### ISSUE TITLE
Button Icons Missing

### ISSUE THREAD

**Issue by Pycorax** [Microsoft/MixedRealityToolkit-Unity#1724]
## Overview
The Buttons brought in from MRDL seem to be missing the textures for the icons. In the Compound Button Icon inspector panel, under "Profile" when expanded, many texture fields can be seen with no assigned textures. This results in being unable to set the icon via the drop down menu.

## Expected Behavior
Selecting the icon to use for the button under the "Icon" drop down menu in the Compount Button Icon inspector should change the icon of the button.

## Actual Behavior
No change is made and the icon selected remains as "ObjectCollectionSphere"

## Steps to reproduce
Dragging any of the Button prefabs under the UX folder into the scene and attempting to change the icon via the CompoundButtonIcon inspector.

## Unity Editor Version
2017.2.1p2

## Mixed Reality Toolkit Release Version
2017.2.1.1

**Comment by cre8ivepark** [comment]
@Pycorax This is fixed in the pull request #1739 
FYI, This MRTK version of CompoundButtonIcon is slightly different from MRDL. In MRTK version, you have to manually create add Texture 2D to the empty slots (or use override). It does not support native font file directly.
