### ISSUE TITLE
[ImmersiveHeadsets] SpatialAnchorTransferManager denied access to WorldAnchor serialization

### ISSUE THREAD

**Issue by MatteoFantasy** [Microsoft/MixedRealityToolkit-Unity#1725]
## Overview
I'm getting an error when trying to export anchors data, using the example from Unity ([link here](https://docs.unity3d.com/Manual/windowsholographic-anchorsharing.html)) : 
Calling "WorldAnchorTransferBatch.ExportAsync" leads to 
> SpatialAnchorTransferManager denied access to WorldAnchor serialization

## Expected Behavior
The anchors should be serialized and returned as a byte array.

## Actual Behavior
The following error is returned and the export fails

> SpatialAnchorTransferManager denied access to WorldAnchor serialization

It happens both in editor and in build.

## Steps to reproduce
- Add an anchor into your project
- Use the [Unity anchor sharing example script](https://docs.unity3d.com/Manual/windowsholographic-anchorsharing.html) or my version of it below to try and save it.

## Unity Editor Version
2017.3.0p4 / 2017.3.1p1 / 2017.2.0p2

## Mixed Reality Toolkit Release Version
Release from the 16th of january

Thanks for your help !
Tom

Code : 
```
private void ExportAnchors() {
	WorldAnchorTransferBatch transferBatch = new WorldAnchorTransferBatch();
	transferBatch.AddWorldAnchor("anchor", myAnchorGameObject.GetComponent<WorldAnchor>());
	WorldAnchorTransferBatch.ExportAsync(transferBatch, OnExportDataAvailable, OnExportComplete);
}

private void OnExportComplete(SerializationCompletionReason completionReason) {
	if (completionReason != SerializationCompletionReason.Succeeded) {
		// If we have been transferring data and it failed, 
		// tell the client to discard the data
		Debug.LogError("Anchors exporting failed");
	} else {
		// Tell the client that serialization has succeeded.
		// The client can start importing once all the data is received.
		Debug.Log("Anchors exporting succeded");
	}
}

private void OnExportDataAvailable(byte[] data) {
	// Send the bytes to the client.  Data may also be buffered.
	File.WriteAllBytes(Application.persistentDataPath+"/anchors.dat", data);
	Debug.Log("Anchors data correctly written");
}


```

**Comment by StephenHodgson** [comment]
The Immersive Headsets don't have the ability to get spatial data.

**Comment by MatteoFantasy** [comment]
Thanks for your answer. I get that most spatial features are unavailable since the headsets don't have a depth camera, but I don't understand why anchors sharing would be unavailable : 

First, the readme states that the "Sharing" feature is available on both the hololens and immersive headsets, and specifies that "Anchor sharing" is included ([here ](https://github.com/Microsoft/MixedRealityToolkit-Unity)and [here](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Sharing/README.md))

And additionally, I can use anchors in my Unity scene, have them saved and loaded automatically from one session to another, I even see them move slightly when they readjust, just like in the Hololens...which in my understanding means that there is some kind of description of the world at this location that is stored somehow, probably just like this hololens does it ?

**Comment by ryansburgoyne** [comment]
I have the same question. @StephenHodgson, could you respond the the OP’s follow-up comment? Why is spatial mapping required for world anchor sharing, since (unshared) world anchors clearly are supported with the immersive HMDs?
