### ISSUE TITLE
TransformSynchronizer not sharing and receiving information

### ISSUE THREAD

**Issue by fraspadafora** [Microsoft/MixedRealityToolkit-Unity#1728]
## Overview
I'm trying to share the transform position, rotation and scale of a gameobject that is not spawned at runtime, but already exists in the scene of the two hololens.

In my project I have:

Manager GameObject with:
- SharingStage
- SharingWorldAnchorManager

WorldAnchor with:
- AutoJoinSessionAndRoom

Sphere (Child of WorldAnchor) with:
- TransformSynchronizer
Where I changed the Start method with:

```
private void Start()
        {
            Initialize();
            transformDataModel = new SyncTransform("transform");
        }
```
The session and room are created but no information is synched between the two hololens.

## Expected Behavior
When I move a sphere in the scene of one Hololens, the sphere moves in the scene of the second Hololens.

## Actual Behavior
When moving the sphere in the Hololens 1, in the Hololens 2 there is no movement.
No **OnPositionChanged** events are called in TransformSynchronizer of the second hololens.

## Unity Editor Version
Unity 2017.3.1f

## Mixed Reality Toolkit Release Version
2.1.1

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
