### ISSUE TITLE
Speech duplicate

### ISSUE THREAD

**Issue by Cycov** [Microsoft/MixedRealityToolkit-Unity#1729]
## Overview
`SpeechInputHandler` keyword events are called twice. `SpeechInputSource` works properly, can't trace the problem within the custom `InputManager`.
## Expected Behavior
When I say a particular keyword the response method to be called exactly once from `SpeechInputHandler `
## Actual Behavior
When I say a particular keyword the response method is called twice
## Steps to reproduce
Add a `SpeechInputSource` with a keyword ("Page up" in my situation) and a `SpeechInputHandler`  which handles that keyword. Both scripts shall reside in the `Managers` GameObject which is added by using the MixedReality Toolkit menu.
## Unity Editor Version
2017.2.1f1 Windows10 64bit
## Mixed Reality Toolkit Release Version
2017.2.1.0

**Comment by StephenHodgson** [comment]
Are you consuming the eventData in the handler script?

**Comment by Cycov** [comment]
No, I'm using holotoolkit's `SpeechInputHandler` purely from the inspector, with static parameters.

**Comment by StephenHodgson** [comment]
Sure you didn't register the handler as a global listener twice?

**Comment by Cycov** [comment]
Indeed, `InputManager` adds itself to global Listeners and by leaving `IsGlobalListener` checked as default in `SpeechInputHandler `  adds the entire managers object to the list again, creating a duplicate.
