### ISSUE TITLE
Ambiguous call GetTypeInfo() in dev branch with .Net 4.6 runtime version.

### ISSUE THREAD

**Issue by eirikhollis** [Microsoft/MixedRealityToolkit-Unity#1730]
## Overview
When importing the latest dev branch with .Net 4.6, the following error appears:

MixedRealityToolkit/Sharing/Scripts/SyncSettings.cs(43,33): error CS0121: 
The call is ambiguous between the following methods or properties: 'MixedRealityToolkit.Common.Extensions.ReflectionExtensions.GetTypeInfo(this System.Type)' and 'System.Reflection.IntrospectionExtensions.GetTypeInfo(this System.Type)'

## Expected Behavior
No errors.

## Actual Behavior
Ambiguous call in [SencSettings.cs#L43](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit/Sharing/Scripts/SyncSettings.cs#L43).

## Steps to reproduce
Import latest dev branch in 2017.3.1p1.
Switch Scripting Runtime Versions to Experimental .Net 4.6
Error appears after restarting Unity.

## Unity Editor Version
2017.3.1p1

## Mixed Reality Toolkit Release Version
dev_branch 19.02.2018

**Comment by StephenHodgson** [comment]
Chances are this will be removed when we make the MRTK target 4.6 by default.

**Comment by genereddick** [comment]
Same issue for me. My temporary work around removes the error though not sure about any actual impact on functionality:

Changed MixedRealityToolkit.Sharing.SyncSettings LINE 38: 
    var typeInfo = type.GetTypeInfo();
To:
    var typeInfo = ReflectionExtensions.GetTypeInfo(type);

**Comment by StephenHodgson** [comment]
Yup, it's a problem with the namespaces.

**Comment by DDReaper** [comment]
I did resolve this in the namespace update, so unsure as to why it's happening again.

**Comment by StephenHodgson** [comment]
I vote we just move the project up to .NET 4.x and just remove the offending code.
This will enable us to do a lot of awesome new stuff (like use the device portal wrapper)

**Comment by keveleigh** [comment]
I'd be hesitant to move to 4.x until Unity stops labeling it "experimental". Is there a known timeframe for that?

Of course, I also have little personal experience yet with how "experimental" it still is.

**Comment by StephenHodgson** [comment]
Everything in Unity is experimental.

**Comment by keveleigh** [comment]
Well, for this they explicitly use the word "stable" next to one and "experimental" next to the other:

![image](https://user-images.githubusercontent.com/3580640/37007132-b6ce09fe-2090-11e8-9dbb-57d112a05f02.png)

**Comment by StephenHodgson** [comment]
It's pretty solid imo.

We gain more by using it.

**Comment by Jarodshow** [comment]
Would 4.6 be implemented sometime soon? Async functionality would be handy.

**Comment by StephenHodgson** [comment]
Yeah, I've got a PR open for it in the dev branch.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
