### ISSUE TITLE
Tracking image is not disappearing inside the application 

### ISSUE THREAD

**Issue by mr-mystery** [Microsoft/MixedRealityToolkit-Unity#1731]
## Overview
tracking image is not disappearing
## Expected Behavior
tracking image should disappear after tracking is done inside the application.
## Actual Behavior
tracking image does not disappearing even after the tracking has been completed, the tracking image keeps on following the camera.
## Steps to reproduce
_(Links to sample github project preferred)_
- open a hololens application
- lose the spatial tracking while inside the application 
- then try to track again, the tracking image will appear  
## Unity Editor Version
2017.2.1p
## Mixed Reality Toolkit Release Version
2017.2.1p

**Comment by eirikhollis** [comment]
This is an Unity bug. Try using Unity 2017.2.0f3 instead.

**Comment by mr-mystery** [comment]
Thank you very much!
