### ISSUE TITLE
How would I impliment something like OnFocusEnter/Exit for a layer/tag in my scene?

### ISSUE THREAD

**Issue by dtb49** [Microsoft/MixedRealityToolkit-Unity#1732]
So, this might be a noob question, but I want to implement basically a highlight material whenever the user's gaze enters an object with a certain layer/tag. I thought the best bet would be to implement something like IFocusable, however after I started thinking about it, I would need to add this script to each object I want to highlight, i.e. 20 to 30 objects. 

Is there a way to implement something like OnFocusEnter and apply to all objects with certain layer/tag without having to add it to each individual object? However, I still only want to highlight the individual object I am looking at.  Or am I going about this all wrong? Any assistance on the matter would be greatly appreciated.

**Comment by StephenHodgson** [comment]
https://www.rageagainstthepixel.com/mrtk-getting-focus/

**Comment by dtb49** [comment]
@StephenHodgson yes, that is basically what I have already. What I am wondering is, Is there a way to apply this in basically the opposite direction? Would I be able to do something like ray casting from the camera or at least getting whatever object is in focus and then check if it contains a certain layer and then highlight it so that I don't have to add that script to every object I want to highlight?

Like with the example above you have to add that script for every cube/object you want to highlight in your scene.

**Comment by dtb49** [comment]
Would the [IPointerSpecificFocusable ](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/ac6b63cdf04ecadd4a44bf0d623e7d29cb439c0f/Assets/HoloToolkit/Input/Scripts/InputHandlers/IPointerSpecificFocusable.cs)script be what I am looking for?

**Comment by StephenHodgson** [comment]
use the shared material instead.

**Comment by StephenHodgson** [comment]
Yeah, you could do your own raycasting, but that has some overhead.

**Comment by dtb49** [comment]
@StephenHodgson yeah i don't really want to raycast a whole lot. Is it possible to get the cursor's state or when the cursor's state changes?

**Comment by StephenHodgson** [comment]
Do you know all your objects that need to be highlighted ahead of time?

**Comment by dtb49** [comment]
@StephenHodgson yes

**Comment by StephenHodgson** [comment]
Then what's the hesitation to add the component to every object?

**Comment by dtb49** [comment]
@StephenHodgson So basically I have an object similar to that parts-wise of a car and I am loading different car systems at a time but, there are hundreds of objects total for the entire object. So I'd have to go through and add the script for every part I want highlight, not to mention when I want to add another whole car. I'd have to do it all over again. 

I mean, if I have to do it that way I can, but I'd really like to avoid it.

**Comment by StephenHodgson** [comment]
You can still use the layer check before adding a component.

**Comment by StephenHodgson** [comment]
So you're not dynamicly adding them to the scene?

**Comment by dtb49** [comment]
... lol I don't know why I didn't think about just adding the script with a for loop through the base object at the start of the program. Haha I feel stupid now 😭
