### ISSUE TITLE
NetworkDiscoveryWithAnchors.StartHosting(string SessionName) does not actually use SessionName parameter

### ISSUE THREAD

**Issue by furkee** [Microsoft/MixedRealityToolkit-Unity#1736]
## Overview
Function's docstring suggest that the name will only be used if a name cannot be calculated. IMO even if a name can be calculated, end-user still should be able to set a name for his/her session.

I got over this restriction by writing an adapter to NetworkDiscoveryWithAnchors class that maps desired session names to generated session names, which also changes the way events are fired. I found that instead of a `session list changed` event, firing a `new session found` event and a `session is closed` event, both containing specific session data in their callbacks, to be more useful. I don't like my adapter though and I want to remove it from my codebase :)

This is more like a suggestion than an issue and I don't know if it makes sense to you. I would love to hear your thoughts on the matter.

Cheers.

## Expected Behavior
Session name is the same as the parameter 'SessionName'

## Actual Behavior
Function does not use the parameter at all.

## Steps to reproduce
`StartHosting("a session name")` is enough to reproduce.

## Unity Editor Version
2017.3.0f3

## Mixed Reality Toolkit Release Version
v2017.2.1.1

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
