### ISSUE TITLE
 InteractionSourceDetected  doesn't work correctly on build (HeadSet, 2017.3)

### ISSUE THREAD

**Issue by warzoku** [Microsoft/MixedRealityToolkit-Unity#1737]
I get input and controller childs via InteractionSourceDetected and InteractionSourceUpdated. In Editor its always works fine, but in build InteractionSourceDetected not work in first start app. After restart app work fine. (work correctly In 2017.2.0p1-MRTP4)
Unity 2017.3.0f3
HeadSet

**Comment by keveleigh** [comment]
I'm unable to repro this in recent Unity versions. Please reopen if it's still an issue.
