### ISSUE TITLE
error CS1929: 'SpatialInteractionController' does not contain a definition for 'TryGetRenderableModelAsync'

### ISSUE THREAD

**Issue by DaveAccenture** [Microsoft/MixedRealityToolkit-Unity#1740]
## Overview
Getting this error building 'GazeRuler' Example
This bug was reported back in Oct 2017 and discussion closed. Well, it's back.
Just install this version of Unity with needed extras for building to HoloLens, open the MRTK, find the GazeRulerExample project, and build. Boom.
Can you PLEASE fix this

## Expected Behavior
That I get no errors and it runs correctly

## Actual Behavior
I get this error when Building

## Steps to reproduce
It's today's available version of the Mixed Reality Toolkit for Unity

## Unity Editor Version
2017.3.1p1

## Mixed Reality Toolkit Release Version
Latest commit 0d54a2d  on Jan 18 2018

**Comment by keveleigh** [comment]
You need the Fall Creator's Update SDK installed, version 16299.

**Comment by DaveAccenture** [comment]
Trying that now. I thought I had FCU. Is there a way we can mod the Unity editor to look for such things and give good tips and URL's for fixing such things?

**Comment by DaveAccenture** [comment]
Tried to update SDK, at the end of that long process, it says I'm still on 15.7. Uninstall/reinstall time

**Comment by keveleigh** [comment]
Please re-open if you're still seeing this issue. Installing 16299 is the SDK where `TryGetRenderableModelAsync` was added, but please let me know if that didn't resolve it for you!

**Comment by play123** [comment]
I got the same error with unity 2018.2f1

**Comment by keveleigh** [comment]
@play123 You may need to update your Visual Studio Installer. It should prompt you when you open it, or you can try downloading the latest: https://visualstudio.microsoft.com/downloads/
