### ISSUE TITLE
Motion Controller trigger mapped on Xbox controller

### ISSUE THREAD

**Issue by odens** [Microsoft/MixedRealityToolkit-Unity#1751]
## Overview
Motion Controller trigger change value on Xbox trigger

## Expected Behavior
Suppose should separate Xbox from Motion controllers

## Steps to reproduce
1) Open sample scene from MRTK
Assets\HoloToolkit-Examples\Input\Scenes\XboxControllerExample.unity

2) Star then press left/right trigger on Motion Controller.
3) Note Xbox left/right/share trigger change value

## Unity Editor Version
Unity 2017.3.1f1

## Mixed Reality Toolkit Release Version
MRTK 2017.2.1.1

**Comment by StephenHodgson** [comment]
This isn't a problem with the toolkit, because that's something that MSFT decided when mapping the axes to similar controllers.

You need to specifically call out a separate controller in your editor input mappings.

**Comment by StephenHodgson** [comment]
Check out this button and axis mapping table for the motion controller.
https://developer.microsoft.com/en-us/windows/mixed-reality/gestures_and_motion_controllers_in_unity#unity_button.2Faxis_mapping_table

**Comment by StephenHodgson** [comment]
and the xbox button and axis mapping here.
https://ritchielozada.com/2016/01/16/part-11-using-an-xbox-one-controller-with-unity-on-windows-10/

**Comment by StephenHodgson** [comment]
and read up on Unity's Input Editor: https://docs.unity3d.com/Manual/class-InputManager.html

**Comment by odens** [comment]
Thank you for help!
