### ISSUE TITLE
SharingWithUUNET in MixedRealityToolkit references -Examples project

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#1755]
## Overview
The Player prefab in the SharingWithUUNET folder of MixedRealityToolkit has a PlayerController script that only exists in the MixedRealityToolit-Examples/SharingWithUUNET/Scripts folder

## Expected Behavior
No references from MRTK to MRTK-Examples

## Actual Behavior
Reference that breaks if you do not include the Examples project

## Unity Editor Version
Any

## Mixed Reality Toolkit Release Version
Dev_Working_Branch

**Comment by StephenHodgson** [comment]
We should probably check the stabilization branch as well.

**Comment by genereddick** [comment]
Just checked. The same issue exists in the Stabilization branch.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
