### ISSUE TITLE
In HandDraggable, when RotationMode is Default and using motion controller, orient the object with the controller rather than the head.

### ISSUE THREAD

**Issue by michaellperry** [Microsoft/MixedRealityToolkit-Unity#1757]
## Overview

I plan to work on this issue.

When dragging an object using HandDraggable in an immersive headset, the orientation of the object follows the user's head by default. Twisting, turning, or yawing the motion controller has no effect.

## Expected Behavior

The orientation of the object when RotationMode is Default should be determined by the motion controller, if a motion controller was used to grab the object.

## Actual Behavior

The orientation of the object is determined by the user's head. Nodding or turning the head results in changes to object orientation, resulting in a very unnatural experience.

For example, to set a horizontal object upright, it is necessary for the user to look down at the floor when grabbing it, and then raise their head to rotate it upward before releasing it. This is more naturally done by lifting the wrist.

## Steps to reproduce

Run [MyScrapRoom](https://github.com/michaellperry/MyScrapRoom) with an immersive headset. Pick up one of the photo albums from the top shelf. Bring it down to the island table top. Notice that it is most likely diagonal, since your head went from looking up to looking straight.

Pick up one of the lava lamps. Tilt your head from side to side. The lava lamp follows your head.

Drop one of the lava lamps on its side on the floor. Now try to right it. It's very difficult to do because you have to move your head.

## Unity Editor Version

Unity 2017.3.0f3 (64-bit)

## Mixed Reality Toolkit Release Version

V1

**Comment by sunt89** [comment]
@StephenHodgson   I have the same problem, Is there any solution?

**Comment by michaellperry** [comment]
I plan to work on a solution. I have not yet done so.

My first intended step would be to isolate the various input methods so that I can be sure not to break one of them while fixing motion controllers. Currently, the code for various inputs is scattered about in various conditional statements.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.

**Comment by Yoyozilla** [comment]
This is fixed in MRTK v2. 

Bulk closing older HTK bug. Please reopen if you can repro this issue in MRTK v2. 
Thanks!
Yoyo

**Comment by Yoyozilla** [comment]
ManipulationHandler.cs is the replacement for HandDraggable
