### ISSUE TITLE
SharingWithUNET causes Hololens crash on Session Start

### ISSUE THREAD

**Issue by reesedonohue** [Microsoft/MixedRealityToolkit-Unity#1758]
## Overview

Cloned MRTK-Unity and opened SharingWithUNET example scene. Configured for UWP and Built. Deployed to Hololens. When I click to start a new session on the Start button, app freezes, then crashes, and returns me to Hololens home space.

Tried this with both latest .unitypackage release and by cloning MRTK repository. Same result.

Have used these Hololenses and this PC to successfully build shared experience Hololens apps. Did full reset of both Hololenses, didn't help.

## Expected Behavior

Expect example scene to run normally, but starting a new network session and beginning anchor export.

## Actual Behavior

App freezes and crashes, returns to Hololens home space.

## Steps to reproduce
Import Holotoolkit unity package. Open SharingWithUNET example scene. Build and deploy. Run the app and  click button to start session.

MRTK-Unity master branch and / or .unitypackage Release 2017.2.1.1
Unity 2017.2.1.f1
Windows 10 Fall Creators Update
Visual Studio 15.5.4 with 10.0.16299.0 SDK

## Unity Editor Version
2017.2.1.1
## Mixed Reality Toolkit Release Version
2017.2.1.1

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
