### ISSUE TITLE
UNetAnchorManager forces you to use the Spatial Mapping Manager if it is provided

### ISSUE THREAD

**Issue by bockelie93** [Microsoft/MixedRealityToolkit-Unity#1762]
## Overview
If you include Spatial Mapping Manager in the scene the UNetAnchorManager will force you to use it when it tries to find the anchor position. 

In my project, I want to have the anchor where I have placed my SharedCollection, but with the current implementation the anchor position gets overwritten by the Spatial Mapping if it is in the scene.

Having the option to choose between using it or not would be neat.

**Comment by dtb49** [comment]
You could always just create a public Boolean and an if statement to do it in the UnetAnchorManager under the CheckConfiguration method. However, I suspect its not in there already because its advised to use the SpatialMapping in order to get a good anchor location.

`            if(allowSpatialMappingAnchor)
                spatialMapping = SpatialMappingManager.Instance;`

**Comment by StephenHodgson** [comment]
Chances are this whole feature area will be rewritten soon with a complete overhaul of how we manage dependencies in our feature areas.

Adding a bool is a bandaid at best.

**Comment by bockelie93** [comment]
I am looking forward to it. Having everything tightly coupled won't work in the long run.

**Comment by Alexees** [comment]
I'd like to know if there's a section somewhere where the overhaul is discussed or discribed. We also had to do things a little differently and would like to know about and contribute to the new design.
