### ISSUE TITLE
Unity editor play does not launch on headed set

### ISSUE THREAD

**Issue by gobanjoboy** [Microsoft/MixedRealityToolkit-Unity#1765]
## Overview
I am unable to get my test project to display on the VR headset anymore. I have deleted the HoloToolkit folder from my Assets and tried both loading the unity package and just downloading the master branch and unzipping and copying HoloToolkit(folder), HoloToolkit.meta, mcs.rsp and mcs.rsp.meta back into the Assets folder. I have run the project setup and scene setup from the menu section. I am at a complete loss.

## Expected Behavior
The project used to display on the head set when pressing play in Unity Editor.

## Actual Behavior
Press play, project builds and loads in the game tab. If I move the headset I can see the camera display moving. When looking through the headset it just sitting in the WMR house.

## Steps to reproduce
Not sure what causes it.

## Unity Editor Version
Unity 2017.2.1f1
## Mixed Reality Toolkit Release Version
2017.2.1.1

**Comment by StephenHodgson** [comment]
Try restarting the Mixed Reality Portal and your PC

**Comment by gobanjoboy** [comment]
I have already done this via computer shut downs and reboots. I have now even uninstalled WMR and went through the setup process again. Any other ideas?.. side note... I am able to build the project and it launches on the headset, just not when using Unity Play. Other note. If I switch the platform away from UWP and use PC with OpenVR it displays on the headset just fine.

**Comment by StephenHodgson** [comment]
Sorry, didn't mean to close this.

**Comment by gobanjoboy** [comment]
I figured it out. I had turned on Unity to run as "administrator" in the shortcut settings. I turned that setting off and it starting working again.

![capture](https://user-images.githubusercontent.com/174855/36753713-a51c1412-1bcc-11e8-870e-a06ce3ac8cab.PNG)
