### ISSUE TITLE
Button (Interactive script) OnHold Event() is only called once?

### ISSUE THREAD

**Issue by dtb49** [Microsoft/MixedRealityToolkit-Unity#1766]
I am trying to rotate an object to the right while a button is being pressed. The rotating is not the problem but, continuing to rotate is. I have my method attached to the OnHold Event() on a Button Prefab from the MRTK examples folder. Maybe the OnHold Event only detects holds once but, I thought it was more along the lines of the equivalent of Input.GetKey where it continues to perform while the user is Holding the button down. Is this not the case? If not, any possible solutions would be appreciated.

**Comment by eirikhollis** [comment]
You could add IInputHandler to your script and start something that runs continuously on OnInputDown, and stop on OnInputUp.

**Comment by killerantz** [comment]
Sorry for the delayed response, the onHold event fires once per onHold. @eirikhollis is correct with his suggestion or you could use GestuerInteractive and extend the GestureInteractiveController class if you need something that's more gesture related.

**Comment by StephenHodgson** [comment]
Yeah I thing was designed to only fire once, not continuously.
