### ISSUE TITLE
Apply Mixed Reality Project Settings causes error for MRTK 2017.2.1.1 in Unity 2017.2.1f1

### ISSUE THREAD

**Issue by edsilv** [Microsoft/MixedRealityToolkit-Unity#1767]
## Overview

I followed your readme and installed Unity 2017.2.1f1 (with Unity Hub), then imported https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/2017.2.1.1 with `Assets > Import Package > Custom Package` leaving all the defaults untouched.

When clicking `Mixed Reality Toolkit > Configure > Apply Mixed Reality Project Settings` with the defaults untouched and then clicking `Apply` nothing happens and I get this error: `switching to universal windows platform:metrosupport is disabled`

## Expected Behavior

The project settings should be applied.

## Actual Behavior

Nothing happens and you get a `switching to universal windows platform:metrosupport is disabled` error.

## Steps to reproduce

Detailed in overview.

## Unity Editor Version

2017.2.1f1

## Mixed Reality Toolkit Release Version

2017.2.1.1

**Comment by StephenHodgson** [comment]
Download and install the UWP modules for unity.

**Comment by edsilv** [comment]
I've already followed this guide: https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/GettingStarted.md#2-setting-up-your-development-environment and had projects working on previous releases of the MRTK.
Is there something new that's not in the guide that I need to install? If so could you provide a link?

**Comment by edsilv** [comment]
Never mind, got it. In Unity Hub you can select "Add Component" for a given install. I was missing "Windows Store .NET Scripting Backend" - sorry, thought I'd installed it.
