### ISSUE TITLE
AutoConfigureMenu's Scene Settings Should Be Updated to Conform to New Standards

### ISSUE THREAD

**Issue by Cameron-Micka** [Microsoft/MixedRealityToolkit-Unity#1768]
## Overview
In a recent [pull request]( https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1743#discussion_r170297565) it was mentioned that scene managers should live under a game object named "Managers". We should change the Mixed Reality Toolkit->Apply Mixed Reality Scene Settings menu item to apply this new standard.

## Expected Behavior
When selecting the Mixed Reality Toolkit->Apply Mixed Reality Scene Settings menu item the Input Manager prefab (if selected) should be instantiated as a child of a "Managers" game object. 

## Actual Behavior
The Input Manager gets instantiated at the scenes root.

## Steps to reproduce
1) Select File->New Scene
2) Select Mixed Reality Toolkit->Apply Mixed Reality Scene
3) Assert "Add the Input Manager Prefab" is selected
4) Select Apply
5) Observe the InputManager gets instantiated at the scene root

## Unity Editor Version
2017.2.1f1

## Mixed Reality Toolkit Release Version
Tested on [Dev_Working_Branch](https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/a66dba1bfcaf941f604d75025ad1df94d232a908)

**Comment by StephenHodgson** [comment]
Personally I don't mind that it get's instantiated on the scene root. Devs can then move the prefabs around as they wish.

**Comment by Cameron-Micka** [comment]
@StephenHodgson I agree, I kind of like it at the root. Just want to make sure the tooling follows the standards and vice versa.

**Comment by DDReaper** [comment]
I'd have to agree, the "Managers" paragidm has been extensively used in the examples and it a good group object for all MRTK managers.  So the scene settings options should have this as a default.

If devs then want to do somethign else they can still move it around, but our own features should promote "best practice"

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
