### ISSUE TITLE
Enable Single Pass Stereo Rendering as Default

### ISSUE THREAD

**Issue by Cameron-Micka** [Microsoft/MixedRealityToolkit-Unity#1769]
## Overview
Apologies if this has been suggested before, but I noticed that the stereo rendering method in the UWP player settings is set to "Multi Pass." I would recommend the default behavior be set to Single Pass (and Single Pass Instanced in the future).

Note, this won't be a performance improvement for most of the example scenes within the MRTK, but complex "production scenes" will likely see a performance improvement. We will also have to update a handful of shaders that are lacking stereo single pass support.

## Unity Editor Version
2017.2.1f1

## Mixed Reality Toolkit Release Version
Tested on [Dev_Working_Branch](https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/a66dba1bfcaf941f604d75025ad1df94d232a908)

**Comment by Cameron-Micka** [comment]
I can do that! I know the MixedReality/Standard shader works with single pass, but I'll want to check the existing shaders as well (I should have some time to test them out tomorrow).

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
