### ISSUE TITLE
Add error logging to BuildDeployTools

### ISSUE THREAD

**Issue by justinpando** [Microsoft/MixedRealityToolkit-Unity#1771]
## Overview
I would like to add additional logging to the build window to get more information about build errors so it's easier to diagnose and solve them.

## Expected Behavior
When a build error occurs I am able to read the error message.

## Actual Behavior
When trying to build APPX through the Build Window, if there are any build errors you only get a message: 
Debug.LogError("MSBuild error (code = " + process.ExitCode + ")");
Usually reads out as "MSBuild error code = 1"
This is a generic failure message and doesn't help us diagnose and solve the problem.

## Steps to reproduce
Have any problem in your dev environment that would cause building APPX to fail. In my case I had additional VS Build Tools installed along with my VS environment and it caused build failure.

## Unity Editor Version
2017.1.3f1
## Mixed Reality Toolkit Release Version
2017.2.1.1

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
