### ISSUE TITLE
Navigation gesture doesn't work in Editor but, works on HoloLens

### ISSUE THREAD

**Issue by dtb49** [Microsoft/MixedRealityToolkit-Unity#1774]
## Overview
I am creating a rotation method using the INavigationHandler. After triple checking my code and on the edge of giving up I deployed to the HoloLens and it actually worked to my surprise. I figured this was some sort of bug. Not sure if it is Unity or Toolkit related or if it has been discovered already and figured I'd report it.

## Expected Behavior
Navigation gesture to work in the editor.

## Actual Behavior
Navigation gesture only works on the HoloLens

## Unity Editor Version
2017.1

## Mixed Reality Toolkit Release Version
latest

**Comment by StephenHodgson** [comment]
Not so much a bug, as it was probably never fully implemented (if you're using just the mouse for navigation)

**Comment by eirikhollis** [comment]
IManipulationHandler works in the editor. You could switch out the navigationhandler code and use this instead. For (I'm guessing) the joystick-like input you desire, something like the code below inside OnManipulationUpdated should work.

`HostTransform.position += eventData.CumulativeDelta;`

**Comment by dtb49** [comment]
@StephenHodgson Ohh I see, I just thought it might be a bug since the Manipulation gesture worked in the Editor with the mouse. 

@eirikhollis I actually first used IManipulationHandler but, since I'm using it for rotation, the Navigation gesture works better. Otherwise when using Manipulation the rotation will jump suddenly based on the distance the hand moved, where as when using Navigation the handDelta, if you will, is normalized and doesn't cause such a jump.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
