### ISSUE TITLE
ObjectCollection doesn't manage correctly the diplay

### ISSUE THREAD

**Issue by GermainJLab** [Microsoft/MixedRealityToolkit-Unity#1775]
## Overview
When using an ObjectCollection, the objects are not displayed as they should.

## Expected Behavior
For example, when displaying 49 objects in 10 rows, there should be 5 objects per row except for the last one where there should be 4.

## Actual Behavior
What actually happens is that there are only 4 objects per rows and the 9 objects left are displayed at the center of the collection.

## Steps to reproduce
Just try displaying a number of objects that is not a multiple of the number of rows, and it should displau the objects in an odd way.

## Correction found
We corrected this issue at the line 180 of the ObjectCollection.cs script : 

Original code : "_columns = Mathf.CeilToInt(NodeList.Count / Rows);"

Working code : "_columns = Mathf.CeilToInt((float) NodeList.Count / (float)Rows);"

Thank you !

**Comment by GermainJLab** [comment]
Sorry I can't submit the PR myself as I'm still a newbie on git :/
It's really a small change so is it possible for you to it?
Sorry

**Comment by StephenHodgson** [comment]
No worries! I've got ya.

**Comment by GermainJLab** [comment]
Thanks !

**Comment by GermainJLab** [comment]
Excuse me but do you know when the AppBar and BoundingBox will be merged in the MRTK ? Would it be worth for me to wait for it or should I code it myself?
Thanks!

**Comment by cre8ivepark** [comment]
@GermainJLab We are about to submit PR for App Bar and Bounding Box.

**Comment by cre8ivepark** [comment]
@GermainJLab Please take a look at #1783

**Comment by GermainJLab** [comment]
Thank you so much !
I was wondering if I could get it done before the end of my internship !
