### ISSUE TITLE
「Trying to map your surroundings」 Continue to be displayed

### ISSUE THREAD

**Issue by sakamoto-systemfriend** [Microsoft/MixedRealityToolkit-Unity#1778]
## Overview
The indication of 「Trying to map your surroundings」 does not disappear

## Expected Behavior
「Trying to map your surroundings」disappears

## Steps to reproduce
1.Application launch
2.Hold your hand over the holoens sensor and make tracking lost
3.「Trying to map your surroundings」 is displayed
4.Take your hand from HoloLens and track around
5.「Trying to map your surroundings」 Continues to be displayed

## Unity Editor Version
Unity 2017.2.1f1

## Mixed Reality Toolkit Release Version
2017.2.1.1 Patch Release

**Comment by Firifire** [comment]
This is a unity bug, use version 2017.2.0f3 or 2017.3.1px

**Comment by sakamoto-systemfriend** [comment]
I solved it, thank you for the correspondence !
