### ISSUE TITLE
WorldAnchorManager RemoveAllAnchors() error

### ISSUE THREAD

**Issue by gamrek** [Microsoft/MixedRealityToolkit-Unity#1781]
## Overview
Using RemoveAllAnchors() after attaching WorldAnchor to a GameObject will return the following error: "NullReferenceException: Object reference not set to an instance of an object.". This issue is caused by line 325 in WorldAnchorManager.cs, where existing anchor is checking if it has a parent and its parent gameobject is equal to spatialMappingManager gameobject. However if existing anchor doesn't have a parent, comparing its parent gameobject will return an error. The correct way to check it is to check its transform component - e.g. "anchors[i].gameObject.transform.parent == spatialMappingManager.transform"

## Expected Behavior
All Anchors should be removed safely and return no error.

## Actual Behavior
Visual Studio return the following error: "NullReferenceException: Object reference not set to an instance of an object."

## Steps to reproduce
Create gameobject use WorldAnchorManager.Instance.AttachAnchor to add new anchor and remove it using WorldAnchorManager.Instance.RemoveAllAnchors().

## Unity Editor Version
2017.3.1 p1

## Mixed Reality Toolkit Release Version
2017.2.1.1 Patch Release

**Comment by HoloLensDev** [comment]
I have the same problem that the anchors will not saved, if i load my application again, no the anchorStoreCount is allways 0...
