### ISSUE TITLE
SimpleTagalong not working on Hololens in Unity 2017.3.1

### ISSUE THREAD

**Issue by MrDChristop** [Microsoft/MixedRealityToolkit-Unity#1793]
## Overview
The SimpleTagalong works in the Editor + in the Unity Holographic emulator (both modes).
But not when deployed on device. Its a Unity bug in GeometryUtility.TestPlanesAABB
which returns always true when running on the device. I noticed this on 2017.3.1 not before.
I post this here because i propose to remove the unitys TestPlanesAABB and use the 
 MathUtils.TestPlanesAABB from MRTK. Replacing the unity function with this one i got it to work again.

## Expected Behavior
Should tag along
## Actual Behavior
Does not when running on Devie
## Steps to reproduce_
Just run the HoloToolkit sample SphereTagalong and replace with SimpleTagalong
## Unity Editor Version
2017.3.1
## Mixed Reality Toolkit Release Version
2017.2.1.1

**Comment by tipiro85** [comment]
I have the same problem with Unity 2017.3.0 and the Holotoolkit 2017.2.1.3, someone found a solution ?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
