### ISSUE TITLE
Fast Configurable Shader goes all black on tiny scale

### ISSUE THREAD

**Issue by XPav** [Microsoft/MixedRealityToolkit-Unity#1794]
The Fast Configurable Shader turns some of my meshes all black when scaled to 1e-5, and none of the options seem to have an affect.

The Obsolete/Unlit shaders do work, and that's fine.

One might ask why I'm dealing with such a small scale, and that's because I'm scaling down the world.

**Comment by StephenHodgson** [comment]
Yeah, sounds like floating point issues.

**Comment by XPav** [comment]
Yeah, that's what some other similar problems say.  I don't mind that I have to use an Unlit shader, I suppose the question is if the Fast Configurable Shader can be made to work, or if there still needs to be an Unlit shader in the MRTK for edge cases like this.

**Comment by StephenHodgson** [comment]
@XPav have you tried the new shader system?

**Comment by XPav** [comment]
I have not.
