### ISSUE TITLE
Camera has been destroyed.

### ISSUE THREAD

**Issue by kvvishwa** [Microsoft/MixedRealityToolkit-Unity#1796]
## Overview
Hi,

I get the below error:

Exception in callback: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> UnityEngine.MissingReferenceException: The object of type 'Camera' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Debug:LogError(Object)
Vuforia.DelegateHelper:InvokeDelegate(Delegate, Object[])
Vuforia.DelegateHelper:InvokeWithExceptionHandling(Action)
Vuforia.VuforiaBehaviour:Update()

I am Trying to switch between Non AR scene --> AR scene --> Non AR Scene and then back to AR scene.

Moving from Non AR to AR scene works fine the first time. But it dosent work the second time.

I have included the VuforiaCameraIssueFix on the Non Ar scene.

Need help, I am not sure what I am missing, tried out various options.
## Steps to reproduce
_(Links to sample github project preferred)_

**Comment by StephenHodgson** [comment]
Sounds like an issue with Vuforia
