### ISSUE TITLE
focus at anywhere then tap will cause all the compound button state change to press state

### ISSUE THREAD

**Issue by DamonLau** [Microsoft/MixedRealityToolkit-Unity#1798]
## Overview

Focus at one game object then tap,if the game object is a target of a GlobalListener,the button state will change  to 'Pressed' state.If the focused game object implement the CompoundButtonMesh then we can achieve a pressed visual effect.
Other game object that has no focus should not change the button state.

## Expected Behavior
Other game object that has no focus should not change the button state.
## Actual Behavior
All the  game objects implement CompoundButton script whether have focus that changed the button state to 'Pressed' state.

Focus at anywhere then tap,all the  game objects implement CompoundButton script that changed the button state to 'Pressed' state.
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2017.3.0f3
## Mixed Reality Toolkit Release Version
v2017.2.1.2

**Comment by StephenHodgson** [comment]
That makes sense because you're making it a global listener.
