### ISSUE TITLE
2017.2.1.2 Patch Release compile errors

### ISSUE THREAD

**Issue by Backer-Sultan** [Microsoft/MixedRealityToolkit-Unity#1800]
## Overview
I'm getting two compile errors on an empty project with only the toolkit package imported.

## Expected Behavior
The toolkit compiles successfully.

## Actual Behavior
Getting two compile errors:
1. Assets/HoloToolkit/SharingWithUNET/Scripts/PlayerController.cs(341,13): error CS0246: The type of namespace name `UNetSharedHologram` could not be found. Are you missing an assembly reference?

2. Assets/Holotoolkit/SharingWithUNET/Scripts/PlayerController.cs(342,13): error CS0841: A local variable `ush` cannot be used before it is decleared

## Steps to reproduce
1. Start a new project.
2. Import package "HoloToolkit-Unity-2017.2.1.2". 
3. Click "Play".

## Unity Editor Version
2017.2.1.p2

## Mixed Reality Toolkit Release Version
2017.2.1.2

**Comment by CarpeTempus** [comment]
Same here. I was curious and tried it with Unity 2017.3.1p2 as well but unfortunately with the same result..

**Comment by mrmaxmagna** [comment]
got same error

**Comment by askor** [comment]
@mrmaxmagna it's fixed in 2017.2.1.3 Hot Fix
