### ISSUE TITLE
Dead Link in Documentation (404 - page not found)

### ISSUE THREAD

**Issue by CarpeTempus** [Microsoft/MixedRealityToolkit-Unity#1801]
## Overview
Hi, I was just reading the documentation and found a dead link:
Open https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit/UX in your Browser. Scroll down until you see step 4. with the text
> Follow the same steps for the sample text layout prefabs in HoloToolkit-Examples\Text

and click on the Link "HoloToolkit-Examples\Text".

## Expected Behavior
documentation should open

## Actual Behavior
Error 404 page not found

**Comment by cre8ivepark** [comment]
@CarpeTempus Thanks for opening this issue!
