### ISSUE TITLE
Suggestion: Refactor to use on other Plattforms

### ISSUE THREAD

**Issue by MarjanPl** [Microsoft/MixedRealityToolkit-Unity#1808]
Hi, I read already that you are planning to support other VR platforms. However, i am often asked to make demos on the hololens and then transfer the same to iOs Cardboard.
Hm. In older versions of the Toolkit it wouldn't even compile, don't know how it is now.

Would be great if one could separate all User Inputs from GameObjects (namely the new UX demo stuff).

But that is just wishful thinking. All the best!

**Comment by davidkline-ms** [comment]
@MarjanPl, We are, indeed, planning to support multiple XR/AR/VP platforms with our vNext release. 

We expect to release an aloha in mid-June, followed by a beta each of the next two months and a full, official release mid-September.

We look forward to your feedback!
