### ISSUE TITLE
Enable Sharing (SharingClient.dll) on Android

### ISSUE THREAD

**Issue by dzak83** [Microsoft/MixedRealityToolkit-Unity#1809]
## Overview
When building for Android, I am getting errors that SharingClient.dll is not available

## Expected Behavior
I should be able to use AR Core with SharingClient.dll

## Actual Behavior
DllNotFoundException: SharingClient

## Steps to reproduce
Switch platform in Unity to Android and build sharing example

## Unity Editor Version
2017.3.1f

## Mixed Reality Toolkit Release Version
Latest

**Comment by davidkline-ms** [comment]
@keveleigh, does this sound like that inspector checkbox / Unity 5.6 issue?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
