### ISSUE TITLE
[bugs/Suggestions] 关于沉浸式头显的传送方式

### ISSUE THREAD

**Issue by jesse51076008** [Microsoft/MixedRealityToolkit-Unity#1810]
在最新主分支（2018/3/8 master）版本中有几个问题（沉浸式头显）：

新建一个场景，添加【MixedRealityCameraParent】【DefaultCursor】【InputManager】后：

1.用控制器向前移动时，以高频率推动方向杆时，传送标记（就是地上那个箭头）会消失；
2.用控制器向前移动时，移动足够远的距离时，无法移动，传送标记没有动画，但传送标记仍然显示，建议不能移动时就让传送标记消失；
3.建议传送时，显示抛物线；

**Comment by StephenHodgson** [comment]
Hi, I lot of your concerns are addressed in the multipointer development branch.  We're currently working on an updated teleportation behavior that includes the parabolic raycasts and better support for cursors and teleportation hotspots. We'll be sure to address the issues you're having there.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
