### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by CarpeTempus** [Microsoft/MixedRealityToolkit-Unity#1811]
## Overview
I'm not sure if this is the right place to ask but does a tutorial exist somewhere which describes step by step how to implement sharing of objects and data? Since weeks I'm fighting with this topic now and it is very frustrating. The documentation provided with MRT (https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Sharing/README.md) is unfortunately not helpful. I've read the Microsoft Academy Tutorials (https://developer.microsoft.com/en-us/windows/mixed-reality/mixed_reality_250#digging_into_the_code) as well. Particularly the 'digging into the code' chapters are realy disappointing.

**Comment by Yoyozilla** [comment]
Sharing is getting revamped in V2. we will make sure to have tutorial and docs when it becomes available.
