### ISSUE TITLE
Is there a sample for Visual Pairing?

### ISSUE THREAD

**Issue by FireDragonGameStudio** [Microsoft/MixedRealityToolkit-Unity#1812]
As it's stated in the documentation, Visual Pairing is possible:

**Visual Pairing**
Connect devices just by looking at them
- One device displays a QR code with connection info and security code
- Other device sees QR code, connects, and validates with security code
- Can also detect location in 3D space using built-in fiducial marker support

Is there also a sample for this, or has anyone experiences using Visual Pairing?

Best regards :)

**Comment by davidkline-ms** [comment]
The may 2018 release (2017.4.0.0) contains a new feature called SpectatorView that does something similar to what  you suggest. A release candidate for 2017.4.0.0 is available now (a second RC should be available in the next day or so).

This implementation supports HoloLens to iOS/ARKit pairing.

**Comment by isurfraz** [comment]
is there still not a visual pairing sample yet? its july and this seems an important feature to building decent shared hololens experiences, which we hope to do currenltly being on the current MRPP cohort.

**Comment by davidkline-ms** [comment]
@isurfraz, I recommend investigating the SpectatorView feature that is in the HoloToolkit-PreviewFeatures package. Here is a [link to the 2017.4.0.0 release.](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/2017.4.0.0) Please note that SpectatorView has a dependency on OpenCV which is licensed separately and requires a separate build process.

Thanks!

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
