### ISSUE TITLE
Issues with UnityGLTF submodules when updating MRToolkit

### ISSUE THREAD

**Issue by rigma** [Microsoft/MixedRealityToolkit-Unity#1813]
## Overview

Hello there! So, I just updated my version of MRToolkit for Unity on a project and my Editor says something strange to me: the `UnityGLTF.GLTFSceneImporter.cs` has ambiguous references between `GLTF` namespace and `GLTF.Schema`.

So far, I've only got this class impacted by those ambiguous references, and they concern the following ones:

- `GLTFRoot`
- `MeshPrimitive`
- `Scene`
- `Node`
- `TextureInfo`
- `Image`

I think the issue comes from that the two namespaces are used in the class, should it be better if we use only one? If we do this, which namespace should I keep for this class? `GLTF` or `GLTF.Schema`? 

## Expected Behavior
The package should be imported without errors in Unity.

## Actual Behavior

![image](https://user-images.githubusercontent.com/1141506/37165479-ffd595a4-22fc-11e8-87bf-c8a5a029c0e3.png)

## Steps to reproduce
1. Take an old project made with MRToolkit
2. Update the MRToolkit with the new released one
3. Enjoy your compilation error

## Unity Editor Version
2017.3.1f1

## Mixed Reality Toolkit Release Version
2017.2.1.2

**Comment by StephenHodgson** [comment]
Did you delete the whole MRTK package in your project before reimporting?

**Comment by rigma** [comment]
Yes we did and the issue still occured.

**Comment by StephenHodgson** [comment]
> 3. Enjoy your compilation error.

I laughed way to hard at this. 😂

**Comment by StephenHodgson** [comment]
@kevleigh any ideas here?

**Comment by rigma** [comment]
So, I gave another try today by removing the whole package and by importing it again, and the issue had dissapeared. But another one took its place in the compilation error castle...

![image](https://user-images.githubusercontent.com/1141506/37200655-b1d29c10-2385-11e8-8a6a-8cd085f52c65.png)

With this error, I'm not able to launch the _Play mode_, and I have some components, like the `CompoundButtonMesh` which are not working anymore (not able to change the `ButtonMeshProfile` in this case).
Hopefully, this time, I was able to reproduce it on an empty project, that I've put on [this repository](https://github.com/rigma/TestsEnFolieWithMRToolkit) to illustrate the issue.

**Comment by DDReaper** [comment]
This new issue confused me, as in the latest release (this past week) the "SharingWithUnet" was completely moved to examples.  Yet your error shows it in the Main HoloToolkit folder, which shouldn't be possible.

**Comment by rigma** [comment]
It confuses me too. But, even after I download again the new release's package, the error is still here, in the main `HoloToolkit` folder. Do I need to import the examples package too?

**Comment by StephenHodgson** [comment]
@DDReaper I don't think we make a patch release for that issue. 

@rigma just remove the Sharing with unet folder if you're not using it, if you are then move the stuff from the sharing with unet examples folder into your project.

**Comment by keveleigh** [comment]
We definitely need to make a patch release for the non-building release (SharingWithUNET issue). We have the draft ready to go, right?

**Comment by StephenHodgson** [comment]
Planning on it.

**Comment by keveleigh** [comment]
Sweet! I misread that as "I don't think we'll make", so sounds good :)
