### ISSUE TITLE
 Please update SpectatorView to support at least Unity 2017.2 and work with the MixedRealityToolkit

### ISSUE THREAD

**Issue by jerrygg** [Microsoft/MixedRealityToolkit-Unity#1815]
We are using MixedRealityToolkit development, we will use SpectatorView, which is very important for developers, please update it

**Comment by StephenHodgson** [comment]
Spectator view has nothing to do with the MRTK, I believe this issue should be addressed in the [Mixed Reality Companion Kit](https://github.com/Microsoft/MixedRealityCompanionKit)'s repository.
