### ISSUE TITLE
Rotate a gameobject with gesture

### ISSUE THREAD

**Issue by Hobl1990** [Microsoft/MixedRealityToolkit-Unity#1816]
Hi guys,

I want to rotate a gameobject e.g. a cube with gestures. 
In #448 a version is mentioned, which I tried with the HoloLens.
Are there other versions available for rotating e.g. TryGetRotation?

Thanks,
Chris

**Comment by cre8ivepark** [comment]
You can use Bounding Box UI which is a standard interface for rotating & scaling object:
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit-Examples/UX/Readme/README_BoundingBoxGizmoExample.md

You can also use Two Hand Manipulation:
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit-Examples/Input/Readme/README_TwoHandManipulationTest.md

**Comment by Hobl1990** [comment]
@cre8ivepark  thank you for the information
