### ISSUE TITLE
UX Button disabled state doesn't prevent clicks

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#1827]
## Overview
Currently, if you have a button using the UX/Scripts/Buttons/Button.cs script, and have the ButtonState set to Disabled, clicking on the Button is not ignored and still causes a state change. 

Other functions, such as OnFocusEnter, OnFocusLost, OnHoldx, etc. check for disabled state, and jump out if found:

```
    if (!m_disabled)
```

However, TriggerClicked, OnInputDown, OnInputUp, OnInputClicked, check for "enabled", which is not a button state but a Behaviour property (not sure what that is). As a result, control still flows through the code and eventually sets the ButtonState to Observation, as well as hitting any code you have set up to handle the click event.

## Expected Behavior
Ignore clicks, state should not change.

## Actual Behavior
Accepts click, triggers event and changes state to Observation

## Unity Editor Version
2017.3.1p2

## Mixed Reality Toolkit Release Version
Dev

**Comment by genereddick** [comment]
Changing the line:

```
if (enabled)
```

To
```
if (enabled && !m_disabled)
```

In each of: OnInputDown, OnInputUp, OnInputClicked, fixes this, though I'm not sure if the intention was to register a click so you can note that it occurred, in which case you might need to but the disabled check further down (before the state is changed and the even triggered). 

In addition, the enabled, m_disabled relationship is somewhat confusing.

**Comment by paseb** [comment]
In the original button code from MRDL a button could have a disabled state that is different from the monobehavior enable/disable state.  The purpose for this was to "grey" out a button when in a disabled state yet still be able to have functionality where it could enable itself based on state changes.  What @genereddick
