### ISSUE TITLE
FixedAngularSize

### ISSUE THREAD

**Issue by MrDChristop** [Microsoft/MixedRealityToolkit-Unity#1831]
## Overview
When using the FixedAngularSize.cs on the cursor, i observed a flicker when it was going from an intersection of an object that was far to an empty area (whereby placing the cursor at the default distance).
I found that the scaling of the cursor was done in the FixedAngularSize.cs Update(), but its positioning from the GazeManager.Update(). So if the FixedAngularSize update is called first and then the Gazemanager.Update is done afterwards you would get the wrong scale for one frame.

I fixed this by changeing Update to LateUpdate in FixedAngularSize.cs to make sure that the scaling of the cursor is computed after its placement.

## Expected Behavior
No flicker
## Actual Behavior
Flickers when going form far to near.

## Steps to reproduce
Add component to a cursor. SO that the cursor stays always the same size, irrespective of near or far.
Then try to look at a few objects you have setup near and far from the camera. When the cursor leaves the focus of an object i observed a slight jump (imminent resize) of the cursor. The explanation is above.
its a really simple fix....

## Unity Editor Version
2017.3.1.p2
## Mixed Reality Toolkit Release Version
2017.2.1.1

**Comment by StephenHodgson** [comment]
Please fill in reproduce steps

**Comment by davidkline-ms** [comment]
@MrDChristop, I'll take a look at FixedAngularSize.cs and try your suggested change.
Thanks!

**Comment by davidkline-ms** [comment]
@MrDChristop, This fix is in the Patch4_Dev branch and will be pushed into master with the next release.
