### ISSUE TITLE
Change modules in spatial mapping API from private to protected (where extension is plausible)

### ISSUE THREAD

**Issue by Shubham7694** [Microsoft/MixedRealityToolkit-Unity#1832]
## Overview
Currently the a lot of spatial mapping api capability seems private. We need to change them to virtual, protected, inherit & override to use our own modification. Later if MRTK makes any update, we need to repeat the same changes. It better can be done from MRTK side. It is a suggestion. Please guide us if there is any other alternative.
## Expected Behavior
Create classes/modules that can be inherited and modified by user without requiring effort (changing protected ..virtual etc...) if it is changed from MRTK side.

**Comment by StephenHodgson** [comment]
We're looking at making much of the MRTK modular and extensible in vNEXT. We'll def revisit this and make sure we make a nice SDK interface here for what you're proposing.

**Comment by Shubham7694** [comment]
@StephenHodgson  Thank you. Will wait for the next version.
