### ISSUE TITLE
Supporting Navigation events with editor hand simulation input

### ISSUE THREAD

**Issue by MrDChristop** [Microsoft/MixedRealityToolkit-Unity#1833]
## Overview
I would like to extent the CustomInputSource.cs to support Navigation Gesture events.
I looked at how the Manipulation gestures were emulated and now have a working prototype.
I dont support NavigationRails with what i have now.
The Wiki says i should ask here first before forking. Is this something you would be interested in?
I like the ability to use MRTK in a Hololens project emulating input using Mouse/keyboard, unfortunately only the Manipulation Gesture is currently supported.

**Comment by StephenHodgson** [comment]
Sounds like a great idea. Can't wait to see what you come up with.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
