### ISSUE TITLE
Room mesh not anchored in view. Sharing anchors fails sometime.

### ISSUE THREAD

**Issue by sebrk** [Microsoft/MixedRealityToolkit-Unity#1836]
## Overview
Recently I've been having a whole lot of weird issues with MRTK and the Hololens. Room meshes seem to get stuck in the frustum and sharing anchors works sometimes, sometimes not. These things have been working before without me doing any changes to my code.

I've been using TapToPlace to place Holograms and then share it directly P2P using TCP. This has worked fine but now I get really weird behaviour like the the wireframe mesh getting "stuck" and moves with the device and so on. When I share Holograms sometimes it works perfectly, sometimes the Hologram on the receiver gets stuck at (0,0,0 : Hololens head position). I have verified the anchor data that is sent. It is the exact same data down to the bit. Export and import is also successful. It just seems random to me. I have tried to delete spaces, no change.

Question: even if it is indeed placed in (0,0,0) shouldnt the Hologram jump to the correct position after a while when the spatial understanding is the same?

Also, I have the other Unity bugs with color separation and wobbling Holograms.

Does anyone know what is going on? I get the feeling that there is something fundamental wrong somewhere...

## Expected Behavior
Sharing anchors works, room meshes map correctly.

## Actual Behavior
Works sometimes.

## Unity Editor Version
2017.2.1f1

## Mixed Reality Toolkit Release Version
2017.2

**Comment by timGerken** [comment]
Unity had a pretty nasty bug with the Stabilization Plane that wasn't fixed until Unity 2017.2.2p1. Try upgrading to that version of Unity or, try disabling the StabilizationPlaneModifier.

**Comment by sebrk** [comment]
@timGerken I can't seem to find that version only 2017.2.2f1. Is this what you are referring to?

**Comment by timGerken** [comment]
https://unity3d.com/unity/qa/patch-releases/2017.2.2p1

**Comment by sebrk** [comment]
I did update and tried it out. It did get better but holograms still wobble a bit at times. Not as much as before but still. Color separation is also still there, I doubt it is impossible to completely get rid of this because of the hardware itself. It's better but still quite noticeable at times, especially white text on transparent/black background. Is this your experience as well @timGerken ?

**Comment by timGerken** [comment]
yes, white will always show color separation with a moving hologram (or hololens) because white uses all three channels (with green rendered twice).

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
