### ISSUE TITLE
Documentation question : ImportExportAnchorManager 

### ISSUE THREAD

**Issue by maguileracanon** [Microsoft/MixedRealityToolkit-Unity#1837]
## Overview

Hi Everyone, this is more a Documentation question. On the Sharing readme file, it is mentioned the **ImportExportAnchorManager**  as part of the SharingTest.unity scene.  (https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Sharing/README.md) 
However, on the example scene I can't find the instance of this singleton. I hae tried looking inside of the scripts that are actually on the scene to find if some of them attach the  _ImportExportAnchorManage_ to the anchor gameobject but I had no luck. 

Is this script actually called on the SharingTest scene or is there any other script that calls it somehow???.
Sorry if it is a silly question, I just got a little bit confused by the documentation .

Thanks in advance for any help you could provide me on this

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
