### ISSUE TITLE
Error with Build Appx Package

### ISSUE THREAD

**Issue by moshiwoxin** [Microsoft/MixedRealityToolkit-Unity#1841]
## Overview
When building Appx package with build window, get the error: Win32Exception. No change with Unity Editor and VS, could work well last day but raise this error when trying to build now.
## Expected Behavior
get the Appx package
## Actual Behavior
Win32Exception: ApplicationName='cmd.exe', CommandLine='/C vswhere -version 15.0 -products * -requires Microsoft.Component.MSBuild -property installationPath', CurrentDirectory='C:\Program Files (x86)\Microsoft Visual Studio\Installer', Native error= The system cannot find the file specified.
## Steps to reproduce
_(Links to sample github project preferred)_

![image](https://user-images.githubusercontent.com/12681054/37562605-f08dccb2-2aa7-11e8-991e-6d49b750f00b.png)
![image](https://user-images.githubusercontent.com/12681054/37562615-5b00ff56-2aa8-11e8-9d1f-6711250fd426.png)

## Unity Editor Version
Unity -- 2017.3.1f1
VS -- 15.6.2
## Mixed Reality Toolkit Release Version
2017.2.1.3 Hot Fix

**Comment by StephenHodgson** [comment]
Add your build settings in the repro steps please.

**Comment by StephenHodgson** [comment]
Chances are you don't have your dev environment setup correctly.

**Comment by moshiwoxin** [comment]
have correctly setup dev environment, and could build two days ago, maybe it has some relation with my windows insider update, my system version is 1803

**Comment by StephenHodgson** [comment]
Nah, I've got that insider preview installed as well. No issue here.

**Comment by samharper94** [comment]
That looks like a VS error from the error output, are you able to build other projects in it? Maybe your VS installation is a bit screwed and needs a clean install.
