### ISSUE TITLE
SharingSpawnTest scene can't spawn object

### ISSUE THREAD

**Issue by jayhersk** [Microsoft/MixedRealityToolkit-Unity#1843]
Hi,

I have been trying to run the SharingSpawnTest scene from the examples folder, but I get an error whenever I try to create an object (using the voice keywords on the HoloLens, or the key presses in editor). The error message is "Can't spawn an object: PrefabSpawnManager is not initialized." I am using Unity version 2017.2.1f1, and toolkit version  2017.2.1.1. Any advice or ideas on how to fix are appreciated! Thanks in advance.

Best,
Jaylin

**Comment by jayhersk** [comment]
Update: This issue seems to have been caused by an issue with SharingService.exe. When I created the project initially and launched the sharing service, I was prompted to download the exe from this repo. However, this was using schema version 18, causing the error:

`List Server Handshake Failed: Invalid schema version.
Expected: 17, got 18
Please sync to latest XTools` 

Using an older version of the exe fixed the issue I was having, but if there is something else that I need to update that I am missing please let me know :)

**Comment by cuihee** [comment]
> 

> Update: This issue seems to have been caused by an issue with SharingService.exe. When I created the project initially and launched the sharing service, I was prompted to download the exe from this repo. However, this was using schema version 18, causing the error:
> 
> `List Server Handshake Failed: Invalid schema version. Expected: 17, got 18 Please sync to latest XTools`
> 
> Using an older version of the exe fixed the issue I was having, but if there is something else that I need to update that I am missing please let me know :)

As  you said , "Expected: 17, got 18", so check your MRTK's version and Server's Version . Make sure they are SAME. (it seems your Server's version is old)

**Comment by Yoyozilla** [comment]
Bulk closing older HTK bug. Please reopen if you can repro this issue in MRTK v2. 
Thanks!
Yoyo
