### ISSUE TITLE
Question about VoiceChat

### ISSUE THREAD

**Issue by shenwooash** [Microsoft/MixedRealityToolkit-Unity#1844]
## Overview
I am using VoiceChat scripts(MicrophoneReceiver.cs and MicrophoneTransmitter.cs) from MixedRealityToolkit-Unity, but I am only hearing my own voice..

## Expected Behavior
I can hear other's voice 

## Actual Behavior
I only can hear my own voice

## Steps to reproduce
1.Open the SharingTest scene which in the Assets\HoloToolkit-Examples\Sharing\SharingService\Scenes by unity.
2.Attached both MicrophoneReceiver.cs and MicrophoneTransmitter.cs onto MixedRealityCamera.
3.Publish the Unity Project to the two HOLOLENS.
4.Launch the Sharing Service on my Computer.
5.Launch the Unity App on two HOLOLENS and both two HOLOLENS successfully to connect to the server.

## Unity Editor Version
2017.2.0f3

## Mixed Reality Toolkit Release Version
2017.2.1.3 Hot Fix

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
