### ISSUE TITLE
InputManager crash because Unity EventSystem.current is null during initialization

### ISSUE THREAD

**Issue by joaocpaiva** [Microsoft/MixedRealityToolkit-Unity#1845]
## Overview
I am hitting a crash in InputManager because the inputEventData.selectedObject can't be evaluated, resulting a null reference exception and I found that it happens because EventSystem.current is null during InputManager initialization. Any ideas why this occurs?

## Expected Behavior
No crash

## Actual Behavior
Crash 

## Steps to reproduce
Air tap anywhere results in the crash

## Unity Editor Version
Unity 2017.3.1f1

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-2017.2.1.1

**Comment by StephenHodgson** [comment]
Not sure I can follow the repro steps, I don't know where to begin to get the same result.

**Comment by joaocpaiva** [comment]
@StephenHodgson once you get into this state then the repro steps are straight forward and consistent - the air tap gesture always results in null reference exception because the InputManager instance is not valid. 

Like I said, I debugged this and narrowed down to the fact that Unity **EventSystem.current** is null during InputManager Awake call. Do you know in what circumstances this can occur?

**Comment by StephenHodgson** [comment]
Do you not have an event system in your scene?

**Comment by joaocpaiva** [comment]
I do.

Funny enough, I have noticed this issue somehow gets fixed, if I clone the repo and build (/regenerate) the UWP project again, without any modifications to the code. I am a suspicious this could be bug in the result of the project generator that leads to different output between iterations. 

Or maybe an issue with the execution order that results in InputManager being initialized before EventSystem? I wonder, can we safely assume that Unity initializes EventSystem before Awake is called for InputManager?

**Comment by StephenHodgson** [comment]
Sounds about right. You could make sure your script execution order is setup so the event system is executed and created first.
