### ISSUE TITLE
Errors without Examples folder

### ISSUE THREAD

**Issue by Jarodshow** [Microsoft/MixedRealityToolkit-Unity#1851]
## Overview
If you remove the Examples folder, the toolkit fails to compile.
Due to [BoundingBoxRig](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit/UX/Scripts/BoundingBoxes/BoundingBoxRig.cs#L8) and [ProgressExampleLaunchButton](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit/UX/Scripts/Progress/ProgressExampleLaunchButton.cs#L54). 
Also [LoadingAnimation](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit/UX/Scripts/Progress/LoadingAnimation.cs#L7) and [ProgressExampleLaunchButton](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit/UX/Scripts/Progress/ProgressExampleLaunchButton.cs#L9) are part of the Examples namespace, not sure if this is intentional.

## Expected Behavior
Compiles

## Actual Behavior
Doesn't compile

## Steps to reproduce
Create empty project, import Dev_Working_Branch, and delete the Examples folder.

## Unity Editor Version
2017.3.1f1

## Mixed Reality Toolkit Release Version
[Dev_Working_Branch](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/Dev_Working_Branch)

**Comment by davidkline-ms** [comment]
@cre8ivepark, can you take a look at this?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
