### ISSUE TITLE
Keyboard Symbols layout is broken

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1852]
## Overview
Running the Keyboard in the editor works somewhat fine. Building it to the Hololens breaks the layout of the Symbols view. The "TAB", "!", "1" and "<" buttons are nowhere to be found. It looks like the first button of each of the button groups is missing. Also all the none character icons are white boxes.

## Expected Behavior
The keyboard shows everything where and how it should be like it does in the editor in Edit Mode

## Actual Behavior
Icons turn into white boxes in editor and build. Buttons are missing in the build

## Steps to reproduce
Latest Dev_Working_Branch
Add MR content to KeyboardTest scene and assign the UiRaycastCamera to the keyboard
Press play to note that the icons change
build it to a hololens and note that the layout is broken when toggling "&123"

## Unity Editor Version
2017.3.1p1

## Mixed Reality Toolkit Release Version
Latest Dev_Working_Branch 17.03.2018

**Comment by samharper94** [comment]
See #1744 for a possible fix.

> Add this:
>
>      `  if (!Application.isEditor) { return; }`
>To the CollectItems and UpdateLayout methods.

**Comment by Alexees** [comment]
@samharper94 thx. It feels weird as a solution, but it worked :)

**Comment by keveleigh** [comment]
From some debugging today, it looks like Unity 2017.3.1p1 had an issue with setting a RectTransform's anchorPosition to (0,0), which [line 196](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/UX/Scripts/UICollection.cs#L196) would do for the first buttons in each collection, when `Vector2 currentOffset = Vector2.zero;`. I checked by adding a small ϵ to either `x` or `y`, and the issue went away.

The proposed fix above this worked around it, by never calling the update methods. This preserved the layouting from the Editor.

I'm going to open a PR fixing the other half of this issue:
>Icons turn into white boxes in editor and build.
