### ISSUE TITLE
[master] Move MRTK versioning from Unity release based to SemVer

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#1859]
Our current, Unity release based versioning system is not NuGet friendly. To remedy this, we will be changing the MRTK version to be SemVer (http://www.semver.org) based.

The proposal is to use year.month.revision (ex: 2018.06.0) to version the MRTK, which will match the vNext versioning scheme. 

This will necessitate consumers of the toolkit to consult release notes and/or README.md to determine the supported Unity version(s) for the package, but will enable us to be more agile and clarify which releases contain new features and which contain only bug fixes.

**Comment by timGerken** [comment]
yay.
Unity version should just be ProjectSettings\ProjectVersion.txt, no?
If the final PR into master (or whatever the v.next release branch is) includes an update to ReadMe.MD that cites the release number, that would make it easy enough for me to reverse engineer where the bits came from.

**Comment by davidkline-ms** [comment]
The master branch, starting with the May 2018 release, will be **2017.4.**x**.0** where x will increment with each release.

**Comment by davidkline-ms** [comment]
@timGerken, not sure what ProjectVersion.txt will contain... yet

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
