### ISSUE TITLE
World Anchor Usage

### ISSUE THREAD

**Issue by Shubham7694** [Microsoft/MixedRealityToolkit-Unity#1866]
Is it okay to call world anchor api to attach or remove anchor frequently ? Does attach & remove anchor has any performance effect?
Use case: User is moving a hologram. I want to attach anchor once user does finger remove gesture. If user again presses finger, to move hologram i should remove world anchor and repeat the same.

Should world anchor attach & remove be tied to UI like button clicked to remove or to user actions like finger press gesture (while doing some action).

**Comment by calebcannon** [comment]
We've been using WorldAnchors pretty extensively with zero problems.  When unlocking an object for positioning (e.g., using HandDraggable), we delete the anchor immediately and recreate it when the drag operation is completed. I've yet to see a single side effect, even in scenes with dozens of anchors.

The only time we don't use anchors is when an object is expected to be more active than not: UI elements with Tagalong components, remote user avatars, etc.

**Comment by Shubham7694** [comment]
Thank you @calebcannon

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
