### ISSUE TITLE
ObjectCollection does not remove moved GameObject that is no longer a child from NodeList

### ISSUE THREAD

**Issue by MSDNAndi** [Microsoft/MixedRealityToolkit-Unity#1868]
## Overview
UpdateCollection() in ObjectCollection does not remove moved GameObject that is no longer a child from NodeList. It only removes GameObjects from NodeList that do not exist anymore, resulting in a wrong number of children and wrong layout
## Expected Behavior
When a GameObject is not a child, it should not be in the NodeList holding the children that should be laid out. 
## Actual Behavior
See above.
## Steps to reproduce
Add a GameObject (e.g. the cube primitive) as a child to a parent GameObject that has ObjectCollection, then call or select UpdateCollection, then move the GameObject elsewhere so it is no longer a child of the GameObject, select or call UpdateCollection on the parent GameObject. NodeList still contains the moved GameObject, resulting in the layout considering too many children.

**Comment by MSDNAndi** [comment]
While I believe I contributed a fix, for the issue described, I still find funky behavior when it comes to hierarchical object collections and their members, where I am not sure about the reason for it yet. I am not sure yet how to describe and repro the observed behavior I am still seeing.

**Comment by MSDNAndi** [comment]
I think I need to rework the fix. I should not have used IsChildOf as it uses deep children.

if (NodeList[i].transform == null || (IgnoreInactiveTransforms && !NodeList[i].transform.gameObject.activeSelf) || NodeList[i].transform.parent==null || ! (NodeList[i].transform.parent.gameObject==this.gameObject) )

Seems to be the better fix. I am not sure if I should open another issue and work against that new issue, if I should submit against this issue, or if I should just edit it again.

**Comment by davidkline-ms** [comment]
Please open a new issue and pull request.

Thanks!

**Comment by StephenHodgson** [comment]
Please keep issues open until they're merged with the master branch.

**Comment by MSDNAndi** [comment]
Sorry, didn't realize. Will they auto-close then?
________________________________

**Comment by davidkline-ms** [comment]
@MSDNAndi, Yes. We will close the issues when the release complete.
