### ISSUE TITLE
[master -> dev] integrate ObjectCollection fix

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#1871]
Ensure that dev_working_branch is updated with the fix (#1869) for #1868

**Comment by keveleigh** [comment]
dev_working_branch is now obsolete
![image](https://user-images.githubusercontent.com/3580640/55982603-1de0ff80-5c4e-11e9-9c1c-d641bfc2fd1f.png)
