### ISSUE TITLE
My UWP unity build seems to crash whenever I try to incorporate the Holotoolkit into the project.

### ISSUE THREAD

**Issue by JJloveshisspurs** [Microsoft/MixedRealityToolkit-Unity#1876]
## Overview
I've been working on a Mixed reality UWP app for months prior to incorporating the holotoolkit my builds were building fine, I've actually uploaded a build to the windows store  that passed certification and everything . I decided to incorporate the Holotoolkit to make use of the motion controllers but  whenever I do multiple breakpoints are triggered and if my app doesn't crash upon launching then it takes me to a scene that is unrendered outside of the Mixed reality headsets gaze tracker.

The breakpoint functions  that seem to be highlighted in debug mode are the following in the runtimehelpers.cpp class : 
```
 void RuntimeHelpers::RunClassConstructor(intptr_t typeIntPtr)
    {
        const Il2CppType* type = reinterpret_cast<const Il2CppType*>(typeIntPtr);
        IL2CPP_CHECK_ARG_NULL(type);

        Il2CppClass* klass = Class::FromIl2CppType(type);
        //MONO_CHECK_ARG(handle, klass);

        il2cpp::vm::Runtime::ClassInit(klass);
    }

    void RuntimeHelpers::RunModuleConstructor(intptr_t module)
    {
        NOT_SUPPORTED_IL2CPP(RuntimeHelpers::RunModuleConstructor, "This icall is not supported by il2cpp.");
    }
```

My console stack trace says the following  : 

```
(Filename: C:\buildslave\unity\build\Runtime/Mono/MonoBehaviour.cpp Line: 1753)

_CRT_ASSERT caught:
'''C:\Users\Evox VR Demo 04\Desktop\builds\RC7_MR_ReleaseBuild\Il2CppOutputProject\IL2CPP\libil2cpp\icalls\mscorlib\System.Runtime.CompilerServices\RuntimeHelpers.cpp(96) : Assertion failed: 0 && "RuntimeHelpers::SufficientExecutionStack"
'''
Stacktrace:
'Relay Cars.exe' (Win32): Loaded 'C:\Windows\System32\dbghelp.dll'. Cannot find or open the PDB file.
0x00007FF80A328314 (UnityPlayer) DllGetActivationFactory
```

I understand this is an issue with IL2CPP and possibly .net4.0 but I was getting security framework errors when using a .net backend  . 

## Expected Behavior
 When the unity app is launched in debug mode or when or from a generated app package it loads into my VR experience with the motion controllers included. 

## Actual Behavior
The app launches , in debug mode it triggers breakpoints and loads into a completely black scene where the gaze tracker is the only thing visible . When I launch it from a generated app package or the Mixed reality start menu  the app actually crashes back to the cliff house scene.

## Steps to reproduce
I basically am generating a unity build , and  running a debug project in Visual Studio if not directly creating an Master app package. 

## Unity Editor Version 
2017.2.1p2

## Mixed Reality Toolkit Release Version
2017.2.1.2 Patch Release  However I have tried this with several versions of the Mixed reality toolkit .

**Comment by StephenHodgson** [comment]
Looks like you're using IL2CPP for your scripting back end.

Could you provide a more detailed description of your project settings to make sure we can reproduce this independently?  Thanks.

**Comment by JJloveshisspurs** [comment]
Thanks for getting back to me so quickly and yes I am using IL2CPP as my scripting back end because as I explained earlier when I use .NET  I've gotten an error that states : 

 error CS0234: The type or namespace name 'X509Certificates' does not exist in the namespace 'System.Security.Cryptography

My current  build settings are  the following 

Target Device :  HoloLens
Build Type : D3D
SDK: 10.0.16299.0

Scripting Runtime Version : I've tried both   Stable ( .NET3.5 Equivalent) & Expirimental (.NET4.6 Equivalent)
Scripting Backed: IL2CPP
API Compatibility Level  .NET4.6

I will also include a screenshot  please let me know if I can give youanymore information . I also would be ok with sending you a copy of the build so that you can see the issue directly .  I don't know how useful that might be to you though.
![screenshot 44](https://user-images.githubusercontent.com/5290595/37861481-060e9e28-2ef8-11e8-8717-4f82aa67a264.png)

**Comment by StephenHodgson** [comment]
We don't use `System.Security.Cryptography` anywhere in the project.

**Comment by StephenHodgson** [comment]
What classes (in the toolkit) are throwing errors?

**Comment by JJloveshisspurs** [comment]
Our Uniweb plugin is what is throwing the error , so is the source of the issue justthat the Holotoolkit doesn't support IL2CPP currently ?

**Comment by StephenHodgson** [comment]
Pretty sure it does. I'll do a quick build to double check.

**Comment by StephenHodgson** [comment]
Yup, confirmed, I was able to build clean project with IL2CPP with the latest toolkit release.

**Comment by JJloveshisspurs** [comment]
hmm ok Thank you , you've been very helpful . I'm going to reach out to the Uniweb plugin developers and see if I can't find a way to use .NET as my scripting BackEnd to workaround this odd IL2CPP issue  and keep poking and prodding to make sure it's not a conflcit between my projects libraries somewhere.



I was curious but is there anyway to get a version of the plugin that only includes the Mixed Reality / immersive  experience libraries and not the hololens libraries  ?     I've made so many builds for the Immersive / Mixed reality headset that  work just fine but i've had a lot of trouble including the Holotoolkit as a whole into my project and truly the only thing I need is the ability to render the Motion controllers.

**Comment by StephenHodgson** [comment]
> I was curious but is there anyway to get a version of the plugin that only includes the Mixed Reality / immersive experience libraries and not the hololens libraries ? 

They use the same Windows APIs so that's not really feasible.

**Comment by JJloveshisspurs** [comment]
How unfortunate ok thank you very much ! I guess one last question before I close this out  . Can you give me any information I may not be understanding about the errors visual studio gave me in the debug stack trace and the breakpoint that was triggered in my initial post?

**Comment by StephenHodgson** [comment]
Sorry, don't much about cpp builds.

**Comment by JJloveshisspurs** [comment]
Thank youvery much , you've been a great help .
