### ISSUE TITLE
AppBar button stays focused

### ISSUE THREAD

**Issue by Jarodshow** [Microsoft/MixedRealityToolkit-Unity#1877]
## Overview
Leftmost button in the AppBar for BoundingBoxRig never becomes unfocused after adjustment.

## Expected Behavior
![oelizc7](https://user-images.githubusercontent.com/9560490/37864254-0f5592ce-2f3a-11e8-958e-1f8e3c9e8cb0.png)

## Actual Behavior
https://i.imgur.com/LY2RCdu.gifv

## Steps to reproduce
* Create scene with "defaults" (project settings, scene settings, etc.)
* Create cube in scene
* Attach `TwoHandManipulatable` and `BoundingBoxRig` to the cube
* Add a `BoundingBoxBasic` to the `BoundingBoxPrefab` field
* Play

Or simply play the BoundingBoxGizmoExample scene.

## Unity Editor Version
2017.3.1f1

## Mixed Reality Toolkit Release Version
Dev_Working_Branch

**Comment by cre8ivepark** [comment]
@davidkline-ms I have included the fix in the Patch4_Dev branch.

**Comment by davidkline-ms** [comment]
Thanks @cre8ivepark!
