### ISSUE TITLE
Tooltip has no line in the Hololens/Emulator

### ISSUE THREAD

**Issue by mrsniperz** [Microsoft/MixedRealityToolkit-Unity#1883]
## Overview

Tooltip has no line when running in the Hololens/Emulator,but a rosy surface in the front.

## Expected Behavior

![default](https://user-images.githubusercontent.com/35944209/37954770-604d8b22-31d9-11e8-9f2a-16e3a329bcb9.PNG)

## Steps to reproduce

- Create scene with "defaults" (project settings, scene settings, etc.)
- Create cube in scene
- Attach ToolTip.prefab to the cube
- Play
Or simply play the MixedRealityToolkit-Unity-Feature_UX_Tooltip\Assets\MixedRealityToolkit-Examples\UX\Scenes\TooltipExamples scene.

## Unity Editor Version

2017.2.1p4/2017.3.1p4

## Mixed Reality Toolkit Release Version

MixedRealityToolkit-Unity-Feature_UX_Tooltip

**Comment by cre8ivepark** [comment]
It seems like Unity version specific issue. Works well in 2017.2.1p2 with HoloLens.

**Comment by mrsniperz** [comment]
![default](https://user-images.githubusercontent.com/35944209/38121600-e282823e-3402-11e8-89f9-74c7b862f383.PNG)
Thx for your reply Park,but i tried it in the 2017.2.1p2 the problem remains.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
