### ISSUE TITLE
Button.cs ButtonState is incorrect

### ISSUE THREAD

**Issue by jonboris** [Microsoft/MixedRealityToolkit-Unity#1887]
## Overview
**This is HoloLens-only issue.** 
Button.cs has separate states to signify when the button has been focussed and unfocussed with the user's hand(s) raised and ready or lowered. However, these states are unpredictable and quickly fall out of sync with the user's true hand state. 

## Expected Behavior
1. Hand down, not looking at button, ButtonState = Observation
2. Hand down, looking at button, ButtonState = ObservationTargeted
3. Hand ready, looking at button, ButtonState = Targeted
4. Hand down, looking at button, ButtonState = ObservationTargeted
5. Hand down, not looking at button, ButtonState = Observation

## Actual Behavior
1. Hand down, not looking at button, ButtonState = Observation
2. Hand down, looking at button, ButtonState = ObservationTargeted
3. Hand ready, looking at button, ButtonState = Targeted
4. Hand down, looking at button, ButtonState = **Targeted**
5. Hand down, not looking at button, ButtonState = **Interactive**

**From here it is not possible to get back to Observation or ObservationTargeted states.**

## Steps to reproduce
1. Open an empty scene and from the MRTK menu do 'apply mixed reality project settings' and 'apply mixed reality scene settings'
2. Create a cube in the scene and drag on the Button.cs script from MRTK
3. Hit run and go through the expected behaviour steps outlined above, observing the 'button state' property on the button component.

## Unity Editor Version
Unity 2017.3.1p3

## Mixed Reality Toolkit Release Version
2017.2.1.2

**Comment by davidkline-ms** [comment]
Confirmed this behavior in the may18_dev branch. Looking into a fix

**Comment by davidkline-ms** [comment]
Just a note that my confirmation was in editor.

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
