### ISSUE TITLE
glTF LoadImage method throws InvalidOperationException on HoloLens

### ISSUE THREAD

**Issue by havalbon** [Microsoft/MixedRealityToolkit-Unity#1888]
## Overview
Attempting to load a glTF model on the HoloLens throws an InvalidOperation exception when the GLTFSceneImporter tries to load the first texture. It appears to be the call to www.downloadHandler.GetContent() that is causing the issue, though I'm not clear why. Replacing this line with the following resolves the issue:

var texture = ((DownloadHandlerTexture)www.downloadHandler).texture;

## Expected Behavior
I expect the glTF model to load successfully.

## Actual Behavior
Exception is thrown and loading is aborted.

## Steps to reproduce
The following code, run on HoloLens, should reproduce the issue:

var sceneImporter = new GLTFSceneImporter(
                uri,
                null,
                false);
            sceneImporter.SetShaderForMaterialType(GLTFSceneImporter.MaterialType.PbrMetallicRoughness, StandardShader);
            sceneImporter.SetShaderForMaterialType(GLTFSceneImporter.MaterialType.KHR_materials_pbrSpecularGlossiness, StandardShader);
            sceneImporter.SetShaderForMaterialType(GLTFSceneImporter.MaterialType.CommonConstant, StandardShader);
            
yield return sceneImporter.Load(-1, true);
var lastLoadedScene = sceneImporter.LastLoadedScene;

## Unity Editor Version
2017.3of3

**Comment by StephenHodgson** [comment]
Please raise this issue over on the [glTF repository](https://github.com/KhronosGroup/UnityGLTF).
