### ISSUE TITLE
MR toolkit Motion controllers not rendering in app on Initial launch

### ISSUE THREAD

**Issue by JJloveshisspurs** [Microsoft/MixedRealityToolkit-Unity#1889]
## Overview
When I make a .appx project the motion controllers are not showing up on initial launch but do appear if I suspend and re-enter the already open app . I built the project with only the Holo Toolkit  motion controller example scene and in place of the controller models I see two  white cuboids instead of the controller models.

## Expected Behavior

Every time the app launches ( 1st time or 50th) the motion controller models are rendered in my project if activated/ on

## Actual Behavior
On the very first app launch the Motion Controllers do not render at all and the custom rays I have built to connect to the controllers are  unresponsive as if the objects aren't even being instantiated.

## Steps to reproduce
-Put HoloToolkit Motion controller prefab in very fist scene which unity loads with build settings
- test that Motion controllers render in editor
- Create an .appx package
- On the first launch test if  Controller models render in scene, you can reproduce multiple times by closing the app and re-launching the application again .

When I did it using the HoloToolkit example scene , White cuboids rendered in the scene instead of the actual Motion controller models.

## Unity Editor Version
2017.4.0f1

## Mixed Reality Toolkit Release Version
2017.2.1.3

**Comment by StephenHodgson** [comment]
@keveleigh thoughts?

**Comment by JJloveshisspurs** [comment]
I will work through testing the compatibility between various versions of Holotoolkit and the Unity versions.

**Comment by JJloveshisspurs** [comment]
I've moved to unity version :  2017.2.1p2  and Holo Tookit version :  2017.2.1.2 Patch Release . unfortunately I am still getting the white cubes in the Holotoolkit example controller scene **I did notice a log however that states :  Model task is null, Loading alternate.**     
  
I can of course infer that that means there is an issue loading the controller model and it's trying to use the alternate default model however is there any reason that that might happen in the example scene ?

**Comment by JJloveshisspurs** [comment]
I ended up fixing this issue by making my scripting backend  .Net - based , removing a few of the plugins with broken references , and  I did have to comment a few functions who lost reference to their respective libraries.    I still don't understand what the crux of the issue was but   I know it had to do with IL2CPP and loading the camera in a custom scene .  Closing Issue.
