### ISSUE TITLE
Trying to access file storage / switch between XAML and D3D causes app to get stuck trying to do spatial mapping

### ISSUE THREAD

**Issue by c-marinos** [Microsoft/MixedRealityToolkit-Unity#1890]
## Overview
Using an asset in the Unity store I was able to get files from OneDrive. I then tried adding MixedRealityToolkit to my app, some holographic buttons, the default cursor, and input manager. When I try to load files into the app now, it causes the app to get stuck on mapping the space. This is when it goes from XAML (File Explorer) back to D3D.  

This asset works using standard HoloLens Input Module and HoloToolkit from Gaze 210 HoloAcademy tutorial in Unity 5.6.5 on the new RS4 preview. (* Without the RS4 preview I have only ever been able to get this asset to work on 5.5.1, and it is slower and buggier than with the RS4+Unity 5.6.5 combo). Additionally, MixedRealityToolkit is no longer compatible with 5.6.5.

One way this could be addressed is to create standard file IO scripts that allow a D3D app to switch to File Explorer and that are known to work with this toolkit. (edit: by "file IO" I should have said "windows storage" here, as UWP apps don't use file IO)

## Expected Behavior
File should be loaded in and I am able to proceed using my app. 

## Actual Behavior
While in XAML File Explorer, D3D components of app sometimes still appear in the corner of eye. App then gets stuck trying to map my surroundings after picking a file to load and returning to D3D app.

## Steps to reproduce
On the RS4 Preview:
Create a Unity project and import this asset (or possibly any asset which switches between XAML/D3D will do this)
Put any .txt file in your OneDrive and make sure OneDrive app is synced on your HoloLens
Create a holographic button to load a file in using File Explorer
Click button and pick a .txt file from OneDrive

Sample app:
https://s3.amazonaws.com/sapph/ReadFile.rar
If successful, Text element should have text from first line of .txt file

## Unity Editor Version
Unity 2017.2.1

## Mixed Reality Toolkit Release Version
Current (3/28/2018)

**Comment by StephenHodgson** [comment]
File.IO namespace is not availible in UWP per the platform specs.

**Comment by StephenHodgson** [comment]
https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-listing-files-and-folders

**Comment by c-marinos** [comment]
There is already an asset in the Unity project I provided in the link that handles accessing the File Explorer / OneDrive. My issue is not that I don't have this at all, my issue is that it is broken with this build. The only differences between what I had working earlier and what doesn't work now is I upgraded the Unity version from 5.6.5 to 2017.2.1 and the toolkit from the one in the Gaze 210 tutorial to this one. I could try the combination of 5.6.5 and the MixedRealityToolkit to see if the issue is with the new Unity version but when I tried that earlier the scripts in MRTK created errors in the console.

**Comment by StephenHodgson** [comment]
Ah I see. I'll reopen then.

**Comment by c-marinos** [comment]
Great news: It works using Unity 2018.1b and SDK 17125. The issue appears to have been with Unity 2017.2.1.

**Comment by StephenHodgson** [comment]
Thanks for the heads up.

**Comment by StephenHodgson** [comment]
I wonder if this is an issue for UWP apps in general and not just the HoloLens.
