### ISSUE TITLE
 Hololens application crashes randomly

### ISSUE THREAD

**Issue by TheYoxy** [Microsoft/MixedRealityToolkit-Unity#1891]
## Overview
I'm using an asset, this [Toolbar](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX/Prefabs/ToolBar.prefab), but when I build and deploy on the Hololens, some times it crashes, but some times, it doesn't. I checked everything around this toolbar, but it appear randomly. This bug occurs, when we are loading a toolbar outside a scene, and we look at while a loading. When it occurs, the application freeze, and we can only stop it from the web portal of the helmet. 

## Actual Behavior

![git](https://user-images.githubusercontent.com/23502440/38072307-f89ad3e2-3325-11e8-918e-40c319336441.png)
It crash when this menu enter in the field of view, but not all the time.

## Steps to reproduce
- Scene with this toolbar
- Spawn the toolbar outside the default view
- Deploy the application in release mode
- It occurs on a physical Hololens and on an Emulator
- Pray it occurs
## Unity Editor Version
2017.3.1f1
## Mixed Reality Toolkit Release Version
Current (28/3/2018)
(168fd6f4112831a9eefade8125dad4434ea0bfbb)

**Comment by StephenHodgson** [comment]
Can you provide us with a stack trace?

**Comment by TheYoxy** [comment]
We aren't able to provide any stacktrace, when the app crash, we can only see 2 threads in `app.cs`

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
