### ISSUE TITLE
World Anchor Issues

### ISSUE THREAD

**Issue by RossKasal** [Microsoft/MixedRealityToolkit-Unity#1899]
## Overview
Hello,
I cloned the mixed reality toolkit for unity and I am attempting to use world anchors for an environment in Hololens.
## Expected Behavior
Ideally the app would create and remove world anchors using the airtap functionality in Hololens.
## Actual Behavior
For some reason I can not find the reference for "WorldAnchorManager" so I can not build my code.
## Steps to reproduce
Here is a picture of my code output.

<img width="949" alt="screen shot 2018-03-30 at 12 05 30 pm" src="https://user-images.githubusercontent.com/32202351/38144534-168625bc-3413-11e8-95fd-619e4aaf81f2.png">

## Mixed Reality Toolkit Release Version
Latest Master

**Comment by Jarodshow** [comment]
master's `WorldAnchorManager` is currently part of the [HoloToolkit.Unity](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/8066264cad070f25094bdc79110ef827d08c292b/Assets/HoloToolkit/Common/Scripts/WorldAnchorManager.cs#L22) namespace.

**Comment by StephenHodgson** [comment]
What version of Unity are you using?

**Comment by StephenHodgson** [comment]
Sounds like you're missing part of the library.  Also make sure that your build settings is targeting UWP.

**Comment by RossKasal** [comment]
I am running this on a mac using Unity 2017.3.1f1

I also have the HoloToolkit downloaded (git clone). But for some reason when I do the 

using HoloToolkit.Unity.(fill in here) WorldAnchorManager does not show up.

**Comment by Jarodshow** [comment]
`using HoloToolkit.Unity;` worked fine for me, just cloned it too.

**Comment by StephenHodgson** [comment]
Pretty sure the `WorldAnchorManager` is only availible on Windows/UWP anyway.  Make sure you switch your build target to one of those.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
