### ISSUE TITLE
Sharing: UNET or Sharing service

### ISSUE THREAD

**Issue by zhangalex** [Microsoft/MixedRealityToolkit-Unity#1902]
Recently I'm learning Hololens development from Hololens Academy. I notice that both holograms-240 and holograms-250 have sharing demo, but 240 is using SharingService.exe, however 250 is using UNET.  I am a little confused that what's the difference between two technologies?

**Comment by StephenHodgson** [comment]
240 is using a server written by JPL back in the day and is based off of RackNet.  The source code is hosted in the MixedRealityToolkit and is cross platform.

250 is using the built in Unity Networking services UNET.

The Sharing Service is free, where UNET may have some cost incurred depending on the usage.

**Comment by zhangalex** [comment]
@StephenHodgson   Thank you.
