### ISSUE TITLE
MRTK vNEXT Sprint 1

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1903]
## Overview
We're starting the first sprint for vNEXT MRTK.

April 4-17, 2018

## Sprint Goals

- [x] Updated Namespace to align with Microsoft NuGet Naming standards.
- [x] #1906 Controller / Headset definitions.
- [x] Initial MixedRealityManager and configuration profile.
- [x] #1901 2018 Support.
- [x] DocumentationGuidelines.md written.
- [x] Add Enum standards to coding guidelines.
- [x] Add Generic Event System.
- [x] Porting over the Input System into vNEXT.

**Comment by StephenHodgson** [comment]
@davidkline-ms and @SimonDarksideJ and anyone else please edit this issue if you want to see things added to this sprint.

**Comment by SimonDarksideJ** [comment]
Will work on the namespace and add the initial edition of the MixedRealityManager.
Initial version will be basic and evolve with vNext

**Comment by davidkline-ms** [comment]
Sprint 1 Complete!
