### ISSUE TITLE
Immersive Headset's camera starting position

### ISSUE THREAD

**Issue by pxk5958** [Microsoft/MixedRealityToolkit-Unity#1905]
## Overview
I have set boundaries for the immersive headset and the camera seems to start at random offsets in the virtual world, no matter what I set it in the editor. Can someone please explain the exact behavior (or its code) so that I can work around it? I just need the camera to start at a fixed X,Z position in the virtual world.

## Expected Behavior
I need some predictability of where exactly the camera is repositioned to.

## Actual Behavior
Seems random offset to me, but I am not sure if there is some explanation for it.

## Unity Editor Version
2017.3.1f1

## Mixed Reality Toolkit Release Version
2017.2.1.1

**Comment by StephenHodgson** [comment]
The camera should always start at the scene origin. (0,0,0)

**Comment by pxk5958** [comment]
So the camera starts at the scene origin, and then Unity updates the camera's transform coordinates based on the boundary type? What kind of adjustment does it do exactly? And the rest of the scene remains as such?

**Comment by StephenHodgson** [comment]
Checkout https://docs.unity3d.com/ScriptReference/XR.InputTracking.html

**Comment by StephenHodgson** [comment]
Closing this because the issue doesn't relate specifically to the MRTK.  Please open it again if you find that something in the toolkit is adversely affecting the positions.
