### ISSUE TITLE
Check for Windows 10 SDK reports it is missing when there is only 1 SDK installed.

### ISSUE THREAD

**Issue by blaynewatt** [Microsoft/MixedRealityToolkit-Unity#1910]
## Overview
Warning about wrong SDK version with correct version installed
## Expected Behavior
No Warning
## Actual Behavior
Warning in console:
Unable to find the required Windows 10 SDK Target!
Please be sure to install the 10.0.16299.0 SDK from Visual Studio Installer.
## Steps to reproduce
Use the Mixed Reality build dialog and check the console.

## Unity Editor Version
2017.4.0f1
## Mixed Reality Toolkit Release Version
latest release

<pre>
            for (var i = 0; i < windowsSdkPaths.Length; i++)
            {
                if (string.IsNullOrEmpty(currentSDKVersion))
                {
                    currentSDKVersionIndex = windowsSdkPaths.Length - 1;
                }
                else
                {
                    if (windowsSdkPaths[i].Equals(SdkVersion))
                    {
                        currentSDKVersionIndex = i;
                    }
                }
            }

            if (currentSDKVersionIndex == 0)
            {
                Debug.LogErrorFormat("Unable to find the required Windows 10 SDK Target!\nPlease be sure to install the {0} SDK from Visual Studio Installer.", SdkVersion);
            }
</pre>

New to reporting on issues, so please excuse if I made an error.

In my case, I have ONLY 10.0.16299.0 installed.  The code above checks if index == 0, and reports a warning that it's not there.  The problem is, index 0 is the first entry in the string array, which equals 10.0.16299.0.  Suggested fix is to initialize currentSDKVersionIndex to = -1, and check if == -1, instead of 0.

Thanks!

-Blayne Watt

**Comment by StephenHodgson** [comment]
Did you install the SDK in a a custom location?

**Comment by blaynewatt** [comment]
It is in the standard location.  I traced the code, it finds my folder.  The contents of windowsSdkPaths[0] (array of length 1) and currentSDKVersion is  "10.0.16299.0".  That sets the currentSDKVersionIndex to 0.

The check appears to be invalid, because if the index is 0, it says it's not installed.  This is listed as an error in the console, but does continue the build... it's not breaking, but it appears to me that this is a false error.

**Comment by StephenHodgson** [comment]
Double checked, I had fixed this issue in the dev branch.

**Comment by blaynewatt** [comment]
Great, thank you very much.  Do you happen to know when the next release will be?  How stable is it to use the Dev branch?

Also, is there a discussion forum specifically for the MRTK?  I have some issues with getting a successful appx build, and don't know where to go (sorry for asking in an issue report)

**Comment by StephenHodgson** [comment]
Probably shouldn't use the dev branch, it's pretty unstable.
@davidkline-ms, when do you think we'll be pushing out the next patch?

**Comment by StephenHodgson** [comment]
> Also, is there a discussion forum specifically for the MRTK? 

Yup, we've got a [slack channel](https://holodevelopers.slack.com), and there's the [Microsoft Developer Forums](https://forums.hololens.com/), and [Unity's Forums](https://forum.unity.com/forums/windows-mixed-reality.102/) as well.

> I have some issues with getting a successful appx build, and don't know where to go (sorry for asking in an issue report)

Let's open a new issue for a different problem.

**Comment by davidkline-ms** [comment]
@StephenHodgson, Patch4 (2017.2.1.4) should be going out mid April. I am targeting the week of 4/16

**Comment by davidkline-ms** [comment]
Adding this to the April (aka Patch4) release. I'll port @StephenHodgson's fix.

**Comment by davidkline-ms** [comment]
Looks like the fix may already be in Patch4.... I do not see the explicit check for index==0. Testing now.

**Comment by davidkline-ms** [comment]
![capture](https://user-images.githubusercontent.com/13281406/38510302-7250b7b8-3bd9-11e8-8148-21e4eb7bb254.PNG)

**Comment by blaynewatt** [comment]
I downloaded the pre-built release unity package...

HoloToolkit-Unity-2017.2.1.3.unitypackage

-B
