### ISSUE TITLE
Auto discover server connect stupidly

### ISSUE THREAD

**Issue by TheYoxy** [Microsoft/MixedRealityToolkit-Unity#1912]
## Overview
While using sharing, the `auto discover` server is an option that can be really useful. But this option looks buggy. When I use it on a computer that has many network interfaces, I only get the 1st ip address available on the server, which is, in most cases, not the right one.

![64c017da571827394f28aa46a0ac55d3](https://user-images.githubusercontent.com/23502440/38302230-363ad612-3802-11e8-843f-75196f485e4e.png)
As we can see on the picture, the ip address of the server that was discovered, is the first avaliable ip on the SharingService, and not the right one. 

An other bug here is that we can't use `SharingWorldAnchorManager` and `AutoJoinSessionAndRoom`, because they have the connect script only in the `Start()` method, and they don't have an other method to start anywhere else. This problem has been fixed in the issue #1911. This problem can be avoid by disabling both scripts while the `Sharing Stage` try to find servers, and enable them when a server has been found.

## Expected Behavior
`Auto discover` returns the ip address where the device can actually connect itself.

## Actual Behavior
`Auto discover` takes the first available ip address from the server.

## Unity Editor Version
2017.4.0f1

## Mixed Reality Toolkit Release Version
168fd6f4112831a9eefade8125dad4434ea0bfbb

**Comment by FlorianJa** [comment]
> As we can see on the picture, the ip address of the server that was discovered, is the first avaliable ip on the SharingService, and not the right one.

if client and server are running on the same machine, all IPs you are seeing in the server console are 'the right' one. What is the right one in your opinion?
The server console are telling you on which addresses the server is available.

**Comment by TheYoxy** [comment]
When I run it on the Hololens, I have the same issue, but in this case, I'm not on the same machine. I used Unity only to show the issue.

**Comment by TheYoxy** [comment]
They don't affect how it finds a connection, but there is no way to delay the start of the sharing, while using  the `AutoDiscover` function or any other ways. If there is a `AutoJoinSessionAndRoom` and `SharingWorldAnchorManager` activated, they try to connect when `Start()` is called, but you want to delay this.

**Comment by StephenHodgson** [comment]
>... they try to connect when Start() is called, but you want to delay this.

Oh I see, that makes sense.  I'll make sure to pull your request and check it out in action to get a better idea of what's going on.

**Comment by TheYoxy** [comment]
But don't forget about the initial bug, which is in the `SharingClient.dll`

**Comment by keveleigh** [comment]
@TheYoxy 
>But don't forget about the initial bug, which is in the SharingClient.dll

The DLL source can be found here, if you have an idea how to fix it: https://github.com/Microsoft/MixedRealityToolkit/tree/master/Sharing

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
