### ISSUE TITLE
FPSDisplay.cs calls InitBuffer every Update() when no TextMesh component added

### ISSUE THREAD

**Issue by Troy-Ferrell** [Microsoft/MixedRealityToolkit-Unity#1913]
## Overview
FPSDisplay.cs has the following if check every update() call:
if (fpsBuffer == null || fpsBuffer.Length != frameRange || textMesh == null)
         
The problem with this code is it only checks the textMesh property, not the uGUIText property. Thus, if the developer only attached to the uGUIText property, not the textMesh, then the if condition is evaluated true resulting in a call to InitBuffer() every update frame. 

This results in the following:
1) wasted performance (GC allocation of new int buffer as well as call to GetComponent<TextMesh>()) every frame 
2) Invalid FPS displayed to the nGuiText property component (since the bufferIndex is reset to 0 every frame)

Furthermore, note this is an issue if no TextMesh or Text component can be found every frame as well

## Expected Behavior
The buffer is created once and the script only tries to get a TextMesh and a Text Component once via GetComponent<>()

Ideally, the InitBuffer() is just called in Start() instead of using this if statement every update method

## Actual Behavior
The if statement is evaluated true every update method, resulting in 0 being displayed as FPS and wasted GC allocation every frame

## Steps to reproduce
Create a Text component to some canvas, attach the FPS display script and hook up the Text component the nGuiText property
Run game
See actual behavior

## Unity Editor Version
2017.3

## Mixed Reality Toolkit Release Version
Latest on master - 2017.2.1.3

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
