### ISSUE TITLE
[May18] Add UNITY_2017_[3|4]_OR_NEWER in scripts to eliminate deprecated API popups

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#1921]
Update the MRTK with support for the LTS version of Unity 2017 (2017.4.1f1)

**Comment by davidkline-ms** [comment]
https://unity3d.com/unity/whats-new/unity-2017.4.1

**Comment by StephenHodgson** [comment]
I don't think Master should move to 2017.4.

It'll break backwards compatibility with 5.6

**Comment by StephenHodgson** [comment]
If devs want to use 2017.4 they can and unity's auto updater will do everything they need.

**Comment by davidkline-ms** [comment]
@StephenHodgson, How would it break 5.6 compat? It didn't break when we went to 2017.1 and .2?
Thx!

**Comment by StephenHodgson** [comment]
Because unity made some Breaking changes to the Editor from 2017.2 -> 2017.3

**Comment by StephenHodgson** [comment]
The Unity API updater takes care of it for you.

**Comment by davidkline-ms** [comment]
Potential issue with shader changes needs investigation.... Can we #if UNITY_2017_... in the shader and allow support for pre/post 2017.3 changes?

**Comment by StephenHodgson** [comment]
> Potential issue with shader changes needs investigation.... Can we #if UNITY_2017_... in the shader and allow support for pre/post 2017.3 changes?

No. That's why I've been apprehensive about updating the editor and just letting Unity's auto updater do the work for us.

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
