### ISSUE TITLE
AutoConfigureMenu broken without .Net 4.6

### ISSUE THREAD

**Issue by jbienzms** [Microsoft/MixedRealityToolkit-Unity#1923]
## Overview
AutoConfigureMenu is broken in Dev_Working_Branch unless the player is set to .Net 4.6. 

## Expected Behavior
Mixed Reality Toolkit menu should appear and work in a new Unity project regardless of scripting runtime setting.

## Actual Behavior
Mixed Reality Toolkit menu only appears after changing the runtime to .Net 4.6. Console error messages do not explain the problem. 

This appears to be an issue with ActionExtensions.cs now depending on the null coalescing operator, which in turn depends on .Net 4.0+. This causes the project to fail to compile, which keeps the AutoConfigureMenu from appearing.

Since AutoConfigureMenu is the primary way most users will get their project setup correctly, it should work even without changing the framework version. If this is not possible (ill advised), setting the proper framework version needs to be called out and highlighted as a critical step in the Getting Started guide.

## Unity Editor Version
2017.4.0f1

## Mixed Reality Toolkit Release Version
Dev_Working_Copy

**Comment by StephenHodgson** [comment]
My apologies, this was my fault.

The is supposed to be a dialogue that should pop up if you don't have it enabled. I guess because there are compiler errors that code never runs.

**Comment by hannesne** [comment]
Maybe we could include a .Net 3.5 compatible compiled dll that is guaranteed to load independently from the rest of the MRTK, that can check prerequisites?

**Comment by StephenHodgson** [comment]
I think the only real way to do this is to use [custom assembly definitions](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html) but they only work in 2017.3+

**Comment by StephenHodgson** [comment]
I think amending the docs is probably the best course of action for the time being.

**Comment by jbienzms** [comment]
Interesting note about custom assembly definitions. I didn't realize those existed, so thank you for linking to the docs. How are you thinking this could help solve the problem? I could see if there was a way to mark the script as compiling against a different runtime that would work, but does this also control build order? If we say that it's targeted for Editor, will that guarantee it to compile even if the rest of the MRTK fails to build?

**Comment by StephenHodgson** [comment]
Yes, it also controls the assembly build and load order.

**Comment by StephenHodgson** [comment]
> Editor: Assembly Definition Files (asmdef) assemblies are now compiled on startup before any other scripts (Assembly-CSharp.dll and friends) and compilation does not stop on the first compile error. All asmdef assemblies that succesfully compile and have all their references compiled are loaded before compiling the remaining scripts (Assembly-CSharp.dll and friends). This ensures that Unity packages are always built and and loaded regardless of other compile errors in the project

**Comment by StephenHodgson** [comment]
There is a bug with Unity though, when importing an Asset Package the Assembly Definition Files aren't recompiled properly.
