### ISSUE TITLE
Grabber with default MotionControl model

### ISSUE THREAD

**Issue by Raqbit** [Microsoft/MixedRealityToolkit-Unity#1924]
## Overview

I want to use the default MotionControl model (loaded via dll) to work with the grabber script. The grabbable-demo uses alternaltive controller block-shaped prefabs to add the grabber script, but I would like to actually use the default models. How would I go about doing so?

## Unity Editor Version
2017.2.1f1
## Mixed Reality Toolkit Release Version
2017.2.1.3 Hot Fix

**Comment by datran-msft** [comment]
This issue is still present in MRTK 2017.4.0.0 with Unity 2017.4.8f1 and not just in the grabbable-demo.
The fallback models for the controllers are just cubes when they should be actual controllers models.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
