### ISSUE TITLE
How to use the Build Window?

### ISSUE THREAD

**Issue by dtb49** [Microsoft/MixedRealityToolkit-Unity#1925]
This feels sort of like a really dumb question but, for some reason I just can't figure out how to use the build window. I have my device connected to USB, which is how I normally build my projects through VS. Whenever I go to install it I just get the following error.

**Failed to start deployment. Install failed. Please contact your software vendor.**

Why is this error happening?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
