### ISSUE TITLE
 BuildAndDeploy\HoloToolkitCommands.cs removed in Dev_Working_Branch?

### ISSUE THREAD

**Issue by alankemp** [Microsoft/MixedRealityToolkit-Unity#1926]
BuildAndDeploy\HoloToolkitCommands.cs, which contained a function to trigger a command line build, seems to have been removed in Dev_Working_Branch.  Is this intentional?

The [HoloLens Unity Build](https://marketplace.visualstudio.com/items?itemName=davesmits.hololens-unity-build) task published on the VSTS marketplace calls this function, so this has broken our build pipeline.

**Comment by StephenHodgson** [comment]
I'll be updating the build deployment tool again so I'll be sure to address this in #1904

**Comment by StephenHodgson** [comment]
See https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1904#comment-378315208

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
