### ISSUE TITLE
Keyboard Input field Backspace/Cursor position incorrect

### ISSUE THREAD

**Issue by sethkrantzler** [Microsoft/MixedRealityToolkit-Unity#1927]
## Overview
When using the Keyboard input field included in HoloToolKit, the input behavior of backspace is not what would be expected. For example, if you have the word "example" entered in the input field and backspace the entire word, you will be left with an empty placeholder text above the keyboard in the keyboard's built in input field , but the scene's input field that the keyboard is targeting will have "e" and not be empty as expected. Clicking enter on the keyboard closes the keyboard, "e" remains in the scene's input field. Clicking again on the scene's input field to open the keyboard opens a keyboard with "e" in the keyboard's built in input field, you can repeat this process from here and never make the scene input field empty.
## Expected Behavior
When backspacing an entire input fields value using the keyboard input field script, the targeted input field should be empty, matching the keyboards input field value.
## Actual Behavior
The targeted input field has a remaining character that is undeletable.
## Steps to reproduce
1. Add a Keyboard Input Field script to an input field
2. Click on the input field and enter a phrase
3. Delete the entire phrase

![screenshot 40](https://user-images.githubusercontent.com/16142625/38513437-1a250bca-3be3-11e8-8d3d-818bce2b2bad.png)
![screenshot 41](https://user-images.githubusercontent.com/16142625/38513438-1a3907d8-3be3-11e8-9a6f-b19eacc77c28.png)
![screenshot 46](https://user-images.githubusercontent.com/16142625/38513439-1a4f0d6c-3be3-11e8-9bfb-13387210004b.png)
![screenshot 47](https://user-images.githubusercontent.com/16142625/38513440-1a6851dc-3be3-11e8-92ab-840dc8560cc5.png)

## Unity Editor Version
2017.3.1f1
## Mixed Reality Toolkit Release Version
2017.2.1.3

**Comment by keveleigh** [comment]
Related to #917

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
