### ISSUE TITLE
License(s) clobbered incorrectly without permission

### ISSUE THREAD

**Issue by riverar** [Microsoft/MixedRealityToolkit-Unity#1931]
@keveleigh incorrectly changed copyright headers across the entire project. Reminder: The CLA does NOT grant Microsoft copyright of submitted code, just a license to use said code in a million ways.

I was not contacted about transferring copyright.

Recommend changing attribution to reflect original owners (reformatting is fine) and reviewing all changes related to this "reformatting license headers" PR to ensure copyright is correctly maintained.

https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1479/commits/b18ec51178f536734b68601247dea3c879d51451#diff-167e05932e42623403cee00f057f0fe1

cc: @StephenHodgson @davidkline-ms

**Comment by StephenHodgson** [comment]
@riverar sorry about that, didn't get caught during the review.

**Comment by davidkline-ms** [comment]
Added to 2017.2.1.4 (April 2018) release

**Comment by davidkline-ms** [comment]
On a quick visual inspection, I identified BuildDeployWindow.cs and XdeGuestLocator.cs as having been changed. Is this correct? Did I miss any?

**Comment by riverar** [comment]
In the case of altered attribution, you're correct. In the case of attribution added to no-attribution files, things are a little murkier. We'll have to go to the original file, see who checked it in, and verify none of those files root back to a public submission.

**Comment by davidkline-ms** [comment]
From MRTK's license.txt (bolding is me, to highlight the lines of interest).

**Copyright (c) 2017 Microsoft Corporation**

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

**The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.**

**Comment by davidkline-ms** [comment]
I am not attempting to interpret what was said above, just pointing it out. I am working to make sure we are doing the right thing in MRTK.

**Comment by davidkline-ms** [comment]
As mentioned above, I am working to ensure we are doing the right thing in MRTK. I will update this when I have more data.
