### ISSUE TITLE
[vNext] Investigate integrating WindowsDevicePortalWrapper

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#1933]
Investigate what it would take to replace the MRTK Windows Device Portal code with a reference to the Windows Device Portal Wrapper project's NuGet package.

**Comment by StephenHodgson** [comment]
I've considered doing this, but I don't want to take another dependency.  Besides the REST client I made for the updated build tools is more than capable at handling this, with minimal code changes.

**Comment by StephenHodgson** [comment]
Well, as it stands there _aren't_ any bugs with the device portal.
