### ISSUE TITLE
Enable Shared Depth Buffer in ProjectSettingsWindow (V2)

### ISSUE THREAD

**Issue by Jarodshow** [microsoft/MixedRealityToolkit-Unity#1939]
## Overview
Maybe we should enable depth buffer sharing by default with `Enable XR`? Obviously only supported in 2017.3.1f1 and later.

**Comment by StephenHodgson** [comment]
Possible duplicate.

The shared depth buffer only works with the immersive headsets and the RS 4 OS on the HoloLens, so this a bit tricky to implement without breaking compatibility for those that are still using the older os on the HoloLens.

**Comment by Jarodshow** [comment]
Perhaps it could be a prompt afterwards noting that it only works on RS4 and IHMD?

**Comment by Troy-Ferrell** [comment]
Unity, starting around roughly Unity 2018 LTS, has by default for new projects Depth Buffer sharing enabled. The problem with an automatic "Apply scene settings" or simple prompt is that some developers do not like MRTK being that intrusive especially under the covers in their project. The PR #5199 is an attempt to provide a tool to make these configurations easy to set but also informative
