### ISSUE TITLE
Unable to build project to Hololens

### ISSUE THREAD

**Issue by StarWardo** [Microsoft/MixedRealityToolkit-Unity#1941]
## Overview

I am unable to build my unity project to my Hololens.

Error in VS:  The command [...] exited with code 1

## Steps to reproduce

-Create new project
-Switch platform to UWP
-Import MRT
-Set project settings
-Set scene settings
-UWP capabilities, mic , spatial , camera
-Add a random Cube

-File -> build window -> build
-Open in VS -> x86 -> device -> start with debugging 
-Hololens is connected by USB

## Unity Editor Version

Unity2017.2.1f1

## Mixed Reality Toolkit Release Version

HoloToolkit-Unity-2017.2.1.3

## Windows 10 SDK version Version

SDK 10.0.16299.0

## Visual studio version

2017 15.6.2

## Windows 10 version

1709 (16299.371)

**Comment by samharper94** [comment]
Have you been able to build to the HoloLens before?

**Comment by ronneke1996** [comment]
Have you tried moving the Unity build to another drive? I had a similar problem where I could not build my project to the Hololens. After moving to an other drive it worked flawlessly. At my end the builder was truncating some paths and could not find some dll because of that.

**Comment by davidkline-ms** [comment]
@samharper94,
Can you post details from the output window? There are some path length issues with some of the tools used when building Unity projects. You may be running into one of those (which may explain @ronneke1996's 'move to another drive' solution).

**Comment by StarWardo** [comment]
I moved the hole project to a folder closer to my drives root folder and it fixed the problem.
My previews folder had a path of 99 character and no special character. (I like folders)

Thanks for your help.
