### ISSUE TITLE
SphereBasedTagAlong behind other objects

### ISSUE THREAD

**Issue by ronneke1996** [Microsoft/MixedRealityToolkit-Unity#1945]
## Overview
I use SphereBasedTagAlong to have some button follow the users gaze. But I cannot specify that the buttons should be placed in front of everything like I can do with the standard TagAlong component. 
 
## Expected Behavior
A combo of SphereBasedTagAlong and TagAlong where I can have a SphereBasedTagAlong with minimum and maximum distance and placing infront of everything.

## Actual Behavior
SphereBasedTagAlong and TagAlong do not work well together. And If I use only SphereBasedTagAlong the buttons will fall behind other objects.

## Steps to reproduce
Create MixedRealityToolkit button and add SphereBasedTagAlong

## Unity Editor Version
2017.3.1p1

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-2017.2.1.3

**Comment by StephenHodgson** [comment]
They're mutually exclusive.  Probably shouldn't use both together.

**Comment by StephenHodgson** [comment]
To use the sphere based tagalong it essentially just makes sure a position is valid within a sphere radius from it's own transform position.

I think there's a setup phase in the sphere based tagalong when it gets enabled that it references that point then does what it needs to stay inside that sphere.

You'll need to make sure the initial position of the sphere based tagalong is where you expect it to be when the object gets enabled.

**Comment by ronneke1996** [comment]
I can understand that but wouldn't it be nice of a spherebasedtagalong to also have a minimum and maximum distance and having the ability to be infront of other objects (like spatial mapping) because now my buttons will clip through walls. The principle should be the same as the Hololens "bloom" menu. That tags along in a kinda sphere like and will bring it self infront of other objects

**Comment by StephenHodgson** [comment]
I agree that would be nice to have.

You're more than welcome to contribute and add the physics needed for this sort of system if you're up to the challenge.

**Comment by ronneke1996** [comment]
Well for the time being I have "solved" the issue by enlarging the boxcollider of my parent of the button that tagsalong. And then I increased the minimum horizontal/vertical overlap. This simulates the sphere based tagalong. If I have the time I'll try to give it a try to implement this feature, but as I'm graduating at the moment time is limited.

**Comment by cre8ivepark** [comment]
@ronneke1996 Have you tried Solver system?
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Patch4_Dev/Assets/HoloToolkit-Examples/Utilities/Readme/README_SolverSystem.md

https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Patch4_Dev/Assets/HoloToolkit-Examples/Utilities/Scenes/SolverExamples.unity

**Comment by davidkline-ms** [comment]
Thanks for the tip @cre8ivepark! I've been looking at something similar to @ronneke1996 myself :)
