### ISSUE TITLE
Add "Create Unity C# Projects" option to Project Config dialog

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#1948]
I love being able to set the project build settings with "one click" using the Apply Project Settings option. There is one setting, however that I **always** have to go to Unity's build dialog for: "Unity C# Projects".

It would be nice to not have to do that step manually. In fact, the same is true for devs who use the "Development Build" option.

**Comment by StephenHodgson** [comment]
The build window has it.
![image](https://user-images.githubusercontent.com/13334553/38696115-0d566bca-3e43-11e8-886b-1fd8d5e9eda8.png)

**Comment by davidkline-ms** [comment]
I must be blind today :)
