### ISSUE TITLE
Help: Hololens Build Fail On Unity 2017.4.1.f3 with Toolkit 2.1.4

### ISSUE THREAD

**Issue by gabylee** [Microsoft/MixedRealityToolkit-Unity#1950]
Assertion failed: Assertion failed on expression: 'FALSE != acquireNewContextResult'
UnityEditor.EditorUtility:WSACreateTestCertificate(String, String, String, Boolean)
PostProcessWinRT:CreateTestCertificate() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:875)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:164)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Assertion failed: Failed to open Assets\WSATestCertificate.pfx
UnityEditor.WSA:SetCertificate(String, String)
PostProcessWinRT:CreateTestCertificate() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:880)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:164)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

FileNotFoundException: Assets\WSATestCertificate.pfx does not exist
System.IO.File.Copy (System.String sourceFileName, System.String destFileName, Boolean overwrite) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/File.cs:107)
System.IO.File.Copy (System.String sourceFileName, System.String destFileName) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/File.cs:86)
PostProcessWinRT.CopyTestCertificate () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1179)
PostProcessWinRT.Process () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:177)
UnityEditor.WSA.BuildPostprocessor.DoPostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:117)

UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x0020e] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:181 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00065] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:88 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by samharper94** [comment]
What SDK are you using?

**Comment by SimonDarksideJ** [comment]
This line seems odd, that file is autogenerated by Unity when you select the UWP platform

> FileNotFoundException: Assets\WSATestCertificate.pfx does not exist

**Comment by davidkline-ms** [comment]
I have not been seeing this on unity 2017.4.1f1 (I am not aware of an f3) with either rc or rc2

**Comment by gabylee** [comment]
Thanks All,I Fixed  By Renew my window10 SDK on visual studio 2017
