### ISSUE TITLE
Can not open the MixedRealityToolkit-Unity

### ISSUE THREAD

**Issue by toriop** [Microsoft/MixedRealityToolkit-Unity#1952]
when I cloned the whole project to my computer,and open it,
it always has error like this:
![image](https://user-images.githubusercontent.com/37078704/38736527-9f3879cc-3f2c-11e8-9896-9d749af0f53b.png)
is thre anybody know what can I do to solve this problem?

**Expected Behavior**
use MixedRealityToolkit-Unity

**Actual Behavior**

Cannot use MixedRealityToolkit-Unity

**Unity Editor Version**
Unity 2017.4.1f1 (64-bit)

**Mixed Reality Toolkit Release Version**
lasted one

In fact, I have opened it one week ago;but I don't know why there is problem now.

**Comment by SimonDarksideJ** [comment]
Have you tried the downloadable asset from a new Project?
The JSON error is a Unity one, since Unity changed to their new nuget style package manager.
P.S. you should either use 2017.2, or 2017.4 (unity have deprecated the 2017.3 release in favour of the 2017.4 rename :D)

**Comment by toriop** [comment]
yes, now I change to Unity 2017.4.1f1 (64-bit), and use "HoloToolkit-Unity-2017.2.1.4-rc.unitypackage".
But there is still the same problem......

![image](https://user-images.githubusercontent.com/37078704/38741282-e824f05e-3f39-11e8-87d2-d3556e5401d9.png)

**Comment by keveleigh** [comment]
I've seen that related to the GLTFSerialization DLL, but that message shouldn't stop anything from building or running. Can you not build?

**Comment by keveleigh** [comment]
And here's a corresponding issue on their side: https://github.com/KhronosGroup/UnityGLTF/issues/161

**Comment by toriop** [comment]
ok, you are right, altough with the error, it don't stop anything from building or running. 👍 

Thank you so much!
