### ISSUE TITLE
MotionControllerVisualizer crashing Unity Editor

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#1955]
## Overview
After running from the editor a few times, I get the error below which crashes the Unity Editor

## Expected Behavior
No crashing

## Actual Behavior
Crashing with the following error message:

RegisterRuntimeInitializeAndCleanup::Register has reached the limit 700 MaxLimit 700 UnityEngine.XR.WSA.Input.InteractionManager:.cctor()
MixedRealityToolkit.InputModule.Utilities.MotionControllerVisualizer:Awake() (at Assets/MixedRealityToolkit/InputModule/Scripts/Utilities/MotionControllerVisualizer.cs:79)

Posted error to Unity as well in case it is their problem: 
https://fogbugz.unity3d.com/default.asp?1025976_n73rnadi17lval9v

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2017.4.1f1

## Mixed Reality Toolkit Release Version
Dev_Working_Branch but a week or two back, I'll update to latest to see if it still happens

**Comment by provencher** [comment]
![image](https://user-images.githubusercontent.com/7420990/41793170-409d0c3c-7629-11e8-9997-cef417632cad.png)

This just happened to me without using the MRTK.

**Comment by provencher** [comment]
https://issuetracker.unity3d.com/issues/fatal-error-referring-registerruntimeinitializeandcleanup-is-thrown-after-playing-a-scene-multiple-times-in-2017-dot-4

**Comment by flufy3d** [comment]
I have the same problem with 2017.4

**Comment by StephenHodgson** [comment]
Unity says this issue is closed.  Try updating to a newer version of Unity.
