### ISSUE TITLE
Activating HandDraggable and TapToPlace by script not working

### ISSUE THREAD

**Issue by Silloty1** [Microsoft/MixedRealityToolkit-Unity#1957]
## Overview
Setting up TapToPlace and HandDraggable scripts on one game object. Adding a button and script to enable/disable script

## Expected Behavior
When clicking on the button, activating HandDraggable to be able to drag and drop the hologram, when re-clicking on it, desactivating HanDraggable for TapToPlace, to be able to place the hologram on SpatialMapping

## Actual Behavior
At the begining, the HandDraggable script is working well, I can drag the asset everywhere I want. Then, i'm activating TapToPlace script, I can put it wherever I want. But when I want to activate HandDraggable again, it doesn't drag anymore. After clicking another time on the button to reactivate TapToPlace, this one is working

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
Unity 2017.2.1f1

## Mixed Reality Toolkit Release Version
2017.2.1.0

**Comment by keveleigh** [comment]
Ahh yes, by-design, and object with a world anchor cannot be moved until it's removed.
