### ISSUE TITLE
Duplication of Holotoolkit camera when switching scenes

### ISSUE THREAD

**Issue by Mustellinus** [Microsoft/MixedRealityToolkit-Unity#1961]
When switching to a scene that already includes a mixed reality camera, the camera is duplicated. Solution included.

## Steps to reproduce
-create two scenes, each with a mixed reality camera.
-run the application in the unity editor
-go to second scene
-messages 

## Solution- The code in the Awake() method of the Singleton class destroys the script but not the object to which it is attached. I corrected the problem with the following code.

```
protected virtual void Awake()
        {
            if (IsInitialized && instance != this)
            {
                if (Application.isEditor)
                {
                   //DestroyImmediate(this);replaced
                    DestroyImmediate(gameObject);
                }
                else
                {
                   // Destroy(this);replaced
                    Destroy(gameObject);
                }

                Debug.LogErrorFormat("Trying to instantiate a second instance of singleton class {0}. Additional Instance was destroyed", GetType().Name);
            }
```
If there is a better solution, let me know.

**Comment by StephenHodgson** [comment]
> create two scenes, each with a mixed reality camera.

Well there's your problem. The expected workflow requires a main master scene and additive loading of your additional scenes.

If you don't like that workflow, then you can _optionally_ disable don't destroy on load, but it's not recommended.

**Comment by Mustellinus** [comment]
Ok, I have a main scene. Additive load of additional scenes solved the problem
