### ISSUE TITLE
[Patch4] Immersive device: NullReferenceException in FocusManager.TryGetFocusedObject

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#1964]
GetSpecificPointerEventData() returns null, which is dereferenced by TryGetFocusedObject

## Steps to reproduce
* build / deploy bounding box example scene to immersive device
* press the select/trigger button on the motion controller

## Unity Editor Version
2017.4.1f1

## Mixed Reality Toolkit Release Version
2017.2.1.4-rc2

**Comment by jerrygg** [comment]
Me too.
Unity Editor Version
2017.3.1p2 
Mixed Reality Toolkit Release Version
Dev_Working_Branch
