### ISSUE TITLE
Clients dont get  shared anchor...

### ISSUE THREAD

**Issue by SorenMuller** [Microsoft/MixedRealityToolkit-Unity#1965]
I'm trying to get the MixedReality250  to work with multiple holo lenses.

I'm using Unity 2018, a few minor updates and it runs without errors.. 

The hololens acting as server works fine.
But when I try to join that, I get an nullreference exeption at the HERE location,
since AnchorStore is null..
This results in no shared anchor...

Hope someone can help..

UNetAnchorManager.cs : 
```
private bool AttachToCachedAnchor(string CachedAnchorName)
{
           if (string.IsNullOrEmpty(CachedAnchorName))
            {
                Debug.Log("Ignoring empty name");
                return false;
            }
#if UNITY_WSA
            UnityEngine.XR.WSA.Persistence.WorldAnchorStore anchorStore = WorldAnchorManager.Instance.AnchorStore;

            string[] ids = anchorStore.GetAllIds();   <== HERE



            for (int index = 0; index < ids.Length; index++)
            {
                if (ids[index] == CachedAnchorName)
                {
                    Debug.Log("Using what we have");
                    anchorStore.Load(ids[index], objectToAnchor);
```

Regards
Søren Müller

## Unity Editor Version
2018.1.0b13

## Mixed Reality Toolkit Release Version
Latests..

**Comment by isurfraz** [comment]
any update on this issue? was there a resolution for it?

**Comment by StephenHodgson** [comment]
Where is the code that waits until the anchor store is valid?

**Comment by isurfraz** [comment]
@StephenHodgson was that question to me?

**Comment by StephenHodgson** [comment]
Whomever is having the problem.

**Comment by StephenHodgson** [comment]
I don't think there's been an update, sorry.

**Comment by isurfraz** [comment]
@StephenHodgson ok, thanks very much for the quick reply!

**Comment by keveleigh** [comment]
@isurfraz Are you using the version of the script from the latest Toolkit release (2017.4.1.0) or the one distributed with MR250? The original issue mentions MR250.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
