### ISSUE TITLE
Bounding Box Rotating Opposite Direction of Input Motion

### ISSUE THREAD

**Issue by davidlieberman** [Microsoft/MixedRealityToolkit-Unity#1968]
## Overview
When I move my hand to the left along either the X or Y axis, the object rotates to the right. Z axis works properly. I am using the included BoundingBoxExample.unity demo scene. I do not have this problem when using the MRDL bounding box.

## Unity Editor Version
Unity 2017.2.0

## Mixed Reality Toolkit Release Version
Dev_Working_Branch

**Comment by StephenHodgson** [comment]
We can probably add a bool to let devs decide which direction they want it to go. This is more of a preference than a bug.

**Comment by davidlieberman** [comment]
I agree. Just thought I'd give you guys a heads-up since it goes in the opposite direction of what's shown in the demo video, and in my opinion, having the object move in the opposite direction of the gesture is somewhat unintuitive. A bool for along/against the axis of gesture would be appreciated.

**Comment by keveleigh** [comment]
@davidlieberman Does this repro in the June or master branches? Using the scene you mentioned, the bounding boxes rotate as expected for me.

**Comment by davidlieberman** [comment]
@keveleigh It's working now for me as well. Thanks guys!
