### ISSUE TITLE
Disabled BoxCollider in button prefab

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#1969]
## Overview
In button prefab there is a disabled BoxCollider (Button GameObject child of ButtonOutline).
What does it do? Is it possible to safely remove it?

## Unity Editor Version
2017.4.1f1
## Mixed Reality Toolkit Release Version
2017.2.1.4 Release Candidate 2

**Comment by davidkline-ms** [comment]
There are actually two colliders in this prefab that are not enabled on the following:
1. ButtonOutline
2. ButtonOutline > Button

When running in Play mode, neither of these become enabled. Investigating whether or not there are any side effects of removing one or both of them.

**Comment by davidkline-ms** [comment]
On the surface, it appears that removing the unused colliders does not present a negative effect

**Comment by davidkline-ms** [comment]
The button referenced here appears to be Button.prefab from the HoloToolkit-Examples\UX\Prefabs folder.

Looking at the button prefabs in the HoloToolkit\UX\Prefabs\Buttons folder, there arent any disabled colliders. I will remove them from the Examples folder prefab.

**Comment by davidkline-ms** [comment]
Same looks to be true for ToggleButton as well

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
