### ISSUE TITLE
Caret not showing on MRT Keyboard Input Field

### ISSUE THREAD

**Issue by Vangaorth** [Microsoft/MixedRealityToolkit-Unity#1978]
## Overview
The 'KeyboardTest' scene inside any Examples package has everything already set up. Otherwise, create a new scene with MixedRealityCameraParent prefab, DefaultCursor, Input Manager prefab, MixedRealityToolkit Keyboard prefab, a main canvas with a child InputField which script has been replaced by a KeyboardInputField component and which 'text' property has been filled with some short single line text.

## Expected Behavior
On Hololens, when I click/tap on the GameObject containing the KeyboardInputField, the MixedRealityToolkit keyboard appears and the caret on the inputfield of the keyboard should be visible and blanking.

## Actual Behavior
The MixedRealityToolkit keyboard appears but the caret of the kayboard input field does not (on Hololens).

## Steps to reproduce
Uuse [this repo](https://github.com/Vangaorth/HolotoolkitCaretIssue)

Otherwise, create a new project, switch to Universal Windows Platform, create a new scene, import an MixedRealityToolkit >= 2017.2.1.0, import the relative 'Example' unity package (found on the releases page), open the KeyboardTest scene, search for the email input field and fill the 'text' property of its 'KeyboardInputField' with some short text (e.g., an email address),  from MixedRealityToolkit menu, select Configure -> Apply MR Project Settings -> Apply, add the scene to the built scenes, build and deploy. On Hololens, tap the GameObject containing the KeyboardInputField.

## Unity Editor Version
2017.2.1p2

## Mixed Reality Toolkit Release Version
2017.2.1.4 Release Candidate 2 but the problem is in every MRT version starting from MixedRealityToolkit for Unity 2017.2.1f1 (included). MixedRealityToolkit for Unity 2017.2.0p1 MRTP4 and previous are not affected by this problem.

**Comment by davidkline-ms** [comment]
Re-enabling the caret causes issue #1940 to repro. I am investigating a fix/workaround to that issue that will accompany the restoration of the caret.

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
