### ISSUE TITLE
Cannot erase all content of KeyboardInputField which ContentType is set to password

### ISSUE THREAD

**Issue by Vangaorth** [Microsoft/MixedRealityToolkit-Unity#1979]
## Overview
The 'KeyboardTest' scene inside any Examples package has everything already set up, you just have to switch the "ContentType" of one of its KeyboardInputField to 'Password' . Otherwise, create a new scene with MixedRealityCameraParent prefab, DefaultCursor, Input Manager prefab, MixedRealityToolkit Keyboard prefab, a main canvas with a child InputField which script has been replaced by a KeyboardInputField component, which 'text' property has been filled with some short single line text and which 'ContentType' property has been set to 'Password'.

## Expected Behavior
When deleting the text of an KeyboardInputField with the 'ContentType' set to 'Password', using the MRT Keyboard, every character in the KeyboardInputField should be erasable until the placeholder appears (please note that the problem affects the KeyboardInputField, not the InputField of the MRT Keyboard).

## Actual Behavior
Even if the InputField of the MRT Keyboard can erase all of its textual content, the KeyboardInputField always leaves one character, preventing the placeholder to appear.

## Steps to reproduce
Use [this repo](https://github.com/Vangaorth/MRTPasswordIssue.git)

Otherwise, create a new project, switch to Universal Windows Platform, create a new scene, import an MixedRealityToolkit >= 2017.2.1.0, import the relative 'Example' unity package (found on the releases page), open the KeyboardTest scene, search for the email input field, fill the 'text' property of its 'KeyboardInputField' with some short text and set its 'ContentType' property to 'Password'. From MixedRealityToolkit menu, select Configure -> Apply MR Project Settings -> Apply, add the scene to the built scenes, build and deploy. On Hololens, tap the GameObject containing the KeyboardInputField and delete every single character until the InputField of the MRT Keyboard is empty (but the KeyboardInputField is not).

## Unity Editor Version
2017.2.1p2

## Mixed Reality Toolkit Release Version
2017.2.1.4 Release Candidate 2 but the problem is in every MRT version starting from MixedRealityToolkit for Unity 2017.2.1f1 (included).

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
