### ISSUE TITLE
Cursor.prefab is missing the point light off holograms

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#1983]
## Overview
In Cursor.prefab, the CursorOffHolograms component used to be a point light. In the process of adding the new hover light (to work with the new Toolkit Standard shader), this light was incorrectly removed.

Additionally, in the port to master, the hover light was incorrectly added to CursorOffHolograms instead of CursorOnHolograms.

## Expected Behavior
[All] When I'm not looking at a hologram using Cursor.prefab, I should see a floating point light.
[master] When I'm looking at a hologram using Cursor.prefab and the Toolkit Standard shader, I should see a light around my cursor.

## Actual Behavior
[All] Nothing is displayed when looking away from holograms.
[master] The hover light does not work.

## Steps to reproduce
1. Create a scene with Cursor.prefab and an object using the Toolkit's Standard shader.
2. Look at the object.
3. Look away from the object.

## Mixed Reality Toolkit Release Version
2017.2.1.4 and latest dev

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
