### ISSUE TITLE
Spatial Interaction Controller not available on RS4 - TapToPlace scene

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#1992]
[Copied from MixedRealityToolkit, courtesy of @ooeygui]

Repro steps:  

1. Install Insider build of RS4 on a HoloLens, enable developer mode, pair to VS
2. Create a new unity project, and import the MRTK & examples
3. Add the TapToPlace sample scene
4. Ensure appropriate capabilities are set
5. Build and deploy to the HoloLens

Observe: 

Failed to get spatial interaction controller - touchpad, thumbstick, and vendor data will be unavailable to the application for InteractionController! Error code: '0x00000000'. Unable to tap to move the cubes around the scene.

**Comment by StephenHodgson** [comment]
This is a unity bug.  It's easily fixed by using the latest Unity 2017.4.1f1 release.

**Comment by ooeygui** [comment]
Thank you; testing now.

**Comment by davidkline-ms** [comment]
Confirmed this appears to be a unity 2017.2 issue. was able to repro in 2017.2.1p2 and not in 2017.4.2f2
