### ISSUE TITLE
Cannot change TwoHandManipulatable.ManipulationMode at runtime.

### ISSUE THREAD

**Issue by satoshi-maemoto** [Microsoft/MixedRealityToolkit-Unity#1994]
## Overview
Cannot change TwoHandManipulatable.ManipulationMode at runtime.
because TwoHandManipulatable.SetManipulationMode(TwoHandedManipulation mode) is private.
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/84493c975fbf0fe0f3541303ce1758ca11dfe44a/Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/TwoHandManipulatable.cs#L135

I think should set public this method and TwoHandedManipulation enumration.

## Unity Editor Version
Unity 2017.2.1p1+

## Mixed Reality Toolkit Release Version
2017.2.1.4 Patch Release

**Comment by cre8ivepark** [comment]
I agree. I think SetManipulationMode should be public since many app scenarios would want to change the mode in real-time(through a menu or voice)
FYI, supported manipulation mode:
- Scale
- Rotate
- Move, Scale
- Rotate, Scale
- Move, Rotate, Scale

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
