### ISSUE TITLE
Add events to listen when a BoundingBoxRig is either activated or deactivated

### ISSUE THREAD

**Issue by rigma** [Microsoft/MixedRealityToolkit-Unity#2004]
## Overview

On a project using MRTK where I am currently involved, I need to know when a bounding box rig is either activated or deactivated by the user.

To do so, I would like to add and use events, which are owned by the bounding box rig, that will be used to track the state of a rig.

## Proposed Behavior

When a bounding box rig is activated, a `BoundingBoxRig.Activated` event is fired.
When a bounding box rig is deactivated, a `BoundingBoxRig.Deactivated` event is fired.

**Comment by davidkline-ms** [comment]
@rigma, Feel free to code up your proposal and submit a pull request. We love contributions!

**Comment by rigma** [comment]
I am doing it right now!
