### ISSUE TITLE
Building error with windows.devices.haptics when using latest version of holotoolkit with Unity 2017.3.1f1

### ISSUE THREAD

**Issue by StefanNeu** [Microsoft/MixedRealityToolkit-Unity#2012]
## Overview
Hey guys,

right now I am working on a really simple MR-App with the HoloLens and therefore I wanted to use the HoloToolkit.
Right now I am using the latest version of the HoloToolkit with Unity 2017.3.1f1 and the Windows SDK has the version number 16299.371.

My only problem right now is that I get this building error when trying to build a visual studio solution:

`Assets\HoloToolkit\Common\Scripts\Extensions\InteractionSourceExtensions.cs(13,23): error CS0234: The type or namespace name 'Haptics' does not exist in the namespace 'Windows.Devices' (are you missing an assembly reference?)`

I already tried some suggested solutions from other closed issues here on git, but it still doesn't really work. Can somebody help please?

Thank you:)

**Comment by StephenHodgson** [comment]
Sounds like we need to have the API checker class make sure the api contract is availible.

**Comment by keveleigh** [comment]
I'm unable to repro this, using Unity 2017.3.1f1 and 16299.15. Looking for 16299.371 now, but it'd be weird if that namespace was removed between those. I was able to build for both .NET and IL2CPP. Are there any other configuration details you have that might help me repro?

**Comment by StefanNeu** [comment]
Sorry, for that late answer.. The only other configuration details that could be problematic are that I used Visual Studio 2015 and another strange thing about Unity: When I want to change the Windows SDK, I only get to choose between "Latest installed" and something like Version 10.14... (I'm not at the PC that I got the error with, so I can't really remember the exact version). 
Is there a known bug with Unity not using the latest installed SDK?

**Comment by StephenHodgson** [comment]
You're definitely going to need to build with the latest version of visual studio.

I'd also check to make sure you didn't install the SDK in a custom location.
