### ISSUE TITLE
HolographicButton throws "Animator is not playing an AnimatorController"

### ISSUE THREAD

**Issue by GiMaWolf** [Microsoft/MixedRealityToolkit-Unity#2019]
## Overview
If one opens a Unity project, imports Toolkit and drags HolographicButton into the hierarchy the warning "Animator is not playing an AnimatorController" ist thrown. How can this warning be fixed?

## Expected Behavior
The button works and throws no warnings.

## Actual Behavior
there is a warning.

## Steps to reproduce
see Overview

## Unity Editor Version
2017.4.0f1

## Mixed Reality Toolkit Release Version
2017.2.1.4

How can this warning be fixed?

**Comment by mrsniperz** [comment]
![default](https://user-images.githubusercontent.com/35944209/39340445-cc07249c-4a00-11e8-84af-c3a843688917.PNG)
You can check the button's animation is there any missing animation,if it has just remake it.

**Comment by cre8ivepark** [comment]
@GiMaWolf Thanks for opening this issue! I have removed text & icon animation but it seems like AnimationController was not removed properly. I'll apply the updated prefab to may18 release.

**Comment by davidkline-ms** [comment]
@cre8ivepark, Do you have this ready for PR?

**Comment by cre8ivepark** [comment]
@davidkline-ms I'll submit the PR tomorrow!

**Comment by cre8ivepark** [comment]
Submitted PR for master and Dev

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
