### ISSUE TITLE
Shared Experience through open internet: What kind of information is transmitted? 

### ISSUE THREAD

**Issue by selinsepin** [Microsoft/MixedRealityToolkit-Unity#2022]
## Overview
We want to have a shared experience that we can connect from anywhere in the world. As far as I understood this functionality works with executing an exe file to start a server on the PC. 

In our application, there are CAD models that are restricted. 

So my question is, what exactly is uploaded to the servers for sharing? Can we track what is transmitted? Does it include any information about CAD model? Or just the transforms of the objects are shared?

Is it possible to use another server possibility or cloud services and still use shared libraries from MixedRealityToolkit?

## Expected Behavior
No restricted CAD related data would be shared. Only the transforms of the objects are shared.
## Actual Behavior
Unknown
## Steps to reproduce
-

## Unity Editor Version
latest Unity version that supports UWP development
## Mixed Reality Toolkit Release Version
latest

**Comment by camnewnham** [comment]
@selinsepin The information that gets shared is up to you and/or your developers. Anchor sharing is not necessary for sharing with remote users as this is only used locate holograms in local space.

It would be possible to have both(all) clients launch an app which already contains the CAD data, and hence not transmit any CAD data over the internet. In which case presumably the only data you'd be wanting to share is the users locations relative to the model, their audio streams, and potentially any interactions etc.
