### ISSUE TITLE
Build window - add "Unity C# Projects" and "Development Build" options

### ISSUE THREAD

**Issue by Waterine** [Microsoft/MixedRealityToolkit-Unity#203]

**Comment by riverar** [comment]
Can you provide more detail as to what you're looking for?

**Comment by Waterine** [comment]
Sorry for not being clear... these refer to the existing options in Unity build settings (Ctrl+Shift+B) for WSA apps. "Unity C# projects" is especially useful to include Assembly-CSharp project in the generated SLN, which is the only place I have intellisense for code wrapped in NETFX_CORE/WINDOWS_UWP defines.

**Comment by jwittner** [comment]
Hmmm, I think it makes sense to mirror some of the build options from the Unity Build settings window in the HTK Build window. For HTK users the Build Window effectively replaces the Unity one.

**Comment by jwittner** [comment]
@Waterine think you'll do this work?

**Comment by HodgsonSDAS** [comment]
@Waterine has this been fixed for you?

**Comment by Waterine** [comment]
I won't be able to verify because I don't work on Hololens anymore.
