### ISSUE TITLE
Structuring and extending the MRTK UNET components and example

### ISSUE THREAD

**Issue by FejZa** [Microsoft/MixedRealityToolkit-Unity#2032]
## Overview
The current "SharingWithUNET" example is basically everything there is concerning UNET. I've been using UNET for all my shared experiences on HoloLens and WMR devices and think there is a lot of potential for reusable components and better documentation here.

The current example contains components / code that can be made reusable and useful for any UNET based project. I'd suggest creating a "SharingWithUNET" folder in the MRTK, analog to the current "Sharing" folder. Refactor the example and move components not specific to the example itself into the new MRTK UNET folder.

## Why is this useful?
- Developers who chose to use UNET get a headstart using MRTK prefabs and components for UNET
- The example becomes more lightweight
- These changes provide a base for futher UNET contributions. I have a lot of code / components from past projects I'd like to get into the MRTK that help with UNET. But right now, I just don't know where to start and where to add them.
- The current UNET code / components are not well structured and really hard to separate into logic pieces. This is a chance to refactor some of the code and have clear responsibilities.

**Comment by FejZa** [comment]
So is there any way to get involved or to know what the plans are?

**Comment by StephenHodgson** [comment]
https://github.com/Microsoft/MixedRealityToolkit-Unity/projects/5#card-9450839

**Comment by FejZa** [comment]
Thanks Stephen!

**Comment by HeadClot** [comment]
Hey - With unet being [deprecated](https://blogs.unity3d.com/2018/08/02/evolving-multiplayer-games-beyond-unet/). What is the plans for this issue going forward?

There is a Community maintained versions of unet below.

https://github.com/vis2k/Telepathy Low Level API
https://github.com/vis2k/Mirror/ High Level API

**Comment by StephenHodgson** [comment]
Likely not. We're looking at using webRTC or Photon for our new initial sharing offerings in vNEXT

**Comment by jwittner** [comment]
Deprecation has been delayed, and UNet will be moved to a package: https://forum.unity.com/threads/unet-deprecation-thread.543501/

New API, in Alpha, looks terribly unready: https://github.com/Unity-Technologies/multiplayer

**Comment by bengreenier** [comment]
Hey folks, a proposal for some webrtc work that could eventually morph into a larger solution (note: this is just my personal opinion) addressing the above can be found in #3590 - cross-linking for context.

**Comment by Yoyozilla** [comment]
Bulk closing older HTK bug. Please reopen if you can repro this issue in MRTK v2. 
Thanks!
Yoyo
