### ISSUE TITLE
PopupMenu: 'IsModal' and 'CloseOnNonTargetedTap' options don't work correctly

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#2040]
## Overview
'IsModal' and 'CloseOnNonTargetedTap' options of the 'PopupMenu' component don't work correctly
## Expected Behavior
The options should work
## Actual Behavior
The options don't work correctly in all the situations
## Steps to reproduce
InputManagerTest scene
IsModal:
Click the modal Popup button and then click the cylinder on the left
CloseOnNonTargetedTap:
Click the cylinder on the left (only if you remove the option 'CloseOnTargetedTap' the example works correctly).
## Unity Editor Version
2017.4.2f2
## Mixed Reality Toolkit Release Version
2017.2.1.4

**Comment by psytgm** [comment]
The situation of triggering twice with one click also occurred when scene switched between each other.

**Comment by keveleigh** [comment]
Ahh, so it looks like PopupMenu is only consuming `OnInputDown` and `OnInputUp` events, while the cylinder uses `OnInputClicked`. It doesn't make sense to me for PopupMenu to respond to those events over clicked (and it's responding identically to both, strangely). I'll put out an update and test these settings.

**Comment by keveleigh** [comment]
I just opened #2358 with a potential fix. Please take a look and let me know if something still doesn't work as expected.

**Comment by ivan2007** [comment]
Hi @keveleigh, I made some test with InputManagerTest scene:
1. When you open the modal window you are still able to move the movable objects (I don't know if this is outside the scope of PopupMenu).
2. The button actions of Shrink and Grow are set with reset.
3. If you place a CheckBoxSet inside the Popup window (IsModal is true) you can't change the state of the check boxes. The modal input stack of InputManager stop the event only if it is marked with used (see HandleEvent).
