### ISSUE TITLE
Unity 2018.1 support

### ISSUE THREAD

**Issue by monsdar** [Microsoft/MixedRealityToolkit-Unity#2044]
## Overview
Unity [just released](https://blogs.unity3d.com/2018/05/02/2018-1-is-now-available/) its first version of Unity 2018. Unfortunately I wasn't able to find much information on what is planned with MRTK compatibility to that release.
The [roadmap](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Roadmap.md) states that vNext will support 2018.1. Does this mean that the "traditional" (??) branch of MRTK will stop being supported after 2017.4?

It would be nice to get some clarification on what the upcoming plans are in that regards.

**Comment by monsdar** [comment]
Sorry for not submitting this issue in the usual format - it's not really a bug or a feature request. Perhaps an outcome of this could be some clarification in the Roadmap.md.

**Comment by pwroff** [comment]
Actively developing for 8 hours now. No issues noticed so far with MRTK and Unity 2018.

**Comment by monsdar** [comment]
May I ask on which branch and version you're developing? Last time I tried to use MRTK with 2018 I got some compiler issues. Currently installing Unity 2018.1 on my PC to test with the latest version.

**Comment by pwroff** [comment]
I'm developing on latest release.

**Comment by brean** [comment]
I am also using Unity 2018 (since its beta/since March) using Dev_Working_Branch without problems.

**Comment by monsdar** [comment]
In the meantime I was able to successfully run the May branch too. Got a NET Standard 2.0 compatible library running by using IL2CPP.

**Comment by davidkline-ms** [comment]
We currently have a PR (#2127) for the May branch with support for 2018.1. Should be merged in the next day or so.

Officially, the "HoloToolkit" releases will be focused on the Unity 2017.4 Long Term Support release, with vNext embracing future Unity releases.

**Comment by keveleigh** [comment]
"No build warnings" support for 2018.1 was included in the May release. Closing this issue, but please re-open (or open new issues) if you have any specific concerns.

**Comment by Madoka7** [comment]
Hi, I noticed that the latest Mixed Reality Tool Kit by Microsoft does not works well in the latest version of unity. Any comments on that? Thanks

**Comment by StephenHodgson** [comment]
> Hi, I noticed that the latest Mixed Reality Tool Kit by Microsoft does not works well in the latest version of unity. Any comments on that?

You're gonna have to be more specific on that to get a meaningful response.
