### ISSUE TITLE
[vNext] Refactor the SpectatorView feature

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#2049]
The new SpectatorView feature should be considered for a refactor in Version Next as it contains components that:
-  are platform specific (we should consider moving them into the Device layer)
- networking /sharing (we should consider moving into the sharing component)
- feature code (should remain in the SpectatorView folder and namespace)

Care will be required to ensure we do not add undo cross component dependencies and/or complexity.

**Comment by chrisfromwork** [comment]
Moving forward this likely won't be the correct repo for tracking spectator view work. Please reopen this issue if that changes.
