### ISSUE TITLE
FpsDisplay component enforces / requires TextMesh component, although its optional

### ISSUE THREAD

**Issue by FejZa** [Microsoft/MixedRealityToolkit-Unity#2056]
## Overview
The FPSDisplay component requires a TextMesh component on the same game object using
`[RequireComponent(typeof(TextMesh))]`

when actually it is not mandatory. The FPSDisplay component is written in a way, that it can work either with a TextMesh or a UGUI Text component. It will just write the FPS into either, depending on whether it's set or not

`if (textMesh != null)
            {
                textMesh.text = displayString;
            }`

`
            if (uGUIText != null)
            {
                uGUIText.text = displayString;
            }`

## Expected Behavior
Writing the FPS into a TextMesh component is optional.

## Actual Behavior
If there is no TextMesh, one will be enforced and FPS will write into it.

## Proposed Solution
Remove [RequireComponent] Attribute in FPSDisplay component.

**Comment by FejZa** [comment]
Sorry I just realized this is already fixed in the Dev_Working_Branch.

**Comment by StephenHodgson** [comment]
uGUI has some performance overhead anyway

**Comment by FejZa** [comment]
Yeah. I just stumbled upon this when creating a "debug console" with UGUI for my project and wanted to use FPSDisplay in it.

**Comment by davidkline-ms** [comment]
@FejZa,

This is fixed in the may18_dev branch and will be released as part of 2017.4.0.0 in mid-May.

Thanks!

**Comment by davidkline-ms** [comment]
Please see #2006
