### ISSUE TITLE
SimpleSinglePointerSelector: consider connecting pointer upon OnSourceDetected

### ISSUE THREAD

**Issue by PJBowron** [Microsoft/MixedRealityToolkit-Unity#2066]
## Overview
When dealing with one or more pointer-providing motion controllers, the user may activate their controller after the app has begun to execute.

## Expected Behavior
The activated controller becomes the primary controller.

## Actual Behavior
Primary control remains with a previous controller (head-gaze, in the case of first controller activation)

## Suggested change
In an internal project, we locally modified `SimpleSinglePointerSelector` and called `ConnectBestAvailablePointer` upon `OnSourceDetected` (if said controller `SupportsPointingRay`).

We'd like to contribute this change, if that sounds good?

**Comment by StephenHodgson** [comment]
Sounds good.

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
