### ISSUE TITLE
0 frame animation warnings from default cursor

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2067]
## Steps to reproduce
- Create a new project
- Import the toolkit
- Apply scene settings (add input mananger and cursor)
- Open the Console window and observe warnings re:
    - Cursor_cross_root
    - CursorRing

## Unity Editor Version
i've seen this with 2017.2.1p2, 2017.4.2f2

## Mixed Reality Toolkit Release Version
2017.2.*

**Comment by StephenHodgson** [comment]
Which cursor are you using?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
