### ISSUE TITLE
Warning cleanup "The private field is assigned but its value is never used"

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2068]
Identify and cleanup "The private field is assigned but its value is never used" warnings

**Comment by davidkline-ms** [comment]
There are some in the SpectatorView feature that was introduced in the may18_dev branch.

**Comment by keveleigh** [comment]
Found one more when building Standalone:

![image](https://user-images.githubusercontent.com/3580640/40802062-68e3b432-64c9-11e8-9b30-2fe9d6528ecf.png)
