### ISSUE TITLE
Warning cleanup: "ImportFBX warnings: Can't import tangents and binormals, because mesh doesnt have it"

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2070]
When loading the toolkit and examples (ex: clone and open the repository), the following models are being reported:
- BackBody
- Backpack
- BottomLeftBody
- BottomRightBody
- Face
- FrontAntenna
- Gas
- GasTank
- GasTankGlass
- GoldBase
- LeftTwirler
- Legs1
- Legs2
- Legs3
- Legs4
- Light
- Nose
- ThrustCylinder
- TopGoldDial
- TopLeftBody

**Comment by bob-smith23** [comment]
L
