### ISSUE TITLE
Solver Body Lock null refs if the tracked object isn't present

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#2073]
## Overview
If the tracked object isn't present, [line 65](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/Solvers/SolverBodyLock.cs#L65) null refs when trying to access transformTarget.

## Expected Behavior
"Fails" silently until the tracked object appears.

## Actual Behavior
![image](https://user-images.githubusercontent.com/3580640/39894547-12a60fac-545c-11e8-94bf-acef382e4fdd.png)

## Steps to reproduce
1. Open SolverExamples and run without a left motion controller connected.
2. Observe the above message in the console.

## Unity Editor Version
2017.2.1p2

## Mixed Reality Toolkit Release Version
2017.2.1.4

**Comment by davidkline-ms** [comment]
good find!

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
