### ISSUE TITLE
Solver Momentumizer quickly becomes { NaN, NaN, NaN }

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#2074]
## Overview
It looks like some calculation in [`CalculateMomentum`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/Solvers/SolverMomentumizer.cs#L47) quickly becomes too large and the calculated velocity becomes { NaN, NaN, NaN }. 🦇

## Expected Behavior
This component works (I guess the cube in the scene should look like it's accelerating/decelerating?). 

## Actual Behavior
![image](https://user-images.githubusercontent.com/3580640/39894963-6e884e24-545d-11e8-8074-24e3c849920c.png)

## Steps to reproduce
1. Open SolverExamples and run.
2. Observe the above message in the console.

## Unity Editor Version
2017.2.1p2

## Mixed Reality Toolkit Release Version
2017.2.1.4

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
