### ISSUE TITLE
Billboards lack support for two axis pivots.

### ISSUE THREAD

**Issue by jwittner** [Microsoft/MixedRealityToolkit-Unity#208]
There are cases where you want this, e.g. Tag-a-longs that don't rotate about the Z. 

I'm thinking of adding PivotAxis.XY, etc. to support these cases.

**Comment by NeerajW** [comment]
I wonder if we should just make Billboard.cs do a LookAt.

**Comment by jwittner** [comment]
@NeerajW and kill the PivotAxis enum?

**Comment by stbertou** [comment]
My 2c: I think the locking feature is really useful and should definitely stay.
What about adding lock per axis instead (as Booleans) although most of the time you only wanna lock the Y axis not sure why you would want to lock another one.

**Comment by jwittner** [comment]
@stbertou I think we can achieve that with the addition of PivotAxis.XY, XZ, and YZ. At that point I think we've covered all the potential options.

**Comment by jwittner** [comment]
Yay!
