### ISSUE TITLE
Error CS1061

### ISSUE THREAD

**Issue by thekidwiz** [Microsoft/MixedRealityToolkit-Unity#2080]
## Overview
Just following a tutorial to become accustomed to the Hololens implementations to design an application. 
## Expected Behavior
should compile and run
## Actual Behavior
produces two errors.
## Steps to reproduce
https://next.reality.news/how-to/hololens-dev-101-building-dynamic-user-interface-part-1-setup-0179747/ 
you can follow the steps: should literally take one minute, theres a pastebin link for the code at the bottom of step 2 so you dont have to type it out.
error occurs as soon as i create the BoundingBox script and put the IFocusable in,  finished part 3, should compile to run but gives the error in unity: 
"Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/TwoHandManipulatable.cs(120,45): error CS1061: Type `BoundingBox' does not contain a definition for `Target' and no extension method `Target' of type `BoundingBox' could be found. Are you missing an assembly reference?" 
and 
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/TwoHandManipulatable.cs(125,45): error CS1061: Type `BoundingBox' does not contain a definition for `Target' and no extension method `Target' of type `BoundingBox' could be found. Are you missing an assembly reference?

**Comment by thekidwiz** [comment]
@StephenHodgson so just an fyi, the problem came when i tried to make a script called "boundingbox" which I'm assuming might have messed with the other boundingbox script in the assests folder.... probably.

**Comment by samharper94** [comment]
Yes, that's almost definitely what's screwed it up.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
