### ISSUE TITLE
Investigate use of pragma warning in MRTK scripts

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2081]
Understand if they are needed / can be worked around and get documented / replaced as appropriate.

**Comment by SimonDarksideJ** [comment]
Something best left for vNext, as we completely avoid them. (as much as AI Possible)

**Comment by keveleigh** [comment]
https://github.com/Microsoft/MixedRealityToolkit-Unity/search?utf8=✓&q=pragma+warning&type=

Looks like 5 scripts currently in master use pragma warning.
Mostly, it's 618 and 612 for obsolete code, 67 for an event never being used, and 414 for a private field being assigned but never used.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
