### ISSUE TITLE
Application hangs after April Update

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#2085]
## Overview
Application hangs after April Update
I think that this is not an issue related to MRTK, but I want to share my experience and I want to know if someone is having the same problem after April Update.
## Expected Behavior
Same before April Update
## Actual Behavior
From the health report of my app published on the Windows Store I can see some hangs after April Update. 
I can't reproduce the same behavior inside the Unity player.
After many tests I was able to reproduce the same behavior using the VS project (debug configuration) and in that case the issue was this:
![dictationrecognizer](https://user-images.githubusercontent.com/17752475/39943885-d5489670-5564-11e8-8e23-8cb959d4f93a.PNG)
59 seconds for new DictationRecognizer().
Disabling the component (DictationInputManager) I was not able to reproduce the issue in debug mode.
With the master release the situation is better but not completely solved.
I think that there is a more general problem with the application activation (OS or Unity issue?).
The stack trace when there is an hang is this:

![cattura](https://user-images.githubusercontent.com/17752475/39944527-498199c2-5567-11e8-9f91-d33ad41b4b90.PNG)

## Steps to reproduce
…..
## Unity Editor Version
2017.4.2f2
2017.4.1f1
## Mixed Reality Toolkit Release Version
2017.2.1.0

**Comment by ivan2007** [comment]
Just an update on this issue
After I opened this issue I also opened an issue with Unity and I gave them a reproduction project (SpeechInputSource scene of the MRTK where I added a script).
The problem is related to DictationRecognizer and KeywordRecognizer.
Now there is the official response from Unity:

Hello, 

Thank you for submitting the issue.

I tested this issue in 2017.4.2f2 and manage to reproduce it but just when the debugger is attached, but on the latest version 2017.4.6f1 the issue isn't reproducible. Unity 2017.4.6f1 will be released next week. When it is released could you check if you can reproduce this issue?

Regards,
Šarūnas
QA team 

I will try with the incoming version of Unity and I will report here my results.

**Comment by ivan2007** [comment]
I can reproduce the issue also with Unity 2017.4.6f1.
The issue isn’t systematic.
When the issue is present (you see the four spinning spheres) if you open and close the HMD the app starts.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
