### ISSUE TITLE
Immersive Application Laggy after deployment

### ISSUE THREAD

**Issue by EdiLipo** [Microsoft/MixedRealityToolkit-Unity#2089]
## Overview
The application works very smoothly in Unity, however, after it's been deployed and is run through the Mixed Reality Portal there is noticeable delay and FPS loss.

## Expected Behavior
Should run smoothly as any other immersive application, i guess?

## Actual Behavior
Runs much slower compared to when it was run in unity

## Steps to reproduce
 followed  the steps for deployment here https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/GettingStarted.md

## Unity Editor Version
 unity v3.0.f3

## Mixed Reality Toolkit Release Version
toolkit v2.1.3

**Comment by ivan2007** [comment]
Probably you selected Debug configuration, try Release or Master

**Comment by keveleigh** [comment]
Unable to repro with the above repro steps. Double checking that your configuration isn't set to Debug (as described above) is a good place to start. Closing as no repro.
