### ISSUE TITLE
Support Generation of AppInstaller file

### ISSUE THREAD

**Issue by BenWoodford** [microsoft/MixedRealityToolkit-Unity#2090]
This is mostly preparing a suggestion for now as it's only part of the VS 15.7 inside preview and RS4, however...

It would be _very_ nice (especially for those of us doing contract work) to have a checkbox to enable the new automatic update functionality for UWP packages. I would assume it works on Hololens too, can't see any reason why not.

You can read about it here, though it doesn't include the necessary command line arguments you'd need to automate it: https://blogs.msdn.microsoft.com/appconsult/2018/03/22/handling-auto-updates-for-sideloaded-uwp-and-desktop-bridge-apps/

**Comment by StephenHodgson** [comment]
Ben, are you suggesting to add this to the build and deploy window?

I'm not sure what the command line option for msbuild this would be. It wasn't immediately apparent from that blog post. Do you have a link to the MSFT docs page?

**Comment by BenWoodford** [comment]
Yep, to Build & Deploy

I’m not sure if the argument docs are available for it yet, as it’s only in the insider preview. I mostly submitted this issue to get the ball rolling on discussion of it.

**Comment by BenWoodford** [comment]
I’ve amended the title to be more accurate to what is needed here. The best option is probably just to generate the .appinstaller file via scripting as MakeAppX.exe doesn’t seem to have an option for it.

The schema format can be found here: https://docs.microsoft.com/en-gb/uwp/schemas/appinstallerschema/schema-root

The best option for post-build seems to be to support running a conmand or batch file after build to handle the new build folder and the updated appinstaller file (either passing the installer and folder as separate command calls, one string or separate variables). VS also generates an index.html to go with it but this isn’t nearly as important to start with 

For a lot of people the post-build script would probably be an FTP upload but there’s all sorts it could be used for.

**Comment by BenWoodford** [comment]
More interesting things...

It seems that if you have an appinstaller file in the folder, MakeAppX.exe will always update it (even through the MRTK build window) and the index.html file with the new information on build such as version number, folder, etc.

```
<?xml version="1.0" encoding="utf-8"?>
<AppInstaller Uri="<appinstaller url>" Version="1.0.83.0" xmlns="http://schemas.microsoft.com/appx/appinstaller/2017/2">
  <MainBundle Name="<bundle name>" Version="<version num>" Publisher="CN=DefaultCompany" Uri="<appxbundle in build folder>" />
  <Dependencies>
    <Package Name="Microsoft.VCLibs.140.00" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" Version="14.0.25426.0" ProcessorArchitecture="x86" Uri="<appx url>" />
    <Package Name="Microsoft.NET.Native.Framework.1.3" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" Version="1.3.24201.0" ProcessorArchitecture="x86" Uri="<appx url>" />
    <Package Name="Microsoft.NET.Native.Runtime.1.4" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" Version="1.4.24201.0" ProcessorArchitecture="x86" Uri="<appx url>" />
  </Dependencies>
  <UpdateSettings>
    <OnLaunch HoursBetweenUpdateChecks="0" />
  </UpdateSettings>
</AppInstaller>
```

HoursBetweenUpdateChecks = 0 means it checks for updates every launch. However auto-update doesn't appear to work on the Hololens right now :(

The appinstaller and index.html files are put in the root of the `AppPackages` folder. You then upload the latest folder (which the appx URLs will point to) and those two files to the file share or web folder for download. I can provide an appinstaller with more context later if you need one, I only have it setup for client projects right now.

**Comment by StephenHodgson** [comment]
Thanks for the info!

**Comment by BenWoodford** [comment]
I’ll see if I can find the bit in the project file that configured the appinstaller at some point

**Comment by BenWoodford** [comment]
It seems to this block that does it, which is part of the main `<Project>` block in the `csproj`

```
<GenerateAppInstallerFile>True</GenerateAppInstallerFile>
    <AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
    <AppxBundle>Always</AppxBundle>
    <AppxBundlePlatforms>x86</AppxBundlePlatforms>
    <AppInstallerUri>[snip]</AppInstallerUri>
    <AppInstallerUpdateFrequency>1</AppInstallerUpdateFrequency>
    <AppInstallerCheckForUpdateFrequency>OnApplicationRun</AppInstallerCheckForUpdateFrequency>
```

The installer URI is the folder rather than the appinstaller file URL

**Comment by BenWoodford** [comment]
Just for more clarification, that block appears in the `PropertyGroup` at the top, just after `</AllowedReferenceRelatedFileExtensions>`

The Uri is a URL, but it's the URL to the root of the folder holding the appinstaller and index.html files. For instance, `https://example.com/appfolder` would be the Uri and also where you store the files.

In terms of post-processing, a general "run this command" would be nice. That can then support all sorts, I personally upload the files using SFTP. Perhaps include an option to run the command it under the Ubuntu/Linux Subsystem if it's possible to call that from command line.

**Comment by RichLogan** [comment]
Apologies for reopening discussion on such an old issue (and this is not exactly specific to MRTK), but are automatic updates as defined in the `.appinstaller` expected to work on the Hololens 2 right now? I can't find any documentation to the contrary, but my application does not appear to update to later versions published to the provided URL on launch as requested. I do see that the App Installer application itself appears to only be available on Desktop though.

**Comment by polar-kev** [comment]
Closing this issue since there isn't clear signal that it is desired.
