### ISSUE TITLE
[may18] "allow unsafe code" not auto-checked via mcs.rsp

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2103]
With the addition of Spectator View, projects including the folder in their project must tell Unity (and Visual Studio) that unsafe code is allowed.

Unity should read the mcs.rsp file (included in the MRTK) and set the checkbox in the Visual Studio project.

This appears to not be happening.

The current workarounds are:
- Manually check "Allow Unsafe Code" **each time** the solution is built from Unity
- Do not generate C# projects when building in Unity (let Unity generate the assemblies).

This may be that the MRTK does not have the correct rsp file for the specific version of Unity or it may be a Unity issue.

**Comment by StephenHodgson** [comment]
Custom assembly definitions will help with this.

**Comment by davidkline-ms** [comment]
Unfortunately, we don't have those for master branch releases :\

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
