### ISSUE TITLE
Scroll Rect not working with Standalone Input Module

### ISSUE THREAD

**Issue by shubhamarora28** [Microsoft/MixedRealityToolkit-Unity#2108]
## Overview
Facing problem with Scroll Rect in HoloLens. It is not working with the Standalone Input Module. If I replace the Standalone Input Module with Holo Lens Input Module, it works(output is not perfect though; content flickers a lot), but, in the MRTK overview, it is clearly mentioned that all the inputs should work with the Standalone Input Module.

## Expected Behavior
Scrolling should work with Standalone Input Module.

## Actual Behavior
Scrolling does not work with Standalone Input Module.
Scrolling does work with Holo Lens Input Module(not perfectly though; content flickers a lot).

## Steps to reproduce
1. Create an empty scene and apply mixed reality scene settings
2. Create a World Space canvas
3. Add a Scroll View to it
4. Build and deploy on HoloLens

## Unity Editor Version
2017.2.1p4

## Mixed Reality Toolkit Release Version
2017.2.1.0

**Comment by StephenHodgson** [comment]
It was never implemented, but that's something we can look into for vNEXT.

**Comment by StephenHodgson** [comment]
Part of the problem is that scrolling with the standalone input module requires the assignment of a axis input, which the HoloLens cannot utilize, or assign.

![image](https://user-images.githubusercontent.com/13334553/40131730-a60f14e0-58ef-11e8-950f-0013af239c4e.png)

**Comment by shubhamarora28** [comment]
Thanks a lot.
Will be using Holo Lens Input Module till the time vNEXT is out.

**Comment by keveleigh** [comment]
This should be better supported in MRTK v2 via #3749. Please re-open if you still see issues after upgrade.
