### ISSUE TITLE
Keyboard subtypes not working (numpad)

### ISSUE THREAD

**Issue by Vizzr** [Microsoft/MixedRealityToolkit-Unity#2110]
## Overview
I am trying to show a numpad only. However, this does not work. Neither do the other keyboard types.
It is possible to switch between Alpha and Symbol, but no sublayout.

## Expected Behavior
Expected to see a numpad only.

## Actual Behavior
This happens:

![image](https://user-images.githubusercontent.com/36069685/40122769-d97a907c-5924-11e8-9acd-0acd0653bde8.png)

## Steps to reproduce

These are the settings:
![image](https://user-images.githubusercontent.com/36069685/40122511-4409f5d2-5924-11e8-95c6-d5e03e1a5679.png)

I used the keyboard test scene.

## Unity Editor Version
2017.1.0p5
2017.3.0f3

## Mixed Reality Toolkit Release Version
1.5.7.0
and one for Unity Editor 2017.1.2f1. oct 17 release (dont know the actual version)

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
