### ISSUE TITLE
[Dev branch] ProgressExampleLaunchButton in MRTK has a dependency on MRTK-Examples

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#2111]
## Overview
The dependency below breaks the MRKT if you don't include the Examples project.

In MixedRealityToolKit there is a dependency between
Assets/MixedRealityToolkit/UX/Scripts/Progress/ProgressExampleLaunchButton.cs 
and
ProgressExamples.cs in MixedRealityToolkit-Examples.

## Expected Behavior
No dependencies between MRKT and Examples

## Actual Behavior
Dependency

## Steps to reproduce
Install MRKT without MRTK-Examples and try to build.

## Unity Editor Version
Any

## Mixed Reality Toolkit Release Version
Dev branch

**Comment by genereddick** [comment]
Probably ProgressExampleLaunchButton.cs is meant to stay in Examples? Delete it from MRKT and you can build.

**Comment by davidkline-ms** [comment]
Just as an FYI, the PR for Dialog and Progress that is heading into the may release has ProgressExampleLaunchButton.cs in the correct location (Examples project)

**Comment by cre8ivepark** [comment]
Yes, it is moved to HoloToolkit-Examples folder in May18 branch.
Need to apply back to Dev branch.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
