### ISSUE TITLE
Master Build warnings with IL2CPP in 2017+

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2124]
## Overview
The `MetroHandleRef.cs` class conflicts with the imported type 'HandleRef" in mscorlib when using the IL2CPP scripting backend.

## Unity Editor Versions
- 2017.4.3f1
- 2018.1.0f2

## Mixed Reality Toolkit Release Version
84493c975fbf0fe0f3541303ce1758ca11dfe44a

**Comment by davidkline-ms** [comment]
Odd thing is that, looking at this class, it shouldn't be getting included when building IL2CPP...

#if UNITY_WSA && !UNITY_EDITOR && !ENABLE_IL2CPP

**Comment by StephenHodgson** [comment]
Yeah, now it is being excluded cause I added the  !ENABLE_IL2CPP in the last few PRs
