### ISSUE TITLE
How to access vNext current build?

### ISSUE THREAD

**Issue by gobanjoboy** [Microsoft/MixedRealityToolkit-Unity#2128]
I have searched and I am unable to find the code for vNext. I looked at the branch but I do not seem to have access to the code. I only see the meta files.

**Comment by StephenHodgson** [comment]
We're not quite ready for people to start using the vNEXT branch just yet.

That being said, if you'd like to help contribute to writing it, pulling the branch should have more than just meta files.  Make sure you don't have any pending changes and clean your git folder before pulling.

**Comment by gobanjoboy** [comment]
I have been trying download as zip from the site.

**Comment by StephenHodgson** [comment]
We don't have any releases for vNEXT availible.

**Comment by davidkline-ms** [comment]
Our first (read: Alpha) release is planned for mid-June.

If you clone and checkout MRTK-Version-Next, you should have code under Assets/MixedRealityToolkit.

Enjoy and as @StephenHodgson says, please feel free to contribute.
