### ISSUE TITLE
vNext: Update coding style guidelines

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2142]
Re: use of [WINDOWS_UWP vs UNITY_UWP](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/2017.4.2.0/CodingGuidelines.md#use-platform-dependent-compilation-to-ensure-the-toolkit-wont-break-the-build-on-another-platform), etc

**Comment by keveleigh** [comment]
I don't think this is in vNext yet
