### ISSUE TITLE
june18: Update coding style guidelines

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2143]
Re: use of WINDOWS_UWP vs UNITY_UWP, etc

**Comment by keveleigh** [comment]
Per https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2136#discussion_r189693473

**Comment by StephenHodgson** [comment]
This might be too big a change for master, when we can easily enforce it in vNEXT.

**Comment by keveleigh** [comment]
I'm just going to add the table to CodingGuidelines.md for now.
