### ISSUE TITLE
Public variables not visible in inspector

### ISSUE THREAD

**Issue by derekfleming95** [Microsoft/MixedRealityToolkit-Unity#2151]
Having an issue where public variables from scripts such as Billboard.cs don't display in the inspector window, all that's visible is the title. Compiling and script functionality work as expected though.

Have tried in Unity 2017.3.1f1 and 2017.2.1f1 with no luck. Any ideas?

## Unity Editor Version
2018.1.0f2
## Mixed Reality Toolkit Release Version
2017.2.1.4

**Comment by keveleigh** [comment]
Yep, this one was my bad. Some fields weren't properly serialized. It's fixed for the next release, and you can grab that version here: https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/may18_dev/Assets/HoloToolkit/Utilities/Scripts/Billboard.cs

**Comment by derekfleming95** [comment]
Great! Thanks for the quick reply.

Just for completeness, are there other scripts where this issue is also present?

**Comment by keveleigh** [comment]
@derekfleming95 I'm not aware of any others present in the previous release, so this should be the only script you'll need to update.
