### ISSUE TITLE
Cursor works in emulator but not at deployment

### ISSUE THREAD

**Issue by kindtje** [Microsoft/MixedRealityToolkit-Unity#2153]
I am creating an application for the Hololens in Unity, when I test it in the Unity holographic emulator the cursor works properly, but when I deploy it to the Hololens it does not work.
I followed the the windows academy to get it working, but that did not help. Anyone any idea how to solve this?

**Comment by cQuencee** [comment]
You will have to be more specific about how it doesnt work: Is it the button clicks, you dont even see it or animation doesnt work. Also what prefab did you use and scripts.

**Comment by kindtje** [comment]
@cQuencee it does not interact with interactables, and the positioning gets updated but very slowly, and when it should go to the default distance of the person it goes towards the person until it disappears

**Comment by cQuencee** [comment]
@kindtje You did deploy it in release right? or master

**Comment by kindtje** [comment]
@cQuencee I didn't do that before, but trying that got me the same result

**Comment by cQuencee** [comment]
@kindtje You always need to deploy on Release or Master(production), you can read more about it [here](https://docs.microsoft.com/sl-si/windows/mixed-reality/exporting-and-building-a-unity-visual-studio-solution#building_and_deploying_a_unity_visual_studio_solution). I've just noticed that you tested it on Unity holographic emulator(thought you said on Hololens emulator). I never use Unity emulator but I test it on Hololens emulator. I think it would be best that you try to deploy a MRTK example to see what results you get. I would also suggest you to use Hololens emulator instead of Unity one.

**Comment by cQuencee** [comment]
@kindtje  If example doesn't work than there is a problem with your set up, meaning unity version, unity settings, windows sdk, etc. I hope you'll get it to work :)

**Comment by keveleigh** [comment]
Which Unity version are you using? Which Toolkit version are you using? Filling out the [pre-filled Issue template ](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/.github/issue_template.md) helps provide us the information we need to debug your issue.

As-is, I tried repeating the steps you provided (in the Academy, I assume 210?), and I was unable to repro your issue.

**Comment by Redge-Ballard** [comment]
I've seen something kind of like this that is super unpredictable. After making changes to my project (totally unrelated to anything with holotoolkit) the cursor will be totally normal in editor but invisible in the build. There's absolutely no rhyme or reason to when it breaks, but just every few builds it occurs. You can still click on things (if you can correctly guess where the cursor should be) but it just doesn't show. Visual Studio gives this error:

NullReferenceException: Object reference not set to an instance of an object.
   at HoloToolkit.Unity.InputModule.Cursor.UpdateCursorTransform()
   at HoloToolkit.Unity.InputModule.InteractiveMeshCursor.UpdateCursorTransform()
   at HoloToolkit.Unity.InputModule.Cursor.$Invoke32(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)

But like I said in the editor it's fine. The only way I've ever been able to fix it is buy duplicating my cursor prefab (I'm using the InteractiveMeshCursor) several times, and randomly the InputManager will sometimes grab one of them and use it, but other times I have to keep duplicating it and rebuilding until it finally likes one of the duplicates. On a bad day this literally sucks up to an hour of time...

I'm using Unity version 2018,1,6f1 and Holotoolkit 2017.4.0.0 (that's the MRTK Version inside that package right?)

**Comment by cQuencee** [comment]
There is definitely something not right. You shouldn't have to duplicate cursor prefabs to get it to work properly(if it even works properly). I've had some kind of similar problems with builds previously, that I had to build it multiple times to be able to deploy it on to the device, I've found out that it was the problem with compatibility between MRTK version and Unity version I was using(My Unity version was not recommended for that MRTK release). I was able to fix that by following MRTK instructions about which is the recommended version for my chosen MRTK version.

So my advise is to always check which is the recommended Unity version for MRTK you are using(version already states which Unity version is ment/recommended) and use that one. I'm using the same MRTK version(2017.4.0.0, same as you) and Unity 2017.4.1f1. So try your project with that version.
Also make sure you have the right Build, Project and Scene settings for your device, you can find lots of info on that subject or just check examples provided by MRTK.

If you want/have to use 2018.1.6f1(which I strongly do not recommend - you can run into similar problems later on) than try to build and deploy example that's provided by MRTK. If that works as it should than carefully check how example uses prefabs and what settings are set. 

Try all that and if you still encounter the same problem, come back and Ill try to help best I can.

Regards.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
