### ISSUE TITLE
Remoting Play doesn't support anchor store

### ISSUE THREAD

**Issue by Merglasch** [Microsoft/MixedRealityToolkit-Unity#2161]
## Overview
On entering play mode I get the warning that this build doesn't support WorldAnchorStoreManager. Which strikes me as weird, as I can use all the other spatial features during remoting play and get info about the movement of the lens.
## Expected Behavior
Being able to use Anchors and Anchor sharing during remoting play
## Actual Behavior
not supported
## Steps to reproduce
The Example sharing project (with the auto join room) will do fine to experience this.
## Unity Editor Version
2017.4.4
## Mixed Reality Toolkit Release Version
2017.2.1.4 Patch Release

**Comment by davidkline-ms** [comment]
Thank you for filing this issue. I have forwarded it to the owner of the Remoting Player.

**Comment by davidkline-ms** [comment]
For future reference, the Feedback Hub application (on your HoloLens or PC) is the best route to providing bug reports, suggestions and other feedback on the Remoting Player.

Thanks again!
