### ISSUE TITLE
Remoting Play Application looses Connection on bloom

### ISSUE THREAD

**Issue by Merglasch** [Microsoft/MixedRealityToolkit-Unity#2162]
## Overview
I don't know if this is the right place to post this error so feel free to redirect me. 
When using remoting play on the hololens, if you make the bloom gesture the remoting play application will get minimized. This is annoying and I wish one could prevent that (without kiosk mode), but alas it is not the real problem for me. Far worse is that when you open up the minimized app again, it has forgotten that it was connected. Unity on the other side still thinks there is a connection. Both will ignore each others status and stay like that forever. If you try to disconnect and reconnect from the unity side of things, unity will simply crash.
## Expected Behavior
Remoting App keeping the connection even while minimized
## Actual Behavior
Remoting App looses the connection.
## Steps to reproduce
Try any project with remoting.

## Unity Editor Version
2017.4.4
## Mixed Reality Toolkit Release Version
2017.2.1.4 Patch Release

**Comment by davidkline-ms** [comment]
Thank you for filing this issue. I have forwarded it to the owner of the Remoting Player.

**Comment by davidkline-ms** [comment]
For future reference, the Feedback Hub application (on your HoloLens or PC) is the best route to providing bug reports, suggestions and other feedback on the Remoting Player.

Thanks again!
