### ISSUE TITLE
may18 rc - WACK fails - spectatorview

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2163]
## Overview
Compiling a project using the 2017.4.0.0 release candidate fails WACK with errors regarding the pinvokes into the spectatorviewplugin.dll -- the dll is NOT present in the build.

## Steps to reproduce
- Import the 2017.4.0.0 release candidate and examples unitypackages
- Open your favorite scene
- Genereate solution
- Build master config
- Generate store package
- Run local WACK

**Comment by davidkline-ms** [comment]
I am going to investigate adding a #define to opt-in to building the SpectatorView components

**Comment by StephenHodgson** [comment]
Is this because we're missing a copy of it in both the normal plugins folder and a wsa folder?

**Comment by davidkline-ms** [comment]
Most likely. I am working on an option to avoid this issue for customers that are not using SpectatorView, yet import the entire unitypackage.

**Comment by davidkline-ms** [comment]
With all required DLLs present, the API check fails when SpectatorView is enabled.

API gzclose in zlib1.dll is not supported for this application type. opencv_core341.dll calls this API.
API gzeof in zlib1.dll is not supported for this application type. opencv_core341.dll calls this API.
API gzgets in zlib1.dll is not supported for this application type. opencv_core341.dll calls this API.
API gzopen in zlib1.dll is not supported for this application type. opencv_core341.dll calls this API.
API gzputs in zlib1.dll is not supported for this application type. opencv_core341.dll calls this API.
API gzrewind in zlib1.dll is not supported for this application type. opencv_core341.dll calls this API.

**Comment by davidkline-ms** [comment]
Removing Bug and adding External tag as this is an issue with OpenCV and not the MRTK code
