### ISSUE TITLE
SpatialMappingSource Build Warning

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2164]
## Overview

When targeting .NET Scripting Backend and .NET Standard 2 using the Master Configuration, `SpatialMappingSource` throws a warning about a possible missing namespace.

```
C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24211\x86\ilc\IlcInternals.targets(936,5): warning : ILTransform_0003: Method '$MethodUtility.$Invoke6632(long, long*)' will always throw an exception due to the missing method 'Expression<Func<SpatialMappingSource>>.Update(Expression, IEnumerable<ParameterExpression>)'. There may have been a missing assembly.
```

**Comment by TChag** [comment]
Method '$MethodUtility.$Invoke24574(long, long*)' will always throw an exception due to the missing method 'Expression<Func<SpatialMappingSource>>.Update(Expression, IEnumerable<ParameterExpression>)'. There may have been a missing assembly.

Any work around for this? I am attempting to create master build to release to the store?

**Comment by waldobronchart** [comment]
@TChag, @StephenHodgson: do you still have this issue? I've been trying to fix this for a while now without any luck

**Comment by inforexperience** [comment]
Any news on this? Unfortunately, using IL2CPP is not an option for us. Unity 2017.4.10f1.

**Comment by waldobronchart** [comment]
If the build fails with "Internal Compiler Error" or "Out Of Memory", then you can turn off optimization. Open Properties/Default.rd.xml and add the following lines after <Assembly Name="*Application*" Dynamic="Required All" />:

> <Assembly Name="Assembly-CSharp" Dynamic="Required All" DoNotOptimize="true"/>
> <Assembly Name="Assembly-CSharp-firstpass" Dynamic="Required All" DoNotOptimize="true"/>

**Comment by davidkline-ms** [comment]
Code has been completely rearchitected. Please reopen if it occurs on current branches.
