### ISSUE TITLE
Can I Change length of Motion Controller pointing ray when if lost focus from a object?

### ISSUE THREAD

**Issue by TakahiroMiyaura** [Microsoft/MixedRealityToolkit-Unity#2166]
## Overview
Can I Change length of Motion Controller pointing ray when if lost focus from a object?
I feel short it in the setting of MRTK2017.4.0.0-RC1. 
When we lost focus from a object,we would be better to "Ray" is pointing far as possible.  We will be easer to understand the state of lost focus .

![1](https://user-images.githubusercontent.com/8484268/40525537-8f735b3c-601b-11e8-8873-c171601c66e4.png)

## Steps to reopen 
Open scene "InputNavigationRotateTest.unity" and execution in HoloToolkit-Unity-2017.4.0.0-rc.unitypackage.

## Unity Editor Version
Unity 2017.4.3f1
## Mixed Reality Toolkit Release Version
MRTK 2017.4.0.0-RC1

**Comment by gobanjoboy** [comment]
It seems I have been able to extend it some, but there seems to be a cap some where. It doesn't really seem to use my 200 value.

![screenshot_1](https://user-images.githubusercontent.com/174855/40552235-b72bead4-6004-11e8-8582-dbf94241bc4f.png)

**Comment by gobanjoboy** [comment]
Okay I figured it out.

Unless I configured something that didn' t need to be set. I found three places that needed to be updated.

![screenshot_1](https://user-images.githubusercontent.com/174855/40553057-242342b6-6007-11e8-9f90-e0c743d7d0ee.png)
![screenshot_2](https://user-images.githubusercontent.com/174855/40553058-2433ec6a-6007-11e8-8e62-6fa8cc5f6af9.png)

**Comment by keveleigh** [comment]
Yep, Default Cursor Distance is (at the moment) where you'd change it. I'm working on a change that'll make this a little more configurable, especially depending on the type of pointer your cursor is attached to (you likely want the default distance further from the controllers than from your gaze, etc). 

I'll also look into the observed cap above. I'm not sure what that might be.

**Comment by cre8ivepark** [comment]
@TakahiroMiyaura @keveleigh I had similar feedback. Thanks for opening the issue!

**Comment by gobanjoboy** [comment]
@keveleigh the Cap I spoke about was because I was not editing all three spots. I was only changing the DefaultCursor. I don't have any cap issues.

**Comment by gobanjoboy** [comment]
Has there been any talk of scaling the cursor bigger as it gets further way?

**Comment by StephenHodgson** [comment]
I'll be sure to make it easier to update this option in vNEXT

**Comment by TakahiroMiyaura** [comment]
@gobanjoboy Thank you for the information!

**Comment by TakahiroMiyaura** [comment]
@StephenHodgson ,@cre8ivepark.
Thank you for your consideration!
When it becomes to set it simple, we'll be more easer to use MRTK!
In addition,I was wondering you could provide by the initial value which set to long distance?

**Comment by cre8ivepark** [comment]
@keveleigh I agree. the default length feels somewhat short. it would be great if we can increase the default length.

**Comment by keveleigh** [comment]
Definitely! From my tests on Friday, 10 feels good as a default. I'll have a PR open early this week.

**Comment by keveleigh** [comment]
PR https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2201 contained the update, and the latest release has this fix in it.

The controller pointer ray now gets its off-hologram distance from the FocusManager's PointingExtent. The other two locations in https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2166#issuecomment-392096374 can be left untouched.

**Comment by ivan2007** [comment]
@keveleigh 
if the input is disabled and we are not gazing an object the loading cursor is not visible because it is too far. Is it possible to show the loading cursor more near to the user and leave the ray with a length of 10?
