### ISSUE TITLE
SpectatorView - HoloLens camera doesn't activate when iPhone tries to join

### ISSUE THREAD

**Issue by SiriusA7** [Microsoft/MixedRealityToolkit-Unity#2170]
## Overview
HoloLens camera doesn't activate when iPhone tries to join the session.

Built & tested example scene, followed all the instructions in the Readme.
iPhone successfully generates & displays marker, HoloLens successfully loads and displays color changing star. But HoloLens camera never activates. Tested with multiple WiFi networks(5G & non-5G) & closed Wireless Lan networks, no success with any of them.

## Unity Editor Version & Relevant Results
2017.4.4f1 - iOS app worked as expected. HoloLens app didn't load & remained blank after displaying unity splash. Output log showed the spectatorviewplugin.dll didn't load.

2017.2.3f1 - iOS app worked as expected. HoloLens app loaded successfully with color changing star, but doesn't recognize iOS devices attempts to join & therefore never loads camera to see the marker. 

## Versions
MRTK - 2017.4
iPhone X - iOS 11.3
HoloLens - OS Build: 10.0.14393.2248

**Comment by davidkline-ms** [comment]
There is an issue in the release candidate that prevents loading SpectatorViewPlugin.dll.  It has been checked into the may18_dev branch and will be in the second release candidate.

Please note that along with the fix, the SpectatorView feature is been moved from the HoloToolkit folder to the HoloToolkit-Preview folder.

**Comment by ilyavitek** [comment]
2017.4.4f1 - iOS app worked as expected. HoloLens app didn't load & remained blank after displaying unity splash. Output log showed the spectatorviewplugin.dll didn't load. - I had this issue right now.

**Comment by cindychen0204** [comment]
hey,same as me. It was just blank I can not figure out.
