### ISSUE TITLE
Bounding Box UX on Hololens

### ISSUE THREAD

**Issue by MarjanPl** [Microsoft/MixedRealityToolkit-Unity#2179]
## Overview
Using the realease Candidate for 2014.4 and using the UX Bounding Box Manipulation excample.

## Expected Behavior
When pressing DONE the object should not be draggable any more

## Actual Behavior
When pressing DONE, the manupaltion Interface disappears, but the object can still be dragged.

## Steps to reproduce
Use MRToolkit Excample .

## Unity Editor Version
Unity36 2017.4.4f1

## Mixed Reality Toolkit Release Version
https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/2017.4.0.0-rc1

**Comment by Jarodshow** [comment]
Pretty sure this is intentional, but I could make a checkbox for this behavior and submit later

**Comment by cre8ivepark** [comment]
@MarjanPl @Jarodshow Yes, this is following the behavior in RS4 HoloLens and the cliff house in the immersive headset. From RS4, objects are movable and manipulatable using one or two hands, without entering 'Adjust' mode.

**Comment by MarjanPl** [comment]
Hmm, this might be...
However
1.  RS4 isn't even available as a public update.
2. In its initial state the object can't be dragged without activating the toggle. However it can be dragged once you activated the toggle and closed it afterwards. This seems not very streamlined. 
3. This behaviour might reflect the behaviour of the newly released OS, but might not be wanted like this in Unity from the developers perspective.
4. The component has other issues, such as weird behaviour with rather large Objects (Appear is way off)

You don't need to open the case or answer, just a thought.

**Comment by Jarodshow** [comment]
Can you elaborate more on issue 2? I can't replicate this behavior.
