### ISSUE TITLE
I was wondering if you could Add dialog that has "Yes/No/Cancel" buttons?

### ISSUE THREAD

**Issue by TakahiroMiyaura** [Microsoft/MixedRealityToolkit-Unity#2190]
## Overview
We can use dialog that is different button type following:
1.OK button
2.Yes/No button

I was wonderring if you could Add the dialog that had "Yes/No/Cancel" buttons? 
This should come in useful.

## Unity Editor Version
Unity 2017.4.3f1

## Mixed Reality Toolkit Release Version
MRTK2017.4.0.0-RC1

**Comment by TakahiroMiyaura** [comment]
My sincere apologies for delay in replying to you. 
  
If this is adapted, I think it is more useful. 
However, if everyone other than me think that it is not very effective, I will withdraw that proposal.

**Comment by Yoyozilla** [comment]
We will add this to our backlog :)
