### ISSUE TITLE
Issues with MeshSaver.cs

### ISSUE THREAD

**Issue by jansensCCF** [Microsoft/MixedRealityToolkit-Unity#2199]
## Overview
When I opened my computer this morning, the path.combine function was giving MeshSaver.cs issues and I don't know why. Code was working fine on Friday
## Expected Behavior
Functioning code
## Actual Behavior
Broken code
## Steps to reproduce
I would be curious to see if anyone else is getting this error or if it is just me. If you do not have this problem, please state your release version of Visual Studio, Unity, and what Libraries you included
## Unity Editor Version
2018.1
## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by keveleigh** [comment]
Specifically, what error are you seeing?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
