### ISSUE TITLE
Proposal:We were wondering if you could add the checkbox:"Add the Spatial Mapping prefab" in "Apply Mixed Reality Scene Setting" dialog?

### ISSUE THREAD

**Issue by TakahiroMiyaura** [Microsoft/MixedRealityToolkit-Unity#2203]
## Overview

"Apply Mixed Reality Project Setting"  has useful to add "Set Default Spatial Mapping Layer",but we might misunderstand that "Spatial Mapping" is become to available.
In actuality,we must set "SpatialMapping.prefab" to the scene, so we ware wonderring if you could add the checkbox:"Add the Spatial Mapping prefab" in "Apply Mixed Reality Scene Setting" dialog?

![image](https://user-images.githubusercontent.com/8484268/40689514-6969b9de-63dd-11e8-83ec-1b5eac7b17f2.png)

we can set both project and scene from configuration dialog,this should come in useful.

## Unity Editor Version
Unity 2017.4.3f1

## Mixed Reality Toolkit Release Version
MRTK 2017.4.0.0-rc1

**Comment by davidkline-ms** [comment]
Great idea! I have added it to the June release (2017.4.1.0) backlog
