### ISSUE TITLE
How to let the object in iPhone follow in the SpectatorView?

### ISSUE THREAD

**Issue by mrsniperz** [Microsoft/MixedRealityToolkit-Unity#2206]
## Overview
I tried the sample scene "SpectatorViewExample" and built it both on Hololens and iPhone,and i added a "Hand Draggable" component on the object.but when i drag the object,the object in iPhone will not move.
So how can i let the object in iPhone follow?

## Unity Editor Version
2017.3.1p4
## Mixed Reality Toolkit Release Version
MRTK4.0RC2

**Comment by JoseSantano-ms** [comment]
Hello mrsniperz

I think there's a bit of a confusion about what SpectatorView should do out of the box. SpectatorView will manage the connection and space sync between the HoloLens and the iPhone, however, it won't sync up every action you do on the HoloLens by default (transform change, color change....) You can do it but it's something you'll have to hook up manually. 

The reason being is that the iPhone doesn't have to be a "window" to what the HoloLens is seeing but a different application with different actions/modes/views that simply shares the same space.

What you're trying to achieve is possible, an easy way to do it so you can get up and running ASAP would be to implement something similar to what `ColorChanger` is doing but sync the transform instead. There are multiple examples around on how to sync a transform using UNET, I'm sure a simple Google search will yield what you're looking for! :)

**Comment by mrsniperz** [comment]
@JoseSantano-ms Thanks a lot!
