### ISSUE TITLE
Hololens Sharing Objects/Collaboration using CustomMessages

### ISSUE THREAD

**Issue by KickinItInSD** [Microsoft/MixedRealityToolkit-Unity#2221]
Is there a good Tutorial/Example that goes over how to send custom messages to other Hololens users to allow for collaboration/visualization? I have the sharing service working, all the users can see the game objects after downloading anchor, but if one transforms an object, I need all three to see the edits. TIA!

**Comment by keveleigh** [comment]
The CustomMessages script came from [Holograms 240](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-240), which contains some examples of sending and receiving custom messages.

[ProjectileLauncher](https://github.com/Microsoft/HolographicAcademy/blob/Holograms-240-SharedHolograms/Completed/Assets/Scripts/ProjectileLauncher.cs#L13) shows how to register a handler for a custom event, as well as [sending one](https://github.com/Microsoft/HolographicAcademy/blob/Holograms-240-SharedHolograms/Completed/Assets/Scripts/ProjectileLauncher.cs#L53).

**Comment by KickinItInSD** [comment]
kev,

Thank you for the response. So if my network is good, all users can see the shared anchor, what would a good workflow be to build in collaborative transforms changes to that model?

**Comment by KickinItInSD** [comment]
For example, If three users can see the box that user 1 placed after downloading his anchor. If user one changes the box from Blue to Red, how do I get the other users to receive the transform and change it on their view? I was thinking:

1. Build a handler for a custom event (transform?)
2. Send customevent through a custom message to all users

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
