### ISSUE TITLE
IPhone Spectator View and Face Detection

### ISSUE THREAD

**Issue by bdunajczyk** [Microsoft/MixedRealityToolkit-Unity#2238]
## Overview
We would like to use both new SpectatorView feature and Face Detection feature on iPhone

## Expected Behavior
Both Spectator View and Face Detection functionalities available

## Actual Behavior
In current MixedRealityToolkit-Unity there is no Face Detection features (or are we missing something?)

## Steps to reproduce
Add **HoloToolkit-Unity-2017.4.0.0.unitypackage** to the project
Add **HoloToolkit-Unity-PreviewFeatures-2017.4.0.0.unitypackage** to the project
Find out that UnityARSessionNativeInterface is lacking in ARFaceAnchorAddedEvent and others

## Unity Editor Version
Unity 2017.3.1p4

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-2017.4.0.0 RC2

**Comment by Yoyozilla** [comment]
We will add this into our backlog when we start to consider iOS support in MRTK v2. 

Thanks!
