### ISSUE TITLE
ExtensionMethod.cs does not set Angular Velocity

### ISSUE THREAD

**Issue by Nathan-Brower** [Microsoft/MixedRealityToolkit-Unity#2241]
## Overview
Angular velocity is not applied when throwing objects using the grab mechanics in the example package.
I was able to fix this by adding:
`angVel = controllerAngularVelocity;`
to ExtensionMethod.cs.

Cheers!
## Mixed Reality Toolkit Release Version
Current

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
