### ISSUE TITLE
Parabola Line Issue

### ISSUE THREAD

**Issue by gobanjoboy** [Microsoft/MixedRealityToolkit-Unity#2244]
## Overview
LineExample mesh objects missing when playing. I was trying to use the Parabola in my own scene and it wasn't rendering the mesh objects. I jumped over to run the LineExample and it looks like that scene is having issues as well. Not sure whats going on.
## Expected Behavior
View in Editor.
![screenshot_4](https://user-images.githubusercontent.com/174855/40941435-75099390-6810-11e8-91fc-1272fd797645.png)

## Actual Behavior
View while in play mode.
![screenshot_3](https://user-images.githubusercontent.com/174855/40941438-77ddcef6-6810-11e8-81dd-8dd7125f9a45.png)

## Steps to reproduce
Run the LineExample.

## Unity Editor Version
2018.1.0f2
## Mixed Reality Toolkit Release Version
2017.2.1.2

**Comment by ivan2007** [comment]
@gobanjoboy 
I don't see any issue with the lines.
I am using the lines in my app and they work fine.
The spheres that you see in the editor are only gizmos showed by the custom editor.
In the example scene only the Line gameobject uses a LineMeshes renderer where the mesh is a cube. 
The Parabola uses a LineStripMesh and it seems correct.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
