### ISSUE TITLE
Task vNext - Implement OpenVR Device and Initial controller

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2247]
## Overview
OpenVR is currently defined as a scaffold.  This needs to be implemented and tested in the Standalone build.
Initial task should cover only a single controller type as a base

## Requires
* OpenVRDeviceManager (rename current scaffold)
* OpenVR**Controller**
* Tests for OpenVR system
* Feedback on implementation

## Acceptance Criteria
- [X] I can start Unity in Standalone mode whilst configured to use the OpenVR VR platform
- [X] I can view a scene using an OpenVR supported headset
- [X] I can visualize a default object as a controller 
- [X] Input System actions are generated from the OpenVR controller and sent to the Input System
- [X] All inputs from the selected controller are mapped to the Input System

## Associated PR
#2396

**Comment by davidkline-ms** [comment]
@SimonDarksideJ, Is this needed for Alpha or are you planning on this going into Beta 1?

**Comment by SimonDarksideJ** [comment]
We stated for the first MVP, we needed WMR plus one other platform.  Whether that is Alpha or Beta, I'm not sure.  Point for discussion, What is Alpha?

**Comment by davidkline-ms** [comment]
alpha is the mvp. I was under the assumption (could be bit rot in the brain) that we had planned on mvp being wmr and beta adding another device.

**Comment by davidkline-ms** [comment]
Receiving feedback that having a second platform in alpha will prove that we are serious about cross sdk support.

**Comment by StephenHodgson** [comment]
Agreed, Which second platform makes since? ARKit? We've already got spectator view working in master.

**Comment by davidkline-ms** [comment]
We could do OpenVR, though ARKit would be great (I had it slated for Beta 1)

**Comment by StephenHodgson** [comment]
OpenVR might be a bit easier to test and build now. I don't have access to a Mac

**Comment by davidkline-ms** [comment]
Agreed (also, I do not have a Mac currently)

**Comment by SimonDarksideJ** [comment]
Initial PR raised (#2396) adding OpenVR support (WIP)

**Comment by SimonDarksideJ** [comment]
PR merged and complete. Open build issue (#2437) but that is separate
