### ISSUE TITLE
Task vNext - Create "Default Rig" SDK component

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2249]
## Overview
From the initial "Device" testing, certain issues arose from an incorrectly created "Rig".  As such an SDK component is needed to generate a default "Rig" (Body / Head / etc) for new users.
The default rig can also be used for visual testing of vNext features.

## Requires
* Script to generate a new Rig
* No prefabs should be used, default Unity objects only (as required)
* Should be callable from the Test project

## Acceptance Criteria
- [ ] I can generate a default rig, press play and be able to use a device in a scene
- [ ] I should be able to test the default rig in the Test project
- [ ] Only scripts added as part of the PR
- [ ] Help page created on the use of the Default Rig and explaining it's setup

**Comment by StephenHodgson** [comment]
What about setups that don't need a rig?

**Comment by davidkline-ms** [comment]
This is just setting the camera to 0,0,0 right?

**Comment by SimonDarksideJ** [comment]
This would be a "Create Default", it's **completely optional** and advanced users will likely not use it.
However, beginners, newcomers and prototypers, want a fast / quick way to get up and running and this will enable this.

**Comment by SimonDarksideJ** [comment]
The initial thought @davidkline-ms would be that it would:
* Create a body, centered at 0,0,0
* Remove the main camera, or parent it to the Body, resetting transform to 0,0,0
* Anything else we need as a "Default" for testing

**Comment by StephenHodgson** [comment]
Still think a few of these things should be dynamic.  Essentially a user can make their own rigs, and we just check if the camera has a parent transform and if not, then create one for them if needed.

**Comment by SimonDarksideJ** [comment]
Agreed, users can create their own (and probably should)  but as a starter for 10 (and for our own unit tests), we should a simple, easy to use script (not using Prefabs!)

**Comment by davidkline-ms** [comment]
I believe this is done as part of the Configure menu (parent the main camera to the body object)
