### ISSUE TITLE
PROPOSAL: Body Lock Solver Orientations need to be more usable

### ISSUE THREAD

**Issue by Ecnassianer** [Microsoft/MixedRealityToolkit-Unity#2250]
## Overview

I can't really make heads or tails of the Body Locked Solver's Orientation field, my only conclusion is that its current behavior is some degraded form of the original intention. Correct me if there's an intention I'm missing.

## Actual Behavior

It seems like the "Default" orientation uses the yaw of the tracked object, but not the pitch or roll. This "Default" only makes sense when it is attached to the head and intended as a "utility belt" item that follows an imagined body instead of the head.

It seems like the "CameraFacing" orientation actually aligns the object with the camera, regardless of the object's position (so if it is beside you, it actually faces behind you). It seems like this was intended to be used only when tracking the head (where "aligned" and "facing" are similar in small FOVs), but even then this behavior seems like a broken version of actually facing the camera.

When off, the "Rotation Tether" ignores the orientation field and uses the identity rotation. Turning this off seems useless.

Finally, there's some really wacky behavior when using Tether Angle Steps. In the gif below you can see the current Body Lock behavior (white) with the new stepping behavior I'm proposing (red). It seems like the top step of the Body Lock solver is 180 degrees, while all the other steps are 45 degrees (left and right) and 90 degrees (bottom). I can't think of a case where this would be intended, so I think it is a bug.

![anglestepping](https://user-images.githubusercontent.com/231247/43030767-13dc5e3c-8c4a-11e8-8f56-8c233da04e14.gif)

I'd like to fix these shortcomings. I see two ways forward and would love your feedback. The first is updating these two behaviors to make sense in more general contexts (or even their intended context?!). There is a risk this could break some content if it is relying on the above strange behaviors. Alternatively, we could deprecate the Body Lock Solver entirely, and create a new "Object Locked Solver" with improved and more flexible behaviors. 

I'm leaning toward deprecation.

## Expected Behavior

Regardless of path, I'd like to implement this functionality:

1. Remove "Rotation Tether" entirely, it is redundant with the orientation field.
2. Change "Default" to use the tracked object's pitch, yaw, and roll.
3. Create a new orientation "Unmodified" which doesn't adjust the object's rotation at all.
4. Change CameraFacing to face the camera, regardless of position, rather than align with it.
5. Create a new orientation "CameraAligned" which aligns the object with the camera (or discard this behavior entirely).
6. Create a new orientation "YawOnly" which uses the tracked object's yaw with zero rotation and zero pitch. This replaces the old Default behavior.

If we update in place, we could leave the Default behavior as is, since there are a few cases where it makes sense to use, and create a new "TrackedObject" orientation that respects pitch, yaw, and roll. I'm not sure this is a great "Default" behavior, but it would prevent any content breakages.

**Comment by Ecnassianer** [comment]
As a note, I have a working version of these changes in my team's project that I would be cleaning up for this work. In that case I just fixed the existing behaviors in place because I knew no one was using them.

**Comment by Ecnassianer** [comment]
Pull Request:
https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2480

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
