### ISSUE TITLE
Task vNext - Investigate "Chained Action" controller SDK component

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#2253]
## Overview
As well as individual Input Actions, user will likely want the ability to chain InputActions together for a different result, e.g.  jumping then pressing select as a new action.
To support this a demonstration (or even implementation) SDK component is needed as an example

## Requires
* A new SDK component to demonstrate how to chain actions
* Code documentation
* Supporting user documentation

## Acceptance Criteria
- [ ] A "sample" SDK component that allows several independent actions to form / select another action (e.g. Point, Grab then Hold)
- [ ] A "sample" SDK component that allows several combined actions to form / select another action (e.g. Hold Trigger and Grip)
- [ ] "sample" SDK component that allows several actions from different controllers to form / select another action (e.g. Two handed Grab)
- [ ] Fully documented code describing the implementation
- [ ] Supporting user documentation describing how to chain / combine Input Actions together

**Comment by Yoyozilla** [comment]
@SimonDarksideJ  are you signing up to create this sample SDK :)
