### ISSUE TITLE
Task vNext - Implement  WMR "Gesture" controller

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2254]
## Overview
The existing interactionSources class implemented multiple behaviours, from controllers, to Gestures and navigation.  The Controller interaction has been extracted in to a new controller, the same has to happen for the other elements of the InteractionSources implementation

## Requires
* A new implementation of the Gesture Interaction
* Documentation to support the use / implementation of the Gesture Interaction

## Acceptance Criteria
- [ ] New Gesture Controller (or other refactored "Device") implementation
- [ ] Documentation to support Gesture implementation

**Comment by StephenHodgson** [comment]
See #2708
