### ISSUE TITLE
Task vNext - Implement WMR "Navigation" controller

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2255]
## Overview
The existing interactionSources class implemented multiple behaviours, from controllers, to Gestures and navigation.  The Controller interaction has been extracted in to a new controller, the same has to happen for the other elements of the InteractionSources implementation

## Requires
* A new implementation of the Navigation Interaction
* Documentation to support the use / implementation of the Navigation Interaction

## Acceptance Criteria
- [ ] New Navigation Controller (or other refactored "Device") implementation
- [ ] Documentation to support Navigation implementation

**Comment by StephenHodgson** [comment]
See #2708
