### ISSUE TITLE
Task vNext - Implement Windows Gaming Controllers

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2256]
## Overview
Provide an implementation for Windows Gaming Controllers for vNext

## Requires
* New ArcadeStick implementation
* New GamePad implementation
* New Joystick implementation
* RacingWheel implementation

## Acceptance Criteria
- [ ] Implementation of the WindowsGaming device manager
- [ ] Implementation of the ArcadeStick controller
- [ ] Implementation of the GamePad controller
- [ ] Implementation of the Joystick controller
- [ ] Implementation of the RacingWheel controller
- [ ] SDK detection and initialization of the WindowsGaming device on all supported Unity platforms
- [ ] Configuration to enable the WindowsGaming device in the Mixed Reality Manager

**Comment by Yoyozilla** [comment]
The recommendation is to use the Unity Joystick data provider :)
