### ISSUE TITLE
Task vNext - Define SDK Selector

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2257]
## Overview
Currently, the Mixed Reality manager forces the activation of the selected device (hardcoded)
This mechanism needs to be replaced with the ability to "Auto" select the required / available SDK at runtime.

## Requires
* The ability to detect the platform the project is running on 
* The ability to detect which supported headset / SDK is active
* The ability for the developer to chose / activate SDK's as they see fit

## Acceptance Criteria
- [X] I can target the UWP platform and make devices available
- [X] I can target the UWP platform and run a project for it to be displayed in an Immersive device
- [x] I can target the UWP platform and run a project for it to be displayed on a HoloLens
- [X] I can target the Standalone platform and run a project for it to be displayed on a HTC Vive
- [ ] I can target the Standalone platform and run a project for it to be displayed on an Occuls Rift
- [ ] I can target the Standalone platform and run a project for it to be displayed on a ….
- … Other targets to be defined

**Comment by SimonDarksideJ** [comment]
Default SDK selector implemented in #2437 
To be refined, as it only supports 1-1 currently (1VR platform to 1VR device)

**Comment by StephenHodgson** [comment]
So far in my research, I've found that when enabling XR settings in a project the default SDK is always added for that platform except for Android.

I'm wondering if this is something we should just let users do? But still be able to handle setup when SDK is loaded?

More research and testing is probably needed.

**Comment by Yoyozilla** [comment]
This seems like something Unity should (and currently is) handling. 
MRTK will leverage this, but we are not implementing our own logic here.
