### ISSUE TITLE
Can't scale the DefaultCursor

### ISSUE THREAD

**Issue by StefanNeu** [Microsoft/MixedRealityToolkit-Unity#2262]
## Overview
I have an scalable GUI in my app. Since the GUI can get really small, I also want to scale the DefaultCursor by changing the _transform.localScale_.
## Expected Behavior
The cursor should scale.
## Actual Behavior
It doesn't scale and stays at (1,1,1). If I change the cursor scale in the inspector, it also gets back to (1,1,1) when I press Play. 
Can I deactivate this default setting of the scale?
## Steps to reproduce
https://github.com/StefanNeu/SC2018testing/tree/test/SC2018

## Unity Editor Version
2017.4.2f2
## Mixed Reality Toolkit Release Version
2017.2.1.4

**Comment by StephenHodgson** [comment]
This is because there is a animation that is driving the cursor's transform.

You should be able to make your own cursor and use it as needed.
