### ISSUE TITLE
PointerEventData.InputSource returns null when using pointerdata from new InputSourcePointer.

### ISSUE THREAD

**Issue by swatvel** [Microsoft/MixedRealityToolkit-Unity#2267]
## Overview
Hi,  After switching the pointer from  Gazemanager to  InputSourcePointer (via SimpleSinglePointerSelector)  why is that 
FocusManager.Instance.TryGetPointingSource(PointerEventData eventData, out source);  returns null for source ?
## Expected Behavior

FocusManager.Instance.TryGetPointingSource(PointerEventData eventData, out source);
should return InputSourcePointer 

## Actual Behavior
returns null because PointingSource.OwnsInput implementation checks inputData.inputSource as null and not InteractionInputSource
 ```
public bool OwnsInput(BaseEventData eventData)
        {
            return (OwnAllInput || InputIsFromSource(eventData));
        }

 public bool InputIsFromSource(BaseEventData eventData)
        {
            var inputData = (eventData as IInputSourceInfoProvider);
            return (inputData != null)
                && (inputData.InputSource == InputSource)
                && (inputData.SourceId == InputSourceId);
        }
```
## Steps to reproduce
Right after starting the application in Windows Immersive  Press the select trigger to switch inputsource from gazemanager to InputSourcePointer.
After I have a MonoBehaviour implementing IPointerExitHandler 
```
   public void OnPointerExit(PointerEventData eventData)
    {
        IPointingSource source;
        FocusManager.Instance.TryGetPointingSource(eventData, out source);
        if(source != null)
        {
            FocusDetails focusDetails = FocusManager.Instance.GetFocusDetails(source);
         }
 }
```
Here source is null
## Unity Editor Version

2017.2.1p4

**Comment by StephenHodgson** [comment]
Because the pointer is always being updated by the focus manager, the context for the current pointer may have already moved on if you switched from one pointer to the other.

Multiple pointers aren't supported in this branch very well, but vNEXT has full support.

**Comment by swatvel** [comment]
ok Thanks. If that is the case why is that 
public PointerInputEventData GetGazePointerEventData()
        {
            return gazeManagerPointingData.UnityUIPointerData;
        }

returns always UI data of gazemanager instance  and not inputsource pointer's ?

**Comment by StephenHodgson** [comment]
Because there wasn't a nice way to get ui raycasts with any pointers at first, and we used to only have a single pointer, your gaze.

The current system was written for HoloLens, initially, and we've done a major overhaul in vNEXT to support multiple pointers. That work should be done in the next few weeks/months

**Comment by swatvel** [comment]
Ok thanks for the quick response.

**Comment by StephenHodgson** [comment]
In the mean time, just checking null is probably the safest thing.

But realistically the pointer that's getting deactivated should call in pointer exit before being unregistered.

**Comment by swatvel** [comment]
For now can I just return the pointers[0].UI data and set its input source at the time of raycastingUnityUI ?

**Comment by StephenHodgson** [comment]
No because you'll be getting the UI raycasts for the wrong pointer.

**Comment by StephenHodgson** [comment]
> the pointer that's getting deactivated should call on pointer exit before being unregistered.

**Comment by swatvel** [comment]
Ok .I will wait for the vNEXT thanks so much .

**Comment by fh35553eh** [comment]
Hello Guys, Do you know what is the API which is could connect between **Unity** and **Whatsapp**??
thanks you a lot T^T...

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
