### ISSUE TITLE
HoloToolkit option in the main menu not visible

### ISSUE THREAD

**Issue by MyCheese** [Microsoft/MixedRealityToolkit-Unity#2270]
I'm using the Unity 2018.1 version and when I imported the HoloToolkit packages, I ran into some errors. Eeverything except this was fixed - Assets/HoloToolkit/BuildAndDeploy/Editor/BuildSLNUtilities.cs(145,44): error CS0029: Cannot implicitly convert type UnityEditor.Build.Reporting.BuildReport' tostring'
Please let me know how to go about it and solve it? Thank you.

I'm using the 2017.4.0.0 version of the HoloToolkit.

**Comment by keveleigh** [comment]
Fixed via #2127, which made its way into in the most recent release.
