### ISSUE TITLE
Warnings importing MRTK packages

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#2271]
## Overview
Importing MRTK packages Unity shows these warnings:
![image](https://user-images.githubusercontent.com/17752475/41143236-db081708-6af8-11e8-88e3-2e86e00ef6ce.png)

## Expected Behavior
No warnings
## Actual Behavior
Warnings
## Steps to reproduce
Import MRTK packages

## Unity Editor Version
2017.4.2f2
## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by StephenHodgson** [comment]
While we do our best to remove as many of the Build warnings and others, many of the line endings and fbx import warnings can be ignored.

We will be sure to clean these up as soon as possible.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
