### ISSUE TITLE
HandDraggable script shake object when moving head.

### ISSUE THREAD

**Issue by Krazyxx** [Microsoft/MixedRealityToolkit-Unity#2272]
## Overview
HandDraggable shake object when we have grab the object and we move head. (Seems to be shaking too with only dragging by hand).
It's only the case when you have a high value of PositionLerpSpeed.
The results of the tests carried out:
 - With PositionLerpSpeed value of 0.9 and 1 → object is shaking
 - With default PositionLerpSpeed value (0.2f) → Expected Behavior (without shaking)

## Expected Behavior
Moving object without shaking.

## Actual Behavior
Moving object with shaking.

## Steps to reproduce
1. Create a new scene
2. Set up the scene with the MRTK configuration (Mixed Reality Toolkit > Configure > Apply Mixed Reality Scene Settings)
3. Create a cube, add "HandDraggable" component and set the value PositionLerpSpeed to 1. (Of course, place the cube in front of you → e.g. : Position (0, 0, 2) and Scale (0.25, 0.25, 0.25)).
4. Build on HoloLens and launch it.
Now, try moving your cube with your hand while moving your head.

## Unity Editor Version
2017.1.0f3

## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
