### ISSUE TITLE
Teleport active also clicking down the thumbstick

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#2279]
## Overview
The teleport is active also clicking down the thumbstick.
## Expected Behavior
Same as in the mixed reality home
## Actual Behavior
With MRTK the teleport is active also clicking down the thumbstick.
In the mixed reality home clicking down on the thumbstick and holding you can virtually walk.
More details here:https://docs.microsoft.com/en-us/windows/mixed-reality/navigating-the-windows-mixed-reality-home#teleport
Is it possible to align the behavior of the MRTK with the mixed reality home?
As first step it would be nice to disable the teleport when we click down the thumbstick and then, as second step, implement the virtual walk.
## Steps to reproduce
Any example scene with teleport
## Unity Editor Version
All
## Mixed Reality Toolkit Release Version
All

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
