### ISSUE TITLE
vNext: Basic controller test scene

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2280]
Alpha release needs a basic controller test scene to allow users to confirm that input is working. Simple cubes is sufficient.

**Comment by StephenHodgson** [comment]
@SimonDarksideJ didn't you already have something along these lines? Or did we remove it before the initial controller implementation PR?

**Comment by davidkline-ms** [comment]
It got removed from the PR.

**Comment by SimonDarksideJ** [comment]
Will create a proper "nice looking" test scene.  But we'll need some basic interactions, visible pointers and probably a cursor for that 🗡

**Comment by davidkline-ms** [comment]
replaced by the basic intro scene #2514
