### ISSUE TITLE
JSON and AssetBundle reading with Hololens

### ISSUE THREAD

**Issue by DPbruno** [Microsoft/MixedRealityToolkit-Unity#2281]
## Overview
I made a project using the first edition of Holotoolkit, at this project I used a JSON file to get some text information's form my server and it was working fine. Recently I updated my project to use the MRTK, I test the project at Unity Editor and everything worked well but when I compile to Hololens the project didn't worked. I made some test to figured out where was the problem, and I the problem is related to the momentum where my code get the information of the JSON file. 

At the first test I used Unity 2017.4.4f1 and the MRTK 2017.4.0.0, the download and save was working perfect, the Hololens don't report a bug just stay loading when I use a Webrequest to get a JSON file form my local folder. I also tested the WWW instead of Webrequest, and the NewtonSoft.Json instead of JsonUtility, and the result was the same. 

![image](https://user-images.githubusercontent.com/40034413/41248513-aa3e5d12-6d87-11e8-8a06-cea9ff3a081a.png)

At the second test I used the Unity 2017.2.1p2 and the MRTK 2017.2.1.4, and the JSON reading worked fine - with the same code and configuration that I was using with Unity 2017.4. But with Unity and MRTK 2017.2  I had problems to open my AssetBundle from a local folder, what is working perfect at Unity Editor. The hololens throw this error: **Serialized file contains typetrees but the target can't use them. Will ignore typetrees.**

![image](https://user-images.githubusercontent.com/40034413/41248887-b9af5854-6d88-11e8-82c2-8bd32f787053.png)
    
## Expected Behavior
Read the JSON file with the MRTK 2017.4 and open the Asset Bundle with the MRTK 2017.2

## Actual Behavior
Do nothing when I tried to read a JSON file with the MRTK 2017.4 at Hololens (but worked at Unity Editor). And throw a error when a tried to open a local Asset Bundle with MRTK 2017.2. 

## Unity Editor Version
2017.4.4f1 and 2017.2.1p2

## Mixed Reality Toolkit Release Version
2017.4.0.0 and 2017.2.1.4

**Comment by StephenHodgson** [comment]
I'm not sure that this issue is related to the MRTK.

**Comment by StephenHodgson** [comment]
>Serialized file contains typetrees but the target can't use them. Will ignore typetrees.

This is because you generated the asset bundles with the wrong build target.

**Comment by DPbruno** [comment]
And the first scenario, where I could not read the JSON?
