### ISSUE TITLE
Plane finding api for hololens help

### ISSUE THREAD

**Issue by Shubham7694** [Microsoft/MixedRealityToolkit-Unity#2284]
## Overview
How does the min area specified for Plane Finding api work. I need to understand the parameter function in better way.
## Expected Behavior
if i increase the min area, only bigger chunks of floor/wall must be detected and vice-a-versa.
## Actual Behavior
Increasing the area actually produces offset where planes, specificially floor are getting detected with some unacceptable level of offset.
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
Unity 2017.2.1p4

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
