### ISSUE TITLE
Compile errors on Android target

### ISSUE THREAD

**Issue by kayy** [Microsoft/MixedRealityToolkit-Unity#2286]
## Overview
When switching to Android for example, DictationInputManager.cs shows 3 errors in Unity:
CS0103	The name 'dictationRecognizer' does not exist in the current context
...

## Expected Behavior
No errors to enable multiplatform development

## Actual Behavior
3 errors, in DictationInputManager.cs, line 210 - 216

## Steps to reproduce
Just import the MRT-Unity and the MRT-Unity-Sample project. Switch to Android
I fixed it by surrounding the method body with `#if UNITY_WSA || UNITY_STANDALONE_WIN` and a `yield break;` in the `#else` case.

## Unity Editor Version
2018.1

## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by keveleigh** [comment]
This sounds like the issue that was resolved in https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2275

**Comment by kayy** [comment]
Yes this sounds great. Sorry for inconvenience I searched for _DictationInputManager_ only but not for the method name

**Comment by keveleigh** [comment]
No worries! Thanks for filing the issue!
