### ISSUE TITLE
Proposal: Should we use SpatialEntityStore for Sharing experience?

### ISSUE THREAD

**Issue by rigma** [Microsoft/MixedRealityToolkit-Unity#2292]
## Overview
Recently when I was browsing on the UWP documentation, I found that the import and export of spatial anchors for collaboration experiences has been [deprecated](https://docs.microsoft.com/en-us/uwp/api/windows.perception.spatial.spatialanchortransfermanager#remarks). Instead, the actual documentation is suggesting to use the [`SpatialEntityStore`](https://docs.microsoft.com/en-us/uwp/api/windows.perception.spatial.spatialentitystore) instead of the old `SpatialAnchorTransferManager` that I suspect Unity to use under the hood.

I wonder why this new method that you suggest is not yet used here, on a Microsoft open-sourced project. Shouldn't we try to use this new method in the `Sharing` part of HoloToolkit or is Unity will implements this new method instead of the actual `WorldAnchorTransferBatch`?

**Comment by timGerken** [comment]
Speculation: I would suspect the reason is that most HoloLens devices in the wild are still on OS version 10.0.14393 and the SpatialEntityStore wasn't introduced until 10.0.15063 (Windows 10 Creator's update). Once HoloLens moves to 10.0.17134 (RS4), the SpatialAnchorTransferManager can finally be finally deprecated.

**Comment by rigma** [comment]
But can't we start to implements this new way of sharing anchors right now, or should we wait until Windows Holographic is updated to the right version on most HoloLens devices?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
