### ISSUE TITLE
Interactive mesh cursor default distance set to 0

### ISSUE THREAD

**Issue by rigma** [Microsoft/MixedRealityToolkit-Unity#2294]
## Overview
As you may know, the HoloLens cursor is following the surface of a box collider by default when it can or it will remain at a default distance otherwise: with the interactive mesh cursor behavior, it's not the case.

When we go anywhere other than a surface of a collider, the interactive mesh cursor is renderer at a distance of 0 with the camera. In other words, we can't see it. And that have a huge bad impact with the UX when using an application using this cursor.

## Expected Behavior
The cursor's distance with the camera is set to the default distance when it's not on a collider surface.

## Actual Behavior
The cursor is rendered on the camera position.

## Steps to reproduce
1. Sets up a Unity project for an HoloLens application
2. Place a new Cube in the scene
3. Use the InteractiveMeshCursor as your cursor

This [project](https://github.com/rigma/InteractiveMeshCursor-Bug) is a reproduction of this issue.

## Unity Editor Version
2018.1.0f2

## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by rigma** [comment]
Okay... A little update here, when I try to reproduce the bug with an example scene with the current June release, it did not appear. So I think it was fixed... I suppose.

I think the issue was coming from the fact that a previous attirbute of `Cursor`, `originalDefaultCursorDistance`, was initialized to 0 and, therefore, the `DefaultCursorDistance` attribute was set to 0 as well. Apparently, this attribute is not used anymore so the issue is no more I suppose.

Am I right? Or does anyone had reproduce the bug?

**Comment by keveleigh** [comment]
The `originalDefaultCursorDistance` attribute you refer to was added [15 days ago](https://github.com/Microsoft/MixedRealityToolkit-Unity/blame/master/Assets/HoloToolkit/Input/Scripts/Cursor/Cursor.cs#L134), in the May release. I'm not sure what could be causing this, unless `DefaultCursorDistance` in the inspector was inadvertently set to 0.

I'm unable to repro this in any of the last two Toolkit releases.

**Comment by keveleigh** [comment]
Aha!

> because it seems that the Awake method of the Cursor class is not called

This is the issue. InteractiveMeshCursor has its own `Awake()`, which hides the base `Awake()`. We'll need to update the Cursor's `Awake()` to be `protected virtual` and override it in InteractiveMeshCursor. I have it fixed in my fork, so I can put out a PR (unless you have one ready!).

**Comment by rigma** [comment]
You were too quick for me! Go ahead!

**Comment by rigma** [comment]
It works @keveleigh 👌
