### ISSUE TITLE
Loading cursor not visible when we are off-holograms

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#2297]
## Overview
The loading cursor is not visible when we are off-holograms
## Expected Behavior
The loading cursor is visible also when we are off-holograms
## Actual Behavior
If the input is disabled the loading cursor is not visible when we are off-holograms because it is too far.
I think it would be better if the loading cursor is always visible when the input is disabled
Something like this (Cursor class):
```
// If no game object is hit, put the cursor at the default distance
if (newTargetedObject == null)
{
    TargetedObject = null;
    TargetedCursorModifier = null;

    if (pointerIsInputSourcePointer)
    {
        // This value get re-queried every update, in case the app has
        // changed the pointing extent of the pointer for the current scenario.
        float distance = FocusManager.Instance.GetPointingExtent(Pointer);
        if (DefaultCursorDistance != distance)
        {
            DefaultCursorDistance = distance;
        }
    }
    else if (DefaultCursorDistance != originalDefaultCursorDistance)
    {
        DefaultCursorDistance = originalDefaultCursorDistance;
    }

    targetPosition = RayStep.GetPointByDistance(Pointer.Rays, InputManager.Instance.IsInputEnabled? DefaultCursorDistance : originalDefaultCursorDistance);
    lookForward = -RayStep.GetDirectionByDistance(Pointer.Rays, DefaultCursorDistance);
    targetRotation = lookForward.magnitude > 0 ? Quaternion.LookRotation(lookForward, Vector3.up) : transform.rotation;
}
```
## Steps to reproduce
- InputManagerTest scene 
- Click timer button
## Unity Editor Version
2017.4.2f2
## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by keveleigh** [comment]
Ahh, good point. I hadn't considered the loading state, only the targeting state.

Something like your proposed fix seems like a good solution, though perhaps caching `InputManager.Instance` so we don't ask for it each frame.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
