### ISSUE TITLE
Add metal and smoothness texture maps to mrtk standard shader options

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2298]
## Overview
Currently the metal and smoothness maps need to be embedded into the albedo texture, but then that limits the ability to use transparency in the albedo alpha.

Adding the metal and smoothness texture slots will give developers greater flexibility in creating materials.

**Comment by Cameron-Micka** [comment]
This shouldn't be too hard to add, I would be worried about enabling these features on HoloLens for perf reasons. But, with IHMDs it should be fine. I'm a tad busy right now, but can add this in the coming weeks!

**Comment by jerrygg** [comment]
Has there been any progress on that front?

**Comment by Cameron-Micka** [comment]
I haven't had a chance to start this yet, but I agree I will make sure to merge all latest changes to vNEXT. I also have a few other enhancements I would like to integrate into the MRTK from our local version.
