### ISSUE TITLE
Can I show two cameras on one camera?

### ISSUE THREAD

**Issue by KiDeokKim** [Microsoft/MixedRealityToolkit-Unity#2302]
## Overview
I want to output a view of another camera(non VR Camera) in one camera(HMD).
##
At the same time ,i need VR camera is showing Non VR Camera. Like Z-index in CSS.
i'm setting Player settings value - Virtual reality Supported : checked , and platform is UWP(Universal windows platform).
and One camera(VR Camera, 'MixedRealityCamera') depth value is '-1' and target eye is 'both' , another camera(Non VR Camera) depth value is '0' and target eye is 'none(Main Display)'
if i change Viewport Rect value, Unity editor is showing 2 camera view.
but if i wearing HMD Camera, not visible.
how can i showing two cameras, if i wearing HMD, at the same time???

## Unity Editor Version
2017.3.1.f1
## Mixed Reality Toolkit Release Version
Latest

**Comment by Ecnassianer** [comment]
I'm not sure exactly what you're asking for, but there are a few things that come to mind that you might be looking for.

If you're trying to get two camera perspectives to render in the same HMD (one in each eye?) you're probably not going to end up with something very desirable. This might work for a debug mode, but it will cause simsickness and eye strain in your users. If you're sure this is what you want, can you explain more about what you're using it for?

A much better approach would be to use Unity's Render Texture functionality to render one camera to a texture. Some people use this for security cameras in video games. One camera records the VR scene and then renders it to a render texture that is on a virtual TV in the game. The HMD user can look at the texture and they can see what the first camera is looking at (albeit, in 2D). Here's a tutorial on how to do this in Unity: https://www.youtube.com/watch?v=pA7ZC8owaeo

And finally, it might be that what you're looking for is a "VR spectator camera" (not be confused with the Mixed Reality Companion Kit's [SpectatorView](https://github.com/Microsoft/MixedRealityCompanionKit/tree/master/SpectatorView) or MRTK's [SpectatorView](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit-Preview/SpectatorView), which are intended to overlay AR holograms on video footage from other devices). The idea behind a VR spectator camera is that the VR user sees through one camera and another person looking at the monitor sees through a different camera (for instance, and overhead view that looks down at the VR player).

A lot of "asymmetric multiplayer" VR games use cameras like this in Unity, and you can find many different techniques searching for those terms on Google. This relatively simple guide shows you how to create spectator cameras using only standard Unity tools:
https://blogs.unity3d.com/2017/12/12/spectating-vr/

**Comment by KiDeokKim** [comment]
Thanks to your comment.
first, i was used Render Texture(child of VR Camera. So followed camera's gaze). but, it is not my intention.  In a similar way, if you're wearing glasses, like something on your glasses.(glasses = HMD , something = Non VR camera)
maybe This is similar to what I was about to do. but it is some different my intention. : https://youtu.be/p_4xfhelak8
as above(few difference), small view camera is just gaze an object from top to bottom. but camera is fixed and follow VR camera(As I mentioned above, like something on your glasses).
sorry about my english speaking. are you understand..?

**Comment by Ecnassianer** [comment]
So you're trying to do something like a scifi robot point of view? Like this:

![captura de pantalla 2013-06-21 a las 13 23 32](https://user-images.githubusercontent.com/231247/41428315-891b8bd0-6fbe-11e8-9473-9992b220b8dd.png)

Putting that close up image in 2D is going to be unpleasant for users. You should really position it in 3D space on a render texture. Consider having the render texture use an MRTK solver to track the head. That will give it nice smooth movement. It will also look cool if you curve the surface the render texture is on.

> another camera(Non VR Camera) depth value is '0' and target eye is 'none(Main Display)'

This is the reason your second camera doesn't display anything in the HMD. By setting the camera to 'none(Main Display)' you're telling Unity to only render that image to the Main Display, and not the HMD. You can set both cameras to Target Eye: Both, but I don't that's really what you want. Here's an example of what that looks like:

![twocams](https://user-images.githubusercontent.com/231247/41428727-cbebd7fc-6fbf-11e8-85d3-c54b716a979d.PNG)

You see the floor twice, each one offset by where the camera is located. Both cameras track the HMD direction.

**Comment by Ecnassianer** [comment]
Oh, maybe I understand now. 

Is this what you want?
- The HMD displays a normal VR view, like regular VR apps show.
- The computer monitor shows an overhead view (or whatever not moving view)
- In the corner of the screen on the computer monitor there is a little box that shows what the HMD user is seeing

In that case, I'd actually use 3 cameras. The default Mixed Reality Camera, one normal unity camera targeting Display 1, None (Main Display), and a second normal unity camera that is attached to the Mixed Reality Camera, and is targeting Display 1, None (Main Display). The second unity camera can use depth only, or Viewport Rects or whatever you want to do to overlay it on the first unity camera.

**Comment by KiDeokKim** [comment]
I don't know if I understand exactly, maybe it's close. but, i'm not using computer monitor. read title - show two cameras on one camera(HMD) 
- The HMD displays a normal VR view, like regular VR apps show. (correct)
- VR view shows an overhead view(In the corner of the VR view).but overhead view is always in my front(So i say that **look like something is attached to my glasses**) and not moving(not tracking)

i'm using UWP(Universal windows platform). it it helpful for understand?

**Comment by Ecnassianer** [comment]
Ok, I understand you now. This threw me off: "but, scifi robot point of view is My HMD, and background is non vr camera."

It's what I first thought. You're not going to get good results of out rendering two cameras to the same HMD display. You should use a render texture that follows the user's head, either with a solver or parented. 

You can use Culling Masks on the non-VR camera if you just want to render the cylinder and nothing else. Then the render texture won't look like a rectangle, it will just be a cutout of your cylinder.

**Comment by KiDeokKim** [comment]
So.... is it possible that i was trying? I'll tell you why I'm trying to do this.
if render texture's distance is 2 , and another object's distance is 1. and that is collinearity(same line more explanation : A position[0,0,2] , B position[0,0,1] ). so render texture is hidden behind another object (can't see render texture). so i tried depth cam, but it is not show render texture...

**Comment by Ecnassianer** [comment]
I don't think the method you're suggesting is possible enough to continue exploring.

Here are two alternatives:
1) There's something called "stereo layers" that solve the depth problem you're talking about. I'm not very well versed in stereo layers, so I can't really help with them, but I've used them for UI in Unreal, but in my experience they are kind of poorly supported, and each platform (Vive, Oculus, etc) handles them differently. An element in a stereo layer renders on top, no matter what, even if it is "behind" some other object. The steam menu overlay is in a stereo layer, if you've seen that. 

2) Generally users don't like putting their faces inside of things. If your render texture is comfortably viewable close to your face (1-2 feet?) I suspect users won't put it inside of many things (depending on the content I guess). You can also look into putting an MRTK surface magnetism solver and a radial view solver to better deal with collisions. I redid the SolverExamples map in my personal fork, and it has a good example of this, if you want to clone it:
https://github.com/Ecnassianer/MixedRealityToolkit-Unity/blob/SolverExampleUpdates/Assets/HoloToolkit-Examples/Utilities/Scenes/SolverExamples.unity

**Comment by KiDeokKim** [comment]
I didn't find what I wanted, thanks to your comment. maybe i'm going to using render texture.
have a nice day.
