### ISSUE TITLE
Unexpected behavior with SpatialProcessing and plane destruction

### ISSUE THREAD

**Issue by radicalad** [Microsoft/MixedRealityToolkit-Unity#2304]
## Overview
The SurfacePlanes prefab is destroyed and redrawn every frame when "Floor" is ticked on in the Destroy Planes dropdown.

## Expected Behavior
The Floor planes would be ignored and all other planes are saved.

## Actual Behavior
Objects skate along planes due to the fact the SurfacePlanes (and child objects) are destroyed and recreated.

## Steps to reproduce
Set up a standard HoloLens scene using SpatialMapping and SpatialProcessing.
Set Destroy planes to "Floor"

## Unity Editor Version
2017.2.1.p2

## Mixed Reality Toolkit Release Version
Current commit on master branch of MRTK

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
