### ISSUE TITLE
`UnityEngine.XR.WSA.WorldManager' does not contain a definition for `state'

### ISSUE THREAD

**Issue by shelbyd** [Microsoft/MixedRealityToolkit-Unity#2307]
## Overview
When building from the command line on linux, compilation fails with: `'UnityEngine.XR.WSA.WorldManager' does not contain a definition for 'state'`
https://nofile.io/f/50UD7XFYSqG/build_1023_step_104_container_0+(1).txt

## Expected Behavior
Project compiles as normal from development PC.

## Actual Behavior
Compilation fails.

## Steps to reproduce
Not verified:
1. Use Ubuntu 14.04
2. Download Unity 2018.1.3f1 (https://beta.unity3d.com/download/093b6115f8df/UnitySetup-2018.1.3f1)
3. Execute the Unity file with " --components=Unity,Windows-Mono"
4. Create a script checking WorldManager.state
5. Build game from the command line

## Unity Editor Version
2018.1.3f1

## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by shelbyd** [comment]
I'm aware I'm using an unsupported version of Unity. This works on my local (Windows) development machine, but not on my build machine. Even with the unsupported version of Unity.

**Comment by keveleigh** [comment]
Which script throws that error? Your link doesn't work for me.

**Comment by keveleigh** [comment]
Ahh, okay! Sounds like this is a Unity bug then, possibly specific to their Linux build. The steps to file a bug with Unity can be found at https://unity3d.com/unity/qa/bug-reporting

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
