### ISSUE TITLE
Sharing with remote hololens not working

### ISSUE THREAD

**Issue by dangnlg2** [Microsoft/MixedRealityToolkit-Unity#2309]
## Overview
Sharing experience between 2 hololens from different wifi network/location is not working. The first hololens create a session called "DefaultSession", but the other hololens cannot find and join the same session. Sharing service shows both hololens connected to "DefaultSession" on the server. Sharing service is hosted on a server which both hololens are connected to. Am able to join "DefaultSession" from PC using Session Manager, but cannot join "DefaultSession" with 2nd hololens.

## Expected Behavior
Second hololens should be able to discover and join the session created by the first hololens.

## Actual Behavior
Second hololens shows up as connected on Sharing Service and SessionManager, but cannot discover or join "DefaultSession" within the hololens application.

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2017.3.1p1
## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by lexiconcreation** [comment]
Facing the same issue..
Any updates on this

**Comment by Yoyozilla** [comment]
Bulk closing older HTK bug. Please reopen if you can repro this issue in MRTK v2. 

We are building the updated sharing support on MRTK V2. 
Thanks!
Yoyo
