### ISSUE TITLE
SpatialUnderstanding.cs limits scanning to one time, any reason for this?

### ISSUE THREAD

**Issue by izatar** [Microsoft/MixedRealityToolkit-Unity#231]
This code checks if the scanstate is "None", but there I see no way to the state back to "None" after scanning, since when finished it is set to "Done".

```
public void RequestBeginScanning()
        {
            if (ScanState == ScanStates.None)
            {
                ScanState = ScanStates.ReadyToScan;
            }
        }
```

By removing this limitation, I am able to run the scanner as many times as I wish with no issues.  So unless there is some reason to have this limitation, I think this should be changed to allow to do another scan after state was set to "Done".

**Comment by NeerajW** [comment]
So you recommend adding an || condition? Seems reasonable.
@jevertt any thoughts?

**Comment by jevertt** [comment]
I'm not certain that this would be the only required change to reset back to the start state. Having a else block that does a reset seems reasonable.

**Comment by davidkline-ms** [comment]
We should continue to investigate this.

**Comment by Holo-Krzysztof** [comment]
I've done what @izatar suggested and it does seem to work indeed. 
However, I'm not sure about the state on the Unity side of things; the native DLL does seem to reset the play space when calling `PlaySpaceInfos_W::InitProcess` (see [here](https://github.com/Microsoft/MixedRealityToolkit/blob/6e72ca9734387757ae079670f04b46f708be6013/SpatialUnderstanding/Src/PlaySpace/PlaySpaceInfos_W.cpp#L1451)).

I'll continue to look at SpatialUnderstanding.cs and report back.
Also, better documentation (or any) for SpatialUnderstanding.dll would be a godsend.

**Comment by Holo-Krzysztof** [comment]
Alright, only resetting the state is not enough; when doing a few scans in a row memory usage increases, which means either native side or the managed wrapper don't free their memory somewhere.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
