### ISSUE TITLE
Change AppBar Icon

### ISSUE THREAD

**Issue by brean** [Microsoft/MixedRealityToolkit-Unity#2310]
## Overview
I don't know if it is even possible with the current implementation, but I like to change the icon for the Hide, Adjust, ...-Buttons in the AppBar to show Sprites instead of the UIButtonSquareIcon-Mesh. 
You can set the "Overwrite Icon" Flag after the buttons are created (in play mode) of the CompontButtonIcon of the Button instance, but they get destroyed after exiting play-mode.

## Expected Behavior
You should be able to overwrite the Button icons in the Inspector somehow, e.g. by configuring the profile for the AppBar-Prefab

## Actual Behavior
There is no way (at least I found none) to change the Mesh to Sprite

## Steps to reproduce
Try to change the Icon of an AppBar-Button

## Unity Editor Version
2018.1f1

## Mixed Reality Toolkit Release Version
june18_dev

**Comment by StephenHodgson** [comment]
Why not just make your own prefab?

**Comment by brean** [comment]
Oh, I have not thought of that. So I just created my own ButtonHolographicSprite prefab based on ButtonHolographic prefab, I can overwrite the icon in the icon-settings and set a sprite there but then every Button has the same icon. I can create my own ComponentIconButton-Script that uses Sprites but I think there should be a checkbox in the ComponentButtonIcon so it looks in the profile if there is a sprite set for this button.

**Comment by brean** [comment]
I tried implementing this but I don't know how to get the icon name (e.g. "Adjust" to do the icon lookup in the profile) in the SetIconName-function of CompoundButtonIcon.

**Comment by brean** [comment]
OK, I have a working version now, as described with a simple checkbox "Use Prefab from Profile" as well as ~10 lines of code. It is an extension to the CompoundButtonIcon as well as the AppBar. 
I can provide a PR, I am not sure on what branch? (I am currently working on june18_dev)

**Comment by StephenHodgson** [comment]
Thanks @brean, I think it would be a wonderful addition. Looking forward to your PR.

**Comment by ThomasAstrakhan** [comment]
> I tried implementing this but I don't know how to get the icon name (e.g. "Adjust" to do the icon lookup in the profile) in the SetIconName-function of CompoundButtonIcon. (The name is always "ObjectCollectionScatter", with the comment Replace with your custom icon texture name in HolographicButton prefab so this should be replaced in code? - But then I have to provide my own AppBar.cs

I had to modify my Appbar.cs because of this. How did you manage to solve this issue ?
