### ISSUE TITLE
Can we restrict the mesh to be used in Plane (floor) finding API?

### ISSUE THREAD

**Issue by Shubham7694** [Microsoft/MixedRealityToolkit-Unity#2311]
## Overview
As we move around, the Hololens saves meshes from vast areas. This inturn means that if i want to detect floor correctly, a mesh covering huge area is used to detect which offsets floor average height from actual floor. How can we restrict to compute floor based on meshes from near by or restrict it from using previously scanned mesh (which accumulate offset over period of time).
## Steps to reproduce
_(Links to sample github project preferred)_

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
