### ISSUE TITLE
Hide AppBar Menu background when not focused

### ISSUE THREAD

**Issue by brean** [Microsoft/MixedRealityToolkit-Unity#2313]
## Overview
The "Show Menu"-Menu is always visible, in the Holograms-App it disappears after some time when it is not focused.

## Expected Behavior
The menu should hide after some time and reappear when the user gazes at it (same as the Holograms-App)

## Actual Behavior
The menu is always visible

## Mixed Reality Toolkit Release Version
june2018_dev

**Comment by brean** [comment]
I created something: https://gist.github.com/brean/a4de7b41b5f3375b6005336b03d95bd3
This does not work because if I set the background to transparent the text is not shown.
Also this script needs access to the background from AppBar, so I added a getter:
```
        public GameObject BackgroundBar {
            get {
                return backgroundBar;
            }
        }
```

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
