### ISSUE TITLE
Does world anchor store return anchors from all spaces or the current space of user?

### ISSUE THREAD

**Issue by Shubham7694** [Microsoft/MixedRealityToolkit-Unity#2320]
## Overview
We query world anchor store api to get all identifiers. Does it return identifiers only for the space we are in or all identifiers from device? [ seems like the latter option but want to validate.]

**Comment by Shubham7694** [comment]
@StephenHodgson Can you answer this! Thanks in advance

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
