### ISSUE TITLE
MotionControllerVisualizer.cs

### ISSUE THREAD

**Issue by ibrahims123457** [Microsoft/MixedRealityToolkit-Unity#2323]
## Overview
I am getting an error everytime I try and build with the holotoolkit in my project. It keeps telling me `Assets\HoloToolkit\Input\Scripts\Utilities\MotionControllerVisualizer.cs(339,44): error CS1729: 'DataReader' does not contain a constructor that takes 1 arguments` 

## Expected Behavior
Build project successfully

## Actual Behavior
Build fails
## Steps to reproduce
_(Links to sample github project preferred)_
Just add the holotoolkit to a project. Don't even have to use any of its features.

## Unity Editor Version
Unity 2018.1.4f1 Personal (64bit)

## Mixed Reality Toolkit Release Version
I tried 2017.2.1.4 and 2017.4.0.0

**Comment by keveleigh** [comment]
I'm unable to repro this. Which SDK are you using to build?

![image](https://user-images.githubusercontent.com/3580640/41749250-3ba49994-756a-11e8-93a1-f4edd6a78321.png)

**Comment by StephenHodgson** [comment]
If you're still seeing this issue, please update with repro steps and reopen.
