### ISSUE TITLE
Mesh transform not preserved when used as room model

### ISSUE THREAD

**Issue by byhag** [Microsoft/MixedRealityToolkit-Unity#2324]
## Overview

When running in the Unity Editor, children of the Room Model `GameObject` in `ObjectSurfaceObserver` are all rotated and translated to `(0, 0, 0)` rather than preserving the transform.

## Expected Behavior

Below shows the transform of one of the Room Model meshes and how it should be positioned relative to the other meshes.

![image](https://user-images.githubusercontent.com/5489050/41735379-1ce12e5c-754f-11e8-8597-14059f0b62f6.png)

![image](https://user-images.githubusercontent.com/5489050/41735458-5daa38a2-754f-11e8-9d83-c100f3bc0fa7.png)

## Actual Behavior

The mesh transform is not preserved when used as Room Model.

![image](https://user-images.githubusercontent.com/5489050/41735250-d20ad018-754e-11e8-9baa-196c3f6c59ea.png)

![image](https://user-images.githubusercontent.com/5489050/41735503-7a419f1e-754f-11e8-98f9-b818cd9b404c.png)

## Steps to reproduce

- Add `SpatialMapping` prefab to scene
- Parent several room mesh objects to `GameObject` to be used as Room Model with relative transform offset from the parent
- Set Room Model
- Hit Play
- Check the rotation of the `roomMesh` objects parented to the `SpatialMapping` object

## Unity Editor Version

`Unity 2017.3.0f3`

## Mixed Reality Toolkit Release Version

`2017.2.1.4`

**Comment by keveleigh** [comment]
Thanks for reporting this. I just opened https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2325 with a fix. Please take a look and make sure it resolves your issue. Thanks!
