### ISSUE TITLE
BoundaryManager RenderBoundary Property Cannot Control Rendering of Mixed Reality Portal Boundary

### ISSUE THREAD

**Issue by jerrygg** [Microsoft/MixedRealityToolkit-Unity#2326]
## Overview
BoundaryManager RenderBoundary Property Cannot Control Rendering of Mixed Reality Portal Boundary
## Expected Behavior
Control Rendering of Mixed Reality Portal Boundary
## Actual Behavior
Cannot Control Rendering of Mixed Reality Portal Boundary

## Unity Editor Version
2017.4.3f1
OS  Win10 17134.112
windows SDK  17134 
## Mixed Reality Toolkit Release Version
MixedRealityToolkit-Unity Master

**Comment by keveleigh** [comment]
This may be a Unity bug / unimplemented feature. I'm not sure if this API ever worked on WMR.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
