### ISSUE TITLE
Add Bluetooth mouse pointing source

### ISSUE THREAD

**Issue by dimatomp** [Microsoft/MixedRealityToolkit-Unity#2330]
## Overview
A Bluetooth mouse as an input source could be a nice extension to Gaze and Gestures on HoloLens (and maybe also on other MR devices, but I cannot be sure about them). The logic could be as follows:
* When mouse is not used, the cursor points at center of the screen.
* When a mouse is connected and a move/button event occurs, cursor stops following the Gaze and changes its position further according to mouse, like in Windows Holographic shell.
* Move and Navigation for mouse can also be implemented.
* When the mouse appears to be inactive for >2sec, cursor gets back to center of the screen and follows the Gaze.

As far as I understood it, `CustomInputSource` is intended for Editor debugging purposes only, but if the above or similar functionality is already implemented, I will be glad to hear about it.

## Implementation details
According to my observations, `UnityEngine.Input.mousePosition` produces invalid and huge numbers on device; looks like the implementaion should use UWP classes directly.
The corresponding input source can rely on another pointing source and produce pointing input as well:
```
class MouseInputSource: BaseInputSource, IPointingSource
{
    [SerializeField] private GameObject basePointingSource;
    [SerializeField] private float inactivityTimeout = 2;

    // ...
}
```

**Comment by StephenHodgson** [comment]
Mrtk vNext will definitely support spatial mouse input similar to the shell

**Comment by dimatomp** [comment]
@StephenHodgson Great news, looking forward to seeing it in vNext.
Actually, I have already implemented the feature for an older version of MRTK. Will it be of any help if I port it to upstream and file a PR?

**Comment by StephenHodgson** [comment]
That's odd, thanks for the heads up.

**Comment by StephenHodgson** [comment]
> Actually, I have already implemented the feature for an older version of MRTK. Will it be of any help if I port it to upstream and file a PR?

Depends on if it follows our updated architectural patterns.

You're more than welcome to submit a PR and we can talk about what changes need to be made to support the new patterns.
