### ISSUE TITLE
Does plane finding api merge all the nearby plane by default to give a bigger plane?

### ISSUE THREAD

**Issue by Shubham7694** [Microsoft/MixedRealityToolkit-Unity#2340]
## Overview
I am facing an offset issue with plane finding api of hololens. While it works fine for walls, floors always come with some offset. It seems like plane finding api merges nearby small planes to create bigger plane thus changing the average height/depth of plane from the actual plane. How can we discard nearby planes which are above or below the main plane? 

I tried using the param such as FloorBuffer =0.0f & UpNormalThreshhold = 0.98f (https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/84493c975fbf0fe0f3541303ce1758ca11dfe44a/Assets/HoloToolkit/SpatialMapping/Scripts/SpatialProcessing/SurfacePlane.cs) to reduce the tolerance range. Any pointers in how to improve this?

## Steps to reproduce
_(Links to sample github project preferred)_

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
