### ISSUE TITLE
Teleportation is in-responsive and slow

### ISSUE THREAD

**Issue by marklinmao** [Microsoft/MixedRealityToolkit-Unity#2342]
## Overview
The user experience of the default MRTK teleportation is quite disappointing, which is in-responsive and slow, especially comparing to the default teleportation in Windows home. I am wondering why. How can we make it consistent as the Windows one.

## Expected Behavior
User launch application from Windows Home, and they expect the teleportation to be as responsive as Windows Home.

## Actual Behavior
The actual teleportation is slow. Sometimes it respond after 1 second, sometimes the arrow doesn't show up at all.

## Steps to reproduce
Just create a new project, import MRTK, Apply project settings and scene settings as a VR project. Play the project and try teleportation.

## Unity Editor Version
2018.1.1f1 Personal 64bit

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-2017.4.0.0

**Comment by StephenHodgson** [comment]
We've got a new system coming in vNEXT that should solve a lot f these issues. Most of the teleportation stuff is example only.

**Comment by marklinmao** [comment]
Thanks for the information, Stephen, about when will that be available?

**Comment by StephenHodgson** [comment]
We're aiming for August, if things go smoothly.

**Comment by marklinmao** [comment]
Thanks. Will we have a 'formal' version of teleportation which will be as same as the Windows Home one?

**Comment by StephenHodgson** [comment]
That is correct.

**Comment by marklinmao** [comment]
That's great! Thank you!

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
