### ISSUE TITLE
Suggestion: Make OnInputClicked from UNETSharedHologram sample optionnal and disabled by default

### ISSUE THREAD

**Issue by benjamincoven** [Microsoft/MixedRealityToolkit-Unity#2352]
## Overview

Hello everyone, I suggest that the method OnInputClicked of UNETSharedHologram should work optionnaly (for exemple a serialized boolean has to be enabled in the editor component window). Because I lost a lot of my work time to look why airtaping on some objects was starting a tap to place mode. Because our project is not small, it was not obvious that this bug was coming from this feature.

## Unity Editor Version

2018.1.2f1

## Mixed Reality Toolkit Release Version

2017.4.0.0

**Comment by StephenHodgson** [comment]
Just don't register the game object with the input manager

**Comment by keveleigh** [comment]
> Just don't register the game object with the input manager

It doesn't sound like it's an issue with a global listener, but the action of actually tapping on an object, where there's no registration component.

I'll take a look at the prefab today.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
