### ISSUE TITLE
TwoHandManipulatable script is not customizable.

### ISSUE THREAD

**Issue by juanmiguelbesada** [Microsoft/MixedRealityToolkit-Unity#2355]
## Overview
I want to use the TwoHandManipulatable to configure my scene. I want to do some stuff when manipulation ended or when manipulation start but, as this methods (`OnManipulationStarted` and `OnManipulationEnded`) are private, I cant overwrite them. So I have to copy the entire class to my own script, and then update that methods.

## Expected Behavior
Allow to overwrite "On" methods or at least provide any way to handle manipulation events.

## Actual Behavior
Can't overwrite because they are private

## Unity Editor Version
- 2017.4
## Mixed Reality Toolkit Release Version
- 2017.4.0.0

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
