### ISSUE TITLE
How to create simple shared anchor program using SharingWorldAnchorManager.cs

### ISSUE THREAD

**Issue by ThomasW0221** [Microsoft/MixedRealityToolkit-Unity#2365]
## Overview
I would like build a simple application that allows multiple users to connect to a server, and see an object in the same space in their physical environment despite where they launched the application in the room. I have several programs that use UNet sharing, and I have different programs that use World Anchors, but I am having trouble figuring out where to start when it comes to combining the two.

This was the tutorial I followed when building my networking applications: https://www.linkedin.com/pulse/share-hologram-hololens-emulator-unity3d-using-unet-krishnan-unni
Is there a way to make this solution compatible with the SharingWorldAnchorManager so that the objects spawned will appear in the same space for all clients?

Thank you, any help is appreciated.

## Unity Editor Version
Unity 2017.2.1p2

**Comment by JoseSantano-ms** [comment]
Hi Thomas 

I think you should have a look at the [examples](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit-Examples) section. There are two of them that achieve what you're looking for. Given that you're already familiar with UNet, I would start with [this one](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit-Examples/SharingWithUNET) 

Thanks

**Comment by ThomasW0221** [comment]
Thanks Jose,

I imported this example and tested it on two devices. If you are able to, would you mind telling me how this project is supposed to be functioning? When we ran it, the anchors for the other device did not seem to be in the correct locations, and I am wondering if there is something wrong, or if I am misunderstanding how this project is supposed to function.

**Comment by isurfraz** [comment]
Hi we have also had the same issues of anchors not appearing at correct locations. Pulling June 18 branch did not fix it , as was suggested in the other issue that i commented on.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
