### ISSUE TITLE
Are Unity 2017.1.0f3, Visual Studio 2015 and HoloToolkit-Unity-2017.2.1.0 compatibile for Hololens application developement? I am getting some errors while trying to create a project.  

### ISSUE THREAD

**Issue by ISUSupriyaRaul** [Microsoft/MixedRealityToolkit-Unity#2366]
## Steps to reproduce
_(Links to sample github project preferred)_

**Comment by ISUSupriyaRaul** [comment]
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(52,62,52,64): error CS1003: Syntax error, ',' expected
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(88,17,88,21): error CS1547: Keyword 'void' cannot be used in this context
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(88,50,95,85): error CS1528: Expected ; or = (cannot specify constructor arguments in declaration)
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(88,50,88,51): error CS1003: Syntax error, '[' expected
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(88,102,88,102): error CS1003: Syntax error, '=>' expected
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(94,18,94,18): error CS1003: Syntax error, ',' expected
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(95,85,95,86): error CS1003: Syntax error, ']' expected

**Comment by StephenHodgson** [comment]
Visual Studio 2017 is required to work with the Holotoolkit.

**Comment by ISUSupriyaRaul** [comment]
@StephenHodgson Thank you for your reply. For some reason, I can not upgrade the Unity and VS versions on my lab's system. Could you please suggest me any alternative version (or any other way) of Holotoolkit to use with them?
