### ISSUE TITLE
MixedRealityPosePose???

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2372]
## Overview
Currently the name of the pose attribute in the InputHandlers looks just odd.

```public MixedRealityPose MixedRealityPosePose { get; private set; } = MixedRealityPose.ZeroIdentity;```

PosePose ??

## Expected Behavior
A name that makes better sense :D like:
* MixedRealityPose
* Pose (it's the pose of the SourcePoseEventData)

Avoiding properties with work duplication

**Comment by StephenHodgson** [comment]
Haha, oops. I guess the renaming didn't go as smoothly as intended.
