### ISSUE TITLE
vNext: Windows Mixed Reality controller corner cases

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2378]
## Overview
Found a couple of corner cases that need to be addressed in the Windows Mixed Reality controller implementation.

## Expected Behavior
Receive TrackingState.NotApplicable for Voice || (Controller && !pointingSupported).
Receive TrackingState.Tracked if have position || rotation data.

## Actual Behavior
Receive TrackingState.NotTracked for Voice || (Controller && !pointingSupported).
Receive TrackingState.NotTracked if have no position data with valid rotation data.

## Mixed Reality Toolkit Release Version
vNext Alpha

**Comment by StephenHodgson** [comment]
I've never seen voice get raised through the interaction manager.

What are some of the repro steps for the voice ones?

**Comment by davidkline-ms** [comment]
Voice comes through in events (ex: Select). We are not actually checking for voice in the fix. We are checking for the positive case (hand or controller that can point) rather than the negative.

**Comment by StephenHodgson** [comment]
Huh, I've never seen Select as Voice get raised through the interaction manager. I'll have to try it out later.

**Comment by keveleigh** [comment]
I've never seen Voice come through the InteractionManager either; just the GestureRecognizer (where Select events come through).
