### ISSUE TITLE
A little problem about Spatital mapping prefab.

### ISSUE THREAD

**Issue by loveXMTX** [Microsoft/MixedRealityToolkit-Unity#2381]
I used the MRTK package to achieve spatital mapping, but when I use this prefab,the scaning model in Hololens is not my room, it is the last room model that I scan in my lab.  I have set Room Model  None(Game object). So what's the reason leading to this problem?

**Comment by davidkline-ms** [comment]
@loveXMTX, what version of the toolkit are you using? Also, does your app ever set the Room Model property?

**Comment by loveXMTX** [comment]
I just use the latest version package. This Unity project had been built once ,and then I change the scene content and some scripts to rebuild it, but  I uninstalled this app,then rebuild app,this trouble  still happened. Do some documents in project remember the scene property leading to this ?How could I do to solve ?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
