### ISSUE TITLE
Not capable with Version Control Mode:Perforce

### ISSUE THREAD

**Issue by fexfox** [Microsoft/MixedRealityToolkit-Unity#2382]
## Overview
when i use perforce as version control, the MR toolkit will always show "Enable Visiable MetaFiles" dialog. Actually, perforce is using Visiable MetaFiles.
## Expected Behavior
won't show that dialog
## Actual Behavior
always show "Enable Visiable MetaFiles" dialog
## Steps to reproduce
_(Links to sample github project preferred)_
Just using Perforce as version control.
the code in HoloToolkit.Unity.EnforceEditorSettings.cs
Line 41 will check the version control state.
Please change to  if (!EditorSettings.externalVersionControl.Equals("Visible Meta Files")&&!EditorSettings.externalVersionControl.Equals("Perforce"))
## Unity Editor Version
2017.4.2f2
## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
