### ISSUE TITLE
Voice commands get disabled for custom apps after some time.

### ISSUE THREAD

**Issue by lexiconcreation** [Microsoft/MixedRealityToolkit-Unity#2383]
## Overview
I deployed a application on hololens with voice commands. Initially the voice commands work but after i start the presentation and in between give any voice commands it just doesn't work.
If i reset the voice command setting : Turn off and then turn on. It starts working.

## Expected Behavior
The voice commands given at any point while using the application should work

## Actual Behavior
Initially the voice commands work but after i start the presentation and in between give any voice commands it just doesn't work.
If i reset the voice command setting : Turn off and then turn on. It starts working.

## Steps to reproduce
Run a custom application with voice commands.
test the commands and start presenting to someone or talking in general about the application or you could just blabber.
Post about 5 mins try any voice command.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
