### ISSUE TITLE
vNext Task: Add Spatial Mapping / Environmental Awareness SDK components

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2386]
## Overview
This task adds an initial implementation for Environment / Spatial Mapping scanning and understanding.
The first implementation of this will be entirely in the SDK layer and support only HoloLens devices - it will need refactoring as additional devices that support environmental awareness/understanding are added to MRTK

## Requires
- SDK layer scripts and prefabs for
    - Receiving spatial mapping data
    - Rendering spatial mapping data
    - Enabling simple plane finding
    - Enabling Spatial Understanding
- SDK layer materials for
    - Rendering wireframe mesh
    - Rendering occlusion
    - Plane representations (floor, wall, etc)
    - Spatial Understanding representations
- MRTK Standard Shader
- Ports of example scenes and scripts
    - Spatial Mapping visualization
    - Simple plane finding
    - Spatial Understanding

## Acceptance Criteria
- [x] User can configure the spatial awareness system to return raw data, planes and/or gameobjects
- [x] Example scenes behave as intended
- [x] Spatial awareness correctly handles non-Spatially aware devices

**Comment by StephenHodgson** [comment]
> User can add a single prefab to perform raw Spatial Mapping, simple plane finding and/or Spatial Understanding

Let's move away from prefabs and use the scriptable objects more.

**Comment by StephenHodgson** [comment]
Pretty sure this task is complete.
