### ISSUE TITLE
Tapping on keyboard keys activates fallbackInputStack callbacks

### ISSUE THREAD

**Issue by SujeathPareddy** [Microsoft/MixedRealityToolkit-Unity#2391]
## Overview
This is related to #2295. In that issue, tapping on a button would activate fallbackInputStack callbacks. HoloToolkit.Unity.Buttons.Button was patched as a result.

That fix does not apply here because the keyboard uses UnityEngine.UI.Button instead.

## Expected Behavior
Should not activate fallbackInputStack.

## Actual Behavior
Activates fallbackInputStack. 

## Steps to reproduce
Download [here](https://github.com/SujeathPareddy/KeyboardRepro/tree/fallbackRepro). 

Build, run and then tap on the button, the keyboard pops up (it might be too close to the camera to render, so move back a bit). Then type something on the keyboard and look at the console messages.

## Fix

Use MRTK's button class instead of Unity's button in the keyboard. I think this bug would occur everywhere there is a Unity button. This is a pretty big change.

## Unity Editor Version
2018.3

## Mixed Reality Toolkit Release Version
2018.4

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
