### ISSUE TITLE
can i change Camera rotation via parent?

### ISSUE THREAD

**Issue by KiDeokKim** [Microsoft/MixedRealityToolkit-Unity#2392]
Hi there,
i'm trying to changing MixedRealityCamera(MRC) rotation via MixedRealityCameraParent(MRCP).
however, MRC is HMD tracking, so rotation and position value change real time(if i moving HMD). but MRCP is fixed position & rotation value(if not control Motion controller).
so, if i control Motion controller(pressed touchpad),  i want to go back to the screen when it's first screen(first screen, an object is in front of me).
but MRC is not changing rotation value, so just modify MRCP rotation value.
To get to the first screen, how do i changing rotation value?

## Unity Editor Version
2017.3.1f1
## Mixed Reality Toolkit Release Version
Latest

**Comment by keveleigh** [comment]
We do have some controls and code that rotate the parent.

https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs#L276

The `transform` referenced here is that of the MRCP. This script is triggered by pushing left or right on the motion controller's thumbstick.

**Comment by KiDeokKim** [comment]
yeah, i know rotate the MRC through an empty object(MRCP). but HMD is always tracking, so MRC rotation value is not changeable(maybe...?).
if i start MRCP rotation value is (0,90,0), and MRC value is (0,0,0). but as shown above, MRC value is HMD tracking value. so MRC value is dependent on HMD Camera.
so, my need is how to set start value MRC and MRCP. just adjust MRCP rotation value is unique solution??

here is reference my intention. maybe it is helpful you understanding
![reference1](https://user-images.githubusercontent.com/40253618/42361916-ba4b0ffe-812b-11e8-8c34-d76586c933f1.jpg)

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
