### ISSUE TITLE
SharingWithUNet problem

### ISSUE THREAD

**Issue by gzpUnreal** [Microsoft/MixedRealityToolkit-Unity#2393]
## Overview
I got HoloToolkit v2017.4.0.0rc2. When I build and deploy the app to two HoloLens, the client one hangs.

## Expected Behavior
I should see the WorldAnchor imported for the client HoloLens when it joins the session. but cannot find the WorldAnchor.
## Actual Behavior
The client HoloLens device keeps waiting for the anchor.
## Steps to reproduce
Simply download v2017.4.0.0rc2, and build and deploy SharingWithUnet to HoloLens devices. Run one as server, second one Join the session.
## Unity Editor Version
Unity 2017.4.6f1
## Mixed Reality Toolkit Release Version
v2017.4.0.0rc2

**Comment by keveleigh** [comment]
Unfortunately, the latest release had an issue with the UNET scripts. A fix was added with #2319, but it hasn't made its way into a release yet. Please grab the june18_dev branch and try with that code.

**Comment by gzpUnreal** [comment]
I checked out the code in june18-dev branch and my first view to it is that UNetAnchorManager.cs and GenericNetworkTransmitter.cs are quite similar as in v2017.4.0.0rc2, in which there are #if UNITY_WSA && !(ENABLE_IL2CPP && NET_STANDARD_2_0) to block out more code so GenericNetworkTransmitter.RequestAndGetData return nothing and no WorldAnchor data. So no WorldAnchor is imported.

**Comment by keveleigh** [comment]
They are similar, but very different, as seen in the PR I linked above.

![screenshot_20180704-151341 2](https://user-images.githubusercontent.com/3580640/42295228-0c415d30-7f9d-11e8-844b-b920a3a7892d.png)

The released version is only true when building .NET Standard 2.0 for a non-IL2CPP backend.
The fixed version in the June branch is true when building anything except IL2CPP and .NET Standard 2.0 together. is that your build configuration?

**Comment by gzpUnreal** [comment]
Yes, I set in Player Settings, to use .NET, not IL2CPP, and Scripting Backend is .NET and Api Compatibility Level is .NET 4.6. So it should make those code in the vs solution.

BTW, are ENABLE_IL2CPP and NET_STANDARD_2_0 are defined in Unity build process?

**Comment by keveleigh** [comment]
Great yep, those settings should be good. You've run your code with the June branch, and it still doesn't work? I ran the scene earlier this week with success (and verified that the pre-fix version did not work). Do your devices have enough overlapping knowledge of the space to localize the anchor?

Correct, those defines are part of the Unity build process, so you don't have to do anything special to get them to work.

**Comment by gzpUnreal** [comment]
I load SharingWithUNET into Unity2017.4.6f1 and build it. After deploy it to two HoloLens devices, the first HoloLens is running and click on Start is also ok, Waiting for deploy on the second HoloLens. the network is too slow here.

BTW, after updated to OS 17134, I didn't see how to manage the Spaces. so I don't know how much spaces on my HoloLens.

**Comment by gzpUnreal** [comment]
I have this message in Unity Console when load june18-dev into Unity 2017.2.1f1:
System.Exception: Package directory not found: C:\Users\gzp07\.nuget\packages\Microsoft.CSharp\4.0.1
How to get that one?

**Comment by isurfraz** [comment]
@gzpUnreal why are you on Unity 2017.2.1f1 when the release version of MRTK is for LTS versions of unity 2017.4 and up?

We are using the UNET example without this issue. We had to pull in the june18 branch but we have been using 2017.4 as well as .Net 4.6. hope this can help

**Comment by gzpUnreal** [comment]
@isurfraz because my teammate has problem on his laptop to run Unity newer than 2017.2.1f1 personal version. And I can work with june18-dev branch and Unity 2017.2.1f1. I do have 2017.4.6f1 and june18_dev. When the release version ready, I think I will use 2017.4.6f1. Thank you.

**Comment by isurfraz** [comment]
Actually I sometimes get client hanging even with June 18 dev branch and 2017.4.6 so please let me know if you have further issues as we are having problems!

**Comment by gzpUnreal** [comment]
Hi
 It looks ok with Unity 2017.2.1f1. The crash was caused by my debugging code that I wanted to print out some info in GenericNetworkTransmitter.cs. 

Best,

Zhenping Guo
 

    On ‎Monday‎, ‎July‎ ‎16‎, ‎2018‎ ‎05‎:‎17‎:‎39‎ ‎PM‎ ‎CST, Isaac Surfraz <notifications@github.com> wrote:  
 
 
Actually I sometimes get client hanging even with June 18 dev branch and 2017.4.6 so please let me know if you have further issues as we are having problems!

**Comment by isurfraz** [comment]
Update: this is still being experienced by us using the latest MRTK release from 4 days ago

**Comment by isurfraz** [comment]
@gzpUnreal  did you manage to solve all your anchor problems? if so, how?

**Comment by gzpUnreal** [comment]
Hi,

We did solve our anchor problem. The way we did is to save it locally on HoloLens. This sounds ok for now but there is problem when re-deploy the app, all data files are lost. Then we have to upload again.

Another problem I have is that Microsoft HoloLens app has problem: the video shows that the virtual scene is not stable but it shouldn't. I attached a video for you to check out. In the video, the robot arm is a real one in the lab, the moving box is the virtual object that the robot will grab it and move it from one belt to another belt. But the box and belts are floating which shouldn't be moving. Please let me know what may cause this and how to fix it. Thank you very much.

**Comment by isurfraz** [comment]
@gzpUnreal  you didnt actually attach a video?
