### ISSUE TITLE
Metadata file could not be found

### ISSUE THREAD

**Issue by PJBowron** [Microsoft/MixedRealityToolkit-Unity#2397]
## Overview

I just set up a clean Unity project and dropped in the current MRTK release but I can't build in VS (say, to make a debugger connection to Unity) due to the following errors:

```
Error	CS0006	Metadata file '(Unity project path)\Assets\HoloToolkit\Utilities\Scripts\GLTF\Plugins\GLTFSerialization\GLTFSerialization.dll' could not be found
Error	CS0006	Metadata file '(Unity project path)\Assets\HoloToolkit\Utilities\Scripts\GLTF\Plugins\JsonNet\Newtonsoft.Json.dll' could not be found
```

I'm sure I've encountered this before and seen a solution but now can't find it anywhere!

## Config

Unity 2017.4.1f1
MRTK 2017.4.0.0
4.6 Scripting Runtime & API compatability; .NET scripting backend

**Comment by keveleigh** [comment]
Strange! I can't say I've seen this before. Are the corresponding .meta files actually not present in your project?

**Comment by PJBowron** [comment]
Apologies, this is nothing to do with MRTK.
Problem occurred because our project root folder (not the Unity project, the 'workspace' root wherein the Unity project is one of many things) had a %20 in its name after cloning a repo with a actual space. Seems that Visual Studio 'intelligently' changes occurrences of %20 into spaces within the build process, which was breaking the local pathname...
Please close/delete/purge/kill with fire ;)

**Comment by timGerken** [comment]
Closed.
