### ISSUE TITLE
Sharing Service Invalid Schema

### ISSUE THREAD

**Issue by BrentKingma** [Microsoft/MixedRealityToolkit-Unity#2404]
## Overview
When I imported all the packages and set my scene up correctly and i try to join my SharingService server i get the error of having an invalid schema version.
<img width="362" alt="server log" src="https://user-images.githubusercontent.com/28910209/42353552-80ebed0e-8104-11e8-98d8-b60b5ced8216.PNG">
I set up my project just to have a simple object that tries to connect to the server so that i can eliminate other factors.
<img width="212" alt="object components" src="https://user-images.githubusercontent.com/28910209/42353571-aa7eb5a2-8104-11e8-9681-f05961040d7a.PNG">

I have checked and followed the guidance given on [Microsoft#487](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/487) and still no result.

## Steps to reproduce
https://github.com/BrentKingma/HololensSharing

## Unity Editor Version
Unity version 2017.2.1f1
## Mixed Reality Toolkit Release Version
Package version 2017.2.1.1

**Comment by StephenHodgson** [comment]
Sounds like you need the latest version of the server to run.

**Comment by BrentKingma** [comment]
How can i run download the latest server, if it is by downloading through github, i have tried that and if it is through the unity editor, i also have tried that.

**Comment by keveleigh** [comment]
Seems like it's the other way around.

The 2017.2.1.1 Toolkit release was the last one with version 17, while any since then have version 18. Is the Toolkit downloader grabbing the latest instead of the one that corresponds to the release? Try this one:

https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/2017.2.1.1/External/HoloToolkit/Sharing

**Comment by BrentKingma** [comment]
That worked, thank you very much.

**Comment by StephenHodgson** [comment]
@Keveleigh So the problem is that the mrtk isn't using the latest?
