### ISSUE TITLE
The Compound Button has no binded Events

### ISSUE THREAD

**Issue by ThomasAstrakhan** [Microsoft/MixedRealityToolkit-Unity#2408]
## Overview

The Unity UI Button has a list of event called when the user press the button "On Click (Button)" :

![image](https://user-images.githubusercontent.com/39410322/42371344-7b93b192-810f-11e8-8f61-51395d566890.png)

So I modified the Compound Button Script to add this list of Event.
![image](https://user-images.githubusercontent.com/39410322/42371745-aa996f62-8110-11e8-9aea-97b3da597e9d.png)

I also modified the InteractableObjectExample scene by 

1. Adding a SpeechInputSource.

1. Adding the keyword "Button" in the SpeechInputSource.

1. Adding an event in the event list of HolographicButton to disable itself when press or called by speech.

![image](https://user-images.githubusercontent.com/39410322/42372275-1d924c2c-8112-11e8-9ec8-00f5907ef013.png)

You can find my work [in my fork](https://github.com/ThomasAstrakhan/MixedRealityToolkit-Unity/tree/CompoundButtonWithEventList)

## Expected Behavior

Have the same list on the CompoundButton script. Make it working when pressing the button and calling the name of the button is there is a CompoundButtonSpeech

## Actual Behavior

I need to create a custom script in addition to a CompoundButton and put it as a Component in my Button GameObject to have the same behavior as a Unity Button. This is not comfy.

## Unity Editor Version

2018.1.0f2

## Mixed Reality Toolkit Release Version

2017.4.0.0 (May 2018)

**Comment by Ecnassianer** [comment]
This has been a thorn in my side as well!

**Comment by StephenHodgson** [comment]
>I need to create a custom script in addition to a CompoundButton and put it as a Component in my Button GameObject to have the same behavior as a Unity Button.

I'd recommend against using the Unity Events as they're a pain to work with. Ppl say it's easier to use in the inspector but I find it tedious as hell.

That being said, it's not hard to wrap your custom script in a binding, in fact the speech input system uses this same wrapping.  I've also got plans to add this to MRTK vNEXT for other functionality.

**Comment by StephenHodgson** [comment]
See this discussion for more info about the design choice:
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/876#issuecomment-323417651

**Comment by cre8ivepark** [comment]
Adding @Railboy who created CompoundButton series.

**Comment by cre8ivepark** [comment]
@ThomasAstrakhan , SpeechInputSource was added in the pull request #2400

**Comment by ThomasAstrakhan** [comment]
@StephenHodgson 
> Instead just add specific GameObject or UnityEngine.Object slots in your inspector and call the method directly.

You want me to call a method directly in compundbutton.cs or in button.cs ?
i can't do that because at the next update my compoundbutton or button script will be erased.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
