### ISSUE TITLE
#IManipulationHandler

### ISSUE THREAD

**Issue by Link2011** [Microsoft/MixedRealityToolkit-Unity#2410]
## Overview
When trying to move an object with Drag and Drop over a Button the Button get's pressed

## Expected Behavior
I can move the object freely without interaction with other objects

## Actual Behavior
When I move with my Cursor over an Object which is interactable the Object stats moving out of my focus and then stops moving again.

## Steps to reproduce
Simply put this Script on an small Object you want to move in a HoloLens Project.
Place a second bigger object with this script on it.
Then drag the smaller object to the bigger object and let your Gaze hit the 2. Object.
The bigger object should then be moved as far as you moved the smaller object and your drag action is then over.

```
public class DragNDrop : MonoBehaviour, IManipulationHandler
{

  [SerializeField]
  float DragSpeed = 1.5f;

  [SerializeField]
  float DragScale = 1.5f;

  [SerializeField]
  float MaxDragDistance = 3f;

  [SerializeField]
  GameObject _toMoveObject;

  Vector3 lastPosition;

  [SerializeField]
  bool draggingEnabled = true;

  private Vector3 targetPosition;

  private bool inDragging;

  public void SetDragging(bool enabled)
  {
    draggingEnabled = enabled;
  }

  public void OnManipulationStarted(ManipulationEventData eventData)
  {
    InputManager.Instance.PushModalInputHandler(gameObject);
    if (_toMoveObject != null)
    {
      lastPosition = _toMoveObject.transform.position;
    }
    else
    {
      lastPosition = transform.position;
    }
  }

  public void OnManipulationUpdated(ManipulationEventData eventData)
  {
    if (draggingEnabled)
    {
        Drag(eventData.CumulativeDelta);
    }

      //sharing & messaging
      //SharingMessages.Instance.SendDragging(Id, eventData.CumulativeDelta);
    }
  }

  public void OnManipulationCompleted(ManipulationEventData eventData)
  {
    InputManager.Instance.PopModalInputHandler();
  }

  public void OnManipulationCanceled(ManipulationEventData eventData)
  {
    InputManager.Instance.PopModalInputHandler();
  }

  void Drag(Vector3 positon)
  {
    targetPosition = lastPosition + positon * DragScale;
    if (Vector3.Distance(lastPosition, targetPosition) <= MaxDragDistance)
    {
      if (_toMoveObject != null)
      {
        _toMoveObject.transform.position = Vector3.Lerp(_toMoveObject.transform.position, targetPosition, DragSpeed);
      }
      else
      {
        transform.position = Vector3.Lerp(transform.position, targetPosition, DragSpeed);
      }
    }
  }
}
```

## Unity Editor Version
2018.1.0f2
## Mixed Reality Toolkit Release Version
2017.4.0.0 (latest realese)

**Comment by StephenHodgson** [comment]
Sounds like you need to push/pop the modal input for your object.

This is a known issue. See #709

**Comment by Link2011** [comment]
@StephenHodgson Thanks for your answer. Sadly I still don't know how to fix the code.  I already tried the Push and Pop functions (as you can see in my code) but it doesn't work (even if I add ClearModalInputStack)
Could you give me an example how to fix my code?
How do you use "InputManager.Instance.OverrideFocusedObject" porperly?

Thanks for your time, I hope you can help me out.

**Comment by StephenHodgson** [comment]
Oh, one last thing, you need to have your component register itself as a global listener so much that it will receive events from the input system when you're not looking at it.

**Comment by StephenHodgson** [comment]
I suppose one thing we could do to help with this when using push and pop modal input, is to register and unregister the game object as a global listener... I'll test this out and see how it feels.

**Comment by keveleigh** [comment]
@StephenHodgson what would be the benefit to making it a global listener as well? I thought the point of modal input was also to receive input even when not (or no longer) being focused.

**Comment by Link2011** [comment]
@StephenHodgson If you get it working, could you show me how you did it? That whould help me a lot.

Thanks for your help

**Comment by keveleigh** [comment]
What's the purpose of the `selectedObject` check here?
```
if (eventData.selectedObject == null)
{
    Drag(eventData.CumulativeDelta);
}
```

Second, it might be worth trying to add `eventData.use()` at the end of all your event handlers. It should cause the event to go to your original object that's now modal and prevent it from falling through to the newly focused object.

**Comment by Link2011** [comment]
@keveleigh
Forgot to remove that, it was part of a bad workaround, my Bad.

I will try it out tomorrow, thanks for the input!

**Comment by StephenHodgson** [comment]
Sorry, I'm not around a computer atm to write something up.

I'd take a look at the hand dragable script to get an idea.  That also takes in spatial mapping into account, and has support for rigidbodies.

**Comment by Link2011** [comment]
@StephenHodgson 
No need to hurry, won't be on my development computer in the next view houers.

**Comment by Link2011** [comment]
@keveleigh I added eventData.Use(); at the end ov every manupulation as you suggested, sadly it still doesn't work properly (now the objects start jumping around as long as I keep my fingeres pressed and looking at a moveable object. Any other ideas how to fix it?

**Comment by Link2011** [comment]
@StephenHodgson Did you get any updates for me?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
