### ISSUE TITLE
MRTK keyboard exceptions building with visual studio

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#2418]
## Overview
NullReferenceException are thrown when using the MRTK keyboard and building the solution with visual studio
## Expected Behavior
No exceptions
## Actual Behavior
Unity log:
```
Exception thrown: 'System.NullReferenceException' in UnityEngine.UI.dll
NullReferenceException: Object reference not set to an instance of an object.
   at UnityEngine.UI.InputField.ActivateInputFieldInternal()
   at UnityEngine.UI.InputField.LateUpdate()
   at UnityEngine.UI.InputField.$Invoke72LateUpdate(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)
```

## Steps to reproduce
1) New project with KeyboardTest scene
2) Build UWP solution
3) Open the solution with VS
4) Build the debug configuration and look at the output window or build the release or master configuration and look at the unity log

## Unity Editor Version
2017.4.6f1
## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
