### ISSUE TITLE
vNext: Make ExperienceScale selection independent of using the a boundary system

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2420]
## Overview
#2402 adds ExperienceScale and maps it to Unity's TrackingSpaceType. While this is correct, having it exposed as part of the Boundary system is not.

ExperinceScale impacts more than just whether or not a boundary should be expected. One use that gets hidden by encapsulating ExperienceScale within the boundary system is that OrientationOnly should disable positional tracking.

The table on https://docs.microsoft.com/en-us/windows/mixed-reality/coordinate-systems describes the scales very well.

**Comment by SimonDarksideJ** [comment]
I think we need to ensure the above documentation is included in any talk / documentation on the new boundary system

**Comment by davidkline-ms** [comment]
Agreed. I have added descriptions of each experience scale to the ConfigurationProfile inspector in #2402 .

![experiencescaleininspector](https://user-images.githubusercontent.com/13281406/42527358-46f2ddf2-842d-11e8-8290-0198253de9cd.png)

**Comment by SimonDarksideJ** [comment]
Implemented as part of #2402
