### ISSUE TITLE
Move CursorWithFeedback Prefab

### ISSUE THREAD

**Issue by Hobl1990** [Microsoft/MixedRealityToolkit-Unity#2421]
## Overview
Hi everyone I want to move the ready cursor of the CursorWithFeedback Prefab depending on the ready gesture. I got the position of the hand and assigned it to the cursor. Additionally I want to assign a rigidbody and a collision collider on the ready cursor to simulate a "real" hand.

## Expected Behavior

I get the position of the detected gesture and assign the position with the gameobject.GetComponent<Rigidbody>().MovePosition() -method to the ready cursor.

## Actual Behavior

The cursor moves depending on the heads and not the gesture movement.

## Steps to reproduce
I configured the cursor state hover and assigned the CursorVisual prefab.

**Comment by davidkline-ms** [comment]
This proposal breaks the input paradigm for Windows Mixed Reality. 

The cursor does not track the hand position, it tracks the user's gaze.

**Comment by Hobl1990** [comment]
Ok thanks for the information. Is it possible when I delete the inputmanager and make my own prefab for the cursor?

**Comment by StephenHodgson** [comment]
Don't remove the input manager, instead remove the cursor prefab on the gaze manager with your own.

**Comment by Hobl1990** [comment]
hi @StephenHodgson how could I replace the cursor in the gaze manager?

**Comment by StephenHodgson** [comment]
Select the gaze manager in your scene and remove/replace the cursor prefab with your own.

**Comment by Hobl1990** [comment]
Yeah that worked great thanks ;) 

But I want to move the ready cursor (with a rigidbody) to the detected gesture position. 
Therefore I used  the obj.state.sourcePose.TryGetPosition(out position_hand) - method to get the position. 
When I attach the position with the transform.position it works but when I use the gameobject.GetComponent().MovePosition() -method it doesn't work. 
(The ready cursor isn't assigned to the gaze manager, the input manager is active)

Do you know why?

**Comment by StephenHodgson** [comment]
Probably because the position is being overridden by the cursor itself. You'll need to toggle isKinematic.
