### ISSUE TITLE
Migrate Dev_Working_Branch changes to master

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#2423]
## Overview
After the namespace refactor work and the divergence of the Dev_Working_Branch, several changes went into Dev that haven't yet been migrated back to master.

This will also give us a single place to migrate content to vNext from.

## Expected Behavior
Dev and master have not diverged.

## Actual Behavior
Dev and master have diverged.

## PRs to Investigate (possibly partial list; some have already been migrated)
- [ ] #1518
- [ ] #1718 
- [x] #1726 (via #1717)
- [ ] #1727
- [ ] #1734
- [ ] #1739
- [ ] #1743 
- [x] #1748 (via #2425) 
- [ ] #1785 
- [ ] #1786 
- [ ] #1789 
- [x] #1817 (via #1856)
- [ ] #1818
- [ ] #1819 
- [x] #1820 (via #2435)
- [ ] #1826 
- [ ] #1839 
- [ ] #1854 
- [ ] #1865
- [ ] #1873
- [ ] #1896
- [ ] #1897
- [ ] #1904 
- [ ] #1934
- [ ] #2005
- [ ] #2011
- [ ] #2024 
- [x] #2029 (via #2030)
- [x] #2036 (via #2035)
- [ ] #2039 
- [x] #2047 (via #2046)
- [x] #2065 (via #2064)
- [x] #2075 (via #2072)
- [x] #2079 (via #2078)
- [x] #2084 (via #2083)
- [x] #2088 (via #2087)
- [x] #2101 (via #2100)
- [x] #2106 (via #2105)
- [ ] #2114 
- [ ] #2116 
- [ ] #2121 
- [ ] #2122 
- [x] #2129 (via #2424)
- [x] #2144 (via #2435)

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
