### ISSUE TITLE
Launching applications with the mixed reality portal closed

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#2426]
## Overview
Launching applications with the mixed reality portal closed can cause an initialization of the app with the tracking space type setted to stationary. This can cause issue for the app because, for example, the floor is not rendered.
## Expected Behavior
Launching applications with the mixed reality portal closed should be the same as launching them from the mixed reality portal.
## Actual Behavior
Sometimes, when you launch an app with the mixed reality portal closed the application is not initialized with the tracking space type setted to room but to stationary.
![stationary](https://user-images.githubusercontent.com/17752475/42525068-876f8e8a-8472-11e8-9cfb-9c5508bf272f.PNG)
This can be a problem, in particular when the floor is an essential part of the app.
Personally I launch the apps from the mixed reality home but the user can also launch the app from a desktop tile. In particular when you install or update an app from the store the system present you a popup in the action center to launch the app directly.
Probably the tracking space is setted to stationary, because when the toolkit try to set it, something is not still initialized.
I don't know if is possible to solve this problem but I made some test with this code:
![code](https://user-images.githubusercontent.com/17752475/42526522-5d3d7a2e-8476-11e8-83a6-8edced6ca690.PNG)
The result is this:
![roomscaleafterretry](https://user-images.githubusercontent.com/17752475/42526621-9ddf3e8c-8476-11e8-8b3b-f8d7a81c83be.PNG)
It would be nice if the toolkit could manage also this situation.
## Steps to reproduce
The issue is not systematic but in my case it happens with the first launch of an immersive app after the boot of the system.
It seems that this situation is particularly critical. Sometimes I see also another issue with motion controller model not loaded.

## Unity Editor Version
2017.4.6f1
## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by SimonDarksideJ** [comment]
This might be better solved in vNext.  Will do some testing of this use case in case we need to make any amendments

**Comment by keveleigh** [comment]
This sounds like a Unity bug, where it's initializing before it can find the spatial stage root. It seems like Unity eventually does find the root, since you're successfully able to change to RoomScale after several tries.

**Comment by SimonDarksideJ** [comment]
Actually, this issue just got a whole lot messier due to changes in Unity 2018.2.  Note this in the changelog:
"XR: Standalone applications which target and require Windows Mixed Reality will now always attempt to initialize the device, even if no HMD is connected or the Mixed Reality OS component is not installed (rather then falling back to flat desktop mode.) This will cause the OS to display a dialog indicating that the user needs to connect a device and install the OS component."

**Comment by ivan2007** [comment]
@SimonDarksideJ, 
the fact that applications which target and require Windows Mixed Reality will now always attempt to initialize the device is a good thing, but in this case the headset is already connected so I am not sure that this will make difference in this case.
@keveleigh,
 yes I think that there is something not completely corrected that Unity does because when there is this issue and you go back to the cliff house with the windows buttton you don't see the house but the system that is initializing.

**Comment by ivan2007** [comment]
I tried with Microsoft layout and the issue is the same
This is the log:

![microsoftlayout](https://user-images.githubusercontent.com/17752475/42601899-88813b8e-8567-11e8-87f3-1910dda428d4.PNG)

**Comment by davidkline-ms** [comment]
@ivan2007, thanks for pointing this out. We should investigate if there is a good workaround to this (perhaps trying to reset the TrackingSpaceType if the application is being used with an opaque headset and the call to SetTrackingSpace returns false).

I'll take a look as I am currently working on the boundary code for vNext.

**Comment by davidkline-ms** [comment]
@ivan2007, I recommend filing a bug with Unity on this. It feels like the type of issue they would want to address in both the 2018.x and 2017.4 LTS products.

**Comment by ivan2007** [comment]
@davidkline-ms,
I will open a bug with Unity on this

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
