### ISSUE TITLE
Compound Button Icon cannot assign any icons.

### ISSUE THREAD

**Issue by lordlycastle** [Microsoft/MixedRealityToolkit-Unity#2429]
## Overview
In the inspector with CompoundButtonIcon component, after the user has assigned any of the icons in the icon profile that icon cannot be selected in the icon property of the component. Selecting the option in dropdown menu does nothing.

![compoundicon-1](https://user-images.githubusercontent.com/11729541/42567850-13c485a8-8503-11e8-944d-b65c0843285d.PNG)

Furthermore, if you "Add custom icon" it does not even show up in the dropdown menu of the "Icon" property of the icon.

![compoundicon-2](https://user-images.githubusercontent.com/11729541/42567841-0e047d08-8503-11e8-80f7-d29711fc1302.PNG)

## Expected Behavior
Expected ability to change icon of the button.
## Actual Behavior
Cannot change icon of the button other than the "ObjectCollection*" set.

## Steps to reproduce
_(Links to sample github project preferred)_
I have seen this happen in my project and in the InteractableObjectExample scene provided with the examples. 
## Unity Editor Version
2017.4.4f1
## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by cre8ivepark** [comment]
@lordlycastle I had a similar experience when I add a new texture. Please restart Unity and see if you are able to select newly assigned texture. Restarting Unity resolved the issue. @Railboy

**Comment by lordlycastle** [comment]
@cre8ivepark it would seem that way. It is accepting the icons now. Still there is a bug because it doesn't work without restart.  Idk if it's a Unity or a Toolkit bug.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
