### ISSUE TITLE
CompoundButtonSounds does not function reliably. 

### ISSUE THREAD

**Issue by lordlycastle** [Microsoft/MixedRealityToolkit-Unity#2430]
## Overview
The compound button sounds script does play a sound but not always, sometimes you get two click sound when you only click once. 
## Expected Behavior
The sound should play on every click and not repeat.
## Actual Behavior
Works sometimes but not always.
## Steps to reproduce
_(Links to sample github project preferred)_
I used the InteractableObjectExample scene. Try pressing any of the button. You'll need headphones or quiet room to hear the click.
## Unity Editor Version
2017.4.4f1
## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by radicalad** [comment]
I'm running into a similar issue where I have a compound button feeding an InteractionReceiver. The InteractionReceiver marks the event as "used". The button class doesn't receive the event (as expected), but somehow CompoundButtonSounds still fires sounds.

**Comment by arsi0001** [comment]
Hey, having still the same problem. Did sb fix it? Any solutions?

**Comment by lordlycastle** [comment]
@arsi0001  Not that I know of. I wrote my own singleton to play the sound so it's same for all except a few special buttons. You can dd the play sound function to the action of all buttons or call it directly from the Receiver.

I would recommend that you only use this module for prototypes. IMO it is far from release/stable build. It's a good starting implementation, if you wanna learn from their mistakes and make your own buttons. Good luck!

**Comment by arsi0001** [comment]
ok, thanks for replying. Yeah Im gonna use the receiver.

**Comment by Yoyozilla** [comment]
Bulk closing older HTK bug. Please reopen if you can repro this issue in MRTK v2. 
Thanks!
Yoyo
