### ISSUE TITLE
Disabling Normal Map + hover light  on the standard shader sometimes stops environment coloring from working

### ISSUE THREAD

**Issue by isurfraz** [Microsoft/MixedRealityToolkit-Unity#2431]
## Overview
Disabling Normal Map on the standard shader stops environment coloring from working
## Expected Behavior
Environment coloring highlights object when enabled.
## Actual Behavior
Environment  coloring does not contribute due to the way normal contributes.
## Steps to reproduce
_(Links to sample github project preferred)_
Highlight with gaze an object using Ifocusable that does not have normal map + normal enabled
## Unity Editor Version
2017.4.6f1
## Mixed Reality Toolkit Release Version
2017.4.0 + June18 branch

**Comment by isurfraz** [comment]
I believe the issues are with pieces of code like this littered throughout the shader:
`#if defined(_NORMAL)
                fixed3 worldViewDir = normalize(UnityWorldSpaceViewDir(i.worldPosition.xyz));
#if defined(_REFLECTIONS) || defined(_ENVIRONMENT_COLORING)
                fixed3 incident = -worldViewDir;
#endif
                fixed3 worldNormal;`

This, if i am not wrong, does not really deal with what happens if Normal is not defined, but environment coloring is. WOuld not worldviewdir be null or empty at this point?

There are a number of calculations for environment coloring that rely on world space normal information or normal information, but do not have cases for working if normal is undefined.

Perhaps the shadergui or shader should be edited so that if you disable this feature that it relies on, it also disables environment coloring?


Currently this is a very hard bug to track and led us down rabbit holes of thinking our use of gaze and input was incorrect when really it was fine all along. Due to the complexity of the shader GUI, it is very difficult to edit this sort of thing successfully, despite the actual shader being simple enough (food for thought)

@StephenHodgson @keveleigh

**Comment by isurfraz** [comment]
To add to this, this shouldnt happen because of this:

`#if defined(_DIRECTIONAL_LIGHT) || defined(_REFLECTIONS) || defined(_RIM_LIGHT) || defined(_ENVIRONMENT_COLORING)
            #define _NORMAL
#else
            #undef _NORMAL
#endif`

hope this helps you at microsoft work out this issue!

**Comment by isurfraz** [comment]
For anyone interested, for now I am just faking data for these values to ensure it alaways has something:

`
// Fake normal and incident (half)
#if	defined(_ENVIRONMENT_COLORING) && !defined(_NORMAL)
					fixed3 incident = (0.5, 0.5, 0.5);
				fixed3 worldNormal = (0.5, 0.5, 0.5);
				fixed3 environmentColor = incident.x * incident.x * _EnvironmentColorX +
					incident.y * incident.y * _EnvironmentColorY +
					incident.z * incident.z * _EnvironmentColorZ;
				output.rgb += environmentColor * max(0.0, dot(incident, worldNormal) + _EnvironmentColorThreshold) * _EnvironmentColorIntensity;

// Actual coloration logic from original
#elif defined(_ENVIRONMENT_COLORING) && defined(_NORMAL)
                fixed3 environmentColor = incident.x * incident.x * _EnvironmentColorX +
                                          incident.y * incident.y * _EnvironmentColorY + 
                                          incident.z * incident.z * _EnvironmentColorZ;
                output.rgb += environmentColor * max(0.0, dot(incident, worldNormal) + _EnvironmentColorThreshold) * _EnvironmentColorIntensity;

				// fake normals if they are not defined 
#endif`

This is in no way an elegant fix, and I would be interested in hearing the correct un-rushed fix.

**Comment by isurfraz** [comment]
This seems to only happen when hover light is not also checked.

**Comment by Cameron-Micka** [comment]
Thank you for the in depth report! I should have time to look at this early next week.

**Comment by isurfraz** [comment]
Hi Cameron,

Yes this is only in Build, can you give any suggestions to get around this? This is with the holotoolkit standard shader,

Thanks for any help you can give

**Comment by isurfraz** [comment]
Hi @Cameron-Micka yes it is only in build, using holotoolkit standard shader. Can you give any advice on this?

**Comment by Cameron-Micka** [comment]
Hi @isurfraz,

Ah, that is good to know you have a solution. The MRTK/Standard shader works very similarly to the Unity Standard shader. So, you can follow Unity's recomendations here: [MaterialsAccessingViaScript](https://docs.unity3d.com/Manual/MaterialsAccessingViaScript.html)

It looks like you are already enabled keywords correctly under step '1' but I'm guessing you just need to included the correct varients mentioned under step '2'.

If including the materials you need becomes too burdensome you can also build a unity shader variant collection, and mark it as always included in your builds.

**Comment by isurfraz** [comment]
Hi Cameron,

For the holotoolkit shader in the end a variant collection is what we did because I could not be bothered with all the faff involved with doing it for each manually. But this has made us get around to writing our own shader something that we have been meaning to do for a couple of weeks now. 

Once you pointed out the fact that it was shader_feature that was being used the rest clicked :) 

Thanks for getting back so fast.

I certainly think the shader should be changed to compile using multi_compile at least for the keywords extensively used in the MR101 -MR250 as currently if you were to follow official Microsoft documentation and tutorials you would end up with issues. Perhaps it is written in the MR series that one must be careful with the holotoolkit  standard shaders or they will cause issues, but I did not see it. 

Naturally for someone who’s sole job is shader and gpu programming perhaps spotting  this is easy, but most people use the holotoolkit to speed up development and we essentially lost half a week or more to this hard to spot bug/design issue.

Certainly at the very least get the team who wrote and maintain the MR series to mention this or provide a hotfix to them to upgrade their shaders to use multi compile? 

I am happy to provide some working shader solution tips to help get anyone up on their feat who is reading this and having issues with the bundled shaders. 

Thanks!

**Comment by Cameron-Micka** [comment]
Hi @isurfraz,

Thanks for the feedback! I agree I would like to make enabling features via script more accessible. Let me think of how I can do this without bloating build times. I'm also not familiar with MR101 or MR250, but I'll check them out in the MR Academy to see what they are suggesting.

**Comment by isurfraz** [comment]
Hi Cameron,

Just to clarify I meant all the MR Academy from 101 to 250 inclusive.

Thanks again! 

Sent from my iPhone

**Comment by isurfraz** [comment]
Hi Kurtis,

From MR 210:

/* TODO: DEVELOPER CODING EXERCISE 2.d */ void IFocusable.OnFocusEnter() { for (int i = 0; i < defaultMaterials.Length; i++) { // 2.d: Uncomment the below line to highlight the material when gaze enters. defaultMaterials[i].EnableKeyword("_ENVIRONMENT_COLORING"); } } void IFocusable.OnFocusExit() { for (int i = 0; i < defaultMaterials.Length; i++) { // 2.d: Uncomment the below line to remove highlight on material when gaze exits. defaultMaterials[i].DisableKeyword("_ENVIRONMENT_COLORING"); } }


Sorry for my phone turning the formatting to garbage. There is an explicit mention of using a keyword, which was the stem of our problems. 


Thanks! 

Isaac

**Comment by keveleigh** [comment]
@isurfraz ah, thanks for the report! In this case, I've included the three highlight variants we need in [this Resources folder](https://github.com/Microsoft/HolographicAcademy/tree/Holograms-210-Gaze/Completed/ModelExplorer/Assets/Resources/Models/AstroMan/Materials), as mentioned in Unity's recommendations above. They're the three with "highlight" in the name. I'll add a note to 210 to call this out.
