### ISSUE TITLE
vNext Issue: Cannot map inputs at runtime

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2432]
## Overview
In testing today, I discovered that we can only load the InputManager at build time.  The classes are not available at runtime.

Need to refactor / break this dependency, as builds only work in the editor.

## Expected Behavior
Need to be able to manage Inputmappings for Axis

## Actual Behavior
Current code breaks in a build, as it's currently (and seems only will ever be) editor specific.

**Comment by StephenHodgson** [comment]
Could you explain this a bit better?

**Comment by SimonDarksideJ** [comment]
lol, it doesn't work.  SerializedObject, which is needed to read the Inputmanager.asset, can only be used in the Editor.  So, going to another PR to resolve this :S

**Comment by StephenHodgson** [comment]
Ah, That makes since. We can only update the input axes at edit time not runtime.

Let's just be sure to add all our axes for all platforms in one go.  Then in the implementation we can just make sure they exist, and throw warnings or errors.

**Comment by SimonDarksideJ** [comment]
Should only add the Axis values for those controllers the user has configured!.
Almost finished working up the PR. It ain't pretty, but it'll work :S

**Comment by davidkline-ms** [comment]
> Should only add the Axis values for those controllers the user has configured!. Almost finished working up the PR. 

Is it sufficient to instruct the developer to add all of the controls that _they_ need? Or is this to allow end-users to customize mappings once an app has been released?

>It ain't pretty, but it'll work :S

What makes it "not pretty"?

**Comment by SimonDarksideJ** [comment]
Like with the HoloToolkit, We need to control the names of the Axis in the Unity InputManager, as they are referred to in code.
As our controllers are purely code, there isn't anywhere to enable us to have config options, plus they are tightly bound to the physical inputs. Would be horrible to force devs to manually setup all the inputaxismappings with the correct Axis / variables and data in Unity.

Controlling the mappings for them is cleaner and safer (until we can rip all this stuff out with something better :D)
