### ISSUE TITLE
Question: Import 2018.2 Packages for target VR platforms?

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2434]
## Overview
With the 2018.2 upgrade, Unity now lists WMR and OpenVR as separate "Packages"
Currently the lack of these bears no impact, however, should we be preemptive and add these package definitions to the MRTK vNext project.

## Option 1
Import the WMR / OpenVR packages (review if any others are interesting)
Review packages defined and remove any we don't care about

## Option 2
Do nothing :D, it currently works and we should wait until it doesn't?
Or simple advise consumers to add the packages.

**Comment by davidkline-ms** [comment]
I tend to lean toward option 1. 

If this causes 2018.1 to stop loading our project, we will need to discuss further.

**Comment by SimonDarksideJ** [comment]
Ok, we'll schedule this for the start of Beta, to avoid impacting the Alpha (as there is no current issue)

**Comment by StephenHodgson** [comment]
So if they moved the VR from SDKs to Packages, does that mean we can directly talk to the native plugins?

**Comment by StephenHodgson** [comment]
I noticed that the OpenVR package has the dll accessible. That means we should be able to get input directly from there.  I didn't look at Oculus yet, but hopefully it's the same.

**Comment by keveleigh** [comment]
Both WMR and OpenVR are now defined in our [Packages/mainfest.json file](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Packages/manifest.json#L10).
