### ISSUE TITLE
Can't type in an InputField when looking at a real keyboard

### ISSUE THREAD

**Issue by ThomasAstrakhan** [Microsoft/MixedRealityToolkit-Unity#2439]
## Overview

- I want to use a bluetooth keyboard with the hololens. I need to look at my keyboard to type but when looking outside of the inputfield, it deselect itself.

1. Tap on an inputField to type some text

1. Move your hand to your real keyboard and move your head to look at your real keyboard. => The hololens will capture your movement and deselect the inputfield (because OnDeselect is called even if you do not click)

**I tried to create an empty public override OnDeselected in the KeyboardInputField script. It does not change anything**

![image](https://user-images.githubusercontent.com/39410322/42695234-061be71c-86b5-11e8-9cfd-bfb91c0f2035.png)

## Expected Behavior

The inputfield should be deselected ONLY if I click elsewhere or when using the ESC or RETURN key.

## Actual Behavior

The inputfield is deselected if I rotate my head while my hand is visible by the captors.

![oldbb](https://user-images.githubusercontent.com/39410322/42694210-e5c62804-86b1-11e8-9fdd-83123b12be24.gif)

(of course I'm still typing ffffffffff when the gaze is not on the inputfield anymore)

## Steps to reproduce
Use the KeyboardTest.unity scene in the example. 
If you want to test in the Unity Editor :

1. Create an inputField (not a keyboardinputfield. Or just add a return; on line 37 so it does not open the virtual keyboard)

1. Shift+left click on an inputField to select it

1. type some text with your keyboard

1. Move with the arrow so you do not look at the inputField anymore

1. press SHIFT to simulate that your hand is still visible

1. The inputField is now deselected 😭

If you want to test for real you need a bluetooth keyboard

## Unity Editor Version

2018.1.0

## Mixed Reality Toolkit Release Version

2017.4.0.0

**Comment by ThomasAstrakhan** [comment]
https://gfycat.com/UnsungLameKouprey
Here is a video to explain a bit more.

The first part (when I type ppppppppp)
is me, typing when continuously looking at the KeyboardInputField

The second part (when I type kkkkkkkkk)
is me typing when looking at my keyboard. This is the expected behavior, peoples want to look at their keyboard when writing down things.

The third part (when I type cccccccc)
is me like the first one, but the keyboard is on my lap and I try to look straight forward. (this is the actual working behavior and it's not a good user experience. Beside, in my video the inputfield is big, but for a e-mail adress inputfield it's aweful)

**Comment by charlesMP** [comment]
Have there been any updates on this? 
Running into the same thing.

**Comment by StephenHodgson** [comment]
I think most ppl are using the built in OS keyboard now. Not sure if this will be included in vNEXT.

**Comment by ThomasAstrakhan** [comment]
Try to write down an entire paragraph with the virtual keyboard. It's a pain.

I hope the 2018.1.7 fix the issue. But I don't know if it's related 🤷‍♀️

[(1048092)](https://unity3d.com/fr/unity/whatsnew/unity-2018.1.7) - XR: Fixed PressType on HoloLens incorrectly reporting Select instead of None.

**Comment by charlesMP** [comment]
Is the OS keyboard the one minimizes Unity and opens some weird generic window for text input?
Cause I was having issues with that, where text wouldn't migrate. Either to the text field or to my app.
Also its very jarring and confusing for the user as far as UX goes.

**Comment by StephenHodgson** [comment]
>Is the OS keyboard the one minimizes Unity and opens some weird generic window for text input?

No, in RS4/5 it should open the keyboard without leaving the app

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
