### ISSUE TITLE
vNext Task: Track Head Pose

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2440]
## Overview
After reviewing different VR / MR / XR concepts, we need to support interactions that use / capture a head pose.   This can be used in various ways:
* To inform Gaze/Focus as an actual interaction, not inference from the headset
* To capture the headsets position in the real world
* To be able to align pointers with interaction with hands/controllers to provide an active focus

## Requires
Headset definition in the devices space
Provide headset value / pose for each platform
Enable visualisers to track pose (likely already partially implemented with Gaze/Focus)
Enable combined pose, Head to hand confirmation of active pose

## Acceptance Criteria
- [x] I can track pose information from the headset
- [x] I can visualize the headset pose
- [ ] I can interact with a hand or controller to provide an active pose
- [ ] Visualize an active pose (combined head / hand)

**Comment by Yoyozilla** [comment]
This is available in v2.
