### ISSUE TITLE
Unable to attach Tool Tip Spawner at runtime 

### ISSUE THREAD

**Issue by CharcoalStyles** [Microsoft/MixedRealityToolkit-Unity#2447]
## Overview
I'm creating a bunch of GameObjects at runtime and want to add tooltips through the Tool Tip Spawner to them. Unfortunately all the properties in the class are private and therefore are unable to be set in another class.

## Expected Behavior
Adding a ToolTipSpawner object to a GameObject at runtime would allow me to set all the properties, to create a working ToolTipSpawner on the GameObject.

## Actual Behavior
Adding a ToolTipSpawner object to a GameObject at runtime works, but the required properties are set as private in the original class.

## Steps to reproduce
1. Create a GameObject.
2. Add a ToolTipSpawner to the game object .
3. Try to set any of the properties.

## Unity Editor Version
2018.1.2f1

## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by isurfraz** [comment]
I am not sure how microsoft want this to be used, but we found that every bit of holotoolkit we liked we recreated as our own script. THis means you can do in place updates to holotoolkit without breaking your app, but also can customize anything you dont like.

I recommend building your own tooltipspawner using theirs as a base, with the bits you want public set to public.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
