### ISSUE TITLE
How many world anchor can we safely store in world anchor store database?

### ISSUE THREAD

**Issue by Shubham7694** [Microsoft/MixedRealityToolkit-Unity#2448]
## Overview
I will be placing world anchor for different types of entities. Is it safe to use if world anchors count in api cross say 500. Does this impact store ready time? If so, any pointers.
## Steps to reproduce
_(Links to sample github project preferred)_

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
