### ISSUE TITLE
"No pointer source end point" assertion in RaycastUnityUI

### ISSUE THREAD

**Issue by PJBowron** [Microsoft/MixedRealityToolkit-Unity#2450]
## Overview
Just a question regarding this assertion...

I have an odd situation where having a MeshCollider in certain positions causes this FocusManager assertion to fire. I can see that it warns against `pointer.End.Point` being zero, but it will also fire when the Collider's position is _almost_ zero - say, a fraction off along the y-axis, and perhaps more strangely, it does **not** fire when the Collider's position **is** exactly zero!

I guess my question is two-fold: why would the collider hit point be exactly zero when the Collider's transform is not (and vice-versa), and more importantly, why does it matter? `RaycastUnityUI`'s continues to execute without ill effects even if `pointer.End.Point == Vector3.zero`.

## Expected Behavior
Colliders can be placed anywhere in the scene without issue.

## Actual Behavior
Assertion fires in certain circumstances:
`(pointer.End.Point != Vector3.zero, "No pointer source end point found to raycast against!")`

## Unity Editor Version
2017.4.1f1

## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by StephenHodgson** [comment]
I think I actually removed this assertion in vNEXT. There are some cases when this is fine.

**Comment by rafek** [comment]
Removed it in #2456.

**Comment by keveleigh** [comment]
Fixed via #2456.
