### ISSUE TITLE
Update Standard shader to be LRP compatible

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#2463]
## Overview
More of an experiment as I haven't even tried the standard shader in the Lightweight Render Pipeline.  But it would be good to ensure the Standard shader is either supported in the LRP, or make a LRP Standard shader

## Expected Behavior
Standard Shader works in LRP

**Comment by Cameron-Micka** [comment]
Sounds like a good idea to test this! I can role this into my next PR if anything needs to change.

**Comment by isurfraz** [comment]
@SimonDarksideJ @Cameron-Micka I am actually doing experiments right now with LWRP and trying to make a slimline LWRP compatible hololens shader. I will update you with progress. BUt would be very nice if on your end you could get the holotoolkit working with the LWRP standard shader. From looking at its code it has some optimisations for XR, and the rendering pipeline also seems to be in general optimised for AR and VR as well as mobile hardware (such as the hololens has).

**Comment by SimonDarksideJ** [comment]
Out LWRP efforts will likely be solely focus on the vNext project, as it is more streamlined and memory efficient already @isurfraz 
We welcome any contribution towards the goal of making MRTK even better :D

**Comment by isurfraz** [comment]
@SimonDarksideJ in that case if I manage to get any decent headway on this in the meantime I will update you both regarding this :)

On a side note, does the vNext project offer any optimisations itself as we are using the release map for this project and hoping to incorporate it when it drops!

**Comment by isurfraz** [comment]
@SimonDarksideJ @Cameron-Micka @StephenHodgson  does a pull of vNext cause any errors or breaking changes? or is it possible to test this in projects now?

**Comment by SimonDarksideJ** [comment]
Best to have this conversation on the Slack channel, in the holodevelopers chat.
vNext hasn't yet reached the Alpha stage, it's close but not there yet.

**Comment by Cameron-Micka** [comment]
"Bumping" this since is something that should be tackled soon, especially once we move to Unity 2019.1 or greater since it takes the LWRP out of preview.
