### ISSUE TITLE
Custom Buttons for AppBar on Bounding Box 

### ISSUE THREAD

**Issue by charlesMP** [Microsoft/MixedRealityToolkit-Unity#2464]
## Question 

I'm trying to add a CustomButton to the AppBar under the BoundingBox and am running into some confusion. 

Mainly how am I supposed to add my own functionality to the CustomButton's OnTappedEvent? 
(For reference I need a play button for video/audio objects that can be placed in my scene.)

Since the AppBar gets instantiated at run time through the BoundingBoxRig I am unable to set the function in inspector. (The my object is also created at run time.)
Past that the instances of AppBars and BoundingBoxes are private members of the BoundingBoxRig so I can't access them in my code. 

Was hoping to be able to use this without editing the Toolkit's code base so my stuff just doesn't get overwritten the second there is a update.

**Comment by ThomasAstrakhan** [comment]
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2408

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
