### ISSUE TITLE
Migrate master branch fixes to mrtk_development

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2465]
List of known fixes that need to be migrated from master -> mrtk_development.

This is a work in progress, *DO NOT* close this issue until vNext release 1 is complete.

- [x] #2245
- [ ] #2306
- [ ] #2457 
- [ ] #2459 
- [ ] #2487

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
