### ISSUE TITLE
Gaze through objects (i.e. Multi-Level focus)

### ISSUE THREAD

**Issue by sibutorovic** [Microsoft/MixedRealityToolkit-Unity#2468]
## Overview
Hello, 

I'm sorry if this is simple or obvious but couldn't find information about this in the documentation nor in the closed issues. Is there any way to activate the focused event of an object that is behind another while also activating the same event on the one in front?

I have a quad with a button somewhere in front of it and I when I gaze at the button, the quad's onFocusExit is activated while the button's onFocusEnter is activated. Disabling the button's collider or ignoring its layer on the focus manager won't help because I need to listen for its onFocus events too.

The behaviour I seek is that the quad's OnfocusExit doesn't get activated when gazing at an object that is in front of it, while also activating said object's onFocusEnter.

Thanks!
## Unity Editor Version
2018.1.0f2
## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by davidkline-ms** [comment]
Hi @sibutorovic!

Thanks for the suggestion. I don't believe this is currently supported, but is a compelling feature request.

If you would like to investigate / submit an implementation (where the default behavior is to match 2017.4.0.0), we would love to take a look! If not, we will add to our backlog.

Thanks!

**Comment by StephenHodgson** [comment]
I'm not sure this is a desired behavior. There should only be one focused object at a time per pointer.

I could see having a list of the last raycast hits in order from closest to farthest GameObjects, but ideally you'd only want one focused object per pointer at a time. This would have rippling effects in other components that rely on reacting to focus, such as pointers, cursors, hover effects, and input logic that directs input to specifically focused GameObjects.

**Comment by StephenHodgson** [comment]
Could you explain exactly what you're trying to do a bit more?

You could add a reference to each other and call into the other whenever an event you're listening for is triggered.

**Comment by sibutorovic** [comment]
Sorry for the late reply, I'll try to explain what I wanted to achieve.

What I am trying to do is to disable a list of tagalong-like objects when the user is gazing at a certain quad with information which is hard to read with the those objects enabled. When the gaze enters the quad, a for loop is used to disable the objects manually. When the user gazes out of the quad, a similar for loop is used to reactivate them. 

The quad has a button on one of its corners. The button has the same script as the quad that disables the objects on focus. When the user, while gazing at the quad, gazes to the button instead, two events fire:

- OnFocusExit on the quad: This enables the objects.

- OnFocusEnter on the button: This disables the objects again.

Since the for loops are rather costly and I expect the list to grow in the future, I don't want to activate and deactivate the objects when going from the quad to the button.

I know there are several workarounds, like the rippling one Stephen mentioned, but to me it seemed more natural to know which objects are in the way that I'm looking. In this particular case, every time I'm gazing at the button, I'm also gazing at the quad.

However, while typing this I thought of a solution that seems better. Every time OnFocusExit fires, I'll have to check what object I am hitting after exiting. If the object is the button, don't enable the list of tagalongs, if not, enable them. I don't know if this is the correct way to go design-wise, but it sounds better than my current solution so I'll give it a try.


Thanks.

**Comment by StephenHodgson** [comment]
Why not keep a list of activated menu items, and let the focus fire as needed, and when reactivated just check the state and do the logic needed?

**Comment by sibutorovic** [comment]
Yes that is what I thought too, but to make it work I would need to know what Object I am gazing like I mentioned on my last response.  This is because the gaze can blur objects in two different cases:

- Button/Quad -> No Object:  All the objects should be reactivated.
- Button -> Quad (or vice versa): All the objects should be deactivated.

Having multi level focus would have been handy, but this works and  is what I am doing now.

Thanks for your help.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
