### ISSUE TITLE
Spectator View (Preview) - Can't build for iOS

### ISSUE THREAD

**Issue by SimonB2011** [Microsoft/MixedRealityToolkit-Unity#2470]
## Overview
When using the example for Spectator View (preview) I switch to iOS build with platform Switcher.  3 errors are then displayed preventing compiling. 

Assets/HoloToolkit/Input/Scripts/InputSources/DictationInputManager.cs(210,20): error CS0103: The name `dictationRecognizer' does not exist in the current context

Assets/HoloToolkit/Input/Scripts/InputSources/DictationInputManager.cs(215,13): error CS0103: The name `PhraseRecognitionSystem' does not exist in the current context

Assets/HoloToolkit/Input/Scripts/InputSources/DictationInputManager.cs(216,13): error CS0103: The name `isTransitioning' does not exist in the current context

## Expected Behavior
When using platform switcher to enable iOS build there should be no errors generated.

## Actual Behavior
Errors are created as the native Microsoft STT and TTS libraries are not present in the build config. 

## Steps to reproduce
Download MRTK Unity master, add HoloToolkit and HoloToolkit-Preview to the Unity project Assets.  Add the Spectator view example (HoloToolkit-Examples\SpectatorView), add generated DLLs to HoloToolkit-Preview\SpectatorView\plugins folder.  Switch to iOS with Platform switcher in the example scene. 

## Unity Editor Version
2017.3.1p4

## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by danielescudero** [comment]
Looks like DictationInputManager is not platfrom-safe

**Comment by keveleigh** [comment]
I'll take a look at this today.

**Comment by keveleigh** [comment]
This was fixed in https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2275 and will be in the next release. You can also pull the current June dev branch to get the fix.
