### ISSUE TITLE
Input Mapping layout needs to be updated to be able to see Input Type config

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2474]
## Overview
Currently the layout of the Input mapping grid for interactions has equal weight for all three columns.  However more space is needed for the input types and possibly the Action.

This the spacing needs to be altered to reduce the width (if possible) to the Axis type and give more space to the other two columns.  If possible and reduce the spacing between the columns to give more visibility.

The screenshot below highlights the readability issue with some input types

![image](https://user-images.githubusercontent.com/1793042/43033621-77fe8c58-8cc4-11e8-9144-c7080a6e536c.png)

**Comment by davidkline-ms** [comment]
I'm a bit puzzled on the second column... Why is there a dropdown for axis type? We cannot change a button from Digital to something else, so why isnt it just a simple text field?

I've seen some pretty straight forward systems on other engines. Perhaps we can do something similar (i'll mock something up "soon")

**Comment by StephenHodgson** [comment]
It'll end up being a simple drop down with actions

**Comment by SimonDarksideJ** [comment]
We've been having a lot of discussions on this @davidkline-ms 
For Alpha, we're going to disable the "advanced" view where you can create mappings.  Instead, you will only be able to configure the actions for the predefined inputs setup for the controllers.

We need more time to review the cases where someone may want to setup their own mappings.

Another thing missing, which will also likely be done in beta, is the filtering of the selected Actions by their AxisType, so only configured actions for a specific action type with the corresponding axis can be selected.

**Comment by StephenHodgson** [comment]
Here's a few concepts for assigning actions I came up with over the weekend.

![image](https://user-images.githubusercontent.com/13334553/44318299-0cf72b80-a3ea-11e8-8c50-a01ab114b93c.png)
![image](https://user-images.githubusercontent.com/13334553/44318302-12ed0c80-a3ea-11e8-8c22-2aa4f8654569.png)
![image](https://user-images.githubusercontent.com/13334553/44318307-17b1c080-a3ea-11e8-9d02-31b5e383f3b4.png)

**Comment by SimonDarksideJ** [comment]
This looks fantastic and more along the lines of a real stand out feature of the MRTK.  No one else has anything like this (steam comes close)
