### ISSUE TITLE
vNext Task: Performance review - ALPHA

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2478]
## Overview
Prior to the Alpha cutoff, we need a final Performance / review check on each Alpha target platform

## Requires
Performance Review on UWP platform
Performance Review on OPENVR platform

## Acceptance Criteria
- [x] No perceptible lag through input system on UWP
- [x] No perceptible lag through input system on OPENVR
- [x] No unnecessary logging
- [x] Any remaining performance leaks documented and tasks created for Beta for review

**Comment by davidkline-ms** [comment]
I am seeing the lag that @SimonDarksideJ mentions when running via OpenVR. Looking into it.
