### ISSUE TITLE
Spatial Understanding Shape HalfDims always returns (0,0,0)

### ISSUE THREAD

**Issue by benjaminboxler** [Microsoft/MixedRealityToolkit-Unity#2485]
## Overview
When using `SpatialUnderstandingDllShapes.QueryShape_FindPositionsOnShape(...)` and querying `halfDims` they always return (0,0,0).

## Expected Behavior
halfDims returns correct dimensions

## Actual Behavior
halfDims returns (0,0,0)

## Steps to reproduce
Using my SpatialUnderstanding tutorial [here](http://boxler.me/SpatialUnderstandingShapes.html) and trying to access `shapeResult[0].halfDims` inside the `InstantiateObjectOnTable()` func always returns (0,0,0)

## Unity Editor Version
2017.4.3f
## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
