### ISSUE TITLE
App wont run after a 2018.2 IL2CPP build

### ISSUE THREAD

**Issue by yanivx4x** [Microsoft/MixedRealityToolkit-Unity#2486]
## Overview
Hello,
For the last two months, I have been building an app using holotoolkit with great success at developing and deploying to the device.
I have been using .net scripting backend, and after upgrading my unity version to 2018.2 I decided to start using IL2CPP as my back, since its recommended.
I have managed to deploy and use a smaller app that I used for testing using 2018.2 and IL2CPP and it worked perfectly fine.
Today I've built my main app using IL2CPP and the build succeeded.
I've installed the app on my hololens, but after launching it, a few moments after the unity splash screen, the device just exits the application back to the main desktop.
I've deployed the app using Visual Studio 2017 and saw that when the programs start an exception detailed as "Exception thrown: write access violation.
__this was nullptr." is thrown multiple times and various cpp scripts in the code.
Any ideas?
## Expected Behavior
The app will run normally.
## Actual Behavior
The build is marked as a success but receiving multiple "Exception thrown: write access violation.
__this was nullptr." errors.
## Unity Editor Version
2018.2
## Mixed Reality Toolkit Release Version
2017.4.0.0

Thank you in advance, and sorry for my English as it is not my native language.

**Comment by StephenHodgson** [comment]
Which cpp scripts are throwing them?

**Comment by ThomasAstrakhan** [comment]
@yanivx4x how did you manage to deploy your app ? I couldn't find the button in my visual studio : https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2419

**Comment by yanivx4x** [comment]
@ThomasAstrakhan I used unity build window that comes with holotoolkit.
@StephenHodgson about 15 different places that got generated by IL2CPP , I can't understand semantically where they refer to. I'll update that using 2018.1 and .net scripting I got it working. Bummer is I want to advance and I've got a dll that only works with IL2CPP.. I'm trying now with a different machine , will update.

**Comment by yanivx4x** [comment]
Ok so after a few attempts to isolate the issue, I've found the problematic script that was part of a demo inside a 3D model asset folder. I am not sure why he was causing the problem with il2cpp, but ill add its content here for future references.

**CODE**
`
using UnityEngine;

namespace Cleverous.Shared
{
    public class FadeCamera : MonoBehaviour
    {
        public AnimationCurve FadeCurve = new AnimationCurve(new Keyframe(0, 1), new Keyframe(0.6f, 0.7f, -1.8f, -1.2f), new Keyframe(1, 0));
        private float _alpha = 1;
        private Texture2D _texture;
        private bool _done;
        private float _time;

        public void Reset()
        {
            _done = false;
            _alpha = 1;
            _time = 0;
        }

        [RuntimeInitializeOnLoadMethod]
        public void RedoFade()
        {
            Reset();
        }

        public void OnGUI()
        {
            if (_done) return;
            if (_texture == null) _texture = new Texture2D(1, 1);

            _texture.SetPixel(0, 0, new Color(0, 0, 0, _alpha));
            _texture.Apply();

            _time += Time.deltaTime;
            _alpha = FadeCurve.Evaluate(_time);
            GUI.DrawTexture(new Rect(0, 0, Screen.width, Screen.height), _texture);

            if (_alpha <= 0) _done = true;
        }
    }
}



`
