### ISSUE TITLE
Unity line does not respect color and width offsets.

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2498]
## Overview
Unity line does not respect the color and width offsets.

The unity line class has an animation curve for the width over the length of the line. When adjusting the offset, the inspector Gizmo updates correctly, but then does not update the animation curve appropriately.

Color is handled by a gradient that is also not updated when the offset is changed, but the Gizmo updates correctly.

## Steps to reproduce

1. Open line example scene.
2. Select any line with a unity line component. (I used spline)
3. Adjust the color and/or width offset on the line renderer component.
4. Note the current approximate value of the line via Gizmo.
5. Press play in editor and compare to generated line renderer.

## Mixed Reality Toolkit Release Version
Latest master branch.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
