### ISSUE TITLE
vNext: Gizmo prefabs "no meshrenderer" errors

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2500]
The models that were imported for the Gizmo prefabs have a mesh renderer down in the hierarchy. Unity is throwing a MissingComponentException when the visualizer tries to fetch it.

MissingComponentException: There is no 'MeshRenderer' attached to the "GizmoLeft(Clone)" game object, but a script is trying to access it.
You probably need to add a MeshRenderer to the game object "GizmoLeft(Clone)". Or your script needs to check if the component is attached before using it.
```
UnityEngine.Renderer.get_material () (at C:/buildslave/unity/build/Runtime/Export/GraphicsRenderers.bindings.cs:123)
Microsoft.MixedReality.Toolkit.Tests.ControllerVisualizer.UpdateControllerVisuals () (at Assets/MixedRealityToolkit-Examples/Test/ControllerVisualizer.cs:65)
Microsoft.MixedReality.Toolkit.Tests.ControllerVisualizer.Update () (at Assets/MixedRealityToolkit-Examples/Test/ControllerVisualizer.cs:134)
```
We either need to modify the model (and learn how) or have the script ask for renderers on children as well.

**Comment by StephenHodgson** [comment]
Why don't we just use the default position handle gizmo in the editor?

It's not like we're going to have ppl use these arrows in a final build

**Comment by davidkline-ms** [comment]
this stems from calls in the test scene (from #2478) that is not querying deep enough for the renderer. I thought it might be part of the perf issue, but it is not.

I would still like to understand how best to fix this going forward as we may encounter models with this issue in the wild.

**Comment by keveleigh** [comment]
I don't think there's anything to fix here, since it was a test script that hasn't been (and won't be?) checked into the Toolkit was throwing the error, right?
