### ISSUE TITLE
vNext Task: Replace UAudioManager with MRTK Audio Manager v2

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2504]
## Overview
The UAudioManager system has been updated to be more developer and designer friendly. Replace with the new MRTK Audio Manager from @joekellyms.

## Requires
New Audio Manager
How-to documentation
API documentation
Demo scene(s) illustrating key functionality

## Acceptance Criteria
- [ ] Audio Manager fully functional
- [ ] Audio Manager UI is easy to read when using both the light and dark UI setting
- [ ] Conceptual documentation staged to docs.microsoft.com
- [ ] Demo scene(s) created

**Comment by Yoyozilla** [comment]
audio will be an extension
