### ISSUE TITLE
vNext Task Define Spatial Mapping abstraction

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2508]
## Overview
Multiple platforms (ex: HoloLens, ARKit, ARCore, Magic Leap) provide environmental data in various forms. The core layer needs an abstraction that make it easy to consume in the desired format (mesh, points, planes) in the SDK.

## Requires
Interface defining the spatial mapping abstraction
Default implementation of the system

## Acceptance Criteria
- [x] Interfaces defined
- [x] Default implementation created and working on HoloLens

## Notes
ARKit and ARCore are coming online after the initial release. We will need to take are with the design / testing to avoid need for breaking changes.

**Comment by clearsitedesigns** [comment]
Would love the ability to classify objects that are known in the point cloud system, and have a referential way to understand the digital objects in relation to the physical spaces. This includes the ability to apply meta and contextual data to the objects for later capability for advanced pattern recognition of like and similar object systems. This gives us the ability to think about physical objects in digital terms and apply contextual meaning to deeper interaction, meta-interaction states and to identify new ways to think about dimensional user experiences across dimensional occupancy.

I talk a lot more about this from a user experience side in the following document. I know it's a tall order, but by doing so we start to understand the connection of what I call Living interactions systems and the experiential glue between these systems regardless of device level access or building up of existing, new or proto-reality states.

https://www.linkedin.com/pulse/teaching-next-evolution-ux-design-thinking-shifting-towards-mccauley/
