### ISSUE TITLE
vNext Task: Define sharing abstraction

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#2509]
## Overview
Sharing is a core part of compelling mixed reality experiences. We need to provide a consistent and extensible system to enable sharing over a variety of networking implementations.

## Requires
Interface defining our sharing system
- Discovery
- Connection management
- Anchor transfer
- Data transfer
Conceptual and API documentation
SDK component(s)

## Acceptance Criteria
- [ ] Sharing system interface defined
- [ ] One or more implementations created (start with UNet?)
- [ ] Conceptual documentation staged on docs.microsoft.com
- [ ] Sharing demo scene

**Comment by wassx** [comment]
There a few things I have in mind which troubled us with UNet:

- [ ] Syncing of collections and sending a full array in correct order
- [ ] Handling of message queue overflows
- [ ] Encryption of data transport. E.g. transforms not encrypted but for data consumers of sensitive data I can chose an encryption.
...thinking...

**Comment by Yoyozilla** [comment]
Sharing will be a standalone component hosted in a new GitHub repo. you can join the public sharing shiproom for weekly updates.
