### ISSUE TITLE
MR Camera gets black screen when loading large asset bundle even when loading asynchnously

### ISSUE THREAD

**Issue by marklinmao** [Microsoft/MixedRealityToolkit-Unity#2515]
## Overview
Mixed Reality Camera gets black screen when loading large asset bundle, even when loading asynchronously with the method below:
assetbundle.LoadAssetAsync<GameObject>(prefabName);

## Expected Behavior
The camera should not be effected when loading assets asynchronously.

## Actual Behavior
The MR camera turns black and user have to wait until it's loaded

## Steps to reproduce
Create a new MR(VR) project. Prepare a large asset bundle ( e.g. bundle file >1MB ). Load asset bundle with method: assetbundle.LoadAssetAsync<GameObject>(prefabName)

## Unity Editor Version
2018.2.0f2 (Personal)

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-2017.4.0.0

**Comment by StephenHodgson** [comment]
Could you please provide more detailed repro steps?

**Comment by marklinmao** [comment]
Firstly of all, my goal is to have it loading(large size asset bundle) asynchronously without effecting user's action in the scene, and preferably have a progress-bar to indicate the loading progress. Below are the steps:

1. Prepare an large size asset bundle, the one that I use is 3.8MB (bundle size) and 60MB (prefab size including relevant resources). Put the asset bundle in your file system or in a HTTP server(locally), below code retrieve bundle from HTTP server.

2. Create a VR project, apply 'Mixed Reality Scene Settings' in MRTK

3. Create an object(e.g. a cube), add a script and handle the click event, when the cube is clicked, use below method to load the assetbundle.

private IEnumerator LoadModelABFromServerAsync(string modelURL, string prefabName, bool isLast)
{
    UnityWebRequest uwr = UnityWebRequestAssetBundle.GetAssetBundle(modelURL);
    yield return uwr.SendWebRequest();

    if (uwr.isNetworkError || uwr.isHttpError)
    {
        Debug.Log("Network error: " + uwr.error);
    }
    else
    {
        AssetBundle loadedAB = DownloadHandlerAssetBundle.GetContent(uwr);
        AssetBundleRequest abRequest = loadedAB.LoadAssetAsync<GameObject>(prefabName);

        // Wait for completion
        yield return abRequest;

        // Get the reference to the loaded object
        GameObject loadedObj = Instantiate(abRequest.asset as GameObject);

        // Unload the AssetBundles compressed contents to conserve memory
        loadedAB.Unload(false);
    }

    // Frees the memory from the web stream
    uwr.Dispose();
}

4. Start the scene, click the cube to load the asset bundle. The code is executed asynchronously but the camera gets black for a few seconds.

Please comment if anything wrong in the code. Thank you.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
