### ISSUE TITLE
Update CompoundButton components to use TextMeshPro

### ISSUE THREAD

**Issue by lordlycastle** [Microsoft/MixedRealityToolkit-Unity#2520]
## Overview
Currently the CompoundButtonText script and prefabs use TextMesh which is inferior to TextMeshPro. TextMeshPro is an official Unity package with no scaling issues. 
## Expected Behavior
...
## Actual Behavior
The prefabs and scripts are using TextMesh.
## Steps to reproduce
_(Links to sample github project preferred)_
Example Project
## Unity Editor Version
2017.4.4.1
## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by SimonDarksideJ** [comment]
This will be addressed in vNext.

**Comment by lordlycastle** [comment]
@SimonDarksideJ Is that the next release? First time hearing about vNext.

**Comment by SimonDarksideJ** [comment]
:D, welcome to the brave new world.  vNext is the next generation for the Mixed Reality Toolkit which aims to be more performance and provide cross platform XR/VR/AR/MR/XXXR.
Full details in the roadmap
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Roadmap.md#mrtk-version-next
