### ISSUE TITLE
The indicator line of the motionControllers does not coincide with the starting point of the ray

### ISSUE THREAD

**Issue by jerrygg** [Microsoft/MixedRealityToolkit-Unity#2523]
## Overview
The indicator line of the motionControllers does not coincide with the starting point of the ray,
Cause small objects in the vicinity to not trigger.
## Expected Behavior
The starting point of the two lines should coincide
## Actual Behavior
The indicator line of the motionControllers does not coincide with the starting point of the ray

## Steps to reproduce
1.Open HoloToolkit-Examples/UX/Scenes/InteractableObjectExample.unity
2.Check the DebugDrawPointingRays property of the FocusManager.

## Mixed Reality Toolkit Release Version
![tupian](https://user-images.githubusercontent.com/7133614/43452033-072e1c50-94e9-11e8-8bbd-179d9743117d.png)
![4](https://user-images.githubusercontent.com/7133614/43452920-37c6a074-94eb-11e8-8e05-86298025a171.png)

**Comment by keveleigh** [comment]
Fixed in the [2017.4.2 release](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/2017.4.2.0).
