### ISSUE TITLE
BugFix: ObjectCollection doesn't behave as expected with non-zero rotation.

### ISSUE THREAD

**Issue by lordlycastle** [Microsoft/MixedRealityToolkit-Unity#2526]
## Overview
Go to object collection example scene, change the rotation of one of the parents  and click update. The objects will be facing is incorrect direction when you choose Sphere or Cylinder.
## Expected Behavior
The collection should be facing as is set in editor.
## Actual Behavior
The collection does not face the correct transform.
## Steps to reproduce
_(Links to sample github project preferred)_
ObjectCollectionExample
## Unity Editor Version
2017.4.4.1
## Mixed Reality Toolkit Release Version
2017.0.0

## Fix
I have the fix but creating a pull request is a pain in the bottom (I wanna help, not learn 10 new things), especially since I can't even find the file in repo. Anyways if you wanna be the hero of the hour find `ObjectCollection.cs` and change lines 287, 294, 326 and 332 from:

     NodeList[i].transform.rotation = Quaternion.LookRotation(newRot);

to: 

    NodeList[i].transform.LookAt(transform);

And you wanna be the knight in shining armour go ahead is remove that `newRot` variable if it's not being used.

*Note: the lines #s might be slightly difference, I made a few more changes.*

**Comment by lordlycastle** [comment]
Actually this fix only works with 1 row. Aw well.

**Comment by lordlycastle** [comment]
Okay I have the solution for reals now. 

In cases of `Sphere` and `Cylinder` surface type with `FaceOrigin` and `FaceOriginReverse` orientation type change the `rotation` to `localRotation`.

    // NodeList[i].transform.rotation= Quaternion.LookRotation(newRot);
    NodeList[i].transform.localRotation = Quaternion.LookRotation(newRot);

**Comment by Ecnassianer** [comment]
This sounds like one of the bugs I fixed in https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2227
PR:
https://github.com/Ecnassianer/MixedRealityToolkit-Unity/commit/945401107c48493cd1e649c5a92090cf4710a7b8

It's in 2017.4.1.0, which I think is stabilizing for release right now. My changes add a bunch of other new features to collection as well if you want to check them out.

**Comment by keveleigh** [comment]
Sounds like this was fixed in the most recent HTK release. Please reopen if not.
