### ISSUE TITLE
Strip Mesh, Instanced Mesh, and Particle System Line Renderers do not properly apply colors

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2528]
## Overview
Stip Mesh, Instanced Mesh, and Particle System Line renderers do not properly apply the color chosen in the inspector.

## Steps to reproduce

1. Open lines example scene
2. Duplicate an existing line
3. Remove the Unity Line component
4. Replace it with any of the renderer components above
5. Change the color
6. Play in editor

## Mixed Reality Toolkit Release Version
master branch

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
