### ISSUE TITLE
vNext Task Flags enum coding style definition updates / cleanup pass

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2529]
## Overview
There has been some discussion among the moderators regarding the coding style of flags enums that include pre-defined combinations.

Clarify the style document and ensure that existing code conforms.

## Requires
Further discussion on the layout that is easiest to read and understand.
CodingGuidelines.md updates to document the decision
Cleanup pass on all _Core and SDK flags enums present in the code base

## Acceptance criteria
- [x] Moderators come to an agreement
- [x] CodingGuidelines.md updated per agreement
- [x] _Core and SDK flags enums cleanup pass

**Comment by StephenHodgson** [comment]
>  _Core and SDK flags enums cleanup pass

Good thing there's only two enums that use flags 😅
