### ISSUE TITLE
Add support for clicker

### ISSUE THREAD

**Issue by lordlycastle** [Microsoft/MixedRealityToolkit-Unity#2536]
## Overview
I find the clicker easier to use than having to hold my arm up due to the small FOV of the sensor. In the current state the Click/AirTap action works find. But we need to add support for dragging using the accelerometer data similar to how it is done in the system for dragging windows and scrolling windows. Currently only dragging only works in XY plane, it should also move in Z direction; unless the sensor is a gyroscope 

It would be nice to have access to the raw (XYZ) data of the sensor for other uses; maybe similar to how we get axis data from in unity for controllers.
## Expected Behavior
Use clicker's accelerometer data to drag and rotate objects.
## Actual Behavior
Not implemented.

## Unity Editor Version
--
## Mixed Reality Toolkit Release Version
2017.4.0

**Comment by StephenHodgson** [comment]
Pretty sure we already support the clicker.

**Comment by lordlycastle** [comment]
@StephenHodgson Which component would that be? AFAIK AirTap works but not dragging.

**Comment by StephenHodgson** [comment]
Related to https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/605#issuecomment-410188033

**Comment by keveleigh** [comment]
>It would be nice to have access to the raw (XYZ) data of the sensor

That data isn't exposed anywhere, as far as I know.

Additionally, manipulation, navigation, and tapping should all be already supported through our existing events. Are you running into issues using the clicker?

**Comment by keveleigh** [comment]
@lordlycastle Navigation and manipulation are some of the [composite gestures](https://docs.microsoft.com/en-us/windows/mixed-reality/gestures#composite-gestures) made available via the [`GestureRecognizer`](https://docs.unity3d.com/ScriptReference/XR.WSA.Input.GestureRecognizer.html). Manipulation is a typically used for scenarios like hologram movement, while navigation is often used for scrolling or rotation.

The Mixed Reality Academy courses can give you a good idea of specific feature areas. In this case, [MR Input 211: Gesture](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-211) shows some use cases for manipulation and navigation, as well as how to use them via the HoloToolkit. Typically, you'll probably only handle one of them in a single script, though that course implements them in the same script and swaps between them via speech commands.

**Comment by jorgeghospital** [comment]
> 
> 
> > Additionally, manipulation, navigation, and tapping should all be already supported through our existing events. Are you running into issues using the clicker?
> 
> @keveleigh Like I've said, I can only do AirTap, nothing else. What exactly do you mean by manipulation and navigation?

Dragging with controller (clicker) doesn't work for current build (Unity 2017.4.11.f1 and HoloToolkit 2017.4.1.0). As lordlycastle said, only tap events are received but movement is not performed. We've been testing that and controller always return false when trying to get its position (both TryGetPointerPosition and TryGetGripPosition) while it worked in past builds. Can anyone check that issue?

**Comment by rievo** [comment]
Same problem here. (Unity 2017.4.5f1 and MRTK 2017.4.1.0). The navigation support is not working anymore. Until now I could use dragging (navigation gesture) using the clicker, but now it doesn't work.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
