### ISSUE TITLE
Compound Button Speech does not work.

### ISSUE THREAD

**Issue by lordlycastle** [Microsoft/MixedRealityToolkit-Unity#2537]
## Overview
I can't seem to get the compound button speech working. Can anyone else? I'm using the holographic button prefab with all the compound buttons components. The `OnSpeechKeywordRecognized` is never called. Even when I'm gazing at the button.

Am I missing something.

## Expected Behavior
The speech commond/button text should call the 
## Steps to reproduce
Any scene with holographic button prefab.
## Unity Editor Version
2017,4,4,1
## Mixed Reality Toolkit Release Version
2017,4,0

**Comment by StephenHodgson** [comment]
Repro steps?

**Comment by lordlycastle** [comment]
@StephenHodgson Step listed below:

1. Open `InteractableObjectExample` scene. 
2. Select any compound button with text script. I chose `ToolbarButton1`. And add `CompoundButtonSpeech` on it. I also had to enable Mic access in publishing settings. 
3. In `ButtonReceiverExample` script in `InputDown` function add following code:

     var localPosition = obj.transform.localPosition;
     localPosition.y += 0.1f;
     obj.transform.localPosition = localPosition;

4. Build and deploy on Hololense. Try using the voice command. For me it was `One` as that was the text in the button.

**Comment by lordlycastle** [comment]
@StephenHodgson *Sidebar:* I remember reading in one of the issues here your thought on dislike of Unity Event while making a case for InputReciever. I can't find it anymore. If I recall correctly your point was that it is a choresome to assign unity events and sometime reference break. I would like to be the devil's advocate. 
1. Using a huge InputReciever with a switch statement can be slower because it has to go through all the possible actions. Even with a dictionary I imagine it wouldn't be as quick. 
2. I agree when you need to assign 10+ events it can be annoying. But you still have to do equivalent in code. You still need to store reference to the objects you need to call a function. You will have to keep track of this in your calling script rather than on the button gamobject. Which is not intuitive.  And these reference can be "silently" broken. 
3. When you use prefabing multiple buttons can be named the same which will be indistinguishable in the reciever. To get around it one could use the InstanceID of the object which comes with it's own problems. You do not know this in editor, you'll have to register the interactable object in run time (again more overhead). 
4. To reduce the execution time on the receiver's switch statement, one could use multiple of them InputReceivers. Again this is non-intuitive and would create a script mess as you need a different one for each type. 

These are some of the points I can think off my head. Let me know your thoughts and suggestions to get around these issues.

I think it would be best to stick with UnityEvents. It is understood by all developers, simple and elegant. I don't think there is a need to reinvent the wheel.

**Comment by StephenHodgson** [comment]
You might be referring to this https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/876#issuecomment-323417651

> Using a huge InputReciever with a switch statement can be slower because it has to go through all the possible actions. Even with a dictionary I imagine it wouldn't be as quick.

I suppose. We would need to have perf tests to see the real results there.  In either case, in vNext the way we've setup actions doesn't require the use of a switch statement, and is a simple id check.

> You will have to keep track of this in your calling script rather than on the button gamobject. Which is not intuitive. And these reference can be "silently" broken.

I really doubt that.  You'd almost always get a null reference exception, unless it was a struct.

**Comment by StephenHodgson** [comment]
You might be referring to this https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/876#issuecomment-323417651

> Using a huge InputReciever with a switch statement can be slower because it has to go through all the possible actions. Even with a dictionary I imagine it wouldn't be as quick.

I suppose. We would need to have perf tests to see the real results there.  In either case, in vNext the way we've setup actions doesn't require the use of a switch statement, and is a simple id check.

> You will have to keep track of this in your calling script rather than on the button gamobject. Which is not intuitive. And these reference can be "silently" broken.

I really doubt that.  You'd almost always get a null reference exception, unless it was a struct.

> When you use prefabing multiple buttons can be named the same which will be indistinguishable in the reciever. To get around it one could use the InstanceID of the object which comes with it's own problems. You do not know this in editor, you'll have to register the interactable object in run time (again more overhead).

Not sure what you mean here.

I'll have to look into points 4 & 5 for vNEXT to make sure we address some of these issues.

> I think it would be best to stick with UnityEvents. It is understood by all developers, simple and elegant in its obviousity. I don't think there is a need to move the wheel somewhere else in the car.

We're not removing the ability for developers to use UnityEvents, I'm just advocating against them, where possible. Their whole system is a bit convoluted to work with via scripting, but is easy visually.  See my comments about the trade offs in #876

**Comment by Pangels** [comment]
@lordlycastle look into #2343, hope that can help you.

**Comment by lordlycastle** [comment]
@Pangels thanks but that just confuses me more. 

What is the purpose of compound button speech, to get the text in the button? I thought it would get it and register it as a keyword.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
