### ISSUE TITLE
vNext Task Update Core namespaces

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2539]
## Overview
The SDK namespaces are all in the format: Microsoft.MixedReality.Toolkit.SDK.<feature>.
Core namespaces are Microsoft.MixedReality.Toolkit.Internal.<feature>.

To make our structure easier to understand, we should replace Internal with Core.

## Requires
Search/replace of Internal with Core in namespaces throughout Core and SDK files.
Discussion re: changing assembly names to not include "internal"

## Acceptance criteria
- [ ] Nothing breaks :)

**Comment by StephenHodgson** [comment]
Pre or post alpha?

**Comment by davidkline-ms** [comment]
> Pre or post alpha?

I currently have it post-alpha to reduce churn as we wrap it up.

**Comment by StephenHodgson** [comment]
Let's also move the systems into the final locations we decide as well when we implement this change.

**Comment by davidkline-ms** [comment]
Starting on this now...
