### ISSUE TITLE
GlobalListeners list get's mutated as we iterate the list.

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2541]
## Overview
Found a bug where the list of global listeners isn't always guaranteed to be executed if that list changes during the execution of that event.

## Expected Behavior
Global Listener Events should always be executed.

## Actual Behavior
If a GameObject registers or un registers during the ExecuteEvent loop, some objects later in the list will be skipped because the list index has changed.

## Mixed Reality Toolkit Release Version
MRTK vNEXT and Legacy HTK

**Comment by davidkline-ms** [comment]
Should be a fairly easy fix. Take a snapshot of the collection and iterate over that. 

Interesting factoid: this was a common bug that became easy to find when using foreach loops. You get an exception of the collection changes while iterating over the loop.

**Comment by StephenHodgson** [comment]
In vNEXT I just make Register and Unregister an async void task and just waited until the loop was finished before registering.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
