### ISSUE TITLE
Improve Boundary Manager with Markers

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2547]
## Overview
Rename and move the Boundary Indicator Demo script into either Core so devs can use it in any scene.
Improve the Indicator Marker Generation to account for variable height differences by adding collision logic and a later mask for calculating their height on a custom terrain/or scene objects.

## Requires
- Boundary Manager to include new property for enabling and disabling indicators.
- Boundary manager to include new property for layer mask to use when calculating indicator height

## Acceptance criteria
- [ ] Indicators can be used in any scene without a prefab
- [ ] Indicators will be offset by the collision height calculated
- [ ] Indicators will be placed on terrain/scene surfaces

**Comment by davidkline-ms** [comment]
what is the value of the indicators to an application? not against this idea, just wondering how it would be utilized in a non-demo app? this scene was expressly designed to show how to use the Contains() method of the Boundary Manager.

**Comment by StephenHodgson** [comment]
Not sure, but seems helpful.

Maybe devs would want to render the boundaries so that they're more themed to their app experience.

**Comment by davidkline-ms** [comment]
> Maybe devs would want to render the boundaries so that they're more themed to their app experience.

At that point, they could turn off auto-rendering and fetch the data from the manager, right? :)

**Comment by StephenHodgson** [comment]
Sure, but that's also why I suggested having a prefab option in the profile.
