### ISSUE TITLE
Open VR Controller Instances raise assertions when controller is on before playing in editor

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2548]
## Overview
Open VR controllers raise assertions about being registered with the Input Manger if the controllers are on before the editor starts.

## Expected Behavior
No assertions

## Actual Behavior
Assertions

## Steps to reproduce
Launch any scene with Open VR settings and both controllers enabled.

## Mixed Reality Toolkit Release Version
vNEXT Alpha

**Comment by SimonDarksideJ** [comment]
I had tested this and found no issues previously. What specific assertions are being raised
(And is it your implementation :P )

**Comment by StephenHodgson** [comment]
Haha, I haven't changed anything with the implementation of the open VR controllers.

It says they're being registered twice.

**Comment by keveleigh** [comment]
Probably a side-effect of no lost being fired. Might be a new Unity bug that we weren't seeing in previous builds?
