### ISSUE TITLE
Open VR controllers do not raise some UnityEditor.XR.Node events

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2549]
## Overview
Some UnityEditor.XR.Node events do not get raised properly.

When turning a controller off, the tracking lost and node removed events do not get raised by the editor.

## Steps to reproduce
Add the following to the Unity Interaction Events region in `OpenVRDeviceManger.cs`

```


        #region Unity InteractionManager Events

        private void InputTracking_nodeAdded(XRNodeState nodeState)
        {
            if (IsNodeTypeSupported(nodeState))
            {
                Debug.Log("Node added:" + nodeState.nodeType);
                GetOrAddController(nodeState);
            }
        }

        private void InputTracking_trackingAcquired(XRNodeState nodeState)
        {
            if (IsNodeTypeSupported(nodeState))
            {
                if (activeControllers.ContainsKey(nodeState.nodeType))
                {
                    Debug.Log("Tracking acquired:" + nodeState.nodeType);
                    var controller = GetOrAddController(nodeState);
                    InputSystem?.RaiseSourceDetected(controller?.InputSource, controller);
                }
            }
        }

        private void InputTracking_trackingLost(XRNodeState nodeState)
        {
            if (IsNodeTypeSupported(nodeState))
            {
                Debug.Log("Tracking lost:" + nodeState.nodeType);
                var controller = GetOrAddController(nodeState);
                InputSystem?.RaiseSourceLost(controller?.InputSource, controller);
            }
        }

        private void InputTracking_nodeRemoved(XRNodeState nodeState)
        {
            Debug.Log("node removed:" + nodeState.nodeType);
            activeControllers.Remove(nodeState.nodeType);
        }

        #endregion Unity InteractionManager Events
```

Start editor with open vr settings.
Turn controllers on, then off.

## Unity Editor Version
2018.1.9f1

## Mixed Reality Toolkit Release Version
vNEXT Alpha

**Comment by keveleigh** [comment]
I can repro this with Vive as well, on 2018.1.9f1. Might not be WinMR-specific.

**Comment by SimonDarksideJ** [comment]
Ok, so possibly an issue in the editor. What about an actual build?

And for Alpha, is this really an issue? SO long as controllers are detected and work. 
We do need to look for better "non Unity" methods of getting controller data

**Comment by keveleigh** [comment]
> What about an actual build?

Same thing.

>And for Alpha, is this really an issue? SO long as controllers are detected and work.

Agreed, cleaning up the controller model / source lost seems to be the only issue.
