### ISSUE TITLE
vNext Task rename transparent emerald or create all color transparent standard materials

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2558]
## Overview
If we are going to have a set of standard materials, we should have all forms in all colors. Currently, the teleport feature has defined MRTK_Standard_Emerald_Transparent for use with the teleport pointer.

## Requires
Rename the transparent emerald material to MRTK_Default_Teleport_Pointer (or similar)
- or - 
Create transparent materials for all of our standard colors.

## Acceptance criteria
- [x] Decide the approach
- [x] rename or create the material(s)
- [ ] Consider updating std material demo scene for ease of color comparisons on HoloLens and other see-through/AR devices.

**Comment by davidkline-ms** [comment]
> What is wrong with the current name?

Nothing, in and of itself. It does imply (at least to me) that it is one of many transparent standard materials

**Comment by Ecnassianer** [comment]
As someone who's always looking for an additive material for prototyping things, my vote's with adding transparent versions for all the standard colors. 

Green, Red, Blue, Yellow, Gray
Emerald, Ruby, Sapphire, Topaz, Quartz? :D

**Comment by StephenHodgson** [comment]
>As someone who's always looking for an additive material for prototyping things, my vote's with adding transparent versions for all the standard colors.

I'll second that.

**Comment by davidkline-ms** [comment]
> Green, Red, Blue, Yellow, Gray
Emerald, Ruby, Sapphire, Topaz, Quartz? :D

@Ecnassianer, see the Standard Assets\Materials folder to see what colors we currently provide. We are open for more if you want to make some :)
