### ISSUE TITLE
vnext bug: cannot teleport using OpenVR layer

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2562]
## Overview
Teleportation is working on Windows Mixed Reality, not OpenVR (on Vive or via Windows Mixed Reality Steam driver)

## Expected Behavior
Functional teleportation

## Actual Behavior
Stationary user

## Unity Editor Version
2018.1.9f1

## Mixed Reality Toolkit Release Version
vNext Alpha

**Comment by StephenHodgson** [comment]
Mostly bc the open vr layer's input mappings are wrong.  Did we have a task to fix that open already?

**Comment by davidkline-ms** [comment]
not sure. just filing as I find....

**Comment by davidkline-ms** [comment]
just checked.... we didnt have a bug filed

**Comment by StephenHodgson** [comment]
I'll do that now.
