### ISSUE TITLE
vNext Task cache unity layer masks at startup

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2564]
## Overview
Unity pre-defines a set of layers and gives them memorable names in addition to their numerical value. These values *could* potentially change.

To be more robust (and for our code to be easier to read) we should cache the pre-defined layer values at startup (lookup by name) so that any interested script can easily lookup the desired value.

## Requires
Component that handles layer value lookup with fields to easily provide these values to callers

## Acceptance criterial
- [ ] All current pre-defined layers are looked up and their values cached
- [ ] Current code referencing one or more layers updated to use the cache

**Comment by StephenHodgson** [comment]
Why do we need this, when we get a nice inspector mask anyway?
![image](https://user-images.githubusercontent.com/13334553/43790855-b21ecb66-9a28-11e8-90e3-a89041257197.png)

**Comment by davidkline-ms** [comment]
It's to replace the 1 << n in our code when initializing values. See discussion in #2545.

**Comment by StephenHodgson** [comment]
Why though?  I seriously don't think we need to do that.

**Comment by StephenHodgson** [comment]
`Physics.DefaultRaycastLayers` and `Physics.IgnoreRaycastLayer`
