### ISSUE TITLE
Iphone screen always says "Almost there..."

### ISSUE THREAD

**Issue by ChasingD** [Microsoft/MixedRealityToolkit-Unity#2578]
## Overview
I have built the both version of the application. However, when I show the marker to the HoloLens, my iphone screen says "Almost there..." and cannot proceed to the next step. 
## Expected Behavior
Iphone will excute the next step when the hololens scans the marker.
## Actual Behavior
My iphone screen display "Almost there".

## Unity Editor Version
2017.4.4f1
## Mixed Reality Toolkit Release Version
2017.4.1.0

**Comment by SiriusA7** [comment]
#2438  Duplicate

**Comment by keveleigh** [comment]
Closing per above linked duplicate.
