### ISSUE TITLE
Unity import with 900 warnings

### ISSUE THREAD

**Issue by dustin2711** [Microsoft/MixedRealityToolkit-Unity#2587]
## Overview
After I imported the "HoloToolkit-Unity-Examples-2017.2.1.1.unitypackage" in my project, I got 20 errors and after I fixed them by removing the code lines I got 900 warnings. That happens although my SDK is on right version10.0.16299.0.

## Expected Behavior
no errors, no warning
## Actual Behavior
~20 errors and after fixing 874 warnings
## Steps to reproduce
create a unity project, apply build settings for HoloLens (like in https://docs.microsoft.com/en-us/windows/mixed-reality/unity-development-overview), import MRK by Assets->Import Package->Custom Package

## Unity Editor Version
Version 2018.1.4f1 (1a308f4ebef1)
## Mixed Reality Toolkit Release Version
2017.2.1.1

**Comment by keveleigh** [comment]
Did you also import the main package? The Examples package is typically an add-on package and doesn't contain the Toolkit itself.

What were the errors?

**Comment by StephenHodgson** [comment]
I totally read +9000

![image](https://user-images.githubusercontent.com/13334553/44057194-39bc2dd6-9eff-11e8-875c-fe94ec6ff727.png)

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
