### ISSUE TITLE
InputUp event is fired right after InputDown

### ISSUE THREAD

**Issue by lordlycastle** [Microsoft/MixedRealityToolkit-Unity#2588]
## Overview
I was writing a script that should run after a button is "held" ie AirTap half way for a few seconds. I tested it in Unity editor and it waits until I let go of the trigger but on Hololens it does not wait to fire the `InputUp` until the finger are back open.
## Expected Behavior
The InputUp event should be fired when fingers stop doing the tap.
## Actual Behavior
InputUp is fired after InputDown disregarding the hand position.

## Mixed Reality Toolkit Release Version
2017.4.0

And while somebody is fixing this can we get some documentation on various events? I couldn't find any info for all these even other than [this page](https://docs.microsoft.com/en-us/windows/mixed-reality/gestures). This is a good start but does not explain it properly such as when is `HoldCompleted` and `HoldCanceled` called? Who knows?

        #region Protected Virtual Callback Functions
        protected virtual void FocusEnter(GameObject obj, PointerSpecificEventData eventData) { }
        protected virtual void FocusExit(GameObject obj, PointerSpecificEventData eventData) { }

        protected virtual void InputDown(GameObject obj, InputEventData eventData) { }
        protected virtual void InputUp(GameObject obj, InputEventData eventData) { }
        protected virtual void InputClicked(GameObject obj, InputClickedEventData eventData) { }

        protected virtual void HoldStarted(GameObject obj, HoldEventData eventData) { }
        protected virtual void HoldCompleted(GameObject obj, HoldEventData eventData) { }
        protected virtual void HoldCanceled(GameObject obj, HoldEventData eventData) { }

        protected virtual void ManipulationStarted(GameObject obj, ManipulationEventData eventData) { }
        protected virtual void ManipulationUpdated(GameObject obj, ManipulationEventData eventData) { }
        protected virtual void ManipulationCompleted(GameObject obj, ManipulationEventData eventData) { }
        protected virtual void ManipulationCanceled(GameObject obj, ManipulationEventData eventData) { }

        protected virtual void NavigationStarted(GameObject obj, NavigationEventData eventData) { }
        protected virtual void NavigationUpdated(GameObject obj, NavigationEventData eventData) { }
        protected virtual void NavigationCompleted(GameObject obj, NavigationEventData eventData) { }
        protected virtual void NavigationCanceled(GameObject obj, NavigationEventData eventData) { }
        #endregion

**Comment by StephenHodgson** [comment]
Repro steps?
