### ISSUE TITLE
bug: it is possible to teleport to "nowhere"

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2591]
## Overview
On vNext, teleportation does not appear to look for a valid position before moving the user. For example, I was able to go >1750m below the floor in the boundary visualization demo.

## Expected Behavior
By default, to block the user from teleporting outside of the experience's world.

## Actual Behavior
Was able to teleport so far away, I could not see the floor object.

## Steps to reproduce
Load the Boundary Visualization Demo scene, teleport off of the side of the floor platform.

## Unity Editor Version
2018.1.9

## Mixed Reality Toolkit Release Version
mrtk_development branch as of 8/14/2018

**Comment by StephenHodgson** [comment]
Interesting that we're getting a raycast "hit" so far away. The teleport position shouldn't be valid unless we focus a GameObject with a collider and the normal of that raycast is not too steep.
