### ISSUE TITLE
vNext Task: Spatial Audio System

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2592]
## Overview
Different platforms require different spatializers. Some platforms are supported by more than one spatializer. Some may need additional configuration beyond simply selecting a plugin.

Developers should be presented with an intelligent default and the option of selecting the spatializer of their choice.

## Requires
- Interface to define the Spatial Audio System
- Default manager implementation
- Mixed Reality Manager updates to enable/disable the system and select the appropriate profile

## Acceptance criteria
- [ ] User can select and configure their chosen spatializer via a profile
- [ ] Correct Spatializer is used for the appropriate platform.

**Comment by StephenHodgson** [comment]
Isn't there already a task for this?

**Comment by davidkline-ms** [comment]
> Isn't there already a task for this?

Nope. The one you are thinking of is the replacement for UAudioManager.  This is to implement a system that choses intelligent defaults for the spatializer plugin (ex: you cannot use MS HRTF on non-Windows 10 platforms).

**Comment by davidkline-ms** [comment]
moving to 2019 as it is a simple process to select the spatializer before buiding. and also hoping that Unity implements a build type configurable spatializer setting

**Comment by davidkline-ms** [comment]
this link should be helpful when implementing this task

https://docs.unity3d.com/ScriptReference/AudioSettings.html

**Comment by Yoyozilla** [comment]
This will be cover by future audio extension
