### ISSUE TITLE
sharing services of Holotoolkit is not working between wmr device and Hololens

### ISSUE THREAD

**Issue by absu** [Microsoft/MixedRealityToolkit-Unity#2613]
## Overview
By using holotoolkit sharing we build an application which is working in the hololens and not in the wmr device.But when we open the application using unity editor it is getting worked.But on building it and while opening it as an application in Wmr device It is not working.
## Expected Behavior
server should get connected when we  open UWP app in device directly.
## Actual Behavior
server is not getting connected to wmr device  when we open in device but it is working in hololens
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2017.2.1f1
## Mixed Reality Toolkit Release Version
2017.4.1.0

**Comment by easypeet** [comment]
I have the same issue and I am using the same Unity Editor and MRT versions as you. I have been able to connect to the sharing service from the hololenses the past 1 month but 2 days ago it stopped working. I suspect visual studio had an update. Do you have any workaround or fix for this?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
