### ISSUE TITLE
API for Windows Mixed Reality pass-through camera feed on VR headsets?

### ISSUE THREAD

**Issue by aidinabedi** [Microsoft/MixedRealityToolkit-Unity#2615]
A month ago, Microsoft showcased the new ["Flashlight" feature][1] for existing WMR immersive/VR headsets.

[![enter image description here][2]][2]

Since then, I've been trying to find a way to programmatically access the pass-through camera feed. Is there any API to retrieve the stream? Or plans on exposing such an API?

  [1]: https://blogs.windows.com/windowsexperience/2018/07/25/announcing-windows-10-insider-preview-build-17723-and-build-18204/
  [2]: https://i.stack.imgur.com/riVaZ.png

**Comment by StephenHodgson** [comment]
I haven't seen any new APIs in the windows namespaces. So it may be an internal thing for now. Hopefully a MS employee might chime in and enlighten us.

**Comment by ivan2007** [comment]
Here are the release notes for October update https://docs.microsoft.com/en-us/windows/mixed-reality/release-notes-october-2018

**Comment by MohsenneChaverdie** [comment]
Any update on that?

**Comment by Yoyozilla** [comment]
Not MRTK specific question. 
You will likely get better response here:
https://forums.hololens.com/
