### ISSUE TITLE
vNext Boundray Visualization Profile should not hide materials if a setting is disabled

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2616]
## Overview
Boundary visualization components can be shown or hidden at any time during the lifespan of an application. Currently, the boundary visualization profile hides settings from the developer when a component is not configured to be shown, though the data is persisted regardless of the setting for "Show".

This results in the user having to check, configure and uncheck any visualization that MAY be desired by the application.... a tedious at best process.

The fix is to ignore the state of "Show" and always display visualization settings.

**Comment by StephenHodgson** [comment]
Agreed, we shouldn't be hiding the materials in the boudnary viz profile.

**Comment by davidkline-ms** [comment]
As part of this change, I will be adding tooltips to the profile as well.
