### ISSUE TITLE
Exception when run Spatial Understanding query

### ISSUE THREAD

**Issue by sylnaw** [Microsoft/MixedRealityToolkit-Unity#2621]
## Overview
I have a bug when I run a Spatial Understanding query on HoloLens. I use object placement solver code from this site: https://docs.microsoft.com/en-us/windows/mixed-reality/case-study-expanding-the-spatial-mapping-capabilities-of-hololens and example code from HoloLens toolkit.

## Actual Behavior
I get the message: Exception thrown at 0x52D58C2E (SpatialUnderstanding.dll) in Spatial Understanding.exe: 0xC0000005: Access violation reading location 0x00000000. 

I use Unity 2018.2.0b8 and previous HoloLens Toolkit version.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
