### ISSUE TITLE
MRTK_Development does not build for the UWP  .NET scripting backend

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#2628]
## Overview
![image](https://user-images.githubusercontent.com/3580640/44436772-e06b1d00-a56b-11e8-8282-fc2ad0b510f6.png)

## Expected Behavior
vNext does build for the UWP .NET scripting backend

## Actual Behavior
vNext does not build for the UWP .NET scripting backend

## Steps to reproduce
1. Switch the target platform to UWP and the scripting backend to .NET.
2. Try to build.

## Unity Editor Version
2018.1.9f1 (but probably all).

## Mixed Reality Toolkit Release Version
MRTK_Development branch

**Comment by wassx** [comment]
I made a PR for this https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2629

**Comment by SimonDarksideJ** [comment]
Can we retest and close this issue now @keveleigh ?
