### ISSUE TITLE
Motion controllers Grab Mechanics scene not working

### ISSUE THREAD

**Issue by Kagigz** [Microsoft/MixedRealityToolkit-Unity#2635]
## Overview

In the Grab Mechanics example scene, it is possible to move and teleport but not to grab objects.

## Expected Behavior

The blocks should change color when pointed at and it should be possible to grab the blocks.

## Actual Behavior

When pointed at, the blocks don't change and nothing happens (even though the cursor points right into the block), and it's not possible to grab any of the blocks with the grab button.

## Steps to reproduce

* Prepare a project for Mixed Reality with the MRTK for Unity as described in the doc
* Go to HoloToolkit-Examples>MotionControllers-GrabMechanics>Scenes>GrabMechanics.Unity
* Open the scene and run
* Try to grab the blocks

## Unity Editor Version

Unity 2018.1.5f1 Personal

## Mixed Reality Toolkit Release Version

2017.4.1.0

**Comment by keveleigh** [comment]
For this scene, you need to actually reach out with the controllers, intersect the block with the controller representation, and press the grab button. From your write-up, it sounds like you're pointing at them instead of reaching for them.

**Comment by XPav** [comment]
Is it this problem?

https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1924

**Comment by cellerby** [comment]
I was having the same issue. I was making this mistake for a few days. Are using hitting the correct button. I thought the trigger was used to grab. However, This is a smaller button on the handle of the controller that is the button grab is mapped to. When my index finger is on the trigger, my middle is on the grab button.

**Comment by Kagigz** [comment]
Indeed I was pointing the blocks instead of intersecting my controllers with them (@cellerby I was using the right buttons though not the triggers).
It's clearer with the word "intersecting", thanks!
