### ISSUE TITLE
vNext Task: Lumin Platform Support

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2641]
## Overview
Add Lumin platform support for devices like the Magic Leap One

## Requires
- [x] Adding the ability to support platforms using Lumin
- [x] Supporting the magic leap one

## Acceptance criteria
- [x] User should be able to configure and setup the Lumin platform.
- [x] User should be able to configure Totem Controller using the controller profile.
- [x] User should be able to build and run any AR Demo scene on the device.
- [ ] User should be able to configure all recognizable gestures to Input Actions.

**Comment by isurfraz** [comment]
So is this or isnt this going into MRTK 2019? Hard to work out where this will land currently from the activity log

**Comment by SimonDarksideJ** [comment]
Initially, this will be shipped as an experimental package that you can install alongside the MRTK @isurfraz , depending on how that goes, it may be introduced in to the core or kept as an addon.

**Comment by Yoyozilla** [comment]
This would be great for someone in the community to add as extension.
