### ISSUE TITLE
WorldAnchorManager RemoveAnchor, translate object, AttachAnchor sequence doesn't work

### ISSUE THREAD

**Issue by sergedesmedt** [Microsoft/MixedRealityToolkit-Unity#2644]
## Overview

This is about a Hololens application.

I have an eventhandler for the tap event of a GestureRecognizer.
In this eventhandler I perform the following sequence:

        private void _gestureRecognizer_Tapped(TappedEventArgs obj)
        {
            Debug.Log("_gesureRecognizer_Tapped");

            WorldAnchorManager.Instance.RemoveAnchor(this.PanelObject);
            PanelObject.transform.Translate(1, 0, 0);

            WorldAnchorManager.Instance.AttachAnchor(this.PanelObject, AnchorName);
         }

However, nothing happens.

However, when I change my code and do the above in the GameObject Update method and perform the three steps with some pause between them it does work.

I've been looking into the sourcecode of the MRTK and it appears like the commands for removing and attaching are not executed immediately but are pushed on some stack and performed in the Update of the WorldAnchorManager.

So, the root cause is probably that the RemoveAnchor in my click event is not yet executed when I Translate, which makes the translate fail because the WorldAnchor is still attached.

So, I was wondering what is the correct way to handle this?
Is there some way for me to know when the RemoveAnchor is effectively executed?

## Expected Behavior

I would expect the object to translate and then it's new position to be saved

## Actual Behavior

The object doesn't move

## Steps to reproduce
see above code

## Unity Editor Version
Unity 2017.4.8f1 

## Mixed Reality Toolkit Release Version
2017.4.1.0

**Comment by Shubham7694** [comment]
I have faced similar issues and had to add artificial delay. In my opinion it should be designed in a way that we can inherit and overwrite functions as per our need. Right now few critical functions are private i think.

**Comment by Yoyozilla** [comment]
Sharing platform getting updated in v2.  

Bulk closing older HTK bug. Please reopen if you can repro this issue in MRTK v2. 
Thanks!
Yoyo
