### ISSUE TITLE
vNext Task: Package Management

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2649]
## Overview
MRTK 2018 will come in both required and optional asset packages. There needs to be a handy system for developers to discover and install the optional features, as well as future partner packages.

The goal is to directly interface with the Unity package manager store and present a curated set of package that are known to work well with the MRTK.

## Requires
- Data format for curated package list
- UI for selecting / filtering / installing packages
- Library that can / will be shared between partner toolkits

## Acceptance criteria
- [ ] Data format can represent package name, company, version, dependencies, download location
- [ ] UI allows
    - [ ] Viewing available packages
    - [ ] Filtering packages by name, type, etc
    - [ ] Selecting packages for install
    - [ ] Downloading / Caching packages
    - [ ] Installing package (may be done by Unity Package Manager UI)
- [ ] Package Management UI / Library can be distributed with partner toolkits

**Comment by Yoyozilla** [comment]
we are doing nuget instead.
