### ISSUE TITLE
Throw up a warning whenever a project that contains MRTK is built without being properly configured

### ISSUE THREAD

**Issue by Ecnassianer** [Microsoft/MixedRealityToolkit-Unity#2668]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
I experience the problem in HoloToolkit, but I would be fine if the feature request just landed in Mixed Reality Toolkit

**Is your feature request related to a problem? Please describe.**
I regularly help people debug the most obscure MRTK problems, missing using directives, bad cameras, failed DLLs. It's a pain in the ass and then I suddenly realize they never ran the Mixed Reality Toolkit Configure operations. These problems are really obscure and hard to track down on their own (and invariably it seems like they fixed one or two of the perquisites by hand in order to get themselves into an all new and unique brokeness state.)

**Describe the solution you'd like**

I'd really like it if MRTK popped a warning message any time it built/ran without having first been configured. And like... don't let them turn it off.

**Comment by JonathanPalmerGD** [comment]
I'll also add for reference that both the Oculus and SteamVR SDKs have either pop-up windows or force enable the options (while printing debug logs). 

They do not allow the user to forget those certain steps easily which likely removes large sections of odd bug cases that would occur otherwise.

**Comment by StephenHodgson** [comment]
In the new MRTK you won't have this issue, bc things are setup automatically on import.

**Comment by Ecnassianer** [comment]
What does the Configure option do?

**Comment by StephenHodgson** [comment]
It only creates the Mixed Reality Manager and puts it in your scene. From there everything is already setup from the initialization of the manager.

**Comment by Ecnassianer** [comment]
Rad!
