### ISSUE TITLE
parabolic laser pointer

### ISSUE THREAD

**Issue by Yoshihide-Nishimoto** [Microsoft/MixedRealityToolkit-Unity#2671]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit 

**Is your feature request related to a problem? Please describe.**
In the Home screen, when the joy sticked is tilted, the parabolic laser does appear.
I want to implement this.
It seems that there are no prefabs, components to achive this in the HoloToolKit and HoloToolKit-Example.
All of the example are using straight laser pointer.
If the laser pointer is straight, it's hard to point a heigher place.

**Describe the solution you'd like**
I want to know how to do this.
Offering the sample project is the best.

**Describe alternatives you've considered**
I'm considering creating original script...but it's little hard.

**Comment by StephenHodgson** [comment]
I'm confused about which version of the mrtk this issue is for.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
