### ISSUE TITLE
Text is changed when changing shape of a Button

### ISSUE THREAD

**Issue by twatzl** [Microsoft/MixedRealityToolkit-Unity#2672]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit 

**Describe the bug**
When changing the aspect ratio of a button, the aspect ratio and size of the text is changed as well.

**To Reproduce**
1. Create empty scene.
2. Create new button from prefab (Either RectangleButton or HolographicButton).
3. Put some text on it.
4. Change the aspect ratio of the button and see that the aspect ratio of the text changes.

**Expected behavior**
There should be a way to change the button shape without changing the text. Either by changing the button scale or by using some dedicated inputs for button size.
If the behavior is correct, then a tutorial on how to create UI with MRTK would be very helpful.

**Actual behavior**
The aspect ratio of the text (thus also the size of text) changes, when the button shape is changed.

**Screenshots**
![ui-button](https://user-images.githubusercontent.com/18753370/44839413-fdc07b00-ac3e-11e8-9c83-c68f9af65fed.PNG)

**Unity Editor Version**
2017.4.10f1

**Mixed Reality Toolkit Release Version**
2017.4.1.0

**Additional context**
none

**Comment by StephenHodgson** [comment]
I'm confused about which version of the toolkit this issue specified. At the top you said the Mixed Reality toolkit but it seems the issue talked about Holotoolkit components.

**Comment by twatzl** [comment]
Well the unitypackage I downloaded was under "Releases" the version 2017.4.1.0, which seems to be the newest version. I am not really aware that this would be a legacy version or that I have used legacy components. How can I know the difference between MRTK and HoloToolkit? Are there legacy components in the MRTK?

**Comment by StephenHodgson** [comment]
The namespace is either HoloToolkit or MixedRealityToolkit

**Comment by twatzl** [comment]
![image](https://user-images.githubusercontent.com/18753370/44969985-d96ee200-af4f-11e8-8920-50ae0b5b1fa2.png)

So from what I can see, it seems that I am using the HoloToolkit.

I think the way the releases are organized, it is not obvious that I am downloading something other than the MixedRealityToolkit. Because for the releases there is just a version number and since this is the MixedRealityToolkit-Unity repo I was just assuming that it is the MRTK I am downloading.

Where can I find information on
1. How to get the real MRTK?
2. What the differences are and what the future plans for MRTK and HoloToolkit are?

Thanks.

**Comment by StephenHodgson** [comment]
You're using the last official release from what I can tell. The MRTK is the next version of the toolkit.

**Comment by StephenHodgson** [comment]
Your initial issue comment said that the issue was for the MRTK not the HTK, hence the confusion. Sorry.

Thanks for reporting this.

**Comment by twatzl** [comment]
I am glad I could help. If you need further information, don't hesitate to ask.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
