### ISSUE TITLE
vNEXT Bug: HoloLens Hand Input incorrectly preregisters the gaze pointer on source lost

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2681]
**Overview**
When a user raises and lowers their hand, triggering a source found and lost event, when the hand input source is lost, it will also unregister the gaze pointer.

**Steps to reproduce the behavior:**
1. Build for HoloLens
2. Raise a hand
3. Lower the hand
4. See cursor stop moving, and error for internal gaze pointer not registered.

**Mixed Reality Toolkit Release Version**
mrtk_development

**Comment by StephenHodgson** [comment]
This may have been addressed already, but I want to confirm.

**Comment by StephenHodgson** [comment]
Couldn't reproduce in dev branch

**Comment by keveleigh** [comment]
Yep, I addressed this in https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2632
