### ISSUE TITLE
Where are April tags?

### ISSUE THREAD

**Issue by lordlycastle** [Microsoft/MixedRealityToolkit-Unity#2683]
In this discussion [here](https://forums.hololens.com/discussion/1482/barcode-qr-code-detection) @StephenHodgson mentions that "the HoloToolkit also has april tags (QR codes) built into it." Where are the respective scripts and documentation for this? I know this is used by spectator view for pairing so it must be somewhere.

**Mixed Reality Toolkit Release Version**
2017.4.1

**Comment by StephenHodgson** [comment]
That was part of the https://github.com/Microsoft/MixedRealityToolkit, but was removed

**Comment by lordlycastle** [comment]
@StephenHodgson how does the spectator view code scan on the phones now, or has that been removed?

**Comment by StephenHodgson** [comment]
Pretty sure it just uses the built in platform support for barcode reading

**Comment by lordlycastle** [comment]
Is there an API for that?

**Comment by StephenHodgson** [comment]
Yup! https://docs.microsoft.com/en-us/uwp/api/windows.devices.pointofservice.barcodescanner

**Comment by StephenHodgson** [comment]
Let me see what the HTK does to get this info.

**Comment by StephenHodgson** [comment]
Nope, they're using open CV. Check out the preview package with Spectator View.

[MarkerDetector](https://github.com/Microsoft/MixedRealityToolkit-
Unity/blob/master/Assets/HoloToolkit-Preview/SpectatorView/Scripts/SpatialSync/MarkerDetector.cs)
[MarkerDetectionHololens.cs](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Preview/SpectatorView/Scripts/SpatialSync/MarkerDetectionHololens.cs)

**Comment by lordlycastle** [comment]
Awesome. Will do! Danke.

**Comment by chrisfromwork** [comment]
@lordlycastle are you still blocked on this issue?
