### ISSUE TITLE
Sharing bug and correspondance between MRTK-Unity and MRTK  depots

### ISSUE THREAD

**Issue by raggnic** [Microsoft/MixedRealityToolkit-Unity#2684]
Hi guys

We've updated MRTK to  [2017.4.1.0](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/2017.4.1.0)

We have one nasty bug that crashes the unity editor (2017.4.10) with an access violation in SharingClient.dll (mainly when we go out of Play Mode). This was already present in our setup with 2017.1.2f1 and a MRTK from last year.

I'm trying to have a look on this, so I've built the MixedRealityToolkit (latest version) in debug, and I've replaced the SharingClient.dll with my one.
Alas, it looks like the one I've built is full of MixedRealityToolkit__ functions, instead of the HoloToolkit__ of the MRTK-unity 2017.4.10, so my guess is i've picked the wrong commit. 

So which commit should i get to be consistent with MRTK-unity 2017.4.10?
Thank you,

Nicolas

**Comment by keveleigh** [comment]
The pre-namespace change commit should be https://github.com/Microsoft/MixedRealityToolkit/tree/cb30bf2ca8a26372fae5ec173ef4e7f3afb6498a/Sharing. If you haven't already, please open an issue on that repo with your bug report as well. Thanks!

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
