### ISSUE TITLE
Question: Developing under different preprocessor directives

### ISSUE THREAD

**Issue by Jarodshow** [Microsoft/MixedRealityToolkit-Unity#2686]
## Overview
How could I develop in VS using a different preprocessor directive such as `WINDOWS_UWP`? In the past I used the built application and it included a solution that had the changes. Was this just a hack or is there a "supported" way to do this?

**Comment by StephenHodgson** [comment]
Make sure your project settings have the following conditions met:
- Build platform is UWP
- IL2CPP
- API compatibility is .Net 4.x

**Comment by Jarodshow** [comment]
Thank you!
