### ISSUE TITLE
vNEXT: DigitalHat Proposal

### ISSUE THREAD

**Issue by Jarodshow** [Microsoft/MixedRealityToolkit-Unity#2696]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Is your feature request related to a problem? Please describe.**
There are 2 instances of a "Hat" switch in the Windows Gaming devices. [FlightStick](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.flightstick#properties), [RacingWheel Gear](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.racingwheelreading#fields)

**Describe the solution you'd like**
A new `AxisType` called `DigitalHat` with a new property in `MixedRealityInteractionMapping` called `IntData` or `EnumData`

**Describe alternatives you've considered**
Using `FloatData` or `RawData` could be a workaround without implementing everything else.

**Comment by StephenHodgson** [comment]
Wouldn't these just be like `AxisType.Digital`? We've kept the axis types as generic as possible. Not sure what the benefit of this would be. Now we are going to introduce Input Action rules where you'll be able to transform the dual axis types into digital button presses (like the hats) but those are coming in through the hardware as Dual Axis input.

**Comment by heatherbarry** [comment]
Ok where do I begin ?

On Sep 3, 2018 7:56 PM, "Stephen Hodgson" <notifications@github.com> wrote:

Wouldn't these just be like AxisType.Digital? We've kept the axis types as
generic as possible. Not sure what the benefit of this would be. Now we are
going to introduce Input Action rules where you'll be able to transform the
dual axis types into digital button presses (like the hats) but those are
coming in through the hardware as Dual Axis input.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2696#issuecomment-418211806>,
or mute the thread

**Comment by Jarodshow** [comment]
I suppose it could stay in the realm of Digital, it's close enough. I can make a new DeviceInputType to go along with it. How would you feel about adding a new data section such as EnumData? Or should I just use RawData?

**Comment by StephenHodgson** [comment]
I'd suggest not mapping it, bc you can't change what you get from the hardware. It comes in as dual axis, can't change that.

**Comment by Jarodshow** [comment]
it comes in as an enum, but yeah I agree.

**Comment by StephenHodgson** [comment]
Well at least for the joysticks (gamepads).  Let's revisit this when we get a bit closer to implementing the racing wheel or a FlightStick.

**Comment by SimonDarksideJ** [comment]
Key thing with the abstraction we have brought with the MRTK, is that we have completely separated input data (and the control that sent it) from the internal use of that data in a project.

We have different "types" of input coming from a controller, be it a digital (bool/button), single axis (float), dual axis (vector2), 3Dof (vector3 position OR Quaternion rotation) and 6Dof (Vector 3 pos AND Quat rotation)
These are then mapped in the controller profiles to send the data to a specific Input Action (constrained by the axis type).

So your game will simply receive an action with data and you would then "do something" with that data.  You won't know what sent the data, except that you mapped the HAT to the HATMove action.

We are also working on an extension to enable one input action to spawn different actions based on the value in that data, e.g. HATUP when the HATMove is +1 and HATDOWN when the HATMove is -1.

Key thing is your project doesn't know what sent the data, as it could be mapped differently for all the different controllers we'll support.

**Comment by Jarodshow** [comment]
Yeah, I think a digital hat is just a bandaid for the underlying Input Action Rules, I'll wait to implement a hat until that's done.
