### ISSUE TITLE
Toggle cannot be to clicked by default cursor once this scene is loaded after a scene

### ISSUE THREAD

**Issue by wenxixi** [Microsoft/MixedRealityToolkit-Unity#2697]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit

**Describe the bug**
I have a toggle set up on a canvas in a scene (main scene), and they can be toggled by the default cursor when this scene is deployed individually to hololens. I also set up voice command to toggle them and it works well. 
Then I added an intro scene with a button to unload intro scene and load main scene. When it is clicked and main scene loads, the toggle can still be controlled by voice command but cannot be toggled with the cursor. 

**To Reproduce**
1. create an intro scene and main scene
2. intro scene contains a button to unload intro scene and load main scene
3. main scene has a toggle (https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX/Prefabs/Toggle.prefab) which can be controlled by both voice command and default cursor (https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Prefabs/Cursor/DefaultCursor.prefab)
4. Built both scenes to hololens

**Expected behavior**
After clicking the button in intro scene, the main scene loads and intro scene disappears, The toggle in main scene can be controlled by both voice command and default cursor.

**Actual behavior**
The toggle can be controlled by voice command but cannot be clicked by default cursor.
When I tried  building the main scene itself to hololens, everything works fine.

**Unity Editor Version**
latest
**Mixed Reality Toolkit Release Version**
latest

**Additional context**
I also have vuforia sdk used in the main scene.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
