### ISSUE TITLE
Dictation Input Manager breaks the app when Keyword Recognizer is used in a noise environment

### ISSUE THREAD

**Issue by baichuan55555** [Microsoft/MixedRealityToolkit-Unity#2699]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit

**Describe the bug**
While you are speaking, you called DictationInputManager.StopRecording(), the whole app stalls (crashes) until you stop speaking.

I checked, it stucks when PhraseRecognizerSystem.Restart() was called (if you also have a keyword recognizer).

**To Reproduce**
https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-212#chapter-3---understanding-and-the-dictation-recognizer
1. You can go the this tutorial
2. Open the scene from this tutorial
3. Open the communicator
4. keep making noise or voice
5. stop recording while you are talking
6. system stuck or crash

**Unity Editor Version**
Tested on 2017.4.3 and 2017.4.10

**Mixed Reality Toolkit Release Version**
2017.4.1.0

**Additional context**
It won't happen on the Hololens emulator SDK 14393. It did happen on emulator SDK 17134 and Hololens.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
