### ISSUE TITLE
Add a Proposal template to the New Issue button or update the documentation

### ISSUE THREAD

**Issue by Ecnassianer** [Microsoft/MixedRealityToolkit-Unity#2717]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Is your feature request related to a problem? Please describe.**
The Getting Started guide suggests that I make a proposal when I want to submit a change, but when I go to New Issue, I can choose from Bug Report, Feature Request, and Mixed Reality Toolkit Task. It's unclear to me which I should use. 

**Describe the solution you'd like**
If it's just a Mixed Reality Toolkit Task, we should clarify the docs (though it is a bit confusing, I'm not sure if tasks are for proposals that have already been approved, or if proposals are just tasks that haven't been commented on yet). If it's a separate kind of issue, we should add that to the New Issues button.

**Additional context**
![image](https://user-images.githubusercontent.com/231247/45189862-e01b8480-b1ef-11e8-9ffd-a63fc0aefcc0.png)

**Comment by keveleigh** [comment]
I can go through and update the docs, or we can update the terminology here. I'm good either way.

My intention was that Feature Requests would be for more general features or proposals without a set list of steps or requirements, while the MRTK Task template was for features that had been agreed upon or have been more fleshed out with specific requirements and scenarios they must account for.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
