### ISSUE TITLE
vNext Task: Core networking abstraction

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#2721]
# Overview
To enable sharing and other mutli-device features, we need a baseline networking system abstraction. This includes interface and type definitions to support the essential features of any networked experience.

# Requirements
* Architecture documentation

# Acceptance Criteria
- [ ] Architecture overview
- [ ] Base interface defining
    - [ ] Endpoint discovery (lobby, peer to peer, etc) interface(s)
    - [ ] Connection management
    - [ ] Data transfer (send, listen, receive handlers)
    - [ ] Reliability

**Comment by Yoyozilla** [comment]
Sharing will be a standalone component in a separate repo. Please join the public sharing weekly shiproom for details :)
