### ISSUE TITLE
Teleport cursor is visible, attached to the controller gizmo, on app launch

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#2749]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
On start, the teleport cursor appears attached to the controller gizmo. After teleporting for the first time, its visibility is correct.

**To Reproduce**
1. Load mrtk_development
2. Click play with a controller attached
3. Observe the teleport cursor

**Expected behavior**
No teleport cursor until I teleport

**Actual behavior**
On start, the teleport cursor appears attached to the controller gizmo.

**Screenshots**
![](https://i.imgur.com/HAUCFvx.png)

**Mixed Reality Toolkit Release Version**
mrtk_development

**Comment by StephenHodgson** [comment]
Fixed in https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2705

**Comment by keveleigh** [comment]
Why is a teleport cursor bug fixed in the gesture implementation PR?
