### ISSUE TITLE
ParabolicTeleportPointer doesn't always register itself correctly

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#2752]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
Sometimes, the pointers don't seem to register themselves correctly on app launch. I haven't been able to get a 100% repro, but I see this ~20% of the time.

The line pointer only extends out a short distance, and the teleport pointer stays visible.

**To Reproduce**
This happens on app launch with a controller attached. I'm not able to get a 100% repro.

**Expected behavior**
The pointers register and work.

**Actual behavior**
Sometimes, the pointers don't properly register themselves.

**Screenshots**
![image](https://user-images.githubusercontent.com/3580640/45378266-d314e180-b5b1-11e8-8633-3544f25b132f.png)

![image](https://user-images.githubusercontent.com/3580640/45378268-d3ad7800-b5b1-11e8-95dc-88fd5e290b87.png)

**Mixed Reality Toolkit Release Version**
mrtk_development

**Comment by keveleigh** [comment]
What change in #2750 fixes this?

**Comment by StephenHodgson** [comment]
It's part of the visibility on start changes.

**Comment by keveleigh** [comment]
This was not fixed in #2750.

![image](https://user-images.githubusercontent.com/3580640/45447017-3ae72d00-b683-11e8-91b3-125ba0c40cf9.png)

The cursor no longer appears (as expected), but registration still fails.

![image](https://user-images.githubusercontent.com/3580640/45447030-45a1c200-b683-11e8-8278-4a41216ae427.png)

**Comment by StephenHodgson** [comment]
Awe man, okay.  Did you have any idea about better repro steps?

**Comment by keveleigh** [comment]
Unfortunately, no. It seems to happen the first (or first few) times I run either on editor launch or after a while of not running.
After it resolves itself, subsequent runs do not repro the behavior.

**Comment by architekth** [comment]
I have the same issue with a class that inherit to LinePointer. This is a very basic class :

```
public class CustomLocomotion : LinePointer
{
    [Tooltip("Define the maximum value of the dead zone of the thumbstick")]
    public float DeadZoneValue = 0.2f;

    private Vector2 position = Vector2.zero;

    public override void OnPositionInputChanged(InputEventData<Vector2> eventData)
    {
        base.OnPositionInputChanged(eventData);

        // This makes sure that the input event we received is the input we want to listen to
        if(Controller.InputSource.SourceId == eventData.InputSource.SourceId)
        {
            // If eventdata description isn't from the thumbstick (action = Move). Exit this function
            if (eventData.MixedRealityInputAction.Description != "Move")
                return;

            position.x = eventData.InputData.x;
            position.y = eventData.InputData.y;

            // Define a dead zone
            if(Mathf.Abs(position.x) < DeadZoneValue)
            {
                position.x = 0f;
            }
            if(Mathf.Abs(position.y) < DeadZoneValue)
            {
                position.y = 0f;
            }
        }
    }

    /// <summary>
    /// Get the position of the thumbstick
    /// </summary>
    /// <returns></returns>
    public Vector2 GetPosition()
    {
        return position;
    }
}
```

**Comment by StephenHodgson** [comment]
I was able to get some solid repro steps for this. 

I can 100% get it if I turn off the Windows Mixed Reality Portal and turn it back on again, the press play.

There seems to be a long startup period after pressing play in the editor that only seems to happen the first time. I'm not entirely sure what's going on during this time, but it seems to be part of the issue. 

I'll update as I find more information.

**Comment by StephenHodgson** [comment]
I can also 100% repro if the headset goes to sleep and I press play from the editor to wake it up.
