### ISSUE TITLE
vNext : spatial mouse should not be added to the optional components profile by default

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2753]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
If an application is not intending to support spatial mouse functionality, they should not have to know to open the optional components profile and remove it.

This feels like an opt-in feature.

**Expected behavior**
No mouse pointer in the scene unless specifically requested

**Actual behavior**
Default optional components profile enables the mouse by default

**Comment by StephenHodgson** [comment]
I def think we should always have mouse input if it's availible, now handling the mouse input intelligently when there's motion controllers or other input types active should really be the goal here.

**Comment by davidkline-ms** [comment]
> I def think we should always have mouse input if it's available

Not sure I agree with that as the default behavior causes unity's editor to take control of the mouse and makes it challenging (yes, the user can press Esc to get it back. but that is not expected and it is confusing as to why)

**Comment by StephenHodgson** [comment]
That's always been the case when developing games with Unity. Seasoned developers know this.

**Comment by StephenHodgson** [comment]
I do agree tho, we should add a notification about pressing "Esc" to regain mouse control

**Comment by keveleigh** [comment]
>Seasoned developers know this.

Seasoned developers are not our only audience.

**Comment by StephenHodgson** [comment]
Yup, that's why I added #2756
