### ISSUE TITLE
vNext: four copies of the mouse pointer are visible in OpenVR if the mouse has not been moved

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2754]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
At app startup (with spatial mouse enabled) when running on OpenVR, there are four copies of the mouse pointer; one each at roughly the cardinal directions.

Once the mouse is moved, they consolidate into one.

**To Reproduce**
- Open create a scene
- Set build platform to Standalone and use the OpenVR SDK
- Launch the app in play mode
- Note the extra mouse pointers
- Move the mouse
- Pointers are consolidated

**Expected behavior**
There to be only one mouse pointer.

**Actual behavior**
There are four until physically moving the mouse

**Comment by StephenHodgson** [comment]
Pretty sure there only ever is one mouse pointer. Likely the position is moving very quickly between these four points. I'll look into this.

**Comment by StephenHodgson** [comment]
I can't seem to repro with your steps. Is there any additional info you can give me?

**Comment by davidkline-ms** [comment]
it is possible that it is related to the combination of this and #2750. let's revisit this once that PR is complete
