### ISSUE TITLE
Is there any guide/readme file to understand UNet Sharing example?

### ISSUE THREAD

**Issue by Shubham7694** [Microsoft/MixedRealityToolkit-Unity#2766]
## Overview
Currently i want to use UNet Sharing to share world anchor between hololens. But i can't what exactly understand if the example shares anchor automatically or any step is required. It would be great to have a read me file for each example. If already such a file exists, please guide me to right place.
## Steps to reproduce
_(Links to sample github project preferred)_

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
