### ISSUE TITLE
Sharing service on a private IP address and in-build problems 

### ISSUE THREAD

**Issue by tezelia** [microsoft/MixedRealityToolkit-Unity#2769]
Hey everyone,  

I have completed the shared holograms tutorial at https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-240 but have a few problems I need to resolve and would appreciate any help, advise or direction. 

I can build and run the hololens network sharing application on both hololens devices but only while the 'sharing service' in Unity is active or running in the background. The sharing service which can be found and accessed at the top of the Unity nav toolbar opens a console displaying details of active sessions and connecting devices. 

Firstly how can I set the application without the need of having Unity or 'sharing service' running in the background while connecting the two hololens devices? Alternatively is it possible to have the 'sharing service' run during a Visual Studio build so I can connect without Unity?

Secondly how do I create a private sharing service including a private IP and port number which can be accessed anywhere as long as I have an internet connection and run the app. The idea is to convert a raspberry pi b+ model into a host machine with a private ipv4 address where two hololens devices can connect too.

I read and researched something about Microsoft Azure, so I'm guessing that I need to host this private machine / address on Azure? If so how can I, what tutorials can I follow, what can I do? Can I convert the Unity build which works on local host machine to a private one? 

My plan was to simply change the parameters of the 'server address' and 'server port' within the Unity inspector of my project into the ipv4 and port number of the private host machine. But I'm guessing this is not possible? Maybe if I could run the application without having Unity open and then changing the parameters to the private ipv4, I thought it would've worked. 

I really want to get into this side of network knowledge/ programming and don't really know much about ip, hosting, etc 

Thank you,

**Comment by isurfraz** [comment]
You could use UNET but to be honest everyone who uses it has problems. 

We are using it and there are always big hologram accuracy issues, and noone here or on any forum seems to have actual answers to the problem, a lot of the problems just get ignored.

If you look up "UNET" or "sharing" on the issue search on this repository you will see what I mean, many have big issues with it that have never been fixed.

**Comment by Yoyozilla** [comment]
Closing older HTK issue as we are no longer actively working on HTK.

Please upgrade to MRTK V2 for the latest fixes.
