### ISSUE TITLE
Using a custom model controller

### ISSUE THREAD

**Issue by TheLLspectre** [microsoft/MixedRealityToolkit-Unity#2772]
Hi ! :)
I'm starting to use the mixed reality toolkit for Unity, I have a custom model for the controller and i see in the DefaultControllerPointer there is an empty Transform for the raycast origin. 
How i can affect it automatically when i launched the game. I try to create a prefab for the raycast and i try by a script, but i think i missed something ....
Do you have some advice ??

Thanks ;)

**Comment by StephenHodgson** [comment]
Are you using the legacy HoloToolkit or the Mixed Reality Toolkit vNEXT Alpha?

**Comment by TheLLspectre** [comment]
I'm using the mixed Reality Toolkit Alpha for Unity

**Comment by StephenHodgson** [comment]
On the Controller Mapping Profile you can assign a custom model at the top:

![image](https://user-images.githubusercontent.com/13334553/45452168-2199ad00-b692-11e8-852e-049ff5f95e74.png)

**Comment by TheLLspectre** [comment]
I already do that, sorry, i want to assign an empty gameObject for the orgin of the raycast, i saw there is an empty transform to assign it one, but i want to assign it before to launch the game, i only succed after launching it ...

**Comment by StephenHodgson** [comment]
Okay, so you're trying to change the raycast location based on your custom controller model?

I'd make an empty game object with the transform data you need, then assign that to your custom pointer prefab.

**Comment by TheLLspectre** [comment]
That's it ! 

It's what i tried, i make this empty object in the world on my custom model and then i make prefab of this. And i affect the empty gameObject from the prefab to the transform but when i launch, the raycast start from the position of the empty in the world where it was placed not on my controller ...  It's come from the creation of the differents parts of the mixed reality toolkit. You know when you start, it instiate some clones: left controller(clone), left defaultPointer(clone), left teleport(clone) and the same for the right. So it need to take data from the left controller(clone) for example to the raycast origin. I know the problem but i don't find how to fix it .. 

It the first issue, because i have two customs controllers one for the left and one for the right. So that's mean i need to assign two differents empty objects.

**Comment by TheLLspectre** [comment]
I make some screen ;)

My prefab with the empty object RayCastOrigin
![capture](https://user-images.githubusercontent.com/30622829/45479571-279d9580-b747-11e8-990a-ac86d7bb0386.PNG)

I affect the empty gameObject to the raycast origin parameter

![capture2](https://user-images.githubusercontent.com/30622829/45479573-279d9580-b747-11e8-9f5c-483d8daf21c1.PNG)

And i test, the right hand have the defaultControllerPointer(so no custom rayscast origin) and the left have the custom one and you see the raycast not start on the left hand and doesn't follow it ...

![sscreen](https://user-images.githubusercontent.com/30622829/45479574-279d9580-b747-11e8-9d17-07530b91f64f.png)

**Comment by StephenHodgson** [comment]
You'll need to update your pointer profile as well.

Create a new pointer profile and add the new pointer prefabs and assign the controller types you'd like to use.

**Comment by TheLLspectre** [comment]
![capture3](https://user-images.githubusercontent.com/30622829/45492055-9856a900-b76b-11e8-8557-6e2527c2d060.PNG)

Something like that ??
I try this too, and when i launch the raycast stay in the hand, there is just a point (the cursor) between two fingers i can't point nothing

**Comment by TheLLspectre** [comment]
Ok !

So i fix my problem, I just had a getter and setter in your BaseControllerPointer.cs file and in my initialized function i change it by the script ! and it's works !!!! ;)

**Comment by StephenHodgson** [comment]
Awesome! could you open a pull request with the changes you needed to make in `BaseControllerPointer`?

**Comment by TheLLspectre** [comment]
Yes i can if you want but may be you have to rewrite it correctly in C#, initially i'm a JAVA developper so i write it like I learned in JAVA

**Comment by StephenHodgson** [comment]
No worries, you could just give me a list of properties you needed to add setters to.

Next question, in your implementation, are you dynamically creating it, or did you set it up as a prefab?

**Comment by TheLLspectre** [comment]
I use the DefaultControllerPointer.prefab

![capture](https://user-images.githubusercontent.com/30622829/45600147-3199ef80-b9f8-11e8-9ad9-63035579c5cc.PNG)

and I had this to the `BaseControllerPointer.cs`

`//add-on methods LEROUGE Ludovic TheRed Games`

        public Transform getRaycastOrigin()
        {
            return raycastOrigin;
        }
        public void setRaycastOrigin(Transform rayCastOrigin)
        {
            this.raycastOrigin = rayCastOrigin;
        }
`

I initialize it like this in a script put on the player object

`

	void Start () {
		Invoke("Initialize", 2);
	}

	void Initialize()
	{
		rightHandPointer = GameObject.Find("Right_DefaultControllerPointer(Clone)");
		rightHandTeleport = GameObject.Find("Right_ParabolicPointer(Clone)");
		rightHand = GameObject.Find("Right_Right_rightHand(Clone)");
		lineRight = rightHandPointer.GetComponent<Microsoft.MixedReality.Toolkit.SDK.UX.Pointers.LinePointer>();
		lineTeleportRight = rightHandTeleport.GetComponent<Microsoft.MixedReality.Toolkit.SDK.UX.Pointers.ParabolicTeleportPointer>();
		lineRight.setRaycastOrigin(rightHand.transform.Find("RayCastOrigin").transform);
		lineTeleportRight.setRaycastOrigin(rightHand.transform.Find("RayCastOrigin").transform);
	}
}`

**Comment by StephenHodgson** [comment]
Why not just set those up with your prefabs? I'm not sure about what you're attempting to do in your `Initialize` method is the right way to go about doing what you're trying to do. 

Give me some time to try and figure out a good example of the proper way to do this (and I'll open a PR if it requires any changes to the base controller pointer).

**Comment by TheLLspectre** [comment]
i did this like this because like i said, when i use a prefab of a controllerPointer with my hand prefab the mixedRealityManager create a clone of the hand prefab and so it's why the controllerPointer doesn't take the rayCastOrigin (empty GameOjbect) from the clone handPrefab

**Comment by Yoyozilla** [comment]
Looks like the issue is solved. 
Please reopen if you think this is still an issue!
