### ISSUE TITLE
Use of Action instead of the MRTK standard of using the MixedRealityEventManager

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2780]
# Overview
The recent [Object Collection PR](https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2606)  was merged using events that did not use the Unity Event System or UnityEvents. Instead, it is using .NET Action's and delegates for raising and passing events.
Functionality should use the build in UnityEventManager for all event exchanging as it's highly performant and threaded in to the MRTK.

# To Reproduce
Open the Object Collection classes and see all the "Action" declarations and use throughout the scripts, as seen below:

```protected Action<BaseObjectCollection> onCollectionUpdated```

# Expected behavior
Events should use the built in "MixedRealityEventManager"

# Actual behavior
```protected Action<BaseObjectCollection> onCollectionUpdated```

# Mixed Reality Toolkit Release Version
MRTK_development

# Additional context
This highlights we still have more work to do in the coding guidelines to ensure core components are used for new MRTK development.

**Comment by StephenHodgson** [comment]
We should avoid using UnityEvents as much as possible. That's why we have our own event system.

**Comment by keveleigh** [comment]
I don't think this should be a guideline.

Sometimes, the entire world doesn't need to know about certain events. In the case of the object collection, when would the entire system need to know that a collection was updated? I think there's a time and place for both ways of doing things, and we should not require one over the other.

**Comment by keveleigh** [comment]
I'm mostly hoping this turns into a discussion instead of a declaration of a rule.

**Comment by StephenHodgson** [comment]
I think with cases like this it's okay to be a regular action. I suppose I'd have to see a performance comparison to make a judgement by objective results.

I think it's okay as is from a subjective point of view.

**Comment by StephenHodgson** [comment]
I'm not sure this is really a bug either, but a proposal we should either add to the coding style or a change to the current class.

**Comment by davidkline-ms** [comment]
approved in shiproom. we will consider the breaking change in 2019. Lars wants to tie this to refactor he is planning for 2019

**Comment by davidkline-ms** [comment]
will reactivate / revisit if/when @Railboy investigates his refactor
