### ISSUE TITLE
No standard script to absorb updates from HoloToolkit

### ISSUE THREAD

**Issue by jwittner** [Microsoft/MixedRealityToolkit-Unity#279]
It'd be nice to have a script that builds everything in a specified HoloToolkit directory and then copies all updated files to the repo. Currently seems like we're moving everything by hand and that's a bit of a recipe for disaster.

**Comment by NeerajW** [comment]
@jwittner could you please explain a little more on what the scenario is that you are trying to achieve? Thanks! It smells like a batch file but I want to make sure I understand better. But something that handles merge conflicts etc.? A file system manager? TortoiseGit?

**Comment by jwittner** [comment]
Could be a batch file. The crux of the problem is that there's no automated way to build the HoloToolkit and all of it's components and then update the HoloToolkit-Unity with the scripts/dlls/executables etc. that it relies on. Doesn't need to be anything fancy. =)

**Comment by HodgsonSDAS** [comment]
Could be a GIT sub-module, but I think that's prone to issues where people have to manually call update from GIT console or whatever GUI they're using.

**Comment by jwittner** [comment]
I think it'd be enough to have a batch file which I could point at any HoloToolkit folder to pull updated files from. Users could clone separately or add as submodule in their forks that way and still get the updates to work.

**Comment by CameronVetter** [comment]
Is there a reason that the HoloToolkit isn't published to the Unity 3d Asset store as a free asset?  This seems like the right way to deploy packages like this in the unity ecosystem...

**Comment by HodgsonSDAS** [comment]
@CameronVetter We're working on it. Right now the HoloToolkit is going though some major changes.

It's definitely on the todo list.

**Comment by NeerajW** [comment]
@CameronVetter the real reason is that we don't have an automated build system that can sign our code binaries. This is a ship requirement for us before shipping software. Hence the delay on making asset packages available on the asset store.

**Comment by jessemcculloch** [comment]
I know this is not a final solution to the problem, but @riverar has a HoloToolkit automated build page located at https://riverar.github.io/HoloToolkit-Unity-Builds/ where you can download already built unity packages that correspond to each pull request that is merged.  You can then import into your project as a custom asset.  This import function displays all the parts of the toolkit, and will show you what is new, what is changed (not code level, but asset level), etc.  This is my normal workflow for getting updates into my packages without worrying about accidentally overwriting something I might have edited and don't want to import.

**Comment by jessemcculloch** [comment]
With the new method of having releases, is this issue still a concern/something we should track?

**Comment by CameronVetter** [comment]
I think it still is an issue, until we have a path that gets the releases into the unity asset store we still aren't aligned with the Unity ecosystem.  This also makes it hard to publish other packages in the unity asset store that require the holotoolkit because you don't know where the developer will get the holotoolkit from, making it hard to know what version to target when you do have a dependency.

**Comment by jwittner** [comment]
My original intention for this issue was to get the native updates into the Unity version of the toolkit. This is supported with scripts now so I'm closing this.
