### ISSUE TITLE
There appears to be no easy way for a title to get the controller object from the manager

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2790]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
Based on the MixedRealityManager, I do not appear to be able to access the controller game object. My scenario needs to be able to perform situational tasks on the object (ex; highlight features, hide during portions where they would distract or no input is posssible).

**To Reproduce**
_(Links to sample GitHub project preferred)_
1. Create a scene with the MRManager
2. Try to find the controller object(s).

**Expected behavior**
A simple method / property to return me the collection of controller game objects

**Actual behavior**
Cant find one

**Comment by StephenHodgson** [comment]
`System.object`? `UnityEngine.Object`? `UnityEngine.GameObject`? I don't think I understand the use of terminology here, but I'll assume the latter `GameObject` as the object you're referring to here.

Shouldn't this have been a proposal or a task? 

Seems like kinda a stretch to call this a bug when there wasn't support for getting the controller `GameObject` references.

**Comment by StephenHodgson** [comment]
I'm going to close this in favor of #2799 as this isn't technically a bug and lists out all the requirements.

Please add any additional details or requirements you'd like to see added
