### ISSUE TITLE
HoloToolkit 2017.4.1.0 Speech Recognition not working

### ISSUE THREAD

**Issue by DineshPunni** [microsoft/MixedRealityToolkit-Unity#2793]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit 

**Describe the bug**
HoloLens doesn't invoke any events when trying to use speech commands. 

**To Reproduce**
1. Import HoloToolkit 2017.4.1.0 to Unity2018.1.9
2. Setup scene and project
3. Add 'SpeechInputHandler' and 'SpeechInputSource' to empty gameobject
4. Enable Microphone capabilities 
5. Deploy to HoloLens

**Expected behavior**
Spoken words get recognized and a sound is being played.

**Actual behavior**
nothing happens

**Screenshots**
![untitled](https://user-images.githubusercontent.com/16058396/45586575-c79b2080-b8f9-11e8-88c1-8d071b427823.png)

**Unity Editor Version**
Unity2018.1.9

**Mixed Reality Toolkit Release Version**
HoloToolkit 2017.4.1.0

**Additional context**

**Comment by Superdajk** [comment]
Happens for me too. Seems to work sometimes when I delete the entire build folder and rebuild that from scratch.

Built my project with 2018.2.4 and voice commands worked again

**Comment by lordlycastle** [comment]
Sidebar: Where did you get the build window in Unity?

**Comment by payyavula** [comment]
observed same issue. some times it works and but most of the times I get Unity exception "UnityException: Speech recognition is not supported on this machine"

**Comment by Yoyozilla** [comment]
HTK requires Unity 2017.4

Closing older HTK issue as we are no longer actively working on HTK.

Please upgrade to MRTK V2 for the latest fixes.
