### ISSUE TITLE
vNext Task: Improve and better implement Controller Model Visualization

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2799]
# Overview
In reviewing the migration of the Solver framework, it has highlighted that controller visualization needs to be better supported.

We also need a way to easily get the controller visualization's `GameObject` or `Transform` references for other components to use.

Currently the controller models are assigned in the Controller Mapping Profile, I'd like to propose that the model assignments should be their own profile, separate from input mapping.

# Requirements

* Controller visualization needs to have it's own profile in the Input System's configuration.
* Controller visualization needs to have it's own interface to define the requirements of a visualized controller. `IMixedRealityControllerVisualizer` ?
* Controller visualization profile needs to be able to assign a concrete implementation that is automatically added to the prefab at runtime, if it was not already added.
* Controller visualization profile needs to have a global prefab for left/right hands
* Controller visualization profile needs to have a prefab option for each supported platform's controller.
* Controller visualization's `GameObject` or `Transform` references need to be easily accessible.

# Acceptance Criteria

- [x] I can create and assign a Controller Visualization Profile to the Input System Configuration.
- [x] I can configure a profile to use a specific concrete implementation of a controller visualizer using the `IMixedRealityControllerVisualizer`.
- [x] I can configure a profile to use a prefab with no additional scripts (auto assigned from concrete implementation).
- [x] I can configure a profile to use a prefab with a previously attached script that implements `IMixedRealityControllerVisualizer`.
- [x] I can get the Controller `GameObject` reference from the `IMixedRealityControllerVisualizer`
- [x] I can get a list of currently detected controllers from the `IMixedRealityInputSystem`
- [ ] I can configure a profile to use the default controller model loaded form glTF or other sources to use the concrete implementation defined in the profile.

**Comment by SimonDarksideJ** [comment]
I would argue, that if we have a Visualization Manager, then it could manage the list of "connected" visualized objects / controllers. Negating the need for the SceneObjects registry.

If you can query the visualization config through the MR Manager, then it would server the same purpose.

**Comment by SimonDarksideJ** [comment]
Note, this requirement

> Controller visualization profile needs to have a global prefab for left/right hands

Is already provided by the Controller configuration, as both a global and a per controller model.

However, the new logic needs to extract the current model lookup currently sitting in the BaseController class.

**Comment by StephenHodgson** [comment]
glTF support to come later after 2807
