### ISSUE TITLE
Motion controller models not always loaded when playing in editor

### ISSUE THREAD

**Issue by ivan2007** [Microsoft/MixedRealityToolkit-Unity#2805]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit

**Describe the bug**
Sometimes, playing in editor, the motion controller models are not loaded.
This happens systematically after the debug with visual studio.

**To Reproduce**
1) Import MRTK and  InputManagerTestScene
2) Press Play in Unity (the motion controller models are loaded) 
3) Attach the VS debug
4) Detach debug
5) Stop the player
6) Press play in Unity (the motion controller models are not loaded) 

**Expected behavior**
Motion controller models always loaded

**Actual behavior**
I made some test and these are my notes:
1) The models are not loaded because there aren't detected spatial sources ( no sources from spatialInteractionManager->GetDetectedSourcesAtTimestamp(perceptionTimestamp) of EditorMotionController).
2) StartTrackingController is called from Awake (if InteractionManager retrives sources) and when an interaction source is detected
3) When the models are not loaded StartTrackingController is called from Awake. In this case if StartTrackingController is called when an interaction source is detected the models are loaded.
To test this I made a loop inside LoadSourceControllerModel to retry when the model is not loaded and this is the result:
![image](https://user-images.githubusercontent.com/17752475/45698637-c15eab80-bb68-11e8-9a43-6a997bd40449.png)

Only after the sources are detected the models are loaded.
It seems that, sometimes, also if InteractionManager retrives source states, these are not ready until the InteractionSourceDetected event is raised.

**Unity Editor Version**
2017.4.11f1

**Mixed Reality Toolkit Release Version**
2017.4.0.0

**Comment by StephenHodgson** [comment]
Thanks for the write up!

**Comment by ivan2007** [comment]
Many thanks for all your hard work on this project!

**Comment by StephenHodgson** [comment]
I wonder if we're forgetting to get a list of already active controllers, and only subscribing to the events

**Comment by stufflesimpsons** [comment]
Can someone please show me how to get all this stuff off my phone.😃

**Comment by keveleigh** [comment]
This should be fixed in the 2017.4.3 release. Please reopen if not.
