### ISSUE TITLE
IMixedRealityInputHandler.OnInputDown triggers twice on a single press

### ISSUE THREAD

**Issue by JonathanPalmerGD** [Microsoft/MixedRealityToolkit-Unity#2811]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit vNext

**Describe the bug**
Implemented OnInputDown from IMixedRealityInputHandler and using a MR headset + controllers using tooltips on vNext.
OnInputDown is being called multiple times for a single controller trigger press (first at 10% and then again at 100%)

**To Reproduce**
[Commit with incorrect behavior](https://github.com/JonathanPalmerGD/MixedRealityToolkit-Unity/tree/eb8bb1f00d8eb29569438a4f46f3f06ebe65dd64)
1. Open the scene TooltipExamples.unity (located in Assets/MRTk-Examples/Demos/UX/Tooltips/Scenes)
2. Ensure your platform setting is UWP.
3. Run the scene.
4. Target your controller at the emerald diamond to the right of the lunar module.
5. Pull the controller trigger slowly. You should see the tooltip appear below it after 10% of the button is depressed. The tooltip should vanish when you finish depressing the button.

**Expected behavior**
OnInputDown should only activate when passing a defined interval until it is unpressed.
Within the repro project, this means it should open the tooltip when you press, and close the tooltip when you press again.

**Actual behavior**
OnInputDown is being called multiple times for a single controller trigger press (first at 10% and then again at 100%)
This means behavior gated behind OnInputDown doesn't correctly trigger as expected.

Within the repro project, the tooltip will open and close within 1 fully completed press (maintaining pointing).

**Screenshots**

I placed several debug logs within a vNext version of ToolTipSpawner.
OnInputPressed gives the eventData.inputData value. When it exceeds .95f, it prints the HIT ===== message.
OnInputDown has a Debug.Log that prints a collection of the InputEventData values.

![mrtk - vnextinput 02](https://user-images.githubusercontent.com/2644214/45781794-ebba7280-bc15-11e8-8183-e5213eda9589.PNG)
![mrtk - vnextinput 01](https://user-images.githubusercontent.com/2644214/45781795-ebba7280-bc15-11e8-9c6c-bf5ce5430d37.PNG)

**Unity Editor Version**
Unity 2018.1.9f1

**Mixed Reality Toolkit Release Version**
Branched from mrtk_development (aka MRTK Alpha)

**Additional context**

**Comment by StephenHodgson** [comment]
Did you define an action to check against with the input event?

**Comment by StephenHodgson** [comment]
Also can you provide the full stack trace from each event?
(we should be able to trace them all the way back to the device layer)

**Comment by JonathanPalmerGD** [comment]
'Define an action to check against with the input event' - what do you mean by this?
I now notice that the MRInputAction.ID is a 0 on the start click and a 1 on the full click?
Is 0 a start press and 1 a full press?

Here's the full stack traces (note the red)

Start Click
![mrtk - vnextinput 04 startclick](https://user-images.githubusercontent.com/2644214/45787416-11517700-bc2a-11e8-8e6c-460b56efc8da.PNG)
Full Click
![mrtk - vnextinput 03 fullclick](https://user-images.githubusercontent.com/2644214/45787419-144c6780-bc2a-11e8-9b7f-4571c180e032.PNG)

[Currently looking into the MixedRealityInputAction and how to utilize it]

**Comment by JonathanPalmerGD** [comment]
By adding a variable MixedRealityInputAction and then checking to see if the eventData.MRIA.ID matched the variable's ID, I was able to get the desired input behavior.

The difference in IDs escaped my notice before you asked about it.

Thanks!
