### ISSUE TITLE
vNEXT Task: Lock Default Profile Inspectors.

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2825]
# Overview
The MRTK's default profile's shouldn't be configurable. We want developers to create their own to use so that when they take updates or changes to the MRTK their projects won't break. We should also be sure to give the ability to easily create a new on in the default configuration profiles as well.

# Requirements

* Consumers of the MRTK cannot change the default profiles
* Consumers of the MRTK can easily create a "Copy" of the default profile and start editing it immediately.
    * When copying a profile, it should also be set in the Mixed Reality Manager.
* Give maintainers easy access to modify or update the default profiles when needed.

# Acceptance Criteria

- [x] I can not edit any of the MRTK's default profiles located in the SDK.
- [x] As a MRTK Maintainer, I can easily edit and update the SDK's default profile.
- [ ] I can click a "Copy Profile" button and instantly start editing my own profile.

**Comment by davidkline-ms** [comment]
How do you propose to "lock" these files?

**Comment by StephenHodgson** [comment]
Still need to figure that out 😅 Got any ideas?

Best I could come up with was an editor pref where you can just toggle it on and off. 

`Editor/Preferences.../MRTK/Some toggle`

Once you toggle it off, then it stays that way unless you toggle it back on.

**Comment by Ecnassianer** [comment]
As long as creating these profiles doesn't require an additional setup step. So like, they're only really created when you go to edit a value.

As to the question of how, you probably want to create a separate data type that stores the defaults in a non-editable way. You could give that type it's own inspector that explains to create the editable type and edit those. That way you can keep the process fairly transparent and the default data only shows up if someone goes looking for it.

**Comment by StephenHodgson** [comment]
The point is to prevent people from editing something that could potentially be overwritten if they updated the asset package.

It's easy to create your own (and we want to encourage people to create their own) profiles.

**Comment by Ecnassianer** [comment]
Sorry, what I meant must not have been clear, I wasn't saying we should let them edit the defaults. If the defaults are actually stored in a separate type, they are essentially "claimed" by the kit, and users shouldn't/won't expect to have them preserved after an updated asset package. 

Just make sure the place where the user's edits of the settings live doesn't require any new setup steps to get MRTK working the first time. You could have the "Configure" option create them automatically or the profile inspector could lazy create them once someone has actually made a change away from the defaults.

**Comment by SimonDarksideJ** [comment]
TO clear things up a little @Ecnassianer , the MRTK "Defaults" are what we set in script, so when you "right-click -> new" a profile, it's defaults are already applied.
The MRTK default profiles in the SDK, are really only there for testing / examples and demos.

The correct workflow when a user starts a new project should be:

1: New Project / Scene
2: Create Main MR Profile and configure
3: Add any additional config profiles as required (so everything isn't ON by default)
4: Build and run

**Comment by Ecnassianer** [comment]
None of my other feedback matters compares to this one thing:

Don't add this step:
>2: Create Main MR Profile

Getting to a point where you can develop for HoloLens/VR is already a very hard task. Every step we can take out is a big win. Every step we add is a big loss. 

This is what I believe the correct workflow is:
0) Have WMR working outside Unity
1) New Project, New Scene
2) Import MRTK package
3) MRTK->Configure
4) Play in editor
5) Put on headset
6) Enjoy VR

I dream of a world where step 3 isn't necessary, most asset packages don't require a step like this and it would be great if we could do that too, but we're doing a lot behind the scenes, and we're doing it well, so I think it's an ok concession considering the lack of alternatives.

However, there are a lot of alternatives to forcing users to set up MRTK-specific profiles as their first interaction with MRTK. We don't need to add another setup step.

**Comment by StephenHodgson** [comment]
>A) Have WMR working outside Unity
>B) New Project, New Scene
>C) Import MRTK package
>D) MRTK->Configure
>E) Play in editor
>F) Put on headset
>G) Enjoy VR

That literally describes exactly what the current workflow is lol.

**Comment by StephenHodgson** [comment]
If we skip step D, then we run the risk of people getting frustrated bc the MRTK did something they didn't want.

**Comment by StephenHodgson** [comment]
>However, there are a lot of alternatives to forcing users to set up MRTK-specific profiles as their first interaction with MRTK

That's the thing. We don't force users to do anything more than press "Configure..."

The profile configuration is for people that want to do more in depth stuff, and I don't really think it's asking a lot of extra there.

**Comment by SimonDarksideJ** [comment]
I think your assumption that other VR / MR toolkits do not require "Configuration" a little off @Ecnassianer 
Even VRTK requires a certain level of setup before it is runnable on a single platform, let along all of its platforms.
MRTK is even going far beyond that supporting ALL AR / VR / XR patterns with additional features.

We are not saying you can't use the defaults, but we recommend you create your own profiles, which takes less than a minute.  The "Enforced" defaults are set, but changeable by you at any time and we've endeavoured to make the process as easy as possible.

EVERYONE's project is different and we've aimed for a common ground across multiple disciplines.

If however, you feel there should be a quick "create all my profiles" options would be useful. Please feel free to suggest and then implement it, we welcome PR's

**Comment by StephenHodgson** [comment]
@Ecnassianer We've pretty much setup the MRTK to be like a "Choose your own adventure" book.

The developer gets to choose how committed they are to customizing components

**Comment by SimonDarksideJ** [comment]
in any case, we'll have some quick (5 min) training videos for the project, to demonstrate just how easy the system is to setup in a new project.  If even then we feel improvements are needed, we'll add them.

Our focus is ensuring the "new user" experience is as painless as we can make it

**Comment by Ecnassianer** [comment]
>That literally describes exactly what the current workflow is lol.
Right, I want it to stay that way! :D

>If we skip step D
I didn't suggest skipping step D. 

>The profile configuration is for people that want to do more in depth stuff
I know, and I think it's fine that when a person is ready to "do more in depth stuff", they need to go setup some profiles. No objection there. It just shouldn't be a prerequisite for using the toolkit at all.

> The developer gets to choose how committed they are to customizing components
100%! I'm just defending the "Didn't have to understand any of it to get it working" level of commitment! :D

To reiterate:
I'm not objecting to having to create profiles in order to change away from the defaults. I'm objecting to having to create profiles to be able to use the toolkit with default settings. You should be able to continue to use the defaults just like you can today, with zero change to setup.
