### ISSUE TITLE
vNext task: add accessors to the boundary system created game objects

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2828]
# Overview
Nothing created and added to the application scene should be "hidden" from developers. Make it easy for them to access and be able to modify the gameobjects create by the boundary system.

# Requirements
User can request (and receive) the boundary game objects.

# Acceptance Criteria
- [ ] GameObjects that have been added to the scene get returned to application code
- [ ] Non-created objects return null until the application code explicitly enables their display the first time

**Comment by SimonDarksideJ** [comment]
Can you expand on that overview @davidkline-ms to out line the use case a little more.  Not getting what you mean from it currently.

**Comment by davidkline-ms** [comment]
actually, this is a noop... the boundary system already allows applications to request the gameobject for the visualizations :)
