### ISSUE TITLE
SerializationCompletionReason return UnknownError as status In ExportComplete()

### ISSUE THREAD

**Issue by CHIRAGPATEL5916** [Microsoft/MixedRealityToolkit-Unity#2842]
Help me out

**Comment by StephenHodgson** [comment]
Please fill out the issue templates so we can better help you out.

**Comment by GtYang2333** [comment]
i just met this problem using worldanchorTranferBatch to share worldanchor between 2 hololens2 device, and do not know why
    private void ExportGameRootAnchor()
    {
        WorldAnchorTransferBatch transferBatch = new WorldAnchorTransferBatch();
        WorldAnchor anchor = rootGameObject.GetComponent<WorldAnchor>();
        if (anchor == null)
        {
            anchor = rootGameObject.AddComponent<WorldAnchor>();
        }
        transferBatch.AddWorldAnchor(rootGameObject.name, anchor);
        DebugText.text = transferBatch.anchorCount.ToString();
        WorldAnchorTransferBatch.ExportAsync(transferBatch, OnExportDataAvailable, OnExportComplete);
    }
    private void OnExportDataAvailable(byte[] data)
    {

        //exportAnchorData.AddRange(data);
         DebugText.text = "sending ";
         List<byte> sf = new List<byte>();
         sf.Add(55);//表明发送的是anchor信息
         sf.Add(44);
         sf.Add((byte)data.Length);
         sf.AddRange(data);
         byte[] sendBuffer = sf.ToArray();
         clientSocket.Send(sendBuffer);
         //TransferDataToClient(data);
         
    }
    private void OnExportComplete(SerializationCompletionReason completionReason)
    {
        if (completionReason != SerializationCompletionReason.Succeeded)
        {
            //SendExportFailedToClient();

            DebugText.text = "send failed +  " +completionReason;
        }
        else
        {
            //SendExportSucceededToClient();
            DebugText.text = "send success" + completionReason;
        }
    }
