### ISSUE TITLE
New config profile created in the wrong folder.

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2856]
**Describe the bug**
When importing only the MRTK core folder and creating a new configuration profile, the profile creates a 
`MixedRealityToolkit-SDK` folder.

Instead this should create just a folder named profiles in the root assets folder.

**Steps to reproduce the behavior:**
1. Download and import just the core MRTK folder.
2. Click configure.
3. Accept the dialog option, asking to create a new configuration
4. See a new folder named `MixedRealityToolkit-SDK`

**Expected behavior**
Should create a new folder named `Profiles` at the root assets folder.

**Actual behavior**
Creates a new folder named `MixedRealityToolkit-SDK`

**Comment by davidkline-ms** [comment]
shouldn't profiles be created in the current folder? that's the behavior I have been seeing.

**Comment by StephenHodgson** [comment]
It is, except for the main configuration profile itself.

**Comment by StephenHodgson** [comment]
Best to repro this without the SDK installed in a new project.
