### ISSUE TITLE
vNext: enable "Virtual Reality Supported" automatically like htk did

### ISSUE THREAD

**Issue by Ecnassianer** [microsoft/MixedRealityToolkit-Unity#2860]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Is your feature request related to a problem? Please describe.**
I've gotten hamstrung by not having Virtual Reality Supported checked for me. I'm so used to htk project settings setup doing it for me, that I keep forgetting it in MRTK, and I send up spending 30+ minutes figuring out why my headset doesn't work.

**Describe the solution you'd like**
I'd like for this to be turned on for me, or at least to have a prompt asking if I want it turned on like the IL2CPP prompt.

**Comment by StephenHodgson** [comment]
This is a good point, and surprised we haven't addressed this sooner.

One of the ideas we had was to enable/disable VR support as hardware changed/plugged in/or was removed. I'm pretty certain you can do this at runtime, but harder still is the api support to intelligently choose which sdk to support based on that hardware.

**Comment by StephenHodgson** [comment]
@Ecnassianer can you please update this to reflect a task with a set of requirements and acceptance criteria?

**Comment by SimonDarksideJ** [comment]
A prompt would be best.  As I find it actually quite annoying (especially while in OpenVR) that Unity "autostarts" the VR client when you open the editor.

But this check needs to verify it for ALL platforms you have enable in the project, and validate it when you have a new one.

Personally, I'd also like a "Update VR Settings" bool, so if I have it OFF, it stays off until I'm ready to test :D  
But have it on by default so existing HTK users get what they expect.

**Comment by StephenHodgson** [comment]
A prompt might get annoying as not every project will be XR specific.

**Comment by StephenHodgson** [comment]
Simon, I thought we discussed active SDK features where things set up based on the hardware detected?

**Comment by SimonDarksideJ** [comment]
The prompt was more whether to turn on/off the VR switch easily.  To stop Unity being annoying. 
Based on the comment from the MRW team work work 90% in the editor, having SteamVR and / or MR Portal open EVERY time you open the editor would BE annoying :D 
Not saying the prompt should be ALL the time, just the first time you import the toolkit.

**Comment by StephenHodgson** [comment]
Generally I'll keep the portal open and running if I'm testing in VR anyway.

Seems like this should be something that's automagickally handled for you.

If we were to get into "simulation" of said devices, I could see that being a toggle it switch somewhere, to turn in/off said simulator feature.
