### ISSUE TITLE
Motion controller has a high chance of being not recognized in Unity 2018.2.10

### ISSUE THREAD

**Issue by marklinmao** [Microsoft/MixedRealityToolkit-Unity#2861]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit

**Describe the bug**
Motion controller not recognized in Unity **2018.2.10f0**. The model fails back to a white cube and no response to trigger events

**To Reproduce**
_(Links to sample GitHub project preferred)_
1. Create a new Unity project, import MRTK, Apply the project settings (for 'occluded headset') and scene settings.
2. Connect headset and 'play'.
3. Click the trigger on the controller
Please refer to the attached image for exception info.

**Expected behavior**
The 

**Actual behavior**
You will see the there is high change (80%) that the controller is not recognized(it falls back to be visualized as a white cube), while 20% chance it is. This problem was not existing in earlier version(e.g. **2018.1.1f1**) of Unity.

**Screenshots**
![lostcontorllerproblem](https://user-images.githubusercontent.com/4719869/46259324-4e462500-c4d8-11e8-95ea-743071f76e28.png)

**Unity Editor Version**
2018.2.10f0

**Mixed Reality Toolkit Release Version**
HoloToolkit-Unity-2017.4.1.0

**Comment by Cheesecakes** [comment]
I'm also seeing this issue in 2018.2.9f1.
Very annoying.

**Comment by marklinmao** [comment]
Any news about this issue, please?

**Comment by jerrygg** [comment]
@keveleigh Please fix it, it has blocked the normal development!

**Comment by keveleigh** [comment]
@jerrygg Please take a look at #3181. I believe this is fixed in that PR.

**Comment by marklinmao** [comment]
As I verified, it is fixed! Thank you @keveleigh !

**Comment by keveleigh** [comment]
This should be fixed in the 2017.4.3 release. Please reopen if not.

**Comment by marklinmao** [comment]
Nice to hear that, Thank!

Best Regards,
Mao LIN


Kurtis <notifications@github.com> 于 2018年11月26日周一 20:51写道：
