### ISSUE TITLE
Mouse and Keyboard input when "Simulate in Editor"

### ISSUE THREAD

**Issue by nosmirck** [Microsoft/MixedRealityToolkit-Unity#2862]
Hello, is there any way I can use mouse and keyboard input to move around when "Simulate in Editor" is on? not everyone has an XBox Controller.

I have a HoloLens, but it's very annoying to keep putting it on and off just to test a minor thing that is very easy to test in the Editor, I could use "none" in the Holographic Emulator mode settings, but that doesn't generate the room's mesh with spatial mapping which I need for my tests.

What would be a solution here? I don't have a controller.

**Comment by StephenHodgson** [comment]
Is this for MRTK or HTK?

**Comment by nosmirck** [comment]
MRTK using HoloLens.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
