### ISSUE TITLE
Default diagnostics profile needs to be locked

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2864]
Mixed Reality Toolkit

**Describe the bug**
The default diagnostics profile needs to be marked as a default (custom == 0)

**Expected behavior**
The default diagnostics profile is locked

**Actual behavior**
The default diagnostics profile is editable

**Comment by StephenHodgson** [comment]
We should probably update the interface to be system as well to be named similar to the other system interfaces

**Comment by davidkline-ms** [comment]
> We should probably update the interface to be system as well to be named similar to the other system interfaces

That should be it's own issue. Agree?

**Comment by StephenHodgson** [comment]
Sounds good, Just something I noticed but didn't have time to write up.

**Comment by davidkline-ms** [comment]
This profile is still unlocked... It probably needs the inspector to be updated to disable the UI

**Comment by keveleigh** [comment]
![image](https://user-images.githubusercontent.com/3580640/46381189-12d36400-c65a-11e8-9564-0e68a7200b8d.png)

It's locked for me. Your editor might be caching some state.

**Comment by StephenHodgson** [comment]
Be sure to check your preferences. Maybe you have it unlocked there.
