### ISSUE TITLE
Usage of UAudioManager's PlayEvent with a GameObject

### ISSUE THREAD

**Issue by PJBowron** [Microsoft/MixedRealityToolkit-Unity#2875]
## Overview
Using the UAudioManager's PlayEvent variant where a GameObject is passed as an 'emitter'. Is it assumed that the specified object be configured in advance for this purpose?

I think there may be a bug in the case where the object has no prior configuration...

## Expected Behavior
An AudioSource is added on the emitter GameObject (assuming no other sources are discovered as per current code flow) and the specified event is played.

## Actual Behavior
If no AudioSource **nor** AudioSourcesReference component is found (``GetUnusedAudioSource``), a new AudioSourcesReference is added to the GameObject, and an attempt is made to add an AudioSource to it. This leads to a null reference exception in ``AudioSourcesReference.AddNewAudioSource``: it's trying to add to a list that is not initialized until the ``OnEnable``.

## Mixed Reality Toolkit Release Version
HoloToolkit 2017.4.1.0

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
