### ISSUE TITLE
Connecting Hololens with another device via matchmaking Unity

### ISSUE THREAD

**Issue by TimReniers** [Microsoft/MixedRealityToolkit-Unity#2876]
Is it possible to connect the Hololens with another device (ios or android phone) through matchmaking in Unity (using uNet)?

Been trying this out for a while now but does not seem to work. I'm using the build-in networking system from Unity. Connecting two seperate desktops via matchmaking seems to work. But when i try to connect the Hololens with the editor on my desktop, Hololens does not seem to find any created rooms. Both devices are connected to the same wifi.

 I used Brackeys tutorials about creating a multiplayer game as the base for my project:
https://www.youtube.com/watch?v=H9GdXiF15r8&t=4s

**Comment by StephenHodgson** [comment]
Is the required capabilities enabled in the player settings for wsa?

- InternetClient
- InternetClientServer
- PrivateNetworkClientServer

**Comment by TimReniers** [comment]
That fixed it. Thanks!

**Comment by isurfraz** [comment]
@TimReniers @StephenHodgson from official capabilities docs:


**internetClientServer** | On Windows, this provides access to your Internet connection, including incoming unsolicited connections from the Internet – the app can send information to or from your computer through a firewall. **You do not need to declare internetClient if this capability is declared**. On Windows Phone, provides full local and internet access and can act as a server, but inbound access to critical ports is always blocked.
-- | --

No need for both InternetClient and InternetClientServer
