### ISSUE TITLE
vNext: NuGet Error NU1108 circular dependency detected when building c# projects debug projects

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2880]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
When using the .NET backend and enabling c# project generation, attempting to build in Visual Studio (15.8.6) generates a set of NuGet circular dependency errors:

- Microsoft.MixedReality.Toolkit.Examples -> Microsoft.MixedReality.Toolkit.SDK -> Microsoft.MixedReality.Toolkit.SDK
- Microsoft.MixedReality.Toolkit.SDK -> Microsoft.MixedReality.Toolkit.SDK
- Microsoft.MixedReality.Toolkit -> Microsoft.MixedReality.Toolkit.SDK -> Microsoft.MixedReality.Toolkit.SDK

**To Reproduce**
1. Specify the .NET backend in Player Settings
2. Set Platform to Universal Windows Platform in Build Settings
3. Check the Use C# Projects box in Build Settings
4. Build
5. Load .sln file in Visual Studio
6. Build

**Expected behavior**
For the project to be able to build using C# projects (for ease of debugging and modifications). The project will build if C# projects are not created.

**Actual behavior**
NuGet detects a cycle in each of the MRTK csproj files.

**Unity Editor Version**
2018.1.9f2

**Mixed Reality Toolkit Release Version**
Current mrtk_development branch (with use of System.Diagnostics.Process commented out of the diagnostics system) - to work around a limitation with UWP's .net implementation.

**Comment by StephenHodgson** [comment]
I think the real issue is that you copied over the c# projects. 

Unity doesn't properly reference the projects when doing this, can I've seen this issue in other projects outside of the MRTK.

I'm not sure about the circular dependency issue though, as I'm unfamiliar with nuget.

**Comment by StephenHodgson** [comment]
`Microsoft.MixedReality.Toolkit.SDK -> Microsoft.MixedReality.Toolkit.SDK`

How can it have a dependency to itself?

**Comment by StephenHodgson** [comment]
@jwittner any ideas here?

**Comment by davidkline-ms** [comment]
> How can it have a dependency to itself?

That has been my question too

**Comment by davidkline-ms** [comment]
> I think the real issue is that you copied over the c# projects.

I asked Unity to create them, I did not copy anything over...

**Comment by jwittner** [comment]
Hmmm, I can't make it that far against latest mrtk_release:

```
Assets\MixedRealityToolkit\_Core\Devices\BaseDeviceManager.cs(93,25): error CS0019: Operator '==' cannot be applied to operands of type 'SystemType' and 'Type'
Assets\MixedRealityToolkit\_Core\Definitions\Devices\ControllerMappingLibrary.cs(190,17): error CS0019: Operator '==' cannot be applied to operands of type 'SystemType' and 'Type'
```

=(

**Comment by keveleigh** [comment]
@jwittner sounds like another bug snuck in like the one fixed in https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2629

**Comment by jwittner** [comment]
Great lead @keveleigh!

@davidkline-ms I'm sure you're away, but I wonder about the policy on Closing as 'Won't-Fix' in situations like this:
![image](https://user-images.githubusercontent.com/12958442/46633285-18b9c100-cb02-11e8-9a04-1b0161b6c207.png)

**Comment by jwittner** [comment]
We should update the build to build all the test scenes so that the build will fail on this kind of thing.

**Comment by ryzngard** [comment]
> NuGet detects a cycle in each of the MRTK csproj files.

This seems odd in general. Why are we using NuGet to reference across csproj files we own? It should just be a package reference. 

I was able to repro this in VS, but I think it's a benign issue. Are there other compile issues? I was able to at least run nuget restore 

```
S:\tmp\Unity_Build>S:\tools\bin\nuget.exe restore MixedRealityToolkit.sln
MSBuild auto-detection: using msbuild version '15.8.169.51996' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'.
Committing restore...
Committing restore...
Committing restore...
Committing restore...
Committing restore...
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: S:\tmp\Unity_Build\GeneratedProjects\UWP\Microsoft.MixedReality.Toolkit.InputSystem\project.lock.json
Assets file has not changed. Skipping assets file writing. Path: S:\tmp\Unity_Build\MixedRealityToolkit\project.lock.json
Assets file has not changed. Skipping assets file writing. Path: S:\tmp\Unity_Build\GeneratedProjects\UWP\Unity.TextMeshPro\project.lock.json
Restore completed in 115.36 ms for S:\tmp\Unity_Build\MixedRealityToolkit\MixedRealityToolkit.csproj.
Assets file has not changed. Skipping assets file writing. Path: S:\tmp\Unity_Build\GeneratedProjects\UWP\Microsoft.MixedReality.Toolkit.Examples\project.lock.json
Assets file has not changed. Skipping assets file writing. Path: S:\tmp\Unity_Build\GeneratedProjects\UWP\Microsoft.MixedReality.Toolkit\project.lock.json
Assets file has not changed. Skipping assets file writing. Path: S:\tmp\Unity_Build\GeneratedProjects\UWP\Microsoft.MixedReality.Toolkit.SDK\project.lock.json
Restore completed in 114.96 ms for S:\tmp\Unity_Build\GeneratedProjects\UWP\Microsoft.MixedReality.Toolkit.InputSystem\Microsoft.MixedReality.Toolkit.InputSystem.csproj.
Restore completed in 114.93 ms for S:\tmp\Unity_Build\GeneratedProjects\UWP\Unity.TextMeshPro\Unity.TextMeshPro.csproj.
Restore completed in 114.96 ms for S:\tmp\Unity_Build\GeneratedProjects\UWP\Microsoft.MixedReality.Toolkit.Examples\Microsoft.MixedReality.Toolkit.Examples.csproj.
Restore completed in 114.95 ms for S:\tmp\Unity_Build\GeneratedProjects\UWP\Microsoft.MixedReality.Toolkit\Microsoft.MixedReality.Toolkit.csproj.
Restore completed in 115.33 ms for S:\tmp\Unity_Build\GeneratedProjects\UWP\Microsoft.MixedReality.Toolkit.SDK\Microsoft.MixedReality.Toolkit.SDK.csproj.

NuGet Config files used:
    C:\Users\andrha\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    https://api.nuget.org/v3/index.json
```

**Comment by StephenHodgson** [comment]
> I wonder about the policy on Closing as 'Won't-Fix' in situations like this

Agreed.

**Comment by Yoyozilla** [comment]
Closing older bug.
