### ISSUE TITLE
SpeechInputHandler doesn't respect IsFocusRequired

### ISSUE THREAD

**Issue by alcooper91** [Microsoft/MixedRealityToolkit-Unity#2883]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
I have a SpeechInputHandler that requires it, and it appears to be being invoked by MixedRealityInputManager's call to the base HandleEvent method with the comment of "Send the event to global listeners"

**To Reproduce**
1. Add a cube to a scene
2. Add Interactable to cube and a simple script to change color on Focus
3. Add a Speech Command and a SpeechInputHandler to the Cube which requires focus
4. Without focus on the cube, say the speech command

**Expected behavior**
Nothing happens

**Actual behavior**
Speech Command is executed.

**Screenshots**
N/a

**Unity Editor Version**
2018.1.9f2

**Mixed Reality Toolkit Release Version**
mrtk_development ~9/28 (Includes Kurtis's fix: https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2787)

**Additional context**

**Comment by keveleigh** [comment]
I believe this is a side effect of the version of Interactable used. It was recently updated to not register as a global listener unless told to, which should resolve this. I'll work with @alcooper91 to verify.

**Comment by krishnan-unni** [comment]
@keveleigh In my case #2911 I have not added an interactable though (I believe you are talking about Interactable Hightlighter). I only have Speech and BaseFocusHandler Derived by my CubeController script.

**Comment by StephenHodgson** [comment]
This bug doesn't involve an interactable, correct?

**Comment by krishnan-unni** [comment]
Yup Only a BaseFocusHandler inherited through my Cube controller and a SpeechHandler and PointerHandler.

**Comment by StephenHodgson** [comment]
The root cause is described in #2918
