### ISSUE TITLE
Controller Mapping profile for Hololens does not show the actions created in the Input action profile

### ISSUE THREAD

**Issue by krishnan-unni** [Microsoft/MixedRealityToolkit-Unity#2901]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit (dev branch)

**Describe the bug**
I tried creating a new Profile System and added new actions in the Input Action Profile. Then I created a Speech Profile and tried to assign actions against keywords and the new Actions were appearing properly. Then I created a Controller mapping profile and selected hololens as the device a window for Action assignment popped up but no actions were being shown there. The only Option was "None".

1) Simply create a new project. 
2) Add MixedRealityManager to a new GameObject.
3) Create a new Active Config profile
4) Add a new Input profile, within that and Input Action profile Spech Profile and Controller Profile
5)  add new actions in the Input Action Profile
6) selected hololens as the device in Controller Mapping profile. Once the action assignment popped up nno actions will be there

**Expected behavior**
Actions are supposed to show in the Assignment window.

**Actual behavior**
Actions are not being shown in the Assignment window.
![active profile](https://user-images.githubusercontent.com/14880339/46645197-c99b7c80-cb51-11e8-8c47-f21c75e98082.PNG)
![controllermapping profile](https://user-images.githubusercontent.com/14880339/46645198-c99b7c80-cb51-11e8-8223-eafa7df50ad6.PNG)
![inputprofile](https://user-images.githubusercontent.com/14880339/46645199-c99b7c80-cb51-11e8-94ca-29bf3795e5bc.PNG)
![inputsystem profile](https://user-images.githubusercontent.com/14880339/46645200-c99b7c80-cb51-11e8-9e33-e61fc5de0057.PNG)
![working speech profile](https://user-images.githubusercontent.com/14880339/46645201-c99b7c80-cb51-11e8-86d6-4df819c60703.PNG)

**Screenshots**

**Unity Editor Version**
2018.2.11f1

**Mixed Reality Toolkit Release Version**
mrtk_development

**Comment by StephenHodgson** [comment]
Try assigning digital to your tap action and six dof for your spatial pointer.

**Comment by krishnan-unni** [comment]
Yup got it. Thanks
