### ISSUE TITLE
Failed to world lock serialization failed

### ISSUE THREAD

**Issue by Shubham7694** [Microsoft/MixedRealityToolkit-Unity#2904]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit

**Describe the bug**
World anchor transfer batch api fails to serialize anchor. This happened mostly during second or third consecutive attempt.

**Unity Editor Version**
Unity 2017.4.6f1

**Mixed Reality Toolkit Release Version**
2017.4.0.0

**Additional context**
Deleting all the holograms and it starts successfuly serializing again.

**Comment by steviegiovanni** [comment]
Hey, I'm encountering the same thing. And deleting the holograms don't fix the issue. I'm using Unity 2017.4.11f1 and MRTK 2017.4.2.0.

**Comment by Shubham7694** [comment]
@isurfraz It's not the size of anchor is small. It's a memory issue i believe. Unity doesn;t clear memory for IL2CPP Platform for LargeHeap Objects and then worldanchor transfer batch fails due to lack of memory. This is what i have found so far and raised a ticket with Unity with a repo. They haven't responded. It happens in anchor sharing example scenes of MRTK . @steviegiovanni Sorry didn't reply earlier.
