### ISSUE TITLE
vNext task: separate registered components (ex: device managers) into assemblies

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2905]
# Overview
Today, the MRTK core assembly contains the code for all of the supported devices (windows mixed reality, open vr, etc). To improve modularization and to allow developers to only include the code that they intend to use (ex: HoloLens only app should not be required to ship OpenVR support code, and the other way around), we should take the Devices code out of the core dll and create individual assemblies.

This will enable faster expansion of device support as well as better customization for developers.

# Requirements
- Core MRTK assembly contains interface and type definitions
- Core MRTK assembly contains the Mixed Reality Manager code
- Core MRTK does NOT contain device implementation code
- Default registered components profile needs to be revisited to properly support the new division of binaries.

# Acceptance Criteria
- [ ] Installing MRTK Core package can configure the scene with the Mixed Reality Manager
- [ ] User is prompted (?) to add the appropriate device support to the Registered Components profile
- [ ] All devices are considered "extensions" to the MRTK

**Comment by ryzngard** [comment]
We need to make this available in NuGet.

**Comment by StephenHodgson** [comment]
This already happens?

I'm not sure the this makes much sense as a task, since Unity already splits these things apart into their own assemblies after each compile.

**Comment by StephenHodgson** [comment]
Should also be availible in Unity's package manager as well.

**Comment by davidkline-ms** [comment]
complete
