### ISSUE TITLE
Failed to Build

### ISSUE THREAD

**Issue by DineshPunni** [microsoft/MixedRealityToolkit-Unity#2909]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit

**Describe the bug**
Can't deploy to my HoloLens using the build window. It used to work fine
but all of a sudden it doesn't work anymore. 

Getting this error: 

```
Deployment Add operation with target volume C: on Package Template3D_1.0.1.0_x86__pzq3xp76mxafg from:  (HelloMRWorld_1.0.1.0_x86.appx)  failed with error 0x80004005. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.(Unspecified error
)
UnityEngine.Debug:LogError(Object)
HoloToolkit.Unity.BuildDeployPortal:GetInstallStatus(ConnectInfo) (at Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployPortal.cs:530)
HoloToolkit.Unity.BuildDeployPortal:InstallApp(String, ConnectInfo, Boolean) (at Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployPortal.cs:482)
HoloToolkit.Unity.BuildDeployWindow:InstallOnTargetDevice(String, ConnectInfo) (at Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs:1309)
HoloToolkit.Unity.<DeployGUI>c__AnonStorey6:<>m__0() (at Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs:928)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()
```

**To Reproduce**
Using Unity2018.1.19f1
HoloToolkit 2017.4.1.0
Configure project settings, build AppX (works)
Then try to Install it on HoloLense. Doesn't work

**Expected behavior**
Installed project on my Lense.

**Actual behavior**
See error above 

**Screenshots**
![2018-10-11_9-55-35](https://user-images.githubusercontent.com/16058396/46789033-daa7e180-cd3b-11e8-8b3f-7c7f4544ac29.png)

**Unity Editor Version**
2018.1.9f1

**Mixed Reality Toolkit Release Version**
HoloToolkit2017.4.1.0

**Comment by DineshPunni** [comment]
PS: Opening the project in VS2017 and trying to deploy it from there doesn't work eighter

**Comment by twatzl** [comment]
Is it possible, that you still have an older version of the app installed on the Hololens? Sometimes there is a problem with version numbering of the packages and Hololens won't allow to install an older version of an already installed app.

IMO there are two things you could try:
 - uninstall the app using device portal
 - increasing the version number of the package

**Comment by isurfraz** [comment]
We have found that using the build window will 100% of the time fail.

I recommend building using release, x86 and then building in VS and deploying via usb cable manually. see if this mitigates the issue as it did for us

**Comment by StephenHodgson** [comment]
> We have found that using the holotoolkit build window will 100% of the time fail.

Please open an issue describing the problems you're running into.

**Comment by DineshPunni** [comment]
It worked for me after I did a hard reset on the HoloLens.

However, a few things to consider when using the build window (In my case using Unity2018.1.9f1)

It only worked with .Net as scripting backend so far. Also building for IL2CPP took ages.
Make sure, that you remove the app manually from the HoloLens when deploying a new version, otherwise it won't override. 
Sometimes when the (successfully) built project can't get deployed it helps to delete the APPX package folder and then rebuild. 
And last, when you can't see your app versions in the Deploy Options it helps to close and reopen the build window. 

Just some things you may consider when using the build window. 

Cheers,
Dinesh

**Comment by twatzl** [comment]
@DineshPunni Have you tried if it works using the latest Unity 2014.4 (LTS) version? I am now building with Unity 2017.4.11f using IL2CPP and it works 100% reliable when I use the Build All button and deploy afterwards. It is also very important, that the version number of the new .appx is higher than the one installed.

AFAIK the HTK is also specifically aimed to work with Unity 2017.4, so the Unity version might cause trouble. In my experience so far it works best to use the matching/LTS Unity version. So if you do not absolutely need some of the newer features I would recommend upgrading Unity at a slower pace.

I think I remember we also had some build issue this year where we had to reset the Hololens, but since a colleague of me was doing that I unfortunately don't know any more details.

Hope I could help you.

**Comment by Yoyozilla** [comment]
HTK requires unity 2017.4 

Closing older HTK issue as we are no longer actively working on HTK.

Please upgrade to MRTK V2 for the latest fixes.
