### ISSUE TITLE
Gesture profile lets you assign previously assigned gestures

### ISSUE THREAD

**Issue by krishnan-unni** [Microsoft/MixedRealityToolkit-Unity#2912]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
In the Gesture profile even if we have more than one action which belongs to the same Gesture Type WMRDeviceManager picks only the last Action of a Gesture type.

**To Reproduce**
This is a code\design question so nothing to reproduce. 

In the Gesture profile add 5 (or more than 3) gestures and assign different actions to each of them
There will be more than 1 action of the same GestureType since there are only 3 GestureTypes defined in the enum currently.

In the Enable function for WMRDeviceManager it loops through the gestures in the profile and assign the action in the gesture to holdaction, Manuipulationaction and Navigationaction respectively. So if 5 gestures are there only the last action per GestureType will be considered. 
Is this how it is intended?

**Screenshots**

![gestureprofile](https://user-images.githubusercontent.com/14880339/46841614-10c67f00-cd97-11e8-8cb1-44e3072b6dff.PNG)
![wmr](https://user-images.githubusercontent.com/14880339/46841615-10c67f00-cd97-11e8-8d18-e33ba8726f19.PNG)

**Mixed Reality Toolkit Release Version**
mrtk_development

**Comment by StephenHodgson** [comment]
You probably shouldn't he iterating over the gesture types.

Instead you should he checking against the action type and then use the gesture type if it matches the action you setup.

**Comment by krishnan-unni** [comment]
:) Thats the code in the toolkit. Its not my code.

**Comment by StephenHodgson** [comment]
But the way the gestures are handled in the windows device, it's probably not a good idea to make more gestures than the device supports.

The idea of the gesture profile is to match the gesture with an action, then raise the action along with any generated data

**Comment by StephenHodgson** [comment]
Likely be need to limit the number of gestures that can be assigned if a gesture bis already created and matched to an action.

**Comment by krishnan-unni** [comment]
Agreed, that there need not be more Gestures. But I could have more than one action right? What if the user wants to execute two actions when a Gesture occurs. Its just a hypothesis. Otherwise we need to communicate to the user that 1 Action per gesture by restriction.

**Comment by StephenHodgson** [comment]
No, one gesture and one action. Unless you wanna swap out your gesture profile.

**Comment by krishnan-unni** [comment]
:) Makes sense. Then my proposal would be to limit the user that way - through code or documentation. It would prevent confusion or unexpected behavior (from their perspective).

**Comment by StephenHodgson** [comment]
@krishnan-unni are you on our slack channel?

**Comment by krishnan-unni** [comment]
nope :(

**Comment by StephenHodgson** [comment]
holodevelopers.slack.com

**Comment by krishnan-unni** [comment]
I tried, but not letting me in. Asking me to contact admin for an invite

**Comment by StephenHodgson** [comment]
@mr0ng can you help us out?

**Comment by Nakda** [comment]
@krishnan-unni there is an automatic invitation sender hosted here:
https://holodevelopersslack.azurewebsites.net/

**Comment by krishnan-unni** [comment]
Got it. Im in.
