### ISSUE TITLE
vNext: Add support for moving the origin of the spatial awareness observer

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#2916]
# Overview
The current implementation of spatial awareness (like Holograms 230) has the observer locked to the origin. In HTK, it is allowed to be moved by application code.

# Requirements

* Allow the app developer to modify the spatial awareness observer origin via the spatial awareness system interface.
* Update the origin as needed in the windows mixed reality observer 

# Acceptance Criteria

- [x] Expose and consume the observer origin
- [x] Add example scene supporting moving the observer

**Comment by StephenHodgson** [comment]
Is this task completed with 2917?

**Comment by davidkline-ms** [comment]
the portions related to chngeing the observer shape is not completed. I will remove those from the criteria
