### ISSUE TITLE
Project Settings recommend deprecated .NET backend

### ISSUE THREAD

**Issue by twatzl** [microsoft/MixedRealityToolkit-Unity#2925]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit 2017.4.2.0

**Describe the bug**
When selecting "Apply Mixed Reality Project Settings" the option "Enable .NET scripting backend" is selected by default, although the build window shows a warning message, that .NET backend will be deprecated

**Expected behavior**
Use IL2CPP per default or remove the warning about .NET being deprecated.

**Unity Editor Version**
2017.4.11f1

**Mixed Reality Toolkit Release Version**
HoloToolkit 2017.4.2.0

**Comment by Yoyozilla** [comment]
Closing older HTK issue as we are no longer actively working on HTK.

Please upgrade to MRTK V2 for the latest fixes.
