### ISSUE TITLE
Build is using outdated scene data

### ISSUE THREAD

**Issue by twatzl** [Microsoft/MixedRealityToolkit-Unity#2928]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit

**Describe the bug**
When using the HoloToolkit build window for building app packages, it seems that an old version of the app.

**To Reproduce**
Have no definitive steps for reproducing the issue in an arbitrary project, however it seems to be connected to some of the components we developed (unfortunately I cannot share them).

**Expected behavior**
The content of the latest version of the scene is included in the appx package.

**Actual behavior**
It seems that there is an older version of the scene included.
Building and deploying the .appx package works fine and without errors or warnings, just the contents of the package seem to be derived of old versions of the scene.

**Unity Editor Version**
2017.4.11f1

**Mixed Reality Toolkit Release Version**
Tested with 2017.4.0.0 and 2017.4.2.0

**Additional context**
It seems that some of our components or stuff is causing problems with the build, but I am not sure about that. I created a new empty project the build works as expected. However I could not find any log files. Where can they be found?

Also when deleting the contents from the UWP folder and rebuilding from the same scene, the missing contents are included in the new .appx package. However this process takes up to 5 minutes or even more.

Checking the 'Rebuild' checkbox in the build window also does not seem to solve the problem.

Configuration is IL2CPP (since .NET is deprecated), Release, x86.
When checking the app version in the device portal it can be verified, that indeed the latest build of my app gets installed.

EDIT: clarification that I am not sure if it is our stuff that causes the problems.

**Comment by StephenHodgson** [comment]
> However I could not find any log files.

You can click on the top right corner of editor console window to open the editor log.
![image](https://user-images.githubusercontent.com/13334553/47025362-28e02a80-d118-11e8-99e1-81a6cd98564e.png)

It's odd that you're seeing older scene content in your build. I've not used the HTK build window in a long time, but I did write a good portion of it. 

Be sure you're also building the Unity Player Project as well as the appx package (they're not the same steps but can be bundled together). Be sure to use "Build All" to bundle both of these build processes.

To build individually use the build window's tabs:
![image](https://user-images.githubusercontent.com/13334553/47025710-db17f200-d118-11e8-9609-a16b23602903.png)
This button _only_ builds the Unity Project. It is similar (but not the same as) the Unity Build window. Our build process does a few extra things to ensure the solution is ready for our appx generation.

![image](https://user-images.githubusercontent.com/13334553/47025837-14506200-d119-11e8-9ad0-98fd729b576c.png)
This button _only_ builds the appx package from the data in the Built Unity Project. If you don't rebuild your Unity Project, then you'll get the behavior you described.
- When the rebuild checkbox is unchecked a new folder and package is created out of the current Unity Project.
- When rebuild is checked, it deletes all data in the current package folder and regenerates everything.

**Comment by isurfraz** [comment]
We never use the build window, it always produces errors and broken builds for us. We manually build using VS which gives us back control over the process

**Comment by twatzl** [comment]
Thank you for your in depth answer Stephen and sorry for my response taking so long. I will check the problem again with your information in mind and will report back, although this might take some time.

As far as I remember it usually worked, when I only used "Build APPX" and only recently this odd behavior started showing up. If I recall correctly (sorry I did try so many different possibilities, that I am not 100% sure anymore), I also tried using the Rebuild checkbox, but the result was the same. I.e. the build took longer, but the scene still was not updated.

However as initially stated I will try out again your suggestions and report back. 

> We never use the build window, it always produces errors and broken builds for us. We manually build using VS which gives us back control over the process

Yeah. Some people on my team do/ recommend doing the same, especially since they did not know about HTK (build window) when they started the project.
However for me it always worked (more or less), besides a few times where I had checked or not checked the wrong checkbox and I refuse to manually build, since it takes so much longer and while the automatic build is running I can do other stuff, while if I would manually build, I would have to constantly watch my build.

**Comment by StephenHodgson** [comment]
@isurfraz did those errors get reported?

If you're having issues with anything I'd like to attempt to fix it if I can.

I haven't been updating the legacy holotoolkit build window and I know unity has been changing the build process somewhat so there's probably issues lurking in there someplace.

**Comment by StephenHodgson** [comment]
> Additionally the "Build Unity Project" && "Build APPX" was finishe far quicker, than using the rebuild checkbox. With the rebuild checkbox it took up to 5 minutes for building...

Up that sounds like the correct behavior. Because you're _forcing_ it to rebuild everything from scratch. With it turned off it incrementally builds.

> - then I went on and deleted the material from the sphere, effectively making it pink
> - I checked the 'Rebuild' checkbox and ran "Build APPX"

You should have ran _Build All_ at the very top, as you didn't rebuild the unity project. So it makes sense why you didn't see the change.

**Comment by twatzl** [comment]
As I said, building the unity project and then building the appx without rebuild works (and significantly faster than just running build appx with rebuild). As far as I have understood you this is essentially the same as build all? I do not want to use build all, because it would automatically deploy on the hololens as well and I don't want to do that at the moment.

Doesn't the rebuild checkbox also rebuild the Unity project?
If this is the behaviour by design, then I find it all very confusing.

**Comment by StephenHodgson** [comment]
> Doesn't the rebuild checkbox also rebuild the Unity project?

The rebuild checkbox in that tab has nothing to do with the unity build process only appx.

> If this is the behaviour by design, then I find it all very confusing.

🤔 Perhaps I can make this window a bit clearer. Maybe we can make the buttonsay _build appx only_?

**Comment by StephenHodgson** [comment]
>As I said, building the unity project and then building the appx without rebuild works (and significantly faster than just running build appx with rebuild).

Yup that makes sense as it's taking advantage of the incremental compiler. With rebuild checked on it completely rebuilds the binaries from scratch.

**Comment by StephenHodgson** [comment]
🤔 Or I could add an additional toggle that says _Rebuild Unity Player_ and update the existing one to say _Rebuild appx_.

**Comment by StephenHodgson** [comment]
Sure there is.

Switching the platform settings like x86 vs x64.
Or switching from debug to master or release.

**Comment by Yoyozilla** [comment]
Bulk closing older HTK bug. Please reopen if you can repro this issue in MRTK v2. 
Thanks!
Yoyo
