### ISSUE TITLE
NuGet packages do not contain default profiles

### ISSUE THREAD

**Issue by ryzngard** [Microsoft/MixedRealityToolkit-Unity#2930]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
In the feature/MRTK_packageManager branch the new NuGet packages do not contain default profiles. This means that new ones must be generated for everyone consuming from NuGet

**To Reproduce**
_(Links to sample GitHub project preferred)_
1. Checkout feature/MRTK_packageManager
2. `dotnet pack` in Build folder
3. Create new Unity project and install NuGetForUnity 
4. Add produced packages from dotnet pack above

**Expected behavior**
Default profiles exist

**Actual behavior**
Default profiles don't exist, and I must create new ones

**Additional context**
This feature is not yet in develop, so is only contained in this branch. This issue is to track before the feature merges.

**Comment by StephenHodgson** [comment]
I think this should be a task not a bug report

**Comment by ryzngard** [comment]
> I think this should be a task not a bug report 

Sure. I'm still adjusting to GitHub. Is there a better place to put this? I thought tasks and issues were basically the same?
