### ISSUE TITLE
Fature-Request: Display Browser Window in 3D space

### ISSUE THREAD

**Issue by Augmentaio** [microsoft/MixedRealityToolkit-Unity#2934]
Mixed Reality Toolkit

It would be fantastic to have an interactive browser window (2D canvas or 3D box) to open HTML pages from WWW. There is no satisfactory solution in asset store or forums on this.

**Comment by ForrestTrepte** [comment]
@Augmentaio, we now have an example of launching a browser window in the HandInteractionsExamples Unity scene as of #5047. I have attached a (compressed) GIF showing what this looks like. Does that solve your problem? Note that this runs the browser as a separate application so it isn't really like a web control that can be tightly integrated within your application.
![Launch](https://user-images.githubusercontent.com/17389739/60473013-18c59800-9c20-11e9-8522-3398af6eae62.gif)

**Comment by Yoyozilla** [comment]
closing as there's an example to show how to do this
