### ISSUE TITLE
Tooltip background doesn't scale with respect to text.

### ISSUE THREAD

**Issue by rohitdesaidev** [microsoft/MixedRealityToolkit-Unity#2949]
**Describe the bug**
If you attach the string dynamically to tooltip text. the background doesn't scale.
I tried even with static prefab, although the scripts for scaling is written but doesn't work as expected.

**To Reproduce**
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX/Readme/README_TooltipExample.md
1. Go to TooltipExample scene set any tooltip text dynamically or statically load the screen text goes out of the background.

**Expected behavior**
Text should fit in the background, as I observed in "ToolTip.cs" , "RefreshLocalContent()" 
resizes the background based on the content size but it doesn't work.

**Unity Editor Version**
Unity 2018.2.5

**Mixed Reality Toolkit Release Version**
 MRTK version(s) 2017.4.1.0

**Additional context**

**Comment by Cris21395** [comment]
Hi @rohitdesaidev,

Do you know if there is a quick solution for this problem until a new release solves it?

Regards,
Cristian.

**Comment by rohitdesaidev** [comment]
@Cris21395 
I Didn't find any solution yet as we have to modify MRTK scripts.
But rather than using dynamic sizing I prefer a static box size for every prefab.
Hope they solve this in coming release.
@StephenHodgson can please provide any solutions if you came across ?

Thanks,
Rohit Desai

**Comment by Yoyozilla** [comment]
HTK requires unity 2017.4 

Closing older HTK issue as we are no longer actively working on HTK.

Please upgrade to MRTK V2 for the latest fixes.
