### ISSUE TITLE
xml serialization broken : Unsupported internal call for IL2CPP:AssemblyBuilder::basic_init - System.Reflection.Emit is not supported.

### ISSUE THREAD

**Issue by rohitdesaidev** [microsoft/MixedRealityToolkit-Unity#2958]
**Describe the bug**
Not able to serialize XML file.  following is the log for a error.
```
 UWP\Il2CppOutputProject\IL2CPP\libil2cpp\icalls\mscorlib\System.Reflection.Emit\AssemblyBuilder.cpp(20) : Unsupported internal call for IL2CPP:AssemblyBuilder::basic_init - System.Reflection.Emit is not supported.
```

**To Reproduce**
read the xml file and serialize with XmlSerializer.

**Unity Editor Version**
2018.2.5f1 & 2018.3.0b6

**Mixed Reality Toolkit Release Version**
2017.4.1.0

**Additional context**
scripting runtime version : .Net 4.x equivalent
scripting backend : IL2CPP
API compatibility level .Net 4.x

**Comment by StephenHodgson** [comment]
Might be a duplicate?

**Comment by StephenHodgson** [comment]
Not sure.

**Comment by rohitdesaidev** [comment]
Got working in unity 2018.3 beta with API compatible level : .Net 2.0

**Comment by FreakTheMighty** [comment]
Does this mean that MRTK doesn't support the IL2CPP backend if you want to serialize objects?

I'm seeing this error trying to serialize an object to JSON. It seems that iOS has a similar issue and that a custom build of Json.NET has been created. https://stackoverflow.com/questions/16359628/json-net-under-unity3d-for-ios

**Comment by FreakTheMighty** [comment]
Also, why is this tagged with `Legacy (HoloToolkit)`?

**Comment by StephenHodgson** [comment]
Because this actually refers to the HoloToolkit release 2017.4.1.0, not the Mixed Reality Toolit

**Comment by FreakTheMighty** [comment]
Got it. Looks like this is [my issue](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2269).

**Comment by Yoyozilla** [comment]
Closing older HTK issue as we are no longer actively working on HTK.

Please upgrade to MRTK V2 for the latest fixes.
