### ISSUE TITLE
HandDraggable script and IManipulationHandler interface are not working with the clicker.

### ISSUE THREAD

**Issue by ivancamra** [microsoft/MixedRealityToolkit-Unity#2971]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit

**Describe the bug**
As the title says, HandDraggable script and IManipulationHandler interface are not working with the clicker.

**To Reproduce**
Clean project. Import MRTK assets. Import Examples. Apply Mixed Reality configurations.

Attach HandDraggable to a cube. 

Testing with the simulator, the translation occurs. 

When I build the project and I upload it to the Hololens, I can use gestures to move the cube.
If I then try to use the clicker to move it (as far as I know it should be compatible), the cube doesn't move.

The output console shows:

> Model stream is null; loading alternate.

As an alternative, I tried to used the IManipulationHandler interface.
If I understood correctly from the documentation (Windows Academy Gestures), I should be able to add to the position of the cube the  eventData.CumulativeDelta value, but this value is always 0.

**Expected behavior**
If I attach the HandDraggable script to an object I expect that I could move it using the clicker (in 2D) in the same way that using gestures. 

**Unity Editor Version**
2017.2.1p2, 2017.4.2f2 and 2017.4.5f1

**Mixed Reality Toolkit Release Version**
2017.4.2.0 and 2017.4.1.0

I am pretty desperate, I don't know what else to try.

Many thanks in advance

**Comment by Yoyozilla** [comment]
Closing older HTK issue as we are no longer actively working on HTK.

Please upgrade to MRTK V2 for the latest fixes.
