### ISSUE TITLE
vNEXT Task: Create Getting Started Guide.md

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2974]
# Overview
I thought we had a document like this already in the vNEXT branch, but it seems to have been misplaced. 

Let's discuss requirements and needs for the Getting Started Guide

# Requirements

* Guide a new developer though downloading, setting up, and running the MRTK
* Highlight any special requirements for the MRTK

# Acceptance Criteria

- [x] Create `GettingStartedGuide.md`
- [x] Add Requirements
    - [x] .Net 4.x equivalent run-time
- [x] Step by step walk though of setup
    - [x] Downloading
    - [x] Importing
    - [x] Setup
    - [x] Building
    - [x] Running

**Comment by SimonDarksideJ** [comment]
I'll pick this up as part of my DevPost series and publish content back to the repo as well.
