### ISSUE TITLE
Remove unused / unimplemented feature folders from the MRTK solution

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#2991]
# Overview
There are a number of empty folders still left over from the initial work to map out the folder structure for the MRTK.  As we reach beta, we should prune any empty folders / features which are not fully implemented.

This will avoid any confusion / queries as to why things are "not there" from general consumers

# Requirements
Remove any folders for "things" not implemented, for example:

* MixedRealityToolkit -> Sharing (just an empty folder with a readme)
* MixedRealityToolkit -> Spatial (just an empty folder with a readme)

# Acceptance Criteria
- [ ] A clean project with no empty folders
- [ ] No boiler plate readme's, each should fully describe the folders contents
- [ ] A small documented readme in each folder for browsing the project in Github / code.

Should be included in the Beta checklist #2973

**Comment by StephenHodgson** [comment]
Please add it to the checklist

**Comment by StephenHodgson** [comment]
@SimonDarksideJ can you update this ticket please?

**Comment by SimonDarksideJ** [comment]
Merged
