### ISSUE TITLE
Solver demo scene magenta materials might be confused for missing materials

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2998]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
 Mixed Reality Toolkit

**Describe the bug**
A few of the objects in the solver demo scene are missing materials

**To Reproduce**
_(Links to sample GitHub project preferred)_
1. Open solver demo scene
2. View Orbital, and Surface magnetism demo objects.

![image](https://user-images.githubusercontent.com/13334553/47609948-d3502b80-d9fd-11e8-938e-e44408e93579.png)

**Comment by keveleigh** [comment]
Those are using the MRTK magenta material.

**Comment by StephenHodgson** [comment]
Would we consider a different color so it doesn't look unprofessional? Most people seeing it would assume something is broken.
