### ISSUE TITLE
Open VR Boundary is misaligned

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#3004]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
When on the Standalone platform and using OpenVR the boundary is rotated 180 in the wrong direction

**To Reproduce**
1. Switch project to Standalone
2. Open any Scene
3. Look down and get close to boundary.
4. See that the OS boundary doesn't match the MRTK's drawn boundary on the floor.

**Additional Remarks**
Works as expected for WMR.

**Screenshots**

![image](https://user-images.githubusercontent.com/13334553/47621969-5df76000-dabc-11e8-8219-cbae2d73a792.png)

![image](https://user-images.githubusercontent.com/13334553/47621973-68b1f500-dabc-11e8-89ae-ace4cf7fc050.png)

**Comment by davidkline-ms** [comment]
There is a bug in Unity that has the OpenVR boundary flipped.

**Comment by StephenHodgson** [comment]
> There is a bug in Unity that has the OpenVR boundary flipped.

I wasn't able to find anything online about this. Is there a bug report or issue tracking number we can reference?

**Comment by keveleigh** [comment]
Not on the public tracker, but it's acknowledged and tracked internally.

**Comment by StephenHodgson** [comment]
Odd that something like this isn't being tracked publicly. 🤔

Isn't that a pretty serious safety thing?

**Comment by StephenHodgson** [comment]
Why are we just closing issues without verification that it's fixed?

This is an MRTK v2 RC1 bug

**Comment by davidkline-ms** [comment]
What version of Unity are you using? This was as @keveleigh mentions it was an acknowledge Unity bug.

pre-rc1 release, i verified that on 2018.3.11f1 that the boundary was properly aligned on both platforms.
