### ISSUE TITLE
Multiple Occlusion*.shaders and "Offset" causes incomplete occlusion.

### ISSUE THREAD

**Issue by larsonmattr** [microsoft/MixedRealityToolkit-Unity#3006]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit 2017.2.1.4

**Describe the bug**
The Mixed Reality Toolkit contains multiple copies of the "Occlusion.shader" or "WindowOcclusion.shader" which are all very similar, but only "WindowOcclusion.shader" is able to fully occlude objects correctly. The other two shaders include "Offset 50, 100" statements in the "Pass" section which causes their writes to the depth buffer to be slightly displaced. When using these occlusion shaders with a material for making a box that occludes an object within it, they will only partially and incorrectly occlude the object.

**To Reproduce**
1. Create 4 planes surrounding a GameObject A. 
2. Set material for GameObject A as the MRTK Standard Shader
3. Set shader for material for the planes to be "SpatialMapping/Shaders/Occlusion.shader", or "UX/Shaders/Occlusion.shader"
(Bug) -> The planes will only partially occlude the GameObject A, due to the "Offset" statement.
4. Set shader for material for the planes to be "Common/Shaders/WindowOcclusion.shader"
(Correct) -> The planes will completely occlude GameObject A.

**Expected behavior**
There should only need to be 1 working Occlusion.shader.
It should not use the depth offset that leads to partial occlusion.
If more than one Occlusion shader are needed in the toolkit, we should have better naming and documentation to indicate how these shaders are different. Shaders could include comments describing their use or linking to documentation.

**Actual behavior**
3 duplicate shaders but only 1 of them is fully functional for "Occlusion"

**Unity Editor Version**
2018.1 or 2018.2.*

**Mixed Reality Toolkit Release Version**
Which MRTK version(s) you've been able to reproduce the bug in.
2017.2.1.4

**Comment by Yoyozilla** [comment]
Closing older HTK issue as we are no longer actively working on HTK.

Please upgrade to MRTK V2 for the latest fixes.
