### ISSUE TITLE
Which branch to use for latest BoundingBox implementation

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#3009]
## Overview
I have not looked into the MRTK Git Repo for a while and am quite confused about all the Branches without any vNext available and such. I tested the BoundingBox from the Master branch but this can't be right as it's handling is wrong using the MR Motion Controller.

Which Branch is the latest with a working BoundingBox in it?

## Unity Editor Version
2018.2.6f1

**Comment by StephenHodgson** [comment]
Master is the way to go. We have not finished porting this feature to vNEXT yet.

**Comment by Alexees** [comment]
@StephenHodgson ok who is in charge of the bounding box then? It's still broken when used with MR Headset. Movement is slow and not always the same direction as the motion controller goes. Even holding the controller still and moving the head moves the object. Scaling is the worst as you never get what you want, scaling down when you effectively scale up and the other way around, having a hard time to scale big really.
The box is not good at all. Who can I talk to?

**Comment by Alexees** [comment]
Ok, I fixed it in my project, but the MRTK there is old and a mess. Nevertheless, the reason why the box is broken is that the code only works for the Hololens hand. The calculations only use the hand position, since there is no beam or cursor. The calculations need to done differently for the controller, as the relevant position is where the controller is aiming at, the offset from it's position in pointing direction.

**Comment by StephenHodgson** [comment]
I'm unsure as to who owns this feature. But we def want to port it as soon as possible. (There's been one or two attempts made already)

If you were able to fix some things, we'd appreciate any contributions back into the HTK dev branch.

If you were able to port to MRTK dev branch already, that'd be awesome to see as well.

**Comment by PJBowron** [comment]
BoundingBox and AppBar were originated by @cre8ivepark / @johnppella .
Those guys have begun porting already, see #3044 . I think it might be wise to hold off on attempting to contribute anything to vNext as their work seems to be ongoing and there's not much back and forth going on.

**Comment by chbecker-ms** [comment]
Bounding box is in mrtk_development. Closing out.
