### ISSUE TITLE
Windows Speech causing massive slowdown on startup/shutdown

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#3026]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
When playing in the editor the Windows Speech Recognizer causes massive slowdowns on both startup and shutdown.
![image](https://user-images.githubusercontent.com/13334553/47687302-ddf4f700-db9c-11e8-98d5-6e09434c53dd.png)

**To Reproduce**
1. Open any scene
2. Enter playmode
3. Lags for a few seconds up to 10+ seconds.
4. Same lag when exiting play mode as well.

Stabilization Branch

**Comment by ivan2007** [comment]
Maybe this issue is related to #2085

**Comment by StephenHodgson** [comment]
Yup. Sounds pretty much exactly the same.

Wondering if it's a regression? 🤔

**Comment by StephenHodgson** [comment]
I'm wondering if it's the app trying to obtain the permissions for usage? 🤔

**Comment by StephenHodgson** [comment]
Dictation is also affected.

**Comment by davidkline-ms** [comment]
> Enter playmode

Is there a noticeable slowdown when running a compiled version of the app? Could this be editor specific?

**Comment by StephenHodgson** [comment]
> Is there a noticeable slowdown when running a compiled version of the app?

None that I could find.  Likely editor specific.

**Comment by davidkline-ms** [comment]
> None that I could find. Likely editor specific.

Thanks for checking.

**Comment by ivan2007** [comment]
Hi,
regarding #2085 I was contacted by Microsoft (Eiden Kim).
After providing a complete report of the problem, the final answer was this:

Hi Ivan,
The problem had been well introduced to our dev team and we started working to fix the issue. Thanks for your detail helpful information you provided to us!
Please check the issue from our next MRTK release and let us know if you still see the problem.
