### ISSUE TITLE
vNext: If loading a system fails with an exception, no systems are active

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#3037]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
This bug should NOT stop the beta release as I have not found a 100% reliable repro,

If an exception is encountered when starting up a core or extension system, other systems are not activated (not attempted or ignored).

On HoloLens, when this occurs, a skybox is rendered and the spatial awareness system is not loaded.

**To Reproduce**
I have hit this randomly running on HoloLens. The easiest way to validate a fix is to force an exception in MixedRealityToolkit.Initialize().

**Expected behavior**
The failing system to not be available and other, unrelated systems to be active.

**Actual behavior**
Unrelated systems are not loaded.

**Unity Editor Version**
2018.2.13f1 and 2018.2.14f1

**Mixed Reality Toolkit Release Version**
mrtk_2018beta_stabilization

**Additional context**
I have a fix for continuing the Initialize method. Still need to uncover all related exceptions when later code assumes a service has successfully started.

**Comment by StephenHodgson** [comment]
What's causing the system to fail loading?

**Comment by davidkline-ms** [comment]
Activation failure. The times I have seen it are a nullreference exception trying to start the input system.

**Comment by davidkline-ms** [comment]
It is important to both try to root cause the exception as well as be resilient to such failures.

**Comment by davidkline-ms** [comment]
Chances are that the complete fix will be more involved that what we should take for beta.

**Comment by StephenHodgson** [comment]
Wondering if a try catch around any activation would help.

**Comment by davidkline-ms** [comment]
> Wondering if a try catch around any activation would help.

That's in my working branch right now... :)
