### ISSUE TITLE
Preview does not exist in namespace Windows.Perception.Spatial

### ISSUE THREAD

**Issue by ericalbers** [Microsoft/MixedRealityToolkit-Unity#3040]
Doing a raw pull and loading into  unity 2017.2.1f1 gives an error on trying to build the QRCodesSample
```
Assets\holotoolkit-preview\QRTracker\Scripts\SpatialGraphCoordinateSystem.cs(30,36): error CS0234: The type or namespace name 'Preview' does not exist in the namespace 'Windows.Perception.Spatial' (are you missing an assembly reference?)
```

Any ideas?

**Comment by benzben** [comment]
Same here for Unity 2018.1.0f2

**Comment by StephenHodgson** [comment]
Is your computer's os using the windows insider preview build?

**Comment by ericalbers** [comment]
No
Version 1803 Build 17134.285
SDK: 10.0.17134

**Comment by StephenHodgson** [comment]
I'm fairly certain you'll need to use the insider preview and also install the preview windows SDK.

**Comment by ericalbers** [comment]
Ok, will try and let you know

**Comment by ericalbers** [comment]
Yes!, updating to insider sdk 10.0.17763.0 has fixed this.
Thank you!
