### ISSUE TITLE
MarkerDetectionHololens reference is null on NewDeviceDiscovery (SpectatorView)

### ISSUE THREAD

**Issue by benzben** [Microsoft/MixedRealityToolkit-Unity#3042]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit

**Describe the bug**
I'm trying to get the SpectatorView Preview running, but I'm having several errors like the one in the title.
Unity gives me these errors:

![grafik](https://user-images.githubusercontent.com/39216624/47790595-e4f44480-dd17-11e8-8c53-7dca17426ec4.png)

**To Reproduce**
I just followed the steps on:
https://docs.microsoft.com/en-us/windows/mixed-reality/spectator-view

**Actual behavior**
I can't build neither for Hololens nor for iPhone

**Unity Editor Version**
2018.1.0f2

**Additional context**
Also in the inspector panel looking at the SpectatorView prefab, the NetworkManager seems to be empty:
![grafik](https://user-images.githubusercontent.com/39216624/47790724-33094800-dd18-11e8-89ec-de95be839168.png)

**Comment by davidkline-ms** [comment]
edited issue to reflect that this is in HoloToolkit.

**Comment by danielescudero** [comment]
@benzben Unity 2017.2.1p2 is the officially supported version but has been tested up to 2017.4.9

**Comment by benzben** [comment]
@MrGuy I can't use the Awake() function as it's not a MonoBehaviour Script, right?

Also I noticed that the SpectatorViewNetworking.prefab I'm using doesn't have the 'NetworkManager' GameObject that appears in this tutorial (https://docs.microsoft.com/en-us/windows/mixed-reality/spectator-view)
![untitled](https://user-images.githubusercontent.com/39216624/48182500-aec44f80-e32b-11e8-95df-8bfc49388481.png)
Where do I find this component?

**Comment by MrGuy** [comment]
Ah, right - You can't use the Awake function there.
There is a portion of those scripts which detect the null references and prints those errors.
You could use the  FindObjectOfType<>() there to find the objects.
Alternatively, you could just use the Start() callback.

I think the network manager script has been moved on to the Shared > Networking object.

**Comment by benzben** [comment]
@danielescudero I just installed Unity 2017.3 for testing and I get the exact same errors.

@MrGuy "I think the network manager script has been moved on to the Shared > Networking object."
When I search in my Assets for 'NetworkManager' it does not find anything except 'SpectatorViewNetworkManager.cs'.
I will try the idea of using FindObjectOfType now, but somehow I doubt that this will result in success. Something's just really messed up in my configuration, but I just can't figure it out. I downloaded the newest Git Repositories, so this should not be the problem.

**Comment by MrGuy** [comment]
Here is the component the Network Manager was loaded on for me:
![image](https://user-images.githubusercontent.com/890159/48184411-a72d9680-e37d-11e8-98e1-dddf0ac81018.png)

Note that the NewDeviceDiscovery and SpectatorViewDiscovery scripts were already included in the SpectatorView prefab, no need to drag in the extra SpectatorViewNetworking prefab.

**Comment by benzben** [comment]
Yeah sure, these components I have too, but as I posted in this reply (https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3042#issuecomment-436892261), the SpectatorViewNetworking.prefab seems to lack a component 'NetworkManager'.
Also I have to point out that I get all these errors even before trying to hit play or build, they appear as soon as I drag the prefabs into my scene.

**Comment by benzben** [comment]
I deleted the SpectatorViewNetworking prefab in my scene as you said and tried to build, then Unity gives me these errors:
![grafik](https://user-images.githubusercontent.com/39216624/48185994-02886600-e337-11e8-98f3-4d55d048058c.png)
The first errors I remember seeing an extra issue for that. However, again I have the missing 'NetworkManager' on SpectatorView.

**Comment by benzben** [comment]
Regarding this issue (https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3040) I solve the problems with the QR Tracker.
However, again I can't build as I get the errors
![grafik](https://user-images.githubusercontent.com/39216624/48187341-1a61e900-e33b-11e8-93cc-e0b208b3b5aa.png)

**Comment by benzben** [comment]
Okay, so this very issue (MarkerDetectionHololens reference is null on NewDeviceDiscovery) is actually solved by using FindObjectOfType for every component in the Awake function (there actually ARE awake functions, I just missed them because I was blind...).
This issue may be closed, I will continue in another specific issue.
