### ISSUE TITLE
vNext Proposal: Change public enum suffix.

### ISSUE THREAD

**Issue by Railboy** [Microsoft/MixedRealityToolkit-Unity#3045]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Is your feature request related to a problem? Please describe.**
The current naming convention for public enums (suffix `Type`) should change. Not everything an enum enumerates can or should be considered a 'type.' For instance:

```
 AppModeEnum.Initializing
 SessionStateEnum.InProgress
```

becomes:

```
AppModeType.Initializing
SessionStateType.InProgress
```

These are clumsy and redundant. A 'type' of mode or a type of state is just a mode or state.

**Describe the solution you'd like**
I'd love to eliminate the suffix for enums altogether, but `Enum` works. It's content-neutral and it helps discoverability.

Since this would be a breaking change it's something we'd want to do before vNext exits beta.

**Comment by StephenHodgson** [comment]
I think we've [already agreed to this naming convention](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/CodingGuidelines.md#do-7).

**Comment by Railboy** [comment]
I figured now would be an ideal time to re-open the subject since we don't have a lot else on our plate.

**Comment by SimonDarksideJ** [comment]
Agreed "Type" is already the enum suffix as per the standards guide.
If there are instances that are not following this, then yes, they should be tidied up.  Do you have some specific examples where this is not being followed @Railboy ?

**Comment by Ecnassianer** [comment]
Most of the agreement around the "Type" suffix was a lot of "I'm ok either way, I guess Type works fine." I was among those answers.

However this example compels me to change my opinion to "Yeah, Enum is better, but it's not a big deal":

> AppModeType.Initializing
> SessionStateType.InProgress

Maybe we should remove the enum guidance from the style guide and leave it to individual judgement? It almost seems like the value of the enum guidance is less than the maintenance of debating the enum guidance.

**Comment by StephenHodgson** [comment]
It doesn't matter to me much, shoot let's just loose it altogether! 🙃 Haha, jk. I think the fact that we have a suffix actually serves a functional purpose when it comes to declaring names of fields and properties in the class based off the enum type.

**Comment by Yoyozilla** [comment]
Breaking change, we should review next shiproom to make a decision with the group

**Comment by jwittner** [comment]
@StephenHodgson Seriously though, lets drop the whole suffix. 'Enum' especially is banned by the standard .Net naming conventions here: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces#naming-enumerations

**Comment by davidkline-ms** [comment]
Changing to NO suffix :)
