### ISSUE TITLE
Dialog appears and stays behind user in DialogsExample

### ISSUE THREAD

**Issue by raddman1** [Microsoft/MixedRealityToolkit-Unity#3052]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit 
**Describe the bug**
When testing the dialog system on the HoloLens I do not see the dialogs in game view.  After some digging in the Unity Editor the scene view shows the dialog has been created in the hierarchy. The dialog is being instantiated and then placed and updated directly behind the user by the solver scripts. 
**To Reproduce**
1. Grab master branch from https://github.com/Microsoft/MixedRealityToolkit-Unity
2. Load project in Unity
3. Open Assets/HoloToolkit-Examples/UX/Scenes/DialogsExample.unity
4. Enable Holographic Emulation -> Select Remote To Device -> put in IP of your device.
5. Hit Play.
6. Gaze at "One Button" button and air tap. 
7. Observe that no dialog is displayed as you move head around.
8. take off headset and switch to Scene view in editor. 
9. Select MixedRealityCameraParent in hierarchy
10.  View from top down perspective
11. Rotate HoloLens with hands and notice that Dialog(Clone) that was created is staying behind user.

**Expected behavior**
I expected Dialog(Clone) to appear in view infront of camera facing the user so they can read and dismiss dialog.

**Actual behavior**
Dialog(Clone) is incorrectly being placed behind the user.  

**Unity Editor Version**
I tested in 2018.2.8f1 and 2017.2.3f1 

**Additional context**
Seems like an issue with how the position is determined by solver scripts.

**Comment by keveleigh** [comment]
This sounds like it might be a duplicate of #2933. Can you take a look at the related PR and see if that fixes your issue?

**Comment by raddman1** [comment]
The fixes made in SolverHandler for checking TrackedObjectToReference != TrackedObjectToReferenceEnum.Head solve the problem.  Thanks for the quick response.

**Comment by raddman1** [comment]
Issue will be fixed when #2933 fix is merged to master.
