### ISSUE TITLE
Diagnostics placement is sporadic and displays no data

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#3056]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
Diagnostics view is meant to display diagnostic information in the scene.  However, when enabled, the "box" is not in the view (placement of the mesh is odd) and there is no content displayed.

**To Reproduce**

* Enable diagnostics in the configuration profile
* Set Visible to True in the diagnostics profile.
* Create a new Scene
* Click Mixed Reality Toolkit > Configure
* Enter play mode.

**Expected behavior**
Diagnostics view should be in the FoV of the headset/camera with data displayed

**Actual behavior**
Placement of window is sporadic and no data is displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/1793042/47917400-4c89cb80-dea1-11e8-9c8f-ef41cdc3e678.png)

This "window" was placed below and to the left of the player, single sided texture so it's only visible if the player steps back.

**Unity Editor Version**
2018.2.13f1

**Mixed Reality Toolkit Release Version**
2018.9 beta

**Additional Notes**
Tested using Seated / standing mode with no boundary

**Comment by davidkline-ms** [comment]
i'll take this one. I am investigating adding additional data

**Comment by davidkline-ms** [comment]
As part of this, the diagnostic window should be parented to the camera (or parent).

The intent weas to be headlocked so the data was always visible.

**Comment by StephenHodgson** [comment]
> The intent weas to be headlocked so the data was always visible.

Headlocked sounds terrible lol. Can we make that configurable at least?

**Comment by davidkline-ms** [comment]
> Headlocked sounds terrible lol. Can we make that configurable at least?

We *can*, though the greatest utility of this feature is to give you information on the portion of the scene that is in view (ex: as you move through the scene, the data is relevant to what you are seeing)

**Comment by StephenHodgson** [comment]
I noticed that this also doesn't really put anything in the headset, but only prints the values to the editor window
