### ISSUE TITLE
Getting to know the Mixed Reality Toolkit Input System - New Guide

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#3057]
# Overview
A guide to understanding the MRTK Input system is required in the Documentation area, to describe how to make the best use of the new Input System

# Requirements
Users should be informed on how to:
- [ ] Configure the input system
- [ ] Make the best use of Pointers / Gaze Focus
- [ ] Build Scripts to react to Input Action events

# Acceptance Criteria
- [ ] As a user I can create interactions using the MRTK Input System in my project
- [ ] As a User, I can configure Pointers and clearly understand how they work
- [ ] As a User, I can utilize Gaze and know how to configure / enable / disable it
- [ ] As a User, I can utilise and react to Input Actions in script.

**Comment by Yoyozilla** [comment]
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Overview.html
