### ISSUE TITLE
Creating interactions between the player and your project - new guide

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#3061]
# Overview
The MRTK needs to provide some good real world examples use cases for implementing interactivity in scenes, based off current good working practice.

# Requirements
Users need to be able to build their own scenes and have documented working cases for good use of interactivity with the MRTK
* Requirement 1
* Requirement 2

# Acceptance Criteria
- [ ] As a user, I should have documented cases for good practice
- [ ] As a user, something else?

**Comment by StephenHodgson** [comment]
What are requirements 1 and 2?

**Comment by SimonDarksideJ** [comment]
I ran out of steam creating these, looking for help to define what a guide describing "Interactions" should look like / achieve.

#3065 seems to be making a good start outlining what this should entail

**Comment by Yoyozilla** [comment]
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_HandInteractionExamples.html
