### ISSUE TITLE
Configuration Profile Usage Guide - new guide

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#3062]
# Overview
A general purpose configuration profile guide is required to help users understand how profiles work, how to switch them out with tips and tricks

# Requirements
Step by step usage instructions to show how:

* Copy profiles
* Create profiles
* Swap Profiles
* Do's and Dont's

# Acceptance Criteria
- [ ] As a user, I understand what the default profiles are and why they are locked
- [ ] As a user, I understand how to create and organise new profiles
- [ ] As a user, I know how to swap out profiles at runtime and good working use cases
- [ ] As a user, I know how profiles are created so I can build my own

**Comment by Yoyozilla** [comment]
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/MixedRealityConfigurationGuide.html

**Comment by SimonDarksideJ** [comment]
Please reopen @yoyozilla as that guide is already out of date, screens have changed with the rc and does not include the newer screens
