### ISSUE TITLE
Guide to Pointers documentation - new guide

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#3064]
# Overview
Users need to understand how to fully utilize pointers within the MRTK and make the best advantage of them with the new multi-pointer system.

# Requirements
Users need to understand the concept and implementation of pointers
* Different kinds of pointers
* Registering pointers
* Listening to pointers
* Adding interactivity around pointers

# Acceptance Criteria
- [ ] As a user, I understand what pointers are and why multiples of them are a good thing
- [ ] As a user, I can configure pointers for my project and understand how they are used
- [ ] As a user, I can write code that responds to pointer and understand the data they deliver
- [ ] As a user, I understand the state model surrounding pointers and their use.

**Comment by Yoyozilla** [comment]
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Pointers.html
