### ISSUE TITLE
Controllers appear fuzzy when Post Processing effects are enabled

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#3071]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
Default Gizmo controllers appear "Fuzzy" when used in a scene using the Unity Post Processing effects

**To Reproduce**

1. Create a new Unity project, using the "3D with Extras" template
2. Import the MRTK and configure the default scene
3. Connect controllers and run

**Expected behavior**
Controllers should appear the same whether they are run with or without the post processing effects

**Actual behavior**
Fuzzy controllers

**Screenshots**
Blank scene
![image](https://user-images.githubusercontent.com/1793042/47965477-c5268e80-e03f-11e8-862a-727354debdbc.png)

Post Processing Effects enabled Scene
![image](https://user-images.githubusercontent.com/1793042/47965481-cf488d00-e03f-11e8-98e1-c39f6bdfdd0f.png)

**Unity Editor Version**
2018.2.14f1

**Mixed Reality Toolkit Release Version**
2018.9 beta

**Additional context**
I suspect this has to do something with the MRTK Standard shader used by the Gizmo when the PPS is enabled.

**Comment by StephenHodgson** [comment]
Likely something to do with your post processing effects. lol. 

Not sure this is a bug related to MRTK

**Comment by SimonDarksideJ** [comment]
Likely, but what exactly.  The Gizmo uses the standard materials and standard shader from the MRTK and in a scene using post processing, it looks as above.
So if changes are needed, we need to understand what they are.

**Comment by Yoyozilla** [comment]
bulk closing older issues.. please reopen if this repros on the latest Unity 2018 + MRTK
