### ISSUE TITLE
Add native Oculus support for the MRTK

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#3072]
## Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?
Mixed Reality Toolkit

## Is your feature request related to a problem? Please describe.
Have native Oculus support to enabling publishing of MRTK solutions to the Oculus store

## Describe the solution you'd like
For it to work? :D 

## Describe alternatives you've considered
None available, Oculus only accept packages using their SDK

## Additional context
Check the chat on Reddit here:
https://www.reddit.com/r/virtualreality/comments/9u3326/the_mixed_reality_toolkit_beta_has_launched/

**Comment by Troy-Ferrell** [comment]
Resolving as dupe in favor of #7272

**Comment by keveleigh** [comment]
Re-opening, as @davidkline-ms and I have been discussing supporting both pipelines.

**Comment by SimonDarksideJ** [comment]
Interesting, would love to be involved in the discussions to help push this forward.  Oculus is a big target at the moment and we've had a lot of interest in the XRTK due to its inbuilt support for it.

**Comment by davidkline-ms** [comment]
This will be implemented on unity 2019 via the XR Management platform. It is an open discussion if 2018 native sdk support is needed / desired.
