### ISSUE TITLE
Add native SteamVR support - including Steam Actions

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#3073]
## Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?
Mixed Reality Toolkit

## Is your feature request related to a problem? Please describe.
Community members have stated they would also like to see native SteamVR support instead of using Unity's OpenVR implementation (I'd have to agree :D )

## Describe the solution you'd like
SteamVR implemented as a native Platform

## Describe alternatives you've considered
Currently Steam VR is implemented using OpenVR

**Comment by davidkline-ms** [comment]
MRTK currently has a SteamVR implementation for the 2018 (and legacy 2019) XR platform. On 2019, it will be utilizing the XR Management platform as available.
