### ISSUE TITLE
vNEXT Task: Refactor Controller Mapping Profile to accept individual controller scriptable objects.

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#3074]
# Overview
At the moment each controller is pre-populated in the controller mapping profile. Ideally we want to give developers full control over the devices and controllers they'd like to use. I'd like to propose changing the controller mapping profile from buttons to Scriptable Object slots for maximum flexibility and customization. This will enable us to easily extend and add new controller types in the future. At present it's a bit difficult. (I had plans to do this before beta but was limited by time and higher priority items).

# Breaking Changes
The controller mapping profiles array of mappings will be turned into their own individual scriptable object profiles which will be assigned in the inspector of the controller mapping profile.

# Requirements
* Controller Mapping Profile should have controller object slots to fill instead of buttons.
* Adding new controller implementations should be simple and easy.
* The only UX change should be the buttons be replaced with scriptable object fields.

# Acceptance Criteria
- [x] Users can create and assign individual controller mapping profiles.
- [x] Users can assign actions to specific buttons and inputs using the existing controller popout windows.

**Comment by Yoyozilla** [comment]
done
