### ISSUE TITLE
System Initialized event

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#3078]
There are likely scenarios where an application may need to know that a system has been initialized / reset and respond accordingly.

Design wise, I envision a single event something like this:
void OnSystemInitialized(IMixedRealityService systemInstance)

This would enable client code to react to the change and (potentially) update existing objects to reflect the changes in the specific system (for example, the desired material or model).

This is not a breaking change as the interface would be additive and optional.

# Requirements

- All existing services send the system initialization event
- Client code can handle system [re]initialization

# Acceptance Criteria

- [ ] Clients wishing to handle initialization events can respond appropriately
- [ ] Clients wishing to NOT handle initialization events need not be changed

**Comment by StephenHodgson** [comment]
Awesome proposal, although I think this should be a task 😄

**Comment by StephenHodgson** [comment]
Please add some requirements and acceptance criteria.

**Comment by davidkline-ms** [comment]
Will look into this as part of the system interface rework that I am investigating

**Comment by polar-kev** [comment]
Closing out in favor of thinking through the entire core architecture.
