### ISSUE TITLE
vNext: Log errors or warnings when MRTK profile fields are blank.

### ISSUE THREAD

**Issue by Ecnassianer** [microsoft/MixedRealityToolkit-Unity#3094]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Is your feature request related to a problem? Please describe.**
I spent like 2 hours debugging and had to have Kurtis come over to help me figure out why one of my MRTK features wasn't working. Turns out I didn't have my Additional Service Providers profile hooked up. I don't know how it got unhooked (something must have happpened while I was updating MRTK to a new version).

**Describe the solution you'd like**
There wasn't a warning or message about a lack of Registered Service Providers. There should be. I think we can assume any missing profile is an error, or at least a warning state. If people want to turn it off, they should just create a blank profile and put that there.

![configerrors](https://user-images.githubusercontent.com/231247/48164031-35c6e880-e296-11e8-94ff-9b170fcb36ae.jpg)

**Comment by Ecnassianer** [comment]
No, what I mean is I _had no registered services profile_. If it's misconfigured, there's not a lot we can do. If it's _missing entirely_ on the other hand...

**Comment by StephenHodgson** [comment]
No repro steps?

**Comment by StephenHodgson** [comment]
One thing we considered as well was to make the concrete implementations register their extension services as needed. That way they don't need to be registered in that profile. The reason why we didn't go this route though was because it wasn't easy to immediately identify all of the extension services that would be registered at run-time.

**Comment by davidkline-ms** [comment]
> No, what I mean is I had no registered services profile.

Got ya. Note that there are some services (boundary and diagnostics) that do not require registered extensions. We should be smart on when to alert devs.

**Comment by SimonDarksideJ** [comment]
Are you referring to specific dependencies?

We cannot guarantee a service can be registered as it cannot be known from one service to the next what the concrete implementation will be for a specific service at runtime.  (here's a bad example) So if I use a input device manager which depends on the InputSystem, I cannot know which concrete input system should be created if I haven't configured it.

So the best "fall back" position would be, at config time, to highlight dependencies and WARN the user if a dependant system isn't configured.  However, we must still be able to allow that system to still run, in case that is actually their intention (e.g. a custom InputService)

**Comment by StephenHodgson** [comment]
Likely in our Services that depend on these extension services we either need to have that service create and register that concrete implementation or better handle how to act and warn developers if that extension service is missing. I thought we made the input systems with these kinds of dependencies pretty robust, and nicely fallback if they were not registered. (Can't say for certain for spatial awareness system)

**Comment by StephenHodgson** [comment]
@Ecnassianer could you give us a sample of some of the errors you were getting?

**Comment by davidkline-ms** [comment]
> We cannot guarantee a service can be registered as it cannot be known from one service to the next what the concrete implementation will be for a specific service at runtime.

We could have extension services implement specific interface(s) that can be searched for at runtime. This is how the spatial awareness system works. The observer extension implements a specific interface that the system looks for in order to be able to control the state. 

It *currently* does not alert the developer to it not being found. That would arguably be a good thing and aid in debugging.

**Comment by Ecnassianer** [comment]
@SimonDarksideJ Is your question directed at me? If so I don't think we're talking about the same thing.

This is what I'm asking for:
![configerrors](https://user-images.githubusercontent.com/231247/48163817-90ac1000-e295-11e8-92ac-006933ee8f7f.jpg)

@StephenHodgson I'm not getting any errors, it's failing silently, that's my point. The service that is failing isn't one of the default MRTK services, so this issue isn't tracking any work in the services. This is a request for profile validity checking.

**Comment by StephenHodgson** [comment]
Ah I see. I wonder how we can do profile validity checks.

I thought it's already setup this way:
- If a system is enabled, it is required to also have a profile (and under the hood it actually says the system is disabled if the profile is missing)
- If a system is disabled, it shouldn't matter if the profile is empty.

**Comment by StephenHodgson** [comment]
Which system and extension service was giving you problems?

**Comment by Ecnassianer** [comment]
I think you misunderstand. The field I drew a magenta arrow pointing at did not have a profile in it. ALL the registered service providers were missing, because there was no profile.
