### ISSUE TITLE
Unclear how to move the camera in Editor

### ISSUE THREAD

**Issue by motionsmith** [Microsoft/MixedRealityToolkit-Unity#3095]
## Overview
With vNext in Editor, it is unclear how to simulate the movement/rotation/airtap inputs, if there is a way. When I create a new project, the keyboard/mouse do not seem to work for user input, besides a strange mouse that appears in addition to the existing mouse. 

In the previous version, there was a `ManualGazeControl` script which allowed camera rotation by right-clicking the mouse, then moving it. There were also `CustomInputControl` scripts that allowed the developer to airtap and move the camera.

## Expected Behavior
For development in editor, I would like to know how to move, rotate, air tap, etc.

## Actual Behavior
In the samples, there is a "fake mouse" that appears when I press play. Neither the keyboard (arrows or wasd) nor the mouse seem to enable navigation and selection input.

## Steps to reproduce

1. Create a new project
2. Import MRTK and the examples.
3. Open an example, change platform to UWP, and add the sample scene. Then press play in editor.

## Unity Editor Version
2018.2

## Mixed Reality Toolkit Release Version
2018.9.0

**Comment by StephenHodgson** [comment]
Hi @motionsmith We've def got plans to enable locomotion in the editor fairly soon. We're looking to take advantage of Unity's Holographic Emulation to handle much of that for us.

**Comment by motionsmith** [comment]
Wow, what a fast reply. That saved me hours of looking around. Thank you.

**Comment by KevGLewis** [comment]
Any updates on this?

**Comment by nablam** [comment]
Re- any updates on this ? Trying to get familiar with mrtkv2 before porting our app :)

**Comment by Yoyozilla** [comment]
Fixed in RC1
see doc here

**Comment by Yoyozilla** [comment]
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSimulation/InputSimulationService.html#camera-control
