### ISSUE TITLE
vNEXT Task: Enable Simulated Input via Mouse when Holographic Simulation is enabled in the editor.

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#3096]
# Overview
We need hook into the Unity Editor's Holographic Simulation and provide a way to simulate hand/gaze input when this feature is turned on.

# Requirements
* Mouse Input is on by Default in the default configuration profile
* Mouse Input support raising simulated events and actions based on the Holographic Emulation provided by the editor.

# Acceptance Criteria
- [ ] I can turn on Holographic Emulation in the Unity Editor and my mouse input be used in play mode.
- [ ] I can do all of the simulated hand gestures in the editor like normal, and the events are forwarded through the input system.
- [ ] I can Tap
- [ ] I can Tap and Hold
- [ ] I can Tap and Drag
- [ ] I can Tap and Manipulate
- [ ] I can use two handed gestures

**Comment by davidkline-ms** [comment]
> We need hook into the Unity Editor's Holographic Simulation 

Is that a requirement? The HoloToolkit had a great simulated input feature that did not rely on Holographic Simulation. 

Also, is this proposal cross platform to other systems (ex: OpenVR, iOS, etc)?

**Comment by StephenHodgson** [comment]
> Is that a requirement? 

Absolutely.

**Comment by StephenHodgson** [comment]
> Also, is this proposal cross platform to other systems (ex: OpenVR, iOS, etc)?

No, Holographic Emulation is a unity editor feature for UWP only.
https://docs.unity3d.com/2017.3/Documentation/Manual/windowsholographic-emulation.html

>Holographic Emulation allows you to prototype, debug, and run Microsoft HoloLens projects directly in the Unity Editor rather than building and running the game every time you want to see the effect of a change. This vastly reduces time between iterations when developing holographic applications in Unity.

Why should we rebuild something that the editor already supports?
We should be building on top of and utilizing what's already there.

Also the old HTK simulated input wasn't that great and had it's own set of problems.

**Comment by cre8ivepark** [comment]
Described this in #3093 . Unfortunately, current Holographic Emulation only supports Xbox controller's input. To become a relevant alternative option, mouse input supported need to be added to this.
