### ISSUE TITLE
vNEXT: Update inconsistent naming of core system implementations

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#3115]
All core system services should have consistent naming.
With the new naming conventions, I've noticed we've got some inconsistent names.

Ideal: `<FeatureName>System`

I think extension services are fine, and don't need to update the names right away, but I'd at least like to address the core system services first.

List of good:
- `MixedRealitySpatialAwarenessSystem`

List of bad:
- `MixedRealityBoundaryManager`
- `MixedRealityDiagnosticsManager`
- `MixedRealityInputManager`
- `MixedRealityTeleportManager`

**Comment by SimonDarksideJ** [comment]
I thought we went through and cleared this up for the Beta, gosh darn it.
Needs fixing ASAP

**Comment by Yoyozilla** [comment]
trivial fix. David will update.

**Comment by davidkline-ms** [comment]
Boundary, Diagnostics and Teleport systems have previously been updated. The remaining piece is input

**Comment by davidkline-ms** [comment]
Fixed with #3342 (and other system move PRs)
