### ISSUE TITLE
Update the "Apply Settings" dialog with choices on import (based on SteamVR dialog)

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#3118]
## Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?
Mixed Reality Toolkit

## Describe the solution you'd like
The current "Configure" screen when first importing the MRTK is an "all or nothing" prompt.

However, while investigating the latest SteamVR support, I found their dialog a lot more useful, as seen below.

![image](https://user-images.githubusercontent.com/1793042/48312528-f1925b80-e5a7-11e8-9064-37ff31e66a95.png)

This would likely be a better solution to the current approach and enable the flexibility to "opt in" to the features the user would like enabled on import.

**Comment by SimonDarksideJ** [comment]
Let's postpone this for review once 2018.3 is released, as the number of options we "Need" to change will be greatly reduced.

**Comment by Troy-Ferrell** [comment]
MRTK project configurator is now configurable. Closing out issue as resolved

![image](https://user-images.githubusercontent.com/25975362/74187926-5d77cf80-4c02-11ea-9ea5-69e5172af9fb.png)
