### ISSUE TITLE
[Hololens] Error when trying to emulate mouse click on a Unity UI with "tap"

### ISSUE THREAD

**Issue by MatteoFantasy** [microsoft/MixedRealityToolkit-Unity#3120]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit 2017.4.2.0 and Mixed Reality Toolkit 2018.9.0 (vNext Beta)

**Describe the bug**
When trying to emulate a mouse click on a Unity UI with the hololens "tap", the following error appears :
```
NullReferenceException: Object reference not set to an instance of an object
UnityEngine.EventSystems.HoloLensInput.EmulateMousePosition (UnityEngine.Vector3 anchorWorldspace, UnityEngine.Vector2 finalOffset) (at C:/buildslave/unity/build/Extensions/UnityHoloLens/Runtime/UI/EventSystem/InputModules/HoloLensInput.cs:183)
UnityEngine.EventSystems.HoloLensInput.GetGazeAndGestureScreenPosition () (at C:/buildslave/unity/build/Extensions/UnityHoloLens/Runtime/UI/EventSystem/InputModules/HoloLensInput.cs:195)
UnityEngine.EventSystems.HoloLensInput.get_mousePosition () (at C:/buildslave/unity/build/Extensions/UnityHoloLens/Runtime/UI/EventSystem/InputModules/HoloLensInput.cs:39)
UnityEngine.EventSystems.StandaloneInputModule.UpdateModule () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/InputModules/StandaloneInputModule.cs:154)
UnityEngine.EventSystems.HoloLensInputModule.UpdateModule () (at C:/buildslave/unity/build/Extensions/UnityHoloLens/Runtime/UI/EventSystem/InputModules/HoloLensInputModule.cs:78)
UnityEngine.EventSystems.EventSystem.TickModules () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/EventSystem.cs:248)
UnityEngine.EventSystems.EventSystem.Update () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/EventSystem.cs:261)
```

**To Reproduce**
- Follow this tutorial
https://forum.unity.com/threads/unity-ui-on-the-hololens.394629/
- Connect to the hololens with holographic remoting
- Click on the button

**Expected behavior**
The "tap" gesture should be registered as a button click

**Actual behavior**
It throws an error

**Unity Editor Version**
- Unity 2017.4.14f1 + HTK 2017.4.2.0
- Unity 2018.2.14f1 + MRTK 2018.9.0

**Comment by StephenHodgson** [comment]
Remove the HoloLens input module. 

Standalone is all that's required.

**Comment by MatteoFantasy** [comment]
Thanks for your answer : it's now doing "something" but the cursor triggers the hover of multiple buttons, and sometimes there's an offset between the cursor and the hovered button.

![hololensuibug](https://user-images.githubusercontent.com/1780378/48781803-1475eb80-ecdd-11e8-8b24-664e76d0509a.png)

**Comment by Yoyozilla** [comment]
Bulk closing older issues. 
Please reopen if it still repros with the latest Unity 2018 + MRTK release
