### ISSUE TITLE
vNEXT Proposal: Provide a way for extension services to only be registered once

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#3127]
# Overview
Currently we have a few different extension services that can be registered more than once, but lots of other devs may want to ensure that there's only one type registered with the service locator. It would be great if there was a way to specify that certain extension services can only be registered once.

# Requirements
* Provide a way to specify when extension services can only be registered with the service locator once.

# Acceptance Criteria
- [ ] I can specify that an extension service can only be registered once.
- [ ] I cannot register another extension service if another of the same type has been registered.

**Comment by SimonDarksideJ** [comment]
Ideally we only want the two Service Locator stores, one for multiples and one for singulars, currently separated by the "IsCoreService" check.
Maybe we should change this "Core Service" approach for a property against the implementation exposed by the interface?

**Comment by StephenHodgson** [comment]
We could add a flag to the `IMixedRealityExtensionService` to mark it as such.

**Comment by SimonDarksideJ** [comment]
Just thinking out loud for changing the interpretation of how the two data stores are used.  DO we make the Singleton/single store available for all developers to use for registering Single instance services.

Meaning the Single Store registry would be used if the implementation requires it.
