### ISSUE TITLE
Xbox One Controller ceases to work correctly RS4 & RS5

### ISSUE THREAD

**Issue by BerndtSam** [microsoft/MixedRealityToolkit-Unity#3130]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit

**Describe the bug**
The Xbox One controller ceases to work correctly in HL deployment to RS4 and RS5. Works great in RS3.

**To Reproduce**
[SampleGitHubProject](https://github.com/BerndtSam/MRTKXboxOneTest)
Build Unity project
Open Visual Studio 2017
Start Debug session and deploy to Remote Device (HoloLens running RS4)
Apply any input to Xbox One controller

**Expected behavior**
The Xbox One controller gives its input to my program which can then manipulate the cubes location.

**Actual behavior**
Upon applying any input to the Xbox One controller, the controller will spam -1 on the horizontal axis or cease to work entirely. If running in debug mode, will occasionally receive the error below:

Failed to get spatial interaction controller - touchpad, thumbstick, and vendor data will be unavailable to the application for InteractionController! Error code: '0x00000000'.

(Filename: C:\buildslave\unity\build\Runtime/VR/HoloLens/Gestures/GestureSource.cpp Line: 822)

**Screenshots**
![capture](https://user-images.githubusercontent.com/10482368/48380748-dd288e80-e68d-11e8-9130-cd3d0105643a.JPG)

**Unity Editor Version**
2017.2.1p2
2017.4.11f1

**Mixed Reality Toolkit Release Version**
Release HoloToolkit 2017.4.2.0

**Additional context**
https://aka.ms/AA342nf

**Comment by Yoyozilla** [comment]
Closing older HTK issue as we are no longer actively working on HTK.

Please upgrade to MRTK V2 for the latest fixes.
