### ISSUE TITLE
Does HL Portal display anchor from World Anchor Store 

### ISSUE THREAD

**Issue by Shubham7694** [microsoft/MixedRealityToolkit-Unity#3145]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit | Mixed Reality Toolkit

**Describe the bug**
Unable to see Spatial Anchor in Web View. I am not sure it's a bug. But wanted to know if HL portal shows anchor from world anchor store or just attaching to game object in scene is enough. I am not able to get anchor even after attaching and saving using world anchor manager api.

**To Reproduce**
Attach world anchor to game object and store using WorldAnchorManager API provided byMRTK. Many a times it fails to delete anchor or even add anchor.

**Expected behavior**

**Actual behavior**
A clear and concise description of what happens instead.

**Screenshots**

**Unity Editor Version**
2017.4.6f1

**Mixed Reality Toolkit Release Version**
2017.4

**Additional context**

**Comment by isurfraz** [comment]
I recommend you post your questions in the hololens and unity forums, as it takes weeks or even months to get replies on here, as you can see from many of the open questions and issues going back to march/april

**Comment by StephenHodgson** [comment]
@davidkline-ms any ideas?

@isurfraz please remember that most of us maintain this repository out of the [kindness of our hearts](https://dev.to/restoreddev/showing-kindness-while-programming-52a7). No response simply means either we don't know, or we're not confident enough to give a satisfactory answer.

**Comment by isurfraz** [comment]
> @davidkline-ms any ideas?
> 
> @isurfraz please remember that most of us maintain this repository out of the [kindness of our hearts](https://dev.to/restoreddev/showing-kindness-while-programming-52a7). No response simply means either we don't know, or we're not confident enough to give a satisfactory answer.

Did not mean any offense stephen, I simply wanted to direct them to a more active place for questions, given that this not really an "issue" as such but more of a question. 

Im well aware that its mainted voluntarily and **thank you greatly for it**, but at the same time I dont think its wrong to let a user know that some issues and questions are not responded to here / take a very long time, and that they will therefore likely get a faster response (and one from a wider range of users) on the more mainstream forums.

**Comment by StephenHodgson** [comment]
No worries, although I am quite curious about the answer to this question too.

We're likely to start working on updating the anchor sharing for vNEXT pretty soon. This might be a helpful tool to complete that feature.

Also, thanks for answering the questions about spatial anchors you did know. Contributions like these are very valuable, and I hope to see you around here more often :)

**Comment by isurfraz** [comment]
> No worries, although I am quite curious about the answer to this question too.
> 
> We're likely to start working on updating the anchor sharing for vNEXT pretty soon. This might be a helpful tool to complete that feature.
> 
> Also, thanks for answering the questions about spatial anchors you did know. Contributions like these are very valuable, and I hope to see you around here more often :)

The one thing I am still quite puzzled about is that anchors very rarely will still get corrupt, and im starting to think this could be tied to something Unity side. We have debugged the hell out of all the holotoolkit code and there doesnt seem to be a "culprit".

I realise this probably just adds more mystery rather than helping, but if it helps reveal a bit where the issue is and is on unitys side, then maybe you will be able to liase with them regarding this in time for the release version of MRTK next winter.

My current thoughts are that the actual world anchor component from unity itself has an issue with corruption and that is why none of us seem to be able to stop it from happening 100% of the time, but I have been wrong in the past!

**Comment by StephenHodgson** [comment]
Nice thing is MSFT has a new [spatial entity store](https://docs.microsoft.com/en-us/uwp/api/windows.perception.spatial.spatialentitystore) that vNEXT is going to take advantage of. Hopefully this will solve some of the issues we've been seeing crop up here and there.

**Comment by Yoyozilla** [comment]
Please reopen your issue in our new spectator view GitHub Repo:
https://github.com/Microsoft/MixedReality-spectatorview

**Comment by keveleigh** [comment]
Re-opening, as world anchors aren't spectator view specific

**Comment by keveleigh** [comment]
The device portal should show anchors loaded in the active app. Simply attaching them should make them visible, but saving them in the anchor store helps persist them across app sessions (after reloading/reattaching them on a new app launch).

Also, this question isn't really MRTK-specific, but would be a great StackOverflow question to give people an easier place to find the answer!
