### ISSUE TITLE
Add support for GLTF importer on HoloLens

### ISSUE THREAD

**Issue by yaqinh** [Microsoft/MixedRealityToolkit-Unity#3153]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
No 

What I want to happen:
When use the GLTF submodule to import GLTF file at runtime in HoloToolkit, it could load the model when the project runs on HoloLens. Personally I believe it is because System.IO access (like FileStream would be denied by HoloLens system and there is no way to fix it) 

**To Reproduce**
Link: https://github.com/yaqinh/Unity-HoloToolkit-GLTF-HoloLens
Please see the Readme file in the repo

**Expected behavior**
The duck.gltf model should appear in the scene and the textMesh should be "flag is true"

**Actual behavior**
The duck.gltf never loads in the scene and the textMesh is the path to the app local folder, which means the GLTF importer never finishs correctly

**Screenshots**

**Unity Editor Version**
2017.4.14F1

**Mixed Reality Toolkit Release Version**
2017.4.2.0

**Additional context**
Could you confirm that the API System.IO.File in Unity does not work at all on HoloLens? Do you have any suggestion about how to make GLTF importer work on HoloLens? Thanks!

**Comment by StephenHodgson** [comment]
I saw you cross posted in the [UnityGLTF repo](https://github.com/KhronosGroup/UnityGLTF/issues/296#issuecomment-439298654) as well. Going to close this as it's not related to the MRTK itself and the other post seems to have answered your question.
