### ISSUE TITLE
Improve Workflow for Stabilization Plane

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#3158]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Is your feature request related to a problem? Please describe.**
As stated in the documentation [here](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/focus-point-in-unity.md):

> On a HoloLens running the Windows 10 April 2018 Update or later, (turning on "Enable Depth Buffer Sharing") will analyze the depth buffer to pick an optimal stabilization plane automatically.

That article incorrectly states that it's turned on by default now, but I see #1939 proposed to address this issue. (And I support that change.) 

Regardless of whether or not #1939 gets implemented, we need to provide better guidance about what to do when **Depth Buffer Sharing** is turned on. In fact, what _should_ be done to the MRTK when this is enabled? Should `StabilizationPlaneModifier` be disabled entirely? Should it's `SetStabilizationPlane` field be set to false? And what changes, if any, should be made to the `InputManager` prefab?

At the very least, I feel something should be added to the **Apply Mixed Reality Project Settings** screen that describes this option. Ideally there would be something that prompts the user to see if all of their devices will be running RS4 or later and changes the settings accordingly.

**Comment by StephenHodgson** [comment]
@jbienzms We don't have the same settings configuration screen in vNEXT, but we can add it to the prompt when importing the first time.

It's a bit strange to grab the SDK and set this property on it, but it is possible to set.

**Comment by Troy-Ferrell** [comment]
Also FYI #5319
