### ISSUE TITLE
vNEXT: Tests fail

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#3160]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
 Mixed Reality Toolkit

Overview
---
MixedRealityToolkitTests are failing.

![image](https://user-images.githubusercontent.com/13334553/48649785-9f3aab80-e9a8-11e8-80e8-4affb5ca1a22.png)

**Comment by davidkline-ms** [comment]
I believe these errors are a result of some methods previously not logging if the active profile was null. Now, activeprofile itself logs.

**Comment by davidkline-ms** [comment]
Here's an example of this: EnableAllServices used to silently fail. Perhaps the test should be update to expect an assert

            //If the Mixed Reality Toolkit is not configured, stop. 
            if (activeProfile == null) { return; }

**Comment by SimonDarksideJ** [comment]
Question is @davidkline-ms how did we merge the Logging PR if the tests hadn't been run?
Should not have gotten this far.  Guess we need to tighten up our testing and got to work on the automated CI testing to ensure PR's cannot be committed if existing tests are failing.
