### ISSUE TITLE
vNEXT: Configuring an empty scene for the MRTK raises errors

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#3161]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
 Mixed Reality Toolkit

**Describe the bug**
When configuring a new scene, errors occur

**To Reproduce**
1. Create new scene
2. Click configure.
3. See errors

![image](https://user-images.githubusercontent.com/13334553/48650452-fd688e00-e9aa-11e8-8ef1-989c14bb6ea3.png)

**Comment by SimonDarksideJ** [comment]
Again, like with #3160 we need to tighten up our testing of the project if a single PR can reduce the dev repo to this state @davidkline-ms
