### ISSUE TITLE
vNext Proposal: [BREAKING CHANGE] Remove requirement for IFocusHandler to be an IFocusChangedHandler

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#3168]
# Overview
Many application scenarios need to know of an object is being focused or not focused without the need to track when a specific focus change occurs.

As defined, IFocusChangedHandler is independent of IFocusHandler, yet the reverse is not true.  The following implementation works as expected and illustrates how the two interfaces are independent.

```
    public class FocusIndicator : MonoBehaviour, IMixedRealityFocusHandler
    {
        private new Renderer renderer = null;
        private Material defaultMaterial = null;

        [SerializeField]
        private Material focusMaterial = null;
        public Material FocusMaterial
        {
            get { return focusMaterial; }
            set { focusMaterial = value; }
        }

        private void Start()
        {
            renderer = gameObject.GetComponent<Renderer>();
            if (renderer != null)
            {
                defaultMaterial = renderer.sharedMaterial;
            }
        }

        public void OnBeforeFocusChange(FocusEventData eventData)
        { }

        public void OnFocusChanged(FocusEventData eventData)
        { }

        public void OnFocusEnter(FocusEventData eventData)
        {
            if ((renderer != null) && (FocusMaterial != null))
            {
                renderer.sharedMaterial = FocusMaterial;
            }
        }

        public void OnFocusExit(FocusEventData eventData)
        {
            if ((renderer != null) && (defaultMaterial != null))
            {
                renderer.sharedMaterial = defaultMaterial;
            }
        }
```

# Requirements

* Remove dependency that IFocusHandler has on IFocusChangedHandler
* Update consumers to either: specify both interfaces or remove unused On*FocusChanged methods

# Acceptance Criteria

- [x] Application can be implemented using the slimmer IFocusHandler to indicate enter/exit
- [x] Application can add support for I*FocusChanged by inheriting from IFocusChangedHandler
- [x] Breaking change has been documented

**Comment by StephenHodgson** [comment]
I think this makes sense. I could incorporate it into the focus refactoring that's already in progress. Make all the breaking changes at once.

**Comment by davidkline-ms** [comment]
Sounds good.
