### ISSUE TITLE
Spectator View (Preview) README needs updating with new instructions

### ISSUE THREAD

**Issue by BenWoodford** [microsoft/MixedRealityToolkit-Unity#3169]
The instructions direct you to the discontinued ARKit Plugin on the Asset Store for one.

Plus, I feel like we really should bundle the required DLLs with MRTK? It's like that for pretty much everything else in MRTK after all. It's a lot of extra steps for DLLs that are going to usually look identical from one machine to the next.

EDIT: Also the Unity ARKit plugin is provided with the Preview release package

**Comment by StephenHodgson** [comment]
I think there was some question about the legality of redistribution of such dlls

**Comment by BenWoodford** [comment]
Another suggestion: Recommend a known-to-be-working `vcpkg` commit. `02839ae4a83d505bae17d5856ce851af29c89c65` seemed to work for me (at least it resolved the issue with `tiff` I was having)

**Comment by BenWoodford** [comment]
Seems the main objection to including them was here: https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1884#discussion_r177601177

@davidkline-ms why...? Policy or not it makes using the plugin _considerably_ more difficult, especially as  using specific versions through `vcpkg` is pretty damn unintuitive and using `master` seems to be prone to breaking and/or version updates that mean you have to roll back to a commit or modify the included library files due to OpenCV having versioned DLLs and Libs.

**Comment by BenWoodford** [comment]
> > it resolved the issue with tiff I was having
> 
> @BenWoodford What issue were you having with tiff? Have you opened a bug on vcpkg?
> 
> @StephenHodgson if you wanted to add instructions to recommend 56ea0dca4098754cee6dba7766c9e38d1fe40165, you could do
> 
> ```
> >git clone -n https://github.com/microsoft/vcpkg
> >cd vcpkg
> >git checkout 56ea0dca4098754cee6dba7766c9e38d1fe40165
> ```

I have updated the issue in question here: https://github.com/Microsoft/vcpkg/issues/4745

Tiff doesn't build on the lastest master.

**Comment by Yoyozilla** [comment]
@chrisfromwork  is this part of the doc update you are doing for spectator view?

**Comment by chrisfromwork** [comment]
So, i have updated the clone instructions to also try master branch if the last known good commit fails. I agree with Ben that we should figure out a better mechanism for distributing the plugin dll's so that developers don't have to obtain opencv/compile native code. Right now its seeming like we may be able to use Nuget packages for this. But it is still TBD.

**Comment by chrisfromwork** [comment]
I'm closing this issue for now based on a lack of activity. If you are still blocked by not being able to obtain spectator view native plugins, please reopen this issue.
