### ISSUE TITLE
The "select" voice command no longer fires an event on Windows Mixed Reality

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#3177]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
When you say "select" on Windows MR, the MRTK input system should fire an input down and input up for the "select" action.

This is a regression, as it previously worked when we were listening for the `InteractionManager`'s events, as voice comes across as events but not as an actual "state". Now that #2890 moved away from eventing to polling, the "select" voice command isn't represented in the `InteractionManager`'s states.

**To Reproduce**
1. Add an input handler to the scene, responding the the Select event.
2. Gaze at the input handler and say "select".

Expected: the handler responds
Actual: the handler doesn't respond because no event is fired

**Mixed Reality Toolkit Release Version**
MRTK Beta and latest mrtk_development

**Comment by Yoyozilla** [comment]
kurtis has two fix he is exploring.

**Comment by NorbertNemec** [comment]
I came across this issue in my attempt to fix the air-tap in Holographic Remoting. IIRC, my original approach to fix that issue would actually have accepted verbal "Select" commands as well:
    https://github.com/NorbertNemec/MixedRealityToolkit-Unity/tree/experimental-input-select-fix
Please have a critical look -- the patch as it is should not be used since it will have side effects, but it might still help inspiring a solution.

**Comment by keveleigh** [comment]
This was fixed when the HL2 payload was added to mrtk_dev.
