### ISSUE TITLE
vNext Task: Invert the relationship between the Spatial Awareness System and Observers

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#3180]
# Overview
In consideration of the proposed DataProvider refactor (#3170),  the SpatialAwarenessSystem -> Observer relationship needs to be modified to have the Observer query the system rather than the system direct the observer.

For example, instead of having a Mesh observer be instructed to start it would, instead, ask the system if it should be running.

This will simplify the system architecture and lead to more robust implementations.

As a side effect, the IMixedRealitySpatialAwarenessObserver interface may no longer be required.

# Requirements

* Existing observer implementations will be updated to support #3170
* Spatial Awareness System interface / implementation will be modified such that customer can target specific systems (ex: mesh) when calling Start/StopObserver
* Observers will ask the Spatial Awareness System if they should start/continue running instead of the system instructing the observer.
* IsRunning becomes a system and not an observer concept.

# Acceptance Criteria

- [ ] Spatial awareness system outward behavior is unchanged
    - [ ] Additional Start/StopObserver arguments use default parameters to avoid breaking changes in application code.
- [ ] Demo scene is updated to conform to the new patterns
- [ ] Default profiles updated
- [ ] Breaking changes documented for release notes

**Comment by StephenHodgson** [comment]
Pretty sure we're still going to need that interface.

**Comment by davidkline-ms** [comment]
> Pretty sure we're still going to need that interface.

When I invert the relationship, we may just be able to use the new data provider interface.

> I've already updated the spatial awareness system to use spatial observers as data providers.

I saw that, thanks for doing it! This is more about cleaning up how the system works with observers. Your change sparked some of the discussion.

**Comment by StephenHodgson** [comment]
I'd still like to have a more specific interface for when you register spatial observer data providers.

It helps filter out the concrete classes to use in the inspector, plus we might have some additional requirements for what a spatial observer is

**Comment by davidkline-ms** [comment]
> It helps filter out the concrete classes to use in the inspector, plus we might have some additional requirements for what a spatial observer is

I am 100% supportive of that. Chances are, at least for now, that it will contain no additional methods :)

**Comment by davidkline-ms** [comment]
#3190 is related to this

**Comment by Yoyozilla** [comment]
covered by #3329
