### ISSUE TITLE
Error while importing HoloToolkit-Unity-2017.4.2.0 on Unity 2018.1.6f1 Personal

### ISSUE THREAD

**Issue by ankursahu19** [microsoft/MixedRealityToolkit-Unity#3182]
While importing HoloToolkit-Unity-2017.4.2.0 on Unity (**Version 2018.1.6f1 (57cc34175ccf) Personal
Branch: 2018.1/release**)
PS: This unity installed by Visual studio itself.

**To Reproduce**
1.Open **Unity** and Go to Assets -> Import Packages 
2. Click on Custom Packages... and select **HoloToolkit-Unity-2017.4.2.0.unitypackage**
3. and after that click on import.
4. After import done , following error and warning occurs.
5. Also clicking on **Apply Mixed Reality Project Settings** will not update anything. 

- **Error is**
     **System.Exception: Package directory not found: "C:\Users\xyz\\.nuget\packages\Microsoft.CSharp\4.0.1".
  at UnityEditor.Scripting.Compilers.NuGetPackageResolver.Resolve () [0x000dd] in <3f368bacb6c34f4db5fe7e90570f303a>:0**

- **Warning are**
       * **Model 'Cursor_cross_root' contains animation clip 'Cursor_Cross_Hold_GestureFOV_root' which has length of 0 frames (start=132, end=132). It will result in empty animation.**
       * **Model 'Cursor_cross_root' contains animation clip 'Cursor_Cross_GestureFOV_off_root' which has length of 0 frames (start=132, end=132). It will result in empty animation**
       * **Model 'Cursor_cross_root' contains animation clip 'Cursor' which has length of 0 frames (start=1, end=1). It will result in empty animation.**
       * **Model 'CursorRing' contains animation clip 'Cursor' which has length of 0 frames (start=5, end=5). It will result in empty animation.**

Please help!

**Comment by isurfraz** [comment]
You dont have the correct C# runtimes installed, make sure you have .NET 4.6 installed and switch to it in editor via player settings

**Comment by StephenHodgson** [comment]
Interesting that you'd get this error. I don't think the HTK has any .net 4.6 language features in the code base.

could you give the whole stack trace of this error and see who's calling it?

The warnings can be safely dismissed.

**Comment by ankursahu19** [comment]
Hello @StephenHodgson , 
 Thank you for reply. 

I am following [your video](https://www.youtube.com/watch?v=34kkoMEkijI) in order to develop Hololens application. It was working and able to deploy on hololens emulator also, but from last three days when i was trying to import hololens toolkit in unity project always found the above mention error.

**PS**: I have update Unity to latest version.
Also tried on Fresh Virtual Machine but same mentions error. 
VM details are OS : Windows 10 Enterprises 1803 17134.285
Unity Version: 2017.4.12f1 Personal
HoloToolkit 2017.4.2.0
Visual Studio 2017 

**Before import HoloToolkit** 

![capture](https://user-images.githubusercontent.com/3880940/48937357-d6263980-ef33-11e8-93e1-759ed4268635.PNG)

**After import completed**
![capture2](https://user-images.githubusercontent.com/3880940/48937468-34ebb300-ef34-11e8-9227-735724c70df5.PNG)

and also nothing happens when clicking on Mixed Reality Toolkit ->Configure-> Apply Mixed Reality Project Settings .

Please suggest me any workaround
Thank you!

**Comment by StephenHodgson** [comment]
Still need the stack trace to fix

**Comment by ankursahu19** [comment]
I have just download Visual studio 2017 with following selection, 

- Windows Universal Platform development 

- .Net Desktop Development

- Desktop Development with C++

- Game Development Unity (and also with Unity Editor )

After installation completed then download Holo-Toolkit and import in unity as custom package and above mention error occurs.

**Comment by Yoyozilla** [comment]
closing older HTK issues as we are no longer updating HTK
