### ISSUE TITLE
Linux standalone sharedassets are corrupted

### ISSUE THREAD

**Issue by wassx** [Microsoft/MixedRealityToolkit-Unity#3183]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
Building a minimal scene for linux standalone with build target Linux64.
In the scene (and project) there is just a mixedrealityplayspace with a camera (tagged) and the mrtk.
Everything compiles and looks fine.
When starting the standalone app (in my case done in a docker container) the Player.log is filled with
```
Initialize engine version: 2018.2.16f1 (39a4ac3d51f6)
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
FMOD initialized on nosound output
Begin MonoManager ReloadAssembly
- Completed reload, in  0.038 seconds
The file '/files/holox_Data/sharedassets0.assets' is corrupted! Remove it and launch unity again!
[Position out of bounds!]

(Filename:  Line: 221)
```

This error messages spams the log.
Cleaning the build folder, library,... did not work.
**This error occurs every 95% of builds/launches.**

Please see attached project.

**Unity Editor Version**
2018.2.16f1

**Mixed Reality Toolkit Release Version**
mrtk_development 
https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/49f5c4c22b66a7e2c212f15b982056dcb31ff4cd
22.11.2018

**Comment by StephenHodgson** [comment]
Thanks for the report.

Could you try going back a few commits and see when this was introduced?

Have you also been able to reproduce this for other platforms like windows or osx?

**Comment by wassx** [comment]
I tried with a version shortly after vnext_beta, same issue. Can only reproduce with linux64. Will try to step back and find latest working version.

**Comment by StephenHodgson** [comment]
Much appreciated.

**Comment by wassx** [comment]
Oh man that was quite some digging. Dating back to 27.10.2018
PR https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/7eca8c5e668f4abc2162e28bfdfed051fd2a6cb6 still works.
The issue occurs with: https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/5d2f3064448941de761fa5fd3c326e8cdd1cd98f
Maybe the Microsoft.MixedReality.Toolkit.Core.Utilities.Editor.Setup.dll?

**Comment by StephenHodgson** [comment]
Hmm that's odd. It's just an editor dll. Shouldn't get into the build at all.

**Comment by wassx** [comment]
I removed the dll (see attached patch for latest mrtk_dev) and now it builds and runs without these sharedassets exceptions.
[Removal_of_editor_setup_dll.zip](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/2610814/Removal_of_editor_setup_dll.zip)

**Comment by StephenHodgson** [comment]
@wassx were you also using a headless build process for linux?

**Comment by wassx** [comment]
@StephenHodgson Hi sorry for late reply, notifications didn't went through. Yes, always started a headless linux.

**Comment by davidkline-ms** [comment]
This is likely fixed as we no longer use a precompiled editor setup dll
