### ISSUE TITLE
Scene XboxControllerExample from HoloToolkit-Unity-Examples does not work. No input from the controller is received.

### ISSUE THREAD

**Issue by GeraldSchmitt** [microsoft/MixedRealityToolkit-Unity#3184]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit

**Describe the bug**
The XBox One Controller connection/deconnection is detected, but no event is triggered/transmitted when a button is pressed.

**To Reproduce**
1. Open the scene **XboxControllerExample** from **HoloToolkit-Unity-Examples-2017.4.2.0**
2. Deploy to a Hololens, and start the app.
3. The app displays the message "No controller connnected".
4. Connect a XBox One Controller to the Hololens.
5. The app displays the id of the controller, and the state of the various buttons.
6. Play with the controller buttons.
7. Nothing happens, the displayed state of the buttons stays the same, the cube does not move.

**Expected behavior**
The cube should move, the state of the buttons should be updated when pressed.

**Actual behavior**
No button pressed event  is transmitted, nothing happens when pressing the buttons. The cube does not move.

**Unity Editor Version**
2017.4.15f1
2017.4.5f1

**Mixed Reality Toolkit Release Version**
HoloToolkit-Unity-2017.4.2.0
HoloToolkit-Unity-Examples-2017.4.2.0

**Additional context**
It may be linked with the issue  #3130 
The Xbox Controller is correctly connected to the Hololens, as I can use it normally in the hub.
I can even exit the app and go to the hub by pressing the  "Xbox logo" button.

**Comment by keveleigh** [comment]
In the past, I've sometimes seen issues like this resolve themselves after a firmware update to the controller. Can you please try that and report back?

https://support.xbox.com/en-US/xbox-on-windows/accessories/how-to-update-xbox-one-controller-windows-10

**Comment by kwmeyer** [comment]
I am seeing the exact same issue; the controller connection is detected, but button and joystick input is not. I am also seeing this behavior in other applications as well, not just this example. My software and firmware is all up to date.

Unity Editor Version: 2017.4.19f1
HoloToolkit/Examples Release: 2017.4.3.0
Controller Firmware 3.1.1221.0
Hololens OS 10.0.17763.134

**Comment by pr0gg3r** [comment]
Same problem here...

**Comment by Yoyozilla** [comment]
Closing older HTK issue as we are no longer actively working on HTK.

Please upgrade to MRTK V2 for the latest fixes.
