### ISSUE TITLE
InteractionManager.SourcePressed is obsolete while InteractionManager.InteractionSourcePressed doesn't work as well

### ISSUE THREAD

**Issue by tazdriver** [Microsoft/MixedRealityToolkit-Unity#3191]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Unity editor version:**
Unity 2018.1.6f1

**Describe the bug**
While using HUX toolkit in Unity project, I have faced an error in InteractionManager.cs:

```Assets/Extern/MRDesignLab/HUX/Scripts/Interaction/InteractionManager.cs(131,57): error CS0619: `UnityEngine.XR.WSA.Input.InteractionManager.SourcePressed' is obsolete: `SourcePressed is deprecated, and will be removed in a future release. Use InteractionSourcePressed instead. (UnityUpgradable) -> InteractionSourcePressedLegacy'```

As I change from 'SourcePressed' to 'InteractionSourcePressed' it gives me:

```Assets/Extern/MRDesignLab/HUX/Scripts/Interaction/InteractionManager.cs(131,57): error CS0123: A method or delegate HUX.Interaction.InteractionManager.InteractionManager_SourcePressedCallback(UnityEngine.XR.WSA.Input.InteractionSourceState)' parameters do not match delegate `System.Action<UnityEngine.XR.WSA.Input.InteractionSourcePressedEventArgs>(UnityEngine.XR.WSA.Input.InteractionSourcePressedEventArgs)' parameters```

**Comment by tazdriver** [comment]
Also, even it says "(UnityUpgradable) -> InteractionSourceReleasedLegacy", API Updater doen't provide any possible solution/fix.

**Comment by SimonDarksideJ** [comment]
The InteractionManager is not part of the Toolkit, as noted by the namespace path:
> UnityEngine.XR.WSA.Input.InteractionManager

This is a Unity issue and should be logged on the Unity forums.
