### ISSUE TITLE
Microsoft.MixedReality.Toolkit.Core.Utilities.Editor.Setup.dll appears to cause app crash on startup

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#3193]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
Customer reported that if they build their application using the command line, the resulting application crashed on startup (see stack below). If they built their project from the editor, the issue did not manifest.

Upon investigation, it appears that removing Microsoft.MixedReality.Toolkit.Core.Utilities.Editor.Setup.dll eliminated the issue for command line builds.

**To Reproduce**
1. Import MRTK
2. Build app using Unity's command line
3. Launch the app.

**Expected behavior**
App to run regardless of build method.

**Actual behavior**
App crashes if built using Unity's command line.

**Stack Trace**
UnityPlayer.dll!DebugStringToFilePostprocessedStacktrace(struct DebugStringToFileData const &)    Unknown
UnityPlayer.dll!DebugStringToFile(struct DebugStringToFileData const &)    Unknown
UnityPlayer.dll!DebugStringToFile<class core::basic_string<char,class core::StringStorageDefault<char> > >(class core::basic_string<char,class core::StringStorageDefault<char> > const &,int,char const *,int,enum LogMessageFlags,int,int,void (*)(struct CppLogEntry const &))    Unknown
UnityPlayer.dll!CachedReader::OutOfBoundsError(unsigned int,unsigned int)    Unknown
UnityPlayer.dll!CachedReader::UpdateReadCache(void *,unsigned int)    Unknown
UnityPlayer.dll!CachedReader::Read<unsigned char>(unsigned char &)    Unknown
UnityPlayer.dll!StreamedBinaryRead<0>::TransferBasicData<unsigned char>(unsigned char &)    Unknown
UnityPlayer.dll!StreamedBinaryRead<0>::Transfer<unsigned char>(unsigned char &,char const *,enum TransferMetaFlags)    Unknown
UnityPlayer.dll!Transfer_Blittable_SingleValueField<class StreamedBinaryRead<0>,unsigned char>(class StreamedBinaryRead<0> &,class GeneralMonoObject &,struct StaticTransferFieldInfo const &)    Unknown
UnityPlayer.dll!Transfer_Blittable<class StreamedBinaryRead<0>,0,unsigned char>(struct SerializationCommandArguments const &,struct RuntimeSerializationCommandInfo &)    Unknown
UnityPlayer.dll!SerializationCommand::Execute(struct RuntimeSerializationCommandInfo &)    Unknown
UnityPlayer.dll!ExecuteSerializationCommands<class StreamedBinaryRead<0> >(struct SerializationCommandProvider &,class StreamedBinaryRead<0> &,class GeneralMonoObject const &)    Unknown
UnityPlayer.dll!ExecuteSerializationCommands<class StreamedBinaryRead<0> >(struct dynamic_array<struct SerializationCommand,0> const &,class StreamedBinaryRead<0> &,class GeneralMonoObject const &)    Unknown
UnityPlayer.dll!TransferScriptingObject<class StreamedBinaryRead<0> >(class StreamedBinaryRead<0> &,class ScriptingObjectPtr,class ScriptingClassPtr,struct MonoScriptCache const *)    Unknown
UnityPlayer.dll!MonoBehaviour::TransferEngineAndInstance<class StreamedBinaryRead<0> >(class StreamedBinaryRead<0> &)    Unknown
UnityPlayer.dll!MonoBehaviour::VirtualRedirectTransfer(class StreamedBinaryRead<0> &)    Unknown
UnityPlayer.dll!SerializedFile::ReadObject(__int64,enum ObjectCreationMode,bool,class TypeTree const * *,bool *,class Object &)    Unknown
UnityPlayer.dll!PersistentManager::ReadAndActivateObjectThreaded(int,struct SerializedObjectIdentifier const &,class SerializedFile *,bool,bool,enum PersistentManager::LockFlags)    Unknown
UnityPlayer.dll!PersistentManager::LoadFileCompletelyThreaded(class core::basic_string<char,class core::StringStorageDefault<char> > const &,__int64 *,int *,int,enum PersistentManager::LoadFlags,class LoadProgress &,enum PersistentManager::LockFlags)    Unknown
UnityPlayer.dll!LoadSceneOperation::Perform(void)    Unknown
UnityPlayer.dll!PreloadManager::ProcessSingleOperation(void)    Unknown
UnityPlayer.dll!PreloadManager::Run(void)    Unknown
UnityPlayer.dll!PreloadManager::Run(void *)    Unknown
UnityPlayer.dll!Thread::RunThreadWrapper(void *)    Unknown
kernel32.dll!@BaseThreadInitThunk@12�()    Unknown
ntdll.dll!77623814()    Unknown
[Frames below may be incorrect and/or missing, no symbols loaded for ntdll.dll]  
[External Code]  

**Unity Editor Version**
2018.1.9f2

**Mixed Reality Toolkit Release Version**
2018.9.0 (Beta)

**Comment by davidkline-ms** [comment]
closing as duplicate

**Comment by StephenHodgson** [comment]
What happens if you use the recommended editor version 2018.2.16f1?

**Comment by StephenHodgson** [comment]
> 2. Build app using Unity's command line

Sure this is a step, but _how_ do you do it? lol
