### ISSUE TITLE
How should the IP on the NetworkManager be set?

### ISSUE THREAD

**Issue by renfengyi** [microsoft/MixedRealityToolkit-Unity#3194]
## Steps to reproduce
_(Links to sample github project preferred)_

**Comment by renfengyi** [comment]
How should the IP on the NetworkManager be set?Why did I display the qr code on the iPad after I released it? I used two Hololens to scan the location of only one scene simultaneously?

**Comment by Yoyozilla** [comment]
Bulk closing older issues.

Also you can try asking the question on Slack Overflow with the mrtk tag. we have a bunch of active folks there helping :)
