### ISSUE TITLE
Multiple Input detected in a loop

### ISSUE THREAD

**Issue by achaperon** [Microsoft/MixedRealityToolkit-Unity#3195]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit VNext

**Describe the bug**

**To Reproduce**
https://github.com/achaperon/MRTK_Test
1. Open project and compile for HoloLens on IL2CPP
2. Launch the App
3. Make Airtap
4. Show the marker in front of the HoloLens and make Airtap at the same time

**Expected behavior**
Only one airtap should be detected per gesture

**Actual behavior**
Sometimes, just showing the marker trigger OnInputDown with the "select" Input Action
When the marker is in front of the HoloLens and you make the "ready" gesture. Multiple Airtap are detected (1 per update).
Actually, at each Update we have OnInputDown and OnInputUp with the "select" Input Action. 

**Unity Editor Version**
2018.2.10

**Mixed Reality Toolkit Release Version**
Beta Release 2018.9 MRTK VNext

**Additional context**

**Comment by StephenHodgson** [comment]
Thanks for the report

**Comment by keveleigh** [comment]
Should be fixed with #3293. Please report back and reopen if not.
