### ISSUE TITLE
Create test scene for SpatialSound\UAudioManager

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#32]
based on Holograms-220 from the HolographicAcademy

**Comment by rhenninger** [comment]
Hey David, I see this has been around a while.  I would have found this and some wiki info on UAudioManager helpful in getting up to speed on best practices in creating hololens sounds. The 220 tutorial was an ok alternative for verifying intended usage, but no substitute for conceptual guidance. As I walk the code, I am happy to help expedite getting tests done or at least flesh out the wiki. Are you the main guardian for this branch of the Toolkit?
Richard

**Comment by davidkline-ms** [comment]
Thanks for reminding me of this one, Richard.  We should have a test scene based on the 220 course added in the near future.

David

**Comment by NeerajW** [comment]
>>The 220 tutorial was an ok alternative for verifying intended usage, but no substitute for conceptual guidance.

@davidkline-ms and @joekellyms  will you be adding more conceptual guidance for these components in perhaps the wiki section?

**Comment by joekellyms** [comment]
Yes, I am working out the wiki details now. @rhenninger if there are any specific questions, please let me know!

**Comment by rhenninger** [comment]
@joekellyms Thanks for asking.  I think the biggest question at the outset is why the toolkit’s spatial audio scripts are worth using.
 
                I’d start with the rationale for using the UAudioManager over just putting AudioClips on AudioSources on objects and setting the SpatialSound’s manually for each one.  I’d indicate what AudioEvents are and how they can group multiple AudioClips for playback randomly, sequentially or simultaneously.  I’d present the architectural advantages of separating these collections of sounds (AudioEvents) from specific AudioSources on a particular GameObject. Also, how the Unity Mixer can be used in conjunction with AudioEvents.
 
                These are all things I gleaned from walking the code in the context of 220, but it would have been nice to have had this in advance when I did the exercise rather than having to figure it out like a mystery novel as I went along.  Not everyone has my patience, intense interest in audio or architectural background sufficient to figure this out on their own.
 
                Since sound designers think in terms of the sounds themselves, I’d emphasize the possibilities offered by grouping and controlling audio assets separate from AudioSources as AudioEvents.  Then I’d have “how-to” pages on setting up the UAudioManager by constructing AudioEvents from those assets going over the pros and cons of various options.
 
                I’d finish up with how to create GameObjects with empty AudioSources and how to have objects or other scripts trigger AudioEvents based upon things that happen to a GameObject – that is, strategies for making objects aware of the AudioEvents that are available of the event names they might use.  The 220 scripts for SurroundController and SurroundEmitter make a nice simple example of how to do this as well as show off the basic value of separating the AudioEvents from a GameObject’s AudioSources.
 
                Hope this helps.
 
                Richard

**Comment by joekellyms** [comment]
@rhenninger This is fantastic feedback - working on the page now, thanks!

**Comment by jwittner** [comment]
@davidkline-ms @joekellyms Was any progress made on this?

**Comment by NeerajW** [comment]
@davidkline-ms @joekellyms  do we still need this?

**Comment by HodgsonSDAS** [comment]
Any update on this?

**Comment by davidkline-ms** [comment]
@joekellyms, I'll assign this one to you. :)
