### ISSUE TITLE
Mixed Reality Headset can't catch the handshank event in UWP Project

### ISSUE THREAD

**Issue by Emerson92** [microsoft/MixedRealityToolkit-Unity#3211]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
 Mixed Reality Toolkit(master)

**Describe the bug**
I am export the example of  "MotionControllerTest Scene" to UWP Project and run this project , i find the demo about MotionControll can not catch the data event about Handshank (both right and left) such as TrggierEvent 、GraspEvent and so on. But When I shut the handshank down and restart it, it works fun.so I check the code of "DebugPanelControllerInfo.CS" and find the issue. I can not get those event because the function "InteractionManager_InteractionSourceDetected(InteractionSourceDetectedEventArgs obj)" does not excution when the first time the HandShank Loaded. And In the funciton "InteractionManager_InteractionSourceUpdated(InteractionSourceUpdatedEventArgs obj)" the Dictionary of controllers has not the info about the handshank so that it can not catch the event data in this function. i will appreciate it if someone can give me some help about this problem.

**To Reproduce**
1. Go to 'HoloToolkit-Examples/Input/Scenes/MotionControllerTest' Scene, and export this Scene into UWP Project. 

**Screenshots**
![update](https://user-images.githubusercontent.com/13955075/49414906-e8b03680-f7af-11e8-8ab3-717b9ed65f78.png)

**Unity Editor Version**
Unity 2017.4.13f1 (64-bit)

**Mixed Reality Toolkit Release Version**
master

**Additional context**
this first time lanuch the demo:
![handproblem](https://user-images.githubusercontent.com/13955075/49414554-cb2e9d00-f7ae-11e8-91cb-2a02f0c13566.gif)
after restart the handshank:
![handrestartclip](https://user-images.githubusercontent.com/13955075/49415909-1a76cc80-f7b3-11e8-8660-96a1a9540063.gif)

**Comment by Yoyozilla** [comment]
Bulk closing older issues. 
Please reopen if it still repros with the latest Unity 2018 + MRTK release
