### ISSUE TITLE
Does HoloToolkit 2017.4.3.0 use Gaze Stabilizer?

### ISSUE THREAD

**Issue by Ariel-Feldman** [microsoft/MixedRealityToolkit-Unity#3212]
HoloToolkit 2017.4.3.0

**Describe the bug**
The input manager object has Gaze Stabilizer component, but it looks like the Gaze Manager not using it... the is no reference for it inside the script.
is it supposed to be this way?

**Screenshots**
![image](https://user-images.githubusercontent.com/37870528/49433493-df789700-f7ba-11e8-861c-e70353dd4e03.png)

**Comment by keveleigh** [comment]
The gaze stabilizer is used here: https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/Gaze/GazeManager.cs#L198

**Comment by chbecker-ms** [comment]
Answered! Further questions?

https://stackoverflow.com/questions/tagged/mrtk
