### ISSUE TITLE
Customer Feedback: Profile inspector views would benefit from being collapsable.

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#3215]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

Recent customer feedback compared the Unity Hierarchy, Inspector and Project views to the MRTK profile view in the inspector and pointed out how it can be helpful to enable collapsing of portions of the view to allow focus on specific aspects.

The feedback proposes enabling a user to collapse specific areas (ex: in the Spatial Awareness Profile, enable collapsing by General, Mesh and Surface Finding areas). This same concept would extend to all other profiles.

**Screenshots**
Project view (with ability to collapse / expand as desired)
![capture](https://user-images.githubusercontent.com/13281406/49467746-fd90c800-f7b7-11e8-8b4a-62ecc99a6fe7.PNG)

Profile Inspector (does not allow collapse / expand)
![capture1](https://user-images.githubusercontent.com/13281406/49467776-0da8a780-f7b8-11e8-8a4c-af99f80357e7.PNG)

**Comment by danielescudero** [comment]
Thanks for this! Easy navigation of profiles and nested profiles helps understand relationships and where to find them. Lets make sure devs can easily glance at that hierarchy :)

**Comment by StephenHodgson** [comment]
The spatial observer data providers will likely get a most of this UI in the future. But I agree. anything longer than half an inspector height should be a foldout.
