### ISSUE TITLE
[Beta] vNext UI events do not propagate the same as vanilla Unity 

### ISSUE THREAD

**Issue by phosphoer** [Microsoft/MixedRealityToolkit-Unity#3216]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit vNext

**Describe the bug**
In vanilla Unity UI with the Standard Input Module + mouse input, a pointer enter event will propagate up the hierarchy such that if you have a Button who's target graphic is a child, the button will respond to the child graphic being hovered. 

When using a pointer input from the MRTK such as the GazeProvider, this is not the case, and pointer enters on child graphics of buttons are ignored. Something about the way the input is handled requires that the Button target graphic be on the same game object, which is likely incompatible with a lot of existing UI hierarchies in projects today. 

**To Reproduce**
[Repro project](https://github.com/phosphoer/repro-mrtk-ui-events)
1. Download the repro unity project and open it with latest Unity 2018
2. Open Scenes/unity-ui and hit play
3. Verify that mouse hovering both buttons produces a highlight effect
4. Open Scenes/mrtk-unity-ui and hit play, the gaze camera should start panning left and right
5. Observe that the button using a child graphic is not highlighted, but the sibling one is

**Expected behavior**
Both buttons are highlighted by the gaze provider

**Actual behavior**
Only buttons with sibling graphics are highlighted by gaze

**Unity Editor Version**
2018.2.14f1

**Mixed Reality Toolkit Release Version**
vNext development beta

**Comment by StephenHodgson** [comment]
I think this might have more to do with the raycast order than event propagation, but I could be mistaken.
I also need to port the raycasting/graphic raycasting unit tests over from HTK as well.

**Comment by StephenHodgson** [comment]
> I'm a bit curious about the design of keeping the StandaloneInputModule in conjunction with your input system. If you are sending pointer enter/exit events yourself, which is also the job of the InputModule, how do you avoid conflicting with it? You'll constantly be receiving normal mouse input in the editor and in builds regardless of any configuration in MRTK, no?

Seems like a separate issue/proposal. I remember there being really good reasons for this (I think updating an existing project was one of them) but I can't think of all of them off the top of my head.
