### ISSUE TITLE
Proposal: Add flag to enable AR/VR specific debugging in Unity Editor

### ISSUE THREAD

**Issue by FireDragonGameStudio** [microsoft/MixedRealityToolkit-Unity#3222]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Is your feature request related to a problem? Please describe.**
When creating appications for MR it's often necessary to implement different features in AR and VR. An example for this would be marker tracking for AR, which is not needed in VR. Within the application it's possible to distinguish between ```MixedRealityToolkit.Instance.ActiveProfile.CameraProfile.IsOpaque```, but this flag is always true within Unity Editor and makes it very hard to test.

**Describe the solution you'd like**
A flag (maybe in CameraProfile) to switch between AR and VR in editor, which affects ```MixedRealityToolkit.Instance.ActiveProfile.CameraProfile.IsOpaque```.

**Describe alternatives you've considered**
Currently VR devices are connected via cable and can be detected within the Unity Editor with ```XRSettings.isDeviceActive``` e.g. 
```
public bool IsVrActive =>
#if UNITY_EDITOR && UNITY_WSA
    XRSettings.isDeviceActive;
#else
    MixedRealityToolkit.Instance.ActiveProfile.CameraProfile.IsOpaque;
#endif
```
But when having autonomous devices like Oculus Quest this check will become obsolete.

**Comment by FireDragonGameStudio** [comment]
As this was mentioned in the HoloDevelopers Slack channel, I'd like to post the solution for this here as well. (Thx Dino) 

In Unity go to Window -> XR -> Holographic Emulation. Then in that window set "Emulation Mode" to "Simulate in Editor". You can even choose a room for the spatial mapping simulation. When you hit play now `MixedRealityToolkit.Instance.ActiveProfile.CameraProfile.IsOpaque` will be false and you can test in editor transparent display behaviour.

**Comment by davidkline-ms** [comment]
add proposal tag, we should investigate feasibility of adding a camera profile override that sets the correct platform specific setting

**Comment by Troy-Ferrell** [comment]
This is resolved via `MixedRealityCameraSystem.IsOpaque`. Closing out item
