### ISSUE TITLE
EditorUtility.FocusProjectWindow() throws an Exception

### ISSUE THREAD

**Issue by Jarodshow** [Microsoft/MixedRealityToolkit-Unity#3225]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
Whenever any of add profile buttons are selected, it throws an error along with creating the new profile.

**To Reproduce**
1. Create new scene
2. Go to the DefaultMixedRealityToolkitConfigurationProfile asset and select "Create new profiles"
3. Select any of the add profile buttons to see the error.
[Stack Trace](https://gist.github.com/Jarodshow/8bc315f378b453146ad0f528ec3cb82b)

**Expected behavior**
No error being thrown and a new profile being created.

**Actual behavior**
A new profile being created but an error being thrown.

**Unity Editor Version**
2018.2.16f1

**Mixed Reality Toolkit Release Version**
latest mrtk_development

**Additional context**
The underlying problem is that a TargetInvocationException is being thrown on FocusProjectWindow(), if this line is commented out, the exception goes away.

![scriptableobjecterror](https://user-images.githubusercontent.com/9560490/49486453-22129180-f804-11e8-80a4-a475f74bcc45.png)

[Stack Trace](https://gist.github.com/Jarodshow/38366a1df8ff1ddc9663121e72b73e4a)

**Comment by StephenHodgson** [comment]
Thanks for the report.
