### ISSUE TITLE
NullReferenceExpection in BaseSpatialObserver.CleanupMeshObject on Hololens

### ISSUE THREAD

**Issue by wassx** [Microsoft/MixedRealityToolkit-Unity#3226]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
We added the spatial awareness system to visualize the room mesh. It works as expected on the hololens, but in the log I receive lots of NullReferenceExceptions in a very short timespan (see screenshot).

![image](https://user-images.githubusercontent.com/3955210/49523400-ffd34f00-f8a9-11e8-96a2-ddfaf3093e5c.png)

**To Reproduce**
The setup of the configuration profile looks like this:
![image](https://user-images.githubusercontent.com/3955210/49523587-622c4f80-f8aa-11e8-98ae-cd6218be266c.png)

So it is initially active and will be set programatically to hidden by using following code, but as far as I found out this switch is not relevant as the error occurs on the InvokeSurfaceDataReadyEvent (see stacktrace):

    private void SetSpatialMeshPulseVisible(bool visible) {
        bool isOpaque = MixedRealityToolkit.Instance.ActiveProfile.CameraProfile.IsOpaque;
        SpatialMeshDisplayOptions displayOptions = visible && !isOpaque ? SpatialMeshDisplayOptions.Visible : SpatialMeshDisplayOptions.None;
        MixedRealityToolkit.Instance.GetService<IMixedRealitySpatialAwarenessSystem>().MeshDisplayOption =
                displayOptions;
    }

**Unity Editor Version**
2018.2.17f1

**Mixed Reality Toolkit Release Version**
mrtk_development 49f5c4c22b66a7e2c212f15b982056dcb31ff4cd

**Comment by StephenHodgson** [comment]
Thanks for the report

**Comment by davidkline-ms** [comment]
this should be addressed in #3399
