### ISSUE TITLE
GLTF Can't load it

### ISSUE THREAD

**Issue by kknsy** [microsoft/MixedRealityToolkit-Unity#3231]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit | Mixed Reality Toolkit

**Describe the bug**
HoloToolkit doesn't work with the latest UnityGLTF due to API breaking changes

**To Reproduce**
_(Links to sample GitHub project preferred)_
Import HoloToolkit-Unity-2017.4.3.0.unitypackage
![image](https://user-images.githubusercontent.com/26211860/49556771-48d5e280-f940-11e8-9272-29fd6501fee9.png)
![image](https://user-images.githubusercontent.com/26211860/49556813-699e3800-f940-11e8-9dab-ea47b7bde402.png)
I blocked the code.
![image](https://user-images.githubusercontent.com/26211860/49556823-791d8100-f940-11e8-90ac-e6872b5a314f.png)
No problem with build and deployment，But it is not loaded in HoloLens
![image](https://user-images.githubusercontent.com/26211860/49556855-8f2b4180-f940-11e8-8864-a13f243728ad.png)
![image](https://user-images.githubusercontent.com/26211860/49556861-95b9b900-f940-11e8-9311-abba88898668.png)

**Expected behavior**

 it can loaded in HoloLens

**Actual behavior**
A clear and concise description of what happens instead.

**Screenshots**

![image](https://user-images.githubusercontent.com/26211860/49557057-4e7ff800-f941-11e8-8e43-8878eb9903bd.png)

**Unity Editor Version**
Which Unity version(s) you've been able to reproduce the bug in.

**Mixed Reality Toolkit Release Version**
Which MRTK version(s) you've been able to reproduce the bug in.

**Additional context**

**Comment by StephenHodgson** [comment]
@Yoyozilla this has nothing to do with vNEXT

**Comment by Yoyozilla** [comment]
Closing older HTK issue as we are no longer actively working on HTK.

Please upgrade to MRTK V2 for the latest fixes.
