### ISSUE TITLE
Diagnostics System crashes HoloLens application on start

### ISSUE THREAD

**Issue by FejZa** [Microsoft/MixedRealityToolkit-Unity#3245]
## Overview
When using the latest mrtk_development state ov vNext having the Diagnostics System enabled and visible will crash the application on start when deployed to HoloLens.

## Expected Behavior
Diagnostics System is enabled and probably should be visible in the top left corner of the HoloLens FOV

## Actual Behavior
Application crashes on start right after Made With Untiy splashscreen.

## Steps to reproduce
- Import the latest vNext state
- Target UWP
- Configure Diagnostics System enabled and visible
- Configure the scene for MRTK
- Build and deploy to HoloLens

## Unity Editor Version
2018.3.0b12

## Mixed Reality Toolkit Release Version
mrtk_development branch

**Comment by StephenHodgson** [comment]
Do you have a stack trace of the crash?

**Comment by FejZa** [comment]
>	GameAssembly.dll!il2cpp::icalls::System::Microsoft::Win32::NativeMethods::GetProcessTimes(int handle, __int64 * creation, __int64 * exit, __int64 * kernel, __int64 * user) Line 30	C++

 	GameAssembly.dll!NativeMethods_GetProcessTimes_mFF1FA0FF468CE0698346FB025408FE4661F5F779(int ___handle0, __int64 * ___creation1, __int64 * ___exit2, __int64 * ___kernel3, __int64 * ___user4, const MethodInfo * method) Line 15064	C++

 	GameAssembly.dll!NativeMethods_GetProcessTimes_mCAB6B28520672C332F9250F565B1178788F8BF64(SafeProcessHandle_tEF75BF77F5F4E121334E2A97EE8E1F6685F38CF7 * ___handle0, __int64 * ___creation1, __int64 * ___exit2, __int64 * ___kernel3, __int64 * ___user4, const MethodInfo * method) Line 15094	C++

 	GameAssembly.dll!Process_GetProcessTimes_mAEE0C477ECD21E85F86EA92ED23C46A1007C5705(Process_t7F28AE318E6CCF89716D05E78E2CBD669767D6A1 * __this, const MethodInfo * method) Line 29835	C++

 	GameAssembly.dll!Process_get_TotalProcessorTime_mE9B83B34CBD1CA8217CE045CA1457D327BC5833A(Process_t7F28AE318E6CCF89716D05E78E2CBD669767D6A1 * __this, const MethodInfo * method) Line 29949	C++

 	GameAssembly.dll!CpuUseTracker_get_CurrentReadingInMs_m8AB075D7600BAA883FF56A22CB1A86C1D65AC1F5(CpuUseTracker_t5EDC3149F2EC745D9F02E83025ADF52DF5136F4E * __this, const MethodInfo * method) Line 19620	C++

 	GameAssembly.dll!DiagnosticsHandler_Update_m20155A96801B2850E85013C46538D5985A1FFCF9(DiagnosticsHandler_tBCD4A28503E79FCBC0B20602F1E48B67AEE7317F * __this, const MethodInfo * method) Line 19308	C++

 	GameAssembly.dll!RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017(void(*)() methodPointer, const MethodInfo * methodMetadata, void * obj, void * * args) Line 34280	C++

 	GameAssembly.dll!il2cpp::vm::Runtime::Invoke(const MethodInfo * method, void * obj, void * * params, Il2CppException * * exc) Line 531	C++

 	GameAssembly.dll!il2cpp_runtime_invoke(const MethodInfo * method, void * obj, void * * params, Il2CppException * * exc) Line 973	C++

**Comment by FejZa** [comment]
Not sure if that helps, sorry. From what I can se the DiagnosticsHandler.cs Update method is invoked. Weirdly enough the exception message says "{ProjectName}.exe has triggered a breakpoint"

**Comment by StephenHodgson** [comment]
Seems to be not implemented by Unity 

```
`IL2CPP_NOT_IMPLEMENTED_ICALL(NativeMethods::GetProcessTimes);`
```

**Comment by FejZa** [comment]
Ugh. Probably should've seen that myself. Still trying to become friends with IL2CPP debugging. Glad you found the issue right away.

**Comment by StephenHodgson** [comment]
Doesn't help that there's and error looking up the error string as well lol

```
'MixedRealityToolkit.exe' (Win32): Unloaded 'C:\Windows\System32\Windows.Shell.ServiceHostBuilder.dll'
'MixedRealityToolkit.exe' (Win32): Unloaded 'C:\Windows\System32\execmodelproxy.dll'
'MixedRealityToolkit.exe' (Win32): Unloaded 'C:\Windows\System32\biwinrt.dll'
'MixedRealityToolkit.exe' (Win32): Unloaded 'C:\Windows\System32\Clipc.dll'
'MixedRealityToolkit.exe' (Win32): Unloaded 'C:\Windows\System32\Windows.Devices.Sensors.dll'
'MixedRealityToolkit.exe' (Win32): Unloaded 'C:\Windows\System32\Windows.System.Profile.SystemId.dll'
Exception thrown at 0x7735F2B2 in MixedRealityToolkit.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x025DEA5C.
'MixedRealityToolkit.exe' (Win32): Unloaded 'C:\Windows\System32\bcd.dll'
Exception thrown at 0x7735F2B2 in MixedRealityToolkit.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x025DEA5C.
'MixedRealityToolkit.exe' (Win32): Unloaded 'C:\Windows\System32\FlightSettings.dll'
'MixedRealityToolkit.exe' (Win32): Unloaded 'C:\Windows\System32\OneCoreCommonProxyStub.dll'
'MixedRealityToolkit.exe' (Win32): Unloaded 'C:\Windows\System32\Windows.ApplicationModel.dll'
Error looking up error string
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.SDK.DiagnosticsSystem.DiagnosticsHandler:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

_CRT_ASSERT caught:
'''C:\Valorem Projects\External\MixedRealityToolkit-Unity\Builds\UWP\Il2CppOutputProject\IL2CPP\libil2cpp\icalls\System\Microsoft.Win32\NativeMethods.cpp(30) : Assertion failed: 0 && "NativeMethods::GetProcessTimes"
'''
```
