### ISSUE TITLE
MissingReferenceException with non-persistent camera and multi-scene setup

### ISSUE THREAD

**Issue by FejZa** [Microsoft/MixedRealityToolkit-Unity#3246]
## Overview
In a project with two scenes A and B. Loading scene B will lead to a missing reference exception when using a non-persistent camera configuration.

## Expected Behavior
When loading scene B the new "MixedRealityPlayspace" game object takes over. The "MixedRealityToolkit" game object is persistent and thus will exist in scene B.

## Actual Behavior
"MixedRealityToolkit" exists in scene B but throws some missing reference exception. It seems they are related to cursors somehow. Couldn't find out yet how and why.

## Steps to reproduce
[Example project](https://github.com/FejZa/MRTK-multiscene-issue)

## Unity Editor Version
2018.3.0f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by StephenHodgson** [comment]
Thanks for the report. I'll look into this as soon as possible.

**Comment by StephenHodgson** [comment]
@FejZa I noticed that you were not async loading the next scene. The MRTK only supports having a base scene and additive loading in the next scene.

I'll open a PR on your example project to show the appropropriate usage to the toolkit in multi scene projects.

**Comment by StephenHodgson** [comment]
See https://github.com/FejZa/MRTK-multiscene-issue/pull/1

**Comment by FejZa** [comment]
@StephenHodgson thank you. I am aware of that. I just kept the example simple. 

Actually whenever I can, I do additive loading. In the current case, I am using the UNET NetworkLobbyManager which uses a "Lobby" and "Game" scene. And at some pont it will do a full scene load to the Game scene. No way for me to change that behaviour. But probably I am going to dump UNET soon so I can live with that.

But to be honest, then I don't get the point of the "persist" flag for the camera in MRTK. Flaging the Camera root DontDestroyOnLoad will not do anything if there will never be a scene transition. Or am I missing something here?

**Comment by StephenHodgson** [comment]
It's mainly to support the uNET case as well. (Yeah it's super frustrating that Unity doesn't even take it's own advice about additively loading scenes with the network manager).

**Comment by StephenHodgson** [comment]
I was working with @wassx to support mrtk with uNET. He might have some best practices there.

**Comment by StephenHodgson** [comment]
I'm actually half tempted to remove that flag altogether to clear up any confusion.

**Comment by FejZa** [comment]
Yes. Let's hope they will do it better with the new networking framework. Thanks for clarifying this.
