### ISSUE TITLE
Some controllers don't send input events on each frame if input is active.

### ISSUE THREAD

**Issue by StephenHodgson** [microsoft/MixedRealityToolkit-Unity#3253]
## Overview
As I was trying to implement an example demo, I realized that input events didn't seem to be sent consistently. 

Looking into a few of the controller classes I realized that we only send input events if the data has changed, but that doesn't mean we always send events for things like continuous button presses or joystick data.

## Expected Behavior
Input events should be raised whenever data is availible and not at the considered "default" state. For example, a Joystick is pushed forward to 1, 0 should raise an event every frame saying that's what the current position of the joystick is from 0, 0 through 1, 0 and continue to raise events while the position is at 1, 0.

## Actual Behavior
Input events are only raised when the data has changed, so we only ever get a single event that the joystick position changed from 0 through 1, but once it's at 1, 0 all events stop.

This would sometimes cause things to "Spring Back" to their initial position.

**Comment by luis-valverde-ms** [comment]
Reopening this as it is still an issue when for example trying to drive a rotation using a thumbstick. Once the thumbstick is pressed all the way its value won't change, events won't be raised and the rotation will stop.
