### ISSUE TITLE
Is the Input Action Rules Profile mandatory?

### ISSUE THREAD

**Issue by krishnan-unni** [Microsoft/MixedRealityToolkit-Unity#3260]
## Overview
Is the Input Action Rules Profile mandatory? I created a default scene and created customer profiles except Action Rules profile as I didnt want to override any of my base actions and tried to run the scene. It wont run since the Action Rule profile is missing. Is it mandatory? What if I dont need to override my actions? I can't even create a default action rules profile as it will force me to override atleast one base action. Is this the expected behavior going forward?

## Steps to reproduce
Add all profiles except Input Action Rules Profile and try to click play on a startup scene

## Unity Editor Version
Unity 2018.2.19f1

## Mixed Reality Toolkit Release Version
vNext -> mrtk_development branch

**Comment by StephenHodgson** [comment]
I'd suggest just using the default profile for the rules as it's empty as well.

**Comment by krishnan-unni** [comment]
You are right. :) Closing this.
