### ISSUE TITLE
Support multiple scenes - MRTK showing up in secondary scenes break the editor

### ISSUE THREAD

**Issue by grbury** [Microsoft/MixedRealityToolkit-Unity#3261]
## Overview
MRTK keeps trying to force itself into the scene.. does not work with a CoreSystems + Scene Loading model
## Expected Behavior
MRTK remains in the main scene

## Actual Behavior
Automatically manifests into secondary scenes and breaksdown

## Steps to reproduce
_(Links to sample github project preferred)_
Sorry - can't provide.

## Unity Editor Version
2018.2
## Mixed Reality Toolkit Release Version
vNext Beta

**Comment by StephenHodgson** [comment]
@grbury you'll need to provide some kinds of reproducible steps so I can guide you through the proper way to support multiple scenes with mrtk.

We've taken Unity's guidelines for this:

Have a base scene that starts the application, with the MRTK configured in that scene.

Then always additively load additional scenes into the main scene, but never unload the main scene.

Additional scenes shouldn't have the MRTK configured for it, but should contain the content.

**Comment by StephenHodgson** [comment]
See https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3246

**Comment by davidkline-ms** [comment]
Per a recent customer visit, this requirement limits how customers can implement their application.

Scenario:
* App has custom scene content (ex: camera rig) per supported platform
* At runtime, the appropriate scene / content is loaded
* Having the MixedRealityToolkit and camera rig enforced on every platform breaks their design and workflow

**Comment by StephenHodgson** [comment]
Then they should add their custom rig content onto it on startup like the MRTK does.

**Comment by StephenHodgson** [comment]
We're not preventing that kinda stuff.

The workflow isn't anything different than what Unity says.

- Make a base scene with all the shared assets (Like camera rigs, etc)
- Additively load in new scenes and never unload the base scene.

**Comment by StephenHodgson** [comment]
Again this is something that needs to be documented, and teached to people utilizing the toolkit.

**Comment by StephenHodgson** [comment]
[Here's a quote from the Unity Docs](https://docs.unity3d.com/Manual/MultiSceneEditing.html):

> Instead, create a manager scene that has all your managers and use SceneManager.LoadScene(<path>, LoadSceneMode.Additive) and SceneManager.UnloadScene to manage your game progress.

**Comment by Yoyozilla** [comment]
dupe
