### ISSUE TITLE
Unity UI Buttons do not work with WMR Motion Controllers

### ISSUE THREAD

**Issue by PhilippRaab** [Microsoft/MixedRealityToolkit-Unity#3262]
## Overview

The click event of the Unity UI buttons is not triggered with the WMR Motion Controllers. The button events with spatial mouse on the other hand are working correctly.

## Expected Behavior
Pressing the Trigger (Select) on the WMR Motion Controllers while pointing at a button should trigger the OnClick event.

## Actual Behavior
OnClick event is not triggered.

## Steps to reproduce

- Use scene and script in [MinimalUIButtonTest.zip](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/2671976/MinimalUIButtonTest.zip) with latest MRTK and standard profile. 
- Start project in Unity Editor.
- Click on the button with the spatial mouse. The Unity console logs "Click"
- Click on the button with a WMR Motion Controller. There is no console log.

## Unity Editor Version
2018.2.17f1

## Mixed Reality Toolkit Release Version
mrtk_development branch

**Comment by StephenHodgson** [comment]
Thanks for the report, I'll check it out as soon as I have time.

**Comment by StephenHodgson** [comment]
I'm not sure that we have it to set up to fire the "OnClick" event out of the box, you'll need to write an input handler wrapper that will forward the event to the ui button.

We're investigating ways to handle input without the wrapper (We have an interactions PR with a lot of the basic functionality in the works.)

**Comment by PhilippRaab** [comment]
Thank you for investigating. The spatial mouse works out of the box and what I understand raises the same events as the controllers. It would be nice when all input devices behave identical.

Could you provide a example of the input handler wrapper, to get a temporary workaround?

**Comment by wassx** [comment]
Tested with latest update form vnext (5f945d25514a87e4d072d894a6a9f90f1c909f31)
and now I get 1 click per pointer click. The important part was to add the pointer click handler and let the event handle by a buttonhandler class. The button itself has no events linked.
**ADDITIONALLY** I delete the camera, added a blank new camera and let vnext configure the mixedrealityplayspace. 
Now the pointer of the WMR works on UI Elements without a collider and triggers a single event on 'select'
Only thing is, that the ray of the controller disappears and the pointer seems to be a little bit off.
![image](https://user-images.githubusercontent.com/3955210/50182390-84dd5000-030f-11e9-9d7a-df4bd0e2aa9d.png)

I added a sample project which show this. But remember, as soon as I changed e.g. the event linking of the button itself, things got broken again.

[ButtonTest.zip](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/2692322/ButtonTest.zip)

**Comment by andriworld** [comment]
There is already code in `MixedRealityInputManager` that is trying to fire "OnClick" :

```
private static void ExecutePointerUp(GraphicInputEventData graphicInputEventData)
        {
            if (graphicInputEventData != null)
            {
                if (graphicInputEventData.selectedObject != null)
                {
                    ExecuteEvents.ExecuteHierarchy(graphicInputEventData.selectedObject, graphicInputEventData, ExecuteEvents.pointerUpHandler);
                    ExecuteEvents.ExecuteHierarchy(graphicInputEventData.selectedObject, graphicInputEventData, ExecuteEvents.pointerClickHandler);
                }
                graphicInputEventData.Clear();
            }
        }`
```

However, `graphicInputEventData.selectedObject` is null.

Hi. I was able to get it to work by adding two lines in `MixedRealityInputManager.HandlePointerUp` as I saw done elsewhere in the code.

```
        private GraphicInputEventData HandlePointerUp(IMixedRealityPointer pointer)
        {
            // Pass handler through HandleEvent to perform modal/fallback logic
            HandleEvent(pointerEventData, OnPointerUpEventHandler);

            GraphicInputEventData graphicEventData;
            FocusProvider.TryGetSpecificPointerGraphicEventData(pointer, out graphicEventData);

//--- ADD THIS:
            GameObject focusedObject = FocusProvider.GetFocusedObject(pointer);
            graphicEventData.selectedObject = focusedObject;
//----
            return graphicEventData;
        }
```

I don't know if it's the correct approach, but it unblocks me.

**Comment by StephenHodgson** [comment]
I'd make sure any canvas elements have a canvas utility on them first.

**Comment by wassx** [comment]
@andriworld do you have colliders on the buttons?

**Comment by andriworld** [comment]
@wassx no colliders.
