### ISSUE TITLE
Significant perf hit in Unity when MRTK Build Window is opened and visible

### ISSUE THREAD

**Issue by whitetigerhelix** [microsoft/MixedRealityToolkit-Unity#3264]
## Overview
I started experiencing extreme chop with Unity: the mouse jumping all over the place, and I couldn't click on anything or interact with the UI reliably.  Playing in the editor was impossible as there would be significant hitching.  I was freaking out because I couldn't make it go away, even after all the usual suspects and rebooting.
 
A colleague pointed out that having the MRTK Build Window visible seems to be causing this.  Sure enough, I switched to my Scene tab and the hitching and perf issues went away.

## Expected Behavior
No impact from having Build Window open

## Actual Behavior
Extreme blocking perf impact when Build Window is open

## Steps to reproduce
Open the MRTK Build Window and have it open and visible in your editor
Observe perf impact when using the editor, and when playing in editor

Note that this may not be as pronounced initially, and may be different for different projects or repos.
Note that rebooting, deleting library, etc do not improve the problem -- the perf hit persists.

## Unity Editor Version
Unity 2018.1.9f2

## Mixed Reality Toolkit Release Version
Latest mrtk_development

**Comment by StephenHodgson** [comment]
Need a bit more information from you:

1. Which version are you using?
2. Can you grab a screenshot of the profiler for the editor?
3. In the profiler, specifically what was causing the perf impacts?

**Comment by StephenHodgson** [comment]
I'm seeing well above 60 fps
![image](https://user-images.githubusercontent.com/13334553/49906129-6b2a9d00-fe25-11e8-83ff-971144459c5c.png)

**Comment by whitetigerhelix** [comment]
Version: latest mrtk_development

The profiler yields nothing interesting.  In fact, this issue causes Unity itself to hitch.  So when watching the profiler, you see it happily profiling, then it pauses for a few fractions of a second, then runs smoothly for maybe a second, then hitches again (repeat endlessly).  In other words, the hitching affects the entire app, including the profiler, and the profiler does not pick up any spikes or anything.  

When I tab away from the Build Window, now Unity stops hitching and is usable.

I have multiple clones of my repo, and strangely the performance impact is not identical between them (some are worse than others, I haven't been able to figure out a pattern).  But the hitching is present for all of them.

Thanks

**Comment by StephenHodgson** [comment]
Nothing coming up on the deep profiler either.

Pretty sure _something_ should be showing up on the profiler.

Do you have anything else that might help figure out what you're seeing, and how we can address it?

**Comment by StephenHodgson** [comment]
Okay, I think I _might_ have found the issue.

When we're updating the list of builds we search all the directories. This could be a pretty expensive call depending on how deep the project structure goes, and how many builds you've done.

I've got an update to make this async. Look for the PR soon.

**Comment by StephenHodgson** [comment]
Wasn't as trivial as I thought to make this change.

I'll need more information from you about the nature of the hang and the source.

**Comment by whitetigerhelix** [comment]
Thanks for investigating Stephen.  The profiler hitches along with the rest of Unity, so when it recovers, it just continues on as if nothing happened.  

It's interesting what you say about updating the list of builds, etc.  It's extremely likely that I have a huge ton of builds as I've been cranking on this enlistment for a couple months.  My other less hitchy enlistment probably has fewer builds to it as I've used it less often than my main enlistment.

As far as project structure, I'm not sure how deep ours is.  It's not a huge app, but it's been in production for a few months and has a fair amount of assets and scripts in it.  There are a lot of folders, and some of them chain a little deep, but nothing I'd red flag.  Of course, we do also have all of MRTK and the examples in our project.

**Comment by StephenHodgson** [comment]
Yeah, if you've got a lot of builds I can see that being the main cause.

Try clearing them out. (If you'd rather archive them, just move them out of your builds folder)

**Comment by whitetigerhelix** [comment]
Sure, I'll try that.  Where are the builds located?  I currently am building to the UWP folder.  I don't see a builds folder or anything like that.  What specifically is the path the build window is looking at?

**Comment by StephenHodgson** [comment]
If you switch over to the appx tab there should be a button that will pop you right to the packages in file explorer.

**Comment by whitetigerhelix** [comment]
Oh, I see, the app packages.  I only had a few of them there, and the problem persisted even after I deleted them all.  With the Build Window open, Unity hitches badly, with the window closed, no hitching.  :(

**Comment by keveleigh** [comment]
@whitetigerhelix The build tools were updated via https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3618. Might be worth retesting to see if this was resolved.
