### ISSUE TITLE
spatial mapping can not detect human body

### ISSUE THREAD

**Issue by joveth** [Microsoft/MixedRealityToolkit-Unity#3265]
## Overview
I'm using spatial mapping to detect my legs, but can not do this.
Does it have any ideas to detect human body?
Or any other module can do this?

Thanks a lot!

## Expected Behavior
detect human body

## Actual Behavior
no spatial mapping  of my leg.

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2017.4 LTS
## Mixed Reality Toolkit Release Version
HoloToolkit 2017.4.2.0

**Comment by ThomasAstrakhan** [comment]
Try to map somebody else. It's working for me. Maybe you are too close from your legs :p

**Comment by davidkline-ms** [comment]
Spatial Mapping is designed to detect and map the enviornment. It _will_ detect a human body, however it does not _track_ human bodies (ex: Kinect)
