### ISSUE TITLE
Missing Parabolic line helper warning using Unity 2018.3.0f2

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#3271]
Missing Parabolic line helper.
The Parabolic Teleport Pointer requires an empty GameObject child for calculating the parabola arc.
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.SDK.UX.Pointers.ParabolicTeleportPointer:OnValidate() (at Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/ParabolicTeleportPointer.cs:36)

**Comment by StephenHodgson** [comment]
Fixed in https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3269

**Comment by davidkline-ms** [comment]
Excellent! I'll stop filing the warnings (was adding them here for tracking) :)

Thanks!

**Comment by StephenHodgson** [comment]
Was this in a specific scene or a prefab?

**Comment by davidkline-ms** [comment]
> Was this in a specific scene or a prefab?

No scenes were loaded. Just a warning (among others) reported by the 2018.3 console window when opening the project.

**Comment by StephenHodgson** [comment]
Yeah, that should be fixed then.

**Comment by davidkline-ms** [comment]
The warning persists with changes made for 2018.3. Will continue investigating.

**Comment by davidkline-ms** [comment]
Cause appears to be a change in 2018.3 where OnEnable is not being called.

.3 debug output
------------------
>>> ParabolicTeleportPointer::EnsureSetop - (parabolicLineData != null) == True
>>> ParabolicTeleportPointer::EnsureSetop - (parabolicLineData != null) == True
Missing Parabolic line helper.


.2 debug output
------------------
>>> ParabolicTeleportPointer::OnValidate - (parabolicLineData != null) == True
>>> ParabolicTeleportPointer::EnsureSetop - (parabolicLineData != null) == True
>>> ParabolicTeleportPointer::OnEnalbe - (parabolicLineData != null) == True
>>> ParabolicTeleportPointer::EnsureSetop - (parabolicLineData != null) == True

**Comment by davidkline-ms** [comment]
Appears to have been resolved by deleting the Library folder after upgrading/updating
