### ISSUE TITLE
problem with jitter/latency issue

### ISSUE THREAD

**Issue by jinyunshui** [microsoft/MixedRealityToolkit-Unity#3277]
## Overview
There is an obvious jitter and latency issue for Holotoolkit for Unity since Unity3d 2018.2.2f1 and the later version (I've tested every version up to 2019.1.0a12).  Just drop a simple box in the scene and apply the mixed reality scene setting which could create an AR camera. No matter to use the holographic remoting or deploy it to Hololens, the hologram appears quite unstable with a very obvious jittering and drifting effect. This effect is very uncomfortable for hololens.  However, this won't happen before unity3d 2017.4.17f1 and the previous version.
Besides, even though it's such a simple scene, the Fps couldn't reach 60 (no matter remoting or deploy to hololens) .  The Fps is around 50, sometimes even lower, but the Microsoft official applications which is more complicated, but could reach 60 fps. Note that the unstable drifing issue is not caused by the lower FPS, because it's the same FPS with  unity3d 2017.4.17f1, but the hologram is relatively stable not that nasty.

## Expected Behavior
The hologram should be stable,  not moving relative to the environment.
## Actual Behavior
The hologram appears quite unstable with a very obvious jittering and drifting effect. 
## Steps to reproduce
_(Links to sample github project preferred)_
1. install the holotoolkit
2. apply the mixed reality scene setting which could create an AR camera
3. drop a simple box in the scene
4.  use the holographic remoting or deploy it to Hololens

## Unity Editor Version
Unity3d 2018.2.2f1 and the later version 

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity--2017.4.3.0

**Comment by darrendelorme** [comment]
Has there been any progress on this or have you found a solution to this issue?

**Comment by Yoyozilla** [comment]
Please reopen if you are able to repro this on MRTK v2 with Unity 2018.4. 
Thank you!
