### ISSUE TITLE
Axis Input not being updated on the HoloLens + Xbox One 

### ISSUE THREAD

**Issue by HyperLethalVector** [Microsoft/MixedRealityToolkit-Unity#3280]
## Overview
I'm currently running Unity 2017.4.17f alongside the MRTK + Examples
I set up the basic scene with a basic project, imported the holotoolkit and examples, setup as guided by the toolkit documentation (apply project + scene settings), run the xboxcontrollerinput scene example, whilst it works well in the unity editor + Xbox One S controller, I get strange axis behaviour on the  HoloLens + Xbox One S controller

On the hololens, all the buttons register correctly, it's only any axis input that doesn't update

(The values for the triggers, sticks, or any axis, are not being updated)
## Expected Behavior
All axis controls update correctly

## Actual Behavior

Axis controls are locked to a single value (See picture)
![image](https://user-images.githubusercontent.com/8954571/50150512-8738ad80-0301-11e9-9a20-5ac8d5814219.png)
## Steps to reproduce
> create new project under 2017.4.17f
> import MRTK + Examples
> set scene to Xbox One
## Unity Editor Version
2017.4.17f 
## Mixed Reality Toolkit Release Version
2017.4.3.0

Seems to be happening here: but I'm at least getting buttons, just not axis input.
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3184
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1490

**Comment by HyperLethalVector** [comment]
I will close this,

For those following, it is a unity 2017.x bug, which was fixed in 2018.2 onwards, however they haven't backtracked the fix to 2017

**Comment by keveleigh** [comment]
@HyperLethalVector Do you have a link to the Unity bug?

**Comment by jb-on-github** [comment]
I think this bug is the same than this one : https://forum.unity.com/threads/xbox-controller-issue-on-hololens.593812/
