### ISSUE TITLE
Controller input stops until I re-enter the application

### ISSUE THREAD

**Issue by HyperLethalVector** [microsoft/MixedRealityToolkit-Unity#3281]
## Overview
Running my unity application on the hololens, if there's any dips in FPS (say because I'm downloading a file) the Xbox One S controller input stops working altogether.
Then, if I "bloom" out of the application, then re-enter (basically put the app in standby, then open and continue where I left off) the input works again as expected.

## Expected Behavior
Controller input to be continuous even after a disconnect/reconnect/frame dip occurs
## Actual Behavior
Controller input halts, until I bloom out then re-enter the application
## Steps to reproduce
This I'm not so sure, I've noticed the main correlation is when my FPS drops suddenly (due to some computation that needs to be done), sometimes during normal use it drops as well (say, if there's no input for a certain amount of time).

## Unity Editor Version
2018.2.20f1
## Mixed Reality Toolkit Release Version
2017.4.3.0

EDIT:
I should probably mentioned this happened only after the RS5 update installed itself, with RS4 nothing like this occured.

**Comment by davidkline-ms** [comment]
@HyperLethalVector,

Thanks for the report! We will investigate and advise as soon as possible.

**Comment by HyperLethalVector** [comment]
Hi david, this is putting a massive risk on my upcoming experiment.

Do you happen to have an image of RS4?

**Comment by HyperLethalVector** [comment]
Hi!
I've managed to get my application to run at a consistent 60fps, but the problem still occurs.
Except now I've found a way to consistently re-produce the issue.

If there is no input from the controller for some period of time, Then you press any buttons/triggers on the controller there is no response until 'blooming' out of the application then re-entering.

There doesn't seem to be anything in the crash logs, this makes me think there's not something wrong with my application but it looks to be a system-level issue.
I also devise this due to the fact this issue didn't occur on RS4, only with RS5.

I'm attaching a google drive link with a deployable package containing a full debug build of my project.
https://drive.google.com/file/d/1eurAekQRU3eAz5N0Gn2nIIZyoAklnZrZ/view?usp=sharing

There's two modes
1) an ordinary UI with a small circle radar at the bottom
2) an additional circular menu appears when you're pressing the 'menu' button

**Comment by HyperLethalVector** [comment]
I decided to try from scratch with a new project & fresh import of the MRTK,
The same problem occurs using the example from HoloToolkit-Examples -> Input -> Scenes -> GamepadTest

On RS5, The controller works initially, but after some time period without input, the controller stops responding until I bloom out of the application then re-enter.


I'm desperate for some answers & solutions, or a link to the RS4 image.

Please help....

**Comment by JaredAvion** [comment]
By chance has anyone figure this out? Been trying for the past couple days to figure out how to solve this Controller input issue.

**Comment by HyperLethalVector** [comment]
From what I understand this may be OS level issues.

**Comment by JaredAvion** [comment]
@HyperLethalVector I just saw a user on reddit say that as well. Apparently Microsoft is aware and a fix is supposedly in the works but that quote was a month ago.

**Comment by Yoyozilla** [comment]
Bulk closing older issues. 
Please reopen if it still repros with the latest Unity 2018 + MRTK release
