### ISSUE TITLE
Getting Started Document is outdated

### ISSUE THREAD

**Issue by overdrivemachines** [Microsoft/MixedRealityToolkit-Unity#3287]
## Overview
I want to install the Mixed Reality Toolkit and was going through the Getting Started Guide (GettingStarted.md). It seems outdated.
## Expected Behavior
Latest versions displayed in WinVer, Unity 3D version, MixedRealityToolkit-Unity asset packages Version. It should be clearly mentioned what versions of Unity will work and what version of Unity it will not work.
So,
1) WinVer should show Microsoft Windows Version 1809 (OS Build 17763.194)
2) Windows 10 SDK version should be 10.0.17763.0
3) "Universal Windows Platform tools" does not exist in the latest Visual Studio Installer as shown in the image VisualStudioComponents.PNG
4) Recommended version of Unity must be consistent with other guides. Other guides say it should be the latest Unity 2017.4 LTS which right now it is 2017.4.17f1.
5) Under heading"2. Download the MixedRealityToolkit-Unity asset packages" the Latest Master Release should be HoloToolkit 2017.4.3.0
## Actual Behavior
1) Images shows Windows 1709
2) Old Windows 10 SDKs shown
3) Universal Windows Platform tools is checked as installed
4) Recommended Unity version is 2017.2.1p2 (which is old)
5) Latest Master Release for MixedRealityToolkit-Unity asset packages is v2018.8.0.0_Alpha2.1

## Steps to reproduce
Go to https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/GettingStarted.md
## Unity Editor Version
N/A
## Mixed Reality Toolkit Release Version
N/A

**Comment by Yoyozilla** [comment]
updated
