### ISSUE TITLE
Appbar in HoloToolkit 2017.4.3.0 duplicate my object

### ISSUE THREAD

**Issue by ghost** [microsoft/MixedRealityToolkit-Unity#3288]
## Overview
If I want an Appbar on my object, I put a Bouding Box Rig Component on it.
When my object is spawned, the function GetUntransformedCornersFromObject from the script BoundingBoxHelper create a duplicate of my objet, do a calculation then delete the duplicate.

This is a terrible thing to do !

Imagine if my object is super heavy to load ? or if in the Awake() or OnDestroy() function of one of my script, I do something super important, it will be called !

## Expected Behavior

Do not create a duplicate of my objects with an Appbar.

## Actual Behavior

Create a duplicate of my object when this object has an Appbar.

## Steps to reproduce

1) New Unity Project
2) Import MRToolkit 2017.4.3.0 (last version)
3) Create a gameObject in the scene
4) Put a BoundingBoxRig on it
5) Put a script with an Awake() and a OnDestroy()
6) Press Play
7) The function Awake will be called twice and OnDestroy will be called too.

![image](https://user-images.githubusercontent.com/39410322/50227695-a63d4b00-03a6-11e9-9b0d-857dfac31b4b.png)

![image](https://user-images.githubusercontent.com/39410322/50227773-ce2cae80-03a6-11e9-9008-92f3532275f0.png)

![image](https://user-images.githubusercontent.com/39410322/50228075-79d5fe80-03a7-11e9-8874-90ca36de5c9a.png)

## Unity Editor Version

2018.1.9f2

## Mixed Reality Toolkit Release Version

HoloToolkit 2017.4.3.0

**Comment by ThomasAstrakhan** [comment]
This is the Function which cause me the issue :


![image](https://user-images.githubusercontent.com/39410322/50229167-f964cd00-03a9-11e9-8784-f9c878f69108.png)

This is what I suggest :

![image](https://user-images.githubusercontent.com/39410322/50229203-0d103380-03aa-11e9-92be-bf4f5cf069a9.png)


But yeah, I know the calculation will not be without transformations...

**Comment by keveleigh** [comment]
Pinging @johnppella and @cre8ivepark for visibility.

**Comment by Yoyozilla** [comment]
Bulk closing older issues. 
Please reopen if it still repros with the latest Unity 2018 + MRTK release
