### ISSUE TITLE
Remove handedness parameter from pointer input events.

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#3298]
## Overview
Pointers shouldn't know about handedness as it doesn't have a property for it (nor should it) Pointers are scene objects that are driven by input sources like controllers. Pointers (like gaze) may be driven by multiple input sources (like hand input). Scripts utilizing this should be determining their handedness from the `IMixedRealityController`.

**Comment by keveleigh** [comment]
I don't think this change should be made. Most of our pointer implementations do know about their handedness, via the underlying `ControllerPoseSynchronizer`. It's set in the synchronizer's `Controller` setter, which is [set on controller pointers when they're created](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityDeviceManager.cs#L422).

In the case of the gaze pointer, forwarding along the handedness ([the way the events currently work](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit-SDK/Features/Input/GazeProvider.cs#L357)) is the only way to get handedness off a gaze-pointer-fired Pointer event. If we remove that forwarding, the only `IMixedRealityController` that's accessible is the gaze pointer's, not the hand's (and I'm not even sure the GazeProvider ever sets its controller to anything).

**Comment by StephenHodgson** [comment]
We should def make this change, and I'll show you the best way to get the handedness when we cross that bridge.

This change is also not a breaking change, unlike the changes you proposed in your PR.

**Comment by keveleigh** [comment]
>I'll show you the best way to get the handedness when we cross that bridge.

Can you show me? I can't see a way to get handedness from the gaze pointer's events.

>This change is also not a breaking change

This is also a breaking change, as it contains [changes to an interface](https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3297/files#diff-9c5abb1cfbe256c72d0aeb5b3ffdcea7R269).

**Comment by StephenHodgson** [comment]
lol, not it's not a breaking change as a developer getting this update wouldn't have to update their code at all.

**Comment by StephenHodgson** [comment]
> Can you show me? 

[Already a step ahead of you](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3299)

Now _that_ is a breaking change :p

**Comment by keveleigh** [comment]
>it's not a breaking change as a developer getting this update wouldn't have to update their code at all.

If they have their own concrete implementation of `IMixedRealityInputSystem`, they will have to update their code with the interface change.

**Comment by StephenHodgson** [comment]
Ah, yes, in that case then I suppose it would be.

**Comment by keveleigh** [comment]
I think removing the Pointer event data setting this value will be confusing. The associated PR doesn't remove the ability to query for `Handedness`, as that's [baked into the underlying `InputEventData` definition](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit/_Core/EventDatum/Input/InputEventData.cs#L19). Instead, it removes meaning from that value while it's still accessible.

Needing to know to query for the specific controller in some cases (re: #3299) while relying on `eventData.Handedness` in others seems like a confusing pattern.

**Comment by StephenHodgson** [comment]
We could update that property to just return the input source controller handedness with that utility method I proposed.

So no need to remove it. In fact I'll add that to the change in the other PR.

**Comment by keveleigh** [comment]
That's exactly the [handedness that's already used](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/ControllerPoseSynchronizer.cs#L62).

What's the value in needing to ask the input system for a handedness when it's already accessible in [one line (`eventData.Handedness`)](IMixedRealityController ) or in the [pointer class's own property](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs#L414)?

**Comment by StephenHodgson** [comment]
See the change in the other PR where I updated the [`event.Handedness` property](https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3300/files#diff-dda3de0f1009832795ed7aa8c4219c71R24).

**Comment by StephenHodgson** [comment]
I actually decided to roll in all the changes together into the same PR.

In either case, pointer event data now inherits from `BaseInputData` instead.

**Comment by keveleigh** [comment]
>In either case, pointer event data now inherits from BaseInputEventData instead.

The solution for providing handedness in pointer events was to remove handedness from the pointer event data? I'm not sure how making this information harder to discover or access adds value.

Handedness in all event data based on input / pointers is valuable information for handed interactions.

**Comment by StephenHodgson** [comment]
Sure, but the pointers shouldn't know that information. It should only be provided by the controller.

**Comment by StephenHodgson** [comment]
And I added an easy way to get that information though the input system.

```
void IMixedRealityPointerHandler.OnPointerUp(MixedRealityPointerEventData eventData)
{
    var controller = MixedRealityToolkit.InputSystem.TryGetController(eventData.InputSource);
    Debug.Assert(controller != null);
    Handedness handedness = controller.ControllerHandedness;
}
```

**Comment by keveleigh** [comment]
Pointers either [already know that information](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/ControllerPoseSynchronizer.cs#L62) or [simply forward it along](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit-SDK/Features/Input/GazeProvider.cs#L369).

Pointers that know about their handedness know about it from the controller in the first place.

**Comment by keveleigh** [comment]
>an easy way to get that information though the input system

It's both less easy and less discoverable than `eventData.Handedness`.

**Comment by StephenHodgson** [comment]
In either case pointers shouldn't know about handedness.

Likely if you need to know about handedness then the logic needs to be in (InputUp/Down/Pressed) as those are specific to controllers.

Pointer events are really only for notifying the UI that events need to take place, and those events should not need to know about the input source nor their handedness.

**Comment by StephenHodgson** [comment]
For example:
A button doesn't need to know that my left hand clicked it. It just needs to know that it was clicked.

**Comment by keveleigh** [comment]
>that logic shouldn't be in the presentation layer, but in the business app logic.

And that's an option if that's how you want to design your app. As is the reverse.

>if anything Focus events should handle if a button can or cannot be clicked by a specific handedness input source.

Instead of filtering within a single event (OnPointerClick), the proposed method after this change is to need to chain two events (OnFocusEnter, OnPointerClick)? Twice as many events to handle doesn't seem better.

**Comment by StephenHodgson** [comment]
> And that's an option if that's how you want to design your app. As is the reverse.

Haha, no that's how the whole Framework architecture was designed.

**Comment by StephenHodgson** [comment]
We have very clear separations between business app logic and presentation layer "GameObject" logic

**Comment by davidkline-ms** [comment]
Not needed.
