### ISSUE TITLE
Proposal: Add a convenience method for easier access to detected controllers

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#3299]
## Overview
I'd like to add a convenience method to the input system interface contract to make it easier to get a reference to a detected controller using the input source.

This will make getting controller properties easier.

```
void IMixedRealityPointerHandler.OnPointerUp(MixedRealityPointerEventData eventData)
{
    var controller = MixedRealityToolkit.InputSystem.TryGetController(eventData.InputSource);
    Debug.Assert(controller != null);
    Handedness handedness = controller.ControllerHandedness;
}
```

**Comment by Yoyozilla** [comment]
seems useful, not adoption blocking. will discuss on teams and slack and close before 1/16

**Comment by Yoyozilla** [comment]
Agreed this is good to have, but not critical for 2018 release. We will opportunistically pull this into 2018.
