### ISSUE TITLE
Using more than one Collider/Button

### ISSUE THREAD

**Issue by arsi0001** [microsoft/MixedRealityToolkit-Unity#3304]
## Overview
I downloaded the HoloToolkit-Examples-Package and tried to understand how buttons work. So I created a cube with one Button on the top. If I press the button, the cube should do some animations. All this works fine, but now I want to have two buttons on the cube and I noticed that the "Compund Button"-scripts has a fixed hierarchy/structure.

## Expected Behavior
Every collider should do his own work

## Actual Behavior
So my problem is that the colliders in my child triggers the same animation like the collider in the parent.

## Steps to reproduce
Here is a image of the cube with the buttons https://imgur.com/Ez5bvZb
What I did was:
Parent -> Button (made out of a cube) with the scripts Compound Button, Compound Button Mesh, Compound Button Anim..
Child -> Cube and another Button (made out of a cube)

Why I didnt choose the hierarchy "Parent: Cube" and "Child: Two Buttons"? Because by putting compound scripts on childs, they cant access the parent. For example pressing the button will trigger an animation with "Compund Button Anim", so the cube rotates. But I cant reference the cube, because its the parent.
## Unity Editor Version
2017.4.17f1
## Mixed Reality Toolkit Release Version
HoloToolkit 2017.4.3.0

**Comment by lordlycastle** [comment]
I doubt you'll be able to have two buttons as child of one or other. It's more unity limitation i think. You should be able to achieve what you're trying without requiring this.

**Comment by Yoyozilla** [comment]
Bulk closing older issues. 
Please reopen if it still repros with the latest Unity 2018 + MRTK release
