### ISSUE TITLE
Update Unity requirement to 2018.3

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#3306]
## Overview
To get the Mixed Reality Toolkit closer to the upcoming Unity 2018 LTS release, it will need to update to 2018.3 and drop support for 2018.1 and 2018.2.

This will be a breaking change as Unity has changed prefab formats in 2018.3.

## Requirements
- [x] Check for 2018.3 or newer on
    - [x] Project load
    - [x] Package import
- [x] Display a message indicating an unsupported version is being used and allow user to:
    - [x] Continue (and expect errors / incorrect behavior)
    - [x] Close the editor
- [x] Project loads without script warnings
- [X] Apps behave as previously

**Comment by davidkline-ms** [comment]
Current blockers on this:
- Warning re: Missing Parabolic line helper (#3271)
- Motion controllers not working properly
    - Controllers that are connected at app start are pinned to the origin
    - Controllers that are turned on after app start do not get a pointer (straight or parabolic)

**Comment by jimmy12day** [comment]
Looking forward to this.
