### ISSUE TITLE
Proposal: Persist profile inspector foldout settings

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#3307]
## Overview
The Unity project panel will remember the expand / collapse settings for the file system. It would be nice for the profile inspectors to do the same with the new foldouts.

## Requirements
- Persist / read the user's desired foldout states for each profile

NOTE: We need to determine the correct behavior when a customer uses the default profiles (i.e. should we persist the foldout settings for the default profiles?)

## Acceptance Criteria
- [ ] Foldouts default to expanded the first time the Mixed Reality Toolkit is configured
- [ ] User settings are persisted across loads of a given project

**Comment by Troy-Ferrell** [comment]
This should be done as the profile system uses SessionState keys via

BaseMixedRealityProfileInspector.cs
protected static void RenderFoldout(ref bool currentState, string title, Action renderContent, string preferenceKey = null)
