### ISSUE TITLE
DeployOptions: Not able to connect to hololens and deploy appx

### ISSUE THREAD

**Issue by wassx** [microsoft/MixedRealityToolkit-Unity#3308]
## Overview
In the build window the deployment of appx to a hololens is broken.
Following stacktrace appears in console:

`Authentication failed! Device Not Found | No Response Headers
0x00000001415391C8 (Unity) StackWalker::GetCurrentCallstack
0x000000014153F706 (Unity) StackWalker::ShowCallstack
0x000000014140ED4B (Unity) GetStacktrace
0x00000001408B19D0 (Unity) DebugStringToFile
0x00000001418DE8A8 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x0000000017CEF790 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,string,UnityEngine.Object)
0x0000000017CEF663 (Mono JIT Code) [DebugLogHandler.cs:10] UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[]) 
0x0000000017CEEEE5 (Mono JIT Code) [Logger.cs:48] UnityEngine.Logger:Log (UnityEngine.LogType,object) 
0x00000000408F8B49 (Mono JIT Code) [Debug.bindings.cs:117] UnityEngine.Debug:LogError (object) 
0x000000003B204453 (Mono JIT Code) [DevicePortal.cs:830] Microsoft.MixedReality.Toolkit.Core.Utilities.WindowsDevicePortal.DevicePortal/<EnsureAuthenticationAsync>c__async15:MoveNext () 
0x000000003E71F516 (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:InvokeMoveNext (object)
0x0000000017003801 (Mono JIT Code) System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x0000000017002B5B (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x000000003E71F2BB (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
0x000000003E7684B9 (Mono JIT Code) System.Threading.Tasks.AwaitTaskContinuation:InvokeAction (object)
0x000000003E768150 (Mono JIT Code) System.Threading.Tasks.AwaitTaskContinuation:RunCallback (System.Threading.ContextCallback,object,System.Threading.Tasks.Task&)
0x00000000408F856B (Mono JIT Code) System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run (System.Threading.Tasks.Task,bool)
0x000000003B269471 (Mono JIT Code) System.Threading.Tasks.Task:FinishContinuations ()
0x000000003B266783 (Mono JIT Code) System.Threading.Tasks.Task:FinishStageThree ()
0x00000000408F8343 (Mono JIT Code) System.Threading.Tasks.Task`1<Microsoft.MixedReality.Toolkit.Core.Utilities.WebRequestRest.Response>:TrySetResult (Microsoft.MixedReality.Toolkit.Core.Utilities.WebRequestRest.Response)
0x00000000408F7F83 (Mono JIT Code) System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Microsoft.MixedReality.Toolkit.Core.Utilities.WebRequestRest.Response>:SetResult (Microsoft.MixedReality.Toolkit.Core.Utilities.WebRequestRest.Response)
0x000000003B20BA3B (Mono JIT Code) [DevicePortal.cs:888] Microsoft.MixedReality.Toolkit.Core.Utilities.WindowsDevicePortal.DevicePortal/<DevicePortalAuthorizationAsync>c__async16:MoveNext () 
0x000000003E71F516 (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:InvokeMoveNext (object)
0x0000000017003801 (Mono JIT Code) System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x0000000017002B5B (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x000000003E71F2BB (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
0x000000003E3D9AE1 (Mono JIT Code) [AwaiterExtensions.cs:146] Microsoft.MixedReality.Toolkit.Core.Utilities.Async.AwaiterExtensions:RunOnUnityScheduler (System.Action) 
0x00000000408F6CA3 (Mono JIT Code) [AwaiterExtensions.cs:191] Microsoft.MixedReality.Toolkit.Core.Utilities.Async.AwaiterExtensions/SimpleCoroutineAwaiter`1<T_REF>:Complete (T_REF,System.Exception) 
0x00000000408F36A3 (Mono JIT Code) [AwaiterExtensions.cs:383] Microsoft.MixedReality.Toolkit.Core.Utilities.Async.AwaiterExtensions/InstructionWrappers/<ReturnSelf>c__Iterator2`1<T_REF>:MoveNext () 
0x000000003E3DB140 (Mono JIT Code) [Coroutines.cs:17] UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) 
0x000000003E3DB330 (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void_object_intptr (object,intptr,intptr,intptr)
0x00007FFD1587A69B (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FFD15801BB2 (mono-2.0-bdwgc) [object.c:2915] do_runtime_invoke 
0x00007FFD1580AB9F (mono-2.0-bdwgc) [object.c:2962] mono_runtime_invoke 
0x0000000140C05C6A (Unity) scripting_method_invoke
0x0000000140BFDF30 (Unity) ScriptingInvocation::Invoke
0x0000000140BBCC36 (Unity) Coroutine::Run
0x0000000140BB574F (Unity) Coroutine::ContinueCoroutine
0x00000001408E9E3D (Unity) AsyncOperation::InvokeCoroutine
0x0000000141EEF12B (Unity) UnityWebRequestAsyncOperation::InvokeCoroutine
0x0000000141EEF3D7 (Unity) UnityWebRequestProto<UnityWebRequestTransport,AtomicRefCounter,RedirectHelper,ResponseHelper,DownloadHandler,UploadHandler,CertificateHandler,HeaderHelper,AsyncOperation>::Job_InvokeCoroutine
0x00000001408A296A (Unity) BackgroundJobQueue::ExecuteMainThreadJobs
0x0000000140969E22 (Unity) `InitPlayerLoopCallbacks'::`2'::EarlyUpdateExecuteMainThreadJobsRegistrator::Forward
0x000000014144C016 (Unity) Application::TickTimer
0x00000001415EB745 (Unity) MainMessageLoop
0x00000001415EDB38 (Unity) WinMain
0x000000014243478A (Unity) __scrt_common_main_seh
0x00007FFDA6A27E94 (KERNEL32) BaseThreadInitThunk
0x00007FFDA6FCA251 (ntdll) RtlUserThreadStart`

## Steps to reproduce
Open build window -> Deploy Options -> Enter IP and user/pwd. Connect triggers exception mentioned above.
Open Device Portal works!

## Unity Editor Version
2018.2.17f1
## Mixed Reality Toolkit Release Version
vnext mrkt_development

**Comment by thewolfwillcome** [comment]
The hololens uses an self signed certificate for the https connection.
In  Unity 2018 UnityWebRequest has a new property named certificateHandler.
https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest-certificateHandler.html
The default implementation checks if an certificate given by the server is trusted by the system on which unity runs.
In case of  self signed certificates the check fails. There are two possible ways to fix this:

1. Install the self signed certificate of the hololens on the system on which unity is running.
2. Implement en own Certifcate handler which checks the public key of the certificate against the public key of the hololens self signed certificate and return an success to allow the connection

For the second way here an example implementation:
``` csharp
public class MyHololensCertificateHandler : CertificateHandler
{
	// Encoded RSAPublicKey
	private static readonly string PUB_KEY = "<cert public key as string>";


	/// <summary>
	/// Validate the Certificate Against the hololens public Cert (self signed)
	/// </summary>
	/// <param name="certificateData">Certifcate to validate</param>
	/// <returns></returns>
	protected override bool ValidateCertificate(byte[] certificateData)
	{
		bool result = base.ValidateCertificate(certificateData);

		if (!result)
		{
			System.Security.Cryptography.X509Certificates.X509Certificate2 certificate = new System.Security.Cryptography.X509Certificates.X509Certificate2(certificateData);
			string pk = certificate.GetPublicKeyString();
			if (pk.ToLower().Equals(PUB_KEY.ToLower()))
			{
				result = true;
			}
		}
		return result;
	}
}
```

**Comment by JACKSONMEISTER** [comment]
@thewolfwillcome Would you be so kind and provide some details on solution 1?
I've downloaded the certificate from Device Portal (Preferences -> Device Security) and followed the steps stated there, however I still cannot connect from the Unity Editor.

**Comment by StephenHodgson** [comment]
One thing I noticed with RS5 devices specifically that some times I have to reset the device portal as one way to fix this issue.

**Comment by thewolfwillcome** [comment]
@JACKSONMEISTER You must install the downloaded certificate (https://<hololensip-address>/config/rootcertificate)
In following certification store inside the certification manager: "Trusted Root Certification Authorities"
You can check if the import was successfull with the right certificate try browse to https://<hololensip-address> with the Microsoft Edge browser (newly startet). Without installing this certificate Edge should show an error message about the unknown certificate. When installed properly the browser should not issue an certificate error.

You have to restart unity after installing the certificate so that it sees the new root certificate in the certificate store.
At least with HoloToolkit + Unity 2018.3.f1 it works this way for me.

**Comment by Yoyozilla** [comment]
Bulk closing older issues. 
Please reopen if it still repros with the latest Unity 2018 + MRTK release
