### ISSUE TITLE
vNext Proposal: Add console output in diagnostics

### ISSUE THREAD

**Issue by wassx** [microsoft/MixedRealityToolkit-Unity#3309]
## Overview
As debugging on the hololens is quite painful it would enormously speed up bug finding when e.g. a log output would be able to have as an overlay to get immediate feedback while testing on the hololens.

**Comment by Yoyozilla** [comment]
Could you elaborate with an example? Also feel free to create a pull request if you have a fix in mind!

**Comment by Yoyozilla** [comment]
Please reopen with a little more detail of your proposal :) 

thanks!
yoyo
