### ISSUE TITLE
Null references when using Sharing auto-discovery

### ISSUE THREAD

**Issue by danieltranca** [microsoft/MixedRealityToolkit-Unity#3311]
## Overview
If you want to enable the Auto Discover Server functionality on the SharingStage.cs script you will get two null references.

## Expected Behavior
It should not throw any errors.

## Actual Behavior
Throws two null references.
![image](https://user-images.githubusercontent.com/5989158/50689258-d597bd00-1020-11e9-81b8-3a0c8466cbcb.png)

## Steps to reproduce
this is done just by removing the manual IP config prefab and enabling the auto-discovery in the Sharing test scene.

## Unity Editor Version
2017.4.8f1

## Mixed Reality Toolkit Release Version
2017.4.3.0

### Extra
Also, the default timeout for auto join session and room is smaller than the ping of auto discovery meaning that it will try to join session/room before the auto discovery even begins. If auto-discovery is enabled the auto join room should wait until it discovered a server.

**Comment by Yoyozilla** [comment]
Sharing will be a standalone component in a separate repo. Please join the public sharing weekly shiproom for details :)
