### ISSUE TITLE
Connecting 2 Unity Editors to a server with auto-discovery crashes the second one

### ISSUE THREAD

**Issue by danieltranca** [microsoft/MixedRealityToolkit-Unity#3312]
## Overview
If you enable SharingStage's auto-discovery functionality it will work well on the first Unity Editor. But if you open a second one in order to test what's what the second one crashed on play in the function SharingClientPINVOKE.DiscoveryClient_Update(swigCPtr);

## Expected Behavior
Don't crash

## Actual Behavior
Crashed

## Steps to reproduce
Enable auto discovery(make sure you won't get any null references like this:  [references issue](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3311)). Duplicate project and try to connect with both and on the second one will crash

## Unity Editor Version
2017.4.8f1

## Mixed Reality Toolkit Release Version
2017.4.3.0

**Comment by Yoyozilla** [comment]
Sharing for HL2 and Unity 2018 will be a standalone component in a separate repo. Please join the public sharing weekly shiproom for details
