### ISSUE TITLE
Can not choose which layers to ignore when calculate BoundingBox for the Appbar

### ISSUE THREAD

**Issue by ghost** [microsoft/MixedRealityToolkit-Unity#3315]
## Overview

In the Appbar.cs script, in the function FollowBoudingBox, at [line 337](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/30934febe062eb9fd42479731fb50376b5076ed1/Assets/HoloToolkit/UX/Scripts/AppBar/AppBar.cs#L321) there is a call to UpdateNonAABoundingBoxCornerPositions() which take a LayerMask ignoreLayer parameter. However, this ignoreLayers variable is non setable in the inspector, making it totally useless.

## Expected Behavior

The ignoreLayers variable can be setted in the inspector.

![image](https://user-images.githubusercontent.com/39410322/50830306-ba41f000-1347-11e9-9d3d-954a4b0d3919.png)

## Actual Behavior

The ignoreLayers variable can not be set.

![image](https://user-images.githubusercontent.com/39410322/50830287-a8f8e380-1347-11e9-82bc-03d8ddfd3557.png)

## Unity Editor Version

2018.1.9f2

## Mixed Reality Toolkit Release Version

HoloToolkit 2017.4.3.0

**Comment by ThomasAstrakhan** [comment]
I found a better solution, it's to use the boundingBox ignoreLayers. Because why have 2 variables to do the same things ?! 

![image](https://user-images.githubusercontent.com/39410322/51185442-7024b580-18d7-11e9-8fdb-62e7175019a7.png)

**Comment by Wolvie9** [comment]
On Jan 15, 2019 6:09 AM, Thomas Astrakhan <notifications@github.com> wrote:I found a better solution, it's to use the boundingBox ignoreLayers. Because why have 2 variables to do the same things ?!

**Comment by Yoyozilla** [comment]
Looks like issues is solved.
bulk closing older issues. please re-open if you hit the issue again on the latest release.
