### ISSUE TITLE
SpatialUnderstanding implementation crashes

### ISSUE THREAD

**Issue by omartemianov** [microsoft/MixedRealityToolkit-Unity#3324]
## Overview

Tried using SpatialUnderstanding features to place an object on the edge of a plane. Here is the code I used:
`using System.Collections;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using UnityEngine;
using HoloToolkit.Unity;

public class TestPlace :MonoBehaviour
{
    public GameObject model;
    public void PlaceObject()
    { 

          List<SpatialUnderstandingDllObjectPlacement.ObjectPlacementRule> rules =
        new List<SpatialUnderstandingDllObjectPlacement.ObjectPlacementRule>() {
       SpatialUnderstandingDllObjectPlacement.ObjectPlacementRule.Create_AwayFromOtherObjects(1.0f),
        };

    List<SpatialUnderstandingDllObjectPlacement.ObjectPlacementConstraint> constraints =
        new List<SpatialUnderstandingDllObjectPlacement.ObjectPlacementConstraint> {
        SpatialUnderstandingDllObjectPlacement.ObjectPlacementConstraint.Create_NearCenter()
        };
        Vector3 halfdim = new Vector3(0.25f, 0.25f, 0.25f);
        Vector3 halfBottom= new Vector3(0.25f, 0.25f, 0.25f);
        SpatialUnderstandingDllObjectPlacement.ObjectPlacementDefinition placementDefinition = SpatialUnderstandingDllObjectPlacement.ObjectPlacementDefinition.Create_OnEdge(halfdim, halfBottom);

        

        // New query
        SpatialUnderstandingDllObjectPlacement.Solver_PlaceObject(
               "CustomObject",
    SpatialUnderstanding.Instance.UnderstandingDLL.PinObject(placementDefinition),
    rules.Count,
    SpatialUnderstanding.Instance.UnderstandingDLL.PinObject(rules.ToArray()),
    constraints.Count,
    SpatialUnderstanding.Instance.UnderstandingDLL.PinObject(constraints.ToArray()),
    SpatialUnderstanding.Instance.UnderstandingDLL.GetStaticObjectPlacementResultPtr());
        
        SpatialUnderstandingDllObjectPlacement.ObjectPlacementResult placementResult = SpatialUnderstanding.Instance.UnderstandingDLL.GetStaticObjectPlacementResult();

        // instantiate the hologram from a model
        var rotation = Quaternion.LookRotation(placementResult.Forward, placementResult.Up);
        Debug.Log("Reached object creation");
        GameObject gameobject = Instantiate(model, placementResult.Position, rotation) as GameObject;
        
    }

    public void Start()
    {
        PlaceObject();
    }

    

}`

## Expected Behavior
Expected to deploy it on HoloLens and see a model.
## Actual Behavior
 Instead of this, HoloLens just closes the application. Later tried to just run it in unity - Unity crashes. Unity supports said the problem is on Holotoolkits side.
## Steps to reproduce
Place SpatialUnderstanding and SpatialMapping prefabs into the scene, create Empty object and place the aforementioned code into it, place a 3d model in the provided field. Watch it crash

## Unity Editor Version
2017.4.1f1
## Mixed Reality Toolkit Release Version
2017.4.2.0

**Comment by Yoyozilla** [comment]
Bulk closing older issues. 
Please reopen if it still repros with the latest Unity 2018 + MRTK release
