### ISSUE TITLE
OnSourceDetected not called (IMixedRealitySourceStateHandler)

### ISSUE THREAD

**Issue by FireDragonGameStudio** [Microsoft/MixedRealityToolkit-Unity#3325]
## Overview
Hy everyone, I'm working with a WMR headset and implemented a small player controller handler for networking the controller. The Spawn/UnSpawn should be triggerd by ```OnStartLocalPlayer``` and by the events provided from ```IMixedRealitySourceHandler```.

## Actual behaviour
When testing in Editor, the events for ```OnSourceDetected``` and ```OnSourceLost``` are not called when a controller is connected/disconnected. The same happens btw. with an implementation of ControllerFinder. On Start it works, but within a session the events are not fired.

## Expected behaviour
The events for ```OnSourceDetected``` and ```OnSourceLost``` should be triggered every time a controller is connected/disconnected.

## Steps to reproduce
This is basically my current implementation. The spawn via ```OnStartLocalPlayer``` does work, but afterwards, nothing happens. It's also not possible to attach VS2017 to debug the events.

```csharp
public class PlayerControllerHandler : NetworkBehaviour, IMixedRealitySourceStateHandler {

    [SerializeField]
    private GameObject _leftNetworkControllerPrefab;
    [SerializeField]
    private GameObject _rightNetworkControllerPrefab;

    public override void OnStartLocalPlayer() {
        // spawn controller
        foreach (IMixedRealityController controller in MixedRealityToolkit.InputSystem.DetectedControllers) {
            SpawnNetworkController(controller);
        }
    }

    public void OnSourceDetected(SourceStateEventData eventData) {
        SpawnNetworkController(eventData.Controller);
    }

    public void OnSourceLost(SourceStateEventData eventData) {
        if (eventData.Controller?.Visualizer != null) {
            DestroyNetworkController(...);
        }
    }
    ...
    ...
}
```

## Unity Editor Version
2018.2.17f1

## Mixed Reality Toolkit Release Version
2018.9.0

Best regards :)

**Comment by keveleigh** [comment]
In order to get the source events without focus, you'll need to register as a global listener on the input system.

The [InputSystemGlobalListener script](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit-SDK/Features/Input/InputSystemGlobalListener.cs) shows a way to do this. You can also inherit from that class to allow it to register your script for you, but since your script is already a `NetworkBehaviour` you may need to add this code manually.

**Comment by FireDragonGameStudio** [comment]
Thx @keveleigh :) I'm pretty sure this will do the trick. I'll close this issue, after I've tested it.
