### ISSUE TITLE
controller visualization for Windows Mixed Reality

### ISSUE THREAD

**Issue by Yoyozilla** [microsoft/MixedRealityToolkit-Unity#3331]
## Overview

Currently, the only mechanism to visualize a specific controller model is for that model to be baked into the application as an obj, fbx, etc. and referenced in the appropriate profile.

HoloToolkit leveraged UnityGLTF, from Khronos, to enable requesting the model from the device. That had an additional dependency on Newtonsoft's JSON library. This dependency has caused conflicts when customers attempted to integrate HTK into projects that used a different version of the library,

To enable GLTF without the dependencies, we are investigating modifications to the UnityGLTF code that replaces the Newtonsoft library with .NET's DataContractJsonSerializer

**Comment by keveleigh** [comment]
Was added for WMR in #3673. Please let us know if you see any issues!
