### ISSUE TITLE
Opening the toolkit in unity throws an OpenVR error if steam isn't installed on machine

### ISSUE THREAD

**Issue by chrisfromwork** [Microsoft/MixedRealityToolkit-Unity#3337]
## Overview
It appears that some aspect of the toolkit's configuration expects openvr to be installed:
[10:58:13] XR: OpenVR Error! OpenVR failed initialization with error code VRInitError_Init_PathRegistryNotFound: "Installation path could not be located (110)"! 

Either the toolkit should list that steam is required in order to not get this error, or this error should only appear when 

## Expected Behavior
MRTK doesn't display any errors when opening in unity after completing setup instructions

## Actual Behavior
MRTK shows the following error when opening in unity after completing setup instructions:
[10:58:13] XR: OpenVR Error! OpenVR failed initialization with error code VRInitError_Init_PathRegistryNotFound: "Installation path could not be located (110)"! 

## Steps to reproduce
1) Get a PC that does not have steam installed
2) Install unity
3) Open MRTK with unity
4) Observe OpenVR Error

## Unity Editor Version
2018.3.1f1 was used to repro this bug, but I have heard that the issue also exists in previous releases

## Mixed Reality Toolkit Release Version
This is an issue when using the mrtk_development branch

**Comment by davidkline-ms** [comment]
This same / similar error occurs if the user does not have a headset plugged in. The message is coming from the OpenVR package.

Please be sure that Unity has the OpenVR package installed or the OpenVR SDK is not enabled in the Standalone player settings (presuming the application does not wish to target OpenVR / Steam)
