### ISSUE TITLE
It's unclear how to locally validate a pull request for the MRTK project

### ISSUE THREAD

**Issue by chrisfromwork** [microsoft/MixedRealityToolkit-Unity#3339]
After looking at the landing page for the MRTK project, it isn't obvious how to validate pull requests locally. I imagine there are best practices used by frequent contributors. We should share these best practices with the community so that new developers/reviewers for the project know how their changes will be validated/can run through validation with their local dev environments.

Some items that seem worth touching on in the documentation:
1) I've heard there are tests/unit tests. I do not know where these tests are located or how to run them.
2) It's unclear what user scenarios are supported/should be manually tested (AR scenarios, VR scenarios, etc). It's also unclear if example scenes exist that can validate these scenarios or if a user has to build their own scenes to avoid regressions.
3) It's easy to find a github example for checking out a pull request locally, but specifically linking to this information or stating the projects best practice for checking out a branch would ease this process.

**Comment by wiwei** [comment]
Closing this one out, as we've mostly moved to tests for the validation of our stuff (and also the PR template with its mention of how to pull things locally)

Also closed out related/duplicate issue
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/3338
