### ISSUE TITLE
Cant delete a world anchor that isnt attached to a gameobject

### ISSUE THREAD

**Issue by artsouflMS** [microsoft/MixedRealityToolkit-Unity#3340]
## Overview
In WorldAnchorManager, deleting a world anchor works only if there is a gameobject with that world anchor active.

## Expected Behavior
When I create a persistent world anchor and saved it to the store, after restarting the app,
and the world anchor isn't in the app in a gameobject, I want to be able to delete that 
world anchor from the store.
 
## Actual Behavior
In this case scenario, the WorldAnchorManager logs an error
Which isn't necessary

## Steps to reproduce
Create a persistent world anchor using WorldAnchorManager.cs so its saved in store.
Close and re-open the app so it starts fresh
Try to delete the world anchor by name
Notice that an error is logged

## Mixed Reality Toolkit Release Version
2017.4.3.0

**Comment by Troy-Ferrell** [comment]
Latest MRTK V2 has added the WorldAnchorManager again and there is an interface for delete world anchors not attached to gameobjects        
`public void RemoveAnchor(string anchorName)`
