### ISSUE TITLE
Tree layout and assembly restructure to align with packaging

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#3341]
## Overview

Currently, there are four top level folders in our tree (beneath Assets):

- MixedRealityToolkit
- MixedRealityToolkit-SDK
- MixedRealityToolkit-Examples
- MixedRealityToolkit-Tests

This proposal defines adding the following to for easy package source discovery:

- MixedRealityToolkit.Devices
    - WindowsMixedReality
    - OpenVR
    - UnityInput
    - WindowsVoiceInput
- MixedRealityToolkit.Services
    - BoundarySystem
    - DiagnosticsSystem
    - InputSystem
    - SpatialAwarenessSystem
    - TeleportSystem

As part of this change, assembly definitions will be adjusted to conform to the following convention:

MixedReality.Toolkit. < Layer > . [ Area ]

Examples:

- MixedReality.Toolkit.Core (was MixedRealityToolkit)
- MixedReality.Toolkit,Devices.WindowsMixedReality
- MixedReality.Toolkit.Services.BoundarySystem

Future pull requests will address renaming existing top level folders (ex: MixedRealityToolkit-SDK -> MixedRealityToolkit.SDK).

# Acceptance Criteria
- [x] Assemblies reference the minimal set required to function (ex: most will only reference MixedRealityToolkit.Core)
- [x] Samples and demos updated to reference new assemblies and namespace changes,
- [x] New assemblies created
    - [x] MixedRealityToolkit.Services.*
        - [x] BoundarySystem
        - [x] DiagnosticsSystem
        - [x] InputSystem
        - [x] SpatialAwarenessSystem
        - [x] TeleportSystem
    - [x] MixedRealityToolkit.Providers.*
        - UnityInput - To be addressed in a later change (needs #3074)
        - [x] WindowsVoiceInput
        - WindowsMixedReality - To be addressed in a later change (needs #3074)
        - OpenVR - To be addressed in a later change (needs #3074)

**Comment by SimonDarksideJ** [comment]
In stead of 
```
MixedRealityToolkit.Devices
```
Better
```
MixedRealityToolkit.Providers
```
As there could be many different data providers being added to the toolkit, e.g. Azure Speech, Networking, etc

**Comment by davidkline-ms** [comment]
> I will point out it makes no difference in packaging.

I agree, it is definitely possible to package regardless of tree structure. The intent is 100% to make it clearer and easier to understand our component divisions.

**Comment by davidkline-ms** [comment]
Edited description to fix grammar error and to be a bit more descriptive.

**Comment by jwittner** [comment]
Can we drop the word System from everything? Seems like everything in a Service is a System.

**Comment by davidkline-ms** [comment]
> Can we drop the word System from everything? Seems like everything in a Service is a System.

We could definitely do that. I will address when I rename "Devices" to "DataProviders" per @SimonDarksideJ's feedback

**Comment by StephenHodgson** [comment]
No, systems are "Singletons". While all systems are services, not all services are systems.

**Comment by davidkline-ms** [comment]
> While all systems are services, not all services are systems.

Is there an example of a non-system service that would warrant it's own assembly in the MRTK today? I can see the class / interface being called *System, but the namespace / assembly could drop the moniker
