### ISSUE TITLE
Cannot install anymore appx build after VS update

### ISSUE THREAD

**Issue by benjamincoven** [microsoft/MixedRealityToolkit-Unity#3346]
## Overview

After updating my Visual Studio start of the week (I rarely do this), all the appx created from my Unity project with .NET scripting backend cannot be installed on Hololens, I get the following error:

Failure reason: Windows cannot install package because this package depends on a framework that could not be found. Provide the framework "Microsoft.NET.CoreRuntime.1.1" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x86 processor architecture and minimum version 1.1.27004.0, along with this package to install. The frameworks with name "Microsoft.NET.CoreRuntime.1.1" currently installed are: {Microsoft.NET.CoreRuntime.1.1_1.1.26702.0_x86__8wekyb3d8bbwe} Failure text: Package failed updates, dependency or conflict validation. (0x80073cf3)

However Installing previous builds done before last week still works.

By the way IL2CPP scripting backend never worked for me, when starting the app from the Hololens, I get a window with the error Failed to load game assembly.

## Unity Editor Version

2018.1.2

## Mixed Reality Toolkit Release Version

2017.4.2

## Visual Studio version

15.9.5

**Comment by benjamincoven** [comment]
Note: I had a look at the Microsoft.NET.CoreRuntime.1.1.appx by unzipping it and AppxManifest.xml Version is 1.1.27004.0

**Comment by benjamincoven** [comment]
Microsoft support had confirmed to me that there is a probleme in the last VS update.

The 3 possible workarounds for the moment are:
-Uninstall previous version of the application before installing a new one. This one did not worked for me
-Reset Hololens, quite annoying, I didn't try.
-Build with IL2CPP scripting backend, it works for me on some project and not on some other, morever it does not work when I use Visual Studio to build the APPX I have to use the MRTK build windows in Unity to make a complete build.

**Comment by cy238** [comment]
I had the same issue and couldn't reset the HoloLens or switch to IL2CPP. In the end installing the package with WinAppDeployCmd did the trick for me.

`WinAppDeployCmd.exe install -file "Microsoft.NET.CoreRuntime.1.1.appx" -ip 192.168.0.123`

Hope this helps.

**Comment by guitarrapc** [comment]
Is issue can avoid with following choice?

* Downgrade VS 15.9 to 15.8.x.
* VS15.9 with install `Microsoft.NET.CoreRunTtime.1.1.appx`
* Switch to IL2CPP

I've confirmed reset HoloLens won't install HoloLens appx build by 15.8.

**Comment by benjamincoven** [comment]
Switching to IL2CPP works for me and might be the best solution since it is said to be more performent and the MRTK vNext will support IL2CPP only.

**Comment by SimonDarksideJ** [comment]
For IL2CPP, you need to ensure you have BOTH the 2017 & 2015 C++ tools installed.  You can see these in the UWP C++ and Game Development for C++ screens to select.  A fair amount of extra bloat to your install for Unity's sake.
![image](https://user-images.githubusercontent.com/1793042/53804417-5c90e500-3f3f-11e9-809b-e7d08d0da213.png)

**Comment by codec-abc** [comment]
And for whose project only build with .Net and not with IL2CPP what is the solution? Am I screwed because HoloLens development is more unstable than the Javascript ecosystem and Microsoft doesn't care about quality?

**Comment by guitarrapc** [comment]
For whom want to stay .NET, not IL2CPP for a while.

I've dropped down CI's Visual Studio from 15.9 to 15.8 temporary and issue gone. (But PDB convert error eventually happen on VS build.)
This is just to gain a time and workaround until IL2CPP. Now changing CI/CD process and debugging to IL2CPP.
