### ISSUE TITLE
Add HoloShell like shader for rendering spatial mesh on air tap

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/MixedRealityToolkit-Unity#335]
Add a shader and material that emits a ring like effect when you air tap on the spatial mapping mesh.

Proposed location: Assets\HoloToolkit\SpatialMapping

**Comment by NeerajW** [comment]
@pinkwerks graciously agreed to add this.

**Comment by pinkwerks** [comment]
I have no idea how git works. This should bootstrap the effort. You'll need to drive the shader properties with a component. I'm not exactly up on the way HoloToolkit does things so its up for interpretation.

[SpatialMappingTap.zip](https://github.com/Microsoft/HoloToolkit-Unity/files/608292/SpatialMappingTap.zip)

**Comment by HodgsonSDAS** [comment]
@pinkwerks Fork the repository, and then pull your copy of the project with GIT or use some 3rd party GIT GUI like [SourceTree](https://www.sourcetreeapp.com/).  Make your changes and submit a PR.

**Comment by pinkwerks** [comment]
Is there supposed to be a fork button somewhere? I keep reading about it but don't see one.

**Comment by HodgsonSDAS** [comment]
Scroll to top of this page and look in upper left corner under your profile picture.

**Comment by pinkwerks** [comment]
Ah, that button seemed to be missing when I was looking from my phone. Thanks for helping me wade through this.

**Comment by keveleigh** [comment]
Was this resolved with #353?

**Comment by StephenHodgson** [comment]
Yes, I believe it was
