### ISSUE TITLE
QRTracker Doesn't detect markers on hololens

### ISSUE THREAD

**Issue by thewizardwand** [Microsoft/MixedRealityToolkit-Unity#3353]
## Overview
Simply attempting to run spectator view example scene and link the iPad to the hololens.

## Expected Behavior
hololens detects QR code on iPad after detecting the floor and Spectator view activates on iOS

## Actual Behavior
hololens fails to detect QR Code
(sharingservice.exe indicates iPad and hololens are in the same networked room
 so at least that part works)

## Steps to reproduce
Following the instructions from spectator preview setup tutorial
https://docs.microsoft.com/en-us/windows/mixed-reality/spectator-view

## Unity Editor Version
Using version 2017.4.3 of unity to build iOS and UWP Builds.

## Mixed Reality Toolkit Release Version
https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/2017.4.3.0

**Comment by chrisfromwork** [comment]
@thewizardwand when you are running the example scene, does the iPad show the ArUco marker on its screen? If this never occurs, it may be a networking issue.

If the marker is shown, have you seen any errors/unexpected log messages when running the HoloLens app under the visual studio debugger? Marker detection uses the HoloLens PV camera, which requires the webcam and microphone uwp capabilities (https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations )? It may be worth checking whether or not the output appxmanifest declares these permissions as expected. Sometimes, unity solution generation doesn't update appxmanifest files correctly/you need to delete your output visual studio solution and do a clean project rebuild in unity.

And just to be sure, when you went through the spectator view preview setup tutorial, did you compile the SpectatorViewPlugin dll out of the MixedRealityToolkit repo (https://github.com/Microsoft/MixedRealityToolkit/tree/master/SpectatorViewPlugin )? Did you put all output dll's into a unity Assets\Plugins\WSA\x86\ folder? Did you use release binaries compared to debug binaries (debug binaries are a lot slower and sometimes get terminated if called on unity's main thread)? There may be some error messages in the log output that can confirm if this dll isn't included correctly. Without this logic, you won't be able to conduct marker detection, but the application shouldn't crash.

**Comment by thewizardwand** [comment]
Greetings, I appreciate your response helping me out, I ended up resolving this issue by allowing the hololens enough time to take multiple pictures of the marker, I saw a video online that made it look instant, but it took about 30 seconds for it to get enough successful marker reads to activate. I did get it working, which and spectator view works nicely ~
