### ISSUE TITLE
Camera offset when changing scenes

### ISSUE THREAD

**Issue by Quatro4** [Microsoft/MixedRealityToolkit-Unity#3360]
I am developing a project in which I have two scenes and they work fine on their own. However, when I try to switch from one to the other I run into some trouble.

In order to switch scenes, I am using: SceneManager.LoadScene("Name of Scene");

The problem is that once the new scene loads, the headset and joystick position is no longer aligned to where I really am. From my current position I can see that the joysticks are a couple meters in front of me. I already tried reimporting the Camera Parent, but had no luck.

**Comment by Wolvie9** [comment]
💯Yeahdehduh~Mean, on that TUREALNESS TIP😎😉✔On Jan 26, 2019 5:18 AM, Quatro4 <notifications@github.com> wrote:Closed #3360.
