### ISSUE TITLE
Example for OneDrive usage

### ISSUE THREAD

**Issue by randystiles** [Microsoft/MixedRealityToolkit-Unity#337]
Can the HoloToolKit-Unity team provide an example of using FilePicker / XAML to open and save onto OneDrive (i.e. drive service).

There have been a number of postings by HoloLens developers over time asking about the use of onedrive with Unity on the HoloLens. This is because there are useful apps where hiding the data from them in Unity's Application.persistentDataPath where Unity's file io operations are supported is not a user solution.

There is one partial example of using StorageFile in the HoloToolkit code for saving meshes in MeshSaver.cs

There are many posts about these onedrive / Unity / HoloLens developer issues, here are a few:

https://forums.hololens.com/discussion/2785/still-having-a-problem-with-asynchronous-calls-using-unity5-40f3-htp-with-hololens

https://forums.hololens.com/discussion/comment/9759#Comment_9759

https://forums.hololens.com/discussion/1662/loading-a-file-from-onedrive-on-hololens

**Comment by cre8ivepark** [comment]
It will be really helpful for the developers!

**Comment by NeerajW** [comment]
@randystiles great request. 
Is this something you have cycles to research on and add one?

**Comment by randystiles** [comment]
I am trying to address this problem and can work with others to add something like a FileManager to deal with the file management aspect.  In my example, on HoloLens I let the user produce scenes, and also add pictures of the real world into the scene, and then save/load them.  References to the picture files taken have to also be moved to onedrive so the scene and pictures are together and not just stored locally on one particular HoloLens in the hidden from the user Unity persistentDataPath.  This turns out to be much more complex than it should be with FileOpenPicker, FileSavePicker, FutureAccessList, Unity UI and App threads, etc.

**Comment by mdouk** [comment]
Hello. Are there any updates on that?

**Comment by steuhh** [comment]
still interested in this

**Comment by randystiles** [comment]
Yes very much so. 

I have a working example in a small unity project, but there is a bug when using FileSavePicker that likely exists in the Microsoft Contract on HoloLens.

It is likely external to my program, I reported it in beta to unity about a year ago but now further action from them.

So - I want to get the MS contract for FileSavePicker fixed before posting the small example/usage to Github for MRTK.

-Randy

**Comment by bepierre** [comment]
Hey randi! It would be awesome if you could share your example. I've been stuck for quite some time now

**Comment by LeonSchulte** [comment]
@randystiles did you fixed the MS contract for FileSavePicker because im interrestet in OneDrive integration too.
And your small project would really help me
Thanks

**Comment by StefanoWoerner** [comment]
I am very interested in this as well, especially since, unlike @randystiles, I don't have a working example yet. Is anyone else out there that has a working example?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
