### ISSUE TITLE
After updating to latest LTS Version 2017.4.18 CS0117 'Application' does not contain a definition for 'quitting' 

### ISSUE THREAD

**Issue by Dustin-Boyle** [microsoft/MixedRealityToolkit-Unity#3373]
I just updated to the latest LTS version  2017.4.18.

After updating I have two errors that I am not sure how to solve:

1: MixedRealityToolkit/_Core/Services/MixedRealityToolkit.cs(398,47): errorCS0117 'Application' does not contain a definition for 'quitting' Microsoft.MixedReality.Toolkit
2: MixedRealityToolkit/_Core/Services/MixedRealityToolkit.cs(398,47): error CS0117: `UnityEditor.EditorApplication' does not contain a definition for `hierarchyChanged'

Any Idea what the problem might be?

I think Mixed Reality Toolkit Release Version is for unity 2018, do I need an Older version? I would like to use the beta so I can take advantage of the sharing features.
`   /// <summary>
        /// Lock property for the Mixed Reality Toolkit to prevent reinitialization
        /// </summary>
        private static readonly object initializedLock = new object();

        private void InitializeInstance()
        {
            lock (initializedLock)
            {
                if (IsInitialized) { return; }

                instance = this;

                if (Application.isPlaying)
                {
                    DontDestroyOnLoad(instance.transform.root);
                }

                Application.quitting += () =>
                {
                    isApplicationQuitting = true;
                };

#if UNITY_EDITOR
                UnityEditor.EditorApplication.playModeStateChanged += playModeState =>
                {
                    if (playModeState == UnityEditor.PlayModeStateChange.ExitingEditMode ||
                        playModeState == UnityEditor.PlayModeStateChange.EnteredEditMode)
                    {
                        isApplicationQuitting = false;
                    }

                    if (playModeState == UnityEditor.PlayModeStateChange.ExitingEditMode && activeProfile == null)
                    {
                        UnityEditor.EditorApplication.isPlaying = false;
                        UnityEditor.Selection.activeObject = Instance;
                        UnityEditor.EditorGUIUtility.PingObject(Instance);
                    }
                };

                UnityEditor.EditorApplication.hierarchyChanged += () =>
                {
                    if (instance != null)
                    {
                        Debug.Assert(instance.transform.parent == null, "The MixedRealityToolkit should not be parented under any other GameObject!");
                        Debug.Assert(instance.transform.childCount == 0, "The MixedRealityToolkit should not have GameObject children!");
                    }
                };`

**Comment by Ecnassianer** [comment]
The Mixed Reality Toolkit requires Unity 2018.2.13f1 or later:
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Documentation/GettingStartedWithTheMRTK.md

You might be confusing Mixed Reality Toolkit with its predecessor, HoloToolkit, which exists for 2017.4. However, HoloToolkit is getting a bit long in the teeth. You're better off updating Unity to 2018.2.13f1 or later. That way you can take advantage of all the improvements in Mixed Reality Toolkit.
