### ISSUE TITLE
vNext Task: Example script/scene for Navigation Gesture

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/MixedRealityToolkit-Unity#3374]
## Overview
There is no example which demonstrates 'Navigation Gesture' for HoloLens. A lot of HoloToolkit customers use Navigation gesture. 

Navigation gesture is introduced as an official gesture in HoloLens:
https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-211

**Comment by Yoyozilla** [comment]
Done?
