### ISSUE TITLE
vNext Task: Example script/scene for Manipulation Gesture

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/MixedRealityToolkit-Unity#3375]
## Overview
There is no example which demonstrates 'Manipulation Gesture' for HoloLens. A lot of HoloToolkit customers use Manipulation gesture. 

Manipulation gesture is introduced as official gesture in HoloLens:
https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-211

**Comment by Yoyozilla** [comment]
done
