### ISSUE TITLE
How do I move the camera position through script?

### ISSUE THREAD

**Issue by Quatro4** [Microsoft/MixedRealityToolkit-Unity#3378]
I am trying to create a button, that when the user clicks it moves the user/camera to a new position. However, I haven't been able to do so either by modifying the transform.position of the MixedRealityCameraParent nor by newsting it into a new empty object.

**Comment by StephenHodgson** [comment]
Alternatively you can also use the Teleport system to achieve the same effect via button clicks and passing in a valid position.
