### ISSUE TITLE
Could not Find SDK "Microsoft.VCLibs, Version=14.0"

### ISSUE THREAD

**Issue by CL-Dan** [Microsoft/MixedRealityToolkit-Unity#3385]
## Overview
After recently being forced to upgrade from Visual Studio 2015 to 2017 I can no longer successfully make a build for the hololense. 
## Expected Behavior
The build should work as normal.
## Actual Behavior
Build fails with error Could not Find SDK "Microsoft.VCLibs, Version=14.0"
## Steps to reproduce
_(Links to sample github project preferred)_
- Bild project in Unity
- Open in Visual Studio
- Build Solution
 
## Unity Editor Version
2017.2.0f3
## Mixed Reality Toolkit Release Version
An old release of Holo Toolkit, Not sure how to find the version number

**Comment by wiwei** [comment]
Looking at other places online, I can see this question got asked around:

https://www.reddit.com/r/HoloLens/comments/alc5k2/could_not_find_sdk_microsoftvclibs_version140/

From what I can tell with some basic googling it looks like these tend to be associated with messed up VS installed - especially given that you mention that there is an upgrade involved, I'm guessing you probably ended up getting something corrupted during the install.

If this is still an issue, I would recommend:

1) Ripping out your existing VS install and starting fresh, installing the reqs needed from scratch.
2) Reopen an issue with more recent info.
