### ISSUE TITLE
Add Attribute to make sure we can migrate to data provider in V3

### ISSUE THREAD

**Issue by Yoyozilla** [Microsoft/MixedRealityToolkit-Unity#3387]
Implement an attribute that will enable both easy migration from v2 to v3 configuration profiles as well as to surface useful default data when adding the provider (ex: configuration profile, supported platforms, etc).

**Comment by davidkline-ms** [comment]
Not a breaking change. If a provider does not have the attribute it will not be moved automatically, but will still work.
