### ISSUE TITLE
3D Mesh Registration between two scanned models

### ISSUE THREAD

**Issue by DasZamomin** [microsoft/MixedRealityToolkit-Unity#3395]
The basic idea is to provide a an ICP algorithm to be able to to estimate the combination and rotation of a previously scanned spatial mapping and the real time spacial mapping. This transformation could be applied to the objects the user wants to place in the real world in relation to the saved an scanned spatial mapping (user could place holograms in Unity in relational to the previously scanned and loaded spatial mapping)

**Comment by davidkline-ms** [comment]
This issue actually applies to the platform vs MRTK. Will talk to that team.
