### ISSUE TITLE
Default Cursor colour won't change in runtime for all pieces

### ISSUE THREAD

**Issue by pocce90** [microsoft/MixedRealityToolkit-Unity#3415]
## Overview
Default Cursor colour won't change in runtime for all pieces
## Expected Behavior
Changing colour of default cursor in runtime must change the colour 

## Actual Behavior
Trying changing colour of default cursor in runtime working but not for the mesh_top, it remains with started color

## Steps to reproduce
Simply try to change colour in the editor after pressed play

The problem is in the CursorWaitingAnim animation, there is a record about the colour. Deleting that record solve the issue

## Unity Editor Version
2018.3.4f1

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-2017.4.3.0.unitypackage

**Comment by StephenHodgson** [comment]
Because it's part of an animation.

You'll need to update the animation with the color you'd like, or change it based on some value you're reading at runtime.

**Comment by Yoyozilla** [comment]
Looks like a solution is provided! Thanks!
Please reopen if issue repros
