### ISSUE TITLE
Proposal: MRTK v2 Packaging Plan

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#3418]
The following images describe the proposed packaging plan for MRTK v2.

We would love to hear your feedback. Please feel free to post your comments!

Some key call outs:
- Foundation packages
    - Maintained and supported by the Microsoft Mixed Reality Toolkit team.
    - Source will be checked in to this Mixed Reality Toolkit repository and will follow the contribution guidelines
- Extension packages
    - Maintained and supported by their author(s)
    - Are made available to the Mixed Reality Toolkit packaging system via tags or similar discovery mechanism(s)
    - May, but need not, take a dependency on one or more Mixed Reality Toolkit components
        - Author(s) are responsible for declaring dependencies
- Experimental packages
    - Support flighting prototype features, pre-release extensions, new ideas, etc. to the community

![slide1](https://user-images.githubusercontent.com/13281406/52441934-d8317a80-2ad6-11e9-8807-8d01f7f18701.PNG)

![slide2](https://user-images.githubusercontent.com/13281406/52441944-dcf62e80-2ad6-11e9-8d67-ab50dc69a95c.PNG)

**Comment by Yoyozilla** [comment]
Love the categorization of packages! 

Questions/thoughts 
I think we should also provide some how to along with the design doc: 
- What's the guidance for building a package that's part of the foundation 
- How can a community member create an extension to MRTK? How to package, how to tag where should their code go? 
- How can Azure or other services integrate into MRTK?

**Comment by hridpath** [comment]
Just so I am clear on the intent. Microsoft Mixed Reality team will own and manage the core of this repository. Non-team contributors will package thier code as Extenstions to the core/Foundation and will only be packaged as NuGet packages. Unity Package manager will not include Extensions. 

Do you intend for the Extensions to be Assets in the Unity Asset Store?

**Comment by davidkline-ms** [comment]
> Just so I am clear on the intent. Microsoft Mixed Reality team will own and manage the core of this repository. Non-team contributors will package thier code as Extenstions to the core/Foundation and will only be packaged as NuGet packages. Unity Package manager will not include Extensions.
Do you intend for the Extensions to be Assets in the Unity Asset Store?

@hridpath, Thanks for the questions!

The Microsoft Mixed Reality Toolkit team will be responsible for the support of the foundation packages built from this repository. Community members are welcome to contribute fixes / features for review and inclusion. Once accepted, the MRTK team will support the code / release updates.

Extensions can be packaged in any way that the author wishes. We are investigating NuGet as a system to help with discovery and dependency resolution. The Asset store remains a great distribution method, though automatic dependency resolution may be a more manual process for customers. 

We also continue to investigate leveraging the Unity Package Manager and it's dependency resolution system.

**Comment by davidkline-ms** [comment]
> I think we should also provide some how to along with the design doc:

@Yoyozilla, agreed! Additional guidance is forthcoming (how to, etc) as the plan solidifies.

**Comment by TakahiroMiyaura** [comment]
This architecture is easy to understand!

If we want to develop the custom SDK for MRTK V2, we develop a Nuget package and distribute it?

Also, is there any reason to use both Nuget and Unity packages?
I think that "Nuget package" is easier to manage and develop the custom SDK :)

**Comment by chbecker-ms** [comment]
Simon brought up at shiproom that Nuget is sometimes restricted for universities or certain enterprises where they require the source. We need to investigate distributing the source as well.

**Comment by SimonDarksideJ** [comment]
Essentially, we should not restrict to one deployment / packaging plan, ensuring we have the most coverage to support all out target audiences:

- NuGet for enterprise and switched on devs
- Standalone asset package (download from GitHub) for newbies, indies, etc
- Aim for Asset store (as another delivery option)
- Source access from GitHub (and instructions for how to consume) for advanced devs.

**Comment by davidkline-ms** [comment]
I agree with @SimonDarksideJ with one caveat. It will be challenging for customers to manage the dependency graph if using multiple packaging systems. We will need to document the recommendation that you select one path for acquiring packages.

I plan on releasing both the core-only and complete foundation "starter" packages on both GitHub and the Unity Asset store (and package manager when available) and fully expect some extensions may only be released via the Asset store (depending on the author's preferences).

Please continue to comment here and help us evolve the MRTK packaging plan and implementation!

**Comment by davidkline-ms** [comment]
@TakahiroMiyaura,

> This architecture is easy to understand!

Thank you!

> If we want to develop the custom SDK for MRTK V2, we develop a Nuget package and distribute it?

If you package your extension vial NuGet, there will be a mechanism for tagging it so that the MRTK automatically detects and offers it via the package management UI that will be written.

> Also, is there any reason to use both Nuget and Unity packages?

The Unity Package Manager is a great new feature of Unity that we anticipate many customers utilizing.  We will likely start with NuGet (plus the other mechanisms @SimonDarksideJ mentioned above) and as the team learns more, branch out to other systems as requested by customers.

As always, feedback and contributions are very welcome!

**Comment by LanceMcCarthy** [comment]
I love the idea of using NuGet to handle package dependency, the only word of caution I have is to consider the NuGet version/ dev environments that don't automatically/silently install the dependencies (looking at you VS for Mac).

**Comment by davidkline-ms** [comment]
Thank you for the info @LanceMcCarthy! We will keep an eye out for that.

**Comment by davidkline-ms** [comment]
We have approved this proposal. Thanks for all of your feedback. Feel free to keep the feedback coming.

**Comment by markgrossnickle** [comment]
Is the path for NuGet mainly for native UWP developers using Visual Studio or do you foresee that being used by Unity developers as well?  I didn't know of any nuget integrations into Unity and just would use nuget to download the dll and drop it into the project, but looks like there is a nuget plugin for Unity now so perhaps it is even easier?

I think the easiest path for plug-in play within Unity would be the asset store but the most flexible path for those who like to extend the source (and contribute to it) would be Unity's package manager using local packages.  I don't think it is officially supported yet but I saw a video on how to do this in 2018.3 and it could be a simple way for github users to pull in specific folders they needed. You'd have a central checkout of the github project and you'd be able to pull in folders from MRTK into your various projects using the Package Manager. It is very similar to the symlink setup.   I was actually expecting/hoping for this route when I checked out MRTK today, but I didn't realize local packages weren't officially released yet.  Ref: https://forum.unity.com/threads/local-packages.637630/   Perhaps something to keep in mind for the roadmap?

**Comment by markgrossnickle** [comment]
Unity Package support can be as simple as adding a package.json to the file directly you would like to allow users to import into their project.  I just added that to MixedRealityToolkit.Exensions/Webrtc and was able to bring in that folder and its sub directories source files into my project using Unity 2018.3 and Unity 2019.1.  Details here:
http://blog.ickydime.com/2019/03/custom-local-packages-unity-package.html

It would be great if its eventually hosted somewhere and versions are maintained but for external contributors or those who just want to pull in the latest source code then this simple solution could be a great way to allow users to import code.
