### ISSUE TITLE
IMixedRealitySpatialAwarenessSystem.GetObservers<>() returns the base type, rather than the templated type

### ISSUE THREAD

**Issue by Ecnassianer** [Microsoft/MixedRealityToolkit-Unity#3420]
## Overview
I've templated GetObservers() to IMixedRealitySpatialAwareness**Mesh**Observers, but it returns IMixedRealitySpatialAwarenessObservers rather than the templeted type.
![image](https://user-images.githubusercontent.com/231247/52453551-ca8eeb80-2afc-11e9-80bb-2c3bcf53cf8f.png)

## Expected Behavior

Templted Get functions return the templted type, rather than a base type

## Actual Behavior

GetObservers returns something that I don't expect and I need to cast it every time I use it.

## Steps to reproduce
Put this in and note the compile error:
   IMixedRealitySpatialAwarenessMeshObserver observer = MixedRealityToolkit.SpatialAwarenessSystem.GetObservers<IMixedRealitySpatialAwarenessMeshObserver>()[0]

**Comment by davidkline-ms** [comment]
thanks @Ecnassianer ! will fix it asap
