### ISSUE TITLE
[UWP] Mixed Reality Toolkit -> Configure menu spawns MainCamera without Cursor Prefab on GazeProvider

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3423]
## Overview
I just wanted to create an empty scene and build it but there was no gaze for the Hololens when using the Configure menu and build it.
Looks like the GazeProvider is not properly setup

## Expected Behavior
Using configure and build just works

## Actual Behavior
No gaze on the Hololens

## Steps to reproduce
- Create an emtpy scene
- Run Mixed Reality Toolkit -> Configure
- Inspect the GazeProvider on the MixedRealityPlayspace/MainCamera

## Unity Editor Version
2018.2.14f1

## Mixed Reality Toolkit Release Version
mrtk_release

**Comment by keveleigh** [comment]
This will be fixed in the next release (coming soon!), and is already fixed in the dev branch. The gaze cursor is now set in the Pointer Profile instead of on the Gaze Provider, which allows it to be serialized in the default profile asset.
