### ISSUE TITLE
GazeProvidertype and Gaze Cursor prefab not assignable on creating new custom pointer profile

### ISSUE THREAD

**Issue by krishnan-unni** [Microsoft/MixedRealityToolkit-Unity#3425]
## Overview
When you create a new Pointer profile, It has the Gaze Provider settings. There the Gaze Cursor Prefab and Gaze Provider Type properties are not settable. The Provider type has a dropdown which shows GazeProvider class, but when you select it nothing happens. None is assigned.

Same happens to Gaze Cursor Prefab, it doesn't allow to set any type of Game object including the 'Default Cursor' prefab that is a part of the toolkit.

## Expected Behavior
Should be able to assign the Gaze Provider type and cursor prefab

## Actual Behavior
Not able to set the cursor prefab and the gaze provider

## Steps to reproduce
Start a new project and import the toolkit package. Click, MixedRealityToolkit-> Configure
Click the Active Profile of MixedRealityToolkit game object and click Create new (Same behavior with Copy&Customize)
Create new Input profile and then a Pointer profile.
In the Pointer profile, try assign the GazeProvider Type and the Gaze Cursor prefab

## Unity Editor Version
2018.3.3f1, 4f1 and 5f1 (tried all these 3)

## Mixed Reality Toolkit Release Version
mrtk_development

![mrtk101](https://user-images.githubusercontent.com/14880339/52540409-1f2da300-2d57-11e9-83e4-2cfdff5e5316.jpg)

**Comment by keveleigh** [comment]
Thanks for flagging this! I've opened PR #3426 with a fix.

**Comment by krishnan-unni** [comment]
One more thing., Now that I was testing, I noticed the same behavior on the Debug draw lines properties of the pointer profile

**Comment by krishnan-unni** [comment]
Nevermind, this #3426 fix that too. I replied too soon. :(
