### ISSUE TITLE
Question: UIRayCastCamera Disappearing on click of create new in profiles

### ISSUE THREAD

**Issue by krishnan-unni** [microsoft/MixedRealityToolkit-Unity#3427]
## Overview
This is a question basically -  Is it an expected behavior that the UIRaycastCamera will be removed and the GazeProvider script component also be removed from Main camera when we try to create new Profiles? (Not Copy and Edit)
Is the developer expected to manually create the UIRaycastCam if needed and to assign the GazeProvider script to Main camera manually? 

Unity version 2018.3.3 - 5f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by davidkline-ms** [comment]
@krishnan-unni, thank you for the bug report. we will investigate and advise as soon as possible,

**Comment by Troy-Ferrell** [comment]
UI Raycast camera now created at runtime, not editor. Closing bug
