### ISSUE TITLE
MRTK continually complains about irrelevant joysticks

### ISSUE THREAD

**Issue by Ecnassianer** [microsoft/MixedRealityToolkit-Unity#3430]
## Overview

I have a Saitek X-45 joystick hooked up to my computer. Unity continually prints this:

No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Core.Providers.UnityInput.GenericJoystickController.

But I don't care about the joystick, my project doesn't use it. Stawp complaining.

## Expected Behavior

Unity doesn't continually print warnings. Once is fine.

## Actual Behavior

No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Core.Providers.UnityInput.GenericJoystickController.
No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Core.Providers.UnityInput.GenericJoystickController.
No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Core.Providers.UnityInput.GenericJoystickController.
No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Core.Providers.UnityInput.GenericJoystickController.
No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Core.Providers.UnityInput.GenericJoystickController.
No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Core.Providers.UnityInput.GenericJoystickController.
No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Core.Providers.UnityInput.GenericJoystickController.
No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Core.Providers.UnityInput.GenericJoystickController.
No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Core.Providers.UnityInput.GenericJoystickController.
No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Core.Providers.UnityInput.GenericJoystickController.
No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Core.Providers.UnityInput.GenericJoystickController.
No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Core.Providers.UnityInput.GenericJoystickController.
<...>

## Steps to reproduce
Plug in a flight stick. Maybe one with a throttle. Maybe one with a little bit of drift.
Play in editor.
Observe so many warnings.

## Unity Editor Version
2013.3.3f1
## Mixed Reality Toolkit Release Version
Something near head in mrtk_development on 2/11/2019

**Comment by davidkline-ms** [comment]
@Ecnassianer, thanks for the issue! I agree that is a bit too much noise in the console window.

As a workaround, if your project does not intend to support joystick devices, you can go into the Registered Services profile and remove "Unity Joystick Manager".

**Comment by davidkline-ms** [comment]
![image](https://user-images.githubusercontent.com/13281406/52587177-57cc8b80-2dee-11e9-9693-d25b6a6e7536.png)

**Comment by Ecnassianer** [comment]
Thanks for the workaround. I also just noticed this guy sometimes too:
No Controller interaction mappings found for MouseController.

**Comment by SimonDarksideJ** [comment]
Hmm, definitely something that should not happen, although we do need to continually check in case someone plugs one in :D

**Comment by Troy-Ferrell** [comment]
Closing this out due to inactivity. If this repos with the latest version of MRTK, please re-open with relevant information. Thanks!

**Comment by Waffle1434** [comment]
This is happening to me as well and its quite annoying.
I plugged in a PS4 controller and this spams the log. This is a pretty bad default behavior.
```
No controller interaction mappings found for Microsoft.MixedReality.Toolkit.Input.UnityInput.GenericJoystickController.
UnityEngine.Debug:LogWarning (object)
Microsoft.MixedReality.Toolkit.Input.BaseController:.ctor (Microsoft.MixedReality.Toolkit.TrackingState,Microsoft.MixedReality.Toolkit.Utilities.Handedness,Microsoft.MixedReality.Toolkit.Input.IMixedRealityInputSource,Microsoft.MixedReality.Toolkit.Input.MixedRealityInteractionMapping[],Microsoft.MixedReality.Toolkit.Input.IMixedRealityInputSourceDefinition) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Providers/BaseController.cs:80)
Microsoft.MixedReality.Toolkit.Input.UnityInput.GenericJoystickController:.ctor (Microsoft.MixedReality.Toolkit.TrackingState,Microsoft.MixedReality.Toolkit.Utilities.Handedness,Microsoft.MixedReality.Toolkit.Input.IMixedRealityInputSourceDefinition,Microsoft.MixedReality.Toolkit.Input.IMixedRealityInputSource,Microsoft.MixedReality.Toolkit.Input.MixedRealityInteractionMapping[]) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Providers/UnityInput/GenericJoystickController.cs:31)
Microsoft.MixedReality.Toolkit.Input.UnityInput.GenericJoystickController:.ctor (Microsoft.MixedReality.Toolkit.TrackingState,Microsoft.MixedReality.Toolkit.Utilities.Handedness,Microsoft.MixedReality.Toolkit.Input.IMixedRealityInputSource,Microsoft.MixedReality.Toolkit.Input.MixedRealityInteractionMapping[]) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Providers/UnityInput/GenericJoystickController.cs:22)
System.Activator:CreateInstance (System.Type,object[])
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:GetOrAddController (string) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Providers/UnityInput/UnityJoystickManager.cs:202)
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:RefreshDevices () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Providers/UnityInput/UnityJoystickManager.cs:156)
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:Update () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Providers/UnityInput/UnityJoystickManager.cs:76)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:Update () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Services/BaseDataProviderAccessCoreSystem.cs:51)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit/<>c:<UpdateAllServices>b__72_0 (Microsoft.MixedReality.Toolkit.IMixedRealityService) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Services/MixedRealityToolkit.cs:1054)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder (System.Action`1<Microsoft.MixedReality.Toolkit.IMixedRealityService>) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Services/MixedRealityToolkit.cs:1145)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:UpdateAllServices () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Services/MixedRealityToolkit.cs:1054)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Services/MixedRealityToolkit.cs:727)
```

```Failed to create GenericJoystickController controller
UnityEngine.Debug:LogError (object)
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:GetOrAddController (string) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Providers/UnityInput/UnityJoystickManager.cs:207)
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:RefreshDevices () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Providers/UnityInput/UnityJoystickManager.cs:156)
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:Update () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Providers/UnityInput/UnityJoystickManager.cs:76)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:Update () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Services/BaseDataProviderAccessCoreSystem.cs:51)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit/<>c:<UpdateAllServices>b__72_0 (Microsoft.MixedReality.Toolkit.IMixedRealityService) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Services/MixedRealityToolkit.cs:1054)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder (System.Action`1<Microsoft.MixedReality.Toolkit.IMixedRealityService>) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Services/MixedRealityToolkit.cs:1145)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:UpdateAllServices () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Services/MixedRealityToolkit.cs:1054)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d1d4cefb204f-1618855547289/Core/Services/MixedRealityToolkit.cs:727)
```

```
Wireless Controller does not have a defined controller type, falling back to generic controller type
```

**Comment by Pallasite** [comment]
I had this issue myself for a SteelSeries Zeemote Bluetooth controller on MRTK 2. For me the issue was from the controller driver. It would show the Zeemote as an active paired Bluetooth device in my Windows devices even when the controller was not connected. The way I was able to get it to stop sending these messages in Unity was by either turning off the Bluetooth or removing the device driver from the control panel.
