### ISSUE TITLE
Controller mapping does not allow more than one 6 D0F mapping

### ISSUE THREAD

**Issue by krishnan-unni** [Microsoft/MixedRealityToolkit-Unity#3442]
## Overview
When you create a new Controller mapping the controller interaction allows for only 1 6DoF mapping and then only allows to set other interactions to the same mapping
## Expected Behavior
Controller interactions should allow different action mapping as long as the Axis constraint is matching
## Actual Behavior
Controller interactions does not allow more than one 6 DoF action in mapping
## Steps to reproduce
Create an Input action profile and define actions. Add 2 6D0F actions
Create a new Controller mapping profile. 
For this test case click on Hololens Gestures
Try to set one 6Dof for Spatial pointer and another 6DoF action for Grip

It'll set to Grip automatically and won't allow to change the action to anything other than None.
## Unity Editor Version
2018.3.5f1
## Mixed Reality Toolkit Release Version
mrtk_development

![1](https://user-images.githubusercontent.com/14880339/52609690-1d91d700-2e4c-11e9-9525-115d49d52463.jpg)

![mrtk102](https://user-images.githubusercontent.com/14880339/52609701-2682a880-2e4c-11e9-8452-038b190e8e6f.jpg)

**Comment by SimonDarksideJ** [comment]
Not sure I understand your query and possibly this is a disconnect between the Physical input definition and the resultant actions that are fired.

The Mixed Reality controllers only have a single 6Dof input, the controller itself, this is then captured and pushed to the input system as Pointer and Grip outputs.

The Controller Mapping then allows you to assign a single action to both the Pointer and Grip outputs from the controller (each having a slightly different origin as per the WMR SDK)

There is no use case for having multiple actions attached to a single input type that we are aware of,  if you wanted the action to do multiple things, then you would just have the "Action" work for multiple things in your project.

Alternatively, you can use the input action rules to fire off multiple events for different states of the 6Dof Input, it rules were only targetted for dual / single axis but it will work for 6Dof.

Did I understand what you are trying to do properly?

**Comment by krishnan-unni** [comment]
> Not sure I understand your query and possibly this is a disconnect between the Physical input definition and the resultant actions that are fired.
The Mixed Reality controllers only have a single 6Dof input, the controller itself, this is then captured and pushed to the input system as Pointer and Grip outputs.
I understand this.

> The Controller Mapping then allows you to assign a single action to both the Pointer and Grip outputs from the controller (each having a slightly different origin as per the WMR SDK)
I didn't understand this. My understanding is Controller mapping is used to map your hardware controller\hand actions\buttons to actions that you want to be interpreted as in your application. 
If this assumption is correct then why can't a user assign two actions defined in Actions profile to corresponding Controller mapping - in this case Point action to Spatial pointer and Grip action to Spatial Grip.

Or the above quote only applies to HoloLens gesture mapping?

Another question is, why and how is Spatial pointer and Spatial Grip the same to be treated with same action? Am I understanding the terms wrong? Are they semantically the same?

Also, may be the screen shot wasn't evident here, but it only allows Grip action to be assigned to both. But won't let Point action to be assigned to both. Though they both are 6DoF actions defined in Action Profile. Does the name has any relevance?

**Comment by keveleigh** [comment]
I'm unable to repro this in either the mrtk_development branch or the beta2_stabilization branch.

>why and how is Spatial pointer and Spatial Grip the same to be treated with same action?

You're right, they shouldn't be. For HoloLens hands, only spatial grip will return data, while Windows Mixed Reality controllers will provide poses for both the pointing ring and the grip handle.

Are there any additional repro steps I might have missed? I tried exactly your steps above.

**Comment by krishnan-unni** [comment]
I can supply screenshots for each step once I reach home from office. I tried with mrtk_development branch yesterday also with Unity 2018.3.3f1 and 5f1. I am sure there wasn't any more steps. But still I'll go see. Sorry for the delay

**Comment by krishnan-unni** [comment]
@keveleigh If HoloLens provides only Grip data then is there a reason Spatial pointer is a part of the HoloLens Gesture mapping? There is a separate mapping profile for WMR controllers right below that.

**Comment by keveleigh** [comment]
>If HoloLens provides only Grip data then is there a reason Spatial pointer is a part of the HoloLens Gesture mapping?

Likely not. I'll look into removing it.

**Comment by krishnan-unni** [comment]
@keveleigh Could this be anyway related to #3428 ? The Air Tap is not firing from Emulator or Unity Editor (I don't have HoloLens to test in real device). According to the code the Tap is not handled by GestureRecognizer from Unity but through Pointer click. So I don't know if the controller mapping config has anything to do with it. Is there additional setup needed for registering the WMRDeviceManager class? Like Speech Service is registered in the additional services.

**Comment by krishnan-unni** [comment]
@keveleigh Attaching screenshots. It is sporadic behaviour. I created 2 more actions of 6DoF Axis. Now it allows me to set different action for Spatial pointer and Grip but it wouldn't allow me certain combinations.. Thats' not it though. The system goes haywire when I try to change the controller mappings frequently after certain attempts. It simply goes blank as shown in the image no matter what option I select and the it wouldn't allow any combinations either. This I did on the mrtk_development branch which I pulled just now.

![1](https://user-images.githubusercontent.com/14880339/52686360-53ea5780-2f1b-11e9-969c-361e22b1adea.jpg)

![2](https://user-images.githubusercontent.com/14880339/52686366-58af0b80-2f1b-11e9-8568-becce7468740.jpg)

**Comment by davidkline-ms** [comment]
@krishnan-unni, Using the latest beta2-stabilization branch (commit: 26ad786), I am unable to reproduce your issue. Please let us know if you have a set of steps / repro project we can use if you are still seeing this after pulling the latest code.

Also, it would be good to know if an updated Unity release changes the behavior you are seeing. I tested using Unity 2018.3.6f1.

Thanks!

**Comment by krishnan-unni** [comment]
@davidkline-ms  I have uploaded the project here: https://github.com/krishnan-unni/MRTK-101
If you add One more action of 6DoF in the Actions profile and randomly change the Hololens mapping you can see the issue.
The issue also has the #3428 problem when tried in emulator. It would be helpful to know I have all the configs right.

**Comment by keveleigh** [comment]
After downloading your project, I'm still unable to repro the issue unfortunately. I tried changing both your existing Rotate action to SixDof and adding a new SixDof action, and I was able to set the controller mapping values however I tried.

**Comment by krishnan-unni** [comment]
I just deleted all actions now and tried again. Now it is assigning properly 😕 . The Air tap is still not working though
