### ISSUE TITLE
Inappropriate Resource Folder Usage in MRTK

### ISSUE THREAD

**Issue by Ecnassianer** [Microsoft/MixedRealityToolkit-Unity#3447]
I've noticed that MRTK uses numerous [Resources](https://docs.unity3d.com/Manual/BestPracticeUnderstandingPerformanceInUnity6.html) folders. There may be something special going on, but my understanding is that "Resources" is a [reserved folder name](https://docs.unity3d.com/Manual/SpecialFolders.html) which causes all assets in that folder to be loaded at runtime, regardless of how they are referenced. This seems inconsistent with how MRTK uses the Resources folder. MRTK's Resources folders contain READMEs, truetype fonts, toolkit icons, and a number of things that most definitely don't have a use at runtime.
 
Unity's first rule of guidance for Resources folders is [Don't Use It](https://unity3d.com/learn/tutorials/topics/best-practices/resources-folder). Is MRTK doing something to override the automatic loading of files in the Resources folders? If not, we should rename/reorganize these folders to cut down on the several mb of global memory overhead and load times that this adds. At the moment it's not a huge concern, but I'm afraid that one day we'll let a large asset (or a full family of Chinese truetype fonts) sneak into one of these folders as part of the documentation, and probably double our overhead in every project that uses MRTK. 

Unless anyone knows of a reason not to, I propose renaming all Resources folders to "Content" (it's not a great name, but it isn't reserved).

**Comment by keveleigh** [comment]
Agreed. There are some core files that we might want to include in Resources (at least, hoping to spark discussion on that 😄), but I've noticed recently as well that we do have several non-runtime-related files (icons, etc, like you listed) that don't belong in the folder.

**Comment by davidkline-ms** [comment]
Contents of the Resources folder is for content that needs to be in the package (not necessarily loaded) so that it can be dynamically utilized in the application.

There _may_ be some reasonable files for us to provide that way, but we _definitely_ need to document what and why. In fact, let's open a request for feedback issue and advertise for community insights on slack.

**Comment by JonathanPalmerGD** [comment]
To add some context: Resources folder gets made into a separate Unity AssetBundle at the start. This means if we heavily utilize the resources folder, then it is always accessible and either always partially loaded or in memory.

The Resources folder isn't terrible to use or entirely antiquated yet. It's still good in small doses.

**Comment by davidkline-ms** [comment]
@JonathanPalmerGD, agreed. The primary issue here is that the vast majority of the Resources folder contents would not be dynamically loaded by an application.

The size savings was not monumental, though following standard practices is always a good thing.
