### ISSUE TITLE
Selection not working in new vNext project

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#3456]
## Overview
This may be me missing a configuration step, but when I attempt to interact with the Example projects (any of them) using the default / unchanged configuration, I see the following upon running:

1. In the Unity Game window I get no interactivity with either an attached Xbox One controller (updated to latest firmware, etc.), mouse or keyboard.

2. If I set up Holographic mode (Simulate in Editor or Remote to Device -- HoloLens), In the editor I still get no interaction with the mouse, with the Xbox I can move but not select. On the device I can also move around but select gestures do not work.

3. If I deploy to the HoloLens gestures work and I can select.

## Expected Behavior
Selection works by default, at least in Holographic Simulation mode.

## Actual Behavior
No ability to select.

## Steps to reproduce
_(Links to sample github project preferred)_
This is what I get from the dev branch project with all lastest changes.

## Unity Editor Version
2018.3.5f1

## Mixed Reality Toolkit Release Version
mrkt_development latest

**Comment by keveleigh** [comment]
Looks like there's a Unity issue about this, tracked at https://issuetracker.unity3d.com/issues/hololens-interactionsourcestate-dot-selectpressed-is-false-when-air-tap-and-hold.

There's also a PR open to workaround this issue for remoting to a device, but it doesn't appear to fix the editor simulation case: #3496

**Comment by davidkline-ms** [comment]
We believe we have a fix (workaround for the issue that @keveleigh mentioned above) in v2 beta 2. If you are still seeing the issue, please reactivate this issue,.

Thanks!

**Comment by wiwei** [comment]
I think that this issue is still alive:

https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3909

I'm following up to see what happened to the true fix (i.e. not the workaround that was checked in to MRTK which was removed recently). This was supposed to have been fixed at the Unity layer or below.
