### ISSUE TITLE
Spectatorview preview: iphone does not trigger hololens camera

### ISSUE THREAD

**Issue by zhaoyh630** [microsoft/MixedRealityToolkit-Unity#3463]
## Overview
I'm using the HoloToolkit spectator view (preview), i did everything following the instruction, but when i run the app on both hololens and iPhone, the camera on HoloLens won't be triggered. I feel that iPhone did not even send a ping message to HoloLens since i got the error: (I'm using HoloToolkit 2017.4.3.0, Unity 2017.4.20f2 LTS)

2019-02-15 16:32:05.508713-0500 SpectatorView[11478:6313086] [si_destination_compare] send failed: Invalid argument
2019-02-15 16:32:05.508755-0500 SpectatorView[11478:6313086] [si_destination_compare] send failed: Undefined error: 0
2019-02-15 16:32:05.508775-0500 SpectatorView[11478:6313086] [si_destination_compare] send failed: Invalid argument
StartAsClient Discovery listening
UnityEngine.Networking.NetworkDiscovery:StartAsClient()
HoloToolkit.Unity.Preview.SpectatorView.SpectatorViewNetworkDiscovery:ManualStart()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

StartAsServer Discovery broadcasting
UnityEngine.Networking.NetworkDiscovery:StartAsServer()
HoloToolkit.Unity.Preview.SpectatorView.NewDeviceDiscovery:ManualStart()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.
UnityEngine.Networking.NetworkDiscovery:StartAsServer()
HoloToolkit.Unity.Preview.SpectatorView.NewDeviceDiscovery:ManualStart()

## Actual Behavior
The hololens camera won't be triggered anyway. They are on the same network.

## Unity Editor Version
Unity 2017.4.20f2 LTS

## Mixed Reality Toolkit Release Version
HoloToolkit 2017.4.3.0

**Comment by zhaoyh630** [comment]
Actually, i found that it was not the iPhone end's problem. When i used unity editor to simulate hololens, it could receive the broadcast from iPhone. But when it launched on HoloLens, HoloLens never received it. Is there any setting on HoloLens that i ignored?

**Comment by MarjanPl** [comment]
You might find this helpful:
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3107

**Comment by chrisfromwork** [comment]
It may be worth checking what permissions you have enabled in the HoloLens appxmanifest. UNET may only require the basic internet permission, but enabling the internetClient and internetClientServer capabilities may be needed (https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations )

If you are building the unity generated solution in visual studio, you should also check that the capabilities you have declared in unity end up appearing declared in the visual studio solution's appxmanifest. I have had mixed experiences where sometimes new permissions don't get carried over without deleting the visual studio solution's directory and doing a clean rebuild in unity.

**Comment by shxutoki** [comment]
I have the same problem. @chrisfromwork I tried your solution but it doesn't work.


2019-03-06 10:19:48.326615+0900 ProductName[6702:14425684] [Technique] World tracking performance is being affected by resource constraints [0]
2019-03-06 10:19:50.877324+0900 ProductName[6702:14425399] [si_destination_compare] send failed: Invalid argument
2019-03-06 10:19:50.877388+0900 ProductName[6702:14425399] [si_destination_compare] send failed: Undefined error: 0
2019-03-06 10:19:50.877407+0900 ProductName[6702:14425399] [si_destination_compare] send failed: Invalid argument
DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.
UnityEngine.Networking.NetworkDiscovery:StartAsServer()
HoloToolkit.Unity.Preview.SpectatorView.NewDeviceDiscovery:ManualStart()

[ line 485] 
(Filename:  Line: 485)

**Comment by chrisfromwork** [comment]
@shxutoki is this an exception stack? If its only the console output compared to an exception stack, can we get the full log file? (https://docs.unity3d.com/Manual/LogFiles.html ) Also, is this output when running on the iPhone or HoloLens device?

@danielescudero and @maluoi have either of you ever seen issues similar to this when setting up the server when using UNET?

Thanks!
-Chris

**Comment by Yoyozilla** [comment]
Please reopen your issue in our new spectator view GitHub Repo:
https://github.com/Microsoft/MixedReality-spectatorview
