### ISSUE TITLE
Spectator Preview Build Error QRTracker

### ISSUE THREAD

**Issue by mtedlin** [microsoft/MixedRealityToolkit-Unity#3509]
## Overview 
Trying to build the Holotoolkit Preview for SpectatorView first on hololens then to a iPhone. When trying to build to a selected folder I receive these errors.

##Errors when building Hololens Spectator preview
- Assets\HoloToolkit-Preview\QRTracker\Scripts\SpatialGraphCoordinateSystem.cs(83,40): error CS0234: The type or namespace name 'Preview' does not exist in the namespace 'Windows.Perception.Spatial' (are you missing an assembly reference?)

- Photo
![spectatorviewqrtracker](https://user-images.githubusercontent.com/37837160/53271494-a4e91100-36bc-11e9-970c-a8a0a6c738fd.PNG)

- UnityEditor.BuildPlayerWindow+BuildMethodException: 4 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x0020e] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:181 

## Unity Editor Version
Unity 2017.4.21f1

## Mixed Reality Toolkit Release Version
HoloToolkit-Unity-Preview-2017.4.3.0
HoloToolkit-Unity-2017.4.3.0-Refresh

**Comment by hayalk** [comment]
Just delete the QRTracker folder. It's not needed for the Spectator Preview.

**Comment by mtedlin** [comment]
Hello,

I appreciate you getting back with me. So to build spectator on both the hololens and the iPhone to be able to communicate in spectator mode you do not need the QRTracker folder ?

Regards,

**Comment by hayalk** [comment]
Yeah. QRTacking is never used. They use a ARUCO marker to get the pose of the iphone and that's through OpenCV.

**Comment by Yoyozilla** [comment]
Please reopen your issue in our new spectator view GitHub Repo:
https://github.com/Microsoft/MixedReality-spectatorview
