### ISSUE TITLE
[MRTK v2 Beta 2] Missing script in SpatialAwarenessMeshDemo scene

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/MixedRealityToolkit-Unity#3516]
## Overview
Missing script in SpatialAwarenessMeshDemo scene
![2019-02-24 08_42_36-inspectorfieldsexample cs - microsoft visual studio](https://user-images.githubusercontent.com/13754172/53302170-3e750780-3810-11e9-9320-4833e936f7b1.png)

## Steps to reproduce
1. Create a new Unity project 
2. Import Microsoft.MixedReality.Toolkit.Unity.Foundation-v2.0.0-Beta2.unitypackage and Microsoft.MixedReality.Toolkit.Unity.Examples-v2.0.0-Beta2.unitypackage
3. Open SpatialAwarenessMeshDemo scene

## Unity Editor Version
2018.3.2f1

## Mixed Reality Toolkit Release Version
v2.0.0 Beta 2

**Comment by davidkline-ms** [comment]
Thanks for the report! Will investigate asap.

**Comment by davidkline-ms** [comment]
On the surface, this looks like an old script that is not required.
