### ISSUE TITLE
Hololens2 support

### ISSUE THREAD

**Issue by MarjanPl** [microsoft/MixedRealityToolkit-Unity#3518]
Now for the burning question:
 Now that HoloLens 2 was unveiled, will Unity support it? Will MRTK support it? As this is a MS GH: Did you have your hands on the device already?
Strangely enough Tim Sweeney from Epic was on the stage. No mention of unity (couldn't even see the logo on the background screen)

**Comment by davidkline-ms** [comment]
MRTK v2 will 100% support HoloLens 2. We will be adding features to the mrtk_development branch in the coming weeks.

Thanks!

**Comment by benjamincoven** [comment]
And concerning the former Holotoolkit?

A migration to MRTK vNext on existing projects seems straightforward.

**Comment by davidkline-ms** [comment]
HoloToolkit is being retired and is not planned to receive support for HoloLens 2 features. 

MRTK v2 is our platform for HoloLens 2. As long as UNET is supported by Unity, there shouldn't be an issue using it in MRTK v2 projects.

Hope this helps!

**Comment by benjamincoven** [comment]
But are Hololens 1 features (spatial mapping, gesture recognition for airtap,...) that are curently avaible in the Holotoolkit will work on Hololens 2 device. Is a project currently built for Hololens 1 will immediatly work on Hololens 2 (except the need to re-build for ARM).

Also is the companion app Hololens Commander will work with Hololens 2.

Thank you.

**Comment by Yoyozilla** [comment]
Please see roadmap for HoloLens 2 support :) 
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Roadmap.md

You may have to fix some outdated/deprecated API between HoloLens 1 and HoloLens 2, also from updating from older version of unity to 2018.2/2019 but I don't imagine there are anything stopping you from targeting HoloLens 2 with your existing HTK project! we do however recommend that you move to MRTK V2 to take advantage of all the new capabilities that will likely also improve your app experience!

**Comment by benjamincoven** [comment]
Thank you for your link, we missed it and it helps us to plan ours devlopments.

Sorry to have focused on this question but we have several projects deployed to our customers and we have to know if a migration to the Hololens 2 with the same features will be free (only re-build for ARM) or paid (MRTK migration). We have some very old projects that was done in Unity 5.3 and that are still used today, despite the fact we do not maintain them anymore. Some customer doesn't want to pay for an update of their application with the new Hololens features but they have already pre-ordered many Hololens 2. We have also to plan on our active projects which one will be migrated and when.

If you have any additional information, we would be happy to have it.

**Comment by wiwei** [comment]
Closing this out, I think that this question has been answered.
