### ISSUE TITLE
Upgrade to Unity 2019.2 causes one ASMDEF to throw an error

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#3521]
## Overview
When upgrading to Unity 2019.2 MixedRealityToolkit.Providers.OpenVR.asmdef reports an error:
"Platform name 'LinuxStandalone32' not supported."

## Temporary fix
Open the ASMDEF file and remove the LinuxStandalone32 entry

# Long term fix
Unity Case 1129911

## Mixed Reality Toolkit Release Version
any

**Comment by davidkline-ms** [comment]
Thanks for the report!

**Comment by wiwei** [comment]
Thanks @Alexees for fixing this! Going through old issues and closing this one out.
