### ISSUE TITLE
[Question] Will MRTK halt at Unity 2018.4 in favor of UNET one way or another?

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3522]
With Unity 2018.3, UNET related classes already start showing up as deprecated. The blog post says 2018.4 TLS will be the last version supporting this. A new solution as simple as UNET is still in development.
Will the Toolkit halt at 2018.4, or advance no matter what?

**Comment by davidkline-ms** [comment]
MRTK v2 will support Unity 2018.4 when released. We will also be supporting Unity 2019 as it is released.

Specific MRTK functionality and feature support may vary between the version of Unity being used.

I hope this helps.
