### ISSUE TITLE
Airtap\Select not working in Emulator when Visual Controller Profile is not present

### ISSUE THREAD

**Issue by krishnan-unni** [microsoft/MixedRealityToolkit-Unity#3524]
## Overview
When you create a new project and apply your own custom profiles , if you dont apply the Visual Controller Profile in the Input System Profile then Airtap does not work in the emulator (not sure about real device as I dont have one)

## Expected Behavior
Airtap should work in emulator when Visual Controller Profile is not present

## Actual Behavior
Airtap not working in Emulator

## Steps to reproduce
Create a new project. Get MRTK toolkit.
Create Custom profiles.
In the Input System Profile, assign Visual Controller Profile to None.
Add actions and maping for Hololens Airtap in the Controller mapping.
Create a sript and handle the Tap with a Point Click Handler.
Build and Run it in Emulator
Airtap does not work (wont trigger the event).

I tried with both mrtk_development and the latest Beta 2.0.0 v2 unity package from here: https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/v2.0.0-Beta2
I was able to reproduce it in both. If you simply set the Visual Controller Profile to None in the Input System Profile Airtap won't work. Once you set that to the Default profile or a new one it will work fine again.

 I have the project uploaded here: 
https://github.com/krishnan-unni/MRTK-101

## Unity Editor Version
2018.3.6f1
## Mixed Reality Toolkit Release Version
mrtk_development branch and Beta 2.0.0 v2 unity package release

**Comment by davidkline-ms** [comment]
thank you @krishnan-unni ! we will investate asap
