### ISSUE TITLE
Preview: build errors related to System.Numerics

### ISSUE THREAD

**Issue by Nakda** [microsoft/MixedRealityToolkit-Unity#3529]
## Overview
Can't build the Unity project when the Preview package is imported. Generated errors come from `SpatialGraphCoordinateSystem.cs`, and seems related to `System.Numerics` namespace.

## Expected Behavior
Unity project should build successfully.

## Actual Behavior
The build fails even if we are not actually using the scripts embedded in the Preview package. Unity's output is the following:
```

> Error building Player because scripts had compiler errors.
> Build completed with a result of 'Failed'.

```

## Steps to reproduce
Import the lastest HoloToolkit version (2017.4.3.0-Refresh) including related Examples and Preview packages.
Build the Unity project targeting UWP and using **IL2CPP**.

## Unity Editor Version
2017.4.21f1

## Mixed Reality Toolkit Release Version
HoloToolkit 2017.4.3.0-Refresh

## Screenshot
![image](https://user-images.githubusercontent.com/25755503/53489218-eb5db780-3a90-11e9-8da7-c6c947161d6f.png)

**Comment by Alexees** [comment]
Potential fix: Replace the using directive "using System.Numerics" with "using UnityEngine"

**Comment by Nakda** [comment]
> 
> 
> Potential fix: Replace the using directive "using System.Numerics" with "using UnityEngine"

This won't work. 

The `SpatialCoordinateSystem` class from `Windows.Perception.Spatial` is expecting a `System.Numerics.Matrix4x4`, not a `UnityEngine.Matrix4x4`. Those types are not interchangeable.

**Comment by chrisfromwork** [comment]
We likely need to stub out these System.Numerics types to only be available for uwp/windows platform development (All types behind a combination of UNITY_WSA and WINDOWS_UWP macros). Are you hitting this issue when building for iOS? I would guess that these types resolve when building for uwp/HoloLens?

@Yoyozilla do we have a stance on whether or not someone at Microsoft will work on a fix for this old preview code when a refactor is occurring to get a new qr tracking experience into the MRTK? If so, can we get a label added and assign this issue to an owner?

**Comment by chrisfromwork** [comment]
Assigning to @Yoyozilla and adding a legacy label to try and get more traction on the issue

**Comment by Nakda** [comment]
@chrisfromwork The issue is actually occuring when building for HoloLens (UWP).

**Comment by chrisfromwork** [comment]
What windows sdk are you using? If you open Unity's Build Settings, what's listed for Target SDK Version and Minimum Platform Version?

**Comment by Nakda** [comment]
@chrisfromwork 

In my current configuration, I have no "Minimum Platform Version" property.
Target Windows SDK is v10.0.17763.0
Unity version: 2017.4.21f1
Scripting Runtime: .NET 4.6
Scripting Backend: IL2CPP

**Comment by y3lousso** [comment]
Exactly the same problem here.
Did you find some kind of quick fix for it ?

Target Windows SDK is v10.0.17763.0
Unity version: 2017.4.19f1
Scripting Runtime: .NET 4.6 Experimental
Scripting Backend: IL2CPP
API Compatibility : .NET 4.6

**Comment by Yoyozilla** [comment]
QR tracking was a beta feature and was only expected to work with specific version of the SDK.
I would suggest wait a few days for the updated QR feature :)
