### ISSUE TITLE
IInputClickHandler.OnInputClicked unreliable after device falls asleep

### ISSUE THREAD

**Issue by FreakTheMighty** [microsoft/MixedRealityToolkit-Unity#3530]
## Overview
The `IInputClickHandler.OnInputClicked` is not always called after the device is woken from sleep.

## Expected Behavior
After the device is turned on and the app is brought into the for ground the click handler should fire everytime and user taps the associated object.

## Actual Behavior
If the app is put into the background and the device is turned off the next time the app is brought into the foreground, `OnInputClicked` fires unreliably.

## Steps to reproduce

* Clone https://github.com/FreakTheMighty/AirTapTest
* Build and run app
* Airtap on each cube. Note that the respective click handlers are responsive and the cubes change from grey to green
* Background the app by blooming then shut the hololens for ~10 seconds
* Turn the HL back on and open the app by launching on the existing app window
* Note, you should not see a splash screen, the app should be launched from a suspended state
* Airtap the `IInputClickHandler` cube. Note that it no longer responds to all click events

## Unity Editor Version
2018.2.18f1
## Mixed Reality Toolkit Release Version
2017.4.3.0

**Comment by jtomizuka** [comment]
Did this get solved with MRTK v2?

**Comment by jtomizuka** [comment]
We may take your test code and try updating. Thanks!

**Comment by Yoyozilla** [comment]
@FreakTheMighty  @jtomizuka   does this issue repro on v2?

**Comment by Yoyozilla** [comment]
Please reopen if the issue repros.

**Comment by FreakTheMighty** [comment]
Just out of curiosity, is the official position that the HoloLens Toolkit V1 is completely end of life with no plans for support?
