### ISSUE TITLE
Some objects not cleaned up when closing the scene

### ISSUE THREAD

**Issue by genereddick** [microsoft/MixedRealityToolkit-Unity#3539]
## Overview
When running a project in the editor using Holographic Simulation, on stopping the project it throws an error (see below). I can't tell if this error has any residual effect, but Holographic Simulation is extremely buggy for me (slow to close, freezes, crashes sometimes) so possible it is related.

## Expected Behavior
No errors.

## Actual Behavior
Error:
Some objects were not cleaned up when closing the scene. (Did you spawn new GameObjects from OnDestroy?)
The following scene GameObjects were found:
Spatial Awareness System
WindowsMixedRealitySpatialMeshObserver

## Steps to reproduce
_(Links to sample github project preferred)_
This happens to me with a, more or less, default project, using latest vNext code.

## Unity Editor Version
2018.3.6f1

## Mixed Reality Toolkit Release Version
vNext

**Comment by davidkline-ms** [comment]
this looks like something we fixed in one of our branches. I will confirm that it is fixed in the current mrtk_development branch.

Thanks!

**Comment by davidkline-ms** [comment]
identified at least one likely cause

                if (observedObjectParent != null)
                {
                    observedObjectParent.transform.DetachChildren();
                }

the above is missing Destroy(observedObjctParent)

**Comment by davidkline-ms** [comment]
it _looks_ as if the Spatial Awareness System game object _should_ be getting cleaned up. will investigate asap.

Thanks again for the report!

**Comment by Yoyozilla** [comment]
@davidkline-ms  fixed?

**Comment by wiwei** [comment]
I haven't seen this particular error in a while - feel free to reopen if this is still happening
