### ISSUE TITLE
[Plan of Record] Namespace simplification

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#3546]
## Overview
The current set of namespaces in MRTK v2, while having the benefit of closely matching the source tree is causing significant confusion with customers.

This proposal is to change the namespaces to be laid out more feature focused (like the .NET framework) than tree location focused.

For example:
Microsoft.MixedReality.Toolkit.Core.Interfaces.InputSystem contents will move to the new Microsoft.MixedReality.Toolkit.Input namespace. The same will hold for *Core.EventDatum.InputSystem.

More complete details:

Microsoft.MixedReality.Toolkit is the root namespace underneath which the following will be parented:

- Boundary
- Diagnostics
- Editor
- Input
- Networking or Sharing (coming later)
- SpatialAwareness
- Teleport
- Utilities

There will be some (not many) child namespaces for the above.

**Comment by maluoi** [comment]
Oh my god yes please! 💯 Shorter namespaces mean better code discoverability, along with being a lot more pleasant to read :)

**Comment by StephenHodgson** [comment]
I thought we removed the *Core* part a long time ago?

**Comment by davidkline-ms** [comment]
We did not. We just moved some namespaces around. this is a large scale simplification effort.
