### ISSUE TITLE
WindowsMixedRealitySpatialMeshObserver errors at edit-time in 2019

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#3551]
## Overview
At edit-time in Unity 2019, WindowsMixedRealitySpatialMeshObserver throws the following error:

![image](https://user-images.githubusercontent.com/3580640/53608955-9e094500-3b79-11e9-8211-d52db80f35ec.png)

Likely, we should make sure not to try creating and configuring a platform observer when not running.

## Unity Editor Version
2019.1.0b3

## Mixed Reality Toolkit Release Version
Latest mrtk_development

**Comment by davidkline-ms** [comment]
i'll get on these changes asap. thanks for finding them!

**Comment by Yoyozilla** [comment]
@davidkline-ms  fixed?

**Comment by keveleigh** [comment]
Should be fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5778
