### ISSUE TITLE
Setting enableboundarysystem to false in config does nothing

### ISSUE THREAD

**Issue by jamesashley1** [Microsoft/MixedRealityToolkit-Unity#3558]
## Overview
programmatically setting EnableBoundarySystem to false in config profile does nothing
## Expected Behavior
Flag should be false
## Actual Behavior
Flag stays true because it is tied to a different private member, enableInputSystem
## Steps to reproduce
_(Links to sample github project preferred)_
        /// <summary>
        /// Enable and configure the boundary system.
        /// </summary>
        public bool IsBoundarySystemEnabled
        {
            get { return boundarySystemType != null && boundarySystemType.Type != null && enableBoundarySystem && boundaryVisualizationProfile != null; }
            internal set { >>>>>enableInputSystem [wrong member]<<<<< = value; }
        }
## Unity Editor Version
2018.3.0f2
## Mixed Reality Toolkit Release Version
v2.0.0 beta 2

**Comment by davidkline-ms** [comment]
good catch, thanks!

**Comment by davidkline-ms** [comment]
fix merged into mrtk_development
