### ISSUE TITLE
MRTK 2 Question: Is it possible to emulate the Hololens in the Unity Editor as in Holotoolkit

### ISSUE THREAD

**Issue by benjamincoven** [Microsoft/MixedRealityToolkit-Unity#3559]
## Overview

Hello everyone,

I would like to know if in the MRTK v2 Beta 2, it is possible to emulate Hololens input in play mode with the Unity editor as it is possible with the Holotoolkit with the keyboard+mouse.

If yes I couldn't make it working, I have activated default Input System service and tried in various scene like ManipulationExemple.

## Unity Editor Version

2018.3.4

## Mixed Reality Toolkit Release Version

V2.0.0 Beta 2

**Comment by lukastoenneMS** [comment]
AFAIK the articulated hand support has not been merged into the public repo yet. Once that has happened the hand simulation should also be working. Sorry for the inconvenience.

**Comment by benjamincoven** [comment]
Thank you very much for your answer.

This raises an another general question that I have. You said that the hand simulation should work when articulated hand support will be avaible. By "hand simulation" you mean as it is actually in the Holotoolkit? Or this will be a new one? 

In fact my question is: are all high-level features in the Holotoolkit like Spatial Mapping, Anchor management, Tap to place or hand simulation, will be rewrote from scratch with the MRTK2 or is the MRTK2 only a change on the mid-level API between the Device API and the High-Level features previously mentionned. In the second case, this would mean that a project built on High-Level features with the Holotoolkit will be very easy to migrate to the MRTK 2.

By asking this question, I assume that all High-Level features in the Holotoolkit will be avaible in the MRTK 2. it seems obvious for me but it is not clear since it does not appear in the roadmap and it is currently missing.

**Comment by jimmy12day** [comment]
I had try emulator in Unity2018.3 with the MRTK2 SDK and it is working as basically display the Hololens1 stuffs. Will hololens2 development use the same emulator or any upgrade for it?

**Comment by keveleigh** [comment]
This is now supported in RC1 via the [Input Simulation Service](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSimulation/InputSimulationService.html).

**Comment by elvirus839** [comment]
@keveleigh I have been trying to use Input Simulation Service in unity editor, but I am unable to navigate through the scene on the HandInteractionExamples! And in unity I am getting the following error: 

![image](https://user-images.githubusercontent.com/5313106/58466818-c1bd3680-813a-11e9-804d-0ba8bb78d52e.png)

any idea on how to get past that?
