### ISSUE TITLE
Performance: Interactable Awake() extremely slow

### ISSUE THREAD

**Issue by kircher1** [microsoft/MixedRealityToolkit-Unity#3562]
## Overview
Creating an Interactable is extremely slow. There are two sub-issues here:

* Interactable.OnAwake calls a helper function, InteractableEvent.GetEventTypes(), which walks through *all types* in all loaded assemblies, looking for types which implement RecieverBase.
* Furthermore, SetupThemes() is also an extremely slow function. I haven't dug into this to see exactly where time is being spent though.

In my project and on my machine, GetEventTypes() takes around 40ms and SetupThemes() takes slightly longer. That is unacceptable for performance and results in a noticeable frame glitch. 

Also note, that time spent is just for instantiating a _single_ interactable. In my project, many interactables could be loaded throughout the lifetime of the app or even in a single frame.

## Expected Behavior
Interactable should not cause frame glitches.

## Actual Behavior
Interactable causes frame glitches when loaded.

## Steps to reproduce
* Add Profiler.BeginSample()/EndSample() to the InteractableEvent.GetEventTypes method.
* Create some interactables in a scene
* Observe spikes in the frame profiler

![interactableperf](https://user-images.githubusercontent.com/20366429/53761820-4f122700-3e7b-11e9-9c6c-77eea70b3d3c.png)

## Unity Editor Version
2018.3.6

## Mixed Reality Toolkit Release Version
Beta 2

**Comment by kircher1** [comment]
This issue is only reproducable when an Interactable is instantiated at runtime, i.e. I don't see any sort of frame spike on frame 0 from Interactables that were already added to the scene...

Attached is a script that can be used to generate an Interactable every second. I used this in the InteractablesGallery scene with the Balloon prefab. You can see a consistent frame spike every second if this script is running. 

[InteractableGenerator.zip](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/2928316/InteractableGenerator.zip)

**Comment by davidkline-ms** [comment]
@kircher1, thanks for the report! we will investigate and advise / fix

**Comment by cre8ivepark** [comment]
@killerantz for visibility

**Comment by kircher1** [comment]
This appear to be fixed in RC1 Refresh.
