### ISSUE TITLE
Duplicates of if you use a new camera

### ISSUE THREAD

**Issue by markgrossnickle** [microsoft/MixedRealityToolkit-Unity#3564]
## Overview
Running a scene with a newly created camera causes duplicate game objects to be created: 
![image](https://user-images.githubusercontent.com/16213480/53773774-ffe2eb00-3ea8-11e9-9de9-9fc6d2220d55.png)

## Expected Behavior
A single camera and cursor should be in the scene. 

## Actual Behavior
Duplicate playspaces, cameras and cursors are created.

## Steps to reproduce
1. Create a new scene
2. Delete Main Camera
3. Right click in hierarchy and create new camera.
4. Click MRTK -> Configure and select a profile
Note, the scene is fine at this point.  
5. Click run in Unity. 

Now you will see the following error in the logs:
'Too many event systems in the scene. The teleport system requires only one.'

You will also see duplicate cursors/cameras:
![image](https://user-images.githubusercontent.com/16213480/53773909-8e576c80-3ea9-11e9-8373-049719e629ea.png)

## Unity Editor Version
2018.3.6f1

## Mixed Reality Toolkit Release Version
I am not sure how to tell? I just have the latest from github release branch as of today.

**Comment by davidkline-ms** [comment]
Thanks for the report @markgrossnickle !

**Comment by keveleigh** [comment]
I wasn't able to repro this on the latest. Some work has been done to make our main camera detection and asset creation more robust, but please reopen if you're still able to repro.
