### ISSUE TITLE
Proposal: MixedRealityToolkit.Providers identification by ASMDEF

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#3566]
## Overview
In the DefaultMixedRealityRegisteredServiceProvidersProfile, Configurations are identified by a Runtime Platform enum. At the same time, the corresponding classes are packed under ASMDEF configurations in their SDK specific folders ( MixedRealityToolkit.Providers\Oculus, MixedRealityToolkit.Providers\OpenVR, ...).
The RegisterService method in MixedRealityToolkit.cs checks for null first and for platform availability second. This results in errors printed on Android as 5 of the services are not available code wise (ASMDEF).

Swapping the checks solves the problem, which leads me to the conclusion, that the platform check currently avoids all null exceptions. This means the check could very well just be a null check, since the ASMDEFs already define on which platforms which SDK or service is available, with the enum check completely removed. It does not make sense to have code compiled out but be able to chose the corresponding platform still.
Maybe it's possible to show the configuration of the ASMDEFs they reside in along with the services in the Profile as read-only.

**Comment by StephenHodgson** [comment]
Assembly definitions should generally be marked as any platform, unless it's editor only. Also, they [don't define runtime components](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html).

> Assembly definition files are not build system files
Note: The assembly definition files are not assembly build files. They do not support conditional build rules typically found in build systems.
>
>This is also the reason why the assembly definition files do not support setting of preprocessor directives (defines), as those are static at all times.

Likely this is a bug with the was the assembly definitions are setup

**Comment by Alexees** [comment]
@StephenHodgson Then I don't understand why they provide the granularity for platform specifics. Classes like the spatial mesh observer do not appear on any other platform than UWP, so why not excluding it on any other platform, just makes sense.
You should check out the subfolders of MixedRealityToolkit.Providers, as they are totally setup like this.

Sure they can not be combined with preprocessor directives, but if they're pure and the code referencing them is wrapped in parallel, why not?

**Comment by StephenHodgson** [comment]
I'm honestly not sure, as I didn't create those assembly definitions for those folders. When I initially setup the project they were created properly, so I'm unsure as to how they may have become broken.

As for why Unity setup the Assembly Definitions to behave this way, it more akin to which assemblies will get built. You can build an assembly for a specific platform without problems, but if that assembly is trying to call on another assembly and that method is missing (maybe bc that assembly wasn't built for that platform), then it'll fail at runtime (which is likely what you're running into).

**Comment by davidkline-ms** [comment]
Thanks @Alexees, we'll definitely look into this.

**Comment by michael-house** [comment]
Ideally you'd have all code for a specific platform in a single directory. Then you'd put an ASMDEF into that directory. This will cause Unity to compile that directory as a separate DLL and only include it for the platforms specified. ASMDEFs are also great for ensuring you're not cross referencing separate submodules, or referencing up (i.e. something in a core library using source defined in a Unity library).

Use caution with them though. If you drop dozens into a Unity project, you'll have dozens of DLLs that need compiling and thus dozens of csproj files in Unity's generated Visual Studio Solution. This can slow down the performance of opening the solution, debugging, etc.

You also need to take care, as any Editor scripts/directories that were automatically put into a separate DLL/project before will have to be manually taken care of (i.e. with yet another ASMDEF).

**Comment by Alexees** [comment]
I wanted to add that I was not even sure how Services or Devices are distinguished in the toolkit. By platform? by SDK? By additional compiler directives? What if I want to support Oculus Go and android mobile phones. Then I would need to distinguish between them by Oculus SDK availability, but that kind is not available right now.
additionally, there's a lot of enum's used, which need to be extended for new platforms etc. they could very well be replaced by ScriptableObjects. those could then provide the logic for the differentiation.

**Comment by SeakingSubHunter** [comment]
Hi guys.  I'm glad i  found this thread because i thought it was something i was doing wrong.  Without a probable solution....is there a way i can just turn off the developer messages in the HMD?  my concrete type message isnt really effecting anything anyway.

**Comment by Alexees** [comment]
> Thanks @Alexees, we'll definitely look into this.
@davidkline-ms I'm cleaning up my issues. Any news on this?
