### ISSUE TITLE
Null Reference errors raised in a Platform build of MRTK

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#3567]
## Overview
When building a MRTK solution in the editor, this can be run and tested without issue in the editor.
However, when it is built for a platform, Unity raises multiple "Null Reference Error" exceptions with limited detail as to the cause

## Expected Behavior
MRTK projects should run without issue.

## Actual Behavior
As described, multiple errors are reported to the development console in either Standalone or UWP

## Steps to reproduce
1. Create a new project
2. Import MRTK
3. Create / update the sample scene with MRTK, just hit configure -> MRTK
4. Save scene
5. Build project for Standalone
6. Build project for UWP
7. Run the projects

## Unity Editor Version
2018.3.6

## Mixed Reality Toolkit Release Version
MRTK Beta 2

##Additional Data
Standalone Screenshot
![image](https://user-images.githubusercontent.com/1793042/53807079-8c8fb680-3f46-11e9-88d5-9214423aefc1.png)

UWP Screenshot
![image](https://user-images.githubusercontent.com/1793042/53807092-96191e80-3f46-11e9-9ed1-b1072cc634be.png)

Standalone log (UWP doesn't output a log, as far as I can see)

```
WARNING: Shader Unsupported: 'Legacy Shaders/Diffuse' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Mixed Reality Toolkit/Standard' - Pass 'Meta' has no vertex shader
UnloadTime: 86.969000 ms
Unable to register a service with a null concrete type.
UnityEngine.DebugLogHandler:Internal_Log()
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:RegisterService(Type, SupportedPlatforms, Object[]) (at E:\Development\MRTK-Blank\Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:623)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:InitializeServiceLocator() (at E:\Development\MRTK-Blank\Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:259)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:InitializeInstance() (at E:\Development\MRTK-Blank\Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:443)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:Awake() (at E:\Development\MRTK-Blank\Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:555)
 
(Filename: E:/Development/MRTK-Blank/Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs Line: 623)

Unable to register a service with a null concrete type.
UnityEngine.DebugLogHandler:Internal_Log()
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:RegisterService(Type, SupportedPlatforms, Object[]) (at E:\Development\MRTK-Blank\Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:623)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:InitializeServiceLocator() (at E:\Development\MRTK-Blank\Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:259)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:InitializeInstance() (at E:\Development\MRTK-Blank\Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:443)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:Awake() (at E:\Development\MRTK-Blank\Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:555)
 
(Filename: E:/Development/MRTK-Blank/Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs Line: 623)
```

**Comment by Alexees** [comment]
@SimonDarksideJ I had similar issues trying to run it on Android. They are related to the DefaultMixedRealityRegisteredServiceProvidersProfile:
- The class referenced here is likely ignored in the ASMDEF for the platform

See my issue here:
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3566

**Comment by StephenHodgson** [comment]
No, this is likely because the serialization of the service type in the configuration profile is corrupted

**Comment by SeakingSubHunter** [comment]
Hi Guys, i'm getting the message "unable to register a service with a null concrete type" through to my HMD in a mixed reality app i'm creating.  Is there a way of repairing this error or just removing the message from the screen.
