### ISSUE TITLE
Proposal: Remove the Mixed Reality manager and move to standalone services like the HTK

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/MixedRealityToolkit-Unity#3568]
## Overview
Based on the numerous feedback internally at MS and the adopting partners, it seems the locator pattern is too big an ask for the current development plans.

As Such, I recommend that the MRTK V2 should drop the MRTK approach built by the community members and uplift the Services to standalone services maintained within the project Scenes.

This would be more in line with partners and enterprise app developers expectations for how they should build apps.

This doesn't deteriorate the excellent work done to architect the services and the overall architecture for managing the cross-platform nature of the toolkit, but brings it back more in to line with Microsofts SDK approach and reduces friction to adoptions.

If such an Locator approach is needed in the future, I'm sure the wider community will build upon this excellent framework and deliver that capability without Microsoft needing to maintain it.

## Expected Behavior

MRTK services should operate independently in the scene as requested by MS Partners and internal staff to better facilitate the current developers used to using Unity.

Updated Architecture diagram to suit:
![image](https://user-images.githubusercontent.com/1793042/53812565-b1d6f180-3f53-11e9-90c1-bd90aff291bc.png)

This ensures a smoother adoption based on Microsoft's internal experience.

**Comment by StephenHodgson** [comment]
The core services and data models would also need to moved into the presentation layer to make the diagram more appropriate

**Comment by StephenHodgson** [comment]
Fixed it
![image](https://user-images.githubusercontent.com/13334553/53815827-4a02b580-3f17-11e9-9364-fc4596807625.png)

**Comment by davidkline-ms** [comment]
> Based on the numerous feedback internally at MS and the adopting partners, it seems the locator pattern is too big an ask for the current development plans.

The feedback received does not rule out the locator pattern. There are customers who like the pattern and customers who do not.

**Comment by SimonDarksideJ** [comment]
Fair enough, but we already had enough complexity with the one pattern and now you want to add another.
Better the MRTK settles on a single pattern and let the community deliver other options.  This will only drive up confusion rather that offer options having too many choices.

Hence the proposal to switch the base MRTK to have a single pattern that you've stated is preferred by MS customers

**Comment by davidkline-ms** [comment]
Plan of record is to implement #3545.

Thanks for the proposal, it helped to land the POR.
