### ISSUE TITLE
Text To Speech is missing in MRTK-v2.0.0-Beta2

### ISSUE THREAD

**Issue by tletie** [microsoft/MixedRealityToolkit-Unity#3569]
##MRTK-v2.0.0-Beta2 (Unity package) doesn't port over "Text to speech" feature that exist in the holotoolkit. I don't see an example or tutorial how to implement this in this new toolkit. In the previous holotoolkit we do have TextToSpeechManager.cs to use.

## Expected Behavior
Developer can just do text to speech using a port-over class TextToSpeechManager.cs
## Actual Behavior
Can't find anything similar to do text to speech
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.3
## Mixed Reality Toolkit Release Version
v2.0.0-Beta2

**Comment by davidkline-ms** [comment]
Thanks for the feedback! We will definitely look into porting that functionality

**Comment by genereddick** [comment]
I added the TextToSpeech.cs file into the new MRTK and it worked as is.

**Comment by tletie** [comment]
Is that TextToSpeech.cs different TextToSpeechManager.cs I mentioned? Can you share the script so that I can test?
Thanks

**Comment by tletie** [comment]
I think it the same. I use TextToSpeechManger.cs and it works too. Thanks

**Comment by davidkline-ms** [comment]
Thanks @genereddick and @tletie! Text-to-Speech is platform specific (windows only) as implemented in HoloToolkit,  The team will work to provide a cross platform implementation as soon as possible.

Do you feel it should be a foundational component or an extension? I can see both ways.

**Comment by genereddick** [comment]
The old code works on WMR/HoloLens and not anywhere else so my expectations for cross-platform are limited. 

I do think if it can be done in a consistent way and across enough platforms than it would be great to have it as foundational, but I think an extension is fine if the platform differences are too challenging to abstract. 

I wouldn't hold up a release for a cross-platform version in any case.

**Comment by ActiveNick** [comment]
Another alternative is to use the [Cloud TTS API](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/#pivot=start&panel=texttospeech) in Cognitive Services Speech. It won't work offline, but you'll get higher quality voices, a cross-platform SDK, and it provides consistent voices across all platforms. There is a Unity quickstart [sample here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/text-to-speech).

**Comment by ChristopherGoe** [comment]
Hey, April 2020 and this is still not implemented or atleast I didn't found it in the current MRTK versions. Are there any plans on adding that? I had some hard time finding the old holotoolkit because most links are dead.

**Comment by nonlin** [comment]
I've started adding this to Unreal but it seems the release version I pulled from once compiled has...
A. an error which is easily fixed but makes me wonder how the error is on release branch
B. Just doesn't work.

I'm not sure why once a fresh pull of source setup, generated and compiled breaks MRTK 2 for hololens. 

I'll keep digging into it to see if I can add TextToSpeech support for Unreal.
