### ISSUE TITLE
Cursor too small to be visible at larg(er) distances

### ISSUE THREAD

**Issue by LocalJoost** [microsoft/MixedRealityToolkit-Unity#3571]
## Overview
When the cursor strikes nothing or is at an object far away (>3 meters) it's so far it's nearly invisible

## Expected Behavior
Cursor needs to be bigger with distance

## Actual Behavior
Cursor becomes nearly invisible

## Steps to reproduce
Create an empty project, import MRTK, Configure and run

## Unity Editor Version
2018.3.6f1

## Mixed Reality Toolkit Release Version
2.0.0 beta 2

**Comment by Alexees** [comment]
@LocalJoost just checked this with the old toolkit. The distance is wrong. In the old it's 2 units, now it's 10. I go fix that.

**Comment by davidkline-ms** [comment]
we recall fixing this some time ago, if we are incorrect, plz reopen
