### ISSUE TITLE
Proposal: Integration of the Oculus GO

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#3574]
## Overview
The Oculus GO is missing, so I want(ed) to integrate it.
The contribution page explained a lot of things concerned with really big features. I didn't feel like this was such a big deal, so I just did it:

#3573 

## Unity Editor Version
Unity 2018.3.4f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by Yoyozilla** [comment]
Looks like we have our first extension!!! 
https://github.com/HoloSpaces/MRTKOculusGo

**Comment by Alexees** [comment]
@Yoyozilla Besides it being a good idea to close old issues, this one is actually not done yet. @davidkline-ms once contacted me and wanted to help get this going the right way, starting off with a call and all that. For some reason that never happened and I did not receive any answer from him ever since. I don't know what the reason is, probably a shift in priority or maybe interest, I don't know, but the repository is stale at the moment.

**Comment by Yoyozilla** [comment]
Thanks for bring this up! I will get a call scheduled asap! This is super exciting. I love your passion in the area, and the just did it attitude <3

**Comment by Alexees** [comment]
Hey @Yoyozilla,
I'm not sure with whom you wanted to get a call scheduled, but I jumped in and started working on the integration into the current MRKT.
Couple of things about the current status:

- I don't know where to put all the necessary files. The shipped controllers and visualizers for examples lie in different namespaces, hence different folder structures. Should the extensions go into a seperate structure with its own namespace?
- The controller mappings have this neat controller images and popup to define the controllers mappings. To integrate that a couple of things also need to go into the folder structures of the MRKT. Is that ok?
- Finally (for now) a new controller needs a change on the SupportControllerTypes enum, which is suboptimal for anyone who wants to create a new controller. I once started working on a System Type based implementation to remove it, but it has been killed as it introduced yet another couple of breaking changes

Would love to have someone who accompanies me here... Still a little unsatisfied of David Klines let down

**Comment by SimonDarksideJ** [comment]
You can check the Go implementation in the XRTK for reference for bringing it to MRTK.
However, I'd recommend just using the OpenVR implementation for now, which is mostly included.
https://github.com/XRTK/XRTK-Core/blob/upm/Providers/Controllers/OpenVR/OculusGoOpenVRController.cs

**Comment by davidkline-ms** [comment]
> Still a little unsatisfied of David Klines let down

@Alexees, please accept my sincere apologies. I acknowledge dropping the ball on this. Are you up for a call early next week? Monday 8/6, perhaps?

**Comment by Alexees** [comment]
@davidkline-ms apologies accepted :) Since there seams to be a working OpenVR based implementation already, do you think it would even make sense to add an Android based Version of it?
Monday 8 am sounds good, that would be 5 pm my time (CEST).

**Comment by davidkline-ms** [comment]
I do believe it would be good to investigate / add an Android OpenVR build target. I also see value in having a version that directly targets the Oculus XR SDK.

I'll send a call invite for monday. Thanks!
