### ISSUE TITLE
HandDraggable is not ported

### ISSUE THREAD

**Issue by tletie** [Microsoft/MixedRealityToolkit-Unity#3575]
## Overview
The feature HandDraggableis not ported to MRTK V2.0.0-Beta2
## Expected Behavior
In Holotoolkit, we can use this from script HandDraggable as a class under HoloToolkit.Unity.InputModule,
## Actual Behavior
I don't see it in MRTK
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.3
## Mixed Reality Toolkit Release Version
v2.0.0-Beta2

**Comment by Alexees** [comment]
Have you checked out ManipulationHandler.cs

**Comment by tletie** [comment]
Oh, Let me give it a try

**Comment by cre8ivepark** [comment]
@tletie ManipulationHandler now supports both one and two-handed manipulation. You can find the example scene here:
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.Examples/Demos/UX/TwoHandManipulation/ManipulationExample.unity

**Comment by davidkline-ms** [comment]
@tletie, as Yoon mentioned, the new manipulationhandler is the replacement for handdraggable.

We are actively working on a porting guide / feature map that will help customers discover the changes.

Please keep issues like this coming! They help us take a step back and review our documentation needs.

**Comment by tletie** [comment]
Thank you @davidkline, ManipulationHandler is the solution.
