### ISSUE TITLE
Tagalong

### ISSUE THREAD

**Issue by tletie** [Microsoft/MixedRealityToolkit-Unity#3576]
## Overview
Can't see this feature in MRTK v2.0.0-beta2
## Expected Behavior
I can use this feature in Holotoolkit under HoloToolkit.Unity namespace.
## Actual Behavior
No longer see it under MRTK
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.3
## Mixed Reality Toolkit Release Version
v2.0.0-Beta2

**Comment by Alexees** [comment]
MixedRealityToolkit.SDK/Features/Utilities/Solvers. There are quite a few that do different things, as well as tagalong (Orbital.cs or example)

**Comment by davidkline-ms** [comment]
@tletie, as @Alexees mentions, tagalong has been integrated into the solver system.

thanks!

**Comment by tletie** [comment]
@Alexees and @davidkline-ms, thank guys and sorry for delay in response.
