### ISSUE TITLE
MixedRealityInputSystem does not handle Focus events correctly

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#3577]
## Overview
Any Interactable component will suffer from incorrect handling of Focus events. If more than one pointer is involved (gaze and controller), a successful exit depends on the order the pointers enter and exit.

- The MixedRealityInputSystem will only ever call FocusEnter once on a gameobject, regardless of how many pointers entered it (pendingOverallFocusEnterSet makes sure of that). This fact makes the whole Pointer counting in the Interactable class useless.
- AddPointer and RemovePointer in the Interactable class add and remove first comes first serve. That means, if you exit focus with the pointer that entered second or later, OnFocusExit won't be called.

Either MixedRealityInputSystem calls Enter and Exit for EACH cursor, or Interactable cannot rely on a specific cursor that entered and exited.

## Expected Behavior
OnFocusExit always works

## Actual Behavior
It does not always work

## Steps to reproduce
- Gaze at an Interactable object
- Point at it with the controller
- Move the controller away
- Look away

The interactable stays in the selected state

## Unity Editor Version
2018.3.7f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by Alexees** [comment]
I'm currently debugging this and the root cause for this is that gazing is calling OnFocusEnter and Exit, but the pointing cursor is not.  The moment the gaze exits, it checks for residing cursors and since the motion controller is still focusing, SetFocus will be called with true. When when then removing the cursor, the same call is not made twice.

**Comment by Alexees** [comment]
Hm, ok:
- The MixedRealityInputSystem will only ever call FocusEnter once on a gameobject, regardless of how many gazes entered it (pendingOverallFocusEnterSet makes sure of that)
- AddPointer and RemovePointer in the Interactable class add and remove first comes first serve. That means, if it's not the same cursor that entered which exits first, the single exit call is passed, but the cursor count is still 1, because the other cursor is in the list.

Either MixedRealityInputSystem calls Enter and Exit for EACH cursor, or Interactable cannot rely on a specific cursor that entered and exited.

**Comment by Alexees** [comment]
@davidkline-ms I think this is a problem and worth a discussion:
It could be desirable to receive all Focus events for the pointers (need two for twohand activation for example). If the InputSystem was to be changed in that way, it's a question of how to handle that in an Interactable. You might want to have the choice between single focus events or every single event. This would either mean that the Interactable component needs to properly count the cursors which deriving classes can check, or using the template pattern and seal the actual Focus calls and providing apropriate methods instead. But that would mean the interface would not work anymore.
What do you think? I'd go with the former.

**Comment by Alexees** [comment]
this goes even further. inputs also have down and up. so there's a few state toggles three and the question is if they all should reliably work for each input device instead of just happening once? I'm not even sure if down and up are called for each already.
the receiving component should handle how it wants to react.

**Comment by davidkline-ms** [comment]
@alexees, thank you for the feedback! we had presumed that developers would desire only one focusenter event.

We will take a look at this for the upcoming (by end of March) release.

**Comment by Alexees** [comment]
@davidkline-ms I don't need one. But dependent on the decision, the Interactable bug has to be fixed or fix itself.

**Comment by Alexees** [comment]
It's not even that simple. When I gaze on a button AND point at it, I expect it to highlight on first enter and return on last exit. If there's just one enter and exit each, the InputSystem needs to count the pointers to make sure this is happening. And if it does, there's no reason to make the choice of receiving all or just one of each call.

**Comment by luis-valverde-ms** [comment]
@Alexees , can we close this one?

**Comment by Alexees** [comment]
@luis-valverde-ms sure, that's quite an old one
