### ISSUE TITLE
LinePointer always lags behind

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3580]
## Overview
Moving a controller around one can clearly see that the LinePointer is detached from the controller, basically lerping behind.

## Expected Behavior
The LinePointer follows the controller on the spot

## Actual Behavior
The LinePointer has some sort of lerping behind behaviour

## Steps to reproduce
Use a simple scene and watch the LinePointer

## Unity Editor Version
2018.3.7f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by Alexees** [comment]
You would think controller, raycast and linerenderer are related, but they are not. Controller orientation and raycasting happen during the same Update step, which is fine because they are initiated from the MixedRealityToolkit's Update method. However the LineRenderer runs it's own Update loop, which of course is undeterministically happening before or after the update of the controller.
In my case, it's before, that's why it lags behind.

**Comment by keveleigh** [comment]
Closed via #3581
