### ISSUE TITLE
TeleportCursor visible for one frame when not targeting a floor

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3582]
## Overview
When not hitting the floor, the TeleportCursor is still activated for a frame. the first time it's within the camera or at 0,0,0, I'm not sure.

## Expected Behavior
Shows when hitting the floor only

## Actual Behavior
Shows for one frame no matter what

## Steps to reproduce
Use the teleport function in a scene without anything

## Unity Editor Version
2018.3.7f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by keveleigh** [comment]
Fixed via #3584
