### ISSUE TITLE
Gaze cursor lerps behind virtual rotation

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3585]
## Overview
Whenever you use the analogue stick for rotation, your view gaze is left behind during that motion, probably due to smoothed movement towards the gaze center, without taking virtual rotation into account.

## Expected Behavior
the gaze stays centered

## Actual Behavior
the gaze gets thrown off when rotating

## Steps to reproduce
Just out of pure luck I used the DefaultButton Material on a floor which lets the gaze highlight the position. Then rotation clearly shows how the gaze tries to get back to view center.

## Unity Editor Version
2018.3.7f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by Alexees** [comment]
@StephenHodgson can you take a look at this?

This problem goes as follows:

- MRKT Update: updates activeSystems, FocusProvider in particular, which does the Raycasting for the pointers, hence saving world position results
- MRKT Update: updates registeredServices, including the InputSystem which performs teleportation/ rotation, hence altering the MixedRealityPlayspace
- BaseCursor Update: updates the cursor position

It does not matter if the BaseCursor updates before the MRKT Update (race condition), it will use an outdated Raycast result and therefore lerps back to its initial position before the rotation happened, only to smoothly rotate toward the new position from there.

Solution:
teleporting must happen before raycasting is performed, but I don't see how this could be easily achieved since teleporting happens during the input phase of the controllers, which is also when you probably want to do something with the raycastresults...

Another solution could be to base the raycast results on

**Comment by luis-valverde-ms** [comment]
@Alexees , I couldn't repro this. I tried adding a plane with the DefaultButton material to the HandInteractionExamples scene and running that in a WMR headset and I see no gaze cursor. I was using v2.0.0-RC1. Am I missing something? Can you add step by step instructions for reproing or a scene setup for it?

**Comment by Alexees** [comment]
@luis-valverde-ms yeah, at one point I started seeing a lot of these "one frame late" issues and my reports got mixed up.
This one is fixes with #3627
