### ISSUE TITLE
Windows Mixed Reality Motion Controllers don't appear in the editor

### ISSUE THREAD

**Issue by rabejens** [microsoft/MixedRealityToolkit-Unity#3589]
I just created an empty project with MRTK 2.0.0 Beta 2. So far I have an empty room and see my controllers, but I only see colored coordinate systems, and when going through the configuration, the controller model shows "Gizmo" which is that coordinate system.

How do I get the actual models of the motion controllers?

**Comment by davidkline-ms** [comment]
@rabejens, controller model importing is not currently available in beta 2. It is currently in active development and should be present in our next release (expected by the end of March 2019)

Thanks!

**Comment by SimonDarksideJ** [comment]
SDK level models are currently in development, to avoid complications with Newtonsoft, we've rearchitected the components to be more cross platform friendly, but still a little way to go.

However, you can easily replace the Gizmo models with your own using the Controller Visualisation configuration (under Input settings) and replace the models either globally or per SDK.  Just look at the Gizmo's prefabs and replicate it and your'll be up and running in no time

**Comment by chrisfromwork** [comment]
It's probably worth calling out that the first wave of work will enable these sdk provided controller models to show in a compiled uwp/windows application. This initial work does not address showing controller models in the editor, which had been supported with the holo toolkit.

@rabejens do you need these models for an application you are building/shipping? How important is it for these models to appear in the editor for your scenario?

**Comment by rabejens** [comment]
Oh, I am just experimenting and playing around at the moment. The “d” HoloToolkit will do for now. But good to read that this is in the works.

**Comment by chrisfromwork** [comment]
@rabejens, if you're not apposed, I will edit and repurpose this issue as providing support for controllers to appear in the editor. Then we can track updates to said work with this issue.

**Comment by rabejens** [comment]
That sounds like a good idea.

**Comment by Troy-Ferrell** [comment]
This is outdated, closing as resolved

**Comment by mr0ng** [comment]
@keveleigh do you know if there's any update on this?

**Comment by polar-kev** [comment]
A fix for OpenXR is very likely to land for 2.7 here.

**Comment by keveleigh** [comment]
Was hoping to unblock this for 2.7, but likely won't make it in for the stabilization snap. A couple blockers that we'll need to work through:

1. DotNetWinRT either needs the `TryGetRenderableModelAsync` (and related) API implemented
2. or there seems to be a bug with DotNetWinRT's support of obtaining the `SpatialCoordinateSystem` while running in the editor via an immersive headset (but not while remoting...)

fixing 2 might be easier (and should probably be done regardless) and would unblock our use of [the native MRTK's EditorMotionControllerDLL](https://github.com/microsoft/MixedRealityToolkit/tree/master/EditorMotionControllerDLL). though option 1 would be a better, more self-contained fix.

**Comment by davidkline-ms** [comment]
Fixed with the OpenXR plugin. Will not apply to v3 (via OpenXR). At runtime, models appear appropriately.
