### ISSUE TITLE
No way to set Interactable / Checkbox to checked on start?

### ISSUE THREAD

**Issue by genereddick** [microsoft/MixedRealityToolkit-Unity#3603]
## Overview
I can't seem to find any way to set an Interactable / checkbox to start checked.

## Expected Behavior
Property that allows setting checkbox to checked

## Actual Behavior
Can't find property

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.3.8f1

## Mixed Reality Toolkit Release Version
vNext Beta 2

**Comment by kolodi** [comment]
Achievable like this:
1. in `MixedRealityToolkit.SDK\Features\UX\Interactable\Scripts\Interactable.cs` script
add a field `public int DefaultDimension = 0;`
2. at the end of `Awake()` method set the dimension index like this: `SetDimensionIndex(DefaultDimension);`
3. to expose it in inspector add this 2 lines in `MixedRealityToolkit.SDK\Inspectors\UX\Interactable\InteractableInspector.cs` inside `RenderCustomInspector()` method:
```
SerializedProperty defaultDimension = serializedObject.FindProperty("DefaultDimension");
defaultDimension.intValue = EditorGUILayout.IntField(new GUIContent("Default Dimension", "Active dimension on start"), defaultDimension.intValue);
```

**Comment by killerantz** [comment]
Created PR #5069 for potential fix. I know it's more than what we are asking here.
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5069

**Comment by Yoyozilla** [comment]
fixed

**Comment by ZAO29** [comment]
Finally, what is the property to know if a checkbox is checked ? or to check/uncheck it ?

**Comment by killerantz** [comment]
I believe it's IsToggled.
