### ISSUE TITLE
LineRenderer shown in wrong position during first frame of controller activation

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#3612]
## Overview
Pulling the trigger of the motion controller makes the beam appear infront of it. It kinda snaps into position, because during the first frame of visibility, its in a wrong position

## Expected Behavior
Line just appears in front of the motion controller

## Actual Behavior
First frame is wrong

## Steps to reproduce
put on MR HMD and pull the trigger on the motion controller

## Unity Editor Version
2018.3.8f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by Alexees** [comment]
@StephenHodgson this is also caused by the wrong order of execution:

- LinePointer PreRaycast: the current position is read and BaseMixedRealityLineDataProvider's First and LastPosition get set.
- LinePointer PostRaycast: the BaseMixedRealityLineDataProvider gets Enabled and gets its matrix saved for the first time

It's the second time the matrix is old the moment it's needed.
Nonetheless, the MixedRealityToolkit seems to have a problem with execution orders. I'm going to do a diagram for who needs what and when it will get it.

**Comment by davidkline-ms** [comment]
@Alexees,

We very much appreciate all of the investigation you have been putting into your issue reports. It helps immensely!

**Comment by Alexees** [comment]
@davidkline-ms,

thanks for the appreciation. im actually ging to work full time in the kit at least until the end of the month. we will be replacing a pretty crippled version of a year old HTK and I want to make sure the conversion goes as smooth as possible

**Comment by wiwei** [comment]
Tagging with Input, but specifically this is pointers within Input

**Comment by luis-valverde-ms** [comment]
@Alexees , this seems to have been fixed via PR #3626. Can you confirm and close the issue if appropriate?

**Comment by Alexees** [comment]
this issue is pretty old, but at that time some errors I found got doubled in issues I've written and from the sounds of these two, these are two of those.
I'm pretty sure this is fixed.

**Comment by Alexees** [comment]
@luis-valverde-ms my assumption is wrong, it's not fixed

**Comment by luis-valverde-ms** [comment]
Thanks @Alexees . With the repro in that one it should be relatively straightforward to get to the bottom of it.
