### ISSUE TITLE
Proposal: Change the Static system checks in to a dynamic validator

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#3636]
## Overview
We are seeing more and more static property checks for more and more systems, simply to have a simple validation as to whether a system is enabled or not.  This ultimately is not a future proof approach as it requires constant updates to the MR Manager.

E.G.
```
public static bool IsTeleportSystemEnabled
```

This needs to be changed to a more dynamic structure or function where the service it'self registers it's activation in a static validator attached to the MRManager, which will prevent further changes to the manager as more systems are added and provide a more generic way for system validation checking.

## Proposal 1
Have extension methods or function that work with the existing service registries, that accept an Interface type and return back true / false to the service being active.

### Pros
Simple to implement with no change to downstream services

### Cons
Requires strict testing for performance and assuring a proper generic path
Complexities when services are disabled, but this could be taken in to account in the test.

## Proposal 2
Have a static dictionary or other lookup to catalogue the reediness of any particular service and a function call that takes an interface to test the services availability.  

### Pros 
Provides an extensible simply registry that is quick and fast to access
Each service designs it's own test independently to determine it's state.

### Cons
Requires updating the services designs to ensure the service (once actually active) properly registers when active and de-registers when inactive.
Lifecyels need to be validated and tested, especially when services have multiple states, e.g. active / live / processing / disabled

## Discussion Points

* is this a valid concern
* which approach suits the platform best
* any other approaches?

**Comment by davidkline-ms** [comment]
Thanks for pointing this out, Simon. The first phase of changes for #3545 (should be in PR today) is actually changing many statics to instance methods/properties.

**Comment by SimonDarksideJ** [comment]
I don't recall that proposal changing the separate static accessor properties that have been added to the manager. So I'll just wait and see the PR.

**Comment by davidkline-ms** [comment]
It wasn't expressly documented in the proposal at the time the accessor issue cropped up while reviewing the implementation and unit tests.

There was some confusion as the team reviewed some usage patterns (ex: MixedRealityToolkit.UnregisterService(...) ) with regards to needing an instance to register, but unregistering from a static feeling confusing.

**Comment by Alexees** [comment]
I don't know if this #3657 belongs here, but it's an example of static checks that could very well be replaced by introducing ScriptableObjects.

**Comment by davidkline-ms** [comment]
XR Interaction toolkit will own the core "systems" (ex: input, teleport, etc.). MRTK addons in v3 are intended to be light weight and startable on demand.
