### ISSUE TITLE
The Diagnostics System Should Auto-Register Profiler Toggle Speech Commands

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#3637]
## Overview
Currently the diagnostics system's profiler can only be toggled on/off via the diagnostics profile.

## Expected Behavior

The diagnostics system should auto-register commands with a speech input handler. The commands should be similar to ones users are already use to in the Visual Profiler:

![Keywords](https://user-images.githubusercontent.com/13305729/54439020-2dbfff00-46f5-11e9-9f23-162050875d79.png)

Note, similar behavior already exists in the diagnostics demo scene, but it would be convenient for developers if any scene they profile had these voice commands.

## Mixed Reality Toolkit Release Version
MRTK vNetx

**Comment by davidkline-ms** [comment]
Thanks for the report @Cameron-Micka! Will likely move the Diagnostic demo voice commands to the diagnostic system itself.

**Comment by Yoyozilla** [comment]
@davidkline-ms  is this done?

**Comment by Yoyozilla** [comment]
This is impacting user. we should fix soon

**Comment by davidkline-ms** [comment]
> @davidkline-ms is this done?

It is not. I have it on my backlog.
