### ISSUE TITLE
UI Raycast takes precedence over 3D objects in front

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3645]
## Overview
When aiming at a 3D interactable while UI elements are behind it, the targeting ray goes straight through and interacts with the UI elements instead

## Expected Behavior
Whatever comes first in terms of z index should be handled first

## Actual Behavior
The UI comes first no matter the 3D objects

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.3.8f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by chrisfromwork** [comment]
@Alexees will close based on submitted fix
