### ISSUE TITLE
Extra click event raised on HoloLens airtap only

### ISSUE THREAD

**Issue by genereddick** [microsoft/MixedRealityToolkit-Unity#3652]
## Overview
I'm getting an odd behavior only on an actual HoloLens deployment. 

In a class that inherits:

    IMixedRealityPointerHandler

In the function that handles the click:

    public void OnPointerClicked(MixedRealityPointerEventData eventData)
        {
            DebugText.text += " clicked: " + Time.time;
            ...

On airtap this gets called twice. So, in the DebugText.text I see the text "clicked: someTime clicked someTime" and the someTime timestamp is identical.

This does not happen in the Unity holographic emulator (Simulate in Editor nor Remote to Device), nor does it happen on a WMR headset where the event is raised only once. In all those cases a single text entry and timestamp is recorded, and a second click (xbox controller or WRM controllers), adds a new timestamp.

## Expected Behavior
Event raised only once.

## Actual Behavior
Event raised twice

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.3.9f1

## Mixed Reality Toolkit Release Version
vNext, latest as of a few days ago

**Comment by Alexees** [comment]
I found the problem

WindowsMixedRealityController.cs:
`new MixedRealityInteractionMapping(4, "Trigger Touch", AxisType.Digital, DeviceInputType.TriggerTouch, MixedRealityInputAction.None),
`

this Input is ignored when holographic remoting, but is not on the Hololens. Since it triggers the same events as `new MixedRealityInteractionMapping(5... Trigger Pressed` not only InputUp is called twice, but InputDown is called twice also.

**Comment by genereddick** [comment]
@Alexees interesting, I see in Interactable.cs there is a method that seems to be designed to avoid this kind of double trigger:

        /// <summary>
        /// Starts a timer to check if input is in progress
        ///  - Make sure global pointer events are not double firing
        ///  - Make sure Global Input events are not double firing
        ///  - Make sure pointer events are not duplicating an input event
        /// </summary>
        /// <param name="isInput"></param>
        protected void StartInputTimer(bool isInput = false)
        {
            if (IsGlobal || isInput)
            {
                if (inputTimer != null)
                {
                    StopCoroutine(inputTimer);
                    inputTimer = null;
                }

                inputTimer = StartCoroutine(InputDownTimer(clickTime));
            }
        }
 
Seems like this kind of protection should be in the MRTK itself and not something we have to re-implement in our own code? Or maybe we are supposed to use something like Interactable everywhere? Seems heavy just to handle a click.

**Comment by radicalad** [comment]
Is this still an issue? I've tested your scenario using `mrtk_development` and only get a single air tap event.

**Comment by radicalad** [comment]
Closing since I can't repro. Feel free to reopen if you're still having issues.
