### ISSUE TITLE
Question: How to deal with large changes?

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3655]
I just went into the DeviceManager and BaseController structures and cleaned them up. There was a lot of redundancy in there, different approaches that could be equalized etc.
This change consists of 650 lines changed and 600 removed, basically reducing the touched code by half.

Is this something that would even make it into the kit and if so under which circumstances?
Most pull requests are not more than 20 lines of code and are already handled like uncooked eggs.

Can someone give some advice on this?

**Comment by chrisfromwork** [comment]
For large changes, like the one you've described, its much better practice to document the upcoming work with a repo issue prior to sending out a pull request. Having to view large amounts of files through github is difficult and regression prone. It also detracts from reviewers wanting to partake in the review based on the perceived required amount of time to feel comfortable signing off on the change. It's unfortunate, but I think these behaviors may explain some of the difficulties you've experienced in contributing to the MRTK. If you personally have suggestions on how to make this process easier/better, we would appreciate this feedback.

Aside from best practices for getting folks on board with your changes, there are some other things that may be considered when determining whether to assess a review:

1) What amount of testing was conducted with said change? Was the contributor able to compile and test against all platforms supported by the MRTK? Will another community member/contributor/moderator have to help with testing?
2) What impact does this have on other developers already consuming the MRTK? Is this change a breaking change? Are there class renames that will break existing scripts? Are there interface changes that will impact MRTK consumer classes? Are there namespace/packaging changes that will cause dependencies to no longer resolve correctly in other projects? If the answer is yes to some of these questions, the worth of the change will have to outweigh the pain experienced in consuming the change. This assessment is likely going to have to be determined case by case.
3) How soon is an upcoming release for the MRTK development branch payload? As we get closer to releases (like RC1 at the end of March), there has to be a transition from accepting all changes to only accepting specific release blocking bug fixes. The risk associated with large refactors begins to outweigh the worth in getting them in before a release compared to after. This detracts from code velocity but does help insure that we release a more stable product. 

I think that everyone working on the MRTK will agree that refactoring/cleaning up code should be both welcome and supported. I do think that the current RC1 push for the end of March is consuming a lot of contributor resources/effort and may be detracting from code velocity.

**Comment by Alexees** [comment]
@chrisfromwork thanks for the long and thorough explanation
