### ISSUE TITLE
Add .NET Backend validation build to CI

### ISSUE THREAD

**Issue by paco-ms** [microsoft/MixedRealityToolkit-Unity#3656]
## Overview
Most developers use IL2CPP on their day to day work. This means .NET backend is easy to break.
Add an additional build configuration to CI that uses the .NET backend (instead of IL2CPP). CI should fail if that configuration fails.

**Comment by wiwei** [comment]
Got this working, will be sending out PR for this soon...

**Comment by keveleigh** [comment]
Pretty sure this is complete, as of #4521
