### ISSUE TITLE
UnityJoystickManager fails to recognize Xbox controller, returns generic controller

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#3657]
## Overview
Running a project with default code, and UnityJoystickManager is logging lots of warning messages and then returning the (presumably) wrong type for an Xbox controller.

The issue is in this code in UnityJoystickManager.cs:

    if (joystickName.StartsWith("Xbox"))
    {
        return SupportedControllerType.Xbox;
     }

However, the joystickName getting passed in is actually:

    "Controller (Xbox One For Windows)"

Thus fails the StartsWith if comparison. Changing this to a contains "Xbox", or StartsWith("Controller (Xbox" works.

## Expected Behavior
    return SupportedControllerType.Xbox;

## Actual Behavior
Debug.Log message
Controller (Xbox One For Windows does not have a defined controller type, falling back to generic controller.

    return SupportedControllerType.GenericUnity;

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.3.9f1
## Mixed Reality Toolkit Release Version
vNext latest build (as of today)

**Comment by Alexees** [comment]
This is a perfect example for using ScriptableObjects. They could perfectly take the roll for the match and make of controller names and their concrete classes.
