### ISSUE TITLE
Errors in 2017.4.3.0 relating to C# 7

### ISSUE THREAD

**Issue by paulmelis** [Microsoft/MixedRealityToolkit-Unity#3675]
## Overview

While working on c# scripts in VS I like to use Ctrl+Shift+B to do a quick check if my project's code compiles correctly. This is with the VS instance launched by Unity on double-clicking a script (so this is different from compiling the IL2CPP generated code). 

With MRTK 2017.4.3.0 and VS 2017 15.9.9 I get errors in certain MRTK files that indicate they need C# 7:

```
2>D:\unity projects\mos\Assets\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(54,62,54,64): error CS8059: Feature 'out variable declaration' is not available in C# 6. Please use language version 7.0 or greater.
2>D:\unity projects\mos\Assets\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(90,22,90,50): error CS8059: Feature 'local functions' is not available in C# 6. Please use language version 7.0 or greater.
```

From what I understand c# 7 is [only supported from Unity 2018.3 upward](https://stackoverflow.com/a/52632034). These files are also not directly used in my project, and I don't see the same errors in the IL2CPP generated code (presumably because the code isn't exactly used and therefore no c++ is generated for it).

This issue is mostly a nuisance, as the IL2CPP generated code compiles without errors. However, in the current situation I need to ignore 2 errors from the build output in order to find actual errors in my own code.

## Expected Behavior

MRTK code compiling without errors

## Actual Behavior

Errors during MRTK compilation, but only in the script-editing instance of VS

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version

2017.4.24f1

## Mixed Reality Toolkit Release Version

2017.4.3.0

**Comment by Yoyozilla** [comment]
We would recommend you move to MRTK v2 and unity 2018.3.x if you can. We are not planning anymore updates to the HTK releases.
