### ISSUE TITLE
latest MRTK-Release doesn't compile in unity

### ISSUE THREAD

**Issue by dapt1989** [Microsoft/MixedRealityToolkit-Unity#3688]
## Overview
Updating Externals/MRTK points to a commit that doesn't compile in Unity
## Expected Behavior
MRTK should be runnable within the editor and build with both il2cpp and .NET backends.
## Actual Behavior
The current status of MRTK-Release doesn't compile in Unity.
## Steps to reproduce
Opening your project in unity and try to compile project.
Console shows errors with the MixedRealityControllerVisualizationProfileInspector.cs 
![MRTK-Release](https://user-images.githubusercontent.com/48930515/54958147-0dbce680-4f12-11e9-8ace-759acfe387d0.PNG)

## Unity Editor Version
Unity 2018.3.1f1
## Mixed Reality Toolkit Release Version
mrtk-release commit: acd338ae68059076485b828bd9cb1fb193732a25

**Comment by Alexees** [comment]
Duplicate to #3689

**Comment by davidkline-ms** [comment]
@dapt1989, can you try a newer release of Unity 2018.3? I believe there were some API changes in recent patches (.3, if my memory serves me) that prevent using 2018.3.1.

Thanks!

**Comment by wiwei** [comment]
Let's use https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3689 to track this issue (AFAICT this isn't a development vs. release issue - we know that .NET backend isn't working and we're actively trying to get it fixed.)
