### ISSUE TITLE
Latest MRTK-Development doesn't compile in Unity

### ISSUE THREAD

**Issue by dapt1989** [Microsoft/MixedRealityToolkit-Unity#3689]
## Overview
Unity doesn't compile with the current implementation on MRTK-Development
## Expected Behavior
Unity should compile and build for both il2cpp and .NET
## Actual Behavior
The commit below does not work, but there is a commit that will compile and build
mrtk_development: 580c7a8a2d29ce417fc0838e4e78c61ccd502bd7 

## Steps to reproduce
Open Unity
Compile project and look at the console

![MRTK-Development](https://user-images.githubusercontent.com/48930515/54958657-b881d480-4f13-11e9-80a3-3b09752b12b1.PNG)

## Unity Editor Version
Unity 2018.3.1f1
## Mixed Reality Toolkit Release Version
mrtk_development commit: 90941f812eb07d828db06a9f2fdd0bf306716182

**Comment by Alexees** [comment]
@dapt1989 what's the build configuration this did not build with? (Platform, backend)

**Comment by dapt1989** [comment]
The error is happening before the build process starts. The unity project as a whole doesn't compile trying to access the MRTK addon, which blocks the project from being able to build. The project is still using a .NET backend and below is the Unity Build Settings window. 

![BuildSettingsForError](https://user-images.githubusercontent.com/48930515/55018399-077d4780-4fb0-11e9-9e68-ef6a42816bae.PNG)

The errors that Unity flags for this bug and #3688 are different so it looks like some issues were solved and new ones appeared thus the reason I created separate bugs, but I apologize if that duplicate complicates things.

**Comment by davidkline-ms** [comment]
@dapt1989, can you try a newer release of Unity 2018.3? I believe there were some API changes in recent patches (.3, if my memory serves me) that prevent using 2018.3.1.

Thanks!

**Comment by Railboy** [comment]
Just verified that this and one other script - InspectorGenericFields.cs - are blocking .NET compilation on in Unity 2018.3.3. Working on a PR now.

**Comment by dapt1989** [comment]
I am able to run with MRTK in editor now, but I am getting errors around glb and gltf importing. 

Scripted importers UnityGLTF.GLTFImporter and Microsoft.MixedReality.Toolkit.Utilities.Gltf.Serialization.Editor.GlbAssetImporter are targeting the glb extension, rejecting both.
UnityEditor.Experimental.AssetImporters.ScriptedImporter:RegisterScriptedImporters()

and

Scripted importers Microsoft.MixedReality.Toolkit.Utilities.Gltf.Serialization.Editor.GlbAssetImporter and Microsoft.MixedReality.Toolkit.Utilities.Gltf.Serialization.Editor.GltfAssetImporter are targeting the gltf extension, rejecting both.
UnityEditor.Experimental.AssetImporters.ScriptedImporter:RegisterScriptedImporters()

It looks like unity can't register the importers not sure what could cause this.

**Comment by Railboy** [comment]
@dapt1989 Let's open a separate issue for the GLTF service problem.

**Comment by chrisfromwork** [comment]
Does anyone have a preference on whether or not the MRTK should come with a default importer? A workaround here is to remove the MRTK GlbAssetImporter and GltfAssetImporter. But we will then lose any ability for users to import gltf/glb files that aren't using UnityGLTF. Long term, i think we will move towards consuming UnityGLTF, but in the immediate, what seems preferred?

**Comment by Yoyozilla** [comment]
Closing as we will track the GLTF issue in a separate issue.

**Comment by salvolannister** [comment]
@Yoyozilla could you link here the other issue? I have this problem and I didn't find the related issue

**Comment by salvolannister** [comment]
Yes I was talking about glTF importer! Thank you for the help, I solved reading #9658

**Comment by keveleigh** [comment]
> Yes I was talking about glTF importer! Thank you for the help, I solved reading #9658 

Excellent! Glad to hear you were able to resolve the issue.
