### ISSUE TITLE
Input Simulation does not work for Desktop Standalone (disable VR support)

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#3692]
## Overview
Building the Toolkit for Windows, be it Standalone or UWP, it's not possible to interact with any of the Interactable objects in the InteractablesGallery. It's also not possible to move the camera in any way. Seems as if there is no default implementation for desktop.

## Expected Behavior
At least the interaction should work with the mouse

## Actual Behavior
no interaction possible at all

## Steps to reproduce
build the InteractablesGallery for Standalone or Desktop without XR support

## Unity Editor Version
2018.3.9f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by Yoyozilla** [comment]
I am not sure if MRTK is suppose to work without XR support.

**Comment by Alexees** [comment]
> I am not sure if MRTK is suppose to work without XR support.

It should because it has a MixedRealityMouseController for example. That's one part that was missing. Another is that the SimulationServices, the only service for WASD movement, gets stripped and doesn't seem to be intended to be used in production.
Additionally, the Standalone platforms are among the supported platforms in the SupportedPlatforms enum. Don't confuse them with their Editor counterparts, which are listed as well.

**Comment by keveleigh** [comment]
I believe the MouseController is intended to be a spatial mouse, present inside your MR experience, as opposed to a more traditional desktop mouse. 
The standalone platforms are present because UWP isn't a requirement for OpenVR (and soon WMR in Unity).
We've had some discussion about supporting non-XR scenarios. @WiWei?

**Comment by Alexees** [comment]
Any news here because otherwise I just close this and implement it on my own for our purposes.

**Comment by Troy-Ferrell** [comment]
We have a MousePointer prefab and Unity Mouse Device Manager & related profiles...I was going to try out myself in InteractablesExamples.

@alexees, have you by chance been using these as well?

**Comment by Troy-Ferrell** [comment]
So I can't get camera working but I can use mouse for interaction. It is a bit buggy and some of that is noted in #5566 

![test](https://user-images.githubusercontent.com/25975362/65923375-91fa9580-e39d-11e9-8e26-25ee26f46cae.gif)

**Comment by Alexees** [comment]
Yes, I tried the mouse so at least that's what I got working.
For some time I managed to change ASMDEFs, script locations and code to get even the simulation services running on windows, but that got so complicated that I reverted all of that.
There should be a runtime equivalent of it so we can move around on windows.
the simulation service is good enough for that.
