### ISSUE TITLE
Changing namespaces breaks System.Type serialization

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3693]
## Overview
System.Type cannot be serialized on its own, this is usually done by serializing the AssemblyQualifiedName. This is based on the namespace a type is in. Every time the namespace changes, serializations break. This happens for using ASMDEFs at all as well.
There should be a mechanism that somehow reserializes those in case of such changes or make the type namespace independent.

I found by running the InteractionsGallery scene and in particular InteractableReceiverList with its List<InteractableEvent> Events is affected, but I'm pretty sure this is not the only place this will happen.

## Expected Behavior
serialized types do not break

## Actual Behavior
they break

## Steps to reproduce
run InteractionsGallery on UWP with XR, attach a debugger prior to starting if you will. The scene will throw two NullReferences.
![stacktrace](https://user-images.githubusercontent.com/32508825/55009884-8f307980-4fe3-11e9-9e93-b841b11288a4.png)

## Unity Editor Version
2018.3.9f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by davidkline-ms** [comment]
Related to #3672

**Comment by wiwei** [comment]
See response to https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3672

I'll take a peek at this this week.

**Comment by chrisfromwork** [comment]
@Alexees do you think that Lars's pull request https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3750 would mitigate some of the pain you've been experiencing?

**Comment by Alexees** [comment]
@chrisfromwork I guess so. But from the looks of it, you still need to fail to know what needs fixing, right?

**Comment by Yoyozilla** [comment]
Closing as #3750 will mitigate this
