### ISSUE TITLE
NullReferenceException in editor when hitting "Copy & customize"

### ISSUE THREAD

**Issue by jelmerS2** [Microsoft/MixedRealityToolkit-Unity#3694]
## Overview
In the MRTK component I click "Copy & customize"
## Expected Behavior
A new profile is available that can be customized

## Actual Behavior
Console gives 100s of errors that won't ever stop again:
NullReferenceException: Object reference not set to an instance of an object
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit.EnsureMixedRealityRequirements () (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:294)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit.InitializeServiceLocator () (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:169)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit.ResetConfiguration (Microsoft.MixedReality.Toolkit.Core.Definitions.MixedRealityToolkitConfigurationProfile profile) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:109)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit.set_ActiveProfile (Microsoft.MixedReality.Toolkit.Core.Definitions.MixedRealityToolkitConfigurationProfile value) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:85)
Microsoft.MixedReality.Toolkit.Core.Inspectors.Profiles.BaseMixedRealityProfileInspector+<CreateCopyProfileValues>d__10.MoveNext () (at Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs:147)

## Steps to reproduce
Get latest MRTK2 unitypackage
in the MRTK copmponent, press "Copy & customize"

## Unity Editor Version
2018.3.8
## Mixed Reality Toolkit Release Version
feb. 2019

**Comment by Alexees** [comment]
naming the branch and being up to date on it is more reliable in reproducing the issue

**Comment by chrisfromwork** [comment]
If you can provide a specific commit to look into for the branch you are using, @davidkline-ms can look into this issue locally.

**Comment by davidkline-ms** [comment]
@Railboy, you were working in this code recently, i recall.. Can you investigate.

**Comment by wiwei** [comment]
I'm not seeing this with a package built from the latest mrtk_development snap.

We're heads down getting RC1 out the door, and let's re-open this then if we still see that.

FWIW I do see another exception (which is unrelated to any of this new payload) which I can fix separately, but from what I can tell is benign.

**Comment by wiwei** [comment]
Let's circle back in ~8 days around this.

**Comment by jelmerS2** [comment]
Hey thanks! I will check again later 👍 
I must maybe add that azure spatial anchors SDK was also present in the project.

**Comment by davidkline-ms** [comment]
Removing the RC tag
