### ISSUE TITLE
Question: Missing MRTK Settings

### ISSUE THREAD

**Issue by twosyde** [Microsoft/MixedRealityToolkit-Unity#3697]
Hey, i hope someone can help me.

First of all i'm new to this all (started yesterday).
I'm trying to build a hologram for the hololens. So i installed everything: Visual Studio (with Universal  Windows and Unity), Unity (with .NET).
When i load the MRTK in my unity project, i cant find some settings. 
For example "Apply Mixed Reality Project Settings" is not there.
I already reinstalled everything and tried it even on another pc.

https://imgur.com/a/2jSZz4C

## Unity Editor Version
Unity 2018.3.10f
## Mixed Reality Toolkit Release Version
The latest one

**Comment by Railboy** [comment]
If you select **'Configure...'** it will create and configure the MRTK singleton in your scene.

**Comment by twosyde** [comment]
So the "configure" replace the "Apply...." -stuff and set the whole project?
Because in the youtube videos i saw, there was another menu.

**Comment by Railboy** [comment]
That's correct - here's some [newer documentation](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html) that should help you get rolling.

**Comment by chrisfromwork** [comment]
Closing based on Lars's answers.

**Comment by keveleigh** [comment]
>Because in the youtube videos i saw, there was another menu.

Those were likely using the HoloToolkit. This menu (and documentation, linked above by @Railboy) has been updated in MRTK v2.

**Comment by twosyde** [comment]
Thank you guys!
