### ISSUE TITLE
Proposal: Getters should handle null checking serialized fields

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#3707]
## Overview
Unity has the problem of not allowing ?. and ?? to be used on SerializedFields, since they're not overloadable like == and != are.
Additionally, by design, all such fields are accessible by Properties only, or at least that's what I assume from looking through a lot of scripts.
If properties are part of the coding guideline and those properties were to do the null checks themselves and actually return null, one can use the Null coalescing and null conditional operators throughout any other scripts, which would inprove readability.

affected is everything deriving from UnityEngine.Object

Example:

```
if (MixedRealityToolkit.Instance != null &&
    MixedRealityToolkit.Instance.ActiveProfile != null &&
    MixedRealityToolkit.Instance.ActiveProfile.InputSystemProfile != null &&
    MixedRealityToolkit.Instance.ActiveProfile.InputSystemProfile.ControllerMappingProfile != null)
```

vs.

`if (MixedRealityToolkit.Instance?.ActiveProfile?.InputSystemProfile?.ControllerMappingProfile)`

**Comment by davidkline-ms** [comment]
great suggestion! thanks!

**Comment by StephenHodgson** [comment]
Can you confirm that the [Resharper Unity plugin still raises warnings/errors](https://github.com/JetBrains/resharper-unity/wiki/Possible-unintended-bypass-of-lifetime-check-of-underlying-Unity-engine-object) about this even after moving the null checks to the properties?

**Comment by Alexees** [comment]
I don't have Resharper, sorry

**Comment by StephenHodgson** [comment]
I'm not entirely convinced that moving the null check will actually fix the lifetime bypass as it's an overload on the type itself.

**Comment by Alexees** [comment]
it won't fix it if references to these objects are saved and those are checked with null coalescing and conditional operators, but as long as you only ever directly use the properties, it will work.  
throughout the current code both mentioned ways of accessing fields are currently used. since you'd need to distinguish between unity objects and regular ones anyway if you ever want to use those operators, there's not much you can do to prevent the use of the wrong accessing way except for disallowing the use of the two operators altogether.

**Comment by luis-valverde-ms** [comment]
I do like the idea of being able to use ?. and ?? but I feel that we're better off disallowing it completely than selectively supporting it. I think that allowing it in some properties will lead to:

1. Client code using it in properties that don't support it because they have seen it used in properties that did.
2. Property implementers forgetting to add the null check.

If we disallow use of those operators completely, seeing them in code will immediatly trigger red flags. If we support them selectively I feel we will end up with more bugs.

**Comment by Alexees** [comment]
It's already weird isn't it:
- You must use == and != for all UnityEngine.Object derived classes
- You must NOT use .? and ?? for all UnityEngine.Object derived classes
- You can do whatever you want with all other classes

And you won't receive any IDE help with it :P

**Comment by luis-valverde-ms** [comment]
I don't see how that addresses either of my concerns...

**Comment by Alexees** [comment]
I just wanted to point out that there already is a common sense of how the existing operators are used which cannot be prevented or warned about.
unless Resharper or some other plugin or IDE I'm not aware about actually can.
If there are, and it's recommended to use them to follow coding guidelines properly, I probably can't really suggest anything useful.
but if not, both operators should be banned, even though code is getting messy.

another possible solution to situations I used as an example would be an extension to reduce call depth and handle the null checks. the outcome would look like this:

var mapping = MixedRealityToolkit.Instance.ProfileInputControllerMapping;
if (mapping != null)
{
    ...
}

**Comment by genereddick** [comment]
As an example of your collective concerns, I was aware that there was an issue with using them with Unity but not the specifics. 

After looking through the MRTK code and seeing the null coalescing operators I had sort of assumed that this was now (somehow) allowed in the latest Unity versions and would likely have used them in my own code.

**Comment by StephenHodgson** [comment]
I'm just gonna leave this here...
https://blogs.unity3d.com/2014/05/16/custom-operator-should-we-keep-it/
