### ISSUE TITLE
ControllerVisualizationProfile is not multi platform capable

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3710]
## Overview
When running the MRKT on a mobile phone and touching the screen, an error is thrown:

> No controller model available. Failed to add controller game object to scene

This happens, because the DefaultMixedRealityControllerVisualizationProfile is queried for controllers. By default, it provides 2 controllers for UWP basically.
It is queried from the DefaultMixedRealityRegisteredServiceProvidersProfile, which CAN distinguish between platforms and uses the UnityTouchDeviceManager, which actually fits the platform.

## Expected Behavior
- Touch devices do not try to instantiate a controller
- Each platform provides its set of controllers

## Actual Behavior
- error because for every platform UWP Controllers are tried to be used
differentiation is currently only possible when exchanging the ControllerVisualizationProfile altogether.

## Unity Editor Version
2018.3.9f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by chrisfromwork** [comment]
This seems similar to https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3685

I will work on getting out a fix for this early next week.

**Comment by Alexees** [comment]
yes I thought the same just forgot to link it

**Comment by thalbern** [comment]
I removed the error message for controllers that have no visualization here https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3822
