### ISSUE TITLE
Question: Status of TouchDeviceManager on Android

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3715]
## Overview
I tried the Toolkit on my Android phone with Unity Remote in the Editor. I was wondering if that kind of support is still in development as it does not really work:

- A pointer is spawned and only on the second screen touch, which renders a black line along the surface normal of it objects and stays there after lifting the finger. For touch, you don't really need a pointer at all.

- The "controller" is updated twice during one Update which results in the cursor to jump around in the scene, probably toggling between two position values

- Clicking on interactables does not work, OnClick does not seem to be implemented

## Unity Editor Version
2018.3.9f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by davidkline-ms** [comment]
as of today, there isn't formal support for platforms other than Windows Mixed Reality and OpenVR. That said, please continue filing issues you encounter on these platforms as they will help us to identify areas for focused testing and investigation as we add formal support.

Thanks!

**Comment by Alexees** [comment]
ok, I will do that.
