### ISSUE TITLE
Input System raises OnInputChanged every frame for pressed buttons

### ISSUE THREAD

**Issue by luis-valverde-ms** [Microsoft/MixedRealityToolkit-Unity#3722]
## Overview

It seems that IMixedRealityInputSystem.RaiseOnInputPressed() is meant to be raised every frame a binary input (e.g. binary button) is down: see MouseController.Update and GenericJoystickController.UpdateButton. The event it is triggering though should only be raised on input changes.

I don't think we should be broadcasting the current state of an input every frame. Users should instead rely on the input down/up events and access directly the input source/controller if they need to know the current state. 

We should substitute the input pressed interface with something like RaiseOnFloatInputChanged() that is called to report changes to float input values. Note that WindowsMixedRealityController is already using RaiseOnInputPressed to report changes to trigger button values.

**Comment by davidkline-ms** [comment]
This feels like event overload. i definitely agree with @luis-valverde-ms that this should be fixed.

**Comment by chrisfromwork** [comment]
@luis-valverde-ms is there a perspective on how long this would take to fix? It would be great to have a fix for this in rc1, but if its going to take a lot of time it may slip to rc2.

**Comment by luis-valverde-ms** [comment]
Opened PR for this: #3787

**Comment by wiwei** [comment]
I believe this is done (by #3787) so closing this out.
