### ISSUE TITLE
Unity 2018.3.10 works in Remote, but has clear screen on deploy

### ISSUE THREAD

**Issue by shamsfk** [Microsoft/MixedRealityToolkit-Unity#3728]
I'm building an app for Hololens, using Unity 2018.3 and Beta 2 MRTK, it runs fine using Holographic Remoting. 

It also builds and deploys successfully using VS2017, but deployed app renders nothing.

Can someone suggest what could I do wrong?

## Unity Editor Version
2018.3.10f1

## Mixed Reality Toolkit Release Version
2.0 Beta 2

**Comment by sanidhya26** [comment]
hi, how did you solve this?

**Comment by RedChris** [comment]
I am also experiencing this, I would also be grateful, if you can share how you solved it.
