### ISSUE TITLE
What happened to GazeManager?

### ISSUE THREAD

**Issue by aliaga-d** [Microsoft/MixedRealityToolkit-Unity#3740]
## Overview
I am opening a project that seems to use the HoloToolKit
(I don't know how to verify which version)
The project does not compile mainly because GazeManager does not exist in several contexts
.
How has GazeManager changed in the ToolKit?

## Actual Behavior
GazeManager does not exist.
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
Unity 2018.1.3f1

**Comment by StephenHodgson** [comment]
Which version are you using?

**Comment by Alexees** [comment]
@aliaga-d the version is the git repository branch you're using. If not up to date preferrably the SHA hash code of the commit you're on.

**Comment by chrisfromwork** [comment]
What project are you attempting to use that references the GazeManager? GazeManager has been deprecated and likely won't be added back to the v2 MRTK.

**Comment by aliaga-d** [comment]
Thanks for the reply. I am trying to use [this project](https://github.com/anderm/holo-assisted-training). It was built for an old version of unity and it uses the Holotoolkit (with Gaze Manager). I am trying to make it work

**Comment by Yoyozilla** [comment]
I think you would need to HTK release for this project. Here's a release of HTK.
https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/2017.4.3.0

Please note that HTK is not receiving any more updates as we are releasing MRTK v2 and it will be the recommended and support build moving forward :)
