### ISSUE TITLE
Visual meshes are not coming when i use spatial mapping in holographic remoting in hololens

### ISSUE THREAD

**Issue by BhavaniGudimetla** [microsoft/MixedRealityToolkit-Unity#3757]
Hi,
I am trying get visual meshes in hololens when i use  holographic remoting. I am not using any room scale model reference.
i have tried by enabling **draw visual meshes** option in SpatialMappingManager script but it didn't work for me.

Can anyone help me how to get visual meshes in hololens without using room scale model when i use holographic remoting?

**Comment by SoundGuy** [comment]
I'm having some similar behaviour. 
I'm on MRTK 1 for unity 2018, and when i use the holographic emulator connected to my hololens device, the spatial mapping SOMETIMES work but most often doesn't.
I couldn't get the spatial mapper to display anything when i use the emulator in the demo in this tutorial.
https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-230#chapter_4_-_placement

Any ideas why?

**Comment by r1sc** [comment]
I experienced the same problem. For me it works but it just takes a very long time for the initial batch of meshes to transfer from the Hololens (up to 45 seconds). After that it chugs along.
