### ISSUE TITLE
UnityUI near interaction pointer events are mouse events, not pointer events.

### ISSUE THREAD

**Issue by danielhofmann-ms** [microsoft/MixedRealityToolkit-Unity#3759]
## Overview
The MixedRealityInputModule translates MRTK pointer events into input events for the Unity UI. We currently translate all MRTK pointer events (far and near) to Unity UI mouse events.

## Expected Behavior
Near pointer events get translated into touch events.

## Actual Behavior
Near pointer events get translated into mouse events.

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.3.1.f

## Mixed Reality Toolkit Release Version
MRTK v2

**Comment by chrisfromwork** [comment]
Assigning to daniel

**Comment by paco-ms** [comment]
@thalbern this issue is quite old. Do you know if it's still relevant?

**Comment by Yoyozilla** [comment]
Closing as the relevant PR seems already merged. Please re-open if repros
