### ISSUE TITLE
Cleanup the EyeTracking Demo code and other HL2 artifacts

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#3767]
There's significant technical debt in the eye tracking demo code which we should clean up.

This has been filed to make sure we don't lose some of the interesting TODOs or comments in the following PR:

https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3755

**Comment by wiwei** [comment]
InputPointVisualizer.cs had a large TODO:

  /// ------------
    /// *** TODO ***
    /// ------------
    /// - Load log files
    /// - Replace GameObjects with particle systems for higher perf on HoloLens
    /// - Question: How to visualize data from multiple ppl? Color lookup table? Limit number of scanpaths visible at a time?
    /// - Question: How can users load files from HoloLens? Built-in file explore? Load by session?
    /// - Allow for tweaking parameters while viewing the scene, such as "transparency" etc.
    /// ------------

Also VisModes needs summaries.

**Comment by wiwei** [comment]
LogStructure_EyeGaze had a lot of TODO code (around raw eye gaze tracking) removed.

**Comment by wiwei** [comment]
OnSelect_VisualizerInputController.cs needs tooltips for its serialized fields

**Comment by wiwei** [comment]
ParticleHeatmap_ParticleData.cs needs a summary

**Comment by wiwei** [comment]
UserInput_Playback.cs needs significant cleanup (see the original PR)

**Comment by wiwei** [comment]
WindowsMixedRealityEyeGazeDataProvider.cs needs work around its confidenceOfSaccadeThreshold

**Comment by wiwei** [comment]
Need to also followup on Interactable.cs's


            if (!CanInteract() || true)
            {
                return;
            }

            if (StateManager != null)
            {
                if (eventData == null && (HasFocus || IsGlobal)) // handle brute force
                {
                    StateManager.SetStateValue(InteractableStates.InteractableStateEnum.Visited, 1);
                    IncreaseDimensionIndex();
                    OnClick.Invoke();
                }
                else if (eventData != null && ShouldListen(eventData.MixedRealityInputAction))
                {
                    StateManager.SetStateValue(InteractableStates.InteractableStateEnum.Visited, 1);
                    IncreaseDimensionIndex();
                    OnClick.Invoke();
                    eventData.Use();
                }
            }
            */

**Comment by Yoyozilla** [comment]
I think this is done?

**Comment by keveleigh** [comment]
Some is in progress with #4032

**Comment by Yoyozilla** [comment]
#4032 is merged. closing issue.
