### ISSUE TITLE
MRTK should use code analysis tools during PR validation to ensure nit critique level code quality

### ISSUE THREAD

**Issue by chrisfromwork** [microsoft/MixedRealityToolkit-Unity#3770]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/322

___

## Overview
A lot of pull requests appear to get checked in with less than ideal coding standards:
1) Todos are left in the code with no associated issue id
2) Large blocks of commented out code are checked with no additional context provided
3) Naming choices for classes/fields vary drastically across the code base
4) Serialized fields don't end up with tooltips
5) public fields/types don't end up with summary information
6) Additional spaces/lines are added for no apparent reason

We should add a code analysis pass to our PR validation pipeline that assesses that new pr's adhere to coding standards. We should also add formal documentation calling out coding standards.

**Comment by polar-kev** [comment]
Things we'd like to keep from this suggestion:
- Todos are left in the code with no associated issue id
- Serialized fields don't end up with tooltips
- Additional spaces/lines are added for no apparent reason
- Anything that's public in documentation should have a summary tag

**Comment by keveleigh** [comment]
We might be able to use the tools described on https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019

**Comment by davidkline-ms** [comment]
This will allow for an automated first review for PRs. We should consider cleaning up simple issues (whitespace, etc.) and mark "change requested" beyond those.

**Comment by Zee2** [comment]
Working on #10726 .

**Comment by AMollis** [comment]
Zee2 original work to add github/super-linter was removed in PR #11084 with the following comment from Zee2:

> So, turns out super-linter can't lint PRs from forks and publish the results, at all :( https://github.com/github/super-linter/issues/3419

Another linting solution needs to be utilized here, one that is capable of executing and publishing results for PRs originating from forks.
