### ISSUE TITLE
WindowsMixedRealityArticulatedHand and WindowsMixedRealityGGVHand should not inherit from WindowsMixedRealityController

### ISSUE THREAD

**Issue by chrisfromwork** [microsoft/MixedRealityToolkit-Unity#3771]
## Overview
It appears that the HoloLens 2 work introduced WindowsMixedRealityArticulatedHand and WindowsMixedRealityGGVHand. It does not feel appropriate for these classes to inherit from WindowsMixedRealityController.

There was an issue when merging logic into the public github branch where hand mesh rendering broke based on changes to the WindowsMixedRealityController. There is nothing preventing this from continuing to happen. If WindowsMixedRealityController exists specifically for VR controllers, it should be able to contain logic that breaks hand experiences. If WindowsMixedRealityController is confusing naming and just a base class for uwp input in ar/vr space, we should create a new class that is specifically for vr controllers.

**Comment by keveleigh** [comment]
Fixed via #4707
