### ISSUE TITLE
Validate BoundingBox and ObjectCollection namespaces

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#3777]
Namespaces are locking in RC1 and a couple of UX components feel like they are not in the right place.

BoundingBox and ObjectCollection are currently under Utilties and it feels they belong under UI

**Comment by cre8ivepark** [comment]
Yes, Please feel free to update old UX namespace!

**Comment by wiwei** [comment]
I'm going to handle this.

**Comment by wiwei** [comment]
Actually I'm just gonna do BoundingBox - ObjectCollection still seems algorithmic and basic enough that it's actually some deeper level thing.
