### ISSUE TITLE
StartCommandLineBuild with -BuildTarget WSAPlayer ignores other command-line options and requires building an appx

### ISSUE THREAD

**Issue by ForrestTrepte** [Microsoft/MixedRealityToolkit-Unity#3779]
## Overview

I'd like to use StartCommandLineBuild in order to create automated builds of my MRTKv2 project. However, I just want it to run the Unity project to generate a Visual Studio solution. The rest of my build system will take it from there and build the .appx.

Unfortunately, if your platform is set to UWP, it looks like [this code in StartCommandLineBuild](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/8238869fe32849c21578b03a379a7d0b6c74c776/Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs#L166) will build an .appx for you regardless of the command-line options you have passed. What is the purpose of this special case for UWP, and why isn't the default case's behavior of parsing the command line options used?

## Steps to reproduce

Build MRTKv2 by running the Unity editor with -BatchMode -ExecuteMethod "Microsoft.MixedReality.Toolkit.Core.Utilities.Build.UnityPlayerBuildTools.StartCommandLineBuild" -BuildTarget WSAPlayer

## Actual Behavior

Builds the Unity project AND builds the appx.

## Expected Behavior

Builds the Unity project WITHOUT building the appx. The expected result would be similar to when you click the "Build Unity Project" button in the Build Window.

It doesn't look like it is currently possible to just build the Unity project with the WSAPlayer target.

Personally, I'd prefer this to be the default with a -buildAppx command line option for those who want to create an appx. Thus, the switch statement could be removed and everything would go through what is currently the default case with an explicit command line option used to control whether the appx is built. Alternatively, if folks feel that building the appx should be the default then we'd need to add a -dontBuildAppx switch, which I think is a more confusing option.

## Unity Editor Version

2017.3.7f1

## Mixed Reality Toolkit Release Version

mrtk_development

**Comment by ForrestTrepte** [comment]
@StephenHodgson, FYI.
Do you know why -BuildTarget WSAPlayer and BuildAppx = true are tied together in this way?

**Comment by StephenHodgson** [comment]
Yup that was how I had designed it.

What's the purpose for the extra build step?

**Comment by MenelvagorMilsom** [comment]
#3785

**Comment by ForrestTrepte** [comment]
This was fixed by #3785. Thanks @MenelvagorMilsom!
