### ISSUE TITLE
InteractableHighlight doesn't work with MRTK Standard shader material

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/MixedRealityToolkit-Unity#3786]
## Overview
A game object with an InteractableHighlight and a MRTK Standard shader material will not get highlighted when the gaze strikes the object. It will work with the UNITY standard shader though.

## Expected Behavior
A game object with an correctly configured InteractableHighlight should always highlight when the gaze strikes it 

## Actual Behavior
Any object with a MRTK Standard shader material will not get highlighted 

## Steps to reproduce
See this project. One cube will highlight, the other not. You can move the gaze my dragging the mouse
https://1drv.ms/u/s!AjesCJDYqwYk2JZs_CbOvnjLjqkSaA

## Unity Editor Version
2018.3.6.f1

## Mixed Reality Toolkit Release Version
Fresh from mrtk_development as of April 3, 10am UTC

**Comment by killerantz** [comment]
Testing in Unity seems to work running the provided project with Unity 2018.3.7. Both boxes turn red.
[RepoTexture_unity2018_3_7.zip](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/3040084/RepoTexture_unity2018_3_7.zip)

**Comment by Cameron-Micka** [comment]
Thanks for testing Todd! I wasn't aware of the InteractableHighlight script. But, looking at the code from a high level it seems like it should work?

**Comment by LocalJoost** [comment]
Very odd. In my Unity version it did not work.

Joost van Schaik

Windows Development MVP & Windows Insider MVP
Sent from my Surface Go

"The world as I envision it in my head is such a more interesting place"


________________________________

**Comment by Cameron-Micka** [comment]
Hi Joost,

I just pulled down the project and both boxes turned red for me. Testing in Unity 2018.3.9f1 with UWP selected as the platform. I'm curious if you try in 2018.3.9f1 (which is the [recomended version](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/ProjectSettings/ProjectVersion.txt) for that branch) if you see the same beahvior?

**Comment by LocalJoost** [comment]
No I used 2018.3.6.f1 as I stated in the original issue. That was the recommended version until shortly 😉

I will try with your version later. It’s time for bed here 😉

Joost van Schaik

Windows Development MVP & Windows Insider MVP
Sent from my Surface Go

"The world as I envision it in my head is such a more interesting place"


________________________________

**Comment by LocalJoost** [comment]
Allright this is pretty much driving me insane.

So what I did was the following:

  *   To be able to offer a minimal project, I removed the Libary and Temp folders
  *   So I just opened the project again – in the same Unity version that I used before (2018.3.6.f1)
  *   The sources needed to be parsed of course again
  *   I started play mode
  *   And both blocks became red, just like you said

I swear it did not work. This was actually a repro from another project. Maybe a Unity bug. In any case I am going to upgrade Unity.

Thanks. I will close the incident. I will come back to it if I can find why and when this thing happens. The Shader is in any case not the cause.

Joost van Schaik

Windows Development MVP & Windows Insider MVP
Sent from my over-the-top-spec'd Windows Mixed Reality development beast

"Where we go we don't need... roads"

________________________________
From: Joost van Schaik <joostvanschaik@outlook.com>
Sent: Wednesday, April 3, 2019 9:25:42 PM
To: Microsoft/MixedRealityToolkit-Unity
Subject: RE: [Microsoft/MixedRealityToolkit-Unity] InteractableHighlight doesn't work with MRTK Standard shader material (#3786)

No I used 2018.3.6.f1 as I stated in the original issue. That was the recommended version until shortly 😉

I will try with your version later. It’s time for bed here 😉

Joost van Schaik

Windows Development MVP & Windows Insider MVP
Sent from my Surface Go

"The world as I envision it in my head is such a more interesting place"


________________________________

**Comment by Cameron-Micka** [comment]
Thank you for trying that out @LocalJoost! I've certainly seen Unity issues around stale Library files, _git clean -xdf_ has become one of my most used commands. ;) Please let me know if this bug pops up again.
