### ISSUE TITLE
PokePointer proximity checks loops though list of NearInteractionTouchables

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#3806]
## Overview
Currently the PokePointer simply [iterates though a static list of NearInteractionTouchables](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs#L61) to determine the closest one. It would be nice if we could switch this over to using Unity physics queries to improve performance (if many NearInteractionTouchables are introduced into a scene) and be able to use other physics query filters such as layers.

## Unity Editor Version
2018.3.9f1

## Mixed Reality Toolkit Release Version
mrtk_development branch

**Comment by Troy-Ferrell** [comment]
@Cameron-Micka looks like the PokePointer.cs does use Physics queries except for Unity UI now?

**Comment by Cameron-Micka** [comment]
@Troy-Ferrell oh nice! I didn't even see @lukastoenneMS fixed that in  https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4942 I would say this can be closed now.
