### ISSUE TITLE
AppBar's show/done button is not pressable on the device

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/MixedRealityToolkit-Unity#3809]
## Overview
On HL2 device, App Bar's Show/Adjust/Done buttons are not pressable. 
In the Unity editor, everything works fine.

## Expected Behavior
Works with hand interactions

## Actual Behavior
Does not work with hand press interaction

## Steps to reproduce
Build and deploy HandInteracitonExamples scene.

**Comment by Railboy** [comment]
Testing now on device. I'm finding that if you interact with the buttons using far interaction, then they become pressable. Once pressed, buttons can no longer be pressed until they've been triggered via far interaction again. Very strange.

**Comment by cre8ivepark** [comment]
Fixed by #3832
