### ISSUE TITLE
Billboard.cs doesn't have X as a pivot axis

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#383]
It was removed because it wasn't working properly.

References:
https://github.com/Microsoft/HoloToolkit-Unity/pull/382#issuecomment-266093566
https://github.com/Microsoft/HoloToolkit-Unity/commit/37247d9489910735b833f5bb20b3be840a07a5b0#diff-40903bdeebaf71c08a776607e5cb91e0

**Comment by HodgsonSDAS** [comment]
https://github.com/Microsoft/HoloToolkit-Unity/issues/208

**Comment by keveleigh** [comment]
Oh, good catch!

**Comment by keveleigh** [comment]
Or, well, I guess it's not 100% a duplicate. Thanks for pointing out the related Issue!

**Comment by HodgsonSDAS** [comment]
Yeah not exactly a duplicate but related!
