### ISSUE TITLE
Unexpected Occlusion Shader behavior on Mixed Reality headset

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#3842]
## Overview
So, maybe this isn't a bug and I'm trying to do something for which the system isn't designed, but the MRTK_Occlusion shader exhibits odd / different behavior on a Mixed Reality Headset versus in Hololens (in Holographic Emulation).

## Expected Behavior
Good question, but I guess on in a VR system I would expect it to occlude everything placed in the scene but to show the skybox behind. 

## Actual Behavior
Works as expected on HoloLens, on WMR headset shows odd distortion, as if it is partially reflecting (but with distortion) the object behind, and partially occluding. As you move around the scene the distortion pattern, reflection patterns move with you though in a trippy fashion.

In this image, a sphere with the occusion shader is in front of a red cube and another green cube and you can through them to the black background.
(https://drive.google.com/file/d/1b1v8T0bN-o4fELoabiTDva9H0yi9SEEd/view?usp=sharing)

In this image the sphere with the occlusion shader (positioned visually at the bottom of the cube, is partially transparent revealing the skybox, and partially distorted showing parts of the red cube behind.
https://drive.google.com/file/d/1_IXncwIP0TR-GNpCpA-IOW3wGab9wnNF/view?usp=sharing

## Steps to reproduce
_(Links to sample github project preferred)_
Put an object with the MRTK_Occlusion shader on it, in front of another object and try running in both Holographic Emulation mode and on a WMR headset.

## Unity Editor Version
2018.3.11f1

## Mixed Reality Toolkit Release Version
mrtk_development latest as of this morning

**Comment by davidkline-ms** [comment]
@generiddick, MRTK v2 is using Unity's built-in occlusion shader for the MRTK_Occlusion material.  Can you try replacing it with the Occlusion shader from the HoloToolkit? (https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/htk_release/Assets/HoloToolkit/SpatialMapping/Shaders/Occlusion.shader)

If this resolves what you are seeing, we will report this issue to Unity. If not, then @Cameron-Micka (assigned) may be able to help.

Thanks!

**Comment by Cameron-Micka** [comment]
Hi @genereddick, I was able to reproduce this locally with Unity's occlusion shader and the HoloToolkit one. The odd distortion you are seeing is the "un-cleared" framebuffer from the previous frames. When using a Unity skybox (which is the default for immersive headsets) the back buffer doesn't get cleared, which is a common optimization you see in many 3D apps/games and results in a "smeared pixel" look. The smear is occurring because the Unity and HoloToolkit shaders don't write to the color buffer, just the depth buffer. To fix this you could go the camera (or the camera profile in the new MRTK) and set the "Clear Flags" to "Solid Color" and pick a color to clear to each frame. If that isn't the desired look you are going for there are a few other techniques we could try.

**Comment by genereddick** [comment]
@davidkline-ms I can confirm that the HoloToolkit shader has the same issue.

@Cameron-Micka That technique sort of works but visually it seems odd / sub-par compared to the fairly seamless effect on HoloLens. The buffer clearing seems to happen slower than head movement so the edges are not smooth for a frame or more until you stop moving and it can catch up, and it appears much more obvious (not sure why exactly), that the occluder is in front of the occludee (whereas on HoloLens it just looks like a hole in the object). 

You also lose the ability to have a skybox (as far as I can see you can either have clearflags and a color or a skybox but not both). 


This is an edge usage case usage for me -- I can handle the desired effect it in code instead -- so if you have more important things to do I wouldn't want to pull you off of them, but I'm happy to try other techniques to see if there is a viable work-around as I'm curious.

**Comment by Cameron-Micka** [comment]
@genereddick There are a few routes you could go down. If you are looking to simply occlude/clip geometry you could use the stencil buffer capabilities in the MRTK/Standard shader (you can see an example if this I the MaterialGallery scene (the portal). Also, if you just want to clip meshes with a shape (like the sphere in your example images) you can use the MRTK Clipping Primitives (Plane, Sphere, Box) which you can also find example usage of in the back row of the MaterialGallery. You *might* also be able to write a custom skybox shader that get's rendered over occlusion geometry, but I haven't tested this in Unity.

**Comment by genereddick** [comment]
@Cameron-Micka OK, I think the stencil buffer or clipping primitives will work for what I want. Thanks for the help.

**Comment by Cameron-Micka** [comment]
@genereddick Excellent! Please let me know if you have any questions.
