### ISSUE TITLE
ManipulationHandler should use pointer pose instead of SpatialGrip interaction

### ISSUE THREAD

**Issue by luis-valverde-ms** [Microsoft/MixedRealityToolkit-Unity#3863]
ManipulationHandler moves the manipulated object using the first interaction (input) of SpatialGrip type in the controller that is driving the pointer that is driving the handler. We should be using the pointer pose (pointer.Position and .Rotation) instead to isolate us from the details of the controller driving the pointer.

An immediate consequence of the current code is that we can't manipulate an object with an Xbox controller because, even though it is used to drive a pointer in conjunction with gaze, it doesn't have a SpatialGrip interaction.

Hit with rc1_stabilization at commit 3f92b5fbbef98045d378d63963a89d5dc9ee1955

**Comment by julenka** [comment]
Fixed by #4056
