### ISSUE TITLE
Inspector null reference exceptions on initial configure

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#3869]
When just using the foundation package without the examples, two null reference exceptions are thrown when doing the initial add to scene and configure. 

Filing the issue to track the resolution, but from what we can see this doesn't affect the functionality of the scene (nor does it repro again after creating a new scene and doing the same operation)

**Comment by chrisfromwork** [comment]
Assigning to Yoyozilla for the time being.

**Comment by wiwei** [comment]
Closing this out - this is an old one and I haven't seen this recently.
