### ISSUE TITLE
Bounding box has a offset when not explicitly setting the Bound Override 

### ISSUE THREAD

**Issue by Yoyozilla** [microsoft/MixedRealityToolkit-Unity#3871]
## Overview
Added bounding box to a simple cylinder 

## Expected Behavior
bounding box shows up around the cylinder 

## Actual Behavior
bounding box shows up with an offset to the actual cylinder 

## Steps to reproduce
_(Links to sample github project preferred)_

**Comment by julenka** [comment]
Doesn't repro on rc2, looks like it's been fixed.
