### ISSUE TITLE
Inconsistencies between profile window messages

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#3876]
## Overview
New Profiles, like the Input Simulation profile have additional "helpful" messages on them.  However, this is now inconsistent with the rest of the profiles in the MRTK.

Should pick a standard and update all screens to match.

Pointer Profile
![image](https://user-images.githubusercontent.com/1793042/55669585-1518b400-5871-11e9-9e71-1abc8339751e.png)

Input Simulation Profile
![image](https://user-images.githubusercontent.com/1793042/55669594-26fa5700-5871-11e9-8ba4-4c9b8db8c9f5.png)

## Expected Behavior
Screen behaviour / look and feel should be the same across all profiles.

## Actual Behavior
Inconsistent behaviour

## Steps to reproduce
Look at all profiles

## Unity Editor Version
Unity 2018.3.11

## Mixed Reality Toolkit Release Version
MRTK-RC1

**Comment by davidkline-ms** [comment]
Will investigate and address while making related profile inspector changes. thanks!

**Comment by chrisfromwork** [comment]
@SimonDarksideJ and @Railboy our expectation for fixing this is that we should add these messages to all profiles. Would this suggested changes suffice in your twos minds?

**Comment by davidkline-ms** [comment]
The images as shown above are encountered only when the MRTK object is not in the scene. The next part of the #3545 work modifies the behavior and eliminates this specific issue.

Thanks!

**Comment by Yoyozilla** [comment]
@davidkline-ms   Is this addressed in the latest profile updates and service facades?

**Comment by Railboy** [comment]
@Yoyozilla no we didn't tackle this issue in the service facade PR.

I'm still waiting on an official style guide a la #3908 to come together (of which this issue would be a part) before I try to homogenize everything. So this might be a chicken-and-egg problem.
