### ISSUE TITLE
Video capture offset holograms with camera

### ISSUE THREAD

**Issue by StarWardo** [Microsoft/MixedRealityToolkit-Unity#3877]
Clearly stated in the MRTK video about interactions with Hololens v2.

Recorded with mixed reality capture on Hololens v2
The video shows holograms with offset to the camera.

Cant we solve this grammatically? Introducing the offset from the camera inside the output of the video to align the holograms correctly? 

Its a shame to show offset in hand tracking were there actually is non.

**Comment by chrisfromwork** [comment]
Hello,

A few questions to try and better understand your issue:
1) Is there a specific MRTK feature that should be improved?
2) Is this issue describing a bug in mixed reality capture?
3) Which MRTK video are you referring to?

**Comment by cre8ivepark** [comment]
The team at Microsoft is working on this and making good progress!

**Comment by Yoyozilla** [comment]
Closing as this is getting addressed (coming very soon!)! Closing this issue for now.
