### ISSUE TITLE
[Docs] Required Unity components not mentioned

### ISSUE THREAD

**Issue by AmineI** [microsoft/MixedRealityToolkit-Unity#3878]
Hi there,

I just had a look at the MRTK v2 "Getting Started" documentation as I'm planning to migrate my HTK projects soon-ish, and couldn't find any mention of the required components of the Unity installation.

I think I can remember from HTK that something around the lines of "Windows Store backend" was required, but these names changed in Unity 2018.x, and I'm left wondering what's needed. UWP .NET ? UWP IL2CPP ? Both ? Maybe more ? The documentation could be more clear by specifying this in the prerequisites, I believe.

![image](https://user-images.githubusercontent.com/15179425/55682024-9d5c8f00-592d-11e9-8f88-6a31ef71aa1c.png)

Thanks for your time !

**Comment by Alexees** [comment]
It actually depends on what you are planning to use the toolkit for. It's up to you what runtime you want to use. Regarding the screenshot, this seems to be older as newer versions of Unity do not even ship with UWP. NET anymore.
As more and more platforms get built into the tookit it's just a matter of your project using them, the Toolkit should compile fine.

**Comment by AmineI** [comment]
I see, thanks for your answer ! But while runtimes indeed depends on what I'm planning to do (here, it's UWP I'm targeting so I wasn't wondering about that), it doesn't really answer which scripting backend is required/supported though (.NET/IL2CPP).

> Regarding the screenshot, this seems to be older as newer versions of Unity do not even ship with UWP. NET anymore.

Older ? It actually is from 2018.3.11f1, which is the latest official release AFAIK ? Am I missing Something maybe ?

**Comment by Alexees** [comment]
> Older ? It actually is from 2018.3.11f1, which is the latest official release AFAIK ? Am I missing Something maybe ?

Oh, well then it must have been 2019.x... my fault. Still, .NET is going to be deprecated, so you're better off using IL2CPP

**Comment by Yoyozilla** [comment]
Unity 2018.3 supports both .NET and il2cpp.
MRTK supports .Net and il2cpp on the recommended 2018.3.x version of Unity. 
.NET support is removed in Unity 2019
