### ISSUE TITLE
[Question] How to get Mixed Reality Portal bugs fixed?

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3880]
I'm asking this here because nobody cares on the Feedback Hub and this is the closest I can get to Microsoft staff.
A toolkit or a software is just as good as it's environment. There are still a couple of bugs in the Mixed Reality Portal that makes working with it a little harder than necessary and considering nobody ever answered my Feedback Hub reports, this gives me the feeling that Microsoft already started to let it die...

Is that the case? How can be get those bugs solved?

**Comment by Railboy** [comment]
Do you have links to the feedback hub bugs you've submitted?

**Comment by Alexees** [comment]
Here they are:

[Mixed Reality Portal captures Inputs after being Started even though blue bar is not shown](https://aka.ms/AA4q0t8)

[Volume Mixer does not remember Mixed Reality Portal Mute](https://aka.ms/AA4qg78)

[Mixed Reality Portal freezes in Simulation mode when asked for Microphone access](https://aka.ms/AA4qg7a)

**Comment by davidkline-ms** [comment]
@Alexees , thank you for the links!

**Comment by Alexees** [comment]
And one more, which more of a nuicance than a real bug. Whenever Unity ran once on the MR Portal, while listening to Spotify, Unity for some reason captures the speakers and you only ever hear music when focusing a different application. You have to restart Unity to get rid of the capture. This is quite new and I don't know when that started happening...

**Comment by Alexees** [comment]
And while we're at it:
- The Store bag has a "..." button at the front. First of all it doesn't do anything when clicked and secondly, there's an invisible button (just the class block) to the right of it, which shouldn't be there.

**Comment by davidkline-ms** [comment]
Feedback issues forwarded to the appropriate team.  Please continue to file them via the Feedback Hub.
