### ISSUE TITLE
In-Editor Input Simulation not working

### ISSUE THREAD

**Issue by SimMue** [Microsoft/MixedRealityToolkit-Unity#3883]
## Overview
When trying to use In-Editor Input Simulation I'm not able to control the camera.

## Expected Behavior
In-Editor Input Simulation is enabled by default and the camera can be controlled by pressing and holding the Mouse Look Button together with the WSAD buttons.

## Actual Behavior
Camera is not moving, only the FPS-box is moving.

## Steps to reproduce
1. Create new unity project
2. Install MRTK asset
3. Click Mixed Reality Toolkit --> Add to Scene and Configure...
4. Click play button
5. Try to move the camera as mentioned here:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSimulation/InputSimulationService.html

## Unity Editor Version
Unity 2018.3.7f1

## Mixed Reality Toolkit Release Version
v2.0.0-RC1

**Comment by lukastoenneMS** [comment]
I could not repro this, the camera rotation/movement works for for me.

@SimMue The default scene is devoid of any objects, so the horizon isn't really changing (other than tilting up and down). Have you tried adding a few objects and see if you can move relative to those?

**Comment by lukastoenneMS** [comment]
You can also select the Main Camera object and look at the Transform values, these should change when you rotate/move.
![image](https://user-images.githubusercontent.com/47210016/55740506-20134600-5a23-11e9-9d90-1cbb3b858230.png)

**Comment by SimMue** [comment]
Thank you for your reply.

I finally found the problem.
I had the Holographic Emulation Mode set to "Simulate in Editor". Therefore I wasn't able to control the camera.

Thanks for your help

**Comment by lukastoenneMS** [comment]
Ah yes, the Holographic Emulation completely takes over the camera, didn't think of that. Glad you found it anyway.

**Comment by elvirus839** [comment]
@SimMue could you please indicate where can I change the Holographic Emulation Mode? I am having the same problem, not able to navigate through the scene.

**Comment by SimMue** [comment]
@elvirus839  you can change it under "Window/XR/Holographic Emulation"
![image](https://user-images.githubusercontent.com/13121693/58469281-79ecde00-813f-11e9-951c-d9cdb92eeda8.png)

And then you can select your Emulation Mode and set it to none:
![image](https://user-images.githubusercontent.com/13121693/58469393-b4567b00-813f-11e9-821e-de19cc7fd95f.png)

**Comment by elvirus839** [comment]
Thanks for the prompt reply.
Apparently on my setup it was already set to "None" ... 
I am also having the following error when pressing play:
![image](https://user-images.githubusercontent.com/5313106/58469903-cdabf700-8140-11e9-8ec6-5dc0c499554c.png)

Any idea how to solve it?
