### ISSUE TITLE
KeyNotFoundException when using XBoxOne Pad triggers or A button on an Interactable

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#3891]
## Overview
A blocking exception is raised at each frame when using a button from xboxone controller in editor, play mode, with default mixed reality profile.

Also happens on most demo scenes (check TooltipExamples, and press on the blue diamond on the right)

## Expected Behavior
No Exception when using a Pad Key that is not mapped

## Actual Behavior
Spamming error each frame:
> KeyNotFoundException: The given key was not present in the dictionary.
>System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
>Microsoft.MixedReality.Toolkit.Input.DefaultPointerMediator.UpdatePointers () (at Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/DefaultPointerMediator.cs:107)
>Microsoft.MixedReality.Toolkit.Input.FocusProvider.UpdatePointers () (at Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs:681)
>Microsoft.MixedReality.Toolkit.Input.FocusProvider.Update () (at Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs:443)
>Microsoft.MixedReality.Toolkit.MixedRealityToolkit.UpdateAllServices () (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:994)
>Microsoft.MixedReality.Toolkit.MixedRealityToolkit.Update () (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:777)

## Steps to reproduce
- Create a new scene
- Menu Mixed Reality Toolkit > Add to scene and Configure... and choose default configuration profile
- Add a Cube in (0,0,10)
- on this cube add an Interactable Script
(optional) - set the cube as Target of the Interactable Profile

=> Click on Play in Unity Editor, and press A, LB, RB... on the joystick
- Exception is raised and all control are blocked

## Unity Editor Version
2018.3.11f1
## Mixed Reality Toolkit Release Version
v2.0.0-RC1

**Comment by gilbdev** [comment]
I tried it again with a fresh project, and i don't get the error ...
I may have broken something in the MRTK coonfiguration, or during the beta to RC1 change ...

**Comment by wiwei** [comment]
Going from Beta to RC1 involved a number of breaking changes from beta - the profiles and namespaces of things changed up enough that even merging those changes on our side was quite tricky (so I can't imagine how it would be to try to go from Beta -> RC1 as a drop-in replacement).

The other possibility is you can try copying a working configuration profile (i.e. using a fresh MRTK + project), and try to map your previous configuration to the new one.

@davidkline-ms might have other ideas.

**Comment by gilbdev** [comment]
on the 'fresh' project, i do have the exception in the "HandInteractionExamples", other examples are working fine.

**Comment by gilbdev** [comment]
looking at the code DefaultPointerMediator.cs: 
`foreach (IMixedRealityPointer otherPointer in pointerByInputSourceParent[pointer.InputSourceParent])
`
on line 107 and 137
seems it doesn't check if there is somevalue in the dictionnary

replacing with:
`HashSet<IMixedRealityPointer> children;`
 `if (pointerByInputSourceParent.TryGetValue(pointer.InputSourceParent, out children))`
get rid of the exception

**Comment by wiwei** [comment]
@Railboy

**Comment by genereddick** [comment]
I have this issue as well and it happens both on new and old projects. For old projects I have tried updating the MRTK to latest code, recreated the library folder, cleared cache all without resolution.

@gilbdev's fix above works for me

**Comment by wiwei** [comment]
Following up on this one, it looks like was actually addressed when I fixed another issue in this PR:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/3808

Finally got around to trying this out and was wondering why this wasn't reproing on latest, but yeah, this should be good now.
