### ISSUE TITLE
Scene switching / Unable to find services / NullReferenceException

### ISSUE THREAD

**Issue by Ziugy** [Microsoft/MixedRealityToolkit-Unity#3895]
## Overview
When reloading scenes with the MRTK prefab in it, you get this error:
`Unable to find IMixedRealityInputSystem service`

followed by this error every frame:
```
NullReferenceException: Object reference not set to an instance of an object

Microsoft.MixedReality.Toolkit.Input.GenericPointer..ctor (System.String pointerName, Microsoft.MixedReality.Toolkit.Input.IMixedRealityInputSource inputSourceParent) (at Assets/MRTK/MixedRealityToolkit/Providers/GenericPointer.cs:23)
```

## Expected Behavior
Able to switch scenes without profile, systems, and state of MRTK breaking.

## Actual Behavior
As stated errors are being thrown and unusable application after scene reloaded.

## Steps to reproduce
1. Load up `HandInteractionExamples`
2. Add a new script with this logic below:
```
private void Update()
{
    if (Input.GetKeyDown(KeyCode.U))
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }
}
```
3. Enter play mode and then press `U`.

## Unity Editor Version
2018.3.7f1

## Mixed Reality Toolkit Release Version
mrtk_release, RC1

**Comment by LocalJoost** [comment]
mrtk_eyes_00_RootScene does not work for probably the same reason. You cannot even start it.

**Comment by Yoyozilla** [comment]
Dupe to 3941
