### ISSUE TITLE
Add hand interaction state (touch, grab) to Interactable's states

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#3897]
## Overview
Current Interactable has four states available for HoloLens v1 and WMR controllers: Default, Focus, Pressed, Disabled. By adding additional states for the hand interactions, developers and creators can define visual/audio feedback without writing additional script. Touch and Grab event could be useful. 
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_Interactable.html

## Expected Behavior
Developers can define visual/audio feedback for Touch and Grab state in the theme of Interactable without writing code.

## Actual Behavior
Currently, there is no way to define visual/audio feedback in the Interactable. Developers have to write additional code with hand interaction related interfaces.

**Comment by killerantz** [comment]
Adding the states to show up in the themes is easy, but wiring up the input to drive those states will require code. I'm working on some updates for press right now.

**Comment by cre8ivepark** [comment]
@killerantz I guess two additional states 'Touch' and 'Grab' could be added for hand interactions. For hand interaction press, I think we can use existing 'Press' state - However, I am not clear how we can drive hand press which is currently in PressableButton script.

**Comment by killerantz** [comment]
There's a PhysicalTouch state that was added recently, it's in there and will listen for touch events I'll try to make it less reliant on other components. The grab will be something new. I saw in another script, I think the Manipulation Handler, that looks for grab and checks for the literal string of the action description. That seems breakable if the actions are changed. Is there guidance for action label/descriptions to enable grab functionality?

**Comment by julenka** [comment]
@cre8ivepark I think it would be good to clarify the meaning of grabbed and touched. Touched is easy: a near pointer is physically touching the Interactable's collider. Grabbed is less clear. An intercatable will already be in the Pressed state if a near pointer grasps the object. So why couldn't a designer just use the Pressed state? Is it really that you want to distinguish "near pressed" from "far pressed"?

**Comment by julenka** [comment]
Fixed by #4357
