### ISSUE TITLE
Missing ProgressIndicator from HTK?

### ISSUE THREAD

**Issue by mtaulty** [microsoft/MixedRealityToolkit-Unity#3899]
## Overview
The original toolkit had a ProgressIndicator which was a useful prefab and it does not seem to have made it into MRTK V2?

## Expected Behavior
I opened up a HTK project, removed the HTK, added the MRTK V2 and hoped to be able to build.

## Actual Behavior
Failed to build because ProgressIndicator seemed to be missing? It wasn't clear whether there's a direct replacement or whether it's just an omission?

## Steps to reproduce
As above.

## Unity Editor Version
2018.3.11f1

## Mixed Reality Toolkit Release Version
2.0.0-RC1

**Comment by Yoyozilla** [comment]
looks like this is done? closing. 
lars please reopen if there are remaining work.
