### ISSUE TITLE
Inspector/Editor items in the MRTK should have consistent appearance

### ISSUE THREAD

**Issue by chrisfromwork** [Microsoft/MixedRealityToolkit-Unity#3908]
## Overview
Right now there isn't any design guidance or standard control appearance in custom MRTK inspector/editor components. It seems like some sort of definition for button sizes, colors, icons, etc should be defined for reuse.

**Comment by chrisfromwork** [comment]
Assigning to @wiwei who will drive our backlog story.

**Comment by Yoyozilla** [comment]
@chrisfromwork 
could you check out Lar's Service Facades and see if that's a good solution. Reopen if you have feedback!
