### ISSUE TITLE
[Question] Virtual Keyboard support?

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3914]
I was wondering what the current cross platform solution for a virtual Keyboard in the new MRTK v2 RC1 is? The old MRTK had the Unity built keyboard. The current keyboard examples only mentions the TouchScreenKeyboard class and I guess that's primarily for HL2. It definitely does not work when running Unity with the attached Mixed Reality Portal.

https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Documentation/README_SystemKeyboard.md

Additionally: I could not find the proposed sample scene even though the RC1 branch states it was even with the mrtk_release, which is weird because it's from february:

**Comment by julenka** [comment]
Hi, this is a great question, could you please post it to stackoverflow with the MRTK tag, or update the issue to be a bug, rather than a question? We are trying to have all questions on stackoverflow so that other people can more easily find answers. Thanks!
