### ISSUE TITLE
Attention! popup while in prefab edit mode

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3915]
## Overview
When editing a prefab an recompiling code, MRTK shows it's popup about the absence of itself in the current scene, which it is not.

## Expected Behavior
No Popup during Prefab Edit mode

## Actual Behavior
Popup showing up

## Steps to reproduce
Open any prefab for editing and change some code letting Unity recompile

## Unity Editor Version
2018.3.11f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by Railboy** [comment]
Related to #3921

**Comment by chrisfromwork** [comment]
Assigning to @davidkline-ms based on other issue ownership.

**Comment by Alexees** [comment]
I wanted to add that this popup shows up like 20 times when you recompile in Prefab Edit mode.

**Comment by Yoyozilla** [comment]
Dupe 
MRTK instance added automatically to all scenes loaded in editor #3921
