### ISSUE TITLE
Feature Request: Automatic or scripted performance setting application

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#3927]
It's very easy to set different performance/shadow/rendering settings which had an inadvertently huge effect on performance. In some cases (i.e. with certain versions of unity) even turning off some settings to their lowest will not work in improving perf (i.e. shadows very low vs shadows off).

Most of the focus on our investigations has been on the hololens 2 - we should have some feature/script in the MRTK that will identify these common pitfalls (i.e. either highlighting to the user that "hey these features that you're using don't add a lot of value and can be turned off to increase performance" or just applying them automatically for the user).

The main focus here is on the hololens 2 platform (i.e. we might have platform-specific guidelines/tips/tricks)

**Comment by Ecnassianer** [comment]
Would it make sense to add a HoloLens quality level to the project's quality settings, and have that be set in the camera profile's Transparent Display Quality field? That might make it less necessary to ask for permission, and then we could do it automagically as part of MRTK's Configure step.

**Comment by wiwei** [comment]
Definitely a possibility - the tricky part is unless I feel like we have 100% confidence in each step it's difficult for me to say that it's "our way or the highway" (i.e. we automatically destroy all of your settings that you've done a lot of work in figuring out).

Really the process here is:

1) We have nothing to help people with performance issues.
2) We have a little (but not a lot) of docs to help people with perf issues.
3) We have better perf docs to help with people.
4) We have some way of applying our suggestions at a button push.
5) We can automatically fix things for people.

We are currently at step #2 and I want to work through them methodically.

**Comment by davidkline-ms** [comment]
There has been some discussion of adding a perf analyzer to check the scene for expensive shaders, etc. We should unify the efforts.

**Comment by wiwei** [comment]
This issue was filed to track those all up efforts. Unless did I file a duplicate issue about this?

**Comment by davidkline-ms** [comment]
don't believe so... i'll look

**Comment by davidkline-ms** [comment]
No pre-existing issue filed. Just confirmed.

**Comment by provencher** [comment]
I'll add that I don't want the MRTK automatically changing performance settings for me.

I'm happy to have it make suggestions, but invasive editor tips should be toggle-able. 

This raises a greater concern regarding invasive editor scripting. I think most tips and non-mrtk-component-specific editor scripts should be disable-able, as they slow down UI responsiveness and don't add much utility for experienced users.
![image](https://user-images.githubusercontent.com/7420990/55890475-bdd05780-5b80-11e9-84ed-67d3e581cb30.png)

For example, the MRTK modifies the editor display of all canvas components, which are a Unity-specific feature.

Perhaps some more granular controls could be achieved regarding editor scripts.

**Comment by Railboy** [comment]
>we should have some feature/script in the MRTK that will identify these common pitfalls (i.e. either highlighting to the user that "hey these features that you're using don't add a lot of value and can be turned off to increase performance" or just applying them automatically for the user).

I'm working on a tool that does exactly this. But it only highlights pitfalls and makes suggestions. It doesn't apply any changes, for all the reasons you point out.

**Comment by Cameron-Micka** [comment]
I have a small script I've written that put's your XR devices into ~3 performance buckets. We could then use that to provide recommendations to the user. (Similar to how the Steam VR plugin guides users down the best path.) It would also be nice to have a tool that points out expensive materials and geometry in the scene. I think we've been talking about that for awhile now. haha

**Comment by Troy-Ferrell** [comment]
Current work in progress

![image](https://user-images.githubusercontent.com/25975362/57660835-3c178380-759d-11e9-92f7-110c073954d0.png)
