### ISSUE TITLE
HolographicButton inevitably requires MixedRealityToolkit in the scene

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#3932]
## Overview
I was trying to rebuild a UI using the MRKT HolographicButton. This scene as additively loaded and therefore does not have a MixedRealityToolkit in the same scene. But the button requires it to let me configure its InputAction. It even complains with a red sign at the top in the inspector. This makes building UI in seperate scenes or for loading from prefabs a problem.

Several times I read that the preferred way is to have one initial setup scene with the Toolkit. Fixing this looks like not so easy as it requires the Toolkit to be globally accessible without being an instance in any scene.

## Expected Behavior
I can configure the buttons no matter the existence of the toolkit, it'll be there, trust me :)

## Actual Behavior
I cannot configure the button

## Steps to reproduce
Add a HolographicButton to an empty scene

## Unity Editor Version
2018.3.11.f1

## Mixed Reality Toolkit Release Version
mrtk_release

**Comment by Alexees** [comment]
Maybe it is possible to move the Toolkit totally off scenes. Using:

[InitializeOnLoad](https://docs.unity3d.com/Manual/RunningEditorCodeOnLaunch.html) for the Editor
[RuntimeInitializeOnLoadMethod](https://docs.unity3d.com/ScriptReference/RuntimeInitializeOnLoadMethodAttribute-ctor.html) for the final game

If this works, the toolkit could just "exist" and we're done with "add it to frist scene" or "add it to every scene".. "what if additive loading is used instead of single loading...." blablabla

**Comment by Railboy** [comment]
Related: #3921

**Comment by Alexees** [comment]
@Railboy I don't think this is related to #3921. That Issue is about avoiding automatically adding MRTK content while this here is about the HolographicButton desperately needing one. It's not automatically forcing it to be added but rather is not configurable if it's not present.

**Comment by chrisfromwork** [comment]
@davidkline-ms this seems related to another issue you own. If there is a greater amount of work required for enabling multiple scene experiences and this needs a new owner, please reach out.

**Comment by Railboy** [comment]
@Alexees You're correct. I've just been lumping all these mrtk singleton related issues into one bucket while we sort out our multi-scene story.

**Comment by Yoyozilla** [comment]
@Railboy   could we have 1 issue that track our multi-scene story planning that links to all the the related issues.
