### ISSUE TITLE
Slow in Stopping Playback in Unity

### ISSUE THREAD

**Issue by DaRockJaeger** [microsoft/MixedRealityToolkit-Unity#3949]
## Overview
When Pressing Play Button in Unity, Application starts really fast (3 seconds).
But when stopping in Unity, it takes about 20 seconds until I can use Unity again.

## Expected Behavior
When stopping in Unity, Editor needs 3 seconds to stop playback.

## Actual Behavior
When stopping in Unity, Editor needs 10 to 15 seconds to stop playback and be usable again.

## Steps to reproduce
1. Create empty Scene.
2. Go Mixed-Reality-Toolkit -> Add to Scene and Configure
3. Start in Unity, and press Stop

## Unity Editor Version
2018.3.12f1
## Mixed Reality Toolkit Release Version
2.0.0 RC1

**Comment by quakeulf** [comment]
I have this exact same issue. It takes me up to 30 seconds after stopping play-mode in editor to resume using it.

It does not happen in other projects in the same version of Unity. I work in WebGL at home and it is not near as slow.

Have you tried 2018.3.10*? It could work better. At least it did for me.

**Comment by wiwei** [comment]
Looking through some old issues, this is possibly handed by:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4439

There's some wierdness with starting/stopping the Unity speech APIs that made the editor hang.
