### ISSUE TITLE
"Microsoft.MixedReality.Toolkit" has dependency on editor assemblies

### ISSUE THREAD

**Issue by lukastoenneMS** [microsoft/MixedRealityToolkit-Unity#3952]
## Overview
The core "Microsoft.MixedReality.Toolkit" assembly has a dependency on
        "Microsoft.MixedReality.Toolkit.Core.Utilities.Editor",
        "Microsoft.MixedReality.Toolkit.Core.Definitions.Utilities.Editor",

It seems to use a number of utility classes from the editor assemblies, wrapped in `#if UNITY_EDITOR`. Apart from good design principle, this also prevents the editor assemblies in turn from referencing the "Microsoft.MixedReality.Toolkit" assembly, which should be possible.

## Expected Behavior
Core should not have a reference on editor assemblies.

## Actual Behavior
It has.

## Steps to reproduce

- Look at [MixedRealityToolkit.asmdef](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit/MixedRealityToolkit.asmdef)
- Try to add dependency on `"Microsoft.MixedReality.Toolkit"` in [MixedRealityToolkit.Core.Utilities.Editor.asmdef](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit/Utilities/Editor/MixedRealityToolkit.Core.Utilities.Editor.asmdef)

## Mixed Reality Toolkit Release Version
MRTK v2 RC1

**Comment by StephenHodgson** [comment]
The reason for this is so the editor scripts are compiled and ran first. Without this then some of the initial editor setup steps will fail.

**Comment by chrisfromwork** [comment]
Assigning to @lukastoenneMS for the time being.

**Comment by davidkline-ms** [comment]
No runtime assemblies should have editor assembly dependencies.

**Comment by davidkline-ms** [comment]
MRTK3 is being very careful to ensure proper package and assembly separation and dependency management. If you find an issue there, please file issue(s) pointing out the specific instances. Thanks!
