### ISSUE TITLE
Mr. Teekay's Standard.shader shows up as pink (without issues) in Unity 2019.2.0a11 (LWRP)

### ISSUE THREAD

**Issue by quakeulf** [microsoft/MixedRealityToolkit-Unity#3953]
## Overview
The newest **LightweightRenderPipelineAsset** is incompatible with the shader. **Removing** the _reference_ to **it** in **_Project Settings > Graphics > Scriptable Render Pipeline Settings_** makes it return to _normal._
## Expected Behavior
A nice feel of **_hologrammatic_** shade.
## Actual Behavior
Plain **_pink._**
## Steps to reproduce
1. Import **MRTK v2 RC1** into the specified version of _Unity._
2. Make _sure_ that the **Scriptable Render Pipeline Settings** in **_Project Settings > Graphics > Scriptable Render Pipeline Settings_** is _set_ to **LWRP_Asset(LightweightRenderPipelineAsset)**
3. Open a **scene** and use the **_Standard.shader_** on a _material on an object_ on the **scene.**
4. It's hereby _pink._

## Unity Editor Version
**Unity** _2019.2.0a11_
## Mixed Reality Toolkit Release Version
**MRTK** _v2_ RC**1**

**Comment by provencher** [comment]
@quakeulf This is not a bug.

The MRTK standard shader is built against a different rendering pipeline. Any shader in the MRTK needs to be completely rebuilt for the LWRP. If you'd like to volunteer such a contribution, I'm sure the community would appreciate it. Until then, if you want the LWRP, you'll need to write new shaders, or use the default unity ones and hope they run well enough.

**Comment by Cameron-Micka** [comment]
Hi @quakeulf, the LWRP is something I hope to support. But, I have yet to evaluate what work needs to be done. I'll be sure to post back here as I know more. :)

**Comment by Cameron-Micka** [comment]
A pull request is up to address this: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4311
