### ISSUE TITLE
MRTK v2 Release Candidate 1 How can i delete the status bar for CPU fps, peak, used, Limit ?

### ISSUE THREAD

**Issue by zxzkf1992** [Microsoft/MixedRealityToolkit-Unity#3954]
## Overview
I am developing a project for HoloLens. When I run my project, a status bar appears, showing FPS, memory usage, and so on. How can I delete this status bar or not display it?
![微信图片_20190412154417](https://user-images.githubusercontent.com/45712264/56042155-a9d05580-5d3a-11e9-9870-0e383ae38219.png)

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.3.11f
## Mixed Reality Toolkit Release Version
MRTK v2 Release Candidate 1

**Comment by provencher** [comment]
Remove the diagnostics profile from the MRTK instance

**Comment by ArtieTwelve** [comment]
To remove the floating Diagnostics screen from your project:
Open MixedRealityToolKit in the Inspector.
Scroll down to  Diagnostic Systems Settings
Unclick Enable Diagnostics System.

**Comment by wiwei** [comment]
I can probably update the doc here to have those steps from @ArtieTwelve as well:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Diagnostics/ConfiguringDiagnostics.html

**Comment by zxzkf1992** [comment]
> To remove the floating Diagnostics screen from your project:
> Open MixedRealityToolKit in the Inspector.
> Scroll down to Diagnostic Systems Settings
> Unclick Enable Diagnostics System.

Thank you, I will try it.

**Comment by zxzkf1992** [comment]
@provencher @ArtieTwelve @wiwei Thank you all, I will try it.

**Comment by davidkline-ms** [comment]
@ArtieTwelve's steps are correct. 

Please note that it is highly recommended to keep the diagnostics profiler enabled during the development of your application so that you can spot performance issues (ex: frame rate below 60) when they are easiest to fix.

**Comment by davidkline-ms** [comment]
This document describes enabling the diagnostics system in detail.

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Diagnostics/DiagnosticsSystemGettingStarted.html
