### ISSUE TITLE
Proposal: Make it easier to obtain the position of the primary active cursor

### ISSUE THREAD

**Issue by provencher** [microsoft/MixedRealityToolkit-Unity#3957]
## Overview
Currently, it is rather difficult to obtain the position of the active cursor in the scene. 

The focus handler system provides many pointers, and it is unclear which one is driving the active cursor. Further, there is no obvious means of gaining access to the active cursor in the scene.

Given that only one UIRayCasting camera is active at once in the scene, so it would make sense to be able to at least obtain information about the pointer driving that camera's position and orientation.

## Expected Behavior
MixedRealityToolkit.InputSystem should contain an easy getter for obtaining information about the primary cursor in the scene. If there are two active cursors (one for each hand), it should return the cursor drawn by the dominant hand.

## Actual Behavior
The MixedRealityToolkit.InputSystem can provide a list of many pointers and does not provide any information about the active cursor.
## Unity Editor Version
Unity 2018.3.8f1

## Mixed Reality Toolkit Release Version
v2 RC1

**Comment by provencher** [comment]
@luis-valverde-ms what do you think about this?

**Comment by luis-valverde-ms** [comment]
@provencher , it doesn't sound unreasonable. Can I ask about your particular use cases?

**Comment by provencher** [comment]
@luis-valverde-ms My use case involves interfacing with an existing UI interaction system, without rendering my scenes incompatible with MRTK interactibles.

I have an existing UI system which requires a Pointer origin and direction to draw a ray

That said, getting a general pointer origin and direction from the MRTK has required some clever hacking around.

The origin seems to be consistently represented by `MixedRealityToolkit.InputSystem.FocusProvider.UIRaycastCamera.transform.position;`

The cursor has been obtainable by writing code that checks for active hoverlight, as follows:
![image](https://user-images.githubusercontent.com/7420990/56051494-c65d9500-5d1c-11e9-91b1-c1dcd92197b9.png)

Finally, the direction I obtain by finding the vector drawn from the origin to the active hoverlight, which represents the active cursor.

**Comment by luis-valverde-ms** [comment]
> getting a general pointer origin and direction from the MRTK has required some clever hacking around

Did you try using IMixedRealityPointer.Position/Rotation for that?

> The origin seems to be consistently represented by MixedRealityToolkit.InputSystem.FocusProvider.UIRaycastCamera.transform.position;

I would advise against relying on that as it will contain information for the last pointer to raycast that frame.

> The cursor has been obtainable by writing code that checks for active hoverlight

Did you try using IMixedRealityPointer.BaseCursor instead?

**Comment by provencher** [comment]
The issue with relying on IMixedRealityPointer anything, is that the only way to get access to it is by iterating over this list 
`MixedRealityToolkit.InputSystem.FocusProvider.GetPointers<IMixedRealityPointer>();`

From that list, how do I know which one is driving the cursor?

**Comment by wiwei** [comment]
One more datapoint: From chats with other folks who were getting started with MRTK v2, they also had similar feedback about wanting to know the "primary" cursor or pointer, so I'm just trying to +1 this to make it clear that we have multiple points of feedback on this.

I think that the other folks who were hitting this also clarified the statement with that the concept of "primary" can be funky when you have multiple sources of input (two hands) active, but the overall request still seems like a reasonable one to ask/explore.

**Comment by provencher** [comment]
@wiwei thanks for weighing in.

Regarding your point on the funkyness of getting the "primary" pointer, I think in most app, it makes sense to expose the dominant hand if two pointers are present. There already exists some notion of "handedness" in the MRTK.

**Comment by luis-valverde-ms** [comment]
@provencher , you usually know who is driving the cursor because you implement your UI logic based on pointer events. Is the problem here that your UI is Unity UI and hence receives a native Unity UI event that does not contain a reference to the pointer/cursor that is focusing it?

**Comment by provencher** [comment]
@luis-valverde-ms the issue is that the legacy UI system has its own focus system that has nothing to do with MRTK interfaces, and as such adapting it is a lot more work than allowing it to exist alongside the default MRTK systems.

I know this is not how the MRTK is designed to be used, but exposing data about what it's doing, allows me to integrate MRTK input in existing systems, without invasively modifying them

**Comment by luis-valverde-ms** [comment]
I think I'm getting there. So, you have your own UI system/components, which neither are [Unity UI](https://docs.unity3d.com/Manual/UISystem.html) nor implement any of MRTK's [pointer events](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Pointers.html#pointer-events).

This is where I get lost, do you want to use the active MRTK pointer to trigger UI events in your system? How would you figure out the UI element the pointer is pointing at, would you redo the raycast in order to raise you own events?

**Comment by provencher** [comment]
@luis-valverde-ms Indeed I do fire my own raycasts. Its a bit redundant, but it provides a ton of flexibility.

**Comment by luis-valverde-ms** [comment]
I'd worry that, unless you perform exactly the same raycast twice, you could end up with one of your UI components and one of the MRTK/Unity UI ones with simultaneous focus from the same pointer. If you don't consider things like the IMixedRealityFocusProvider.FocusLayerMasks and IMixedRealityPointer.PrioritizedLayerMasksOverride in use, you could get different results even from the same origin and direction. 

Unless you really need to perform that second raycast yourself, I'd suggest having instead a global event listener that listens for all focus changes via IMixedRealityFocusChangedHandler and raises your UI events. 

That would still leave us with the issue of deciding which pointer we care about. For that, I'd like to give a try to the concept of _last pointer with input_ which I think it is similar to what we use in WMR portal, where you will see that the cursor ray is only displayed for the last controller you clicked. The input system could keep track of the last pointer that raised a pointer down event and report it as the primary cursor. 

What do you think?

**Comment by provencher** [comment]
@luis-valverde-ms thanks for breaking that down.

I do agree that it's quite possible to get some variance if the layer masks are different. 

The global listener suggestion isn't a bad one, however it comes at the cost of overhauling all my UI elements so that they will raise events when the MRTK raycast points at them. 

My issue here especially, comes from the fact that I'm maintaing several apps with different UI interaction models. One in particular uses screen space graphics raycasting in order to determine focus, while the others use regular world raycasting for highlight. The former has additional code in place in order to snap to ui elements as the cursor is near, but not quite over the element. This was especially helpful given the HL1's gaze cursor isn't as stable as a hand caster.

In both of these cases however, the ray is initially cast from a pointer origin in a pointer direction. I use a common framework between these apps that both make use of this functionality, and both have very different cursor behaviors.

Finally, I'm perfectly comfortable with the notion of the last pointer, as in the WMR portal. Most vr systems are setup with this paradigm, and it's more than suitable. In our cases, the primary use case is going to be HoloLens 1 and 2, and I don't see it as important to select UI with more than one hand at once. 

The important thing is largely that the bendy pointer ray lines up with where my ray cast is firing. 
For the time being, as I've mentioned previously, I can accomplish this is simply by reversing the ray draw between the UIRaycastCamera and the first active cursor I find. Getting the last pointer used would be even more robust.

**Comment by luis-valverde-ms** [comment]
The idea behind the global listener is to avoid having to modify your UI elements by emulating the way you usually drive them based on the incoming MRTK events. The logic for that should reside in that shared, global listener that dispatches to the individual UI elements.

Nevertheless, I'll create a PR for that last _pointer with input change_ and let you give it a try.

**Comment by provencher** [comment]
Perhaps I misunderstand the global listener workflow you're proposing.

Will the global listener just receive the pointer state every update, which I then route to my UI? 
I assumed pointer still require interacting with some MRTK UI in order to trigger events.

Cheers for working on that PR however. It is much appreciated.

**Comment by luis-valverde-ms** [comment]
Pointer events are raised when the raycast hits something, whether it is UI or not, but looking at the code I see that at the moment some of them (focus changed, enter and exit) are not dispatched to the global listener.

**Comment by luis-valverde-ms** [comment]
@provencher , can you gives this a try? https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3983
@wiwei , do you think the changes in that PR could be useful too for that other people trying to figure out the primary pointer?

**Comment by provencher** [comment]
@luisalvesmartinsms that PR is certainly on the right track. It needs a bit of work however. Wrote some comments on the PR

**Comment by chrisfromwork** [comment]
Assigning to @luis-valverde-ms

**Comment by provencher** [comment]
@luis-valverde-ms I've been experimenting with this for a week now and here's where I'm at.

OnPointerDown, I store the active pointer. The issue is that the pointer is constantly destroyed when it goes out of view, so frequent clicking is required to get up to date things.

Beyond that I experimented with filtering out near interaction pointer, and finding which pointer is best represented by the ui targetting camera.

This code works about 90% of the time, but it does occasionally fail. I think this is a good way to look forward however.



`private Vector3 GetReferenceDirection()
        {
            return MixedRealityToolkit.InputSystem.FocusProvider.UIRaycastCamera.transform.rotation * Vector3.forward;
        }`

`        private void Update()
        {
            if (PointerValid) return;

            IMixedRealityPointer closestPointerToReference = null;
            float referenceDotProduct = -1f;

            var referencePointerDirection = GetReferenceDirection();

            foreach (var pointer in MixedRealityToolkit.InputSystem.FocusProvider.GetPointers<IMixedRealityPointer>())
            {
                // Filter out near pointers and inactive pointers
                if (!pointer.IsActive || (pointer as IMixedRealityNearPointer) != null) continue;

                float dotProduct = Vector3.Dot(pointer.Rotation * Vector3.forward, referencePointerDirection);

                if (!(dotProduct >= referenceDotProduct)) continue;

                referenceDotProduct = dotProduct;
                closestPointerToReference = pointer;
            }

            ActivePointer = closestPointerToReference;
            //Debug.Log("New Active Pointer: " + ActivePointer);
        }`

**Comment by jbienzms** [comment]
Hey @provencher, interesting code. I'd like to understand a little better what the code is trying to do. When you say "which pointer is best represented by the ui targetting camera", how are you determining the "ui targeting camera"? Are you referring to the one that is referenced by the Unity UI system? You may not be referring to that one, but if you are I was under the impression that one of the reasons we moved to Interactables and away from Unity UI in v-next was to support multiple pointers and touch sources being able to interact with targets at the same time. But again, I could be misunderstanding what you mean here.

In your code above, what does the method `GetReferenceDirection()` return?

**Comment by provencher** [comment]
Hi @jbienzms 

I've found that `MixedRealityToolkit.InputSystem.FocusProvider.UIRaycastCamera.transform.rotation * Vector3.forward;` is roughly mapped to the direction of the pointer, but not exactly. 

That camera moves to match the head rotation when the GGV pointer is active, and then moves to the hand position and orientation when the hand far interaction pointer is active. From what I found there is also only one of those. I use that as a metric for aligning with the far interaction pointer.

I use this simply because I have failed to find any other suitable metrics

**Comment by luis-valverde-ms** [comment]
@provencher , I'd advise against taking a dependency on the value of `UIRaycastCamera.transform`. It is used by `FocusProvider` to perform raycasts against Unity UI for each pointer. The specific value it will end up with depends on the last pointer updated by the focus provider and there are no guarantees on pointer update order.

Would the forward direction of the main camera (`CameraCache.Main.transform.forward`) be a good altearnative for you here?

**Comment by provencher** [comment]
@luis-valverde-ms 
I'll try using the main camera's forward direction as an alternative, however the reason I was using the rasycast camera was because it seemed to move to the far interaction pointer's world source dynamically. 

Thinking about this further, I think my ideal usage scenario the following:
Before any click is detected:
- The first pointer to draw a cursor on screen is held onto
- If that first pointer goes out of view, the system switches to whatever other pointer is currently drawing on screen
After a click is detected:
-The click pointer should be the default, and I should be able to cache it without it going null after it going off screen.
- If that pointer is no longer active (no longer in view), the system will fallback to the pointer above
- If the pointer that clicked once comes back into view, it should return as the default pointer.

My code above is trying to emulate this scenario, but between the pointers getting destroyed and not being able to know when a pointer shows up on screen, it's quite difficult to get there exactly.

**Comment by provencher** [comment]
Pointers not being destroyed is filed as a separate proposal here: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4223

**Comment by provencher** [comment]
So I have another bit of code that helps recover the pointer that was used when you last clicked.

Basically I store the name, and when my cached pointer goes stale, I just search for the one that had the same name as the one that was cached when I clicked. 

If that fails, I fallback to my dot product check.

`        private void Update()
        {
            if (PointerValid) return;

            IMixedRealityPointer closestPointerToReference = null;
            float referenceDotProduct = -1f;

            var referencePointerDirection = GetReferenceDirection();

            foreach (var pointer in MixedRealityToolkit.InputSystem.FocusProvider.GetPointers<IMixedRealityPointer>())
            {
                // Filter out near pointers and inactive pointers
                if (!pointer.IsActive || (pointer as IMixedRealityNearPointer) != null) continue;

                if (_clickPointerNameReference != null && pointer.PointerName.Equals(_clickPointerNameReference))
                {
                    closestPointerToReference = pointer;
                    Debug.Log("Found old pointer: " + _clickPointerNameReference);
                    break;
                }

                float dotProduct = Vector3.Dot(pointer.Rotation * Vector3.forward, referencePointerDirection);

                if (!(dotProduct >= referenceDotProduct)) continue;

                referenceDotProduct = dotProduct;
                closestPointerToReference = pointer;
            }

            ActivePointer = closestPointerToReference;
            //Debug.Log("New Active Pointer: " + ActivePointer);
        }`

**Comment by provencher** [comment]
Further update that should include support for controllers

`// If active pointer is gaze, search for a better one
            if (PointerValid) return;

            Handedness handInView = Handedness.None;

            // Check for controllers
            var connectedControllers = MixedRealityToolkit.InputSystem.DetectedControllers;
            bool isControllerConnected = connectedControllers.Count > 0;

            // Check if hand in view
            handInView = CheckHandInView();

            // If no hand in view or controllers are not found, we do not bother searching for a pointer and default to gaze pointer
            if (handInView == Handedness.None && !isControllerConnected)
            {
                UpdateActivePointer(MixedRealityToolkit.InputSystem.GazeProvider.GazePointer);
                return;
            }

            foreach (var pointer in MixedRealityToolkit.InputSystem.FocusProvider.GetPointers<IMixedRealityPointer>())
            {
                // Filter out near pointers and inactive pointers
                if (!pointer.IsActive) continue;

                var pointerName = pointer.PointerName;

                if (_clickPointerNameReference != null && pointerName.Equals(_clickPointerNameReference))
                {
                    UpdateActivePointer(pointer);
                    break;
                }

                // Filter out near interaction pointers
                if (pointer is IMixedRealityNearPointer) continue;

                Handedness pointerHandedness = GetPointerHandedness(pointerName);

                // Ensure we have a usable handedness
                if (pointerHandedness != Handedness.Left && pointerHandedness != Handedness.Right) continue;

                if (pointerHandedness == handInView || CurrentEngagedHand == pointerHandedness)
                {
                    UpdateActivePointer(pointer);
                    break;
                }

                if (!isControllerConnected) continue;
                // If we have controllers, try and match a hand with the first controller found
                foreach (var controller in connectedControllers)
                {
                    if (controller.ControllerHandedness != pointerHandedness) continue;
                    UpdateActivePointer(pointer);
                    break;
                }
            }`

**Comment by luis-valverde-ms** [comment]
Resolved by #4538
