### ISSUE TITLE
SetFocusPointForFrame not updating Stabilization Plane

### ISSUE THREAD

**Issue by RickyAvina** [Microsoft/MixedRealityToolkit-Unity#3958]
## Overview
The Stabilization Plane does not update upon calling SetFocusPointForFrame within the *StabilizationPlaneSetting.unity* or any other project. I am verifying that the stabilization plane actually updates using the Windows Device Portal and qualitatively, but noticing the color bleeding/jitter does not improve upon setting the focus point. In both my projects and the provided  *StabilizationPlaneSetting.unity*, I am deselecting *Enable Depth Buffer Sharing* under the Windows Mixed Reality toolkit settings.

## Expected Behavior
Stabilization plane updates, which should cause stabilization.

## Actual Behavior
Stabilization plane does not move.

## Steps to reproduce
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/htk_release/Assets/HoloToolkit-Examples/Utilities/Scenes/StabilizationPlaneSetting.unity

## Unity Editor Version
2018.2.171f

## Mixed Reality Toolkit Release Version
2017.4.3.0

**Comment by Yoyozilla** [comment]
HTK does not support Unity 2018, and there is no plans to update HTK after MRTK v2 release.
We would recommend MRTK v2 for development to receive future updates/bug fixes.
