### ISSUE TITLE
Some upcoming process changes.

### ISSUE THREAD

**Issue by wiwei** [Microsoft/MixedRealityToolkit-Unity#3959]
This issue describes some of the upcoming process changes that we will be adopting, and is filed as an issue to give some transparency before it happens, to give some of the rationale behind the changes, and to gather data and feedback on things that we may not have thought of. Overall the philosophy behind these changes are that we want to take incremental steps toward improving pain points that we've had (these are not set in stone and will change over time so that we can improve our processes).

### Usage of Code Owners

Code owners was a feature introduced to [github several years back](https://github.blog/2017-07-06-introducing-code-owners/) which allows for people to specify 'owners' for specific paths, extensions, etc. We want to start using this for areas where the area clear area experts so that the act of issuing PRs will automatically add them for review. As our team has grown and areas of expertise have formed around specific parts of the code (i.e. input, prefabs, etc), we'd like to reduce the cognitive burden associated with "who should actually review this code" and have some automatic help when issuing a PR.

### Release Cadence

In the aspiration of going to a monthly cadence, we're proposing a specific pattern for how and when we snap releases:

#### Week 1
PRs issued against mrtk_development

#### Week 2
PRs issued against mrtk_development
End of week 2 we'll do a build call to look at the overall quality of the build.

#### Week 3
PRs issued against mrtk_development
At the end of week 3, we will snap a stabilization branch for that month's release. After that point mrtk_development will only be for future releases)

Naming of stabilization branch tentatively looking like:
prerelease/2.0.0.rc1_stabilization

#### Week 4
Stabilization PRs issued against stabilization branch, build calls during this week and at the end of the week stabilization branch merges into mrtk_release.

Being as though we're already halfway into this month we have to see whether or not this is actually going to happen for April, but this is being called out here to give some clarity on our thoughts. 

A major reason for wanting to declare this process up front was the lack of clarity (both internally and externally) around when things were happening, what branches you had to work out of, what the actual deadlines were for getting fixes in for specific releases, and so on. While it's not expected that this process (or any process) will fix all issues, the hope is the the increase in predictability should help both people working on the project and also consuming it.

### Build Quality

One of the difficulties we dealt with was around integrating large sets of changes all up into one branch - with our limited test coverage, it is extremely easy for issues to get introduced that aren't discovered until much later in the process, at which point teasing out original regressions were really challenging. 

A couple of things we're going to be doing to try to help with that:
1) Ongoing build calls (as described in the release cadence)
2) A recommendation that for features that are well isolated and reasonably short in duration (i.e. <1 month) to put the changes into a feature branch, and when changes are ready to be brought into mrtk_development, to do a build call against the feature branch to ensure that the changes being brought in there don't regress the overall usage of MRTK. There isn't a specific set or rules governing this, and is mostly left up to the judgement of the folks working on the areas. However, there are some examples of what would be a good candidate vs. not:

- If you are working on changes to the way that the input system works or other core features, working out of a feature branch isn't recommended because it's not isolated (people who need to use your changes would either need to wait for yours or start working out of your branch, at which point your branch might become the defacto development branch)
- If you are working on some new prefabs that are well isolated form the rest of the MRTK and require ~2 weeks of work consider spinning up a feature branch.

#### Number of required reviewers per pull request
For mrtk_development, changed from 2 -> 1.
For mrtk_release, remaining at 2.

#### Resetting reviews when new commits are pushed
For mrtk_development, this will no longer be enabled.
For mrtk_release, this will still be enabled.

There's been feedback around the heaviness of process for reviews, where both the number is necessary (i.e. a particular person is an expert in an area and you don't need to get another token reviewer), and resetting the reviews is a pain (because of the distributed nature of this project, having to re-acquire approval after fixing a spelling nit is a huge pain).

One more restriction that will be added, however, is that only core team members will be able to merge into the mrtk_development or mrtk_release branches. As we move to make our release and branching process more predictable we want to make sure that those who are coordinating the release and stabilization have the ability to direct changes in at the right time and to the right place.

#### Draft PRs
When sending out a PR for the purpose of getting feedback (i.e. it's a prototype idea or we want to send out code to have a more educated discussion) that isn't intended to be submitted yet, use the [Draft PR feature](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

**Comment by StephenHodgson** [comment]
> One of the difficulties we dealt with was around integrating large sets of changes all up into one branch - with our limited test coverage, it is extremely easy for issues to get introduced that aren't discovered until much later in the process, at which point teasing out original regressions were really challenging.

Actually getting valid feedback and not removing the original authors from having the ability to request changes probably would have gone a long way as well.
