### ISSUE TITLE
Who I can select or interact the objects or buttons using hololens1 ?

### ISSUE THREAD

**Issue by tamizhuser** [Microsoft/MixedRealityToolkit-Unity#3968]
Press WASD keys to fly / move.
Press and hold right mouse to look around.
Press and hold space bar to use a simulated hand.

"Above input are work but who I can select or interact the objects or buttons using hololens1"

**Comment by julenka** [comment]
Hi, thank for filing an issue! Could you please post this to stackoverflow and tag the question with MRTK, since it is more of a question? This will make it easier for others who run into the same problems to find your answer, and will allow us to better answer the question.
