### ISSUE TITLE
Windows SDK 18362 on Hololens 1 (build with MRTKv2 RC1)

### ISSUE THREAD

**Issue by Ariel-Feldman** [Microsoft/MixedRealityToolkit-Unity#3969]
## Overview
In order to build with Unity and  MRTKv2 RC1, we need to install the Windows SDK 18362  which we get from windows insider program, that's OK. but when deploying from VS I get an error that my Hololens 1 can't receive it since its Windows SDK is 17x.
doesn't anyone know what's the trick?.. updating the Hololens SDK is never mention in here or docs, and it can be kind of a problem since its Hololens 1.
anyone can advise? []-)

## Steps to reproduce
build any scene, target UWP,
Windows SDK 18362 (development PC) 
Windows SDK 1.7x (Hololens) 

## Unity Editor Version
2018.3 12f
## Mixed Reality Toolkit Release Version
MRTKv2RC1

**Comment by davidkline-ms** [comment]
@Ariel-Feldman, can you post the specific error message(s) you are seeing during deployment? There should be no errors when deploying to a HoloLens 1 (version 1809, build 17763) even when building with a newer SDK (ex: 18362).

I run this exact scenario myself and have not seen errors.

Thanks!

**Comment by Ariel-Feldman** [comment]
@davidkline-ms, Thanks! I saw your replay in the other thread, the answer as you said,  was in StackOverflow. On unity build screen, the **target** SDK should be 10.0.18362 and the **Minimum** **must** be 10.0.10240.
all thanks to @julenka and #Mrtk tag, thanks again! []-)
