### ISSUE TITLE
Unity UI text edit field should make virtual keyboard appear

### ISSUE THREAD

**Issue by danielhofmann-ms** [microsoft/MixedRealityToolkit-Unity#3970]
## Overview
Open the _HandInteractionExamples_ scene and select a text edit control. This should cause a virtual keyboard to show up by default.

## Mixed Reality Toolkit Release Version
MRTK v2

**Comment by chrisfromwork** [comment]
I've hit this pain as well. It would be nice to have this behaviour just work by default. Android and iOS seem to work without any additional logic.

**Comment by julenka** [comment]
Removing Yoyo since she is not actively working on this.

**Comment by julenka** [comment]
@keveleigh is this a bug in Unity?

**Comment by julenka** [comment]
Marking as GA blocker because many partners actually use Unity UI

**Comment by Troy-Ferrell** [comment]
@julenka / @keveleigh any update on this one?

**Comment by julenka** [comment]
I'm on vacation until 8/8, I don't have any updates. I believe we assigned this to Kurtis since the issue is actually a problem with how Unity makes the Windows API calls for [InputPane.show](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.ViewManagement.InputPane).

**Comment by davidkline-ms** [comment]
> I believe we assigned this to Kurtis since the issue is actually a problem with how Unity makes the Windows API calls for InputPane.TryShow.

Per the above, moving this to "consider for next iteration"
