### ISSUE TITLE
Default settings dialog should say "would like" instead of "needs" wrt il2cpp

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#3978]
## Overview
When running on Unity 2018, there is no requirement to use IL2CPP (.NET backend still exists, MRTK is compatible with the .NET backend), so _technically_ MRTK does not _need_ to switch backends.

This will also make the language more consistent with the prompt at the bottom of the dialog ("Would you like to make this change?").

When 2019 is detected, this dialog should not be shown as that version of Unity does not contain the .NET backend.

## Unity Editor Version
2018.3.12f1

## Mixed Reality Toolkit Release Version
v2 RC1

**Comment by wiwei** [comment]
Does this still matter after this change?

https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3964

**Comment by davidkline-ms** [comment]
it may not be. i will pull the latest and double check whether or not this is a duplicate

**Comment by davidkline-ms** [comment]
closing as a duplicate
