### ISSUE TITLE
Missing SettingsProviders scope in MixedRealityPreferences

### ISSUE THREAD

**Issue by frangagn** [Microsoft/MixedRealityToolkit-Unity#3993]
## Describe the bug

Unity 2019.1.0f2 Personal: 

Unity compile error: "Assets\MixedRealityToolkit-Unity-mrtk_release\Assets\MixedRealityToolkit\Inspectors\MixedRealityPreferences.cs(70,32): error CS7036: There is no argument given that corresponds to the required formal parameter 'scopes' of 'SettingsProvider.SettingsProvider(string, SettingsScope, IEnumerable<string>)"

Missing argument on line 70 of MixedRealityPreferences: SettingsScope.Project

## Expected behavior
MRTK Would just compile after importing

- Unity Version [e.g. 2019.1.0f2]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by wiwei** [comment]
This was fixed in:

https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3962

Note that MRTK v2 is very experimental with Unity 2019 right now. We're currently working out the kinks. Our dev team is primarily focused on 2018 (and the to-be LTS build of 2018) right now.
