### ISSUE TITLE
Interactable Profile Theme text at incorrect indentation?

### ISSUE THREAD

**Issue by genereddick** [microsoft/MixedRealityToolkit-Unity#3997]
## Describe the bug
I'm not sure this is a bug, but in the Interactable script (for a checkbox) under the Profiles for each of Background, Button, Label, CheckBoxCheck there are four items. 

    CheckboxCheck
        Target
        Theme
        > ToggleSomething
           Theme
        >ToggleSomethingElse

    

Visually I find this confusing: either 
a) , the two toggles and the second theme are meant to be in some sort of nested relationship with the first theme, and the toggle buttons icon (>) are offset to the left of the (otherwise) similarly indented items, or
b) there is no nested relationship, and so the toggle button icon (>) is at the same level as the first Theme, but then the second Theme is incorrectly indented to the right

If (a) the nature of the nested relationship is unclear. If (b) the second Theme needs to be moved left.

## To reproduce
See in Inspector window

## Expected behavior
?

## Your Setup (please complete the following information)

- Unity Version 2018.3.12f1
- MRTK Version v2.0 latest

## Target Platform (please complete the following information)
Unity Editor

**Comment by davidkline-ms** [comment]
@Railboy / @killerantz, can you clarify the interactable property nesting?

Thanks!

**Comment by killerantz** [comment]
@genereddick is correct, it is confusing and a bug. The second theme, for a single target, should not be tabbed in, but flush with the first Theme. All the themes effect different properties of the same object equally and are not meant to be nested. Thanks for catching this.

**Comment by killerantz** [comment]
![image](https://user-images.githubusercontent.com/22085553/56380628-8ccad500-61c7-11e9-9c84-caef2582874a.png)

Maybe the first Theme in the list needs to be indented with the second, so that they imply more that they are effecting the target.

**Comment by genereddick** [comment]
@killerantz I like the idea of indenting the first theme to the same level as the others as I think it clarifies the relationship

**Comment by Yoyozilla** [comment]
@genereddick feel free to open a PR to fix this!

**Comment by killerantz** [comment]
I created a PR #4143
