### ISSUE TITLE
Can't build with MRTK 2RC1

### ISSUE THREAD

**Issue by OzoneABN** [Microsoft/MixedRealityToolkit-Unity#3999]
I'm not able to build any example to HoloLens, neither using standard Unity Build nor the MRTK Build Window. I've also tried IL2CPP and .NET.

When trying to build with .NET using the normal build window from Unity (Unity C# Project, see Screenshot for build settings)
![Bildschirmfoto 2019-04-17 um 11 38 09](https://user-images.githubusercontent.com/1853359/56277888-78be9f00-6105-11e9-9784-b235c5a4167a.png)

I got these errors in VS2017:
![Bildschirmfoto 2019-04-17 um 11 46 31](https://user-images.githubusercontent.com/1853359/56278405-76107980-6106-11e9-81d0-7498c2cff6a0.png)

If I try to build it with IL2CPP (same settings except Unity C# Project) I got these errors in Unity, but the build succeeded:
![Bildschirmfoto 2019-04-17 um 11 55 54](https://user-images.githubusercontent.com/1853359/56279189-f683aa00-6107-11e9-8c80-034f29e49734.png)

In VS2017 I get these errors
![Bildschirmfoto 2019-04-17 um 11 53 01](https://user-images.githubusercontent.com/1853359/56279007-97be3080-6107-11e9-97a2-1ef04e297907.png)

![Bildschirmfoto 2019-04-17 um 11 54 29](https://user-images.githubusercontent.com/1853359/56279023-a0af0200-6107-11e9-90ec-020d17e61492.png)

Using the MRTK build window and .NET I get these errors, but the build succeeded:
![Bildschirmfoto 2019-04-17 um 12 02 05](https://user-images.githubusercontent.com/1853359/56279550-a22cfa00-6108-11e9-8f08-5625ee97c1b5.png)
Trying to build the Appx these errors occur:
![Bildschirmfoto 2019-04-17 um 12 03 12](https://user-images.githubusercontent.com/1853359/56279647-ca1c5d80-6108-11e9-829d-bb48a674dd4e.png)

I don't get it, I've used an older beta version of the MRTK 2 and I do not have any problems so far, but after switching to the RC1, nothing works for me anymore.

## To reproduce
1. Download MRTK V2 RC1 (source)
2. Open it with Unity 2018.3.12f1
3. Open any Example and add it to the builds
4. Try to build it

## Expected behavior
The build should be working

## Your Setup
- Windows 10 Version 1903 Build 18875.1000
- Windows_InsiderPreview_SDK_en-us_18362
- Unity Version 2018.3.12f1
- MRTK Version v2.0 RC1

## Target Platform (please complete the following information)
- HoloLens

**Comment by davidkline-ms** [comment]
@OzoneABN, if you change the minimum SDK version to 10.0.10240.0, do you still see the errors?

**Comment by OzoneABN** [comment]
Yes, same errors :-(

**Comment by davidkline-ms** [comment]
Thank you for trying! We will investigate

**Comment by wiwei** [comment]
I believe RC1 had it's .NET build target broken due to few set of changes, see this issue:

https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3903

According to the latest in the issue it's been fixed in the latest mrtk_development

**Comment by wiwei** [comment]
By the way, super good bug filing, these screenshots and steps and everything is the best.

**Comment by OzoneABN** [comment]
Thank you very much for the quick help. It worked, I can now build my project with .NET again.

**Comment by davidkline-ms** [comment]
Closing as @wiwei's solution resolved the issue.
