### ISSUE TITLE
Better Initial Setup, Especially for HoloLens

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#4005]
## Describe the problem
When MRTK first initializes some important steps can be missed based on the current target platform. For example, if targeting HoloLens it does not change the project platform to UWP. We understand this is because MRTK is wanting to be more cross-platform, however this does cause significant confusion, especially for first-time developers.

During this first-run "initialization phase", MRTK does set up XR settings but only for the current platform. If UWP is not the current platform at the time, for example, these steps are never applied. There is no way to run this initialization phase again once it's completed

## Describe the solution you'd like

What I really want to see is a return of the "Apply Project Settings" and "Apply Capability Settings" dialogs. Those dialogs clearly stated why they were doing certain tasks and each step could be skipped by simply unchecking the box.

## Describe alternatives you've considered

The only alternative is manually applying each of the changes, however currently there is no good "getting started" guide that documents _all_ of the required steps. 

For HoloLens alone, here are some of the most critical steps that can easily be missed:

- Platform must target UWP
- XR must be enabled
- Shared Depth Buffer must be enabled (for depth-based LSR)
- Ideally rendering should be single-path instanced. What problems might arise and how can they be resolved?
- Microsoft HRTF should be set as the audio spatializer
- What should the depth buffer format be?
- What are some basic guidelines on the graphics quality settings and Unity Lightweight Rendering Path? 
- Which capabilities need to be set? Camera? Microphone? Internet?

## Additional context

We totally understand the desire to be platform independent and we support that. However, HoloLens does have a number of very important steps that can easily be missed and need to be done right for apps to work correctly. While MRTK design goals should absolutely focus on cross-platform, we also want to make make sure to help HoloLens developers get things right "out of the box". And as MRTK grows and improves the cross-platform story, these same principals can be applied to Immersive, ARCore, ARKit, and beyond.

**Comment by genereddick** [comment]
It would be nice to either make relevant changes directly, or at least have the setup guide include additional links / text on top recommendations:

Additional recommendations include:
Depth Format 16-bit
And, reducing the Near & Far Clipping Plane at least for HL

(https://docs.microsoft.com/en-us/windows/mixed-reality/recommended-settings-for-unity)

**Comment by chrisfromwork** [comment]
This feels like something comparable to spectator view preview's platform switcher editor control. With that tooling I have been able to specify needed capabilities/player settings/build settings when switching platforms.

**Comment by chrisfromwork** [comment]
Assigning to @Yoyozilla to figure out an appropriate owner.

**Comment by StephenHodgson** [comment]
I thought the capabilities were already being updated set by the classes that implement features that depend on them?

Also, I think switching platforms is something that's fairly easy to do, but not something that the toolkit should be facilitating. We're not trying to re-write all the functionality of the editor.

**Comment by Railboy** [comment]
>This feels like something comparable to spectator view preview's platform switcher editor control.

We're talking about a wizard in the shiproom right now. An editor window sounds ideal. A simple tool where you can choose which platform you're targeting and which associated features you want enabled won't cover every scenario but it will at least get people started.

I agree with @StephenHodgson that it shouldn't be built into the guts of the toolkit itself. It's just an auto-configuration tool that could be removed without consequence.

**Comment by Yoyozilla** [comment]
#4780 #4442

**Comment by Troy-Ferrell** [comment]
Also FYI on PR #5319

**Comment by jbienzms** [comment]
I see how #5319 helps with getting the right performance settings. But what PR or update fixed the other missing features for #4005? Namely:

- Platform must target UWP
- XR must be enabled for UWP
- Shared Depth Buffer must be enabled (for depth-based LSR)
- Shared Depth Buffer should be 16-bit
- Microsoft HRTF should be set as the audio spatializer

**Comment by jbienzms** [comment]
Whoops, I somehow got to a different issue than 5319. I understand how this works to resolve 4005 now. I will comment on 5319.
