### ISSUE TITLE
Cloning a Sub-Profile in the Editor Results in the Wrong Name

### ISSUE THREAD

**Issue by mtaulty** [Microsoft/MixedRealityToolkit-Unity#4014]
## Describe the bug

It seems like the name that I enter for a cloned sub-profile isn't used.

## To reproduce

If I add a new Scene in Unity, configure the MRTK in the scene, configure a profile for the MRTK and then use the UI to 'clone' one of the sub-profile then it seems like the name that I enter for the new profile isn't used.

For example - try cloning the camera profile, call your new profile FOO and you end up with a profile called 'Mixed Reality Camera Profile' or similar

## Expected behavior

I'd expect the name from the dialog to be used.

## Screenshots

N/A
## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0.0 RC1]

## Target Platform (please complete the following information)

- HoloLens 2

## Additional context

N/A

**Comment by wiwei** [comment]
I believe this should have been resolved by this change:

https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3992

It'll be in the latest mrtk_development
