### ISSUE TITLE
Additional Parameter to construct SettingsProvider on 2019.1

### ISSUE THREAD

**Issue by mtaulty** [Microsoft/MixedRealityToolkit-Unity#4015]
## Describe the bug

Source file MixedRealityPreferences.cs (around line 70) constructs a SettingsProvider with a single parameter. It looks like in Unity 2019 the second (scope parameter) is required so you get a compilation failure there.

## To reproduce

Source file MixedRealityPreferences.cs (around line 70) constructs a SettingsProvider with a single parameter. It looks like in Unity 2019 the second (scope parameter) is required.

## Expected behavior

N/A

## Screenshots

N/A

## Your Setup (please complete the following information)

- Unity Version 2019.1.0f1
- MRTK Version V2.0.0-RC1

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

## Additional context

N/A

**Comment by wiwei** [comment]
This was resolved by:

https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3962

This is in the latest mrtk_development.
