### ISSUE TITLE
Bluetooth iBeacon in Unity

### ISSUE THREAD

**Issue by seaswander** [Microsoft/MixedRealityToolkit-Unity#402]
Now I'm working with an indoor localization project, which involves iBeacon. How can I access all the Bluetooth devices paired to HoloLens? And then, get the information that the iBeacon sends.

**Comment by mattfedocsg** [comment]
Check out my post here: https://forums.hololens.com/discussion/7304/ibeacon-beacons-hololens

I would love to make this part of the toolkit.  Just let me know.

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
