### ISSUE TITLE
my Speech Demo in MRTK v2 donnot work(unity or HoloLens(1st)),but other demo perform well 

### ISSUE THREAD

**Issue by tisaud** [Microsoft/MixedRealityToolkit-Unity#4020]
## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by tisaud** [comment]
Set Up : unity2018.3.7f MRTK V2

**Comment by julenka** [comment]
Hi, thanks for opening a bug! Unfortunately this bug doesn't have quite enough detail to be actionable, could you please give more details about the steps, including filling in the required fields in the template when you file a bug?

Also, if this is more of a question you need help with and not a bug in MRTK, please ask your question on stackoverflow and add the tag 'mrtk'

**Comment by tisaud** [comment]
hi,thanks for your reply.When I'm testing the Speech Example in MRTK v2.I found that Voice input for this example donnot work (in unity or HoloLens / English or Chinese).In addition,I made sure to give the microphone permission










------------------ 原始邮件 ------------------
发件人: "Julia Schwarz"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 下午2:37
收件人: "Microsoft/MixedRealityToolkit-Unity"<MixedRealityToolkit-Unity@noreply.github.com>;
抄送: "@lllusion"<353636485@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Microsoft/MixedRealityToolkit-Unity] my Speech Demo in MRTK v2donnot work(unity or HoloLens(1st)),but other demo perform well  (#4020)




Closed #4020.
