### ISSUE TITLE
MRTK v2/Manipulation Handler - how to make rectangle around coffee cup?

### ISSUE THREAD

**Issue by junpark12** [Microsoft/MixedRealityToolkit-Unity#4023]
## Describe the Issue
Hi. I'm following the Manipulation Handler in MRTK v2.0 documentation.
(Environment - MRTK v2.0 RC1)
I copied existing "HandInteractionExamples" scene and deleted couple of object to make it simple. Then i imported coffee cup prefab on the scene and applied the same manipulation handler with same properties of original scene.
But when i run it, i don't see boudingbox like rectangle around coffee cup.
![image](https://user-images.githubusercontent.com/20918194/56415858-fcc18400-62c9-11e9-8322-7db3cb99436f.png)

But when i run the original scene, i can clearly see the rectangle from the beginning.
![image](https://user-images.githubusercontent.com/20918194/56415987-72c5eb00-62ca-11e9-8255-2fe83918544e.png)

Because i cannot see the rectangle, i cannot scale and rotate it. The only thing i can do is dragging.  Can you give me some hint on this?

## Feature Area
What's incorrect? What's missing?

## Existing Doc Link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_ManipulationHandler.html

## Additional context
Here are the Inspector properties of coffee cup.
![image](https://user-images.githubusercontent.com/20918194/56416078-c46e7580-62ca-11e9-92da-9bb33ac9ccb5.png)

**Comment by Yoyozilla** [comment]
I think you are missing the bounding box script
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_BoundingBox.html
