### ISSUE TITLE
Write RC2 Release Notes

### ISSUE THREAD

**Issue by luis-valverde-ms** [Microsoft/MixedRealityToolkit-Unity#4025]
## Describe the Issue
This is where we track the things we need to include in RC2 release notes. 

## Breaking changes

- Added OnPointerDragged() method to IMixedRealityPointerHandler. Will cause a build error on all custom implementations of the interface that can be safely fixed adding an empty implementation for the new method.

**Comment by wiwei** [comment]
This should also account for these changes:

https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/4019

i.e. namespaces changes

**Comment by julenka** [comment]
# New Features
- Slider - New UI control that allows you to change a value continuously by grabbing and moving a slider on a track. PR #4022

**Comment by cre8ivepark** [comment]
# New Features
- Slate zooming support - Two-handed content zooming on Slate with min/max values. PR #4018

**Comment by wiwei** [comment]
Closing this out
