### ISSUE TITLE
Input simulation doesn't work if speech is not supported on dev machine

### ISSUE THREAD

**Issue by matkrzyztt** [Microsoft/MixedRealityToolkit-Unity#4026]
## Describe the bug

Camera controls (rotation, movement) is not working in editor despite Emulation Mode being set no "none".

## To reproduce

1. Create an empty project in unity 2018.3.12
2. Change platform to UWP
3. Enable VR with Mixed Reality Toolkit
4. Import MRTK v2 Core
5. Click "Add to scene and configure"
6. Launch project
7. Hold right mouse button and move 

## Expected behavior

Instead of camera rotating, nothing happens. 

## Your Setup (please complete the following information)

Windows 10 Pro
Unity 2018.3.x (not working on any version)
MRTK v2 RC

## Additional context

This is however working on my home machine. The only difference is my work computer (the one it's not working on) I don't have speech recognition, and thus get an error on play.

> UnityException: Speech recognition is not supported on this machine.
> UnityEngine.Windows.Speech.KeywordRecognizer..ctor (System.String[] keywords, UnityEngine.Windows.Speech.ConfidenceLevel minimumConfidence) (at C:/buildslave/unity/build/Runtime/Export/Windows/Speech.cs:221)
> Microsoft.MixedReality.Toolkit.Windows.Input.WindowsSpeechInputProvider.Enable () (at Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs:95)
> Microsoft.MixedReality.Toolkit.MixedRealityToolkit.RegisterServiceInternal (System.Type interfaceType, Microsoft.MixedReality.Toolkit.IMixedRealityService serviceInstance) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:843)
> Microsoft.MixedReality.Toolkit.MixedRealityToolkit.RegisterServiceInternal[T] (T serviceInstance) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:858)
> Microsoft.MixedReality.Toolkit.MixedRealityToolkit.RegisterService[T] (System.Type concreteType, Microsoft.MixedReality.Toolkit.Utilities.SupportedPlatforms supportedPlatforms, System.Object[] args) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:199)
> Microsoft.MixedReality.Toolkit.MixedRealityToolkit.RegisterDataProvider[T] (System.Type concreteType, Microsoft.MixedReality.Toolkit.Utilities.SupportedPlatforms supportedPlatforms, System.Object[] args) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:280)
> Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.Enable () (at Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs:219)
> Microsoft.MixedReality.Toolkit.MixedRealityToolkit.EnableAllServices () (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:973)
> Microsoft.MixedReality.Toolkit.MixedRealityToolkit.OnEnable () (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:772)
> 

Is a speech recognition mandatory to emulate the input in edior?

**Comment by lukastoenneMS** [comment]
Speech should not be mandatory, but it looks like the input system runs into an exception when registering data providers. Since input simulation is registered after speech it never gets to the point where it initializes that service. If possible we should check if speech is supported before registering the data provider.

**Comment by matkrzyztt** [comment]
Thank you for replying. So it is speech recognition after all. 
Is there any way to disable it, so the input system would be registered correctly?

**Comment by julenka** [comment]
Hi, I haven't tested this myself (don't have a machine that doesn't support speech), but could you please try disabling speech and dictation in your input configuration profile? You just need to delete the two entries in red by hitting the '-' button on the right

![image](https://user-images.githubusercontent.com/168492/56476848-ad5a8f80-6452-11e9-806d-9b95e338ce99.png)

Also, if possible it would be great to also post this question to stackoverflow (tagged with 'mrtk') so we can reference this issue in case other people hit it in the future.

**Comment by julenka** [comment]
Lukas, do you have some time to take a look at this? If not, please feel free to un-assign yourself. Since it's blocking people from using MRTK it seems important to look at.

**Comment by lukastoenneMS** [comment]
Fixed in mrtk_development by catching the exception, same as WindowsDictationInputProvider does already.

**Comment by matkrzyztt** [comment]
> Hi, I haven't tested this myself (don't have a machine that doesn't support speech), but could you please try disabling speech and dictation in your input configuration profile? You just need to delete the two entries in red by hitting the '-' button on the right.
> 
> Also, if possible it would be great to also post this question to stackoverflow (tagged with 'mrtk') so we can reference this issue in case other people hit it in the future.
> 
> ![image](https://user-images.githubusercontent.com/168492/56476848-ad5a8f80-6452-11e9-806d-9b95e338ce99.png)

Yes, this works without any issues so far. Thank you Julia.
