### ISSUE TITLE
[HTK] Problems with MicStream on Hololens

### ISSUE THREAD

**Issue by benjamincoven** [Microsoft/MixedRealityToolkit-Unity#4029]
## Describe the bug

Hello, I am experiencing several problem with the Microphone on the Holotoolkit.

Here what I try to achieve: Record the voice input and send it to Azure Speech-To-Text, the only way I found to do this is to use the MicStream class, save the data in a file then upload the file to Azure.

Here are my problems:

1. When I try to to stop de record, if I call MicStream.MicStopRecording, the app crashs despite the fact the file is well saved on the Music folder. However calling MicStream.MicStopStream seems to work. Is this normal and a viable solution? I was not able to catch any error since the application totally crashes.

2. I cannot read the file once created, the path is ?/Music/MicStreamRecordings/... , I enabled the application capabilities to access audio library. I don't have the full path since I did not use MicStream.MicStopRecording, I tried 
```
#if ENABLE_WINMD_SUPPORT
        Debug.Log("test");
        Debug.Log(KnownFolders.MusicLibrary);
    
    #endif
```
however the Hololens build does not seem to enable this compiler condition, I tried Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) but I get an error UnauthorizedAccessException. I am not even sure that I have access to this folder.

3. Finally, I am doing all this to send byte[], is there any better method than using files to achieve this?

Thank you

Here my MicStreamInitialization:
```
MicStream.StreamCategory streamType = MicStream.StreamCategory.HIGH_QUALITY_VOICE;
MicStream.MicInitializeCustomRate((int) streamType, AudioSettings.outputSampleRate);
MicStream.MicSetGain(1);
```
And how I start record:
```
MicStream.CheckForErrorOnCall(MicStream.MicStartRecording(fileName, false));
```

And here how I read the file:
`byte[] data = File.ReadAllBytes(microphoneRecorder.GetFileLocation());`

## Expected behavior

MicStream.MicStopRecording does not make the application crash and return the file path that should be accessible.

## Your Setup (please complete the following information)

- Unity Version 2019.1
- MRTK Version 2017.4.2

## Target Platform (please complete the following information)

- HoloLens

**Comment by chrisfromwork** [comment]
Assigning to @Yoyozilla. I do not know that we will continue to provide fixes for moving the holotoolkit to newer unity versions.

**Comment by benjamincoven** [comment]
I understand, but this is more a problem about the UWP API. I guess also that the MRTK 2 will have a similar feature implemented not much differently. This could be enough for me to do the fix.

Thank you.

**Comment by Yoyozilla** [comment]
Is this something we can repro on MRTK v2?

**Comment by benjamincoven** [comment]
I could make it works by using an UWP exemple for Windows Phone instead of the MicStream plugin+script from the HTK. I let you choose to close or not this issue.

**Comment by Yoyozilla** [comment]
Thanks for the update! we are not actively updating HTK anymore so I will close this issue. We will make sure MicStream works in MRTK v2.
