### ISSUE TITLE
MRTK 2 RC1 UWP Unity 2019.2.0a11 Multiple Build errors on examples: WindowsMixedRealityArticulatedHand.cs

### ISSUE THREAD

**Issue by Seantron** [Microsoft/MixedRealityToolkit-Unity#4030]
## Describe the bug

In Unity 2019.2.0a11 with MRTK 2 RC1

## To reproduce

First I had to resolve an issue in MixedRealityPreferences.cs:

I added the SettingsScope.Project arg into line 70:

![MixedRealityPreferencesIssues](https://user-images.githubusercontent.com/438733/56430254-d2ed6a80-6293-11e9-83da-7e2169d4bb63.PNG)

to get past this error:

![MixedRealityPreferencesError](https://user-images.githubusercontent.com/438733/56430495-7fc7e780-6294-11e9-8be9-af8767119aa8.PNG)

Then I tried to build out:

![SolverExamples](https://user-images.githubusercontent.com/438733/56430103-48a50680-6293-11e9-96c0-3a6eb5dd94d2.PNG)

And received the following build errors:

![MRTK2_RC1_BuildIssues](https://user-images.githubusercontent.com/438733/56430135-65413e80-6293-11e9-8455-a5af1863bf4c.PNG)

## Expected behavior

Should build a project.

## Screenshots

See above.

## Your Setup (please complete the following information)

- Unity Version 2019.2.0a11
- MRTK Version v2.0 RC1

## Target Platform (please complete the following information)

- HoloLens

**Comment by wiwei** [comment]
A couple of things are going on here:

1) https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3962 addressed the SettingScope issue.
2) You'll need to install the Windows 10 SDK 18632 or greater per the getting started guide:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html#prerequisites

https://blogs.windows.com/buildingapps/2019/04/18/start-developing-on-windows-10-may-2019-update-today/#DOp1cyLq90cW4ZMp.97

**Comment by Seantron** [comment]
Thank you @wiwei, updating right now. Sorry about that.

**Comment by Alexees** [comment]
@wiwei I just followed the installation instructions, but when it comes to running the Mixed Reality Portal now it seems to try to update, gets to 6% and then tells me that the portal could not be installed. I tried reinstalling already but to no avail.
I know this is not where this belongs but happened to me during this process. Do you know what I can do?
