### ISSUE TITLE
Proposal: Create a core camera management service which can be disabled / configured to work with AR

### ISSUE THREAD

**Issue by Railboy** [Microsoft/MixedRealityToolkit-Unity#4031]
## Describe the problem

The MRTK exercises a great deal of control over the main camera. This can lead to problems when using ARKit / ARCore / ARFoundation.

## Describe the solution you'd like

A camera management service should be written. The default service should mimic the toolkit's current functionality. Alternate versions can be written to accommodate AR solutions and/or more complex camera setups. And like any core service, it should be possible to disable camera control altogether.

This has the added benefit of making it easier to use the toolkit as a pure service provider, if desired.

Related issues: #3616, #3948, #3762

**Comment by chrisfromwork** [comment]
Assigning to @Yoyozilla  and @wiwei to try and find an appropriate owner
