### ISSUE TITLE
AttachToController Functional?

### ISSUE THREAD

**Issue by andreiborodin** [microsoft/MixedRealityToolkit-Unity#4033]
We have a code file ([AttachToController](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/AttachToController.cs) )that contains substantial ammount of commented code with a TODO. Not sure whether the functionality actually works.

Opening the issue to track fixing it, cleaning up the commented code or removal.

**Comment by chrisfromwork** [comment]
Assigning to @luis-valverde-ms for now

**Comment by luis-valverde-ms** [comment]
We should aim to at least remove the file for RC2.
