### ISSUE TITLE
No Active Toolkit Found Dialog shows up during build

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#4043]
## Describe the bug
For awhile now when attempting to build in Unity, it will create and open an empty scene. When the build is complete it will return to the scene that was open when the build started and the temporary scene will vanish. 

Now, in addition to this odd behavior, while the build is ongoing, for this empty scene the MRTK will open up a No Active Toolkit Found dialog (see screenshot below).

This dialog does not automatically close when the build is done and it returns to the original scene. It does not seem to impact anything, it doesn't stop the build. It is just odd / annoying.

## To reproduce
?

## Expected behavior
Assuming the empty scene is some Unity bug, this dialog seems overly aggressive in any case, though maybe it is ncessary? 

## Screenshots
[https://photos.app.goo.gl/iV22FVHHESkjHTio9](https://photos.app.goo.gl/iV22FVHHESkjHTio9)

## Your Setup (please complete the following information)
- Unity Version: 2018.3.12f1
- MRTK Version: latest MRTK_developmernt

## Target Platform (please complete the following information)
- HoloLens
- WMR immersive

**Comment by julenka** [comment]
Hi, I am not hitting these issues when I try to compile a UWP in Unity 2018.3.11f1. Perhaps your build steps are different? Could you please detail your build steps?

For example, here's what I do:

1. File -> Build Settings...
2. Ensure UWP is selected. I usually set the Scripting Backend as .NET.
2. Press "Build" button.

**Comment by genereddick** [comment]
I created a new project this morning from MRTK_development (as of yesterday), and tested with both .NET scripting backend and IL2CPP on 2018.3.13f1 with the same result. During the build Unity creates a new scene ("Untitled" in the screenshot below) and switches to it from the default Sample Scene. 

At which point the MRTK apparently checks the scene and, as there is no Toolkit installed, pops up the dialog. 

When the build is done the temporary scene goes away and switches back to the correct scene. The dialog stays up and has to be closed.

[https://photos.app.goo.gl/gjKvfkc2pcYWyw918](https://photos.app.goo.gl/gjKvfkc2pcYWyw918)

**Comment by genereddick** [comment]
OK, the first issue is Unity related, in that Unity is creating a backup scene in the temp folder 
( /Temp/__Backupscenes/0.backup -- If I delete this it gets recreated during the build) and temporarily redirecting to it during the build before switching back to the actual scene.

 This happens for default Unity installs (not UWP output, no MRTK), so only really noticeable because of the interaction with the MRTK throwing up the missing Toolkit dialog.

**Comment by julenka** [comment]
I am able to reproduce this issue. Repro steps are pretty simple:

1. checkout mrtk development
2. File -> Build Settings...
3. Ensure build type is UWP
4. Select HandInteractionAll scene
5. Press build

Expected:
UWP builds

Actual:
UWP Builds, but there is a dialog window that pops up. 
![image](https://user-images.githubusercontent.com/168492/56528069-7b553600-6503-11e9-8ca2-9a474e7f01c4.png)
