### ISSUE TITLE
I build UWA and install in PC,but don't connect to local unity server.Please help.

### ISSUE THREAD

**Issue by neciszhang** [Microsoft/MixedRealityToolkit-Unity#4045]
## Overview
Hi , 
     1. I build UWA app and install it in windows 10.
     2. I build local server by unity.
     3. I open unity server and UWA app. But the app don't connect to unity server.
Can you help me?I search lots of questions,but i don't resolve this question.
## Steps to reproduce
_(Links to sample github project preferred)_

**Comment by chrisfromwork** [comment]
@neciszhang are you using the MRTK repo to setup your uwa application?

Assigning to @davidkline-ms

**Comment by davidkline-ms** [comment]
@neciszhang,

By default, UWP applications are subject to network isolation. For development and 
side-load scenarios, your PC can be configured to allow an application to establish
loopback connections.

For side-load scenarios, please refer to the documentation describing network isolation
troubleshooting (https://msdn.microsoft.com/en-us/library/windows/apps/hh780593.aspx).
