### ISSUE TITLE
"Add to Scene and Configure" doesn't gracefully fail when no camera is present in the scene.

### ISSUE THREAD

**Issue by Cameron-Micka** [Microsoft/MixedRealityToolkit-Unity#4046]
## Describe the bug

When the "Mixed Reality Toolkit->"Add to Scene and Configure..." menu item is selected in a scene **without** a camera a handful of null reference exceptions occur and the MRTK is not configured correctly.

The project we are seeing this occur in loads a camera dynamically at runtime based on certain project restrictions.

## To reproduce

Select "Mixed Reality Toolkit->"Add to Scene and Configure..." in a scene without a camera.

## Expected behavior

All exceptions are gracefully handled. Optionally, anything relying on the Camera or Camera Cache could automatically setup a main camera for the user.

**Comment by Railboy** [comment]
Related: #3890

**Comment by chrisfromwork** [comment]
Assigning to @Yoyozilla to find an owner.

**Comment by Yoyozilla** [comment]
Cameron, could you please check that your issue is fixed by Lar's PR linked above?

**Comment by Cameron-Micka** [comment]
Thanks! I'll give this a try when I get a chance.
