### ISSUE TITLE
Changing MRTK folder paths results in problems with Controller Mapping

### ISSUE THREAD

**Issue by Avalin** [microsoft/MixedRealityToolkit-Unity#4067]
## Overview
Moving the MRTK folders to another folder than Assets (My path was in this case Assets/Libs/MRTK/MixedRealityToolkit... etc) results in issues with Controller Mapping, as the EditorWindow (ControllerWindowPopup.cs) is hardcoded to open up directly from Assets folder. 

## Expected Behavior
My idea would be one or more of potential scenarios:
- Controller Mapping working no matter where MRTK folders are placed
- Easily readable LogErrors when attempting to open the ControllerMapping from wrong path
- Highlighted in documentation that moving the project to a different folder creates issues (Like it is highlighted with changing the camera position) 

## Actual Behavior
NullPointerReference saying it couldn't close the window because it is null from the ControllerWindowPopup.cs

## Steps to reproduce
-Download MRTK RC1
-Generate Custom Profiles (Particularly ControllerMapping profile) 
-Move all folders into a new folder called MRTK 
-Open any of the EditorWindows from the ControllerMapping profile

## Unity Editor Version
2018.3.13f

## MRTK Version
MRTK RC1

**Comment by wiwei** [comment]
I thought that this might have been fixed recently because we did some work to make relative paths work (i.e. to support the MRTK being put in non-root-asset folder locations), but it looks like it didn't quite cover this case. We'll take a look here

**Comment by wiwei** [comment]
A long time later, this got fixed.
