### ISSUE TITLE
Let Xbox Controller control position and hands in editor just like in Emulator

### ISSUE THREAD

**Issue by LocalJoost** [microsoft/MixedRealityToolkit-Unity#4069]
## Describe the problem

When I deploy an MRTK2 app in the HL2 emulator I get a beautiful and very useful control of both camera and hands position - and visualization. In the Unity Editor, in play mode, nothing happens when I use the Xbox controller 

## Describe the solution you'd like
I would very much like to see that in the editor in play mode the Xbox controller would have the same effect as in the Emulator. I would like to be able to set the joystick sensitivity for a solution like this. I think this will shorten the development loop considerably.

## Describe alternatives you've considered

Using keyboard and mouse, but that's very hard to do.

**Comment by davidkline-ms** [comment]
Investigate XRI input simulator vs the custom MRTK simulated hands.

**Comment by polar-kev** [comment]
Hey @LocalJoost, I'm happy to say that this is possible in our early builds of MRTK v3.

**Comment by LocalJoost** [comment]
Wow. I had all but forgotten this. :D Thanks
