### ISSUE TITLE
Oculus Touch controller won't send an action when trigger is pressed

### ISSUE THREAD

**Issue by ChauNTran** [microsoft/MixedRealityToolkit-Unity#4072]
## Describe the bug

Oculus Touch controller won't send an action when trigger button is fully pressed. Action has "Digital" axis constraint.

## To reproduce

1. Make new scene using a clone of DefaultMixedRealityToolkitConfigurationProfile
2. Clone and apply DefaultMixedRealityInputSystemProfile, DefaultMixedRealityInputActionProfile, and DefaultMixedRealityControllerMappingProfile
3. Make sure the is "Select" action with "Digital" axis constraint in the MixedRealityInputActionProfile.
4. In the MixedRealityControllerMappingProfile, map the "Select" action to Oculus Touch controller under Axis1D.PrimaryIndexTriggerPress and Axis1D.SecondaryIndexTriggerPress

## Expected behavior

"Select" action is supposed to be fired when the trigger button is fully pressed.

## Your Setup (please complete the following information)

- Unity Version 2018.3.9f1
- MRTK Version RC1

## Target Platform (please complete the following information)

- Oculus running on OpenVR

**Comment by ddutchie** [comment]
also ran into this issue. is there a workaround?

**Comment by SimonDarksideJ** [comment]
I'll investigate, but a simple workaround is to use the singleaxis axis and test if the value is 1 (or above 0.9) before actioning.

I assume you are working on OpenVR though SteamVR in your tests?

**Comment by ddutchie** [comment]
Correct. Running with Open VR.Thanks!

**Comment by keveleigh** [comment]
Should be fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5874
