### ISSUE TITLE
QR Tracking

### ISSUE THREAD

**Issue by overedge** [Microsoft/MixedRealityToolkit-Unity#4092]
## Describe the bug

Hello i wan't to try QR Tracking for my WMR headset in unity but if i run the project and i print QRTrackerStartResult i show 
```
        // The QRTracking Feature is not supported by the current HMD driver
        // systems
        FeatureNotSupported = 2
```

What the version of driver is work with my headset ? (hp wmr vr 1000)

## Your Setup 

- Unity Version 2017.4 LTS
- HoloToolkit 2017.4.3.0 - Refresh
- Windows 10 SDK 17763
- Last update Windows
- Visual Studio 2017

## Target Platform
- WMR immersive

## Additional context
My headset is hp wmr vr 1000
i have set this in cmd (Admin)
```
reg add "HKLM\SOFTWARE\Microsoft\HoloLensSensors" /v EnableQRTrackerDefault /t REG_DWORD /d 1 /F
```

**Comment by Yoyozilla** [comment]
This doc talks about the required driver:
https://docs.microsoft.com/en-us/windows/mixed-reality/qr-code-tracking
"You can use the QR tracking scripts in the MRTK scripts folder or write your own. Note: These plugins are only for Windows 10 October 2018 Update (also known as RS5) builds. The plugins will be updated with the next windows release. The current plugins were experimental and will not work for future version of the windows. New plugins will be published which can be used from next windows release and they will not be backwards compatable and will not work with RS5"

**Comment by Yoyozilla** [comment]
Please reopen if you need additional help!

**Comment by overedge** [comment]
I saw a friend use immersive WMR to read aruco marker how did he do it knowing that he did not have access to the webcam and the specatorview mode only works for hololens?
