### ISSUE TITLE
Spelling mistake in ManipulationHandler.md 

### ISSUE THREAD

**Issue by ChristophHoltmann** [Microsoft/MixedRealityToolkit-Unity#4093]
## Describe the Issue
Spelling mistake in README_ManipulationHandler.md in the "Events" topic: Manupulation 

## Existing Doc Link
Unity/Documentation/README_ManipulationHandler.md

**Comment by wiwei** [comment]
Thanks for filing this! I don't know who you are, but I'm really happy that you actually took the time to file this issue - I feel like most people would have been like "huh" and then moved on with their lives.

tl;dr issue reporter is the the hero we need.
