### ISSUE TITLE
Hololens Emulation: Cursor stops working after first air-tap on Hololens (Gen 1) using RC1

### ISSUE THREAD

**Issue by SimMue** [microsoft/MixedRealityToolkit-Unity#4094]
## Describe the bug

When using RC1 on hololens emulator, air-tapping does stop working after first tap.
After the cursor animates to a circle, the cursor stays as a circle and objects cannot be selected.

## Steps to reproduce
1. Create new unity project
2. Pull newest commit from mrtk_development
3. Copy Asset folder into unity project root folder => Wait until assets are loaded
4. Configure scene: Mixed Reality Toolkit --> Add to scene and configure... --> Select default configuration
5. Switch build settings to UWP
6. Change Player settings: Project Settings --> Player --> XR Settings --> Virtual Reality Supported
7. Build using Utilites: Mixed Reality Tookit --> Utilities --> Build Window --> Build Unity Project
8. Deploy to emulator: Open Visual Studio Solution --> Switch to x86 --> Select Hololens Emulator --> Click Start
9. Perform an air-tap

## Expected behavior

Scene starts, white dot indicating gaze is seen. When air-tapping, the cursor should animate from dot to circle to dot. The object being selected should also recognize that its being selected.

## Setup

- Unity Version 2018.3.7f1
- MRTK Version v2.0 RC1 and also the latest commit on development

## Target Platform

- HoloLens Emulator

## Additional context

This problem is similar to the bug described [here](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3909). @wiwei suggested to file another issue.

**Comment by AmineI** [comment]
Could you confirm whether this appears on real HoloLens or not ? I'm having the same issue (I'll add a detail by saying it happens on the latest emulator version, 10.0.17763.253, didn't try earlier ones), I'll be able to confirm in ~1/2 weeks

**Comment by SimMue** [comment]
I'm going to test this on the real hololens and will come back with more information next week.

**Comment by AmineI** [comment]
I just tested on real HoloLens and it's fine ! So the issue is only present in the emulator. That's still bothering at times - but thankfully the Editor Play Mode does the job most of the time :) .
