### ISSUE TITLE
Orbital needs a little redesign

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#4095]
Orbital provides two offsets in the inspector (LocalOffset and WorldOffset). The tooltip prohibits the use of both at the same time.
This should be reduced to just an offset and an enum distinguishing between local and world mode for that. Nothing really prevents you from screwing this up.

The difference between these two is just that worldOffset uses yawOnly. They have nothing to to with wether they follow a "LocalPosition" or a "WorldPosition" (static position) as I would have expected.

Futhermore, there is the orientationType yawOnly, which explicitly uses the TransformTarget. it cannot be combined with all the other orientations which could use this "keep it up right" option.

yaw Only should be a boolean used with all other options.

**Comment by Yoyozilla** [comment]
This is a feature request. updating tag to reflect.

**Comment by wiwei** [comment]
@cre8ivepark what do you think of this request?

**Comment by julenka** [comment]
Closing in favor of #5713
