### ISSUE TITLE
Pressable Buttons are invisible

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#4097]
## Describe the bug
I wanted to check the new buttons out, but their body is invisible.

## To reproduce

check out the PressableButtonExample scene

## Expected behavior

All buttons look like buttons

## Screenshots

![image](https://user-images.githubusercontent.com/32508825/56811523-2f72fb80-6839-11e9-9915-55155d6dd030.png)

## Your Setup (please complete the following information)

- Unity Version 2018.3.13f1
- MRTK Version v2.0

## Target Platform (please complete the following information)

- Editor
- WMR immersive

**Comment by Railboy** [comment]
Some of this is expected and some isn't. The bottom buttons alternate between no backplate / backplate, so those are fine. However the top buttons use a shared backplate that should stretch to cover them all.

This is what I see when I check out mrtk_development:
![Buttons1](https://user-images.githubusercontent.com/9789716/56832357-9b953580-6820-11e9-83d2-141bfda5e55e.PNG)

@cre8ivepark Probably unrelated to the buttons but I also notice a missing script reference in the same scene. I think it's an old solver script:
![MissingReference](https://user-images.githubusercontent.com/9789716/56832373-a780f780-6820-11e9-999a-26060f6f7301.PNG)

**Comment by Alexees** [comment]
@Railboy I took the screenshot from the 2019 RC1 prerelease using Unity 2018.3.13.f1. Might be the reason for the difference

**Comment by Yoyozilla** [comment]
Looks like this is solved in the latest development. Closing issue. Please reopen if you hit this again!
