### ISSUE TITLE
Feature Request: Move all service management out of MixedRealityToolkit and into MixedRealityServiceRegistry

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedRealityToolkit-Unity#4104]
## Describe the problem

With the introduction of the MixedRealityServiceRegistry (#4099) our registration story has become a bit muddled.

## Describe the solution you'd like

Turn the MixedRealityToolkit instance into a front-end for the service registry so we clean up our story without breaking existing services.

The ONLY place services are actually registered / stored is in the MixedRealityServiceRegistry class.

And the ONLY thing the MixedRealityToolkit instance would be responsible for is relaying MonoBehaviour events to the registered services (which is the one thing a static class can't do).

```
public class MixedRealityToolkit : MonoBehaviour, IMixedRealityServiceRegistrar
{
     [Obsolete("Use MixedRealityServiceRegistery.ActiveSystems.")]
     public IReadOnlyDictionary<Type, IMixedRealityService> ActiveSystems => MixedRealityServiceRegistry.ActiveSystems;

     [Obsolete("Use MixedRealityServiceRegistery.RegisteredMixedRealityServices.")]
     public IReadOnlyList<Tuple<Type, IMixedRealityService>> RegisteredMixedRealityServices => MixedRealityServiceRegistry.RegisteredMixedRealityServices;

     ...

    [Obsolete("Use MixedRealityServiceRegistery.RegisterService directly.")]
    public bool RegisterService<T>(
        Type concreteType,
        SupportedPlatforms supportedPlatforms = (SupportedPlatforms)(-1),
        params object[] args) where T : IMixedRealityService
    {
        MixedRealityServiceRegistery.RegisterService(concreteType, supportedPlatforms, args);
    }

    ...
}
```

**Comment by wiwei** [comment]
@davidkline-ms can you comment a bit on this? It seems like it would be valuable to have your take on the next steps associated with this change.
