### ISSUE TITLE
SharingServices.exe is missing

### ISSUE THREAD

**Issue by DaRockJaeger** [Microsoft/MixedRealityToolkit-Unity#4108]
Hello,

in your repository last year ago, the folder  "External/Holotoolkit/Sharing/Server" contained a cool file called "SharingService.exe". You could connect several Hololenses with that server and you could use them for Multiplayer.

Was that "SharingService.exe" moved to another folder? I can't find it anymore :(

**Comment by DaRockJaeger** [comment]
When the Toolkit was called "HoloTookit" in 2017, the SharingServices.exe was there. Was ist removed some months ago?

**Comment by keveleigh** [comment]
If you're looking for it in MRTK v2, we're still working on our sharing implementation (#2509, #2721, #2722, #3664, #4016).
If you're looking for it in HTK, it can still be found in the release branch: https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/htk_release/External/HoloToolkit/Sharing/Server
