### ISSUE TITLE
Copy & Customize of MRTK settings should dirty the scene so that profile change is saved

### ISSUE THREAD

**Issue by ForrestTrepte** [Microsoft/MixedRealityToolkit-Unity#4109]
## Describe the bug

When MRTK applies changes via *Copy & Customize*, it should dirty the scene so that the scene can be saved.

## To reproduce

1. Create new project, add MRTK foundation .unitypackage
2. Click on Mixed Reality Toolkit > Add to Scene and Configure
3. Save scene
4. Select MixedRealityToolkit game object
5. In Inspector, click Copy & Customize button
6. View MixedRealityToolkit game object in inspector, notice that Active Profile = MixedRealityToolkitConfigurationProfile (the settings that you just cloned)
7. Exit Unity
8. Reopen project

## Actual behavior
MixedRealityToolkit game object Active Profile = DefaultMixedRealityToolkitConfigurationProfile.

## Expected behavior
* After step 5, asterisk (*) is shown in the Unity title bar, indicating that the scene is dirty
* As part of step 7, you are prompted to save changes to the scene before exiting
* After step 8, MixedRealityToolkit game object Active Profile = MixedRealityToolkitConfigurationProfile (the settings that you just cloned)

## Your Setup (please complete the following information)

- Unity Version 2019.1.0f2
- MRTK Version v2.0.0 RC1

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by ForrestTrepte** [comment]
It looks like this may be fixed in the latest mrtk_development branch.

**Comment by ForrestTrepte** [comment]
Strange. I was reproducing this earlier with *Add to Scene and Configure* not dirtying the scene. But now I can't reproduce that. I'm going to edit this bug to refer just to *Copy & Customize*, which I can reproduce even in the latest mrtk_development branch.

**Comment by wiwei** [comment]
Thanks for reporting (and fixing!) this issue!
