### ISSUE TITLE
Profile-"Constellation" templates - UX Boost!

### ISSUE THREAD

**Issue by KarlSupertramp** [microsoft/MixedRealityToolkit-Unity#4111]
## Describe the problem
I'm a bit lost in the forest of options all the profile types give you. I unsderstand why it makes sense to have all these settings, but in my opinion this is just a confusing mess that leads to frustration and a waste of resources (time). 

## Describe the solution you'd like
For a start, it would be great to have downloadable setups for all the devices out there. I'm developing for HL1 I'd love to just have it like the old HLTK. No need for hand rotation and all that other fancy stuff (,yet...). Right now I'm really struggeling to get my project up and running again simply because there is too much stuff to create, edit, rename, research etc etc...

## Describe alternatives you've considered
Alternatively and even better would be if you could just toggle an option for what kind of device you're developing for (or trying to simulate in the editor). Adjustability is great, but not always needed.

## Additional context
Renaming the profiles doesn't really work by the way. (Filename does not chang in the file itself and cloning does not set itself to the name that you write down in the inputfield)

**Comment by wiwei** [comment]
Thanks for the feedback - there's a lot of feedback around this, and this is something we're looking to fix up. Tagging this with Profile and Inspectors to help with data around impact

**Comment by Zee2** [comment]
Profiles have been (mostly) burninated in MRTK3.
