### ISSUE TITLE
Updating with Windows Insider destroyed my Windows Installation beyond repair

### ISSUE THREAD

**Issue by thedevleon** [Microsoft/MixedRealityToolkit-Unity#4113]
I wanted to try out the new MRTK and as instructed in the documentation, opted into the Windows Insider Program so I could get the latest Windows SDK required.
While the update installed fine, a lot of errors starting popping up like "the application was unable to start correctly". Turns out, the cumulative update for the may update completely removed everything related to the .NET Framework as well as left me unable to reinstall any .NET Framework.

Please see more detail on the issue [here](https://developercommunity.visualstudio.com/content/problem/421852/windows-10-64-bit-1809-net-framework-4-and-472-can.html) and [here](https://answers.microsoft.com/en-us/insider/forum/all/cant-enable-net-environment-in-windows-10-1903/f0431447-d385-4238-8de7-80fea0902e94).

I now have no other option other than to do a complete new install of my windows installation.
A complete day of work is wasted, and this is unacceptable.

Just as a caution to people who want to checkout the latest MRTK - do it in a VM. At least that way it won't screw up your primary work computer and put you out of work for a whole day.

**Comment by Naphier** [comment]
Thank you, we were debating this today and fortunately decided to use an older release of MRTK. MS's move to incorporate and release features in this SDK when the hardware is not available seems very premature. Or maybe some people actually have H2s? Anyway, the 2.0.0 RC1 release notes don't make mention of needing the insider preview, we only stumbled upon it in the readme.md with no information that it's a new requirement.

**Comment by Alexees** [comment]
I found this by accident and followed it. Worked well. Only issue was that I had to update from the recommended preview build as the recommended one had an issue with the portal:
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/4030

**Comment by Yoyozilla** [comment]
We actually do not require you to enroll and upgrade your OS to the latest, only the insider SDK :) 

Closing this issue as this is related to Windows update not MRTK. 

You can also find more MRTK doc here: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html

**Comment by thedevleon** [comment]
Thanks, but when I click on the link to the "Windows SDK 18362+" in the docs, the first thing that pops on the page, is this:

Install the latest Windows 10 Insider Preview release.
Make sure you have the latest Windows 10 Insider Preview. We match the latest Windows 10 SDK and Windows 10 Mobile Emulator preview releases to the latest Windows Insider Preview OS Release.

This gives the impression that the 18362 SDK won't work without upgrading to Windows Insider Release 18362 too. Maybe you can add a small tip saying that upgrading is not necessary.

**Comment by keveleigh** [comment]
@thedevleon This link [was just updated](https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/4127/files), as the SDK has now been released out of preview.

**Comment by thedevleon** [comment]
The link on the main readme (https://github.com/Microsoft/MixedRealityToolkit-Unity) still links to the sdk preview page.

**Comment by keveleigh** [comment]
Ahh yes, thank you. I brought these changes into our stabilization branch via https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/4139, which will be merged into mrtk_release (and thus the main landing page) today.
