### ISSUE TITLE
Some Vector2 input changes are not reported correctly 

### ISSUE THREAD

**Issue by luis-valverde-ms** [microsoft/MixedRealityToolkit-Unity#4114]
The code used to set Vector2 values in interaction mappings (MixedRealityInteractionMapping.Vector2Data setter) performs the following check:
```
Changed = !vector2Data.x.Equals(value.x * invertXAxisFactor) &&
          !vector2Data.y.Equals(value.y * invertYAxisFactor);
```
Which only returns true if both x and y components have changed.

**Comment by wiwei** [comment]
Closing, I believe this was fixed by #4116
