### ISSUE TITLE
HL1 opens MRTK 2 RC1 sample project in "window mode" instead of full screen

### ISSUE THREAD

**Issue by benjamincoven** [microsoft/MixedRealityToolkit-Unity#4115]
## Describe the bug

I am testing the MRTK 2 RC 1, I made a build with the HandInteractionExamples and installed it on a Hololens 1. However when I start the application it creates a holographic 2D window (like a UWP application) where the camera is rendered and no interactions are captured.

## To reproduce

Create a blank project with only the MRTK 2 RC 1 foundation and exemples then create a build with the HandInteractionExamples scene.

## Expected behavior

When the app starts, all app holograms should disappear and the app should be rendered in 3D with all interactions working.

## Screenshots

Please ask if needed.

## Your Setup (please complete the following information)

- Unity Version 2019.1
- MRTK Version 2 RC 1

## Target Platform (please complete the following information)

- HoloLens 1

**Comment by keveleigh** [comment]
Did you enable Virtual Reality Supported in your UWP settings?

![image](https://user-images.githubusercontent.com/3580640/56919560-c62bfc00-6a75-11e9-8b6c-4ec3667cd590.png)

**Comment by Yoyozilla** [comment]
@benjamincoven

**Comment by benjamincoven** [comment]
Sorry I was not in my office.

Yes now it works, Virtual Reality Supported was enabled but there was no sdk in the Virtual Reality SDK. Adding Windows Mixed Reality did the job.

I let you choose to close or not this issue since the MRTK2 automaticly enables Virtual Reality Supported but does not seem to add WMR to SDK list.

Thank you.

**Comment by wiwei** [comment]
I think that someone else hit something similar here because their gitignore rules were ultimately ignoring the manifest.json that we have (which will ensure that the WMR package gets pulled down).

It would be interesting to check to see that you didn't hit this issue.

Going forward if you hit this again + have a min repro we can look at, feel free to reopen this issue or file a new issue.

**Comment by Weasy666** [comment]
Um...i'm experiencing the same issue, even with a Virtual Reality SDK.
Here my config:
Unity 2019.1.4f1
Visual Studio 2019
MRTK v2.0.0-RC1-Refresh (Foundation + Examples)
![image](https://user-images.githubusercontent.com/11967542/58794503-a2218480-85f8-11e9-9a58-068a00b6f4fb.png)
![image](https://user-images.githubusercontent.com/11967542/58794854-79e65580-85f9-11e9-9bc8-b0d0fd4e9d53.png)

**Comment by keveleigh** [comment]
@Weasy666 A few things to try:
1. Open the [Package Manager](https://docs.unity3d.com/Packages/com.unity.package-manager-ui@1.8/manual/index.html) to verify that the Windows Mixed Reality package successfully downloaded
2. Try deploying with the "WSA Holographic Remoting Supported" checkbox unchecked. I think I've seen this behavior before with that checked

**Comment by Weasy666** [comment]
@keveleigh i checked it out with "WSA Holographic …" unchecked and that did the trick. Thanks for that!

**Comment by benjamincoven** [comment]
@keveleigh Maybe a stupid question but do you think it is possible to develop an Unity application that is not in fullscreen but in window mode, and that would reacts to inputs. This can be really interesting for developping 2D application with Unity instead of classic UWP.
