### ISSUE TITLE
Manipulation Handler : Rotate About Grab Point does not behave as expected, when grabbing at edges of collider

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#4126]
## Describe the bug

If you set "One Hand Rotation Mode" to "Rotate About Grab Point" and grab near the collider's edge, the rotation also applies an unexpected translation along the Y axis. 

## To reproduce

1. Apply "Manipulation Handler" to an object that has a box collider
2. Set the following properties on the "Manipulation Handler"
   a. Manipulation Type = One and Two Handed
   b. Two Handed Manipulation = Move Rotate
   c. Allow Far Manipulation = false
   d. One Hand Rotation Mode Near/Far = Rotate About Grab Point
   e. Release Behavior = Nothing
   f. Constraint On Rotation = Y Axis Only
   g. Constraint on Movement = Fix Distance From Head
   h. Smoothing Active = true
   i. Smoothing Amount = 0.01
3. Build and Deploy App
4. Grab object with one hand, at the edge of the collider.
5. Rotate hand

## Expected behavior

Object to stay attached to the hand, as you rotate

## Actual behavior

As you rotate, object translates up or down along y-axis.  Detaching from hand

## Your Setup (please complete the following information)

- Unity Version - 2018.3.8
- MRTK Version - RC1

## Target Platform (please complete the following information)

- HoloLens 2

## Additional context

Ping me for a repo if needed

**Comment by chrisfromwork** [comment]
Please validate Manipulation Handler: "Rotate Around Grab Point" Rotates around palm position not Grab Point #4128 when fixing this issue.

**Comment by thalbern** [comment]
wasn't fixed with 4681 - there's still some y offset when rotating the object in hand
