### ISSUE TITLE
Manipulation Handler: "Rotate Around Grab Point" Rotates around palm position not Grab Point

### ISSUE THREAD

**Issue by AMollis** [Microsoft/MixedRealityToolkit-Unity#4128]
## Describe the bug

When setting to "manipulation handler" to "rotate around grab point" seems to rotate around the palm position, and not the actual grab point.  This could be causing this issue as well.... https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/4126

## To reproduce

0. Assuming issue 4126 is fixed
1. Apply "Manipulation Handler" to an object that has a box collider
2. Set the following properties on the "Manipulation Handler"
   a. Manipulation Type = One and Two Handed
   b. Two Handed Manipulation = Move Rotate
   c. Allow Far Manipulation = false
   d. One Hand Rotation Mode Near/Far = Rotate About Grab Point
   e. Release Behavior = Nothing
   f. Constraint On Rotation = Y Axis Only
  g. Constraint on Movement = Fix Distance From Head
  h. Smoothing Active = true
  i. Smoothing Amount = 0.01
3. Build and Deploy App
4. Pinch object with one hand, so palm is not within the collider
5. Rotate hand

## Expected behavior

Rotation to be around pinch point, not palm

## Your Setup (please complete the following information)

- Unity Version - 2018.3.8
- MRTK Version - rc1

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by chrisfromwork** [comment]
Closing #4128 for now. We will use #4126 for tracking.
