### ISSUE TITLE
Setting Bounding Box to "Activate Manually" Interferes with GameObject Rigidbody

### ISSUE THREAD

**Issue by ChauNTran** [microsoft/MixedRealityToolkit-Unity#4138]
## Describe the bug
When activation enum is set to "activate manually" in Bounding Box component, game object with rigidbody dances around.

## To reproduce

1. Go to HandInteractionExamples scene in Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes.
2. In the LunarModule gameobject, change activation to "activate manually".
3. Play the scene.
4. LunarModule dances around

## Expected behavior

LunarModule rigidbody should acts normally.

## Your Setup (please complete the following information)

- Unity Version 2018.3.9f1
- MRTK Version RC1

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
I can confirm, this is super weird.

**Comment by julenka** [comment]
Looks like this no longer repros on the latest mrtk_development.
