### ISSUE TITLE
Pinch Slider: Add snap points to pinch slider

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#4140]
## Describe the problem

Add snap points to pinch slider.

Specify number of snap points on a pinch slider. If 0 snap points specified, there are no snap points. Default number of snap points is zero.

## Describe the solution you'd like

Here's an extension of PinchSlider that adds snapping.  This implementation felt good.

```
    public class SliderWithSnapPoints : PinchSlider
    {
        [SerializeField]
        [Tooltip("The number of snap points")]
        float snapPoints = 100;

        float lastSnapPoint;
        float snapPointSize;

        public override void OnPointerDown(MixedRealityPointerEventData eventData)
        {
            base.OnPointerDown(eventData);
            if (eventData.used)
            {
                lastSnapPoint = SliderValue;
                snapPointSize = 1f / snapPoints;
            }
        }

        /// <summary>
        /// Handle slider value changes by dragging, and commit these changes.
        /// </summary>
        /// <remarks>
        /// Note, this requires the MRTK pinch slider to implement this function signature,
        /// and the pinch slider needs to call this function instead of instead setting SliderValue 
        /// directly.
        /// </remarks>
        protected override void OnPointerDragged(float newSliderValue)
        {
            var valueChange = Mathf.Abs(lastSnapPoint - newSliderValue);
            if (valueChange >= snapPointSize)
            {
                lastSnapPoint = SliderValue = newSliderValue;
            }
        }
    }

```

**Comment by provencher** [comment]
Seconding this. It's important for our usecases.

**Comment by Yoyozilla** [comment]
@AMollis  feel free to open a PR with your change!
 @julenka  to review!

**Comment by julenka** [comment]
Removing myself from asignees for now, since as I understand @AMollis will be making the PR, and I'll be doing the review.

**Comment by julenka** [comment]
Feature request from a DDE partner, Hae-Jin Lee could provide details on the design / request.

**Comment by julenka** [comment]
> @AMollis feel free to open a PR with your change!
> @julenka to review!

Clarified a bit with Adam, I don't think Adam actually agreed to do the PR :-)

**Comment by julenka** [comment]
Hi @AMollis, this looks like a great candidate for an [experimental feature](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4688). Here's an example PR that implements an experimental feature: Hand constrainted UI: PR #4532 

Since I'm not actively working on this I'm removing myself from assignment. I need to focus on existing functionality of our other controls and adding tests to protect from regressions. Have a look at our [1906 Mileston](https://github.com/microsoft/MixedRealityToolkit-Unity/milestone/6) for an idea of the bugs we are working on.

If you or somebody else wants to make a PR with a snap slider as an experimental feature, I'd be happy to shephard it in!

**Comment by gauravb4** [comment]
Hey! I'm interested in contributing to this feature request. This would be my first Open Source contribution and just had a few questions regarding the procedure. I already went ahead and implemented the snap points, the number of which can be set in the editor. I was wondering what other features needed to be tied in with this to complete the request. 

Also attaching a demo of the feature, I'm really new to this so any feedback on how I should proceed is greatly appreciated!
[Demo.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/5054368/Demo.zip)

**Comment by 0tobsam0** [comment]
I modified this implementation slightly:

```cs
using Microsoft.MixedReality.Toolkit.UI;
using UnityEngine;

public class SliderWithSnapPoints : PinchSlider
{
#pragma warning disable 649
    [Tooltip("The number of snap points")]
    [Min(2)]
    [SerializeField] private int snapPoints = 5;
#pragma warning restore 649

    /// <summary>
    /// Handle slider value changes by dragging, and commit snap point aligned changes.
    /// </summary>
    /// <remarks>
    /// Note, this requires the MRTK pinch slider to implement this function signature,
    /// and the pinch slider needs to call this function instead of setting SliderValue 
    /// directly.
    /// </remarks>
    protected override void OnPointerDragged(float newSliderValue)
    {
        float gap = 1f / (snapPoints - 1f);
        newSliderValue = 0.5f * gap + newSliderValue;
        newSliderValue -= (newSliderValue % gap);

        SliderValue = newSliderValue;
    }
}
```
<br><br>
As the comment suggests you also have to edit the main PinchSlider script from:
```cs
public void OnPointerDragged(MixedRealityPointerEventData eventData)
{
    if (eventData.Pointer == activePointer && !eventData.used)
    {
        var delta = activePointer.Position - startPointerPosition;
        var handDelta = Vector3.Dot(SliderTrackDirection.normalized, delta);

        SliderValue = Mathf.Clamp(startSliderValue + handDelta / SliderTrackDirection.magnitude, 0, 1);

        // Mark the pointer data as used to prevent other behaviors from handling input events
        eventData.Use();
    }
}
```
To:
```cs
public void OnPointerDragged(MixedRealityPointerEventData eventData)
{
    if (eventData.Pointer == activePointer && !eventData.used)
    {
        var delta = activePointer.Position - startPointerPosition;
        var handDelta = Vector3.Dot(SliderTrackDirection.normalized, delta);

        OnPointerDragged(Mathf.Clamp(startSliderValue + handDelta / SliderTrackDirection.magnitude, 0, 1));

        // Mark the pointer data as used to prevent other behaviors from handling input events
        eventData.Use();
    }
}

protected virtual void OnPointerDragged(float newSliderValue)
{
    SliderValue = newSliderValue;
}
```

<br>
Hope it helps! :)
