### ISSUE TITLE
[MRTK-v2.0.0-Beta2/Unity/MacOS] WindowsSpeechInputProvider & WindowsDictationInputProvider Compiler Errors 

### ISSUE THREAD

**Issue by ratmat2002** [microsoft/MixedRealityToolkit-Unity#4142]
## Description

The following compilers error exist when MRTK-v2.0.0-Beta2 is used in a Unity project on MacOS:

Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs(20,71): error CS0535: 'WindowsSpeechInputProvider' does not implement interface member 'IMixedRealitySpeechSystem.StartRecognition()'

Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsDictationInputProvider.cs(20,74): error CS0535: 'WindowsDictationInputProvider' does not implement interface member 'IMixedRealityDictationSystem.StartRecording(GameObject, float, float, int, string)'

Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs(33,13): error CS0246: The type or namespace name 'Transform' could not be found (are you missing a using directive or an assembly reference?)

## To reproduce

Install MRTK-v2.0.0-Beta2 into any Unity project on MacOS and open the project.

## Expected behavior

No compiler errors should exist.

These compiler errors can be fixed by making the following changes:

WindowsSpeechInputProvider.cs (Lines 7 & 53)
-----------------------------------------
Change: 
#if UNITY_STANDALONE_WIN || UNITY_WSA || UNITY_EDITOR_WIN
To:
#if UNITY_STANDALONE_WIN || UNITY_STANDALONE_OSX || UNITY_WSA || UNITY_EDITOR_WIN

WindowsDictationInputProvider.cs (Lines 10 & 44)
--------------------------------------------
Change:
#if UNITY_STANDALONE_WIN || UNITY_WSA || UNITY_EDITOR_WIN
To:
#if UNITY_STANDALONE_WIN || UNITY_STANDALONE_OSX || UNITY_WSA || UNITY_EDITOR_WIN

## Your Setup (please complete the following information)

- Unity Version: 2019.1
- MRTK Version: MRTK-v2.0.0-Beta2

## Target Platform (please complete the following information)

PC, Mac & Linus Standalone

**Comment by keveleigh** [comment]
This should be fixed as of https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/4088, though this has not yet made it into a release.

**Comment by chrisfromwork** [comment]
Closing this issue, please reopen if 4088 doesn't resolve the compilation problem.
