### ISSUE TITLE
Poking a button really slowly will enable highlight and sound but won't actually perform the action on the button

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4149]
## Describe the bug
Button highlight and sound doesn't match interaction

## To reproduce
On HoloLens 2 try to poke very slowly into a button (near interaction). Observe that the button will highlight and press the "click" sound but doesn't actually perform any action. We have the same behaviour while swiping diagonal or sideways through the button. 

## Expected behavior
Button should only highlight or play sound when it's actually activated

## Your Setup (please complete the following information)

RC1

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by Yoyozilla** [comment]
This impact user confidence in pressing buttons. we should fix soon!

**Comment by thalbern** [comment]
should be fixed with the pressablebutton refactor and changing triggers to press (instead of release)

couldn't repro anymore with those changes on hl2

**Comment by Shubham7694** [comment]
"pressablebutton refactor" Who do you mean by it? I already have changed the trigger to press

**Comment by thalbern** [comment]
@Shubham7694  it got fixed with this PR https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4527

**Comment by Shubham7694** [comment]
@thalbern  Any idea when these fixes or going to be released?

**Comment by thalbern** [comment]
@Shubham7694 the fixes are available in mrtk_development branch and in the upcoming release RC2 which is currently out for review and should be merged soon #4834
