### ISSUE TITLE
Add a scroll bar to the slate sample interaction

### ISSUE THREAD

**Issue by benjamincoven** [microsoft/MixedRealityToolkit-Unity#4153]
## Describe the problem

The 2D slate panel tool described [here](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Documentation/README_Slate.md) is very usefull however the scrolling can be incoveniant and it does not work on Hololens 1.

## Describe the solution you'd like

Add a scroll bar to the right.

## Describe alternatives you've considered

Add top and down buttons.

**Comment by happyao** [comment]
Same question, do you get any feedback? Thanks!

**Comment by benjamincoven** [comment]
No I didn't, there was a change on this prefab in the RC 1 Refresh release, I don't know if it is related. I am working on something else for the moment, I only tried to migrate from RC 1 to RC1 Refresh and it totally broke my testing project.

**Comment by happyao** [comment]
Thanks for you reply.  I added theHandInteractionPan.cs  and change the finger index to the head ray, but  it still can't work on hololens 1. My unity version is 2018.3.14f1. 

HandInteractionPan.cs: This script handles articulated hand input for touching and moving the content on the slate's ContentQuad.

**Comment by benjamincoven** [comment]
I close this issue because it has many duplicates : #4555 #4732 #4727
