### ISSUE TITLE
ManipulationHandler won't respect "Two Handed Manipulation Type"

### ISSUE THREAD

**Issue by limbusdev** [Microsoft/MixedRealityToolkit-Unity#4155]
## Describe the bug

When Setting the property "Two Handed Manipulation Type" to "Rotate", the host transform can still be translated with gestures.

## To reproduce

1. Add ManipulationHandler to a Default cube with Collider
2. Set "Two handed Manipulation type" to "Rotate"
3. Try to translate it

## Expected behavior

The host transform (cube here) should only rotate.

## Your Setup (please complete the following information)

- MRTK v2.0.0 RC1

**Comment by julenka** [comment]
Hi, thank you for filing a bug!

If you want to make the object rotate using two hands, but not move, please double check the **Manipulation Type** field, and make sure it is set to **Two Handed Only**.

When I set the repro steps as described I get rotation only when Manipulation Type is set to Two handed only. I get one hand translation and two hand rotation when Manipulation Type is set to One And Two Handed. 

Thank you @johnppella for investigating.

**Comment by limbusdev** [comment]
Hi, thank you for replying. Shouldn't this work with "One Handed Only" and "One and two handed" as well?

**Comment by julenka** [comment]
Hm, I think I'm a little bit confused...I'd like to come up with a solution though that's understandable, so let's debug this.

Could you describe the desired behavior you want again, and the configuration you used?

My understanding is you want to be able to have an object that can be rotated, but not moved. The rotation should be perform-able with two hands. If you try to use one hand, then nothing should happen.

The configuration you tried was:

- 1 and two handed manipulation allowed
- Two hand manipulation mode is set to 'rotate only'.

Thanks, hopefully we can come up with a design that works.

**Comment by limbusdev** [comment]
Alright, maybe it's better to tackle it from another side. I want to be able to set the behaviour for one and two hand gestures, not only for one handed. Right now only two handed gestures are settable. I watn to be able to set what happens, when using only one handed gestures. Maybe another setting "One handed manipulation type" where I can set "Rotate only" would be the way to go.

**Comment by limbusdev** [comment]
Alright, maybe it's better to tackle it from another side. I want to be able to set the behaviour for one and two hand gestures, not only for one handed. Right now only two handed gestures are settable. I watn to be able to set what happens, when using only one handed gestures. Maybe another setting "One handed manipulation type" where I can set "Rotate only" would be the way to go.
