### ISSUE TITLE
Gestures Documentation not distinguishing between cumulativeDelta and normalizedOffset

### ISSUE THREAD

**Issue by limbusdev** [microsoft/MixedRealityToolkit-Unity#4156]
## Describe the Issue

Trying to figure out the updated interface from `INavigationHandler` and `IManipulationHandler` to `IMixedRealityGestureHandler<Vector3>` I came across the [Gesture Events Documentation](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Gestures.html#gesture-events). There it says `eventData.InputData` represents `cumulativeDelta` or `normalizedOffset`. It does however not explain how to distinguish between them.

Please add Information on how to really upgrade from the old interfaces.

**Comment by julenka** [comment]
Thank you for the feedback! @lukastoenneMS  is this something that you worked on, and could help with?

**Comment by lukastoenneMS** [comment]
The way to distinguish different actions is by string comparison. Have a look at the gesture demo script, this handles the gesture events and looks at [eventData.MixedRealityInputAction.Description](https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.Input.BaseInputEventData.html#Microsoft_MixedReality_Toolkit_Input_BaseInputEventData_MixedRealityInputAction) to determine the source of the event:
[MixedRealityToolkit.Examples/Demos/HandTracking/Script/GestureTester.cs](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/acee452b82ffbfe6f48c0c4b1086058496d94161/Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/GestureTester.cs#L60)
