### ISSUE TITLE
Can't get IMixedRealityGestureHandler to call methods

### ISSUE THREAD

**Issue by limbusdev** [microsoft/MixedRealityToolkit-Unity#4157]
## Overview

Hi there. I am trying to upgrade my stuff from `IManipulationHandler` and `INavigationHandler` to the newer MRTKv2 `IMixedRealityGestureHandler`.

As a simple example I added a cube to the Scene, added a Script "RotationGesture" to it with this Content:

```cs
public class RotationGesture :
    BaseInputHandler,
    IMixedRealityGestureHandler<Vector3>
{
    private static IMixedRealityInputSystem inputSystem = null;
    protected static IMixedRealityInputSystem InputSystem => inputSystem ?? (inputSystem = MixedRealityToolkit.Instance.GetService<IMixedRealityInputSystem>());


    # region IMixedRealityGestureHandler
    public void OnGestureUpdated(InputEventData<Vector3> eventData)
    {
        Debug.Log("OnGestureUpdated(InputEventData<Vector3> eventData)" + eventData.InputData);
        eventData.Use();
    }

    public void OnGestureCompleted(InputEventData<Vector3> eventData)
    {
        Debug.Log("OnGestureCompleted(InputEventData<Vector3> eventData)" + eventData.InputData);
        
        inputSystem.PopModalInputHandler();
        eventData.Use();
    }

    public void OnGestureStarted(InputEventData eventData)
    {
        Debug.Log("OnGestureUStarted(InputEventData eventData)" + eventData.ToString());

         inputSystem.PushModalInputHandler(gameObject);
    }

    public void OnGestureUpdated(InputEventData eventData) => Debug.Log("OnGestureUpdated(InputEventData eventData)" + eventData.ToString());

    public void OnGestureCompleted(InputEventData eventData) => Debug.Log("OnGestureCompleted(InputEventData eventData)" + eventData.ToString()); 

    public void OnGestureCanceled(InputEventData eventData)
    {
        Debug.Log("OnGestureCanceled(InputEventData eventData)" + eventData.ToString());

        inputSystem.PopModalInputHandler();
        eventData.Use();
    }

    #endregion IMixedRealityGestureHandler
}
```

and tried to perform the gesture (Right Mouse click, hold and move with space or rotate Hand with E, R and F) in Simulator in Unity Editor. But None of the Methods gets called.

Either I am trying to perform the Gesture the wrong way in the Simulator or something else is wrong.

## Expected Behavior

Expected to see the debug logs.

## Actual Behavior

Nothing happens

## Steps to reproduce

1. Add simple cube to Scene 
2. Add `RotationGesture` to it
3. Start Simulator and try to perform gesture

## Mixed Reality Toolkit Release Version

MRTK v2.0.0 RC1

Any ideas? What am I doing wrong? Thank you

**Comment by lukastoenneMS** [comment]
You probably need to switch the input simulation hand mode from "Articulated" to "Gestures":
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSimulation/InputSimulationService.html#hand-simulation

The Articulated mode does not raise gesture events, since it emulates the Hololens 2, which (afaik) does not raise these events either. "Gestures" is emulating Hololens 1, which uses the gesture events.

**Comment by wiwei** [comment]
Closing this issue out, as it seems like @lukastoenneMS has provided an answer, please reopen if it hasn't addressed your question.
