### ISSUE TITLE
Docs: "Service Provider" link points to "MRTK Configuration Guide"

### ISSUE THREAD

**Issue by paco-ms** [Microsoft/MixedRealityToolkit-Unity#4163]
## Describe the Issue
See here:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/MixedRealityConfigurationGuide.html

Note the section in the side panel is "How Tos > Service Provider"

![image](https://user-images.githubusercontent.com/36960481/57091913-16e26580-6cbf-11e9-8a30-e1bc27147673.png)

**Comment by keveleigh** [comment]
Fixed via #4190
