### ISSUE TITLE
MRTK scripts should support multi-object editing

### ISSUE THREAD

**Issue by provencher** [microsoft/MixedRealityToolkit-Unity#4165]
## Describe the problem

Multiselecting objects, like buttons, with the same components, does not support batch editing the properties.

## Describe the solution you'd like

Simply add this attribute to MRTK inspector scripts, to allow multi-object editing.
https://docs.unity3d.com/ScriptReference/CanEditMultipleObjects.html

**Comment by wiwei** [comment]
@provencher do you have some other specific ones in mind? Or maybe this is a question for the greater set of folks on this, which is if the set of things that should be multi-editable is obvious (@Railboy)

**Comment by Railboy** [comment]
Most if not all of our UX controls should be using this feature.

**Comment by provencher** [comment]
Every time I come across a script that doesn't have, I wish it did.

I ran into this editing buttons and other controls, for example. I can't imagine a case where it wouldn't be useful.

**Comment by BillingsAm3** [comment]
@polar-kev : Heard back from the partner that this was an old request and can be closed

**Comment by polar-kev** [comment]
Thanks @BillingsAm3.
