### ISSUE TITLE
Slate prefab box collider performance issue

### ISSUE THREAD

**Issue by carmines** [microsoft/MixedRealityToolkit-Unity#4167]
The box collider on the slate prefab is using a sphere, where the grabbable visual is a box 
![image](https://user-images.githubusercontent.com/36190349/57110908-11047880-6cef-11e9-9ffb-ac783214d2d9.png)

![image](https://user-images.githubusercontent.com/36190349/57110934-34c7be80-6cef-11e9-8fa1-748f3caa4982.png)

**Comment by julenka** [comment]
@cre8ivepark , I believe you worked on the slate prefab, could you please take a look?

**Comment by wiwei** [comment]
I've got a fix for this.

**Comment by wiwei** [comment]
A couple of notes for future folks, especially people who don't know that much about unity physics debugging guides.

Note that the screenshot above was taken in play mode with the physics analysis tools enabled - that is, you'll want to:

1) Go to Window->Analysis->Physics Debugger
2) Check this box

![image](https://user-images.githubusercontent.com/5840182/57956092-a76a9980-78ac-11e9-84e8-76a7ec64a17e.png)

3) Add the slate prefab to an empty scene
4) Enter play mode, and then press spacebar to use input simulation to move your hand ray pointer over the slate - you'll see the colliders show up.

**Comment by julenka** [comment]
Fixed by #4669
