### ISSUE TITLE
Pressable button inconsistent firing

### ISSUE THREAD

**Issue by provencher** [microsoft/MixedRealityToolkit-Unity#4169]
## Describe the bug

A default pressable button's onclick event fires inconsistently, and often more than once per press, unless the physical event router script's enum is set to EventOnClickCompletion

![image](https://user-images.githubusercontent.com/7420990/57112328-841ce780-6d0d-11e9-8ea1-8abd2e000022.png)

It seems that this mode also only triggers when the the button is released, but this makes it mismatch with audio cues, and makes it difficult to fire. The name is also unclear.

![image](https://user-images.githubusercontent.com/7420990/57112407-da8a2600-6d0d-11e9-9282-c50035b54a39.png)

## To reproduce

Copy a pressable button example, like one taken from the hand interaction scene.
Add an event OnClick, and it will fire more than once, and sometimes accidentally.

## Expected behavior

Button onclick event fires once per touch event

## Your Setup (please complete the following information)

- Unity Version 2018.3.8f1
- MRTK Version v2.0 latest dev branch

## Target Platform (please complete the following information)
- HoloLens 2

**Comment by julenka** [comment]
@thalbern are you taking over on buttons now? Is this something you could look at?

**Comment by julenka** [comment]
@thalbern with your latest fixes is this done now?

**Comment by thalbern** [comment]
Seems like with the recent changes this is not happening anymore:
In the default setup the button will do the click on press and we only emit the pressed event once per button interaction. (there has to be a touch end to have this event trigger again). I agree with the click completion being confusing, it should be release, because that's what it's actually doing.

**Comment by thalbern** [comment]
The original issue here is fixed, however the confusing part (physical press event router event names) is still there - we have a ticket for removing the physical press event router and making the button easier to use which should tackle this issue.  see https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4258
