### ISSUE TITLE
Please provide updated SharingWithUNET example

### ISSUE THREAD

**Issue by limbusdev** [microsoft/MixedRealityToolkit-Unity#4172]
In MRTK v1 there was an example Scene "SharingWithUNET". Please provide this example for MRTK v2 as well.

**Comment by benjamincoven** [comment]
Also please separate more the code of networking and anchor sharing, thank you.

**Comment by chrisfromwork** [comment]
UNET is deprecated by Unity. We are actively working on other sharing solutions but will not be building a new UNET based sharing experience for MRTK v2.
