### ISSUE TITLE
null reference when creating ManipulationHandler at runtime

### ISSUE THREAD

**Issue by lukastoenneMS** [microsoft/MixedRealityToolkit-Unity#4173]
## Describe the bug
I am creating a number of ManipulationHandler components _at runtime_ (because there are too many parts to set up manually in the editor). I'm getting null references on the 4 ManipulationEvents in the component (ManipulationStarted/Ended, HoeverEntered/Exited).

The event fields are never explicitly assigned in the code, it seems they "usually" are created automatically somehow, but this seems to fail at runtime.

## To reproduce

1. Create a new scene with MRTK
2. Add a cube
3. Use a script component to create the ManipulationHandler, like so:
```

using Microsoft.MixedReality.Toolkit.UI;
using UnityEngine;

public class ManipTest : MonoBehaviour
{
    void Start()
    {
        gameObject.AddComponent<ManipulationHandler>();
    }
}

```
4. Enter play mode
5. Look at the Cube
6. Hit null reference in ManipulationHandler.OnFocusEnter

## Expected behavior

Events are either initialized properly or checked for null.

## Your Setup (please complete the following information)

- Unity Version 2018.3.9f1
- MRTK RC1 Refresh

## Additional context

The null reference doesn't always seem to be logged in Unity, but is hit consistently when putting a breakpoint or debug print. This may be due to uninitialized memory (the events are not initialized to null either).

**Comment by randystiles** [comment]
This same runtime issue with events is probably present in the other interaction types, where they presume things are set up in the editor, instead of created at runtime.

**Comment by chrisfromwork** [comment]
A fix has been checked into mrtk_development. Please reopen this issue if additional problems occur or if the fix does not suffice.
