### ISSUE TITLE
Head cursor on by default in scene

### ISSUE THREAD

**Issue by erhavir** [microsoft/MixedRealityToolkit-Unity#4176]
## Overview
We are seeing the head cursor being on by default. It turns off when hands enter the scene, and then turns back on when hands go away. This isn't the behavior in the shell, where head cursor appears only before first hand interaction and disappears and then only appears again when voice has been used and then goes away upon hand interaction and stays away.

## Expected Behavior
If the user says "Select" or other voice commands, the head cursor is activated until their next hand interaction, at which time the head cursor goes away.

## Actual Behavior
Head cursor is always on.

## Steps to reproduce
_(Links to sample github project preferred)_

## Mixed Reality Toolkit Release Version
MRTK RC1

**Comment by Yoyozilla** [comment]
@julenka this seems like a shell parity issue, could you confirm?

**Comment by julenka** [comment]
Yeah, by default shell does not show gaze cursor.

**Comment by julenka** [comment]
Started on this yesterday.

**Comment by wiwei** [comment]
Closing this out now that the fix was merged
