### ISSUE TITLE
ManipulationHandler transform not settable at runtime

### ISSUE THREAD

**Issue by randystiles** [microsoft/MixedRealityToolkit-Unity#4179]
## Describe the bug

ManipulationHandler does not allow runtime setting of hostTransform for manipulation.

Works in editor, but not in a runtime script.

## To reproduce

1. Add manipulation handler to your GameObject in script using AddComponent
2. Try to set the hostTransform
3. It is private and there is no set method for it.

## Expected behavior

In script (runtime) set proper transform to use for Manipulation

Need method for setting hostTransform as part of class

## Your Setup (please complete the following information)

- Unity Version [2018.3.11f1]
- MRTK Version [ v2.0 RC Refresh]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive

**Comment by chrisfromwork** [comment]
It appears that julia has fixed this issue. If this bug exists with the fix in 4184, please reopen.
