### ISSUE TITLE
Null reference when creating Interactable at runtime

### ISSUE THREAD

**Issue by dl4mmers** [microsoft/MixedRealityToolkit-Unity#4183]
## Describe the bug

I'm getting a NullReferenceException @ Interactable.cs:272 when i'm creating gameobjects with  interactable components at runtime. This exception does not occur when i'm creating the gameobjects before runtime in editor. 

## To reproduce

1. Create a new MRTK scene. 
2. Add an empty gameobject and assign the following script:

```
using Microsoft.MixedReality.Toolkit.UI;
using UnityEngine;

public class InteractableTest : MonoBehaviour
{
    void Start()
    {
        GameObject test = GameObject.CreatePrimitive(PrimitiveType.Cube);
        test.AddComponent<Interactable>();
    }
}
```
3. Hit play button
4. Console should print following NullReferenceException

```
NullReferenceException: Object reference not set to an instance of an object
Microsoft.MixedReality.Toolkit.UI.Interactable.SetupStates () (at Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs:272)
Microsoft.MixedReality.Toolkit.UI.Interactable.Awake () (at Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs:192)
UnityEngine.GameObject:AddComponent()
InteractableTest:Start() (at Assets/InteractableTest.cs:9)
```

## Expected behavior

States should be setup at runtime without any exception. 

## Your Setup (please complete the following information)

- Unity Version 2018.3.14f1
- Mixed Reality Toolkit 2.0.0-RC1

## Target Platform (please complete the following information)

- HoloLens

**Comment by SimMue** [comment]
Same problem here. Haven't found a nice way how to achieve this yet.
My current workaround copies the interactable settings from a gameobject which I added to the scene via editor.

>`var copiedSettings = GetComponent<Interactable>();
var settings = loadedObj.AddComponent<Interactable>();
settings.enabled = true;
settings.States = copiedSettings.States;
settings.Events = copiedSettings.Events;
settings.OnClick = copiedSettings.OnClick;
return settings;`

This works, however it would be really great if anyone could show me how to do this the right way.

**Comment by julenka** [comment]
Thank you! I'd like to take a look at this one. FYI @thalbern since you are on buttons, and Interactable is like a button :-)

**Comment by julenka** [comment]
Adding Urgency-soon tag because it is blocking a few people, with an unpleasant workaround (see SimMue comment above)

**Comment by julenka** [comment]
Starting on this.

**Comment by julenka** [comment]
Hi @dl4mmers I thought about this a bit more and actually was wondering if maybe you are looking for a quick, in-code way to add a component that handles clicks from pointers out of the box. Is this correct? In that case, Interactable may not actually be the tool that you want to use, since it is fairly complex and intended mostly to be something that can drive visual states based on pointers. The onclick events it exposes are more of a bonus.

Would it be useful to create in MRTK a "click handler" script which just exposes Unity Events like: 

- OnPointerDown
- OnPointerUp
- OnPointerClicked

That you can just listen for in code and hook up?

Or, do you really want to be able to instantiate an Interactable in code and hook up states and themes?

**Comment by dl4mmers** [comment]
Hi @julenka 
We need to create many different panels and buttons at runtime for a generic step-by-step solution. The steps are structured as a tree and all nodes and branches are stored in a XML or JSON file. The application should be compatible with the Hololens 1 and Hololens 2. Yes, we need to create buttons at runtime that handles clicks from pointers for the Hololens 1, but that would not be enough for Hololens 2 Near Interactions I guess. It would be nice if we easily could change the visual states and also be able to use other types of buttons like radio buttons, switches etc. 

For now a click handler script would be useful, but for the future I guess something like Interactable is nessessary for us.

**Comment by julenka** [comment]
Thanks for the response! I've merged #4433 last week and the fix will be available in our next release which should be coming out next week. Even though the null reference is fixed I am noticing that some properties of interactable are not so easy to configure in code, but I'm not sure which parts are most important for you. So please if you find specific examples of how you need to configure an interactable in code that is not working for you file an issue so we can prioritize fixing that.

**Comment by mmskrzyn** [comment]
Experienced this issue in MRTK v2.0.0 RC1 Refresh trying to programmatically add Intractable script to an active gameobject in a scene.

I received the same NullReferenceException regardless of when I tried to instantiate the script (Awake, Start, Update):

NullReferenceException: Object reference not set to an instance of an object
Microsoft.MixedReality.Toolkit.UI.Interactable.SetupStates () (at Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs:272)
Microsoft.MixedReality.Toolkit.UI.Interactable.Awake () (at Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs:192)
UnityEngine.GameObject:AddComponent()
Interactible:Awake() (at Assets/Scripts/Managers/Interactible.cs:29)

**Comment by julenka** [comment]
Hi, thanks for the comment! If you're feeling adventurous, please give the latest mrtk_development branch a go (you can just clone the repo and copy/paste the code, or grab a unity package from our CI system and import the unity packages). The latest mrtk_development has this fix.

The MRTK V2.0.0 RC2 Refresh will also have the fix once we release it. The release should happen soon (actively working on it).
