### ISSUE TITLE
Github.io Generation Problem?

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#4186]
## Describe the Issue
Some pages are not rendering correctly on Github.io. For example, on this page:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/EyeTracking/EyeTracking_ExamplesOverview.html

Images do not show up correctly, and the **Eye Tracking example package** link on that page returns a 404.

However, if you click the [Improve this Doc](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Documentation/EyeTracking/EyeTracking_ExamplesOverview.md/#L1) link for that page, all of the images and the package show up correctly.

**Comment by keveleigh** [comment]
GitHub is more forgiving with their image paths. I can update these.

**Comment by keveleigh** [comment]
Fixed links and images via https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/4190
