### ISSUE TITLE
Instanced Color on Standard Shader causes Visual Artifacts on Device

### ISSUE THREAD

**Issue by mgrman** [microsoft/MixedRealityToolkit-Unity#4188]
## Describe the bug

Turning on Instanced Color for back plates of the pressable buttons, to batch them, causes visual artefacts on device. Color flickers as the cursor moves over the buttons. Tested with PressableButtonPlated prefab. 

## To reproduce

1. In PressableButtonPlated prefab, in the Material on BackPlate GameObject enabled Instanced Color (close to the bottom in the inspector).
2. Deploy to device
3. Color flickers as the cursor moves over the buttons.

## Expected behavior

No visual artifacts, same as in Editor.

## Your Setup (please complete the following information)

- Unity Version 2019.1
- MRTK Version v2.0

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by Cameron-Micka** [comment]
Thank you Martin for filing this! Are you using the Graphics.DrawMeshInstanced api (or something similar) to render the backplates? Or, how are you passing in the instanced color?

**Comment by mgrman** [comment]
Nothing special, backplate is part of the scene.  Only checked the checkbox in the material. Then the interactable Theme changes the color based on button state using materialBlock

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Cameron-Micka** [comment]
Ah okay! When the “instanced color” checkbox is checked the shader assumes a buffer of instanced color properties exists. If one doesn’t exist (which one will not unless explicitly set) then it is probably reaching into uninitialized, or neighboring, memory hence the flickering colors. I’m hoping to open source an example of using this feature soon, but I can send you the example early if you would like?

**Comment by Troy-Ferrell** [comment]
I think this is a bug we may have seen earlier Cameron whereby during initialization the material property is accessed causing a new instance to be created when that shouldn't be the case because the InteractableShaderTheme should be setting values via materialblocks

**Comment by Cameron-Micka** [comment]
I was able to get more context on this, this has already been addressed with https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4049

**Comment by Rinatsin** [comment]
Добрый день. У меня возникла та же проблема с мерцанием после установки GPU Instance на материале. Хотя скрипт стоит уже исправленный.   Я делаю меню с компонентом Scrollig Objects, скрипт вешает на префаб меню , компонент MaterialInstance. И возникает ошибка 
------------------
ArgumentException: Could not find MaterialProperty: '_InstancedColor', Num properties: 96
UnityEditor.ShaderGUI.FindProperty (System.String propertyName, UnityEditor.MaterialProperty[] properties, System.Boolean
-------------------
Хотя в шейдере  и материале исходном визуально я вижу что это поле есть.

**Comment by Rinatsin** [comment]
And further . Of course, I'm not very good at shaders, but as far as I understand, the UNITY_INSTANCING_BUFFER_START (Props) block should be implemented in the shader. The standard shader has this block, but it does not implement the _InstancedColor property (there is only _Color).

**Comment by Cameron-Micka** [comment]
Hi @Rinatsin, that you for reporting this. You are correct the MRTK/Standard shader's instanced color property is named `_Color` and not `_InstancedColor` which you can [see here](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/e1d1a43632d2a84e567614b570ee114eaaa8ccea/Assets/MRTK/StandardAssets/Shaders/MixedRealityStandard.shader#L331). 

Do you know where the exception you posted above is coming from, or can you post the whole call stack? If it's coming from MRTK code it should be easy enough to change the FindProperty call from `FindProperty("_InstancedColor")` to `FindProperty("_Color")`.

**Comment by Rinatsin** [comment]
Thank you, Cameron. I corrected the name of the property in the file to _Color, since you say that it should be.
