### ISSUE TITLE
Gaze Input capability missing

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#4193]
## Describe the bug

Currently the _Gaze Input_ capability cannot be set in Unity. This is a Unity issue but it does [not appear](https://unity3d.com/search?refinement=issues&gq=Gaze) it has been reported to Unity. This bug severely affects MRTK and the ability for MRTK to properly set capabilities. Without this capability in Unity, the user must manually add it after the project has been exported to Visual Studio which is a step that can easily be missed. Without this capability it is also much harder for MRTK to enable the capability when a developer chooses the enable eye tracking.

I will submit a feature request about potentially setting this capability in a post-build step and I will link that feature request to this bug for clarity.

**Comment by genereddick** [comment]
Wish I had seen this bug report one day of annoying debugging earlier. Thanks for saving me from day two!

**Comment by StephenHodgson** [comment]
We're already modifying the appx manifest anyway. Shouldn't be hard to add something to fix it in the meantime.

**Comment by chrisfromwork** [comment]
@wiwei will work to have documentation updated for this issue.

**Comment by wiwei** [comment]
Checking up on this, we have docs for this already but I think it's fair to call this out a little stronger (i.e. in bold). Unfortunately as folks have mentioned this is ultimately a Unity issue (i.e. it doesn't have the capability listed in the unity UI).

**Comment by wiwei** [comment]
I'll use the other issue (#4194) to handle the appx manifest modification so that folks who are using the build tools can get that for free.
