### ISSUE TITLE
Auto-enable capabilities needed for eye tracking

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#4194]
## Describe the problem

Work is being done in the MRTK to try and automatically enable the app capabilities (permissions) necessary for services to work. On HoloLens 2, a special capability called _'Gaze Input'_ is needed, but that capability is not currently being set when eye tracking is enabled.

This is mainly due to #4193 which is currently out of our control, but it could be possible to work around this issue with a post-build step.

## Describe the solution you'd like

Ideally we should work with Unity to address the missing capability from the interface and then turn that capability on as we do with all other services. If that is not possible, we should implement it as a post-build step.

**Comment by chrisfromwork** [comment]
Assigning this to @wiwei based on #4193

**Comment by wiwei** [comment]
See https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4234 - I opted to make this a help text around the setting, rather than additional magic. I'm concerned that we already have a large amount of automagic in the toolkit, and additional stuff increases this automatic complexity.

**Comment by jbienzms** [comment]
Thanks for the work @wiwei. However, just adding help text isn't sufficient. We're in Berlin right now and partners are already struggling with this. In fact, one user created a PowerShell script that he could use as part of his automated build just to make sure this capability gets set. I don't feel that help text is enough. We either need to do something to modify the manifest or we need to push to get this surfaced in Unity so we can enable it as we do for all other capabilities.

I'm going to open this issue again. We can discuss in next weeks MRTK shiproom (I won't be able to make it this week due to the hacks).

Thanks!

**Comment by chbecker-ms** [comment]
We have precedent elsewhere in MRTK, Kurtis pointed me here: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/895c408b9c58703ebd7b2748191678f574aaa877/Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs#L68

We should resolve this one way or the other for all capabilities.

**Comment by jbienzms** [comment]
A friend at Unity just informed me that they were able to get the GazeInput capability surfaced in Unity 2019.3. 

![GazeInput](https://user-images.githubusercontent.com/5230670/61741010-97ac7d00-ad55-11e9-8dc9-252b3c739625.png)

It would be great to finally update the eye tracking service to automatically turn on the capability if running on 2019.3+

**Comment by Yoyozilla** [comment]
Let me check if we are also getting this fix into Unity 2018.4

**Comment by Troy-Ferrell** [comment]
@Yoyozilla any new info on ingestion into Unity 2018.4. If Unity doesn't surface the API, that will make it trickier. 

FYI @jbienzms and all, the MRTK build window can auto-add the Gaze Input capability since it builds the manifest itself:
![image](https://user-images.githubusercontent.com/25975362/62385422-e9999380-b509-11e9-8752-5eb8868bf214.png)

**Comment by jbienzms** [comment]
Thanks @Troy-Ferrell. The stated goal was that whenever any core MRTK service was "enabled" it should also enable any UWP capabilities that are dependencies for it to function. Eye Gaze was the only service that was not able to follow this rule because it was the only one that didn't have its related capability surfaced through the Unity editor. While I appreciate the check in the build window, I don't believe that helps enforce the goal of having each service ensure its related capabilities are enabled.
