### ISSUE TITLE
Create ARM64 and AMD64 build tasks

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4198]
MRTK RC1 (refresh) supports Unity 2019.1 which supports HoloLens 2 ARM64 applications. Our CI systems should validate this as well.

AMD64 appears to be missing as well which I assume we need for OpenVR/WRM support?

https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=1469

**Comment by MenelvagorMilsom** [comment]
@chbecker-ms we're currently looking at ways to improve build times. Each build task we add is another 10-15 minutes for CI and PR validation. We're looking at ways that we can parallelize our build tasks over multiple build agents. Until this is a possibility, adding additional build steps isn't feasible.

I'll keep this GitHub issue up to date with the latest on parallelizing our builds.

**Comment by MenelvagorMilsom** [comment]
I'm currently testing Unity cache server changes made to our build agents. If it significantly reduces build times we should be able to add these build tasks. However, I'm not certain that we'll have time to add Unity 2019.1 to the build agents and make the changes required to support it before Friday as myself and Maciej are focusing more on signing our NuGet packages.

**Comment by MenelvagorMilsom** [comment]
Unfortunately. The cache server changes have not had a significant effect on our build times. I'm still going to check the changes in (#4517), as there was no increase in time taken either. We can monitor this over the next few days to ensure that no significant change is observed.

**Comment by Yoyozilla** [comment]
any update here?

**Comment by MenelvagorMilsom** [comment]
No significant changes have been made to the agent pool to reduce build time. Our CI pipeline runtime has almost doubled since when I first commented on this issue (now at 70mins). However, most of the time, the actual queue time on doesn't last longer than a minute. However, queue times do reach 50-70 minutes often enough.

We could add these builds, and most of the time we wouldn't see any significant backlog. However, especially when we have stabilization builds running, queue times could potentially take a hit. 

We could set up a daily build that runs these flavours to catch failures maybe?

**Comment by wiwei** [comment]
> No significant changes have been made to the agent pool to reduce build time. Our CI pipeline runtime has almost doubled since when I first commented on this issue (now at 70mins). Most of the time, the actual queue time doesn't last longer than a minute. However, queue times do reach 50-70 minutes often enough.
> 
> We could add these builds, and most of the time we wouldn't see any significant backlog. However, especially when we have stabilization builds running, queue times could potentially take a hit.
> 
> We could set up a daily build that runs these flavours to catch failures maybe?

I think daily builds to run with these flavours sounds good - I think we'd want to get some coverage, but I agree that having them run on each CI run is going to increase time unnecessarily.

**Comment by MenelvagorMilsom** [comment]
Yeah, I'll start some work on this, but we still need Unity 2019 on the CI machines. @wiwei has requested this.

**Comment by MenelvagorMilsom** [comment]
Looks like we've got the required version now. I'll see if I can get a daily build up and running.

**Comment by Troy-Ferrell** [comment]
@MenelvagorMilsom what happened on this?

**Comment by MenelvagorMilsom** [comment]
@Troy-Ferrell the work is done for ARM64, but as far as I'm aware, play mode tests are still failing in Unity2019. Here are the results of the build running on my branch:
https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build?definitionId=37

I didn't get a chance to fix these failing tests, so I haven't completed #5736. It will definitely need some touching up one way or another.

**Comment by MenelvagorMilsom** [comment]
I rebased my branch and ran tests again today. Tests were still failing. However it looks like if you run the tests individually, they'll pass. When you run all again though, they fail again.

@keveleigh FYI, as I believe you were starting a conversation about this.

**Comment by keveleigh** [comment]
@MenelvagorMilsom Ah, thanks for the heads up! I'll take a look and update my notes

**Comment by davidkline-ms** [comment]
moving out of milestone as this is an build process (CI) change and is not a customer facing feature

**Comment by Troy-Ferrell** [comment]
This is fixed and will be enabled in the build window when opening a project in 2019.1 or newer. Closing as resolved

**Comment by keveleigh** [comment]
>enabled in the build window when opening a project in 2019.1 or newer

This issue was for enabling it in CI, though I believe that's completed too via our daily builds https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5736
