### ISSUE TITLE
Destroy transform errors

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#4208]
## Describe the bug
appear destroy transform errors when stop unirt editor.
Can't destroy Transform component of 'SpatialMesh - 1023'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.
## To reproduce

1.unity editor remote connect to Hololens 1 and open SpatialAwarenessMeshDemo scene;
2. Click on play button in unity editor;
3. show SpatialMeshs (wire frame grid);
4. See errosr; 

## Screenshots
 
![V56VSJ(_Z65KV2 ZG $%RJ](https://user-images.githubusercontent.com/38685433/57344410-b9945b80-7179-11e9-8340-3c5f1cf6cd40.png)

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.12f1]
- MRTK Version [e.g. v2.0.0 RC1 Refresh and v2.0.0 RC1 ]

## Target Platform (please complete the following information)

- HoloLens 1
 
I can not find any code about Destroy transform.

**Comment by wiwei** [comment]
@IfnoLee, are you also seeing similar issues/blocking problems when deployed to HL1 (i.e. non-remoting scenarios?)

**Comment by Troy-Ferrell** [comment]
No repo on latest
