### ISSUE TITLE
All Interactable buttons do not play "click" sound until after bringing up the WMR windows menu and dismissing the menu.

### ISSUE THREAD

**Issue by Tom-Wells-NW** [microsoft/MixedRealityToolkit-Unity#4209]
## Describe the bug

Toggle button does not play "click" sound until after bringing up the WMR windows menu and dismissing the menu. Sometimes I have to bring the WMR windows menu up more than once to get a "click" to sound. After this when I "click" the toggle button, the sound is only played once - subsequent clicks fail to play the sound. If you repeat the process of displaying the menu, the first click on the button succeeds in playing the sound, later clicks fail to play the "click" sound. Repeat and rinse.

## To reproduce

1. Create a new scene.
2. Drag ToggleButton prefab into the scene.
3. Run in Editor.
4. Click the button with WMR controller - sound not played.
5. Bring up the WMR windows menu.
6. Dismiss the menu.
7. Click the button with WMR controller - sound plays. 
8. Click the button again with WMR controller - sound does NOT play.
9. Bring up the WMR windows menu *again*.
10. Dismiss the menu *again*.
11. Click the button with WMR controller - sound plays. 
12. Click the button again with WMR controller - sound does NOT play.  

## Expected Behavior
Every click on a UX button (toggle or otherwise) should play the "click" sound. 

## My Setup 

Unity 2018.3.14f1
MRTK Version: MRTK v2.0.0 RC1 Refresh 

## Target Platform 

- WMR immersive
- PC
- UWP
- Target SDK Version: 10.0.18362.0
- Minimum Platform Version: 10.0.10240.0

## Additional context

N/A

**Comment by julenka** [comment]
Hey @radicalad could you see if this repros in latest?

**Comment by radicalad** [comment]
@julenka this still repros in mrtk_development.

**Comment by radicalad** [comment]
Just checked the other Interactable button types - this repros across the board.

**Comment by radicalad** [comment]
Finally got to the bottom of this. The "click" you hear on the button immediately following the dismissal of the WMR pins panel is in fact the shell's focus "clicking" back into the exclusive application. It is not tied any way to `Interactable`.

I set breakpoints in the `InteractableAudioTheme`. The default theme for `Interactable` has no audio implemented. In the case of pressable button prefabs, they handle audio feedback via UnityEvents and an Audio source component.

A quick way to confirm the above shell "click":
- Launch any exclusive app
- Open pins panel & launch settings
- Click outside of the Settings slate (click)
- Close Settings and click in the app again. (you'll hear it exactly once)
