### ISSUE TITLE
Throwing objects is not working in ManipulationHandler, object just drops to ground

### ISSUE THREAD

**Issue by Tom-Wells-NW** [microsoft/MixedRealityToolkit-Unity#4210]
## Describe the problem

Please add **DragAndDropHandler** (or something similar) back into the MRTK v2. I think throwing and tossing interactable objects will be useful in MR games. ManipulationHandler does not seem to allow for throwing or tossing objects.

## Additional context

For and example of what I mean, see this video: https://www.youtube.com/watch?v=CcoX6g67S6o

**Comment by Shizola** [comment]
@cre8ivepark Hi Yoon, I tested this the other day and can confirm this behaviour doesn't currently work. 
If you try the HandInteractionExamples scene and try to throw one of the cubes, it will just drop directly downwards. I had little look and it seems the method that gets the velocity of the controllers always returns zero.

I'm switching over from using VRTK and I would definitely appreciate more grabbing / throwing options.

**Comment by Tom-Wells-NW** [comment]
Thanks for the feedback. The DragAndDropHandler also had a distance scale property (that might not be useful in non-gaming systems). Would it be possible to add this property to the ManipulationHandler? The distance scale property is a Z-axis scale movement multiplier.

**Comment by julenka** [comment]
Hi @Tom-Wells-NW, yes it  is possible to add, however it would be great to move this into a separate issue / feature request., since this issue is specifically about throwing objects.

**Comment by googlan** [comment]
Should be fixed with #5259 . This fixes specifically Release behavior for MR controllers and articulated hands.
