### ISSUE TITLE
Visual Debugger for pointers and colliders 

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4212]
## Describe the problem

Currently it's really hard to figure out what's going on whenever you fail to manipulate or grab objects with articulated hands on hololens 2. 

## Describe the solution you'd like

It would be great to have some sort of debug visualization that shows eg:
- which pointer is currently active
- (hand)rays
- intersection points ptr / geometry
collision spheres / bounding volumes

**Comment by Yoyozilla** [comment]
nice to have!
If community wants to add this, would be awesome!

**Comment by wiwei** [comment]
@thalbern do you have any more details on the specifics there? The level of detail so far is one where we can probably do something but not know if it is valuable.

**Comment by thalbern** [comment]
the info i got from our customers is in the description. As far as i understood the optimal scenario would be a mix of some debug info on a 2d slate and some 3d debug visualizers.
2d slate: active pointer, focus object, ???
3d visualization: draw hand rays, draw intersection points when ptr ray hits geometry, draw collision spheres / bounding volumes (they only have that in unity editor, but wouldn't see that on the device itself)

**Comment by polar-kev** [comment]
Closing due to low interest from customer/community.
