### ISSUE TITLE
Make hand mesh / joint visualization a platform setting

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4213]
## Describe the problem

On Hololens 2 we usually don't want to visualize hand mesh / joints for performance reason, however for eg the hand input simulation in editor we still want to show the joints. Currently you have to modify the profile (or setting in the example scene) to switch the mesh / joints on / off whenever you switch your debugging / testing scenario from editor to hololens 2. It would be great to have this as a per platform setting to avoid having to change the profile everytime you're deploying on device.

## Describe the solution you'd like

A per platform setting for hand mesh / joing visualization.

**Comment by Yoyozilla** [comment]
This would be nice to have. We should also add a doc in the perf section to note this.

**Comment by Yoyozilla** [comment]
Docs needs to be soon.

**Comment by wiwei** [comment]
@Yoyozilla, is the Urgency-Soon issue for the documentation guidelines, or for everything?

**Comment by Yoyozilla** [comment]
urgency soon on Doc.

**Comment by Yoyozilla** [comment]
removing urgency soon as we have the HL2 default profile now.

**Comment by wiwei** [comment]
This is still a painpoint for folks using this, and I'm plus1ing this because folks are still keen on getting this fixed.

The hand joint problem is still there even with the HL2 profiles
