### ISSUE TITLE
Offset ray while scaling a bounding box with near interaction on Hololens 2

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4214]
## Describe the bug

Ray that is drawn from your hand to the corner of a slate on scaling while hand is moving away from the slate has an offset 

## To reproduce

Create a slate and try to scale by grabbing one of the end points. If your hand moves away from the slate while doing that there's a ray drawn that should point to the corner of the slate. On moving your hand that ray will start to drift off.

## Expected behavior

Ray should be drawn between hand and corner of slate

## Your Setup (please complete the following information)

- MRTK v2 RC1

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by Yoyozilla** [comment]
@cre8ivepark  could you please evaluate this?

**Comment by thalbern** [comment]
@Yoyozilla @cre8ivepark i've got screenshots and a video showing the problem. Please poke me if you need access to that!

**Comment by wiwei** [comment]
@thalbern, any chance you could share that video here?

**Comment by thalbern** [comment]
@wiwei I don't think I can - it's a hl2 capture from one of the customers - it doesn't show a lot, but I rather not post this until someone signs off on this

**Comment by thalbern** [comment]
@wiwei I posted a request for using screenshots / video on github

**Comment by julenka** [comment]
This is actually a bug with bounding box (scaling a slate is actually scaling a bounding box), not slate.

**Comment by julenka** [comment]
Reading this even more, it's actually an issue with the near tether.

**Comment by cre8ivepark** [comment]
@julenka Could you please check if this issue still needs to be fixed?

**Comment by julenka** [comment]
I would say yes, but not for GA. The shell has the same bug (the tether is not directly attached to the corner).  Removing GA blocker tag.

**Comment by julenka** [comment]
@thalbern I've forgotten a bit what the issue is and can't quite tell from the description. Could you perhaps post a video / screenshot? If not or if you don't remember, perhaps we can close the issue as "not repro" or "fixed" and re-open if we get enough info in the future?

**Comment by thalbern** [comment]
sry julia! i didn't see this until now - i haven't seen this issue for a long time. so closing this now
