### ISSUE TITLE
Input is not working reliably on NearTouchInteractables placed next to/ close to each other

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4215]
## Describe the bug
 
Interacting with a NearTouchInteractable won't work reliably if there's another NearTouchInteractable closeby. 

## To reproduce
 Place a pressable button next to a pannable view and observe that the edge of the button close to the pannable view can't be pressed anymore

## Expected behavior

Button and views should always work independent on what is next to them.

## Your Setup (please complete the following information)

- MRTK Version v2 RC1

## Target Platform (please complete the following information)

- HoloLens 2
- Unity Editor Hand Simulation / Articulated Hand

**Comment by MenelvagorMilsom** [comment]
Should be fixed by #4152
