### ISSUE TITLE
Add playmode tests to mrtk_pr and mrtk_ci

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4222]
Currently playmode tests don't run in CI/PR pipelines, which would be nice because we don't want to regress these tests going forward.

This PR tried do this but hit an issue unrelated:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4185

We'll need to fix the issue highlighted by that PR (i.e. making dictation/speech non-critical to MRTK startup)

**Comment by paco-ms** [comment]
@wiwei , @googlan is looking into this. Worth syncing with him to ensure there is no information loss or duplication. Thanks!

**Comment by googlan** [comment]
Thank you @paco-ms . I'm almost done. Most issues so far are from non-existent deinitialization in some of MRTK services and components. I'm fixing them one by one now.

**Comment by googlan** [comment]
Done with #4498.
