### ISSUE TITLE
Pointers should not be destroyed when source is lost

### ISSUE THREAD

**Issue by provencher** [microsoft/MixedRealityToolkit-Unity#4223]
## Describe the problem

Currently, pointers are destroyed and re-instantiated when their source is lost.
This has a number of side effects:

- It is not possible to cache them, since new ones take their place and the old ones go stale quickly.
- If attempting to cache a pointer, to detect that it has gone stale, it is imperative to first cast it to a monobehavior to then null check it using Unity's overridden null check. 

## Describe the solution you'd like

Pointers should be set inactive, perhaps with a tracking state change, but should not be destroyed. This will alleviate performance considerations as recreating pointers is no longer necessary, and when they return into view, the cached instances will not be stale.

**Comment by SimonDarksideJ** [comment]
Agreed. I the source is "Lost" then everything should be cleaned up as you cannot guarantee the state of the controller if it is discovered again.

If however, it needs to be retained, better to look at ways to hold the controller and not fire the source lost in those instances.

**Comment by Yoyozilla** [comment]
This is a performance issue where pointer is destroyed everytime when hand is not in view, and recreated when it comes back. 

@provencher  could we get performance profiling data on perf gain when not destroying pointers?

**Comment by provencher** [comment]
@Yoyozilla I don't think I should be assigned to solve this.
I'm personally not very familiar with how pointers are managed at a data provider level, especially in regards to WMR platforms which our apps don't support.

I haven't benchmarked how this performs, but I know from much experience with unity that instantiating a prefab can take a non-trivial amount of CPU time and block the Unity thread each time it's done.
By not destroying these pointers, we save that compute time. 

Right now, to get around losing access to the pointers and not being able to cache them, I have to iterate over the list of all pointers and do a series of checks, including string comparisons, which generates garbage, each frame that neither hand or controller has an active source.


@SimonDarksideJ I don't think you should clean up the pointer the moment the source is lost.

There can never be more than 2 hands, or 2 controllers at any given moment. With that said, while you cannot guarantee the state of the controller when it returns, you can easily query it before setting it active and exposing that state to the API user.

In regards to controllers, even if their source is lost, as in they're outside the field of view, they're still paired and provide acceleration and rotation information that can be useful.

As for hands, they come drop in and out constantly, and doing all these checks around finding active pointers in view can get expensive, without mentioning the impact of disposing and re-instantiating the prefab what could be several times per second depending on the user's hand movement.

**Comment by StephenHodgson** [comment]
> As for hands, they come drop in and out constantly

That's pretty much what we're saying. We shouldn't be calling source lost on these, but instead just update the tracking to reflect that the position is unknowable.

We should def have the input sources clean up the pointers when the source is lost. We just need to update the hands so that they don't raise source lost when they leave the camera view.

**Comment by provencher** [comment]
How you define losing source in that case? For controllers it could be disconnected, but for hands, I don't see any case in which they should be cleaned up.

**Comment by StephenHodgson** [comment]
Instead their tracking state will change from known to lost

**Comment by luis-valverde-ms** [comment]
I see two separate issues here:

1. I can't keep references to pointers because they get destroyed

What is the specific use case that requires you to keep the references? Would it be enough with keeping the pointer ID?

2. Re-creating pointers is expensive

Have you profiled a use case were this is an actual issue? Can you share that data with us?

I can see how @StephenHodgson suggestion would help with 2.

**Comment by provencher** [comment]
@luis-valverde-ms 
1. The use case is driving my UI from the far interaction pointer. 
I do this because I have my own UI system, and this is described at length here:
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/3957

Right now I cache the pointer, and I use the handedness or name to recover it after it gets set to null.
However, because it gets destroyed, I have to null check it, when a simple IsActive check would suffice.

The general unity optimization docs recommend against doing Monobehavior null checks every frame because they have an overridden behavior that incurs a non-trivial performance hit. To make matters worse in this case, I have to cast it before null checking it, because the overwritten behavior is not called by default since I have an interface reference, and not a monobehavior reference. (IMixedRealityPointer)
https://docs.unity3d.com/Manual/BestPracticeUnderstandingPerformanceInUnity7.html

2. I have not profiled the instantiation cost in this instance, but it can happen every few frames depending on how much your hands move in an out of view, and each time it's destroyed, garbage is created which means the GC needs to run and clean up after it. 

Frankly, I don't see why we would ever want to destroy any pointers at runtime. If the pointers are no longer tracked, we just disable them, and their update scripts will not run. They will have no performance overhead for existing in the scene, and then we can guarantee that their references will never be null.

In 99% of cases, if a controller is no longer tracked, it will almost certainly be tracked again shortly after. There are not that many pointers created, and they can all continue to exist for the duration of the application.

**Comment by luis-valverde-ms** [comment]
@provencher , I do think it would be better if pointers weren't destroyed. I was hoping to get a bit more solid data about the issues you've encountered (e.g. concrete timmings showing performance/increased GC) and the posible alternatives (e.g. caching pointer ID instead) to prioritize accordingly. As it stands, I think it is something we need to tackle but not top of the list.

**Comment by provencher** [comment]
@luis-valverde-ms  I could try gathering some data, but there are a lot of moving pieces involved in the creation of the pointers, so it's hard for me to quantify.

I understand that it's not at the top of the list, though in my opinon, the very fact that pointers can ever be null causes a number of issues across the MRTK as a whole. The issue I linked above #4270 has a number of null checks that make it harder to read and have non-negligible performance hits.

If there is a plan to make it impossible for pointers to be null, it should be done sooner rather than later, given the way it will affect MRTK code and code using it.

**Comment by luis-valverde-ms** [comment]
@provencher , understood.
