### ISSUE TITLE
Optimize Shader property and Material access on Interactable*Theme classe

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#4228]
## Describe the bug

Interactable and other MRTK components utilize the Theme profiles to modify scene assets based on some input such as Focus, click, etc. InteractableShaderTheme.cs will modify a provided shader property based on scene interaction but does so using the string property name. The class should utilize Shader.PropertyToID() from Unity to modify shader properties via their integer key, not their string names as this utility is much faster. 
https://docs.unity3d.com/ScriptReference/Shader.PropertyToID.html

InteractableMaterialTheme also seems to create a new material isntance by access renderer.material in Get & Set Value() functions. This breaks batching gains in Unity.

## To reproduce

Look at SetValue() of these two classes InteractableShaderTheme & InteractableMaterialTheme 

## Expected behavior

MRTK should utilize sharedMaterial property instead of material property so it does not break scene instancing and should utilize shader property changes via integer keys and not string keys which involve an extra layer of computation to lookup it's integer key

## Your Setup (please complete the following information)

- Unity Version 2018.3.13
- MRTK Version RC1-Refresh

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by wiwei** [comment]
@Troy-Ferrell, do you have any data/numbers on the impact of this?

**Comment by Troy-Ferrell** [comment]
No, I don't have any numbers. It depends on how regularly you call Shader.SetBlah as well as how many different shader properties there are in the project. The goal is to bypass the memory lookup of the int key for every call.

**Comment by Yoyozilla** [comment]
potentially affecting performance
