### ISSUE TITLE
GridObjectCollection should support undo

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#4231]
## Describe the bug

"Update collection" button on GridObjectCollection, etc should be undoable when it performs the transform changes. 
https://docs.unity3d.com/ScriptReference/Undo.html

Also, if the "Plane" type is default, the "Face Parent Forward" or "Face Parent Forward Reversed" 
should be default over "Face Origin"

## To reproduce

Assing GridObjectCollection to component. Run "Update..." and try to CNTRL-Z

## Expected behavior

Pressing CNTRL-Z should reset all the transforms back to their original state

## Your Setup (please complete the following information)

- Unity Version 2018.3.13f1
- MRTK Version RC1-Refresh

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Yoyozilla** [comment]
This is a new feature ask. 
Assigning to Yoon to investigate.
