### ISSUE TITLE
docfx generates "obj" cache folder and Unity then creates a meta file for it

### ISSUE THREAD

**Issue by ghost** [microsoft/MixedRealityToolkit-Unity#4237]
## Describe the bug

docfx creates a "obj" cache folder in Assets, next to the first folder by alphabet, which happens to be Assets\MixedRealityToolkit.Examples\Demos\Audio\Scripts. Unity then creates a meta file "obj.meta" which is included by git, while the obj folder is excluded via .gitignore.

## To reproduce

1. Run docfx: [https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/DevDocGuide.html](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/DevDocGuide.html)
2. Assets\MixedRealityToolkit.Examples\Demos\Audio\Scripts\obj is created
3. Start Unity
4. Assets\MixedRealityToolkit.Examples\Demos\Audio\Scripts\obj.meta is created and show up in git status as a new file.

## Expected behavior

Ideally the obj cache folder should not be created inside Assets (fix docfx invocation). Alternatively add [Oo]bj.meta to the .gitignore list.

**Comment by wiwei** [comment]
Oddly enough, while I can repro the fact that the obj folder gets created, I don't see the obj.meta (or any of those files) showing up on git status as a new file.

**Comment by wiwei** [comment]
Oh duh, actually this is happening to me as well. Scratch my previous comment.
