### ISSUE TITLE
InteractableStates - "Focus"-state not working properly with HL1

### ISSUE THREAD

**Issue by KarlSupertramp** [microsoft/MixedRealityToolkit-Unity#4238]
## Describe the bug
I'm using the DefaultInteractableStates for my Interactable objects. Everything works fine in the editor. The elements change color and offset when being focused and change back when focus is lost. Now it's basicly working on the HoloLens 1. The only problem is, when the HL1 recognizes a "pinch"-gesture (when I hold up my hand ready to click), the "focus-lost"-event is not executed. My buttons only lose the highlight when I hover over them without holding up a hand.

## To reproduce
Use the DefaultInteractableStates on a custom button with HoloLens1

## Expected behavior
Toggle highlight on focus every time, no matter what device.

## Your Setup (please complete the following information)

- Unity Version 2018.3.12f1
- MRTK Version v2.0

## Target Platform (please complete the following information)
- HoloLens 1

**Comment by wiwei** [comment]
@hdaUwe, just to check, is this when you've deployed to HL1, or using holographic remoting?

**Comment by hdaUwe** [comment]
> 
> 
> @hdaUwe, just to check, is this when you've deployed to HL1, or using holographic remoting?

I deployed it on HL1

**Comment by SimMue** [comment]
Same problem here.
I've got multiple game object with children, which have to change color when gazing at them. In editor everything looks well, but in hololens 1, the focus state isn't triggered as expected.
This behaviour occurs on holographic emulation as well as on the hololens itself.

**Comment by SimMue** [comment]
As @hdaUwe suggested, I checkout the current development branch and there the issue seems to be fixed.

**Comment by radicalad** [comment]
Confirming `Interactable` using default 'InteractableStates' works as expected on HL1 using `mrtk_development`. This includes focus state handling with a hand both inside and outside of the device FOV with the ready gesture.

Feel free to open a new issue if you're still having issues. Thanks!
