### ISSUE TITLE
Remove SupportedControllerEnum

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#4239]
## Describe the problem

This enum has a fixed number of controllers. Any new device (Oculus Go) needs to define its own controller there. increasing the list of controllers is crucial when you want to add more controllers.

## Describe the solution you'd like

Like #4239, the enum should be replaced with classes instead. A lot of the code is converting between enum and actual class type already, so why not just go with classes altogether?

## Describe alternatives you've considered

None considered, seems the best option.

**Comment by Railboy** [comment]
@Alexees I think you meant to link to #4235 

Really like this proposal as well.

**Comment by keveleigh** [comment]
#9106 made it in as a first step in this direction for 2.6, adding the concept of "controller definitions" to eventually replace this enum.

A reworked profile using these definitions and deprecation of this enum will come in a future release.

**Comment by davidkline-ms** [comment]
Excellent news! MRTK3 no longer uses a SupportedControllerEnum! We are using Unity's input system and supporting a new controller is effectively automatic.
