### ISSUE TITLE
Eye tracking support with external camera

### ISSUE THREAD

**Issue by DominicBoettger** [microsoft/MixedRealityToolkit-Unity#4241]
## Describe the problem

The eye tracking needs to be simulated via different key presses.

## Describe the solution you'd like

It would be great to be able to add an external camera to simulate the eye tracking in unity.

**Comment by wiwei** [comment]
@DominicBoettger, do you have any other details on what you'd like to see here? i.e. is this external camera like a real image-camera (which we then maybe do some sort of ML/stuff to figure out what you're looking at on screen?) Or is this a request for maybe some 6dof controller toggle that will enable some "eye gaze pointer thing?"

**Comment by DominicBoettger** [comment]
@wiwei I think it's not needed to have a special ML stuff. It would be sufficient to use eye tracking hardware like TOBII eye tracker or something similar.

**Comment by Zee2** [comment]
Closing as stale.
