### ISSUE TITLE
ability to search MRTK settings?

### ISSUE THREAD

**Issue by ForrestTrepte** [microsoft/MixedRealityToolkit-Unity#4243]
## Describe the problem

There are a lot of settings in the MRTK in a deeply-nested hierarchy.
A customer mentioned to me that he would like to have the ability to search for settings.

## Describe the solution you'd like

I'm picturing this as a text entry box that can be used as a free-text search of MRTK settings.

## Describe alternatives you've considered

I'm picturing that this would find settings as you type and then when you click one of the settings that has been found it would expand the tree to that setting and ping the setting it in the inspector.

For example, in Windows Control Panel you can type "mouse" in the search box and find all settings related to mouse. Or in Chrome's settings you can type in a search box and (while you are typing) it automatically filters the settings to those containing the text that you type.

A solution should include partial matches so that you can find words or parts of words inside a longer setting. Perhaps should search tooltips or have the ability to add keywords as well. Visual Studio does a really great job of this when you hit Ctrl + comma.

## Additional context

This is tangentially related to #3545 and #4242, and the solutions to those issues could impact how a search feature could potentially work or perhaps make a search feature less necessary.

**Comment by wiwei** [comment]
One note is that the inspector/profile system is already fairly complex, and adding things like search-ability would make things more usable but still not fix the true underlying issue (which is that profiles are super hard to understand as a new user).

If we had better and actually comprehensive settings listed in our docs, would that help, or is the customer in this case interested in staying purely within Unity as they're doing their work?

My hesistation here is that, if we truly believed that this profile/inspector world that we're living in is the 100% right thing to do going forward (I don't believe this is the case, given the feedback we've heard from every customer that this is confusing), then this would make sense to invest in - however given that we know we want to change this (though admittedly haven't settled on how), it's a little difficult to justify doing what we believe will actually be throwaway work.

That being said, we haven't decided either way on how configuration will change/stay the same going forward - if in the future we want to double down on profile/inspector stuff then this is a great thing for us to do.

**Comment by ForrestTrepte** [comment]
In this case, the customer was overwhelmed with the amount of settings and the amount of expanding required to browse for them. He says documentation may be helpful, but he really wanted to do this within Unity. The example he gives is in Visual Studio you use the Quick Launch (Ctrl + Q) box to search for settings.

If this were done via documentation then all the settings would have to be in one page (to make them easily searchable). And then you'd have to switch from Unity to that page, come back to Unity, and then find the setting in the hierarchy.

**Comment by ForrestTrepte** [comment]
I agree with this concern about complexity and that we should sort out the underlying profile usability issues before adding searchability on top.

Afterwards, there may still be a lot of settings so a search feature may be useful. Or perhaps it will feel unnecessary at that point.

**Comment by StephenHodgson** [comment]
The original plan was to have the configuration profile in the editor's preferences window (which itself is searchable) but that got sidelined at some point I think.
