### ISSUE TITLE
Assertion failed on expression: ValidTRS()

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#4247]
## Describe the bug
The contents of the display are clear while unity editor remote connected HoloLens 1，but
 then the contents of the display are very vague;
Assertion failed on expression: 'ValidTRS()';
## To reproduce

1.unity editor remote connect to Hololens 1 and open SpatialAwarenessMeshDemo scene;
2. Click on play button in unity editor;
3. show SpatialMeshs (wire frame grid);
4. See errosr; 

## Screenshots
 
![image](https://user-images.githubusercontent.com/38685433/57427290-e1f18800-7255-11e9-9a7a-f030efe92497.png)

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.12f1]
- MRTK Version [e.g. v2.0.0 RC1 Refresh and v2.0.0 RC1 ]

## Target Platform (please complete the following information)

- HoloLens 1

**Comment by keveleigh** [comment]
Took a look at this and was unable to repro with Unity 2018.4.16 and mrtk_development. May have been fixed by now.
