### ISSUE TITLE
NearInteractionTouchable gets touch up when finger goes more than 20cm behind front surface

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4252]
## Describe the bug

NearInteractionTouchables will always get a TouchUp or PointerUp event when a finger goes more than 5 cm behind a surface, even if a collidable is actually much larger.

## To reproduce
1. Import the following .unitypackage into mrtk_development latest
[repro.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3163242/repro.zip)
2. Open repro scene and hit play.
3. Move finger forward into the collider and watch the cube and output window (it will output time of touch down / up events, as well as change cube color)

## Expected behavior

I should only get a touch up event when I leave the back of the collider

## Actual behavior

I get a touch up event as soon as I'm 0.2m away from front of collider, even though my collider is huge. 

## Screenshots

![image](https://user-images.githubusercontent.com/168492/57473109-f3ca2f80-7243-11e9-91d4-380732229213.png)

## Your Setup (please complete the following information)

- Unity Version 2018.3.9f1
- MRTK Version mrtk_development

**Comment by MenelvagorMilsom** [comment]
@thalbern, I don't have much on my plate at the moment. Do you mind if I grab this one?

**Comment by Yoyozilla** [comment]
closing since the related PR seems to be merged

**Comment by Yoyozilla** [comment]
@julenka  please reopen if you think this issue is not fixed
