### ISSUE TITLE
Add a Solver Tracked Object option for the tip of a pointer

### ISSUE THREAD

**Issue by Ecnassianer** [microsoft/MixedRealityToolkit-Unity#4255]
## Describe the problem

I'd like to position an object at the tip of a pointer that I'm using on an articulated hand. It would be nice if I could just pick this like I pick a controller point.

## Describe the solution you'd like

Tracked Object To Reference could be set to "Right Pointer", "Left Pointer", or "Gaze Pointer".

**Comment by danielescudero** [comment]
Since headgaze is not the only option anymore it makes sense for solvers to follow not only hands but pointers.

**Comment by julenka** [comment]
Fixed by #6280
