### ISSUE TITLE
Can't see hand mesh when simulated in editor

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4257]
Set hand visualization in Hand Tracking Profile to just be the mesh (make all joints null).
Simulate hands in editor using mouse + keyboard
Expected: I see the mesh, or at least some hand joint visualization so that I cdan see what my simulated hand is doing

Actual: I see nothing.

From Lukas:
Julia, isn't the hand mesh provided entirely through the Mirage API?

Only WindowsMixedRealityController raises the HandMeshUpdated event, using data obtained from SpatialInteractionSourceState through the handMeshObserver. The "hand" mesh prefab appears to be just a cube, with actual geometry generated at runtime from vertex buffers. So we couldn't use it directly for simulating the hand.

I've been playing with the idea of getting an actual rigged hand model working, with a SkinnedMeshRenderer and regular bone objects. This could work both for simulating a human hand in AR as well as VR hands in various shapes and sizes.

The tricky part here is getting the deformation bones to line up properly with the joints as reported by the input system, especially when considering that different devices may use different joint models. When directly attaching deformation bones to the joint objects it leads to stretching and/or gaps because the rest pose doesn't match.

Also the orientation of joint objects in the BaseHandVisualizer is computed with -Z=forward, which doesn't match what DCC tools do (Blender uses Y for bone direction, Maya/Max use X). So the most robust solution for transferring tracked or simulated joints onto the hand model would probably be a set of LookAt constraints on the bones to make them follow joints, rather than copying transforms directly.

From Julia:
I was thinking what you were saying -- a rigged hand mesh. You're right that the mesh is provided by the Mirage API. I actually don't think we even need this for ship necessarily so I moved it back to P3. It's really a nice to have.

**Comment by chbecker-ms** [comment]
Ported from internal database.

**Comment by wiwei** [comment]
Nice to have, would tag with "Help Wanted" but I think it's a fairly significant chunk of work (@lukastoenneMS correct me if I'm wrong here)

**Comment by julenka** [comment]
I'm going to close this for now since nobody has asked for it.

**Comment by polar-kev** [comment]
Closing since there is now a rigged hand visualizer in v2 that meets this need.
