### ISSUE TITLE
UnityTouchController controller should be Handedness.None

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4260]
Note: There is some special-case handling in BaseDeviceManager.RequestPointers for Handedness.Any which should be looked into.

[MixedRealityController(
    SupportedControllerType.TouchScreen,
    new[] { Handedness.Any })] // should be None as Any is a combination of Handedness.Left | Right | Other
public class UnityTouchController : BaseController
{
...
}

**Comment by chbecker-ms** [comment]
Comment from Daniel:

This is not actually a bug and does not cause any problems, and should be done for consistency reasons. Sometimes we use Handedness.Any and sometimes we use Handedness.None if there is no designated handedness for a controller per se.

**Comment by chbecker-ms** [comment]
Ported from internal database.

**Comment by wiwei** [comment]
Seems like a good candidate for anyone to jump in and help out.
