### ISSUE TITLE
Buttons do not activate on release if frame rate is low.

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4266]
This is a bug in response to experience with OOBE.

To repro, after pressing a button, move your hand out very quickly.

Alternately, force a very low framerate on your app (e.g. 30 fps).

The button will only fire a release when you were still touching, but crossed back above the press plane. 

So, if the following sequence happens:

button press
touch up + cross press plane
Then the event would never fire. The sequence that the current buttons expect are:

button press
cross the press plane
touch up

**Comment by chbecker-ms** [comment]
Ported from internal database

**Comment by wiwei** [comment]
If anyone has a scenario in which this affects non-low perf cases, would be good to have data here.
