### ISSUE TITLE
[HTK] HoloToolkit's Selection Gestures Broken on HL2. Works fine on HL1

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4267]
Tap gestures seem to be behaving differently on HoloLens 2 devices, than on HoloLens 1 devices.  This is causing apps built with older MR toolkits to not work correctly on HoloLens 2. Apps built with older toolkits, should still work on HoloLens 2. 

Sample App Repro

1) Open attached Unity Project  (used Unity version 2018.1.9f2, and HoloToolkit version 2017.4.0.0).  (note versions selected based on pattern app versions)

2) Build Unity App
3) Deploy on HL1. Select Sphere.  Sphere changes color
4) Deploy on HL2. Select Sphere.

RESULT
Cursor jumps off sphere, and sphere doesn't change color

EXPECTED
Cursor to stay on sphere, and sphere to change color

**Comment by chbecker-ms** [comment]
Ported from internal database.

**Comment by wiwei** [comment]
I believe this ask is around the old HTK - we're primarily focused on V2 right now.
