### ISSUE TITLE
Turning off "Enable Hand Joint Visualization" turns off hand input in Editor

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#4268]
## Describe the bug

In the MRTK configuration, under input, under Hand Tracking settings, unchecking "Enable Hand Joint Visualization" hides the hand joints in play mode but also disables hand joint input. 

## To reproduce

Example => Open "HandInteractionPanZoom" example scene
Turn off "Enable Hand Joint Visualization" in MRTK configuration inspector
Try to pan on the slates, nothing happens
Turn back on setting
Try to pan on the slates, you now have control

## Expected behavior

This property should only control the "visualization" of the hand joints, not also the input events.

## Your Setup (please complete the following information)

- Unity Version 2018.3.13f1
- MRTK Version (latest MRTK_Development ~5/10/19)

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by BarboraAtVResearch** [comment]
Hi, it is now 2021 and sadly, the above-described behavior still remains for my Oculus Quest project using MRTK 2.7.2.0 . Is there any workaround, or anything I can do to see hands without the cubes?

**Comment by ChauNTran** [comment]
> Hi, it is now 2021 and sadly, the above-described behavior still remains for my Oculus Quest project using MRTK 2.7.2.0 . Is there any workaround, or anything I can do to see hands without the cubes?
you could clone the hand tracking profile and clear the references of those joints. That way the cubes won't get instantiated.
![shot](https://user-images.githubusercontent.com/18691055/140192375-0186ec42-a8fc-4f21-96fe-64fd075e7202.JPG)
