### ISSUE TITLE
PressableButtonExample needs polish or removal

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4269]
Open PressableButtonExample scene and play in editor.
Look at Click Indicator cube and click mouse button or press gamepad button.
Observe no color cycling.
The buttons to the left look a bit wonky too and the scene lacks a description panel. We need to freshen this scene up or remove it from examples.

![untitled](https://user-images.githubusercontent.com/42761412/57544169-681bd600-730b-11e9-985b-3df550033beb.png)

**Comment by chbecker-ms** [comment]
Ported from internal database.

**Comment by wiwei** [comment]
It looked really bad before, but it's better than it was when this bug was filed.

**Comment by cre8ivepark** [comment]
We can delete this scene since everything here is already in HandInteractionExamples scene.

**Comment by keveleigh** [comment]
Closed via removal in #4523

**Comment by julenka** [comment]
Hm...actually bernadette and I found that scene useful for testing different configurations. Without that scene there's not great way to test different button sizes, etc. I would argue for bringing it back as a PressableButtonTest scene.

**Comment by julenka** [comment]
Thinking on it a bit more, while it's useful to have pressable button examples as separate scene, maybe the current form of the scene is not appropriate. Closing for now, we will open a separate issue if we feel need to have second pressable button scene to show different configurations.

**Comment by julenka** [comment]
Fixed in #4527
