### ISSUE TITLE
MRTK defaults to teleport and boundary services on for HoloLens developers

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4271]
## Describe the bug

MRTK V2 profiles default to teleport and boundary services even when intent is to create a HoloLens 2 application

## To reproduce

1. Install latest MRTK build
2. Notice Teleport and boundary are defaulted to on

## Expected behavior

A way to express my intent of building an AR app and getting great defaults tuned for those app types.

## Your Setup (please complete the following information)

- Unity Version - 2018.3.11f1
- MRTK Version - RC1 Refresh

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
Tracking this in this issue:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4351
