### ISSUE TITLE
Update collection on a Grid object in a prefab does not save changes.

### ISSUE THREAD

**Issue by thejawson** [microsoft/MixedRealityToolkit-Unity#4272]
## Describe the bug

I click Update Collection on a Grid Object that is in a prefab. Leave the prefab and the changes are not saved. Looks like a dirty flag is not getting set when update collection is called.

## To reproduce

1. Create a Grid object in a prefab
2. Add a collection of objects. I used pressable buttons.
3. Click update collection
4. Delete an object from the middle of the collection
5. Leave the prefab
6. Open the prefab 
7. Click update collection.
8. Leave and come back into prefab. The locations are reset.

## Expected behavior

Prefab should be updated

## Your Setup (please complete the following information)

- Unity Version 2018.3.13f1
- MRTK v2.0

## Target Platform (please complete the following information)

Happens in Unity

**Comment by Railboy** [comment]
I'm going to say this is related to #4231 since adding undo support will automatically dirty the object.

**Comment by Troy-Ferrell** [comment]
PR out: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4317

Also, if children object transforms are modified in scene level, they will overwrite any changes made at prefab level of course. But so far working for me as expected with above change
