### ISSUE TITLE
Manipulation Gesture is not triggering when expected, only triggers at the same time as the Navigation gesture

### ISSUE THREAD

**Issue by Kjakubzak** [microsoft/MixedRealityToolkit-Unity#4274]
## Describe the bug

We realized recently that Gestures are no longer working properly for our app; the Manipulate Gesture and Navigation gestures seem to be going off at the same time and the expected behavior of "tap to start Manipulate" is no longer working. Now, tapping and then moving your hand while holding the tap seems to trigger both Navigation and Manipulation.  

Making sure that this wasn't a project-specific bug, I then repro'd with the MRTK HandInteractionGesturesExample scene. GIF attached. 

## To reproduce

1. Create a bare sample project and bring the latest source into it (as well as the examples).
2. Open the example scene, HandInteractionGesturesExample. 
3. Set the input simulation profile to use the Gesture simulated hand rather than the articulated simulated hand
4. Try to manipulate the object in the example scene; it only triggers the manipulate orb when you begin to navigate (and they do so at the same time).

## Expected behavior

The Manipulate gesture starts when the simulated gesture hand taps, rather than when moving.

## Screenshots

![gif](https://i.imgur.com/M0PHSIS.gif)

## Your Setup (please complete the following information)

- Unity Version 2018.3.10f1
- MRTK Version 2.0.0-20190506.1 and 2.0.0-20190510.2

## Target Platform (please complete the following information)

- HoloLens/HoloLens 2

**Comment by wiwei** [comment]
@Kjakubzak just to check, is this primarily happening with input simulation, or also something that happens on a real device? The way input simulation and input works is slightly different.

**Comment by Yoyozilla** [comment]
We should validate our new gesture system

**Comment by Yoyozilla** [comment]
@ritijain could you please follow up on urgency

**Comment by lukastoenneMS** [comment]
So just to be absolutely clear, we basically expect these two cases and order of events:

"Hold":
1. Gaze focus on object (nothing happens yet)
1. Start tap:
  - Hold gesture **started**
  - Manipulation gesture **started** [NEW]
1. Release tap:
  - Hold gesture **completed**
  - Manipulation gesture **canceled** (or should it be **completed** here?)

"Move":
1. Gaze focus on object (nothing happens yet)
1. Start tap:
  - Hold gesture **started**
  - Manipulation gesture **started** [NEW]
1. Move hand:
  - Hold gesture **canceled**
  - Navigation gesture **started**
1. Release tap:
  - Manipulation gesture **completed**
  - Navigation gesture **completed**

Please let me know if there is something else, otherwise i will implement it like that.

**Comment by Kjakubzak** [comment]
Hi Lukas,

In general, that seems like it would be the expected order of events. That being said, I initially thought for release tap during the "Hold" scenario it would also trigger manipulate completed rather than cancel, but I can see why it'd be cancel now that the two scenarios are laid out. 

My only concern is that for gestures there's no 1:1 for tap start/end; but since that can be accomplished through pointer down/up/click, it's not really that much of an issue.

**Comment by naostranMS** [comment]
@lukastoenneMS @Kjakubzak 

Sorry I only just caught this - I think the way that it worked initially was a much better approximation of how HL1 works (I'm not sure about HL2 - but unless they changed what "manipulate" means, I don't see how it could be substantially different). The manipulate action is not fired by the gesture recognizer until the hand has moved some distance away from the input down position. We handled that on Layout pretty much how Ken mentioned in his last update - store initial info in response to input down, then start dragging when manipulation started fires (or do nothing if we get input up before manipulation start).

**Comment by lukastoenneMS** [comment]
@naostranMS Hmm ... yeah, i don't know what the exact behavior on HL1 is, i'll take your word for it 😉 

I will reopen this and make another PR to revert this (but keep documentation etc.) I would like to try and write tests for this too, so that at least we state explicitly how it's supposed to work.

**Comment by lukastoenneMS** [comment]
Oh, i've just seen that the change is already being reverted in #5051, that should fix it.

**Comment by Kjakubzak** [comment]
@lukastoenneMS @naostranMS 

I'm okay with this revert since we're now using the select gesture for airtapping; but I have some questions. 

If we're reverting it back; doesn't it just make Manipulation and Navigation functionally the same (they have the same triggers, and the only difference is that they're separated and navigation has slightly more functionality)? 

If they're that close in functionality, shouldn't they be condensed into the same thing? I must be missing something; so additional context would be great.

**Comment by lukastoenneMS** [comment]
Yes, the manipulation and navigation events are active at the same time. The main difference is that the navigation vector is clamped to a -1..1 cube around the starting point, and the axes can be constrained (although i'm not sure this feature is working right now).

**Comment by Kjakubzak** [comment]
Ah, okay. So I was thinking that Navigation should really be a specific type of manipulation (settable like with navigation's axis constraint), but I realized just now that it would probably cause more problems with consumers of MRTK than anything else since they're expecting the same pattern (them being separate) that we've had for years.

Disregard my last comment. Thanks for clarifying this @naostranMS

**Comment by naostranMS** [comment]
It's not just a matter of maintaining compatibility with older HTK/MRTK (though that is helpful also), it's that it needs to work more or less the same in editor (input sim) as on device(s) (e.g. WMRDeviceManager for HL1/WMR VR) - i.e. changing input sim without changing the real platform versions just means that input sim is less accurate

**Comment by Kjakubzak** [comment]
> It's not just a matter of maintaining compatibility with older HTK/MRTK (though that is helpful also), it's that it needs to work more or less the same in editor (input sim) as on device(s) (e.g. WMRDeviceManager for HL1/WMR VR) - i.e. changing input sim without changing the real platform versions just means that input sim is less accurate

I didn't realize that the fix was only for input simulation. This was a big mistake on my part.
