### ISSUE TITLE
Spatial mapping visualization doesn't work with non-identity playspace transform

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4276]
Easiest repro:

1) Enable MRTK spatial mapping visualization (on by default in default MRTK profile)
2) Add 1 meter offset on Y in MixedRealityPlayspace position
3) Deploy and run on HL

Note that all the spatial mapping wireframes are one meter low.

This is significant in any situation where it is desired to effectively apply a transform to the camera. This includes situations such as teleport, camera fly mode, and grabbing the entire contents of the world and manipulating them as a unit.

**Comment by chbecker-ms** [comment]
Comment from David:

This is likely due to the parenting of the meshes... I will investigate.

**Comment by chbecker-ms** [comment]
Ported from internal database

**Comment by fast-slow-still** [comment]
I have had to address this in other work. @davidkline-ms  I would be happy to help save some time for you here, either working up a fix or pointing out failure point. Just let me know how I can best assist.

**Comment by wiwei** [comment]
@fast-slow-still if you have cycles to look at this, this would be great.

I don't believe that @davidkline-ms is actively investigating this right now.
