### ISSUE TITLE
MRTK: spatial mesh spams warning messages

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4277]
(Ported to GitHub)

MRTK: spatial mesh spams warning messages

[Warning]OnDataReady reported no data written for mesh id 1974
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.Core.Devices.SpatialAwareness.WindowsMixedRealitySpatialObserver:SurfaceObserver_OnDataReady(SurfaceData, Boolean, Single)
UnityEngine.XR.WSA.SurfaceDataReadyDelegate:Invoke(SurfaceData, Boolean, Single)
UnityEngine.XR.WSA.SurfaceObserver:InvokeSurfaceDataReadyEvent(SurfaceDataReadyDelegate, Int32, MeshFilter, WorldAnchor, MeshCollider, Single, Boolean, Boolean, Single)

**Comment by chbecker-ms** [comment]
Comments from David:

Compare messaging with HTK's implementation.  Should we consider retrying or just try again the next time the observer notices a change (current behavior).

This indicates that Unity did not update the object in OnDataReady. Not an issue to remove the warning,. Is more of a debugging message for the system developer than for application developers.

**Comment by davidkline-ms** [comment]
fixed with #5520
