### ISSUE TITLE
Don't dispatch touch events for a hand that is already grabbing something and vice versa

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4279]
(Ported to GitHub, reference 19739652)

If a hand H1 is grabbing and moving an object O1, then touchable objects should not receive touch events from H1 until H1 has released O1.

For example: if I am moving something that has a touchable surface/button, I should not be accidentally pressing that button while moving.

### To reproduce

Import the unity package below, and then grab the cube, and move finger to touch the sphere.

[touchgrab_repro.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3192273/touchgrab_repro.zip)

Expected behavior is that while hand is grabbing, the sphere should not get touch events (change color)

![GrabTouchConflict](https://user-images.githubusercontent.com/168492/57942192-b558f400-7885-11e9-93c7-6fd7ec218c23.gif)

**Comment by wiwei** [comment]
@julenka can you add some more details on what the request/bug is here? The last mention I've seen here is around the mediator handling this.

**Comment by julenka** [comment]
Fixed by #4645
