### ISSUE TITLE
Coffee cup can get lost in playground app

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4280]
(Ported to GitHub, reference 21172526)

From Sophie:

First, the scene is great! Love it! However, if I drop an item, it’s lost! For example, I grabbed a coffee cup and accidentally opened my hand and it fell into the abyss. Would be nice to either have a respawn layer so that if they fell low enough they would just rematerialize at their original position (or spawn point). And/or have a button to restart the scene from fresh. Currently the only option is to close the app and restart it again.

**Comment by wiwei** [comment]
@cre8ivepark do you guys have any "reset scene" affordances that you will put into a scene but rip out prior to checking things in?

**Comment by wiwei** [comment]
@julenka as well (see question for @cre8ivepark)

**Comment by julenka** [comment]
I don't have one that I've used in MRTK, though I did have this in my old prototypes. I guess this should not be part of core MRTK but part of examples, or maybe part of MRTK.SDK.

**Comment by julenka** [comment]
Here is the script I used in my old prototypes to move the scene in front of the user and reset the world:
[MoveHereAndResetWorld.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3183227/MoveHereAndResetWorld.zip)
