### ISSUE TITLE
Remove velocity tracking from ManipulationHandler

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4281]
(Ported to GitHub, reference 21400301)

In follow up to comment on this PR https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/4118:

> Not to sound self-referential but this PR fixes the issue it fixes, i.e.: #4117. I agree ManipulationHandler could do with a general review (e.g. use of controller velocities) but in the meantime fixing those null references does no harm and help us with upcoming changes to gaze pointer.

I agree that using velocities in ManipulationHandler is something we can remove. This is to support a specific behavior of throwing things, which I think is a great idea to have as a separate component, but doesn't seem critical for manipulation.

Creating a bug to track removing tracking of velocity from ManipulationHandler

Related issue: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4210

**Comment by wiwei** [comment]
@julenka is this purely "remove anything that has to do with velocity" or is this "refactor velocity into its own class?"

See this comment for reference
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4118#issuecomment-487824639

**Comment by vaoliva** [comment]
Non Fix Issue as it fix would be a breaking change.

**Comment by vaoliva** [comment]
Non fix issue as fix would be a unnecessary breaking change.
