### ISSUE TITLE
Near tether line style does not match the HoloLens shell

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4282]
(Ported to GitHub, reference 21020620)

The tether in the shell is a dotted line, however in MRTK it is a solid line.

Tether in shell:
![untitled](https://user-images.githubusercontent.com/42761412/57559020-d9bc4a00-7334-11e9-955b-38a025bc6faf.png)

Tether in MRTK:
![untitled2](https://user-images.githubusercontent.com/42761412/57559049-e771cf80-7334-11e9-84d4-f08b881171ca.png)

**Comment by cre8ivepark** [comment]
Resolved by #4526 
Merged for RC2 release.
