### ISSUE TITLE
Unity UI interaction toggle button doesn't work on playground

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4284]
(Ported to GitHub, reference 21070689)

No further description. Let's double check that this works as expected with Daniels latest change to support hand interaction with Unity UI.

**Comment by wiwei** [comment]
There's not a lot of information in this issue, so I'm closing this out. I've messaged the original customer who reported this and have advised to reopen this with more details if this is still a problem.
