### ISSUE TITLE
Diagnostic panel should indicate the 8 ms per GPU frame thermal/power limit in addition to the 16 ms 60fps limit

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4286]
(Ported to GitHub, reference 21300666)

There will be power/thermal guidance for how long per frame an app should be using the GPU, but it's not decided yet. Tentatively it's no more than 8 ms per GPU frame, and that's what we're using for internal apps.

We should upgrade the diagnostics panel to show red above 16 ms per GPU frame, yellow above 8 ms GPU frame, and green below 8 ms GPU frame. We can tweak the actual guidance once we have a final number.

**Comment by chbecker-ms** [comment]
We need to decide on the future of the diagnostic panel.

HoloLens 2 will support a low overhead FPS counter. The more complex we make this panel, the more GPU we are using.

It does provide great value on non-HL platforms where a counter may not be available.

**Comment by wiwei** [comment]
I think that this also was originally called out to help with some HoloLens 2 specific things (around thermal/power) - not sure how generally useful this actually is. 

I'm going to close this out - if we can show some value that accrues to VR and AR maybe we would take this.
