### ISSUE TITLE
Exception raised in call to InteractionManager.GetCurrentReading() : "Assertion failed on expression: 'index < size()'"

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4287]
(Ported from GitHub, reference 21323136)

It happens when starting a MRTK app on a HoloLens 2 device. This is the exception reported:

```
Assertion failed on expression: 'index < size()'
UnityEngine.XR.WSA.Input.InteractionManager:GetCurrentReading_Internal(InteractionSourceState[])​
UnityEngine.XR.WSA.Input.InteractionManager:GetCurrentReading(InteractionSourceState[])​
Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityDeviceManager:Enable()​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(Type, IMixedRealityService)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(T)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterService(Type, SupportedPlatforms, Object[])​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterDataProvider(Type, SupportedPlatforms, Object[])​
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Enable()​
Microsoft.MixedReality.Toolkit.<>c:<EnableAllServices>b__63_0(IMixedRealityService)​
System.Action`1:Invoke(T)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServices(Action`1)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:EnableAllServices()​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:OnEnable()​

```​

MRTK version: custom built packages using commit 59a2ffca36c53a2a4cc6d5fcc68c381d3224d759
Windows SDK version: 10.0.18362.1
Unity Version: 2018.3.7f1

**Comment by chbecker-ms** [comment]
Comment from Luis:

Link to similar looking issue, no resolution: https://forum.unity.com/threads/assertion-failed-on-expression-index-m_size.490584/

**Comment by chbecker-ms** [comment]
Comment from Kurtis:

I started seeing this for the first time yesterday as well. I believe it was caused by our change to passing in a preallocated array to the InteractionManager call.
I started investigating a little bit on the Unity-side, but haven't found anything yet.
I'll file a Unity bug as well, to get it on their radar (since it looks like the forum reporter never filed one).

**Comment by luis-valverde-ms** [comment]
There doesn't seem to be anything wrong here on our side. @keveleigh , do you mind following up with Unity?

**Comment by chrisfromwork** [comment]
Adding Urgency-Now this seems to break all vr uwp builds. I guess building for release is a work around, but this feels urgent to fix now.

**Comment by wiwei** [comment]
@Railboy

**Comment by Railboy** [comment]
>I believe it was caused by our change to passing in a preallocated array to the InteractionManager call.

That would have been #3946

If that's the problem we can roll back the change with one line in WindowsMixedRealityDeviceManager.cs:
`interactionmanagerStates = InteractionManager.GetCurrentReading();`

Can someone try that and report back? My device is out for repairs.

**Comment by keveleigh** [comment]
@Railboy Yeah, that's the problem. There's a bug in Unity's implementation when no controllers are attached. I'm working on it with them.

**Comment by wiwei** [comment]
Should call out, this is a Debug-build specific issue.

**Comment by wiwei** [comment]
I'm working on this fix.

**Comment by ei2kpi-ptc** [comment]
FYI, I hit this when I deployed the PressableButton scene onto a HL1 as well (Just in case someone else searches for it)
