### ISSUE TITLE
Far beams start where the original head position was

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4290]
(Ported to GitHub, reference 21098803)

When hands begin tracking, the far beam starts out originating from the original head position where the user starts the app (both in editor and on device) for a frame before correctly positioning based on the hand.

**Comment by chbecker-ms** [comment]
Comment from Luis:

Looks like this could be another instance of: https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3612

**Comment by wiwei** [comment]
Looks like a dupe, resolving. We can reopen if this is not the case.
