### ISSUE TITLE
Service Inspector dropdown in scene turns off after I play and then stop in editor

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4293]
## Overview
Playing and then stopping a gaame in editor turns off the service inspector dropdown.

## Steps to reproduce
In MRTK profile, check "use service inspectors"
![image](https://user-images.githubusercontent.com/168492/57565903-95ec3380-737a-11e9-8970-77db3a89bd87.png)

Notice that MRTK game object now has dropdown:
![image](https://user-images.githubusercontent.com/168492/57565911-a43a4f80-737a-11e9-94bb-dcb3f203a905.png)

Play scene, then stop playing

Notice that MRTK game object no longer has dropdown:
![image](https://user-images.githubusercontent.com/168492/57565920-b5835c00-737a-11e9-9492-1741efa9698f.png)

## Unity Editor Version
2018.3.9f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by wiwei** [comment]
I think this was called out in the initial PR review as well, the workaround I believe is to re-toggle the service inspectors checkbox.

**Comment by Railboy** [comment]
This is (mostly) fixed in #4384. Once you select the MixedRealityToolkit instance, they will appear again without having to toggle the checkbox.
