### ISSUE TITLE
[ManipulationHandler] Cheese rotates on grab

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4294]
(Ported to GitHub, reference 20940836)

In the HandInteractionExamples scene, cheese rotates on grab. 

![MRTK_Manip_Click2](https://user-images.githubusercontent.com/13754172/57643230-250d6d00-756e-11e9-9763-987a61bde83a.gif)

**Comment by cre8ivepark** [comment]
For any object with ManipulationHandler, there is a very subtle movement on each click. I suspect this is because there is a small movement of the simulated fingertip when the mouse is clicked?  
@julenka @thalbern

**Comment by cre8ivepark** [comment]
Closing this issue since it is caused by the simulated hand's subtle movement on click.
