### ISSUE TITLE
Rotations marked as 'maintain rotation to user" rotate as I roll my head.

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4295]
(Ported to GitHub, reference 20941268)

**Comment by chbecker-ms** [comment]
Comment from Luis:

A bit more info here, this seems to refer to the One Hand Rotation Modes in the Manipulation Handler script.

**Comment by luis-valverde-ms** [comment]
This sounds like a job for @julenka . Feel free to re-assign otherwise.

**Comment by thalbern** [comment]
according to documentation this is the expected behavior https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_ManipulationHandler.html

**Comment by julenka** [comment]
While it's true the docs say this, the end experience feels odd, don't you think? Perhaps we should update the documentation as part of this fix. My thinking is that 'maintain rotation to user' should really be 'maintain rotation to user about the Y axis'. In other words, the object should not rotate about the X or Z axes if you rotate your head about the X or Z axis.

**Comment by thalbern** [comment]
I'll try how it feels with Y only

**Comment by thalbern** [comment]
I think it would be fine to have pitch and yaw  (x / y) , just roll feels very awkward.
