### ISSUE TITLE
Clicking 'Copy & Customize' in the Mixed Reality Toolkit component adds AsyncCoroutineRunner to scene

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4297]
1. Create a new scene
2. Mixed Reality Toolkit > Configure > Choose default configuration profile
3. Go to MRTK component and click 'Copy & Customize'
4. Observe 'AsyncCoroutineRunner' game object added to scene root.

From Lukas:

This probably is a consequence of
commit 1c3e99bc: Fixed an issue with creating multiple async runners.

Previously the AsynCoroutineRunner would be created as well, but hidden using `gameObject.hideFlags = HideFlags.HideInHierarchy`. The commit above searches for existing objects with matching name "AsyncCoroutineRunner" (not so great).

~~GameObject.Find ignores hidden objects according to docs: "This function only returns active GameObjects", so i assume that's why the hiding was removed.~~
I have made a little test script, and it seems that `GameObject.Find` actually does find hidden gameobjects, just not inactive ones (as in `gameObject.SetActive(false)`). So i'm not sure why this was removed after all.

**Comment by Troy-Ferrell** [comment]
Does not repo on new scene latest MRTK development in Unity 2018 LTS
