### ISSUE TITLE
HandInteraction Example scene does not run at 60 fps

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4299]
(Ported to GitHub, reference 21395675)

All our example scenes should probably run at 60 fps, to match best practices.

**Comment by chbecker-ms** [comment]
(Ported to GitHub, reference 21395675)

All our example scenes should probably run at 60 fps, to match best practices.

**Comment by wiwei** [comment]
@julenka if you still see this let me know how you're hitting it. Last I tried this, it was running at 60fps.

Would also be helpful to have the platform/settings specified (i.e. HL2? HL1?)
