### ISSUE TITLE
SeeItSayIt should either not require the phrase to be added to the Speech Input Profile or should have a drop down to indicate such

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4301]
(Ported to GitHub, reference 19337614)

1. Add a Holographic Button to an MR Scene
2. Add "Hello" as the See It Say It" and hook an item up to "OnClick"
3. Check "Is Global" and uncheck "Require Gaze"
4. Run Scene, say "Hello"

Expected: Button OnClick is triggered
Actual: Button OnClick is only triggered if I *also* add the SeeItSayIt keyword to the SpeechCommandsProfile

If SeeItSayIt allows me to type in the string I would not expect to have to add it to the SpeechCommands Profile

While I believe that not having to add it to the SpeechCommands profile would be the better design, I could be okay with/understand the design if the SeeItSayIt field instead of allowing me to type in required me to select from a dropdown the keyword, much like the SpeechInputHandler does

**Comment by chbecker-ms** [comment]
Comment from Yoyo:

This is a nice to have. 
We should consider this update post beta to improve developer experience.

**Comment by chbecker-ms** [comment]
Comment from David:

Adding a dropdown to select the configured speech command makes a lot of sense as there are some tie-ins with the action definitions that are also needed to properly wire up a speech command.

**Comment by Troy-Ferrell** [comment]
Voice command is now a dropdown related to the speech profile in Interactable
![image](https://user-images.githubusercontent.com/25975362/61170054-00178500-a532-11e9-8851-73e91fc349df.png)
