### ISSUE TITLE
Mouse Pointer does not move on slow mouse movement

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#4304]
## Describe the bug

When moving the hardware mouse very slowly, the Mouse Pointer does not move at all. This is most noticeable when you want to adjust its position just a little and nothing happens.

## To reproduce

1. Go to any empty scene and add a MRTK profile
2. Add the MouseDeviceManager to the InputSystemProfile
3. Start the scene and move the mouse slowly
4. See how the virtual version does not move

## Expected behavior

The virtual mouse moves as precise as the real (lol) one

## Your Setup (please complete the following information)

- Unity Version 2018.3.13f1
- MRTK Version v2.0 mrtk_development as of now

## Target Platform (please complete the following information)

- Windows Desktop (Editor)

**Comment by wiwei** [comment]
Thanks for filing this issue, and then fixing it!

**Comment by wiwei** [comment]
Closed out the issue, as I believe that with your fix merged in, it should be addressed.
