### ISSUE TITLE
Sub-Profile navigation instead of fold out

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#4307]
## Describe the problem

The MRTK provides foldouts for each profile it contains to show their configuration. Using IMGUI this noticeably slows down the inspector and editing/ scrolling is kinda laggy.

## Describe the solution you'd like

Each profile already has a "Back to configuration file" button. The MRTK could have an "eye" button next to the clone button, that opens the desired profile in the inspector. This way the navigation is complete (up and down) and the overhead of drawing the whole MRTK + folded out Profiles would be gone

**Comment by Troy-Ferrell** [comment]
If you double click the object field of a given profile (component to left of "Clone" button), it will drill into that particular profile asset in the inspector thus allowing you up and down navigation

**Comment by Railboy** [comment]
@Alexees Troy is working on an inspector upgrade that reduces drawing overhead quite a bit. @Troy-Ferrell when can we expect that PR?

**Comment by Troy-Ferrell** [comment]
Just submitted :) https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4314
