### ISSUE TITLE
Public properties in SurfaceMagnetism are missing

### ISSUE THREAD

**Issue by thedevleon** [microsoft/MixedRealityToolkit-Unity#4310]
## Describe the bug

Not exactly a bug per se, but while the SolverHandler, RadialView, Orbital, and a couple other Solvers have their private properties also exposed as public properties, that is not the case for SurfaceMagnetism. The only public accessible property is OnSurface.
I want to add a SurfaceMagnetism Component and setup its variables during runtime, which is not possible currently.

## To reproduce

Take a look at the SurfaceMagnetism class.

## Expected behavior

Public Properties to all the private variables that can be edited in the Inspector in Unity.

## Setup

- Unity 2018.3.14f
- MRTK v2.0.0 RC1 Refresh

**Comment by wiwei** [comment]
@cre8ivepark @keveleigh  do you have any history/background for why these variables weren't made public? Seems like a fairly obvious extension point that we should enable.

**Comment by keveleigh** [comment]
I'm not aware of any specific reason. I know other solvers have had public properties added over time, so it's possible this is one that hasn't been worked on yet.

**Comment by Troy-Ferrell** [comment]
This is a dupe of #4650
