### ISSUE TITLE
MRTK design time code execution puts Editor/project into bad states

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4319]
(Ported to GitHub, reference 20076381)

When using MRTK vNext, there seems to be a fair bit of code that executes at
edit/design time. This logic seems to be buggy and puts the Unity Editor/project
in a bad state that sometimes requires reopening the scene or restarting Unity.
This is expected to be a major developer workflow issue and is a major
contributing factor for MRW teams not adopting MRTK vNext at this point. Here
are some comments directly from David Evans after doing some in-depth
prototyping with MRTK vNext:

*Additionally, there are many small quality-of-life issues and bugs that make
development difficult. There is a lot of edit-time code running in the MRTK, and
it often errors or assumes too much about what you are trying to do and
automatically does the wrong thing. I frequently had to close and reopen the
scene or Unity itself in order to get things working again...*

*...there’s a couple things, they have edit time scripts like
CanvasEditorExtensions which attempt to modify assets and game objects at
runtime but do so without marking them dirty, preventing the data from ever
being serialized. In several places there are edit time scripts which attempt to
access objects on the mixed reality toolkit singleton, which may or may not be
valid depending on whether you’ve recently hit play or recompiled. I would
frequently see errors in console at edit time that looked like “failed to find
mixed reality toolkit”*

**REPRO CASE (\~33%):**

\-Open an already-used repro where the MRTK examples live (I.E. you've used one
of the available demo scenes and the project Library folder already exists).

\-Open a new demo scene that you haven't opened before in this repro (in our
case, HandInteractionUnityUIExample).   
-Go to the MRTK profile configuration, and select "Copy and Customize". 

\-After you do, select the new profile and then go to the input profile and make
a few changes to the input simulation (we changed it to a gesture hand from an
articulated hand). Modify/customize a few other things just to be sure.

\-Upon completing and saving the new profiles, check your log. You should see a
similar error to what is attached in the photo.  
  
Notes:  
-If you delete your temp folder, it doesn't fix the problem. Only deleting your
library folder does the trick. 

Here's an instance of the MixedRealityControllerMappingProfile throwing reflection errors when I tried to search for objects in assets:
![untitled](https://user-images.githubusercontent.com/42761412/57660675-8d734300-759c-11e9-9a5a-0da51ac8fdac.png)

**Comment by wiwei** [comment]
If anyone else is able to repro this, please let me know what steps you've undertaken to hit this. I've tried the steps a number of times without hitting this.

For folks who are hitting, if you can unpack the exception (i.e. attach VS to Unity) (i.e. dump the exception) that would be really helpful - I can put in a patch here to lessen the impact.

**Comment by wiwei** [comment]
Okay doing some searches, I can see that this type of exception isn't common, but also isn't uncommon - especially given how we're enumerating possibly controller types by enumerating every single visible assembly, it probably makes sense to handle failures in one-off assemblies (especially if the assembly is a non-MRTK one that has nothing to do with controllers)
