### ISSUE TITLE
Play a scene without an Mixed Reality Toolkit object in the scene will trigger some errors.

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4322]
(Ported to GitHub, reference 19937520)

[Editor Bug] Play a scene without an Mixed Reality Toolkit object in the scene will trigger some errors and one will be added to the scene automatically, and it will prompt for making a profile selection. However, once profile is chosen and tries to Play again, it won't work. I see a popup animation on the MixedRealityToolkit object in scene tree, but the app won't start. The workaround is to close and restart Unity.

**Comment by Railboy** [comment]
This issue is fixed in #4035
