### ISSUE TITLE
Remove need for camera at startup.  Partner dynamically inserts a camera, based on platform type.  This cause null exceptions during MRTK initialization.

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4323]
(Ported to GitHub, reference 19937570)

Remove need for camera at startup.   Our project dynamically inserts a camera, based on platform type.  This cause null exceptions during MRTK initialization.

Addition from Graham:

Common request to decouple MRTK from camera in the main scene (or scene where MRTK lives) and dynamically create cameras in sub-scenes.  Does not block current customers, but would make the structure of the project easier.

Note: workaround could be having MRTK in a separate main scene to load the empty camera scene (i.e. like open source Galaxy Explorer shows)

**Comment by Railboy** [comment]
This change should be incorporated into our camera system service.
