### ISSUE TITLE
MRTK vNext has build breaks when using "warnings as errors" (-warnaserror+)

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4324]
(Ported to GitHub, reference 20029618)

Production apps typically build with "warnings as errors" (the -warnaserror+ compiler option).  To enable it, add an "Assets\csc.rsp" file to MRTK and include "-warnaserror+".  Try to build MRTK vNext and you'll hit build breaks.

I fixed the build breaks I could and added TODOs to fix the remaining ones where the fix was non-obvious to me.  See the "Links" in this bug for commit info.

To prevent breaks from creeping back in, MRTK will need to keep "-warningsaserror+" in its csc.rsp file.

**Comment by wiwei** [comment]
We need to keep our code warning and error clean, lest we break other projects that treat warnings as errors.

**Comment by wiwei** [comment]
I think the issues that this was originally for have been resolved - we can open new issues for specific ones when we encounter them in the future. There's not really a point to keep this around as a catch-all
