### ISSUE TITLE
[VR] Motion controller pointer ray (white) disappears after failing teleport

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4326]
(Ported to GitHub, reference 20223654)

Initiate a teleport, but aim the parabolic ray somewhere you can't go (e.g. where there's no floor).

On releasing the stick, there will be no ray from the controller axis proxy.

Doing a successful teleport will bring back the white (straight) pointer ray.

**Comment by keveleigh** [comment]
I was unable to repro this on the latest MRTK
