### ISSUE TITLE
[MRTK Shell Parity] Voice Command Confirmation Label

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4327]
(Ported to GitHub, reference 20272553)

This came up while I was talking with Lia about SeeItSayIt and nailing down the requirements for the desired behavior.
Command Confirmation is a feature for speech oriented things (where it pops up a small box with the command words you said).
Shell does Command Confirmation for itself, but **not** for exclusive apps.
 
MRTK does not currently have any functionality for command confirmation (to my knowledge)

This means individual devs/partners need to reproduce this functionality themselves. 
Many devs won’t do this and this will de-prioritize speech as a result.

**Comment by wiwei** [comment]
@Yoyozilla, this actually seems like a feature request, and I'm not sure that this is really necessary for GA. Moreover, I think that this issue (and the original issue in the internal tracker that spawned this) is lacking in details on how we'd validate this feature request, what the ask is, etc.

I'm removing the GA tag/tracking.

**Comment by cre8ivepark** [comment]
Completed with #5868
