### ISSUE TITLE
Projects with a space in the title break the "Open in Visual Studio" button in the MRTK Build Window

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4329]
(Ported to GitHub, reference 20308712)

I created a project called Is Mirage? and made the project name IsMirage. When I hit Build Unity Project in the build window, everything is fine. But when I hit Open In Visual Studio it says it can't find my project and asks if I want to build again.

**Comment by Troy-Ferrell** [comment]
No longer repos (2.1 stabilization latest 9/27)
