### ISSUE TITLE
Radial button selection doesn't visually change when set from script

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4331]
(Ported to GitHub, reference 21387842)

Using either the CurrentIndex member or the SetSelection(int idx) set the current index and generate appropriate callbacks, but don't call SetDimensionIndex on the the ToggleList elements so that they can visually update. That happens in OnSelection(), which is protected.

It seems like ideally SetSelection(idx) should call OnSelection(idx, true).

This would also get around having to call both "set.CurrentIndex = idx" and "set.SetSelection(idx)" to set the current index.

But I may be missing some subtlety here.

**Comment by killerantz** [comment]
The correct approach is to call SetSelection(idx) which calls into the Interactable and sets it to toggled, which should call back to the InteractableToggleCollection to change the Current Index. Changing the current index only effects the collection when enabled, it's a way to set the default selected value through the inspector. **Some recent updates to Interactable broke the round trip and actually no longer executes any code in Interactable.** 

A fix would be to change the SetSelection(index) to call OnSelection(index, true). This will set the visual state of the radial button or toggle, but will not execute any OnClick events, which I think is preferred. The original intention would have triggered the OnClick event for the selected toggle, which doesn't offer much flexibilty if we only want to change the visual state of the radials. I can test and push something up in the next day or so.

**Comment by keveleigh** [comment]
Fixed by #4356.
