### ISSUE TITLE
[MRTK Shell Parity] Contextual cursor visualization logic needed

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4332]
(Ported from GitHub, reference 20672232)

MRTK Pointer/Cursor logic need to have a mechanism to show different types of cursors in various states. We need to provide shell's default cursor visualizations. Developers should be able to easily assign own cursor assets through Unity Inspector. (example image below)

![Shell_Cursor](https://user-images.githubusercontent.com/13754172/57989817-429e7300-7a55-11e9-927b-e1834f20f0a3.jpg)

**Comment by cre8ivepark** [comment]
@keveleigh I have the assets ready! we need logic to display different types of cursor icon prefab. This work also includes replacing the existing cursor asset to match shell.

**Comment by cre8ivepark** [comment]
Image updated based on the latest shell design. (Alex Gough)
