### ISSUE TITLE
MRTK > Add to Scene and Configure menu does not add MixedRealityPlayspace

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#4334]
## Describe the bug
MRTK > Add to Scene and Configure menu does not add MixedRealityPlayspace

## To reproduce

1. File > New Scene
2. Mixed Reality Toolkit > Add to Scene and Configure

![2019-05-15 00_49_40-Unity 2018 3 13f1 Personal - Untitled - MRTK-GitHub - PC, Mac   Linux Standalone](https://user-images.githubusercontent.com/13754172/57712437-6a40a600-7625-11e9-9f8b-c6f8d6dd9ea1.png)

## Result
Only **MixedRealityToolkit** is added. **MixedRealityPlayspace** is missing.

![2019-05-15 00_50_02-Unity 2018 3 13f1 Personal - Untitled - MRTK-GitHub - PC, Mac   Linux Standalone](https://user-images.githubusercontent.com/13754172/57712527-8e9c8280-7625-11e9-80c0-39c23a1d05eb.png)

## Expected behavior
**MixedRealityPlayspace** should be added together with **MixedRealityToolkit** just like other existing example scenes.

![2019-05-15 00_53_15-Unity 2018 3 13f1 Personal - HandInteractionExamples unity - MRTK-GitHub - PC, M](https://user-images.githubusercontent.com/13754172/57712610-bc81c700-7625-11e9-8d3f-2dfa5e7e6b9d.png)

## Setup 

- Unity Version: 2018.3.13f1
- MRTK: mrtk_development branch

**Comment by Railboy** [comment]
This is a change introduced by the new static playspace class.

Is this considered a bug, or is it just new expected behavior? Does anyone know if people make use of the playspace transform prior to runtime?

**Comment by cre8ivepark** [comment]
@Railboy Oh, if that's the case, we should update the existing example scenes and documentation. I can do it once it is clarified.

**Comment by Railboy** [comment]
If people depend on the playspace being there to do setup work then I think I'd call it a bug. I'll start asking around.

**Comment by cre8ivepark** [comment]
Currently, since we have MixedRealityPlayspace in our documentation:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html

**Comment by keveleigh** [comment]
Fixed via #4338
