### ISSUE TITLE
PROPOSAL: Add service profile accessor property to core system interfaces.

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#4335]
By strict definition, this is a breaking change (any custom system implementation would be required to update). For application code, this provides a new option for gaining access to the profiles.

## Describe the problem

Currently, application code is required to call MixedRealityToolkit.Instance.ActiveProfile.<system>Profile to access profile data at runtime. The work related to #3545 enables developer customers to use a custom registration path for systems which does not gurantee that the MixedRealityToolkit object will be instantiated.

## Describe the solution you'd like

Add an accessor property to each core system that exposes the profile to application code, similar to the following:

```
IMixedRealityInputSystemProfile Profile { get; }
```

## Describe alternatives you've considered

Considering many (most?) systems provide individual profile settings as properties of their interfaces, one option is to disallow application code from directly accessing the profiles.

**Comment by Railboy** [comment]
If we do this then we may want to standardize how profiles are used by services. At the moment some services continue to use profile data at runtime, so changing the profile changes their behavior. Other services consume the profile data on initialize and ignore it from that point forward.

So if all core services 'officially' expose their profile data, there may be an incorrect expectation that either a) the profile can be modified at runtime to affect the service, or b) that the data can be modified _without_ affecting the service.

**Comment by davidkline-ms** [comment]
Great points, @Railboy!

**Comment by davidkline-ms** [comment]
Step 1 should be to review what gets exposed by the services and what can only be accessed via the profiles.

If memory serves, very few (any?) services read profile settings on demand.

**Comment by davidkline-ms** [comment]
Scanning for references to "ActiveProfile" uncovered two example/demo scripts that access a system profile:

- MixedRealityToolkit.Examples\Demos\HandTracking\Script\GestureTester.cs
- MixedRealityToolkit.Examples\Demos\HandTracking\Script\ToggleHandVisualisation.cs

**Comment by davidkline-ms** [comment]
Other key locations:

- MixedRealityToolkit\Inspectors (profile inspectors)
- MixedRealityToolkit\Providers (controllers and visualizers)
- MixedRealityToolkit.Providers (Windows mixed reality and windows voice)
- MixedRealityTookit,SDK (ux features and speech input handlers)
- MixedRealityToolkit.Services (input system and simulation)
