### ISSUE TITLE
Slate is missing sounds on touch down and on touch up. These should be configurable via OnTouchDown and OnTouchUp events in the slate contents, like we do for manipulation.

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4344]
Ported to Github, reference 21090800.

Slate is missing sounds on touch down and on touch up. These should be configurable via OnTouchDown and OnTouchUp events in the slate contents, like we do for manipulation.

**Comment by cre8ivepark** [comment]
Merged
