### ISSUE TITLE
Slate feature is buried in Examples package.

### ISSUE THREAD

**Issue by jwittner** [microsoft/MixedRealityToolkit-Unity#4345]
## Describe the problem

Slate feature is cool, but the documentation doesn't lead you to any prefab to use. After some investigation it turns out that the prefab exists inside the Examples. Core features that are surfaced in the README should not be inside the Examples package.

## Describe the solution you'd like

Move the Slate out of examples and into the core package. Update the Slate docs to link to the prefab in the source to get started with.

**Comment by wiwei** [comment]
@cre8ivepark @julenka do you have any background here on why certain types of prefabs were put directly into the examples folder, instead of outside of the examples folder?

**Comment by julenka** [comment]
No, I do not know. Yoon would be the right person to answer this.

**Comment by julenka** [comment]
Merged

**Comment by jwittner** [comment]
Yay! Thanks for surfacing this super useful feature!
