### ISSUE TITLE
Error "There's already a UIRaycastCamera in the scene. It will be ignored" when opening HandInteractionAll scene

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4346]
Ported to Github, reference 20337078

Open HandInteractionAll scene.
2. Error window shows the following error:

There's already a UIRaycastCamera in the scene. It will be ignored, so please delete it to avoid confusion.
UnityEngine.Debug:LogError(Object, Object)
Microsoft.MixedReality.Toolkit.Services.InputSystem.FocusProvider:Initialize() (at Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs:329)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:InitializeAllServices() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:907)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:InitializeServiceLocator() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:293)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:InitializeInstance() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:453)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:get_Instance() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:387)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:ConfirmInitialized() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:486)
Microsoft.MixedReality.Toolkit.Core.Services.MixedRealityToolkit:OnValidate() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:543)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

It looks like just deleting the UIRaycastCamera from the hand interactions scene should handle this.

**Comment by keveleigh** [comment]
I fixed this a while back.
