### ISSUE TITLE
MRTK should have different hand mesh/marker settings based on transparent or opaque displays

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4347]
In VR you always want hand visualizations, even if you only use it in the editor, but in AR there's a good chance you don't want the hand visualizations. You should be able to determine which to use based on display type.

**Comment by wiwei** [comment]
Ported to Github, reference 20585593

**Comment by keveleigh** [comment]
This feels like a dupe of #4213

**Comment by wiwei** [comment]
Yep, definitely overlaps
