### ISSUE TITLE
MRTK's Appx Build Options tab on the build menu doesn't list "ARM64" as a choice

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4349]
Ported to github, reference 20430683

**Comment by keveleigh** [comment]
The `Architecture` enum does have ARM as an option:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/e1c20568f7b39d17b9ccde8376b5328cc0314834/Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs#L41

so I'm repurposing this issue to track ARM64 support in Unity 2019
