### ISSUE TITLE
DocFX API documentation assembly reference points to cs.temp.dll.dll

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4350]
Ported to Github, reference 20998588

Open any class entry in the api documentation generated by docfx and observe wrong assembly information:
Assembly: cs.temp.dll.dll

This is due to the fact that we're using the .cs files without any project files for generation. Docfx just can't figure out in which binaries they will end up. A solution would be to generate the unity project files on the CI and add the project files instead of the .cs files  - I already tried that and it worked, but I bulk added all the project files which will lead to broken / missing links. So there needs to be a finer filtering in the json build file for those project files.

**Comment by keveleigh** [comment]
I think we should still look into fixing this. It'd be useful to know which class exist in which assembly

**Comment by MaxWang-MS** [comment]
After the migrating the API reference docs from github.io to docs.microsoft.com this issue is no longer present.
