### ISSUE TITLE
Add a default HoloLens 2 profile

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4351]
A common ask from a number of customers is to have a common HL2 profile, which does things like disabling boundaries, disabling hand visualizations (for perf), etc.

**Comment by wiwei** [comment]
Should have teleport off as well.

**Comment by julenka** [comment]
@wiwei any reason this is still open or should I close it?

**Comment by keveleigh** [comment]
Added via #4442
