### ISSUE TITLE
How can I Anchor the position on load scene?

### ISSUE THREAD

**Issue by WarrenMondeville** [Microsoft/MixedRealityToolkit-Unity#436]
The position when I load the next scene ,the position is changed, After mapping the room ,I find some position to place GameObjects, I use an empty GameObject with WorldAnchor and DonDestoryOnLoad Script On it to save the position,but when load to the next scene and get the position ,some Info has changed,Can you help me ? How to keep the virtual Object position in the real world,even I load scene

**Comment by jessemcculloch** [comment]
@WarrenMondeville - Is this still something you need answers to?  or can we close this?

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
