### ISSUE TITLE
Default grab radius is too large

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4371]
Ported to Github, reference 20800672

During our work with ISVs over the past few weeks we have always lowered the grab radius on the GrabPointer. By default objects can be grabbed within a 15 cm (with an additional 0.5 cm constant) radius sphere. A 5 to 10 cm radius seems more appropriate.

![01750420-175e-4dda-8596-07dad8e7b315](https://user-images.githubusercontent.com/5840182/57795614-494a8480-76fb-11e9-895e-d1f322a4cde5.jpg)

**Comment by julenka** [comment]
merged
