### ISSUE TITLE
GGV cursor does not stick to object during manipulation

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4372]
Ported to Github, reference 20823387

Use HoloLens 1 gestures to move an object in HandInteractionExamples scene. You can use either in-editor simulation or go to an actual HoloLens device. For in-editor simulation set Hand Simulation Mode in InputSimulationProfile to Gestures:

![66739081-02a9-4a87-9924-ca0604dca01c](https://user-images.githubusercontent.com/5840182/57795709-81ea5e00-76fb-11e9-8914-92865d0bdb33.png)

Expected:
when you grab and move an object, the cursor sticks to the object like in the HoloLens 1 shell

Actual:
The cursor does not stick to the object being manipulated.

**Comment by keveleigh** [comment]
I think this represented the opposite of the request in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6350. We should make this a toggle-able feature.
