### ISSUE TITLE
MRTK instance can be initialized twice in editor

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedRealityToolkit-Unity#4381]
## Describe the bug

MRTK instance can be initialized twice in quick succession when entering playmode in editor. This can cause a null reference exception in GazeProvider, which cascades into a series of errors about missing cursors.

## Steps to Reproduce

- Open HandInteractionExamples scene, or any scene with a main camera that already has a GazeProvider component.
- Hit Play.
- Observe errors.

## Expected behavior

MRTK instance should be initialized once. No errors should occur.

**Comment by gilbdev** [comment]
other repro:
- play
- edit some code, unity will auto recompile code and try to keep it played ("edit and continue")
=> mrtk is initialized again (you can see diagnostic twice)
