### ISSUE TITLE
Having the setting to toggle bounding box visualization enabled in editor will be helpful in debugging

### ISSUE THREAD

**Issue by ritijain** [microsoft/MixedRealityToolkit-Unity#4394]
## Describe the problem

While using the bounding box, it would be helpful to have the rigidbody created for bounding box to be visible in inspector and the hierarchy. (I had my collider configuration messed up and so i was not able to get bounding box working, since it used to pop up at a different location in the 3d space.  Enabling this property helped me debug this issue faster)

## Describe the solution you'd like

set the 
hideElementsInInspector  property to be configurable in the inspector.

**Comment by djee-ms** [comment]
I agree, this is a very simple yet valuable thing to have. I would like to understand the rationale of hiding those things in the first place. Creating some `GameObject` at runtime already makes it more difficult to reason about the `BoundingBox`; hiding those in addition increases the burden.

**Comment by julenka** [comment]
@johnppella wrote the Bounding Box, John could you please comment?

**Comment by julenka** [comment]
I will expose this in an upcoming PR

**Comment by julenka** [comment]
I've got a PR that will address this.

**Comment by wiwei** [comment]
I believe this has been addressed by the referenced PR, closing this out.
