### ISSUE TITLE
The ManipulationHandler script settings seem to imply that there is a “onehanded scale operation”

### ISSUE THREAD

**Issue by ritijain** [microsoft/MixedRealityToolkit-Unity#4396]
## Describe the bug
The ManipulationHandler script settings seem to imply that there is a “onehanded scale operation”. Allowing configuration if Scale mode supporting manipulations in onehanded manipulation mode is confusing. From the code it seems that the only intended operation for onehanded manipulation is Move. This applies to any ManipulationType setting that contains Scale.
![image](https://user-images.githubusercontent.com/17660747/57821138-458f2000-7744-11e9-90dd-9c2d2d0747e5.png)

This can be very confusing for the developers trying to consume this script. 

Either  MRTK should do the following two things - 
1. The script/ document should clarify that some of the TwoHandedManipulationTypes settings only work with 2 handed manipulation. (eg - Scale only works 2 handed)  
2. The script needs an On Validate  to prevent users from incorrectly configuring the script, resulting in unintended results.  (eg - i set my script to "OneHandedOnly" "Scale" mode, but my pointer is still able to move the gameobject which is not what i wanted in my app)

or

Start supporting some sort of OneHanded Scale operation.

Update the ManipulationHandler documentation accordingly.

**Comment by Yoyozilla** [comment]
We should add in the doc that onehanded scaling is not supported.

**Comment by ritijain** [comment]
@Yoyozilla this is not just a documentation issue. First there needs to be a code change and then the documentation should be updated accordingly.

**Comment by MenelvagorMilsom** [comment]
This issue is fixed in #5955. If TwoHandedOnly is selected, only two hand options will show:
![image](https://user-images.githubusercontent.com/47415945/64970313-6b1c6980-d89d-11e9-9e9a-382f2ee04b3d.png)
I will follow this up with improvements to the docs.
