### ISSUE TITLE
v2.0.0 RC1 Refresh doesn't work with HoloLens 1 and loads of other issues

### ISSUE THREAD

**Issue by devedse** [microsoft/MixedRealityToolkit-Unity#4401]
## Describe the bug

**Quick disclaimer: This post may look a bit ranty but I'm simply struggling with a lot of issues that I'd like to get resolved. So please if someone has an answer to what I'm doing wrong let me know**

I've been struggling with loads of issues the last few days on getting anything deployed to the HoloLens 1 we have.

I first tried version v2.0.0 RC1 Refresh of MRTK and imported this in a clean Unity 2018.3.14f1 project on a laptop running Windows 10 1803 (17134).

```
Setup 1:
Windows 10 1803 (17134)
Unity 2018.3.14f1
MRTK v2.0.0 RC1 Refresh
```

I then kept running into trouble where it wouldn't build due to errors around classes like HandMeshVertex missing.

![image](https://user-images.githubusercontent.com/2350015/57860302-efc68080-77f4-11e9-92ff-9550d6788025.png)

**So basically, issue 1:
Latest version of the SDK needs a preview version of Windows which is not described in the release notes or on the github home page.**

I looked around for this error and some people suggested to install the latest preview SDK. To do this you have to also use a preview version of windows, so forward a few hours and we now have this setup:

```
Setup 2:
Windows 10 1903 (18898.0)
Unity 2018.3.14f1
MRTK v2.0.0 RC1 Refresh
```

I switched the SDK version around to this:
![image](https://user-images.githubusercontent.com/2350015/57860776-be9a8000-77f5-11e9-9208-58d2c296cdf9.png)

And tried again. I then found out that apparently the "Build All" button does all kinds of things but never actually produces a working build.

It usually crashes somewhere on an error that it tries to build |Master as configuration.

**Issue 2:
Build all tries to build some strange non existant configurations like |Master.**

I also forgot to mention that since Visual Studio 2019 the MSBuild.exe file was moved.

**Issue 3:
The path of MSBuild is hardcoded and has moved with VS2019, this means it can't find it anymore.**

While we're talking about VS2019, another issue is that it also seems the MRTK can't be satisfied with the build tools of VS2019,

**Issue 4:
MRTK needs to have the old Visual Studio 2017 installed (which is in fact quite hard to even download nowadays), simply installing the 2017 build tools from the 2019 installer doesn't work**

Ok back to where we were, we can now click on the other build button that does usually work:

![image](https://user-images.githubusercontent.com/2350015/57861293-97907e00-77f6-11e9-8298-ed1909708069.png)

**Issue 5:
After a few minutes of building we now sometimes get a folder with the dependencies in it and sometimes we don't**
![image](https://user-images.githubusercontent.com/2350015/57861371-c27ad200-77f6-11e9-83c2-72bd6efe1cf0.png)

I haven't really been able to pinpoint when it does create the dependencies and when it doesn't, but it seems to help to sometimes click that other build all button in between, wait till that fails, and the build the real stuff with the "good" button.

Ok, so now we have an appx file with dependencies. Let's now try to deploy this.

![image](https://user-images.githubusercontent.com/2350015/57861532-0d94e500-77f7-11e9-88df-d7714837f459.png)

**Issue 6:
When we click on connect an error pops up that doesn't give any information on what is actually wrong:**
![image](https://user-images.githubusercontent.com/2350015/57861590-256c6900-77f7-11e9-9711-56ed69afbb9d.png)

It seems to have something to do with the HTTPS certificate not being accepted from the HoloLens but when I try to install that it also doesn't go smoothly as there doesn't seem to be a way to install a certificate without a valid issuer:

![image](https://user-images.githubusercontent.com/2350015/57861668-4d5bcc80-77f7-11e9-8fba-16f7748848d6.png)

**Issue 7:
No clear documentation on how to install the HoloLens certificate to avoid issue 6 (if this is even the right thing to do**

I then started fiddler, enabled HTTPS decrypting and by doing that fiddler seems to accept the certificate and Unity can now connect to the HoloLens.

**Issue 8:
The deploy button doesn't do anything, but yeah basically at this point I gave up diving into this and went directly to the web UI to deploy**

I selected the package to deploy:
![image](https://user-images.githubusercontent.com/2350015/57861871-b2afbd80-77f7-11e9-9f64-e2a477b5cbb4.png)

Added the VCLib stuff as a dependency:
![image](https://user-images.githubusercontent.com/2350015/57861932-c9eeab00-77f7-11e9-92d2-4312e42fd1b7.png)

And started deploying

**Issue 9:
An application with the name Template3D already exists, due to the project name not changing when creating a new Unity project**

This took quite some investigation as well but apparently in the project settings file in unity the newly created project was still named Template3D:
![image](https://user-images.githubusercontent.com/2350015/57862100-1afe9f00-77f8-11e9-8ccc-55361b374533.png)
![image](https://user-images.githubusercontent.com/2350015/57862043-fb677680-77f7-11e9-8533-6bd66d6707d9.png)

Ok, I changed this and tried to rebuild the project again.

**Issue 10:
You have to delete all the generated project files as any output from the build will still internally be named Template3D**

After simply deleting everything, and re-cloning the project we were moving forward again. I built the solution into an appx + dependencies and uploaded them to the HoloLens.

**Issue 11:
Now the created packages is built using an SDK too high for my HoloLens:**
![image](https://user-images.githubusercontent.com/2350015/57862447-a1b37c00-77f8-11e9-9196-1b89aac14bea.png)

## Summary

Don't issue as much as a rant as it might sound, but I'm simply stuck in getting my project build and running into issues everywhere I go.

Am I simply using the wrong versions for deploying to the HoloLens or is something else in my procedure going wrong? I'd like to know.

## Target Platform (please complete the following information)

- HoloLens 10.0.17763.438

**Comment by wiwei** [comment]
Thanks for the taking the time to write up everything (the pictures are super helpful). There's a number of things to talk about, so let's start from the top.

1) The assembly rewriter errors that you're seeing there are benign and are a Unity bug: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/3939

2) Some of the older docs + a few months ago you needed to get the insider SDK, but that's no longer the case - the thing that was the insider SDK is now the published SDK, and following the links on the GettingStarted page or just on the MRTK wiki (i.e. the default page) should get you to this thing:

![image](https://user-images.githubusercontent.com/5840182/57872019-a1e35580-77bf-11e9-87f8-ae635cf8c982.png)

I think that the version that you did download is actually super advanced (our team internally hasn't tried that out yet, so I actually have no idea if it's supposed to work).

3) I don't believe the build window tools have been updated for the new VS, but then again, as a caveat, not everyone actually uses that build window tool. Some on the team do use it, though personally I've used Unity's default tooling.

So for me to build and deploy I will:

![image](https://user-images.githubusercontent.com/5840182/57872129-d6efa800-77bf-11e9-8031-88733e6fe4d0.png)

Hit the build button there, this will generate a VS solution:

![image](https://user-images.githubusercontent.com/5840182/57872155-e8d14b00-77bf-11e9-8aac-89177029f3d8.png)

I will then open this solution and do:

![image](https://user-images.githubusercontent.com/5840182/57872193-04d4ec80-77c0-11e9-923c-564aa68d0b81.png)

Note that I will have connected the device via USB prior to hitting run.

**Comment by wiwei** [comment]
If others on the team have been using the flow mentioned above, please chime in here

**Comment by devedse** [comment]
> I think that the version that you did download is actually super advanced (our team internally hasn't tried that out yet, so I actually have no idea if it's supposed to work).

Thanks for the quick response, but what exactly do you mean by this? Are you talking about the version of MRTK or of Windows?

Also, what suggestion would you suggest for "Production" for HoloLens 1 development?
Would that be HoloToolkit, MRTK Renew or the old MRTK? (If possible, could you specify the exact version number)

**Comment by devedse** [comment]
@wiwei , do you have any update on this?

**Comment by wiwei** [comment]
_Are you talking about the version of MRTK or of Windows?_

I think that the listed SDK above was from here:

https://blogs.windows.com/buildingapps/2019/05/09/windows-10-sdk-preview-build-18890-available-now/

This is more advanced than the one that we use (i.e. 18632, which is now just the regular i.e. non-preview SDK). None of the folks on the team have been using the _new_ preview SDK, so I wanted to call that out to switch to the currently released one (18632) so that we're all on the same SDK version.

I believe this information is covered here:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html

Under the prereqs section.

Regarding version of Windows, our team has been working on 
https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1809_(October_2018_Update)
https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1903_(May_2019_Update)

I think technically speaking even 1507 would work assuming you could install VS2017 and the SDK on them, but our team has mostly been keeping up to date using windows update itself.

Lemme chat with the rest of the team about the remaining question - there's a timing aspect to this where we're trying to stabilize V2 for a general release (at which point the answer should be obvious - V2) but in the interim I want to make sure to chat with the folks who worked on V1 to know they think.

**Comment by krishnan-unni** [comment]
Hey @wiwei I have tried the same that you have mentioned above:

Unity 2018.3.14f1
Win SDK 10.0.18362
VS 2017
IL2CPP backend
Hololens 2 Emulator

I am building it in x86 mode and deploying to the emulator.

![image](https://user-images.githubusercontent.com/14880339/58768787-5924ee00-856e-11e9-97b0-e0d26fbc4437.png)

Once the App starts, it shows the Unity Splash screen and then a black screen. I can see that the App is running through the device portal, also I can see that a DefaultRoom is loaded. Any idea what I could be doing wrong? Could it be the HL2 emulator?
The project has nothing but the MRTK toolkit added with the Input Action scene example from the Example project. 

This is what is shown in the emulator. I took a look through the 3D view in the device portal. Nada.
![image](https://user-images.githubusercontent.com/14880339/58769487-a9ec1500-8575-11e9-81a8-c46c205401b3.png).

**Comment by wiwei** [comment]
Out of curiousity, do you have XR remoting enabled in the Unity player settings? A while back there were questions where folks were hitting something similar on Slack, and oddly enough it came down to some folks who had the XR remoting setting enabled.

**Comment by krishnan-unni** [comment]
@wiwei, no I have not enabled the holographic remoting.

**Comment by Yoyozilla** [comment]
@krishnan-unni did the issue resolve with holographic remoting enabled?

**Comment by krishnan-unni** [comment]
@Yoyozilla Im not at home. I'll test and update once I'm back this week.

**Comment by devedse** [comment]
Hi @wiwei , haven't really looked at this thread for a while now. But I was wondering if things have changed already in regards to what version of the MRTK I should use. Should I already start using the latest release on github?: Microsoft Mixed Reality Toolkit v2.0.0 RC2.1 or should I stay with HoloToolkit 2017.4.3.0 - Refresh?

**Comment by Troy-Ferrell** [comment]
@devedse, looking at the issues filed here, I believe they all should be fixed/covered with latest MRTK. 

RC1/RC2.1 are pretty old now with MRTK 2.1 officially released. Can you please download latest and try your process again? 

If you run into any problems, please file a new issue
