### ISSUE TITLE
Loading UX: Indeterminate loader

### ISSUE THREAD

**Issue by radicalad** [microsoft/MixedRealityToolkit-Unity#4408]
## Describe the problem
Looking through our list of UX controls, we currently have no loading state.

## Describe the solution you'd like
We should have a Loader library. Both simple indeterminate loaders as well as loaders that use the scene transition service.

## Additional context
This is a gap from HTK UX.

**Comment by radicalad** [comment]
Closing old issue.

**Comment by cre8ivepark** [comment]
Merged.
