### ISSUE TITLE
[MRTK Shell Parity] [Fingertip visualization] Match the final shell design spec. (distance, ring size, alignment behavior)

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#4411]
Part of #4200 UX Controls Parity with HoloLens 2 Shell

**Comment by cre8ivepark** [comment]
@Cameron-Micka Could you please take a look at the latest shell and tweak the values to match?

**Comment by Cameron-Micka** [comment]
Certainly! I might be low on time until late June. But, I would love to "fix" this.

**Comment by ADP-JoNeff** [comment]
Note: Still need to tune the sizing of the ring relative to distance

**Comment by cre8ivepark** [comment]
Completed with #4836 
@ADP-JoNeff Please re-open & submit PR if you see any additional tunning is needed.
