### ISSUE TITLE
Visual Profiler Warning in Player Builds

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#4414]
## Describe the bug

In player builds this warning is reported in the Unity.log: "A shader supporting instancing could not be found for the VisualProfiler, falling back to traditional rendering. This may impact performance."

## To reproduce

Play a scene with the Visual Profiler in use and check the Unity.log

## Expected behavior

The VisualProfiler finds a shader to utilize instanced and improve rendering performance.

**Comment by Cameron-Micka** [comment]
Fixed in this PR: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4388

**Comment by keveleigh** [comment]
Fixed via #4388
