### ISSUE TITLE
[MRTK Shell Parity] [Bounding Box] Handles should be scaled up on hand proximity

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#4415]
Part of #4200 UX Controls Parity with HoloLens 2 Shell

**Comment by julenka** [comment]
@cre8ivepark  I think you could actually create an Interactable theme that will scale the handles on hover, I think it could be done all in design, no need for code modification.

**Comment by keveleigh** [comment]
@danielescudero had a similar request recently, as far as highlighting the handles on proximity.

**Comment by cre8ivepark** [comment]
PR in-progress as of 7/15

**Comment by julenka** [comment]
merged!
