### ISSUE TITLE
MRTK assemblies are built against the "split" Unity assemblies

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4440]
Ported to Github, reference 21543183

MRTK assemblies are built against the split Unity assemblies, such as UnityEngine.CoreModule.dll. I believe these are only supposed to be used at runtime so that Unity can load smaller assemblies. At compile time, it seems that the intention is that you reference the top level UnityEngine.dll. The following pages suggest this is the case:

https://docs.unity3d.com/Manual/UsingDLL.html
https://forum.unity.com/threads/unityengine-dll-vs-unityengine-coremodule-dll-unityengine-animationmodule-dll-etc.509478/

This is what we did in MRW, but what that means is that our code thinks things like MonoBehaviour is the type defined in UnityEngine.dll, while MRTK code thinks it is defined in UnityEngine.CoreModule.dll, which at compile time are effectively two different types, which makes MRTK code incompatible with MRW code when compiling from the context of MSBuild.

I believe the right change here is to ensure that MRTK is built against UnityEngine.dll.

**Comment by Yoyozilla** [comment]
high priority for MRW.
MRTK can be used in individual apps, but this blocks building a shared tech for all apps to consume.

Need to find an owner to address this week. (david/Nial are the expert here)

**Comment by Yoyozilla** [comment]
@davidkline-ms Let's chat today, may be a dependency related change

**Comment by davidkline-ms** [comment]
I am not familiar with our nuget package build system enough to spot the changes that need to be made.

Assigning @andreiborodin and @MenelvagorMilsom who should have a better understanding.

**Comment by Yoyozilla** [comment]
fixed.
