### ISSUE TITLE
Solver documentation is sparse

### ISSUE THREAD

**Issue by ritijain** [microsoft/MixedRealityToolkit-Unity#4444]
## Describe the Issue
Solver model is too convoluted for ease of understanding, and the documentation doesn't help.

## Feature Area
It is hard to leverage the Solver script, and its implementations.
1. Some of the solvers exhibit too many settings. The tooltips on those are not very helpful and can be more descriptive.
2. It would be great if the Solver implementations that come with MRTK have separate documentation pages. The number of settings exposed in them can be a little overwhelming and not all settings inherited from SolverBase.cs are applicable to all types it seems. 

A little more focus on usage of the scripts rather than intent would be helpful. 

## Existing Doc Link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_Solver.html

**Comment by ritijain** [comment]
@gejohnst  - I believe you are addressing some of these issues?

**Comment by ritijain** [comment]
Related - https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4675

**Comment by wiwei** [comment]
Assigning to @gejohnst because he's working on some runtime-programmability of solvers and solver documentation.
