### ISSUE TITLE
Tooltips rendering grey plane in scene

### ISSUE THREAD

**Issue by davidraguilar** [microsoft/MixedRealityToolkit-Unity#4447]
## Describe the bug

When using any of the ToolTip prefabs, a grey plane is displayed in the scene rendering the tooltips useless. It works fine when playing the scene in the editor, but broken when testing on device. This happens when using tooltips in a custom scene as well as when testing the TooltipExamples demo scene in the MRTK examples.

## To reproduce

1. Load TooltipExamples demo scene found here: MixedRealityToolkit.Examples/Demos/UX/Tooltips/Scenes/TooltipExamples.unity
2. Build
3. Deploy to device and start app
4. See grey plane

## Expected behavior

Regular tooltip functionality without the grey plane

## Screenshots

![20190517_004015_HoloLens](https://user-images.githubusercontent.com/1686969/57912300-d5b19000-783e-11e9-9e1c-fb203b7cde15.jpg)

![20190517_003950_HoloLens](https://user-images.githubusercontent.com/1686969/57912328-e6fa9c80-783e-11e9-841c-650356aa8e52.jpg)

![20190517_003929_HoloLens](https://user-images.githubusercontent.com/1686969/57912346-ea8e2380-783e-11e9-9f00-051ae916d23a.jpg)

## Your Setup (please complete the following information)

- Unity Version 2018.4.0f1, 2018.3.14f1
- MRTK Version v2.0.0-RC1-Refresh

## Target Platform (please complete the following information)

- HoloLens

**Comment by Railboy** [comment]
@wiwei I've been discussing this with @cre8ivepark and we should probably elevate to a GA blocker.

**Comment by cre8ivepark** [comment]
@wiwei Added GA block label since the functionality is broken and not usable.
