### ISSUE TITLE
Teleportation for the HoloLens experience

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#4451]
## Describe the problem
In HoloLens experience, there are situations that require movement inside a large object. (e.g. immersive view of architecture model). Moving camera is not recommended which can cause motion sickness. Need a way to support MRTK's existing teleportation(point destination and commit, fade transition) in the HoloLens apps too. 

## Describe the solution you'd like
We could use hand ray with the parabolic pointer when pointed the teleportable floor area. 

## Additional context
Partner requests

**Comment by polar-kev** [comment]
As of MRTK 2.6, gesture teleport is supported on all platforms.

MRTK 2.6 release notes:
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/release-notes/mrtk-26-release-notes#teleportation-with-the-teleport-gesture-now-supported-on-all-platforms
