### ISSUE TITLE
Configuration profile inspector doesn't constrain profile types for camera and diagnostics systems.

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedRealityToolkit-Unity#4452]
## Describe the bug

When selecting profiles for the camera system and diagnostics system the object picker doesn't constrain available profile types.

## To reproduce

- Select a MixedRealityToolkit instance
- Try to select a CameraSystem profile
- Observe that all scriptable objects are available

## Expected behavior

Profiles should be constrained to service type.

## Your Setup

- MRTK Version 2.0 mrtk_development

**Comment by Troy-Ferrell** [comment]
Harden MRTK inspectors & increase re-usability of code #4467
