### ISSUE TITLE
Feature Request: Assign services an auto-incremented ID so they're easier to track

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedRealityToolkit-Unity#4454]
## Describe the problem

It can be hard to tell which instance of a service you're dealing with when debugging.

## Describe the solution you'd like

An auto-incremented ID would make it easier to verify / track the identity of a service instance.

Since this ID would only be used for diagnostics we could add the property to `BaseCoreSystem` or even `BaseService` instead of `IMixedRealityService` to avoid a breaking change, and assignment could happen inside the constructor.

**Comment by davidkline-ms** [comment]
Interesting thought. How do you suggest ensuring a consistent auto-incrementing value in scenarios where there is not a single registrar?

**Comment by Railboy** [comment]
@davidkline-ms Huh good question. I'll have to think about it.

**Comment by Railboy** [comment]
@davidkline-ms On reflection I don't think the registrar should assign the ID. I think the base core system should handle this in its constructor. That would reinforce the notion that this is not considered a dependable system-wide ID. What do you think?

**Comment by SimonDarksideJ** [comment]
I take it this is an artifact of the multiple instances change.  In the single instance, service ID isn't an issue as the majority of services are singular and accessed from the registry via its interface.

For the multi-service registry, it's up to the developer to manage them how they see fit.

**Comment by Railboy** [comment]
>I take it this is an artifact of the multiple instances change.

@SimonDarksideJ No, multiple instances don't change registration behavior. Each instance just acts as a 'terminal' for interacting with a shared set of services.

This has more to do with services being rapidly torn down and recreated before scripts have a chance to react. Example:

- Service 1 initialized in state X
- Script A subscribes to a Service 1 event that fires when service enters state Y
- Service 1 enters state Y, fires off event
- Something causes Service 1 to be torn down, Service 1 is re-initialized in state X
- Next frame, Script A reacts to Service 1's event, but service is no longer in relevant state Y
- Confusion!

Not super common, and not usually fatal when it happens, but a debugging aid would be nice.

**Comment by Railboy** [comment]
After a couple of experiments I can only see this leading to further confusion. Closing for now.
