### ISSUE TITLE
Xbox Controller ManipulationHandler Using Bumpers should move object forward / backward

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4469]
In the Mixed Reality Shell, using a gamepad controller has the following behavior:

- Joystick moves the object up/down/left/right in camera space
- Bumpers move the object forward/back
- Object can be rotated using secondary bumpers

After #4398 the gamepad will move the object up/down/left/right in camera space, but will not move it forward/backward or rotate the object in camera space.

We should either create a new component "GamepadManipulation", or add functionality to ManipulationHandler, to match the shell.

**Comment by polar-kev** [comment]
In MRTK v3, xbox controllers can move, rotate and pinch objects.
