### ISSUE TITLE
Vive Pro Defaults OpenVr Generic Device causing one hand operation errors due to missing Spatial Grip Input Action

### ISSUE THREAD

**Issue by JShull** [microsoft/MixedRealityToolkit-Unity#4470]
## Describe the bug
When using the default MRTK profile provided with Vive Pro hardware you cannot use one hand interactions with the controllers.

## To reproduce
**This happens when using Vive Pro hardware**
1.) SteamVR added to the Project
2.) Make sure you have all of the other XR settings on as suggested by the generic toolkit setup.
3.) Run the HandInteractionExample scene and try to pick up an item with one controller
4.) Error 'InvalidOperationException': Sequence contains no matching element' --> ManipulationHandler.cs the line in the code that generates the error is 
`return controller.Interactions?.First(x => x.InputType == DeviceInputType.SpatialGrip);`

## Expected behavior

I would expect the one hand interaction to work with the trigger as I am using the default provided MRTK profiles.

## Screenshots
Slack thread image of the error --> https://holodevelopers.slack.com/files/U8RDSPJR3/FJT9YB71N/image.png

## Your Setup (please complete the following information)

- Unity Version 2019.1.3f1
- MRTK Version 2.0.0-RC1

## Target Platform (please complete the following information)

-Windows Standard Build
- OpenVR
-Vive Pro Hardware
## Additional context
**Solution**
One solution, update the Generic Open VR Left/Right Hand Controller Input Action Assignment to include _Spatial Grip_
Slack thread solution--> https://holodevelopers.slack.com/files/U8RDSPJR3/FJTJXBBEU/inputactionupdate.png

**Comment by wiwei** [comment]
Closing this one out now that it's been merged
