### ISSUE TITLE
[MRTK Shell Parity] [AppBar] Add carry mode button

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#4472]
Part of #4200 UX Controls Parity with HoloLens 2 Shell

**Comment by cre8ivepark** [comment]
duplicated

**Comment by wiwei** [comment]
Closing out GA epics

**Comment by cre8ivepark** [comment]
![MRTKv2_AppBar3](https://user-images.githubusercontent.com/13754172/150285825-7e1f65ad-e8fb-44da-b80d-b03cf159c38c.gif)
