### ISSUE TITLE
Handler for gesture events with data receives events with no data

### ISSUE THREAD

**Issue by luis-valverde-ms** [microsoft/MixedRealityToolkit-Unity#4477]
## Describe the bug

`IMixedRealityGestureHandler<T>` derives from `IMixedRealityGestureHandler` causing it to receive events (calls to the base interface methods) for gesture events with no data. We should do the same we do for the `IMixedRealityInputHandler` interface and keep the two versions separate.

## To reproduce

1. Add a cube with a `GestureTester` script to an empty scene setup for MRTK
2. Set Hand Simulation Mode to 'Gestures' in the Input Simulation Settings profile 
3. In play mode, focus the cube and left click while pressing space. Observe how `OnGestureStarted` in `GestureTester` is called with a gesture event with no data even though it is a `IMixedRealityGestureHandler<Vector3>`

## Expected behavior

Gesture handlers for specific data types should only receive events of those types.

**Comment by wiwei** [comment]
@luis-valverde-ms would this involve a breaking change in order to fix this?

**Comment by luis-valverde-ms** [comment]
As far as I can tell there will be two breaking changes:

1. We'll be modifying a behavior someone may have taken a dependency on. Benefit outweighs risk here for me.
2. First solution that comes to mind involves adding new methods to IMixedRealityInputSystem for RaiseGestureStarted and RaiseGestureCanceled which will break existing input system implementations. I don't think there are many custom input systems around and the breakage would be easy to spot (build error) and fix.

**Comment by luis-valverde-ms** [comment]
Oh, importantly, I forgot:
3. Implementations of IMixedRealityGestureHandler<T> will be broken as well (methods added and removed).

**Comment by luis-valverde-ms** [comment]
@wiwei , unless you think otherwise, I'm going to move this out of GA because of the extent of the breaking changes and the fact that it can be worked around by checking the event data type. E.g. if you have a `IMixedRealityGestureHandler<Vector3>`, you can do:

```
public void OnGestureStarted(InputEventData baseEventData)
{
	var eventData = baseEventData as InputEventData<Vector3>;
	if (eventData != null)
	{
		//...
	}
}
```
