### ISSUE TITLE
ScriptableObject serialization error reported in player

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedRealityToolkit-Unity#4479]
## Describe the bug

Dev console in player reports ScriptableObject serialization error.

## To reproduce

- Build MRTK project with the Development Build option checked.
- Run built app.
- Observe error in dev console.

## Screenshots

![SerializationError](https://user-images.githubusercontent.com/9789716/58040627-c35b7e80-7aea-11e9-9a66-583e861c728d.PNG)

This looks like an incorrect diagnosis since MixedRealityInputSimulationProfile has no `#if UNITY_EDITOR` blocks.

## Your Setup (please complete the following information)

- Unity 2019.1.1.
- MRTK Version 2.0 mrtk_development

**Comment by genereddick** [comment]
Also #3971 if you want to consolidate

**Comment by keveleigh** [comment]
Duplicate of #3971
