### ISSUE TITLE
Can't build UWP APPX from MRTK Build Window in Unity

### ISSUE THREAD

**Issue by olga-microsoft** [microsoft/MixedRealityToolkit-Unity#4485]
## Describe the bug

Can't build UWP APPX from MRTK Build Window in Unity

## To reproduce

1. Create a new project and import MRTK; go to MRTK Build Window
2. Click on Unity Build Options and build
3. When build succeeds click on 'Build Appx' in the dialog
4. See error: The specified solution configuration "master|" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties
5. Change configuration to Release
6. See error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.Cpp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

## Expected behavior

Expect the project to build and manage own dependencies or be clear if a dependency is missing
Expect MRTK to not contain build configurations that are not supported

## Your Setup (please complete the following information)

- Unity Version 2018.3.11f1
- MRTK Version v2.0-RC1-Refresh

## Target Platform (please complete the following information)

- UWP/APPX

**Comment by wiwei** [comment]
We can fix this up - note that you can still use the Unity build window to build the VS solution, and then open up that solution in visual studio to deploy to the device

**Comment by gilbdev** [comment]
sure works by hand, but this comes to be problematic when using automatic build step in command line.
