### ISSUE TITLE
MRTK NuGet package should provide a simple debugging solution

### ISSUE THREAD

**Issue by ericob** [microsoft/MixedRealityToolkit-Unity#4486]
(ported to github, reference 21556516)

If you consume MRTK via NuGet and need to debug, there doesn't seem to be a straight forward way to do this. We need an easy way to access both the debug symbols and the source. One option would be to just embed the symbols and source in the package. It might also be possible to leverage source linking.

Even if we don't use source linking, we should ensure the repo url and commit id are included in the package metadata. This last part can easily be achieved by putting tokens in the nuspec files for repo url and commit id, then passing those in as parameters in the build definition.

@ryantrem can provide more context

**Comment by Yoyozilla** [comment]
One of the top issues from MRW. 

@niallatms  can we short term index the symbols as a build step in CI.

Long term we should have a solution that can enable debugging without bloating the size of the packages.

**Comment by MenelvagorMilsom** [comment]
@Yoyozilla I think this is more Andrei's area of expertise. I'm going to reassign to him.

**Comment by Yoyozilla** [comment]
Fixed
