### ISSUE TITLE
When upgrading the MRTK nuget package or local version of the MRTK souce, previously defined custom profiles are no longer identified or visible for selection

### ISSUE THREAD

**Issue by ericob** [microsoft/MixedRealityToolkit-Unity#4488]
Ported to github, reference 21424435

Right now, if you create custom profiles in MRTK  and bring in a new version of the nuget package, it no longer recognizes previously-defined profiles.

MRTK Nuget Versions (2.0.0-190425005/2.0.0-190425007)

Repro Rate (60-80%)

Repro Steps:
Create a test project and pull in the MRTK nuget package (not through the Unity Nuget tool).
Then create several custom profiles based on the default profiles. Afterwards, modify several properties within them.
Then, close Unity and update the nuget package to a newer version and bring it into the project. 
Open the project again, and try to find the custom profiles that were previously defined.
Observations:
 
-It seems like the BaseMixedRealityInspector isn't seeing them when the GetProfileTypesForService function is called. 
-I looked at a diff between my old profile and the new one I was forced to generate (an hour later), and it seems like they're different. When I then create a new new profile (new profile #2}, the GUIDs are the same; making me assume that the GUID lookup might be causing this behavior to occur.

**Comment by Yoyozilla** [comment]
Sending this back to MRW to check for repro
