### ISSUE TITLE
Cloning items and saving prefabs periodically causes file lock errors to pop up in Unity. 

### ISSUE THREAD

**Issue by ericob** [microsoft/MixedRealityToolkit-Unity#4489]
Ported to github, reference 21413012

When cloning items, or saving prefabs, periodically an error stating "Saving from <TempPath>\RandomUnrelated.pfb to <LibraryPath>\RandomUnrelated.pfb failed". This is more easily reproable when cloning profiles based on the default profile (though I also suspect that this is enabled even further by having a project where a lot of editor script modifying files are running). It seems to be related to the nature of the editor scripts running in background that modify prefabs periodically and saves them.

MRTK Nuget version:
2.0.0-190425005

Repro Rate:
30%-50%

Repro Steps:
Open a larger project (preferably not a sample project or an empty one) and bring MRTK in; and add it to the main scene. This repros quite a bit in the RA project, so using that might be a good idea when trying to repro.
Use the default settings at first, and then try to clone the main MRTK profile to generate a custom one.
Watch the gears spin as it tries to do so when contested for editor resources. Eventually, an error similar to the one below might appear in relation to a prefab or dll:
![image](https://user-images.githubusercontent.com/1052073/58056872-8d80bf00-7b17-11e9-8d7b-024170ef02d0.png)

**Comment by wiwei** [comment]
Ah, it turns out we ported this already (https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4420)
