### ISSUE TITLE
[nuget] configuration profile UI missing default types when consuming MRTK as nuget package

### ISSUE THREAD

**Issue by naostranMS** [microsoft/MixedRealityToolkit-Unity#4491]
## Describe the bug

When consuming MRTK as a nuget package, the configuration profile inspector doesn't seem to be able to locate the default MRTK system types (e.g. MixedRealityCameraSystem) and so the dropdowns are not populated.

## To reproduce

1. Create a new project, and add MRTK as a nuget package.
2. From the MRTK menu -> Add to Scene and Configure
3. Clone the MRTKConfigurationProfile
4. Select the Camera configuration and clone it
5. Note that Camera System Type is "MixedRealityCameraSystem {Missing}"
6. Click "Try Repair" -> error "No types with the name 'MixedRealityCameraSystem' were found"
7. Try to select a type with the dropdown -> "None" is the only option

This also happens with input providers in the input system configuration (and probably others, but those are all I've tried).

## Expected behavior

Default/built-in MRTK system types are selectable through the configuration profile inspector.

## Screenshots
![image](https://user-images.githubusercontent.com/38891743/58059890-b1e29880-7b23-11e9-9ff2-f921e0877d47.png)
![image](https://user-images.githubusercontent.com/38891743/58059911-c7f05900-7b23-11e9-8614-132aac878093.png)
![image](https://user-images.githubusercontent.com/38891743/58059933-e3f3fa80-7b23-11e9-94fd-500f777f9c85.png)

## Your Setup (please complete the following information)

- Unity 2018.4.0f1
- Microsoft.MixedReality.Toolkit/2.0.0-20190517.1

## Target Platform (please complete the following information)

- Unity editor

**Comment by Yoyozilla** [comment]
blocks nuget consumption

**Comment by MenelvagorMilsom** [comment]
@Yoyozilla I think this is more Andrei's area of expertise. I'm going to reassign to him.
