### ISSUE TITLE
can not see any thing whitout cursor.

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#4494]
## Describe the bug
It's ok when unity remote connected hololens, but i can not see any thing after deploy to hololen
 

## To reproduce

1.Build scene InputManagerTest by unity Build;
2.visual studio open genereated .sln file;
3.deploy to hololens by USB;
4.open app in hololens but I can not see anything whitout cursor;

 

## Screenshots
![image](https://user-images.githubusercontent.com/38685433/58072754-3fc98c80-7bd3-11e9-9666-c112f6141660.png)

![image](https://user-images.githubusercontent.com/38685433/58072767-4b1cb800-7bd3-11e9-9ac7-ccc9159ddd75.png)

![image](https://user-images.githubusercontent.com/38685433/58072784-5d96f180-7bd3-11e9-8881-5882c1232270.png)

 
![image](https://user-images.githubusercontent.com/38685433/58072737-33453400-7bd3-11e9-9645-82c12633019d.png)

![image](https://user-images.githubusercontent.com/38685433/58072702-19a3ec80-7bd3-11e9-90e9-e1dcf8d2e296.png)

## Your Setup (please complete the following information)

-Unity Version [e.g. 2018.3.12f1 ,2018.3.09f1 , 2018.4 ]
-HoloToolkit 2017.4.3.0 - Refresh

## Target Platform (please complete the following information)

- HoloLens

**Comment by Yoyozilla** [comment]
HTK requires Unity 2017.4

Closing older HTK issue as we are no longer actively working on HTK.

Please upgrade to MRTK V2 for the latest fixes.

**Comment by keveleigh** [comment]
In your second screenshot, you should uncheck "WSA Holographic Remoting". That fixed this issue for a couple others.
