### ISSUE TITLE
MRTK Demo Scenes not preconfigured with Profiles

### ISSUE THREAD

**Issue by SarahSexton** [microsoft/MixedRealityToolkit-Unity#4496]
## Describe the bug

Opening any MRTK v2 Eye Tracking example demo scene, (reproducible with the Assets/MixedRealityToolkitExamples/Demos/EyeTracking/Scenes/mrtk_eyes_02_TargetSelection.unity, or MRTK_eyes_03_Navigation.unity, or any other demo scene) opens a dialog that says "No Active Toolkit Found." You must select the correct Configuration Profile for the Eye Tracking scene, in this case, "EyeTrackingDemoConfigurationProfile," if it is in the list. If it is not in the list, you can clone a preconfigured Default configuration, but with this configuration, the scene will not build to a working demo, because the configuration does not fulfill all requirements. 

## To reproduce

1. With Unity Hub, create a New Project, name it and give it a location, select Unity 2018.3.14f1
2. Import the MRTK v2 Foundation as a custom package (v2.0.0-RC1-Refresh) 
3. Import MRTK v3 Example as a custom package (v2.0.0-RC1-Refresh)
4. Navigate to Assets/MixedRealityToolkitExamples/Demos/EyeTracking/Scenes and open "mrtk_eyes_02_TargetSelection.unity"
5. Press the import button on the dialog about Text Mesh Pro
6. See error dialog about "No Active Toolkit Found" "There is no active Mixed Reality Toolkit in your scene. Would you like to create one now?" 
7. You must circle-select a Configuration Profile that is the correct profile for your scene, in this case "EyeTrackingDemoConfigurationProfile," if it is in the list. 
8. Alternatively: If the MRTK v2 packages are imported in the wrong order (Examples before Foundation), the profiles will not show up in this list. Then the developer must clone and configure a new Input System Settings / Input System Profile.

## Expected behavior

Mixed Reality Toolkit should already be in the Eye Tracking demo scenes with "EyeTrackingDemoConfigurationProfile" already configured.

## Screenshots

![image](https://user-images.githubusercontent.com/8670346/58086103-4ac5f200-7bbe-11e9-9d9a-6e1914274758.png)

## Your Setup

- Unity Version: 2018.3.14f1
- MRTK Version: v2.0.0

## Target Platform

- HoloLens 2

**Comment by wiwei** [comment]
I don't think that any of the eye scenes #1-5 are designed to actually be opened up directly themselves, and that this is an artifact of the level of support for multi scene work.

@sostel, I believe the only supported way of using these scenes is to open the root scene. Can you comment on what you expect here? We should have a README in this folder (in addition to some doc updates here) to give some instructions on how to use these scenes.

**Comment by keveleigh** [comment]
This is by design. There's a base ET scene, while the rest are designed to be loaded additively. This information can be found in the ET Examples documentation: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/EyeTracking/EyeTracking_ExamplesOverview.html#setting-up-the-mrtk-eye-tracking-samples

**Comment by sostel** [comment]
+1 to what Kurtis said. 
It would probably be good to add some info text that is only rendered in the Editor to let the user know to load the root scene. 
**Why did we do it like that?** This was mainly due to the circumstance that MRTK did not handle switching scenes using the default scene loader. Loading scenes additively worked though.

**Comment by sostel** [comment]
Checked again and single scene loading is still not supported. Please also see here: #4530

**Comment by sostel** [comment]
Just to conclude: The scenes are still set up as additive loading, but I've added some instructions to the sub scenes to make it more clear that the base scene has to be loaded. 

![image](https://user-images.githubusercontent.com/32180789/59124550-deb0f100-8914-11e9-9cd5-f8e15862a568.png)
