### ISSUE TITLE
WorldAnchor doesn't change GameObject location after load

### ISSUE THREAD

**Issue by sebastianpietraszek-wi** [microsoft/MixedRealityToolkit-Unity#4499]
## Description

The WorldAnchorStore doesn't seem to do anything. The related objects are not moving after loading the anchor from the store.

## To reproduce

1. Setup the environment (https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html)
2. Load HandInteractionExamples
3. Create new GameObject and add attached script (WorldAnchorsSetup) to it
4. Drag&drop Tree from the scene to WorldAnchorsSetup.theGameObjectsIWantAnchored
5. Setup events to Pressable Button 1, 2 (and optionally 3) to trigger WorldAnchorPersist: SaveAnchors, LoadAnchors (and optionally ClearAnchors)
6. Deploy app to HoloLens 1
7. Run the app and move the tree
8. Save the anchors (Pressable Button 1)
9. Restart the app
10. Load the anchors (Pressable Button 2)
11. Tree is still at it's starting position

## Expected behavior

I expect that after load the Tree should be relocated to the position that was set at previous instance of the app.

## Setup

- Unity Version: 2018.4.0f1
- MRTK Version 2.0.0-RC1

## Target Platform

- HoloLens

[WorldAnchorsSetup.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3203753/WorldAnchorsSetup.zip)

**Comment by Yoyozilla** [comment]
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4509 
Unity AnchorStore works apparently

**Comment by sebastianpietraszek-wi** [comment]
Ok. The problem was with spatial mapping.

In my case I had to:
1. Project Settings -> Player -> Publishing Settings -> Capabilities -> Spatial Perception
2. Build Settings -> Universal Windows Platform -> Minimum Platform Version 10.0.10586.0

The second one took me a while to figure out - my setting was 10.0.10240.0 on which spatial mapping is not supported.
