### ISSUE TITLE
HoloToolkit's StabilizationPlaneModifier does not exist in MRTK and the Porting Guide doesn't offer any guidance for replacing it

### ISSUE THREAD

**Issue by naostranMS** [microsoft/MixedRealityToolkit-Unity#4508]
## Describe the bug

We are currently using the StabilizationPlaneModifier provided in HoloToolkit, and it's not clear how to replace it as we transition to MRTK.

## Expected behavior

Either MRTK contains a version of StabilizationPlaneModifier, or the [Porting Guide](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/HTKToMRTKPortingGuide.html) gives an explanation of how it can be replaced.

## Target Platform

- HoloLens
- HoloLens 2
- WMR immersive

**Comment by Yoyozilla** [comment]
This should be replaced by SU soon!

**Comment by naostranMS** [comment]
@Yoyozilla What is SU?

**Comment by naostranMS** [comment]
@blgrossMS let me know that SU is Scene Understanding, which I don't think is applicable to stabilization plane.
That said, Blake also made some improvements to the stabilization plane code in Layout, which should probably be contributed back, so he will hopefully be following up about that.

**Comment by Yoyozilla** [comment]
@naostranMS edited, sorry mixed up the comment on two issues. This is not addressed by SU. We are evaluating if we need to add this for HL2, if you already have some code available to contribute, please open a PR and we'll jump on it!

**Comment by blgrossMS** [comment]
I recommend that MRTK just pull in the old HoloToolkit StabalizationPlaneModifier script at least. I can make a PR that brings it into MRTK. I made some changes as well that may be helpful.

**Comment by Yoyozilla** [comment]
@blgrossMS  please open a PR :)

**Comment by Troy-Ferrell** [comment]
@blgrossMS , do you still have that updated StabilizationPlaneModifer for MRTK v2 input etc?

**Comment by blgrossMS** [comment]
#4965 is the updated PR. Let me know if you have any feedback! Would be happy to update it

**Comment by Troy-Ferrell** [comment]
@blgrossMS awesome thank you!

**Comment by wiwei** [comment]
Should be resolved now thanks to @blgrossMS!

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4965
