### ISSUE TITLE
HoloToolkit's WorldAnchorManager does not exist in MRTK and the Porting Guide doesn't offer any guidance for replacing it

### ISSUE THREAD

**Issue by naostranMS** [microsoft/MixedRealityToolkit-Unity#4509]
## Describe the bug

We are currently using the WorldAnchorManager provided in HoloToolkit, and it's not clear how to replace it as we transition to MRTK.

## Expected behavior

Either MRTK contains a version of WorldAnchorManager, or the Porting Guide gives an explanation of how it can be replaced.

## Target Platform

HoloLens
HoloLens 2
WMR immersive

## Additional context

Admittedly WorldAnchorManager does not provide a lot beyond Unity's WorldAnchor/AnchorStore, but I think it does add a bit of convenience - and I think we'd end up duplicating/re-implementing some of the same code otherwise so it's nice to have it in shared code.

**Comment by sebastianpietraszek-wi** [comment]
Agree. I've been looking for WorldAnchorManager in MRTK Version 2.0.0-RC1 with no luck and found no info about what happened to it.

@naostranMS have you tested WorldAnchorStore in MRTK Version 2.0.0-RC1? Either I'm doing something wrong or it doesn't work.

**Comment by naostranMS** [comment]
@sebastianpietraszek-wi I haven't used WorldAnchorStore directly as we're still using HTK's WorldAnchorManager at the moment, but that does use Unity's WorldAnchorStore under the hood - as far as I can tell it is working fine still (on unity 2018.3.1f1 if that helps).

**Comment by Yoyozilla** [comment]
partner reported same thing

**Comment by sebastianpietraszek-wi** [comment]
@naostranMS are you working on MRTK Version 2.0.0-RC1?

**Comment by naostranMS** [comment]
@sebastianpietraszek-wi I'm working out of the mrtk_development branch on a commit from sometime last week iirc

**Comment by Yoyozilla** [comment]
They can still get the implementation copied from HTK, and it still works. However it is not available in MRTK v2 package. We can create a package to include this in MRTK v2 as a workaround for now. 

Step 2 is to clean this up and understand the story with AR Foundation and XR SDK in 2019

**Comment by Yoyozilla** [comment]
Urgency soon is only for getting this into MRTK v2 package or updating porting guide

**Comment by wiwei** [comment]
I've brought the class itself over, though with a few caveats:

Some things that were public/protected were made private. I wanted to go with the smaller API surface and then open things up as we got more information on what people needed, rather than blasting out with a larger surface without a good understanding of the needs.

So to this end, feel free to open other issues or PRs if we need to open up the visibility of some of the fields
