### ISSUE TITLE
[Cursor] No cursor displayed in HoloLens 1 (mrtk_development)

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#4510]
## Describe the bug
No cursor displayed in HoloLens 1. (for all gesture states idle, ready, air-tap)
The cursor only briefly shows up for the speech command "Select".

## To reproduce
1. Clone mrtk_development branch
2. Build and deploy HandInteractionExample scene

## Expected behavior
Proper cursor display

- Unity Version 2018.3.9f1
- MRTK Version mrtk_development branch (as of 5/21/2019)

## Target Platform (please complete the following information)
- HoloLens

## Additional context
This could be related to #4720

**Comment by wiwei** [comment]
@julenka

**Comment by julenka** [comment]
Looking at this now. It reproduces in editor, you just need to set the hand simulation mode to "Gestures"

![image](https://user-images.githubusercontent.com/168492/58200511-c93a9680-7c87-11e9-9294-8440de05e6c7.png)
