### ISSUE TITLE
[Cursor] Cursor does not represent proper input state

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#4511]
The cursor does not show proper input state visual on both HoloLens 1 and 2.
It seems like some of the updates in the input do not trigger a proper state change. (DefaultCursor prefab has not changed from HoloToolkit)

## Describe the bug
**HoloLens 1 (GGV)**
- Default: Dot cursor is displayed (OK)
- On hand detected (ready gesture): the cursor is updated to ring cursor (OK)
- On pinch: the cursor is updated to bigger dot (OK)
- On pinch release: the cursor is updated to ring (OK)
- **On source lost (move the hand out of GFOV): the cursor stays as ring cursor (BUG: Cursor should return to Dot)**

**HoloLens 2 (At the end of the Hand Ray)**
- Default hand ray: Dot cursor is displayed (OK)
- On pinch: the cursor is updated to dot (OK)
- **On pinch release: the cursor is updated to ring but a few seconds later, it changes to dot (BUG: Cursor should stay as a ring)**

## Expected behavior
HoloLens 1
![2019-05-21 17_34_44-YoonPark_UnityUniteBerlin2018_MixedRealityToolkit_20180621 pptx - PowerPoint](https://user-images.githubusercontent.com/13754172/58139315-0868d900-7bef-11e9-8c46-0557e3caa995.png)

HoloLens 2
Hand ray's default cursor should be a ring. On pinch = big dot.

## Blocking
Without the fix, it would be difficult to properly test out implementations for these items
#4418 and #4417 

## To reproduce
1. Clone mrtk_release branch (or download and import RC1 Refresh)
2. Build and deploy HandInteractionExample scene

## Target Platform (please complete the following information)
- HoloLens

**Comment by paco-ms** [comment]
Hi @cre8ivepark  - this bug is a regression I assume?

**Comment by MenelvagorMilsom** [comment]
@cre8ivepark I don't see any animation for the big dot for when pinching. Did this work before?

**Comment by cre8ivepark** [comment]
Merge
