### ISSUE TITLE
How to set Disable State of PressableButtonPlated at runtime

### ISSUE THREAD

**Issue by arunrajselvaraj** [microsoft/MixedRealityToolkit-Unity#4512]
## Describe the bug

Disable state of the button are not working. When PressableButtonPlated interactable.isenabled = false.  After applying this, when gaze/finger over the button front plate highlight get's active

## Expected behavior

Button shouldn't get highlight when it in disabled state. 

## Your Setup 

- Unity Version : Unity 2018.4 / 2019.1
- MRTK Version : v2

## Target Platform 

- HoloLens 2

## Additional context

Need additional documentation for adding different types of profiles to the PressableButtonPlated.

Thanks!

**Comment by thalbern** [comment]
HI @arunrajselvaraj ! If you want to disable the PressableButtonPlated (or any MRTK button) you have to not only disable the interactable but also set the enable flag on the PressableButton (or PressableButtonHololens2) component. That can be either done by unticking the box next to the component in the inspector:
![image](https://user-images.githubusercontent.com/36998103/60612673-18b0ce00-9dc1-11e9-9296-9303e0ed0ff0.png)

or in code by setting the enabled = false on the component.

Let me know if that resolves your issue.

**Comment by thalbern** [comment]
closing issue - pls reopen if provided solution doesn't work for you!
