### ISSUE TITLE
[MRTK Shell Parity] [Slate] Touch point affordance

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#4513]
Part of #4200 UX Controls Parity with HoloLens 2 Shell

**Comment by julenka** [comment]
@cre8ivepark are we done with this? Can we close it?

**Comment by cre8ivepark** [comment]
Merged into 2.0.0.rc2_stabilization
@julenka Yes! we have a separate item for the ring shadow. #4413
