### ISSUE TITLE
PressableButtonInspector marks the asset as "dirty" on every draw

### ISSUE THREAD

**Issue by lukastoenneMS** [microsoft/MixedRealityToolkit-Unity#4516]
## Describe the bug

The PressableButtonInspector flags the target asset as dirty in every OnInspectorGUI draw call:
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/9abf0a1eac906c7ffae688ffd5b5d125202f4ca7/Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/PressableButtonInspector.cs#L299

## Expected behavior

Inspector should only mark the asset dirty when it actually changes settings. Apart from that it is also recommended by Unity to use Undo.RecordObject instead: https://docs.unity3d.com/ScriptReference/EditorUtility.SetDirty.html

**Comment by lukastoenneMS** [comment]
This causes Unity to constantly save the scene while a button object is selected.

**Comment by kmoverall** [comment]
I have also seen this bug on all classes that use derivatives of the BaseLineDataProviderInspector (Base, Ellipse, Simple, ParabolicConstrained, ParabolaPhysical, Rectangle, Bezier, and SplineLineDataProviderInspector)

**Comment by Railboy** [comment]
@kmoverall @lukastoenneMS If you open a separate issue for the line classes I'll clean them up. They should be using callbacks.
