### ISSUE TITLE
build.ps1 build script not running locally

### ISSUE THREAD

**Issue by fast-slow-still** [microsoft/MixedRealityToolkit-Unity#4518]
## Describe the bug

Running the build script locally generates errors and fails to generate .unitypackage files.

## To reproduce

Here are full steps I took to perform the build:
1. Start from clean copy of mrtk_development branch.
2. Load project into Unity
3. Open HandInteractionExamples scene.
3.5 Import TextMeshPro Essentials
3.6 Restart Unity
4. Open File > Build Settings
5. Select:
a. Platform => PC, Mac, & Linux Standalone
b. Architecture => x86
c. All other settings default.
6. Hit Build button
7. Check that build completed successfully.
8. Change to:
a. Platform => UWP
b. Development Build check
c. Script Debugging check
9. Hit Build button
10. Check that build completed successfully
11. Run Assets > Retarget to DLL
12. Check that retarget completed successfully.
13. On command line, run powershell .\build.ps1 -OutputDirectory .\MyDir -Version 0.3.1 -UnityVersion 2018.3.7f1 >buildlog_0.txt

## Expected behavior

build.ps1 to run without errors, and generate .unitypackage and .nupkg files in MyDir.

## Actual behavior

See attached buildlog_0.txt. Errors generated for all .unitypackage output files, and NO .unitypackage files were generated. Also errors for the .nupkg files, but the .nupkg files were generated. Unfortunately, I can't currently consume the .nupkg files to verify that they were generated correctly.

## Your Setup (please complete the following information)

- Unity Version [2018.3.7f1]
- MRTK Version [mrtk_develop branch at commit 9abf0a1eac906c7ffae688ffd5b5d125202f4ca7]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

## Additional context

See attached logs. buildlog_0.txt is output from build.ps1. 

[buildlog_0.txt](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3207872/buildlog_0.txt)

Editor_bx86_buwp_retarget.log is Unity Editor log from session building the x86 standalone, the UWP solution, and then running the Retarget to DLL.

[Editor_bx86_buwp_retarget.log](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3207875/Editor_bx86_buwp_retarget.log)

**Comment by wiwei** [comment]
This file has been deleted, since we moved our scripting into YAML files on the build. For the nuget stuff some new stuff is coming.
