### ISSUE TITLE
SpeechInputHandlerInspector broken

### ISSUE THREAD

**Issue by lukastoenneMS** [microsoft/MixedRealityToolkit-Unity#4520]
## Describe the bug

The SpeechInputHandlerInspector does not show the keyword responses any longer, making it useless:
![image](https://user-images.githubusercontent.com/47210016/58187288-c4410b80-7cb6-11e9-9331-4fe471847c7f.png)

**Comment by lukastoenneMS** [comment]
Workaround: It seems that after opening a project i have to select the MixedRealityToolkit object at least once, so that MixedRealityToolkit.IsInitialized becomes true. After that the speech handler gui works fine.

**Comment by lukastoenneMS** [comment]
Similar issue with `MixedRealityInputAction` fields: They show up with a message: "Missing MixedRealityToolkit", fine after showing the MRTK object once in inspector.

**Comment by wiwei** [comment]
Closing this one out as fixed by #4661
