### ISSUE TITLE
Doc bug: The main page says Windows SDK "Fall Creators Update" and "18362+"

### ISSUE THREAD

**Issue by robertos** [microsoft/MixedRealityToolkit-Unity#4522]
## Describe the Issue
The main page says Windows SDK Fall Creators Update and 18362+. Those don't match - Fall Creators Update is 16299 and 18362 is the May 2019 update. One of those has to change to match the other.

## Existing Doc Link
Main page ([README.MD](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/README.md))

**Comment by keveleigh** [comment]
The statement is true, though the alignment with the SDK number is confusing.
The Fall Creators Update was the first update that added support for WMR immersive apps on desktop.
I'll add some clarifications.

**Comment by keveleigh** [comment]
Fixed via #4558
