### ISSUE TITLE
Hand Constained UI

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#4531]
## Describe the problem

Many users have requested guidance and examples of UI constrained to the articulated hands. This is an area which could include a lot of caveats and design guidance.

## Describe the solution you'd like

It would be great if the MRTK contained behaviors and examples to aide in development of hand constrained UI.

## Additional context

Many of the requests have come from partners and HoloLens 2 hacks.

**Comment by cre8ivepark** [comment]
Merged into 2.0.0.rc2_stabilization
