### ISSUE TITLE
Infinite loop caused by InscribedRectangle ctor

### ISSUE THREAD

**Issue by kircher1** [microsoft/MixedRealityToolkit-Unity#4541]
## To reproduce

This was reported by a customer, and means the following configuration occured:
1) Tracking space is room scale
2) UnityBoundary.TryGetGeometry returns true
3) The boundary point array is empty

When this happens, the do-while loop inside of the InscribedRectangle ctor never returns.

It should be straight forward enough to add some some input checking to prevent getting into this state. 

- Unity Version: 2018.3
- MRTK Version: RC1 Refresh

**Comment by keveleigh** [comment]
Fixed via #4550
