### ISSUE TITLE
[Question] Will MRTK support standalone VR headset running on Android?

### ISSUE THREAD

**Issue by ChauNTran** [microsoft/MixedRealityToolkit-Unity#4542]
Headset like Oculus Quest is running on Android and Open VR hasn't supported Android yet.
Is there any plan to have MRTK supported Android platform?

**Comment by keveleigh** [comment]
We just created a tracking issue for adding Oculus Quest support: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4549. We're definitely looking into supporting additional platforms!

**Comment by keveleigh** [comment]
Closing in favor of using #4549 to track this going forward.
