### ISSUE TITLE
Namespace EventSystem not found

### ISSUE THREAD

**Issue by MitchelKerckhaert** [microsoft/MixedRealityToolkit-Unity#4545]
## Describe the bug

I have been trying to get started with the MixedRealityToolkit-Unity and am noticing a bug in the setup process. After importing the MixedRealityToolkit 90+ compiler errors pop up. Most of them say "type or namespace 'Evensystems' could not be found", but it appears for other namespaces aswell like: BaseEventData, IEventSystemHandler, RaycastResult and a couple others. I am using Unity 2019.3.0a3 and have setup a project with buildsettings for the Hololens (v1)

## To reproduce

1. Create a new Unity Project.
2. Click on Assets -> Import Package
3. Import the MixedRealityToolkit.
4. See the errors pop up in the console.

## Expected behavior

The MixedRealityToolkit is loaded in Assets. A dropdown menu for the toolkit should appear (among other setting changes).

## Your Setup (please complete the following information)

- Unity Version [2019.3.0a3]
- MRTK Version [ v2.0.0-RC1-Refresh ]

## Target Platform (please complete the following information)

- HoloLens

**Comment by keveleigh** [comment]
>Unity Version [2019.3.0a3]

Our officially supported version is currently Unity 2018.3/.4. It's possible there are some breaking changes in Unity we'll need to account for when we add support for 2019.3, but we can't guarantee the MRTK will work in an alpha release of Unity.

**Comment by MitchelKerckhaert** [comment]
Ah, Thank you! The package is indeed not compatible with Unity 2019.3.x (yet), but after Installing the 2018.3.x version of Unity all problems were resolved.

**Comment by Kulanei** [comment]
Thanks for the answer ! I'll be using Unity 2018.3.x for the project, thanks for your time !

**Comment by jernkuan** [comment]
Does not work for 2019.2 as well. Would be good to keep this issue open, and maybe update the README.MD to indicate the range of Unity version that it would work.

**Comment by wiwei** [comment]
Closing this one out - we're clear in our getting started about using 2018.4.x, and we can update this when we've done the 2019.3 reconciliation
