### ISSUE TITLE
Add Oculus Quest Support for MRTK 

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4549]
## Overview
Oculus Quest is a great wireless VR experience that has potential to be adopted en masse by consumers. It would be great if MRTK could support this platform, to enable developers to build applications that can reach a broad audience.

## Expected Behavior
Oculus would be supported either through the OpenVR data provider. Since Oculus Quest is an Android platform, the MRTK project needs to compile and deploy for Android. Finally, we need to add a controller mapping and type for the oculus quest controllers to appropriately map the inputs. We may actually be able to re-use the oculus touch controller mapping.

**Comment by SimonDarksideJ** [comment]
SO to be clear from a deployment approach.  The Oculus devices will support OpenVR for sideloading, as such the MRTK (WIth the Android / OpenVR controller support) should support this out of the box.

However, in order to publish to the Oculus store, the MRTK will also require native Oculus support with the Oculus APIs in an extension.

**Comment by ChauNTran** [comment]
@julenka Support for Oculus Quest would be awesome. Is there an estimated time when this will be added into mrtk?

**Comment by julenka** [comment]
Hi, at this time we don't have an estimate for when our FTEs will get to it, our team is currently focusing on increasing quality of existing features before tackling new ones. However, community contribution would be very welcome here! I'd be happy to take a look at any PR adding Oculus Quest support.

**Comment by julenka** [comment]
Early version of Oculus Quest support for MRTK created by contributor tattichan from HoloLab [twitter](https://twitter.com/Ash_Yin/status/1146851771668545539) and [github repo](https://github.com/tattichan/MRTKForOculusQuest-Trial).

**Comment by julenka** [comment]
No ETA yet on official support from Microsoft, referring to @wiwei  and @chbecker-ms who can provide info about official support.

**Comment by SimonDarksideJ** [comment]
XRTK is currently in the process of publishing it's native Oculus support (Rift / Quest) which is what tattichan work is based on.  Once it's got past the extension review process, it should land fairly quickly after that.

**Comment by wiwei** [comment]
Keeping the discussion focused to what's being worked on this repo - we're currently acquiring some devices and looking to schedule time in our upcoming iteration to add this support.

**Comment by SiriusA7** [comment]
Hand tracking is coming to oculus Quest early 2020!

https://youtu.be/2VkO-Kc3vks

Would be awesome to use MRTK hand tracking on Quest and HoloLens 2!

Is there any overall status update on MRTK Quest support?

**Comment by Alexees** [comment]
I also have a working state with both Oculus Quest and Oculus Go now. Next up, teleport and manipulation-z-direction for the Go:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/32508825/68391306-99b11500-0167-11ea-9298-b08eeb8681ec.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/32508825/68391307-99b11500-0167-11ea-9e88-18c39a9a4d49.png)

I'm using parts of the Oculus Integration pack to get controller visuals, API calls and Gradle build modifications.

**Comment by SimonDarksideJ** [comment]
Something to be aware of @Alexees as this hit us in the XRTK.  Unity does not offset headset height for the Oculus platform through their app. This has to be grabbed from their API or estimated (like HL)

This is also true for OpenVR on the Quest or on PC when the Oculus client is used to host OpenVR (Instead of SteamVR)

This affects teleporting / head height.  And be careful, if you offset the head pose, this will NOT correspondingly alter the controller pose, they are handled separately.

**Comment by Alexees** [comment]
> This has to be grabbed from their API or estimated (like HL)

@SimonDarksideJ does a HL estimation algorithm exist?

**Comment by SimonDarksideJ** [comment]
Thoughts @davidkline-ms , on whether your current case of HL height offset could be used here?

My only concern with that (and the HL height offset) is it is a global settings, meaning your project either IS or is not a HL project and has to be manually set between builds.

We've taken an alternate approach in the XRTK to determine the setting is used only IF unity is not managing the headset height (as it does with WMR / OpenVR under Steam)

**Comment by SiriusA7** [comment]
[Hand Tracking is finally available on the Quest!](https://www.oculus.com/blog/thumbs-up-hand-tracking-now-available-on-oculus-quest/)

SDK is rolling out next week!

**Comment by RoyMudie** [comment]
Just wanted to make sure this great work by @tarukosu was linked to this issue as currently it looks like the best implementation we've got.

https://github.com/HoloLabInc/MRTKExtensionForOculusQuest

**Comment by Alexees** [comment]
Here is another one. Supports Go and Quest:
https://github.com/HoloSpaces/MixedRealityToolkit-Unity/tree/mrtk_oculusGo

**Comment by provencher** [comment]
@RoyMudie just want to chime in with my own implementation. It does not support Go, but it does support controllers, link, hands, and hotswapping input methods.

My work is built on the work of @tarukosu, though it does add a number of improvements.
https://github.com/provencher/MRTK-Quest

**Comment by RoyMudie** [comment]
@provencher @tarukosu 
https://forums.oculusvr.com/community/discussion/86022/quest-go-build-13-0-release-notes/p1 

I'm sure you've seen this, but just in case you haven't...

"Remote rendering support for Unity has been added so developers can more easily build and test Hand Tracking apps through their PC" 👍
