### ISSUE TITLE
InteractableColorTheme does not support TextMeshPro

### ISSUE THREAD

**Issue by killerantz** [microsoft/MixedRealityToolkit-Unity#4551]
## Describe the bug
InteractableColorTheme supports coloring UI Text and TextMesh components, but does not include support for coloring TextMeshPro objects.

## To reproduce

1. Create an empty with a collider and add the Interactable component.
2. Create a TextMeshPro object
3. Add the TextMeshPro object as a profile target on the Interactable
4. Add a theme that effects color, like InteractableColorTheme or ScaleOffsetColorTheme.
5. Observe that the theme displays the shader property dropdown "_Color", but TextMeshPro does not have a _Color property. It will cause an error when running and not update any colors.

## Expected behavior
The color themes should work on Text, TextMesh, TextMeshPro, TextMeshProUGUI, as well as renderers with materials.

## Screenshots

![image](https://user-images.githubusercontent.com/22085553/58294168-780cce80-7d7d-11e9-82f8-7eb84ca60c3a.png)

**Comment by cre8ivepark** [comment]
MERGED
