### ISSUE TITLE
slate sample interaction can't work on hololens 1

### ISSUE THREAD

**Issue by happyao** [microsoft/MixedRealityToolkit-Unity#4555]
## Describe the bug
can't not scroll the ContentQuad content on hololens1.

## Expected behavior

The ContentQuad content window can be scrolled via articulated hand input.

## Your Setup (please complete the following information)

- Unity Version 2018.3.14f1
- MRTK Version v2.0

## Target Platform (please complete the following information)

- HoloLens 1

**Comment by julenka** [comment]
Fixed by #4735
