### ISSUE TITLE
Prevent the player for moving and pass through colliders

### ISSUE THREAD

**Issue by lionrig** [microsoft/MixedRealityToolkit-Unity#4556]
## Overview
Hello, I have a problem. I would like to prevent the player for moving in certain moments, but I dont know how to do this or if there is a way to do that.
Another problem is that you can go though colliders because you move with teleport, so if you aim to a wall you wont move but if you aim to the wall bottom you will pass though

## Expected Behavior
Prevent the player for moving and prevent him to pass though walls
## Actual Behavior
Cant do this / Dont know how to do this
## Steps to reproduce
No steps.
For walking though a wall just aim to thw wall floor and you will pass though.
## Unity Editor Version
2019
## Mixed Reality Toolkit Release Version
v2.0 RC1 Refresh

**Comment by wiwei** [comment]
Super late response, but I think this would require updating the teleportation system yourself to factor in other surfaces when considering places to teleport. @davidkline-ms, is there any way to create surfaces that are teleportation-not-allowed? I'm curious if this could be marked this way, or if this is just something that could be done by also looking at teleport requests and seeing if they are too close to some other user-specified surface type.

**Comment by mishawagon** [comment]
Has this really  not been fixed in two years?

**Comment by Zee2** [comment]
We're using the built-in XRI locomotion system in MRTK3, which has support for all of this and more :)

https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@2.1/manual/locomotion.html
