### ISSUE TITLE
BoundingBox doesn't recompute bounds when boundsOverride is modified

### ISSUE THREAD

**Issue by lukastoenneMS** [microsoft/MixedRealityToolkit-Unity#4557]
## Describe the bug

BoundingBox reacts to transform changes of the Target object to recompute bounds. However, if a BoxCollider is used for boundsOverride to take the bounds values from, changes to the BoxCollider will not trigger a bounds update.

There is no equivalent "hasChanges" flag on BoxCollider, as there is on Transform (aside from the questionable practice of resetting the Target.transform.hasChanged flag from BoundingBox). Quick hack solution was to add a custom "HasDirtyBounds" flag that can be set externally to force a bounds update.

Problematic code:
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/47663d2a35becea2fd6db8b8cd4ec238507c3ad8/Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs#L485

## To reproduce

1. Open the HandInteractionExamples scene
1. Select one of the bounding box examples, e.g. "ActivateByProximityAndPointer"
1. Go into play mode
1. Press T to show the left hand, hold shift, move the hand over the object so the bounding box is shown
1. Select the scene tab so you can see the bounds
1. Change the scale of the target object, observe how the bounds adapt
1. Change the size of the box collider, observe how the bounds _don't_ adapt

## Expected behavior

BoundingBox also works with a boundsOverride collider set.

## Screenshots

Initial bounds:
![image](https://user-images.githubusercontent.com/47210016/58322551-8f9d9300-7e21-11e9-90b3-a347b3e6ef6f.png)

Changing Target transform works:
![image](https://user-images.githubusercontent.com/47210016/58322613-c1165e80-7e21-11e9-9937-5243e63eb669.png)

Changing BoxCollider size does not work:
![image](https://user-images.githubusercontent.com/47210016/58322649-e0ad8700-7e21-11e9-9b8f-07ab30093d0c.png)

**Comment by julenka** [comment]
How about the following solution approach: expose a method in bounding box "recalculate bounds" that would recompute the bounds? Whoever is changing the bounding box would need to call that method.

**Comment by hdaUwe** [comment]
> 
> 
> How about the following solution approach: expose a method in bounding box "recalculate bounds" that would recompute the bounds? Whoever is changing the bounding box would need to call that method.

This fixed art of the problem for me. I exposed UpdateBounds() and UpdateRigHandles() and call them, after my collider is done updating itself to the desired bounds. The next problem is, that my scaleHandles (not flattend) are now all rotated the same way.

![handleTwister](https://user-images.githubusercontent.com/12151775/59038806-ecfb0080-8873-11e9-82db-73c85e1d9096.PNG)

**Comment by hdaUwe** [comment]
Ok I fixed that to:
The BoxCollider (BoundsOverride) must be on the TargetObject.

**Comment by KarlSupertramp** [comment]
Simply disabeling the BoundingBox component, when changing the collider bounds, seems to work for me. So if anyone is looking for a quick workaround, just use ...

`boundingBox.enabled = true/false`

... while you're recalculating the collider.

**Comment by julenka** [comment]
merged.
