### ISSUE TITLE
Compressible button visuals tuning

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4562]
## Overview
- Scale the button visuals transform along Z as press depth changes.
    - Requires a ‘visuals depth’ or similar parameter to map press-depth to scale.
- Also ensure that the front plane of visuals is the point at which depressing begins.

Need to follow up with Joshua Neff for more explanation.

**Comment by ADP-JoNeff** [comment]
Closing dupe of this issue, #4978

**Comment by cre8ivepark** [comment]
Completed with #5168
