### ISSUE TITLE
Proximity Shader GlobalProximityAssigner should use point of interaction (pokepointer position) instead of fingertip joint

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4563]
## Overview
Bug #4559 says that the poke pointer position needs to actually be in front of the index finger slightly. We need to make the values that the finger proximity shader uses match the point of interaction, not the index finger position.

**Comment by Cameron-Micka** [comment]
I moved the Proximity Light to the cursor position which is slightly in front of the index finger in this PR https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4836 So, this should be fixed.
