### ISSUE TITLE
PressableButton back press logic prevents fast hands from pressing buttons

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4566]
## Overview
Modify back-press filter logic to work if interaction point enters press depth, without having entered interactable zone on a previous frame (touch has started on this frame), by storing and providing access to PokePointer’s previous position.  Might be able to pass the pointer single-frame velocity along with the input event to achieve the same thing.

**Comment by thalbern** [comment]
back press detection will already get the velocity of the controller to detect if we've missed one of the planes on touch start - though that velocity isn't set in all controllers and also the articulated hands are doing some smoothing/interpolation with the previous frame which can cause skipping over a plane again. I don't want to change how the velocity is determined in articulated hands as I'm not sure if that breaks other behavior so I'll go with previous position in poke pointer for now.
