### ISSUE TITLE
BoundingBox does not look at descendants when computing bounds

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4568]
## Overview
Bounding box only looks at its immediate children when computing its bounds, it does not look deeper in the hierarchy.

A good way to reproduce this is to modify the Gltf example at .\Assets\MixedRealityToolkit.Examples\Demos\Gltf\Scripts\TestGltfLoading.cs to the following (modify the Start method):

```
private async void Start()
{
    var path = $"{Application.streamingAssetsPath}{uri}";
    path = path.Replace("/", "\\");

    if (!File.Exists(path))
    {
        Debug.LogError($"Unable to find the glTF object at {path}");
    }

    GltfObject gltfObject = null;

    try
    {
        gltfObject = await GltfUtility.ImportGltfObjectFromPathAsync(path);
    }
    catch (Exception e)
    {
        Debug.LogError($"{e.Message}\n{e.StackTrace}");
    }

    if (gltfObject != null)
    {
        Debug.Log("Import successful");
    }

    if (gltfObject != null)
    {
        var bb = gltfObject.GameObjectReference.AddComponent<BoundingBox>();
        bb.BoundingBoxActivation = BoundingBoxActivationType.ActivateOnStart;
        bb.HideElementsInInspector = false;
    }
}
```

The bounding box will incorrectly create a bounds that does not encapsulate the lamp:

![image](https://user-images.githubusercontent.com/168492/58359557-e9f61e00-7e38-11e9-95f0-6e59f1df854b.png)

**Comment by StephenHodgson** [comment]
Is there a collider on the gltfObject? I'm honestly not sure if I wrote that into the mrtk version.

**Comment by julenka** [comment]
Hi, no there is not, one way to solve this problem would be to create a component that computes the bounds all child colliders and makes a collider on this component that matches the bounds.

However, then developers would need to know to use this component. We could also have the bounding box automatically create the component, but I'm not sure what benefit that would give.

Talking to two different people that were trying to use bounding box, their expectation was the bounding box would encapsulate all children without them needing to add a box collidable with the proper size. I think having bounding box automatically encapsulate all descendants is a reasonable behavior if there is not collidable present.

**Comment by Railboy** [comment]
@johnppella Correct me if I'm wrong but I believe this was by design.

The original bounding box did look at child objects, but we struggled to find a performant way to do it. We tried limiting depth, collider types etc but in we never quite cracked a generic solution. Every time we were close some weird edge case would blow it up.

One option is to use a SystemType field to choose a bounds encapsulation class. A default class could implement the current behavior. Then if devs need to encapsulate more complex objects they can write their own.

**Comment by julenka** [comment]
Thanks for that context @Railboy. It sounds like this is by design then, to avoid requiring bounding box to do potentially expensive recursive exploration of bounds. The solution then for people using GLTF would be to compute the bounds of the GLTF object themselves and then attach a boxcollider with those bounds to the root object (or point bounding box to a difference bounds override). Resolving as by design.
