### ISSUE TITLE
Create Hand Coach Prefabs to teach gestures / interactions

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4569]
## Overview
In OOBE and Learn Gestures app we have some nice 3D hand animations to teach people things like the system gesture, and suggest things like "press this button".

These hand coach prefabs could be helpful in teaching first time users how to interact with the mixed reality UI. The hand coach could also be useful for demonstrating hand movements when training workers, for example.

Here is an example of a hand coach module from the [MRDL Lunar Module project](https://github.com/Microsoft/MRDesignLabs_Unity_LunarModule):

![image](https://user-images.githubusercontent.com/168492/58362653-4c0d4e00-7e4e-11e9-9966-4bbe51630e7c.png)

As a first step we could provide pre-recorded 3D animations of hand movements for common motions like "press the button" or "grab the object". However, we could also create a way to record and serialize hand gestures, and then use these gestures in the hand coach.

**Comment by julenka** [comment]
I added the Epic label because I think it would be awesome to have this :-)

**Comment by julenka** [comment]
I would really like to have this for the next month if we can squeeze it in. Realistically though we have a pretty big number of bugs regarding bounding box and manipulation  handler that we need to fix so core dev team might not get to it. This is poachable / please feel free to help.

**Comment by polar-kev** [comment]
Hand coach has graduated from experimental to a full feature in MRTK 2.6
https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/hand-coach
