### ISSUE TITLE
Unity 2018.4.0f1+Vuforia MTG8.1.8+MRTK v2+Hololens1 How to start?

### ISSUE THREAD

**Issue by anranx** [microsoft/MixedRealityToolkit-Unity#4570]
## Overview
I am beginner in AR. Recently I want to using Unity 2018.4.0f1+Vuforia MTG8.1.8+MRTK v2+Hololens1 to recognize a real object.

## Expected Behavior
Using Unity 2018.4.0f1+Vuforia MTG8.1.8+MRTK v2+Hololens1 to recognize a real object.

## Actual Behavior
Vuforia Hololens Sample https://assetstore.unity.com/packages/templates/packs/vuforia-hololens-sample-101553 can be deployed and run successfully. But it is using HoloToolkit, now I am using MRTK, my project can be deployed in hololens but when I open this app, it is black...

## Steps to reproduce
First, I imported the .obj file to the Vuforia Model Target Generator(MTG) and download the dataset file .unitypackage to unity.
Secondly, I imported the MRTK example and foundation those two .unitypackages to unity.
Thirdly, I set the setting conditions followed the instruction https://microsoft.github.io/MixedRealityToolkitUnity/Documentation/GettingStartedWithTheMRTK.html and https://library.vuforia.com/content/vuforia-library/en/articles/Solution/model-target-test-app-user-guide.html.
Fourthly, I compiled it in vs2017 and deployed it in hololens.

The finnal result is the app icon can be see in hololens ,but it is show nothing when I open it. And there are some errors in Unity, such as:  Origin doesnt exist in target framework.It is referenced from MRTK..
I was wondering maybe there are some mistakes in Unity setting condition. But conditions in HoloToolkit and MRTK is different. So I dont know which step is wrong, MRTK or Vuforia AR camera setting?

## Unity Editor Version
Unity 2018.4.0f1 
Vuforia 8.1.11 Vuforia MTG 8.1.8
Windows SDK 10.18362/17134

## Mixed Reality Toolkit Release Version
MRTK v2

The main question is I was confused with so many software and their multifarious softwera vision.
I cannot find a Specific Tutorial for beginner. Is there a Specific Tutorial on how to recognize a 3D object by using the latest softwera vision? 
 Thanks a lot!

**Comment by samharper94** [comment]
There's a few issues and potential causes here, so let's go from the start

> But it is using HoloToolkit, now I am using MRTK, my project can be deployed in hololens but when I open this app, it is black

The first thing to check is on the build screen that you've actually added your scene properly (I miss this a lot). That's File>Build Settings then the box at the top of the new window should have your scene in it. If it doesn't, you can hit "Add Open Scenes".

Vuforia's documentation is (in my opinion) poor and the software can be full of errors that aren't immediately apparent. If you follow the MRTK setup in here then you're doing the right thing. For the camera for Vuforia, you can just add the Vuforia behaviour script to the camera.

Does that Vuforia package come with a version of MRTK/HoloToolKit? If so, use that, especially if it's HoloToolkit as trying to replace it is quite challenging.

Hope this helps.
