### ISSUE TITLE
How to make a basic button from scratch

### ISSUE THREAD

**Issue by Yoyozilla** [microsoft/MixedRealityToolkit-Unity#4571]
How to make a basic button from scratch! 
The docs start with the prefab and then lists all the components. IMO would be more helpful to build up a button with minimal needed parts, like:
	Add a PressableButton to get interaction with pointers
	Add Interactable to define button states
	Add PhysicalPressEventRouter to let PressableButton change the states

**Comment by cre8ivepark** [comment]
Added examples and documentation. (PR #4527)

Updated README 
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/prerelease/2.0.0.rc2_stabilization/Documentation/README_Button.md
