### ISSUE TITLE
How to attach an object to a hand joint

### ISSUE THREAD

**Issue by Yoyozilla** [microsoft/MixedRealityToolkit-Unity#4573]
One team built a hand-locked menu using a customized solver. Would have helped to have a minimal template for this scenario and leave it to devs to build on top.
	Hand tracking docs talk about polling vs. events, but don’t include source detected/lost handling.
	ControllerFinder excludes hand controllers, it only works for motion controllers.
	Existing solvers have a lot of additional settings that obfuscate behaviour.

**Comment by chbecker-ms** [comment]
See https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4532 ?
