### ISSUE TITLE
Add input action handler interfaces for non-digital actions

### ISSUE THREAD

**Issue by luis-valverde-ms** [microsoft/MixedRealityToolkit-Unity#4576]
## Describe the problem

Currently we can only handle digital input actions (on/off types) via `IMixedRealityInputActionHandler`. We should add a generic version of the interface for other input action types, similar to what we have for `IMixedRealityInputHandler`. #4477 must be fixed first for this.

**Comment by polar-kev** [comment]
@Zee2 can you confirm that this is solved in v3?

**Comment by Zee2** [comment]
This is solved by variable selectedness and `IVariableSelectInteractor` and `StatefulInteractable` in MRTK3. Three years later. 😛
