### ISSUE TITLE
TouchScreenKeyboard does not work in editor/simulator

### ISSUE THREAD

**Issue by eoineoineoin** [microsoft/MixedRealityToolkit-Unity#4577]
## Describe the bug

When running a scene in the editor, opening the TouchScreenKeyboard, no keyboard is displayed; the keyboard status is immediately set to TouchScreenKeyboard.Status.Done.

## To reproduce

1. In the MRTK examples, open Demos/HandTracking/Scenes/HandInteractionExamples
2. Press play to start simulation in editor
3. Click button to enable keyboard interaction (left of scene)
4. See: no keyboard; OpenKeyboard.cs sets the debug message to "typed " (the completion message)

## Expected behavior

Keyboard should be displayed and allow user input.

## Your Setup (please complete the following information)

- Unity Version 2018.3.5f1
- Microsoft Mixed Reality Toolkit v2.0.0 RC1 Refresh

**Comment by StephenHodgson** [comment]
Not exactly a bug as the touch screen keyboard is a Unity method call, and you're not on a platform that supports the touch screen if you're running in the editor.

**Comment by julenka** [comment]
While I agree it would be really great to bring up the keyboard in the editor, this is not something we are able to do since it would require creating an entire keyboard control just for in-editor simulation. For in-editor simulation, you can directly type into a UnityUI text field using your keyboard.

**Comment by Grave18** [comment]
And if we want to test TouchKeyboard do we need all the time build application? This is a waste of time.
