### ISSUE TITLE
ET demo texture size is too big.

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#4582]
## Describe the bug
There are two large files under Eye Tracking examples folder. 36MB and 15MB.
Not sure if the PSD file is used. Map example texture needs optimization.

![2019-05-27 20_27_28-Textures](https://user-images.githubusercontent.com/13754172/58448822-e8895780-80bd-11e9-8911-b9c4043a01f2.png)

## Branch
mrtk_development

**Comment by keveleigh** [comment]
Closed via #4628
