### ISSUE TITLE
Can't build HoloToolkit in Unity 2018.4 (LTS)

### ISSUE THREAD

**Issue by travelhawk** [microsoft/MixedRealityToolkit-Unity#4583]
## Describe the bug

The latest HoloToolkit (not Mixed Reality Toolkit!) doesn't work in Unity 2018.4 (LTS).
There are errors after exporting the Visual Studio project.

![image](https://user-images.githubusercontent.com/7582909/58465274-a13fad00-8137-11e9-903a-27bb39b932e9.png)

## To reproduce

1. Create new project in Unity 2018.4
2. Import HoloToolkit-Unity-2017.4.3.0.unitypackage
3. Switch to UWP
4. Build project
5. Open Visual Studio project and build

## Expected behavior

Successful VS build without error. Instead there are errors about missing references.

## Your Setup (please complete the following information)

- Unity Version 2018.4.0f1
- HT Version 2017.4.3.0

## Target Platform (please complete the following information)

- HoloLens

**Comment by Yoyozilla** [comment]
HTK requires Unity 2017.4

Closing older HTK issue as we are no longer actively working on HTK.

Please upgrade to MRTK V2 for the latest fixes.

**Comment by travelhawk** [comment]
Unfortunately I have a project running on HTK which I cannot upgrade easily without rewriting a lot of custom scripts.

But at least I got HTK running for Unity 2018.2.
