### ISSUE TITLE
Force release manipulated object

### ISSUE THREAD

**Issue by Xend1992** [microsoft/MixedRealityToolkit-Unity#4584]
## Describe the problem

It's more of a question than a feature. Also, it is my first one on Git Community so I apologize if it's not how questions should be asked here.

I can't figure out how to release currently manipulated object by ManipulationHandler. There may be some easy way, but I can't see one.

## Describe the solution you'd like

I can see what's the current HostTransform object, but I'd like to be able to remove it (or force release it).

## Describe alternatives you've considered

In my problem I need to make sure that manipulated object can't be moved outside of specific collider. Currently I disable ManipulationHandler from the manipulated gameobject OnTriggerExit, reset the position of manipulated gameobject back to just before entering the collider and then enable ManipulationHandler again so the object can be moved/manipulated again. I believe I could ommit enabling/disabling ManipulationHandler overall, but it would not solve the current problem, as the object is still manipulatable.

## Additional context

Feel free to remove my question if Git is a place to only report bugs or propose features. Just let me know before you do so, so that I know for the future. Thanks

**Comment by julenka** [comment]
Seems like a reasonable request to be able to force release a manipulationhandler.

**Comment by julenka** [comment]
Not sure if we will have time for it in the next milestone given our other issues, but it's something that falls under the category of "ux controls are easy to configure by devs"
