### ISSUE TITLE
ReflectionTypeLoadException in MRTK

### ISSUE THREAD

**Issue by zxzkf1992** [microsoft/MixedRealityToolkit-Unity#4586]
## Describe the bug

When I import MRTK in unity, this error will occur, how can I fix it?

## To reproduce

Create an empty project in unity 2018.3.11f
Change platform to UWP
Enable VR with Mixed Reality Toolkit
Import MRTK v2 RC1
Click "Add to scene and configure"
Launch project

## Expected behavior

No error

## Screenshots

ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
System.Reflection.Assembly.GetExportedTypes () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Reflection.Assembly.get_ExportedTypes () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Microsoft.MixedReality.Toolkit.Input.MixedRealityControllerMappingProfile.CollectControllerTypes () (at Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMappingProfile.cs:43)
Microsoft.MixedReality.Toolkit.Input.MixedRealityControllerMappingProfile.get_ControllerMappingTypes () (at Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMappingProfile.cs:30)
Microsoft.MixedReality.Toolkit.Input.MixedRealityControllerMappingProfile.AddMappings () (at Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMappingProfile.cs:68)
Microsoft.MixedReality.Toolkit.Input.MixedRealityControllerMappingProfile.Awake () (at Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMappingProfile.cs:62)

## Your Setup (please complete the following information)

- Unity Version 2018 3.11f
- MRTK Version MRTK V2.0.0 RC1

## Target Platform (please complete the following information)

- HoloLens

**Comment by wiwei** [comment]
Thanks for filing this issue! Can you try to grab the latest mrtk_development and see if you're still hitting this issue? Given the callstack/information here this *should* have been addressed by:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4432

Feel free to reopen if this didn't address the issue.
