### ISSUE TITLE
MRTK Standard Shader - Enable "_MainTex" by default

### ISSUE THREAD

**Issue by radicalad** [microsoft/MixedRealityToolkit-Unity#4590]
## Describe the bug

Currently, the MRTK Standard shader only enables keywords when the fields are manually enabled on the material. This makes sense with "Rendering Options".

I assumed the "Main Maps" are enabled by default as there is no check box to _enable_ the fields.

Unfortunately, Albedo's `Color` is the only keyword enabled by default. It was quite a process to figure out why I wasn't able to set a texture on a MRTK standard shader material.

## To reproduce

Try setting the "_MainTex" directly with `renderer.material.mainTexture = ...`

or via `MaterialPropertyBlock`:

`MaterialPropertyBlock materialPropertyBlock = new MaterialPropertyBlock();
 obj.Renderer.GetPropertyBlock(materialPropertyBlock);
 int MainTexID = Shader.PropertyToID("_MainTex");
 materialPropertyBlock.SetTexture(MainTexID, );
 obj.Renderer.SetPropertyBlock(materialPropertyBlock);`

## Expected behavior

As mentioned above, I'd expect the more basic "Main Maps" keywords to be enabled be default.

## The fix

A single but not intuitive line to add:
`obj.Renderer.material.EnableKeyword("_MainTex");`

## Setup

- Unity Version - 2018.3.11f1
- MRTK Version - pulled MRTK_development from last week.

## Target Platform
- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Cameron-Micka** [comment]
Thank you @radicalad for pointing this out. This is a somewhat frustrating optimization that has "bitten" a few users. I probably need to bubble up the documentation a bit more.

As an optimization albedo operations are disabled when no albedo texture is specified. To control this (as requested by this blog post: http://dotnetbyexample.blogspot.com/2018/10/workaround-remote-texture-loading-does.html) simply check this box:

![albedoassignment](https://user-images.githubusercontent.com/13305729/47942430-28cd8200-deaf-11e8-8df7-d80a51485047.png)

Note, you don't need to check this box if a texture is specified in the albedo slot at runtime (even a placeholder one).

**Comment by dudziakl** [comment]
Albedo Assigned at Runtime field is now on top of the inspector and it is still working in v2.5.1 :) 
![image](https://user-images.githubusercontent.com/12583808/102893816-77a94d80-4462-11eb-95f1-cd0432939033.png)
