### ISSUE TITLE
MixedRealityInteractionMappings to store the Input Action they Invoked

### ISSUE THREAD

**Issue by killerantz** [microsoft/MixedRealityToolkit-Unity#4597]
## Describe the problem

Related to #4475 
"It would be great for Interaction Mappings to have a better link to the actions they invoke. or the eventData to include the InteractionMapping that invoked it as a property."

The MixedRealityInteractionMappings on a controller will have a Select Action in the mappings, but there isn't an easy way to figure out which of the controller buttons Select is actually mapped to. 

If we store eventData from a pointer event, then want to track the value of the button that triggered it over time, this is difficult to do.

The Select action is digital, but could be mapped to the trigger which has a float value. We can only track the Select Action boolData for on or off at this point.

## Describe the solution you'd like

When a pointer event happens, get the mapping to the button that triggered it so we can track it over time.

Maybe eventData.ControllerMappingIndex, would store the index of the button or finger that triggered the input action. Or eventData.InputMapping would be the MixedRealityInteractoinMapping that triggered it.

**Comment by Zee2** [comment]
Closing as stale, as we now use the Unity Input System.
