### ISSUE TITLE
Interactable Voice Command feature is confusing

### ISSUE THREAD

**Issue by killerantz** [microsoft/MixedRealityToolkit-Unity#4598]
## Describe the bug

Interactable has a field for Voice Command, but entering a value there does nothing when running the experience. Older versions of Interactable had the ability to setup a voice command directly from Interactable. Now voice commands need to be setup using the Speech Commands Profile. This should be documented.

Now the Voice Command field just filters the Speech Command that are spoken while the Interaction has focus. This is nice, but should be a drop down instead of a string field to avoid typo bugs.

The Requires Focus property is not hooked up to anything. The ISpeechInputHandler in Interactable does check if Requires Focus is checked and if the Interactable has Focus, but the ISpeechInputHandler does not receive any events unless the Interactable has focus anyway. This property used to let make the Interactable listen globally for a speech commands, but this functionality is not working any more, even with IsGlobal checked. Is there a way to register as a global listener for SpeechCommands?

## To reproduce

1. Create an object with an Interactable.
2. Add a string to the Voice Commands field.
3. observe the voice command does not work.
4. Go to the SpeedCommandsProfile and add a new voice command
5. Enter the voice command from the profile as a string in the Voice Command field of Interactable
6. Observe the Voice Command does work with focus.
7. Uncheck Requires Focus on the Interactable.
8. Observe that the voice command still requires focus.

## Expected behavior

It's clear where and how to setup voice commands
Voice Commands should be a drop down if they are setup in the Speed Command Profile
Change name to Speech Commands for consistency
Requires Focus property should enable a global listener for speed commands if unchecked.

## Screenshots

![image](https://user-images.githubusercontent.com/22085553/58523339-f223c580-8178-11e9-9470-b29ae2890810.png)

**Comment by julenka** [comment]
merged.
