### ISSUE TITLE
Generic way to track drag and other interactions

### ISSUE THREAD

**Issue by killerantz** [microsoft/MixedRealityToolkit-Unity#4599]
## Describe the problem

There are a number of components that follow this interaction pattern.
1. I care about input data
2. cache some values on start
3. compare current input data to the start data
4. Calculate some deltas
5. stop caring about input data

It would be easier to integrate gesture, drag, touch and other interactions into new without worrying about duplicate code if we had a more generic way to process this data. It would also be easier to extend functionality of an existing manipulation component.

A good example of this is the SliderEventData in the slider controls, though this is limited to just dragging along an axis, it could be expanded to track some deltas of rotation as well.

PressableButton, ManipulationHandler, Sliders follow this pattern and handle interaction in a different way.

## Describe the solution you'd like

An easy way to track deltas over time.

1. A class that can be instantiated on a press or other input type.
2. Configure some base settings to how deltas are calculated or which values we care about.
3. Pass in the eventData to track
4. Start Values are stored
5. During press eventData is passed in and compared to the start values
6. Deltas are calculated
7. Respond to deltas in some way by moving, scaling, rotating, sliding, poking, or just checking if a destination or threshold was reached.

The class should contain some commonly used processing methods.

Values could also be passed into solvers for further processing.

## Describe alternatives you've considered

1. Maybe this could be added to gesture or drag event data.
2. MixedRealityInteractionMappings include start values for position and rotation when the floatData, boolData, positionData, or rotationData starts changing, then reset when those values go back to default.

## Additional context

Interaction is going to be a big part of HoloLens too and MR, so making it easier to experiment with input data without building everything from scratch will help the community move further faster. Also a simpler system could enable more tools for designers to experiment.

**Comment by Zee2** [comment]
Closing as stale, we use XRI for MRTK3 which offers some very nice APIs surrounding input-agnostic manipulation.
