### ISSUE TITLE
Input Simulation Does not work on Mac

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4601]
## Describe the bug
If you open an MRTK-Enabled scene on Mac OSX and hit play, the camera will not move when you WASD and hands do not show up.

The expected behavior is that input simulation should work as it does on Windows

I was able to work around this by checking "Mac Standalone" in the Platforms for Input Simulation Service Input Providers: 

![image](https://user-images.githubusercontent.com/168492/58529939-91ed4d80-8191-11e9-93bf-49d19956d4df.png)

## Your Setup (please complete the following information)

- Unity Version 2018.3.14f1
- MRTK Version mrtk_development

## Target Platform (please complete the following information)

- Mac OSX Editor

**Comment by julenka** [comment]
After I apply the workaround above I'm able to use input simulation just fine.

**Comment by djee-ms** [comment]
I can confirm the bug and the workaround, thanks @julenka for the tip!
