### ISSUE TITLE
[RC2 Stabilization] Interactable says 'Mixed Reality Toolkit is missing', PressableButtonExamples scene is not working

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#4610]
## Describe the bug

Interactable says 'Mixed Reality Toolkit is missing' even though it is in the Hierarchy.
PressableButtonExamples scene is not working.

![2019-05-29 09_49_29-Unity 2018 3 8f1 Personal - HandInteractionExamples unity - MRTK-Public-Microsof](https://user-images.githubusercontent.com/13754172/58575517-17571900-81f7-11e9-88b5-8401d367a8e7.png)

![2019-05-29 09_47_15-Unity 2018 3 8f1 Personal - PressableButtonExample unity - MRTK-Public-Microsoft](https://user-images.githubusercontent.com/13754172/58575459-f393d300-81f6-11e9-9500-efefb2a63178.png)

![2019-05-29 09_47_24-Unity 2018 3 8f1 Personal - PressableButtonExample unity - MRTK-Public-Microsoft](https://user-images.githubusercontent.com/13754172/58575460-f393d300-81f6-11e9-8c1c-90ee0ccdc666.png)

![2019-05-29 10_17_34-Interactable cs - Microsoft Visual Studio](https://user-images.githubusercontent.com/13754172/58577501-728b0a80-81fb-11e9-80d4-2627b48316db.png)

## To reproduce
Open HandInteractionExamples scene or PressableButtonExamples scene
Select PressableButton from the Hierarchy panel. See inspector panel.

## Branch
**prerelease/2.0.0.rc2_stabilization**

**Comment by julenka** [comment]
Taking a look

**Comment by killerantz** [comment]
I saw this when taking the latest from MRTK_development on Friday. I had to restart Unity to get rid of all the errors that flooded the console window. I still get the MRTK is missing message on Interactable, but everything still works and no more errors. I was hoping it was an issue with a recent commit.

**Comment by julenka** [comment]
I have a fix.
