### ISSUE TITLE
Expandable overflow button

### ISSUE THREAD

**Issue by pdlipman-apx** [microsoft/MixedRealityToolkit-Unity#4612]
## Describe the problem

As a user, i want to keep my user interface decluttered so that I can stay focused on my primary tasks. When additional options on a screen are needed, i want to be able to tap a single button that unfurls to reveal one or more additional button-based options that can be tapped to take take action on the current view.

## Describe the solution you'd like

Add an MRTK solution where a single pressable button can be tapped to reveal one or more buttons arranged in a vertical or horizontal row/column. Tapping an option would collapse the expanded button back into a single button again.

_AC_
- The overflow button "..." can have text, icon, and voice command associated with it
- The number of buttons that get revealed on tap of the overflow button is configurable
- The revealed buttons can be arranged in a vertical column or horizontal row (with configurable spacing value between each button
- Tapping on a "revealed" button automatically collapses the panel back into the single "overflow" button
- The reveal buttons can each have an icon, text, and voice command associated with them

## Describe alternatives you've considered

Looked at App Bar (script) as original inspiration but it is fixed number of buttons and purpose built to a specific use case.

**Comment by Railboy** [comment]
@pdlipman-apx A 'collapsable menu' or 'button collection' prefab sounds like a good idea.

> it is fixed number of buttons and purpose built to a specific use case.

@pdlipman-apx The App Bar is definitely for a specific use case and won't meet the needs listed here, but it's not totally fixed either - you can add custom buttons by dragging the PressableButtonAppBar prefab into the button parent transform and setting its type to Custom. You can also hide the built-in buttons via checkboxes.

**Comment by Zee2** [comment]
Dynamically arranged and laid-out content and buttons are now easily achievable with the new Canvas UI-based volumetric buttons. Feel free to reopen or DM me directly with any questions.
