### ISSUE TITLE
Type-o in PressableBUttonHoloLens2.cs

### ISSUE THREAD

**Issue by fast-slow-still** [microsoft/MixedRealityToolkit-Unity#4615]
## Upper case 'M' rather than lower case 'movingButtonIconText' will crash.

The getter for MovingButtonIconText returns "MovingButtonIconText", rather than the correct "movingButtonIconText". Simple type-o, but if called will crash the app with an infinite loop.

**Comment by keveleigh** [comment]
Fixed via #4674 and #4624
