### ISSUE TITLE
Consider changing focus provider management from input system to registrar

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#4622]
## Describe the problem

In the current implementation of the input system and the mixed reality toolkit service locator, there is not a clean way to unregister the focus provider independently of the input system.

As it stands the focus provider is considered a core system in the service locator, but is registered as a dependency of the input system. Unregistering the focus provider does not allow for full cleanup (ex: marking the property value as null in the input system).

## Describe the solution you'd like

Ideally, the focus provider and the input system could be decoupled and managed independently in the service locator / registrar. This would involve:

- Moving the focus provider profile to be a peer of the other core systems
- Add a FocusProvider accessor to the MixedRealityToolkit object
- Update the input system to request the focus provider from the registry

Alternatively, the focus manager could be declassifed as a core system and made to be owned and managed by the input system.

**Comment by Railboy** [comment]
Definitely support this. It would also highlight the possibility of - and hopefully encourage - writing custom focus providers.

**Comment by davidkline-ms** [comment]
@Railboy, am I reading correctly that you are supportive of making the focus provider a true peer of the other core services?

**Comment by Railboy** [comment]
>you are supportive of making the focus provider a true peer of the other core services?

@davidkline-ms Correct. At some point we'll have to call it quits with this proliferation of core services. But IMO this one makes sense. Its place in the current system obscures how important it is.

**Comment by Zee2** [comment]
XRI provides focus in MRTK3; the `XRInteractionManager` provides a global store of interaction state and mediation between interactors and interactables.
