### ISSUE TITLE
Manipulation Handler not working right for Two hand only manipulation 

### ISSUE THREAD

**Issue by zhang37966** [microsoft/MixedRealityToolkit-Unity#4629]
may be related to this (which is not fixed)
TwoHandsManipulation acts weird when One Hand Movement disabled. #2797 

Scenario: Have a steering wheel model which I want to make it rotate just like a real wheel when user grabs it with two hands. Wheel should not rotate when grabbed with one hand only. 

Settings:
Manipulation Type: two handed only 
Two Handed Manipulation type: rotate 
Allow Far manipulation: yes
One hand Roation Mode Near: maintain original rotation 
Release Behavior: None 

Constraints on Rotation: Z axis only

Expected Behavior:
Wheel rotates when grabbing with both hands 
Wheel stop rotating when any hand is released 
Wheel doesnt do anything when grabbed with one hand

Actual behavior:
Wheel rotates as expected when grabbing with two hands. 
I release one hand, now wheel is moving with the other grabbed hand.

**Comment by Yoyozilla** [comment]
china hack
