### ISSUE TITLE
InteractionSourceLocation.TryGetPosition Bug! Obsolete public bool TryGetPosition(out Vector3 position);

### ISSUE THREAD

**Issue by YingJiangMua** [microsoft/MixedRealityToolkit-Unity#4631]
## Describe the bug
Hi guys, I tried to run one project code and met one problem which may be caused by the difference among different version of Holotoolkit. The bug is as shows:
	CS0619	“InteractionSourceLocation": InteractionSourceLocation is deprecated, and will be removed in a future release. Use InteractionSourcePose instead. (UnityUpgradable) -> InteractionSourcePose”	

![image](https://user-images.githubusercontent.com/30496220/58642982-f09cfd80-8330-11e9-86e0-5435b5e2c31d.png)

Actually, this code using HoloToolKit (very old versions of  Hololens SDK), I found there were some incompatible problems. The original code is:

![image](https://user-images.githubusercontent.com/30496220/58642722-78ced300-8330-11e9-9951-7bcbe54a43b1.png)

And the latest version does not support the function "state.properties.location.TryGetPosition(out pos);". Thus I have to change it into: "InteractionSourceLocation.TryGetPosition(out pos, XXXX)". And I do not know what should be filled into XXXX. Thus I just used InteractionSourceLocation. And this function is Obsolete either. I am exhausted.....Does anybody know how to fix this problem? Many thanks!!!!!! This file is under: Assets/Holotoolkit/Input/Scripts/Handmanager.cs The most terrible thing is that there are only a few docs about Holotoolkit (The previous version).

## Your Setup (please complete the following information)

- Unity Version 2018.3.11f1
-VS Version 2017

## Target Platform (please complete the following information)

- HoloLens

**Comment by Troy-Ferrell** [comment]
Sorry to hear but Holotoolkit is no longer supported
