### ISSUE TITLE
Visualizations of near interaction touchable planes

### ISSUE THREAD

**Issue by MenelvagorMilsom** [microsoft/MixedRealityToolkit-Unity#4632]
## Describe the problem

Currently, the only way to modify near interaction touchable planes that govern when we receive touch down and touch up events is through the property inspector.

## Describe the solution you'd like

It would be great to have visualizations of these values in the scene view, much like we have for buttons. 

## Additional context

#4263

**Comment by Zee2** [comment]
All "touchable" surfaces in MRTK3 derive from the Button class, so we get this for free. If this behavior is still critical for MRTK2, please reopen.
