### ISSUE TITLE
Spatial mapping simulation in Editor

### ISSUE THREAD

**Issue by danielescudero** [microsoft/MixedRealityToolkit-Unity#4636]
When developing/designing apps that use spatial mapping, it is required to deploy in order to test. So developers would like to do some easy spatial map simulation in editor.

Ideally dragging a prefab in the scene to test a sample spatial mesh and ensure their renderers are working correctly/right material, basic hit / raytest tests to make sure it works, etc. Without having to build to device.

Ideally we can simulate:
- Refresh rate
- Renderers
- Office room, small/medium/large areas
- Spatial understanding
- Use developer-generated meshes

**Comment by keveleigh** [comment]
Are you able to use Unity's built-in room simulation to get a mesh?

https://docs.unity3d.com/Manual/wmr_testing.html#SimulateInEditor

**Comment by keveleigh** [comment]
Also, related to #3535
