### ISSUE TITLE
Documentation should include code samples of how to use properties and methods

### ISSUE THREAD

**Issue by danielescudero** [microsoft/MixedRealityToolkit-Unity#4641]
Documentation (https://microsoft.github.io/MixedRealityToolkit-Unity/api) should include code examples, just like the Unity ScriptingReference.

Many times developers are looking for code snippets to accomplish a task. Properties and methods should always include a small snippet of code showing how to use them and when.

Great example below:

![unity](https://user-images.githubusercontent.com/19855491/58667045-d12eb200-82e9-11e9-9c02-7248dad4f696.jpg)

**Comment by keveleigh** [comment]
We may be able to use the `example` tag for this: https://dotnet.github.io/docfx/spec/triple_slash_comments_spec.html#top-level-block-tags

**Comment by Troy-Ferrell** [comment]
Documentation is being pushed to have code examples everywhere:
#5699 and #5701 and #5633 as examples.

Closing this as too general. There are already a lot of documentation issues covering specific areas. If there is a specific page, please reference but many are already under way
