### ISSUE TITLE
Solver to follow any hand (not one or the other)

### ISSUE THREAD

**Issue by danielescudero** [microsoft/MixedRealityToolkit-Unity#4642]
Solver forces you to choose either left or right hand, but not "any" of the two. 
- Developers would like solvers to follow any hand that's available.
- Solver component should address accessibility issues, like not knowing what hands users will use for their work.
- Currently to work around the missing feature we have to check the Handedness, then change the target.

**Comment by mtirion** [comment]
Might want to consider removing this option. It's bad UX to attach it to only one hand or even have different menu's per hand. Hard to discover
