### ISSUE TITLE
Add HelpURL attributes to Interactable, ManipulationHandler, boundingbox, pointer

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4648]
The [HelpURL](https://docs.unity3d.com/ScriptReference/HelpURLAttribute-ctor.html) attribute is useful for pointing people to documentation. We can add this to our UX components to help teach people how to use and configure the controls.

**Comment by Railboy** [comment]
@julenka fyi DocLink is exclusively for services. For stuff like BoundingBox and Pointer we should use the Help attribute.

**Comment by julenka** [comment]
Oh, thanks for clarifying!

**Comment by julenka** [comment]
@Railboy do you mean the [HelpURL attribute](https://docs.unity3d.com/ScriptReference/HelpURLAttribute-ctor.html)?

**Comment by Railboy** [comment]
@julenka Yup that's the one!
