### ISSUE TITLE
Solvers can only be configured at design time

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#4650]
## Describe the bug

Virtually every important setting in solvers cannot be configured at runtime. Here are just a few examples:

**SurfaceMagnetism**

- magneticSurfaces
- maxDistance
- closeDistance
- raycastMode
- sphereSize
- raycastDirection
- orientationMode

**Momentum**

- resistance
- accelerationRate
- springiness

**ConstantViewSize**

- targetViewPercentV
- minDistance
- maxDistance
- minScale
- maxScale

There are many, many more. Virtually _every_ configurable field in every solver is private with no publicly exposed property.

_**This makes solvers a design-time only feature!**_

There is currently no way to instantiate a solver in code and then configure it, yet there are many reasons to do so. For example, trying to write a replacement for the HTK **TapToPlace** behavior requires access to **SurfaceMagnetism** properties like **maxDistance** and **orientationMode**.

Related, many of the types necessary to configure the solvers are both private _and_ nested.

For example, **RaycastDirectionEnum** should not be private, nor should it be a nested child of the **SurfaceMagnetism** solver.

## Expected behavior

1. Every single value that is configurable in the Unity inspector should be settable by code.
2. Every type necessary for configuring solvers should be public and should not be nested within other types.
3. Changes made to values at runtime must be honored. 

## Your Setup (please complete the following information)

- Unity Version 2018.3.6f1
- MRTK Version v2.0

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by gilbdev** [comment]
i agree on that.
it's often more easy to jsut copy the whole solver and make our own editable solver, which is a bit sad.

**Comment by StarWardo** [comment]
I am also looking for this. As almost everything in my app is defined at runtime by the user.

**Comment by julenka** [comment]
Merged
