### ISSUE TITLE
Can't bind the keyboard input for voice input

### ISSUE THREAD

**Issue by Ailegen** [microsoft/MixedRealityToolkit-Unity#4654]
![image](https://user-images.githubusercontent.com/16714300/58687078-2edb0100-83b3-11e9-843c-f08c6129b8e9.png)

**Comment by Ailegen** [comment]
should work according to the document
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Speech.html

**Comment by Troy-Ferrell** [comment]
@Ailegen see PR referenced above. The dropdown selector UI should still work if you click on it. It's not a functional bug, it's just a visual bug. The PR referenced though fixes the visual issue

**Comment by wiwei** [comment]
Closing this one out as fixed by #4661
