### ISSUE TITLE
SpeechInputHandler - IsFocusRequired not working

### ISSUE THREAD

**Issue by mkaczmarek7** [microsoft/MixedRealityToolkit-Unity#4658]
## Describe the bug

Its not matter when you have enabled/disabled IsFocusRequired  in SpeechInputHandler. 
You still need focus when you have IsFocusRequired = false.

## To reproduce
1.Attach  SpeechInputHandler to object (from script).
2.Add keywords to dictionary (from script).
3.Disable IsFocusRequired .
![image](https://user-images.githubusercontent.com/51234444/58705169-a9555200-83ae-11e9-83e7-f3bc0f4407e4.png)
4.See bug.

## Expected behavior
You dont need to focus on object when you call voice command

## Your Setup (please complete the following information)

- Unity Version [2018.3.12f1]
- MRTK Version [Mixed Reality Toolkit 2.0.0-RC1-Refresh]

## Target Platform (please complete the following information)
- HoloLens 2

**Comment by wiwei** [comment]
I *think* this got fixed in recent mrtk_development - please reopen if not the case.
