### ISSUE TITLE
 MRTK inspector doesn't allow you to enable / disable a service when using default profiles

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedRealityToolkit-Unity#4663]
## Describe the bug

You can't enable / disable a service when using the default profiles.

## Expected behavior

You should be able to enable / disable services regardless of whether a profile is default.

## Screenshots
![MRTKInspectorBUg](https://user-images.githubusercontent.com/9789716/58719241-fff96680-8383-11e9-9547-005bfef5b63b.PNG)

- Unity Version 2019.1
- MRTK 2.0 mrtk_development

**Comment by keveleigh** [comment]
This seems by-design to me, for the same reason we don't allow other settings to be changed in default profiles.
If we allow this profile to be edited without creating a new one, and somebody imports a new version of the MRTK, they may overwrite their changes.

**Comment by Railboy** [comment]
Ugh.

The fact that we can't even *disable a service* in the default profiles is so obnoxious that I took it for a mistake, even though I should know better by now.

My rage at this daily inconvenience continues to grow.

**Comment by RobDesrosiers** [comment]
You can disable it. Pretty sure the default profile is made that way so you're unable to change it. Click "Copy and Customize" on the button in the screenshot and all your dreams will come true.

**Comment by Railboy** [comment]
@RobDesrosiers Thanks, I know you can get around it I just find the pattern irritating.
