### ISSUE TITLE
Unable to build solution: ArticulatedHand.cs The type or namespace could not be found

### ISSUE THREAD

**Issue by RobDesrosiers** [microsoft/MixedRealityToolkit-Unity#4668]
## Describe the bug

When building the solution, there are four errors:
"Assets\MRTK\MixedRealityToolkit.Providers\WindowsMixedReality\WindowsMixedRealityArticulatedHand.cs ... : error CS0246: The type or namespace name ... could not be found (are you missing a using directive or an assembly reference?)"
- (418,73) HandJointKind
- (111,17) HandMeshObserver
- (382,33) HandJointKind
- (412,26) JointPose

These errors do not appear during Play Mode. Based on previous incidents, Windows has been updated to 18362 in an effort to remedy these issues (listed in the Additional Context section), but unfortunately did not resolve the issue. I've attempted to delete/reload the Library and the previous project solution, as well as restarting PC/Unity to no effect.

## To reproduce

1. Go to 'File > Build Settings'
2. Use the following settings and click 'Build':
![bug_articulatedhand2](https://user-images.githubusercontent.com/48729823/58722865-2e843b00-839e-11e9-9f43-626ad75e5d2d.PNG)
3. See errors

## Expected behavior

The project should build successfully without errors.

## Screenshots

![bug_articulatedhand](https://user-images.githubusercontent.com/48729823/58722747-dc431a00-839d-11e9-87f1-7e1ee58a7c7c.PNG)

## Your Setup

- Windows 10 Version 1903, Build 18362.116
- Unity Version 2018.4.1f1
- MRTK v2 RC1 Refresh
- Samsung HMD Odyssey

## Target Platform

WMR immersive headset

## Additional context

Similar issues that have happened in the past:
- #3844 
- #3967 
- https://stackoverflow.com/questions/55616928/mrtk-v2-need-to-update-hololens/55626479#55626479

**Comment by keveleigh** [comment]
What's the latest SDK do you have installed (`Target SDK Version` in the Unity build window)?
It's not as important which Windows build you have installed, but more which SDK you're building to. Those APIs are only present in the 18362 SDK. https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

**Comment by RobDesrosiers** [comment]
@keveleigh Latest SDK is 18362 since yesterday. Originally had 18356.14 and has to reset the PC to get it to update properly again; had the same bug during then too. Hoped that updating to 18362 would fix it.

**Comment by RobDesrosiers** [comment]
@keveleigh Thanks for clearing that up, thought they were one and the same (early comp sci student here). Downloading the SDK worked it out.

**Comment by keveleigh** [comment]
@RobDesrosiers Great, glad you got it sorted!

**Comment by lovelieren** [comment]
**Minimum Requirement for MRTK v2**
Unity 2018.3.x
Microsoft Visual Studio 2017 or later
Windows SDK 18362+
Windows 10 1803 or later

I made a mistake, see that ? should install SDK 18362+ individuall,before it my lasted windows sdk is 17763!!!

**Comment by Railboy** [comment]
Alternative solution: Uninstall older SDK versions.
