### ISSUE TITLE
Any Readme file or guidelines to follow for the new HTK - Unity 5.5?

### ISSUE THREAD

**Issue by kotAPI** [Microsoft/MixedRealityToolkit-Unity#467]
Hey, I've been using the previous version of HTK for a while and found my way across it quite well. I see that there have been major changes in 5.5 and my older projects dont work with the new HTK anymore. Is there any readme file/guidelines for migrating to use the new functionalities of 5.5?

**Comment by NeerajW** [comment]
Your best bet with the input changes are:
1. https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Tests/Scenes/InputTapTest.unity
2. https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Tests/Scenes/InputManagerTest.unity

Please let us know if you have any specific questions.

**Comment by S-Hodgson-MMOARgames** [comment]
Unfortunately, I don't think anyone has taken the time to write a upgrade guide.

Any insight would be beneficial to anyone still trying to upgrade.

**Comment by kotAPI** [comment]
I could only find a handy website with a post that talks about basic implementation of the new 5.5
Hopefully someone finds some use of it

https://livierickson.com/blog/unity-5-5-and-the-holotoolkit-changes-in-input-when-developing-hololens-apps/

**Comment by StephenHodgson** [comment]
I think having upgrade guides is good.
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/882
