### ISSUE TITLE
Add support for profiles to Solvers

### ISSUE THREAD

**Issue by gejohnst** [microsoft/MixedRealityToolkit-Unity#4675]
Configuring a solver currently requires a lot of tweaking to ensure the behavior feels right, and copying settings between solvers is an involved process.  By adding profiles to solvers, the configuration data becomes separated from the functionality and can easily be shared within and between projects. This allows for faster development and more consistency for consumers of the MRTK.  This also allows for default configurations to be packaged with the MRTK alongside common use cases.

To support backwards compatibility, these profiles will act as override values for the existing settings when both are present.  There will also exist an easy means to store preexisting settings as a profile for older projects to facilitate upgrading to this system.

**Comment by keveleigh** [comment]
Related to #2798

**Comment by Troy-Ferrell** [comment]
Why does copy component not work for this scenario? The serialized object is effectively a profile.

![image](https://user-images.githubusercontent.com/25975362/61566014-a92d1680-aa2f-11e9-947f-7574fcf20588.png)

**Comment by Zee2** [comment]
Closing as not planned; we won't be using profiles for solvers, but we may end up offering ScriptableObject support.
