### ISSUE TITLE
Error compilation on Build 18362...

### ISSUE THREAD

**Issue by RussianDragon** [microsoft/MixedRealityToolkit-Unity#4687]
Hello.

I try to compile a simple project in MixedReality.
If I start project using Play button it works, but when I try to build it - I have an error

```
Assets\MixedRealityToolkit.Providers\WindowsMixedReality\WindowsMixedRealityArticulatedHand.cs(418,73): error CS0246: The type or namespace name 'HandJointKind' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedRealityToolkit.Providers\WindowsMixedReality\WindowsMixedRealityArticulatedHand.cs(111,17): error CS0246: The type or namespace name 'HandMeshObserver' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedRealityToolkit.Providers\WindowsMixedReality\WindowsMixedRealityArticulatedHand.cs(382,33): error CS0246: The type or namespace name 'HandJointKind' could not be found (are you missing a using directive or an assembly reference?)

Assets\MixedRealityToolkit.Providers\WindowsMixedReality\WindowsMixedRealityArticulatedHand.cs(412,26): error CS0246: The type or namespace name 'JointPose' could not be found (are you missing a using directive or an assembly reference?)

```
Other issues tell - update windows and set special setting... I set this, but it did not help...

![image](https://user-images.githubusercontent.com/12259067/58801890-7f9d6480-8614-11e9-9b93-236370983aab.png)

Unity version 2018.3.9f1
![image](https://user-images.githubusercontent.com/12259067/58802182-2e41a500-8615-11e9-9d0c-3bd9d3505f4b.png)

HoloLens 2 Emulator

What could be the problem?

**Comment by wiwei** [comment]
Can you verify that you have SDK version 18632 installed? i.e. there's a difference between being on an OS that is that version, and having an SDK that is that version (they are disjoint things).

Can you take a screenshot with the  "Target SDK Version" dropdown open?

**Comment by RussianDragon** [comment]
of course

![image](https://user-images.githubusercontent.com/12259067/58804144-ce013200-8619-11e9-9bf5-b99f4ba60cfb.png)

**Comment by wiwei** [comment]
Ah yeah, this is a classic case of missing SDK.

You'll want to grab the latest one from:

https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

Per the notes here:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html#prerequisites

**Comment by RussianDragon** [comment]
Yes. Thank you.
