### ISSUE TITLE
Create reusable hand proximity component

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4689]
## Overview
In PR #4646 @JarodShow expressed desire to have a component to indicate proximity of a hand to the object. This would allow an object to for example grow as the hand got near it.

The ProximityHandler component that would expose an event like OnPointerProximityChanged(ProximityEventData d), as well as a way to poll for the closest pointer information (which would return Infinity of no pointer is within grabbing distance). You would also probably want to have events like OnNearStateEntered, OnFarStateEntered, OnMediumStateEntered.

ProximityEventData would be something like this:

```
class ProximityEventData
{
    ProximityState oldState;
    ProximityState newState;
    float oldDistance;
    float newDistance;
}

enum ProximityState
{
    FarDistance,
    NearDistance,
    MediumDistance
}
```

I think that with that component you could build the behavior you need for the bounding box handles by adding a ProximityHandler to each of the corner prefabs. 

You could then just listen for those proximity events and change the visuals in the way you're doing here. Or, a designer could hook up the Unity events OnNearStateEntered, etc. to set different states in an Interactable, which would allow for somebody to make really interesting visual feedback based on the proximity of a hand to a corner.

For #4646 it was out of the scope of the bugfix, so we created a new issue to track it.

**Comment by Zee2** [comment]
Marking this as stale.

**Comment by Zee2** [comment]
This is possible with the generic ActiveHover state in StateVisualizer in MRTK3.
