### ISSUE TITLE
Extensible, type based supported platforms solution.

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#4692]
## Describe the problem
As new platforms are developed, the core MRTK assemblies need to be modified and recompiled to add support for them in the SupportedPlatform enum.  This means that support for a completely new platform requires more than just an extension module.

@Alexees created a PR (#4358) that proposes a type based approach that, unfortunately, did not meet the v2 bar for breaking changes and is being added to our backlog to consider for the next major MRTK version.

**Comment by Alexees** [comment]
@davidkline-ms how about the following approach:
the current SupportedPlatforms enum could have an additional "Custom" entry (preferably the 32th bit). When selected, the inspector shows a second dropdown, additionally showing the list of class based platform checks. This way, if any platform from the default enum is supported, the check can opt out early like it does now, keeping the current code intact, and if not also check the additional, custom platforms. Of course, the MixedRealityDataProviderAttribute needs to be extended, being able to serialize both, the enum and the new classes.
So, if nobody needs the system, they just do not implement any class based on the new IPlatformSupport interface.
We could even go as far as to show an inspector info field if somebody chooses the custom entry but does not have any classes implemented.

**Comment by davidkline-ms** [comment]
@Alexees, interesting idea! We will definitely look into that as we start planning the next major version.

For now, all current Unity XR/VR/AR platforms are defined in our enum.

**Comment by keveleigh** [comment]
Closing in favor of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4235
