### ISSUE TITLE
Extensible system for defining controller types

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#4693]
## Describe the problem
As new controllers are released, the core MRTK assemblies need to be modified and recompiled to add awareness of them. This means that support for a completely new platform requires more than just an extension module.

@Alexees created a PR (#4240) that proposes a type based approach that, unfortunately, did not meet the v2 bar for breaking changes and is being added to our backlog to consider for the next major MRTK version.

**Comment by Yoyozilla** [comment]
I am not sure if this is GA blocking.

**Comment by Alexees** [comment]
> I am not sure if this is GA blocking.

What does GA mean?

**Comment by luis-valverde-ms** [comment]
That'd be General Availability, I think, a.k.a. the actual MRTK 2.0.0 release.

**Comment by Yoyozilla** [comment]
this can come after GA in an update. removing the tag.

**Comment by polar-kev** [comment]
Closing since this will be covered by Unity's input system/Unity abstractions in MRTK v3.
