### ISSUE TITLE
There is no way to access pointer mediators from code

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4696]
## Describe the bug
There is no way to access the pointer mediators in the MRTK input system from code, which makes it difficult to customize which pointers are enabled / disabled at run time. I think we should consider this for GA because it falls under principle of "allow developers to customize behavior".

## Additional Context
Developers can implement their own custom pointer mediators, but if they want to talk to that mediator to say do different behaviors based on application state (let's say you sometimes want to turn all pointers off), there is no way to talk to their custom mediators.

For example, there is no way to turn off the far hand rays at run time without modifying MRTK input system. The following [stackoverflow question](https://stackoverflow.com/questions/56248329/how-to-turn-off-motion-controller-pointer-mediator) is an example of an external user wanting this behavior. 

While it may seem like turning off line pointers could be done by directly accessing `myPointer.IsActive = false`, this actually does not work because the pointer mediators overwrite these values every frame based on the state of other pointers. Therefore, to turn off line pointers a component must talk to the mediator and ask the mediator to turn the line pointers off.

**Comment by Jarodshow** [comment]
> Note: the reason you need to use this approach of modifying the mediator instead of directly setting `myPointer.IsActive = false` is because the default mediator overwrites these values every frame. 

Could we put this in the docs somewhere? :)
