### ISSUE TITLE
Bounding box creates a giant collider at runtime for ActivateManuallyWithButton in HandInteractionExamples scene

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#4706]
## Describe the bug

At runtime, the bounding box script creates a large box collider for the ActivateManuallyWithButton object in the HandInteractionExamples scene.
This additionally causes it to be impossible to point at any of the objects on the left side of the example scene.

## To reproduce

1. Open the HandInteractionExamples scene and hit play
2. Optionally: Window -> Analysis -> Physics Debugger (to more easily see colliders in the scene)
3. Click on the ActivateManuallyWithButton object in the scene hierarchy
4. Observe the massive collider present on that object

## Expected behavior

No massive collider in the scene

## Screenshots

Edit time: 
![image](https://user-images.githubusercontent.com/3580640/58914892-87bcd900-86d4-11e9-815e-db3b57900710.png)

Runtime:
![image](https://user-images.githubusercontent.com/3580640/58914918-986d4f00-86d4-11e9-90d6-28df8f599935.png)

## Your Setup (please complete the following information)

- Unity Version 2018.4.1f1
- MRTK Version RC2 Stabilization

**Comment by julenka** [comment]
Interesting, doesn't seem to repro in mrtk_development.

**Comment by julenka** [comment]
Also doesn't seem to repro in latest rc2_release candidate. Restarting Unity in case I can get it to repro again...Kurtis also wasn't able to repro.

**Comment by julenka** [comment]
Still not reproducing after Untiy reboot. Going to mark it as not repro.
