### ISSUE TITLE
Can't change hands model during Runtime

### ISSUE THREAD

**Issue by Kanaoko** [microsoft/MixedRealityToolkit-Unity#4713]
## Overview
Hello. I'm trying to change my hands model during time. My problem its that I don't find a way to change the profile on runtime, so I tried to search the model, delete it and instantiate another one in his position.

The problem its that when controllers are lost the riginal model will appear again so its problematic.

Any help?

## Expected Behavior
Be able to change hands model
## Actual Behavior
I cant/ I dont know how
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2019.1.0f2
## Mixed Reality Toolkit Release Version
v2.0.0 RC1- Refresh

**Comment by SimonDarksideJ** [comment]
To change the hands module, you should only need to swap out the visualisation profile you are using.
Don't think about changing the model file, rather you are swapping to another profile / setup at runtime.

Profile swapping should be fully supported, so you can try that.

1. Create one visualisation profile for Model A
2. Create one visualisation profile for Model B
3. Configure Profile A at design time in editor
4. At runtime, swap the profile out

Hope that clears that up.  In a profile world, you decide what you need in your project up front and then switch profiles as the runtime demands, ensure you have ALL the correct settings.

It's also hierarchal, so if you want to change the configuration of the entire project in one go, simply make two versions of the main configuration profile and swap it out.  Only asset to keep the same is the input actions profile, that profile can't change.

**Comment by Kanaoko** [comment]
> To change the hands module, you should only need to swap out the visualisation profile you are using.
> Don't think about changing the model file, rather you are swapping to another profile / setup at runtime.
> 
> Profile swapping should be fully supported, so you can try that.
> 
> 1. Create one visualisation profile for Model A
> 2. Create one visualisation profile for Model B
> 3. Configure Profile A at design time in editor
> 4. At runtime, swap the profile out
> 
> Hope that clears that up. In a profile world, you decide what you need in your project up front and then switch profiles as the runtime demands, ensure you have ALL the correct settings.
> 
> It's also hierarchal, so if you want to change the configuration of the entire project in one go, simply make two versions of the main configuration profile and swap it out. Only asset to keep the same is the input actions profile, that profile can't change.

My problem its that i dont know how to change it. I can in editor mode but i dont know how to do that in runtime. There is some API or something or what is the code to change a profile?

Thx

**Comment by SimonDarksideJ** [comment]
@davidkline-ms , this highlights the need for a demo/explanation of the profile swapping system.  Can you talk to the MS teams about providing a sample, such as in this use case.

**Comment by Kanaoko** [comment]
How can i talk them? i dont think I know who do you mean

**Comment by Yoyozilla** [comment]
we can fix this after GA

**Comment by SimonDarksideJ** [comment]
Sorry @Yoyozilla but No.  This is a GA critical issue as it affects both AR and VR.  There must be a documented way of changing models at runtime, either as I described by swapping the profiles or another method.  If it isn't working then there is a serious issue in that configuration cannot be managed at runtime.
Thoughts @davidkline-ms ?

**Comment by davidkline-ms** [comment]
> this highlights the need for a demo/explanation of the profile swapping system

Profile swapping is one possible implementation (though it carries the performance burden of re-initializing systems). I will investigate what it would take to add a runtime model swap solution (I recall having a discussion over precisely this feature a few months back).
