### ISSUE TITLE
Layer mask hard-coded for SphereOvelap case

### ISSUE THREAD

**Issue by fast-slow-still** [microsoft/MixedRealityToolkit-Unity#4719]
## Hard-coded SphereOverlap case means BoundingBox interactions can't be filtered.

In the FocusProvider.cs, other cases in QueryScene are filtered by the prioritizedLayerMasks. This allows runtime filtering of interactions appropriate to the current mode.

The SphereOverlap case is unlike the others in that it is hardcoded to only ignore the UnityEngine.Physics.IgnoreRaycastLayer. For consistency, especially since it is already ignoring the IgnoreRaycastLayer, it might be better to ignore the prioritizedLayerMasks like the other cases.

- Seen in current mrtk_development.

**Comment by fast-slow-still** [comment]
Note that if disabling bounding box interaction via layer masks works, the bounding box's Activate by Proximity should probably not activate when the nearby grabber is excluded by layer mask. See [visual cues issue](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4741).

**Comment by RogPodge** [comment]
Resolved by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7625
