### ISSUE TITLE
Tests for Touchables

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4726]
## Overview
Write five tests to give confidence that touch input will not break when somebody makes a change. The tests should most likely be PlayMode tests to ensure that end to end behavior works.

## Test List
**TODO: asignee please write down cases to test. You can use [this issue](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4723) as an example**

**Comment by MenelvagorMilsom** [comment]
#4893

**Comment by julenka** [comment]
Great! I'll assign the task to lukas then. Thanks Lukas!
