### ISSUE TITLE
Tests for ManipulationHandler

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4729]
## Overview
Write five tests to give confidence that manipulation handler will not break when somebody makes a change. The tests should most likely be PlayMode tests to ensure that end to end behavior works.

## Test List
- [x] Test force release feature
- [x] one hand movement near
- [x] one hand movement far
- [x] rotate with user
- [x] throw object
- [x] one hand manipulation rotation with constraints
- [ ] two hand manipulation rotation with constraints

**Comment by thalbern** [comment]
I'm adding tests to the list as they're being added by fixing bugs - it won't be possible to cover the whole manipulationhandler in 5 tests - but I'd suggest we keep on adding tests as things break / features get added / while refactoring

**Comment by wiwei** [comment]
@thalbern, totally agree on adding tests as go here - I'm going to close this out because unless we've made some good progress here for the current iteration, and we can continue to improve the coverage here as we're fixing bugs/refactoring
