### ISSUE TITLE
Manipulation Update when Head moves.

### ISSUE THREAD

**Issue by charlesMP** [Microsoft/MixedRealityToolkit-Unity#473]
IManipulationHandler works well when my hand is the only thing that is moving; but I've experienced that the OnManipulationUpdate event will trigger when I rotate my head. 
It also keeps happening when the hand is not visible and the Manipulated object will keep moving until you refocus on your hand to trigger the end event.

An easy way to replicate this is get a GameObject that you can Manipulate. Move it with your hand upwards. Then move your head to look up at the GameObject. You should see that the GameObject still moves upward even though your hand is in the same position.

**Comment by HodgsonSDAS** [comment]
I didn't get as bad of movement using Hand Draggable script.

**Comment by mgraszek** [comment]
I have the same issue with manipulation. I'm trying to receive same effect as in "Drag and Move" Holograms, but no success.
The thing is, when im using `eventData.CumulativeDelta` i receive delta from my last move, but when i stopped moving my hand i still receive the same data in this variable. Data stops appearing after few seconds (5 or more seconds).

**Comment by davidkline-ms** [comment]
We should continue to investigate this.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
