### ISSUE TITLE
Tests for Cursor States

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4731]
## Overview
Write five tests to give confidence that cursor states will not break when somebody makes a change. The tests should most likely be PlayMode tests to ensure that end to end behavior works.

## Test List
**TODO: asignee please write down cases to test. You can use [this issue](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4723) as an example**

**Comment by MenelvagorMilsom** [comment]
Fixed with #4995
