### ISSUE TITLE
Slate Pan and Zoom do not work as expected

### ISSUE THREAD

**Issue by asugaya-apx** [microsoft/MixedRealityToolkit-Unity#4732]
## Possibly Related Issues
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4727
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4555

## Describe the bug
Slate panning interactions don't work as expected in the slate example scene, and zooming using pinch gestures (when the gesture mode is set to touch) causes the image to become unusable.

## To reproduce

1. Load up the Slate examples
2. Use touch to pan the images (notably the free scroll and horizontal examples)

## Expected behavior
Expected behavior is the image to move right when panning right with the index finger and left when panning left with the index finger.

## Your Setup (please complete the following information)

- Unity Version 2019.1.4f1
- MRTK Version 2.0.0.rc1.refresh_stabilization

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by julenka** [comment]
Hi, thanks for the bug report! Could you please describe a bit more the actual behavior you are seeing? Currently on slate when I pan to the right the image scrolls to the right.

**Comment by julenka** [comment]
Looks like this has been fixed recently. Behavior in example scene as well as on device in HoloLens 2 is actually pretty good. Resovling as fixed.
