### ISSUE TITLE
Stabilization and Depth Buffer Sharing

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#4733]
## Describe the problem

When enabling depth buffer sharing the stabilization of renderables greatly diminishes when a user looks at a renderable that has a material which does not write to the depth buffer.

## Describe the solution you'd like

I would like the MRTK to warn the user that the material they are using will not work correctly with depth buffering sharing.

## Additional context

This has been a common pain point for HoloLens 2 users which don't understand why their holograms look distorted or unstable.

**Comment by Troy-Ferrell** [comment]
Love the idea! Only caveat that might be tricky with this is that transparent items are fine if they have an opaque backing. Also other than maybe selecting the hololens 2 profiles, how would you know the developer is using MRTK for HL2?

**Comment by Cameron-Micka** [comment]
That's a good point, I don't know of a nice way to detect if the material is being used in conjunction with another "nearby" material that writes depth. Maybe in the warning we could link to an article that talks about creating depth safe content?

 For checking if the user is using a HL2 I check if depth buffer sharing is enabled for the project (which seems to be available on Oculus and UWP VR apps only) before showing the warning.

**Comment by Cameron-Micka** [comment]
Fixed in #4734.
