### ISSUE TITLE
Toggle profiler button no longer works and diagnostics demo scene is now empty

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4738]
## Overview
After #4708 removed the Diagnostics Demo Controls script, the ToggleFeaturesPanelPrefab prefab shows a missing script, and pressing the "toggle profiler" button no longer works.
![image](https://user-images.githubusercontent.com/168492/59011785-9ac1cd00-87ea-11e9-9b86-d3d86fd1e5af.png)

Additionally, the Diagnostics demo scene is now empty. It might be good to just remove this scene and the folder structure, since there isn't much to show there any more.

## Expected Behavior
When I click the "toggle profiler" button in HandInteractionExamples scene, the profiler disappears.

![image](https://user-images.githubusercontent.com/168492/59011855-cc3a9880-87ea-11e9-82ae-981c90a84ce5.png)

## Actual Behavior
Nothing happens.

**Comment by julenka** [comment]
I was able to work around this by adding "Diagnostics System Voice Controls" component to ToggleFeaturesPanel and hooking up the buttons to its "Toggle Visualization" method.
![image](https://user-images.githubusercontent.com/168492/59012032-3eab7880-87eb-11e9-8ea6-b4f7b7b1beef.png)

**Comment by davidkline-ms** [comment]
> work around this by adding "Diagnostics System Voice Controls" component

This change may cause issues as the voice controls script is automatically added with the diagnostics system.  I'll see about writing a small script specific to this scene.

**Comment by julenka** [comment]
I'm fixing this as part of another change since it was bugging me :)

**Comment by julenka** [comment]
merged.
