### ISSUE TITLE
Upgrade the project to 2018 LTS release

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#4739]
## Describe the bug

Was reviewing some issues / PR's today and noticed the project version has not yet been updated to the 2018 LTS release in development.

Is there a reason for this, if not, get it done :D

## To reproduce

Look at projectversion.txt or open Unity in the LTS release and see warning

## Expected behavior

Should be at the highest release in the currently supported version

**Comment by wiwei** [comment]
I think that we're waiting on getting the LTS version on the CI build machines before we do this - we're currently working on that part so this should happen soon (TM)

**Comment by MenelvagorMilsom** [comment]
There's already two PRs open for this:
#4756
#4468

**Comment by wiwei** [comment]
Horray

**Comment by keveleigh** [comment]
Fixed via #4756 and #4758
