### ISSUE TITLE
Change documentation link for creating a service, to point to the documentation for creating a service.

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#4740]
## Describe the bug

Although absolutely awesome (well done @Railboy ) the documentation link on the "Create Extension Service" functionality only points to the root of the MRTK docs.  

It should jump direct to the page describing services and what creating them means, else users have to jump through hoops as to why / how they are creating a service.

## To reproduce

1. Click on  "Mixed Reality Toolkit -> Utilities -> Create Extension Service"
2. Click on Documentation

## Expected behavior

The user should see the services documentation or at least documentation about creating a service.

## Actual behavior

User is taken to the root of the docs structure

**Comment by wiwei** [comment]
I think @davidkline-ms has the "how to do this thing" on his backog somewhere, 

I guess in the interm probably pointing to https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Utilities/ExtensionServiceCreationWizard.html would be better than the root though.
