### ISSUE TITLE
Failed to start Keyword and Dictation recognizer

### ISSUE THREAD

**Issue by mattandria** [microsoft/MixedRealityToolkit-Unity#4747]
## Describe the bug

I'm following the "Getting started with MRTK" guide on https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html, and I'm facing some errors when I run the example scene `HandInteractionExamples`.

## To reproduce

1. Run the scene named `HandInteractionExamples`

## Expected behavior

No error on the console

## Screenshots

![Erreur_Unity](https://user-images.githubusercontent.com/38125978/59033291-a5bb4280-8868-11e9-8a88-50a150e1d273.PNG)

## Your Setup (please complete the following information)

- Unity Version 2018.3.7f1
- MRTK Version v2.0.0 RC1

## Target Platform (please complete the following information)

- Simulation on Unity (first)
- HoloLens (later)

## Additional context

I have installed Windows SDK 18362 as it is said in the guide.

**Comment by wiwei** [comment]
Oddly enough, I thought we made some changes here to make these non-critical. We'll double check what's going on here.

If you don't need the voice/speech stuff and want to check out the other things, you can do the following to workaround this issue:

![image](https://user-images.githubusercontent.com/5840182/59037104-72a38f80-8825-11e9-9d91-fb619f47e620.png)

Basically press those little things that don't look like buttons but actually are, they will remove the speech/dictation stuff from the system.

**Comment by mattandria** [comment]
How do I access to this window?

**Comment by Troy-Ferrell** [comment]
@mattandria , please see instructions below

1) Select "MixedRealityToolkit" object in your scene and make sure the Unity Inspector window is open
2) Select "Input" tab on left hand side
3) Select "Input Data Providers" which opens foldout
4) Follow Will's instructions above for rest

**Comment by mattandria** [comment]
@Troy-Ferrell thank you, I found it and I have disabled Dictation and Speech Input. 
Now the scene is working !!!!

**Comment by wiwei** [comment]
I don't think we can guarantee that every system will have correctly set up privacy/speech settings to make the underlying Unity Dictation/Keyword APIs work - nevertheless, we should just not die when this happens.

**Comment by julenka** [comment]
Adding Urgency-Now tag because it is completely blocking partners at hack weeks with no known workarounds. They have updated to RC2 release.

**Comment by julenka** [comment]
This is completely blocking partners because they want to use speech input but have no way to test this in the editor.

**Comment by googlan** [comment]
I've tried to repro this one on the recent version of `mrtk_development` and it seems to be fixed. Errors with dictation and keyword recognizer are not fatal after #4498 .

**Comment by googlan** [comment]
@julenka no change needed on mrtk_dev, but I can keep this issue open until you confirm nobody is blocked by this (in case fix needs to be cherry-picked from dev branch).

@mattandria I saw that you are unblocked by now, but in case you need dictation/speech functionality, this issue is fixed in `mrtk_development` branch.

**Comment by wiwei** [comment]
Closing this out based on @googlan's latest comments. Feel free to reopen with updated information if this is still a problem.
