### ISSUE TITLE
[RC2 Build Call] Slider, scroll bar and text selection don't react to hand movements on HL1

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4750]
## Describe the bug

Slider, scroll bar and text selection in HandInteractionExample don't react to hand movements on Hololens 1

MRTK RC2 Build Call
Unity 2018.4

**Comment by julenka** [comment]
This is for Unity UI, by the way.

**Comment by julenka** [comment]
I'll take a look
