### ISSUE TITLE
Touch ScreenKeyboard invokes Twice

### ISSUE THREAD

**Issue by arunrajselvaraj** [microsoft/MixedRealityToolkit-Unity#4751]
## Describe the bug

I use Unity.Ui Inputfiled to process text from user. To invoke keyboard, using
 ` touchKeyBoard = TouchScreenKeyboard.Open(text, TouchScreenKeyboardType.EmailAddress, false, false, false, true);
        TouchScreenKeyboard.hideInput = true;` 

Touch screen keyboard is invoked but comes in twice 

- Keyboard appears twice
- Assist input field attached to keyboard is not displaying the text
- As per `TouchScreenKeyboard(string text, TouchScreenKeyboardType keyboardType, bool autocorrection, bool multiline, bool secure, bool alert, string textPlaceholder, int characterLimit);` alert, placeholder are not working. 

## To reproduce

1.  use any inputfield to generate this error. 

## Expected behavior
- Keyboard to appear once, while clicking on inputfield
- Assist field along the keyboard should show the typing text
- Alert type keyboard to be invoked
- keyboard to show place holder text 

## Your Setup (please complete the following information)

- Unity Version [2018.4.0]
- MRTK Version [v2.0.0-RC1-Refresh]

## Target Platform (please complete the following information)
- HoloLens 2

**Comment by Yoyozilla** [comment]
@julenka new keyboard issue?

**Comment by julenka** [comment]
Looks like a new one. I've actually never even seen keyboard being invoked from Unity UI text field so it's great to see that this person got that working.
________________________________

**Comment by arunrajselvaraj** [comment]
Just to add one more point, `TouchScreenKeyboard.Open()`, opens the keyboard at point of application start positions / direction. Its not appearing at the point where the UI.Inputfiled is facing to the user. Is there a way to control the position of keyboard invoking ?

Thanks

**Comment by julenka** [comment]
Hi, is this in HoloLens 1, or HoloLens 2? last I checked TSK.Open() will place the keyboard in front of the user.

**Comment by arunrajselvaraj** [comment]
Am experiencing this in Hololens 2. 
yeah it will come in-front of user. but on first click we have to search for keyboard. i.e on making little rotation( user ) it comes in front of user. other wise its on the starting point of application.

**Comment by julenka** [comment]
Interesting, I've actually never seen that behavior. It would be very helpful to have that issue (when you launch keyboard it appears at origin) filed separately from the main issue described here "Touch Screen Keybaord invokes twice", since these are two separate issues. Could you please file a separate issue for the second problem you are seeing, so we can make sure to track each one?

**Comment by arunrajselvaraj** [comment]
> 
> 
> Interesting, I've actually never seen that behavior. It would be very helpful to have that issue (when you launch keyboard it appears at origin) filed separately from the main issue described here "Touch Screen Keybaord invokes twice", since these are two separate issues. Could you please file a separate issue for the second problem you are seeing, so we can make sure to track each one?

created  https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4790

**Comment by julenka** [comment]
This is actually an OS level issue that has been fixed in recent builds of HoloLens 2. Closing since it has been fixed, should be available in a Hololens 2 update.
