### ISSUE TITLE
MRTK API Review to enable runtime access and extensibility

### ISSUE THREAD

**Issue by Yoyozilla** [microsoft/MixedRealityToolkit-Unity#4766]
We need to review all of current API to make sure MRTK is extensible and accessible at runtime.

**Comment by Yoyozilla** [comment]
#441

**Comment by wiwei** [comment]
Chatted offline on this one - this is a pretty open ended can of worms with no real way of validating if the changes are actually going to be immediately beneficial in GA. Instead we'll take the set of issues we're already addressing for extensibility and use that to see if there are fundamentally concerning things we may have around breaking changes in the future

**Comment by wiwei** [comment]
This a very open ended task which is basically "read all of the code and see what needs to be public" which isn't super helpful given where we are in the process

**Comment by Yoyozilla** [comment]
As discussed this morning, this is about understanding that there is no big underlining issue to make things more accessible at runtime. If we go through the exercise of instantiate a button at run time, and change it's inspector-exposed properties via code, and prove this can be done additive post GA. Then we can close this

**Comment by polar-kev** [comment]
Closing this in favour of specific feature related issues that do not hold true to run time access/extensibility.
