### ISSUE TITLE
Consolidate the location of the eye-related settings in our profiles

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4773]
Folks looking at eye and gaze related settings tend to get really confused because the settings are so disjoint - we have an eye gaze provider (which is under the data providers section), we have another section under Pointers that has a gaze related setting, and then we have other gaze settings on input simulation areas.

If we cannot consolidate them for whatever reason, we should document why and also provide clearer guidance about just where everything is.

**Comment by polar-kev** [comment]
Putting this on your radar since you're making profile improvements @RogPodge.

**Comment by Zee2** [comment]
Profiles have been (mostly) burninated in MRTK3.
