### ISSUE TITLE
.NET performance with hands (Release build) is slow

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4774]
With the .NET backend enabled (and release build, as Master doesn't currently work because we don't currently have a workaround for the .NET native bug), just having two hands in view causes a significant FPS drop (~15fps).

When I was profiling this using device portal perftraces earlier, I noticed significant overhead in the Unity event dispatch (i.e. the unity events system). Tentatively it seemed like maybe switching to using flat C# delegates/callbacks (the tricky part is that the unity profiler doesn't show time spent in unity itself.

It would also be worth looking at this under the unity profiler again (.NET) as we were mostly looking at it from IL2CPP side.

**Comment by Troy-Ferrell** [comment]
This should likely be kept around with the other performance bugs

**Comment by davidkline-ms** [comment]
MRTK3 is being built with performance very much in mind. If specific issues are found, please file them and mark as MRTK3.

Thanks!
