### ISSUE TITLE
Tests for Slate aka HandInteractionPanZoom

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4781]
## Overview
Write five tests to give confidence that slate aka HandInteractionPanZoom will not break when somebody makes a change. The tests should most likely be PlayMode tests to ensure that end to end behavior works.

## Test List
- [ ] HandInteractionPanZoom works with physical finger touch
- [ ] HandInteractinPanZoom works with articulated hands at distance
- [ ] HandInteractionPanZoom works with HoloLens 1 gestures
- [ ] Scrolling , panning works
- [ ] Zooming with two inputs works

**Comment by wiwei** [comment]
@julenka Is this the same as https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4727?

**Comment by julenka** [comment]
Yes, whoops.

**Comment by julenka** [comment]
Duplicate of #4727
