### ISSUE TITLE
Touch screen keyboard opens at Start point of Application

### ISSUE THREAD

**Issue by arunrajselvaraj** [microsoft/MixedRealityToolkit-Unity#4790]
## Describe the bug

TouchScreenKeyboard.Open(), opens the keyboard at point of application start positions / direction. Its not appearing at the point where the UI.Inputfiled is facing to the user. Is there a way to control the position of keyboard invoking ?

## Expected behavior

Touch screen keyboard appears in-front of user

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.4.0]
- MRTK Version [v2.0.0-RC1-Refresh]

## Target Platform (please complete the following information)

- HoloLens 2

## Additional context

On first click we have to search for keyboard. i.e on making little rotation( user ) it comes in front of user. other wise its on the starting point of application.

**Comment by Troy-Ferrell** [comment]
Unfortunately there is not. The virtual keyboard is a system/shell feature, not an MRTK feature. The API TouchScreenKeyboard.Open() is also actually provided by Unity. The keyboard will spawn to face the user, not a particular hologram or gameobject
