### ISSUE TITLE
Horizontal Surface Magnetism, z-axis Rotation Issue

### ISSUE THREAD

**Issue by orenono** [microsoft/MixedRealityToolkit-Unity#4800]
## Describe the bug
I'm using Solver Handler+  Surface Magnetism to have an object float over the room's surfaces.

Everything works as expected on vertical surfaces, however on horizontal surfaces the object will often keep rotating on the Z-axis without stabilizing according to the headset location. 

## To reproduce

I've attached a screenshot of the settings.
## Expected behavior

When placing the object on horizontal surfaces, the object's z-axis should face the HoloLens's direction (as it does on vertical surfaces).

## Screenshots

![Settings](https://user-images.githubusercontent.com/10733786/59207015-2c776480-8b74-11e9-9138-746862fd9904.JPG)

## Your Setup (please complete the following information)

- Unity Version 2018.3.14f
- MRTK Version 2 RC1 Refresh

## Target Platform (please complete the following information)

- HoloLens

**Comment by Troy-Ferrell** [comment]
@orenono there is PR (linked above) to fix this but if I understand your desires correctly, you actually have the wrong parameters set. You should set OrientationMode to "Vertical" (which will translate to "TrackedTarget" - just a rename, same enum value). This will keep the GameObject facing the camera.
