### ISSUE TITLE
Speech demo not working

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4809]
We got this feedback a while back but I don't see an issue already open for it - it was around how the speech sample didn't work. 

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/895c408b9c58703ebd7b2748191678f574aaa877/Documentation/Input/Speech.md

In particular, the thing that that doc references. It's possible that other changes since (this was months ago) have made things good now, but we should just double check it.

**Comment by googlan** [comment]
Checked this on the latest `mrtk_development`, demo seems working as intended. I was able to add speech commands and actions as well. Documentation part seems to be up-to-date as well.
