### ISSUE TITLE
Add mechanism to check for feature availability on the runtime platform

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#4817]
There have been many questions from customers on how to differentiate HoloLens 2 from the original HoloLens in order to know, at runtime, if a new feature is available.

Since MRTK is cross platform and other platforms may support features similar to HoloLens 2, the ideal approach is to not burden the developer on maintaining the knowledge of each platform's features and instead provide a simple runtime capability check.

For example, such a check _might_ take the form of:

```
if (MixedRealityCapabilities.Check(ArticulatedHands))
{
  // Perform articulated hand specific code
}
```

**Comment by wiwei** [comment]
I think that we already have an issue tracking this:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4250

Closing this one out based on that - feel free to reopen if this is a different issue.
