### ISSUE TITLE
Hololens 2 System keyboard for Unity Editor

### ISSUE THREAD

**Issue by derekfreed** [microsoft/MixedRealityToolkit-Unity#4823]
In MRTK with first HoloLens it was possibly to use the holographic keyboard within the Unity Editor.
In MRTKv2 for HoloLens 2 using the keyboard in the editor is no longer possible due to the leveraging of the OS's keyboard (which is great). Would it be possible to add a holographic keyboard from original MRTK skinned like the new HoloLens OS to be used when in the Unity Editor?

**Comment by Alexees** [comment]
I've been working on porting the HTK keyboard over #6466

**Comment by julenka** [comment]
Fixed in #6492
