### ISSUE TITLE
ServiceInspectors assembly has dependencies on individual service binaries

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#4825]
Core assemblies should not have dependencies on service, platform or feature assemblies.

The new service inspectors assembly directly references
- services.boundary
- services.input
- services,scenesystem
- services.spatialawarenss
- services.teleport

**Comment by davidkline-ms** [comment]
Per offline design discussion, giving to @Railboy to address.

Thanks, sir!

**Comment by julenka** [comment]
fixed.
