### ISSUE TITLE
Editor Hand Simulation Mesh Collapsing to a single point

### ISSUE THREAD

**Issue by anuitz** [microsoft/MixedRealityToolkit-Unity#4827]
## Describe the bug

A few of us are hitting an issue where the joints in the editor hand simulation appears all on the exact same point. We are consuming the v2.0.0-20190521.3 MRTK nuget package via MSBuild (not nuget for unity). We can't debug the issue because there are no debug symbols, which makes this rather challenging to solve on our own. Does anyone have any ideas about what is causing this and how to fix it?

## To reproduce

1. Make any scene and add MRTK to the scene and configure
2. Press Play
3. Press whatever key shows the hand sim

## Expected behavior

A full hand mesh. Instead there is the 3d gizmo and a bunch of small cubes collapsed into a single point

## Screenshots

![image](https://user-images.githubusercontent.com/51683688/59233981-9f4a0500-8b9f-11e9-9b65-2c40d9dc0985.png)

![image](https://user-images.githubusercontent.com/51683688/59233988-a53fe600-8b9f-11e9-81a1-5198f9131f50.png)

![image](https://user-images.githubusercontent.com/51683688/59233997-ab35c700-8b9f-11e9-952b-0062fa2b12c1.png)

## Your Setup (please complete the following information)

- Unity Version 2018.4.1f1
- MRTK Version v2.0.0-20190521.3 

## Target Platform (please complete the following information)

This is during the editor step, by the target will be Hololens 2

**Comment by lukastoenneMS** [comment]
I have a pretty good hunch what is happening here:

The `MixedRealityToolkitFiles` utility class is used to look for resource files based on relative paths: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/bffa2f2345c1bf531c3b09f79c49bcfa53b22d08/Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs#L87

This expects either a "MixedRealityToolkit.Services" or "MRTK.Service" base path to find the simulated hand poses in `<basePath>/InputSimulation/ArticulatedHandPoses/` (any parent directory will work as long as the path ends with this combination). That works alright for the git repository and the Unity package.

However, the directory structure of the nuget package is such that the pose data files end up in `Microsoft.MixedReality.Toolkit.Services.<version>/MRTK/InputSimulation/ArticulatedHandPoses` which does not match the expected pattern.

I'm not sure what the correct fix for this would be, possibly the nuget package paths can be updated or the MixedRealityToolkitFiles utility improved.
