### ISSUE TITLE
Typing after Speech Dictation doesn't register key presses

### ISSUE THREAD

**Issue by rwedoff** [microsoft/MixedRealityToolkit-Unity#4837]
## Describe the bug

When I open the keyboard in the example scene with OpenKeyboard.cs, the keyboard opens successfully and I can type. Then I try to use the Speech Dictation. When the speech to text is entered correctly. Then, I attempt to go back to type again, however, the keyboard does not register the key events anymore until I restart the app.

## To reproduce

1. Go to the example scene.
2. Click on open keyboard button
3. Type some characters.
4. Start the speech to text dictation, say some words.
5. Stop dictation.
6. Type some more words.
4. See error (the user can no longer type with the keyboard).

## Expected behavior

After speech dictation, the user should be able to continue typing.

## Your Setup (please complete the following information)

- Unity Version 2018.3.10f1
- MRTK Version vNext Lastest Master

## Target Platform 
- HoloLens 2

## Additional context

Note, that you can still delete text in the text box and you can still use Speech Dictation to enter text, but you can't type.

Probably not related, but this includes the workaround for the Unity keyboard closing issue.
(https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4373)

**Comment by philomathikus** [comment]
@wiwei Do you know if there's any workaround for this?

**Comment by hemasree99s** [comment]
Any idea on why dictated word repeats more than once when microphone button is clicked in keyboard
