### ISSUE TITLE
Porting guide incorrectly says to use radialsolver for billboard 

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4843]
The porting guide says to replace Billboard with Solver but the solver doesn't implement billboard behavior. MRTK alread contains a billboard script so there's no need to have this row.

**Comment by keveleigh** [comment]
The porting intent was to use radial view with `Reference Direction` set to `Object Oriented` and the `Tracked Object To Reference` set to `Head`, which should billboard it towards you (these settings should probably be added to the guide as well).
Migrating over the actual Billboard script wasn't originally intended (we wanted to replace as many one-off utilities with solvers as possible), but we decided not to remove it once we realized it had been added to the repo.

**Comment by Troy-Ferrell** [comment]
@keveleigh that doesn't actually work for billboard though. Billboard generally is just rotation to face user, radialview will translate the model. It also doesn't seem to possible to lock what axis of rotation are possible.

**Comment by keveleigh** [comment]
@troy-ferrell If you turn off the clamps at the bottom, the object should stay in place and only billboard:
![image](https://user-images.githubusercontent.com/3580640/60045131-ebee0f80-9678-11e9-89ca-b3d518b9e42e.png)

You're right that it doesn't seem to be possible to lock the axes of rotation though.
