### ISSUE TITLE
EyeTrackingTarget does not properly override methods from InputSystemGlobalListener

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#4849]
## Describe the bug

The class EyeTrackingTarget does not override Start and OnDisable properly (Throwing warnings when compiled). The correct implementation of this would mean that the base class InputSystemGlobalListener changes its Start methods return type to Task as it's async resulting in futher code changes in other classes.
OnDisable can be corrected just fine.

**Comment by wiwei** [comment]
Thanks for filing this! I think you pulled mrtk_development within the hour or two where this existed - this should be fixed by:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4845

**Comment by wiwei** [comment]
Ah, wait, I missed the async part. Lemme fix that.

**Comment by Alexees** [comment]
@wiwei just wanted to inform you, that now I get a compilation warning:

> Assets\MixedRealityToolkit\MixedRealityToolkit.SDK\Features\Input\Handlers\EyeTrackingTarget.cs(145,39): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.

What will happen if you override InputSystemGlobalListener and you depend on the InputSystem? I would say code fails then. You'd need to await the base call, but then it needs to return Task, which does change it from being a Unity engine callback.
What about sealing the base Start and do a Task.Run on a seperate method that can be overridden properly?
