### ISSUE TITLE
Initial setup of Hololens2, typing very hard as calibration not an option till registered.

### ISSUE THREAD

**Issue by NickvandenBerg** [microsoft/MixedRealityToolkit-Unity#4860]
## Describe the bug

When first setting up the Hololens2 and logging into to your profile, entering Wifi pasword etc it is quite hard to type on the keyboard due to no calibration app running so it being at the default IPD.

You are unable to run the calibration app as it is locked behind in the normal windows menu screen which you can't access until you have registered. Basically a catch 22.

Would be ideal to first have the calibration app run as default before the setup screen, and then it saves this information and assigns it to the first user.

A secondary less preferred option is to run the calibration app, have it assign a temporary IPD to the user, finish the setup and then rerun the calibration to assign a permanent IPD.

Either way will allow for a more easier starting experience. 

## To reproduce

1) Flash a device
2) Enter the registration mode
3) Type in your email/wifi password to bring up the keyboard

## Expected behavior

Would expect to be able to type easily on the first menu screen.

## Screenshots

n/a

## Your Setup (please complete the following information)

- Unity Version  2018.4.2.f1
- MRTK Version  v2.0 RC1 refresh

## Target Platform (please complete the following information)

- HoloLens 2

## Additional context

Bug discovered at Melbourne MR Hololens 2 hack.

**Comment by wiwei** [comment]
We can carry on this feedback to the underlying OS team - from what I can gather from this issue, this is actually feedback for the HoloLens 2 out of box/initial setup experience and not MRTK related.

**Comment by julenka** [comment]
Thanks for the feedback! We are working on improving eye calibration experience internally. Closing as we can't do much about it in MRTK. I've passed this feedback along.
