### ISSUE TITLE
Guidance for upgrading build to build

### ISSUE THREAD

**Issue by grbury** [microsoft/MixedRealityToolkit-Unity#4861]
## Describe the Issue
Difficult to know the steps for importing from various versions.  Are there steps to take in various cases?  Should I remove existing MRTK and import or import side by side?  What happens with file directory changes?  Is it the same if I'm going from HTK to MRTKv2?  RC1 > RC2?  etc

## Feature Area
Docs

## Existing Doc Link
https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/v2.0.0-RC2

**Comment by wiwei** [comment]
This is something we didn't do great for the Refresh -> RC2. I'm changing some tags around to reflect that this isn't actually just a documentation thing, but we need to spin up some work to have a representative project + pipeline for us to go through to validate future releases.

**Comment by wiwei** [comment]
Okay, I spent some time upgrading the https://github.com/microsoft/MRDL_Unity_PeriodicTable app, I found an issue and fixed it.

Looks like the RC1 Refresh -> RC2.1 instructions worked well in this case, so we should be good to re-issue the same instructions included in RC2.1
