### ISSUE TITLE
Adding MRTK to scene with colliders reduces framerate even when input system not used

### ISSUE THREAD

**Issue by jackiebecker** [microsoft/MixedRealityToolkit-Unity#4863]
Adding MRTK v2 to scene, despite not integrating features or doing additional work, caused perf to be eaten up by toolkit. 

Notes:
* MRTKv2 input system active in scene, not being used for anything
* Hand mesh and joints off
* Scene has large number of colliders. However, in HoloLens 1 the raycast against those colliders are not impacting perf that much.

## Screenshots

<img width="951" alt="Capture1" src="https://user-images.githubusercontent.com/13605689/59395767-e1a25a80-8dc8-11e9-8ed1-66a09bfde1f9.PNG">

<img width="951" alt="Capture2" src="https://user-images.githubusercontent.com/13605689/59395776-e9fa9580-8dc8-11e9-9144-bc917ba11db8.PNG">

Setup:

- Unity Version 2019.1
- MRTK Version v2

Target Platform:

- HoloLens 2

**Comment by IsaacSurfraz** [comment]
There is no perf hit that is recognizable on HoloLens 1, if that helps.

**Comment by Troy-Ferrell** [comment]
Tried adding MRTK to new scene with 50 spheres. Slight overhead of of 0.2 to 0.5 ms on laptop. Update to latest version of MRTK (as of July 23rd) to see if performance difference now. Without additional information, closing this issue.
