### ISSUE TITLE
Consider changing the deployed MRTK directory structure

### ISSUE THREAD

**Issue by keith-phillips** [microsoft/MixedRealityToolkit-Unity#4864]
Currently when you deploy the MRTK, it creates a number of top-level directories:
- Assets/MixedRealityToolkit
- Assets/MixedRealityToolkit.Providers
- Assets/MixedRealityToolkit.SDK
- Assets/MixedRealityToolkit.Services

Consider changing the deployed structure of the MRTK to move everything under a single top-level directory, e.g.
- Assets/MRTK/MixedRealityToolkit
- Assets/MRTK/MixedRealityToolkit.Providers
- Assets/MRTK/MixedRealityToolkit.SDK
- Assets/MRTK/MixedRealityToolkit.Services

This would allow us to control the MRTK as a separate git submodule, which provides some nice benefits:
- It's more obvious if we ever make changes to the MRTK code, as opposed to our own scripts
- If we do ever make any changes, we can keep our own branch of the submodule and easily merge with new versions
- It's simpler to extract any patches we make to submit a PR upstream

Currently any user-derived profiles, etc that are created go under a different top-level directory:
- Assets/MixedRealityToolkit.Generated

It would probably make most sense for these to remain at this level, so that user-generated files don't clutter up the directory with the original MRTK code in it.

**Comment by wiwei** [comment]
We have some work which would make our package UPM compliant, which I believe ends up getting placed in the Packages folder instead of the root assets - this might also help with the issue that we're hitting here (it won't clutter up your project folder that way)

**Comment by gilbdev** [comment]
my current working solution : 
- have the whole mrtk repo as a submodule
`git submodule add -b mrtk_release --force your/git/repo/fork/Microsoft_MixedRealityToolkit-Unity Subrepos/MixedRealityToolkit-Unity`
 
- add some symlinks for each fo the 4 subfolders in your Unity project (named Unity folder here)

`mklink /D Unity\Assets\MixedRealityToolkit ..\..\Subrepos\MixedRealityToolkit-Unity\Assets\MixedRealityToolkit`

**Comment by wiwei** [comment]
Okay, finally got around to this one - so I think for our unity package, we'll probably keep the current structure around where it is put initially (for now), but now with https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5483 it's possible to put MRTK in a non-root folder (there were a few issues where some specific things weren't working outside of the non-root folder).

@davidkline-ms @keveleigh FYI.
