### ISSUE TITLE
[RC2] PressableButton planes are in wrong location after restarting Unity

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4870]
## Overview
Some pressable buttons that have a movingVisuals with a non-zero z local position will have their planes moved way off the button when you enter play mode, even though in edit mode the buttons look fine.

## Repro steps:
1. Create empty unity project
2. Import RC2 release
3. Unzip the following folder "Scenes" into the Assets folder
4. Examine Buttons/Deep/MyButton and see planes show up correctly over button
![image](https://user-images.githubusercontent.com/168492/59418095-c0169280-8e0b-11e9-9ee4-20be49003984.png)
5. Hit play and observe the planes are now completely off the button:
![image](https://user-images.githubusercontent.com/168492/59418181-ef2d0400-8e0b-11e9-9eea-a32842b93fc3.png)

[Scenes.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3284995/Scenes.zip)

Note that the root cause seems to be that the moving button visuals object has a non-zero local space z:

![image](https://user-images.githubusercontent.com/168492/59418261-1388e080-8e0c-11e9-9333-7e4850e7d0e0.png)

**Comment by paco-ms** [comment]
See #4527 for changes that probably triggered this regression.
