### ISSUE TITLE
Interactable OnFocus not responding after hiding GameObject

### ISSUE THREAD

**Issue by ColinPeigne** [microsoft/MixedRealityToolkit-Unity#4871]
## Describe the bug

OnFocus event of Interactable script is not responding after a GameObject was set inactive by calling OnClick from the same Interactable script and then active back from another Interactable Button

## To reproduce

Create new Scene
Add MRTK to the scene
Add one 3D Object cube (1)
Add another 3D Object cube (2) with MRTK Interactable script
Add OnClick Event, drag (2), select GameObject and SetActive to false
Add OnFocusReceiver event, OnFocus() drag (1) and select GameObject SetActive to false and OnFocusOff() drag (1) and select GameObject SetActive to true
Add a MRTK Button prefab and add a OnClick event, drag (2) and select GameObject SetActive to true
(1) is not showing when pointer is on (2), OnFocusEnter is not called

## Expected behavior

OnFocusEnter is called

## Screenshots

![ScreenShot1](https://user-images.githubusercontent.com/51783339/59424161-c8eb7200-8dd3-11e9-93f4-b2bb4df20098.png)
![ScreenShot2](https://user-images.githubusercontent.com/51783339/59424166-cab53580-8dd3-11e9-80a0-efb0f3b6e458.png)

## Your Setup

Unity 2018.3.11f1
Mixed Reality Toolkit 2.0.0-RC2

## Target Platform

- HoloLens

May be related to #3577

**Comment by CDiaz-MS** [comment]
This issue has been resolved in the latest release, MRTK 2.0.0. 
 [Issue 4871 Testing](https://youtu.be/6FlawkVWRWg)
