### ISSUE TITLE
Cloning MixedRealitySpatialMeshObserver modifies DefaultMixedRealitySpatialAwarenessSystemProfile

### ISSUE THREAD

**Issue by timGerken** [microsoft/MixedRealityToolkit-Unity#4874]
## Describe the bug

With the DefaultMixedRealitySpatialAwarenessSystemProfile selected, cloning MixedRealitySpatialAwarenessMeshObserver causes DefaultMixedRealitySpatialAwarenessSystemProfile.asset to change

## To reproduce

1. `git clone http://github.com/Microsoft/MixedRealityToolkit-Unity mrtk`
1. `cd mrtk`
1. `git checkout mrtk_release`
1. Launch Unity 2018.4.1f1 and open the cloned mrtk project from above
1. Select MixedRealityToolkit -> Add to Scene and Configure... from the menu bar
1. Choose "Default HoloLens2ConfigurationProfile" if prompted
1. Select the "MixedRealityToolkit" GameObject in the hierarchy
1. Select "Spatial Mapping" in the inspector
1. Under "Windows Mixed Reality Spatial Mesh Observer" select "Clone"
1. `git status`

**Observe:**
```
C:\src\GitHub\Microsoft\mrtk [mrtk_release ≡ +2 ~1 -0 !]> git status                                                                                   On branch mrtk_release
Your branch is up to date with 'origin/mrtk_release'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealitySpatialAwarenessSystemProfile.asset

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        Assets/MixedRealityToolkit.Generated.meta
        Assets/MixedRealityToolkit.Generated/

no changes added to commit (use "git add" and/or "git commit -a")
```
## Expected behavior

Cloning the Spatial Mesh Observer should be disallowed until the Spatial Awareness System has been cloned.

## Your Setup (please complete the following information)

- Unity Version: 2018.4.1f1
- MRTK Version: v2.0 RC2

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
I'm not able to repro this, since the Clone button is disabled by default. Clicking the button doesn't appear to do anything.

![image](https://user-images.githubusercontent.com/3580640/59534362-f6ebb780-8ea2-11e9-8103-fd4b8f15c2d3.png)

Is it possible you unlocked your profiles? I think that setting might be global instead of per-project.

![image](https://user-images.githubusercontent.com/3580640/59534408-1256c280-8ea3-11e9-90a4-3afe3b749240.png)

**Comment by timGerken** [comment]
@keveleigh Glad I included the detailed repro steps :)
Took me forever to find this setting:
![image](https://user-images.githubusercontent.com/14828396/59588564-d197bd00-90df-11e9-9902-d14f71070f69.png)
Is it really a global setting? Seems dangerous if so.

**Comment by keveleigh** [comment]
>Is it really a global setting? Seems dangerous if so.

Looks like I was (happily!) incorrect: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/895c408b9c58703ebd7b2748191678f574aaa877/Assets/MixedRealityToolkit/Inspectors/MixedRealityPreferences.cs#L35

`EditorPreferences` uses `Application.productName` as part of the key;
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/9ab0e9b69afe45f7856b5731436ae427c3fe7cc4/Assets/MixedRealityToolkit/Utilities/Editor/EditorPreferences.cs#L33

**Comment by wiwei** [comment]
Closing this one out, feel free to reopen if this is still happening in mrtk_development
