### ISSUE TITLE
Shader warning on importing the MRTK RC2

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#4877]
## Describe the bug
Warning errors given on a fresh import of the MRTK RC2

Warning 1:
```
Shader warning in 'Mixed Reality Toolkit/HandTriangles': loop only executes for 1 iteration(s), forcing loop to unroll at line 695 (on d3d11)

Compiling Geometry program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR
```

Warning 2
```
Shader warning in 'Mixed Reality Toolkit/HandTriangles': Use of UNITY_MATRIX_MVP is detected. To transform a vertex into clip space, consider using UnityObjectToClipPos for better performance and to avoid z-fighting issues with the default depth pass and shadow caster pass.
```

## To reproduce

1. Create a new Project
2. Import MRTK RC2
3. View warnings

## Expected behavior

No warnings or errors

## Your Setup (please complete the following information)

- Unity Version 2019.1.5f1
- MRTK Version RC2

## Target Platform (please complete the following information)

- Unity

**Comment by Cameron-Micka** [comment]
Thank you for reporting this Simon! This should be addressed in this pull request: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4836
