### ISSUE TITLE
Update Text Mesh Pro to Natively Support Single Pass Instanced Rendering

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#4881]
## Describe the problem

Unity recently updated the Text Mesh Pro package to support single pass instanced rendering. We should update the package the MRTK uses so that users are not required to manually update newly created Text Mesh Pro materials to use the MRTK/Text Mesh Pro shader.

## Describe the solution you'd like

Update the Text Mesh Pro package version in the package manifest.

**Comment by wiwei** [comment]
@Cameron-Micka - is this just as simple as updating the TMP version number in our project json file?

**Comment by Cameron-Micka** [comment]
Yes it is! Then obviously testing.

**Comment by Cameron-Micka** [comment]
Looks like the latest version of Text Mesh Pro (1.4.1) is still missing SPIR support. :( 
```
		struct vertex_t {
			float4	vertex			: POSITION;
			float3	normal			: NORMAL;
			fixed4	color			: COLOR;
			float2	texcoord0		: TEXCOORD0;
			float2	texcoord1		: TEXCOORD1;
		};
```

We should still take a update to get the latest bug fixes.

**Comment by elbuhofantasma** [comment]
SPIR is currently supported in the version of TMP that we use in the latest MRTK release, so I am closing this issue.
