### ISSUE TITLE
Manipulation handler does not rotate object.

### ISSUE THREAD

**Issue by junpark12** [microsoft/MixedRealityToolkit-Unity#4885]
## Describe the bug
Manipulation handler script does not scale simple object.

## To reproduce

1. Added Cube to the scene.
2. Attached manipulation handler to the object.
![image](https://user-images.githubusercontent.com/20918194/59483208-48964100-8ea7-11e9-9b4c-273f49620044.png)

3. Play the scene in unity editor.
4. Select the cube, try to rotate cube with "Q" and "E"  but does not work.

## Screenshots
Here's hands rotation setting.
![image](https://user-images.githubusercontent.com/20918194/59483308-c2c6c580-8ea7-11e9-9da8-83f52755c49f.png)

## Your Setup (please complete the following information)

- Unity Version 2018.3.14f1
- MRTK Version v2.0.0 RC2.1

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by Troy-Ferrell** [comment]
Using hand rays and rotating the simulated hand won't work as the hand ray comes from the index and not the palm, but only in simulation. 

Grabbing and rotating via the Q and E works in latest stabilization branch. Remember to add NearInteractionGrabbable to the GameObject as well with ManipulationHandler
