### ISSUE TITLE
Add DefaultCursor.prefab settings in MRTK profile 

### ISSUE THREAD

**Issue by benjamincoven** [microsoft/MixedRealityToolkit-Unity#4888]
## Describe the problem

Hello, I might missed it if it is already the case but that would be great to be able to change the settings of the prefab MixedRealityToolkit.SDK/Features/UX/Prefabs/Cursors/DefaultCursor.prefab somewhere else that directly in this file.

I changed the hoverlight radius by changing the prefab file but this is not the clean way since I lose this modifications when upgrading MRTK version.

## Describe the solution you'd like

Having something similar for the camera settings in the MRTK profile that would change the MonoBehaviour data.

**Comment by Zee2** [comment]
In MRTK3, we use prefabs to customize the rig and the cursor(s) therein! Nice and WYSIWYG.
