### ISSUE TITLE
Ci Runner compatibility and multi core appx build

### ISSUE THREAD

**Issue by jganser** [microsoft/MixedRealityToolkit-Unity#4890]
## Describe the problem

The appx build function was not working on the CI Runner due to different reasons.
* Not necessarily locking reload of assemblies, which can be done manually.
* StartCommandLineBuild killing the batchmode (application exit)
* StartProcessAsync never returning its result on CI machine (Batchmode...)
* appx build not using multi core functionality of msbuild

## Describe the solution you'd like

* StartCommandLineBuild introduces a flag for keeping the application alive, so that a appx build can be done from our own build tool script
* Sequencial solution for Process calls
* add flag for multi core builds with msbuild if desired
  * _reduces the overall build time needed to 50% on our CI Machine_
  * _reduces the appx build time needed to 33% on our CI Machine_

## Additional context

Solution can be found in [Pull Request](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4889)

**Comment by Zee2** [comment]
Closing as stale
