### ISSUE TITLE
MixedRealityToolkit-Unity.assetpackage missing sharing services

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#490]
The Sharing Service executable is missing from theunity asset package releases of the MRTK.

**Comment by NeerajW** [comment]
This is a tricky one as when creating asset packages the External folder really does not show up :)

**Comment by HodgsonSDAS** [comment]
Yeah, I think there is a way to do it though. We might just need to include the extra setup steps in the GettingStarted doc.

**Comment by Lordinaire** [comment]
I totally agree with @HodgsonSDAS, it will be nice to add some extra steps in the documentation.

The zip solution can be great! And split the asset package in two parts : _HTK base_ / _External_ ?

**Comment by HodgsonSDAS** [comment]
Did a bit of research today. We would need to use .NET 4.x but unity does not support past 3.5 just yet.

There are some libraries we could use, but I don't know how we would do that to keep the licensing compatible.

**Comment by NeerajW** [comment]
Following up more internally with @matthejo

**Comment by HodgsonSDAS** [comment]
I actually got something working today using powershell.

Keep an eye out for a PR

**Comment by HodgsonSDAS** [comment]
Done. Next time we make a package we just need to make sure that zip file is in there.

I'd also like to look into triggering the HoloLens Project Settings & Capabilities Window as soon as a user imports the asset package.

**Comment by S-Hodgson-MMOARgames** [comment]
Repro Steps:

1. New Project
2. Import HTK asset package
3. HoloToolkit -> Sharing Service -> Launch Sharing Service

![image](https://cloud.githubusercontent.com/assets/22268546/22616068/78f1ac84-ea73-11e6-91c8-b649dd9224c7.png)
