### ISSUE TITLE
Arrow keys don't work on System Keyboard

### ISSUE THREAD

**Issue by rwedoff** [microsoft/MixedRealityToolkit-Unity#4900]
## Describe the bug

When typing on the system keyboard, the left and right keys don't change where you are typing. While there isn't a cursor/caret, there the arrow keys don't update where you are typing.

## To reproduce

1. Go to HandInteractionExample scene.
2. Click on Open Keyboard
3. Type something on the keyboard
4. Press the left or arrow key
5. Type again, and see the characters are still entered on the right at the end of the string.

## Expected behavior

If I press the left arrow key and type again, I expect to type in the middle of the word instead of the very end of the word.

## Your Setup (please complete the following information)

- Unity Version 2018.3.10f1
- MRTK Version: latest dev branch

## Target Platform (please complete the following information)

- HoloLens 2

## Additional context

Most likely a Unity bug, however, it could also be an input service/system keyboard bug.

**Comment by Yoyozilla** [comment]
Kurtis could you take a look at see if this is an unity bug or we need to send it to the keyboard team?

**Comment by Yoyozilla** [comment]
@keveleigh

**Comment by julenka** [comment]
Fixed
