### ISSUE TITLE
For any object with Rigid Body, Bounding Box handles are not grabbable with Hand Ray.

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#4901]
For any object with **Rigid Body**, Bounding Box handles are not grabbable with **Hand Ray**.
You can experience this symptom with the Lunar Module in the HandInteractionExamples scene. Grabbing handles moves the object. It shows proper colliders and script order (BoundingBox.cs above ManipulationHandler.cs). When the Rigid Body is removed, handle works well.

![2019-06-14 11_43_57-Unity 2018 4 0f1 Personal - HandInteractionExamples unity - MRTK-Public-Microsof](https://user-images.githubusercontent.com/13754172/59531300-75902700-8e9a-11e9-8ec7-9fa2776a9d45.png)
![2019-06-14 11_43_53-Unity 2018 4 0f1 Personal - HandInteractionExamples unity - MRTK-Public-Microsof](https://user-images.githubusercontent.com/13754172/59531301-75902700-8e9a-11e9-8751-19a0b2c3c5f4.png)

## To reproduce
Open HandInteractionExamples scene.
With hand ray, grab the corner handle of the Lunar Module's bounding box
The object moves instead of scale/rotate

## Expected behavior
Scale & Rotate with handles

## Your Setup (please complete the following information)
mrtk_development
Unity 2018.4

**Comment by thalbern** [comment]
happens with WMR controllers as well

**Comment by thalbern** [comment]
this wasn't working because of a wrong setup in the input profile. I've added a warning to bounding box and a button to fix the setup 

![image](https://user-images.githubusercontent.com/36998103/65427148-9f49da00-de09-11e9-8942-d71d3d1d114d.png)
