### ISSUE TITLE
Rework of DefaultMixedRealityControllerMappingProfile

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#4903]
## Describe the problem

As new platforms will be added in the future, new Controllers will also be added into the mix. Right now, the DefaultMixedRealityControllerMappingProfile lists all currently supported controllers with fancy images, along with simple entries for controllers that do not support that.
Problems are the following:

- I always have all the controllers listed, even though I might only be interested in just the Vive Knuckles.
  - This slows down the Unity inspector
  - Controllers do not show any relationship to their controllers
- There is currently no way we can add new controllers with images (Oculus Go) and fancy controller overview schemes
  - this is probably fine for the generic versions of controllers

## Describe the solution you'd like

Controllers should be shown along with their respective DeviceManagers. Since those have their controller responsibilities hardcoded into them it does not make sense to show any controller that is not able to be spawned.
This would also mean less performance overhead for the inspector and less clutter.
Additionally, Controllers should be allowed so specify their representation images data paths outside of the "MixedRealityToolkit" subfolders

## Describe alternatives you've considered

This would mean a "breaking change". To avoid this, an additional profile could be added that's used in parallel to the existing one to be used for new controllers.
One could also go up one level and create the profiles on the manager level, because the manager knows which controllers he can spawn, which might make more sense

![image](https://user-images.githubusercontent.com/32508825/59547710-85177a80-8f43-11e9-9df0-6c0941336096.png)
![image](https://user-images.githubusercontent.com/32508825/59547731-d4f64180-8f43-11e9-9108-3551226e2dca.png)

**Comment by davidkline-ms** [comment]
MRTK3 now builds upon Unity's input system, this type of profile is no longer applicable.
