### ISSUE TITLE
Directory Junction breaks hardcoded paths

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#4904]
## Describe the bug

@StephenHodgson has written a [documentation on how to add the MRTK to an existing repo via directory junction](https://www.rageagainstthepixel.com/expert-import-mrtk/). This involves creating the junction as a subfolder of the assets data path. This breaks all appearances of hardcoded data paths:

(Paths I found)
- ControllerPopupWindow: 19: EditorWindowOptionsPath
- ThemeInspector: 1347: Shader.Find("MixedRealityToolkit/Standard")

## To reproduce (first issue)

1. Add the MRKT via directory junction
2. Open a scene with MRTK and drill into the configuration Input -> Controllers -> Controller Definitions
3. Click one of the controller image buttons

## Expected behavior

No error no matter where the toolkit is placed in the project

## Screenshots

![image](https://user-images.githubusercontent.com/32508825/59547867-02dc8580-8f46-11e9-82a5-03841a1b4f6c.png)

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1
- MRTK Version 2 development_branch

**Comment by gilbdev** [comment]
using directory symlinks instead of junction should solve your errors. this will require some admin rights though.

`mklink /D Assets\MixedRealityToolkit ..\..\Subrepos\mrtk\Assets\MixedRealityToolkit`

**Comment by Alexees** [comment]
Since I prefer to work with the development branch, I don't think this trick won't go away any time soon for me ;)

**Comment by Alexees** [comment]
@gilbdev is it possible that the solution is less switching from junction to symlink than linking each folder from the Toolkit separately rather? Because from what I found is that the difference between the two only concerns local or remote linkage.
To me it looks as if I had to do the linking with each subfolder of the toolkit to avoid breaking the path.

**Comment by gilbdev** [comment]
i do 4 symlinks for each of those subfolders:
```
MixedRealityToolkit
MixedRealityToolkit.Providers
MixedRealityToolkit.SDK
MixedRealityToolkit.Services
```
you don't need Tests, and Examples is up to you, if oyu want them accessible in your project or not.
so yeah, 4 commands, and 4 symlink folders.

you jsut can't link to the upfolder named "Assets", as it won't merge correctly with your existing Assets folder (maybe it does in junction ?)

**Comment by Alexees** [comment]
Ok, that's what I thought.
Anyways, this means you can't cleanup your Unity project by moving ALL the external assets to a subfolder, cause this one here needs at least 4 folders at the root structure.
Is that improvable? I mean reading the path backwards, relative to the calling script or something?

**Comment by K780420** [comment]
![image](https://user-images.githubusercontent.com/97131332/190008639-ffc8c618-e685-4169-91e3-ef8ba64def9b.png)

**Comment by K780420** [comment]
![image](https://user-images.githubusercontent.com/97131332/190009252-1dd27a9c-8d37-4c13-a35b-f7bb2036ed28.png)

**Comment by K780420** [comment]
![image](https://user-images.githubusercontent.com/97131332/190009475-706adaef-5dc1-4e79-88f1-6bddaf05b193.png)

**Comment by K780420** [comment]
![image](https://user-images.githubusercontent.com/97131332/190009587-eb954b47-3e30-4dd0-9d86-16851c3e9f8d.png)

**Comment by K780420** [comment]
![image](https://user-images.githubusercontent.com/97131332/190009948-d6e9023f-c1fd-4f8c-918e-0e3121f0d4b9.png)

**Comment by K780420** [comment]
![image](https://user-images.githubusercontent.com/97131332/190012597-26cc6796-a3da-4efc-96fc-a41c19de304d.png)
