### ISSUE TITLE
"PressableButtonHoloLens2" suggests incompatibility with HoloLens 1

### ISSUE THREAD

**Issue by camnewnham** [microsoft/MixedRealityToolkit-Unity#4912]
## Describe the Issue
When upgrading to MRTK v2.0.0 RC2 the name change from PressableButton to PressableButtonHoloLens2 suggests that it is no longer compatible with HoloLens 1, whereas far functionality should still function even if near does not.

## Feature Area
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/PressableButtonHoloLens2.prefab

**Comment by cre8ivepark** [comment]
@camnewnham Thanks for the feedback! The naming updates were to indicate it is 'HoloLens 2 shell style' button vs other custom buttons. We also have ButtonHoloLens1.prefab for those apps maintaining HoloLens 1 style buttons. I'll include more detailed info for upcoming documentation updates.
