### ISSUE TITLE
Link to "MRTK Standard Shader" page is missing from MRTK Guides

### ISSUE THREAD

**Issue by SarahSexton** [microsoft/MixedRealityToolkit-Unity#4916]
## Describe the Issue
Link to "MRTK Standard Shader" page is missing from MRTK Guides.

## Feature Area
Link to "MRTK Standard Shader" page is missing from "MRTK" Guides README. None of the side bar navigation links point to "MRTK Standard Shader" or any information about shaders. 

## Existing Doc Link
Link to existing document: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_MRTKStandardShader.html?q=standard%20shader

Should be linked in https://microsoft.github.io/MixedRealityToolkit-Unity

**Comment by cre8ivepark** [comment]
Thanks Sarah! #4923 update includes the left nave menu for the MRTK Standard Shader.
