### ISSUE TITLE
change UI raycast to allow customization similar to IMixedRealityRaycastProvider for physics

### ISSUE THREAD

**Issue by naostranMS** [microsoft/MixedRealityToolkit-Unity#4917]
## Describe the problem
Originally in HTK, the UI raycast used distance to pick which UI element to focus on, but that was changed to work better with coplanar UI in this change:
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/1101

In our case the UI is not coplanar, and it's awkward to have to reorder the UI to make raycasts work as expected, so prioritizing distance over depth makes more sense.

## Describe the solution you'd like

Reorder the UI raycast prioritization to put distance before depth, and change the distance check to bypass (and move on to depth test) if the delta is less than some epsilon. With the epsilon check, I think it would still work the same way for coplanar UI, while also allowing it to use the distance check first for non-coplanar UI. (I'm also open to suggestions for better ways to do the coplanar test, but the epsilon seems like it should work and is simple enough)

## Describe alternatives you've considered

Another solution would be to make the UI raycast prioritization overridable, and then we could just override the prioritization locally to do distance before depth.

**Comment by Railboy** [comment]
Unless I've misunderstood the problem, this sounds like something a [custom raycast provider class](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4678) could fix.

**Comment by naostranMS** [comment]
@Railboy The custom raycaster is really tailored toward physics raycast and not the UI raycast. I could theoretically make it work that way but there are a couple of things that would make it pretty awkward:
- the custom raycaster returns a MixedRealityRaycastHit which is based on the physics RaycastHit
- it still does RaycastGraphics after the configurable raycast, which might just end up overriding the result anyway

Admittedly, I had meant to add this feedback to that PR but took too long:
1. I wish the default physics raycaster allowed for overriding prioritization without having to override all of the raycast behavior (and that would apply to using the configurable raycaster here as well - I really just want to override prioritization).
2. I think it could be beneficial to have a more generalized version of the customized raycasters and raycast prioritization/comparators that would encompass UI raycasts as well.

**Comment by naostranMS** [comment]
Another part of it is just that I think the default behavior would be more intuitive if it more closely mimicked draw behavior. That is, it seems like the expected behavior would be that the focus provider will pick whatever is drawn on top, but it doesn't work that way if the UI isn't coplanar.

**Comment by Railboy** [comment]
>raycast prioritization/comparators that would encompass UI raycasts as well.

@naostranMS My thoughts exactly. I'd forgotten that UI raycasts were not covered by the custom provider class. They really should be.

>Another part of it is just that I think the default behavior would be more intuitive if it more closely mimicked draw behavior. That is, it seems like the expected behavior would be that the focus provider will pick whatever is drawn on top, but it doesn't work that way if the UI isn't coplanar.

You may be right. Either way there's no downside to giving you the option to override the default behavior.

**Comment by naostranMS** [comment]
After some investigation I discovered that I have misunderstood how Unity UI draw order works, and now I can't really think of any universal solution for this. Basically, Unity's default UI shader doesn't do a normal ZTest, so distance doesn't really have any effect. The reason it matters in our app is because we're using a custom shader that does a normal ZTest. Taking into account different shader settings when prioritizing the raycast results seems rather problematic, and I am not aware of a way to tell what bit of UI will draw on top (short of doing a rendering pass and seeing what happens).

That said, I think this issue can just be changed to: we need to be able to customize the UI raycast in the same way as the physics raycast. I do still think it would be cool if I could just override the prioritization (for both physics and UI), but it's not absolutely necessary.
