### ISSUE TITLE
Missing .Unitypackage?

### ISSUE THREAD

**Issue by lepidecko** [microsoft/MixedRealityToolkit-Unity#4918]
## Describe the bug

GettingStartedWithTheMRTK: describes importing "Microsoft.MixedRealityToolkit.Unity.Examples.unitypackage" and
"Microsoft.MixedRealityToolkit.Unity.Foundation.unitypackage"

but these seem to be missing from the download. In fact, the zipfile does not contain any .unitypackage files.

## To reproduce

Download: MixedRealityToolkit-Unity-2.0.0-RC2.1
Try to install, no .unitypackage files found inside.
What am I missing here?

## Expected behavior

Expected the zip to contain the Microsoft.MixedRealityToolkit.Unity.Foundation.unitypackage that the docs refer to.

## Your Setup (please complete the following information)

- Unity Version 2019.1.7
- MRTK Version 2.0.0-RC2.1

## Target Platform (please complete the following information)

- WMR immersive

**Comment by keveleigh** [comment]
Under each release's assets, we've uploaded the unitypackages for download: 
![image](https://user-images.githubusercontent.com/3580640/59624475-afa43780-90eb-11e9-9285-a14638cc2745.png)

The most recent release can be found at https://github.com/microsoft/MixedRealityToolkit-Unity/releases/tag/v2.0.0-RC2.1
