### ISSUE TITLE
SolverHandler does not force a view

### ISSUE THREAD

**Issue by romsahel** [microsoft/MixedRealityToolkit-Unity#4932]
## Describe the Issue
We use SolverHandler to attach UI elements to the hands. However, adding SOlverHandler to an object does not warn you that at least one View is required. Without it, nothing seems to happen.

## Feature Area
Solvers

## Existing Doc Link
N/A

**Comment by romsahel** [comment]
@jbienzms From Paris Hack

**Comment by Troy-Ferrell** [comment]
SolverHandler is in charge of managing solvers. A solver component needs to be added to get hte desired behavior of how it should move/orient etc. There has been multiple bugs fixed though around this feature in case you hit something else. #5514 , #5416 

There also is much better updated documentation:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_Solver.html
