### ISSUE TITLE
Need Inspectors Working with Scene System Service

### ISSUE THREAD

**Issue by romsahel** [microsoft/MixedRealityToolkit-Unity#4935]
## Describe the problem
We want to use Unity additive scene loading. We have MRTK in one scene and then load child scenes additively. However, this results in the MRTK object missing from the child scenes which causes many of the MRTK inspectors to break.

![InspectorSceneInstance](https://user-images.githubusercontent.com/3393362/59677683-be155080-91ca-11e9-8618-7892e7a895ef.png)

We were told to check out the [Scene System Service](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SceneSystem/SceneSystemGettingStarted.html) but that won’t be working until [PR4455](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4455) is complete. Also, even with those in place, it seems the inspector issue in the screenshot above still won’t be fixed. Possibly due to issue #4083?

**Comment by romsahel** [comment]
@jbienzms From Paris Hack

**Comment by wiwei** [comment]
I think this is probably going to be an ongoing issue with input actions unless we can fix it as described by @luis-valverde-ms in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4083

**Comment by Zee2** [comment]
Stale, this is no longer an issue with the Unity Input System/XRI/etc.
