### ISSUE TITLE
More configurable AppBar

### ISSUE THREAD

**Issue by romsahel** [microsoft/MixedRealityToolkit-Unity#4936]
## Describe the problem
1. We need to dynamically add buttons to an AppBar and ideally, to configure if it should be visible during "edit" mode, or "normal" or during both.
2. We like the positioning behaviour of the AppBar but we'd like to use it without having to use the AppBar. 

## Describe the solution you'd like
1. Expose a method to add buttons to the AppBar and expose a parameter in the AppBarButton to configure in what mode it should be visible.
2. Split the AppBar button into two class to isolate the positioning behaviour and make it reusable.

## Describe alternatives you've considered
We currently rewrote from scratch a system that has a similar behaviour but that fits our needs better. However, we'd like to leverage the power of MRTKv2 and if it had some more configurability we could just use it.
For 2., we can make an empty AppBar and use it as-is. It feels a bit workaround-ish though.

**Comment by Alexees** [comment]
It would have been awesome if you did those changes you're mentioned to the AppBar and created a PullRequest for it.
It would love to see a configurable AppBar and it doesn't look like it being too far from it, except for the extra work of keeping it updated in edit mode to preview your configuration

**Comment by wiwei** [comment]
@julenka who on the UX side would have the most background around appbar stuff?

**Comment by julenka** [comment]
> We currently rewrote from scratch a system that has a similar behaviour but that fits our needs better. However, we'd like to leverage the power of MRTKv2 and if it had some more configurability we could just use it.

To clarify, did you mean to say "we wrote our own input system + set of UX controls, buttons, manipulation handler, etc.  but would use MRTK if MRTK was more configurable", or "we wrote our own system for the app bar but would use MRTK if the app bar in MRTK was more configurable"?

**Comment by Zee2** [comment]
ObjectBar/Canvas/etc supports dynamic layout in MRTK3.
