### ISSUE TITLE
Broken links in MRTK GitHub.IO, as well as docs.microsoft.com

### ISSUE THREAD

**Issue by SarahSexton** [microsoft/MixedRealityToolkit-Unity#4939]
## Describe the Issue
Broken links in MRTK GitHub.IO, as well as docs.microsoft.com, with regard to Text in Unity.

## Existing Doc Links
**Existing document: "Text Prefab" MRTK GitHub.IO** 
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_TextPrefab.html?q=text 
Broken: "3DTextPrefab.prefab" 
https://microsoft.github.io/Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text/
"UITextPrefab.prefab"
https://microsoft.github.io/Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text/

**Existing document: "Text in Unity" docs.microsoft.com**
https://docs.microsoft.com/en-us/windows/mixed-reality/text-in-unity
Broken: 
https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/mrtk_release/Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text 

## Additional context
Perhaps this is a problem with link validation, or use of absolute paths?

**Comment by Troy-Ferrell** [comment]
Also link to other documentation PR: https://github.com/MicrosoftDocs/mixed-reality/pull/1310

**Comment by cre8ivepark** [comment]
@SarahSexton Added TextPrefab to MRTK development branch 
#4682
