### ISSUE TITLE
Popup for enabling XR setting in new unity project doesn't check platform

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4941]
## Describe the bug

Whenever someone creates a new project with MRTK we're displaying a popup telling the user to enable the XR settings, however we're not checking which platform is currently selected. So if the user is eg. on windows platform and switches over to UWP after that popup was confirmed, the setting won't be enabled in the UWP build.

## To reproduce

- create new unity project (make sure your platform is not set to UWP)
- import mrtk packages
- observe popup
- switch platform to UWP
- observe missing XR setting

# Platform
- Unity Version 2018.4
- MRTK Version v2 RC2.1

![image](https://user-images.githubusercontent.com/36998103/59691575-82d34b80-91e3-11e9-8482-55e68fae3ce0.png)

**Comment by Troy-Ferrell** [comment]
My PR doesn't enable XR support for every build platform. But at least users will be notified if they do switch build target and the optimize window tool also notifies as well

**Comment by thalbern** [comment]
I don't get a notification if I switch platform. Have been running into this several times now (ending up with a flat app on HL2)

**Comment by Troy-Ferrell** [comment]
It's showing up for me. Can you check again latest?

![image](https://user-images.githubusercontent.com/25975362/63188680-d82aae00-c016-11e9-9d11-19957e3862ec.png)

**Comment by thalbern** [comment]
Ah! I was waiting for a popup like the first time you import mrtk. I'll check if that console output is there.

**Comment by thalbern** [comment]
checked with stabilization branch from friday and can confirm I have that popup now - did the original test with one of our prebuilt packages, so checking latest release package later today as well.

**Comment by Troy-Ferrell** [comment]
Yea we switched to that to be a bit less intrusive to the developer.
