### ISSUE TITLE
Difficult to change button colors or icons.

### ISSUE THREAD

**Issue by SarahSexton** [microsoft/MixedRealityToolkit-Unity#4943]
## Describe the Issue
There is no discoverable documentation on how to do something very simple and commonplace like change button colors or icons.  

## Feature Area
We are missing information on how to change it in both the code and in the Unity Editor. 

## Existing Doc Link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_Button.html 

## Additional context
Maybe add a Best Practices or Design page for sliders, slates, and button customization, etc.

**Comment by Troy-Ferrell** [comment]
@SarahSexton the information is in that document you mentioned but maybe slightly hidden. It is under "How to Make a button from scratch"  and the subsection "Adding visual states and handle far interaction events". The color is modified in the Interactable component profiles. 

There is also more detailed information for the Interactable class for both editor & coding changes under:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_Interactable.html

The icon is not mentioned at all under the "Prefab Layout" section unfortunately but the layout in Unity for the PressableButtonHololens2 is also different.

**Comment by Alexees** [comment]
Same here.
The old buttons provided button icon profiles. The current implementation looks as if you basically have to duplicate the material for each button. And what about batching?

**Comment by Troy-Ferrell** [comment]
@Alexees that is very true. I believe though issue #4660 is tracking what you are saying about icon setting via profiles instead of a million materials and better performance.
