### ISSUE TITLE
UnityUI sample needs touch down, touch up sounds

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4950]
## Overview
The UnityUI canvas in HandInteractionExampleScene does not contain sounds for touch down and touch up. To ensure customers implement UnityUI interactions using appropriate feedback, we should add this to the UnityUI example.

**Comment by julenka** [comment]
@cre8ivepark please let me know if you have questions.

**Comment by cre8ivepark** [comment]
@julenka Unity UI only provides OnClick() event in the inspector. Not sure if we can add audio clips for the touch down & up? In the PR #5341 I just added audio feedback to OnClick event.

![2019-07-17 22_02_57-Unity 2018 4 2f1 Personal - HandInteractionExamples unity - MRTK-GitHub - Univer](https://user-images.githubusercontent.com/13754172/61377985-475d9700-a8df-11e9-9e50-f508873df898.png)

**Comment by julenka** [comment]
Could we instead add a separate component that listens to touch events and fires the sounds? Not part of unity ui but on the whole canvas.

**Comment by Troy-Ferrell** [comment]
@julenka is sound onclick not sufficient?

**Comment by julenka** [comment]
No, you need audio feedback to k ow when you engine a touch as well.

Sent from phone, please excuse typos.
________________________________

**Comment by cre8ivepark** [comment]
Figured out. We can use Unity's Event Trigger. I'll open PR with updates.

![2019-07-24 18_36_30-Sourcetree](https://user-images.githubusercontent.com/13754172/61839349-154db700-ae42-11e9-97e2-eacd0639cdb2.png)

**Comment by cre8ivepark** [comment]
Completed with #5422
