### ISSUE TITLE
Need docs for how to configure pointer profiles

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#4953]
## Overview
Provide documentation on [profiles README](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Profiles/Profiles.html) for how to configure pointer profiles for the following common use cases:

1. Use GGV on HoloLens 2.
2. Use only the poke pointer, no hand rays (turn hand rays off)

**Comment by Troy-Ferrell** [comment]
For issue 2 of this bug, that should be tracked by #4954
