### ISSUE TITLE
Pressable buttons press begins at back of the button, not the front.

### ISSUE THREAD

**Issue by JonathanPalmerGD** [microsoft/MixedRealityToolkit-Unity#4955]
## Describe the bug

When you press an MRTK button, the button begins to press and move when you reach through and touch the back of the button.
This undermines the idea of responsive interaction intended for the first moments.

## To reproduce

Attempt to push a PressableButton and notice when the movement/compression of the button actually begins.

## Expected behavior

The button should press from the front face (not the back face)

## Screenshots

![image](https://user-images.githubusercontent.com/2644214/59721938-47cb1b00-91d7-11e9-93c7-589abaaa34d8.png)

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

## Additional context

We want the glow on first contact to also be when interaction begins and the button starts to push.

**Comment by wiwei** [comment]
@thalbern FYI
