### ISSUE TITLE
Unity LWRP TerrainLit material problem with WMR Headset

### ISSUE THREAD

**Issue by genereddick** [microsoft/MixedRealityToolkit-Unity#4956]
## Describe the bug
Maybe not an MRTK bug, and I know 2019 is not officially supported yet, but thought I report it here in case:

While testing the updates to the MRTK Standard shader to support the LWRP (which seems to work correctly), and creating shaders using Shader Graph (which also seem to work), I had a weird effect with the Unity TerrainLit material (described here: https://github.com/Unity-Technologies/ScriptableRenderPipeline/wiki/Terrain-Lit-Shader).

Specifically, the terrain appears in the left eye only in duplicate and drifts as you move your head -- as if the right eye version of the terrain is also appearing in the left eye (see screenshots). This effect occurs on Run both in the Editor Game window and on a WMR headset.

It effect does not occur in the Hololens (simulated) experience, but I'll test on the device in a bit to make sure.

## To reproduce

Create a LWRP Unity project, add a terrain, test in WMR headset. Close an eye, move your head.

## Expected behavior
Appears in both eyes, no drift.

## Screenshots
Screenshots are from the editor but reflects what appears in the headset. Second screenshot is a minimal install:

![terrain-separation](https://user-images.githubusercontent.com/1033793/59733793-f422f680-9203-11e9-870f-08a7c8ae44bf.png)
![terrain-separation-2](https://user-images.githubusercontent.com/1033793/59733794-f422f680-9203-11e9-9608-d2ae7603605c.png)

## Your Setup (please complete the following information)

- Unity Version: 2019.1.5f1
- MRTK Version: latest dev as of 6/18/19

## Target Platform (please complete the following information)
Testing on WMR immersive

**Comment by genereddick** [comment]
This seems to be a problem with Single Pass Instanced mode. For the HDRP, and so I assume for the LWRP as well, Single Pass is required but apparently Single Pass Instanced is not. When I changed this the problem went away.

**Comment by Merichbier** [comment]
Hi,
I have the same problem as you have, can you detail what you did to fix it ? I don't understand what/where you changed the settings ("When I changed this the problem went away")

Thanks
Cheers

**Comment by genereddick** [comment]
Not sure what the state of this issue is currently, but the setting can be found in:
File | Build Settings | Player Settings | XR Settings | Stereo Rendering Mode

Try changing the setting to each option (Multi Pass, Single Pass or Single Pass Instanced) to see which (if any works):

![image](https://user-images.githubusercontent.com/1033793/64463404-c50c7a80-d0b8-11e9-8f0b-ea98543f29ff.png)

**Comment by TheLLspectre** [comment]
Hi !

I've the same issue on my project and it's a little bit more complicated than changing the Stereo rendering Mode.

So there is this first issue with the terrain which is in double in the left eye with the single pass instanced. So I switch to the "Single Pass" and with this setting I have a weird "filter" in front of everything what I looking. It's like a big shadow and like it tried to duplicate some part of my models. And we clearly see a separation like the separation between the right and left eye.

And I suppose this comming from the custom shaders I used. To use it I need the LWRP.

I'm working on the Unity 2019.2.16 with the MRTK 2.2.0

I tried to find solutions like exporting terrain to export it with blender as a model but it's another problem ^^

What do you thinking about this ? How we can fix this issue ??

Thanks ;)
