### ISSUE TITLE
Add HoverLight script settings in MRTK profile for each cursor

### ISSUE THREAD

**Issue by benjamincoven** [microsoft/MixedRealityToolkit-Unity#4957]
## Describe the problem

Hello everyone, maybe I missed it (if yes documentation is not clear), but I would like to change the settings of the hoverlight scripts of the cursors.

## Describe the solution you'd like

Would it be possible to have the possibility to change these settings in the input profiles?

## Additional context

Specifically I want to disable it for eye tracking and set radius for hand ray. The only I found to change that is to create a script that will find the script at run time, it's quite dirty.

Thank you

**Comment by wiwei** [comment]
@cre8ivepark @Cameron-Micka is this something you guys could help answer?

**Comment by Cameron-Micka** [comment]
Hi @benjamincoven, the HoverLight (and ProximityLight) settings are driven from a HoverLight (or ProximityLight) component that lives in the cursor prefab that each pointer instantiates. I would recommend making a prefab variant of the cursor you wish to modify, and a prefab variant of the pointer you wish to modify, then connect the new cursor variant to the new pointer variant and specify that new pointer variant in your input profile.

Typing also those steps out it sounds laborious, but should be auto-update safe if you take future MRTK updates. We could push overrides to HoverLight/ProximityLight settings somewhere in a profile, but that could cause extra settings clutter. But, I could be convinced either way. 

Note, you can also specify HoverLight and Proximity light setting overrides on a per material basis in the material inspector.

**Comment by benjamincoven** [comment]
If I change the HoverLight and Proximity Light, it would whange it for all pointers isn't it (hands and eye)?

The first solution is what I was looking for. Thank you.

**Comment by Cameron-Micka** [comment]
Yes, it should! I haven’t taken a look at how many cursors are used among all the HoloLens pointers recently (last I checked it was 2 or 3), but changing the HoverLight & ProximityLight settings in those cursor should apply the change globally.
