### ISSUE TITLE
MixedRealityRaycastHit Throws Exceptions on Every Frame

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#4966]
## Describe the bug
[MixedRealityRaycastHit](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit/Definitions/InputSystem/MixedRealityRaycastHit.cs) throws exceptions on every frame.

A [commit](https://github.com/microsoft/MixedRealityToolkit-Unity/commit/f896a975d23edeec8eb5e71afd8a27c01d7fb83e) was made 7 days ago to wrap access to `hitInfo.lightmapCoord` in a Try / Catch block. Unfortunately this does not correct the actual condition that's causing the exception to be thrown in the first place. Even though the exception is being handled, it's still causing an exception on _every frame_. This introduces a significant performance hit. Exceptions are very expensive and should be avoided at all costs in the render thread.

There is a comment in the recent comment:

> Accessing lightmap coord appears to throw a NullReferenceException in some cases, probably when lightmaps are not used.

Rather than catching the exception, effort should be made to determine if this is in fact the root cause and determine a way to avoid accessing the property under this condition. If we determine the condition is unavoidable, we should open a bug with Unity.

## To reproduce

1. Create a new Unity project
2. Import MRTK
3. Configure MRTK for HoloLens 2
4. Press play in Unity
5. Under Exception Settings in Visual Studio, set it to stop on all exceptions (even handled ones).
6. Attach Visual Studio to Unity

You will see the Visual Studio Debugger break on every frame.

## Expected behavior

An exception should not be thrown on every frame.

## Your Setup (please complete the following information)

- Unity Version: 2018.4.2
- MRTK Version: mrtk_develop as of 2019-06-19

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
This is bad, I'm fixing this now
