### ISSUE TITLE
Pressable Button in Incorrect State after getting enabled [mrtk rc2.1]

### ISSUE THREAD

**Issue by Shubham7694** [microsoft/MixedRealityToolkit-Unity#4967]
## Describe the bug
MRTK Pressable Button State is incorrect after getting enabled post disabling it.
## To reproduce

1. Keep a PressableRound Button in scene.
2. Add a script to disable this button when clicked on it. 
3. Enable the button using script after few seconds.
4. Button is enabled in Focused state.
5. Button goes in Pressed State or stays in focused state based on whether it's near or far interaction.
Note: Change the color in button profile to contrasting color as there is chance of mistaking state as i did.

## Expected behavior
Button should start in default/normal state when enabled.

## Your Setup (please complete the following information)

- Unity Version [2018.42f1
- MRTK Version [v2.1] aka RC2 

## Target Platform (please complete the following information)
- HoloLens 2

**Comment by gilbdev** [comment]
Same Problem here.

suggestion : 
reset States to default value in Interactable.OnEnable

current workaround:
adding another component with:
```
void OnEnable()
{
  GetComponent<Interactable>().SetFocus(false);
 // or more globally : parse all states and call SetState(state, false)
}
```

**Comment by gilbdev** [comment]
i tried in 2.0.0 : bug still reproductible.

i tried with `Interactable.Enabled` and `Interactable.SetDisabled()`
have to call `Interactable.ResetAllStates()` or `SetFocus(false)` when enabling button to workaround the issue.

main problem is (without the resetallstates call) that when focusing in and out after a disable/enable, the interactable still keeps the focus state.
so this is more like a OnFocusExit that should be triggered (and decrement the focus count) when disabling the interactable.

**Comment by gilbdev** [comment]
linked to/duplicate #4481

**Comment by Troy-Ferrell** [comment]
@julenka FYI, sounds like issue with input on Interactable

**Comment by pampas93** [comment]
This was because the `lastState` within InteractableThemeBase.cs was not defaulted to null after disabling the button. I just worked around it by adding this in the onDisable of interactable.cs
``` 
for (int i = 0; i < runningThemesList.Count; i++)
    if (runningThemesList[i].Loaded)
        runningThemesList[i].LastState = -1;
```
where `LastState` is public setter for `lastState` in the InteractableThemeBase.cs

**Comment by pampas93** [comment]
> Same Problem here.
> 
> suggestion :
> reset States to default value in Interactable.OnEnable
> 
> current workaround:
> adding another component with:
> 
> ```
> void OnEnable()
> {
>   GetComponent<Interactable>().SetFocus(false);
>  // or more globally : parse all states and call SetState(state, false)
> }
> ```

But having `GetComponent<Interactable>().SetFocus(false);` being called from another script within the gameObject doesn't work.

**Comment by julenka** [comment]
@Troy-Ferrell I wonder if your interactable refactor will fix this, just because you are fixing some of the code in Interactable states

**Comment by julenka** [comment]
@cdiaz-ms has this been fixed?

**Comment by CDiaz-MS** [comment]
@julenka yes it has, but a new test PR for this issue is coming today and then it can be closed.
