### ISSUE TITLE
[MRTK Shell Parity] [Bounding Box] In Flattened mode, the border visualization is too thin and almost invisible

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#4976]
## Describe the bug
In Flattened mode, the border visualization is too thin and almost invisible
Part of #4200 UX Controls Parity with HoloLens 2 Shell

## To reproduce
In HandInteractionExamples scene, hover flattened examples (slate, MRTK plane) with hand ray or finger to make the border visible.

## Expected behavior
Shows solid border similar to the Bounding Box in the 3D objects

## Screenshots
![2019-06-19 14_40_52-Unity 2018 4 0f1 Personal - HandInteractionExamples unity - MRTK-Public-Microsof](https://user-images.githubusercontent.com/13754172/59803527-9395c700-92a0-11e9-8233-601169f6b8d5.png)
![2019-06-19 14_41_19-Unity 2018 4 0f1 Personal - HandInteractionExamples unity - MRTK-Public-Microsof](https://user-images.githubusercontent.com/13754172/59803528-9395c700-92a0-11e9-9a37-8dd795509d16.png)
![2019-06-19 09_34_42-Unity 2018 4 0f1 Personal - HandInteractionExamples unity - MRTK-Public-Microsof](https://user-images.githubusercontent.com/13754172/59803529-9395c700-92a0-11e9-8fa3-bed78bd23597.png)

## Branch
mrtk_development

**Comment by julenka** [comment]
Fixed
