### ISSUE TITLE
[MRTK Shell Parity] [Button] Front cage should be compressed

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#4978]
## Describe the bug
Button's front cage should be compressed. Currently, it moves back and penetrates through the backplate.
Part of #4200 UX Controls Parity with HoloLens 2 Shell

## To reproduce
In the HandInteractionExamples scene, press button with a finger.

## Expected behavior
Front cage is compressed on the press interaction.

![2019-06-19 14_51_53-Unity 2018 4 0f1 Personal - HandInteractionExamples unity - MRTK-Public-Microsof](https://user-images.githubusercontent.com/13754172/59803921-cf7d5c00-92a1-11e9-89fd-86f7aa3b666c.png)

## Current behavior
![2019-06-19 14_49_50-Unity 2018 4 0f1 Personal - HandInteractionExamples unity - MRTK-Public-Microsof](https://user-images.githubusercontent.com/13754172/59803827-86c5a300-92a1-11e9-98ca-e70daa7d5ecf.png)

## Branch
mrtk_development

**Comment by ADP-JoNeff** [comment]
#Close
Dupe of #4562

**Comment by cre8ivepark** [comment]
Completed with #5168
