### ISSUE TITLE
MixedRealityLineRenderer is showing an error when used with default configuration

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4986]
## Describe the bug

Using the MixedRealityLineRenderer in it's default configuration will cause an error during runtime because there's no material assigned to it. 

## To reproduce

Add a MixedRealityLineRenderer component to any gameobject and hit play

## Expected behavior

There shouldn't be an error when using a component in default configuration.

## Your Setup (please complete the following information)

- Unity Version 2018.4
- MRTK Version V2 RC2.1

## Target Platform (please complete the following information)

- Unity

**Comment by Railboy** [comment]
How would we feel about this:
- If no material is assigned in edit mode the inspector displays a helpbox warning.
- If no material is assigned in play mode a default material is generated and a warning is logged.

**Comment by thalbern** [comment]
do we have some default material we could assign so it's the same behavior in editor / simulation mode? i'm not very happy having a different behavior in editor / simulation mode.

**Comment by Railboy** [comment]
@thalbern We have a default material, but outside of the editor there's no simple way to retrieve it at runtime except via Resources, and that's not a pattern we want to use.
