### ISSUE TITLE
UDP client not working on Hololens

### ISSUE THREAD

**Issue by mattandria** [microsoft/MixedRealityToolkit-Unity#4987]
## Describe the bug

I'm trying to communicate with the Hololens through UDP to send and receive data: I made a C++ socket (Winsock) which is the Udp server and a C# script (the Udp client) on Unity. 
When I run the Unity scene on my local machine (my PC), it works fine. But when I deploy it on the Hololens, it seems that the UdpClient cannot find the UdpServer on the PC. 
Both are on the same wifi connection though. I can't figure out why it still doesn't work.

## To reproduce

I give below the scripts I used.
1. Launch the server (server_win.cpp) first 
2. Create an empty scene on Unity
3. Attribute the UdpClient C# script (Client.cs) on a GameObject
4. Build the project
5. Deploy the scene on Hololens

olens via Visual Studio

## Expected behavior

The server prints the received and sent data if the connection 

## Your Setup (please complete the following information)

-Unity Version 2018.3.7f1
-MRTK Version v2.0.0 RC1
-Visual Studio Community 2019

## Target Platform (please complete the following information)

- HoloLens 1

## Source Code

> server_win.cpp

```
#include <iostream>
#include <stdlib.h>
#include <stdio.h>
#include <WinSock2.h>
#include <windows.h>

#pragma comment(lib,"ws2_32.lib") //Winsock Library

#define BUFLEN 512	//Max length of buffer
#define PORT 8888	//The port on which to listen for incoming data

int main()
{
	SOCKET s;
	struct sockaddr_in server, si_other;
	int slen, recv_len;	
	char buf[BUFLEN];
	WSADATA wsa;

	slen = sizeof(si_other);

	//Initialise winsock
	printf("\nInitialising Winsock...");
	if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0)
	{
		printf("Failed.Error Code : % d ", WSAGetLastError());
		exit(EXIT_FAILURE);
	}
	printf("Initialised.\n");

	//Create a socket
	if ((s = socket(AF_INET, SOCK_DGRAM, 0)) == INVALID_SOCKET)
	{
		printf("Could not create socket : % d", WSAGetLastError());
	}
	printf("Socket created.\n");

	//Prepare the sockaddr_in structure
	server.sin_family = AF_INET;
	server.sin_addr.s_addr = INADDR_ANY;
	server.sin_port = htons(PORT);

	//Bind
	if (bind(s, (struct sockaddr*) &server, sizeof(server)) == SOCKET_ERROR)
	{
		printf("Bind failed with error code : % d", WSAGetLastError());
		exit(EXIT_FAILURE);
	}
	puts("Bind done");


	printf("Waiting for data...\n");
	fflush(stdout);

	double tab_s[6] = { 0.0, 0.0, 0.0, 4.0, 5.0, 6.0 };
	double tab_r[3];


	//keep listening for data
	while (1)
	{

		//clear the buffer by filling null, it might have previously received data
		memset(buf, 0, BUFLEN);

		//try to receive some data, this is a blocking call
		if ((recv_len = recvfrom(s, (char*)& tab_r, sizeof(tab_r), 0, (struct sockaddr*) & si_other, &slen)) == SOCKET_ERROR)
		{
			printf("recvfrom() failed with error code : % d", WSAGetLastError());
			exit(EXIT_FAILURE);
		}

		printf("\nOn recoit:\n");
		std::cout << "fx: " << tab_r[0] << " fy: " << tab_r[1] << " fz: " << tab_r[2] << std::endl;

		tab_s[0] = tab_s[0] - 0.1;

		printf("\nOn envoie:\n x = %f, y = %f, z = %f\n", tab_s[0], tab_s[1], tab_s[2]);
		printf("vx = %f, vy = %f, vz = %f\n", tab_s[3], tab_s[4], tab_s[5]);

		//now reply the client with the same data
		if (sendto(s,(char*)&tab_s, sizeof(tab_s), 0, (struct sockaddr*) &si_other, slen) == SOCKET_ERROR)
		{
			printf("sendto() failed with error code : % d", WSAGetLastError());
			exit(EXIT_FAILURE);
		}
	}

	closesocket(s);
	WSACleanup();

	return 0;
} 

````

> Client.cs

````
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using System.Net;
using System.Net.Sockets;
using System.Text;

public class Client : MonoBehaviour
{
    UdpClient udpClient;

    private Vector3 read_buff1 = new Vector3(0f, 0f, 0f);
    private Vector3 read_buff2 = new Vector3(0f, 0f, 0f);
    private Vector3 send_buff = new Vector3(1f, 2f, 3f);

    // IP du serveur
    String Ip_wifi = "192.168.43.87"; // put the IP adress of you PC here when you deploy on Hololens
    String Ip_local = "127.0.0.1"; // localhost

    int port_rcv = 11000; // port where we receive data
    int port_send = 8888; // port where we send data

    // Start is called before the first frame update
    void Start()
    {
        Connection(Ip_local); // put Ip_local or Ip_wifi here
        SendData(); // first send, in order to get in touch with the server

    }

    void Update()
    {   
        ReadData();
        SendData();
    }

    public void Connection(String Ip)
    {
        // Initialisation of the UdP Connection
        try
        {
            udpClient = new UdpClient(port_rcv);
            udpClient.Connect(Ip, port_send);
            Debug.Log("Connection established");
        }
        catch (Exception exception)
        {
            Debug.Log("Exception caught: " + exception.Message);
        }
    }

    // Synchrone read function
    public void ReadData()
    {
        try
        {
            //IPEndPoint object will allow us to read datagrams sent from any source.
            IPEndPoint RemoteIpEndPoint = new IPEndPoint(IPAddress.Any, 0);

            Byte[] receiveBytes = udpClient.Receive(ref RemoteIpEndPoint);
            this.read_buff1 = new Vector3((float)BitConverter.ToDouble(receiveBytes, 8),
                                    (float)BitConverter.ToDouble(receiveBytes, 16),
                                    -1 * ((float)BitConverter.ToDouble(receiveBytes, 0)));

            this.read_buff2 = new Vector3((float)BitConverter.ToDouble(receiveBytes, 32),
                                       (float)BitConverter.ToDouble(receiveBytes, 40),
                                       -1 * (float)BitConverter.ToDouble(receiveBytes, 24));

            Debug.Log("Received: " + this.read_buff1);
        }
        catch (Exception e)
        {
            Debug.Log(e.ToString());
        }
    }

    public void SendData()
    {
        // Formatting data to send
        byte[] dataX = BitConverter.GetBytes((double)-1 * this.send_buff.z);
        byte[] dataY = BitConverter.GetBytes((double)this.send_buff.x);
        byte[] dataZ = BitConverter.GetBytes((double)this.send_buff.y);

        byte[] dataToSend = new byte[24];
        for (int i = 0; i < dataX.Length; i++)
        {
            dataToSend[i] = dataX[i];
            dataToSend[i + 8] = dataY[i];
            dataToSend[i + 16] = dataZ[i];
        }

        try
        {
            udpClient.Send(dataToSend, dataToSend.Length);
        }
        catch (Exception exception)
        {
            Debug.Log("Exception caught: " + exception.Message);
        }

        Debug.Log("Sent: " + this.send_buff);
    }
}

**Comment by gilbdev** [comment]
you are receiving data from 'any' ip :
check that you configured your wifi router to enable udp broadcast for wifi (disabled by default on most of them)

**Comment by mattandria** [comment]
Ok. But I tested the UDP connection between 2 computers on the same wifi and it works. So normaly, my wifi network is able to exchange data through UDP. Maybe there is a parameter to enable in order to permit udp broadcasting with the hololens?

**Comment by Jarodshow** [comment]
Did you enable the appropriate capabilities?

**Comment by mattandria** [comment]
Yes, I've enabled these capabilities:

![Capabilities](https://user-images.githubusercontent.com/38125978/59860197-87803700-937e-11e9-8e8c-9f8e32086936.PNG)

I don't know if I missed some.

**Comment by Jarodshow** [comment]
Your `IPEndPoint` points to port 0, it should point to the port you're listening to.

**Comment by mattandria** [comment]
@Jarodshow Effectively I forgot to put the port there, but on Unity Editor, it works even it's 0.

**Comment by mattandria** [comment]
I've done some researches and I found that `UdpClient` is not compatible with the Hololens. I have to use `DatagramSocket` instead.
I will test and I will tell you if it works

**Comment by chiarapalu** [comment]
Hi Mattandria, did you find out if using DatagramSocket the connection works fine?
Thanks!

**Comment by Samvid95** [comment]
Hey did you find the solution with the Datagram socket? @chiarapalu

**Comment by mattandria** [comment]
@chiarapalu sorry for the late answer
Eventually, it works fine with DatagramSocket ;)
UdpClient really doesn't work on the Hololens

**Comment by AakashM29** [comment]
Can you please share the code here again with the updated datagram.socket ?

**Comment by josodo** [comment]
Hi! I have tried it with DatagramSockets and it doesn't work. No errors, but not connection. On editor it works perfectly.
using System;
using System.Net;
using System.Net.Sockets;
using System.Text;
using UnityEngine;

public class ClientNoClientUDP : MonoBehaviour
{
    public string serverIP = "127.0.0.1"; // IP address of the server
    public int serverPort = 5500; // port of the server
    private Socket socket;

    private void Start()
    {
        // create a new socket
        socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);

        // connect to the server
        socket.Connect(new IPEndPoint(IPAddress.Parse(serverIP), serverPort));

        

        // prepare to receive data
        socket.BeginReceive(new byte[1024], 0, 1024, 0, new AsyncCallback(ReceiveCallback), socket);
    }

    private void SendData()
    {
        // send a message to the server
        byte[] message = Encoding.ASCII.GetBytes("Hello, server!");
        socket.Send(message);
    }

    private void ReceiveCallback(IAsyncResult ar)
    {
        try
        {
            // retrieve the socket from the async state
            Socket socket = (Socket)ar.AsyncState;

            // read the data from the server
            int bytesReceived = socket.EndReceive(ar);
            byte[] receivedData = new byte[bytesReceived];
            Array.Copy(new byte[1024], receivedData, bytesReceived);

            // process the received data
            string receivedMessage = Encoding.ASCII.GetString(receivedData);
            Debug.Log("Received message from server: " + receivedMessage);

            // prepare to receive more data
            socket.BeginReceive(new byte[1024], 0, 1024, 0, new AsyncCallback(ReceiveCallback), socket);
        }
        catch (Exception e)
        {
            Debug.Log("Error: " + e.ToString());
        }
    }

    private void OnDestroy()
    {
        // close the socket when the script is destroyed
        socket.Close();
    }
}

**Comment by dilkekurt** [comment]
@mattandria I know its been so long since you have closed this issue. But I am having a similar problem with sending data to Hololens right now. However, somehow my Datagramsocket code is not working also. Can you share your solution woth Datagramsocket?

**Comment by AakashMehtaPAG** [comment]
@dilkekurt Hi, I might be able to help you with it...will you be able to send the code?

**Comment by dilkekurt** [comment]
@AakashMehtaPAG thank you for replying :') It is the receiver code. It has both UDPClient and Datagramsocket so that I can try on both unity and hololens. The aim is to change the color of a cube object whenever a message is received. It doesnt matter what is the message itself. It work on unity with UWP settings but it doesnt work on hololens somehow.

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using System.Net;
using System.IO;
#if UNITY_EDITOR
using System.Net.Sockets;
using System.Threading;
using System.Text;
#else
using Windows.Networking.Sockets;
using Windows.Networking;
using Windows.Storage.Streams;
#endif
public class udpTest : MonoBehaviour
{
#if !UNITY_EDITOR && UNITY_WSA
        DatagramSocket socket; 
#endif
    static Material m1, m2, m3;
    private int ClientPortNumber2 = 11000;
    static string ClientPortNumber = "11000";
    static GameObject go;
    static bool received2 = false;

    // Start is called before the first frame update
    void Start()
    {
        m1 = new Material(this.gameObject.GetComponent<MeshRenderer>().material);
        m2 = new Material(this.gameObject.GetComponent<MeshRenderer>().material);
        m2.color = Color.red;
        m3 = new Material(this.gameObject.GetComponent<MeshRenderer>().material);
        m3.color = Color.blue;
        go = this.gameObject;

#if UNITY_EDITOR
        IPEndPoint IPep = new IPEndPoint(IPAddress.Any, ClientPortNumber2);
        UdpClient udpClient = new UdpClient(IPep);

        UdpState s = new UdpState();
        s.e = IPep;
        s.u = udpClient;

        udpClient.BeginReceive(new AsyncCallback(ReceiveCallback), s);
#else
        StartClient();
#endif
    }

    // Update is called once per frame
    void Update()
    {
        if (received2)
        {
            go.GetComponent<Renderer>().material = m2;
            //Debug.Log("mat changed");
            received2 = false;
        }


    }

#if UNITY_EDITOR
    public struct UdpState
    {
        public UdpClient u;
        public IPEndPoint e;
    }

    public static void ReceiveCallback(IAsyncResult ar)
    {
        UdpClient u = ((UdpState)(ar.AsyncState)).u;
        IPEndPoint e = ((UdpState)(ar.AsyncState)).e;

        byte[] receiveBytes = u.EndReceive(ar, ref e);
        string receiveString = Encoding.ASCII.GetString(receiveBytes);

        received2 = true;
        u.Close();
    }
#endif
#if !UNITY_EDITOR

    private async void StartClient()
    {
        try
        {
            // Create the DatagramSocket and establish a connection to the echo server.
            var clientDatagramSocket = new Windows.Networking.Sockets.DatagramSocket();

            clientDatagramSocket.MessageReceived += ClientDatagramSocket_MessageReceived;

            await clientDatagramSocket.BindServiceNameAsync(ClientPortNumber);
        }
        catch (Exception)
        {
            go.GetComponent<Renderer>().material = m3;
        }
    }

    private void ClientDatagramSocket_MessageReceived(Windows.Networking.Sockets.DatagramSocket sender, Windows.Networking.Sockets.DatagramSocketMessageReceivedEventArgs args)
    {
        string response;
        using (DataReader dataReader = args.GetDataReader())
        {
            response = dataReader.ReadString(dataReader.UnconsumedBufferLength).Trim();
        }

        received2 = true;
    }
#endif

}


`

**Comment by AakashMehtaPAG** [comment]
Perhaps this will work...I was not able to test it, but please let me know what happens.

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using System.Net;
using System.IO;
#if UNITY_EDITOR
using System.Net.Sockets;
using System.Text;
#else
using Windows.Networking.Sockets;
using Windows.Networking;
using Windows.Storage.Streams;
using System.Threading.Tasks;
#endif

public class udpTest : MonoBehaviour
{
#if !UNITY_EDITOR && UNITY_WSA
    DatagramSocket socket;
#endif

    static Material m1, m2, m3;
    private int ClientPortNumber2 = 11000;
    static string ClientPortNumber = "11000";
    static GameObject go;
    static bool received2 = false;

    // Start is called before the first frame update
    void Start()
    {
        m1 = new Material(this.gameObject.GetComponent<MeshRenderer>().material);
        m2 = new Material(this.gameObject.GetComponent<MeshRenderer>().material);
        m2.color = Color.red;
        m3 = new Material(this.gameObject.GetComponent<MeshRenderer>().material);
        m3.color = Color.blue;
        go = this.gameObject;

#if UNITY_EDITOR
        IPEndPoint IPep = new IPEndPoint(IPAddress.Any, ClientPortNumber2);
        UdpClient udpClient = new UdpClient(IPep);

        UdpState s = new UdpState();
        s.e = IPep;
        s.u = udpClient;

        udpClient.BeginReceive(new AsyncCallback(ReceiveCallback), s);
#else
        StartClient();
#endif
    }

    // Update is called once per frame
    void Update()
    {
        if (received2)
        {
            go.GetComponent<Renderer>().material = m2;
            received2 = false;
        }
    }

#if UNITY_EDITOR
    public struct UdpState
    {
        public UdpClient u;
        public IPEndPoint e;
    }

    public static void ReceiveCallback(IAsyncResult ar)
    {
        UdpClient u = ((UdpState)(ar.AsyncState)).u;
        IPEndPoint e = ((UdpState)(ar.AsyncState)).e;

        byte[] receiveBytes = u.EndReceive(ar, ref e);
        string receiveString = Encoding.ASCII.GetString(receiveBytes);

        received2 = true;
        u.Close();
    }
#else

    private async void StartClient()
    {
        try
        {
            socket = new DatagramSocket();
            socket.MessageReceived += ClientDatagramSocket_MessageReceived;

            await socket.BindEndpointAsync(null, ClientPortNumber);
        }
        catch (Exception)
        {
            go.GetComponent<Renderer>().material = m3;
        }
    }

    private async void ClientDatagramSocket_MessageReceived(DatagramSocket sender, DatagramSocketMessageReceivedEventArgs args)
    {
        try
        {
            uint stringLength = args.GetDataReader().UnconsumedBufferLength;
            string receivedString = args.GetDataReader().ReadString(stringLength);

            received2 = true;
        }
        catch (Exception ex)
        {
            // Handle the exception
            go.GetComponent<Renderer>().material = m3;
        }
    }
#endif
}
`
