### ISSUE TITLE
Appx build inside build window does not use correct build configuration

### ISSUE THREAD

**Issue by Jordu29** [microsoft/MixedRealityToolkit-Unity#4989]
## Describe the bug

When I'm about to build & deploy on Hololens, the first appx build I try after building Unity project seems to use Master configuration while I selected Release. It then throws an error because it seems it does not find such configuration. If I retry a build, it uses the configuration.

## To reproduce

1. Open a Unity project and then MixedRealityToolkit> Utilities > Build Window
2. Make sure in Appx Build Options tab that Build Configuration is set on "Release"
3. In Unity Build Option tab, select Build Unity Project
4. When it's done, either use Build appx from popup or go in Appx Build Options tab and use "Build APPX"
5. MSBuild indicates in Unity console that build failed

## Expected behavior

MSBuild should complete successfully

## Screenshots

![image](https://user-images.githubusercontent.com/10146031/59841534-c7cabf80-9354-11e9-993c-bcc820829eb0.png)

## Your Setup (please complete the following information)

- Unity Version 2018.3.0f2
- MRTK Version 2.0.0-RC2.1

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by gilbdev** [comment]
should have been fixed #4485

**Comment by wiwei** [comment]
Should have been fixed, though that looks like it should have included the fix. I'll take a peek.

**Comment by Troy-Ferrell** [comment]
Works in latest MRTK of this comment and Unity 2018 LTS
