### ISSUE TITLE
HoloLens 2 hand tracking mesh and pointer direction not working in HoloLens 2 and RC2.1

### ISSUE THREAD

**Issue by mr0ng** [microsoft/MixedRealityToolkit-Unity#4990]
## Describe the bug

Articulated hand mesh is very unstable. The joint cubes appear to always align well, but the hand mesh is either missing or at a fixed location in space (though fingers still move when the user moves their physical fingers.

The raycasts also point in the wrong direction.

Once in a while, the hand mesh will briefly superimpose perfectly on the hand. When that happens, the pointer points in the correct direction. But the hand mesh is easily lost again.

## To reproduce

Deploy any RC2.1 app with the default mixed reality toolkit profile to a HoloLens 2. W
We tried with two different apps.
We tried with a MRTK RC1 app, and the issue did not appear.

## Expected behavior

Hand mesh superimposed on hand.
Hand pointers pointing in the correct direction

## Screenshots

![image](https://user-images.githubusercontent.com/19508106/59845026-407d4c00-9354-11e9-8d9b-3499db5e031d.png)

## Your Setup (please complete the following information)

- Unity Version  2018.4.2f1
- MRTK Version RC2.1

## Target Platform (please complete the following information)

- HoloLens 2

## Additional context

Running the latest build of HoloLens 2 as of 6/20/2019 - tagging @jessemcculloch

**Comment by jessemcculloch** [comment]
HoloLens build 18362.1072.19h1_release_svc_sydney.190613-1404 (UUP-CTv2)

**Comment by mr0ng** [comment]
Latest HoloLens 2 Build has fixed the issue.
