### ISSUE TITLE
MRTK inspector tab selection is not preserved when entering playmode

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedRealityToolkit-Unity#4997]
## Describe the bug

When entering play mode with an MRTK instance selected, the inspector's tab selection resets.

## To reproduce

- Create a new scene
- Add an MRTK instance and select it
- Select 'Spatial Mapping' tab
- Enter play mode
- Observe tab selection default back to 'Camera'

## Expected behavior

Tab selection should be preserved when entering play mode.

**Comment by Railboy** [comment]
@Troy-Ferrell is this something you're already working on? If not I have some ideas.

**Comment by Troy-Ferrell** [comment]
No I haven’t. We can add a saved state
