### ISSUE TITLE
pointers should not always raise PointerClicked on InputUp

### ISSUE THREAD

**Issue by naostranMS** [microsoft/MixedRealityToolkit-Unity#4998]
## Describe the bug

In HTK, we used to get InputClicked events in response to tap events from the gesture recognizer (for WMR/HL). Now in MRTK, it seems that the tap event isn't handled at all, and PointerClicked happens unconditionally with PointerUp (at least for BaseControllerPointer, GGVPointer, and PokePointer) whereas there used to be a distinction: tap would only happen when there's a short time between input down/up, whereas hold/manipulate happen after a long period of time (it seems like tap and hold should be mutually exclusive, but I'm not 100% certain if that is actually the case for WMR).

Often PointerUp and PointerClicked can be used interchangeably, but there are some cases where it is helpful to just respond to a click - particularly when hold and/or manipulate are also used for different functionality, in which case it is helpful to have the other gestures filtered automatically.

Note that UnityTouchController already works that way (although it's kind of weird that sometimes the event is coming from the pointer and other times from the controller) - it would be nice to see the same applied to other controller types (WMR in particular).
 
Here's the old version:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/98365a45ca0a8d99b857afb288a4b4dbc4311daf/Assets/HoloToolkit/Input/Scripts/InputSources/GesturesInput.cs#L38
And the new one:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/e5dac4afce15cc6719b6cd11b965b1dcb0919a6a/Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityDeviceManager.cs#L403

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive

**Comment by naostranMS** [comment]
@julenka You had mentioned also having an issue with this in the past - do you have any insight into whether using the tap gesture (for WMR at least) - as it used to - would work?
I'm currently in the process of adding support for the tap gesture to input sim and WMRDeviceManager, so it would be easy enough for me to switch this over to tap if that is a helpful change.

**Comment by julenka** [comment]
I think the tap gesture  would only get raised on device if you release select without moving, is that what you were asking about?

**Comment by julenka** [comment]
Hm...what do you mean by a tap gesture? Do you mean a press followed by a release, or just a press?

**Comment by naostranMS** [comment]
yeah, the tap gesture is *I think* mutually exclusive with hold/manipulate - i.e. you only get the tap on input up if the time between down and up wasn't long enough to start a hold gesture, and the hand movement delta wasn't far enough to start a manipulate gesture

**Comment by Yoyozilla** [comment]
This is blocking MRW. Layout has to fork to workaround this. Kurtis and Nathan actively discussing the solution

**Comment by julenka** [comment]
This should be fairly easy to fix directly in the pointer, just have a timer and possibly a check in on pointer up—don’t raise click of pointer has been pressed too long it has moved to much.

**Comment by julenka** [comment]
Kurtis is there some subtlety I’m missing?

**Comment by davidkline-ms** [comment]
addressed by #5051
