### ISSUE TITLE
Can't delete select and delete pointer options in Input Profile

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#5004]
## Describe the bug

It's currently not possible to select and delete existing pointer options in the input profile. The button for deleting is there but we can't select any elements in the list so the button is not working.

## To reproduce
-Select the MRTK gameobject 
- navigate to Input
- inspect the pointer options
- try selecting one of them and pressing the - button for deleting them

## Expected behavior
- pointers entries should be selectable and deletable

## Your Setup (please complete the following information)

- Unity Version 2018.4
- MRTK Version 2 RC2.1

**Comment by Troy-Ferrell** [comment]
@thalbern FYI as workaround, if you set handness to nothing then the pointer should be active for any input

**Comment by Troy-Ferrell** [comment]
@thalbern Also if you double click directly into the pointer profile, then you can select & delete pointers
