### ISSUE TITLE
[Docs] FocusProvider not documented

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#5005]
## Describe the Issue
I can't seem to find any documentation on using FocusProvider. Maybe it could be part of pointers? There definitely needs to be some guidance of how one can figure out what is in focus for a given pointer as well as how to access all the available pointers currently available. 

## Feature Area
ex: Developer should be able to easily write a line of code for "What gameobject is my right hand ray hitting?"

## Existing Doc Link
If this is about something in an existing document, please provide link

**Comment by wiwei** [comment]
We added some documentation here on focus/pointers here:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Architecture/InputSystem/ControllersPointersAndFocus.html

I think what's still missing is that prescriptive "here's how you do the easy thing you wanna do"
