### ISSUE TITLE
Having eye-tracking and gaze dwell selection at the same time

### ISSUE THREAD

**Issue by Jordu29** [microsoft/MixedRealityToolkit-Unity#5009]
## Describe the problem

The use-case concerns a UI window for a user who can't make use of his hands (busy doing something else) or voice (assuming voice recognition would not work 100% of time).

I'd like to be able to use a GazeCursor which could dwell on UI buttons to trigger them but I'd also like to use Eye Tracking so the user is also able to scroll over text using ET inside the same window.

As far as I know we can't use both system at the same time right now with MRTK v2

**Comment by wiwei** [comment]
@sostel in case there's been some research in this

**Comment by sostel** [comment]
Hey @Jordu29, interesting! Is there a reason why you don't want to use the EyeGazeCursor to dwell? 

In any case, the question came up a few times to use some form of head gaze + eye gaze: @wiwei Does MRTK support this?

**Comment by polar-kev** [comment]
Hey @Jordu29, this is not something that's currently supported in MRTK v2. After speaking with @Zee2, it is something that would be easy to support in MRTK v3. Given that this is an old issue and we haven't heard back from you, I'm going to close this request. Feel free to reopen if you would like to see it in MRTK v3.
