### ISSUE TITLE
Eye tracking simulation in editor

### ISSUE THREAD

**Issue by Jordu29** [microsoft/MixedRealityToolkit-Unity#5010]
## Describe the problem

Right now the eye tracking simulator uses the center of the Main Camera FoV. What would have been great is having the eye tracking simulator being separate from the center of the MC FoV so we could simulate limit cases such as using eye tracking on the edge of Hololens FoV. One idea that came up to my mind is having the eye tracking following the mouse when holding the left mouse button (which if I recall correctly is not used in Play Mode)

**Comment by julenka** [comment]
Completed!

**Comment by julenka** [comment]
You can check "simulate eye tracking" in input simulation profile

![image](https://user-images.githubusercontent.com/168492/68610857-a2f2f800-046d-11ea-937b-9513f38b26e0.png)
