### ISSUE TITLE
GazeProvider should use the same LayerMask as pointers

### ISSUE THREAD

**Issue by timothyt** [microsoft/MixedRealityToolkit-Unity#5020]
## Describe the problem

I was trying to track down why gaze wasn't interacting with an object that had a custom layer and discovered that the GazeProvider pointer uses a Layermask set in the inspector for the GazeProvider component on the Camera while Pointers use PointingRaycastLayerMasks set in the Pointer Profile. This is confusing and seems inconsistent since GazeProvider seems to be treated as a Pointer by FocusProvider

Additionally I see that GazeProvider always assigns it's RaycastLayerMask to PrioritizedLayerMasksOverride. This results in FocusProvider using PrioritizedLayerMasksOverride instead of FocusLayerMasks. Is this how PrioritizedLayerMasksOverride is intended to be used? 

## Describe the solution you'd like

Documentation for FocusProvider and intended usage of PrioritizedLayerMasksOverride

## Describe alternatives you've considered

Changing GazeProvider so it doesn't assign to PrioritizedLayerMasksOverride in which case the LayerMask from the Pointer Profile will be used

**Comment by naostranMS** [comment]
I agree that this is kind of weird (and it seems to apply to pointer extent as well). I can see some advantages to the gaze provider's pointer being internal, but it would also be nice if it could be configured with the other pointers and make use of the global pointer settings.

**Comment by RogPodge** [comment]
Fixed with #10508
