### ISSUE TITLE
Selecting Input category in MixedRealityToolkit in play mode deletes UIRaycastCamera

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5025]
## Describe the bug

The UIRaycastCamera gets deleted wheh the Input category from the MixedRealityToolkit is selected.

## To reproduce

1. Run any scene with the MRTK in it
2. Select the MRTK
3. Choose Input in the inspector
4. See error and that the UIRaycastCamera is missing

## Expected behavior

UIRaycastCamera does not get deleted

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1
- MRTK Version development branch

**Comment by Troy-Ferrell** [comment]
@Alexees how recently have you pulled the development branch? This sounds like #4944 which was recently fixed by #4991 . Can you please check you pull latest and close this issue if no longers repos? Thanks!

**Comment by Alexees** [comment]
Yes, gone. I was exactly 6 commits behind and the oldest was it.
