### ISSUE TITLE
BoundingBox uses null check on structs

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5028]
## Describe the bug

Two Vector3 variables (maximumScale, minimumScale) are checked for null:

```
        public float ScaleMaximum
        {
            get
            {
                return maximumScale != null ? maximumScale.x : scaleMaximum;
            }
        }

        public float ScaleMinimum
        {
            get
            {
                return minimumScale != null ? minimumScale.x : scaleMinimum;
            }
        }
```

I would have fixed it myself, but I don't know what the coding convention says about nullables.

**Comment by wiwei** [comment]
Yeah, this actually just doesn't make any sense. It would make a lot of sense to just remove the null checks here. We should fix this up, but also marking as Help Wanted since it's a relatively simple thing to do.

**Comment by wiwei** [comment]
Closing this issue, as the linked PR has gone in.
