### ISSUE TITLE
SpectatorViewSetup needs updating

### ISSUE THREAD

**Issue by jessedsiegel** [microsoft/MixedRealityToolkit-Unity#5032]
I'm following the guide here:

[https://github.com/microsoft/MixedRealityToolkit-Unity/blob/feature/spectatorView/Assets/MixedRealityToolkit.Extensions/SpectatorView/SpectatorViewSetup.md](url)

Steps 10 and 11 appear to refer to older versions of the SpectatorView script. I believe the spatial anchor id, key, and domain should now be set in the AzureSpatialAnchorsDemoConfig asset. 

I could be wrong, I can't get builds working on Hololens or Android anyway.

Also, should the ip address be changed on the SpectatorView script for Hololens builds?

**Comment by Yoyozilla** [comment]
Please reopen your issue in our new spectator view GitHub Repo:
https://github.com/Microsoft/MixedReality-spectatorview
