### ISSUE TITLE
InputActionHandler script wrong initialization for list of actions (missing MixedRealityToolkit)

### ISSUE THREAD

**Issue by mtirion** [microsoft/MixedRealityToolkit-Unity#5037]
## Describe the bug

In some cases the UI for the InputActionHandler script is not initialized well. This results in a list of actions where only "Missing MixedRealityToolkit" is shown. Clicking on MixedRealityToolkit and go back to the GameObject and it's solved.

## To reproduce

1. Add a GameObject
2. Add InputActionHandler script from MRTK to the GameObject
3. Press Unity PLAY
4. Press Unity STOP
5. Notice the "Missing MixedRealityToolkit" text in the Actions list.

## Expected behavior

It should just show the list of actions

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1 (LTS)
- MRTK Version v2.0 RC2.1

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by MenelvagorMilsom** [comment]
I don't think this repros on the latest mrtk_development

**Comment by Troy-Ferrell** [comment]
This doesn't repo truly on latest mrtk_devlepment. (It may show missing MRTK for one editor frame refresh quickly). This I believe was largely fixed by #4661
