### ISSUE TITLE
BoundingBox causes error after dynamic add in script

### ISSUE THREAD

**Issue by mtirion** [microsoft/MixedRealityToolkit-Unity#5038]
## Describe the bug

GameObjects are created in a loop on the main thread. BoundingBox and Manipulator scripts are added to those objects. Because it's a large number of GameObjects that need to be added it's done in multiple frames. This results in an error during one of the frames:

Microsoft.MixedReality.Toolkit.UI.BoundingBox:UpdateRigHandles() (at Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs:1635)
Microsoft.MixedReality.Toolkit.UI.BoundingBox:CreateRig() (at Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs:721)
Microsoft.MixedReality.Toolkit.UI.BoundingBox:set_BoxGrabbedMaterial(Material) (at Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs:219)

It could be solved by creating a Coroutine. But the script shouldn't crash.

## To reproduce

Create large number of GameObjects with the script attached over multiple frames.

## Expected behavior

No crash

## Screenshots

n/a

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1
- MRTK Version v2.0 RC2.1

## Target Platform (please complete the following information)

- HoloLens 2

## Additional context

n/a

**Comment by wiwei** [comment]
We've made a number of fixes to BoundingBox since the 2.1 release (that should make it possible to dynamically add it) - can you try out the latest mrtk_development?

**Comment by wiwei** [comment]
Please reopen if this is still an issue for you
