### ISSUE TITLE
Speech Input Handler UI breaks after playmode

### ISSUE THREAD

**Issue by floAr** [microsoft/MixedRealityToolkit-Unity#5039]
## Overview
The speech input handler component losses most of its editor ui after entering playmode and leaving it again. Selecting the mrtk object in the scene tree 'resets' the behaviour until next playmode. 
Seems to be only visual as speech commands keep working.

## Expected Behavior
Component should still be configurable after leaving playmode once.

## Actual Behavior
It is not
Perfore playmode
![grafik](https://user-images.githubusercontent.com/765387/60086833-1ead0c00-973c-11e9-9e78-81d193bd8cfc.png)
In playmode
![grafik](https://user-images.githubusercontent.com/765387/60086871-2c629180-973c-11e9-8c18-ca82696dcb68.png)
After playmode
![grafik](https://user-images.githubusercontent.com/765387/60086889-35536300-973c-11e9-801a-1013641c8174.png)

## Unity Editor Version
2018.4.2f1
## Mixed Reality Toolkit Release Version
Mixed Reality Toolkit 2.0.0-RC2.1

**Comment by Troy-Ferrell** [comment]
It's just a visual issue. This has been largely fixed by #4661 which is beyond
