### ISSUE TITLE
ManualCameraControl in Docs and Documenting Changes

### ISSUE THREAD

**Issue by jbienzms** [Microsoft/MixedRealityToolkit-Unity#504]
ManualCameraControl is still referenced at these locations:

[ColorPicker Readme](https://github.com/Microsoft/HoloToolkit-Unity/blob/135224a041201d388945a516bfdb0423ac9536cb/Assets/HoloToolkit-Examples/ColorPicker/README.md)

[MDFiles Readme](https://github.com/Microsoft/HoloToolkit-Unity/blob/bbc2aa9c4d44180bf3e2cfe719844ae324229025/External/HoloToolkit/Utilities/DocSource/MDFiles/ReadMe.md)

[Input Readme](https://github.com/Microsoft/HoloToolkit-Unity/blob/229e4ee9ba5282b496281badce15e9efbd18a216/Assets/HoloToolkit/Input/README.md)

Also, any thoughts on how we can better document changes? It took me several minutes to find out that **ManualCameraControl** had been renamed to **ManualGazeControl**. It also appears that this script has changed so much that we should probably bring in the **HoloLensCamera** prefab instead. But neither of these changes appear to be documented anywhere. The only way I figured this out was through web search that landed me on an issue where someone mentioned the rename. How can we better document changes to key components in the toolkit? Especially to the names of core behaviors.

**Comment by HodgsonSDAS** [comment]
I'm curious to know if the MDFiles were autogenerated.  Could be fairly easy to just regenerate.

I also noticed a lot of those files are not directly linked anywhere in the main page, and I didn't even know a lot of them existed until recently.

**Comment by NeerajW** [comment]
I believe [Doxygen](http://www.stack.nl/~dimitri/doxygen/) is a tool that can be used to generate API docs. I have not tried it personally though.

**Comment by davidkline-ms** [comment]
We need a doc scrub in master and vNext will be properly documented (and maintained) going forward.

**Comment by keveleigh** [comment]
For MRTK v2, our documentation is now generated and built to https://microsoft.github.io/MixedRealityToolkit-Unity/.

Going forward, `xref`s in the documentation should break when scripts are renamed, making it more obvious when things go stale.

Closing this, as we now have a better plan for change documentation and a central location to find it and search for it.
