### ISSUE TITLE
Camera destroyed when selecting different profiles in the inspector

### ISSUE THREAD

**Issue by MenelvagorMilsom** [microsoft/MixedRealityToolkit-Unity#5040]
## Describe the bug

Swapping off of camera in the profile inspector while in play mode causes the camera to be destroyed and MissingReferenceExceptions. 

## To reproduce

1. Start play mode
1. Open the mrtk profile
1. Switch from the camera profile to another profile in the inspector
1. Observe exceptions

![DestroyCamera](https://user-images.githubusercontent.com/47415945/60087741-e4446e80-973d-11e9-8dd5-2c2c38e5b89a.gif)

**Comment by keveleigh** [comment]
This sounds like the issue that was fixed with https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4991

**Comment by Troy-Ferrell** [comment]
Yes it is a dupe
