### ISSUE TITLE
Breaking change detection automation

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#5042]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/320

___

In our current mode of work (2019/06/25), all of our breaking change detection is manual - we review PRs, and try to catch breaking changes there, or we, as part of our day-to-day work, recognize if a change is going to be breaking and document it.

This might not scale in the future as more work gets done, and it depends on the careful eyes of reviewers to catch something that should ideally be automated.

This is likely to require a decent upfront investment, but adding this to our backlog so that this work/feature can be tracked and prioritized.

**Comment by davidkline-ms** [comment]
Adding myself as an assignee... i have some experience in tooling to do build-over-build surface area comparisons

**Comment by davidkline-ms** [comment]
While this is a tool that is planned (and, in fact, begun) it is being tracked elsewhere.

**Comment by keveleigh** [comment]
> While this is a tool that is planned (and, in fact, begun) it is being tracked elsewhere.

Where is "elsewhere"?

**Comment by davidkline-ms** [comment]
The tracking is being done internally, though @keveleigh has a great point. We should use this issue for tracking / public accountability.
