### ISSUE TITLE
show error when  Build  Microsoft Mixed Reality Toolkit v2.0.0 RC2.1

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#5056]
## Describe the bug
Assets\MixedRealityToolkit.Providers\WindowsMixedReality\WindowsMixedRealityArticulatedHand.cs(390,73): error CS0246: The type or namespace name 'HandJointKind' could not be found (are you missing a using directive or an assembly reference?)

## To reproduce

1.  Building scene PressableButtonExample 

## Screenshots
![image](https://user-images.githubusercontent.com/38685433/60155965-fdbce780-981d-11e9-97c5-9a1377c107ac.png)

## Your Setup (please complete the following information)

- Unity Version [2018.4.0f1 LTS]
- MRTK Version [v2.0.0 RC2.1]

## Target Platform (please complete the following information)
- HoloLens

**Comment by MenelvagorMilsom** [comment]
Looks like it may be a Windows SDK version issue. See #4668

**Comment by wiwei** [comment]
Please follow the getting started guide's prerequisite section:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html#prerequisites

The reason this is happening because the latest SDK is missing.
