### ISSUE TITLE
Auto-generated camera is missing MixedRealityInputModule

### ISSUE THREAD

**Issue by lukastoenneMS** [microsoft/MixedRealityToolkit-Unity#5061]
## Describe the bug

When the CameraCache does not find a camera it will auto-generate one. This auto-generated camera, however, does not have a MixedRealityInputModule script component on it.

The MixedRealityInputModule script pipes MRTK input data into the Unity event system. It is necessary in particular for make Unity UI elements work.

## To reproduce

1. Create an new scene
1. _Mixed Reality Toolkit > Add to Scene and Configure_
1. Remove the main camera from the MixedRealityPlayspace
1. Enter PlayMode

A new camera is generated automatically with a warning:
"No main camera found. The Mixed Reality Toolkit requires at least one camera in the scene. One will be generated now."

## Expected behavior

The generated camera has a MixedRealityInputModule. Unity UI elements work.

## Additional context

Playmode tests are using auto-generated camera and do not work with Unity UI buttons for this reason.

Note that the MixedRealityInputModule type is in the InputSystem service assembly and is not accessible directly in the CameraCache.

**Comment by wiwei** [comment]
Just tried this out on latest, looks like the input module is getting added. (I thought I saw @railboy make a change to address this some time back)
