### ISSUE TITLE
[Partner Hack] Using XRTK blocking HL2 feature implementation

### ISSUE THREAD

**Issue by vijang** [microsoft/MixedRealityToolkit-Unity#5073]
Customer: ByteCubed (U.Group)

Problem Description: 
Customer is using XRTK (Fork of MRTK1 with support for magic leap) with customizations, which may make implementing HL2 features more difficult

Impact: 
Making it harder to implement HL2 features, as XRTK doesn't support HL2 and MRTK2 doesn't support Magic Leap. 

@hannesne filing bug from SF hack #

**Comment by wiwei** [comment]
Closing as this isn't an issue about the MRTK
