### ISSUE TITLE
[Partner Hack] Border thickness in MRTKStandShader is different on device

### ISSUE THREAD

**Issue by vijang** [microsoft/MixedRealityToolkit-Unity#5075]
Problem: 
Border thickness in MRTKStandShader is different on device than in editor. Images above show what's shown in editor versus on HL2.

 

Partner is using a quad with an image. Quad is stretched to make it wide, but in editor it looks very different to on-device.

See attachment for images

Partner:Afternow

Reported by: @danielescudero

**Comment by wiwei** [comment]
@vijiang, can you please reopen this bug with more detailed information? There's not a lot for us to go on in this issue.
