### ISSUE TITLE
[Partner Hack] Multi-lens Sharing

### ISSUE THREAD

**Issue by vijang** [microsoft/MixedRealityToolkit-Unity#5076]
Found: London Hack
Customer: OverIT
Problem Description: 
They currently use the sharing solution in MRTK v1 and need an equivalent set of features in MRTKve for HoloLens 2.

@ActiveNick bug from London hack

**Comment by Yoyozilla** [comment]
Sharing will be a standalone component in a separate repo. Please join the public sharing weekly shiproom for details :)
