### ISSUE TITLE
[Partner Hack] "Eye-Supported Positioning" MRTK sample scene lists incorrect instructions for placing objects 

### ISSUE THREAD

**Issue by vijang** [microsoft/MixedRealityToolkit-Unity#5078]
Copied from Description when changed from Task to Bug
Problem: 
MRTK's "Eye-Supported Positioning" scene text and online documentation ​says, "Look at one of the boxes below and say 'Put this,' then look over where you want to place the hologram and say 'here.'" However, the word "here" in the explanation for placing objects does not work. The phrase you need to say is "OVER here."

Reprot steps: 

Build and deploy fully functional MRTK Sample Scene "EyeTrackingDemo-04-TargetPositioning.unity"  

Partner: 

Digital Surgery

Filed for: @SarahSexton

**Comment by wiwei** [comment]
Ah, I remember this one - I fixed the docs at the hack.
