### ISSUE TITLE
[Partner Hack] Video decoding

### ISSUE THREAD

**Issue by vijang** [microsoft/MixedRealityToolkit-Unity#5079]
Problem: 
Video decoding is very slow on device, affecting framerate. Neither H.265 nor H.264 worked. Jerome from Unity is investigating and filing a ticket with Unity. Streaming the same codec from the internet worked fine, so this could be an "on device" issue.

Partner: 

Digital Surgery

Filed for: @SarahSexton

**Comment by Troy-Ferrell** [comment]
@vijang how are you doing video decoding? What is the texture format you are using?

**Comment by vijang** [comment]
@SarahSexton do you have further info regarding this bug?

**Comment by wiwei** [comment]
@vijiang, @SarahSexton please reopen the issue when you get some more details added!
