### ISSUE TITLE
Refactor redundant Interpolation Scripts

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#508]
[QuaternionInterpolated.cs](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/InterpolatedValues/QuaternionInterpolated.cs) and [Vector3Interpolated.cs](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/InterpolatedValues/Vector3Interpolated.cs) seems to be very similar to
 [InterpolatedQuaternion.cs](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/InterpolatedValues/InterpolatedQuaternion.cs) and [InterpolatedVector3.cs](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/InterpolatedValues/InterpolatedVector3.cs)

**Comment by davidkline-ms** [comment]
Chose one and deprecate the other (in master)
Bring the chosen one forward in vNext.
@keveleigh and i vote for keeping "Interpolated..." for consistency of naming.
