### ISSUE TITLE
[Partner Hack] Interactable component errors when loaded programmatically

### ISSUE THREAD

**Issue by vijang** [microsoft/MixedRealityToolkit-Unity#5080]
Description: 
When adding the Interactable component dynamically onto game objects at run time, get null reference errors

Workaround: Have to create a game object with an interactable component ahead of time in editor, than copy that component onto a game object at runtime

Partner/Customer: Stryker
Filed for: @TobiahZ  during Redmond June hack

**Comment by wiwei** [comment]
@julenka, did the GA work around Interactable improve this stuff at all? I know that we've made huge strides in other UX controls/scripts

**Comment by julenka** [comment]
Yup this has been fixed.
