### ISSUE TITLE
[Partner Hack] ARM support and MRTKv2 equivalent needed for HoloLens apps built with UrhoSharp

### ISSUE THREAD

**Issue by vijang** [microsoft/MixedRealityToolkit-Unity#5082]
Description: 
Atos' Augmented Field Worker app built is with UrhoSharp, collaboration and features A/V calls via WebRTC, digital twin data, PDF doc viewer, management ERP features. They need updated support for UrhoSharp to compile their app and plugins for ARM and also get access to components similar to MRTKv2 for hand interactions, solvers, etc.

Partner: Atos
Filed for: @ActiveNick  during Paris hack

**Comment by wiwei** [comment]
@ActiveNick This looks like a  request specifically for UrhoSharp support for ARM? If so we probably want to close this issue and have folks follow up with UrhoSharp
