### ISSUE TITLE
Grid Object Collection script Layout setting not working

### ISSUE THREAD

**Issue by mtirion** [microsoft/MixedRealityToolkit-Unity#5092]
## Describe the bug

In the Editor panel for Grid Object Collection there is a dropdown for Layout with "First Row then Column" and "First Column then Row" and an "Update Collection" button. That doesn't show a different pattern. I don't think the logic is correct in ResolveGridLayout() as it always works per row (horizontal), where "first column then row" should go vertical first.

## To reproduce

Open the ObjectCollectionExamples scene, Pick one if the collections and give each cube in the collection a different color. Then play with the Layout setting and the "Update Collection" button. The code is hit every time, but it doesn't show a different result.

## Expected behavior

"First Row then Column" should show items first items in the first row, the next items in the next row. "First Column then Row" should show item 1 in row 1, item2 in row 2 until the max rows. Then go to the next column, 

## Screenshots

n/a

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1
- MRTK Version v2.0 RC2.1

## Target Platform (please complete the following information)

- HoloLens 2

## Additional context

n/a

**Comment by Alexees** [comment]
There might be a fix here #3919, but I don't know if and into which release this went. You could grab the code and see if it fixes it for you.

**Comment by Troy-Ferrell** [comment]
This works in latest version of MRTK_development on Unity 2018 LTS
