### ISSUE TITLE
Updating Legacy Hololens Code (what happened to the TestButton object?)

### ISSUE THREAD

**Issue by MichaelZhou** [microsoft/MixedRealityToolkit-Unity#5104]
I'm currently working on a new project using HoloToolKit 2017.4.3.0, and I'm trying to re-use some code that was written between May-August 2017, the version used was likely v1.5.7.0,  [HoloToolkit-Unity for Unity 5.6.1f1+](https://github.com/microsoft/MixedRealityToolkit-Unity/releases/tag/v1.5.7.0)

In the MixedRealityToolkit-Unity for Unity 2017.1.2f1 update, the Test and Example folders were merged, and in my old code I now have a deprecated object called TestButton. 

Can someone direct me on what happened to TestButton and what I need to do to get my old code working in the newer version of the toolkit that I'm using?

**Comment by wiwei** [comment]
I still see this here: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/htk_release/Assets/HoloToolkit-Examples/Input/Scripts/TestButton.cs
