### ISSUE TITLE
HandInteractionExample in HL2 scene drops to 30 fps when you bring hands up

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5107]
## Overview
When compiled in Master or Release, the hand interactionexamples scene on HoloLens2 will drop to 30 fps when you bring your hands into view, and stays that way even when hand mesh and joints are turned off.

## Expected Behavior
Framerate should stay at 60.

## Steps to reproduce
1. Build and deploy HandInteractionExample scene to HoloLens 2
2. Keep the profiler on.
2. Play around with the holograms for about 1 minute, especially bounding box
3. Bring hand up and target the lunarmodule with hand rays

You will notice that after being on for a while the framerate will drop to 30 fps.

## Mixed Reality Toolkit Release Version
mrtk_development latest

**Comment by lukastoenneMS** [comment]
@Railboy Can we consider this fixed now?

**Comment by wiwei** [comment]
Closing this one out.

**Comment by Railboy** [comment]
@lukastoenneMS @wiwei There are still performance issues with hand interaction that should be looked into. I will write up a separate issue after some more research. They're not severe enough to kill the frame rate for the hand interaction examples scene, so we can consider this closed.
