### ISSUE TITLE
Can not build scene 

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#5108]
## Describe the bug

Reference Rewriter found some errors while running with command "--target=Temp\StagingArea\Data\Managed\Assembly-CSharp.dll" "--target=Temp\StagingArea\Data\Managed\MixedRealityToolkit.Services.CameraSystem.dll" "--target=Temp\StagingArea\Data\Managed\MixedRealityToolkit.Examples.Demos.UX.Interactables.dll" "--target=Temp\StagingArea\Data\Managed\MixedRealityToolkit.Examples.Demos.Utilities.InspectorFields.dll"

**If I ignore these errors and deploy on Hololens 1 , but I can not see anything .**

## To reproduce

1. Build scene PressableButtonExample
2. see errors 

## Screenshots

![image](https://user-images.githubusercontent.com/38685433/60313785-f9fea180-9992-11e9-8b1a-13405538166b.png)
![image](https://user-images.githubusercontent.com/38685433/60314036-c53f1a00-9993-11e9-8c2c-413c7fdf1a06.png)

## Your Setup (please complete the following information)

- Unity Version [2018.4.2f1 ,  2018.4.0f1]
- MRTK Version [v2.0.0 RC2.1]

## Target Platform (please complete the following information)

- HoloLens

**Comment by IfnoLee** [comment]
[fixed in Unity 2019.1.8](https://unity3d.com/unity/whats-new/2019.1.8)
![image](https://user-images.githubusercontent.com/38685433/60315683-2a960980-999a-11e9-9390-9242743466db.png)

**Comment by Alexees** [comment]
These errors are normal and can be ignored https://github.com/microsoft/MixedRealityToolkit-Unity/issues/3939#issuecomment-484377528
