### ISSUE TITLE
Allow manual ordering of Solvers for a SolverHandler

### ISSUE THREAD

**Issue by romsahel** [microsoft/MixedRealityToolkit-Unity#5110]
## Describe the problem
As noted in the ["Known Issues"](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_Solver.html#known-issues), we currently have to set the Solvers' order of execution in case of a problem: it is neither practical nor does it allow it to be done per-instance. 

## Describe the solution you'd like
Currently, the list of solvers is obtained `GetComponents<Solver>()`: exposing the list so that it can be manually ordered within the inspector and from the code would solve this issue.

## Additional context
Solvers

**Comment by keveleigh** [comment]
The list should be returned in the order they're positioned in the Inspector (higher = earlier), so I don't think script execution order needs to be changed. I'll update the known issue to clarify that.

Though! There are some solver improvements planned, so making this list more explicit definitely sounds like something that should be considered.

**Comment by romsahel** [comment]
Oh, alright. Documentation seemed to talk about the _script execution order_! I apologize, I should've checked :), I didn't know the order of elements returned by `GetComponents` depended of the order in which they are added.

> making this list more explicit definitely sounds like something that should be considered.

Indeed! I can see use cases where the list of Solvers should be determined at runtime, after the initialization of the SolverHandler.
