### ISSUE TITLE
Parabolic drag line tip overshoots target position

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5112]
## Describe the bug

When holding onto a GameObject, the pointer gets fixed in position and the parabolic pointer bends while moving the motion controller. In doing so, the tip of the parabola seems to moving ahead of the current position instead of always ending where the pointer is. It always overshoots the position it should end in which leads to circling the pointer when the motion controller is actually moved in a circle.

Video:
[Preview.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3338512/Preview.zip)

## To reproduce

1. Grab something that does not move and move your motion controller.

## Expected behavior

the parabola always ends at the center of the pointer or hold position, whatever it's called

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1
- MRTK Version mrtk_development 27.06.

## Target Platform (please complete the following information)

- WMR immersive

**Comment by wiwei** [comment]
@keveleigh, any thoughts here on the original design/intent? I can see that the slight shifting could be thought of as a feature (i.e. you see that your motion still does SOMETHING, just nothing major)

**Comment by Alexees** [comment]
This seems fixed from all the usage lately
