### ISSUE TITLE
Bounding Sphere from Dynamics 365 Guides 

### ISSUE THREAD

**Issue by Phuc-BMW** [microsoft/MixedRealityToolkit-Unity#5113]
## Describe the solution you'd like

Our end users are very happy with using the bounding sphere of Dynamics 365 Guides to get a comfortable usability for rotating and scaling the icons precisely e.g. arrow, marks, etc, instead of using the classic bounding box of the MRTK. With the bounding sphere, they can rotate dynamically around the X- and Y-Axis, and also use the free axis rotation. Also they can scale with a dynamic scale bar.

## Describe alternatives you've considered

Our end users still have problems with using the classic bounding box of the MRTK. Sometimes, they can't catch the corners and edges precisely and couldn't do a proper rotation.

## Additional context

We would look forward to the bounding sphere feature for the next MRTK release. :)

**Comment by Zee2** [comment]
Closing as stale.
