### ISSUE TITLE
MSBuild not found during build scripts

### ISSUE THREAD

**Issue by MenelvagorMilsom** [microsoft/MixedRealityToolkit-Unity#5114]
## Describe the bug
A partner at the Berlin Hack tried to extend BuildAppx method to build for HL2. However, BuildAppxAsync throws an error when trying to find MSBuild.exe:
![msbuildfail](https://user-images.githubusercontent.com/47415945/60334198-346c3c80-999b-11e9-9df5-1c63363cb1e9.png) 

The problem is probably that the methods expects to find the MSBuild.exe in a directory that ends with _\MSBuild\15.0\Bin\MSBuild.exe_ but MSBuild cannot be found at this locaton for there VS Installation.

## Expected Behaviour
The build should find MSBuild independent of where it is located in your VS installation.

**Comment by wiwei** [comment]
Resolved by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5415, which was submitted on behalf of @julianloehr-kg
