### ISSUE TITLE
Pinch slider properties are changing on their own

### ISSUE THREAD

**Issue by gergely-xyz** [microsoft/MixedRealityToolkit-Unity#5117]
## Description
The "Slider Start Distance" and "Slider End Distance" properties of the Pinch Slider script keep changing without any user input.

## To reproduce
Add a Pinch slider prefab to the scene from MRTK2 RC2.1
MixedRealityToolkit.SDK\Features\UX\Prefabs\Sliders
Play the scene, stop it and select the slider object in the Hierarchy.

## Screenshots
https://imgur.com/a/9kvfhXX 

## My setup
- Unity Version 2019.1.8f1
- MRTK Version v2.0.0 RC2.1

## Target Platform
- HoloLens
- HoloLens 2

## Additional context
I used holographic remoting when the problem first showed up.

**Comment by CDiaz-MS** [comment]
The slider behavior was tested with the input simulation and using the windows holographic remoting.  The slider start and end distance remained constant.  

The issue has been resolved in the latest release MRTK 2.0.0. If this behavior is present on a future release, please open again.
