### ISSUE TITLE
OnFocus events are not routed through global listeners

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5119]
## Describe the bug

The IMixedRealityFocusHandler interface can be implemented and registered with the InputSystem.RegisterHandler method. Yet nothing is received because the FocusProvider directly calls the receiver instead of passing through the regular eventchain.
(I mentioned it in #3607 and forgot about it)

## To reproduce

1. Register any IMixedRealityInputHandler implemeter with the InputSystem and gaze on something
2. Note that you do not receive anything

## Expected behavior

You can listen to all events you are allowed to register the corresponding interface for.

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1
- MRTK Version mrtk_development 27.06.

## Target Platform (please complete the following information)

- Editor

**Comment by wiwei** [comment]
Closing this as the linked PR is in
