### ISSUE TITLE
MRTK Utilities Build Window is not documented

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#5121]
## Describe the Issue
The benefits and how-to of using the MRTK build window is not documented anywhere. The build tool also in particular does some added benefits such as inserting the xml in VS for the ARM64 issue as well as setting the eye gaze capability since Unity does not provide. 

Docs should probably also call out IL2CPP optimizations:
https://docs.unity3d.com/Manual/IL2CPP-OptimizingBuildTimes.html

## Feature Area
Missing details on build window

## Existing Doc Link
If this is about something in an existing document, please provide link

**Comment by cre8ivepark** [comment]
@keveleigh Created skeleton page with screenshots. Draft Docs PR: https://github.com/MicrosoftDocs/mixed-reality-pr/pull/2915

**Comment by keveleigh** [comment]
Closed via MicrosoftDocs/mixed-reality-pr#2915
