### ISSUE TITLE
Build error when a scene with MRTK instance is open in editor

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedRealityToolkit-Unity#5131]
## Describe the bug

When building while a scene with an MRTK instance is open, if that scene has entered play mode, an error is caused due to an OnValidate call in the instance.

## To reproduce

- Open scene with MixedRealityToolkit instance
- Play scene
- Stop scene
- Build player
- Observe error

## Your Setup

- Unity Version 2019.1
- MRTK branch mrtk_development

**Comment by keveleigh** [comment]
Reopening due to revert in #5178

**Comment by wiwei** [comment]
@Railboy, is this something you can take a look?

**Comment by Railboy** [comment]
@wiwei I'm investigating a way to fix this without the side effects that caused #5178.
