### ISSUE TITLE
InBetweenInspector/-Editor serializes non existing field

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5143]
## Describe the bug

The following field does not exist and causes error when choosing HandJointLeft or -Right in "Tracked Object For Second Transform" in the inspector:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/ab6bfc0b97a59d2ba76b2f1695c43115aba3bb63/Assets/MixedRealityToolkit.SDK/Inspectors/Utilities/Solvers/InBetweenInspector.cs#L23

I don't know what this did so I don't know if this could just be removed as the Inspector code is explicitly using this:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/ab6bfc0b97a59d2ba76b2f1695c43115aba3bb63/Assets/MixedRealityToolkit.SDK/Inspectors/Utilities/Solvers/InBetweenInspector.cs#L42-L46

Additional note: InBetweenInspector is the name of the file, InBetweenEditor the name of the class

**Comment by wiwei** [comment]
Seems like dead code to me - a good candidate for someone getting started here making a contribution
