### ISSUE TITLE
Input not working if MRTK is packed in a Unity Custom Package

### ISSUE THREAD

**Issue by fcagnetta** [microsoft/MixedRealityToolkit-Unity#5146]
## Describe the bug
If you pack the toolkit in a custom package, you will get an error in the Editor saying it can't find the toolkit because it looks for itself in the Asset folder. Then you can edit in the code where to look for, and the error disappears. Everything works fine, but the Input. We did not find out how to make it work.

## To reproduce
Create a custom package with the MRTK. Add the package to your project editing the package manifest.

## Expected behavior
Everything should work normally

## Setup

- Unity Version [e.g. 2018.3.12f1]
- MRTK Version [2.0.0 RC1]

## Target Platform
- HoloLens
- HoloLens 2
- WMR immersive

**Comment by wiwei** [comment]
@fcagnetta, is this when you're treating the MRTK as a psuedo-UPM package (i.e. authoring a package.json file for it?)

Or are you just moving the MRTK into another sub-folder of the Assets folder?

**Comment by fcagnetta** [comment]
@wiwei Yes, it happens if you treat the MRTK as UPM package

**Comment by wiwei** [comment]
Doh, should have asked you also, are you building IL2CPP? (Last question, I swear :))

**Comment by fcagnetta** [comment]
No worries at all :) yes I build IL2CPP

**Comment by wiwei** [comment]
If so, you should check out https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5274

In particular, try pulling in the link.xml into your root assets folder (or as another file root of the UPM package) to see if that helps out.

I suspect that you're getting bytecode stripping issues (which you can also confirm by looking at the generated  IL2CPP .cpp files and seeing that things like the input system and other systems are just missing from the output folder)

**Comment by wiwei** [comment]
@fcagnetta Let us know if this ends up resolving the issue for you!

**Comment by fcagnetta** [comment]
Hi Will, I'll check this out as soon as I come back from Inspire. Hope this will fix :P

**Comment by wiwei** [comment]
Going through issues now, this *should* be resolved - by that link.xml. If you are still having trouble please re-open and ping me.

**Comment by christjt** [comment]
Hey @wiwei, this issue is not due to link.xml, but rather the editor script "MixedRealityToolkit\Utilities\Editor\Setup\MixedRealityToolkitFiles.cs" searching /Assets/ when it should also check /Packages/. As you can read in the original post: "...you will get an error in the Editor", which also indicates that this has nothing to do with link.xml, because the code hasn't been build an hence hasn't been stripped either. Please re-open this issue.

**Comment by wiwei** [comment]
@christjt there are a few issues here - the original post mentions that the person had updated the code to look in the right place, but was hitting issues with the input system specifically.

> If you pack the toolkit in a custom package, you will get an error in the Editor saying it can't find the toolkit because it looks for itself in the Asset folder. **Then you can edit in the code where to look for, and the error disappears. Everything works fine, but the Input.** We did not find out how to make it work.

The specific issue this person was hitting was around bytecode stripping/optimization in Unity.
