### ISSUE TITLE
Local axis on ManipulationHandler constraints

### ISSUE THREAD

**Issue by fcagnetta** [microsoft/MixedRealityToolkit-Unity#5147]
## Describe the problem
When you add manipulation handler to an object you can choose to lock one or more axis in the original rotation. When you then rotate the object, the axis you chose to lock will be locked on the GLOBAL axis (let's say Transform.up for Y-Axis and so on) instead of keeping the local one.

rotation locked Axis does NOT respect local rotation.

## Describe the solution you'd like
ManipulationHandler should check for the original rotation of the object and keep the rotation for the locked Axis.

**Comment by benjamincoven** [comment]
Also it would be great to add constraints on translation. Many times we want to use the bounding box only on the X and Z axis.

**Comment by fcagnetta** [comment]
Hi guys, any news on this feature?

**Comment by wiwei** [comment]
@MenelvagorMilsom @julenka something else to consider for manip handler stuff.

In this case I assume that only a single rotation constraint should exist (i.e. local OR global, not both), so maybe there's just some dropdown above Constraint on Rotation the is "Constraint Locality - global or local")

**Comment by wiwei** [comment]
@benjamincoven somewhat belated but hopefully still useful for you (constraints on translation, though this is for manip handler not bounding box)

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5976

**Comment by MenelvagorMilsom** [comment]
@wiwei, I was planning this as part of my constraint changes.

**Comment by fcagnetta** [comment]
> @wiwei, I was planning this as part of my constraint changes.

this is awesome :D
