### ISSUE TITLE
MRTK initialize itself and set its script execution order

### ISSUE THREAD

**Issue by fcagnetta** [microsoft/MixedRealityToolkit-Unity#5148]
## Describe the problem
Scenario: cross-platform application (UWP-iOS) - Unity scene for iOS

You have the MRTK in your assets and you do NOT have the MixedRealityToolkit object in the scene. The MRTK script has its entry in the script execution order, and you remove it.
When you play the scene: script execution order entry is back and MRTK initializes itself with a default profile.

or (workaround trial):

You have the MRTK in your assets and you HAVE the MixedRealityToolkit object in the scene with a custom profile with all submodules disabled.
When you Play the scene, you get an error because MRTK cannot find the Input Module. In editor, I just go on and everything is fine with my custom Input Module for iOS, but I cannot build the application because of that error.

## Describe the solution you'd like
Maybe a less intrusive MRTK or possibility to enable/disable toolkit at runtime.

## Describe alternatives you've considered
Make a different project only for iOS (with only spatial anchors).

**Comment by wiwei** [comment]
I think this intrusive thing (which adds itself back or wants to add itself back) was removed in the most recent release (or mrtk_development)
