### ISSUE TITLE
controller is not show

### ISSUE THREAD

**Issue by Ashokmaurya** [microsoft/MixedRealityToolkit-Unity#5149]
## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Ashokmaurya** [comment]
I have run the latest project but controller is not show in unity scene

please help me

**Comment by wiwei** [comment]
Hi there,

I'm closing this issue down because there isn't enough information for people to take action on it - please read the template and provide more information on the issue you're hitting, what you expect to work, the platform you're on, etc.
