### ISSUE TITLE
Existing materials should be converted to use FastConfigurable

### ISSUE THREAD

**Issue by dbastienMS** [Microsoft/MixedRealityToolkit-Unity#515]
This would result in a very large performance improvement and show best practices.

**Comment by HodgsonSDAS** [comment]
Disabling Cast Shadows, Receive Shadows, Light probes and reflection probes should probably also be done with this enhancement.

**Comment by solkar** [comment]
How do you keep cross platform projects in that case?

**Comment by HodgsonSDAS** [comment]
Custom build scripts that swap out the materials you'd want per platform.  There's whole libraries devoted just to this sort of thing, for example: http://smuggletruck.com/multiplatform/

**Comment by StephenHodgson** [comment]
@dbastienMS I'm pretty sure we did this.  I'll go ahead and close
