### ISSUE TITLE
Revert mrtk_development specific doc warnings after going up to mrtk_release

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#5155]
This issue tracks the set of changes we'll need to revert after going up to mrtk_release

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5137

**Comment by keveleigh** [comment]
We already have a version drop-down on the docs. Can we start populating it with releases or even just mrtk_release? Then we can be more explicit about docs versioning and hopefully not need disclaimer messages anymore.
