### ISSUE TITLE
SolverHandler does not calculate offset for TransformTarget on Start

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5157]
## Describe the bug

SolverHandler only ever calculates or recalculates its offset transform when either the override transformTarget is empty, or any of the offsets are changed.
This means on start, no offset is given for a transform target.

Bonus: The name of the placeholder transform only ever contains TrackedObjectType.
Additionally, transforms are checked for Null with !transform

## To reproduce

1. Add an Orbital to a gameobject, define an offset on the SolverHandler and press play.

## Expected behavior

If offsets are set, they should be used on all gameobjects the user wants to follow. The inspector and API allow that.

**Comment by keveleigh** [comment]
Fixed via #5158
