### ISSUE TITLE
SphereOverlap QueryScene method should be moved out of FocusProvider and into IMixedRealityRaycastProvider

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedRealityToolkit-Unity#5160]
## Describe the problem

FocusProvider uses IMixedRealityRaycastProvider to handle SimpleRaycast and SphereCast scene query types, but handles SphereOverlap scene query type on its own.

## Describe the solution you'd like

SphereOverlap scene query types should be handled by IMixedRealityRaycastProvider as well for consistency.

**Comment by davidkline-ms** [comment]
This would be a breaking API change. As a rule, MRTK strives to avoid breaking changes (acknowledging that many have been made). At this point in the MRTK v2.x lifecycle, we are closing this issue as it will not apply to MRTK3
