### ISSUE TITLE
Hololens 1 keyboard

### ISSUE THREAD

**Issue by FlorianJa** [microsoft/MixedRealityToolkit-Unity#5169]
## Describe the bug

When opening the system keyboard, the layout of the keyboard is completely messed up. see pictures below:

![20190702_083104_HoloLens](https://user-images.githubusercontent.com/3525062/60493311-dc8c4900-9cac-11e9-8057-5a171dc05268.jpg)
![20190702_083323_HoloLens](https://user-images.githubusercontent.com/3525062/60493316-deeea300-9cac-11e9-9140-e8f1973f1912.jpg)
![20190702_083350_HoloLens](https://user-images.githubusercontent.com/3525062/60493319-e01fd000-9cac-11e9-809e-d3844a67672c.jpg)

## To reproduce

1. Open and deploy HandInteractionExamples demo scene to Hololens 1
2. Open keyboard (left side). The first time it may looks good, after opening it again will mess up the keyboard layout.

## Expected behavior

Working keyboard every time.

## Your Setup (please complete the following information)

- Unity Version: 2019.1.6f1
- MRTK Version: v2.0.0 RC2.1

## Target Platform (please complete the following information)

- HoloLens

## Additional context

I am not sure if it is related to MRTK or a Unity / Hololens issue.
Also the keyboard is looking different every time you open it.
You can also see a lot of exceptions be thrown after opening the keyboard and the framerate droping

**Comment by FlorianJa** [comment]
Tested it with the latest mrtk_development commit and unity 2018.3.11f1 and it work fine except opening the keyboard again (#4373)

**Comment by wiwei** [comment]
AFAIK this is the system keyboard (i.e. something that the MRTK itself has no control over).

I'll forward this on to the folks who own the system keyboard here at MSFT.

**Comment by kevbarn** [comment]
Hi @FlorianJa, this is an OS bug that was recently fixed. Make sure your HoloLens is fully up to date. You'll want at least the 2019-06 Cumulative Update. If you have an OS version number of at least 17763.557, you have the fix for this.

Please let us know if you continue to see this issue on newer OS versions.

**Comment by FlorianJa** [comment]
Yeah, the layout bug is gone, but unfortunately the workaround for reinvoking the keyboard does not work on Hololens 1

**Comment by kevbarn** [comment]
Yes, unfortunately that workaround doesn't have the intended effect on HoloLens 1. Please open a new issue to track this and we can discuss options.
