### ISSUE TITLE
 import a dynamic 3D model in HoloLens

### ISSUE THREAD

**Issue by zhaobingshuai** [microsoft/MixedRealityToolkit-Unity#5170]
## Describe the Issue
A clear and concise what the issue

Hello, I want to import a dynamic 3D model in HoloLens. Do you have a recommended viewer app? In addition, how can I combine multiple static 3D models into a dynamic 3D model? For example, FBX format?
## Feature Area
What's incorrect? What's missing?

## Existing Doc Link
If this is about something in an existing document, please provide link

**Comment by wiwei** [comment]
I think that what you might be after here is the more general question of how you import a dynamic 3d model in unity - there's not really anything special here (i.e. if you can get it to work in Unity, you can deploy it to HL)

I'd recommend still sticking to going on the Unity forums themselves (or stackoverflow) to get an answer to this more general question
