### ISSUE TITLE
Robust Spectator View leveraging Azure Spatial Anchors for HL2

### ISSUE THREAD

**Issue by ALaurain** [microsoft/MixedRealityToolkit-Unity#5171]
## Describe the problem

Spectator View integration is one of the most frequent and essential feature request from clients. They want the ability to hold up a tablet, project to a TV or view from another HoloLens what a user is doing in real time. Any attempt to use the "pre-built" MRKT spectator view in the past has failed for various reasons, was full of bugs, or did not met the needs of our application. And now with UNET being deprecated, this feature is unusable as is. We had to write our own spectator view using UDP and TCP networking, and add capabilities as they are needed

## Describe the solution you'd like

A new Spectator View based on Azure Spatial Anchors for the HoloLens 2 seems like an essential feature. Using UDP and TCP, come up with a Spectator View that utilizes Azure Spatial Anchors instead of the iOS QR code reader (also very buggy and extremely time consuming to build out). This solution could then be adapted to work for any specific customer/user scenarios 

## Describe alternatives you've considered

As of right now, the only alternative is building your own Spectator View from scratch, or using an "out of the box" solution/package that you can download form the Unity store. These packages fit niche needs and don't cover all that you should be able to do with Spectator View

**Comment by Yoyozilla** [comment]
Please reopen your issue in our new spectator view GitHub Repo:
https://github.com/Microsoft/MixedReality-spectatorview

FYI this may already be available in their latest beta release
