### ISSUE TITLE
Null ref in MixedRealityServiceRegistry.TryGetService<IMixedRealityInputSystem>()

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5176]
## Steps to reproduce
1. Load the HandInteractionExamples scene
2. Hit play.

## Expected Behavior
I get no errors and can use hand simulation

## Actual Behavior
Get lots of errors like this:

NullReferenceException: Object reference not set to an instance of an object
Microsoft.MixedReality.Toolkit.UI.Interactable.ResolveInputAction (System.Int32 index) (at Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs:1071)
Microsoft.MixedReality.Toolkit.UI.Interactable.Awake () (at Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs:417)

Root cause is  MixedRealityServiceRegistry.TryGetService<IMixedRealityInputSystem>() is returning null

**Comment by julenka** [comment]
I need to leave early so handing off to will. What I've learned:

- Services seem to be correctly added to registry list
- In Interactable::Awake, when we call                     MixedRealityServiceRegistry.TryGetService<IMixedRealityInputSystem>(out inputSystem) the registry list length is zero. Seems unexpected.

**Comment by davidkline-ms** [comment]
depending on script execution order, it is possible for a service to not be registered when a component's awake method is called. i will look at the code for interactable.

**Comment by davidkline-ms** [comment]
Resolved by #5178
