### ISSUE TITLE
DefaultCursor clones are added on every inspection of MRTK profile options in play mode

### ISSUE THREAD

**Issue by googlan** [microsoft/MixedRealityToolkit-Unity#5188]
## Describe the bug

When looking into Mrtk profile options in play mode, every click in Profile options inspector window adds a clone of DefaultCursor under MixedRealityPlayspace. It might be one of visible consequences of a larger issue.

## To reproduce

1. Start play mode in any scene with Mrtk.
2. Select MixedRealityToolkit and go to 'Inspector'.
3. In profile settings select 'Input' (not specific to input, just easier to repro).
4. Start expanding-collapsing any settings group under it (e.g. Pointers).
5. See that every click adds a new cursor game object into scene hierarchy.

## Screenshots

![image](https://user-images.githubusercontent.com/5463350/60597562-07f15f80-9da3-11e9-9478-b3715affb36a.png)

## Your Setup (please complete the following information)

- Unity Version [e.g. 2019.1.8f1]

**Comment by Troy-Ferrell** [comment]
This sounds like it is similar to #4944 and was fixed by #4991 . I have pulled latest on mrtk_development and can't repro. @googlan can you pull latest and validate as well?

**Comment by googlan** [comment]
@Troy-Ferrell Sure, will do.

**Comment by googlan** [comment]
Doesn't repro on the latest mrtk_dev. Thanks @Troy-Ferrell .
