### ISSUE TITLE
HoloLens 2 - MRTK - Unity UI Interaction - direct manipulation doesn't work

### ISSUE THREAD

**Issue by vijang** [microsoft/MixedRealityToolkit-Unity#5190]
Description:

Direct manipulation of Unity UI Interaction in MRTK doesn't work.

1. Go to MRTK
2. Try far field (hand rays) interaction to manipulate Button, Toggle Button, Slide Bar and Drop down Menu. 
3. Confirm far field interaction works.
4. Try near field (direct manipulation) interactions to manipulate Button, Toggle Button, Slide Bar and Drop down Menu. 
5. Confirm near field interaction doesn't work.

 Setup 
- MRTK Version [2018.9.10.0]

Target Platform 
- HoloLens 2

**Comment by vijang** [comment]
could be related to https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3749

**Comment by wiwei** [comment]
@vijiang, can you see if this repros on latest mrtk_development? The MRTK version being used there is super old (i.e. 10 months now) and there's been significant churn since then.
