### ISSUE TITLE
InputHandler Breaking Change

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#5197]
## Describe the bug

It looks like PR #4970 added two abstract methods to [InputSystemGlobalHandlerListener](https://github.com/googlan/MixedRealityToolkit-Unity/blob/8b149581e86a7dc8e416ff41305e1c0b1b94273a/Assets/MixedRealityToolkit.Services/InputSystem/InputSystemGlobalHandlerListener.cs). These abstract methods are **RegisterHandlers** and **UnregisterHandlers**. This is a breaking change for anyone inheriting from **BaseInputHandler** or **InputSystemGlobalListener**.

In addition, **InputSystemGlobalListener** was marked Obsolete with a recommendation to use **InputSystemGlobalHandlerListener** instead.

## Recommended Fix

The following two documents need to be updated:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/InputEvents.html

and 

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/UpdatingToGA.html 

- InputEvents.html should clarify when to use BaseInputHandler vs. when to use InputSystemGlobalHandlerListener.

- InputEvents.html should document the pattern of the abstract Register and Unregister methods.

- UpdatingToGA.html should document the obsolescence of *InputSystemGlobalListener** and recommend **InputSystemGlobalHandlerListener** instead.

- UpdatingToGA.html should document the new abstract methods and route users to InputEvents.html for new guidance.

**Comment by googlan** [comment]
Done with #5224 .
