### ISSUE TITLE
BoundingBox toggleable collider

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5202]
## Describe the problem

It's not always desirable to active the BoundingBox via its own BoxCollider. Because of this collider any interaction is blocked for the actual target object, meaning:
- you can't click it
- you cannot let your gaze move across the actual surface

## Describe the solution you'd like

It should be possible to disable the BoundingBox collider in favor of the objects collider. The BoundingBox can be activated via its Active property.

## Describe alternatives you've considered

Adding the whole BoundingBox only at runtime. But that's unfeasible. the box initializes a few things in it's Start method, so if you want to for example set a different maximum scale, you need to yield for that to happen.

## Additional context

I am not entirely sure why the BoundingBox is so tightly coupled with their targets. The old toolkit created a BoundingBox that could be used with different object, depending on which one you chose it should operate on, or am I missing something here?

**Comment by Zee2** [comment]
MRTK3 can use the object's collider for BoundsControl.
