### ISSUE TITLE
Raycast Rubber effect

### ISSUE THREAD

**Issue by Tabularas** [microsoft/MixedRealityToolkit-Unity#5203]
Hello Folks,

We are currently producing some Training modules on Unity 2018.3.6f1 and are/where using Windows Mixed Reality toolkit v2.0.0-Beta 2.

We now wanted to upgrade to 2019.1.8f1 because of LWRP, ShaderGraph, VisualEffectsGraph, which would be very handy to create the upcoming modules.

Sadly, we found out that the current Version we were using from WMRT is not compatible with Unity 2019 so we had to upgrade to Version RC2.1. Sadly, this ment we had to rewrite our whole scripts.

My main question would be the Raycast(er) (if I’m naming it correctly). In the "old" beta 2.0 version it was a stiff ray that was coming out of the Gizmo but in the new RC2.1 version it has a new rubber band effect that’s not very effective. Because we need to drag and drop many objects in the scene/game, the feeling is somewhat flimsy and not very intuitive. It's like moving objects with a fishing rod.

Is there a way to change this behavior of the Raycast? Stiffen the raycast somehow?

It would be nice to add a variable of how stiffen the Raycast should be (e.g. 10 = hard, 1 = soft)

Thank you in advance

Beta 2.0
![image](https://user-images.githubusercontent.com/52523926/60646045-99f87700-9e3a-11e9-925c-9f35f7ef3c3b.png)

RC 2.1
![image](https://user-images.githubusercontent.com/52523926/60646096-b8f70900-9e3a-11e9-9980-4476edc4e1d0.png)

**Comment by wiwei** [comment]
@Tabularas, to clarify a bit, is this describing the curving that happens on the line when you say, grab a thing, move it over to the right or left, how the line will curve and then eventually snap back to being straight? Or are you seeing things be permanently curved?

**Comment by Tabularas** [comment]
@wiwei It is not directly the curving which is disturbing me, it's more that if you drag an object (which we had to do a lot in our project) the object is lagging behind the raycast position that came out of the origin. So placing an object exactly is hard because you have to drag the object more to on or the other side because of the lag. The curve from the Raycast is just showing the "lag". So it would be nice to change how fast/slow the object that you have selectet will be dragged/moved from the raycast.

I hope I could clarify my problem better :)

**Comment by Tabularas** [comment]
@wiwei I don't know if I explained my problem good enough. If you grab an object in  version v2.0.0-Beta 2 the object was directly moving with the raycast. No slow movement or curved Raycast because. The object was directly moving with the Raycast and the Raycast was just a straight line.

If you grab an object in Version RC2.1 the object has the impression kind of having now some weight to it. It is hard to move it sideways and even harder to move it towards you. It feels like handling a 
"fishing rod". It seems that in the current RC2.1 version all objects have some kind of weight to it when grabbet.


I'm uploading an GIF to visualize our problem better. 

**WMR v2.0.0-Beta 2**
![WMR_2 0 0_Beta_small](https://user-images.githubusercontent.com/52523926/61442443-e918ce80-a947-11e9-8dd6-228594df23e8.gif)

**WMR RC2.1**
![WMR_RC2 1_small](https://user-images.githubusercontent.com/52523926/61442471-fb930800-a947-11e9-9c51-5b2346152f20.gif)

**Comment by wiwei** [comment]
Ah, thanks for creating those clips! I'll need to do a little research here, but I think that this might be something you can do with some configuration.

If not, we should definitely make this an option for folks.

**Comment by Tabularas** [comment]
@Wiwei
Thank you for your answer. I just checked with our collegue and he had an additional "problem" that if an object is too far away it is very hard to drag the object close to you. This is also visible in the below clip. 

We searched on the ManipulationHandler script and it seems that the depth movement (towards you) is "just" working if you are close to an object.

**Comment by wiwei** [comment]
Alrighty, I got a chance to look into this one today - someone else on the team was actually hitting this a couple months back, but I don't think it was until today (with this video) that we had a good example of what was actually happening.

I just tried this out on the latest mrtk_development, and the issue doesn't repro for us anymore (i.e. other person tried out the same scenario that was exhibiting the issues you describe, and now the same repro steps weren't hitting that anymore.).

There is one thing to note - the bezier-curve based drag motion still exists (i.e. the pointer will still bend toward the object). Even if you did swap to perfectly straight lines (doing so is a bit complicated and I'll need to write docs on it, which involves editing the DefaultControllerPointer and removing the Bezier Line Data Provider and replacing it with a Simple Line Data Provider), you would still see some degree of lerping going on as the object is smoothed into its final location.

Assuming you're using the manipulation handler stuff here, you could disable that lerping stuff by unchecking this box:

![image](https://user-images.githubusercontent.com/5840182/61903078-8475ea80-aed8-11e9-8b3c-73cfb3d4c8b8.png)

I'm changing this to a doc bug to explain more about how the line pointers/renderers work - if you could help confirm that the latest doens't exhibit this issue for you, that would be extremely helpful

**Comment by wiwei** [comment]
@Tabularas meant to ping on the last response, lemme know!

**Comment by Tabularas** [comment]
@wiwei

I turned it off but the objects that are moved sideways and especially dragged from far away close to you are still lagging very much behind. :(

**Comment by wiwei** [comment]
@Tabularas, do you have a min repro that you can share out that exhibits this? We could take a closer look with that.

**Comment by Tabularas** [comment]
@wiwei how can I upload a testscene for this thread (890MB)??

**Comment by wiwei** [comment]
@Tabuluras If you have a onedrive/google drive/dropbox link you can share (maybe something that explodes in 7 days so that you don't have to keep it around forever) that would work.

Is there maybe something simpler (i.e. create a scene with object at 5 meters, attach X script to it, run in VR) that you find also hits this issue? Could save the hassle of uploading more stuff than you want :)

Also, reading through the message above I didn't see the explicit call out, but did you try out latest mrtk_development? Or did you primarily try turning off that smoothing active box? The box itself is additive on top of everything else done in mrtk_development, so if you're still using one of the currently released versions I would expect that you'd hit the same behavior.

**Comment by Tabularas** [comment]
@wiwei 
I just uploaded a "light" version of our application on my Gdrive account.

https://drive.google.com/open?id=1KXwG6zDhUwvJ8ldBIz2NmvjJchuBT3B6 which was the fastest solution in that time :)

No we are currently just using the v2.0.0 RC2.1 Package for unity (https://github.com/microsoft/MixedRealityToolkit-Unity/releases). And i did primarily turn off the smoothing active box, but I still had that "fishing rod" effect.

**Comment by flyingaudio** [comment]
HandInteractionExamples shows the same issue, where you pull the trigger with the pointer on any draggable object, and they lag behind, never catch-up to where the controller is pointing. Very noticeable if you rotate your wrist.  Add a cube to the screen, scale it down, add Manipulation Handler component, and it does the same thing. We abandoned development with it because of this issue, but we are revisiting it again. Unticking smoothing changed nothing.
This is with version Mixed Reality Toolkit 2.0.0-RC2.1.

Someone on StackOverFlow said they believe it works with the latest branch. I haven't tested yet.

The Microsoft MR Cliff House pointer works just right imo, a little lag, but always ends up straight out from the controller.

**Comment by flyingaudio** [comment]
@Tabularas @wiwei I just tried the latest development build https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/mrtk_development
and Will, you are right, it "fixes"??? the problem. 

1) Smoothing now works. It can be turned off and adjusted, but the line drawing seems to be low performance, the line can get jittery, depending how you move (this is on the lower/faster settings).
2) Pushing and pulling objects to and fro doesn't have enough distance change. Is there an adjustment for it?

You already have a **gold standard**; the **pointer in the Cliff House is silky smooth** (no jitter) and very responsive, and the push/pull curve/multiplier feels very good. It is finely tuned.  Please make mrtk work the same. You are close.

**Comment by Tabularas** [comment]
@flyingaudio

Agreed. The cliff house demo works very good. You can even pull/push object from very far away. Even the feature to see the battery level on the back is great but not available in mrtk (controller also missing)
