### ISSUE TITLE
MRTK adds several MixedRealityInputModule component to main camera

### ISSUE THREAD

**Issue by fcagnetta** [microsoft/MixedRealityToolkit-Unity#5204]
## Describe the bug

Scenario: I have 3 MixedRealityPlayspace object in the scene, but ONLY ONE active per time. Each of them has a Camera as a child in it. Each time I open the editor, I got an error saying "For Mixed Reality Toolkit input to work properly, please remove your other input module(s) and add a MixedRealityInputModule to your main camera." and I found multiple MixedRealityInputModule attached (instead of the only one I put) to the active Camera. I have then to manually remove them each time it happens.

## Expected behavior

MRTK to understand that a MixedRealityInputModule is already there.

## Screenshots

![image](https://user-images.githubusercontent.com/36179012/60650730-ffe9fc00-9e44-11e9-93c7-2ee84d22da69.png)

## Setup

- Unity Version 2018.3.12f1
- MRTK Version 2.0.0 RC1

## Target Platform
UWP:
- Desktop
- HoloLens
- HoloLens 2
- WMR immersive

**Comment by wiwei** [comment]
@fcagnetta, can you see if this still repros with the latest mrtk_development? RC1 was quite a while ago and we churned a bunch of things since then. Please reopen if it's still happening (along with a min-repro we can follow to hit the issue)
