### ISSUE TITLE
Normal Mouse Input

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5206]
## Describe the problem

I've tried to use the current MouseController but even though it's fancy and all, it's not as easy to use as the regular 2D mouse cursor. It's way too large when raycasting closeobjects, it's way too small in the distance, it's movement is angular based and different from how you configured your mouse to behave on your desktop.

## Describe the solution you'd like

An additional MouseController that is just the desktop mouse.

## Additional context

The current MouseDeviceManager implementation handles hiding the real cursor for the MouseController instead of letting it do so itself. The controller should know if he has its own appearance on screen or not.

**Comment by wiwei** [comment]
Closing this out, as the linked merged PR has gone in
