### ISSUE TITLE
HMD stuck at loading screen while playing in editor

### ISSUE THREAD

**Issue by Wolgraph** [microsoft/MixedRealityToolkit-Unity#5207]
Hi.
I'm working on a project where I can explore a museum hall and change light parameters via UI.
When I plug in HMD and controllers and Play the scene from Unity, the screen goes black to the loading scene, but even after the scene is completerly loaded, nothing happens withing the display, but those four loading dots.
I need to use HDRP, but VR doesn't work with no pipeline either.
Can you tell me if I just miss something or there is incompatibility I can't walk around?

Here my hardware and software:
Windows 10
intel i7-4510U
Nvidia GTX 850M
Unity 2018.4.3f1
High Definition Render Pipeline
Steam with Steam VR

**Comment by wiwei** [comment]
@Wolgraph, thanks for filing this issue! Reading through this I'm not sure if this is a Unity question, or a MRTK question. Do you have a specific MRTK version you're hitting? Are you having success with just the basic scenes?

If this is an MRTK question feel free to re-open with the version information specified in the bug template, if not, it might be better to ask this on stackoverflow or unity forums to maximize your changes at getting more eyes.
