### ISSUE TITLE
Hololens can´t connect to the SharingTest example scene

### ISSUE THREAD

**Issue by filipocasper** [microsoft/MixedRealityToolkit-Unity#5210]
The sharing service gets the following error when i boot my hololens through the sln file from my build and the hololens wont connect

Error : SharingService: Created Session "Default" with ID 0 on port 20601
SharingService: Created Session "DefaultSession" with ID 1 on port 20600
SharingService: User Test at address 127.0.0.1 joined session DefaultSession
SharingService: ListServer: Handshake failed with error 1

## To reproduce

1. install holoToolkit release
2. Open SharingTest example scene
3. Start SharingService.exe
4. Boot to hololens through sln file from your build

Expected behaviour : The "ManualIPConfigUtility" will show on my hololens that i am connected and the anchor text will say that it has successfully uploaded my anchor "worldstage" so that other hololenses can join my session

My setup:

- Unity Version  2017.2.5
- MixedRealityToolkit-Unity-htk_release

and Yes the firewall is not blocking any of the sharingservice and i have all the right capabilities 
thanks to @StephenHodgson youtube video "HoloToolkit for Unity Live Sream Tutorial Series 003"

**Comment by Yoyozilla** [comment]
Sharing for HL2 and Unity 2018 will be a standalone component in a separate repo. Please join the public sharing weekly shiproom for details

If you are using Unity 2017, the recommended version is 2017.3. 

We also recommend that you upgrade to MRTK v2 release for the latest updates :)
