### ISSUE TITLE
Write a test to ensure voice commands work in MRTK

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5216]
## Overview
This is a follow-up task for bug #5176, which was caused by a regression in PR  #5132. 

We should write a test to ensure that changes to MRTK do not break the ability to use voice commands.

The test would do the following:

- Run a scene that has MRTK, with default voice commands.
- Trigger a voice command that is registered in the voice commands list, such as "menu" or "select" (keyboard keys '1' and '2').
- Ensure that the voice command event gets raised.

Here is an example test:

- Create a gameobject, add a component that listens for voice commands, and simulate pressing the '1' key (in editor, pressing '1' simulates a voice command 'select'). Ensure that the component received the 'select' keyword.

In case simulating keyboard buttons is not possible in Unity, here is a second idea:

- In the voice data provider, throw an exception if voice system is not enabled, then in the test load up a scene and ensure no exceptions get thrown.

**Comment by julenka** [comment]
Hi David, it looks like the test added in PR #5230 doesn't actually fail when Speech is broken. Here's how I tested.

1. `git revert 3cb3c201ec8550b435cd8fc13a72bcd7b96c4994`
2. Load BoundingBoxRuntimeExample scene and verify that speech commands are not working (pressing "1" key doesn't actually trigger select
3. Run the Speech test, and see that the test passes.

**Comment by wiwei** [comment]
I think the revert mentioned above wasn't related to speech.

Nevertheless, removing this from GA because we added some coverage here (i..e assuming the event is fired, things work)

**Comment by julenka** [comment]
Re-opening as I believe this test was never written.
