### ISSUE TITLE
PressableButtonHololens2 is used in our example projects a lot and confuses users on other platforms.

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#5223]
## Describe the bug

PressableButtonHololens2 is for example integrated into Slate and is our default button for the example scenes. There's users working with Windows Mixed Reality Headsets / Hololens 1 and it's not clear to them if they should use these buttons and components. We should either rename that button or add some info about that in the documentation. (also state which features might not work if used on other platforms)

## Expected behavior

- we should only use components suitable for all supported platforms in our generic sample scenes. I would only expect platform specific components in a platform specific example scene.

## Your Setup (please complete the following information)

- MRTK Version v2 RC2.1

## Target Platform (please complete the following information)

- HoloLens
- WMR immersive
- OpenVR

**Comment by cre8ivepark** [comment]
It was renamed to differentiate from other generic buttons. I'll add more details to the docs.
Thanks!
