### ISSUE TITLE
How to connect HoloLens to server via TCP/IP?

### ISSUE THREAD

**Issue by haythem-bahri-github** [microsoft/MixedRealityToolkit-Unity#5225]
Hi guys,
I am a beginner in this field. I want to know there is a tutorial that explains to me, how can I connect HoloLens to a server on the network using TCP/IP to exchange data between them.
Thnx

**Comment by wiwei** [comment]
Hi there,

Thanks for posting your issue, and welcome to the MRTK!

We usually want to keep these issues associated with bugs, feature requests and doc questions - reading over this issue I see that it's a more general question about hololens development.

Doing networking stuff on a HL device should be the same as doing it on any other UWP platform (i.e. build the app, enable the networking capabilities).

Looking through some resources online, I see that @mtaulty wrote up this helpful piece:

https://mtaulty.com/2017/02/21/windows-10-uwp-hololens-a-simple-two-way-socket-library/

Which might give a good starting point for what you're going after.
