### ISSUE TITLE
Hand needs to be way too close to grabbable before hand ray disappears

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5240]
## Overview
The hand ray currently only turns off when the hand is incredibly close to a grabbable, when the hand is ~1cm near a grabbable. The ray should turn off when the hand is ~10cm near a grabbable.

This should be implemented by having a separate radius for turning off the line ray, separate from the radius that is used for doing a query for determining what to grab.

Currently, SpherePointer.IsNearObject contains the following:

```
return UnityEngine.Physics.CheckSphere(position, SphereCastRadius, ~UnityEngine.Physics.IgnoreRaycastLayer);
```

Instead of `SphereCastRadius` (used when determining grab start/edn), we should use a different radius `HandRayOffRadius`.

## Expected Behavior
The ray should turn off when hand is ~10cm near a grabbable
![image](https://user-images.githubusercontent.com/168492/60873303-2064ec80-a271-11e9-8c6a-66f69d218f65.png)

## Actual Behavior
Ray is still on, even when hand is very close to grabbable
![image](https://user-images.githubusercontent.com/168492/60873140-d24fe900-a270-11e9-8cb6-0066a3992c7a.png)

## Steps to reproduce
_(Links to sample github project preferred)_

**Comment by keveleigh** [comment]
There was originally a 0.05 buffer between the grab radius and the hand ray disappearing, but it looks like that was removed in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4974 via https://github.com/microsoft/MixedRealityToolkit-Unity/commit/b8160ca9de48c104f474b9d9141cda71a90a65c6#diff-2be5244793f0a456321d940ebafd4e55.

In addition, the grab radius was reduced to a third of its previous size in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4898.

Those two combined are likely contributing to this issue.

**Comment by lukastoenneMS** [comment]
Should this behavior actually be controlled by grabbables? Because it sounds to me like disabling the far interaction pointer should be a feature of that pointer, instead of relying on a large grabbable radius to disable a different kind of pointer. So

1. When line pointer hit is closer than X, the pointer is hidden and interaction disabled. Pointer keeps raycasting though, we want to un-hide when moving further away.
1. Grabbable distance is a separate issue, should the previous radius of 0.15 be restored? It does sound a little bit excessive and if it was just to hide the line pointer then the 1st point would take care of that.

**Comment by julenka** [comment]
>  Should this behavior actually be controlled by grabbables? Because it sounds to me like disabling the far interaction pointer should be a feature of that pointer, instead of relying on a large grabbable radius to disable a different kind of pointer. 

I don't fully understand the plan, but it could work, I don't have strong objections. Currently the far pointer [is disabled by the mediator](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/cfdf60e4471cc3a3ccd4b847449371dfa4ec94e8/Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/DefaultPointerMediator.cs#L135).

**Comment by julenka** [comment]
Assigned this issue to you Lukas in case you can help out, since I've got a bit too many bugs to finish before end of this week.

**Comment by julenka** [comment]
> Grabbable distance is a separate issue, should the previous radius of 0.15 be restored? It does sound a little bit excessive and if it was just to hide the line pointer then the 1st point would take care of that.

The grabbable radius should not go back to 0.15 -- that was too big and caused too much accidental grabbing. The current value is okay.
