### ISSUE TITLE
PointerClickHandler and PointerHandler are almost identical, very confusing

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5251]
## Overview
There are two scripts located under Assets\MixedRealityToolkit.SDK\Features\Input\Handlers which are nearly identical, `PointerHandler` and `PointerClickHandler`. We should depracate/delete the PointerClickHandler class to reduce confusion regarding which class to use.

We should remove PointerClickHandler in favor of PointerHandler for three reasons:

* Both classes expose Unity events for listening to pointer events (down, up, clicked, etc.), though only PointerHandler can be configured via code (PointerClickHandler requires setup in the designer because the InputActionEventPair fields in PointerClickHandler are private.
* PointerClickHandler naming is misleading -- the class responds to all input events, but the naming leads devs to believe it is only for click events.
* PointerClickHandler requires devs to specify an input action for every event, the default action is None. Several devs did not notice this input action field for the event handlers, and did not change it from "None". Unless the input action field is configured properly, the events will not respond to most inputs.

**Comment by julenka** [comment]
@luis-valverde-ms you know about pointer events -- do you have any context for why we have the duplicate? Or, suggestions on how to deprecate PointerClickHandler? My vote would be to just delete the file. @wiwei  is that appropriate to just delete the file PointerClickHandler?

**Comment by luis-valverde-ms** [comment]
I think I just left `PointerClickHandler` in when I introduced `PointerHandler` to avoid breaking existing code, but the latter should supersede the former.
