### ISSUE TITLE
GazeProvider GazeTarget returns null when articulated hands are up

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5252]
## Overview
Many customers use GazeProvider to know what user is looking at by examining where the head ray is pointing. For example, Experimental/Features/Utilities/StabilizationPlaneModifier.cs uses the GazeProvider to determine where to place the LSR stabilization plan for Hololens.

The `GazeProvider.GazeTarget` is filled in on startup, but then becomes null whenever articulated hands are present, even though Gazeprovider is enabled.

## Steps to reproduce
You can use the following class to print the gaze target 

```
using Microsoft.MixedReality.Toolkit;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GazeProviderDebug : MonoBehaviour
{
    // Update is called once per frame
    void Update()
    {
        var gp = MixedRealityToolkit.InputSystem.GazeProvider;
        //DebugInfo.Status($"gazeprovider enabled: {gp.Enabled} target: {gp.GazeTarget}");
        Debug.Log($"gazeprovider enabled: {gp.Enabled} target: {gp.GazeTarget}");
    }
}

```
2. Place a cube at 0, 0, 3, attach the GazeProviderDebug script to the cube.
3. Press play, look at console, notice the following messages:

gazeprovider enabled: True target: Cube (UnityEngine.GameObject)

4. Bring up articulated hand, look at console, notice messages

gazeprovider enabled: True target: 

## Expected Behavior
Even when the articulated hands are up, the console output should read:

gazeprovider enabled: True target: Cube (UnityEngine.GameObject)

**Comment by julenka** [comment]
This is a tricky one -- I briefly looked into it but didn't quickly find solution (spent ~5 minutes on it). Can somebody with knowledge of gaze provider and input provide thoughts on how to fix / hints for where to look? @luis-valverde-ms or @keveleigh  know the most, @googlan  also knows about input and could help.

**Comment by wiwei** [comment]
This could be a side effect of how the whole hands/eyes interactions aren't reallllllly specified and are still being figured out.

I haven't looked at this myself, but this could fall into two buckets:

1) An obvious bug which we just fix.
2) Another instance of the fact that we haven't really figured out the perfect set of hand/eye interaction models, and we'd be doing some hack or workaround that doesn't necessarily create additional clarity.

I hope it's #1

**Comment by keveleigh** [comment]
My guess is it's a side effect of disabling the gaze pointer:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/3f8a2c6fa1c6d5600dd3614bcec2a11661158a35/Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs#L999

since we don't attempt to raycast, etc if interaction is disabled:

**Comment by luis-valverde-ms** [comment]
+1 to what Kurtis said

**Comment by julenka** [comment]
merged.
