### ISSUE TITLE
Create a toggle pressable button prefab for HoloLens 2

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5254]
## Overview
A few people have asked how to implement a pressable button with a toggle state. We should make a prefab that people can use that's a toggle version of HoloLens2PressableButton.

* The button would be similar to HoloLens2PressableButton, but with toggle functionality on Interactable enabled. 
* The button should also visually change state when the toggle button is disabled

**Comment by Troy-Ferrell** [comment]
@cre8ivepark & @killerantz  FYI

There is PR #5069 out still which would be directly impact to this bug. Also there is "InteractableExamples.scene" as well as a "HolographicButtonToggle" prefab in MRTK. Maybe it needs to be updated to match Hololens2PressableButton? @julenka

**Comment by julenka** [comment]
Just merged that PR in!

**Comment by cre8ivepark** [comment]
Added HoloLens 2 shell-parity toggle button prefab:
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5457

**Comment by julenka** [comment]
Fixed.
