### ISSUE TITLE
Is unity getting support for passthrough from tracking cameras?

### ISSUE THREAD

**Issue by TheBricktop** [microsoft/MixedRealityToolkit-Unity#5262]
Since newest update we can use flashlight in WMR immersive headsets
Could we in some future acces the same cameras through api in unity?
It would really justify using "mixed reality" in the name of this line of products.

**Comment by wiwei** [comment]
Reading through this, it sounds like this would probably be better asked on the Unity forums, so that this has the highest chance of getting someone from Unity to look at it.

**Comment by wiwei** [comment]
We usually keep the issues here scoped to the MRTK itself - for Unity questions like this definitely going to Unity forums is the way to go
