### ISSUE TITLE
Interactable not working past 10 meters

### ISSUE THREAD

**Issue by derekfreed** [microsoft/MixedRealityToolkit-Unity#5269]
## Describe the bug

I am unable to interact with an interactable past 10 meters even with the camera raycast limit distance enlarged

## To reproduce

Try to interact with a basic interactable past 10 meters

## Expected behavior

Should be able to interact past 10 meters

## Your Setup (please complete the following information)

- Unity Version 2018.3.13f1
- MRTK Version v2.0

## Target Platform (please complete the following information)

- HoloLens

**Comment by wiwei** [comment]
@keveleigh IIRC our default raycast limits at 10 meters, but I think that this is changeable. 

@keveleigh do you know if that number was set to 10 due to some perf reasons, or because that was the limit of when it became less ... "interactable" (i.e. the jitter from hand rays or ability to stabilize on gaze was too low?)

**Comment by derekfreed** [comment]
I also made sure to change the camera's raycast limit

**Comment by Yoyozilla** [comment]
@julenka  Do you know why we have the default raycast stop at 10m?

**Comment by derekfreed** [comment]
is there somewhere where I can change the default raycast? I haven't been able to find where this is being set. I would have thought it'd be the raycast limit on the camera

**Comment by julenka** [comment]
> @julenka Do you know why we have the default raycast stop at 10m?

It's to match shell behavior, which I think is actually even less than 10 m.

You can change the default raycast by modifying your pointer prefab. If you are using the default rays, that would be in DefaultControllerPointer:

![image](https://user-images.githubusercontent.com/168492/61828387-68604380-ae1b-11e9-9923-cfc0689d6b65.png)

**Comment by wiwei** [comment]
Changing this to a doc bug, because we should be able to show people how to change this without having to file an issue.
