### ISSUE TITLE
link.xml generator

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#5273]
Something that we've found happen when consuming via NuGet (compiled binaries) or UPM (source) is that a lot of our components are getting optimized out in IL2CPP bytecode stripping:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4265

Basically, because of how we do psuedo-injection via the configuration in our profiles, and because the types contained within those profiles aren't actually directly GUID or asset references (they are instead SystemType references which basically just two strings, one of which is the type name, one of which is the assembly), when IL2CPP bytecode stripping comes into play, it optimize away some relatively critical parts of the system like:

1) Key parts of the the input system
2) Boundary/Spatial/Diagnostic (and other systems).

The exact things that get stripped away depend on the consumption mechanism and the agressiveness of the bytecode stripping setting.

In order to make these basic scenarios work, we're going to add a link.xml to the root Asset folder which will ensure that those core systems can get generated.

Note that this isn't EXACTLY optimal because certain customers might actually want some of these things to be stripped away (for example, if you don't ever plan on having the spatial system or boundary system turned on, optimizing them away is actually fine). To this, one of the things we can do is write up a Utility (in the MRTK tooling window) that will look at your current profile to generate the appropriate link.xml file that you can include to ensure a minimal set of lines in link.xml (and thus the minimal set of things that get included)

Until then, for people who want to build and don't ever plan on having the teleportation of boundary system enabled, for example, can modify the link.xml file to look like:

```
<linker>
  <assembly fullname="Microsoft.MixedReality.Toolkit" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Providers.WindowsVoiceInput" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Providers.OpenVR" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.SDK" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Services.InputSystem" preserve="all"/>
  REMOVE THIS LINE: <assembly fullname="Microsoft.MixedReality.Toolkit.Services.BoundarySystem" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Services.CameraSystem" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Services.DiagnosticsSystem" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Services.SceneSystem" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Services.SpatialAwarenessSystem" preserve="all"/>
  REMOVE THIS LINE: <assembly fullname="Microsoft.MixedReality.Toolkit.Services.TeleportSystem" preserve="all"/>
</linker>
```

**Comment by TautvydasZilys** [comment]
Note that blanket preserving assemblies like that will lead to significantly increased build times with IL2CPP. Stripping code makes building faster - that's one of the reasons you cannot disable stripping for IL2CPP.

**Comment by wiwei** [comment]
@TautvydasZilys yep, note that we aren't shipping this out with the .unitypackage, only the scenarios in which they are known to hit (i.e. NuGet/UPM).

**Comment by keveleigh** [comment]
From @davidkline-ms https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9112#issuecomment-757076768:

>we probably need an issue to support updating the link.xml file if it exists, so that we can handle new packages in the future

Though, I think we need to take a different approach. As commented above, blanket link.xml files significantly increase build times. We should investigate using [Unity's `Preserve` attribute](https://docs.unity3d.com/ScriptReference/Scripting.PreserveAttribute.html) on the specific classes we need to stick around.

**Comment by davidkline-ms** [comment]
this shipped in 2.5

**Comment by Zylvian** [comment]
Hi.

This error is still persistent for me with the 22.03.22 MRTK build. The error is present over all forms of deployment: holographic remoting, debugging through VSC, and full deployment.

![image](https://user-images.githubusercontent.com/33404765/159855002-0811f172-042d-42eb-af89-5ae9e3e14a7c.png)

The link.xml file is stored in the allocated MixedRealityToolKit.Generated folder, with the default contents:

![image](https://user-images.githubusercontent.com/33404765/159855208-e2c1b4a9-c2ef-4d5e-beca-e7c25ea4e1c9.png)

I am using the standard build settings from the documentation:

![image](https://user-images.githubusercontent.com/33404765/159855336-71d294bd-e73f-45f6-82d3-1244548281ff.png)


If there is any pointers you might have, please let me know.

**Comment by keveleigh** [comment]
Which version of Unity are you using, which profile are you using, and is anything not working for you? In certain versions of Unity (mostly 2020+) with certain profiles, you'll get those logs, but they're benign and shouldn't prevent anything from working assuming your profile has data providers for the platform you're running on.

**Comment by Zylvian** [comment]
> @Zylvian, which version of Unity are you using, which profile are you using, and is anything not working for you? In certain versions of Unity (mostly 2020+) with certain profiles, you'll get those logs, but they're benign and shouldn't prevent anything from working assuming your profile has data providers for the platform you're running on.

I'm using the documentation-suggested 2020.3 version. I'm using the default HoloLens 2 spatial mapping profile, have tried messing with different providers but they get stripped and refuses to work nonetheless. For some reason, I have a single 3-day build that correctly imports the system, but any new builds refuse to work correctly. It's not just the logs, the functionality is completely absent. 
In regards to platform, it's as shown UWP ARM64 for the actual HoloLens2.

Do you have any ideas if any settings might be incorrect or any ideas? Not being able to incorporate AR into my app is quite limiting.

**Comment by Zylvian** [comment]
Don't usually do issues so here's a @keveleigh for good measure.
