### ISSUE TITLE
provide example for how to do video and photo capture in mrtk

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5276]
## Overview
A customer is having trouble doing video capture on HoloLens. They were looking for code to copy. It would be nice to provide an example for how to do photo and video capture in the MRTK examples package.

**Comment by Troy-Ferrell** [comment]
@julenka I would be wary of creating too much. There is already existing documentation with pretty good amount of how-to code:
https://docs.microsoft.com/en-us/windows/mixed-reality/locatable-camera-in-unity
https://docs.microsoft.com/en-us/windows/mixed-reality/locatable-camera
https://docs.unity3d.com/Manual/windowsholographic-photocapture.html
https://docs.unity3d.com/Manual/windowsholographic-videocapture.html

I think it would be more interesting to have an example of how to use an opencv plugin in Unity/HL. That is much harder to accomplish to create one's own native plugin and then ingest properly with Unity. We have this example but it hasn't been updated for HL2:
https://github.com/microsoft/MixedRealityCompanionKit/tree/master/PosterCalibrationSample

**Comment by Yoyozilla** [comment]
I think this would be a good candidate for community member if they are interested.

**Comment by wiwei** [comment]
Actually closing this one out - I agree with @Troy-Ferrell in that we shouldn't duplicate efforts here in terms of doing video/photo capture (i.e. if I google "unity hololens video capture" it literally brings you to a unity page that tells you how to do it).
