### ISSUE TITLE
MixedRealityToolkit object spawns duplicate object

### ISSUE THREAD

**Issue by maluoi** [microsoft/MixedRealityToolkit-Unity#5277]
## Describe the bug

MRTK spawns a duplicate MixedRealityPlayspace object in the editor when disabled, if it's selected in the inspector during runtime. It also automatically re-enables the MixedRealityToolkit object.

## To reproduce

-Create an empty scene
-Mixed Reality Toolkit->Add to Scene and Configure
-Disable MixedRealityToolkit and MixedRealityPlayspace objects
-Hit Play
-Select the disabled MixedRealityToolkit object
-Unity spawns new MixedRealityPlayspace and MixedRealityToolkit enables itself

## Expected behavior

Nothing should happen

## Setup

Unity 2018.4
MRTK v2.0.0.RC.2.1

**Comment by wiwei** [comment]
@Railboy
