### ISSUE TITLE
Add iOS to SupportedPlatforms

### ISSUE THREAD

**Issue by camnewnham** [microsoft/MixedRealityToolkit-Unity#5278]
## Describe the problem

The InputSystem fails to start when running on iOS.  This appears to be because it is not listed as a supported platform for the InputSystem.

## Describe the solution you'd like

Having iOS listed as a supported platform. In my testing the only change that is required is to add it to the SupportedPlatforms.cs enum and add the filters in PlatformUtility.cs

## Describe alternatives you've considered

I modified the above files and builds work successfully. https://gist.github.com/camnewnham/5742fd877bc48f612da6b6429610162a

## Additional context

Making this changes results in an app that runs the same on iOS and Android, which is great!

An aside: When I need to make changes to the core MRTK files to support our specific development requirements, is the best way to do this by creating a git fork inside the the Assets folder? At the moment I've installed via the UnityPackage which means updating the MRTK will be a headache to reconcile my changes.

**Comment by Alexees** [comment]
Just wanted to link #4235 as an alternative for a mechanism that lets people define any kind of platform specific, even within a platform

**Comment by keveleigh** [comment]
iOS was added to SupportedPlatforms in the dev branch via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4691. Looks like this didn't make it into RC2, but will be in the GA release.
