### ISSUE TITLE
Remove unused materials

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#5279]
## Describe the bug

Remove un-used assets thanks to #5096 , focused mostly on eyetracking sample

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by wiwei** [comment]
Closing this one out, as the linked PR was merged. Feel free to reopen if there are other specific assets that you want to remove and such.
