### ISSUE TITLE
Create a basic way to get the eye gaze ray, hand ray, head ray, and controller ray

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5280]
## Overview
MRTK should have a way to get the eye, head, hand rays in basically one line of code, something like:

PointerUtils.TryGetEyeRay()
PointerUtils.TryGetHandRay(Handedness h)
PointerUtils.TryGetMotionControllerRay(Handedness h)

We can also have TryGet* versions of these functions.

**Comment by julenka** [comment]
@Yoyozilla FYI

**Comment by davidkline-ms** [comment]
i have a basic design for the helpers. there are some implementation details being worked out and tests to perform / write

**Comment by julenka** [comment]
Taking this bug over since David is going on holiday. Thank you very much for the help, David!
