### ISSUE TITLE
IMixedRealityTeleportHandler not working

### ISSUE THREAD

**Issue by pocce90** [microsoft/MixedRealityToolkit-Unity#5282]
## Describe the bug
Trying implementing the interface "IMixedRealityTeleportHandler" in a script attached on a gameObject. When I teleport myself, the system never enter inside the implemented interface methods

## To reproduce
- implement IMixedRealityTeleportHandler interface in a script
- attach the script on something in the scene
- try to teleport

## Expected behavior

The system executes the code inside the implemented methods

## Your Setup (please complete the following information)

- Unity Version 2018.3.12
- MRTK Version 2.1

## Target Platform (please complete the following information)

- WMR immersive

**Comment by keveleigh** [comment]
You'll need to register as a listener of the teleport system. An example of how to do this (with the spatial awareness system, though the pattern should be the same) can be found at and around https://github.com/microsoft/MixedRealityToolkit-Unity/blob/5c172ecc4eb92fbd41924547ad0e654798e21e4e/Assets/MixedRealityToolkit.Examples/Demos/SpatialAwareness/Scripts/DemoSpatialMeshHandler.cs#L39

I'm also looking into an abstract class to abstract away much of this common code and make registering more straightforward.

**Comment by wiwei** [comment]
Changing this one to a doc bug
