### ISSUE TITLE
Null exception when MRTK v2 tries to create a controller model

### ISSUE THREAD

**Issue by davidmurray** [microsoft/MixedRealityToolkit-Unity#5287]
## Describe the bug

Crash happens when MRTK v2 tries to create a controller model.

## To reproduce
Usually clicking with the clicker triggers this, but recently it's been happening without me sending any inputs (just having HoloLens on my head and not moving. The crash happens after a few seconds)

## Expected behavior

No crash

## Screenshots

![crash](https://user-images.githubusercontent.com/545502/61079848-bc1d6680-a3f1-11e9-9bab-8e2cd0ebc6d8.png)

## Your Setup (please complete the following information)

- Unity Version 2018.4.3f1 Personal
- MRTK Version v2.0.0 RC2.1
- VS 2017, 15.9.13

## Target Platform (please complete the following information)

- HoloLens 1

Thanks

**Comment by keveleigh** [comment]
>Usually clicking with the clicker triggers this

Does this specifically repro when the clicker is attached?

**Comment by davidmurray** [comment]
@keveleigh Yes, but sometimes it takes a few clicks to work. That is, I'll be able to click with the clicker once and then on the second click the app will hang for 2 seconds and then crash (for example).

**Comment by wiwei** [comment]
Let's get this fixed soon, we shouldn't be having crashes as an obvious rule.

**Comment by davidmurray** [comment]
Update: this seems to happen without me clicking at all or doing the air tap gesture.

**Comment by keveleigh** [comment]
Fixed via #5402.
