### ISSUE TITLE
Additive Lit Materials Do Not Get Clipped Properly by Clipping Primitives

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#5290]
## Describe the bug

Additive materials which are lit do not get clipped properly by Clipping Primitives (plane, sphere, box). The lit pixels are still visible.

## To reproduce

1. Add a renderer to the scene that uses the MRTK/Standard material that is both additive and lit.
2. Add a clipping primitive to the same scene.
3. Add the renderer to the "Renderers" property of the clipping primitive
4. Notice the renderer does not get clipped completely on the lit portions.

## Expected behavior

All pixels are clipped by the clipping primitive.

**Comment by Troy-Ferrell** [comment]
@Cameron-Micka fixed?

**Comment by Cameron-Micka** [comment]
Yep fixed!
