### ISSUE TITLE
Multi-scene switch with MRTK UI buttons not supported

### ISSUE THREAD

**Issue by khaleepha007** [microsoft/MixedRealityToolkit-Unity#5293]
## Describe the bug
I have three scenes each with their MRTK instance and camera ,
- Home scene has no 3d objects .it is just the start menu scene,  

- Pre-operative scene has complex 3d objects with animations, soft body simulation , box collider ,mesh collider components,  also MRTK manipulative, interactive components 

-Intra-operative scene has a 3d object with MRTK manipulative, interactive components .

Furthermore ,the Home scene has two MRTK buttons ,the pre-operative and intra-operative buttons which are meant to switch to other scenes  respectively when buttons are air tapped. For the  pre-operative scene it has only button ,this is also the same for intra-operative scene and when each the button is air tapped the scene is meant to switch back to home scene. But when I run it and air tap any of the buttons in any of the scene via the Hololens it just hangs and it stops working. I am using the scene manger and this code can be seen below

`public void SceneSwitcher : MonoBehaviour
{

     public void SceneLoader(int SceneIndex)
   {
   SceneManager.LoadScene(SceneIndex);
   }
}`

I know there has been a proposed solution for working with multiple scene switching with MRTK . This solution is to additive load a base scene then additively load and unload the other scenes but I will never unload the base.Also the base scene will be the only scene to contain the MRTK instance and camera. That's the much I can understand from the discussion I have been coming across.My question how use this additive load and unload work for my case.
## To reproduce

 just create 3 scenes each with their own MRTK instance and camera.
- scene 1 should have two buttons ,which are scene 2 button and scene scene 3 button.
- scene 2 should have 3d objects with animations and MRTK manipulative and interactive components but it should only have one button which is the scene 1 button.
- scene 3 should also have sd objects with animations and MRTK manipulative and interactive components but it should only have one button which is the scene 1 button(1).

Then create an empty game object and each the script above to it. Next place this game object at each of the scene. Now at each of the scene select the button under the OnClick event drag and that game object and then choose the Sceneswitch(int) function ,then enter the 1 of the scene that button is meant to switch to when clicked.Do the same for the rest of the buttons.

After go build setting and simply drag and drop the scene in order.

## Expected behavior
The scene should switch when the buttons are air tapped

## Your Setup (please complete the following information)

- Unity Version  2018.3
- MRTK Version . v2.0

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by khaleepha007** [comment]
@Railboy

**Comment by Railboy** [comment]
@khaleepha007 Thanks for the detailed write-up.

>My question how use this additive load and unload work for my case.

I recommend that you check out our [scene loading example](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4919) using the eye tracking demo. It's still in progress but it demonstrates the basics of setting up a manager scene and content scenes, as well as how to use buttons to switch between scenes. If I understand your write-up correctly the eye tracking demo closely matches what you're trying to do.

Also take a look at our scene system [documentation](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SceneSystem/SceneSystemGettingStarted.html) as you poke around.
