### ISSUE TITLE
Remove unused MRTK assets

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5296]
## Overview
There are several large assets that are not used anywhere in MRTK. Delete them. We can use the new Dependency window #5096 to quickly find unused assets.

**Comment by wiwei** [comment]
Related to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5279

**Comment by wiwei** [comment]
I should call out, the dependency window is a useful tool but not all of those assets on there actually can be safely deleted. For example, csc.xml and link.xml are important to leave there (otherwise we lose warnings-as-errors and IL2CPP bytecode stripping protection)

**Comment by wiwei** [comment]
Looking through more, there are plenty of other ones there that also would be bad if we removed, so we should really, really be careful about actions we take here.

**Comment by wiwei** [comment]
Closing this out to reduce the number of non-specific issues (i.e. it's not clear exactly what needs to be updated here and what can be done safely)
