### ISSUE TITLE
Export Remote Spatial Mesh from Device to Unity Editor?

### ISSUE THREAD

**Issue by gkh38** [Microsoft/MixedRealityToolkit-Unity#530]
When I save WorldAnchors using the WorldAnchorManager, is there a way to export the saved WorldAnchors to the UnityEditor? (So I can view the Anchors in the Editor, not in runtime) Or can I get the positional data relative to the SpatialMapping? I'm already using the Remote Mapping Manager, but can't figure out how to send the WorldAnchors as well.

**Comment by HodgsonSDAS** [comment]
No, you cannot use world anchors in the editor. Although, you can create fake data to send as a test.
See [RoomTest.cs](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Sharing/Tests/Scripts/RoomTest.cs#L27) for an example of fake anchor data.

**Comment by HodgsonSDAS** [comment]
My latest PR https://github.com/Microsoft/HoloToolkit-Unity/pull/513 for the Sharing Service pretty much makes it easier to work with Devices and users in Editor over the sharing service.

**Comment by gkh38** [comment]
I mainly want to use the positions of the WorldAnchors in the downloaded SpatialMesh, is that possible? From what I understand, simply taking the xyz values won't cut it, right?

**Comment by HodgsonSDAS** [comment]
Take a look at the RemoteMapping test scene. I'm unsure if it works in editor (because there's no way to grab the `WorldAnchorStore`) but there might be a way to load in the mesh using `RemoteMeshSource` and `RemoteMappingManager`.

**Comment by gkh38** [comment]
Instead of saving the WorldAnchor positions I create a prefab on the place where I placed the WorldAnchor. When I stream the meshes to Unity using the RemoteMappingManager they show up in my Beamed files, but as soon as I save it, it doesn't show up in the .room file. Any tips on how to handle this? (Add prefabs to meshes)

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
