### ISSUE TITLE
MRTK tests documentation is hard to find on bing and google

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5317]
## Overview
The following [bing query](https://www.bing.com/search?q=mrtk+tests&form=WNSGPH&qs=SW&cvid=89cb823109e44107a7a725be2d4091d6&pq=mrtk+tests&cc=US&setlang=en-US&nclid=749F70F130801DE116EE8D6C9A5B5051&ts=1563235959490&wsso=Moderate) does not point to the mrtk tests page on github and neither does this [google query ](https://www.google.com/search?q=mrtk+tests)

This task covers asking Google to re-index our site as well as adding common keywords to docs so that the page is easier to find.

**Comment by wiwei** [comment]
After @thalbern re-requested indexing, this has gotten a lot better. (i.e. for both, mrtk tests is now the first thing)

We can open a new doc bug if there are additional keywords that should be leading users here - note that we should be wary of spending too much time doing SEO stuff, as that's not where we will give consumers the most value.
