### ISSUE TITLE
MRTK Gizmo icons are large and get in the way of viewing the scene

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5323]
## Overview
![image](https://user-images.githubusercontent.com/168492/61274215-2d497a80-a760-11e9-8575-9f7ff53ba827.png)

By default, MRTK Icons in Unity Editor Gizmo are visible and are in a large size. This gets in the way of viewing the scene in editor. In fact, people have shared [workarounds like this](https://twitter.com/Saelia/status/1148794572509573121)

It would be nice if we could remove the icons from the MRTK scripts.

**Comment by timGerken** [comment]
Hopefully it can be done in a way that leaves the icons on the scripts in the inspector (super useful in differentiating MRTK from app scripts).

**Comment by Railboy** [comment]
My preference would be to remove icons altogether. If we do keep them we should adjust them automatically. In the MRDL we wrote a script that scaled icons on startup to a reasonable size.

**Comment by wiwei** [comment]
Yeah, honestly I've heard other feedback that the icons are confusing to people - why does the MRTK have its own csharp file icon, for example?

**Comment by keveleigh** [comment]
Fixed via #5646
