### ISSUE TITLE
ManipulationHandler -> OnHoverExited "crashes" the pointer (in editor)

### ISSUE THREAD

**Issue by KarlSupertramp** [microsoft/MixedRealityToolkit-Unity#5326]
## Describe the bug
I wired a method (toggle UI elements) to HoverEnter & HoverExit. Now if I aim the hand ray on the object OnHoverEnter correctly enables my UI. But when I stop aiming at the object, my hand ray vanishes. After that, I can't use my hand ray anymore. It only works again, when I use near interaction. 
Everything seems to work on HoloLens 1 (release build), but it still looks glitchy sometimes. HoverExit seems to interfear with the pointers raycast in a strange unexpected way.

## Expected behavior
Call the methods wired to HoverEnter & HoverExit without breaking my pointer

## Your Setup (please complete the following information)

- Unity Version  2018.4.2f1]
- MRTK v2.0.0 RC2.1

## Target Platform (please complete the following information)
- HoloLens
- Unity Editor

**Comment by wiwei** [comment]
@thalbern, have you ever seen anything like this before? I just tried this out on both latest mrtk_development and also on RC2.1 and wasn't able to repro this with a really simple scene that looks like:

1) A cube with a manip handler that had On Hover Exited.
2) It calls a script that looks like:

```csharp
public class HoverHandler : MonoBehaviour
{
    public void OnHoverEntered(ManipulationEventData manipulationEventData)
    {
        Debug.Log("Hover entered");
    }

    public void OnHoverExited(ManipulationEventData manipulationEventData)
    {
        Debug.Log("Hover exited");
    }
}

```

@KarlSupertramp do you have any other details on any other interesting things happening in OnHoverExit that might be leading to this, or otherwise have a min repro scene/project that we can take a look at?

**Comment by KarlSupertramp** [comment]
This...

` public void ToggleCloseButtonOnGaze(bool active) {
            if (closeButton != null) {
                closeButton.transform.DOKill();
                if (active)
                {
                    closeButton.transform.DOScale(1, .5f);
                }
                else {
                    closeButton.transform.DOScale(0, .5f).SetDelay(1);
                }
            }
        }`

... is the method, that's called by the HoverEvents. I'm using the DOTween Plugin for smooth tweening transitions. I doubt that it has anythig to do with DOTween, but my pointer disappears after  the DOScale() coroutine is done. Like I said, it's a strange bug.

**Comment by KarlSupertramp** [comment]
Ok, I tried it with just a Debug.Log() and It works like expected. Maybe OnHoverExit doesn't like DOTween after all.

**Comment by KarlSupertramp** [comment]
Update: It works when I disable the NearInteractionTouchable component

**Comment by wiwei** [comment]
Sweet, I'll take a look at this next up

**Comment by wiwei** [comment]
Ah, I misread the previous part - @KarlSupertramp,is that last image you shared slightly cutoff (i.e. is it supposed to Manipulation Handler as one of the components on the object?)

To help reduce a little back and forth, maybe do you have a basic scene (i.e. single button) that you could share out that happens to repro this?

**Comment by wiwei** [comment]
Removed the label while we wait for more information

**Comment by KarlSupertramp** [comment]
I can't share any actual code/project files, I'm sorry. But to repo this, just create a button with the compontents shown on the picture:

![](https://user-images.githubusercontent.com/12151775/61447121-a3accf00-a950-11e9-8baf-89319a62368e.PNG)

My pointer always breaks, if I set the scale of the whole GameObject to 0. 
This does not happen, when disalbe the NearInteractionTouchable.
