### ISSUE TITLE
A Handful of Icons Do Not Depth Test

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#5329]
## Describe the bug

A handful of icons are using the GUI/Text Shader which does not depth test which results in the icons drawing though objects.

I would recommend switching the materials of those icons to use the MRTK/Standard shader then switching the Rendering Mode on the material to "TransparentCutout."

## To reproduce

1. Open the HandInteractionsExample scene.
2. Look at the ToggleFeaturesPanel from the back
3. Notice icons drawing though the back panel.

## Expected behavior

3D objects should respect depth.

## Screenshots

![image](https://user-images.githubusercontent.com/13305729/61334808-fca92580-a7df-11e9-868d-89036a2c5e9c.png)

## Your Setup (please complete the following information)
- mrtk_development

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by julenka** [comment]
@Cameron-Micka  and @cre8ivepark  this is marked for our next iteration. Could you please assign/follow up?

**Comment by Cameron-Micka** [comment]
I fixed this in this PR: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5522 please let me know if any other icons exhibit this behavior!
