### ISSUE TITLE
BaseInputHandler Update is not protected virtual

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#5331]
## Describe the bug

Several major changes were made to BaseInputHandler and related classes in #5197. In this update it appears an `Update` method was added which calls `RegisterHandlers `and `UnregisterHandlers`. Unfortunately, this `Update` method is not virtual, which means it cannot be overridden. If any class which inherits from BaseInputHandler and adds their own `Update` method it will effectively disable the `Update` that sits within BaseInputHandler. The end effect is that handlers will no longer be registered or unregistered.

## Expected behavior

BaseInputHandler.Update needs to be made `protected virtual`.

**Comment by googlan** [comment]
This was a serious mistake, thank you for highlighting it! Should be fixed now.

**Comment by jbienzms** [comment]
Awesome, thank you for getting that addressed so quickly!
