### ISSUE TITLE
Gesture Events registered twice

### ISSUE THREAD

**Issue by michel-de-verdelhan** [microsoft/MixedRealityToolkit-Unity#5337]
## Describe the bug

I have Gesture Handler's callback functions which are called twice in the same frame. This bug appear because WindowsMixedRealityDeviceManager.RegisterGestureEvents is called twice at startup, so the callback events are registered twice.

## To reproduce

Create new project on Unity (tested on 2018.4.3f1) and import MRTK package (tested with MRTK v2.0 RC 2.1)
* setup the scene using menu "Mixed Reality Toolkit=>Add To Scene And Configure"
* choose DefaultMixedRealityToolkitConfigurationProfile as profile
* setup project build parameters to Hololens
* use .Net scripting backend
* build project
* Set build solution to debug configuration and put a breakpoint at the start of WindowsMixedRealityDeviceManager.RegisterGestureEvents() function (optionaly, also put a breakpoint on UnregisterGestureEvents() to test unregistration)
* launch application

=> the breakpoint in WindowsMixedRealityDeviceManager.RegisterGestureEvents() is hit twice

this appear because when the Toolkit call EnableAllServices, it enable the MixedRealityInputSystem, this class register the InputDeviceManager service (which call Enable on the service), and just after, EnableAllServices also call Enable on all registered services.

## Expected behavior

only one call to WindowsMixedRealityDeviceManager.RegisterGestureEvents() when starting the application

## Your Setup

- Unity Version 2018.4.3f1
- MRTK Version v2.0 RC 2.1

## Target Platform

- HoloLens
- HoloLens 2 (when available)

**Comment by Alexees** [comment]
This was fixed by #4832 and is available in the currrent mrtk_development branch

**Comment by wiwei** [comment]
Please grab latest mrtk_development, if you still see this please reopen and ping me.
