### ISSUE TITLE
UnityTouchDeviceManager does not raise InputActionEvents

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#5342]
## Describe the bug

In #4006 we introduced the ability for Input Actions to be handled in a source-agnostic way. This allows an application developer to handle Input Actions in a single handler regardless of whether the action was triggered by Voice, Controller, Hands, etc.

The TouchScreen controller can be configured to handle Input Actions. Those actions are never received by classes registered to receive **IMixedRealityInputActionHandler** events.

![image](https://user-images.githubusercontent.com/5230670/61393720-32551980-a887-11e9-8390-9725c8ee7298.png)

## To reproduce

1. Create a global handler that implements **IMixedRealityInputActionHandler**
2. Touch the screen

## Expected behavior

The **IMixedRealityInputActionHandler** should receive the Select input action but it does not.

## Your Setup (please complete the following information)

- Unity Version 2018.4.4
- MRTK Version mrtk_develop as of 7/15

## Target Platform (please complete the following information)

- Unity Editor
- Android

**Comment by wiwei** [comment]
@davidkline-ms This I think goes under better support for mobile. See @keveleigh's comments in the PR https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5343

**Comment by davidkline-ms** [comment]
Confirmed #5903 resolves this issue
