### ISSUE TITLE
Example Scene "Hub"

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#5348]
## Describe the problem

When speaking with partners, ISVs, hackers, etc I've noticed the discover-ability of MRTK example scenes is pretty low. Many developers just want to build a single binary of the MRTK and experience all of the example scenes and functionality available to them.

## Describe the solution you'd like

I propose that we build a MRTK "hub scene" that exposes users to all the available examples and launches them into the example (there should also be UI that can bring the user back to the "hub"). Unreal Engine 4 does a great job of this with their content examples: https://docs.unrealengine.com/en-US/Resources/ContentExamples/ExampleLevelOverview/index.html
 
We could even get fancy and load in the example scenes additively using @Railboy's new multi-scene tools, or just load singles in single mode.

## Describe alternatives you've considered

We could use the scene launcher built by @ForrestTrepte: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/689

**Comment by cre8ivepark** [comment]
Let's use Lars' Scene System. https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SceneSystem/SceneSystemGettingStarted.html
For the entry point design, we can use Playground's concept. (launcher objects on a table)

**Comment by cre8ivepark** [comment]
@Cameron-Micka I created a branch and added a new scene 'MRTKExamplesHub.unity'
https://github.com/cre8ivepark/MixedRealityToolkit-Unity/tree/mrtk_development_ExamplesHub

It is a simple scene that contains touchable cubes. We can use MRTK Scene System to load/unload scenes. To reduce the cost for creating 3D model/icons for many example scenes, it would be better to use text only in the cubes. (currently placed dummy geometry).
@Railboy Could you please help with setting up the Scene System? (e.g. OnTouchCompleted() of Hand Interaction Examples cube, load HandInteractionExamples scene. I guess each example scene also needs a back/home button)

![2019-07-19 00_45_12-Unity 2018 4 2f1 Personal - MRTKExamplesHub unity - MRTK-GitHub - Universal Wind](https://user-images.githubusercontent.com/13754172/61472240-03da5a00-a9bf-11e9-9bd3-f17bf010d4e5.png)
![2019-07-19 00_46_02-Unity 2018 4 2f1 Personal - MRTKExamplesHub unity - MRTK-GitHub - Universal Wind](https://user-images.githubusercontent.com/13754172/61472246-076de100-a9bf-11e9-8350-1487d1c60728.png)

We can use this HandInteractionTouch script's OnTouchCompleted() event to load other scene.
![2019-07-19 00_52_33-Unity 2018 4 2f1 Personal - MRTKExamplesHub unity - MRTK-GitHub - Universal Wind](https://user-images.githubusercontent.com/13754172/61472610-c1654d00-a9bf-11e9-8a33-60629e95229e.png)

**Comment by Railboy** [comment]
@cre8ivepark Committed.

**Comment by cre8ivepark** [comment]
Work-in-progress.

**Comment by cre8ivepark** [comment]
Added to 2.1.0 release
