### ISSUE TITLE
On HL1 and Oasis, keyboard cannot be re-opened after it has been closed using HandInteractionExample "Show Keyboard" button

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5363]
## Describe the bug

Since the TouchScreenKeyboard does have a Unity Bug, which means it's neither null, nor reporting an inactive state even though it's closed, @julenka created a potential experimental fix #5018.
The problem is, the fix also does not work. For the fix to work the callbacks from the InputPane, Hiding and Showing need to fire, but they don't, at least not on WMR Immersive.

The code must be correct, so my question is, is it another bug, some configuration I have to do in Unity or something else?

## To reproduce

1. Create a new scene
2. add MixedRealityKeyboard.cs to a gameobject
3. add `ShowKeyboard();` to the start method
4. build and run on UWP native platform with script debugging enabled and all the network capabilities on
5. set a breakpoint in OnKeyboardShowing

it will never fire

## Expected behavior

The keyboard should just work rather, but for now I would be happy if those callbacks were fired.

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.4.2f1]
- MRTK Version current dev branch

## Target Platform (please complete the following information)

- WMR immersive

**Comment by wiwei** [comment]
@julenka, do you remember if keyboard issue was also written for WMR Immersive? I remember the original keyboard issues we hit were with with HL devices.

**Comment by Alexees** [comment]
> do you know which OS build you're running? I believe there was a bug with those events that was fixed in 18362.

@keveleigh I guess I better answer you here, because this is a new issue while the other was a closed PR. I checked the System and can confirm that it's 18362.239

Now I did a little investigation.
On that System (Windows 10 Home) the following happened:
- Opening the Keyboard does not even show it
- From the beginning of the opening, the Keyboard.active state stays true
- The mentioned callbacks of the InputPane are indeed not being called

the first issue is actually a weird one because at work, on another machine, it works. It has either to do with:
-WMR Headset VS Emulator
- Scene with or without MRTK
- Windows 10 Home Vs Enterprise
- Version difference
will test in a couple of hours as I'm not at work right now

**Comment by Alexees** [comment]
Ok, this was a major f***up.
I came to the following conclusion:

- The Keyboard was not showing because I was calling its Open() method too (I think that's the reason). The InputField I was operating on seemed to do this already.
- Since Unity suffers from the active state bug, neither InputField nor TMP_InputField show the Keyboard a second time you click on them. Choosing a different InputField shows it up again
- TMP_InputField is not open source, so I have no idea what OnPointerDown does under the hood and the only possibility do to the workaround with the InputPane hence checking the keyboard instance for null is deriving from it because the relevant field m_softkeyboard is protected

**Comment by Alexees** [comment]
Ok, I give up. Maybe someone else can shed some light on this, but not even the TMP_InputField shows the Keyboard reliably on first try.
I don't know if Unity messes up the code when toggling "Build Scripts only" all the time and building incrementally.
It seems impossible to even get a consistent result with the regular functionality... 😭

**Comment by julenka** [comment]
It was specifically written for HoloLens 2 actually. I assumed it would work on all UWP platforms, though that seems to be not true.

________________________________

**Comment by wiwei** [comment]
I chatted with some folks who know the keyboard stuff from the OS side, it sounds like there are different underlying OS issues as well with respect to how some of these events fire on HL1 or WMR, so it's not actually going to be trivial to just "fix" this (i.e. there needs to be a workaround based on the device capability check to figure out WHICH problem you need to workaround).

I'm going to group up all of these keyboard related issues and we can address them holistically

**Comment by Alexees** [comment]
@wiwei that's interesting to hear, can you tell more about how to fix this. or is someone going to do that? Front and foremost, when?

**Comment by cre8ivepark** [comment]
@Alexees @julenka @wiwei 
Confirmed. In HoloLens 1 and Windows Mixed Reality immersive headset, re-opening keyboard does not work. (Tested with GA stabilization branch 8/12)

**Comment by Alexees** [comment]
Any news on when this is going to be addressed and fixed. Hololens 1 recently went out of major update support after more than 3 years of existence and it's native keyboard is still broken? 😒

**Comment by Troy-Ferrell** [comment]
Also possibly related once fixed: #5310 , #5260

**Comment by julenka** [comment]
Hi Alexees, I'm taking a look at this now. As will mentioned, there are a few underlying OS issues, the current HandInteractionExample implementation provides a workaround just for HoloLens 2 implementation. I'm testing a workaround that might work for HoloLens 1, HoloLens 2, and WMR headsets. If not, we will provide information for how to work around different platforms.
