### ISSUE TITLE
Simulated hand gets "stuck" in pinch pose when alt-tabbing out of editor

### ISSUE THREAD

**Issue by lukastoenneMS** [microsoft/MixedRealityToolkit-Unity#5375]
## Describe the bug

When Unity editor loses focus while holding the mouse button it will never get a matching MouseButtonUp event for the initial MouseButtonDown. The input simulation then doesn't un-pinch the hand, until clicking again to pinch and release.

## To reproduce

1. Start Play Mode
1. Press T to bring up the left hand
1. Hold shift and Left mouse click to pinch
1. Press alt + tab to take focus away from Unity editor
1. Hand stays in pinched pose

To un-pinch the hand:
1. Set focus back to the editor
1. Hold shift and Left click again

## Expected behavior

Hand gesture goes back to default when editor focus is lost (see how manual camera control in input simulation handles it).

**Comment by wiwei** [comment]
I guess probably using:

https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationFocus.html

Oh maybe even easier is:

https://docs.unity3d.com/ScriptReference/Application-isFocused.html

And just check on update if this is false, and if so, treat mouse states as just being gone?
