### ISSUE TITLE
combine 3D models of obj format at 10 different moments into a dynamic 3D model of fbx format

### ISSUE THREAD

**Issue by zhaobingshuai** [microsoft/MixedRealityToolkit-Unity#5376]
## Describe the Issue
Hello, I have recently encountered some questions. How do I combine 3D models of obj format at 10 different moments into a dynamic 3D model of fbx format? Should I use Unity or Blender?
## Feature Area
What's incorrect? What's missing?

## Existing Doc Link
If this is about something in an existing document, please provide link

**Comment by Alexees** [comment]
This is definitely not something related to the MRTK. You should as this question on Unity answers, or even better, a forum for 3D modeling tools and it totally depends on what you want to do with the result mesh.

**Comment by wiwei** [comment]
Thanks @Alexees.

It would probably be better to ask this question on stackoverflow (or Blender forums).
