### ISSUE TITLE
Toggle features panel solver moves menu directly in front of face

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5380]
Having menus directly in front of the face is not great for comfort, but the solver in the toggle features panel moves the menu to be right in front of the face. We should update the params of the solver to be closer to the waist.

**Comment by julenka** [comment]
Marking at GA blocker because toggle menu is usually the script people use to implement follow menu behavior (they copy / paste that prefab), so this prefab needs to have the recommended following behavior.

**Comment by cre8ivepark** [comment]
Updated Radial Solver to match the shell's Follow Me behavior. Testing out on the device and tuning the values now.
