### ISSUE TITLE
Graduate the hand menu out of experimental

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#5381]
Feedback from the hand menu has been really positive, and we'd like to graduate this out of experimental and into the regular ol' SDK.

Filing this issue to track this request, which can be expanded upon with more details about exactly what the requirements/criteria are.

**Comment by Cameron-Micka** [comment]
Might be a dupe of: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5312

**Comment by wiwei** [comment]
Yass, it is, closing this out.
