### ISSUE TITLE
Support 2019 for NuGet

### ISSUE THREAD

**Issue by andreiborodin** [microsoft/MixedRealityToolkit-Unity#5384]
Currently the MSBuild project generation doesn't work for 2019. To make it work, there needs to be relatively small modification to support BuiltInPackages:
2019.1.6f1\Editor\Data\Resources\PackageManager\BuiltInPackages

This will follow the same approach as standard packages, but putting this work after the current effort is complete.

**Comment by keveleigh** [comment]
Looks like this was fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5516
