### ISSUE TITLE
HandInteractionPanZoom is Input, not UI namespace

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5387]
HandInteractionPanZoom should be in the UI namespace, to match BoundingBox and ManipulationHandler

**Comment by Yoyozilla** [comment]
could you add explanation why this is a GA blocker

**Comment by Yoyozilla** [comment]
@julenka

**Comment by julenka** [comment]
I consider it an issue with the usability of our API that a class that's clearly a UI component lives in the Input namespace. Changing the namespace in a future release would be a breaking change, so I'm concerned with putting this off until after GA.

**Comment by julenka** [comment]
Removing myself from this issue since I'm currently out, hopefully we can assign it to somebody else while I'm out. This is an easy fix, doesn't require any UX or input knowledge.
