### ISSUE TITLE
would like to be able to configure FocusProvider to target colliders instead of rigid bodies when both are present

### ISSUE THREAD

**Issue by naostranMS** [microsoft/MixedRealityToolkit-Unity#5391]
## Describe the problem

In FocusProvider.PointerHitResult.Set(MixedRealityRaycastHit hit, ...) and MixedRealityRaycaster.TryGetPrioritizedPhysicsHit, it uses the RaycastHit.transform.gameObject as the target gameObject. In the case of compouned colliders (example here: [https://docs.unity3d.com/Manual/class-Rigidbody.html](url)), the transform will be that of the parent rigidbody rather than the particular collider that was hit.

E.g. when raycasting at the cylinder in this setup (where the Parent object has a RigidBody, and the children each have colliders):
![image](https://user-images.githubusercontent.com/38891743/61568111-d204da00-aa36-11e9-97f6-c1f8ace9d02a.png)
you get the following raycast result:
![image](https://user-images.githubusercontent.com/38891743/61568062-910cc580-aa36-11e9-8ebb-55ecfe290248.png)

In our forked version of HTK, we changed it to use the collider as the focus object to get more granularity, and without that in MRTK, we end up with a lot of broken functionality due to the focus target being different than expected (and also due to prioritization changes because the collider game objects are often on a different layer than the parent rigidbody).

## Describe the solution you'd like

I would like to have a simple way of configuring or overriding the default FocusProvider behavior to use hit.collider.gameObject instead of hit.transform.gameObject.

## Describe alternatives you've considered

1. It might be possible to subclass the FocusProvider and override the needed functionality, but it seems like that would take a lot of extra/duplicated code in the override for what is a very small difference.
2. I imagine the data could be rearchitected to work with the existing behavior, but I think that would be a pretty substantial undertaking.

**Comment by Alexees** [comment]
Hi @naostranMS I felt this task was fun and I did a little something, maybe you're interested in checking it out:
https://github.com/HoloSpaces/MixedRealityToolkit-Unity/tree/mrtk_removeMixedRealityRaycastResult

All you need to do is opening the MixedRealityInputSystem profile you're using and enable "FocusIndividualCompoundCollider"

Would love to hear if that works for you.

**Comment by naostranMS** [comment]
@Alexees thanks for looking into this!
I looked at your change - one thing is that it doesn't look like it will affect the prioritization (see [MixedRealityRaycaster.TryGetPrioritizedPhysicsHit](https://github.com/HoloSpaces/MixedRealityToolkit-Unity/blob/222e50ae873b305560fc56b5589d25c9f8ed288d/Assets/MixedRealityToolkit/Utilities/Physics/MixedRealityRaycaster.cs#L166)), which is also important for our use case.
Also, this was the justification for adding the MixedRealityRaycastHit: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4678#discussion_r289582737. I imagine that removing it might be breaking for some - instead, I think it would be better to just add the collider to it.

**Comment by Alexees** [comment]
Ha, I see. Did not think of that :)

**Comment by wiwei** [comment]
@naostranMS @Alexees these all seem pretty reasonable - a few questions here:

1) @naostranMS Is this something that you think you'll want to change the behavior of at runtime, or primarily something you want to set once at the beginning and then leave it alone?
2) @naostranMS when we do this, can you review the tests that get added to verify that it be representative of your scenario?

**Comment by naostranMS** [comment]
@wiwei 
1. set once and leave it alone
2. yes, I can review the tests

**Comment by naostranMS** [comment]
To add some context, this is the change I made in our fork to make it work as expected: https://github.com/naostranMS/MixedRealityToolkit-Unity/commit/e40c425f2c7c03b0ffd8c0c26ae6914e9780b159. (Note that I'm not putting that up for PR because it changes the default behavior, and I don't want to do that).

After thinking more about it, maybe the simplest/cleanest way would be to add a "target object" var to the MixedRealityRaycastHit, and set that to the transform.gameObject or collider.gameObject depending on the global config setting. Then you could just use that wherever it currently uses hit.transform.gameObject and you wouldn't need to pass any new data to the raycaster.

**Comment by ritijain** [comment]
> To add some context, this is the change I made in our fork to make it work as expected: [naostranMS@e40c425](https://github.com/naostranMS/MixedRealityToolkit-Unity/commit/e40c425f2c7c03b0ffd8c0c26ae6914e9780b159). (Note that I'm not putting that up for PR because it changes the default behavior, and I don't want to do that).
> 
> After thinking more about it, maybe the simplest/cleanest way would be to add a "target object" var to the MixedRealityRaycastHit, and set that to the transform.gameObject or collider.gameObject depending on the global config setting. Then you could just use that wherever it currently uses hit.transform.gameObject and you wouldn't need to pass any new data to the raycaster.

@wiwei  - If @naostranMS 's proposal makes sense, I can work on creating a PR for it.

**Comment by wiwei** [comment]
> > To add some context, this is the change I made in our fork to make it work as expected: [naostranMS@e40c425](https://github.com/naostranMS/MixedRealityToolkit-Unity/commit/e40c425f2c7c03b0ffd8c0c26ae6914e9780b159). (Note that I'm not putting that up for PR because it changes the default behavior, and I don't want to do that).
> > After thinking more about it, maybe the simplest/cleanest way would be to add a "target object" var to the MixedRealityRaycastHit, and set that to the transform.gameObject or collider.gameObject depending on the global config setting. Then you could just use that wherever it currently uses hit.transform.gameObject and you wouldn't need to pass any new data to the raycaster.
> 
> @wiwei - If @naostranMS 's proposal makes sense, I can work on creating a PR for it.

Makes sense to me - that would be awesome!
