### ISSUE TITLE
[Solver] Add degree/distance range to Orbital or Add Y-pos lock to Radial view

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#5393]
## Describe the bug
To achieve shell-parity 'Follow Me' behavior, we need to either:
- Add degree/distance allowance range to Orbital 
- OR Add Y-pos lock to Radial view

Currently, with Orbital Solver, it is possible to place objects with specific Y offset, but it does not have a degree/distance allowance range option which allows lazily movement
Radial Solver has degree/distance range option but it cannot have fixed Y offset. When you move your head up, the object also follows.

Part of the shell-parity items #4200 
Related item: [#4472] Follow Me behavior: no examples available yet in MRTK.

## Degree/Distance allowance range in Radial Solver which is missing in Orbital Solver
This example makes an object stay within 0.3~0.7m and left/right 30degree threshold:
![2019-07-20 10_19_09-Unity 2018 4 2f1 Personal - HandInteractionExamples unity - MRTK-GitHub - Univer](https://user-images.githubusercontent.com/13754172/61572403-dfbe6c00-aad7-11e9-85d2-cfb234fcba16.png)

**Comment by Alexees** [comment]
Wasn't the idea of those solvers to chain them? What about adding Radial first, enabling UpdateLinkedTransform in the inspector, and Orbital second?

**Comment by wiwei** [comment]
@keveleigh, do you have some background on @Alexees  question?
