### ISSUE TITLE
On switching to a different session, created Objects do not show up

### ISSUE THREAD

**Issue by StokedOnIt** [Microsoft/MixedRealityToolkit-Unity#540]
On switching sessions after connected to a session already with objects, objects from switched to Session do not show up. Using AutoJoinSession to switch sessions. After a session is entered with objects, no objects works, but if you are in a session with created objects and then you switch to another session the objects in the switched to session do not show up.

**Comment by StephenHodgson** [comment]
I'm a little confused on your explanation.

Btw, did you try my latest PR for sharing service updates?

**Comment by StokedOnIt** [comment]
No I haven't tried yours but I will, fixes?

**Comment by StephenHodgson** [comment]
This could be a combination of a few things:
1. You could be spawning sync objects that are owned by a specific player, so when they leave a session their objects are also destroyed.
2. You are spawning objects that are owned by the server but when all the users leave the room is destroyed.

PR https://github.com/Microsoft/HoloToolkit-Unity/pull/513 added a few nice things for easier/faster testing in editor.

**Comment by StokedOnIt** [comment]
So are the spawned objects connected to a session or a room? Because changing the room seemed to do nothing.

**Comment by StephenHodgson** [comment]
No worries. Pretty sure that it depends on your setup and how you're doing the sync object spawning. They attach themselves to the root object of the room.

**Comment by StokedOnIt** [comment]
Thanks, Hmmm, I must be missing something as switching rooms does nothing but sessions does. And there is pretty much no explanation from Microsoft. The code in the videos is old and has changed. 

What is the proper way to setup a room and switch? Thanks.

**Comment by StephenHodgson** [comment]
Good question. I think the Room and Anchor test scene is good, but only works in the editor, but doesn't also show synced objects.  A bunch of this stuff has been on my todo list to make a bit better.

**Comment by StokedOnIt** [comment]
I kind of got the idea that the rooms were just for the anchor position if people were in different rooms and that the objects were attached to the session. That's what I got from reading the descriptions in GitHub repeatedly.

**Comment by StephenHodgson** [comment]
Yeah that sounds correct.

**Comment by StokedOnIt** [comment]
The sessions seem to if the session is kept alive. It's just the switching from one with objects to the other with objects that isn't. 
Would you know if there is a way I can attach a String or Bool Value on a session/room?

**Comment by StephenHodgson** [comment]
No you can only create new sync variables on the sync root object.

**Comment by StokedOnIt** [comment]
Hmmmm maybe the sync root is what I need to reset when switching sessions.

**Comment by StephenHodgson** [comment]
[Sync System Docs](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/External/HoloToolkit/Sharing/DocSource/MDFiles/SyncSystem.md)

> - Ownership
>     - Each element has an 'owner'
>     - Owner is either user in the session or the Invalid user, which is used to represent unowned elements
>     - When a system leaves a session
>         - The server removes elements owned by the user that left, forward changes to remaining systems
>         - The system that left deletes all elements except his/her own and global data

**Comment by StephenHodgson** [comment]
Check out https://github.com/Microsoft/HoloToolkit/pull/42. 
It seems to address the persistent session data functionality you're looking for.

**Comment by StephenHodgson** [comment]
Going to close this.  I did push a update to recreate synced objects if needed.
