### ISSUE TITLE
"Change Target Size Override" does not adjust bounding box size

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5414]
## Overview
BoundingBox has an "override" field people can fill in to manually specify bounds. When this changes, bounding box should update its bounds, without needing to call createrig() on its own.

## Steps to reproduce
Open BoundingBoxRunTimeExamples scene and step through the scenarios.

On the "change target bounds override size" step, the bounds should change size to be the following:

![image](https://user-images.githubusercontent.com/168492/61811192-d09c2e80-adf5-11e9-822a-dd3d5aa29d1d.png)

It actually doens't change size:

![image](https://user-images.githubusercontent.com/168492/61811102-9a5eaf00-adf5-11e9-962f-4d2514843646.png)

**Comment by keveleigh** [comment]
Fixed via #5982
