### ISSUE TITLE
Assert in GetGltfObjectFromGlb

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#5417]
## Describe the bug

After pulling the latest dev branch, the following assert fires upon loading in Unity:

chunk 1 & buffer 0 length mismatch

```
UnityEngine.Debug:Assert(Boolean, String)
Microsoft.MixedReality.Toolkit.Utilities.Gltf.Serialization.GltfUtility:GetGltfObjectFromGlb(Byte[]) (at Assets/MixedRealityToolkit/Utilities/Gltf/Serialization/GltfUtility.cs:258)
Microsoft.MixedReality.Toolkit.Utilities.Gltf.Serialization.<ImportGltfObjectFromPathAsync>d__4:MoveNext() (at Assets/MixedRealityToolkit/Utilities/Gltf/Serialization/GltfUtility.cs:116)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start(<ImportGltfObjectFromPathAsync>d__4&)
Microsoft.MixedReality.Toolkit.Utilities.Gltf.Serialization.GltfUtility:ImportGltfObjectFromPathAsync(String)
Microsoft.MixedReality.Toolkit.Utilities.Gltf.Serialization.Editor.<OnImportGltfAsset>d__0:MoveNext() (at Assets/MixedRealityToolkit/Utilities/Gltf/Serialization/Importers/GltfEditorImporter.cs:16)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<OnImportGltfAsset>d__0&)
Microsoft.MixedReality.Toolkit.Utilities.Gltf.Serialization.Editor.GltfEditorImporter:OnImportGltfAsset(AssetImportContext)
Microsoft.MixedReality.Toolkit.Utilities.Gltf.Serialization.Editor.GlbAssetImporter:OnImportAsset(AssetImportContext) (at Assets/MixedRealityToolkit/Utilities/Gltf/Serialization/Importers/GlbAssetImporter.cs:13)
UnityEditor.Experimental.AssetImporters.ScriptedImporter:GenerateAssetData(AssetImportContext)
```

Looking at recent merge history, it seems as if this may have been caused by #5378.

**Comment by wiwei** [comment]
@davidkline-ms, can you rollback the change?

**Comment by davidkline-ms** [comment]
@wiwei, I'll look into it.

**Comment by Troy-Ferrell** [comment]
@davidkline-ms did you get any insights into why this shows? I just hit this in an upgrade migration test with 8/10 preview build.

![image](https://user-images.githubusercontent.com/25975362/62963132-41ab8200-bdb5-11e9-9b2d-713f5d3374d6.png)

**Comment by kelsosharp** [comment]
Is there a fix or workaround for this issue?

**Comment by keveleigh** [comment]
@kelsosharp Not yet. I think for this specific issue, we'll need to make some updates to our glTF logo file.

Are you hitting it with that, or in your own file? Is it causing a blocking issue for you?

**Comment by kelsosharp** [comment]
@keveleigh Honestly I am not sure, this is a brand new project, and all I have done is to import MRTK and Nether, and this error is in my console, I am just coming back to using Unity after being away, so I am not sure this is going to block me or not.

**Comment by keveleigh** [comment]
>so I am not sure this is going to block me or not.

It shouldn't! It should just show up the first time you import MRTK, then not show up again. It should be pretty benign, but we'll still look into cleaning it up.
