### ISSUE TITLE
UI Button handle click twice

### ISSUE THREAD

**Issue by vNikolenkoMIF** [microsoft/MixedRealityToolkit-Unity#5424]
## Overview
UI Button still focused after interaction and handle event twice.
## To reproduce
1. Create Scene in Editor
2. Add Mixed Reality Toolkit RC2 assets and MRTK prefab on Scene 
3. Create Gameobject with World Space Canvas with hierarchy
1.Canvas:
->  1.1. Unity.UI Button(First Button)  (onClick event activate/deactivate Toolbar)
      1.2. Toolbar(empty object with Background) (unactive)
       ->  1.2.1. Unity.UI Button (Second button) (onClick event do some activity, for example - show text)
4. Click on the first button to activate Toolbar by gesture Air Tap and after Toolbar actiation immediately click on the second button.

NOTE: Bug doesn`t reproduce constantly.

## Expected behavior

 - Taps on the second button must show text or you custom action

## Actual behavior

 - Toolbar is disabling, because Air Tap handle First Button action

##  My Setup
 - For interaction simulation in Unity Editor I use XboX 360 Gamepad
- Unity Version  2018.4.3f1
- MRTK Version v2.0 RC2

## Target Platform
- HoloLens 2

**Comment by Troy-Ferrell** [comment]
@vNikolenkoMIF, can you try to repo with latest GA?

**Comment by vNikolenkoMIF** [comment]
@Troy-Ferrell, no, but we found one of the causes of the problem. Problem was in our component, which directly handle events from Unity EventTrigger. In places where we using just UI.Button I did not notice this bug, so, I think issue solved.
