### ISSUE TITLE
Multi-platform sample

### ISSUE THREAD

**Issue by KevinKennedy** [microsoft/MixedRealityToolkit-Unity#5426]
It would be great to have some docs and samples that that demonstrate the right way to build a multi-platform MRTK-based app

A solution would have annotated answers to the following questions:
* Do you try to have a single scene for all platforms or do one scene per platform?
* On ARKit/ARCore do the MRTK controls still make sense or should you use something else like Unity UI?
* How do you gracefully have a profile set for each platform?
* Should apps use ARKit/ARCore directoy or should they choose ARFoundation?
* Can the app handle tablet-ar like it would GGV or does it need to do something special?
* When doing a build from Unity, is it just a platform switch in the build settings or will other steps be necessary (like picking a different scene, changing profile, etc.)
* Bonus: How to automate the Unity part of a multi-platform build

**Comment by polar-kev** [comment]
- A multiplatform app can exist as one scene
- Touch screen support is supported
- Several of these questions are answered by this video on multiplatform MRTK development, https://channel9.msdn.com/Shows/Mixed-Reality/Intro-to-MRTK-Unity

**Comment by KevinKennedy** [comment]
Wow, blast from the past 😊.  Thanks for looking into this!
