### ISSUE TITLE
Pressable Button Instantiation

### ISSUE THREAD

**Issue by asugaya-apx** [microsoft/MixedRealityToolkit-Unity#5428]
## Describe the bug

GameObjects that are linked to the HoloLens2 pressable button script do not always instantiate correctly when we load them as part of a scene that scales up from .001.

## To reproduce

1. Create a view that with a child view that has a pressable button script attached.
2. Initialize the view's scale at (.001, .001, .001).
3. Enlarge the view to (1, 1, 1) [or something that is otherwise visible].
4. Try pressing the object.

## Expected behavior

Button visuals and touchable surfaces should instantiate properly, regardless of original/final scales.

## Your Setup (please complete the following information)

- Unity Version 2019.1.8f1
- MRTK Version RC2

## Target Platform (please complete the following information)

- HoloLens 2
(Also reproducible in editor)

## Additional context

- In order to make the button functional, you have to press it at least once (sometimes this means finding an invisible button because its visual elements seem to get shoved at about 0,0,0). Note that until you press it with a near interaction, it cannot be selected with a far interaction
- Once you press a button's collider once, the visuals will reset/snap into the proper location
- After this point, near and far interactions are possible
- Note that even when the button contents and pressable surfaces "reset" they dont always instantiate into quite the correct position. They can be offset on x,y, or z axis up to about 2cms

- Deactivating and reactivating the pressable button prefab also fixes the glitch.

**Comment by Troy-Ferrell** [comment]
The additional context is a little confusing but this sounds eerily similar to #4971 .

Scaling a button with plane distances in world space causing the "pressability"to break because the plane distance ratios don't update correctly.

@asugaya-apx , I'll work on a better fix. But for the moment & test this is your issue, when instantiating a button, grab the **PressableButton** component, then set DistanceSpaceMode property to SpaceMode.Local

**Comment by asugaya-apx** [comment]
Ahhh, thanks for the information and link -- it does look like it may the same. I tried setting the DistanceSpaceMode to SpaceMode.Local to no avail, but I'm going to take a deeper look today and will report back.

Also odd is that this is more reproducible for us when the camera has a negative X component and the pressable button has a parent game object with a radial solver attached to it. Hopefully I'll have some more information on this after looking at it today.

**Comment by Troy-Ferrell** [comment]
Hmm, that's interesting. When you scale back up to <1,1,1> look at the plane distances in editor view.

If you can share a screenshot or a scene file that would be helpful in understanding the situation. Sounds like there may be more going on than just scaling

**Comment by asugaya-apx** [comment]
Good call -- definitely appreciate the feedback! The distances seem to be reasonable (in between start push distance and max push distance); though the position of the iconAndText/frontPlate are off by just a little bit. My guess is that their positions are set in UpdateMovingVisualsPosition before the scale occurs, then when it's scaled up, there's a bit of a rounding error (which explains why using SpaceMode.Local wouldn't have an effect, given that the position is still set pre-scaling).

To test this, I placed UpdateMovingVisualsPosition into an if block in the Update loop of the pressable button that checks to see if the world scale of the object has changed, something like this: 

`if(transform.lossyScale != previousScale){
                previousScale = transform.lossyScale;
                UpdateMovingVisualsPosition();
  }`

That seems to fix this particular for the time being; that said, when there's a stabilization branch for the next version of the MRTK, we'll check to see if this issue persists.

As a side note, when the button is instantiated outside of the camera's frustum, it seems like there may be a similar issue (the button's moving visuals don't appear) -- I'll have to investigate this a bit more and will attach a video/screenshots if I can capture something informative. If you'd like me to open a separate ticket for this, let me know; that said, I'll still dig to see if there's a root issue causing both.

**Comment by asugaya-apx** [comment]
Following up here, it seems like the frustum issue only occurs (or at least, is only visible) in editor; so we're all good.

There's also a little bit off an X/Y offset for the moving visuals (likely due to that their position is calculated from a world position, though setting to local spacemode didn't seem to help which is odd) -- I put in a temporary fix on our side that just forces these values to 0.

Once the stabilization branch / RC are in a good place, we'll test it out to see if the issues have resolved -- and we'll open a new ticket if not. Thank you again for your feedback Troy!
