### ISSUE TITLE
PointingRaycastLayerMasks do not respect UI layer priority

### ISSUE THREAD

**Issue by camnewnham** [microsoft/MixedRealityToolkit-Unity#5435]
## Describe the bug

When setting the PrioritizedLayerMasks (PointingRaycastLayerMasks) to have UI at the top, the UI layer is not correctly picked up. Changing the objects to a new layer (i.e. CustomUI) and putting that at the top does not exhibit this behaviour

## To reproduce

1. Enable spatial mapping (or use an object on the SpatialAwareness Layer)
2. Create a cube and add manipulationhandler functionality.
4. Set PointingRaycastLayerMasks to UI -> Default -> Spatial Awareness
5. Observe that the object on the UI layer can not be manipulated when it is behind the spatial mapping.

## Expected behavior

The UI layer is treated the same as any other layer when prioritizing raycasts

## Screenshots

Configuring for raycasting with UI priority

![raycast_ui](https://user-images.githubusercontent.com/19278856/61933180-920a9d80-afc8-11e9-8a18-19f03d457cda.PNG)

exhibits this behaviour:

![normalui](https://user-images.githubusercontent.com/19278856/61933200-a2bb1380-afc8-11e9-8d43-edf6f5099f1d.gif)

And changing the prioritized layer and object layer

![raycast_customui](https://user-images.githubusercontent.com/19278856/61933216-aea6d580-afc8-11e9-9947-5cf990a28b88.PNG)

exhibits this behaviour (expected)

![customui](https://user-images.githubusercontent.com/19278856/61933238-bd8d8800-afc8-11e9-9fbc-705759bf3dd0.gif)

## Your Setup (please complete the following information)

- Unity Version 2018.4.3f1
- MRTK Version 2.1 Refresh

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

## Additional context

The reason this is relevant:
- When making a slate, it's not uncommon to put it on the UI layer. 
- When a slate has to 'spawn' it might spawn behind other objects (i.e. spatial mapping). The user may need to be able to drag it out from that position, or interact with it when it's behind said object.

In this example, the spatial mapping is visible for clarity, but oftentimes the meshrenderer would be disabled and the collider would remain,  and hence this results in the user being able to see the object clearly but not manipulate it

**Comment by camnewnham** [comment]
And potentially a related issue: the whether the masks are respected or not appears to be related to distance. When close to the spatialawareness object the raycasts hit it, but when further away they do not.  This is when using the default layer and the pointer masks Default -> SpatialAwareness

![collider_behind_spatialmapping_s](https://user-images.githubusercontent.com/19278856/61939296-4a8b0e00-afd6-11e9-8dbb-e6ab82e8fb60.gif)

**Comment by camnewnham** [comment]
And further supporting documentation, the view in the InputModule _does_ show the correct masks, regardless of the distance:

![image](https://user-images.githubusercontent.com/19278856/61940025-f3863880-afd7-11e9-9945-02b0bbaf2053.png)

**Comment by Troy-Ferrell** [comment]
@camnewnham thanks for filing this issue.

The respecting layer mask appears to be fixed in the stabilization branch as I cannot repo. 

![spatial-map](https://user-images.githubusercontent.com/25975362/62724877-cfa7f700-b9c8-11e9-8b5a-196ede95bf8f.gif)

Also regarding the distance, there is the pointer extent field which I believe is the raycast distance effectively. If you increase this then you should get expected behavior for longer distance interactions.

![image](https://user-images.githubusercontent.com/25975362/62724976-0716a380-b9c9-11e9-9765-3291b0e31aef.png)

Closing this for now, but re-open if you find something else

**Comment by salvolannister** [comment]
I am facing a very similar situation and setting Point Extend to a bigger value doesn't solve my problem :/ 

using:
Unity 2019.4.16 
Azure Mixed Reality Services 2.7.1
