### ISSUE TITLE
Can't notify user of manipulation event

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5436]
## Describe the bug

There was already a bug report (#511) but it was closed, so bear with me when I open this up again.

I was testing the native keyboard stuff with the MRTK, a canvas and 4 Input fields in the scene when all of a sudden this error showed up about 5 times in a row.

```
Can't notify user of manipulation event - error code says we successfully retrieved the delta, but it's null!
 
(Filename: C:\buildslave\unity\build\Runtime/VR/HoloLens/Gestures/GestureRecognizer.cpp Line: 978)
```

I wasn't sure this should be filed on Unity's side or if it's better to do it here (or both?)

## To reproduce

no idea

## Expected behavior

No error

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1
- MRTK mrtk_development

## Target Platform (please complete the following information)

- WMR immersive

**Comment by PJBowron** [comment]
FWIW I've been getting this same error today. I even found a reliable way to cause it; but unfortunately that's not as useful as it sounds.
I have an app where the user is able to point at and drag a UI panel around via far interaction and the hand rays. At a certain time, the app also shares an anchor across the network. Under certain circumstances (that can be hard to replicate, but persist once they exist) anchor serialization takes excessive time and will block the device to the point where the screens actually stop rendering for period of time.
If the panel is being dragged when this block occurs, then the error will spam momentarily afterwards.
I'm not sure if this helps anyone, but there it is.

**Comment by Holo-FloWandinger** [comment]
I encountered the same issue, while moving a UI panel around via far interaction with hand rays and a similir scenario to PJBowron. But in my case this error was thrown 10 times in a row. (Maybe for both hands?)

**Comment by keveleigh** [comment]
Hrm yeah, the root source of the message is internal to Unity. It's possible MRTK is doing something or there are specific scenarios it might show up more often though, maybe when the app's under slightly heavier load. Could be a sign of a race condition in Unity's code somewhere.

I think the best course of action here would be to log a Unity bug if anybody has some reasonable repro, and we can ask them to take a look at it. Otherwise, I'm not sure what we can do to improve this case in MRTK.
