### ISSUE TITLE
Opening slates cancels pointer interaction with UI Elements

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5439]
## Describe the bug

Whenever a slate is opened (Menu, Keyboard), the loss of the controller in the scene is not reflected by the MixedRealityInputModule.
UI elements gazed upon do not receive proper exit calls.

## To reproduce

1. Create a canvas with some UI element, preferably an InputField and change its normal color
2. build to WMR Immersive
3. point at the InputField -> it turns white
4. press the menu button on the controller, point somewhere else and close the menu button
Notice how the InputField still is white

If you open the menu while holding the trigger (Pointer Down), you'll notice it stays grey, which is the pressed color

## Expected behavior

MixedRealityInputModule calls the same cleanup methods as the FocusProvider does

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1
- MRTK mrtk_development

## Target Platform (please complete the following information)

- WMR immersive

**Comment by keveleigh** [comment]
Could be related to the underlying cause of #4657
