### ISSUE TITLE
Access violation running sharing prefab on emulator

### ISSUE THREAD

**Issue by geshas** [Microsoft/MixedRealityToolkit-Unity#544]
Hi,
After adding the sharing prefab to my project

I keep getting this error, when trying to run it on emulator:
maybe someone have an idea?

SharingService: Local Machine Name: hololens-5h8ea
 
(Filename: C:/buildslave/unity/build/artifacts/generated/Metro/runtime/DebugBindings.gen.cpp Line: 51)

SharingService: Connecting to Server at 10.110.72.73:20602
 
(Filename: C:/buildslave/unity/build/artifacts/generated/Metro/runtime/DebugBindings.gen.cpp Line: 51)

Setting up 1 worker threads for Enlighten.

  Thread -> id: b98 -> priority: 1 

The program '[416] VCC.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

**Comment by christjt** [comment]
Closing unity + emulator and building from Unity again usually fixes this bug for me. Not sure why / where Access violation comes from though.

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.

**Comment by furkee** [comment]
I am running into same issue. I think this should be re-opened as the suggested solution is not really a solution but a tiresome work around.

**Comment by StephenHodgson** [comment]
@furkee please open a new issue with a list of repro steps and the exact access code violation.
Thanks

**Comment by dtoceaneering** [comment]
Hi, StephenHodgson
I am also at the same issue.I am getting this issue while making a build on Hololens device or Emulator.
I want to open web browser inside Hololnes,but i am able to do this due tho these type of issue.Could please suggest how to fix it.
