### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by SoundGuy** [microsoft/MixedRealityToolkit-Unity#5441]
## Describe the bug

I'm trying to build an empty project that only includes that MRTK foundatoin and examples, and i'm getting this error:

F:\Unity Projects\Tests\MRTK2-examples\Builds\WSAPlayer\MRTK2-examples.sln.metaproj : error MSB4126: The specified solution configuration "master|" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [F:\Unity Projects\Tests\MRTK2-examples\Builds\WSAPlayer\MRTK2-examples.sln]
UnityEngine.Debug:Log(Object)
Microsoft.MixedReality.Toolkit.<>c__DisplayClass1_0:<StartProcessAsync>g__OnOutputDataReceived|2(Object, DataReceivedEventArgs) (at Assets/MixedRealityToolkit/Extensions/ProcessExtensions.cs:106)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()

## To reproduce

Clean project with MRTK and examples, using the spatial awareness scene

## Expected behavior

Expected build to suceed

## Your Setup (please complete the following information)

- Unity Version  2019.1.11f
- MRTK Version v2.0.0 RC2.1
Visual Studio 2019

## Target Platform (please complete the following information)

- HoloLens

**Comment by wiwei** [comment]
Ah, I remember fixing something like this a little while back:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4625

Should be fixed in the next release.

**Comment by SoundGuy** [comment]
I tried the workaround of building for the firs time but - This also happens if I build the project , Both if i do first Unity and then in Visual studio, and also if i try to only build the unity project from the build window (success).
it doesn't go away when I build the project for the first time.
