### ISSUE TITLE
Documentation Push - Bounding Box

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#5460]
This issue tracks work to improve the documentation (both code and github.io) for this component.

- [x] #5742
- [ ] #5743

**Comment by Troy-Ferrell** [comment]
@thalbern are these items still necessary with regards to refactor?

**Comment by thalbern** [comment]
sry late for the party - there's a ticket to track the bounds control conceptual docs https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7443

I'll close this one now bc work is done for boundingbox docs
