### ISSUE TITLE
Documentation Push - Manipulation Handler

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#5461]
This issue tracks work to improve the documentation (both code and github.io) for this component.

- [ ] Ensure that the public and protected members of the code have doccomments.
- [ ] Ensure that github.io docs has a "golden path" tutorial on how to use it in editor.
- [ ] Ensure that github.io docs has a "golden path" tutorial on how to use it via runtime/code instantiation.

**Comment by thalbern** [comment]
passing this on to @MenelvagorMilsom as he's refactoring big parts of manipulationhandler - golden path tutorials should be written after the refactor is finished.
