### ISSUE TITLE
What would be the best way to network HandDraggable?

### ISSUE THREAD

**Issue by Holo-Krzysztof** [Microsoft/MixedRealityToolkit-Unity#548]
I'm currently working on a multi-user application and being able to use HandDraggable would save me a lot of work; however, I don't know what'd be the best way to make the script network-aware while keeping the changes from upstream minimal.

To do that, I'd have to inherit from NetworkBehaviour instead of MonoBehaviour and check if e.g. the current player has authority over the object, but that would require components which might be unneeded for people building a single player app/game. I think the best solution would be to make a separate script, e.g. NetworkedHandDraggable that inherits from NetworkBehaviour and only applies input when e.g. the server allows it. A problem however would be, that changes to  HandDraggable would need to be manually copied over to the new class, which would suck for maintenance.

What's your take on this?

**Comment by StephenHodgson** [comment]
I actually did something very similar not too long ago.
Let me go back and look at my notes and I'll get back to you.

**Comment by StephenHodgson** [comment]
@Holo-Krzysztof, are you using uNET or the HTK sharing service?

I've been able to get this working with the HTK sharing service using the sync objects, but not over uNET

**Comment by Holo-Krzysztof** [comment]
I'm using UNet.

**Comment by StephenHodgson** [comment]
You'll definitely have to write your own networked implementation.

**Comment by Holo-Krzysztof** [comment]
Yeah, I'm aware of that.

However, a large part of its code would be shared with the current HandDraggable. Is there a way that'd make it less painful to integrate  changes made to the original script?

**Comment by StephenHodgson** [comment]
Not that I can think of. Hopefully someone will come by with a good idea.

The only thing I can suggest is trying to create a networked component you'd add to your draggable object. Only let it keep track of position and a bool that tracks if it's editable/draggable or not. Then toggle the hands draggable component depending on the boolean value.

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
