### ISSUE TITLE
In-Editor camera/hand simulation can get into a bad state when the mouse goes out of the Unity Editor window. 

### ISSUE THREAD

**Issue by hendryems** [microsoft/MixedRealityToolkit-Unity#5485]
## Describe the bug

One of our developers observed that the hand simulation can get into a bad state when the mouse goes out of the Unity Editor window. Specifically, when enabling mouse look (Mouse Right Click), Left Hand Manipulate (Left Shift), Pinch (Mouse Left Click) to drag an object in the HandInteractionExamples scene until the mouse is outside of the Unity Editor window. Releasing all would still result in mouse look state still being active.

## To reproduce

1. Run the HandInteractionExamples scene
2. Grab an object with Mouse Right Click, Left Shift + Mouse Lift Click
3. Start dragging the object until the mouse cursor leaves the Unity Editor
4. Release Mouse Right & Left Click & Left Shift

## Expected behavior

Mouse movement no longer triggers mouse look

## Actual behavior

Mouse movement continues to drive camera

## Your Setup (please complete the following information)

- Unity Version [2018.4.4f1]
- MRTK Version [Microsoft.MixedReality.Toolkit.Foundation 2.0.0-20190730.2]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by lukastoenneMS** [comment]
So this is definitely a Unity bug. Unfortunately they won't be fixing this any time soon, so i'm going to close this issue as well.

[https://issuetracker.unity3d.com/issues/mouse-button-input-remains-active-after-clicking-going-off-screen-and-releasing-it](https://issuetracker.unity3d.com/issues/mouse-button-input-remains-active-after-clicking-going-off-screen-and-releasing-it)

**Comment by hendryems** [comment]
@ericob , do you know if this is something we're tracking on the Unity side already?

**Comment by lukastoenneMS** [comment]
@hendryems I have logged the bug with Unity. The reply was

> I've reached out to our developers about your issue and, unfortunately, it is highly unlikely that this issue would be fixed, given its low severity and the fact that we are hoping to move to the new Input System at some point in the near future.
