### ISSUE TITLE
In-Editor Input simulation does not allow for head tilt/camera roll

### ISSUE THREAD

**Issue by hendryems** [microsoft/MixedRealityToolkit-Unity#5489]
## Describe the problem

From the [documentation](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSimulation/InputSimulationService.html), it doesn't look like head tilting (camera roll) is something that's supported:

![image](https://user-images.githubusercontent.com/50596066/62320785-01174480-b456-11e9-8ef2-b2177c92b6d9.png)

Here's what's desired:
![image](https://user-images.githubusercontent.com/50596066/62320882-3d4aa500-b456-11e9-957f-3ea08b39fe2a.png)

This is also something that's supported in the [HL simulator](https://docs.microsoft.com/en-us/windows/mixed-reality/advanced-hololens-emulator-and-mixed-reality-simulator-input):

![image](https://user-images.githubusercontent.com/50596066/62320966-6c611680-b456-11e9-84d7-dbbdcc251698.png)

This is critical to be able to test out code that more accurately mimics user's head movement without having to deploy onto a physical HMD.

## Describe the solution you'd like

Extend `ManualCameraControl.GetCameraControlRotation` ([source](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit.Services/InputSimulation/ManualCameraControl.cs)) to include additional keys that supports this:

```
            if (this.isGamepadLookEnabled)
            {
                ...
            }

            KeyboardLookTick(ref rot);

            if (this.ShouldMouseLook)
            {
                ...
            }

```

KeyboardLookTick implementation would be something like this:

```
    private void KeyboardLookTick(ref Vector3 rot)
    {
        // TODO: Make keys customizable from profile
        if (Input.GetKey(KeyCode.Comma))
        {
            rot.z += InputCurve(Time.deltaTime * this.keyboardRotationSensitivity);
        }
        else if (Input.GetKey(KeyCode.Period))
        {
            rot.z -= InputCurve(Time.deltaTime * this.keyboardRotationSensitivity);
        }
    }
```

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by lukastoenneMS** [comment]
Main obstacle here is the crowded keyboard mapping for input simulation. The Q/E keys in particular are already used by the hand rotation feature, which occupies 6 keys in total and is very awkward to use. It would prefer to try and refactor the hand rotation using mouse movement first, using some kind of turntable + twist combination. That would free up the keys for camera rotation as well.

**Comment by ericob** [comment]
This works now
