### ISSUE TITLE
Interactable Themes need to allow reverting to original properties

### ISSUE THREAD

**Issue by LaneMax** [microsoft/MixedRealityToolkit-Unity#5497]
## Describe the bug

When disabling an Interactable that's using an InteractableShaderTheme, the Interactable needs to clean up all its MaterialPropertyBlocks so that the properties of the targeted material are not locked.

## To reproduce

1. Setup an Interactable that uses an InteractableShaderTheme
2. At runtime, disable or destroy the Interactable
3. Select the MeshRenderers material propertie that the InteractableShaderTheme was targeting and try to change its value, it will be locked from the MaterialPropertyBlock

## Expected behavior

All targeted renderer materials should be cleaned up and unlocked from the MaterialPropertyBlocks when ether disabling or destroying the Interactable script.

## Your Setup (please complete the following information)

- Unity Version 2019.1.0f2
- MRTK Version v2.0.0 RC2.1

## Target Platform (please complete the following information)

- Any

**Comment by Troy-Ferrell** [comment]
@LaneMax awesome find! Thanks, adding to list of other Interactable issues

**Comment by Troy-Ferrell** [comment]
@LaneMax I investigated this a bit more. Can you please provide additional details on your scenario? Are you using InteractableShaderTheme directly or the InteractableColorTheme or something else? How are you trying to change the color or shader property after disabling or destroying interactable?

When using MaterialPropertyBlocks (regardless of using Interactable or not), modifying say the color via the material inspector will not work in Unity. 

However, you should be able to modify the shader properties via your own script using your own MaterialPropertyBlock. For example, this worked for me. 

MaterialPropertyBlocks are more like containers and shouldn't acquire a "lock" on a material. They just get and set data. I was concerned Interactable may still be running even when disabled possibly but that is not the case.

```csharp   
            meshRenderer.GetPropertyBlock(propertyBlock);
            propertyBlock.SetColor("_Color", Color.red);
            meshRenderer.SetPropertyBlock(propertyBlock);
```

**Comment by michael-house** [comment]
I believe the issue isn't "locking" per-se, it's just the property block **still exists**, and continues to override any other changes made to the material, even after the InteractableShaderTheme is removed. 

The property block just needs to be removed/reverted when a shader theme is removed/destroyed.

**Comment by Troy-Ferrell** [comment]
@michael-house how are you making material changes? 

If you have another script that is using MaterialPropertyBlock as well, that should work in conjunction

**Comment by michael-house** [comment]
@Troy-Ferrell It's not so much that changes are being made after the fact, it's that the changes made by the InteractableShaderTheme still exist. 

So, for example, if one used their InteractableShaderTheme to add a highlight to an object, then removed the InteractableShaderTheme, the highlight would remain.

**Comment by Troy-Ferrell** [comment]
Ah, I think I see. That's not cleaning up a MaterialPropertyBlock. That's just resetting Material values to their original state before the Theme was applied. Again, MaterialPropertyBlocks are just transient containers. They copy and set properties in an actual material. You can keep a MaterialPropertyBlock "alive" and change a Material property to something else. 

Your request is a bit tricky because some people would not want the behavior you described. Some people would want any changes done by the Theme to persist. They might want to disable a theme to stop making future changes but keep the material as-is currently. 

What you are describing is only a bug depending on who you are asking. It's more of a feature request though to allow themes to revert/reset to original state.

**Comment by Troy-Ferrell** [comment]
Keep this around
