### ISSUE TITLE
FindMsBuildPathAsync() does not actually follow filtering criteria for bestPath

### ISSUE THREAD

**Issue by genbod** [microsoft/MixedRealityToolkit-Unity#5499]
## Describe the bug

The first result from vswhere -all -products * -requires Microsoft.Component.MSBuild -property installationPath will always be returned regardless of the filter criteria.  This is because result.Output is a string array of each returned path.  The code currently then reads the first string splits on newlines and tries to filter that array by the filter criteria and return the best path.  That first line only has one msbuild install path though so it will always be returned.

## To reproduce

1.  Install multiple versions of Visual Studio, i.e. 2019, 2017 professional/community/enterprise etc.
2. Run vswhere -all -products * -requires Microsoft.Component.MSBuild -property installationPath from Visual Studio Installer directory.
3.  Take note of order results are returned
4. Run build appx from MRTK build window
5. Take note of msbuild version that is used (it will be the first in the list)
6.  Change the filter order in "FindMsBuildPatchAsync()" in UwpAppxBuildTools
7. Run build appx from MRTK build window
8. Notice the same msbuild version is used

## Expected behavior

The path to the current msbuild version should be returned.  Right now the script can't handle the case if Visual studio 2019 is installed and shows up earlier in the list.  The location of msbuild is slightly different in VS2019.  I have change that will fix this but also requires changing the VSTools version in the generated solution.

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by keveleigh** [comment]
I believe this is fixed by a combination of https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6477, https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6903, and https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5415
