### ISSUE TITLE
Sharing Transformations?

### ISSUE THREAD

**Issue by Nakle** [Microsoft/MixedRealityToolkit-Unity#550]
Is it possible to manipulate objects in a shared scene? Maybe use `HandDraggable` to transform different objects and update the anchors?

**Comment by Ziugy** [comment]
You normally use a network layer for synchronizing objects in a shared experience: HoloToolkit.Sharing, UNET. I've been using UNET with custom NetworkBehaviours or NetworkTransform / NetworkTransformChild for syncing local position / rotation relative to shared world anchor(s). I would recommend looking at SharingWithUNET under HoloToolkit-Examples.

**Comment by Nakle** [comment]
Allright, thanks! I will look at the UNet samples asap. I figured that the `HandDraggable` would sync the positions between users by it self..

**Comment by StephenHodgson** [comment]
If you're using the sharing system, take a look at the SharingSpawnTest scene.

1. Add the InputManager.prefab to the scene
2. Add the DefaultCursor.prefab to the scene
3. Add `HandDraggable` to either/both of the spawn object prefabs located in `Sharing/Tests/Prefabs`
4. ???
5. Profit

**Comment by StephenHodgson** [comment]
The Sharing libraries have been updated to include sync transform components.
