### ISSUE TITLE
Null Reference Exception in SystemKeyboardExample

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#5501]
## Describe the bug

When running the HandInteractionExamples the Unity log is spammed with null reference exceptions from the SystemKeyboardExample due to the debug text not being set up in the inspector.

## To reproduce

1. Run the HandInteractionExamples on a HoloLens 2.
2. Download the UnityPlayer.log
3. Notice `NullReferenceException: Object reference not set to an instance of an object.
  at Microsoft.MixedReality.Toolkit.Examples.Demos.SystemKeyboardExample.Update () [0x00000] in <00000000000000000000000000000000>:0 ` throughout the log.

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1
- mrtk_development

**Comment by Troy-Ferrell** [comment]
Thank you! Just hit this
