### ISSUE TITLE
Input simulation 'tap/press' does not work 

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#5506]
## Describe the bug
When I click the mouse, instead of tap/press, the simulated hand only moves vertically.

## To reproduce
Run any scenes in the Unity editor. Click left mouse button to simulate press.

## Screenshots
![MRTK_InputSimulation2](https://user-images.githubusercontent.com/13754172/62397169-ddbdc980-b529-11e9-881b-5946ad54a526.gif)

![MRTK_InputSimulationIssue](https://user-images.githubusercontent.com/13754172/62396533-4015ca80-b528-11e9-8494-d5afb32af309.gif)

## Branch
prerelease/2.0.0_stabilization

**Comment by Cameron-Micka** [comment]
I've re-produced this locally too.

**Comment by Troy-Ferrell** [comment]
Same, it's in stabilization

**Comment by davidkline-ms** [comment]
this was addressed by #5513, if this does not fix the issue, please reopen with any additional information. thanks!
