### ISSUE TITLE
IMixedRealityService vs IMixedRealityDataProvider complicates service registration

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#5509]
## Describe the bug

The service registration process is a bit convoluted at the moment. The interfaces currently in place, to not break customers and scenarios, result in a contradictory architecture.

Much of the issue revolves around the MRTK tracking it's own services while still have the MixedRealityServiceRegistry around. Unfortunately, the MixedRealityServiceRegistry cannot register IMixedRealityDataProviders. But IMixedRealityDataProvider is just an empty interface extending IMixedRealityService.

Thus, the MRTK object is a Registrar is the class to register services & data providers and the Registry is the class for storage.

However, only the services & not the dataproviders can be placed in the Registry storage which is very odd. This makes it difficult to clean up the code. 

It's also strange that developers can access services in both the MixedRealityServiceRegistry  and the MRTK.GetService and MRTK.GetDataProvider. But also subsystems can also provide GetDataProvider etc

Related Issues:
#4104 

## Expected behavior

Clear service registration and access as well as flexibility for people to use some services but not all of the MRTK framework

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by davidkline-ms** [comment]
Spoke with @Troy-Ferrell, we believe we have updated the design to alleviate the confusion. He will be opening a PR shortly,
