### ISSUE TITLE
Building MRTK v2.0.0 RC2.1 with min. SDK 16299 fails

### ISSUE THREAD

**Issue by dl4mmers** [microsoft/MixedRealityToolkit-Unity#5510]
## Describe the bug

We get errors in Visual Studio when we try to build and deploy a clean MRTK v2.0.0 RC2.1 Unity Project (with min. SDK 16299 in Unity build settings) to the HoloLens1. We need the min. SDK 16299 because our main project depends on a DLL which needs 16299 as min. SDK. 

The following errors occur: 

`18>------ Build started: Project: MRTK_SDK_Test, Configuration: Release x86 ------`
`[...]`
`18>  Running AssemblyConverter...`
`18>  Failed to fix references for method System.Reflection.MethodInfo Microsoft.MixedReality.Toolkit.ReflectionExtensions::GetMethod(System.Type,System.String,System.Reflection.BindingFlags)`
`18>  Failed to fix references for type Microsoft.MixedReality.Toolkit.ReflectionExtensions`
`18>  System.Exception: Failed to resolve System.Reflection.BindingFlags`
`18>     bei Unity.ModuleContext.Retarget(TypeReference type, GenericContext context)`
`18>     bei Unity.FixReferencesStep.Visit(MethodDefinition method, GenericContext context)`
`18>     bei Unity.FixReferencesStep.Visit(TypeDefinition type)`
`18>     bei Unity.TypeDefinitionDispatcher.DispatchType(TypeDefinition type)`
`18>     bei Unity.TypeDefinitionDispatcher..ctor(ModuleDefinition module, ITypeDefinitionVisitor visitor)`
`18>     bei Unity.FixReferencesStep.ProcessModule()`
`18>     bei Unity.ModuleStep.Execute()`
`18>     bei Unity.FixReferencesStep.Execute()`
`18>     bei Unity.Step.Execute(OperationContext operationContext, IStepContext previousStepContext)`
`18>     bei Unity.Operation.Execute()`
`18>     bei Unity.Program.Main(String[] args)`

[This answer at Stackoverflow](https://stackoverflow.com/a/55626479) stated that it should be possible to build the MRTK Project with a min. SDK at or lower as the HoloLens OS version (which in our case is 10.0.17763.615). 

In Unity forums I've found [a workaround](https://forum.unity.com/threads/error-while-building-uwp-app-with-min-platform-version-10-0-16299-0.685918/#post-4621726) with which I could resolve these errors and successfully build and deploy the MRTK v2.0.0 RC2.1 Unity Project with min. SDK 16299 on HoloLens1. 

## To reproduce

1. Create a new MRTK v2.0.0 RC2.1 Unity Project and scene with MixedRealityToolkit and MixedRealityPlayspace Gameobjects. 
2. Build the scene with the following build settings: 
![build-options](https://user-images.githubusercontent.com/42814715/62454888-75632800-b775-11e9-9610-eda2096bbfa4.png)
3. Build the resulting VS solution with the following settings: Release, x86

## Expected behavior

The VS solution should build without errors and deploy the resulting app on HoloLens1. 

## Your Setup (please complete the following information)

- Unity Version 2018.4.5f1
- MRTK Version v2.0.0 RC2.1
- Visual Studio 2017 v. 15.9.28307.586

## Target Platform (please complete the following information)

- HoloLens 1

**Comment by wiwei** [comment]
Interesting, according to the latest on the Unity thread, it looks like an issue in VS itself.

Looking around, I found what seems like a fairly good explanation for what's going on:

https://github.com/NuGet/Home/issues/6201

**Comment by dl4mmers** [comment]
Thank you for your answer. That makes it clearer.

We were building the VS solution with .NET Core v5.4.4. After switching to .NET Core v6.2.8 the error is gone, but another one appears: 

`18>  Running AssemblyConverter...`
`18>  System.InvalidOperationException: Die Sequenz enthält mehrere übereinstimmende Elemente. (german for 'The sequence contains several matching elements.')`
`18>     bei System.Linq.Enumerable.Single[TSource](IEnumerable 1 source, Func 2 predicate)`
`18>     bei Unity.ModuleContext.GetCorLibMethod(TypeReference type, Func 2 predicate)`
`18>     bei Unity.ModuleContext.GetCorLibMethod(String typeFullName, String methodName)`
`18>     bei Unity.AddMethodUtilityClassStep.WSA_AddInvokeDefaultConstructorMethod(TypeDefinition type)`
`18>     bei Unity.AddMethodUtilityClassStep.ProcessModule()`
`18>     bei Unity.ModuleStep.Execute()`
`18>     bei Unity.Step.Execute(OperationContext operationContext, IStepContext previousStepContext)`
`18>     bei Unity.Operation.Execute()`
`18>     bei Unity.Program.Main(String[] args)`

I've tested building/deploying different configurations with Unity 2018.4.5f1 + MRTK 2.0.0-RC2.1:

### .NET Core v5.4.4
- Min SDK: 10.0.10240 => **✓**
- Min SDK: 10.0.10586 => **✓**
- Min SDK: 10.0.14393 => **✓**
- Min SDK: 10.0.15063 => **✓**
- Min SDK: 10.0.16299 => **✓** (Workaround)
- Min SDK: 10.0.17134 => **✓** (Workaround)
- Min SDK: 10.0.17763 => **✓** (Workaround)

### .NET Core v6.2.8
- Min SDK: 10.0.10240 => **✓**
- Min SDK: 10.0.10586 => **✓**
- Min SDK: 10.0.14393 => **✓**
- Min SDK: 10.0.15063 => **✓**
- Min SDK: 10.0.16299 => **✗** (error mentioned above)
- Min SDK: 10.0.17134 => **✗** (error mentioned above)
- Min SDK: 10.0.17763 => **✗** (error mentioned above)

Do you think this error is also a VS issue?

**Comment by wiwei** [comment]
To be totally honest, I'm not sure - I'm guessing that you're probably running into what this person also hit about two years ago:

https://forums.hololens.com/discussion/9017/problem-with-universal-windows-platform-when-minimal-version-is-set-to-10-0-16299

I think you might be hitting some incompatibility/less tested combination of things (i.e. an older SDK version with more current .NET Core versions)

**Comment by wiwei** [comment]
For now maybe the workaround is what you have to do - I can ask around internally to see if anyone has any thoughts on this.

I'm guessing what you're hitting here shouldn't be MRTK specific (i.e. it's based on the combination of things that are being pulled in, but given the other person's question on that hololens forum I would assume that it's probably a more general issue you're encountering)

**Comment by Troy-Ferrell** [comment]
@dl4mmers , after updating to GA, does this still repo for you?
