### ISSUE TITLE
Interactable Focus broken. Activates when not actually in focus

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#5529]
## Describe the bug

When creating a new interactable, the component will respond to focus theme values when the object is not actually in focus. Just activating the left or hand line ray pointers into space will cause the interactable to become in "focus" even when the hand ray isn't pointing at the cube

What is odd is that the bucky ball in the InteractablesExample scene works as expected. It appears after reloading the scene or some such change, the interactable will start working as expected. So there is some default initialization value causing the odd behavior.

At first the emerald box was not working then on re-opening the scene a second time, it started working. When I created a new orange cube, that one started off broken.

![interactable-focus-bug](https://user-images.githubusercontent.com/25975362/62558880-b2d7bc00-b82e-11e9-9968-687e449dc5ed.gif)

![interactable-focus-bug-2](https://user-images.githubusercontent.com/25975362/62559109-2aa5e680-b82f-11e9-9a1d-52859a7f1bf4.gif)

## To reproduce

Create new scene
Add MRTK with HL2 default profile
Create cube and add interactable component
Add Target of Cube and add "Model_BuckyTheme" as theme

![image](https://user-images.githubusercontent.com/25975362/62558376-c5052a80-b82d-11e9-976e-503e1de3bdf4.png)

## Expected behavior

The model should only rotate when articulated hands actually focuses on the collider of the cube.

## Your Setup (please complete the following information)

- Unity Version 2018.4.5
- MRTK Version Stabilization branch

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by killerantz** [comment]
@Troy-Ferrell  and I could not repro this in development or release branches, closing.
