### ISSUE TITLE
GazeProvider is not able to be implemented as editor UI Indicates, and it's impossible to define your own GazePointer

### ISSUE THREAD

**Issue by Kjakubzak** [microsoft/MixedRealityToolkit-Unity#5545]
## Describe the bug

Right now, you are not able to properly define and set your own IMixedRealityGazeProvider in the pointer configuration. The FocusProvider implementation takes the passed in IMixedRealityGazeProvider and then casts it to the GazeProvider in UpdateGazeProvider() to call  .UpdateGazeInfoFromHit(). This causes problems for a IMixedRealityGazeProvider that's not the MRTK-defined GazeProvider.

## To reproduce

1. Write a new GazeProvider that implements the IMixedRealityGazeProvider class
2. Assign the new implementation to the GazeProvider option in the Pointer profile 
3. Click play, and see the casting exception occur

![image](https://user-images.githubusercontent.com/1617757/62663010-d41dd280-b92a-11e9-9169-56812d25f3df.png)

## Expected behavior

It doesn't throw an exception and allows you to have your own implementation of the GazeProvider. 

Also, being able to implement your own GazePointer and provide that to the GazeProvider seems like a feature that's missing; given that user-defined pointer definition is available for all other pointer types.
 
## Your Setup (please complete the following information)

- Unity Version 2018.4.4f1
- MRTK Version - mrtk_development - 2.0.0-20190730.2

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

## Additional context

Spoke to @wiwei and @keveleigh about this already and just wanted to immortalize it in bug form.

**Comment by keveleigh** [comment]
Fixed via #5610. Opened https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5612 to track custom gaze pointers
