### ISSUE TITLE
ManipulationHandler's TwoHandMoveLogic doesn't properly adjust to the ConstraintOnMovement public field changing (indicating intent to change the type of movement)

### ISSUE THREAD

**Issue by Kjakubzak** [microsoft/MixedRealityToolkit-Unity#5546]
## Describe the bug

Currently, if the user is trying to trigger far-field manipulations using the gaze pointer + ManipulationHandler and have defined the ConstraintOnMovement type as not being "FixDistanceFromHead" in the scene, the move logic's update function causes NaN errors to pop up. 

This is due to line 63 in TwoHandMoveLogic; which tries to recalculate the distance ratio based on the current hand distance (which is 0 since this is done by a gaze-driven pointer).

 A simple workaround to this issue would be to allow for dynamic setting of the ConstraintOnMovement variable that the TwoHandMovementLogic would respect when its Update function is called; much like it is for rotation constraint when the TwoHandRotationLogic Update function is called.

## To reproduce

1. Create an object with a ManipulationHandler object, where the constraint on movement option is anything but the "FixDistanceFromHead" type. 
2. Stare at the object, and using a voice command, spoof some pointer events (Down and Dragged) and utilize the gaze pointer as the pointer for those events to respect.
3.  See resulting NaN error

## Expected behavior

The ManipulationHandler

## Screenshots

ManipulationHelper settings the MoveConstraint type on Awake():
![image](https://user-images.githubusercontent.com/1617757/62663544-c701e300-b92c-11e9-9182-eb5a3f6aaba6.png)

TwoHandRotateLogic function parameters:
![image](https://user-images.githubusercontent.com/1617757/62663517-a6398d80-b92c-11e9-95a2-9772db697297.png)

TwoHandMoveLogics function parameters:
![image](https://user-images.githubusercontent.com/1617757/62663500-8f933680-b92c-11e9-859f-ead478e7eecc.png)

## Your Setup (please complete the following information)

- Unity Version 2018.4.4f1
- MRTK Version 2.0.0-20190730.2

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

## Additional context

Spoke to @keveleigh about this, and since it's a small change and I know what needs to be done, I'll be making the changes for it.

**Comment by keveleigh** [comment]
Fixed via #5554
