### ISSUE TITLE
ManipulationHandlerOriginOffset test has race condition causing unpredictable failures

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#5552]
## Describe the bug

Running ManipulationHandlerOriginOffset locally in different branches, I get consistently get inconsistent success/fail results. There is a failure for checking the position of the expected vs actual data components at the very end of the test.

Not exactly sure what is going on but I believe it is causing the CI failures intermittently 

## To reproduce

In Test Runner, just run selected multiple times and get different results

## Expected behavior

This should pass 100% of the time predictably. 

## Your Setup (please complete the following information)

- Unity Version 2018.4.5
- MRTK Version Stabilization branch

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Kjakubzak** [comment]
I've also encountered this on the mrtk_development branch, It seems to be non-deterministic. I'm verifying my changes for a PR I'll be putting out today, and it seems like it fails [3-5]/10 times it is run in the mrtk_development branch.
 
The errors aren't consistent, and sometimes only puts out a position error, and other times will spit out a huge log of errors like so:
 
```

Failed for position of object for one hand rotate near, expected (0.000, 0.000, 1.000), was (0.016, -0.049, 1.014)
Failed for rotation of object for one hand rotate near, expected (0.000, 0.000, 0.000, 1.000), was (0.462, 0.191, 0.191, 0.845)
Failed for position of object for two hand rotate/scale near, expected (0.000, 0.000, 1.000), was (-0.041, 0.041, 1.008)
Failed for rotation of object for two hand rotate/scale near, expected (0.000, 0.000, 0.000, 1.000), was (0.000, 0.000, 0.241, 0.971)
Failed for scale of object for two hand rotate/scale near, expected (0.200, 0.200, 0.200), was (0.480, 0.480, 0.480)
Failed for position of object for two hand rotate/scale far, expected (0.000, 0.000, 1.000), was (0.015, 0.055, 1.436)
Failed for rotation of object for two hand rotate/scale far, expected (0.000, 0.000, 0.000, 1.000), was (0.000, 
Failed for scale of object for two hand rotate/scale far, expected (0.200, 0.200, 0.200), was (1.079, 1.079, 1.0
Failed for position of object for one hand rotate far, expected (0.000, 0.000, 1.000), was (0.709, 0.006, 0.709)
Failed for rotation of object for one hand rotate far, expected (0.000, 0.000, 0.000, 1.000), was (0.000, 0.383, 0.000, 0.924)
```

**Comment by Troy-Ferrell** [comment]
For stabilization branch, looks like BoundingBoxTests.ScaleViaHoloLens1Interaction may need to be added to the list as well. Although harder to notice? succeeded 7/8

**Comment by Troy-Ferrell** [comment]
@CDiaz-MS and @davidkline-ms FYI

**Comment by CDiaz-MS** [comment]
Adding in a WaitForSeconds in ManipulationHandlerOriginOffset() seems to decrease the frequency of failures but not solve it completely

```
            for (int i = 0; i < vertices.Length; i++)
            {
                vertices[i] += offset;
            }
            mesh.vertices = vertices;
            mesh.RecalculateNormals();
            testObject.GetComponent<BoxCollider>().center = offset;

            testObject.transform.position = Vector3.forward - testObject.transform.TransformVector(offset);

            yield return new WaitForSeconds(1);

            // Collect data for modified cube
            OriginOffsetTest actualTest = new OriginOffsetTest();
            yield return actualTest.RecordTransformValues(testObject);
            yield return null;
```

**Comment by julenka** [comment]
This test is failing even when you do not modify the vertices to offset them from the origin. In other words, if you move and record positions of a cube, then reset that cube, then move and record the positions again, they do not match.
