### ISSUE TITLE
Interactable throws error for onFocus event with selected toggle buttonmode

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#5553]
## Describe the bug

Interactable will throw an assertion fail for all OnFocusEnter calls if the OnBeforeFocusChange fails with CanInteract(). 

OnBeforeFocusChange is called which returns early because CanInteract() returns false because of some logic I don't understand fully. Since OnBeforeFocusChange returns early, the focusingPointers is never set properly and thus the following event call to OnFocusEnter right after, throws an error

Inside Interactable.cs
```csharp
       public void OnFocusEnter(FocusEventData eventData)
        {
            Debug.Assert(focusingPointers.Count > 0,
                "OnFocusEnter called but focusingPointers == 0. Most likely caused by the presence of a child object " +
                "that is handling IMixedRealityFocusChangedHandler");
```

Thanks to @KevinKennedy for discovery!

## To reproduce

This seems to primarily occur with Toggle interactable buttons, most likely using the InteractableToggleCollection? 

For a good repo, do the following

1) Open the SolverExample scene (at least in stabilization branch)
2) Press space to get input simulated hand
3) Hover over the "RadialView" interactable button with it already selected
4) See error message in console

## Expected behavior

Users should be able to focus on a selected toggle interactable without errors in console

## Your Setup (please complete the following information)

- Unity Version 2018.4.5
- MRTK Version Stabilization branch 2.0.0

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by julenka** [comment]
Thanks for the great repro steps!
