### ISSUE TITLE
UnityMouseDeviceManager needs improvement and bug fix

### ISSUE THREAD

**Issue by benjamincoven** [microsoft/MixedRealityToolkit-Unity#5566]
## Describe the bug

Hello, I tried the mouse device manager from the MRTK and it's not usable as it is. Here some of the problems I got:

- The cursor is way too big, it should be the same size as the real cursor
- The cursor is invisible when we are not over an object
- The cursor position is not the same as the real cursor position
- When we stop moving the mouse for few seconds, the cursor disappear and its position change
- The cursor is not oriented towards the camera but seems to follow the normal of the collider that we are pointing at
- The crusor shakes a lot, it is not smooth at all

Here a screenshot of my profiles:

![image](https://user-images.githubusercontent.com/12698212/62780917-107e3980-bab7-11e9-9738-e6544c7d055c.png)

Here some screenshots to illustrate the problems, note that the third media is not a zoom of my screen, it's simply the MRTK camera that is very very close to the button.

![3](https://user-images.githubusercontent.com/12698212/62780976-373c7000-bab7-11e9-89ef-8ea82a79b65c.png)

![2](https://user-images.githubusercontent.com/12698212/62780989-3c99ba80-bab7-11e9-95e6-c62244bcc83d.gif)
![1](https://user-images.githubusercontent.com/12698212/62780993-3efc1480-bab7-11e9-850f-cf3fb53b4b91.gif)

## To reproduce

Create a default MouseInput profile and add a Mouse device manager to the MRTK

## Expected behavior

The MRTK cursor behaviour is the as the windows cursor

## Your Setup (please complete the following information)

- Unity Version 2019.1
- MRTK Version RC2.1

## Target Platform (please complete the following information)

- Desktop

**Comment by benjamincoven** [comment]
I was able to fix some of the issues by tweaking the MousePointer prefab and some components:

- The cursor is invisible when we are not over an object: Set the MeshCursor.DefaultCursorDistance on the gameobject Any_Spatial Mouse Pointer_Cursor to a lower value (1 or 2).

- When we stop moving the mouse for few seconds, the cursor disappear and its position change: Set the MousePointer.HideCursorWhenInactive to false on the gameobject Spatial Mouse Pointer

- The cursor is not oriented towards the camera but seems to follow the normal of the collider that we are pointing at: Set the MeshCursor.LookRotationBlend to 1 on the first gameobject


Maybe these settings should have these values by default? I am still looking for the other problems.

**Comment by benjamincoven** [comment]
The biding of the delta mouse position to the delta cursor depends of the camera rotation. At default rotation there is no problem but for exemple, turning for Y = 180, inverts the Y mouse axis.

**Comment by benjamincoven** [comment]
Also the bounding box behaviour is very strange with the mouse pointer.

**Comment by wiwei** [comment]
@davidkline-ms @keveleigh

**Comment by benjamincoven** [comment]
I was able to have something working good by highly and dirtly modifying the MRTK code, I let you choose to close or not this issue. And if you want I share you some stuff let me know.

**Comment by davidkline-ms** [comment]
The pointer size is controlled by the MouseCursor prefab and can be scaled there. I will investigate a better default scaling.

**Comment by davidkline-ms** [comment]
@benjamincoven, please do share your changes. We would love to see if your modifications can be applied in a way that will be helpful.

**Comment by davidkline-ms** [comment]
> I was able to fix some of the issues by tweaking the MousePointer prefab and some components:

Many of these settings are planned to be added to the mouse profile as part of the changes to address #5838

**Comment by davidkline-ms** [comment]
> turning for Y = 180, inverts the Y mouse axis.

This was also reported as #5793 and will be also be fixed as part of the changes for #5838.

**Comment by davidkline-ms** [comment]
After looking into this some more, i will be opening a proposal to add optional profiles to the pointers themselves. This would allow for greater configuration discoverability and ease of swapping settings.

**Comment by benjamincoven** [comment]
Thank you very much for your help (and sorry for my response time I was on vacation :p).

Concerning my dirty modifications, I take the side to use directly the cursor instead of the MRTK cursor system that uses the delta mouse to create a rotation.

I disabled the mesh cursor and enabled the UnityEngine.Cursor.visible .

I changed the MousePointer.OnPreSceneQuery like this:

```
Ray ray = CameraCache.Main.ScreenPointToRay(Input.mousePosition)
ray.direction = ray.direction * 10; //TODO change with pointer profile setting
RaycastHit raycastHit;
Physics.Raycast(ray, out raycastHit);
if (raycastHit.transform == null)
{
    raycastHit.point = ray.origin + ray.direction;
}
Rays = new RayStep[1];
```
I need also to disable the transform computations in this class and I still have to check some things before writting it here.

Changing some prefabs (like the one you mentionned) was also necessary.

I consider this as dirty since it doesn't use at all the MRTK pointer system, but the mouse cursor directly. However, doing this solve many problems and the code is simpler.

Also what would you advise to me? Keep working on my way or wait any updates on the MRTK? Our customer is urged.

Thank you!

**Comment by Alexees** [comment]
You might want to have a look at the ScreenSpaceMousePointer.
Just replace the MousePointer with it in the MRKT Input -> Pointer profile.
I also got annoyed by the unnecessary overhead of the 3D cursor so I created it. Basically gives you the desktop cursor back.

**Comment by anxious-pineapple** [comment]
> 
> 
> You might want to have a look at the ScreenSpaceMousePointer.
> Just replace the MousePointer with it in the MRKT Input -> Pointer profile.
> I also got annoyed by the unnecessary overhead of the 3D cursor so I created it. Basically gives you the desktop cursor back.

Hey, could you be a little more elaborate ? What exactly did you do? Couldn't find any ScreenSpacePointer. Thanks!
