### ISSUE TITLE
Green Gem in HandInteractionExample will immediately scale the mesh down on interaction

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#5569]
## Describe the bug

Transform Scale Handler is using the wrong scale values

## To reproduce

Open HandInteractionExample scene
Try to far manipulate the green gem on the left side
Observe it snaps to a lower scale
![image](https://user-images.githubusercontent.com/36998103/62797496-ca839e80-bad3-11e9-8e96-293623334172.png)

## Expected behavior

Gem should keep it's size until it gets scaled.
Gem setup should define max / min bounds that include the initial setup

## Your Setup (please complete the following information)

MRTK stabilization 2.0.0
tested with WMR controller far interaction

**Comment by cre8ivepark** [comment]
@thalbern  I found that the slate with MRTK logo has the same symptom

**Comment by thalbern** [comment]
the problem with the gem is that the bounding box is referring to the gem gameobject itself and the manipulationhandler points to the parent gameobject including the buttons - AND that in combination with the Transform Scale Handler simply doesn't work because it will cause a conflict.

Transform Scale Handler will apply the min max scaling relative to the transform of the gameobject it's referring to. however if both of those components (manipulationhandler and boundingbox) are attached and point to different objects they will fight against each other. 

A possible solution is to move manipulation handler to the parent gameobject and have another Transform scale handler there - then it's well defined in both cases which max / min to take and also makes more sense to do it that way bc we want to include the buttons in the manipulationhandler case

**Comment by thalbern** [comment]
@MenelvagorMilsom fyi

**Comment by keveleigh** [comment]
@thalbern Is this a side effect of https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5544 or has it been this way?

**Comment by cre8ivepark** [comment]
@thalbern Confirmed, simply assigning the same Platonic to the ManipulationHandler fixes the problem. The MRTK logo slate's ManipulationHandler was missing transform. same solution works.
<img width="292" alt="2019-08-09 10_57_24-Unity 2018 4 5f1 Personal - HandInteractionExamples unity - MRTK0809 - Universal" src="https://user-images.githubusercontent.com/13754172/62798992-8329ed80-ba94-11e9-9178-e7a605f86edf.png">

**Comment by davidkline-ms** [comment]
fixed in stabilization. will be in mrtk_development after next bulk merge

**Comment by thalbern** [comment]
thanks @cre8ivepark !
