### ISSUE TITLE
Performance drops to 45fps on one hand detected, after a lot of manipuation. Drops to 22 fps on two hands detected.

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#5572]
## Describe the bug
After a lot of manipulation interaction (one or two-handed), the Profiler shows the framerate drop to 45fps on two hands detected even there are no objects in the viewport. (no hand mesh/joint)
Presenting a single hand seems fine (60fps). Only drops when both hands are detected.

After pausing and restarting the app and manipulating the HL2 style bounding box, then bringing up a single hand can cause the framerate to drop to 45 fps, and bringing up 2 hands causes frame rate drop to 22 fps.

## To reproduce
In the HandInteractionExample scene, keep interacting with the objects with ManipulationHandler and BoundingBox. Use two-handed manipulation for scaling/rotating.

## Expected behavior
No framerate drop

## Your Setup (please complete the following information)
- Unity Version 2018.4.

## Target Platform (please complete the following information)
- HoloLens 2

## Branch
- prelease

**Comment by Troy-Ferrell** [comment]
This behavior is also pretty noticeable in Unity editor on desktop. Looking quickly into the Unity profiler, these are the bigger hitters that start taking up computation on hands shown (Input simulation Hands)

BoundingBox (Multiple instances) -> Update()
MRTK.Update() -> Huge increase
MRTK.LateUpdate() -> Huge increaase
Physics->Processing

**Comment by davidkline-ms** [comment]
Is this a recent regression?

**Comment by Troy-Ferrell** [comment]
@davidkline-ms hard to fully say. The BoundingBox isn't recent and I believe was part of #4895 . The MRTK update and MRTK late update may have been there a while too. Haven't investigated yet

**Comment by Troy-Ferrell** [comment]
The MRTK update with hands appears to be mostly in UpdatePointers(), and in particular the Graphics raycast for every pointer Ray step is very expensive

DefaultControllerPointer has 2 rays instead of just one but setting to 1 breaks Unity UI slider?

**Comment by wiwei** [comment]
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5615
