### ISSUE TITLE
Normal Maps + Proximity Light Causes Shader Compilation Failure

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#5573]
## Describe the bug

When enabling Normal Maps and Proximity Light on a MRTK/Standard material the MRTK/Standard shader fails to compile.

## To reproduce

1. Select a MRTK/Standard material.
2. Enable the Normal Map and Proximity Light features.
3. See compilation error in the console.

## Expected behavior

Shader compiles with all feature permutations.

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1
- mrtk_development

## Target Platform

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by davidkline-ms** [comment]
fixed in stabilization. will get to mrtk_development with the next bulk merge

**Comment by Cameron-Micka** [comment]
Thank you!
