### ISSUE TITLE
MRTK Windows should be under the Window menu

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#5574]
## Describe the problem

The last few times I've gone looking for the Build Window, my first instinct has been to check under the built-in Unity Window menu:

![image](https://user-images.githubusercontent.com/3580640/62797463-a94d8e80-ba90-11e9-950f-97603797da22.png)

Instead, they're under a custom Mixed Reality Toolkit menu:

![image](https://user-images.githubusercontent.com/3580640/62797412-8327ee80-ba90-11e9-94e4-224c086fbda5.png)

## Describe the solution you'd like

I think it would be more intuitive for these to be under an MRTK subheading of the Window menu, like (but better placement):

![image](https://user-images.githubusercontent.com/3580640/62798207-976ceb00-ba92-11e9-8671-72aeaafca7a1.png)

## Additional context

Looking for feedback and other opinions here :)

**Comment by polar-kev** [comment]
@keveleigh can we close this given https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9649
![image](https://user-images.githubusercontent.com/30964480/125333983-b66bfb80-e2ff-11eb-8b1d-c49f919046d8.png)

**Comment by keveleigh** [comment]
@polar-kev I'd say they're slightly different, if we wanted to have these options in both places (under Mixed Reality and under Window) for maximum discoverability. I'm fine with closing this though if we don't want to make this change!

**Comment by saed219** [comment]
Q

**Comment by polar-kev** [comment]
@keveleigh I like that options/windows added by MRTK are all under the Mixed Reality dropdown because it makes it clear that they were added to the project and not part of native Unity.

**Comment by keveleigh** [comment]
Works for me!

**Comment by saed219** [comment]
E
