### ISSUE TITLE
Start push distance is wrong for all buttons

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5576]
## Overview
All hololens 2 buttons should begin to compress immediately as the finger tip touches the button surface. Currently, the finger needs to go at least half way through the button before the button begins to compress.

## Steps to reproduce
In the editor, press a button and observe where the finger is when the button starts moving.

![image](https://user-images.githubusercontent.com/168492/62799157-ee73bf80-ba94-11e9-930c-1764f6c7a721.png)

You can also observe this by looking at the press planes of the button (select button component then inspect in scene view. Ensure "Show Button Event Planes" is checked. Noticethat the start push distance is half way into the button:

![image](https://user-images.githubusercontent.com/168492/62799189-077c7080-ba95-11e9-9dc6-6a8cdbea2e82.png)

## Expected Behavior
The start push plane should be at the beginning of the button cage, the button should start moving as soon as the finger touches the cage.

**Comment by Troy-Ferrell** [comment]
@julenka Sorry, when I updated the buttons I just tested functionality and didn't look at finese also not realizing this was desired behavior. 

For defaults for PressableButton, can we also review so they make more sense as starting point?

And is there any way to create an auto-place feature that sets the plane distance based on our "golden" ratios?

**Comment by cre8ivepark** [comment]
@Troy-Ferrell @julenka It seems like with the code updates, PressableButtonHoloLens2's Start Push distance cannot be 0. I tried adjusting the planes and ended up with the following values. Updated both HoloLens 2 buttons and Round buttons.

![2019-08-09 22_04_21-Unity 2018 4 5f1 Personal - PressableButtonExample unity - MRTK - Universal Wind](https://user-images.githubusercontent.com/13754172/62818025-8b664500-baf5-11e9-81de-9b02d82f6e1b.png)

<img width="422" alt="2019-08-09 11_08_24-Unity 2018 4 5f1 Personal - PressableButtonExample unity - MRTK0809 - Universal " src="https://user-images.githubusercontent.com/13754172/62800003-1d8b3080-ba97-11e9-8f17-497c3e81a373.png">

![2019-08-09 22_11_01-Unity 2018 4 5f1 Personal - PressableButtonExample unity - MRTK - Universal Wind](https://user-images.githubusercontent.com/13754172/62818033-be103d80-baf5-11e9-95f6-28e9912c25e8.png)

**Comment by julenka** [comment]
@cre8ivepark and @thalbern  is this done? If so, please close it.

**Comment by davidkline-ms** [comment]
@julenka, this is reported as fixed in #5577

**Comment by umaknow-manu** [comment]
Hi, I have a similar problem where if the button is pressed in far interaction mode and call an event that SetActive(false) the button (or a parent), the button will be stuck at the "half postition" mentionned above when re-enabled. Should I open a new bug report for this ?

**Comment by julenka** [comment]
>Hi, I have a similar problem where if the button is pressed in far interaction mode and call an event that SetActive(false) the button (or a parent), the FrontPlate cover GameObject will be stuck at the "half postition" mentionned above when re-enabled. Should I open a new bug report for this ?

Hi @umaknow-manu thank you for reporting your issue. Yes this sounds like a different bug, please open a new issue. Ping @CDiaz-MS and @thalbern  for awareness.
