### ISSUE TITLE
HoloToolkit Branding

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#558]
Hi everyone,

I wanted to open this issue to discuss branding for the HoloToolkit.
I'm mainly interested in getting concepts for iconography and images for use in the Unity Asset store, on HTK specific assets in the Unity Editor Inspector windows, and for invisible objects in the scene.

![image](https://cloud.githubusercontent.com/assets/13334553/23824794/39c7c0cc-064b-11e7-8414-0cc704c751db.png)

[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/NISY5Crstio/0.jpg)](http://www.youtube.com/watch?v=NISY5Crstio)

**Comment by jessemcculloch** [comment]
I think this is an excellent idea... but it seems like we need some sort of a HTK logo...
Maybe the same one used in the Holographic Remoting tool??  The head with HoloLens...

**Comment by StephenHodgson** [comment]
Yeah I figured this would be up to MSFT to figure out, but maybe someone in the community will sketch something neat up?  Who knows.
