### ISSUE TITLE
UnityUI is missing shadow and sounds (slate parity issue)

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5587]
## Overview
UnityUI is one of our top-used UI components, but it is not at shell parity. It is missing a shadow, as well as sounds on touch down and up. Sounds exist when pressing buttons and moving sliders, but not when touching the back panel to scroll.

## Steps to reproduce
Touch the unityui component with a hand, either in editor or on device.

## Expected Behavior
The expectation is that the visuals and sounds match the behavior in the "Pan & Zoom Interaction" slate on the left side of interaction examples.

1) There should be a shadow to help with targeting and knowing proximity of hand to surface
2) There should be a sound on touch down and on touch up, even when interacting with the back panel of Unity UI.

**Comment by Cameron-Micka** [comment]
I can add the shadow real quick!

**Comment by davidkline-ms** [comment]
fixed in stabilization. will be in mrtk_development after next bulk merge
