### ISSUE TITLE
HoloLensCamera.prefab Gaze Controls: Joystick Axis Controllers' Input Axis not setup

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#559]
Joystick Gaze Controllers on the `HoloLensCamera.prefab` have not had their Input Axis' set up in the Input Settings.

**Comment by jasonhbartlett** [comment]
Just ran into this problem.  Is there a work around?  I prefer to use a gamepad when testing in the editor.

**Comment by StephenHodgson** [comment]
No workaround but to set them up. haha.  I had been working on this a bit, but didn't get a chance to finish.

https://github.com/StephenHodgson/HoloToolkit-Unity/tree/HTK-JoystickInput

**Comment by jasonhbartlett** [comment]
You're amazing.  I out of my depth on this and don't have a lot of time.  Hence dumb questions following: How did it work in the old HTK versions?  Both AxisController.cs and Project Settings>Input look identical.   Looked at that branch and see JoystickControl.cs and JoystickController.cs ... is the latter just for XBO S bluetooth controller?  I'm just using a crappy USB XB Afterglow controller.  Should I try that branch, or wait for Your Awesomeness :) to finish and just keep using old HTK for now.  (Or I could just get used to the keyboard inputs.  :)

**Comment by StephenHodgson** [comment]
I don't remember the last time I updated it.  So YMMV.  I was using the XBO S bluetooth controller.

**Comment by jasonhbartlett** [comment]
Cool, I'll play with it if I find the time.

**Comment by jasonhbartlett** [comment]
I hate to drag this issue back up again after so long, so my apologizes in advance.  I'm not super proficient with how the Unity input was supposed to work and so with versions 5.6 and previous I always just took it for-granted that when working in the editor my RIGHT Thumb Stick 4th and 5th axis was able to control the look rotation of the HoloLens camera.  However now that I understand these kinds of inputs are supposed to be setup in the Unity Properties>Input, when I look there don't see the 4th and 5th axis mapped to anything!!??  So how was/is this working?  I've been search through all the HTK scripts and can't find any reference to the 4th and 5th axis.  I've even tried breaking it by deleting the AxisController.cs, ManualGazeControl.cs, ManualHandControl.cs, and EditorHandsInput.cs and my app still runs perfectly fine in the editor and I can rotate using the right thumb stick!  I'm so confused!

**Comment by StephenHodgson** [comment]
The Xbox support can be enabled in the HoloToolkit/Configure/Apply Project Settings window

**Comment by StephenHodgson** [comment]
When enabled it'll automatically download and update your input manager asset with the correct mappings

**Comment by jasonhbartlett** [comment]
Oh Splendid!  I just tested this in 2017.1.1 using an Example Scene and it worked!  Sweet!  Thank you so much!  I can't imagine testing my app without use of the controller.   I'm super happy right now!

BTW - Any idea how to suppress this error in the console? 
"RenderTexture.GenerateMips failed: render texture does not have mip maps (set useMipMap to true)."
I know this is a Unity bug...but it makes the console useless.

**Comment by StephenHodgson** [comment]
It'll close once I merge the PR.  Please review it.
