### ISSUE TITLE
Using MRTK/Standard Shader results in pink materials

### ISSUE THREAD

**Issue by Grubzyy** [microsoft/MixedRealityToolkit-Unity#5599]
## Describe the bug

Materials using the MRTK Standard shader are pink.

## To reproduce

**For a new project**
   1. Start a new 3D project.
   2. Import RC2.1.
   3. Create a material and set it's shader to "MRTK Standard".
   4. Pink.

**For MRTK Release**
   1. Download MRTK release from GitHub
   2. Open Project in Unity 2018.4.5f1
   3. Materials using MRTK Standard shader are pink.

## Expected behavior

Materials using the MRTK Standard shader should not be pink.

## Screenshots

![image](https://user-images.githubusercontent.com/54028320/62865758-2da94700-bd07-11e9-8ab3-4cad613d58e4.png)
![image](https://user-images.githubusercontent.com/54028320/62866386-8f1de580-bd08-11e9-8658-13f743a706d3.png)

![image](https://user-images.githubusercontent.com/54028320/62866348-7d3c4280-bd08-11e9-93da-2c4739b6f682.png)

## Your Setup

- Unity Version 2018.4.5f1
- MRTK Version v2.0.0 RC2.1
- VS 2019

## Target Platform

- HoloLens
- Target SDK 10.0.18362.0

## Additional context

The pink materials don't show any missing references to shaders and the shader doesn't seem to have any compile errors.

**Comment by wiwei** [comment]
@Cameron-Micka

We saw another report of this a while back, but it got resolved when the person updated to the latest:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4873

According to the repro steps above, it looks like you are on latest. Out of curiousity, what version of windows are you on (i.e. when you run "winver" what does it show you?). Were there any other errors in the console?

**Comment by Cameron-Micka** [comment]
Hi @grubzyy this hints that the shader failed to compile, can you post your console output? Any shader compilation errors should appear there. Also, are you running Parallels or any other virtual machine/emulation to run Windows?

**Comment by Grubzyy** [comment]
Thanks for the response. I've tried different versions of Unity and MRTK(including the latest) and it gives the same results.

I'm using Version 18039(OS Build 17134.885) on a virtual machine.
![image](https://user-images.githubusercontent.com/54028320/62877323-aec00880-bd1e-11e9-985f-1340ef4cab88.png)

Below is a screenshot of the console after a successful UWP build.
![image](https://user-images.githubusercontent.com/54028320/62878179-7b7e7900-bd20-11e9-8c85-172547d2ed4d.png)

**Comment by Cameron-Micka** [comment]
> I'm using Version 1803(OS Build 17134.885) **on a virtual machine.**

I think the virtual machine may be the issue, I've seen some issues around VMs not emulating some D3D features quite right. Out of curiosity, could you open the MixedRealityStandard.shader file and comment out anything between the SHADER_API_D3D11 preprocessor directives? Does this fix the pink issue?

`#if defined(SHADER_API_D3D11)`
// Comment all of this out.
`#endif`

I've seen this fix an compilation error that the shader compiler wasn't generating any errors for, but failed to render on VMs.

**Comment by Grubzyy** [comment]
> `#if defined(SHADER_API_D3D11)`
> // Comment all of this out.
> `#endif`

Yes, that fixed the pink issue. Thank you!

**Comment by Cameron-Micka** [comment]
That's great to know! Thank you Grubzyy. I'll reach out to Unity and see if they have seen this issue too on VMs.

**Comment by Grubzyy** [comment]
Great! Let me know if you need any more info from my end.
