### ISSUE TITLE
Flickering texture in Bounding Box example

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#5602]
## Describe the bug

Go through the BoundingBoxRuntimeExample and observe the flickering Cyan Material applied in one of the later steps of the example (cycle through steps by pressing 1)

## To reproduce

Open BoundingBoxRuntimeExample
Press 1 to advance in the steps
Step that changes material to cyan will cause the bounding box to flicker

## Expected behavior

Bounding box shouldn't flicker

## Screenshots

![cyan_material](https://user-images.githubusercontent.com/36998103/62877375-cac3aa00-bd1e-11e9-8644-3d8ab0e4f71f.gif)

## Your Setup (please complete the following information)

- stabilization drop 2.0.0 from 08-10-2019

## Target Platform (please complete the following information)

- WMR immersive
- Unity Editor

**Comment by Troy-Ferrell** [comment]
@thalbern  I don't see flickering in latest stabilization. But the transform override seems wrong?
![bb-error](https://user-images.githubusercontent.com/25975362/62980582-d628db00-bddb-11e9-800d-feda54acc965.gif)

**Comment by Troy-Ferrell** [comment]
No longer repos
