### ISSUE TITLE
Nullptr in Overlap.SolverUpdate after Upgrade from RC2 to G1

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5604]
## Overview
After I updated my personal project from RC2 to GA, I am getting NullPtr every frame when I hit "Play" in my sample scene

## Repro steps
1. Unzip the project Assets folder located [here](https://microsoft-my.sharepoint.com/:u:/p/jschwarz/EXlokMtzbbxArfKNoRsVOO0BgFfKuW6hGDh3K0H68sUOUQ?e=kjyzpO), move it to a new test project
2. Open the project, then open the BouncyBall/SampleScene.unity scene, and then hit play

You will get a large number of errors like:

    NullReferenceException: Object reference not set to an instance of an object
    Microsoft.MixedReality.Toolkit.Utilities.Solvers.Overlap.SolverUpdate () (at Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/Overlap.cs:13)
    Microsoft.MixedReality.Toolkit.Utilities.Solvers.Solver.SolverUpdateEntry () (at Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/Solver.cs:245)
    Microsoft.MixedReality.Toolkit.Utilities.Solvers.SolverHandler.LateUpdate () (at Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/SolverHandler.cs:326)

This project contains my old project (all my files are in the BouncyBall folder), plus the new MRTK GA release (in the other MRTK folders). All MRTK files have been updated to their newer version, except PinchSlider.cs

## Expected Behavior
The expectation is to not get any errors.

## Unity Editor Version
2018.4.4f1

## Mixed Reality Toolkit Release Version
GA

**Comment by julenka** [comment]
Assigning to Troy since he has been modifying solvers recently.

**Comment by davidkline-ms** [comment]
I'll pitch in and investigate while @Troy-Ferrell works on #5572
