### ISSUE TITLE
Override ArticulatedHand/Joint transforms

### ISSUE THREAD

**Issue by derekfreed** [microsoft/MixedRealityToolkit-Unity#5605]
## Describe the problem

I need to be able to modify where a user's digital hands appear including the position, rotation, and scale. I have use cases where the user needs to be able to do touch interactions from a distance and even have larger hands than they have in reality.

## Describe the solution you'd like

As a developer I want to be able to override the position, rotation, and scale of HoloLens 2's digital hands. I think this is possible by making a custom class using WindowsMIxedRealityArticulatedHand as the base.

## Additional context

Here's an example of the hack I made to do positional offset along the pointer ray.

![GoGoGadgetHands](https://user-images.githubusercontent.com/10147303/62881546-deeab580-bce4-11e9-8087-6b5e5aa0c8ae.gif)

Note: In the hack I didn't bother offsetting the Hand Visuals as well but that would be desirable.

My branch with the hack: https://github.com/derekfreed/MixedRealityToolkit-Unity/tree/dev/GoGoGadgetHands

**Comment by polar-kev** [comment]
Cool idea. We are exploring other ways to interact with objects that are really far, really large and really small, in a way that still feels natural.
