### ISSUE TITLE
Allow defining a custom GazePointer

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#5612]
## Describe the problem

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5610#discussion_r313096956

> While being able to define your own GazeProvider means you also are able to define your own InternalGazePointer; it isn't very easily discoverable.

Related to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5545

>Also, being able to implement your own GazePointer and provide that to the GazeProvider seems like a feature that's missing; given that user-defined pointer definition is available for all other pointer types.

**Comment by ericob** [comment]
Following up with Ken to see if there's anything else here we need
