### ISSUE TITLE
SharingService.exe running on Azure IaaS

### ISSUE THREAD

**Issue by doughjoe77** [Microsoft/MixedRealityToolkit-Unity#562]
Hi,

I'm trying to get the SharingService to run on an Azure IaaS.  I've tried the following:

- Created the IaaS in the new Azure portal

- Opened up Firewall rules for ports 20601 and 20602

- copied the executable from the Unity Folder and ran it like this "SharingService -local"

This works for me when I run it on my local wireless network (tried with 2 HoloLens with demo code from https://developer.microsoft.com/en-us/windows/holographic/holograms_240), but, I want a more stable place in the cloud to continue my testing and demoing of a shared holographic experience.

Thanks!

Joe

**Comment by Mandur** [comment]
Hello Doug,

I did the same manipulation as you described and it worked for me. Quick question, did you opened up the ports on the Windows server firewall? Is your VM deployed with a Network Security group (NSG) component as shown below? 
![image](https://cloud.githubusercontent.com/assets/8555833/24928323/5d4c0c40-1f02-11e7-8818-c5ddb16f8520.png)
In this case, you might want to either delete the NSG or to also add the ports to pass through it as explained [here](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-create-nsg-arm-pportal#create-rules-in-an-existing-nsg)

Hope this helped

Mikhail

**Comment by RussellXie7** [comment]
Hey how did you get it to work? I am doing the samething on google cloud platform. I opened up firewall rules, and execute the sharing service with ./SharingService.exe -local, but even if the terminal shows Created Session, I could still not be able to connect Hololens to the server.

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
