### ISSUE TITLE
LinePointer is overly expensive

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#5620]
## Describe the bug

The LinePointer class is used for hand rays but executes expensive ray marching every frame. The line pointer class is written to support multiple curve types, not just straight lines. This is evident in TeleportPointer extending from LinePointer as well. The problem is even if ShellHandRayPointer which extends LinePointer and only needs to raycast a straight line for the hand ray, will still execute ray marching based on the number of extents in the **rendered** line.

The ShellHandRayPointer has a line that can bend when wobbling or when selecting and pulling like a lasso. The raycast though is still just a straight line. 

In particular, LinePointer generally keeps the bezier line at the PointerExtent distance and then modifies *LineBase.LineEndClamp* normalized length to a value of the raycast hit point when intersecting an object. Thus, the raycast is the full PointerExtent but the rendered line only goes to the hit object. 

Setting this *LineBase.LineEndClamp* is quite expensive because of `lineBase.GetNormalizedLengthFromWorldLength`. This walks down the entire line and performs multiple 1) `linebase.GetUnClampedPoint()` and 2) sqrt distance calculations. This is excedingly expensive especially with two hands accounting for probably 0.25-1ms on device (hard to tell with profiler overhead etc)

## To reproduce

Read OnPreSceneQuery and OnPostSceneQuery in LinePointer.cs

## Expected behavior

Make LinePointer class just a straight line and make a CurvePointer class that extends from LinePointer. This curve pointer class can support bending curve lasso like pointers such as TeleportPointer. 

The LinePointer would only have to worry about one RayStep

Furthermore, it may be wise to also update TransformPoint and DistortPoint in BaseMixedRealityLineDataProvider to utilize ref struct Vector3 to avoid additional copying between functions.

## Your Setup (please complete the following information)

- Unity Version 2018.4.5
- MRTK Version - Stabilization branch

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by julenka** [comment]
@Troy-Ferrell @thalbern @davidkline-ms  @wiwei thoughts on trying to get this in for 2.3?

**Comment by Troy-Ferrell** [comment]
I started work on this when I opened the issue here:
https://github.com/Troy-Ferrell/MixedRealityToolkit-Unity/tree/users/trferrel/line-pointer-refactor

I remember it turned out to be a bit more difficult than I expected but I don't remember where I left off

**Comment by Railboy** [comment]
@Troy-Ferrell My understanding is that we need the line to bend when focus is locked in order to match the look of the shell. So a straight line won't get the job done. @cre8ivepark Is this correct?

![Bendy](https://user-images.githubusercontent.com/9789716/69463019-72de0b80-0d2f-11ea-9c74-6e4474375fe2.PNG)

**Comment by Troy-Ferrell** [comment]
Yea unfortunately I realized during investigation that we do need a parabolic line on the shellhandraypointer for that lasso effect. But there is still items there to optimize regardless
