### ISSUE TITLE
SpherePointer to cache TryGetNearGraspPoint

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#5621]
## Describe the bug

SpherePointer leverages TryGetNearGraspPoint() for many commonly used properties (i.e IsNearObject and IsInteractionEnabled). These properties are called multiple times which causes the TryGetNearGraspPoint and resulting Physics.CheckSphere to be redundantly called everytime.

## To reproduce

Read SpherePointer.cs => IsNearObject & IsInteractionEnabled

## Expected behavior

For a given frame update, the results of TryGetNearGraspPoint and Physics.CheckSphere could potentially be cached. The checksphere may be problematic if objects are instantiated during an update loop. But the TryGetNearGrapsPoint should not be altering.

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by julenka** [comment]
fixed.
