### ISSUE TITLE
WorldAnchor.isLocated not updated properly 

### ISSUE THREAD

**Issue by Nakda** [Microsoft/MixedRealityToolkit-Unity#563]
Problem: When running the Sharing with UNET example, the anchor debug text (Unity TextMesh object) does not appear at the same location on the clients. Both are in the same room, and the anchor get exported/serialized/imported correctly.

Guessing: From my understanding, WorldAnchor locks an object in the physical world, thus auto-adjusting the unity object's tansform to position it correctly. When exporting it via WorldAnchorTransferBatch, we extract the location information (relative to the real world). By sending this information to clients via a network protocol, clients can see the anchor at the same physical location than the sender does.

If I did not understand this correctly, what is the point of exporting/serializing over network the WorldAnchor ?

**Comment by Ziugy** [comment]
Correct. World Anchors are real-world tracked locations. At times it could be difficult for a multiple HoloLens to agree on the exact real-world location.

Here's some troubleshooting tips for syncing World Anchors that we've been using:
- Clear the spaces on both HoloLens. This can be done in Settings on the device.
- Remap the room. Essentially walk around and look at your room. 30 seconds should be enough for a commonly sized room.
- Avoid capturing dynamic, moving, objects when scanning. Moving objects around in the world while syncing could also introduce issues.

Let me know if this helps!

**Comment by Nakda** [comment]
That is basically how we prepare an important sharing session.

Ideally, it would be great to scan the room with a HoloLens, and lock this spatial mapping down so no further update can be made. Sharing it, or doing the same process with another lens would make the sharing experience more reliant as they would both evolve in the same meshed surrounding.

At the moment, the application often starts with a successful export/serialization/import of the anchor, but they do not appear at the same physical location. Fortunately, most of the time it drifts back to the correct position after a while (not always though).

**Comment by Ziugy** [comment]
One thing to keep in mind is that the device may show that the anchor is synchronized (export/serialized/imported), but that doesn't mean the anchor has been located. You can check this with the anchor's `isLocated` flag. Ideally if this isn't true you could guide the user to look around the room more. Most importantly, with the sharing example, look in the position and direction that the host was looking when the World Anchor was placed.

**Comment by Nakda** [comment]
I am actually checking the `isLocated ` flag as such:

```
private void ProcessWorldAnchor ()
{
    if (m_WorldAnchor == null)
    {
        m_WorldAnchor = GetComponent<WorldAnchor>() ?? gameObject.AddComponent<WorldAnchor>();
    }

    if (m_WorldAnchor.isLocated)
    {
        Debug.Log("WorldAnchor successfully located.");

        ExportWorldAnchor();
    }
    else
    {
        Debug.Log("WorldAnchor attached, but waiting for it to get located.");

        m_WorldAnchor.OnTrackingChanged += OnAnchorTrackingChanged;
    }
}
```

Then, I track the changes as follow:

```
private void OnAnchorTrackingChanged (WorldAnchor self, bool located)
{
    if (located)
    {
        Debug.Log("WorldAnchor is now correctly located.");

        self.OnTrackingChanged -= OnAnchorTrackingChanged;

        ProcessWorldAnchor();
    }
    else
    {
        Debug.Log("WorldAnchor still not located. Keep waiting..");
    }
}
```

Problem is: at first the anchor is not located. Quickly, I reach `WorldAnchor is now correctly located`. But right after, when it calls back  `ProcessWorldAnchor()`, the `isLocated` went back to `false ` so it never calls `ExportWorldAnchor()`.

Even when deleting the current cached space and mapping the environment again before running this code, I get the same result. Any idea why this happen ?

**Comment by Nakda** [comment]
Seems like there is an issue with the `OnTrackingChanged` callback. I placed a `TextMesh` bound to the `WorldAnchor`, which continuously displays the `isLocated` property in an `Update()` loop. Thing is, the `TextMesh` output `true` while the callback is not triggered. 

I am wondering how the `isLocated` can switch from `true` to `false` while `OnTrackingChanged` do not get triggered.

**Comment by Cameron-Micka** [comment]
Hi Nakda,

Your guess about OnTrackingChanged callback getting fired before the isLocated property is set could be accurate. In all of my implementations I always query the located parameter sent into the OnAnchorTrackingChanged event, rather than checking the isLocated property on the WorldAnchor, and everything seems to "work" as expected.

If you can verify that your guess is correct I would recommend filing a bug with Unity since you probably aren't the only person experiencing this.

Thanks,
Cameron

**Comment by Nakda** [comment]
I can now confirm this was the issue. Filed a bug report within Unity, and I would update this post to link the Bug ID in case anyone need to track it.

Even if it won't get fixed because it needs to work this way internally for any reason, I asked them to state it in the documentation.

In the meantime, I recommend anyone working with WorldAnchor not to rely on the internal .isLocated property after a OnTrackingChanged event.

**Comment by Cameron-Micka** [comment]
Excellent, thank you for filing the report!

**Comment by StephenHodgson** [comment]
@Nakda, any update from Unity about this issue?

**Comment by Nakda** [comment]
@StephenHodgson, no update so far. The ticket is still marked as "Open".

**Comment by nablam** [comment]
I did notice thisAnchor.isLocated flipping back to false. I went ahead and made a singleton Debugger and placed it in the ImportExportAnchormanager.Awake(). That broke evrything, but it also gave me an idea: Awake() fires before my singelton awakes...so   I decided to call WorldAnchorStore.GetAsync(AnchorStoreReady) from the Start() instead of Awake() and that seems to work.

**Comment by Nakda** [comment]
@nablam your situation is probably more related to #640 

@StephenHodgson just so you know I did not forget about this issue and as I didn't not receive any update from Unity, I decided to open a thread on their dedicated forum: [Unity Forum](https://forum.unity3d.com/threads/worldanchor-islocated-property-not-updated-before-ontrackingchanged-callback.469249/)

**Comment by StephenHodgson** [comment]
@Nakda do you know if this ever got fixed?

**Comment by Nakda** [comment]
Unity never answered my ticket regarding this issue. Since then, I didn't
check if it has been fixed but I could give it a try tomorrow morning.

Le 18 oct. 2017 21:00, "Stephen Hodgson" <notifications@github.com> a
écrit :

**Comment by tvald** [comment]
update: this bug is still present in 2018.2.14f1

**Comment by markus-enklu** [comment]
and then .isLocated went away in 2019.4 without any mention of what to replace it with :(

**Comment by keveleigh** [comment]
It should still be present (though deprecated) in 2019.4 if you're using the legacy APIs. https://docs.unity3d.com/2019.4/Documentation/ScriptReference/XR.WSA.WorldAnchor-isLocated.html

If you're using the new XRReferencePoint/XRAnchor API, you can use the `trackingState` property.

**Comment by markus-enklu** [comment]
Yes it is! I had "show warnings as errors" turned on in that package, sorry.
