### ISSUE TITLE
Interactable - "Remove Event" button does not work, NullPtr

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5634]
## Overview
You should be able to remove events using the "remove event" button in interactable. Unfortuantely, the button does not work for removing all but the first event, and instead throws large number of exceptions.

![image](https://user-images.githubusercontent.com/168492/62977286-70385580-bdd3-11e9-93d0-3de785fc750b.png)

## Steps to reproduce
1. Open any interactable, and under "event", add a second event
2. Try to remove that second event

## Expected Behavior
I can remove the event!

## Actual Behavior
Oh no! I cannot actually remove the second event.

**Comment by Troy-Ferrell** [comment]
I fixed a similar issue with removing themes in the inspector code so curious if it is the same problem just different place....looking now
