### ISSUE TITLE
[Input Simulation] Add ability to select using just mouse clicks (no spacebar to bring up simulated hands)

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5635]
## Overview
As indicated by [this stackoverflow question](https://stackoverflow.com/questions/56821449/hl1-input-for-mrtk-v2-1/57194136#57194136) and [this slack post](https://holodevelopers.slack.com/archives/C2H4HT858/p1564597430080500), some people want to just be able to use the mouse, no keypresses, to select things using just the HoloLen 1 GGV (aka the head) cursor.

In the [SO post](https://stackoverflow.com/questions/56821449/hl1-input-for-mrtk-v2-1/57194136#57194136) I provided a solution script which will simulate click events from the left mouse button. It would be nice to be able to configure input simulation service to support this style of interaction -- just to allow the left mouse button to simulate a select event.

## Expected Behavior
When hand simulation is in Gestures mode, then even if hands are not up, left clicking with the mouse could simulate a click event.

![image](https://user-images.githubusercontent.com/168492/62978479-387edd00-bdd6-11e9-9a98-5eb76c730dc7.png)

**Comment by julenka** [comment]
Lukas, this seems right up your alley. Would you be interested?

**Comment by julenka** [comment]
Here is a sample containing a full solution that worked for our customers. Just drag the prefab in to enable the behavior they wanted (right click to move the camera, left click to select / press buttons). It would be nice if we could just do this using the input simulation service, without needing an extra prefab.

[SO.Mouse.Only.Input.Simulation.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3498955/SO.Mouse.Only.Input.Simulation.zip)

**Comment by debfdias** [comment]
Hi, @julenka ! I'm facing a similar situation where I need to select an object with the mouse pointer. I'm attaching the SimulateSelectOnClick script to the object and my hand mode is in Gestures mode, but still nothing happens. Can you help me?

**Comment by RogPodge** [comment]
@debfdias we're still working on adding this feature for the next release, with this PR tracking our latest progress https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7631

Are you able to select the object after bringing up either the left hand (left shift) or the right hand (spacebar)?

**Comment by debfdias** [comment]
> ble to select the object after bringing up eithe

Yes, with spacebar or left shift I can select the objects. Thank you for the reply! I'll be looking foward the next release :)
