### ISSUE TITLE
Scene System fails to start

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#5641]
## Describe the bug
When you activate the Scene System from the MRTK profile, it shows this error message and cannot use it.

Enable the SceneSystem in the Profile
![2019-08-13 18_50_02-Unity 2018 4 2f1 Personal - MRTKExamplesHub unity - MRTK-Public-Microsoft - Univ](https://user-images.githubusercontent.com/13754172/62989000-37ac7200-bdfb-11e9-93a6-eaca710ec779.png)

Error message in the console. Scene System is not displayed under MixedRealityToolkit Hierarchy. 
![2019-08-13 18_49_23-Unity 2018 4 2f1 Personal - MRTKExamplesHub unity - MRTK-Public-Microsoft - Univ](https://user-images.githubusercontent.com/13754172/62989003-39763580-bdfb-11e9-842c-84a22681643a.png)

**Failed to start the Scene System!**

UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:407)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeInstance() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:535)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:674)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:OnValidate() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:1386)

**Unable to register a service of type IMixedRealityDataProvider. Register this DataProvider with the MixedRealityService that depends on it.**
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(Type, IMixedRealityService) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:752)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(IMixedRealitySceneSystem) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:791)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterService(Type, SupportedPlatforms, Object[]) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:211)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:405)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeInstance() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:535)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:674)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:OnValidate() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:1386)

**When SceneSystem related script is used in a script, it asks to change obsolete namespace:**
Assets\MixedRealityToolkit.SDK\Features\UX\Scripts\Utilities\LoadContentScene.cs(44,13): error CS0618: 'MixedRealityToolkit.SceneSystem' is obsolete: 'Utilize CoreServices.SceneSystem instead'

## To reproduce
1. Go to MRTK Profile
2. Click on Scene System
3. Check 'Enable Scene System' and assign MixedRealitySceneSystem, select DefaultMixedRealitySceneSystemProfile.

## Expected behavior
SceneSystem should be activated without error message and it should be shown in the Hierarchy (with Editor's 'Use Service Inspectors' checked)

## Branch
prerelease/stabilization
You can check out the MRTK Example Hub PR branch #5443  for Scene System Testing.
Open ExamplesHub scene which has configured profile for the SceneSystem

**Comment by davidkline-ms** [comment]
This should be an easy fix. It appears that the scene service implements IDataProvider instead of IExtensionService.

**Comment by wiwei** [comment]
Let's make sure to have a test case for this going forward.

**Comment by davidkline-ms** [comment]
> Let's make sure to have a test case for this going forward.

We can definitely have a test that validates being able to register the scene (and any of our other services).

We can also add a test (for MRTK team shipped extensions) that ensure that none of them inherit IMixedRealityDataProvider

**Comment by davidkline-ms** [comment]
Fixed by #5648
