### ISSUE TITLE
MixedRealityToolkit.Instance.GetService<T> does not find any self-made Extension Services anymore

### ISSUE THREAD

**Issue by LocalJoost** [microsoft/MixedRealityToolkit-Unity#5644]
## Describe the bug

If you create an ExtensionService MyService, MixedRealityToolkit.Instance.GetService<IMyService> does not find it anymore

## To reproduce

1.Create an extension service MyService using the wizard, register
2. Create a simple behaviour that calls MixedRealityToolkit.Instance.GetService<IMyService>() in Start
3. Returns null value

## Expected behavior
Return an implementation of IMyService. This used to work

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.4.2f1]
- MRTK Version prerelease/2.0.0_stabilization as of August 14

## Target Platform (please complete the following information)

- HoloLens

## Observation

All my 3 extension services are stored as IMixedRealityExtensionService in stead of their having their own interface as key

## Workaround

I have added the following extension method and this allows me to get extension services again
```Csharp
using System.Linq;
using Microsoft.MixedReality.Toolkit;

namespace MRTKExtensions.Utilities
{
    public static class MixedRealityToolkitExtensions
    {
        public static T GetExtensionService<T>(this MixedRealityToolkit tk ) where T : IMixedRealityExtensionService
        {
            var service = tk.GetServices<IMixedRealityExtensionService>().FirstOrDefault(p => p is T);
            return (T) service;
        }
    }
}
```
Is this change intentional? If so, some definite guidance is needed. And maybe I missed that

**Comment by davidkline-ms** [comment]
> All my 3 extension services are stored as IMixedRealityExtensionService in stead of their having their own interface as key

This is super helpful info, @LocalJoost. Thanks!

**Comment by Troy-Ferrell** [comment]
Taking a look now, this is very interesting. We actually have a unit test for this case. MixedRealityToolkitTests::Test_05_01_RegisterMixedRealityExtensionService()

@LocalJoost , can you elaborate more on how you are calling MRTK.Instance.GetService<T>()?

MRTK.Instance.GetService<IMixedRealityExtensionService>()
MRTK.Instance.GetService<IMyExtensionService>()
MRTK.Instance.GetService<MyExtensionService>()
MRTK.Instance.GetService<IMixedRealityExtensionService>("name of my service")?

**Comment by Troy-Ferrell** [comment]
Also if you just do 
MRTK.Instance.REgisterService (new TestExtensionService()) then that's basically

MRTK.Instance.RegisterService < TextExtensionService > (new...) so it needs to be

MRTK.Instance.GetService< TestExtensionService >()

**Comment by LocalJoost** [comment]
Hi,
I used MixedRealityToolkit.Instance.GetService&lt;IMyService&gt;().
And I don't register the extension server in code - I add it to the configuration using the Editor. _You_ tell me how it's registered. ;) I spent 6 hours debugging my code until finally resorted to my little workaround

**Comment by Troy-Ferrell** [comment]
Thank you for the additional information! I'll look into the default registration by the profile

Can you try MRTK.Instance.GetService < MyService >() if that works?

**Comment by davidkline-ms** [comment]
Added to GA Blocker list. This was an unintended side effect of the registry work from last April

**Comment by LocalJoost** [comment]
Imported the 2.0.0_stabilization again and it works now without my work around. Interestingly, the workaround still works as well ;) Thanks!
