### ISSUE TITLE
PrimaryPointer demo does not restore gaze ptr when last controller lost

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#5655]
## Describe the bug

When turning off the last controller during the PrimaryPointer demo, the gaze pointer is not restored.

## To reproduce

1. Ensure all controllers are off
2. Run PrimaryPointer demo on VR headset
Note gaze pointer
3. Turn on a motion controller
Note controller pointer at the end of the pointing ray
4. Turn off motion controller

## Expected behavior

The gaze pointer to be restored.

## Your Setup (please complete the following information)

- Unity Version 2018.4.6f1
- MRTK Version 2.0.0 (build from 2019-08-14)

## Target Platform (please complete the following information)

- WMR immersive
- OpenVR

**Comment by julenka** [comment]
This is expected behavior -- in WMR and HL2, you need to say the keyword "select" before the gaze pointer returns. That's the default behavior we are matching in MRTK.
