### ISSUE TITLE
Instantiating a Clone w/ TapToPlace as a Component

### ISSUE THREAD

**Issue by mattfedocsg** [Microsoft/MixedRealityToolkit-Unity#567]
I am not sure if this is "by design", but if you have an object that has TapToPlace.cs added as a component, with a saved friendly anchor name specified and then go to instantiate a clone, the clones position and anchor matches that of the original object.  Even if you try to instantiate the object with a new pos and rot.  I assume because the position is saved by anchor.

I fixed this on my end by instantiating the object, changing the anchor name, attaching the anchor to the WorldAnchorManager, then changing the position and rotation.

I feel like the script should have done this for me though.  Maybe check to see if the world anchor store already has that key anchor name?  Then at on destroy remove the anchor that was cloned?

I guess it is just my opinion, but anyone else have any thoughts?  Or maybe I am missing something?  Thanks!

**Comment by mattfedocsg** [comment]
If anyone is having issues with this, Ive just been updating the friendly name with the date down to the second or millisecond that the object was intantiated.  Then, in best gaming practice, throw that object in a pool.

`gameObject.GetComponent<TapToPlace>().SavedAnchorFriendlyName = "gameObject_" + System.DateTime.Now.ToString("yyyyMMddhhmmss");`

**Comment by StephenHodgson** [comment]
@mattfedocsg With the latest PR You would just need to make sure the `GameObject` names are unique.
