### ISSUE TITLE
Spatial Awareness System and Object Mesh Observer profile inspectors missing Clone button

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#5679]
## Describe the bug

When loaded in the inspector, the  DefaultMixedRealitySpatialAwarenessSystemProfile and DefaultSpatialObjectMeshObserverProfile do not have a Clone button (like other profile inspectors)

## To reproduce

1. Double-click on the profile in the project window.
2. Note the missing Clone button

## Expected behavior

A clone button in the inspector.

## Your Setup (please complete the following information)

- Unity Version 2018.4.6f1
- MRTK Version 2.0.0 (15.7)

**Comment by davidkline-ms** [comment]
Workaround: Manually create a copy of the profile (ex: Ctrl+D in Unity) and rename as desired.

**Comment by davidkline-ms** [comment]
This issue and workaround should be added to the 2.0.0 release notes.

**Comment by Troy-Ferrell** [comment]
IsCustomProfile is true when it should be false for those two

**Comment by Troy-Ferrell** [comment]
Also I cannot find a DefaultSpatialObjectMeshObserverProfile

**Comment by davidkline-ms** [comment]
> Also I cannot find a DefaultSpatialObjectMeshObserverProfile

That lives in MixedRealityToolkit.Providers\ObjectMeshObserver\Profiles

**Comment by Troy-Ferrell** [comment]
Ahh, file name is DefaultObjectMeshObserverProfile for others reading this

**Comment by timGerken** [comment]
There are other "Default" profiles that snuck into the 2.0.0 release with their isCustomProfile bit set to 1:
```
C:\src\GitHub\Microsoft\MRTK [mrtk_release ≡]> findstr -s -i -c:"isCustomProfile: 1" *.asset | findstr -v Examples                                     Assets\MixedRealityToolkit.Extensions\SceneTransitionService\DefaultSceneTransitionServiceProfile.asset:  isCustomProfile: 1
Assets\MixedRealityToolkit.Providers\ObjectMeshObserver\Profiles\DefaultObjectMeshObserverProfile.asset:  isCustomProfile: 1
Assets\MixedRealityToolkit.SDK\Profiles\DefaultMixedRealityInputRecordingProfile.asset:  isCustomProfile: 1
Assets\MixedRealityToolkit.SDK\Profiles\DefaultMixedRealitySceneSystemProfile.asset:  isCustomProfile: 1
Assets\MixedRealityToolkit.SDK\Profiles\DefaultMixedRealitySpatialAwarenessSystemProfile.asset:  isCustomProfile: 1
Assets\MixedRealityToolkit.SDK\Profiles\HoloLens1\DefaultHoloLens1InputSimulationProfile.asset:  isCustomProfile: 1
```
