### ISSUE TITLE
Add a warning for Internet connection requirement in Dictation Handler doc

### ISSUE THREAD

**Issue by Kent1LG** [microsoft/MixedRealityToolkit-Unity#5683]
## Describe the Issue
I'm currently working on an application which will be used without an internet connection. I wanted to use Dictation and it took me a long time to understand that an internet connection is required for Dictation to work. 

## Feature Area
Please can you add a warning on the documentation about the internet connection requirement?
 
## Existing Doc Link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Dictation.html?q=dictation

**Comment by wiwei** [comment]
@Kent1LG definitely - I was checking out the Unity docs for this and they also don't mention this which is weird, but looking at https://docs.microsoft.com/en-us/windows/mixed-reality/voice-input-in-unity, this is mentioned there.

I'll update this to make sure that others don't have to go through your pain
