### ISSUE TITLE
Remove SceneManager and LightingManager in build settings 

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5685]
## Overview
![image](https://user-images.githubusercontent.com/168492/63181723-8e859780-c005-11e9-8d3a-6aff49f20c6c.png)

The first two scenes in build settings for mrtk_development are annoying, devs need to remove them when building always. They don't add any value. Remove them

**Comment by wiwei** [comment]
@Railboy in case these are necessary/helpful for the scene management testing.

It should be noted that some tests depend on certain scenes being in the scene list (i.e. the sanity test depends on hand interaction examples being there)
