### ISSUE TITLE
Making SpatialMappingObserver more flexible

### ISSUE THREAD

**Issue by sontharr** [Microsoft/MixedRealityToolkit-Unity#569]
I am using both SpatialMappingManager and SpatialMappingObserver in a project, but discovered that SpatialMappingObserver doesn't really do everything I want it to do with the cooked data.  I decided to look into finding a way to modify SpatialMappingObserver.  I wanted to do it in a way that didn't modify the Holotoolkit itself since I want the code to be exportable to other projects, and not break projects that also used SpatialMappingManager and SpatialMappingObserver.  

After looking at SpatialMappingManager, I found that it specifically looked for a SpatialMappingObserver object during the Awake() function. and it has a RequiredComponent directive for the SpatialMappingObserver.  This made replacing the SpatialMappingObserver with one of my own constructs hard, because I didn't want to modify the SpatialMappingManager.  

The other problem is that SpatialMappingObserver uses private functions, not protected virtual ones, so I could not derive a class from it to contain my modifications.  

What I would like to propose for the HoloToolKit is three things:

1)  Remove the required component from the SpatialMappingManager.  This would allow anyone to include their own SpatialMappingObserver-type component as long as it was derived from SpatialMappingObserver (which would allow it to be found by the gameObject.GetComponent<SpatialMappingObserver>() in Awake())

2)  Modify the code in SpatialMappingManager's Awake() method to create a SpatialMappingObserver component if one is not found.  

3)  Change all private functions in SpatialMappingObserver to protected virtual to allow derived classes.

What do you folks think?  Is this a good idea, or am I way off base?

-Alex

**Comment by HoloFan** [comment]
That sounds like a very good idea. I actually looked into that as well but as I only needed small changes just adapted the SpatialMappingObserver ([Issue #557](https://github.com/Microsoft/HoloToolkit-Unity/issues/557), [PR #560](https://github.com/Microsoft/HoloToolkit-Unity/pull/560)  ).
But I think, that adapting the SpatialMappingObserver and the SpatialMappingManager as outlined by you is a good way to allow for more individual and custom programming using the HTK.

**Comment by davidkline-ms** [comment]
We should continue to investigate.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
