### ISSUE TITLE
Deploy via USB isn't intuitive

### ISSUE THREAD

**Issue by XPav** [microsoft/MixedRealityToolkit-Unity#5698]
Unity 2018.4.6f1
mrtk_development 33fd136c8fcbe7af09cf5fe5c1b92fcaef6430ff

This is pretty much my old bug #1959.  

The "Local Machine" target selection can mean either:
1. The PC
2. The HL1 connected via USB

I press "Install", and it tries to deploy the AppX to the PC, not the HL1.   "Pair HoloLens" is disabled.
I unplug the HoloLens USB, plug it back in, the "Pair HoloLens" button goes enabled, but now when I press "Install" it deploys to the HL1.
I restart Unity, it comes back up in the same state, I press "Install" and it deploys to PC.

I would recommend different deploy targets for "Local Machine", "HL via USB", and "Variety of HLs via Network".

**Comment by davidkline-ms** [comment]
Moving to 2.3.0. The plan to address this is to revise the Deploy UX to be similar to the [Mixed Reality Commander app](https://github.com/microsoft/MixedRealityCompanionKit/tree/master/HoloLensCommander).
