### ISSUE TITLE
[UNET-Sharing] Invoked function does not exist

### ISSUE THREAD

**Issue by Nakda** [Microsoft/MixedRealityToolkit-Unity#570]
In the HoloToolkit example "SharingWithUNET", in the GenericNetworkTransmitter class, line 201:
Invoke("RequestAndGetAnchor", timeToDeferFailedConnections);

Problem is RequestAndGetAnchor function does not exist (probably got renamed but the Invoke part has not been updated accordingly).

**Comment by nablam** [comment]
well, SharingWithUNET still works despite this. I am able to generate an anchor when server starts, then I can download the anchor when a client joins... I was looking for a way to trigger an event when the anchor is downloaded and came across  this .. has anyone figured out if this RequestAndGetAnchor() was renamed or if it is hidden somewhere ?

**Comment by StephenHodgson** [comment]
From the log of this class it seems it was never implemented when added.
