### ISSUE TITLE
Tap to place parent

### ISSUE THREAD

**Issue by StarWardo** [Microsoft/MixedRealityToolkit-Unity#571]
I am using the tap to place script when the app started to let the user move a cube around the room for choosing a location to place holograms.

When I move my cube around and place it again it seems like only some of the holograms are move to the location of the cube and some are still in the old location. I cannot find a difference in these game objects.

The cube with the Tap to Place script is inside a game object called "holograms". The place parent on tap is checked and the Parent game object is set to the Holograms object. The holograms object has a bunch of other objects that will appear by script.

**Comment by mattfedocsg** [comment]
You need to check and make sure the friendly anchor name is different for each object.  If they are all the same and you go to move them, they will all snap back to that one anchor.  You can see Issue #567 and follow if I can get an answer on instantiation as well.

**Comment by StarWardo** [comment]
I only need one object as anchor. 

The object is used to place a group of holograms where the user wants them. But some of the holograms keep the old position.

**Comment by mattfedocsg** [comment]
You will have to change the anchor position per object if you had any previous anchors attached to that object.  Try clearing the anchor store as well.  Ive come across this issue before.

**Comment by nyp-leon** [comment]
@mattfedocsg  What do u mean by anchor position and anchor store? How do I clear the anchor store? I'm trying to tap to place a bunch of holograms but only some are above to be moved and relocated. Same problem I guess..
