### ISSUE TITLE
Follow Solver (experimental)

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5713]
Menus that follow the user are common interaction pattern in mixed reality. MRTK's solvers offer the promise of enabling these menus, however it is quite challenging to configure solvers to achieve the follow behaviors that we see in flagship applications such as the HoloLens 2 onboarding experience. Let's fix this by providing a "Follow" solver which will allow people to easily build near interaction menus that follow them around.

This work will combine efforts from two existing PRs: Orbital2 #5159 and Follow #5611. The plan is to make a new "Follow Solver" as an experimental feature, let the feature gather feedback / fixes for a month, and then graduate the solver with docs + tests.

## Desired behavior
Follow should be a solver that people can use to easily build menus that follows the user around. By default the behavior should match the carefully tuned / optimized behavior that exists in HoloLens 2 onboarding (OOBE). The primary goal of Follow is to support near interaction menus.

## Requirements:
These are taken from pr #5611 and pr #5159
- Default configuration should match the behavior from #5611, because it matches the implementation of near menus in HoloLens 2 OOBE.
- Add "leashing" behavior provided by #5159. 
    - When leashing is not enabled, do not show leashing params.
- Add "face target" field to allow the object to face to be decoupled from the transform target (use #5159 for guidance). For example, when following a hand, you may want the object to still face the head.
    - scene object
    - body part (head, motion controllers, hands)
    - whatever the solver handler is tracking (tracked object)   
    - when "face target" is not enabled, hide face target params.
- Add ability to specify arbitrary pivot axis (by default, Y). See "pivot axis" in #5159.
- Keep the angle stepping feature from orbital

We also aim to follow a few guidelins when implementing this:
- Make it easy to customize / extend. Follow #4532 as an example
- The inspector reflects the decisions that can be made by hiding and showing fields. For example, when "face target" type is "body part" (final name tbd), shows options head, motion controllers, hands.

Possibly incorporate the following (still discussing in #5611)
    - Solver offsets can be defined in world or local space (separate issue)
    - It can snap angles on any constraint axis

### Appendix: Current challenges with Orbital + Radial 
There are a few specific challenges with the orbital solvers that make the "follow me" behavior many people want out of their menus, etc. difficult:
- It is difficult (impossible?) to have the orbital follow one object, but try to face another
- Not possible to specify arbitrary constraints on the way an object rotates
- The name is confusing / not easy to discover.

**Comment by Cameron-Micka** [comment]
I just spoke with @ErianVazquez-Microsoft and Alex Gough, I'm going to try and accelerate getting this in for this https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6235 so we can have a keyboard preview window that tags along _similar_ to the shell and gives the community a shell-like Follow solver.

**Comment by julenka** [comment]
Looks like #6235 was able to go in without a follow solver, so guessing this work was maybe started but not completed. We would like to get this in for 2.3. Since Cameron is out, @thalbern suggested @MenelvagorMilsom  could have a look.
