### ISSUE TITLE
Add pipeline script to ensure no profiles are checked in with isCustomProfile: 1

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#5717]
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5715 highlights another case where isCustomProfile: 1 is getting checked in on our built-in profiles - these are because of mistakes as people are cloning profiles or otherwise making changes.

We our checkin submits should error out if this is detected, so that we don't have to fix this repeatedly in the future and depend on someone detecting and noticing things after the fact.

**Comment by timGerken** [comment]
@wiwei ,
There are other "Default" profiles that snuck into the 2.0.0 release with their isCustomProfile bit set to 1:
```
C:\src\GitHub\Microsoft\MRTK [mrtk_release ≡]> findstr -s -i -c:"isCustomProfile: 1" *.asset | findstr -v Examples                                     Assets\MixedRealityToolkit.Extensions\SceneTransitionService\DefaultSceneTransitionServiceProfile.asset:  isCustomProfile: 1
Assets\MixedRealityToolkit.Providers\ObjectMeshObserver\Profiles\DefaultObjectMeshObserverProfile.asset:  isCustomProfile: 1
Assets\MixedRealityToolkit.SDK\Profiles\DefaultMixedRealityInputRecordingProfile.asset:  isCustomProfile: 1
Assets\MixedRealityToolkit.SDK\Profiles\DefaultMixedRealitySceneSystemProfile.asset:  isCustomProfile: 1
Assets\MixedRealityToolkit.SDK\Profiles\DefaultMixedRealitySpatialAwarenessSystemProfile.asset:  isCustomProfile: 1
Assets\MixedRealityToolkit.SDK\Profiles\HoloLens1\DefaultHoloLens1InputSimulationProfile.asset:  isCustomProfile: 1
```

**Comment by wiwei** [comment]
Thanks to @keveleigh for solving this problem once and for all!
