### ISSUE TITLE
Contributing page is out of date

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5718]
## Overview
Our contributing page is out of date:

1. Has old instructions for how to build UWP
2. Has old instructions for how to get help

There are plenty of other things that it recommends that aren't great. I think that this was probably copied from some older place prior to this docfx setup. I think in general this should be updated so that we don't lead to incorrect information.

**Comment by cre8ivepark** [comment]
How about adding visual step-by-step flow for the contribution? As a beginner, it was hard to understand the flow of forking/branching/opening PRs.
![2019-08-19 18_30_37-MRTKv2_UX_BuildingBlocks_20190708a_YoonPark_ENG pptx - PowerPoint](https://user-images.githubusercontent.com/13754172/63310423-83559480-c2af-11e9-85a8-96a127e57fd2.png)

**Comment by davidkline-ms** [comment]
Fixed with release notes update PR #5613
