### ISSUE TITLE
InteractionManager.InteractionSourceDetected and Lost spam

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5721]
## Describe the bug
I'm not entirely sure if it is a bug, but the HL1 seem to have a hard time to reliably call InteractionSourceDetected and InteractionSourceLost.
I logged the handedness of the detected sources on those two and even waving one hand infront if it can trigger every possible combination:
- single enter and exit (exprected)
- exit - enter - exit for a single exit
- right hand is detected as left and vice versa
- same hand gets detected and lost as the same or the other hand

You don't even need to be fast moving, it's very easy to reproduce

## To reproduce

Connect a Hololens via Holograpic Remoting and add the following code to a script in an empty scene you're playing:

```
    void Start()
    {
        InteractionManager.InteractionSourceDetected += t => Debug.Log(t.state.source.handedness);
        InteractionManager.InteractionSourceLost += t => Debug.Log(t.state.source.handedness);
    }
```

## Expected behavior

One Hand, one detection

## Your Setup (please complete the following information)

- Unity Version 2018.4.6f1

## Target Platform (please complete the following information)

- HoloLens

**Comment by wiwei** [comment]
@keveleigh I feel like this has come up in the past - I think that these are just forwarding on of underlying platform source detected and source lost events, so assuming that's true, it's not really an MRTK issue as much as it is the underlying platform events.

@julenka I think this may also be related to how on HL1, source detected/lost is based around the 'ready' gesture? Or is this not related at all?

**Comment by Troy-Ferrell** [comment]
Yea this is either a Unity/WMR platform issue. Something may have changed to accommodate HL2 on Unity's side. 

@Alexees it is important to file an issue via the Feedback hub app in your HL1. That way a bug is created in the system tracked by the platform team
