### ISSUE TITLE
Will the Mixed Reality Portal be deprecated? (Conclusion from lack of support)

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5733]
I know this does not belong here, but I feel like not having any other choice to get any information about this matter:

For quite some time, the Portal has a couple of problems. I reported them all to the Feedback HUB, but to no avail. Either nobody cares about them, or nobody cares about fixing the Feedback HUB so I know what's going on prior to fixing or leaving the bugs concerning the portal.
The most recent ridiculousness is, that either the portal, or the Unity Mixed Reality SDK does not seem to be able to render correctly (the rendered frame glitches in 90 degrees on its side every now and then and running the game smears the upper and bottom quarter of the view when moving the head), while running SteamVR within it does. Why is the functionality for SteamVR in the portal better than the portal itself?

I WANT to develop for this platform, but all the lack in support tells me not to. Is there anything that I am missing? I don't want to spend my development time on something that might be considered for deprecation we just don't know of yet.

**Comment by wiwei** [comment]
As you say, this isn't related to the MRTK, but the underlying platform. I've forwarded this feedback onto the mixed reality portal owners.

**Comment by Alexees** [comment]
@wiwei
Did anything happen here? I have been away for a month, came back and still received nothing in the feedback hub.
