### ISSUE TITLE
Keyboard System issues on enter and space buttons

### ISSUE THREAD

**Issue by Kent1LG** [microsoft/MixedRealityToolkit-Unity#5739]
## Describe the bug

Pressing Enter or Space keys erases currently typed text with the Keyboard system.

## To reproduce

- Create a Holographic scene 
- Instantiate KeyboardSystemExemple
- Press Space/Enter buttons

## Your Setup (please complete the following information)

- Unity 2018.3.14f1
- MRTK Release 2.1 + Keyboard files from https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5651

## Target Platform (please complete the following information)

- HoloLens

**Comment by wiwei** [comment]
I'll route this to the person who owns the keyboard on the platform side - this isn't an MRTK-specific issue.

**Comment by kevbarn** [comment]
Hi @Kent1LG, I want to make sure I understand your issue. When you say the "keyboard system crashed", does that mean everything on your device went black and you saw a Microsoft logo followed by the shell? If this isn't the crash that you experienced, can you clarify what you observed?

If you saw the crash as I described, can you please repro this again and then immediately file a Windows Feedback issue? After doing so, can you reply back here with a link to the feedback so I can track down the bug internally?

**Comment by Kent1LG** [comment]
Hey @kevbarn I m really sorry to wasted you time i think that was my fault. I just tried again and it works without crashing.
But there is still the two others issues.

**Comment by kevbarn** [comment]
Thanks for confirming @Kent1LG. A crash like what you are describing will automatically be uploaded to Microsoft (depending on your settings for diagnostic data). If this is getting in your way, I suggest filing a feedback through Feedback Hub immediately after rebooting explaining what actions you took and what you observed right before the crash. That extra information can be really helpful when we are investigating issues like this.

**Comment by wiwei** [comment]
Yep - we'll take care of that double cursor one - since this is an underlying platform thing and I think that the next steps here are somewhat clear, I'm closing out the MRTK tracking issue for this one.
