### ISSUE TITLE
Bounding box golden path tutorials

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5743]
-  Ensure that github.io docs has a "golden path" tutorial on how to use it in editor.
-  Ensure that github.io docs has a "golden path" tutorial on how to use it via runtime/code instantiation.

**Comment by thalbern** [comment]
closing this as yoon already updated the docs and there's a separate issue for bounds control that tracks that the changes are carried over to the new control https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7443
