### ISSUE TITLE
HandConstraint solver treats Xbox Controller (and possibly other non-hand controllers) as a hand 

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#5749]
## Describe the bug

HandConstraint solver treats Xbox Controller (and possibly other non-hand controllers) as a hand. This means the "OnHandActivate" event is raised even though there is no hand visible.

## To reproduce

1. Create an app that uses the HandConstraint solver for a hand menu (i.e. show menu when hand is visible)
2. Connect an Xbox controller to your device
3. Start app
4. Hide hands
4. Hand menu is still visible (because HandConstraint thinks the Xbox controller is a hand)

## Expected behavior

HandConstraint should only treat hand controllers as hands, and ignore things like the Xbox controller, mouse, or any other non-hand device.

## Your Setup (please complete the following information)

- Unity Version = 2019.1.10f1
- MRTK Version = v2.0

## Target Platform (please complete the following information)

- HoloLens 2
- WMR immersive

**Comment by AMollis** [comment]
@Cameron-Micka  i think you're the best person for this

**Comment by Cameron-Micka** [comment]
Thank you for reporting this @AMollis! This probably stems from allowing hand menus on motion controllers, but it sounds like we need to do a bit more filtering for controllers which don't have and assigned hand and/or motion.

**Comment by Cameron-Micka** [comment]
TODO, add warning if handedness is not left, right, or both.

**Comment by AMollis** [comment]
@Cameron-Micka   it appears to be this line in ChangeTrackedObjectType(...) that's causing the problem.

`if (SolverHandler.TrackedHandness != hand.ControllerHandedness)
{
      **SolverHandler.TrackedHandness = hand.ControllerHandedness;**
`

**Comment by wiwei** [comment]
@Troy-Ferrell FYI
