### ISSUE TITLE
How to know when an Anchor is loaded?

### ISSUE THREAD

**Issue by alamboley** [Microsoft/MixedRealityToolkit-Unity#575]
Hey,

I modified the HandDraggable script for being able to use Anchors. I don't need *SpatialMapping* if I don't make raycast with the environment, right?

My anchor is used on a specific object which is hidden to the final user (available via Speech Recognition). This object is used to place my final object. So at the beginning of the application, I wish it had the anchor position:
```csharp
anchorManager.AttachAnchor(gameObject, SavedAnchorFriendlyName);

foreach(Transform seq in sequences)
{
    seq.position = transform.position;
    seq.rotation = transform.rotation;
}
```
But it hasn't due to the asynchronous anchors loading. The method `Anchor_OnTrackingChanged` from class `WorldAnchorManager` is private. How can I know the anchor is loaded?

Obviously I could check its transform in an update with *hasChanged* property.

**Comment by StephenHodgson** [comment]
See https://github.com/Microsoft/HoloToolkit-Unity/issues/737

**Comment by StephenHodgson** [comment]
I believe that the anchor should update its transform automatically.

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
