### ISSUE TITLE
Mixed reality Toolkit not appearing in toolbar

### ISSUE THREAD

**Issue by Smofkey** [microsoft/MixedRealityToolkit-Unity#5753]
Mixed reality toolkit doesnt appear in toolbar like it should do? I have 3 errors in my console but dont know how to fix them.

**Comment by Smofkey** [comment]
![Fout](https://user-images.githubusercontent.com/53091558/63513509-c3eb2300-c4e6-11e9-832d-6be93ff9dcd7.PNG)

**Comment by keveleigh** [comment]
Have you imported the Microsoft.MixedReality.Toolkit.Unity.Foundation.2.0.0.unitypackage as well, or just the Tools package?

All of the three optional packages have a dependency on the Foundation package.

**Comment by Smofkey** [comment]
> Have you imported the `Microsoft.MixedReality.Toolkit.Unity.Foundation.2.0.0.unitypackage` as well, or just the Tools package?
> 
> All of the three optional packages have a dependency on the Foundation package.

Im sorry for the late response. I imported all files but it still didnt work. I use version Microsoft Mixed Reality Toolkit v2.0.0.

**Comment by Smofkey** [comment]
I got it fixed thanks.
