### ISSUE TITLE
MRTK and OpenVR not compatible for Holographic Remoting

### ISSUE THREAD

**Issue by telion2** [microsoft/MixedRealityToolkit-Unity#5754]
## Describe the bug
When having a project with MRTK and OpenVR in the XR Settings, hitting Play in Unity will show nothing in Holographing Remoting.

## To reproduce
Player Settings -> XR Settings -> add MRTK & OpenVR (I did this using SteamVR) 
Start Holographic Remoting & Connect to Hololens 1 -> See that nothing happens

I created a very simple Scene with only one GameObject in it (Sphere) and I only could see it when I removed OpenVr form the XR Settings. 

## Expected behavior
That Holographic Remoting still shows the scene when hitting play no matter what else is in the XR Settings, besides MRTK.
Atleast a warning that incompatible Settings are used. I took me weeks to find that out.  

## Your Setup (please complete the following information)

MRTK 2.0.0
Unity 2018.3.12.f1

## Target Platform (please complete the following information)

- HoloLens 1
- OpenVR, in particular only the Vive Trackers

**Comment by keveleigh** [comment]
Are your build settings set to `Universal Windows Platform` or `PC, Mac & Linux Standalone`?

![image](https://user-images.githubusercontent.com/3580640/63536121-c5f1b980-c4c7-11e9-8b98-0c6a9a2ccd9d.png)

Unity only supports remoting when set to `Universal Windows Platform`, which shouldn't have OpenVR as an XR Setting:

![image](https://user-images.githubusercontent.com/3580640/63536207-f89bb200-c4c7-11e9-9a7b-64e80338e517.png)

 Also, when switched to `Standalone`, I'm unable to access the Holographic Remoting window:

![image](https://user-images.githubusercontent.com/3580640/63536268-16691700-c4c8-11e9-8a90-9326ce93ea60.png)

Switching back and forth between UWP and Standalone shouldn't affect each other. The MRTK repo project has OpenVR in its Standalone XR Settings:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/bf942792f99a5169528d7ca09537a68c2edac4ac/ProjectSettings/ProjectSettings.asset#L307

**Comment by telion2** [comment]
Its set to UWP, but I was able to add OpenVr to the XR Settings, which broke the whole thing. If you want to know how, then I need a little more time to reproduce it. 
Is there a way to have Remoting with MRTK and OpenVR? 
The use-case are vive-trackers. Basically I want to track certain things (e.g. hands off-screen) with vive-trackers, as it is more accurate and less error-prone. They however need SteamVR to connect and everything.

**Comment by keveleigh** [comment]
>Is there a way to have Remoting with MRTK and OpenVR?

You won't be able to remote to a HoloLens, which isn't supported by OpenVR, but you can definitely use MRTK with OpenVR-supported headsets, like the [WMR immersive headsets](https://docs.microsoft.com/en-us/windows/mixed-reality/immersive-headset-hardware-details) or the Vive. Hitting play in the editor with one of those attached should launch you directly into the device.

**Comment by telion2** [comment]
Looking for a workaround, for those that end up here aswell: 
https://stackoverflow.com/questions/57706685/how-to-stream-data-between-unity-projects
