### ISSUE TITLE
Multi-User Sharing (Photon) Example has errors

### ISSUE THREAD

**Issue by genereddick** [microsoft/MixedRealityToolkit-Unity#5758]
## Describe the bug
Not sure this is an MRTK issue or with another team -- let me know if this should be filed elsewhere.

Working through the Connecting Multiple Users example here:
https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch1
Step 11:
Import the custom package called SharingAssetCollection which can be downloaded here:
(links to a download for SharingAssetCollection.unitypackage)

After import the project has the several errors. Most of these are as a result of it overwriting some of the classes in the Examples project. This can be fixed by re-importing the Examples again afterwards to get what is (I assume) the latest code.

However, one error remains:

The type or namespace name 'IMixedRealityHandPanHandler' could not be found ...HLSharingProject\Assets\BaseModuleAssets\Base Module Scripts\MoveWithPan.cs

## To reproduce
Work through the project steps per the link above

## Expected behavior
No errors

## Your Setup (please complete the following information)

- Unity Version 2018.4.7f1
- MRTK Version 2.0 Release

## Target Platform (please complete the following information)
NA

**Comment by wiwei** [comment]
I think the right avenue is probably here:

https://github.com/microsoft/MixedRealityLearning

@jessemcculloch

**Comment by genereddick** [comment]
Thanks. Reposted here:
https://github.com/microsoft/MixedRealityLearning/issues/14

**Comment by wiwei** [comment]
Thanks! I also pinged him offline - @jessemcculloch may correct me here but at least the wheels are turning now
