### ISSUE TITLE
SpatialObjectMeshObserverProfile gives back a serialization error when loading

### ISSUE THREAD

**Issue by Deukhoofd** [microsoft/MixedRealityToolkit-Unity#5762]
## Describe the bug

Ever since the 2.0 release build, whenever I build my project to the Hololens and launch it, it returns the following error:

> A scripted object (probably Microsoft.MixedReality.Toolkit.SpatialObjectMeshObserver.SpatialObjectMeshObserverProfile?) has a different serialization layout when loading. (Read 68 bytes but expected 156 bytes)
> Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?

After this the spatial observer does not function properly, and while it does draw the mesh, it doesn't appear to have a material set.

## To reproduce

My spatial awareness settings are as follows:

![image](https://user-images.githubusercontent.com/10423862/63591694-ca919d00-c5af-11e9-8695-39ccf171d9c4.png)

I deploy to the Hololens 1 in a Release configuration, launch the app, and the error occurs.

## Expected behavior

I expected the serialization error to not occur, and for the mesh to have its proper material set.

## Your Setup
- Unity Version 2019.4.6f1
- MRTK Version v2.0

## Target Platform

- HoloLens

**Comment by wiwei** [comment]
@davidkline-ms 

@Deukhoofd do you have any other repro steps, or is it literally grab package, take X sample scene, deploy to hololens1?

**Comment by Deukhoofd** [comment]
I've deleted all MRTK assets, and then imported them again. This seems to have resolved the issue. I can only assume it was some issue with upgrading from the RC to the actual build, but as this seems to have resolved it and I can't replicate it anymore I'm closing this now.

**Comment by boubouk50** [comment]
Exact same issue here.
I've cloned both the Default Mixed Reality Spatial Awareness System Profile and the Mixed Reality Spatial Object Mesh Observer Profile and the issue appeared.
I can't delete and import the MRTK assets since I don't use the default ones... I need your help to fix this.
Thanks,
Antoine.

_using MRTK 2.1.0 and Unity 2019.2.0f1 Personal for Hololens 1._

**Comment by xwipeoutx** [comment]
I've got this error showing as well as well - Unity 2019.2.14f1, MRTK 2.2.0.

My workaround is just to not have that observer (add it as needed during development, which isn't much), but it'd be simpler to not have to do that.

**Comment by boubouk50** [comment]
My "workaround" was to delete the clone and reclone it, and, of course, never ever modify it.
