### ISSUE TITLE
Code execution when opening ParabolicPointer in prefab mode leading to error

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5763]
## Describe the bug

When opening ParabolicPointer in prefab mode, an error is thrown because the ParabolocTeleportPointer has the ExecuteAllways attribute set, calls Start at that moment and soemwhere down the line Destroy is called, which is not allowed and maybe not even desired:

```
Destroy may not be called from edit mode! Use DestroyImmediate instead.
Also think twice if you really want to destroy something in edit mode. Since this will destroy objects permanently.
UnityEngine.Object:Destroy(Object)
Microsoft.MixedReality.Toolkit.Input.<Start>d__18:MoveNext() (at Assets/MixedRealityToolkit/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs:167)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<Start>d__18&)
Microsoft.MixedReality.Toolkit.Input.BaseControllerPointer:Start()
Microsoft.MixedReality.Toolkit.Teleport.TeleportPointer:<>n__0()
Microsoft.MixedReality.Toolkit.Teleport.<Start>d__21:MoveNext() (at Assets/MixedRealityToolkit/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs:110)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<Start>d__21&)
Microsoft.MixedReality.Toolkit.Teleport.TeleportPointer:Start()
```

I also received a different error once I created a variant, but I could not reproduce it a second time

## To reproduce

1. Open ParabolicPointer in prefab mode

## Expected behavior

No errors

## Your Setup (please complete the following information)

- Unity Version  2018.4.6f1
- MRTK mrtk_development

## Target Platform (please complete the following information)

- Editor

**Comment by Troy-Ferrell** [comment]
So does *PokePointer* prefab, *DefaultControllerPointer* prefab.  It's under `BaseControllerPointer.cs`

This is more or less an editor only bug

**Comment by Alexees** [comment]
I'm not sure if this is related, but creating either a full copy or a variant of the ParabolicPointer and using it instead of it has some really weird behaviour.
As soon as you run the game, NullReferenceExceptions are thrown. Checking the "original" prefab shows that the game has added a cursor to it.
Altering a prefab is something that should never happen and for some reason only happens to a copy or variant.
