### ISSUE TITLE
release notes:

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#5764]
## Describe the Issue
Following the upgrade procedure (RC2.x -> 2.0.0), customers may encounter errors like those shown in the following image.

![image](https://user-images.githubusercontent.com/13281406/63608684-70321580-c58a-11e9-8c66-3199af569336.png)

Customer reports state that after restarting Unity, the errors are resolved,

The release notes should be updated with the image and mitigation information.

## Existing Doc Link
ReleaseNotes.md

**Comment by wiwei** [comment]
@davidkline-ms, if this is something we should add, feel free to reopen (it feels like we could have just updated the docs in this case instead of filing the issue, since it seems like the text above could have just gone into the docs)
