### ISSUE TITLE
Manipulation Handler not documented correctly

### ISSUE THREAD

**Issue by benpaddlejones** [microsoft/MixedRealityToolkit-Unity#5776]
## Describe the bug
One Maninpulatin hander is attached to an object, changes to the release behaviour have no impact until the component is made a rigid body.

## To reproduce

Steps to reproduce the behaviour:

1. Go to attached the manipulation handler
2. Change behaviour to everything
3. Click play
5. Stop play and add a rigidbody component to the game object
6. Uncheck kinematic and gravity
7. Click play and see the correct behaviour

## Expected behaviour

1. Add manipulation handler
2. Choose behaviour
3. Object behaves as chosen

## Your Setup (please complete the following information)

- Unity Version 2018.4.6f1
- MRTK Version v2.0.0.0

## Target Platform
UWP & WMR

**Comment by benpaddlejones** [comment]
Not sure if this is a bug? The Manipulation handler should automatically add and configure the RB component or a documentation issue?

**Comment by benpaddlejones** [comment]
Also a feature request would be to have a public int that is a multiplier to the force.

**Comment by MenelvagorMilsom** [comment]
This is fixed in #5955, inspector now gives info on missing component.
![image](https://user-images.githubusercontent.com/47415945/64970116-15e05800-d89d-11e9-8519-16cb892b9156.png)

**Comment by thalbern** [comment]
@MenelvagorMilsom leaving this ticket with you for adding docs for the object manipulator

**Comment by thalbern** [comment]
documented properly now in Object Manipulator , v2.4
