### ISSUE TITLE
Provide option to install MRTK as an embedded Package using Unity 2019's new Package Manager UI

### ISSUE THREAD

**Issue by gerwalk** [microsoft/MixedRealityToolkit-Unity#5779]
## Describe the problem
There are currently several approaches to acquiring and implementing MRTK into a Unity project (e.g. downloading the 4 *.unitypackage files from the release page and importing their contents, or using git submodules) but these can be tricky to manage long-term and result in your Assets folder being cluttered by as many as 7 third party asset folders.

## Describe the solution you'd like
Starting in Unity 2018, Unity introduced a new "Package Manager" interface along with an update to the old concept of a Unity "package". The Package Manager is an alternative way of incorporating and managing extra tools and libraries (many of which Unity provides out-of-the-box now, such as TextMesh Pro, Unity Timeline, Test Framework, and more).

Unity provides documentation on how to create your own custom package, as well as various ways of distributing it: https://docs.unity3d.com/Manual/CustomPackages.html

If MRTK were provided in this new package.json format, we users could configure our Unity project to download and embedd MRTK into our project, all within the Unity Editor, and it could be configured in such a way to remain external to the Assets folder, preventing project and repo clutter, and allowing us to stay up to date with releases without needing to fiddle with git submodules or symlinks.

## Additional context
Unite 2018 talk introducing the Package Manager: https://www.youtube.com/watch?v=j4AAXS3HuMI
Unity documentation on the Package Manager https://docs.unity3d.com/Manual/upm-ui.html

**Comment by achaperon** [comment]
Hello,

For our development and to simplify the integration we have made a fork of the MRTK git and reorganize the whole folder to be able to generate 8 Unity package that we make available in our private repository. We have done it for the 2.3 release.

So it's possible but it implies few changes in terms of folders.

First we have moved all the resources to MRTK.Resources folders. 1 for each MRTK folder (MixedRealityToolkit, Examples, Extensions, Providers, SDK, Services, Test, Tools).
Then we have added a Resources exporter/importer mechanism.

Each resource folder is exported as a .unityPackage inside the corresponding package (for the package manager). Then there is an editor script that allow the user to import those resources when the package is imported via the Unity Package Manager (identical as TextMesh Pro).

All the resources are imported into an MRTK.Resources folder inside the folder Assets of your project. And then you can use every assets.

Note that it implies that each time you update your package, resources will be overwritten so your changes can be lost unless you make copy of it.

It could be great if the MRTK allows this kind of mechanism directly.
Also, I would appreciate to have a much more modular approach to use only what I need on my project. As the MRTK is growing more and more, having everything is not always a good solution.

Best regards.

**Comment by gerwalk** [comment]
Today I learned that there is now a NuGet package that provides pre-built MRTK. While that's a nice to have, I still think the preferred goal should be to have MRTK available as a set of **UPM Packages**. The Unity Package Manager is based on/similar to NuGet, but provides a much more "native" workflow in Unity, and installing a UPM Package would alleviate the need for users to have to first install "NuGetForUnity" which in my experience is somewhat clunky to begin with.

**Comment by keveleigh** [comment]
@gerwalk Good news! We (largely @davidkline-ms) are driving towards providing UPM as a distribution option for the 2.5 release. See https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8128 and https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8151 for examples of how it's going.

**Comment by gerwalk** [comment]
@keveleigh Fantastic, thanks for the update! I'll be sure to follow along with the progress.

**Comment by polar-kev** [comment]
Hey @gerwalk, UPM support was added in MRTK 2.5. We've gone a step further and created a new way to discover, acquire and update packages for the MRTK (and other Microsoft MR packages) that leverages UPMs.

Check out the page here to get started,
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/welcome-to-mr-feature-tool
