### ISSUE TITLE
Branch mechanics update (mrtk_development -> master)

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#5780]
This issue describes work that we're going to undertake in changing up our branching story. This is being filed about a week before this starts to take effect, to give people both internal and external a heads up on what's happening.

### What is happening?

Active development of the MRTK is going to move from the mrtk_development branch to the master branch. Instead of having an MRTK-specific named branch, we're going to adopt common terms that are used in other repos.

The default branch of the MRTK will be changed to master.

| Previous Branch Name  | New Branch Name |
| ------------- | ------------- |
| mrtk_development  | master |
| mrtk_release  | release/latest  |

### Why is this happening?

The main goal behind this proposal is to align the branch structure and defaults of the project to be optimized for contributors (both internal and external).

Specific examples of problems that this is trying to solve includes:

- When opening a new pull request, the default "base" branch is "mrtk_release", which is 99.999% of the time, never the right branch to go into. This extra step is confusing for new contributors (who regularly are issuing changes against mrtk_release, which is usually fairly old). This has at times led to PRs that were opened, fixing issues that were already fixed in mrtk_development, but because the default branch is mrtk_release, new contributors will attempt to re-fix the issue (because they didn't know that things were fixed in mrtk_development). For existing contributors, this is a minor pain, but one that is paid on each pull request.
- When completing a pull request, having the default branch be the active development branch allows for features like closing issues automatically via pull requests to work. Today, there's an additional step after each PR resolution, which people will (and have forgotten) to do, which involves closing the linked issues.
- Familiarity to existing branching naming - mrtk_development and mrtk_release are mrtk-specific modifications to the Git Flow workflow. Ideally we'd want to follow a naming pattern that is immediately familiar to new and old contributors alike (i.e. release/development, or master)

### What about the old branches?

The following branches will remain present (but locked so that no new changes will go into them).

- mrtk_development
- mrtk_release
- htk_development
- htk_release

These will be preserved so that external users who are directly linking to them (for example, git submodule-ing) will not be immediately broken. These branches will be kept around for some number of months, at which point for the mrtk_* flavors, we will likely spin up another issue and notice to finally delete them.

### When is this happening?

Below is the rough schedule for the transition. Note that Day 0 is the day that this issue is posted.

#### Day 0

Post issue/information to Github about the upcoming changes.
Post issue/information to Slack about upcoming changes.

#### Day 7

Add master branch to Github
Update the mrtk_pr pipeline to support the master branch (builds both master and mrtk_development)
Update the mrtk_docs pipeline to support the master branch (builds both master and mrtk_development)
Encourage new PRs to be issued against master

#### Day 8

Merge mrtk_development into master (to ensure that any new changes made to mrtk_development are in master)
Update the mrtk_CI pipeline to support the master branch (builds both master and mrtk_development)
Retarget existing PRs to target master instead of mrtk_development
Add an error message to mrtk_pr pipeline if the branch detected is mrtk_development (to recommend checking into master)
Change default branch to master

#### Day 9

Merge mrtk_development into master (to ensure that any new changes made to mrtk_development are in master)
Turn down mrtk_pr pipeline's support of mrtk_development
Turn down mrtk_docs pipeline's support of mrtk_development
Turn down mrtk_CI pipeline's support of mrtk_development

**Comment by wiwei** [comment]
Okay quick update here - I'm going to be out for a bit in the near future and won't be able to see this to completion in that timeframe, so I'm going to table this until I'm back.

Someone else could pick this up while I'm out once the other things in the current iteration are taken care of.

**Comment by Alexees** [comment]
Is it possible to change what's considered master branch for the time being?
https://help.github.com/en/github/administering-a-repository/setting-the-default-branch
