### ISSUE TITLE
Mouse Input 'Y' Axis Flips when Moving Main Camera

### ISSUE THREAD

**Issue by LaneMax** [microsoft/MixedRealityToolkit-Unity#5793]
## Describe the bug

I noticing when you have 'Unity Mouse Device Manager' added to the Input profile for using the mouse that when the Main Camera Y rotation is 180 degrees the Y-axis flips. 

## To reproduce

1) Open the MRTK example HandInteractionExamples.scene
2) Add the 'Unity Mouse Device Manager' to the Input Data Providers in the MixedRealityToolkit gameobject.
3) Start the scene and turn 180 degrees, the Y input will be flipped
4) Or before starting select the Main Camera and set the Y axis to 180 then start, the Y input will be flipped
Note: Maximize Game window to makes it easier to move around with the cursor enabled

## Expected behavior

The Input 'Y' Axis should not flip.

## Screenshots

In this example I have the real cursor enabled to show the problem
![Honeycam 2019-08-27 09-09-06](https://user-images.githubusercontent.com/8669498/63788513-7980f200-c8aa-11e9-9179-f5a94abad666.gif)

## Your Setup (please complete the following information)

- Unity Version 2019.1.0f2
- MRTK Version v2.0.0

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR
- Windows
- Mac

**Comment by davidkline-ms** [comment]
I will be checking in a fix for this as part of my work on #5838.

**Comment by davidkline-ms** [comment]
@michael-house, thanks for investigating the fix! My belief is that the Space.World bug was a result of not manually moving the camera in the editor during initial testing.
