### ISSUE TITLE
Navigation not working for WMR or xBox Controller

### ISSUE THREAD

**Issue by benpaddlejones** [microsoft/MixedRealityToolkit-Unity#5817]
The navigation does not move the scene and has no impact on the scene or main camera.

## To reproduce
1. Use the default profile
2. Change Navigation to "Dual Axis" in Input Action Settings
3. Change the left joystick of WMR controller or left joystick of xBox controller to navigation in Controller input mapping settings
4. Please play
5. The joystick of the left WMR controller or the xBox controller do not move the scene

## Expected behavior
At step 5 both the WMR controller and xBox controller should move the scene

## Your Setup (please complete the following information)

- Unity Version 2018.4.6
- MRTK Version v2.0.0.0

## Target Platform (please complete the following information)

- WMR immersive

## Additional context
In RC2 this worked for xBox and WMR controllers

**Comment by julenka** [comment]
Looks like this is blocking teacher + students, relevant conversation in stackoverflow: https://stackoverflow.com/questions/57469979/controlling-main-camera-with-xbox-controller-mrtk-unity/57503067?noredirect=1#comment103807725_57503067
