### ISSUE TITLE
About MRTK2 for Hololens Question

### ISSUE THREAD

**Issue by DioneLJH** [microsoft/MixedRealityToolkit-Unity#5818]
## Overview
I need to create the program for Hololens, but I can only package the msix file now.Only once again create a new Unity project to import MRTK2 can continue to pack out appx format file, and then packaged several times and became msix format file, msix format file cannot be installed on the Hololens, because for 10.0.18362.0 Hololens version requirements, and I only 10.0.17763.678 Hololens version. I don't know where the problem is, how can I solve this problem.
![微信截图_20190829120007](https://user-images.githubusercontent.com/45588391/63909282-aec94380-ca54-11e9-9ac3-8680c2cadb1e.png)

## Expected Behavior
APPX
## Actual Behavior
MSIX
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.4.1LTS
## Mixed Reality Toolkit Release Version
2.0

**Comment by wiwei** [comment]
@DioneLJH I haven't been using .msix for our own stuff, but from looking at a few resources online it seems like it should still be possible (https://docs.microsoft.com/en-us/windows/msix/msix-sdk/sdk-guidance)

It seems like the app that you're building has specified a minimum target SDK version that's really high - are you following the instructions here:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/BuildAndDeploy.html#building-and-deploying-mrtk-to-hololens-1-and-hololens-2-uwp

Note that the min target version is set super low (I'm guessing maybe your VS solution is setting that higher or changing that after the fact)

**Comment by DioneLJH** [comment]
I did it the way I did it in the tutorial, and when I packaged it, it changed to 18362 again.Now I'll try to change the configuration in appxmanifest.xml to see if it works. Thanks for your answer

**Comment by gilbdev** [comment]
from what i have observed, as soon as your minimal version is above18xxx, the solution produces a .msix
and you have to clean all generated files and build all again with 17763 or lower  to be able to get an .appx

i've also noted that when using the mrtk build window, the minimal version get occasionnaly changed to 18362 ; haven't tried it again since v2.0.0 though.
=> just checked, it seems UwpBuildDeployPreferences.MIN_SDK_VERSION is at 18362 @wiwei

**Comment by wiwei** [comment]
> UwpBuildDeployPreferences.MIN_SDK_VERSION is at 18362 @wiwei

Thanks for that callout - I'll get that fixed to avoid this confusion going forward.

**Comment by wiwei** [comment]
Actually yeah definitely thanks for the callout - that code never should have been setting the wsaMinSdkVersion (which is probably why some subset of the population was filing bugs about deployment issues).

Sending out a PR for this now.
