### ISSUE TITLE
Flag enum "Handedness" not binary compared (there's probably more)

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5821]
Not really a bug, but since Handedness is an enum flag, code could be refactored in that it properly does a binary comparison.
I've seen things like `value == any || value == both`, where `any` already includes `both`.

**Comment by Troy-Ferrell** [comment]
@alexees what code are you referring to? Any and both are actually different. 

Both only includes Left | Right
Any includes Other | Both

**Comment by Alexees** [comment]
I began to wonder when I saw this:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/95f16ac53bd19b2dd36f0a3d7fcee6bd5d0af001/Assets/MixedRealityToolkit/Providers/BaseInputDeviceManager.cs#L69-L71

**Comment by keveleigh** [comment]
Could possibly replace many of these comparisons with [`HasFlag`](https://docs.microsoft.com/en-us/dotnet/api/system.enum.hasflag?view=netframework-4.8)

**Comment by Troy-Ferrell** [comment]
Maybe a simpler line would simply be
pointerProfile.Handedness.HasFlag(controllingHand)?

**Comment by Alexees** [comment]
Oh nice.
You're finding bit check all over the place but nobody mentions this method :)
