### ISSUE TITLE
Support for Both Hand controllers

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5828]
## Describe the problem

While implementing the Oculus Go and the Oculus Quest, two things arose. First of all, the Oculus Go uses one controller for both hands, just one at a time.
Secondly, the "Oculus Integrations" packages provides one Prefab with all controller models for all Oculus platforms, which means the Quest uses the same prefab for both hands, just configures them differently (I did this using the ControllerVisualizer class).

I went for left first in case there's a check for left or right controller in the case of both.

## Describe the solution you'd like

I like to be able to choose "Both Hands" for a controller, so it does not matter which hand it's spawned for.

## Describe alternatives you've considered

Adding the same controller, once for left, once for right. But that's rather unnecessarily tedious

## Additional context

I already did that, just wanted to get my upcoming pull request its context first.

**Comment by davidkline-ms** [comment]
Question: Does Handedness.Any work for this scenario?

**Comment by Alexees** [comment]
> Question: Does Handedness.Any work for this scenario?

I guess so, did not consider this. The comment on both says:

> The controller is identified as being either left and/or right handed.

and the comment for other is
> Reserved, for systems that provide alternate hand state.

Since we are talking about left and right hand only I thought it should be as precise as that. I'm not even sure what an alternate hand state could be, but in this case it's definitely not.
If it does not matter though, I'll use any.

**Comment by Zee2** [comment]
Closing as stale. I believe this is essentially irrelevant for XRI (and the Go is now discontinued anyway... :( )

Please reopen if this is still a critical issue.
