### ISSUE TITLE
Input logger scene for new devices

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5832]
## Describe the problem

Now that there's active work on the workflow for adding additional devices to the MRTK it's rather tedious to get all the input reading from new controllers.

## Describe the solution you'd like

One Testscene with a big panel one can view all the possible inputs on the device and write them down to create a new DeviceManager.
Not all input comes from the Unity.Input class, so it should probably be generic enough that you maybe just plug a different script on it and reading comes from whatever new API there is.

## Describe alternatives you've considered

logging everything to the console and read that

**Comment by wiwei** [comment]
Tagging with Help Wanted - definitely would be an awesome thing to have for making new device onramp easier.

**Comment by keveleigh** [comment]
I have basically this scene lying around from the early vNext days. I'll go find it and clean it up!

**Comment by julenka** [comment]
@Davidkline-ms please don't close this issue until the scene in your PR #5902 has a scene description panel and a doc file.
