### ISSUE TITLE
TouchableVolume cannot be touched from all sides

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5836]
## Steps to reproduce
Add a cube to the scene and add a touchable volume to it, configure it to raise pointer events.

Add the following component to see when pointer events get raised:

```csharp
public class PrintPointerEvents : MonoBehaviour, IMixedRealityPointerHandler
{
    public void OnPointerDown(MixedRealityPointerEventData eventData)
    {
        if (eventData.Pointer is SpherePointer)
        {
            Debug.Log($"Grab start from {eventData.Pointer.PointerName}");
        }
        if (eventData.Pointer is PokePointer)
        {
            Debug.Log($"Touch start from {eventData.Pointer.PointerName}");
        }
    }

    public void OnPointerClicked(MixedRealityPointerEventData eventData) {}
    public void OnPointerDragged(MixedRealityPointerEventData eventData) {}
    public void OnPointerUp(MixedRealityPointerEventData eventData) {}
}
```

Move a simulated hand through all 6 faces of the cube.

## Expected Behavior
Touch start happens on all 6 faces.

## Actual Behavior
Touch start only occurs on some of the faces.

## Notes
This bug occurs because the ray that PokePointer builds changes as the finger goes through the surface of the cube. This is because the normal returned by NearInteractionTouchableVolume.DistanceToTouchable is not correct.

Below, the red cross is the ray start, and the cyan cross the result hit point. You can see that as the hand goes through the cube volume, the ray start moves all the way to the other side of the cube, causing the hit point to be large, 

![touchvolume](https://user-images.githubusercontent.com/168492/64040366-b8fd4780-cb11-11e9-8c6d-246af69ec849.gif)

I think if the finger is inside the volume, it would be great if we could not do a raycast and just return - the distance from the finger hit to the closest point on the volume bounds.

**Comment by lukastoenneMS** [comment]
@julenka Thanks for investigating this!

I couldn't really reproduce what you describe, entering any of the 6 cube faces gives a "TouchStarted" event as expected.

However, i noticed that the touchable still recomputes the closest point while you are moving around, and Unity seems to have some kind of quantization going on that makes it snap to particular points on a plane. Every time that happens i get a new touch event too.

I agree that the normal calculation in NearInteractionTouchableVolume is not great either. It will flip the normal direction when you are inside the collider. If backfaces are disabled in the raycast the collider then will not be hit by the ray (even though the DistanceToTouchable finds a closest point), and the resulting "hit point" is just the end of the ray. Unfortunately i don't think there is a way to detect if we are inside a collider or not (that would make closed manifold meshes a hard requirement). So this is something the touch system would have to keep track of: keep the last valid normal once touch starts.

**Comment by lukastoenneMS** [comment]
Did a bit of investigation:
1. Normal calculation in `NearInteractionTouchableVolume.DistanceToTouchable` is indeed wrong for the inside-collider case: it interprets the bbox center as a local vector but it's in fact world space. That's easy to fix:
    ```diff
    -                normal = samplePoint - transform.TransformVector(TouchableCollider.bounds.center);
    +                normal = samplePoint - TouchableCollider.bounds.center;
    ```
1. Inside the collider the `Collider.ClosestPoint` method doesn't work, so as a next-best solution we use the bbox center. This normal is "backward" though, which means that we cast from deep inside the collider. Inverting this normal might help get a more consistent ray step.
1. Focus locking doesn't work well for touch pointer. There is property on pointers `IsTargetPositionLockedOnFocusLock` which never gets unset. I'm not sure what the thinking behind this thing is, but it causes the hit point to be stuck on the collider while the pointer moves. When the distance between this fixed point and the pointer gets too large, the touch is ended and a new one started immediately, which is why you can see "random" touch events while moving in a collider.

**Comment by julenka** [comment]
> Focus locking doesn't work well for touch pointer. There is property on pointers IsTargetPositionLockedOnFocusLock which never gets unset. I'm not sure what the thinking behind this thing is, but it causes the hit point to be stuck on the collider while the pointer moves. When the distance between this fixed point and the pointer gets too large, the touch is ended and a new one started immediately, which is why you can see "random" touch events while moving in a collider.

Oh, I forgot about that! The goal of that is to allow things like the ray endpoint to "stick" to the collider when you are moving it, allowing for bendy beams, etc. However, you point out a great case where `IsTargetPositionLockedOnFocusLock` should be false. We should probably save the state on pointer down, set to false, then restore on pointer up. Or, perhaps even just set `IsTargetPositionLockedOnFocusLock = false` in Pointer.

**Comment by julenka** [comment]
Re-opening to track work to add a regression test for this.

I think a test case that does the following would work:

1. Places cubes in 10 random positions around origin (say, within a 2 meter radius from origin)
1. For each cube, touch the cube from all 6 sides, and ensure touch up and down events are received.
1. To ensure we don't regress behavior in future, I think we should add this test before we close the bug related to this.

**Comment by julenka** [comment]
> Focus locking doesn't work well for touch pointer. There is property on pointers IsTargetPositionLockedOnFocusLock which never gets unset. I'm not sure what the thinking behind this thing is, but it causes the hit point to be stuck on the collider while the pointer moves. When the distance between this fixed point and the pointer gets too large, the touch is ended and a new one started immediately, which is why you can see "random" touch events while moving in a collider.

Lukas, great catch. I've created a bug for this: #5873. Marked it as Current iteration because it is a defect in core system (touch input).
