### ISSUE TITLE
Android rendering problem

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5845]
## Describe the bug

Activating the BoundingBox on an Oculus Quest instantly turns this:

![de holospaces helios-20190901-225026](https://user-images.githubusercontent.com/32508825/64082179-65eee480-cd0b-11e9-93bf-94193bc0251b.jpg)

into this:

![de holospaces helios-20190901-225036](https://user-images.githubusercontent.com/32508825/64082168-39d36380-cd0b-11e9-8ac3-7b27f7be2025.jpg)

## To reproduce

1. Build a BoundingBox to the Oculus Quest somehow

## Expected behavior

Normal rendering

## Your Setup (please complete the following information)

- Unity Version 2018.4.6f1
- MRTK Version mrtk_development

## Target Platform (please complete the following information)

- Oculus Quest

**Comment by SimonDarksideJ** [comment]
Two things, MRTK doesn't support the Oculus Quest atm.   Additionally, the Bounding Box requires a Wireframe shader that uses Geometry shaders at present.  The Quest GPU does not support Geometry shaders at this time.

**Comment by Alexees** [comment]
@SimonDarksideJ I should have mentioned, that I'm working with @davidkline-ms on making 3rd party platform integration possible. I am working on integrating the Quest.
Do you have a suggestion on how I can use the BoundingBox wihout the use of GeometryShaders?

**Comment by SimonDarksideJ** [comment]
That is the 10 million $$$ question. Might be worth reaching out to @wassx and @Cameron-Micka our resident shader bobbins

**Comment by Cameron-Micka** [comment]
Hi @alexees, that is an interesting bug! Is there anything interesting in the Unity log file when this occurs? It looks to me like a potential GPU driver issue, but it's hard to tell with these things. (Sounds like I need to pick up an Oculus Quest). 

Also, the current bounding box shaders only rely on vertex and pixel shaders. So, they should work on a platform that doesn't support geometry shaders.

**Comment by SimonDarksideJ** [comment]
That's curious @Cameron-Micka as I was under the impression the bounding box renderer used the wireframe shader.  The current wireframe shader isn't supported on Quest.

**Comment by Cameron-Micka** [comment]
It does look like it does, but it's just using the opaque border option on the _MRTK/Standard_ shader. AFAIC the only gemoetry shaders in the MRTK are _MRTK_Wireframe_ and _HandTriangles_.

**Comment by Alexees** [comment]
@Cameron-Micka 
This is the log I receive from logcat:

```
09-05 12:11:23.038 10941 10989 E Unity   : The given primitive topology does not match with the topology expected by the geometry shader
09-05 12:11:23.038 10941 10989 E Unity   :
09-05 12:11:23.038 10941 10989 E Unity   : (Filename:  Line: 0)
09-05 12:11:23.038 10941 10989 E Unity   :
09-05 12:11:23.058 10941 10989 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
09-05 12:11:23.058 10941 10989 E Unity   :
09-05 12:11:23.058 10941 10989 E Unity   : (Filename: /Users/builduser/buildslave/unity/build/Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 340)
```

**Comment by Cameron-Micka** [comment]
Oh! Yeah that property name might be misleading. The wireframe material property usually takes another non traditional wireframe material (you can see which one in the BondingBox example scene). 

This might be a good bug to send to Unity they should gracefully handle the loading of shader’s not available  for  the current platform.

**Comment by Alexees** [comment]
Funny enough, when running just the wireframe shader on a cube in an empty project/ scene, the error is different:

```
09-06 09:06:19.434  4427  4444 D Unity   : WARNING: Shader
09-06 09:06:19.434  4427  4444 D Unity   : Unsupported: 'Mixed Reality Toolkit/Wireframe' - Pass 'PassName' has no vertex shader
```

**Comment by Cameron-Micka** [comment]
Ha, weird. Does this built-in geometry shader cause the same issue? https://github.com/TwoTailsGames/Unity-Built-in-Shaders/blob/master/DefaultResourcesExtra/VR/Shaders/SpatialMappingWireframe.shader

**Comment by SimonDarksideJ** [comment]
Yes, that is the base shader we were using in the XRTK too, it also fails.  Any geometry shader will fail on Oculus

**Comment by Alexees** [comment]
Just to round up, what's the solution here? Is there a way of providing a Android specific shader pass, or is this a problem Unity needs to fix? I'd gladly report a bug if I knew what bug it actually is, in detail.

**Comment by Cameron-Micka** [comment]
I would recommend trying to solve this issue from two directions. First try using just the HoloLens2 bounding box materials (they can be seen used in the BoundingBox and HandInteraction example scenes). Since they don’t use a geometry shader they “should work.” I would also recommend notifying Unity of a bug where the engine doesn’t seem to gracefully handle when loading an unsupported shader type (geometry shader) on Oculus Quest. I can also try to repo this locally next week.

**Comment by Alexees** [comment]
Guys, the shader works. With #5908 applied errors are gone and a cube the shader is applied to, shows the wireframe properly. Since the fallback shader is the default diffuse, seeing the triangles makes this clear.
The above screenshot ahows the instantiated the shader at runtime since I wasn't using any ShaderVariantCollection and maybe broke because if this.

Bottom line, Oculus Quest supports geometry shaders

**Comment by SimonDarksideJ** [comment]
That would be awesome if it does indeed work. Gonna grab it and begin testing.  

Curious if you say the Quest supports geometry shaders as Oculus says it doesn't :P  But if it works, I'm certainly not going to argue :D

**Comment by Alexees** [comment]
If it doesn't then I completely lose my mind on this stuff. I had a wireframed cube on the quest and unless it's the diffuse shader, a hidden pass, UnityMagicShaderCrossCompiler or whatnot, the geometry shader did that.

**Comment by Cameron-Micka** [comment]
That’s great to hear! Do you have a screenshot of the wireframe  cube? Just curious since the default bounding box materials aren’t usually configured to be wireframe.

**Comment by Alexees** [comment]
It's really just the MRKT_Wireframe.shader that I accidentially plugged into the BoundingBox, which kicked off the whole "does not work" process, but I think this Oculus Quest screenshot is proof, that it really works despite all assumptions about geometry shader support:

![image](https://user-images.githubusercontent.com/32508825/65057342-c10f1100-d972-11e9-9414-135872997530.png)

**Comment by Cameron-Micka** [comment]
Awesome! That does appear to be working on Quest. Thanks for taking a look at this.

**Comment by SimonDarksideJ** [comment]
I've just tested the exact same shader in a clean project, and no joy.  Object with the shader material on it does not render.
Can you share the rest of your Android project setup @Alexees please.

P.S. the shader we already had in the XRTK was already using the keyword that was added to the MRTK shader.

**Comment by SimonDarksideJ** [comment]
Check the PR, after a LOT of testing, this fix only works in a non-MRTK solution.
Once you have MRTK active in your scene, it breaks.  SO it must be something to do with the camera settings the MRTK is applying.  The same effect is in XRTK, so likely something common.

**Comment by xtr33me** [comment]
Found this trying to research a similar issue to that with which the OP stated and just wanted to add a bit more info regarding the Quest hardware. It is running the **Adreno 540 GPU** which supports **GLES 3.2** and therefore does support geometry shaders. I have seen some that have had no issues running certain geometry shaders, but there is definitely still an issue as I'm dealing with the black screen and neon colored objects in one eye. Should I figure out what part of the GS is causing this I will post here.

**Comment by keveleigh** [comment]
@RogPodge, could be worth validating this now that #8088 has gone in

**Comment by RogPodge** [comment]
Confirmed to be working now :)
