### ISSUE TITLE
Pointer permanence based on scene lifetime

### ISSUE THREAD

**Issue by quakeulf** [microsoft/MixedRealityToolkit-Unity#5846]
## Describe the problem
Currently interaction pointers are created and deleted upon detection of hands and so forth. This creates issues when trying to reference them etc. as well as might create hitches in performance.

## Describe the solution you'd like
Make pointers at the start and keep them during the lifetime of the scene. Instead of creating and deleting, toggle them on and off. This goes well with object pooling, and also if you would need HOLP.

## Describe alternatives you've considered
My own system, but it is time-consuming and costly.

## Additional context
Sadly no code or anything as I have the limited times for this...

**Comment by wiwei** [comment]
FWIW, this has come up in the past as well: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4223

Probably something for us to consider next iteration
