### ISSUE TITLE
Controller code refactor

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5847]
## Describe the problem

A lot of the hierarchy code of the MRTK controllers can be refactored in being more readable, a little more automatic and easier to use for new controllers.

## Describe the solution you'd like

**BaseController**:

1. The method SetupDefaultInteractions is abstract. First of all, not all controllers do need to call this, but have to implement it anyway. Second, the only place this is ever called is in SetupConfiguration of the same class. And third, overrides of the default controller mappings and SetupDefaultInteractions makes it kind of redundant what mapping will be used. I think this can be refactored to auto assign a mapping based on handedness by just overriding any of the three DefaultInteractions, as in case of null, DefaultInteractions will be used. (Leaves the case where the base class defines left and/or right and you only want to provide default)
    - UnityTouchController is the only class that does more than just assigning mappings, but that could be done in the constructor.

2. Mouse and Joystick controller switch over Interactions[i].AxisType every frame even though the method called does not change. It would be easier to add them to MixedRealityInteractionMapping directly and just call them one after the other

3. There is no apparent reason for SetupConfiguration to exist at all. All it get's passed in is either known by the constructor of the type, or by the type itself. The constructor in a lot of cases does nothing and could very well undertake SetupConfiguration's roll. As an example, the MouseController passes the type of itself to it.

**MixedRealityInteractionMapping**:
1. The mapping ID, as far as the overridden default mappings go, follow their containing array index exactly. This could be factored out of there and therefore make it less error prone to put numbers the wrong order or use duplicates...

## Additional context

In my opinion it's worth streamlining this as good as possible so new controllers can be added more easily and existing controllers can be read without thinking about why they are so different where they shouldn't be. As an example, the structure of the MouseController looks completely different than the other controllers (using if statements instead of switch, calling things in different locations than the others...).

**Comment by SimonDarksideJ** [comment]
A Little feedback from the operation of controllers:

> The method SetupDefaultInteractions is abstract.
The Windows / OpenVR platforms don't use this much.  However other SDK's and such require subtle overriding for this function.  It's simply abstract to allow platform overriding as necessary.

> Mouse and Joystick controller switch over Interactions[i].AxisType 
Mouse doesn't use Switch, Joystick does.  However, this is the standard pattern, looping through the Interaction Mappings assigned to the controller in an efficient way.  For each configured interaction, we get the relevant data from the configured input, which is wholly dynamic.

> There is no apparent reason for SetupConfiguration to exist at all.
SetupConfiguration (like Setup Mappings) is an abstract capability to initiate any given platform. Granted, Windows and Unity input don't need it (simply because Unity does this internally). Almost every other platform does need this to perform pre-setup for that given platform.

While the suggestions are well thought through, they don't include the scope for all other platforms.
If however, (@davidkline-ms ) the intention is not to support other platforms or rely solely on OpenXR when it's available, this may be worth trimming down to avoid other platforms complexities

**Comment by Alexees** [comment]
> Mouse doesn't use Switch, Joystick does. However, this is the standard pattern, looping through the Interaction Mappings assigned to the controller in an efficient way. For each configured interaction, we get the relevant data from the configured input, which is wholly dynamic.

What I meant with this is that the linking between method and axistype is reevaluated every time the loop runs. If the methods were moved into the definition of the mappings (as System.Actions for example) they could just be called, no matchmaking.

> SetupConfiguration (like Setup Mappings) is an abstract capability to initiate any given platform. Almost every other platform does need this to perform pre-setup for that given platform.

The thing about this method is that it's called immediately after the constructor was and that it's two parameters are Type, which the controller that was instantiated just IS, and InputSourceType, which is the same case. The method is defined in BaseController, so we are talking about controllers only and the only exceptions from being a controller are two hand classes that define this as hand. I don't see where it's relevant to tell the Hand class that it's a hand.

**Comment by SimonDarksideJ** [comment]
> What I meant with this is that the linking between method and axistype is reevaluated every time the loop runs. If the methods were moved into the definition of the mappings (as System.Actions for example) they could just be called, no matchmaking.

Can you elaborate on this point?  Not seeing where you are heading. 
Based on the Axis, each platform interrogates for the data differently, this is determined in either the dataprovider or controller depending on the complexity of the API.

And the Axis type is evaluated for each mapping per update, to query the platform data and check it.

**Comment by Alexees** [comment]
> Can you elaborate on this point?

Sure. As you can see in the following code, for example AxisType.Digital always maps to UpdateButtonData. That doesn't change. And it's always the Interactions that are getting looped over switching on their axis every time. The method used by each axis could very well be part of the interaction itself, evaluated once and assigned.
Now Interactions are assigned in two places, once per the BaseController constructor (which is acutally never the way it's getting assigned, I checked the references) and in the AssignControllerMappings method of it. Just like overriding what default mappings go into the controller in derived classes, AssignControllerMappings could be made abstract so you can override which method goes into which mapping, assigning them once and for the rest of the application just iterate the interactions and call their System.Actions. Something like that, I hope that was clear enough.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/9b6b91aa5729f5710ed5db1b7e80824416cb88cf/Assets/MixedRealityToolkit/Providers/UnityInput/GenericJoystickController.cs#L52-L73

**Comment by keveleigh** [comment]
>The thing about this method is that it's called immediately after the constructor was and that it's two parameters are Type, which the controller that was instantiated just IS, and InputSourceType, which is the same case.

InputSourceType as a parameter was deprecated in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6653. I'll investigate the rest of your suggestions as part of my controller rework.

**Comment by keveleigh** [comment]
@Alexees 

>BaseController:
>
>The method SetupDefaultInteractions is abstract. First of all, not all controllers do need to call this, but have to implement it anyway. Second, the only place this is ever called is in SetupConfiguration of the same class. And third, overrides of the default controller mappings and SetupDefaultInteractions makes it kind of redundant what mapping will be used. I think this can be refactored to auto assign a mapping based on handedness by just overriding any of the three DefaultInteractions, as in case of null, DefaultInteractions will be used. (Leaves the case where the base class defines left and/or right and you only want to provide default)

This was updated to be `virtual` in #7374, to keep allowing devs to override it if needed. I refactored down a combination of the actual implementations of this class (which were largely identical). The existing version was additionally deprecated and replaced with a parameter-less version that gets the handedness from the controller itself.

>Mouse and Joystick controller switch over Interactions[i].AxisType every frame even though the method called does not change. It would be easier to add them to MixedRealityInteractionMapping directly and just call them one after the other

I think this is an interesting point, though it does match the pattern in the other controllers at the moment (other than switch vs ifs, like you mentioned). I'm working on a larger controller refactor proposal, and will see if I can address this there. Filed https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7433 to track.

>There is no apparent reason for SetupConfiguration to exist at all. All it get's passed in is either known by the constructor of the type, or by the type itself. The constructor in a lot of cases does nothing and could very well undertake SetupConfiguration's roll. As an example, the MouseController passes the type of itself to it.

This method was deprecated in #7375 with the work moved to the constructor.

>MixedRealityInteractionMapping:
>
>The mapping ID, as far as the overridden default mappings go, follow their containing array index exactly. This could be factored out of there and therefore make it less error prone to put numbers the wrong order or use duplicates...

This last part hasn't yet been addressed, but I filed a more targeted issue for it: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7432

>In my opinion it's worth streamlining this as good as possible so new controllers can be added more easily and existing controllers can be read without thinking about why they are so different where they shouldn't be.

Agreed! That's the main focus of my upcoming proposal.
