### ISSUE TITLE
World Anchor Persistence

### ISSUE THREAD

**Issue by bikramthapa18** [microsoft/MixedRealityToolkit-Unity#5848]
I have being working with the world anchor store, saving and retrieving world anchors for correct positioning of objects in the spatial mapped environment. But due to some reason when I remove all holograms from the **SETTINGS > HOLOGRAMS > REMOVE ALL HOLOGRAMS** panel of the _Hololens_, the application is not able to retrieve the world anchor when I run it.
Is it related to the world anchor being stored locally in the _Hololens_ or should I go ahead with the Azure spatial anchors?

**Comment by wiwei** [comment]
@keveleigh to keep me honest.

I believe that the world anchor store (both the MRTK's experimental thing on top of the Unity WorldAnchorStore and the Unity WorldAnchorStore itself

https://docs.unity3d.com/560/Documentation/ScriptReference/VR.WSA.Persistence.WorldAnchorStore.html)

Are just built on top of the underlying OS's anchor/storage stuff, so this is all getting stored locally on the HoloLens.

https://docs.microsoft.com/en-us/hololens/hololens-spaces

If you need to make sure they persist across devices/hololens wipes you'll definitely want to go with ASA instead.

**Comment by bikramthapa18** [comment]
Thank you @wiwei for the information. Does WorldAnchorTransferBatch help sharing the world anchors in a robust way?
https://docs.unity3d.com/2019.3/Documentation/Manual/windowsholographic-anchorsharing.html

**Comment by wiwei** [comment]
@bikramthapa18 I haven't used that myself, but reading the docs I assume that it would be well purposed for that.

Note that it doesn't provide the network transport layer (i.e. assuming you already have some way of communicating between the two devices).

FWIW it might be interesting to try using ASA instead (if it works for your scenarios - i.e. always being connected to the internet instead of being connected only to some local network).

**Comment by bikramthapa18** [comment]
@wiwei Thank you for your help. I came across a post that the world anchors cannot be shared across multiple platforms like ios and android using the WorldAnchorTransferBatch. ASA is the only option as far as I have researched!

**Comment by wiwei** [comment]
@bikramthapa18, yeah I would assume that WorldAnchorTransferBatch wouldn't work for other platforms because it's part of the "WSA" namespace (i.e. Windows Store Apps, which are specific to apps in the windows store and not Android/iOS).

Because this question has been answered, I'm closing this out
