### ISSUE TITLE
Apps deployed on HoloLens are in a "screen form"

### ISSUE THREAD

**Issue by Lepiaf95** [microsoft/MixedRealityToolkit-Unity#5850]
## Describe the bug

When i play an app that i deploy on HoloLens, the device show me just a "screen" of the first scene.

## To reproduce

Create a new project
Add Mrtk on it
build it
Deploy it on HoloLens 1
Play the app
See the problem

## Expected behavior

Normal behavior of an holoLens's application : immersion of the user.

## Screenshots

![Capture](https://user-images.githubusercontent.com/45283124/64121685-da736300-cd9f-11e9-88ae-f406f35d8760.PNG)

## Your Setup (please complete the following information)

- Unity Version 2019.1.7f1
- MRTK Version v2.0.0

## Target Platform (please complete the following information)

- HoloLens 1

**Comment by Alexees** [comment]
Might be happening when the "Windows Mixed Reality" Virtual Reality SDK is missing in the XR Settings of the Player Settings.

**Comment by Lepiaf95** [comment]
![Capture](https://user-images.githubusercontent.com/45283124/64154892-017a7500-ce32-11e9-8561-4fbec2ecab61.PNG)

I have this settings

**Comment by wiwei** [comment]
Seems similar to this report:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5447

Note that the MRTK doesn't have control over how Unity renders things on the device (if it could, that would be interesting... but weird... but interesting!).

For simplicity's sake, I would just try to get things working WITHOUT the MRTK, and you should be able to then copy the exact settings and get things to work with the MRTK.

I remember hearing about a buggy WMR package (i.e. UPM package) - I used 1.0.12 recently which works fine.

**Comment by Lepiaf95** [comment]
It was actually in the XR settings with the "WSA Holographic...".
Problem solved, thank you.
