### ISSUE TITLE
HolographicButton icons

### ISSUE THREAD

**Issue by Weasy666** [microsoft/MixedRealityToolkit-Unity#5852]
## Describe the problem

I can't seem to find an easy way to change the icon on a HolographicButton, like it was possible with the Holo Toolkit.

## Describe the solution you'd like

I would like to be able to easily change the icon of a HolographicButton, like possible in Holo Toolkit, see below image:
![image](https://user-images.githubusercontent.com/11967542/64163228-23c7bf00-ce41-11e9-8328-4f3e7b539973.png)

Another nice to have would be a standard MixedReality Icon set included in MRTK, like Segoe MDL2 is for Windows applications.

**Comment by wiwei** [comment]
@cre8tivepark

I think this falls under: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5463 (as in, is a specific instance of the general pain highlighted by that).

I think that the buttons generally aren't made like a typical API surface (but are just a prefab) - I think at the very minimum here we should have documentation explaining how to do this.

**Comment by davidkline-ms** [comment]
MRTK3 has a new design language and prefab structure. It is unlikely that significant UX changes will be made in MRTK v2.x
