### ISSUE TITLE
Cast Error in Interactable

### ISSUE THREAD

**Issue by asugaya-apx** [microsoft/MixedRealityToolkit-Unity#5856]
## Describe the bug

We receive a cast error in the OnEnable method in the Interactable class.

## To reproduce

1. Enable a disabled Interactable GameObject (occurs in editor as well)

## Workaround/solution
Adding the following null/type checks to line 453 in Interactable.cs solves the issue:
` focusingPointers.RemoveAll((focusingPointer) => focusingPointer.FocusTarget == null||focusingPointer.FocusTarget.GetType()!=typeof(Interactable)|| (Interactable)focusingPointer.FocusTarget != this);`

## Expected behavior

The code should be resilient to FocusTargets that may be null or non-Interactable GameObjects.

## Your Setup (please complete the following information)

- Unity Version: 2019.1.8f1
- MRTK Version: mrtk-release

## Target Platform (please complete the following information)

- HoloLens 2
- Also occurs in editor

**Comment by davidkline-ms** [comment]
Thanks for the report @asugaya-apx!

**Comment by wiwei** [comment]
@julenka, this seems like something we should loop into our current Interactable push.

**Comment by julenka** [comment]
I can take a look since I've been in interactable. Or if @CDiaz-MS finishes her stuff early i'll have her take a look.

**Comment by davidkline-ms** [comment]
I'll take this one.

**Comment by davidkline-ms** [comment]
(focusingPointer.FocusTarget as Interactable) != this)

should be the functional equivalent to 

focusingPointer.FocusTarget == null||focusingPointer.FocusTarget.GetType()!=typeof(Interactable)|| (Interactable)focusingPointer.FocusTarget != this)

in fact, that is essentially what the as keyword is doing; checking for null and then checking the type of focusingPointerFocusTarget

**Comment by davidkline-ms** [comment]
once i can get a repro with the current code, i will make the change and confirm the fix.

**Comment by asugaya-apx** [comment]
Awesome, thank you! Let me know if we can help with reproing this -- that said, I'm not 100% sure we know the exact steps to repro ourselves. At the very least, we can replace our code with this if need be to confirm it fixes.

**Comment by davidkline-ms** [comment]
I am not able to repro in the editor, However, using the c# as keyword is preferable to c-style casts, which will protect against what is reported in this issue,

The change will be to replace 

```
(Interactable)focusingPointer.FocusTarget != this
```

with

```
(focusingPointer.FocusTarget as Interactable) != this
```

**Comment by davidkline-ms** [comment]
> At the very least, we can replace our code with this if need be to confirm it fixes.

Yes, please do!

**Comment by davidkline-ms** [comment]
Thanks @asugaya-apx!

**Comment by davidkline-ms** [comment]
@asugaya-apx, please reopen if the change does not fix your application. Thanks!
