### ISSUE TITLE
Cursor that resembles the shell cursor

### ISSUE THREAD

**Issue by killerantz** [Microsoft/MixedRealityToolkit-Unity#586]
I've been working on a mesh based cursor that looks and functions like the shell cursor. It shows a dot when not in contact with a collider, turns into a ring when colliding. The size changes when a source and gesture are detected. It also has a point light similar to the shell. I'm submitting a pull request for my branch so you can let me know what you think. #587

**Comment by StephenHodgson** [comment]
Thanks!  We did have a cursor that resembled the shell cursor already ([defaultCursor](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Prefabs/Cursor/DefaultCursor.prefab)), but it's wonderful you've shared yours as well.

**Comment by jessemcculloch** [comment]
So, just because i'm curious, how does this one differ from the defaultCursor we already have?

**Comment by killerantz** [comment]
It's visually more like the shell cursor, more refined.

**Comment by jessemcculloch** [comment]
Thanks @killerantz.  I wonder if it would be a good idea to deprecate the defaultCursor, or replace it with your implementation, rather than have two very similar cursors in the toolkit.  Thoughts from anyone else?  @StephenHodgson?

**Comment by HaraldHeide** [comment]
Would like a cursor that would be easy to notify from your scripts and then would give a nice visual indication if you are in Move Rotation or Scale mode when hovering above a gameObject..

**Comment by StephenHodgson** [comment]
@HaraldHeide, that exists already: [CursorModifier.cs](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/Cursor/CursorModifier.cs)
