### ISSUE TITLE
Disable firing FocusHandler OnExit event for children objects

### ISSUE THREAD

**Issue by asugaya-apx** [microsoft/MixedRealityToolkit-Unity#5863]
## Describe the problem

When focusing on a child object that also responds to focus events, the parent receives the onExit event. This seems less intuitive, though it's understandable why this occurs.

## Describe the solution you'd like

We would like the onExit event to only fire when the focus moves away from the entire hierarchy under and including the game object in question.

## Describe alternatives you've considered

We currently perform a check in each of the parent gameobjects in the onExit method to see if the newly focused object is a child, which works well.

**Comment by wiwei** [comment]
@davidkline-ms, @julenka FYI

Something to consider is that others may actually be depending on this current behavior, so it would have to be some opt-in behavior (or something else to make sure we don't break existing users)

**Comment by wiwei** [comment]
@asugaya-apx have you hit any perf/issues associated with doing this chain walking, or has this mostly worked well for you?

**Comment by julenka** [comment]
Hm I'm curious what other UX frameworks do, like react, winforms, wpf.

**Comment by asugaya-apx** [comment]
Apologies for the late response here! @wiwei we haven't seen any major performance hits.

**Comment by asugaya-apx** [comment]
@julenka that's a good question -- one possibility is something like in Javascript in which they're handled as two separate events (mouseleave vs mouseout), where the former is bubbled and the latter isn't. https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event

**Comment by polar-kev** [comment]
Closing due to low interest from community.
