### ISSUE TITLE
Touching the Oculus Rift motion controller performs a press (select)

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5869]
## Describe the bug

When using Rift or Quest controllers, just touching the triggers performs select actions, hence button presses and such.
That's because PrimaryIndexTrigger Touch and Press use the same keycode they listen to, which in case of Press is wrong.

The mappings, Unity's mapping description and Oculus's official mapping support seem to be out of order anyways.

While OculusTouchController.cs has 4 PrimaryIndexTrigger definitions, Unity's documentation only contain 3, of which OculusTouchController.cs misses out on "Squeeze", which is probably "Axis1D.SecondaryIndexTrigger" according to its axis.

PrimaryIndexTrigger Press is therefore redundant and basically needs to be a digital implementation of PrimaryIndexTrigger Squeeze.

the problem is that the default "select" InputAction is used for digital types, but the Trigger press is analogue and there is no logic for combining the two yet.

## To reproduce

1. Build to a Rift and touch the trigger. You'll already see the beam becoming a straight line

## Expected behavior

Only pulling the trigger performs the default select action

## Your Setup (please complete the following information)

- Unity Version 2018.4.6f1
- MRTK Version mrtk_development

## Target Platform (please complete the following information)

- OpenVR
- Oculus Quest

**Comment by Alexees** [comment]
The only KeyCode fired for the trigger press is Mouse0 (on the Quest that is), but this goes for both controllers.
What would be the best approach for reading an axis digitally? As far as I can tell, InputActions match if the ID and the AxisType is identical. This means even though its a SingleAxis reading, it must be digital and the implementation for that reads keycodes...

**Comment by SimonDarksideJ** [comment]
Just reviewing through this and looks like some changes happened somewhere that changed the default behaviour, so I'll sort out a PR to resolve them, both here and the XRTK.

a few points:
* 1, "Axis1D.PrimaryIndexTrigger" - this is the axis value for the trigger mapped to axis 9 which is the Squeeze value in Unity OpenVR
* 4, "Axis1D.PrimaryIndexTrigger Press", should be the digital equivalent of this but as you point out its been mapped to the Touch keycode
* Touching the trigger should start the pointer / select, if you feel it shouldn't then you need only update the controller mapping to your preference.

I'll get the Axis / button mappings cleaned up

**Comment by Alexees** [comment]
> * Touching the trigger should start the pointer / select, if you feel it shouldn't then you need only update the controller mapping to your preference.

Are you sure about that? Just putting the finger into a rest position on the controller clicks buttons. Or is that something Oculus recommends with these kinds of controllers?

**Comment by SimonDarksideJ** [comment]
Not a recommendation, it's just how the shell operates.  Try switching between hands in the shell.
But it's a developer choice in the end and you configure the mapping for how you want it to work for your project.

**Comment by Alexees** [comment]
> Not a recommendation, it's just how the shell operates. Try switching between hands in the shell.
> But it's a developer choice in the end and you configure the mapping for how you want it to work for your project.

I don't have a Rift here, but the Quest's controllers seem to be similar enough that they should work the same and on the Quest, touching is not enough, I have to pull the trigger to activate anything in the shell.
Of course I can configure this to my liking, but I rather stick to the defaults and how the shells do things. If a touch is the default on the Rift and a trigger pull on the Quest, so be it, but it feels inconsistent.

**Comment by SimonDarksideJ** [comment]
OK, I'll do some more testing on the Rift and Quest for this update and ensure it matches.
