### ISSUE TITLE
Oculus Rift controller can not evaluate Near Touch at all

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5871]
## Describe the bug

Neither Near touch nor Trigger Touch can be evaluated to true by the controller. That's because the MixedRealityInteractionMapping for that defines the AxisType as digital and provides an Axis code instead of a keycode for it.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/6dd8bd5d17d6ba49a09b4532048a80b520622242/Assets/MixedRealityToolkit.Providers/OpenVR/OculusTouchController.cs#L35

The evaluating code however only checks keycodes in case of the digital axis type, which in this case is Keycode.None.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/6dd8bd5d17d6ba49a09b4532048a80b520622242/Assets/MixedRealityToolkit/Providers/UnityInput/GenericJoystickController.cs#L86-L91

Maybe the AxisType just needs to be changed to SingleAxis and that's it.

## Expected behavior

NearTouch is interpreted some boolean way

## Your Setup (please complete the following information)

- Unity Version 2018.4.6f1
- MRTK Version mrtk_development

## Target Platform (please complete the following information)

- OpenVR
- Oculus Quest

**Comment by SimonDarksideJ** [comment]
This is certainly a bug and not sure where the change to remove the axis -> digital check disappeared to.  I'll get that reinstated and with #5869 I'll clean up the mappings.

**Comment by keveleigh** [comment]
This should be fixed
