### ISSUE TITLE
MRTK V2 running on Android and iOS.

### ISSUE THREAD

**Issue by TakahiroMiyaura** [microsoft/MixedRealityToolkit-Unity#5875]
## Describe the problem

 I want to develop multi platform development  using MRTK V2.

## Describe the solution you'd like 

MRTK V2 can develop XR multi devices(Hololens ,Oculus, Open VR...),but  
I want to develop AR application for mobile devices(ex android,iOS ...) using MRTK.

## Describe alternatives you've considered

Using ARFoundation and MixedRealityInputSystem(UnityTouchDeviceManager),
I've been able to run on Android and iOS.

## Additional context

**Comment by thalbern** [comment]
assigned Cameron for android shader support

**Comment by Cameron-Micka** [comment]
Thanks! I have a few shader fixes coming soon.

**Comment by Cameron-Micka** [comment]
A handful of shader fixes are now in to improve Android support.

**Comment by kelsosharp** [comment]
@TakahiroMiyaura Do you have a code project or a sample of how you made this work with ARFoundation somewhere?

**Comment by TakahiroMiyaura** [comment]
Hi, @kelsosharp

Yes, I have a sample about this.
My sample project is below.
https://github.com/TakahiroMiyaura/MixedRealityToolkit-Unity/tree/mrtk_running_arfoundation

I sent pull request about this, but now is closed.

Instead of this,@davidkline-ms have been implementing.
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6344

**Comment by julenka** [comment]
Fixed: shaders added, android support added.
