### ISSUE TITLE
Enable research mode

### ISSUE THREAD

**Issue by Weasy666** [microsoft/MixedRealityToolkit-Unity#5879]
I'm currently working on a project in which i need access to the raw sensor stream. To gain access there are some steps that need to be done in Package.appxmanifest and Assembly-CSharp.csproj, but these files are replaced with every 'Build Unity Project'. So...i added two checkboxes to the build window, which let the developer choose if the two file will be modified to allow sensor access and to allow unsafe code in the build Assembly-CSharp project.
![image](https://user-images.githubusercontent.com/11967542/64291786-435a0700-cf69-11e9-9fa5-724461ae81e6.png)

Now my question is if there is interest in something like this. I could start a pull request and add this. I'm not sure if a research mode exists for HoloLens 2, so i would look to make the checkboxes or at least the file modifying checkbox visible dependent on the target device.

**Comment by wiwei** [comment]
@MenelvagorMilsom FYI

@Weasy666  This seems reasonable to me - note that there is already precedent in the build window for adding a capability in after the project is generated (see Appx Build Options -> Gaze Input Capability). There's some code there that already adds capabilities in (and makes sure we don't duply-add them).

If you have already done some stuff here, it would probably be cool to follow that existing pattern, but yeah, even if it's not something everyone is necessarily using, having it be an easy option for folks who need it would be great to have in the toolkit.

**Comment by Weasy666** [comment]
I have seen the Gaze Input Capability, but in my workflow i am not building the Appx from inside the Unity Editor. I need to hide most of the code behind preprocessor directives, because the Windows APIs i need (SoftwareBitmap and so on) are not accessible in the editor project.
So i build the unity project, then open the built solution and do most of the C# work in the build/generated project.  And i think other people need to do it that way too….so the options should be available in the 'Unity Build Options' tab.

I think i can whip up a pull request with my changes tomorrow in the course of the day. There we can discuss the details of the change. Do you know if research mode exists for HoloLens 2?

**Comment by Weasy666** [comment]
@wiwei pull request is up.
There are two things that need to be clarified. I asked them in the PRs comment.

**Comment by wiwei** [comment]
Regarding research mode, I'm following up on that internally.

I'll take a look at the PR, thanks for sending that out!

**Comment by wiwei** [comment]
@Weasy666, got confirmation from folks working on research mode that it's being worked on for HL2.

**Comment by Weasy666** [comment]
Nice to hear and thanks for following up on that!
The reason i was asking (besides my curiosity), was because of the `EditorUserBuildSettings.wsaSubtarget == WSASubtarget.HoloLens` condition for displaying the checkboxes and adding the capability to the manifest. I assume that this condition is true for both HoloLenses and as HoloLens 2 currently seems to not have a research mode, i think this needs to somehow be addressed.  
Do you know of a way to differentiate both devices at that point of time in the build pipeline?

**Comment by wiwei** [comment]
Differentiating between the two is tricky - I think the question here is differentiating at build time, and without another enum from Unity I don't realllly know what we'd do here (I guess we could augment it with our own for now).

What I think I would actually recommend is just treating the two as a pair (i.e. target == hololens applies to both 1 and 2). If we hit some issues with this we can fix it at that point. I guess the thing here is that I assume that the way we do research mode for the two *should* be similar (I don't see what value there is in the SDK folks having different ways of enabling research mode)

**Comment by Weasy666** [comment]
You never know ;) But yeah, i think it will be the same method.

**Comment by Weasy666** [comment]
This was merged, so this issue can be closed.
