### ISSUE TITLE
Increase default number of HoverLights / ProximityLights  to 10 in MRTK Standard shader

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedRealityToolkit-Unity#5888]
## Describe the problem

In multiple projects we've needed to increase the default number of HoverLights and/or ProximityLights from 3/2 to 10. Since these numbers are defined in multiple places this can get tedious.

## Describe the solution you'd like

Make Hoverlight support 10 lights by default instead of 3.
Make ProximityLight support 10 lights by default instead of 2.
If performance is a concern, consider additional multi-compile options.

HoverLight & ProximityLight should also provide static properties for max number of supported lights so devs can manage light activation manually if desired.

**Comment by Cameron-Micka** [comment]
I’ll try profiling with 10 lights and get back to you! I’m assumption is 10 lights would add too many instructions, but you never know until you profile.

**Comment by kircher1** [comment]
+1 on the idea of making this configurable via some sort of static property that feeds into a global variable that shaders can use. Perf should be less of a concern then as you aren't required to unroll 10 iterations in the pixel shader even when 1 or 2 lights may only be active.

**Comment by Cameron-Micka** [comment]
I think there is an efficient way to increase this number without effecting existing users. When I have a free moment I would try and address this. Thank you!

**Comment by Zee2** [comment]
#8596 should have resolved this, as the number of hover lights is now configurable. Please reopen if further issues are experienced or more information is needed!
