### ISSUE TITLE
HoverOffsetYScale in AppBar does nothing

### ISSUE THREAD

**Issue by kwmeyer** [microsoft/MixedRealityToolkit-Unity#5899]
## Describe the bug

The App Bar's `HoverOffsetYScale` property does nothing. The property is not actually used in determining the final position of the app bar.

## To reproduce

In Unity, for any App Bar component, set `HoverOffsetYScale` to a non default value.

## Expected behavior

The final position of the app bar should change, presumably in a vertical direction.

## Your Setup (please complete the following information)

- Unity 2018.4.8f1
- MRTK v2.0.0 RC2, v2.0.0 GA

## Target Platform

- HoloLens 2

## Additional context

This was reported in #2962, but was presumably missed during the HTK-to-MRTK upgrade and never reopened. Please see the last comment on that issue for a patch that I believe fixes this, though I admittedly do not know what the actual expected behavior is supposed to be.

**Comment by wiwei** [comment]
@Railboy, can you take a peek to see if the linked solution looks good to you?

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/2962#issuecomment-522069647
