### ISSUE TITLE
non-existent assembly error upon importing MRTK.Unity.Tools.2.0.0

### ISSUE THREAD

**Issue by nir-Visual3d** [microsoft/MixedRealityToolkit-Unity#5909]
when starting an empty new project (with extras) using unity 2018.2.2.21 and importing the MRTK tools2.0.0 unity package, the following error automatically emerge

Assembly has reference to non-existent assembly 'Microsoft.MixedReality.Toolkit' (Assets/MixedRealityToolkit.Tools/Microsoft.MixedReality.Toolkit.Tools.asmdef)

reproduction:  
1. create a new 2018.2.21 project
2. import from
https://github.com/Microsoft/MixedRealityToolkit-Unity/releases
Microsoft.MixedReality.Toolkit.Unity.Tools.2.0.0.unitypackage
error is produces

## Expected behavior

I'de expect this state to be error free -  have i missed any mandatory import?

## Screenshots

![Capture](https://user-images.githubusercontent.com/45819554/64528229-9dafea80-d310-11e9-90cd-91e483a5348d.PNG)

## Your Setup 

- Unity Version 2018.2.21
- MRTK Version 2.0.0

## Target Platform 
- HoloLens
- HoloLens 2

**Comment by wiwei** [comment]
@nir-Visual3d 

You'll also need to grab the foundation package as well - the tools don't work without the underlying foundational pieces.

Check out the getting started guide for more information on how to get started:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html

Basically, foundation is the only required package, everything else is optional (and shouldn't have any dependencies on each other)

**Comment by nir-Visual3d** [comment]
hi
according to our input i installed foundation on 2 projects
both in unity  2018.2 and 2018.4
the 2018.2 crashed and could not be reopened (autocrash)
the 2018.4 seemed to already have it installed and still the error persisted.
