### ISSUE TITLE
Accessability for EyeTrackingTarget's Update method prevents inheriting component

### ISSUE THREAD

**Issue by radicalad** [microsoft/MixedRealityToolkit-Unity#5911]
## Describe the bug

`EyeTrackingTarget`'s `Update()` method directly polls the `InputSystem` for eye tracking data and broadcasts the appropriate `UnityEvent`s. Problem is, `Update()` is a private member, so when extending `EyeTrackingTarget`, it effectively stops working since you can't call the base `Update()`.

## To reproduce

1. Extend `EyeTrackingTarget`.

## Expected behavior

`EyeTrackingTarget` should continue to work, even when a base class. This seems to be the intent as the methods you'd expect to override have the appropriate accessibility.

## Your Setup (please complete the following information)

- Unity Version 2018.3.11f1
- MRTK Version GA

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
@sostel it doesn't look like this class was designed to be extended given the set of other private members/statics that exist.

@radicalad do you have some more info on how you'd want to extend it (i.e. what's the scenario you're trying to light up?)

**Comment by radicalad** [comment]
The scenario I have is app-logic that sets itself up with the `EyeTrackingTarget`'s events. When upgrading from RC1 to GA, this inheritance broke my component. If this isn't the intention with the component, I can go another route (Require component). I don't see why we can't have the option to inherit here. In general, I'd prefer to keep the `MonoBehaviours` to a minimum. This one change would double by MonoBehaviors from 5 to 10.

**Comment by sostel** [comment]
Yes, so far the class wasn't designed to be extended. But open-minded to do so, if there's a good value for it.
