### ISSUE TITLE
ColliderNearInteractionTouchable was removed breaking clients

### ISSUE THREAD

**Issue by hendryems** [microsoft/MixedRealityToolkit-Unity#5922]
## Describe the bug

When upgrading from MRTK  2.1.0-20190904.1 to 2.1.0-20190909.7, I noticed that `BaseNearInteractionTouchable` was refactored and as a result, `ColliderNearInteractionTouchable` was removed.

The `PokePointer` was updated accordingly but because we cloned/forked the PokePointer to augment it with app specific logic, we didn't automatically get the change and had to track down how to correctly migrate it.

Relevant commit: https://github.com/microsoft/MixedRealityToolkit-Unity/commit/faa20948a25ce2ef1a7c29c202468cfcdfa19c15#diff-c875ac46b3fede23576d1e3ce2c0e140

## Your Setup (please complete the following information)

- Unity Version [N/A]
- MRTK Version [v2.1.0-20190909.7]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by ericob** [comment]
@davidkline-ms any update on this?

**Comment by julenka** [comment]
Marking as release blocker because it blocks at least one person in the upgrade scenario.

**Comment by julenka** [comment]
I would suggest:
1) Mention class migration in release notes
2) Add back the class, mark it as deprecated.

**Comment by julenka** [comment]
fixed
