### ISSUE TITLE
Hand drag direction

### ISSUE THREAD

**Issue by StarWardo** [microsoft/MixedRealityToolkit-Unity#5936]
Use case : user wants to move an object a little to the right. 
The hand dragging will also move the object in other axis resulting in frustration. The user will have to maintain a very stable hand in order to only move it to the desired direction.

Alternative:
A slider could be an option but the user will need to define the direction of the drag by a voice command or button. Or there will need to be a slider for each axis which will cludder the UI. 

Solution:
I would like to get the positive or negative X, Y or Z direction of a global or focused user hand/gestures drag. The functionally is to move an object in a certain fixed direction based on hand dragging. 

Would be nice to also have a direction constraint on movement: X , Y , Z  and combinations XY, XZ , ...on the Manipulation Handler script/

**Comment by davidkline-ms** [comment]
@Zee, is this solved by your translation handles work?

**Comment by Zee2** [comment]
@StarWardo , the new Translation Handles (part of the `BoundsControl` feature) should completely satisfy your needs. There is also a translation constraint that works in local space that will work with `ObjectManipulator`.
