### ISSUE TITLE
Test that MRTK can run with custom pointer mediator

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5937]
## Overview
MRTK should run fine even if people create custom input providers, mediators, input systems, etc. It would be good to write a set of tests that ensure we do not break custom implementations.

The current task tracks writing a test to ensure that a custom pointer mediator will work with mrtk. The test should:

- declare a simple custom mediator
- Instantiate MRTK with a profile that uses this custom mediator
- Run MRTK for a few frames, make sure there are no exceptions thrown.

**Comment by keveleigh** [comment]
I think this was somewhat added in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8258
