### ISSUE TITLE
Preliminary 2.2.0 iteration plan

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#5950]
[Note: This plan is preliminary and subject to change. Please add your feedback to this issue.]

2.2.0 Iteration plan

Release: 2019/11

Themes
- **Stability** - Maintain and improve stability and quality
- **Developer education** - Expand and improve developer resources, including documentation and example scenes
- **Mobile AR** - Add formal support for Mobile AR by embracing Unity's AR Foundation
- **Build Tools** - Bug fixes, NuGet restore, etc
- **UX improvements**

**Comment by julenka** [comment]
To consider possible experimental feature: write a PhysicsManipulationHandler that applies physics forces to the target objects instead of directly updating transforms. This would allow developers to leverage unity's physics. From suggestion: https://holodevelopers.slack.com/archives/C2H4HT858/p1568360346167800

**Comment by davidkline-ms** [comment]
> If I'm not mistaken also, did the TileGenerator go away

Not 100% sure @XPav, I will look into it.

**Comment by davidkline-ms** [comment]
> Under the "Quality" bullet, please improve the experience of building/deploying a complete application

Thanks for the feedback!

**Comment by chrisfromwork** [comment]
We're seeing issues in spectator view where MRTK build tools fail to generate appx's. It seems like these tools should be updated to perform nuget restores: https://github.com/microsoft/MixedReality-SpectatorView/issues/220

Please look into this for the 2.2.0 release when addressing build tools work.

**Comment by gilbdev** [comment]
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6153

**Comment by davidkline-ms** [comment]
The 2.2.0 plan is now published at https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.1.0/Documentation/Contributing/Roadmap.html
