### ISSUE TITLE
Add headset gaze to input handler script

### ISSUE THREAD

**Issue by benpaddlejones** [microsoft/MixedRealityToolkit-Unity#5952]
## Describe the problem

Head-gaze is not as easily programmable as controller-gaze, buttons and joy sticks.

## Describe the solution you'd like

Have head-gaze added to the list of input options in the input handler script. So when input actions can be assigned to head-gaze in the same way as controller inputs.

## Describe alternatives you've considered

Manually programming the functionality as documented here: https://docs.microsoft.com/en-us/windows/mixed-reality/gaze-in-unity

**Comment by davidkline-ms** [comment]
If this is still something that is needed, please reopen and provide an example of how a gaze generated input action would work.
