### ISSUE TITLE
SDK/Experimental folder structure is confusing

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5953]
## Overview
When you import the MRTK 2.0 Foundation package, several non-experimental systems are actually under the experimental folder, they should not be under the Experimental folder.

All of the systems in the below image should not be under the experimental folder
![image](https://user-images.githubusercontent.com/168492/64914577-e4835300-d709-11e9-9612-7c989d807f98.png)

## Steps to reproduce
Download and import the foundation package from the [mrtk release page](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases)

Import the package. I was using Unity 2019.2.5f1.

## Expected Behavior
There are no folders under MRTK.SDK/Experimental

## Actual Behavior
There are several folders under MRTK.SDK/Experimental

## Unity Editor Version
Unity 2019.2.5f1.

**Comment by julenka** [comment]
Since nobody has noticed / complained about this, I don't think there's a need to do a hotfix release, but for our next release let's make sure that there are no unintentional folders under Experimental. FYI @wiwei (when you get back).

**Comment by cre8ivepark** [comment]
Confirmed with Periodic Table app which was updated to v2.0.0
https://github.com/microsoft/MRDL_Unity_PeriodicTable/tree/master/Assets/MixedRealityToolkit.SDK/Experimental/Features

**Comment by julenka** [comment]
Ah, turns out this is by design. This is part of David's experimental "standalone services".

**Comment by julenka** [comment]
Re-opening to keep the feedback for @davidkline-ms. The current structure is by design because there is an experimental 'standalone services' system he is working on. However, the current structure makes it look slike there is an experimental Features, Camera, Diagnostics, Dwell, Input, etc... system. When in fact there is just one experimental thing: standalone services. Suggest modifying the structure to from Experimental/Features to Experimental/StandaloneServices/Features

**Comment by davidkline-ms** [comment]
I'm open to that, Thanks!

**Comment by SimonDarksideJ** [comment]
I personally would have moved them to a separate branch, maybe providing them as a separate asset.  Shouldn't be in a release branch imho.
