### ISSUE TITLE
Far Manipulation Rotate About Object Center does not rotate about X, Y axes

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5957]
## Overview
Somehwere in 2.0 release we lost the ability to rotate objects about their center  when manipulating at a distance. It was very handy to have this so you could place objects far away, but then rotate them just by rotating your hand. I can rotate about the z axis, but not so much about the X and Y axes.

I believe this is because we are using the pointer rotation instead of the pointer controller's grip pose rotation. Here is the code to get grip pose:

        private bool TryGetGripRotation(IMixedRealityPointer pointer, out Quaternion rotation)
        {

            for (int i = 0; i < pointer.Controller.Interactions.Length; i++)
            {
                if(pointer.Controller.Interactions[i].InputType == DeviceInputType.SpatialGrip)
                {
                    rotation = pointer.Controller.Interactions[i].RotationData;
                    return true;
                }
            }
            rotation = Quaternion.identity;
            return false;
        }

## Expected Behavior
I expect when I rotate my palm for the object to rotate about the object center. This is handy for rotating things at a distance.

![rotateObjectCenter](https://user-images.githubusercontent.com/168492/64983023-6b543f00-d874-11e9-9fea-645171d466b0.gif)

## Actual Behavior
The object only rotates about the Z axis, not the x/y axis

![rotateObjectCenter_actual](https://user-images.githubusercontent.com/168492/64983145-b1110780-d874-11e9-9669-107a73e63f37.gif)

## Steps to reproduce
In ManipulationHandler, set the One Hand Rotation Mode Far to "RotateAbout Object Center", and then manipulation object with the articulated hands.

## Unity Editor Version
2018.4.6f1

## Mixed Reality Toolkit Release Version
2.0

## Notes
I used the following code to work around this -- just needed to apply the Grip Pose rotation:

https://gist.github.com/julenka/842720daf201d1d511d47d87628d5964

**Comment by julenka** [comment]
@MenelvagorMilsom and @thalbern  please don't forget about this one as you are doing your refactoring...this is something that was working in RC2.1 but then broke in our GA release

**Comment by MenelvagorMilsom** [comment]
@julenka this is fixed in #5955, specifically [this commit](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5955/commits/70a6f652056b6b3ee62e5a52d79073941193ce88). Do we want to port the fix for this release too?

**Comment by julenka** [comment]
I would love that (strive to improve the product), but not if it risks adding regressions (maintain trust). Up to you. It's not a regression from 2.0 so we could wait until 2.2

**Comment by keveleigh** [comment]
Fixed via #6423
