### ISSUE TITLE
"Failed to world lock serialization failed"

### ISSUE THREAD

**Issue by MrMatthias** [Microsoft/MixedRealityToolkit-Unity#596]
"Failed to world lock serialization failed"
I sometimes get this error after creating a WorldAnchor in a UNet Sharing project (Host). What does it mean?

**Comment by lukaswerz** [comment]
Same Problem here

**Comment by fraspadafora** [comment]
I have the same problem...  When I run a hololens with the sharing service, it fails to upload the anchors.

**Comment by sebrk** [comment]
I got this too. Clearing the space fixed it. This should probably be a more detailed error message in any case but is there a way to check this in runtime?

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.

Please open a new issue if it still exists.
