### ISSUE TITLE
Duplicated service displayed under MixedRealityToolkit hierarchy (Service Inspector)

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#5968]
## Describe the bug
A scene with 'Use Service Inspectors' checked sometimes show duplicated MRTK service.
<img width="400" alt="2019-09-17 12_05_19-Unity 2018 4 7f1 Personal - MRTKExamplesHub unity - MRTK-Public-Microsoft - Univ" src="https://user-images.githubusercontent.com/13754172/65071459-b12c0880-d943-11e9-84da-3dc381dae8eb.png">

## To reproduce
In MRTK Profile > Editor > check 'Use Service Inspectors'
Save the scene and close Unity editor.
Open Unity editor, load the scene.

## Branch
mrtk_development

**Comment by keveleigh** [comment]
Should be fixed via #5977
