### ISSUE TITLE
Enable MRTK standard shader to support RectMask2D

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#5969]
## Describe the bug

When using 16-bit depth buffer format for performance with depth LSR/HL2 device, stencil buffer is not created. Developers using mask operations, if in 2d space and coplanar, can use the [RectMask2D](https://docs.unity3d.com/Manual/script-RectMask2D.html) unity component to still utilize 16-bit buffer format while getting stencil operations.

Note: to others reading this, using 24-bit depth buffer format in Unity will create an 8-bit stencil buffer and fix any features utilizing a stencil buffer.

See [RenderTexture.depth](https://docs.unity3d.com/ScriptReference/RenderTexture-depth.html) for details on the depth buffer format and stencil buffer

Related: #5784 

## To reproduce

See related bug for reproduce info

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Cameron-Micka** [comment]
This is something I should probably still add!

**Comment by polar-kev** [comment]
@Cameron-Micka, putting this on your radar again.

**Comment by Cameron-Micka** [comment]
I will try and support this in the coming weeks. :)
