### ISSUE TITLE
Why EyeTracker doesn't work in hololens emulator even though I tick the 'GazeInput' checkbox under Capabilities in 'Package.appxmanifest' 

### ISSUE THREAD

**Issue by blablamoxian** [microsoft/MixedRealityToolkit-Unity#5980]
## Describe the Issue
The problem of using eye Tracker in HoloLens emulator.

## Feature Area
I did the work step by step by following this link "https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/EyeTracking/EyeTracking_BasicSetup.html". But the HoloLens emulator didn't have the "Eye Tracker"checkbox. So what's the problem?

**Comment by Alexees** [comment]
Did you read and follow this part?

> You don't see a 'GazeInput' capability?
> 
> Check that your system meets the [prerequisites for using MRTK](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html#prerequisites) (in particular the Windows SDK version).
> You can also manually add the entry by opening the appxmanifest in an XML editor and adding the following:

```
  <Capabilities>
    <DeviceCapability Name="gazeInput" />
  </Capabilities>
```

**Comment by blablamoxian** [comment]
Thanks for your reply.

I did this but it didn't work. When I run the MRTK "eyeTracking"example, I could see this in HoloLens Emulator.
[cid:930e98e2-3c2a-4f5d-a249-bcdfbeca59c3]

But when I run my own app, I couldn't see it. I truly did it as you say (setting the "Gazeinput"), But it didn't work.
So is there any other reason?

Thanks.
________________________________
发件人: Alexander Seeck <notifications@github.com>
发送时间: 2019年9月18日 4:46
收件人: microsoft/MixedRealityToolkit-Unity <MixedRealityToolkit-Unity@noreply.github.com>
抄送: cheeseEvil <wulele1996@outlook.com>; Author <author@noreply.github.com>
主题: Re: [microsoft/MixedRealityToolkit-Unity] Why EyeTracker doesn't work in hololens emulator even though I tick the 'GazeInput' checkbox under Capabilities in 'Package.appxmanifest' (#5980)


Did you read and follow this part?

You don't see a 'GazeInput' capability?

Check that your system meets the prerequisites for using MRTK<https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html#prerequisites> (in particular the Windows SDK version).
You can also manually add the entry by opening the appxmanifest in an XML editor and adding the following:

  <Capabilities>
    <DeviceCapability Name="gazeInput" />
  </Capabilities>


―
