### ISSUE TITLE
Disabling a button as part of its OnClick constantly moves the collider backwards

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5984]
## Describe the bug

In case a button (in my case PressableButtonHoloLens2) is pressed and causes its own deactivation, the button breaks. The next time the button is activated, it's press collider starts at where it left off, constantly moving it backwards for every click.
This is not very convenient in cases, where the button is part of larger menu structures where layers of buttons get toggled all the time.

## To reproduce

1. Check out [this Repository](https://github.com/HoloSpaces/MixedRealityToolkit-Unity/tree/mrtk_buttonColliderMovement), or temporarily merge it into the current dev branch
2. Open Assets/Test scene
3. Press Play
4. Mouse interaction should be enabled, press the button multiple times and observe the collider (button comes back after a sec)

## Expected behavior

A button always starts in it's default state.

## Screenshots

![image](https://user-images.githubusercontent.com/32508825/65151363-41db1500-da26-11e9-860f-1a26cf5a404c.png)

## Your Setup (please complete the following information)

- Unity Version 2018.4.6f1
- MRTK Version mrtk_development

## Target Platform (please complete the following information)

- Editor for now

**Comment by Troy-Ferrell** [comment]
Fixed by @CDiaz-MS
