### ISSUE TITLE
Unified SeeItSayItLabel

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5985]
## Describe the problem

At the moment, if your SeeItSayItLabel requires a larger Text label, you need to change the size of TextMeshPro and LabelPlate manually.
This could be simplified with a ContentSizeFitter, if the BackPlate was a Unity UI component using a RectTransform.

![image](https://user-images.githubusercontent.com/32508825/65152357-1527fd00-da28-11e9-98c1-2fe09227bc6d.png)

## Describe the solution you'd like

If not already possible, the HolographicBackPlate material with its StandardShader should be able to be used in UI Images, or RawImages, or whatever type so it can be used along with the Unity UI.
This way, the plate could be put behind the label, all if it could receive a ContentSizeFitter component and voila, Text scales the content.

## Describe alternatives you've considered

Manually adjusting both, making sure, offsets look right

**Comment by davidkline-ms** [comment]
We believe this has been addressed (and mistakenly not resolved). If it is still an issue, please reopen.
