### ISSUE TITLE
DefaultPointerMediator needs a parameterless constructor to avoid a breaking change

### ISSUE THREAD

**Issue by AdamMitchell-ms** [microsoft/MixedRealityToolkit-Unity#5989]
In a [recent change](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5920/files#diff-9be9f00a0ff5b2382c2ec6e9d83ddf32) to DefaultPointerMediator, a new constructor was added which requires a parameter.

This removes the implicit parameterless constructor.  This is a breaking change.  Now classes derived from DefaultPointerMediator must somehow construct the param and pass it in.

We should add in an explicit parameterless constructor.  It should effectively set this.pointerPrefs to null and a null check will then be needed in places where it's referenced.

**Comment by julenka** [comment]
Huge thank you to adam mitchell for helping!
