### ISSUE TITLE
Clipping Primitives are writing shader keywords directly to materials

### ISSUE THREAD

**Issue by radicalad** [microsoft/MixedRealityToolkit-Unity#5993]
## Describe the bug
I've run into an issue where once I've added items with shared materials to a `ClippingPrimitive` (in my case a holographic button), any additional materials have the shader keyword `_CLIPPING_BOX` enabled, but its not configurable in the inspector.

I know `ClippingPrimitive` makes use of material property blocks, and those are applied to the objects added to the renderer list. I'm not sure where the base material is being changed though...

## To reproduce

1. New scene
2. Add button prefab
3. New Gameobject add `ClippingBox` component
4. Add backplate quad from button prefab to `Renderers` list on `ClippingBox`
    Works as expected
5. Add new button prefab to the scene
     Backplate is no longer visible
     Inspector doesn't show modification to base material
6. File -> Save project
7. open HolographicBackPlate.mat in code viewer, `_CLIPPING_BOX` is added

## Expected behavior

Material property blocks should prevent changing the base materials.

## Screenshots
![image](https://user-images.githubusercontent.com/1186832/65174645-2c55f300-da06-11e9-8072-85f87bb41df2.png)
![image](https://user-images.githubusercontent.com/1186832/65174603-12b4ab80-da06-11e9-9370-d9c27f226859.png)

(after step 4, you can see the back plate on see it say it is already disabled)

new button (that is not clipped)

![image](https://user-images.githubusercontent.com/1186832/65174734-53142980-da06-11e9-9a1c-a2611e97e9a3.png)
![image](https://user-images.githubusercontent.com/1186832/65174751-59a2a100-da06-11e9-80e4-5005c8d56061.png)
inspector doesn't show material property block message, and clipping box is turned off.

![image](https://user-images.githubusercontent.com/1186832/65174898-aab29500-da06-11e9-88d3-b45113e6bece.png)
after saving project, `HolographicBackPlate.mat was modified` but doesn't show in unity inspector.

## Your Setup (please complete the following information)

- Unity Version 2018.4.7f1
- MRTK Version - mrtk_development - last merge was 7f8571bd27eff2ee6021eafb876bddb1884c6d4e (~9/16/2019)

## Target Platform (please complete the following information)

- Editor, haven't needed to check on device yet.

**Comment by julenka** [comment]
@Cameron-Micka this is blocking #6001, and seems like it would also block anybody that uses buttons with a ClippingPrimitive. Could you please take a look?

**Comment by Cameron-Micka** [comment]
I'll try and steal some time this afternoon to take a look. My guess is that Unity is saving the shared materials during editmode, not sure why this has changed? But, I'll take a peek.
