### ISSUE TITLE
LWRP Warning in MRTK/Standard Shader Inspector

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#5994]
## Describe the problem

When switching to the LWRP it is not immediately clear how to upgrade the MRTK/Standard shader.

## Describe the solution you'd like

The material inspector should have a "Fix Now" button in the inspector.

## Describe alternatives you've considered

Or, if we can detect the render pipeline change a dialog should pop up.

## Additional context

Needed for ARR users.

**Comment by davidkline-ms** [comment]
@Cameron-Micka, is this still needed? Do we need a dialog to point to the update shader menu item?

**Comment by Cameron-Micka** [comment]
I think this feature would be still helpful and an easy addition. We could follow the same "fix now" button paradigm we do for depth. See this PR for that: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4734

**Comment by Cameron-Micka** [comment]
Done in Graphics Tools: https://github.com/microsoft/MixedReality-GraphicsTools-Unity because no upgrade is needed anymore.
