### ISSUE TITLE
Editing pre- typed text with system keyboard. 

### ISSUE THREAD

**Issue by TChag** [microsoft/MixedRealityToolkit-Unity#5999]
## Describe the problem

Opening System keyboard with pre-typed text (preexisting string to edit) through MixedRealityKeyboard.cs not possible.

## Describe the solution you'd like

ShowKeyboard method in MixedRealityKeyboard.cs should expose this option.

## Describe alternatives you've considered

Alternatives: 
1. Developer must handle merging keyboard text with pretypted text, as well as keyboard backspace input to delete characters from pretytped text. 
2. User must edit strings from scratch, all previous input lost when editing string. (not ideal for editing dns / email login).

**Comment by Alexees** [comment]
It's experimental, isn't it? You can just change it to your liking

**Comment by Merichbier** [comment]
I think this issue is solved
