### ISSUE TITLE
Hold Gesture will impact on Xbox Controller Trigger input

### ISSUE THREAD

**Issue by meiyg0927** [microsoft/MixedRealityToolkit-Unity#6000]
## Description

The developer found that the action of Xbox One controller "Trigger L/R" would be also executed when he make Hold gesture in device.

**This feedback is from strategic customer of Japan**

## To reproduce

1.	Create new project and setup MRTKv2 (Import Foundation & Examples) in Unity
2.	Unzip the attachment and Import "Custom.Controller.unitypackage" in Unity
3.	Open the scene “ControllerExampleScene” which is in the “Custom.Controller” directory
4.	Check the profile, ensure that two default profiles have been replaced
- DefaultMixedRealityInputActionsProfile -> New MixedRealityInputActionsProfile
- DefaultMixedRealityControllerMappingProfile -> New MixedRealityControllerMappingProfile
5.	Check the game object “Cube” in the scene, ensure that "ObjectController.cs" script has been attached
6.	Deploy to device (HoloLens 1 or HoloLens 2)
7.  Connect Xbox Controller with HoloLens via bluetooth and launch the app. Press the “RT” or “LT” to rotate the Cube. **If user make Hold Gesture, the Cube can also be rotated.**

## Setup Environment
- Unity 2019.2.2f1
- MRTK v2.0
- [Custom.Controller.unitypackage.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3628978/Custom.Controller.unitypackage.zip)

## Target Platform 
- HoloLens
- HoloLens 2

## Additional context
I don't know whether “IMixedRealityInputHander” would replace the Controller’s Triger data with Hold Gesture’s data.

**Comment by davidkline-ms** [comment]
Thanks for the issue report. Asking @keveleigh to investigate.

**Comment by davidkline-ms** [comment]
This work is being scheduled for MRTK 2.2.0

**Comment by meiyg0927** [comment]
Thank you for help!
