### ISSUE TITLE
UWP Native Keyboard flicker jumps around

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6005]
## Describe the bug

@julenka provided a fix that made the NativeKeyboard work for HL1 and UWP, thanks for that. It's still broken thought.

I attached a video that shows that the keyboard, besides performing a slight stretch-glitch when opened, jumps around like crazy when looking down at a certain angle.

I would have reported this in Microsofts Feedback HUB, but I never received any answer on any of my reports there... @SarahSexton was so kind to try fixing the discrepancy between the HUBs user and Microsoft staff view as well as getting anyone to react to the tasks, but to no avail.

[Mixed Reality Portal 2019-09-19 15-32-45_Trim.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3631469/Mixed.Reality.Portal.2019-09-19.15-32-45_Trim.zip)

## To reproduce

- Simply open the Keyboard wearing a UWP headset and slowly look down. At some point it flickers around like no tomorrow

## Expected behavior

Keep still... just work dammit

## Your Setup (please complete the following information)

- Unity Version 2018.4.6f1
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- WMR immersive

**Comment by kevbarn** [comment]
Hi @Alexees, can you tell us what version of Windows you are running? Running 'winver' should give you a box with a string like "Version 1903 (OS Build 18362.356)". This is important information since the code that is making the keyboard jump around like that is part of the OS and has changed from version to version.

**Comment by Alexees** [comment]
> Hi @Alexees, can you tell us what version of Windows you are running?

Sure

![image](https://user-images.githubusercontent.com/32508825/65267228-e3d92b00-db14-11e9-9a2d-750df797b932.png)

**Comment by Alexees** [comment]
@kevbarn it matches the version you've provided

**Comment by kevbarn** [comment]
Thanks for confirming @Alexees. This is a bug with Windows and not specific to Unity or MRTK. We are tracking this internally in our Windows bug database as bug 21829931.

**Comment by Alexees** [comment]
@kevbarn May I ask you something? I have reported a couple of bugs about the Mixed Reality Portal and I have neither received any feedback on them nor are they solved, and I can't see their status. If possible, I'd really love to go over the bugs I've found because at the moment, developing for the MR portal is not pretty and it doesn't feel like it's going to change anymore.

**Comment by davidkline-ms** [comment]
@Alexees, can you confirm if this issue shows in the immersive device as well as in the Mixed Reality Portal on your PC?

Thanks!

**Comment by davidkline-ms** [comment]
@Alexees, I am also looking into the best source of information on your reported issues.
 I will reach out to you once i have an update for you.

**Comment by Alexees** [comment]
> @Alexees, can you confirm if this issue shows in the immersive device as well as in the Mixed Reality Portal on your PC?
> 
> Thanks!

Not entirely sure what you mean, but I saw it first wearing the HMD and then recorded it in the portal. That was at work, I can't test in on my private notebook, I don't have a headset there.

**Comment by davidkline-ms** [comment]
> Not entirely sure what you mean, but I saw it first wearing the HMD and then recorded it from the desktop view of the portal. 

That confirmed what i was asking. It is present in both displays (the HMD and the portal). Thanks!
