### ISSUE TITLE
Enumerating and Accessing Spatial Mesh

### ISSUE THREAD

**Issue by astaikos316** [microsoft/MixedRealityToolkit-Unity#6013]
I have been having trouble trying to understand how to use the Spatial Awareness user guide to get access to the spatial meshes to use in a multi-user app. I cannot find a way to serialize the meshes to be able to send them to a remote device as was previously possible in the older toolkit. I have tried to add the meshes to a list and used the old simplemeshserializer but that did not seem to work at all. Any help would be greatly appreciated in trying to understand the current capabilities in current MRTK and how the same functionality can be replicated.

**Comment by Alexees** [comment]
Questions are better suited for StackOverflow, using the mrtk tag.

**Comment by Troy-Ferrell** [comment]
@davidkline-ms FYI, in case this should be a documentation bug

**Comment by Troy-Ferrell** [comment]
@astaikos316 see related PR, search for ObjExporter or FBXExporter libraries online and then you should be able to use the documentation usage guide to tie them together
