### ISSUE TITLE
Unify the MixedRealityToolkit profile management

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6014]
## Describe the problem

The MixedRealityToolkit uses a mix of single and multi-platform-capable profiles to be configured. For some settings you need to create a completely new MRTK profile, for others, you can keep one because it's possible to configure for each platform.
With projects scaling across several platforms and devices this becomes difficult, because you might have to branch at the MRKT profile level all of a sudden and then start splitting settings up and move them around.

Example:

- Camera: Single platform
- Input: One Profile for a gigantic amount of settings
  - InputDataProviders: multi-platform
  - InputActions: single platform
  - Gestures/Speech/Handtracking: Not even possible on a lot of devices, why view them?
- Teleport: VR only so far
...

## Describe the solution you'd like

A true multi-platform solution, based on device capabilities, split across scenes.
- The problem with the current profile based approach mainly suffers from all configuations being packed for every built.
The only mechanism I know of would be providing a per patform scene with its configuration that is additively loaded.
- Services not even capable of being used on platforms should not show in the inspector. They should not even be compiled or deserialized.
- There should only ever be as many devices listed as the setup is capable of supporting, while HMD, controllers and visualizers should be merged into one configuration set, right now those are split up into 3 different configuration groups.

Funnily enough, I found the same though here:
https://github.com/XRTK/XRTK-Core/issues/290

Since everything is based on platform checks, which in case of Android can support a variety of devices (mobile, Oculus Go, Quest....), the scene split approach would also solve that problem.

## Describe alternatives you've considered

- Starting with creating multi-platform capable profiles for settings like the Camera so I can continue using just one MRKT profile.
- Start using multiple MRKT profiles and seeing which subprofiles I can reuse, which ones I don't etc.

**Comment by davidkline-ms** [comment]
Thanks for the suggestion, @Alexees!

**Comment by davidkline-ms** [comment]
MRTK3 has retired the v2.x profile strategy, there are no current plans to make wide scale changes to the v2.x profiles.
