### ISSUE TITLE
documentation vague on using spatial awareness to access surfacetypes(wall, floor, ceiling etc)

### ISSUE THREAD

**Issue by neur19** [microsoft/MixedRealityToolkit-Unity#6018]
Documentation about the subsystem which separates the walls and floors are vague. Older versions of the toolkit had at least example to understand more about surface types. Please elaborate about querying and enumeration with respect to walls/floors fro spatial data.

I am working on a simple project and I want to put a material only on the walls. Spacial awareness systems helps giving wireframe or occulution to entire mapped mesh (layer 31). is there a way to have walls alone in a different layer? for organisation. Thank you.

##  Setup 
- Unity Version [2019.1.7f1]
- MRTK Version [v2.0]

## Target Platform 
- HoloLens
- HoloLens 2

**Comment by Troy-Ferrell** [comment]
Spatial Awareness is just mapping. Spatial or scene understanding is a different feature. @davidkline-ms FYI

**Comment by neur19** [comment]
@Troy-Ferrell I was confused about using the api given with toolkit.
For reference : https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.SpatialAwareness.SpatialAwarenessSurfaceTypes.html

**Comment by Troy-Ferrell** [comment]
Thanks for the additional info! Looking for find all references of that SpatialAwarenessSurfaceTypes enum, I don't see it used in MRTK at all atm. 

This might have been add prematurely or to prepare for the future work.

@davidkline-ms, do you have any info on the enum?

**Comment by pinkwerks** [comment]
This enum is present in 2.2 but I don't believe it to be of practical use.
[https://github.com/microsoft/MixedRealityToolkit-Unity/blob/f38399007d30bcee7d3e7ceb27c058074650a311/Assets/MixedRealityToolkit/Definitions/SpatialAwareness/SpatialAwarenessSurfaceTypes.cs](url)

Now, the good news. Effort is underway to get this added:
https://github.com/pinkwerks/MixedRealityToolkit-Unity/commit/d6804f808f1fcbadb10e94b903799065648636b3

**Comment by pinkwerks** [comment]
We now have a feature request to better support spatial awareness surface types. #6928 

Will be continuing discussion and putting forth associated pull request there.
