### ISSUE TITLE
Request to provide ablilty to quick rotate hand up in Editor to work on hand menus

### ISSUE THREAD

**Issue by erhavir** [microsoft/MixedRealityToolkit-Unity#6028]
## Describe the problem

When working on hand menus in the editor, it's time consuming to validate one's work. You need to show the hand and then rotate it around until it is facing up and triggering the hand menu. 

## Describe the solution you'd like

It would be convenient to have a shortcut to turning the hand palm-up while playing the project in the editor. It could be a key or gesture.

## Describe alternatives you've considered

There are a number of ways to implement this. Trying to remember which way to rotate the hand and then rotating it until the menu shows is too time consuming, so any number of methods could be an improvement.

**Comment by davidkline-ms** [comment]
You can perform this gesture by : rotating the hand is available in the input / hand simulation (hold control, move mouse). Set flat hand in the simulation profile.

If this does not solve the issue, please reactivate.

**Comment by davidkline-ms** [comment]
@CDiaz-MS, please add helper images, thjanks!

**Comment by CDiaz-MS** [comment]
To make the hand flat in the input simulation, change the `Middle Mouse Hand Gesture` in the input simulation profile to `Flat` located under Input > Input Data Providers > Input Simulation Service

![image](https://user-images.githubusercontent.com/53493796/124009305-48841380-d992-11eb-82a7-09071fee1ad6.png)

To rotate the hand in-editor, press the middle mouse button, then hold ctrl + move the mouse:

![HandRotate](https://user-images.githubusercontent.com/53493796/124009886-fbed0800-d992-11eb-96b0-b047415a7eb4.gif)
