### ISSUE TITLE
InputSimulationIndicators causes deserialization error

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6033]
## Describe the bug

When running a build on UWP with development enabled, a serialization error pops up

## To reproduce

1. Build MRTK scene with development mode

## Expected behavior

No serialization problem

## Screenshots

![image](https://user-images.githubusercontent.com/32508825/65421211-7b839580-de03-11e9-95ef-e36435f739f2.png)

## Your Setup (please complete the following information)

- Unity Version 2018.4.6f1
- MRTK Version mrtk_development

## Target Platform (please complete the following information)

- WMR immersive

**Comment by keveleigh** [comment]
Fixed via #6034
