### ISSUE TITLE
Finger Cursor is Offset from the Interaction Location

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#6045]
## Describe the bug

The finger cursor within the MRTK is offset from the interaction location (and Shell location) when a finger is roughly perpendicular to a interactable surface normal.

This was found by one of our partners when trying to interact with narrow UI.

## To reproduce

1. Open the PressableButtonExample scene.
2. Make sure the hand is roughly perpendicular to the surface normal of a button.
3. Move the hand towards a button to press it.
3. Notice the cursor is located above the finger tip rather than near the finger pad.
4. Reproduces in Editor and on HoloLens 2.

## Expected behavior

The finger cursor and proximity light match the interaction location.

## Screenshots

![image](https://user-images.githubusercontent.com/13305729/65456309-e0d48800-ddfd-11e9-92a1-df068e7dde62.png)

## Your Setup (please complete the following information)

- mrtk_development

## Target Platform (please complete the following information)

- Editor
- HoloLens 2

**Comment by MenelvagorMilsom** [comment]
Fixed in #6479
