### ISSUE TITLE
InputManager does not support ability to use Unity ScrollBars and ScrollRects 

### ISSUE THREAD

**Issue by vbielkin** [Microsoft/MixedRealityToolkit-Unity#605]
HoloToolkit InputManager does not use ExecuteEvents.beginDragHandler and ExecuteEvents.dragHandler when handling input sources events. As the result Unity ScrollBars and ScrollRects does not receive any events or calls from InputManger

**Comment by StephenHodgson** [comment]
You should be able to tap and drag the list, I've got a few projects that utilized this, but never implemented the scro

**Comment by niklasj93** [comment]
Since I wasn't able to get scrolling functionality on ScrollRects without the HoloLens Input Module, but activating it caused the double firing of OnClick-events like mentioned in other issues, I came up with a workaround yesterday. Modified the InputManager and tried to use the Navigation Gesture events and GripPosition to provide a kinda "fake" pointer movement to the dragHandler. Works fine for me but hasn't been tested in combination with e.g. Handdraggable. Anyhow scrolling is still a bit dysfluent.

Would be interesting to get some feedback on this approach:

`
        private bool drag = false;
        private Vector2 dragInitialPosition;
`

#region Navigation Events

        private static readonly ExecuteEvents.EventFunction<INavigationHandler> OnNavigationStartedEventHandler =
            delegate (INavigationHandler handler, BaseEventData eventData)
            {
                NavigationEventData casted = ExecuteEvents.ValidateEventData<NavigationEventData>(eventData);
                handler.OnNavigationStarted(casted);
            };

        public void RaiseNavigationStarted(IInputSource source, uint sourceId, object[] tags = null)
        {
            // Create input event
            navigationEventData.Initialize(source, sourceId, tags, Vector3.zero);

            // Pass handler through HandleEvent to perform modal/fallback logic
            HandleEvent(navigationEventData, OnNavigationStartedEventHandler);

            // UI events
            IPointingSource pointingSource;
            FocusManager.Instance.TryGetPointingSource(inputEventData, out pointingSource);
            PointerInputEventData pointerInputEventData = FocusManager.Instance.GetSpecificPointerEventData(pointingSource);
            PointerInputEventData pointerInputEventData2 = FocusManager.Instance.GetSpecificPointerEventData(pointingSource);

            if (pointerInputEventData != null)
            {
                pointerInputEventData.InputSource = source;
                pointerInputEventData.SourceId = sourceId;
                pointerInputEventData.pointerId = (int)sourceId;

                pointerInputEventData.eligibleForClick = true;
                pointerInputEventData.delta = Vector2.zero;
                pointerInputEventData.dragging = false;
                pointerInputEventData.useDragThreshold = true;
                pointerInputEventData.pressPosition = pointerInputEventData.position;
                pointerInputEventData.pointerPressRaycast = pointerInputEventData.pointerCurrentRaycast;

                if (pointerInputEventData.selectedObject != null)
                {
                    //ExecuteEvents.ExecuteHierarchy(pointerInputEventData.selectedObject, pointerInputEventData, ExecuteEvents.initializePotentialDrag);
                    if (drag == false)
                    {
                        Debug.Log("Start Dragging");
                        ExecuteEvents.ExecuteHierarchy(pointerInputEventData.selectedObject, pointerInputEventData, ExecuteEvents.beginDragHandler);
                        drag = true;
                        Vector3 position;
                        source.TryGetGripPosition(sourceId, out position);
                        dragInitialPosition = new Vector2(position.x, position.y);
                    }

                    //ExecuteEvents.ExecuteHierarchy(pointerInputEventData.selectedObject, pointerInputEventData, ExecuteEvents.scrollHandler);
                }
            }
        }

        private static readonly ExecuteEvents.EventFunction<INavigationHandler> OnNavigationUpdatedEventHandler =
            delegate (INavigationHandler handler, BaseEventData eventData)
            {
                NavigationEventData casted = ExecuteEvents.ValidateEventData<NavigationEventData>(eventData);
                handler.OnNavigationUpdated(casted);
            };

        public void RaiseNavigationUpdated(IInputSource source, uint sourceId, Vector3 normalizedOffset, object[] tags = null)
        {
            // Create input event
            navigationEventData.Initialize(source, sourceId, tags, normalizedOffset);

            // Pass handler through HandleEvent to perform modal/fallback logic
            HandleEvent(navigationEventData, OnNavigationUpdatedEventHandler);

            // UI events
            IPointingSource pointingSource;
            FocusManager.Instance.TryGetPointingSource(inputEventData, out pointingSource);
            PointerInputEventData pointerInputEventData = FocusManager.Instance.GetSpecificPointerEventData(pointingSource);

            if (pointerInputEventData != null)
            {
                pointerInputEventData.InputSource = source;
                pointerInputEventData.SourceId = sourceId;
                pointerInputEventData.pointerId = (int)sourceId;

                pointerInputEventData.eligibleForClick = true;
                pointerInputEventData.delta = Vector2.zero;
                pointerInputEventData.dragging = false;
                pointerInputEventData.useDragThreshold = true;
                pointerInputEventData.pressPosition = pointerInputEventData.position;
                pointerInputEventData.pointerPressRaycast = pointerInputEventData.pointerCurrentRaycast;


                if (pointerInputEventData.selectedObject != null)
                {
                    ExecuteEvents.ExecuteHierarchy(pointerInputEventData.selectedObject, pointerInputEventData, ExecuteEvents.pointerDownHandler);
                    //ExecuteEvents.ExecuteHierarchy(pointerInputEventData.selectedObject, pointerInputEventData, ExecuteEvents.initializePotentialDrag);
                    if (drag != false)
                    {
                        
                        Vector3 position;
                        source.TryGetGripPosition(sourceId, out position);
                        Vector2 deltaPos = new Vector2(position.x, position.y) - dragInitialPosition;
                        pointerInputEventData.position += deltaPos * 1000.0f;
                        Debug.Log("Dragging..." + deltaPos);
                        ExecuteEvents.ExecuteHierarchy(pointerInputEventData.selectedObject, pointerInputEventData, ExecuteEvents.dragHandler);
                    }
                    //ExecuteEvents.ExecuteHierarchy(pointerInputEventData.selectedObject, pointerInputEventData, ExecuteEvents.scrollHandler);
                }
            }

        }

        private static readonly ExecuteEvents.EventFunction<INavigationHandler> OnNavigationCompletedEventHandler =
            delegate (INavigationHandler handler, BaseEventData eventData)
            {
                NavigationEventData casted = ExecuteEvents.ValidateEventData<NavigationEventData>(eventData);
                handler.OnNavigationCompleted(casted);
            };

        public void RaiseNavigationCompleted(IInputSource source, uint sourceId, Vector3 normalizedOffset, object[] tags = null)
        {
            // Create input event
            navigationEventData.Initialize(source, sourceId, tags, normalizedOffset);

            // Pass handler through HandleEvent to perform modal/fallback logic
            HandleEvent(navigationEventData, OnNavigationCompletedEventHandler);

            // UI events
            IPointingSource pointingSource;
            FocusManager.Instance.TryGetPointingSource(inputEventData, out pointingSource);
            PointerInputEventData pointerInputEventData = FocusManager.Instance.GetSpecificPointerEventData(pointingSource);
            if (pointerInputEventData != null)
            {
                pointerInputEventData.InputSource = source;
                pointerInputEventData.SourceId = sourceId;

                if (pointerInputEventData.selectedObject != null)
                {
                    Debug.Log("Stop Dragging");
                    ExecuteEvents.ExecuteHierarchy(pointerInputEventData.selectedObject, pointerInputEventData, ExecuteEvents.endDragHandler);
                    drag = false;
                    dragInitialPosition = Vector2.zero;
                }

                pointerInputEventData.Clear();
            }
        }

        private static readonly ExecuteEvents.EventFunction<INavigationHandler> OnNavigationCanceledEventHandler =
            delegate (INavigationHandler handler, BaseEventData eventData)
            {
                NavigationEventData casted = ExecuteEvents.ValidateEventData<NavigationEventData>(eventData);
                handler.OnNavigationCanceled(casted);
            };

        public void RaiseNavigationCanceled(IInputSource source, uint sourceId, object[] tags = null)
        {
            // Create input event
            navigationEventData.Initialize(source, sourceId, tags, Vector3.zero);

            // Pass handler through HandleEvent to perform modal/fallback logic
            HandleEvent(navigationEventData, OnNavigationCanceledEventHandler);

            // UI events
            IPointingSource pointingSource;
            FocusManager.Instance.TryGetPointingSource(inputEventData, out pointingSource);
            PointerInputEventData pointerInputEventData = FocusManager.Instance.GetSpecificPointerEventData(pointingSource);
            if (pointerInputEventData != null)
            {
                pointerInputEventData.InputSource = source;
                pointerInputEventData.SourceId = sourceId;

                if (pointerInputEventData.selectedObject != null)
                {
                    Debug.Log("Stop Dragging");
                    ExecuteEvents.ExecuteHierarchy(pointerInputEventData.selectedObject, pointerInputEventData, ExecuteEvents.endDragHandler);
                    drag = false;
                    dragInitialPosition = Vector2.zero;
                }

                pointerInputEventData.Clear();
            }
        }

        #endregion // Navigation Events

**Comment by StephenHodgson** [comment]
This would also privacy l probably be useful for clicker support as well.

**Comment by keveleigh** [comment]
This functionality should be present in MRTK v2 now as of #3749.
