### ISSUE TITLE
Maximum number of 64 colliders found in PokePointer overlap query. 

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#6052]
## Describe the bug
I am trying to build a color selection list in my personal project, with 48 * PressableButtonHoloLens2 + GridObjectCollection. When I run and hover with the simulated fingertip, the editor gives me these warning message: **'Maximum number of 64 colliders found in PokePointer overlap query. Consider increasing the query buffer size in the pointer profile.'**
![TypeInSpace_ColorList](https://user-images.githubusercontent.com/13754172/65484195-86fead00-de53-11e9-9641-cf8e124890a9.gif)

**Q1**: Is this because too many buttons are too close to each other? Or just the number of the buttons with collider is over 64? The message says 'Consider increasing the query buffer size in the pointer profile' 

**Q2**: Where can I increase the buffer size? I don't see any 'Buffer size' field in the pointer profile.
![2019-09-23 23_06_35-Window](https://user-images.githubusercontent.com/13754172/65485542-02ae2900-de57-11e9-93b2-9f9c4030d365.png)

**Q3**: Would it decrease performance? (increasing the buffer size) 

## Warning message

Maximum number of 64 colliders found in PokePointer overlap query. Consider increasing the query buffer size in the pointer profile.
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.Input.PokePointer:FindClosestTouchableForLayerMask(LayerMask, BaseNearInteractionTouchable&, Single&, Vector3&) (at Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs:169)
Microsoft.MixedReality.Toolkit.Input.PokePointer:OnPreSceneQuery() (at Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs:127)
Microsoft.MixedReality.Toolkit.Input.FocusProvider:UpdatePointer(PointerData) (at Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs:878)
Microsoft.MixedReality.Toolkit.Input.FocusProvider:UpdatePointers() (at Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs:841)
Microsoft.MixedReality.Toolkit.Input.FocusProvider:Update() (at Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs:518)
Microsoft.MixedReality.Toolkit.<>c:<UpdateAllServices>b__60_0(IMixedRealityService) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:880)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServices(IEnumerable`1, Action`1) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:969)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:950)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:UpdateAllServices() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:880)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:580)

## To reproduce
1. Create an empty game object
2. Put 48(or more) x PressableButtonHoloLens2 prefabs under it
3. Assign GridObjectCollection to the parent
4. Update layout (cell width x height = 0.032)
5. Run and hover with simulated hand.
![2019-09-23 22_55_35-Window](https://user-images.githubusercontent.com/13754172/65485559-135e9f00-de57-11e9-9802-796503e647ae.png)

## Expected behavior
No warning messages

## Your Setup (please complete the following information)
- Unity Version [e.g. 2018.4.6f1]
- MRTK Version [e.g. v2.0.0]

**Comment by keveleigh** [comment]
Q1: Looks like it, assuming there are additional colliders around (I think I count 48 color buttons?). This isn't necessarily a bad thing, but an optimization introduced in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5156. You can increase the buffer size if your app depends on it.
Q2: Ah, looks like that message needs to be updated. The buffer size can be found in the Input System Settings: 
![image](https://user-images.githubusercontent.com/3580640/65799454-0082ed80-e129-11e9-8edb-08404e3a3a30.png)
Q3: I believe this number is specific to limiting our allocations per frame. Since it appears to be a one-time allocation, You can change the number as needed by your app.

**Comment by studyVersion** [comment]
> Q1: Looks like it, assuming there are additional colliders around (I think I count 48 color buttons?). This isn't necessarily a bad thing, but an optimization introduced in #5156. You can increase the buffer size if your app depends on it. Q2: Ah, looks like that message needs to be updated. The buffer size can be found in the Input System Settings: ![image](https://user-images.githubusercontent.com/3580640/65799454-0082ed80-e129-11e9-8edb-08404e3a3a30.png) Q3: I believe this number is specific to limiting our allocations per frame. Since it appears to be a one-time allocation, You can change the number as needed by your app.

where is this setting located at?

**Comment by keveleigh** [comment]
> where is this setting located at?

It's on the Mixed Reality Toolkit object in the scene. If you select it and look in the inspector, you'll see an Input System button and should see the system settings after selecting that.

**Comment by studyVersion** [comment]
> > where is this setting located at?
> 
> It's on the Mixed Reality Toolkit object in the scene. If you select it and look in the inspector, you'll see an Input System button and should see the system settings after selecting that.

Thankd for the reply, i found it, but increasing the focus query buffer doen't seem to fix the issue, any other suggestions ?
this is the error message i'm getting:
" Maximum number of 64 colliders found in SpherePointer overlap query. Consider increasing the query buffer size in the pointer profile.
UnityEngine.Debug:LogWarning (object)"
