### ISSUE TITLE
PressableButtonHololens2UnityUI in-editor hit target size is too big

### ISSUE THREAD

**Issue by AdamMitchell-ms** [microsoft/MixedRealityToolkit-Unity#6065]
## Describe the bug

The script that resizes the cube in that button to fit into a rect transform ends up making the hit target very large.

![HitTargetTooBig](https://user-images.githubusercontent.com/41760870/65554530-b6a6c700-dede-11e9-9acd-534d8f581e00.gif)

**Comment by Troy-Ferrell** [comment]
YES! Thank you for fixing this. It's been on my bucket list for a while now

**Comment by AdamMitchell-ms** [comment]
Fixed in mrtk_development by #6066
