### ISSUE TITLE
LeapMotion cross platform support

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#6076]
Add code to enable customers who have installed the LeapMotion SDK to compile MRTK integration code to produce an input data provider. This provider will enable applications to acquire hand data from a connected LeapMotion device and leverage hand interaction with MRTK's UX elements.

Note: This may be a code distribution (both unitypackage and nuget) and will require the developer customer to install the Leap Motion SDK and Unity components.

**Comment by mr0ng** [comment]
@davidkline-ms saw this removed from 2.3. Any additional info on this?

**Comment by wiwei** [comment]
@mr0ng slightly late response, but 2.3 ended up being a fairly targetted release just to get XR SDK + 2019.3 support.

We're starting to work on this now. Hopefully this means it falls into the 2.4 timeframe (i.e. when we work on something != the same iteration it gets released, but the hope is that it's something that makes it to the current one). If not, it *should* fall to the next one once we get the quality and infrastructure collateral there.
