### ISSUE TITLE
not being able to build my app 

### ISSUE THREAD

**Issue by Hololensmoon** [microsoft/MixedRealityToolkit-Unity#6077]
Suddenly, when I am going to create a new project, I am not able to build the project. Even when I open an empty project and just changing the settings for HoloLens. The strange thing is that everything is fine with my previous projects and I can change and rebuild them. I do not know what has happened because I haven't changed anything in my projects. I used different versions of unity, but I got the same error for all of them. I would appreciate any help that can guide me in solving the problem.

![error](https://user-images.githubusercontent.com/54004142/65634632-a9f0a480-dfac-11e9-8467-f8474c69e252.PNG)

**Comment by cre8ivepark** [comment]
Have you tried deleting the Library folder and re-open the project in Unity?

The error message seems something related to the certificates. 
I haven't experienced it in Unity but when I get the certificate error in Visual Studio, it was resolved by creating a new test certificate.

<img width="629" alt="2019-09-25 13_02_48-MixedRealityToolkit - Microsoft Visual Studio" src="https://user-images.githubusercontent.com/13754172/65635371-0d6ed800-df95-11e9-9e0f-f4a5badf3ca1.png">
<img width="305" alt="2019-09-25 13_02_58-MixedRealityToolkit - Microsoft Visual Studio" src="https://user-images.githubusercontent.com/13754172/65635388-12cc2280-df95-11e9-971e-a99863df78c9.png">
<img width="327" alt="2019-09-25 13_03_15-Create Test Certificate" src="https://user-images.githubusercontent.com/13754172/65635394-15c71300-df95-11e9-908d-9276179694b7.png">
<img width="288" alt="2019-09-25 13_03_22-Choose Certificate" src="https://user-images.githubusercontent.com/13754172/65635401-1a8bc700-df95-11e9-8b0d-030f96ca6e3f.png">

**Comment by Troy-Ferrell** [comment]
Does it work if you build to a new app directory for from Unity to the VS solution?

**Comment by Hololensmoon** [comment]
@cre8ivepark
Thanks for your response. Yeah, I actually have deleted the "library" folder and re-open the project in unity (and apparently, a new library folder will be created), but I got the same errors.

**Comment by Hololensmoon** [comment]
@Troy-Ferrell 
Thanks for your response. Yeah, I have tried building the app in a new directory (if I got your point correctly). But the problem has not been solved.

**Comment by Hololensmoon** [comment]
@cre8ivepark 
When I check my "assets" folder, I see that unity does not build the "WSATestCertificate" for my new projects. I know this is the problem but I do not have any idea what has caused this problem because I have not changed anything. Even I do not know in this stage, whether the problem is with Visual Studio or Unity. I would be really thankful if you can guide me in this regard.
