### ISSUE TITLE
Code Configurability - Visual Themes

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#6080]
## Describe the bug

Similar to #5459 , this bug is to track making Visual Themes more configurable. Right now, Visual Themes are very difficult to set up via code and they are very difficult to modify at runtime on InteractableThemeBase. 

notes:
- Difficult to isolate particular property, just access via known index (see below)
- Not well guarded or imposed balance between number of ThemePropertyValues in a ThemeStateProperty to the actual state objects assigned
- The ThemePropertyValue is a bit overloaded and difficult to keep adding additional types
- Slight weirdness in that ThemeDefinitions are copied into InteractableThemeBase at runtime so in some cases have to reference/modify two different endpoints which is a bit redundant

Related bugs:
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5971 
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5497
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4554
- [ ] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6009

## To reproduce

```csharp

var themeDefinition = ThemeDefinition.GetDefaultThemeDefinition<ScaleOffsetColorTheme>().Value;
            // themeDefinition.Easing.Enabled = false;
            // Set the offset state property (index = 1) to move on the Pressed state (index = 2)
            themeDefinition.StateProperties[1].Values = new List<ThemePropertyValue>()
            {
                new ThemePropertyValue() { Vector3 = Vector3.zero},
                new ThemePropertyValue() { Vector3 = Vector3.zero},
                new ThemePropertyValue() { Vector3 = new Vector3(0.0f, -0.32f, 0.0f)},
                new ThemePropertyValue() { Vector3 = Vector3.zero},
            };
            // Set the color state property (index = 2) values
            themeDefinition.StateProperties[2].Values = new List<ThemePropertyValue>()
            {
                new ThemePropertyValue() { Color = DefaultColor},
                new ThemePropertyValue() { Color = FocusColor},
                new ThemePropertyValue() { Color = Color.green},
                new ThemePropertyValue() { Color = DisabledColor},
            };

            Theme testTheme = ScriptableObject.CreateInstance<Theme>();
            testTheme.States = interactable.States;
            testTheme.Definitions = new List<ThemeDefinition>() { themeDefinition };

            interactable.Profiles = new List<InteractableProfileItem>()
            {
                new InteractableProfileItem()
                {
                    Themes = new List<Theme>() { testTheme },
                    Target = translateTargetObject.gameObject,
                },
            };
```
## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by gilbdev** [comment]
related bug:
#6509

#6800
