### ISSUE TITLE
"Hide Cursor" in eye tracking example scenes does not work

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6086]
This is for the eye tracking example scenes.

## Expected Behavior
When I say "hide cursor", the eye gaze indicator hides.

## Actual Behavior
Nothing.

## Steps to reproduce
1. Build MRTK configured to run the example hub
2. Open any eye tracking scene
3. Say "hide Cursor"

## Mixed Reality Toolkit Release Version
2.1.0_stabilization

**Comment by julenka** [comment]
Not a release blocker -- command also does not work in 2.0 mrtk examples hub.

**Comment by julenka** [comment]
@sostel do you know if the "Hide Cursor" command works in your sample if you do not use examples hub? I wonder if this is again related to switching of active profiles #6061

**Comment by sostel** [comment]
> @sostel do you know if the "Hide Cursor" command works in your sample if you do not use examples hub? I wonder if this is again related to switching of active profiles #6061

Yep, works in my examples.

**Comment by dennyronngren** [comment]
I ran into the same issue (on released 2.1.0). It's just the Hide Cursor command that does not work for me, the other voice commands works fine.

**Comment by julenka** [comment]
Since all commands except "hide cursor" work, my guess the profile is just missing that command.

**Comment by sostel** [comment]
I've just tested it and there seems to be an issue with the SpeechInputHandler script which seems to handle voice commands that require focus just fine, but not general voice commands. In the Unity Editor, I had to toggle "IsFocusRequired" twice to take the keycode/voice command. Where there any recent changes to that file?

**Comment by sostel** [comment]
Ok, yes, there seems to be a problem with the profile switching and "general voice commands" (in contrast to voice commands requiring focus). If I disable "LoadProfilesOnStartup" in the additive scenes, then "show cursor" / "hide cursor" works again. I'll take a look what the issue is.

**Comment by sostel** [comment]
So, I tested a bit further and can confirm that if I disable "LoadProfilesOnStartup.cs" then it works fine. If it's enabled, the SpeechInputHandler returns the correct "IsFocusedRequired" value, but doesn't populate it through. I'm not sure where to address this. Hence, for now, I've added a simple workaround, in which I remember the original "IsFocusedRequired" value on startup and set it to true then. In the LateUpdate, I update it to its original value. This seems to work just fine. Certainly not ideal as it would be nice to be able to "cleanly" switch input profiles. @keveleigh or @cre8ivepark Do you know how to address this better?

**Comment by julenka** [comment]
FYI @davidkline-ms  who is working on profile switching for 2.3.

**Comment by dennyronngren** [comment]
Thanks for the quick responses, I'll tryout @sostel fix.

**Comment by julenka** [comment]
Reopening as I just confirmed the command still does not work on latest mrtk hub examples scene.
