### ISSUE TITLE
BoundingBox scales about incorrect pivot

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6088]
## Overview
Regression in 2.1 stabilization. When scaling bounding box near or far, some bounding boxes in the hand interaction example scenes scale about the wrong pivot point. This is especially visible when scaling slate.

## Repro
Scale the slate, cheese, or hololens 2 coffee cup to see the issue in HandInteractionExamples scene. 

## Expected Behavior
Bounding box should scale about opposite corner.

## Actual Behavior
Bounding box seems to scale about some point between opposite corner and center.

![mrtk_2 1_boundingbox_2](https://user-images.githubusercontent.com/168492/65656299-395d7e00-dfd4-11e9-9217-703949bc24d9.gif)

**Comment by davidkline-ms** [comment]
verified rolling back the scaling change addressed this
