### ISSUE TITLE
Cannot interact with UnityUI in Examples Hub

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6089]
## Overview
When you launch the handinteraction examples scene from examples hub, it's not possible to interact with Unity UI near or far.

![mrtk_2 1_unityUI](https://user-images.githubusercontent.com/168492/65656438-b983e380-dfd4-11e9-8094-0498e690c27d.gif)

## Expected Behavior
Should be able to interact with UnityUI example.

## Actual Behavior
Cannot interact with UnityUI example

## Steps to reproduce
1. Configure MRTK to launch examples hub, build to device
2. Open HandInteractionExamples scene and interact with the UnityUI
3. You will notice it is broken.

**Comment by cre8ivepark** [comment]
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6061

**Comment by julenka** [comment]
duplicate of #6061
