### ISSUE TITLE
PressableButtons UnityUI example does not work with hand ray

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6090]
## Overview
PressableButtons UnityUI example does not work with hand ray when the scene is launched using examples hub. It may alsonot work when launched without examples hub (did not test).

![mrtk_2 1_pressableui_2](https://user-images.githubusercontent.com/168492/65656616-55155400-dfd5-11e9-82ef-759e22b37d9c.gif)

## Expected Behavior
Should be able to press unityui buttons with hand ray.

## Actual Behavior
Can press buttons near, but not with hand ray.

**Comment by cre8ivepark** [comment]
@julenka @AdamMitchell-ms I believe this is the same issue that we experience in
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6061
It works well when the scene is not loaded through the Example Hub (profile switching)

**Comment by ritijain** [comment]
@AdamMitchell-ms  - this could be because of the missing Interactable script on the prefab.

**Comment by Railboy** [comment]
@julenka @ritijain This is being caused switching the ActiveProfile. I describe the cause of the bug in #6061.

**Comment by AdamMitchell-ms** [comment]
Thanks for the info @Railboy.  I think you're right and I think it's also related to a similar bug (#6061) in a unit test.

**Comment by julenka** [comment]
Not a regression from 2.0, @cre8ivpark removed UnityUI from the examples hub for this reason. Removing release blocker.

**Comment by julenka** [comment]
Duplicate of #6061
