### ISSUE TITLE
Can't rename objects in the Hierarchy after "Add to Scene and configure ..."

### ISSUE THREAD

**Issue by jdpoenisch** [microsoft/MixedRealityToolkit-Unity#6091]
## Describe the bug

After doing "Add to scene and configure ..." the F2 funtionality for renaming objects in the `Hierarchy` breaks and it is impossible to rename objects except via the Inspector. It is still possible to use <kbd>F2</kbd> to rename Assets.

## To reproduce

1. Create a new Unity Project
2. Import the MRTK 2
3. Until now everything works as expected, you can still rename objects in the hierarchy using <kbd>F2</kbd>
4. Go to <kbd>Mixed Reality Toolkit</kbd> $rightarrow; <kbd>Add to Scene and configure ...</kbd>
5. After doing this and the according objects are added to the scene it is now impossible to rename objects in the Hierarchy pressing <kbd>F2</kbd>! It goes to rename mode for a millisecond then the object is not focused anymore.
6. As soon as the according MRTK2 objects are removed from the scene it works again.

See GIF below

## Expected behavior

Having MRTK2 in the scene should not break the <kbd>F2</kbd> rename shortcut

## Screenshots

[![anim1][1]][1]

[1]: https://user-images.githubusercontent.com/5939315/65667907-feddfa80-e040-11e9-88c0-a2f0ef752bab.gif

## Your Setup

- reproduced in Unity Version `2019.1.14f1`, `2019.2.5f1`, `2019.2.6f1`
- MRTK Version v2.0.0

## Target Platform

 - Not relevant as it is a Bug in the Editor regardless which target platform.

**Comment by Alexees** [comment]
The current mrtk_development branch has a fix for that by
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5746
