### ISSUE TITLE
install into Hololens1 .but it show nothing(has not "made with unity")but hololens remote is normal

### ISSUE THREAD

**Issue by zhudaxing** [microsoft/MixedRealityToolkit-Unity#6092]
and my project be named "win32",i want to know  this is correct?

**Comment by Alexees** [comment]
If not even the engine is launching correctly it's probably not an MRKT bug but something wrong with your project.

**Comment by zhudaxing** [comment]
I want to know  be named"win32"  is true ?maybe I lost some settings

**Comment by Alexees** [comment]
This is what VS needs to show, then you're Win32

![image](https://user-images.githubusercontent.com/32508825/65716761-14ced800-e0a0-11e9-82ca-f566f8370a77.png)
