### ISSUE TITLE
StateManager is not private in Interactable

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#6103]
## Describe the bug

Interactable.StateManager is publicly accessibly directly. Furthermore, the event handlers even get passed a reference to the StateManager on update/state changes. 

This is problematic because the StateManager controls and contain the interactive state information for the Interactable class (i.e HasFocus, HasPress) etc. Many of these state properties need to guard against invalid values or do some other kind of work when their state changes. 

If consumers can just directly set whatever state value on the StateManager themselves, this defeats the purpose of the public interface gates in Interactable and could result in unexpected behavior. 

## To reproduce

Look at Interactable.cs

## Expected behavior

Redesign StateManager interface to not be retrievable by outside consumers or as some kind of readonly interface only.

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Troy-Ferrell** [comment]
This still should be addressed

**Comment by davidkline-ms** [comment]
This would be a significant breaking change in v2.x. MRTK3 has adopted the Unity XR Interaction Toolkit for interactions and this issue no longer applies.
