### ISSUE TITLE
Input simulation indicators interfere with graphics raycasts

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6106]
## Overview
Input simulation indicators show the state of hands which is nice, but placing them in the center of the screen introduces visual clutter. However, when you move the indicators to the sides, they interfere with graphics raycasts.

This bug is preventing us from turning on the input simulation indicators. Once it is fixed we can show the blue viewport indicators.

![image](https://user-images.githubusercontent.com/168492/65729148-1da8b500-e072-11e9-86a8-f8874d3a74d7.png)

See PR #6062 

## Steps to reproduce
Update the input simulation indicators to be 50 px from the bottom left corner for left indicator, 50 px from bottom right for right indicator. Set indicators on in the default profile. 

Run FocusProviderRaycastTests.RaycastProxies test

## Expected Behavior
The test passes

## Actual Behavior
The test fails. You will see also if you try to raycast against Unity UI, the raycast will fail.

**Comment by Alexees** [comment]
@julenka seems this is fixed but the documentation is not updated still stating this bug as pending :
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSimulation/InputSimulationService.html
