### ISSUE TITLE
cannot deploy  MRTK v2 to hololens 1

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#6116]
## Describe the bug
I need update my hololens 1 to 18362 , but hololens cannot receive the update (18362).
Hololens OS version is 10.0.17763.737.
 
## To reproduce

Build and Deploy MRTK v2.0 to hololens 1.

## Screenshots 
![image](https://user-images.githubusercontent.com/38685433/65763498-2377c680-e156-11e9-9de1-d03d7ed3671f.png)

![image](https://user-images.githubusercontent.com/38685433/65763430-fc20f980-e155-11e9-8526-74237402b6ee.png)

## Your Setup (please complete the following information)

- Unity Version [2018.4.0f1]
- MRTK Version [ v2.0]

## Target Platform (please complete the following information)
- HoloLens

**Comment by Troy-Ferrell** [comment]
@lfnoLee, you need an earlier version of the windows 10 SDK installed when building. 
https://blogs.windows.com/windowsdeveloper/2018/10/02/start-developing-on-windows-10-october-2018-update-today/

Then in Visual Studio, not Unity, right click the UWP project -> Properties -> Under General tab in the popup window, change **Target Platform Version** to 10.0.17763.0 or lower

**Comment by Troy-Ferrell** [comment]
@IfnoLee
If using the build window, this is probably fixed by #5877 

Try building with regular Unity build: 

In the VS solution, not Unity, right click your UWP project and select Properties. Then under the General tab make sure
Target Platform Version => 10.0.18362.0
Target Platform Min Version => (basically anything but will probably be 10.0.10240.0)

**Comment by IfnoLee** [comment]
show errors in Visual studio 2017.
![image](https://user-images.githubusercontent.com/38685433/65827152-d57fd180-e2c1-11e9-97c0-c181881b9d58.png)
![image](https://user-images.githubusercontent.com/38685433/65827159-e9c3ce80-e2c1-11e9-9ee7-54df65a75f83.png)
![image](https://user-images.githubusercontent.com/38685433/65827169-0b24ba80-e2c2-11e9-829d-f78fea3c5860.png)
![image](https://user-images.githubusercontent.com/38685433/65827183-2263a800-e2c2-11e9-96e8-ac030120c656.png)

**Comment by IfnoLee** [comment]
I ignore these errors in Unity2018.4.0f1.
![image](https://user-images.githubusercontent.com/38685433/65827210-65be1680-e2c2-11e9-93e5-b6ca87037a77.png)

**Comment by IfnoLee** [comment]
@wiwei  @Troy-Ferrell

**Comment by wiwei** [comment]
@IfnoLee 

Kinda belated reply, and in case this is still something you're hitting, the first image that's above is a little different from what's recommended in here:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Images/getting_started/SwitchPlatform.png

The last image shared looks to be right, but the errors in the console suggest that the latest SDK isn't actually installed (that's the only time I've seen those types of errors). What does "Target SDK Version" look like in the dropdown itself?

**Comment by Troy-Ferrell** [comment]
@IfnoLee were you able to resolve this? A
