### ISSUE TITLE
TestGazeProviderTargetNotNull and ScaleViaHl1Interaction are failing intermittently

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6121]
## Overview
We aim to fix intermittent failures right away so they do not block people

TestGazeProvierNotNull is failing intermittently, for example see https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=5608&view=ms.vss-test-web.build-test-results-tab

**Comment by Troy-Ferrell** [comment]
Also I saw ScaleViaHL1Interaction failing
