### ISSUE TITLE
Registered Services throws NullReferenceException when service is added

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6134]
## Describe the bug

When adding a service to the Registered Services a NullReferenceException is thrown by the inspector because adding the entry does not define the actual type of service.

## To reproduce

1. Add SceneTransitionService, which currently is the only one

## Expected behavior

No error

## Your Setup (please complete the following information)

- Unity Version 2018.4.6f1
- MRTK Version mrtk_development

## Target Platform (please complete the following information)

- Editor

**Comment by davidkline-ms** [comment]
i believe this was fixed in 2.1.0 or 2.2.0. i am not experiencing it in the current development branch (and was, in fact, testing this scenario)
