### ISSUE TITLE
only see 2D scene

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#6135]
## Describe the bug
I deploy MRTK Example to Holoens 1, but I only see 2D window in scene，and I donot make any change with camera.

## To reproduce

1. Build HandInteractionExamples scene （The same is true of other scenes）;
2. deploy to Hololens 1 via visual studio 2017;
3.  see 2D scene; 

## Screenshots
![image](https://user-images.githubusercontent.com/38685433/65830460-3c14e780-e2e2-11e9-9aa7-b590690fa9e9.png)
![image](https://user-images.githubusercontent.com/38685433/65830258-6fef0d80-e2e0-11e9-99b2-7564a45760a8.png)
![image](https://user-images.githubusercontent.com/38685433/65830363-63b78000-e2e1-11e9-8c4c-6fdffcb776b3.png)
![image](https://user-images.githubusercontent.com/38685433/65830377-8d70a700-e2e1-11e9-9fba-42582fdad39c.png)
![image](https://user-images.githubusercontent.com/38685433/65830404-b7c26480-e2e1-11e9-90a1-86118f650cb8.png)
![image](https://user-images.githubusercontent.com/38685433/65830411-c3ae2680-e2e1-11e9-8e6a-fbe610fb0890.png)

## Your Setup (please complete the following information)

- Unity Version [2019.2.6f1]
- MRTK Version [v2.0]

## Target Platform (please complete the following information)

- HoloLens

**Comment by coderFirework** [comment]
Yes, The same bug exists in my project. Does anyone know how to fix it?

**Comment by neur19** [comment]
Turn off WSA holographic remoting in XR setting before building. That should do the trick.

**Comment by IfnoLee** [comment]
> Turn off WSA holographic remoting in XR setting before building. That should do the trick.

Thank you , it is OK!
