### ISSUE TITLE
Backspace doesn't work on system keyboard.

### ISSUE THREAD

**Issue by darosas** [microsoft/MixedRealityToolkit-Unity#6149]
## Describe the bug

When typing on the system keyboard, the backspace key doesn't delete previously typed characters.

## To reproduce

1. Go to HandInteractionExample scene.
2. Add a text mesh that outputs keyboard text.
3. Click on Open Keyboard
4. Type something on the keyboard
5. Press the backspace key.
6. Notice how nothing gets deleted.

## Expected behavior

Previously typed characters should be deleted when you press backspace.

## Your Setup (please complete the following information)

- Unity 2019.2.6f1
- Microsoft Mixed Reality Toolkit 2.1.0

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by Railboy** [comment]
This is becoming a blocking issue for an MRTK project we're working on.

**Comment by Cameron-Micka** [comment]
@Railboy I have a fix for this coming soon.

**Comment by Magmoule** [comment]
> 
> 
> @Railboy I have a fix for this coming soon.

I still have this issue with MRTK 2.3.0

Is it possible to reopen this one ?

**Comment by Cameron-Micka** [comment]
@Magmoule are you seeing the issue in Unity 2019? Unfortuantly a bug was introduced in 2019 that broke the backspace key: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6921#issuecomment-591026358
