### ISSUE TITLE
Hands-Free Button

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#6153]
## Describe the problem
Seems i didn't find this kind of button yet:

Having a prefab button that can be clicked automatically after focusing it for a given time.

This is useful when both of your hands are used with real (or virtual..) tools for example (mostly an hololens request, but can be applied elsewhere too i guess).

## Describe the solution you'd like

- user focus the button (with head or eye tracking)
- the button 'fills' visually
- the user can unfocus it to cancel
- once fully filled, the onclick is automatically triggered
- if the user stays focus on the button after it has been triggered, the fill process does not start (user has to unfocus and focus again)

## Additional Context
see Guides 365 videos for examples

**Comment by cre8ivepark** [comment]
@sostel has been investigating Gaze & Dwell button.

**Comment by ritijain** [comment]
This was an attempt to bring the Guides 365 implementation to MRTK - https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit.SDK/Experimental/Features/Dwell/DwellHandler.cs

Unfortunately there is no prefab for this yet. But there is an example scene which demonstrates this - 

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit.Examples/Experimental/Dwell/DwellScene.unity

**Comment by sostel** [comment]
> @sostel has been investigating Gaze & Dwell button.

@gilbdev Yes, this is already part of the eye tracking demo scenes, but is not well documented yet. If you try out the eye tracking demo scenes, you can say "Enable dwell" and you can simply look at (or move the simulated eye gaze cursor over) at one of the UI elements in the top bar of the scenes that let you switch between the eye tracking examples. You can then load the scene and explore the functionality of the DwellSelection.cs. 
![image](https://user-images.githubusercontent.com/32180789/66065955-867eaa00-e516-11e9-8422-0c81fdb10a1b.png)

**Comment by julenka** [comment]
There is also a set of experimental dwell buttons in mrtk under MRTK.Examples/Experimental/Dwell that do what you are asking for. Closing since the features exist as experimental. Would love to hear your feedback on the dwell buttons we have so far! See #5594

**Comment by gilbdev** [comment]
Thanks all!
will try that dwell button :)
