### ISSUE TITLE
Issue with MRTK keyboard (system keyboard on HL2)

### ISSUE THREAD

**Issue by agosselin** [microsoft/MixedRealityToolkit-Unity#6155]
## Describe the bug

It seems there is a few issue with the keyboard: 1) the system keyboard doesn't allow you to preview the text while you type on the keyboard. 2) There is no way to complete the text (aka no way to trigger TouchScreenKeyboard.Status.Done). 3) The first time the keyboard appears you can read the .text properties  4). You can only add new text, delete doesn't seems to work and every time you spawn the keyboard the old text is there

## Expected behavior

1) we should have a way to see the preview text window
2) I would like to see a 'done' button for the user to specify when he is actually done entering the text
3) Keaybord.text should work the first time
4) Every time I show the keyboard the text should be empty. Delete button should work and setting keyboard.text to an empty string should clear the values

## Your Setup (please complete the following information)

- Unity Version 2019.1.1f1
- MRTK Version v2.0

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by techtide** [comment]
This issue persists even in the HoloLens 1, where the system keyboard does not show previews and the delete button does not work (in D3D).

**Comment by Cameron-Micka** [comment]
@techtide Thank you for reporting, there is another issue tracking this problem: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6759

**Comment by gigxr** [comment]
We still encounter this on MRTK 2.4. The preview window does not appear.

**Comment by polar-kev** [comment]
Preview text and delete key issues required fixes on the Unity side. According to Unity they are fixed in 2019.4.9f1, 2020.1.3f1 and 2020.2.0a20. Please let us know if you see otherwise.
