### ISSUE TITLE
BoundingBox stops scaling object correctly on device (HL1)

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#6163]
## Describe the bug

Loading HandINteractionExamples scene for stabilization branch on HL1 device, scaling the bounding box corners scales object but then object stops scaling even though BB keeps scaling

## To reproduce

Build HandINteractionExamples scene for HL1
Run on device
Scale object on left hand side and notice incorrect scaling

NOTE: The panel seems to scale fine

## Expected behavior

Scale like in editor

## Screenshots

![image](https://user-images.githubusercontent.com/25975362/66006945-56c39980-e465-11e9-90d1-b1635dec9004.png)

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version - Stabilization 10/1

## Target Platform (please complete the following information)

HL1

**Comment by julenka** [comment]
Seems like duplicate of #6088

**Comment by julenka** [comment]
Reopening, since #6088 has been fixed but looks like Troy was able to repro on a build that was supposed to have that fix.

**Comment by Troy-Ferrell** [comment]
Ignore false alarm
