### ISSUE TITLE
Consolidate usage of Renderer.material(s) with MaterialInstance.

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#6166]
## Describe the bug

A cleanup pass should be done to remove usage of [Render.material(s)](https://docs.unity3d.com/ScriptReference/Renderer-material.html) and replace it with the MaterialInstance behavior from https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6165/. This will reduce accidental leakage of materials. See the note from the Unity [Render.material(s)](https://docs.unity3d.com/ScriptReference/Renderer-material.html) docs: 

> Note:
This function automatically instantiates the materials and makes them unique to this renderer. It is your responsibility to destroy the materials when the game object is being destroyed. Resources.UnloadUnusedAssets also destroys the materials but it is usually only called when loading a new level.

## To reproduce

1. Play a scene
2. Invoke a script which calls [Render.material(s)](https://docs.unity3d.com/ScriptReference/Renderer-material.html)
3. Open the Unity Profiler Memory Panel
4. Take a detailed memory snapshot
5. Look under Scene Memory/Materials
6. Note the material count
7. Delete the game object which invoked Render.material(s)
8. Note the material count remains the same

## Expected behavior

Scene materials are removed with the object which instantiates them.

## Screenshots

![image](https://user-images.githubusercontent.com/13305729/66009694-7a401180-e470-11e9-87ed-10e877c699b5.png)

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Cameron-Micka** [comment]
Needs to be consolidated with UIMaterialInstantiator from PR #6049

**Comment by Cameron-Micka** [comment]
@wiwei this is probably something that should still be addressed to avoid materials leaks.

**Comment by Zee2** [comment]
@Cameron-Micka ; closing this here, if this is still relevant for MRGT make sure to copy it over.
