### ISSUE TITLE
The System Keyboard Does Not Have a Preview Area on HoloLens 2

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#6167]
## Describe the problem

It is difficult to determine what is being typed using the system keyboard on HoloLens 2 because a preview panel doesn't exist like what is found in the shell.

## Describe the solution you'd like

A text panel which mimics the shell (built within Unity) can tag along with the system keyboard to aide with text input.

## Additional context

This has come from internal and external requests.

Shell Keyboard:

![20191002_102433_HoloLens](https://user-images.githubusercontent.com/13305729/66066922-5b3c9080-e4ff-11e9-899d-3e894e294417.jpg)

MRTK System Keyboard:

![20191002_102704_HoloLens](https://user-images.githubusercontent.com/13305729/66066943-68597f80-e4ff-11e9-84d3-81b37df03c79.jpg)

**Comment by Cameron-Micka** [comment]
Tried using https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.inputpane.occludedrect#Windows_UI_ViewManagement_InputPane_OccludedRect which is not available on HoloLens 2. A viable option may be this API once it is out of preview: https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.preview.holographic.holographickeyboardplacementoverridepreview

**Comment by Troy-Ferrell** [comment]
@Cameron-Micka  This lack of preview should be occurring on all Unity apps, regardless of MRTK or not, correct? I believe MRTK is mainly calling the TouchScreenKeyboad.Open
https://docs.unity3d.com/ScriptReference/TouchScreenKeyboard.Open.html

I'm not seeing any way into that API to control preview though. I wonder what the platform teams for the shell keyboard thinks

**Comment by Cameron-Micka** [comment]
@Troy-Ferrell you are correct that this isn’t MRTK specific. I spoke with a member of the keyboard team last week and notified them of the issue. As an interim(?) fix I’m making a UI widget that looks and behaves similar to the Shell window. I’m also addressing these issues: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6155 & https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6149
