### ISSUE TITLE
PressableButtonHoloLens2Toggle prefab is not a toggle button

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#6169]
## Describe the bug

The PressableButtonHoloLens2Toggle button is actually not a toggle, but a standard button.
- when changing to a toggle, the button does not behave correctly (see attached gif) #6187 
## Expected behavior

prefab should be fixed to be a toggle button andhave a correct behavior

## Screenshots

![image](https://user-images.githubusercontent.com/49415246/66033338-5bd92500-e507-11e9-9121-3cdb8fbaddb9.png)

## Your Setup (please complete the following information)

- Unity Version [2018.4.9f1]
- MRTK Version **[v2.1 Stabilization branch]**

## Additional context

#5254
#5457

**Comment by julenka** [comment]
Fixed
