### ISSUE TITLE
MRTK v2 low fps

### ISSUE THREAD

**Issue by StarWardo** [microsoft/MixedRealityToolkit-Unity#6170]
## Describe the bug

When starting a new empty project I get a low FPS count on device. Diagnostics window is showing around these numbers: CPU 25-30 (30-40ms) , used 245mb , peak 246mb and limit 900mb.

## To reproduce

1. Create a new Unity Project (I am using 2019.1.10f1)
2. Import the mrtk assets 
3. Create a new scene and configure (I am using the default profile)
4. Open the optimization window and make sure everything is checked
5. Add a cube in front of the camera with MRTK standard shader
6. Set quality settings to: Very Low
7. Build to HL1

## Expected behavior

Expected the FPS count to be at least 60 FPS on device for an empty project. 

## Your Setup (please complete the following information)

- Unity Version 2019.1.10f1
- MRTK Version v2.0

## Target Platform (please complete the following information)

- HoloLens 1

**Comment by Troy-Ferrell** [comment]
Are you building debug, release, or master?

**Comment by StarWardo** [comment]
@Troy-Ferrell Thanks - I am getting twice the results with the release build.

**Comment by EdoParo95** [comment]
@StarWardo did u fix the problem?

**Comment by Zikun-Huang** [comment]
hi @StarWardo 
I got same issue happens on HL2 as well. Did you fix the issue eventually?
