### ISSUE TITLE
"ignore settings prompt on startup" in project settings is applied globally

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6174]
## Overview
The ignore settings prompt on startup" option is located in MRTK project settings, which makes me think it is local to my project. However, the setting is applied globally.

## Steps to reproduce
1. Edit > Project Settings > Mixed Reality Toolkit check "ignore settings prompt on startup" for an mrtk project.
2. Create a brand new project, import MRTK

## Expected Behavior
For my new project I would expect to be prompted to set up MRTK because the "ignore settings prompt" is a _project setting_, which to me indicates it is _local to the project_

## Actual Behavior
The setting is _global across all my unity projects_.

Since the setting is global, the setting should go in preferences, not project settings

_(Links to sample github project preferred)_

**Comment by julenka** [comment]
@Troy-Ferrell and @davidkline-ms I believe this setting was intentionally set to global, is that correct?

**Comment by Troy-Ferrell** [comment]
Huh, maybe this was recently moved? I thought these parameters used to be under **Edit** > **Preferences** > **MRTK** tab which would make more sense. Because I believe they are supposed to be global across all Unity project for YOUR dev machine. They shouldn't be settings to be checked into source just your dev environment

**Comment by keveleigh** [comment]
It was moved a while back, in April at the latest (but really before that, since that commit seems to just make the Unity default behavior for that API more explicit for future-proofing): https://github.com/microsoft/MixedRealityToolkit-Unity/commit/3ed9025340596ecdf17ebac5437ee3a37b57d3ac
