### ISSUE TITLE
Pin / unpin on toggle features panel does not work

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6176]
## Steps to reproduce
1. Grab the latest 2.1 prerelease
2. Build to HL2
3. Press the pin / unpin button

![pinunpin2](https://user-images.githubusercontent.com/168492/66071748-8d9ebb80-e508-11e9-98f6-c614b55f5618.gif)

## Expected Behavior
When I press, the button should toggle and menu should follow me

## Actual Behavior
The button does not toggle and follow me

**Comment by julenka** [comment]
Marking this is as release blocker since it is user visible defect for a feature we are advertising

**Comment by Troy-Ferrell** [comment]
On latest stabilization via git branch and in Unity 2018.6, the hand interaction examples scene pin works

![pin](https://user-images.githubusercontent.com/25975362/66075808-38b37300-e511-11e9-9a91-60c7e28a2c36.gif)

**Comment by Troy-Ferrell** [comment]
Version of this not working is same as #6169 

For some reason, Unity is not treating FormallySerailizedAs properly. Try updating to latest stabilization and trying

**Comment by julenka** [comment]
Duplicate of #6169
