### ISSUE TITLE
Oculus Quest controller input issues, No Controller interaction mappings found

### ISSUE THREAD

**Issue by SiriusA7** [microsoft/MixedRealityToolkit-Unity#6177]
## Description

When building out the latest stabilization branch to android targeting oculus quest, the touch controllers never show up and no controller inputs are registered.
Probably related to #6164 

Repeated error in Logcat console when testing in Quest headset:

```
Oculus Quest Controller - Left does not have a defined controller type, falling back to generic controller type
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:GetCurrentControllerType(String)
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:GetOrAddController(String)
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:RefreshDevices()
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:Update()
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:Update()
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServices(IEnumerable`1, Action`1)

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

No Controller interaction mappings found for Microsoft.MixedReality.Toolkit.Input.UnityInput.GenericJoystickController.
Microsoft.MixedReality.Toolkit.Input.BaseController:SetupConfiguration(Type, InputSourceType)
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:GetOrAddController(String)
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:RefreshDevices()
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:Update()
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:Update()
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServices(IEnumerable`1, Action`1)

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

```

## To reproduce

1. Load any demo scene (tested BoundaryVisualization, ControllerMappingTool, & HandInteractionExamples
2. Set Android build target and install oculus android and Logcat from package manager
3. Basic project settings setup noted on oculus developer documentation
4. 'Build And Run' with 'Run Device' set as Quest headset

## Expected behavior

Touch Controllers or default axis controller model to be visualized and inputs to be registered.

- Tested Unity Versions 2018.4 - 2019.2
- MRTK Version  v2.1 stabilization

## Target Platform

- Android
- OpenVR
- Oculus Quest

## Additional context

General build-out and install to the quest headset is relatively successful. When in HandInteractionExamples headset gaze cursor visually interacts with all the elements. The ControllerMappingTool works and shows inputs, but still no default controller model or input reactions.
No difference when testing #5830

**Comment by keveleigh** [comment]
Related to #4549 

We don't yet have full Quest support in MRTK, but we've been working on making them work better together! Thanks for filing this for our work items.

**Comment by keveleigh** [comment]
@RogPodge Would you say this is resolved with your Quest work?

**Comment by RogPodge** [comment]
Yeah this should be fixed, I haven't had any incidents where the Oculus Controllers never get recognized (thanks xrsdk :D)
