### ISSUE TITLE
Evaluate performance of PressableButtonUnityUI

### ISSUE THREAD

**Issue by ritijain** [microsoft/MixedRealityToolkit-Unity#6180]
## Describe the Issue

Creating 3D content  using UnityUI can be fairly tricky, and can cause performance issues. There have been some concerns raised by partners that when a button which is a very core components of any app is not performant, it can cause some serious perf issues. 

I realized that the Unity UI pressable button is using 2 Image components rendered at different Z depths. While it looks great and is  fully functional, how does it impact perf?

**Comment by ritijain** [comment]
@AdamMitchell-ms , @julenka -

I am not sure if a discussion about performance happened when this work was done. If this seems like a legit concern, then there should be a perf evaluation of this  (and similar unity ui) components.

If there are no concerns, i think it would be great to capture the discussion on Github so that we can point it to folks who express concerns.

**Comment by Zee2** [comment]
This is an ongoing concern for Canvas-based elements in MRTK3. Already having an ongoing discussion with @Cameron-Micka for how best to mitigate drawcalls here.

**Comment by Zee2** [comment]
Investigation is ongoing and promising developments in order :)

**Comment by AMollis** [comment]
@marlenaklein-msft Can you follow-up with @Cameron-Micka on his ideas here

**Comment by AMollis** [comment]
We're now tracking this issue with the following investigation task

- [Investigate performance improvements to canvas UI#11471](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11471)
