### ISSUE TITLE
MRTK does not function out-of-the-box with the Unity 2019.3.0b4 Universal Render Pipeline template

### ISSUE THREAD

**Issue by djohnsomsft** [microsoft/MixedRealityToolkit-Unity#6181]
## Describe the bug

When applying the MRTK to Unity's URP sample, there is buggy behavior with the rendering appearing to come from the wrong camera, resulting in the profiler UX flying around detached with the standard controls when run in the editor.

## To reproduce

1. Create a new Universal Render Pipeline project.
2. Change settings to enable Windows Mixed Reality for the project.
3. Import MRTK Foundation package (2.0.0)
4. Run the utilities to "Add to scene and configure" for HL2 as well as "Upgrade MRTK Standard Shader for Lightweight Render Pipeline"
5. Turn off the "Simple Camera Controller" script on the camera.
6. Run in editor.

Image in Game mode:
![image](https://user-images.githubusercontent.com/27969160/66079516-11f93a80-e519-11e9-8bd2-fe7eaaab0e0f.png)

Scene view shows the camera rendering a completely different frame. The back buffer appears to also not clear correctly when the main camera is moved manually.

![image](https://user-images.githubusercontent.com/27969160/66079602-39500780-e519-11e9-8330-2ba683be2d5a.png)

The profiler is visible moving around from the Game view when WASD are used, and the lighting and culling of the scene appear to change.

![image](https://user-images.githubusercontent.com/27969160/66079733-803dfd00-e519-11e9-8a9c-7333c1fa6cba.png)

## Setup

- Unity 2019.3.0b4
- MRTK 2.0.0

**Comment by djohnsomsft** [comment]
Experimenting further, this also occurs building a plain 3D project with MRTK and adding URP to it (with a default UniversalRenderPipelineAsset). When deployed to device, the camera seems to be correct, but the back buffer doesn't seem to clear and a "hall of mirrors" effect occurs.

**Comment by djohnsomsft** [comment]
This also reproduces without MRTK just by using WMR + URP. Filed a bug report with Unity tracking this with a min repro (Case 1188596, for reference).

**Comment by davidkline-ms** [comment]
Closing as this is not MRTK specific and @djohnsomsft has filed a Unity issue

**Comment by Cameron-Micka** [comment]
Posting the Unity issue tracking this here: https://issuetracker.unity3d.com/issues/uwp-xr-lwrp-gameview-camera-rendering-from-incorrect-transform-when-entering-play-mode
