### ISSUE TITLE
PressableButtonHoloLens2Toggle front plate moves back with successive presses

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6187]
## Describe the bug
Toggling the toggle button via far interaction multiple times causes the front plate to move back.

![togglebug](https://user-images.githubusercontent.com/49415246/66033804-4dd7d400-e508-11e9-829c-7c55738efac0.gif)

## Expected Behavior
After the hand releases at distance, front plate should return to original position

## Actual Behavior
Front plate does not return to original position

## Your Setup (please complete the following information)

- Unity Version [2018.4.9f1]
- MRTK Version **[v2.1 Stabilization branch]**

## Additional context

#5254
#5457

**Comment by julenka** [comment]
Apply fix to #6169 before working on this, it requires that fix (otherwise pressablebuttonhololens2toggle will not actually show up as a toggle)

**Comment by gilbdev** [comment]
from what i've seen:

when changing a Button to a Toggle, the themes changes accordingly , from 1 theme, to 2 themes (Selected/Deselected)
preivously there was only one theme with an offset for FrontPlate in the 'Pressed' state.

when toggling the button, it also switch theme, which probably lead to this bug 
(Pressed state may not be 'on' when switching theme ??)

**Comment by julenka** [comment]
Duplicate of #6178 and I have a fix I will be making a PR for shortly.

**Comment by julenka** [comment]
Fixed
