### ISSUE TITLE
Unreliable test PointerBehaviorTests.TestGrab

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6194]
## Overview
PointerBehaviorTests.TestGrab failed from unrelated changes in PR 
 #6168. The failure was: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6186/checks?check_run_id=245737592

Error was:
```
 Incorrect state for Left Line Pointer.IsInteractionEnabled
  Expected: False
  But was:  True
```

**Comment by CDiaz-MS** [comment]
Could not repro test failure after running TestGrab 1000 times.  Closing this issue.
