### ISSUE TITLE
[Docs] Getting Started Page - broken links, table layout, outdated content

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#6201]
## Describe the bug
There are some broken links, table layout, outdated content.

![2019-10-03 11_24_19-MixedRealityToolkit-Unity_GettingStartedWithTheMRTK md at mrtk_development · mic](https://user-images.githubusercontent.com/13754172/66158255-61ec0600-e5da-11e9-9f90-15da1e23ea09.png)

**Comment by Troy-Ferrell** [comment]
@cre8tivepark is this fixed?
