### ISSUE TITLE
ExamplesHub null active profile - Windows Mixed Reality

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#6209]
## Describe the bug
While running the MRTKExamplesHub scene for Windows Mixed Reality, there is a null active profile error.
```
No Mixed Reality Configuration Profile found, cannot initialize the Mixed Reality Toolkit
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:293)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ResetConfiguration(MixedRealityToolkitConfigurationProfile) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:117)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:set_ActiveProfile(MixedRealityToolkitConfigurationProfile) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:87)
Microsoft.MixedReality.Toolkit.Examples.Demos.EyeTracking.LoadProfilesOnStartup:Start() (at Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/General/Scripts/Utils/LoadProfilesOnStartup.cs:19)
```

## To reproduce

- Connect Windows Mixed Reality headset
- Import latest stabilization test packages
- Run the MRTKExamplesHub Scene from the editor
- Error: No Mixed Reality Configuration Profile found, cannot initialize the Mixed Reality Toolkit

## Your Setup 

- Unity Version: 2018.4.7f1
- MRTK Version: Stabilization for 2.1

## Target Platform

- WMR immersive
- OpenVR

## Additional context

Eye tracking is causing the issue and WMR does not have eye tracking capabilities.

**Comment by cre8ivepark** [comment]
@Cameron-Micka @Railboy

**Comment by Railboy** [comment]
The error message is technically by design. The LoadProfilesOnStartup sets the ActiveProfile to null, and that action will always generate an error. We should change it from an error to a warning if we intend to support setting ActiveProfile to null.

**Comment by davidkline-ms** [comment]
This issue is unlikely to be addressed as primary development has moved to MRTK3 (and that this issue impacts only the Examples Hub)
