### ISSUE TITLE
Access denied using WorldAnchorTransferBatch Export

### ISSUE THREAD

**Issue by tvrDev** [microsoft/MixedRealityToolkit-Unity#6210]
## Describe the bug

Using WorldAnchorTransferBatch.ExportAsync() returns 

`SpatialAnchorTransferManager denied access to WorldAnchor serialization
UnityEngine.XR.WSA.Sharing.WorldAnchorTransferBatch:ExportAsync_Internal(WorldAnchorTransferBatch, SerializationDataAvailableDelegate, SerializationCompleteDelegate)
UnityEngine.XR.WSA.Sharing.WorldAnchorTransferBatch:ExportAsync(WorldAnchorTransferBatch, SerializationDataAvailableDelegate, SerializationCompleteDelegate)`

I am developing a VR UWP application on Windows 10 for the new HP Reverb which has inside out tracking. 

**WorldAnchors are working perfectly** in editor and with deployed apps, trying to export them however gives me the above error.

Also tried the azure spatial anchors example [project](https://github.com/Azure/azure-spatial-anchors-samples) with the same outcome. The Error reads "Access denied to spatial anchor exporter. Ensure your OS build is up to date and the spatialperception capability is set."

Spatial Perception is checked in the "capabilities".

## Your Setup
- Unity Version 2019.2.7
- MRTK 2.0
- HP Reverb Professional Edition

## Target Platform
- WMR immersive

**Comment by KevinKennedy** [comment]
Do you have "SpatialPerception" selected in the Unity Project Settings -> Universal Windows Platform settings -> Publishing Settings -> Capabilities dialog:
![image](https://user-images.githubusercontent.com/6423774/66230940-26b10c00-e69a-11e9-8295-fb6e5e46d19d.png)

You can also verify it's making it to Visual Studio by checking the .appxmanifest Capabilities:
![image](https://user-images.githubusercontent.com/6423774/66231107-83acc200-e69a-11e9-9d3d-b18950e32cb7.png)

**Comment by tvrDev** [comment]
I did check for that repeatedly, then I went overboard and tried checking them all, didnt work either :')

**Comment by Troy-Ferrell** [comment]
Related #1725
@tvrDev, it may be that export is not supported on VR headsets but the related item is very old.

FYI, WorldAnchorTransferBatch API is not MRTK, it is an Unity API for particular use with the Windows Mixed Reality platform. 

It'll be easier for someone on one of the Windows Mixed Reality channels to specialize on this issue. 

Slack and Twitter
--
https://aka.ms/holodevelopers
https://twitter.com/MxdRealityDev

If I find an answer, I'll be sure to ping this thread though.
