### ISSUE TITLE
Designtime build failed for project IntelliSense might be unavailable.

### ISSUE THREAD

**Issue by PatientEz** [microsoft/MixedRealityToolkit-Unity#6226]
## Describe the bug

i use MRTKv2 and i build scenes successfully.
![image](https://user-images.githubusercontent.com/47288625/66307803-fb4b4d00-e937-11e9-84b1-34fbad7bb1fa.png)

But when i open .sln in visual studio 2019,
it shows error : Designtime build failed for project 'D:\UnityWorkSpace\MR\APP\MR\MR.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
![image](https://user-images.githubusercontent.com/47288625/66307816-030af180-e938-11e9-9a54-9771af943525.png)
![image](https://user-images.githubusercontent.com/47288625/66307825-0dc58680-e938-11e9-9744-5da74fa0d3db.png)

i try to  disable IntelliSense but it doesn't work ,i find maybe it  is caused by the project being moved,so i want to get some suggets here

## Expected behavior

i expect i can figure out this problem so i can use hololens2 emulator to run this appliaction

## Your Setup (please complete the following information)

- Unity Version 2019.2.3f1
- MRTK Version v2.0.0
- Win10SDK Version 10.0.18362.0

**Comment by wiwei** [comment]
It looks like this is something that folks have hit in other projects as well, enough such that there's some guidance on how to dig further:

https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/visual-cpp-intellisense-configuration.md#troubleshooting-intellisense-build-failures

If you follow the instructions there, are there more helpful notes/logs about what went wrong?

**Comment by keveleigh** [comment]
Closing out, as Will provided some info above and there hasn't been a follow-up in several months. Please re-open if you have additional info!
