### ISSUE TITLE
Add page tracking to documentation pages

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#6227]
## Describe the Issue
Add site tracking functionality to the github pages feature of MRTK to track visitor count for each individual page.

## Feature Area
Site tracking

## Existing Doc Link
If this is about something in an existing document, please provide link 

## Additional context
https://webapps.stackexchange.com/questions/103618/analytics-on-github-pages

**Comment by Troy-Ferrell** [comment]
MRTK should still have page analytics

**Comment by polar-kev** [comment]
Now that documentation is hosted on docs.microsoft.com, we collect visitor count date.
