### ISSUE TITLE
Hand mesh toggle button disables hand input

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#6234]
## Describe the bug

Hand mesh toggle button in the toggle features panel disables hand input and freezes HoloLens 2 app.

## To reproduce

1. Build HandInteractionExample - UWP
2. Connect HoloLens 2
3. Run app through visual studio: Release, ARM, Device
4. Press hand mesh toggle button in the toggle features panel

## Screenshots

[Video of Issue - Hand Mesh Toggle](https://youtu.be/tvyGgy6a9QU)

## Your Setup (please complete the following information)

- Unity Version 2018.4.7f1
- MRTK Version v2.1

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by davidkline-ms** [comment]
fixed with #6238
