### ISSUE TITLE
Tile Grid Object Collection needs some rework

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#6237]
## Describe the bug
Today, i tried to use Tile Grid Object Collection ..

first of all : "Centered" option is bugged (missing parenthesis in the code arround `Column - 1`)
secondly : does not derive from BaseObjectCollection or GridObjectCollection
third (link to 2nd) : the position is updated constantly in the Update() function (performance issue) 
fourth : typo in property `LayoutDireciton`

lastly, not sure what the difference is from Grid, and documentation is not very explicit (and misleading, as we can think it inherit from Grid) :

> `TileGridObjectCollection.cs` provides some additional options to GridObjectCollection

## Expected behavior

minimal : fix 1 and 4 
optimized: inherit from Grid and document better to tell what are the differences
radical : remove TileObjectCollection

## Your Setup (please complete the following information)

- Unity Version [2018.4.9f1]
- MRTK Version [2.1 stabilization]

## Additional context

I can help and make a PR based on decision

**Comment by julenka** [comment]
Fixed by #6550 ,
