### ISSUE TITLE
Toggle-Dot moves outside of control constraints

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#6241]
from: https://stackoverflow.com/questions/58283654/mrtk-v2-toggle-dot-moves-outside-of-constraints

Description - I have a settings panel in my scene which appears if I click the settings button on my toolbar. By repeating this, I noticed one bug → The dot of all toggled toggles moves further and further. The dot of an untoggled toggle stays in the right position. Did someone fix that bug in the script interactable or did a workaround?

![image](https://user-images.githubusercontent.com/13281406/66434862-53399080-e9d8-11e9-8766-1ec2461b0392.png)

How to reproduce - I used the toggles that were given by the example package. Place one that is already toggled and one not toggled and start play mode. Activate and deactivate the script Interactable on your toggle and you should see this behavior

![image](https://user-images.githubusercontent.com/13281406/66434901-68aeba80-e9d8-11e9-873a-3904f555808c.png)

Unity 2019.2.8f1
MRTK 2.0.0

**Comment by Troy-Ferrell** [comment]
@davidkline-ms, I believe this was fixed for 2.1. 

I think this is actually related to the bug fix @CDiaz-MS did

**Comment by CDiaz-MS** [comment]
@Troy-Ferrell @davidkline-ms,  just confirmed that this issue has been fixed in 2.1.
