### ISSUE TITLE
PressableButtonCube position shift 

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#6242]
## Describe the bug

PressableButtonCube shifts positions in play mode.

## To reproduce

1. Navigate to PressableButtonExample
2. Run Scene

## Expected behavior

No position shift.

## Screenshots

[Video of Issue](https://youtu.be/qF4uD1nkm30)

<img width="1305" alt="PressableButtonIssue" src="https://user-images.githubusercontent.com/53493796/66440211-23de5000-e9e7-11e9-8c5d-5cd8e2592775.png">

## Your Setup (please complete the following information)

- Unity Version: 2018.4.7f1
- MRTK Version: v2.1

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by AdamMitchell-ms** [comment]
@CDiaz-MS, I have a fix for this locally.  Sending out a PR shortly.
