### ISSUE TITLE
Boundary System does not work correctly

### ISSUE THREAD

**Issue by KrasnovPavel** [microsoft/MixedRealityToolkit-Unity#6243]
I tried to visualize Boundaries but instead I get warning "Failed to calculate boundary bounds." and just Spatial Mesh.
 
![image](https://user-images.githubusercontent.com/5003831/66476557-93634680-ea9e-11e9-9456-0822ba237a9c.png)

```
Failed to calculate boundary bounds.
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.Boundary.MixedRealityBoundarySystem:CalculateBoundaryBounds() (at Assets/MixedRealityToolkit.Services/BoundarySystem/MixedRealityBoundarySystem.cs:932)
Microsoft.MixedReality.Toolkit.Boundary.MixedRealityBoundarySystem:Initialize() (at Assets/MixedRealityToolkit.Services/BoundarySystem/MixedRealityBoundarySystem.cs:45)
Microsoft.MixedReality.Toolkit.<>c:<InitializeAllServices>b__57_0(IMixedRealityService) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:865)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServices(IEnumerable`1, Action`1) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:972)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:953)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeAllServices() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:865)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:430)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeInstance() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:535)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean) (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:674)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Awake() (at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:568)
```

It happens in both editor and Hololens 1st gen.

## To reproduce

I encountered this in empty unity project with only MRTK.Foundation installed.
My settings:
![image](https://user-images.githubusercontent.com/5003831/66476765-1389ac00-ea9f-11e9-960a-6bb58238af7a.png)
![image](https://user-images.githubusercontent.com/5003831/66476804-27351280-ea9f-11e9-9ef1-b5c7856d1c76.png)
![image](https://user-images.githubusercontent.com/5003831/66476823-32883e00-ea9f-11e9-9039-9e16325e18ba.png)
![image](https://user-images.githubusercontent.com/5003831/66476840-3d42d300-ea9f-11e9-8929-c7f34c23348c.png)

## Expected behavior

Boundary Visualization

## Setup
I tested it with Unity 2018.4.4f1(.NET) and Unity 2019.1.3f(IL2CPP).
MRTK v2.0.0

## Target Platform

- Unity editor
- HoloLens 1st gen

**Comment by davidkline-ms** [comment]
@KrasnovPavel ,

The message your are receiving "Failed to calculate boundary bounds" indicates that either a boundary is not configured (vr device) or that the device does not support the concept of boundaries (Microsoft HoloLens).

The boundary system utilizes Unity's support for virtual reality devices and their configured boundaries (ex: tracing your play space via a Windows Mixed Reality immersive headset or an HTC Vive).

Spatial awareness is designed for devices such as the Microsoft HoloLens that have environmental sensors that provide mesh data matching the observed environment.

Hope this helps.

**Comment by KrasnovPavel** [comment]
@davidkline-ms , thank you for quick response. It looks like I misunderstood the documentation. I thought Boundary System is replacement for Spatial Understanding form HoloToolkit. 

Is there replacement for Spatial Understanding mechanism in MRTK like it was in [HoloToolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/case-study-expanding-the-spatial-mapping-capabilities-of-hololens)? 
I found [Scene Understanding](https://docs.microsoft.com/en-us/windows/mixed-reality/scene-understanding) but looks like Hololens (1st gen) goes not support it.

**Comment by davidkline-ms** [comment]
There currently is no replacement for Scene Understanding from the HoloToolkit. We are investigating the work required to update the required components and do not yet have a timeline for release.

**Comment by davidkline-ms** [comment]
Opened #6246 to track the request
