### ISSUE TITLE
[HTK Parity] Spatial Understanding

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#6246]
HoloToolkit shipped with the Spatial Understanding feature that has not yet been ported to MRTK v2.

This feature took the spatial mapping mesh and performed some analysis on the enviornment to create a play space similar to what is done in the Robo Raid application.

We have received numerous requests to port Spatial Understanding (ex: #6243)

**Comment by cre8ivepark** [comment]
Additional context: since MRTK v2 need to support HoloLens 1st Gen devices, Plane Finder/Spatial Understanding is needed. It will unblock the customers migrating from HTK to MRTK v2.

**Comment by JSWorkspace1** [comment]
Is this being considered for MRTK 2.2.0 ?

**Comment by MartinPyka** [comment]
would like to bring this up again. this is really missing in the MRTK for some types of applications

**Comment by westparezal2** [comment]
26.06.2020... still here.

**Comment by polar-kev** [comment]
We've opted not to do this. It's been replaced by scene understanding released in MRTK 2.6.
