### ISSUE TITLE
DLL Not Find，I try to Config DLL into X64 or X86,while ,this does not help

### ISSUE THREAD

**Issue by nrchuanqi** [Microsoft/MixedRealityToolkit-Unity#625]
DllNotFoundException: SpatialUnderstanding

**Comment by Sacristan** [comment]
Can You please provide more info. 

Can You find SpatialUnderstanding.dll in project ?

**Comment by jessemcculloch** [comment]
If you have added the DLL into your project, but it still can't be found when you run your app, try deleting the App folder (or whatever you build from unity to), and then restart unity and then do a fresh build.

**Comment by StephenHodgson** [comment]
@nrchuanqi did you resolve this issue?
