### ISSUE TITLE
Replace sphere in spatial awareness demo with button bar. Add functionality

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#6262]
The current spatial awareness demo scene does not use MRTK's button bar UI to control demo options.

In addition, the demo should illustrate more of the system functionality.

- [ ] Replace sphere functionality with button bar
    - [ ] Clear meshes
    - [ ] Visible / Occlusion materials
    - [ ] Change visible material
- [ ] Make the sphere movable to help illustrate occlusion, etc.
- [ ] Configurable use of mesh object vs on-device observer, dependent if running in editor or not

**Comment by Troy-Ferrell** [comment]
@davidkline-ms, added item to cover #6471
