### ISSUE TITLE
StabilizationPlaneModifier, when using gaze input, doesn't fallback to default distance if there is no gaze target

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#6263]
## Describe the bug

If the StablizationPlaneModifier's mode is set to "Gaze Mode", it doesn't correctly fallback to the default distance when the Gaze provider doesn't have a valid hit target.  This results in the stabilization plane to be placed on top of the main camera; this causes poor hologram stabilization.

The bug is in this function 

```
private bool TryGetGazeHitPosition(out Vector3 hitPosition)
{
    if (InputSystem.GazeProvider.Enabled)
    {
        hitPosition = InputSystem.GazeProvider.HitPosition;
        return true;
    }
    hitPosition = Vector3.zero;
    return false;
}
```

That is, InputSystem.GazeProvider.Enabled is true and InputSystem.GazeProvider.HitPosition is  zero if there is no hit target. 

## To reproduce

1. Apply StablizationPlaneModifier to your camera
2. Set StablizationPlaneModifier's mode to "Gaze mode"
3. Enable StablizationPlaneModifier's  gizmos
4. Turn off depth sharing (if playing on device)
5. Play in editor
6. Ensure gaze pointer has nothing in focus
7. (BUG) see stabilization plane is on top of the camera.  On device this cause horrible hologram stabilization.

## Expected behavior

When the gaze provider has no target, the stabilization plane should be set to the fallback distance; which by default is 2m in front of the main camera.

## Your Setup (please complete the following information)

- Unity Version 2018 - 2019
- MRTK Version v2.1

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

## Possible fix

Check if hit target is valid inside TryGetGazeHitPosition(...)

```
private bool TryGetGazeHitPosition(out Vector3 hitPosition)
{
    if (InputSystem.GazeProvider.Enabled && 
        InputSystem.GazeProvider.HitInfo.raycastValid == true)
    {
        hitPosition = InputSystem.GazeProvider.HitPosition;
        return true;
    }
    hitPosition = Vector3.zero;
    return false;
}
```

**Comment by davidkline-ms** [comment]
Thanks for the report @AMollis
