### ISSUE TITLE
Changing between scenes

### ISSUE THREAD

**Issue by psn2liz** [microsoft/MixedRealityToolkit-Unity#6266]
## Describe the bug
I am trying to change Scenes in Unity including the MRTK. The first Scenes includes a menu and the other ones are simple CAD objects. I want to switch from the menu to every other Scene and from there back to the menu. But when loading the new Scene the debug simply freezes. 

## Expected behavior
Im pretty new to the MRTK and Unity and Ive already seen that there has been a lot of discussion about this topic in the past. But i havent found any "How to" or anything like that. I would be thankful if you could write a short step by step guide how to manage to change scenes without crashing the whole programm. 

## Your Setup

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform

- HoloLens

**Comment by psn2liz** [comment]
@Railboy

**Comment by gilbdev** [comment]
rule n°1 : 
`MixedRealityToolkit` and `MixedRealityPlaySpace` should be unique and in a scene that is never unloaded.

This means all other scenes need to be loaded Additively ( `LoadSceneMode.Additive` )
By default in Unity, the LoadScene functions uses `LoadSceneMode.Single` which will unload all other scenes.

you can make your own scene management to quickly load additively (and save last loaded scene to unload) or see the Scene system profile that will handle that (and much more) here :
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SceneSystem/SceneSystemGettingStarted.html

**Comment by cre8ivepark** [comment]
@psn2liz Please take a look at the MRTK Examples Hub which uses MRTK's Scene System and Scene Transition Service (fade effect). It makes it very easy to manage multiple scenes.
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Documentation/README_ExampleHub.md

**Comment by davidkline-ms** [comment]
@Railboy / @cre8ivepark, sounds like a great opportunity for some new / enhanced documentation.

**Comment by psn2liz** [comment]
Thank you very much guys:)
