### ISSUE TITLE
Proper Video Streaming for HoloLens

### ISSUE THREAD

**Issue by travelhawk** [microsoft/MixedRealityToolkit-Unity#6267]
## Describe the problem

I was trying to build a video streaming solution for HoloLens 1. It works, but it turned out to be  hard to obtain a good performance. I couldn't process the mp4 stream properly, so I implemented a mjpeg solution which has just decent performance.

I would like to have a proper and high-performance way to video stream (including holograms) which you can integrate in your own apps.

## Describe the solution you'd like

The MixedRealityToolkit should provide an easy way to video stream. A challenge is to investigate the right solution checking  `MediaCapture`, WebRTC, different encodings, different network stacks and ease of use.

**Comment by Cameron-Micka** [comment]
@carmines do you have any suggestions?

**Comment by Troy-Ferrell** [comment]
@travelhawk, look at https://github.com/microsoft/MixedReality-WebRTC for webRTC support.

And a custom realtime streaming solution is here:
https://github.com/microsoft/MixedRealityCompanionKit/tree/master/RealtimeStreaming

The key if you do MediaFoundation yourself is to keep the render target that is decoded to YUV and not RGBA32 or something else. Turns out the texture format conversion when decoding to something non-YUV is prohibitively expensive.
https://docs.microsoft.com/en-us/windows/win32/medfound/recommended-8-bit-yuv-formats-for-video-rendering

**Comment by travelhawk** [comment]
@Troy-Ferrell The WebRTC support is still in Public Preview. Last time I tried, it was quite hard to get it working properly. Maybe it got better now.

The RealtimeStreaming solution is new to me, looks actually promising! But it looks like it is limited to .NET. What I need is to stream to a web application which doesn't use .NET or WPF.

What I tried is to use MediaCapture.PrepareLowLagRecordToStreamAsync with encoding profile mp4 and avi. The first option creates bytes which misses the initialization information (moov) which is needed to decode the mp4 stream. The second option kind of works, but the byte stream seems to be almost uncompressed why it is using a huge amount of bandwidth. Am I missing an option for MediaEncodingProfile here or how can I decode the byte stream?

**Comment by travelhawk** [comment]
> @carmines do you have any suggestions?

My suggestion is to do a MediaCapture and to provide functions to push to a rtmp (real time messaging protocol) server to broadcast the video stream. With ffmpeg this would be something like that: 

ffmpeg -i dummy.mp4 -f flv rtmp://example.com/live
ffmpeg -s 896x504 -r 20 -f rawvideo -pix_fmt nv12-i stdin -f flv rtmp://example.com/live

https://trac.ffmpeg.org/wiki/StreamingGuide
There is a ffmpeg library supported by the UWP: https://github.com/microsoft/FFmpegInterop

I'm just not how the decoding of the byte chunks work. Any suggestions?

**Comment by Troy-Ferrell** [comment]
So you want to stream MRC(?) from Hololens to a web application?

The RealtimeStreaming solution goes from endpoint to device while this solution below goes from HL device to PC endpoint (of course, it's not designed for web but also a UWP PC app endpoint)
https://github.com/microsoft/MixedRealityCompanionKit/tree/master/MixedRemoteViewCompositor

From what you describe, WebRTC seems like it would be your best bet. The two companion kit repos are posted for referenced and not supported. The WebRTC is better funded and uses a universal protocol standard. 

It is extremely unlikely that MRTK will provide anything of this nature in the near term, especially when there is the WebRTC repo.

**Comment by Troy-Ferrell** [comment]
https://twitter.com/mxdrealitydev/status/1184527229998501894?s=21

**Comment by travelhawk** [comment]
Thank you for your reply and the info! Exactly I want to stream MRC to web clients.

Looks like the first stable(?) release from the WebRTC repo is out. That's timely :)
I guess I will give it a try as the best fit at the moment. Thanks anyway.

**Comment by wiwei** [comment]
Closing this out, since it looks like the question has been addressed - definitely follow up on the WebRTC repo (i know those guys are fielding feedback and responding to questions)
