### ISSUE TITLE
Manipulation Handler ignores Colliders

### ISSUE THREAD

**Issue by JSWorkspace1** [microsoft/MixedRealityToolkit-Unity#6268]
## Describe the problem

When Moving Object with the Manipulation handler all colliders are ignored and you can move the object through others objects or clip them into the floor. 

## Describe the solution you'd like

I would like a option where the colliers are not ignored and the manipulated object is stopped when moved against an other object with a collider. 
Similar behavior can be observed in the the "lobby" of  Microsofts Mixed Reality Portal where furniture can be moved around but not into each other or the floor.

Additionally a constraints for the movement axis would be useful. for example only allow movement across the x- and z-Axis.

**Comment by genereddick** [comment]
For the constraints request, see #4154

**Comment by wiwei** [comment]
Closing this one out - this should make the next release!

**Comment by MenelvagorMilsom** [comment]
@davidkline-ms I tried to port this feature to `mrtk_development` this morning. It's not working as expected unfortunately. The fix must be dependent on some other change I made in `ObjectManipulator` (the state machine fix potentially). Is it alright if we merge this back with the other `ObjectManipulator` changes in 2.3?

**Comment by JSWorkspace1** [comment]
the ObjectManipulator  in MRTK 2.3.0  fulfills this Feature Request. Closing Issue.
