### ISSUE TITLE
No versioning on nuget feed binaries

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#6276]
## Describe the bug

The DLLs in the MRTK nuget feed all have versions set to 0.0.0.0.  The DLLs should have versioning applied.  Without this, it will be hard to debug issues (such as MRTK Editor Watson crashes) without having explicit knowledge of the MRTK version.

## To reproduce

Examine versions of the Nuget DLLs...they are all 0.0.0.0

## Expected behavior

Have a version that corresponds to the release

**Comment by davidkline-ms** [comment]
Nice catch @AMollis!

**Comment by andreiborodin** [comment]
So we will make this in by 2.2, unless there is an urgent request to have it in earlier.
