### ISSUE TITLE
Hand Rays do not seem to work in Solvers example scene

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#6279]
## Describe the problem
Currently, there is no easy way to make an object attached to the endpoint of the Hand Ray and make it placed on a surface with the surface normal aligned. 

## Describe the solution you'd like
Adding a new option 'Hand Ray' to Surface Magnetism Solver.

**Comment by Troy-Ferrell** [comment]
@cre8ivepark , there is the hand target option in the tracked reference type on the SolverHandler

![image](https://user-images.githubusercontent.com/25975362/66787198-a2c80280-ee97-11e9-9525-6620f1d9f025.png)

It looks like hand tracking broke though in the solvers example scene. I'm guessing it is an issue with input simulation and the scene still works on device (although I haven't just now tested on device yet)

**Comment by Troy-Ferrell** [comment]
oh well duh, the forward is up flowing through the hand
![image](https://user-images.githubusercontent.com/25975362/66880056-f577ec00-ef75-11e9-9e0b-a715d7103dc2.png)
