### ISSUE TITLE
Use MRTK with ZED cameras

### ISSUE THREAD

**Issue by flaming910** [microsoft/MixedRealityToolkit-Unity#6282]
So I'm looking to use some form of AR/MR SDK to work with a ZED camera as the input and was wondering if that is possible with the MRTK for Unity or not?

**Comment by davidkline-ms** [comment]
We have not performed any testing with Zed cameras. If there is Unity support, it should be reasonably straight forward to adapt MRTK to support these devices via the [CameraSystem](https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk_release/Assets/MixedRealityToolkit.Services/CameraSystem).

**Comment by cpaganucci** [comment]
A little late, but for anyone else looking into this, I got this in working in the sample scene by doing the following:

- Disable the camera system (uncheck Enable Camera System in the MRTK component)
- Remove the Main Camera game object
- Add the ZED_Rig_Stereo prefab under MixedRealityPlayspace
- Change the Tag of Left_eye camera to MainCamera 
- Change the Stereo Rendering Mode to Multipass in XR Settings

Good luck!
