### ISSUE TITLE
Solving 'self overlap' with transparent 3D objects

### ISSUE THREAD

**Issue by jwittner** [microsoft/MixedRealityToolkit-Unity#6285]
## Describe the problem

Hey all, when rendering transparent 3D geometry we often get the issue of 'self overlap' as seen in the below image. 

![image](https://user-images.githubusercontent.com/12958442/66781037-25949180-ee87-11e9-8613-9ec4886b6128.png)

## Describe the solution you'd like

To remedy this for a recent project we made a modified version of the MRTK/Standard shader that included a depth only pass before writing colors. 

![image](https://user-images.githubusercontent.com/12958442/66781169-7310fe80-ee87-11e9-87fb-bebe859a15af.png)

## Describe alternatives you've considered

We did a quick test of this functionality by using two materials on one MeshRenderer, where the first was configured to only write to the Alpha (ColorMask doesn't currently support specificying 0 or no channels). This however was a little less performant than one material with two passes.

![image](https://user-images.githubusercontent.com/12958442/66781274-b7040380-ee87-11e9-90d7-56b000c36bc5.png)

![image](https://user-images.githubusercontent.com/12958442/66781355-e581de80-ee87-11e9-8359-51742488188a.png)

Unfortunately you cannot control passes externally from a shader so we can't make this a flag within the current Standard shader (open to work arounds if there are any!).

## Additional context

I'm interested in if this would be a useful change to propagate back to the MRTK and, if so, how everyone would feel about moving many of the functions in the standard shader out to cginc files so that both shaders/passes can be built on the same code?

**Comment by Cameron-Micka** [comment]
Thank you documenting this issue @jwittner, this has been un-officially raised by a few folks. It would be nice to add a depth pre-pass to the default MRTK/Standard shader and have the pass disabled by default (via https://docs.unity3d.com/ScriptReference/Material.SetShaderPassEnabled.html?), but I'm not sure how to have it disabled by default on existing materials?

I like your alternative idea of moving a lot of the shader code into an include and maintaining multiple variants. The shader has grown enough that it is probably time for that.

**Comment by jwittner** [comment]
Really unfortunate that you can't control the default for any given pass. Should we make a feature request of Unity?

**Comment by Cameron-Micka** [comment]
I like that idea! Could you file a Unity bug?

**Comment by Zee2** [comment]
@Cameron-Micka I've actually run into this recently, and had to write my own depth prepass shader, haha. Pinging you again to see if you want to add a depth prepass option to your ubershader.

Closing here. @Cameron-Micka feel free to port this issue to the MRGT repo.
