### ISSUE TITLE
HoloLens 1 and 2 support multi-thread？

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#6288]
HoloLens 1 and 2 support multi-thread？
1.UI thread is stoped while Loading data or some Prefabs (hololens 1) .
2.I cannot see anything or low frame rate in hololens 1 while runing MRTK demos once in a while.

**Comment by davidkline-ms** [comment]
@IfnoLee,

Yes, you can write multithreaded applications for HoloLens devices. Please be aware that Unity objects are only supported on the UI thread.

If your application requires processes that may take longer than a single frame as well as Unity objec interaction, I recommend implementing a Unity [coroutine](https://docs.unity3d.com/Manual/Coroutines.html).

Hope this helps!

**Comment by IfnoLee** [comment]
> @IfnoLee,
> 
> Yes, you can write multithreaded applications for HoloLens devices. Please be aware that Unity objects are only supported on the UI thread.
> 
> If your application requires processes that may take longer than a single frame as well as Unity objec interaction, I recommend implementing a Unity [coroutine](https://docs.unity3d.com/Manual/Coroutines.html).
> 
> Hope this helps!

Thank you very much!
