### ISSUE TITLE
PlaneFinding.dll is missing for Plugins\WSA\x64

### ISSUE THREAD

**Issue by timGerken** [Microsoft/MixedRealityToolkit-Unity#629]
Under `Assets\HoloToolkit\SpatialMapping`, there are two versions of `PlaneFinding.dll` for x86 (one in `Plugins\WSA\x86` and the other in `Plugins\x86`.) There is, however, only one version of `PlaneFinding.dll` for x64, found in `Plugins\x64`.

I think this causes the VisualStudio side of the build to fail because it can't find the dll it is looking for.
> Could not copy the file `"D:\Project\App\Project\Plugins\x64\PlaneFinding.dll"` because it was not found.

**Comment by StephenHodgson** [comment]
I'm pretty sure that x64 is unsupported on HoloLens

**Comment by StephenHodgson** [comment]
Which scene are you building for?

**Comment by StephenHodgson** [comment]
Related to https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/746

**Comment by StephenHodgson** [comment]
Closed By https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/dc4375db8643632565fa21c4d21893d7f098a98d
