### ISSUE TITLE
Editor Facades to group data providers by their registrar

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#6295]
## Describe the problem

The service facade system creates GameObjects for both services and dataproviders. For the data providers that are part of a specific core service (which is Input  system and Spatial Awareness system), the dataprovider gameobjects should be children of their respective service facade gameobjects. 

![image](https://user-images.githubusercontent.com/25975362/66878423-a7abb580-ef6e-11e9-9932-e6c23002635b.png)

## Describe the solution you'd like

Dataprovider service facades should be under their parents so it is more logically grouped

**Comment by Troy-Ferrell** [comment]
@Railboy, FYI

**Comment by davidkline-ms** [comment]
Facades have been deprecated (removed?) since 2.4/2.5. We can safely close this.
