### ISSUE TITLE
This logic will order not found paths ("False") before found paths ("True")

### ISSUE THREAD

**Issue by genbod** [microsoft/MixedRealityToolkit-Unity#6297]
## Describe the bug

The comment in UwpAppxBuildTools.cs states that the preferences for msbuild versions is enterprise, pro, then community, but this logic will actually order those paths in reverse.  
string bestPath = paths.OrderBy(p => p.ToLower().Contains("enterprise"))
                                .ThenBy(p => p.ToLower().Contains("professional"))
                                .ThenBy(p => p.ToLower().Contains("community")).First();

## To reproduce

1. Install community and enterprise versions of msbuild
2. Run build command
3. check to see which version is used

## Expected behavior

The preference should match the documentation

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

## Additional context

The fix is to use OrderByDescending, ThenByDescending, that way found paths ("True") will be sorted before not found paths ("False") and the correct preference will be chosen.

**Comment by davidkline-ms** [comment]
Thanks for the report. We will add this to the work we plan to do on the build tools for v2.2.0

**Comment by keveleigh** [comment]
Fixed via #6477
