### ISSUE TITLE
can not connect internet with websocket

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#6298]
## Describe the bug
It is ok while run my program in unity editor,  but it seem can not connect internet after deploy to hololens.
It is no errors while in unity editor and visual studio while deploying to hololen . 
I donot know the question.
The output is "已加载“C:\Windows\System32\Windows.Networking.Connectivity.dll”。无法查找或打开 PDB 文件。" while program is debuging.

**Or my way is wrong of using websocket in hololens.**

## Screenshots
![image](https://user-images.githubusercontent.com/38685433/66909872-19076900-f040-11e9-8ff4-d6d1c5b14583.png)
![image](https://user-images.githubusercontent.com/38685433/66910871-fe35f400-f041-11e9-846b-c3abd22e1f41.png)

**below two images is debuging output.**
![image](https://user-images.githubusercontent.com/38685433/66910120-8a471c00-f040-11e9-848e-69cba097366e.png)
![image](https://user-images.githubusercontent.com/38685433/66910217-bc587e00-f040-11e9-8edb-09b2ea3aadaf.png)

## Your Setup (please complete the following information)

- Unity Version [e.g. 2019.2.6.f1]
- MRTK Version [e.g. v2.1]

## Target Platform (please complete the following information)

- HoloLens

**Comment by Troy-Ferrell** [comment]
@IfnoLee, thanks for filing an issue. But it doesn't seem like you are using any MRTK component. If you have an issue with the HoloLens platform, you should reach out in that community. It'll be easier and faster for you to get an answer to resolve any platform-specific issues (irrelevant of MRTK)

https://support.microsoft.com/en-us/hub/4338666/hololens-help

Can you also provide more details about the hololens? Is it 1 or 2? What OS version do you have on there?

**Comment by IfnoLee** [comment]
> @IfnoLee, thanks for filing an issue. But it doesn't seem like you are using any MRTK component. If you have an issue with the HoloLens platform, you should reach out in that community. It'll be easier and faster for you to get an answer to resolve any platform-specific issues (irrelevant of MRTK)
> 
> https://support.microsoft.com/en-us/hub/4338666/hololens-help
> 
> Can you also provide more details about the hololens? Is it 1 or 2? What OS version do you have on there?

The WebSocket SDK is ok ,but the token is not be parsed because of  Newtonsoft.Json is not work in UWP . Everything is ok after I replace Newtonsoft.Json by [Json.Net.Unity3D](https://github.com/SaladLab/Json.Net.Unity3D).

**Comment by dahaideyu** [comment]
I have same issue when I had used Newtonsoft.Json.  I hope that Microsoft office don't close bug. I looking forward to  fixing this bug for MRTK.

**Comment by dahaideyu** [comment]
> > @IfnoLee, thanks for filing an issue. But it doesn't seem like you are using any MRTK component. If you have an issue with the HoloLens platform, you should reach out in that community. It'll be easier and faster for you to get an answer to resolve any platform-specific issues (irrelevant of MRTK)
> > https://support.microsoft.com/en-us/hub/4338666/hololens-help
> > Can you also provide more details about the hololens? Is it 1 or 2? What OS version do you have on there?
> 
> The WebSocket SDK is ok ,but the token is not be parsed because of Newtonsoft.Json is not work in UWP . Everything is ok after I replace Newtonsoft.Json by [Json.Net.Unity3D](https://github.com/SaladLab/Json.Net.Unity3D).

this version is old ? author  think about update Json.Net.Unity3D?
