### ISSUE TITLE
I just upgraded to the latest mrtk_release branch and now I get FileNotFoundException: Unable to find 'Assembly-CSharp.csproj' file. error every time I try to build the project.

### ISSUE THREAD

**Issue by genbod** [microsoft/MixedRealityToolkit-Unity#6308]
## Describe the bug

Pushing the "Build" button in the build window ends with this error: FileNotFoundException: Unable to find 'Assembly-CSharp.csproj' file.

And not the "Done" window.

## To reproduce

1. checkout mrtk_release branch
2. click on Build button in build window

## Expected behavior

No errors.

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.4.11f1]
- MRTK Version [e.g. v2.1]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by SimonDarksideJ** [comment]
I'd recommend closing Unity and deleting the Library / Temp folders as well as any existing .csproj/.sln files then restart Unity

**Comment by genbod** [comment]
I tried that.  It doesn't look like any of my .csproj files are being copied to the output directory. The offending code is "UpdateAssemblyCSharpProject".  As far as I can tell that function just updates the AllowUnsafeCode option for experimental support.  Considering there are valid configurations that don't end up copying Asssembly-CSharp.csproj into the output folder, it probably isn't good for this code to fail and stop the post build steps if the file is not there.  I recommend either handling the missing file more gracefully, or allowing the user to disable this code path  along with the AllowUnsafeCode option.

**Comment by keveleigh** [comment]
@Weasy666, this sounds like the code you added?

**Comment by SimonDarksideJ** [comment]
Right, not sure what is going on here but I'm unable to replicate this issue:
* Tried building from mrtk_release (as described) - no issue
* Tried building from mrtk_development - no issue
* Tried building using the assets - no issue.

Tested on both Windows Standalone and UWP with 2018.4.11.

Also curious from your response, the MRTK isn't responsible for copying assemblies/projects or even modifying them.

Can you replicate the issue in a clean project and if you do, please update your replication steps?

**Comment by julianloehr-kg** [comment]
We are running into the same error with the latest MRTK (2.1.0) on Unity 2019.1.14.
We are using the IL2CPP scripting backend, which does not copy over any ".csproj" files when building the Unity Player.

**Comment by Weasy666** [comment]
Hm... @genbod are you using the IL2CPP backend? AllowUnsafeCode is only working with C# backend. So the compile backend should be checked before calling `UwpAppxBuildTools.UpdateAssemblyCSharpProject`

**Comment by Weasy666** [comment]
As a workaround for now you can wrap this line into an `if (EditorUserBuildSettings.wsaGenerateReferenceProjects)`
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/2c711ab4d9f059fa0b12761a10188a051c7785b4/Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs#L89
That should make it possible to compile an IL2CPP project without an error.

Question is how to handle it from here on. I think wrapping this in the if for Unity 2018 projects is the way to go, but for 2019 projects i think we need to wrap the complete code path in a preprocessor directive, because afaik IL2CPP is the only backend in Unity 2019 and it will never generate an AssemblyCSharp file.

**Comment by genbod** [comment]
@Weasy666 yes, I am using the IL2CPP backend.

**Comment by xwipeoutx** [comment]
I just ran into this on 2019.2.0f1 (IL2CPP) - I'm using the 2.1.0 `.unitypackage` from the repo here.

Commented out that call ` UwpAppxBuildTools.UpdateAssemblyCSharpProject(uwpBuildInfo);` got me going again easily enough.

**Comment by keveleigh** [comment]
A fix for this is in review at https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6488.

**Comment by keveleigh** [comment]
This should be fixed via #6488 and the upcoming 2.2 release. Thanks for the report!
