### ISSUE TITLE
Head Gaze cursor do not reappear after hand cursor got disabled

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#6320]
## Describe the bug
At startup, default gaze cursor is visible.
When  a hand is detected, the gaze cursor disappeared and the hand cursor is visible.
When the hand is not detected anymore, the head gaze cursor should be visible again just like at startup, but it stays inactive.

## To reproduce

1. Launch any example (in the gif it's HandMenuExamples)
2. Click Play in Unity and observe that a cursor is visible
3. pop a hand and observe that the hand cursor is visible (but the head gaze is not anymore)
so far, all good ;)
4. unpop/hide the hand
=> no cursor is displayed anymore

## Expected behavior
when no hand is detected, the default head gaze cursor should be displayed just like at startup

## Screenshots
![pointer_disappear](https://user-images.githubusercontent.com/49415246/67093091-1f692280-f1b1-11e9-8af5-c72f45646492.gif)

## Your Setup (please complete the following information)

- Unity Version [2018.4.9f1]
- MRTK Version [v2.1]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by gilbdev** [comment]
@julenka, it seems you amde some changes back in amy to fix some hololen 1 issue  (in FocusProvider.ReconcilePointers and GazePointerVisibilityStateMachine.UpdateStateHeadGaze).

the state for the defaultgaze goes from Initial to Inactive once a hand is visible, but stays inactive forever after that (because numFarPointersWithoutCursorActive stays at 0)

looking at the StateEyeGaze above, it seems it falls back correctly to active when no other pointer is active, but it doesn't work that way for StateHeadGaze, can you explain why ? (jsut want to be sure it's a bug and not a wanted behavior)

**Comment by cre8ivepark** [comment]
Hi @gilbdev This is correct behavior matching the shell. You need to explicitly say 'Select' to bring the gaze cursor back. (works in the editor too)

**Comment by gilbdev** [comment]
hmm 3 points in this current  behavior that i don't like : 
- initial state (cursor is visible) is different than 'idle state' (cursor not visible after showing and hiding hands)
- only way to display it is with voice command, no alternative
- when the eye tracking is supported, the behavior is different (default cursor visible as long as no hand is detected)

**Comment by julenka** [comment]
Hi @gilbdev, I believe you can actually force the gaze cursor to be always on by setting the PointerBehavior using `PointerUtils.SetGazePointerBehavior`. Please see #5920 for more details. You can learn more at [this documentation page](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Architecture/InputSystem/ControllersPointersAndFocus.html#how-to-disable-pointers)

**Comment by julenka** [comment]
Closing as this is the expected default behavior.

**Comment by gilbdev** [comment]
i don't want to have it AlwaysOn, i would like :
**having the gaze pointer visible when no hand is detected**

currently `PointerBehavior.Default` behaves like :
- **gaze pointer hides as soon as a hand is detected**

if this is the wanted behavior fine, but imo, **to be consistent, the pointer should not be visible from the start**.

this still won't fit my use case though:
- i want the gaze pointer visible when no hand is detected, to be able to dwell buttons (without having to say "select", which would not correspond to the wanted action [enabling dwell interaction] and we don't want to force users to use voice commands.

**Comment by gilbdev** [comment]
ok,
dig into it again :
apparently this is working as expected after all.

what's buggy is that in **the input simulation profile, the `Simulate Eye position` is disabled by default** (even for the DefaultHololens2InputSystemProfile) so without any eye data, the poitner is disabled, and the focusprovider will keep fallback to HeadGaze and be disabled.

so, this should be fin in the real hololens2, but could be improve in unity simulation to enable the eye tracking by default for the hololens2 profile.

question in suspend for devices that have hand tracking without eye tracking (if it exists..)

**Comment by julenka** [comment]
Hi, thanks so much for your contribution and for contributing to MRTK! It's great that you were able to figure out a behavior that works for you. 

Regarding this:

>  I want the gaze pointer visible when no hand is detected, to be able to dwell buttons (without having to say "select", which would not correspond to the wanted action [enabling dwell interaction] and we don't want to force users to use voice commands.

By default the behaviour of MRTK is to match the shell behavior in both VR and HoloLens 2, which is to require the "select" keyword. We keep this behavior in the defaults so that we are consistent with the system. However, it's great you're able to modify the profiles to customize this.

You can also accomplish the behavior you want by forcing the gaze pointer on with the following code;

`PointerUtils.SetGazePointerBehavior(PointerBehavior.AlwaysOn)`

**Comment by keveleigh** [comment]
Since #6393 was reverted via #6516, I'm reopening this.

**Comment by keveleigh** [comment]
Or, I guess...this was closed originally as "by-design"?
