### ISSUE TITLE
MRTK inspector renders incorrectly on Unity 2019.3

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#6330]
## Describe the bug

MRTK inspector renders incorrectly on Unity 2019.3:

![image](https://user-images.githubusercontent.com/3580640/67132240-f77fbc00-f1bc-11e9-9ed1-48a05f87f8b4.png)

## Your Setup (please complete the following information)

- Unity Version Unity 2019.3.0b7
- MRTK Version mrtk_dev

**Comment by Troy-Ferrell** [comment]
Wow lol @keveleigh, we might want to wait until 2019.3 gets out of beta

**Comment by keveleigh** [comment]
@Troy-Ferrell No disagreement here haha! Figured I'd log in case it ends up persisting past their beta :)

**Comment by Troy-Ferrell** [comment]
Yea leave it for tracking

**Comment by Troy-Ferrell** [comment]
I believe this is fixed by Unity in latest 2019.3 (Note I used #7193 as starting point)

![image](https://user-images.githubusercontent.com/25975362/73481476-bfa61a00-4350-11ea-813c-cfc3eaab856a.png)

**Comment by keveleigh** [comment]
Yep! I think it was fixed ~2019.3.0f4. Thanks for closing this out!

**Comment by keveleigh** [comment]
One outstanding graphical error I've seen though is the controller mapping profile.
