### ISSUE TITLE
OnInputDown not trigger when attach to the main camera

### ISSUE THREAD

**Issue by Kent1LG** [microsoft/MixedRealityToolkit-Unity#6331]
## Describe the bug

With the MRTK 2 RC2 i use to create IMixedRealityInputHandler script and attach it to the main camera. By this way i can trigger every InputDown.
When i do it with the MRTK 2.1 it's not working.

## To reproduce

1 : Create a scipt using "IMixedRealityInputHandler".
2 : Configure the "OnInputUp"(Only on HoloLens 2 i guess) and "OnInputDown"
3 : Check if it trigger the AirTap 

## Expected behavior

Triggered every "OnInputDown"

## Your Setup (please complete the following information)

- Unity Version 2018.4.9f1
- MRTK V2.1 (install by nugget)

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by Troy-Ferrell** [comment]
@Kent1LG, you should look at registering for global input handler. See our documentation for how to achieve this

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/InputEvents.html#register-for-global-input-events
