### ISSUE TITLE
Example Hub 2.1.0.0 Has dLSR Issues on Text

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedRealityToolkit-Unity#6335]
## Describe the bug

When installing the Example Hub linked in the 2.1.0 release (https://github.com/microsoft/MixedRealityToolkit-Unity/releases/download/v2.1.0/MRTKExamplesHub2.1.0.0_ARM_HoloLens2.zip) on HoloLens 2 text within a few scenes is not stabilized because it is not writing depth. 

## To reproduce

1. Open the Examples Hub 2.1.0 on a HoloLens 2
2. Select the Hand Interactions Example scene.
3. Examine the text.

## Expected behavior

Text is stable.

## Screenshots

![20191021_135638_HoloLens](https://user-images.githubusercontent.com/13305729/67242706-ec21d000-f40a-11e9-849d-de274166be1a.jpg)

## Your Setup

- MRTK Version 2.1.0

## Target Platform

- HoloLens 2

**Comment by keveleigh** [comment]
I think this was fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6474
