### ISSUE TITLE
Gestures Documentation needs to be updated

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#6337]
## Describe the Issue
The Gestures page does not communicate it's feature well to new users

Things not clear
- What is a hold, navigation, or manipulation gesture type?
- For gestures one will generally more expect how do I recognize a bloom, or an L-shaped hand or a swipe
- Not clear how one should configure the Gestures profile
- Gesture events doesn't provide code snippets on how to get started
- Order of Events is also very confusing. Order of events for what?

## Feature Area
What's incorrect? What's missing?

## Existing Doc Link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Gestures.html

**Comment by keveleigh** [comment]
I'm working on gestures for XR SDK, so I can work on this too
