### ISSUE TITLE
What's new and change tracking for 2.2.0

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#6349]
This issue is for tracking changes and new features in MRTK v2.2.0.

**New**
- AR Foundation support [Experimental]
    - Camera settings provider

- Directional Indicator Solver

- Enhanced MRC support [Experimental]

![image](https://user-images.githubusercontent.com/13281406/69677386-ae424800-1057-11ea-8721-70615513294d.png)

- [Ability to search mrtk profiles for keywords](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6183)
![config_search_2](https://user-images.githubusercontent.com/168492/69468019-6497eb80-0d3f-11ea-8568-874db66c0099.gif)

- [New audio clips for HoloLens 2 style Bounding Box](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6465)
- [Surface Magnetism Solver + Hand Ray Example scene](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6280)
![mrtk_surfacemagnetism](https://user-images.githubusercontent.com/13754172/69566003-f6377100-0f6a-11ea-8963-a6ef93554e43.gif)

- [Experimental - Pulse shaders for spatial mesh and hand mesh visualization](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6486)
![MRTK_SpatialMesh_Pulse](https://user-images.githubusercontent.com/13754172/68261851-3489e200-fff6-11e9-9f6c-5574a7dd8db7.gif)
![MRTK_HandMesh_Pulse2](https://user-images.githubusercontent.com/13754172/68262035-e4f7e600-fff6-11e9-9858-796afd1cabc5.gif)

- [Experimental - Scrolling Object Collection](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6001)

  ![MRTK_ScrollingList3](https://user-images.githubusercontent.com/13754172/65283862-f3dd1480-daec-11e9-8868-671106c6732b.gif)

- MSBuild for Unity (installed via MRTK configuration dialog, used to acquire MRTK NuGet dependencies)

- Support for HoloLens2 articulated hand and eye remoting (requires use of MSBuild for Unity)

- Windows Mixed Reality camera settings provider
    - Can specify HoloLens 2 reprojection mode|

    ![image](https://user-images.githubusercontent.com/13281406/69587130-8f7d7c00-0f99-11ea-8c8d-20117eb22c3b.png)

**Changed**
- Camera system now supports settings providers (allows custom camera configuration based on build target, ex: Android).
- Camera system falls back to v2.1.0 behavior if no supported settings provider can be loaded
- InteractableToggleCollection refactor - added custom inspector 
- [GridObjectCollection now supports aligning content left/center/right and top/middle/bottom](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6550)

  ![layout](https://user-images.githubusercontent.com/168492/69363541-83b25280-0c45-11ea-91af-b2b6d9e5b6da.gif)
- [Cursor resizing based on distance and angular scale](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6310)
- [Fingertip cursor translation/alignment](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6479)
- [[Shell Parity] Added icon lift on focus to PressableButtonHoloLens2 button](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6407)

- GridObjectCollection asset version has been upgraded to allow for some fixes. All components with layout ColumnsThenRows will be upgraded automatically, keep eye out for logs and remember to check and save assets.

**Known Issues**
- 2018: If building UWP with the .NET backend, AND including AR Foundation packages, selecting "Unity C# Projects" in the build settings window is not supported. (Caused by ar foundation using unsupported APIs)
- see #6576
- If importing Providers.UnityAR, you may see
Assembly has reference to non-existent assembly 'Unity.XR.ARFoundation'. Install ARFoundation and ARCore/ARKit to resolv, or remove the MixedRealityToolkit,Staging folder from the project.
- Enhanced MRC support is off by default as it is not supported on Unity 2019.1 and 2019.2. Clone the Windows Mixed Reality camera settings profile to enable if using Unity 2018.4 or 2019.3.
- MRTK Configuration dialog may display multiple times at load (ex: if applying the Enable MSBuild for Unity option) as Unity appears to be reloading the project when packages are installed

**Comment by Troy-Ferrell** [comment]
New 

Depth Buffer Viewer in Editor
![depth-buffer-example](https://user-images.githubusercontent.com/25975362/67987843-aa074400-fbeb-11e9-9b40-f9158f1dc40f.gif)
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6446

Project Configuration Window
![image](https://user-images.githubusercontent.com/25975362/66785582-8a091e00-ee92-11e9-89ae-6407d8baaaaa.png)
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6286

**Comment by cre8ivepark** [comment]
Added some UX updates to David's comment.
