### ISSUE TITLE
Example SharingwithUnet not working with Unity 5.6

### ISSUE THREAD

**Issue by AndrejRu** [Microsoft/MixedRealityToolkit-Unity#635]
I tried with 5.5.2f which worked fine for me. After Upgrading to 5.6 the Client gets the Anchor ID but the Anchor dont sync.

**Comment by StephenHodgson** [comment]
Thanks for the report.  Are you using visual studio 2017 as well?

**Comment by AndrejRu** [comment]
Yes. Done a fresh install of vs2017 and unity 5.6.

**Comment by Ziugy** [comment]
Just to check, have you looked through #563 for further debugging of this issue?

**Comment by AndrejRu** [comment]
I cant debug because of #623

**Comment by StephenHodgson** [comment]
Any update to this?

**Comment by StephenHodgson** [comment]
Please reopen a new issue for 2017 if issue persists.

**Comment by AndrejRu** [comment]
Sorry about the late Feedback. It is working now with 2017.1.0f3
