### ISSUE TITLE
AsyncCoroutineRunner is invoking DontDestroyOnLoad in editor mode

### ISSUE THREAD

**Issue by julianloehr-kg** [microsoft/MixedRealityToolkit-Unity#6353]
## Describe the bug

When trying to deploy an app package within the build window by clicking on install, Unity throws the error 

`
InvalidOperationException: The following game object is invoking the DontDestroyOnLoad method: AsyncCoroutineRunner. Notice that DontDestroyOnLoad can only be used in play mode and, as such, cannot be part of an editor script.
`

Deploying is therefore currently broken. The offending line is https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit/Utilities/Async/Internal/AsyncCoroutineRunner.cs#L96

There has been a `UNITY_EDITOR` preprocessor around it, though it was removed in #5951 by @wiwei.

## To reproduce

1. Open any MRTK project
2. Build an app package
3. Try to deploy it to a device using the Build Window Deploy Options tab

## Your Setup (please complete the following information)

- Unity 2019.1.14
- MRTK 2.1.0

## Target Platform (please complete the following information)

- HoloLens

**Comment by keveleigh** [comment]
fixed via #6363
