### ISSUE TITLE
Clipping primitive doesn't work if Renderer has more than one material 

### ISSUE THREAD

**Issue by AntonioFlumen** [microsoft/MixedRealityToolkit-Unity#6354]
## Describe the bug
When you associate a Renderer component to a ClippingBox (or any subclass of ClippingPrimitive), if the Renderer has two materials, the second material will not be clipped.

## To reproduce

1. Add to the scene a GameObject 'A' containing a MeshRenderer component with two materials;
2. Add to the scene a GameObject 'B' containing a ClippingBox component;
3. Add The MeshRenderer of 'A' as element of  ClippingBox.Renderers array of 'B';
4. Play game is not necessary;
4. Move 'A' inside and outside 'B' cube.

## Expected behavior

the second material of MeshRenderer component will not be clipped.

## Screenshots

No Screenshot

## Your Setup (please complete the following information)

- Unity Version 2018.4.9f1
- MRTK Version v2.0 and v2.1

## Target Platform (please complete the following information)

- HoloLens

**Comment by keveleigh** [comment]
@Cameron-Micka?

**Comment by Cameron-Micka** [comment]
Hi @AntonioFlumen, thank you for reporting this issue. This bug is fixed in this pull request: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6165 and will be in the _next_ MRTK release.
