### ISSUE TITLE
[Android] Shader error in 'Mixed Reality Toolkit/Standard': Program 'frag', error X8000: D3D11 Internal Compiler Error: Invalid Bytecode

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#6359]
## Describe the bug
The first time i compile the MRTK Standard shader for Android, i see a collection (30) of errors that fith the following pattern.  Each one specifies a different opcode, but they all look about the same

```
Shader error in 'Mixed Reality Toolkit/Standard': Program 'frag', error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Incompatible min precision type for operand #1 of opcode #29 (counts are 1-based). Expected int or uint. (on gles)

Compiling Vertex program with UNITY_PASS_FORWARDBASE _CLIPPING_PLANE _DISABLE_ALBEDO_MAP _ROUND_CORNERS _IGNORE_Z_SCALE
Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER SHADER_API_MOBILE UNITY_HARDWARE_TIER1 UNITY_COLORSPACE_GAMMA UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_DLDR_ENCODING
```

This is when the following Android player settings are configured. Not sure if they are part of the issue:

- Auto Graphics API
- Minimum API Level: 24

Unity 2018.4.11f1
MRTK development branch

**Comment by Alexees** [comment]
Ah, that's reported already, just having this too

**Comment by Alexees** [comment]
I found this as a very similar cause for the very same error:
https://fogbugz.unity3d.com/default.asp?934464_sjh4cs4ok77ne0cj&_ga=2.227501789.1300041981.1572856207-2072500192.1561120911

**Comment by SimonDarksideJ** [comment]
Try lowering your Graphics Quality on the Camera Settings to Medium or lower, as depending on the device .

**Comment by davidkline-ms** [comment]
> I found this as a very similar cause for the very same error:

Thanks @Alexees!

**Comment by Kjelll** [comment]
I unchecked "strip engine code" in the project settings and i could build without issues now. (No idea if the .apk still works on a device though)

**Comment by iamblesson** [comment]
Hi I am still facing this issue in Unity 2019.4.5
Auto Graphics API
Minimum API Level: 24

Platform - Android 
Mixed Reality Toolkit v2.4.0

Can someone provide a solution for this?

**Comment by SimonDarksideJ** [comment]
@davidkline-ms can you reopen this issue, I don't seem to have that access anymore

**Comment by provencher** [comment]
I can also attest to still seeing this error when working with MRTK-Quest.

**Comment by Cameron-Micka** [comment]
It might be best to report this to Unity since the error is stemming from the D3D compiler: `error X8000: D3D11 Internal Compiler Error`

I have a few ideas on how we might be able to "side step" the issues. But, it would be good to know the root cause rather than having to guess and check.

@davidkline-ms do you have time to report this to Unity? If not, I can try to in the coming weeks.

**Comment by provencher** [comment]
It seems that if replace all fixed<X> and half<X> with float<X> the error is no longer present.

**Comment by Cameron-Micka** [comment]
Thank you @provencher! I almost changed the default precision to full a few changes back (since the Adreno 630 in HoloLens 2 only supports full precisions scalers). But, I was worried this might hurt performance on other Android/iOS platforms.

But, since it seems Android building is broken as is. This might be a worthy change to make since most mobile AR devices have pretty modern GPUs.

Does anyone have any objections to changing everything to full precision?

**Comment by provencher** [comment]
I made the change on my Standard Shader mirror for those who don't want to wait for this to land in the newest MRTK release.
https://github.com/provencher/MRTK-StandardShader/commit/fe4f61f77ed423a3ed025d10a66adefe981edf5e

**Comment by Acimaz** [comment]
I've found another way to fix this by using the URP and upgrading all shaders using the provided mrtk upgrade tool: https://github.com/provencher/MRTK-Quest/issues/84

**Comment by Cameron-Micka** [comment]
A fix for most of these errors is coming soon: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10041 

One last error remains which I will reach out to Unity about (you can see the PR details for more info.)
