### ISSUE TITLE
Investigate CI pipeline improvements

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#6383]
## Describe the problem

Our CI is currently running ~90 minutes long. It'd be great if we could investigate parallelizing some of the jobs or splitting tasks up to take advantage of the general Azure pipelines machines in addition to our private Unity machines.

## Describe the solution you'd like

https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages

## Describe alternatives you've considered

Currently, we've increased the timeout to 120 minutes instead of 90. #6382

**Comment by wiwei** [comment]
Closing out some old issues, things are faster now!
