### ISSUE TITLE
Examples hub scene fails to load with error "Can't load invalid scene LoadHubOnStartup"

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6384]
## Overview
The examples hub scene fails to load the main menu scene, throwing this error:

Can't load invalid scene LoadHubOnStartup - make sure the scene name is spelled correctly and that you have added the scene to your MixedRealitySceneSystem profile's content scenes array.

It seems this is caused by the script LoadHubOnStartup

## Steps to reproduce
In latest mrtk_development...

1. Open MRTKExamplesHub scene
2. Verify the MRTK ExamplesHub is the first scene in Build settings, as specified by [this documentation](https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.1.0/Documentation/README_ExampleHub.html)
2. Hit Play

## Expected Behavior
I see the MRTK Examples hub main menu

## Actual Behavior
I see nothing, and get the following two errors:

```
Can't load invalid scene LoadHubOnStartup - make sure the scene name is spelled correctly and that you have added the scene to your MixedRealitySceneSystem profile's content scenes array.

No valid scenes found to load.
```

**Comment by julenka** [comment]
Marking as Urgency-Soon because this is a regression in a core scene that we use to show MRTK.

**Comment by julenka** [comment]
@davidkline-ms could this be related to #6218 ?

**Comment by davidkline-ms** [comment]
> could this be related to #6218 ?

Possibly, it depends on what is serialized for the scene name in the profile.
