### ISSUE TITLE
On first time Checkbox.Interactable.TriggerOnClick() doesn't work

### ISSUE THREAD

**Issue by mingkyme** [microsoft/MixedRealityToolkit-Unity#6394]
## Describe the bug

All of check boxs's isToggled = true;
```c#
public Interactable[] interactables;
    public void ResetAction()
    {
        foreach(var i in interactables)
        {
            i.IsToggled = false;
            i.TriggerOnClick(); // expected true
            print(i.IsToggled);
        }
    }
```
When I pressed 4 times
![image](https://i.imgur.com/KF6enVC.png)
## Your Setup (please complete the following information)

- Unity Version 2018.4.11f
- MRTK Version 2.1

## Target Platform (please complete the following information)

- HoloLens

**Comment by Troy-Ferrell** [comment]
This works in the latest MRTK_development branch for me
