### ISSUE TITLE
Configuration checker window: first run does not display header image

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#6396]
## Describe the bug

When using the new configuration checker window (#6286), the first time it displays (generally on package import) the header image does not appear.

## To reproduce

1. Load the development branch repository
2. Create an asset package containing:
    - MixedRealityToolkit
    - MixedRealityToolkit.Services
    - MixedRealityToolkit.Providers
    - MixedRealityToolkit.SDK
3. Create a new Unity project
4. Import the package created in step 2

## Expected behavior

Dialog to be fully populated, including the header image

## Screenshots

![image](https://user-images.githubusercontent.com/13281406/67714769-cb66f680-f985-11e9-9c46-075ecd7922eb.png)

## Your Setup (please complete the following information)

- Unity 2018.4.11f1
- MRTK development branch

**Comment by CDiaz-MS** [comment]
This issue comes up when importing the foundation package, but the MRTK Project Configurator window also pops up twice.

**Comment by davidkline-ms** [comment]
This appears to be related to when Unity runs the configuration dialog and when the package import unpacks the image.

**Comment by davidkline-ms** [comment]
No longer seeing this issue.  Tested on 2.3.0 using Unity 2018.4.17f1
