### ISSUE TITLE
Cursor in HoloLens 1 not showing

### ISSUE THREAD

**Issue by datHSOsnabrueck** [microsoft/MixedRealityToolkit-Unity#6405]
## Overview
Its my first time working with MRTK. Before that I use HoloToolkit to display the cursor via Inputmanager and Meshcursorprefab. Now in MRTK I dont know how to have the cursor back in HoloLens 1. I would like to have a better instruction to implement the cursor into HoloLens 1.
## Expected Behavior
Cursor Icon should be visible and changing state since the gaze provider is included in Main Camera
## Actual Behavior
No cursor icon visible in HoloLens or gameview. Only sceneview and the state of cursor does not change.
## Steps to reproduce
open new scene and apply mrtk config
start deploy
## Unity Editor Version
2019.2
## Mixed Reality Toolkit Release Version
Microsoft Mixed Reality Toolkit v2.1.0

## attachment
![Capture](https://user-images.githubusercontent.com/33029648/67758534-2825e800-fa3e-11e9-8698-bc4ce0a3e773.PNG)
![Capture1](https://user-images.githubusercontent.com/33029648/67758844-ba2df080-fa3e-11e9-8426-6fcdfd708c80.PNG)

**Comment by cre8ivepark** [comment]
For HoloLens 1st gen projects, please use DefaultHoloLens1ConfigurationProfile.
You can change this profile by clicking MixedRealityToolkit object in the hierarchy, then through the Inspector. 
More details can be found in documentation
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Profiles/Profiles.html

**Comment by datHSOsnabrueck** [comment]
@cre8ivepark  Thanks for the information but I did the same setup once but it seem not to be the problem here.

![Capture2](https://user-images.githubusercontent.com/33029648/67834195-10ef0500-fae7-11e9-9ba2-653b5f8dafc8.PNG)

**Comment by Troy-Ferrell** [comment]
@datHSOsnabrueck , can you confirm you are on RC2 (as listed in the issue)? If so, please update to the latest version of MRTK

**Comment by datHSOsnabrueck** [comment]
> @datHSOsnabrueck , can you confirm you are on RC2 (as listed in the issue)? If so, please update to the latest version of MRTK

Hi @Troy-Ferrell, I have install the mrtk version from this link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html

I believe that it is the latest version right now right ?

**Comment by Troy-Ferrell** [comment]
@datHSOsnabrueck checking back on this, can you install the latest version 2.3 from releases page?
https://github.com/microsoft/MixedRealityToolkit-Unity/releases

**Comment by tjcomserv** [comment]
Hi did you resolve the issue?

**Comment by mathisloge** [comment]
@Troy-Ferrell 
i have been a fellow student of @datHSOsnabrueck and since our studies already completed, i do not think he will answer any more. Since I was not in the project, I cannot give any further information about it. Therefore I think that this issue can be closed.

**Comment by keveleigh** [comment]
Closing due to age, inability to repro, and the above comment.
