### ISSUE TITLE
Unreliable test TestToggleEvents

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#6417]
## Describe the bug

This test failed during PR validation for an unrelated change https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6411

https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=6369&view=ms.vss-test-web.build-test-results-tab&runId=13820&resultId=100036&paneView=debug

```
Toggle select did not fire
Expected: True
But was: False
```

**Comment by Troy-Ferrell** [comment]
@keveleigh still an issue?

**Comment by keveleigh** [comment]
Not sure. Can't say I've seen it recently. I'll go ahead and close unless we see it again
