### ISSUE TITLE
Align to spatial mesh?

### ISSUE THREAD

**Issue by paulcanning** [Microsoft/MixedRealityToolkit-Unity#642]
I want to align gameobjects that use "TapToPlace" to the mesh created by spatial mapping.

I think I'm on the right track by modifying the TapToPlace.cs script. I have added a public gameobject which I drag the cursor object to, and then I have modified the following code:

```
if (Physics.Raycast(headPosition, gazeDirection, out hitInfo, 30.0f, spatialMappingManager.LayerMask))
                {
                    // Rotate this object to face the user.
                    Quaternion toQuat = Camera.main.transform.localRotation;
                    toQuat.x = 0;
                    toQuat.z = 0;

                    var cursorRotation = cursor.transform.localRotation; // get cursors rotation

                    // Move this object to where the raycast
                    // hit the Spatial Mapping mesh.
                    // Here is where you might consider adding intelligence
                    // to how the object is placed.  For example, consider
                    // placing based on the bottom of the object's
                    // collider so it sits properly on surfaces.
                    if (PlaceParentOnTap)
                    {
                        // Place the parent object as well but keep the focus on the current game object
                        Vector3 currentMovement = hitInfo.point - gameObject.transform.position;
                        ParentGameObjectToPlace.transform.position += currentMovement;
                        ParentGameObjectToPlace.transform.rotation = toQuat;
                    }
                    else
                    {
                        gameObject.transform.position = hitInfo.point;
                        //gameObject.transform.rotation = toQuat; // old code
                        gameObject.transform.rotation = cursorRotation; // new rotation
                    }
                }
```

However, it just doesn't seem quite right. Especially, when trying to place an object on a ceiling, it does not face downwards.

**Comment by angelaHillier** [comment]
You might need to call RecalculateNormals() for the SpatialMapping mesh in order to tell the difference between a floor/ceiling/wall, etc. 

In the Holograms 230 Academy version of the HoloToolkit, SpatialMappingObserver.cs will call this after creating a new mesh when you set the 'RecalculateNormals' option to 'true'. This is done in the SurfaceObserver_OnDataReady() function:
`                if (RecalculateNormals)
                {
                    MeshFilter filter = surface.GetComponent<MeshFilter>();
                    if(filter != null && filter.sharedMesh != null)
                    {
                        filter.sharedMesh.RecalculateNormals();
                    }
                }`

I don't believe this option was ever added to the official HoloToolkit, but it might be a good addition for cases when the meshes need to have the correct normals.

**Comment by paulcanning** [comment]
I have implemented this and it seems to work a bit better, although it seems like the cursor doesn't always lie "flat" along the spatial mesh. I'm hoping that increasing the triangles per cubic metre helps.

**Comment by jessemcculloch** [comment]
Try this @paulcanning

`gameObject.transform.rotation = Quaternion.LookRotation(-hitInfo.normal, Vector3.up);`

**Comment by sebrk** [comment]
Any update on this? I'm facing the same issue. Sometimes the spawned object is really weirdly aligned although I'm facing a flat wall and it looks flat judging the wall mesh itself.

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
