### ISSUE TITLE
MRTK V2 - Visualization of Spatial Awareness Mesh is not working properly

### ISSUE THREAD

**Issue by arsi0001** [microsoft/MixedRealityToolkit-Unity#6425]
## Describe the bug

In my project I'm using a button that enables and disables spatial mapping/awareness. It works quite good, in 7 times out of 10. The following behaviour can be observed in the other 3 times. By disabling the spatial-map-mesh (polygones), they disappear to 90%. But 10% stays where it is. Repeated pressing of my button (dis/enable spatial mapping) does not help, the 10% just stays. Any suggestions what the reason for that behaivour could be?

## To reproduce

**Code Observer:**

    public void ToggleObservers()
    {
        if (SpatialAwarenessSystem == null) return;

        // If running → stop "running"
        if (_isObserverRunning)
        {
            SetVisualizationOfSpatialMapping(SpatialAwarenessMeshDisplayOptions.None);
            SpatialAwarenessSystem.SuspendObservers();
            _isObserverRunning = false;

            // Disabling the whole system boosts performance ~+5fps
            if (ShouldSpatialSystemBeDisabled)
                SpatialAwarenessSystem.Disable();

        }// Else start spatial mapping
        else
        {
            SpatialAwarenessSystem.Enable();
            SetVisualizationOfSpatialMapping(SpatialAwarenessMeshDisplayOptions.Visible);
            SpatialAwarenessSystem.ResumeObservers();
            _isObserverRunning = true;
        }
    }
**Code Set Visualtization of Spatial Mapping:**<br>

    public void SetVisualizationOfSpatialMapping(SpatialAwarenessMeshDisplayOptions option)
    {
        if (CoreServices.SpatialAwarenessSystem is IMixedRealityDataProviderAccess provider)
        {
            foreach (var observer in provider.GetDataProviders())
            {
                if (observer is IMixedRealitySpatialAwarenessMeshObserver meshObs)
                {
                    meshObs.DisplayOption = option;
                }
            }
        }
    }

## Your Setup (please complete the following information)

- Unity Version 2019
- MRTK Version v2.0

## Target Platform (please complete the following information)
- HoloLens

## Stackoverflow
https://stackoverflow.com/questions/58628429/mrtk-v2-visualization-of-spatial-awareness-mesh-is-not-working-properly?noredirect=1#comment103565478_58628429

**Comment by davidkline-ms** [comment]
This sounds like a race between the code that is fetching new meshes and the clearing code. New meshes are fetched asynchronously and they get added to the hierarchy and an internally managed collection.

The clearing logic only talks to the internally managed collection.

Thanks for the issue!

**Comment by davidkline-ms** [comment]
Investigating the potential race by using the observation clearing function. At this time, i have not found a consistent repro. Will also create a version of the spatial demo that uses the reported code.

**Comment by davidkline-ms** [comment]
@arsi0001, which specific version of Unity 2019 are you using? Is it .1, .2 or the .3 beta?

Also, does the behavior work better on MRTK 2.1.0?

**Comment by arsi0001** [comment]
@davidkline-ms right now I'm using 2019.2.11
I did not try it on the newest mrtk version. Should I try this with the new version, I'll get back to you here. But right now I cant say when this will happen.

**Comment by darax** [comment]
ahh, I think this is the same issue I just filed.  I'm about to try adding this to the Mesh observer suspend function:

MixedRealityToolkit.Providers\WindowsMixedReality\WindowsMixedRealitySpatialMeshObserver.cs
```
/// <inheritdoc/>
        public override void Suspend()
        {
#if UNITY_WSA
            if (!IsRunning)
            {
                Debug.LogWarning("The Windows Mixed Reality spatial observer is currently stopped.");
                return;
            }

            // UpdateObserver keys off of this value to stop observing.
            IsRunning = false;

            // Clear any pending work.
            meshWorkQueue.Clear();

            **if (outstandingMeshObject != null)
            {
                ReclaimMeshObject(outstandingMeshObject);
                outstandingMeshObject = null;
            }**
#endif // UNITY_WSA
        }
```

**Comment by darax** [comment]
@arsi0001, the patch I posted above seems to be working in my application that was having the same trouble as yours.

**Comment by arsi0001** [comment]
@darax hey, just tried it a few times and I guess it works. Thanks! You can post this as an answer to my post stackoverflow, so I can accept it as a solution.
