### ISSUE TITLE
Slate ContentQuad Material is in MixedRealityToolkit.Examples

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#6438]
## Describe the bug
Slate Prefab is  in: MixedRealityToolkit.SDK\Features\UX\Prefabs\Slate
but it uses a Material PanContent that is in: MixedRealityToolkit.Examples\Demos\HandTracking\Materials
(with texture in Assets\MixedRealityToolkit.Examples\Demos\StandardShader\Textures)

so when opening the prefab without having Examples, teh pink default material is displayed.

## To reproduce

1. Open Slate prefab without having Examples installed

## Your Setup (please complete the following information)

- Unity Version [2018.4.9f1]
- MRTK Version [v2.1]

**Comment by keveleigh** [comment]
Fixed via #6483
