### ISSUE TITLE
MRTK defaults for best hologram stability on HoloLens 2

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6447]
## Overview
This bug tracks work to ensure that MRTK will provide good default behavior for Hologram stability on HoloLens 2.

 * [ ] Provide a default hand menu in the MRTK SDK folder (not samples) that has a menu with a backing panel
 * [ ] Ensure that slate has a backing panel
* [ ] When picking up slate,  ManipulationHandler will add a transparent area (see screenshot) around the slate which will cause depth lsr issues.

![image](https://user-images.githubusercontent.com/168492/69392256-4a500600-0c8a-11ea-87ca-702d179bf320.png)

**Comment by Troy-Ferrell** [comment]
Related: #6449
