### ISSUE TITLE
Object with Constant View Size solver becomes 2x in MRC capture

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#6458]
## Describe the bug
The size of an object which has ConstantViewSize solver becomes larger when MRC capture starts. You can see it when you start MRC. When you stop MRC, it returns back to its original size. Not sure if MRC introduces a different camera into the scene and affects object scaling.
https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.Utilities.Solvers.ConstantViewSize.html

*Functionality has no issue in normal use. The symptom only shows up in MRC.

## To reproduce
1. On any object, assign ConstantViewSize script. 
2. Build, deploy, launch app
3. Star, stop MRC. Check the object size.

## Expected behavior
Object size should not be changed on MRC

**Comment by Troy-Ferrell** [comment]
MRC changes the FOV of one of the eyes...That must be propagating to the MainCamera in Unity and the fov scale is calculated every frame in the ConstantViewSize
