### ISSUE TITLE
Text to speech script not working

### ISSUE THREAD

**Issue by DarrenGuinness** [Microsoft/MixedRealityToolkit-Unity#646]
I followed this guide (https://abhijitjana.net/2017/01/02/using-text-to-speech-in-your-holographic-app/) on how to use the text to speech manager. I have verified that I have attached the audio source to the textToSpeech.cs script, but when the project loads I get the following output:

“An AudioSource is required and should be assigned to ‘Audio Source’ in the inspector.”
Speech not initialized. “Hello World”

Am I missing something?

**Comment by StephenHodgson** [comment]
You're missing an audio source just as the error described

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
