### ISSUE TITLE
UnityARCameraSettings causes NullReferenceExeption

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6461]
## Describe the bug

Starting the Editor, opening a scene with the MRKT, or assigning a profile to a not yet configured MRKT while on Android platform causes the UnityARCameraSettings to throw a NullReferenceException here

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/4929b9e39ac7a5a54a6df97b3a90d567fac39d4d/Assets/MixedRealityToolkit.Providers/UnityAR/UnityARCameraSettings.cs#L119

Same happens on the Oculus Quest, which leads me to thinking this is either a problem the of the current preview version of the ARFoundation package, the package does not support the Quest at all, or it is due to the await being run as a coroutine due to the AwaiterExtensions wrapping the call.

## To reproduce

1. switch to android, add MRKT, select a profile

## Expected behavior

no error

## Your Setup (please complete the following information)

- Unity Version 2018.3.12f1
- mrtk_development

## Target Platform (please complete the following information)

- Editor Android
- Oculus Quest

**Comment by Alexees** [comment]
Wanted to add that the current preprocessor directive wraps the only await in the method. It should wrap the whole method to not generate the error for a missing await in an async method.

**Comment by davidkline-ms** [comment]
Potential fix is in PR. Also, given the newness of this feature, it is being categorized as experimental for 2.2.0

**Comment by Alexees** [comment]
Do you think defaulting it to false would be a good idea? I wouldn't have had this problem if it wasn't enabled

**Comment by davidkline-ms** [comment]
#6461 removes ar foundation from the default profiles, along with moving it to experimental.

a documentation PR will be opened in the coming days with instructions on how to enable and configure ar foundation support for Android and iOS
