### ISSUE TITLE
NearInteractionTouchableUnityUI should allow for extension/customization of how the touchable surface is determined

### ISSUE THREAD

**Issue by hendryems** [microsoft/MixedRealityToolkit-Unity#6462]
## Describe the problem

We observed an issue, in our app, where due to a how our app's UI is designed, we have touchable surfaces that's on the edge of a canvas.

Also due to the size **AND** position of the touchable surface (towards the bottom), this results in users trying to poke/touch the surface at an angle that would cause the finger to go outside the bounds of the surface:
![image](https://user-images.githubusercontent.com/50596066/68163549-9cb1c880-ff0f-11e9-8546-b94c4d32f8ea.png)

This would cause code in the PokePointer to detect that there's no more touchable surface and prematurely raise the Pointer up event resulting in double clicks (when the user's finger comes back up).

## Describe the solution you'd like

Allow customization **AND** extension to NearInteractionTouchableUnityUI that gives developers the flexibility to control the rect of the touchable surface that's independent from the RectTransform.

## Additional context

Here's some code I added that extends this:

```
        [Tooltip("Optional border to apply, on top of Unity UI RectTransform, for the purposes of determining if the surface is touchable")]
        [SerializeField]
        private RectOffset touchableRectOffset = new RectOffset();

        private Rect touchableRect = new Rect();

        public override float DistanceToTouchable(Vector3 samplePoint, out Vector3 normal)
        {
            normal = transform.TransformDirection(-LocalPressDirection);

            Vector3 localPoint = transform.InverseTransformPoint(samplePoint);

            // touchables currently can only be touched within the bounds of the rectangle.
            // We return infinity to ensure that any point outside the bounds does not get touched.
            Rect hitTestRect = GetTouchableRect(rectTransform.Value.rect);
            if (!hitTestRect.Contains(localPoint))
            {
                return float.PositiveInfinity;
            }

            // Scale back to 3D space
            localPoint = transform.TransformSize(localPoint);

            return Math.Abs(localPoint.z);
        }

        /// <summary>
        /// Allows for the rectangle of the Unity UI element to be augmented for the purpose of determining if the surface is touchable
        /// </summary>
        /// <param name="uiRect">The Rect of the Unity UI element</param>
        /// <returns>The Rect of the touchable surface</returns>
        protected virtual Rect GetTouchableRect(Rect uiRect)
        {
            this.touchableRect.xMin = uiRect.xMin - touchableRectOffset.left;
            this.touchableRect.xMax = uiRect.xMax + touchableRectOffset.right;
            this.touchableRect.yMin = uiRect.yMin - touchableRectOffset.bottom;
            this.touchableRect.yMax = uiRect.yMax + touchableRectOffset.top;
            return this.touchableRect;
        }
```

**Comment by davidkline-ms** [comment]
@polar-kev, can you review and talk with d365 and help scope the work?

**Comment by davidkline-ms** [comment]
Questions related to this:

* How much work would it be to implement this request
* Is there a prototype that exists to help validate the concept
* Would it lead to customer confusion where one 2D touchable control can be approached from an angle (ex: one at the bottom of the gesture frame) and another cannot (one in the middle of the frame)

**Comment by Zee2** [comment]
Closing as stale. We've decided to pursue an alternative route for UGUI-based UI with touch interactions.
