### ISSUE TITLE
Validation Errors when publishing to the Windows App Store

### ISSUE THREAD

**Issue by benpaddlejones** [microsoft/MixedRealityToolkit-Unity#6463]
## Describe the bug
Validation errors when validating MRTK app for the Microsoft App store:
Failed:
- Binary analyzer
- Supported APIs
- Debug configuration (The binary UnityRemotingWMR.dll is built in debug mode.)

## To reproduce
1. Make a simple MRTK app
2. Build
3. Package for Microsoft Store
4. Run validation test

## Expected behavior
Should pass the validation test

## Screenshots
See summary file attached

## Your Setup (please complete the following information)
[ValidationResult.txt](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3806581/ValidationResult.txt)

- Unity Version 2018.4.11f1
- MRTK Version v2.1
- VS 2017 & 2019 

## Target Platform (please complete the following information)
- WMR immersive

**Comment by keveleigh** [comment]
How are you building your app for the store? If you package it as a **Master** build, it should strip out the development binaries (like `UnityRemotingWMR.dll` you mention above).

**Comment by benpaddlejones** [comment]
> How are you building your app for the store? If you package it as a **Master** build, it should strip out the development binaries (like `UnityRemotingWMR.dll` you mention above).

A lot less fails when using Unity 2019.2.11f1 and VS2019:
[ValidationResult2.txt](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3806786/ValidationResult2.txt)

1. Build from Unity
2. Open in *.sln in VS 2019
3. Publish/Associate App with thre
4. Publish/Create App Packages (choose option "Microsft store as ...")
5. Create for x64 only
6. Run local validation test

**Comment by benpaddlejones** [comment]
Update, we just received this feedback from Microsft Store certification:

API GetFileVersionInfoA in version.dll is not supported for this application type. UnityPlayer.dll calls this API.
API GetFileVersionInfoSizeA in version.dll is not supported for this application type. UnityPlayer.dll calls this API.

**Comment by keveleigh** [comment]
What does your "Select and configure packages" page look like (I got here via Create App Packages, but I assume there's a similar page via the other paths)? The architectures you're building should all be configured for Master (what you set in Unity doesn't matter here, just what's set in Visual Studio):

![image](https://user-images.githubusercontent.com/3580640/68172534-caf1d100-ff2c-11e9-94b2-4a265672a455.png)

**Comment by benpaddlejones** [comment]
Yes, that's exactly the same as I had set in both versions.

**Comment by benpaddlejones** [comment]
fixed by changing .net compatibility

**Comment by martatesar** [comment]
> fixed by changing .net compatibility

How exactly? I have same issue.

**Comment by TiMeJuMp** [comment]
Same issue here with Unity 2019.4.25

**Comment by keveleigh** [comment]
I'd recommend reporting this on the Unity forums, as we don't have direct control over the contents of Unity's DLLs and packages.
