### ISSUE TITLE
OnScreen Keyboard for platforms not natively supporting one

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6466]
## Describe the problem

With Microsoft's and most mobile devices supporting a keyboard a lot of them are already covered. There are still devices that do not support this like the Oculus devices.

## Describe the solution you'd like

A Unity keyboard that will be used in the case that a platform does not support it.

## Describe alternatives you've considered

Not using a keyboard?

## Additional context

The current implementation for spawning keyboards already started streamlining the various ways of handling the keyboards that are available. Wouldn't be too difficult to add one as a fallback for all other cases.

**Comment by Alexees** [comment]
@julenka I ported the HTK keyboard to MRKT as a first step for at least having a keyboard. Do you think it will suffice for the time being? What folder should I be putting it into?

**Comment by julenka** [comment]
> @julenka I ported the HTK keyboard to MRKT as a first step for at least having a keyboard. Do you think it will suffice for the time being? What folder should I be putting it into?

Hi, I would recommend putting this in as an experimental feature, you can follow the experimental feature guidelines [here](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/ExperimentalFeatures.html) to see which folder to put files in. Reason is without this being an experimental feature it would need tests as well as documentation explaining when the keyboard could be used.

**Comment by julenka** [comment]
Fixed in #6492
