### ISSUE TITLE
Debug.Log is used in cases where nothing changes

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6468]
## Describe the bug

The method ApplyARFoundationUWPCompileFix is a little annoying as it throws 3 logs even in the case nothing gets changed. I'd like to only be bothered when something actually changed

## Expected behavior

log changes only

## Screenshots

![image](https://user-images.githubusercontent.com/32508825/68198834-13f16600-ffbd-11e9-912e-51c851b3fc73.png)

## Your Setup (please complete the following information)

- Unity Version 2018.3.12f1
- mrtk_development

## Target Platform (please complete the following information)

- WMR immersive/ Editor

**Comment by Alexees** [comment]
Same goes for OnProcessScene in SceneInfoUtils

**Comment by keveleigh** [comment]
Fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6480
