### ISSUE TITLE
Unable to build with Unity 2019.2.11 + MRTK 2.1.0

### ISSUE THREAD

**Issue by SoundGuy** [microsoft/MixedRealityToolkit-Unity#6469]
## Overview
When trying to build through the build windows i'm getting an error:

MissingMethodException: void UnityEditor.EditorUserBuildSettings.set_wsaGenerateReferenceProjects(bool)

## Expected Behavior
Unity should perform a build.

## Actual Behavior

gives this error and doesn't do anything:

MissingMethodException: void UnityEditor.EditorUserBuildSettings.set_wsaGenerateReferenceProjects(bool)
Microsoft.MixedReality.Toolkit.Build.Editor.UwpPlayerBuildTools+<BuildPlayer>d__2.MoveNext () (at <5e8ab2ff4db94d18af7b4dddb781b2e9>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <567df3e0919241ba98db88bec4c6696f>:0)
Microsoft.MixedReality.Toolkit.Build.Editor.UwpPlayerBuildTools+<BuildPlayer>d__1.MoveNext () (at <5e8ab2ff4db94d18af7b4dddb781b2e9>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <567df3e0919241ba98db88bec4c6696f>:0)
Microsoft.MixedReality.Toolkit.Build.Editor.BuildDeployWindow+<BuildAll>d__73.MoveNext () (at <5e8ab2ff4db94d18af7b4dddb781b2e9>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <567df3e0919241ba98db88bec4c6696f>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:114)
System.Reflection.MethodBase:Invoke(Object, Object[])
Microsoft.MixedReality.Toolkit.Utilities.SyncContextUtility:ExecuteContinuations()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:303)

## Steps to reproduce

Opened a new emty project,
imported nuget.
Installed MRTK foundation, extentions, tools, examples.
Changed platform to UWP
OPened builed window,
clicked build all

error

## Unity Editor Version
2019.2.11f

## Mixed Reality Toolkit Release Version
2.1.0

**Comment by Troy-Ferrell** [comment]
This is fixed in MRTK_dev latest and should be good in 2.2

**Comment by keveleigh** [comment]
For reference, this was fixed in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6016
