### ISSUE TITLE
Error when trying to connecto to hololens device in build window deploy tab

### ISSUE THREAD

**Issue by SoundGuy** [microsoft/MixedRealityToolkit-Unity#6470]
## Describe the bug
Unable to connect to hololens

getting this error:
InvalidOperationException: The following game object is invoking the DontDestroyOnLoad method: AsyncCoroutineRunner. Notice that DontDestroyOnLoad can only be used in play mode and, as such, cannot be part of an editor script.
Microsoft.MixedReality.Toolkit.Utilities.AsyncCoroutineRunner.get_Instance () (at <4f0fe93e8db3440297d2c719f5578907>:0)
Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions+<>c__DisplayClass14_0`1[T].<GetAwaiterReturnSelf>b__0 () (at <4f0fe93e8db3440297d2c719f5578907>:0)
Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions.RunOnUnityScheduler (System.Action action) (at <4f0fe93e8db3440297d2c719f5578907>:0)
Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions.GetAwaiterReturnSelf[T] (T instruction) (at <4f0fe93e8db3440297d2c719f5578907>:0)
Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions.GetAwaiter (UnityEngine.AsyncOperation instruction) (at <4f0fe93e8db3440297d2c719f5578907>:0)
Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DevicePortal+<DevicePortalAuthorizationAsync>d__40.MoveNext () (at <f356ca7bd2894174bf4b2bb532e579a0>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <567df3e0919241ba98db88bec4c6696f>:0)
Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DevicePortal+<EnsureAuthenticationAsync>d__39.MoveNext () (at <f356ca7bd2894174bf4b2bb532e579a0>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <567df3e0919241ba98db88bec4c6696f>:0)
Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DevicePortal+<GetMachineNameAsync>d__18.MoveNext () (at <f356ca7bd2894174bf4b2bb532e579a0>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <567df3e0919241ba98db88bec4c6696f>:0)
Microsoft.MixedReality.Toolkit.Build.Editor.BuildDeployWindow+<ConnectToDevice>d__69.MoveNext () (at <5e8ab2ff4db94d18af7b4dddb781b2e9>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <567df3e0919241ba98db88bec4c6696f>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:114)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:94)

## To reproduce
in an empty project, i imported:
MRTK foundation, extension, tools and examples
I opened up the build windows
I opened deploy options, hit the + button
added the IP , username and password
clicked connect and got this error

## Expected behavior

Expected it to connect to hololens and then deploye there after building.

## Your Setup (please complete the following information)

- Unity Version  2019.2.11f1
- MRTK Version 2.1.0

## Target Platform (please complete the following information)

- HoloLens

**Comment by keveleigh** [comment]
This should be fixed in the dev branch via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6363, and will be in the 2.2 release.
