### ISSUE TITLE
SR_Triangles_Object_Space.shader has warnings

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#6475]
## Describe the bug

This shader, added in #5988, throws some Unity warnings on first load.

## To reproduce

1. Pull the latest mrtk_dev and open in Unity (might need to right click on this shader and select `Reimport`)

## Screenshots

![image](https://user-images.githubusercontent.com/3580640/68251978-21b4e480-ffd9-11e9-9bd8-c04fccb1f572.png)

![image](https://user-images.githubusercontent.com/3580640/68251986-25e10200-ffd9-11e9-9f8a-b8ac1fe48858.png)

**Comment by davidkline-ms** [comment]
@keveleigh, you mention this may have been fixed and not closed. please confirm and close as appropriate

**Comment by keveleigh** [comment]
Fixed (a while ago) via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6686
