### ISSUE TITLE
FocusProvider.GetPrioritizedHitResult is prioritizing raycast hits that aren't found in the prioritized layer masks

### ISSUE THREAD

**Issue by semcbeth** [microsoft/MixedRealityToolkit-Unity#6481]
## Describe the bug

In FocusProvider.GetPrioritizedHitResult, the physics and graphics raycast hits are compared using the prioritized layer masks supplied to the method. When one of the raycast hits is in a layer that's not included in the array of prioritized layer masks, the FindLayerListIndex call will return -1. This -1 result is then prioritized because it's lower than any other FindLayerListIndex result.

Any -1 results should be treated as a lower priority than any other result.

## To reproduce

1. Add an object with a collider to the scene with a layer that's not included in the "Pointing Raycast Layer Masks" in the pointer configuration profile.
2. Position a UI object in a layer that is included in the list of prioritized layer masks in front of the object from step 1.
3. Point your line pointer at the UI object.

## Expected behavior

The line pointer cursor is placed on the UI object.

## Actual behavior

The line pointer cursor goes through the UI object and is placed on the physics object.

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.4.8f1]
- MRTK Version [latest]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by Troy-Ferrell** [comment]
@semcbeth, out of curiosity, how are you getting a raycast result that is not in the prioritized layer mask? The `GetPrioritizedHitResult` still needs to be fixed to have guards for the case you outlined. But the `GetPrioritizedHitResult` is used to compare the 3D raycast against the graphics raycast result, both of which use the prioritizedLayerMasks....thus any object not one of the layers in that mask should not be returned as a 3D raycast result
