### ISSUE TITLE
Publish Remote Host Desktop App

### ISSUE THREAD

**Issue by reillydonovan** [Microsoft/MixedRealityToolkit-Unity#649]
This is less of an issue and more of a feature request.
I was wondering if there is a way to publish an application from Unity with remote hosting built in.  I can run remote hosting from the Unity Editor but would love to do this with a self contained app.  Is there a way to do this without going into the VS project that Unity publishes?  And if not, is there a guide for how to do this with a VS project published through Unity?  Thanks!

https://developer.microsoft.com/en-us/windows/mixed-reality/add_holographic_remoting

**Comment by HoloFan** [comment]
@reillydonovan : Maybe you can have a look at the [HoloLens CompanionKit](https://github.com/Microsoft/HoloLensCompanionKit)

I have not worked with it so far. But it sounds just like what you were asking for.
Please let us know if it helped you.

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
