### ISSUE TITLE
Gaze cursor is showing up when hand rays are off

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6496]
## Describe the bug
The shell design is gaze cursor should only show up on hololens 2 if both hands are not visible AND the user says "select". But right now the gaze cursor is showing up any time hand rays are turned off.

![image](https://user-images.githubusercontent.com/168492/68325674-be7d8d80-007e-11ea-9abe-a17c7f606c30.png)

## To reproduce

1. Go to HandInteractionExamples scene
2. Move hand near an object so rays turn off
4. See that the gaze cursor turns on

## Expected behavior
The gaze cursor should only turn on after user says "select"

## Screenshots

![image](https://user-images.githubusercontent.com/168492/68325730-dbb25c00-007e-11ea-8aa5-ffebbcc47c5b.png)

## Your Setup (please complete the following information)

- mrtk_development latest

## Why release blocker
This is a user-visible regression and regression from shell parity.

**Comment by julenka** [comment]
It looks like `CoreServices.InputSystem.EyeGazeProvider.IsEyeGazeValid` is returning true when running in the editor.

**Comment by keveleigh** [comment]
I think the input simulation service returns eye gaze in the editor for that scene

**Comment by julenka** [comment]
Yup that's the issue. I don't recall us having this for 2.1, but maybe I'm wrong. checking now.

**Comment by julenka** [comment]
Okay, for 2.1 release we did not simulate eye position by default in the HL2 profile. Looks like the new input sim profile for HL2 is commit  63d9e86955504965f0258a15e72a51fea827ee8c, introduced in #6393 I think the feedback form PR #6393 and PR #6320 is interesting and it's great to know that it's possible to solve the issue of #6393 by modifying the profile. However, the change actually causes a bug which is when the hand gets near a grabbable and hand ray disappears, the gaze cursor shows up. This does not match hololens 2 shell and design recommendations.
