### ISSUE TITLE
ManipHandler does not provide way to know which pointer(s) are manipulating it

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6498]
## Describe the bug
When building a prototype I needed to have an object that would only be grabbable by certain pointers (e.g. only articulated hands). To do this I needed to go into the input system, and iterate over all pointers to see which one was manipulating my object. It would be much easier if the OnManipulationStarted, Updated events contained a field "Pointer" referencing the pointer that was manipulating the object.

Currently ManipulationEventData has the following fields:

```
    public class ManipulationEventData
    {
        public ManipulationHandler ManipulationSource { get; set; }
        public bool IsNearInteraction {get; set; }
       public Vector3 PointerCentroid { get; set; }
       public Vector3 PointerVelocity { get; set; }
       public Vector3 PointerAngularVelocity { get; set; }
    }
```

I propose we add a field "Pointer" which will contain the pointer that initiated manipulation:

```
    public class ManipulationEventData
    {
        public ManipulationHandler ManipulationSource { get; set; }
        public IMixedRealityPointer Pointer { get; set; }
        public bool IsNearInteraction {get; set; }
       public Vector3 PointerCentroid { get; set; }
       public Vector3 PointerVelocity { get; set; }
       public Vector3 PointerAngularVelocity { get; set; }
    }
```

**Comment by keveleigh** [comment]
Is your filter more strict than "far" vs "near" (in which case, `IsNearInteraction` seems useful)?
Or are you filtering on the controller type, since you mention articulated hands?

**Comment by Railboy** [comment]
I've wanted this feature since HTK.
