### ISSUE TITLE
Bounding Box handles colliders does not orient correctly

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#6507]
## Describe the bug

When using rotation handles size and padding, teh created box collider does not take the correct rotation for X and Z rotation handles. (see attached screenshot).

**EDIT: seems scale handles are not aligned properly too** (see 2nd screenshot)
## To reproduce

- add a bounding box to an object  with rotation handle size and padding setup (example in attached screenshot)
- click play and observe the created box collider (click on the bounding box in the hierarchy and observe gizmo in the Scene view)

## Expected behavior

box colliders for handls should take the orientation of each handle.

## Screenshots

![image](https://user-images.githubusercontent.com/49415246/68384991-21dbee00-0159-11ea-9284-af6e563a6273.png)
![image](https://user-images.githubusercontent.com/49415246/68992250-4fb3e780-0869-11ea-951a-457a86e5922c.png)

## Your Setup (please complete the following information)

- Unity Version [2018.4.9f1]
- MRTK Version [v2.1]

**Comment by gilbdev** [comment]
fixed but as PR suggests, a unit test could be added.

**Comment by keveleigh** [comment]
@gilbdev Possible side effect? #6582

**Comment by gilbdev** [comment]
check
 github.com/gilbdev/MixedRealityToolkit-Unity/commits/bugfix/boundingbox_rotationhandle

i've fixed 6582, but not sure the scale fix is perfect (i've jsut recentered the box collider but this is probably not the best solution (could be better centered to the mesh), at least it's better than acutal impl.
![image](https://user-images.githubusercontent.com/49415246/68992323-1af46000-086a-11ea-841f-db536e938420.png)

**Comment by gilbdev** [comment]
fixed as per #6615
