### ISSUE TITLE
Interactable Disable/Enable does not 'cut' theme easing

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#6509]
## Describe the bug

Now that reenabling an interactable reset states correctly (i.e. interactable appear correctly in default state and not in focused or pressed state), another bug emerge :
the state transitionning still happens between the last state while the interactable was enabled and the state when enabling to default.

so if we disable the interactable while in 'pressed' state, when enabling the button again, the theme will apply the easing between pressed and default state.
(see gif below)

## To reproduce

1. Configure 2 interactable to have themes with easing and enabling/disabling each other
2. Click to disable
3. click to enable and observe

## Expected behavior

when enabling an interactable, the easing should not occur and the interactable should appear like it was 'new'.

## Screenshots
here is an example, with a very slow easing to demonstrate.
(also note that when doing a quick click, the easing is not complete and it resumes at the time it was when disabled)

![interactable_theme_easing](https://user-images.githubusercontent.com/49415246/68389678-cfec9580-0163-11ea-8ddb-7730de54f780.gif)

## Your Setup (please complete the following information)

- Unity Version [2018.4.9f1]
- MRTK Version [v2.1 - 2.2]

**Comment by Troy-Ferrell** [comment]
@CDiaz-MS FYI, this sounds related to the work you did for 2.2
