### ISSUE TITLE
MRTK script compilation errors when Microsoft.Windows.MixedReality.DotnetWinRT package is installed

### ISSUE THREAD

**Issue by dfields-msft** [microsoft/MixedRealityToolkit-Unity#6511]
## Describe the bug

After installing both MRTK and [Microsoft.Windows.MixedReality.DotnetWinRT](https://www.nuget.org/packages/Microsoft.Windows.MixedReality.DotnetWinRT), script compilation errors occur in MRTK scripts due to references to the `Windows` namespace. This occurs because the scripts themselves exist inside the `Microsoft` top-level namespace, so bare references to the `Windows` namespace within the scripts will bind against the `Windows` *sub*namespace from Microsoft.Windows.MixedReality.DotnetWinRT rather than the global `Windows` namespace. The fix is to qualify these references with `global::`.

## To reproduce

1. Install MRTK
2. Install [Microsoft.Windows.MixedReality.DotnetWinRT](https://www.nuget.org/packages/Microsoft.Windows.MixedReality.DotnetWinRT) per [documentation](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-namespace-with-unity-apps-for-hololens#mixed-reality-apis)
3. Wait for Unity to recompile scripts
4. Observe script compilation errors in the Output window due to missing types in the `Microsoft.Windows` namespace.

## Expected behavior

No compilation errors when both packages are installed.

## Screenshots

![Unity script compile errors](https://user-images.githubusercontent.com/18537467/68414012-3d88c980-0144-11ea-9156-32dbfcd62c6b.jpg)

## Your Setup (please complete the following information)

- Unity Version 2019.2.11f1
- MRTK Version 2.1

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive

## Additional context

I believe this conflict has already been addressed in the changes to consume MRTK as a NuGet package, but this fix is needed independent of that so that even consumers who aren't using the NuGet package to acquire MRTK itself can still successfully use Microsoft.Windows.MixedReality.DotnetWinRT and other related packages like Microsoft.MixedReality.QR and Microsoft.MixedReality.SceneUnderstanding.

**Comment by dfields-msft** [comment]
@keveleigh @davidkline-ms FYI.

**Comment by keveleigh** [comment]
The `Storage` fixes went in with #6147

**Comment by davidkline-ms** [comment]
Confirmed this has been resolved in 2.2.0 via #6147
