### ISSUE TITLE
TeleportPointer teleportation logic requires Thumbstick

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6527]
## Describe the bug

Right now I'm trying to implement a MRTK conforming way of teleporting with the Oculus Go controller. The controller just has a Touchpad, which behaves differently then a thumbstick. While that one can be easily rotated around it's outer most extendability, the Touchpad as being a surface is rather interacted with everywhere.
For the teleportation to work, the user needs to know that he must move their thumb on the outer edges to not trigger the center threshold, which activates the teleport.
In the case of this controller, pressing down on the pad would be a good way to enter the teleport state and releasing it to execute it. This should allow for free movement on the whole surface while in that state.
The TeleportPointer should handle activation and deactivation of the teleport arc interaction process seperately from the values it needs to direct the arrow.
The threshold that distinguishes between the states would be pulled into the controller performing it, or some in between handler...

Right now, for this to work, one has to adjust the input to the thresholds in the TeleportPointer to not undercut them.

## To reproduce

1. Not yet implemented

## Expected behavior

Teleport alghorithm is not specifically thumbstick bound but rather expects a bool and an axis toggling on and off and reading for the direction arrow

## Your Setup (please complete the following information)

- Unity Version [2018.4.12f1
- mrtk_development

## Target Platform (please complete the following information)

- Oculus Go native

**Comment by keveleigh** [comment]
Still should be addressed
