### ISSUE TITLE
Allow other input values than a 6-DOF controller for ManipulationHandler

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6537]
## Describe the problem

The ManipulationHandler directly reads from the Pointer that's activated it, which means it expects that to be a 6-DOF device.
With mobile devices or the Oculus Go controller, this is not the case, we lack information to perform the same movements.

## Describe the solution you'd like

Maybe the ability to add a component next to ManipulationHandler that is responsible for providing the 6-DOF values.
This way they can be customized and calculated the way we want.

## Describe alternatives you've considered

Talking Oculus Go here, and since I'm currently only clashing with the controller visualizer, I could configure IT to listen to a pacific InputAction, while manually adding z values based on the touch controller for the regular execution path.
This would however mean that as soon some other service is interested in the controller position, it'll move back and forth.

## Additional context

The Oculus Go controller lacks translation. It rotates about the elbow of the user, with an offset but that's about it. Pushing or pulling is not one of its capabilities

**Comment by polar-kev** [comment]
Hi @Alexees, since Oculus Go is not supported I'll be closing this issue.
