### ISSUE TITLE
BoundingBox rotate 360

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6538]
## Describe the problem

At the moment the BoundingBox can only be rotate as far as the handle being orthogonal to the view direction. This forces the user to grab a new handle and turn again. leading to at least 2 grabs for nearly 360 degree.
This should be part of the overall refactor of the box #5340 

## Describe the solution you'd like

The Box should be able to just spin about an angle per controller movement/ rotation

## Describe alternatives you've considered

none really

**Comment by polar-kev** [comment]
@Zee2 can you check if this is still the case in the hand interaction scene?

**Comment by Zee2** [comment]
Hi, this should be totally possible with `BoundsControl` by just rotating the object with the rotation handles, and reaching "through" the object.

![rotating](https://user-images.githubusercontent.com/5544935/126229924-aa9dba67-4e20-4c8f-bca2-7b4e7bf55b4f.gif)

@Alexees We understand this is a very old issue, but if there is something fundamentally missing from our implementation, we'd love to hear from you!
