### ISSUE TITLE
IMixedRealityInputHandler.OnInputDown is not working in MRTK 2.1.0

### ISSUE THREAD

**Issue by bharath09vadde** [microsoft/MixedRealityToolkit-Unity#6554]
## Describe the bug
IMixedRealityInputHandler.OnInputDown is not working in MRTK v2.1.0, But is working fine with MRTK v2.0.0 RC2.1
When I air tapped, the OnInputDown is not called at all.
## To reproduce
Import the latest MRTK 2.1.0 unity package and create a simple script using IMixedRealityInputHandler.OnInputDown to activate a gameobject or something simpler.
Import the latest MRTK 2.1.0 unity package and create a simple script using IMixedRealityInputHandler.OnInputDown to activate a gameobject or something simpler.

## Expected behavior
When air tapped the object has to be activateed.

## Your Setup (please complete the following information)

- Unity Version [2019.2.5f1],[2019.1.14f1]
- MRTK Version [v2.1.0]

## Target Platform (please complete the following information)

- HoloLens

**Comment by wiwei** [comment]
@bharath09vadde can you provide some more details about the scenario in which you're hitting this? i.e. are you using holographic remoting? Are you deploying to a device (i.e. HL1?) Are you testing in the editor?

**Comment by keveleigh** [comment]
Could be related to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6413

**Comment by bharath09vadde** [comment]
@wiwei I was testing it on Hololens1 as well as the editor. Maybe I can send you the screenshot of the scene setup tomorrow.

**Comment by Troy-Ferrell** [comment]
@bharath09vadde can you update to the latest release of MRTK and confirm your issue repros?
https://github.com/microsoft/MixedRealityToolkit-Unity/releases

**Comment by bharath09vadde** [comment]
It is working fine when I have attached the script to the Main Camera. I guess it no more is a problem even with the older version of MRTK.
Thanks for looking into it.
