### ISSUE TITLE
MRTK won't compile in Unity 2019.x until you manually change Microsoft.MixedReality.Toolkit.Providers.UnityAR.asmdef

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedRealityToolkit-Unity#6555]
## Describe the bug

When we pull the latest dev branch into Unity 2019.x it fails to compile with the following error:

`Assets\MixedRealityToolkit.Extensions\Providers\Experimental\UnityAR\Utilities\ArEnumConversion.cs(21,23): error CS0246: The type or namespace name 'TrackedPoseDriver' could not be found (are you missing a using directive or an assembly reference?)`

## Expected behavior

Ideally the MRTK should compile in official Unity releases, especially releases that we [link to in our docs.](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html)

If that's not possible then we should try to use preprocessor directives to throw an error that provides more context.

## How to fix manually

This error can be fixed by selecting **Microsoft.MixedReality.Toolkit.Providers.UnityAR.asmdef** and adding a reference to **UnityEngine.SpatialTracking.asmdef.**

[Additional context.](https://forum.unity.com/threads/trackedposedriver-in-2019-1.634963/)

**Comment by wiwei** [comment]
@davidkline-ms @keveleigh

**Comment by Troy-Ferrell** [comment]
@Railboy  Also FYI, there is a script atm to workaround this issue easily under, scripts\support2019\setup_for_2019.ps1

**Comment by Railboy** [comment]
@Troy-Ferrell Thanks. The issue is simple to fix, so I'm not blocked. I'm more concerned about the first impression of the toolkit not compiling on startup and then not offering any feedback or instructions for how to get it running.

**Comment by davidkline-ms** [comment]
Release notes have been updated to point to the appropriate documentation article in reference to this error message.
