### ISSUE TITLE
Existing Extension services do not contain assembly definitions

### ISSUE THREAD

**Issue by radicalad** [microsoft/MixedRealityToolkit-Unity#6562]
## Describe the bug

This issue stemmed out of attempting to create an example scene for an Extension Service I wrote (PR coming soon 😄 ). I found that it is impossible to reference anything inside of the `Microsoft.MixedReality.Toolkit.Extensions` namespace.

After further inspection, it appears `Microsoft.MixedReality.Toolkit.Extensions` does not have an assembly definition. @davidkline-ms pointed out that the proper pattern is for each extension service to have its own assembly definition.

## To reproduce

Navigate to any of the Extension Services in `Microsoft.MixedReality.Toolkit.Extensions`.

## Your Setup (please complete the following information)

- Unity Version 2018.4.12f1
- MRTK Version latest MRTK_development

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by keveleigh** [comment]
It feels like example scenes for extensions should ship side by side with the extension?
MRTK examples should be for core / SDK, while extensions, similar to ones that might ship independent of this repo and packaging, would be more standalone.

**Comment by radicalad** [comment]
Totally valid point. I'd be happy to move everything over to appropriate Extensions folder before I open my PR. I haven't ever seen Examples anywhere other than in `MixedRealityToolkit.Examples`, including  `MRTKExamplesHub` which uses extension services.

**Comment by radicalad** [comment]
Fixed in #6563 and added to 2.2.0 release in #6571
