### ISSUE TITLE
HoloLens 2 Emulator shows only black for MRTK v2

### ISSUE THREAD

**Issue by javenu** [microsoft/MixedRealityToolkit-Unity#6566]
## Describe the bug

When I load the MRTK v2 Examples and deploy them to the Hololens2 Emulator in Visual Studio, all I see is black with the exception of the blue system menu. No amount of W A S D, arrows, or manipulation brings the 3D objects into view. I have tried using different versions of Unity, different versions of the Hololens emulator, and run on both a desktop and laptop - all variations result in black. 

## To reproduce

1. Load an MRTK v2 example project in Unity
2. Include the current scene and build to UWP
3. Open the .sln in Visual Studio and deploy to Hololens 2 emulator
4. Nothing but black in the emulator, with the exception of the blue system menu

## Expected behavior

I expect to see the MRTK 3D objects that are visible in the Unity project scene

## Screenshots

Nothing but black:
![BlackBackground](https://user-images.githubusercontent.com/26263645/68725288-ca7fb880-0572-11ea-872c-b6ca944d0744.PNG)

MRTK objects show in Unity:
![Unity objects](https://user-images.githubusercontent.com/26263645/68725908-bc329c00-0574-11ea-9f15-2d2dace26b8d.PNG)

## Your Setup (please complete the following information)

- Unity Version 2018.4.12f1
   and 
- Unity Version 2019.2.12f1
- MRTK Version 2
- MRTK Examples
- Visual Studio 2019 Community Edition

## Target Platform (please complete the following information)

- HoloLens 2 Emulator (10.0.18362.1034)
   and
- HoloLens 2 Emulator (10.0.18362.1039)

## Additional context
The same issue is occurring on two Windows 10 machines with different hardware configurations

**Comment by keveleigh** [comment]
Can you double check the `WSA Holographic Remoting Supported` checkbox in the UWP Player Settings' XR Settings please? Make sure it's unchecked:

![image](https://user-images.githubusercontent.com/3580640/68726816-817e3300-0577-11ea-83f4-5c3d811c882b.png)

I've seen this as a common cause of what you're describing.

**Comment by javenu** [comment]
Hi, thanks for the quick reply. Yes, the WSA box is unchecked on both of my dev platforms.

I read that Desktop Optimization was causing this back in 2017, but unchecking that in the Emulator Tools did not resolve the issue either. 

Is it related to scaling? Camera clipping? Ideally the MRTK would work out of the box...

**Comment by javenu** [comment]
To follow up - the newer version of the Hololens Emulator 2 (10.0.18362.1039) only shows black, I was able to get the older version of the HL2 Emulator (1034) working.
