### ISSUE TITLE
AddComponent menu cleanup

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6567]
## Describe the problem

The current AddComponent menu for scripts looks like this, unusable

![image](https://user-images.githubusercontent.com/32508825/68743925-c5168280-05f3-11ea-8b53-134855a6e1ca.png)

## Describe the solution you'd like

Using [AddComponentMenu](https://docs.unity3d.com/ScriptReference/AddComponentMenu.html) allows us to structure the components in a readable manner. This should be mandatory for all new MonoBehaviours and added to all existing ones

## Describe alternatives you've considered

Well, you have to know the component name and type it in to find it

**Comment by Troy-Ferrell** [comment]
@alexees what version of Unity are you on? You are trying "Add Component" just on a GameObject? I'm not seeing the same results

**Comment by Alexees** [comment]
> @Alexees what version of Unity are you on? You are trying "Add Component" just on a GameObject? I'm not seeing the same results

2018.4.12f1
Happens when selecting AddComponent -> Scripts

**Comment by Troy-Ferrell** [comment]
> @Alexees what version of Unity are you on? You are trying "Add Component" just on a GameObject? I'm not seeing the same results
> 
> 2018.4.12f1
> Happens when selecting AddComponent -> Scripts

I see now. I'm curious to understand the scenario, do you not just search via typing for the script component you want?

**Comment by Alexees** [comment]
Not for every script, cause I don't know them all. In my case it wanted to see what kind of solvers are available.
Of course in can look into the wiki, but to be honest, the very least is that the scripts get proper structure so I can find MY stuff within scripts more easily
