### ISSUE TITLE
ScreenSpaceMouseCursor aims in the wrong direction

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6568]
## Describe the bug

When using the ScreenSpaceMouseCursor the direction it as well as the UIRaycastCamera points towards is completely off
## To reproduce

1. Add a UnityMouseDeviceManager to the list of Input Data Providers
2. Switch the MousePointer out with the ScreenSpaceMousePointer
3. Play, aim into the scene and watch the UIRaycastCamera and the MouseCursor clone

## Expected behavior

The cursor hits where it aims to from a MainCamera perspective

## Screenshots

![image](https://user-images.githubusercontent.com/32508825/68744539-1e32e600-05f5-11ea-93e5-404be9daba46.png)

## Your Setup (please complete the following information)

- Unity Version 2018.3.12f1
- mrtk_development

## Target Platform (please complete the following information)

- Android Editor

**Comment by MenelvagorMilsom** [comment]
@Alexees would it be possible to provide some more details as so far I have been unable to repro the bug. I followed your repro steps and was still able to interact with buttons/manipulate etc. (see .gif):

![screen_space_mouse](https://user-images.githubusercontent.com/47415945/69263168-ac423a00-0bbc-11ea-922c-f549e01cc67c.gif)

It looks to me as if the cursor does hit from a MainCamera perspective, but I may be misunderstanding you.

**Comment by Alexees** [comment]
That's weird, the problem is gone on my side... I don't know what happened but I'll close this and if it happens again I'll open it up again.
