### ISSUE TITLE
Assembly has reference to non-existent assembly 'Unity.XR.ARFoundation' 

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#6576]
## Describe the bug
[2:38 PM] Yoon Park
Upgrading a personal project to the 2.2.0 stabilization branch gives me this error message:
**Assembly has reference to non-existent assembly 'Unity.XR.ARFoundation' (Assets/MixedRealityToolkit.Extensions/Providers/Experimental/UnityAR/Microsoft.MixedReality.Toolkit.Providers.UnityAR.asmdef)**

## Environment
Unity 2018.4.12f1
Deleted the original MRTK v2.1.0 folders, Library folder, copy and pasted new MRTK folders from the source clone and opened Unity.

<img width="975" alt="2019-11-13 14_38_34-Unity 2018 4 12f1 Personal - Untitled - TypeInSpace2 - PC, Mac   Linux Standalon" src="https://user-images.githubusercontent.com/13754172/68810700-ac25c580-0623-11ea-8afb-52ed082ed0c9.png">

**Comment by cre8ivepark** [comment]
Solution: #6574

**Comment by davidkline-ms** [comment]
This is related to the extensions package containing the UnityAR camera settings provider. Documentation instructions are in flight to explain what need to be added to the manifest

**Comment by davidkline-ms** [comment]
This component is no longer in the extensions package.

**Comment by davidkline-ms** [comment]
Documentation of prerequisites included in #6608
