### ISSUE TITLE
Many MRTK examples scenes show warning "GridObjectCollection on * has layout ColumnsThenRows but columns are not specified."

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#6580]
## Describe the bug

![image](https://user-images.githubusercontent.com/3580640/68812160-21df6080-0627-11ea-8da5-a655346c9fde.png)

When opening several of the examples scenes that utilize GridObjectCollection, warnings show up.
It's stated that this is `Most likely from asset upgrade to MRTK 2.2.`

We should likely do a pass on the example scenes to ensure the correct values here are written into the scene files.

## Expected behavior

No warnings in example scenes.

**Comment by keveleigh** [comment]
@julenka I think this is from your update to `GridObjectCollection`. Do you have a recommendation on how we should resolve this? Just reserialize the scenes after the asset upgrades the columns property automatically on open?

**Comment by julenka** [comment]
Hi, ah great catch! I should have opened & upgraded all the scenes.

The grid script tries to automatically re-adjust the rows/columns correctly, but it's good to check each asset just to be sure. I'll take this bug since I broke it.
