### ISSUE TITLE
Broken link in READEME_SystemKeyboard

### ISSUE THREAD

**Issue by ShayneRC** [microsoft/MixedRealityToolkit-Unity#6581]
## Describe the Issue
At the bottom of this page: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Documentation/README_SystemKeyboard.md click the OpenKeyboard.cs link and it goes to a 404.

The link goes to here: https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/OpenKeyboard.cs

## Feature Area
Should go to the cs file.

**Comment by Troy-Ferrell** [comment]
Related: #6235
