### ISSUE TITLE
MRTK OnValidate causes InputSystem to call DestroyImmediate

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6584]
## Describe the bug

The following error appears when switching between MRTK scenes:

`Destroying components immediately is not permitted during physics trigger/contact, animation event callbacks or OnValidate. You must use Destroy instead.`
```UnityEngine.Object:DestroyImmediate(Object)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Destroy() (at Assets/MixedRealityToolkit/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs:346)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:UnregisterService(IMixedRealityInputSystem) (at Assets/MixedRealityToolkit/MixedRealityToolkit/Services/MixedRealityToolkit.cs:264)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:UnregisterService(String) (at Assets/MixedRealityToolkit/MixedRealityToolkit/Services/MixedRealityToolkit.cs:253)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:DestroyAllServices() (at Assets/MixedRealityToolkit/MixedRealityToolkit/Services/MixedRealityToolkit.cs:980)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean) (at Assets/MixedRealityToolkit/MixedRealityToolkit/Services/MixedRealityToolkit.cs:708)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:OnValidate() (at Assets/MixedRealityToolkit/MixedRealityToolkit/Services/MixedRealityToolkit.cs:1428)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

```

## To reproduce

1. Create and save a scene with MRKT and default profile
2. Create another scene with MRKT and profile without saving it (asterisk should be visible)
3. Open the saved MRTK scene
observe the console

## Expected behavior

No error

## Your Setup (please complete the following information)

- Unity Version 2018.3.12f1
- mrtk_development

## Target Platform (please complete the following information)

- Editor

**Comment by davidkline-ms** [comment]
Looking at the history of this code, this issue is not new (it has been present since before 2.0.0).
