### ISSUE TITLE
Content is obscure

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#6585]
## Describe the bug
Sometimes it is obscure in Hololens ,but sometimes it is clear。
The map of mapbox  nad other 3D models are obscure in hololens , but it is clear in Unity3D editor while hololens remote by wifi. 

## Your Setup (please complete the following information)

- Unity Version [e.g. 2019.2.6f1]
- MRTK Version [e.g. v2.1]

## Target Platform (please complete the following information)

- HoloLens

**Comment by Troy-Ferrell** [comment]
@IfnoLee can you elaborate more what you mean? Or better yet provide media examples? It is not clear what you are saying is wrong

**Comment by wiwei** [comment]
Closing this out as there isn't enough information here to act on - feel free to reopen with more details!
