### ISSUE TITLE
"Select" MixedRealityInputAction does not raise the "OnGestureStarted"

### ISSUE THREAD

**Issue by siamonas** [microsoft/MixedRealityToolkit-Unity#6586]
## Describe the bug

When implementing the IMixedRealityGestureHandler interface, four (4) functions:
- OnGestureStarted
- OnGestureUpdated
- OnGestureCompleted
- OnGestureCanceled

I'm trying to catch the exact moment the "Select" action is started. All other input actions (hold, manipulation and navigation) are triggered, only "select" action doesn't raise the "OnGestureStarted".

## To reproduce

1. Write a C# script that implements the IMixedRealityGestureHandler interface
2. Attach the script to a GameObject
3. Run the scene
4. Debug on the "OnGestureStarted" function

## Expected behavior

When I start the "Select" action, "OnGestureStarted" should be called.

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.4.12f1]
- MRTK Version [e.g. v2.1.0]

**Comment by keveleigh** [comment]
>When I start the "Select" action, "OnGestureStarted" should be called.

I think at the moment, it only fires `OnGestureCompleted`. Would you expect a started event and immediate completed event, since a tap doesn't really have a time length component to it?
