### ISSUE TITLE
HandInteractionUnityUIExample WMR slate text display issue

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#6592]
## Describe the bug

![UnityUISlateExampleScene](https://user-images.githubusercontent.com/53493796/68897759-fde15500-06e2-11ea-9896-f3f676db06ad.gif)

## To reproduce

1. Switch platform to UWP
2. Plug in WMR headset
3. Run the HandInteractionUnityUIExample scene in the editor
4. Click through the UI Elements with the VR controllers 

## Your Setup (please complete the following information)

- Unity Version 2018.4.11
- MRTK Version v2.2.0

## Target Platform (please complete the following information)
- WMR immersive

**Comment by thalbern** [comment]
happens on hl2 as well

**Comment by ritijain** [comment]
looks like a z-fighting issue. I will take a look

**Comment by ritijain** [comment]
Tagging a few UX folks - @thalbern , @CDiaz-MS , @julenka , @cre8ivepark 

I see two example scenes - HandInteractionUnityUIExample.scene and HandInteractionExample scene with very similar content (the same scroll-able Unity UI panel exists in both) . Is there a reason HandInteractionUnityUIExample exists independent of what we see in HandInteractionExample  ? I would propose removing HandInteractionUnityUIExample and just using HandInteractionExample scene as the showcase. Thoughts?

**Comment by julenka** [comment]
I would be fine with removing unnecessary example scenes. This brings up another question for @cre8ivepark  and @wiwei — what principles should we use when deciding on whether to add an example? What’s our plan for pruning  out unnecessary or duplicate examples?
