### ISSUE TITLE
ProgressIndicatorRotatingOrbs generates error messages

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#6593]
## Describe the bug
ProgressIndicatorRotatingOrbs generates error messages when the state is changed to 'Opening'. Animation does not start.

NullReferenceException: Object reference not set to an instance of an object
Microsoft.MixedReality.Toolkit.UI.ProgressIndicatorOrbsRotator.Update () (at Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/ProgressIndicators/ProgressIndicatorOrbsRotator.cs:148)

## Expected
The orb rotating animation without errors

## To reproduce
1. Create a new scene
2. Drag and drop ProgressIndicatorRotatingOrbs.prefab into the scene
3. Change the State to 'Opening' in the Inspector.
4. Run

<img width="422" alt="2019-11-14 14_25_00-Unity 2018 4 12f1 Personal -  PREVIEW PACKAGES IN USE  - Untitled - MixedReality" src="https://user-images.githubusercontent.com/13754172/68901496-e5753880-06ea-11ea-9366-b993a6522a0f.png">

<img width="889" alt="2019-11-14 14_25_08-Unity 2018 4 12f1 Personal -  PREVIEW PACKAGES IN USE  - Untitled - MixedReality" src="https://user-images.githubusercontent.com/13754172/68901503-e7d79280-06ea-11ea-9423-66a07f65144c.png">

<img width="1517" alt="2019-11-14 14_24_58-Unity 2018 4 12f1 Personal -  PREVIEW PACKAGES IN USE  - Untitled - MixedReality" src="https://user-images.githubusercontent.com/13754172/68901513-e9a15600-06ea-11ea-8457-29ec23a1a075.png">

**Comment by radicalad** [comment]
Looks like these Loaders are specific to the Scene Transition service. IMO they should be moved to the appropriate namespace and folders.

`IProgressIndicator` assumes it will be Enabled via the `Task` `OpenAsync()`. Controlling it manually will fail as those hooks are specific to the Transition Service. We could certainly make it work generically, but we already have a HL2 parity indeterminate loader in UX/Prefabs. `IndeterminateLoader`. @Railboy should we move these loaders to be more closly coupled with the extension service?

**Comment by radicalad** [comment]
Looking deeper, `IProgressIndicator ` is a part of SDK. We could mitigate this if we want to keep it separated from the Scene Transition service (as it is currently), by including a inspector textbox explaining the intent of these scripts/prefabs and hiding the `state` property from the inspector. At least that way if its added to a scene, it will gracefully fail with explanation of how to use it, versus right now where its possible to break it by setting the state manually.

**Comment by Railboy** [comment]
@radicalad Yeah since this is a release blocker I think we should take the path of least resistance for now.

>Looks like these Loaders are specific to the Scene Transition service. IMO they should be moved to the appropriate namespace and folders.

I honestly couldn't remember why we put them in SDK and had to dig up some old issues. I'm fine with keeping them in SDK, but if we do so we should discuss how to make them more drag-and-drop friendly for a later release. Additional context: #3899, #5034, #4355
