### ISSUE TITLE
OnPreSceneQuery Null Ref Error

### ISSUE THREAD

**Issue by lordlycastle** [microsoft/MixedRealityToolkit-Unity#6595]
## Describe the bug
I keep getting following error when running on hololens. 

```
NullReferenceException: Object reference not set to an instance of an object.
Microsoft.MixedReality.Toolkit.Input.GGVPointer.OnPreSceneQuery () (at <00000000000000000000000000000000>:0) 
Microsoft.MixedReality.Toolkit.Input.FocusProvider.UpdatePointer (Microsoft.MixedReality.Toolkit.Input.FocusProvider+PointerData pointer) (at <00000000000000000000000000000000>:0) 
Microsoft.MixedReality.Toolkit.Input.FocusProvider.UpdatePointers () (at <00000000000000000000000000000000>:0) 
Microsoft.MixedReality.Toolkit.Input.FocusProvider.Update () (at <00000000000000000000000000000000>:0) Microsoft.MixedReality.Toolkit.MixedRealityToolkit+<>c.<UpdateAllServices>b__68_0 (Microsoft.MixedReality.Toolkit.IMixedRealityService service) (at <00000000000000000000000000000000>:0) System.Action`1[T].Invoke (T obj) (at <00000000000000000000000000000000>:0) 
Microsoft.MixedReality.Toolkit.MixedRealityToolkit.ExecuteOnAllServices (System.Action`1[T] execute) (at <00000000000000000000000000000000>:0) 
Microsoft.MixedReality.Toolkit.MixedRealityToolkit.Update () (at <00000000000000000000000000000000>:0)

```

## To reproduce
 Use toolkit and build project. 

## Expected behavior

The error should not be printed constantly.

## Your Setup (please complete the following information)

- Unity Version 2019.1.14f1
- MRTK Version RC 2.1

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by Troy-Ferrell** [comment]
@lordlycastle, are you able to update your MRTK version and try again? MRTK Version RC 2.1 is pretty old now. Thanks!

**Comment by wiwei** [comment]
Closing this old issue out - I think that this is basically this one:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5494

The tricky part is that we haven't really seen this recently and we've made a ton of changes to the MRTK since this was originally filed.

If folks are still seeing this I think that attaching some min repro would go a long way to figuring out what's going on.
