### ISSUE TITLE
MRTK2 hand cursor does not target objects

### ISSUE THREAD

**Issue by javenu** [microsoft/MixedRealityToolkit-Unity#6604]
## Describe the bug

None of the objects in MRTK2 receive the hand cursor target in Unity Play mode, in spite of following the HL2 turorials, adding the appropriate scripts, configuring Input Simulation, etc. At this point, the Hololens 2 tutorials are a nice intro to 3D modeling in Unity but without the cursor targeting + interaction in play mode, they aren't very helpful.

## To reproduce

1. Follow the Hololens2 Getting Started tutorials: [LINK](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base)
2. Complete all 6 steps, including adding necessary touch interaction scripts
3. Launch Unity in Play mode
4. None of the objects receive the hand cursor. The cursor goes in front or behind the objects, irregardless of how close / far the hand + pointer ray is
5. Even changed the pointer from a Bezier to a Parabola, still no targeting: [Guidance](https://stackoverflow.com/questions/56244033/how-can-i-change-hand-rays-in-my-mrtk-v2-project-for-hololens-2-to-parabolic-ins)
6. Also configured the Input Simulation service per the API Documentation, but no go [HERE](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSimulation/InputSimulationService.html)

## Expected behavior

Objects should receive target from hand pointer

## Screenshots

Pointer never connects to objects
![objects without targeting](https://user-images.githubusercontent.com/26263645/68977547-5715bb00-07ad-11ea-9303-ebf02c303988.png)

## Your Setup (please complete the following information)

- Unity Version 2019.2.12f1
- MRTK Version 2

## Target Platform (please complete the following information)

- HoloLens 2 (I am running in Unity, not deploying to Hololens)

**Comment by Troy-Ferrell** [comment]
@javenu , thanks for filing this.

Are you able to share your Untiy project somehow?

Do the example scenes with MRTK work for you? (i.e HandsINteractionExample scene)

If you do the following, does it work
1) Create a new scene
2) MRTK > Add to scene and configure
3) Select DefaultHololens2ConfigurationProfile in MRTK profile object
4) Add "PressableButtonHololens2" prefab into scene or for maybe "RadialSet" prefab (search in assets and should be in SDK package)
5) Click play and use input simulation hands to click them

**Comment by javenu** [comment]
Hi @Troy-Ferrell , thanks for the quick response!

Yes, I loaded the HandInteractionExamples from the toolkit and was able to play Mary Had a Little Lamb on the piano. Also created a scene with the pressable button and radial buttons - both worked. 

I have included a link to the Unity project that I built for the tutorial - also includes the recent test scene. I will take another look at the tutorial scene on my end. Note: you will see the parabolic pointer, but it works fine w/ the HL2 buttons.

[Unity project](https://1drv.ms/u/s!AkJkbbWJYJOigYAoS6NlXIexqI2paw?e=HkSjhJ) (127Mb)

**Comment by Troy-Ferrell** [comment]
Your scene worked for me by
Deleting duplicated MixedRealityPlayspace/camera
Turning off the cube solver
Reverting the DefualtControllerPointer prefab to original shipped with MRTK

Only component that did not respond was the yellow diamond...which worked once I enabled far manipulation on the maniuplationhandler

**Comment by javenu** [comment]
Thank you, it looks like the duplicated Playspace/camera was the primary culprit. 
I'm not sure how/when that snuck in there, but great learning opty for me :)

Thank you for taking a look and helping resolve this!
