### ISSUE TITLE
CheckCapability(MixedRealityCapability.SpatialAwarenessMesh) always return false on HoloLens 1

### ISSUE THREAD

**Issue by satoshi-maemoto** [microsoft/MixedRealityToolkit-Unity#6613]
## Describe the bug

WindowsMixedRealitySpatialMeshObserver.CheckCapability(MixedRealityCapability.SpatialAwarenessMesh) always return false on HoloLens1

cause is capability check runs on UniversalApiContract v8 environment only.
Hololens 1 is UniversalApiContract v7.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/2c711ab4d9f059fa0b12761a10188a051c7785b4/Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs#L88

if change UniversalApiContractV8_IsAvailable to UniversalApiContractV7_IsAvailable above source, runs fine on HoloLens 1.

but I'm not sure that is currrectly..

## Environment

- Unity Version [2019.2.12f1]
- MRTK Version [v2.1.0]

## Target Platform

- HoloLens

**Comment by Troy-Ferrell** [comment]
@keveleigh FYI who has good knowledge in this area

**Comment by julenka** [comment]
This is a code defect, marking consider for next and putting in 2.3

**Comment by davidkline-ms** [comment]
Great find @satoshi-maemoto!

**Comment by davidkline-ms** [comment]
fixed in 2.3.0 (current the mrtk_development branch) by #6884.
