### ISSUE TITLE
MixedRealityToolkit.Staging folder is missing version, license files....and explanation of what it is

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6624]
## Overview
In 2.2 prerelease there is a new MRTK folder MixedRealityToolkit.Staging. Apart from being another folder to manage (@wiwei it would be good to provide guidance / principles around "do we add folders"), it is unclear why we have this folder. I don't see it mentioned in any documentation.

The folder is also missing version and license text files, though these exist for all other files.

**Comment by keveleigh** [comment]
Ah, looks like the license and version files ended up a level lower, in the UnityAR folder

**Comment by davidkline-ms** [comment]
> Ah, looks like the license and version files ended up a level lower, in the UnityAR folder

They did as that is the folder that is ultimately packaged.

**Comment by davidkline-ms** [comment]
The addition of the staging folder was in relation to @Alexees' comment in #6574 re: not forcing customers to include AR Foundation (they were required if they imported the complete Extensions package).

Initial (not complete) documentation was added in #6608. Additional documentation work is in progress and will be included as part of the Getting Started page.

**Comment by davidkline-ms** [comment]
> In 2.2 prerelease there is a new MRTK folder MixedRealityToolkit.Staging. Apart from being another folder to manage (@wiwei it would be good to provide guidance / principles around "do we add folders"), it is unclear why we have this folder.

In an offline discussion with @wiwei and @keveleigh, it was debated whether we should create an individual top level folder for the UnityAR provider to avoid it being included in one of the core packages (Foundation or Extensions). @wiwei suggested we create a top level staging folder to contain this provider (and future components that may have specific requirements) while we transition our packaging process^ to support providing components individually).

^ Note: There is a limitation of Unity's command line packaging tooling that does not allow inclusion of individual files. In a future release, we will work around this issue and enable ourselves to remove the top level staging folder.

**Comment by wiwei** [comment]
FWIW, I think that what's missing here is a README.md or something in that folder explaining the purpose of it and how it's intended to be temporary.

**Comment by wiwei** [comment]
Or rather, temporary is a bad word - it's literally meant to stage a change that would be too risky to do this week, and have the right work done in the next iteration. We shouldn't be making additional changes to anything in that folder and the next move should be to put it back to where it was at (and add the proper packaging support in the process)

**Comment by julenka** [comment]
> FWIW, I think that what's missing here is a README.md or something in that folder explaining the purpose of it and how it's intended to be temporary.

Yes! That's exactly what I was hoping to find in the folder. Normally I look for READMEs first to understand what something is, even before trying to find release notes, or the "Getting started" page.

**Comment by julenka** [comment]
> it's literally meant to stage a change that would be too risky to do this week, and have the right work done in the next iteration. We shouldn't be making additional changes to anything in that folder and the next move should be to put it back to where it was at (and add the proper packaging support in the process)

What's the difference between "staging" and "experimental"?

**Comment by davidkline-ms** [comment]
Staging was a way to specifically separate out the UnityAR component from the extensions package due to the risky change mentioned by @wiwei and the dependencies that we cannot assert in unitypackage files.

**Comment by davidkline-ms** [comment]
It could be called experimental, though in that case, we may wish to move all experimental work there which could cause a large amount of churn and not solve the issue with dependencies.
