### ISSUE TITLE
"Failed to unload 'Assets/MixedRealityToolkit.Staging/UnityAR/Profiles/DefaultUnityARCameraSettingsProfile.asset'"

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6625]
## Overview
Upon opening the latest mrtk 2.2.0 package, I see a message saying "Failed to unload 'Assets/MixedRealityToolkit.Staging/UnityAR/Profiles/DefaultUnityARCameraSettingsProfile.asset'"

## Expected Behavior
There should be no error when opening a unity project with MRTK

## Steps to reproduce
Open a unity project that is synced to prerelease/stabilization_2.2.0

## Unity Editor Version
2018.4.12f1

## Mixed Reality Toolkit Release Version
prerelease/stabilization_2.2.0

**Comment by julenka** [comment]
@keveleigh I assigned to  @davidkline-ms because it is about the ar foundation feature, just FYI.

**Comment by davidkline-ms** [comment]
Interesting... i havent seen that error. will investigate asap

**Comment by davidkline-ms** [comment]
I am not seeing an error when loading from the repository (multiple fresh and older clones). 

@julenka, Are you seeing this with package files or the repository?

**Comment by julenka** [comment]
I saw it with repository.

**Comment by davidkline-ms** [comment]
Thanks @julenka. I have tried that as well as importing packages without successfully reproducing this issue. If you see it again, please let me know.
