### ISSUE TITLE
Supersaturated colors

### ISSUE THREAD

**Issue by ChristophHoltmann** [microsoft/MixedRealityToolkit-Unity#6630]
## Describe the bug

I use the MRTK standard shader in my scene. Everything looks good in the Unity editor, but when I build the project, all the colors are way too colorful.

## To reproduce

I'm not sure, but it might have something to do with the LWRP. I can not test this for my project because I can not fix the current bad state.
I've tried to test it on a new project, but I can not click on the "Update Mixed Reality Toolkit / Utilities / MRTK S... Pipeline" button (grayed out).

## Expected behavior

The materials rendered using the HoloLens device should resemble the materials rendered in the Unity Scenes window.

## Your Setup (please complete the following information)

- Unity Version 2019.2.9f1
- MRTK Version v2.1.0 NuGet

Project Settings/Player/XR Settings:
- Depth Format: 16-bit
- Enabled Depth Buffer Sharing: enabled
- Rendering Mode: Single Pass Instanced

## Target Platform (please complete the following information)

- HoloLens

**Comment by Railboy** [comment]
@ChristophHoltmann Do you think you could take some captures on your device / in editor for comparison?

**Comment by ChristophHoltmann** [comment]
Hi @Railboy thank you for your fast response! 
Here are some pictures:
![image](https://user-images.githubusercontent.com/6481647/69171995-480c7100-0afd-11ea-937a-946fc11958fc.png)
![20191119_183730_HoloLens](https://user-images.githubusercontent.com/6481647/69172035-5d819b00-0afd-11ea-9532-7068cafaf9c3.jpg)
![image](https://user-images.githubusercontent.com/6481647/69172052-68d4c680-0afd-11ea-8de5-748319363e11.png)
![image](https://user-images.githubusercontent.com/6481647/69172172-a2a5cd00-0afd-11ea-9650-c308db4480ea.png)
![image](https://user-images.githubusercontent.com/6481647/69172285-d5e85c00-0afd-11ea-86d6-53febc3fb507.png)
![image](https://user-images.githubusercontent.com/6481647/69172298-dda80080-0afd-11ea-9011-b2e28960c8af.png)

Hope this helps.

**Comment by ChristophHoltmann** [comment]
The problem looks similar to the followign bug reports:

**Comment by ChristophHoltmann** [comment]
The problem looks similar to the following bug reports:

**Comment by Railboy** [comment]
@ChristophHoltmann What color space is your project using?

**Comment by ChristophHoltmann** [comment]
@Railboy This is the perfect question!
I was able to fix it an hour ago by using "gamma" color space. It is a hack, but it works ;)
These issues might look similar to the problem I had:
https://issuetracker.unity3d.com/issues/lwrp-android-scene-is-rendered-darker-in-build-when-graphics-api-set-to-gles3-and-color-space-set-to-linear
https://issuetracker.unity3d.com/issues/lwrp-android-lighweight-scene-is-noticeably-darker-when-building-application-with-gles3-on-android-9-device

**Comment by ChristophHoltmann** [comment]
https://forum.unity.com/threads/sprite-images-too-dark-with-burnt-colors.264459/
