### ISSUE TITLE
InteractableExamples scene missing voice commands, back panel, and sounds

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6632]
## Describe the bug
 found few issues with interactable scene:
 
1) Cannot turn off profiler via 'toggle profiler' (annoying, not major but nice to fix)
2) Ray shoots through back panel

![image](https://user-images.githubusercontent.com/168492/69172546-df000b80-0ab2-11ea-931e-ccc50f923f59.png)

3) Some interactables play sound on click, others do not (inconsistent)

To fix:
1) Interactable_SpeechCommandsProfile needs the keywords
2) Backpanels don't have any colliders
3) self-obvious, just need to add onclicks

**Comment by ritijain** [comment]
@julenka is 1 above indicating the toggleability of the diagnostics panel?

**Comment by julenka** [comment]
Yes I cannot say toggle profiler or press 0 to turn off the profiler in that scene

Sent from phone, please excuse typos.
________________________________

**Comment by davidkline-ms** [comment]
Splitting the "toggle profiler" command into a separate issue.
