### ISSUE TITLE
Undefined symbols for architecture arm64, IOS build issue

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#6646]
## Describe the bug

Build for IOS fails:
`Undefined symbol: void RegisterUnityClass<WorldAnchor>(char const*)`

```
Undefined symbols for architecture arm64:
  "void RegisterUnityClass<WorldAnchor>(char const*)", referenced from:
      RegisterAllClasses() in UnityClassRegistration.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

<img width="867" alt="Screen Shot 2019-11-19 at 3 32 51 PM" src="https://user-images.githubusercontent.com/53493796/69195938-ef7baa80-0ae1-11ea-90ef-1c44877dbc73.png">

## To reproduce

1. Open Unity on a Mac
2. Import all MRTK packages
3. Switch platform to IOS
4. Add HandInteractionExample
5. Open Xcode solution
6. Click play button in the corner of Xcode to run

## Your Setup (please complete the following information)

- Unity Version 2018.4.12
- MRTK Version v2.2

## Target Platform (please complete the following information)
- IOS

**Comment by CDiaz-MS** [comment]
To fix:
Player Settings > Other Settings > Under Optimization, uncheck Strip Engine Code

**Comment by Ahmadre** [comment]
> Current short term fix:
> Player Settings > Other Settings > Under Optimization, uncheck Strip Engine Code

Not working for me... same error

**Comment by Jovisx** [comment]
I have the same error and doesn't work for me

Unity: 2020
Xcode: 12
iOS: 13

the log


Ld /Users/wakeapp/Library/Developer/Xcode/DerivedData/Unity-iPhone-bgkeiyryrwcvrccxlmumqgfpqtzi/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework normal arm64
    cd /Users/wakeapp/Desktop/Survival/iOSBuild
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios11.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk -L/Users/wakeapp/Library/Developer/Xcode/DerivedData/Unity-iPhone-bgkeiyryrwcvrccxlmumqgfpqtzi/Build/Products/ReleaseForRunning-iphoneos -L/Users/wakeapp/Desktop/Survival/iOSBuild/Libraries -F/Users/wakeapp/Library/Developer/Xcode/DerivedData/Unity-iPhone-bgkeiyryrwcvrccxlmumqgfpqtzi/Build/Products/ReleaseForRunning-iphoneos -F/Users/wakeapp/Desktop/Survival/iOSBuild/Frameworks/com.unity.ads/Plugins/iOS -filelist /Users/wakeapp/Library/Developer/Xcode/DerivedData/Unity-iPhone-bgkeiyryrwcvrccxlmumqgfpqtzi/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -map -Xlinker /Users/wakeapp/Library/Developer/Xcode/DerivedData/Unity-iPhone-bgkeiyryrwcvrccxlmumqgfpqtzi/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-arm64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/wakeapp/Library/Developer/Xcode/DerivedData/Unity-iPhone-bgkeiyryrwcvrccxlmumqgfpqtzi/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_lto.o -fembed-bitcode-marker -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -liPhone-lib -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp /Users/wakeapp/Desktop/Survival/iOSBuild/Libraries/baselib.a -framework UnityAds -framework AdSupport -framework CoreTelephony -framework StoreKit -weak_framework Metal -weak_framework GameController -Xlinker -dependency_info -Xlinker /Users/wakeapp/Library/Developer/Xcode/DerivedData/Unity-iPhone-bgkeiyryrwcvrccxlmumqgfpqtzi/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_dependency_info.dat -o /Users/wakeapp/Library/Developer/Xcode/DerivedData/Unity-iPhone-bgkeiyryrwcvrccxlmumqgfpqtzi/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework

Undefined symbols for architecture arm64:
  "_IsMobile", referenced from:
      _WebGLTool_IsMobile_mFFE4B63D41AE02D2C9CACFE416F862B9C4545F9D in Assembly-CSharp2.o
     (maybe you meant: _WebGLTool_IsMobile_mFFE4B63D41AE02D2C9CACFE416F862B9C4545F9D, _TheGame_IsMobile_m54D560BF2D22C1F61BC924A6ADBF744EDC815120 )
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
