### ISSUE TITLE
Misleading property name BoundingBox class

### ISSUE THREAD

**Issue by NULLt1** [microsoft/MixedRealityToolkit-Unity#6656]
## Describe the problem

The property RotationHandleSlatePrefab in the BoundingBox class is misleading cause the variable name is rotationHandlePrefab.

```csharp
        [SerializeField]
        [Tooltip("Prefab used to display rotation handles in the midpoint of each edge. Aligns the Y axis of the prefab with the pivot axis, and the X and Z axes pointing outward. If not set, spheres will be displayed instead")]
        private GameObject rotationHandlePrefab = null;

        /// <summary>
        /// Prefab used to display rotation handles in the midpoint of each edge. Aligns the Y axis of the prefab with the pivot axis, and the X and Z axes pointing outward. If not set, spheres will be displayed instead
        /// </summary>
        public GameObject RotationHandleSlatePrefab
        {
            get { return rotationHandlePrefab; }
            set
            {
                if (rotationHandlePrefab != value)
                {
                    rotationHandlePrefab = value;
                    CreateRig();
                }
            }
        }
```

## Describe the solution you'd like

Change the name of RotationHandleSlatePrefab to RotationHandlePrefab.

## Describe alternatives you've considered

-

## Additional context

I encountered the problem because i wanted to assign a new value to the variable.

**Comment by keveleigh** [comment]
@NULLt1 Did you mean to close this issue?

**Comment by keveleigh** [comment]
Oh I see, you opened #6657 instead.

**Comment by NULLt1** [comment]
@keveleigh Sorry for the mess, this is the first issue I opened.

**Comment by keveleigh** [comment]
@NULLt1 No worries at all! I didn't notice I had clicked on two different issues from my emails and wanted to make sure this was still tracked!
