### ISSUE TITLE
Misleading property name in BoundingBox class

### ISSUE THREAD

**Issue by NULLt1** [microsoft/MixedRealityToolkit-Unity#6657]
## Describe the problem

The property RotationHandleSlatePrefab in the BoundingBox class is misleading cause the variable name is rotationHandlePrefab.

```csharp
        [SerializeField]
        [Tooltip("Prefab used to display rotation handles in the midpoint of each edge. Aligns the Y axis of the prefab with the pivot axis, and the X and Z axes pointing outward. If not set, spheres will be displayed instead")]
        private GameObject rotationHandlePrefab = null;

        /// <summary>
        /// Prefab used to display rotation handles in the midpoint of each edge. Aligns the Y axis of the prefab with the pivot axis, and the X and Z axes pointing outward. If not set, spheres will be displayed instead
        /// </summary>
        public GameObject RotationHandleSlatePrefab
        {
            get { return rotationHandlePrefab; }
            set
            {
                if (rotationHandlePrefab != value)
                {
                    rotationHandlePrefab = value;
                    CreateRig();
                }
            }
        }
```

## Describe the solution you'd like

Change the name of RotationHandleSlatePrefab to RotationHandlePrefab.

## Describe alternatives you've considered

-

## Additional context

I encountered the problem because i wanted to assign a new value to the variable.

**Comment by cre8ivepark** [comment]
I think this prefab asset is the handle for the 2D

**Comment by Pycorax** [comment]
I've just run into this issue as well. May I suggest an update to the Bounding Box documentation for now, to indicate that the `RotationHandleSlatePrefab` is actually using `rotationHandlePrefab` as a backing field and that there is no actual slate rotation handle?
