### ISSUE TITLE
Docs on Building NuGet Packages Correct?

### ISSUE THREAD

**Issue by mtaulty** [microsoft/MixedRealityToolkit-Unity#6658]
## Describe the Issue
If I follow the docs [here](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/MRTKNuGetPackage.html) to attempt to build the NuGet packages as described in [this section](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/MRTKNuGetPackage.html#locally-building-the-nuget-package) then I don't have any success.

I have not managed to get to the bottom of this at the time of writing but it seems like the file [BuildSource.proj](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/NuGet/BuildSource.proj) has a hardcoded reference to Visual Studio 2017 Enterprise Edition. I'm running on Visual Studio 2019 so that doesn't seem to work for me.

Further, if I correct this then I seem to get into a problem where MSBuild is picking up Visual Studio as V15.0 rather than V16.0. 

I'm unsure whether this is just my system but it'd be good to perhaps have the document talk through in a little more detail how to get this to work as I've spent maybe 2 hours on it this morning and I don't have it working.

The specific error I end up with is relating to MSBuild not being able to import XAML tagets into any of the .csproj files that are generated by the Unity build process.

## Feature Area
As above - building NuGet packages to allow for local debugging of the MRTK when packaged as NuGet packages

## Existing Doc Link
As above

## Additional context
N/A

**Comment by keveleigh** [comment]
@andreiborodin?
