### ISSUE TITLE
World Anchor and tap to placement

### ISSUE THREAD

**Issue by TinyTangS** [Microsoft/MixedRealityToolkit-Unity#666]
I just want to build a scene like this,but I have several problems: 
1. tap my finger in the real world, there will be a cube Instantiated at the cursor hit point; but when I want to instantiate more cube , the cube position wasn't the cursor hit point, them were at the previous cube position. I tried to disable  "World Anchor Manager.cs"and "Tap To Place.cs"  in unity ,there were what I wanted, but I cannot tap and place the cube any more;
2. tap my finger on the cube (which was instantiated),that I can put it any where I wanted in the real world.SomeTimes they worked not very well, you should restart the scene several times that can worked well;
3. placed the cube,adjusted the button on UI to controll the cube to move to every directions and rotate to every directions;but when I click the button ,there is no reaction,I had tried disabled the "World Anchor Manager.cs"and "Tap To Place.cs" after placed the cube,  but the button was no reaction either;
4.when I used model with a big scale (the count is only one),the machine running very card; but when I do it as the Academy Holograms 101, without holotoolkit 1.5.6 ,there is no problem;
PS: you can _also_ contact with me by email anger37@sohu.com

**Comment by TinyTangS** [comment]
Is there anybody who can help me ?

**Comment by Ziugy** [comment]
Do you have a sample scene and repository we may view to help debug your issues?

**Comment by TinyTangS** [comment]
@Ziugy   May I get you email adress ,I will send you what I had built project.

**Comment by Ziugy** [comment]
I would prefer a public fork or repository so that others may be able to help diagnose the issue too. This would also help others who may be running into similar issues. Thank you very much!

**Comment by TinyTangS** [comment]
@Ziugy OK, I had push my project into github. the adress is https://github.com/TinyTangS/test.  Thanks very much.

**Comment by StephenHodgson** [comment]
Related to https://github.com/Microsoft/HoloToolkit-Unity/issues/567

**Comment by TinyTangS** [comment]
Thanks very much! The issue of #567 can solve the first and second problem. How about the others? I also read #571 .But when the customer wanna use tap to place for put the cube,and then use the button to adjust the cube position very accurate.For this moment need I clear the anchor store after it placed? if I clear the anchor store but the customer wanna tap to place the cube again, Am I need add the anchor store?  I think that is very complicate. Is there any way to deal with it?

**Comment by StephenHodgson** [comment]
Pretty sure the script was updated to use this.
