### ISSUE TITLE
Shader error in 'Mixed Reality Toolkit/Standard' after ARKit XR Plugin import

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#6662]
## Describe the bug

On import of the ARKit XR Plugin package via UPM causes this shader error on a Mac:

```
Shader error in 'Mixed Reality Toolkit/Standard': Program 'frag', error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Incompatible min precision type for operand #3 of opcode #49 (counts are 1-based). Expected int or uint. (on metal)

Compiling Fragment program with UNITY_PASS_FORWARDBASE _CLIPPING_PLANE _CLIPPING_SPHERE _CLIPPING_BOX _DISABLE_ALBEDO_MAP _ROUND_CORNERS _IGNORE_Z_SCALE
Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF3 SHADER_API_MOBILE UNITY_HARDWARE_TIER1 UNITY_COLORSPACE_GAMMA UNITY_LIGHTMAP_DLDR_ENCODING
```

## To reproduce

1. On a Mac, import all MRTK packages
2. Import AR Foundation preview 6 - Window > Package Manager > Advanced > Show Preview Packages
3. Import ARKit XR Plugin

## Screenshots

<img width="1368" alt="Screen Shot 2019-11-20 at 10 17 10 AM" src="https://user-images.githubusercontent.com/53493796/69265898-fa384d00-0b7e-11ea-9446-d7d19ef38e2f.png">

## Your Setup 

- Unity Version 2018.4.12
- MRTK Version v2.2

## Target Platform 
- iOS

**Comment by Alexees** [comment]
Duplicate of #6359
