### ISSUE TITLE
Manipulate Object Material After Speech Command

### ISSUE THREAD

**Issue by Pratt-Eric** [microsoft/MixedRealityToolkit-Unity#6672]
## Describe the bug

If I have code in a script to change the material of an object and that code is called using speech recognition, if I tap on the object itself or interact with it in anyway (i.e. drag, size, etc) or if I tap on anything that is not interactable, it will execute the same code every time I tap.

## To reproduce

Using Unity 2019.2.12f1
1. Create new project
2. Import all MRTK unity packages available
3. Add Mixed Reality Toolkit to the scene
4. Go to build settings and Player Settings to add XR Settings, check "Virtual Reality Supported and add "Windows Mixed Reality" and check ''Vuforia Augmented Reality Supported"
5. I switched to UWP, but I don't know if that's important to duplicate the bug
6. Add a cube to the 3d space and a "PressableButtonHoloLens2.prefab"button
7. Select the PressableButtonHololens2 button
8. Under the Interactable script portion, uncheck "Requires Focus"
9. Create a script and a function that will toggle between two different materials. (Actual script I was using is included in the "Additional context" section
10. For the OnClick() event of the PressableButtonHoloLens2 button, call the function of the script
11. Run program
12. While holding space, click on the button to make sure the object toggles back and forth with the different materials, then click around the object to confirm that it does not change back and forth.
13. Now say the command out loud while looking anywhere and confirm that the object has changed.
14. Now repeat tapping anywhere else regardless of where your gaze is and watch the material toggle back and forth.

## Expected behavior

I did not expect the material to change by dragging the object around (when it had a bounding box and manipulation handler on it, etc). I did not expect it to change when tapping literally anywhere else where there wasn't a handler to catch the event of the tap.

I was expecting the object to remain the same as it was with no change.

## Screenshots

N/A

## Your Setup (please complete the following information)

- Unity Version 2019.2.12f1
- MRTK Version v2.1.0

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

## Additional context

Here's the script I was using:
public class DoTheThingsScript : MonoBehaviour
{
    [SerializeField]
    private GameObject cube;
    [SerializeField]
    private Material mat;
    private Material original;
    private bool toggled = false;
    void Start()
    {
        original = cube.GetComponent<MeshRenderer>().material;
    }

    public void DoTheThings()
    {
        toggled = !toggled;
        if (toggled)
        {
            cube.GetComponent<MeshRenderer>().material = mat;
        }
        else
        {
            cube.GetComponent<MeshRenderer>().material = original;
        }
    }
}
I've attached the a zipped folder of my exported package from unity. I only included my scene and script. After you add the MRTK packages, import that one and I believe it should work.
[Package.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3871907/Package.zip)

**Comment by Pratt-Eric** [comment]
I've attached the a zipped folder of my exported package from unity. I only included my scene and script. After you add the MRTK packages, import that one and I believe it should work.

[Package.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3871899/Package.zip)

**Comment by Pratt-Eric** [comment]
I've found it can only be duplicated if you do not have "Requires Focus" checked under "Interactable"

If I change Speech Command to "(No Selection)" and add a separate "Speech Input Handler" script, uncheck "Is Focus Required", choose my keyword, and select a response accordingly it doesn't have an issue. I'm using that as a work around until this can be fixed.

**Comment by Troy-Ferrell** [comment]
@Pratt-Eric I believe this is fixed in the stabilization branch for 2.2 release which will come out soon. We did a lot of work and fixes between 2.1 and 2.2 on interactable input.

Here is again what I did to be clear:

Add PressableButtonHololens2 
Hook up function to Interactable's OnClick event (in my case I just log to console)
Turn off "Requires Focus" on speech command and make command == "Select"
Start scene in play mode
Click on button, see console output
Say speech command "Select" w/o focus on button, see console output
Click anywhere else in scene, no console output
Click on button, see console output

**Comment by Troy-Ferrell** [comment]
Closing this out due to inactivity. If you are still facing problems, please feel free to re-activate this issue or create a new one. THanks!
