### ISSUE TITLE
meta files missing every now and then

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6678]
## Describe the bug

I'm trying to stay up to date with the mrtk_development branch and for some reason, at least every 5th pull, some meta files have not been pushed along with the new files they were generated for. I've created about 4 Pull Requests in the past already adding them.

## Expected behavior

meta files are always pushed along with the files they were created for.
Maybe it's possible to implement some mechanism that checks that.

**Comment by keveleigh** [comment]
Ah, good idea! We do have a code validation step as part of our PR pipeline, so adding something to the powershell script to check for the existence of a corresponding meta file sounds like a great addition.

**Comment by keveleigh** [comment]
Fixed via #6691
