### ISSUE TITLE
Error "type or namespace name 'SpatialTracking' does not exist in the namespace 'UnityEngine'" with various versions

### ISSUE THREAD

**Issue by Firlefanz73** [microsoft/MixedRealityToolkit-Unity#6679]
Hello,

I Need both XR and AR work together, and found there were bugfixes 9 days ago.
So I chosed the two newer branches.
Both give me Always error:
 "type or namespace name 'SpatialTracking' does not exist in the namespace 'UnityEngine'"
I tried included packages, then used package Manager to install suggested updates, and even tried the prereleases there. Always get this error.

Thanks a lot!
 

Unity 2019.2.9

Both Branches Development or PreRelease 2.2.0

**Comment by Railboy** [comment]
Related: #6555

**Comment by Firlefanz73** [comment]
Thanks a lot, Great work with the MRTK by the way!

I did add a reference to the asmdef, now I get this one:

Assets\MixedRealityToolkit.Staging\UnityAR\Utilities\ArEnumConversion.cs(21,23): error CS0246: The type or namespace name 'TrackedPoseDriver' could not be found (are you missing a using directive or an assembly reference?)

**Comment by wiwei** [comment]
Closing out some old issues - I think this was fixed in the related thing but please reopen if you're still hitting this.
