### ISSUE TITLE
Add versioning to MRTK custom assets

### ISSUE THREAD

**Issue by david-c-kline** [microsoft/MixedRealityToolkit-Unity#6681]
Based on #6650 and several related discussions, MRTK should implement asset versioning for profiles and other custom scriptable objects.

From @julenka, 

```
we would do something like:

    private const int CurrentVersion = 2;

    [SerializeField]
    [HideInInspector]
    private int version = CurrentVersion;

    private void PerformVersionPatching()
    {
        if (version == 0)
        {
            // Migrate from version 0 to 1.
            ...
        }
            
        if (version <= 1)
        {
            // Migrate from version 1 to 2.
            ...
        }

        version = CurrentVersion;
    }
```

**Comment by wiwei** [comment]
Note that this is related to:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6650

There's a little more to consider here, and this issue is a specific solution to a problem that we could consider

**Comment by davidkline-ms** [comment]
Adding MRTK3 tag to ensure we keep scriptable object versioning in mind.
