### ISSUE TITLE
Toggle Profiler voice command is not working

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#6683]
From #6632, the "toggle profiler" command is not working.

From @julenka
> I cannot say toggle profiler or press 0 to turn off the profiler in that scene

**Comment by keveleigh** [comment]
I think this was fixed in #6642 

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6642/files#diff-430596b91af1b54f9e69bd10a34a591fR34

**Comment by ritijain** [comment]
Yes this was fixed. in my PR.
