### ISSUE TITLE
Investigate if ui collection can be removed and replaced by grid object collection

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#6689]
## Describe the problem
 ui collection is currently used by our non native keyboard. Preferably we would use GridObjectCollection and add missing functionality there instead of having another very similar layouting class

## Additional context

This is a follow up task for the NonNativeKeyboard ported from HTK - PR #6492

**Comment by polar-kev** [comment]
GridObjectCollection is being replaced by a new layout tool so this issue is no longer relevant. #6690 has been updated with a comment to use the latest MRTK layout tools.
