### ISSUE TITLE
New Changes in IInputClickHandler to method OnInputClicked right?

### ISSUE THREAD

**Issue by Heromanic** [Microsoft/MixedRealityToolkit-Unity#670]
error CS0535: `HoloToolkit.Examples.SharingWithUNET.PlayerController' does not implement interface member `HoloToolkit.Unity.InputModule.IInputClickHandler.OnInputClicked(HoloToolkit.Unity.InputModule.InputClickedEventData)'

Did I make a mistake or is there an error in the Toolkit? I upgraded my local HoloToolkit with the newest version and receive everywhere an error where IInputClickHandler is used but "public void OnInputClicked(**InputEventData** eventData)" is implemented. The System suggest to implement "public void OnInputClicked(Input**Clicked**EventData eventData)" instead.

Should I change the parameter to InputClickedEventData on my system?

**Comment by jessemcculloch** [comment]
This change was merged in back on Jan 19th.  https://github.com/Microsoft/HoloToolkit-Unity/pull/433

So yes, you will need to change your signatures to match.
