### ISSUE TITLE
MRTK 2.2 after upgrade I cannot assign my custom MRTK profile

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6701]
## Describe the bug
I had a custom profile in my MRTK 2.1 project. After upgrading to 2.2, my scene no longer had a valid MRTK profile and I was not able to assign the MRTK profile to my custom profile.

## To reproduce

1. Take project in 2.1 that has custom mrtk profile. My custom profile:
![image](https://user-images.githubusercontent.com/168492/69394030-b123ee00-0c8f-11ea-91ca-36bd7bfe59f1.png)

2. Upgrade to 2.2
3. Open your scene, look at the MRTK profile. My MRTK Profile is invalid:
![image](https://user-images.githubusercontent.com/168492/69394080-cb5dcc00-0c8f-11ea-9d28-760e68ea7428.png)

4. I cannot select my profile:
![image](https://user-images.githubusercontent.com/168492/69394111-e03a5f80-0c8f-11ea-9b0b-220cb4d5bacf.png)

**Comment by davidkline-ms** [comment]
@julenka, great catch!

**Comment by julenka** [comment]
Looks like this is user error. After closing Unity, deleting library, re-opening Unity the error went away.

I had missed the following: 

![image](https://user-images.githubusercontent.com/168492/69456284-17a41d00-0d1f-11ea-9bd4-a7b9ffce406e.png)
