### ISSUE TITLE
Standard Shader Reflections alter baked lighting

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6705]
## Describe the bug

I'm not sure if this a bug though it looks like it is one. Turning the Reflections setting on on the MRTK standard shader darkens baked light by quite a bit while the same setting keeps baked light the same color when using the Unity Standard Shader

## To reproduce

1. Create two cubes, one with standard shader material, one with MRKT standard shader material
2. enable static lightmapping on them
2. Put a point light in between them, setting it to baked
3. let the scene auto bake and toggle the reflections setting on the MRTK material on and off

## Expected behavior

Same behavior as the Unity Standard shader

## Screenshots

Reflections on:
![image](https://user-images.githubusercontent.com/32508825/69426579-db2bed80-0d2d-11ea-8b22-349ca4a96c2c.png)

Reflections off:
![image](https://user-images.githubusercontent.com/32508825/69426688-175f4e00-0d2e-11ea-99d1-9eae2591c2a2.png)

## Your Setup (please complete the following information)

- Unity Version 2018.5.12f1
- mrtk_development

## Target Platform (please complete the following information)

- Editor for now

**Comment by Alexees** [comment]
@Cameron-Micka this is still an issue and a problem in our project in Unity 2019.3.14f1 using the Universal Render Pipeline now.
Do you know what's happening here? We probably have to use the builtin shaders because of this.
Oh and another question. what's the performance compared between the two?

**Comment by Cameron-Micka** [comment]
Hi @Alexees, thank you for letting me know this is a blocking issue. I've not had a chance to look at this. But, I'll put it on my calendar to take a peek next week.

**Comment by Ayfel** [comment]
Definitely something off with ligthing, 1st picture is baked ligthing with the settings you see there in the shader (baked indirect or shadowmask give the same results)

![image](https://user-images.githubusercontent.com/13970424/105758024-6bf2f000-5f14-11eb-8d92-df48790bb696.png)

The next picture I just remove all the lighting in the rendering options, notice the big change 

![image](https://user-images.githubusercontent.com/13970424/105758097-7dd49300-5f14-11eb-85df-3140d32e6d64.png)

Finally this is the lighting with the standard shader (non mrtk):

![image](https://user-images.githubusercontent.com/13970424/105758148-8c22af00-5f14-11eb-8765-d6bce9181863.png)

And finally the MRTK just with reflections active:

![image](https://user-images.githubusercontent.com/13970424/105758261-aceb0480-5f14-11eb-840f-3668c7b01517.png)

What I can guess is that the lighting that better resembles the standard shader is when having all the rendering checkmarks off, but then its confusing as to how to best bake with a MRTK shader

**Comment by Ayfel** [comment]
Any thoughts on this? I still struggle to get the best results and playing with rendering options with MRTK

**Comment by davidkline-ms** [comment]
MRTK3 has adopted a new standard shader (from the com.microsoft.mrtk.graphicstools.unity package). It is unlikely that the standard shader in MRTK v2.x will be changed.
