### ISSUE TITLE
Stepping backwards does not check for a floor

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6706]
## Describe the bug

Teleporting with the beam always makes sure that you cannot go anywhere you're not allowed to.
Stepping backwards on the other hand just works and lets you run wild.

## To reproduce

1. walk backwards, through a cube, off an edge

## Expected behavior

Stepping backwards should also be a teleport command, checking for a valid place first

## Your Setup (please complete the following information)

- Unity Version 2018.4.12f1
- mrtk_development

## Target Platform (please complete the following information)

- Oculus Quest

**Comment by SimonDarksideJ** [comment]
Quite understandable how this was missed, as its been there since the HTK. But does need a solution, likely doing a reverse raycast to the floor behind the player.

**Comment by SimonDarksideJ** [comment]
@davidkline-ms have you managed to replicate and schedule a fix for this?

**Comment by Alexees** [comment]
We have a solution, just not the time to create a PR.
What we took into consideration:
- We do a vertical raycast through the new position the player would backstep to
- The length is twice a step height (so you can move up or down a certain height, just like you can with teleporting)
- We also created a fake HotSpot, so we could fire this a a TeleportStarted event to be able to listen to, whenever the playspace was moved

What we missed:
- Angle check for what's considered a floor. I our case everything from 0 to 89.9 degree in relation to the world up is considered floor

**Comment by davidkline-ms** [comment]
@Alexees, can you clarify the desired behavior a bit? 

From my read, the request is for the VR world to shift if the end-customer physically moves through the world and encounters a virtual object or off of the supported plane. Is this accurate?

Asked another way, does this image match your request?

![image](https://user-images.githubusercontent.com/13281406/80130388-5861c580-854d-11ea-9967-2c78c6933d0c.png)

**Comment by keveleigh** [comment]
I think other than the "world shifted to the left" part. If we just treat this like a "normal" teleport, the teleport wouldn't happen if an invalid location is detected.

**Comment by davidkline-ms** [comment]
Based on the repro steps, the issue sounds like locomotion related

> walk backwards, through a cube, off an edge

**Comment by davidkline-ms** [comment]
Interesting topic, to be sure

**Comment by Alexees** [comment]
It is related to the Motion Controller analog stick backwards teleport (whatever you call it) functionality. @keveleigh is right, it would suffice to treat it as a regular teleport.

**Comment by davidkline-ms** [comment]
Thanks for the clarification @Alexees! Much appreciated.
