### ISSUE TITLE
Interactable Material Theme wrongly set Active to false

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#6707]
## Describe the bug
when using material theme, gameobject got automatically disabled.
seems the material theme was copied from activate theme without removing corresponding line ...

```
StateProperties = new List<ThemeStateProperty>()
{
	new ThemeStateProperty()
	{
		Name = "Material",
		Type = ThemePropertyTypes.Material,
		Values = new List<ThemePropertyValue>(),
		Default = new ThemePropertyValue() { Material = null }
		},
	},
}
//...

public override void SetValue(ThemeStateProperty property, int index, float percentage)
{
	Host.SetActive(property.Values[index].Bool);

	material = property.Values[index].Material;
	renderer.material = material;
}
```
`Host.SetActive(property.Values[index].Bool);` should not be there !

## To reproduce

create an interactable with a material theme

## Expected behavior
gameobject doesn't get disabled

## Workaround
also add an Interactable Activate Theme (after the material one) and check all to true to override what materialtheme does

## Your Setup (please complete the following information)

- Unity Version [ 2018.4.9f1]
- MRTK Version [**v2.1 and stabilization 2.2**]

**Comment by keveleigh** [comment]
Fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6712
