### ISSUE TITLE
Replace/overwrite file with FileSavePicker

### ISSUE THREAD

**Issue by FlorianJa** [microsoft/MixedRealityToolkit-Unity#6708]
When you select an existing file with the FileSavePicker and press the save button you will hear a warning sound (same as for low battry warning) and after that the buttons for save and cancel do not work. Only way to close the FileSavePicker is to use the close button on the top right. Saving a new file works fine.

## Steps to reproduce the behavior:

1. Open a new FileSavePicker
2. Select an existing file
3. Press save button
4. Hear warning sound
5. FileSavePicker does not respond on input (only close button works)

## Expected behavior

I expect a dialog to confirm the replacing/overwrite of the selected file.

## My Setup (please complete the following information)

- Unity Version 2018.4.11f
- MRTK Version v2.1

## Target Platform 

- HoloLens

## Additional context

I think this is not related to MRTK but i think someone can forward it to the responable persons?!

**Comment by cre8ivepark** [comment]
Just tested on HoloLens 2 device and had slightly different behavior. I could press 'Ok' or 'Cancel' buttons without a problem. However, the file was not overwritten. I'll forward this issue to the shell team. Thanks!

[20191125_133432_HoloLens](https://user-images.githubusercontent.com/13754172/69580097-baab9f80-0f88-11ea-9f3f-777c011675e1.jpg)

**Comment by FlorianJa** [comment]
Thanks. On HoloLens 1 this dialog does not appear.

**Comment by wiwei** [comment]
Closing this one out as I believe @cre8ivepark forwarded this on internally to the right folks.
