### ISSUE TITLE
Sr mesh Visability per scene

### ISSUE THREAD

**Issue by grayclee** [microsoft/MixedRealityToolkit-Unity#6715]
## Describe the problem

I am currently using the scene switcher but I want some scenes to activate the SR mesh and other scenes to be invisible

## Describe the solution you'd like

To have a Tool or script that would allow me to initialize the SR mesh visibility depending on the scene.

**Comment by Troy-Ferrell** [comment]
You can resume and suspend observers via code by accessing the SpatialAwarenessSystem at runtime

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SpatialAwareness/UsageGuide.html

You can write a script in your project that on scene change calls the appropriate function. Look at SceneManager.activeSceneChanged or add the code to your own scenemanager that is switching scenes
```c#
// Resume Mesh Observation from all Observers
CoreServices.SpatialAwarenessSystem.ResumeObservers();

// Suspend Mesh Observation from all Observers
CoreServices.SpatialAwarenessSystem.SuspendObservers();
```

https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager-activeSceneChanged.html

If you have any other issues, please feel free to re-open this or file a new issue
