### ISSUE TITLE
Errors when switching between Default MRTK and custom profiles

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6716]
## Overview
I get the following error when switching between the default and a custom mrtk profile:

InvalidOperationException: Collection was modified; enumeration operation may not execute.
System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Microsoft.MixedReality.Toolkit.Utilities.Facades.MixedRealityToolkitFacadeHandler.DestroyFacades () (at Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs:189)
Microsoft.MixedReality.Toolkit.Utilities.Facades.MixedRealityToolkitFacadeHandler.UpdateServiceFacades () (at Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs:129)
Microsoft.MixedReality.Toolkit.Utilities.Facades.MixedRealityToolkitFacadeHandler.OnUpdate () (at Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs:53)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:200)

## Steps to reproduce
In MixedRealityToolkit...
1. Select custom profile
2. Swifch to Default profile
3. Switch back to custom profile

![profile_switch_error](https://user-images.githubusercontent.com/168492/69467799-7e84fe80-0d3e-11ea-8368-bc55a2e54ffa.gif)

**Comment by Troy-Ferrell** [comment]
What version of Unity are you on? I can't repo. I also see way more profiles than you @julenka 

![profile-error](https://user-images.githubusercontent.com/25975362/69473218-10edc800-0d68-11ea-8024-9a00ae72730c.gif)

**Comment by julenka** [comment]
Unity 2018.4.12f1. I have fewer profiles because I did not import the examples package

**Comment by julenka** [comment]
Removing release blocker for now, since it is not 100% repro (did not repro for Troy). Might be unique to my build, and doesn't break functionality. If we see lots of feedback about this we can release a 2.2.1 patch to fix.

**Comment by Troy-Ferrell** [comment]
I can repo once I just include foundation. After importing another package, the cache refreshes and I see my "custom" MRTK profile again. 

Issue lies with the following not returning our custom profile type
MixedRealityProfileUtility.GetProfilesOfType(profileType);

**Comment by julenka** [comment]
I am not seeing this with latest code, so closing for now. We can reopen if we hit it again.
