### ISSUE TITLE
move auto-modification of the package manifest into the configurator 

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#6723]
#6718 adds automatic modification of the package manifest to add msbuild for unity. move this from project load to a selectable option in the configurator dialog. 

We wish to do this to give customers a choice whether or not to install MSBuild for Unity. Currently, everyone who imports the MRTK gets MSBuild for Unity automatically.

**Comment by julenka** [comment]
For my own education, why do we need to do this, and why is it a release blocker?

**Comment by davidkline-ms** [comment]
To give customers a choice whether or not to install MSBuild for Unity. @keveleigh suggested this one.

Currently, everyone who imports the MRTK gets MSBuild for Unity automatically.

**Comment by julenka** [comment]
Thanks for the explanation! That adds some useful context I agree it's important to not force new frameworks on people if possible. For the future, it might be good to add the "why we care" in the bug description, especially for release blockers which folks would pay attention to more.

**Comment by davidkline-ms** [comment]
> For the future, it might be good to add

100% agree. I missed adding that part.
