### ISSUE TITLE
An idea to add functions to MRTK Examples / MaterialGallery for easy understanding by developers.

### ISSUE THREAD

**Issue by HoloMoto** [microsoft/MixedRealityToolkit-Unity#6724]
## Describe the problem
 MRTK sample material gallery scene can understand MRTK StandardShader, but I feel there are some problems.
  ・Cannot intuitively understand the functions of MRTK StandardShader with HoloLens

If this problem is solved and MRTK StandardShader can be confirmed not only on the Unity editor but also on the actual HoloLens machine, it will lead to understanding of MRTK StandardShader.  
## Describe the solution you'd like

It would be great if there was a function in the Material Gallery scene of the MRTK example to better understand the functions of the MRTK StandardShader.

## Describe alternatives you've considered
 I put Slider in the scene as a way to solve the problem
Suggests an idea of ​​changing MRTK StandardShader parameters from a script.

**Comment by cre8ivepark** [comment]
@Sthesia Thank you HoloMoto! Please let me know if you need any help on opening PR.

**Comment by Troy-Ferrell** [comment]
@Cameron-Micka  as FYI

**Comment by Cameron-Micka** [comment]
I love this idea, I agree it will make the scene more interactable while improve understanding. I just returned from paternity leave but hope to take a look at the pull request soon.

**Comment by Sthesia** [comment]
@Cameron-Micka  Thank you, I believe the greatness of MRTK StandardShader can be shared with all developers.
I was sick for a while, so I couldn't move.sorry
It's my first time, so I'd be glad if you could tell me what to do.

**Comment by polar-kev** [comment]
Hey @HoloMoto, there hasn't been any activity on the PR associated with this, #6744. I'm going to close this issue. If you still want to finish the PR, feel free to open it again.
