### ISSUE TITLE
FrontPlate gets stuck for all buttons if disabled while pressed in far interaction mode

### ISSUE THREAD

**Issue by umaknow-manu** [microsoft/MixedRealityToolkit-Unity#6725]
## Describe the bug

If a pressable prefab button is pressed in far interaction mode and call an event that SetActive(false) the button (or a parent), the FrontPlate cover GameObject will be stuck at the pushed position when re-enabled. This bug does not happend in near interaction mode.

## To reproduce

1. Go to HandInteractionExampes scene from MRTK exemples
2. Set a button (button 1) event onclick to setActive(false) its own prefab GameObject
3. Set an other button (button 2) event onclick to setActive(true) button 1 prefab GameObject
4. Click on button 1 and button 2 alternately many time ( e.g 5).

## Expected behavior

The FrontPlate of button 1 should be at the start of the button cage.

## Screenshots

![image](https://user-images.githubusercontent.com/46577508/69554224-76f86c00-0f6f-11ea-849b-78cf4e90903b.png)

## Your Setup

- Unity Version 2019.2.3f1
- MRTK Version v2.0

## Target Platform

- HoloLens
- HoloLens 2
- Bug has been tested on Hololens 1

## Additional infos
I don't feel like it's a duplicate of #4528 since the button is pressable when reenabled.
Pinging @CDiaz-MS and @thalbern

**Comment by Troy-Ferrell** [comment]
@umaknow-manu this does sound like #4528. Can you please update to MRTK v2.1 to confirm if that fixes it for you? Thank you!

**Comment by umaknow-manu** [comment]
@Troy-Ferrell  Updated to MRTK 2.1.0 and I can confirm it is fixed now. Thank you and sorry for not digging enough.
