### ISSUE TITLE
Wireframe shows up in wrong position with Standard Shader

### ISSUE THREAD

**Issue by lordlycastle** [microsoft/MixedRealityToolkit-Unity#6726]
## Describe the bug

The wireframe drawn using the standard shader has the wrong position and scale.

## To reproduce

1. Create new 3D object. 
2. Assign a material created from Standard Shader.
3. Change Scene View to show Shaded Wire Frame.
4. Move and scale object and see wireframe doesn't change.

## Expected behavior

Wireframe should be overlayed on the shaded model.

## Screenshots

![image](https://user-images.githubusercontent.com/11729541/69557457-8cd15580-0f9e-11ea-8310-710dda2c1f3b.png)

## Your Setup (please complete the following information)

- Unity Version 2018.4.10f1
- MRTK Version 2.0.0

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR
- UWP

**Comment by Troy-Ferrell** [comment]
@lordlycastle thanks for filing the issue. This does not repo for me in latest MRTK. 

Can you try repoing again yourself? Also update from v2.0 to v2.1? If you see it repo again, if you change the material shader from MRTK standard to Unity standard, does the wireframe render correctly?

Closing out for now. If you get a consistent repo on latest, please feel free to re-open

![image](https://user-images.githubusercontent.com/25975362/70097261-f2ed5680-15f6-11ea-8d36-50fdaaa1be80.png)

**Comment by lordlycastle** [comment]
@Troy-Ferrell  Yes it shows up incorrect position with unity shader.

**Comment by Troy-Ferrell** [comment]
"it shows up in correct position" or "it shows up in the incorrect position" with the Unity standard shader?

Is this after updating and restarting Unity etc?

**Comment by lordlycastle** [comment]
@Troy-Ferrell Oh sorry. In the correct position i.e. on the cube where the mesh is. Edited.

**Comment by Troy-Ferrell** [comment]
@lordlycastle if you update your MRTK to use v2.1 and try the MRTK standard shader in wireframe mode, can you confirm if that works or doesn’t work for you?

**Comment by Troy-Ferrell** [comment]
jk HandsInteractionExample scene demos problem

![image](https://user-images.githubusercontent.com/25975362/70261604-c48b8a80-1760-11ea-99b3-9db2b4931263.png)

**Comment by lordlycastle** [comment]
@Troy-Ferrell Just tested with the latest version v2.1. Issue is still there.

**Comment by lordlycastle** [comment]
@Troy-Ferrell Just tested with the latest version v2.1. Issue is still there.

**Comment by Cameron-Micka** [comment]
@lordlycastle thank you for reporting this. I was not able to exactly reproduce the issue. But! I was able to get the issue when selecting an object. You can see in this screenshot:

![image](https://user-images.githubusercontent.com/13305729/74560499-8908fb80-4f1b-11ea-9e4d-233c618df237.png)

I have the coffee cup selected. The coffee cup's wireframe renders in the correct location, but the selection wireframe renders at the model's identity matrix.

I've narrowed the issue down to the meta pass within the shader, it appears UnityMetaVertexPosition is not respecting the EDITOR_VISUALIZATION keyword. Moving the meta pass as the second pass (or anything but the first pass) seems to fix the issue. I'm going to do some more testing then will create a pull request to fix this.
