### ISSUE TITLE
Sharingservice connect attempt causes app to die on HoloLens

### ISSUE THREAD

**Issue by Siman007** [Microsoft/MixedRealityToolkit-Unity#673]
Updated - I reported the issue a few days ago. Having spent a day or two looking at it I think its the issue mentioned here https://forums.hololens.com/discussion/7203/vs2017-u5-6-crash-winrtscriptingobjectwrapper-internaladdref-reference-count-cannot-be-zero
*********************************************************************

Hi have a problem with the HoloToolKit for Unity. I am using the current version of the HoloToolKit (download yesterday)  running in a Unity 5.60f3, built and debugging using VS 2017.

When I add the ImportExportAnchorManager to a simple test app the app dies as it loads on HoloLens with no debug output. Tracing it through it appears to execute line 225 in ImportExportAnchorManager which in my build reads SharingStage.Instance.SharingManagerConnected += Connected; (see below for the full function)

and returns - it appears to die just after the return.
Sorry for the lack of precision here I don't seem to be able trace it any closer as the debugger is jumping and missing the exact line that is tripping it up.

private void Start()
{
// SharingStage should be valid at this point, but we may not be connected.
if (SharingStage.Instance.IsConnected)
{
Connected();
}
else
{
SharingStage.Instance.SharingManagerConnected += Connected;
}
}

The only debug I get after this line is in SharingStage.cs in HandleLog which is an Assert with the log message logString = "WinRTScriptingObjectWrapper::InternalAddRef Reference Count cannot be zero"

When I remove ImportAnchorManager   and just run the sharingstage and autojoin scripts I can see the Hololens connecting to the sharing service (running via WIFI on my local machine with no firewall) just fine.

The project is a brand new one with a single empty  parent game object and a single child with only AnchorText  for debuging.

The sharing service log records
SharingService: Created Session "Default" with ID 0 on port 20601
SharingService:  ** Logging Session Began at 22:25:36, 5-18-2017
SharingService: ***********************************
SharingService: ****** Sharing Service OnStart ******
SharingService: ***********************************
SharingService: Server Info: 
	Build Version: 1.1.0.0 
	Schema Version: 17
SharingService: Listening for session list connections on port 20602 of all network devices of the local machine.
SharingService: Local IP addresses are:
SharingService: 	172.16.80.1
SharingService: 	169.254.80.80
SharingService: 	10.10.1.130
SharingService: Created Session "Default" with ID 0 on port 20601
SharingService: ListServer: Handshake failed with error 1

Any ideas gratefully received

**Comment by StephenHodgson** [comment]
This issue might need to be moved into the main [HoloToolkit](https://github.com/Microsoft/HoloToolkit).

**Comment by StephenHodgson** [comment]
See https://github.com/Microsoft/HoloToolkit-Unity/issues/623

**Comment by sebrk** [comment]
I cannot get the sharing services to work either, Hololens never finds anything.

**Comment by StephenHodgson** [comment]
`ImportExportAnchorManager` was replaced by `AutoJoinSessionAndRoom`
