### ISSUE TITLE
Non-uniform scaling option for Bounding Box

### ISSUE THREAD

**Issue by danielescudero** [microsoft/MixedRealityToolkit-Unity#6734]
**Problem**
As a developer I'd like to be able to enlarge (scale) a backplate or slate in order to fit more content inside. I'd like to make it wider or taller and not be limited to uniform scaling.

**Solution**
Allowing for a boolean value that toggles uniform/non-uniform scaling in the editor. Uniform by default of course.

**Alternatives**
Consider an OnScaleUpdated UnityEvent so we can re-layout content while it is scaling.
@thalbern :)

**Comment by FlorianJa** [comment]
@thalbern are already working on this?

**Comment by Lukas-dev-threads** [comment]
I would love to use the bounding box in my application if it could be scaled non-uniform !

@thalbern Are there any updates on the topic ?

**Comment by FlorianJa** [comment]
@thalbern, @danielescudero:  Are there any updates?

**Comment by thalbern** [comment]
sry this took so long, but working on it now!
