### ISSUE TITLE
ExamplesHub has two Toggle Features panels

### ISSUE THREAD

**Issue by sostel** [microsoft/MixedRealityToolkit-Unity#6735]
## To reproduce
1. Sync to the latest mrtk_development branch

2. Open Unity and switch to UWP

3. Load MRTKExamplesHub

4. Play in the Unity Editor

5. Once that scene is loaded, you also can see that there are two "Toggle Features" panels:
![image](https://user-images.githubusercontent.com/32180789/69590251-b6d94680-0fa3-11ea-8828-ad5304fdefc5.png)

## Expected behavior

One "Toggle Features" panel.

**Comment by julenka** [comment]
It seems like the errors are no longer appearing, most likely fixed by David's changes. Renaming this bug to reflect only that the duplicated toggle features panel still appears.

**Comment by julenka** [comment]
Correction: first error Sophie points out still pops up, going to move that to a separate issue so we can track fixing toggle features panel separately.

**Comment by julenka** [comment]
Moved the errors to #7572

**Comment by cre8ivepark** [comment]
The issue was resolved by hiding duplicated ToggleFeaturesPanel in each example scene.
Closing this.

**Comment by keveleigh** [comment]
> The issue was resolved by hiding duplicated ToggleFeaturesPanel in each example scene.

@cre8ivepark Is this what caused the missing ToggleFeaturesPanel that I re-enabled in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9687? Were these changes all checked into the repo? It feels like a weird state, since it'd make the scenes unusable on their own :/
