### ISSUE TITLE
Eye Targeting scene: Gems are rotating too fast

### ISSUE THREAD

**Issue by sostel** [microsoft/MixedRealityToolkit-Unity#6736]
## Describe the bug
The gems in the eye targeting scene are rotating much too fast, inducing anxiety. 

## To reproduce
Either through the "MRTKExampleHub" scene or through the "EyeTrackingDemo-00-RootScene", load the "EyeTrackingDemo-02-TargetSelection". Move the cursor over a gem and it will start turning very quickly.

## Expected behavior
Slow and subtle rotational feedback to being looked at.

**Comment by wiwei** [comment]
Closing out some older issues which may not be super impactful - the gems do rotate somewhat fast, though I've tried slowing them down a bit and it hasn't caused a noticable change on my overall quality of life.

It's probably still fine to send out a PR to reduce the speed but not sure that this specific thing is gonna keep us up at night.
