### ISSUE TITLE
Toolkit-less UI

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6739]
## Describe the problem

I am additively loading scenes. Additive scenes with MRKT UI have the problem that their components require an existing MRKT, which I'm providing in a different scene. Depending on the device I need to load a completely different MRKT profile and since profile switching is not supported I have to use a completely different one.

Same goes for prefabs you want to spawn. The prefab edit mode does not even support that very well. If you choose to add the toolkit it goes into the scene you started editing it from which you might not want.

## Describe the solution you'd like

UI elements should be able to be used in whatever situation you'd like. The dropdown on the Interactable component should always show valid input actions and speech commands

## Describe alternatives you've considered

I'm not sure if it's possible, but the InitializeOnLoadAttribute could put the MRTK into global existence, maybe as a static instance, holding everything configured for the time the Editor is open. This goes in addition to placing it into a scene for the runtime initialization.

Second idea would be to populate the required fields for the scripable objects on the components. If the Toolkit is missing, why not assigning the components automatically. The hierarchy could reflect this in that it highlights gameobjects or flags them all the way up to the parent in case neither the MRKT is present, nor a scriptable object is assigned.

**Comment by davidkline-ms** [comment]
The MRTK v3 effort includes moving to using Unity's XR Interaction Toolkit (XRI), which will result in our UX components being usable in any application that utilizes XRI, even if other MRTK components are not included.

**Comment by Zee2** [comment]
Confirming that MRTK3 supports lazy-loading of UI.
