### ISSUE TITLE
Assertion failed on expression: 'GetAssetScriptingType(*m_RefreshQueue.begin()) 

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#6741]
## Describe the bug
I get the following error after importing the Foundation package in Unity 2019.1.14f1:

```
Assertion failed on expression: 'GetAssetScriptingType(*m_RefreshQueue.begin()) != AssetScriptingType::Script'
```

## To reproduce

1. Import latest 2.2 test Foundation Package

## Screenshots

<img width="1105" alt="error2019" src="https://user-images.githubusercontent.com/53493796/69662303-f43be380-1038-11ea-9e5c-f41a0cca64b1.png">

## Your Setup 

- Unity Version:  2019.1.14f1
- MRTK Version: v2.2

**Comment by Troy-Ferrell** [comment]
@CDiaz-MS I couldn't repo this in 2019.2.15. Are you able to repo with official released packages?

**Comment by CDiaz-MS** [comment]
@Troy-Ferrell  yes it still repros with the 2.2 release packages but I have only seen it in Unity 2019.1.14 so far.

**Comment by Troy-Ferrell** [comment]
@CDiaz-MS cool thanks for checking!
