### ISSUE TITLE
German umlauts with MRKT TextMeshPro shader causes error

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6746]
## Describe the bug

Setting the Text for a TextMeshPro using the MRKT TextMeshPro shader using any of the german umlauts "äöü" causes the TextMesh to throw an error because it copies the material, probably for generating a different set of letters, of with it cannot find a particular shader property:

```
Material doesn't have a float or range property '_CullMode'
UnityEngine.Material:GetFloat(String)
TMPro.TMP_SubMesh:UpdateMaterial() (at Library/PackageCache/com.unity.textmeshpro@1.5.0-preview.2/Scripts/Runtime/TMP_SubMesh.cs:584)
TMPro.TMP_SubMesh:SetMaterialDirty() (at Library/PackageCache/com.unity.textmeshpro@1.5.0-preview.2/Scripts/Runtime/TMP_SubMesh.cs:562)
TMPro.TMP_SubMesh:SetSharedMaterial(Material) (at Library/PackageCache/com.unity.textmeshpro@1.5.0-preview.2/Scripts/Runtime/TMP_SubMesh.cs:505)
TMPro.TMP_SubMesh:AddSubTextObject(TextMeshPro, MaterialReference) (at Library/PackageCache/com.unity.textmeshpro@1.5.0-preview.2/Scripts/Runtime/TMP_SubMesh.cs:425)
TMPro.TextMeshPro:SetArraySizes(UnicodeChar[]) (at Library/PackageCache/com.unity.textmeshpro@1.5.0-preview.2/Scripts/Runtime/TMPro_Private.cs:1337)
TMPro.TMP_Text:ParseInputText() (at Library/PackageCache/com.unity.textmeshpro@1.5.0-preview.2/Scripts/Runtime/TMP_Text.cs:1858)
TMPro.TextMeshPro:OnPreRenderObject() (at Library/PackageCache/com.unity.textmeshpro@1.5.0-preview.2/Scripts/Runtime/TMPro_Private.cs:1542)
TMPro.TextMeshPro:Rebuild(CanvasUpdate) (at Library/PackageCache/com.unity.textmeshpro@1.5.0-preview.2/Scripts/Runtime/TextMeshPro.cs:239)
TMPro.TMP_UpdateManager:DoRebuilds() (at Library/PackageCache/com.unity.textmeshpro@1.5.0-preview.2/Scripts/Runtime/TMP_UpdateManager.cs:187)
TMPro.TMP_UpdateManager:OnCameraPreCull(Camera) (at Library/PackageCache/com.unity.textmeshpro@1.5.0-preview.2/Scripts/Runtime/TMP_UpdateManager.cs:158)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

## To reproduce

1. Create a PressableButtonHoloLens2 in any scene and type any of the umlauts into the SeeItSayItLabel -> TextMeshPro text component

## Expected behavior

No error

## Your Setup (please complete the following information)

- Unity Version 2018.3.12f1
- mrtk_development

## Target Platform (please complete the following information)

- Unity Editor
- Android Oculus Quest

**Comment by wiwei** [comment]
Going through some older bugs, I'm not seeing this repro on 2018.4.14f1 (with either the latest non-prerelease TMP package, or the latest-latest (i.e. preview4) prerelease TMP package).

If we're still seeing this happen, it's probably worth filing a bug on Unity (i.e. owners of TMP) as AFAIK this is just happening within TMP itself.
