### ISSUE TITLE
unity ui example is scrolling content to outside of panel

### ISSUE THREAD

**Issue by vaoliva** [microsoft/MixedRealityToolkit-Unity#6747]
## Describe the bug

Unity UI Example on HandInteractionExamples Scene  scrolls content outside of panel.
Bug is not visible on the editor or Video Capture. Bug only visible on the device.

## To reproduce

1. Create New Unity Project
2. Import 2.2.0 Stabilization Unity Packages
3. Deploy HandInteractionExamples scene to Hololens2
4. Scroll window of the Unity UI Example

## Expected behavior

Content should stay inside scrolling panel, hiding the overflow.

## Screenshots

![image](https://user-images.githubusercontent.com/16922045/69745199-ad81e280-1139-11ea-8726-a1118a6f6eb9.png)

## Your Setup (please complete the following information)

- Unity Version 2018.4.12f1]
- MRTK Version 2.2.0 Stabilization

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by cre8ivepark** [comment]
I remember that it happens when you set the depth buffer to16-bit. Cameron said it seems Unity UI requires 24-bit for masking.

**Comment by davidkline-ms** [comment]
Closing as this is a known (and documented) issue with Unity UI

**Comment by DanCRichards** [comment]
@cre8ivepark - Where can you change the depth buffer of Unity UI items? I am looking on google as well

**Comment by DanCRichards** [comment]
Note:

**Comment by Pycorax** [comment]
Hi, I just encountered this issue while trying to set up eye auto-scroll using the docs as a guide. I think it would be useful to have this information added to the docs to keep people in the loop.

**Comment by keveleigh** [comment]
@davidkline-ms I think we might also want to remove our debug warning when the depth buffer is set to 24 bit. There are valid scenarios, like this, where 16 bit isn't sufficient. Thoughts?
