### ISSUE TITLE
Camera rotates on z axis in playmode

### ISSUE THREAD

**Issue by FlorianJa** [microsoft/MixedRealityToolkit-Unity#6750]
## Describe the bug

When holding down the right mouse button in playmode, the camera slowly rotates on the z axis.

## To reproduce

1. open scene in playmode
2. select main camera in inspector
3. switch to game window and press and hold right mouse button
4. observe z axis rotation

## Expected behavior

no rotation while pressing and holding the right mouse button

## Your Setup 

- Unity Version 2018.4.0f1
- MRTK Version v2.1

## Target Platform

Editor (hololens 1 default profil)

**Comment by Alexees** [comment]
I cannot reproduce this problem with the latest mrtk_development branch

**Comment by FlorianJa** [comment]
I tested it as well and i cannot repoduce it with the dev branch. Maybe it was an error in my application.
