### ISSUE TITLE
Is it possible to render opaque meshes in front of all others with the MRTK shader?

### ISSUE THREAD

**Issue by benjamincoven** [microsoft/MixedRealityToolkit-Unity#6757]
## Describe the problem

Hello,

I would like to be able to render some GameObjects in front of all others like if they would have a later render queue. GameObjects are using the MRTK standard shader in opaque mode.

## Describe alternatives you've considered

I have considered to use a second camera, however this may be quite unecessary complex in my case if there is a simpler solution with the shader.

Thank you.

**Comment by Alexees** [comment]
Usually you do this by altering the Queue value of the shader. If you want to render infront of all put something like 3001 (3000 being the default transparency queue value). For a better explanation look here:
[Rendering Order - Queue Tag](https://docs.unity3d.com/Manual/SL-SubShaderTags.html)

**Comment by benjamincoven** [comment]
Hello, I am sorry if I have not replied earlier.

However I am asking for Opaque materials, the render queue only works for transparent ones.

**Comment by Troy-Ferrell** [comment]
@benjamincoven try render queue and on the material with the MRTK standard shader, set ZTest to always. You may have to change rendering mode from opaque to custom to access the ZTest property. Let me know if that works for you

**Comment by benjamincoven** [comment]
Yes, it works! I still have to change the render queue to avoid color issues.

Thank you very much.
