### ISSUE TITLE
PinchSlider uses wrong values for its slide distances

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6758]
## Describe the bug

The PinchSlider is moved by the delta position of the currently used pointer. This might work on Hololens because you're moving your hand, but motion controllers can just be turned in place altering the cursors position, not the pointer, which keeps still.
In case of the mouse pointers, this results in very fast movement when using the slider up close, because their whole pointer is moving to where the world position of the cursor would be, but even worse, always report the position at their maximum distance from the camera, no matter what they hit closer by.
This is also very noticeable when the slider is far away but looked at at a steep angle. then the movement might be in the users favor, because he can still operate it and move by small values, but it's also not very accurate... How do you determine how much you go at what angle or dinstance?

I have not tested this with a motioncontroller, but from the looks of the code my prediction is correct for those.

## To reproduce

1. place a pinch slider close to the camera
2. move it either by any of the mouse cursors, or with a motion controller by just rotating it

## Expected behavior

The slider moves along with the cursor. This should probably be a plane mapped movement that tracks the traveled distance of whatever cursor, ray, pointer, whatever in a local plane of the slider

## Your Setup (please complete the following information)

- Unity Version 2018.3.12f1
- mrtk_development

## Target Platform (please complete the following information)

- UWP VR HMD
- Editor Mouse Cursors

**Comment by Troy-Ferrell** [comment]
@julenka  FYI

**Comment by Zee2** [comment]
@RogPodge , this might still apply to MRTK3 (and definitely MRTK2, unless otherwise addressed)

**Comment by Zee2** [comment]
Completely fixed in MRTK3! @Alexees take a peek :)
