### ISSUE TITLE
Can not use system keyboard in hololens 1

### ISSUE THREAD

**Issue by oneSitDown** [microsoft/MixedRealityToolkit-Unity#6759]
![image](https://user-images.githubusercontent.com/47908151/69848966-71c05780-12b6-11ea-9217-fbbc25933c1e.png)
When I use the latest MRTK, I run the official demo in HoloLens1, but I cannot use the keyboard of the system call. Like the picture above, there is no way to display the word I preview. Is there a way to solve it?

**Comment by cre8ivepark** [comment]
Currently, the system keyboard cannot display the preview text on both HoloLens 1 and 2. Check out this PR which creates a preview text UI. However, it does not fully follow the keyboard surface.
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6235

**Comment by IfnoLee** [comment]
Same problem。

**Comment by MaxWang-MS** [comment]
Closing as the lack of preview text in Unity app is external to MRTK (it's on Unity/OS side). Please check out `MixedRealityKeyboardPreview` if you want to see the preview with MRTK.
