### ISSUE TITLE
How to implement In app Windows Store purchase with UWP?

### ISSUE THREAD

**Issue by mayovtester** [Microsoft/MixedRealityToolkit-Unity#676]
Is possible (or will be) to implement Windows Store purchase with hololens?

**Comment by thebanjomatic** [comment]
@mayovtester Can you elaborate on what you mean by a Windows Store purchase?

**Comment by mayovtester** [comment]
@thebanjomatic In-game purchases, microtransactions.

**Comment by keveleigh** [comment]
@mayovtester Here's the UWP sample for in-game purchases: https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Store
I have not tested this on a HoloLens, but UWP *should* just work! Let me know if you run into any issues.

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.

**Comment by MrMatthias** [comment]
How would that work from within an immersive Unity HoloLens app? As i understand you need to present some 2d view? 
Is there an example?
