### ISSUE TITLE
NullReferenceExeption when using SetState on an interactable in OnEnable or while it is inactive

### ISSUE THREAD

**Issue by Yolo-Jerome** [microsoft/MixedRealityToolkit-Unity#6760]
## Describe the bug

The origin of the bug is actually that Interactables do not reset their states when they get disabled and re-enabled. 

To workaround this I made a simple script

```csharp
public class InteractableResetter : MonoBehaviour
{
    #region Inspector
#pragma warning disable 0649
    [Header("Components")]
    [SerializeField] private Interactable _interactable;
#pragma warning restore 0649
    #endregion Inspector


    #region MonoBehaviour Methods

    private void Awake()
    {
        FetchComponents();
    }

    private void OnEnable()
    {
        _interactable.ResetBaseStates();
    }

    #endregion MonoBehaviour Methods


    #region Private Methods

    [ContextMenu("FetchComponents")]
    private void FetchComponents()
    {
        if (!_interactable) _interactable = GetComponent<Interactable>();
    }

    #endregion Private Methods
}
```
However, this throws a `NullReferenceException` for `StateManager` in `Interactable.UpdateState`!

When I checked the code I noted that you do the `!=null` check in `SetState`

```csharp
public void SetState(InteractableStates.InteractableStateEnum state, bool value)
{
    if (StateManager != null)
    {
        StateManager.SetStateValue(state, value ? 1 : 0);
    }

    UpdateState();
}
```

But then you call `UpdateState` where you do not do the `!=null` check:

```csharp
protected virtual void UpdateState()
{
    StateManager.CompareStates();
}
```

&rightarrow; I would suggest to either do `UpdateState` only if `StateManager != null` in `SetState`

```csharp
public void SetState(InteractableStates.InteractableStateEnum state, bool value)
{
    if (StateManager != null)
    {
        StateManager.SetStateValue(state, value ? 1 : 0);
        UpdateState();
    }
}
```
or/and add a check to `UpdateState`

```csharp
protected virtual void UpdateState()
{
    if(StateManager != null) StateManager.CompareStates();
}
```

## To reproduce

Call `ResetBaseStates` ro any `SetState` method on an `Interactable` in `OnEnable` or e.g. while the `Interactable` is inactive.

## Expected behavior

The main wish would be that Interactables reset their states `OnEnable`.

When resetting "manually" there shouldn't be a `NullReferenceException` but MRTK2 should handle/catch this properly.

## Your Setup (please complete the following information)

- Unity Version 2019.2.6f1
- MRTK Version v2.0

## Target Platform (please complete the following information)

- HoloLens(1/2)

**Comment by Troy-Ferrell** [comment]
Hello! @Yolo-Jerome thanks for filing this. The bug states you are using MRTK v2? There has been significant work in Interactable in both 2.1 (especially) and 2.2. Can you please update?

**Comment by Yolo-Jerome** [comment]
> 
> 
> Hello! @Yolo-Jerome thanks for filing this. The bug states you are using MRTK v2? There has been significant work in Interactable in both 2.1 (especially) and 2.2. Can you please update?

Hi,
currently I'm close before the end of a production and would rather not update right now ;)
I checked out the code real quick, however, and can see that you already fixed this in the newer releases 👍
