### ISSUE TITLE
LoadContentScene script missing on MRTK 2.1 Nugget package

### ISSUE THREAD

**Issue by Kent1LG** [microsoft/MixedRealityToolkit-Unity#6763]
## Describe the bug

The LoadHubonStartup gameobject of the MRTKExamplesHub use LoadContentScene, but it's a missing Script. 
I don't know if it's relating to Nugget package.
Cause of this, you can't use the Examples Hub.

## To reproduce

1. Create Unity project
2. Import Nugget Unity package
3. Download MRTK.Foundation, MRTK.Examples , MRTK.Extensions
4. Open MRTKExamplesHub
5. Check LoadHubOnStartup gameobject

## Expected behavior

LoadContenScene should be on the package and assigned to LoadHubOnStartup gameobject.

## Screenshots

![Annotation 2019-12-02 144703](https://user-images.githubusercontent.com/11636956/69964498-d7108480-1512-11ea-8ac3-97653e31f15d.png)

## Your Setup (please complete the following information)

- Unity 2018.4.12f1
- MRTK Version 2.1 (Nugget)

## Target Platform (please complete the following information)

- Unity Editor
- HoloLens 2

## Additional context

The documentation : https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_ExampleHub.html show the script "LoadcontentScene" assigned to the scene.

**Comment by Kent1LG** [comment]
Maybe add "Documentation" label to this issue.

**Comment by Kent1LG** [comment]
Fixed on MRTK 2.2 (Nugget again)

**Comment by LeoQIao** [comment]
Hey . I meet this issue on MRTK 2.4.0 again.
