### ISSUE TITLE
Input Simulation Service Profile Selector does not filter by type

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6765]
## Describe the bug

![image](https://user-images.githubusercontent.com/168492/69974528-6d34b280-14f3-11ea-9c57-b7435dc21399.png)

When trying to change the input simulation profile, it is very easy to corrupt / ruin your MRTK profile because the profile selector shows all profile assets instead of just filtering to profiles of type input simulation profile. This can make it very easy to get your MRTK profiles into an invalid state which can only be fixed by reverting the input system profile asset.

## To reproduce

0. Import MRTK 2.2 release candidate. Close, then re-open Unity, etc. etc. etc.
1. Go to input system profile
2. Click on "Input Simulation Service"
3. Click on the dropdown to select the profile
![image](https://user-images.githubusercontent.com/168492/69974218-d10aab80-14f2-11ea-95ab-01ddc55f732f.png)

4. Notice that all MRTK profiles are shown, not just profiles of type input simulation service

![image](https://user-images.githubusercontent.com/168492/69974536-76be1a80-14f3-11ea-9958-29d4ad1cdabc.png)

## Expected behavior

The dropdown should only contain profiles that match the type. 

## Your Setup (please complete the following information)

- Unity Version 2019.2.13f1
- MRTK Version 2.2 stabilization

**Comment by julenka** [comment]
Marking as release blocker because this bug makes it very easy to get user into invalid state. Based on principle "fix existing issues / broken things". Profile dropdown for a given type should only show profiles of that type.

**Comment by julenka** [comment]
I am using Unity 2019, however other profile dropdowns (like the camera system profile) DO filter correctly. So I believe this is code defect, not issue with my Unity version.

**Comment by davidkline-ms** [comment]
This is true for all input data providers. Each provider type is likely to have a different profile.

Looking into whether or not there is a clean way to filter based on the expected profile type for each provider.

Investigating if this is a regression from 2.1

**Comment by davidkline-ms** [comment]
Interstingly enough, the mouse provider filters but no other device manager types. I do not see anything that is performing this filtering....

**Comment by Railboy** [comment]
This is due to the `InputSimulationService` being implementing both `IInputSimulationService` and `IMixedRealityEyeGazeDataProvider`.

Two different profiles types indicate that they're intended for services implementing each of these interfaces. This results in multiple supported profile types being found for `InputSimulationService`. When multiple profile types are found by the inspector, the profile dropdown renderer opts to include all profile types. See `BaseMixedRealityProfileInspector.RenderProfileInternal`, line 124.
 
I think it would be reasonable to update the profile dropdown renderer to draw multiple profile types.

**Comment by Alexees** [comment]
> I think it would be reasonable to update the profile dropdown renderer to draw multiple profile types

Does this mean unfiltered, or should this be filtering? Because I just found that the DropDown for the WindowsMixedRealityDeviceManager still shows all available profiles
