### ISSUE TITLE
Data providers that do not have profiles should show nothing in the profile dropdown.

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#6769]
When adding a data provider to the input system, some do not require profiles. For such providers, MRTK should show nothing in the drop down, rather than showing all possible profiles.

Not a ship blocker for 2.2.0 as this has been the behavior since 2.0.0

**Comment by Alexees** [comment]
Instead of showing nothing in the dropdown, maybe completely removing the dropdown could be a better option?

**Comment by Troy-Ferrell** [comment]
@davidkline-ms not sure this is true.

The requiresProfile indicates that a profile must be selected but when false, a profile can still be assigned to the service/dataprovider. 

Comment on property => "Is a profile explicitly required?"

Thus there is the case of, I don't require a profile but you can give me one, in which case we should show options. 

I think larger issue may be that the following function
MixedRealityProfileUtility.IsProfileForService()
Checks for MixedRealityServiceProfileAttribute but not MixedRealityDataProviderAttribute\MixedRealityExtensionServiceAttribute
