### ISSUE TITLE
Unnecessary GC Allocation every frame by MRTK

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#6772]
## Describe the bug

MRTK allocates GC memory that is not necessary every frame. One of these is the foreach loop below for IEnumerable. There are a few others as well

MRTK.ExecuteOnAllServicesInOrder - 40B
DefaultPointerMediator.ApplyCustomPointerBehaviours - 366B
InputSimulationService.UpdateMouseDelta - 92B

There has been a mishmash of communication on the performance of foreach vs for loops. Research suggests around Unity 5 that foreach loops with List<> eliminated unnecessary garbage collection. But other collection types, such as IEnumerable, still allocated additional enumerator memory. Further, there is research to suggest foreach loops create additional assembly instructions and processing. 

References:
https://jacksondunstan.com/articles/3805
https://jacksondunstan.com/articles/4573
https://jacksondunstan.com/articles/3458
https://docs.unity3d.com/Manual/IL2CPP-CompilerOptions.html

## To reproduce

![image](https://user-images.githubusercontent.com/25975362/70001440-299d7100-1512-11ea-9774-ccede96ffba8.png)

## Expected behavior

For non-critical code paths, foreach loops are fine and mostly nominal especially if used with the appropriate collection type. But we should strive to use for loops instead of for-each loops in critical paths or large collections. We only benefit with foreach for slightly cleaner code

## Your Setup (please complete the following information)

- Unity Version 2018.4.13
- MRTK Version mrtk_development

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by davidkline-ms** [comment]
@Troy-Ferrell, do you have a list of files with critical path foreach loops? Not an issue if the answer is no. Just thought i would ask.

**Comment by Troy-Ferrell** [comment]
yes, I have started work on this. Particularity targeting 
MRTK.cs
FocusProvider.cs
MixedRealityInputModule.cs

Next level would be any pointer classes and their updates
