### ISSUE TITLE
WindowsMixedReality controllers are initialized differently depending on when the were detected

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6780]
## Describe the bug

The WindowsMixedRealityDeviceManager basically uses copy and paste code for either creating controllers on init, or when detection events are fired. Difference is that one code path calls RaiseSourceDetected first while the other calls it last, which at least leads to a missing controller model the moment the event is raised in the latter case.

## To reproduce

1. register as a IMixedRealitySourceStateHandler and access eventData.Controller.Visualizer.GameObjectProxy
It will result in a NullReferenceException for the visualizer

## Expected behavior

Visualizer is available when the detection event is fired

## Your Setup (please complete the following information)

- Unity Version 2018.3.12f1
- MRTK Version mrtk_development

## Target Platform (please complete the following information)

- WMR immersive

**Comment by davidkline-ms** [comment]
thanks for this report @Alexees! you are finding some excellent issues.

**Comment by Alexees** [comment]
I kinda feel like MRTKs QA. I just try to use it but it seems like I do this different from how it should be used and therefore just stumble over them.
Maybe there's some benefit to it in the long run, who knows :racehorse:
