### ISSUE TITLE
TrackedObjectType misses TrackedObjectType.MotionController

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6788]
## Describe the bug

The TrackedObjectType has the now obsolete MotionControllerLeft and MotionControllerRight fields. The obsolete message points towards using TrackedObjectType.MotionController... which is missing and probably not implemented anywhere.

## Expected behavior

MotionController exists as entry or the obsolete message is changed. But then the question remains if there is code specifically aiming at motion controllers and if Hands and Controllers shouldn't be handled interchangeably.

## Your Setup (please complete the following information)

- Unity Version 2018.3.12f1
- MRTK Version mrtk_development

## Target Platform (please complete the following information)

- WMR immersive

**Comment by keveleigh** [comment]
Fixed via #6791
