### ISSUE TITLE
official diminished reality support?

### ISSUE THREAD

**Issue by Lei-Wei** [microsoft/MixedRealityToolkit-Unity#6801]
is that possible to get official "diminished reality" support in this toolkit?

**Comment by Alexees** [comment]
I don't think that it will be part of this Toolkit. In VR, you don't have the real world you would do this in. In AR you see the real world with your own eyes so you'd need to add rendered patches as overlayes which might be ugly. This leaves devices that show the image via camera feed, meaning mobile phones. And for those you don't need the MRTK.

**Comment by keveleigh** [comment]
Do you have a link to more information on "diminished reality"? I'm not sure I've heard this term before.

**Comment by wiwei** [comment]
https://www.marxentlabs.com/diminished-reality-ken-moser-explains-marxent/

I think that has some interesting videos which show some of these things

FWIW, I don't think that this is something that we'll be pursuing anytime soon in this toolkit - i.e. we are focused on augmenting  + virtual worlds, not so much taking existing worlds and removing things from them.
