### ISSUE TITLE
Unity Remoting needs HolographicRemotingPlayer v 2.10

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6811]
## Describe the bug

The latest version of HolographicRemoting player on HoloLens 2 does not work with Unity 2018.4.12f1's holographic remoting emulation. An older version of the remoting player (v 2.10.10) needs to be installed.

**Comment by keveleigh** [comment]
I'm not able to repro this. I'm currently using the latest remoting player (2.0.16) with Unity 2018.4.12 and  the 1.0.15 WMR Unity package.

**Comment by julenka** [comment]
I had the same setup but it was not working on my machine. My setup was:

latest remoting player (2.0.16) with Unity 2018.4.12 and the 1.0.15 WMR Unity package.

It seems like it may work on some machine / network configurations, but not others. Perhaps we should try testing on a few more machines to determine if my machine is in the minority, or majority. We could always provide the 2.10 packages in case some people hit the same issue as I did.

**Comment by davidkline-ms** [comment]
@CDiaz-MS was also able to successfully remote using the latest player.
