### ISSUE TITLE
Grid Object Collection Anchor center does not take into account minimum count

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#6813]
## Describe the bug

When configuring a grid collection with 3 columns and anchor is 'Middle Center', if there are only 1 or 2 elements in the grid, the elements are centered based on the 3 columns (so it's behave like a Top Left anchoring)

## Expected behavior

when the number of children in the grid is less than the number of column (or rows if (Row Then Column layout), the Anchor should center elements based on the minimal number of elements, and not the number of columns.

## Screenshots

![image](https://user-images.githubusercontent.com/49415246/70311734-8484e000-1812-11ea-809b-1891d00b52ba.png)

## Your Setup (please complete the following information)

- Unity Version [2018.4.13f1]
- MRTK Version [v2.2]

**Comment by gilbdev** [comment]
not sure about wanted behavior.

- a workaround (in user code?) could be to flip rowtocolumn and columntorow when number of children is less than the specified number of row(or column)

- what do you want with 5 children in a 3 columnthenrow layout ? should the second row have its elemetns aligned to the row above (current) or should the 2 elements be centered to fit the anchor description ?

```
[ ] [ ] [ ] 
[ ] [ ] 
```
or 
```
[ ] [ ] [ ] 
  [ ] [ ] 
```

**Comment by julenka** [comment]
Hi @vaoliva I added you but then removed you because there's still ambiguity regarding correct behavior and I realized I have way more context because I wrote the feature, sorry for the add and then remove!
