### ISSUE TITLE
Add documentation and description field to MRTK profiles

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#6826]
## Describe the problem

MRTK ships with several profiles that are not clearly documented. Users don't know when to use which profiles (importing the example packages drags in quite a lot of profiles)

## Describe the solution you'd like

We should document profiles that ship with official MRTK packages so users can understand when to use them. 
The usage for each profile should also be reflected in the inspector with either a description field or a link to the documentation
Additionally we should clean up the existing profiles if there's any of the example ones that we actually don't need.

## Additional context

follow up task from  PR #6825

**Comment by polar-kev** [comment]
This issue will be addressed in large part by #10120 .

**Comment by polar-kev** [comment]
Closing since tooltips were added when hovering over the various profiles in the Editor Inspector for the MixedRealityToolkit prefab as part of #10180.
