### ISSUE TITLE
There is a code error in the MRTK Doc 

### ISSUE THREAD

**Issue by PatientEz** [microsoft/MixedRealityToolkit-Unity#6830]
## Existing Doc Link
the link is :
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/InputEvents.html#global-input-registration-example

## Bug Report
the function OnSourceDetected() and  OnSourceLost() code is same. And i think
there is something wrong with  OnSourceLost().The code in this function need to be changed

**Comment by keveleigh** [comment]
Thanks for pointing this out! I opened https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6832 to update this code.

**Comment by keveleigh** [comment]
Fixed via #6832
