### ISSUE TITLE
Missing Microsoft.MixedReality.Toolkit.Providers.UnityAR?

### ISSUE THREAD

**Issue by robinzhx** [microsoft/MixedRealityToolkit-Unity#6831]
## Describe the Issue
As document mentioned in step 1, we are supposed to download and import the Microsoft.MixedReality.Toolkit.Providers.UnityAR package from [GitHub](https://github.com/microsoft/MixedRealityToolkit-Unity/releases/tag/v2.2.0), but the page become 404,

## Feature Area
What's incorrect? What's missing?
The release version 2.2 was removed for some reasons but there is no clear reason.

## Existing Doc Link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/CrossPlatform/UsingARFoundation.html

**Comment by robinzhx** [comment]
I think the issue related to #6803 ?

**Comment by keveleigh** [comment]
You're currently looking at our development branch docs, which may be ahead of our releases. In this case, you're looking at a feature that'll ship with our 2.2 release, [currently in stabilization](https://github.com/microsoft/MixedRealityToolkit-Unity/tree/prerelease/2.2.0_stabilization), which should be released in the next day or so.

Glad you're interested in this feature! I'll update here when we ship.

**Comment by robinzhx** [comment]
I see. I will pull from the 2.2 branch then. Looking forward to hearing more news about features! Thanks for the quick follow-up! @keveleigh

**Comment by wiwei** [comment]
Closing this out - we can reopen if you're still seeing issues here once 2.2 is out!
