### ISSUE TITLE
Gltf module not working when building windows standalone

### ISSUE THREAD

**Issue by Yohdu** [microsoft/MixedRealityToolkit-Unity#6833]
## Overview
I have a fresh project in which I imported the MRTK (only the Foundation package). In my newly created scene (with just a light and a camera), I add a gameobject with a very simple script to load a GLTF model thanks the GLTF module available in the MRTK. The scripts basically calls one line of code in the Start method (I marked it as async) :
`GltfObject loadedGltfObject = await GltfUtility.ImportGltfObjectFromPathAsync("model.gltf");`

## Expected Behavior
The GLTF model is loaded and displayed at runtime.

## Actual Behavior
It works fine in the Editor, but when I build a windows standalone version, it does not work. The "await" statement never ends, it looks like the Task is stuck.

## Unity Editor Version
2019.2.9f1

## Mixed Reality Toolkit Release Version
Microsoft Mixed Reality Toolkit 2.1.0

**Comment by ashikns** [comment]
So I tried this out. The problem is that `SynchronizationContext.Current` shows up as null in standalone player. Due to this a call in `AwaiterExtensions` that creates `AsyncCoroutineRunner` instance gets posted to the AsyncCoroutineRunner queue itself. In Editor during that call SynchronizationContext shows up correctly.

**Comment by ashikns** [comment]
On further examination this seems to be coming from a background thread so it's a bug in MRTK possibly. It just happens to work in Editor. A quick fix is to force the creation of `AsyncCoroutineRunner` by first executing this - `new WaitForUpdate().GetAwaiter();`

**Comment by ashikns** [comment]
Another thing to note when building is that Unity strips away shaders you don't use. GLTF requires MRTK/Standard and Standard shaders, so if you want to preserve them use them in one of the scenes. I personally have a shader retention scene that has two cubes to preserve the two shaders.

**Comment by Yohdu** [comment]
Thank you very much, you quick fix solved it. Should I close the issue, or should I let it open since the bug is still there?

**Comment by keveleigh** [comment]
@Yohdu Feel free to leave this open. We have a few other issues around `AsyncCoroutineRunner` like #6362, so this will help us with some additional info if the issues are related. Thanks!

**Comment by AnandDixit27** [comment]
> On further examination this seems to be coming from a background thread so it's a bug in MRTK possibly. It just happens to work in Editor. A quick fix is to force the creation of `AsyncCoroutineRunner` by first executing this from the main thread - `new WaitForUpdate().GetAwaiter();`

Hi I am also facing the same issue GLTF model is loaded in Editor but not on device. Its difficult to understand this quick fix that is given. So can you please explain in detail.

**Comment by Yohdu** [comment]
@ArnandDixit27 
You only need to have any script in your scene call the instruction `new WaitForUpdate().GetAwaiter();` in the Awake or Start method (before any loading operation).

**Comment by AnandDixit27** [comment]
> @ArnandDixit27
> You only need to have any script in your scene call the instruction `new WaitForUpdate().GetAwaiter();` in the Awake or Start method (before any loading operation).

Thanks for your quick response, I will implement it.

**Comment by AnandDixit27** [comment]
> @ArnandDixit27
> You only need to have any script in your scene call the instruction `new WaitForUpdate().GetAwaiter();` in the Awake or Start method (before any loading operation).

Hi,
According to your comment I tried to quick-fix the GLTF loading on Hololens device but now I am getting Index was outside the bound of array error. Please help me to get out from this error.
![GLTFLoadErrorOnDevice](https://user-images.githubusercontent.com/49301003/71443135-46068500-272f-11ea-9439-a9c38183d96f.png)

You can see that WaitForUpdate().GetAwaiter(); is called before GLTF loading.

**Comment by AnandDixit27** [comment]
> @ArnandDixit27
> You only need to have any script in your scene call the instruction `new WaitForUpdate().GetAwaiter();` in the Awake or Start method (before any loading operation).

@Yohdu 
Even after implementing that fix given by you the GLTF model did not load on standalone device. Please help me on this.

**Comment by ashikns** [comment]
@AnandDixit27 Did you preserve the shaders as I mentioned?

**Comment by ashikns** [comment]
In general the GLTF module in MRTK is not mature and has other issues like lack of animation support. For the time being at least I'd recommend using some other library like [UnityGLTF](https://github.com/KhronosGroup/UnityGLTF) or [Gru](https://github.com/ashikns/Gru).

Disclaimer: I wrote Gru, it is not as feature complete as UnityGLTF but is much more performant.

**Comment by AnandDixit27** [comment]
> @AnandDixit27 Did you preserve the shaders as I mentioned?

Yes i have also included shader retention scene while building for device.

**Comment by AnandDixit27** [comment]
> In general the GLTF module in MRTK is not mature and has other issues like lack of animation support. For the time being at least I'd recommend using some other library like [UnityGLTF](https://github.com/KhronosGroup/UnityGLTF) or [Gru](https://github.com/ashikns/Gru).
> 
> Disclaimer: I wrote Gru, it is not as feature complete as UnityGLTF but is much more performant.

Is this Gru is compatible with MRTK because i want to model in hololens. And how will i get assembkly definition references when i import it i got GUID values but how should i map it?

**Comment by ashikns** [comment]
Are you talking about how to add an assembly definition reference? https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html
