### ISSUE TITLE
Unity AR Config SpatialTracking not applied automatically

### ISSUE THREAD

**Issue by reneschulte** [microsoft/MixedRealityToolkit-Unity#6854]
## Describe the bug

I followed the docs here with the new MRTK 2.2 how to configure for ARFoundation mobile:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/CrossPlatform/UsingARFoundation.html

It is mentioned that the SpatialTracking setting is applied automatically but it is not.
![image](https://user-images.githubusercontent.com/7439129/70613410-de1d4e00-1c08-11ea-9f42-9f97403d8bce.png)

## To reproduce

Follow the steps in the documentation. 
See that Console shows a bunch or Errors that SpatialTracking reference is missing. 

## Expected behavior

That the setting is automatically applied like the docs mention and no Console Error.

## Your Setup (please complete the following information)

- Unity Version 2019.1.14f1
- MRTK Version 2.2

## Target Platform (please complete the following information)

Android

## Additional context

As a workaround I applied the setting manually and got all working.
![image](https://user-images.githubusercontent.com/7439129/70612884-03f62300-1c08-11ea-9264-44b1aab67017.png)

**Comment by keveleigh** [comment]
@davidkline-ms Looks like we check for 2019.2 or newer, leaving out 2019.1:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/9647cf728961fa4280aa1fec12dcaf6042fba016/Assets/MixedRealityToolkit.Staging/UnityAR/Editor/ConfigurationChecker/UnityARConfigurationChecker.cs#L79

**Comment by davidkline-ms** [comment]
Nice catch, @reneschulte. I had moved from Unity 2019.1 to .2. If you are importing unitypackage files, you can change the line mentioned above by @keveleigh to contain UNITY_2019_1_OR_NEWER
