### ISSUE TITLE
ARFoundation is not optional

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6856]
## Describe the bug

Just updated mrtk_development and got forced to add ARFoundation. Even removing the missing reference in the ASMDEF seems to be overridden by some mechanism.

Furthermore, this page describes how to use not, but not how to not use it:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/CrossPlatform/UsingARFoundation.html

## To reproduce

1. Import current MRKT without having the ARFoundation package ready

## Expected behavior

You should be able to choose

## Your Setup (please complete the following information)

- Unity Version 2018.3.12f1
- MRTK Version mrtk_development

## Target Platform (please complete the following information)

- Editor

**Comment by davidkline-ms** [comment]
@Alexees, are you using a clone of the repository? In that instance, it is currently "on" by default.

If you are importing packages, it is safe to remove the MixedRealityToolkit.Staging folder or to not import the Providers.UnityAR package.

To resolve the repository clone issue, i am looking into adding a #define around the UnityAR prorovider that would be set only if AR Foundation is imported.

**Comment by Alexees** [comment]
> @Alexees, are you using a clone of the repository? In that instance, it is currently "on" by default.

Yes, it's a clone. It's faster to stay up to date this way 
> If you are importing packages, it is safe to remove the MixedRealityToolkit.Staging folder or to not import the Providers.UnityAR package.

will do
> To resolve the repository clone issue, i am looking into adding a #define around the UnityAR provider that would be set only if AR Foundation is imported.
awesome

**Comment by Alexees** [comment]
@davidkline-ms I updated to the latest version now. What do I have to do to get the code that's supposed to check for ARFoundation compiled without adding it in the first place because the existing ASMDEFs fail due to the lack of that reference?
In the project folder I see the regular ASMDEF, one ending on 2018 and one ending on 2019. If I remove the former, the Editor ASMDEF complains about its absence
