### ISSUE TITLE
HandTrackingProfile and HandJointService documentation link goes to 404

### ISSUE THREAD

**Issue by timGerken** [microsoft/MixedRealityToolkit-Unity#6857]
## Describe the bug

Clicking on the [Documentation] link in the Hand Tracking Settings goes to a non-existent page

## To reproduce

Click on the [Documentation] link in Hand Tracking Settings

Broken link: [https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSystem/HandTracking.html](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSystem/HandTracking.html)

```
Affected source files:
C:\src\github\microsoft\mrtk-Unity [mrtk_release ≡]> findstr -s "Input.*Hand.*.html" *.cs
Assets\MixedRealityToolkit\Definitions\Devices\MixedRealityHandTrackingProfile.cs: [HelpURL("https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSystem/HandTracking.html")]
Assets\MixedRealityToolkit\Providers\Hands\HandJointService.cs: [HelpURL("https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSystem/HandTracking.html")]
Assets\MixedRealityToolkit.Providers\WindowsMixedReality\WindowsMixedRealityUtilities.cs: /// Please see https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSystem/HandTracking.html#net-native for more info.
```
## Expected behavior

Correct link: [https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/HandTracking.html](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/HandTracking.html)

## Your Setup (please complete the following information)

- Unity Version [2018.4.13f1]
- MRTK Version [v2.2, by NuGet]

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
Fixed via #6859
