### ISSUE TITLE
MixedRealityLineRenderers and Data Providers perform more work than necessary

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#6864]
## Describe the bug

MixedRealityLineRender is updating the Unity LineRenderer every late update. The component should be redesigned to only update when necessary especially for properties that have changed.

## To reproduce

Look at class. Many properties are even hardcoded every lateupdate which could be done in OnEnable

## Your Setup (please complete the following information)

- Unity Version 2018.4 LTS
- MRTK Version MRTK_Dev

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Railboy** [comment]
Incoming changes include pushing major line renderer work onto background threads and caching line data provider local positions.

**Comment by keveleigh** [comment]
@Railboy This is quite old, but do you remember if

> major line renderer work onto background threads and caching line data provider local positions.

was completed?

**Comment by Zee2** [comment]
I believe #6863 closed this.
