### ISSUE TITLE
How does SurfaceMappingSource's EventHandlers work?

### ISSUE THREAD

**Issue by SuperShinyEyes** [Microsoft/MixedRealityToolkit-Unity#687]
Hi, 

I've been reading [`SpatialMappingSource.cs`](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingSource.cs).
I couldn't understand how this works.
```csharp
// SpatialMappingSource.cs
public event EventHandler<DataEventArgs<SurfaceObject>> SurfaceAdded;
public event EventHandler<DataEventArgs<SurfaceUpdate>> SurfaceUpdated;
public event EventHandler<DataEventArgs<SurfaceObject>> SurfaceRemoved;
public event EventHandler<EventArgs> RemovingAllSurfaces;

protected void AddSurfaceObject(SurfaceObject toAdd)
{
    ...
    var handlers = SurfaceAdded;
    if (handlers != null)
    {
        handlers(this, DataEventArgs.Create(toAdd));
    }
}
...
```
I also checked out [`DataEventArgs.cs`](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/DataEventArgs.cs).

```csharp
namespace HoloToolkit.Unity
{
    public static class DataEventArgs
    {
        public static DataEventArgs<TData> Create<TData>(TData data)
        {
            return new DataEventArgs<TData>(data);
        }
    }

    [Serializable]
    public class DataEventArgs<TData> : EventArgs
    {
        public TData Data { get; private set; }

        public DataEventArgs(TData data)
        {
            Data = data;
        }
    }
}
```
But this didn't really tell me anything.

How does this event handler works? When are they called and what do they do?
I assume that this is used by `SurfaceMappingObserver` as a subclass but I can't figure out how.

**Comment by davidkline-ms** [comment]
MR Spatial 230 (formerly Holograms 230) demonstrates these events.

https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-230
