### ISSUE TITLE
Deploy to HoloLens 2 via USB doesn't work

### ISSUE THREAD

**Issue by julianloehr-kg** [microsoft/MixedRealityToolkit-Unity#6877]
## Describe the bug

Deploying to a HoloLens 2 using the Deploy Window via USB result in the error `Authentication failed! Device Not Found | No Response Headers`.

The issue seems to be that on HoloLens 2 the device portal does not feature non-SSL access anymore. Accessing 'http://127.0.0.1:10080/' return a '307 Temporary Redirect' with 'Location: https://127.0.0.1:10443/' in the header. The Unity WebRequest does not follow that redirect and the deployment fails.

## To reproduce

1. Build the MRTK or any project with the latest MRTK installed. Using the MRTK Build Window.
2. Connect a Hololens 2 via USB. Make sure the device portal is enabled.
3. Go to the Deploy Window
4. Enter Device Portal credentials.
5. Click on 'Install' for the app package.

## Expected behavior

Expected behavior: App package is successfully deployed and installed on the Hololens 2.
Actual behaviour: Deployment fails with error `Authentication failed! Device Not Found | No Response Headers`.

## Your Setup (please complete the following information)

- Unity Version 2019.1.14f1
- MRTK Version v2.2.0

## Target Platform (please complete the following information)

- HoloLens 2 OS Version 18362.1039

## Additional context

Changing the code so  the deployment use SSL also for USB-Connected HoloLens 2 devices results in an SSL error. (We do not install the Self-Signed Certificates on our machines, due to the amount of HoloLens units and development machines. Its not feasible for us to install every device certificate on every development machine. Especially as you have to redo that every time you flash the device.)

One solution for that would be to implement a custom CertificateHandler for the device portal requests that simply accepts all SSL certificates. However that may rise security concerns for some users.

**Comment by evmill** [comment]
Just to be clear are you installing from Device Portal after building with Visual Studio, or does Unity 2019 have a Deploy window that 2018.4.x LTS doesn't? 

Also I'm not sure how many HoloLens 2 you have but if your concern is installing in bulk, and having devices flashed multiple time you may want to look into using Intune for your MDM solution to just push your app(s) to the device automatically.

**Comment by julianloehr-kg** [comment]
I'm talking about the MRTK _Build Window_, specifically the _Deploy Options_ tab.

The issue affects our development procedures, to quickly build and deploy feature and development builds to development devices.
