### ISSUE TITLE
Extend spatial awareness documentation to include code examples

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#6881]
## Describe the Issue
Users can't find out easily how to disable/enable spatial awareness in code . We're currently only describing how to use the feature in the unity editor. 

It would be great if we can add some documentation for developers that want to modify / use the feature in code. 

## Feature Area
Spatial awareness - code documentation

## Existing Doc Link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SpatialAwareness/SpatialAwarenessGettingStarted.html

**Comment by Troy-Ferrell** [comment]
It does exist here: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SpatialAwareness/UsageGuide.html

I'll look at trying to bubble it up more
