### ISSUE TITLE
Use custom overlap sphere test for Sphere/Poke Pointers

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#6890]
## Describe the bug

Both the sphere pointer and poke pointers perform an overlap sphere collision test every frame using UnityEngine.Physics.OverlapSphereNonAlloc

Even though a layermask is provided to filter the physics operation, both only care about colliders that have a corresponding NearInteractionGrabbable or NearInteractionTouchable variant on them. However, we are searching all colliders (on a valid layer) in the scene and then from these results checking if they have the right component. 

We could probably save on performance by doing the reverse. If we have all NearInteraction* Game Objects register themselves in some static cache, then every frame we just do a bounds check between a sphere and that Collider. 

```csharp
for (all of my NearInteractionObjects)
{
    if (nearCollider.enabled && spherePointerBounds.contains(nearCollider.bounds)
    {
     // then do normal stuff
    }
}
```

The two key facts to consider where this proposal might be more beneficial.
1. num of collidable objects >= num of nearinteractiongrabble is always true. It's more likely we have lots of collider objects in the scene
2. GetComponent is fairly expensive as well. 

UnityEngine.Physics.OverlapSphereNonAlloc might be greatly optimized by the engine under the hood. In particular, I am worried about how the collider.bounds is computed and the contains/intersect API performance

We could also add a simple distance test first before doing bounds.intersect

## To reproduce

Look at 
FindClosestTouchableForLayerMask
TryUpdateQueryBufferForLayerMask

Also some data to support this:
In HandsInteractionExample scene, if I filter the scene view with the following queries, I get the following number of GameObjects. So again principal 1 states above for benefits is important

t:NearInteractionGrabbable => 19
t:NearInteractionTouchable => 50
t:collider => 80

## Expected behavior

We should optimize as much as possible here because 
1) This operation happens every frame
2) If both hands are up, any savings are multiplied by 4 (two pointers each hand)

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Troy-Ferrell** [comment]
@julenka @thalbern FYI, I stumbled upon this as I was looking into #6870

**Comment by keveleigh** [comment]
>If we have all NearInteraction* Game Objects register themselves in some static cache

We used to have this! Looking now...it's gone? I'm not sure when / why though

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/2e755a9c9e5d369909926d522f82bbd67146af91/Assets/MixedRealityToolkit.Services/InputSystem/NearInteractionTouchable.cs#L95

**Comment by keveleigh** [comment]
Oh looks like that's what was replaced with `OverlapSphereNonAlloc`

**Comment by Troy-Ferrell** [comment]
Ahh turns out their was a bug (very long ago) on the inverse of this issue #4218. That actually resulted in a PR to remove a static instances list for testing. Need to investigate why this was the case
