### ISSUE TITLE
Duplicated TestPointer classes

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#6894]
## Describe the bug

There are two TestPointer classes in the tests package

Microsoft.MixedReality.Toolkit.Tests.TestPointer
Microsoft.MixedReality.Toolkit.Tests.InputSystem.TestPointer

Looks like these can be consolidated into one for re-use

## To reproduce

Looks like SetFromTestProxy() just needs to be extracted

## Expected behavior

Weird that there are two classes with same name and basically same principal. 

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by davidkline-ms** [comment]
While not ideal, each of these TestPointer classes lives in a separate assembly (one for edit mode tests, the other for play mode tests).

It is unlikely that these will be merged or differentiated at this point in the MRTK v2.x product cycle.
