### ISSUE TITLE
MRTK should use the new Microsoft Spatializer with hardware offload support

### ISSUE THREAD

**Issue by ashtat** [microsoft/MixedRealityToolkit-Unity#6897]
We have released a new [Unity Spatializer plugin](https://github.com/microsoft/spatialaudio-unity)  that leverages hardware offloaded spatial audio processing on HoloLens 2 freeing up the CPU for the app. MRTK should switch over to this new plugin instead of using the legacy MS-HRTF spatializer.

**Comment by davidkline-ms** [comment]
We should ensure that the MRTK documentation recommends acquiring and using the Microsoft Spatializer. I will follow up.

**Comment by davidkline-ms** [comment]
Moving this to MRTK3. Documentation regarding spatializers is currently planned and this issue is a large part of the expected document.

**Comment by AMollis** [comment]
@marlenaklein-msft  there are 5 issues related to spatial audio,  Can you help provide more context on these issues, and resolve any deduplicates?

The spatial audio issues area:

1. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6897
3. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10744
4. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10979
5. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11176
6. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11177
