### ISSUE TITLE
Duplicate manager/provider objects after build

### ISSUE THREAD

**Issue by Helco** [microsoft/MixedRealityToolkit-Unity#6907]
## Describe the bug

After building a Unity project every object in `MIxedRealityToolkit` is duplicated. 
I tested only in 2020.1.0a16 as this version is required for my project.

## To reproduce

1. Create new project with MRTK packages imported
2. `Mixed Reality Toolkit -> Add to Scene and configure`
3. `Build Unity Project` in the `Build Window` of MRTK
4. Observe that every object in `MixedRealityToolkit` (e.g. `HandJointService`, `WindowsMixedRealityDeviceManager`) exists twice.

## Expected behavior

No object duplication after building

## Your setup (please complete the following information)

- Unity Version 2020.1.0a16
- MRTK Version 2.2.0

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by Naphier** [comment]
Happening in Unity 2019.3.3f1 with MRTC v2.3.0 too.

**Comment by eusebiu** [comment]
This also happens on Unity 2020.1 with MRTK Quest.

**Comment by jbienzms** [comment]
Do we know the root cause? Also what is the workaround? Should the user manually delete one of each of the duplicates or is there a better fix?
