### ISSUE TITLE
Cannot properly open project in OSX

### ISSUE THREAD

**Issue by Helco** [microsoft/MixedRealityToolkit-Unity#6910]
## Describe the bug

When opening any MRTK project with Unity on a Mac (e.g. to use the experimental iOS support), the following error is printed to console many times:

```
DirectoryNotFoundException: Could not find a part of the path 'Applications/Unity/Hub/Editor/2020.1.0a16/Data\Resources\PackageManager\BuiltInPackages'.
```

Between console printouts a progress window with the title `Building MSBuild projects...` appears for a split-second.
The editor cannot be used with these errors interrupting any action.

## To reproduce

1. Create a Unity project with MRTK imported (e.g. on a Windows computer)
2. Open that project on an OSX computer
3. Observe the errors flow in

## Your setup (please complete the following information)

- Unity Version 2020.1.0a16
- MRTK Version 2.2.0

**Comment by genereddick** [comment]
Looks like this is being addressed, see @keveleigh 's comment in  #6947
