### ISSUE TITLE
Unity 2019.3 marks many PlayerSettings methods obsolete

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#6918]
## Describe the bug

As part of Unity moving towards their new XR Management pipelines, they've started to deprecate many of the existing APIs. This looks to have started with their `PlayerSettings` APIs

![image](https://user-images.githubusercontent.com/3580640/70951313-eebe3180-2017-11ea-874a-e0403b1f906c.png)

We may need to rework some of the optimization utilities to ask MRTK data providers for their settings, instead of depending on the built-in ones.

## Your setup (please complete the following information)

- Unity Version 2019.3.0f3

**Comment by davidkline-ms** [comment]
Adding pragmas around the newly obsolete methods/properties.

Will also add xr management versions of the functionality and update the configurator based on whether or not the appropriate unity packages are installed

**Comment by thalbern** [comment]
![image](https://user-images.githubusercontent.com/36998103/73369742-02151b80-42ab-11ea-8054-ebce7e294bae.png)
Also getting a bunch of obsolete warnings for boundary system and project configurator when importing our latest release packages (drop jan 29)

**Comment by SimonDarksideJ** [comment]
I would advise against Pragma statements @davidkline-ms , rather bound things in the standard Unity
```
#if UNITY_VERSION
```
Ultimately though, it's better to update the functionality to use non-deprecated features, else we are just incurring technical debt

**Comment by davidkline-ms** [comment]
@SimonDarksideJ, XR SDK and the legacy API exist side-by-side in Unity 2019.3. Customers can choose to use the legacy API or to install the XR Management, and device plugins, to enable the new API.

When an API is removed, rather than deprecated, from Unity, MRTK will use version defines instead of pragmas.

**Comment by keveleigh** [comment]
>rather bound things in the standard Unity

For this one, it's more based on Unity packages and Unity XR pipelines than a specific Unity version. There may be an opportunity to create custom defines based on package installation state though.

>When an API is removed, rather than deprecated, from Unity, MRTK will use version defines

I think that's true in this case, where the APIs truly live side-by-side and are completely different implementations, with various variables to consider when switching from one to the other.
In many cases though, where Unity deprecates an API between Unity versions that has a clear replacement, I think we'd just the standard Unity `#defines` (or package version `#defines`) where possible.
