### ISSUE TITLE
2.3.0 Release Notes and Breaking Changes

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#6922]
This issue tracks the new features and breaking changes that are coming in 2.3.0. These will eventually make their way to the github.io docs during the release process.

Please use this issue and add your release notes and breaking changes (and associated upgrade instructions) here.

**Comment by artsouflMS** [comment]
[Pinch slider orientation #6858 ](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6858)
PinchSlider's visuals such as TrackVisuals and TickMarks, rotate along the SliderAxis every time user updates the value of the SliderAxis

**Comment by Troy-Ferrell** [comment]
#6919 
StartupBehaviour now drives start behaviour for both initialize and on re-enable() in spatial awareness system

**Comment by Troy-Ferrell** [comment]
#6863 
`ShellHandRayPointer.lineRendererSelected` and `ShellHandRayPointer.lineRendererNoTarget` have been deprecated in favor of `ShellHandRayPointer.lineMaterialSelected` and `ShellHandRayPointer.lineMaterialNoTarget` respectively

**Comment by keveleigh** [comment]
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6989

Namespace of `WindowsMixedRealityUtilities` changed from `Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input` to `Microsoft.MixedReality.Toolkit.WindowsMixedReality`.

**Comment by davidkline-ms** [comment]
#6891 - confirm the changes currently documented are accurate

**Comment by Troy-Ferrell** [comment]
#7012 - ControllerPoseSynchronizer.handedness (private serialized field) deprecated
#7012 - ControllerPoseSynchronizer.Handedness setter removed and fixed

**Comment by thalbern** [comment]
#7070 - the following prefabs are now using the PressableButton component instead of TouchHandler:
- AnimationButton
- Button
- ButtonHoloLens1
- ButtonHoloLens1Toggle
- CheckBox
- RadialSet
- ToggleButton
- ToggleSwitch
- UnityUIButton
- UnityUICheckboxButton
- UnityUIRadialButton
- UnityUIToggleButton

**Comment by julenka** [comment]
#7016 and #6870 ensure that poke and grab pointers are not actually enabled when they are interacting with objects that are not visible to the camera. This can help prevent accidental grabs and touch interactions. If you wish for pointers to grab / touch colliders that are not visible, deselect the "ignore colliders not in FOV" checkbox in the GrabPointer and PokePointer prefabs (after cloning them to make your own :-) )

**Comment by julenka** [comment]
I believe we also want to call out a few new experimental features:

1. (Experimental) Non-native keyboard  #6492 
![image](https://user-images.githubusercontent.com/168492/73916489-5b181d00-4872-11ea-9c1e-7ef6738a9f6f.png)

2. (Experimental) Hand coach #6493 
![image](https://user-images.githubusercontent.com/168492/73916521-771bbe80-4872-11ea-80ce-c117253e3c24.png)

3. (Experimental) Follow solver (solver that matches HoloLens 2 shell behavior). #6981 
![follow_solver](https://user-images.githubusercontent.com/47415945/71829132-d338ca80-309b-11ea-97eb-9afc341a21ed.gif)

4. (Experimental) ObjectManipulator #6924 (@thalbern can you add image please?)

5. (Experimental) BoundsControl #6924 (@thalbern  can you add image please?)
