### ISSUE TITLE
Add support for Windows scene understanding as a spatial observer

### ISSUE THREAD

**Issue by radicalad** [microsoft/MixedRealityToolkit-Unity#6928]
## Describe the problem

HoloLens 2 supports the Windows scene understanding SDK. This is a great candidate for a spatial system observer. Scene understanding provides a high-level environmental representation via object quads, object meshes, and a world water-tight SR mesh snapshot.

This service would make common SU scenarios more easily achieved as the overhead would be built into the observer and users would simply consume environmental data via the spatial awareness event system.

## Additional context

More info here: https://docs.microsoft.com/en-us/windows/mixed-reality/scene-understanding

**Comment by mr0ng** [comment]
Excited for this. Following closely.

**Comment by reneschulte** [comment]
Agreed that Scene Understanding should be integrated nicely into the MRTK.

**Comment by MaxWang-MS** [comment]
Scene Understanding is now available in MRTK 2.6.

**Comment by malikkayaalp** [comment]
Hello there. I am working on a project. Scene understanding demo works without any problems. However, I cannot activate world mesh in my own project. I choose World as the surface type. And I'm calling the mesh data to the stage. As a material, I use the material that comes with the demo. I would be glad if you could help. Thanks.

Holollens 2
MRTK 2.6.1
Unity 2020.2.1f1
