### ISSUE TITLE
Unity 2019.3.0f3 Unable to register IMixedRealityInputDeviceManager on HL2

### ISSUE THREAD

**Issue by yacuzo** [microsoft/MixedRealityToolkit-Unity#6929]
## Describe the bug

When I upgrade our 2019.2 project to 2019.3 and build for HoloLens 2 I do not get any gesture/hand input. 

## To reproduce

1. Take a working 2019.2 project using articulated hands
2. Upgrade to 2019.3
3. Build ARM for HL2 with the usual settings
4. Deploy to HL2 and start the app
5. Only gaze pointer available, no reaction to hands or gestures

## Expected behavior

It works as for 2019.2.

## Your setup (please complete the following information)

- Unity Version 2019.3.0f3
- MRTK Version 2.1

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

Unity log has a few of these:
 "Unable to register IMixedRealityInputDeviceManager service with a null concrete type"

I have tried re-creating MRTK configuration settings, and using the default settings, with no luck. 
I have tried using both old and new Unity XR SDK systems.

There is so many nice new features in 2019.3 I hope you at MRTK don't take too long to support it.

**Comment by keveleigh** [comment]
>I have tried using both old and new Unity XR SDK systems.

Work for the new XR SDK system is ongoing and will ship in MRTK 2.3.

As far as the old system not working, that's strange. Can you check your input system data providers in your profiles to see if any types are highlighting red? That's typically what
>"Unable to register IMixedRealityInputDeviceManager service with a null concrete type"
is referring to. You should be able to click Repair to try repairing them, if you aren't using the default profiles.

**Comment by yacuzo** [comment]
I think you may close this. I can't remember this now, but we do have a project working. It may be that some combination of deleting Unity cache, resetting the profiles or upgrading to MRTK 2.2. solved it.

**Comment by gerwalk** [comment]
I'm having the exact same problem in Unity 2019.4.0 on the HoloLens 2 with MRTK 2.4, using the old XR system.
