### ISSUE TITLE
Some popup windows on Unity Mac are poorly formatted, content below fold

### ISSUE THREAD

**Issue by genereddick** [microsoft/MixedRealityToolkit-Unity#6933]
## Describe the bug
On Mac some of the popup display windows in the Unity Editor have too much space at the top so that no content appears without having to expand the window.

## To reproduce
Try various options  in the Mixed Reality Toolkit Menu, the Configurator is the screenshot but I saw others.

Problem is in Unity Mac

<img width="681" alt="Screen Shot 2019-12-18 at 1 25 54 PM" src="https://user-images.githubusercontent.com/1033793/71125111-391beb80-219b-11ea-9de5-3dc4ec85d33b.png">

No scrollbar appears so it isn't obvious that there is more content unless you expand the window.

<img width="656" alt="Screen Shot 2019-12-18 at 1 38 41 PM" src="https://user-images.githubusercontent.com/1033793/71125546-01fa0a00-219c-11ea-849d-8c787b11b1b4.png">

**Comment by keveleigh** [comment]
Which Unity version are you using? Possibly related to #6330?

**Comment by genereddick** [comment]
I'm using 2019.2.17

**Comment by Troy-Ferrell** [comment]
Looks like this is fixed in latest 2019.2 and 2019.3 versions

![image](https://user-images.githubusercontent.com/25975362/73482381-7fe03200-4352-11ea-822a-b149cab83bc6.png)
