### ISSUE TITLE
Unity PhotoCapture API Failure on HoloLens 2

### ISSUE THREAD

**Issue by dw-ffs** [microsoft/MixedRealityToolkit-Unity#6951]
## Overview
Unity PhotoCapture/PhotoCaptureFrame API works fine taking photo and retrieving CameraToWorld and CameraProjection matrices on HoloLens 1, however, it always fails to provide those two matrices on HoloLens 2. Does anyone have an idea if this is an MRTK related issue or have any insight to share? Thanks!

## Expected behavior
PhotoCaptureFrame provides CameraToWorld and CameraPojection matrices on HoloLens 2.

## Actual behavior
PhotoCaptureFrame fails to provide CameraToWorld and CameraPojection matrices on HoloLens 2. No location data available.

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity editor version
2019.2.17f.

## Mixed Reality Toolkit release version
MRTK 2.2

**Comment by wiwei** [comment]
@dw-ffs are you able to use these successfully when the MRTK isn't in the picture? These are Unity APIs (which under the covers use other UWP/WSA specific APIs AFAIK), and I assume the best way to get this started would actually to be to file a Unity bug - from there the right things will get set in motion (i.e. to engage devs on both the Unity and MS side)

**Comment by wiwei** [comment]
Feel free to reopen with more information - given the data here it sounds like this is an issue at the Unity layer or below.
