### ISSUE TITLE
GLTF Model never loaded Hololens device.

### ISSUE THREAD

**Issue by AnandDixit27** [microsoft/MixedRealityToolkit-Unity#6955]
## Overview
I have imported MRTK toolkit v2.1.0 in newly created fresh unity project. And tried to run Gltf-Loading-Demo scene to load provided Avocado.gltf model in editor as well as on hololens-1 device. 
The scripts basically calls one line of code in the Start method (it marked as async) :
GltfObject loadedGltfObject = await GltfUtility.ImportGltfObjectFromPathAsync("Avocado.gltf");

**Model is loaded in unity editor but it never loaded on hololens-1 device**.

I also tried quick-fix given on this issue #6833 for loading of GLTF model but still the model didn't load on device. 

Error came that attached here.
![GLTFLoadErrorOnDevice](https://user-images.githubusercontent.com/49301003/71505485-5a6b8e80-28a3-11ea-9640-507463ec9962.png)

Please help me with this.

## Expected behavior
The GLTF model is loaded and displayed at runtime on hololens-1 device.
## Actual behavior
It works fine in the Editor, but when I build for hololens-1 device, it does not work.
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity editor version
Unity 2018.4.12f1

## Mixed Reality Toolkit release version
Microsoft Mixed Reality Toolkit v2.1.0

**Comment by amol989** [comment]
I am facing the same issue in my project.

**Comment by ravip** [comment]
Yes. Facing same issue. Please address.

**Comment by shekhar331** [comment]
I am facing similar issues, the glTF models loads  in the Editor but fails on Hololens 1 Device
