### ISSUE TITLE
When can I support iris recognition?

### ISSUE THREAD

**Issue by qazqaz12378** [microsoft/MixedRealityToolkit-Unity#6956]
When can I support iris recognition?

Need to use iris recognition to confirm user information in unity to facilitate user identification and open corresponding functions

**Comment by Troy-Ferrell** [comment]
@qazqaz12378 assuming you are talking about Hololens 2 iris recognition. On HL2 iris recognition is used for Windows Hello authentication. You can use the Windows APIs to identify who is logged in.

If you have other questions about HL2, get support directly: https://support.microsoft.com/en-us/hub/4338666/hololens-help
