### ISSUE TITLE
Unity Exception" Destroy

### ISSUE THREAD

**Issue by TerraSame** [microsoft/MixedRealityToolkit-Unity#6962]
Hello...
While working with the HoloLens and the Odyssey HMD, I have run into a very persistent Exception. Where upon switching to a new scene I get the exception each time. Then after 4 or 5 scene switches there is a major crash.

I am creating numerous Scenes where each Scene has an interactive button that launches a next Scene. Upon launching a new Scene from a launched Scene, or for that matter, switching from any Scene to another Scene, I get a nasty Development Console message saying:
______________________________________________________________________
Unity Exception" Destroy can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers instead move initialization code to the Awake or Start function.
______________________________________________________________________

So that's it ! Is it me? Maybe Unity? Or could it be the MRTK system?
I get this nasty situation  no mater the project such as if I start a simple project and compile, then fire up and switch a scene I always get this issue.

I have attached  to this message the "Player Log" file, where you can see all is well until I switch a scene, I do it a few times then you will see the crash at the end. According to the Player Log, (we believe) this looks to to have something to do with - Speech.DictationRecognizer.Dispose ???

Player Log File:
[Unity Player Log.txt](https://github.com/microsoft/MixedRealityToolkit-Unity/files/4012735/Unity.Player.Log.txt)

To reproduce:
Simply fire up your Hub Example, compile and launch. Switch to a few different scenes then check your Player Log.

My setup:
- This occurs from Unity Version 2019.1.14f1 to the newest, that I am presently using, 2019.2.17f1
- Microsoft.MixedReality.Toolkit.Unity.Examples.2.2.0.unitypackage

Target platforms:
- HoloLens
- WMR immersive - Samsung Odyssey 

Also, I have researched on the www and found others who have wrestled with this exception.
For example:
https://forum.unity.com/threads/load-can-only-be-called-from-the-main-thread-error-on-changing-scenes.382574/

Any advice as to a way to terminate this bug will be greatly appreciated...
I look forward to being enlightened and if anything else is requested of me I will be most eager to respond.
Thanks, Paul
paul@terrasame.com
www.terrasame.com

**Comment by Alexees** [comment]
This got me interested and found this thread:
https://forum.unity.com/threads/error-this-value-can-only-be-destructed-on-mainthread-when-doing-dispose.585607/

According to it, Dispose might not be working unless the DictationRecognizer was stopped, even though [the official documentation](https://docs.unity3d.com/540/Documentation/ScriptReference/Windows.Speech.DictationRecognizer.html) does not state anything like it. Could be worth trying to call Stop before Dispose.

**Comment by TerraSame** [comment]
Hello Alexees... Good of you to respond... Yes agreed as we have been looking for an answer and wrote the code bite to stop but can't find where to add the stop. I think it 
needs to be added in a dll...  I found a work around for this issue by recreating the entire project in the format of the "Hub Example". The crashes are gone and the fade between scenes is a nice add. BUT, now, there seems to be another BUG where it is not possable to get the sky box running for HMD/Odyssey as the clear flags constantly change to color at run time... I would like to compile for all uwp devices... If it isn't one bug it's another...
Thanks Alexees
Paul

**Comment by TerraSame** [comment]
Update:
I said that by using the Hub Example that all crashes are gone. This is only 1/2 correct as the crashes are gone when running through the HMD Odessey but the same crash occurs when running through the HoloLens...
Thanks

**Comment by TerraSame** [comment]
I have figured out how to get the sky box to work. And I have created a bug report with Unity about the exception crashes. They are presently looking into this. Thanks

**Comment by keveleigh** [comment]
We've made improvements across profile switching, scene switching, and the examples hub over the last couple years. I'm going to close this out now, but please re-open if you're still seeing this.

**Comment by TerraSame** [comment]
Okay... Thanks!
