### ISSUE TITLE
Allow InputSimulationService in standalone builds

### ISSUE THREAD

**Issue by ar51-nadav** [microsoft/MixedRealityToolkit-Unity#6966]
## Describe the problem

When developing a complex AR project, I would like to use the InputSimulationService for testing the game's logic outside of the Unity editor. For example, running several builds to test networking.
Unfortunately, this is currently impossible since the simulation service is using the MixedRealityToolkitFiles utility to load files from the project folder hierarchy.

A comprehensive explanation of this can be found here:
https://stackoverflow.com/questions/56601801/is-it-possible-to-force-the-use-of-the-mrtks-inputsimulationservice-in-a-build

## Describe the solution you'd like

I would like the option to build the unity project with the InputSimulationService enabled.
I believe there's no need to access the project folder structure from this script and instead use Unity's Scriptable Objects to store the pose data the simulation service requires.

## Describe alternatives you've considered

Currently, for testing things like multiplayer, I have to run several instances of the unity editor so I can have the simulation service.
I thought about creating an alternative simulation service but since I need the hand gestures simulation it would basically be duplicating all of the service's logic.

**Comment by Troy-Ferrell** [comment]
Related #3692
