### ISSUE TITLE
Proposal: Shorten folder names to reduce instances of exceeding path length limitations

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#6985]
Every so often, a customer encounters an error that appears as if there is a bug in an MRTK component. Many times, these issues root cause down to a long path name.

Historically, Windows has had a max path length of 260, of which 256 characters are usable between "x:\" and the null terminator.

Today, every MRTK folder contains the fully spelled out "MixedRealityToolkit" which consumes 19 of the 256 allowable characters.

This proposal would replace those 19 characters with "MRTK" and reduce each path length by 15.

NOTE: If approved, the change would manifest itself as many hundreds of files under the Assets folder being renamed.

- [x] MixedRealityTookkit (#7512)
- [x] MixedRealityToolkit.Examples (#7509)
- [x] MixedRealityToolkit.Extensions (#7497, #7502)
- MixedRealityToolkit.Generated (not being renamed)
- [x] MixedRealityToolkit.Providers (#7491)
- [x] MixedRealityTookit.SDK (#7494)
- [x] MixedRealityToolkit.Services (#7479, #7492)
- [x] MixedRealityToolkit.Tests (#7508)
- [x] MixedRealityToolkit.Tools (#7504)
- [x] Update documentation links and references (#7529)
- [x] Update packaging steps in CI
    - [x] .unitypackage
    - [x] NuGet

**Comment by keveleigh** [comment]
As a follow-up consideration, do we also want to make the change proposed in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4864? It'll add 5 characters back, but could help with structure

**Comment by keveleigh** [comment]
Or even go futher, drop the `MRTK.` in these folders, and use the preceding folder as the MRTK designation

**Comment by julenka** [comment]
Small request as I was looking for this issue description for context. Could you please explain what each folder will be renamed **to** in the issue? So, MixedRealityToolkit.Examples -> MRTK/Examples
