### ISSUE TITLE
Cursor should not rely on concrete implementation of ICursorModifier

### ISSUE THREAD

**Issue by Danta1st** [Microsoft/MixedRealityToolkit-Unity#699]
As stated in the title, the cursor should not rely on the concrete implementation of an ICursorModifier, but rather call GetComponent on the Interface itself for better compliance with the Open/Closed principle.

Current code from the Cursor class aproximately line 265.
```c#
        protected virtual void OnFocusedObjectChanged(GameObject previousObject, GameObject newObject)
        {
            TargetedObject = newObject;
            if (newObject != null)
            {
                OnActiveModifier(newObject.GetComponent<CursorModifier>());
            }
        }
```

**Comment by StephenHodgson** [comment]
This is no longer the case
