### ISSUE TITLE
Updating Controller mapping profiles fails when adding new entry

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#6991]
## Describe the bug

Updating the controller mappings fail once a mapping for a new controller was created and you add another mapping to it.
The problem is that the code assumes that the current profile and the new entries are of the same size, which they might not:
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/eee7a55e3cfd99526f20ecdbde34480990bf2a5d/Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMapping.cs#L141-L157

## To reproduce

1. Add an additional mapping to any controller and choose MixedRealityToolkit -> Utilities -> Update -> Controller Mapping Profiles

## Expected behavior

Updating profiles works no matter the size

## Your setup (please complete the following information)

- Unity Version 2018.3.12f1
- MRTK Version mrtk_development

## Target platform (please complete the following information)

- Editor (Android)

**Comment by Alexees** [comment]
While trying to update the code I ran into a problem:
I added a new mapping entry in second place. Since the id's get compared too, every mapping except the first is off. Now the question is, what are the really relevant parts if you want to keep your your action mapping intact?

I actually ran a good result when I left the id out of the comparison

**Comment by Alexees** [comment]
On second thought, maybe the comparsion should always be like the implementation I did. consider the case that you change something without altering the size...

**Comment by keveleigh** [comment]
>On second thought, maybe the comparsion should always be like the implementation I did. consider the case that you change something without altering the size...

I think that makes sense to me!
