### ISSUE TITLE
Graduate Follow Solver from experimental

### ISSUE THREAD

**Issue by MenelvagorMilsom** [microsoft/MixedRealityToolkit-Unity#6994]
Follow solver was specified as a feature request in #5713. This feature was added to experimental in #6981. In upcoming releases we should graduate the solver out of experimental. This will require the addition of documentation.

This issue can also be used as a place to discuss possible improvements we can make to the follow solver.

**Comment by cre8ivepark** [comment]
@MenelvagorMilsom To graduate this feature, I think we need to update the Slate prefab to use this script and update the default configuration values to match the shell behavior.
