### ISSUE TITLE
Wrong MSBuild path for nuget build 

### ISSUE THREAD

**Issue by Kent1LG** [microsoft/MixedRealityToolkit-Unity#6996]
## Describe the bug

During the process to build a MRTK nuget package with this documentation : https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/MRTKNuGetPackage.html
We need to execute the powershell script "scripts\packaging\createnugetpackages.ps1" who build
every InEditor and Player file.
There is a crash to the "Buidling Player WSA" step caused by a wrong hardcoded MSBuild path on the "NuGet/BuildSource.proj" file at line 38 :

`<MSBuild Projects="@(ProjectReferences)" Targets="Restore;Build" Properties="Configuration=Player;Platform=WSA;BuildProjectReferences=false;MSBuildExtensionsPathOverride=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild">`

Other issue : The build crash if the MRTK folder to build had a path name to long.

## To reproduce

1. Download MRTK source code.
2. Execute "scripts\packaging\createnugetpackages.ps1" with the right unity folder and package version you need.

## Expected behavior

Dynamically choose the right MSBuild path or let the user target it.
Succeed the build.

## Additional context

@thalbern message on slack about this issue :

> There's a hardcoded path in one of the project files msbuild is using - If you go to the Nuget folder in the MRTK repo and open the BuildSource.proj in a text editor you will notice in the last target definition (line 38) that the visual studio version there is hardcoded. - Please replace that path with the visual studio version you're using (folder should be the MSBuild folder insideyour visual studio installation. We'll open a ticket for this as we shouldn't have any hardcoded paths in that file, but this should work as a workaround for now :)

**Comment by thalbern** [comment]
this will break for anyone who doesn't have vs 2017 enterprise installed - we shouldn't use hardcoded paths to vs installs

**Comment by davidkline-ms** [comment]
Great catch @Kent1LG. Thanks!
