### ISSUE TITLE
Support Unity's new XR SDK pipeline

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#7003]
## Describe the feature

Unity is releasing a new XR pipeline and deprecating the existing APIs and settings.

https://blogs.unity3d.com/2020/01/24/unity-xr-platform-updates/
https://forum.unity.com/threads/xr-plugins-and-subsystems.693463/
https://docs.unity3d.com/Packages/com.unity.xr.management@3.0/manual/index.html
https://docs.unity3d.com/Packages/com.unity.xr.windowsmr@3.0/manual/index.html

- [x] Folder + asmdef #7013, #7040, #7075
- [x] Boundary #7013 
- [x] Spatial mapping #7061 
- [ ] Input #7093
  - [ ] WMR
    - [x] Controller input #7124, #7195
    - [x] Articulated hand input #7124
    - [ ] Gestures - to be implemented in MRTK 2.4.0
    - [x] GGV hand #7153, #7166
  - [ ] Oculus
- [x] Camera #7061, #7083, #7180 
- [ ] Documentation #7088
- [ ] Packaging - to be implemented in MRTK 2.4.0

## Additional context

This will allow MRTK to take advantage of the cross-platform work Unity is doing, instead of needing to self-define each platform ourselves. There will likely be additional platforms we want to support, which we can investigate either supporting as an MRTK extension or possibly an XR SDK extension.

**Comment by keveleigh** [comment]
Thought I had filed an issue a while back. Looks like not, so I filed this to track XR SDK work.

**Comment by davidkline-ms** [comment]
Do you want to add check boxes to help track the components to be added?

**Comment by davidkline-ms** [comment]
Closing as the 2.3.0 work is complete and merged.  Will open separate issues to track the 2.4.0 work
