### ISSUE TITLE
IMixedRealityInputHandler and IMixedRealityFocusHandler events are fired twice

### ISSUE THREAD

**Issue by lordlycastle** [microsoft/MixedRealityToolkit-Unity#7020]
## Describe the bug

I've created a script that implements `IMixedRealityInputHandler and IMixedRealityFocusHandler` and the `InputDown and InputUp and FocusEnter and FocusExit` events are being fired twice.

## To reproduce
See script that I used at: https://gist.github.com/1f9dfa6172cd31ccb1f5966e0c72eea4

## Expected behavior

The event should only fire once.

## Screenshots

![image](https://user-images.githubusercontent.com/11729541/72057184-e62ee300-32c5-11ea-8d64-9fa1193b0da4.png)

## Your setup (please complete the following information)

- Unity Version 2018.4.10f1
- MRTK Version v2.1.0

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by lordlycastle** [comment]
The double input event happen more consistently on the device and focus events on editor. I also was able to get input count to 10 so that means some input up events weren't fired at all.

**Comment by wiwei** [comment]
@lordlycastle do you have more information on the scene setup that triggers this (i.e. do we just create a cube, attach the monobehavior in the gist, and switch to HL1 style air tap/gestures, and then go to town?)

Or do you have a more interesting hierarchy (i.e. are there multiple objects in the scene that are parent/children of each other that may implement some of these interfaces as well?)

**Comment by lordlycastle** [comment]
@wiwei I just recreated the double input down issue by creating a simple cube and adding that component in the editor. Haven't checked on device. Will report back. 

In the real button it's doesn't have other script that implement any other MRTK interfaces in it's children; obv there're other objects like text, image etc. This is the only script on top level button game object that uses any MRTK interfaces.

**Comment by keveleigh** [comment]
I believe you're getting input down events with different action types. By default, I think most controllers fire one for select and also one for the trigger being pressed. If you add `eventData.MixedRealityInputAction` to your logs, you'll be able to see if they're different. #5109 may also help with this.

Depending on your use case, you may be able to use [`IMixedRealityInputActionHandler` to filter automatically](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/InputActions.html#handling-input-actions).
You can also take a look at the [`InputActionHandler` script](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/InputActionHandler.cs#L16) for an example of how to implement action filtering, if you need to do it yourself in a custom script.

**Comment by lordlycastle** [comment]
@keveleigh I thought they were meant to filtered so multiple would not be fired. There's a whole 'service/system/module' about it.

So how do I reduce it so it fires only one. Having filtering code in is silly as code should run with either so we'd need a counter.

**Comment by lordlycastle** [comment]
@keveleigh `eventData` doesn't have that property. 
![image](https://user-images.githubusercontent.com/11729541/72145161-d54ba380-3391-11ea-95fa-2bc2495eb598.png)

**Comment by keveleigh** [comment]
Ah, looks like you might be looking in the focus event data. That one doesn't have it, but the input events data does: https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.Input.BaseInputEventData.html#Microsoft_MixedReality_Toolkit_Input_BaseInputEventData_MixedRealityInputAction

Your duplicate focus events are definitely more strange though. Can you print out the name of the `Pointer` that's sending them to you?

>I thought they were meant to filtered so multiple would not be fired. There's a whole 'service/system/module' about it.

I'm not sure what this is referring to

**Comment by lordlycastle** [comment]
@keveleigh I was talking about https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Architecture/InputSystem/ControllersPointersAndFocus.html#pointer-mediation

**Comment by Troy-Ferrell** [comment]
@lordlycastle I cannot repo the duplicated focus events. I do get two OnInputDown & OnInputUp: one with inputaction = select and one with inputaction = grip press.

How are you triggering the double focus? Even with the two input simulation hands, OnFocusEnter does not fire twice. 

I am also testing on 2.3.0_stabilization...so there may be missing changes between 2.1 and 2.3

**Comment by lordlycastle** [comment]
@Troy-Ferrell I have no idea. I literally did only have that single script.

Should the grip press be triggered in editor when you click? Why does it happen randomly and not always?

How do you just subscribe to select? Having an if condition everywhere would be annoying.

**Comment by Troy-Ferrell** [comment]
@lordlycastle the two event executions with *select* and *grip press* fire when I just select with one of the simulated articulated hands in editor. So holding **space** bar and then clicking **left-mouse-button**.  For me, it does not happen randomly. I always get those two events.

Are you using the default MRTK configuration profile or default HL2 MRTK configuration profiles? Do you have custom pointers or other extended overrides in the system?

Maybe @keveleigh or @julenka know a better way....but I think you just have to if statement it

**Comment by lordlycastle** [comment]
@Troy-Ferrell i don’t use the space at all. I just use left click to select. I’m using default HL2 profile. I don’t have any custom things at all. 

And isn’t the toolkits I out profiles meant to do the filtering. Thought there was another whole system for this ie specifying which high level event you’re interested in like select, grab, touch etc. 

I also don’t understand what grip event is on HL2. Grab? That should not fire same as select. Is this intended Behaviour? Docs don’t seem to mention it; there are other devs that think two events are a bug too so maybe make it really _**explicit**_ that it’s not.

**Comment by lordlycastle** [comment]
And what’s up with the not having same number of up events as down?  The script for sure didn’t just miss to count them. 

> The double input event happen more consistently on the device and focus events on editor. I also was able to get input count to 10 so that means some input up events weren't fired at all.

**Comment by Troy-Ferrell** [comment]
@lordlycastle can you provide a unity project zip and the build platform setup (targeting UWP? IL2CPP? etc etc)? 

I am not able to fully repo what you are seeing. It is interesting that you say you can just left-mouse-button click to select without holding space or bringing up hands. I am not sure how you are doing that. 

>@Troy-Ferrell i don’t use the space at all. I just use left click to select.
