### ISSUE TITLE
Building to multiple platforms from the same scene

### ISSUE THREAD

**Issue by tylershatch** [microsoft/MixedRealityToolkit-Unity#7024]
## Describe the issue

We are using MRTK in our application which targets a variety of Unity platforms (Hololens, Oculus Quest, Magic Leap, and Android Mobile, with others in the pipeline). We are using a different MRTK configuration profile for each platform, as well somewhat different MRTK playspace objects for each platform. Until now we have been mantaining separate scenes for each platform in order to manage this, but we would like to collapse these all into a single scene in order to simplify maintenance.

I can't find any documentation regarding how to approach this task. Is there an accepted best practice?

**Comment by wiwei** [comment]
@tylershatch  this is actually a somewhat common ask that I've heard from folks - there's a common solution that I'll post in a docs update. Gimme a sec...

**Comment by wiwei** [comment]
Alrighty, the linked PR *should* unblock you if I understood your ask correctly.
