### ISSUE TITLE
Using ARFoundation for Object Tracking on HoloLens2

### ISSUE THREAD

**Issue by Morgan-6Freedom** [microsoft/MixedRealityToolkit-Unity#7046]
## Describe the issue
It seems that ARFoundation is compatible with MRTK. So I wanted to use the [Object Tracker Subsystem](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@3.1/manual/object-tracking.html) to recognize a real object and displays virtual info around it.

In the documentation of the [Object Tracker Susbsystem](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@3.1/manual/object-tracking.html) it is written

> You will need to then populate the reference object entries with provider-specific assets. Refer to the provider's documentation for instructions on how to do this.

So I looked into the MRTK Documentation and found nothing.

## Feature area
The documentation is missing information about "How to Create a Reference Object Entries in UWP for using ARFoundation Object Tracker Subsystem"

## Existing doc link
The only things I found [are about iOS and Android](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/CrossPlatform/UsingARFoundation.html?q=arfoundation). But I would like to use the ARFoundation with UWP and HoloLens2.

## Additional context
Maybe I'm wrong and I can't use ARFoundation with HoloLens2 ? I did not even try to use the image tracker. Maybe this one does not even work. If ARFoundation doesn't work with HL2, sorry to believe that in the first place.

**Comment by davidkline-ms** [comment]
The current implementation of MRTK and ARFoundation is limited to camera and far interaction on Android and iOS. A future release of MRTK will add support for Spatial Awareness on Android and iOS.

MRTK 2.3.0 will be introducing support for Unity's XR SDK architecture (2019.3 and newer required), which will be much more feature rich.

**Comment by Thomas-6freedom** [comment]
Does Image Tracking (image, not QR Code) and Model tracking are planned for MRTK ?

**Comment by serhii-shydel** [comment]
Hi, @davidkline-ms! There's already 2.4.0 version in the release. I see that now MRTK supports custom spatial awareness systems. But is there any news about how to use spatial awareness on Android?

**Comment by Thomas-6freedom** [comment]
@serhii-shydel this thread is about Image Tracking and Model tracking on Hololens, not Android.

**Comment by kai0122** [comment]
Hi, Is there any update on Image tracking on Hololens with AR foundation?
I used the AR Tacked Image Manager script on AR device and it worked, but when I run it on Hololens, it cannot work.....

**Comment by polar-kev** [comment]
Hey @Morgan-6Freedom, ARFoundation is owned by Unity so this work here would be out of scope for the MRTK team.
https://unity.com/unity/features/arfoundation.

I recommend exploring Azure Object Anchors since it will work on HoloLens.
