### ISSUE TITLE
ToggleSwitch/RadialSet prefabs use TouchHandler instead of PressableButton component

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#7048]
## Describe the bug

The ToggleSwitch and RadialSet prefabs use a TouchHandler component with Interactable instead of the PressableButton and PhysicalPressButtonRouter.

The problem with TouchHandler is that it only looks at touch start and touch completed to activate a "press" which is just a collider intersection detection for touch. Thus, the user could push through to activate a toggle switch and on the pull back consequently de-activate as a new "touch". 

![toggle-button-issue](https://user-images.githubusercontent.com/25975362/72277537-f3f6a800-35e6-11ea-8cb7-b042024e8a27.gif)

By disabling the TouchHandler and using PressableButton component instead, the toggle switch worked as expected.

![image](https://user-images.githubusercontent.com/25975362/72277608-0bce2c00-35e7-11ea-819a-a3721cc575d6.png)

## To reproduce

See gif above
Open InteractableExamples scene
Bring up hand input simulation
Go through button and then mouse scroll index finger back, notice button double activates

## Expected behavior

"pressing" a button like the toggle and radialset prefabs should result in a one way switch/selection.

## Your setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version - latest MRTK_dev

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by thalbern** [comment]
this is actually happening with all prefabs used in the interactable example scene - even the buttons emit the click twice because they're hooked up with touch handler
