### ISSUE TITLE
Clipping box prevents to display dynamically set texture

### ISSUE THREAD

**Issue by Bertrand75014** [microsoft/MixedRealityToolkit-Unity#7054]
## Describe the bug

I'm making a draggable list, dynamically filled with basic elements. These elements are based on the prefab _PressableButtonHoloLens2_32x96_ from the MRTK (1 icon, 1 text and the back/front plates ). I want to set dynamically the icon of each element, so i'm using the HolographicButtonIconFontMaterial with _RenderingMode_ set to _Fade_, no _Albedo_ set, and _Assigned at Runtime_ checked.
At the same time, I'm setting a clipping box so I cannot see the elements outside the UI. Since the elements are added dynamically, I must add their renderers to the clipping box at runtime too : 
 
```
public ClippingBox clippingBox;

GameObject go = Instantiate(prefab, parent);

// Add all the element's renderers to the clipping box
Renderer[] renderersToClip = go.GetComponentsInChildren<Renderer>();
for (int i = 0; i < renderersToClip.Length; i++)
{
    clippingBox.AddRenderer(renderersToClip[i]);
}
```

Then I'm just setting the texture I want on the newly created element's material.

The issue here is that the icons appear fully transparent. Same issue when setting the _RenderingMode_ to _Transparent_. 
However, if I set it to _Opaque_, the icon is appearing correctly (with transparency) , same thing with _Cutout_. Same thing if I don't add the elements to the clipping box.

## Expected behavior

The icon should appear even if set dynamically with _Fade_ or _Transparent_ _RenderingMode_.

## Your setup (please complete the following information)

- Unity Version 2019.2.6f1
- MRTK Version 2.1 & 2.2

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2

## Additional context

I tried with and without depth buffer sharing with no luck.

**Comment by Bertrand75014** [comment]
It seems to actually have nothing to do with setting dynamically the texture. As soon as a renderer has a material with _RenderingMode_ set to _Opaque_ or _Transparent_ and we add this renderer dynamically to a clipping box, the texture is invisible.

**Comment by AlexisAG** [comment]
@Bertrand75014 I had the same issue. When you set the renderingMode to Fade do you change "Blended Clipping Width" ? When I set it to '0' my texture is not transparent anymore. Have you tried that ?

**Comment by Bertrand75014** [comment]
Thanks @AlexisAG, setting "Blended Clipping Width" to 0 (or a tiny value to have a blend though) fixed the issue. Shouldn't the default value rather be set to 0 instead of 1 ?
