### ISSUE TITLE
Media Foundation and HoloLens 2

### ISSUE THREAD

**Issue by MickaelSERENO** [microsoft/MixedRealityToolkit-Unity#7058]
Hi,

I want to have access to the depth camera streams with the HoloLens 2 as I was able to do with the HoloLens 1. With the HoloLens 1, I was able to call that method while with the HoloLens 2 I have the exception "no capture device available":

`            IReadOnlyList<MediaFrameSourceGroup> allFrameSourceGroups = await MediaFrameSourceGroup.FindAllAsync();`

I paid attention to activate both the Camera and the perceptionSensorsExperimental Capabilities: 

```
<?xml version="1.0" encoding="utf-8"?>
<Package xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest" xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" xmlns:uap2="http://schemas.microsoft.com/appx/manifest/uap/windows10/2" xmlns:uap3="http://schemas.microsoft.com/appx/manifest/uap/windows10/3" xmlns:uap4="http://schemas.microsoft.com/appx/manifest/uap/windows10/4" xmlns:iot="http://schemas.microsoft.com/appx/manifest/iot/windows10" xmlns:mobile="http://schemas.microsoft.com/appx/manifest/mobile/windows10" xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities" IgnorableNamespaces="uap uap2 uap3 uap4 mp mobile iot rescap" xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10">
  <Identity Name="SciVisHololens" Publisher="CN=DefaultCompany" Version="1.0.0.0" />
  <mp:PhoneIdentity PhoneProductId="4e761bd6-9819-4b93-943b-0d9037e8077d" PhonePublisherId="00000000-0000-0000-0000-000000000000" />
  <Properties>
    <DisplayName>SciVis_Hololens</DisplayName>
    <PublisherDisplayName>DefaultCompany</PublisherDisplayName>
    <Logo>Assets\StoreLogo.png</Logo>
  </Properties>
  <Dependencies>
    <TargetDeviceFamily Name="Windows.Holographic" MinVersion="10.0.17763.0" MaxVersionTested="10.0.18362.0" />
  </Dependencies>
  <Resources>
    <Resource Language="x-generate" />
  </Resources>
  <Applications>
    <Application Id="App" Executable="$targetnametoken$.exe" EntryPoint="SciVisHololens.App">
      <uap:VisualElements DisplayName="SciVis_Hololens" Square150x150Logo="Assets\Square150x150Logo.png" Square44x44Logo="Assets\Square44x44Logo.png" Description="SciVis_Hololens" BackgroundColor="transparent">
        <uap:DefaultTile ShortName="SciVis_Hololens" Wide310x150Logo="Assets\Wide310x150Logo.png" />
        <uap:SplashScreen Image="Assets\SplashScreen.png" BackgroundColor="#FFFFFF" />
        <uap:InitialRotationPreference>
          <uap:Rotation Preference="landscape" />
          <uap:Rotation Preference="landscapeFlipped" />
          <uap:Rotation Preference="portrait" />
          <uap:Rotation Preference="portraitFlipped" />
        </uap:InitialRotationPreference>
      </uap:VisualElements>
    </Application>
  </Applications>
  <Capabilities>
    <Capability Name="internetClient" />
    <uap2:Capability Name="spatialPerception" />
    <iot:Capability Name="lowLevelDevices" />
    <rescap:Capability Name="perceptionSensorsExperimental" />
    <DeviceCapability Name="webcam" />
    <DeviceCapability Name="microphone" />
    <DeviceCapability Name="humaninterfacedevice">
      <Device Id="any">
        <Function Type="usage:0001 0004" />
      </Device>
      <Device Id="any">
        <Function Type="usage:0001 0005" />
      </Device>
    </DeviceCapability>
  </Capabilities>
</Package>
```
My HoloLens 2 is up-to-date and I should at least be able to access the default RGB camera.
I compiled a managed assembly OUTSIDE Unity (for the piece of code handling cameras) in ARM 32, minimal version 15063. I wanted to compile with the 17134 version as the doc advices (regarding that function), but then I have a conflict about system.runtime versions between my managed assembly and Unity…

I both tried using Unity 2018 LTS and Unity 2019 (last version) to generate the IL2CPP code compiled using Unity. target: HoloLens ARM. MRTK version: v2.2.0
thank you!

**Comment by carmines** [comment]
This is not a MRTK specific question. Camera capture and other Windows SDK questions should be directed to one of the official support channels. You can find more information located here:
https://support.microsoft.com/en-us/hub/4338666/hololens-help

As a quick check, did you also enable research mode on the device? Depth information is only for developer unlocked devices with research mode enable
https://docs.microsoft.com/en-us/windows/mixed-reality/research-mode

Have you tried a one the samples that does work?
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/HolographicFaceTracking

**Comment by MickaelSERENO** [comment]
Hi,
I thought MRTK would have locked the cameras, hence why I cannot have access to any. I will try to make a UWP application then to find if yes or no MRTK is in fault.
Research-mode is enabled and no I did not try applications that is known to work (my code though worked on HoloLens 1).
