### ISSUE TITLE
Spatial Mapping Observer not stopped when Spatial Understanding scanning is finished

### ISSUE THREAD

**Issue by Reeley** [Microsoft/MixedRealityToolkit-Unity#706]
Is there a reason why the SpatialMappingObserver is not stopped when the RequestFinishScan function is called in SpatialUnderstanding?

In my opinion it should be stopped and started via the SpatialUnderstanding script, or am i wrong?

**Edit:** and what is the use for the UpdatePeriod_AfterScanning variable? just setting the time between updates in the SpatialMappingObserver, so it doesnt update that often? why not just stop it as mentioned?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
