### ISSUE TITLE
Start the work to getting RS2 and Master synced up

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#707]
This could be quite the undertaking, but we should start looking at updating small parts of master to closer reflect the changes in RS2.

This should happen in many small increments so we can review and test changes.

**Comment by NeerajW** [comment]
I will work on a plan for this when I publish the next roadmap. Thank you for filing!
There might be some feature folders that we can merge sooner than others.
