### ISSUE TITLE
[Input] Manipulation update breaks if focus is lost

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#709]
When implementing manipulations I found that when the focused object being manipulated is lost by the gaze manager, the `InputManager` does not raise events for manipulation correctly.

[Update] Tested this out on device. Broken there too.

**Comment by StephenHodgson** [comment]
Adding the current object you're trying to manipulate to the global listeners should fix the issue.

**Comment by killerantz** [comment]
I normally clear the input stack, push my inputHandler, then clear the input stack on los or release.

InputManager.Instance.ClearModalInputStack();
InputManager.Instance.PushModalInputHandler(gameObject);

The push and pop is scary. Adding to the global listeners is probably the better way to go though.

**Comment by StephenHodgson** [comment]
Good call about clearing the stack.
