### ISSUE TITLE
Namespace 'Media' missing after Enabling MSBuild for Unity

### ISSUE THREAD

**Issue by pampas93** [microsoft/MixedRealityToolkit-Unity#7094]
## Describe the bug

Namespace Media does not exist in the namespace 'Microsoft.Windows' ONLY when I "Enable MSBuild for Unity". Trying to build spectator view test scene, 'SpectatorView.ASA.HoloLens' and builds fine. But after enabling the MSBuild option from the MRTK Project Configurator, Build fails with the given error.

## To reproduce

1. Create new empty project
2. Import Microsoft.MixedReality.Toolkit.Unity.Foundation.2.2.0.unitypackage
3. Copy the required Extensions for SpectatorView from 
`prerelease/2019.build.spectatorView` branch
4. Setup the project as given in the [Spectator view README](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/prerelease/2019.build.spectatorView/Assets/MixedRealityToolkit.Extensions/SpectatorView/SpectatorViewSetup.md)
5. Build for UWP and works fine
6. Now, Enable MSBuild for unity from the MRTK Project Configurator
7. Trying to build again, fails with the below error

Error: 
`Assets\MixedRealityToolkit.Extensions\PhotoCapture\HoloLensCamera.cs(1330,60): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Microsoft.Windows' (are you missing an assembly reference?)`

## Your setup

- Unity Version [e.g. 2019.2.18]
- MRTK Version [e.g. v2.2] + Extensions from `prerelease/2019.build.spectatorView` branch

## Target platform

- HoloLens 2

**Comment by MenelvagorMilsom** [comment]
@andreiborodin @chrisfromwork may know more about this. Also @CDiaz-MS who I think was working on this recently.
