### ISSUE TITLE
Blank/empty scene on Hololens 1 from Unity 2018.4.14f1, MRTK2 and Visual Studio 2017

### ISSUE THREAD

**Issue by BitterDone** [microsoft/MixedRealityToolkit-Unity#7095]
## Describe the bug

NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.MixedReality.Toolkit.WindowsMixedReality.WindowsMixedRealityCameraSettings.InitializeReprojectionUpdater

## To reproduce

Follow these Microsoft steps: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html
Prereqs
-Hololens 1 on Windows 10.0.17763
Installed on the development machine:
-Windows SDK 10.0.17763 
-Unity (free) 2018.4.14f1
-Visual Studio 2017 v15.9.17
-Internet access or MRTK2 v2.2.0 downloaded

1. Create a new 3D project in Unity 2018.4.14f1
2. Download MRTK2 Foundations v2.2.0 from https://github.com/Microsoft/MixedRealityToolkit-Unity/releases
3. Import the Foundations into Unity via Asset -> Import Package -> Custom Package, ensure all options are checked, then click Import
4. The MRTK Project Configurator should popup with suggested settings changes, choose Apply
5. Import Text Mesh Pro Essentials via Window -> TextMeshPro -> Import TMP Essential Resources and restart Unity
6. Switch the project to UWP from the Build Settings window
7. Open the project and add a new scene
8. Observe the new option menu bar options Mixed Reality Toolkit 
9. Choose Mixed Reality Toolkit -> Add to Scene and Configure
10. Choose DefaultHoloLens1ConfigurationProfile for Hololens 1
11. Add a basic 3D cube to the Hierarchy. I placed mine at  xyz coordinates (0, 1, 2).
12. Install the Holographic Remoting Player app to the Hololens device and open it, oberving the IP address displayed
13. In Unity, choose Window -> XR -> Holographic Emulation
14. Enter the IP address from the Hololens Holographic Remoting Player and choose Connect
15. Play the Unity scene, observing the 3D cube in the Hololens
16. See this page to build the Unity project https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/BuildAndDeploy.html
17. Open the Visual Studio .sln file in Visual Studio 2017
18. See this page for Visual Studio configuration https://docs.microsoft.com/en-us/windows/mixed-reality/using-visual-studio
18. In Visual Studio, change the Configuration to Debug and the Architecture to x86, and Deployment Target to Remote Machine
18b. If the Remote Connections window did not pop up automatically, open Solution Explorer, right-click on the solution and choose Properties. On the left panel, choose Debugging. Ensure Remote Machine is selected in the dropdown at the top of the window, and open the drop down next to Machine Name. Choose < Locate > to open the Remote Connections window.
19. Select the Hololens under the Auto Detected section, or enter the same IP Address as was used for the Holographic Remoting player. Choose Universal (Unecrypted Protocol) as the Authentication Mode, and click OK through any/all windows.
20. In Visual Studio, choose Debug -> Start with debugging
21. After the build and deployment are done, any visible windows/holograms will disappear as the app loads. But, all that's seen is a blank/black scene and cursor. The Made with Unity splash screen does not appear, nor does the 3D cube

## Expected behavior
The project is built and deployed to the Hololens.
The Made with Unity splash screen appears in the Hololens field of view
The 3D cube is seen as a hologram per its coordinates in the Unity project

## Your setup (please complete the following information)
-Windows SDK 10.0.17763 
-Unity (free) 2018.4.14f1
-Visual Studio 2017 v15.9.17
-MRTK2 v2.2.0 

## Target platform (please complete the following information)
- HoloLens 1

Following basic Microsoft steps in Unity 2017.4.35f1 (without MRTK) work for the Hololens 1
https://docs.microsoft.com/en-us/windows/mixed-reality/configure-unity-project

**Comment by BitterDone** [comment]
May be related to 
Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityCameraSettings.cs line 96 
https://github.com/microsoft/MixedRealityToolkit-Unity/commit/ddfeb557e0c6dc075907c3486525be39b921d1dd

**Comment by BitterDone** [comment]
Full error
`NullReferenceException: Object reference not set to an instance of an object.
  at Microsoft.MixedReality.Toolkit.WindowsMixedReality.WindowsMixedRealityCameraSettings.InitializeReprojectionUpdater ()
  at Microsoft.MixedReality.Toolkit.WindowsMixedReality.WindowsMixedRealityCameraSettings.Enable ()
  at Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem.Enable ()
  at Microsoft.MixedReality.Toolkit.CameraSystem.MixedRealityCameraSystem.Enable ()
  at Microsoft.MixedReality.Toolkit.MixedRealityToolkit+<>c.<EnableAllServices>b__62_0 (Microsoft.MixedReality.Toolkit.IMixedRealityService service)
  at System.Action`1[T].Invoke (T obj)
  at Microsoft.MixedReality.Toolkit.MixedRealityToolkit.ExecuteOnAllServices (System.Collections.Generic.IEnumerable`1[T] services, System.Action`1[T] execute)
  at Microsoft.MixedReality.Toolkit.MixedRealityToolkit.ExecuteOnAllServicesInOrder (System.Action`1[T] execute)
  at Microsoft.MixedReality.Toolkit.MixedRealityToolkit.EnableAllServices ()
  at Microsoft.MixedReality.Toolkit.MixedRealityToolkit.OnEnable ()`

**Comment by Troy-Ferrell** [comment]
@davidkline-ms / @keveleigh  FYI

**Comment by keveleigh** [comment]
Hmm... can you double check your WMR camera settings provider? It's possible the `Profile` call is causing the null ref, if a profile isn't provided. I'll look into adding a null check.

![image](https://user-images.githubusercontent.com/3580640/73096327-59754f00-3e99-11ea-8c41-13c32b27b6c4.png)

**Comment by keveleigh** [comment]
Ah! The HoloLens1 profile you mention doesn't have this profile set! There's the issue.
I think this is an okay situation, since HL1 doesn't support the features this profile is meant to enable. I'll add that null check now.

**Comment by BitterDone** [comment]
@keveleigh Thank you for finding a fix so quick!

Can you point me to information on how to build MRTK from the prerelease/2.3.0_stabilization branch, do do we have to wait for it to merge with mrtk_development? I'd love to see the fix in action

**Comment by davidkline-ms** [comment]
@BitterDone, please try the following link. You should be able to download .unitypackage files containing the latest 2.3.0 version.

https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=9001&view=artifacts&type=publishedArtifacts

Thanks!
