### ISSUE TITLE
GesturesInput freezes Unity Editor

### ISSUE THREAD

**Issue by niklas87** [Microsoft/MixedRealityToolkit-Unity#710]
Hi all!

I've experiencing some issues with the GesturesInput script attached to the InputManger prefab: 

On my Surface Pro 3, Windows 10 Pro (15063.296), Visual Studio 2017, Unity 5.6.1f1 setup, the Editor freezes immediately after pressing play. The "play" button doesn't event turn blue, there are no console messages and Unity doesn't have any CPU activity (0,0 %). I could isolate the GesturesInput script as the troublemaker by disabling all GameObjects in the hierarchy and enabling them one by one again. One can also notice that a running application freezes as soon as the checkbox for the GesturesInput component is enabled again in an already running scene (started with disabled GesturesInput).

I couldn't fix the issue by neither reinstalling Unity nor re-downloading my repo or deleting all created files by the build process.

Strange thing is, that this issue doesn't appear on my desktop computer (same software) or my work laptop (also the same, but VS 2015).

**Comment by StephenHodgson** [comment]
Is a surface pro 3 up to spec to run Unity?

**Comment by niklas87** [comment]
I would have guessed that the SP3 outperforms the hardware of the HoloLens by far, so it is suitable as development device.

**Comment by StephenHodgson** [comment]
I can understand the device running the application under development, but the unity editor can be quite a resource hog by itself, depending on the size of your project.

**Comment by niklas87** [comment]
The whole rest works quite performant and even the GesturesInput didn't make any troubles for a long while, so I can only assume its some kind of bug. But I understand that its difficult to track because it seems I'm the only one with this bug (and just on one device) and it occurs so early after starting that I don't have any console output.

**Comment by StephenHodgson** [comment]
No worries, yeah if you can get a solid reproduction process down, please add it here so we can try to fix the issue.

**Comment by MarcPilgaard** [comment]
I found a guy experiencing the same problem saying he fixed it by installing the Windows 10 SDK. Not certain that I had installed it myself, I tried installing it but it does not seem to work for me at least:

https://forum.unity3d.com/threads/unity-freezes-when-creating-a-new-gesturerecognizer-5-5-and-up.468514/

**Comment by Cangi** [comment]
Hello,
I have the same problem.
I installed:
-a fresh image of windows 10 pro with all the updates.
-unity 5.6.1f1 with all the needed extensions.
-visual studio 2017 with win10 sdk.
I tried to play the scenes from the HoloLens toolkit and for all of them unity freezes.
I deployed scenes to the HoloLens and I get this error:
![20170616_080309_hololens](https://user-images.githubusercontent.com/16014047/27232262-44799066-526a-11e7-83db-95497de9c8c5.jpg)

**Comment by StephenHodgson** [comment]
Can't read the error well. Any change you can run for VS and paste the output? Thanks.

**Comment by markgrossnickle** [comment]
I was in the same boat.  

I have a new alienware laptop and it was freezing on play when there was a GesturesInput in the scene but otherwise it worked fine.  More specifically, if I commented out creating a new GestureRecognizer it worked. 

I had windows 10 SDK installed.  

I just turned on Developer Mode and restarted the computer and that fixed it.  

Thanks for the tip.

**Comment by StephenHodgson** [comment]
I think we should add a section to the getting started doc that describes the environment setup and required software as well.

**Comment by HaimBendanan** [comment]
I had exactly the same issue on my new laptop running windows 10. 
Turned on developer mode and restarted my computer -> it solved the problem.

**Comment by ForrestTrepte** [comment]
Does anyone know if this has been reported to Unity as a bug? Enabling developer mode fixed this for me, but it would be nice for Unity to present instructions to the user instead of hanging.

**Comment by ForrestTrepte** [comment]
I created a minimum repro case and reported this via the Unity Bug Reporter.

**Comment by StephenHodgson** [comment]
@ForrestTrepte, can we get the case number?

**Comment by ForrestTrepte** [comment]
My case number with Unity is 933776, but is that publicly visible or is that just a number in their internal database.

**Comment by ForrestTrepte** [comment]
And here it is in IssueTracker: https://issuetracker.unity3d.com/issues/the-editor-will-freeze-on-play-mode-enter-if-developer-mode-is-off-in-windows-and-a-gesture-recognizer-is-used

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
