### ISSUE TITLE
Target scale and pure orientation-only experience

### ISSUE THREAD

**Issue by sodach1** [microsoft/MixedRealityToolkit-Unity#7105]
## Describe the bug

Target scale and pure orientation-only experience doesn't work as expected on build while fine in the editor. 'Orientation Only' target scale mode on build seems like any other one.
The result I want to achieve is like on Oculus GO, or in other words completely orientation-only.

https://docs.microsoft.com/en-us/windows/mixed-reality/coordinate-systems-in-unity
Applying the solution above causes a problem described on https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1376 . I can't see if it had been solved, but seems like it hadn't.

## To reproduce

1. Set 'Target scale' in MRTK profile to 'Orientation Only'
2. See in editor that everything works as expected while only orientation is tracked and you can't move.
3. Build the app 
4. See that you can still move around the scene if you walk IRL like if room scale is set.

## Expected behavior

If you move IRL you would still stay straight in the scene like you're holding position.

## Your setup

- Unity Version 2019.1.9f1
- MRTK Version v2.0 and v2.2

## Target platform

- Immersive HMD (Lenovo explorer) both UWP and standalone with Mixed reality for SteamVR

**Comment by Troy-Ferrell** [comment]
@sodach1 thanks for filing the issue. 

I can repo with mrtk_development latest. 
If I add in the code: `InputTracking.disablePositionalTracking = Scale == ExperienceScale.OrientationOnly;` to the boundary system to "fix" the first issue, I do run into the controller tracking being wrong. The controller tracks "movement" correctly but it's positioning is off I believe.

Repo info;
1) Add line of code above to MRBoundarySystem.SetupTrackingSpace()
2) Open hands interaction example scene in editor and play with VR attached 
3) Have the headset on when starting play mode and a VR controller attached. You will see the shell VR controller position as the animation for app launching is executing
4) When the actual hands interaction scene launches, you should see the controller model jump from it's position to a new place where MRTK is tracking the controller

Internal folks, ping @Troy-Ferrell for video of repo

**TODO:**
1) Add `InputTracking.disablePositionalTracking = Scale == ExperienceScale.OrientationOnly;` to setup
2) Consider moving SetTrackingSpace from MRBoundarySystem to core MRTK component code. That or update the experience scale to be set in the boundary inspector code (MRTK profile rendering). 
3) Investigate controller offset issue with orientation-only tracking

**Comment by keveleigh** [comment]
>investigate controller offset issue with orientation-only tracking

Hmm...we're specifically getting this data from Unity APIs. I wonder if they're using the wrong coordinate system in that case? Could be a Unity bug

**Comment by Llleea** [comment]
This issue is supposed to be fixed by now, but I am facing the same problem. 
I am using Unity 2019.4.22f1, with MRTK 2.8.3.0.

I set the _Target experience scale_ set to  _Orientation Only_.

When I build the project (UWP) and deploy it to HoloLens 2, the position is still tracked, as for other experience scales.

Is there any fix to that?
