### ISSUE TITLE
MRTK v2.2.0 seems to generate issues for WINDOWS_UWP macros in custom code

### ISSUE THREAD

**Issue by chrisfromwork** [microsoft/MixedRealityToolkit-Unity#7106]
## Describe the bug

We're seeing issues filed for Spectator View around our implementation of HoloLensCamera. It seems that MRTK 2.2.0 might cause the WINDOWS_UWP to resolve in the Unity editor. It may also cause SDK to resolve incorrectly, causing Windows SDK Camera apis to not be available.

## To reproduce

Add Spectator View code and MRTK 2.2.0 to the same project

## Expected behavior

Things compile and play well with one another.

## Observed behavior

Assets\MixedReality-SpectatorView\PhotoCapture\Scripts\HoloLensCamera.cs(1334,60): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Microsoft.Windows' (are you missing an assembly reference?)
https://github.com/microsoft/MixedReality-SpectatorView/blob/403fec0ab62be1c430eff5c69262dd847cc8558b/src/SpectatorView.Unity/Assets/PhotoCapture/Scripts/HoloLensCamera.cs#L1334

**Comment by keveleigh** [comment]
Are you able to see which assembly this comes from? It's likely coming from the `.Player` assembly, which does resolve `WINDOWS_UWP`.

The underlying issue is likely that MRTK can import the DotNetWinRT adapter, which defines a set of `Microsoft.Windows.*` namespaces, which is confusing your nanespace resolution.

**Comment by jbarbeau** [comment]
I have this same issue with a project I got from someone else, and am trying to build for Hololens 2.  I have MRTK 2.2 and Unity 2019.2.19f1 and lastest Windows SDK.

What is the solution for resolving this namespace?  I am trying to build a UWP for HL2 of course.  Am I missing the DotNetWinRT adapter?

The headers look like this in one of the MRTK cs files
#if WINDOWS_UWP || DOTNETWINRT_PRESENT
using System;
using System.Collections.Generic;
using UnityEngine;
#if WINDOWS_UWP
using Windows.Foundation.Metadata;
using Windows.Perception;
using Windows.Perception.People;
using Windows.UI.Input.Spatial;
#elif DOTNETWINRT_PRESENT
using Microsoft.Windows.Foundation.Metadata;
using Microsoft.Windows.Perception;
using Microsoft.Windows.Perception.People;
using Microsoft.Windows.UI.Input.Spatial;
#endif
#endif // WINDOWS_UWP || DOTNETWINRT_PRESENT

Why isn't WINDOWS_UWP defined?  I think thats the issue.

Perhaps this project was made with MRTK 2.1 could that be the problem?

**Comment by rdikshit** [comment]
Please let me know of any updates on this. If I use a different MRTK , will I be able to build without error?

**Comment by keveleigh** [comment]
If you need DotNetWinRT but are having trouble resolving the `Microsoft.Windows.*` namespaces, please use [this guide](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html#debugging-hololens-2-remoting-via-unity-package-import) to debug your installation.

If you don't need DotNetWinRT, and its presence is causing you issues in accessing `Windows.*` namespaces, you can either append them with `global::` or uninstall DotNetWinRT using [this guide](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html#removing-hololens-2-specific-remoting-support).
