### ISSUE TITLE
[HL2] All hand pointers stop working after hitting exception in Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.RaisePointerDown 

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#7107]
## Describe the bug

Once an exception occurs in  Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.RaisePointerDown, all future hand pointers fail to work.  

I hit this exception first: 

> [C:\buildslave\unity\build\Modules/VR/HoloLens/VRDeviceHoloLens.cpp line 309] 
> (Filename: C:\buildslave\unity\build\Modules/VR/HoloLens/VRDeviceHoloLens.cpp Line: 309)
> 
> NullReferenceException: Object reference not set to an instance of an object.
>   at UnityEngine.GameObject.get_transform () [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.RaisePointerDown (Microsoft.MixedReality.Toolkit.Input.IMixedRealityPointer pointer, Microsoft.MixedReality.Toolkit.Input.MixedRealityInputAction inputAction, Microsoft.MixedReality.Toolkit.Utilities.Handedness handedness, Microsoft.MixedReality.Toolkit.Input.IMixedRealityInputSource inputSource) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.Input.BaseControllerPointer.OnInputDown (Microsoft.MixedReality.Toolkit.Input.InputEventData eventData) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem+<>c.<.cctor>b__196_16 (Microsoft.MixedReality.Toolkit.Input.IMixedRealityBaseInputHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00000] in <00000000000000000000000000000000>:0 
>   at System.EventHandler`1[TEventArgs].Invoke (System.Object sender, TEventArgs e) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.BaseEventSystem.HandleEvent[T] (UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] eventHandler) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.HandleEvent[T] (UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] eventHandler) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.RaiseOnInputDown (Microsoft.MixedReality.Toolkit.Input.IMixedRealityInputSource source, Microsoft.MixedReality.Toolkit.Utilities.Handedness handedness, Microsoft.MixedReality.Toolkit.Input.MixedRealityInputAction inputAction) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.BaseWindowsMixedRealitySource.UpdateTriggerData (UnityEngine.XR.WSA.Input.InteractionSourceState interactionSourceState, Microsoft.MixedReality.Toolkit.Input.MixedRealityInteractionMapping interactionMapping) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.BaseWindowsMixedRealitySource.UpdateController (UnityEngine.XR.WSA.Input.InteractionSourceState interactionSourceState) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityArticulatedHand.UpdateController (UnityEngine.XR.WSA.Input.InteractionSourceState interactionSourceState) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityDeviceManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.MixedRealityToolkit+<>c.<UpdateAllServices>b__63_0 (Microsoft.MixedReality.Toolkit.IMixedRealityService service) [0x00000] in <00000000000000000000000000000000>:0 
>   at UnityEngine.Windows.WebCam.VideoCapture+OnVideoCaptureResourceCreatedCallback.Invoke (UnityEngine.Windows.WebCam.VideoCapture captureObject) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.MixedRealityToolkit.ExecuteOnAllServices (System.Collections.Generic.IEnumerable`1[T] services, System.Action`1[T] execute) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.MixedRealityToolkit.ExecuteOnAllServicesInOrder (System.Action`1[T] execute) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.MixedRealityToolkit.Update () [0x00000] in <00000000000000000000000000000000>:0 

Then immediately after the first exception, I see this exception every frame:

> (Filename: currently not available on il2cpp Line: -1)
> 
> NullReferenceException: Object reference not set to an instance of an object.
>   at UnityEngine.Component.get_transform () [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.Input.BaseControllerPointer.get_Position () [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.Input.PokePointer.OnSourceDetected (Microsoft.MixedReality.Toolkit.Input.SourceStateEventData eventData) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem+<>c.<.cctor>b__196_0 (Microsoft.MixedReality.Toolkit.Input.IMixedRealitySourceStateHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00000] in <00000000000000000000000000000000>:0 
>   at System.EventHandler`1[TEventArgs].Invoke (System.Object sender, TEventArgs e) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.BaseEventSystem.HandleEvent[T] (UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] eventHandler) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.HandleEvent[T] (UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] eventHandler) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.RaiseSourceDetected (Microsoft.MixedReality.Toolkit.Input.IMixedRealityInputSource source, Microsoft.MixedReality.Toolkit.Input.IMixedRealityController controller) [0x00000] in <00000000000000000000000000000000>:0 
>   at Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityDeviceManager.InteractionManager_InteractionSourceDetected (UnityEngine.XR.WSA.Input.InteractionSourceDetectedEventArgs args) [0x00000] in <00000000000000000000000000000000>:0 
>   at UnityEngine.XR.WSA.Input.InteractionManager+SourceEventHandler.Invoke (UnityEngine.XR.WSA.Input.InteractionSourceState state) [0x00000] in <00000000000000000000000000000000>:0 
>   at UnityEngine.XR.WSA.Input.InteractionManager.OnSourceEvent (UnityEngine.XR.WSA.Input.InteractionManager+EventType eventType, System.IntPtr statePtr, UnityEngine.XR.WSA.Input.InteractionSourcePressType pressType) [0x00000] in <00000000000000000000000000000000>:0 

## To reproduce

Unclear how to reproduce.  However, hand pointer were unusable.  I needed to restart the application to resolve the issue.

## Expected behavior

Pointers to recover after exceptions.

## Your setup (please complete the following information)

- Unity Version: 2019.2.17f1
- MRTK Version: 2.2.0

## Target platform (please complete the following information)

- HoloLens 2

**Comment by Troy-Ferrell** [comment]
@AMollis , can you update to mrtk_dev or 2.3.0_stabilization?

This looks like it may have been fixed.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/25acfd3536543867f8cc38aca53f564c99c1ec20/Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs#L991

vs

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/b499db73297bdceb1c56ab886ab36b17857d028b/Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs#L991

**Comment by AMollis** [comment]
If the input system owner feels like this has been fixed. please resolve the bug.  I have no way of repo'ing (as this was a one time failure).

**Comment by wiwei** [comment]
Resolving as fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7111, we can revisit if this happens again after getting the new version.
