### ISSUE TITLE
Interactable gets stuck in "focused" and "pressed" state when a voice command is used

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#7112]
## Describe the bug

If an Interactable button responses to a voice command, Interactable::HasFocus and Interactable::HasPress gets stuck "true" until a pointer clicks the button.

Bug is within this function.  The "if statements" should have the _not_ operators removed...

```
protected IEnumerator GlobalVisualReset(float time)
{
    yield return new WaitForSeconds(time);
    HasVoiceCommand = false;
    if (!HasFocus)
    {
        HasFocus = false;
    }

    if (!HasPress)
    {
        HasPress = false;
    }

    globalTimer = null;
}
```

## To reproduce

1. Add voice command to MRTK's input profile  (e.g. "click my button")
2. Add Holographic button to scene
3. Go to button's Interactable behavior
4. Add "click my button" to the interactable's speech handler
5. Set the interactable's speech settings "require focus" to false.
6. Play app
7. Say "click my button"
8. RESULT. Button gets stuck in a focused and pressed state.

## Expected behavior

Clear focus and pressed states 

## Your setup (please complete the following information)

- Unity Version: 2019.2.17f1]
- MRTK Version: v2.2.0

## Target platform (please complete the following information)

- HoloLens 2

**Comment by Troy-Ferrell** [comment]
HasFocus should probably be ` HasFocus = focusingPointers.Count > 0;`

HasPress....might also need to track pointers or input sources. Because technically, I could push or touch an Interactable but not release my finger/touch...and then fire the voice command which would auto disable the HasPress even though I am still "pressing" it

**Comment by julenka** [comment]
assigned to bernadette for triage
