### ISSUE TITLE
Support importing MRTK via MSBuildForUnity

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#7121]
## Describe the problem

https://github.com/microsoft/MSBuildForUnity is another NuGet entry point for Unity. We need to update some of our NuGet files to support importing our Unity assets alongside the correct binaries.

**Comment by CDiaz-MS** [comment]
We also need to add documentation on how to consume the packages via MSBuildForUnity.

**Comment by wiwei** [comment]
Per comment here, this looks to have been addressed:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7113#issuecomment-577328519
