### ISSUE TITLE
Changing Interactable.IsToggled only works when its GameObject is active in the hierarchy

### ISSUE THREAD

**Issue by ShayneRC** [microsoft/MixedRealityToolkit-Unity#7125]
## Describe the bug

I have multiple checkboxes (CheckBox prefab from MRTK (MRTK.SDK/Features/UX/Interactable/Prefabs/CheckBox.prefab)) on different panels and I want them to be 'linked' such that when I toggle one from Off to On, the other 'linked' checkboxes do the same. I attempted this by setting the other checkboxes Interactable.IsToggled to match the toggled one but it would not work because those checkboxes weren't active in the hierarchy. It would only update if the Interactable.gameObject.activeInHierarchy was true.

As a work around, in my Update() I checked if the Interactable was now active in the hierarchy and if it didn't match the bool value then change the IsToggled. Although you can briefly see the previous state when switching panel.

## To reproduce

1. Set up test scene with MRTK.
2. Create 2 empty GameObjects. Name them Parent1 and Parent2
3. Add a CheckBox to each of those GameObjects as children. Lower the second CheckBox so they aren't overlapping.
4. Create the script below and add it to Parent1.
5. Drag and drop from the hierarchy to the script:
    a. CheckBox1 -> Checkbox One
    b. CheckBox2 -> Checkbox Two
    c. Parent2 -> Parent Two
6. For CheckBox1's OnClick() assign the ClickNotWorking().
7. Set Parent2's Active to false.
8. Run and toggle CheckBox1
    a. CheckBox2 will appear without being toggled.
9. Set CheckBox1's OnClick() to ClickWorking().
8. Run and toggle CheckBox1
    a. CheckBox2 will appear and will be toggled

```
public class BugTest : MonoBehaviour
{
    public Interactable checkboxOne;
    public Interactable checkboxTwo;

    public GameObject parentTwo;

    public void ClickNotWorking()
    {
        checkboxTwo.IsToggled = checkboxOne.IsToggled;
        parentTwo.SetActive(true);
    }

    public void ClickWorking()
    {
        parentTwo.SetActive(true);
        checkboxTwo.IsToggled = checkboxOne.IsToggled;
    }
}
```

## Expected behavior

Changing IsToggled should change the toggled state regardless if it is active in the hierarchy.

## Screenshots

![Scene](https://user-images.githubusercontent.com/54519937/72955004-47df6900-3dff-11ea-950d-abff458aef8e.png)
![Script](https://user-images.githubusercontent.com/54519937/72955007-4d3cb380-3dff-11ea-9a24-a435cdfbb9be.png)

## Your setup (please complete the following information)

- Unity Version 2019.2.16f1
- MRTK Version v2.2.0

## Target platform (please complete the following information)

- HoloLens 2

**Comment by julenka** [comment]
assigned to bernadette for triage

**Comment by Troy-Ferrell** [comment]
I think I found the issue. If the checkbox starts up inactive, then it's awake is never called. Thus, IsToggled calls get overwritten when it's finally activated because of Interactable.Awake()

After it's awake has been called, then it should work correctly there on out.
