### ISSUE TITLE
Newer version

### ISSUE THREAD

**Issue by andrasbalazs** [microsoft/MixedRealityToolkit-Unity#7155]
Hello There,

I'm just curious, do you have any plan to move MRTK to newer Unity version (for example 2019.2.19)?

Thanks.

**Comment by andreibosco** [comment]
The next stable version (2.3) will support Unity 2019.3: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/Roadmap.html

**Comment by andrasbalazs** [comment]
Awesome!

Can I ask you, when will be the next release? later than next week? Just curious about my project :). 

Thanks again.

**Comment by andreibosco** [comment]
I'm not one of the developers, I'm a regular user like you :)

But I'm guessing in the next couple of weeks? Shouldn't be too far away. You can keep track of the milestones here: https://github.com/microsoft/MixedRealityToolkit-Unity/milestones

**Comment by wiwei** [comment]
The latest version of the MRTK *should* be good on the 2019.2.x, though as @andreibosco mentions we'll be coming out with the next version "soon." We're currently working on stabilization/testing of it (you can see the various PRs going to the stabilization branch and such).

**Comment by keveleigh** [comment]
Are you running into specific issues with Unity 2019.3 on the latest MRTK releases? Would definitely like to make sure we support anything you're running into!

**Comment by andrasbalazs** [comment]
@wiwei Thank you very much for your answer :). 

@keveleigh No, i don't have any issue, my question has only close-future planning reasons. :).
