### ISSUE TITLE
Error: IOException: Win32 IO returned 234 when importing MRTK into Unity

### ISSUE THREAD

**Issue by zxzkf1992** [microsoft/MixedRealityToolkit-Unity#7157]
## Describe the bug

After i created new Unity project and imported MRTK, the error shown in the console.

## To reproduce

1. create Unity project
2. import MRTK

## Expected behavior

no error

## Your setup (please complete the following information)

- Unity Version 2018.4.15f
- MRTK Version v2.2.0

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2

## Additional context

IOException: Win32 IO returned 234. Path: C:\Users\kefei zhang\Desktop\MR_Test\Assets\MixedRealityToolkit.Providers\WindowsMixedReality\DotNetAdapter\Plugins\netstandard2.0\Microsoft.Windows.MixedReality.DotNetWinRT\Editor\Microsoft.Windows.MixedReality.DotNetWinRT.Init.cs
System.IO.FileStream.get_Length () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean checkHost) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.IO.StreamReader..ctor (System.String path) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
(wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
System.IO.File.ReadAllText (System.String path) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
UnityEditor.Scripting.Compilers.CSharpLanguage.ReadAndConverteNewLines (System.String filePath) (at D:/unity/Editor/Mono/Scripting/Compilers/CSharpLanguage.cs:152)
UnityEditor.Scripting.Compilers.CSharpLanguage.GetNamespaceNewRuntime (System.String filePath, System.String definedSymbols, System.String[] defines) (at D:/unity/Editor/Mono/Scripting/Compilers/CSharpLanguage.cs:91)
UnityEditor.Scripting.Compilers.CSharpLanguage.GetNamespace (System.String filePath, System.String definedSymbols) (at D:/unity/Editor/Mono/Scripting/Compilers/CSharpLanguage.cs:133)
UnityEditor.Scripting.ScriptCompilers.GetNamespace (System.String file, System.String
![Error](https://user-images.githubusercontent.com/45712264/73185102-c731ad00-411d-11ea-8cbb-43cff13c5483.png)

**Comment by keveleigh** [comment]
I believe you're running into the file path character limit of 160 here. 

@davidkline-ms I propose we take the proposed dependency folder naming (a root MixedRealityToolkit.Plugins folder) in 2.3, since this issue seems to be pretty frequent.

**Comment by wiwei** [comment]
@zxzkf1992 in the interim, I think that you can work around this by placing your project in a higher up folder (i.e. c:/project).

**Comment by zxzkf1992** [comment]
@wiwei I have never encountered this error before, under the same path

**Comment by zxzkf1992** [comment]
@keveleigh So this problem needs to be solved in version 2.3 ?

**Comment by Troy-Ferrell** [comment]
@zxzkf1992 if you create a new project in a folder path higher up, do you still see this error?

**Comment by zxzkf1992** [comment]
@Troy-Ferrell  i created the project on my desktop, C:\Users\kefei zhang\Desktop\
i think the name of this path should not be be very long.

**Comment by Troy-Ferrell** [comment]
@zxzkf1992 its your path plus all of the MRTK deep path that is the problem. MRTK needs to shorten its path which is what @keveleigh is referring to

To confirm this is the issue indeed for you, can you try recreating at C:/mrtk?
