### ISSUE TITLE
MRTK Standard shader does not load baked lightmap from Unity 2019.2

### ISSUE THREAD

**Issue by gregoireduttine** [microsoft/MixedRealityToolkit-Unity#7163]
## Describe the bug

A baked lightmap from a simple cube scene in Unity 2019.2 is not visible once deployed in the HoloLens 2.
Works in the Editor.
Works in Unity 2018.3 with MRTK standard shader but not in 2019.2
Works in HL2 and Unity 2019.2 with Unity standard shader but not with MRTK standard shader

## To reproduce

1. Create a simple scene with a plane, a cube and a baked directional light.
2. Set the plane in Static 'Contribute to GI' (new label in Unity 2019 for lightmap static).
3. Generate lightning in Unity (Lighting settings)
4. Run in the editor : you see the shadow and the baked lightmap on the plane
5. Deploy on the H2 : you do not see any shadow and lightmap on the plane

## Expected behavior

You should see on the H2 the baked lightmap like with the Unity standard shader

## Your setup (please complete the following information)

- Unity Version 2019.2.17f1
- MRTK Version 2.2.0

## Target platform (please complete the following information)

- HoloLens 2

![Screenshot (55)](https://user-images.githubusercontent.com/47125813/73197910-7a0c0600-4132-11ea-9ea8-83d66efe6dbf.jpg)
![20200127_092437_HoloLens](https://user-images.githubusercontent.com/47125813/73197932-7ed0ba00-4132-11ea-957a-bc9f15c3f9ee.jpg)

**Comment by wiwei** [comment]
@Cameron-Micka is this something that the MRTK Standard Shader could support, or would the runtime cost of this be too high for HL2/HL1 devices?

**Comment by Troy-Ferrell** [comment]
hmmm, might be something with 2019.2.17f1. I get baked lightmaps in both VR & AR on Unity 2018 LTS with MRTK standard shaders. I'll try out 2019.2 soon

**Comment by gregoireduttine** [comment]
looks like a issue with 2019. I have tested with multiple versions of Unity from 2019.1.0 up to 2019.2.17f1, same behavior

**Comment by Troy-Ferrell** [comment]
@gregoireduttine I believe I have found the issue. We have had issues with the MRTK standard shader in the past when compilation versions of it were excluded in the final built projects, especially when the shader was dynamically built/configured at runtime and not included in any scenes/prefabs etc. 

It appears in Unity 2019 they have changed this compilation logic somewhere and thus I am guessing the declaration LIGHTMAP_ON is not enabled for the built HL2 project. 

To force this declaration available and thus ensure the correct compiled versions of the MRTK shader are available, go to **EDIT** > **PROJECT SETTINGS** > **GRAPHICS**

There are two options
1) Force lightmaps on by changing *Lightmap Modes* under *Shader Stripping* from **Automatic** to **Custom** (this worked for me on device in 2019.2)
2) Add the MRTK standard shader file to the **Always included shaders** list. NOTE: This will ensure all compilations of the MRTK shader are included with your project. Thus, when building from Unity to UWP VS, your project compilation will be much longer...but you will always have all possible version of the MRTK shader available. 

![image](https://user-images.githubusercontent.com/25975362/73567725-cc437480-441b-11ea-8a69-e8892ce893cd.png)

We should keep this issue around as a documentation issue to put these learnings on the MRTK standard shader doc page

**Comment by edgarrodrigosantos** [comment]
Hi. I tried the suggestion of including the MRTK standard shader in the "Always included shaders" and I get an error building:

Mixed Reality Toolkit/Standard has too many Shader variants(9895604649984).To resolve this, go to Project Settings > Graphics and remove this Shader from the Always Included Shaders list.For more explicit control over how Unity includes specific Shader variants in a build, use a ShaderVariantCollection.

I was actually trying this for a related problem. I would like to apply the shader at runtime with a directional light, but that doesn't seem to work...

**Comment by Troy-Ferrell** [comment]
ah interesting, @edgarrodrigosantos . The shader has grown a lot. Try building the shadervariantcollection and seeing if that resolves it:
https://docs.unity3d.com/ScriptReference/ShaderVariantCollection.html

If the shader isn't used with any material, and related keywords, that is in one of the built scenes, then it won't be compiled and added into the build. 

Thus, the shader variant collection should work or you can create a hidden/empty object in your scene with a material using the MRTK standard shader

**Comment by Cameron-Micka** [comment]
@gregoireduttine thank you for reporting this! (It's great to see people using lightmaps on HoloLens.) 

I just got back from paternity leave, but will certainly take a peek at this. It sounds like @Troy-Ferrell has already found the issue (thank you!). It's possible Unity has a new mechanism in 2019 for toggling on lightmap support which I can check for. Else, we can make it a shader feature material property to avoid too many extra variants.

@wiwei to help answer your question. I would love if developers took advantage of static lighting more often. It's hard in AR applications to use since there are very few static objects, but there are certainly some compelling use cases. The MRTK/Standard shader does support a subset of Unity's lightmap system and is currently the only ways shadows and ambient occlusion are supported. It requires an extra texture sample, but that is less of a concern on HoloLens 2.

**Comment by Cameron-Micka** [comment]
This is still something I need to address!
