### ISSUE TITLE
Radial Set InteractableToggleCollection and Deselecting

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#7165]
## Describe the bug

As originally reported here
https://stackoverflow.com/questions/59676016/radial-set-interactabletogglecollection-and-deselecting

pretty new to MR development so bear with me here

I am trying to use the Radial Set to change states within my scene.

How I initially understood it's use is that the OnDeselect() function would be called on all other children part of the radial set that is not being pressed. But this seems to be not the case, as any function I add to the OnDeselect() is not being executed.

For example: In a set of

Radial A (active)
Radial B
Selecting Radial B would trigger Radial B's onSelected event (which it does) and Radial A's onDeselected event (which it doesn't)

enter image description here

I have also tried setting the Can Deselect to true on the radial buttons Interactable Script, but this is just overridden at run-time and set back to false.

If I am approaching this the wrong way and there is a better alternative to achieve what I am intending to please let me know

Thanks :)

## Your setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Troy-Ferrell** [comment]
Side issue: InteractableToggleCollectionInspector does not show public property OnSelectionEvents

**Comment by Troy-Ferrell** [comment]
Issue here is that InteractableOnToggleReceiver only fires OnClick in which case the interactable is deselected because of a press/click. 

With the InteractableToggleCollection, the interatable is toggled via it's `interactable.IsToggled` property which doesn't fire any click events. 

We could re-wire InteractableOnToggleReceiver to listen if `IsToggled` changes and then fire each event...but not sure that is clear behavior. It's weird to fire an event OnDeselection when the Interactable has `CanDeselect` to false.

**Comment by Troy-Ferrell** [comment]
Gonna dupe this to #7167 

InteractableOnToggleReceiver.OnDeselection should really only fire when the button is clicked deselected.

**Comment by liberty293** [comment]
Hi Troy, in this case, I think it makes sense for OnDeselection to fire when deselected via the ToggleCollection. The purpose of the ToggleCollection is to ensure only one toggle is selected at a time. However, if OnDeselection is never fired, is as if the toggle is always selected. 
For example, if you are using the ToggleCollection to display different states, but you only want one displayed at a time, you would want to disable a state when the toggle button turns off. However, the states would always be on if you cannot turn them off during deselection (of course you could write a new script with a reference to the toggle and check the state after a selection occurs, but it seems that the ToggleCollection has a very limited use if you cannot do anything when a button toggles off)
