### ISSUE TITLE
fixing maxY computation in InscribedRectangle constructor

### ISSUE THREAD

**Issue by mfraslin** [microsoft/MixedRealityToolkit-Unity#7171]
At line 127 of InscribedRectangle.cs, the maxY value is computed using Mathf.Min instead of Mathf.Max:

`maxY = Mathf.Min(edge.PointA.y, edge.PointB.y);`

While it works most of the time, it can causes a very long (several minutes) execution of InscribedRectangle constructor when the geometryEdges represent some specific shapes (in my case it was some kind of an L shape).

Be replacing Mathf.Min with Mathf.Max, it fixed the very long execution time. It seems to me that this is a valid fix but I may missing some details.

**Comment by wiwei** [comment]
This looks like it was just an oversight in the original checkin (i.e. as far back as two years ago).

I think the code as-is happens to work in many cases where things are aligned well with the min y axis but I can think of some cases where this would fail to produce the largest inscribed rectangle.

I'll see if I can write a test case to verify this...

**Comment by wiwei** [comment]
Yep, this is a case where the existing code would fail:"

```c#
/// #
        /// ###
        /// #####
        /// #######
        /// #########
        /// ###########
        /// #############
        /// ###############
        /// #################
        /// ###################
        /// #####################
        /// #######################
        /// #########################
        /// ###########################
        /// #############################
        /// #
        /// #############################
```

Gotta fix for this coming up.
