### ISSUE TITLE
NearTouchInteractable & sphere collider

### ISSUE THREAD

**Issue by Thomas-6freedom** [microsoft/MixedRealityToolkit-Unity#7177]
## Describe the issue
In this [page ](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/HowToAddNearInteractivity.html)of the documentation it explains how to configure a NearTouchInteractable with a box collider.
However when using a sphere collider, the buttons "Fix Bounds" and "Fix Center" does not appear, so the user is tempted to let the value as they are and have a 0 sized bounds and the touch cannot work.

## Feature area
I suggest to change the documentation on this [page](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/HowToAddNearInteractivity.html) to add a line "Warning : if you are using a sphere collider, choose a bounds manually like x: 1, y: 1" 

## Existing doc link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/HowToAddNearInteractivity.html

Thank you

**Comment by wiwei** [comment]
Interesting - AFAICT NearTouchInteractable is great for objects with box objects specifically. There's another NearInteractionTouchableVolume that's more appropriate for arbitrary objects (i.e. where there isn't a well defined forward plane).

**Comment by Thomas-6freedom** [comment]
Oh yes! There is event a note about that... Sorry.

**Comment by wiwei** [comment]
I think that the docs could definitely be updated to be clearer (i.e. being upfront about how that specific step is really just for box colliders). I can still update the docs to avoid this confusion in the future
