### ISSUE TITLE
Update project settings .net target to 4.6

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#718]
Unity Editor 5.6 now support .net target 4.6

Some features would be beneficial.

Pros? Cons?

**Comment by HoloFan** [comment]
Does the new Unity Version allows CLI-Wrapping? If yes, we could switch from marshalling to CLI-Wrapping when using external dlls.

**Comment by Holo-Krzysztof** [comment]
@HoloFan What do you mean by CLI wrapping? Using C++/CLI?
