### ISSUE TITLE
TapToPlace

### ISSUE THREAD

**Issue by iotMice** [microsoft/MixedRealityToolkit-Unity#7190]
## Describe the issue
Not able to implement TapToPlace feature in Hololens 1 with mrtk 2.2.0

## Feature area
The documentation provided is for Hololens toolkit.
Do let me know what is the exact procedure to implement the same.

**Comment by wiwei** [comment]
Oh man, great timing :)

Take a look at: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7188
