### ISSUE TITLE
Conflict between AzureSpatialAnchor SDK and MRTK2 on UWP

### ISSUE THREAD

**Issue by NicolasCalvi** [microsoft/MixedRealityToolkit-Unity#7191]
## Overview
They are a namespace conflict between MRTK2 and Azure Spatial Anchors SDK on UWP target.
In the ".\Assets\AzureSpatialAnchors.SDK\Scripts\SpatialAnchorManager.cs" file we have at line 320 and 321 a reference of "Windows.Perception.Spatial.SpatialPerceptionAccessStatus" object in UWP framework.
But, when we build, the compilator replace "Windows.Perception.Spatial.SpatialPerceptionAccessStatus" by "Micorosoft.Windows.Perception.Spatial.SpatialPerceptionAccessStatus". 

The "Micorosoft.Windows.Perception.Spatial" in MRTK hide the "Windows.Perception.Spatial" in UWP.

Separetly this two SDK works fine.

Errors generated :

"Assets\AzureSpatialAnchors.SDK\Scripts\SpatialAnchorManager.cs(320,44): error CS0234: The type or namespace name 'SpatialPerceptionAccessStatus' does not exist in the namespace 'Microsoft.Windows.Perception.Spatial' (are you missing an assembly reference?)"

"Assets\AzureSpatialAnchors.SDK\Scripts\SpatialAnchorManager.cs(320,95): error CS0234: The type or namespace name 'SpatialAnchorExporter' does not exist in the namespace 'Microsoft.Windows.Perception.Spatial' (are you missing an assembly reference?)"

"Assets\AzureSpatialAnchors.SDK\Scripts\SpatialAnchorManager.cs(321,50): error CS0234: The type or namespace name 'SpatialPerceptionAccessStatus' does not exist in the namespace 'Microsoft.Windows.Perception.Spatial' (are you missing an assembly reference?)"

## Expected behavior
Can build application with MRTK and Azure Spatial Anchors SDK in the same project.

## Actual behavior
Error at buil beacause "Windows.Perception.Spatial.SpatialPerceptionAccessStatus" class cannot located because of the existance of "Microsoft.Windows.Perception.Spatial" namespace in MRTK.

## Steps to reproduce
- Create a Unity project for Hololens (UWP) 
- Add package of MRTK 2.2 
- Add package of AzureSpatialAnchors SDK located at https://github.com/Azure/azure-spatial-anchors-samples.git.
- Build the application

## Unity editor version
2019.2.19

## Mixed Reality Toolkit release version
2.2

**Comment by keveleigh** [comment]
This is a conflict with https://www.nuget.org/packages/Microsoft.Windows.MixedReality.DotNetWinRT, which imports during MRTK configuration if "Enable MSBuild for Unity" is checked.

I believe the Spectator View project was hitting a similar thing.

@dfields-msft, do you know if there's anything we can do here, short of asking ASA to rewrite their scripts?

**Comment by dfields-msft** [comment]
@keveleigh I'm afraid not... When these conflicts arise, there are two possible resolutions:
1. Qualify the Windows namespace references with `global::`
2. Switch over to referencing Microsoft.Windows.MixedReality.DotnetWinRT (assuming it supports all re requisite types... And if it doesn't, follow up with me to see about adding them).

**Comment by Maheenmathew** [comment]
Hi @NicolasCalvi  I got the 3 errors you have mentioned above and also 2 extra ones:
- Failed to parse AsmDef meta for asm def: 'C:\Users\xxx\Documents\Hololens\Unity Projects\New UnityProject\Assets\MixedRealityToolkit.Providers\WindowsMixedReality\DotNetAdapter\Plugins\net46\Microsoft.Windows.MixedReality.DotNetWinRT\Editor\Microsoft.Windows.MixedReality.DotNetWinRT.Editor.asmdef', didn't find guid.
UnityEngine.Debug:LogError(Object)

- Failed to parse AsmDef meta for asm def: 'C:\Users\xxx\Documents\Hololens\Unity Projects\New UnityProject\Assets\MixedRealityToolkit.Providers\WindowsMixedReality\DotNetAdapter\Plugins\net46\Microsoft.Windows.MixedReality.DotNetWinRT\Editor\Microsoft.Windows.MixedReality.DotNetWinRT.Editor.asmdef', didn't find guid.
UnityEngine.Debug:LogError(Object)

I understand I am not giving solutions, just adding to the list, so apologies. But was wondering did you face something similar and if yes, what resolution steps did you carry out.

Appreciate any help you can provide.

**Comment by keveleigh** [comment]
>Failed to parse AsmDef meta for asm def

For these, they're related to the path length being too long for Unity to properly load. I have a PR in the works that'll help shorten this path as far as what MRTK adds to it.

**Comment by Maheenmathew** [comment]
> > Failed to parse AsmDef meta for asm def
> 
> For these, they're related to the path length being too long for Unity to properly load. I have a PR in the works that'll help shorten this path as far as what MRTK adds to it.

@keveleigh : That would be brilliant! Thanks a lot for the immediate reply. When its complete would you please share the link.

**Comment by NicolasCalvi** [comment]
> @keveleigh I'm afraid not... When these conflicts arise, there are two possible resolutions:
> 
> 1. Qualify the Windows namespace references with `global::`
> 2. Switch over to referencing Microsoft.Windows.MixedReality.DotnetWinRT (assuming it supports all re requisite types... And if it doesn't, follow up with me to see about adding them).

I try to make this namespace Global, but I have this error 👍 

Assets\AzureSpatialAnchors.SDK\Scripts\SpatialAnchorManager.cs(24,15): error CS0400: The type or namespace name 'Windows' could not be found in the global namespace (are you missing an assembly reference?)

**Comment by keveleigh** [comment]
Is that showing up when you try to build? Or just by loading in the Unity editor?

**Comment by NicolasCalvi** [comment]
@keveleigh both. But separatly, the to SDK compile without problems. It's just when I put them together.

**Comment by keveleigh** [comment]
The error about the global namespace?

**Comment by NicolasCalvi** [comment]
Yes, I think the Microsoft.Windows.Perception.Spatial of the MRTK hides the Windows.Perception.Spatial namespace of UWP framework. It's a namesapce conflict I think. 
And whe the reference assembly is resolved, it's a mess between the two SDK.

**Comment by NicolasCalvi** [comment]
@keveleigh I find a interesting case, with the MRTK 2.1, the both SDK can compile together. The problem is with the MRTK 2.2.
If it can help you :)

**Comment by keveleigh** [comment]
@NicolasCalvi Ah yes! That makes sense, since 2.2 is when we started importing the DotNetWinRT plugin.

One workaround at the moment, if you don't need HoloLens 2 hand joints over holographic remoting, would be to go to Window -> Package Manager and uninstall MSBuild for Unity. Then, you can search for DotNetWinRT in your assets list in Unity and delete the Plugins folder to remove the adapter. That should remove these conflicting namespaces, while keeping MRTK around.
You'll just need to make sure you don't re-enable MSBuild for Unity in the MRTK configurator if / when it pops up.

**Comment by PedroMontes** [comment]
Same error here.

**Comment by PedroMontes** [comment]
> @NicolasCalvi Ah yes! That makes sense, since 2.2 is when we started importing the DotNetWinRT plugin.
> 
> One workaround at the moment, if you don't need HoloLens 2 hand joints over holographic remoting, would be to go to Window -> Package Manager and uninstall MSBuild for Unity. Then, you can search for DotNetWinRT in your assets list in Unity and delete the Plugins folder to remove the adapter. That should remove these conflicting namespaces, while keeping MRTK around.
> You'll just need to make sure you don't re-enable MSBuild for Unity in the MRTK configurator if / when it pops up.

I tried this and appeared other conflicts with the Microsoft and Windows library. :(

Should we downgrade to MRTK 2.1 to fix this temporarily?

Thanks

**Comment by dfields-msft** [comment]
The Windows APIs being referenced by the Azure Spatial Anchors scripts are feasible to include in Microsoft.Windows.MixedReality.DotNetWinRT itself, which would resolve this conflict. I'll look into publishing an update to that package to add coverage for `SpatialPerceptionAccessStatus` and `SpatialAnchorExporter`.

In the meantime, I'm surprised that the `global::` workaround isn't working... @NicolasCalvi can you point me to the specific version of the Azure Spatial Anchors scripts that you're using? I looked at the version here, and there's no reference to the Windows namespace on line 24:
https://github.com/Azure/azure-spatial-anchors-samples/blob/master/Unity/Assets/AzureSpatialAnchors.SDK/Scripts/SpatialAnchorManager.cs#L24

**Comment by dfields-msft** [comment]
@PedroMontes which specific conflicts did you encounter after disabling MSBuild for Unity?

**Comment by dfields-msft** [comment]
I've published an update to the Microsoft.Windows.MixedReality.DotNetWinRT package which should resolve this; please update to version 0.5.**1045** and let me know if you still have any problems:
https://www.nuget.org/packages/Microsoft.Windows.MixedReality.DotNetWinRT/0.5.1045

**Comment by keveleigh** [comment]
Closing as fixed with #7267 and DotNetWinRT 0.5.1045 or newer.
