### ISSUE TITLE
Non-existent assembly 'Unity.XR.ARFoundation' 

### ISSUE THREAD

**Issue by vaoliva** [microsoft/MixedRealityToolkit-Unity#7192]
## Describe the bug

UnityAR provider is not included in the latest Pre Release / Stabilization 2.3 Packages.
 
## How to reproduce

Import all built 2.3 pre release packages (28.01.2019) to a new empty Project.
The following error is throwed:

Assembly has reference to non-existent assembly 'Unity.XR.ARFoundation' (Assets/MixedRealityToolkit.Providers/UnityAR/Microsoft.MixedReality.Toolkit.Providers.UnityAR.asmdef).

Installing Unity AR Foundation  through the Unity Package Manager solves the issue.

## Your setup (please complete the following information)

- Unity Version 2018.4.12f1 and 2019.3.0f6
- MRTK Version 2.3 Pre Release

## Target platform (please complete the following information)

- Any

**Comment by davidkline-ms** [comment]
This is an artifact of moving the UnityAR provider into the foundation package. It should be distributed as a separate package.

**Comment by keveleigh** [comment]
@davidkline-ms If we want to distribute it alongside the other providers, we just need to make sure the asmdef doesn't get rewritten by the configuration checker before packaging occurs.

**Comment by davidkline-ms** [comment]
@keveleigh, excellent point!

**Comment by wiwei** [comment]
@davidkline-ms is there any way we can add a test or some infrastructure to make sure we don't regress this again?

**Comment by davidkline-ms** [comment]
@wiwei, i will look into it. the issue is that, to enable validation / ci to ensure the code meets standards / and compiles, we need the relevant packages in our manifest. them being present makes it difficult to automate a test for this scenario
