### ISSUE TITLE
InputActionHandler events are fired even when the related InputAction doesn't happen

### ISSUE THREAD

**Issue by ValtielChan** [microsoft/MixedRealityToolkit-Unity#7201]
## Describe the bug

I'm using the InputActionHandler script provided by the MRTK without any modification and the events OnInputActionStarted & OnInputActionEnded are fired for nothing.
In my case, if the InputAction is set to "Select", the event is fired even if there's no air-tap.

## To reproduce

Sometime, whatever position your hands are in, a "Select" event will be detected.
It seems to happen often in laggy scene and it's more difficult to reproduce in a smooth running scene.

## Expected behavior

With the inputAction set on "Select", the event should fire only when a real air-tap is done.

## Your setup (please complete the following information)

- Unity Version 2018.4.12f1
- MRTK Version v2.1

## Target platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
@keveleigh to keep me honest.

This is super weird, though this is probably some weird interaction between the device and lower level APIs themselves - i.e. the MRTK itself doesn't synthesize "select" from nothing - it is told by lower level APIs that such a gesture happens, and then it will fire that off in response to that.

I'm guessing there's something weird associated with the hardware/environment that's triggering this - I also see that lagginess is mentioned (so maybe there's some queued select that happens).

Also, 'select' can be triggered by other events (i.e. voice saying 'select') - I could imagine the speech system also suffering from some weirdness and maybe thinking something happened.

I think maybe the best way to figure out what's going on here is if you could add some logging to this line:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/5d290de52c7aa1ddec58281c58b12840676530fb/Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs#L1137

i.e. basically logging the callstack: https://docs.microsoft.com/en-us/dotnet/api/system.environment.stacktrace?view=netframework-4.8

And then sharing out what's triggering it.

**Comment by wiwei** [comment]
@ValtielChan FYI

**Comment by wiwei** [comment]
Closing this one out because we don't have enough information here to make progress - feel free to reopen with more info (or to carry on convo about what you're hitting)
