### ISSUE TITLE
Assertion Failed PokePointer OnValidate

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#7213]
## Describe the bug

On import of the MRTK Foundation NuGet package two Assertion failed statements are logged.  The source is the PokePointer OnValidate.

```
        protected void OnValidate()
        {
            Debug.Assert(line != null, this);
            Debug.Assert(visuals != null, this);
            touchableDistance = Mathf.Max(touchableDistance, 0);
            sceneQueryBufferSize = Mathf.Max(sceneQueryBufferSize, 1);
        }
```

```
Assertion failed
UnityEngine.Debug:Assert(Boolean, Object)
Microsoft.MixedReality.Toolkit.Input.PokePointer:OnValidate()
UnityEditor.AssetDatabase:LoadAssetAtPath(String)
Microsoft.MixedReality.Toolkit.Editor.ScriptableObjectExtensions:GetAllInstances()
Microsoft.MixedReality.Toolkit.Editor.SceneInfoUtils:RefreshSceneInfoFieldsInScriptableObjects()
Microsoft.MixedReality.Toolkit.Editor.SceneInfoUtils:InitializeOnLoad()
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()

```

## To reproduce

1. Import the latest 2.3 test Foundation NuGet package via NuGet for Unity
2. Observe the console 

## Your setup 

- Unity Version 2018.4.14
- MRTK Version v2.3 test packages NuGet

**Comment by keveleigh** [comment]
We should maybe re-evaluate this `OnValidate` via the info in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4202#issuecomment-495765433 and https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4899
