### ISSUE TITLE
There is no way to get hand data without using MRTK's Input System

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7219]
## Describe the bug

Sometimes, I want to know the positions of hand joints, but don't actually want to use MRTK's input system. For example, if I'm making an interactive art piece where I don't want any MRTK input active. Or, if I want to build my own input system. It would be nice if I could get the position, rotation of hand joints (either from HoloLens, other sensors, or simulated hands) without needing the MRTK input system to be enabled.

## To reproduce

1. Disable MRTK's input system
2. Call `HandJointUtils.TryGetJoint(JointType.IndexTip)` in an update loop in your code
3. Run your scene, and bring up either a simulated hand, or your real hand, using HoloLens 2.

## Expected behavior

I expect to get the position of the fingertip. However, what I actually get is nothing, because the MRTK input system is not active. It would be nice if we could decouple getting sensor data from the input system in MRTK.

## Screenshots

N/A

## Your setup (please complete the following information)

N/A 

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by davidkline-ms** [comment]
This is a v3 timeframe item. Things to consider:

- Migration to the Unity XR SDK Input system
- How to best represent an MRTK abstraction for a hand
- How to start / operate a data provider outside of it's parent service
- Consider if the concept of a data provider needs to be rethought (provider as just another system?)

**Comment by Zee2** [comment]
Solved by OpenXR and partly our package modularity. You can query joint data directly from OpenXR, or just use our hands subsystems without the rest of MRTK.
