### ISSUE TITLE
There is no way to get eye gaze information and also use head + airtap as primary input method

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7220]
## Describe the bug

Let's say I want to use hand head gaze for input, but still know where the user is looking. I would like to call `InputRayUtils.TryGetEyeGaze` to get this information, however currently that method will return false if the EyeGazeProvider is not the primary gaze provider for MRTK. I wish there was a way for me to just know where the eyes were looking in MRTK without needing to write custom code, and without using eye gaze as an input method.

## To reproduce

1. Disable Eye Tracking in the GazeProvider so that for input, the system is using head gaze instead of eye gaze.
2. In your code, call `InputRayUtils.TryGetEyeGaze` or , grab eye gaze info from EyeGazeProvider.
3. Deploy to Hololens 2, with eye tracking enabled.

## Expected behavior

I expect to both  `InputRayUtils.TryGetEyeGaze` or , EyeGazeProvider direction to return my eye gaze, since eye tracking is enabled.

However, the system actually returns the idrection of my head gaze, not my eye gaze.

I expect that if I am on a device that supports eye tracking, that MRTK has a built in way for me to access eye gaze data without needing to also use eye gaze as an input method.

## Workaround
Currently to work around this issue it's possible to call the WinRT APIs directly, see [EyeGaze.cs](https://gist.github.com/julenka/874ce481287dd49e59cc3f1fab4465cf).

## Screenshots

N/A

## Your setup (please complete the following information)
N/A

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target platform (please complete the following information)
N/A

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by sostel** [comment]
The HoloLens 1 profile is probably missing the "Windows Mixed Reality Eye Gaze Provider": 
![image](https://user-images.githubusercontent.com/32180789/73702990-4e919a00-46a3-11ea-8543-e4c0e8131ea3.png)

For additional info on how to access eye gaze while hand rays are active, you can also refer to this page: 
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/EyeTracking/EyeTracking_TargetSelection.html#example-4-use-hand-rays-and-eye-gaze-input-together

Let me know if that helps!

**Comment by julenka** [comment]
Hi @sostel thanks for the answer. I think I misworded the bug -- the case I wanted was to use head gaze + airtap as the primary input method, but also know where the eyes are looking. Is this possible?

**Comment by sostel** [comment]
Yes, that should work. In my prototype, I have a head gaze mode while still showing a custom eye gaze cursor. Let me double check that though.
