### ISSUE TITLE
2-hand manipulation makes objects always jump to .05 scale

### ISSUE THREAD

**Issue by KarlSupertramp** [microsoft/MixedRealityToolkit-Unity#7222]
## Describe the bug
I'm working on an application that used to run smooth on HL1. I can load (instantiate) several objects and move them freely using the ManipulationHander & BoundingBox. Everything looks fine so far. Near interaction, rotation, highlighting etc. all works. But when I use two hands, to scale or rotate, all my objects transition to .05 scale (xyz) within a fraction of a second. I disabled all my code & functionality, but this is still happening.
Changing settings like max/min scale did not help, either. There seems to be a new component "TransformScaleHandler" that's added in runtime. But disabling or changing its values still did not fix it.

Not sure what causes this problem, it feels like a bug.

## To reproduce
Create an Object with:
- BoxCollinder
- BoundinBox
- ManipulationHander
- NearInteractionGrabbable

Then grab it with both handrays (bug also occurs in the editor)

## Your setup (please complete the following information)

- Unity Version 2019.2.11f1
- MRTK Version v2.2

## Target platform (please complete the following information)
- HoloLens 2

**Comment by wiwei** [comment]
@MenelvagorMilsom, maybe something specific to the older one, or you think it also affects the second iteration of these two components?

**Comment by MenelvagorMilsom** [comment]
@wiwei I'll have a quick look today.

**Comment by MenelvagorMilsom** [comment]
I can't repro in editor or on device for either v2.2.0 or latest `mrtk_development`. Here's a gif I recorded with the set up described in _To reproduce_ above, using 2.2 packages:
![two_hand_working](https://user-images.githubusercontent.com/47415945/73841903-7738a180-4813-11ea-9a5a-d72d4dec1e25.gif)

@KarlSupertramp, in your repro steps, did you change any of the properties of `BoundingBox` or `ManipulationHandler`? Also, can you try to reproduce on the latest `mrtk_development` and see if your problem persists?

**Comment by KarlSupertramp** [comment]
Ok sorry, I forgot a part. The bounds of my BoxCollider are generated, while the object is intantiated. I'm afraight the BoundingBox is not able to fit itself to a changing BoxCollider. 

So I guess this more a feature request: Updatable BoundingBox?

**Comment by KarlSupertramp** [comment]
Ok sorry I forgot one part that happens before the object is instatiated. I'm using DOTween to smoothly load my objects into the scene. The ManipulationHander or BoundingBox seem to save the scale value on Start(). I'll take a closer look into those classes, maybe I can find a workaround.

It would be helful to manually update any values that are set at Start(). Feature Request?

**Comment by MenelvagorMilsom** [comment]
Cool. If you want to repurpose this issue as a feature request, or create a new feature request, feel free to do so.
