### ISSUE TITLE
Request for Color Picker

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#7226]
From slack:

Any way you could bring to MRTK v2 the paint/color picker functionality that used to be available? https://docs.microsoft.com/en-us/windows/mixed-reality/mixed-reality-213  Thanks.

**Comment by polar-kev** [comment]
Hi @zhudaxing, a color picker feature was added to MRTK 2.5 as an experimental feature.
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/release-notes/mrtk-25-release-notes?view=mrtkunity-2021-05#color-picker-experimental

![image](https://user-images.githubusercontent.com/30964480/125333597-46f60c00-e2ff-11eb-9102-7eb90375f3de.png)
