### ISSUE TITLE
MRTK Examples Hub 2.2 for HL2 fails to deploy

### ISSUE THREAD

**Issue by reneschulte** [microsoft/MixedRealityToolkit-Unity#7233]
## Describe the bug

Trying to sideload the 2.2 Examples Hub appx with a HL2 fails to install.
The Examples Hub for 2.1 works just fine. 

## To reproduce

Download this 
MRTK.Examples.Hub_v2.2.0_HoloLens2_ARM.zip
https://github.com/microsoft/MixedRealityToolkit-Unity/releases/download/v2.2.0/MRTK.Examples.Hub_v2.2.0_HoloLens2_ARM.zip 

And sideload on a HL2 device.
Fails to install.

## Expected behavior

Should install.

## Target platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
@reneschulte do you have any specific errors/logs that you see when this happens?

**Comment by Troy-Ferrell** [comment]
@cre8ivepark can you validate 2.3 Examples Hub appx  sideload works?
