### ISSUE TITLE
MixedRealityInputSystem.RaisePointerDown event throws exception if GameObject was destroyed

### ISSUE THREAD

**Issue by djohnsomsft** [microsoft/MixedRealityToolkit-Unity#7236]
On the first line:

Transform currentObject = pointer.Result?.Details.Object?.transform;

This null check does not function properly because Unity doesn't overload the ?. operator. There needs to be an explicit == null check.

This causes the rest of the logic controlling pointer behavior like updating focus lock to fail to execute.

**Comment by wiwei** [comment]
I think this particular issue was fixed a while back (if you take a look at mrtk_development, the code was changed some time ago).

It does bring up the age old discussion around how we deal with Unity's null operator overload, which we still don't really have a great answer to (also not sure if there's a universally great story here and would love to know if anyone else out there has some workable solutions)
