### ISSUE TITLE
DotNetAdapter and MSB4U Dependencies csproj loop

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#7239]
## Describe the bug

On import of the latest 2.3 test packages into Unity 2019.3.0f6, MSBuild csprojs continue in an infinite loop:

![FoundationImportError](https://user-images.githubusercontent.com/53493796/73893124-a65c0c80-482d-11ea-83e1-004e5c0cbd37.gif)

## To reproduce

1. Import the latest unity foundation package into Unity 2019.3.0f6

**Comment by davidkline-ms** [comment]
The MRTK will be transitioning from using MSBuild for Unity to UPM in a future release. To work around this issue, developers should install a NuGet client (ex: https://github.com/GlitchEnzo/NuGetForUnity/releases) and install the Microsoft.MixedReality.DotNetWinRT package.

**Comment by keveleigh** [comment]
I wonder if there's any chance this was fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7833, which also seemed specific to Unity 2019.3?
