### ISSUE TITLE
Holographic Remoting & Hand Tracking Errors: HandConstraintPalmUp & IHolographicCameraRenderingParameters Error

### ISSUE THREAD

**Issue by hiqb217** [microsoft/MixedRealityToolkit-Unity#7245]
## Describe the bug

When running hand-tracking demo's supplied in MRTK on Unity on HoloLens 2 via Holographic Remoting, it can't seem to support the full hand tracking abilities. Palm-rays are still emitted and functional, but finger-based interaction with holograms is not possible. 

These two errors show in the Unity console:
```
Failed to get IHolographicCameraRenderingParameters from main camera for updating rendering parameter.
```

```
HandConstraintPalmUp requires controllers of type IMixedRealityHand to perform hand activation tests.
UnityEngine.Debug:LogError(Object)
```

**However**, if this setup is used to build and deploy an app to the HoloLens 2, the demos work as expected.

## To reproduce

1. Install Holographic Remoting app on HoloLens 2
2. Import MRTK Foundation, MRTK Examples packages on Unity
3. Open HandMenuExamples.unity scene from Examples folder
4. Open Holographic Remoting App on HoloLens 2
5. Window>XR>Holographic>Holographic Emulation
6. Connect, and then press play in Unity Editor
7. Bring hands into frame 

## Expected behavior

Should be able to interact with holograms by touch and should be able to view a mesh representing the hands as with a deployed app.

## Screenshots

![](https://i.imgur.com/vSH1mep.png)

## Your setup

- Unity Version [2018.4.16f1]
- MRTK Version [v2.2.0]

## Target platform

- HoloLens 2
- Holographic Remoting App

**Comment by NLR-L** [comment]
I'm also having this issue in Unity 2019.3.2f1

**Comment by NLR-L** [comment]
Still occurs in 2019.3.9f1

**Comment by keveleigh** [comment]
`Failed to get IHolographicCameraRenderingParameters from main camera for updating rendering parameter.` should be fixed in Unity 2018.4.19 and 2019.3.7. See #6807 for more info.

The `HandConstraintPalmUp` sounds like an MRTK issue that won't be affected by Unity version.

**Comment by keveleigh** [comment]
Looks like the `HandConstraintPalmUp requires controllers of type IMixedRealityHand to perform hand activation tests.` message is actually incorrect. The issue here is that no palm joint was reported. I've opened https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7668 to update the log.

It seems like you might not have gone through the set-up steps to enable additional HL2 features over remoting, like hand joints. Please take a look at [our guide](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html#hololens-2) and see if your setup matches those steps.

**Comment by NLR-L** [comment]
I could not get the MSBuild for unity to work (there was no option in the project configurator), but using https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html#manual-dotnetadapter-installation it worked just fine. My hands are now showing up, thanks for telling me what to do @keveleigh

**Comment by keveleigh** [comment]
Glad to hear it! Closing this one out
