### ISSUE TITLE
Securing Direct Headset Pairing

### ISSUE THREAD

**Issue by ivosluganovic** [Microsoft/MixedRealityToolkit-Unity#725]
Hi all,

We are a group of security researchers from the University of Oxford who are currently focusing on the security of HoloLens devices and the general Microsoft Mixed Reality platform.

As part of our research, we are looking into methods of securely establishing initial communication between two HoloLens devices to establish shared holographic experiences, but without relying on a third-party service or online connectivity.
This is crucial in order to prevent man-in-the-middle attacks and subsequent eavesdropping on the communication that can happen if the integrity of the information exchanged over unsecured wireless channel is not verified via some out-of-band channel.

Unfortunately, even though many apps for the Windows Mixed Realiry rely on direct communication between AR devices, there is currently no implementation or an achievable proposal for secure direct pairing of two AR headsets.
The previous proposals for device pairing are not directly applicable to AR headsets, since they assume a single user that controls both devices, which is the case for AR.

In order to close this gap, we proposed a pairing protocol, built a working prototype and experimentally evaluated the security and usability of our proposal, which we describe in our latest paper.

Given that our goal is not only to publish research, but to actively contribute to improving the security of the Platform, we have recently been instructed that raising an issue in this repository and potentially adding our prototype as one of the HoloToolkit-Unity examples might be the best way forward.
Our current prototype implementation is available as a fork under a repository which was anonymised for the double-blind submission: https://tinyurl.com/holopair

Ideally, some form of secure direct pairing should be integrated in the core Sharing module, but we are aware that this is process that depends on many other factors.

Since we plan to continue improving the code, we would greatly appreciate if you could give your opinion:
     
_Would such an application make sense as one of the HoloToolkit-Unity Examples, or is there a more suitable place to make it available to the wider development community?_

**Comment by Ziugy** [comment]
I'm definitely interested in your findings! How much will this be based on utilizing UNet? What in particular have you found thus far which is unsecured? Is this just validating that the proper device joined the shared experience?

**Comment by ivosluganovic** [comment]
That's awesome to hear!

Yes, the challenge that we are currently focusing on indeed boils down to "how to authenticate the devices with the help of their human owners?" In on other words, is it really the headset of the person in front of me that my HoloLens is communicating with over Wi-Fi, or is someone relaying (eavesdropping and potentially modifying) all the information that is being exchanged.

At the moment, UNet does not provide any encrypted communication to e.g., exchange of the WorldAnchor), but even if that was the case, the two headsets would need to establish a secure channel first. Thus our current research looking at how to do this securely and usably for AR/MR headsets.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
