### ISSUE TITLE
Pokepointer fails to activate on giant slate

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7258]
## Describe the bug
Regression from #7016 -- if you make a slate huge, it's possible to get the poke pointer to fail to activate. See the GIF for repro.

![image](https://user-images.githubusercontent.com/168492/74067046-31afdc00-49ad-11ea-97d6-17535a1553db.png)

## To reproduce

1. Make slate huge
2. Get close to slate and try to touch it

I expect to touch the slate, but actually I cannot touch it because the poke pointer fails to activate.

**Comment by keveleigh** [comment]
Fixed via #7283
