### ISSUE TITLE
"Float" holograms

### ISSUE THREAD

**Issue by kripll** [Microsoft/MixedRealityToolkit-Unity#726]
Our development team is doing a medical project. When you insert your foot into the dummy and start to look at it from different sides, it creates the feeling that the model in the dummy "swims". Is there any way to solve this problem?

**Comment by davesmits** [comment]
does it have a collider? see https://developer.microsoft.com/en-us/windows/mixed-reality/Hologram_stability.html

**Comment by StephenHodgson** [comment]
I believe you're in need of an anchor.

**Comment by christjt** [comment]
This could also be an effect caused by inter-pupillary distance configuration where it is not correct for a given specific user. You may also notice that this "swimming" effect may be different depending on the user. Check this repo: https://github.com/Microsoft/HoloLensCompanionKit/tree/master/KinectIPD for automatic configuration. I also think doing the "learn gesture" tutorial in HoloLens sets the IPD.

**Comment by StephenHodgson** [comment]
It could also be caused by a low fps, if your model/shader are resource intensive.

**Comment by mattfedocsg** [comment]
In my experience, @StephenHodgson is right.  Your shaders have to be optimized or use the Holotoolkit shaders and your poly counts should be low to avoid lag.

**Comment by kripll** [comment]
The exact same swimming is noticeable in the standard Holograms app, although Hololens issues 60 fps

**Comment by StephenHodgson** [comment]
[Microsoft Mixed Reality Documentation for Spatial Anchors](https://developer.microsoft.com/en-us/windows/mixed-reality/spatial_anchors)
> Spatial anchors stabilize their coordinate system near the anchor's origin. If you render holograms more than about 3 meters from that origin, those holograms may experience noticeable positional errors in proportion to their distance from that origin, due to lever-arm effects. That works if the user stands near the anchor, since the hologram is far away from the user too, meaning the angular error of the distant hologram will be small. However, if the user walks up to that distant hologram, it will then be large in their view, making the lever-arm effects from the faraway anchor origin quite obvious.

**Comment by NeerajW** [comment]
Please reopen if your question was not answered.
