### ISSUE TITLE
Constraint on Rotation Should Reflect Axis that Can't Be Rotated, Not Axis that Can

### ISSUE THREAD

**Issue by VRacity** [microsoft/MixedRealityToolkit-Unity#7262]
## Describe the problem

The Constraint on Rotation item in the Manipulation Handler currently allows the user to choose only ONE axis that can be rotated for an object.  

## Describe the solution you'd like

This should be changed so that the user can, for example, choose one axis that CAN'T be rotated for an object, allowing the other 2 axes to be rotated.

Here's a screenshot of what's allowed in MRTK:

![image](https://user-images.githubusercontent.com/60830074/74110021-aca7fc80-4b3d-11ea-8748-0384652db897.png)

However, other platforms (e.g., Oculus) allow more flexibility regarding which axes can be rotated:

![image](https://user-images.githubusercontent.com/60830074/74110068-2d66f880-4b3e-11ea-8421-2b040ee43c05.png)

This might also help with understanding how, in MRTK, to constrain, for example, the movement of drawers in a desk.  Oculus, for example, has a Directional Drive script:

![image](https://user-images.githubusercontent.com/60830074/74110376-da427500-4b40-11ea-97fc-bd184a0d8f22.png)

Thanks.

See also #5303 and #5147

**Comment by polar-kev** [comment]
Hi @VRacity, this issue has been fixed in the new constraint system.
See the constraint manager docs page: https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/constraint-manager?view=mrtkunity-2021-05
