### ISSUE TITLE
Add Oculus support via XR SDK

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#7272]
## Describe the problem

XR SDK supports multiple device platforms. MRTK 2.3 shipped with support for Windows Mixed Reality devices. We should add support for Oculus devices as well.

## Additional context

Follow-up issue to #7003

**Comment by davidkline-ms** [comment]
Moving to 2.5.0 as performance instrumentation and investigations have taken priority.

**Comment by wiwei** [comment]
@RogPodge closing this out - lemme know if there are things that this is still tracking (I know we still have tests and the teleport audio discussion pending, but I think that this is tangential to the XR SDK work which you already did)
