### ISSUE TITLE
ObjectManipulator should be more general to support non-hand inputs

### ISSUE THREAD

**Issue by adambehringer** [microsoft/MixedRealityToolkit-Unity#7274]
## Describe the problem

I would like to scale, rotation, and translate objects using inputs besides hands (such as a game pad). If the object has a ManipulationHandler, it would seem logical to use it to perform the transforms so that they will obey the active constraints, and also to trigger related events (OnManipulationStarted, ...).

Currently ManipulationHandler contains hard-coded logic specific to one and two-handed gestures and does not provide public methods for applying transforms through other inputs.

## Describe the solution you'd like

In my opinion ManipulationHandler should be more general, handling the application of transforms to an object along with the related constraints and side effects. The logic related to specific input controls (such as hands) should be modular and extensible, since transforms could be triggered by anything including game pads, voice commands, or other input methods.

## Describe alternatives you've considered

I have considered manipulating object transforms directly. Unfortunately, this bypasses the pre-existing constraints and events in the manipulation handler.

**Comment by adambehringer** [comment]
Note that this has accessibility implications as well.

**Comment by Alexees** [comment]
Related #7104

**Comment by polar-kev** [comment]
ObjectManipulator replaces ManipulationHandler as of 2.4.0 but this issue is still relevant.

**Comment by davidkline-ms** [comment]
This looks to be for non-VR / non-Hand controls (ex: xbox controller). Things to consider:

- Controls to use to engage a behavior (ex: Press A and use triggers to resize)
- How to target the specific manipulation handle (ex: upper right, front corner)?
- Accessibility considerations (ex: difficulty holding a control while adjusting another)

**Comment by adambehringer** [comment]
Generalizing the behavior of ObjectManipulator would aid the integration of controller such as the Xbox Controller. However, it would also be useful for things like speech commands ("scale up the blue box by 50%") or indirect controls such as a holographic control panel that manipulates 3D objects in the scene.

In both those cases, selecting specific handles is probably not part of the user flow. So I would suggest that manipulations should be accessible directly through an API, and not exclusively through the manipulations widgets. I'd still want the API calls to be limited by the manipulation constraints though. Part of the issue with bypassing ObjectManipulator is missing out on those constraints.

**Comment by RogPodge** [comment]
This is an excellent suggestion and we'll make sure to consider it for the next evolution of our MRTK UI tools!

**Comment by RogPodge** [comment]
This is officially a reality with MRTK v3. Look forward to using the object manipulator with controllers, eye gaze and more in the upcoming version.

Controller support still pending but the hooks for it are reality available.

**Comment by Zee2** [comment]
This is definitely a reality in MRTK3! ObjectManipulator works uniformly across all input modalities, including any custom interactors you might cook up yourself.
