### ISSUE TITLE
Left Eye Doesn't Fade In/Out in Scene Transition

### ISSUE THREAD

**Issue by VRacity** [microsoft/MixedRealityToolkit-Unity#7294]
## Describe the bug

With Scene Transition and Scene Manager turned on, and using a Manager scene, the fade in/fade out of the Scene Transition service only partially covers the left eye in my Samsung Odyssey (right eye works fine).

## To reproduce

1. Use the MRTK Scene System.
2. Turn on the Scene Transition service.
3. In the Scene Transition service Configuration Profile (in the Inspector) choose CameraFaderQuad as the Camera Fader Type.
4. Play the app; when transitioning between scenes, the left eye only partially fades out/in.

## Expected behavior

Total fade out/fade in.

## Screenshots
View in the left eye, during transition:
![image](https://user-images.githubusercontent.com/60830074/74284598-e5c8a400-4cd8-11ea-8b9c-f19e3bd32ee9.png)

https://1drv.ms/v/s!Akv2-8_1m_i2isdQaz2sdO7R9FYYVQ?e=lJoSkb

## Your setup (please complete the following information)

- Unity Version 2019+
- MRTK Version 2.2

## Target platform (please complete the following information)

- WMR immersive (Samsung Odyssey)

Note:  I'm not a coder, but I opened the CameraFaderQuad script and changed 1.01f to 1.21f, and that solved the problem.  The left eye now completely fades out and in.

![image](https://user-images.githubusercontent.com/60830074/74284682-1c062380-4cd9-11ea-910d-175cb70f52ed.png)

P.S.  The Progress Indicator settings never seem to do anything.
![image](https://user-images.githubusercontent.com/60830074/74284819-6a1b2700-4cd9-11ea-94c4-a69ccd8db6fb.png)

**Comment by cre8ivepark** [comment]
@Railboy Could you please take a look?
