### ISSUE TITLE
Share MRTK-specific .gitignore

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7298]
## Describe the bug
MRTK requires that some files like DotNetAdapter.csproj at `/Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/DotNetAdapter/DotNetAdapter.csproj` should be included in git. These files are ignored by the recommended .gitignore file for Unity.

Provide a recommended .gitignore to use in MRTK projects. [Can use this .gitignore as a starting point](https://gist.github.com/julenka/b65ece128107ae7cbace92c70c285c8c).

**Comment by xwipeoutx** [comment]
@julenka - I've just run into this, I don't really get which files need ignoring and not, so have simply stolen the bottom parts of that gist you shared - which seems fine (for now at least), so thanks for sharing it 🙂

**Comment by wiwei** [comment]
I'm writing up a doc page for guidance around consuming the MRTK in larger projects, since both the .gitignore and other aspects will come up frequently.

**Comment by davidkline-ms** [comment]
Closing per #7725
