### ISSUE TITLE
Unity hangs after switching to UWP in 2019.3

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#7299]
## Describe the bug
Unity hangs on the selawk.ttf file after switching to UWP on 2019.3 on the latest 2.3 test packages.  In order to resolve the issue, you need to end the task in the task manager.

## To reproduce

1. Open Unity 2019.3.0f6
2. Import the latest 2.3 test packages
3. Click apply when the project configurator pops up
4. Navigate to the Mixed Reality Toolkit menu -> Add to Scene and Configure
5. Press play in your scene with the MixedRealityToolkit objects, make sure the diagnostics panel shows up in play mode.
6. Exit play mode
7. Switch the platform to UWP
8. You should see unity hang on the selawk.ttf

![image](https://user-images.githubusercontent.com/53493796/74289190-3a711c80-4ce3-11ea-938b-f28558323195.png)

## Your setup (please complete the following information)

- Unity Version: 2019.3.0f6
- MRTK Version v2.3 prerelease

**Comment by CDiaz-MS** [comment]
Destroying GameObjects immediately is not permitted during physics trigger/contact, animation event callbacks or OnValidate. You must use Destroy instead.
UnityEditor.SceneManagement.EditorSceneManager:ClosePreviewScene_Injected(Scene&)
UnityEditor.SceneManagement.EditorSceneManager:ClosePreviewScene(Scene)
UnityEditor.PreviewScene:Dispose()
UnityEditor.PreviewRenderUtility:Cleanup()
UnityEditor.MaterialEditor:OnDisable()
UnityEngine.Object:DestroyImmediate(Object, Boolean)
UnityEngine.Object:DestroyImmediate(Object)
UnityEditor.AssetPreviewUpdater:CreatePreviewForAsset(Object, Object[], String)
UnityEditor.AssetDatabase:Refresh(ImportAssetOptions)
UnityEditor.AssetDatabase:Refresh()
Microsoft.MixedReality.Toolkit.Utilities.Editor.ProjectPreferences:get_Instance() (at Assets\MixedRealityToolkit\Utilities\Editor\Preferences\ProjectPreferences.cs:69)
Microsoft.MixedReality.Toolkit.Utilities.Editor.ProjectPreferences:Get(String, Boolean) (at Assets\MixedRealityToolkit\Utilities\Editor\Preferences\ProjectPreferences.cs:119)
Microsoft.MixedReality.Toolkit.Editor.MixedRealityProjectPreferences:get_AutoEnableUWPCapabilities() (at Assets\MixedRealityToolkit\Utilities\Editor\Preferences\MixedRealityProjectPreferences.cs:86)
Microsoft.MixedReality.Toolkit.Utilities.Editor.UWPCapabilityUtility:RequireCapability(WSACapability, Type) (at Assets\MixedRealityToolkit\Utilities\UWPCapabilityUtility.cs:27)
Microsoft.MixedReality.Toolkit.Windows.Input.WindowsSpeechInputProvider:Initialize() (at Assets\MixedRealityToolkit.Providers\WindowsVoiceInput\WindowsSpeechInputProvider.cs:123)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProvider(IMixedRealityInputDeviceManager) (at Assets\MixedRealityToolkit\Services\BaseDataProviderAccessCoreSystem.cs:243)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProviderInternal(Boolean, Type, SupportedPlatforms, Object[]) (at Assets\MixedRealityToolkit\Services\BaseDataProviderAccessCoreSystem.cs:226)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProvider(Type, SupportedPlatforms, Object[]) (at Assets\MixedRealityToolkit\Services\BaseDataProviderAccessCoreSystem.cs:151)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:CreateDataProviders() (at Assets\MixedRealityToolkit.Services\InputSystem\MixedRealityInputSystem.cs:265)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Initialize() (at Assets\MixedRealityToolkit.Services\InputSystem\MixedRealityInputSystem.cs:232)
Microsoft.MixedReality.Toolkit.<>c:<InitializeAllServices>b__60_0(IMixedRealityService) (at Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:923)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1) (at Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:1019)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeAllServices() (at Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:923)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:468)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeInstance() (at Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:582)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean) (at Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:720)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:OnValidate() (at Assets\MixedRealityToolkit\Services\MixedRealityToolkit.cs:1456)

**Comment by thalbern** [comment]
![image](https://user-images.githubusercontent.com/36998103/74362725-1be15300-4dc1-11ea-9f67-734dbcc404d5.png)
 having this as well - it's in this state since 10 minutes now

**Comment by wiwei** [comment]
Closing this out since we ended up fixing this recently (https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7833)
