### ISSUE TITLE
Using Nuget to get MRTK 2.2.0 dosn't work with Unity 2019.2

### ISSUE THREAD

**Issue by Thomas-6freedom** [microsoft/MixedRealityToolkit-Unity#7303]
## Describe the bug

There are some issues when pressing PLAY on an empty project with MRTK 2.2.0 downloaded from Nuget when using Unity 2019.2

## To reproduce

1. New Unity 2019.2 project
2. Download NuGetForUnity.2.0.0.unitypackage
3. Import it
4. Nuget => Add Package => Microsoft.MixedReality.Toolkit.Foundation.2.2.0
5. Wait to download and compile
6. Press Play
7. Some error in the console

## Expected behavior

No error

## Screenshots

![2020-02-12 15_50_55-](https://user-images.githubusercontent.com/49686866/74346377-cc465b80-4daf-11ea-986a-3024cbf92b1b.png)

## Your setup (please complete the following information)

- Unity Version 2019.2.19f1
- MRTK Version 2.2.0

## Target platform (please complete the following information)

In Editor

Maybe it's related to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7150

**Comment by davidkline-ms** [comment]
@Thomas-6freedom, we currently build our NuGet packages for Unity 2018.4. #7150 is our issue tracking adding Unity 2019,3 NuGet packages.
