### ISSUE TITLE
Allow ManipulationHandler to use rigidbody.MovePosition/MoveRotation

### ISSUE THREAD

**Issue by ar51-nadav** [microsoft/MixedRealityToolkit-Unity#7315]
## Describe the problem

The current way ManipulationHandler works changes the object's rigidbody to `isKinematic = true` and directly moves its transform position and rotation. This can be problematic in situations where manipulated objects are supposed to stay inside the room, since players can accidentally move things outside of the spatial mapping colliders.
This is especially important with objects that are effected by gravity since if a player moves something below the floor, it will start falling forever.

## Describe the solution you'd like

I would like an option in the ManipulationHandler inspector to allow moving the object via its rigidbody. When this option is tagged, the object will not be set as `isKinematic = true` but instead have `useGravity=false`. Additionally, if this setting is checked, the handler will change the position and rotation via `rigidbody.MovePosition` and `rigidbody.MoveRotation`.

## Describe alternatives you've considered

I've tried adding a component that registers to the OnManipulationStarted/Ended events and changes the isKinematic and useGravity properties itself. It than listens to OnCollisionEnter and if it collides with the Spatial Awarness layer it tries to move the object away from the contact point. The problem is that this approach causes the object to vibrate when touching a wall, and it also doesn't fully solve the problem since if the user keeps pushing the object, it will pop out of the other side.

**Comment by wiwei** [comment]
@thalbern @MenelvagorMilsom do you guys have any thoughts on this request?

**Comment by MenelvagorMilsom** [comment]
@wiwei  I think we're doing something similar to this in `ObjectManipulator`. See docs:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_ObjectManipulator.html#physics-and-collisions

**Comment by MenelvagorMilsom** [comment]
There's also an _ObjectManipulatorExamplePhysics_ example scene with a bunch of rigidbody objects inside a room.

**Comment by MenelvagorMilsom** [comment]
I found `rigidbody.MovePosition` and `rigidbody.MoveRotation` didn't work incredibly well with collisions with other rigidbodys. Instead, I altered the velocity directly, allowing for proper collision responses.

**Comment by MenelvagorMilsom** [comment]
Also, if you want to be sure that an object doesn't pass through the walls of a room, make sure to use `CollisionDetectionMode.ContinuousDynamic` on the rigidbody. It's not set up that way in the example scene yet, we should probably make that change.

**Comment by ar51-nadav** [comment]
Thank you for the response. I'm a little confused since the doc page you linked seem to be an updated version of the ManipulationHandler but I can't find a link for it in the Guides list. Is it a new planned feature? In which version is this expected to be released?

**Comment by MenelvagorMilsom** [comment]
> Thank you for the response. I'm a little confused since the doc page you linked seem to be an updated version of the ManipulationHandler but I can't find a link for it in the Guides list. Is it a new planned feature? In which version is this expected to be released?

It's an [experimental feature](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/ExperimentalFeatures.html). We plan to graduate from experimental next release. This will come with updates to docs and example scenes.

Even though it's currently experimental, it has some improved functionality and it's unlikely to change before the next release, so feel free to start making use of this feature before the next release. You can migrate your scenes very easily using the [migration window](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/MigrationWindow.html).

**Comment by polar-kev** [comment]
The ObjectManipulator script which replaces ManipulationHandler allows for physics and collisions with rigid bodies, and will allow you to achieve the scenarios you mentioned.

Here's a link to the docs:
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/object-manipulator?view=mrtkunity-2021-05#physics-and-collisions
