### ISSUE TITLE
Upgraded 2.2 to 2.3 and getting run time errors for HandInteractionExamples

### ISSUE THREAD

**Issue by wxydesign** [microsoft/MixedRealityToolkit-Unity#7317]
## Describe the bug

Upgraded existing "vanilla" project from 2.2 to 2.3. I opened the HandInteractionExamples from the demo folder, hit play and got the below error messages.

## To reproduce

1. Have previous project using MRTK 2.2 with HandInteractionExample open
2. Follow instructions to upgrade to MRTK 2.3
3. Open HandInteractionExample and press play
4. Scene plays fine but getting errors during runtime

## Expected behavior

Scene plays with no errors

## Screenshots
![image](https://user-images.githubusercontent.com/7551438/74486209-4db1f280-4e71-11ea-98a9-a4ab18aeb513.png)

## Your setup (please complete the following information)

- Unity Version 2019.2.19f1
- MRTK Version 2.3

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

I initially did not delete all the MRTK files within the Asset folder which caused other errors. I eventually deleted everything including the examples

**Comment by vaoliva** [comment]
Could you please give more details about the steps you followed on 

> 2. Follow instructions to upgrade to MRTK 2.3

**Comment by wxydesign** [comment]
Hi there,

I was following the instructions on the GitHub release notes. FYI, my internal employee email is willyang@microsoft.com.

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/ReleaseNotes.html

Will

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
