### ISSUE TITLE
Dynamic Near Menu that tracks controllers too

### ISSUE THREAD

**Issue by DanCRichards** [microsoft/MixedRealityToolkit-Unity#7320]
## Describe the problem

The current near menu is a great tool that allows Hololens and Headset users have a menu which follows them, or can be pinned to a specific location with sizing adjustments through a manipulation handler. 

The Open Menu is targeted from what I feel towards Hololens users. (As it should be). Further enhancements can be made. 

## Describe the solution you'd like

A menu that on startup checks for controllers, if it detects a controller the menu attaches to the controller, if the controller is disconnected the Near Menu then attaches to the other controller if found or goes back to head tracking mode. 

## Describe alternatives you've considered

Ultimately creating a new type of menu would be more appropriate, I would suggest calling this a Control Panel or User Panel (?) as ultimately this would be a personal menu to the user. The project I am working on we currently implement this through adjustments to the near menu script. I just want to see if other people are interested in this functionality and we can contribute to this repo.

**Comment by polar-kev** [comment]
Thanks for this submission. Please submit a PR for this and we can explore your implementation.
