### ISSUE TITLE
Programatically modifying Bounding Box material or prefabs properties outside of Unity play mode will add unecessary run time components

### ISSUE THREAD

**Issue by Pycorax** [microsoft/MixedRealityToolkit-Unity#7328]
## Describe the bug
I'm currently writing a Unity Editor menu item that adds the `Bounding Box`,  `Manipulation Handler` and `Audio Source` programmatically outside of play mode. It would then set up the materials defined in the [documentation](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_BoundingBox.html#handle-styles) to create the HoloLens 2 style bounding boxes.

However, as the assignment of the materials and prefabs into the property also executes `CreateRig()`, it generates extra runtime-only components for the Bounding Box.

## To reproduce

1. Access and modify either of the following `Bounding Box` properties outside of play mode in the Unity Editor via an Editor script:
    - `BoxMaterial`
    - `BoxGrabbedMaterial`
    - `RotationHandleSlatePrefab`
    - `ScaleHandlePrefab`
    - `ScaleHandleSlatePrefab`
2. Observe the additional components added to the object

## Expected behavior

Modification of the material and prefab properties of the `Bounding Box` outside of play mode should not create the runtime-only components of the `Bounding Box`.

## Your setup

- Unity Version 2019.1.14f1
- MRTK Version v2.2.0

## Target platform

- HoloLens
- HoloLens 2
- AR Foundation

## Additional context

Perhaps, there should be a check for if the Unity Editor is in play mode prior to executing `CreateRig()` when changes are made to the `Bounding Box` properties

**Comment by Pycorax** [comment]
To add on, I notice that as a result of executing `CreateRig()` upon the change of each property, if someone is changing multiple properties, it results in multiple `CreateRig()` and `DeleteRig()` calls being executed within the same frame. Perhaps, a dirty check could be used and the resetting of the rig would be done in a `LateUpdate()` of some sort?

**Comment by thalbern** [comment]
thanks for reporting this! You're right, we shouldn't create the rig in edit mode. Also I'm linking https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6260 here as this should be addressing your other issue

**Comment by Pycorax** [comment]
No problem, glad to see that is is already being worked on :)
