### ISSUE TITLE
Screenshot for Getting Started for 2.3.0 out of date?

### ISSUE THREAD

**Issue by genereddick** [microsoft/MixedRealityToolkit-Unity#7331]
The screenshot for the MRTK Project Configurator on this page:
https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.3.0/Documentation/GettingStartedWithTheMRTK.html

Does not match what appears when I install into a new Unity 2019.3.1f1 project:
![image](https://user-images.githubusercontent.com/1033793/74571572-e2c8f000-4f32-11ea-9932-49c9d8790403.png)

Perhaps not too important, but the checkbox in the position for
Enable VR Supported => Enable Legacy XR

With this text:
    Enable XR Settings for your current platform (enabling the XR checkbox).

Creates some confusion and uncertainty -- are we supposed to enable Legacy XR, aren't we updating to the new XR system?

**Comment by davidkline-ms** [comment]
Good catch @genereddick. It looks like we forgot to create images for the differences between running the Configurator on Unity 2018.4 and 2019.3
