### ISSUE TITLE
mircast problem

### ISSUE THREAD

**Issue by oneSitDown** [microsoft/MixedRealityToolkit-Unity#7335]
When I open the projection of mircast on Hololens2 for real-time preview on the laptop, when I open the camera function in my program, the mircast connection will be interrupted, and the real-time preview cannot be performed. What is wrong with this? I haven't encountered this problem on H1.

**Comment by Troy-Ferrell** [comment]
Hi @oneSitDown ! Thanks for posting but this repo/site is for issues related to MRTK. 

For hololens 2 issues, please see
https://support.microsoft.com/en-us/hub/4338666/hololens-help

Also please look at the Hololens docs
https://docs.microsoft.com/en-us/hololens/holographic-photos-and-videos
