### ISSUE TITLE
Lighting Scene is not taking effect in Scene system

### ISSUE THREAD

**Issue by waynebaby** [microsoft/MixedRealityToolkit-Unity#7337]
## Describe the bug

Lighting Scene is not taking effect in Scene system

## To reproduce

Create 2 lighting scene with SunLight and moonlight direction light  (different color and intense)

Open Example Hub  example scene.

Enable the lighting scene.

add SunLight And MoonLight Scene into the array 

Set sunlight as default scene

start with the Example Hub Scene

sunlight scene is loaded and the direction light in the scene is disable. no light in the scene
## Expected behavior

sunlight scene is loaded and the direction light in the scene is enabled

## Your setup (please complete the following information)

- Unity Version 2018.4.17f1
- MRTK Version 2.3

## Target platform (please complete the following information)

Unity Editor

**Comment by keveleigh** [comment]
@Railboy, any ideas?

**Comment by Railboy** [comment]
@waynebaby Question, before loading the sunlight scene, did you update the cached lighting settings in the scene system profile?

**Comment by c11epm** [comment]
Hi I seem to experience this problem as well. It works fine with a lighting scene in play mode in the editor, the lighting scene gets loaded and works fine. But when I build and deploy to Hololens 2(via the build window from MRTK (build all and install)) the lighting doesn't work and the content scenes are not lit by anything. For now I have disabled the lighting scene and just added a Directional Light to the Manager scene and it seems to work fine.

**Comment by LazyWood** [comment]
I had the same problem，Unity only direct light has this problem，other light can use.
Unity 2021.3.4，MRTK 2.8.2
