### ISSUE TITLE
Landing page of docs has some absolute links that will redirect users to default docs instead of version specific docs

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#7338]
## Describe the issue
Currently there's 4 links on our landing page (README.md) that point to the direct html links of our mrtk_development docs. These links will throw users out of the version specific documentation and might lead to guides that are not applicable to their version.

## Feature area
Landing page links

## Existing doc link
https://microsoft.github.io/MixedRealityToolkit-Unity/README.html

## Additional context
We should never navigate a user unknowingly out of the version specific docs. 

There's another problem @cre8ivepark brought up with this: We don't have any direct links to our doc portal from the .md preview if we remove those direct links - so maybe we can add some script before triggering docfx that patches up those direct links (to relative ones / xrefs) before throwing them into the docfx conversion.

**Comment by thalbern** [comment]
Solution suggested by Alex Turner / David Fields: store version selected by dropdown in cookie and redirect user to correct version in case they're thrown back into dev docs by accident. Javascript in web folder of project root could be used for that.

**Comment by wiwei** [comment]
I *think* that with the changes that @thalbern just made here (https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8202)
