### ISSUE TITLE
PrefabSpawnManager is not working without sharingstage

### ISSUE THREAD

**Issue by davesmits** [Microsoft/MixedRealityToolkit-Unity#734]
we are working on a new app that has to work with a multi device but also standalone. we tried to use the PrefabSpawnManager but without the SharingStage connected ends up in being not functional. Does someone has good alternative? if no alternative would be interested in a updated version that works also without the sharing stage active?

**Comment by StephenHodgson** [comment]
You should def use the sharing stage.
