### ISSUE TITLE
Windows XR Plugin 2.0.4 preview.3 breaks tracking on HoloLens 2

### ISSUE THREAD

**Issue by KlausEngel** [microsoft/MixedRealityToolkit-Unity#7340]
Windows XR Plugin 2.0.4 preview.3 breaks tracking on HoloLens2 in Unity 2019.31.1f1. When upgrading from Windows XR Plugin 2.0.3 to 2.0.4 preview.3, the tracking of the head and hands does not work properly anymore, i.e. the content, including tracked hands shifts away from the user. 

1. Install Unity 2019.3 1f1
2. Create new project and install MRTK 2.3 following these instructions: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html
3. Follow these instructions for using the XR SDK: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html
4. Update Windows XR Plugin in Package Manager to 2.0.4 preview 3 as advised in MRTK 2.3 release notes
5. Set MRTK profile to DefaultXRSDKConfigurationProfile 
6. Build project for Visual Studio 2019
7. Use Visual Studio to deploy project to HoloLens 2
8. Observe that the content and hands shift when moving the head, i.e. tracking does not work properly

Expected behavior: Head tracking works properly and content does not shift.

Setup
- Unity 2019.3 1f1
- MRTK Version 2.3
- Windows XR Plugin 2.0.4 preview 3

Target platform:
- HoloLens 2

**Comment by keveleigh** [comment]
This is currently a known issue with that version of the plug-in. I'm working with Unity to get a fix in for the next release.

In the meantime as a workaround at app launch, covering the HoloLens sensors with your hands to force tracking loss and uncovering them should help you regain positional tracking.

**Comment by KlausEngel** [comment]
Yes, the workaround with covering the sensors works for now. Thanks!

**Comment by wiwei** [comment]
Thanks @keveleigh. Closing this out for now, since this is an issue with the XR Unity plugin.

**Comment by sostel** [comment]
Has this been fixed? When is a fix to be expected?

**Comment by ericalbers** [comment]
Seriously, this needs a fix, basically cannot develop for HL2 in unity

**Comment by keveleigh** [comment]
This was fixed a while ago. The latest several releases should work as expected.
Note that if you're still seeing the camera not track with your headset, you might need a [Tracked Pose Driver](https://docs.unity3d.com/2018.3/Documentation/ScriptReference/SpatialTracking.TrackedPoseDriver.html) on your scene camera. This gets added at runtime by MRTK if you're [using the XR SDK profile](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html#required-in-mrtk).
