### ISSUE TITLE
Cannot Access MRTK site

### ISSUE THREAD

**Issue by maristhek** [microsoft/MixedRealityToolkit-Unity#7341]
Accessing the MRTK site opens the Profile page with no way to get to the site.  Only option is to update the profile or log-out.

Please advise how to continue.

**Comment by keveleigh** [comment]
Which site are you referring to? Is there a specific link you're clicking to get there?

**Comment by maristhek** [comment]
https://mixedreality.microsoftcrmportals.com/en-US/

**Comment by maristhek** [comment]
It also happens with external Microsoft Account login.

**Comment by keveleigh** [comment]
I'm not sure exactly what that link is for. If you're looking for the MRTK docs, they can be found at https://microsoft.github.io/MixedRealityToolkit-Unity/README.html, with no login required.

**Comment by maristhek** [comment]
Tnx
