### ISSUE TITLE
MicStreamDemo.cs demo example doesn't exist

### ISSUE THREAD

**Issue by Porupu** [microsoft/MixedRealityToolkit-Unity#7343]
Hi, 
looking through the front page of https://github.com/microsoft/MixedRealityToolkit it mentiones an example demo on this repo https://github.com/microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Tests/Scripts/MicStreamDemo.cs but that page doesn't exist; is the demo/scripts still available?

**Comment by keveleigh** [comment]
That demo can be found in the old HoloToolkit branches: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/htk_release/Assets/HoloToolkit-Examples/Input/Scripts/MicStreamDemo.cs

**Comment by wiwei** [comment]
I just updated the README on the other site and fixed this up there, closing this out for now.
