### ISSUE TITLE
Blur and ripple at edges on head movement

### ISSUE THREAD

**Issue by anilozfuttu** [microsoft/MixedRealityToolkit-Unity#7344]
## Describe the bug
I have HP Mixed Reality Headset and trying to develop an application using  Unity Project version 2019.3 and MRTK . There is a blur and ripple on edges when camera is rotating. Problem only occur on Unity projects

## To reproduce

1. Create Unity Project v2019.3.06f
2. Install MRKT packages
3. Mixed Reality Toolkit -> Add to Scene and Configure
4. Play

## Expected behavior
Default hub scene of Windows does not have these problems. It only occur on unity project and MRKT examples
## Your setup (please complete the following information)

- Unity Version [2019.3.06f]
- MRTK Version [v2.3.0]

## Target platform (please complete the following information)
- WMR immersive (HP Mixed Reality Headset)

**Comment by Alexees** [comment]
I tried quite a lot to get some attention on bugs MR Portal related, but from my experience it's not being worked on anymore. If you use SteamVR and run the editor with OpenVR aktive, you'll get the same experience but with proper rendering

**Comment by keveleigh** [comment]
Do you have depth buffer sharing turned on under Edit > Project Settings > Player > XR Settings?

**Comment by anilozfuttu** [comment]
@keveleigh Yes it is turned on
XR settings are;
![settings](https://user-images.githubusercontent.com/17238960/74932749-9c243b80-53f3-11ea-8a8c-bd15501b07b7.PNG)

**Comment by keveleigh** [comment]
Can you test without depth buffer sharing enabled and see if it still repros? We've had some issues in the past around it causing visual issues like this. Also, which version of Windows are you running?

**Comment by anilozfuttu** [comment]
Problem solved after disabling Depth Buffer Sharing. Thank you keveleigh

**Comment by keveleigh** [comment]
If possible, can you file a Feedback Hub report while running with the depth buffer on? We should get this reported on our side so we can investigate the issue! Running with the depth buffer shouldn't cause rendering issues.
