### ISSUE TITLE
Japanese Keyboard 日本語のキーボード入力です。

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/MixedRealityToolkit-Unity#735]
皆様、IME(InputMethodEnvironment)なしに、基本的なひらがなとカタカナ文字の入力ができるHoloLens用キーボードを作りました。ひらがな・カタカナと濁音・半濁音を支援します。濁音・半濁音は一般的な入力方法とは違ってトグル方法で作りました。（やはり、IMEの支援なしで）便利な入力方法ではないですが、日本語の入力が必要する時に役立ちます。
日本の開発者コミュニティからのフィードバックで、50音キーボードレイアウトタイプを追加しました。距離に応じていくつかのキーにフォーカスバグがまだあります。

これは、キーボードをテストすることができるUnityのSceneです。Text fieldをエアータップするとキーボードが表現されます。
https://github.com/cre8ivepark/HoloToolkit-Unity/blob/Keyboard_Japanese/Assets/HoloToolkit-Tests/Input/Scenes/KeyboardTestJapanese.unity

このフォルダの中で、Keyboard_Japanese_50on.prefabが日本語のキーボードです。
https://github.com/cre8ivepark/HoloToolkit-Unity/tree/Keyboard_Japanese/Assets/HoloToolkit/UI/Prefabs

Demo Video: https://twitter.com/cre8ivepark/status/878032202600136704

[備考]
HoloLensデフォルトで使われているキーボードを変更するためのものではありません。

![2017-06-21 16_06_15-unity 5 6 0f3 personal 64bit - keyboardtest unity - holotoolkit-unity - pc ma](https://user-images.githubusercontent.com/13754172/27410530-fa75c4d0-569c-11e7-85a7-4295902510a3.png)

Hi everyone, I am sharing very basic level of Japanese keyboard which supports Hiragana input with dakuon/hantakuon support (without IME). Since this is based on [Patrick Sebring's EN keyboard](https://github.com/paseb/HoloToolkit-Unity/tree/master/Assets/HoloToolkit/UI/Test), it supports English and Symbol mode too. Since this is temporary basic level keyboard, I am sharing through my forked repo.

Thanks!
Yoon

**Comment by waynebaby** [comment]
Cool!

It is so hard to create so many different keyboard with different cultures. The Chinese Chars input seems impossible. 

My choice is create a XAML view and use the built in Holo-Keyboard (which is not ready for Asia IME in HoloLens 14393,  T_T).

We might need deeper IME service support than simple buttons

**Comment by cre8ivepark** [comment]
@waynebaby Thanks! Yes eventually we need full IME support for Romaji input and kanji/Chinese character conversion. I hope this could be used for the short basic input situations.

**Comment by cre8ivepark** [comment]
すこしキーボードが高くなりますが(height),50音キーボードのレイアウトでテストしています。
![2017-06-22 11_31_56-unity 5 6 0f3 personal 64bit - keyboardtest unity - holotoolkit-unity - pc ma](https://user-images.githubusercontent.com/13754172/27450052-4b83064c-573f-11e7-8f7e-1d2d47a3bcfc.png)

**Comment by cre8ivepark** [comment]
50音キーボードレイアウトタイプを追加。カタカナも追加しました。距離に応じていくつかのキーにフォーカスバグがまだあります。 
https://github.com/cre8ivepark/HoloToolkit-Unity/tree/master/Assets/HoloToolkit/UI/Test

![20170622_153529_hololens](https://user-images.githubusercontent.com/13754172/27460132-d38a2ba2-5766-11e7-986a-20257ce7f5f5.jpg)
![20170622_153519_hololens](https://user-images.githubusercontent.com/13754172/27460138-d980c3a4-5766-11e7-8395-f2c37d0235f5.jpg)

**Comment by cre8ivepark** [comment]
Demo Video: https://twitter.com/cre8ivepark/status/878032202600136704
