### ISSUE TITLE
Command line Build Improvement

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#7351]
## Describe the problem

when using the command line build for CI, we ended up havoing our own function to add some missing parameters, current code is also hardly extensible due to private non virutal implementation.

1/ needed extra parameters:
1a- being able to configure the version number
 `"-appVersion" : PlayerSettings.WSA.packageVersion = new Version(arguments[++i]);`

1b- for unity 2018.4 gaze capability has to be controlled outside project settings, so enabling it from CLI: 
`"-gazeInput": buildInfo.GazeInputCapabilityEnabled = true;`

 1c- there is only the targetUwpSdk accesible from command line currently, so adding:
 `"-minSdkVersion": EditorUserBuildSettings.wsaMinUWPSDK = arguments[++i];`

2/ one appx for multiple platforms:
this ended up being a bit more tricky here:
2a: first add a "-buildPlatform" instead of "-x86", "-arm"... to be able to specify "x86|arm"
`buildInfo.BuildPlatform = arguments[++i];`

2b: when calling `msbuild.exe` in `BuildAppxAsync`
split the platform string and:
 for each independant platform call a build process without building the package (by adding `/p:GenerateAppxPackageOnBuild=false` ) 
then call an extra `msbuild.exe` with `/p:AppxBundle=Always /p:AppxBundlePlatforms="x86|arm" /p:UseSubFolderForOutputDirDuringMultiPlatformBuild=false` (replace `x86|arm` with real parameters from commandline, this is just for the example

note that it will generate an .appxbundle instead of a .appx

3/ related to 2, when i wanted to add this extra capability, i ended up copying the entire functions from UwpPlayerBuildTools, as most of them where private.
so making this class extensible with protected virtual functions would be a good idea.

**Comment by wiwei** [comment]
@gilbdev can you share out a commit for your changes? It'll probably be easier to discuss changes we could take given that you already have some deltas to talk about

**Comment by gilbdev** [comment]
i created this issue following up a discussion on slack.
i didn't really modified the initial mrtk files but created a new BuildTools.cs in our framework.
sorry for not having the time to do proper PR ..

here is our file  (most of function are jsut copied past from mrtk,as i said they are private non virtual so i add to bring all of them in our file)
https://gist.github.com/gilbdev/28c881cb29eeb57c6fd385578b82afae
