### ISSUE TITLE
Vuforia Image Target

### ISSUE THREAD

**Issue by Jun-Hyung348** [microsoft/MixedRealityToolkit-Unity#7353]
## Describe the issue
I use MRTK 2.2.0 and Vuforia engine 8.6.7. There is an error
Trackable I-found NO_POSE -- UNKNOWN
UnityEngine.Debug:LogFormat(String, Object[])
DefaultTrackableEventHandler:OnTrackableStatusChanged(StatusChangeResult) (at Assets/Vuforia/Scripts/DefaultTrackableEventHandler.cs:67)
Vuforia.TrackableBehaviour:RegisterOnTrackableStatusChanged(Action`1)
DefaultTrackableEventHandler:Start() (at Assets/Vuforia/Scripts/DefaultTrackableEventHandler.cs:50)
What is this? 
On Default Trackable Event Handler, Event when target is found is empty.

## Feature area
What's incorrect? What's missing?

## Existing doc link
If this is about something in an existing document, please provide link

## Additional context
Can I use MRTK and Vuforia engine at the same time? I wonder if I use MRTK, I couldn't use vuforia.

**Comment by CDiaz-MS** [comment]
There is no official MRTK documentation for Vuforia support but here is a link to [Microsoft Vuforia Unity documentation](https://docs.microsoft.com/en-us/windows/mixed-reality/vuforia-development-overview).
