### ISSUE TITLE
Add MoveAxisConstraint and ScaleAxisConstraint to ManipulationHandler

### ISSUE THREAD

**Issue by Yolo-Jerome** [microsoft/MixedRealityToolkit-Unity#7355]
## Describe the problem

For full flexibility I would like to be able to additionally constrain the movement and scaling to one or more axes.
Currently there only exists the `FixedDistanceConstraint` which doesn't allow to do so.

## Describe the solution you'd like

The `ManipulationHandler` should additionally also have a `MoveAxisConstraint` and there also should be a `ScaleAxisConstraint` component attached so I can additionally constraint the movement on certain axes.

**Comment by polar-kev** [comment]
Hi @Yolo-Jerome, move, rotation and scale constraints are handled by the Constraint manager that can be used with the ObjectManipulator script that replaced ManipulationHandler.
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/constraint-manager?view=mrtkunity-2021-05

![image](https://user-images.githubusercontent.com/30964480/125334911-c33d1f00-e300-11eb-96c3-72934342cf13.png)
