### ISSUE TITLE
Missing images in Solvers documentation 

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#7361]
## Describe the issue
There are empty images in the solvers documentation found here: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_Solver.html

![image](https://user-images.githubusercontent.com/53493796/74870892-5db55080-530f-11ea-96cc-97330c1eb0a1.png)

**Comment by Troy-Ferrell** [comment]
Interesting...looks like it works in 2.3 but somehow broken in MRTK_dev?

https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.3.0/Documentation/README_Solver.html

**Comment by wiwei** [comment]
The name of the png I think got changed up. There's actually a number of broken links images here even within our own docs. 

We should fix this once and for all by adding a validation step for this so that we don't have to manually do this.

**Comment by wiwei** [comment]
Note that we're also not consistent with how we use <img> vs ()[].

I tried using ()[] hoping that docfx would validate it but it unfortunately didn't quite work, so I think we'll have to roll our own.

**Comment by wiwei** [comment]
Another possibility is to push something to docfx but I'm not sure what the turnaround is on a change there making it to their latest nuget feed, especially in light of the issue here: https://github.com/dotnet/docfx/issues/5536

**Comment by wiwei** [comment]
Wait, I'm wrong.

**Comment by wiwei** [comment]
It's a case sensitive/insensitive thing. It strikes again.
