### ISSUE TITLE
Hand Menu 2.4 updates

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#7365]
This issue tracks revisions and improvements to the hand menu that are happening in the 2.4 timeframe.

**Comment by wiwei** [comment]
@julenka @cre8ivepark I'm filing this in order to track the desire to rev the hand menu in 2.4. I don't have line of sight on the specific changes (or if there are specific changes we want to call out at this moment) - if you guys have them, could you add them to the issue (i.e. edit the issue description) or ACK that specifics will be added later?

**Comment by keveleigh** [comment]
Not sure if there's room in this iteration for extending this to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7320, but wanted to make the connection
