### ISSUE TITLE
NotImplementedException when running HandInteractionExample scene in editor

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7366]
I'm getting an exception when running the HandInteractionExample scene. The error doesn't seem to impact behavior, but I believe we want to have no errors / exceptions thrown when running a scene.

Editor: Unity 2018.4.14f1
Build Settings Platform: UWP

To repro, open the handinteractionexample scene and hit play

```
NotImplementedException: The method or operation is not implemented.
System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
WinRT.Mono+ThreadContext..cctor () (at <da2d3aabe3524d9fba5ebaabd307ffc7>:0)
Rethrow as TypeInitializationException: The type initializer for 'ThreadContext' threw an exception.
WinRT.Delegate+InitialReference..ctor (System.Guid iid, System.IntPtr invoke, System.Object invoker) (at <da2d3aabe3524d9fba5ebaabd307ffc7>:0)
WinRT.Interop.DelegateProperty`1[T].set_Value (T value) (at <da2d3aabe3524d9fba5ebaabd307ffc7>:0)
WinRT.Interop.IAsyncOperation.set_Completed (WinRT.Interop.IAsyncOperation+CompletedHandler value) (at <da2d3aabe3524d9fba5ebaabd307ffc7>:0)
WinRT.Interop._IAsyncOperation`2[TTask,TResult].AsTask (System.Threading.CancellationToken cancellationToken) (at <da2d3aabe3524d9fba5ebaabd307ffc7>:0)
WinRT.Interop._IAsyncOperation`2[TTask,TResult].AsTask () (at <da2d3aabe3524d9fba5ebaabd307ffc7>:0)
Microsoft.Windows.Perception.People.IEyesPoseStatics.RequestAccessAsync () (at <da2d3aabe3524d9fba5ebaabd307ffc7>:0)
Microsoft.Windows.Perception.People.EyesPose.RequestAccessAsync () (at <da2d3aabe3524d9fba5ebaabd307ffc7>:0)
Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityEyeGazeDataProvider+<AskForETPermission>d__30.MoveNext () (at Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XR2018/WindowsMixedRealityEyeGazeDataProvider.cs:186)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:155)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:105)
```

**Comment by keveleigh** [comment]
Looks like this is from DotNetWinRT. Are you remoting when this happens?

**Comment by julenka** [comment]
No I was not running Unity Remoting.

**Comment by bassempro** [comment]
I habe the same issue Editor: Unity 2018.4.14f1 , MRTK 2.3 
NotImplementedException: The method or operation is not implemented.
System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
WinRT.Mono+ThreadContext..cctor () (at <ed1f6dedc2514473bacf0986f8922b29>:0)
Rethrow as TypeInitializationException: The type initializer for 'ThreadContext' threw an exception.
WinRT.Delegate+InitialReference..ctor (System.Guid iid, System.IntPtr invoke, System.Object invoker) (at <ed1f6dedc2514473bacf0986f8922b29>:0)
WinRT.Interop.DelegateProperty`1[T].set_Value (T value) (at <ed1f6dedc2514473bacf0986f8922b29>:0)
WinRT.Interop.IAsyncOperation.set_Completed (WinRT.Interop.IAsyncOperation+CompletedHandler value) (at <ed1f6dedc2514473bacf0986f8922b29>:0)
WinRT.Interop._IAsyncOperation`2[TTask,TResult].AsTask (System.Threading.CancellationToken cancellationToken) (at <ed1f6dedc2514473bacf0986f8922b29>:0)
WinRT.Interop._IAsyncOperation`2[TTask,TResult].AsTask () (at <ed1f6dedc2514473bacf0986f8922b29>:0)
Microsoft.Windows.Perception.People.IEyesPoseStatics.RequestAccessAsync () (at <ed1f6dedc2514473bacf0986f8922b29>:0)
Microsoft.Windows.Perception.People.EyesPose.RequestAccessAsync () (at <ed1f6dedc2514473bacf0986f8922b29>:0)
Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityEyeGazeDataProvider+<AskForETPermission>d__30.MoveNext () (at Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XR2018/WindowsMixedRealityEyeGazeDataProvider.cs:186)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:115)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by julenka** [comment]
It looks like this was an artifact of switching branches in mrtk_development and DotNetWinRT folder not getting cleared out. Doing a fresh clone of mrtk_development branch removed the issue.
