### ISSUE TITLE
Deploy window connection on HoloLens 2 fails with "authentification failed"

### ISSUE THREAD

**Issue by Softelectro** [microsoft/MixedRealityToolkit-Unity#7378]
## Describe the bug

Connection to Hololens 2 for the purpose of deploying my application through the build window of MRTK is always failing with the message "Authentication failed! Device Not Found | No Response Headers". I have already installed the certificate of my HoloLens 2 in my PC.

## To reproduce

1. Open Build and deploy window
2. Enter IP address and credentials of HoloLens in deploy tab
3. Press Connect
4. Receive error "Authentication failed! Device Not Found | No Response Headers "

## Expected behavior

The connection to the HoloLens is established and we can successfully deploy our app.

## Your setup (please complete the following information)

- Unity Version [2019.2.7f2]
- MRTK Version [v2.2.0]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by Troy-Ferrell** [comment]
@Softelectro thanks for filing this. Are you sure the Hololens is on the same LAN as your build machine? If deploying over wifi via an IP address, ensure the HL is not connected to the build machine via USB

If deploying via USB, ensure the IP selected is local host/127.0.0.1.

Can you deploy your app to the device via the traditional Visual studio deployment over wireless?

**Comment by Softelectro** [comment]
It is on the same LAN and not connected by USB.
I can deploy using Visual Studio over wireless.

The current workaround I'm using is creating the package in the build window and then install through the device portal. But it is more convenient to deploy through the build window itself.

**Comment by Troy-Ferrell** [comment]
Thanks @Softelectro for the additional information. I also forgot to mention, looks like you were using MRTK 2.2?

Can you try updating to latest code in the MRTK_Development branch (i.e clone locally and then copy/paste directories)? You could also attempt 2.3, but there has been 1/2 fixes since then.

**IMPORTANT**: In any of the above, make sure you turn off "Use SLL"

**Comment by Softelectro** [comment]
In terms of disabling "Use SSL", I did try it once since I read one of the posts saying that it caused issues. This managed to solve the issue of deploying to HoloLens 1 but not for HoloLens 2.

I also tried the release version of MRTK 2.3 and there I didn't even find the build and deploy editor window. So I came back to MRTK 2.2.

I'll try out the latest code in the dev branch and then come back to you.

**Comment by Troy-Ferrell** [comment]
> I also tried the release version of MRTK 2.3 and there I didn't even find the build and deploy editor window. So I came back to MRTK 2.2.

FYI, I believe the Build Deploy Window has moved to the MRTK.Tools unity package which is on the release page.
https://github.com/microsoft/MixedRealityToolkit-Unity/releases

Thanks for following up. Please ping this thread with any new information you can gather.

**Comment by Softelectro** [comment]
> FYI, I believe the Build Deploy Window has moved to the MRTK.Tools unity package which is on the release page.

Thanks for the information. I managed to get the mrtk 2.3 build window. But it didn't solve the issue.

I also tried the code from the dev branch but still get the same error.
`Authentication failed! Device Not Found | No Response Headers`

**Comment by francescoStrada** [comment]
I would like if possible to reopen the issue. I am unable to install the appx through the Build Window when connecting to the device remotely. From the build window I am able to successfully connet to the device via username e password buth when it attempts to install I get the two errors attached below.
I am currently using Unity 2020.3.34f1 with MRTK version 2.8.2.0

**ERROR #1**
REST Error: 403

Content-Length: 0
UnityEngine.Debug:LogError (object)
Microsoft.MixedReality.Toolkit.Utilities.Rest/<ProcessRequestAsync>d__10:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/WebRequestRest/Rest.cs:370)
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions:RunOnUnityScheduler (System.Action) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/Async/AwaiterExtensions.cs:144)
Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions/SimpleCoroutineAwaiter`1<UnityEngine.AsyncOperation>:Complete (UnityEngine.AsyncOperation,System.Exception) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/Async/AwaiterExtensions.cs:196)
Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions/InstructionWrappers/<ReturnSelf>d__2`1<UnityEngine.AsyncOperation>:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/Async/AwaiterExtensions.cs:387)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

**ERROR #2**
 Resetting Auth failed!
UnityEngine.Debug:LogError (object)
Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DevicePortal/<RefreshCsrfTokenAsync>d__50:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/WindowsDevicePortal/DevicePortal.cs:802)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<bool>:Start<Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DevicePortal/<RefreshCsrfTokenAsync>d__50> (Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DevicePortal/<RefreshCsrfTokenAsync>d__50&)
Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DevicePortal:RefreshCsrfTokenAsync (Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DeviceInfo)
Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DevicePortal/<InstallAppAsync>d__39:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/WindowsDevicePortal/DevicePortal.cs:452)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Microsoft.MixedReality.Toolkit.Utilities.Response>:SetResult (Microsoft.MixedReality.Toolkit.Utilities.Response)
Microsoft.MixedReality.Toolkit.Utilities.Rest/<PostAsync>d__4:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/WebRequestRest/Rest.cs:145)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Microsoft.MixedReality.Toolkit.Utilities.Response>:SetResult (Microsoft.MixedReality.Toolkit.Utilities.Response)
Microsoft.MixedReality.Toolkit.Utilities.Rest/<ProcessRequestAsync>d__10:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/WebRequestRest/Rest.cs:382)
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions:RunOnUnityScheduler (System.Action) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/Async/AwaiterExtensions.cs:144)
Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions/SimpleCoroutineAwaiter`1<UnityEngine.AsyncOperation>:Complete (UnityEngine.AsyncOperation,System.Exception) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/Async/AwaiterExtensions.cs:196)
Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions/InstructionWrappers/<ReturnSelf>d__2`1<UnityEngine.AsyncOperation>:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/Async/AwaiterExtensions.cs:387)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

**Comment by demisquare** [comment]
> I would like if possible to reopen the issue. I am unable to install the appx through the Build Window when connecting to the device remotely. From the build window I am able to successfully connet to the device via username e password buth when it attempts to install I get the two errors attached below. I am currently using Unity 2020.3.34f1 with MRTK version 2.8.2.0
> 
> **ERROR 1** REST Error: 403
> 
> Content-Length: 0 UnityEngine.Debug:LogError (object) Microsoft.MixedReality.Toolkit.Utilities.Rest/d__10:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/WebRequestRest/Rest.cs:370) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run () Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions:RunOnUnityScheduler (System.Action) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/Async/AwaiterExtensions.cs:144) Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions/SimpleCoroutineAwaiter`1<UnityEngine.AsyncOperation>:Complete (UnityEngine.AsyncOperation,System.Exception) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/Async/AwaiterExtensions.cs:196) Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions/InstructionWrappers/<ReturnSelf>d__2`1<UnityEngine.AsyncOperation>:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/Async/AwaiterExtensions.cs:387) UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
> 
> **ERROR 2** Resetting Auth failed! UnityEngine.Debug:LogError (object) Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DevicePortal/d__50:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/WindowsDevicePortal/DevicePortal.cs:802) System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<bool>:Start<Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DevicePortal/<RefreshCsrfTokenAsync>d__50> (Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DevicePortal/<RefreshCsrfTokenAsync>d__50&) Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DevicePortal:RefreshCsrfTokenAsync (Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DeviceInfo) Microsoft.MixedReality.Toolkit.WindowsDevicePortal.DevicePortal/<InstallAppAsync>d__39:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/WindowsDevicePortal/DevicePortal.cs:452) System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Microsoft.MixedReality.Toolkit.Utilities.Response>:SetResult (Microsoft.MixedReality.Toolkit.Utilities.Response) Microsoft.MixedReality.Toolkit.Utilities.Rest/d__4:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/WebRequestRest/Rest.cs:145) System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Microsoft.MixedReality.Toolkit.Utilities.Response>:SetResult (Microsoft.MixedReality.Toolkit.Utilities.Response) Microsoft.MixedReality.Toolkit.Utilities.Rest/<ProcessRequestAsync>d__10:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/WebRequestRest/Rest.cs:382) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run () Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions:RunOnUnityScheduler (System.Action) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/Async/AwaiterExtensions.cs:144) Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions/SimpleCoroutineAwaiter`1<UnityEngine.AsyncOperation>:Complete (UnityEngine.AsyncOperation,System.Exception) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/Async/AwaiterExtensions.cs:196) Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions/InstructionWrappers/d__2`1<UnityEngine.AsyncOperation>:MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@321dd3d08b64/Core/Utilities/Async/AwaiterExtensions.cs:387) UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

Same error for me

**Comment by JeroenTekle** [comment]
I'm having the same issue, sometimes it works magically

**Comment by Bian-Sh** [comment]
me too
