### ISSUE TITLE
NearInteractionGrabbable triggers exception when ManipulationHandler Component is disabled

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#7386]
## Describe the bug

`InvalidOperationException: NearInteractionGrabbable requires a BoxCollider, SphereCollider, CapsuleCollider or a convex MeshCollider on an object. Otherwise grab interaction will not work correctly.`

On an active GameObject with disabled ManipulationHandler Component.

`Collider[] colliders = gameObject.GetComponents<Collider>();`

**the `GetComponent `does not include disabled components, an alternative could be to use `GetComponentsInChildren(includeInactive:true)` which has an extra param (sadly the GetComponent does not have this extra param)**
i don't know if searching in children would have any side effect here.

## To reproduce

1. Create a GameObject with a ManipulationHandler
2. Disable the ManipulationHandler by hand or by code
3. When enabling the gameobject, the exception got triggered

## Alternative workaround
by code, Enable gameobject first, then disable component

## Expected behavior

no exception

## Your setup (please complete the following information)

- Unity Version [e.g. 2018.4.13f1]
- MRTK Version 2.2/2.3

**Comment by MaxWang-MS** [comment]
Hi @gilbdev, I cannot reproduce the issue using Unity 2018.4.24f1 and MRTK 2.4, could you try to update to the latest versions and see if the problem still persists? Also, if that still happens please give us a more detailed repro procedure, as the current one is slightly confusing (the supposedly buggy NearInteractionGrabbable script is not mentioned in the repro procedure)

**Comment by MaxWang-MS** [comment]
Please reopen the issue if you are still encountering this problem.
