### ISSUE TITLE
Serious display issue in HoloLens 2 running Windows Holographic for Business OS Build 10.0.18362.1053

### ISSUE THREAD

**Issue by Shiloh-James-ELC** [microsoft/MixedRealityToolkit-Unity#7387]
## Describe the bug

There is a serious display issue when running a Unity-compiled application in a HoloLens 2 device which is running Windows Holographic for Business OS Build 10.0.18362.1053.

The visual effect looks somewhat like a stencil image is masking out huge portions of the display, with squares of the scene visible through the grid. Please see the attached screenshot as an example of what we're seeing.

## To reproduce

Unity version: 2018.4.17f1
MRTK version: 2.2 (available at: https://github.com/microsoft/MixedRealityToolkit-Unity/releases/tag/v2.2.0 )
We are also using AVProVideo v1.10.1 to play a movie onto a cube, though we have encountered the issue with simple textures rendering on quads as well.

1. Set up Unity project in Unity version 2018.4.17f1 with MRTK v2.2.
2. Set up the scene using the menu item: [Mixed Reality Toolkit]>[Add to Scene & Configure].
3. Place a Unity cube in the scene with a textured material attached (we used AVProVideo to render a movie onto the cube).
4. Configure the build for HoloLens 2 using the recommended specs (listed at: https://docs.microsoft.com/en-us/windows/mixed-reality/recommended-settings-for-unity ).
5. Build and deploy to a HoloLens 2 device which is running the Windows Holographic for Business OS Build [10.0.18362.1053], firmware revision number: [11968.01.01.191205.F].
6. Run the application.
7. Observe the mask obstructing the view of the scene.

## Expected behavior

The scene should be visible in the HoloLens 2 viewport.

## Screenshots

![20200225_192554_HoloLens](https://user-images.githubusercontent.com/57342873/75230025-3119a100-5807-11ea-9ea8-af42db2f5f09.jpg)

## Your setup (please complete the following information)

Unity Version [2018.4.17f1]
MRTK Version [v2.2]

## Target platform (please complete the following information)

HoloLens 2

## Additional context

No additional contextual info.

**Comment by Shiloh-James-ELC** [comment]
I should also note that we have access to four HoloLens 2 devices, and this issue is displaying on two of them. Both of the affected devices are running OS Build: [10.0.18362.1053] Firmware revision number: [11968.01.01.191205.F].

The unaffected devices are currently running OS Build: [10.0.18362.1042] Firmware revision number: [11967.01.01.190923.F], so we can continue development on these devices for now. However, we do expect them to develop the issue when they decide to upgrade to the new firmware.

**Comment by davidkline-ms** [comment]
@Shiloh-James-ELC, are you seeing these issues with any other application on these devices?

Thanks!

**Comment by Shiloh-James-ELC** [comment]
Thanks for responding @davidkline-ms !

We are seeing this with all applications we have generated using the above Unity 2018.4.17f1 + MRTK v2.2 configuration. We have tested this with three entirely distinct Unity projects which used three separate downloads of the MRTK v2.2, using the same Unity install on the same machine.

We have not seen this issue with third-party apps we have used, however it is unclear from within the HoloLens which apps on the store are built using Unity, and what Unity version or MRTK version they may be using. If you can point us to a specific app to test, or are able to provide a project to us using these Unity & MRTK versions for internal deployment, we can test further.

**Comment by keveleigh** [comment]
This is a known issue with builds later than 1043, which matches your observation of unaffected devices running 1042. We're investigating internally, and I can update this thread when a fix is expected.

**Comment by Shiloh-James-ELC** [comment]
Thanks for the confirmation @keveleigh ! We'd appreciate any fixes, workarounds and info you can provide!

**Comment by keveleigh** [comment]
@Shiloh-James-ELC I just received word that the [Advanced Recovery Companion](https://docs.microsoft.com/en-us/hololens/hololens-recovery#hololens-2) is still pulling down the 1042 build. If you're able, you can use that tool to roll your device back.

**Comment by Shiloh-James-ELC** [comment]
@keveleigh Thanks for this suggestion. This will be useful for development in the short term, however we still require a tenable solution for production.

**Comment by keveleigh** [comment]
@Shiloh-James-ELC Can you recall if you were building a debug build (as opposed to release or master)? Recent reports have mentioned this mainly reproing in a debug build
