### ISSUE TITLE
Disable/Enable Spatial Mapping mesh collider in runtime

### ISSUE THREAD

**Issue by Kent1LG** [microsoft/MixedRealityToolkit-Unity#7389]
## Describe the problem

During some projects we need to disable the mesh collider of the spatial mapping during runtime
and enable it after. 
Example : I got an object who can move if i click on it, but when if i start my app near a wall my object can appear on the wall, you can't interact with it. The only solution is to restart the app.

## Describe the solution you'd like

Add a convenient method to enable or disable spatial mapping mesh collider.
David Kline on slack said : "like we did with ClearObservations()"

Thank you!

**Comment by davidkline-ms** [comment]
> David Kline on slack said : "like we did with ClearObservations()"

I did say that :smile: 👍

**Comment by davidkline-ms** [comment]
One consideration is going to be minimizing breaking changes. Working on a proposal now.

**Comment by in3dtech** [comment]
Any update on this?

**Comment by polygonfuture** [comment]
Updates on this would be very helpful.

**Comment by Zee2** [comment]
In MRTK3 this would be achieved by directly talking to the ARFoundation spatial mesh object. @davidkline-ms , if you'd like to add this feature to MRTK2, please reopen.
