### ISSUE TITLE
Errors with language version - Feature is not available in C# 6

### ISSUE THREAD

**Issue by Wizardsxz** [microsoft/MixedRealityToolkit-Unity#7392]
## Describe the bug
Errors after importing Microsoft Mixed Reality Toolkit v2.3.0 package when compiling in visual studio 2019 with UWP platform, IL2CPP and API compatibility level .NET 4.x in Unity 2019.2.13

## To reproduce

1- Create new project with Unity 2019.2.13
2- Import Microsoft Mixed Reality Toolkit v2.3.0 foundation package and setup the project
3- Switch to Universal Windows Platform
4- Create script with function using C# 7 or higher (e.g "out variable declaration")
5- Compile and observe as errors appear requiring language version 7.0 or higher

## Expected behavior
Should be able to compile in visual studio 2019 and see relevant errors to my work (Not using MS BUILD dropdown in Unity Editor)

## Screenshots

![image](https://user-images.githubusercontent.com/61468939/75266961-0a4d7180-57eb-11ea-8b7c-3ca9a959310e.png)

## Your setup
- Visual studio 2019
- Windows SDK Version=10.0.18362.0
- Unity Version [2019.2.13f1]
- MRTK Version [v2.3.0]

## Target platform
Universal Windows Platform (in editor)

**Comment by Troy-Ferrell** [comment]
hi @Wizardsxz I understand you are seeing the compiling errors, but when you click the following button, does the IDE not attach to Unity and enter debug mode?
![image](https://user-images.githubusercontent.com/25975362/75279127-e9235b80-57bf-11ea-99c5-f1a0c8d7cab6.png)

**Comment by Wizardsxz** [comment]
> hi @Wizardsxz I understand you are seeing the compiling errors, but when you click the following button, does the IDE not attach to Unity and enter debug mode?
> ![image](https://user-images.githubusercontent.com/25975362/75279127-e9235b80-57bf-11ea-99c5-f1a0c8d7cab6.png)

Hey @Troy-Ferrell, 

Thanks for the quick reply! You are correct I am able to actually attach the editor, I just assumed the errors were blocking because they appeared in Assembly-CSharp. I still have 500 errors in the code that hide my own and bloat the error/output windows.

I updated the expected result of my issue.

**Comment by Troy-Ferrell** [comment]
@Wizardsxz , I can repo the same regarding compiling issues but still able to attach debugger. At least you are not blocked there but it is a red herring issue for users. Thanks for filing

**Comment by Wizardsxz** [comment]
@Troy-Ferrell 

Glad it's a worthy report! It also throws my IDE for a loop, leaving red lines everywhere in my code despite that line not containing any errors or "fake" unsupported language features errors, makes for a visual mess and difficult to work with. if there was ever an error at some point on that line, the visual indicator remains until I reboot.

**Comment by brogall** [comment]
I've been running into this annoyance on a (non Mixed Reality) UWP project. Until it's resolved, is there any problem editing the .csproj file at the line that says 

&lt;LangVersion&gt;6&lt;/LangVersion&gt;

 It seems to get rid of the error messages.

**Comment by luchspeter** [comment]
I have the same issue.
Adding `<LangVersion>7</LangVersion>` did not solve the issue. The default, for the project that causes this error message, is `<LangVersion>latest</LangVersion>` anyways.

**Comment by nuernber** [comment]
Switching `<LangVersion>6</LangVersion>` to `<LangVersion>latest</LangVersion>` removes the errors for me

**Comment by cellarmation** [comment]
I am in the process of porting a MRTK 2.4.0 application from Unity 2018.4.18f1 to Unity 2019.4.16f1 and am now seeing this issue. Unity now generates *.Project.csproj files for each assembly in my project, these are duplicates of your assemblies that have the conditional complication flags for UWP set. I only see the LangVersion 6.0 issue in these "Project" files, the normal and Editor projects are fine. I suspect this is why some people can still run and attach the debugger. Another work around might just be to unload these projects.

I can't find much documentation on this "*.Project.csproj" feature, I am not sure at the moment if it is a Unity3D, MRTK or VS Unity Tools feature.

**Comment by cellarmation** [comment]
Looks like you can control if "*.Player.csproj" files get generated using this setting (at least in Unity3D 2019.4.18f1).

![PlayerProjects](https://user-images.githubusercontent.com/3090483/102133472-0f98ad00-3e4d-11eb-8733-b615af283a6b.png)

Initially when I had upgraded my project the player project files were being generated with a LangVersion of 6.0 even though the checkbox was un-selected. Checking it and forcing it to re-build fixed the issue, the projects got regenerated and had a LangVersion of 7.3. Interestingly I also tried un-checking and then Unity correctly didn't generated the player projects, so I guess it was in some bad/indeterminate state by the upgrade process. I don't really know if this is the same issue @Wizardsxz was seeing or not though.

**Comment by SeanBuckmaster** [comment]
please use language version 10.0 or greater

**Comment by keveleigh** [comment]
I haven't been able to repro this locally. I assume Unity made some changes to the way they generate the csproj files, or VS had some issues they fixed, or this was generally an upgrade-only issue (I've been mostly testing fresh sln builds). Going to close out as No Repro, but please reopen or ping if this is still blocking you.

**Comment by cellarmation** [comment]
> I haven't been able to repro this locally. I assume Unity made some changes to the way they generate the csproj files, or VS had some issues they fixed, or this was generally an upgrade-only issue (I've been mostly testing fresh sln builds). Going to close out as No Repro, but please reopen or ping if this is still blocking you.

Are you able to confirm what version of Unity and VS you have been using? What version does your UWP player vsproj files have for LangVersion? Just interested in working out if this is down to a Unity fix.
