### ISSUE TITLE
Bounding Box Handling proximity scaling gone wrong

### ISSUE THREAD

**Issue by pampas93** [microsoft/MixedRealityToolkit-Unity#7395]
## Describe the bug

Default behavior of HoloLens 2 styled bounding box has a handle bars which scale when cursor is close it them. These are input values (handleCloseProximity, handleMediumProximity). It works fine when the Target model is small (around below 0.6f scale)
Problem: The scaling of the handles does not work on proximity when the model is bigger (tested for (1,1,1) and doesn't work.

## To reproduce

1. Open the sample "BoundingBoxExamples.unity" scene
2. Increase the CoffeeCup3 gameObject size to 1,1,1
3. Now, on play, the handle bars don't scale on proximity

## Expected behavior

Expected behavior is to scale the handle bars as it works while the Target object is smaller in size.

### Problem,
![NotWorkingProximity](https://user-images.githubusercontent.com/8945788/75296652-01f53680-57eb-11ea-9bb8-892640d97c65.gif)
### Expected Behavior
![WorkingProximity](https://user-images.githubusercontent.com/8945788/75296658-0ae60800-57eb-11ea-87d3-dd9f221d0d09.gif)

## Your setup (please complete the following information)

- Unity Version [e.g. 2018.4.12f1]
- MRTK Version [e.g. v2.3]

## Target platform (please complete the following information)

- Unity Editor
- HoloLens 2

**Comment by pampas93** [comment]
After debugging through the code, found the following,

* To begin scaling the handles (on proximity) in `HandleProximityScaling()`, **we first need to add the positions of the pointers which are considered to be close to the bounding box**.
* Problem is, the way we calculate the above (in bold)
* maxRadius is not calculated correctly, and since maxRadius is smaller when the Target/BoundingBox becomes bigger, no pointer positions are added into the `proximityPoints` list.

**Comment by pampas93** [comment]
@thalbern I did a quick fix for this in the `HandleProximityScaling()`
```
// Grab points within sphere of influence from valid pointers
foreach (var pointer in proximityPointers)
{
    proximityPoints.Add(pointer.Position);

    Vector3? point = pointer.Result?.Details.Point;
    if (point.HasValue)
    {
        proximityPoints.Add(pointer.Result.Details.Point);
    }
}
```

And I don't check or calculate the `maxRadius` and `IsPointWithinBounds` anymore. I simply add it into the `proximityPoints`

**Comment by thalbern** [comment]
Thanks @pampas93 ! I'll have a closer look / add tests for this in a bit :)
