### ISSUE TITLE
Hololens mapping

### ISSUE THREAD

**Issue by Jun-Hyung348** [microsoft/MixedRealityToolkit-Unity#7398]
## Describe the problem
Hi, I use holeolns 1st generation, MRTK 2.2.0.
I want to locate all objects in unity on real-life object like third picture.
I can recognize real-life object in hololens but it doesn't work like third picture.
When I wore hololens, I can see real-life object, but all objects in unity doesn't locate real-life object.
![error1](https://user-images.githubusercontent.com/55191549/75312860-9076c000-589e-11ea-8b2c-37cbeefd18e7.PNG)
![error2](https://user-images.githubusercontent.com/55191549/75312861-92408380-589e-11ea-9536-af05fefae03f.PNG)
![image](https://user-images.githubusercontent.com/55191549/75312929-be5c0480-589e-11ea-9d7f-61f1bc11562b.png)

## Describe the solution you'd like

I just want to recognize real-life object like table and locate all animals and background on real-life object.
But When I operate hololens, animals and background move different direction like second picture. So I can see only background.
How could I see all objects on real-life object?

**Comment by Troy-Ferrell** [comment]
@Jun-Hyung348 thanks for filing this.

Everytime your Unity app starts up on HoloLens, a new coordinate system is used. Where-ever your head is at and looking on start-up of app in HL, will be the origin and pose for world space coordinate system.

You need to place your virtual scene objects at the correct physically location. There are a few ways to do this.

You can use an image tracking API like [vuforia](https://developer.vuforia.com/) or [QR code tracking](https://docs.microsoft.com/en-us/windows/mixed-reality/qr-code-tracking) -only supported on HL2.

You can use the TapToPlace component that will allow the user to place an object in the scene.(Requires latest version of code in MRTK_Development branch on gitub here)
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_TapToPlace.html

You can have the user move the virtual gameobjects via the ManipulationHandler component
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_ManipulationHandler.html

Or you can build something custom to your needs

**Comment by polar-kev** [comment]
Closing since Troy's reply is sufficient.
