### ISSUE TITLE
Windows xr plugin remoting

### ISSUE THREAD

**Issue by chiarapalu** [microsoft/MixedRealityToolkit-Unity#7399]
I can't connect remotely to the device (Hololens 1) using windows xr plugin remoting. I'm using unity 2019.4.0f5 with mrtk 2.3

1. Go to 'Window'
2. Click on 'windows xr plugin remoting'
3. emulation mode--> romote to device--> fill the IP of the remote machine
4. I got a visual c++ runtime library error and the application crash

**Comment by keveleigh** [comment]
There are some known issues with remoting and that plug-in at the moment. They're being worked on on the Unity side

**Comment by cre8ivepark** [comment]
https://forum.unity.com/threads/hololens-1-windows-xr-plugin-remoting-not-working.827970/

**Comment by uniqmuz** [comment]
Same Issue, but it's working on unreal engine 4.

**Comment by Misos95** [comment]
I have the same issue, has anybody found the solution?

**Comment by keveleigh** [comment]
> I can't connect remotely to the device (Hololens 1) using windows xr plugin remoting

HoloLens 1 isn't supported with Windows XR Plugin remoting. Closing this as external.
