### ISSUE TITLE
upgrade error : "MSBUILD : error MSB1008"

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#7408]
## Describe the bug
Show errors after upgrade project from v2.1.0 to v2.3.0.
It is not ok after that delete Library folder and reopen project.
MSBUILD : error MSB1008.
## To reproduce

1. upgrade Project from V2.1.0 to V2.3.0
2. show errors for each open project

## Screenshots
![image](https://user-images.githubusercontent.com/38685433/75345446-b4a2c300-58d7-11ea-9b1f-b1706e4ee821.png)
![image](https://user-images.githubusercontent.com/38685433/75406683-0d13a800-594c-11ea-9caf-49d82d2cfc44.png)
![image](https://user-images.githubusercontent.com/38685433/75406780-53690700-594c-11ea-930a-7246b3ebd2b9.png)
![image](https://user-images.githubusercontent.com/38685433/75406837-74315c80-594c-11ea-9d7c-30cb13b0bdc9.png)
![image](https://user-images.githubusercontent.com/38685433/75406922-b3f84400-594c-11ea-90f1-0839c3a101a7.png)

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.2.6f1]
- MRTK Version [e.g. v2.3.0]

## Target platform (please complete the following information)

- HoloLens
- Editor

**Comment by jasonhbartlett** [comment]
I'm getting this error even with a brand new empty project.

Unity 2018.4.20f1
MRTK Release 2.3.0

After importing packages and set project to UWP - Mixed Reality Toolkit > Utilities > Configure Unity Project > Enable MSBuild for Unity

Close and reopen Unity and get this error.

Is MSbuild for Unity optional or required for MRTK 2.3.0 use?

**Comment by keveleigh** [comment]
>Is MSbuild for Unity optional or required for MRTK 2.3.0 use?

MSBuild for Unity isn't required, but adds access to additional features. Currently those feature revolve around HoloLens 2, with most of them relating to holographic remoting from the editor. If you don't use HoloLens 2, you don't need it (currently, though we may add more features in the future on different devices).

**Comment by jasonhbartlett** [comment]
I am developing for HL2 and I'm now on MRTK v2.3.0 but have left MSBuild for Unity disabled.  I would like to enable it but I would really like:

1. Not to get this error:
```
MSBUILD : error MSB1008: Only one project can be specified.
UnityEngine.Debug:LogError(Object)
Microsoft.Build.Unity.MSBuildProjectBuilder:LogProgressMessage(String, ProgressMessageType) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.1-20200131.14/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:385)
Microsoft.Build.Unity.<>c__DisplayClass13_0:<BuildProjects>b__1(ValueTuple`2) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.1-20200131.14/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:213)
Microsoft.Build.Unity.DelegateProgress`1:Report(ValueTuple`2) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.1-20200131.14/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:516)
Microsoft.Build.Unity.<>c__DisplayClass14_0:<BuildProjectsAsync>b__1(ValueTuple`2) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.1-20200131.14/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:330)
Microsoft.Build.Unity.DelegateProgress`1:Report(ValueTuple`2) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.1-20200131.14/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:516)
Microsoft.Build.Unity.<>c__DisplayClass21_0:<ExecuteMSBuildAsync>b__0(Object, DataReceivedEventArgs) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.1-20200131.14/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:462)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()
```
2. A really simple tutorial about what MSBuild for Unity is!  I'm not an super experienced .NET developer and so I have no idea what this does for helping to develop MR applications in Unity.  I've tried reading the docs at [MSBuildForUnity GitHub page](https://github.com/microsoft/MSBuildForUnity) but its pretty confusing and I am having a hard time grasping it.  (Let alone try to figure out how to troubleshoot my this error I'm getting when I enable it in my MRTK Unity project.)

3. Are there docs explaining how MRTK uses it and how it improves developer workflow?

(FYI - we are pretty early in the development of our project so I may go ahead and start from scratch following the instructions of setting up a new project with Nuget for Unity to import MRTK.  Perhaps that will be smoother?  The only thing is that my project uses Mapbox for Unity SDK which unfortunately doesn't yet support IL2CPP if targeting UWP and therefore I'm having to stay at Unity > 2018.4  :(  )

**Comment by jasonhbartlett** [comment]
Hi @keveleigh I went through the [Debugging HoloLens 2 remoting via Unity package import](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html#debugging-hololens-2-remoting-via-unity-package-import) readme and everything checks out except for when I get to the section about adding DOTNETWINRT_PRESENT to the scripting define symbols. The field shows blank, and when I try to enter the symbol, it doesn't save!?  I click away and then back and the field is empty again?  Any thoughts?
Regarding this issue, since I AM developing for HL2 I really do want Remoting to work correctly.  What would you recommned?  Should do the Manual DotNetAdapter installation?  Will that allow Holographic Remoting to work?

**Comment by keveleigh** [comment]
>The field shows blank, and when I try to enter the symbol, it doesn't save!? I click away and then back and the field is empty again?

This sounds like the DotNetWinRT DLL isn't present in your Assets folder (the step "DotNetWinRT NuGet package resolution"). MRTK looks for that DLL and writes / removes the symbol as required. So, if you're unable to save it, likely MRTK is overwriting it due to a missing DLL.

Yeah, if MSBuildForUnity is causing problems, I'd recommend manual DotNetAdapter installation in your case. That should still allow everything to work.

**Comment by jasonhbartlett** [comment]
@keveleigh No, I forgot to mention that it doesn't exist and following the instructions to click the Build or Rebuild buttons doesn't create it.  That's when I just get this "MSBUILD : error MSB1008: Only one project can be specified." error.

Okay, I want to try manual DotNetAdapter installation.  Do I need to Uninstall MSBuild for Unity first?  The Readme has the warning that "Using both MSBuild for Unity and another NuGet client within the same project is not supported."  But, the instructions don't say to uninstall MSBuild for Unity first???

**Comment by keveleigh** [comment]
@jasonhbartlett Yep, I'd follow https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html#removing-hololens-2-specific-remoting-support for uninstallation instructions.

>But, the instructions don't say to uninstall MSBuild for Unity first???

Ahh, I think those are assuming you're starting from scratch. I can add a reference to the uninstallation steps in case others are starting from where you are.

**Comment by jasonhbartlett** [comment]
@keveleigh Okay, that worked.  Recommend adding note about deleting any existing NuGet.config file before importing NuGet for Unity package into your project.  [Ref this issue on NugetForUnity github](https://github.com/GlitchEnzo/NuGetForUnity/issues/326)

Tested out and the Holographic Remoting works again!  Sweet!

**Comment by jasonhbartlett** [comment]
@keveleigh 
Hmmm... tried building and getting this error:  Any ideas?  

I'll try deleting and reimporting MRTK, and other packages I guess.

`UnityException: Failed to run reference rewriter with command "--target=Temp\StagingArea\Assembly-CSharp.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.Shared.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Gltf.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Extensions.Tracking.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Extensions.SceneTransitionService.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Extensions.HandPhysics.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Examples.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Demos.UX.Interactables.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Demos.InspectorFields.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Demos.Gltf.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Async.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Providers.WindowsVoiceInput.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.SDK.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.BoundarySystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.CameraSystem.dll" "--target=Temp\StagingArea\Unity.XR.WindowsMR.dll" "--target=Temp\StagingArea\Unity.TextMeshPro.dll" "--target=Temp\StagingArea\Unity.Analytics.DataPrivacy.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Tools.Runtime.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.TeleportSystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.SpatialAwarenessSystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.SceneSystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.InputSystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.InputSimulation.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.InputAnimation.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.DiagnosticsSystem.dll" "--target=Temp\StagingArea\System.Drawing.Primitives.dll" "--target=Temp\StagingArea\UnityEngine.Timeline.dll" "--target=Temp\StagingArea\UnityEngine.UI.dll" "--target=Temp\StagingArea\Mapbox.VectorTile.Geometry.dll" "--target=Temp\StagingArea\UdpClientServer.dll" "--target=Temp\StagingArea\MapboxAccountsUnity.dll" "--target=Temp\StagingArea\UnityEngine.SpatialTracking.dll" "--target=Temp\StagingArea\Mapbox.VectorTile.VectorTileReader.dll" "--target=Temp\StagingArea\Mapbox.VectorTile.ExtensionMethods.dll" "--target=Temp\StagingArea\Microsoft.Windows.MixedReality.DotNetWinRT.dll" "--target=Temp\StagingArea\Mapbox.VectorTile.PbfReader.dll" "--target=Temp\StagingArea\UnityEngine.Networking.dll" "--target=Temp\StagingArea\Mapbox.IO.Compression.dll" "--target=Temp\StagingArea\Mapbox.Json.dll" "--additionalreferences=Temp\StagingArea,Temp\StagingArea\Plugins\X64,Temp\StagingArea\Plugins\ARM,Temp\StagingArea\Plugins\ARM64,Temp\StagingArea\Plugins\X86,C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0\Facade,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.AI.MachineLearning.MachineLearningContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.AI.MachineLearning.Preview.MachineLearningPreviewContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.Background.CallsBackgroundContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.CallsPhoneContract\5.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.CallsVoipContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.SocialInfo.SocialInfoContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.StartupTaskContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Custom.CustomDeviceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.DevicesLowLevelContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Printers.PrintersContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.SmartCards.SmartCardEmulatorContract\6.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.UniversalApiContract\8.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.XboxLive.StorageApiContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Graphics.Printing3D.Printing3DContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.Connectivity.WwanContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.Sockets.ControlChannelTriggerContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Maps.GuidanceContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Maps.LocalSearchContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Store.StoreContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.TargetedContent.TargetedContentContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileHardwareTokenContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileSharedModeContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.SystemManufacturers.SystemManufacturersContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.SystemManagementContract\6.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.ViewManagement.ViewManagementViewScalingContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Xaml.Core.Direct.XamlDirectContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.ActivatedEventsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.ActivationCameraSettingsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.ContactActivatedEventsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.WebUISearchActivatedEventsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Background.BackgroundAlarmApplicationContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.LockScreenCallContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.FullTrustAppContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Preview.InkWorkspace.PreviewInkWorkspaceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Preview.Notes.PreviewNotesContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Resources.Management.ResourceIndexerContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Search.Core.SearchCoreContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Search.SearchContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Wallet.WalletContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Portable.PortableDeviceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Printers.Extensions.ExtensionsContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Scanners.ScannerDeviceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Sms.LegacySmsApiContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.Input.GamingInputPreviewContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.Preview.GamesEnumerationContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.UI.GameChatOverlayContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.UI.GamingUIProviderContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Globalization.GlobalizationJapanesePhoneticAnalyzerContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Management.Deployment.Preview.DeploymentPreviewContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Management.Workplace.WorkplaceSettingsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.AppBroadcasting.AppBroadcastingContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.AppRecording.AppRecordingContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.AppBroadcastContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.AppCaptureContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.AppCaptureMetadataContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.CameraCaptureUIContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.GameBarContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Devices.CallControlContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.MediaControlContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Playlists.PlaylistsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Protection.ProtectionRenewalContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.NetworkOperators.LegacyNetworkOperatorsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.XboxLive.XboxLiveSecureSocketsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Perception.Automation.Core.PerceptionAutomationCoreContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Security.EnterpriseData.EnterpriseDataContract\5.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Security.ExchangeActiveSyncProvisioning.EasContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Storage.Provider.CloudFilesContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileRetailInfoContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.UserProfile.UserProfileContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.UserProfile.UserProfileLockScreenContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.ApplicationSettings.ApplicationsSettingsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Core.AnimationMetrics.AnimationMetricsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Core.CoreWindowDialogsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Shell.SecurityAppManagerContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Xaml.Hosting.HostingContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Web.Http.Diagnostics.HttpDiagnosticsContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Embedded.DeviceLockdown.DeviceLockdownContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.NetworkOperators.NetworkOperatorsFdnContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Phone.PhoneContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Phone.StartScreen.DualSimTileContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.WebUI.Core.WebUICommandBarContract\1.0.0.0" "--platform=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0\Facade\Windows.winmd" "--dbg=pdb" "--support=Temp\StagingArea\WinRTLegacy.dll" "--supportpartialns=Unity.Partial" "--system=System" "--lock=UWP\project.lock.json" "--alt=Microsoft.Win32.SafeHandles,System.IO.FileSystem;Microsoft.Win32.SafeHandles,System.Runtime.Handles;System,System.ComponentModel;System,System.Data.Common;System,System.Runtime;System,System.Runtime.Extensions;System,System.Runtime.InteropServices;System,System.Threading.Tasks;System.CodeDom.Compiler,System.Diagnostics.Tools;System.Collections,System.Collections;System.Collections,System.Collections.NonGeneric;System.Collections,System.Runtime;System.Collections.Generic,System.Collections;System.Collections.Generic,System.Runtime;System.Collections.ObjectModel,System.ObjectModel;System.Collections.ObjectModel,System.Runtime;System.Collections.Specialized,System.Collections.NonGeneric;System.Collections.Specialized,System.Collections.Specialized;System.Collections.Specialized,System.ObjectModel;System.ComponentModel,Microsoft.Win32.Primitives;System.ComponentModel,System.ComponentModel;System.ComponentModel,System.ComponentModel.EventBasedAsync;System.ComponentModel,System.ObjectModel;System.ComponentModel,System.Runtime;System.ComponentModel.DataAnnotations,System.ComponentModel.Annotations;System.Data,System.Data.Common;System.Data.Common,System.Data.Common;System.Diagnostics,System.Diagnostics.Debug;System.Diagnostics,System.Diagnostics.StackTrace;System.Diagnostics,System.Runtime;System.Diagnostics,System.Runtime.Extensions;System.Diagnostics.CodeAnalysis,System.Diagnostics.Tools;System.Globalization,System.Globalization;System.Globalization,System.Globalization.Calendars;System.Globalization,System.Globalization.Extensions;System.Globalization,System.Runtime;System.IO,System.IO;System.IO,System.IO.FileSystem;System.IO,System.IO.FileSystem.Primitives;System.IO,System.IO.UnmanagedMemoryStream;System.IO,System.Runtime;System.IO,System.Runtime.Extensions;System.IO,System.Runtime.Handles;System.IO.Compression,System.IO.Compression;System.IO.IsolatedStorage,System.IO.IsolatedStorage;System.Linq,System.Linq;System.Linq,System.Linq.Expressions;System.Linq,System.Linq.Queryable;System.Linq.Expressions,System.Linq.Expressions;System.Net,System.Net.Primitives;System.Net,System.Net.Requests;System.Net,System.Net.WebHeaderCollection;System.Net.NetworkInformation,System.Net.NetworkInformation;System.Net.NetworkInformation,System.Net.Primitives;System.Net.Security,System.Net.Primitives;System.Net.Sockets,System.Net.Primitives;System.Net.Sockets,System.Net.Sockets;System.Reflection,System.Reflection;System.Refl<message truncated>`

**Comment by jasonhbartlett** [comment]
@keveleigh Okay, it appears that importing specifically the DotNetWinRT package (with NuGet for Unity) is the cause for the above UnityException.  :(

Fortunately I have a work-around for building my project.  If I simply uninstall that DotNetWinRT package and clear DOTNETWINRT_PRESENT out of the Scripting Define Symbols before attempting to build, then my project builds successfully.

So I at least have a way of still using the Holographic Remoting and having the hand interactions fully work by installing that DotNetWinRT package, but still being able to build by removing it.

I'll take whatever I can get I suppose.  Have submitted an issue at the N4U GitHub page here: [Issue 332](https://github.com/GlitchEnzo/NuGetForUnity/issues/332)
