### ISSUE TITLE
Investigate refactoring some GetOrAddController code across data providers

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#7416]
## Describe the problem

As mentioned in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7375#discussion_r383904910, there are some similar patterns that data providers follow when creating new controller types. It's worth investigating and potentially refactoring some of this logic into the base class to reduce the code needed to create a custom data provider.

Related to #5847

**Comment by polar-kev** [comment]
This improvement to 2.x is no longer necessary given MRTK 3's move to Unity's XRI.
