### ISSUE TITLE
ScreenPointToRay is laggy on AR Session camera

### ISSUE THREAD

**Issue by vburovIntuitive** [microsoft/MixedRealityToolkit-Unity#7420]
## Overview

I'm using the ScreenPointToRay function to cast a ray from a position on screen to a 3D object, and then using LineRenderer to draw a line between those two objects.

In the AR Session camera, when I move the phone, the LineRenderer drawing doesn't update fast enough and lags. In my case, I have a RectTransform with an Image, to the center pivot of which the LineRenderer receives its first point ( the second is the 3D object ). The Line Position 0 is behind the Image, but due to the lag, the origin appears outside the Image.

Furthermore, applying this same technique in regular 3D Space, or Vuforia Model Tracking does not lag.

I'm setting positions via SetPositions, and tried running this in Update and LateUpdate with no resolve. 

## Unity editor version

2019.3

## Mixed Reality Toolkit release version

2.3

**Comment by davidkline-ms** [comment]
@vburovIntuitive, do you see lag when using the AR Session camera without MRTK?
