### ISSUE TITLE
SRP Batcher not supported by MRTK Standard shader

### ISSUE THREAD

**Issue by rwetzold** [microsoft/MixedRealityToolkit-Unity#7434]
## Describe the problem

Selecting the MRTK 2.3 standard shader in the Unity explorer (when upgraded to URP) in Unity 2019.3 will show that it is not compatible with the SRP Batcher (_color in wrong cbuffer). This is prohibitive right now as this will double the draw calls in my VR app compared to the Unity standard shader eliminating all performance gains.

## Describe the solution you'd like

Support SRP Batcher.

## Describe alternatives you've considered

Unity standard shader.

## Additional context

Upon request

**Comment by rwetzold** [comment]
Has there been any more work on this? I see that MRTK 2.5 is now out and it would be great to get the best Unity performance possible.

**Comment by keveleigh** [comment]
@Cameron-Micka Is this something you've looked at?

**Comment by Cameron-Micka** [comment]
@keveleigh I've not had a chance to look at this, but Troy was investigating it awhile back. His PR looks ready to go if someone has time to test it/verify things batch as expected: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7440 

@RogPodge has been looking at a few graphics related things recently, he might be interested in taking a look?

**Comment by RogPodge** [comment]
I can take some time to verify the PR

**Comment by Cameron-Micka** [comment]
@rwetzold I finally had a chance to dig into @RogPodge's PR and see what it would take to get SRP Batcher support working. Sadly it appears to be a bigger change than initially thought. :(

The way Unity defines a handful of shader variables in its commonly used CG includes breaks the SRP Batcher. So, to properly support the batcher and the MRTK/Standard shader's existing features we would have to add a new HLSL sub shader to the MRTK/Standard shader. I've posted my thoughts on how to do this here: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8830

Please let me know if you have any questions!

**Comment by RogPodge** [comment]
A fix for this is Unity 2020+ specific and located in this branch. We're not committed to pushing it here yet due to still supporting unity 2018 and unity 2019

**Comment by Zee2** [comment]
@Cameron-Micka update on this? I'm assuming modern MRGT handles this?

**Comment by Cameron-Micka** [comment]
> @Cameron-Micka update on this? I'm assuming modern MRGT handles this? Closing here for staleness, but reopen if needed.

Thanks! This is closed/complete. All shaders in [Graphics Tools](https://github.com/microsoft/MixedReality-GraphicsTools-Unity) (and in turn MRTK3) are SRP batcher compatible: 
![image](https://user-images.githubusercontent.com/13305729/177641154-f8fbfa71-440e-45d3-8f0c-409baaa8bdd6.png)
