### ISSUE TITLE
Rendering issue with LWRP, ShaderGraph and Stereo rendering mode

### ISSUE THREAD

**Issue by TheLLspectre** [microsoft/MixedRealityToolkit-Unity#7436]
Hi everyone !
## Describe the bug

There are two issues with this big one ! 
The first one, is with the "Single Pass Instanced" the terrain in Unity is duplicated in the left eye and disappear in the right.

The second one, when you switch to the "Single Pass" setting, there is a weird "filter" which appear on every models. It's like a big shadow and like it tried to duplicate some parts of models but not on the terrain ! And we clearly seen the separation between the right and left eye.

## To reproduce

Install your scene with some custom models and a terrain.
Add the LWRP.
Add ShaderGraph.
Add customs shaders from shadergraph.
Apply material build with shadergraph on custom models
Switch stereo rendering settings

## Screenshots

![Capture](https://user-images.githubusercontent.com/30622829/75524366-0b121d80-5a0e-11ea-9bde-5102331afafa.PNG)

See the difference between those two images you clearly see the separation from eyes. I thinks it's from the rendering of both eyes.
![Capture2](https://user-images.githubusercontent.com/30622829/75524392-182f0c80-5a0e-11ea-8b9c-b827f0b9e340.PNG)

And why I switch the camera to only one eye this issue disappear.
![Capture3](https://user-images.githubusercontent.com/30622829/75524397-1a916680-5a0e-11ea-925a-13d8c51981c4.PNG)

I put it but nothing clearly appear on this one. Is when I passed to the Single Pass Instanced, the terrain are duplicate in the left eye.
![Capture4](https://user-images.githubusercontent.com/30622829/75524399-1bc29380-5a0e-11ea-8982-0645cfeaa4f5.PNG)

And this is the setting from my LWRP
![Capture5](https://user-images.githubusercontent.com/30622829/75524404-1cf3c080-5a0e-11ea-8260-942609cdcbbd.PNG)

## Your setup (please complete the following information)

- Unity Version [2019.2.16f]
- MRTK Version [v2.2.0]

## Target platform (please complete the following information)

- OpenVR

## Additional context

An issue was open few month ago, and they just said change the stereo rendering mode but it's not enough to fix this problem...

**Comment by Troy-Ferrell** [comment]
@TheLLspectre thanks for filing the issue. Do you still see this problem if you proceed with your repo instructions without MRTK? Your notes seem to indicate this is more a Unity issue vs MRTK.

I am also assuming from your notes that you are not using the MRTK standard shader, you are using a custom built shader from ShaderGraph

**Comment by TheLLspectre** [comment]
@Troy-Ferrell Well I already published one game with this LWRP settings. And a classic camera not VR
 
> I am also assuming from your notes that you are not using the MRTK standard shader, you are using a custom built shader from ShaderGraph

And when I see this answer I'm thinking about the problem comming from my shaders with the rendering system of the left AND right eye.
May be I need to exaggerate the setting of my shaders
