### ISSUE TITLE
Older version of HTK - Getting Started - outdated?

### ISSUE THREAD

**Issue by Porupu** [microsoft/MixedRealityToolkit-Unity#7464]
Hi,
I've been recently trying to install an older version of the Toolkit when it still used to be HTK and followed the steps at https://github.com/microsoft/MixedRealityToolkit-Unity/blob/htk_release/GettingStarted.md (downloading the described version of Unity, Visual Studio and the Toolkit). Once I loaded the Toolkit into Unity, however, I got these 10 errors:
![Annotation 2020-03-01 193053](https://user-images.githubusercontent.com/32370305/75632385-63eedb00-5bf3-11ea-892d-058e126c52c5.png)
Should I have installed a different version or is the guide outdated?

I need HTK as MRTK no longer supports a functionality I need (Mic Stream Selection).
Thanks a lot.

**Comment by keveleigh** [comment]
Did you install the HTK using a unity package or cloning the repo? Do you remember which exact version you installed?

**Comment by Porupu** [comment]
It was the HTK v2018.8.0.0_Alpha as per the guide on the Getting Started page (https://github.com/microsoft/MixedRealityToolkit-Unity/releases/tag/2018.8.0.0_Alpha2.1).

Tried it using the .unitypackage.

**Comment by keveleigh** [comment]
Ah, also which version of Unity are you using? We stopped development on HTK around the Unity 2017.x timeframe, so it's possible Unity made some breaking changes on more recent versions. You should be able to go in and fix up any missing references though, either via Unity's recommendations in their docs or by looking at the corresponding MRTK scripts (which were based originally written for Unity 2018.x).
