### ISSUE TITLE
IMixedRealityInputSystem.RaiseGestureCanceled is never called in WindowsMixedRealityDeviceManager

### ISSUE THREAD

**Issue by Holo-Viktor** [microsoft/MixedRealityToolkit-Unity#7466]
## Describe the bug

`InteractionManager_InteractionSourceLost(args)` is called before any `Hold/Manipulation/NavigationCanceled` events, which calls `RemoveController(source)` and removes the controller from the `activeControllers` Dictionary. This causes the `GetController(id)` in the `Hold/Manipulation/NavigationCanceled` events to return `null` resulting in `RaiseGestureCanceled` to never being called.

## To reproduce

1. Create a new 3D Project.
2. Import the MRTK Foundation package.
3. Go to Mixed Reality Toolkit -> Utilities -> Configure Unity Project
4. Ensure all Checkboxes are enabled
5. Click on Apply
6. Open the Assets/Scenes/SampleScene
6. Go to Mixed Reality Toolkit -> Add to Scene and Configure
7. Add a Cube GameObject to the Scene
8. Attach the BoundingBox Script Component to the Cube
9. Open the Project in Visual Studio
10. Open the file WindowsMixedRealityDeviceManager.cs
11. Add a breakpoint on the `RaiseGestureCanceled` call inside the `GestureRecognizer_ManipulationCanceled` method definition.
12. Attach Visual Studio to Unity
12. Connect a HoloLens 1 (haven't tested it with HL2)
13. Open the Holographic Remoting App on the HL1
14. Go to Window -> XR -> Holographic Emulation
15. For the EmulationMode select Remote to Device and enter the IP adress shown in the Holographic Remoting App on the HL1
16. Click on Connect
17. Click on Play to start the SampleScene
18. HL: Grab one of the Manipulation handles and drag it with your hand with your hand leaving the field of view of the HL cameras.
19. Observe how the breakpoint is never hit.

## Expected behavior

`GetController(id)` should not return `null` in the `Hold/Manipulation/NavigationCanceled` events and the `IMixedRealityInputSystem.RaiseGestureCanceled` should be called with the controller which is to be removed at the end of the frame.

## Your setup

- Unity 2018.4.13f1
- MRTK v2.2 (I haven't tested v2.3 but a file diff of the two versions does not indicate any fix for that)

## Target platform

- HoloLens
- HoloLens 2 (probably)

**Comment by polar-kev** [comment]
Hey @Holo-Viktor, is this issue still present in the latest version of MRTK? If it is please feel free to let us know and reopen this issue.
