### ISSUE TITLE
CoreServices method does not contain the definition for GetInputSystemDataProvider

### ISSUE THREAD

**Issue by amfdeluca** [microsoft/MixedRealityToolkit-Unity#7472]
## Describe the issues
CoreServices method does not contain the definition for GetInputSystemDataProvider.

## Feature area
CoreServices  does not implement the method although I have imported all the necessary utilities. I'm using MRTK2.2.0

## Existing doc link
https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.CoreServices.html

under the voice "Joint transform from hand joint service"

**Comment by davidkline-ms** [comment]
The documentation page defaults to the mrtk_development branch. To see the content for a specific version of MRTK, you can click on the title bar like shown in the following diagram.

Thanks!

![image](https://user-images.githubusercontent.com/13281406/75819711-fd330400-5d4f-11ea-9127-0e80fde0aa90.png)
