### ISSUE TITLE
PC UWP terminates when attempting to connect using Holographic Remoting API to HoloLens2 from PC UWP app

### ISSUE THREAD

**Issue by RobertLee6108** [microsoft/MixedRealityToolkit-Unity#7493]
## Describe the bug

When I try to connect to Hololes2 using Holographic RemotingAPI in the PC UWP app, 
the PC UWP exits after outputting a "Screen position out of view frustum" error. (high probability)

## To reproduce

1. Create a new 3D Project.
2. Import the MRTK Foundation package.
3. Go to Mixed Reality Toolkit -> Utilities -> Configure Unity Project
4. Ensure all Checkboxes are enabled
5. Click on Apply
6. Open the Assets/Scenes/SampleScene
7. Go to Mixed Reality Toolkit -> Add to Scene and Configure
8. Add a Cube GameObject to the Scene
9. Add remoteconnect C# script and drag Cube
10. copy and paste this in remoteconnect.cs

using UnityEngine;
using UnityEngine.UI;
using UnityEngine.XR.WSA;
using UnityEngine.XR;
public class remoteconnect : MonoBehaviour
{
    public InputField _IP;
    public Button _button;
    private void Start()
    {
        _button.onClick.AddListener(connect);
    }
    public void connect()
    {
        try
        {
            if (XRSettings.enabled)
            {
                HolographicRemoting.Connect(_IP.text, 9999, RemoteDeviceVersion.V2);
            }
            else
            {
                XRSettings.enabled = true;
                HolographicRemoting.Connect(_IP.text, 9999, RemoteDeviceVersion.V2);
            }
        }
        catch (System.Exception e)
        {
            Debug.Log("error message : " + e.ToString());
        }
    }
}

11. Add Unity Button and InputField
12. Drag and drop InputField, Button form remoteconnect.cs
13. Open File -> Build Settings
14. Add SampleScene in Scenes In Build
15. Build UWP project
16. Open sln file
17. Change Relese,x64 config
18. Open Package.appxmanifest 
19. Move Packaging tab
20. Select certification
21. Press Ctrl + F5
22. After holographic remoting app is executed in Hololens2, input the IP shown in holographic remoting app to UWP app InputField and click button (Hololens2 and PC should be in the same network)

## Screenshots

![frustum](https://user-images.githubusercontent.com/53291925/75954655-8fc1d780-5ef7-11ea-9b8f-d62b1c538e22.PNG)

outputting a "Screen position out of view frustum" error. (high probability)

## Your setup (please complete the following information)

- Windows SDK [ 10.0.18362.1 ]
- Unity Version [ 2018.4.16f1 ]
- MRTK Version [ 2.2.0 ]

## Target platform (please complete the following information)

- PC
- HoloLens 2

**Comment by keveleigh** [comment]
We've had a few issues with this scenario in previous Unity releases. I believe the latest WMR plug-in for Unity (1.0.19 in the Unity Package Manager) has fixed most, if not all of the issues. Can you try updating that package?

**Comment by RobertLee6108** [comment]
Fixed by updating Unity version. (2018.4.20f)

**Comment by keveleigh** [comment]
Closing as resolved in newer versions of Unity and the WMR plug-in
