### ISSUE TITLE
Unable to register IMixedRealityInputDeviceManager service with a null concrete type on Standalone builds

### ISSUE THREAD

**Issue by amonnot-ah** [microsoft/MixedRealityToolkit-Unity#7496]
## Describe the bug

Unable to use the same input simulation as in Unity editor in a Windows Standalone build as it is described here  #7018 
_Unable to register IMixedRealityInputDeviceManager service with a null concrete type._ 

## To reproduce

1. Create a new Unity project
2. Import the Microsoft.MixedReality.Toolkit.Unity.Foundation.2.3.0.unitypackage
3. Mixed Reality Toolkit > Add to Scene and Configure
3. Clone the DefaultMixedRealityToolkitConfigurationProfile, clone the DefaultMixedRealityInputSystemProfile
4. Go to Input Data Providers > Input Simulation Service and add Windows Standalone as supported plateforms
5. Build and run

## Expected behavior

Be able to fly around the 3D scene and to display hands with space or shift key

## Your setup (please complete the following information)

- Unity Version 2019.3.3f1
- MRTK Version v2.3.0

## Target platform (please complete the following information)

- Windows Standalone

## Additional context

I've attached the Player.log file that match the describe steps
[Player.log](https://github.com/microsoft/MixedRealityToolkit-Unity/files/4298747/Player.log)

**Comment by keveleigh** [comment]
Looks like the PR you mention (https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7018) was not merged for the 2.3 release but will instead ship with our upcoming 2.4 release. I just tested this scenario in the mrtk_development branch, and it should be ready for 2.4!

**Comment by pinkwerks** [comment]
@keveleigh I'm seeing this problem in mrtk 2.5.1

**Comment by dahaideyu** [comment]
> Looks like the PR you mention (#7018) was not merged for the 2.3 release but will instead ship with our upcoming 2.4 release. I just tested this scenario in the mrtk_development branch, and it should be ready for 2.4!

But I have same issue in MRTK 2.6.1

**Comment by patrickmemestar** [comment]
I have the same problem!

**Comment by keveleigh** [comment]
Those all seem expected on a standalone build. We should probably find a way to clean the logs up to something more accurate as far as why they aren't being registered. Are they causing issues?

**Comment by Abbeychow** [comment]
> > Looks like the PR you mention (#7018) was not merged for the 2.3 release but will instead ship with our upcoming 2.4 release. I just tested this scenario in the mrtk_development branch, and it should be ready for 2.4!
> 
> But I have same issue in MRTK 2.6.1:
> 
> **1. Unable to register IMixedRealityInputDeviceManager data provider (Windows Mixed Reality Device Manager) because the value of concreteType is null.**
> 
> **2.Unable to register IMixedRealitySpatialAwarenessObserver data provider (Windows Mixed Reality Spatial Mesh Observer) because the value of concreteType is null.**
> 
> **3.Assertion failed on expression: 'NULL == handler->m_Next'**
> 
> **4.Unable to register IMixedRealitySpatialAwarenessObserver data provider (Windows Mixed Reality Spatial Mesh Observer) because the value of concreteType is null.**

Have you solved the problem?

**Comment by powerschaf** [comment]
Hello everyone, i found a kind of soloution please check out my Bug Report (#9722).

I hope i can help you out.

**Comment by Wyattari** [comment]
![image](https://user-images.githubusercontent.com/9206357/192038979-e08fe310-b756-454b-a312-1fe9de86fb03.png)
That's how it's currently set up
