### ISSUE TITLE
MRTK Standard Shader performance does not seem to vary with keyword toggling

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#7499]
## Describe the bug

While trying to set up a shader test scene to look at how performance might vary with changes to the MRTK shader, I noticed that performance remained mostly the same with keywords/features ON or OFF. 

Maybe I am missing something thus far, but this is worth investigating if even turning off features does not necessarily translate into full performance benefit. 

At very least, the MRTK standard shader should perform generally as well as the unlit/texture shader if everything is turned off. There is a slight noticeable perf difference with everything on (it's definitely more volatile).

**NOTE:** This is only tested in Unity editor, not built, and on a desktop dev machine.

**ALL KEYWORDS/FEATURE OFF**
![all-off](https://user-images.githubusercontent.com/25975362/76121098-bb9c9600-5fa7-11ea-9259-4a9ba04d8286.gif)

**KEYWORDS/FEATURES ON**
![all-on](https://user-images.githubusercontent.com/25975362/76121079-b63f4b80-5fa7-11ea-93cf-79e32be9d4f6.gif)

**Unity Unlit texture shader**
![unlit](https://user-images.githubusercontent.com/25975362/76121482-99574800-5fa8-11ea-9f64-9c0daad5d79b.gif)

## To reproduce

Downloaded 500k poly car model and instantiate 5 in scene with each unique material instance. 
For base material that was instantiated for each car, try to use the Unity standard shader, MRTK shader, or unlit/diffuse shader. 

On my machine, 
Unity Standard shader = 25 FPS
MRTK standard shader = 40-44 FPS?
Unlit/diffuse = 60+ FPS

However, toggling all of the MRTK keywords did not really fluctuate performance much, maybe 1-3 FPS difference. Everything off should effectively be an unlit shader (like Unity's unlit/detail) which should easily run at 60. 

## Expected behavior

Turning on/off MRTK standard shader features should fluctuate performance as different variants of the shader code is used (i.e ones with more or less instructions)

## Your setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Troy-Ferrell** [comment]
**Update notes:**

Issue seems to be tied to GPU instancing. There must be a memory bottleneck issue whereby there is a large list of per-vertex instanced data being submitted to the GPU as well in teh MRTK/standard OFF vs unlit/texture shaders

**Comment by Cameron-Micka** [comment]
Thank you for bringing this up @Troy-Ferrell! It does look like when a user checks "Enable GPU Instancing" it toggles the `#pragma multi_compile_instancing` shader feature which in turn adds an extra uint32 per vertex (which in these scene would be 3.6 million x 32 bits = ~14.5MB of vertex data) and potentially a lot more cache misses. It also adds a few more instructions to the vertex shader via [`UNITY_SETUP_INSTANCE_ID()`](https://github.com/TwoTailsGames/Unity-Built-in-Shaders/blob/2d24565fed6e5a2ac85bd69e38f583526793c437/CGIncludes/UnityInstancing.cginc#L166).

So, I suppose we should be careful to enable GPU instancing only when we think it will influence batch count. I normally leave it unchecked unless I know a certain material/mesh pair will appear often (or using one of the [`Graphics.DrawMeshInstanced`](https://docs.unity3d.com/ScriptReference/Graphics.DrawMeshInstanced.html) APIs.

This all brings up another good point that it would be great to have some tests built in that monitor frame rate. It could be as simple as looking at the frame rate delta from previous Azure pipeline runs for now.
