### ISSUE TITLE
Update Project Configurator for Unity 2019/2020

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#7513]
## Describe the bug

Unity 2019.3+ switches to XR plugins instead of "legacy VR supported" feature. The project configurator currently checks for this property.

![image](https://user-images.githubusercontent.com/25975362/76353628-480fc700-62ce-11ea-9aa1-402f22e4d98d.png)

## To reproduce

Open MRTK_Dev in 2019.3

## Expected behavior

Project Configurator for Unity 2019 should be conscious of what XR plugin to auto-enable

## Your setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by MaxWang-MS** [comment]
Will be fixed by #9652.
