### ISSUE TITLE
MixedRealityEditorSettings checks for IsSinglePassInstanced on Android

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#7518]
## Describe the bug

MixedRealityEditorSettings's LogConfigurationWarnings logs a warning on Android because on Android you cannot use Single Pass Instanced (at least not in Unity 2018.4.15.f1).
Additionally, the recommended action in the Optimize Window provides this changes, but it's getting reverted of course.

## To reproduce

1. switch to android
2. watch the console

## Expected behavior

Optimization should be satisfied with single pass on android

## Your setup (please complete the following information)

- Unity Version 2018.4.15f1
- MRTK Version mrtk_development

## Target platform (please complete the following information)

- Editor

**Comment by SimonDarksideJ** [comment]
Is this more likely a unity bug, or do you feel there is some setting that needs to be altered for Android/Quest builds @Alexees

**Comment by Alexees** [comment]
@SimonDarksideJ if you check the Stereo Rendering Mode for Android, there is simply no Single Pass Instanced option

**Comment by SimonDarksideJ** [comment]
So what in your opinion is setting/sending a single passed option?  Is it something in the MRTK?

**Comment by Alexees** [comment]
Here are relevant portions for the problem:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/31f1a04118d3a35a1c7855d0a01034bfa7a0cb77/Assets/MRTK/Core/Inspectors/Setup/MixedRealityEditorSettings.cs#L91-L94

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/31f1a04118d3a35a1c7855d0a01034bfa7a0cb77/Assets/MRTK/Core/Utilities/Editor/MixedRealityOptimizeUtils.cs#L13-L16

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/31f1a04118d3a35a1c7855d0a01034bfa7a0cb77/Assets/MRTK/Tools/OptimizeWindow/MixedRealityOptimizeWindow.cs#L473-L490

All these would need to accommodate to Androids lack of instanced rendering

**Comment by SimonDarksideJ** [comment]
Right I see the problem, this is mainly due to the focus of the MRTK being on the HL2 platform as all of those functions expect UWP to top be the platform.

Although, they don't look like they are actually changing anything, so likely it's just a spurious error you should be able to ignore and shouldn't affect your project.

You can probably update your local code to add "#if !UNITY_ANDROID" around the debug messages if you don't want to see them.

**Comment by keveleigh** [comment]
Thanks for the heads up! @davidkline-ms, something to keep an eye on as you're working on Oculus Quest support.

**Comment by Alexees** [comment]
I read a bit about this and got a but confused about what devices support what. According to this page, Android devices supporting the MultiView Extension support Single Pass Instancing:
https://docs.unity3d.com/Manual/SinglePassInstancing.html

This post is talking about it, but not about which devices it does support:
https://blogs.unity3d.com/2017/11/21/how-to-maximize-ar-and-vr-performance-with-advanced-stereo-rendering/

And then there is this one only mentioning Single-Pass Multi-View, which seems to be yet another rendering technique:
https://docs.unity3d.com/Packages/com.unity.xr.oculus@1.2/manual/index.html

**Comment by Alexees** [comment]
There is also a problem with Unity itself.
Since the PlayerSettings.stereoRenderingPath seems to be a cross platform setting, selecting the Android tab is enough to revert it to Single Pass, because of the lack of Android supporting it. I guess that's a Unity 2018 problem.
Nevertheless, The optimization window should probably set some "remember that setting" flag and keep it updated whenever it's lost.

I did not find a property that told me which PlayerSettings tab was highlighted or if it was switched. If any of the two were possible one could deal with this. But at the moment you have to remember to not switch to Android unless settings SinglePassInstanced again afterwards.
