### ISSUE TITLE
Boundary System causes the stationary guardian of the Oculus Quest to stay

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#7519]
## Describe the bug

When launching the default MRTK (also profile) on the Oculus Quest while using the stationary bounds, the guardian stays active until you go to the shell and back into the game again.
this is caused by:
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/31f1a04118d3a35a1c7855d0a01034bfa7a0cb77/Assets/MRTK/Services/BoundarySystem/XR2018/MixedRealityBoundarySystem.cs#L39

I could not find any documentation about this call online. @StephenHodgson do you know something? I found your documentation about that experimental namspace.
What's the call for? can it be removed? can it be disabled on Android?

## To reproduce

1. Build an empty scene with MRKT default to the quest
2. Make sure your bounds are stationary and launch (guardian stays visible)
3. remove that call and launch again (bounds are gone and only visible when reaching out to it)

## Expected behavior

The guardian disappears from the beginning like it normally would

## Your setup (please complete the following information)

- Unity Version 2018.4.15f1
- MRKT Version mrtk_development

## Target platform (please complete the following information)

- Oculus Quest

**Comment by keveleigh** [comment]
Ah interesting! @davidkline-ms, I wonder if we can remove this call and let each device manage the visibility of its boundary on the OS level instead of forcing it on. I'm not sure if this does anything on WMR. Do you remember why it was hardcoded to `true`? Looks like it was configurable in the boundary profile before https://github.com/microsoft/MixedRealityToolkit-Unity/pull/2542/.

**Comment by davidkline-ms** [comment]
I vaguely recall needing to add that back around beta 1. I'll investigate and see about turning that flag off.

**Comment by keveleigh** [comment]
Fixed via #7904
