### ISSUE TITLE
How can I control Spatial Awareness System?

### ISSUE THREAD

**Issue by Jun-Hyung348** [microsoft/MixedRealityToolkit-Unity#7520]
## Describe the problem

I want to control Spatial awareness system in unity. When I operate on HL1, Frame is so low. So I can't see anything in HL1.
How can I increase our frame in HL1?
Also, When spatial awareness system is operated in HL1, we want to recognize only one time.
So I changed update interval in Spatial Awareness System Setting. But nothing changed. 

## Describe the solution you'd like
![inspector](https://user-images.githubusercontent.com/55191549/76414252-46cbc080-63da-11ea-9811-5b5b37b9637c.PNG)

When operating hololens, we want to recognize real-world just one time.

**Comment by Troy-Ferrell** [comment]
Hi @Jun-Hyung348 , I am not sure what particullary you are asking. What frame is slow? Do you mean framerate?

You can start and stop spatial awareness for an observer via:
```C#
// Get the first Mesh Observer available, generally we have only one registered
var observer = CoreServices.GetSpatialAwarenessSystemDataProvider<IMixedRealitySpatialAwarenessMeshObserver>();

// Suspends observation of spatial mesh data
observer.Suspend();

// Resumes observation of spatial mesh data
observer.Resume();
```

FYI there is documentation here for Spatial Awareness control at runtime:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SpatialAwareness/SpatialAwarenessGettingStarted.html

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SpatialAwareness/UsageGuide.html

**Comment by cre8ivepark** [comment]
And please make sure to set 'Release' or 'Master' for the deployment. 'Debug' build is slow.
![2020-03-12 20_34_30-MixedRealityToolkit - Microsoft Visual Studio](https://user-images.githubusercontent.com/13754172/76587385-e8b5e080-64a0-11ea-9582-a3005dc04443.png)

**Comment by yuhe0925** [comment]
> Hi @Jun-Hyung348 , I am not sure what particullary you are asking. What frame is slow? Do you mean framerate?
> 
> You can start and stop spatial awareness for an observer via:
> 
> ```cs
> // Get the first Mesh Observer available, generally we have only one registered
> var observer = CoreServices.GetSpatialAwarenessSystemDataProvider<IMixedRealitySpatialAwarenessMeshObserver>();
> 
> // Suspends observation of spatial mesh data
> observer.Suspend();
> 
> // Resumes observation of spatial mesh data
> observer.Resume();
> ```
> 
> FYI there is documentation here for Spatial Awareness control at runtime:
> 
> https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SpatialAwareness/SpatialAwarenessGettingStarted.html
> 
> https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SpatialAwareness/UsageGuide.html

'CoreServices' does not contain a definition for 'GetSpatialAwarenessSystemDataProvider'

using 2.3 package, I think the document is outdated

**Comment by keveleigh** [comment]
> 'CoreServices' does not contain a definition for 'GetSpatialAwarenessSystemDataProvider'
>
> using 2.3 package, I think the document is outdated

@yuhe0925 Ah yeah, looks like that was added in MRTK 2.4. Have you been able to update your version and resolve this issue?

**Comment by polar-kev** [comment]
Hi @Jun-Hyung348 and @yuhe0925, since we haven't heard back from you, I'm going to assume the solutions provided worked. Please reopen this issue if that is not the case.
