### ISSUE TITLE
Reset Interaction Mappings Button for supported Controller definitions

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#7521]
## Describe the problem

When altering the controller mappings for supported controllers in the inspector, there is no way to reset them.
Only the two Generic Open VR Hand Controller do have such a button.

## Describe the solution you'd like

A button within the Input Action Assignment Window that resets Input Actions

![image](https://user-images.githubusercontent.com/32508825/76427959-51239580-63ad-11ea-9719-906447f7a554.png)

## Describe alternatives you've considered

Since my use case is keeping coded actions instead of being able to set them in the inspector, I tried fiddling with the MRTK ->Utilities -> Update -> Controller Mapping Profiles, but there's no good way to distinguish between actions you want to keep and those you want to discard.

**Comment by polar-kev** [comment]
Going to keep iterating on the best possible way to implement this. Removing from mrtk 2.6 milestone.
