### ISSUE TITLE
Extension service creator tool defaults to a null path if Generated/Extensions does not previously exist

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#7530]
Starting in MRTK 2.4 (mrtk_development branch), the extension service creator tool creates extensions in the MixedRealityToolkit.Generated/Extensions folder by default.

If the folder does not exist when the tool is run, it gets created but the wizard is set to TargetPath == null.

Re-running the tool allows the wizard to find the folder and function appropriately,

**Comment by wiwei** [comment]
@davidkline-ms can you add some more details on how to hit this (i.e. repro instructions) so that this could be sharded out with others?
