### ISSUE TITLE
Freezing Hand Rays on Hololens 2

### ISSUE THREAD

**Issue by wozniakm93** [microsoft/MixedRealityToolkit-Unity#7547]
Hi!
I have problem with freezing Hand Rays once the app is minimized :
1. Put hand in front of camera so Hand Ray is visualized
2. Keeping it still visible click on "Windows" button on your hand so main menu shows up
3. Go to "All Apps" and open e.g "Settings" (dont click "Home" button)
4. Hand Ray get "frozen", my app is minimized, and "Settings" app is displayed.
5. Click on "X" in settings to close it
6. I am back in my app but Hand Ray visualization which was frozen is still here but when I put hand in front of camera I control another instance of Hand Ray (the old "frozen" is not usable but still visible in space).

When I performed same steps on some example scene from MixedReality Toolkit  (MRTKExamplesHub scene) it looks like the app is never  minimized and the bug described above with Hand Rays doesn't happen. I would like the same behavior for my app.

Question: Are there some sort of settings to configure for my app so it never gets minimized? Or if you have some different solution for that problem please let me know!

Unity Version: 2019.3.3f1
MRTK 2.0

Target Platform: Hololens 2

Thanks in advance for help  :)

**Comment by keveleigh** [comment]
One thing you can try is to set the Run in Background setting in the Unity player settings for UWP.
Though, I thought we had fixed some of the app pausing and clean-up issues in recent versions of Unity and MRTK.
When you say "minimized", do you mean it disappears, or something else?

**Comment by wozniakm93** [comment]
When I say it is "minimized" I mean it disappears but I can go back to it
and resume it.
I confirm that setting up "Run in Background" fixed the issue. Thanks!

Kind Regards,
Mateusz Woźniak


śr., 18 mar 2020 o 20:10 Kurtis <notifications@github.com> napisał(a):
