### ISSUE TITLE
ProgressIndicatorOrbsRotator animation get stuck after the first Close

### ISSUE THREAD

**Issue by Merichbier** [microsoft/MixedRealityToolkit-Unity#7560]
## Describe the bug

when using the ProgressIndicatorOrbsRotator prefab, if we show the progress bar several time using the OpenAsync and CloseAsync function, the animation is only shown on the first run.

It seems that this comes from the hasAnimationFinished preoperty which is set to true when CloseAsync function is called, but is not reset to false in OpenAsync.

## To reproduce

Add the ProgressIndicatorOrbsRotator prefab to you scene.

Call OpenAsync, and then after some delay CloseAsync.

Call OpenAsync a scond time. The animation doesn't run.

## Expected behavior

The animation should run multiple times

## Your setup (please complete the following information)

- Unity Version 2019.3.1f
- MRTK Version 2.3.0

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

Do I miss use the prefab ? If yes what should be the proper way to use it ?

Thanks

**Comment by Railboy** [comment]
>Do I miss use the prefab ? If yes what should be the proper way to use it ?

This is a bug, it's been fixed in #7561
