### ISSUE TITLE
Need a constant repaint of Services inspectors

### ISSUE THREAD

**Issue by raggnic** [microsoft/MixedRealityToolkit-Unity#7587]
## Describe the bug
Services inspectors are a good debug tool in editor. But as it is there's no way to have inspectors update at each frame. 

## To reproduce

1. Open InteractablesExamples Scene
2. Enable the Services Inspectors in MRTK profile (editor tab)
3. Switch to play mode
4. Select Focus provider inspector under MRTK object
4. in Game move the hand pointer on different objects. Focus provider don't update unless Play mode is paused, or mouse hovers inspector.

## Expected behavior
At times it is valuable to have frequent update on custom inspectors, such as Focus providers to be able to use them efficiently. 
The following can be added in ServiceFacadeInspector for a quick workaround

`        public override bool RequiresConstantRepaint()
        {
            return true;
        }
`

It may have an impact on editor performance so maybe it could be an option next to the checkbox that enables Service Inspectors?

## Setup
- Unity  2019.3.6
- MRTK v2.3

**Comment by keveleigh** [comment]
Is this the same as or related to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5991?

**Comment by davidkline-ms** [comment]
Looks related.

**Comment by Railboy** [comment]
I've implemented this in a private branch and it works. Performance impact is negligible.
