### ISSUE TITLE
Instaling MRTK after StreamVR Plugin causes a compile error.

### ISSUE THREAD

**Issue by torikasyu** [microsoft/MixedRealityToolkit-Unity#7588]
## Describe the bug

When instaling MRTK after SteamVR Plugin, existing openvr_api will be overridden and causes a compile error.

## To reproduce

1. Install SteamVR Plugin
2. Install MRTK Foundation.
3. Many compile errors.

## Screenshots

![image](https://user-images.githubusercontent.com/5829873/77548931-8cb47880-6ef2-11ea-8ee2-29ee5251698d.png)

## Your setup (please complete the following information)

- Unity 2019.1.14f1
- MRTK v2.3
- StreamVR Plugin v2.5.0

## Target platform (please complete the following information)

- HoloLens 2
- OpenVR

## Additional context

- Assets/SteamVR/Plugins/openvr_api.cs
- MixedRealityToolkit.Providers/OpenVR/Headers/openvr_api.cs

Their paths are different, but they have the same GUID.
UnityPackage has a tendency to override the same GUID regardless of the path.
So,I think the GUID of openvr_api.cs included in MRTK needs to be changed.

regards.

**Comment by keveleigh** [comment]
>but they have the same GUID.

Ah shoot, I thought I had changed this. I'll update

**Comment by keveleigh** [comment]
Though, what do the compile errors look like? I wouldn't expect that out of a GUID clash.

Is it actually because two of the same script exist?

**Comment by eusebiu** [comment]
Still happens for SteamVR 1.2.3. The errors now are:
Assets\MixedRealityToolkit.Providers\OpenVR\OpenVRRenderModel.cs(10,45): error CS0234: The type or namespace name 'Headers' does not exist in the namespace 'Microsoft.MixedReality.Toolkit.OpenVR' (are you missing an assembly reference?)
Assets\MixedRealityToolkit.Providers\OpenVR\OpenVRRenderModel.cs(235,45): error CS0246: The type or namespace name 'CVRRenderModels' could not be found (are you missing a using directive or an assembly reference?)
...

**Comment by keveleigh** [comment]
@eusebiu Which version of MRTK were you using? This should be resolved in our upcoming 2.4 release.

**Comment by eusebiu** [comment]
> @eusebiu Which version of MRTK were you using? This should be resolved in our upcoming 2.4 release.

2.3.0
