### ISSUE TITLE
How could we delete all the anchors inside the room on the server(clear the room)?

### ISSUE THREAD

**Issue by EvgeniiKramzyuk** [Microsoft/MixedRealityToolkit-Unity#759]
How could we delete all the anchors inside the room on the server(clear the room) when it's connected to the server (SharingService)? 
When we try to import the anchor from the room all the anchors are uploaded (WorldAnchorTransferBatch.ImportAsync). It's just wasting of time. I need just one anchor. How can I clear the room of the anchors or send the request to get the particular anchor?

**Comment by StephenHodgson** [comment]
Have you tried out my recent PR for addressing this?

https://github.com/Microsoft/HoloToolkit-Unity/pull/742

**Comment by EvgeniiKramzyuk** [comment]
Not yet in the workplace. This will definitely help remove anchors from the server?

**Comment by StephenHodgson** [comment]
Good point. I'll make sure to add that.

**Comment by StephenHodgson** [comment]
@EvgeniiKramzyuk, I don't think there's currently any way to remove an anchor from the room in the sharing service.  That would have to be updated in the main HoloToolkit.

**Comment by EvgeniiKramzyuk** [comment]
The fact is that I need the same room.

**Comment by StephenHodgson** [comment]
Currently the Sharing Service does not support that.

**Comment by StephenHodgson** [comment]
If you're just trying to get a single anchor you could always get the anchor name and just download the single one. Check out the InportExportAncorManager class for an example of this.

```
XString roomAnchorId = SharingStage.Instance.CurrentRoom.GetAnchorName("MyAnchor");
roomManager.DownloadAnchor(SharingStage.Instance.CurrentRoom, roomAnchorId.GetString());
```

**Comment by EvgeniiKramzyuk** [comment]
Thank, I'll try it

**Comment by EvgeniiKramzyuk** [comment]
@StephenHodgson This method does not help.

> XString roomAnchorId = SharingStage.Instance.CurrentRoom.GetAnchorName("MyAnchor");
> if(roomAnchorId != null)
> {
>     roomManager.DownloadAnchor(SharingStage.Instance.CurrentRoom, roomAnchorId.GetString());
> }

If there is an anchor in room 1, then I event RoomManagerCallbacks_AnchorsDownloaded shows 800.000 bytes (approximately).
And if there are 10-12 anchors, then it shows 11.000.000 bytes (approximately).

```
private void RoomManagerCallbacks_AnchorsDownloaded(bool successful, AnchorDownloadRequest request, XString failureReason)
    {
        // If we downloaded anchor data successfully we should import the data.
        if (successful)
        {
            int datasize = request.GetDataSize();
            Debug.Log(datasize + " bytes ");
            rawAnchorData = new byte[datasize];
            request.GetData(rawAnchorData, datasize);
            CurrentState = ImportExportState.DataReady;
        }
        else
        {
            // If we failed, we can ask for the data again.
            box.GetComponent<TextMesh>().text += "\n" + "Anchor DL failed " + failureReason;
            Debug.Log("Anchor DL failed " + failureReason);
            MakeAnchorDataRequest();
        }
    }
```

**Comment by StephenHodgson** [comment]
I suggest opening an issue on the main [MixedRealityToolkitRepo](https://github.com/Microsoft/MixedRealityToolkit) addressing this enhancement to the sharing service
