### ISSUE TITLE
PinchSlider

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#7593]
## Describe the bug

Yes, I kept the title that short because it concerns the whole thing any a lot of ways. Needs overhaul urently.

- Changing any value on the PinchSlider does not change any of the visuals
- Changing axis once moves the tickmarks onto the line
- Changing to Z Axis even moves the Slider to the side of the line
- You cannot define the amount of TickMarks (automatically incrementing/ decrementing)
- You cannot define a prefab used for your TickMarks/Slidebar... 
- You can't toggle snap/smooth sliding
- And this one #6758
- ...

I really wanted to use it, but it seems it was created to work and then dropped half baked.

P.S.: Why is the axis dropdown there? Rotating the whole thing even allows for any angle. There is a lot of code that alters the child gameobjects, which is also broken

It would make a lot more sense if you had just the slider gameobject, assigned it 3 prefabs (slider, bar and tickmark) and it would assemble itself, maybe even hide the gameobjects in the hierarchy. Without the need for an axis, you can rotate it. Alter values in the inspector and it will adjust...

## To reproduce

1. Just use it

## Expected behavior

Everything mentioned above working

## Your setup (please complete the following information)

- Unity Version 2018.4.15f1
- MRTK Version mrtk_development

## Target platform (please complete the following information)

- Editor

**Comment by cre8ivepark** [comment]
@julenka @thalbern @Cameron-Micka for visibility

**Comment by CDiaz-MS** [comment]
Here is what changing the axis looks like for the sliders, the tick marks move onto the line as @Alexees pointed out:
![SliderIssue](https://user-images.githubusercontent.com/53493796/84078894-87fa4f00-a98e-11ea-838a-b28ce9e8c212.gif)

**Comment by Zee2** [comment]
Slider is much improved in MRTK3 and takes into account basically all of these suggestions! @Alexees , take a peek and see if you like it :) All of the slider interactivity/logic is separated from visuals, you can replace any part of it, rotate it any which way you like, flip the axes, and use Canvas layout. We're still missing a few things (like tickmarks) but we're aiming for UnityUI parity at least for now.

**Comment by Alexees** [comment]
@Zee2 sorry to disappoint you, but I'm not working on a VR project anymore, so no time to check it out
