### ISSUE TITLE
Unity error crashes when building the MRTK

### ISSUE THREAD

**Issue by NSudharsan** [microsoft/MixedRealityToolkit-Unity#7598]
## Describe the bug

Unity editor crashes sometimes because of a font asset corrupted error in the MRTK.  The build gets stuck especially at the point where it has to build the font assets. I'm using Unity 2019.3.1f1 and MRTK V2.3. I have also seen a similar error with the TextMeshPro Assets.  The only thing that fixed this was erasing the MRTK packages and importing them again.

## To reproduce
Happens sometimes... so don't know what the exact steps to reproduce are. However, you could try the editor version 2019.3.1f1 and importing the Foundation package of MRTK V2.3
Also error mostly occurs when I create my own customized profiles for HoloLens2. Cleaning the project also does not help. Deleting the library also does not help. 

## Your setup (please complete the following information)

- Unity Version 2019.3.1f1
- MRTK Version V2.3

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
Are you able to grab the logs immediately after the crash and post them here? You don't have to post the whole file, but if you could copy over the relevant crash stack, that'd be helpful! I haven't seen this repro before.

https://docs.unity3d.com/Manual/LogFiles.html

**Comment by NSudharsan** [comment]
Hi , if it happens again- I’ll make Sure to do that. Could you tell me where I could get the logs from though? Not done this before. 
Best, Nischita 

Sent on the go, please excuse brevities

**Comment by keveleigh** [comment]
Yep! You should be able to find the path from Window > General > Console in the editor and select Open Editor Log from the Console window menu.

Depending on your OS, the path can be found at https://docs.unity3d.com/Manual/LogFiles.html too, under Editor.

**Comment by NSudharsan** [comment]
Thanks! Will do. 

Sent on the go, please excuse brevities
