### ISSUE TITLE
MRTK Sharing Service Extensions

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedRealityToolkit-Unity#7599]
## Describe the problem

MRTK needs a set of sharing services for networked apps.

## Describe the solution you'd like

# ISharingService
A bare-bones networking service. Initially built on Photon but the interface should support any back-end. Some requirements:
 - Connects to other devices in a lobby or room
 - Can send / receive bytes to / from connected devices
 - Allows devices to specify which types of data they want to receive
 - Implementation compiles and fails gracefully even if Photon is not installed

# Additional Services
A more advanced set of extensions built on the `ISharingService` extension:
### ITimeSyncService
Synchronizes time between connected devices.

### IStateSyncService
Efficient, error-free state synchronization. Some requirements:
 - Makes iterating through shared states easy
 - Synchronizes complete app state when new devices connect
 - Can handle merging conflicting states
 - Uses JsonUtility out of the box but lets users implement custom binary / JSON / BSON serialization methods
 - Provides optional components to automate detection / application of state changes to objects in scene

### IUserSyncService
A user management system built on `IStateSyncService` - some requirements:
 - Can assign multiple devices to single 'users' (eg, a single user wearing a HoloLens while using a phone for input)
 - Allows devs to define what devices 'compose' a user as well as what transforms should be represented / synchronized between devices
 - Simulates absent users for testing purposes
 - Reports user readiness for custom lobby systems

### IStageSyncService
A stage synchronization system built on `IStateSyncService` and `IUserSyncService` that guides users through pre-defined stages of an app. Examples would be a game with connect / loadout / gameplay / scoring stages or a showcase app with lots of slides. Some requirements:
 - Synchronizes scene loading among multiple users
 - Smoothly transitions between stages / scenes
 - Starting / stopping / skipping stages etc.

## Describe alternatives you've considered

Continue to use bespoke Photon solutions for each app.

## Additional context

These proposals are based on implementations used for sharing apps developed internally. A while ago we opened a PR to incorporate a Photon-based version of a state sharing extension similar to IStateSyncService. That version relied on PhotonView components and didn't mesh well with MRTK service architecture, so it was closed without being merged. The services described would not rely on scene assets to function.

**Comment by Cameron-Micka** [comment]
This is long overdue, thank you for purposing/making this!

Some other ideas off the top of my head (some of these might be more appropriate for the transport layer):

- Works over LAN and "the internet"
- Allows me to run multiple instances of the app locally (on a dev PC)
- Position & rotation extrapolation utilities
- "Gracefully" handles version mismatch communication
- Utilities for data compression
- Voice over IP (I've seen good results with the Opus audio codec)
- State serialization and recovery from disk

Many of these aren't needed for the first release, but adding them for tracking purposes.

**Comment by keveleigh** [comment]
Linking https://github.com/microsoft/MixedRealityToolkit-Unity/issues/3313 for some previous MRTK conversation around this.

**Comment by Railboy** [comment]
Related discussion: #3210

**Comment by mr0ng** [comment]
@Railboy What do you propose for addressing this issue in the MRTK? In the [HoloLens 2 tutorial sharing chapters](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch1), photon is used and a rudimentary abstraction was implemented, with the intention that other sharing platforms could eventually used should the reader decide.

**Comment by Railboy** [comment]
@mr0ng I'm not sure what you're asking, could you clarify your question?

**Comment by jbienzms** [comment]
Correct me if I'm wrong @mr0ng, but what I believe he's asking is if someone should:

1. Replace the [Sharing Capabilities sample](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch1) on docs.microsoft.com to use these new capabilities when they're complete.

or

2. Add an alternative example on docs.microsoft.com that leverages these new capabilities.

**Comment by Zee2** [comment]
The comments on #7613 are relevant here; currently, our recommendation is to explore the [Microsoft Mesh](https://www.microsoft.com/en-us/mesh) solutions for multi-party XR experiences.
