### ISSUE TITLE
ObjectManipulation ignores constraints when using a Rigidbody

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#7603]
## Describe the bug

ObjectManipulation provides the ability to add constraint components. This works. Until you add a rigidbody. The rigidbody plain ignores the constraints.

## To reproduce

1. Add a rigidbody to whatever boundingbox demo and move it along a static collider

## Expected behavior

Having a Rigidbody or not should always use the constraints, especially for consistency reasons

## Your setup (please complete the following information)

- Unity Version  2018.4.15f1
- MRTK Version mrtk_development

## Target platform (please complete the following information)

- Editor

**Comment by cre8ivepark** [comment]
Hi @Alexees I think new ObjectManipulator(refactored version of ManipulationHandler) and AdjustBox(refactored version of BoundingBox) resolved this issue.
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_ObjectManipulator.html?q=objectmanipulator
@thalbern ?

**Comment by Alexees** [comment]
Do you mean BoundsControl from #5340 ?
