### ISSUE TITLE
error CS0433: The type 'ICloneable' exists in both 'Microsoft.Windows.MixedReality.DotNetWinRT, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

### ISSUE THREAD

**Issue by tjhappy** [microsoft/MixedRealityToolkit-Unity#7616]
## Describe the bug

I use websocket in bestHTTP to send messages. But I get the following error during compilation. How can I solve it?

error:
Assets\Best HTTP (Pro)\BestHTTP\SecureProtocol\x509\store\IX509Selector.cs(11,11): error CS0433: The type 'ICloneable' exists in both 'Microsoft.Windows.MixedReality.DotNetWinRT, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

IX509Selector.cs
code:

#if !BESTHTTP_DISABLE_ALTERNATE_SSL && (!UNITY_WEBGL || UNITY_EDITOR)
#pragma warning disable

// compile with: /reference:Microsoft.Windows.MixedReality.DotNetWinRT.dll /reference:System=netstandard.dll
using System;

namespace BestHTTP.SecureProtocol.Org.BouncyCastle.X509.Store
{
    public interface IX509Selector
#if !(SILVERLIGHT || PORTABLE || NETFX_CORE)
        : ICloneable
#endif
    {
#if SILVERLIGHT || PORTABLE || NETFX_CORE
        object Clone();
#endif
        bool Match(object obj);
    }
}
#pragma warning restore
#endif

## Your setup (please complete the following information)

- Unity Version . 2018.4.2f1
- MRTK Version v2.2
Microsoft Mixed Reality Toolkit 2.2.0
## Target platform (please complete the following information)

 HoloLens 2

**Comment by keveleigh** [comment]
@dfields-msft, have you seen this?

**Comment by tjhappy** [comment]
Can someone help me?

**Comment by dfields-msft** [comment]
Sorry for the delay responding, @tjhappy - we took this offline and diagnosed a problem with the Microsoft.Windows.MixedReality.DotnetWinRT package. A new version will be published shortly with a fix. Thanks for your patience!

**Comment by dfields-msft** [comment]
The fixed version is published here, please update your package and let us know if it resolves your issue :
https://www.nuget.org/packages/Microsoft.Windows.MixedReality.DotNetWinRT

**Comment by tjhappy** [comment]
Great. After theGreat. After the update, the problem has been solved. Thank you update, the problem has been solved. Thank you
