### ISSUE TITLE
A UI Keyboard that works with WMR/Desktop/Hololens alike

### ISSUE THREAD

**Issue by ajnaduvil** [microsoft/MixedRealityToolkit-Unity#7626]
## Describe the problem
MRTK doesn't provide a  UI based keyboard. I am having trouble integrating a keyboard solution that works with WMR headset as well as hololens and editor.

## Describe the solution you'd like
A customizable UI based keyboard that works with UGUI as well as TextMeshPro. Similar to what we had in Holotoolkit

**Comment by keveleigh** [comment]
Does the experimental NonNative Keyboard fit your need? https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk_development/Assets/MRTK/SDK/Experimental/NonNativeKeyboard
