### ISSUE TITLE
Object selection behavior with the sphere pointer is ill-defined for overlapping objects

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#7629]
## Describe the bug
Currently when 2 grabbable objects are overlapping, the object actually grabbed by the sphere pointer is determined by order of instantiation, it will always grab the object that was created later. This behavior is not quite intuitive to the user, and work needs to be done to improve the user experience when they are trying to grab overlapping 3d objects.

## To reproduce

1. Create an example scene, and place two objects with Manipulation Handlers/NearInteractionTouchables in it.
2. Configure the scene's pointers to have a single SpherePointer
3. Set up the objects so that they overlap each other. Make the object that was instantiated first smaller so its completely covered by the other object.
4. Attempt to grab the smaller object and notice that it's never prioritized to be grabbable
5. Repeat these steps making the later instantiated object the smaller one and see that its grabbable

## Expected behavior
We need to settle on a approach that is comfortable for users and make sure that they know what object they are selecting in these edge cases

## Your setup (please complete the following information)

- Unity Version 2018.4.20f1

**Comment by RogPodge** [comment]
This issue is still relevant as of this writing. Marking it for MRTK 2.6.0 as dealing with potentially overlapping objects is a common situation that we can expect users to encounter.

**Comment by davidkline-ms** [comment]
@RogPodge, do you expect this to make 2.6? If not, is it a candidate for a 2.6.1?

**Comment by RogPodge** [comment]
Push it out of 2.6 for now. I'll try to free up cycles to tackle this in 2.6.1 since it's been on the backlog for a bit.

**Comment by RogPodge** [comment]
Updating this issue to reflect with thoughts on future implementation. At the moment, this problem does not have a good solution, since both ClosestPoint and ClosestPointOnBounds will return the pointer's position when it is located inside of the collider. To implement this solution, we'd need to keep track of the "layers" of colliders we pass through and be sure to keep track of the latest one, something that is not readily achievable with our current implementation that relies on multiple OverlapSphere calls.

Continuing to keep this open to ensure that we solve this in MRTK 3.x, where we're looking to move to a more collider/trigger based implementation for our near pointers.
