### ISSUE TITLE
Detect location in 3D space using built-in fiducial marker support

### ISSUE THREAD

**Issue by f-strieg** [Microsoft/MixedRealityToolkit-Unity#763]
Hi all,

this is not exactly an issue but I found following text in the documentation:

> Visual Pairing
> 
> Connect devices just by looking at them
> 
> One device displays a QR code with connection info and security code
> Other device sees QR code, connects, and validates with security code
> **Can also detect location in 3D space using built-in fiducial marker support**

That would be great because I would not be forced to use Vuforia or any of those AR plattforms.
However I can not find any other informations on  #this in the document or in code.
I would be very thankful for some tipps where to find this functionality, if its really built-in.

Many thanks

**Comment by StephenHodgson** [comment]
I think this documentation has been depreciated. That stuff has been removed from the [main HoloToolkit](https://github.com/Microsoft/HoloToolkit/pull/69)

**Comment by XinliZ** [comment]
Do we know where did these functions landed to? They are kind of what we need as well.

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
