### ISSUE TITLE
ManualGazeControl arrow keys not working

### ISSUE THREAD

**Issue by MartinOrtiz** [microsoft/MixedRealityToolkit-Unity#7636]
In inspector for camera -> Manual Gaze Control -> Keyboard,Supported is checked and enabled.

 I run more or less an empty  scene with a plane and one 3D object.
The mouse look works fine, but the arrow keys don't work

These are all initialized properly and are not null
        public AxisController KeyboardXYRotationAxisControl;
        public AxisController KeyboardXZRotationAxisControl;
        public AxisController KeyboardXYTranslationAxisControl;
        public AxisController KeyboardXZTranslationAxisControl;

**Comment by keveleigh** [comment]
Is this for the HoloToolkit component? `ManualGazeControl` has been replaced with `ManualCameraControl` and the input simulation service in MRTK.

We don't really support the HoloToolkit anymore. Offhand, I can't think of a reason why ManualGazeControl shouldn't be working the way you describe. I'd say just make sure the `AxisController`s are properly assigned and also properly set (check that the `AxisType` is what you expect, etc)

**Comment by MartinOrtiz** [comment]
I am switching back and forth between HoloToolkit and the MRTK, because all the e-books only cover HoloToolKit. Plus I wanted to use it outside of both, that is, in a regular project (because the mouse look is nicely done, and if I could just get the moving part working, I would be happy).

It is very difficult to debug, because the debugging process intercepts the keystrokes as well inside of VS. The AxisType = mouse.... (it is initialized to it).
Even if I disable the mouse support, and only enable the key support, it's still "mouse".''

All the AxisControllers are initialized....at first, I did not do that, but then I fixed it...and again, the mouse looking part works great,....love it....but there is no joy in HoloLand because the arrow keys do not work....

**Comment by MartinOrtiz** [comment]
Do I have to do anything or modify anything as far as input in the Unity 3D project settings?

**Comment by keveleigh** [comment]
>The AxisType = mouse.... (it is initialized to it)

Sounds like you might need to update the `KeyboardXYRotationAxisControl` etc to be one of the keyboard settings instead of mouse.

ManualCameraControl.unity should be set up properly, to give you an idea.

**Comment by MartinOrtiz** [comment]
How do I move forward or backward with just the mouse? 
I can look around with mouse, but not move with mouse, aren't I supposed to be able to move with the mouse as well?

**Comment by MartinOrtiz** [comment]
`            if (KeyboardSupported)
            {
,,,,................
            Vector3 keyboardXYTranslate = KeyboardXYTranslationAxisControl.GetDisplacementVector3();
`,,,,................
}

**Comment by MartinOrtiz** [comment]
Ugh, I accidentally "closed", how do I unclose?

**Comment by MartinOrtiz** [comment]
(thx)
keyboardXYTranslate  always returns back (0.0, 0.0, 0.0{

**Comment by MartinOrtiz** [comment]
axisType = AxisType.Mouse;
axisType is initialize to mouse, and never re-assigned to anything else...
What should I use to test it with keyboard?
axisType = AxisType.Keyboard8426;    <---- should I try this?

**Comment by keveleigh** [comment]
I'm not sure about moving with the mouse. I don't remember that being supported, but it's been a while since I've look at HTK.

>What should I use to test it with keyboard?
>axisType = AxisType.Keyboard8426; <---- should I try this?

Worth trying! That should use the numpad for movement. I think WASD is an option as well. ManualCameraControl.unity should be set up properly, to give you an idea. Check the keyboard `AxisController`s there.

**Comment by MartinOrtiz** [comment]
I will look at ManualCameraControl

**Comment by MartinOrtiz** [comment]
Yes, MRTK, uses the classic WASD +QE approach.....
In MRTK, the WASD + QE works great, as well at the mouse looking.
Would it be easy to pull out the "gaze" stuff so I could use it in a regular project? (non-AR project)
For HoloToolKit, it looked easy to do that....(except for the arrow key problem)

**Comment by MartinOrtiz** [comment]
OK, I know what's wrong....

**Comment by MartinOrtiz** [comment]
![sc1](https://user-images.githubusercontent.com/11322523/79023655-d5a13980-7b4e-11ea-9fd2-cb1a563ec210.jpg)


<img width="960" alt="sc2" src="https://user-images.githubusercontent.com/11322523/79023671-e0f46500-7b4e-11ea-8125-d1ab709bd71d.png">

**Comment by MartinOrtiz** [comment]
I don't care about using the keyboard for rotations....

But what is the correct settings for the keyboard?

**Comment by MartinOrtiz** [comment]
For the XY and XZ ROTATION, I set the axis types to "none"
<img width="960" alt="sc3" src="https://user-images.githubusercontent.com/11322523/79024308-8d831680-7b50-11ea-9ba5-2c12b7dcbfee.png">

For the XY TRANSLATION I set the axis type to "Keyboard QE"
<img width="960" alt="sc4" src="https://user-images.githubusercontent.com/11322523/79024333-9c69c900-7b50-11ea-9b59-43a73173cc6c.png">

For the XY TRANSLATION I set the axis type to "Keyboard WASD"
<img width="960" alt="sc5" src="https://user-images.githubusercontent.com/11322523/79024341-a12e7d00-7b50-11ea-8561-518cd1404d66.png">

**Comment by MartinOrtiz** [comment]
To go up and/or down I use the "Q" and "E", so that's working now...

The "A" key goes left
The  "D" key goes right
But the "W" and "S" keys go up and down, instead of forward and backward?

**Comment by MartinOrtiz** [comment]
Oops....I double checked...The "Q" and "E" go left and right too, not up and down....

**Comment by MartinOrtiz** [comment]
OK....I think I got it working correctly now...

I had to correct the "Axis 0 Destination" and the "Axis 1 Destination" 
for the XY and XZ translations,.

**Comment by julenka** [comment]
Looks like this has been resolved based on last comment in discussion
