### ISSUE TITLE
BoundingBox deletes NearInteractionGrabbable when BoundsOverride is TRUE

### ISSUE THREAD

**Issue by pampas93** [microsoft/MixedRealityToolkit-Unity#7660]
## Describe the bug

When you add the BoundingBox component to a GameObject, and override the BoundsOverride with it's own BoxCollider, anywhere we call CreateRig(), it deletes the NearInteractionGrabbable component. This spirals down into other problems but, main bug is the above.

## To reproduce

1. Create a cube, and Add the BoundingBox component to it
2. Grab and drop the cube's box collider to the BoundsOverride property of BoundingBox
3. Add another button which basically calls the BoundingBox.CreateRig()
4. Hit play. and you'll see the NearInteractionGrabbable component added.
5. Press the button now (calling CreateRig()) and this deletes the NearInteractionGrabbable component

## Expected behavior

Not deleting the NearInteractionGrabbable component anytime we call CreateRig()

## Test Project to reproduce bug

https://github.com/abhijitsri/UWP-EdgeTest-MRTK/tree/boundingBox-bug
boundingBox-Bug branch

## Your setup (please complete the following information)

- Unity 2018.4.12f1 or 2019.3
- MRTK 2.3

## Target platform (please complete the following information)

- HoloLens 2
- WMR immersive
- OpenVR
- Mostly all of it

**Comment by Pycorax** [comment]
I would also like to add that this is also present in the `BoundsControl` component that is meant to replace this and is extremely frustrating to work with.
