### ISSUE TITLE
Allow customization of configurator defaults

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#7662]
The MRTK configurator today provides sane defaults for most projects getting started - for more advanced projects, however, it can be useful to customize what those defaults should be.

For example, there have been some cases where some projects have seen that msbuild4unity's default behavior (in conjunction with their system) has led to very difficult to reconcile situations (i.e. conflicts with their own build tooling and configuration).

At the same time, having msb4u enabled by default (under WMR) is super helpful for HL2 scenarios (for remoting from Unity).

Given this, this issue tracks making it so that on a project by project basis, you can configure the defaults for the configurator (so that individual contributors to those projects don't blow away the values set manually with the defaults shown.

**Comment by keveleigh** [comment]
Would the end result be different from ignoring / hiding / having some way to tell the configurator to stop trying to change things?
It feels like, if you need to configure the MRTK's configurator, you should just be trusted to set the Unity settings yourself to whichever values you need (which it sounds like has been done already, if there's danger of MRTK blowing away those values).
Is there an issue with the ignore button, which should be check-in-able on a project-by-project basis by checking in ProjectPreferences.asset in MixedRealityToolkit.Generated?

**Comment by wiwei** [comment]
This assumes that everyone running the configurator cares to understand the configuration, vs having it be set up by a person who is initially starting up the project and then sharing the repo with others - I think the min bar here is that for others pulling from the repo (consider someone who doesn't care about the the setup of the project, but just wants to get going with their part), they shouldn't see a dialog because the project has been configured to be different from the defaults (explicitly by the creator of the project)

**Comment by wiwei** [comment]
So yes, if you're an individual starting up a project and looking at things and you want to customize stuff things work fine.

If you're sharing your project and working with others, currently things fall apart in certain scenarios.

**Comment by keveleigh** [comment]
>I think the min bar here is that for others pulling from the repo (consider someone who doesn't care about the the setup of the project, but just wants to get going with their part), they shouldn't see a dialog because the project has been configured to be different from the defaults (explicitly by the creator of the project)

That's the scenario I think is already covered by checking in the ProjectPreferences.asset in MixedRealityToolkit.Generated after clicking "ignore" in the configurator or marking "Ignore settings prompt on startup" in the MRTK Project Settings:

![image](https://user-images.githubusercontent.com/3580640/79288599-04375100-7e7c-11ea-8695-530ad9e0ced9.png)

This gets serialized into that .asset file and can be checked in to the repo for anybody pulling things down.

Note that the "This applies to all projects using the MRTK" part of the tooltip is now incorrect. This used to be stored in the global editor preferences but is now serialized to an asset after https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6315

**Comment by keveleigh** [comment]
Though, if we're finding that that setting isn't being respected, we should definitely fix that!

**Comment by keveleigh** [comment]
I opened https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7665 to improve our wording and some discoverability of this .asset file.

**Comment by wiwei** [comment]
Perfect, yep, I think that the project setting should handle the scenario nicely, closing this out.
