### ISSUE TITLE
UnityUI won't receive input from the user during a session (Intermittent)

### ISSUE THREAD

**Issue by DanCRichards** [microsoft/MixedRealityToolkit-Unity#7663]
## Describe the bug

When a user attempts to interact with UnityUI elements on an MRTK Canvas they are unable to perform the actions expected from Buttons, Dropdowns, Text inputs, etc. 

## To reproduce
- On built applications only (Unity editor works fine)
- Intermittently occurs
- There seems to be a correlation between the problem occurring and fixing/breaking it by rebooting your machine. (_See steps below_)
- When running the application overnight it would not work when leaving the office, but on return, it would work in the morning. See the below point, I believe this is related to the restarting of controllers. 

Steps to reproduce the behaviour:
1. User A performs a build and runs the application
2. User A interacts with a UnityUI object. It works! 
3. User A gives a .zip containing the package installer to another User (B)
4. _User B_ installs and runs the application. 
5. _User B_ is **unable** to interact with UnityUI objects. 
6. _User B_ can restart his machine (potentially more than once)
7. _User B_ is **able** to interact with UnityUI objects. 
8. User A restarts his machine. 
9. User a is **unable** to interact with UnityUI objects. 

Steps to temporarily fix the problem: 
- Consider that there is a correlation between rebooting the machine and the error occurring.
1. When a User A/B has a machine that is _proven_ not to work: turn off your controllers
2. Close the application
3. Start the application
4. Only once the application has started, turn on your controllers
5. The user is able to interact with UnityUI objects. 

Separate detail of problem working
1. When a User has a machine that is _proven_ not to work
2. Leave the application running overnight. 
3. In the morning, attempt to use the UnityUI objects. 
4. It works! 

Separate detail of problem working
1. When a User has a machine that is _proven_ not to work
2. Close the application, do something else whilst observing social distancing rules 😷 
3. Go for a walk from being locked inside all-day 🚶 
4. Start the application without having rebooted your machine
5. It works! 💯 

## Expected behaviour
Interacting with UnityUI objects should work regardless of rebooting your machine, having observed social distancing and going for a walk and restarting your controllers. 

## Screenshots
![image](https://user-images.githubusercontent.com/17732740/79284020-a5bab300-7f0d-11ea-81fe-e8b9cfc6c332.png)
**Image showing the Canvas **

## Your setup (please complete the following information)

![image](https://user-images.githubusercontent.com/17732740/79285677-5d51c400-7f12-11ea-9335-8fdc163e1217.png)
- Lmao I'm usually a Mac user so I'm not certain if I need to redact the ID's 

- Unity Version [e.g. 2019.2.12f1]
- MRTK Version [e.g. v2.3]

## Target platform (please complete the following information)

- HoloLens
- WMR immersive 
Note that most of these problems have been occurring on the WMR immersive. 

## Additional context
 
- This has been occurring on both v2.2 and v2.3
- It's making me go crazy
- The comment about it working overnight, I think that this is simply related to restarting the controllers, but I want to write this issue in extreme detail.

**Comment by davidkline-ms** [comment]
From slack, re: the hand interaction example.

When the application first runs, the UnityUI elements cannot be interacted with, the highlight state cannot be activated when 'hovering' over buttons.
How ever! I pressed the 'Open Edge Browser' button.... I closed the edge browser and now the UnityUI elements work!
