### ISSUE TITLE
add input simulation overlay cheat sheet to show keyboard/mouse commands

### ISSUE THREAD

**Issue by ForrestTrepte** [microsoft/MixedRealityToolkit-Unity#7675]
## Describe the problem

There are [great controls](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSimulation/InputSimulationService.html) for manipulating your simulated view, hands, and eye gaze while testing in the Unity editor. However, there's a *lot* there that isn't immediately intuitive if you take up bringing up, holding, tapping, moving, rotating both hands. I have observed that most people aren't aware of the full set of capabilities, forget how to do them, or don't take the effort to research this in documentation.

## Describe the solution you'd like

1. Ability to quickly toggle on and off an overlay on top of the game window with simple reference info about all the available controls and keys to trigger them. Try to take all the info from [Input Simulation Service](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/InputSimulation/InputSimulationService.html) and condense it down in the clearest way possible.
2. Discoverability for #1. For example, if there's a special key combo to bring up the overlay, how would a new person know to hit that key combo? I'm thinking that, on startup, an overlay message could say something like "Mixed Reality Input Simulation Service: press Ctrl+Shift+I to show quick reference".

Note: I think a key combo like this might be a good solution, but feel free to come up with something better.

**Comment by kianng** [comment]
Love this suggestion! Thanks Forrest!
