### ISSUE TITLE
Failed to build nuget packages

### ISSUE THREAD

**Issue by peted70** [microsoft/MixedRealityToolkit-Unity#7682]
I was following the guide [here](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/MRTKNuGetPackage.html) to build Nuget packages for the toolkit that I can use to debug an Exception coming from the toolkit. When I run the createnugetpackages script it fails with an error:
 
RunUnityTask : Failed to execute Unity Task 'MSBuildGeneration'

## To reproduce

1. Get the source tagged with v.2.3.0
2. run
.\createnugetpackages.ps1 -UnityDirectory "C:\Program Files\Unity\Hub\Editor\2019.2.21f1\Editor" -Version 2.3.2
3. Notice the error in the output
4. Also the log
[Unity.MSBuildGeneration.2.3.2.log](https://github.com/microsoft/MixedRealityToolkit-Unity/files/4494362/Unity.MSBuildGeneration.2.3.2.log)

 has the error:
InvalidOperationException: Can't find an asmdef for project: Unity.ugui

## Expected behavior

No error and nuget packages created.

## Your setup (please complete the following information)

- Unity Version [2019.2.21f1]
- MRTK Version [v2.3.0]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
@CDiaz-MS @davidkline-ms I think you two most recently built NuGet packages locally for testing. Have either of you seen something like this?

**Comment by CDiaz-MS** [comment]
I haven't seen something like this before, but I will test the createnugetpackages script on a recent project and see if there are any issues.

**Comment by CDiaz-MS** [comment]
I was able to repro following the steps above. @davidkline-ms have you seen this before?

**Comment by DaehyunLee** [comment]
experiencing the same issue on 2019.4.9f1 with mrtk releases/2.4.1 branch.

Any updates on this topic?

**Comment by keveleigh** [comment]
I believe this should be fixed due to a fixed quirk on the Unity side plus some changes @MaxWang-MS has made to our project generation steps. We've been successfully using MSBuildGeneration with Unity 2019.4
