### ISSUE TITLE
Use a cone instead of a sphere for grab interactions

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7686]
Break up of #6634  into sub issues

## Describe the bug
MRTK uses a sphere to detect if a grabbable is near the hand, which does not match shell parity. This means the hand can be in front of an object but still grab it.

![image](https://user-images.githubusercontent.com/168492/71216142-97fe6500-226e-11ea-8516-9c0a8184f095.png)

Instead, create a ConePointer which uses a cone instead of a sphere when doing its cast check for grabbables.
![image](https://user-images.githubusercontent.com/168492/71216167-a5b3ea80-226e-11ea-85d1-211eac7eb5be.png)

The default pointer for near grab interactions should use this cone pointer instead of sphere pointer.

**Comment by keveleigh** [comment]
What's the cone pointer's raycast direction relative to? If I turn my hand around towards my face, can I grab that cube? It feels like I should be able to. Same for reaching for something to the left or right of my hand instead of straight ahead according to the direction my body's facing.
