### ISSUE TITLE
Leap Motion Improvements

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#7689]
- [x] Add configurable pinch thresholds

- [x] ~~Add near interaction grab support, currently a grab is only recognized as a pinch~~
The configurable pinch thresholds are used to trigger the grab gesture

- [x] Update documentation with "Configure Pinch Thresholds" section and update screenshots

**Comment by keveleigh** [comment]
I think Leap Motion provides a hand mesh too. Is that in the existing provider, or something we want to add?

**Comment by CDiaz-MS** [comment]
They do have a hand mesh but in Unity it takes the form of a different set of hand prefabs called the rigged hands.  The rigged hands can be used by adding the Leap Hand Model Manager

![image](https://user-images.githubusercontent.com/53493796/79790780-24926000-8301-11ea-86a4-b2a4239f9984.png)

Here is what the rigged hands look like now, but we could just add an option not to render the joint representation if the user wants to use the hand models from leap instead

![LeapRiggedHandMRTK](https://user-images.githubusercontent.com/53493796/79790921-56a3c200-8301-11ea-88b1-ad807e9cecec.gif)
