### ISSUE TITLE
Building for WSA x64 fails due to a missing WSA x64 PlaneFinding.dll

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#769]
Probably related to #746, at least for x64.

**Comment by StephenHodgson** [comment]
Duplicate of https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/629

**Comment by StephenHodgson** [comment]
Closed By https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/dc4375db8643632565fa21c4d21893d7f098a98d
