### ISSUE TITLE
Only list files in migration tool project option that actually can be migrated

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#7690]
## Describe the bug

Atm we're listing all files of the project which is not a great user experience, as it's uncertain to the user if all their files will be affected by the upgrade. 
It would be better to just list the files that actually contain the components we're planning to upgrade. That would also make the list shorter, make it easier to filter files and give a better overview before pressing the migration button. 

## To reproduce

Try the migrate project option on the MRTK project - there's a long list of files shown but actually only one scene gets migrated.

## Expected behavior

Only show upgradeable files in that list.

**Comment by thalbern** [comment]
similar to what is done on deciding if a file is saved or not on migration in this PR https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7688

**Comment by vaoliva** [comment]
Resolved on #7707
