### ISSUE TITLE
Applying HoloToolkit scene and project settings should show proper status in menu items

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#770]
[Migrated from internal feedback 10971165]
"When we use the HoloToolkit menu to setup camera, field of view, etc., please look at what is already set. If it is set, check it in the little menu you show, that way we don't have to remember or wonder if something has been set previously."

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
