### ISSUE TITLE
HandInteractionExample scene bugs

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#7701]
## Describe the bug

- Some broken debug messages
- Overlapping texts on slider values
- Toggle Features Panel button overlaps, the layout needs to be updated with new 'Gaze Source' button

![2020-04-21 09_59_13-Unity 2018 4 21f1 Personal -  PREVIEW PACKAGES IN USE  - HandInteractionExamples](https://user-images.githubusercontent.com/13754172/79896423-35081080-83bd-11ea-96ff-21405a012fcf.png)
![2020-04-21 09_59_05-Unity 2018 4 21f1 Personal -  PREVIEW PACKAGES IN USE  - HandInteractionExamples](https://user-images.githubusercontent.com/13754172/79896429-36393d80-83bd-11ea-97ee-2a3d0a4e8983.png)

**Comment by davidkline-ms** [comment]
Closing per changes in #7703
