### ISSUE TITLE
Hand Menu in 2.4 Update moves forward/backward as I move head side to side

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7706]
## Describe the bug
The larger hand menus introduced in #7365 are quite large, which seems to exacerbate an issue with the hand menu placement algorithm. When the user moves his/her head from side to side, the menu moves considerably forward / backward relative to the user. See in the attached video the z-movement as the head (appearing as a frustrum) rotates.

![hand menu move camera move](https://user-images.githubusercontent.com/168492/79942290-5ac40280-841b-11ea-9f69-ff6398844176.gif)

## To reproduce

1. Play the HandMenuExamples scene in editor over remoting, or on Hololens 2
2. Bring up the large menu 
3. Rotate head from side to side
4. See menu moving foward and backward

## Expected behavior

I would expect the menu to stay still, attached to the hand, as I move my head from side to side

**Comment by julenka** [comment]
I have recorded an input simulation recording that reproduces this issue.

**Comment by wiwei** [comment]
Resolving this because it was fixed by #7716

This wasn't auto-closed because the change wasn't submitted to the default branch (i.e. it went to stabilization, not development)
