### ISSUE TITLE
'Object at index 0 is null' error after hitting play, with custom MRTK pointer profiles

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7713]
## Describe the bug
I am getting the following errors in play mode in my Unity editor, after I have create custom MRTK pointer profile in my scene

```
ArgumentException: Object at index 0 is null
UnityEditor.SerializedObject..ctor (UnityEngine.Object[] objs, UnityEngine.Object context) (at C:/buildslave/unity/build/Editor/Mono/SerializedObject.bindings.cs:39)
UnityEditor.Editor.GetSerializedObjectInternal () (at C:/buildslave/unity/build/Editor/Mono/Inspector/Editor.cs:526)
UnityEditor.Editor.get_serializedObject () (at C:/buildslave/unity/build/Editor/Mono/Inspector/Editor.cs:433)
Microsoft.MixedReality.Toolkit.Input.Editor.MixedRealityPointerProfileInspector.OnEnable () (at Assets/MRTK/Core/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs:40)
```

## To reproduce

1. Make custom MRTK pointer profile
2. Hit play
## Your setup (please complete the following information)

- Unity Version 2018.4.20f1
- MRTK Version 2.4 stabilization

## Target platform (please complete the following information)

- Editor

**Comment by tank-t-bird** [comment]
Seems related to #5935 . Reestarting Unity should remove the error.

**Comment by julenka** [comment]
Doesn't repro in 2.4 stabilization resolving as closed in favor of 5935.
