### ISSUE TITLE
Better user feedback for migration window

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#7717]
## Describe the problem

Right now after performing any kind of upgrade the progress bar just disappears and the user won't have any information if the upgrade succeeded and which files got upgraded. (there is some message in the log, but not all users will have that open all the time)

## Describe the solution you'd like
Proposed changes:
1. Let user know that upgrade process is finished by showing a message (popup or notification) after the progress bar is finished.
2. Keep the list of items that were added for upgrading in the UI and show a green tick or a red X to indicate if the asset has been upgraded. Green tick ones can have a tooltip like: Asset has been upgraded sucessfully  - where red ones can show a truncated version of the error and on double click lead the user to the actual log message that gives the full information.

3. (Should we warn the user before starting upgrading process that this is a non - revertible process?  -> once migration is performed the files can't be changed back (except by their own version control, but that's out of our hands)

## Describe alternatives you've considered

Open for any other suggestions on how we can improve user feedback for this :)

**Comment by vaoliva** [comment]
Closed as issue solved by #7735
