### ISSUE TITLE
Do not require full HoloToolkit import for Holographic settings

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#772]
[Migrated from internal feedback 10977867]
"I like the HoloToolkit menu, but importing HoloToolkit to get just that is too much. Please split that into a separate package."

**Comment by StephenHodgson** [comment]
I'm not sure I fully understand this request.

**Comment by keveleigh** [comment]
Hmm, I believe this was a request to have a separate unitypackage for just the editor menu.

**Comment by StephenHodgson** [comment]
I wonder which parts they're referring to.

The Build, and UWP Capabilities windows _could_ be it's own thing, but the rest is tied into the toolkit pretty closely.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
