### ISSUE TITLE
Proposal: Modal input stack changes

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#7720]
The modal input stack is a hold over from the HoloToolkit, where we essentially had one input source (air tap). The intent of this feature is to allow application developers to display an object and route all events to that object, even if the user is not actively focusing upon it.
 
In MRTK, we added many more events, each of which are routed to the modal input stack. This issue is magnified when there are more than one control source in use (ex: two hands) as the number of events is multiplied.
 
It is believed that the modal input behavior shoud be modified to limit the types of events that are sent to that stack. We have landed on three possiblities.
	
- Only send pointer events
  - pro: best performance, minimal event traffic
  - con: behavior change, events that may be relied upon will no longer be sent
- Send pointer and source detected / lost events
  - pro: improved performance, applications can handle source lost mid click/tap
  - con: behavior change, events that may be relied upon will no longer be sent
- Allow developers to specify the types of events to send
  - pro: most flexible, developers can balance features / performance, can replicate current behavior
  - con: highest performance cost, added complexity raising modal input

If we choose option 3, we can avoid behavior change by defaulting to sending all event. Alternatively, we can default to the most performant option and document how to restore the legacy behavior.

**Comment by Zee2** [comment]
@davidkline-ms what is the status on this issue? Assuming it will be moot for XRI, but was there a 2.x-era resolution?

**Comment by davidkline-ms** [comment]
MRTK3 should not have this issue at all. Also, MRTK2 is unlikely to get such a large change at this point.
