### ISSUE TITLE
Create generic toggle panel for SDK, use variants in demo scenes

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#7722]
From a comment, by @keveleigh, in #7703

"Small question on the toggle features panel: does it make sense for the one we use in our example scene to be the SDK prefab? It feels very specific to our scenario. It might be interesting to have a generic one, with ours being an example prefab variant or something."

This is a great suggestion and would help developers to more easily create application specific variants  rather than needing to duplicate and customize the SDK control.

**Comment by davidkline-ms** [comment]
This was a added and forgotten to be closed.

**Comment by davidkline-ms** [comment]
I was incorrect. the panel we have is not the generic panel we would like to have.

**Comment by Zee2** [comment]
This is being built as part of the sample scene hand menu for MRTK3. (#10852 )
