### ISSUE TITLE
Constant Boundary floor outline

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#7724]
## Describe the problem

In VR application that involves physical movement a lot you can barely avoid to reach your boundary grid. The biggest two problems with the grid are:
- You don't see it at all when you're not close, so you don't know when to anticipate it

## Describe the solution you'd like

Showing the boundary outline at floor level at all times. This has the benefit of you knowing beforehand when you come close. You can move better as if it was the edge of a sidewalk, you see it from the corner of your eye.

**Comment by davidkline-ms** [comment]
@Alexees, the default boundary system settings has the following configuration:

Floor: on
Tracked area (the outline) : on
Play area (largest rectangle in the tracked area): on
Walls: off
Ceiling: off

Are you not seeing the outline? Can you confirm the boundary visualization profile settings?

Also, which device are you using? It is possible that the device does not actually return the tracked area via Unity's API.

Thanks!

**Comment by davidkline-ms** [comment]
Another quick question, is this the legacy Unity API or XR SDK on Unity 2019.3?

**Comment by Zee2** [comment]
If you're on SteamVR, you can always set the roomscale boundary option at the SteamVR platform level to show floor edges at all time. Otherwise, please see @davidkline-ms 's response for configuring the boundary system.
