### ISSUE TITLE
Forbidden MonoBehaviour instantiation through constructor

### ISSUE THREAD

**Issue by der-hugo** [microsoft/MixedRealityToolkit-Unity#7727]
## Describe the bug

When building a poject using MRTK v2.3 I get a warning in the Unity console

> You are trying to create a MonoBehaviour using the 'new' keyword.  This is not allowed.  MonoBehaviours can only be added using AddComponent(). Alternatively, your script can inherit from ScriptableObject or no base class at all
>UnityEngine.MonoBehaviour:.ctor()
>Microsoft.MixedReality.QR.Init:.ctor()
>UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

when looking into `Microsoft.MixedReality.QR.Init` which is `MonoBehaviour` you are using `[InitializeOnLoad]` combined with a `static Init()` constructor. This is not allowed and very unclean for Unity. dos this even need to be a `MonoBehaviour`?

In general I just want to point out that there is also [`[InitializeOnLoadMethod]`](https://docs.unity3d.com/ScriptReference/InitializeOnLoadMethodAttribute.html) which you could/should use instead so no constructor is used but you can still execute a `private static void Initialize()` or something similar.

- Unity Version any
- MRTK Version v2.3

## Target platform

- HoloLens
- HoloLens 2

**Comment by keveleigh** [comment]
Thanks for the report!
`Microsoft.MixedReality.QR` is not part of this repo. Did you import that separately?

**Comment by keveleigh** [comment]
Closing as External
