### ISSUE TITLE
Unity Editor Extension - Surface the description of a change without requiring the user to click the checkbox

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#773]
[Migrated from internal feedback 10996530]
"My suggestion is to surface the description of the change without requiring the user to click the checkbox. At a minimum (since it's a lot of information), even surfacing the first line of the description would give an increased user experience."

**Comment by StephenHodgson** [comment]
What is this in regards to?

The toolkit's configure windows?  If so, doesn't it already do this?

**Comment by keveleigh** [comment]
I had no idea what this was referring to when I migrated it here, but I've since noticed that I have to hover for ~a second before the description actually changes. It seems to change automatically on click, which may be why they assumed it only changes in that case.
