### ISSUE TITLE
Unity 19.3.7f1 MRTK 2.4.0 can't connect HoloLens2 with Wi-Fi nor USB: NullReferenceException: DownloadHandler has already been destroyed

### ISSUE THREAD

**Issue by FatherKingXWH** [microsoft/MixedRealityToolkit-Unity#7734]
## Describe the bug

I can connect HoloLens2 with Wi-Fi using Chrome by ip address:192.168.0.102, and the Windows Device Portal shows correctly. (I also installed the certificate to make a trust connection)
![image](https://user-images.githubusercontent.com/36912965/80339288-df39d980-8890-11ea-8507-d229bdf5e407.png)

But when I tried to connect it in Unity, it didn't work:
![image](https://user-images.githubusercontent.com/36912965/80339267-d77a3500-8890-11ea-83b6-404f3c72c402.png)

## To reproduce

In Unity
1. Go to 'Mixed Reality Toolkit'
2. Go to 'Utilities'
3. Click on 'Bulid Window'
4. Click on 'Deploy Options'
5. Click on 'Target Type'

With Wi-Fi:
1. Scroll to 'Remote'
2. Type IpAddress, Username, Password
3. Clcik on 'Test Connection'
4. Unity Editor shows "NullReferenceException: DownloadHandler has already been destroyed"

With USB:
1. Scroll to 'Local'
2. Type Username, Password
3. Clcik on 'Test Connection'
4. Unity Editor shows "NullReferenceException: DownloadHandler has already been destroyed"

## Expected behavior

How can I fixed it? 

## My setup 

- Unity Version [v2019.3.7f1]
- MRTK Version [v2.4.0]
- win10 SDK[10.0.18362.1]

## Target platform 

- HoloLens 2

## Additional context

In HoloLens2, "Developer Mode" and "Enable Device Portal" options are turned on

**Comment by keveleigh** [comment]
Fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7823. Will ship in MRTK 2.4
