### ISSUE TITLE
Unity unresponsive after switching from Standalone to UWP

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#7737]
## Describe the bug

Unity 2019.3.8f1 does not respond after attempting to switch to UWP from Standalone.  

![image](https://user-images.githubusercontent.com/53493796/80549722-d7eafc80-8972-11ea-9c0a-fa4d8785b1c5.png)

## To reproduce

1.  Import the latest stabilization unity foundation package
2. While still in Standalone
   - Mixed Reality Toolkit > Add to Scene and configure
   - Add a prefrab that prompts the TMP essentials import, I just searched for "tooltip" and added the Bezier Tooltip prefab to the scene.  Adding the prefab prompts the TMP Essentials import, select import the essentials. 
 3. Switch to UWP and unity hangs

## Your setup

- Unity Version: 2019.3.8f1
- MRTK Version: stabilization 2.4

**Comment by keveleigh** [comment]
Hmm, I'm not able to repro this on 2019.3.10f1. Looks like that font is distributed with TextMesh Pro. Which version of the package do you have installed? Mine's 2.0.1.

**Comment by CDiaz-MS** [comment]
I have 2.0.1 also.  When I ended the task in task manager and reopened the project this was logged to the console:

```
A default asset was created for 'Assets/TextMesh Pro/Fonts/LiberationSans.ttf' because the asset importer crashed on it last time.
You can select the asset and use the 'Assets -> Reimport' menu command to try importing it again, or you can replace the asset and it will auto import again.
```

I tried to reimport text mesh pro and switch to UWP, but it still hangs on the same font.  This might be an issue specific to my project if you cannot repro.

**Comment by CDiaz-MS** [comment]
I imported the packages again and then immediately switched to UWP and it worked.  But I did repro the issue on a fresh project after importing the TMP Essentials in Standalone and then switching to UWP.

More specific repro steps:
1.  Import the latest stabilization unity foundation package
2. While still in Standalone
   - Mixed Reality Toolkit > Add to Scene and configure
   - Add a prefrab that prompts the TMP essentials import, I just searched for "tooltip" and added the Bezier Tooltip prefab to the scene.  Adding the prefab prompts the TMP Essentials import, select import the essentials. 
 3. Switch to UWP and unity hangs

**Comment by wiwei** [comment]
I can confirm that this happens.

The reasons this happens is here:


Destroying GameObjects immediately is not permitted during physics trigger/contact, animation event callbacks or OnValidate. You must use Destroy instead.
UnityEditor.SceneManagement.EditorSceneManager:ClosePreviewScene_Injected(Scene&)
UnityEditor.SceneManagement.EditorSceneManager:ClosePreviewScene(Scene)
UnityEditor.PreviewScene:Dispose()
UnityEditor.PreviewRenderUtility:Cleanup()
UnityEditor.MaterialEditor:OnDisable()
UnityEngine.Object:DestroyImmediate(Object, Boolean)
UnityEngine.Object:DestroyImmediate(Object)
UnityEditor.AssetPreviewUpdater:CreatePreviewForAsset(Object, Object[], String)
UnityEditor.AssetDatabase:Refresh(ImportAssetOptions)
UnityEditor.AssetDatabase:Refresh()
Microsoft.MixedReality.Toolkit.Utilities.Editor.ProjectPreferences:get_Instance() (at Assets\MRTK\Core\Utilities\Editor\Preferences\ProjectPreferences.cs:69)
Microsoft.MixedReality.Toolkit.Utilities.Editor.ProjectPreferences:Get(String, Boolean) (at Assets\MRTK\Core\Utilities\Editor\Preferences\ProjectPreferences.cs:119)
Microsoft.MixedReality.Toolkit.Editor.MixedRealityProjectPreferences:get_AutoEnableUWPCapabilities() (at Assets\MRTK\Core\Utilities\Editor\Preferences\MixedRealityProjectPreferences.cs:87)
Microsoft.MixedReality.Toolkit.Utilities.Editor.UWPCapabilityUtility:RequireCapability(WSACapability, Type) (at Assets\MRTK\Core\Utilities\UWPCapabilityUtility.cs:27)
Microsoft.MixedReality.Toolkit.Windows.Input.WindowsSpeechInputProvider:Initialize() (at Assets\MRTK\Providers\WindowsVoiceInput\WindowsSpeechInputProvider.cs:123)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProvider(IMixedRealityInputDeviceManager) (at Assets\MRTK\Core\Services\BaseDataProviderAccessCoreSystem.cs:254)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProviderInternal(Boolean, Type, SupportedPlatforms, Object[]) (at Assets\MRTK\Core\Services\BaseDataProviderAccessCoreSystem.cs:237)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProvider(Type, SupportedPlatforms, Object[]) (at Assets\MRTK\Core\Services\BaseDataProviderAccessCoreSystem.cs:162)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:CreateDataProviders() (at Assets\MRTK\Services\InputSystem\MixedRealityInputSystem.cs:268)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Initialize() (at Assets\MRTK\Services\InputSystem\MixedRealityInputSystem.cs:235)
Microsoft.MixedReality.Toolkit.<>c:<InitializeAllServices>b__60_0(IMixedRealityService) (at Assets\MRTK\Core\Services\MixedRealityToolkit.cs:924)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1) (at Assets\MRTK\Core\Services\MixedRealityToolkit.cs:1034)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeAllServices() (at Assets\MRTK\Core\Services\MixedRealityToolkit.cs:924)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets\MRTK\Core\Services\MixedRealityToolkit.cs:469)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeInstance() (at Assets\MRTK\Core\Services\MixedRealityToolkit.cs:583)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean) (at Assets\MRTK\Core\Services\MixedRealityToolkit.cs:721)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:OnValidate() (at Assets\MRTK\Core\Services\MixedRealityToolkit.cs:1477)

**Comment by wiwei** [comment]
Also for future reference, here's maybe some helpful information for other folks who are debugging Unity hang issues.

It seems like the editor is hanging in this case, but actually, it's not - I was starting to dig into this by looking at the Unity player log i.e.:

C:\Users\username\appdata\local\Unity\Editor\...

I assumed it would have the most interesting stuff at the very end - it turns out, as I was watching it, it was still growing (i.e. in a minute had grown to like 500MB).

So it turns out it wasn't hung, it was just hitting errors at just the worst time in OnValidate

**Comment by keveleigh** [comment]
Looks like it comes down to an explicit `AssetDatabase.Refresh()` call.

**Comment by keveleigh** [comment]
(unintentional close/reopen)

I think we have a few of those scattered around. I've seen other warnings printed (I think @CDiaz-MS pointed some out too possibly?) around calling this at the "wrong" time too. Might need to reevaluate our use of them, especially in code that might be called in reload scenarios like this.

**Comment by CDiaz-MS** [comment]
Yep this is one of the warnings I have seen related to AssetDatabase.Refresh in the unity packages:

```
An AssetDatabase Refresh is pending after a successful Package Manager request. You should not call AssetDatabase.Refresh at this time because it can lead to import-related errors.
UnityEditor.AssetDatabase:SaveAssets()
Microsoft.MixedReality.Toolkit.Editor.EditorLayerExtensions:SetupLayer(Int32, String) (at Assets/MRTK/Core/Extensions/EditorClassExtensions/EditorLayerExtensions.cs:65)
Microsoft.MixedReality.Toolkit.Utilities.Editor.MixedRealityProjectConfigurator:SetSpatialAwarenessLayer() (at Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs:311)
Microsoft.MixedReality.Toolkit.Utilities.Editor.MixedRealityProjectConfigurator:Configure(Configurations) (at Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs:194)
Microsoft.MixedReality.Toolkit.Utilities.Editor.MixedRealityProjectConfigurator:ConfigureProject(HashSet`1) (at Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs:233)
Microsoft.MixedReality.Toolkit.Utilities.Editor.MixedRealityProjectConfiguratorWindow:ApplyConfigurations() (at Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs:244)
Microsoft.MixedReality.Toolkit.Utilities.Editor.MixedRealityProjectConfiguratorWindow:RenderChoiceDialog() (at Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs:137)
Microsoft.MixedReality.Toolkit.Utilities.Editor.MixedRealityProjectConfiguratorWindow:OnGUI() (at Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs:101)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```
