### ISSUE TITLE
MixedRealityKeyboard does not unsubscribe from InputPane::Hiding and InputPane::Showing causing crash

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7739]
## Describe the bug

MRTK's MixedRealityKeyboard.cs isn't unsubscribing from InputPane::Hiding before GameAssembly.dll is unloaded (and it previously subscribed to InputPane::Hiding with an object from that DLL).

This doesn't immediately lead to a crash as we don't notice it right away. In this case we only notice it when something else unsubscribes from that event, but we would also notice it and crash if that InputPane;:Hiding event actually fired.

**Comment by keveleigh** [comment]
Fixed via #7741
