### ISSUE TITLE
Apply Mixed Reality Settings menu causes the Editor to hang

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#774]
[Migrated from internal feedback 10996587]
"Inside of Unity, when selecting the HoloToolKit -> Configure -> Apply Mixed Reality Project/Scene/Capability Settings

Issue:
When hitting the X button, the Unity editor visibly hangs for a moment. This is particularly inconvenient when trying to explore the options available. I noticed this to be more prominent when leaving the Capability Settings window open and switching to the feedback portal. It was difficult to gain control of the Unity editor again and I almost did a force close. (It started to slowly show life again, so I held off.)

Repo Steps:
1. Open one of the settings windows through HoloToolKit -> Configure -> Apply Mixed Reality Project/Scene/Capability Settings
2. Check/Uncheck a few buttons to read the description.
3. Click the X to close the window."

**Comment by StephenHodgson** [comment]
@keveleigh, I wasn't able to reproduce this issue with the steps provided.

**Comment by StephenHodgson** [comment]
Possibly fixed by https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/887?

Reopen if you're able to duplicate after this PR.
