### ISSUE TITLE
Standard Shader OPENGL NATIVE PLUG-IN ERROR

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#7744]
## Describe the bug

the following errors are thrown on my Oculus Quest, when I run the subsequent shader on it and the object does not show up:
![image](https://user-images.githubusercontent.com/32508825/80714769-ac444f80-8af5-11ea-8c52-d7877041999d.png)
![image](https://user-images.githubusercontent.com/32508825/80715066-1eb52f80-8af6-11ea-8618-b5681200110f.png)

## Expected behavior

Rendering should work

## Your setup (please complete the following information)

- Unity Version  2018.3.15.f1
- mrtk_development

## Target platform (please complete the following information)

- Oculus Quest

## Additional context

@Cameron-Micka do you have an idea what's that all about, you're the shader guy, aren't you?

**Comment by Cameron-Micka** [comment]
Hi @Alexees, unfortunately I do not have an Oculus Quest to test on. But, my assumption based on the error is that the custom render mode specified by this material is invoking Unity's renderer to change the OpenGL state in a way that is not supported by the platform (for example maybe the above blending operations are not supported in that configuration, likely not actual issue).

This is likely a bug that needs to be reported to Unity via their [bug reporter](https://unity3d.com/unity/qa/bug-reporting). If you can alter some of the settings under "Rendering Mode" until the issue goes away that might help narrow down which setting is the culprit and help create a min repo example.

**Comment by Cameron-Micka** [comment]
@Alexees I'm having difficulty getting hold of an Oculus Quest. Would you mind filing this bug with Unity using their bug reporter?
