### ISSUE TITLE
Old project (Hololens 2) : Could not copy the file "*\Plugins\ARM\SpatialUnderstanding.dll" because it was not found 

### ISSUE THREAD

**Issue by efsjouw** [microsoft/MixedRealityToolkit-Unity#7757]
## Overview

An old project with the really old Holotoolkit + MRDesignLabs HUX gives me this error on deploying to the Hololens.

Could not copy the file "*\Plugins\ARM\SpatialUnderstanding.dll" because it was not found 

- First of all, this should not be a dll but a pdb right?
- Replacing it with the Unity 2017 holotoolkit version gives a whole bunch of errors and seems incompatible with HUX
- Remove all dll import directives and returning false in the spatial mapping enabled variable doesn't appear to fix it
- Removing the SpatialMapping folder completely makes this error go away but it replaced by a different dll error about the SpatialUnderstanding dll

Is there any other way to tell Unity to not search for this dll?

## Expected behavior
Deploy to the Hololens 2

## Actual behavior
Could not copy the file "*\Plugins\ARM\SpatialUnderstanding.dll

## Steps to reproduce
- Download old holotoolkit from 2016 (sorry it's unclear what version this is and where to do download it, you guys should know this better than me?)
- Include MRDesignLab HUX
- Build for Hololens 2 ARM with Unity 2018.4
- Deploy to Hololens 2

## Unity editor version

2018.4.22f1

## Mixed Reality Toolkit release version

Some old "HoloToolkit" 2016 version

**Comment by efsjouw** [comment]
Ok, copying the SpatialUnderstanding from WSA and the folder above that and then making ARM folders in both and putting CPU on ARM fixed this for me.

**Comment by keveleigh** [comment]
Looking back at the repo, looks like we added ARM support for that DLL: https://github.com/microsoft/MixedRealityToolkit/pull/132

If you're planning on using it on HL2, you should be able to clone that repo and build a new set of binaries, or you can open the solution and build just an ARM binary to fill the gap you currently have.

**Comment by keveleigh** [comment]
>Is there any other way to tell Unity to not search for this dll?

Otherwise, I'm not sure. This behavior was updated in Unity 2019.3.9, but I'm not sure if the fix is going to be backported to Unity 2018.

**Comment by dahaideyu** [comment]
now ,in MRTK2.4 ,how to using spatialUnderstanding. or other way to get floor and Collision detection

**Comment by keveleigh** [comment]
Going to close this one down. It should be possible to build an ARM flavor of this DLL, and we've since replaced it with built-in [MRTK Scene Understanding suppor](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/spatial-awareness/scene-understanding)t.
