### ISSUE TITLE
GazeProvider focus interface

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#7758]
## Describe the problem

Sometime you might be interested in what the user is looking at even though he uses hands or MotionController.
E.g.: Showing the controllers button capabilites when he looks at it

According to this documentation, this is a limitation at the moment:
[Eye-supported target selection](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/EyeTracking/EyeTracking_TargetSelection.html)

> 1. Use the primary focus pointer:
> 
> This can be understood as your prioritized cursor. By default, if the hands are in view, then this would be hand rays. If no hands are in view, then the prioritized pointer would be head or eye gaze. Thus, please note that based on the current design head or eye gaze is suppressed as a cursor input if hand rays are used.

## Describe the solution you'd like

The GazeProvider should provide an interface like IMixedRealityGazeHandler you can listen to just like you can with IMixedRealityFocusHandler

## Describe alternatives you've considered

Polling the current gaze target as described here:
[Gaze](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Gaze.html)

**Comment by keveleigh** [comment]
>Describe alternatives you've considered
>Polling the current gaze target

Are you saying polling wasn't sufficient for your scenario, or it wasn't working? The gaze target should continue to be updated and accessible via polling even as other rays, like the motion controller far rays, are present.

**Comment by Alexees** [comment]
Not quite, just saying that there is an interface for almost everything else and it feels that it's not necessary to do this differently all of a sudden.
Ok, FocusProvider does not use an interface but SubscribeToPrimaryPointerChanged, which is also different from the input system, but then at least GazeProvider could have the exact same thing, although I'd suggest to streamline this and use interfaces for both.

**Comment by RogPodge** [comment]
Closing due to pre-existing polling solution, as well as not wanting to overload the focus provider with more overmanagement of pointers.
