### ISSUE TITLE
Object Manipulator is not available in conceptual docs menu

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#7760]
## Describe the issue
there's still manipulationhandler - version 2.4 should point to Object Manipulator

**Comment by cre8ivepark** [comment]
@thalbern I fixed it with this PR:
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7740

Kept Manipulation Handler with [Obsolete] tag.
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_ObjectManipulator.html
