### ISSUE TITLE
Copying Assembly failed Multiplayer HLAPI

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#7761]
## Describe the bug

On import of the Leap Core assets into 2019.3, the following error is logged:

```
Copying assembly from 'Temp/com.unity.multiplayer-hlapi.Runtime.dll' to 'Library/ScriptAssemblies/com.unity.multiplayer-hlapi.Runtime.dll' failed
```

This issue occurs if the source of MRTK is cloned from the repo and not if the source is from the unity packages.

## To reproduce

1. Clone MRTK using `git clone https://github.com/microsoft/MixedRealityToolkit-Unity.git`
2. Open the project in Unity 2019.3.
3. Import the Leap Core Assets: https://github.com/leapmotion/UnityModules/releases/tag/Release-CoreAsset-4.4.0
4. See the 'Copying Assembly' issue 

## Your setup 

- Unity Version: 2019.3.8
- MRTK Version: 2.4

## Target platform

- Leap Motion

## Issue Resolution

To resolve the issue, restart unity.

**Comment by wiwei** [comment]
This type of failure on asset load is actually relatively 'common' in Unity when importing somewhat large Unity packages. This is typically (i.e. from what I've seen) in interaction between antimalware on the machine and Unity's import process, where you'll see something like Windows Defender try to scan the new files as they get copied over. This can race and cause Unity to throw up, forcing a re-import attempt (which may also just hit the same issue). Ultimately it ends up being somewhat intermittent, and if you import really large unity packages, you'll see that it will often fail on different assets (i.e. some DLLs will succeed in one, the same one will fail in another).

I just gave this a shot on my machine (on a low powered laptop) w/ defender exclusion on the project folder and it worked out just fine.

We should probably add this note (i.e. windows defender exception or AV exception on development notes and stuff)
