### ISSUE TITLE
Vector rotation handle size for bounding box

### ISSUE THREAD

**Issue by djee-ms** [microsoft/MixedRealityToolkit-Unity#7772]
## Describe the problem

The bounding box component assumes uniform scaling of the handles, which works fine for the default sphere, but prevents the user from using _e.g._ a rectangle spanning a larger part of the edge.

## Describe the solution you'd like

Change `RotationHandleSize` to be `Vector3`.

## Describe alternatives you've considered

I don't see one.

## Additional context

With local change I modified `RotationHandleSize` to be `Vector3` and use a stretched cube to have a rotate handle spanning almost the entire edge. The cube doesn't scale, so there is no confusion in this use case.

![image](https://user-images.githubusercontent.com/49064175/80867844-4808c380-8c8e-11ea-9f42-eb847e95e853.png)

**Comment by Zee2** [comment]
`BoundsControl` resolves this problem. It supports arbitrary handle sizes, shapes, prefabs, etc.
