### ISSUE TITLE
Hand simulation moves cursor on click

### ISSUE THREAD

**Issue by djee-ms** [microsoft/MixedRealityToolkit-Unity#7773]
## Describe the bug

When using hand simulation in the Unity editor, clicking with LMB moves the cursor, and on release the cursor doesn't always point at the same location anymore, making precise selections difficult.

## To reproduce

![mrtk_handsim_unstable](https://user-images.githubusercontent.com/49064175/80868047-e5b0c280-8c8f-11ea-9b0f-248b67b9d60b.gif)

Note how the box starts to rotate, even though the mouse cursor doesn't move, only LMB is pressed. The hand simulation cursor however does appear to move up slightly on its own. Also when clicking on the upper part of the handle, the cursor doesn't anymore hovers the handle after releasing LMB.

## Expected behavior

Motion and click should be completely independent.

## Screenshots

See above.

## Your setup (please complete the following information)

- Unity Version 2018.4.15f1
- MRTK Version 2.3

## Target platform (please complete the following information)

- Unity Editor

**Comment by julenka** [comment]
@RogPodge  this could be a nice one to look at for you.

**Comment by wiwei** [comment]
I think that this one has actually been in there forever - the location that determines that hand position actually shifts ever so slightly during the gesture (so this could I think be addressed by updating the positions of the simulated joints themselves)

**Comment by djee-ms** [comment]
Thanks @RogPodge !
