### ISSUE TITLE
 The volumetric UnityUI slate appears to be empty in the hand interaction examples

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#7783]
## Describe the bug

The volumetric UnityUI slate appears to be empty in the hand interaction examples:

![image](https://user-images.githubusercontent.com/5840182/81018298-196b2400-8e19-11ea-9cfb-203536db72ef.png)

This is because the scroll view content element is disabled:

![image](https://user-images.githubusercontent.com/5840182/81018358-2ee04e00-8e19-11ea-855a-0e52a13b556e.png)

## To reproduce

1. Open the HandInteractionExamples scene
1. Look to the right and see that the volumetric buttons don't appear on the UnityUI slate.

## Your setup (please complete the following information)

- Unity Version 2018.4.22f1
- MRTK Version 2.4.0.prerelease

**Comment by cre8ivepark** [comment]
Not sure why it is disabled. And if I enable it, still some of the layout details are broken (see-it, say-it label position, debug color cube text, button's front plate shows double lines)
![2020-05-04 17_22_28-Unity 2018 4 21f1 Personal - HandInteractionExamples unity - MRTKBuildCall050420](https://user-images.githubusercontent.com/13754172/81025649-21808f00-8e2c-11ea-9c98-1c77e87c4ecf.png)
![2020-05-04 17_21_56-Unity 2018 4 21f1 Personal - HandInteractionExamples unity - MRTKBuildCall050420](https://user-images.githubusercontent.com/13754172/81025650-22b1bc00-8e2c-11ea-83be-847dcd309a03.png)

**Comment by cre8ivepark** [comment]
Oh,, I found that PressableButtonsTestCanvas is showing (Missing Prefab)
![2020-05-04 17_29_20-Unity 2018 4 21f1 Personal - HandInteractionExamples unity - MRTKBuildCall050420](https://user-images.githubusercontent.com/13754172/81025830-e3d03600-8e2c-11ea-95da-244802d85834.png)

**Comment by thalbern** [comment]
same issue on hl2 / unity 2018.4.17

**Comment by thalbern** [comment]
seems like some sort of packaging problem - the link to the prefab gets lost in our release packages. - everything works fine when using the repo directly
