### ISSUE TITLE
Organization of the MRTK menu with just the Foundation package

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#7785]
Not exactly a bug, but more for having a discussion. When you just pull in the Foundation package, the MRTK dropdown folder's organization looks a bit interesting:

![image](https://user-images.githubusercontent.com/5840182/81020430-a44e1d80-8e1d-11ea-8c82-0cc9560752fb.png)

Should Leap be first there, or do we want to have (or already have some other standard for how we choose to sort that?)

**Comment by wiwei** [comment]
@keveleigh @CDiaz-MS thoughts?

**Comment by keveleigh** [comment]
Ahh interesting, yeah. I wonder if we want to have a platform/device-specific subsection somewhere. It feels like it shouldn't be first though? Looks like the menu items are currently hardcoded to be first with the `0`:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/55f8afa15fb774d620f3d27ff8634e706e7ecb66/Assets/MRTK/Providers/LeapMotion/Editor/ConfigurationChecker/LeapMotionConfigurationChecker.cs#L328

so we can update it there? I think, if we want the line to show up separating sections, we need at a gap of at least 10 between one menu item and the next.
Configure Unity Project uses `499`, but others (like Input Simulation) don't specify anything, so it might come down to load order at that point.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/e0b9d322d367d33047b7b0f09f87c193b81fbf18/Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs#L59

**Comment by wiwei** [comment]
Yeah, I always felt like these hardcoded numbers have been kinda goofy - there's no clear single place to understand how the menu is being laid out at a global level.

**Comment by keveleigh** [comment]
> I always felt like these hardcoded numbers have been kinda goofy - there's no clear single place to understand how the menu is being laid out at a global level.

We've been using [the ProfileMenuItemIndices enum](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MRTK/Core/Definitions/Utilities/ProfileMenuItemIndices.cs) for ordering the "create asset" menu. We could do something similar for this menu

**Comment by wiwei** [comment]
> > I always felt like these hardcoded numbers have been kinda goofy - there's no clear single place to understand how the menu is being laid out at a global level.
> 
> We've been using [the ProfileMenuItemIndices enum](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MRTK/Core/Definitions/Utilities/ProfileMenuItemIndices.cs) for ordering the "create asset" menu. We could do something similar for this menu

That sounds good - we can add a CI step to check that you aren't using hardcoded numbers as well, which would prevent future folks from messing up.

**Comment by CDiaz-MS** [comment]
Removed Leap menu priority in #7877
