### ISSUE TITLE
TextToSpeech not working at Scene initialisation

### ISSUE THREAD

**Issue by 4random** [Microsoft/MixedRealityToolkit-Unity#779]
After loading a new scene I use the `TextToSpeechManager `within the `Start()` function of one of my scripts. If Unity calls the `Start()` function of the TextToSpeechManager prior to my `Start()` function TextToSpeech works, otherwise not. The reason is that the `SpeechSynthesizer` is created during `Start()` but when calling a function of a script it is not guaranteed that `Start() ` has already been called. Therefore I encapsulated the synthesizer behind the following function inside the `TextToSpeechManager`:
```
private SpeechSynthesizer GetSynthesizerInstance()
        {
            try
            {
                if (synthesizer == null)
                {
                    synthesizer = new SpeechSynthesizer();
                }
            }
            catch (Exception ex)
            {
                Debug.LogError("Could not start Speech Synthesis");
                Debug.LogException(ex);
            }
            return synthesizer;
        }
```

This works for me but is not my suggested solution. I suggest using a proper Singelton of the `SpeechSynthesizer ` or maybe the initialisation inside the `Awake()` function would solve the problem as well.

I am using HoloToolit 1.5.7, Unity 5.6.2f1 and Vuforia 6.2.10

**Comment by acarabott** [comment]
I experienced something similar, but need to have multiple instances of `SpeechSynthesizer`, my solution is to use a co-routine:

```
public class Person : MonoBehaviour 
{
    public string personName = "no-one";
    private TextToSpeechManager voice;
    
    private void Start()
    {
        voice = gameObject.GetComponent<TextToSpeechManager>();
        SayName();
    }

    public void SayName()
    {
        StartCoroutine(SayNameRoutine());
    }

    private IEnumerator SayNameRoutine()
    {
        yield return new WaitUntil(() => voice.gameObject.activeSelf && !IsSpeaking());
        voice.SpeakText(personName);
    }

    public bool IsSpeaking()
    {
        return voice.SpeechTextInQueue() || voice.IsSpeaking();
    }
}
```

**Comment by StephenHodgson** [comment]
Renaming the `TextToSpeechManager`'s Start function to Awake should fix this issue.

**Comment by acarabott** [comment]
Hah, much simpler.
