### ISSUE TITLE
MRTK 2.4 Release Notes Missing ObjectManipulator and BoundsControl

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7799]
## Describe the issue
Our 2.4 release notes are missing the awesome new ObjectManipulator graduation from @thalbern  and @MenelvagorMilsom. We should mention these as they are much cleaner than ManipulationHandler and BoundingBox.

**Comment by thalbern** [comment]
linking graduation task https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7357
