### ISSUE TITLE
Use 'Toggle' buttons for the Toggle Features Panel

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#7801]
## Describe the bug
Currently, buttons on the Toggle Features Panel are regular buttons which could be confusing. To clearly communicate the on/off state of the features such as hand mesh/hand joint/profiler/etc, we need to replace them with Toggle buttons. 
![2020-05-05 20_09_16-Unity 2018 4 21f1 Personal - HandInteractionExamples unity - MRTKBuildCall050420](https://user-images.githubusercontent.com/13754172/81135282-549a4f80-8f0c-11ea-9951-3ca9e5d6c4ab.png)

**Comment by keveleigh** [comment]
Fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7902
