### ISSUE TITLE
Getting started Tutorials don't result in working app

### ISSUE THREAD

**Issue by sekapp** [microsoft/MixedRealityToolkit-Unity#7804]
## Describe the issue
After following the "Getting started" Tutorials the UWP app instantly crashes when deployed on a HoloLens 2.

## Feature area
I had to disable the "Graphics Jobs" option in the player settings to get the app to work.

## Existing doc link
e.g. https://docs.microsoft.com/de-de/windows/mixed-reality/mrlearning-base-ch1

## Additional context
Steps to reproduce:
1. Create new Unity Project
2. Switch to UWP build target, enable and set up Windows Mixed Reality in Player Settings (following the documentation)
3. Build App -> Works and shows the empty example scene
4. Add MixedRealityToolkit Foundation Package and apply the recommended settings
5. Set up the Scene (following the documentation)
6. Build App -> App instantly crashes on HoloLens 2
7. Go to Player Settings and disable "Graphics Jobs"
8. Build App -> Works as intended

I don't know if this is a bug in the MRTK, a missing detail in the documentation or an issue on my side but maybe it should be added to the documentation somewhere as I spent a very long time to figure out why my apps didn't work.

Note: I tested the v2.3.0 release with Unity 2019.2 and 2019.3 with the same result. The issue did not show on 2018.4.

**Comment by keveleigh** [comment]
This is currently a known issue on the Unity side of things. It can be tracked on their public issue tracker: https://issuetracker.unity3d.com/issues/enabling-graphics-jobs-in-2019-dot-3-x-results-in-a-crash-or-nothing-rendering-on-hololens-2

**Comment by sekapp** [comment]
This should be resolved with #7858
