### ISSUE TITLE
An issue of BoundingBox

### ISSUE THREAD

**Issue by WuHaoDataMesh** [microsoft/MixedRealityToolkit-Unity#7805]
## Describe the bug

When we add a BoundingBox to some GameObjects (about 100) by coding, and set all properties of it,  program will lag for a long time.

## To reproduce

1. use AddComponent to add a BoundingBox to a GameObject
2. set all the properties of this BoundingBox
3. do it 100 times
4. the program will lag , maybe more than 4~5 second.

## Expected behavior

Don't lag so long.

## Your setup (please complete the following information)

- Unity Version : 2019.2.21
- MRTK Version : 2.3

## Target platform (please complete the following information)

- All platform

## Additional context

We reviewed the code of BoundingBox.cs, and we found that the Set Function of all properties include "CreateRig" function. We think this is the problem. After we create BoundingBox, we must set all the properties, and it will call CreateRig many many times! 

We have solved this problem, by adding a bool variable to prevent "CreateRig". After we create BoundingBox by code, we set this bool to true, then set all the properties. After that, we set this bool to false, and call "CreateRig" manually at the end.

**Comment by wiwei** [comment]
Closing this out per info in the linked PR - the latest changes to BoundsControl (the successor for BoundingBox) should have greatly alleviated it.

Feel free to reopen if it doesn't end up working for you
