### ISSUE TITLE
Separate eye gaze for left/right/both eyes

### ISSUE THREAD

**Issue by Naphier** [microsoft/MixedRealityToolkit-Unity#7806]
## Describe the problem
Currently there is no way to allow users to select which eye (left/right/both) to use for gaze tracking. This makes it difficult for those of us with amblyopia where one eye will tend to be very dominant and the other points in a different direction. 
Please implement a way to allow devs to expose the ability to toggle between left/right/both eyes for gaze input.
Thanks!

**Comment by keveleigh** [comment]
The MRTK currently exposes eye gaze based on the Windows APIs, which provides a [single gaze ray](https://docs.microsoft.com/en-us/uwp/api/windows.perception.people.eyespose?view=winrt-18362). @sostel might be able to provide more background on this.

**Comment by Naphier** [comment]
That's quite unfortunate as there's a lack of accessibility for those with
amblyopia then. My amblyopia is not even bad and the eye tracking in the HL
is useless for me.
Tobii had it exposed in their API.
I know MS can do better than Tobii :)

**Comment by sostel** [comment]
Yes, @keveleigh is correct - this is not supported by the Windows APIs at this time. Unfortunately, not much MRTK can do about it right now. 

I'm curious though - when you use eye targeting with HoloLens how bad is it?

**Comment by Naphier** [comment]
How do I get this into the hands of the Windows API folks then?
As for how bad. It's very inaccurate and floats around a bit.

I tried calibration with just my dominant eye open but that didn't really
help.

TBH the Tobii and Give Pro Eye gave me less issues.

**Comment by sostel** [comment]
Sorry to hear! I'll let the team know. Thanks for sharing, Sean!
@Naphier

**Comment by Zee2** [comment]
Apologies for this accessibility issue; unfortunately as mentioned above we are limited by the platform API. Please use Feedback Hub to communicate this to the platform team.

**Comment by Naphier** [comment]
@Zee2 hopefully @sostel already did that. Feedback Hub is a dead end and black void.
