### ISSUE TITLE
Release Notes, Upgrade guide missing Eye Gaze API Changes

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7808]
## Describe the issue
Both the [Release Notes](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/prerelease/2.4.0_stabilization/Documentation/ReleaseNotes.md) and [Updating guidance](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/prerelease/2.4.0_stabilization/Documentation/Updating.md#updating-230-to-240) are missing info about how to upgrade old eye tracking api calls to new ones. It should include a section like this:

**Eye Gaze API Changes**

If you did this previously...

```csharp
GazeProvider gzProvider = FindObjectOfType<GazeProvider>();
gzProvider.UseEyeTracking = false;
```

Do this now...

```csharp
GazeProvider gzProvider = FindObjectOfType<GazeProvider>();
((IMixedRealityEyeGazeProvider) gzProvider).IsEyeTrackingEnabled = true;
```

**Comment by wiwei** [comment]
There's another thing missing here, which is IsEyeTrackingEnabled should also have a FormerlySerializedAs attribute
