### ISSUE TITLE
Release Notes is missing info about Button Config Helper

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7809]
## Describe the issue
There is a new Button Config Helper coming in out MRTK 2.4, it would be great to have the release notes mention this nice feature.

![image](https://user-images.githubusercontent.com/168492/81211778-bb5d4e80-8f88-11ea-94c7-33cf265586df.png)

**Comment by keveleigh** [comment]
Added in #7827
