### ISSUE TITLE
HoloToolkit Tap to Place issue

### ISSUE THREAD

**Issue by DrunkReaperMatt** [Microsoft/MixedRealityToolkit-Unity#781]
I'm using the TapToPlace form the HoloToolkit in order to move the hologram (duh). But on runtime, i cant seem to get any response from the script, only from another script that i created that uses the IInputClicker interface.

On a blank scene, the TapToPlace does not still seem to respond and the AnchorManager projects the hologram on a point far away from the origin, in the range of the +/- 40's. 

Thanks

**Comment by DrunkReaperMatt** [comment]
The TapToPlace still does not work properly most of the time. From my previous issue, the hologram stays at a reasonable distance in the scene, I can select a hologram. But there is still a problem where it will not be set in a location

**Comment by StephenHodgson** [comment]
I believe the GazeManager has a maximum distance, which is set to 10.

**Comment by DrunkReaperMatt** [comment]
So basically, anything further than 10 wouldn't be registered by the tap?

Any way to increase that range?

**Comment by StephenHodgson** [comment]
Yes, you can update this distance on the `GazeManager` component.
![gazemanager](https://user-images.githubusercontent.com/13334553/28801523-cf84fc30-7606-11e7-97b7-1fa46a2a678e.PNG)

**Comment by keveleigh** [comment]
This looks answered. Please reopen if not!
