### ISSUE TITLE
After upgrade to MRTK 2.4, all custom icons on buttons are reverted

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7810]
## Describe the bug
When upgrading a project from MRTK 2.3 to 2.4, all buttons created, modified from prefab "PressableButtonHoloLens2" get their icons reverted to the default icon.

![image](https://user-images.githubusercontent.com/168492/81215977-04b09c80-8f8f-11ea-839a-28314935c8aa.png)

## To reproduce

1. Create a project with MRTK 2.3 and create a scene with some buttons.
2. Customize the icons in your buttons.
3. Update to 2.4.
4. Notice that the button icons have changed back to the default icons.

## Expected behavior
The customized button icons should stay the same.

## Screenshots

Before update, in MRTK 2.3:
![image](https://user-images.githubusercontent.com/168492/81215725-9b308e00-8f8e-11ea-8d65-d9fc8c1fe5cf.png)

After update, MRTK 2.4:

![image](https://user-images.githubusercontent.com/168492/81215756-a7b4e680-8f8e-11ea-8d2c-cf06c70b7c41.png)

**Comment by julenka** [comment]
I wonder if this is related to the Button Configurator -- perhaps the button configurator is forcing the icon?

**Comment by cre8ivepark** [comment]
@Railboy I think we should include an upgrade guide for this new ButtonConfigHelper in the Release Note. Under 'Button Config Helper added to Pressable Buttons' section.
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/prerelease/2.4.0_stabilization/Documentation/ReleaseNotes.md

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_Button.html#how-to-change-the-icon-and-text

**Comment by Railboy** [comment]
Yes, this is related to button config helper.

The button icons are still intact so no work has been lost. They're just being masked by a property block override.

>Would it be possible to automatically select an icon in the ButtonConfigHelper based on the existing icon when upgrading?

@cre8ivepark Yes, and I think this would be a good solution.

**Comment by cre8ivepark** [comment]
I guess there are many people who already added their own custom textures for the icons. It would be still breaking if those custom icons are not in the new ButtonConfigHelper's icon list. How about just maintaining existing icon as-is and only change the icon when the user explicitly selects an icon in the new ButtonConfigHelper?

**Comment by Railboy** [comment]
I will write a tool that sniffs out new icons from custom button materials and adds them to the icon list. Custom icons always required creating a new material so this should be pretty foolproof.
