### ISSUE TITLE
Corrupted SharedAssets0 after upgrading to MRTK 2.3.0

### ISSUE THREAD

**Issue by ylanluu-ms** [microsoft/MixedRealityToolkit-Unity#7815]
## Overview
Our project has been running on MRTK 2.2.0-20191003.3. After upgrading to Unity 2.3.0 and making script changes to address the namespace changes, our server builds and some instances of local builds have started crashing on startup on device, with this error:

The file 'c:/Data/Programs/WindowsApps/.../Data/sharedassets1.assets' is corrupted! Remove it and launch unity again!
[Position out of bounds!]

(Filename: Line: 220)

We've regressed our project temporarily back to MRTK 2.2.0-20191003.3 and our server builds and all local builds have started working again.

## Expected behavior
Once deployed on device, our application will run without any issues.

## Actual behavior
Once deployed on device, our application crashes and there is an infinite loop indicating "loading".

## Unity editor version
2018.4.16f

## Mixed Reality Toolkit release version
2.3.0

**Comment by keveleigh** [comment]
Is this still happening?

**Comment by keveleigh** [comment]
Going to close this out as no repro
