### ISSUE TITLE
Pointer doesn’t collide on gameObject with mesh collider on HoloLens 2 device

### ISSUE THREAD

**Issue by spartan1047** [microsoft/MixedRealityToolkit-Unity#7816]
## Describe the bug
When there is a 3D object that holds a Mesh collider, the pointer does not collide with the mesh. I found that this only happens when the app is running in the HoloLens 2 (no matter the build type), but in HoloLens 1 or the Unity editor the pointer behaves correctly. 

This happens only with the Mesh colliders, if you use any collider based on a primitive (Box collider, Sphere collider, etc...) the behavior is correct. 

I need to retrieve the hit point in runtime of loaded meshes wiht complex shapes so, using primitive shape colliders doesn't work for me. 

## To reproduce

1. Create a 3D primitive (or add any 3D model)
2. Add a Mesh collider
3. Build the VS solution
4. Create an appx for ARM64 as Master build.
5. Run the app on the HoloLens 2 
6. Try to put the pointer over the 3D object. 

## Expected behavior

The pointer should impact over the 3D model that holds the mesh collider. 

## Screenshots

Wrong behavior:
![imagen](https://user-images.githubusercontent.com/15834155/81233184-d4cbbe00-8fbb-11ea-8446-6547090f967b.png)

Correct behavior:
![imagen](https://user-images.githubusercontent.com/15834155/81233006-8dddc880-8fbb-11ea-9713-47b4b9386cb2.png)

A video showing the issue: 
https://youtu.be/2aZStzjbugs

## Your setup (please complete the following information)
- I'm using a Config profile that is a exact clone of the DefaultMixedRealityToolkitConfiguration profile with the profiler off and spatial mesh visualization off
- Unity Version: 2019.3.0f6
- MRTK Version 2.3.0
![thumbnail](https://user-images.githubusercontent.com/15834155/81235141-dbf4cb00-8fbf-11ea-94bb-d4a91bc1836e.png)

![CaptureCube](https://user-images.githubusercontent.com/15834155/81237361-11e87e00-8fc5-11ea-9541-8eb136aa0ee9.PNG)

## Target platform (please complete the following information)

- HoloLens 2 ARM64 Master build

## Additional context

This bug is only showed when the app is running in a Holo Lens 2 device, running in HoloLens 1 or the Unity editor, the pointer behaves as it should be.

**Comment by RTZCLE** [comment]
I have this exact same problem as I was able to confirm that box collider works while mesh collider does not.

**Comment by keveleigh** [comment]
Sounds like the issue tracked by Unity at https://issuetracker.unity3d.com/issues/bv4-midphase-only-supported-on-intel-platforms-appears-when-exporting-for-android

It's marked as fixed, but we're tracking the effects on HL2 with them separately.

**Comment by davidjeagle** [comment]
Have the same issue with all collisions on a runtime generated mesh with 2019.3.15 on HL2. Has always worked perfectly on HL1.

**Comment by davidjeagle** [comment]
Looks like it's fixed in 2019.4.1.

**Comment by wiwei** [comment]
Thanks @davidjeagle, closing this out

**Comment by coderFirework** [comment]
I fixed this problem by following https://issuetracker.unity3d.com/issues/bv4-midphase-only-supported-on-intel-platforms-appears-when-exporting-for-android
---------
Steps:
- Create an empty project(no ,I use the fbx gameobject )
- Add any non-animated mesh fbx to it, make sure 'Generate colliders' is checked in the import settings(yes)
- Make sure in the Player settings, 'Prebake collision meshes' is checked(yes)
- Build for Android(HL2 by unity 2019.4.0)
