### ISSUE TITLE
Getting Started Prerequisites Missing VS Installation Components

### ISSUE THREAD

**Issue by polar-kev** [microsoft/MixedRealityToolkit-Unity#7818]
## Describe the issue
The following Visual Studio components are missing from the "Getting Started with MRTK" page's list of prequisite tools to be installed. Proper context around each component should also be included.

- Desktop development with C++
- Universal Windows Platform (UWP) development
- USB Device Connectivity (required to connect to a HoloLens device)

## Existing doc link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html

## Additional Context
There is a more detailed list of prerequisites on another Microsoft HoloLens docs site, https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools

Users who start on the GitHub page may not come across this more detailed set of prereqs until after going through lots of troubleshooting.

**Comment by polar-kev** [comment]
this is still relevant.

**Comment by davidkline-ms** [comment]
@polar-kev, Can we modify our documentation to link to https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools to provide the guidance?

**Comment by polar-kev** [comment]
Let's use the link you mentioned as the main installation instructions moving forward.

**Comment by polar-kev** [comment]
New install the tools page created as part of docs migration.
