### ISSUE TITLE
Messages brodcasted lost with Sharing Service

### ISSUE THREAD

**Issue by fraspadafora** [Microsoft/MixedRealityToolkit-Unity#782]
Hi all,
I'm using the Sharing Service with CustomMessage to create a Master/Slave configuration between 2 hololens.

It's working fine but I have one problem, in some moments, specially when the slave joins the room, the master sends lot of messages and someone get lost and don't arrive to the slave.
If I put a Log before sending messages all works fine because the log slows the sending process.

I'm using the following method:

```
serverConnection.Broadcast(
  msg,
  MessagePriority.Immediate,
  MessageReliability.ReliableOrdered,
  MessageChannel.Avatar);
```

Anyone has an idea of how to solve the problem?

Thank you.

**Comment by StephenHodgson** [comment]
Shot in the dark here, but try making sure there's a connection between the two before sending messages?

**Comment by DKandrew** [comment]
Hi fraspadafora, 

I wonder how you achieve the master/slave configuration. Do you manually assign the priority to each HoloLens or have some automatic solution like "the first one join the session will be the master"? Would you share your idea to me? Thanks!

**Comment by StephenHodgson** [comment]
Sounds like you aren't reading/writing all your bits in the right order

**Comment by NeerajW** [comment]
Please reopen if your question was not answered.
