### ISSUE TITLE
Set NearInteractionTouchableVolume collider at runtime

### ISSUE THREAD

**Issue by hermann-noll** [microsoft/MixedRealityToolkit-Unity#7820]
## Describe the problem

In a couple of projects I would like to create MRTK components at runtime. Mostly this works fine, an exception found is `NearInteractionTouchableVolume` where the `touchableCollider` can only be set with the editor, either by user-interaction or by the `OnValidate` message.
I could not find a technical reason for this to not be possible (e.g. also hacking the value by using reflection seems to work fine), maybe I am missing something?

## Describe the solution you'd like

I would like to be able create the component at runtime, for this the `touchableCollider` has to be set at runtime. E.g. the component could search for a `Collider` component on the own GameObject (like `NearInteractionTouchable` is doing), or by having a `SetTouchableCollider` method (see also `NearInteractionTouchable`).

**Comment by Zee2** [comment]
#9199 fixed this issue.

**Comment by keveleigh** [comment]
Yep, as @Zee2 this issue has been fixed since 2.6 I believe, though I was tracking it via a different issue, so I missed closing this one! I took the path where NearInteractionTouchableVolume caches the collider of the object it's being added to automatically in `Awake()`
