### ISSUE TITLE
Hand joints invisible when using holographic remoting with Unity 2019

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#7830]
## Describe the bug
hands are invisible when using holographic remoting, influencing things like recordings. Hand rays still show up and touch/pinch/grab events still work

## To reproduce

Use holographic remoting in 2019 and see no hands.

## Your setup (please complete the following information)

- Unity Version 2019.3.12
- MRTK Version 2.4

**Comment by RogPodge** [comment]
Directly related to this issue (not having the DotNetWinRT package means we can't get the joints from the HoloLens 2) https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7239

Will try resolving the above issue as we get closer to stabilizing 2.4, but if it is unsuccessful we'll update the documentation to acknowledge the workaround: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html#msbuildforunity-package-import-via-writing-into-the-packagemanifest

**Comment by wiwei** [comment]
Clearing release blocker because it's not a regression (even if it's painful)

**Comment by RogPodge** [comment]
This also has a side effect of not allowing touch controls to work while doing holographic remoting. While we have a workaround with manually installing the DotNetWinRT package, is there anywhere to put Unity 2019 specific guidance so as to not confuse our users?

**Comment by RogPodge** [comment]
Mitigated/handled in pr #7848
