### ISSUE TITLE
PokePointer for every finger

### ISSUE THREAD

**Issue by crodriguezouterelo** [microsoft/MixedRealityToolkit-Unity#7837]
Hi! Great repositorie, I have been tinkering with the Quest focused branch for a while now.
However, I have not yet managed to make the PokePointer element work with every finger.
What am I missing? It should be easy to implement as each finger has its own skeleton with iterable names.

I have also tried to use the HandsManager prefab from the Oculus Framework along with the InteractableToolsSDKDriver. While my try found no avail, perhaps you could use these controllers to define the position of new PokePointer elements.

Sorry for the inconvenience and thanks in advance.

**Comment by Zee2** [comment]
This feature will be included in MRTK v3.

**Comment by RogPodge** [comment]
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/2608#issuecomment-892837732 addressing this specific issue will help get this issue completed as well.
