### ISSUE TITLE
Button aliasing inside and outside the its outline

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#7838]
## Describe the bug

The MRTK PressableButtonHoloLens2 has aliasing artifacts on the inside of its outline, which is controller in the Shader via Border Light -> Width %. It's not reacting to the aliasing settings

In the Image, you can see the edge of a cube in game view. Even though it's rotated a little, Anti-aliasing is good (2 times multi sampling). The inside however is still aliased and looks bad on devices other than Hololens.

For some reason, the quality of the button's outside anti-aliasing is still worse than the one from the cube.

## To reproduce

Putting cube and button next to each other and watching them while rotating slowly shows that the cube is smoother
When increasing the Round Corners margin this is getting worse or is in the state of ignoring anti-aliasing as well.

## Expected behavior

The out side and inside of the button are getting properly anti-aliased

## Screenshots

![image](https://user-images.githubusercontent.com/32508825/81560337-83437a80-9391-11ea-8303-8fbad91b82e5.png)

## Your setup (please complete the following information)

- Unity Version 2018.3.15f1
- MRTK Version mrtk_development

## Target platform (please complete the following information)

- Oculus Quest

**Comment by Alexees** [comment]
@Cameron-Micka Do you know if this can be fixed?

**Comment by Cameron-Micka** [comment]
@Alexees, you may be able to fix this using the "Edge Smoothing Value" property in the material inspector:

![image](https://user-images.githubusercontent.com/13305729/81582476-f5ea3100-9364-11ea-8418-7e6bcf24d1fa.png)

Note, this value will perform local anti aliasing on the interior edges and also the exterior edges if the material is transparent (or Additive). If you want local anti aliasing on non-round edged panels, simply set the unit radius to the min.

**Comment by Alexees** [comment]
@Cameron-Micka thanks so much. How come this is a slider? Does it have an impact on performance? What's the reason for it?

**Comment by Cameron-Micka** [comment]
@Alexees, for some reason I don't see your last comment (but I see the email):

> @Cameron-Micka thanks so much. How come this is a slider? Does it have an impact on performance? What's the reason for it?

I wish it was not a slider. My hope is to introduce an option where it is automatically calculated based on the pixel's distance from the camera and/or object's size. But, for now it is manual.

Also, it does have an impact on performance since it requires the material be transparent (blended) and adds a few extra shader instructions. So, I only recommend using it when the aliasing is quite obvious.

**Comment by Alexees** [comment]
> for some reason I don't see your last comment (but I see the email)

yeah, I felt stupid after writing it that I did not read the text in the image describing it, so I deleted it ;)

**Comment by Cameron-Micka** [comment]
Ah, no worries. It was a valid question for all to see!
