### ISSUE TITLE
Investigate removing version.txt files

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#7843]
Starting with MRTK v2.3, all assemblies now contain the product version number (via the AssemblyInfo.cs file).

The version.txt files that were previously used to give customers an indication of which MRTK was in use is no longer required. In fact, the assembly version is more reliable.

We should investigate the leaf issues (packaging?) related to removing these files for the next release.

**Comment by keveleigh** [comment]
Fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7986, as these files were removed.
