### ISSUE TITLE
MRTK Pointer Result Example Not Working on Hololens 1 Device

### ISSUE THREAD

**Issue by ikun03** [microsoft/MixedRealityToolkit-Unity#7850]
I have been trying to get my Hololens 1 to accept MRTK GGV pointers but it hasn't worked. Even the Pointer Result Example has not worked. The application does not accept air tap or any other gesture input and the pointer also does not change to the ring shape. **The examples work as intended in Unity Play simulator mode**.

## To reproduce

Run the MRTK 2.3 Pointer Result Example on Hololens 1 with Unity 2019.3.9f1.

## Expected behavior

Perform air tap to paste sticky notes on board

## Setup

- Unity Version [Unity 2019.3.9f1]
- MRTK Version [v2.3]

## Target platform
- HoloLens

## Additional context
I also had to add Tracked Pose Driver to the camera to get the camera movement working,

**Comment by keveleigh** [comment]
>I also had to add Tracked Pose Driver to the camera to get the camera movement working,

This likely means your project is using Unity's new XR SDK pipeline. In which case, you should be sure to [follow these steps](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html) to make sure you're using the correct MRTK profiles and settings.

If you want to go back to using the legacy XR pipeline (the one present in prior versions), you can uninstall the Windows XR Plugin package and make sure the Windows Mixed Reality plugin is installed under the [Unity package manager](https://docs.unity3d.com/Manual/upm-ui.html).

**Comment by ikun03** [comment]
It worked, I did the changes mentioned on the page and the Example works as intended. Thank you
