### ISSUE TITLE
UIEvents.IMGUIRenderOverlays

### ISSUE THREAD

**Issue by zhudaxing** [microsoft/MixedRealityToolkit-Unity#7851]
I use MRTK On Hololens1 .when I analyze performance By Unity Proflier .I found something strange. UIEvents.IMGUIRenderOverlays is to long.it is showing when I use OnGUI ?but I do not use OnGUI .then i found FrameDebugger also show something, there are many RenderEvent about GUI.Repaint.and i do not know what i Render ? EditorMode ,it is normal. this problem lead to  my frameCount so low .can you explain it for me?  what i do to solve it?
![C_YQS~JYQXE)MS~ZJT5CQB](https://user-images.githubusercontent.com/38905803/81645051-755a2c00-945b-11ea-8e22-a734885930f4.png)
![F2E41R)41Y11VIEMNV118GH](https://user-images.githubusercontent.com/38905803/81645061-7a1ee000-945b-11ea-999c-1c5a712f3096.png)

**Comment by wiwei** [comment]
@zhudaxing can you clarify the question about how MRTK is involved in this scenario? At first glance this seems like a HL1 + Unity perf question that may be specific to a particular application

**Comment by zhudaxing** [comment]
I think i found the problem.this GUI.Repaint showing because of  developerConsole .but I set development Build false. it do not work .and other people had same condition on UWP .just like this:
![image](https://user-images.githubusercontent.com/38905803/81762197-a17ab900-94fe-11ea-8125-fd9978bc4a5c.png)
there are some solution ,for example ,set solution Config Master In VS can close this console . I do not try it not yet because of build master error. and I want to know what other solution about this. 
![image](https://user-images.githubusercontent.com/38905803/81762515-6331c980-94ff-11ea-9067-d374db1384a4.png)
![image](https://user-images.githubusercontent.com/38905803/81762560-7d6ba780-94ff-11ea-80e7-687de21c0d03.png)

https://forum.unity.com/threads/how-can-i-remove-development-console-window-in-built-game.229171/

**Comment by zhudaxing** [comment]
![U7MJYTN~$_A9Y9UI8 H6@06](https://user-images.githubusercontent.com/38905803/81762694-dfc4a800-94ff-11ea-91b1-7f092d2640f1.png)
![HBE`{7%635EFA@}JNG0MF{R](https://user-images.githubusercontent.com/38905803/81762746-fff46700-94ff-11ea-850d-65d3b0d3ebb6.png)
