### ISSUE TITLE
MicrophoneTransmitter / MicrophoneReciever network stream mismatch

### ISSUE THREAD

**Issue by alankemp** [Microsoft/MixedRealityToolkit-Unity#786]
In the MicrophoneTransmitter class the direction of the audio source is added to the network stream:
[MicrophoneTransmitter.cs#L274](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Sharing/Scripts/VoiceChat/MicrophoneTransmitter.cs#L274)

But in the MicrophoneReciever the code to extract this has been commented out:
[MicrophoneReceiver.cs#L258](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Sharing/Scripts/VoiceChat/MicrophoneReceiver.cs#L258)

Immediately following the audio source direction in the stream is the audio buffer.  I think this means the audio data is read incorrectly, it actually takes the first 12 bytes from the direction vector and misses the last 12 bytes.

Fix is either to not add it to the stream, or to decode it and ignore it (or skip the stream forward by 12 bytes).

**Comment by StephenHodgson** [comment]
Thanks for the report.
