### ISSUE TITLE
Enabling 'Use palm kinematic body' in the hand physics service extension breaks hand tracking

### ISSUE THREAD

**Issue by MilanPolle** [microsoft/MixedRealityToolkit-Unity#7861]
When you are using the hand physics service extension and enable the 'use palm kinetic body' option, hand tracking no longer works.

To reproduce:
Open the HandPhysicsServiceExample.
In the projects window, select the DefaultHandPhysicsServiceProfile.
Enable the 'use palm kinematic body option'.
Build the project and deploy on the HoloLens 2.
Notice hand tracking no longer works.

Unity Version: 2019.3.13f1
MRTK Version: 2.3
Target platform: HoloLens 2

I fixed the problems I found by making the following changes to HandPhysicsService.cs:

Line 39: public GameObject HandPhysicsServiceRoot { get; private set; } = new GameObject("Hand Physics Service");
After line 198: jointKinematicBodies.Clear(); (this seems to be the root of the problem)
After line 218: if (parent == null) return false;

**Comment by keveleigh** [comment]
@radicalad Have you seen this?

**Comment by radicalad** [comment]
Ah, yes. this was brought up in #7786 and fixed in #7787.

**Comment by keveleigh** [comment]
Oh perfect, thanks! @MilanPolle, looks like this has been fixed for the MRTK 2.4 release.

**Comment by MilanPolle** [comment]
Sorry, I didn't come across those reported issues. Thanks for the quick replies and good to hear it has been fixed already.

**Comment by keveleigh** [comment]
>Sorry, I didn't come across those reported issues. 

All good! Thanks for taking the initiative in making sure an issue you were seeing gets reported
