### ISSUE TITLE
MRTK Debug menu entries in Unity GameObject menu

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#7864]
## Describe the bug

There's two menu entries under GameObject > MRTK in Unity after importing our foundation package that don't create a gameobject (even though putting an entry in this section would suggest a gameobject to be created).
After looking further into this I think this is just some debug functionality that sneaked in there by accident:
The menu options will log combined bounds of renderers or colliders of selected gameobjects.

## To reproduce

- Create a new project and scene
- Import the 2.4 foundation package
- Open the GameObject top menu in Unity and observe the MRTK section with debug entries

## Expected behavior

if we add a MRTK section into the GameObject menu I would expect that a GameObject with some MRTK component will be created. I would not expect an entry there that will give me a debug log output about some bounds calculation.

## Screenshots

![image](https://user-images.githubusercontent.com/36998103/81832821-dc004800-9536-11ea-8bbd-c6a98a83d834.png)

## Your setup (please complete the following information)

- Unity Version 2018
- MRTK Version 2.4

## Target platform (please complete the following information)

- Editor

**Comment by keveleigh** [comment]
>After looking further into this I think this is just some debug functionality that sneaked in there by accident

From what I remember, these were added intentionally in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7584:

>This PR adds a editor utility that allows one to get the Renderer or Collider world space bounds sizes for a selected GameObject.
>
>Right click gameobject > MRTK > Render/Collider Size => See output results in debug log console

I do agree that its placement in the menu is confusing though. Does it make more sense if it's pushed down to the other "action" (non-create) items in that menu? "Move To View" etc

**Comment by thalbern** [comment]
yes i can live with moving them down there!

**Comment by keveleigh** [comment]
Fixed via #7869
