### ISSUE TITLE
Holograms sticks to holocamera

### ISSUE THREAD

**Issue by DrunkReaperMatt** [Microsoft/MixedRealityToolkit-Unity#787]
The hologram in the scene is being moved to the origin (the cameras position) on startup. 

Using SpatialMapping, WorldAnchorManager, TapToPlace and InputManager in the scene.

**Comment by StephenHodgson** [comment]
Make sure you don't have a script that's changing the position of your object.

**Comment by DrunkReaperMatt** [comment]
I have no scripts that changes the position of the object attached to the hologram. Only the TapToPlace and the Interpolator scripts were added to my object, outside the script i created.

**Comment by StephenHodgson** [comment]
@DrunkReaperMatt did you ever figure out what the problem was?

btw we've updated the Hololens camera to the MixedRealityCameraParent, give it a try.
