### ISSUE TITLE
"Toggle MRTK Features" buttons are missing their toggle state visuals.

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7872]
## To reproduce

1. Run HandInteractionExample scene
2. Click toggle buttons
3. The toggle background should show for toggle buttons that are in 'on' state. The background does not actually show up for buttons that should be 'on', and toggling them does not change their background.

## Screenshots
Expected behavior from mrtk 2.3 examples hub:
![bug-toggle_expected](https://user-images.githubusercontent.com/168492/81853202-fc1d1080-9510-11ea-80f1-01c347d4c1ed.png)

Actual behavior in mrtk 2.4
![bug-toggle-actual](https://user-images.githubusercontent.com/168492/81853306-1f47c000-9511-11ea-982f-f1fa8a383595.png)

**Comment by keveleigh** [comment]
I think the hand interaction examples scene has always behaved this way, but the examples hub uses a different asset. Converting them to toggle buttons is tracked by https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7801

**Comment by cre8ivepark** [comment]
@julenka @keveleigh I'll update these and open PR.
