### ISSUE TITLE
Migration window error: Unable to load the icon: 'd_TimelineEditModeRippleOFF'

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7876]
## Describe the bug

When opening the migration window in 2.4, I get the following error in the Unity editor, and am not able to select a scene to migrate my assets.

![image](https://user-images.githubusercontent.com/168492/81862668-e3b3f280-951e-11ea-84cb-9c66260a1ec5.png)

## To reproduce

1. Open my 2.3 project, import MRTK 2.4 following upgrade steps
2. Import the tools package
3. Open the Migration window
4. Try to select a scene to perform upgradde

I noticed the error and am not able to select a scene to perform the upgrade.

## Your setup (please complete the following information)

- Unity Version 2019.3.13f1
- MRTK Version 2.4. Upgrading from 2.3 to 2.4

**Comment by keveleigh** [comment]
Fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7925
