### ISSUE TITLE
XRSDK: No boundary displayed in VR when a boundary is configured

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#7878]
In comparing legacy XR apis and XR SDK, i am not seeing a boundary displayed in VR using XR SDK and the associated profile

Repro:
* Open Unity 2019.3, import MRTK packages (Foundation and Examples)
* Add the Windows XRSDK package
* Load Audio Lo-Fi Demo
* Switch to the DefaultXRSDKConfigurationProfile
* Ensure a boundary is configured on the device
* Build and deploy UWP project
* Run on device, note no floor or boundary

**Comment by keveleigh** [comment]
@davidkline-ms Looks like the `XRDevice.isPresent` API is [not expected to work in XR SDK](https://forum.unity.com/threads/xrdevice-ispresent-with-xrmanagement-on-quest.817722/). I'll update.

**Comment by dahaideyu** [comment]
No boundary displayed in my hololens2 ,and I using to XR SDK in unity2019.4.3 and MRTK2.4.0,
scene is  using MRTK2.4.0 example

**Comment by dahaideyu** [comment]
> 
> 
> @dahaideyu Boundary isn't supported on HoloLens 2, only on the immersive headsets.

in hololens2 ,how to do? what I using to?
