### ISSUE TITLE
Remove Gaze Source button from Hand Interaction Examples scene until platform feature is supported

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#7884]
## Describe the bug

Right now, that button doesn't really do anything, since the platform API returns the same data we'd get from using the camera's forward for head gaze.

It's been proposed to remove this the prevent confusion until the platform feature is widely available. It will also need docs when it's re-added.

**Comment by tank-t-bird** [comment]
I was wondering why it didn't work. @keveleigh  does this mean that it is not possible to switch from Hand Ray controls to Eye Gaze controls during Runtime yet?

**Comment by keveleigh** [comment]
@tank-t-bird Ah, this button is also a bit misleading! I'll be sure to add documentation when it's re-added.

Basically, the idea behind this button was to switch the gaze ray's source from using the camera's position to using a platform-supplied value. More info can be found at #6436.

For your scenario:

>does this mean that it is not possible to switch from Hand Ray controls to Eye Gaze controls during Runtime yet?

I haven't fully tested this out, but we have [some sample code](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Pointers.html#disable-pointers) on toggling between various types of pointers, including what sounds very similar to your scenario.

**Comment by tank-t-bird** [comment]
Thank you for the links, tips and clarification @keveleigh ! it would be great if one of the EyeTracking examples had a toggle button prefab demonstrating this.  I'll try to do implement something with the example code you have provided.
