### ISSUE TITLE
Input Recording feature is not working in MRTK Examples Hub

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#7890]
## Describe the bug
I found that Input Recording feature is not working in MRTK Examples Hub scene. Verified that it is not the button/toggle features panel problem since it works in other scenes. It could be related to the custom profile for the MRTK Examples Hub scene. I see there is Input Recording Service in the MRTK profile. Not sure why it shows Null Reference Exception.

## Repro Steps
1. Open MRTKExamplesHub scene
2. Play
3. Press Input Recording button. Check error messages

Compare with Input Recording button on other scenes that work properly. 

![2020-05-14 22_47_27-Unity 2018 4 21f1 Personal -  PREVIEW PACKAGES IN USE  - MRTKExamplesHub unity -](https://user-images.githubusercontent.com/13754172/82016351-b4dc7000-9635-11ea-8dc7-5edc09f14880.png)

Verified that both ToggleFeaturesPanel and ToggleFeaturesPanelExamplesHub have these function calls on OnClick().
![2020-05-14 22_53_42-Unity 2018 4 21f1 Personal -  PREVIEW PACKAGES IN USE  - MRTKExamplesHub unity -](https://user-images.githubusercontent.com/13754172/82016396-caea3080-9635-11ea-806e-1ca82b6c4938.png)

## Error Message
NullReferenceException: Object reference not set to an instance of an object
Microsoft.MixedReality.Toolkit.**Input.InputRecordingService.PruneBuffer** () (at Assets/MRTK/Services/InputAnimation/InputRecordingService.cs:322)
Microsoft.MixedReality.Toolkit.Input.InputRecordingService.set_UseBufferTimeLimit (System.Boolean value) (at Assets/MRTK/Services/InputAnimation/InputRecordingService.cs:103)
Microsoft.MixedReality.Toolkit.UI.InputRecordingControls.ToggleRecording () (at Assets/MRTK/SDK/Features/UX/Scripts/Utilities/InputRecordingControls.cs:60)
UnityEngine.Events.InvokableCall.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:166)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:58)
Microsoft.MixedReality.Toolkit.UI.Interactable.SendOnClick (Microsoft.MixedReality.Toolkit.Input.IMixedRealityPointer pointer) (at Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs:1251)
Microsoft.MixedReality.Toolkit.UI.Interactable.TriggerOnClick () (at Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs:1241)
Microsoft.MixedReality.Toolkit.PhysicalPressEventRouter.OnHandPressTriggered () (at Assets/MRTK/SDK/Features/UX/Scripts/PressableButtons/PhysicalPressEventRouter.cs:90)
UnityEngine.Events.InvokableCall.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:166)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:58)
Microsoft.MixedReality.Toolkit.UI.PressableButton.UpdatePressedState (System.Single pushDistance) (at Assets/MRTK/SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs:480)
Microsoft.MixedReality.Toolkit.UI.PressableButton.UpdateTouch () (at Assets/MRTK/SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs:304)
Microsoft.MixedReality.Toolkit.UI.PressableButton.Update () (at Assets/MRTK/SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs:289)

**Comment by RogPodge** [comment]
Hey Yoon, I notice that none of the buttons in the MRTKExamplesHub.Unity scene's ToggleFeatures Panel seems to work, and I'm also seeing these errors on startup

![image](https://user-images.githubusercontent.com/39840334/82102626-f5cf9580-96c4-11ea-8912-9306e5564c45.png)

**Comment by cre8ivepark** [comment]
@RogPodge That's probably because there are two instances in the scene. To use Examples Hub, you need to deactivate/hide ToggleFeaturesPanel in each scene. (we don't have automated script for this yet) Cursor error might be related to the runtime profile loading but not sure.

**Comment by cre8ivepark** [comment]
I'll remove the Input Recording Button in the Examples Hub's ToggleFeaturesPanel since the feature is not that relevant for the examples demo.
