### ISSUE TITLE
App remoting.dll not found when using the XR SDK

### ISSUE THREAD

**Issue by FSchmidNT** [microsoft/MixedRealityToolkit-Unity#7894]
When trying to build my UWP app created in Unity via Visual Studio for the HoloLens 2 the following error occurs:  Error MSB3030 Could not copy the file "...\Plugins\ARM64\Microsoft.Holographic.AppRemoting.dll" because it was not found.
In this build I am trying the new XR SDK from Unity. Since I just wanted to try it out, there is only one cube in the scene. 

## Your setup (please complete the following information)
- Unity Version 2019.3.4f1
- MRTK Version 2.3

## Target platform (please complete the following information)
- HoloLens 2

**Comment by tank-t-bird** [comment]
This happens with or without the new XR SDK. The error can be made to go away if you disable WSA Holographic Remoting Supported (assuming you don't need this) in the PLayer XR Settings . Remoting in the editor should still work.

**Comment by FSchmidNT** [comment]
There are no "WSA Holographic Remoting Supported" options enabled. 
Settings under Player/XR Settings are depricated disabled and not editable. Also in the XR Plugin Management/ Windows Mixed Reality menu Holographic Remoting ist disabled. So i forgot any Settings?

**Comment by tank-t-bird** [comment]
Ah my bad, I am not currently on the new XR version, that was a wrong assumption on my behalf.

**Comment by zantiu** [comment]
Same issue here:

- Unity 2019.3.7f1
- MRTK 2.4
- Hololens 2

**Comment by keveleigh** [comment]
I believe this was fixed in Unity 2019.3.9 and later. Closing as External, but will monitor for follow-up questions.
