### ISSUE TITLE
Loss of Spatial Mapping Causes Phantom Hand Tracking

### ISSUE THREAD

**Issue by jcady** [microsoft/MixedRealityToolkit-Unity#7896]
## Describe the bug
I'm fairly reliably encountering an issue with hand tracking when Hololens 2 loses its spatial mapping. I reproduced this issue in the linked YouTube video. In the video, you can see me opening the hand menu and then intentionally causing the HL2 to lose its spatial mapping (via a beat-up curtain).

After the spatial mapping is regaining a couple weird things happen. First, the hand models no longer leave the screen. When my hands are lowered off camera, the hand mesh visualizations persist.

The second odd thing is that the hand menu gets stuck floating in space with a phantom hand joint visualization. It's impossible for me to dismiss this visualization or the hand menu and it prevents the hand menu from reappearing when my actual hand is raised. It does not seem to be interactable, only able to be nudged, as shown in the video. The only solution is to quit the app and restart.

Has anyone else encountered this odd issue? This will be a big issue for us to fix, as we've encountered it numerous times just in testing our application.

(apologies for the happy pup squeaking the toy 😄)

## To reproduce
1. Create hand menu using `HandConstraintPalmUp`.
2. Activate hand menu by raising palm. [unsure if necessary]
3. Cause HL2 to lose its spatial mapping. [may require spatial mapping jitter (i.e. lose the mapping and regain it multiple times in quick succession]
4. Observe phantom joint visualization and stuck hand menu in air.
5. Observe hand mesh visualizations not disappearing when hands are outside of view.

It's not 100% deterministic using these steps. It may be that some condition with the spatial mapping jitter is required to reproduce the issue.

## Expected behavior
After regaining the spatial mapping:
- There is no phantom hand floating with the hand menu.
- Hand tracking/visualization meshes do not persist after lowering hands out of view.
- The hand menu correctly appears when raising your palm.

## Screenshots
https://www.youtube.com/watch?v=XeYQ1qaYFVE

## Your setup

- Unity: 2018.4.21f1
- MRTK: 2.3.0

## Target platform
- Hololens 2

**Comment by Strepto** [comment]
I have also seen this bug. MRTK 2.4.0.  Unity 2019.4.7. Legacy Mixed Reality Plugin. 

Needed forced restart to restore tracking for that hand. 

Observed while using Remote Assist, no recording or logs available.

**Comment by xwipeoutx** [comment]
I've also seen this happen - I didn't link it to the spatial mapping, but it seems to happen in spikes in processing activity (deserializing a large JSON for example), which would also kill spatial mapping for a bit.

https://user-images.githubusercontent.com/1008567/105658394-1cabc000-5f12-11eb-8239-d9b58d210238.mp4

**Comment by keveleigh** [comment]
I haven't been able to repro this :/ possibly fixed by #9890? Going to close out, but please re-open if you're able to repro with MRTK 2.7
