### ISSUE TITLE
Editor 2017.2 compilation issues

### ISSUE THREAD

**Issue by Jihosong** [Microsoft/MixedRealityToolkit-Unity#790]
Hi,

I got a HoloLens for a research project at school. I have downloaded a Toolkit here.
I am on Unity 2017.2.0b3. I believe I set everything right... But at my console, I am getting this error, only this one.

Assets/HoloToolkit-Examples/SpatialUnderstanding/SpatialUnderstanding-FeatureOverview/Scripts/SpaceVisualizer.cs(8,22): error CS0234: The type or namespace name `WSA' does not exist in the namespace `UnityEngine.VR'. Are you missing an assembly reference?

I googled for the issue. I couldn't solve the problem. Any idea?

**Comment by keveleigh** [comment]
Unity has changed that namespace from `UnityEngine.VR` to `UnityEngine.XR`. Everything under the namespace should be the same, from my experience!

**Comment by Jihosong** [comment]
Thanks! It works. But... I am facing another problem... Typical. haha

**Comment by StephenHodgson** [comment]
Thanks for the heads up.

**Comment by jessemcculloch** [comment]
The namespace change is one part of it.  Some of the handlers have changed in the SDK as well.  This resolves about 90% of the issues.

**Comment by StephenHodgson** [comment]
I'm going to go ahead and close this. Please be sure to use the Dev-2017.2 branch.
