### ISSUE TITLE
AssemblyInfo.cs (Error CS0579) duplicate attributes

### ISSUE THREAD

**Issue by amfdeluca** [microsoft/MixedRealityToolkit-Unity#7911]
## Describe the bug

Today I changed the PC on which I work and I cloned the project, after opening it the console continues to give me these errors, I state that on the other PC I have no errors of this type. I don't understand why it only occurs on this computer. Do you have any advice or has it ever happened to you?

## Expected behavior

No error

## Screenshots

![Screenshot (97)](https://user-images.githubusercontent.com/56428422/82331272-2fb1dc00-99e4-11ea-8d25-d3ed538ab028.png)

## Your setup

- Unity 2019.2.21f1
- MRTK 2.3.0

## Target platform

- HoloLens 2

**Comment by keveleigh** [comment]
Huh, I haven't seen this before. Does that folder somehow have multiple AssemblyInfo files?
Is this the MRTK project you cloned, or your own project?

**Comment by amfdeluca** [comment]
Hi, no, only one AssemblyInfo file in that folder, the problem does not occour if i clone the repo from gitbash and not from a gitclient
