### ISSUE TITLE
Blank Screen via Hololens 2 Remoting

### ISSUE THREAD

**Issue by InitusJames** [microsoft/MixedRealityToolkit-Unity#7914]
Unity 2019.3.13f1
MRTK
Hololens 2
 
I installed the Remoting App on the Hololens.
I successfully connect to the HL2 via Unity Remoting Windows. 
I can see the Remoting App screen disappears when it connects, just a blank screen.

When pressing play on Unity... nothing. I've enabled the HL2 "enable diagnostics", nothing changes.
It seems connected, no unity errors.

I was expecting to see something from the scene or even see the camera sync to the HL2 head movements. Nothing.

Any ideas?

**Comment by InitusJames** [comment]
Conflicting libraries, this is no longer an issue

**Comment by doys** [comment]
> Conflicting libraries, this is no longer an issue

@InitusJames could you elaborate what libraries were conflicting? i experience a similar issue, remoting connects and the screen of the HL 2 stays blank. For me the Editor acts as if its connected though, following interactions and head movements of the device.

**Comment by camnewnham** [comment]
I'm  experiencing the same issue as @doys in 2019.4.9f1 and MRTK 2.4.0 where my head and hands are tracked as expected in the editor, but nothing is rendered on the device.
