### ISSUE TITLE
Leapmotion not working in Unity editor when platform is UWP

### ISSUE THREAD

**Issue by rolandsmeenk** [microsoft/MixedRealityToolkit-Unity#7916]
## Describe the bug

After adding LeapMotion to the project ([as described here](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/CrossPlatform/LeapMotionMRTK.html)) and the platform is set to UWP LeapMotion will not run in the Unity Editor. 

<img width="1920" alt="LeapmotionEditorUWP" src="https://user-images.githubusercontent.com/480316/82369627-9ef4f380-9a17-11ea-80a3-616c77701738.png">

Cause: The LEAPMOTIONCORE_PRESENT is only added to the Standalone BuildTargetGroup.

## Additional context

First step to PR

**Comment by CDiaz-MS** [comment]
Hi @rolandsmeenk 
The Leap Motion Data Provider documentation notes that only Standalone is currently supported under step 5 in the configuration process: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/CrossPlatform/LeapMotionMRTK.html

**Comment by wiwei** [comment]
It might be helpful for iteration speed (i.e. if someone is targeting UWP and they don't want to switch to standalone to do development). The only thing we have to be careful here is around not making it seem like it's supported for deployment (it's not) - so we'd have to add errors/messages/warnings when trying to actually build for real.

**Comment by wiwei** [comment]
Otherwise we'll start getting the opposite bugs - i.e. people who are filing issues because leap isn't working in UWP (despite the fact that it's not supposed to work when deployed as real UWP)

**Comment by rolandsmeenk** [comment]
I am aware that leapmotion cannot be used in a UWP app, but it can be used in the editor.
The PR that I submitted takes this into account. When developing for HoloLens I would want to test interactions in the editor with help of the leapmotion without having to switch between platforms.

**Comment by CDiaz-MS** [comment]
Interactions can be tested in editor on Standalone and then the platform can be switched to UWP when you need to build your app for HoloLens.  It might be confusing to support a certain platform but only in the editor and not a build.  Testing the PR now and the build is successful for UWP when it should not be, so we would need to add guards.

**Comment by rolandsmeenk** [comment]
I don't understand why the build should not be successful. I think it should be. The Leapmotion DLL is not included in a UWP build and the defines in the PR take care that the LeapMotionDeviceManager has no active implementation when building as UWP app.

You can run the LeapMotionHandTracking example in the editor with platform set to UWP and use the LeapMotion hand tracking. And then build and deploy to HoloLens 2 and use the HoloLens hand tracking.
