### ISSUE TITLE
Remoting "Connect" button is non-functional

### ISSUE THREAD

**Issue by InitusJames** [microsoft/MixedRealityToolkit-Unity#7929]
## Describe the bug

The editor window that allows you to connect and disconnect has an issue with the "button". Although it's NOT greyed out it does not allow pressing. It acts like a non-functional component.

## To reproduce

Pull up the Menu, attach to an HL2, shut the editor window down, Play, Stop, re-open the editor window.

## Expected behavior

the button should work

## Your setup (please complete the following information)

- Unity Version 2018.3.21f1
- MRTK Version v2.30

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

You need to restart Unity and attempt the action again. Sometimes it doesn't work, it seems random and is a very difficult tool to work with.

**Comment by keveleigh** [comment]
Editor remoting support is a Unity component, not an MRTK one. Which version of the Windows Mixed Reality package are you using in the Unity Package Manager? This sounds like an issue we had with a previous version of the package. It might be worth checking for updates.
There have also been some fixes for the remoting window in recent builds of Unity 2018.4, if you're able to update your editor.
