### ISSUE TITLE
No spatializer was specified

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#7949]
## Describe the bug

When importing the foundation package into Unity, the process fails to import the 'ExampleSpatialMesh.room' asset, and the AssetDatabase Refresh warning is shown. This happens in 2018.4 and 2019.3, see the screenshotsfor specifics.

## To reproduce

1. Create new project
2. Import Foundation package
3. Apply Project Configuration
4. Check console 

## Expected behavior

No errors displayed in console after initial MRTK Foundation package import. The console should be error free.

## Screenshots

<img width="1691" alt="Spatializer error" src="https://user-images.githubusercontent.com/65038391/82698908-8c013f80-9c20-11ea-9450-6d9629a7d97c.png">

<img width="1913" alt="Spatializer error2019" src="https://user-images.githubusercontent.com/65038391/82699471-95d77280-9c21-11ea-8c3f-a88a98b4b63b.png">

## Your setup (please complete the following information)

- Unity Version 2018.4, 2019.3
- MRTK Version 2.4

## Target platform (please complete the following information)

-Unity

**Comment by elbuhofantasma** [comment]
Additionally if one imports the examples package after this error occurs, the errors in the pictures below happen. This happens in 2018.4 and 2019.3

<img width="1525" alt="2019exampleimport" src="https://user-images.githubusercontent.com/65038391/82713262-3720f180-9c3f-11ea-8d4a-7a3f6dd38633.png">

<img width="1701" alt="2018exampleimport" src="https://user-images.githubusercontent.com/65038391/82713269-3daf6900-9c3f-11ea-9432-a1a7be6aa0c4.png">

**Comment by davidkline-ms** [comment]
I can quiet these non-fatal warnings.
