### ISSUE TITLE
Massive gap in MRTK profiles on Unity 2019.3.13f1, personal

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7959]
## Describe the bug
There is a large visual gap in the MRTK profile inspector, when on Unity 2019.3.13f1, on the personal skin only. The pro (dark) skin does not show this gap.

Personal view:
![image](https://user-images.githubusercontent.com/168492/82716505-96d1c980-9c4c-11ea-8776-be23d6c0235f.png)

Pro view:
![image](https://user-images.githubusercontent.com/168492/82716483-7a359180-9c4c-11ea-8d14-ca5291a1ce73.png)

**Comment by keveleigh** [comment]
Huh! This sounds like what I was seeing in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6330, but I thought Unity fixed it. Maybe there's something off with our logo file in that color?
