### ISSUE TITLE
GrabPointer not grabbing for Motion Controllers

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#7961]
## Describe the bug

When trying to grab something with a motion controller, nothing is happening

## Expected behavior

Grabbing works

## Your setup (please complete the following information)

- Unity Version 2019.3.14f1
- MRTK Version mrtk_development

## Target platform (please complete the following information)

- Oculus Quest

**Comment by provencher** [comment]
@Alexees seeing as you're targeting Quest, have you taken a look at [MRTK-Quest](https://github.com/provencher/MRTK-Quest)?

**Comment by Alexees** [comment]
@provencher oh, nice to know. No I haven't. I guess by the time we started using MRKT for the Quest I was one of the first to add it myself I guess. But we never made it past the controllers for Quest and Go.
Might check this out sometime
