### ISSUE TITLE
Scrolling Object Collection causes TextMeshPro MissingReferenceExceptions outside of example scene

### ISSUE THREAD

**Issue by Pycorax** [microsoft/MixedRealityToolkit-Unity#7963]
## Describe the bug
When copying any of the Scrolling Object Collection sample objects (with text) outside of the Scrolling Object Collection example scene, scrolling the list would cause the following error to appear:
```
MissingReferenceException: The object of type 'Material' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
TMPro.TextMeshPro.GenerateTextMesh () (at Library/PackageCache/com.unity.textmeshpro@2.0.1/Scripts/Runtime/TMPro_Private.cs:1969)
TMPro.TextMeshPro.OnPreRenderObject () (at Library/PackageCache/com.unity.textmeshpro@2.0.1/Scripts/Runtime/TMPro_Private.cs:1549)
TMPro.TextMeshPro.Rebuild (UnityEngine.UI.CanvasUpdate update) (at Library/PackageCache/com.unity.textmeshpro@2.0.1/Scripts/Runtime/TextMeshPro.cs:241)
```

## To reproduce
1. Create a new Unity project
2. Import MRTK and MRTK Examples packages
3. Open `ScrollingObjectCollection.unity`
4. Press play and verify that scrolling any of the Scrolling Object Collection objects has no errors
5. Copy any of the Scrolling Object Collection objects that has text on it
6. Create a new scene
7. Select `Mixed Reality Toolkit/Add to Scene and Configure...`
8. Paste the Scrolling Object Collection objects that we have copied
9. Press play and try scrolling any of the Scrolling Object Collection objects
10. The error indicated above will appear

## Expected behavior
Users should be able to copy the sample over and modify it for my own use without running into any errors

## Your setup

- Unity Version 2019.3.14f1
- MRTK Version 2.3.0
- TextMeshPro Package Version 2.0.1

## Target platform 

- HoloLens
- HoloLens 2
- Android
- iOS

**Comment by bcol23** [comment]
I've also encountered the same problem in 2019.3.12f (macOS) with TextMeshPro 2.0.1.
change **line 2094** in _/com.unity.textmeshpro@2.0.1/Scripts/Runtime/TMPro_UGUI_Private.cs to_

`if (m_currentMaterial != null && m_currentMaterial.HasProperty(ShaderUtilities.ID_GradientScale))`

seems like to fix the problem.
