### ISSUE TITLE
Refactor teleport for articulated hand usage, not just thumbstick/touchpad

### ISSUE THREAD

**Issue by machenmusik** [microsoft/MixedRealityToolkit-Unity#7964]
## Describe the bug

Currently the TeleportPointer has code that responds to 2D axis input from a thumbstick or touchpad, and also includes rotation and movement semantics that are not teleport functionality.  As such, it can't be used with articulated hands even though much of the code is independent.

## To reproduce

This can be seen by adding the ParabolicPointer (which has a ParabolicTeleportPointer in it) to articulated hand (disabled by default) and noticing that it does nothing.

## Expected behavior

Expectations
- Teleport functionality can be invoked in some fashion using articulated hands.
- 2D axis behaviors such as strafe and rotation should be available for relevant controllers, but separated from teleport.

- It may also be useful to provide a way for articulated hands to generate 2D axis data, but in that case it seems highly unlikely that other behaviors such as strafe and rotation would want to be included by default.

## Your setup (please complete the following information)

- Unity Version 2018.4.23f1
- MRTK Version v2.3.0+

## Target platform (please complete the following information)

- HoloLens 2
- OpenVR / WMR immersive
- also Quest (see https://github.com/provencher/MRTK-Quest)

## Additional context

Thanks for the excellent discussion in HoloDevelopers Slack at
https://holodevelopers.slack.com/archives/CTW7K59U4/p1590468076355100?thread_ts=1590361318.325600&cid=CTW7K59U4

**Comment by provencher** [comment]
I think this goes beyond simply the teleport pointer.

Going forward, SteamVR is pushing the standard for articulated hands to be the default, even with controllers such as touch. With Index being the first to support fully articulated hands with controllers, it makes sense for such controllers to be labelled as articulated hands, even if they're technically controllers.

@machenmusik put it well in the thread on slack discussing this:
"Ideally it would be more like traits, if you have a poke pointer and and index pose you can do hand like things, if you have buttons and sticks you can do controller like things."

**Comment by provencher** [comment]
Related bug report:
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7965

**Comment by keveleigh** [comment]
Also conceptually related: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6527

**Comment by polar-kev** [comment]
Teleportation with a teleport gesture is now supported in MRTK 2.6.
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/release-notes/mrtk-26-release-notes#teleportation-with-the-teleport-gesture-now-supported-on-all-platforms
