### ISSUE TITLE
Delete key does not work in MixedRealityKeyboardBase Unity 2019.3.13f1

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#7970]
## Describe the bug

Pressing the delete key when using MixedRealityKeyboardBase does not delete the text entered. Reproduces for all classes that extend MixedRealityKeyboarBase

## To reproduce

1. Build HandInteractionExamples scene  in Unity 2019.3.*
2. Run on HoloLens 2
3. Under "keyboard Interaction, press the keyboard button
4. Type some text
5. Press delete key

Notice keyboard text does not get deleted

## Expected behavior

Keyboard text gets deleted

## Your setup (please complete the following information)

- Unity 2019.3.13f1
- MRTK Version 2.4

## Additional context

This does not repro when building with Unity 2018

**Comment by keveleigh** [comment]
@julenka Is this a duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7813?

**Comment by keveleigh** [comment]
Closing as a duplicate of #7813
