### ISSUE TITLE
Update folder names in the Updating.md for MRTK 2.5 

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#7975]
## Describe the issue

The upgrade steps in the Updating.md should reflect the new folder structure.  

For example, MixedRealityToolkit.Providers should be changed to MRTK > Providers.

The steps are valid for 2.3 -> 2.4 but the names will need to be changed for 2.4 -> 2.5

## Existing doc link
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Documentation/Updating.md#upgrading-to-a-new-version-of-mrtk

**Comment by wiwei** [comment]
Great issue, thanks for filing this one!

**Comment by davidkline-ms** [comment]
This was resolved by https://github.com/microsoft/MixedRealityToolkit-Unity/commit/a077467a3c3e7d3eb75a50e28c9388a69a97c6ac
