### ISSUE TITLE
Prefabs objects created by the toolbox does not inherit its original state

### ISSUE THREAD

**Issue by decoc** [microsoft/MixedRealityToolkit-Unity#7988]
## Describe the problem

Prefabs objects created by the toolbox does not inherit its original state. I think this will affect future version updates.

## Describe alternatives you've considered

MixedRealityToolboxWindow uses Instantiate() to generate prefabs, but how about using PrefabUtility() instead?

**Comment by keveleigh** [comment]
Oh, interesting! Can you expand on what you mean by "does not inherit its original state". I want to make sure I understand the issue here.

**Comment by Zee2** [comment]
Hi, we are going to close this issue, unless there is additional information available or reproduction steps. Please reopen if you'd like further support on this issue.
