### ISSUE TITLE
Custom profiles are not selectable after updating MRTK

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#7992]
Following the update process

* Close Unity
* Delete MRTK folders (not MixedRealityToolkit,.Generated)
* Load Unity
* Import updated MRTK packages

results in custom profiles not appearing in the selection dropdown (for example)

![image](https://user-images.githubusercontent.com/13281406/83195155-a3dc3600-a0ee-11ea-8d8a-c05a5247b581.png)

The list shown should contain "CoreProfile" from the MixedRealityToolkit.Generated/CustomProfiles folder.

![image](https://user-images.githubusercontent.com/13281406/83195258-cff7b700-a0ee-11ea-8fa4-cbb5a13c4da6.png)

Unity version: 2018.4.23f1
MRTK version: 2.4.0

**Comment by wiwei** [comment]
@davidkline-ms I think that this issue has been reported before and we have specific instructions for how to avoid it:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Updating.html#unity-asset-unitypackage-files

I noticed that the listed instructions above weren't exhaustive (i.e. the second library delete is critical)

**Comment by wiwei** [comment]
Closing this out - it's addressed by the upgrade instructions that are provided in our docs.
