### ISSUE TITLE
BoundingBox resizes collider OnDisable

### ISSUE THREAD

**Issue by lmaxsmith** [microsoft/MixedRealityToolkit-Unity#7997]
## Describe the bug

When I'm using boxPadding, it seems to treat the rig creation differently than rig destroy. Everytime the object turns off, the bounding box size is reduced (linear). 

## To reproduce

1. Create an interactable object
2. add a box padding
3. Turn the object on and off and watch the collider slowly shrink

## Expected behavior

The permanent collider used as override should not be changed. It seems that you are growing the targetbounds on creation, but shrinking the bounds override. 

## Your setup (please complete the following information)

- Unity Version 2019.3.1f1
- MRTK Version v2.3

## Target platform (please complete the following information)

- HoloLens

**Comment by Zee2** [comment]
Thanks for the report. I'll take a look at this.
