### ISSUE TITLE
Unable to get Air-Tap working in MRTK v2.4 on HoloLens 1 using Unity 2019.3.4f1

### ISSUE THREAD

**Issue by Shiloh-James-ELC** [microsoft/MixedRealityToolkit-Unity#7998]
## Describe the bug

We're trying to get Air-Tap working on HoloLens 1 using the MRTK v2.4, however, while we _are_ able to get simulated air-tap events working in the editor (using LB+A on an Xbox 360 Controller for Windows), we have not been able to get elements of any kind within the app to respond to gestures after deploying the app to a HoloLens 1 device.

We have built this test app using the components provided in the MRTK 2.4 packages:
* MRTK/SDK/Features/UX/Interactable/Prefabs/ButtonHoloLens1.prefab
* MRTK/SDK/Features/UX/Interactable/Prefabs/UnityUIInteractables/UnityUIButton.prefab

Our assumption is that these components should be drag-and drop, and should work after linking in our target event in the appropriate location. However it appears that these components aren't working as we expect.

Neither Unity.UI Canvas-based elements nor collider-based elements are registering air-tap gestures. Both types of objects are responding to gaze, and the app appears to be detecting a hand in a 'Pinch' (or closed fist) gesture as well as in a 'Ready' gesture, however it does not appear to be recognising or responding to the standard HoloLens Air-Tap gesture.

Further, when building the HandInteractionExamples scene to a Hololens device, we still see no gesture-based interaction with any of the elements in that scene. This is true both with and without the following edits to the scene:
* Adding a 'Tracked Pose Driver' component to the main camera (without this, all content is gaze-locked).
* Using 'DefaultHoloLens2ConfigurationProfile' (the app doesn't respond to gesture input at all), the pre-configured setting for this scene.
* Using 'DefaultXRSDKConfigurationProfile' (app does seem to detect hands, but does not detect an air-tap gesture), as recommended here: https://hololabinc.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html
* Using 'DefaultHoloLens1ConfigurationProfile' (the app doesn't respond to gesture input at all), ALSO as recommended at the above link. This recommendation conflicts with the above recommendation by the way, and the documentation makes it unclear which we should be using.

I should note that the only time the application was able to detect my hands at all was when using the 'DefaultXRSDKConfigurationProfile' configuration profile.

We do not currently have access to a HoloLens 2 device so we are unable to determine whether any input functionality is working on that platform. Ideally we want air-tap to work on both device types, but it is most critical that it works on HoloLens 1.

## To reproduce

1. Download our example project at: https://drive.google.com/file/d/1s5ZfOwxrDwmksSB2e0yRoNcZi3RU9MF5
2. Launch the project in Unity 2019.3.4f1.
3. Ensure confirguration of the project complies with the instructions located at: https://hololabinc.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html
4. Build the app and deploy to a Hololens 1 device.
5. Run the app on the HoloLens 1 device.
6. Observe the gaze cursor and confirm that the application is detecting 'Pinch' and 'Ready' gestures.
7. Attempt to air-tap any/all of the buttons, and/or the red sphere.
8. Observe that no change occurs to the green cube, indicating that no air-tap gesture is detected by the application on any of these elements.

## Expected behavior

* The application should detect an air-tap gesture performed by the user.
* The gaze cursor should respond when user performs an air-tap gesture.
* The buttons should respond to air tap gestures by firing their OnClick, etc. events.
* The example scenes should function as advertised for Hololens 1, or alternate scenes should be included that demonstrate how to configure the application for Hololens 1 gesture inputs.

## Your setup (please complete the following information)

- Unity Version: 2019.3.4f1
- MRTK Version: v2.4

## Target platform (please complete the following information)

* HoloLens (primary platform)
* HoloLens 2 (secondary platform)

## Additional context

We've been all over the interwebs looking for any working solution to this issue, and we've encountered myriad examples of other people who have also had difficulty getting air-tap to work. Unfortunately we've tried every solution offered up in these examples and not one of them has solved our issue, or affected it in any way.

What we have also found is that there's a respectable amount of documentation on the MRTK 2, but the vast majority of it appears to be incomplete, obsolete, or contains screenshots of configuration settings which do not accurately reflect what we see when we look at our configuration options.

The one thing we _are_ sure of is that there is lot of confusion in the Hololens development community about how to use this MRTK framework, particularly when developing for Hololens 1.

So we'd like to request the following:
* Clear and complete documentation on how to properly configure a MRTK 2 project for deployment to a HoloLens 1 device (existing documentation seems to focus on HoloLens 2 which seems to have different configuration requirements, and what remains appears to be incomplete and/or obsolete).
* Working example scenes added to the existing examples package (or put into a new, HoloLens 1-specific examples package) - This really is critical for those of us developing on the HoloLens 1 platform.
* Clear and complete documentation on how to get all core features of the MRTK 2 working on a Hololens 1 device (air-tap, speech recognition, stabilisation, single-pass instanced rendering, etc.). This is more of a nice to have, but given the amount of confusion we've encountered in the wider dev community, there does seem to be a need for it. I'd even be happy to do a write-up on the single-pass instancing one myself, since we've already solved that one internally!

Thanks in advance for any help you can offer! And if you have any additional questions, please feel free to tag me here!

**Comment by davidkline-ms** [comment]
@Shiloh-James-ELC, 

A couple of questions:
* Are you using the new XR platform in Unity 2019.3?
* If yes, are you using the DefaultXRSDKConfigurationProfile?

**Comment by Shiloh-James-ELC** [comment]
Hi @davidkline-ms , thanks for responding!

> A couple of questions:
> 
>     * Are you using the new XR platform in Unity 2019.3?
> 
>     * If yes, are you using the DefaultXRSDKConfigurationProfile?

As described in my original post, yes.

>     * If yes, I recommend updating the Windows XR Plugin via Window > Package Manager. There are some known issues in earlier versions of that plugin

We have been using _Windows XR Plugin_ v2.0.3. I see in the package manager that v2.1.5 is available, so I've updated our project with this later version and have run another test.

The result is that the update broke the test project entirely.

The first result was that I could build from Unity, but when trying to build from the generated Visual Studio build, the build failed due to being unable to find _HolographicAppRemoting.dll_. We aren't using holographic remoting at all and had the setting disabled, but after enabling it the build still failed due to being unable to find _PerceptionDevice.dll_. As we are using the _Windows XR Plugin_ via the package manager, we are unable to alter the existing configuration of settings under Project Settings>Player>XR settings.

On the assumption that the project requires a refresh following the plugin update, I deleted the _Library_ folder and reopened the project. I then set the build target to _WSA-HoloLens_, rebuilt via _MS Build_ and re-generated SDK projects. Following this, builds in the editor began to fail due to a .dll collision error, presumably the result of the longstanding issue of a net46 folder and contents being erroneously generated by the MRTK's build tools. So I checked the setting in Player>Other Settings to confirm that the project is still using IL2CPP backend (it is), closed the project and deleted the net46 folder, then reopened the project. At this step, the editor froze for about 20 minutes and regenerated the net46 folder. Trying to build from here yields the same .dll collision error.

At this point the project was left in an unusable state, so I'm going to go out on a limb and say there's something wrong with the way the MRTK is processing the _Windows XR Plugin_ upgrade process. Are you able to shed some light on why this failed, and how I might go about performing the upgrade in a more safe and functionality-preserving manner?

**Comment by keveleigh** [comment]
>when trying to build from the generated Visual Studio build, the build failed due to being unable to find HolographicAppRemoting.dll.

This was a Unity bug that was fixed in (if I'm remembering correctly) Unity 2019.3.9. Any more recent version of Unity 2019.3 should build successfully.

**Comment by keveleigh** [comment]
Additionally yeah, if you've been on 2.0.3, airtap was broken until 2.0.4-preview.4. It should be good to go in 2.1.5.
