### ISSUE TITLE
IOException: Win32 IO returned 234. Path: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract

### ISSUE THREAD

**Issue by sunshinesjw1** [microsoft/MixedRealityToolkit-Unity#8007]
## Describe the bug
After I switch platform to UWP, and it appears IOException: Win32 IO returned 234. Path: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract\2.0.0.0\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract.winmd" error when I press "build" button. I want to know why this situation appeared and how to solve, could someone help me? Thanks very much.
First, I used Windows Mixed Reality Check to check if my computer to apply mixed reality, the result showed it can and the checked result as follows.
Windows Mixed Reality 电脑检查结果[20200602-110005]
Tool Version: 0.2.0.0
Spec Version: 74

Ok  操作系统    Windows 10 Fall Creators Update 或更高版本
Ok  图形卡     NVIDIA GeForce RTX 2070
Ok  图形驱动程序  25.21.14.1722 (WDDM 2.5)
Ok  CPU     Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Ok  RAM     16 GB
Ok  磁盘空间    361 GB
Ok  USB     3.0+
Ok  蓝牙      4.0+

------------------------------
  以下数据仅供疑难解答使用，且仅使用英语（美国）呈现。
------------------------------

Bluetooth: Ok
  > BluetoothVersion            : Ok  [Target: 6                                  ]  [Actual: 8                                  ]
  > DalBluetooth                : Ok  [Target: true                               ]  [Actual: true                               ]
  > DeviceDescription           : Ok  [Target: Qualcomm Atheros QCA61x4 Bluetooth ]  [Actual: Qualcomm Atheros QCA61x4 Bluetooth ]
  > DriverVersion               : Ok  [Target: 10.0.0.714                         ]  [Actual: 10.0.0.714                         ]
  > FirmwareVersion             : Ok  [Target: HCI 8.0 / LMP 8.602                ]  [Actual: HCI 8.0 / LMP 8.602                ]
  > Manufacturer                : Ok  [Target: Qualcomm                           ]  [Actual: Qualcomm                           ]
  > RadioPresent                : Ok  [Target: true                               ]  [Actual: true                               ]
  > RadioPresentIsDisabled      : Ok  [Target: false                              ]  [Actual: false                              ]
  > SupportsLE                  : Ok  [Target: true                               ]  [Actual: true                               ]
  > SupportsRequiredStates      : Ok  [Target: true                               ]  [Actual: true                               ]
  > SupportsSecureSimplePairing : Ok  [Target: true                               ]  [Actual: true                               ]

Cpu: Ok
  > DalCpu                    : Ok  [Target: 0              ]  [Actual: 0                                                                   ]
  > KnownCpu                  : Ok  [Target: NotFoundOnList ]  [Actual: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz,GenuineIntel,13,14,9,6,0,0 ]
  > LogicalCores              : Ok  [Target: 4              ]  [Actual: 8                                                                   ]
  > MinSpeedMhz               : Ok  [Target: 1600           ]  [Actual: 3600                                                                ]
  > PhysicalCores             : Ok  [Target: 2              ]  [Actual: 8                                                                   ]
  > SupportsAvxInstruction    : Ok  [Target: true           ]  [Actual: true                                                                ]
  > SupportsPopcntInstruction : Ok  [Target: true           ]  [Actual: true                                                                ]

Disk: Ok
  > DalDisk   : Ok  [Target: true        ]  [Actual: true         ]
  > FreeSpace : Ok  [Target: 10485760000 ]  [Actual: 387659812864 ]

Gpu: Ok
  > BestGpuDegradedByHybridPartner        : Ok  [Target: false          ]  [Actual: false                    ]
  > BestGpuDriverEvaluation               : Ok  [Target: AnyValidDriver ]  [Actual: 25.21.14.1722 (WDDM 2.5) ]
  > BestGpuHardwareEvaluation             : Ok  [Target: AnyValidGpu    ]  [Actual: NVIDIA GeForce RTX 2070  ]
  > BestGpuOverallEvaluation              : Ok  [Target: AnyValidGpu    ]  [Actual: NVIDIA GeForce RTX 2070  ]
  > BestGpuOverallHybridPartnerEvaluation : Ok  [Target: AnyValidGpu    ]  [Actual: NotFound                 ]
  > DalGpu                                : Ok  [Target: true           ]  [Actual: true                     ]
  > HmdAttachedGpuDriverEvaluation        : Ok  [Target: AnyValidDriver ]  [Actual: NotFound                 ]
  > HmdAttachedGpuSufficient              : Ok  [Target: AnyValidGpu    ]  [Actual: NotFound                 ]
  > HmdFoundCount                         : Ok  [Target: 0              ]  [Actual: 0                        ]
  > IntegratedGpuHasDualChannelMemory     : Ok  [Target: 0              ]  [Actual: 0                        ]

Memory: Ok
  > DalMemory : Ok  [Target: true       ]  [Actual: true        ]
  > Quantity  : Ok  [Target: 8388608000 ]  [Actual: 17179869184 ]

Os: Ok
  > DalOs          : Ok  [Target: true      ]  [Actual: true      ]
  > IsVM           : Ok  [Target: false     ]  [Actual: false     ]
  > OsSkuSupported : Ok  [Target: Supported ]  [Actual: Supported ]
  > Version        : Ok  [Target: 16000     ]  [Actual: 17763     ]

SystemThermal: Ok
  > DalCpu                   : Ok  [Target: 0                      ]  [Actual: 0                                                                                ]
  > DalGpu                   : Ok  [Target: 0                      ]  [Actual: 0                                                                                ]
  > DalSmbios                : Ok  [Target: 0                      ]  [Actual: 0                                                                                ]
  > SystemOnThermalWhitelist : Ok  [Target: NotRequiredOnWhitelist ]  [Actual: Dell Inc.,XPS,XPS 8930,0859,Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz,32902,16024 ]

Usb: Ok
  > DalUsb                      : Ok  [Target: true  ]  [Actual: true      ]
  > ErrorControllerCount        : Ok  [Target: 0     ]  [Actual: 0         ]
  > FastestSpeedAvailable       : Ok  [Target: 3     ]  [Actual: 3         ]
  > FoundHmd                    : Ok  [Target: false ]  [Actual: false     ]
  > HmdPortIsSelfPowered        : Ok  [Target: false ]  [Actual: false     ]
  > HmdPortSpeed                : Ok  [Target: 0     ]  [Actual: 0         ]
  > NonBlockingControllerCount  : Ok  [Target: 1     ]  [Actual: 3         ]
  > OkControllerCount           : Ok  [Target: 1     ]  [Actual: 3         ]

----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------

<?xml version="1.0" encoding="UTF-8"?>
<MrrEvaluation ToolVersion="0.2.0.0" SpecVersion="74" TelemetryID="{63C4B554-B930-42C7-942E-9A0EFA3DE508}" Status="Ok">
  <ComponentType Name="Bluetooth" Status="Ok">
    <Attribute Name="BluetoothVersion" Status="Ok" ActualValue="8" TargetValue="6" />
    <Attribute Name="DalBluetooth" Status="Ok" ActualValue="true" TargetValue="true" />
    <Attribute Name="DeviceDescription" Status="Ok" ActualValue="Qualcomm Atheros QCA61x4 Bluetooth" TargetValue="Qualcomm Atheros QCA61x4 Bluetooth" />
    <Attribute Name="DriverVersion" Status="Ok" ActualValue="10.0.0.714" TargetValue="10.0.0.714" />
    <Attribute Name="FirmwareVersion" Status="Ok" ActualValue="HCI 8.0 / LMP 8.602" TargetValue="HCI 8.0 / LMP 8.602" />
    <Attribute Name="Manufacturer" Status="Ok" ActualValue="Qualcomm" TargetValue="Qualcomm" />
    <Attribute Name="RadioPresent" Status="Ok" ActualValue="true" TargetValue="true" />
    <Attribute Name="RadioPresentIsDisabled" Status="Ok" ActualValue="false" TargetValue="false" />
    <Attribute Name="SupportsLE" Status="Ok" ActualValue="true" TargetValue="true" />
    <Attribute Name="SupportsRequiredStates" Status="Ok" ActualValue="true" TargetValue="true" />
    <Attribute Name="SupportsSecureSimplePairing" Status="Ok" ActualValue="true" TargetValue="true" />
  </ComponentType>
  <ComponentType Name="Cpu" Status="Ok">
    <Attribute Name="BrandString" Status="Ok" ActualValue="Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz" TargetValue="" />
    <Attribute Name="DalCpu" Status="Ok" ActualValue="0" TargetValue="0" />
    <Attribute Name="KnownCpu" Status="Ok" ActualValue="Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz,GenuineIntel,13,14,9,6,0,0" TargetValue="NotFoundOnList" />
    <Attribute Name="LogicalCores" Status="Ok" ActualValue="8" TargetValue="4" />
    <Attribute Name="MinSpeedMhz" Status="Ok" ActualValue="3600" TargetValue="1600" />
    <Attribute Name="PhysicalCores" Status="Ok" ActualValue="8" TargetValue="2" />
    <Attribute Name="SupportsAvxInstruction" Status="Ok" ActualValue="true" TargetValue="true" />
    <Attribute Name="SupportsPopcntInstruction" Status="Ok" ActualValue="true" TargetValue="true" />
  </ComponentType>
  <ComponentType Name="Disk" Status="Ok">
    <Attribute Name="DalDisk" Status="Ok" ActualValue="true" TargetValue="true" />
    <Attribute Name="FreeSpace" Status="Ok" ActualValue="387659812864" TargetValue="10485760000" />
  </ComponentType>
  <ComponentType Name="Gpu" Status="Ok">
    <Attribute Name="BestGpuDegradedByHybridPartner" Status="Ok" ActualValue="false" TargetValue="false" />
    <Attribute Name="BestGpuDriverEvaluation" Status="Ok" ActualValue="25.21.14.1722 (WDDM 2.5)" TargetValue="AnyValidDriver" />
    <Attribute Name="BestGpuHardwareEvaluation" Status="Ok" ActualValue="NVIDIA GeForce RTX 2070" TargetValue="AnyValidGpu" />
    <Attribute Name="BestGpuOverallEvaluation" Status="Ok" ActualValue="NVIDIA GeForce RTX 2070" TargetValue="AnyValidGpu" />
    <Attribute Name="BestGpuOverallHybridPartnerEvaluation" Status="Ok" ActualValue="NotFound" TargetValue="AnyValidGpu" />
    <Attribute Name="DalGpu" Status="Ok" ActualValue="true" TargetValue="true" />
    <Attribute Name="HmdAttachedGpuDriverEvaluation" Status="Ok" ActualValue="NotFound" TargetValue="AnyValidDriver" />
    <Attribute Name="HmdAttachedGpuSufficient" Status="Ok" ActualValue="NotFound" TargetValue="AnyValidGpu" />
    <Attribute Name="HmdFoundCount" Status="Ok" ActualValue="0" TargetValue="0" />
    <Attribute Name="IntegratedGpuHasDualChannelMemory" Status="Ok" ActualValue="0" TargetValue="0" />
    <Component Name="Intel(R) UHD Graphics 630" Status="Ok">
      <Attribute Name="BlacklistedDriver" Status="Ok" ActualValue="Intel(R) UHD Graphics 630,Intel Corporation,Intel Corporation,11/18/2018 00:00:00,2786148352/30703313,25.20.100.6374,6559974/1638420,2" TargetValue="NotFoundOnList" />
      <Attribute Name="DedicatedVideoMemory" Status="Ok" ActualValue="134217728" TargetValue="134217728" />
      <Attribute Name="HybridPartnerMeetsRequirements" Status="Ok" ActualValue="true" TargetValue="true" />
      <Attribute Name="IsRenderOnlyHardwareDevice" Status="Ok" ActualValue="false" TargetValue="false" />
      <Attribute Name="IsSoftwareOnlyDevice" Status="Ok" ActualValue="false" TargetValue="false" />
      <Attribute Name="KnownGpu" Status="Ok" ActualValue="PCI\VEN_8086&amp;DEV_3E98&amp;SUBSYS_08591028&amp;REV_02" TargetValue="Whitelist" />
      <Attribute Name="MeetsPcieLinkWidthRequirement" Status="Ok" ActualValue="0" TargetValue="0" />
      <Attribute Name="MeetsPcieMaxLinkSpeedRequirement" Status="Ok" ActualValue="0" TargetValue="0" />
      <Attribute Name="SupportsDX12" Status="Ok" ActualValue="true" TargetValue="true" />
      <Attribute Name="SupportsRealtimeCqp" Status="Ok" ActualValue="true" TargetValue="true" />
      <Attribute Name="UnsupportedCpuGpuCombo" Status="Ok" ActualValue="cpu/gpu combination satisfies conditions" TargetValue="i3 cpu cannot be paired with only Intel HD Graphics 620" />
      <Attribute Name="WddmVersion" Status="Ok" ActualValue="2.5" TargetValue="2.2" />
    </Component>
    <Component Name="Microsoft Basic Render Driver" Status="Error">
      <Attribute Name="BlacklistedDriver" Status="Ok" ActualValue="Microsoft 基本呈现驱动程序,Microsoft,Microsoft,06/21/2006 00:00:00,2743894016/29791429,10.0.17763.1,1164115969/655360,2" TargetValue="NotFoundOnList" />
      <Attribute Name="DedicatedVideoMemory" Status="Ok" ActualValue="0" TargetValue="0" />
      <Attribute Name="HybridPartnerMeetsRequirements" Status="Ok" ActualValue="true" TargetValue="true" />
      <Attribute Name="IsRenderOnlyHardwareDevice" Status="Ok" ActualValue="false" TargetValue="false" />
      <Attribute Name="IsSoftwareOnlyDevice" Status="Error" ActualValue="true" TargetValue="false" />
      <Attribute Name="KnownGpu" Status="Untested" ActualValue="PCI\VEN_1414&amp;DEV_008C" TargetValue="NotFoundOnList" />
      <Attribute Name="MeetsPcieLinkWidthRequirement" Status="Ok" ActualValue="0" TargetValue="0" />
      <Attribute Name="MeetsPcieMaxLinkSpeedRequirement" Status="Ok" ActualValue="0" TargetValue="0" />
      <Attribute Name="SupportsDX12" Status="Ok" ActualValue="true" TargetValue="true" />
      <Attribute Name="SupportsRealtimeCqp" Status="Ok" ActualValue="true" TargetValue="true" />
      <Attribute Name="UnsupportedCpuGpuCombo" Status="Ok" ActualValue="cpu/gpu combination satisfies conditions" TargetValue="i3 cpu cannot be paired with only Intel HD Graphics 620" />
      <Attribute Name="WddmVersion" Status="Ok" ActualValue="2.5" TargetValue="2.2" />
    </Component>
    <Component Name="NVIDIA GeForce RTX 2070" Status="Ok">
      <Attribute Name="BlacklistedDriver" Status="Ok" ActualValue="NVIDIA GeForce RTX 2070,NVIDIA,NVIDIA,11/29/2018 00:00:00,2023522304/30705526,25.21.14.1722,919226/1638421,2" TargetValue="NotFoundOnList" />
      <Attribute Name="DedicatedVideoMemory" Status="Ok" ActualValue="8421113856" TargetValue="8421113856" />
      <Attribute Name="HybridPartnerMeetsRequirements" Status="Ok" ActualValue="true" TargetValue="true" />
      <Attribute Name="IsRenderOnlyHardwareDevice" Status="Ok" ActualValue="false" TargetValue="false" />
      <Attribute Name="IsSoftwareOnlyDevice" Status="Ok" ActualValue="false" TargetValue="false" />
      <Attribute Name="KnownGpu" Status="Ok" ActualValue="PCI\VEN_10DE&amp;DEV_1F02&amp;SUBSYS_12FE1028&amp;REV_A1" TargetValue="Whitelist" />
      <Attribute Name="MeetsPcieLinkWidthRequirement" Status="Ok" ActualValue="16" TargetValue="0" />
      <Attribute Name="MeetsPcieMaxLinkSpeedRequirement" Status="Ok" ActualValue="3" TargetValue="0" />
      <Attribute Name="SupportsDX12" Status="Ok" ActualValue="true" TargetValue="true" />
      <Attribute Name="SupportsRealtimeCqp" Status="Ok" ActualValue="true" TargetValue="true" />
      <Attribute Name="UnsupportedCpuGpuCombo" Status="Ok" ActualValue="cpu/gpu combination satisfies conditions" TargetValue="i3 cpu cannot be paired with only Intel HD Graphics 620" />
      <Attribute Name="WddmVersion" Status="Ok" ActualValue="2.5" TargetValue="2.2" />
    </Component>
  </ComponentType>
  <ComponentType Name="Memory" Status="Ok">
    <Attribute Name="DalMemory" Status="Ok" ActualValue="true" TargetValue="true" />
    <Attribute Name="Quantity" Status="Ok" ActualValue="17179869184" TargetValue="8388608000" />
  </ComponentType>
  <ComponentType Name="Os" Status="Ok">
    <Attribute Name="DalOs" Status="Ok" ActualValue="true" TargetValue="true" />
    <Attribute Name="IsVM" Status="Ok" ActualValue="false" TargetValue="false" />
    <Attribute Name="OsSkuSupported" Status="Ok" ActualValue="Supported" TargetValue="Supported" />
    <Attribute Name="Version" Status="Ok" ActualValue="17763" TargetValue="16000" />
  </ComponentType>
  <ComponentType Name="SystemThermal" Status="Ok">
    <Attribute Name="DalCpu" Status="Ok" ActualValue="0" TargetValue="0" />
    <Attribute Name="DalGpu" Status="Ok" ActualValue="0" TargetValue="0" />
    <Attribute Name="DalSmbios" Status="Ok" ActualValue="0" TargetValue="0" />
    <Attribute Name="SystemOnThermalWhitelist" Status="Ok" ActualValue="Dell Inc.,XPS,XPS 8930,0859,Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz,32902,16024" TargetValue="NotRequiredOnWhitelist" />
  </ComponentType>
  <ComponentType Name="Usb" Status="Ok">
    <Attribute Name="DalUsb" Status="Ok" ActualValue="true" TargetValue="true" />
    <Attribute Name="ErrorControllerCount" Status="Ok" ActualValue="0" TargetValue="0" />
    <Attribute Name="FastestSpeedAvailable" Status="Ok" ActualValue="3" TargetValue="3" />
    <Attribute Name="FoundHmd" Status="Ok" ActualValue="false" TargetValue="false" />
    <Attribute Name="HmdPortControllerEvaluation" Status="Ok" ActualValue="Not found" TargetValue="" />
    <Attribute Name="HmdPortIsSelfPowered" Status="Ok" ActualValue="false" TargetValue="false" />
    <Attribute Name="HmdPortSpeed" Status="Ok" ActualValue="0" TargetValue="0" />
    <Attribute Name="NonBlockingControllerCount" Status="Ok" ActualValue="3" TargetValue="1" />
    <Attribute Name="OkControllerCount" Status="Ok" ActualValue="3" TargetValue="1" />
    <Component Name="Intel(R) USB 3.0 可扩展主机控制器 - 1.0 (Microsoft)" Status="Ok">
      <Attribute Name="Powered30PortCount" Status="Ok" ActualValue="10" TargetValue="1" />
      <Attribute Name="UsbControllerDriverBlacklisted" Status="Ok" ActualValue="USBXHCI/10.0.17763.1075/02/20/2020 00:00:00" TargetValue="" />
      <Attribute Name="UsbControllerHardwareBlacklisted" Status="Ok" ActualValue="41647/32902/0" TargetValue="" />
    </Component>
    <Component Name="NVIDIA USB 3.10 可扩展主机控制器 - 1.10 (Microsoft)" Status="Ok">
      <Attribute Name="Powered30PortCount" Status="Ok" ActualValue="4" TargetValue="1" />
      <Attribute Name="UsbControllerDriverBlacklisted" Status="Ok" ActualValue="USBXHCI/10.0.17763.1075/02/20/2020 00:00:00" TargetValue="" />
      <Attribute Name="UsbControllerHardwareBlacklisted" Status="Ok" ActualValue="6874/4318/161" TargetValue="" />
    </Component>
    <Component Name="ASMedia USB 3.1 可扩展主机控制器 - 1.10 (Microsoft)" Status="Ok">
      <Attribute Name="Powered30PortCount" Status="Ok" ActualValue="2" TargetValue="1" />
      <Attribute Name="UsbControllerDriverBlacklisted" Status="Ok" ActualValue="USBXHCI/10.0.17763.1075/02/20/2020 00:00:00" TargetValue="" />
      <Attribute Name="UsbControllerHardwareBlacklisted" Status="Ok" ActualValue="4674/6945/0" TargetValue="" />
    </Component>
  </ComponentType>
</MrrEvaluation>

 
IOException: Win32 IO returned 234. Path: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract\2.0.0.0\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract.winmd" or "Temp\StagingArea\Data\Managed\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract.winmd
System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
PostProcessWinRT.CopyFrameworkAssemblies () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1823)
PostProcessWinRT.Process () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:164)
UnityEditor.UWP.BuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:91)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.UWP.BuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:95)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at D:/unity/Editor/Mono/Modules/DefaultBuildPostprocessor.cs:27)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at D:/unity/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:281)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at D:/unity/Modules/IMGUI/GUIUtility.cs:179)

## To reproduce

1. Open 'unity'
2. Right click SampleScene, and selected GameObject, clicked 3D Object
1. Click on 'Switch Platform'
2. Click on 'build'
3. See error

## Expected behavior
build succeed
build succeed
## Screenshots
![a](https://user-images.githubusercontent.com/48056580/83476139-76aecf80-a4c2-11ea-8649-d3c5a1c254fa.PNG)

## Your setup (please complete the following information)

- Unity Version [2019.2.8f1]
- MRTK Version [2.4.0]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
Taking a look at the screenshot, it doesn't look like MRTK is involved here (i.e. it doesn't have the MRTK menu which means the assets are probably not in the project, and it also doesn't have the MRTK object in the scene).

If you do a search for that error (i.e. google "Win32 IO returned 234" without the quotes) you see similar things that other folks are hitting:
https://forum.unity.com/threads/publish-to-uwp-platform-by-il2cpp-throws-error-ioexception-win32-io-returned-234.617977/

Definitely feel free to reopen if you're finding this to be specific to MRTK-Unity.
