### ISSUE TITLE
Simplify Focus / Pointer systems

### ISSUE THREAD

**Issue by provencher** [microsoft/MixedRealityToolkit-Unity#8008]
## Describe the problem

In trying to pull out the logic of the teleport pointer to manually control it in MRTK-Quest, it has become clear how coupled input, focus and pointers all are to each other.

Pointer seems like a standalone object, but since it also extends controller pose synchronizer, it is coupled to the controller pose it was designed to be used with, and cannot be controlled outside of this system.

Then, to interact with the scene, the actual ray cast is performed by the Focus Provider, which implements a whole lot of private or internal classes which are only exposed as interfaces outside.

To simply do the raycast, I have to copy the raycast logic, along with all the related pointer results and pointerdata classes which only exist in the monolithic FocusProvider.

## Describe the solution you'd like

Ideally, Pointers would be standalone objects that do their own hit testing, without relying on a monolithic class like FocusProvider. The provider's job should be to mediate the results of the hit testing done by the pointers, rather than do all the hit testing itself.

Second, Pointers should be have clear access points to control them independently of the input action system, which is rigid and not easily extensible.

## Additional context
[Here](https://github.com/provencher/MRTK-Quest/blob/TeleportSystem/Assets/MRTK.ThirdParty/MRTK-Quest/Scripts/Input/TeleportPointer/CustomTeleportPointer.cs) is my WIP of the custom teleport pointer.

**Comment by Zee2** [comment]
Hi @provencher ; our move towards utilizing XRI primitives in MRTK v3 will make pointers much more modular and flexible. When that time comes (soon), please let us know if the additional flexibility fits your needs.

**Comment by methot-ilya-3ds** [comment]
@provencher I'm also having difficulty modifying the pointer system for my own projects. Have you worked on a custom pointer system for interaction yet?

**Comment by RogPodge** [comment]
Closing this issue as we move towards the XRI input system. Drastic changes to the pointer/focus provider systems is a bit out of scope and more than what we can do while using our own input system.
