### ISSUE TITLE
unable to find profiles when installed via UPM

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#8023]
While experimenting with UPM installs, it was discovered that the MRTK.Files lookup does not properly account for MRTK residing in the library folder.

![image](https://user-images.githubusercontent.com/13281406/83924460-956acb80-a739-11ea-9dbe-09c99abae605.png)

**Comment by davidkline-ms** [comment]
At first glance, this appears to be due the MRTK searching via the assets database and not the folder structure itself.

**Comment by davidkline-ms** [comment]
A likely better approach is to provide an option to copy the profiles into the assets folder, similar to how Text Mesh Pro prompts to install the essential components.

**Comment by davidkline-ms** [comment]
Issue with copying profiles from the Library -> Assets:

Unity is regenerating the GUIDs in the copied meta files. This breaks the association between profiles.

**Comment by davidkline-ms** [comment]
The Text Mesh Pro package contains .unitypackage files containing resources that need to be in the Assets folder. It should be relatively simple to create these artifacts and bundle them in the UPM package(s).

**Comment by keveleigh** [comment]
Instead of copying them over, the `AssetDatabase` APIs can also look in any installed packages.

If there's a way for us to know how we're installed we can default to the correct one, or maybe just search both, but replacing `Assets` in the path with `Packages` should work:

https://docs.unity3d.com/Manual/upm-assets.html

**Comment by davidkline-ms** [comment]
The above appears to work on Unity 2019 where the dependency packages are also represented in the Packages folder. Unfortunately,  this is not the case for 2018 (as of .4.23)., so the APIs are likely to not find the files.

**Comment by keveleigh** [comment]
>Unfortunately, this is not the case for 2018 (as of .4.23)., so the APIs are likely to not find the files.

@davidkline-ms I tested this out, and even though they don't show up in the Packages view, they _are_ in the `Library/PackageCache` folder and are successfully loaded via the `AssetDatabase` APIs in Unity 2018.4.

Tested with `AssetDatabase.LoadAssetAtPath<AssemblyDefinitionAsset>("Packages/com.unity.xr.arsubsystems/Runtime/Unity.XR.ARSubsystems.asmdef")`, which was loaded as a dependency of AR Foundation.

**Comment by davidkline-ms** [comment]
will continue to investigate

**Comment by davidkline-ms** [comment]
Fixed with #8058
