### ISSUE TITLE
Windows XR Plugin causes offset/wrong scaling in hand mesh and spatial mesh

### ISSUE THREAD

**Issue by rolandsmeenk** [microsoft/MixedRealityToolkit-Unity#8024]
## Describe the bug

After switching to the new XR System I am experiencing a scaling issue on HoloLens2 in the spatial mesh and hand meshes. The hand mesh renders closer but smaller than where my real hands are. The spatialmapping mesh offset is the most pronounced directly after startup of the application. The tracking seems to be a bit more jittery. It also shows the Unity logo on startup closer and larger than normal.

## To reproduce

1. Install Unity 2019.3.15f1d
2. Create new project and install MRTK 2.4
3. Install Windows XR Plugin in Package Manager to 2.15
4. Set MRTK profile to DefaultXRSDKConfigurationProfile
5. Build project for Visual Studio 2019
6. Use Visual Studio to deploy project to HoloLens 2
7. Observe that the hand and spatial mapping mesh have an offset

## Your setup (please complete the following information)

Unity 2019.3.15f1
MRTK2.4
Windows XR Plugin 2.1.5 (same issue also with 2.1.6 preview.3)

## Target platform

- HoloLens 2

**Comment by fate4gle** [comment]
The identical issue persists for Unity2019.3.10.f1 and Unity2019.4.1f1

**Comment by edgar-rodrigo-santos** [comment]
I would like to add that this happens for other holograms too (in general, things appear much closer to our face). There seems to be issues with stereo rendering. This issue seems somewhat related: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8111

Windows XR Plugin + HLL2 is unusable at the moment.

**Comment by omanuke** [comment]
I encountered same issue.
My environment are
- Unity 2019.4.2
- Windows XR Plugin2.2.0
- XR Plugin Management 3.2.13

The behavior on Holographic Remoting Player is same.

**Comment by keveleigh** [comment]
This has been identified as an issue by Unity and is being investigated.

**Comment by edgar-rodrigo-santos** [comment]
@keveleigh I couldn't find the issue in their issue tracker. Could you point me to it, please? Since this is a severe issue I just wanted to make sure this is reported. Thank you.

**Comment by keveleigh** [comment]
@edgar-rodrigo-santos It hasn't made it to the public issue tracker yet. I'll see what I can do.

**Comment by andnovar** [comment]
I am also presenting the same issue. I have the same environment as @omanuke . Just commenting to receive a follow up.

**Comment by RichLogan** [comment]
@keveleigh Was there any update on this from Unity? It's pretty awkward to have to downgrade back to Legacy XR but I guess we don't have a choice with such a fundamental issue 😞

**Comment by keveleigh** [comment]
@RichLogan no update just yet, but this has become both their and my top priority in getting a fix out the door for.

**Comment by 0tobsam0** [comment]
Can confirm for Unity 2019.4.4f1 LTS and Hololens 1.

**Comment by keveleigh** [comment]
Update: a fix has been merged and should be present in the next plug-in release. I'll update this thread when I have a release date.

**Comment by keveleigh** [comment]
The most recent 2.3.0 release of Windows XR Plugin should resolve this issue. You'll need to manually go into the package manager to update the version for now, and this will become the default verified package in a future editor release.

![image](https://user-images.githubusercontent.com/3580640/89451291-ce5ef680-d710-11ea-8147-3e67e1ce04db.png)

**Comment by keveleigh** [comment]
Closing as fixed. Information on the fix can be found in previous comments.
