### ISSUE TITLE
MixedRealityToolkit Inspector Click Select Tab

### ISSUE THREAD

**Issue by sakuriver** [microsoft/MixedRealityToolkit-Unity#8026]
## Describe the bug

When I click on a MixedRealityToolkit object and then click SpatialAwareness in Inspector, the Inspector does not become selected

As you can see in the screenshot, I've confirmed that Enable Spatial Awareness is showing up.

## To reproduce

1. Go to 'MixedRealityToolkit'
2. Click on 'Spatial Awareness'

## Screenshots

<img width="788" alt="no_select_tab" src="https://user-images.githubusercontent.com/309414/83962051-9edc6b00-a8d4-11ea-9560-45f134ebc540.png">

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.3.13f1]
- MRTK Version [e.g. v2.4]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by keveleigh** [comment]
Looks like a rendering bug in Unity 2019. Whatever we're using for highlighting doesn't seem to be working

**Comment by sakuriver** [comment]
That's right.

If so, will we have to wait for unity2020?
Should we wait for something that can be supported on the mrtk side?

**Comment by keveleigh** [comment]
This is fixed: 
![image](https://user-images.githubusercontent.com/3580640/120018179-a42a3e00-bf9b-11eb-926b-9a222f10c0bd.png)

I don't remember the exact PR, but it shouldn't be an issue anymore!
