### ISSUE TITLE
In unity development, some shaders can only be displayed in one spectacle lens

### ISSUE THREAD

**Issue by zanzan524** [microsoft/MixedRealityToolkit-Unity#8030]
## Describe the bug

In unity development, some shader can only be displayed in one spectacle lens

## To reproduce

I used my object using the shader of TextMeshPro/sprite and found that the object appeared with only one eye.

## Expected behavior

Hope this problem can be solved

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.3.14f1]
- MRTK Version [e.g. v2.4.0]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
There's not too much information in this issue to highlight if this is an MRTK specific question, or a more general shader question as it deal with doing single pass instanced rendering.

Check out: https://docs.unity3d.com/Manual/SinglePassStereoRenderingHoloLens.html
