### ISSUE TITLE
Hololens 2: Near Touchable UI stops working when there are grabbables in the scene

### ISSUE THREAD

**Issue by ninjanoka** [microsoft/MixedRealityToolkit-Unity#8047]
## Overview
The UI interaction stops working in my scene with grabbables. (far interaction still works)
## Expected behavior
Can press the UI as before.
## Actual behavior
UI only works with far interaction.
## Steps to reproduce
_(Links to sample github project preferred)_
use UGUI nearinteraction. Load grabbables(nearinteractiongrabbable, manipulationhandler, boundingbox) -> UI stops responding
## Unity editor version
2019.3.13
## Mixed Reality Toolkit release version
2.3

**Comment by ninjanoka** [comment]
It seems something is blocking it somehow. Is there any way to find out what? When I move my button down it starts to work properly.

**Comment by MrMatthias** [comment]
In the _Input -> Pointer settings_ you can set multiple _Pointing Raycast Layer Maks_. You could put the UI and grabbables on  separate layers and prioritize the UI layer. That's at least how i fixed a conflict with a bounding box

**Comment by Zee2** [comment]
@ninjanoka did @MrMatthias 's suggestion resolve your issue? Closing this issue for staleness now, but please reopen if you need further assistance.
