### ISSUE TITLE
Build type XAML breaks system keyboard on HL2

### ISSUE THREAD

**Issue by mgrman** [microsoft/MixedRealityToolkit-Unity#8048]
## Describe the bug

On XAML builds, when unity triggers the system keyboard the app minimizes and another Window opens with a text field and the system keyboard. 

## To reproduce

1. Build the HandInteractionExamples scene from the MRTK 2.3 release with BuildType XAML
2. Start the app
3. Click on input field (on the right side in the canvas)
4. The app minimizes to shell and another window with input field opens and system keyboard opens
5. Also upon submiting the edited test the app does not open back up, but crashes.

## Expected behavior

System keyboard opens in an overlay on top of the Unity application as when Build Type is Direct3D.

## Screenshots

![20200612_054651_HoloLens](https://user-images.githubusercontent.com/6034981/84504236-e0e22400-acbb-11ea-9769-472e644540db.jpg)

## Your setup (please complete the following information)

- Unity Version 2019.2.19
- MRTK Version 2.3

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

The build type XAML is intentionally chosen so the app supports https://assetstore.unity.com/packages/tools/gui/3d-webview-for-uwp-hololens-166365 which requires XAML build type.

**Comment by mgrman** [comment]
Reproducible on Unity 2019.4 and MRTK 2.4, although the app still minimizes and the system keyboard opens for a bit but closes immediatelly.

**Comment by olabrahammar** [comment]
This issue still present building with Unity 2019.4.13 (LTS),  Visual Studio 16.7.7,  Target/Min SDK platform 10.0.19041.0.
I'll see if i find a work-around

**Comment by MaxWang-MS** [comment]
This is a bug on the Unity side and they are working a fix to be released in a future version of Unity. I will post back when I know the fix is shipped.

**Comment by JBrentJ** [comment]
Hi all! 
This issue is being reported as fixed by Unity in the upcoming versions: 
2021.2 a1
2021.1 b1
2020.2.2
2019.4.19

**Comment by polar-kev** [comment]
@elbuhofantasma, can you confirm this fix on 2019.4?
