### ISSUE TITLE
SolverExamples can not use

### ISSUE THREAD

**Issue by yj12138** [microsoft/MixedRealityToolkit-Unity#8055]
## Your setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by yj12138** [comment]
the solver is effective，but in hololens2，it can not work

**Comment by wiwei** [comment]
This bug report doesn't contain any actionable information, closing this out.
