### ISSUE TITLE
the slover in unity editor can work,but in hololens2 ,the obejct is not show

### ISSUE THREAD

**Issue by yj12138** [microsoft/MixedRealityToolkit-Unity#8056]
## Your setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by wiwei** [comment]
There's not a lot of information in this bug report. Based on the title it seems like it's probably this one:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7912

Feel free to open a new issue with information requested in the bug template.
