### ISSUE TITLE
MixedRealityCanvasInspector editor script Screen Space - Camera error

### ISSUE THREAD

**Issue by efsjouw** [microsoft/MixedRealityToolkit-Unity#8057]
## Describe the bug

When dragging a camera into a Screen Space - Camera canvas in the inspector the MixedRealityCanvasInspector throws an error.

## To reproduce

1. Create a Canvas
2. Set Render Mode to Screen Space - Camera
3. Drag camera into Render Camera
4. MixedRealityCanvasInspector throw an error

"TargetParameterCountException: Number of parameters specified does not match the expected number."

## Expected behavior

The camera can be dragged into the Render Camera field without any errors.

## Your setup (please complete the following information)

- Unity Version 2019.4.0f1
- MRTK Version 2.3.0

## Target platform

- HoloLens 2

**Comment by wiwei** [comment]
@efsjouw can you grab the latest (2.4) and double check. I wasn't able to hit this on latest. We ended up doing some refactoring here to delete duplicated inspector code:

https://github.com/microsoft/MixedRealityToolkit-Unity/commit/0df9f4ef8e70ca7a37b9b2480f23ad6c76c8eb0b#diff-d7217cb88bbf199669bde763d392040b
