### ISSUE TITLE
Asking for a collider when adding DockPosition.cs to a dock children

### ISSUE THREAD

**Issue by nooxouille** [microsoft/MixedRealityToolkit-Unity#8061]
Hi everyone! Hoping you are all doing well wherever you are.

## Describe the bug

When creating a dock from scratch, adding the DockPosition.cs to the child of the Dock.cs object is considered as an invalid operation. It is then required to add a Collider component to child object.

## To reproduce

1. Create an empty gameObject (the Dock)
2. Add the Dock.cs component to it
3. Create an empty gameObject, child of the Dock gameObject
4. Add the DockPosition.cs component to it

## Expected behavior

The same result as in the DockExample scene : children without any component but the DockPosition.cs

## Screenshots

![Unity_0YWZA1USvl](https://user-images.githubusercontent.com/2682226/84746889-de7f1300-afb6-11ea-8190-c6d4e159b962.png)
![dPDcRRnnjI](https://user-images.githubusercontent.com/2682226/84746962-f35ba680-afb6-11ea-9692-7e17e7dc2f6b.gif)

## Your setup

- Unity 2019.4.0f1 (LTS)
- MRTK v2.4
- Legacy XR pipeline (not on the new Unity XR pipeline)

## Target platform

- HoloLens 2
- UWP

## Additional info

The dock from the example scene is working as intended.

**Comment by wiwei** [comment]
@robertos I'm guessing this line was added after the example scene was made:

```c#
[RequireComponent(typeof(Collider), typeof(Rigidbody))]
```

I think the right thing here is just to update the example scenes to have the box collider - it's righteous I think to require people to explicitly add a collider for the dock (i.e. that's how the docking happens). I guess the tradeoff here is there's an extra step (i.e. ensuring the object has a collider) but I think that in general automagic is less good than not automagic.
