### ISSUE TITLE
Solver can not effect in unity2019.3

### ISSUE THREAD

**Issue by yj12138** [microsoft/MixedRealityToolkit-Unity#8063]
## Describe the bug

in hololens2,When I use unity2018.4, the solver may be used, but the cups in unity2019.3 solver case are missing, why?

## Your setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by wiwei** [comment]
This is the third duplicate issue that you've opened:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8056
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8055

None of these issues contain repro information or details that are actionable. There's a response to your questions in this issue you opened:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8056

The response contains the mostly likely reason you're hitting the issue you're seeing. Please read the responses to your issues before opening new ones.
