### ISSUE TITLE
LogError shows when hide/reload DockExample objects. 

### ISSUE THREAD

**Issue by Ericbing** [microsoft/MixedRealityToolkit-Unity#8065]
## LogError shows when hide/reload DockExample objects. 

The dock feature still working when the error shows in console panel. However, when it runs on mobile device like Quest, the docking speed seems much slower than on PC. 
The LogError is "AssertionException: Assertion failure. Value was Null
Expected: Value was not Null
When a dockable is docked, its dockedPosition must be valid.
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <23a7799da2e941b88c6db790c607d655>:0)
UnityEngine.Assertions.Assert.IsNotNull (UnityEngine.Object value, System.String message) (at <23a7799da2e941b88c6db790c607d655>:0)
UnityEngine.Assertions.Assert.IsNotNull[T] (T value, System.String message) (at <23a7799da2e941b88c6db790c607d655>:0)
Microsoft.MixedReality.Toolkit.Experimental.UI.Dockable.Update () (at Assets/MRTK/SDK/Experimental/Dock/Dockable.cs:133)"

## To reproduce

1. Add two buttons in MRTK example scene.
Button one: Hide the DockExample object group in Hierarchy panel with "GameObject.SetActive" value=off.
Button two: Show the DockExample object group in Hierarchy panel with "GameObject.SetActive" value=on.

2. Click button one to hide the DockExample object group, then click button two to show the group, then the debug.LogError will keep coming.

## Expected behavior

The debug.LogError will keep coming in Console panel.

## Screenshots

<img width="693" alt="ErrorCapture" src="https://user-images.githubusercontent.com/39200338/84810190-d1b2ed00-afbf-11ea-99c5-5098aeee519b.PNG">

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.3.14f1]
- MRTK Version [e.g. v2.4.0]

## Target platform (please complete the following information)

- Oculus Quest
- Oculus Rift

**Comment by wiwei** [comment]
Looks like this is because OnDisable doesn't clear the dockState:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MRTK/SDK/Experimental/Dock/Dockable.cs#L110

**Comment by wiwei** [comment]
Should be a relatively easy fix, marking as help wanted in case someone else wants to take this up.

**Comment by Ericbing** [comment]
debug.LogError shows when hide/reload DockExample game objects :
"AssertionException: Assertion failure. Value was Null
Expected: Value was not Null
When a dockable is docked, its dockedPosition must be valid.
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <23a7799da2e941b88c6db790c607d655>:0)
UnityEngine.Assertions.Assert.IsNotNull (UnityEngine.Object value, System.String message) (at <23a7799da2e941b88c6db790c607d655>:0)
UnityEngine.Assertions.Assert.IsNotNull[T] (T value, System.String message) (at <23a7799da2e941b88c6db790c607d655>:0)
Microsoft.MixedReality.Toolkit.Experimental.UI.Dockable.Update () (at Assets/MRTK/SDK/Experimental/Dock/Dockable.cs:133)"

Way to reproduce the issue:

Add two buttons in MRTK-Quest_2.4_Extra scene.
Button one: Hide the DockExample object group in Hierarchy panel with "GameObject.SetActive" value=off.
Button two: Show the DockExample object group in Hierarchy panel with "GameObject.SetActive" value=on.

Click button one to hide the DockExample object group, then click button two to show the group, then the debug.LogError will keep coming.

**Comment by Ericbing** [comment]
Thank you, wiwei!
