### ISSUE TITLE
Is there a way to force webcam to stop when in use?

### ISSUE THREAD

**Issue by amfdeluca** [microsoft/MixedRealityToolkit-Unity#8069]
## Describe the problem
During the webrtc streaming it happens that the webcam component freezes if sudden disconnections occur. Unfortunately, it becomes impossible to stop it, so the hololens continues to record (red icon on the top left). I wanted to know if there was a way to force the camera to stop using some mrtk logic.

## Describe the solution you'd like
A command to force the use of the webcam to stop

**Comment by keveleigh** [comment]
This sounds like an issue for the WebRTC repo at https://github.com/microsoft/MixedReality-WebRTC. They should be able to answer this for you there! We don't have any WebRTC components in this repo.
