### ISSUE TITLE
Missing Prefab in DoubleSidedTest scene

### ISSUE THREAD

**Issue by keveleigh** [Microsoft/MixedRealityToolkit-Unity#807]
![image](https://user-images.githubusercontent.com/3580640/28645376-1a727ab8-7212-11e7-8f9a-7e41af6c1100.png)

I'd fix this, but I'm not sure what it's supposed to be. Any idea @dbastienMS?

**Comment by dbastienMS** [comment]
Looks like it's a missing model and the missing prefab error is a red herring.  The guid it is referencing seems to be a file I have locally but cannot be submitted to OSS.  Any model that made sense as a double-sided one would work though, and if you modify the guid in the meta file of said model to be 719621daa667a2c4e97801f908d922e6 everything else should just magically work.

**Comment by dbastienMS** [comment]
I felt guilty enough about this that I made a tool to find such problems by scrubbing through assets and scenes looking for missing references.  It can also be used to find objects which are unused.

I'm not sure whether or not it belongs in the HTK, but I've attached it.
[Assets.zip](https://github.com/Microsoft/HoloToolkit-Unity/files/1178227/Assets.zip)

Might make sense to combine the two test scenes as well to make breakages more easily found.

**Comment by StephenHodgson** [comment]
@dbastienMS what is the missing prefab?

**Comment by StephenHodgson** [comment]
Never mind, I just added a new double sided material and put it on a quad in the example scene.

**Comment by dbastienMS** [comment]
It was actually a bogus error - was really a missing model not prefab.  Quad sounds great, thanks!

Feel free to combine the two scenes if you think it'll reduce maintenance cost going forward.
Also not sure if the asset scrubbing tool I shared above is HTK material or not, but it is insanely useful.

**Comment by StephenHodgson** [comment]
I'll let you add that as a PR in it's own right if you feel like sharing it.

**Comment by dbastien** [comment]
I can do that - want to take a look and let me know if you think it belongs first?

**Comment by StephenHodgson** [comment]
I did already.  I know I'd personally use it.

If you do end up adding it it'll probably go in utilities folder

**Comment by dbastienMS** [comment]
I'm out on medical leave for awhile unfortunately so someone else will have to grab this if it's still desired.

**Comment by StephenHodgson** [comment]
Sorry to hear that.  Hope everything goes well!

Got this fixed already bro.
