### ISSUE TITLE
Empty "CINEMA_4D_Editor" object inside a DockExample prefab

### ISSUE THREAD

**Issue by nooxouille** [microsoft/MixedRealityToolkit-Unity#8076]
## Describe the bug

Hi there!

The Model_Bucky prefab hold an empty CINEMA_4D_Editor item.
That's all.

## Versions 

- MRTK 2.4
- Unity 2019.4.0f1 LTS

## Screenshots

![Unity_mGvTMXOOAf](https://user-images.githubusercontent.com/2682226/85106667-dcae8d00-b20c-11ea-9610-f21dc31de017.png)

**Comment by wiwei** [comment]
Looks like we can get rid of this - marking as Help Wanted
