### ISSUE TITLE
Can I get raw point clouds?

### ISSUE THREAD

**Issue by dsaito3110** [microsoft/MixedRealityToolkit-Unity#8078]
## Overview
I want to know how to get not mesh data but raw point clouds data.
Does such a method exist?

**Comment by wiwei** [comment]
This isn't exactly an MRTK question, but you may be able to get this using the depth information from research mode:

https://docs.microsoft.com/en-us/windows/mixed-reality/research-mode

I'm assuming this question is primarily targetted toward HL.
