### ISSUE TITLE
TapToPlace.StartPlacement Ignored if Called Before Start

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#8080]
## Describe the bug

If **StartPlacement** is called on **TapToPlace** before the **TapToPlace** component has started, the request will never be fulfilled and no error is generated.

This is due to an `If` condition in the `Start` method of **TapToPlace**. The condition checks to see if `AutoStart` is **false**. If `AutoStart` is **false**, `SolverHandler.UpdateSolvers` is also set to **false**.

## Expected behavior

In Unity it's not very easy to control the starting order of behaviors. Therefore, a behavior that references and uses **TapToPlace** may get started before **TapToPlace** itself. If the controlling behavior calls **StartPlacement** before **TapToPlace** has started, I would expect **TapToPlace** to begin working once it has started.

One may ask "Why not just set `TapToPlace.AutoStart` to true?" The problem is that the controlling behavior may decide whether to start in Placing mode or Creating mode based on previously saved data. Therefore whether or not TapToPlace should start is up to the calling component. If the calling component just sets `AutoStart = true` in this case, that may not work either if TapToPlace was actually started first.

## Your setup (please complete the following information)

- Unity Version 2019.2.21f1
- MRTK Version 2.4

## Target platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
Tagging as help wanted since this should be a good first issue to pick up.

**Comment by Synergiz-RROUINVY** [comment]
A simple and dirty delay of 10 ms between component activation and StartPlacement() seems to be a working workaround.

**Comment by jbienzms** [comment]
The start order and length of start time will vary by each machine. I do not believe that a hard-coded delay of 10 ms will solve this problem for good.

A more resilient approach IMO would be a way of knowing if the behavior has been Started. In StartPlacing, if the behavior hasn't started the method would set a flag called startRequested. This flag would be checked during Start. Or something similar to this.
