### ISSUE TITLE
NearInteractionGrabbable Ignores Child Colliders

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#8081]
## Describe the bug

**NearInteractionGrabbable** only honors the colliders found on the same object where it is applied. This is different than **Rigidbody** which honors all colliders found in its children.

In my application I have an oscillating fan hologram with rotating head. This necessitates having two different colliders. One at the base and one that rotates with the head.

When colliders only exist in the children, **NearInteractionGrabbable** does not work. However it's worth pointing out that far interactions through **ObjectManipulator** work fine with child colliders, as do **Rigidbodies**.

## Expected behavior

I would expect **NearInteractionGrabbable** to find and honor colliders in children. If not the entire child tree, at least immediate children. If necessary (and as an optimization strategy), **NearInteractionGrabbable** could skip the child search if it finds colliders on the immediate GameObject where it's applied. However, this should be clearly documented if implemented.

## Your setup (please complete the following information)

- Unity Version 2019.2.21f1
- MRTK Version 2.4

## Target platform (please complete the following information)

- HoloLens 2

**Comment by Zee2** [comment]
Hi, thanks for reporting this!

I ran into a similar issue previously with an internal prototype, I brought it up with the team.

The workaround is that you can actually still do this, you just need to add another `NearInteractionGrabbable` on each child collider objects. Messy, but it works exactly as you'd expect.

**Comment by jbienzms** [comment]
Thanks for the workaround @Zee2. I really appreciate that. But yes, it does seem rather wasteful to add NearInteractionGrabbable for every object with a collider. The fan in my project has 3. Since this isn't required for a RigidBody, I'd love to see ObjectManipulator work the same way.

**Comment by Zee2** [comment]
Agreed. Definitely onboard with your assessment of the wastefulness.... I believe it is a result of how we use NearInteractionGrabbables to determine which objects can actually receive the interaction events; however, this doesn't line up with how Unity does child colliders. I'll bring this up with the team.

**Comment by deibu** [comment]
I also ran into this issue with having buttons underneath an object with the ObjectManipulator component. I tried the workaround with adding NearInteractionGrabbables to my child objects, but it doesn't seem to work unless I also add an ObjectManipulator to them. Do you have any other ideas for a workaround when you don't want the child objects to have ObjectManipulator as well?

**Comment by Zee2** [comment]
XRI handles this gracefully by being able to explicitly associate colliders with individual interactables, even with complex nesting hierarchies.
