### ISSUE TITLE
Blank build and multiple duplicate providers after build

### ISSUE THREAD

**Issue by HKBSC** [microsoft/MixedRealityToolkit-Unity#8087]
## Describe the bug

Brand new project setup and built yesterday using MRTK 2.3 and 2.4 successfully to HoloLens 2, same project with minor changes (game object names etc.) shows multiple duplicate providers under MixedRealityToolkit object and the application on device opens without any content (including missing hand rays or any other functionality).

Additional side note. When this happens, it sometimes messes with HoloLens 2 system menu, i.e. System Menu appears offset from hand position. This issue sometimes persists after the app is closed until device restart.

## To reproduce

1. Build a HoloLens 2 app using MRTK 2.3 or 2.4 with DefaultHoloLens2ConfigurationProfile and Unity 2019.2.6f1
2. Deploy to HoloLens 2 using VS 2019 (remote machine). Run the app on HoloLens 2 and confirm that it works properly.
3. Restart unity project. Change something minor such as a scene object name. Build project into a different folder. Uninstal previous build from device. Deploy new build the same way.
4. Run the app on HoloLens. Observe blank application. Observe Unity project now has multiple duplicate providers.

## Expected behavior

Build should show content properly

## Screenshots

![image](https://user-images.githubusercontent.com/63201460/85303992-39ae7b00-b479-11ea-8607-b17b6ec465a1.png)

## Your setup (please complete the following information)

- Unity 2019.2.6f1
- Target SDK Version 10.0.19041.0
- Minimum Platform Version 10.0.10240.0
- Same issue with MRTK v2.3 and v2.4

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

This issue occurred on existing project, so we created a new project from scratch. Same issue with the new project. What worked fine yesterday is failing today.

Old build works fine after uninstalling new build from device and re-installing the old one.

**Comment by wiwei** [comment]
We've had this issue around for a bit - see: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6907

Beyond it looking funky there's no runtime/edit time impact. Closing this out as it's a dupe

**Comment by HKBSC** [comment]
Please read the description. Beyond the duplicate providers, the actual build doesn't work as well.
