### ISSUE TITLE
AudioPluginMicrosoftSpatializer & Build Exceptions (dll's unloaded)

### ISSUE THREAD

**Issue by jasonhbartlett** [microsoft/MixedRealityToolkit-Unity#8090]
## Setup
Windows 10 Pro 20H2 (Build 19042.3330)
Visual Studio Community 2019 16.6.2
Unity 2019.3.15f1
MRTK 2.4.0
Target UWP - HoloLens 2 - ARM64

## Error
Getting the following message on the UnityPlayer.log on the HL2:

```
Loading native plugins
  Loading AudioPluginMicrosoftSpatializer.dll
Plugins: Failed to load 'AudioPluginMicrosoftSpatializer' because one or more of its dependencies could not be loaded.
(Filename: C:\buildslave\unity\build\Runtime/Misc/Plugins.cpp Line: 246)
```
For full output see: [PasteBin: unityplayer.log](https://pastebin.com/0zbA98iN)

## To reproduce
This is a new project and I followed these instructions to add the Microsoft Spatializer to the project:
[Enable Spatialization](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/spatial-sound-in-unity.md#enable-spatialization)

I have verified/installed all the Microsoft Visual C++ Redistributables from:
[The latest supported Visual C++ downloads](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

## Output from Deployment
I'll include output here from VS Deployment/Debug log which may help point to the issue.  There are some exceptions there as well as some dll's that are loaded and then unloaded for some reason.  I don't know whats going on.  The app runs, but in the unityplayer.log is where I see the Plugins: Failed to load 'AudioPluginMicrosoftSpatializer' error.
Here is output from the build:
[PasteBin: deployment.log](https://pastebin.com/zpKNnNGM)

**Comment by davidkline-ms** [comment]
Which version of the Microsoft Spatializer did you install?

**Comment by jasonhbartlett** [comment]
@davidkline-ms 
Version 1.0.12 (from NuGet4Unity)

**Comment by ashtat** [comment]
@jasonhbartlett thank you for reporting this issue! This was a regression with our CMake project generation that we didn't catch, we've recalled v1.0.12 and updated it with [v1.0.18](https://github.com/microsoft/spatialaudio-unity/releases/tag/v1.0.18) which should work correctly.

**Comment by keveleigh** [comment]
Closing as it's reported that this should work with a newer version of the spatializer.
