### ISSUE TITLE
Customer feedback: Teleport pointer configuration is hidden / undiscoverable

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#8093]
From https://dotnetbyexample.blogspot.com/2020/06/migrating-to-mrtk2-changing-viewpoint.html.

"If you are using MRTK2 to build a Mixed Reality app to run on Immersive Headsets - or at least an environment where you control the environment using controllers - you can typically 'teleport' forward and backward by pushing the thumbstick forward and backward, and rotate the view by pushing it left and right. Your viewpoint rotates either 90° left or 90° right (and of course you can change the view by rotating your head, but that's not the point). But what if you want to rotate only 45°? Or 22.5°?

I have spent quite some time looking in the MRKT2 config profiles looking for the rotation angle. The reason I could not find it, is because it's not there. At least, not directly. It's in the pointer - the 3D cursor, if you like. Yeah, you read that right."

This is great feedback, as it points to challenges in adoption. Thank you @LocalJoost!

**Comment by LocalJoost** [comment]
Hi David,

Thank you for appreciating the implied feedback.

I hope you will forgive me my snarky remarks. I was expressing my amazement of find a setting like this in a prefab, as I am pretty much conditioned to look into configuration profiles by now. I certainly did not did not write it this way to deride all the effort that went into the MRTK2, I really love it and it’s my bread and butter. They aim of my blog is at the top:
“This blog attempts to be a collection of how-to examples in the Microsoft software stack - things that may take forever to find out, especially for the beginner. I see it as my way to return something to the Microsoft community in exchange for what I learned from it.”

Finding this setting  took, indeed, quite some time. I could have asked, but I am stubborn. Now, I hope, no-one ever will have to search for this again. The snarkyness comes from writing this just after having finally having located the setting. The ‘gosh darn it I was looking in the wrong place all the time’ feeling every developer knows all to well 😉

I would suggest putting this somewhere in the camera or controller settings. I think there’s arguments for both. I’d be happy to discuss.

Kind regards,

Joost van Schaik

Windows Development MVP & Windows Insider MVP
Sent from my over-the-top-spec'd Windows Mixed Reality development beast

"Where we go we don't need... roads"

**Comment by mwarvik** [comment]
Thanks for this! We have been looking all over the place for where to disable the TeleportCursor for MRTK 2.5 on HoloLens 2. Didn't think to look in a _bloody_ cursor 😂 I agree that it's hard to discover, as I have been through the configuration profiles several times.
