### ISSUE TITLE
MixedRealityToolkitFiles class is specific to the Assets folder and could use some improvements

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#8094]
## Describe the bug

The MixedRealityToolkitFiles class has some strong assumptions that the MRTK will only ever be present in the Assets folder of a project. #8058 does some good initial work to expand the scope of this expectation, but with the ability to reference a [local UPM package by path](https://docs.unity3d.com/Manual/upm-localpath.html) makes it impossible to support all cases by manually adding specific folders.

Unity provides a way to search and load assets from UPM packages in [a generic way via the `AssetDatabase` APIs](https://docs.unity3d.com/Manual/upm-assets.html). This could be used in a few different ways:

1. Use `AssetDatabase.FindAssets` to locate the sentinel files, which will give us an `AssetDatabase`-compatible path to the well-known folders.
1. Use GUID references to load assets instead of hard-coded paths, which can be more robust to file / folder / package name changes, as well as how the package or asset is consumed.
1. Use `AssetDatabase.FindAssets` to locate specifically-named assets, like the default profiles.

and probably other ways I'm not thinking of right now.

**Comment by davidkline-ms** [comment]
The call stack for searching for the MRTK folders includes:

- SearchForFoldersAsync
- SearchForFolders (in a for loop)
- TryRegisterModuleViaFile (does not return a status - what is it trying?)
- RegisterFolderToModule

At no point in the above is it possible to early exit from the SearchForFolders loop.
