### ISSUE TITLE
Cursors flicker ever ~2 seconds due to briefly-missing SR meshes

### ISSUE THREAD

**Issue by matthejo** [microsoft/MixedRealityToolkit-Unity#8097]
## Describe the bug

I've been debugging why Remote Assist's cursors seem to flicker every 2 seconds or so. I've put tracing in our custom Cursor, RaycastProvider, and PointerMediator to try to understand what happens. It appears that there's a single frame during which the SR mesh is not available, and the RaycastProvider hits nothing. This leads to there being no focused object, and the cursor positions itself at a default distance instead.  In this trace, you can see there's a frame where the RARaycastProvider hits nothing (while I'm staring directly at a piece of furniture).  When the RACursor checks the previously-focused element (the SR mesh), its name has changed to Unused Spatial Mesh and it's no longer active. By the next frame, the RARaycastProvider does hit the SR mesh again, and the cursor jumps back to where it should be.
 
RAPointerMediator: there are 1 pointers with these states: (Gaze Pointer = True)
RARaycastProvider: hit object is True, name = SpatialMesh - 1026
RACursor: Pointer is Gaze Pointer, NewTargetObject is: SpatialMesh - 1026, OldTargetedObject is: SpatialMesh - 1026 isActiveInHierarchy=True
Distance to new cursor position: 0.00619647
RAPointerMediator: there are 1 pointers with these states: (Gaze Pointer = True)
RARaycastProvider: hit object is False, name = null
RACursor: Pointer is Gaze Pointer, NewTargetObject is: null, OldTargetedObject is: Unused Spatial Mesh isActiveInHierarchy=False
RACursor: No GazeTarget, target object is null!
Distance to new cursor position: 0.8049302
RAPointerMediator: there are 1 pointers with these states: (Gaze Pointer = True)
RARaycastProvider: hit object is True, name = SpatialMesh - 1026
RACursor: Pointer is Gaze Pointer, NewTargetObject is: SpatialMesh - 1026, OldTargetedObject is: null
Distance to new cursor position: 0.7948098

## To reproduce

In Remote Assist, this reproduces easily by looking at a fairly-close surface mesh with either the Gaze cursor or a hand cursor. At approximately the rate of SR mesh updates, you'll see the cursor flicker to a different depth and then back. In Remote Assist, some of the cursor visuals are quite large and the depth change is very noticable (e.g. the cursor we show while taking a snapshot has instruction text and an large camera bracket icon).

## Expected behavior

We would ideally like for none of the FocusProvider's focus updates to happen on a frame where there is not currently an SR mesh to hit, either because the SR observer doesn't have frame gaps, or because the FocusProvider knows to pause raycasting during those gaps in time.

## Your setup (please complete the following information)

- Unity Version 2018.4.21f1
- MRTK Version 2.5.0-20200622.1

## Target platform (please complete the following information)

- HoloLens 2

**Comment by davidkline-ms** [comment]
Still looking into this. Going to attempt another min repro.

**Comment by davidkline-ms** [comment]
I attempted a repro on the latest mrtk_development (pre-2.6.0) branch and am unable to repro using the Hand Interaction Demo. Offline discussion indicated that this demo should display the issue if Spatial Awareness is enabled.

Repro steps:
* Update Hand interaction demo to have spatial awareness enabled
* Configure the visible mesh material to solid yellow
* Build and deploy to HoloLens 2
* Raise a hand and hover the far interaction cursor over the mesh
* Wait for several mesh updates
 
 Cursor remains at the expected distance (on the mesh). It does not flicker or jump in distance.
 
 * Lower hands and say "select" - this turns on the Gaze cursor
 * Hover the gaze cursor over a different part of the mesh
 * Wait for several updates

 Cursor remains at the expected distance (on the mesh). It does not flicker or jump in distance.

**Comment by davidkline-ms** [comment]
Based on my testing, the issue appears to be either; fixed in MRTK 2.6.0 or related to the RAPointerMediator/RARaycastProvider mentioned in the issue description.

**Comment by davidkline-ms** [comment]
@polar-kev, assigning to you to review the repro results and my conclusion.

**Comment by polar-kev** [comment]
@matthejo , can you please try to reproduce on the latest available MRTK?

**Comment by keveleigh** [comment]
Going to close this as "no repro". Please reopen if you're able to repro with the latest MRTK.
