### ISSUE TITLE
The static class 'Rest' collides with Microsoft.Rest.ClientRuntime

### ISSUE THREAD

**Issue by rubit0** [microsoft/MixedRealityToolkit-Unity#8104]
## Describe the bug

Several Azure SDK nuget packages that are part of the cognitive services (Custom Vision, Bot Framework, etc.) family have a dependency to the package **Microsoft.Rest.ClientRuntime** which collides with the helper static class [Rest](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/33499654c85e036f41b10d16ec25962f2f27c400/Assets/MRTK/Core/Utilities/WebRequestRest/Rest.cs).

This makes using those otherwise compatible packages impossible and forces to write your own custom client to those Azure services.

## To reproduce

- Download one of the Microsoft.Azure.CognitiveServices packages from nuget.org
- Download the dependent Microsoft.Rest.ClientRuntime package from nuget.org
- Unpack the nuget packages and place the .Net Standard based .dll files into your Unity Plugins folder
- MRTK classes that uses the Rest helper class will complain that it can't associate Rest anymore to a namespace.

## Workaround

Rename the Rest helper class to something else, but this breaks upgrading to future MRTK versions.

## Additional context

Solution: Rename [Rest](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/33499654c85e036f41b10d16ec25962f2f27c400/Assets/MRTK/Core/Utilities/WebRequestRest/Rest.cs) to something like **RestHelper**.

**Comment by wiwei** [comment]
This collision is pretty unfortunate - the tricky part is that renaming is going to break existing users who use those Rest wrappers that we have (even if renaming to RestHelper would be the better thing long term).

It would be safer from this perspective to just use a using clause to avoid this within the DevicePortal code to avoid this conflict.

**Comment by rubit0** [comment]
Great idea, adding an explicit using clause in the DevicePortal.cs (from what I saw it is only class using it) makes this a good compromise.
