### ISSUE TITLE
SharingService Schema Version 

### ISSUE THREAD

**Issue by CocarDorian** [microsoft/MixedRealityToolkit-Unity#8113]
## Overview
When I imported all the packages and set my scene up correctly and I try to join my SharingService server I get the error of having an invalid schema version.

## Expected behavior

![expected](https://user-images.githubusercontent.com/61968485/85996839-0768c480-ba09-11ea-9aa5-154562e639c7.PNG)

## Actual behavior
![Error](https://user-images.githubusercontent.com/61968485/85996785-f4ee8b00-ba08-11ea-9341-bd379d5d25b8.PNG)

## Steps to reproduce
I set up my project just to have a simple object that tries to connect to the server so that I can eliminate other factors.

I created a new project
Imported HoloToolkit
Arranged all objects and configured all settings (projects and inspectors)
And finally the tricky part I think:
I create these folders External/HoloToolki/Sharing/Server, with the SharingService.exe inside that I got from Microsoft "MR Sharing 240: Multiple HoloLens devices". 

It seems I don't have the right / latest version of the SharingService.exe, is that correct?
But every time I'm looking for a GitHub link for the latest version, I come up against a 404 page.

![SharingS404](https://user-images.githubusercontent.com/61968485/85997217-8827c080-ba09-11ea-8507-2fb9cbbca7b9.png)

## Unity editor version
2018.4.23f1

## Mixed Reality Toolkit release version
HoloToolkit-Unity-2017.4.1.0

**Comment by timGerken** [comment]
Maybe this path instead?
https://github.com/microsoft/MixedRealityToolkit-Unity/tree/htk_release/External/HoloToolkit/Sharing/Server

**Comment by CocarDorian** [comment]
It seems to be working, I have no longer any mistakes. But I still don't have a user joining the room. Do you have any ideas about this? Otherwise, I'll look for the problem. Thank you very much!

**Comment by CocarDorian** [comment]
It works!!! With the session manager, I was able to get in and out of the room without any problems. I'll look through my ImportExport script and figure out / come up with why I didn't join the room directly. Thank you!!!

**Comment by wiwei** [comment]
Looks like @timGerken resolved the issue, thanks!
