### ISSUE TITLE
Add pipeline for building Android

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#8129]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/314

___

Tracking work to be done for an Android build pipeline. A basic sanity check to ensure that our code is able to build on that device properly

**Comment by eusebiu** [comment]
Please consider Oculus builds too (i.e. OCULUS_INTEGRATION_PRESENT is defined).

**Comment by davidkline-ms** [comment]
@keveleigh is investigating. Not _required_ for 2.6, though should be done as soon as feasible
