### ISSUE TITLE
HL2 iris recognition

### ISSUE THREAD

**Issue by Lenovezhou** [microsoft/MixedRealityToolkit-Unity#8130]
Hi sir,  I'm looking for the iris recognition solution and hitting this topic by chance. May I know what Windows APIs we can use for the HL2 iris recognition and where I can find them?  I've looked into the HL2 documentation but unluckily no relevant stuff found.
Thanks so much in advance.

**Comment by wiwei** [comment]
If this existed it would be under the research mode stuff: https://docs.microsoft.com/en-us/windows/mixed-reality/research-mode

There was an old issue that looks pretty similar:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6956

If you're looking for specific access to the iris scanner hardware, I don't believe that's exposed in an way that you can use directly, but you can use the APIs built on top of that (i.e. "what user is logged in")
