### ISSUE TITLE
Documentation shouldn't start on the development version

### ISSUE THREAD

**Issue by Kent1LG** [microsoft/MixedRealityToolkit-Unity#8131]
## Describe the issue

By default, the documentation web site start on the mrtk_development branch. Most users are using the release versions for their productions, searching in the documentation could be dangerous if the information are not the same.

Example : A Coworker of mine was searching for a specific function, he found it on the doc but this was only available on the develpment branch, he didn't see the difference and was wondering why he can't find it his script.

## Feature area

I think it should be better if we start by default on the latest release documentation.

**Comment by keveleigh** [comment]
@thalbern How possible would this be with the way our docs versioning is currently configured?

**Comment by thalbern** [comment]
actually switching wouldn't be that hard to do - I can adjust the script to what i did for mrtk unreal - that means we wouldn't have a root version of the docs anymore and can easier swap to the one we're pointing to, but have to adjust the output CI dir for dev branch for that.
