### ISSUE TITLE
No hand tracking on Unity 2019.4 Holographic Remoting

### ISSUE THREAD

**Issue by Kent1LG** [microsoft/MixedRealityToolkit-Unity#8132]
## Describe the bug

Like said on the title, the hand tracking doesn't work on the Unity Holographic Remoting. I only got the line and the pointer of my hands for far interactions.

## To reproduce

1. Create Scene with MRTK ("Add to scene...")
2. Launch Holographic Remoting 
3. Place Hands face to the device and see

## Expected behavior

Using Holographic Remoting should show and use the hands for near interaction, hand menu, etc.

## Your setup (please complete the following information)

- Unity Version 2019.4/.1 - VR legacy (no XR SDK)
- MRTK Version 2.4

## Target platform (please complete the following information)

- HoloLens 2

## Additional context
I'm using the Holographic remoting with usb connection (wifi disable).

**Comment by keveleigh** [comment]
Have you gone through the manual DotNetWinRT instructions in our documentation? https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.4.0/Documentation/Tools/HolographicRemoting.html#manual-dotnetadapter-installation

The rest of that page describes a more automatic process for using Unity 2018, but we found one of the steps had issues on 2019 and instead recommend this process.

**Comment by Kent1LG** [comment]
Hi Kurtis !
Thank you really much, that it : I needed to manually install DotNetWinRT.
Now it's working with hand tracking.
