### ISSUE TITLE
BoundsControl Reacting to Configuration Changes + Rotation Pivot

### ISSUE THREAD

**Issue by ILikeCreamCheese** [microsoft/MixedRealityToolkit-Unity#8157]
Hi guys, 
I currently have two issues with using the BoundsControl and wanted to ask for advice:

## Description
I'm using MRTK 2.4 and I'd like to use the BoundsControl and ObjectManipulator to make a handle interactive by adding the components at runtime through code like this:

```
BoundsControl boundsControl= gameObject.AddComponent<BoundsControl>();

boundsControl.BoxDisplayConfig = this.boxDisplayConfiguration;
```
I've come across the problem that making changes to configurations in such a manner is essentially ignored by the BoundsControl, because the initialization happens only in Awake. 

The other issue I'm facing is that I'd like to rotate around the pivot of my mesh (i.e. just rotate in local space) instead of rotating around the rigroot. For example imagine having a lever that you want to pull down.

### Configuration issue
In the application Im working on arbitrary meshes are loaded at runtime, so I can't just create a prefab with the configuration already on there with the mesh. It's also uncertain whether a part of an object will be interatable at the time I'm loading the meshes. I could refactor my code to move the meshes under an instance of such a prefab, but would prefer not having to, since it might lead to other issues with my hierarchy.
Another solution would be to copy the contents of my configurations to the configuration of the boundsControl, but this seems to be not the point of using scriptableObjects.

Albeit probably not a very elegant solution, adding a method to refresh the private configuration classes is currently working for me:
```
        public void NotifyConfigurationsExchanged()
        {
            DestroyRig();

            // ensure we have a default configuration in case there's none set by the user
            scaleHandlesConfiguration = EnsureScriptable(scaleHandlesConfiguration);
            rotationHandlesConfiguration = EnsureScriptable(rotationHandlesConfiguration);
            boxDisplayConfiguration = EnsureScriptable(boxDisplayConfiguration);
            linksConfiguration = EnsureScriptable(linksConfiguration);
            handleProximityEffectConfiguration = EnsureScriptable(handleProximityEffectConfiguration);

            // instantiate runtime classes for visuals
            scaleHandles = new ScaleHandles(scaleHandlesConfiguration);
            rotationHandles = new RotationHandles(rotationHandlesConfiguration);
            boxDisplay = new BoxDisplay(boxDisplayConfiguration);
            links = new Links(linksConfiguration);
            proximityEffect = new ProximityEffect(handleProximityEffectConfiguration);

            CreateRig();
        }
```

### Rotation pivot issue
This is the line where the rotation is happening: 

`Target.transform.RotateAround(rigRoot.transform.position, axis, angle);`
BoundsControl.cs in TransformTarget(HandleType transformType)

Would love to see a property where you can change the rotation axis to be local such that it would look like this:
`Target.transform.RotateAround(this.targetObject.transform.position, axis, angle);` 

I realize that the BoundsControl is not out of experimentation, so I'm not sure if solutions to these problems are already planned. I still wanted to use it because it worked better with using the constraints. I checked out the issue about the refactoring of the bounding box but couldn't find anything that would fit my description.

Thanks in advance and best wishes

**Comment by Zee2** [comment]
Seems this was resolved by #9045. If this persists, please reopen.
