### ISSUE TITLE
SR_Triangles shader is missing from MRTK SDK

### ISSUE THREAD

**Issue by Strepto** [microsoft/MixedRealityToolkit-Unity#8176]
## Describe the bug

`MRTK/SDK/Experimental/PulseShader/Materials/MRTK_SurfaceReconstruction.mat` is missing a shader in the Foundation package. 

The shader its missing seems to be `SR_Triangles` which is in the `MRTK/Extensions` package `MRTK/Extensions/LostTrackingService/Assets/SR_Triangles.shader`.

## To reproduce

Find
`MRTK/SDK/Experimental/PulseShader/Materials/MRTK_SurfaceReconstruction.mat` after importing just the `MRTK Foundation` package in a new project. Observe that it has a missing shader.

## Expected behavior

The missing shader should be included in the foundation package.

## Screenshots

![image](https://user-images.githubusercontent.com/3185998/87548306-9da91580-c6ac-11ea-99d0-17d8af095805.png)

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.4.1f1]
- MRTK Version [e.g. v2.4] (Foundation Package Only)

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by cre8ivepark** [comment]
We need to graduate SR Pulse shader. I'll update it to match shell behavior (generate pulse on air-tap)

**Comment by Strepto** [comment]
@cre8ivepark I see you fixed the behaviour of the Pulse-effect in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8307 , but the actual shader was not promoted from the "Extensions" package. The `SR_Triangles.shader` is still located at `Assets/MRTK/**Extensions**/LostTrackingService/Assets/SR_Triangles.shader`.

**Comment by davidkline-ms** [comment]
Fixed in the upcoming 2.5.0
