### ISSUE TITLE
Make Eye Gaze Input usable by default in MRTK

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#8184]
## Describe the problem

Currently, eye tracking is not enabled in our default MRTK profiles. This is because the gaze cursor tracks the eyes by default, causing it to flicker across the screen with eye movement in when deployed on device. We need to work to improving the developer experience with eye tracking and make it easier for devs use the technology without compromising user experience.

Some specific issues are the gazepointer is locked to be either head or eye tracking and is coupled with the voice system. We need to separate out these components.

**Comment by polar-kev** [comment]
We'll be looking at this for MRTK v3

**Comment by RogPodge** [comment]
Eye gaze is now a first class feature in v3. Going to leave this open on until v3 goes public.

**Comment by Zee2** [comment]
MRTK3 is gaze-on by default.
