### ISSUE TITLE
HoloLens 2 Unity 2019.4 build works only in Debug mode

### ISSUE THREAD

**Issue by Kent1LG** [microsoft/MixedRealityToolkit-Unity#8185]
## Describe the bug

I'm currently creating  an HoloLens 2 application and i m facing a weird issue. I'm used to placing some sprites, 3D models and  interact with a Hand menu. If i m building for the device I'm choosing to set in ARM64 Release the deploying.
Then no sprites appear, no hand menu works but the 3D Models are fine.
When I try it in Debug ARM64 everything works fine but with FPS dropping specific to debug mode.

## To reproduce

1. Create Unity 2019.4 project
2. Import MRTK 2.4
3. Set a simple scene with : sprites, 3D Models and Hand menu (Hand Constraint Palm Up)
4. Build it : x64, Release
5. On Visual Studio, deploy : ARM64 Release

## Expected behavior

Everything should work in any case whether it's in Master, Release or Debug.

## Your setup (please complete the following information)

- Unity Version 2019.4.0f1
- MRTK Version 2.4

## Target platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
@Kent1LG can you see if you can disable smoothing as mentioned here:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7624

This looks to be an ARM64 compiler bug, we just haven't created the min repro/figured out how to tease out a minrepro yet to get this fixed in the compiler itself.

**Comment by Kent1LG** [comment]
Hey Will,

Thank you for the tips, it'is now working. Is all the smoothing checkbox of the MRTK components had to be disable too?
There is one on the Radial View, on the TapToPlace and more.

**Comment by wiwei** [comment]
Sorry for the delay here - yes, pretty much anything that uses smoothing (in Solver.cs) is affected by this. If you wanted to fix this once in the code you could hard-code smoothing to true (or rather change the places that use it within Solver to not use smoothing)

**Comment by Kent1LG** [comment]
OK good to know.
Thank you Will
