### ISSUE TITLE
Input Animation Recording is not working with Leap Motion

### ISSUE THREAD

**Issue by hyungilkim** [microsoft/MixedRealityToolkit-Unity#8221]
## Describe the bug
When recording hand input using Input Simulation tools with Leap Motion, hand animation is not recorded at all. (Input recording works perfectly with HoloLens 2)
Only head movement is recorded.

## To reproduce
1. [Configure Leap Motion](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/CrossPlatform/LeapMotionMRTK.html#using-leap-motion-by-ultraleap-hand-tracking-in-mrtk) for hand tracking
2. Open the Input Simulation Tools window (_Mixed Reality Toolkit > Utilities > Input SImulation_)
3. _Record_ the hand input
4. _Playback_ shows only the head movement, not hand animation.

## My setup
- Tested in Unity version 2018.4.16f1, 2019.3.7f1, 2019.4.4f1
- MRTK Version v2.4.0
- Leap Motion mounted OpenVR headset

## Target platform
- OpenVR

**Comment by CDiaz-MS** [comment]
Hi @hyungilkim I tested this out and it is currently working for me.

Steps:
- Imported the MRTK 2.4 Foundation package into Unity 2019.4.5
- Imported the Leap Core assets 4.5.0
- Remained the Standalone platform 
- Opened a new scene
- Added MRTK via Mixed Reality Toolkit > Add to Scene and Configure 
- Changed the configuration profile to the `DefaultLeapMotionConfigurationProfile`
- Cloned the profiles and changed the Leap Controller Orientation to Desk

I also did hold my hand over the leap tracker prior to recording.

![InputAnimationRecordingLeap](https://user-images.githubusercontent.com/53493796/88975016-5e62f300-d26e-11ea-8771-89615840114e.gif)

**Comment by hyungilkim** [comment]
Thank you @CDiaz-MS for your help!
I tested with your steps, and it works.
(Setting Leap Controller Orientation to _Desk_ in MRTK > Input > Input Data Providers > Leap Motion Device Manager)

However, when I change the Leap Controller Orientation to _Headset_, the recording did not work.
![brgIPYIppj](https://user-images.githubusercontent.com/14970203/89162467-149c4480-d5af-11ea-95a0-67d4628f3187.gif)

**Comment by CDiaz-MS** [comment]
Hi @hyungilkim the fix in #8354 should have resolved this issue.  Please reopen this issue if the leap hands continue to not show up while using the input animation.

**Comment by hyungilkim** [comment]
Hello @CDiaz-MS, the issue has resolved! thank you very much :)
