### ISSUE TITLE
ObjectManipulator that requires permission to manipulate

### ISSUE THREAD

**Issue by julesra** [microsoft/MixedRealityToolkit-Unity#8231]
## Describe the problem

I'm using Hololens2 and making a networked infrastructure (for connecting AR+VR+PC+Mobiles) which allows virtual objects to be manipulated by any user. This means that I might try to grab and object which another user is currently using. When that happens, I want the local user's ObjectManipulator to still be able to point at objects, but in this case it should be denied access to the manipulation, and should display some feedback (ex: changing cursor to "X")

Please let me know if there's something that already exists for this.

## Describe the solution you'd like

I'd like it so when I look at an object and grab it, the system should ask that object if it's allowed to be manipulated, and the manipulation should happen only if I'm allowed.  This could be something inside ObjectManipulator which calls a function that tells it true/false if it's allowed to manipulate the object; and a nice cursor that gets displayed if the manipulation is denied.
PS: I'm not sure if ObjectManipulator is the right place for this fix, so please correct me if there's another approach.

## Describe alternatives you've considered

- Ideally I would like the ObjectManipulator to call a function that tells it if it's allowed to manipulate the currently focused object or not. 
- I'm not sure how to make that in a way that is suitable for the inspector (in the inspector I'd like to just drag that boolean function in the inspector, similar to how it's done for events)
- I also tried extending ObjectManipulator to a new class with custom start/end of manipulation, but I get runtime errors when I try grabbing the object through the extended class. I'm not sure if extending ObjectManipulator actually works.

## Additional context

I'm happy to answer any questions, or to be told of other approaches, or to implement this if people are interested. Thanks !

**Comment by Alexees** [comment]
@julesra What we did (Using Mirror for networking) was handling authority in a different class and only when authority was obtained, enabled the manipulator for that user. This is not something I'd put into the MRKT as it's merely a matter of the component being enabled or not.

**Comment by julesra** [comment]
For anyone else interested in doing the same, here's what I did to make that work based on Alexees' suggestion:
1. Create a class that implements IMixedRealityPointerHandler. It will need to be attached on each object that has an ObjectManipulator.
2. In that class, start by disabling ObjectManipulator (but do this after the first update, so that the ObjectManipulator script has a chance to initialize)
3. Also in that class when OnPointerDown is invoked, check if the object should be manipulated; if yes, reenable ObjectManipulator and call .OnPointerDown passing it the same event.
4. In the same class register an event handler on ObjectManipulator.OnManipulationEnded; that handler should just disable the ObjectManipulator.
5. To this class I added event handlers OnManipulationStarted/Ended/Denied so it functions in a similar way to ObjectManipulator. 
5. You might also want to implement IMixedRealityFocusChangedHandler if you want the cursor to change like it does on ObjectManipulator

@Alexees thanks for the suggestion; please let me know if there's anything else to consider.

**Comment by davidkline-ms** [comment]
It appears there is a viable workaround. MRTK v3 will be based on a different foundation and should get a feature like this "for free".
