### ISSUE TITLE
BoundsControl's ActivateOnStart breaks the handle visibility options

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#8239]
## Describe the bug
Handle configurations allow the user to selectively enable and disable specific handles. When the BoundsControl has been set to use the `ActivateOnStart` option, all handles will be visible, even if they have been configured to not be visible.

## To reproduce

1. Go to BoundsControlExamples.unity example scene
2. Select CoffeeCup3, which already has `ActivateOnStart` selected.
3. Edit the CoffeeCup3 rotation handle configuration to specify that none of the handles should be visible.
4. Play the scene
5. Observe that the handles are now visible.

## Expected behavior
Handles should obey their visibility settings, even when `ActivateOnStart` is used.

## Versions

- Unity 2018.4.23f1
- MRTK Version v2.4 - active `mrtk_development`
- All platforms, AFAIK

## Additional context
This is blocking my work on #8236

**Comment by thalbern** [comment]
ha! this is funny - i just tried to reproduce and it actually works with hiding the scale handles and the rotation handles - the bug only occurs when hiding ALL rotation handle types at the same time :D

**Comment by thalbern** [comment]
there was an early out when resetting handles that caused this behavior, but only when all rotation handle types (axes) were deactivated. it's an issue that is local to the rotation handles. i changed the visibility check now to be easier to understand and fixed that early out. however this can not have interfered with the translation handles as they aren't using rotation handle specific logic
