### ISSUE TITLE
Tilegenerator creates icons which then result in an "Failed to build appx from Solution.  Error 1"

### ISSUE THREAD

**Issue by XPav** [Microsoft/MixedRealityToolkit-Unity#824]
I used the Tilegenerator to make all the icons.   When I went to build via Holotoolkit, the AppX build failed -- red text flashed by and I got an error 1.

Running MSBuild from the command line brought up:

`"C:\dev\AugmntrHoloTest\WindowsStoreApp\AugmntrHoloTest.sln" (default target) (1) ->
"C:\dev\AugmntrHoloTest\WindowsStoreApp\AugmntrHoloTest\AugmntrHoloTest.csproj" (default target) (2) ->
(_ValidateAppxPackage target) ->
  Package.appxmanifest(19,54): error APPX3207: App manifest references the wide 310x150 logo image 'Assets\Wide310x150Logo.scale-400.png' which is larger than the maximum image file size. It must be no larger than 204,800 bytes.`

The outputted icon is 236KB.

`[C:\dev\AugmntrHoloTest\WindowsStoreApp\AugmntrHoloTest\AugmntrHoloTest.csproj]
  Package.appxmanifest(20,27): error APPX1619: App manifest references the splash screen image 'Assets\SplashScreen.scale-400.png' which does not have valid dimensions. It must be 2480x1200 pixels. [C:\dev\AugmntrHoloTest\WindowsStoreApp\
AugmntrHoloTest\AugmntrHoloTest.csproj]`

The outputted icon is 2400x1200.

**Comment by jvhgamer** [comment]
I'm not a dev. for the Toolkit, but with that said, the first error is because the maximum file size is 200kb, (204800 bytes). The second error is because your dimensions are off. It wants 2480x1200.

**Comment by XPav** [comment]
These are the output files from the Tilegenerator, generated from the 2 source images passed in. 

I did not output these, the Holotooklit Tilegenerator did.    I fixed this by using simpler source images.

The place this should be fixed is in the Tilegenerator, which could just simple error out when it went to make the WSA tiles.

**Comment by StephenHodgson** [comment]
Maybe we should write a test into it that checks the output image properties and makes sure to throw proper errors so a build cannot even be triggered if the images do not pass the test.

**Comment by XPav** [comment]
I think that would be all that's needed -- it just wasn't clear why the build was failing.

The other option could be to display AppX build errors along with the "failed to build error 1" dialog box.
