### ISSUE TITLE
PointerUtils doesn't work with custom PointerMediator

### ISSUE THREAD

**Issue by 4ipideil** [microsoft/MixedRealityToolkit-Unity#8243]
## Describe the bug
PointerUtils.SetHandRayPointerBehavior have no affect with custom PointerMediator;

When im trying to override and use my own PointerMediator, PointerUtils functionality stops working for me. 
## To reproduce

1. create custom class, for example:
`public class TestDefaultPointerMediator: DefaultPointerMediator
    {   
        public override void UpdatePointers()
        {
            base.UpdatePointers();
        }
    }`
2. Go to Pointers MRTK settings;
3. Click on **DefaultPointerMediator** drop down menu
3. Select **TestDefaultPointerMediator** instead
4. Disable pointers somewhere in the code:
`PointerUtils.SetHandRayPointerBehavior(PointerBehavior.AlwaysOff, _hand);
 PointerUtils.SetHandGrabPointerBehavior(PointerBehavior.AlwaysOff, _hand);
 PointerUtils.SetHandPokePointerBehavior(PointerBehavior.AlwaysOff, _hand);`
5. See that there is no affect at all

## Expected behavior
the code above should actually disable all of those hand related MRTK pointers;

## Your setup (please complete the following information)
- Unity 2019.4.5f1
- MRTK 2.4.0

## Target platform (please complete the following information)
- HoloLens 2

**Comment by wiwei** [comment]
Ay... yuck. Addressed in that PR. You could patch it in a similar to way unblock yourself temporarily

**Comment by 4ipideil** [comment]
don't worry, all good i have a workaround!

ср, 5 серп. 2020 о 21:24 Will <notifications@github.com> пише:
