### ISSUE TITLE
MixedRealityToolkit creates duplicate Service GameObjects

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#8247]
## Describe the bug

When you open a scene with the MixedRealityToolkit in it, unfolding it reveals at least two GameObjects for each service. It's possible to have even more although I have no idea how they get created.

## To reproduce

1. "Add To Scene And Configure..." in a new scene
2. save that scene
3. create a new scene
4. open the previously saved scene
5. unfold the MixedRealityToolkit GameObject

## Expected behavior

Each Service's GameObject appears once

## Screenshots

![image](https://user-images.githubusercontent.com/32508825/89261801-f9711980-d62e-11ea-9ccf-fe78016b77f8.png)

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.3.14.f1]
- MRTK Version mrtk_development (of today)

## Target platform (please complete the following information)

- Unity Editor

**Comment by wiwei** [comment]
Ah this issue has been around for some time - having some trouble finding the duplicate issue but this has been opened before.

How often are you using these nested game objects for configuring the MRTK? We're considering turning this off by default until we can get it into a better working state for everyone.

**Comment by keveleigh** [comment]
Here's a/the duplicate issue: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6907

**Comment by Alexees** [comment]
@wiwei I discovered this by accident I actually never look into these. The one scene we additively load with the MRKT in it was filled with 8 of each service.

**Comment by wiwei** [comment]
Closing this as duplicate (see the PR that's also currently open which is going to turn this stuff off)
