### ISSUE TITLE
FollowMeToggle throws exception when added on disabled GameObject

### ISSUE THREAD

**Issue by devedse** [microsoft/MixedRealityToolkit-Unity#8248]
## Describe the bug

I've followed the MRKT 2 for HoloLens 2 tutorial where you setup the Rover. When you disable the "Menu" gameobject though the following exception pops up:

![image](https://user-images.githubusercontent.com/2350015/89287038-8037ed80-d653-11ea-80f8-9fc07a06d86a.png)

Even though I have the Menu disabled:

![image](https://user-images.githubusercontent.com/2350015/89287256-ede41980-d653-11ea-88fb-55749bc9123d.png)

## To reproduce

1. Complete the rover tutorial here: https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-06
2. Disable the Menu
3. Press the play button

## Expected behavior

I would not expect this exception

## Screenshots

See above

## Your setup (please complete the following information)

- Unity Version: 2019.4.6f1
- MRTK Version: 2.4.0

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

N/A

**Comment by wiwei** [comment]
@devedse I've tried to repro this locally (mrtk_development) and haven't been able to hit this - I followed this section specifically: https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-06#creating-a-dynamic-menu-that-follows-the-user (so in all honesty, I don't have a project in a state where it's already done steps 1-5 and then started at step 6).

Do you have the full log associated with that error (i.e. callstack of the errror), or alternatively, some zip of the code in that state?

**Comment by devedse** [comment]
@wiwei  I tried to reproduce the issue today but of course everything works again :smile:. No idea what was acting up but for now let's just close the issue. If I can reproduce it in the future I'll let you know.
