### ISSUE TITLE
Document Screen Space Needs for Outline Effect

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#8252]
## Describe the issue
With the current documentation it's possible to get into a situation where the outline effect doesn't appear to work at all or only works in certain parts of the scene.

![image](https://user-images.githubusercontent.com/5230670/89333944-626e8680-d65b-11ea-8f1a-c0b503956103.png)

This is due to the effect being accomplished in screen space. And when using a screen space effect it's important to understand things like draw order and depth testing. However these things are not discussed in the documentation.

## Feature area
Here are some suggestions of things to add:

1. Add information about it being a screen space effect.

1. Explain the need for the outline material and the material(s) of the object being outlined to be rendered in a different order.

1. Recommend a render order to use (greater than 2000?) and explain why that number.

1. Show screenshots and / or provide clear description of how to set the render layer.

1. Finally, the document already says to turn off depth writing but doesn't explain why. Depth writing would help solve the draw order problem, but it would also potentially cause the outline material to occlude the object being outlined.

## Existing doc link
[MRTK Standard Shader - Mesh outlines](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_MRTKStandardShader.html#mesh-outlines)

## Additional context
N/A

**Comment by jbienzms** [comment]
Tagging @Cameron-Micka

**Comment by Cameron-Micka** [comment]
I'll probably end up moving outlines to their own markdown file (like we did with hoverlight and proximitylight) so I can add all of this extra information. Thanks!

**Comment by polar-kev** [comment]
@Cameron-Micka do you have any cycles to look at this?

**Comment by Cameron-Micka** [comment]
> @Cameron-Micka do you have any cycles to look at this?

Hey @polar-kev, I just started a new project and trying to gauge my availability. I'll put this on my "todo" list to visit as soon as I can. Good news is I just wrote similar docs for MRTK-Unreal we could borrow from: https://github.com/microsoft/MixedReality-GraphicsTools-Unreal/blob/main/Docs/MeshOutlines.md

**Comment by Zee2** [comment]
Closing as stale in favor of MRGT repo. @Cameron-Micka tracking this.

**Comment by Cameron-Micka** [comment]
New docs can be found here: https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-graphicstools/features/mesh-outlines 

We also have some ongoing work to improve outline setup: https://github.com/microsoft/MixedReality-GraphicsTools-Unity/issues/33
