### ISSUE TITLE
Using RectTransform for UX Elements

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#8257]
## Describe the problem

One thing I've been wondering for months now is why MRTK doesn't utilize [RectTransform](https://docs.unity3d.com/ScriptReference/RectTransform.html) for UX controls and panels. I'm wondering if this is an intentional design decision or if it's perhaps due to a perception that **RectTransform** only exists for Unity UI?

**RectTransform** is not explicitly tied to Unity UI. And using **RectTransform** will _not_ automatically add a **Canvas** to the scene. 

**RectTransform** _is_ a regular **Transform**. In fact **RectTransform** inherits from **Transform**.

**RectTransform** can be used any place **Transform** can, but not the other way around.

The main benefit **RectTransform** provides that **Transform** does not is the ability to use Unity's [relative layout](https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/UIBasicLayout.html) system. And while I understand Unity filed that article under "Unity UI", all of those layout features can be used without needing Unity UI or **Canvas**.

I wanted to attach some animations to demonstrate the value. Here is a clip of the **HandMenu_Large_WorldLock_On_GrabAndPull** prefab.

![Scale](https://user-images.githubusercontent.com/5230670/89444275-154fea80-d717-11ea-973d-e69422645e03.gif)

Notice that the only way to resize this prefab is to scale it. But using scale _stretches_ the object rather than resizing it. If a developer wants to modify this prefab, they must manually resize and reposition each child element in the prefab. This is a _lot_ of work. (Trust me, I've been doing it.)

Here's the same menu prefab but I converted the entire layout to use **RectTransform**:

![RectTransform](https://user-images.githubusercontent.com/5230670/89444535-737ccd80-d717-11ea-9216-1e0eae938434.gif)

Notice there are now actual **Width** and **Height** fields that can be modified separate from **Scale**. And changing those values results in an intelligent relayout of the control. 

I can now also set meaningful constraints. For example I can say that the slider collection should always be **0.03** meters from the right edge of its container:

![image](https://user-images.githubusercontent.com/5230670/89444817-e71eda80-d717-11ea-8c13-44c247dfb790.png)

Finally, I'm attaching this zip file:

[RectLayout.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/5030187/RectLayout.zip)

In it you will find a **.unitypackage** that includes my redesign of the menu and a test scene. 

## Describe the solution you'd like

I would like to see all menus, panels, slates and UX controls switch to using **RectTransform**. I believe this will greatly reduce (if not eliminate) the friction currently experienced when attempting to resize or modify MRTK UX prefabs.

## Describe alternatives you've considered

I've spent a lot of time editing existing prefabs and I haven't come up with a better solution. I even tried some dynamic resize scripts. 

## Additional context

I did spend a bit of time researching **RectTransform** to make sure it doesn't add a massive performance penalty. So far, other than a very old bug I haven't been able to find any notable performance penalties. Having said that, it would be prudent to do some testing and validation of our own before making a full switch over.

**Comment by polar-kev** [comment]
Hey @jbienzms, thanks for this investigation. Flexible prefabs will be achievable in MRTK v3 using new volumetric layout tools.

**Comment by Zee2** [comment]
@jbienzms this is pretty cool. Like @polar-kev said, we're pursuing some new standalone volumetric layout tools, but using built-in recttransforms for layout is neat. I would have figured that this would cause some serious perf issues but I guess not! I'll ping you to chat about this some more.
