### ISSUE TITLE
SpatialMappingObserver.cs Error CS1525

### ISSUE THREAD

**Issue by Rayne91** [Microsoft/MixedRealityToolkit-Unity#826]
Dear everyone,
I was studying a book to start developing with Hololens. The problem is that, when i copy the Assets folder from the HoloToolkit, i have this problem and i can't build the project.

`Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingObserver.cs(444,136): error CS1525: Unexpected symbol ';', expecting ':'`

The corrisponding line code is:
` SurfaceObject? replacedSurface = UpdateOrAddSurfaceObject(outstandingMeshRequest.Value, destroyGameObjectIfReplaced: false);`

I tried to reimport the assets folder and also to automatically modify the Line Endings in Visual Studio but it didn't help to resolve the problem.

Can anyone help?
Thank you in advance

**Comment by suuhaasa** [comment]
I had got the same error, I was using Unity 5.3 HTP. I used it with Unity 5.6 and it worked.

**Comment by jessemcculloch** [comment]
@Rayne91 - Did you ever get this resolved?
