### ISSUE TITLE
assets in foundation should not depend on assets in examples packages

### ISSUE THREAD

**Issue by brandf** [microsoft/MixedRealityToolkit-Unity#8265]
## Describe the bug

There are several instances of a similar issue.  Assets dependencies violate the presumed package dependencies.  What i mean by that, is that Foundation presumably shouldn't depend on Examples (otherwise Examples shouldn't be optional while Foundation is required), however certain assets in the foundation package such as MRTKStandardUnityUI.mat have guid references to assets from the examples package, such as Circle.png.

## To reproduce

1. load Circle.png (from examples) into your dependency tool (see screenshot) - something in Foundation depend on it
2. I found dozens of similar cross-package asset references using an automated search.

## Expected behavior

foundation doesn't depend on any asset in 'higher level' packages.

- Unity Version [2019.4.6f1]
- MRTK Version [2.4.0]

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

![image](https://user-images.githubusercontent.com/877443/89582179-0b002000-d7ed-11ea-8af7-0700c858ddaf.png)

**Comment by wiwei** [comment]
Thanks for filing this!

When fixing this issue, we should make sure to add some tooling to ensure this doesn't regress again. We can probably just use the dependency code to double check this (we'll have to see how fast this can be and if it can go with the usual PR validation pipeline)

**Comment by brandf** [comment]
Can I use this bug to make a pitch for first class UPM support?  It's easy to add & maintain along with the legacy unitypackages you already provide.  

With UPM you have to be explicit about your package dependencies, and while I was converting the MRTK packages to UPM packages I needed to understand the (implicit) dependencies between your unitypackages.

have tooling to validate that assets don't violate package dependencies, and discovered there are many upward dependencies between foundation and examples as well as circular dependencies between examples and extensions (about 70 total)

**Comment by wiwei** [comment]
For UPM, this is something that we're actively working on in 2.5 (actually because of how our dev branch is the default github.io one you can see some of the documentation for the not-yet-released feature: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/usingupm.html)

Having tooling would still be necessary for us, but still ideally would be separate from the UPM implementation itself (i.e. we should be able to know by understanding the asmdef references within each group of things which happen to correspond to a UPM package that things are good/bad, rather than depend on grouping them in UPM packages first and then waiting for compiler errors).

**Comment by brandf** [comment]
Not sure I agree with you wrt the tooling, or at least you'd need a manual version to avoid issues.

The asmdef references and package references aren't always 1 to 1.  Specifically, the former is often a subset of the latter.

You can end up in a situation where you have no code dependency on a package, but you do have asset dependencies, and in this case you'd have no compiler errors.  It would also generally just work in your development project since you have all the packages, but if someone pulls down a subset of the packages from UPM they'll end up with broken references.

**Comment by polar-kev** [comment]
Hey @brandf, as of MRTK 2.5 we support importing packages through UPM and as of MRTK 2.5.1, the specific issue you mentioned is fixed.
