### ISSUE TITLE
Scrolling Object Collection stops working after using "Select" Voice Command on list element.

### ISSUE THREAD

**Issue by yeahbunny** [microsoft/MixedRealityToolkit-Unity#8277]
## Describe the bug

After using "Select" Voice Command on any element in Scrolling Object Collection, scrolling stops working at all.

## To reproduce

1. Open ScrollingObjectCollection scene on HL2
2. Scroll any of available list (e.g. VerticalScroll Buttons 2) - working fine
3. Use "Select" Voice Command on scrolled list 
4. Try again to scroll list - ScrollingObjectCollection stops working

## Expected behavior

The expected behaviour is to have the possibility of using basic Voice Commands with a scrollable list without any bugs and errors.

## Your setup (please complete the following information)

Unity Version 2019.4.0f1
MRTK Version 2.4.0
Branch release
ScrollingObjectCollection.scene
IL2CPP
Release build

## Target platform (please complete the following information)

HoloLens2
UWP
IL2CPP

## Additional context

In our application, that is utilizing the ScrollingObjectCollection, this bug appeared only after upgrading to 2.4.0. On earlier versions Voice Commands was working fine with ScrollingObjectCollection.

**Comment by vaoliva** [comment]
Hi @yeahbunny. At the moment we are working on the graduation of the scroll component. The changes are being made to a separate branch [graduation/scroll_view](https://github.com/microsoft/MixedRealityToolkit-Unity/tree/graduation/scroll_view). This issue was opened before and closed with a fix added to the graduation branch. Could you please try the branch?

**Comment by vaoliva** [comment]
Issue fixed on https://github.com/microsoft/MixedRealityToolkit-Unity/tree/graduation/scroll_view

**Comment by yeahbunny** [comment]
Hi @vaoliva!
Much thanks for your answer. I tested graduation scroll view branch (scene: ScrollingObjectCollection) and unfortunately situation is the same. When I say "Select" VC when looking on Scrolling Object Collection then list is no longer working.
