### ISSUE TITLE
Ultraleap/Leapmotion controller manual offset

### ISSUE THREAD

**Issue by HyperLethalVector** [microsoft/MixedRealityToolkit-Unity#8284]
Hi there!

Is there any reason why we can't use a transform for the offset of the leapmotion/ultraleap controller? Like how we can with the XR Input controller provided by the leapmotion sdk?

**Comment by CDiaz-MS** [comment]
Hi @HyperLethalVector is the offset you are referring to the `Leap Controller Offset` while the controller orientation is on the Desk?
![image](https://user-images.githubusercontent.com/53493796/90037146-b0e1dd80-dc78-11ea-899a-2787f8724c35.png)

**Comment by HyperLethalVector** [comment]
What happens if we intend to use it in a HMD, but can't adjust the offset from the head ;) 
Also offset might include rotation, which is why the leapmotion sdk allows the offset to be set by a transform.

*shrug*

**Comment by CDiaz-MS** [comment]
Controlling the offset of the hands if the device is in the headset orientation is possible.  When the leap controller is in the headset orientation, the `LeapXRServiceProvider` component is attached to the main camera during play mode and the offset can be edited there.  Although we could maybe expose these settings in the Leap Motion Device Manager to make things easier.
 
![image](https://user-images.githubusercontent.com/53493796/90174617-202ffe00-dd5b-11ea-88d4-86ee8971f8ba.png)

**Comment by HyperLethalVector** [comment]
I agree, however your implementation doesn't search for a Leap XR service provider and use it's settings, check my modified code snippet, rather than spawning a gameobject I first use the one in the scene.
I think this is better, as it allows for adjustment during runtime.
(LeapMotionDeviceManager.cs)
![image](https://user-images.githubusercontent.com/8954571/90198311-7d39bb80-de10-11ea-9fdd-31e784e2ef47.png)


Might be useful :)

**Comment by CDiaz-MS** [comment]
@HyperLethalVector the transform offset can be modified in the current implementation, here is an example:

```
LeapMotionDeviceManager leapMotionDeviceManager = CoreServices.GetInputSystemDataProvider<LeapMotionDeviceManager>();
LeapXRServiceProvider leapXRServiceProvider = leapMotionDeviceManager.LeapMotionServiceProvider as LeapXRServiceProvider;
leapXRServiceProvider.deviceOffsetMode = LeapXRServiceProvider.DeviceOffsetMode.Transform;
leapXRServiceProvider.deviceOrigin = gameObject.transform;
```
But I agree that we can expose offset properties in the profile for easy initial offset value setting.
