### ISSUE TITLE
ControllerVisualizer.cs is calling on WSA properties and classes that dont exist yet

### ISSUE THREAD

**Issue by jessemcculloch** [Microsoft/MixedRealityToolkit-Unity#829]
In the ControllerVisualizer.cs file in the Dev_Unity_2017.2.0 branch, there are some calls that are throwing errors.  These are calls to WSA API's that don't exist yet. 
SpatialInteractionSource.Handedness is one of them, on line 108 (called as source.Handedness)
SpatialInteractionSourceHandedness type is also missing, on line 113

There are a few other instances of this same error from other locations.
Is there a more recent SDK I should be using?

**Comment by jessemcculloch** [comment]
So, once I downloaded the 16232 SDK this started working.  Might need to add this to the documentation.

**Comment by keveleigh** [comment]
A link to that SDK exists in the main Toolkit readme in the dev branch, but it's worth adding to the script documentation itself as well.

**Comment by StephenHodgson** [comment]
This was actually a Unity Bug.

XR: Windows Mixed Reality is now only supported when running Windows Fall Creators Update (RS3). This would previously work on RS2 builds, but this configuration is no longer supported.
