### ISSUE TITLE
Unable to add Leap Motion to MRTK Project w/ Leap Motion Orion 4.51

### ISSUE THREAD

**Issue by rlbogue** [microsoft/MixedRealityToolkit-Unity#8291]
## Describe the bug

Unable to configure an MRTK project for Leap Motion when using Leap Motion 4.5.1

## To reproduce

1. Start a brand new project.  (I'm using Unity 2019.4.6f1)
2. Import the Leap Motion Core module from 4.5.1,
3. Optionally import the Graphic Renderer, Hands, and Interaction Engine packages.
4. Import MRTK Foundations 2.4.0.
5. Optionally import MRTK Extensions
5. Notice errors indicating that the 'Type or namespace name...' appears for many types and namespaces.

## Expected behavior

I expected that the code would compile correctly.

## Your setup (please complete the following information)

- Unity Version 2019.4.6f1
- MRTK Version 2.4.0
- Leap Motion Orion 4.5.1

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by CDiaz-MS** [comment]
Hi @rlbogue, MRTK 2.4 only supports version 4.4.0 and 4.5.0 for the leap motion core assets, but support for the 4.5.1 assets will be added for the 2.5 release.

**Comment by rlbogue** [comment]
@CDiaz-MS 4.5.0 doesn't appear to work either.  Are special configurations that are not documented required?

**Comment by CDiaz-MS** [comment]
Issue resolved on the HoloDevelopers slack
