### ISSUE TITLE
Provide example non uniform scaling centered scale handles 

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#8302]
## Describe the problem

Provide an MRTK example that mimics the HL2 shell slate scaling:

![image](https://user-images.githubusercontent.com/16922045/90260805-f69ed180-de43-11ea-934b-c31f0763442e.gif)

This can be achieved by adding a custom constraint and scale handle to bounds control while using non uniform scaling.

Created from discussion in PR #8293

**Comment by thalbern** [comment]
@vaoliva

**Comment by thalbern** [comment]
related to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8693

**Comment by Zee2** [comment]
This will be implemented in MRTK3 as a RectTransform resizer. (Not scaling!)
