### ISSUE TITLE
Register speech phrases (keyword) to MRTK speech via C# codes

### ISSUE THREAD

**Issue by taikitakashita** [microsoft/MixedRealityToolkit-Unity#8310]
How can we register speech phrases (keyword) to MRTK speech via C# codes?
We do not want to use Unity UI to register speech phrases like this document (https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Speech.html) because we have so many words to register.

**Comment by Kent1LG** [comment]
Hi guys,

Is this feature is still planned?
For a next release?

Thank you

**Comment by keveleigh** [comment]
Closing as a duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5316. This is definitely something we should support in MRTK3 (FYI @MaxWang-MS, is this already the case?)

**Comment by keveleigh** [comment]
Duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5316

**Comment by MaxWang-MS** [comment]
Yeah this is something we already support in MRTK3.
