### ISSUE TITLE
Update the MRTK configurator to turn off "Graphics Jobs" by default in Unity 2019

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#8326]
There's a relatively bad and crippling Unity bug which will crash the app when the "Graphics Jobs" setting is enabled in Unity and the app is deployed to HL2:

https://issuetracker.unity3d.com/issues/enabling-graphics-jobs-in-2019-dot-3-x-results-in-a-crash-or-nothing-rendering-on-hololens-2

The workaround is just to turn off Graphics Jobs until Unity has that fixed, as the effect is quite painful.

**Comment by davidkline-ms** [comment]
Addressed by #8327
