### ISSUE TITLE
Building Unity C# projects does not work with the Dev_Unity_2017.2.0 branch

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/MixedRealityToolkit-Unity#833]
- Make a basic app using Unity 2017.2.0b5, with the Dev_Unity_2017.2.0 branch HoloToolkit in it
- Put only a MixedRealityCameraParent in it
- Select .NET as scripting backend
- Select "Unity C# Projects" 
- Fails with "KeyNotFoundException" and two more
![capture](https://user-images.githubusercontent.com/4129183/29006014-fd0bf3d0-7ae7-11e7-9c59-4bb508bd0fe6.PNG)

This is currently blocking my progress into MR

**Comment by LocalJoost** [comment]
Hmm. This might just be a Unity bug, not a HTK issue: 
https://unity3d.com/unity/beta/ see issue 927925

**Comment by jessemcculloch** [comment]
This is a Unity bug, not a HTK issue.  

That said, I think this issue should not be closed until the bug is fixed on the unity side, for tracking purposes.  That way if someone comes to the HTK looking for an answer, they will at least be able to track the problem back.
