### ISSUE TITLE
Keyboard.cs Refactor

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#834]
- Seeing as this class is a singleton we should also probably rename it to `KeyboardManager`.
- `Keyboad.cs` should implement the `IDictationHandler`.

**Comment by mpb84** [comment]
Any updates on this? The dictation recognizer always fails for me.

**Comment by keveleigh** [comment]
@mpb84 That sounds like it should be fixed in #1496

**Comment by StephenHodgson** [comment]
@keveleigh indeed this was
