### ISSUE TITLE
UPM registry link invalid / down?

### ISSUE THREAD

**Issue by grubFX** [microsoft/MixedRealityToolkit-Unity#8345]
## Describe the issue
I'm currently trying to add MRTK to a new Unity3D 2019.4 project, following the [tutorial](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/usingupm.html). I added the relevant registry entry & dependencies to the manifest but UPM fails to find the packages (2.5.0 as in the tutorial). Could the [registry](https://pkgs.dev.azure.com/aipmr/MixedReality-Unity-Packages/_packaging/Unity-packages/npm/registry) be down, since also I don't get any response opening the link in the Browser?

## Feature area
Is the link incorrect or is the registry down?

## Existing doc link
[Tutorial](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/usingupm.html)
[Registry Link](https://pkgs.dev.azure.com/aipmr/MixedReality-Unity-Packages/_packaging/Unity-packages/npm/registry)

**Comment by wiwei** [comment]
Ah, we really need to fix our default docs branch - the default one points to the development branch, which contains preview information for the upcoming release. Our UPM support is something we're adding in 2.5 (soon (TM))

**Comment by grubFX** [comment]
I see, thanks for the clarification - hoping that it's soon™️ soon™️ 😄
