### ISSUE TITLE
Add "Apply Lighting Settings" to project settings wizard

### ISSUE THREAD

**Issue by brean** [Microsoft/MixedRealityToolkit-Unity#835]
The default settings in Unity set a Skybox and Realtime and Mixed Lighting. You can manually set

* Skybox Material to None,
* Environment Lighting to Gradient,
* Disable Realtime Lighting and
* Disable Mixed Lighting

in the Lighting Window of Unity 3D, but it would be nice if there would be a point for this in the HoloToolkit-Menu.

**Comment by StephenHodgson** [comment]
This should also be able to handle occluded headsets as well.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
