### ISSUE TITLE
Merge stuff from MRDesignLabs over to HTK

### ISSUE THREAD

**Issue by brean** [Microsoft/MixedRealityToolkit-Unity#836]
Hi,

The [MRDesignLab](https://github.com/Microsoft/MRDesignLabs_Unity_Tools) has some parts that might be useful in the standart HTK. 
It would for example be nice to have the the AnimCursor as part of HTK together with the other cursors.

**Comment by StephenHodgson** [comment]
This is already planned and outlined in the main repo readme.

**Comment by brean** [comment]
Sorry for asking without searching enough. Thank you for pointing me to the roadmap!

**Comment by StephenHodgson** [comment]
We can leave this open until we merge for tracking purposes. Thanks.

**Comment by paseb** [comment]
@StephenHodgson you can assign this one to me as I'm working with @NeerajW and team to bring over all of the foundational functionality.

thanks
-pat

**Comment by Zod-** [comment]
Are they compatible at all right now? Like for example can I use the `InteractableObject` in combination with HTK?

**Comment by hridpath** [comment]
@paseb Have you been able to define a map as to what items in the HTK will merge with comperable functionality in the MRDL? Any idea how much of the HUX will be affected?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
