### ISSUE TITLE
Configuration of XR Plugin causes head/camera locked image

### ISSUE THREAD

**Issue by laultman** [microsoft/MixedRealityToolkit-Unity#8361]
## Describe the issue
Starting new project and configuring and desire XR capability to have images off the window and in free space. Unity 2019.4 allows legacy XR to be configured. Unity 2020.1.3 requires XR Plugin management. I have been lately following these instructions: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html 
In 2019.4 the Unity player will not accept keyboard or mouse input. In 2020.1.3 these work. In 2019.4 the HoloLens 2 behaves as expected (images are in free space and can be manipulated). In 2020.1.3 images are testable in Unity Player but are head/camera locked in HoloLens (image stays directly in front of the camera/eyes as if a still image). No one seems to be complaining so I think it is configuration.

## Feature area
What's incorrect? What's missing? The configuration is likely the problem but there are so many options it is impossible to trial and error fix.

## Existing doc link
If this is about something in an existing document, please provide link

**Comment by keveleigh** [comment]
It sounds like the configuration profile needs to be changed to the default XR SDK one: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html#required-in-mrtk

>Choose the "DefaultXRSDKConfigurationProfile" as the active profile or clone it to make customizations. This profile is set up with MRTK's XR SDK systems and providers, where needed.

Once updated, the camera profile will attach a TrackedPoseDriver to the camera at runtime. You can also do that manually and save it into the scene if you expect to only use the new XR plugin system.

**Comment by laultman** [comment]
I did this previously with disastrous results. See this topic for more information: #8362

**Comment by laultman** [comment]
@keveleigh I tried this again as you suggested. Still does not work. Could not locate TrackedPoseDriver in the configuration settings.

**Comment by laultman** [comment]
One thing I can say with fair certainty, the problem is the XR SDK plugin. It works without it and it does not when it is used.

**Comment by keveleigh** [comment]
>Could not locate TrackedPoseDriver in the configuration settings.

If you couldn't locate TrackedPoseDriver when trying to add a component to an object, it's worth double checking that the required packages are installed:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html#windows-mixed-reality

Legacy Input Helpers contains the TrackedPoseDriver script. Otherwise, the XR SDK Camera Settings in the camera profile will be what adds it automatically at runtime.

**Comment by keveleigh** [comment]
Closing this down due to other similar issues that have since been reported as fixed. I haven't encountered this in a long time.
