### ISSUE TITLE
Using the DefaultXRSDKConfigurationProfile Causes Player Keyboard/Mouse Unresponsive

### ISSUE THREAD

**Issue by laultman** [microsoft/MixedRealityToolkit-Unity#8362]
## Describe the bug
There are three related bugs affecting Unity player 2020.1.3 and HoloLens 2. **Bug 1** prevents the use of XR Management because of bug 2. Bug 1 forces you to use the built-in legacy XR and Spatial audio is no longer accessible as there are no configuration options available. To resolve Bug 1 you are forced to use XR management and to enable Windows Mixed Reality checkbox. This setting causes two additional behaviors that are unacceptable.
In Bug 1, selecting DefaultHoloLens2ConfigurationProfile (legacy XR, no Spatial Audio) causes the objects rendered on HoloLens 2 to be contained an a Window (not in free space.) To fix this causes **Bug 2.** In the Project Settings adding the XR Management configuration to switch to the new XR SDK plugin causes the HoloLens 2 now render the scene object at a fixed location locked to the head/camera location (always in front of the eye and the gaze dot is present). The object is not reachable. But the scene does function in Unity Player as expected. To fix Bug 2, follow the XR SDK profile setup [here](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html )
This causes **Bug 3**: Setting the profile to DefaultXRSDKConfigurationProfile causes the Unity Player editor to become unresponsive to keyboard and mouse (these both work normally out side the Player). HoloLens 2 continues to display objects in a head/camera locked, unresponsive to any input.

## To reproduce

Bug 1: Legacy XR does not allow spatial audio.
1 Clean install of Unity 2020.1.3 and start an new 3D project. **Do NOT use XR Management allow it to default to legacy XR.**
2 Set up for UWP by adding MRTK 2.4.0 to a new scene. Change the MRTK to DefaultHoloLens2ConfigurationProfile
3 Configure, enable Spatial Awareness (requires cloning of the DefaultHoloLens2ConfigurationProfile).
3 Add a cube to the scene (optional add BoundingBox and configure it to be controlled by hand input) set the Z position at 1.5.
4 Test in Unity Player, should work as expected.
5 Deploy to HoloLens 2, the scene object will display inside a Window (not in free space). If you configured a BoundingBox on the cube it should respond normally in the Window. Spatial Audio will not work because it cannot be configured in this version with the legacy XR.

Bug 2: Fixing Spatial Audio with XR SDK causes locked scene in HoloLens.
1 Using the above project, go to Project Settings and install XR SDK using the XR Management and check the Window Mixed Reality checkbox.
2 Using the Unity Player, verify the scene still operates as expected (no changes from those above.)
3 Deploy to HoloLens 2, Bug 2 appears. The scene object is now not contained in a Window, but it is now locked to the head/camera and is non-responsive.

Bug 3: Fix the Locked scene 
1 Using the recommended DefaultXRSDKConfigurationProfile and configure per these [instructions](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html )
2 Using the above project run in Unity Player, the keyboard and mouse are unresponsive in the Player window.
3 Deploy to HoloLens 2, and there is no change to the problem. The image remains locked and unresponsive.

## Expected behavior

I expected to be able to use Unity to configure, edit, and deploy to HoloLens 2 and that scenes would be usable as they are in other applications.

## Your setup (please complete the following information)
- Unity Version 2020.1.3
- MRTK Version 2.4.0

## Target platform (please complete the following information)
- HoloLens 2

**Comment by laultman** [comment]
For completeness, I performed the same setup in Unity 2019.4.8f1 with expected results.
1 New Unity 3d project configured with MRTK 2.4.0 with legacy XR and XR configuration in Project Settings with Windows Mixed Reality enabled.
2 Using the DefaultHoloLens2ConfiguratonProfile as my beginning profile.
3 I am able to add scene objects and to manipulate them in a free space setting in the HoloLens 2 device.
4 The Unity Player works as expected.

**Comment by laultman** [comment]
I found that no scene had been selected in the Build Settings. Adding the scene to the build and then building it seemed to correct the Unity Player not providing support of keyboard and mouse. This did not fix the locked condition in HoloLens. It appears as if it has taken an and image screen-shot of the player window right down to the white doughnut as a still image rather than the 3d object. It should warn you that there are no selected scenes in the output.

**Comment by laultman** [comment]
I failed to add the scene to the build. Adding it to the build had no effect.

**Comment by keveleigh** [comment]
Unity 2020 removes the legacy XR pipeline, so any non-XRSDK MRTK profiles will fail to work. That explains bug 1. We don't yet fully support Unity 2020, but what you're describing should be possible.

It sounds like you successfully solved bug 2 by following the XR SDK set-up instructions.

Bug 3 sounds like a result of the input simulation service not being in the profile, which was the case in the 2.4 release but has been fixed in #8144. You should be able to add it manually to the profile.

**Comment by laultman** [comment]
@keveleigh Thanks, will give your suggestions a try. For now, sticking with 2019 LTS and legacy XR.

**Comment by keveleigh** [comment]
Closing this down, as everything mentioned above should have been fixed by either MRTK releases or Unity releases. Please reopen if not!
