### ISSUE TITLE
Combine hand gesture and eye-gaze to manipulate objects together

### ISSUE THREAD

**Issue by xempie** [microsoft/MixedRealityToolkit-Unity#8364]
## Describe the problem

In some cases it's necessary to manipulate a gaze-selected object with hands. In this case we don't need to use gesture to select the object (for example if it's out of reach or in a different position). But seems we can manipulate the objects with either hand gesture only or eye-gaze only (or some cases combination of other inputs)
I think we had this option in Hololens1 but can't find it in Hololens2 .

## Describe the solution you'd like

The requested feature is to select the object with eye-gaze and use hand to move the object. So, in this case hand gesture should behave differently because as soon as hand is moved, the gesture gets activated and take the control of the manipulation (i.e. a different object that it points to).

## Describe alternatives you've considered

An alternative which I'm thinking about is to deactivate hand gesture or having a possibility to override it while  eye-gaze is used (if needed) and only hand movements are considered not the raycast or gesture.

**Comment by polar-kev** [comment]
Hey @xempie, although something like this should be possible today in the MRTK by turning off hand rays, turning on eye gaze, and writing some custom code, we are working on bringing an out of the box solution to MRTK v3. If you have a HoloLens 2, you can check out a preview of this experimental feature in the latest release of the Mesh app in the Microsoft store.
