### ISSUE TITLE
Toolkit Examples Lack Directions on MRTK Profile Selection to Use with Examples

### ISSUE THREAD

**Issue by laultman** [microsoft/MixedRealityToolkit-Unity#8365]
## Describe the issue
This [page](https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.4.0/README.html) jumps users into documentation of specific example demo scenes where the demo documentation is not providing enough information.

## Feature area
What's incorrect? What's missing? The problem is that the demo scenes do not provide the configuration profile necessary for the demo to work. It simply defaults to the MRTK default configuration profile.
## Existing doc link
If this is about something in an existing document, please provide link
This demo tells the user where to find the scene but does not provide the necessary configuration profile to use and there are lots of them in the drop-down list.

**Comment by laultman** [comment]
Here is the link to an example where the documentation is insufficient. https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.4.0/Documentation/README_HandMenu.html

**Comment by polar-kev** [comment]
Hi @laultman, we've done the work to make sure that every example scene now has the correct profile by default. If you use MRTK 2.7 this should no longer be an issue. If you still encounter problems please let us know.
