### ISSUE TITLE
Button Documentation Needs a Simple Custom C# Controller Hook-up Example

### ISSUE THREAD

**Issue by laultman** [microsoft/MixedRealityToolkit-Unity#8367]
## Describe the issue
The documentation seems to provide a largely complete description of management of the button object in MRTK. 

## Feature area
What's incorrect? What's missing? It took hours to dig out of the examples how to compose an new C# script controller and then how to hook that up to objects. For example to toggle an object on and off where I also want to change its properties using C#. The basics of programming for objects is also important and there is a decided lack of instruction.

## Existing doc link
If this is about something in an existing document, please provide link
https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.4.0/Documentation/README_Button.html

**Comment by polar-kev** [comment]
Hi @laultman, since the MRTK is built on top of Unity, there are some prerequisite Unity concepts that we do not cover in our docs.
