### ISSUE TITLE
IsEyeTrackingEnabled in POINTER profile determine whether Eye Tracking is enabled

### ISSUE THREAD

**Issue by LocalJoost** [microsoft/MixedRealityToolkit-Unity#8390]
## Problem

To enable Eye Tracking for HL2, you have to make sure two things are set:

- Windows Mixed Reality Eye Gaze Provider must be added to tot Input Data Providers
- In the _pointer_ settings you have set if eye tracking is enabled.

This strikes me as a rather non-intuitive place to store this setting. It's not a display property of the gaze or a cursor. It's affecting the behavior of the PROVIDER.

## Solution
I think "IsEyeTrackingEnabled"  and "UseHeadGazeOverride" should be properties of the provider's profile and be edited in there, as shown below:
![image](https://user-images.githubusercontent.com/4129183/91267626-12737300-e774-11ea-980c-2637552d7106.png)

**Comment by vaoliva** [comment]
Hi @LocalJoost . Agree with the issue.  There are also other gaze settings found under MixedRealityToolkit / Input / Pointer profile ( Gaze Provider Type, Use Head Gaze Override) that maybe we should consider to move. They are not really relevant to the Eye Gaze Data provider though. So maybe we consider moving those to the top of Input Profile, close to Focus Provider.

**Comment by davidkline-ms** [comment]
@RogPodge, assigning to you to ensure that this scenario is straight forward in MRTK v3

**Comment by RogPodge** [comment]
Fundamentally, we think this pattern is still the right one to use (the gaze provider might get eye gaze data, but it can choose as to whether or not use to that data for targetting). The PR pushed changes the wording to better describe it's actual function, and contains a link to the eye targetting getting started guides.
