### ISSUE TITLE
edge case: toggling between visible and occlusion display modes will reset customized materials

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#8397]
when #8396 is fixed, there will still be a scenario where the developer's custom material will be reset to the default visible material. this would occur if the application switches display modes from visible -> occlusion -> visible.

**Comment by davidkline-ms** [comment]
Needs a way to track when a material was customized or cached. Also a way to say "force material refresh"

**Comment by davidkline-ms** [comment]
This should definitely be looked into for MRTK3. The ability to reliably maintain the spatial mesh materials is key to end user understanding of the application's understanding of the world.

**Comment by Zee2** [comment]
This is covered by the ARFoundation `ARMeshManager`'s mesh prefab, I believe.
