### ISSUE TITLE
Anchor point for teleportation.

### ISSUE THREAD

**Issue by TheLLspectre** [microsoft/MixedRealityToolkit-Unity#8400]
Hi everyone !

## Describe the issue
That's not really an issue... I tried to make anchor point for the teleportation. Currently simply is just a box collider with a transform point and when the teleportation's raycast hit this box collider the state of the teleportation passed to "Valid" and the cursor point goes to the anchor point. By this way the best result will be the "player"  changes repository. Like to be included in vehicule.

And also may be we need to detect the anchor point by the teleportation's raycast ?

## Feature area
May be I missed something about that and you can tell me how I can do that. Or by my script I can may be subscribe to an event of the teleportation system to change its state.

Tanks ;)

**Comment by RogPodge** [comment]
Closing since this sounds like something which can be handled by the teleport hotspot
