### ISSUE TITLE
BaseControllerPointer.cs Null Reference Error on InputSourceParent Parameter

### ISSUE THREAD

**Issue by JShull** [microsoft/MixedRealityToolkit-Unity#8409]
## To reproduce

1. While tethered to a PC running an Oculus Link in Unity's Editor
2. Seems to happen when going between transitioning the headset up on my head and back down while simultaneously having controllers/hands being tracked

## Expected behavior

Line 475 of BaseControllerPointer.cs throws a null reference exception error. This is occurring because at that moment in time the InputSourceParent reference hasn't been fully established yet and/or is cleared when the headset goes into an idle state?

## Screenshots
![image](https://user-images.githubusercontent.com/12342337/91583437-3921dd00-e91f-11ea-90c6-e458889dbc0d.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.8LTS
- MRTK Version 2.4

## Target platform (please complete the following information)

- Oculus Quest

## Additional context

I originally posted this bug with the MRTK Quest extension and realized that this is actually more or so related to the BaseControllerPointer script which the quest extension is referencing. My workaround is just to check if the InputSourceParent exists. Included a photo for that here as well and the previous bug I filed with MRTK-Quest.
![image](https://user-images.githubusercontent.com/12342337/91583577-6e2e2f80-e91f-11ea-9d1a-b77bdf12dde3.png)

[MRTK-Quest Closed Bug](https://github.com/provencher/MRTK-Quest/issues/88#issuecomment-682671258)

**Comment by VirsabiMunk** [comment]
Same issue. But when this happens the pointer breaks and cannot be reactivated, so ignoring is not a solution.

**Comment by davidkline-ms** [comment]
@RogPodge, can you investigate if this still happens (read: in the MRTK shipped implementation)?

Thanks!

**Comment by RogPodge** [comment]
@davidkline-ms I'll get to this after I get back and have my Oculus setup again. Our current posted scenario for using Oculus Quest with MRTK doesn't use Oculus Link though, and I personally haven't tried using Quest in Editor when handling my quest support work.

For any new people looking at this issue, we've added official Quest support in October 2020, you can find the docs for deploying on the Quest [here](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/CrossPlatform/OculusQuestMRTK.html), but using the quest in-editor is unexplored territory at this date.

**Comment by polar-kev** [comment]
Removing from the 2.6 milestone since we haven't explicitly stated support for Oculus Link.
