### ISSUE TITLE
Wrong Reported Camera FOV

### ISSUE THREAD

**Issue by amoffatt** [microsoft/MixedRealityToolkit-Unity#8417]
## Overview
Unity "Camera" component reports too large of FOV for for HL2, causing any logic dependent on FOV to fail.

## Expected behavior
Something appropriate, close to 30 degrees.

## Actual behavior
Camera vertical FOV locked to 135 degrees (if change to "Horizontal") then reports 150 degrees

## Steps to reproduce
Run MRTK Hand Tracking demo while remoting to HL2.

## Unity editor version
2019.4.8f1, Windows XR Plugin 2.3 (previous XR Plugin version 2.2 caused the device's  Horizontal FOV to be reported as the vertical FOV)

## Mixed Reality Toolkit release version
2.4

![HL2 Bad FOV](https://user-images.githubusercontent.com/437344/91663575-9abc8580-ea9e-11ea-9375-7e9fa571abe0.JPG)

**Comment by wiwei** [comment]
I think this issue has come up in the past as well, but it's not really an MRTK related issue:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/176

@keveleigh in case I'm missing anything here

**Comment by amoffatt** [comment]
@wiwei Where can the issue be logged? I was told that Windows XR Plugin bugs should also be logged to MRTK2? This was aggravated by the plugin 2.2 => 2.3 update, but reported an incorrect value in 2.2 as well. Note this is not Unity Editor-specific, and affects scripts in the built application too.

**Comment by wiwei** [comment]
@amoffatt Issues in the plugins themselves (shipped via Unity's package registry) should get filed on Unity itself. We have some system for talking with them on these issues, but since it's not actually in MRTK code it should be tracked where work is done.

**Comment by amoffatt** [comment]
Will, Thank you for the update. Developing for the HL2 has been
exceptionally burdensome on our developer team due to bugs at every level
of the required tech stack.

We participate in both the Microsoft Mixed Reality Partners program and the
Magic Leap Independent Creators Program, and the difference in developer
experience and platform stability has been stark and dramatic.

Bugs in our application logic are our responsibility, but I appreciate it
when the Windows XR team as a whole takes responsibility for their platform
and does what it takes to get bugs resolved. This involves not putting the
responsibility back on your users to file another ticket.

Regards

*Aaron Moffatt*

CTO, Immersion Analytics (a Virtual Cove, Inc. company)

LinkedIn <https://www.linkedin.com/in/aaron-moffatt-b6a044aa/> |
immersionanalytics.com <http://www.immersionanalytics.com/>



Read our Solution Brief with Intel <https://rebrand.ly/IAandIntel>
