### ISSUE TITLE
Eyetracking shift for close object to wearer

### ISSUE THREAD

**Issue by hgtavakoli** [microsoft/MixedRealityToolkit-Unity#8419]
## Describe the problem

I am working on Hololens2 Eyetracking feature, in our project we are facing the scenario in which a wearer is working in a small workstation in which all the objects are in a small zone. I am facing a problem for close objects to the wearer. (about less than 1 meter). 
## Describe the solution you'd like

I want to know if there is any way to tackle this problem or not?

## Describe alternatives you've considered

I found out that the gaze point is always drifted vertically.

**Comment by Zee2** [comment]
Closing as stale.
