### ISSUE TITLE
Teleport and other controls should match the shell

### ISSUE THREAD

**Issue by jessemcculloch** [Microsoft/MixedRealityToolkit-Unity#843]
Right now the HTK has a teleport script which uses the Xbox Y button for teleport, and the bumpers for rotation.  However, in the recent versions of the Mixed Reality Portal, the navigation uses the left thumb stick forward to teleport, and the right thumbstick to rotate.  

I think it would be best if the default behavior of the HTK matched that of the shell.

Thoughts?

**Comment by Subere23** [comment]
agreed!

**Comment by StephenHodgson** [comment]
Agreed.

**Comment by jessemcculloch** [comment]
@StephenHodgson - You implemented a good chunk (if not all) of the input module, right?  Any thoughts on how best to go about this?

**Comment by StephenHodgson** [comment]
Unsure about the new branch. I haven't looked at it at all yet.

**Comment by jessemcculloch** [comment]
I'm going to mark this an an enhancement, not a bug.

**Comment by jessemcculloch** [comment]
Closed by #964
