### ISSUE TITLE
Inconsistent line endings in 'Packages/com.unity.xr.windowsmr/Runtime/InputSystem/DeviceLayouts.cs'

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#8446]
## Describe the bug

When switching from Legacy XR to the XR SDK in Unity 2019.4.9, a warning about inconsistent line endings is output in the Unity console.

## To reproduce

1. Create a Standalone new project in Unity 2019.4.9f.
2. Import all of the MRTK packages.
3. Open Project Settings and click on XR Plug-in Management. 
4. Install the XR SDK using the install button and click okay to remove the Legacy XR components.
5. Look at the Unity console.

## Expected behavior

Source files in the MRTK should not have inconsistent line endings.

## Screenshots

![lineendingswarning](https://user-images.githubusercontent.com/65038391/91910637-3c410400-ec64-11ea-8a60-7ac981751681.png)

## Your setup (please complete the following information)

- **Unity Version** 2019.4.9f1
- **MRTK Version** 2.5-20200901.2

## Target platform (please complete the following information)

- Standalone

**Comment by davidkline-ms** [comment]
This warning is from a Unity published package. We should forward this feedback.

**Comment by wiwei** [comment]
Closing this one out - this is an issue in a Unity published package. We usually file Unity bugs for this.
