### ISSUE TITLE
Hand tracking with Acer headset?

### ISSUE THREAD

**Issue by zite** [Microsoft/MixedRealityToolkit-Unity#845]
None of the hand tracking / air tap stuff seems to be working with my new Acer MR headset. Is it meant to or is this disabled? I'm running Unity 2017.2.0b5 and trying the scenes in Assets\HoloToolkit-Examples\InteractiveElements\Scenes. Everything else seems to work great.

**Comment by zite** [comment]
I tried on both branches. Tried just putting logs in the OnSourceDetected events and am getting nothing

**Comment by FlorianJa** [comment]
there was a similar question in the holodeveloper slack group yesterday. it was about the hp headset but maybe its the same for the acer one.

![image](https://user-images.githubusercontent.com/3525062/29159640-90cceaec-7daf-11e7-858f-556e6bb43f58.png)

**Comment by jessemcculloch** [comment]
@zite - @FlorianJa is correct, there is no hand tracking at this time on the Immersive Headsets.  See documentation here: https://developer.microsoft.com/en-us/windows/mixed-reality/navigating_the_windows_mixed_reality_home

**Comment by jessemcculloch** [comment]
@zite: Can we close this issue, or would you like it left open for further discussion?

**Comment by zite** [comment]
We can close it. Thanks.
