### ISSUE TITLE
Can I use multi clipping sphere?

### ISSUE THREAD

**Issue by Dsai1006** [microsoft/MixedRealityToolkit-Unity#8450]
I want to clip a object with multi clipping  sphere, so I set multi clipping sphere in editor.
But, one is working well, others is not working.
Is it a bug? 
Please tell me how to use multi clipping sphere.

**Comment by vaoliva** [comment]
Hi @Dsai1006 , could you please give the reproduction steps for replicating your issue?

**Comment by Dsai1006** [comment]
I create a empty, add clipping sphere, apply cylinder to Renderer. It is working well.
Next, I create another empty, add clipping sphere, apply cylinder to Renderer. It doesn't work.
First empty isn't working and second empty is working well. 

![unity_screen](https://user-images.githubusercontent.com/53937999/91978012-6aa30a00-ed5e-11ea-98ce-7472b01df1a8.png)

**Comment by vaoliva** [comment]
@Dsai1006 this is the way the clipping primitive currently works: the MRTK shader has a property for the pixel distance to the clipping primitive boundaries and the pixel is clipped if this distance is over a threshold. This value is set by the clipping primitive, so if you have two clipping primitives referencing the same renderer, this property will be overwritten by one of them. So short answer is at the moment multi clipping is not supported.

**Comment by Dsai1006** [comment]
Sorry, I was able to do after I read https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Rendering/ClippingPrimitive.html
