### ISSUE TITLE
'EditorUserBuildSettings' does not contain a definition for 'wsaGenerateReferenceProjects'

### ISSUE THREAD

**Issue by einstyle** [microsoft/MixedRealityToolkit-Unity#8457]
Hi,

I tried to import HoloToolkit 2017.4 into a new unity project (Unity 2019.1), and I have this error: error CS0117: 'EditorUserBuildSettings' does not contain a definition for 'wsaGenerateReferenceProjects'

Any suggestions to solve this?

**Comment by keveleigh** [comment]
Closing out as fixed in MRTK and HTK won't have 2019 support.
