### ISSUE TITLE
A Native Collection has not been disposed, resulting in a memory leak

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#8460]
## Describe the bug

When using the in-editor player to play any scene after switching to the XR SDK and installing the Oculus XR Plugin, the Unity console reports a memory leak and a few other Errors. No supported devices were connected to the computer. When you remove the Oculus XR package and attempt to load the scene again, you get a slightly different set of errors, but you still get the memory leak error. The Unity console output section has the stack traces for each error as well as a picture showing the Unity console. 

The new scene does not need to have anything in it, other than the MRTK for this issue to occur. The Oculus XR package does not need to be installed for this issue to occur. 
## To reproduce

1. Create a new project or open clone from this repository and open it in Unity.
2. Import all of the MRTK packages.
3. Use the default Unity created scene, or create a new scene and add MRTK to the scene through the drop down menu.
4. Open Project Settings and then go to XR Plug-in Management and install the XR Plug-in Manager.
5. After the XR Plug-in Manager is installed, install the 'Oculus' and 'Windows Mixed Reality' Plug-in Providers.
6. Click the Play button to start the in-editor player.
7. Check the Unity console.

Note: Sometimes you need to load the scene multiple times before this issue occurs.

## Expected behavior

Memory leaks do not occur when playing a new scene in the editor.

## Your setup (please complete the following information)

- **Unity Version** 2019.4.9f1
- **MRTK Version** 2.4 | PR#8386

## Target platform (please complete the following information)

- Standalone

## Unity console output

**Playing a scene:**
![playscene](https://user-images.githubusercontent.com/65038391/92058928-b34dc980-ed44-11ea-98a6-5caf05539e0a.jpg)

**Unable to start Oculus XR Plugin**
> Unable to start Oculus XR Plugin.
0x00007FF7DE63840C (Unity) StackWalker::GetCurrentCallstack
0x00007FF7DE63C3C1 (Unity) StackWalker::ShowCallstack
0x00007FF7DCD187A5 (Unity) GetStacktrace
0x00007FF7DF2B826E (Unity) DebugStringToFile
0x00007FF7DE6977A5 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x00000238BF1E668B (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x00000238BF1E652B (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x00000238BF1E5A4E (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object)
0x00000238BF1E569A (Mono JIT Code) UnityEngine.Debug:LogError (object)
0x00000238BF1E26AB (Mono JIT Code) [OculusLoader.cs:113] Unity.XR.Oculus.OculusLoader:Initialize () 
0x00000238BF1E140B (Mono JIT Code) [XRManagerSettings.cs:169] UnityEngine.XR.Management.XRManagerSettings:InitializeLoaderSync () 
0x00000238BF1E0DCB (Mono JIT Code) [XRGeneralSettings.cs:175] UnityEngine.XR.Management.XRGeneralSettings:InitXRSDK () 
0x00000238BF1E081B (Mono JIT Code) [XRGeneralSettings.cs:148] UnityEngine.XR.Management.XRGeneralSettings:AttemptInitializeXRSDKOnLoad () 
0x0000023911A56025 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007FF8DD10D690 (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FF8DD092912 (mono-2.0-bdwgc) [object.c:2921] do_runtime_invoke 
0x00007FF8DD09B96F (mono-2.0-bdwgc) [object.c:2968] mono_runtime_invoke 
0x00007FF7DE5AAB2E (Unity) scripting_method_invoke
0x00007FF7DE5A486D (Unity) ScriptingInvocation::Invoke
0x00007FF7DE024DAF (Unity) RuntimeInitializeOnLoadManager::ExecuteInitializeOnLoad
0x00007FF7DE02A40B (Unity) RuntimeInitializeOnSceneLoadedBeforeAwake
0x00007FF7DC951052 (Unity) CallbackArray3<int const ,AwakeFromLoadQueue & __ptr64,enum SceneLoadingMode>::Invoke
0x00007FF7DE06947F (Unity) LoadSceneOperation::CompleteAwakeSequence
0x00007FF7DE069803 (Unity) LoadSceneOperation::CompletePreloadManagerLoadSceneEditor
0x00007FF7DE06A4B9 (Unity) LoadSceneOperation::IntegrateMainThread
0x00007FF7DE06DE09 (Unity) PreloadManager::UpdatePreloadingSingleStep
0x00007FF7DE06E65F (Unity) PreloadManager::WaitForAllAsyncOperationsToComplete
0x00007FF7DC956038 (Unity) EditorSceneManager::RestoreSceneBackups
0x00007FF7DC3B7544 (Unity) PlayerLoopController::EnterPlayMode
0x00007FF7DC3C9CB5 (Unity) PlayerLoopController::SetIsPlaying
0x00007FF7DC3CC992 (Unity) Application::TickTimer
0x00007FF7DCD3E1C0 (Unity) MainMessageLoop
0x00007FF7DCD48398 (Unity) WinMain
0x00007FF7DFD56542 (Unity) __scrt_common_main_seh
0x00007FF9503D6FD4 (KERNEL32) BaseThreadInitThunk
0x00007FF951ABCEC1 (ntdll) RtlUserThreadStart 

**Failed to load display subsystem**

> Failed to load display subsystem.
0x00007FF7DE63840C (Unity) StackWalker::GetCurrentCallstack
0x00007FF7DE63C3C1 (Unity) StackWalker::ShowCallstack
0x00007FF7DCD187A5 (Unity) GetStacktrace
0x00007FF7DF2B826E (Unity) DebugStringToFile
0x00007FF7DE6977A5 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x0000023911C22FBB (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x0000023911C22E5B (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x0000023911C2237E (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object)
0x0000023911C21FCA (Mono JIT Code) UnityEngine.Debug:LogError (object)
0x0000023911C0E693 (Mono JIT Code) [OculusLoader.cs:118] Unity.XR.Oculus.OculusLoader:Initialize () 
0x0000023911C1F6EB (Mono JIT Code) [XRManagerSettings.cs:169] UnityEngine.XR.Management.XRManagerSettings:InitializeLoaderSync () 
0x0000023911C1F0AB (Mono JIT Code) [XRGeneralSettings.cs:175] UnityEngine.XR.Management.XRGeneralSettings:InitXRSDK () 
0x0000023911C1EAFB (Mono JIT Code) [XRGeneralSettings.cs:148] UnityEngine.XR.Management.XRGeneralSettings:AttemptInitializeXRSDKOnLoad () 
0x000002390C868925 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007FF8DD10D690 (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FF8DD092912 (mono-2.0-bdwgc) [object.c:2921] do_runtime_invoke 
0x00007FF8DD09B96F (mono-2.0-bdwgc) [object.c:2968] mono_runtime_invoke 
0x00007FF7DE5AAB2E (Unity) scripting_method_invoke
0x00007FF7DE5A486D (Unity) ScriptingInvocation::Invoke
0x00007FF7DE024DAF (Unity) RuntimeInitializeOnLoadManager::ExecuteInitializeOnLoad
0x00007FF7DE02A40B (Unity) RuntimeInitializeOnSceneLoadedBeforeAwake
0x00007FF7DC951052 (Unity) CallbackArray3<int const ,AwakeFromLoadQueue & __ptr64,enum SceneLoadingMode>::Invoke
0x00007FF7DE06947F (Unity) LoadSceneOperation::CompleteAwakeSequence
0x00007FF7DE069803 (Unity) LoadSceneOperation::CompletePreloadManagerLoadSceneEditor
0x00007FF7DE06A4B9 (Unity) LoadSceneOperation::IntegrateMainThread
0x00007FF7DE06DE09 (Unity) PreloadManager::UpdatePreloadingSingleStep
0x00007FF7DE06E65F (Unity) PreloadManager::WaitForAllAsyncOperationsToComplete
0x00007FF7DC956038 (Unity) EditorSceneManager::RestoreSceneBackups
0x00007FF7DC3B7544 (Unity) PlayerLoopController::EnterPlayMode
0x00007FF7DC3C9CB5 (Unity) PlayerLoopController::SetIsPlaying
0x00007FF7DC3CC992 (Unity) Application::TickTimer
0x00007FF7DCD3E1C0 (Unity) MainMessageLoop
0x00007FF7DCD48398 (Unity) WinMain
0x00007FF7DFD56542 (Unity) __scrt_common_main_seh
0x00007FF9503D6FD4 (KERNEL32) BaseThreadInitThunk
0x00007FF951ABCEC1 (ntdll) RtlUserThreadStart 

**Failed to load input subsystem**
> Failed to load input subsystem.
0x00007FF7DE63840C (Unity) StackWalker::GetCurrentCallstack
0x00007FF7DE63C3C1 (Unity) StackWalker::ShowCallstack
0x00007FF7DCD187A5 (Unity) GetStacktrace
0x00007FF7DF2B826E (Unity) DebugStringToFile
0x00007FF7DE6977A5 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x0000023911C22FBB (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x0000023911C22E5B (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x0000023911C2237E (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object)
0x0000023911C21FCA (Mono JIT Code) UnityEngine.Debug:LogError (object)
0x0000023911C0E77B (Mono JIT Code) [OculusLoader.cs:123] Unity.XR.Oculus.OculusLoader:Initialize () 
0x0000023911C1F6EB (Mono JIT Code) [XRManagerSettings.cs:169] UnityEngine.XR.Management.XRManagerSettings:InitializeLoaderSync () 
0x0000023911C1F0AB (Mono JIT Code) [XRGeneralSettings.cs:175] UnityEngine.XR.Management.XRGeneralSettings:InitXRSDK () 
0x0000023911C1EAFB (Mono JIT Code) [XRGeneralSettings.cs:148] UnityEngine.XR.Management.XRGeneralSettings:AttemptInitializeXRSDKOnLoad () 
0x000002390C868925 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007FF8DD10D690 (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FF8DD092912 (mono-2.0-bdwgc) [object.c:2921] do_runtime_invoke 
0x00007FF8DD09B96F (mono-2.0-bdwgc) [object.c:2968] mono_runtime_invoke 
0x00007FF7DE5AAB2E (Unity) scripting_method_invoke
0x00007FF7DE5A486D (Unity) ScriptingInvocation::Invoke
0x00007FF7DE024DAF (Unity) RuntimeInitializeOnLoadManager::ExecuteInitializeOnLoad
0x00007FF7DE02A40B (Unity) RuntimeInitializeOnSceneLoadedBeforeAwake
0x00007FF7DC951052 (Unity) CallbackArray3<int const ,AwakeFromLoadQueue & __ptr64,enum SceneLoadingMode>::Invoke
0x00007FF7DE06947F (Unity) LoadSceneOperation::CompleteAwakeSequence
0x00007FF7DE069803 (Unity) LoadSceneOperation::CompletePreloadManagerLoadSceneEditor
0x00007FF7DE06A4B9 (Unity) LoadSceneOperation::IntegrateMainThread
0x00007FF7DE06DE09 (Unity) PreloadManager::UpdatePreloadingSingleStep
0x00007FF7DE06E65F (Unity) PreloadManager::WaitForAllAsyncOperationsToComplete
0x00007FF7DC956038 (Unity) EditorSceneManager::RestoreSceneBackups
0x00007FF7DC3B7544 (Unity) PlayerLoopController::EnterPlayMode
0x00007FF7DC3C9CB5 (Unity) PlayerLoopController::SetIsPlaying
0x00007FF7DC3CC992 (Unity) Application::TickTimer
0x00007FF7DCD3E1C0 (Unity) MainMessageLoop
0x00007FF7DCD48398 (Unity) WinMain
0x00007FF7DFD56542 (Unity) __scrt_common_main_seh
0x00007FF9503D6FD4 (KERNEL32) BaseThreadInitThunk
0x00007FF951ABCEC1 (ntdll) RtlUserThreadStart

**Removing the Oculus XR package and playing a scene:**
![removeoculusxrpackage](https://user-images.githubusercontent.com/65038391/92058983-d8423c80-ed44-11ea-9e8f-94317b028c57.jpg)

**Error converting build target group names .**
> Error converting build target group names .
Must specify valid information for parsing in the string.
0x00007FF7DE63840C (Unity) StackWalker::GetCurrentCallstack
0x00007FF7DE63C3C1 (Unity) StackWalker::ShowCallstack
0x00007FF7DCD187A5 (Unity) GetStacktrace
0x00007FF7DF2B826E (Unity) DebugStringToFile
0x00007FF7DE6977A5 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x0000023911C22FBB (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x0000023911C22E5B (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x0000023911C2237E (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object)
0x0000023911C21FCA (Mono JIT Code) UnityEngine.Debug:LogError (object)
0x00000239128AA933 (Mono JIT Code) UnityEditor.XR.VRDeviceTransition:EnableVRSettings ()
0x00000239126680F3 (Mono JIT Code) UnityEditor.XR.VRDeviceTransition:HandleVRDeviceTransition ()
0x00000239128AA12B (Mono JIT Code) UnityEditor.XR.VRDeviceTransition:SubsystemReloadCompleted ()
0x00000239128AA01E (Mono JIT Code) UnityEngine.SubsystemManager:Internal_ReloadSubsystemsCompleted ()
0x0000023911AF8405 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007FF8DD10D690 (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FF8DD092912 (mono-2.0-bdwgc) [object.c:2921] do_runtime_invoke 
0x00007FF8DD09B96F (mono-2.0-bdwgc) [object.c:2968] mono_runtime_invoke 
0x00007FF7DE5AAB2E (Unity) scripting_method_invoke
0x00007FF7DE5A486D (Unity) ScriptingInvocation::Invoke
0x00007FF7DE59E855 (Unity) ScriptingInvocation::Invoke<void>
0x00007FF7DB8B0B1B (Unity) Scripting::UnityEngine::SubsystemManagerProxy::Internal_ReloadSubsystemsCompleted
0x00007FF7DBC7E8E5 (Unity) SubsystemManager::DiscoverAllSubsystems
0x00007FF7DBC821C5 (Unity) SubsystemManager::ResolvePackages
0x00007FF7DD122518 (Unity) PackageManager::PackageAssets::RegisterPackages
0x00007FF7DD123320 (Unity) PackageManager::PackageAssets::ResolvePackages
0x00007FF7DD0FD983 (Unity) PackageManager::Project::Refresh
0x00007FF7DBCF6699 (Unity) CallbackArray::Invoke
0x00007FF7DCE95296 (Unity) RefreshInternalV2
0x00007FF7DCE99596 (Unity) StopAssetImportingV2
0x00007FF7DCE97146 (Unity) RefreshV2
0x00007FF7DCDB9801 (Unity) AssetDatabase::Refresh
0x00007FF7DBCF66A1 (Unity) CallbackArray::Invoke
0x00007FF7DC3CC1AE (Unity) Application::TickTimer
0x00007FF7DCD3E1C0 (Unity) MainMessageLoop
0x00007FF7DCD48398 (Unity) WinMain
0x00007FF7DFD56542 (Unity) __scrt_common_main_seh
0x00007FF9503D6FD4 (KERNEL32) BaseThreadInitThunk
0x00007FF951ABCEC1 (ntdll) RtlUserThreadStart

**No XR SDK Provider detected in project**
> No XR SDK Provider detected in project. Re-enabling VR Device settings for Standalone
0x00007FF7DE63840C (Unity) StackWalker::GetCurrentCallstack
0x00007FF7DE63C3C1 (Unity) StackWalker::ShowCallstack
0x00007FF7DCD187A5 (Unity) GetStacktrace
0x00007FF7DF2B826E (Unity) DebugStringToFile
0x00007FF7DE6977A5 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x0000023911C22FBB (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x0000023911C22E5B (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x00000239128ABDAC (Mono JIT Code) UnityEngine.Logger:LogFormat (UnityEngine.LogType,string,object[])
0x00000239128ABBBE (Mono JIT Code) UnityEngine.Debug:LogFormat (string,object[])
0x00000239128AAA9B (Mono JIT Code) UnityEditor.XR.VRDeviceTransition:EnableVRSettings ()
0x00000239126680F3 (Mono JIT Code) UnityEditor.XR.VRDeviceTransition:HandleVRDeviceTransition ()
0x00000239128AA12B (Mono JIT Code) UnityEditor.XR.VRDeviceTransition:SubsystemReloadCompleted ()
0x00000239128AA01E (Mono JIT Code) UnityEngine.SubsystemManager:Internal_ReloadSubsystemsCompleted ()
0x0000023911AF8405 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007FF8DD10D690 (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FF8DD092912 (mono-2.0-bdwgc) [object.c:2921] do_runtime_invoke 
0x00007FF8DD09B96F (mono-2.0-bdwgc) [object.c:2968] mono_runtime_invoke 
0x00007FF7DE5AAB2E (Unity) scripting_method_invoke
0x00007FF7DE5A486D (Unity) ScriptingInvocation::Invoke
0x00007FF7DE59E855 (Unity) ScriptingInvocation::Invoke<void>
0x00007FF7DB8B0B1B (Unity) Scripting::UnityEngine::SubsystemManagerProxy::Internal_ReloadSubsystemsCompleted
0x00007FF7DBC7E8E5 (Unity) SubsystemManager::DiscoverAllSubsystems
0x00007FF7DBC821C5 (Unity) SubsystemManager::ResolvePackages
0x00007FF7DD122518 (Unity) PackageManager::PackageAssets::RegisterPackages
0x00007FF7DD123320 (Unity) PackageManager::PackageAssets::ResolvePackages
0x00007FF7DD0FD983 (Unity) PackageManager::Project::Refresh
0x00007FF7DBCF6699 (Unity) CallbackArray::Invoke
0x00007FF7DCE95296 (Unity) RefreshInternalV2
0x00007FF7DCE99596 (Unity) StopAssetImportingV2
0x00007FF7DCE97146 (Unity) RefreshV2
0x00007FF7DCDB9801 (Unity) AssetDatabase::Refresh
0x00007FF7DBCF66A1 (Unity) CallbackArray::Invoke
0x00007FF7DC3CC1AE (Unity) Application::TickTimer
0x00007FF7DCD3E1C0 (Unity) MainMessageLoop
0x00007FF7DCD48398 (Unity) WinMain
0x00007FF7DFD56542 (Unity) __scrt_common_main_seh
0x00007FF9503D6FD4 (KERNEL32) BaseThreadInitThunk
0x00007FF951ABCEC1 (ntdll) RtlUserThreadStart 

**XR SDK Provider detected in project**
> XR SDK Provider detected in project. Disabling VR Device settings for Standalone
0x00007FF7DE63840C (Unity) StackWalker::GetCurrentCallstack
0x00007FF7DE63C3C1 (Unity) StackWalker::ShowCallstack
0x00007FF7DCD187A5 (Unity) GetStacktrace
0x00007FF7DF2B826E (Unity) DebugStringToFile
0x00007FF7DE6977A5 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x0000023911B7E4FB (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x0000023911B7E35B (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x0000023911B7DC1C (Mono JIT Code) UnityEngine.Logger:LogFormat (UnityEngine.LogType,string,object[])
0x0000023911B7D91E (Mono JIT Code) UnityEngine.Debug:LogFormat (string,object[])
0x0000023911B7C543 (Mono JIT Code) UnityEditor.XR.VRDeviceTransition:DisableVRSettings ()
0x0000023911B79CDB (Mono JIT Code) UnityEditor.XR.VRDeviceTransition:HandleVRDeviceTransition ()
0x0000023911B79B6B (Mono JIT Code) UnityEditor.XR.VRDeviceTransition/AssetCallbacks:OnProjectChanged ()
0x0000023911AC10C7 (Mono JIT Code) (wrapper delegate-invoke) <Module>:invoke_void ()
0x0000023911B776C6 (Mono JIT Code) UnityEditor.EditorApplication:Internal_CallProjectHasChanged ()
0x000002391289DBF5 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007FF8DD10D690 (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FF8DD092912 (mono-2.0-bdwgc) [object.c:2921] do_runtime_invoke 
0x00007FF8DD09B96F (mono-2.0-bdwgc) [object.c:2968] mono_runtime_invoke 
0x00007FF7DE5A1386 (Unity) CallStaticMonoMethod
0x00007FF7DE5A0FC9 (Unity) CallStaticMonoMethod
0x00007FF7DE5A0D51 (Unity) CallStaticMonoMethod
0x00007FF7DC2398F8 (Unity) SceneTracker::ProjectHasChanged
0x00007FF7DCE8E784 (Unity) HotreloadV2
0x00007FF7DCE96F50 (Unity) RefreshInternalV2
0x00007FF7DCE99596 (Unity) StopAssetImportingV2
0x00007FF7DCE97146 (Unity) RefreshV2
0x00007FF7DCDB9801 (Unity) AssetDatabase::Refresh
0x00007FF7DBCF66A1 (Unity) CallbackArray::Invoke
0x00007FF7DC3CC1AE (Unity) Application::TickTimer
0x00007FF7DCD3E1C0 (Unity) MainMessageLoop
0x00007FF7DCD48398 (Unity) WinMain
0x00007FF7DFD56542 (Unity) __scrt_common_main_seh
0x00007FF9503D6FD4 (KERNEL32) BaseThreadInitThunk
0x00007FF951ABCEC1 (ntdll) RtlUserThreadStart

**Comment by RogPodge** [comment]
We seem to only encounter this error specifically when using the Oculus XRSDK plugin for targetting standalone.  Found a thread with several other users encountering difficulty here: https://forum.unity.com/threads/unable-to-start-oculus-xr-plugin.913883/

Our vetted solution, Oculus XRSDK plugin for targetting Android, used for deploying to Quest works perfectly fine.

**Comment by RogPodge** [comment]
![image](https://user-images.githubusercontent.com/39840334/93122652-bc5f6480-f67b-11ea-9ff0-4d97617bedfd.png)
 updating thread with error image that we're including in the release notes

**Comment by wiwei** [comment]
Given this is an Oculus issue AFAIK, closing out the MRTK issue (it's not something we have control over)

**Comment by ahmedaniss25** [comment]
Problem fixed here : https://youtu.be/w6cRuLJQ7E0
