### ISSUE TITLE
Duplicate Service GameObjects Appear in Hierarchy

### ISSUE THREAD

**Issue by deibu** [microsoft/MixedRealityToolkit-Unity#8466]
## Describe the bug

Upon loading a scene, duplicate service GameObjects appear in the hierarchy.

## To reproduce

1. Create a new scene and setup MRTK with "Add to Scene and Configure..."
2. Save and reload the scene
3. Expand the "MixedRealityToolkit" GameObject in the hierarchy
4. See duplicate service GameObjects

## Expected behavior

Have only one GameObject per service.

## Screenshots

![image](https://user-images.githubusercontent.com/2654631/92142195-51cf3e80-edc8-11ea-83e0-6f15395d3d05.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.5f1
- MRTK Version v2.4.0

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

Duplicate service GameObjects disappear upon entering play mode, and stay gone when leaving play mode. However, reloading the scene causes them to come back again.

I also created an empty Project, imported MRTK 2.4.0, and saw it happen when adding MRTK to the SampleScene, saving and reloading the scene.

**Comment by wiwei** [comment]
Yo this is an oldie but goldie. We fixed this in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8335, so this should make the 2.5 release

Basically this was a pretty neat feature, but there are still a decent number of bugs / difficulties in maintaining this in the long run, so turning it down was the way we ended up going

**Comment by deibu** [comment]
Thanks! Didn't find that in my search.
