### ISSUE TITLE
Version 2.4.0 is not on nuget.org

### ISSUE THREAD

**Issue by KuraiAndras** [microsoft/MixedRealityToolkit-Unity#8474]
## Describe the bug

Version 2.4.0 is not on nuget.org. The latest version there is 2.3.0

## To reproduce

1. Go to nuget.org
2. Search for Microsoft.MixedReality.Toolkit

## Expected behavior

Latest package version is 2.4.0

## Screenshots

![image](https://user-images.githubusercontent.com/19240945/92224556-3fc1ce80-eea2-11ea-8f14-7cac9dc79fc4.png)

**Comment by wiwei** [comment]
We've sunset the nuget distribution, so this is expected - we're opting to go with UPM for 2.5 (coming soon!)
