### ISSUE TITLE
Usage of Camera.main throughout the repository

### ISSUE THREAD

**Issue by Zod-** [Microsoft/MixedRealityToolkit-Unity#848]
Using `Camera.main` basically, does a `FindByTag` on the scene and searches through all tagged objects to find the main camera. With more tagged objects the performance gets worse and worse. Instead, the reference should be cached in Awake/Start.
There are a lot of occurrences of `Camera.main` in the repository that doesn't do this and might potentially cause performance issues at some point or at least drain the performance unnecessarily. Some scripts call `Camera.main` up to 8 times on every `Update`.
There are functions that will have to be made obsolete like `MathUtils.IsInFOV(position)` to include the camera reference in the call.

**Comment by StephenHodgson** [comment]
I was not aware this was a `FindByTag` operation. 

Great catch.

**Comment by StephenHodgson** [comment]
The only drawback I just want to consider is if we cache the `Camera.main` we should note that tags can be changed at runtime, like if a camera object is replaced by another, how should we handle this?

**Comment by Zod-** [comment]
My first thought was that a project that changes the main camera often would probably implement their own system to handle this. But then I realized they would have to update the references in every single script, which will probably be quite a challenge to keep track of all of them in the scene and all the different ways they are cached (`GazeTransform`, `TargetTransform`, `mainCamera`, `MainCamera`). Some scripts like `HandDraggable` even have private caches so this wouldn't be entirely possible. 

I'm not sure what the best way would be to handle this. 

If we just keep the references public, add an interface to at-least make this consistent? Some scripts cache the transform and some the camera.

Provide a cache version of the camera through an extension like for example `Camera.cachedMain`?

**Comment by StephenHodgson** [comment]
I like the idea of having a centralized cache in the `GazeManager`. I think replacing all the `Camera.main` calls with `GazeManager.CachedCamera` would do the trick. I think most devs that look into the code could easily see the usage. Documentation would also need to be specific about this.

**Comment by Zod-** [comment]
I don't think the GazeManager would be a good place for it since it would require an instance of the GazeManager and make the utility scripts coupled to it. This should probably be standalone.

**Comment by StephenHodgson** [comment]
Good point, then I agree an extension of the Camera class should do the trick.

**Comment by Zod-** [comment]
I realized extensions need an object of the class. What about something like `CameraCache.main`.
