### ISSUE TITLE
support web XR

### ISSUE THREAD

**Issue by dungnguyen234** [microsoft/MixedRealityToolkit-Unity#8480]
## Describe the problem

now MRTK can work with android ,ios and wearable devices but it still have a bit inconvenient because we need to install the app to device so we really need the web XR feature

## Describe the solution you'd like
i have tried demo  by @Rufus31415 in https://github.com/Rufus31415/Simple-WebXR-Unity - including MRTK integration. It's great if this target officially supported in MRTK

## Additional context

Existing Repo: https://github.com/Rufus31415/Simple-WebXR-Unity
Demo site: https://rufus31415.github.io/sandbox/simple-webxr-mrtk/

**Comment by keveleigh** [comment]
Closing as a duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8472. Thanks for submitting! We'll use the other issue for discussion.
