### ISSUE TITLE
Please LINK to the project for download!

### ISSUE THREAD

**Issue by laultman** [microsoft/MixedRealityToolkit-Unity#8482]
Why can't you link to the project?

## Feature area
The link to the project.

## Existing doc link
missing

**Comment by laultman** [comment]
OH! I assumed the "Improve Documentation" link would actually know which page needed improvement, silly me. In case you can't tell. https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_ExampleHub.html

**Comment by laultman** [comment]
To save you some time finding the link: https://github.com/microsoft/MixedRealityToolkit-Unity/releases/tag/v2.0.0
At the very BOTTOM of the page (how much would it cost to put a link to the assets at the top of the page?)

**Comment by laultman** [comment]
This [page](https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.4.0/README.html) has a link to the **Release Assets**. Notice the page is marked as version 2.4.0. However the link actually goes to version 2.0.0 NOT 2.4.0

**Comment by laultman** [comment]
For the confused (like me) I want to see from the examples how this stuff is supposed to work. The documentation is all over the place. I don't know vocabulary of Unity which the documenters assume the whole world understands. The following statement (aside from being totally incorrect) "Open MRTKExamplesHub.unity which is located at MRTK/Examples/Experimental/Demos/ExamplesHub/Scenes/" doesn't make any sense. How do you "Open" this?
First the location is just flat WRONG. You find this out after you have gone through the long process of setting up a completely new project, adjusted it in Unity for UWP, XR, and other stuff, imported MRTK, MRTK Extensions, and the [highly elusive examples](https://github.com/microsoft/MixedRealityToolkit-Unity/releases/download/v2.4.0/Microsoft.MixedReality.Toolkit.Unity.Examples.2.4.0.unitypackage) project never mentioned in the [Examples Hub](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_ExampleHub.html) documentation. With enough persistence/desperation you will find the Examples Hub scene here: Assets/MRTK/Examples/Experimental/ExamplesHub/Scenes and the scene name is MRTKExamplesHub. DRAG the scene into the Unity Hierarchy pane to "Open". Now maybe you can start following the rest of the instructions. Tune in for more.

**Comment by wiwei** [comment]
Resolving this after @keveleigh 's cherry pick to 2.5. This should get fixed as well in the latest once we release it.
