### ISSUE TITLE
Input Playback Service is missing in RecordArticulatedHandPoseInputSystemProfile

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#8499]
## Describe the bug

The RecordArticulatedHandPoseInputSystemProfile used by the HandInteractionRecordArticulatedHandPose scene does not include the Input Playback Service, which causes errors when one tries to record/playback input.

## To reproduce

1. Go to the HandInteractionRecordArticulatedHandPose scene
2. Open the input simulation window from Mixed Reality Toolkit > Utilities > Input Simulation
3. Run the scene in editor play mode
4. Bring up a simulated hand by pressing t
5. Start recording
6. Move the hand around by holding left shift
7. End recording
8. See error

## Expected behavior

Error should not appear.

## Your setup (please complete the following information)
Unity 2019.4.8f1
MRTK v2.4

**Comment by davidkline-ms** [comment]
fixed in the forthcoming 2.5.0 release
