### ISSUE TITLE
How to share custom SyncObject via SharedStage?

### ISSUE THREAD

**Issue by GAnatoliy** [Microsoft/MixedRealityToolkit-Unity#850]
Hi,

I am trying to use Sharing in my project.
I would like to share some data without transformation (I don't need to create it on scene in some place).

Now SyncRoot contains list of SyncSpawnedObject that as far as I understand is created specially for objects that placed on the scene (it has transformation, rotatation, etc).

According to the documentation I can create own SyncRoot implementation with another SyncArray.

> By default, the SyncRoot object (which inherits from SyncObject) only contains an array of InstantiatedPrefabs, which may not be enough for your application.

But how can I use new sync model with SharedStage? I noticed that it creates SyncRoot directly in Connect method, so I can't create my own sync model.

> Root = new SyncRoot(Manager.GetRootSyncObject());

Probably I missed something, how can I share data via SharedStage?

Thanks for help.

**Comment by robinkruyt** [comment]
I agree with @GAnatoliy. It is unclear how to add your own fields to the SyncRoot but the documentation states you can. Any news on this? Why was the issue closed without an answer?
