### ISSUE TITLE
Description panel's title text wrapping issue

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#8502]
## Describe the bug
The description panel's title text sometimes overflows and covers the content text area. 
(Reported by Max Wang)

![MicrosoftTeams-image](https://user-images.githubusercontent.com/13754172/92601121-68552880-f2e7-11ea-8f68-a780ef5dec08.png)

**Comment by keveleigh** [comment]
Fixed via #8503
