### ISSUE TITLE
Allow TouchableCollider in Near Interaction Touchable Volume to be set 

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#8506]
## Describe the problem

The `TouchableCollider` property is currently read only and is set to the game object's collider.  

Add the ability to set this property.

**Comment by julenka** [comment]
Hi @CDiaz-MS, FYI. There actually is a reason why this particular property cannot be changed -- currently, the PokePointer figures out which touchable it's closest to by performing a collision test, and for each collider intersected that has a touchable on it, computing the distance to that touchable. See in particular [lines 208 - 233 of PokePointer.cs.](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MRTK/Services/InputSystem/NearInteractionTouchableVolume.cs)

**Comment by julenka** [comment]
Closing in favor of #8507 which I belive should solve the customer request, but will not require a large change to the underlying touch dispatch architecture.
