### ISSUE TITLE
NearInteraction TouchableVolume cannot be instantiated at runtime

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#8507]
## Describe the bug

It is not possible to instantiate an object at runtime, add both a collider and a NearInteractionTouchableVolume to it such that the object then responds to touch interactions.

## To reproduce

TODO: create sample code to reproduce the issue

## Expected behavior

Running the code above should generate a cube that responds to touch events.

**Comment by afarchy** [comment]
Here's some sample code:

```
var touchable = gameObject.AddComponent<NearInteractionTouchableVolume>();
touchable.EventsToReceive = TouchableEventType.Touch;
touchable.TouchableCollider = GetComponent<Collider>();    // <-- Doesn't compile
```

**Comment by polar-kev** [comment]
Closing as a duplicate of #9143 which has more detail. Still aiming for the 2.6 milestone.
