### ISSUE TITLE
HTK Build Window not compatible with Immersive Headset build and deploy

### ISSUE THREAD

**Issue by jessemcculloch** [Microsoft/MixedRealityToolkit-Unity#851]
Right now the Build Window is specifically targeted at building out to either the emulator or to IpOverUsb and deploying to device.  It is not capable of deploying to local machine like is needed for the immersive headsets.

**Comment by StephenHodgson** [comment]
@jessemcculloch, is this for the 2017.1 or 2017.2 branches? Or both?

**Comment by jessemcculloch** [comment]
Probably both, but I think it only needs to be fixed for the 2017.2 branch since that is where the immersive headsets are supported

**Comment by StephenHodgson** [comment]
Using the built in `Build and Run` should suffice for this. Not really sure if that needs to be added to the Build Window.
