### ISSUE TITLE
Having too long of a path can cause 'file not found' for example scenes (MAX_PATH)

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#8511]
## Describe the issue
When you import the UPM packages into a project that has a long path (i.e. D:\unity\upmbugbash\packagemanagerrepro), the Unity console will generate a 'file not found' exception similar to the one pictured below.

![bf4381b6-7d62-4c4a-9fa9-ce547d52ed92](https://user-images.githubusercontent.com/65038391/92642853-afb2c900-f295-11ea-9ffd-d53ca337cc39.jpg)

## Feature area
MAX_PATH

## Additional context
This issue should be included on the Release notes.

**Comment by wiwei** [comment]
Adding release blocker tag so that we get this doc-ed for known issues - there's unfortunately only so much we can do to fix MAX_PATH issues, but people should know how to identify it.

**Comment by davidkline-ms** [comment]
fixed with #8658
