### ISSUE TITLE
MRTK Project Configurator does not give the user buttons to continue when switching to UWP from Standalone

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#8515]
## Describe the bug

MRTK Project Configurator does not give the user buttons to continue when switching to UWP from Standalone. This happens only when the Assets\MRTK\Examples\Demos\EyeTracking\Scenes\EyeTrackingDemo-00-RootScene.unity is opened in Standalone with the MS HRTF audio spatializer selected, and then switching to UWP.

## To reproduce

1. Clone the prerelease/2.5.0_stabilization from commit 84ac47a67
2. Open the fresh clone in Unity 2019.4.9f1 on the Standalone platform
3. Import TMP Essentials and then open Assets\MRTK\Examples\Demos\EyeTracking\Scenes\EyeTrackingDemo-00-RootScene.unity
4. Open the Build Settings, click on UWP, and change the Minimum Platform Version to 10.0.18362.0
5. Click the Switch Build button
6. Observe the MRTK Project Configurator

## Expected behavior

The MRTK Project Configurator gives the user an option to continue through the configuration process.

## Screenshots

![Annotation 2020-09-09 143937](https://user-images.githubusercontent.com/65038391/92660980-6459e400-f2b0-11ea-852a-08723fad4e2f.png)

## Your setup (please complete the following information)

**- Unity Version** 2019.4.9f1
**- MRTK Version** 84ac47a67

## Target platform (please complete the following information)

**- UWP**
**-Standalone**

**Comment by wiwei** [comment]
@elbuhofantasma is the user in a permanently hosed state, or can they just X out and move on with their lives here?

**Comment by polar-kev** [comment]
I believe this is now fixed. @elbuhofantasma, can you confirm?

**Comment by keveleigh** [comment]
Closing as likely fixed. I haven't seen this in my recent tests.
