### ISSUE TITLE
InteractableToggleCollection Touch input sometimes ignored

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#8517]
## Describe the bug

Far interaction input for the InteractableToggleCollection is reliable but near interaction input is sometimes ignored when the toggle is pressed more than once.

![ToggleCollectionBug](https://user-images.githubusercontent.com/53493796/92662720-49896e80-f2b4-11ea-8690-137fb51ab483.gif)

## To reproduce

1. Add the RadialSet prefab to your scene
2. Press each toggle once via near interaction 
3. Try to press the toggles again and they are sometimes unresponsive

**Comment by keveleigh** [comment]
Fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8533
