### ISSUE TITLE
Object Manipulator - Smoothing Near is off by default

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#8523]
## Describe the bug
In ManipulationHandler, Smoothing was on by default.
In Object Manipulator - **Smoothing Far** is on but **Smoothing Near** is off by default. Different default behavior affects all existing example scenes and creates confusion. - Why far interaction is smooth while near interaction is jittery?
![2020-09-10 11_53_11-Unity 2018 4 26f1 Personal -  PREVIEW PACKAGES IN USE  - HandInteractionExamples](https://user-images.githubusercontent.com/13754172/92676546-be17e800-f35c-11ea-80e0-4776982bcc9a.png)
## To reproduce
Open HandInteractionExamples scene.
Directly grab and move any objects - coffee cup, cheese, etc...
Grab and move with hand ray.

## Expected behavior
Both near and far interaction shows smooth behavior.

![2020-09-10 11_52_32-Unity 2018 4 26f1 Personal -  PREVIEW PACKAGES IN USE  - HandInteractionExamples](https://user-images.githubusercontent.com/13754172/92676543-bce6bb00-f35c-11ea-8d7f-58f9bc644536.png)

![2020-09-10 11_52_39-Unity 2018 4 26f1 Personal -  PREVIEW PACKAGES IN USE  - HandInteractionExamples](https://user-images.githubusercontent.com/13754172/92676549-beb07e80-f35c-11ea-8835-437971bc25f2.png)

**Comment by thalbern** [comment]
happened in this PR https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8204 from Jared. You are right @cre8ivepark this should be default enabled to have the same behavior. I'm gonna change it!

**Comment by thalbern** [comment]
should be addressed by linked PR
