### ISSUE TITLE
Azure Spatial Anchors crashing with Unity XR

### ISSUE THREAD

**Issue by Aupuma** [microsoft/MixedRealityToolkit-Unity#8538]
## Describe the bug

When trying to create an Azure Spatial Anchor through https://docs.microsoft.com/es-es/windows/mixed-reality/mr-learning-asa-02, the app crashes to UnityEngine.XR.WSA.WorldAnchor::GetNativeSpatialAnchorPtr() inside UnityEngine.VRModule.cpp

## To reproduce

1. Create the basic demo scene following the tutorial from the web
2. Switch to the new XR Plug-in system
3.  Use a XRSDKConfiguration profile
4. Press Start Azure Session
5. Press Create Azure Anchor

## Expected behavior

It should create a spatial anchor where the cube is placed

## Your setup (please complete the following information)

- Unity 2019.4.4f1
- MRTK Version 2.4.0

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
Looks like this is tracked on the ASA sample repo at https://github.com/Azure/azure-spatial-anchors-samples/issues/212. Going to close this one down in favor of that, as this isn't MRTK related.

**Comment by israaz** [comment]
Hello, I have the same issue!!
