### ISSUE TITLE
HL2 MRTK SlateUGUI Content not Constrained to Slate

### ISSUE THREAD

**Issue by laultman** [microsoft/MixedRealityToolkit-Unity#8539]
## Describe the bug

The MRTK SlateUGUI prefab renders correctly in the Unity Player with all fields working as expected and the page scrolls as expected with text or controls confined to the view port area. On HL2 the text and controls are not confined to the view port and are in view at all times. However any control visible outside the view port is "inactive" to input. Also scrolling input actions only are detected while in the view port, even though text and controls are visible outside the view port they are not responsive as if hidden.

## To reproduce

Use the MRTK Example Hub and select the Hand Interaction example. Observe the UI Examples.

## Expected behavior

I would expect the TextMesh Pro and Unity controls to be visible only in the view port area and that input would only be possible in the view port.

## Screenshots
Content in Unity Player is constrained to the view port.
![PlayerView](https://user-images.githubusercontent.com/20271666/93072277-2ad9fd80-f64f-11ea-8846-7d1184daaa9a.png)

Content in HL2 is visible at all times outside the view port.
![HL2-Slate](https://user-images.githubusercontent.com/20271666/93072291-32010b80-f64f-11ea-9339-fc44a13bd8c3.png)
The button controls above the view port are inactive as is scroll input outside the view port (as expected). Input only occurs inside the view port as it should.

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.10f1]
- MRTK Version [e.g. v2.4.0]

## Target platform (please complete the following information)
- HoloLens 2

**Comment by keveleigh** [comment]
This sounds like https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6747, which is caused when the depth buffer submission is set to 16-bit. It's a side effect of the way Unity sets up stencil buffers. We have some references on it [here](https://docs.microsoft.com/en-us/windows/mixed-reality/performance-recommendations-for-unity#optimize-depth-buffer-sharing), [here](https://docs.unity3d.com/ScriptReference/RenderTexture-depth.html), and [here](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Performance/PerfGettingStarted.html#depth-buffer-sharing-hololens).

If you'd like to use this component, please change the depth buffer format to 24-bit in the Player settings:
![image](https://user-images.githubusercontent.com/3580640/93157860-e5a1e400-f6bf-11ea-8c87-c4d2ae1e70a3.png)

**Comment by polar-kev** [comment]
Closing this issue as a duplicate.
