### ISSUE TITLE
Allow HandInteraction with objects focused by EyeGaze

### ISSUE THREAD

**Issue by Mikkelsv** [microsoft/MixedRealityToolkit-Unity#8541]
## Describe the problem

In MRTK 2.2, one was allowed to enable manipulation of objects focused by Eye Gaze, e.g. "grabbing" objects that one is gazing at by pinching and moving the hand at a distance.
This was done by disabling the FarPointer (`ShellHandRayPointer`) through PointerPreferences, and implementing a mix of both `IMixedRealityFocusHandler` and `IMixedRealityInputHandler`.
This "feature" is, however, removed in the later update [to be more consistent with the shell.](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6320)

## Describe the solution you'd like

I would like to see this type of flexibility using the EyeGaze being returned to MRTK. 
The preferred solution would be to extend the EyeGaze pointer options to allow it to be used alongside hands as long as the hands are not interacting with anything, such as described [here](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5920).

## Describe alternatives you've considered

An alternative workaround to this is always enabling the GazePointer, manually track if the hands are interacting with anything 
, and in turn, enabling/disabling the GazePointer at the appropriate situations.

## Additional context
We have used this feature in our work to allow the user to interact with out-of-reach objects with only the use of eye gaze and gestures. This allowed us to shy away from the tedious process of having to carefully point at the intended object and the strain to your arms when having them raised to interact with certain objects.

**Comment by Zee2** [comment]
This is a first-class interaction method in MRTK3! Check it out and let us know what you think. If adding support for this in MRTK2 is a critical priority, we'd be happy to merge a PR.
