### ISSUE TITLE
MRTK Examples UPM Packages does not include Sample Scenes

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#8544]
## Describe the bug

The example scenes are the most valuable assets in the MRTK examples packges, yet they don't seem to exist in the UPM packages.

Actual folders available in the MRTK examples package:
![image](https://user-images.githubusercontent.com/168492/93127559-fc761580-f682-11ea-83a7-3177ec03620b.png)

Folders I expect to see (these are available when you import the .unitypackage):
![image](https://user-images.githubusercontent.com/168492/93128307-1f54f980-f684-11ea-9061-df5dc77be61d.png)

## To reproduce

1. Add the following package dependencies in Packages\manifest.json:

```
    "com.microsoft.mixedreality.toolkit.examples": "2.5.0-preview.20200910.3",
    "com.microsoft.mixedreality.toolkit.foundation": "2.5.0-preview.20200910.3",
```
2. After packages have imported, try to open the HandInteractionExamples scene, that should exist under the MRTK examples folder under packages.
3. Observe that the HandInteractionExamples scene does not exist

## Expected behavior

I would expect that the example scenes are published as part of the MRTK examples UPM package.

## Screenshots
See above.

## Your setup (please complete the following information)

- Unity Version 2019.4.10f1
- MRTK Version 2.5 UPM 2.5.0-preview.20200910.3

## Target platform (please complete the following information)
This was tested in Unity Editor, on Mac.

**Comment by keveleigh** [comment]
When examples are imported via UPM, we've hooked into [Unity's samples feature](https://forum.unity.com/threads/samples-in-packages-manual-setup.623080/). There's an additional step to import specific examples in the UPM UI:

![image](https://user-images.githubusercontent.com/3580640/93130027-c175e100-f686-11ea-8e01-2c484818349c.png)

I'm not sure this is documented though. @davidkline-ms leaving this as a release blocker to track adding UPM-specific docs for examples.

**Comment by julenka** [comment]
Looks like documentation exists for this extra step: https://microsoft.github.io/MixedRealityToolkit-Unity/version/prerelease/2.5.0_stabilization/Documentation/usingupm.html#using-mixed-reality-toolkit-examples

**Comment by Meruja** [comment]
The correct documentation link can be found here:
[https://docs.microsoft.com/en-gb/windows/mixed-reality/mrtk-unity/running-example-scenes?view=mrtkunity-2021-05](https://docs.microsoft.com/en-gb/windows/mixed-reality/mrtk-unity/running-example-scenes?view=mrtkunity-2021-05
)

**Comment by GLARKI** [comment]
Thanks ya all!
