### ISSUE TITLE
How to appear cursor object

### ISSUE THREAD

**Issue by stwktw** [Microsoft/MixedRealityToolkit-Unity#855]
Hi

I use holotoolkit in my unity hololens project.

But my cursor object do not appear at my gaze position.

I use prefab inputmanager, hololenscmera, cursorwithfeedback.

**Comment by jessemcculloch** [comment]
@stwktw - We need much more information to help with this.  It might be better addressed in the forums.

If you prefer to keep the conversation here, please let us know what version of Unity, what version of the HoloToolkit-Unity you are using, if you are getting any errors, and exactly what behavior you are seeing.  Screenshots would be supremely helpful, of the inspectors for each of the items you mention above, as well as of your project hierarchy.

**Comment by stwktw** [comment]
hm

i using holotoolkit in my project.
But i have question.
Look at the next screen capture.

ex _ 1) 
prefab - InputManager, HoloLensCamera, **BasicCursor**.
issue - I can't see basicCursor. 
<img width="795" alt="screen shot 2017-08-16 at 11 04 03 am" src="https://user-images.githubusercontent.com/5934412/29344573-bdce0972-8273-11e7-8419-9d036766103d.png">

ex _ 2)
prefab - InputManager, HoloLensCamera, **Cursor**.
I can see Cursor, in center, as camera position.
<img width="795" alt="screen shot 2017-08-16 at 11 04 33 am" src="https://user-images.githubusercontent.com/5934412/29344620-11a1dc7c-8274-11e7-87d4-6f6179b76c4b.png">

ex _ 3)
prefab - InputManager, HoloLensCamera, **CursorWithFeedback**.
issue - I can't see normal cursor. but i can see hand feedback to click gesture.
<img width="795" alt="screen shot 2017-08-16 at 11 05 11 am" src="https://user-images.githubusercontent.com/5934412/29344653-5079aeb6-8274-11e7-8d1c-e5cd5a68dc7b.png">
<img width="793" alt="screen shot 2017-08-16 at 11 05 22 am" src="https://user-images.githubusercontent.com/5934412/29344664-6c606660-8274-11e7-8d59-fd1562c622e8.png">

ex _ 4)
prefab - InputManager, HoloLensCamera, **DefaultCursor**.
<img width="794" alt="screen shot 2017-08-16 at 11 06 02 am" src="https://user-images.githubusercontent.com/5934412/29344706-a9814d5c-8274-11e7-92e3-09ac06d13c05.png">

ex _ 5) HoloToolKit ColorPicker
I can see ColorPicker scene 's BasicCursor. 
<img width="794" alt="screen shot 2017-08-16 at 11 20 38 am" src="https://user-images.githubusercontent.com/5934412/29344760-16cdfc98-8275-11e7-9811-1bf6462ff4fe.png">


Why in my project can't see cursor?
HoloToolKit ColorPicker project is good cursor.

To test the cursors, i dragged the prefabs and added them to Scene.
Do I have more to do? I don't know.

Env
Unity - 5.6.2f1
OS - Windows 10
Device - HoloLens 
Screen Capture Device - Unity game play screen

**Comment by stwktw** [comment]
HI .

I find solution. I mistake.
my object don't have collider component.

I add collider for my object. then my cursor is papered.

Thankyou.
