### ISSUE TITLE
Bounding box in HandInteractionExamples shows warnings about negative scale or size.

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#8550]
## Describe the bug

SceneContent/BoundingBoxExample/HoloLens1 Style/Platonic in the HandInteractionExamples scene causes 7 warnings when the scene is played. The warnings look like the following:

BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "SceneContent/BoundingBoxExample/HoloLens1 Style/Platonic/rigRoot/corner_[X]/visualsScale/visuals"

[X] ranges from 0 to 6.

This issue looks identical to #6582.

## To reproduce

1. Open HandInteractionExamples.unity
2. Press play
3. See warnings

## Your setup

- Unity Version 2019.4.8f1
- Latest MRTK UPM package

**Comment by keveleigh** [comment]
Fixed via #8561
