### ISSUE TITLE
Migration window tooling for migrate all

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#8552]
I was doing the migration from 2.4 -> 2.5 (see https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8551) and found that following the migration tool instructions basically involves running each of the migration tooling's handlers one after the other. As this grows in the future, this becomes kinda onerous for users.

Would be nice to have a "migrate everything/run all handlers" option -> do migration

It's possible this might not scale to show everything in that page (so maybe we'd show some small number of them)

**Comment by Zee2** [comment]
Closing as stale.
