### ISSUE TITLE
Go to component button on Object Manipulator not working

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#8554]
## Describe the bug

The "Go to component" button under the constraints section of the Object Manipulator on many GameObjects (e.g. all in the bounding box section and all but the earth in the manipulation interaction section) in the HandInteractionExamples scene is not working. When pressed, the following warning appear in the console:

Item Min Max Scale Constraint (Script) not found in window Inspector.
UnityEditor.Highlighter:Highlight(String, String)
Microsoft.MixedReality.Toolkit.Utilities.Editor.InspectorUIUtility:DrawComponentTypeFoldout(GameObject, Boolean, String) (at Assets/MRTK/Core/Inspectors/Utilities/InspectorUIUtility.cs:742)
Microsoft.MixedReality.Toolkit.Editor.ObjectManipulatorInspector:OnInspectorGUI() (at Assets/MRTK/SDK/Editor/Inspectors/UX/ObjectManipulator/ObjectManipulatorInspector.cs:133)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

It seems that all GameObjects with the Object Manipulator attached and at least one constraint set there are affected.

## To reproduce

1. Open HandInteractionExamples.unity
2. Press play
3. Try clicking any GameObject mentioned above
4. Go to inspector
5. Click on the "Go to component" button under the constraints section of the Object Manipulator
6. See error

## Expected behavior

The button should work.

## Your setup

- Unity Version 2019.4.8f1
- Latest MRTK UPM package

**Comment by MaxWang-MS** [comment]
Cannot repro with Unity 2018.4.26f1, so it seems to be a Unity bug.

**Comment by wiwei** [comment]
Doesn't seem to be specific to UPM, can also repro this in .unitypackages

**Comment by wiwei** [comment]
Also can confirm, even using Highlighter.Highlight on some basic things that should work (i.e. Hierarchy -> GameObject) doesn't work, so there's probably a regression here in 2019 Unity.

Removing from 2.5 milestone, we can file a bug on Unity for this one.

**Comment by AMollis** [comment]
@marlenaklein-msft can you please check if this is still reproducible?  If it is, please fix

**Comment by marlenaklein-msft** [comment]
Tested the MRTK3 HandInteractionExamples.unity scene with Unity 2020.3.44 to see if this repros for MRTK3. Pressing the 'Go to component' button under the constraints section of Object Manipulator highlights the component id under Constraint Manager, but pressing the 'Go to component' button under Constraint Manager produces a similar "Item Min Max Scale Constraint (Script) not found in window Inspector" error.

**Comment by marlenaklein-msft** [comment]
Bugs with highlight [not disappearing](https://issuetracker.unity3d.com/issues/highlighter-dot-highlight-does-not-disappear-when-the-highlighted-element-disappears-from-view) and [not scrolling to the right place](https://issuetracker.unity3d.com/issues/highlighter-dot-highlight-does-not-disappear-when-the-highlighted-element-disappears-from-view) in some versions of Unity.

**Comment by marlenaklein-msft** [comment]
Fixed with PR #11497
