### ISSUE TITLE
Warning in HandInteractionExample scene: BoxColliders does not support negative scale or size

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#8560]
## Describe the bug
"A 'BoxColliders does not support negative scale or size' warning is issued when playing the scene with the in-editor player. There are 7 warnings generated when the scene is started for "SceneContent/BoundingBoxExample/HoloLens1 Style/Platonic/rigRoot/corner_0/visualsScale/visuals" with the '../corner_0/..' incrementing by one up to '../corner_7/..' in the Unity console. You are still able to interact with the scene as expected."

Warning was discovered in the bounds control migration PR https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8508 

## To reproduce

Open Hand Interaction scene and observe platonic hololens 1 gameobject emiting warning once at the start of the scene.

## Expected behavior

example scenes shouldn't emit any warnings.

**Comment by vaoliva** [comment]
Is this the same as #8550 ?

**Comment by thalbern** [comment]
yes! i didn't see that one. Thank you @vaoliva :)

**Comment by thalbern** [comment]
closing as duplicate
