### ISSUE TITLE
Add -development flag to StartCommandLineBuild

### ISSUE THREAD

**Issue by FreakTheMighty** [microsoft/MixedRealityToolkit-Unity#8562]
## Describe the problem

We use `StartCommandLineBuild` for automated builds on our server. We like to have non-release builds to run with the `development` mode flag on so that we can rely on pre-processors for a few switches. I doesn't look like there is an argument that can be passed in to set this build option.

## Describe the solution you'd like

I'd like to add a `-development` flag to the build command.

## Describe alternatives you've considered

I've looked into what sort of per-processors are available that might differentiate between `release` and `master` builds. We've used search & replace tasks in our automated builds for some switches that we'd like between the two types of builds.

**Comment by wiwei** [comment]
@FreakTheMighty if you have a change that you have in mind, I'd be happy to review it. This sounds like a good flag to have, though we're probably a little bit aways from tackling this right now (i.e. stabilizing 2.5 at the moment)

Also the reason I say this is I *think* I know that the request is here but I could also be misinterpreting things (i.e. UWP appx generation of Release/Debug/Master vs Standalone, etc)

**Comment by FreakTheMighty** [comment]
@wiwei we've found that is pretty easy to create our own build command that calls through to the MRTK build command. I think that's a pretty reasonable solution. While `-development` seems like something generally useful I can see adding all the build options to the cli might be an uphill battle.

In short, I'm going to close this.
