### ISSUE TITLE
Input simulation key info overlay improvement

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#8564]
## Describe the bug
Input simulation key info has been occupying too much screen space on regular DPI monitors and smaller window sizes.

## To reproduce
Open HandInteractionExample scene.
Press CTRL+H key to bring up key info

![2020-09-15 08_46_34-Unity 2018 4 26f1 Personal -  PREVIEW PACKAGES IN USE  - HandInteractionExamples](https://user-images.githubusercontent.com/13754172/93231615-e451e380-f7b3-11ea-84c2-3caeba5791b3.png)

**Comment by keveleigh** [comment]
Fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8565
