### ISSUE TITLE
"Failed to Create Boundary Bounds" Warning when playing in editor using default MRTK Profile

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#8568]
## Describe the bug

See title.

## To reproduce

1. Create a new Scene
2. MRTK -> Add to scene and configure
3. Hit play
4. See warnings:

```
MRTK was unable to set Tracking Space to RoomScaleUnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.Boundary.MixedRealityBoundarySystem:SetTrackingSpace() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.0-preview.20200910.3/Services/BoundarySystem/XR2018/MixedRealityBoundarySystem.cs:98)
Microsoft.MixedReality.Toolkit.Boundary.BaseBoundarySystem:Initialize() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.0-preview.20200910.3/Core/Services/BaseBoundarySystem.cs:67)
```

and

```
Failed to calculate boundary bounds.
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.Boundary.BaseBoundarySystem:CalculateBoundaryBounds() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.0-preview.20200910.3/Core/Services/BaseBoundarySystem.cs:929)
Microsoft.MixedReality.Toolkit.Boundary.BaseBoundarySystem:Initialize() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.5.0-preview.20200910.3/Core/Services/BaseBoundarySystem.cs
```
## Expected behavior

No warnings when playing an empty scene with default MRTK profile

## Your setup (please complete the following information)

- Unity Version 2019.4.10f1
- MRTK Version 2.5

## Target platform (please complete the following information)
Tested in editor on Mac, with following player config, but should repro on windows, with other vr configs as well:

![image](https://user-images.githubusercontent.com/168492/93249838-bf735700-f746-11ea-8bd4-4d1cf1291e84.png)

**Comment by wiwei** [comment]
Agree with the 2.5 marker because this is a regression from 2.4 and is an obvious warning in a core pathway that shouldn't have warnings.

**Comment by keveleigh** [comment]
Looks like a regression from https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8255. Previously, `base.Initialize();` wasn't called if no XR device was present. It's now called always, to ensure the profile is read.

**Comment by MaxWang-MS** [comment]
@keveleigh I noticed that in `MixedRealityBoundarySystem` the XR device presence test in placed after `base.Initialize();` but in `XRSDKBoundarySystem` the test is placed before. I am wondering if the difference is intended.

**Comment by keveleigh** [comment]
>I am wondering if the difference is intended.

It wasn't originally (they were aligned in the original commit), but #8255 changed the behavior for `MixedRealityBoundarySystem`.
