### ISSUE TITLE
ApplicationViewManager.cs throws error when building VS solution

### ISSUE THREAD

**Issue by Gentatsu** [Microsoft/MixedRealityToolkit-Unity#857]
After you build the initial solution from unity, the VS solution produced fails when building because of ApplicationViewManager.cs. 

I delete the file to get it to build, but it seems consistent across every project.

**Comment by jessemcculloch** [comment]
Hello @Gentatsu - Thanks for the report.  Can you please include more details, including what errors you are seeing, what configurations you are using, screenshots, etc.  This in not behavior I see in my projects, so I am not sure how I could reproduce it right now.  Any additional information you might be able to provide would be great.

**Comment by b8566679** [comment]
I have the same error:

var dispt = newView.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
            {
                //This happens when User switch view back to Main App manually
                void CoreWindow_VisibilityChanged(CoreWindow sender, VisibilityChangedEventArgs args)
                {
                    if (args.Visible == false)
                    {
                        CallbackReturnValue(null);
                    }
                }
                newView.CoreWindow.VisibilityChanged += CoreWindow_VisibilityChanged;
                Frame frame = new Frame();
                var pageType = Type.GetType(Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName.Replace(".App,", $".{xamlPageName},"));
                var appv = ApplicationView.GetForCurrentView();
                newViewId = appv.Id;
                var cb = new Action<object>(rval =>
                {
                    returnValue = rval;
                    isCompleted = true;
                });
                frame.Navigate(pageType,pageNavigateParameter);
                CallbackDictionary[newViewId] = cb;
                Window.Current.Content = frame;
                Window.Current.Activate();
            }).AsTask();

**Comment by Gentatsu** [comment]
Sorry, I didn't save what the errors were! It happens when I create a fresh project, import the latest HoloToolKit, and build the VS solution. If I delete that, then build again, it's fine.

**Comment by StephenHodgson** [comment]
@Gentatsu what are your build and player settings?  Are you targeting WSA, and building for XAML correctly?

**Comment by StephenHodgson** [comment]
I'm still unable to duplicate this.

**Comment by Gentatsu** [comment]
Sorry for the late reply. I'm not entirely too sure if I'm targeting it directly. I'm using the standard build settings for Hololens, and then building the subsequent VS solution produced. I'm using DotNet.

It also seems to have been fixed on my end since upgrading to Unity 2017.1.1f and the MRTK release equivalent.

**Comment by StephenHodgson** [comment]
Thanks for the update.
