### ISSUE TITLE
[HandInteractionPanZoom] Asymmetric pan settings and dynamic configurations are needed

### ISSUE THREAD

**Issue by tarukosu** [microsoft/MixedRealityToolkit-Unity#8571]
## Describe the problem

I tried to use the HandInteractionPanZoom.cs script to dynamically display the document, but it was missing the following features.

### Asymmetric pan settings
I need `minPanHorizontal` to control minimum value.  
The same is true for `minPanVertical`.

### Change settings via code
I want to change `maxPanHorizontal` and `maxPanVertical` via code.  
It would be nice if I could change other settings as well.

### Create property to change settings like this

```cs
[SerializeField]
[Range(1.0f, 20.0f)]
private float maxPanHorizontal = 2;
public float MaxPanHorizontal
{
    set
    {
        maxPanHorizontal = value;
    }
    get
    {
        return maxPanHorizontal;
    }
}
```

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/1c9e05f3ba65b5c52d191b9b1d204dde41f866f8/Assets/MRTK/SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs#L64-L66

### Use minPanHorizontal instead of minus maxPanHorizontal
```cs
if (uvTestValue.x > tiling.x * maxPanHorizontal || uvTestValue.x < tiling.x * minPanHorizontal)
{
    xLimited = true;
}
if (uvTestValue.y > tiling.y * maxPanVertical || uvTestValue.y < tiling.y * minPanVertical)
{
    yLimited = true;
}
```

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/1c9e05f3ba65b5c52d191b9b1d204dde41f866f8/Assets/MRTK/SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs#L430-L437

## Additional context
This video is the application I wanted to create.  
I used the custom HandInteractionPanZoom script with the above features added.

https://youtu.be/qldZZ65yXTM

**Comment by Zee2** [comment]
Hi @tarukosu, if you'd like, we'd be happy to review a PR with the added feature.
