### ISSUE TITLE
Need to ensure asmdefs are correctly set up for 2019 before packing for UPM

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#8574]
## Describe the bug

If the asmdefs aren't correctly set up for Unity 2019 before packing for UPM, the auto-config-checkers attempt to edit immutable assets and fail:

```
The package cache was invalidated and rebuilt because the following immutable asset(s) were unexpectedly altered:
  Packages/com.microsoft.mixedreality.toolkit.foundation/Providers/XRSDK/Microsoft.MixedReality.Toolkit.Providers.XRSDK.asmdef
  Packages/com.microsoft.mixedreality.toolkit.foundation/Providers/WindowsMixedReality/XRSDK/Microsoft.MixedReality.Toolkit.Providers.XRSDK.WMR.asmdef
```

This prevents references and asmdef-specific compilation defines from being set, preventing certain code from properly running.

## To reproduce

1. [Import MRTK via UPM](https://microsoft.github.io/MixedRealityToolkit-Unity/version/prerelease/2.5.0_stabilization/Documentation/usingupm.html)
2. Watch the console

## Tracking

- [x] XRSDK (#8591)
- [x] WMR XRSDK (#8591)
- [x] Oculus (#8655)
- [x] Leap (#8697)
- [x] UnityAR (#8667)

**Comment by wiwei** [comment]
@keveleigh if you're heads down this week on other things, can you redirect this to @MaxWang-MS?

**Comment by davidkline-ms** [comment]
Fixed with #8591

**Comment by keveleigh** [comment]
@davidkline-ms I'm going to reopen this for now, to continue tracking the Leap Motion and Oculus asmdefs, which I believe need additional changes to set them up for when the corresponding SDKs are installed. https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8591#issuecomment-696393464

**Comment by keveleigh** [comment]
@davidkline-ms Thoughts on adding any configuration checkers to a .npmignore once we get the asmdefs configured correctly in the repo? That way there isn't any confusion or attempt to edit the asmdefs

**Comment by MaxWang-MS** [comment]
According to @RogPodge the Oculus integration works just fine when he tested using UPM MRTK. Maybe @RogPodge could take a look?

**Comment by keveleigh** [comment]
After some additional testing, I think Unity 2019 might allow you to edit these asmdefs even though they're in immutable folders, but the message in the original post about an invalidated package cache happens in Unity 2020. We should prepare for that and not edit files from UPM wherever possible.

**Comment by hybridherbst** [comment]
May I recommend having the Oculus asmdefs referenced directly?
If the Oculus integration is not there they're not there, but the asmdefs still work.
(this is also the preferred way to work with packages that might potentially be there but are not always).

**Comment by RogPodge** [comment]
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8655 

PR up here, still needs testing.

**Comment by davidkline-ms** [comment]
Completed with #8697
