### ISSUE TITLE
MRTK Example Hub - " On Focus"Tooltip not appearing at correct scale

### ISSUE THREAD

**Issue by polar-kev** [microsoft/MixedRealityToolkit-Unity#8578]
## Describe the bug
The Examples Hub Tooltip scene tooltip that appears in the Show on Focus example is too small and not legible.

![image](https://user-images.githubusercontent.com/30964480/93381420-7b9b5300-f815-11ea-8691-047fe3b20d10.png)

## To reproduce

1. Import MRTK 2.5
2. Import MRTExampleHub package
3. Open the MRTKExamplesHub Scene
4. Run the Tooltip Scene in the editor
5. Focus on the green polygon

## Expected behavior

Tooltip should appear and be legible when green polygon is in focus

## Your setup (please complete the following information)

- Unity Version 2019.4.10.f1
- MRTK Version 2.5

**Comment by MaxWang-MS** [comment]
I was able to repro the behavior. Furthermore, pressing the platonic to the left causes null reference exception.
