### ISSUE TITLE
Question: Best Shader to display images?

### ISSUE THREAD

**Issue by HoloFan** [Microsoft/MixedRealityToolkit-Unity#858]
Hello,

I want to display images inside my application. So far I apply the image as a texture to a material. The material uses the "StandardFast"-Shader from the HTK. Unfortunatley the image ist quite dark and therefore it appears very transparent. Does someone knows a better shader to display images? Or maybe another trick?

Thanks in advance.

**Comment by StephenHodgson** [comment]
I believe that shader has been deprecated and you should be using `FastConfigurable`.
See https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/628

**Comment by Ziugy** [comment]
Do you need / want lighting on this image? You could use Mobile/Diffuse or Unlit, or Sprites/Default or Diffuse depending on your case. Will be quite performant too.

**Comment by HoloFan** [comment]
@Ziugy : Thanks you very much!

I used the Unlit->Texture shader and it works like a charme.
