### ISSUE TITLE
Oculus Package integration tool does not initialize prefabs properly and doesn't give helpful log messages

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#8587]
## Describe the bug

When configuring the MRTK for the Oculus Quest, the Oculus Package integration tool does not initialize prefabs properly and doesn't give helpful log messages. This causes anything the MRTK built for the Oculus Quest to have a stationary viewpoint on the device.

## To reproduce

1. Follow the steps on the [Configure MRTK for Oculus Quest](https://microsoft.github.io/MixedRealityToolkit-Unity/version/mrtk_development/Documentation/CrossPlatform/OculusQuestMRTK.html?q=QUEST) page to add the Oculus Quest to the project.
2. Build and deploy any MRTK example scene.
3. Attempt to look around the example scene.

## Expected behavior

When the Oculus Package integration tool fails, it should generate helpful log messages to notify the user of the issue.

## Your setup (please complete the following information)

- MRTK Version 2.5.0-20200912.1

## Target platform (please complete the following information)

- Oculus Quest

**Comment by keveleigh** [comment]
Ahh, I think we might be missing some info on setting the profiles up for XR SDK in addition to adding the Oculus data provider.

[This page](https://microsoft.github.io/MixedRealityToolkit-Unity/version/mrtk_development/Documentation/GettingStartedWithMRTKAndXRSDK.html#required-in-mrtk) is titled generically but currently pretty specific to WMR. Generally though, the

>Choose the "DefaultXRSDKConfigurationProfile" as the active profile or clone it to make customizations. This profile is set up with MRTK's XR SDK systems and providers, where needed.

part is likely important for Quest as well, as there are XR SDK camera settings that are required. We could either be more clear on the Quest page or update the above "Getting Started" page to include Quest and link to it.

**Comment by elbuhofantasma** [comment]
I believe that the PR #8590 takes care of this issue, so I am closing this.
