### ISSUE TITLE
send data from android app to hololens

### ISSUE THREAD

**Issue by hencohen3** [Microsoft/MixedRealityToolkit-Unity#859]
Hi,
I am trying to connect android (As server) to hololens. i tried tcp connection but uwp does not supported.
What connection can i make between the devices?

If i want to use the SharingStage.cs -"Allows you to communicate between a Windows and non-Windows device" how can i connect android device?

Thanks,
Chen

**Comment by shenwooash** [comment]
you can use streamsocket.

**Comment by hencohen3** [comment]
@shenwooash  do i need visual studio 2017 for that or i can use visual studio 2015?

**Comment by StephenHodgson** [comment]
The only difference visual studio will make is if you're using specific SDK APIs that requires you to have a different msbuild path.

**Comment by HoloFan** [comment]
I used the StreamSocket-Class to establishe a communication between my HoloLens and an Server (UWP-Application). it works quite good. You just need to use the same port and the HoloLens needs to know the IP-Adress of the server.

**Comment by hencohen3** [comment]
@HoloFan  thanks, do you have a StreamSocket-Class for example to attache?

**Comment by HoloFan** [comment]
@hencohen3 : Sorry for the delay. I hat no internet :(
Here is the unity code I used. I threw out all the stuff that is not necessary. Also keep in mind that you need the server side as well. I used some simple Keywords to set up my own protocol. All keywords are followed by "|" to seperate the commands/information. 

CHATM - Chat message. Just plain string
JOINM - Confimation from server that client has joined the session
BROAD - simple string send from server to all clients.
CONCT - Followed by UserName to establish connection between client & server
DSCON - Disconnect from server
SVRCL - Server closed down. 

I hope this helps you to solve your problem.

[SampleSSClient.txt](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/1255731/SampleSSClient.txt)
[SampleSSConnection.txt](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/1255732/SampleSSConnection.txt)

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
