### ISSUE TITLE
Exception "Instancing is not supported" on platform that doesn't support GPU draw call instancing

### ISSUE THREAD

**Issue by Rufus31415** [microsoft/MixedRealityToolkit-Unity#8600]
## Describe the bug

If you enable the visual profiler, an InvalidOperationException: "Instancing is not supported" could occur in MixedRealityToolkitVisualProfiler.cs line 384, if the platform doesn't support GPU draw call instancing. The method ```Graphics.DrawMeshInstanced()``` throws this exception.

## To reproduce

WebGL 1.0 doesn't support it for example. 
1. Change your Unity platform to WebGL
2. Edit -> Graphics emulation -> "WebGL 1.0"
3. Play in editor and you will get the exception at each frame

You can also compile for WebGL and execute it in a browser that only support WebGL 1.0.

## Setup

- Unity Version 2019.4.2f1
- MRTK Version 2.4

## Target platform 

- WebGL 1.0

## Additional context

In MixedRealityToolkitVisualProfiler.cs, you already bypass ```Graphics.DrawMeshInstanced()``` if ```defaultInstancedMaterial  == null```, you coud just add the condition ```SystemInfo.supportsInstancing``` :

``` cs
if (defaultInstancedMaterial != null && SystemInfo.supportsInstancing)
{
  frameInfoPropertyBlock.SetMatrix(parentMatrixID, parentLocalToWorldMatrix);
  Graphics.DrawMeshInstanced(quadMesh, 0, defaultInstancedMaterial, frameInfoMatrices, frameInfoMatrices.Length, frameInfoPropertyBlock, UnityEngine.Rendering.ShadowCastingMode.Off, false);
}
else
{
...
}
```

**Comment by keveleigh** [comment]
Fixed in 2.5 via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8613
