### ISSUE TITLE
MRTK Extensions Missing Links

### ISSUE THREAD

**Issue by laultman** [microsoft/MixedRealityToolkit-Unity#8601]
## Describe the issue
To enable the extension, open your RegisteredServiceProvider profile. WHERE is it?

## Feature area
Enabling the extension
MRTK is massive, the extensions just add more pain when you don't provide links to the topic.

## Existing doc link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Extensions/SceneTransitionService/SceneTransitionServiceOverview.html

**Comment by laultman** [comment]
Just in case anybody is looking... This is NOT in the Scene System in the MRTK. You find this by selecting the MixedReality Tookit from the Hierarchy pane then in the list of services (Camera, Input, etc.) You will find Scene System but it is not there, it is in the Extensions. Why there in no link to this information is simple there is no documentation to link to.

**Comment by keveleigh** [comment]
I couldn't find exactly the lines you're referring to, but docs on the Scene System are at https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/mrtk2/features/scene-system/scene-system-getting-started?view=mrtkunity-2022-05 and docs on the Scene Transition Service are at https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/mrtk2/features/extensions/scene-transition-service?view=mrtkunity-2022-05
