### ISSUE TITLE
Build folder conflicts with gitignore defaults

### ISSUE THREAD

**Issue by AlexKaczmarek** [Microsoft/MixedRealityToolkit-Unity#861]
Hey,

I just spotted it today, that Build folder from MixedRealityToolkit won't be recognized in git if you generate by default a .gitignore for Unity:

![image](https://user-images.githubusercontent.com/7922303/29316408-3d7880d2-81c8-11e7-86c9-147094d91648.png)

I had to remove [Bb]uild to fix this issue.

I understand, that's not a bug per se and it's not your fault, but it would be nice if new users could avoid it in the future :)

**Comment by StephenHodgson** [comment]
Thanks for the report
