### ISSUE TITLE
Core interface breaking change review for 2.5

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#8611]
## Overview

I was doing a diff between our core interfaces between 2.4 and 2.5 to see if we had any breaking changes in that layer. I found three:

1. https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8258 adds a new required method to IMixedRealityPointerMediator, which seems unavoidable because it's a required contract for the mediator respecting pointer preferences.
    1. Seems unavoidable, but it'd be great if there are any suggestions for improvement!
1. https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8227, which could be split out into an IMixedRealityDictationAudio interface.
    1. I think this is a good candidate for splitting out.
1. https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7712, which added a grasp axis method to IMixedRealityNearPointer that seems to be only internally used by the sphere pointer at this time.
    1. Opened #8610 to remove

**Comment by davidkline-ms** [comment]
I agree with these recommendations.

**Comment by davidkline-ms** [comment]
The POR is to not change item #2. closing as the others are complete
