### ISSUE TITLE
Crash at launch when building targeting ARM64 with dotnetwinrt package imported

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#8615]
## Describe the bug

Currently mrtk_dev branch hand interactions example application built targeting ARM64 with the dotnetwinrt package imported into Unity crashes at launch on HL2.

## To reproduce

1. Open the dev branch in Unity
2. Import nuget and then dotnetwinrt. Also make sure to perform the check configuration step for WMR
2. Build the hand interactions example scene targeting master ARM64
3. Deploy to HL2 with the same settings

## Expected behavior

The application should not crash.

## Your setup (please complete the following information)

- Unity 2019.4.10f1
- mrtk_dev branch

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
Are you able to repro without DotNetWinRT? This sounds like the known issue we found with ARM64 crashing on launch, which https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8588 should help with until VS ships the bug fix.

**Comment by MaxWang-MS** [comment]
I can confirm that the workaround introduced in #8588 solves this problem. The issue is left open for now in case someone encounters the same problem. Thanks @keveleigh!

**Comment by wiwei** [comment]
Closing this one out as a dupe (and also because we added that build tooling to auto add that ARM64 workaround)
