### ISSUE TITLE
Loading overlays for Windows Mixed Reality in Unity

### ISSUE THREAD

**Issue by subzero110** [Microsoft/MixedRealityToolkit-Unity#862]
It seems that Steam and OVR plugins in Unity ship with a script that can be used during transitions (scene change, load behavior, etc.) to display overlays (instead of the screen going all dark). This is a pretty useful out-of-box script that anyone can use while developing their games.

Attached are the scripts.

Can we do something similar for Windows MR, so that not everyone has to write one from scratch?

[OVROverlay.cs.txt](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/1226092/OVROverlay.cs.txt)
[SteamVR_Overlay.cs.txt](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/1226091/SteamVR_Overlay.cs.txt)

**Comment by jessemcculloch** [comment]
@subzero110 - In the Dev_Unity_2017.2 branch, in the Utilities/Scripts area, there is a fadescript script.  Check that out and see if that is similar to what you are talking about, or maybe that's what we need to extend for this.

**Comment by plmayer** [comment]
I'd like to second that request. The FadeScript seems to be something else. What we are talking about, as implemented in Steam and OVR, is the ability to set an image (i.e. a Sprite in Unity) to be displayed on the HUD of the headset without any Unity involvement. (In Steam and OVR, the image is displayed only on the HUD (not in the mirror view), so I believe it is a rather low-level access mechanism).

This is super-helpful for displaying loading screens in-between scenes. I.e. you fade out, display that image, and then load a new scene (synchronously) in Unity, all the while only displaying the loading image, no hickkups. When the loading is done, you remove the image and fade in your scene. The loading screen is thus independent of any one scene.

**Comment by StephenHodgson** [comment]
One other thing to keep in mind is that if we add anything to the Mixed Reality Camera Parent then we also need a way to disable this overlay so it doesn't impact performance.

**Comment by plmayer** [comment]
Yes. By the way, you probably are not talking about the Unity gameobject parent for the camera when you say "Camera Parent", but on the off chance that you do, note that the SteamVR/OpenVR-image is independent of any scene. It's set directly, bypassing Unity scene mechanics.

**Comment by plmayer** [comment]
@StephenHodgson There is no way to do this currently with WMR, is there? Outside of the MixedRealityToolkit, maybe - directly calling some DLL?

**Comment by plmayer** [comment]
@StephenHodgson I've noticed that the Haptics implementation only works at runtime, and by directly calling Windows API. Is there any way to do something similar for a screen overlay? If there are classes in the Windows API which can do this I'd really appreciate a tip. Thanks.

**Comment by 265lutab** [comment]
I'm also looking for a way to do this.

**Comment by plmayer** [comment]
@StephenHodgson I am still interested in this feature - any updates?

**Comment by StephenHodgson** [comment]
None yet

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
