### ISSUE TITLE
Scrolling Object Collection - Destroyed Objects / Colliders

### ISSUE THREAD

**Issue by mattfedo-insight** [microsoft/MixedRealityToolkit-Unity#8633]
## Describe the bug

When dynamically adding objects to a ScrollingOC, then destroying them, then updating the collection, the ScrollingOC is throwing a Missing Ref exception.  For Colliders and Transform nodes.  It does not understand that the transform at which the Collider/Transform is based, is now gone and destroyed.

## To reproduce

Add a ScrollingOC > Dynamically add children to "Container" > dynamically destroy objects in a pool > UpdateCollection() > Null Ref  ** NOTE this also happens in the Transform for the Nodes. **

## Expected behavior

A Clear and Update function should be applied to the ScrollingOC so that all is cleared and we can then re-lazy load objects and prefabs into the SOC. :) Thanks!

## My fix - currently, just adding NULL checks on everything.

```

// Disable colliders on items that will be scrolling in and out of view
                    if (disableNode)
                    {
                       if(node == null) return;
                        foreach (Collider c in node.Colliders)
                        {
                            if(c != null)
                                c.enabled = false;
                        }
                    }
                    else
                    {
                        if (node == null) return;
                        foreach (Collider c in node.Colliders)
                        {
                            if(c != null)
                                c.enabled = true;
                        }
                    }
```

**Comment by vaoliva** [comment]
Hi @mattfedo-insight. Thanks for spotting the issue. The Scrolling Object Collection is being graduated from an experimental feature in MRTK 2.5 with some changes to its functionality. This issue was also addressed.

**Comment by mattfedo-insight** [comment]
@vaoliva huzzah!  Thank you!

**Comment by wiwei** [comment]
Now that 2.5 is released, closing this issue out

**Comment by mattfedo-insight** [comment]
Thanks @wiwei !!
