### ISSUE TITLE
"Integrate Oculus Integration Unity Modules" does not work with new packages

### ISSUE THREAD

**Issue by hybridherbst** [microsoft/MixedRealityToolkit-Unity#8637]
## Describe the bug

After following the package setup steps listed here: https://microsoft.github.io/MixedRealityToolkit-Unity/version/prerelease/2.5.0_stabilization/Documentation/usingupm.html

I was trying to follow the Quest setup from here: https://microsoft.github.io/MixedRealityToolkit-Unity/version/prerelease/2.5.0_stabilization/Documentation/CrossPlatform/OculusQuestMRTK.html

However, it seems since there is some asmdef magic going on there's an error when the MRTK is coming from a package (which are immutable in Unity):
![image](https://user-images.githubusercontent.com/2693840/94017345-9f2f4200-fdaf-11ea-8628-62d128c4957a.png)

## Expected behavior

No error thrown, Quest setup works

## Your setup (please complete the following information)

- Unity 2020.2.0b2
- MRTK Version 2.5.0-preview.20200922.2

## Target platform (please complete the following information)

- Quest

## Additional context

I think the right way to handle this is that the asmdefs already have the right reference to the correct GUID. It's not a problem if an asmdef has missing references as long as their existance is properly checked (e.g. through project scripting defines or version defines on the asmdef).

**Comment by keveleigh** [comment]
Related to #8574. We need to make sure this assembly is properly configured before packing

**Comment by hybridherbst** [comment]
I see.
Happy to do a PR to fix the Oculus side of things.

**Comment by davidkline-ms** [comment]
Fixed by #8655
