### ISSUE TITLE
UPM Package version 2.5.0 from the docs does not exist (yet)

### ISSUE THREAD

**Issue by hybridherbst** [microsoft/MixedRealityToolkit-Unity#8638]
## Describe the issue
The docs mention that the right package version to use is 0.2.5:
https://microsoft.github.io/MixedRealityToolkit-Unity/version/prerelease/2.5.0_stabilization/Documentation/usingupm.html

Actually, this version does not exist yet; the latest version is 2.5.0-preview.20200922.2 (and needs to be entered exactly like that to work).

## Existing doc link
https://microsoft.github.io/MixedRealityToolkit-Unity/version/prerelease/2.5.0_stabilization/Documentation/usingupm.html

**Comment by davidkline-ms** [comment]
This is correct. The documentation on UPM was written in preparation of the release.

**Comment by hybridherbst** [comment]
I figured that by now :)

I for myself had been drawn to those docs pages because people started posting on Twitter that everything's ready to be used, linking to them. Not sure if it's feasible but maybe a note on the docs ("this will work in a future release") might make sense?
