### ISSUE TITLE
Oculus Quest Hands setup docs are missing crucial steps

### ISSUE THREAD

**Issue by hybridherbst** [microsoft/MixedRealityToolkit-Unity#8642]
## Describe the issue
The docs don't mention that the prefab references to OVRCameraRig and LocalAvatar need to be set up manually.
Also, they don't mention that for hands to work, a new Prefab (or Variant) needs to be created with hands included (e.g. from the HandsInteractionTrainScene camera rig with added hands).

## Existing doc link
https://microsoft.github.io/MixedRealityToolkit-Unity/version/prerelease/2.5.0_stabilization/Documentation/CrossPlatform/OculusQuestMRTK.html

## Additional context
Those Prefab references are empty by the default.
The OVRCameraRig variant (or prefab) needs to be created first, using the regular OVRCameraRig will not include hands.

![image](https://user-images.githubusercontent.com/2693840/94048827-5ccc2c00-fdd4-11ea-908a-463f2186ee65.png)

**Comment by RogPodge** [comment]
the latest MRTK code should set up these prefabs automatically, will be monitoring as we test the latest preview packages.

**Comment by wiwei** [comment]
Closing this out given @RogPodge comments above.

**Comment by hybridherbst** [comment]
I think this should be closed when the packages are actually live?
