### ISSUE TITLE
Referenced script missing in Examples Hub Scene (UPM)

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#8647]
## Describe the bug

The `LoadProfilesOnStartup` script is missing from SceneContent when playing the MRTKExamplesHub scene (the SceneContent GameObject is under MRTKExamplesHubMainMenu in the hierarchy).

## To reproduce

1. Go to the MRTKExamplesHub scene
2. Click on play
3. See error

## Your setup

- Unity 2019.4.10f1
- Latest MRTK UPM package

## Target platform

- HoloLens 2

**Comment by davidkline-ms** [comment]
Thanks @MaxWang-MS ! I'll take a look today
