### ISSUE TITLE
ClosestPoint warning in the MRTKExamplesHub scene

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#8649]
## Describe the bug

The non-convex mesh colliders on the MRTK logo quads of buttons are generating the following warning when interacting with simulated hand in editor play mode:

Physics.ClosestPoint can only be used with a BoxCollider, SphereCollider, CapsuleCollider and a convex MeshCollider.
UnityEngine.Collider:ClosestPoint(Vector3)

It might be good to just remove those colliders.

## To reproduce

1. Go to the MRTKExamplesHub scene
2. Click on play
3. Move simulated hand to one of the big buttons (e.g. hand menu examples)

## Your setup

- Unity 2019.4.10f1
- MRTK 2.5 stabilization branch

## Target platform

- HoloLens 2

**Comment by keveleigh** [comment]
Fixed via #8652
