### ISSUE TITLE
Leap Motion Hand Tracking Example scene has too many event systems warning

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#8654]
## Describe the bug

When opening the Leap Motion Hand Tracking Example scene in Unity 2019.10f1 a warning is generated for having too many events in the scene. This issue does not happen in Unity 2018. 

## To reproduce

1. Import the .unitypackages into a new project
2. Switch the platform to UWP
3. Open the Leap Motion Hand Tracking Example scene
4. Look at the Unity console output

## Expected behavior

No warnings will be generated when opening the Leap Motion Hand Tracking Example scene.

## Screenshots

![teleportwarning](https://user-images.githubusercontent.com/65038391/94073908-2202cd80-fdad-11ea-9c9d-21b11519d1ec.png)
![Teleportevent](https://user-images.githubusercontent.com/65038391/94073917-24652780-fdad-11ea-81c4-58ae787ea949.png)

## Your setup (please complete the following information)

- Unity Version 2018.4.10f1
- MRTK Version 20200922.2

## Target platform (please complete the following information)

- UWP

**Comment by elbuhofantasma** [comment]
This issue is similar to #8720

**Comment by keveleigh** [comment]
Fixed by #8750 and cherry-picked to 2.5.1 by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8799
