### ISSUE TITLE
Dictation Example scene generates an error about the MixedRealityInputModule when opened

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#8656]
## Describe the bug

When opening the Assets/MRTK/Examples/Demos/Input/Scenes/Dictation/DictationExample.unity scene, an error is generated for having an input module already selected for the main camera. 

## To reproduce

1. Import the MRTK .unitypackages
2. Open Assets/MRTK/Examples/Demos/Input/Scenes/Dictation/DictationExample.unity
3. Look at Unity console output

## Screenshots
**Unity 2018**
![2018dictationexampleinputmoduleerror](https://user-images.githubusercontent.com/65038391/94082664-4fa04480-fdb6-11ea-8f5f-bf8d2a7e3b06.png)

**Unity 2019**
![2019dictationexampleinputmoduleerror](https://user-images.githubusercontent.com/65038391/94082691-5f1f8d80-fdb6-11ea-9de8-95ece5ac60e3.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.10f1, 2018.4.27f1
- MRTK Version 20200922.2
## Target platform (please complete the following information)

- Standalone
- UWP

**Comment by keveleigh** [comment]
Fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8659
