### ISSUE TITLE
MRTK prefabs are showing pink icons on Unity 2019.4

### ISSUE THREAD

**Issue by vaoliva** [microsoft/MixedRealityToolkit-Unity#8662]
## Describe the bug

A good number of MRTK prefabs are showing pink icons on 2019.4.
Icons appear normal in Unity 2018.4.

![Screenshot (75)](https://user-images.githubusercontent.com/16922045/94165926-a6735000-fe82-11ea-892e-ab06b425ca2e.png)

##  Steps to reproduce

1. Checkout the prerelease/2.5.0_stabilization branch
2. Open project in Unity 2019.4
3. Under editor Project tab, do a search by type `Prefab`

## Setup
Unity 2019.4
MRTK 2.4  + MRTK 2.5 - Stabilization branch

**Comment by MaxWang-MS** [comment]
I was not able to repro with a fresh copy of 2.5 stabilization branch and Unity 2019.4.10f1. Could you retry with a fresh copy of MRTK or share more detailed repro instructions?

**Comment by vaoliva** [comment]
Thanks @MaxWang-MS . I have updated the steps. I will try with a completely fresh copy.

**Comment by wiwei** [comment]
Closing this out for now, we can reopen if we still hit this going forward
