### ISSUE TITLE
Rename HoloToolkit folders to MixedRealityToolkit

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#867]
I know this is already on the roadmap but I'd like to put it here for tracking purposes.

**Comment by Mikeman3561** [comment]
I know this is a touchy subject, but can you provide a reason to why this toolkit is Mixed as opposed to Augmented? I appreciate the advancement, but personally feel that the Hololens is an AR technology, as opposed to MR.

**Comment by StephenHodgson** [comment]
That's what Microsoft choose to market their technology as.

**Comment by Mikeman3561** [comment]
So Mixed encompasses Augmented, Virtual, and Mixed?
Thank you, I'll bring this to a different forum.

**Comment by keveleigh** [comment]
@Mikeman3561 Yep! The term Mixed Reality is meant to refer to a spectrum of device types and experiences (the blue can be thought of as augmented reality, and the green can be thought of as virtual reality):

![image](https://user-images.githubusercontent.com/3580640/30401509-64f5220e-988f-11e7-93af-2885b277a3d5.png)
![image](https://user-images.githubusercontent.com/3580640/30401524-7924e1d8-988f-11e7-9705-7f6ced881567.png)

We're currently working on adding support for the immersive headsets in [our dev branch](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/Dev_Unity_2017.2.0), which is part of what prompted the name change.

**Comment by HattMarris1** [comment]
Where does XR fit into this? (I understand that there are different definitions for these things, but I thought what @keveleigh described was XR)
