### ISSUE TITLE
Hololens2 not detected correctly 

### ISSUE THREAD

**Issue by eusebiu** [microsoft/MixedRealityToolkit-Unity#8673]
## Describe the bug
An app built using MRTK 2.4  on Hololens2 (19041.1117.arm64fre.vb_release_svc_sydney_rel_prod.200903-1632) is not detecting correctly the device.

## To reproduce

1. Download sample app - https://1drv.ms/u/s!Aq1jgNgVNaunk2lysu7PJQEZO2Dh?e=HavpHL
2. Switch platform to UWP
3. Build
4. Open built project - Release & ARM64 - and deploy on HL2.
=> app starts but with errors and the objects follow the camera.

## Expected behavior

Application starts and objects stay put.

Log:
[Log] Hand - Right does not have a defined controller type, falling back to generic controller type
[Warning] No controller interaction mappings found for Microsoft.MixedReality.Toolkit.Input.UnityInput.GenericJoystickController.
[Error] Failed to create GenericJoystickController controller
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:GetOrAddController(String)
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:RefreshDevices()
Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityJoystickManager:Update()
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:Update()
Microsoft.MixedReality.Toolkit.<>c:<UpdateAllServices>b__64_0(IMixedRealityService)
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:UpdateAllServices()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update()

## Screenshots

See [video](https://1drv.ms/v/s!Aq1jgNgVNaunk2hwY6F5H3e3NjLl)

## Your setup

- Unity Version 2020.1.3f1, 2019.4.11f1
- MRTK Version 2.4.0

## Target platform

- HoloLens 2

**Comment by davidkline-ms** [comment]
This behavior sounds as if the XR settings are not configured. Is the project using XRSDK or the legacy XR API?

**Comment by eusebiu** [comment]
> This behavior sounds as if the XR settings are not configured. Is the project using XRSDK or the legacy XR API?

It is using the XRSDK (Unity 2020 removed the legacy XR, I think).

![image](https://user-images.githubusercontent.com/414589/94292818-1b6b8600-ff66-11ea-926d-9890c139b379.png)

![image](https://user-images.githubusercontent.com/414589/94292881-35a56400-ff66-11ea-8ea5-49ea90411b83.png)

**Comment by keveleigh** [comment]
Yep, that looks like XR SDK! You'll want to make sure you're using the DefaultXRSDKConfigurationProfile, if you're using MRTK defaults. Otherwise, more info can be found at https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.4.0/Documentation/GettingStartedWithMRTKAndXRSDK.html#required-in-mrtk for updating your custom profile.

**Comment by eusebiu** [comment]
Indeed, that was it! Then what is with the DefaultHololens2ConfigurationProfile? Which one is recommended for Hololens2?

**Comment by keveleigh** [comment]
>Which one is recommended for Hololens2?

Sorry about the confusion here. We're in a bit of a transition between Unity's original XR pipeline and their [new XR SDK APIs](https://blogs.unity3d.com/2020/01/24/unity-xr-platform-updates/). Most of our profiles are still on the old pipeline at the moment.

**Comment by eusebiu** [comment]
Oh, ok. That makes sense! Thanks for the support! Much appreciated!

**Comment by BogdanoVolcano** [comment]
> 
> 
> Yep, that looks like XR SDK! You'll want to make sure you're using the DefaultXRSDKConfigurationProfile, if you're using MRTK defaults. Otherwise, more info can be found at https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.4.0/Documentation/GettingStartedWithMRTKAndXRSDK.html#required-in-mrtk for updating your custom profile.

Thank you so much! That's completely solved all my problems.
