### ISSUE TITLE
Importing Foundation .unitypackage generates a 'type or namespace does not exist' error

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#8681]
## Describe the bug

After importing the Foundation package into Unity 2019.4.10f1, the Unity console generates a 'type or namespace does not exist' error as seen in the screenshot below. This issue does not occur in Unity 2018.

## To reproduce

1. Import the Foundation .unitypackage
2. Navigate to Unity console to see the error

## Expected behavior

There are no errors generated from importing the Foundation package into a new Unity project.

## Screenshots

![foundation import](https://user-images.githubusercontent.com/65038391/94317680-a5522980-ff3b-11ea-9d59-f5f08f745037.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.10f1
- MRTK Version 20200925.7

## Target platform (please complete the following information)

- Standalone

**Comment by keveleigh** [comment]
Fixed via #8683
