### ISSUE TITLE
Importing Foundation + Extension + Utilities + Tools .unitypackages will generate 2 'could not delete file' errors

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#8685]
## Describe the bug

Importing the Foundation, Utilities, and Tools .unitypackages will generate 2 'could not delete file' errors when imported in a specific way. The Foundation package needs to be imported first, then import the Extension package, and then install the Utilities package, and finally the Tools package. The Utilities and Tools packages can be installed in any order after the Foundation and Extension packages are imported.

## To reproduce

1. Import the Foundation .unitypackage
2. Import the Extensions .unitypackage
3. Import the Utilities .unitypackage
4. Import the Tools .unitypackage

## Expected behavior

There should not be any errors generated when importing MRTK packages.

## Screenshots

![handphysicsddl bakdeleteerror](https://user-images.githubusercontent.com/65038391/94322302-f582b900-ff46-11ea-8800-d47f8107a7ce.png)
![handphysics pdbdeleteerror](https://user-images.githubusercontent.com/65038391/94322303-f74c7c80-ff46-11ea-8121-ac12f8c99a51.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.10f1
- MRTK Version 20200925.7

## Target platform (please complete the following information)

- Standalone

**Comment by wiwei** [comment]
I *think* that what you're hitting here is related to windows defender exclusion lists and things - i.e. we noticed this would happen if you didn't add the project's source folder to defender's exclusion. I think that this should get resolved once that's done.
