### ISSUE TITLE
Allow adding customized handles to bounds control

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#8693]
## Describe the problem

We're already creating handles via factory pattern and configurations in bounds control. Potentially users could create their own version of handles through this system. However what's missing is:
- Some methods in handles might still be access restricted to internal 
- The logic for actually modifying the transform is still inside of the bounds control class. If we move that logic into the handles we could swap handles and logic easier.
Stretch goal: We're not limiting the handles to Translate\Scale\Rotate but instead have a more flexible way (list) of adding handles. That way a bounds control could be created with just having eg scale handles, or several different types of rotation handles depending on where they were created. (Stretch goal can be moved into separate issue)

## Describe the solution you'd like

Users can plug their own handles into existing translation / scale / rotate handle configuration slots and bounds control uses those configurations to perform manipulation.

Handles are not limited to the three available transform slots but there can be user defined amount of handles plugged into the system.

## Describe alternatives you've considered

Users can plug their own handles into existing translation / scale / rotate handle configuration slots and bounds control uses those configurations to perform manipulation.

Handles are limited to the three available transform slots.

**Comment by Zee2** [comment]
Handle customization is prefab-based in MRTK3 and quite flexible. Closing this as stale for now.
