### ISSUE TITLE
MRC not aligned with perspective of pv camera (XRSDK)

### ISSUE THREAD

**Issue by normanRV** [microsoft/MixedRealityToolkit-Unity#8707]
## Describe the bug

When using Mixed Reality Capture holograms aren't aligned with pv camera  (XRSDK). It seems that the transformation offset isn't considered when rendering from the pv camera. With mixed reality built-in xr platform integration hologram alignment ist correct. The problem exists only with XRSDK.

## To reproduce

1. Using mrtk InteractableExamples-scene
2. Added mrtk + xrsdk
3. Attach TrackedPoseDriver to MainCamera
4. Using cloned DefaultXRSDKConfigurationProfile, just enabled Render from PVCamera
5. Build XR SDK app to Hololens (ARM)

## Expected behavior

Aligned holograms with PV camera

## Screenshots

![bugReport](https://user-images.githubusercontent.com/70317161/94552270-e5285200-0256-11eb-92e1-02b7cee18477.jpg)

![20200929_123139_HoloLens](https://user-images.githubusercontent.com/70317161/94552344-fffac680-0256-11eb-96ba-5b99a6d0fb90.jpg)

## Your setup (please complete the following information)

- Unity 2019.4.9f1 and Unity 2020.1.6f1 
- Mixed Reality Toolkit 2.4.0
- Windows XR Plugin 4.0.2
- XR Plugin Managment 3.2.15

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
This is currently a known issue that we're tracking with Unity. I'll update this thread when I have more info!

**Comment by polar-kev** [comment]
Additional detailed repro steps captured in a duplicate issue https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9169#issue-793922581

**Comment by camnewnham** [comment]
> This is currently a known issue that we're tracking with Unity. I'll update this thread when I have more info!

Have there been any updates on this issue or is there a Unity bug tracker for it?

**Comment by keveleigh** [comment]
Apologies about my lack of update here. This _should_ be fixed on the latest Windows XR Plugin across the latest Unity versions. I can narrow down the versions if needed, and please let me know if you're still seeing issues on the latest!

**Comment by camnewnham** [comment]
@keveleigh I can confirm that it's resolved and records correctly in the only configuration I tested:
Unity 2020.3.12f1 with Windows XR Plugin 4.5.0

The warning from https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9170 is still present in the MRTK MRC settings as of MRTK 2.7.2.0:
![image](https://user-images.githubusercontent.com/19278856/125023091-791a2a80-e0c1-11eb-9137-358d702ef7d4.png)

Thanks!

**Comment by keveleigh** [comment]
@camnewnham Ah, thanks for pointing that out! It's probably been enough time that we can remove that now. I'll get it sorted tomorrow!

**Comment by Hanning-Liu** [comment]
@keveleigh Hi, I meet the same issue recently and I’m using MRTK3. How to set the “render from PV camera” function in MRTK3?

**Comment by keveleigh** [comment]
> @keveleigh Hi, I meet the same issue recently and I’m using MRTK3. How to set the “render from PV camera” function in MRTK3?

I believe it's on by default now when you're using the Mixed Reality OpenXR Plugin. If you're looking to turn it off, there's a checkbox in the Mixed Reality Features settings:
![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/3580640/92e345aa-cb96-458d-9c3a-e1705a7e7514)

**Comment by Hanning-Liu** [comment]
> > @keveleigh Hi, I meet the same issue recently and I’m using MRTK3. How to set the “render from PV camera” function in MRTK3?
> 
> I believe it's on by default now when you're using the Mixed Reality OpenXR Plugin. If you're looking to turn it off, there's a checkbox in the Mixed Reality Features settings: ![image](https://private-user-images.githubusercontent.com/3580640/328240719-92e345aa-cb96-458d-9c3a-e1705a7e7514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTQ4MjUsIm5iZiI6MTcxNTAxNDUyNSwicGF0aCI6Ii8zNTgwNjQwLzMyODI0MDcxOS05MmUzNDVhYS1jYjk2LTQ1OGQtOWMzYS1lMTcwNWE3ZTc1MTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMTY1NTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI4YWQ0NGU2ZjQ1NjI2OGUzZDYzOGY0OGI2NDdjNDI1M2M4NTk1YTFmZGIyYjc0ZDVhN2RlNGEwNzMwZGNjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.15E-lnkOlOtm7n5gO3we9VsFLWcUIqy2UmGcEjBhshE)

Thank you for your reply! I’m using holographic remoting app now, is it possible to implement “render on PV camera” in this mode?

**Comment by keveleigh** [comment]
> Thank you for your reply! I’m using holographic remoting app now, is it possible to implement “render on PV camera” in this mode?

I don't believe it used to be, but someone from Microsoft can comment on the current state of things (@AMollis? @yl-msft?)
