### ISSUE TITLE
MeshSaver 'StorageFile' does not contain definition for 'OpenStreamForReadAsync'

### ISSUE THREAD

**Issue by DrunkReaperMatt** [Microsoft/MixedRealityToolkit-Unity#871]
I'm having an issue building the project due to this error. I can't seem to find any info on this.

**Comment by StephenHodgson** [comment]
Thanks for the report.

**Comment by ThmsMsqrt** [comment]
@StephenHodgson I bumped into this one yesterday too. I was using Unity v2017.2.0b7 and the toolkit version from the Master branch (so 2017.1.0f3). It seems the error triggers when you try to build with the backend version in the Player Settings is set to IL2CPP instead of .NET.

**Comment by DrunkReaperMatt** [comment]
My current setup for my project is 

Unity 2017.1.0f2
Backend: IL2CPP


To bypass this error, i just comment out the problem lines (162 and 189 of MeshSaver.cs)

**Comment by StephenHodgson** [comment]
Related to https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/265
