### ISSUE TITLE
Shell hand ray line visual does not stay connected to the pointer attachment sphere when moving windows

### ISSUE THREAD

**Issue by matthejo** [microsoft/MixedRealityToolkit-Unity#8710]
## Describe the bug

When moving a window using far hand interactions, the hand ray line does not stay connected to the cursor, and appears to sway back and forth before eventually re-tethering to the cursor. This seems to be a regression within the last few months.

## To reproduce

Open the MRTK Hand Interaction scene and use the far hand ray to move windows, especially with fast motion.

## Expected behavior

The spline for the bend hand ray remains attached to the cursor

## Screenshots

![image](https://user-images.githubusercontent.com/10050922/94599118-d5a00d80-0244-11eb-999f-e7d424185378.png)

## Your setup (please complete the following information)

- Unity Version 2018.4.26f1
- MRTK Version 2.6.0-20200908.3

## Target platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
Did a little looking at history here - I can see this issue as far back as January this year, digging a little more to see if there was a specific time in history where things were better than they are today.

**Comment by keveleigh** [comment]
Agreed with @wiwei that this doesn't seem like a recent regression. I remember a similar issue when working with @julenka on her "hand grab indicator" line, with it drifting off the object as the hand moved around. I also feel like I've noticed this issue in the past and can't think of a time when it changed.

It wouldn't surprise me if there's some visualization code around the hand ray bending that's drifting the "true" end point, or possibly the data sources for the cursor vs the pointer getting out of sync, maybe a frame or so apart causing the offset.
