### ISSUE TITLE
Improve Icon Rendering on HL2/VR devices.

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#8713]
## Describe the problem
Related to https://github.com/provencher/MRTK-Quest/issues/64#issuecomment-655584078

Icon rendering is noticeably blurry on VR devices Hololens 2 (slightly less so for the latter). 

![button_icon](https://user-images.githubusercontent.com/16922045/82577788-6114de00-9b83-11ea-896e-d17c0c9d7b8b.gif)

## Describe the solution you'd like

To address this improving the default icon shader with supersampling has been suggested 
https://medium.com/@bgolus/sharper-mipmapping-using-shader-based-supersampling-ed7aadb47bec

The plan is to add make modifications to the MRTK Standard Shader to super sample the mip maps and provide much sharper icon rendering. We'll be making this improvement toggleable on the shader level so users can choose to enable or disable this improvement. Note that there are performance concerns for hololens 1, so we need to take the impact on those users into consideration and need to either not enable this by default or have a way to configure settings based on deploying to Hololens 1 vs HL2/VR devices.

## Describe alternatives you've considered

We've considered creating a new shader with these improvements, though this approach would create further confusion for users for the "right way" to render icons with MRTK, so we'll be making these improvements to the default shader instead and making it toggleable.

**Comment by cre8ivepark** [comment]
Added GIF image captured by @vaoliva 
@Cameron-Micka for visibility

**Comment by vaoliva** [comment]
I believe this issue was also described on https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7941
