### ISSUE TITLE
How to test in Editor and build for VR

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#872]
I'm having issues testing in the editor and making builds with the Acer headset.

Does anyone have a link or some info on how this process should work?
Thanks.

Acer Headset & Controllers
Unity 2017.2.0b7
Visual Studio 2017 15.3

**Comment by keveleigh** [comment]
What issues are you running into? The process should be the same as HoloLens, except you're deploying to Local Machine instead of Device/Remote Machine.

Do you have the Windows Insider SDK installed? What build of Windows are you on?

**Comment by StephenHodgson** [comment]
Hey Kev, yeah I have the insider preview installed and set to `Active development` and `Fast`.

In the editor, when I press play the Acer device just has a black screen but the tracking works, and the editor freezes.

**Comment by jessemcculloch** [comment]
What machine/GPU are you using.  I've heard of a couple people seeing this same thing.

**Comment by jessemcculloch** [comment]
https://forums.hololens.com/discussion/8175/no-video-signal-in-headset-but-device-is-tracking-acer-mr-headset#latest

**Comment by StephenHodgson** [comment]
Probably not the best device for the job 😆

NVIDIA Quadro M1000M

It was working previously before trying to run in the editor, but now it's blank.

**Comment by StephenHodgson** [comment]
Got everything working in the Editor. Come to find out you need to launch the MR Portal before you start the Editor.  After that everything should work fine.
