### ISSUE TITLE
Fix the Handcoach/rigged hand model to handle pinch animations correctly

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#8730]
Currently the rigged hand meshes we use for visualization have issues matching the user's animations. Though the hand looks fine when doing pointing motions, the fingers do not close completely when doing pinching motions.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/39840334/94866457-3caff480-03f4-11eb-9e65-ec0643ebeaac.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/39840334/94866459-3de12180-03f4-11eb-8567-3dc528e7fb41.png)

This issue is mostly here to track the work for fixing up the model/getting a new one working.

**Comment by grayclee** [comment]
Leaving comment to keep track
