### ISSUE TITLE
UPM packages are missing Changelog.md / License.md

### ISSUE THREAD

**Issue by hybridherbst** [microsoft/MixedRealityToolkit-Unity#8734]
## Describe the bug

Unity UPM packages should contain a Changelog.md and License.md.
These are opened when users click on the respective buttons in the PackMan UI:
![image](https://user-images.githubusercontent.com/2693840/94901194-88b37580-0496-11eb-9fb4-4d086dba4058.png)

## To reproduce

1. Use the Unity UPM packages for MRTK
2. Open PackMan window
3. Click on "View changelog".

## Expected behavior

Changelog.md gets opened and a SemVer-following changelog is displayed

- Unity Version 2019-2020
- MRTK Version 2.5.0

## Additional Information

While I could create a PR adding the current and past changelog(s), I think this is probably better as a CI task.

**Comment by davidkline-ms** [comment]
Thank you for filing this!
