### ISSUE TITLE
"SerializedObjectNotCreatableException: Object at index 0 is null exceptions" when configuring scene for Hololens 1

### ISSUE THREAD

**Issue by KuraiAndras** [microsoft/MixedRealityToolkit-Unity#8736]
## Describe the bug

Configuring the MixedReality Toolkit with cloned default Hololens 1 profile produces 48 exceptions on start each are:
"SerializedObjectNotCreatableException: Object at index 0 is null exceptions"
from various parts of MRTK.

After build the scene is not working as intended: the whole scene is fixed in front of the user and follows the user when turning around.

## To reproduce

1. Create new unity projcet
2. Add MRT through UPM
3. Add new Scene
4. Add mrtk to scene
5. On the MixedRealityToolkit asset select the DefaultMixedRealityToolkitConfigurationProfile

The same bug is present when using the Hololens1 profile, cloning it, and fixing the broken default profiles with no luck. The same is also true for hololens 2

## Expected behavior

Default Hololens 1 profile should work out of the box for hololens 1

## Screenshots

![image](https://user-images.githubusercontent.com/19240945/94923912-eb1f6c80-04bc-11eb-9a1e-d6187fb3b19d.png)

## Your setup (please complete the following information)

- Unity Version 2020.1.6
- MRTK Version 2.5.0

## Target platform (please complete the following information)

- HoloLens 1
- HoloLens 2

## Additional context

[profiles.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/5317966/profiles.zip) The configuration I tried to use.
Using 2.4.0 the default Hololens 1/2 settings worked as expected

**Comment by keveleigh** [comment]
Can you click on any of those messages in the console and post the resulting call stack please?

**Comment by davidkline-ms** [comment]
Thanks for filing this. We are investigating.

**Comment by KuraiAndras** [comment]
Ok, so I cloned the repo on another computer, and it seems to work just fine. I can check on my other machine which produced the errors on Monday. Maybe it was just some weird caching error in Unity?

**Comment by KuraiAndras** [comment]
I have tried it again on my work computer, and could not reproduce the errors in the editor, although, the camera issue is still present when running on the HoloLens 1.

**Comment by davidkline-ms** [comment]
>Maybe it was just some weird caching error in Unity?

Sometimes, I find it helpful to delete the Library folder and let Unity recreate it. It pulls fresh copies of the packages too.

This one is up next on my backlog. Hope to have an idea of what you are seeing soon.

**Comment by davidkline-ms** [comment]
@KuraiAndras, I wanted to give an update on where I am investigating this (my apologies for the delay, i got prempted). Based on your original screen shot, I tried running using the Default HoloLens 1 profile in the editor using the following configuration:

* Unity 2019.4.12f1
* MRTK Foundation package (2.5.0) via UPM
* Windows Mixed Reality package (4.2.3) via UPM
* Enable Virtual Reality in Player settings
* DefaultHoloLens1ConfigurationProfile

I did not receive any errors re: broken profiles (I would be very interested to learn what you are seeing here). Also, i had no errors in the console.

My next step will be to deploy to a HoloLens 1 and confirm i see no debug messages and that i can walk around the cube (rather than the image being statically locked).

![image](https://user-images.githubusercontent.com/13281406/95620387-f32f5d00-0a24-11eb-9084-f53a96caa376.png)

**Comment by KuraiAndras** [comment]
@davidkline-ms 
This is what I see when I select the DefaultHoloLens1ConfigurationProfile:

![image](https://user-images.githubusercontent.com/19240945/95621349-d1a89280-0a71-11eb-8186-566a10053538.png)

Starting the application with the default profile:

![image](https://user-images.githubusercontent.com/19240945/95621412-edac3400-0a71-11eb-947b-54f73ce7a134.png)

**Comment by KuraiAndras** [comment]
Version stuff:
- Unity 2020.1.8
- MRTK 2.5.0 via UPM
- Windows XR Plugin via UPM 3.3.1 (I can't seem to find the Windows Mixed Reality package your mentioned?)
- Enabled Virtual reality in player settings

**Comment by davidkline-ms** [comment]
Ahhh. thank you for the corrections. I will test again!

**Comment by davidkline-ms** [comment]
> (I can't seem to find the Windows Mixed Reality package your mentioned?)

That package was deprecated in Unity 2019 and removed in 2020.1

**Comment by KuraiAndras** [comment]
Sorry, i did not want to close the issue, I pressed the wrong button

**Comment by davidkline-ms** [comment]
I JUST realized.... Our default profiles are designed for Unity 2018.4 users (and 2019.4 when using the legacy XR pipeline).

2020.1 no longer supports that and the XRSDK profiles are required.... Let me confirm which we have and ensure we have a full set.

**Comment by davidkline-ms** [comment]
@KuraiAndras, can you try using the DefaultXRSDKConfigurationProfile? The diagnostics system will not launch by default (I modified the profile on my project and will enable it in my PR).

![image](https://user-images.githubusercontent.com/13281406/95631740-0e0bcc80-0a39-11eb-8d72-e40712d8d0ba.png)

**Comment by davidkline-ms** [comment]
the warning i have is that i did not set my rendering to single pass instanced and is not related to what you are seeing

**Comment by KuraiAndras** [comment]
In the editor I no longer get warnings or errors, I'll try a build with the HoloLens emulator.

**Comment by keveleigh** [comment]
@KuraiAndras Here's some additional information about MRTK on 2020 with the new XR pipeline: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html

**Comment by davidkline-ms** [comment]
I will definitely create HoloLens 1 and HoloLens 2 versions of the XRSDK default profile, thought the umbrella one should work (just has more features enabled by default)

**Comment by KuraiAndras** [comment]
@davidkline-ms I tried the build in the hololens 1 emulator and it works! Thank you.
What will be the resolution of this? Will you provide a different default setting in 2.5.1?

**Comment by davidkline-ms** [comment]
I will provide mirrors of the DefaultHoloLens*ConfigurationProfile assets for XRSDK as a convenience.

Glad it is working for you!

**Comment by keveleigh** [comment]
Updated our docs as part of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9185, which will hopefully resolve confusion! We'll also be working on improving profile compatibility across XR backends and Unity versions.
