### ISSUE TITLE
Changing MRTK profiles at runtime before MRTK initialization does not work

### ISSUE THREAD

**Issue by dl4mmers** [microsoft/MixedRealityToolkit-Unity#8737]
## Describe the bug

[This part in documentation](https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.5.0/Documentation/MixedRealityConfigurationGuide.html#swapping-profiles-prior-to-mrtk-initialization) says that it's possible to change the MRTK profile before MRTK initialization. I created a script that sets active profile to another profile than in the MRTK object in my scene. Then I set the script to a higher priority than MRTK in script execution order. Then when pressing Play in Unity Editor the following errors are thrown and MRTK profile remains the same:

```
There's already a IMixedRealityInputSystem.Mixed Reality Input System registered!
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(Type, IMixedRealityService) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:893)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(IMixedRealityInputSystem) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:919)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(Boolean, Type, SupportedPlatforms, Object[]) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:275)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterService(Type, SupportedPlatforms, Object[]) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:196)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:410)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeNewProfile(MixedRealityToolkitConfigurationProfile) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:123)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:689)
``` 

``` 
Failed to start the Input System!
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:412)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeNewProfile(MixedRealityToolkitConfigurationProfile) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:123)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:689)
``` 

``` 
There's already a IMixedRealityFocusProvider.Focus Provider registered!
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(Type, IMixedRealityService) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:893)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(IMixedRealityFocusProvider) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:919)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(Boolean, Type, SupportedPlatforms, Object[]) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:275)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterService(Type, SupportedPlatforms, Object[]) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:196)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:416)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeNewProfile(MixedRealityToolkitConfigurationProfile) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:123)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:689)
``` 

``` 
Failed to register the focus provider! The input system will not function without it.
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:418)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeNewProfile(MixedRealityToolkitConfigurationProfile) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:123)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:689)
``` 

## To reproduce

1. Create Unity scene with MRTK standard assets
2. Create a script that changes the MRTK profile like in [this example](https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.5.0/Documentation/MixedRealityConfigurationGuide.html#swapping-profiles-prior-to-mrtk-initialization).
3. Set the script to a higher priority as MRTK in Unity script execution order.
4. Press Play in Unity
5. See the errors above printed
6. See that MRTK profile has not changed

## Expected behavior

The MRTK profile should be changed.

## Your setup (please complete the following information)

- Unity 2019.4.11f1
- MRTK 2.5.0

## Target platform (please complete the following information)

- HoloLens 1
- HoloLens 2

## Additional context

It would be nice to only have one scene that can be build for both HoloLens 1 and HoloLens 2. Currently I am using two equal scenes with different profile configurations for HoloLens 1 and HoloLens 2. Every change in a scene must be manually copied to the other scene and vice versa.

**Comment by keveleigh** [comment]
>It would be nice to only have one scene that can be build for both HoloLens 1 and HoloLens 2. Currently I am using two equal scenes with different profile configurations for HoloLens 1 and HoloLens 2. Every change in a scene must be manually copied to the other scene and vice versa.

What are the differences you need between the profiles?

**Comment by dl4mmers** [comment]
The profile for HL1 is based on DefaultHoloLens1ConfigurationProfile and the profile for HL2 is based on DefaultHoloLens2ConfigurationProfile. Differences are in speech commands, eye tracking enabled for HL2 and input simulation. Is it possible to handle these things for both devices in one profile? It's also important to have the maximum possible performance, because we are using MRTK along with MixedReality-WebRTC for audio and video calls.
