### ISSUE TITLE
SupportedControllerType is not extendable 

### ISSUE THREAD

**Issue by N0RAIR** [microsoft/MixedRealityToolkit-Unity#8746]
## Describe the problem

I want to add a custom input controller. To propetly do that, I need to add/extend the Enum **_SupportedControllerType_**. 
Until v2.4 I was manually changing the _**SupportedControllerType.cs**_ file. Now with MRTK 2.5 I want to use the UPM, but then I can't change the file. 

## Describe the solution you'd like

I would like to have a profile or something similar, so I can easily add new enums (e.g. like we can do with Input Actions)

## Describe alternatives you've considered

Currently, If I want to use MRTK 2.5, I need to go the old way with the .unitypackage which should be avoided.

**Comment by keveleigh** [comment]
I'm going to close this issue out in favor of using https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4239 to track. I'm working on this for 2.6.
