### ISSUE TITLE
Clipping Primitive: Support operating on SharedMaterial as well as MaterialInstance.

### ISSUE THREAD

**Issue by jwittner** [microsoft/MixedRealityToolkit-Unity#8751]
## Describe the problem

Currently ClippingPrimitive works by creating a new instance of each Renderer's material and applying changes to that. This avoids mucking with materials that could be shared, but it means that in cases where we're rendering many of the same objects with the same materials we lose our automatic batching of those objects if we want to clip.

## Describe the solution you'd like

If there were an exposed field in the Clipping Primitive classes to control the behavior in different circumstances we could ensure that batching continues in cases where we know the materials are only shared amongst all the objects being clipped. This would mean that with a little material/asset management, significantly larger quantities of objects could be clipped than today.

## Describe alternatives you've considered

* Writing our own custom clipping based on the MRTK.
* Copying the code out of the MRTK and making the required modifications ourselves.

CC: @Cameron-Micka

**Comment by jwittner** [comment]
I've done some testing and was able to :

* Add a boolean 'ApplyToSharedMaterial' to a fork of `ClippingPrimitive`
  * This prevents using `MaterialInstance` and toggles the feature on the `Renderer.sharedMaterial` instead.
  * Note: Still applies `MaterialPropertyBlock` changes to Renderer.
* Modify the `MixedRealityStandard/Gui` to use `INSTANCING_ON` rather than `_INSTANCED_COLOR` and instance
  * _Color
  * Clipping information if `_CLIPPING_*` is defined

This allows me to have dynamic colors for every object and clip the objects against shared volumes and still have Unity automatically use GPU instancing to render the objects - no custom DrawPrimitive calls required. If we're interested in this solution I can start crafting a PR to support it. CC: @Cameron-Micka

**Comment by Cameron-Micka** [comment]
I love this, I thing a PR for this would be valuable!
