### ISSUE TITLE
Visual Studio build failed after migrating from 2.4 to 2.5

### ISSUE THREAD

**Issue by Aupuma** [microsoft/MixedRealityToolkit-Unity#8754]
## Describe the bug

After migrating my project from 2.4 to 2.5 following the MRTK guide, I've tried to make a build with Visual Studio and it fails with two different errors: MSB3073 and C1007

## Screenshots

![Anotación 2020-10-06 151343](https://user-images.githubusercontent.com/22346231/95206056-84fd5700-07e6-11eb-80f3-13fe37fe666b.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.4f1
- MRTK Version v2.5

## Target platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
@Aupuma what version of Visual Studio are you using? I think you're hitting an issue with the ARM64 workaround, I'm wondering if you're either on a version that is so old that it doesn't know that flag, or on a newer one where the issue maybe is fixed and the flag is also donezo.

**Comment by Aupuma** [comment]
> @Aupuma what version of Visual Studio are you using? I think you're hitting an issue with the ARM64 workaround, I'm wondering if you're either on a version that is so old that it doesn't know that flag, or on a newer one where the issue maybe is fixed and the flag is also donezo.

Thanks, upgrading to the latest VS Update (16.7.5) solved it!
