### ISSUE TITLE
Improve the loading time of VS 2019 (16.7.5) from Unity 2019.4

### ISSUE THREAD

**Issue by eusebiu** [microsoft/MixedRealityToolkit-Unity#8762]
## Describe the problem
After updating to MRTK 2.5.0 (from 2.4.0) opening Visual Studio 2019 (16.7.5 - no additional extensions) from Unity 2019.4.11 is quite slow (~2 mins on 8 core CPU @ 2.6GHz, 32 GB RAM, GTX 1070) - the Editor is using ~20% CPU and it is frozen.

I noticed that this happens only if I switch the platform to UWP and add some examples. In this case, the number of projects in the solution is 66 (in my case I also use LeapMotion). I see that all packages with sources are loaded, including MRTK (e.g. Unity.Burst.Player, Unity.RenderPipelines.Core.Runtime.Player, etc. even if all checkboxes are unchecked in Preferences/External tools).

## Describe the solution you'd like
The VS solution should be opened in a couple of seconds, as in the Standalone platform.

## Describe alternatives you've considered
None.

## Additional context
I removed all .csproj files and restarted Unity and it appears that Unity is regenerating all of them each time I restart it (maybe not regenerating as the timestamp is not changed).

**Comment by tmhab** [comment]
Might be related to this Unity issue: https://issuetracker.unity3d.com/issues/compilationpipeline-project-recompile-and-package-changes-takes-a-long-time-when-project-includes-a-lot-of-packages

**Comment by davidkline-ms** [comment]
> In this case, the number of projects in the solution is 66

I would not expect there to be anywhere near that many projects in the Visual Studio solution when using UPM. I will take a look and see if I can get a repro.

**Comment by eusebiu** [comment]
Yep, it is quite frustrating to double click on a script and to wait 2 minutes each time for VS to open.
![image](https://user-images.githubusercontent.com/414589/95628777-6073da00-0a87-11eb-81a0-dcb977163481.png)

**Comment by FejZa** [comment]
I got the same issue on one of my machines. Cloning said project on another machine did not have this issue. Haven't found a stable way to reproduce or fix this yet.

**Comment by tmhab** [comment]
I have the same issue. I started using MRTK 2.5.0 with Unity 2019.4.10f through UPM.
As a test, I removed the UPM version of MRTK 2.5.0 and imported the .unitypackage version of MRTK 2.5.0, after that, I deleted the many .csproj files (and the .sln file) from project root.

Creating a new script and opening it regenerated all the .csproj and .sln files and opening the project took almost exactly 1 min. Too long time obviously.

**Comment by Xan2063** [comment]
We are facing the same issue since 2.3. A lot of projects (.player as well with a old c#-version, so they never compile).
Very long loading times as well. So if someone finds a solution, we are happy to know.

**Comment by eusebiu** [comment]
I think this happens only when the platform is UWP. For Standalone or Android, the number of projects is way smaller. Maybe this is related to IL2CPP?

**Comment by davidkline-ms** [comment]
@eusebiu, looking at your image again, it appears you may have Player Projects selected in Preferences.

![image](https://user-images.githubusercontent.com/13281406/113443331-9cd52280-93a6-11eb-80d0-d7432624054a.png)

If not, please delete your build folder, rebuild in Unity and see if the solution continues to contain them. If so, please re-open this issue.

Thanks!
