### ISSUE TITLE
Several unintended dependencies in 2.5

### ISSUE THREAD

**Issue by brandf** [microsoft/MixedRealityToolkit-Unity#8763]
## Describe the bug
Presumably foundation, extensions, and tools, should not depend on examples, but they do:

Tools\ControllerMappingTool\ControllerMappingTool.unity depends on Examples/StandardAssets/Prefabs/SceneDescriptionPanelRev.prefab, but package dependency is missing.

Extensions\Samples~\HandPhysicsService\HandPhysicsServiceExample.unity, that depends on Examples/StandardAssets/Prefabs/SceneDescriptionPanelRev.prefab, but package dependency is missing.

Foundation\SDK\Features\UX\Interactable\Materials\MRTKStandardUnityUI.mat, that depends on Examples/Experimental/Dwell/Circle.png, but package dependency is missing.

... and about 250 others like this.

## Expected behavior

Packages should declare their dependencies for any assets within the package.  In this case, I don't think they are intended, so assets should be moved to the appropriate place.

## Your setup (please complete the following information)

- Unity Version: 2019.4 LTS
- MRTK Version: 2.5

**Comment by davidkline-ms** [comment]
Thank you for filing this! I will investigate and update asap.

**Comment by brandf** [comment]
FWIW, the tool I have to detect these issues (sorry I can't contribute it) isn't too different from what you already have in the MRTK dependency window.  It just goes through every package & asset, finds all it's dependencies by guid, and then checks that those dependencies are reflected either directly or indirectly in the packages dependencies.

It may be worth investing in similar tooling.  It only took me an afternoon to make, and has saved me countless times (my project is like 30 packages, so it's impossible to manage manually).

**Comment by davidkline-ms** [comment]
The result of this work will be a new step in the pr validation pipeline to help ensure that incorrect cross package dependencies are not introduced,
