### ISSUE TITLE
Oculus profile would not save between unity instances after running integration tool

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#8768]
## Describe the bug
The Oculus integration tool's changes to the device manager profile would not get saved between closing and opening unity instances.

## To reproduce
1. run Mixed Reality Toolkit > Utilities > Oculus > Integrate Oculus Integration Unity Modules
2. verify that the OculusXRSDKDeviceManagerProfile has valid gameobjects set in the Prefab References category
3. close Unity
4. reopen Unity and see that the OculusXRSDKDeviceManagerProfile changes were not saved

**Comment by keveleigh** [comment]
Fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8769
