### ISSUE TITLE
Unity 2017.2.0b8 has some breaking changes to the HTK

### ISSUE THREAD

**Issue by jessemcculloch** [Microsoft/MixedRealityToolkit-Unity#877]
Upgrading to 2017.2.0b8 has surfaced a few types that have changed names or I just can't find.  To repro, just start a new project, and import the Dev_Unity_2017.2 version of the HTK, and the errors will surface themselves.

**Comment by keveleigh** [comment]
I have these changed in a local branch, so I can put out a pull request now.

**Comment by StephenHodgson** [comment]
There are lots of regressions in the beta 8 patch, it only addresses the security fix.

**Comment by keveleigh** [comment]
Where do you see an announcement that regressions are present? These changes align with my expectation as announced by Unity:

> XR: Updated interfaces and new data for GestureRecognizer and InteractionManager (UnityEngine.VR.WSA.Input). Some of the API surface for this has breaking changes on the way and will land soon.

**Comment by StephenHodgson** [comment]
> XR: Updated interfaces and new data for GestureRecognizer and InteractionManager (UnityEngine.VR.WSA.Input). Some of the API surface for this has breaking changes on the way and will land soon.
That was already addressed in b7.

B8 diff from B7
> **Improvements**
> XR: XRDevice.SetTrackingSpaceType will now allow users to reason about where the floor is on VR HMDs for WindowsMR.
> **Fixes**
> Editor: Fixed exception when backspacing iOS target SDK version in PlayerSettings inspector.
> Editor: Fixed Security Vulnerability UNITY-SEC-844 - https://unity3d.com/security
> Physics: Ensure no work is done if the 2D physics world is empty. (940666)
> XR: Performance and stability during in-editor remoting has been improved for the HoloLens. (901423)

**Comment by keveleigh** [comment]
b7 didn't have any API changes: #873 

It's strange that these API changes aren't called out in the release notes, but I've been using versions of Unity with these APIs from before the security vulnerability was found (8/13, according to that security page). See my old commit from the 10th (incorrectly labeled b7 updates as I misunderstood which version these APIs would be released in, and only found in my fork to compare against my b8 PR): b082656a7f368333f406440f80d85e7dc649b11a

**Comment by jessemcculloch** [comment]
I agree with @keveleigh - These changes appeared in b8 even though they are not called out in the release notes.  I was using a previous pull of the HTK MR Build in b7 and it was working fine
