### ISSUE TITLE
XRMeshSubsystem.GenerateMeshAsync crashes Unity

### ISSUE THREAD

**Issue by brandf** [microsoft/MixedRealityToolkit-Unity#8770]
## Describe the bug

I'm trying to use Holographic Remoting with XR Management and the XRMeshSubsystem on a HoloLens2.  I'm not using GenericXRSDKSpatialMeshObserver.cs, but doing something similar.  I'm able to get back various meshid's via TryGetMeshInfos, so it looks like it's suppose to work, however when I call GenerateMeshAsync  Unity crashes.

## To reproduce

call XRMeshSubsystem.TryGetMeshInfos to get a valid MeshId.
call XRMeshSubsystem.GenerateMeshAsync with this meshID, mesh, and mesh collider and *MeshVertexAttributes.None* to get a crash.

Note: I don't need/want normals - so I was assuming I could pass MeshVertexAttributes.None to just get positions...if I do this it crashes.

## Expected behavior

Unity never crashes.  It should generate the requested mesh with just positions, or return a failure without crashing if that's not supported.

## Your setup (please complete the following information)

- Unity Version 2019.4
- MRTK Version 2.5

## Target platform (please complete the following information)

- HoloLens 2 / Holographic Remoting

## Additional context

========== OUTPUTTING STACK TRACE ==================

0x00007FFDADF95D6E (WindowsMRXRSDK) UnityWindowsMR_session_resume
0x00007FFDADF6649C (WindowsMRXRSDK) ReleaseAllSourceStates
0x00007FF616327AA6 (Unity) XRMeshingSubsystem::AcquireMeshRouter
0x00007FF61632D554 (Unity) xr::ProcessMeshJob
0x00007FF6158828B1 (Unity) JobQueue::Exec
0x00007FF61588925B (Unity) JobQueue::Steal
0x00007FF6158830C3 (Unity) JobQueue::ExecuteJobFromQueue
0x00007FF615884C13 (Unity) JobQueue::ProcessJobs
0x00007FF61588A2AF (Unity) JobQueue::WorkLoop
0x00007FF615DDB393 (Unity) Thread::RunThreadWrapper
0x00007FFDDAA97BD4 (KERNEL32) BaseThreadInitThunk
0x00007FFDDB88CE51 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

A crash has been intercepted by the crash handler. For call stack and other details, see the latest crash report generated in:
 * C:/Users/brandf/AppData/Local/Temp/Unity/Editor/Crashes

**Comment by keveleigh** [comment]
Which version of Windows XR Plugin are you using? I thought I had seen this fixed in recent releases (maybe 2.3.0+?)

**Comment by brandf** [comment]
I'm on 2.3.0

**Comment by brandf** [comment]
To be clear.  It works just fine if you pass MeshVertexAttributes.Normals.  I just didn't need normals so I was passing MeshVertexAttributes.None, and this is what caused the crash.  It also preproduced with a player build on the HL2 device (as well as remoting).

**Comment by keveleigh** [comment]
Have you filed a bug with Unity about this? I can raise the priority on it if you have

**Comment by keveleigh** [comment]
@brandf Can you confirm if you're still hitting this? Looks like for Unity 2019 this was fixed in 2.3.1

**Comment by keveleigh** [comment]
This should be fixed across the latest Windows XR Plugin releases!
