### ISSUE TITLE
Crashreport: HolographicCameraRenderingParameters depth buffer commit error

### ISSUE THREAD

**Issue by Markovicho** [microsoft/MixedRealityToolkit-Unity#8775]
## To reproduce

Error appeared after upgrading from MRTK 2.4 -> 2.5. It only happend once and with no connection to specific events odr actions. So it's hard trying to reproduce it.

At least this is what i could see in the console:

`Camera pose from main camera - world management may ....
HolographicCameraRenderingParameters from main camera for updating rendering
HolographicCameraRenderingParameters from main camera for depth buffer commit.Error
`

## Screenshots

![20201008_191557_HoloLens](https://user-images.githubusercontent.com/11967926/95552609-44335700-0a0d-11eb-9708-94b1bb7b8bb0.jpg)

## Your setup (please complete the following information)

- Unity Version : 2019.4.12f1
- MRTK Version: 2.5.0
- Legacy VR Pipeline

## Target platform (please complete the following information)

- HoloLens

## Additional context

I never investigated this error before. The application itself was completely untouched . I upgrade from MRTK 2.4.0 -> 2.5.0. Therefore i assume that this is related to an internal issue in the MRTK framework.

**Comment by keveleigh** [comment]
This is an internal Unity error. Are you still seeing it? It _should_ be an uncommon case to get into, possibly at lower frame rates. I'm going to close this issue as external, but feel free to add more info!
