### ISSUE TITLE
UPM: Upgrading shaders for Universal Render Pipeline does not persist

### ISSUE THREAD

**Issue by FejZa** [microsoft/MixedRealityToolkit-Unity#8783]
## Describe the bug

When MRTK is installed via UPM upgrading the MRTK Standard shader for Universal RP will only update materials for the current sessoin. Once Unity is restarted the shader/materials are back to the legacy mode.

## To reproduce

1. Import MRTK via UPM
2. Upgrade shaders/materials
3. Restart Unity
4. Materials are not working with URP again

## Expected behavior

The upgrade persists.

## Your setup (please complete the following information)

- Unity 2019.4 LTS
- MRTK 2.5
- Import via UPM

**Comment by Kent1LG** [comment]
Got it too!

**Comment by keveleigh** [comment]
Ahh @Cameron-Micka, does this step edit the shader file directly?
@davidkline-ms might be another asset we'll need to import into the Assets folder.

**Comment by Cameron-Micka** [comment]
@keveleigh yes it does! It changes two lines in the shader: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/06a06778e38da622b37cc299a93f16e143b7bdeb/Assets/MRTK/Core/Inspectors/MixedRealityStandardShaderGUI.cs#L781

**Comment by davidkline-ms** [comment]
@keveleigh @Cameron-Micka thanks for the info.

I would love to not require importing unless the customer needs to update to URP. Any thoughts on how to do that given the constraints of UPM?

**Comment by davidkline-ms** [comment]
fixed with #8804
