### ISSUE TITLE
Tap to Place Sharing

### ISSUE THREAD

**Issue by reillydonovan** [Microsoft/MixedRealityToolkit-Unity#879]
Hi, is there a simple way to modify the tap to place script so it is supported across shared sessions?  I'd like for people to see each other pick up, move, and place holograms.

**Comment by TinyTangS** [comment]
I had tried to using the "UNetSharedHologram.CS" which is coming from the Spectator View sample.But  there is a problem. In the server you can tap and place the model at where you want ,the client also can see where it is . On the contrary the client tap and place the model, the server has no reaction. I want using this scripts for my project, how can I deal with it ?

**Comment by chrisfromwork** [comment]
@reillydonovan are you still looking for an answer to this question? There are a few working groups actively looking into HoloLens shared experiences. Your described scenario can be brought into upcoming discussions around desired shared experiences.

**Comment by Yoyozilla** [comment]
We will consider this in the new sharing platform features.
