### ISSUE TITLE
if shut down handray  .then air tap is not able to do .

### ISSUE THREAD

**Issue by dahaideyu** [microsoft/MixedRealityToolkit-Unity#8795]
## To reproduce

1. Go to build simple  example just close HandRay  
2.  air tap  no enable  event to clicked method 
 

## Your setup (please complete the following information)

- Unity Version 2019.4.6f and 2020.1.0f1c1
- MRTK Version  2.4  and 2.5

## Target platform (please complete the following information)

 
- HoloLens 2

**Comment by MaxWang-MS** [comment]
Are you expecting HoloLens 1 style interaction (cursor always in the middle, air tap to select) after turning off the hand rays? Also you can reply in Chinese if you prefer.

**Comment by dahaideyu** [comment]
是的，我希望那样做。因为手射线选择不够准确。希望头来选择点。然后手势确定是这个点。

**Comment by MaxWang-MS** [comment]
如果您程序中所有的交互都希望不使用hand ray的话，可以在MixedRealityToolkit GameObject -> Inspector -> Input -> Pointers -> Pointer Options里找到Prefab为DefaultControllerPointer的项目（应该在最上面），然后在controller type下拉菜单中去除Articulated hand。之后再在这个列表的最下方找到Prefab为GGVPointer的项目，然后在controller type下拉菜单中添加Articulated hand。如果您不知道如何修改profile的话请参阅https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Profiles/Profiles.html和https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/MixedRealityConfigurationGuide.html
更多信息请见这篇文档：https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Pointers.html#pointer-options-configuration
