### ISSUE TITLE
Popup Menu button issue

### ISSUE THREAD

**Issue by ali-siddiqui** [Microsoft/MixedRealityToolkit-Unity#880]
The first time I use the popup menu button it works fine. However, once I close the popup menu and try to activate it again it doesn't work and no other input works. Anyone else get this problem? Is it an easy fix?

**Comment by kewlniss** [comment]
There is an "easy" fix, but I'm not sure what else it breaks. One of my members found this a while back and I figured out the "fix", but forgot to raise an issue here for it.

In the DehydrationDeactivation.cs file under Input/Tests/Scripts the OnStateExit needs to be changed back to OnStateEnter. It was modified sometime in mid December if I remember correctly.

I believe this just affects the animation, but I'm not sure what else that change may break.

The change that caused the popup to fail to reopen was #401

**Comment by StephenHodgson** [comment]
@kewlniss I'll take a look, thanks for the report.

**Comment by kewlniss** [comment]
No problem, @StephenHodgson. Sorry I didn't bring this up back in April when it was brought to my attention. Here's a video just I uploaded that includes a clip from the Live Q&A where I talked about the issue in case it helps.
https://www.youtube.com/watch?v=zBe4GpE-dTY
