### ISSUE TITLE
Move ShaderUtilities from Foundation to Standard Assets

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#8806]
For the UPM distribution, MRTK 2.5.0 created the StandardAssets package to allow customers wishing to consume the MRTK shaders and other assets without consuming the MRTK itself.

This was done successfully with one omission.... The ShaderUtilities that are used for some features of the MRTK Standard Shader were not included. This was intentionally done to avoid a breaking change (the assembly containing the scripts would be required to change).

**Please comment** on this issue with your choice of the following:

1. Leave the ShaderUtilities in the Foundation until MRTK 3.x. Most of the features work without them, so a breaking change should be avoided,
2. Move the ShaderUtilities to the StandardAssets and leave the namespace the same in MRTK 2.6.0. It is better to have all shader resources in one place. Requiring developers to add an assembly is ok.
3. Rip the bandage! Move the ShaderUtilities, change the assembly AND the namespace.

Thanks!

**Comment by eusebiu** [comment]
A breaking change should be in a major version, hence, by this logic I would incline towards 1.
But if this change would fix some blocking issues, then I would incline towards 3.

**Comment by Tom-Wells-NW** [comment]
I would prefer option 3.

**Comment by davidkline-ms** [comment]
Shaders and their accompanying utilities are part of the Mixed Reality Graphics Tools package (for MRTK3). Any related script migration in MRTK2 will either not be performed or is already complete.
