### ISSUE TITLE
Windows Mixed Reality Headset not connecting to a new Unity project

### ISSUE THREAD

**Issue by Jaskerv** [microsoft/MixedRealityToolkit-Unity#8813]
## Describe the bug

Mixed Reality Headset does not connect to unity.

## To reproduce

1. Create new 3D Unity project 
2. Configure project and import MRTK with package manager.
3. Add scene and configure
4. Connect WMR headset
5. Press play.
6. Headset does not display/connect to unity.

## Expected behavior

WMR to connect to unity play instance.

## Your setup (please complete the following information)

- Unity Version 2019.4.12f1
- MRTK Version v2.5.0

## Target platform (please complete the following information)

- WMR immersive

## Additional context
Followed https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.5.0/Documentation/Installation.html except using the package manager to install MRTK.

**Comment by SimonDarksideJ** [comment]
Daft question, but have you checked your VR / XRSDK settings?  That's usually the first thing to verify if it only launches in 2D or only in the editor

**Comment by Jaskerv** [comment]
> Daft question, but have you checked your VR / XRSDK settings? That's usually the first thing to verify if it only launches in 2D or only in the editor

Are you referring to the XR Plug-in Management settings? I have enabled it for WMR. 

I think I just messed up somewhere when configuring the project.
