### ISSUE TITLE
Building the Hand Interaction Examples scene with XR SDK generates several Errors 

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#8824]
## Describe the bug

Building the Hand Interaction Examples scene with XR SDK generates several Errors in the Unity Console. I have been unable to reproduce this issue, but I took a picture of the errors and got the log from the project that generated these errors.

## Screenshots

![Screenshot 2020-10-20 161706](https://user-images.githubusercontent.com/65038391/96660282-ff0d0000-12fd-11eb-9356-56d7ca40b307.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.12f1
- MRTK Version 2.5.1-preview.20201019.2

## Target platform (please complete the following information)

- UWP
- HoloLens 2

## Additional context

Log file is here:
[errorsEditor.log](https://github.com/microsoft/MixedRealityToolkit-Unity/files/5412516/errorsEditor.log)

**Comment by polar-kev** [comment]
Closing since this is no longer relevant.
