### ISSUE TITLE
MRTK.Shaders.sentinel Naming Issue

### ISSUE THREAD

**Issue by adampsst** [microsoft/MixedRealityToolkit-Unity#8826]
## Describe the bug

When importing 2.5.1 (through UPM) into Unity (on Mac OS) you are unable to convert to the LWRP shaders, because the MRTK.Shaders.sentinel asset is named with a lowercase 's' instead of a capital 'S', which the OnLoadUtilities class is searching for.

## To reproduce

1. Import 2.5.1 packages through UPM
2. See error in console that cannot locate the sentinel asset

## Expected behavior

Should be able to locate the sentinel asset by using the correct naming convention, which should then import the shaders into the project.

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.1.8f1]
- MRTK Version [e.g. v2.5.1]

## Target platform (please complete the following information)

- Editor (Mac OS)

**Comment by ptc-ccrabb** [comment]
I plan to put up a PR to fix this
