### ISSUE TITLE
Scroll Object Collection works in editor but not on Hololens 2

### ISSUE THREAD

**Issue by dbarrett49** [microsoft/MixedRealityToolkit-Unity#8829]
## Overview
I was trying to create a pretty simple UI on the Hololens 2 using the scroll object collection. I got it working in the Unity editor just as I expected. I followed the documentation here:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_ScrollingObjectCollection.html

However, when I built it and deployed it to the Hololens 2 it didn't seem to work correctly. When I tried to scroll it just wouldn't scroll down at all. It would animate but essentially scroll all the way back to the top every time I tried to scroll down.

## Unity editor version
2019.15

## Mixed Reality Toolkit release version
2.5

**Comment by dbarrett49** [comment]
It seems I wasn't calling ScrollView.UpdateContent() weird how it works in the editor but not in the build.

**Comment by AlexPiro** [comment]
Thank you very much for posting the solution ! I was in the same case and AFAIK it's written nowhere that we need to UpdateContent() after some functions like MoveByTiers(). 
And the most weird is that it is working in the editor but not deployed in HoloLens 2...
