### ISSUE TITLE
OpenVR controllers are not tracked

### ISSUE THREAD

**Issue by eusebiu** [microsoft/MixedRealityToolkit-Unity#8835]
## Describe the bug

The OpenVR (HTC Vive) controllers are not tracked. The headset is tracked correctly.

## To reproduce

1. Install OpenVR XR SDK Plugin https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/installer
2. Activate OpenVR Loader in XR Plugin Management
3. Create a profile based on DefaultXRSDKConfigurationProfile - see below
4. Create an input profile - see below

## Expected behavior

Controllers are tracked but they are frozen.

## Screenshots
![image](https://user-images.githubusercontent.com/414589/96913860-de36dd00-14ac-11eb-91c6-b89f62dc9e98.png)
![image](https://user-images.githubusercontent.com/414589/96913898-ee4ebc80-14ac-11eb-84a6-f2caa219f36d.png)

![image](https://user-images.githubusercontent.com/414589/96914607-e2afc580-14ad-11eb-9907-709310ad9e6e.png)

## Your setup (please complete the following information)

- Unity 2019.4.11 - using XR SDK
- MRTK 2.5.1

## Target platform (please complete the following information)

- OpenVR (HTC Vive)

## Additional context

N.A.

**Comment by keveleigh** [comment]
We haven't yet tested support for Valve's OpenVR XR SDK plug-in. Can you try adding the original OpenVRDeviceManager? It's probable the data is still coming across the legacy input APIs for now, but I had heard that Valve's plug-in doesn't use the XR SDK [feature usage APIs](https://docs.unity3d.com/ScriptReference/XR.CommonUsages.html) for input, which is likely why you're seeing what you're seeing.

**Comment by eusebiu** [comment]
They also have a bug in the dlls configuration - https://github.com/ValveSoftware/unity-xr-plugin/issues/60 - but with an easy fix.

**Comment by eusebiu** [comment]
Added but no difference. If I remove the XRSDK Windows Mixed Reality Device Manager, the controllers (gizmo) disappear.

**Comment by eusebiu** [comment]
https://github.com/ValveSoftware/unity-xr-plugin/issues/16#issuecomment-662708512

**Comment by eusebiu** [comment]
After some research in SteamVR, it appears that MRTK needs a OpenVR XR SDK Device manager & controllers. 
Usint the  Windows Mixed Reality XR SDK profile will try to use the Unity XR SDK API which does return the correct values for pose and input data.

Basically, the `inputDevice.TryGetFeatureValue` on `BaseWindowsMixedRealityXRSDKSource` is not workting as it suppose to do.
It does work for GenericXRSDKController `inputDevice.TryGetFeatureValue(CommonUsages.devicePosition, out CurrentControllerPosition)` and rotation but not for `BaseWindowsMixedRealityXRSDKSource` inputDevice.TryGetFeatureValue(CustomUsages.PointerPosition, out currentPointerPosition) or `GenericXRSDKController` `inputDevice.TryGetFeatureValue(buttonUsage, out bool buttonPressed)`.

**Comment by eusebiu** [comment]
A first implementation of this can be seen here:
https://github.com/eusebiu/MixedRealityToolkit-Unity/tree/mrtk_development/Assets/MRTK/Providers/SteamVR/XRSDK

**Comment by stephenprosso** [comment]
The link to your example is broken. We are running into this same issue right now. Can you share your fix to get the controller to track?

**Comment by eusebiu** [comment]
> The link to your example is broken. We are running into this same issue right now. Can you share your fix to get the controller to track?

I've uploaded it here: https://1drv.ms/u/s!Aq1jgNgVNaunk3LGFzgZZItE12Aw?e=9wqLk9

For the sake of folder structure, you should put it in MRTK/Providers. Also, you will need to configure the manager with the SteamVR prefabs (similar to Oculus) - Player can be found here (after you import SteamVR): Assets\SteamVR\InteractionSystem\Core\Prefabs.
![image](https://user-images.githubusercontent.com/414589/117099940-251a5f00-ad7b-11eb-9104-2e15211665d7.png)

**Comment by stephenprosso** [comment]
awesome! I followed your instructions and now the controllers track (as VR gloves). I had an error that said I was missing my actions.json file and I was prompted to create one from the example. I did create one and the error went away. The controllers track my hand movements, but I do not have a raycast to select anything. What am I missing to get the ability to raycast and select objects?

Your SteamVRXRSDKdeviceManager is a lifesaver! thanks for your help!



![VR glove](https://user-images.githubusercontent.com/26071362/117171924-27cb8300-ad80-11eb-9d54-0e9d8bb9ecb6.PNG)

**Comment by eusebiu** [comment]
OpenVR plugin (the one from Package manager) is obsolete in the newer versions of Unity (I think in XR SDK projects). So you need to use SteamVR plugin, the one from the Asset Store (which will also be obsolete due to OpenXR).
The OpenVR XR plugin (the current one version 1.1.4) is part of the SteamVR Plugin (from asset store) and it will be automatically installed (N.B.: SteamVR plugin is not a plugin in the Unity sense).
For raycast you need to configure MRTK to hide the dummy controller - just clone the prefab and disable the Mesh Renderer (that's what I did). In your pictures I see that the ray is visible - see Pointer settings. So, in order to interact with objects, you need to add the MRTK scripts (like Interactable). 

![image](https://user-images.githubusercontent.com/414589/117185566-a35e1c00-ade2-11eb-9204-899bae6662b1.png)
![image](https://user-images.githubusercontent.com/414589/117185711-cd174300-ade2-11eb-92e5-500a8ca2e9dd.png)

In my case, the MixedRealityToolkit is configured as:
![image](https://user-images.githubusercontent.com/414589/117185157-35195980-ade2-11eb-8c48-97736dabc3b9.png)
![image](https://user-images.githubusercontent.com/414589/117185248-4ebaa100-ade2-11eb-8eda-3b38485d00b3.png)
![image](https://user-images.githubusercontent.com/414589/117185301-5e39ea00-ade2-11eb-8465-d9d67e496d6a.png)

**Comment by eusebiu** [comment]
Also, if you need to override the controls (e.g. to make the touchpad click to behave as the trigger - old VRTK style :) ), you will need to override the SteamVR actions json.

**Comment by stephenprosso** [comment]
I think my setting match yours, but my raycast still isnt working. Our objects should all be interactible already. Our app works on Oculus and HoloLens2 and now trying to get it deployed to the HTC Vive Pro Eye. 

when you say "For raycast you need to configure MRTK to hide the dummy controller - just clone the prefab and disable the Mesh Renderer (that's what I did)." I dont see where to hide the dummy controller. I do also see the raycast on the ground below my avatar but it is not connected to my hand. 

In my pointer settings I have "ShellHandRayPointer" selected. I do not have a DefaultControllerPo* as seen in your screen shot. My settings are as follows:
![1](https://user-images.githubusercontent.com/26071362/117190575-78e57200-ad94-11eb-8887-1692210e4c88.PNG)
![2](https://user-images.githubusercontent.com/26071362/117190576-797e0880-ad94-11eb-8ef1-d004e7a29419.PNG)
![3](https://user-images.githubusercontent.com/26071362/117190577-797e0880-ad94-11eb-9557-d8417db808a1.PNG)
![4](https://user-images.githubusercontent.com/26071362/117190579-797e0880-ad94-11eb-9408-39b3843cbf0d.PNG)
![5](https://user-images.githubusercontent.com/26071362/117190581-7a169f00-ad94-11eb-9bd6-ea408a3425f1.PNG)

**Comment by eusebiu** [comment]
I am referring to these settings. You can close  that prefab and then assign the clone in the profile. In the cloned prefab you can disable the Mesh Renderer component.
![image](https://user-images.githubusercontent.com/414589/117200990-cc87a800-adf4-11eb-9256-ebc36435e4fc.png)

I think the DefaultControllerPointer (the initial name) is the same as ShellHandRayPointer.

I think in your case the controllers are not detected correctly by MRTK - Try running the tool "Controller mappings profiles" from Mixed Reality Toolkit -> Utilities -> Update. If that does not work, then you will need to debug the SteamVRXRSDKdeviceManager to see why the controller is not created.
Normally, the MRTK controller (the prefab above) should align with and follow the SteamVR one (that comes from SteamVR Player).
Also, I forgot to mention that I am using a directive STEAMVR_INTEGRATION that needs to be setup in the Unity Player Project settings:
![image](https://user-images.githubusercontent.com/414589/117201980-f5f50380-adf5-11eb-9d3a-a09647c7a5f3.png)

**Comment by stephenprosso** [comment]
Where do I add the STEAMVR_INTEGRATION? I have looked through my Project Settings but cannot find the Script Compilation of the Script Define Symbols.

Thanks again!

**Comment by stephenprosso** [comment]
What if we dont want to use the glove hands and we just want to see the controllers?

**Comment by eusebiu** [comment]
> What if we dont want to use the glove hands and we just want to see the controllers?

I think you need to check SteamVR documentation for that - maybe their Player prefab has some settings for changing the hands though I think you will also need to do the rigging, animations, etc.

**Comment by stephenprosso** [comment]
Is it as easy as just typing in STEAVR_INTEGRATION? Or do i need to import a script from somewhere?

**Comment by eusebiu** [comment]
> Is it as easy as just typing in STEAVR_INTEGRATION? Or do i need to import a script from somewhere?

Just add it in that list - it's simply a preprocessing directive.

**Comment by eusebiu** [comment]
Will close this as we have a solution by using the custom SteamVR MRTK integration package - https://1drv.ms/u/s!Aq1jgNgVNaunk3LGFzgZZItE12Aw?e=9wqLk9

**Comment by methot-ilya-3ds** [comment]
From what I've seen this is the closest information there is out here for getting close to making the Vive work with MRTK. For all of the documentation claiming that Vive is supported I've found the opposite to be true. At best the controllers will track but pairing the input system with them seems near impossible.
