### ISSUE TITLE
Sharing service doesn't support loopback when server doesn't exist

### ISSUE THREAD

**Issue by XinliZ** [Microsoft/MixedRealityToolkit-Unity#884]
The SpanManager doesn't work if there is no server. 

I expect we could have a single user mode, where we could still work with only one device when server is not available, without writing another set of spawners. So the SpawnManager needs a single user mode, which is convenient to not needing a computer.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
