### ISSUE TITLE
Two bugs after having updated my project to MRTK 2.5.1

### ISSUE THREAD

**Issue by tomaszzackiewicz** [microsoft/MixedRealityToolkit-Unity#8849]
## Describe the bug

Hello,

Here is the bugs.

The first one appears when you restart Unity. You must set up Mixed Reality Toolit -> utilities -> oculus -> Integrate oculus....

GenericJoystickController controller should be created with no problem.

## To reproduce

1. Start Playing game in Unity

## Expected behavior

The first error should happen only once, and the second should not happen at all. 

## Screenshots

![image](https://user-images.githubusercontent.com/5631906/97280075-11c29000-183c-11eb-93e7-f146e7fa7289.png)

![image](https://user-images.githubusercontent.com/5631906/97281758-2c960400-183e-11eb-84cf-68df8539c1ee.png)

## Your setup (please complete the following information)

- Unity 2020.1.10f1
- MRTK 2.5.1

## Target platform (please complete the following information)

- Oculus Quest 1

## Additional context

I have just updated my project from the previous MRTK to MRTK 2.5.1.

**Comment by keveleigh** [comment]
Ah hmm, @RogPodge the first message might be related to the fact that profiles in the Packages folder can't be edited, so the flow introduced in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8557 isn't working.

**Comment by RogPodge** [comment]
yeah I can see how this can be an issue with UPM, I'll see if there's a better way to handle these prefabs and have things work better out of the box.

**Comment by tomaszzackiewicz** [comment]
Thank you for your comments. We use MRTK in our project and it is very useful, but there are some bugs that prevent us from implementing some features. In the previous MRTK version, we were unable to switch off/on teleporting, so we made a decision to upgrade the MRTK version to the newest. I removed the previous one and I got those errors. Hopefully, it will be possible to use it with Oculus Quest in Unity.

**Comment by keveleigh** [comment]
Partially fixed by #8861

**Comment by RogPodge** [comment]
Oculus side thing taken care of, not sure who should take up the generic joystick controller investigation. Some more details might be helpful here @tomaszzackiewicz

**Comment by keveleigh** [comment]
My guess for the others is that you'll want to upgrade to Unity's XR SDK / XR Management flow, since it looks like your profile has some missing types (the red highlighting) which matches types we're unable to load on Unity 2020 due to Unity's removal of them. [We have a guide](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html) with the steps required to do that.

**Comment by tomaszzackiewicz** [comment]
Well, I have all updated.
![image](https://user-images.githubusercontent.com/5631906/97690368-323d5500-1a9d-11eb-85e6-a96ab28cad9a.png)
And still the bugs. 
![image](https://user-images.githubusercontent.com/5631906/97690624-86483980-1a9d-11eb-8def-08e7198d039c.png)
Can I try out the new MRTK with this fix. Is it ready? Or are you going to apply more fixes?

**Comment by RogPodge** [comment]
I don't think we applied the fix yet to 2.5.1 @davidkline-ms

**Comment by RogPodge** [comment]
the oculus side PR got in and should be fixed now
