### ISSUE TITLE
Fail to compile under VS2017

### ISSUE THREAD

**Issue by Xispeo** [Microsoft/MixedRealityToolkit-Unity#885]
Hello,

Upgraded a couple of days ago Unity to 2017.1, HoloToolkit to MixedRealityToolkit release 1 and Visual Studio to 2017 and cannot compile under VS with the guideline workflow : 

2>CSC : error CS0006: Metadata file '***\Unity\WindowsStoreApp\GeneratedProjects\UWP\Assembly-CSharp-firstpass\bin\x86\Debug\Assembly-CSharp-firstpass.dll' could not be found
3>------ Build started: Project: AdB, Configuration: Debug x86 ------
3>CSC : error CS0006: Metadata file '***\Unity\WindowsStoreApp\GeneratedProjects\UWP\Assembly-CSharp-firstpass\bin\x86\Debug\Assembly-CSharp-firstpass.dll' could not be found
3>CSC : error CS0006: Metadata file '***\Unity\WindowsStoreApp\GeneratedProjects\UWP\Assembly-CSharp\bin\x86\Debug\Assembly-CSharp.dll' could not be found

**Comment by Xispeo** [comment]
So after having read workaround solutions I switched back to VS2015 and now have : 
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(52,62,52,64): error CS1003: Syntax error, ',' expected
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(88,17,88,21): error CS1547: Keyword 'void' cannot be used in this context
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(88,50,95,85): error CS1528: Expected ; or = (cannot specify constructor arguments in declaration)
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(88,50,88,51): error CS1003: Syntax error, '[' expected
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(88,102,88,102): error CS1003: Syntax error, '=>' expected
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(94,18,94,18): error CS1003: Syntax error, ',' expected
***\HoloToolkit\Utilities\Scripts\ApplicationViewManager.cs(95,85,95,86): error CS1003: Syntax error, ']' expected

So am switching back to previous HoloToolkit packages and will try your MixedRealityToolkit release 2 when it will be available. Lost 2 days ^^

**Comment by StephenHodgson** [comment]
@Xispeo, what version of Visual Studio are you using?

**Comment by TinyTangS** [comment]
I also happened with such problem，it confused me for two days. I had reinstalled VS2017 with 15.3 for many times,but it didn't work. I also tried to update the Unity , but the old project can't be opened without any questions. I had a very long way to find the solution(I also tried VS2015) . At last the VS2017 with 15.0 and the unity 5.6.2 works well in my computer, that is my way to solved this problem. I wish it may be helpful.

**Comment by Xispeo** [comment]
@StephenHodgson as indicated in my previous posts I tried with both VS 2017 and 2015. Universal module is installed, am not a newcomer with Hololens since I develop since a year on it, and have a project to get ready for an incoming demo. Sounds like there are problems with last Unity version and the toolkit.

@TinyTangS ty for your feedback, will help :)

**Comment by Xispeo** [comment]
Ok am sorted with Unity 5.6.3, HoloToolkit 1.5.8 and VS 2015.
Will try to update when next iterations of both Unity and MixedRealityToolkit will get released since I don't have the time to betatest atm.

**Comment by SinSeitan** [comment]
I just dont get why is allways so complicated to even do anything with the Hololens. Do you think they will thrive give all this errors and problems? Im just sickk of having to go through thousnads of tutorials, forums, chats, emails and so on every time Unity updates, or the HoloToolkit or the MRDL or visual studio... It is just SUPER UNSTABLE and a serious pain in the *** to do anything. I think Hololens will fail miserably due to all the constant difficulties.
BTW I was compiling no problem this afternoon, until sudenly it started throwing errors ive never seen before. Hope Holelns V.2 never come out. Seriously.

**Comment by StephenHodgson** [comment]
@SinSeitan I def understand how frustrated you are, but every new platform has its shares of issues and stability.  Yeah, there's been issues from the manufacturer, all the way through to the middle ware game engine, and even here in the community trying to solve the problems. (odd thing is that's what keeps me around 😅 ).

Please keep in mind this is a Gen1 device, that was never really intended to go beyond developers who wanted to play with it, and companies wanting to do a feasibility test.

> The only way to grow and learn is to make mistakes, the important thing is that you learn from them.

This quote couldn't be any more true, especially when it comes to software. The nice thing is that it's a continuous process to grow and learn, and they only way you really know that it's happening is when you make mistakes.  I'm glad to see the software getting better (and it has!).  Microsoft, Unity, and even the Toolkit have come a long way in the last two years.

> I'm just sick of having to go through thousands of tutorials, forums, chats, emails and so on.

I agree it is a pain, but I think the difference here is that you haven't talked to me, or other engineers trying to make your life easier by fixing some of the problems. This is the first time I've heard from you, so let's open a new issue and try to figure out what's going on.  Remember to follow the [Code of Conduct](https://opensource.microsoft.com/codeofconduct/faq/).  I understand you're frustrated, but having a positive attitude, even when you're stressed out or frustrated speaks volumes to others who are genuinely trying to help.
