### ISSUE TITLE
Rotating pinch slider shifts position of Thumb

### ISSUE THREAD

**Issue by SakaITa** [microsoft/MixedRealityToolkit-Unity#8856]
## Describe the bug

If you rotate the PinchSlider after launching the application, the Thumb shifts to the side.

## To reproduce

1. Open 'SliderExample' scene in MRTK Examples
2. Rotate 'PinchSliderColorRed' on Scene Window
3. Grabbing slider
4. Thumb shifts to side

## Expected behavior

Thumb does not move sideways when rotating.

## Screenshots

![shifts_position_of_thumb](https://user-images.githubusercontent.com/28783235/97391203-06e22b00-1922-11eb-9e08-21c63a332350.gif)

## Your setup (please complete the following information)

- Unity Version 2019.4.9f1
- MRTK Version v2.51

## Target platform (please complete the following information)

- HoloLens 2

**Comment by cre8ivepark** [comment]
Verified, when the scene is rotated (you can do this by grabbing the title bar of the description panel), then when you pinch and move the slider thumb, it shows the shift.
![2020-11-03 15_33_31-MRTK250 - HandInteractionExamples - Android - Unity 2019 3 13f1 Personal _DX11_](https://user-images.githubusercontent.com/13754172/97955704-27aaf480-1dea-11eb-9502-995b401e4b5c.png)
![2020-11-03 15_34_09-MRTK250 - HandInteractionExamples - Android - Unity 2019 3 13f1 Personal _DX11_](https://user-images.githubusercontent.com/13754172/97955711-2a0d4e80-1dea-11eb-82be-ea2cf08d9952.png)

**Comment by Glokta0** [comment]
I can also confirm this. 
The same behavior can be reproduced regardless of the axis used in the PinchSlider.cs script.

**Comment by Glokta0** [comment]
Current workaround: Only change the thumbRoot local Position.

1. Calculate newSliderPos in the given UpdateUI() method via:
```csharp 
var newSliderPos = GetSliderAxis() * (sliderValue - .5f) * Vector3.Distance(SliderStartPosition, SliderEndPosition); 
// ChosenSliderAxis * (sliderValue-.5) * Distance between start and end points (sliderThumbOffset should not be needed here.) 
// -.5f needed to allow 0 be the center of the slider track.
newSliderPos += initialLocalThumbRootPosition; // adding the initial Position of the ThumbRoot to position it on the slider.
thumbRoot.transform.localPosition = newSliderPos;
```

2. After storing the initial thumbRoot Position in start before initializing it via InitializeSliderThumb()
```csharp
            initialLocalThumbRootPosition = thumbRoot.transform.localPosition;
```


... not as pretty - but it allows to 
- rotate the object or any of its parents
- change SliderAxis on runtime (need to re-run visuals, or slider position only updates correctly on first interaction.)
- while keeping the rest untouched.

Hope this helps anyone if their experiencing this issue before 2.6! 🚀
