### ISSUE TITLE
The examples package does not contain the Hand Interaction Example scenes

### ISSUE THREAD

**Issue by Acimaz** [microsoft/MixedRealityToolkit-Unity#8857]
The Microsoft.MixedReality.Toolkit.Unity.Examples.2.5.1.unitypackage package does not contain the hand interaction example scene I was looking for. Setting up mrtk with UPM contains said scene.

**Comment by keveleigh** [comment]
Which scene are you looking for? I see HandInteractionExamples in the package: 
![image](https://user-images.githubusercontent.com/3580640/97469173-55cc9800-1903-11eb-949c-c69cd85249d3.png)
