### ISSUE TITLE
slider events poor documentation Documentation/README_Sliders.md

### ISSUE THREAD

**Issue by FelixWeichselgartner** [microsoft/MixedRealityToolkit-Unity#8881]
## Describe the issue
For me its seems still unclear how the slider events exactly work

## Feature area
How do you have to setup the slider object and the script in order to call the event functions like "OnValueUpdated". I understand that there is an example, however i stay have issues making it run in my program.

## Existing doc link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_Sliders.html
Documentation/README_Sliders.md

## Additional context
Maybe its possible to make a more detailed instruction.

**Comment by MaxWang-MS** [comment]
Have you been able to run the example scene successfully? That should be the first step. In the example scene if you click on a slider GameObject then look at the Inspector -> Pinch Slider you can see how the events are linked to functions etc. After that follow the instructions here: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_Sliders.html#how-to-use-sliders

**Comment by FelixWeichselgartner** [comment]
Hello, thank you for your response.
Yes I ran the example successfully and now I was also able to reproduce the event triggering.

Here the problem:
In the example, when I inspect the pinch slider, I somehow cannot see the linked function (it says no function I think) and generally the linked object also looks weird. This is why I didnt understand how I had to link the function in the first place. Got it working by trial and error now. I am using Unity 2018 LTS - I dont know whether that can be the issue why I didnt see linked functions. I will post a screenshot of the example and my version tomorrow.

Thank you.

**Comment by FelixWeichselgartner** [comment]
![image](https://user-images.githubusercontent.com/41804639/98211087-d1e96000-1f41-11eb-9a5f-b574eed322d9.png)

This is how the scene looked after I imported Foundation, Extension, Tools, Examples. Unity Version is 2018.4.24f1. 

Dont know where the error would be. Maybe I made some import mistakes. However the "no Function" confused me there.

Thank you for your help.

**Comment by MaxWang-MS** [comment]
Looks like the compilation error is causing the no function problem. Also based on the screenshot you are not using the latest version of MRTK (v2.5.1) right? I have tried the latest MRTK and was not able to reproduce the errors. Please use the 2.5.1 version and let me know if that resolves the issue. Should the issue persists, please tell us the target platform of your project (i.e. standalone or UWP or something else)

**Comment by FelixWeichselgartner** [comment]
I used MRTK v2.5.1. Build settings: Standalone for Windows x86_64.

**Comment by MaxWang-MS** [comment]
I was not able to reproduce using Unity 2018.4.26f1, MRTK 2.5.1 targeting Standalone for Windows. Did you update the MRTK version to 2.5.1 in an existing project? If so, please try creating a new and empty Unity project and import MRTK to see if the problem persists. If it doesn't, there might be something wrong during the update process. Try deleting the Library folder may help. You can also check our doc on how to update to a newer version of MRTK.

**Comment by RogPodge** [comment]
Closed with doc update
