### ISSUE TITLE
modular import of the project

### ISSUE THREAD

**Issue by hanseuljun** [microsoft/MixedRealityToolkit-Unity#8886]
## Describe the problem
MRTK is definitely the best framework for mixed reality. However, its willingness to tweak global settings and the sheer amount of functionalities it tries to provide combined to its reliance on native plugins (the native MRTK library) makes it look very scary. Combined this with the versioning issue that happens to all Unity libraries, I can easily imagine a situation I will need to rollback and reimplement things.

## Describe the solution you'd like

The issue can be divided into two. (1) There are side effects and (2) the framework is very large. While providing standard practice is understandable, for example, I do not think a library should try to tweak global setting regarding the rendering pass of an application, such as using single pass instanced rendering. The framework being large magnifies this issue. In case having side effects is unavoidable, making it into a set of smaller modules will be able to mitigate the issue. Also, the smaller number of modules leads to smaller number of native plugins, resulting in higher stability of applications, especially when they already have their own native plugins.

## Describe alternatives you've considered

As a person who wants to use the input system of this project, writing the UI system by myself... 

## Additional context

If this is actually already possible, first I would like to say sorry for bothering you all, and please let me know...

**Comment by Zee2** [comment]
Does the new UPM packaging system that was rolled out with MRTK 2.5 not allow for this?

I know that the new UPM setup allows for more modular installation of MRTK, but I don't know if it is sufficiently granular for your uses.

Have you looked at consuming MRTK through UPM?

**Comment by Zee2** [comment]
MRTK3 has been drastically re-architected to be distributed into a large number of independent packages. Check it out and let us know what you think!

**Comment by hanseuljun** [comment]
@Zee2 Thanks a lot!! I didn't expect to receive an answer such as this which is totally amazing!!
