### ISSUE TITLE
Objects not matching physical length

### ISSUE THREAD

**Issue by hummlj** [microsoft/MixedRealityToolkit-Unity#8893]
Objects appear not with the expected scale within the deployed programs. The difference in scale is as much as 20%.

## To reproduce:

* Add MRTK 2.5.1 to Unity (2020.1.3f1)
* Platform -> UWP, Device -> HoloLens
* Make a new scene in Unity
* MRTK -> Configure Unity Project
* MRTK -> Add to scene and configure
* Change to *DefaultXRSDKConfigurationProfile*
* 3D Object -> Cube -> scale (0.5, 0.5, 0.5) and position (0.0,0.0,2.0)
---
Compare the screenshot below. Basically all objects appear smaller than intended. 
 
## Expected behavior

As 1 unit in Unity translates to 1m in physical space, the cube should appear with edge length of 0.5m

## Screenshots

![20201102_193059_HoloLens](https://user-images.githubusercontent.com/40237504/97906430-eeb84480-1d43-11eb-9739-16de78b2bc19.jpg)
![image](https://user-images.githubusercontent.com/40237504/97906444-f4ae2580-1d43-11eb-9620-13cab296ffa8.png)
![image (1)](https://user-images.githubusercontent.com/40237504/97906458-f972d980-1d43-11eb-8428-5fcc389d4bf7.png)

## setup

- Unity Version 2020.1.3f1
- MRTK Version 2.5.1

## Target platform

- HoloLens 2

## Additional context

I did also run the eye calibration and tried various MRTK profiles.

**Comment by hummlj** [comment]
Just checked, same issue with Unity 2020.1.11f1.

**Comment by hummlj** [comment]
Also checked, Windows XR Plugin 4.0.2 installed

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8024

**Comment by keveleigh** [comment]
@hummlj Are you still seeing this? According to Unity's release notes, the issue should be fixed in 4.1.0 (which aligns with the 2.3.0 release mentioned in #8024)

**Comment by hummlj** [comment]
@keveleigh thanks for the reply. Yes, updating fixed the problem. I guess we could close this issue here.
Best
