### ISSUE TITLE
Occlusion Culling Too Early

### ISSUE THREAD

**Issue by Jaskerv** [microsoft/MixedRealityToolkit-Unity#8898]
## Describe the bug
Occlusion Culling popping objects in and out before it is completely out of view.

## Expected behavior

Occlusion culling to occur when objects are completely out of the view of the VR headset.

## Screenshots

![image](https://user-images.githubusercontent.com/26532014/98057199-93529780-1ea6-11eb-98a2-1b21a544ac2a.png)

![image](https://user-images.githubusercontent.com/26532014/98057276-cb59da80-1ea6-11eb-82e2-878dc9f81338.png)

See that the green object above is completely in view. If the camera is rotated in a certain angle, The green object is culled too early as shown below.

![image](https://user-images.githubusercontent.com/26532014/98057309-df054100-1ea6-11eb-9c5f-dc2dae2d6070.png)

Although these screenshots are taken within unity editor. While wearing the headset. Objects are still popping in and out.

## Your setup (please complete the following information)

- Unity Version 2019.4.12f
- MRTK Version 2.5.1

## Target platform (please complete the following information)

- WMR immersive

## Additional context

I have also set the far plane to 1000  and pre baked occlusion culling to no avail.

**Comment by keveleigh** [comment]
Which version of Windows XR Plugin are you using? This sounds like an issue that should be fixed in Unity's latest release (2.4.1).

**Comment by Jaskerv** [comment]
Looks like its fixed by upgrading from Unity Version 2019.4.12.f to 2020.2.0b9
