### ISSUE TITLE
Detect headset removed

### ISSUE THREAD

**Issue by o-mobile** [Microsoft/MixedRealityToolkit-Unity#890]
Can we detect if the headset has been removed?

**Comment by StephenHodgson** [comment]
Well you could check to see it the camera orientation is changing each update.  If it's not moving even a little bit then chances are it's not on someone's head.

**Comment by keveleigh** [comment]
I'm not sure how supported this is with HoloLens, but you can definitely use [XRDevice.userPresence](https://docs.unity3d.com/2017.2/Documentation/ScriptReference/XR.XRDevice-userPresence.html) with the immersive headsets. I believe this was added in Unity 2017.2.

**Comment by o-mobile** [comment]
Thanks for the help. This would be for an event where we need to detect it being removed and then put on again, so detecting movement is not ideal here. Thanks anyway.
