### ISSUE TITLE
BoundsControl FlattenY axis causes bounds control handles and wireframe to disappear. 

### ISSUE THREAD

**Issue by polygonfuture** [microsoft/MixedRealityToolkit-Unity#8904]
## Describe the bug

After attaching boundsControl on a game object in Unity, setting its FlattenAxis to Y axis, with bounding box padding on all axis, all bounds control handles and visual indicators become invisible, and I am unable to manipulate the object.

## To reproduce

Create Cube GameObject in Unity
Add Bounds Control to object

In Bounds Control Script:
Link GameObject to Target Object
Set Flatten Axis to Flatten Y

Visual configurations can be set or left default.  The same result occurs.

Enjoy results of missing bounds control handles.

## Expected behavior

FlattenAxis Y, Z, or X should flatten the display of the bounds control on that axis and prevent any scaling of that axis.  A flattened Y axis, should only allow scale to happen on the Y plane.    FlattenAxis Y, Z, or X should not cause the bounds control to go invisible.  This bug is hampering workflow on a project.
## Screenshots

![objectBoundsCOntrolIssue](https://user-images.githubusercontent.com/12026545/98185659-edad2180-1ec1-11eb-92a6-24951e9060be.PNG)

## Your setup (please complete the following information)

- Unity Version [2018.4.28f1 Personal]
- MRTK Version [v2.5]

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

FlattenAxis Y, Z, or X should flatten the display of the bounds control on that axis and prevent any scaling of that axis.   Flatten Auto works; however it allows for axis to be scaled in any direction.  This is not desirable.  With flatten auto it should be initialized only once, and then constrain scaling on that axis.

**Comment by MaxWang-MS** [comment]
Can you try using the latest MRTK release (i.e. 2.5.1) and let us know if the issue persists?

**Comment by polygonfuture** [comment]
Hi,  I can potentially test locally but this is for a production project that needs this to work on our current version base.

Is there any quick term fixes for this issue?   We're on a tight spring schedule and cant afford to investigate deeply.

**Comment by polygonfuture** [comment]
@MaxWang-MS Any word?  Is there a specific commit in which this was changed?  Is there any way I can apply a fix to V2.4?  We are on a production and cannot update mid project.

**Comment by MaxWang-MS** [comment]
@polygonfuture Please see the linked PR for the fixes for the first issue. You can try just getting the files I modified and apply them to a MRTK 2.5 project and I think there is a fairly high chance that it just works. For the second issue I am not sure I understand what you are describing, so if the issue does not go away with the fixes in the PR please elaborate more on that (pictures, gifs, videos or small repro will be helpful)
