### ISSUE TITLE
Plane Generation

### ISSUE THREAD

**Issue by qfliu** [Microsoft/MixedRealityToolkit-Unity#891]
(I am sorry if this should not be posted here. I tried to find a button to add "Question" L abel, but was unable to find it when I create this issue)

I am trying to get a surfacePlane for a wall in a room. I built my program based on the SpatialMapping/SpatialUnderstanding example from the HoloLenToolKit example. 

From my understanding, the scanning part is trying to figure our where you are in the already stored mesh in Hololens. Then, the planes are generated based on that mesh. Currently, when I face a wall and try to find a plane for that wall. It does not always give me the same plane. For the wall in front of me, there can be multiple plane generated and the result would depend on which plane is processed first. Then, I try to find the largest plane in front of me instead. However, there are planes that are similar size and the resulted plane is still inconsistent.

Is there a way to make sure you always find the same plane? I am currently using remote holographic to run my program due to some constraint, I am unsure whether that is the cause of the problem.

Thanks in advance.

**Comment by davidkline-ms** [comment]
There is no mechanism for ensuring that a generated plane is exactly the same as an earlier one. The HoloLens is continually updating it's understanding of the world, so refinements are almost inevitable.

One thing you COULD do is to scan the room, generate planes and anchor them for later use.
