### ISSUE TITLE
"Physics.ClosestPoint can only be used with a BoxCollider" - Continiously printed in the Log File

### ISSUE THREAD

**Issue by arunrajselvaraj** [microsoft/MixedRealityToolkit-Unity#8915]
## Describe the bug
After starting the application, the below exception fills the log file continuously 

## To reproduce

Always reproducible 

## Expected behavior

Not to print this 

## Screenshots
``
Physics.ClosestPoint can only be used with a BoxCollider, SphereCollider, CapsuleCollider and a convex MeshCollider.
UnityEngine.Collider:ClosestPoint(Vector3)
Microsoft.MixedReality.Toolkit.Input.SpherePointerQueryInfo:TryUpdateQueryBufferForLayerMask(LayerMask, Vector3, Vector3, QueryTriggerInteraction, Boolean)
Microsoft.MixedReality.Toolkit.Input.SpherePointer:OnPreSceneQuery()
Microsoft.MixedReality.Toolkit.Input.FocusProvider:UpdatePointer(PointerData)
Microsoft.MixedReality.Toolkit.Input.FocusProvider:UpdatePointers()
Microsoft.MixedReality.Toolkit.Input.FocusProvider:Update()
Microsoft.MixedReality.Toolkit.<>c:<UpdateAllServices>b__67_0(IMixedRealityService)
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:UpdateAllServices()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update()

## Your setup 

- Unity Version - 2019.4.12f1
- MRTK Version - v2.5

## Target platform 

- HoloLens 2

Thanks

**Comment by arunrajselvaraj** [comment]
This was due to internal issue in the project.

**Comment by JPhilC** [comment]
@arunrajselvaraj  I have this problem. If you don't mind me asking, what was the internal problem with your project?

**Comment by arunrajselvaraj** [comment]
@JPhilC I closed this bug by mistake. Still I are facing this issue.

**Comment by JPhilC** [comment]
Funnily enough this started happening for me when I changed the Managed Stripping Level from Low to Medium. I changed it back and the problem went away.

**Comment by derekdominoes** [comment]
This is occurring for me using the latest MKT3. It fills up my logs!
I have spline shaped meshes (road, wire, etc...) that need selecting thus have 'concave' Mesh Colliders.
The error is coming from the called to Physics.ClosestPoint inside "InteractorVisuals/ReticleMagnetism.cs:15"
Even though the error happens, everything seems to work fine (even the Reticle on the spline mesh seems correct).
Is there a way to turn off the Reticle Magnetism for certain Interactables?
Not sure how/where it gets enable?
As is, it makes my logs useless

Happens in the Unity Editor or on Oculus:
com.microsoft.mixedreality.openxr: 1.4.0
com.microsoft.mrtk.core: 3.0.0-development
com.microsoft.mrtk.extendedassets: 3.0.0-development
com.microsoft.mrtk.graphicstools.unity: 0.3.15
com.microsoft.mrtk.input: 3.0.0-development
com.microsoft.mrtk.spatialmanipulation: 3.0.0-development
com.microsoft.mrtk.standardassets: 3.0.0-development
com.microsoft.mrtk.uxcomponents: 3.0.0-development
com.microsoft.mrtk.uxcore: 3.0.0-development

**Comment by Zee2** [comment]
@derekdominoes thanks for bumping this. Sorry this fell in between the "couch cushions" so to speak. We'll take a look.

**Comment by Zee2** [comment]
This is almost certainly related to cursor magnetism.

**Comment by derekdominoes** [comment]
Not sure what it means to be added to a 6 week old milestone in your process?
The BUG still exists in the latest release so why mark as Closed?

com.microsoft.mixedreality.openxr: 1.5.1
com.microsoft.mrtk.core: 3.0.0-pre.11
com.microsoft.mrtk.extendedassets: 3.0.0-pre.11
com.microsoft.mrtk.graphicstools.unity: 0.4.0
com.microsoft.mrtk.input: 3.0.0-pre.11
com.microsoft.mrtk.spatialmanipulation: 3.0.0-pre.11
com.microsoft.mrtk.standardassets: 3.0.0-pre.11
com.microsoft.mrtk.uxcomponents: 3.0.0-pre.11
com.microsoft.mrtk.uxcore: 3.0.0-pre.11

**Comment by keveleigh** [comment]
@Zee2, is this the bug fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11096?

**Comment by Zee2** [comment]
Yep, #11096 fixed this. @derekdominoes, we close issues when the fix is merged, not necessarily packaged as a release. Stay tuned for pre.12!

**Comment by derekdominoes** [comment]
Thank you. It does look like the same bug. I'll stay tuned :)

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
