### ISSUE TITLE
System Keyboard: Tiping into TMP field mixes up the letter

### ISSUE THREAD

**Issue by Spoon2311** [microsoft/MixedRealityToolkit-Unity#8917]
## Describe the bug

When using the MRKeyboardInputField_TMP.prefab the keyboard opens as expected. When then typing the right letters appear but in a wrong order or sometimes even double. 
E.g. when tipping "Dave" the result can be "aeaevD", as shown in the screenshot below, or even more random.

Adding the TMP_KeyboardInputField.cs script to a TMP object creates the same behavior. (Just wanted to see if the prefab might have an issue)

## To reproduce

1. Go to Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/Prefabs/MRKeyboardInputField_TMP.prefab within MRTK in Unity
2. Add it to the scene
3. Deploy to HoloLens 2
4. Select the Text Field
5. The Keyboard appears
6. Type a word in to the Keyboard
7. The result in the Text Field

## Expected behavior

The expected behavior would be that the typing behavior is equal to when typing usually on a keyboard.

## Screenshots
![20201106_184903_HoloLens](https://user-images.githubusercontent.com/59868550/98398963-0c4a1e80-2062-11eb-80a7-0c32d66423b6.jpg)

The above mentioned behavior is shown in this screenshot.

## Your setup (please complete the following information)

- Unity Version 2019.4.13.f1 & 2019.4.12.f1
- MRTK Version 2.5 & 2.4

## Target platform (please complete the following information)
- HoloLens 2

**Comment by deckarComplex** [comment]
I just found out that closing and opening the keyboard bypass the problem. It only occurs reproducibly the first time the keyboard is opened.

**Comment by RichLogan** [comment]
I appreciate this is fixed upstream but if anyone comes here looking for a fix against Release like I did: switching to a standard non-TMP input field works fine for now.
