### ISSUE TITLE
Error not clearing after adding Holotoolkit

### ISSUE THREAD

**Issue by MrGaryB** [Microsoft/MixedRealityToolkit-Unity#892]
I'm getting an error I cant clear after adding the Holotoolkit to the Assets folder in Unity (5.6.1f1). I can't seem to clear it and therefore the menu isn't loading in Unity.

Can anyone help please?

Thanks

![2017-08-25 14_58_27-unity 5 6 1f1 personal 64bit - untitled - tutorial - pc mac linux standalon](https://user-images.githubusercontent.com/31349269/29717170-143c0a50-89a6-11e7-8f19-00cf241ce4ec.png)
![2017-08-25 14_58_40-unity 5 6 1f1 personal 64bit - untitled - tutorial - pc mac linux standalon](https://user-images.githubusercontent.com/31349269/29717171-143d59dc-89a6-11e7-8b2e-0348c4bffa61.png)
![2017-08-25 14_59_03-tutorial - microsoft visual studio](https://user-images.githubusercontent.com/31349269/29717172-145711c4-89a6-11e7-8b7e-d0343d3db8f6.png)

**Comment by MrGaryB** [comment]
Great thanks, I'll have a look now.

For info, I'm using 'HoloToolkit-Unity-v1.2017.1.0.unitypackage' downloaded from https://github.com/Microsoft/MixedRealityToolkit-Unity/releases just today?

**Comment by StephenHodgson** [comment]
Yeah it says it's for Unity 2017.1 not 5.6.

The 5.6 release is 1.5.8.0.

Please read the details of each release.
