### ISSUE TITLE
Spatial mesh problem on Windows XR Plugin

### ISSUE THREAD

**Issue by fast-slow-still** [microsoft/MixedRealityToolkit-Unity#8920]
## Describe the bug

When running on HoloLens using XRSDK (not legacy), a non-identity transform on the MixedRealityPlayspace (or any other transform in the camera's hierarchy) will cause the Spatial Awareness Mesh to fly off. A rotation will cause the spatial mesh to spin around the camera, a translation will be repeatedly applied causing the mesh to fly off in that direction.

## To reproduce

1. Set up an MRTK application (e.g. HandInteractionSamples) to run on Windows XR Plugin.
2. Make sure the spatial mesh is visible (in Spatial Awareness profile).
3. Set a small rotation (e.g. 5 degrees about Y) or translation (e.g. (0,-0.25,0)) on MixedRealityPlayspace transform.
4. On running, the spatial awareness mesh will animate incorrectly (it shouldn't "move" at all.)

## Expected behavior
Spatial awareness mesh remains fixed relative to the physical environment.

## Screenshots

If helpful, I can try to capture a video of the mesh moving around. But it should be very easy to repro.

## Your setup (please complete the following information)

- Unity Version 2019.4.2f1
- MRTK Version 2.5.1 (mrtk_development branch on Nov 7, 2020).

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by keveleigh** [comment]
Interesting...these meshes should end up under the SpatialAwarenessObjectParent, which itself should be under the Playspace: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/cf034fcb1981e2e9f5eaaad0d6ba97766e008df1/Assets/MRTK/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs#L182-L184

but it's possible XR SDK is missing a crucial step.

>When running on HoloLens using XRSDK (not legacy)

Are you saying this _does not_ repro with legacy?

**Comment by fast-slow-still** [comment]
Correct, it works fine on Legacy, since I fixed #4276.

I was going to offer to have a look at this in the XR SDK sync Wednesday.

**Comment by keveleigh** [comment]
@fast-slow-still Sounds good! Looking at that previous PR, interestingly in this case there isn't (currently) a spatial anchor involved.
