### ISSUE TITLE
Missing info on exact location/coordinates of the Main Camera on device while using MRTK

### ISSUE THREAD

**Issue by hferrone** [microsoft/MixedRealityToolkit-Unity#8927]
## Describe the issue
There isn't actually a true reference point that is determined as the origin for the Main Camera when using MRTK.

## Feature area
Exact location/coordinates of the Main Camera on the device (HL2) while using MRTK is missing.

## Existing doc link
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/CameraSystem/CameraSystemOverview.html

## Additional context
Step 1: Add in a small note in the existing CameraSystemOverview page that calls out the HoloLens as an example and mentions that the camera location at the start of the experience is 0,0,0, which then moves with the user.

Step 2: Need to create a simple article that explains the location of the camera and the scene origin (differs between AR/VR/Specific Platforms). Optionally, the new doc could also include the following:
What are intrinsics
	- What are extrinsics
	- What do they get used for / why would you use it
	- Basic matrix math / transformation math
	- basic sample showing a real world scenario

**Comment by polar-kev** [comment]
Camera location and differences between AR/VR/Specific platforms are covered at the Unity level as opposed to the MRTK level.
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/camera-in-unity

I'm not sure this is something we want to include in MRTK specific docs.

**Comment by hferrone** [comment]
No problem, i'm following up on this on the Unity side.
