### ISSUE TITLE
Add support for the Leap Motion Unity Modules 4.6.0, 4.7.0, and 4.7.1

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#8928]
Add support for the Leap 4.6 Unity Modules as MRTK only currently supports version 4.5.0 and 4.5.1 
https://github.com/leapmotion/UnityModules/releases/tag/UM-4.6.0

**Comment by slimshader** [comment]
ETA on the merge?

**Comment by CDiaz-MS** [comment]
@slimshader The PR has been merged.
