### ISSUE TITLE
Articulated hand tracking not working with Holographic Remoting on Unity 2019.4.5f1

### ISSUE THREAD

**Issue by Ozelotl** [microsoft/MixedRealityToolkit-Unity#8930]
## Describe the bug

I have the same issue as 8747 or 8132: Articulated Hand Tracking does not work over holographic remoting, even if enabled, no hand joint/mesh visualization is visible in device, interactions don't work as expected.

Additionally, I tried all the troubleshooting steps mentioned there and outlined 
[in the MRTK Documentation](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html)

## To reproduce

I have uploaded reproduce Unity projects here:
[https://github.com/Ozelotl/MRTKBugReproProjects/releases/tag/release](https://github.com/Ozelotl/MRTKBugReproProjects/releases/tag/release)
One with all setup steps up for automatic DotNetAdapter installation, the second with manual DotNetAdapter installation.

## Your setup

- Unity 2019.4.5f1
- MRTK 2.5.1

## Target platform

- HoloLens 2

**Comment by keveleigh** [comment]
Hand mesh over remoting isn't currently supported, as [the APIs aren't supported](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/holographic-remoting-troubleshooting#limitations).

Hand joints not working does sound like the DotNetWinRT issue if you're using legacy Windows Mixed Reality. If you're using Windows XR Plugin, it could be related to [MRTK profile configuration](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/configuration/getting-started-with-mrtk-and-xrsdk?view=mrtkunity-2021-01#configuring-mrtk-for-the-xr-sdk-pipeline).

**Comment by keveleigh** [comment]
Closing this out due to lack of traction. Please reopen with more info if you're still hitting this!
