### ISSUE TITLE
Render from the PV camera (opt-in) show all layers

### ISSUE THREAD

**Issue by qazqaz12378** [microsoft/MixedRealityToolkit-Unity#8935]
![image](https://user-images.githubusercontent.com/4353931/98888928-d6a59b00-2490-11eb-8756-4ca4fad2bbf4.png)
![image](https://user-images.githubusercontent.com/4353931/98888954-e0c79980-2490-11eb-8f74-7f31d7b7a879.png)
![image](https://user-images.githubusercontent.com/4353931/98888972-ec1ac500-2490-11eb-8a5f-a6685708f4e7.png)

When PV camera is turned on, all layers are rendered, and only the selected layers should be rendered just like the main camera

It should be the same as that rendered by the camera, without rendering the HideModel level

**Comment by keveleigh** [comment]
This sounds like a Unity bug, since the engine is what handles the rendering to this additional camera. Please file a bug with them and/or post on the Unity forums. Thanks for the report!
