### ISSUE TITLE
We should reconsider the Set Scene Settings option(s) that are in the Toolkit Menu

### ISSUE THREAD

**Issue by jessemcculloch** [Microsoft/MixedRealityToolkit-Unity#895]
Those settings right now are very HoloLens centric.  Almost all the settings that are being done in that are not what is needed for Immersive Headsets.  I would like to see a discussion on how this can be better implemented for all cases, Immersive Apps, Holographic Apps, and Hybrid/Asymmetric Apps.

**Comment by StephenHodgson** [comment]
Agreed, I've already taken some steps to do this in my utilities update.

**Comment by jessemcculloch** [comment]
I am wondering if we start pushing people to using some of the prefabs.  A lot of this is taken care of by things like the HololensCamera, Mixed Reality Camera, and Mixed Reality Camera Parent prefabs.  Maybe a drop down that offers them which camera we put in the scene?
