### ISSUE TITLE
Hololens Pointer disappear while project deployed into the Hololens

### ISSUE THREAD

**Issue by cookgreen** [microsoft/MixedRealityToolkit-Unity#8951]
I use Unity 2019 and MRTK 2.5.0
![image](https://user-images.githubusercontent.com/21171007/99216569-f03c3f00-2810-11eb-8524-45a69932f06f.png)

After I deploy this project into Hololens, the pointer is disappeared and can't operate anything

**Comment by cookgreen** [comment]
Hololens Preview:

![image](https://user-images.githubusercontent.com/21171007/99218127-9ccbf000-2814-11eb-8748-9ff41993fd3f.png)

**Comment by cookgreen** [comment]
XR Setting:

![image](https://user-images.githubusercontent.com/21171007/99218208-cdac2500-2814-11eb-8780-3cc518fcafff.png)

**Comment by cookgreen** [comment]
Seems like some error

![image](https://user-images.githubusercontent.com/21171007/99225517-24206000-2823-11eb-8e28-618087d188b6.png)

**Comment by cookgreen** [comment]
Fixed

**Comment by cookgreen** [comment]
this error appears again

**Comment by MaxWang-MS** [comment]
Can you take a look at https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html and make sure that you have followed all the steps? It seems that this issue is related to the version of Windows XR Plugin (i.e. you might need to upgrade).

**Comment by cookgreen** [comment]
> Can you take a look at https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html and make sure that you have followed all the steps? It seems that this issue is related to the version of Windows XR Plugin (i.e. you might need to upgrade) and the profile of the MRTK GameObject.

I use 2.3.0 version for Windows XR Plugin, don't know whether it is the newest version
![image](https://user-images.githubusercontent.com/21171007/99491394-a6855d00-29a6-11eb-931b-d5ee1e96327f.png)

**Comment by MaxWang-MS** [comment]
Do you still see the compilation error in the console? If not please describe what is the problem you are experiencing now.

**Comment by cookgreen** [comment]
> Do you still see the compilation error in the console? If not please describe what is the problem you are experiencing now.
I always meet this problem since I have already added the MixedRealityInputModule into Canvas, even Camera and Event System  

![image](https://user-images.githubusercontent.com/21171007/99493612-822b7f80-29aa-11eb-9786-1fddb883d3ad.png)

**Comment by cookgreen** [comment]
@Microsoft

**Comment by MaxWang-MS** [comment]
You should not add that input module to anything other than the main camera under the mixed reality place space GameObject (and even for that GameObject the module should be added automatically already). You can try [run the example scene first](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Installation.html#run-the-handinteractionexamples-scene-in-the-unity-editor) and remember to change the MRTK profile to a XRSDK one.

**Comment by cookgreen** [comment]
Solved
