### ISSUE TITLE
Input System reported Error "Failed to register the MixedRealityInputSystem"

### ISSUE THREAD

**Issue by cookgreen** [microsoft/MixedRealityToolkit-Unity#8952]
## Describe the bug

After dragging a Input System Unity Engine reported Error "Failed to register the MixedRealityInputSystem"

## To reproduce

Go to MRTK prefabs and drag a Input System into the scene

## Expected behavior

No errors and can click the ui object

## Screenshots
![image](https://user-images.githubusercontent.com/21171007/99253802-5abea080-284c-11eb-80ce-a7f84689041e.png)

## Your setup  

- Unity Version 2019
- MRTK Version2.5.0

## Target platform 
- HoloLens 2

**Comment by cookgreen** [comment]
@microsoft

**Comment by CDiaz-MS** [comment]
@cookgreen We have a way for adding MRTK to the scene that does not include dragging individual prefabs.  After you import MRTK into your project, there will be a new menu at the top of Unity.  Go to **Mixed Reality Toolkit > Add to Scene and Configure** to add MRTK to your scene.

![image](https://user-images.githubusercontent.com/53493796/99425608-ede0f000-28b7-11eb-839a-624600c7a6aa.png)

**Comment by cookgreen** [comment]
I have done this

**Comment by MaxWang-MS** [comment]
Can you create a new scene, add MRTK to it following the directions posted by @CDiaz-MS and also configure the profile correctly (see [here](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8951#issuecomment-729443901)) and let us know if that works?

**Comment by cookgreen** [comment]
> Can you create a new scene, add MRTK to it following the directions posted by @CDiaz-MS and also configure the profile correctly (see [here](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8951#issuecomment-729443901)) and let us know if that works?

I created a new project and follow the all steps. but the cursor still can't see

**Comment by MaxWang-MS** [comment]
> > Can you create a new scene, add MRTK to it following the directions posted by @CDiaz-MS and also configure the profile correctly (see [here](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8951#issuecomment-729443901)) and let us know if that works?
> 
> I created a new project and follow the all steps. but the cursor still can't see

Can you make sure that you have used the XRSDK profile for the MRTK GameObject as mentioned in the guide?

**Comment by cookgreen** [comment]
> > > Can you create a new scene, add MRTK to it following the directions posted by @CDiaz-MS and also configure the profile correctly (see [here](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8951#issuecomment-729443901)) and let us know if that works?
> > 
> > 
> > I created a new project and follow the all steps. but the cursor still can't see
> 
> Can you make sure that you have used the XRSDK profile for the MRTK GameObject as mentioned in the guide?

I am sure I followed the all steps

**Comment by cookgreen** [comment]
Solved
