### ISSUE TITLE
Teleport System only works on Default Layer

### ISSUE THREAD

**Issue by JSWorkspace1** [microsoft/MixedRealityToolkit-Unity#8958]
## Describe the bug

The Teleport system only works on GameObjects that are in Unitys Default Layer.
On  Game Objects in a different layer the teleport pointer stays red and wont allow a teleport.

## Expected behavior

Teleport system works on all Game Objects.

##Alternative 

Add a Layer Mask Option to the Teleport System Settings in the MRTK Inspector.
or 
Use the "Pointing Raycast Layer Masks" in the Input Settings of the MRTK Inspector 

## Your setup (please complete the following information)

- Unity Version [2019LTS]
- MRTK Version [v2.5]

## Target platform (please complete the following information)
- WMR immersive

**Comment by davidkline-ms** [comment]
Thanks for the report! This is a great callout!

**Comment by anastasiadevana** [comment]
Turns out, there's a place to set the layers, but it's buried inside the Parabolic Pointer prefab. A much better place to set the layer mask would be in the Teleport section of the configuration profile

**Comment by BarboraAtVResearch** [comment]
Is there a way to make the settings from the Parabolic Pointer prefab actually work? I am changing it to a different layer to no avail. No matter what I put in there, it only works on "Default" :(

**Comment by BarboraAtVResearch** [comment]
SOLVED! For anyone interested, there are actually 2 places that needed to be changed: Pointing Raycast Layer Masks in MRTK settings AND the prefab
