### ISSUE TITLE
Hololens Re-scanning the environment with spatial understanding

### ISSUE THREAD

**Issue by Rishanthakumar** [Microsoft/MixedRealityToolkit-Unity#896]
I'm using spatial understanding to scan the environment and generate the spatial meshes. (According to the example in the HoloToolkit spatial understanding example)

After generating the meshes initially, i want to have an option to re-scan the environment again(removing the old meshes and regenerating new meshes or updating the old meshes). Is there any possible ways where i can achieve this. Any help would be much appreciated.

**Comment by StephenHodgson** [comment]
Duplicate of #231
