### ISSUE TITLE
Configurable button activations for hands-free accessibility  (head and eye gaze-dwell support)

### ISSUE THREAD

**Issue by kndrewa** [microsoft/MixedRealityToolkit-Unity#8961]
## Describe the problem

Some MR apps like D365 Guides have "gaze" activation.  This interaction is excellent for when users hands are busy with tools or part installation - just look at the button to go to the next step.  MRTK buttons should be configurable, per button, to enable various combinations of activation types, at the app developer's discretion.

1.) direct touch
2.) laser touch
3.) head direction (like D365 Guides)
4.) eye tracking

## Describe the solution you'd like

Items 1. and 2. from the list above work as expected.  However, for items 3. and 4. head direction and eye direction clicks, we need to include a "dwell" time so the user can choose not to complete the interaction just by glancing at the buttons.  Dwell should be tunable for duration and audio/visual feedback.  In guides, the buttons play sound while filling up to help the user anticipate completion.  In addition, there is a shader effect indicating a loading progress.

## Describe alternatives you've considered

Voice commands work, but often require the user to learn many special commands.  See-it/Say-it is a good model to improve voice command familiarization, but doesn't always work with graphical menu layouts.

## Additional context

This technology, gaze activation, requires special UI layout consideration.  We should include an example scene to help developers learn about what not to do.  A grid layout of gaze activations can cause discomfort, because the buttons start to activate just by trying to read what they do.  For this reason, the D365 Guides app has a very specific layout to ensure clear pathways for common gaze directions, and breathing room between buttons.  The gaze controls are most commonly positioned out of the way of the user to avoid accidents or anxiety.  There are similar considerations for list views, with feedback on the list items, and a special target area to the left of the list item which functions with gaze activation.  Repeatable positioning, "target area is always on the left of list items" ensure users understand a consistent pattern.

**Comment by keveleigh** [comment]
Hey @kndrewa! Some of the dwell features you describe sound like they were included in @ritijain's contribution at https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5594. Have you taken a look at that? If there are any features missing or polish that needs to be done, we can look into graduating this feature from experimental.

**Comment by polar-kev** [comment]
@kndrewa, there is a gaze and dwell example scene that has been graduated recently. There is also some ongoing pointer mediation work that will accrue to this in the 3.0 time frame. Please let us know if there are any features missing based on @keveleigh's comments above.

**Comment by Zee2** [comment]
Implemented as a first-class interaction paradigm in MRTK3!

**Comment by kndrewa** [comment]
This is fantastic, thank you very much Finn!  I'm really proud of this work we're doing here!
