### ISSUE TITLE
Quest 2 custom input action not working

### ISSUE THREAD

**Issue by trentpiercy** [microsoft/MixedRealityToolkit-Unity#8966]
## Describe the bug

Oculus Quest 2 custom input action assignments not working.

## To reproduce

1. Load the MRTK examples InputActionsExample scene.
2. Assign any digital button to Rotate on either Quest controller mapping
3. Build and run on Quest 2
4. Pressing any button mapped to any custom input is not registered by the InputActionHandler

## Expected behavior

When I press the A or B buttons, the InputActionHandler should be triggered and the cube should rotate, but the action is not registered by the InputActionHandler and the cube does not rotate.

## Screenshots

Input Action Assignments:
![image](https://user-images.githubusercontent.com/29619204/99737921-efb0dc00-2a8e-11eb-9f26-bb6aafa87c64.png)

Input actions:
![image](https://user-images.githubusercontent.com/29619204/99738090-559d6380-2a8f-11eb-83ff-2ad810a6f1d5.png)

Input data provider:
![image](https://user-images.githubusercontent.com/29619204/99738108-60f08f00-2a8f-11eb-9c98-f5dde6cf2b31.png)

InputActionHandler:
![image](https://user-images.githubusercontent.com/29619204/99738266-b331b000-2a8f-11eb-9225-a390123ccc52.png)

## Your setup (please complete the following information)

- Unity 2019.4.11f1
- MRTK v2.5.1 through UPM

## Target platform (please complete the following information)

- Oculus Quest 2

## Additional context

I've tried single axis based input too and no custom input actions have worked for me.

**Comment by qasim-sajid** [comment]
Hi @trentpiercy , I am facing the same issue while building for Quest 2 using MRTK package in Unity. How did you solve this issue?
