### ISSUE TITLE
HandGuidance.cs: error CS0619

### ISSUE THREAD

**Issue by edisonqkj** [Microsoft/MixedRealityToolkit-Unity#897]
Hey, guys!
I just download the master branch and use the package in my unity project. Before i build my project into VS solution, 8 errors are pushed out as the following picture:
![image](https://user-images.githubusercontent.com/5396193/29771667-aad6f78a-8c27-11e7-850f-4c80e9a82a93.png)
it recommends to use the functions with a prefix of '**_Interaction_**' in **_UnityEngine.XR.WSA.Input.InteractionManager.xxxx()_**
Can anybody help me out on this problem? Thanks!
Edison

**Comment by jessemcculloch** [comment]
@edisonqkj - I am guessing you downloaded Unity 2017.2.0b8.  It is a newer API set than the one the Master branch is currently on.  If this is the case, you will want to use the Dev_Unity_2017.2.0 branch instead.  

Some things to note.  The two branches are somewhat divergent at this point.  We are working on bringing them back into sync, but we are not there yet.  That said, there are things in Master that have not been brought into the Dev branch right now.  Just an FYI.  Also, unrelated to the Toolkit, but still relevant, there is a bug in 2017.2 that makes it so you can't deploy apps to the HoloLens, they just launch as a blank screen.  So if you are doing HoloLens development, and can't wait for this bug to be fixed, I would recommend installing the 2017.1 version of Unity and using it.  Unfortunately, 2017.1 does not support the immersive headsets.  

I know, it's pretty much a compatibility nightmare right now between Unity and Visual studio.  If you have any further questions, let us know.

Thanks,
Jesse

**Comment by edisonqkj** [comment]
@jessemcculloch - Thank you, Jesse! I really appreciate your help on this problem. Currently, I'm developing HoloLens apps with Unity 2017.2.0b8 (sorry for this unmentioned information in the question). As your suggestion, I will install the 2017.1 version of Unity. 
Thank you all for the hard work on this great project!
Edison
