### ISSUE TITLE
HandMenu throws MissingReferenceException in TeleportCursor on HoloLens

### ISSUE THREAD

**Issue by pcatalanojr** [microsoft/MixedRealityToolkit-Unity#8978]
## Describe the bug

When using a HandMenu prefab, Unity throws the following error:
"MissingReferenceException: The object of type 'Transform' has been destroyed but you are still trying to access it." in TeleportCursor.cs line 119.

## To reproduce

Load the HandMenuExamples scene.
Run it on a HoloLens 2.
Raise wrist within view to show menu.
Lower wrist outside of view to hide menu.

## Expected behavior

No errors.

## Your setup (please complete the following information)

- Unity 2019.4.15f1
- Windows XR Plugin 2.4.1
- MRTK 2.5.1.
- MixedRealityToolkit configuration profile: DefaultXRSDKConfigurationProfile.

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

Stack trace of error:
MissingReferenceException: The object of type 'Transform' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Microsoft.MixedReality.Toolkit.Teleport.TeleportCursor.SetVisibility (System.Boolean visible) (at Assets/MRTK/SDK/Features/UX/Scripts/Cursors/TeleportCursor.cs:119)
Microsoft.MixedReality.Toolkit.Utilities.Solvers.HandConstraint+<ToggleCursors>d__62.MoveNext () (at Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraint.cs:478)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <526469d5a48c43eebd9af19f8745afa1>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Microsoft.MixedReality.Toolkit.Utilities.Solvers.HandConstraint:SolverUpdate() (at Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraint.cs:318)
Microsoft.MixedReality.Toolkit.Utilities.Solvers.Solver:SolverUpdateEntry() (at Assets/MRTK/SDK/Features/Utilities/Solvers/Solver.cs:260)
Microsoft.MixedReality.Toolkit.Utilities.Solvers.SolverHandler:LateUpdate() (at Assets/MRTK/SDK/Features/Utilities/Solvers/SolverHandler.cs:323)

**Comment by keveleigh** [comment]
This sounds like the bug that was fixed in the development branch via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8970. Will ship with our next release!
