### ISSUE TITLE
How to launch Unity UWP app as 2D instead of Mixed Reality Portal

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#898]
Anyone know how to prevent a Unity App build as a UWP from launching in the Mixed Reality Portal if running on a local machine?

**Comment by jessemcculloch** [comment]
Uhhh? Why would you want to?

**Comment by StephenHodgson** [comment]
I'd like to launch the UWP app as a normal application on desktop, but instead it launches the Mixed Reality Portal and then runs in the portal.

**Comment by jessemcculloch** [comment]
How are you launching it?  Via the start menu, or when you run it in debug mode in Visual Studio, or when you are hitting play in Unity?

**Comment by StephenHodgson** [comment]
Via Start Menu.

**Comment by jessemcculloch** [comment]
Interesting, I have not seen this.  Let me try to replicate

**Comment by StephenHodgson** [comment]
Thanks Jesse

**Comment by jessemcculloch** [comment]
Hate to ask a dumb question, but you don't have Virtual Reality Enabled in the player settings, do you?

**Comment by StephenHodgson** [comment]
@jessemcculloch that was the right question to be asking!  Thanks!

That was it!

**Comment by jessemcculloch** [comment]
LOL, glad to help
