### ISSUE TITLE
UGUI not working in HandInteractionExamples scene on dev branch

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#8983]
## Describe the bug

The UGUI examples on the right hand side are currently not working (e.g. buttons cannot be clicked, input field does not respond to click) on apps deployed to HL2 in debug mode. They work in editor remoting and deployed release mode app though.

## Your setup (please complete the following information)

- Unity Version 2019.4.15f1 & 2018.4.29f1
- MRTK dev_branch

## Target platform (please complete the following information)

- HoloLens 2

**Comment by davidkline-ms** [comment]
@MaxWang-MS has this been fixed (and then forgotten to close)?

**Comment by davidkline-ms** [comment]
Debug mode drops the app frame rate on HoloLens. This behavior is likely due to the game-loop timing in debug.
