### ISSUE TITLE
Dial-type UI proposal for HoloLens 2

### ISSUE THREAD

**Issue by HoloMoto** [microsoft/MixedRealityToolkit-Unity#8988]
## Describe the problem

In HoloLens 2 you can move and rotate objects with your hands.
I propose a Dial-type UI with this.

## Describe alternatives you've considered

I created a simple video as follows

https://youtu.be/SvW9O9QeGVc

It is similar to the JoyStick added in MRTK 2.5, with both visible and real moving objects.

The rotation angle can be limited and the user can specify events depending on the angle.

I think the Dial-type UI is an opportunity for developers as well as creators to express themselves in a new way with MRTK.

Also, I think it will create a situation where users can interact with the holograms in a way that is more like real life.

I'd love to contribute, but I'd be happy to receive your feedback and suggestions.

**Comment by HoloMoto** [comment]
@cre8ivepark  Please check it.  Also, if there are any improvements in the video stage, I will push the improvements

**Comment by Zee2** [comment]
@HoloMoto, feel free to create an MRTK3 package with this UX component!

**Comment by HoloMoto** [comment]
@Zee2 
Thank you !
I will challenge！
