### ISSUE TITLE
Bounds Control With Non Uniform Scale Issues

### ISSUE THREAD

**Issue by JYBA1** [microsoft/MixedRealityToolkit-Unity#8992]
## Overview
When using the bounds control with scale configuration set to non uniform the object can have erratically and move in unintuitive ways.

I was able to reproduce this behaviour using the boundscontrols found in the MRTK sample scene just by setting the scale mode to non uniform.

## Expected behavior
The object should be moveable on a single axis related to the handle selected.

## Actual behavior
The object sometimes seems to move along a completely different axis and moves at inconsistent speeds making it impossible to use. 

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity editor version
2019.4.6f1

## Mixed Reality Toolkit release version
2.5

**Comment by MaxWang-MS** [comment]
This should have already been fixed in #8923. Please try out the dev branch and let us know if you are still experiencing the problem.

**Comment by JYBA1** [comment]
I will test this when I have the opportunity, but looking through the PR I am not sure it will fix the issue. I have found this issue while FlattenAxis is set to 'Do Not Flatten'. It looks like it's related to rotation in some way. Parenting the object under a rotated parent causes the erratic behaviour. 

Will report back after testing latest changes though to be sure.

**Comment by JYBA1** [comment]
Tried with dev branch this morning and the problem is still there.
- Create an empty game object and set it's x rotation to 45
- Create a cube as a child of the empty object and set it up as a bounds control
- Set the scale to be non uniform with not axis being flattened
- Scale behaviour is unstable and broken

**Comment by MaxWang-MS** [comment]
I was able to reproduce with Unity 2019.4.15f1 and HoloLens 2 remoting.

**Comment by JYBA1** [comment]
After some work today we have come up with something that looks like a solution. Within BoundsControl.TransformTarget(HandleType transformType) we made the following changes:

`Vector3 initialDist = (initialGrabPoint - oppositeCorner);`
`Vector3 currentDist = (currentGrabPoint - oppositeCorner);`
becomes
`Vector3 initialDist = Target.transform.InverseTransformVector(initialGrabPoint - oppositeCorner);`
`Vector3 currentDist = Target.transform.InverseTransformVector(currentGrabPoint - oppositeCorner);`

and

`var originalRelativePosition = initialPositionOnGrabStart - oppositeCorner;`
`var newPosition = originalRelativePosition.Div(initialScaleOnGrabStart).Mul(Target.transform.localScale) + oppositeCorner;`
becomes
`Vector3 originalRelativePosition = Target.transform.InverseTransformDirection(initialPositionOnGrabStart - oppositeCorner);`
`var newPosition = Target.transform.TransformDirection(originalRelativePosition.Mul(scaleFactor)) + oppositeCorner;`

**Comment by elenzil** [comment]
Not sure if the erratic behaviour I'm seeing is the same as what's discussed here,
but in MRTK 2.5.4 I'm easily able to get erratic behaviour with non-uniform "scale behavior" on a Bounds Control.

Additionally, when non-uniform is selected, the scale seems to override the min/max constraints of an attached MinMaxScaleConstraint.  I've filed [a new bug for that](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9389).
