### ISSUE TITLE
errors: caused by “Unity C# Projects" option checked and Blank Screen app startup

### ISSUE THREAD

**Issue by edisonqkj** [Microsoft/MixedRealityToolkit-Unity#900]
Hello, friends!
Currently, i'm using **Win 10(Professional)+Unity 5.6+VS2017(15.3)** to develop HoloLens apps.

Following the tutorial: _**Chapter 1 - "Holo" world**_([https://developer.microsoft.com/en-us/windows/mixed-reality/holograms_101e](url)), i checked the “**Unity C# Projects**" and "**Copy References**" options as following pic, it **succeeds** in building the project. (All settings are the same as Alex Turner told).
![image](https://user-images.githubusercontent.com/5396193/29820382-dbcafef2-8cf6-11e7-99c3-88436fe579f5.png)

After that, i opened the solution with VS2017, setting the configuration as Release, x86 and Hololens Emulator 10.0. While pressing the Play button, errors pushed out as following pic:
![image](https://user-images.githubusercontent.com/5396193/29820718-fe6820b0-8cf7-11e7-8c58-a3a9839eb730.png)

I've searched for many solutions to this problem, such as @NeerajW gave ([https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/295](url)). But it still doesn't work.

As a tradeoff, i unchecked “**Unity C# Projects**" and "**Copy References**" options when building Unity project into VS solution. Luckily, the errors about "Assembly-CSharp-xxx.dll" are no longer occur. And the only error is also fixed with the usage given by @Handosa
([https://forum.unity3d.com/threads/net-scripting-backend-and-visual-studio-2017-3-incompatibility.487833/](url)).

Finally, the VS solution can be compiled and deployed into Emulator successfully. However, when i started the app, only **a blank screen** is rendered in the Emulator. I can rotate the environment, select items with Space or Enter key.
![image](https://user-images.githubusercontent.com/5396193/29821339-1b3f7a10-8cfa-11e7-8034-09fbc29fc6e7.png)

I'm aware of the information in the **Output window** in VS as following:
> 
> d3d11: failed to create 2D texture id=48 width=64 height=64 mips=7 dxgifmt=65 [D3D error was 887a0005] 
> (Filename: C:\buildslave\unity\build\Runtime/GfxDevice/d3d11/TexturesD3D11.cpp Line: 498)
> d3d11: failed to create 2D texture shader resource view id=48 [D3D error was 80070057]
> (Filename: C:\buildslave\unity\build\Runtime/GfxDevice/d3d11/TexturesD3D11.cpp Line: 517)
> 
![image](https://user-images.githubusercontent.com/5396193/29821486-b1c4c062-8cfa-11e7-9728-473cae2075c2.png)

The all information printed in Output window:
[output.txt](https://github.com/Microsoft/MixedRealityToolkit-Unity/files/1260298/output.txt)

Can anybody give me a solution to my question? Thanks! 🍡 
Best wishes!

Edison

**Comment by jessemcculloch** [comment]
Can you tell me what version specifically of Unity 5.6 you are using?  Need the full build number.  

I think you are running into this issue - #860 

I don't think the patch file for 5.6 has been released yet, so it's the upgrade to Visual Studio 15.3 that broke things for you.

**Comment by edisonqkj** [comment]
@jessemcculloch the full build number of Unity is **5.6.3f1**
![image](https://user-images.githubusercontent.com/5396193/29849240-06e1f45e-8d58-11e7-9b86-7ddf314f02d7.png)

**Comment by jessemcculloch** [comment]
@edisonqkj - Yeah, unfortunately you are kind of stuck right now.  You can try some of the solutions that were in that other issue I linked to.  Or you can wait for the 5.6.3 patch build to eventually release (no date yet).  Or you can go up to 2017.1.0.

**Comment by edisonqkj** [comment]
@jessemcculloch - OK, thank you Jesse sincerely. I will try Unity 2017.1.0 with a lower version of VS2017. If it works, I will tell the combination of these softs.

**Comment by StephenHodgson** [comment]
@edisonqkj, I suggest using the current editor version found on the front page 2017.1.0p5

**Comment by edisonqkj** [comment]
@jessemcculloch @StephenHodgson - thanks you both, my friends.

Currently, I installed **VS2017(v15.0)+Unity 2017.1.0p5(64bit)** and it made it finally!
Both “**Unity C# Projects**" and "**Copy References**" options are **checked** when building Unity project into VS solution. It goes well during compilation without errors existing in this question.
So, i think this combination of VS & Unity works well.

the downloading url of VS2017(v15.0): [https://my.visualstudio.com/Downloads?q=visual%20studio%202017](url)

The problem of **blank screen** is still unsolved. I'm working on it.
If any friend could give me some help on it, I'll appreciate it.

Edison

**Comment by StephenHodgson** [comment]
I don't think `Copy References` is working quite yet. Pretty sure that's a unity bug.

**Comment by edisonqkj** [comment]
@StephenHodgson hi Stephen, it works without **Copy References** being checked.

**Comment by edisonqkj** [comment]
currently, i'm debugging my app in HoloLens device instead of the emulator. it works fine. thanks all for helping me out on my questions.

**Comment by Uri92** [comment]
@edisonqkj @StephenHodgson  I encountered the same problem and installed Unity 2017.1.0p5(64bit). However, I cannot install Visual Studio v15.0. During the installation process, I am receiving this error (already tried uninstalling, deleting all associated files etc. but the same error keeps popping back up): 

> Package 'Microsoft.VisualCpp.Redist.14,version=14.10.25008,chip=x86' failed to install.

I could not find any workarounds. Do you have any idea how to fix this?

**Comment by StephenHodgson** [comment]
Try cleaning out any old VS files in your app data folders and program folders, then do the install.  Might be something hanging around blocking your install.

**Comment by Uri92** [comment]
@StephenHodgson Thanks for the prompt reply, I really appreciate it! Unfortunately, I already tried that and it ended with the same mistake.

[https://social.msdn.microsoft.com/Forums/en-US/4ecc1495-de4d-432f-9886-94d28ced6dc9/vs-community-2017-installation-problems?forum=vssetup](This) discusses the same problem, but the fix described at the bottom of the page is also not working.
