### ISSUE TITLE
To align with other Mixed Reality products in Unity, menu items should move under a "Mixed Reality" top-level item

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#9003]
## Describe the problem

As other Mixed Reality products are adding menu items in Unity, having two menu items at the top takes up valuable real estate and can lead to confusion:

![image](https://user-images.githubusercontent.com/3580640/100929494-96887580-349c-11eb-86ae-215809dff743.png)

## Describe the solution you'd like

Instead, we should move the Mixed Reality Toolkit menu items under the shared Mixed Reality top-level item.

## Additional context

Instead of continually growing the menu bar if each product adds their own top-level item, it feels more aligned to me to combine things.

**Comment by keveleigh** [comment]
Could be an opportunity to address (or Won't Fix) https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5574

**Comment by davidkline-ms** [comment]
For MRTK.Next?

**Comment by keveleigh** [comment]
Fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9649
