### ISSUE TITLE
Grab issue with Unity 2020 XR SDK on MRTK 2.5.1

### ISSUE THREAD

**Issue by JarlErikC** [microsoft/MixedRealityToolkit-Unity#9007]
## Describe the bug

When using apps on the HoloLens built with the new XR SDK and MRTK 2.5, grabbable objects are not possible to grab if your hand is rotated more than 45-50 degrees. This makes it difficult for the user to grab and interact with objects without ensuring that they keep their hand rotated straight up or less than 45 degrees. Comparison with the old XR system on Unity 2019, grabbable objects shows that this issue is not present (see video).

## To reproduce

Steps to reproduce the behaviour with Unity 2020, XR SDK and MRTK 2.5.1:

1. Add a cube to the scene with a collider, ObjectManipulator and NearInteractionGrabbable
2. Select profile DefaultXRSDKConfigurationProfile
3. Build and deploy to HoloLens
4. In the HoloLens, grab the object with the hand rotated more than 45 degrees or holding sideways.
5. Not possible/difficult to grab

—

Repeat with Unity 2019 and old XR system.

## Expected behavior

When grabbing a grabbable object, the rotation of the hand should in most cases not impact the registration of grab interaction while the hand is in the HoloLens FOV.

## Screenshots / Video

**Unity 2020 new XR SDK**
![Unity2020](https://i.makeagif.com/media/12-03-2020/BykYZD.gif)

**Unity 2019 old XR system**
![Unity2019](https://i.makeagif.com/media/12-03-2020/mGqkqO.gif)

## Your setup (please complete the following information)

- Unity Version 2020.1.9f1
- MRTK Version 2.5.1
- New XR SDK

## Target platform (please complete the following information)

- HoloLens 2

**Comment by anthony-simetri** [comment]
I find that if you do the air tap with your thumb and index finger closing in full-frontal view, it's fairly consistent at recognizing it but otherwise has a hard time at detecting the grabbing motion.

**Comment by mwarvik** [comment]
This has a huge detrimental effect on our applications, so I hope it will be looked into shortly (or we can find some way to fix it locally).

**Comment by anthony-simetri** [comment]
This is only part of the problem for me. In this same setup, I get a lot of errors when trying to set constraints on object manipulation. I am completely unable to restrict rotation to the y axis with RotateAxisConstraint and scale constraint is very finicky on when it will throw an exception I cannot read from the compiled il2cpp. Manually trying to correct it at manipulation event start and end also results in unexpected behavior that is unacceptable for our audience. Working with MRTK has overall been a very frustrating experience. At the current rate, it is likely I will have to try to completely reengineer the object manipulator script to try to get something to work correctly.

**Comment by yacuzo** [comment]
According to https://techcommunity.microsoft.com/t5/mixed-reality-blog/bg-p/TheMixedRealityBlog the support for XR SDK will be dropped in the future, so I guess time is rather spent on OpenXR which will replace it.

**Comment by Holo-Fiedel** [comment]
This issue also appears with lower Unity version.
In our case it's the latest 2019.4.x LTS

**Comment by RogPodge** [comment]
Sorry for the late response (we've been handling things for the 2.6.0 release!) 

We've been able to reproduce this issue and are diving deeper into this. Also, to clarify, OpenXR is another provider to the XR SDK pipeline. We are **not** dropping support for XR SDK, in fact, we're moving to supporting it more in the future 😅
