### ISSUE TITLE
Cursor invisible

### ISSUE THREAD

**Issue by friuns2** [Microsoft/MixedRealityToolkit-Unity#901]
Hello when i add prefab Basic Cursor to my project its invisible for somre reason.

in editor and in demos it is visible

don't see any errors in console, what can be the problem?

**Comment by friuns2** [comment]
and seems to be IsHandVisible is always false

**Comment by StephenHodgson** [comment]
@friuns2 ever figure this out?

**Comment by NeerajW** [comment]
Please reopen if your question was not answered.
