### ISSUE TITLE
Height configuration for standing, room, and world target scales

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#9011]
## Describe the problem

Currently, when using MRTK, the MRTK camera and Playspace are both positioned at the origin upon initialization, with adjustments to the camera position offsetting it from the parent playspace object. When trying to set the camera to start at a relative "height" compared to the playspace, the user ends up higher than they would expected based on just the editor window. 

In addition, without setting this "height", teleportation across surfaces ends up teleporting users to floor level, as the default "height" of the user is set to be zero.

What we need to do is to be able to easily set a relative "height" for the user for standing, room and world target scale experiences so that can provide a better experience with the teleportation move system and other systems that might need to take the users's height into account

Also requested by #9497

**Comment by davidkline-ms** [comment]
@RogPodge moving this out to MRTK.Next. If we have a branch with this we can reconsider

**Comment by RogPodge** [comment]
That's fine, at the moment it's looking to be part of the core usability improvements we're making
