### ISSUE TITLE
Improve input simulation for easier use of several gestures without relying on the altering the profile

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#9013]
## Describe the problem

Currently it's a bit cumbersome to try out different input gestures in input simulation, as you need to change the gestures associated with different mouse buttons in the input simulation profile each time. This becomes inconvenient for some gestures like teleportation, which has a "start" and "end" state required to perform the action.

This issue tracks making improvements in this area.

**Comment by Zee2** [comment]
Added in MRTK3.
