### ISSUE TITLE
Initial scale 0 causes GridObjectCollection to have no content

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#9029]
## Describe the bug

We have a piece of UI that contains a GridObjectCollection.  A change was made to hydrate the UI so that it starts at 0 scale, and ramps to 1 over a small amount of time.  This change caused all the content in the GridObjectCollection to be missing.  If I change the scale to be a very small non-zero number, it works fine.  We had the same problem and same workaround on a previous project.  

## Your setup (please complete the following information)

Using MRTK 2.5.1

**Comment by julenka** [comment]
@polar-kev  I wasn't sure who to assign this to, so for now I assigned to you to triage. Perhaps @RogPodge ?

**Comment by RogPodge** [comment]
Resolved this issue and found it wasn't on MRTK side. Turns out the child object was getting moved out of the collection and added back in, so it's localScale was getting zero'd out and thus wouldn't grow with the grid object collection upon getting reparented. 

Closing the issue.
