### ISSUE TITLE
Spatial Audio demo scene

### ISSUE THREAD

**Issue by paco-ms** [microsoft/MixedRealityToolkit-Unity#9032]
## Describe the problem

- Need a way to showcase Spatial Audio as an MRTK/HL feature.
- Need an app/experience that can be used as a benchmark as to what an "optimal spatial audio experience" sounds like. Developers are sometimes unsure if their apps audio experience is optimal or not.
- Need to document / guide developers on how to use Spatial Audio features in Unity/MRTK

## Describe the solution you'd like
An MRTK sample scene, to be incorporated into the MRTK Examples Hub (and thus the Store) that showcases Spatial Audio.

## Describe alternatives you've considered
Some ready experiences with spatial audio in them (RoboRaid, etc) showcases the feature but lack enough control to be used as a benchmark. Also those can't be used to help the developer.

**Comment by jbienzms** [comment]
I too would like to vote for an interactive Spatial Audio sample, especially one added to the MRTK Examples Hub in the store.

As for a document / guide on how to use Spatial Audio, I believe that's fairly well covered in the 5-part series [here](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/unity-spatial-audio-ch1). However, I do agree that this series is located on docs.microsoft.com and isn't mentioned anywhere in the [MRTK Feature Guides](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_Button.html). In fact the Feature Guides doesn't return any results for either "sound" or "audio". This does feel at least a missed opportunity if not a gap in MRTK documentation.

**Comment by Zee2** [comment]
Added in MRTK3.
