### ISSUE TITLE
[Accessibility] Add 'grab' and 'release' voice command and behavior

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#9039]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/311

___

## Describe the problem
HoloLens & MRTK provides the default 'Select' keyword for triggering press/air-tap event. This works well with the UX components such as buttons. However, there is no way to achieve grab and move then release behavior. 
Some examples that require grab and release voice command:
- Bounding Box's handles 
- Slate's title bar
- Slider 
- Near menu's backplate

## Describe the solution you'd like
Add keyword definitions to MRTK's Speech Input profile and connect with grab (select-and-hold) behavior.

**Comment by davidkline-ms** [comment]
@RogPodge can you scope the work and advise?
