### ISSUE TITLE
System keyboard can only be opened as a default type.

### ISSUE THREAD

**Issue by KFleszar-H4L** [microsoft/MixedRealityToolkit-Unity#9046]
The system keyboard type is currently hardcoded into MixedRealityKeyboardBase.ShowKeyboard(string, bool).

![image](https://user-images.githubusercontent.com/73595313/102067771-e00d8480-3dfb-11eb-9b8a-940e17a6704c.png)

It would be preferable if the keyboard type was passed as a parameter, provided that MRTK actually handles different types of keyboard.

It is a bad UX design to open a default keyboard when e.g. the given input field only accepts numeric input.

**Comment by MaxWang-MS** [comment]
Due to #7944 we do not plan to make it a parameter for now.
