### ISSUE TITLE
BoundsControl should orient handles to the managed object

### ISSUE THREAD

**Issue by ModischFabrications** [microsoft/MixedRealityToolkit-Unity#9047]
## Describe the problem

I want to use custom rotation handles ("rotate arrows") for the BoundsControl, but the prefab is instantiated without a rotation.
Won't matter for the default spheres, but any non-round shape isn't working without an orientation. 

## Describe the solution you'd like

Point the handle objects towards the middle of the bounds. 

## Describe alternatives you've considered

Adding a rotateTo script to the prefab. This does not work since the handles are not an object visible in the inspector, so I don't know how to access them or if I could align to the parent. 

## Additional context

![image](https://user-images.githubusercontent.com/25404728/102086420-5b7d2f00-3e18-11eb-9768-b436b82669eb.png)

**Comment by ModischFabrications** [comment]
I found a workaround:

```
    public string objectName;

    private void Start()
    {
        Vector3 directionToTarget = GameObject.Find(objectName).transform.position - transform.position;
        transform.rotation = Quaternion.LookRotation(-directionToTarget);
    }
```

Add it to the prefab assigned as a handle and insert the name of the object contained inside the BoundsControl. You might want to rotate the mesh inside the prefab if this points in the wrong direction. 

This is not a clean solution, but this works for me until a proper solution is done.

**Comment by keveleigh** [comment]
@Zee2 Adding you here for awareness, since you've been looking at BC bugs recently.

**Comment by Zee2** [comment]
Hi @ModischFabrications , this has already been updated/changed in the `main` branch. The handle transforms are properly rotated now. If you're still having this issue, try cloning `main` and seeing if your handles behave as expected now.

**Comment by ModischFabrications** [comment]
Great, but I've moved on to other projects in the meantime and am therefore unable to test it. Feel free to close this issue if it's fixed.

**Comment by Zee2** [comment]
Great, no worries.
