### ISSUE TITLE
IMixedRealityGestureHandler<Vector3> called on one object not on the other

### ISSUE THREAD

**Issue by ikun03** [microsoft/MixedRealityToolkit-Unity#9058]
## Describe the bug
I have 2 objects in my scene. An empty test object and a Model with animation. When I attach the script below to the model it works but disabling the model and enabling the empty test object with the same script does not work i.e the GestureHandler on the empty object receives no messages. Everything else is the same except simply enabling either the model or the empty test object.
````
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Microsoft.MixedReality.Toolkit.Input;

public class GestureHandler : MonoBehaviour, IMixedRealityGestureHandler<Vector3>
{
    void Awake() {
        UnityThread.initUnityThread();
    }

    public void OnGestureCanceled(InputEventData eventData)
    {
        Debug.Log("OnGestureCanceled");
    }

    public void OnGestureCompleted(InputEventData<Vector3> eventData)
    {
        Debug.Log("OnGestureCompleted");
        var action = eventData.MixedRealityInputAction.Description;
        Debug.Log(action);
       //Some code to execute
    }

    public void OnGestureCompleted(InputEventData eventData)
    {

        Debug.Log("OnGestureCompleted");
        var action = eventData.MixedRealityInputAction.Description;
        Debug.Log(action);
       //Some code to execute
    }

    public void OnGestureStarted(InputEventData eventData)
    {
        Debug.Log("OnGestureStarted");
        
    }

    public void OnGestureUpdated(InputEventData<Vector3> eventData)
    {
        Debug.Log("OnGestureUpdated");
    }

    public void OnGestureUpdated(InputEventData eventData)
    {
        Debug.Log("OnGestureUpdated");
    }

    void HandleCameraResult(string detectedObject) {
        
   //Some relevant code
    
    }

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}

````

## To reproduce

Attach the gesture script to an empty object with MRTK and other required components

## Expected behavior

The GestureHandler Script should receive the required messages.

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.4.2f1]
- MRTK Version [e.g. v2.3]

## Target platform (please complete the following information)

- HoloLens 1

**Comment by ikun03** [comment]
I tried the same approach in the HandInteractionGestureExample Scene by disabling only the children of the GestureTester object and the gesture tester stopped working as well. It only started working after enabling the cube object(did not test enabling others). For now, adding a cube placed **inside the camera view frustum** seems to work for my script as well.

**Comment by keveleigh** [comment]
One suggestion to try is to make this script a `InputSystemGlobalHandlerListener` instead of a `MonoBehaviour`, registering for the gesture events like (but with `IMixedRealityGestureHandler<Vector3>` instead of `IMixedRealityDictationHandler`):

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/171f524b0cfc1a2f2ef735b5edcd618b615b163c/Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Scripts/NonNativeKeyboard.cs#L296-L304

That way, it'll receive events even if not focused. My guess is that the object in the middle of the camera view is getting focused by the gaze cursor or something.

**Comment by ikun03** [comment]
It solved my issue in the simulator but on the Hololens 1, it still does not work. I removed the cube so that the screen does not focus on any object in the center of the screen. But the listener still does not receive the signals.

**Comment by keveleigh** [comment]
Ah, I think I misunderstood this issue based on the configuration.
Turns out, gestures aren't currently supported on Windows XR Plugin. That's tracked by #7271, so I'm closing this one as a duplicate.
