### ISSUE TITLE
Holographic Emulator throws error about render texture missing mipmaps

### ISSUE THREAD

**Issue by Ironfreak** [Microsoft/MixedRealityToolkit-Unity#908]
```
Holographic Emulator (Simulate and Remote) Error! RenderTexture.GenerateMips failed: render texture does not have mip maps (set useMipMap to true).
```

Used versions: Unity 2017.1.0p5 / HoloToolkit-Unity-v1.2017.1.0

Thanks!

**Comment by StephenHodgson** [comment]
Do you know what class this is getting thrown in?

**Comment by jessemcculloch** [comment]
I believe this is a Unity bug, not generated by the HTK.  It seems it might be related to the far clipping plane issue as well.

https://forum.unity3d.com/threads/beta-7-case-943170-windows-mixed-reality-far-clip-and-rendertexture-generatemips-error.488714/

**Comment by StephenHodgson** [comment]
Thanks Jesse
