### ISSUE TITLE
2.5.2 broke Oculus

### ISSUE THREAD

**Issue by A1igator** [microsoft/MixedRealityToolkit-Unity#9083]
## Describe the bug

You get the error:
Library\PackageCache\com.microsoft.mixedreality.toolkit.foundation@2.5.2\Providers\Oculus\XRSDK\MRTK-Quest\Scripts\Input\Controllers\OculusHand.cs(186,30): error CS0102: The type 'OculusHand' already contains a definition for 'IsInPointingPose'

I looked at the file in the MRTK-release branch and it also has a duplicate definition so I don't think I updated MRTK wrong.

**Comment by keveleigh** [comment]
@rogpodge Might be a good reason to raise the priority of #8129

**Comment by RogPodge** [comment]
Should be fixed with our 2.5.3 hotfix, closing for now
