### ISSUE TITLE
Handinteraction Demo in Unity Holographic Remoting

### ISSUE THREAD

**Issue by Xalderane** [microsoft/MixedRealityToolkit-Unity#9087]
## Describe the bug

Enabling MRTK, then Holographic Remoting. Build settings ARM running a Hololens 2. When running holographic remoting, the handtracking doesn't seem to register touch. However, occasion grabbing is registered. There is the option to toggle these actions, but this doesn't affect the result.

## To reproduce

1. Unity version 2019.4.3f1
2. Add MRTK
3. Load examples
4. Open handtracking demo
5. Try to play the keyboard. You'll have the hand tracking rays, but no hand interactions.

## Expected behavior

When the hand intersects the keyboard, the notes should play. This performs as expected in Unity when using manual controls. When loaded in Hololens 2, there are only hand rays.

- Unity Version [e.g. 2019.4.3f1]
- MRTK Version [e.g. v2.5.2]

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

Doesn't seem to work for other demos either.

**Comment by keveleigh** [comment]
If you're using the legacy Windows Mixed Reality package, you'll need to [additionally install DotNetWinRT](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/tools/holographic-remoting?view=mrtkunity-2021-01#legacy-xr-setup-instructions).

If you're using Windows XR Plugin with an MRTK version pre-2.7.0, you'll need to make sure you're [using the correct profiles](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/configuration/getting-started-with-mrtk-and-xrsdk?view=mrtkunity-2021-01#configuring-mrtk-for-the-xr-sdk-pipeline). It sounds like your profiles are correct if you see hand tracking rays, so my best guess is that it's the DotNetWinRT configuration.

I'm going to close this out as it's had low traction for a few months, but please re-open if you're still having issues!
