### ISSUE TITLE
Holographic Remoting settings unresponsive (or unclear) on Linux

### ISSUE THREAD

**Issue by NoTuxNoBux** [microsoft/MixedRealityToolkit-Unity#9092]
## Describe the bug

Holographic Remoting cannot be activated on Linux - or possibly all other platforms than Windows. Alternatively, if this cannot be supported: it is not clear that this does not or cannot work from the UI.

## To reproduce

1. (Ensure _Windows Mixed Reality_ is checked under _XR Plug-in Management_.)
1. Go to Window -> XR -> Windows XR Plugin Remoting. The _Windows Mixed Reality_ window shows up.
2. Select _Remote To Device_ under _Emulation Mode_.
3. Nothing happens, i.e. the settings to configure it are not displayed. You can modify the dropdown selection, but it has no effect and does not display the address bar and other fields.

## Expected behavior

Preferably holographic remoting should work on other platforms than Windows, as it can be done over the network and the MRTK isn't tied to Windows necessarily. This is of course assuming the Holographic Remoting app is installed on the HoloLens itself.

Alternatively, if it is impossible to support it, the option should not be given or a clear error message should be displayed that it cannot work (and possibly why).

## Your setup (please complete the following information)

- Unity Version 2019.4.17f1 and 2020.2.1f1
- MRTK Version [e.g. v2.0] 2.5.1

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
Holographic Remoting itself isn't an MRTK feature, but a HoloLens / Windows Mixed Reality one overall. Since it's directly replacing the WMR runtime locally, according to https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/holographic-remoting-create-remote-wmr

>Holographic Remoting works by replacing the Windows Mixed Reality runtime which is part of Windows with a remoting specific runtime.

my guess is it requires Windows, since that's the only place the WMR runtime exists.

**Comment by MrWatts-Anorak** [comment]
Thanks for the information!

Since it's not part of the MRTK, the configuration dialog itself perhaps also isn't? (In that case feel free to close this issue, as there is nothing that can be done here to fix it, I wrongly assumed it was part of the MRTK.)

**Comment by keveleigh** [comment]
> Since it's not part of the MRTK, the configuration dialog itself perhaps also isn't?

If this is referring to the "Windows XR Plugin Remoting" window, that's correct. That UI is shipped by Unity as part of their Windows XR Plugin package.
