### ISSUE TITLE
CoffeeCups in BoundsControlExamples have incorrect local space

### ISSUE THREAD

**Issue by jjimenezg93** [microsoft/MixedRealityToolkit-Unity#9102]
## Describe the bug

The local space of each `CoffeeCup` in the `BoundsControlExamples` scene is aligned to the World's space, so for example setting `UseLocalSpaceForConstraint` in `Rotation Axis Constraint` to `true` becomes meaningless.

## To reproduce

1. Go to `BoundsControlExamples`.
2. Click on a `CoffeeCup` GameObject.
3. Notice how the coordinate system's gizmo on the object is aligned with the World's.
4. Repeat 2-3 a few times.

## Expected behavior

My understanding is that the local coordinate system should be aligned to one face of the mesh. For example:

![expected_local_space](https://user-images.githubusercontent.com/6595611/103752043-15734f80-5001-11eb-8f49-67e619995356.jpg)

## Screenshots

![image](https://user-images.githubusercontent.com/6595611/103752213-53707380-5001-11eb-9189-8e04cfe4b546.png)
![image](https://user-images.githubusercontent.com/6595611/103752255-64b98000-5001-11eb-822d-eac4305f0a90.png)
![image](https://user-images.githubusercontent.com/6595611/103752290-71d66f00-5001-11eb-8534-b9fc368973f2.png)

## Your setup (please complete the following information)

- Unity Version: 2019.4.6f1
- MRTK Version: v2.6 - `mrtk_development` / commit [1ba4258f74](https://github.com/microsoft/MixedRealityToolkit-Unity/commit/1ba4258f74)

## Target platform (please complete the following information)

N/A

## Additional context

N/A

**Comment by keveleigh** [comment]
I'm not able to repro this...did you possibly have your "Toggle Tool Hand Rotation" setting set to Global instead of Local?

![image](https://user-images.githubusercontent.com/3580640/123718868-17420100-d835-11eb-9c9d-3ff4847f7449.png)

**Comment by jjimenezg93** [comment]
I can't repro either, so that must be it, sorry about the hassle.
