### ISSUE TITLE
Build tool cannot find solution when product name contains CJK characters

### ISSUE THREAD

**Issue by zxubian** [microsoft/MixedRealityToolkit-Unity#9104]
## To reproduce

1. In Project Settings/Player set Product Name to テスト ("test" in Japanese)
2. In the MRTK Build Window, press "Build All"

## Expected behavior

The Unity project is built, and then the appx is built.

## Actual behavior
The Unity project is built, but then the build tool fails and gives a "Unable to find solution to build from!" message.

## Your setup

- Unity Version 2019.4.16f1 (LTS)
- MRTK Version 2.5.1 (UPM)

## Target platform
- Tested when building for HoloLens 2 (UWP), but probably occurs with other platforms

**Comment by davidkline-ms** [comment]
The error is coming from UwpAppxBuildTools.cs (BuildAppxAsync)

```
if (!File.Exists(slnFilename))
{
    Debug.LogError("Unable to find Solution to build from!");
    return IsBuilding = false;
}
```

File.Exists() is failing. Could be a culture settings issue or there may be a better API to use.

**Comment by MaxWang-MS** [comment]
I was not able to reproduce this issue using the Unity version you specified and MRTK 2.5.3 (UPM). Could you try to see if you can reproduce the issue with the latest MRTK version (2.5.3) and if so please share more details and/or create a minimum repro project.

**Comment by zxubian** [comment]
@MaxWang-MS 
I also tried making an empty repro project in Unity, and was not able to reproduce it, so the reason might be different.
However, the original error (Unable to find solution to build from!) still happens on my production project with MRKT v2.5.3.
The variable "slnFilename" has the value "Builds/WSAPlayer\MRコンパス.sln" at the time of error.
For the record, the file does exist in the directory, and I am able to successfully build & deploy to device by directly opening the solution with VS2019.

**Comment by MaxWang-MS** [comment]
Please reopen the issue if you are still encountering it.
