### ISSUE TITLE
App not starting on device using OpenXR Plugin Version 0.1.2-preview.2

### ISSUE THREAD

**Issue by eusebiu** [microsoft/MixedRealityToolkit-Unity#9105]
## Describe the bug

An MRTK 2.5.3 app is not started from Unity Editor 2020.2.1 using OpenXR Plugin Version 0.1.2-preview.2.

## To reproduce

1. Install/Update OpenXR Plugin Version 0.1.2-preview.2 package
2. Configure an MRTK app to use OpenXR Profile
3. Enable OpenXR & features from Project Settings/XR Management; Set OpenXR Runtime to Oculus
4. Start app

## Expected behavior

App starts.

## Actual behavior

App does not start (enters in simulation mode)

## Your setup (please complete the following information)

- Unity Version 2020.2.1
- MRTK Version 2.5.3

## Target platform (please complete the following information)

- Oculus Link 23

**Comment by eusebiu** [comment]
Fixed by restarting the editor.

**Comment by keveleigh** [comment]
It might be worth reporting this on the Unity forums, if you're able to consistently repro! Seems like something they'd need to fix
