### ISSUE TITLE
Incorrect perceived depth of holograms with Unity apps

### ISSUE THREAD

**Issue by HaydenLeeteUC** [microsoft/MixedRealityToolkit-Unity#9116]
## Describe the bug

I'm writing a program that requires simple virtual objects to rest on the ground; objects are placed on the ground as defined by the spatial awareness mesh, but both the objects and the spatial awareness mesh appear to be floating above the ground. Notably, objects and the mesh appear to rest on the environment correctly when looking at the scene with one eye at a time, implying correct positioning in world. 

The issue appears in all of my Unity projects including MRTK examples, but not in the mixed reality home where I have tested for the issue by using the 3D objects app to place objects around my environment. It seems like the virtual cameras in Unity do not have the same spacing as my eyes, though the issue persists after calibration and between users.

## Expected behavior

Stationary holograms appear at the correct depth with reference to the environment.

## Your setup

- Unity 2019.4.4f1
- MRTK v2.4.0

## Target platform

- HoloLens 2

**Comment by HaydenLeeteUC** [comment]
Upgrading to Unity 2019.4.17f1 has fixed the issue for me. I upgraded to MRTKv2.5.3 first, but the issue was not resolved until I also updated Unity.

**Comment by keveleigh** [comment]
Ah yeah, this sounds like an issue that was fixed in Unity's Windows XR Plugin. Updating Unity must have triggered an update of the package as well.
