### ISSUE TITLE
Cursor lost after pressing trigger button on motion controller

### ISSUE THREAD

**Issue by angelaHillier** [Microsoft/MixedRealityToolkit-Unity#912]
While trying out the new BoundaryTest and MotionControllerTest scenes in an immersive device, the cursor disappeared after pressing the trigger button on a motion controller. There was no pointer/grip ray visible to indicate where the controllers were pointing either. We need some visual indication for what the user is looking/pointing at.

**Comment by shenshen211** [comment]
hello angelaHllier, I want to know the schedule of dev_mixedreality branch，can I use the gesture and spatial mapping property in my development with ue4 now?

**Comment by jessemcculloch** [comment]
@angelaHillier - Is the trigger how you would normally cause a teleportation?  I ask because the teleportation target seems to be very, very small in the HTK.  It's also hard to tell that you have done it because the floor recenters when you do, so you can't really tell that you teleported at all, even when you have.  I am wondering if this is what is happening in your case.

**Comment by jessemcculloch** [comment]
@shenshen211 - Unreal Engine is not supported for HoloLens or Mixed Reality Development

**Comment by NeerajW** [comment]
@angelaHillier I just tried the MotionControllerTest.unity and cursor stealing worked.
1. Ensure your motion controller has latest firmware.
2. Unpair/re-pair
3. Deploy scene
4. Turn on motion controller right, see log show up 'Right controller'.
5. Press trigger button and CursorOffHologram follows your motion controller.
6. When on the cube we see CursorOnHologram

Hope this helps.

**Comment by angelaHillier** [comment]
Thanks Neeraj,
I'm updating my OS and firmware today, so I'll give it another try :)

**Comment by angelaHillier** [comment]
Closing. I was able to confirm that with new OS/driver update, this does work.
Thanks!
