### ISSUE TITLE
About Hands renderer Bug

### ISSUE THREAD

**Issue by DN-kyeongminKim** [microsoft/MixedRealityToolkit-Unity#9122]
## Describe the bug

You can check the bug with the two hand rendering of MRTKv2 via the link.
https://dnsoftcokr.sharepoint.com/:v:/s/msteams_ed61d1/EcrImiBZw0lNq1UXtIF039sBtk9UsnPu0W5sOXVGSIOKrQ?e=vtKmW0

1. Rendering of the right hand continues to overlap.

2. Hand joint rendering is separated and fixed in the air.

Is there any way to fix this bug?

I desperately want help.

## To reproduce

Occurs intermittently at any time during use.
It is difficult to determine the exact point of time.
It often happens when performance drops.

## Screenshots

https://dnsoftcokr.sharepoint.com/:v:/s/msteams_ed61d1/EcrImiBZw0lNq1UXtIF039sBtk9UsnPu0W5sOXVGSIOKrQ?e=vtKmW0

## Your setup (please complete the following information)

- Unity Version [2019.4.15f]
- MRTK Version [v2.4.0]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by polar-kev** [comment]
hey @DN-kyeongminKim, it looks like you linked us to a sharepoint directory that we don't have access to. Can you copy and paste any images or videos you have directly into github?

**Comment by keveleigh** [comment]
This sounds like the issue fixed in 2.7.0 with #9890. Please re-open if you're still experiencing in 2.7.0.
