### ISSUE TITLE
How to know raycast hit position

### ISSUE THREAD

**Issue by rjtshrm** [microsoft/MixedRealityToolkit-Unity#9134]
I am new to hololens2. I want to instantiate a new object based on the raycast hits. For this, I want to detect planes in the hololens view. Furthermore, when I point ray from my finger to any direction it should instantiate a game object if it hits that plane. Is there any demo for this or solution on how to do this.

**Comment by eusebiu** [comment]
You might need to use the ```IMixedRealityFocusHandler``` (for simple focus) or ```PointerHandler``` (for Select action) - this is for general objects (please install the samples to see how they work).
If you are referring to the Spatial Awareness meshes, check if the Spatial Awareness API helps you:
e.g. https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.SpatialAwareness.SpatialAwarenessMeshObject.html

**Comment by polar-kev** [comment]
Hey @rjtshrm, we don't currently have plane finding in the MRTK as yet. There is however a getting started tutorial that shows you how to use the tap-to-place (it's in section 7. Interacting with 3D objects) https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-01
