### ISSUE TITLE
Tap to Place Sharing

### ISSUE THREAD

**Issue by TinyTangS** [Microsoft/MixedRealityToolkit-Unity#914]
Hello everyone:
When work with Spectator View sample ,you suggest using Unet to share the scene. So I tried using Unet to sharing my scenes. I had tried to using the "UNetSharedHologram.CS" which is coming from the Spectator View sample.But there is a problem. In the server you can tap and place the model at where you want ,the client also can see where it is . On the contrary the client tap and place the model, the server has no reaction. I want using this scripts for my project, how can I deal with it ,or can you give me any more sample to study how to share my scenes with Unet?

**Comment by TinyTangS** [comment]
At the same time , the sample for us to study how to make the share scene is too poor. The academy of 240   was a way to share scene how concise it is.The academy of 250 with a bate unity which is without archive. How poor for me to study for it.

**Comment by davidkline-ms** [comment]
The academy courses should be updated correctly by a newer Unity 2017 release automatically when opened.
