### ISSUE TITLE
Mixed Reality update broke compatibility with Samsung Odyssey Plus! Huge problem!

### ISSUE THREAD

**Issue by Nashismo** [microsoft/MixedRealityToolkit-Unity#9141]
Dear Guys:

I do not know if this is the right place, but I have a HUGE problem with my VR headset, a Samsung Odyssey Plus and Windows Mixed Reality.

I bought this VR headset about a month ago, and everything was working great. Until I uninstalled the Mixed reality software from Windows 10, then I install it again (cannot remember why I did this, I was troubleshooting other things).

So, Saturday 9 at about 10pm eastern time, I re installed the Mixed Reality softwate. What happened then was atrocious! I was stuck with a FOV of about 60! My VR headset became a cyclope!

I said to myself, maybe is the Nvidia drivers, re install the old drivers (the ones that I used the first month I had the Samsung Odyssey), but no, this woudn't fix anything.

I ended up installing the entire Windows 10 all over again. Then I re installed EVERYTHING and NO! The VR headset still had the problem of the reduced FOV!

The only conclusion I got, was that on that very same day saturday January 9, 2021, something happened, and the Mixed Reality update from that day ruined compatibility with my VR headset.

My system: i59400f, 240gb SSD, 32GB DDR4, EVGA 1080ti

Guys I have elevated this problem using the Windows 10 feature to do so, but there has been 5 days and no one at Microsoft does nothing for me, or answers my questions in any way.

Couls you guys help me somehow? You are my only chance to fix my VR headset, I live in Chile and there is ZERO options for me, even if I take my headset back to the store, there is no other options to buy.

Thank you from the bottom of my heart,

Ignacio H.

**Comment by polar-kev** [comment]
Hey @Nashismo, this doesn't look like an MRTK bug. Have you considered messaging the Samsun tech support? It looks like they have a community, email and web support: https://www.samsung.com/us/support/owners/product/hmd-odyssey-plus-mixed-reality
