### ISSUE TITLE
Issue in scrollbar(mrtk 2.5.1) using Script

### ISSUE THREAD

**Issue by IrfanKureshi8792** [microsoft/MixedRealityToolkit-Unity#9145]
Issue in scrollbar(mrtk 2.5.1) using Script we are using multiple dynamic scrollbar in our application. when we try to  update collection first time at that time scroll is working fine but when we are updating collection second time with more node/values then scroll is not working properly.
can anyone explain me what i am missing here?

**Comment by polar-kev** [comment]
Hey @IrfanKureshi8792, are you using the Scrolling Object Collection or UnityUI here? Is it possible for you to provide steps to reproduce and screentshots?

**Comment by MaxWang-MS** [comment]
Please reopen the issue if you are still encountering it.
