### ISSUE TITLE
Sharing Array System.AccessViolationException

### ISSUE THREAD

**Issue by maxenceboucas** [Microsoft/MixedRealityToolkit-Unity#915]
Hi,

I'm sharing RemoteHead , a Raycast and un Array trough CustomMessages.

But since i'm sending the array i receive this error:

> System.AccessViolationException 
HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

that append on broadcasting the message.
Thanks for help

**Comment by StephenHodgson** [comment]
This issue might need to be migrated to the main [MixedRealityToolkit](https://github.com/Microsoft/MixedRealityToolkit) repo.

**Comment by maxenceboucas** [comment]
migrated at [Sharing Array AccessViolationException #112](https://github.com/Microsoft/MixedRealityToolkit/issues/112)
