### ISSUE TITLE
Hand joint positions do not regain tracking after temporary loss of hand tracking.

### ISSUE THREAD

**Issue by HaydenLeeteUC** [microsoft/MixedRealityToolkit-Unity#9151]
## Describe the bug

Occasionally when hand tracking is lost, the joint positions for that hand are not discarded nor subsequently updated when hand tracking is regained. 

When tracking of the hand is regained, an additional persistent hand mesh that does not disappear when tracking is lost is rendered on top of the hand in question's last known pose. In the video attached under **Screenshots**, you can see there are a total of three hand meshes being rendered after the bug occurs. All hand meshes track their hands correctly before and after the bug occurs, but the joint positions are not updated correctly after the bug occurs. 

I am not able to find a more reliable method of repoducing this bug other than repeatedly moving hands out of the headset's FOV, but it occurs regularly while testing my apps. The tracking does not resume normal function until the app is restarted.

## To reproduce

**Project Setup:**
1. Create new Unity project and import MRTK.
2. Set MixedRealityToolkit profile to DefaultXRSDKConfigurationProfile.
_Edit:_ Enable XR Plug-in mangament in project settings
3. Add gameobject with mesh and Orbital solver.

**In app reproduction of bug:**
1. Move hand out of tracking view of the headset, then back in.

## Expected behavior

No duplicate hand meshes are displayed, and joint tracking resumes on physical hand instead of the old hand joint data

## Screenshots

Shows expected behaviour the first time hand lost and regained, Followed by faulty behaviour the second time.
https://youtu.be/-8yrjCxPk3k

## Your setup

- Unity 2019.4.17f1
- MRTK v2.5.3 
- Also observed using MRTK v2.4.0 and Unity 2019.4.4f1

## Target platform

- HoloLens 2

**Comment by polar-kev** [comment]
Hey @elbuhofantasma, can you repro and see if this happens in legacy vs just XR SDK?

**Comment by raymondpols** [comment]
I seem to have the same problem. While using my HoloLens2 app, more hands get stuck and freeze in the scene. 
![image](https://user-images.githubusercontent.com/29376541/106803995-1d0c2f80-6665-11eb-8b8a-07b7978197f1.png)
I'm using Unity 2020.1.10f1 (but same happens in Unity 2020.2.2f1) and using MRTK 2.5.3, 
Any ideas how to fix this?

**Comment by ModischFabrications** [comment]
Same problem here, but it came up only in the last few weeks. I think the chance for "ghost hands" increased with cpu load, but I can't pin any special cause.

**Comment by keveleigh** [comment]
This sounds related to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9165

**Comment by keveleigh** [comment]
The stuck hand tracking should be fixed via #9890 in the upcoming 2.7.0 release. Please re-open if you're still able to repro on 2.7.0.
