### ISSUE TITLE
Teleport Marker is super small

### ISSUE THREAD

**Issue by jessemcculloch** [Microsoft/MixedRealityToolkit-Unity#916]
When using the Mixed Reality Teleport script, the teleport marker is super tiny, and you can't really see it, it does not contrast well.  It would be really nice if we could get the same or similar visuals that are being used in the shell/cliff house for this.

We can probably include this at the same time as we make the changes to #843 provided we can get the visual assets

**Comment by LanceMcCarthy** [comment]
I second this.

**Comment by StephenHodgson** [comment]
Already addressed in #918
