### ISSUE TITLE
Oculus Device Manager prefab constantly reverts to non-working state on UPM

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#9160]
## Describe the bug

The Oculus Device Manager prefab always reverts changes made after running "Add Oculus Integration Tool". This is due to the prefab's guids not matching the guid's provided by the Oculus Integration Package as it updates. 

## To reproduce

1. Add MRTK foundations via UPM
2. Add Oculus Integration package
3. Run MixedRealityToolkit -> Utilities -> Oculus -> Integration Oculus Integration Unity Modules
4. See that the OculusXRSDKDeviceManagerProfile asset has the prefabs set correctly
5. Reboot unity and see that the asset has been reverted.

## Expected behavior

DeviceManger settings should saved between sessions

![image](https://user-images.githubusercontent.com/39840334/105532823-58981880-5cb9-11eb-97a3-169069184b38.png)

**Comment by RogPodge** [comment]
To be fixed in a release coming soon.

**Comment by polar-kev** [comment]
This is fixed in the MRTK 2.5.4 release that just went out today.
