### ISSUE TITLE
LED Tracking

### ISSUE THREAD

**Issue by Manuel-Meyer** [microsoft/MixedRealityToolkit-Unity#9171]
## Describe the problem

I tried to implement LED tracking with Hololense tracking cameras. And I thought, hey there must be an easy way to do this, because it is exactly how the motion controllers of windows MR Headsets are tracked. But I found no easy solution. We eaven habe QR-Code tracking but no LEDs.
Have I missed something or is there no easy solution?

## Describe the solution you'd like

An easy way to configure some kind of LED layout, that is being tracked.

## Describe alternatives you've considered

Of course I could use QR-Tracking, but I thought LED tracking should be much faster and possible over greater distances.

**Comment by Zee2** [comment]
We recommend using the QR tracking library. https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/qr-code-tracking-overview
