### ISSUE TITLE
MRTK_SurfaceReconstruction.mat and SpherePulseMat.mat are missing from 2.5.3

### ISSUE THREAD

**Issue by aprilspeight** [microsoft/MixedRealityToolkit-Unity#9175]
## Describe the bug

The materials MRTK_SurfaceReconstruction.mat and SpherePluseMat.mat are missing from MRTK 2.5.3. this was shared with me by someone in the community. I have confirmed that the material is missing. The material _was_ in 2.4. 

## To reproduce

1. Go to Assets > MRTK > SDK > Experimental > PulseShader >Materials.

## Expected behavior

Both MRTK_SurfaceReconstruction.mat and SpherePulseMat.mat should be available in either the folder or somewhere in the package.

## Screenshots

None.

## Your setup (please complete the following information)

- Unity Version 2019.4.12f1
- MRTK Version 2.5.3

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

None.

**Comment by CDiaz-MS** [comment]
Hi @aprilspeight,

In MRTK 2.5 the SpherePulseMat.mat was renamed to the MRTK_Pulse_ArticulatedHandMeshPurple in [this PR](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8307)

![image](https://user-images.githubusercontent.com/53493796/106075603-cd58c180-60c2-11eb-895d-7b92a56e467f.png)

**Comment by aprilspeight** [comment]
thanks!
