### ISSUE TITLE
UnityEngine.XR.XRDevice.GetNativePtr() always return IntPtr.Zero 

### ISSUE THREAD

**Issue by Namithia20** [microsoft/MixedRealityToolkit-Unity#9183]
## Overview
I'm trying execute this code on Hololens 2 applying SceneUnderstanding SDK, but the method UnityEngine.XR.XRDevice.GetNativePtr() always return IntPtr.Zero. 

¿There is other way to get a NativePtr?

```
IntPtr nativeStruct = UnityEngine.XR.XRDevice.GetNativePtr();           
if (nativeStruct != IntPtr.Zero) 
{
      HolograhicFrameData holoFrameData = Marshal.PtrToStructure<HolograhicFrameData>(nativeStruct);
      SpatialCoordinateSystem unityCoordinateSystem = SpatialCoordinateSystem.FromNativePtr(holoFrameData.ISpatialCoordinateSystemPtr);
      SpatialCoordinateSystem sceneCoordinateSystem = SpatialGraphInteropPreview.CreateCoordinateSystemForNode(scene.OriginSpatialGraphNodeId);
      sceneToUnityTransform = sceneCoordinateSystem.TryGetTransformTo(unityCoordinateSystem);
}
```
## Setup
Unity Version 2020.2
MRTK Version 2.5.3
OpenXR Plugin 0.1.2
Windows XR Plugin 4.2.1
XR Plugin Management 4.0.0-pre.2

**Comment by keveleigh** [comment]
>OpenXR Plugin 0.1.2
>Windows XR Plugin 4.2.1

Using Unity new XR SDK plugin, this API returning `IntPtr.Zero` is expected. I can't find the exact Unity forum post anymore, but one of their engineers mentioned that this is intentional.

If you're looking for the underlying `SpatialCoordinateSystem`, you can use a different API: the OriginSpatialCoordinateSystem under https://docs.unity.cn/Packages/com.unity.xr.windowsmr@2.6/api/UnityEngine.XR.WindowsMR.WindowsMREnvironment.html

**Comment by Namithia20** [comment]
Thanks, but now I have a new problem on Hololens 2 Device. Whe the app is running on device I recibe the next error: "Unable to load DLL WindowsMRXRSDK: the specified module could not found".

¿Windows XR Plugin its not compatible with UWP? ¿Are there any alternative with OpenXR?

**Comment by keveleigh** [comment]
>Windows XR Plugin its not compatible with UWP

It definitely is! Are there any other logs around the DLL load issue? What architecture are you building (ARM vs ARM64)? Early releases of Windows XR Plugin didn't support ARM, but anything recent should be fine.

**Comment by Namithia20** [comment]
That error it's show on run time on Device, like an exception. In Editor it don't show any error/log about DLLs. 
The architecture for building is ARM64 (I always use that for Hololens 2).
My setup is:  
- SDK 10.0.19041.0
- Unity Version 2020.2
- MRTK Version 2.5.3
- OpenXR Plugin 0.1.2
- Windows XR Plugin 4.2.1
- XR Plugin Management 4.0.0-pre.2

**Comment by Namithia20** [comment]
Hi, finaly I'm solved the DLL WindowsMRXRSDK error (Im not sure how excatly, because I tried a lot of changes.). 

In Visual Studio, I'm installed all abailables versions of Windows SDK (I was desperated). 
I'm back de XR plugin to version 3.2.16 (removing OpenXR too) and the Windows XR plugin to version 3.4.0
I uninstalled MSBuild too and I rebuilded the proyect step by step. 

With all that, it's works. :) One thousand of thanks @keveleigh ! 

Now, it's not necesary using the structure 'holoFrameData' and 'Marshal.PtrToStructure<T>()'.

Old code:
```
IntPtr nativeStruct = UnityEngine.XR.XRDevice.GetNativePtr();           
if (nativeStruct != IntPtr.Zero) 
{
      HolograhicFrameData holoFrameData = Marshal.PtrToStructure<HolograhicFrameData>(nativeStruct);
      SpatialCoordinateSystem unityCoordinateSystem = SpatialCoordinateSystem.FromNativePtr(holoFrameData.ISpatialCoordinateSystemPtr);
      SpatialCoordinateSystem sceneCoordinateSystem = SpatialGraphInteropPreview.CreateCoordinateSystemForNode(scene.OriginSpatialGraphNodeId);
      sceneToUnityTransform = sceneCoordinateSystem.TryGetTransformTo(unityCoordinateSystem);
}
```

New code:
```
IntPtr nativePtr = WindowsMREnvironment.OriginSpatialCoordinateSystem;    
           
if (nativeStruct != IntPtr.Zero) 
{
      SpatialCoordinateSystem unityCoordinateSystem = SpatialCoordinateSystem.FromNativePtr(nativePtr);
      SpatialCoordinateSystem sceneCoordinateSystem = SpatialGraphInteropPreview.CreateCoordinateSystemForNode(scene.OriginSpatialGraphNodeId);
      sceneToUnityTransform = sceneCoordinateSystem.TryGetTransformTo(unityCoordinateSystem);
}
```

**Comment by chrisnasseh** [comment]
> > Windows XR Plugin 4.2.1
> 
> Using Unity new XR SDK plugin, this API returning `IntPtr.Zero` is expected. I can't find the exact Unity forum post anymore, but one of their engineers mentioned that this is intentional.
> 
> If you're looking for the underlying `SpatialCoordinateSystem`, you can use a different API: the OriginSpatialCoordinateSystem under https://docs.unity.cn/Packages/com.unity.xr.windowsmr@2.6/api/UnityEngine.XR.WindowsMR.WindowsMREnvironment.html
> 
> Note that this only works for the Windows XR Plugin. If you're using OpenXR, we'd have to find another way.

I have looked at so many different forums but still can't find a way to get the IntPtr value in OpenXR for the Coordinate System.
Could anyone help me with that?

The original line of code was:
		// WorldOriginPtr = UnityEngine.XR.WindowsMR.WindowsMREnvironment.OriginSpatialCoordinateSystem;

When I write
		// WorldOriginPtr = SpatialLocator.GetDefault().CreateStationaryFrameOfReferenceAtCurrentLocation().CoordinateSystem;

I get a compilation error that says implicit conversion to IntPtr isn't possible.

**Comment by keveleigh** [comment]
@chrisnasseh For OpenXR, you can use https://docs.microsoft.com/dotnet/api/microsoft.mixedreality.openxr.perceptioninterop.getscenecoordinatesystem?view=mixedreality-openxr-plugin-1.4#microsoft-mixedreality-openxr-perceptioninterop-getscenecoordinatesystem(unityengine-pose) with `Pose.identity` as the parameter.

**Comment by chrisnasseh** [comment]
> If you specifically need the IntPtr for your scenario, let me know and I can look into retrieving that.

Since I am working on an environment that was written with the Legacy XR in mind, the entire script relies on the IntPtr for WorldOrigin coordinates. If it is possible to find that, it would allow me to adapt the entire code to OpenXR. Thanks in advance.
