### ISSUE TITLE
Improve clarity on when / how to use XRSDK profiles

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#9185]
From the holodevelopers slack group:

Ben N. Yesterday at 12:01 PM
Apologizes if this has been addressed already (seems like there's a bunch of related posts recently), but it appears that the MRTK example scenes in 2.5.3 don't work out of the box on HL2 if you're using Unity's XR SDK. The MRTK example scenes have configuration profiles that are not compatible with Unity's XR SDK. Following the MRTK documentation here, it appears that the Default HL2 profile doesn't work with the XRSDK (e.g., it's still using the old Windows MR camera settings), and using the XRSDK default profile doesn't work with HL2 out of the box either (e.g., the skybox is on). Or am I missing something obvious here?

David Kline  21 hours ago
@Ben N., the team is looking at better ways to handle the Unity XR platform supported by the example scenes.
They currently utilize Legacy XR (required by 2018.4).
To enable them to support XR SDK on 2019.4 and newer, please change DefaultMixedRealityToolkitConfigurationProfile to  DefaultMixedRealityToolkitXRSDKConfigurationProfile.
Thanks!

Ben N.  20 hours ago
Ah I see, thank you! Is that documented somewhere? It would be nice if it were on that page I linked to or elsewhere.

**Comment by polar-kev** [comment]
Hey @keveleigh, what's the status on these docs updates?

**Comment by keveleigh** [comment]
@polar-kev In progress!
