### ISSUE TITLE
Allow temporarily disabling the teleport system

### ISSUE THREAD

**Issue by eusebiu** [microsoft/MixedRealityToolkit-Unity#9186]
## Describe the problem

The thumb stick/touch pad is currently used in the teleport system but there are use cases when that input needs to be used in other functions.

## Describe the solution you'd like

API calls that disables and enables the system on demand.

## Describe alternatives you've considered

Using a different root profile but this impacts all systems.

**Comment by eusebiu** [comment]
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7100

**Comment by RogPodge** [comment]
You should be able to disable the teleport system using the MRTK profile

To the MixedRealityToolkit GameObject in the hierarchy and then disable the system in the inspector

![image](https://user-images.githubusercontent.com/39840334/106490404-c72c6180-6483-11eb-8eb1-8025d3b78ea0.png)

**Comment by RogPodge** [comment]
As far as disabling it at runtime, we're looking at it with the above issue so stay tuned.
