### ISSUE TITLE
BuildWindow sometimes opens out of screen with 2 monitors running on different DPI

### ISSUE THREAD

**Issue by devedse** [Microsoft/MixedRealityToolkit-Unity#919]
After strugling a bit with my BuildWindow not appearing whenever I clicked it from the HoloToolkit menu I found out that it had gone out of my screen.

To get it back I had to change the DPI of my main monitor to 100% after which it would appear somewhere on my right screen again.

To reproduce the issue:

1. Open Unity + BuildWindow on screen running on 100% dpi
2. Drag Unity to screen running 200% dpi
3. Start dragging buildwindow from screen with 100% dpi to screen with 200% dpi. It now disappears into infinity. (When you now release your mouse it's gone).

I'm not sure if this an issue that can be solved in the MRT, but if we can do something like whenever you open the window that it will appear in a visible position, that would be great.

**Comment by StephenHodgson** [comment]
Already on top of it.

**Comment by devedse** [comment]
Woo thanks
