### ISSUE TITLE
Headlock camera in MRTK Unity

### ISSUE THREAD

**Issue by 9and3** [microsoft/MixedRealityToolkit-Unity#9196]
## Describe the bug

Hello! When I try to holographic remote the example hand tracking MRTK scene in Unity by clicking play, the camera on the Hololens2 is locked, it's like I am watching a 2D flat scene. It's like the headset isn't placed in a 3D space.
Please refer[ to this post ](https://forum.unity.com/threads/anything-i-build-it-always-shows-as-2d-on-the-actual-hololens-2-arm64-device.920135/)which exposes the same issue.

## To reproduce

1. Create a fresh new Unity project
2. Install XR-plu gin menagement
3. import MRTK foundation unitypackage
4. import MRTK examples unitypackage
5. enable remoting on project settings
6. import examples > demo > first scene in HandTracking of MRTK folder
7. run the remote

## Expected behavior

The remoting doesn't show any features of MRTK and is headlocked

## Your setup (please complete the following information)

- Unity Version 2019.4.15f
- MRTK Version 2.5.3

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
When using XR Plugin Management, you'll need to follow the steps at https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html and use the default XR SDK profile. My guess is you're using the regular defaults, which only work with legacy XR. #9185 is tracking improvements to our docs about this scenario.

**Comment by 9and3** [comment]
Hello @keveleigh and thank you so much for taking the time to answer. MRTK is such an amazing toolbox, as a new Hololens2 developer though it is a very confusing time to decide which " XR pipeline " in Unity I should use with MRTK: XR Legacy, XR SDK, OpenXR... I am aware that part of the confusion comes of course from my inexpertise on the subject. Having said that, what kind of Unity set would you recommend for a Hololens2 + MRTK project starting now and ending in 3-4 years? Thank you !

**Comment by RogPodge** [comment]
@9and3 I think the best way to use XR with Unity in the short and medium-term is XR SDK, as Unity is currently pushing it as the go-to platform: https://docs.unity3d.com/Manual/configuring-project-for-xr.html. OpenXR will be getting more support in the coming few years, but it uses the same fundamental XR-Plugin management system that XR SDK uses, so it's better to hop on that tech stack for now. 

Legacy XR is being phased out of Unity, so I would definitely recommend moving to a newer "XR Pipeline"
