### ISSUE TITLE
Hiding the Keyboard when using a bluetooth keyboard

### ISSUE THREAD

**Issue by jburfield92** [Microsoft/MixedRealityToolkit-Unity#920]
I have a bluetooth keyboard paired with my hololens and when I tap on a input field that opens the HoloToolkit keyboard, the keyboard does not disappear when typing with the bluetooth keyboard. I'd expect it to hide itself when using an external keyboard, like it does when you type in the address bar in Microsoft Edge in the HoloLens.

Having both the HoloToolkit Keyboard visible and a bluetooth keyboard, causes problems if you tap on any of the keys on the HoloToolkit keyboard. It will start ignoring input from the bluetooth keyboard until you tap in the HoloToolkit keyboard's textbox or reopen the keyboard again.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
