### ISSUE TITLE
Using SpatialUnderstanding Saved Mesh in Unity Editor

### ISSUE THREAD

**Issue by dannycarrera** [Microsoft/MixedRealityToolkit-Unity#922]
Using the SaveSpatialUnderstanding scene from the SavingSpatialMeshes example, I have saved a nice mesh of my environment. After converting the room to a .obj, In the SpatialUnderstandingExample scene, I have set the Room Model to use this mesh.
When I run the example in the editor, it loads the mesh (white color to represent SpatialMapping) but it doesn't properly scan and process the space.  I only see the green mesh sporadically spaced out. I don't think this is expected behaviour.

Better yet, is it possible to use this saved Mesh and have the scanned state = Done? This would really speed up development because we can test in the editor, as opposed to continuously deploying to a HoloLens or the emulator.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
