### ISSUE TITLE
2 'Script attached to...' warnings are generated when building examples in Unity 2019

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9227]
## Describe the bug

In Unity 2019.4.19 with the 'release/2.5.4' branch when the building the example scenes, the Unity console has 2 'Script attatched to...' warnings, but builds successfully. These 2 warnings are generated when building each example scene. please refer to #9228 for more information.

## To reproduce

1. Clone the 'release/2.5.4' branch.
2. Open project in Unity 2019.4.19.
3. Switch project to XR SDK.
3. Build any example scene.
4. Look at Unity console output.

## Expected behavior

No 'Script attached to...' errors appear when building the example scene.

## Screenshots

Unity console warnings:
![image](https://user-images.githubusercontent.com/65038391/106851558-52b41700-666b-11eb-8d19-7ba1ae89fb3f.png)

## Your setup (please complete the following information)

- Unity Version **2019.4.19f1**
- MRTK Version **release/2.5.4**
- XR System **XR SDK** 

## Target platform (please complete the following information)

- UWP
- HoloLens 2

**Comment by keveleigh** [comment]
These are printed by Unity scripts. I've only seen it happen with XR SDK, but haven't been able to narrow down the cause.

**Comment by keveleigh** [comment]
Going to close this out as External.
