### ISSUE TITLE
2 'Script attached to...' warnings are generated when building examples scenes in Unity 2020

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9228]
## Describe the bug

In Unity 2020.2.2 with the 'release/2.5.4' branch when the building the example scenes, the Unity console generates 2 'Script attached to...' warnings, but builds successfully. This issue effects all example scenes built with the XR SDK. This issue does not occur in OpenXR, Legacy XR, or Unity 2018 (Legacy XR)

## To reproduce

1. Clone the 'release/2.5.4' branch.
2. Open project in Unity 2020.2.2.
3. Build an effected example scene
4. Look at Unity console output.

## Expected behavior

No 'Script attached to...' warnings appear when building the example scene.

## Screenshots

![image](https://user-images.githubusercontent.com/65038391/106852338-c3a7fe80-666c-11eb-8201-af339b9f7ace.png)

## Your setup 
- Unity Version **2020.2.2**
- MRTK Version **release/2.5.4**

## Target platform 

- UWP
- HoloLens 2
- XR SDK

## Additional information

This issue is similar to #9227 but contains more details.

This issue effects the following example scenes and profiles in XR SDK (Note: I did not test all profiles):
-  **Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionGestureEventsExample.unity**
DefaultXRSDKConfigurationProfile
GestureEventsConfigurationProfile
DefaultHoloLens2ConfigurationProfile

- **Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity**
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile

- **Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionRecordArticulatedHandPose.unity**
RecordArticulatedHandPoseConfigurationProfile
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile

- **Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionTouchablesExample.unity**
DefaultMixedRealityToolkitConfigurationProfile
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile

- **Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandMenuExamples.unity**
HandMenuMixedRealityToolkitConfigurationProfile
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile

- **Assets/MRTK/Examples/Demos/HandTracking/Scenes/NearMenuExamples.unity**
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile

- **Assets/MRTK/Examples/Demos/Audio/Scenes/AudioLoFiEffectExamples.unity**
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile
DefaultMixedRealityToolkitConfigurationProfile

- **Assets/MRTK/Examples/Demos/Audio/Scenes/AudioOcclusionExamples.unity**
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile
DefaultMixedRealityToolkitConfigurationProfile

- **Assets/MRTK/Examples/Demos/Gltf/Scenes/Glb-Loading-Demo.unity**
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile
DefaultMixedRealityToolkitConfigurationProfile

- **Assets/MRTK/Examples/Demos/Gltf/Scenes/Gltf-Loading-Demo.unity**
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile
DefaultMixedRealityToolkitConfigurationProfile

- **Assets/MRTK/Examples/Demos/ScrollingObjectCollection/Scenes/ScrollingObjectCollection.unity**
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile

- **Assets/MRTK/Examples/Demos/Solvers/Scenes/SolverExamples.unity**
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile

- **Assets/MRTK/Examples/Demos/Solvers/Scenes/SurfaceMagnetismSpatialAwarenessExample.unity**
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile
DefaultMixedRealityToolkitConfigurationProfile

- **Assets/MRTK/Examples/Demos/Solvers/Scenes/TapToPlaceExample.unity**
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile
DefaultMixedRealityToolkitConfigurationProfile

- **Assets/MRTK/Examples/Demos/EyeTracking/Scenes/EyeTrackingDemo-00-RootScene.unity**
EyeTrackingDemoConfigurationProfile
DefaultHoloLens2ConfigurationProfile
DefaultXRSDKConfigurationProfile

**Comment by keveleigh** [comment]
These are printed by Unity scripts. I've only seen it happen with XR SDK, but haven't been able to narrow down the cause.

**Comment by keveleigh** [comment]
Going to close this out as External.
