### ISSUE TITLE
Speech input source: Add a confidence level selector

### ISSUE THREAD

**Issue by cybergoulion** [Microsoft/MixedRealityToolkit-Unity#925]
As it is in SpeechInputSource, new keyword recognizers are created with the default confidence level. This is problematic epsecially if the application targets non native speakers of the spoken language, because confidence cannot be set to ConfidenceLevel.Low.  This can be solved by adding confidence level enumeration selector for a property in the inspector and using the alternative constructor for the new KeywordRecognizer in the Start() function as in:

`keywordRecognizer = new KeywordRecognizer(keywords, ConfidenceLevelSelection);`

**Comment by StephenHodgson** [comment]
Great idea!

**Comment by cybergoulion** [comment]
@StephenHodgson I actually already implemented it and use it, but I am not familiar with the procedure to contribute the changes to the project.

**Comment by StephenHodgson** [comment]
Fork the repo and make a pull request and be sure to sign the contribution
agreement.

**Comment by cybergoulion** [comment]
OK, I'll do that then!

**Comment by StephenHodgson** [comment]
Just be aware I have some pending changes to those classes in https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/747

**Comment by cybergoulion** [comment]
Ok, I saw the change, there should be no conflict.
I mainly added this in SpeechInputSource.cs:  
`[Tooltip("The confidence level for the keyword recognizer.")]
        public ConfidenceLevel RecognitionConfidenceLevel;`

and made some changes to SpeechInputSourceEditor.cs to work in the inspector.

I also have some questions if you please.
1. Is the name of the property clear enough? 
2. Should I create a branch for this?
3. Should I change this and make a pull request now?

Sorry, I have not contributed to the project before and trying to get my bearings...

**Comment by StephenHodgson** [comment]
> 1. Is the name of the property clear enough?

Yeah it's great, no worries there.

> 2. Should I create a branch for this?

Yes, after forking your copy of the repository make a new branch and add your changes.

> 3. Should I change this and make a pull request now?

That would be awesome!

**Comment by cybergoulion** [comment]
Ok, last question. Is there a guideline for branch naming?

**Comment by StephenHodgson** [comment]
Nope not really, that's up to you on your repo.
