### ISSUE TITLE
Unable to locate Azure spatial anchors; Multi-user shared experience tutorial 

### ISSUE THREAD

**Issue by ghostravenstorm** [microsoft/MixedRealityToolkit-Unity#9272]
## Describe the bug

Following the multi-user demo with the lunar rover, other users are not able to locate the shared Azure spatial anchor.
When the program gets to AnchorModuleScript.FindAzureAnchor(string), and the message "Looking for Azure anchor... please wait..." appears, the search process seems to get stuck here and no anchor is found. I can confirm that Client A is creating an anchor with ID "xyz" and Client B is receiving anchor id "xyz" via Photon and searches for that particular anchor. But the system just fails to find anything.

## To reproduce

- Make a new Unity project following the tutorial
- https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-05
- Build out to 2 separate HoloLens devices
- (I've included my spatial anchors app id and everything, also I disabled the rover spawn. Just trying to get a spatial anchor to load)
- Create an anchor on HL A and share it
- Get the anchor on HL B
- Observe the finding get stuck and doesn't proceed

## Expected behavior

Finding the Azure spatial anchor shouldn't take more than a few seconds.
I had this working in my main project (that borrows MRTK tutorial code) and the tutorial itself. Now today nothing using this code is able to get Azure spatial anchors.

I haven't been able to figure out if something is wrong with Azure services, or maybe I hit a quota limit with spawning anchors.
I just know that this tutorial was working before, and now it's not.

I also noticed that this tutorial code with spatial anchors somehow doesn't affect the graphs on the dashboard.
Running the sample project from the Azure Spatial Anchors SDK github I'm able to see the graph "anchors created" count up, but this MRTK tutorial doesn't seem to affect it.

Client A
![image](https://user-images.githubusercontent.com/14009559/107451605-a0ba9600-6b15-11eb-8266-0b0ed7584976.png)

Client B
![image](https://user-images.githubusercontent.com/14009559/107451628-aca65800-6b15-11eb-8c90-d7dc6c678662.png)

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.4.18f1]
- MRTK Version [e.g. v2.4]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by PattyUnity** [comment]
I also encountered the same issue. I could start session, create anchor and get anchor ID but when find anchor button is pressed, it stuck there forever with this log "Looking for Azure anchor... please wait"

![image](https://user-images.githubusercontent.com/58160271/112798267-3f3b9000-909f-11eb-9b68-868f301dd6f6.png)

I wonder if it has something to do with the quality of the anchor when it's created? According to https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/guidelines-effective-anchor-experiences, it's recommended to scan the anchor position from various perspective but how to do that? Once I click Create Anchor button, the anchor is created in a few seconds which doesn't provide enough time to include various perspective.

**Comment by miyocrosoft** [comment]
In my case, changing the wifi network profile of Hololens2 to "Public" was successful, but I don't know why.

**Comment by MaxWang-MS** [comment]
Hi @Sean-Kerawala could you take a look at the issue since it seems to be external to MRTK?

**Comment by MarkoXR** [comment]
Are there any updates on this issue? I am having the same problem.

**Comment by F1batman** [comment]
If I set wifi to private then run it until it says please wait then switch back to public while the app is still running. Then select Find Azure Anchor again it says it is unable to find the anchot then set it to 0,0,0. I did get it to work once when swapping to or from public but have not been able to replicate.

**Comment by MarkoXR** [comment]
Updating the ASA SDK Core and Windows to v2.10.2 solved the issue for me: https://github.com/Azure/azure-spatial-anchors-samples/issues/291

**Comment by F1batman** [comment]
Thanks Heaps thats what fixed it for me.
