### ISSUE TITLE
Remote build from Unity problem HL2

### ISSUE THREAD

**Issue by 9and3** [microsoft/MixedRealityToolkit-Unity#9277]
## Describe the bug

I build both from Unity and MRTk build window the same remote holographic app for HL2, in both cases, the compile is without error and no problem, once I tried to lunch the app I got this white window with this message. Does anyone know why?

## Screenshots

![WhatsApp Image 2021-02-10 at 21 41 05](https://user-images.githubusercontent.com/50238678/107569775-f9a72e80-6be8-11eb-9dea-137824773313.jpeg)

## Your setup (please complete the following information)

- Unity Version 2019.4.15f1
- MRTK Version 2.5.4

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by keveleigh** [comment]
hmm, this sounds like it might be an issue on the Unity side. I'd recommend filing a Unity bug with them

![image](https://user-images.githubusercontent.com/3580640/108777521-c6ce3600-7518-11eb-8741-c7c5525a1eaa.png)

**Comment by keveleigh** [comment]
Hmm, this sounds like it might be a bug on the Unity side. I'd recommend filing a bug with them 
![image](https://user-images.githubusercontent.com/3580640/108777607-e8c7b880-7518-11eb-9e2f-35382d9ff3e4.png)

We're tracking some other issues around remoting, but more reports and data would be good!
