### ISSUE TITLE
Make Finger Cursor disappear while grabbing.

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#9288]
## Describe the bug

Splitting the parent issue into 2 parts: #8960

Currently the finger cursor will stay visible when grabbing. This makes it hard for the user to differentiate between actively grabbing an object vs. not.

**Comment by polar-kev** [comment]
@RogPodge, after speaking with @matthejo and Andy Kline, let's align with the HoloLens 2 shell on this one.

**Comment by RogPodge** [comment]
Currently the cursor disappears during the grab in Hololens 2 shell right?

**Comment by Zee2** [comment]
Closing, will reopen another feature request for grab tethers.
