### ISSUE TITLE
Customer feedback: Why is the toolbox not part of the foundation?

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#9291]
Ruben de la Torre  3:37 AM
Why is the "Toolbox" https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_Toolbox.html an extra package if its just spawns UX Prefabs from Foundation?

**Comment by keveleigh** [comment]
My original rationale: it was envisioned as an add-on tool for the rest of the MRTK (it's not required for success, but it can help), so I put it in the Tools package. It also contains many images, which seemed better to make optional instead of sticking in the Foundation.
