### ISSUE TITLE
Add scroll in Build Window

### ISSUE THREAD

**Issue by GMyjak** [microsoft/MixedRealityToolkit-Unity#9296]
## Describe the problem

Cannot use Build Unity Project in Build Window when I have too many scenes in build.

## Describe the solution you'd like

Add scroll.

## Describe alternatives you've considered

You can detach Build Window and enlarge it but it is not very convenient and I if I had even more scenes this solution wouldn't work.

## Additional context

![image](https://user-images.githubusercontent.com/46460733/107933017-830a8800-6f7e-11eb-9296-04cfa4e508eb.png)

Build Unity Project button is under scene list.

**Comment by keveleigh** [comment]
Thanks for the report! This was added via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8789 and will be included in the upcoming 2.6 release.
