### ISSUE TITLE
Request information

### ISSUE THREAD

**Issue by caveDweller22** [microsoft/MixedRealityToolkit-Unity#9299]
I would like to use the Windows Mixed Reality toolkit (MRTK) to set up a unity immersive project that will allow me to create an executable that I can distribute to users in my company. Our company has restricted access to the Microsoft Store. Can an app be produced from unity that you can distribute to other users without the use of Microsoft Store? (via copying an EXE to their machine)? Can you direct me to information that may answer this question and/or Describe the process step by step of completing this task?

**Comment by elbuhofantasma** [comment]
Hello @caveDweller22 

Our official documentation for deploying to HoloLens is [located here.](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02#building-your-application-to-your-hololens-2)

If you would like to build from the command line, you can take a look at [Unity's document](https://docs.unity3d.com/Manual/CommandLineArguments.html) on it.
