### ISSUE TITLE
UPM Foundation package import is missing a directory

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9322]
## Describe the bug

When importing the Foundation package via UPM, 3 Directory Not Found errors are generated for files in the following directory: `\Library\PackageCache\com.microsoft.mixedreality.toolkit.foundation\SDK\Experimental\InteractiveElement\StateVisualizer\StateAnimatableProperties\AnimatableProperties\ShaderProperties\`

## To reproduce

1. Create a new Unity 2019 project
2. Import the Foundation Package
3. Look at the Unity Console

## Screenshots

![image](https://user-images.githubusercontent.com/65038391/108282390-5ef1a700-7136-11eb-9fa7-527a8834614e.png)
![image](https://user-images.githubusercontent.com/65038391/108282439-7892ee80-7136-11eb-9e5f-1b7422e73444.png)
![image](https://user-images.githubusercontent.com/65038391/108282467-83e61a00-7136-11eb-8b2e-a387c22609e1.png)

## Additional context

The errors will not persist in the project, even after removing the Foundation package and re-importing it. When the Foundation package is re-imported, the folder from the error is still missing and the errors are not generated.

**Comment by keveleigh** [comment]
This looks like a path-too-long error

**Comment by keveleigh** [comment]
@CDiaz-MS Any ideas on if we can shorten 
![image](https://user-images.githubusercontent.com/3580640/108284230-acbbde80-7139-11eb-8908-6e3e94d90fc2.png)

**Comment by CDiaz-MS** [comment]
@keveleigh yes folders can be collapsed, I'll shorten the path.

**Comment by davidkline-ms** [comment]
fixed with #9323

**Comment by FlorianJa** [comment]
I am still running into a very similar problem with the 2.6 release. I could fix the problem since the path to …\Library\PackageCache\... was quite long for my project. However, there is this "@635490bc259e-1615042220629" added to the package name. These are 27 characters. Are they necessary?

**Comment by keveleigh** [comment]
I don't think we have any control over that string 😞 @davidkline-ms?

**Comment by FlorianJa** [comment]
Most other packages just have only their version number at the end, like @2.6. Sometimes it is also the commit sha (if pulled via git)

**Comment by keveleigh** [comment]
Unity seems to append the long `@` when a package is imported via tarball/tgz, which is the way the Feature Tool handles packages
