### ISSUE TITLE
UPM Hand Physics Service is missing 'JointKinematicBody' namespace

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9326]
## Describe the bug

When attempting to build any example scene after importing the Hand Physics Service from the UPM package, the build will fail with the following error: `Assets\Samples\Mixed Reality Toolkit Extensions\[Version]\HandPhysicsService\PhysicsTriggerEventReadout.cs(29,22): error CS0246: The type or namespace name 'JointKinematicBody' could not be found (are you missing a using directive or an assembly reference?)`

The Hand Physics Service does not need to be added to the example scene, only imported to the project.

## To reproduce

1. Create a new Unity 2019 Legacy XR project
2. Import the Foundation, Extensions, and Examples UPM packages
3. Import any example scene into the project
![image](https://user-images.githubusercontent.com/65038391/108294313-7c307080-714a-11eb-99bb-6ea5ba9939d2.png)

4. Import the Hand Physics Service sample to the project
5. Attempt to build the example scene

## Screenshots

![image](https://user-images.githubusercontent.com/65038391/108290748-e692e200-7145-11eb-980c-522e7e8e2755.png)
![image](https://user-images.githubusercontent.com/65038391/108290777-f0b4e080-7145-11eb-888b-2b4283cd3181.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.20f1

## Target platform (please complete the following information)

- OpenVR

## Additional information

This issue only occurs on the Standalone platform. Example scenes will build successfully on the UWP platform.

**Comment by davidkline-ms** [comment]
@elbuhofantasma, what do you mean "import the hand physics service"?  are you importing the sample from the extensions package?

**Comment by elbuhofantasma** [comment]
I have updated that step. I am importing the 103.58KB Sample to the project. The Hand Physics Service is NOT being added to the example scene.

**Comment by davidkline-ms** [comment]
this may also be a long path issue. sideloading UPM packages generates some very long folder names (ex: com.microsoft.mixedreality.toolkit.extensions@d5334872877f-1613612471447)

**Comment by davidkline-ms** [comment]
while the path is REALLY long > 130 characters, that is not likely the cause. the examples asmdef does not have a reference to the extensions assembly.

**Comment by elbuhofantasma** [comment]
As a side note, this issue does not occur on UWP builds. I will try building with a short path in Open VR/Standalone and see if the results are the same.

**Comment by davidkline-ms** [comment]
it may be that we need to add guards around the hand physics for non uwp builds

**Comment by keveleigh** [comment]
>it may be that we need to add guards around the hand physics for non uwp builds

Or include the assembly on all Windows platforms, which we should probably do anyway since we support Leap Motion

![image](https://user-images.githubusercontent.com/3580640/108399449-f86c9780-71ce-11eb-8f8c-92ccb30cea5f.png)

**Comment by davidkline-ms** [comment]
I'll do that and open a PR. From looking at the class, there is nothing that should prevent it from working on any platform.

**Comment by keveleigh** [comment]
>working on any platform.

Agreed! May as well enable it across the board

**Comment by davidkline-ms** [comment]
fixed.
