### ISSUE TITLE
motion controllers are off...

### ISSUE THREAD

**Issue by jaimerodriguez** [Microsoft/MixedRealityToolkit-Unity#933]
with current gltf implementation... the controllers seem to be tilted by a few degrees (like 5) when placed in a flat surface..  
Also, they don't pivot correctly. Put the two controllers next to each other, touching and rotate them and see that at some angles, they can't touch, they are like 5-10 cm apart, at other angles they overlap...

**Comment by StephenHodgson** [comment]
I have also noticed this, even in the mixed reality portal desktop.  Unsure if this issue needs to be raised here.

**Comment by jaimerodriguez** [comment]
@StephenHodgson  -  I validated w/ internal tools that the issue was in toolkit's implementation...  
Kurtis will have internal context and I am sure he and I will sync.. I just wanted it tracked here for completeness..   

I have not seen this in the portal -- that is not what I validated against, but I did look -- If you can repro in portal, can you please file a feedback hub item against portal? 
Thanks!

**Comment by Jamroah** [comment]
Hope it's okay if I add to this question, I'm having a similar issue but much more extreme.

The controllers seem to take their position and rotation from the immersive headset's initial position and then apply it in world coordinates e.g. (-0.2, -0.1, 0.5) whereas my headset sets local coordinates from the floor correctly e.g. the y is usually around 1.2 when sitting at my desk. So visually and functionally (the ray cast starts from the aforementioned world vector) my controllers are attached to the floor and pointing in the wrong direction. I'm using the current version of the MotionControllerTest.unity scene with no modifications. My portal is set up for the seated/standing position, no boundary (however, setting up a boundary doesn't solve my issue).

**Comment by StephenHodgson** [comment]
Will do.

**Comment by keveleigh** [comment]
It's looking less like this is in the Toolkit implementation and more that this is in Unity's implementation. I'll likely still have some Toolkit updates as this (and other) bugs are fixed.

**Comment by keveleigh** [comment]
@Jamroah, that sounds like you're hitting a known bug. I believe this will be fixed in b11.

**Comment by keveleigh** [comment]
I was incorrect with passing this off to Unity. The GLTFLoader's rotation decomposition was failing somewhere. I wasn't able to pinpoint the actual failure in the math, but, luckily, Unity has added a rotation value to Matrix4x4s in 2017.2. Querying that value instead of calculating it manually provides the correct rotation of the base controller. I'll have a PR out shortly.

**Comment by StephenHodgson** [comment]
Looks like the lastest windows insider preview update fixed the motion controller axis being off, but now they jump around erratically.  Is there a way to calibrate the motion controllers?

**Comment by keveleigh** [comment]
Fixed via #942
