### ISSUE TITLE
Reading Mode has missing/invalid script attached to Game Objects when building

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9330]
## Describe the bug

In Unity 2018 when the user builds the Reading Mode example scene, 8 warnings for a missing\invalid script are generated for the Game Objects in the scene. The Inspector for the Game Objects that are generating the warnings, have missing mono scripts. 

## To reproduce

1. Create a new UWP platform Unity 2018 project
2. Import the Foundation, Extensions, and Examples .unitypackages
3. Open the Reading Mode example scene
4. Select DefaultHoloLensConfigurationProfile, DefaultHoloLens2ConfigurationProfile, or DefaultMixedRealityToolkitConfigurationProfile
5. Build the Reading Mode example scene
6. Look at the Unity Console for the warnings. 

## Expected behavior

Reading Mode has all necessary scripts attached in Unity 2018.

## Screenshots

![image](https://user-images.githubusercontent.com/65038391/108366205-f42f8280-71ac-11eb-90e6-e3d1c8dc4dbb.png)
![image](https://user-images.githubusercontent.com/65038391/108367503-648ad380-71ae-11eb-8226-f42f947c5c5b.png)
![image](https://user-images.githubusercontent.com/65038391/108367552-6eacd200-71ae-11eb-84c5-593e5671c1db.png)
![image](https://user-images.githubusercontent.com/65038391/108367614-7c625780-71ae-11eb-9bf3-7591c7395e95.png)
![image](https://user-images.githubusercontent.com/65038391/108367654-871cec80-71ae-11eb-9fd6-801b1451a3b6.png)
![image](https://user-images.githubusercontent.com/65038391/108367693-90a65480-71ae-11eb-9ad5-27889bb0c492.png)
![image](https://user-images.githubusercontent.com/65038391/108367743-9a2fbc80-71ae-11eb-8bf2-69e73f480466.png)

## Your setup (please complete the following information)

- Unity Version 2018.4.31f1

## Target platform (please complete the following information)

- UWP
- HoloLens
- HoloLens 2

## Additional context

The scene successfully builds and will run on device, but has major usability issues.

**Comment by keveleigh** [comment]
@elbuhofantasma This should be fixed in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9344, if you get a chance to review. Thanks!
