### ISSUE TITLE
Holograms are not interactable when used Vuforia with MRTK 2.5.4 and Unity for HoloLens

### ISSUE THREAD

**Issue by madhawap** [microsoft/MixedRealityToolkit-Unity#9331]
## Describe the bug

I am trying to build a simple HoloLens 2 app to recognize a marker and display a cube and to enable basic interactions with it using hands. 
I am using Unity 2019.4.11 and MRTK version 2.5.4 and Vuforia Engine AR version 9.7.4.

Under the MixedRealityToolKit game object, I have selected DefaultXRSDKConfigurationProgile.
(When I test with DefaultMixedRealityToolKitConfigurationProgile it gives me Access violation executing location 0x00000250348FD4C0. error when app is deployed to HoloLens 2 )
Under the MixedRealityPlayspace -> Main Camera, I have added the Vuforia Behaviour Script.
Then I added a Vuforia Image Target Game object and under that, I added a simple cube. After that, I attached NearInteractionGrabbable, Object Manipulator, and BoundsControl scripts to the cube. However, when the app is deployed to HoloLens and when the cube appears (after reading the marker), the cube is not interactable. The cube has a box collider and link to Host Transform under Object Manipulator script and enabled far manipulation as well. Still, the cube is not interactable. Any thoughts on what is going wrong here?

## To reproduce

1. Install Vuforia Engine AR version 9.7.4 on Unity version 2019.4.11
2. Install MRTK foundation package version 2.5.4
3. Under the "Mixed Reality Toolkit" menu on Unity click on "Add to Scene and Configure..."
4. This will add Directional Light, MixedRealityToolkit, and MixedRealityPlaySpace game objects to the scene. 
5. In the MixedRealityToolkit GameObject, set the configuration profile to the DefaultXRSDKConfigurationProfile.
6. Add Vuforia Behaviour Script under MixedRealityPlaySpace -> Main Camera
7. Add an app license by clicking "Open Vuforia Engine Configuration"
8. Add Image Target game object to the hierarchy and under the "Image Target Behaviour" component select "From Database" and click "Add Target" and create a custom marker and import the marker database to Unity
9. Under the Image Target game object add a cube.
10. Attach NearInteractionGrabbable, Object Manipulator, and BoundsControl scripts to the cube. Link to the cube to Target Object in Bounds Control component. 
11. Deploy the app to HoloLens 2 and when the marker is detected cube will appear but the cube is not interactable.

## Expected behavior

The cube should be grabbable and change the size. 

## Screenshots

![image](https://user-images.githubusercontent.com/12988860/108386325-a5dbbb80-7260-11eb-9b3c-c115d9b4724a.png)

![image](https://user-images.githubusercontent.com/12988860/108386389-b68c3180-7260-11eb-88b9-f64b15be875b.png)

![image](https://user-images.githubusercontent.com/12988860/108386851-27cbe480-7261-11eb-9f79-bcf5feba8d26.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.11f1
- MRTK Version 2.5.4
- Vuforia Engine AR version 9.7.4

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
Fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9343

**Comment by MaxWang-MS** [comment]
I think you might forget to turn off Vuforia tracking after the target image is detected the first time or possibly in events of bounds control such as scale/translate started. Otherwise I think Vuforia will always try to position the cube above the target image.
