### ISSUE TITLE
[Stabilization 2.6.0] HandInteractionExamples scene: Unity UI Slate text filed : text wrapping is not supported but input field is vertically big.

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#9333]
## Describe the bug
HandInteractionExamples scene: Unity UI Slate text field: text wrapping is not supported and text is displayed as a single line. However, the input field is vertically big.

![20210217_191021_HoloLens](https://user-images.githubusercontent.com/13754172/108409946-aaaa5c00-71db-11eb-8d70-d323a2fca481.jpg)

**Comment by keveleigh** [comment]
Fixed via #9343
