### ISSUE TITLE
[Stabilization 2.6.0] Slate: Bounding Box handles are not visible, and not grabbable

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#9334]
## Describe the bug
Slate: Bounding Box handles are not visible, and not grabbable
![20210217_191239_HoloLens](https://user-images.githubusercontent.com/13754172/108410157-e6ddbc80-71db-11eb-8c07-696889b9fb16.jpg)
![20210217_191130_HoloLens](https://user-images.githubusercontent.com/13754172/108410159-e80ee980-71db-11eb-8f2f-adb4ea706095.jpg)
![20210217_191213_HoloLens](https://user-images.githubusercontent.com/13754172/108410160-e80ee980-71db-11eb-8e62-54f7fa2bdd9f.jpg)

**Comment by cre8ivepark** [comment]
Tested with 2.4.0 and 2.5.0.
From 2.5.0, the outline effect became thin, and handle is not triggering well. 

## 2.4.0 - Correct white outline thickness & handle trigger
![2021-02-19 11_34_00-Unity 2018 4 31f1 -  PREVIEW PACKAGES IN USE  - HandInteractionExamples unity - ](https://user-images.githubusercontent.com/13754172/108552855-b878e380-72a6-11eb-8d5a-d4f43eb99f10.png)
![2021-02-19 11_33_31-Unity 2018 4 31f1 -  PREVIEW PACKAGES IN USE  - HandInteractionExamples unity - ](https://user-images.githubusercontent.com/13754172/108552858-b9117a00-72a6-11eb-92b6-44b9232e8e71.png)

## 2.5.0+ - Thin white outline thickness & handle is not visible
![2021-02-19 11_24_34-Unity 2018 4 31f1 -  PREVIEW PACKAGES IN USE  - HandInteractionExamples unity - ](https://user-images.githubusercontent.com/13754172/108552861-b9117a00-72a6-11eb-8b5e-bf23eb7a6463.png)

**Comment by cre8ivepark** [comment]
I don't see any big differences between 2.4.0 version and the current. (Inspector values and the collider size in the editor looks the same)

![SlateBB](https://user-images.githubusercontent.com/13754172/108560469-a2245500-72b1-11eb-9536-4b758bebbc9e.png)

**Comment by davidkline-ms** [comment]
Closed with #9353

**Comment by cre8ivepark** [comment]
Another PR submitted to address invisible Bounding Box's wire #9357

**Comment by davidkline-ms** [comment]
re-closing as fixed by #9357
