### ISSUE TITLE
Oculus Touch Controllers Missing Spatial Grip

### ISSUE THREAD

**Issue by CodeTako-Ball** [microsoft/MixedRealityToolkit-Unity#9339]
## Describe the bug
The controller definitions for the Oculus Touch controllers are missing Spatial Grip as an input. This means that Near Object Grabbable cannot work with the controllers, among other issues.

## To reproduce

Set any pointer to use Grip Pose with the Oculus Touch controller, try to use said pointer. It will not update correctly.

Check the controller mapping definition for the Oculus Touch controllers. While Spatial Pointer is a mappable field, Spatial Grip is not.

## Expected behavior

Have Spatial Grip as a mappable input with the Oculus Touch controller.

## Screenshots

![image](https://user-images.githubusercontent.com/72283672/108436733-39819d80-7209-11eb-994b-b4f51d2c151c.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.20f1
- MRTK Version 2.5.4

## Target platform (please complete the following information)

- Oculus Quest 2

**Comment by keveleigh** [comment]
@RogPodge made some improvements in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9255 to remove some assumptions that "spatial grip" will specifically exist for `ObjectManipulator`. Is that the script you're using for near interactions, or are there more gaps we need to cover?

**Comment by CodeTako-Ball** [comment]
If this is intended behavior, I imagine that update to the `ObjectManipulator `will cover needs for most people. I'm not well versed on where grip pose is expected / used elsewhere in the MRTK.

I will probably be using a custom manipulation handler for my own uses, but I see no reason why the spatial grip shouldn't be added as an input from the controllers by default. The information is available from the hardware, and the interaction is present in other controller definitions (eg Windows Mixed Reality Controllers). I ended up defining a new controller type / Device Manager with the extra interaction mapping, which was a hassle (looking forward to your improvements to controller definitions), but is working fine now.

**Comment by CodeTako-Ball** [comment]
For reference, for my new controller types I main just added one more interaction mapping:

`new MixedRealityInteractionMapping(17, "Spatial Grip", AxisType.SixDof, DeviceInputType.SpatialGrip)`

Since `DeviceInputType.SpatialGrip` is properly found, I don't see why it wouldn't be included in the controller definition.

**Comment by keveleigh** [comment]
What data do you put in there? Is it different than the data for `DeviceInputType.SpatialPointer` or what's passed into `RaiseSourcePoseChanged`?

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/86fa40b39362ab1de0603e3945200469e7bbeb8b/Assets/MRTK/Providers/XRSDK/Controllers/GenericXRSDKController.cs#L114-L117

**Comment by keveleigh** [comment]
The main rationale for including it in the WMR controller but not others was that WMR provides distinct poses for "pointer" and "grip", while many other controllers treat them identically. If this is an incorrect assumption we've made about Oculus Touch, we should definitely fix it!

**Comment by Wolvie9** [comment]
🙌Thank You..... figuratively speeking... lol, im just saying... I'm not saying not a damn-thing... hummmm🤔💯🙊🎶... Yeahdehduh~¡≈saying😉... ★☆★☆Gët@m€♤♠︎♤♠︎°°°FirstLostLastFound~~~On Feb 18, 2021 4:24 PM, CodeTako-Ball <notifications@github.com> wrote:
If this is intended behavior, I imagine that update to the ObjectManipulator will cover needs for most people. I'm not well versed on where grip pose is expected / used elsewhere in the MRTK.
I will probably be using a custom manipulation handler for my own uses, but I see no reason why the spatial grip shouldn't be added as an input from the controllers by default. The information is available from the hardware, and the interaction is present in other controller definitions (eg Windows Mixed Reality Controllers). I ended up defining a new controller type / Device Manager with the extra interaction mapping, which was a hassle (looking forward to your improvements to controller definitions), but is working fine now.

**Comment by CodeTako-Ball** [comment]
Ah, I see. It's probably not pulling a distinct input stream, then. I'm not overriding anything for updating the pose, just using what's there for the `GenericXRSDKController` base class. I don't think there's a difference in my grip pose / pointer pose output.

Is there any documentation that specifies the difference between the intended uses of pointer and grip pose? I did quick search but couldn't find anything. My initial reaction is that it seems safer to provide the duplicate stream as grip pose, but I don't know how different they are in the WMR Controllers.  #9255 seems to fix the Object Manipulator by shifting to a generic Source Pose, which suggests to me that using either should be fine in many circumstances.

**Comment by CodeTako-Ball** [comment]
I stumbled upon this searching for something unrelated. It would be nice to copy some of this information to documentation about controllers and the input system:
[Grip Pose vs Pointing Pose](https://docs.microsoft.com/en-us/windows/mixed-reality/design/motion-controllers#grip-pose-vs-pointing-pose)

Given the distinction, it makes sense to retain the lack of a grip pose from a controller unless it is expressly different.

**Comment by keveleigh** [comment]
>It would be nice to copy some of this information to documentation about controllers and the input system

Yeah, agreed. I think we need a larger effort around docs for how to define a controller, where this would fit well
