### ISSUE TITLE
Unable to build with C# Project enabled.

### ISSUE THREAD

**Issue by HattMarris1** [Microsoft/MixedRealityToolkit-Unity#934]
Hello!

I am able to generate the Visual Studio solution file, but am then unable to build the UWP app and deploy to the emulator.

I'm using the latest version of HTK, and I'm only including a blank scene with a sphere in it in the build.

 I get the following error:

![image](https://user-images.githubusercontent.com/17457941/30068796-bf431962-9256-11e7-9c62-ca85fc11262c.png)

Loving the ToolKit otherwise, hope someone can help!

Thanks,

**Comment by jessemcculloch** [comment]
By latest version, do you mean you pulled down the master, or are you using one of the releases?

**Comment by HattMarris1** [comment]
I just tried building the same blank scene but without the HoloToolKit in the project, and that gave me the same errors.

Would be great if someone could tell me what's causing the errors anyway.

**Comment by HattMarris1** [comment]
@jessemcculloch I pulled down from master

**Comment by jessemcculloch** [comment]
Ok, let me fire up a blank project and see if I can replicate

**Comment by jessemcculloch** [comment]
What settings were you using for deploy (Debug, Release, or Master)?

**Comment by HattMarris1** [comment]
In visual studio: All three give the same error :( 

In unity: Target Device: HoloLens
SDK: 10.0.14393
Unity c# project is checked

**Comment by jessemcculloch** [comment]
Hmmm, i'm completely unable to replicate

**Comment by HattMarris1** [comment]
:( Thank you for trying anyway

**Comment by StephenHodgson** [comment]
You need to uncheck Unity C# check box in build window.

**Comment by HattMarris1** [comment]
Ok, done that, and now I get different errors: 
![image](https://user-images.githubusercontent.com/17457941/30071814-2429a446-9260-11e7-899c-e4b9b2f04e56.png)
(There's more than that)

**Comment by StephenHodgson** [comment]
Your build window should look like this:
![image](https://user-images.githubusercontent.com/13334553/30072104-1ddc731c-921e-11e7-97dd-3794696c46b3.png)

**Comment by StephenHodgson** [comment]
Also, what is the name of the folder you're building to?  It _should_ be UWP.

**Comment by StephenHodgson** [comment]
What happens when you use the toolkit's build window?

Try `HoloToolkit/Build Window/ Build SLN, Build APPX`

**Comment by HattMarris1** [comment]
Yeah, mine looks like that.

I just tried changing the folder to UWP (I was building to one called "App") before, and I still get the errors

**Comment by StephenHodgson** [comment]
Did you "Build" or did you "Rebuild" to pull the Nuget packages?

**Comment by HattMarris1** [comment]
I'm able to build an appx that way, Thanks!

Is this a bug with Unity then?

**Comment by StephenHodgson** [comment]
Yes

**Comment by HattMarris1** [comment]
To be clear: using the toolkit's build window is what allowed me to build

**Comment by jessemcculloch** [comment]
Hmmm, i'm not so sure about this.  I have never called my build folder UWP, it's always been App from the early days of HoloLens.  And I didn't think that 2017.1.1 ever had the C# projects bug, that was always 2017.2.0

**Comment by StephenHodgson** [comment]
@jessemcculloch https://github.com/StephenHodgson/UwpBuildTest

**Comment by genereddick** [comment]
@StephenHodgson:  Can you clarify regarding the folder name. I have also always used "App" for the folder name. Is using "UWP" a new requirement or just a convention that has been agreed upon?

**Comment by StephenHodgson** [comment]
See project attached to comment above.

**Comment by marcduino** [comment]
Hi,
I have actually the same Problem. I can build it also, when I don't check the C# projects. But: where are my scripts? can I only edit them via Unity? 

My Setup:
Unity 2017.1.1f1
VS 2015 Community (14.0.25431.01 Update 3)

**Comment by HattMarris1** [comment]
Build the SLN with c# projects unchecked using the MRTK Build window, then make sure your nuget packages are up to date by right clicking solution, then manage nuget packages

**Comment by jessemcculloch** [comment]
@HattMarris1 - Can we close this issue, or does it still exist?   I can't replicate.

**Comment by HattMarris1** [comment]
Yeah it's fine for me as well, maybe we add some common solutions to build issues to the readme?

**Comment by StephenHodgson** [comment]
Sounds like a great idea.
