### ISSUE TITLE
Unity crashes while adjusting the pinch slider in the Reading Mode example scene

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9340]
## Describe the bug

When the user adjusts the pinch slider in the Reading Mode example scene while using the in-editor player, Unity crashes to the desktop and produces a crash dump. This issue only happens on the Legacy XR pipeline.

## To reproduce

1. Add the Foundation, Extensions, and Examples packages to a new project
2. Check that you are on the Legacy XR pipeline
3. Open the Reading Mode example scene
4. Press the Play button to start the scene with the in-editor player
5. When the scene loads, manipulate the pinch slider
6. See crash

## Your setup (please complete the following information)

- Unity Version 2018.4.31f1, 2019.4.20f1

## Target platform (please complete the following information)

- Unity in-editor Player

## Additional information
This issue only occurs when Virtual Reality Supported is enabled. Using UPM or .unitypackages will work to reproduce this issue.

**Comment by elbuhofantasma** [comment]
This could potentially be an external bug.

**Comment by polar-kev** [comment]
@keveleigh, any updates on this?

**Comment by davidkline-ms** [comment]
fixed with #9398
