### ISSUE TITLE
[Stabilization 2.6.0] BoundsControl - Translation handles show a wrong orientation

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#9346]
## Describe the bug
Side translation handles show a wrong orientation

![2021-02-19 13_12_58-Unity 2018 4 31f1 -  PREVIEW PACKAGES IN USE  - BoundsControlExamples unity - MR](https://user-images.githubusercontent.com/13754172/108562228-65a62880-72b4-11eb-926d-e52b048d3f86.png)
![2021-02-19 13_12_23-Unity 2018 4 31f1 -  PREVIEW PACKAGES IN USE  - BoundsControlExamples unity - MR](https://user-images.githubusercontent.com/13754172/108562229-663ebf00-72b4-11eb-9bd4-f7af18f53271.png)

Top handle looks fine.
![2021-02-19 13_11_35-Unity 2018 4 31f1 -  PREVIEW PACKAGES IN USE  - BoundsControlExamples unity - MR](https://user-images.githubusercontent.com/13754172/108562226-650d9200-72b4-11eb-8605-633ded21d44c.png)

## To reproduce
Assign these prefabs and materials, configure to show Translation handles.
![2021-02-19 13_14_36-Unity 2018 4 31f1 -  PREVIEW PACKAGES IN USE  - BoundsControlExamples unity - MR](https://user-images.githubusercontent.com/13754172/108562311-866e7e00-72b4-11eb-8cc1-bbceaf42a2c9.png)

**Comment by MaxWang-MS** [comment]
Just confirmed this also repros in 2.5.4. Looking into this now.

**Comment by davidkline-ms** [comment]
Fixed with #9353
