### ISSUE TITLE
Editor inspector fails to display MRTK IconSet

### ISSUE THREAD

**Issue by philip-lamb** [microsoft/MixedRealityToolkit-Unity#9354]
## Describe the bug

When selecting a MRTK IconSet in the Unity Editor, the icons are not displayed. Instead an error is displayed in the inspector "You can't nest FoldoutHeaders, end it with EndHeaderFoldoutGroup.".

## To reproduce

1. Install MRTK standard assets.
2. Navigate to default IconSet
3. Look at inspector pane

## Expected behavior

Should see icons in set.

## Screenshots

<img width="878" alt="Screenshot 2021-02-22 125557" src="https://user-images.githubusercontent.com/5752887/108643103-e875f000-750d-11eb-8c1d-09bcd4c96d55.png">

## Your setup (please complete the following information)

- Unity 2020.2.2f1
- MRTK 2.5.4

## Target platform (please complete the following information)

- HoloLens 2

**Comment by atiemark** [comment]
Having the same issue. Is there a temporary workaround?

**Comment by keveleigh** [comment]
Hmm, I'm not able to fully repro. Am I missing anything? I'm able to view the asset, but unable to fold out any of the foldouts due to packages being immutable:

![image](https://user-images.githubusercontent.com/3580640/109687230-e4625780-7b37-11eb-859a-bf20eb5056de.png)

**Comment by philip-lamb** [comment]
I re-imported the project (close project, delete library folder, reopen, set platform and build settings) and I can't reproduce this now. At a guess it could have been  some out of date asmdef.

**Comment by MiPa12** [comment]
Hi, I'm having the same issue.
![Screenshot (41)](https://user-images.githubusercontent.com/61323363/123399974-8b667580-d5a5-11eb-8e0b-a5d9d98f69a4.png)

Your setup (please complete the following information)
Unity 2020.3.11f1
MRTK 2.7.0

**Comment by keveleigh** [comment]
@RogPodge Was this an issue fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9999?

**Comment by RogPodge** [comment]
Yep! should be fixed

**Comment by daffy76** [comment]
same problem

**Comment by istvanContXtual** [comment]
Same problem, 

Created a new icon set, Quad and Sprite Icons error in inspector panel:
"You cant nest Foldout Headers, end it with EndHeatherFoldoutGroup"

**Comment by MilanPolle** [comment]
This problem still exists in MRTK 2.7.2

**Comment by RogPodge** [comment]
The fix is checked into the main repo but is not yet released in one of our official packages.

We are looking to put out a release which contains this bug fix before end of the year, so stay tuned

**Comment by MilanPolle** [comment]
Thank you for your reply! I downloaded the fix and applied it to the mrtk core package, this solved the problem.

**Comment by kkyuri0419** [comment]
@MilanPolle
I am facing the same issue with MRTK 2.7.2
May I ask what do you mean by you downloaded the fix?

**Comment by MilanPolle** [comment]
@kkyuri0419 the file with the fix is here: [https://raw.githubusercontent.com/RogPodge/MixedRealityToolkit-Unity/02f3e41f650a14eb744b41507270fea0d0470d6a/Assets/MRTK/SDK/Features/UX/Scripts/Buttons/ButtonIconSet.cs](url)

Open the /packages/MixedReality folder, in your Unity project and then open the toolkit.foundation tgz file there (with 7Zip, for instance). 

In the tgz file, navigate to /package/SDK/Features/UX/Scripts/Buttons/ and there you can replace the ButtonIconSet.cs file with the one you've downloaded.

Unity will process the changes by itself and then you should be able to add your icons in the editor without the errors that were there.

**Comment by kkyuri0419** [comment]
> @kkyuri0419 the file with the fix is here: [https://raw.githubusercontent.com/RogPodge/MixedRealityToolkit-Unity/02f3e41f650a14eb744b41507270fea0d0470d6a/Assets/MRTK/SDK/Features/UX/Scripts/Buttons/ButtonIconSet.cs](url)
> 
> Open the /packages/MixedReality/ folder, in your Unity project and then open the .toolkit.foundation tgz file there (with 7Zip, for instance).
> 
> In the tgz file, navigate to /package/SDK/Features/UX/Scripts/Buttons/ and there you can replace the ButtonIconSet.cs file with the one you've downloaded.
> 
> Unity will process the changes by itself and then you should be able to add your icons in the editor without the errors that were there.

Thank you so much @MilanPolle !! it perfectly works!

**Comment by MilanPolle** [comment]
@kkyuri0419 Glad to hear that! Thanks for letting me know.

**Comment by jbienz** [comment]
Just curious, since this was fixed in March what caused it to be missed in the 2.7.2 release? Also, would love to see this fixed in the next package release. It's kind of painful to apply the hotfix above and the next MRFT update will likely overwrite it. Thanks!

**Comment by keveleigh** [comment]
> Just curious, since this was fixed in March what caused it to be missed in the 2.7.2 release?

The PR that fixed this was #9999, which was merged in June and just missed the 2.7.2 stabilization cutoff. It'll definitely be in our next release!

**Comment by dvDevel** [comment]
> 

The link is not available now.

**Comment by dvDevel** [comment]
You may fix the bug with the link.
The easiest way is to update to 2.7.3 fundamental with MixedRealityFeatureTool.

Additionally.
I tried exchanging ButtonIconSet.cs into tar at the package and tied it again.
but It's not working.
