### ISSUE TITLE
VoiceCommand in Interactable cannot be set from UnityEvent

### ISSUE THREAD

**Issue by FlorianJa** [microsoft/MixedRealityToolkit-Unity#9363]
## Describe the bug

The field "VoiceCommand" from the Interactable script does not show up when you want to register a listener for a UnityEvent.

## To reproduce

1. Open an example scene with an interactable object (e.g. HandInteractableExamples)
2. Select a PressableButton
3. Go to the Interactable component.
4. Add a new OnClick Event.
5. Drag and drop the button into the object field.
6. Select Function -> Interactable -> search for "string VoiceCammand" (see screenshot below)

## Expected behavior

The VoiceComand field should show up in the Unity inspector when selecting a listener for am Unity event

## Screenshots

![image](https://user-images.githubusercontent.com/3525062/108882955-2bff5580-7605-11eb-8a4b-6f903c723ed9.png)

## Your setup

- Unity Version: 2018.4.22 and 2019.4.20
- MRTK Version: latest dev commit

## Additional context

Background information: I am creating an app with localization and i dont want only the text to change but also the speech keyword. I am using Unitys' localization package. I also know that the speech keyword can be localized with the localization key and a UWP ressource file. But since i am already using the localization package from unity i dont want to maintain the localization at two different locations.

**Comment by keveleigh** [comment]
Thanks for the report! This is being fixed in #10197 and will be in the 2.8.0 release.

![image](https://user-images.githubusercontent.com/3580640/131906575-6c982328-afc3-4689-a159-1fcc2adea7d9.png)

**Comment by terence733** [comment]
.amz_inline_image{
                max-width: 100%
            }
         
        body{
            font-family: -apple-system-font, HelveticaNeue, LucidaGrande;
            font-size:  17px;
        }
