### ISSUE TITLE
Pinch Slider visual(Thumb) gets displaced from track when there is rotation added to root.

### ISSUE THREAD

**Issue by satorihunter** [microsoft/MixedRealityToolkit-Unity#9365]
**Describe the bug**

While trying to interact with both near and far interaction, the slide knob visual (ThumbRoot) gets displaced a little from the track. This generally happens when some rotation value is applied to the pinch slider root during runtime. Though the functionality is intact and works fine, visually the slider doesn't look correct as the knob is offset from the track.

**Use Case :** 

We have a model visibility slider which gets spawned by hand menu in front of the user. This makes the pinch slider root to have random rotation and position value based on user position. When the user tries to change the slider value, the knob moves out of the track and looks visually incorrect.

**Steps to reproduce the behavior:**

1. Drag and drop the default PinchSlider (MRTK) to scene
2. Reset the pinchslider root transform to 0/0/0 for rotation
3. Play the scene and try to move the slider be near/far interaction - (works fine)
4. Still in play mode, apply some random values for rotation eg( 32/-48/16)
5. now try to move the slider knob, it immediately moves off track.
6. you can see the offset value applied to ThumbRoot transform
6. Kindly check the screen shots for more detail.

**Expected behavior**

Regardless of the position and rotation value on pinchslider root gameobject, the slider know should be connected to track and move along the track axis when moved.

**Screenshots**

![MRTK_SliderIssue_01](https://user-images.githubusercontent.com/18205544/108898693-83211c80-763d-11eb-8294-7e1eee30d38e.png)

![MRTK_SliderIssue_02](https://user-images.githubusercontent.com/18205544/108898711-8c11ee00-763d-11eb-8741-caa95123dc51.png)

**Our setup**

- Unity Version 2019.4.12f1
- MRTK Version v2.5.0

## Target platform (please complete the following information)

- HoloLens 2

**Comment by satorihunter** [comment]
@julenka, could you please have a look into this?

**Comment by RogPodge** [comment]
Fixed by this #9163 in 2.6.0
