### ISSUE TITLE
OculusXRSDKDeviceManager error: The name 'Debug' does not exist in the current context

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9372]
## Describe the bug

When the switches to the Android platform after importing the MRTK, the following error is generated upon switching:
![image](https://user-images.githubusercontent.com/65038391/109049989-c4d9b380-768d-11eb-8959-b433ad3073e8.png)

## To reproduce

1. Import the MRTK packages to a new Unity project
2. Switch to the Android platofrm
3. See error

## Expected behavior

Switching to the Android platform will not generate errors.

## Your setup (please complete the following information)

- Unity Version 2019.4.20f1

## Target platform (please complete the following information)

- Oculus Quest (Android)

## Additional context

This issue happens with UPM and .unitypackages.

**Comment by keveleigh** [comment]
Looks like this was broken by me. Taking a look

**Comment by elbuhofantasma** [comment]
Unity fails to build any example scene for the Android platform with this issue as well.

**Comment by keveleigh** [comment]
@elbuhofantasma https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9373 should fix this!
