### ISSUE TITLE
Input Actions example scene Rotate speech input does not work

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9375]
## Describe the bug

When the user is running the Input Action Example scene on device, the 'Rotate' speech input command does not work. When the user says 'Rotate', the yellow cube will not respond. Looking at the yellow cube or using the far interaction pointer with the yellow cube does not change the outcome. 

## To reproduce

1. Import the Foundation, Extensions, and Examples packages into a new project
2. Open the Input Actions Example scene and deploy it to HoloLens
3. Look at the yellow cube and say 'Rotate'
4. See no rotation on the yellow cube

## Expected behavior

The yellow cube will rotate when the appropriate voice command is said.

## Your setup (please complete the following information)

- Unity Version 2019.4.20f1

## Target platform (please complete the following information)

- HoloLens 2
- UWP
- Legacy XR

**Comment by CDiaz-MS** [comment]
If you change the rotate key code to F5 in the Rotate Speech command profile 
![image](https://user-images.githubusercontent.com/53493796/109342969-7eb55900-7821-11eb-90dd-d700c62debe8.png)

And test in editor with Focus + pressing F5, it works:

![F5RotateInputActionScene](https://user-images.githubusercontent.com/53493796/109343106-a86e8000-7821-11eb-9b28-f628cf74c74f.gif)

Have not tested on device, but the command works in editor.

**Comment by davidkline-ms** [comment]
On device, this is working for me. I _did_ have to say "select" once to replace the hand far pointer with the gaze cursor. then it just worked.
