### ISSUE TITLE
Input Actions Example does function properly on XR SDK

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9376]
## Describe the bug

When the user is on the XR SDK pipeline and tries to run the Input Actions Example scene on HoloLens 2, the scene will not function as intended. When the user adds the XR SDK camera and input system and removes the Legacy XR camera and input system, the GGV pointer is the only pointer available and the scene will not track the user's hands or gestures. The hand mesh and and joints are also not rendered.

The yellow cube will rotate when the 'Rotate' speech command is said by the user.

## To reproduce

1. Create a new project and import the Foundation, Extensions, and Example packages
2. Switch to UWP and XR SDK
3. Open the Input Actions Example scene
4. Remove the WMR/Legacy XR camera profile and input data provider from the Input Actions profile
5. Add the XR SDK camera profile and input data provider to the Input Actions profile
6. Build the scene and deploy to HoloLens 2
7. See issue

## Screenshots

![image](https://user-images.githubusercontent.com/65038391/109079190-6c1d1180-76b3-11eb-82ac-8b29b5c70a53.png)
![image](https://user-images.githubusercontent.com/65038391/109079204-750de300-76b3-11eb-87ea-ba7edb6ee755.png)

https://user-images.githubusercontent.com/65038391/109079224-7c34f100-76b3-11eb-8972-41c3283eb55e.mp4

## Your setup (please complete the following information)

- Unity Version 2019.4.20f1

## Target platform (please complete the following information)

- HoloLens 2
- UWP
- XR SDK

## Additional context

This is the part of the debug output that occurs when the user puts their hands in the Hand Tracking zone.
`Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEFF0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF380.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF410.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEFF0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF380.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF410.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEFF0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF380.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF410.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEFF0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF380.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF410.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEFF0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF380.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF410.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEFF0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF380.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF410.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEFF0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF380.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF410.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEFF0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF380.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF410.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEFF0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF380.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF410.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEFF0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF380.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF410.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEEB0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FEFF0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF0A0.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF220.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF380.
Exception thrown at 0x00007FFB4F25A71C in primarypntr.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002FC65FF410.`

**Comment by RogPodge** [comment]
Closing this because we seem to have a similar situation as #9369 

| Default Input Simulation Profile |  Input Simulation Profile for the HandInteractionGestureEventsExample scene |
|---|---|
| ![image](https://user-images.githubusercontent.com/53493796/109074902-3ecd6500-76ad-11eb-950f-9208a33ad6f9.png) | ![image](https://user-images.githubusercontent.com/39840334/109219117-10628f00-776c-11eb-96a7-472f2ac78516.png)|

This scene appears to be intentionally simulating HoloLens 1 style input. 

Also closing because the XR SDK profile issues are captured by #9378. I think for now we're ok so long as things work on legacy XR, as we don't want to force/assume people are going to use XRSDK until we reach full feature parity.
