### ISSUE TITLE
Hand Menu scene description panel buttons overlap with text

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9377]
## Describe the bug

On device and the editor, the buttons in the Hand Menu Example scene description panel overlap with the text above it. 

## Screenshots

On device:
![20210224_162237_HoloLens](https://user-images.githubusercontent.com/65038391/109084925-89ef7400-76bd-11eb-9fbd-18947445988a.jpg)

Editor:
![image](https://user-images.githubusercontent.com/65038391/109084966-9a075380-76bd-11eb-9bee-4f3e99164495.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.20f1

**Comment by cre8ivepark** [comment]
@elbuhofantasma Could you please check the version number of the TextMeshPro? It seems like TMP version issue.

**Comment by elbuhofantasma** [comment]
@cre8ivepark I am using the version that Unity 2019.4.20f1 gives you by default. That version is 2.1.1.
![image](https://user-images.githubusercontent.com/65038391/109343144-b6240580-7821-11eb-87b6-46c248e930b2.png)

**Comment by cre8ivepark** [comment]
@elbuhofantasma I tried multiple combinations with Unity 2018 and 2019 with TextMeshPro 1.4.1 and 2.x.x
It seems this is the bug specific to TextMesh Pro 2.1.0 - 2.1.3. 
A higher or lower version does not show this symptom.
1.4.1 - No issues (this is our current ver. in the [packages/manifest.json](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Packages/manifest.json))
2.0.1 - No issues
2.1.0 - Shows the symptom
2.1.1 - Shows the symptom
2.1.3 - Shows the symptom
2.1.4 - No issues (latest version available)

Looking into changelogs about 'spacing' and it seems there were several updates around it.
https://docs.unity3d.com/Packages/com.unity.textmeshpro@2.1/changelog/CHANGELOG.html

**Comment by polar-kev** [comment]
@davidkline-ms to add an update in the json manifest for UPM.
@polar-kev to verify that docs recommend latest version of TMP when manually importing packages
