### ISSUE TITLE
Example scene specific profiles need to be updated for XR SDK

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9378]
## Describe the bug

The following example scene specific profiles need to be updated for the XR SDK pipeline.

- GestureEventsConfigurationProfile
- HandMenuConfigurationProfile
- RecordArticulatedHandPoseConfigurationProfile
- Dictation.MixedRealityToolkitConfigurationProfile
- DisablePointersExampleConfigurationProfile
- InputActions.MixedRealityToolkitConfigurationProfile
- Speech.MixedRealityToolkitConfiguraitonProfile
- PulseShaderConfigurationProfile
- Interactable_MixedRealityToolkitConfigurationProfile
- CameraOffsetProfile
- MRTKExamplesHubConfiguraitonProfile
- NonNativeKeyboardMixedRealityToolkitConfigurationProfile
- DemoSceneUnderstandingMixedRealityToolkitConfigurationProfile
- HandPhysicsMixedRealityToolkitConfigurationProfile

**Comment by davidkline-ms** [comment]
This is a bit of a slippery slope. If we update the profiles, then the examples will not work on Legacy XR (ex: 2018.4). If we duplicate the profiles, it could overwhelm customers by display a _very_ large number of profiles.

**Comment by polar-kev** [comment]
This won't make it into the 2.6 release next week but is high priority for immediately after.

**Comment by RogPodge** [comment]
Handled by #9419
