### ISSUE TITLE
Null base cursor in shell hand ray pointer

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#9383]
## Describe the bug

When debugging the hand interaction example scene running on HL2 with Visual Studio, there are a few exceptions shown in the output window after interacting with the objects in the scene for a while. These exceptions also triggered a tangible slowdown when they happened. After looking into the issue it seems that the base cursor in shell hand ray pointer is sometimes null and thus the call to get the gameObject reference on the cursor caused the problem. But strangely the null check before the call seems to be unable to stop the call for some reason. I was not able to repro with XRSDK.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/6177ee4eba2d5cc5039565541a541238aeeba452/Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs#L505-L521

## To reproduce

1. Build the hand interaction example scene with the legacy XR pipeline and start debugging the built solution on HL2 using either ARM or ARM64 (also the issue seems to be reproducible with both debug and release configuration)
2. Use your hands to interact with the objects in the scene and check the output window whenever you feel there is a slowdown
3. See error

## Expected behavior

There should be no slowdowns when running the example scene.

## Your setup (please complete the following information)

- Unity Version 2019.4.19f1
- MRTK 2.6 prerelease

## Target platform (please complete the following information)

- HoloLens 2

**Comment by polar-kev** [comment]
Issue seen after launching the app for 1 minute. Appears to happen at random and can happen multiple times during runtime. Difficult to reproduce and frequency is unknown.

**Comment by MaxWang-MS** [comment]
This bug is no longer reproducible with the current 2.6 prerelease branch.
