### ISSUE TITLE
Changing Render Viewport Scale to the minimum value in the Reading mode scene causes visual issues

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9386]
## Describe the bug

When the user runs the Reading Mode example scene on HoloLens 2 and sets the Render Viewport Scale to it's minimum possible value, the hologram becomes unstable and the text is unreadable due to visual issues. This issue occurs with natural head motion.  The attached video is a little bit more spastic than necessary to see the issue on device with your eyes because the camera has a difficult time picking up the visual issues without the excessive movement speed. Mixed Reality Capture does not record the issue. This issue occurs with Single and Multi Pass Stereo Rendering Modes.

## To reproduce

1. Load the Reading Mode example scene on HoloLens 2
2. Change the Render Viewport Scale slider to it's minimum value
3. Turn your head to attempt to read the text

## Screenshots

https://user-images.githubusercontent.com/65038391/109241178-c094bf80-778d-11eb-97ae-4930e9aac1b7.mp4

## Your setup (please complete the following information)

- Unity Version 2019.4.20f1

## Target platform (please complete the following information)

- HoloLens 2
- UWP

## Additional context

The following exception is thrown constantly when the Render Viewport Scale is set to the minimum value:
`Exception thrown at 0x770394EB (KernelBase.dll) in upkg2019.exe: WinRT originate error - 0x80070057 : 'The provided value was outside of the range of valid values.'.
analog\input\mirage\publicapi\holographiccamera.cpp(262)\Windows.Mirage.dll!7029AFDB: (caller: 72407AE7) ReturnHr(386) tid(1850) 80070057 The parameter is incorrect.
    Msg:[value <= 0.0] `

**Comment by davidkline-ms** [comment]
I am not seeing this. Will follow up with @elbuhofantasma offline

![readingMode](https://user-images.githubusercontent.com/13281406/109369547-90165980-7851-11eb-8400-7be17f94f404.jpg)

**Comment by keveleigh** [comment]
I added a commit to #9398 which ensures we don't set 0.0 to the scale, to prevent ` The parameter is incorrect. Msg:[value <= 0.0]`

**Comment by davidkline-ms** [comment]
fixed with #9398
