### ISSUE TITLE
Poor performance on hololens 2 with InputRecordingService

### ISSUE THREAD

**Issue by Gregoire6Fr** [microsoft/MixedRealityToolkit-Unity#9388]
## Describe the Bug 

Poor performance on hololens 2 with the application in general (between 7 and 15 fps) and less than 5 fps when recording hands with the InputRecordingService. 

Performance is however correct in the editor. 

When calling the function InputRecordingService.SaveInputAnimation a huge freeze occurs that may stop rendering completely. We managed to fix this freeze by writing a custom function InputRecordingService.SaveInputAnimationAsync (since the official one is not available in the last MRTK release). 

## To reproduce 

You can pull our test repository here: https://github.com/6Freedom/HandRecorder and try to build on hololens to check the issue. 

In the app you can click on the button record to start and stop recording your hands movements and on the replay button to replay the last movement you recorded. 

The script that records the hands movement is in Assets/Scripts/MRTKRecording.cs 

## Setup: 

MRTK version 2.5.4 

Unity version 2020.2 (URP Project) 

Hololens 2, windows version 10.0.19041.1136 

## Target platform 

Hololens 2

**Comment by davidkline-ms** [comment]
@Gregoire6Fr , thank you for the report. When you are running the project on HoloLens 2, is it a debug build? Also, are  you running under the debugger at the time you see the <=15fps?

**Comment by Gregoire6Fr** [comment]
Hello @davidkline-ms, 
We were running the project as a debug build, and we reach less than15fps even without the debugger.

**Comment by Gregoire6Fr** [comment]
Update: I tried both master and release builds and it achieve better performances ~45fps normally and ~25fps when recording hands movements.  Is this the expected performances ?

**Comment by MaxWang-MS** [comment]
Hi @Gregoire6Fr, we have just released MRTK 2.6 which contains [performance improvements to the input recording service](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/release-notes/mrtk-26-release-notes#input-recording-service-improvements). Please update to that version and you should be able to observe noticeable improvements. Also the recording file format has been changed so please pay attention to that. You are expected to use release or master configuration when you are not debugging/trying to evaluate the performance of your application. I am closing the issue for now and please feel free to reopen if there are other questions.
