### ISSUE TITLE
Sharing Service schema Backwards Compatibility.

### ISSUE THREAD

**Issue by RaoAM** [Microsoft/MixedRealityToolkit-Unity#939]
HI, I have a problem with sharing service. I developed few hololens apps using HTK V 1.5.6. For all those apps I used sharing service executable file provided in HTK 1.5.6 with schema 15 hosted on a public IP.

Recently I developed 2 hololens apps with VOIP features using HTK V 1.5.8. In order to make this app work, I updated my sharing server with the new version available in 1.5.8 with schema 17. After that all my old apps using sharing service stop working.
With out migrating my previous apps, how can I make the sharing server to understand schema 17 and previous schema 15.

Thank you in advance

**Comment by StephenHodgson** [comment]
Backwards compatibility is not currently implemented.  My only suggestion is to have two servers, or to upgrade your old projects.  (Unsure about what's entailed in this, sorry)

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
