### ISSUE TITLE
MRTK shaders are not updated through Mixed Reality Feature Tool

### ISSUE THREAD

**Issue by FlorianJa** [microsoft/MixedRealityToolkit-Unity#9391]
## Describe the bug

When updating a project with MRTK v 2.5.x to v 2.6 preview with the Mixed Reality Feature Tool, the shaders in Assets/MRTK/Shaders are not updated, but the custom inspector script is updated and this is causing issues when selecting a Material with the standard shader (and some other problems). 

I think this issue is only partly related to this repository but i dont know where the Mixed Reality Feature Tool is maintained.

**Comment by davidkline-ms** [comment]
Thanks @FlorianJa!

The issue is with how MRTK copies in the shader files. It looks for a specific file and copies if not found. There are currently no version checkss

**Comment by keveleigh** [comment]
@davidkline-ms Have the shaders been updated for 2.6? If so, this feels like a ship blocker until developers can successfully upgrade MRTK.

**Comment by keveleigh** [comment]
Looks like there are three PRs that are new in 2.6: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8739, https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8842, https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8812

**Comment by davidkline-ms** [comment]
In progress.

The standard assets package will check for a version number in the sentinel file and prompt for customer approval to overwrite.

Also adding an item in MRTK > Utilities to check for shader upgrade.
