### ISSUE TITLE
Lots of error messages when XR system is not enabled

### ISSUE THREAD

**Issue by eusebiu** [microsoft/MixedRealityToolkit-Unity#9392]
## Describe the bug

When I have a profile with Oculus, WMR and Input simulation, and I uncheck the Initialize XR on startup, MRTK displays lots of error messages.
Even if the message is useful, one would see immediately that some loader is not working correctly due to XR configuration.

## To reproduce

1. Install MRTK 2.6.0 preview
2. Create a profile with Oculus, Windows MR and Input simulation 
3. Unckeck  the Initialize XR on startup from Unity XR Management
4. Run

## Expected behavior

Two errors: one for Oculus, one for WMR.

Actual: lots of errors like this one: Microsoft.MixedReality.Toolkit.XRSDK.Oculus.Input.OculusXRSDKDeviceManager has not set a value for IsEnabled, returning false.

## Your setup

- Unity Version 2020.2
- MRTK Version 2.6.0 preview

## Target platform

- Editor

**Comment by keveleigh** [comment]
Fixed via #9411
