### ISSUE TITLE
A script that automatically fits a BackPlane to a GridObjectCollection

### ISSUE THREAD

**Issue by rolandsmeenk** [microsoft/MixedRealityToolkit-Unity#9393]
## Describe the problem

I'm always frustated when building menus with the GridObjectCollection and I need to manually calculate the scale of the backplane to fit that GridObjectCollection. Furthermore I would like to directly see the result of the GridObjectCollection to any changes I make in the inspector instead of having to press the "Update Collection" button.

## Describe the solution you'd like

I would like my BackPlane visual to automatically scale to a GridObjectCollection that it is behind.

## Additional context

Pull request incoming

**Comment by Zee2** [comment]
This is solved by hybrid Canvas support in MRTK3.
