### ISSUE TITLE
Using AR Foundation documentation needs to be updated

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9405]
## Describe the issue
Bug #6646 no longer effects building on MacOS Big Sur with Xcode 12. The step for un-checking the 'Strip Engine Code' check box in Project Settings > Player > Other Settings > Optimization is no longer necessary to successfully build the MRTK for iOS.

## Feature area
iOS/AR Kit

## Existing doc link
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Documentation/CrossPlatform/UsingARFoundation.md

## Additional context
Enabling the Unity AR camera settings provider should also be updated to include removing the WMR camera settings provider if using a profile that has that camera settings provider.

**Comment by MaxWang-MS** [comment]
The issue has been fixed.
