### ISSUE TITLE
No camera position and orientation update (hololens 2)

### ISSUE THREAD

**Issue by Xispeo** [microsoft/MixedRealityToolkit-Unity#9408]
## Overview

After configuration of a fresh hololens 2 project, the virtual camera does not move into the virtual scene so the virtual scene is static.

## Expected behavior

Seeing the virtual world moving accordingly to the user's head movements : a static cube stays at the same position in the real world

## Actual behavior

The virtual camera is static, a virtual cube is constantly display in front of the user's head even if the user moves. 

## Steps to reproduce
New configured project, add a cube in the scene, compile and deploy on hololens 2, the cube stays in front or the user's eyes even if the user walks or turns his head

## Unity editor version
Unity 2019.4.21

## Mixed Reality Toolkit release version
MRTK 2.5.4

**Comment by keveleigh** [comment]
If you're using Unity's new XR SDK pipeline (if you user XR Plugin Management as opposed to the Player Settings for XR), you'll want to ensure MRTK is set up with the correct profiles: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html#configuring-mrtk-for-the-xr-sdk-pipeline

**Comment by Xispeo** [comment]
That was it :)
Thank you !
