### ISSUE TITLE
Improve profile configuration across legacy XR and XR SDK

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#9419]
## Describe the problem

Currently, it's confusing to know when to swap out profiles and which profiles to swap them out for (#9185) as well as unmaintainable to provide duplicate profiles for all sample scenes for both XR pipelines (#9378).

## Describe the solution you'd like

It should be possible to mark specific systems as valid for specific pipelines and allow configuration across both in a single profile, with the MRTK spinning up one list or the other depending on the app context. We may also want to mark specific systems as valid across both/all pipelines.

![image](https://user-images.githubusercontent.com/3580640/109854691-32488f80-7c0c-11eb-9321-6e4a0b0414ed.png)

**Comment by polar-kev** [comment]
This issue should be fixed before #9378

**Comment by RogPodge** [comment]
Will solve:
#9378
