### ISSUE TITLE
MRTK2 is not work on hololens2 

### ISSUE THREAD

**Issue by 108504877** [microsoft/MixedRealityToolkit-Unity#9429]
## Describe the bug

Iused the case given by the authorities，but is not work.
how can i solve this poroblem?

## step
1.open the Assets/MRTK/Examples/Demos/StandardShader/Scenes/HoverLightExamples.unity;
2.build the Settings like this 
![image](https://user-images.githubusercontent.com/79572516/110201328-7a321580-7e9d-11eb-9165-047e69a8495c.png)
3.Project Settings :
![image](https://user-images.githubusercontent.com/79572516/110201358-9b930180-7e9d-11eb-9bd6-4565d2ad27b7.png)
![image](https://user-images.githubusercontent.com/79572516/110201363-a483d300-7e9d-11eb-9464-9f1598bde3b8.png)
![image](https://user-images.githubusercontent.com/79572516/110201374-aea5d180-7e9d-11eb-87fa-9e1a5e87595c.png)
4.MixedRealityToolkit profile:
![image](https://user-images.githubusercontent.com/79572516/110201431-03494c80-7e9e-11eb-9895-1a7f2aa3ef1c.png)
5.Build and deploy the application
![image](https://user-images.githubusercontent.com/79572516/110201473-37bd0880-7e9e-11eb-9336-6d015bca082d.png)
![image](https://user-images.githubusercontent.com/79572516/110201543-984c4580-7e9e-11eb-9e8a-fa9ab5be9130.png)
6.When i usedit  in Hololens2 ,but is not work.

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.4.21f1]
- MRTK Version [e.g. v2.5.4.0]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

## Additional context

![image](https://user-images.githubusercontent.com/79572516/110051501-f854c600-7d90-11eb-9321-44cf87a1e76d.png)

![image](https://user-images.githubusercontent.com/79572516/110051575-19b5b200-7d91-11eb-9f36-656cd2ac1cb5.png)

https://user-images.githubusercontent.com/79572516/109898119-ab102000-7cce-11eb-991f-516c01db5d2a.mp4

**Comment by eusebiu** [comment]
Make sure you use the correct profile - DefaultHololens2ConfigurationProfile for legacy XR and DefaultHololens2XRSDKConfigurationProfile for XR SDK (new one).

**Comment by davidkline-ms** [comment]
Hi @108504877 , can you add repro steps? HoloLens 2 is a primary device for which MRTK was developed and is tested daily. The team would very much like to help you be successful though we need some more information to be able to help.

Thanks!

**Comment by 108504877** [comment]
> Hi @108504877 , can you add repro steps? HoloLens 2 is a primary device for which MRTK was developed and is tested daily. The team would very much like to help you be successful though we need some more information to be able to help.
> 
> Thanks!
I have updated it.
Plese help me  solve this problem.

**Comment by 108504877** [comment]
> Make sure you use the correct profile - DefaultHololens2ConfigurationProfile for legacy XR and DefaultHololens2XRSDKConfigurationProfile for XR SDK (new one).

Profile as  is  shown in:
![image](https://user-images.githubusercontent.com/79572516/110201663-566fcf00-7e9f-11eb-81b4-a191c1e226d6.png)

**Comment by eusebiu** [comment]
You are trying to use a legacy profile with the XR SDK. 
Please use the DefaultHololens2XRSDKConfigurationProfile. Also remember that legacy XR is not available in newer Unity versions (2020+).

**Comment by eusebiu** [comment]
Also, you will need to configure the build for Holographic.
![image](https://user-images.githubusercontent.com/414589/110201990-a2eee680-7e6e-11eb-9efc-93a6044a8f3b.png)

**Comment by 108504877** [comment]
> You are trying to use a legacy profile with the XR SDK.
> Please use the DefaultHololens2XRSDKConfigurationProfile. Also remember that legacy XR is not available in newer Unity versions (2020+).

how can i get DefaultHololens2XRSDKConfigurationProfile?

**Comment by eusebiu** [comment]
> how can i get DefaultHololens2XRSDKConfigurationProfile?
Should be in the list of profiles in the MixedRealityToolkit object.

**Comment by 108504877** [comment]
> > how can i get DefaultHololens2XRSDKConfigurationProfile?
> 
> Should be in the list of profiles in the MixedRealityToolkit object (see first image from here: https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/configuration/mixed-reality-configuration-guide)

when  i use  the DefaultHololens2XRSDKConfigurationProfile，what happened is like this:

https://user-images.githubusercontent.com/79572516/110225435-8d39f980-7f20-11eb-83f8-04ebb8d5a15c.mp4

**Comment by eusebiu** [comment]
Try running it in debug mode from VS and see the errors in Console.

**Comment by MaxWang-MS** [comment]
@108504877 I would suggest that you start a new project based on these two pages:
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-01
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02
Try to make sure you have all the necessary tools installed and then follow the instructions as closely as you can. If the instructions on the second page work for you you can then build the sample scenes. Please let us know if that works for you.

**Comment by MaxWang-MS** [comment]
Please reopen the issue if you are still encountering it.
