### ISSUE TITLE
MRTK 2.6.0 - compilation issues

### ISSUE THREAD

**Issue by eusebiu** [microsoft/MixedRealityToolkit-Unity#9433]
See https://holodevelopers.slack.com/archives/C2H4HT858/p1614853259077400

 MRTK 2.6 (unity package install) - CS0103	The name 'HandPoseUtils' does not exist in the current context	Microsoft.MixedReality.Toolkit	C:\Personale\LetsVR\LetsVR\Assets\MRTK\Core\Providers\Hands\ArticulatedHandDefinition.cs	285

**Comment by keveleigh** [comment]
From the thread, it looks like HandPoseUtils is still showing up in the Oculus folder. That file was moved to the Core in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8714, so all dependencies should resolve. When you say "unity package install", do you mean with the .unitypackage files? Did you [delete the previous MRTK folder before importing the new package](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/updates-deployment/updating#unity-asset-unitypackage-files)? If not, sometimes Unity leaves behind moved / deleted files.

**Comment by eusebiu** [comment]
Yes, unitypackage files.
I did not delete MRTK but when I searched for HandPoseUtils in VS I found it only in Oculus.

**Comment by keveleigh** [comment]
Since they have the same GUID, Unity will often not move existing files and instead update them in-place 😞

**Comment by eusebiu** [comment]
That makes sense... so, I think I will close this one. :)
Thanks!
