### ISSUE TITLE
Using SyncString

### ISSUE THREAD

**Issue by pampas93** [Microsoft/MixedRealityToolkit-Unity#944]
I'm not able to wrap my head around using SyncString. When I try to put a string to the Value attribute, I get a NullReferenceException.

Anyone mind helping me guide on how exactly to use the SyncString? Is it similar to the SyncVar property of Unity?

My final goal is to just keep a String updated through all the Hololens connected to the Network. 
[Question]
https://forums.hololens.com/discussion/8481/how-exactly-do-i-use-syncstring#latest

**Comment by StephenHodgson** [comment]
`SyncVar` is a [Unity Editor networking attribute](https://docs.unity3d.com/ScriptReference/Networking.SyncVarAttribute.html) to properties and fields.

`SyncString` is a data object in the Sharing Service that acts in a similar way.

Both pretty much sync values on both the client and the server.

To use `SyncString` you need build a data model to use on the server.
See `SyncTransform` for a great example of a data model and its usage.
Also See `TransformSynchonizer` to see how values get updated on your clients.

To create your own data model you need to inherit from `SyncObject`.

Then create a public field you want to sync:
```
public class MySyncDataModel : SyncObject
{
    [SyncData] public SyncString MyString = new SyncString("MyString");

    public event Action MyStringChanged;

    public MySyncDataModel(string field) : base(field)
    {
        MyString.ObjectChanged += OnSyncStringChanged;
    }

    private void OnSyncStringChanged(SyncObject obj)
    {
        MyStringChanged.RaiseEvent();
    }
}

public class MyStringSynchonizer : Monobehavior
{
    public TheStringYoureActuallyTryingToSend
    { 
        get;
        set
        {
            stringDataModel.MyString.Value = value;
        }
    }

    private MySyncDataModel stringDataModel;
    public MySyncDataModel StringDataModel
    {
        private get { return stringDataModel; }
        set
        {
             if(stringDataModel != value)
             {
                  if(stringDataModel != null)
                  {
                      stringDataModel.MyStringChagned -= OnStringChagned;
                  }
                  
                  stringDataModel = value;
                  
                  if(stringDataModel != null)
                  {
                      TheStringYoureActuallyTryingToSend = stringDataModel.MyString.Value;

                      stringDataModel.MyStringChagned += OnStringChagned;
                  }
             }
        }
    }

    private void OnStringChanged()
    {
        stringDataModel.MyString = TheStringYoureActuallyTryingToSend;
    }
}
```

**Comment by pampas93** [comment]
@StephenHodgson Thanks for the detailed reply.
In the MySyncDataModel, I wasn't able to use the ObjectChanged Action for MyString. And isn't TheStringYoureActuallyTryingToSend be a string? I didn't quite understand. 
On click, which string variable should I actually update?

And, Is it not possible to create just use SyncString without creating a data model?

**Comment by StephenHodgson** [comment]
> Is it not possible to create just use SyncString without creating a data model
No

Take a look at how the other data model classes work.
I'm working on a detailed Sharing Service tutorial series that should be released later this year.
(I know it doesn't help in the short term)

**Comment by bickhofe** [comment]
Hi folks, hi stephen,

sending short status messages (strings) for synced objects are so essential. we try for over a week now to modify the transform synchonizer and reduce it to simple string commands to change the appearance of the spawned obj. we simply don't get it. in the sync spawn test is already a test float that inherits from "SyncSpawnedObject" is there any chance to show us how to change this testfloat and how to read it as a client? this would help. (just a few comments in the script to show us the way would we awesome)

regards, peter (and thx for the huge work you do)

**Comment by reillydonovan** [comment]
How would someone implement the TransformSynchronizer with the SyncTransform data model?

**Comment by Firifire** [comment]
@StephenHodgson SyncString  does not inherit from SyncObject. So we cant access ObjectChanged

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
