### ISSUE TITLE
Copy PDB files option in build tools

### ISSUE THREAD

**Issue by MenelvagorMilsom** [microsoft/MixedRealityToolkit-Unity#9444]
## Copy PDB files option in build tools

I see the option to copy pdb files when compiling in editor for both UWP and Standalone Windows:

![image](https://user-images.githubusercontent.com/47415945/110140182-b7c66e00-7dcb-11eb-8f88-b1e6831f324d.png)

However, I couldn't find this option exposed on unity command line, nor in the MRTK command line build scripts. It would be nice to have this option exposed so that we can build with PDB files on CI builds.

## Solution

I suggest we add an bool to `BuildInfo` and flag to `ParseBuildCommandLine` which can then be used to set the some value in the Unity C# build settings.

**Comment by Zee2** [comment]
Closing as stale for now; please reopen if this is still necessary.
