### ISSUE TITLE
SDF Fonts are not writing to depth by default

### ISSUE THREAD

**Issue by carmines** [microsoft/MixedRealityToolkit-Unity#9446]
![image](https://user-images.githubusercontent.com/36190349/110027446-d69f0480-7ce6-11eb-8e09-605d88c83117.png)

All text should be writing to depth when used on HL2 to prevent artifacts. There may need to be logic added to component scripts that have references to these materials so modify this property to know if/when it needs to write to depth. By default it should be writing to depth.

**Comment by keveleigh** [comment]
@carmines heads up that I transferred your two depth issues from the MRTK repo to the MRTK-Unity repo.

**Comment by keveleigh** [comment]
@Cameron-Micka @cre8ivepark Do you remember if there was a reason we didn't set these up to write to depth by default?

**Comment by Cameron-Micka** [comment]
I don't remember as explicit reason why depth write is disabled on them. My guess would be that someone placed the font above a translucent back plate and depth sorting issues (little rectangles where the back plate was not being rendered) and disabled depth write. But that is just a hunch.

My advice would be that we enable depth write by default for text materials or have two variants (a depth write and depth do not write version). 

We should also check this box: 
![image](https://user-images.githubusercontent.com/13305729/110522646-f73fd380-80c5-11eb-9c6c-441bd3ed367c.png) 

Then audit all of the example scenes to make sure we don't see red pixels where we would not expect them.

**Comment by RogPodge** [comment]
@Cameron-Micka do you think this is related to #9503

**Comment by Cameron-Micka** [comment]
My gut reaction would be this is _not_ related to #9503 since that was reported on Oculus Quest. But, not having text write depth could cause readability issues on HoloLens 2.

**Comment by davidkline-ms** [comment]
Should add zwrite off versions of all of the sdf materials and be consistent with when it is on and off

**Comment by davidkline-ms** [comment]
OR remove any zwrite off versions.

**Comment by davidkline-ms** [comment]
Let's add zwrite off versions of all SDF materials and add documentation to explain when you may want one over the other.

We need to review all SDF materials and align them as such:

* mysdf == on
* mysdf_zwrite_off == off
