### ISSUE TITLE
Clipping Primitive Raises MissingReferenceExceptions when removed during runtime

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#9450]
## Describe the bug

A MissingReferenceException is raised when the Clipping Primitive is removed from the scene during runtime. These exceptions persist throughout the lifetime of the application

## To reproduce

1. Go to the ScrollingObjectCollection Example scene.
2. Start the scene
3. Delete the ScrollingObjectCollection GameObject, including it's children.
4. See the MissingReferenceExceptions pile up in the Console

## Expected behavior

No exceptions are raised

## Your setup (please complete the following information)

- Unity Version 2019.4
- MRTK Version 2.5+

## Target platform (please complete the following information)
-All

**Comment by keveleigh** [comment]
This sounds like the cause of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9441 too
