### ISSUE TITLE
Errors creating icon set

### ISSUE THREAD

**Issue by SahilMayenkar** [microsoft/MixedRealityToolkit-Unity#9458]
## Describe the bug

Creating a custom icon set results in the following error for the Quad and Sprite icon options.
`You can't nest Foldout Headers, end it with EndHeaderFoldoutGroup.`

Additionally, increasing the array size does not populate the section with slots to drag the icons into.

## To reproduce

1. Open up a Unity project with MRTK 2.6.0.
2. From the menu bar, navigate to and click on `Assets > Create > Mixed Reality Toolkit > IconSet`.
3. Find and select the new IconSet asset in your project window, and then try to edit its properties in the Inspector window.

These steps are also described in [this page on the docs](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/button#creating-and-modifying-icon-sets).

## Expected behavior

No error should occur, and user should be able to populate arrays with custom sprite/quad icons.

## Screenshots

<img src="https://user-images.githubusercontent.com/12429513/110199822-51236d80-7e28-11eb-870a-b809dfd94fb2.png" width=300px>

## Your setup (please complete the following information)

- Unity Version 2020.2.7f1
- MRTK Version 2.6.0

**Comment by philip-lamb** [comment]
Looks similar to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9354

**Comment by amccraw** [comment]
I'm having the same issue with MRTK 2.6.1 and Unity 2020.3.1f1, I'm currently circumventing it by putting the inspector in debug mode and adding the icons.  Doing that allows the icon set to function correctly when referenced by another script, but the icon list disappears when the inspector is set back to normal mode.

**Comment by davidkline-ms** [comment]
@RogPodge please investigate. thanks!

**Comment by Simcard54** [comment]
Having the same issue with Unity 2020.3.9f1 and MRTK 2.7.0
