### ISSUE TITLE
ImportExportAnchorManager doesn't change the current state to DataRequest when start Downloading

### ISSUE THREAD

**Issue by leo92613** [Microsoft/MixedRealityToolkit-Unity#946]
ImportExportAnchorManager.cs doesn't change the current state to DataRequest when start Downloading the Anchor from the room.

roomManager.DownloadAnchor(currentRoom, currentRoom.GetAnchorName(0))
doesn't return true even the download process is alrealdy undergoing

This bug causes the IEAM keeps call startanchorprocess() in the update loop and potentially breaks the downloading and loading the WorldAnchor.

**Comment by StephenHodgson** [comment]
Probably belongs in the main MixedRealityToolkit repository.

**Comment by StephenHodgson** [comment]
@leo92613 I've updated the sharing service.  Please check to see if this is still an issue.
