### ISSUE TITLE
Investigate creating Azure authentication component

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#9473]
This item covers investigating a common Azure authentication component for MRTK.

Each of the following will be broken out into separate issues in time.

- [ ] What would make a good component for all levels of customer
- [ ] Guidance (don't add credentials into the app code, etc.)
- [ ] Package as a stand-alone MRTK package/component.
- [ ] Example code
- [ ] Documentation

**Comment by eusebiu** [comment]
We are using this for a MRTK based app - https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-overview (only Standalone Windows because MSAL.NET is not supported directly on Android - one could use the native aar and a wrapper).
Are you looking for something else?
