### ISSUE TITLE
Object Manipulator Rotation Broken in 2.6.0

### ISSUE THREAD

**Issue by burkewm** [microsoft/MixedRealityToolkit-Unity#9474]
Rotation behavior is no longer working after upgrading to the newest MRTK update

Game Objects with Object Manipulator and Near Intractable Behavior will no longer rotate based on hand rotation, grabbing at grab point also teleports the objects now. 

1. Add Object Manipulator and Near Intractable to game object.
2. make sure Leap Motion is set up.
3. Play and attempt to rotate object remotely and near by.

## Expected behavior

Object should rotate based off of hand rotation

## Setup:

- Unity Version 2020.2.6f1
- MRTK Version 2.6.0
- Leap Motion

## Target platforms:

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR
- Oculus

**Comment by keveleigh** [comment]
@RogPodge @CDiaz-MS Looks like a combination of the change made in and that the LeapMotionArticulatedHand class isn't raising the source pose event

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/b6c5be20b2f5fda34450873e3ce43ab81118a0aa/Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Scripts/Input/Controllers/OculusHand.cs#L137

should be a straight forward fix, adding `CoreServices.InputSystem?.RaiseSourcePoseChanged` shortly after we get the grip pose: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/b6c5be20b2f5fda34450873e3ce43ab81118a0aa/Assets/MRTK/Providers/LeapMotion/LeapMotionArticulatedHand.cs#L235-L239

**Comment by burkewm** [comment]
Can confirm that the fixed worked for me, thanks for the very fast response time with this!

**Comment by keveleigh** [comment]
Closing as fixed in the upcoming 2.6.1 release. Thanks @burkewm for verification!
