### ISSUE TITLE
HoloLens 2 features not working with OpenXR

### ISSUE THREAD

**Issue by leonunity** [microsoft/MixedRealityToolkit-Unity#9476]
## Describe the bug

We're having trouble with spatial mapping on a build for HoloLens 2 using OpenXR.
With MRTK 2.5.4, we can't get spatial mapping to work, even after cloning and modifying the MRTK profiles as shown [on this page](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/configuration/getting-started-with-mrtk-and-xrsdk). Other features like hand tracking do work.

With MRTK 2.6, spatial mapping still doesn't work for us, and we also can't get hand tracking to work.

If we don't use OpenXR, it all works for us, but our project requires we use OpenXR.

We're not sure if this is a bug or just additional configuration needed when using OpenXR. We've tried following the latest docs.

We have sample projects that we can share.

## To reproduce

1. Have an app using the XR Plugin Management system, the OpenXR Plugin and the Mixed Reality OpenXR plugin in a Unity app, with MRTK 2.5.4 and spatial mapping enabled.
2. Create a build with the Surface Magnetism sample scene.
3. Deploy to HoloLens 2.
4. The panels do not stick to the surfaces, and the spatial mapping mesh is not visible.

## Expected behavior

The panels stick to the surfaces, and the spatial mapping mesh is visible (like it is when using WMR instead of OpenXR).

## Screenshots

(None for now)

## My setup

- Unity 2020.2.3f1
- MRTK 2.5.4 (also 2.6)
- HoloLens 2 with OS version 10.0.19041.1136

## Target platform

- HoloLens 2

## Additional context

I can send sample projects showing the problem. It all works with WMR (no OpenXR).

**Comment by keveleigh** [comment]
>With MRTK 2.5.4, we can't get spatial mapping to work, even after cloning and modifying the MRTK profiles as shown on this page. Other features like hand tracking do work.

Spatial mapping is next on my backlog to implement on the OpenXR plug-in side of things. https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/openxr-supported-features#whats-coming-soon can keep you up-to-date with the current state of OpenXR support in Unity in general, with MRTK support following shortly after.

>With MRTK 2.6, spatial mapping still doesn't work for us, and we also can't get hand tracking to work.

This was a regression in 2.6. The fix is in #9430 and we'll be shipping a 2.6.1 hotfix soon.

**Comment by keveleigh** [comment]
I opened https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9491 to track the spatial mapping implementation
