### ISSUE TITLE
Can't import examples package MRTK2.6.1

### ISSUE THREAD

**Issue by jelmerS2** [microsoft/MixedRealityToolkit-Unity#9496]
## Describe the bug

Unity 2020.2.3 says "Failed to import package with error: Couldn't decompress package" when trying to import Microsoft.MixedReality.Toolkit.Unity.Examples.2.6.1.unitypackage downloaded from https://github.com/microsoft/MixedRealityToolkit-Unity/releases

## To reproduce

-Get Microsoft.MixedReality.Toolkit.Unity.Examples.2.6.1.unitypackage from https://github.com/microsoft/MixedRealityToolkit-Unity/releases
-Try to import into Unity 2020.2.3

## Expected behavior
Package should import

- Unity Version 2020.2.3
- MRTK Version 2.6.1

## Additional context
Windows machine 
the foundation package imported fine. 
Existing project.

**Comment by alwinv** [comment]
I can confirm the repro - examples package fails with "Failed to import package with error: Couldn't decompress package" (https://github.com/microsoft/MixedRealityToolkit-Unity/releases/download/v2.6.1/Microsoft.MixedReality.Toolkit.Unity.Examples.2.6.1.unitypackage)

**Comment by studentutu** [comment]
Examples are failing to decompress - tried on empty project both on 2018.4 and 2019.4

**Comment by keveleigh** [comment]
Not sure what happened, but it looks like the original upload was corrupted somehow. I've just re-uploaded the examples package to the release, so please re-download! After testing it locally, this new upload looks good to go.

**Comment by alwinv** [comment]
Works now! Thanks!
