### ISSUE TITLE
Unable to Deploy OpenXR MRTK to Oculus Quest 2

### ISSUE THREAD

**Issue by dilmerv** [microsoft/MixedRealityToolkit-Unity#9499]
Hello guys,

I tried for hours with many different settings and I have previously setup Oculus Quest 2 with MRTK without problems, however this time I wanted to try OpenXR but it seems like there should also be a "OpenXR Plugin for Oculus" in order for this to work? or am I mistaken?

The result when it deploys to Oculus 2 is a crash and a dialog stating that my app is not responding.

## Screenshots

![image](https://user-images.githubusercontent.com/1216121/111113370-47d08a00-8527-11eb-822d-ab71b0182871.png)

![image](https://user-images.githubusercontent.com/1216121/111113410-59199680-8527-11eb-8055-87602aaa729c.png)

![image](https://user-images.githubusercontent.com/1216121/111113634-b281c580-8527-11eb-96cd-ae33f2f993f0.png)

![image](https://user-images.githubusercontent.com/1216121/111113697-c3cad200-8527-11eb-9dd8-bc17bb2924dd.png)

## Your setup (please complete the following information)

- Unity Version 2020.2.7f1
- MRTK Version 2.6.1
- Mixed Reality OpenXR Plugin 0.1.4
- Oculus Integration 25.0

## Target platform (please complete the following information)

- Oculus Quest 2

**Comment by dilmerv** [comment]
Duplicated I didn't see a previous open issue.

**Comment by dilmerv** [comment]
Reopening, I saw #9497 but it is different than this, this is during deployment where 9497 is in play mode.

I also saw this article from Oculus to active [OpenXR in experimental mode (https://developer.oculus.com/documentation/unity/unity-openxr/) but still crashes when the app opens.

**Comment by polar-kev** [comment]
Hey @dilmerv, it's not clear if this crash is being caused by MRTK or something else. Could you provide a player log? Have you retested on the latest version of Unity/OpenXR package?

**Comment by keveleigh** [comment]
@dilmerv Another update: it looks like the latest Unity OpenXR package (1.2.0) should have better support for Quest! I haven't been able to test myself, but I was told they added better support for the Oculus deployment tools for Android.

**Comment by davidkline-ms** [comment]
@elbuhofantasma confirmed that 2.7.0 and OpenXR was able to deply to Quest 2 successfully.

**Comment by polar-kev** [comment]
@elbuhofantasma, do you have any details to share here?

**Comment by polar-kev** [comment]
@elbuhofantasma confirmed that he was able to deploy to device.
