### ISSUE TITLE
Quality Settings Regression

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#950]
The default names for QualitySettings Levels have been changed in [Unity 2017.1.0f3](https://unity3d.com/unity/whats-new/unity-2017.1.0).

> Graphics: The default names for Graphics Quality Levels have been changed to be a little clearer, and more in line with what is common across other games. This will only affect newly created projects; existing projects will have the same Quality Level names as before (though, as always, you can edit the names via Edit -> Project Settings -> Quality).

This affects the [Project Setup Window](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/813d94b05377328e716fa3bb43443ade50d62519/Assets/HoloToolkit/Utilities/Scripts/Editor/ProjectSettingsWindow.cs#L84) for the toolkit, when it sets the quality settings for you.

The code attempts to do a string comparison and we need a new way to calculate the lowest settings.

**Comment by jessemcculloch** [comment]
There is a further issue with the Dev_Unity_2017.2 branch, in where the MixedRealityCamera does some setting of these levels for you.  However they are using a deprecated enum that has these values hardcoded

**Comment by StephenHodgson** [comment]
Yeah I've already fixed it in my private branch of 2017.2

**Comment by jessemcculloch** [comment]
How?

**Comment by StephenHodgson** [comment]
I'll probably submit a PR for it soon

**Comment by genereddick** [comment]
So, is the new "Very Low" setting the one we should use?

**Comment by StephenHodgson** [comment]
Check out my PR.  It iterates and decreases the level each time it finds a new setting, then sets the default.
