### ISSUE TITLE
There is No Proper Documentation available for Mixed Reality Headsets

### ISSUE THREAD

**Issue by ashishash** [microsoft/MixedRealityToolkit-Unity#9500]
## Describe the issue
There is No Proper Documentation available for Mixed Reality Headsets. provided in Mixed Reality Docs. How to get started.

## Feature area
![deploy](https://user-images.githubusercontent.com/10698763/111132466-670afe00-859f-11eb-8bb1-b66cf1123e55.PNG)

## Existing doc link
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-visual-studio?tabs=hl2

there is no proper guide that says how to deploy for Mixed Reality Headsets, its all about Hololens 2  and Hololens 1

they mentioned Mixed reality Simulator but not about Mixed Reality Headsets. How to connect via Visual Studio.

**Comment by keveleigh** [comment]
In the page you linked, I see a section called [Deploying a VR app to your local PC](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-visual-studio?tabs=hl2#deploying-a-vr-app-to-your-local-pc). Does this cover what you're looking for?

Also, for future reference on non-MRTK docs, you'll want to click the "This page" button under "Feedback" at the bottom of the doc page to file issues and submit feedback:

![image](https://user-images.githubusercontent.com/3580640/111235060-20240500-85ad-11eb-91a9-b538a0a2a956.png)

It takes you to the [docs repo](https://github.com/MicrosoftDocs/mixed-reality).

**Comment by MaxWang-MS** [comment]
Please reopen the issue if you are still encountering it.
