### ISSUE TITLE
Improve text readability and and bondary rendering from far away

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#9503]
## Describe the problem

Issue tracking points 2 and 3 on this issue: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9497

**Comment by ssiiddaa** [comment]
Hi, was this issue resolved? Was the fix merged? Thank you!

**Comment by Zee2** [comment]
SDF font rendering + depth write should result in highly readable text on all platforms.
