### ISSUE TITLE
Near interaction support with controllers

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#9505]
## Describe the problem

Currently, our near interaction pointers (poke and grab) are only supported with articulated hands, making them unusable with controllers and other non-articulated hand scenarios. This issue tracks making these pointers usable in those scenarios.

Requested by #9497

**Comment by keveleigh** [comment]
The grab pointer _should_ work with controllers, we just don't currently have them enabled in the profile. There's code for the pointer to fall back to source position if the required hand joints aren't available:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/d4a891b1829a3fa00de0e8cde5bfd9e71e91f966/Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs#L252-L257

**Comment by RogPodge** [comment]
Updated the original issue with some clarity. Though currently there's not much functional difference between having/not having the grab pointer with Quest, when we implement #9293 it should be more apparent that a user is doing a grab interaction.

**Comment by Tiger-Cross** [comment]
I may be wrong but I believe these are enabled for the Oculus Quest devices in Eric Provencher's [MRTK Quest](https://github.com/provencher/MRTK-Quest) Plugin. I'm currently developing an application where this type of interaction would be extremely useful, since I have disabled the hand-ray.

**Comment by MikkelVirsabi** [comment]
I'm just going to bump this issue. The lack of articulated hand support similar to Provencher's MRTK Quest fork can really be felt after we upgraded one of our projects to the official MRTK. If I had time I would look into it myself. I can see it has been added to the backlog, but what is a realistic timeline for this feature request?

**Comment by RogPodge** [comment]
@MikkelVirsabi sorry for the late reply, a PR is out for this feature, it just needs to be reviewed and approved. Expect it in our next MRTK release!

**Comment by whitebozo** [comment]
I don't see this listed under 2.7.3 changelog is this fixed in current version of MRTK? Or was this pushed to 3.0?

**Comment by RogPodge** [comment]
Unfortunately it's waiting for our next release, since it was considered a new feature. We hope to have it out in April or May
