### ISSUE TITLE
Build Tool fails due to incorrect Win 10 SDK location read from registry

### ISSUE THREAD

**Issue by micha-tum** [microsoft/MixedRealityToolkit-Unity#9507]
## Describe the bug

Apparently, the Unity MRTK cannot find the Windows 10 SDK since reading the location information from the registry. This was introduced by pull request #9147 (should have fixed #9146).

## To reproduce

- Install Windows 10 SDK on 64bit Windows 10
- Try to build project with build window

## Expected behavior

Build tools uses the correct location of the Win 10 SDK. It is installed in the "Program Files (x86)" folder on x64 machines. The correct registry entry that should be read is in the **WOW6432Node** (but only on 64bit Windows):
```reg
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Kits\Installed Roots]
"KitsRoot10"="C:\\Program Files\\Windows Kits\\10\\"
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows Kits\Installed Roots]
"KitsRoot10"="C:\\Program Files (x86)\\Windows Kits\\10\\"
```

## Actual behavior
MRTK probably reads the Win 10 SDK location from the "[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Kits\Installed Roots]" entry which results in the "Program Files" (non-x86) path where the SDK is not installed. 
This produces the following error:
```
Error:
DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\Windows Kits\10\Lib'.
```

## Setup

- Unity Version  2019.4.21f1
- MRTK Version v2.6.1

## Target platform

- HoloLens 2

## Additional context

See the fixes in other repos:
https://bugzilla.mozilla.org/show_bug.cgi?id=1364137
https://github.com/mxre/winres/issues/14

**Comment by keveleigh** [comment]
Interestingly, my entry in the non-WOW6432Node path is correct, which must be why I didn't hit this while testing:

![image](https://user-images.githubusercontent.com/3580640/111344280-776fb700-8639-11eb-82fa-61c445d2b745.png)

**Comment by micha-tum** [comment]
The reason might be that I installed the 64bit version of the HoloLens 2 emulator which installs to the (non-x86) "Program Files" folder and maybe sets the non-WOW6432Node (aka 64bit) path of the KitsRoot10 entry.
