### ISSUE TITLE
1st Draft of Data Binding and Virtualization framework

### ISSUE THREAD

**Issue by m-the-hoff** [microsoft/MixedRealityToolkit-Unity#9517]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/310

___

Support for data binding and localization of text and other assets. This framework is a combination of platform agnostic and Unity specific code.

**Comment by polar-kev** [comment]
Many of the issues we're seeing with scrolling object collection will be fixed by this--particularly with large lists, performance, and using dynamic data.
