### ISSUE TITLE
Missing Script in HandMenu prefabs

### ISSUE THREAD

**Issue by zxubian** [microsoft/MixedRealityToolkit-Unity#9523]
## To reproduce

1. In an empty project, get the following features via the Feature Tool:
![image](https://user-images.githubusercontent.com/8446683/111569891-fa824000-87e6-11eb-9859-87519f471066.png)

2. Open any of the hand menu prefabs (e.g.) HandMenu_Large_AutoWorldLock_On_HandDrop.prefab
@packages\com.microsoft.mixedreality.toolkit.examples\Common\Prefabs

## Expected behavior

The prefab is valid and can be dropped in the scene and usesd.

## Actual behaviour
Selecting the prevab gives the following unity warning in the inspector: 

"Prefab has missing scripts. Open Prefab to fix the issue."

Opening the prefab reveals that the bottommost script is missing.

## Screenshots

![image](https://user-images.githubusercontent.com/8446683/111570051-5220ab80-87e7-11eb-8e2b-df8f38c5ede8.png)
![image](https://user-images.githubusercontent.com/8446683/111570204-9d3abe80-87e7-11eb-8218-14fc95e90e0b.png)

## Your setup (please complete the following information)

- Unity Version: 2019.4.22 (LTS)
- MRTK Version: 2.6.1 via MRFT

## Target platform (please complete the following information)
 - UWP (HoloLens 2)

**Comment by zxubian** [comment]
Fixed upon importing Examples from the package manager.

**Comment by Wyrlock** [comment]
I know this is a bit old, but, what script was it?  I'm experiencing the same thing, but after already importing Examples.
