### ISSUE TITLE
There is no Input Data Providers Type, Help me.

### ISSUE THREAD

**Issue by parsley777** [microsoft/MixedRealityToolkit-Unity#9525]
## Describe the bug

1. I installed MRTK(Foundation, Example) in Unity.
2. I went into the HandInteractionExamples Scene.
3. I saw the bug, Console message is 

'Unable to register IMixedRealityInputDeviceManager data provider (Windows Mixed Reality Device Manager) because the value of concreteType is null.
This may be caused by code being stripped during linking. The link.xml file in the MixedRealityToolkit.Generated folder is used to control code preservation.'

'Unable to register IMixedRealityInputDeviceManager data provider (Windows Mixed Reality Eye Gaze Provider) because the value of concreteType is null.
This may be caused by code being stripped during linking. The link.xml file in the MixedRealityToolkit.Generated folder is used to control code preservation.'

4. I took the route below to investigate the problem.
Hierarchy > MixedRealityToolkit > MixedRealityToolkit Script > Input > Input Data Providers > Windows Mixed Reality Device Manager > Type

5. The type item is marked in red, and there is an error.
6. There are two things marked in red ones.
- Windows Mixed Reality Device Manager > Type
- Windows Mixed Reality Eye Gaze Provider > Type

## Screenshots
![20210318_180342](https://user-images.githubusercontent.com/80885893/111601657-edc91080-8815-11eb-9e80-00283411d66b.jpg)
![20210318_181551](https://user-images.githubusercontent.com/80885893/111601815-14874700-8816-11eb-8ebb-baa1ef8b05a2.jpg)
![20210318_181609](https://user-images.githubusercontent.com/80885893/111601824-16e9a100-8816-11eb-8c06-b2e6e29300f8.jpg)

## Your setup (please complete the following information)

- Unity Version 2020.2.7
I tested Unity 2019.4.8  version, but the same problem occurred.
- MRTK Version 2.6.1
I tested MRTK 2.5.3  version, but the same problem occurred.

## Target platform (please complete the following information)
- HoloLens 2

**Comment by iluvian** [comment]
我遇到和你一样的问题，请问这个bug解决了吗？如何解决的呢

**Comment by MaxWang-MS** [comment]
Please see the solution in #9528.
