### ISSUE TITLE
Interactable Multi-Dimension Event support

### ISSUE THREAD

**Issue by derekfreed** [microsoft/MixedRealityToolkit-Unity#9526]
## Describe the problem

When using a multi-dimension interactable, developers must create a script to route onclick events according to each dimension.

## Describe the solution you'd like

The solution I would like is an EventReceiverType that will respond to click events for each dimension of the button. This sort of behaviour is supported by the visual profiles but not for functional use cases.

## Describe alternatives you've considered

As stated in the problem, my current alternative is to create a script that listens to the onclick and routes event triggers based on the current dimensional index of the interactable

## Additional context

![image](https://user-images.githubusercontent.com/10147303/111670163-e988fd00-87ed-11eb-82fc-90b3d5f7fcbf.png)
![image](https://user-images.githubusercontent.com/10147303/111670233-fb6aa000-87ed-11eb-8e30-114aae05662e.png)

**Comment by PJBowron** [comment]
Additionally, although the alternative solution that Derek describes works well enough, what spoils things is that `Interactable` increments `CurrentDimension` _before_ the invocation of the OnClicked event, so we have to reinterpret the value in the delegate in order to trigger the corresponding response.

**Comment by Zee2** [comment]
Closing as stale, please reopen if necessary. We've pursued an alternative approach to interactables in MRTK3, using XRI interactables and the new `StateVisualizer`. Check it out, and see if it solves your needs!
