### ISSUE TITLE
2.6.x shader copy code appears to not be working in some situations

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#9527]
This issue was filed on the documentation site https://github.com/MicrosoftDocs/mixed-reality/issues/237.

**Comment by davidkline-ms** [comment]
Investigating this as potentially being Unity not executing script code due to compile errors (there is a likely long path issue for at least one customer)

**Comment by lazerwalker** [comment]
It's worth calling out that I'm encountering this on 2.5.4, not 2.6.x (more info on my situation in the linked issue), although I am using a version of the Mixed Reality Feature Tool that supports 2.6

**Comment by davidkline-ms** [comment]
looks to be path length related
