### ISSUE TITLE
Oculus Hand-tracking Integration not working in Android build, but working in editor via Oculus Link.

### ISSUE THREAD

**Issue by WuchiOnline** [microsoft/MixedRealityToolkit-Unity#9534]
## Describe the bug

The MRTK in my project does not seem to be properly integrating Oculus hand-tracking when building to Android.

However, the hand tracking seems to work perfectly through the Unity editor and Oculus Link. The hand mesh renders properly, as do all of the interactions (teleport, near/far interaction, etc). When I make an Android build, the hand mesh does not render and I can't use the teleport gesture, and I imagine none of the other hand-tracking interactions work as well. I can exit the app using Oculus's palm-up pinch gesture, so I know the hand-tracking is working on the hardware side.

## To reproduce

MRTK-Oculus hand-tracking in Android builds was working properly until a couple weeks ago, when I temporarily disabled the Input System in the Input tab on the MRTK Configuration component. After I renabled it, it was no longer working in Android builds. I have a near-identical copy of the same project in which I never disabled the Input System, and it all works perfectly. I have used that as a reference on what the proper settings are for MRTK-Oculus integration.

## Your setup (please complete the following information)

- Unity 2019.4.17f1
- MRTK v.2.5.4 and 2.6.1

## Target platform (please complete the following information)

- Oculus Quest 1/2

## Additional context

Fixes I've tried:

Manually cloning profiles by mirroring the settings to another near-identical project (which works properly across the board)

Cloning all of the profiles again as a sanity-check. Same settings as the working configuration.

Upgrading to the latest MRTK v. 2.6.1

I always integrate oculus modules before building.

I've added a ovrAppID and ovrGearAppID.

I've manually toggled XRSettings.asset between False and True (Unity automatically sets it to True if you browse through the XR sections of Player Settings, even if you don't change any configurations)

I've meticulously inspected as much of the profiles and MRTK settings as I could and there seems to be no reason why this should be happening. I'm out of ideas, and this has become a blocker for me, as I don't want to continue to develop on this project folder if there is a chance of not being able to repair this down the road. Any advice would be super duper appreciated. Thanks.

**Comment by keveleigh** [comment]
@RogPodge Any ideas? This almost sounds like the opposite of what I'd expect 😅

**Comment by WuchiOnline** [comment]
An update: I've added some other things I've tried to resolve the issue.

On the brightside: fortunately I was able to find the last commit where everything was working, checked it out in a cloned repo, and was able to build successfully with everything working properly. This is peculiar though because I've already analyzed all of my diffs and any deltas related to configs were reverted/resolved. If I can't figure out the issue soon, I will resort to checking out the working commit, migrating all progress since then into a detached head, and moving on from there. Reconstructing my work from a stable point was always a last resort though, since my goal is to understand MRTK more deeply, so it feels a bit dirty to walk away from a bug without solving it.

I will try to reproduce the issue from the working commit when I have some spare time this weekend.

**Comment by RogPodge** [comment]
@WuchiOnline can you double check your Hand Tracking Profile? (should be located in the attached image). Outside of this getting reverted/not saved somehow I'm also completely unsure as to how the mesh gets toggled off on device but remains visible in editor...

Will make sure to double check this case as we revisit our profile system.

![image](https://user-images.githubusercontent.com/39840334/112041083-3547e900-8b03-11eb-8826-624bad640544.png)

**Comment by WuchiOnline** [comment]
@RogPodge Thanks for taking a look. Yeah I'm completely baffled too. The hand-tracking profile is properly configured, as are the other profiles.

Time permitting, I'll be spending this weekend debugging this some more. Hopefully, I'll have more notes on this soon. Have a great rest of the week.

**Comment by WuchiOnline** [comment]
@RogPodge @keveleigh hope you both had a great week. I have some good (and confusing) news regarding this issue!

It still makes no sense to me, but I am relieved to have found the source and solution.

As part of one of my many hail mary attempts to reproduce this bug, I decided to make a build in which I enabled my Unity splash screen. I typically have this off, but I figured why not... I've already turned every other stone.

Inexplicably, the build with the splash screen enabled worked in my controlled debugging environment. I just enabled the splash screen on the latest commit in my development branch, and confirmed that the hand-tracking is all working properly again within both the Unity Editor and standalone Android builds.

Any idea why this would be the case? Thanks again for taking a look into this issue, I hope this helps prevent any future related bugs.

**Comment by WuchiOnline** [comment]
A thought: could it be that Oculus' app ID (or some other process) is initialized during the splash screen?

**Comment by WuchiOnline** [comment]
I've stripped down the project with the reproduced issue and have submitted a bug report to Unity. In case you're interested, here's a download link to the project zip: https://www.dropbox.com/s/wayqszzrky9t59c/Wuchi_MRTKQuestHandtrackingSplashBug.zip?dl=0

One more thing I tested: disabling the splash image causes the issue, regardless of if I'm logged into Unity hub or not. I figured maybe the issue was caused by my Unity subscription not being detected and conflicting with the disabling splash image feature, but that doesn't seem to be the case.

**Comment by RogPodge** [comment]
Wow! that's a really wild find! I can't believe that it was all because of the splash screen 😅😅💦💦

Thank you so much for looking into the issue, can you @ me when the bug is accepted and publicly tracked by Unity so we can add it to our documentation? Going to close this for now in the meantime.

Thank you so much for discovering this!

**Comment by RogPodge** [comment]
@polar-kev can you forward this splash screen issue to Unity so we can have it listed as higher priority?

@WuchiOnline do you have a link/confirmation of the sent bug report we can use to try to help elevate?

**Comment by WuchiOnline** [comment]
@RogPodge Sure thing, here's the Unity Bug Case #: 1325113

**Comment by polar-kev** [comment]
Hey @WuchiOnline, the Oculus XR Plugin 1.10.0 preview 1 has been released https://docs.unity3d.com/Packages/com.unity.xr.oculus@1.10/manual/index.html

Can you please let us know if this fixes your issue?
