### ISSUE TITLE
Files wont open in unity

### ISSUE THREAD

**Issue by Lo118** [microsoft/MixedRealityToolkit-Unity#9535]
## Describe the bug

when i try to open the unity projekt a error message popped up. it says that there is an uexpectet file end (zlib) whitch is odd sice there is no file with that end in the project also its only for the 2 largest files (remoterendering/examples). the rest works and the zlib.ddl seems to be working. windows cant find anything wrong with it so im cluless.

## To reproduce

idk i think its a problem with the pc so idk if you can reproduce it.

## Expected behavior

i expect there to be no error message and the packets to show up when i open unity.

## Screenshots

![error](https://user-images.githubusercontent.com/42409590/111986707-988b4880-8b0e-11eb-905c-c97b43b5f072.png)

## Your setup (please complete the following information)

- Unity Version 2019.4.20f1
- MRTK Version 1.0.2103.2

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

**Comment by keveleigh** [comment]
@davidkline-ms This sounds like one of the MR Feature Tool issues that was fixed/improved in the latest release?

**Comment by Lo118** [comment]
Ill try it.thx

**Comment by Lo118** [comment]
> 
> 
> @davidkline-ms This sounds like one of the MR Feature Tool issues that was fixed/improved in the latest release?

ok downloading it again did not work to fix the issue. i might be downloading from the wrong sorce? https://www.microsoft.com/en-us/download/details.aspx?id=102778 idk but if i need to update that or somthing pls let me know.

**Comment by davidkline-ms** [comment]
@Lo118, That is the correct source.

Can you go to c:\users\<your name>\AppData\Local\MixedRealityFeatureTool and find the log file? I would be happy to take a look and see if it contains any issues or clues to what you are experiencing.

There is logic in the 1.0.2103.2 version that should protect against 0 length files, but it is possible that the file is somehow getting corrupted in a different way,

**Comment by Lo118** [comment]
> @Lo118, That is the correct source.
> 
> Can you go to c:\users\<your name>\AppData\Local\MixedRealityFeatureTool and find the log file? I would be happy to take a look and see if it contains any issues or clues to what you are experiencing.
> 
> There is logic in the 1.0.2103.2 version that should protect against 0 length files, but it is possible that the file is somehow getting corrupted in a different way,
> 

Will do but this is a projekt for an intenship so i wont be abel to send it untill tomorrow (might never send it bc ill be working on a diffrent pc whitch might not have the issue. No worrys ill close this if that is the case but i alredy thank yall for your time)

**Comment by davidkline-ms** [comment]
no problem. if there is any way we can help, please let us know.

**Comment by peter-clemenko** [comment]
I'm getting the same issue.

**Comment by peter-clemenko** [comment]
[MixedRealityFeatureTool.log](https://github.com/microsoft/MixedRealityToolkit-Unity/files/6365463/MixedRealityFeatureTool.log)
This is my log file. No zlib mentioned in the log.

**Comment by davidkline-ms** [comment]
@peter-clemenko, which package(s) are showing the error? your log looks as if everything downloaded successfully (no zero length files). that info may help diagnose the specific trouble you are seeing, thanks!
