### ISSUE TITLE
Restrict the region of spatial mapping

### ISSUE THREAD

**Issue by LexieMeng** [Microsoft/MixedRealityToolkit-Unity#954]
I am trying to scan a single object with Hololens. I do not want the meshes of the whole room, instead, I want to restrict the region of spatial mapping to get meshes in certain space. Does anyone have any idea about how can I do that?

**Comment by niklas87** [comment]
I'd suggest you to set the "Origin" parameter of the Spatial Mapping Observer to the center of your POI and change the observed volume ("extents") to the desired amount.

As I'm not sure if the origin is oriented at the main camera position or the Unity scene origin, you'll have to find out by yourself. I had a quick glance into the Spatial Mapping Observer class but you can only see that the origin vector is passed to the Surface Observer which only provides meta information about the methods. Maybe the [documentation](https://docs.unity3d.com/ScriptReference/VR.WSA.SurfaceObserver.html) provides additional information.

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
