### ISSUE TITLE
Unable to register IMixedRealityInputDeviceManager data provider

### ISSUE THREAD

**Issue by iluvian** [microsoft/MixedRealityToolkit-Unity#9540]
## Import a new MRTK and report an error directly
unity 2020.2.2
![image](https://user-images.githubusercontent.com/39895100/112150139-b8a82e00-8c1a-11eb-8993-8a5016deb08d.png)

**Comment by MaxWang-MS** [comment]
Please see my response to a similar case in #9528. Also please fill out our template bug report next time or it may be very hard for us to try to fix the issue without the information requested in that template.
