### ISSUE TITLE
Click flickering rapidly on 2 finger pinch - Quest

### ISSUE THREAD

**Issue by SiriusA7** [microsoft/MixedRealityToolkit-Unity#9544]
## Describe the bug

Started happening after upgrading to MRTK v2.6
When doing a 2-finger pinch, before the index and thumb meet there is a rapid fire click flickering. When the 2-fingers finally meet, it goes back to normal.

I've included a video below demonstrating the issue.

## To reproduce

Setup a new MRTK unity project for quest following the directions in the documentation.
Build and install to Quest 1 or 2 headset.

## Expected behavior

No rapid input flickering when pinching to interact with something.

## Your setup (please complete the following information)

- Unity Version: 2019.4 LTS, 2020.2 & 2020.3 LTS
- MRTK Version: v2.6 & v2.6.1

## Additional context

https://user-images.githubusercontent.com/35086581/112251889-4b47cd80-8c19-11eb-8e82-2c9454c0c0bc.mp4

**Comment by stychu** [comment]
+1 I also experienced this behaviour

**Comment by akzeac** [comment]
I also saw something similar. Does it also happen with the left hand?

**Comment by keveleigh** [comment]
@rogpodge have you seen this?

**Comment by RogPodge** [comment]
I haven't seen this issue before. The flickering of the pointer reminds me of a bug we had before where mrtk would rapidly flicker between near and far interaction modes, so it's possible we had a regression there (will investigate)

**Comment by SafetyOrange** [comment]
+1 can successfully reproduce with MRTK 2.6.1 & Unity 2020.3.1
