### ISSUE TITLE
Windows Speech Input Provider generates Assertion failed error with non XR SDK profiles

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9545]
## Describe the bug

When using the in-editor player to run example scenes, after the 3rd session the Windows Speech Input Provider generates an Assertion failed error every time the in-editor player is used. The error is generated on every example scene in the MRTK after it starts showing up. This issue happens without the XR SDK installed and with the XR SDK installed when trying to use a non XR SDK profile in the Unity 2020 LTS. The error will not generate for the first 2 in-editor player sessions after restarting the editor when the project has encountered the error, but will start generating again on the 3rd session.

## To reproduce

1. Create a new project and import the MRTK
2. Open any example scene
3. Choose the 'DefaultMixedRealityToolkitConfigurationProfile" for No XR SDK installed/XR SDK installed or "DefaultOpenXRConfigurationProfile" for OpenXR
4. Press the Play button to start the in-editor player
5. See error

## Screenshots

![standaloneinputprovider](https://user-images.githubusercontent.com/65038391/112287994-27e94680-8c4a-11eb-9faf-9ccfea9f7f36.PNG)
![xrsdksettings](https://user-images.githubusercontent.com/65038391/112288451-95957280-8c4a-11eb-9a71-402b6019c9ff.PNG)
![noXRSDKsettings](https://user-images.githubusercontent.com/65038391/112288460-975f3600-8c4a-11eb-8e72-db5e63b774d3.PNG)

## Your setup (please complete the following information)

- Unity Version 2020.3.0f1 
- Unity Version 2020.3.1f1
- MRTK Version 2.6.1
- XR SDK
- No XR SDK
- OpenXR

## Target platform (please complete the following information)

- Standalone
- UWP
- Android

## Additional information
This issue happens on OpenXR with the DefaultOpenXRConfigurationProfile.

**Comment by keveleigh** [comment]
Since this error is happening in Unity code (`UnityEngine.Windows.Speech.PhraseRecognizer.Start()`) can you file a Unity bug please? Sounds like they might not be cleaning something up properly.

**Comment by polar-kev** [comment]
We should test this on Unity 2019 to see if this is a newly introduced problem.

**Comment by RogPodge** [comment]
Potentially be solved by:
#9419

**Comment by polar-kev** [comment]
@elbuhofantasma, can you make sure to double check this in the next build call?

**Comment by elbuhofantasma** [comment]
I can confirm that this issue is fixed by #9419 and is not present in 2.7 with XR SDK and OpenXR on Unity 2020.3.7f1
