### ISSUE TITLE
NullReferenceException is generated with the in-editor player and an XR SDK profile

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9546]
## Describe the bug

When using the in-editor player and an XR SDK profile to run the example scenes, a NullReferenceException is generated once as well as a constantly generating error for the XR SDK Windows Mixed Reality Device Manager. The Device Manager error will generate as long as the in-editor player is running an example scene.

## To reproduce

1. Create a new project and import the MRTK and the XR SDK
2. Open any example scene
3. Change the profile to "DefaultXRSDKConfigurationProfile"
4. Press the Play button
5. See errors

## Screenshots

![XRnullexception](https://user-images.githubusercontent.com/65038391/112297677-6df6d800-8c53-11eb-90fa-d5484b325ea6.PNG)
![devicemanagererror](https://user-images.githubusercontent.com/65038391/112297830-941c7800-8c53-11eb-985c-75c50469c3c6.PNG)
![devmanagererrorfulllist](https://user-images.githubusercontent.com/65038391/112297952-b615fa80-8c53-11eb-890d-1f433acf53ff.PNG)
![oculusdevmanager](https://user-images.githubusercontent.com/65038391/112299962-8f58c380-8c55-11eb-9ca6-cde9094b1769.PNG)

## Your setup (please complete the following information)

- Unity Version 2020.3.1f1
- MRTK Version 2.6.1

## Target platform (please complete the following information)

- Standalone
- UWP
- Android

## Additional context

This issue also occurs on OpenXR with the DefaultOpenXRConfigurationProfile, after adding the OpenXR package with the Feature Tool but only before the user enables the OpenXR plugin for any Platform in the XR Plugin Manager.

**Comment by keveleigh** [comment]
@elbuhofantasma Can you check this against the dev branch please? This sounds like https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9469, which was fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9521

**Comment by Zee2** [comment]
Closing as duplicate and fixed
