### ISSUE TITLE
'Virtual reality supported not enabled' warning is generated with no XR pipeline package in a project

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9547]
## Describe the bug

When the in-editor player is used to run an example scene in the Unity 2020 LTS, the 'Virtual reality supported not enabled' warning is generated. This issue occurs with the OpenXR + XR Plugin Manager packages are installed in a project. This issue also occurs on a new 2020 LTS project that has not installed the XR Plugin Manager or the OpenXR package. This issue does not occur in 2020 LTS projects that have the XR Plugin Manager + Windows XR Plugin in them.

## To reproduce

1. Create a new project and import OpenXR with the Feature Tool
2. Configure your project settings for OpenXR
3. Open any example scene
4. Press the 'Play' button to start the in-editor player
5. Look at the Console and 

## Screenshots

![virtsupportwarning](https://user-images.githubusercontent.com/65038391/112313017-a5ba4b80-8c64-11eb-840c-54f28f6907be.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.1f1
- MRTK Version 2.6.1
- OpenXR
- No XR pipeline

## Target platform (please complete the following information)

- UWP
- Standalone

**Comment by keveleigh** [comment]
>without the XR SDK package imported into the project, the 'Virtual reality supported not enabled' warning is generated. This issue occurs when OpenXR is installed in a project

I'd like to understand more of what this means, since the OpenXR package is part of XR SDK. Which packages are you referring to by "XR SDK package"?

**Comment by elbuhofantasma** [comment]
> > without the XR SDK package imported into the project, the 'Virtual reality supported not enabled' warning is generated. This issue occurs when OpenXR is installed in a project
> 
> I'd like to understand more of what this means, since the OpenXR package is part of XR SDK. Which packages are you referring to by "XR SDK package"?

I am referring to two separate configurations in that quote. The issue happens in both configurations. I also updated the issue to clarify the separation. 

The first configuration is a new Unity 2020 LTS project > import MRTK .unitypackages > skip [XR SDK setup](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Documentation/GettingStartedWithMRTKAndXRSDK.md#configuring-unity-for-the-xr-sdk-pipeline) > run example scene with the in-editor player. 

The second configuration is a standard MRTK OpenXR project as defined in the [OpenXR Getting Started](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/openxr-getting-started) documentation.

**Comment by MaxWang-MS** [comment]
Will be fixed by #9652.
