### ISSUE TITLE
Profiles should be scenario based instead of platform based

### ISSUE THREAD

**Issue by polar-kev** [microsoft/MixedRealityToolkit-Unity#9548]
There is often confusion on which profile to use when creating an app for a device other than holoLens. By switching to a scenario based approach vs a platform based approach, we can avoid this confusion.

See #5426 for reference.

**Comment by RogPodge** [comment]
Will be closed as we move away from using the profile system in the newest MRTK. For now, we need to verify that our profiles cover the appropriate range of deployment scenarios.

**Comment by RogPodge** [comment]
Closing for 2.8 as the DefaultMixedRealityToolkitConfgurationProfile has been vetted for deployment for devices that support OpenXR.
