### ISSUE TITLE
ScrollingObjectCollection's clippedRenderers should be a HashSet

### ISSUE THREAD

**Issue by nuernber** [microsoft/MixedRealityToolkit-Unity#9553]
`clippedRenderers` is currently a `List`, which makes its `Contains()` calls take forever if you have a big object collection. Changing it to a `HashSet` makes things go much faster!

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/ca6f802b2107f3275feb34ddf083bd23d9a65b49/Assets/MRTK/SDK/Features/UX/Scripts/ScrollingObjectCollection/ScrollingObjectCollection.cs#L1679

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/ca6f802b2107f3275feb34ddf083bd23d9a65b49/Assets/MRTK/SDK/Features/UX/Scripts/ScrollingObjectCollection/ScrollingObjectCollection.cs#L1709

Note that your object collection doesn't have to be that large to see a performance penalty. For example, a list of 100 clipped objects, each with 10 renderers attached will cause 1000 calls to `Contains()` every frame... ouch!

**Comment by keveleigh** [comment]
Fixed visa #9813
