### ISSUE TITLE
Sanitize Speech string TextToSpeech functions.

### ISSUE THREAD

**Issue by acarabott** [Microsoft/MixedRealityToolkit-Unity#956]
This is probably caused by the underlying APIs, but is relevant here.

Calling `SpeakText("?")` causes a strange form of hang: the visuals freeze, audio continues but localisation stops. The app can be killed via the DevicePortal.

**Comment by StephenHodgson** [comment]
I don't think punctuation is supported with the speech APIs

**Comment by acarabott** [comment]
I see, thanks for clarifying  👍.

Might be worth having some defensive mechanism: warning, or stripping out the punctuation. Kind of a nasty thing to encounter, and not the most intuitive source of a bug.

**Comment by StephenHodgson** [comment]
Yeah I think sanitizing the string before passing to the API might be helpful.

**Comment by acarabott** [comment]
Just a note, that punctuation does seem to be supported. I have no issue with the string `hello?`

**Comment by StephenHodgson** [comment]
Thanks for the update. 

So what had happened before? Just the fact that it had punctuation and no word attached?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
