### ISSUE TITLE
Hard to figure out how to import samples when using MRFT/UPM

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#9577]
Currently it may be hard for someone new to UPM to figure out how to import the samples into the Assets folder even after importing the examples UPM package via Mixed Reality Feature Tool.

**Comment by keveleigh** [comment]
I think currently this is the only mention of importing examples from UPM in our docs: https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/configuration/usingupm#using-mixed-reality-toolkit-examples

**Comment by MaxWang-MS** [comment]
@keveleigh I have found a way to show the UPM window (with the example package in focus) via code and would propose to add a button or something to show it in the configurator (so that new users can easily import them). By the way, do you know how to tell whether MRTK is consumed via UPM or not besides using UPM API?

**Comment by keveleigh** [comment]
@MaxWang-MS Hmm...you should also be able to check something like (this should be runnable in any MRTK script that won't be copied to Assets even when consumed via UPM, that way it can always be assumed to be in the right place)

```c#
if (UnityEditor.AssetDatabase.TryGetGUIDAndLocalFileIdentifier(this, out string guid, out long _))
{
    string assetPath = UnityEditor.AssetDatabase.GUIDToAssetPath(guid);
    if (assetPath.StartsWith("Assets"))
    {
        // Assume it's non-UPM
    }
    else if (assetPath.StartsWith("Packages")) // GUIDToAssetPath returns an empty string if the GUID isn't found, so we probably want to either guard against that case above or explicitly check for both Assets and Packages
    {
        // Assume it's UPM
    }
}
```

I haven't tested this but logically it seems to make sense
