### ISSUE TITLE
MRTK Configurator needs to be improved

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#9578]
The configuration should be improved in the following aspects:
- Only show options that are relevant to the current Unity version (i.e. no Legacy XR related item on Unity 2020)
- Provide information about XR SDK and Legacy XR pipeline, check the current pipeline (if any) and ask the user to select one if none is currently used (we should provide an easy path for users not understanding the pipelines as well).

**Comment by keveleigh** [comment]
Related to #7513

**Comment by keveleigh** [comment]
Also might be a good time to look into https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7514 and verify that https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8846 and https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9547 are fixed.
