### ISSUE TITLE
Can't run SharingTest scene from HoloToolkit-Test on emulator

### ISSUE THREAD

**Issue by valthec** [Microsoft/MixedRealityToolkit-Unity#958]
I compiled the sample and put to my **HoloLens where is working fine**, but when I tried to do the same on emulator I got "Found anchor, ready to export" message and later I have hundreds of "Failed to upload anchor, trying again..." messages. 
![2017-09-11_164553](https://user-images.githubusercontent.com/12583808/30325890-cd3319a8-97c6-11e7-885b-0c7ae0b8d7ad.png)
I tried to debug ImportExportAnchorManager script and I found that problem is in ExportComplete method where there is a check for exportingAnchorBytes.Count. In my case it has always 310 bytes that that is too low for MinTrustworthySerializedAnchorDataSize (set to 100000). 
Anyone had similar issue? I didn't change anything on this project so it should work just OOTB. Am I missing something?
I was able to repro this on another machine both with Unity 5.6.3p2, HoloToolkit 1.5.7 and emulator v10.0.14393.1358. I tried many rooms but it always is 310.

**Comment by StephenHodgson** [comment]
Unsure if the emulator is supported.

**Comment by StephenHodgson** [comment]
Have you tried adding a room to the emulator to get more spatial mapping data?

**Comment by valthec** [comment]
Yes I did. I tried also with default rooms. Always same number. I tried also to connect my HoloLens first so it should download some WorldAnchor from server, but result was the same. 
Have you check "SharingTest" test project on Unity 2017? Is it working there?

**Comment by StephenHodgson** [comment]
I don't ever use the emulator, so I couldn't tell ya.

**Comment by valthec** [comment]
Lucky you! I don't have another HoloLens for my own :)

**Comment by StephenHodgson** [comment]
I updated the sharing services.  See if that helps at all.

**Comment by valthec** [comment]
Thanks Stephen! I had to re-create project as your changes were targeting Unity 2017.1. I did my test again and it is same story. It is working fine for HoloLens and not working for emulator. SharingTest project is different now and it is no longer using ImportExportAnchorManager script. Now Import/Export anchors is done in SharingWorldAnchorManager script. I managed do attached debugger and here is my result. 
![2017-09-13_142113](https://user-images.githubusercontent.com/12583808/30377396-e2b42d3e-988f-11e7-9820-c010b3468f21.png)
In green box there is successful try to save and export "AnchorVisual". That was fine. Anchor was saved and cached. In red box there is debug output about another anchor that was created but not exported. 
![2017-09-13_141942](https://user-images.githubusercontent.com/12583808/30377534-59b3e5aa-9890-11e7-9838-08cd47e0cd08.png)
As you can see upload data is too small to be exported. It is very similar to problem that I got with ImportExportAnchorManager script. 
Do you know what data is used to build anchors? I'm curious why it is so small.

**Comment by StephenHodgson** [comment]
Great details on the issue!

Yeah I'm unsure as to why the anchors are so small on the emulator.  My only suggestion (Shot in the dark) is to clear the spaces in the emulator (like you would the device) and see if that helps.

Seems like you're getting bad spatial data from the emulator.

**Comment by valthec** [comment]
I loaded DefaultRoom.xef file and clear Space that should remove all anchors but still is not working. I noticed that my emulator has no Internet access. Is Internet needed for WorldAnchors?
![2017-09-14_104050](https://user-images.githubusercontent.com/12583808/30420431-d89ca312-9939-11e7-9e2c-4a597958f27c.png)

**Comment by StephenHodgson** [comment]
As long as you can reach the sharing service server locally in your pc, you should be good.

Even then, really the only thing I can think of is just making the minimum size smaller just for the emulator.

**Comment by fraspadafora** [comment]
I have the same error but also in the Hololens. In my case the Anchor size is 0. Any news about this bug?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
