### ISSUE TITLE
Sometimes ending a Holographic Remoting session generates exceptions

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9586]
## Describe the bug

Sometimes when ending a Holographic Remoting session, one or more exceptions can be generated. This can happen with both XR SDK and OpenXR pipelines. I found this issue while quickly starting and stopping remoting sessions to switch between the Hand Menu Examples scene and the Hand Interaction Examples scene. The XR SDK pipeline has different exceptions that get thrown than the OpenXR pipeline. The warnings and exceptions are not always thrown when stopping a remoting session, there appears to be some sort of magic timing needed. This issue either does not happen in Unity 2019 LTS or is much more difficult to trigger than the Unity 2020 LTS.

## To reproduce

1. Create a new project, import the MRTK, and enable the XR SDK or OpenXR pipeline
2. Open either the Hand Interaction Examples scene or the Hand Menu Examples scene
3. Change to the 'DefaultHoloLens2XRSDKConfigurationProfile' for XR SDK or 'DefaultOpenXRConfigurationProfile' for OpenXR
3. Configure Holographic Remoting in Unity for your device
4. Press the 'Connect' button to connect to the device
5.  Press the 'Play' button to start the remoting session and wait for the scene to start rendering on device
6. Press the 'Play' button stop the remoting session.
7. Open the other scene that was not chosen in step 2
8. Press the 'Connect' button to connect to the device
9. Press the 'Play' button to start the remoting session and wait for the scene to start rendering on device
10. Press the 'Play' button stop the remoting session.
11. Check the Unity console for errors
12. If there are no unexpected behaviors, repeat these steps

## Screenshots
**XR SDK:**
![UWPXRSDKendremotesessionexceptions](https://user-images.githubusercontent.com/65038391/113085578-fd8d1100-9194-11eb-8092-81022457bb42.png)
![UWPXRSDKcamerawarning1](https://user-images.githubusercontent.com/65038391/113086087-d4b94b80-9195-11eb-8455-473bd7c59843.png)
![UWPXRSDKnullobjectreference1](https://user-images.githubusercontent.com/65038391/113086169-016d6300-9196-11eb-97b7-d3dd989e228a.png)
![UWPXRSDKnocamera2](https://user-images.githubusercontent.com/65038391/113086231-1cd86e00-9196-11eb-9917-222681635c7e.png)
![UWPXRSDKcamerawarning2](https://user-images.githubusercontent.com/65038391/113086295-3a0d3c80-9196-11eb-9f63-4ffa565f2aff.png)
![UWPXRSDKnullref2](https://user-images.githubusercontent.com/65038391/113086339-4b564900-9196-11eb-8478-cab9afa599a1.png)

**OpenXR:**
![OpenXRrefexception](https://user-images.githubusercontent.com/65038391/113086552-b0aa3a00-9196-11eb-92c4-54d3e0255990.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.2f1
- MRTK Version 2.6.1

## Target platform (please complete the following information)

- HoloLens 2
- UWP
- OpenXR
- XR SDK

**Comment by keveleigh** [comment]
Possibly related to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8459

**Comment by keveleigh** [comment]
Exceptions fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9868
