### ISSUE TITLE
Reading Mode functionality does not work when Holographic Remoting with XR SDK

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9587]
## Describe the bug

In the Reading Mode example scene while Holographic Remoting to HoloLens 2, the functionality of the Enable/Disable Reading Mode radial set and the Render Viewport Scale pinch slider is not effected by the manipulation of their respective control interfaces. This issue does not happen when running the example scene on device as a package.

The Enable/Disable Reading Mode radial set will change to the intended radial button when using near and far interaction, but the FOV will not change.

The Render Viewport Scale pinch slider does not change the amount of pixels being rendered on the device. The pinch slider prefab does move around as intended with near and far interaction.  

## To reproduce

1. Create a new project, import the MRTK, and enable the XR SDK pipeline
2. Open the Reading Mode example scene
3. Change the profile to "DefaultHoloLens2XRSDKConfigurationProfile" or "DefaultXRSDKConfigurationProfile"
4. Start a Holophraphic Remoting session for the Reading Mode example scene
5. Attempt to change the FOV or resolution using the radial buttons and pinch slider

## Your setup (please complete the following information)

- Unity Version 2020.3.2f1 2019.4.23f1
- MRTK Version 2.6.1

## Target platform (please complete the following information)

- HoloLens 2
- UWP
- XR SDK

**Comment by keveleigh** [comment]
This is expected. Holographic Remoting doesn't currently support the APIs required for this feature: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/holographic-remoting-troubleshooting#limitations

> The following APIs are currently not supported when using Holographic Remoting for HoloLens 2 and will raise an ERROR_NOT_SUPPORTED error unless otherwise stated:
> [...]
> HolographicCameraPose.OverrideProjectionTransform

**Comment by elbuhofantasma** [comment]
Awesome, I did not find that in the API area of the documentation. I am closing this issue since it is expected.
