### ISSUE TITLE
OpenXR Holographic Remoting apps can lose hand tracking when starting a session

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9591]
## Describe the bug

When Holographic Remoting with an OpenXR app, it is possible to lose hand tracking when starting a session. The GGV pointer/input starts by default when HoloLens 2 is not tracking any hands during the start of an app that uses XR SDK or OpenXR. 

 Normally when an app starts in this state and the device starts tracking hands again, the app will switch from the GGV pointer/input to the Hand Ray pointer/input. However when an OpenXR app starts a Holographic Remoting session and there are no hands currently being tracked by the device during the start of that remoting session, it can get stuck in the GGV interaction model. The user must stop the Holographic Remoting session and start a new session to get hand tracking to work in the app. When a remoting session is stuck on the GGV interaction model, sometimes the hand rays will show up but it is impossible to use far/near interaction to manipulate an example scene. It is possible to return to the Shell using the Home button in the Shell menu while stuck in the GGV input state.

## To reproduce

1. Create a new project, import the MRTK, and enable OpenXR
2. Open an example scene
3. Change the profile to 'DefaultOpenXRConfigurationProfile'
4. Configure Holographic Remoting in Unity for your device
5. Press the 'Connect' button to connect to the device
6. Press the 'Play' button to start the remoting session
7. While the editor is starting the remoting process, sit on your hands so that they are completely out of view of the device sensors
8. Wait for the device to fully render the example scene
9. Bring your hands completely into the device sensors' field of view
10. Attempt to use far interaction to manipulate the example scene
11. If the input method changes from GGV and allows manipulation with far interaction, then repeat steps 5-10 

## Your setup (please complete the following information)

- Unity Version 2020.3.2f1
- MRTK Version 2.6.1

## Target platform (please complete the following information)

- HoloLens 2
- UWP
- OpenXR

## Additional context

This issue does not occur 100% of repro attempts.

**Comment by keveleigh** [comment]
We've been tracking this bug on the OpenXR plug-in side, so I've marked this as "external" for the moment.

**Comment by keveleigh** [comment]
This _should_ be fixed on the runtime side (and has been for a while). But please reopen if you're still seeing this on recent runtimes and plugin versions!
