### ISSUE TITLE
XR SDK profiles contain 'Undefined' controllers in the Controller Visualiztion Definitions 

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9594]
## Describe the bug

When I was looking at the Controller Visualization Settings section in the inspector, I noticed that the 'Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityController' Controller Type is missing for the Windows Mixed Reality Controller [Left\Right] Hand. This issue only effects Unity 2020 and the below profiles.

Profiles effected:
1. DefaultHoloLens2XRSDKConfigurationProfile
2. DefaultXRSDKConfigurationProfile

## Screenshots

![undefinedcontrollers](https://user-images.githubusercontent.com/65038391/113139339-d60d6700-91db-11eb-9cd4-6738c32be7c7.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.2f1
- MRTK Version 2.6.1

## Target platform (please complete the following information)

- UWP
- XR SDK

## Additional context

This issue might be related to #9586

**Comment by keveleigh** [comment]
This is fixed in 2.7.0-preview.1 via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9550. I updated the profiles to reference the correct controllers.
