### ISSUE TITLE
Visual profiler moves out of view while taking screenshot or recording video on the HoloLens 2.

### ISSUE THREAD

**Issue by agzimmerman** [microsoft/MixedRealityToolkit-Unity#9596]
## Describe the bug

The [visual profiler](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/diagnostics/using-visual-profiler) does not appear while taking screenshots or recording videos on the HoloLens 2.

## To reproduce

1. Start any app that shows MRTK's visual profiler.
2. Use the HoloLens main menu to take a screenshot. The Visual Profiler disappears, the screenshot is taken, and then it reappears. The same occurs when recording (again via the main menu).

## Expected behavior

Whether or not the visual profiler is shown should be independent of the system recording state.

## Screenshots

In this screenshot, taken via the HoloLens main menu, I used my index fingers and thumbs to frame the visual profiler that I could see before and after the screenshot was taken. I was running the ~Examples Hub~ hand interactions demo from this repo.

![20210331_163819_HoloLens](https://user-images.githubusercontent.com/9367569/113162902-f707a380-923f-11eb-9b42-d9fa3b5d63d9.jpg)

## Your setup (please complete the following information)

- Unity Version 2019.4.23f1 LTS 
- MRTK Version 2.6.1 (actually the releases/2.6.1 branch of this repo) 

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

For my work it would be useful to regularly include the visual profiler in the video recordings that I am making anyway (e.g. for feature demonstration purposes), so that I can better investigate performance regressions without having to manually write down a small subset of the performance data.

I have experienced this same issue with two different HoloLens 2 devices on multiple Unity projects using multiple versions of Unity (including 2019.4 LTS and 2020.3 LTS). I have yet to see any example of a video recording including the diagnostics profiler. 

Perhaps related: The visual profiler also does not appear when running in Play Mode in the Unity editor.

**Comment by agzimmerman** [comment]
After gathering all of the information above and taking a screenshot for the second time, I saw the "Show Profiler During MRC"  option in MRTK configuration settings in the Inspector:
![image](https://user-images.githubusercontent.com/9367569/113163975-f7546e80-9240-11eb-80b6-fa43cec099e5.png)
By default the option is disabled. If I understand the option correctly, then I think it would lead to what I am observing.

Then I quickly found #7369 where, if I understand correctly, the behavior I am experiencing was explicitly desired and then implemented in #7370. 

So, I enabled the option (as shown in the screenshot) and built again, and took another screenshot, which gave the same result. Anyway, maybe this helps provide more context. Also if it turns out that the option was supposed to suppress the behavior I'm observing and if someone confirms that it works on a recent version of Unity MRTK, then I can try it again.

**Comment by agzimmerman** [comment]
@keveleigh , FYI, I just noticed I had only changed the MRTK configuration in the examples hub scene, not in the hand interactions scene, so I'll test the MRC option again.

**Comment by agzimmerman** [comment]
Update: Now I've I enabled the option properly in the scene I was building. The visual profiler no longer disappears. Instead, it moves closer to me, almost out of view, and then goes back to the original position when recording (screenshot or video) is over. But it does show up in this screenshot:
![20210331_174755_HoloLens](https://user-images.githubusercontent.com/9367569/113173411-a301bc80-9249-11eb-8252-21612220a492.jpg)

**Comment by keveleigh** [comment]
> Instead, it moves closer to me, almost out of view, and then goes back to the original position when recording (screenshot or video) is over.

Hmm...I think it uses some camera resolution/frustum data for placement. The changes during MRC must be messing with it...I'll take a look
