### ISSUE TITLE
Plan of Record: MRTK v3.0 requires Unity 2020.3

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#9597]
Given the planned release timeline (estimate: end of 2021), the team has determined that Unity 2020.3 LTS will be the minimum supported version for MRTK v3.

This brings several benefits:

- Longer lifetime of Unity LTS support (2020.3 will be ~6 months into it's support window)
- Support for OpenXR!

Running total (as of 4/20/2021 ~10am PDT)

- 2020.3: 13
- 2019.4: 1

Reasons (from the community):
- 2020.3
  - OpenXR support
  - Major MRTK upgrade is a good time to change
  - Important Unity milestone, breaking changes and new concepts
  - Keeping 2019.4 will add mainentance overhead
  - By EOY 2021, 2019.4 will be nearing end of support (~6mos?)
  - Reduced support matrix gives more time for stability/reliability
- 2019.4
  - OpenXR only supports ARM64
  - Some packages do not support ARM64 (ex: webrtc) / tracking unity & MRTK version matrix is challenging

**Comment by vbandi** [comment]
End of 2021 means that support for 2019 LTS will be running out in a few months anyway. Also, it is usually quite troublesome to find a working combination of Unity + MRTK + XR framework + Device OS, so the more variables can be removed from this, the better. Especially if limiting supported Unity versions mean that the team has more bandwidth to focus on stability and reliability.

**Comment by davidkline-ms** [comment]
From holodevelopers.slack.com

Sahil Mayenkar  5 hours ago
I think this makes sense, and I'm in support of having 2020.3 LTS be the minimum version. Another thing that this could allow is dropping  Windows XR plugin support and having OpenXR plugin be mandatory for MRTK v3 HoloLens and WMR apps. There could be benefits in having everyone on the same platform, and it might be simpler for new developers to choose a single hololens 2 config profile rather than choose between an xrsdk version and an openxr version.
I get that this suggestion could be controversial, but at the same time, if OpenXR is eventually going to become the only supported Unity backend anyway for HL2/WMR in later Unity versions (as described here), then having a major MRTK upgrade like this is the perfect opportunity to make the leap. This is especially true when the lowest supported editor version (2020.3) supports OpenXR so there's no reason to maintain support for the older Windows XR plugin for the many years in the future.  And anyone who really needs Windows XR plugin (can't think of a reason why for HL2/WMR), then they could continue developing with MRTK v2.x

**Comment by davidkline-ms** [comment]
From holodevelopers.slack.com

Dino Fejzagić:speech_balloon:  7 hours ago
The 2020.X series is an important milestone where Unity introduced some breaking changes / new concepts. So keeping 2019.4 support from here will definitely add some unnecessary overhead and maintenance effort.

Adam Hill  2 hours ago
I am fine with 2020.3 LTS as being a minimum requirement.

**Comment by davidkline-ms** [comment]
More from slack

Glen Kingston  < 1 minute ago
The webrtc package supports ARM (NOT ARM64) and OpenXR only supports ARM64.  Right now trying to juggle which versions of different packages work with which versions of unity and which versions of MRTK is a mess.  Can this get resolved before trying to force everyone to OpenXR?  Seems like it's already happening which just results in people having to stay on old versions of Unity.

**Comment by studentutu** [comment]
Please take a look at the  Azure Spatial Anchors sample https://github.com/Azure/azure-spatial-anchors-samples   for MRTK - it is not yet ported to use new XR Management Subsystems system (it uses obsolete XR Management)

**Comment by studentutu** [comment]
@vbandi @davidkline-ms  also, as some of the features do need to use Nuget packages (Like QR Code scanning feature)  it would be nice if MRTK included some sort of pre-execution checks /service that will allow assembly classes to be called on the editor start  (check for Nuget packages - as NugetForUnity deletes them on the first start and you need to manually/restart unity to resolve packages )

**Comment by davidkline-ms** [comment]
@studentutu, can you open a separate feature request for

> as some of the features do need to use Nuget packages (Like QR Code scanning feature) it would be nice if MRTK included some sort of pre-execution checks /service that will allow assembly classes to be called on the editor start (check for Nuget packages - as NugetForUnity deletes them on the first start and you need to manually/restart unity to resolve packages )

**Comment by ltwlf** [comment]
Totally agree. Unity 2020 should be minimum. With OpenXR as the new standard this is necessary.

**Comment by studentutu** [comment]
@davidkline-ms @vbandi @ltwlf @gabriele  also, please update the Microsoft WebRTC package to use the newest XR Management System for Mixed Reality Capture feature (currently it uses obsolete XR Management and does not work with MRTK v2.6.1 and further on XR Management). I've already raised it in there - but just to make sure all the teams are aware of the consequences - https://github.com/microsoft/MixedReality-WebRTC/issues/742

**Comment by davidkline-ms** [comment]
I will make sure the WebRTC team is aware of the issues. Thanks @studentutu!

**Comment by davidkline-ms** [comment]
This has been completed.
