### ISSUE TITLE
Proposal: Bring in MixedRealityCommander like functionality into the MRTK Build Window

### ISSUE THREAD

**Issue by david-c-kline** [microsoft/MixedRealityToolkit-Unity#9598]
The Mixed Reality Companion Kit's [MixedRealityCommander](https://github.com/microsoft/MixedRealityCompanionKit/tree/master/HoloLensCommander) app has a UI that may help make the build window a bit more intuitive.

We should consider merging some of the concepts into the build window.

![image](https://user-images.githubusercontent.com/13281406/113185815-c574e500-920b-11eb-8c50-2ec70d650891.png)

**Comment by davidkline-ms** [comment]
Let's do a gap analysis of what the build window can do now vs what is missing. Another question is whether or not a ui refresh is valuable to customers here.

**Comment by davidkline-ms** [comment]
Closing as stale. The form of the build window for MRTK3 is being discussed separately.

**Comment by keveleigh** [comment]
> Closing as stale. The form of the build window for MRTK3 is being discussed separately.

I'm going to reopen this one, as it's already in the MRTK3 milestone and can be used to track this specific feature as part of the separate discussion.

**Comment by AMollis** [comment]
We won't be bringing a build window to the MRTK3 in the near future.  We found the existing build window in Unity is good enough to build and deploy to HoloLens.

If a build window is desired, such a system would make more sense outside of the MRTK project in its own repository, similar to https://github.com/microsoft/VisualProfiler-Unity
