### ISSUE TITLE
MRTK Scene System does not work well for VR

### ISSUE THREAD

**Issue by polar-kev** [microsoft/MixedRealityToolkit-Unity#9600]
We're using MRTK2.6 in a Oculus Quest project, together with the MRTK scene system. I thought I just leave my 2 cents here, just some thoughts on the scene system and Vr development. 

It seems that the MRTK Scene System is designed with HoloLens in mind, which has some implications for VR. 

The main problem is lighting and active scene behaviour: by default MRTK proposes to use a separate scene with some default lights which becomes the "active" active scene (there can only be one active scene at the time in Unity, this scene is responsible for not only lighting but also the background and other properties such as fog I believe). 
This is a very strange workflow for general game development, because normally you include lighting and background in your game scene, not separately. 

One can disable this behaviour in MRTK so that there is no separate "lighting scene", but then the ManagerScene (or the scene containing the MRTK object) remains the active scene, thus still overriding the game scenes lighting and other things. This is a not optimal for VR dev.

Our workaround has been very simple though. We include this snippet of code in every "game scene". So far there seem to be no side effects but what worries me is that the active scene is also used for new GameObjects instantiated by scripts, [according to the unity docs](https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.SetActiveScene.html). So this could potentially backfire for us later =) 

```
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Assets.Scripts.Core
{
	public class SetActiveScene : MonoBehaviour
	{
		void Start()
		{	
			SceneManager.SetActiveScene(gameObject.scene);
#if DEBUG
			Debug.Log($"Set {gameObject.scene.name} as active scene");
#endif
		}
	}
}
```

But I think it would be good to reconsider how the MRTK scene manager works to make MRTK a bit more logical for VR projects.

_Originally posted by @jelmerS2 in https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/9509_

**Comment by davidkline-ms** [comment]
We are looking for feedback on the following questions:

* Should MRTK v3 remove the scene system from the product?
* If no, how can it be made better?

Thanks!

**Comment by lilfish** [comment]
> 
> 
> We are looking for feedback on the following questions:
> 
>     * Should MRTK v3 remove the scene system from the product?
> 
>     * If no, how can it be made better?
> 
> 
> Thanks!

I am currently working a lot with the MRTK scene system on various small projects. There are sometimes issues when switching between projects where the profiles act weird. Though I have to admit that I have not yet used the light scenes.

I think the scene system is quite nice and should stay in MRTK. It gives the project a nice fade animation and the switching scene options (prevScene, nextScene) are also nice to use. But there should be more documentation on how to set it up, especially for the profiles.
