### ISSUE TITLE
Graduate Step Slider from Experiemental

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#9602]
Graduate Step Slider from Experimental

Captures these sub issues:
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9401
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8881

**Comment by keveleigh** [comment]
@RogPodge Not sure if these are directly related to the step slider (one mentions "ticks", but it could just be the pinch slider), but wanted to call these two issues out as well in case they're in scope for the graduation:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9172
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9365

**Comment by RogPodge** [comment]
I'll try to get fixes for those in as well 💯
