### ISSUE TITLE
Adding WMR plugin after the Oculus Integration Package generates shader warnings

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9607]
## Describe the bug

Adding WMR plugin after the Oculus Integration Package generates the shader warnings that are found in the screenshot below. It looks like most of them are related to the Oculus provided assets. 

## To reproduce

1. Create a new project and switch the platform to Android
2. Import the MRTK .unitypackages
3. Import the XR Plugin Manager
![Screenshot 2021-03-31 170430](https://user-images.githubusercontent.com/65038391/113225816-70ed5c00-9243-11eb-99b4-a292602a0283.png)
4. Check the Oculus box in the Plug-ins Providers pane
![Screenshot 2021-03-31 170536](https://user-images.githubusercontent.com/65038391/113225870-924e4800-9243-11eb-9e1f-b93f9a98ec74.png)
5. Import the Oculus Integration Package and let it restart the editor
6. Return to the XR Plugin Management page and choose the Windows tab
![Screenshot 2021-03-31 170851](https://user-images.githubusercontent.com/65038391/113225932-c7f33100-9243-11eb-8d05-4a1a7e48127e.png)
7. Check the Windows Mixed Reality box in the Plugin Providers pane
![Screenshot 2021-03-31 171015](https://user-images.githubusercontent.com/65038391/113226040-04269180-9244-11eb-9c0e-dc6794d5d8b9.png)
8. See generated warnings in the Console

## Warnings

![Screenshot 2021-03-31 171314](https://user-images.githubusercontent.com/65038391/113226190-65e6fb80-9244-11eb-803c-a22a30c13aaa.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.2f1
- MRTK Version 2.6.1

## Target platform (please complete the following information)

-

**Comment by keveleigh** [comment]
I'm going to mark this as External. If we want to report this to Oculus and track it ourselves, we can leave this open. If nobody's going to do that, we may as well close this down as there's nothing we can do to fix this ourselves.

**Comment by keveleigh** [comment]
Going to close this out as External (and it may be fixed!)
