### ISSUE TITLE
How to setup uGUI for toolkit

### ISSUE THREAD

**Issue by shllybkwrm** [Microsoft/MixedRealityToolkit-Unity#961]
Barring whether or not using Unity UI is a _good_ idea... I had previously used sliders and buttons in my HoloLens app and they worked for the most part (slider dragging did not).  Now I'm trying to port over a more complex version of the Android app, and the UI elements are completely unresponsive to taps or gaze.

I have already followed [the UI setup steps from the Unity forums](https://forum.unity.com/threads/unity-ui-on-the-hololens.394629/).  Anything else I should be doing?

**Comment by StephenHodgson** [comment]
Those steps from the forum are not reflective of the requirements for the toolkit.

uGUI should work fine with the normal events via the toolkit's `InputManager`.

See [Getting Started](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/GettingStarted.md#4-preparing-a-scene-for-holographic-content) for a simple setup of the input system in your scene.

**Comment by shllybkwrm** [comment]
I did previously follow all the steps from Getting Started.  However, I just experimented with making the interface smaller and closer to the user, and that seems to have fixed some of my issues (sliders, buttons, and dropdown menus are working).  Checkboxes, however, are not staying checked - the check appears after click and disappears immediately.  Any ideas about that?

Also, I believe that some of the steps from the forum do need to be followed.  Leaving the Canvas in Render Mode:  Screen Space - Overlay does not show the UI at all.  Render Mode:  Screen Space - Camera shows the interface, but it is unusably tiny and the canvas size can't be adjusted in that mode.

**Comment by shllybkwrm** [comment]
No idea what changed (I'm just adjusting the interface size and spacing at this point), but the checkboxes seem to be working now.  I'll test some more and see if that holds.
One more thing that isn't working is the highlight color and pressed color on the buttons.  It works on the slider buttons, however.

**Comment by StephenHodgson** [comment]
Check out the [InputManagerTest.unity](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Tests/Input/Scenes/InputManagerTest.unity) scene.  It has button highlighting and presses.

**Comment by shllybkwrm** [comment]
Question, what is the recommended way of developing your UI in Unity?  It's not visible with the canvas in Render Mode:  World Space, and when you switch back from another mode you need to input all the transform settings again.

**Comment by shllybkwrm** [comment]
After a lot of testing, I think the original issue was that the interface was both too far in the distance and too small to allow proper interactions.  I've basically fixed everything except the checkbox issue.  Basically, if I keep my gaze on the checkbox while clicking, my air tap is registered twice.  If I move the gaze cursor slightly off the box while clicking, the tap only goes through once as expected.  Can anyone else recreate this?  I can post a video of the bug if needed.

**Comment by StephenHodgson** [comment]
Updated Input Manger now properly catches all the used events before sending them.

Should have fixed that issue you're having there.

I believe the only thing that isn't properly implemented for uGUI is scrolling.
