### ISSUE TITLE
MinMaxScaleConstraint should have a mode for non-uniform clamping.

### ISSUE THREAD

**Issue by elenzil** [microsoft/MixedRealityToolkit-Unity#9610]
## Describe the problem

This behavior in the MinMaxScaleConstraint makes sense as a default:
[The returned vector's direction will be the same as the given vector](https://docs.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.toolkit.ui.minmaxscaleconstraint?view=mixed-reality-toolkit-unity-2020-dotnet-2.6.0)

but it would be nice to have an option where each axis could be constrained independently.

ie, either a separate min/max for each axis, or the same single value for all three but with an option to clamp each one independently.

**Comment by Zee2** [comment]
Done in MRTK3. Reopen if a backport to MRTK2 is desirable.
