### ISSUE TITLE
Feedback requested: Granularization of MRTK v3 packages

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#9612]
As of MRTK 2.6, there are six core MRTK packages (plus three feature **addons).**

The core six are:
- Standard assets
- Foundation
- Extensions
- Tools
- Test utilities
- Examples

For version 3, we are investigating how these packages should be granularized,.

**Why?**
The team has heard from a number of customers that MRTK's packages are too large and that there is a desire for a more ala carte consumption. A common theme in this feedback is "our application does not use feature a at all. including it in the package makes our distribution unnecessarily larger."

There are two proposed approaches: Feature and Scenario. In both of these scenarios, it is planned to maintain "bundles" which recreate the current set, to make upgrades easy and to allow developers to maintain the current workflow.

**Feature**
Feature granularization takes the form of a core package and individual packages for each feature (boundary system, user experience controls, etc.) and platform (ex: windowsmr, oculus, etc.).

Estimated package count (excluding bundles): 23

Pro:
- Greatest degree of granularity
- Include ONLY the specific features that are desired
- Smallest package size

Con:
- Results in a very large increase in package count
- Related features are separated
- More work to add functionality (try to implement, discover feature not installed, download/install, implement code, ...)

Examples:
- com.microsoft.mrtk.boundary
- com.microsoft.mrtk.spatialawareness

**Scenario**
Scenario granularization is one level higher than feature in that it bundles related functionality (ex: boundary and spatial awareness) together. The core and platform packages are the same as with feature granularization.

Estimated package count (excluding bundles): 19 (or fewer)

Pro:
- Easy selection of packages (ex: "our application will interact with the [real|virtual] world")
- Related features are packaged together
- Smaller increase in package count

Con:
- Unused features (ex: boundary in an AR experience) remain in the application distribution

Examples:
- com.microsoft.mrtk.environment (boundary,  spatial awareness & tracking lost systems)
- com.microsoft.mrtk.physics (hand physics service & future physics related features)

Please leave preference and feedback in the comments. Thanks!

**Comment by machenmusik** [comment]
Not mentioned in the description:
- Whose responsibility will it be to identify the handful of the most common combinations of functionality?
- Whose responsibility will it be to ensure that the various permutations of possible packages function properly/as desired?
I defer to the implementation team of course, but I have some concern although automated tests for each individual package may be improved, a sudden explosion of possible permutations and combinations that now require integrated testing may completely destroy any feature velocity the project may have.
My personal suggestion would be to identify a reasonably small number of combinations, ideally the most commonly used in practice, for which the implementation team prioritizes direct and timely support/response.
If the pieces are also available a la carte with known boundaries for more determined developers / organizations to customize/optimize, great.

**Comment by davidkline-ms** [comment]
Thanks @machenmusik! The MRTK team would take a first pass to propose the scenario packages. We will definitely solicit community feedback to finalize the set.

**Comment by eusebiu** [comment]
One level might be based on providers/target platform - e.g. OpenVR, Oculus, WindowsMR, LeapMotion - and then system based - e.g. Boundary, Teleportation, Spatial Awareness, Scene System.

In general Unity projects, the size comes from the assets, not from the code, so I think this can easily be solved by just excluding the folders the developer does not want using the ~ (indeed, this is possible if one imports MRTK as an unitypackage) - I use this Unity feature when I build an app for Oculus vs. SteamVR or mobile/Android vs. Desktop. 
![image](https://user-images.githubusercontent.com/414589/113484497-4274b880-94b1-11eb-839e-7bc60621d7b3.png)

Honestly, I don't see this capability of MRTK - i.e. granularity of features - extremely important as the code impact on size is quite small.

**Comment by davidkline-ms** [comment]
Interesting idea @eusebiu! Thanks!

**Comment by adamhill** [comment]
Is there any way we could get a rough size for each component in the current granularization & the two proposals? 

And since it is probably the most restrictive deployment — Would Hololens apps share same versioned runtime components or would thy all be linked (and stripped potentially) into / out of the APK?

**Comment by davidkline-ms** [comment]
For v2.6.1, the current package sizes are approximately

- Standard Assets : 4.5MB
- Foundation: 8.4MB
- Extensions: 1.1MB
- Tools: 2.0MB
- Test Utilities: 16KB
- Examples: 53MB

I haven't done the math on the proposals, yet. I anticipate Tools and Test Utilities to be pretty much unchanged.

**Comment by adamhill** [comment]
Roughly 15.1MB total excluding samples.

15.1 M / 19 or 15.1 M / 23 ~= 795K vs 652K per package

So the size savings are really that important go customers? Why? Don't un-referenced bits get stripped by the linker anyway?

Could this be done invisibly via more granular namespaces to give the linker an "easier" decsion path for stripping? Or do I completely misunderstand how mobile stripping works? (All my knowledge comes from Xamarin at the moment)

**Comment by eusebiu** [comment]
It is less than than because those packages are the actual code and assets. The compiled version of MRTK is ~2.4 MB.
![image](https://user-images.githubusercontent.com/414589/113564799-a19e0e80-9612-11eb-8a84-97bee8e9a64b.png)

**Comment by ThomasMountainborn** [comment]
I would personally weigh in against further granularization. In my experience, it just makes setting up a project more of a hassle, and maintenance from your end more difficult. With every new feature, it will be a question of which package it should end up in. Or it might even require a new package altogether because it doesn't quite fit in with the current ones. As eusebio highlights above, the actual file size is negligible. Why make things more complicated for no actual gains?

**Comment by davidkline-ms** [comment]
This is a great discussion. Please keep it going!
