### ISSUE TITLE
MRTK 2.6.1 OpenXR Spatial Awareness Does Not Function In HoloLens 2

### ISSUE THREAD

**Issue by laultman** [microsoft/MixedRealityToolkit-Unity#9619]
## Describe the bug

HoloLens 2 app often depend on the environment. OpenXR in Unity 2020.2.7 and higher (not tested lower versions of 2020) will not display the mesh nor will the occlusion work. It is as if it is not enabled. Verified spatial perception is enable in project, that Spatial Awareness is enable in the MRTK.  Followed the MS docs [here](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=winxr) multiple times to ensure that the service is in fact not functioning.

## To reproduce

1. Start an new project in Unity using version 2020.2.7 or higher.
2. Follow the instructions for Unity 2020 exactly as detailed in the [documentation](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=winxr). (Note: in the documentation it asks you to use the 2.7 version of MRTK which was not available in my release and I am using the very latest Feature Tool as of 4/3/2021.)
3. Do not modify any of the settings other than those detailed in the tutorial.
4. Build in Unity.
5. Build in Visual Studio 2019 16.9.3
6. Deploy to HoloLens 2 (current updates as of 3/30/2021)
7. Run app and observe that there is no mesh displayed nor does the cube respect physical object (walls etc.)

## Expected behavior

In prior version of Unity 2019.4.x using the same documentation for Unity 2019.4 the scene mesh is displayed and the cube is occluded by the physical environment (walls etc.)  I expect the same behavior in Unity 2020.2 and higher using the OpenXR as is the recommended tooling.

## Screenshots

None

## Your setup (please complete the following information)

- Unity Version 2019.4.x with MRTK Version 2.5.4 configured with XR plugin (success)
- Unity Version 2020.2.7 + with MRTK Version 2.6.1 configured for OpenXR (fail)
- 
## Target platform (please complete the following information)
- HoloLens 2

## Additional context
More detail is found in #9618

**Comment by keveleigh** [comment]
Yes, spatial awareness with OpenXR was not supported in the MRTK 2.6.1 release. This work was tracked by https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9491 and added to the 2.7.0 release by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9567. It's present in the 2.7.0 preview, which you can download via the feature tool if you enable previews in the settings.

**Comment by laultman** [comment]
@keveleigh Thanks, I am fine with closing this ticket. However, In response to email from Kurtis "Yes, spatial awareness with OpenXR was not supported in the MRTK 2.6.1 release. This work was tracked by #9491 and added to the 2.7.0 release by #9567. It's present in the 2.7.0 preview, which you can download via the feature tool if you enable previews in the settings."

As I noted in my discussion in the current version of the Feature Tools the 2.7.x features are NOT available even with the preview enabled.

**Comment by keveleigh** [comment]
>As I noted in my discussion in the current version of the Feature Tools the 2.7.x features are NOT available even with the preview enabled.

After enabling previews, did you click the refresh button on the package list page?

**Comment by laultman** [comment]
I enabled them from the beginning as it was detailed in the documentation. They were never present at any time.

**Comment by keveleigh** [comment]
Have you tried clicking the refresh button to resolve this issue? I just checked the preview box, clicked refresh, and could see the preview packages:

![image](https://user-images.githubusercontent.com/3580640/113642110-f1d99880-9633-11eb-8abf-8259323c916c.png)

**Comment by laultman** [comment]
Honestly, no. Did not know a refresh button existed and there was no instruction to use it. But I will on my next try. :)

**Comment by laultman** [comment]
@keveleigh  Found the refresh button. It is available after you get to the Discover Features step. Works as you describe. Would have been easy if there had been a Note in the documentation about this as there is absolutely no hint of it in the docs so how would anybody know. My expectation is I think, fairly normal, check the box and the action happens.

**Comment by davidkline-ms** [comment]
Beyond the basic flow described on the welcome page, each step is documented on a dedicated page. 

Ex: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/discovering-features#refresh-the-feature-catalog
