### ISSUE TITLE
Pre-execution checks / validation service + custom execution check/validation of Nuget Package

### ISSUE THREAD

**Issue by studentutu** [microsoft/MixedRealityToolkit-Unity#9622]
## Describe the problem

Some of the features do need to use Nuget packages (Like QR Code scanning feature) it would be nice if MRTK included some sort of pre-execution checks /service that will allow assembly classes to be called on the editor start (check for Nuget packages - as NugetForUnity deletes them on the first start and you need to manually/restart unity to resolve packages )

Solution: 
Just another service with extensions (static initializer with [InitializeOnLoad]) + wrappers to make extension methods/custom checks easier to add.

UnityEditor callbacks also have on post-processing assets/on compile callbacks I'm not sure which of them is the best way to implement such service.

**Comment by keveleigh** [comment]
We've been working on migrating our NuGet packages to UPM, accessible via the MR Feature Tool. Does this make this scenario better? I'm not fully sure what you're describing here, unfortunately.

**Comment by studentutu** [comment]
It would still be nicer to have this option for older packages
