### ISSUE TITLE
MRTK MS Docs - polish & improvements

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#9627]
Layout, images, etc.

Update - Button Docs:
https://github.com/MicrosoftDocs/mixed-reality-pr/pull/2914

**Comment by RogPodge** [comment]
Thanks for the work Yoon! Can you make sure to keep this updated with the changes you add to the mixed-reality-pr repo?

**Comment by polar-kev** [comment]
Closing since the referenced PR has been merged.
MicrosoftDocs/mixed-reality-pr#2914
