### ISSUE TITLE
IsEnabled value is null in WindowsMixedRealityDeviceManager 

### ISSUE THREAD

**Issue by amitsheokand** [microsoft/MixedRealityToolkit-Unity#9636]
## Describe the bug

I created a brand new Unity project following the documentation [here ](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=openxr) using Unity versions 2019.4.23 with MR Feature Tool v1.0.2103.3 Beta. After setting MRTK configuration profile to "DefaultXRSDKConfigurationProfile" in Playmode it throws following error

"Microsoft.MixedReality.Toolkit.XRSDK.WindowsMixedReality.WindowsMixedRealityDeviceManager has not set a value for IsEnabled, returning false."

## To reproduce

1. Create a new project using following  [guide](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=openxr)
2. import MRTK
3. setting MRTK configuration profile to "DefaultXRSDKConfigurationProfile" 
4. Hit play

## Expected behavior

There should be no null error.

## Screenshots
![image](https://user-images.githubusercontent.com/8472545/114009295-a49e3680-9880-11eb-8573-0040ffc1bc91.png)

## Your setup (please complete the following information)

- Unity 2019.4.23f1
- MRTK 2.6.1

## Target platform (please complete the following information)

- HoloLens 2
- Hololens 2 Emulator

**Comment by keveleigh** [comment]
This should be fixed in the 2.7.0-preview.2 release via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9521. It seems like the underlying cause is a weird state where Unity's settings object isn't accessible. It might be good to re-open the XR Plugin Management view in Project Settings and enable/disable the provider to try to get things properly serialized as a workaround if you can't update.

**Comment by keveleigh** [comment]
Closing as fixed, but happy to continue to conversation here!

**Comment by Jasperouz** [comment]
I have MRTK 2.7.0 but still get the same error.

**Comment by keveleigh** [comment]
@Jasperouz Any chance there's an exception before the `IsEnabled` errors in your console?

**Comment by Jasperouz** [comment]
Yes, I receive a _FileNotFoundException: Failed to load "vcruntime140_app.dll". Please ensure that "Microsoft Visual C++ 2015-2019 Redistributable" is installed_ exception maybe thats the reason why.

**Comment by keveleigh** [comment]
Yep, that'll be it! Do you happen to have the Mixed Reality Input package installed?

**Comment by SergoMar** [comment]
@keveleigh Hi, I have exactly this issue, using MR Input from Feature tool for HP Reverb 2 Motion Controllers. As the A, B, X, Y buttons don't work, I thought this library (https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/unity-reverb-g2-controllers) would help and not break the existing functionality. I have downloaded that vcruntime140_app.dll but still IsEnabled error is there both for WMR and Oculus sdk. Is there a workaround for that? Thanks.
