### ISSUE TITLE
How to identify whether the left hand or the right hand is operating

### ISSUE THREAD

**Issue by zxzkf1992** [microsoft/MixedRealityToolkit-Unity#9641]
## Describe the problem
In MRTK 2.6, is it possible to identify whether it is a left-hand click operation or a right-hand click operation?
I want to grab objects with both hands in HoloLens 2 at the same time, and obtain the data of the objects separately.

**Comment by keveleigh** [comment]
> I want to grab objects with both hands in HoloLens 2 at the same time

Are you using an MRTK component for this or looking for how to get this info from MRTK events?
