### ISSUE TITLE
Windows XR Plugin change to auto-enable remoting breaks projects

### ISSUE THREAD

**Issue by derzorngottes** [microsoft/MixedRealityToolkit-Unity#9642]
## Describe the bug

The recent update of the Windows XR Plugin package in Unity to 4.4.2 brought in a change that makes the Holographic Remoting feature automatic and tied to the play mode enter/exit. HOWEVER because it takes a couple of seconds to establish the connection some of the settings in my project which assign input connections think that there is no headset connected and instead go into alternate input mode. This totally blocks development.

Because the remoting connection will always lag, I strongly recommend changing this back or making it optional.

## To reproduce

Have a mixed reality project in Unity that is configured for Hololens. Have a script that does input assignment in Awake/Start. Have Holographic remoting enabled w/the 4.4.2 plugin. See that the connection takes too long and the input settings are not correctly applied.

## Expected behavior

The Unity app waits for the remote connection to succeed or fail before running the rest of the Awake/Start calls, or preferably, the old option to connect in the editor is brought back.

## Screenshots

N/A

## Your setup (please complete the following information)

- Unity Version 2020.3.2
- Windows XR Plugin 4.4.2
- MRTK package versions are all 2.5.0

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

I really hope this can be rolled back - it would be a huge pain to have to refactor around this change. Thank you!

**Comment by keveleigh** [comment]
Please file a Unity bug and/or report this on the Unity forums! This package isn't something we publish but it handled by Unity.

**Comment by javdavalos** [comment]
This is a huge problem, same thing with unity 2019.4.24f and XR plugin 2.7

Except in my case it's worse, it doesn't even try to auto connect. it fails complaining it can't find some windowsmrremotesettings.asset file and erases the machine name i enter, then says: "Atempting to initiate remoting connection with no valid machine name set."

I notice the XR plugin has an optional sample scene, where it does the connection manually when I press the C key?. why would I want to do that?.

**Comment by keveleigh** [comment]
@javdavalos Can you file a Unity issue from that project please (or another min repro project where you hit this case)? I haven't been able to repro this, so it'd be good to give Unity a project in this broken state.

**Comment by javdavalos** [comment]
> @javdavalos Can you file a Unity issue from that project please (or another min repro project where you hit this case)? I haven't been able to repro this, so it'd be good to give Unity a project in this broken state.

I'm afraid i don't have time for that. But it happened even on a clean project for me.

When you hit play, it fails to find the file: UserSettings/WindowsMRRemoteSettings.asset the ip address i entered is cleared and then it fails with
"Atempting to initiate remoting connection with no valid machine name set."

**Comment by javdavalos** [comment]
I found  a workaround for Unity not connecting to the remoting player. Just create a folder named UserSettings on your project and it will start working.

**Comment by javdavalos** [comment]
I tried the XR plugin on our main project, i create the usersettings folder, it connects after i hit play but it just shows a black screen.

The unity editor does see my hands though, it's just that the video is not transmitted to the headset.

**Comment by keveleigh** [comment]
>it connects after i hit play but it just shows a black screen.
>
>The unity editor does see my hands though, it's just that the video is not transmitted to the headset.

This sounds like the issue where you need to enable Windows Mixed Reality under the Standalone settings for remoting, since the editor itself is a Win32 app (vs UWP).

![image](https://user-images.githubusercontent.com/3580640/114749024-5917dc80-9d07-11eb-85e1-a0e8ba321a2b.png)

**Comment by javdavalos** [comment]
Yeah I'm not sure what the problem is but there is a problem, even if it's just that how things are done now should be better communicated.

I also want to note that we also have a problem with our spatial anchors in the editor, the auto-connect takes too long and the app starts and XRReferencePointSubsystem is not ready.

I would suggest to roll back to manual connect or do not start the unity playmode until after the connection is succesful.

**Comment by keveleigh** [comment]
> I would suggest to roll back to manual connect

Good new on this front! Unity is working on making manual/automatic connect a setting, where you get to choose one or the other.

**Comment by keveleigh** [comment]
@javdavalos In the latest Windows XR Plugin releases, the manual connection option is restored! Uncheck "Connect on Play" and the button will return:

![image](https://user-images.githubusercontent.com/3580640/119426626-68068d00-bcbe-11eb-976c-a9a1982d4043.png)
