### ISSUE TITLE
Can't enable Focused speech voice command, no voice commands on buttons

### ISSUE THREAD

**Issue by studentutu** [microsoft/MixedRealityToolkit-Unity#9686]
## Describe the bug

Started from the default MRTK v.2.6.1 project for Hololens 2.
Enabled microphone, camera, internet capabilities
Using Cloned version of the Default Hololens2 XR SDK configuration profile
Added Windows Speech Data Provider (described here :  https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-09?tabs=winxr )

Inside the device I see the requests for microsoft/track eyes, camera - all of them accepted
Button configured to be used with Focused flag.
Can't use "Select"/any other voice command to initiate button press (using Hololens2 Button with ButtonHelperConfig)

## To reproduce

Add a single Button from MRTK Toolbox and Build for device (ARMx64, Hololens)

## Expected behavior

Interactable propagates the command into the OnClick

## Screenshots
Here are some screenshots:

![image](https://user-images.githubusercontent.com/18601652/115292895-482ff680-a15f-11eb-8763-50def7a4164d.png)

![image](https://user-images.githubusercontent.com/18601652/115292363-87117c80-a15e-11eb-9812-017c19d3860f.png)

![image](https://user-images.githubusercontent.com/18601652/115292535-c8099100-a15e-11eb-80ef-017d7805c605.png)
![image](https://user-images.githubusercontent.com/18601652/115292615-e3749c00-a15e-11eb-9a72-b26a1878bc7d.png)

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.4.22f1]
- MRTK Version [e.g. v2.6.1]
- 2 toolbox Hololens 2 buttons
- Clones Default XR SDK  Configuration Profile

## Target platform (please complete the following information)

- HoloLens 2

Please, help to understand why voice command is not working. (MRTK v2 speech is not working)

Edit:
Tried with the default SpeechInput Demo - Open/Close works with my configuration, but the focused items do not.

![image](https://user-images.githubusercontent.com/18601652/115299834-fb045280-a167-11eb-9956-60d5b52e2c32.png)

Should I add some sort of focus provider?

**Comment by RogPodge** [comment]
@cre8ivepark might you have more context on this topic?

**Comment by studentutu** [comment]
for now I've just added MRTK.SpeechInputHandler (global) and added custom component (has a method for set focus, which is being set from interactable button). It works fine, but not ideal solution.

**Comment by cre8ivepark** [comment]
I found that the **Select** keyword is not recognized/triggered. Tested with other example scenes as well.
Somehow, other keywords are working well. For example, if I add a new keyword **Message** to a HoloLens2 style button and assign it using Interactable's Speech keyword, it works well. 

**Select** keyword is still in the Speech Input Profile list. @keveleigh any insights?

![2021-05-03 00_58_52-MRTK - HandInteractionExamples - Universal Windows Platform - Unity 2019 4 22f1 ](https://user-images.githubusercontent.com/13754172/116853551-1da45b80-abab-11eb-829b-c98115aef605.png)

![2021-05-03 00_59_28-MRTK - HandInteractionExamples - Universal Windows Platform - Unity 2019 4 22f1 ](https://user-images.githubusercontent.com/13754172/116853562-2137e280-abab-11eb-9368-198d3d90989e.png)

**Comment by keveleigh** [comment]
I think this might be due to the lack of a way to get information on the voice select state like we had in legacy XR via https://github.com/microsoft/MixedRealityToolkit-Unity/blob/38626e1c32e2d6268d5b3d5044f9c22fb35b3fba/Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealityDeviceManager.cs#L868-L887

We're actively thinking about the right way to expose this in OpenXR, and I'll have to look into ways we can access this info via Windows XR Plugin.

**Comment by RogPodge** [comment]
So a few comments on some findings.

1. The select command is being detected and processed by the input system, so we can be confident that the speech handler is able to understand and process the speech keyword
2. Focused objects that can be affected by speech commands seems to be limited to objects in focus via the GazeProvider, hence why the SpeechInputExamples Scene has this label over it's objects
![image](https://user-images.githubusercontent.com/39840334/117218857-d986a600-adb8-11eb-9670-e7993ac633fc.png)
3. The Gaze Cursor (and thus I believe the gaze pointers) are deactivated the minute that hands are detected on device. Combined with needing to say "Select" to bring up the gaze cursor in the first place, this makes interacting with focused objects via voice commands really hard to use in general.

I'm wondering if for the near term, making voice commands work on objects "focused" via hand interactions is sufficient? Longer term, we might need to have more considerations on how we want to incorporate more eyetracking and hands free interaction along side articulated hand interactions. @cre8ivepark @keveleigh

**Comment by RogPodge** [comment]
We should also remove the 'Select' to bring up gaze cursor behavior since it's hard coded.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/265a0ea3621c84b88e4b02e7fcd1b5682afef56a/Assets/MRTK/Services/InputSystem/GazePointerVisibilityStateMachine.cs#L101-L107

**Comment by RogPodge** [comment]
Small update on how we're faring here compared to the hololens shell.

1. Hololens lets the select action work on objects that are in focus via the hand ray pointers.
2. Objects will always bring up a small dialogue under objects that can be activated via speech commands, greatly improving the usability of those controls
3. The Hololens doesn't hide the gaze cursor and disable interaction via gaze until the hands are actively engaging in near interactions or far interactions (ie. getting close enough to touch an interactable or forming a pinch gesture). This makes it much easier to stay in the Gaze Interaction Mode for an extended period of time.

These three points will need to be addressed to make speech voice commands (and likely other gaze/eyetracking inputs) work much more smoothly within MRTK and we'll make separate issues to track the different pieces of this endeavor.
