### ISSUE TITLE
Scene Understanding: ArgumentException when updating or toggle the view of Meshes

### ISSUE THREAD

**Issue by samuelspagl** [microsoft/MixedRealityToolkit-Unity#9706]
## Describe the bug

I'm working on a project where I'm using the in #9524 added functionality to access GameObjects throught the provided IReadOnlyDictionary in the public method `GetSceneObjectsofType(SpatiaAwarenessSurfaceTypes type)`. 
If the dictionary is accessed upon the startup of the App (in Unity as well as on the Hololens) no error occurres and i can process the data provided by the dictionary. But if you toggle either one of the UI Buttons like "Auto Update", "Infer Regions", "Walls", "Ceiling", etc. then the system throws an Exception resulting in not being possible call the `GetSceneObjectsofType(SpatialAwarenessSurfaceTypes type)` anymore.

It throws this Exception (The key value varies):

```
ArgumentException: An item with the same key has already been added. Key: -479192099
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Microsoft.MixedReality.Toolkit.Experimental.SceneUnderstanding.DemoSceneUnderstandingController.OnObservationAdded (Microsoft.MixedReality.Toolkit.SpatialAwareness.MixedRealitySpatialAwarenessEventData`1[T] eventData) (at Assets/MRTK/Examples/Experimental/SceneUnderstanding/Scripts/DemoSceneUnderstandingController.cs:112)
Microsoft.MixedReality.Toolkit.WindowsSceneUnderstanding.Experimental.WindowsSceneUnderstandingObserver+<>c.<.cctor>b__145_0 (Microsoft.MixedReality.Toolkit.SpatialAwareness.IMixedRealitySpatialAwarenessObservationHandler`1[T] handler, UnityEngine.EventSystems.BaseEventData eventData) (at Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs:498)
Microsoft.MixedReality.Toolkit.BaseEventSystem.HandleEvent[T] (UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] eventHandler) (at Assets/MRTK/Core/Services/BaseEventSystem.cs:118)
UnityEngine.Debug:LogException(Exception)
Microsoft.MixedReality.Toolkit.BaseEventSystem:HandleEvent(BaseEventData, EventFunction`1) (at Assets/MRTK/Core/Services/BaseEventSystem.cs:122)
Microsoft.MixedReality.Toolkit.WindowsSceneUnderstanding.Experimental.WindowsSceneUnderstandingObserver:SendSceneObjectAdded(SpatialAwarenessSceneObject, Int32) (at Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs:523)
Microsoft.MixedReality.Toolkit.WindowsSceneUnderstanding.Experimental.WindowsSceneUnderstandingObserver:Update() (at Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs:178)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:Update() (at Assets/MRTK/Core/Services/BaseDataProviderAccessCoreSystem.cs:51)
Microsoft.MixedReality.Toolkit.<>c:<UpdateAllServices>b__72_0(IMixedRealityService) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:1054)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:1145)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:UpdateAllServices() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:1054)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:727)
```

## To reproduce

1. Create a new Unity-Project
2. Add all the MRTK Dependencies
3. Install the Scene Understaning Extension through the MixedRealityFeatureTool
4. Open Unity, and start the SceneUnderstanding Demo, you will see that everything works fine, and no errors occur
5. Add the changes of the scripts described in #9524
6. Open Unity, start the "Play Mode", toggle on of the SurfaceType Buttons and see the Error.

## Expected behavior

Not throwing an exception, thus letting me access the dictionary and its GameObjects. 

## Screenshots

![MRTK_SceneUnderstanding_Bug2](https://user-images.githubusercontent.com/46893256/116039670-51432b00-a66b-11eb-94fd-6f391a4f284c.PNG)

## Your setup (please complete the following information)

- Unity Version [2019.04.22f1]
- MRTK Version [v2.6], SceneUnderstanding[0.6]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
Fixed via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9744
