### ISSUE TITLE
Better presentation of profiles

### ISSUE THREAD

**Issue by polar-kev** [microsoft/MixedRealityToolkit-Unity#9712]
The drop down list for profiles in MRTK 2.6.1 has grown very large. We should use Unity's GenericMenu to reduce the amount of profiles shown to the user at once.
![image](https://user-images.githubusercontent.com/30964480/116162639-12cd6080-a6ab-11eb-91eb-1015f5bc5d0a.png)

![image](https://user-images.githubusercontent.com/30964480/116162627-0ba65280-a6ab-11eb-8160-3382fb03d634.png)

This improvement should be considered before or at the same time as #9548.

**Comment by keveleigh** [comment]
Going to close this out. With the existing MRTK2 profiles, I'm not sure what the best groupings would be, and we've moved away from such a large dropdown in MRTK3.
