### ISSUE TITLE
What is the HoloLens 2 system default popup textbox when voice command is detected?

### ISSUE THREAD

**Issue by qian256** [microsoft/MixedRealityToolkit-Unity#9713]
In HL2, when some system reserved keywords are detected (e.g. select), there is a popup toast flying up: white border, black background, showing text of the keyword. Is this part of UWP API, or MRTK?
I did some search and could not find anything documenting this. Is this somthing available to hololens developers?

**Comment by NoTuxNoBux** [comment]
I think this is the `SpeechConfirmationTooltip`. It has a similar pop-up toast animation, but I don't know if the colours are the same.

There is also a sound called `MRTK_Voice_Confirmation` available that I think you can use to play a matching sound.

**Comment by qian256** [comment]
Thanks @NoTuxNoBux
