### ISSUE TITLE
Testing Vuforia+HL applications on desktop

### ISSUE THREAD

**Issue by shllybkwrm** [Microsoft/MixedRealityToolkit-Unity#973]
My HoloLens app uses Vuforia for image recognition.  I normally test my app in the Unity player first, using my laptop's webcam, but this is impossible with the HoloLensCamera prefab as it blacks out the camera backdrop.  
This also affects the UWP app on my Windows 10 machine - but I'm unsure if there are other compatibility issues affecting that from the HoloLens setup.
What can I change to allow Vuforia to show the camera but still allow the HL camera to work?  Vuforia's camera is linked to the HoloLensCamera prefab as part of the required setup.

**Comment by shllybkwrm** [comment]
Okay, I did a little digging and it seems Vuforia apps are only supported on Surface devices which have a rear camera, so I will save the non-HoloLens version for when our Surface gets in.
In the meantime, I have been able to get the webcam input to show in Unity Play mode by doing the following steps:

1.  Disable the HoloLensCamera
2.  Revert the ARCamera prefab, i.e. switch World Center Mode back to DEVICE_TRACKING from CAMERA
3.  In Vuforia Configuration, switch Digital Eyewear Type back to None.

However, it's hard to test like this since everything is at the wrong scale, and I can't test Vuforia apps in the HoloLens Emulator either.  I also don't know whether things will work properly due to the settings I changed.  Does anyone have suggestions for easier debugging with Vuforia?

**Comment by StephenHodgson** [comment]
Thanks for sharing your progress!

**Comment by shllybkwrm** [comment]
I forgot to mention one more thing.  When I follow the steps above, the Unity UI elements are completely unresponsive, but when the HoloLens capabilities are enabled, they function and are shown on top of the black background rather than the webcam feed as desired.  So I'm unable to test the complete app in the Unity player, and each component is fairly useless without the other.
