### ISSUE TITLE
Unexpected manipulation behavior when object isn't centered on object

### ISSUE THREAD

**Issue by jaraymsft** [microsoft/MixedRealityToolkit-Unity#9750]
## Describe the bug

We have an object with an ObjectManipulator attached. The manipulation colliders are ~85cm above the object's origin. When manipulating the object, it also moves unexpectedly in a vertical direction.

## To reproduce

Create a large object. (Ours is a 85cm tall table)
Add an ObjectManipulator, set to use ManipulationMoveLogic and RotateAboutObjectCenter.
Add a grab collider that is significantly away from the object origin. (Our table's origin is at the floor, while the grab colliders are on the tabletop).
Move the object with distance beams.
When trying to move the object toward/away from yourself, it will also move vertically.
The amount it moves is proportional to how far the collider is from the object origin.
The unexpected direction it moves is along the vector from the object origin to the grab location.

## Expected behavior

Expect the manipulation to behave the same as if the object's origin was at the collider location.

## Your setup

- Unity Version 2019.4.13f1
- MRTK Version v2.5.1

## Target platform

HoloLens 2

## Additional context

We have a fix for this that changes ManipulationMoveLogic.cs to not multiply grabToObject by distanceRatio. Our team can prepare a PR with the fix.

**Comment by CDiaz-MS** [comment]
Fixed by #9755
