### ISSUE TITLE
MRTK docs should have instructions for setting up HP Reverb G2

### ISSUE THREAD

**Issue by polar-kev** [microsoft/MixedRealityToolkit-Unity#9757]
Dear all,

I'm trying to build a basic prototype and I don't find basic tutorial which explain the "how to" set up HP reverb G2 controllers. I mean which prefab/3D object set up in my hierarchy, which script do I add to my prefac/3D object.

I don't understand how to manage the inspector device manager.

could you please provide screenshots guideline to set up controllers? The current documentation does not help unfortunately or I missed something.

Many thanks in advance

_Originally posted by @sebstax7 in https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/9730_

**Comment by keveleigh** [comment]
Our existing non-MRTK docs for this live at https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/unity-reverb-g2-controllers

Is this an issue that can be solved by

1. Ensuring that doc is correct and up-to-date
2. Filling out our docs on controller mappings
3. Maybe clarifying that controller models won't show up in the editor in non-OpenXR
4. Making it clear that MRTK's systems will adapt when the input package mentioned in the above doc is installed

**Comment by polar-kev** [comment]
@keveleigh Yes to 1,3, and 4.

For number 2, I'd like to clarify--I think those updates should be made on MRTK controller input docs at, https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/input/controllers. I think surfacing number 4 in these MRTK docs with a link to the Reverb g2 page mentioned above will address the types of questions we've received recently.

Is that what you meant or were you referring to the [controller mapping tool doc](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/tools/controller-mapping-tool).

**Comment by keveleigh** [comment]
@polar-kev You got it exactly!

**Comment by RogPodge** [comment]
Docs updated and reorganized a bit: https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/input/controllers

Would a dedicated page describing the Microsoft.MixedReality.Input package and the role it plays in getting many WMR platforms up and running be useful? I'm thinking it could live in the newly revamped [Supported Device Overview](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/input/controllers) section
