### ISSUE TITLE
Keyboard OnDictationResult not updating InputField

### ISSUE THREAD

**Issue by shaddadjr** [Microsoft/MixedRealityToolkit-Unity#976]
When attempting to use voice commands to input text with the new Keyboard, the InputField does not appear to update with the text.

I put breakpoints in the function:

```
 private void OnDictationResult(string text, ConfidenceLevel confidence)
        {
            if (text != null)
            {
                m_InputField.text.Insert(m_InputField.caretPosition, text);
                m_InputField.caretPosition += text.Length;
            }
        }

```

and verified it is making these calls without exceptions, the text string is correctly populated, but the text never appears in the input field. The input field is properly mapped in the inspector.

I am using Unity 2017.1.0f3

**Comment by StephenHodgson** [comment]
Related to #834
