### ISSUE TITLE
MissingReferenceException in TeleportCursor

### ISSUE THREAD

**Issue by mbpictures** [microsoft/MixedRealityToolkit-Unity#9761]
## Describe the bug

I'm getting a "MissingReferenceException" exception several times while interacting with the hand menu.
```
MissingReferenceException: The object of type 'Transform' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Microsoft.MixedReality.Toolkit.Teleport.TeleportCursor.SetVisibility (System.Boolean visible) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d50bf63c95b4-1619092775596/SDK/Features/UX/Scripts/Cursors/TeleportCursor.cs:119)
Microsoft.MixedReality.Toolkit.Utilities.Solvers.HandConstraint+<ToggleCursors>d__62.MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d50bf63c95b4-1619092775596/SDK/Features/Utilities/Solvers/HandConstraint.cs:478)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <4d9f7249f1de41e384668fea10e9822f>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Microsoft.MixedReality.Toolkit.Utilities.Solvers.HandConstraint:SolverUpdate() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d50bf63c95b4-1619092775596/SDK/Features/Utilities/Solvers/HandConstraint.cs:318)
Microsoft.MixedReality.Toolkit.Utilities.Solvers.Solver:SolverUpdateEntry() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d50bf63c95b4-1619092775596/SDK/Features/Utilities/Solvers/Solver.cs:260)
Microsoft.MixedReality.Toolkit.Utilities.Solvers.SolverHandler:LateUpdate() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d50bf63c95b4-1619092775596/SDK/Features/Utilities/Solvers/SolverHandler.cs:323)
```

## To reproduce

1. Create and configure a Project with MRTK
2. Create a hand menu game object containing buttons
3. Disable Teleport System in MRTK Configuration

## Expected behavior

No exceptions.

## Your setup (please complete the following information)

- Unity Version 2020.3.3f1
- MRTK Version 2.5.4

## Target platform (please complete the following information)

- HoloLens 2

## Additional context
It seems that there was already a fix for this issue (#8978), but is not available in the used version (2.5.4), although the merge happened before the release of 2.5.4.

**Comment by MaxWang-MS** [comment]
Hi @mbpictures, please try to reproduce with the latest MRTK version and let us know if the issue persists. We do not backport fixes to prior versions and the dot releases (e.g. 2.5.1, 2.5.2) only contain fixes to critical issues.

**Comment by mbpictures** [comment]
Ah okay! Well I can't test the current Version, as it seems that HandTracking (and therefor hand menu) doesn't work in Version 2.6.1 and 2.6.0 (See #9682 )

**Comment by MaxWang-MS** [comment]
Please reopen the issue if you are still encountering it. Also the hand tracking issue mentioned above has been fixed.
