### ISSUE TITLE
Missing mrtk_development branch

### ISSUE THREAD

**Issue by krishnan-unni** [microsoft/MixedRealityToolkit-Unity#9763]
## Overview
The documentation on MRTK contribution here: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Documentation/Contributing/CONTRIBUTING.md says we need to get the 
https://github.com/microsoft/mixedrealitytoolkit-unity/tree/mrtk_development branch.
Although this branch is no more available. What branch should be forked to use for contributions? Guess the docs need to be updated?

**Comment by RogPodge** [comment]
Yeah we need to update the documentation. Currently, [main](https://github.com/microsoft/MixedRealityToolkit-Unity/tree/main) is the branch that should be forked for contributions
