### ISSUE TITLE
Missing Input Playback service for Hololens2XRSDK profile

### ISSUE THREAD

**Issue by cwule** [microsoft/MixedRealityToolkit-Unity#9764]
## Describe the problem

I want to play back hand movements on the Hololens 2 recorded with the `InputRecordingControls`. If I set the MRTK profile to `DefaultHololens2ConfigurationProfile`, playing the animation works in the editor, however that profile leads to problems of the app on the Hololens 2 (no room tracking).
If I chose the `DefaultHololens2XRSDKConfigurationProfile`, I cannot play animations, since there is no `InputPlaybackService`.

## Describe the solution you'd like

Can the InputPlaybackService be added again to the `DefaultHololens2XRSDKConfigurationProfile `or is there anything else I am missing?

## Describe alternatives you've considered

I tried cloning and modifying the profiles, eg. to clone the `DefaultHololens2XRSDKConfigurationProfile `and replace the `DefaultXRSDKInputSystemProfile ` with the `DefaultHololens2InputSystemProfile`. That didn't show hands on the Hololens 2 unfortunately.

**Comment by keveleigh** [comment]
Starting with 2.7.0-preview.4, you no longer need to change profiles for XR SDK and all these asymmetrical service lists should be resolved! If you've cloned the profiles, you should be able to safely re-add the playback service to the cloned `DefaultXRSDKInputSystemProfile` without other changes.

**Comment by cwule** [comment]
@keveleigh  Yes, that works, thanks a lot!
