### ISSUE TITLE
Ability to Modify Camera Transform Position at Runtime

### ISSUE THREAD

**Issue by torynfarr** [microsoft/MixedRealityToolkit-Unity#9765]
## Describe the problem

Using MRTK 2.6.1 and Unity 2019.4.25f1 LTS, it's not possible to change the camera position (via code) at runtime. It's possible when running in the editor, but not in the player. Setting _Camera.main.transform.position_ to a new Vector3 does nothing.

The MRTK camera profile being used is: _DefaultXRSDKCameraProfile_ and at runtime the device being used is an Oculus Quest 2.

## Describe the solution you'd like

Specifically, the ability to set the position of the transform on the main camera to a new Vector3. This could be a setting that could be enabled/disabled in the MRTK camera profile.

## Describe alternatives you've considered

As a work around, I've implemented a system where the entire environment is repositioned and rotated to give the illusion that you've walked up a set of stairs and turned to face the direction you would be facing had you walked up the stairs in real life.

The problem with this alternative is that it requires that you leave everything in the scene as a dynamic object rather than static. This prevents you from having shadows via baked lighting; essentially requiring real time lighting for shadows. On a device like Oculus Quest 2, this is not performant.

## Additional context

It's understandable why the camera position is something that you wouldn't want to alter when the application is designed for augmented reality (HoloLens in particular), but for virtual reality, there are a few valid reasons to have this capability. 

Movement via the teleportation system works great in single-floor virtual environments. When you need the player to be able to move up or down multiple floors in the environment, the hand gesture teleportation is not ideal. Typically, you can't see where the teleportation cursor is landing.

An example use-case:  the player uses the teleportation system to enter an elevator. Inside the elevator is an up button. They press it. You would then alter the position of the camera to move the player up to another floor in the environment.

Another reason would be if you wanted to move the user a large distance (horizontally), teleporting them to another part of a level without having to load a new scene.

**Comment by keveleigh** [comment]
This behavior is unfortunately not controlled by MRTK but is instead inherent in the way Unity keeps the camera aligned with your head.

For this reason, MRTK exposes the MixedRealityPlayspace, which we use for things like teleportation in order to move the camera from one area in the scene to another. You basically need to move a parent of the camera instead of the camera itself.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/d6398dd1603d7ba9376a0e75ff6e0a6f91d805d8/Assets/MRTK/Core/Utilities/MixedRealityPlayspace.cs#L73-L77

**Comment by torynfarr** [comment]
> This behavior is unfortunately not controlled by MRTK but is instead inherent in the way Unity keeps the camera aligned with your head.
> 
> For this reason, MRTK exposes the MixedRealityPlayspace, which we use for things like teleportation in order to move the camera from one area in the scene to another. You basically need to move a parent of the camera instead of the camera itself.
> 
> https://github.com/microsoft/MixedRealityToolkit-Unity/blob/d6398dd1603d7ba9376a0e75ff6e0a6f91d805d8/Assets/MRTK/Core/Utilities/MixedRealityPlayspace.cs#L73-L77

Oh fantastic! Thank you!

I'll give this a shot and see if I can move the camera this way. Sounds simple enough!

**Comment by torynfarr** [comment]
> @torynfarr Great! Please follow-up here if you run into any blockers!

@keveleigh I can confirm that I'm able to both reposition and rotate the camera using the MixedRealityPlayspace.

```
    public void OnUpButtonPress()
    {
        MixedRealityPlayspace.Position = UpstairsHotspot.transform.position;
        MixedRealityPlayspace.Rotation = UpstairsHotspot.transform.rotation;
    }
```

Thanks so much for your quick help! 

The way I was doing it before (repositioning the entire environment) was quite difficult to do (given that both position and rotation needed to be changed and destination position was not the pivot point. Way too much math 😅

**Comment by keveleigh** [comment]
Glad to hear it!

**Comment by torynfarr** [comment]
@keveleigh So, I sort of spoke too soon. I'm able to move and rotate the _MixedRealityPlayspace_ Game Object and this does change the camera's position, however... it doesn't seem to alter the camera's rotation as expected.

The expectation would be that after the rotation is set on the _MixedRealityPlayspace_, the camera's rotation would be 0, 0, 0 (facing the same orientation as the playspace).

To help visualize what's happening, I put a blue cube scaled into the shape of a rectangle on the _MixedRealityPlayspace_ and can visually confirm that it's both changing the position and the rotation. It's perfectly aligned with the green visual indicator on the destination Game Object (which denotes its orientation).

I put a red cube on the camera (and it's also the selected Game Object, so you can see the directional handles on it).

In the attached images, you can see the positions of everything when I approach the stairs and press a button to go up the stairs. The camera is rotating, but there's an offset. It's no longer matching the orientation of the _MixedRealityPlayspace_.

What's odd is that it's definitely rotating. It's just not rotating as expected. Is it a local vs. world space issue? Is there a way to reset the main camera Game Object to match the orientation of its parent?

![Bottom of Stairs](https://user-images.githubusercontent.com/36836551/117379029-3313d100-ae9c-11eb-8728-407dd75f0fbd.jpg)

![Top of Stairs](https://user-images.githubusercontent.com/36836551/117378871-e62ffa80-ae9b-11eb-9c83-2bb1aaf980d7.jpg)

**Comment by keveleigh** [comment]
Ah yeah, we have some math in the teleport system to attempt to orient the playspace in a way that puts the camera in the correct pose:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/d6398dd1603d7ba9376a0e75ff6e0a6f91d805d8/Assets/MRTK/Services/TeleportSystem/MixedRealityTeleportSystem.cs#L300-L308

You might be able to adapt that for your use case! Assuming I'm interpreting those images correctly, it does look like the blue cube ends up in the same spot relative to the green dash on the circles on the floor (it's ~160° counter clockwise in both images)

**Comment by torynfarr** [comment]
> Ah yeah, we have some math in the teleport system to attempt to orient the playspace in a way that puts the camera in the correct pose:
> 
> https://github.com/microsoft/MixedRealityToolkit-Unity/blob/d6398dd1603d7ba9376a0e75ff6e0a6f91d805d8/Assets/MRTK/Services/TeleportSystem/MixedRealityTeleportSystem.cs#L300-L308
> 
> You might be able to adapt that for your use case! Assuming I'm interpreting those images correctly, it does look like the blue cube ends up in the same spot relative to the green dash on the circles on the floor (it's ~160° counter clockwise in both images)

Yeah, I was already thinking somewhere along those lines:   get the playspace oriented correctly, then calculate the rotation difference on the _y_ axis between the playspace and the camera and adjust the playspace _y_ rotation accordingly.

This is what I came up with... and it seems to work correctly (going both up the stairs and down the stairs):

```
    public void OnButtonPress()
    {
        MixedRealityPlayspace.Position = Destination.transform.position;
        MixedRealityPlayspace.Rotation = Destination.transform.rotation;
        MixedRealityPlayspace.Rotation = Quaternion.Euler(new Vector3(0.0f, MixedRealityPlayspace.Rotation.eulerAngles.y + (MixedRealityPlayspace.Rotation.eulerAngles.y - Camera.main.transform.rotation.eulerAngles.y), 0.0f));
    }
```

So that works correctly when the _rotation.eulerAngles.y_ of both the playspace and camera are positive numbers. I'm guessing that my math will be incorrect if either of them are a negative number. Something I'll have to test and account for if I use button based teleportation anywhere else in my app.

Thanks again for your help! 🙏🏻
