### ISSUE TITLE
Mutliple trigger events from single Pinch Geusture - MRTK Quest

### ISSUE THREAD

**Issue by SabinMGeorge** [microsoft/MixedRealityToolkit-Unity#9771]
## Describe the bug
When interacting using far pointer on UI buttons or MRTK buttons (in hand mode, quest2), single pinch action results in multiple Click events gets invoked. Near interactions works fine as expected.

Far pointer Pinch action using hand invokes multiple events instead of single. 

## To reproduce

Set Up unity project with following modules
Unity 2021.03.01f 
Oculus Integration 28.0
Mixed Reality Toolkit v2.6
Oculus XR Plugin 1.8.1

OculusProjectConfig - hand tracking mode = controllers and hand.

Build the project with HandInteractionExamples scene. Run the build on the Quest2, and try to use far pointer interaction with hand. Select any button or 3d objects using hand pinch action, you can notice the multiple events gets triggered from single pinch action.

Also, you can try playing the piano in the scene. Multiple key presses registered on a single action.

## Expected behavior
A single event should be triggered from single pinch action. 

## Your setup (please complete the following information)

- Unity Version [e.g. Unity 2021.03.01f]
- MRTK Version [ v2.6]
- Oculus Integration 28.0

## Target platform (please complete the following information)

- Oculus Quest

**Comment by keveleigh** [comment]
This sounds like the bug that should be fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9576, which has shipped in our latest MRTK 2.7.0-preview.4 if you want to try it out! FYI @RogPodge

**Comment by SabinMGeorge** [comment]
@keveleigh, ya its fixed. Thanks
