### ISSUE TITLE
Dockable auto re-scale problem

### ISSUE THREAD

**Issue by D3m0n92** [microsoft/MixedRealityToolkit-Unity#9783]
## Describe the problem

In some cases the re-scale done by the dockable script is not useful or desired. For example in my case I need to leave the real scales of the objects unchanged (already precisely scaled), even when they are in the dock.

## Describe the solution you'd like

The solution would be to add a flag in the Dockable script to enable or disable auto re-scale.

**Comment by D3m0n92** [comment]
Anyone?

**Comment by D3m0n92** [comment]
As mentioned, I fixed the scripts myself. Closed.

**Comment by keveleigh** [comment]
> As mentioned, I fixed the scripts myself. Closed.

@D3m0n92 If you're able to contribute this back as a configurable setting (something like `maintainScaleOnDock`), I'm sure others would benefit from your fixes! Glad you were able to figure it out.
