### ISSUE TITLE
I'd like to be able to create a Rotate gizmo using MRTK

### ISSUE THREAD

**Issue by cjosewski** [microsoft/MixedRealityToolkit-Unity#9792]
## Describe the problem

I have a feature request.  I'd like the ability to create a Rotate Manipulator with a Sphere Collider. 

## Describe the solution you'd like

Use a sphere collider to create a Rotate manipulator and modify the BoundsControl and ObjectManipulator scripts to be able to use a sphere collider so you can create a Rotate gizmo.

## Describe alternatives you've considered

The alternatives are to create my own but the dependencies in MRTK are a bit of an issue.  Would be nice to have more control over customization

**Comment by Zee2** [comment]
You can create custom rotation handles for BoundsControl, which should do what you're looking for.
