### ISSUE TITLE
Request: Make SpherePointer.IsNearObject virtual

### ISSUE THREAD

**Issue by AMollis** [microsoft/MixedRealityToolkit-Unity#9794]
## Describe the bug

This bug impacts ARR Showcase/Mesh Showcase interaction with remote objects.  To support grabbing remote objects, without using Unity colliders, ARR Showcase implements a custom SpherePointer for grab interactions. 

Most of the SpherePointer can be extended.  However we can't extend the IsNearObject::getter behavior.

At the moment we copy the code in SpherePointer, because we want the "local object" handling.  However, it would be better if we could extend the SpherePointer.  Or even better, could the SpherePointer logic be encapsulated for use in custom pointers?

## To reproduce

1. Try to extend SpherePointer to add additional logic for IsNearObject::getter
2. You can't extend

## Expected behavior

Make IsNearObject::getter virtual

## Your setup (please complete the following information)

- Unity Version: 2019.4.17
- MRTK Version: 2.7-preview

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2

## Additional context

See ARR Showcase's RemoteSpherePointer implementation.

**Comment by RogPodge** [comment]
PR out for 2.7! #9803
