### ISSUE TITLE
SaveInputAnimationAsync never completes

### ISSUE THREAD

**Issue by cwule** [microsoft/MixedRealityToolkit-Unity#9795]
## Describe the bug

If I record an animation and save it via `SaveInputAnimation`, a .bin file is saved in the respective folder as expected.
If I however try to record an animation and save via `SaveInputAnimationAsync`, only an empty .bin file is created and the async saving task is never completed.
I prefer to use `SaveInputAnimationAsync`, since `SaveInputAnimation `leads to a noticable interruption of the app.

## To reproduce

Replace `RecordingService.SaveInputAnimation();` in `InputRecordingControls` with `RecordingService.SaveInputAnimationAsync();`.

## Expected behavior

`SaveInputAnimationAsync` should also create a not-empty .bin file.

## Your setup (please complete the following information)

- Unity Version 2020.3.6f1
- MRTK Version 2.7.0

## Target platform (please complete the following information)

- HoloLens 2

**Comment by MaxWang-MS** [comment]
Hi @cwule, just to make sure could you confirm that you used the await keyword before RecordingService.SaveInputAnimationAsync()? If not please make sure to do that and mark the SaveRecordedInput function as async. Let me know if that works for you.

**Comment by cwule** [comment]
@MaxWang-MS Thanks for the quick reply, that was it!
