### ISSUE TITLE
Build window to support HTTPS communication

### ISSUE THREAD

**Issue by jevertt** [Microsoft/MixedRealityToolkit-Unity#98]
We currently only support local IP (IPOverUSB) due to lack of HTTPS support. We would like to add secure communication to the REST calls used by this window (the Portal class) so that remote IPs can be exposed out.

**Comment by HodgsonSDAS** [comment]
Doesn't the Windows Device Portal support this already?
Is the issue that the work just needs to get done in the Build Window to support this?

**Comment by jevertt** [comment]
The blocking issues was that the device portal code is latest .net & Unity editor only supports up to 3.5. Would love to find a way to get around this.

**Comment by StephenHodgson** [comment]
@jevertt I believe 5.6 supports 4.5

**Comment by StephenHodgson** [comment]
After some research I found that when targeting HTTPS we also need to either add `auto-` prefix to the username for all non GET rest calls or add the CSRF token to the header on each call.

[**CSRF Protection and Scripting**](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal#csrf-protection-and-scripting)
> In order to protect against CSRF attacks, a unique token is required on all non-GET requests. This token, the X-CSRF-Token request header, is derived from a session cookie, CSRF-Token. In the Device Portal web UI, the CSRF-Token cookie is copied into the X-CSRF-Token header on each request.
Important This protection prevents usages of the REST APIs from a standalone client (e.g. command-line utilities). This can be solved in 3 ways:
> - Use of the "auto-" username. Clients that prepend "auto-" to their username will bypass CSRF protection. It is important that this username not be used to log in to Device Portal through the browser, as it will open up the service to CSRF attacks. Example: If Device Portal's username is "admin", curl -u auto-admin:password <args> should be used to bypass CSRF protection.
> - Implement the cookie-to-header scheme in the client. This requires a GET request to establish the session cookie, and then the inclusion of both the header and the cookie on all subsequent requests.
> - Disable authentication and use HTTP. CSRF protection only applies to HTTPS endpoints, so connections on HTTP endpoints will not need to do either of the above.
>
>_Note: a username that begins with "auto-" will not be able to log into Device Portal via the browser._

**Comment by StephenHodgson** [comment]
Did this make it into master yet?
