### ISSUE TITLE
Importing certain example scenes via UPM generates "Creating missing ConstraintManager" warning

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9802]
## Describe the bug

When importing the example scenes highlighted below via UPM, a "Creating missing ConstraintManager" warning is generated.

**Initial Examples UPM package import**
![image](https://user-images.githubusercontent.com/65038391/118031972-fae91400-b31b-11eb-8419-6b11ba8c1e8b.png)

**Demos - HandTracking **
![image](https://user-images.githubusercontent.com/65038391/118032270-54514300-b31c-11eb-8c09-5507eb712954.png)

**Demos - ScrollingObjectCollection**
![image](https://user-images.githubusercontent.com/65038391/118032465-91b5d080-b31c-11eb-8c32-7d38bf4856d3.png)

**Experimental - ColorPicker**
![image](https://user-images.githubusercontent.com/65038391/118032897-0426b080-b31d-11eb-8cfc-b6c12d0ab5a1.png)

**Experimental - Examples Hub**
![image](https://user-images.githubusercontent.com/65038391/118033064-39330300-b31d-11eb-9b4a-b8e30bc588dc.png)

**Experimental - HandMenuLayout**
![image](https://user-images.githubusercontent.com/65038391/118033208-67184780-b31d-11eb-9892-bffcf2765d2e.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.7
- MRTK Version 2.7
- 
## Target platform (please complete the following information)

- OpenXR
- UWP

**Comment by davidkline-ms** [comment]
Closed with #9805
