### ISSUE TITLE
XR SDK Spatial meshes partially broken with non-identity playspace

### ISSUE THREAD

**Issue by fast-slow-still** [microsoft/MixedRealityToolkit-Unity#9810]
## Describe the bug
When the transform on the playspace goes from identity to non-identity, the spatial meshes get into an inconsistent state. Some appear to still be correctly aligned with the physical environment, but some are offset by the new MRTK playspace transform.

## To reproduce

1. Build app with spatial mesh visualization on (XR SDK) for HoloLens
2. Run app.
3. After seeing some spatial meshes display, trigger the setting of some obvious transform on the MRTK playspace (e.g. position=(1,1,1).
4. Walk around some more, generating more spatial meshes.
5. Note that some meshes are correctly aligned with physical environment, but some are offset by e.g. (1,1,1).

## Expected behavior

All spatial meshes should still be aligned with their physical counterparts.

## Screenshots

I tried capturing a screenshot showing some correct and some incorrect spatial meshes, but they all came out just looking like noise. It's very obvious in HoloLens when it happens.

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.3.2f1]
- MRTK Version [e.g. v2.6.1]

## Target platform (please complete the following information)

- HoloLens 2

## Additional context
- Have only seen this on XR SDK using Windows XR Plugin. Haven't tested extensively on other targets though.

**Comment by fast-slow-still** [comment]
It _appears_ that spatial meshes correctly displaying before the change to the playspace transform continue to correctly display, but new meshes coming in and being created are displayed incorrectly offset.

**Comment by laultman** [comment]
I sent you two video captures that may reveal the issue.
