### ISSUE TITLE
HandCoachExample generates "Found an existing event system in your scene" warning when opened

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9812]
## Describe the bug

The HandCoachExample generates "Found an existing event system in your scene" warning when opened in the editor. This issue occurs with UPM and .unitypackages.

## Screenshots

![image](https://user-images.githubusercontent.com/65038391/118156727-8ae79600-b3ce-11eb-928b-50481a78ef90.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.7
- MRTK Version 2.7

## Target platform (please complete the following information)

- UWP
- OpenXR

## Additional context

This issue has not been verified in Unity 2018 or Unity 2019.

**Comment by davidkline-ms** [comment]
From looking at the scene file, there is o,ne EventSystem object and it is on the Camera object. However, in Unity 2020, the parent of the EventSystem is getting reported as the MixedRealityPlayspace, so another is added on the camera. This results in two (2) EventSystem objects on the Camera object.

**Comment by davidkline-ms** [comment]
fixed with #9842
