### ISSUE TITLE
Importing ColorPicker sample generates ConstraintManager warning

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9821]
## Describe the bug

When importing the ColorPicker sample from the Examples UPM package, a "Creating missing ConstraintManager componenent..." warning is generated for ObjectManipulator in Quad.

## Screenshots

![image](https://user-images.githubusercontent.com/65038391/118311902-64e0f500-b4a5-11eb-8599-8e4fcc551dda.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.7f1
- MRTK Version 2.7

## Target platform (please complete the following information)

- Standalone
- OpenXR

**Comment by davidkline-ms** [comment]
I have a fix ready for this. It'll likely be part of a PR with at least one other import / asset load warning fix.

**Comment by davidkline-ms** [comment]
Fixed with #9842
