### ISSUE TITLE
Add way to disable controller visualization at runtime. Clarify Hand Joints and Hand Mesh as specifically for articulated hands

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#9823]
## Describe the problem

Users currently have the ability to turn off articulated hand mesh and articulated hand joint visualizations at runtime, this issue tracks doing the same for controller visualizations. We also need to be more clear that hand mesh and hand joints refer specifically to articulated hand meshes and joints.

Related to this: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8793#issuecomment-841621907

**Comment by keveleigh** [comment]
This has always been a feature where its current implementation kinda goes against our other MRTK patterns. It currently checks against the profile itself, while we've always tried to use the profile as startup values and expose runtime settings on systems themselves.

Probably a larger overhaul than we'd want to do for 2.x (and not really in scope specifically for this issue) but could be good for us to keep in mind for 3.x going forward.

**Comment by RogPodge** [comment]
Closing with the profile rename. Refactoring the interface to explicitly toggle visual status is a bit out of scope for 2.8. As it stands, disabling the GameObjectProxy usually works well enough as a workabout.
