### ISSUE TITLE
Microsoft's MixedReality-WebRTC library. remote video player does not show up even though Peer conne

### ISSUE THREAD

**Issue by sogofurikai** [microsoft/MixedRealityToolkit-Unity#9825]
Hi Everyone,

The remote video player does not show up.
Tutorials on https://microsoft.github.io/MixedReality-WebRTC/manual/unity/helloworld-unity-connection.html and https://forum.unity.com/threads/mic...mponent-doesnt-have-a-source-property.994370/ I'm referring to the question.
(The webrtc connection seems to be fine, and the offer and answer messages seem to be fine.)

I think it has something to do with the "Starting the WebRTC connection" part of the tutorial, but I don't know what I am supposed to do here.

The remote camera is configured as follows.
<img width="489" alt="ead0ad6215" src="https://user-images.githubusercontent.com/74498777/118393820-05890d80-b67c-11eb-822d-cf70cd75f18f.png">

I am using Unity 2019.4.24.

Any help would be greatly appreciated.

**Comment by MaxWang-MS** [comment]
Hi, sorry for the delayed response. It seems like the issue you are having is related to MixedReality-WebRTC, so please report it in [their repo](https://github.com/microsoft/MixedReality-WebRTC). Thanks!
