### ISSUE TITLE
Bounds Control's Configuration files does not exist as asset

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#9829]
## Describe the bug
BoundsControl.cs provides the capability for customizing visuals through Configuration (profile) files. However, currently, there are no configuration files in the assets. Users have to use configuration files under specific example (Cheese.prefab) which can cause problems when those prefabs are deleted or removed from the project.

## To reproduce
1. Add any object
2. Add BoundsControls.cs
3. Under Visuals section > Box Configuration > click empty field and find configuration file
4. Configuration files belong to Cheese.prefab or Slate.prefab.

## Expected behavior
Configuration files should exist as a stand-alone asset.

## Screenshots
<img width="1002" alt="BoundsControlConfig" src="https://user-images.githubusercontent.com/13754172/118591981-08f2c680-b75a-11eb-94c5-4f9d0b4aa8d5.png">

**Comment by davidkline-ms** [comment]
resolved by #9830
