### ISSUE TITLE
How to save spatial understanding results ?

### ISSUE THREAD

**Issue by Emerson92** [Microsoft/MixedRealityToolkit-Unity#984]
After scanning the room and trying to "understand" it, is there a way to save the result of all this "understanding" process (on the device,locally) in order to avoid rescanning/understanding again at each launch ?

**Comment by Weasy666** [comment]
I'm also interested in this.
It should be possible, if i'm not wrong Asobo is doing something like this in Fragments.
If my memory is correct, they are even warning the user when the differences between saved and current room are to big.

**Comment by tontonwawa** [comment]
Maybe #188 could help. There's code in it to that end. I couldn't get it to work but who knows.
On the other hand there is a SaveSpatialMeshes in SpatialUnderstandingCustomMesh hinting that we can save this mesh. But I can't find how to load it.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
