### ISSUE TITLE
Hand tracking for HP Reverb G2 controllers

### ISSUE THREAD

**Issue by Rego363** [microsoft/MixedRealityToolkit-Unity#9849]
## Describe the bug

I was able to get hand tracking on the Reverb G2 controllers when I first added MRTK to my project. I could see the models, move them, point and close my hands yesterday. Over night it appears to have stopped working. I can no longer see the models and the gameobjects for the models are in the hierarchy anymore. I don't remember changing anything to make this happen.

## To reproduce

1. Add MRTK to project using the Mixed Reality Feature Tool. (MRTK Foundation and Standard Assets, MR OpenXR plugin and MR Input)
2. Go to project settings, "XR Plug-in Management" and check the "OpenXR" and "Windows Mixed Reality feature set" boxes
3. Go to "Features"  under "OpenXR" in the project settings hierarchy. Here make sure "Hand Tracking plugin", "HP Reverb G2 Controller Profile", "Microsoft Hand Interaction Profile" and "Microsoft Motion Controller Profile" as all checked.
4. Clone Hand Tracking setting in MRTK in project, making sure Hand Mesh/Joint Visualization Modes have everything selected.

## Expected behavior

Being able to have full hand/controller tracking with movement, point and close hands

## Screenshots
![image](https://user-images.githubusercontent.com/22478063/119156590-47cf9780-ba4c-11eb-937b-7a45f157df54.png)
Note bottom right game window has hand tracking working & 4 gameobjects in the hierarchy for the right hand controller ( taken last night)

![image](https://user-images.githubusercontent.com/22478063/119157456-1c997800-ba4d-11eb-879a-d26d31863186.png)
No longer seen in game or scene views, 2 gameobjects in the hierarchy now (taken as I am typing this)

## Your setup (please complete the following information)

- Unity Version 2020.3.6f1
- MRTK Version v2.6.1

## Target platform (please complete the following information)

- HP Reverb G2

**Comment by keveleigh** [comment]
I realized I had been leaving some updates on #10297 but not updating here:

>Basically, the OpenXR integration into Unity works by spinning up two `InputDevice`s per hand/controller: one for providing the button/thumbstick/airtap/etc interactions and one for the hand joints.
MRTK currently makes an incorrect assumption that _only_ a hand can provide hand joints. Therefore, when we receive the hand joint `InputDevice` first, we spin up the hand joint visualization. When we receive the interactions `InputDevice` first, we spin up the controller visualization.
I'm not specifically sure about the play mode vs build behavior you're seeing, but it could be that each environment tends towards providing the two `InputDevice`s in a specific order for some reason...
I've been making steps towards fixing this in MRTK 2.8, but it's not completed yet.

Still in progress, but I wanted to make sure that info was here as well.
