### ISSUE TITLE
"Script attached to Sphere in scene is missing" warning is generated when building example scenes

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9853]
## Describe the bug

On certain builds a "Script attached to Sphere in scene is missing" warning is generated. This issue occurs in Unity 2019 and Unity 2020 with OpenXR and XR SDK.

## Screenshots

![Image 5-21-21 at 10 27 AM](https://user-images.githubusercontent.com/65038391/119176461-fe695300-ba1f-11eb-9d43-152d66e632c0.jpg)

## Your setup (please complete the following information)

- Unity Version 2020.3.7f1 and 2019.4.25f1
- MRTK Version 2.7

## Additional Information
This warning appears on multiple platforms

**Comment by keveleigh** [comment]
I'm pretty sure I've seen this in non-iOS builds as well. I don't think it's an MRTK issue, since I couldn't find anything in the scene named "Sphere".

**Comment by elbuhofantasma** [comment]
I am seeing this in other non-iOS builds as well. I am changing this issue to remove the iOS specific info.

**Comment by davidkline-ms** [comment]
@elbuhofantasma, what is the specific scene that is being built? Is this a batch build?

**Comment by polar-kev** [comment]
> @elbuhofantasma, what is the specific scene that is being built? Is this a batch build?

Friendly ping on this @elbuhofantasma.

**Comment by keveleigh** [comment]
Going to close this out as external and not something Unity's likely to fix, as they've moved on to OpenXR.
