### ISSUE TITLE
"Script attached to _PlaneThatCallsIntoPlugin in scene" warning is generated when building for iOS

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9855]
## Describe the bug

On every build for iOS the "Script attached to _PlaneThatCallsIntoPlugin in scene" warning is generated. This issue occurs in Unity 2019 and Unity 2020 with OpenXR and XR SDK.

## Screenshots

![Image 5-21-21 at 10 27 AM (1)](https://user-images.githubusercontent.com/65038391/119183582-214c3500-ba29-11eb-8312-46bb1cb1f89c.jpg)

## Your setup (please complete the following information)

- Unity Version 2019.4.25f1 and 2020.3.7f1
- MRTK Version 2.7

## Target platform (please complete the following information)

- iOS
- OpenXR
- XR SDK

**Comment by davidkline-ms** [comment]
does not impact the ability to build/properly run the application. moving to 2.x future.

**Comment by Ahriana** [comment]
i have this same issue, however im not building for iOS, i get this warning for all targets for PlaneThatCallsIntoPlugin and Sphere neither of which are apart of my scene so im not sure why this error has started showing up all of a sudden

![image](https://user-images.githubusercontent.com/28003629/130509117-c094351e-9bf0-48d1-bc9d-fec0bffb197f.png)

**Comment by keveleigh** [comment]
While it's not super clear to me initially where these objects are coming from, I'm not aware of anything we do in MRTK to create these objects. It might be worth filing a Unity bug or posting on the Unity forums to try to resolve this.

**Comment by keveleigh** [comment]
Going to close this out as external and not something Unity's likely to fix, as they've moved on to OpenXR.
