### ISSUE TITLE
"Script attached to DefaultOpenXRCameraSettingsProfile is missing" warning is generated when building for iOS

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9856]
## Describe the bug

On every build for iOS a "Script attached to DefaultOpenXRCameraSettingsProfile is missing" warning is generated. This issue occurs in Unity 2019 and Unity 2020 with OpenXR and XR SDK.

## Screenshots

![Image 5-21-21 at 10 28 AM](https://user-images.githubusercontent.com/65038391/119186335-cfa5a980-ba2c-11eb-8c80-8c91bba7a77e.jpg)

## Your setup (please complete the following information)

- Unity Version 2019.4.25f1 and 2020.3.7f1
- MRTK Version 2.7

## Target platform (please complete the following information)

- iOS
- OpenXR
- XR SDK

**Comment by davidkline-ms** [comment]
does not impact the ability to build/properly run the application. moving to 2.x future.

**Comment by keveleigh** [comment]
Fixed via #9880
