### ISSUE TITLE
Oculus controllers not visualized without Oculus Integration package

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#9861]
## Describe the bug

This PR: #9589 makes it so that the Oculus controllers don't use the MRTK controller visualizations by default, since the Oculus Integration Package comes with it's own visualization. We need to have a visualization in the case that the Oculus Integration package is present.

## To reproduce

Deploy on Oculus without importing the Oculus integration package.

## Expected behavior

The normal gizmo controls are visible

**Comment by keveleigh** [comment]
Fixed by #9862
