### ISSUE TITLE
XR SDK Remoting moves MixedRealitySceneContent to random place

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#9867]
## Describe the bug

Using remoting causes MixedRealitySceneContent to be moved to a position with very large/small y value.

## To reproduce

1. Create a new Unity 2019.4.26 project
2. Switch to UWP platform
3. Import the standard assets, foundation, extension and example UPM packages
4. In the configurator that pops up, choose xr sdk, follow the instructions
5. Update WinXR plugin from 2.7 to 2.8
6. Import hand interaction scene from the example package
7. Open that scene
8. Open the remote window, uncheck the auto connect box, enter ip address and manually connect
9. Enter play mode
10. See issue
![image](https://user-images.githubusercontent.com/68253937/119422902-e2cbaa00-bcb6-11eb-8f2f-f53f927ea101.png)

## Your setup (please complete the following information)

Environment: OS 10.0.19042, Unity 2019.4.26, Windows XR Plugin 2.8, VS 2019 16.9.6, HL2 OS 21H1 20346.1002
UPM package used: https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=18999&view=artifacts&pathAsName=false&type=publishedArtifacts

## Target platform (please complete the following information)
- HoloLens 2

**Comment by keveleigh** [comment]
Interesting...the MixedRealitySceneContent is marked as "align with head height", which means it should align with the camera on start-up. I wonder if the camera happens to be reporting some completely wrong position at the time we try to align? @RogPodge have you seen this?

**Comment by RogPodge** [comment]
I have not seen this errror though I imagine it's what's causing the bug... I'll investigate it as I start looking into XR SDK remoting
