### ISSUE TITLE
Hand mesh off OpenXR w/ non-identity playspace

### ISSUE THREAD

**Issue by fast-slow-still** [microsoft/MixedRealityToolkit-Unity#9873]
## Describe the bug

The hand meshes display in the incorrect position with OpenXR, when the playspace has a non-identity transform.

## To reproduce

1. Open HandInteractionExamples scene
2. Set the X position of the MixedRealityPlayspace object to 1 meter.
3. Build and deploy to HoloLens2, using OpenXR as the XR plugin.
4. Run application
5. You will start up one meter to the right of where you normally would, because of 1 meter offset to playspace. That's fine.
6. Look at your hand meshes (you might have to enable them). They won't be colocated with your hands.
7. Look to your left, there your hand meshes are, a meter left of where they should be.

## Expected behavior

Hand meshes colocated with hands.

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.3.8f1]
- MRTK Version [e.g. v2.7.0_preview]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
Fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9875
