### ISSUE TITLE
Unity crashes if the Mixed Reality portal isn't started

### ISSUE THREAD

**Issue by DDReaper** [Microsoft/MixedRealityToolkit-Unity#988]
Probably not an issue for the library itself but worth discussing with the Unity team.

If you open up MR scenes, like Boundary or MotionControllerTests, without the MR portal started.  Then Unity just dies.

Considering some titles may want to offer a non-VR experience with their apps/games, this could cause an issue.
Still testing to see if the issue happens with a built project or if it is just the Unity Editor.

**Comment by DDReaper** [comment]
Sadly confirmed, the same happens with a built project.
The behaviour on the desktop is slightly different however, the MR portal is automatically launched but if it doesn't start in time (especially when using the emulator) then the game crashes.

If the MR portal isn't running (at first), the "Win + Y" prompt comes up but using this has no effect.

**Comment by jessemcculloch** [comment]
@StephenHodgson - I think this is the same bug we were running into when testing the Teleport stuff.

I noticed if I remove the FadeScript from the MixedRealityCamera then I don't get the crash anymore, but i have not been able to determine what in the Fade Script is causing it

**Comment by DDReaper** [comment]
Found that Unity will also crash with MRToolkit projects if the platform is NOT set to Windows Universal.  E.G. If platform is Windows, editor crashes on start.

**Comment by DDReaper** [comment]
Seems to be mostly resolved and Unity are continuing to work on the problem.

**Comment by jessemcculloch** [comment]
I believe this is resolved in the 2017.2.0f2 MRTP fixes this

**Comment by StephenHodgson** [comment]
I'm going to peace this open until the branch is using the correct build.

**Comment by keveleigh** [comment]
Closed via #1050
