### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by Avinash0795** [microsoft/MixedRealityToolkit-Unity#9882]
## Describe the bug

Upon playing and stopping the developed Scene, the Interactable Script (in whichever Gameobjects attached) are not accessible in the inspector. Upon clicking the interactable script in the inspector window I get this Error:

**NullReferenceException: Object reference not set to an instance of an object
Microsoft.MixedReality.Toolkit.UI.Editor.InteractableInspector.TryGetInputActions (System.String[]& descriptionsArray) (at Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/InteractableInspector.cs:564)
Microsoft.MixedReality.Toolkit.UI.Editor.InteractableInspector.<OnInspectorGUI>g__InputActions|31_0 () (at Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/InteractableInspector.cs:88)
Microsoft.MixedReality.Toolkit.UI.Editor.InteractableInspector.OnInspectorGUI () (at Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/InteractableInspector.cs:82)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <8004fcc221b54f98ba547350ea71d812>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)**

## To reproduce

1. Go to 'Play Button'
2. Click on 'Play Button and stop the Game window'
3. Scroll down to 'Console'

## Expected behavior

I want to be able to access the interactable script to work further in my project. 

## Screenshots

![image](https://user-images.githubusercontent.com/70105576/119609954-bcae2300-bdf8-11eb-90ed-7fed8391be46.png)

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.4.10f1]
- MRTK Version [e.g. v2.5.3]

## Target platform (please complete the following information)

- HoloLens
**- HoloLens 2**
- WMR immersive
- OpenVR

## Additional context

- I am using the Unity Sample for Hololens 2 provided by the Vuforia Engine as my project demands Image Tracking. This sample provides the user with MRTK 2.5.3 package and the latest version of Vuforia. Therefore I didn't download the MRTK Package seperately.

**Comment by RogPodge** [comment]
After downloading and trying the Vuforia scene, it seems like that interactable is loaded in at runtime

In Editor:
![image](https://user-images.githubusercontent.com/39840334/121097959-bc733780-c7a9-11eb-89db-be97de9992a7.png)


At Runtime:
![image](https://user-images.githubusercontent.com/39840334/121098015-d6ad1580-c7a9-11eb-89f3-9aa3f1504a41.png)

Closing since there is not much we can do on our end regarding how Vuforia sets up it's sample scene. You can use our existing PressableButtonHololens2 prefabs to get an example of existing behavior, and use this reference page for more information about using the Interactable Component.

**Comment by keveleigh** [comment]
@RogPodge Do you think it's worth adding a null check wherever this is failing? Or is it better off being an obvious failure state?

**Comment by RogPodge** [comment]
Well the exact error seems to be raised because that piece of code in particular has a dependency on the presence of CoreServices.InputSystem. I'm not sure which part ultimately ended up null, but I can add a null check around raise a more relevant warning.
