### ISSUE TITLE
Scene Understanding Example - White intransparent background on HL2

### ISSUE THREAD

**Issue by fschmidmichels** [microsoft/MixedRealityToolkit-Unity#9884]
## Describe the bug

I'm having a white intransparent overlay while using the SceneUnderstandingExample-Scene from the Examples. See the screenshots. I expect the white to be transparent or see-trough to see my real room in the background. There are some small areas where I can see through, but I cannot say why. These "black" or see-through areas have nothing to do with the features in my (real) room.

## To reproduce

Create Unity Project in 2019.4.23f1
Feature Tool - MRTK 2.6.2 or 2.6.1
Import examples (SpatialAwareness first, there was a note about some requirements, then SceneUnderstanding)
Use Legacy XR (but I think I also tried the nex XR Plugin with the same problem)
Open SceneUnderstandingExample
Use Holographic Remoting or build and deploy the project with the active scene in build settings
--> White everywhere where it should be see-trough to reality

## Expected behavior

Demo Scene works without the white overlay stuff

## Screenshots

![20210526_171153_HoloLens](https://user-images.githubusercontent.com/64133200/119686126-4e904d00-be46-11eb-97fc-e0dc6de52376.jpg)
![20210526_171208_HoloLens](https://user-images.githubusercontent.com/64133200/119686131-4fc17a00-be46-11eb-8d2f-1ea77b0269c8.jpg)

## Your setup (please complete the following information)

- Unity Version 2019.4.23f1
- MRTK Version 2.6.1 or 2.6.2

## Target platform (please complete the following information)

- HoloLens 2

**Comment by MaxWang-MS** [comment]
Hi @fschmidmichels, Scene Understanding via Remoting is not supported at the time. My guess for the opaque background showing up is that you selected the should load from file option in the SU observer profile and the loaded sample data was shown on device during remoting. However I am not sure why that would happen on device. Can you try clicking on the clear scene button and then the update scene button and see if things work as expected? Just to set the expectation the white planes are expected but they should line up with the real world. If they do line up and you just do not like the materials you can switch them under the observer profile.

**Comment by MaxWang-MS** [comment]
Please reopen if you are still encountering this issue.
