### ISSUE TITLE
Holographic Remoting does not fail to connect to device gracefully on OpenXR

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9885]
## Describe the bug

When the user has configured the MRTK for Holographic Remoting but does not have their device running the Holographic Remoting app and presses the Play button, Unity and OpenXR will not handle the failure to connect gracefully. Unity will become unresponsive while the in-editor player is active, but the Play button will respond to being clicked while in this state so it is possible to restore Unity back to a responsive state. Upon the in-editor player stopping, 7 warnings and 1 error are generated for the OpenXR plugin. Their messages are in the screenshots below. This issue does not effect Unity 2019. This issue does effect Unity 2020 with OpenXR via UPM and .unitypackage packages. Eventually all opened Unity 2020 projects with OpenXR will crash after this issue is encountered. 

## To reproduce

1. Import the MRTK to Unity 2020 via UPM or .unitypackages
2. Configure MRKT for OpenXR 
3.  Configure Holographic Remoting for your HoloLens
4.  Keep your HoloLens powered off or do not load the Holographic Remoting app
4. Open any example scene and click the Play button
5. Watch Unity become unresponsive with the example scene running
6. Click the Play button to stop the in-editor player
7. Look at the Unity Console for warnings and error

## Warnings and Errors
**All warnings and error**
![image](https://user-images.githubusercontent.com/65038391/119701892-b4aaaf00-be09-11eb-820d-9a85635bc640.png)

**OpenXR Reprojection warning**
![image](https://user-images.githubusercontent.com/65038391/119701998-d2781400-be09-11eb-9c09-3f539c7d57dd.png)

**OpenXR mesh settings warnings**
![image](https://user-images.githubusercontent.com/65038391/119702070-e885d480-be09-11eb-8d27-9b73389b5366.png)
![image](https://user-images.githubusercontent.com/65038391/119702164-018e8580-be0a-11eb-8f2d-9a13896556a5.png)
![image](https://user-images.githubusercontent.com/65038391/119702209-0ce1b100-be0a-11eb-8a53-35f906de926d.png)

**Connection warning**
![image](https://user-images.githubusercontent.com/65038391/119702264-1e2abd80-be0a-11eb-8c87-86b61cb6f618.png)

**OpenXR Reprojection warning**
![image](https://user-images.githubusercontent.com/65038391/119702354-37cc0500-be0a-11eb-90ad-214336848361.png)

**Single line console output**
![image](https://user-images.githubusercontent.com/65038391/119702447-503c1f80-be0a-11eb-8d38-c2aa6bbd5322.png)

## Expected Behavior

![image](https://user-images.githubusercontent.com/65038391/119701532-4b2aa080-be09-11eb-948b-21d9fca64637.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.7f1
- MRTK Version 2.7
- OpenXR 0.9.5
- 
## Target platform (please complete the following information)

- UWP
- Holographic Remoting

## Additional Information
Let the in-editor player run for a few seconds in this state and the "Successful Restart" message will populate in the Unity Console as well.

**Comment by keveleigh** [comment]
This looks by-design to me. The remoting feature will continue to attempt to connect until you tell it not to. How would you prefer it to behave otherwise? @elbuhofantasma 

All the warnings are also by-design. The idea is that you call the API and it either succeeds or it doesn't depending on the OpenXR feature being supported. All these cases should have appropriate fallback behavior, with the logs being present to let you know specifically why it failed.

**Comment by keveleigh** [comment]
This has now been improved on the Mixed Reality OpenXR Plugin side. We now attempt a specific number of retries and then exit play mode automatically if unsuccessful.
