### ISSUE TITLE
Plan of Record: Adopt XR Interaction Toolkit as the foundation of MRTK v3

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#9888]
Currently (v2.x) the Mixed Reality Toolkit implements a collection of core systems that
provide, in part, a level of platform abstraction that enables developers to use their
choice of Unity (2018 LTS, 2019 LTS, 2020 LTS), XR platform (built-in XR, XR SDK, OpenXR)
and hardware.

With the creation of XR Interaction Toolkit (XRI), Unity now provides much of what the
MRTK v2.x built into our foundation (camera rig, input system with action mapping, teleport,
interactions, etc.).

While this effort will 100% result in some significant breaking changes from MRTK
v2.x -> v3, it will enable MRTK components to better be consumed individually in an
a la carte manner.

Part of our effort will be to create a porting / migration guide and tooling to ease
the speed bumps.

**Comment by adamhill** [comment]
I think taking this dependency is much better in the long run, despite the migration pain.

**Comment by eusebiu** [comment]
As a developer would also like to have:
- Backwards compatibility for v2.x projects - minor changes would be fine
- Well documented migration procedure

Otherwise, if the effort to migrate is too high, existing apps will stay on v2.x and only the new ones will be built on v3.
This is exactly what VRTK did (i.e. VRTK4 was completely different that VRTK3) and that's why I moved towards MRTK (that and Hololens2 support - I don't know if they added support for HL2, and I don't even care now).

But from my experience with MRTK, it is already using the Unity XR API. So, I would have to ask why is (or does) XRI better?

**Comment by anders-lundgren** [comment]
What would this mean for future versions of MRTK on Unreal (and potentially other engines)? I would much prefer MRTK to adopt a UI first, platform agnostic approach that would be somewhat easy to port across different game/rendering engines. Specifically, I'd like to see official support for a WebXR engine, Babylon JS would be a sensible choice I think: https://github.com/BabylonJS/Babylon.js/issues/4310

**Comment by davidkline-ms** [comment]
> @eusebiu  said.
> As a developer would also like to have:

> * Backwards compatibility for v2.x projects - minor changes would be fine

We are investigating a thin layer that would translate from the v2.x patterns to v3. We are early in the process and still have much to discover before committing.

> * Well documented migration procedure

That is 100% the plan.

> it is already using the Unity XR API. So, I would have to ask why is (or what ... does) XRI better?

The goal is to reduce the amount of platform abstraction work that the MRTK team would need to write, in favor of more innovation in Mixed Reality features and capabilities.

**Comment by davidkline-ms** [comment]
> @anders-lundgren asked
> What would this mean for future versions of MRTK on Unreal (and potentially other engines)?

Unreal, Unity, Babylon, etc. have different asset and scene formats as well as supported programming languages. That said, we are always looking for ways to unify our offerings.

One of the goals of moving to Unity's XRI is to focus more on features such as UX, layout, etc, that pose unique challenges in the Mixed Reality world. The more we are able to build upon the strengths of others, the more we can focus on these features and goals such as cross engine.

**Comment by ltwlf** [comment]
I vote for XR Interaction Toolkit (XRI), even it may be painful migrating, exactly for the reasons as described above.

**Comment by maxking7** [comment]
I vote XRI because it's nice and easy to get started so far as Unity dev is concerned.

**Comment by davidkline-ms** [comment]
Thanks to everyone for the feedback! The team made the call today (8/5/2021) to adopt XRI.

**Comment by ltwlf** [comment]
> Thanks to everyone for the feedback! The team made the call today (8/5/2021) to adopt XRI.

Great news!

**Comment by KReguieg** [comment]
Howdy y'all,

Great news indeed and thank you in general for the good and open work you provide! 💯 

Nevertheless, I have a question: Can a statement be made about where in this graph MRTK will be located?

![image](https://user-images.githubusercontent.com/6112303/144033796-33400353-31c1-49fb-8dc5-4f524a2e8e71.png)

**Comment by keveleigh** [comment]
> Howdy y'all,
> 
> Great news indeed and thank you in general for the good and open work you provide! 💯
> 
> Nevertheless, I have a question: Can a statement be made about where in this graph MRTK will be located?
> 
> ![image](https://user-images.githubusercontent.com/6112303/144033796-33400353-31c1-49fb-8dc5-4f524a2e8e71.png)
> 
> _source: https://blog.unity.com/technology/unity-xr-platform-updates_

I'd say it makes the most sense to me to put MRTK in the "Developer Tools" red layer with XR Interaction Toolkit and AR Foundation. We're building on both of those for v3, as well as building directly on some XR Subsystems (the blue area) where needed.

**Comment by keveleigh** [comment]
![giphy](https://user-images.githubusercontent.com/3580640/177828052-90fc362f-1faf-420c-8a6d-74adfe1209f1.gif)
