### ISSUE TITLE
MRTK 2.7 won't build for Android on OpenXR

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#9895]
## Describe the bug

With the Mixed Reality OpenXR Plugin package installed, MRTK won't build for Android anymore due to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9880. This is due to the MR package not being compatible with Android and thus not including its assembly.

**Comment by davidkline-ms** [comment]
Fixed by #9897
