### ISSUE TITLE
Examples Hub - Error: 'There should only be one AsyncCoroutineRunner in the scene'

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#9896]
## Describe the bug
In Unity editor, when you run MRTKExamplesHub.unity scene, it continuously prints out the error messages.
The scene works well without any problems.

![2021-05-26 17_24_18-Unity 2018 4 35f1 Personal -  PREVIEW PACKAGES IN USE  - MRTKExamplesHub unity -](https://user-images.githubusercontent.com/13754172/119747792-55b85a80-be48-11eb-856b-9ac5a52def5c.png)
![2021-05-26 17_24_36-Unity 2018 4 35f1 Personal -  PREVIEW PACKAGES IN USE  - MRTKExamplesHub unity -](https://user-images.githubusercontent.com/13754172/119747796-56e98780-be48-11eb-8bc7-31ba4eea1514.png)

## To reproduce
1. Open MRTKExamplesHub.unity scene
2. Hit Play.

## Your setup (please complete the following information)

- Unity Version 2018.4.35f1
- MRTK Version : 2.7.0_stabilization branch (5/25/2021, at b7c269432e02e931d2d6b1aa40d88fc73dfc7a60)

**Comment by cre8ivepark** [comment]
Even if I delete AsyncCoroutineRunner in the Hub root scene, it is automatically added when I hit Play.

![2021-05-26 17_39_04-Unity 2018 4 35f1MRTKExamplesHub unity -](https://user-images.githubusercontent.com/13754172/119748415-bbf1ad00-be49-11eb-8d4a-b082835bc4aa.png)

**Comment by davidkline-ms** [comment]
fixed by: #9898
