### ISSUE TITLE
Scene Understanding causes complier error during build time

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#9903]
## Describe the bug

Due to a change in LoaderHelpers Scene Understanding generate an error in build time when OpenXR is used.

`WindowsSceneUnderstanding\WindowsSceneUnderstandingObserver.cs(134,36): error CS0266: Cannot implicitly convert type 'bool?' to 'bool'. An explicit conversion exists (are you missing a cast?)`

**Comment by davidkline-ms** [comment]
fixed by 9904
