### ISSUE TITLE
Need way to access Observation Parent

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#9907]
## Describe the problem

Observers create GameObjects to represent their observations.  Since there can be many many observations, it's important to keep the hierarchy from getting too cluttered. To help with this, [IMixedRealitySpatialAwarenessSystem](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Assets/MRTK/Core/Interfaces/SpatialAwareness/IMixedRealitySpatialAwarenessSystem.cs) provides a method called `CreateSpatialAwarenessObservationParent`. This method creates a container for the Observer to put all of its observations into. 

**The problem:** There's no good way for code outside of the observer to gain access to this parent.

## Why is access to the parent needed?

When running in the editor there are times that access to the parent might be needed. For example, when `WindowsSceneUnderstandingObserver` loads a saved room, that room is loaded in a fixed orientation. The application may which to control this orientation. For example, it may be desirable to control which room of the saved scan the application starts in.

## Describe the solution you'd like

Ideally I would like to see all Observer interfaces include an `ObservationParent` property. This would be similar to the `IMixedRealitySpatialAwarenessSystem.SpatialAwarenessObjectParent` property, except it would be scoped to the individual observer.

## Describe alternatives you've considered

The only method I know to find the ObservationParent is to use `GameObject.Find` with a specific name at runtime.  This approach is slow and it's also fragile because it requires knowing the "magic string" name each observer uses. If the observer decides to use a different name, the application will break.

**Comment by MaxWang-MS** [comment]
After some investigation I believe you can call `CoreServices.SpatialAwarenessSystem.SpatialAwarenessObjectParent` to achieve the desired result. It's public so you should be able to call it from anywhere.

**Comment by davidkline-ms** [comment]
The suggestion from @MaxWang-MS will get you the top-most parent for ALL observers. Unfortunately, the observation parent for the individual observers is protected.

```
        /// <summary>
        /// The parent GameObject for all observed meshes to be placed under.
        /// </summary>
        protected virtual GameObject ObservedObjectParent => observedObjectParent != null ? observedObjectParent : (observedObjectParent = Service?.CreateSpatialAwarenessObservationParent(Name));
```

We should consider making this public in a future release.

**Comment by davidkline-ms** [comment]
Making this change would involve breaking interfaces. A workaround when talking to IMixedRealitySpatialAwarenessMeshObserver implementers would be to call

GameObject observationParent = observer.Meshes[0].GameObject.transform.parent.gameObject;

When talking to the scene understanding observer, Meshes[0] would be replaced with SceneObjects[0]

**Comment by jbienzms** [comment]
> The suggestion from @MaxWang-MS will get you the top-most parent for ALL observers. Unfortunately, the observation parent for the individual observers is protected.

Correct @davidkline-ms, the suggestion by @MaxWang-MS will give the top-level container for all observers. Not the container for a specific observer.

> A workaround when talking to IMixedRealitySpatialAwarenessMeshObserver implementers would be to call
> GameObject observationParent = observer.Meshes[0].GameObject.transform.parent.gameObject;

This approach is fragile for a few reasons:

1. Using this code it would not be possible to get access to the parent during app launch. This is because no surfaces have been observed at app launch.
2. This code will not work during an observer refresh. For example, SceneUnderstanding supports clearing the observer as well as manual triggering of an update. If the observer is cleared or if no manual update has been triggered, there will be no surface to obtain the parent from.
3. It is possible that an observer could choose to nest observation objects. For example, SceneUnderstanding might choose to group Plane and Mesh objects together for a single observation. Then, doing observer.SceneObjects[0].transform.parent would give you the _group_ object and not the observation root.

> Making this change would involve breaking interfaces.

Sadly, this is true. I wonder if `IMixedRealitySpatialAwarenessSystem` could have a new method called `GetSpatialAwarenessObservationParent` where you pass in the observer. I don't know how that would work, though, since the observers don't pass in themselves when the parent is created. They pass in a "magic string" that is not known publicly.

**Comment by davidkline-ms** [comment]
any addition to the interface is a breaking change. we can investigate an alternative mechanism for exposing this data, however.
