### ISSUE TITLE
OpenXR with Quest and other devices

### ISSUE THREAD

**Issue by ltwlf** [microsoft/MixedRealityToolkit-Unity#9919]
I just realized in the MRTK config splash that currently Quest is not supported (coming soon)
It seems there is not much missing. Far interaction/movement seems to work, but Pointers and Controllers/Hands are missing.
Would be glad to support here dev/documentation.

**Comment by RogPodge** [comment]
Hey there, can you give the Oculus Integration Package and MRTK version that you are using, we can use those to start investigating.

In the meantime, I would suggest using the Oculus XR plug-in provider rather than the OpenXR one, since the OpenXR plug-in does not support hand tracking on Quest quite yet.

![image](https://user-images.githubusercontent.com/39840334/120524860-6018ae00-c38c-11eb-8412-18f05a956c67.png)

**Comment by ltwlf** [comment]
Thanks @RogPodge - I tried it without the oculus integration. My understanding of openxr is that I don’t need the Integrations anymore, because openxr is the abstraction layer, do I? (When no native controllers are found, MRTK should use the default ones.

Regards hand tracking, I really hope Oculus will fix this soon.

In production I use MRTK 2.6 with oculus integration. Works like a charm :)

**Comment by RogPodge** [comment]
Yeah the current Oculus handtracking feature set is locked to the Oculus Integration package, we'll update our [documentation](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/supported-devices/oculus-quest-mrtk?view=mrtkunity-2021-01) when we learn of a more convenient way to get handtracking on the quest.

Closing this issue for now. Glad to help!

**Comment by Brend-Smits** [comment]
> Yeah the current Oculus handtracking feature set is locked to the Oculus Integration package, we'll update our [documentation](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/supported-devices/oculus-quest-mrtk?view=mrtkunity-2021-01) when we learn of a more convenient way to get handtracking on the quest.
> 
> Closing this issue for now. Glad to help!

Could you explain why this is locked to the Oculus Integration package? It would be very convenient to only be able to use MRTK instead of MRTK + Oculus...

**Comment by RogPodge** [comment]
It's an Oculus side constraint: https://developer.oculus.com/documentation/unity/unity-handtracking/?locale=en_US their hand tracking api's are currently only available via the OVRHand, which is a Oculus Integration Package specific API

**Comment by ltwlf** [comment]
And in my case the controllers didn’t work too. Of more concrete the models weren’t loaded. MRTK should show the default controllers. 
anyone can confirm this?

**Comment by keveleigh** [comment]
> Or more concrete the models weren’t loaded.

Is this referring to the RGB axis gizmos too? Or just the model that looks like the physical controller?
If the model that looks like the physical controller, this is expected, as only Windows Mixed Reality controllers support this OpenXR at the moment. If the other, that's definitely a bug!

**Comment by RogPodge** [comment]
We've also fixed a potential issue where the RGB axis wouldn't load when the Oculus Integration package wasn't imported, there should always be some sort of visualization when deploying to the Quest for Quest controllers now.
