### ISSUE TITLE
Occulsion shader doesn't compile in 2017.1.1p2

### ISSUE THREAD

**Issue by flarb** [Microsoft/MixedRealityToolkit-Unity#992]
Anyone notice that the Occlusion shader won't compile in 2017.1.p2? Maybe something went awry when I upgraded my project but I had to revert to 2017.1f1 to get it back to normal. After the upgraded it said the current CPU was not supported by this shader. I think it also wouldn't draw the wireframe shader--although that doesn't seem to throw any errors.

Had the same problem with a few shaders in the MRDesignLabs package.

**Comment by StephenHodgson** [comment]
I hadn't seen this issue at all. Try right clicking on the shaders that are giving you problems and reimport them to see if it solves the issue.
