### ISSUE TITLE
Dragging visual on disabled ManipulationHandler

### ISSUE THREAD

**Issue by qian256** [microsoft/MixedRealityToolkit-Unity#9921]
## Describe the bug

When a GameObject has a disabled ManipulationHandler, the pointer still shows "dragging" visual, although the object is not going to be dragged anywhere.

## To reproduce

1. Attach ManipulationHandler.cs to a mesh (e.g. a cube)
2. Disable the ManipulationHandler component
3. When dragging using one-hand far interaction, there is a curve showing the dragging manipulation.

## Expected behavior

There should be no curve, just a raycast cursor + line. The line should not be responding to drag manipulation, because the object is not responding to drag manipulation.

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.3.12f1]
- MRTK Version [e.g. v2.3]

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

The dragging visual will disppear when ManipulationHandler is removed, but not disabled.

**Comment by RogPodge** [comment]
We've replicated the issue and will take a look at it. Thanks for point this out!

**Comment by RogPodge** [comment]
Adding note here: the issue was caused by the disabled manipulation handler still claiming the focus of the far manipulator, even though it was disabled. The PR fixed this by making it so that disabled components could not longer steal the focus.
