### ISSUE TITLE
How to open word excel pdf. in app  (open edge web view in UWP)

### ISSUE THREAD

**Issue by dahaideyu** [microsoft/MixedRealityToolkit-Unity#9932]
## Describe the problem

I want to open word /excel /PDF  in my application. and can next page etc.
## Describe the solution you'd like

Unity ,there have a plugs  to open pdf .but open word in UWP

## Describe alternatives you've considered

 Option   can use edge in my app.

**Comment by MaxWang-MS** [comment]
Please take a look at the `LaunchUri` class in MRTK. It might also be helpful to look at `UnityEngine.WSA.Launcher`, the Unity class we used inside our class.

**Comment by dahaideyu** [comment]
> Please take a look at the `LaunchUri` class in MRTK. It might also be helpful to look at `UnityEngine.WSA.Launcher`, the Unity class we used inside our class.

please give me a simple . I find the class. but how to use this class open excel or pdf
