### ISSUE TITLE
BoundsControl Translation Handles have wrong colliders for some HandlePrefabs 

### ISSUE THREAD

**Issue by JSWorkspace1** [microsoft/MixedRealityToolkit-Unity#9946]
## Describe the bug

The grabbable colliders for the Translation Handles of the BoundsControl component are positioned wrong with some handle Prefabs.  As a result the handles cannot be grabbed as expected. 

As seen in the following Image the generated colliders are offcenter or even fully inside the object.

![BoundsControle](https://user-images.githubusercontent.com/23420842/121157780-1fb4a680-c84a-11eb-8979-2626fae1f30e.png)

## To reproduce

1. Create new Cube  and ad  the BoundsControl component 
2. Configure as seen in Image ( show Translation Handles for all axes; increase Handle size for better visibility) 
3. Set a Handle Prefab:   it only occurs for some prefabs. The simples one i found is the default cone create with the unity ProBuilder.

## Expected behavior
The translation handle colliders are center over the handles and can be adjusted with the Collider padding to fully contain them.
Alternatively colliders that are already attached to the handle Prefabs could be used for the translation. 

## Your setup (please complete the following information)

- Unity Version [2020.3Lts]
- MRTK Version [2.7]

## Target platform (please complete the following information)
- WMR immersive

**Comment by Zee2** [comment]
Hi, thanks for reporting this. I'll take a look into what could be causing this.

**Comment by Zee2** [comment]
@JSWorkspace1 #9973 is a partial fix for this issue. Handle colliders will still have issues with the Scale handles, but this ought to improve the behavior with the translation and rotation handles, which you've seen.

**Comment by Zee2** [comment]
@JSWorkspace1 #9973 is merged, can you take a look and see if this has resolved your issue?
