### ISSUE TITLE
Hololens 2 - OpenXR - Unity 2020.3.10f - Scene Understanding not working

### ISSUE THREAD

**Issue by DSprtn** [microsoft/MixedRealityToolkit-Unity#9958]
## Describe the bug

The official scene understanding example scene does not seem to be working in a release build no matter what configuration I try.

## To reproduce

Setup Unity project in v.2020.3.10f, with all newest MRTK packages with the OpenXR target.
Build example scene, deploy on Hololens 2.

## Expected behavior

Demo should function properly. Instead, no spatial understanding features seem to be working at all.

## Your setup (please complete the following information)

- Unity Version - 2020.3.10f
- MRTK Version - 2.6.1
- OpenXR plugin version - 0.9.2
- Scene understanding version - 0.6.0

## Target platform

- HoloLens 2
- OpenXR

**Comment by keveleigh** [comment]
> MRTK Version - 2.6.1

This should be fixed in our 2.7.0 release! @MaxWang-MS added support in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9744.

**Comment by DSprtn** [comment]
Great to hear! 

Is there any ETA on 2.7.0?

**Comment by keveleigh** [comment]
@DSprtn May 27th (so it's already out!)

The GitHub release is at https://github.com/microsoft/MixedRealityToolkit-Unity/releases/tag/v2.7.0
It can also be accessed via the Mixed Reality Feature Tool https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/welcome-to-mr-feature-tool (make sure to click refresh on the package list page if you've already used the tool!)

**Comment by MaxWang-MS** [comment]
@DSprtn Also please make sure to use the latest version of MR OpenXR plugin (currently 0.9.5/1.0.0-preview 1).

**Comment by DSprtn** [comment]
Ah gotcha, I just didn't refresh my packages. 😅

That's kind of a confusing thing to make the user do though, to be honest. 
Should it not refresh by itself every time it's started up?

**Comment by MaxWang-MS** [comment]
We decided to by default not refresh but we will revisit the decision soon. Closing the issue as it has been resolved.
