### ISSUE TITLE
Reload keyword in speech input handler

### ISSUE THREAD

**Issue by cybergoulion** [Microsoft/MixedRealityToolkit-Unity#996]
As it is, when the speech input source keywords are changed, the changes are not reflected in the speech input handler, as the list is updated only once in OnEnable(). One simple solution is to just create a button to reload them as needed. 
I did that and it looks like the screenshot bellow. It works ok. If there is no better solution I could create a pull request with the changes.
![image](https://user-images.githubusercontent.com/24978515/30670448-024fd09a-9e6b-11e7-9954-13cb3aad5130.png)

**Comment by StephenHodgson** [comment]
@cybergoulion please submit a PR, thanks.

**Comment by cybergoulion** [comment]
Yes, probably. I will try this tomorrow and submit a PR with a solution either way.

**Comment by cybergoulion** [comment]
@StephenHodgson I moved the code in OnIspectorGUI after all. Seems to work fine and needs no extra action to update now.

**Comment by StephenHodgson** [comment]
Awesome!
