### ISSUE TITLE
Scene Observer in Scene Understanding doesn't work in Unity Play Mode

### ISSUE THREAD

**Issue by c11epm** [microsoft/MixedRealityToolkit-Unity#9960]
## Describe the bug

When initializing the SceneObserver in Unity Play Mode the `SceneObserver.IsSupported()` returns false and the try to Compute a scene freezes the Unity Editor indefinitely (Kill process to close and restart) if the IsSupported status is not checked.

## To reproduce

Set up a Scene with a script running the code from the Scene Understanding SDK page: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/scene-understanding-sdk

`if (!SceneObserver.IsSupported())
            {
                // Handle the error
                Debug.Log("Scene Observer not supported");
                return;
            }

            // This call should grant the access we need.
            await SceneObserver.RequestAccessAsync();`
Watch it return false in Unity Play Mode and crash the program if you try to compute a scene anyway:
`// Create Query settings for the scene update
SceneQuerySettings querySettings;

// Compute a scene but serialized as a byte array
SceneBuffer newSceneBuffer = SceneObserver.ComputeSerializedAsync(querySettings, 10.0f).GetAwaiter().GetResult();

// If we want to use it immediately we can de-serialize the scene ourselves
byte[] newSceneData = new byte[newSceneBuffer.Size];
newSceneBuffer.GetData(newSceneData);
Scene mySceneDeSerialized = Scene.Deserialize(newSceneData);`

## Expected behavior

According to the documentation this should work since it doesn't say it wouldn't. 

## Your setup (please complete the following information)
- Unity 2019.4.22f
- MRTK 2.7.0
- Scene Understanding 0.6.0

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

Is this a bug or miss in the documentation? Should this work in Unity Play Mode or not? To my understanding this should work since the documentation refers to the "Initialization from Data (also known as. the PC Path)" but I could be wrong.

It would be very convenient to have it work in the Play Mode for quick testing purposes. 

Anyone with some ideas?

**Comment by MaxWang-MS** [comment]
Scene Understanding should work with in editor play mode (non remoting). The documentation you referred applies to the situation when you are not using MRTK. If you are using MRTK please look [here](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/spatial-awareness/scene-understanding). With MRTK you would not need to use the code you mentioned but you can use the MRTK observer to control the behavior (see DemoSceneUnderstandingController).

**Comment by c11epm** [comment]
Hi, Thanks for the answer. I started some testing with the base form the example you refers to. Wasn't sure if it was a bug or documentation thingy, thanks for clearing that up!
