### ISSUE TITLE
About integrating and using speech recognition and transcription

### ISSUE THREAD

**Issue by kinaco17** [microsoft/MixedRealityToolkit-Unity#9962]
Hi.

I have done the tutorial at the following URL.
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mrlearning-speechsdk-ch1
When I deploy to HoloLens2, I only get "select a mode to begin." when I press the microphone button, and cannot input voice.

When I use playmode on unity, voice input is possible.

Unlike the tutorial, I have set the Configration to DefaultHoloLens2Configuration.
 (This is because the app cannot be operated without that setting...)
If the configuration setting is wrong, how do I set the DefaultHoloLens2Configuration?

If the problem is something else, what is wrong?

Thank you very much for your help.

**Comment by RogPodge** [comment]
It seems odd to me that the recognition service works on your computer and not on the Hololens device itself. MRTK doesn't directly reference any AzureSpeechServices code, so I'm not sure if there's something weird happening on our end, though I did notice that the tutorial  requests you to clone the default profile and change the start behavior.

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mrlearning-speechsdk-ch1#configuring-the-speech-commands-start-behavior

**Comment by RogPodge** [comment]
@mr0ng perhaps you have a bit more context around this?

**Comment by mr0ng** [comment]
I'll check with the team and get back to you.

**Comment by veeruby-developer** [comment]
Hey @kinaco17  can you please confirm you have set up the Unity project to publish the Azure Speech plugins for ARM64 described in this part of the [Tutorial](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mrlearning-speechsdk-ch1#importing-the-tutorial-assets) after importing the tutorial assets.
and also what is the MRTK version, Unity Version using..?

**Comment by kinaco17** [comment]
Thank you all for your help.

I installed and ran the packages listed in the tutorial.

MRTK version is 2.6.1
The version of unity is 2019.4.24f1

**Comment by veeruby-developer** [comment]
> When I deploy, do I set the configuration to Master and the platform to ARM64? If that's what you mean, then yes.
not this. I'm referring to the Azure Speech plugins for ARM64 as in the below screenshot.
![image](https://user-images.githubusercontent.com/61759322/121860557-96541700-cd16-11eb-911f-d6b7258c1c87.png)

please also ensure that you have enabled Microphone in the capabilities section of the player settings.
![image](https://user-images.githubusercontent.com/61759322/121860816-dc10df80-cd16-11eb-8ea3-b5f005978d23.png)

**Comment by kinaco17** [comment]
I guess I was missing a setting there.
I fixed it and it works now.
Thank you so much!
