### ISSUE TITLE
ه

### ISSUE THREAD

**Issue by mwwm1** [microsoft/MixedRealityToolkit-Unity#9966]
## Your setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by RogPodge** [comment]
A mistakenly generated/empty issue. @davidkline-ms do you know who might have permissions to delete this?
