### ISSUE TITLE
Overview of available IconTextureNames missing

### ISSUE THREAD

**Issue by janick187** [microsoft/MixedRealityToolkit-Unity#9969]
## Describe the issue
I am trying to update the icon of a button with the help of ButtonConfigHelper.SetQuadIconByName(String).
However, I do not know the Texture Name of the new icon. 
E.g. I want to update the button with the 'refresh' icon. But I don't know the Texture Name of this icon.

## Feature area
In the documentation the different Texture Names of default icons are not included.

## Existing doc link
https://docs.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.toolkit.ui.buttonconfighelper.setquadiconbyname?view=mixed-reality-toolkit-unity-2020-dotnet-2.7.0#definition

**Comment by RogPodge** [comment]
The texture names refer to the names of the icons in the icon set:
![image](https://user-images.githubusercontent.com/39840334/121959724-ff895980-cd19-11eb-9515-c27ca17ae301.png)

![image](https://user-images.githubusercontent.com/39840334/121959750-0a43ee80-cd1a-11eb-9d19-20b6cfc1fbd1.png)

We realize that these aren't easily surfaced within the button config helper, and will let users toggle the icon names within the button config inspector

**Comment by RogPodge** [comment]
Updated as follows in the PR: 
![image](https://user-images.githubusercontent.com/39840334/121963508-0cf51280-cd1f-11eb-97f9-17f2476cb387.png)
