### ISSUE TITLE
IActiveBuildTargetChanged could not be found

### ISSUE THREAD

**Issue by XiaohuanIT** [Microsoft/MixedRealityToolkit-Unity#997]
I download the source from the MixedRealityToolkit-Unity. And I open the project by Unity 5.6.3p2 (64-bit). When I try to export package in Asset, it show error "Assets/Holokit/Utilities/Scripts/Editor/AutoConfigureMenu.cs(14,38):error CS0246: the type or name 'IActiveBuildTargetChanged' could not be found. Are you missing an assembly  #reference?"
![1](https://user-images.githubusercontent.com/13150803/30675695-85d36eba-9eb4-11e7-98a4-ff584607ef8a.png)

**Comment by StephenHodgson** [comment]
I've already addressed this in a recent PR #975
