### ISSUE TITLE
New profile creation does not work properly

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#9979]
## Describe the bug

Currently if you attempt to create a new profile a null pointer exception may appear and the inspector window becomes unusable.

Separately, after clicking copy and customize button for an existing profile the settings remained grey out.

## To reproduce

Steps to reproduce bug 1:
(You need to follow the steps exactly)
1. Create an empty scene
2. Add to scene and configure
3. Click on the MRTK gameobject, in the inspector select the input tab, and then click on Create new profiles
4. In the new profile created, switch to the boundary tab
5. See error

Steps to reproduce bug 2:

1. Create an empty scene
2. Add to scene and configure
3. Click on the MRTK gameobject, in the inspector click on Copy & Customize
4. See the error of newly created clone profile being greyed out

## Expected behavior

The exception should not appear.
The settings should not be greyed out after cloning.

## Screenshots

Bug 1: Exception
![image](https://user-images.githubusercontent.com/68253937/122103249-42573a00-cdcb-11eb-900d-e122171d894a.png)

Bug 2: Greyed out problem
![image](https://user-images.githubusercontent.com/68253937/122102666-8564dd80-cdca-11eb-86d3-436e7c8de02f.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.11f1
- MRTK main branch (9b61acf667)

## Target platform (please complete the following information)

- Editor

**Comment by davidkline-ms** [comment]
This issue could potentially warrant a 2.7.1 as it is a pretty significant regression.

**Comment by RogPodge** [comment]
The second bug seems to be due to the inspector not refereshing, if you click on the profile asset itself, the sections become ungreyed out and that gets reflected in the original toolkit's inspector

As for the first bug, it seems to be because of the inspector code trying to render before the settings profile gets initialized. I'll post a patch for this later today hopefully.

**Comment by MaxWang-MS** [comment]
@RogPodge Could you maybe add a refresh call for bug 2?

**Comment by RogPodge** [comment]
I think it already is trying to do a refresh (everything works fine in previous unity version), it may be a different API for Unity 2020, trying to fix it.
