### ISSUE TITLE
HoloToolkit menu not added to Unity after importing v1.2017.1.1 package

### ISSUE THREAD

**Issue by hicotech** [Microsoft/MixedRealityToolkit-Unity#999]
After importing newest unity package (HoloToolkit-Unity-v1.2017.1.1) new menu item is not added and there is a error in console saying:
> Assets/HoloToolkit/Utilities/Scripts/Editor/AutoConfigureMenu.cs(14,38): error CS0246: The type or namespace name `IActiveBuildTargetChanged' could not be found. Are you missing an assembly reference?

It looks like there is a "bug" in _AutoConfigureMenu.cs_.
Class AutoConfigureMenu is defined as **IActiveBuildTargetChanged**, but in previous versions (e.g.: HoloToolkit-Unity-v1.5.8.0) it was defined as MonoBehaviour.

Reproducible every time with new Unity project, after HoloToolkit-Unity-v1.2017.1.1.unitypackage package file is imported. Downloaded from https://github.com/Microsoft/MixedRealityToolkit-Unity/releases

**Comment by StephenHodgson** [comment]
What version of the unity editor are you using?

**Comment by hicotech** [comment]
Ok my bad.. I overlooked that it works only in newest Unity.
I tried it with 5.6.1f1
