### ISSUE TITLE
OpenXR HoloLens 2 remoting generates error and warning

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#9993]
## Describe the bug

Cherry picking #9954 caused new error and warning to show up during OpenXR remoting.

## Screenshots

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/68253937/122454696-8465b480-cf60-11eb-8587-a737ccf127cf.png)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/68253937/122454735-8af42c00-cf60-11eb-8666-9ca732f24374.png)

## Your setup (please complete the following information)

- Unity 2020.3.11f1
- MRTK 2.7.1 branch

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
Fixed via #9994
