### ISSUE TITLE
HP Reverb G2 Controller Prefab - OpenXR

### ISSUE THREAD

**Issue by MiPa12** [microsoft/MixedRealityToolkit-Unity#9997]
Hi @keveleigh, I installed MRTK 2.7 + Open XR 0.9.5 + Inputs using MixedRealityFeatureTool + Unity Version 2020.3.11. I also enabled the HP Reverb G2 Controller Profile in the OpenXR Settings. Everything is working fine except the rendering of the HP Reverb G2 controllers. In my case it is just rendering the hand model (RiggedHandLeft, RiggedHandRight). Are there HP Reverb G2 Controller prefabs or how can I render the controllers in unity? Or do I have the wrong settings? Thanks.

I'm reffering to this discussion:
https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/9071

![Screenshot (22)](https://user-images.githubusercontent.com/61323363/122545926-b2192f00-d02e-11eb-80f8-559e9e62218d.png)

![Screenshot (24)](https://user-images.githubusercontent.com/61323363/122546004-cc530d00-d02e-11eb-9388-bd29d0038b5b.png)

**Comment by sebstax7** [comment]
@MiPa12   Do you have any interactable object in your scene? If not just add a cube with "object manipulator" script and "near interectable" script.
In your player settings, "XR plug in management", check OPENXR and then windows mixed reality feature set box appears, check the box.

**Comment by keveleigh** [comment]
There's currently a bug in MRTK regarding the fact that OpenXR providers both controller input _and_ hand joint representations when using a controller. MRTK currently assumes only hands will provide hand joint representations.

I'm working on a fix this week. We're also tracking this via https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9849

As a workaround for your setup, you can uncheck "Hand Tracking" to only get controller input and the controller model:

![image](https://user-images.githubusercontent.com/3580640/123690594-65410f80-d809-11eb-83cd-85e8ba82f89b.png)

**Comment by MiPa12** [comment]
@keveleigh thanks.

This solved the problem.  I confirm controllers works fine. Prefab is visible and I also can interact with objects.

![Screenshot (59)](https://user-images.githubusercontent.com/61323363/124242982-9b3e0680-db1d-11eb-9d14-00337616f441.png)
